### ISSUE TITLE
[question] How to handle multiple libraries in multiple applications 

### ISSUE THREAD

**Issue by marcosteffan** [conan-io/conan#10001]
We have a lot of in-house build libraries (libA, libB, libC), each of them in their own repo and each of them available as conan-package. These libraries have dependencies to each other, as well as dependencies to some 3rd-party libraries (lets call them 3rdpartyA, 3rdpartyB). Then we develop multiple applications (appA, appB) which in turn make use of these libraries (the in-house ones as well as 3rd-party).

That results in a diagram like:
![Copy of Unbenanntes Diagramm](https://user-images.githubusercontent.com/24871864/141283726-fd350a07-47bf-4552-9859-129717fe0369.png)

What I would like to achieve is a structure in which every library is just present in a single version:

![simplified](https://user-images.githubusercontent.com/24871864/141283962-0db99216-e78b-4d68-ba68-fd7db93c0333.png)

We know that the upper approach will work too, but since we are supposed to deliver small-as-possible products to our customers, we need to drop everything which is not absolutely required. The effort to update all libraries to fit the desired version-set is acceptable!

The questions are: 

- How can we provide a set of versions for 3rdparty, and in-house libs which shall be used by all of these libraries and apps? I am thinking of a centralized definition of versions. Is there some mechanism in conan which provides something like this?
- Does this make any sense to you, or are we probably missing something else?
- The probably most obvious solution to simply communicate to our developers "use libA 0.0.1, libB1.2.3,..." is not an option ;-)

Any feedback is appreciated!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @marcosteffan 

I think if you want a consistent, unique versions dependency graph, it could be as simple as providing a single "project" conanfile that does a ``requires`` to both ``appA/1.2.3`` and ``appB/5.0.0``. The moment those applications belong to the same dependency graph, with the same common root, by default they will be requiring the same versions of the upstream dependencies, or they will conflict. 

This conanfile.txt can be routinely built by CI to raise these issues, in fact it is a good thing for CI, because you can do full efficient (build only what needs to be built, based on the package_id modes, etc) builds using that common conanfile.

Please tell me if you think it could make sense for your use case.

**Comment by marcosteffan** [comment]
Hi,
that sounds like a very good idea to check at least if there are conflicting packages - which is also very important and will be a first step that we'll take! 
I could use that information to dig into the libraries and "solve" these conflicts manually by setting the appropriate versions.

But I would prefer to provide library-versions somewhere else (and that is the question if that is possible with conan built-ins) and that all of libraries and apps take their dependency-versions from there.

That version-info might be present like:
3rdpartyA:0.0.5
3rdpartyB:1.2.3
3rdpartyC:5.0.0
libA:4.3.1
libB:0.2.0
libC:0.4.2
libD:0.2.0

Then, i.e. libD (which depends on libA, libB, libC) gets the versions of its dependencies from that version-info instead of hardcoded conanfile.py.

**Comment by memsharded** [comment]
That might be doable in different ways, let me throw some ideas:

- the ``conandata.yml`` file is a place to put information that recipes automatically load. You can put there data, and use ``self.conan_data`` in your ``requirements()`` method, for example, to avoid writing it in the conanfile.py
- But the ``conandata.yml`` is per-recipe, not a centralized place.
- You can do in your ``requirements()`` method pretty much what you want. You can be reading a text file from somewhere, and getting the information you want from there. Something like:

```python
class Pkg(ConanFile):
    _my_requires = "liba", "libb"

    def requirements(self):
          # get some handle to that global versions file
          versions = json.loads(load(versions_file))
          for r in self._my_requires:
               v = versions["r"]
               self.requires("{}/{}".format(r, v))
```


However, I am not sure that the global file approach is the best one, and that it won't bite you later in different forms. The idea is that a given package version builds against some other dependencies versions (possibly in a valid API range). If some of the dependencies versions change, then it is necessary to do changes to your own source code, resulting in your own new version. But then recipes (and developers), basically lose all control over the current version, because it is fixed by the file?

Another possible approach that you can do is use ``overrides``. Lets say you define the downstream consumer ``conanfile.py``, that requires both applications. You could define there all the dependencies ``override=True``, to force upstream the versions that you want. These versions could be defined as well in a text/json/yaml file. However this has the problem that it only works when building form such consumer conanfile, when you are building the individual packages, they will still use their defined versions.



Some other hints:

- Start using lowercase package names asap, Conan 2.0 will use lowercase only (already approved by the Tribe 2.0)

**Comment by marcosteffan** [comment]
>  If some of the dependencies versions change, then it is necessary to do changes to your own source code, resulting in your own new version

Yes, we have that in mind an can go with that effort.

> But then recipes (and developers), basically lose all control over the current version, because it is fixed by the file?

Exactly! Sure, that means that developers loose some amount of freedom, but for the overall-product it gets clearer.

> Another possible approach that you can do is use overrides

I was just reading the documentation about overrides. That could actually be an option, even if the dependency-management is then built up top-down - but that is fine. Browsing through our libraries I have found lots of dependencies marked with private=True. Is the assumption correct that overrides do not work on these?

**Comment by memsharded** [comment]
> I was just reading the documentation about overrides. That could actually be an option, even if the dependency-management is then built up top-down - but that is fine. Browsing through our libraries I have found lots of dependencies marked with private=True. Is the assumption correct that overrides do not work on these?

Yes, "private" dependencies are basically invisible, because otherwise they will be overriden by normal requires and cause unexpected conflicts that most likely the "private" qualifier was trying to avoid in the first place. Conan 2.0 will come with some improvements over the dependencies model, it is likely that you will not need that amount of privates (because privates should be only used in some excepcional cases).

**Comment by marcosteffan** [comment]
I'm pretty sure that these privates are a mixture of lack of knowledge and in the other case an attempt to hide dependency-conflicts... we'll get that straight!

However, thanks for the suggestions!

I think we will start by removing all non-required private=True and see where it gets by using override=True from the apps then. That should be a good starting point to get versions clean from bottom up. I'm thinking of a repo which keeps all versions in a conandata.yml which gets fetched in each library...

**Comment by memsharded** [comment]
>  That should be a good starting point to get versions clean from bottom up. I'm thinking of a repo which keeps all versions in a conandata.yml which gets fetched in each library...

Ok, just one recommendation if you are trying this way: if you add the whole conandata.yml to every package, when something, anything, any version changes in the global conandata.yml, that will induce a new revision of all the recipes, even if they didn't change at all.

You might be interested in the ConanCenter hook (https://github.com/conan-io/hooks/blob/master/hooks/conan-center.py) that we are using to prune the conandata.yml to the versions that are being processed, dropping the others from the copy. With that approach, you can obtain the same revisions of packages whose dependencies didn't change.
