### ISSUE TITLE
Manage dependencies under development

### ISSUE THREAD

**Issue by melak47** [conan-io/conan#1001]
Is there a workflow that supports working on multiple projects - say an application and some of its library dependencies - at the same time?

E.g. I want to add some feature to `myapp`, and need to add some other feature to `mylib` to support that.
Can I tell conan to use a locally checked out `mylib` repo instead of a cached version/release?

Ideally, I'd also like to have some way to make `conan install` clone `mylib` for development (e.g. in source), but that may be out of scope and better suited to an external script.

**Comment by memsharded** [comment]
It is not something provided by conan out of the box, the normal flow would be mainly to work with one component, if you need to modify one of its dependencies, you can open it and modify locally. If you meant that, all the package creating, testing and consuming can be done locally, no need to upload anything to any server. But not simultnaeously in the user space, but as package. A typical flow could be:

1. git clone my_pkg #the one I want to work with
2. conan install  #to get its dependencies
3. edit, modify, start working, realize you need changes in lib1 dependency
4. git clone lib1 # cloning the package recipe
5. conan install #dependencies of lib1
6. Modify, build, debug locally.
7. conan test_package #when everything is good, create the package locally
8. go back to my_pkg
9. Might need to do "conan install" depending if it is an inmmediate dependency or intermediate dependencies need to be rebuilt
10. re-build or re-link my_pkg

This would be a modular, escalable approach, in which, if the componetization is well designed, is not that common to be editing dependencies at the same time. And if it is necessary, it is not as convenient as having all the dependencies in the same solution/project opened for edition at the same time, but good enough and robust (most likely everything will go fine in CI).

Said that, depending on the build system, it can be configured to develop locally several packages at once. Right now I am trying to create a proof of concept with CMake, using cmake-install, and cmake find_package(). I will let you know if I get something.

**Comment by petermbauer** [comment]
Any news on that? Unfortunately the separation between the modules/packages in corporate eco-systems is often quite bad so it would be great to have the possibility to work on multiple packages without the need to export and install. I was wondering if a CMake-based solution would be possible, basically include the CMakeLists.txt of the repsective dependency instead of using find_package or having it in the CONAN_LIBS variable.

**Comment by memsharded** [comment]
Certainly, conan is very hackable, so as long as the build system allows to do it, it can be configured to work with multiple packages opened at the same time. The only issue is that we haven't found so far a common usage pattern, as every team does things differently, so we haven't found a way to develop useful tools or flows.

So if you still want to figure out something, just as some tips, if you are using CMake, you could for example consider the following:

- Use CMake install syntax so it is not necessary to implement the ``package()`` method:

```python
class SayConan(ConanFile):
    name = "say"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    exports_sources = "*"

    def build(self):
        cmake = CMake(self.settings)
        install = '-DCMAKE_INSTALL_PREFIX="%s"' % self.package_folder
        self.run('cmake %s %s %s' % (self.conanfile_directory, cmake.command_line, install))
        self.run("cmake --build . --target install %s" % cmake.build_config)
```

- Then, use the ``CONAN_EXPORTED`` flag in the package CMakeLists.txt to copy package artifacts to the normal place (the ``package_folder`` in the conan local cache), or to an ``output`` folder in the project:

```cmake
set(LIB_NAME say)

ADD_LIBRARY(${LIB_NAME} STATIC ${LIB_NAME}.cpp)

if(CONAN_EXPORTED)
        install(TARGETS ${LIB_NAME}
                LIBRARY DESTINATION lib
                ARCHIVE DESTINATION lib)

        install(FILES Find${LIB_NAME}.cmake
                DESTINATION /)

        install(FILES ${LIB_NAME}.h
                DESTINATION include)  
else()
        set(INSTALL_DIR ${CMAKE_BINARY_DIR}/output/${LIB_NAME})
        install(TARGETS ${LIB_NAME}
                LIBRARY DESTINATION ${INSTALL_DIR}/lib
                ARCHIVE DESTINATION ${INSTALL_DIR}/lib)

        install(FILES Find${LIB_NAME}.cmake
                DESTINATION ${INSTALL_DIR}/)

        install(FILES ${LIB_NAME}.h
                DESTINATION ${INSTALL_DIR}/include)
endif()
```

Note that packages will be using their own Find.cmake files inside the package.

Then, have a project root CMakeLists.txt in which you could point the ``${CONAN_CMAKE_MODULE_PATH}`` variable to your local project ``${CMAKE_BINARY_DIR}/output/${LIB_NAME}`` folder (or add any possibly open dependency package).

In this way, if one of the project dependencies, is opened for edition, its output artifacts will go to the local ``output`` folder, the Find.cmake file will also be found there, that points to the binaries in the project instead of those in the conan local cache.

Maybe, other approaches could be valid too, like using scopes, and defining the scope "open" for packages, so if that scope is set to a certain path, it will use that as a package folder instead of the local cache one. Just thinking loud, not sure about details.

It is true that these approaches require active edition of the packages, but it is because it is not obvious to design a flow that will fit for most users. I suggest revisiting this issue again, this release is already full, but for the next one, and to study it again and look for possible improvements, if we could come up with something.

**Comment by tsondergaard** [comment]
I believe "conan editable" and "conan workspace" are features related to this question.

https://docs.conan.io/en/latest/developing_packages/editable_packages.html
https://docs.conan.io/en/latest/developing_packages/workspaces.html

**Comment by memsharded** [comment]
Hi @tsondergaard 

yes, as an update: 
- Editable packages have been improved and a lot of work put onto them, with the new ``layout()`` method
- Workspace feature is complicated, and has been put on stand-by for a long time now. Not very recommended for production, it has been removed in Conan 2.0 at the moment. Recommended to use your own script to automate a project using the "editables" feature.
