### ISSUE TITLE
[bug] Conanfile with conditional requirement with "conan install .. --require-override"

### ISSUE THREAD

**Issue by zawlin** [conan-io/conan#10045]
### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu18
  * Compiler+version:  
  * Conan version: 1.40.4
  * Python version: 3.8.11

### Steps to reproduce (Include if Applicable)
I encountered this while packaging opencv with optional cuda. The conanfile has the following:
```python
    options = {"with_cuda":[True,False]}
    default_options = {"with_cuda":True}
    def requirements(self):
        if self.options.with_cuda:
            self.requires('cuda/[>=10.1 <=11.4.2]')
```
`conan install  ..  --require-override="cuda/10.1"` fails with
```
ERROR: conanfile.py (opencv/4.5.3): Error in requirements() method, line 47
        self.requires('cuda/[>=10.1 <=11.4.2]')
        ConanException: Duplicated requirement cuda/10.1 != cuda/[>=10.1 <=11.4.2]
```
`conan create  ..  --require-override="cuda/10.1"` works successfully.

As a workaround the following works:

```
        if self.options.with_cuda:
            # workaround for conan bug
            if 'cuda' in self.requires:
                req = self.requires['cuda']
                del self.requires['cuda']
                self.requires(str(req))
            else:
                self.requires('cuda/[>=10.1 <=11.4.2]')
```
However, a simpler check fails to install cuda, even though there is an entry in `self.requires`
```
            if 'cuda' not in self.requires:
                self.requires('cuda/[>=10.1 <=11.4.2]')
```

**Comment by memsharded** [comment]
Hi @zawlin 

Managed to reproduce in a test, and doing a potential fix in https://github.com/conan-io/conan/pull/10046. However, it is not clear the risk of breaking.

The fact is that ``--require-override`` was created to override transitive dependencies when creating and building packages in the cache. The ``conan install . --require-override`` doesn't fall in this category, because you can directly change the ``conanfile.py`` easily to test the dependency version that you want. 

lets see how the PR moves, thanks for reporting!

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/10046 was closed without merging. The unknowns were many, and the final approach will be using lockfiles, as introduced in https://github.com/conan-io/conan/pull/10713 for 2.0-alpha.6. Cli args for overrides will be removed in 2.0 then.
