### ISSUE TITLE
Manifest option show path when relative

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1005]
When in a `my_package/test_package/build/xxxxxxxx` directory, I want to generate a manifest in the `my_package/manifests/` directory, but if I give it the correct relative path of `../../../manifests`, it actually puts it somewhere else (it ends up relative to the conanfile location).

I have to add `$PWD`, as in:

        conan install ../.. --build=never -m $PWD/../../../manifests
to get it to generate manifests in the correct directory.

**Comment by memsharded** [comment]
I think we decided to do it relative to the conanfile, because it seemed more intuitive when playing a bit with it, as it is something associated to the conanfile, not to the location from which the install is executed. So it reads, this conanfile, who declares this dependencies, have this manifests in the manifest folder. 

Also it had some problems and it was much more convenient to people using different build folder layouts, all of them have to store the manifests in the same location, so they had to issue a different relative path regarding the build folder, which was temporary and could be located anywhere, so it made more sense to use the relative to the conanfile.

So if you want ``my_package/manifests`` wouldn't it be the default one when your don't provide an argument?

**Comment by tamboril** [comment]
Actually `.conan_manifests`, but yes.  It works if I give it an argument of `-m ./manifests`.  It just is unexpected from a command line user that a relative directory path is relative to something implicit rather than the current working directory.  Maybe an informational message saying where the manifests were created, if an argument to `-m` was given, would be helpful.

**Comment by memsharded** [comment]
Ok, I see your point, yes, it makes sense printing the output path of the manifest. Let's leave the issue open then, as an enhancement.

**Comment by luckielordie** [comment]
Can you assign me to this task please? I'd like to tackle it as a first contribution. Thanks.

**Comment by memsharded** [comment]
Hi @luckielordie 

No problem. I am assigning it to myself, because github doesn't allow to assign to non owners, but I will wait until your contribution and manage your PR. Don't forget to add to contributors.txt if you want to add your personal details (github lists contributors anyway)

Thanks!
