### ISSUE TITLE
[bug] Workspaces do not work correctly when defining layout method

### ISSUE THREAD

**Issue by ziish** [conan-io/conan#10050]
### Environment Details (include every applicable attribute)
  * Operating System+version: `Ubuntu 21.04`
  * Conan version: `Conan version 1.42.0` 

### Steps to reproduce (Include if Applicable)

I have created a small example repository [here](https://github.com/physhh/conan-monorepo) which can be used to reproduce the behavior. The repository contains two projects with two separated conanfiles. In both conanfiles the `layout` method is used to describe the package which makes it possible to use `AutoPackager`. So far so good - I can can build both packages as expected and the package layout looks exactly how I want. 

Now I want to create a conan workspace for both packages. There is a [script](https://github.com/physhh/conan-monorepo/blob/5f70f4f334d874a8bf58c1bd5c1135bc25ef9f99/workspace/generate.sh) in the workspace subdirectory which shows how I try to generate the workspace. When I execute the script the build files (`conan_paths.cmake` and so on) are put in the root directories of the projects (`hello` and `world`) and I do not know why. According to the [layout definition](https://github.com/physhh/conan-monorepo/blob/5f70f4f334d874a8bf58c1bd5c1135bc25ef9f99/hello/conanfile.py#L23) there should be a build directory. 

This happens as soon as the `layout` method is defined. I think it has something to do with [this special case](https://github.com/conan-io/conan/blob/bcf385540876373ad36001c9bc70ec171fc7cd59/conans/client/installer.py#L465-L486) defined in conan?

**Comment by ziish** [comment]
Just a small update. This is not a fix but with those two hacks it would build:
```
diff --git a/conans/client/installer.py b/conans/client/installer.py
index cbbf0361..dbb754ca 100644
--- a/conans/client/installer.py
+++ b/conans/client/installer.py
@@ -472,7 +472,7 @@ class BinaryInstaller(object):
             output = conanfile.output
             output.info("Rewriting files of editable package "
                         "'{}' at '{}'".format(conanfile.name, conanfile.generators_folder))
-            self._generator_manager.write_generators(conanfile, conanfile.install_folder,
+            self._generator_manager.write_generators(conanfile, conanfile.build_folder,
                                                      conanfile.generators_folder, output)
             write_toolchain(conanfile, conanfile.generators_folder, output)
             output.info("Generated toolchain")
diff --git a/conans/model/workspace.py b/conans/model/workspace.py
index 708a96c8..5b6d1de8 100644
--- a/conans/model/workspace.py
+++ b/conans/model/workspace.py
@@ -76,6 +76,9 @@ class Workspace(object):
 
                 conanfile = node.conanfile
                 src = build = None
+
+                src= node.conanfile.folders.source_folder
+                build = node.conanfile.folders.build_folder
                 if editable:
                     build = editable.folder(ref, EditableLayout.BUILD_FOLDER, conanfile.settings,
                                             conanfile.options)
```

With this the separate layout file is not used at all. Can anyone give me some heads up how it is supposed to work? Maybe I can provide an actual fix.

**Comment by memsharded** [comment]
Hi @physhh 

The "workspace" feature is not expected to work with the new ``layout()`` and new editables flow. We decided that a whole new approach was necessary first on the foundation of the package layout and editables, and that is the reason we did that effort and the new ``layout()`` was developed. We think it is a massive improvement over the initial version of the editables.

But the ``workspace`` has been put on hold since then, and it is not being maintained. We have even removed the ``workspace`` command in the ``develop2`` branch for Conan 2.0. We prefer to have solid building blocks like good "editables" than half-baked features like the ``workspace``. At the moment it is not a top priority, because it is possible to get very far with editables (see for example a demo in this meetup video: https://youtu.be/VzUJQw89U7o?t=2498, where setting up a VS solution for Debug & Release for 2 packages in editable mode only takes a few minutes).

**Comment by ziish** [comment]
Hey @memsharded - Thanks for the info. 
I have a use case in which a bunch (10+) of packages are developed at the same time. Editable packages would probably work but imho still takes too much time to setup. That said, I guess I can just create a cmake superbuild on my own.

**Comment by memsharded** [comment]
> I have a use case in which a bunch (10+) of packages are developed at the same time. Editable packages would probably work but imho still takes too much time to setup. That said, I guess I can just create a cmake superbuild on my own.

This is more or less what I am suggesting. If editables work robustly and easily with the ``layout()``, setting up a large project with multiple editables as you like it can probably be done more easily with a custom script (cmake, python, or whatever) than trying to make the current ``workspace`` feature to do what you want at this moment. We will eventually resume work on workspaces, most likely right after 2.0 because not a very high priority now, but at the moment, this is at least what I would try.

**Comment by memsharded** [comment]
Hi @ziish 

Workspaces are been introduced back in Conan 2.10: https://docs.conan.io/2/incubating.html

I am closing this ticket as solved, but please create new tickets for any further question or issue. Thanks very much for the feedback!
