### ISSUE TITLE
Package options printed as python objects, not string values

### ISSUE THREAD

**Issue by Manu343726** [conan-io/conan#1008]
Since the last release conan fails to configure one of my packages, which defines a set of package options as follows:

``` python
 options = {
'stack_walking_unwind': [True, False],
'stack_walking_backtrace': [True, False],
'stack_details_auto_detect': [True, False],
'stack_details_backtrace_symbol': [True, False],
'stack_details_dw': [True, False],
'stack_details_bfd': [True, False],
'shared': [True, False]
}
```

When runing `conan install`, cmake configuration fails with the following error:

```
backward/0.0.0@Manu343726/testing: Copying sources to build folder
backward/0.0.0@Manu343726/testing: Generated cmake created conanbuildinfo.cmake

backward/0.0.0@Manu343726/testing: ERROR: Package 'a6331343afb457a1b4a3515575800fc11b6b9af8' build failed
backward/0.0.0@Manu343726/testing: WARN: Build folder /home/manu343726/.conan/data/backward/0.0.0/Manu343726/testing/build/a6331343afb457a1b4a3515575800fc11b6b9af8
ERROR: backward: Error 256 while executing cmake /home/manu343726/.conan/data/backward/0.0.0/Manu343726/testing/build/a6331343afb457a1b4a3515575800fc11b6b9af8 -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release  -DCONAN_EXPORTED=1 -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="6.2" -DCONAN_CXX_FLAGS=-m64 -DCONAN_SHARED_LINKER_FLAGS=-m64 -DCONAN_C_FLAGS=-m64 -DCONAN_LIBCXX="libstdc++" -Wno-dev -DSTACK_WALKING_UNWIND=<conans.model.options.PackageOptionValues object at 0x7fef9ede4610>-DSTACK_WALKING_BACKTRACE=<conans.model.options.PackageOptionValues object at 0x7fef9ede4a90>-DSTACK_DETAILS_AUTO_DETECT=<conans.model.options.PackageOptionValues object at 0x7fef9ede4bd0>-DSTACK_DETAILS_BACKTRACE_SYMBOL=<conans.model.options.PackageOptionValues object at 0x7fef9ede41d0>-DSTACK_DETAILS_DW=<conans.model.options.PackageOptionValues object at 0x7fef9ede43d0>-DSTACK_DETAILS_BFD=<conans.model.options.PackageOptionValues object at 0x7fef9ede4050>-DBACKWARD_SHARED=<conans.model.options.PackageOptionValues object at 0x7fef9ede4250> -DBACKWARD_TESTS=OFF
-- Configuring incomplete, errors occurred!
```

Here's the complete [conanfile](https://github.com/bombela/backward-cpp/blob/master/conanfile.py) just for reference.

**Comment by memsharded** [comment]
``self.options[pkg_name]`` is the intended way to access the options of the dependencies, not your own options. The way to access your own package options would be: ``self.options.myoption``, or if dynamically: ``getattr(self.options, myoption)``

It is truth that a big refactor has been done, and it happened that your way of getting the value of the options accidentally worked, because it was first getting the nested set of options for ``myoption``, then forcing its conversion to string, and as it didn't have any nested options, it happened to match the parent option name. But practically, some lucky coincidence. As you can see, it was a bit of mess, this is why we did this refactor, very necessary, sorry if your build was broken. Please use the ``getattr`` syntax.

**Comment by Manu343726** [comment]
Thanks for the feedback, it is fixed now.
