### ISSUE TITLE
[question] How to ensure repeatability of our builds in the long term ? Dealing with breaking changes in recipes

### ISSUE THREAD

**Issue by aurelienrb** [conan-io/conan#10133]
Hello,

Recently , the CMake target name for the [gtest recipe](https://github.com/conan-io/conan-center-index/pull/7894) has been changed from `gtest` to `GTest`. As a result, our build suddently failed to pass because `CONAN_PKG::gtest` is no longer valid, and must be updated to `CONAN_PKG::GTest`.

To me, the issue here is that while the recipe itself has changed, the version of the package has not. So one day `gtest/1.11.0` means something, and the day after it means something else. This is quite weak to ensure build repeatability in the long term.

Regardless of where the recipe is being hosted (conan center or a custom remote), what is the recommended strategy for dealing with breaking changes that need to be introduced in a recipe ? How to ensure backward compatibility with legacy builds ?

Thanks for your help 😃 

PS: the need here is to be able to rebuild an old software version from its git tag that can be several years old

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by eigenwhat** [comment]
I believe this was a bug in the `cmake` generator which was erroneously taking the `cmake_target_name` property into account. It was patched in `1.42.1`. The targets produced should always be `CONAN_PKG::<package name>`.

**Comment by eigenwhat** [comment]
As for how you can avoid that sort of random change, you can either make sure revisions are enabled and pin each dependency to a particular recipe revision in your conanfile or [use lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles.html).

**Comment by aurelienrb** [comment]
Thanks for the answer, indeed it's likely to be the issue you mention because once we updated conan everything went back to normal 🎉 

Thanks also for pointing the lockfiles. I'm aware of this feature, but - correct if I'm wrong - it does not solve the problem of a breaking change done on the recipe file itself.

The thing I'm not aware is how are managed the changes done to a recipe on the Conan Center? To me, it seems that while we always asked for the same package `gtest/1.11.0` we didn't always get the same recipe associated to it. After a change was committed to its main recipe, it was applied to existing packages that used to be associated to the legacy recipe - thus altering them. This is what puzzles me.

Did I missed something? How to explain that an existing versioned package was altered after its publication?

**Comment by eigenwhat** [comment]
[Recipes have their own revision IDs](https://docs.conan.io/en/latest/versioning/revisions.html), and if you have revisions enabled in your Conan configuration it should record which revision was pulled when the lockfile was written, and ensure only that revision of the recipe is used (and not a newer one). You can similarly specify a revision in your `conanfile.txt` or `.py` for a given dependency, for example `gtest/1.11.0@#<revision-id>`.

As for how recipes are updated, it's all managed in the https://github.com/conan-io/conan-center-index project. Recipes are frequently updated to support the latest features in Conan, improve configurability and compatibility, and fix bugs in the recipe itself. The exact logic is a bit more detailed, but basically if you request a package and you don't have a matching one locally pre-built, and don't otherwise specify a recipe revision, it'll fetch the latest one from the remote. It'll also do so if you pass `--update` when running `conan install`.

If you want to prevent getting any potentially breaking recipe updates from ConanCenter, you have to tell Conan to stick with a particular recipe revision using any of the available methods or stop using ConanCenter directly and manage recipes yourself with a private remote. You could then, for example, copy over known working recipes from the aforementioned GitHub and rehost yourself.

**Comment by aurelienrb** [comment]
Thank you @eigenwhat  for all this clarification. I'm happy to learn about this revision ID mechanism: this is exactly what I was hopping for.

I've started to mirror our dependencies from Conan Center into our own local Artifactory + Gitlab self hosted. So far it's going well.

Have a nice day !
