### ISSUE TITLE
Ancestor's PATH component is repeated in PATH in activate.sh

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1015]
For the `virtualenv` generator, I'm seeing the path that I append to `env_info` in a distant ancestor repeated in the `PATH=` variable set in the generated `activate.sh` a number of times equal to that ancestor's `requires()` distance from the ultimately installed package.

If my package requires C that requires B  that requires A, then the `PATH` I set up in A is repeated four times in `activate.sh` if I install C.

I only append it once in the `package_info(self)` method of the ancestor.

Is this known, or is there something I might be doing wrong?

**Comment by lasote** [comment]
Definitely not an expected behavior. We have this PR #1006 pending to merge. We have refactored the whole env/virtualenv system. Today I'm going to release a development version (pypi package) of the 0.20 release (planned for next Monday), would be nice if you can try it and tell me if it works well. 

I'll write you when I release it.
Thanks

**Comment by lasote** [comment]
Hi! 
You can (please help us :rofl: ) to try the release candidate installing with `pip install conan==0.20.0rc1`
Please tell me if it still fail or it's ok now.

Thanks!

**Comment by gasuketsu** [comment]
Hi, currently trying 0.20.0rc1 and found that env val `PATH` definition in `activate.sh` generated in consumer package gets increased like below by performing `conan install` for consumer package.
(in this example, `package_info()` in recipe for `Protobuf/2.6.1@gasuketsu/testing`  appends path to package bin directory)

```activate.sh
PATH="/home/tharada/.conan/data/Protobuf/2.6.1/gasuketsu/testing/package/81a2fd4ff2b1309c415a72710e1b7fcb494ee7e6/bin":"/home/tharada/.conan/data/Protobuf/2.6.1/gasuketsu/testing/package/81a2fd4ff2b1309c415a72710e1b7fcb494ee7e6/bin":"/home/tharada/.conan/data/Protobuf/2.6.1/gasuketsu/testing/package/81a2fd4ff2b1309c415a72710e1b7fcb494ee7e6/bin":"/home/tharada/.conan/data/Protobuf/2.6.1/gasuketsu/testing/package/81a2fd4ff2b1309c415a72710e1b7fcb494ee7e6/bin":"/home/tharada/.conan/data/Protobuf/2.6.1/gasuketsu/testing/package/81a2fd4ff2b1309c415a72710e1b7fcb494ee7e6/bin":"/home/tharada/.conan/data/Protobuf/2.6.1/gasuketsu/testing/package/81a2fd4ff2b1309c415a72710e1b7fcb494ee7e6/bin":"/home/tharada/.conan/data/Protobuf/2.6.1/gasuketsu/testing/package/81a2fd4ff2b1309c415a72710e1b7fcb494ee7e6/bin":"/home/tharada/.conan/data/Protobuf/2.6.1/gasuketsu/testing/package/81a2fd4ff2b1309c415a72710e1b7fcb494ee7e6/bin":"/home/tharada/.conan/data/Protobuf/2.6.1/gasuketsu/testing/package/81a2fd4ff2b1309c415a72710e1b7fcb494ee7e6/bin":"/home/tharada/.conan/data/Protobuf/2.6.1/gasuketsu/testing/package/81a2fd4ff2b1309c415a72710e1b7fcb494ee7e6/bin":$PATH
export PATH
```

**Comment by memsharded** [comment]
Hi @gasuketsu ,
I have been trying to replicate this without success. A couple of questions:
- It is just a 1 level dependency graph? i.e. does this happens if you just depend on Protobuf and nothing else?
- Is it produced when you execute several ``conan install`` one after the other?
If you please could clarify with exact steps to reproduce the issue, I would like to have a look, lets try to solve it for the release. Thanks!

**Comment by gasuketsu** [comment]
Hi @memsharded ,

> It is just a 1 level dependency graph? i.e. does this happens if you just depend on Protobuf and nothing else?

I was verifying env variables are applied as expected with your [conan-protobuf](https://github.com/memsharded/conan-protobuf) repository plus small change below, and the issue is observed when performing `conan install` under test_package.  So level dependency graph should be 2. (zlib <- Protobuf <- test_package)

```diff
tharada@xubuntu:~/repos/memsharded/conan-protobuf/test_package$ git diff
diff --git a/conanfile.py b/conanfile.py
index d23e28b..079d00b 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -103,3 +103,4 @@ class ProtobufConan(ConanFile):
             self.cpp_info.libs = ["libprotobuf.a"] if not self.options.shared else ["libprotobuf.9.dylib"]
         else:
             self.cpp_info.libs = ["protobuf"]
+            self.env_info.path.append(os.path.join(self.package_folder, "lib"))
diff --git a/test_package/conanfile.py b/test_package/conanfile.py
index 5255065..f050c1c 100644
--- a/test_package/conanfile.py
+++ b/test_package/conanfile.py
@@ -5,7 +5,7 @@ import os
 class ProtobufTestConan(ConanFile):
     settings = "os", "compiler", "build_type", "arch"
     requires = "Protobuf/2.6.1@memsharded/testing"
-    generators = "cmake"
+    generators = "cmake", "virtualenv", "virtualbuildenv"
 
     def build(self):
         self.run('%s ../../message.proto --proto_path=../.. --cpp_out="."'
```

> Is it produced when you execute several conan install one after the other?
> If you please could clarify with exact steps to reproduce the issue, I would like to have a look, lets try to solve it for the release. Thanks!

Procedure to reproduce the issue is;
1. clone conan-protobuf and apply above patch
2. perform `conan export` under `conan-protobuf`
3. perform `conan install under `conan-protobuf/test_package` several times

env val PATH in `activate.sh` will grow up per number of times you did step 3

**Comment by memsharded** [comment]
Great, thanks very much for the details, I'll work on it later, cheers!

**Comment by memsharded** [comment]
Been able to reproduce it. This is what happens:

- Env values are dumped and cached in ``conaninfo.txt`` file
- ``conaninfo`` is loaded at each command, to get the cached values.
- Env variables that execute an ``append`` add them again while running ``conan install`` for second time.

In the final env-values dict, the strings are not exactly the same, even if they look the same, one is unicode with forward slash, and the other is str with double backward slash (at least in Win-py27). 

Not sure how to address this issue, it is important for @lasote to have a look too. This has not happened before, because other cached values are not cumulative/appendeable:
- It doesn't seem good to just don't cache env vars values. All the other info from ``conan install`` is cached. Conan commands as build, package, etc, need it.
- Maybe overwriting the ``append()`` so it doesn't add already existing values?

Any other ideas?

Thanks @tamboril  and @gasuketsu for your help!
