### ISSUE TITLE
[bug] CMakeToolchain does not include cpp_info.builddirs from build requirements in CMAKE_PREFIX_PATH CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#10167]
When using CMakeToolchain, `cpp_info.builddirs` from all requirements are being added correctly to `CMAKE_PREFIX_PATH` and to `CMAKE_PREFIX_PATH`, However cpp_info.builddirs from **build_requirements** are ignored.

This is problematic, as you could have a conan package that only contains cmake modules, like [extra-cmake-modules](https://conan.io/center/extra-cmake-modules), this package is a conan `build_requirements` and it's `cpp_info.builddirs` should be added `CMAKE_PREFIX_PATH` and `CMAKE_PREFIX_PATH` as well!

### Environment Details (include every applicable attribute)
  * Operating System+version: windows 10
  * Compiler+version: msvc
  * Conan version: 1.41.0
  * Python version: 3.7

**Comment by memsharded** [comment]
It seems it make sense to add ``builddirs`` for ``build_requires`` too, I have verified only ``host`` requirements are added atm to ``CMakeToolchain`` paths.

We need to think what happens with dual build-host requirements (like protobuf being both in build and host context), what would be the priority, and the mechanism to use one or the other, this is not a bug per se, but a feature to implement.

Will check with the team to see what could make sense.

**Comment by SpaceIm** [comment]
I think you should consider removing root package folder from `builddirs` by default (see https://github.com/conan-io/conan/issues/9427#issuecomment-993685376), otherwise it will be a mess for cross-build if `builddirs` of build requirements are added to `CMAKE_PREFIX_PATH`.

But actually for `extra-cmake-modules`, you want to add `build_paths` of build requirements in `CMAKE_MODULE_PATH`, not `CMAKE_PREFIX_PATH`.

**Comment by SpaceIm** [comment]
You can try with these changes https://github.com/conan-io/conan/pull/10186
