### ISSUE TITLE
`conan get package/version@user/channel conan_export.tgz` retrieves broken file

### ISSUE THREAD

**Issue by tvogel** [conan-io/conan#10172]
When using the above command to retrieve the `conan_export.tgz`, I receive a file that is too short and is not recognized as a tar.gz file.

```
> conan get -r my-remote -raw package/version@user/channel conan_export.tgz | file -
/dev/stdin: Applesoft BASIC program data, first line number 8
> conan get -r my-remote -raw package/version@user/channel conan_export.tgz | wc -c
1105
```
While retrieving the file from the artifactory web UI, I get
```
> file conan_export.tgz 
conan_export.tgz: gzip compressed data, was "conan_export.tgz", max compression, original size modulo 2^32 20480
> wc -l conan_export.tgz
1870 conan_export.tgz
```

Taking a brief look at the `hexdump -C` from both, all characters >= 0x80 are just stripped out! 
some characters

Wow, I guess, you should remove the 7bit-filter with `-raw`! Or in general when `get`ing files?

Current version:
```
> conan -v
Conan version 1.43.0
```

**Comment by memsharded** [comment]
This ``conan get`` utility was never meant to download or copy files, just as a convenience to quickly inspect text files like ``conanfile.py`` or ``conaninfo.txt`` mostly for debugging purposes (I wouldn't recommend to use it in production). Furthermore, the ``conan_export.tgz`` file is an internal, undocumented storage format, which is not guaranteed to be kept stable or available in the same way.

I am not sure about the ``conan get`` survival in conan 2.0, it might be replaced by some other more generic cache paths utility or something, lets see what makes sense for the future of this command.

**Comment by tvogel** [comment]
Is there another way to retrieve files from a repo?

Anyway, the last line here is the culprit:
```    
def get_recipe_path(self, ref, path):
        url = self.router.recipe_snapshot(ref)
        files = self._get_file_list_json(url)
        if self._is_dir(path, files):
            return self._list_dir_contents(path, files)
        else:
            url = self.router.recipe_file(ref, path)
            cache = (ref.revision != DEFAULT_REVISION_V1)
            content = self._get_remote_file_contents(url, use_cache=cache)
            return decode_text(content)
```
One should only decode downloaded files that are known to be text - not everything. With the generality of this method and also, `conan_export.tgz` of course being listed by the directory listing, it feels like an error to do unwarranted utf-8 decodes on binary data.

**Comment by memsharded** [comment]
>  Is there another way to retrieve files from a repo?

If you want to get files from a package, you have different mechanisms:

- Use ``imports`` to copy the files that you want (like dlls only, for example), from packages you list as requirements. You can write for example a simple ``conanfile`` with only ``requires`` and ``imports`` and do a ``conan install .`` it
- Use ``deploy()`` to copy the files that you want for that package and its dependencies (not only dependencies, like ``imports``)
- Use the ``-g deploy`` generator to get a copy of the whole dependency graph packages into your local folder.


> One should only decode downloaded files that are known to be text - not everything. With the generality of this method and also, conan_export.tgz of course being listed by the directory listing, it feels like an error to do unwarranted utf-8 decodes on binary data.

That is the thing. With cache layout changes, the ``.tgz`` files will no longer be under the path that is referenced by ``conan get <ref>``, so it will not be listed at all, and will remain as an internal implementation detail (as it already is, just it becomes somehow visible because some legacy cache structure).

**Comment by tvogel** [comment]
Well, if `conan get <reference> .` is supposed to list files in that package - and it does, one should be able to retrieve those files. Everything else is a surprise.

About my use case: It is really just about having a quick way to peek into some text files (patch files, or the qtmodules.conf for the Qt package). The implementation detail that the exports are stored in an archive indeed is not what I am interested in. I would find if way more convenient to retrieve those files directly for inspection.

But of course: If there were binary files in the exported files, I wouldn't want those to get text-decoded either!

**Comment by memsharded** [comment]
> Well, if conan get <reference> . is supposed to list files in that package - and it does, one should be able to retrieve those files. Everything else is a surprise.

Yes, but the files will be ``conanfile.py``, ``conanmanifest.txt``, ``myfile.h``, or ``mylib.dll``. The ``.tgz`` is an internal transfer and storage in server thing, it is not documented, not intended for external usage or manipulation by users. 
For example:

```bash
conan install zlib/1.2.11@
conan get zlib/1.2.11@ .
Listing directory '.':
 conandata.yml
 conanfile.py
 conanmanifest.txt
```

The ``.tgz`` is not even there, because it is stored in a different location in the cache (not accessible). The fact that the ``.tgz`` is visible in the server side (which server, Artifactory?) is a server implementation detail that can be changed at any time.

**Comment by memsharded** [comment]
> About my use case: It is really just about having a quick way to peek into some text files (patch files, or the qtmodules.conf for the Qt package). The implementation detail that the exports are stored in an archive indeed is not what I am interested in. I would find if way more convenient to retrieve those files directly for inspection.

I see, doing that against the server directly might be challenging. Checking in the uncompressed format locally in the cache after ``conan install`` is probably better. If not, and using Artifactory, the API is quite rich and powerful, maybe it is possible to directly do some command to get inside a ``tgz`` (I know at least the Web UI can navigate easily inside tgz files)

**Comment by ghost** [comment]
I was facing the same problem today and found out that there are also differences between getting files from the Conan cache on my local PC and getting them from a remote. Files like `conandata.yml` are not downloadable from an Artifactory remote but are available in the cache.

I think that this is a design decision and that is fine but should be mentioned in the documentation of the `get` command.

My workaround would be to do a
`conan download --recipe -r my_remote my_package/2.0.0@user/channel`
and then a
`conan get --raw my_package/2.0.0@user/channel conandata.yml`
(at least until the `get` option is removed).

**Comment by AbrilRBS** [comment]
Closing as no longer relevant in Conan 2, where the `conan get` command has been dropped :)
