### ISSUE TITLE
[question] How to set cppstd of dependent packages from conanfile.py?

### ISSUE THREAD

**Issue by gouriano** [conan-io/conan#10187]
Hi

The problem is that my package requires C++17, but it depends on GRPC (grpc/1.39.) which fails to build with C++17 (It builds fine with C++14).
I can create conanfile.txt:

    [requires]
    grpc/1.39.1

and install requirements:

    conan install . -s grpc:compiler.cppstd=14

it works, no problem.
My question is how to do the same in conanfile.py, that is in my package recipe?

**Comment by memsharded** [comment]
Hi @gouriano 

No, it is not possible to define dependencies settings from consumer recipes. The reason is that we already have the same feature implemented for ``options`` and it is quite challenging to maintain, but also confusing for users. Such in-recipe definition of options can cause for example configuration conflicts in the dependency graph (not only version conflicts, but also different options values), which also require a mechanism to be solved (and that is option overriding). They are difficult to understand the priorities when they are both defined in recipes as ``default_options``, in recipes in the ``configure()`` method, and in profiles (also because there are some not great current defaults). And finally, they are also a bit challenging to maintain at scale, because the definitions are scattered along a dependency graph, and it becomes a burden to debug and understand who is defining which option value in the graph.

So we will not do the same for settings, it is not worth. The key is that you shouldn't define that value in the command line, the recommended approach for production is to use your own ``profile`` files, in which you can put that ``grcp::compiler.cppstd=14`` setting and forget about it too. Using your own profiles is also recommended over the auto-detected profile, which shouldn't be used for production.

**Comment by gouriano** [comment]
Understood. Once so, I have another question. 
Consider a theoretical possibility of me submitting  my package to Conan center. Is it possible to submit it with such custom profile?

**Comment by memsharded** [comment]
> Consider a theoretical possibility of me submitting my package to Conan center. Is it possible to submit it with such custom profile?

Not at the moment. ConanCenter is only building packages with the default compiler version cppstd profile. So at the moment recipes that need a higher cppstd might be just defining it directly in their builds (hardcoded, but not coming from the Conan model). That kind of works so far (so you are mostly good to do that if you plan to submit it soon to ConanCenter), but we are working to try to provide a better compatibility model for cppstd that would allow a better management of the cppstd setting at scale in ConanCenter.

**Comment by gouriano** [comment]
Understood. Thanks
