### ISSUE TITLE
[question] Is there a way to freeze dependency recipe revisions into the recipe upon export?

### ISSUE THREAD

**Issue by tmatheson-arm** [conan-io/conan#10189]
Here's a demonstration of the problem I'm having while trying to set up CI:

```sh
# Create a consumer -> dependency chain
conan new dependency/1.0 --bare
conan create .

conan new consumer/1.0 --bare
echo "    requires = [('dependency/[>=1.0]', 'private')]" >> conanfile.py
conan create .

# Create a new version of dependency
conan new dependency/2.0 --bare
conan create .

# It is no longer possible to install consumer from a binary
conan install consumer/1.0@
```

The `conan install` command fails with `ERROR: Missing prebuilt package for 'consumer/1.0'` because the package ID for the prebuilt binary is based on `dependency/1.0`. The recipe includes a version range which is re-evaluated using `dependency/2.0` and therefore the package would need to be rebuilt from source.

What I would like is a way to bake the resolved dependencies (version numbers and recipe revisions) into the exported recipe, similar to how the `scm` attribute with `revision: auto` will bake the SCM hash into the exported recipe. Then the `conan install` command above would know to fetch the recipe for `dependency/1.0` and therefore find the existing package. Is there a way to accomplish this?

This example uses version ranges, but the same thing happens when using an alias package which is updated over time, or creating new recipe revisions of dependencies.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @tmatheson-arm 

Automatically baking the resolved dependencies into the recipe is not possible at the moment. But you can try to use lockfiles to obtain a snapshot of the dependency graph, and use it later to achieve the same build. Please check https://docs.conan.io/en/latest/versioning/lockfiles.html. At the moment they are a bit complicated, but we have already simplified them a lot for the majority of cases for 2.0.

**Comment by tmatheson-arm** [comment]
Thanks @memsharded. I'm aware of lockfiles, but from what I understand they require a separate mechanism for distributing them. If a user wants to do `conan install consumer/1.0` to get the CI-built package on their own machine, they would first have to fetch the lockfile from somewhere and then do `conan install consumer/1.0 --lockfile=consumer_1_0.lockfile`. This is possible but requires extra infrastructure and tooling to workaround the problem.

It seems like a fundamental limitation that the dependency graph is recalculated at install time, and the result can be different from at build time even with the same settings and options on the same machine. The package ID is affected by external state (i.e. the creation of a new dependency version/revision) which is not reflected in the recipe. This seems fundamentally broken. Features like `default_package_id_mode=recipe_revision_mode` allow you to lock down the package ID to the point of recipe/package revisions, but which ultimately make it harder to fetch the correct binary without a way to specify those revisions.

The information about exact dependency revisions used is captured in the consumer `conaninfo.txt`, but this is not accessible without first knowing the Package ID. Baking them into the exported recipe seems like the best solution; this would allow users to fetch the package easily with `conan install`, and also allow the builds to be fully reproducible from the top level recipe. Alternatively, is there is a way to generate a lockfile from an existing binary package?

**Comment by memsharded** [comment]
> Thanks @memsharded. I'm aware of lockfiles, but from what I understand they require a separate mechanism for distributing them. If a user wants to do conan install consumer/1.0 to get the CI-built package on their own machine, they would first have to fetch the lockfile from somewhere and then do conan install consumer/1.0 --lockfile=consumer_1_0.lockfile. This is possible but requires extra infrastructure and tooling to workaround the problem.

If the project is a consumer only, then, it could just store the lockfiles in the repo, that would make it straightforward to apply, and will work well for different branches, etc of the repo. 

> The information about exact dependency revisions used is captured in the consumer conaninfo.txt, but this is not accessible without first knowing the Package ID. Baking them into the exported recipe seems like the best solution; this would allow users to fetch the package easily with conan install, and also allow the builds to be fully reproducible from the top level recipe.

That is another challenging thing, the problem is that the dependency graph is different for every different configuration. The same package can use "boost/1.65" in Windows and "boost/1.75" in Linux. Then there is no a single lockfile that can store that, and it is necessary to store all the possible lockfiles for all the possible variants. But when you export a recipe, it gets its new recipe revision, which freezes the state, so it is not possible to add a new lockfile after the recipe has already been uploaded for a given configuration. These have been the major blockers until now.

We are working on improving this for Conan 2.0 lockfiles, it doesn't seem possible to improve this with the Conan 1.0 infrastructure.

> Alternatively, is there is a way to generate a lockfile from an existing binary package?

No, because the problem is not well determined. For example, if you have a "minor_mode" binary compatibility mode. One given package binary will be the same exact (and compatible) binary for different patch versions of its dependencies (this is achievable for example if using all static libraries and using semver versions bumping correctly)

**Comment by petermbauer** [comment]
From an enterprise user perspective the current situation wrt CCI, revisions and lockfiles gives us headaches.
Going through the "solutions" given in the [CCI docs](https://github.com/conan-io/conan-center-index/blob/master/docs/consuming_recipes.md):
- we have our own Artifactory instance but whenever we upload new revisions of existing packages coming from the CCI, these are automatically used everywhere (due to the latest revision being used by default) so e.g. a new Conan version has to be rolled out in advance (for CI and all developers) and it would not be possible anymore to build old versions (using an old Conan version). Having to create a new repo for every new version of e.g. the Qt package also does not scale well.
- using lockfiles would be acceptable for CI but for local usage it is too cumbersome and error-prone

So from our POV its unfortunate that the package revisions feature is heavily used by the CCI for breaking changes although the lockfiles or a similar feature are not "production-ready".

**Comment by memsharded** [comment]
Hi @petermbauer 

We are aware of these issues, specially the complexity of lockfiles (the approach using Artifactory indeed is limited to moving forward without breaking with unexpected ConanCenter updates), that is the thing that makes them cumbersome for developers usage.

We have put a ton of effort in simplifying lockfiles in 2.0, they are already inside the released alpha-2, but they are lacking an upgrade to the CLI args, and of course all the documentation. 

We have also started a proof of concept (related to @tmatheson-arm question) in https://github.com/conan-io/conan/pull/10261, about exporting the lockfiles together with the recipe, but that will introduce some new challenges, so it is too early to know if this will move forward. 

In any case, the above mentioned simplifications will probably be a game changer for lockfiles, it would be great if you can keep tuned and give feedback when this is documented enough to try it.

**Comment by petermbauer** [comment]
Hi @memsharded

thank you very much for the insights and all your efforts, happy to hear that this topic is on the radar already.
I will try to keep up with the development and provide feedback.

**Comment by AbrilRBS** [comment]
Closing in favour of https://github.com/conan-io/conan/issues/6851, which tracks the progress of the work going into automatically exporting the lockfile alongside the recipes
