### ISSUE TITLE
[question] ERROR: boost/1.77.0: Error in build() method, line 829 

### ISSUE THREAD

**Issue by mayerdev** [conan-io/conan#10206]
I am trying to install boost 1.77 on M1 in docker container with debian 11.

conanfile
`[requires]
sol2/3.2.3
mongo-cxx-driver/3.6.6
boost/1.77.0

[generators]
cmake`

CMakeLists
`cmake_minimum_required(VERSION 3.1)

project(rncore LANGUAGES CXX)

add_executable(rncore src/main.cpp)
add_definitions("-std=c++14")

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -W -Wall -Wextra -Werror -Wno-unused-parameter")

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()`

[log.txt](https://github.com/conan-io/conan/files/7739504/log.txt)

**Comment by mayerdev** [comment]
I was able to install without problems via vcpkg, it doesn't work via conan.

**Comment by memsharded** [comment]
Sorry this issue was not responded back then @mayerdev, sometimes it is not possible to respond to every ticket.

This report is now quite outdated, using legacy integrations like the old ``cmake`` generator, that has already been removed in Conan 2. 
Also, recipes for ConanCenter packages have been improved since then to better support ``arm`` architectures, it is possible that even boost required some patches in 1.77 for Linux-arm that Conan recipe was not doing yet and newer boost versions already have better support.

I am closing the ticket as outdated, sorry again, if you still have any issues please don't hesitate to create new tickets, nowadays we are typically able to respond to the vast majority of them. Thanks for your feedback!
