### ISSUE TITLE
[question] build dependency from source for debugging

### ISSUE THREAD

**Issue by andiwand** [conan-io/conan#10223]
Hello!

I wondered if there is a solution for re-building dependencies from source when they changed.

Looking at the following scenario: I am working on `Library Molecule` which depends on `Library Atom`. Both are CMake projects. I get a bug report for `Library Molecule` which I suspect is actually originated in `Library Atom`. If I am building `Library Atom` from source (e.g. via `add_submodule`) I can easily change the source and test my theory.
The same procedure using conan packages is more tedious because full rebuild and repackage take much longer than going through the CMake rebuild.

Is there a mechanism in conan that would speed this process up?

Otherwise it might be acceptable to have a switch in CMake of `Library Molecule` to either build `Library Atom` from source or consume it through conan.

Sorry if this is already answered somewhere - I was not able to find it.
Thank you in advance!

**Comment by franramirez688** [comment]
Hi @andiwand 

I think what you need are the [packages in editable mode](https://docs.conan.io/en/latest/developing_packages/editable_packages.html) so you'll be able to work with any of your dependencies from the source.
Please, have a look at [this video](https://www.youtube.com/watch?v=VzUJQw89U7o&t=2487s&ab_channel=ItalianCppCommunity) as well because it explains more about this topic.
Let me know if it is what you're looking for o you need anything else.

**Comment by andiwand** [comment]
thank you @franramirez688 - sounds cool I will check it out!
