### ISSUE TITLE
[bug] default profile is mandatory in 2.0

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#10262]
Hello,

It seems that the `default` profile is mandatory in 2.0, even though the error message implies otherwise.

### Environment Details (include every applicable attribute)
  * Conan version: 2.0.0a2

### Steps to reproduce (Include if Applicable)

* remove `default` profile
* run `conan create --profile=whatever`

### Logs (Executed commands with output) (Include/Attach if Applicable)

```shell
$ conan create /Users/theo/Tanker/conan/recipes/libcxx --profile=macos-x86_64-release --update

#ERROR: The default profile file doesn't exist:
#/Users/theo/.conan2/profiles/default
#You need to create a default profile or specify your own profile
```

**Comment by memsharded** [comment]
Hi @theodelrieu 

Probably the message could be improved, but this doesnt seem a bug:

- 2.0 always uses 2 profiles, if one is not specified it will be defaulted to "default" profile
- In your case, it is defaulting to add ``--profile:build=default`` as you already specified the host one
- The "default" profile doesn't exist. And it is not automatically created. This was also approved in the Tribe: https://github.com/conan-io/tribe/pull/24

The solutions would be:
- Call ``conan profile detect`` to create a default profile
- Pass ``--profile:build=xxxx`` explicitly pointing to one of your own profiles
- Use the ``[conf]`` to specify other default profile (must exist), rather than the "default"

Please let me know if this clarifies it a bit. Then we need to think how to improve the message, I'd say to add the ``conan profile detect`` message.

**Comment by theodelrieu** [comment]
Right, I've missed that subtlety! Indeed I had to `touch default` at some point :D

I guess improving the message would be enough for 1.x users like me.

**Comment by babariviere** [comment]
@memsharded In this case, why not fallback to the host profile since it's specified by the user?

**Comment by memsharded** [comment]
> @memsharded In this case, why not fallback to the host profile since it's specified by the user?

Yes, this is something that we also thought, and there were a few reasons that slightly inclined the balance towards the current default (but something that can be discussed and changed if it makes sense, of course): The "build" context, that will contain tools like "cmake", or compilers, etc, is typically very constant for multitude of scenarios: for all cross-building for example, you dont want host-profile==build-profile, but build-profile to be basically the same, while you change the host one. The same applies for different native settings: you don't want cmake to use "debug" build-type just because you are targeting "debug", or you don't want to have cmake linked dynamically, and depend on zlib.so and openssl.so to run, because you are building shared libraries for your app. So it seems a bit more likely that an auto-detected "default" profile will match better the build settings than the user provided one.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/10409
