### ISSUE TITLE
Two profile with different compilers use the same packages

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#10264]
Hello

I have two toolchains that I store in each their own package
1: gcc 8.5.0 with glibc 2.27
2: gcc 8.5.0 with glibc 2.19

I have a host profile for each of these toolchains:
```
[settings]
arch=armv7hf
os=Linux
build_type=Debug

compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11

[build_requires]
gcc_8.5.0_glibc_2.27_armhf/0.0.1
```
and
```
[settings]
arch=armv7hf
os=Linux
build_type=Debug

compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11

[build_requires]
gcc_8.5.0_glibc_2.19_armhf/0.0.1
```

My project conan file looks like this:
```
[requires]
libbacktrace/cci.20210118
boost/1.73.0
openssl/1.1.1k
log4cplus/2.0.5
libssh2/1.9.0
xerces-c/3.2.3
libcurl/7.70.0
protobuf/3.12.4
libmicrohttpd/0.9.59
bcm2835/1.68
pca9685/1.0
libarchive/3.5.1
bluez-armhf-binaries/5.54

[generators]
cmake

[options]
boost:without_stacktrace=True
log4cplus:unicode=False
log4cplus:fPIC=True
log4cplus:shared=True

```

If I start with an empty local conan cache and run conan install with the first host profile packages are downloaded and built with the toolchain as expected. If i then run conan install with the second profile conan determines that the packages already exist and reuse what was built with the first profile. But that was with the other compiler in the first profile, and event though their both gcc 8.5.0 they're not identical. I guess conan does this because the profiles are identical from a settings/options perspective. But how can I make it build packages with the correct toolchain as specified in the profile build_requires?

Rgds
Klaus

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Yes, exactly the glibc is not modeled by default into the binaries, so it must be added if you want to handle it. Please have a look at https://docs.conan.io/en/latest/extending/custom_settings.html#adding-new-sub-settings, that could be a good start, adding a "sub-setting" will allow to define your glibc in your profiles, and no changes are necessary in recipes it will take you just a few minutes. 

The only thing is that it will require building new binaries from source, as the ConanCenter ones will not be valid for the new definitions you are adding, but I guess that you expect this, right? I'd recommend to store the pre-compiled binaries for your different glibcs in an Artifactory server, to avoid continuous rebuilding from source.

Maybe also want to consider a higher grain definition, instead of pinning the glibc completely, define "families" of glibc-compatible packages. But that completely depends on your application and requirements.

Please let me know if this helps.

**Comment by klausholstjacobsen** [comment]
James, YOU'RE THE MAN!
Thanks. It works!

Rgds
Klaus
