### ISSUE TITLE
Printable dependency graph

### ISSUE THREAD

**Issue by austinjmorlan** [conan-io/conan#1030]
I have an idea for a feature add that I would be happy to implement if I knew that you would be open to incorporating it into the code base.

Often while working on a big project with a lot of dependencies, it's nice to be able to see at a glance what the dependency tree looks like. The current way of seeing it via `conan info` is nice but hard to view mentally because it's just flat text.

My idea would be to add something like `conan graph` which would generate a [dot](http://www.graphviz.org/content/dot-language) file that could be fed into a graph generator like [graphviz](http://www.graphviz.org/) or [mermaid](https://knsv.github.io/mermaid/).

Thank you.

**Comment by memsharded** [comment]
Yes, I think it is a good idea, have been previously around, but never got priority enough to be implemented. If you are willing to do it, great, very welcome.

Some tips:
- The ``conan info`` command receives same parameters as ``install``. Depending on the inputs, the dependency graph could be different, also the binaries. Same should be for ``conan graph``
- Then, as much code will be duplicated, you might consider using a ``conan info --graph`` instead, or do refactor internals.
- Consider abstracting and having a TextPrinter and a GraphPrinter. Probably, html/js graph would be cool too, so that could be implemented in another Printer.

Just ask if you need any help with the implementation, testing, setup, or understanding something from the code. Thanks very much!!

**Comment by austinjmorlan** [comment]
Great, I've started some work on it.

I've got one question at the moment.

I have a code block like this where I'm attempting to go through the project's dependencies so the project itself and each of its dependencies can print its info (name and version) in the DOT format to a file.

```
for node in self._deps_graph.nodes:
    ref = node.conan_ref

    if ref is None:
        ref = self._project_reference

    depends = self._deps_graph.neighbors(node)
```

This works to get the entire dependency tree, but because `self._project_reference` is a string rather than a ConanFIleReference, I'm unable to parse its name and version using `ref.name` and `ref.version`, and I don't think doing something like `ref.split('/')[0]` and `ref.split('/')[1]` is the best way to do it.

Is there a different way to do it other than using `project_reference` which is passed into `conan info` via `manager`?

**Comment by memsharded** [comment]
The issue is that the project reference for the root node can be different
things:
- a ConanReference if conan install [reference]
- a string if installing a user conanfile. If the conanfile has name and
version iy will be pkg/ver@project
- a string Project if user conanfile.txt or conanfile.py didnt declare name
and version

So I guess that the only solution is to conditionally parse it. Or maybe
just leave it as a string.

**Comment by austinjmorlan** [comment]
Sorry, I deleted my comment because I realized there's no need to parse the name and version separately as the graph should contain the entire conan reference (i.e., `name/version@user/channel`) because two packages could feasibly have the same name and version but be from different users and/or channels.

**Comment by memsharded** [comment]
ok, no problem, makes sense :)

**Comment by CodingSpiderFox** [comment]
I would like this very much, too

**Comment by CodingSpiderFox** [comment]
I made some experiments with the networkx library some time ago. Looked quite well I think.
