### ISSUE TITLE
[bug] Windows installer package is missing python modules (pathlib)

### ISSUE THREAD

**Issue by slietzau** [conan-io/conan#10365]
The Windows installer package is broken since 1.44.0. It doesn't include the full Python standard library anymore and produces the following error message:

```
ModuleNotFoundError: No module named 'pathlib'
```

I also tested 1.43.3, 1.43.2 and some previous versions. They didn't have the bug.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 20H2
  * Compiler+version: not relevant
  * Conan version: 1.44.0 and 1.44.1
  * Python version: not relevant since the windows installer package is used

### Steps to reproduce (Include if Applicable)

Create a simple *conanfile.py*:
```python
from conans import ConanFile
from pathlib import Path


class MyTool(ConanFile):
    name = "mytool"
    version = "0.0.1"
    author = "me"
    settings = "os", "build_type", "compiler", "arch"
```

Run any conan command with the conanfile. For example `conan info conanfile.py`.
### Logs (Executed commands with output) (Include/Attach if Applicable)

```console
PS D:\tmp\conan\bug_pathlib> conan info .
ERROR: Error loading conanfile at 'D:\tmp\conan\bug_pathlib\conanfile.py': Unable to load conanfile in D:\tmp\conan\bug_pathlib\conanfile.py
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\tmp\conan\bug_pathlib\conanfile.py", line 2, in <module>
    from pathlib import Path
ModuleNotFoundError: No module named 'pathlib'
```

**Comment by memsharded** [comment]
Hi @slietzau 

This is one of the side effects of ``pyinstaller`` and changes in the Python ecosystem. Due to ``pyinstaller`` bundling what it considers from the Python interpreter, usage of the Python stdlib should be reduced to whatever is documented in Conan docs, and ``pathlib`` is not used at all (this is the reason ``pyinstaller`` probably decided to not bundle it). Changes in the Python packaging ecosystem (in this case it seems it was a recent version of virtualenv, that changed something) can also change how ``pyinstaller`` behaves.

And this is one of the reason we don't recommend the installer as the main way to install Conan. Especially if you intend to use things from the Python interpreter beyond what Conan does, then maybe it is better to use the full ``pip`` installation.

Besides that, we can try to add it explicitly to the ``pyinstaller`` code (``--hidden-imports``), we already did that for something in latest Conan 1.44.1 (are you sure you tested explicitly also with 1.44.1?). By the way, the code is in the repo root, it is called ``pyinstaller.py``, if you run it, it will create the executable for you that you can try. But even if we fix it for this release, it is difficult to guarantee full stability of the bundled installation over time, so please consider.

Lets try to fix this for next release (no patch release is scheduled yet, it is bad to change just the installer without bumping the version).

**Comment by slietzau** [comment]
Thanks again for the quick response.

We found the bug with version 1.44.1. After a lot of `choco install conan --version 1.XY` calls my conclusion is that the bug first appeared in version 1.44.0. A fix for 1.45 would be great.

Adding that exception, so `pathlib` is useable in conanfiles would be a great. I guess there will be demand since the object oriented interface has some advantages over `os.path`.

**Comment by slietzau** [comment]
Concerning the installer vs `pip` argument:
Managing different Python versions and packages in a corporate setting is a difficult task. Separating `conan` from the Python dependency is a big advantage for us, especially if one uses tools like `chocolatey` to manage the `conan` installation.

**Comment by memsharded** [comment]
Fixed in https://github.com/conan-io/conan/pull/10386, will be in next 1.45
