### ISSUE TITLE
[question] With build profile specified the self.copy() does not work for build_required package?

### ISSUE THREAD

**Issue by michkrom** [conan-io/conan#10370]
I am calling `self.copy()` in `imports()` to copy a build tool binary form a dependency specified as `build_require`. This works normally, the tool is found and copied to build dir. However, when build profile is specified it does not - the tool is not copied.

I can work around the problem by finding out absolute path to the build_required package (from self.dependencies) and then calling self.copy() with this absolute path.

Is this an expected behavior?

**Comment by memsharded** [comment]
Hi @michkrom 

Yes, this is expected behavior at this moment. The current ``self.copy()`` of the ``imports()`` only manages the "host" context when the 2 profiles are used.

If you want to access the dependencies inside the method you can do with:

```python
def imports(self):
      for r, d in self.dependencies.build.items():
           self.output.info("DIRECTBUILD {}: {}".format(r.direct, d))
```

And then accessing the ``d`` information of the dependency, you can get its folder, and copy the files that you need. You might get some more info about ``self.dependencies`` in https://docs.conan.io/en/latest/reference/conanfile/dependencies.html.

Though the truth is that we are trying to avoid as much as possible to do copy of files, specially from the "build" requires, and if you need to use them, we use "virtualenvs", more exactly the ``VirtualBuildEnv`` generator, that will create scripts that can be used to call the tools inside the ``build_requires`` without doing a file copy, which is more efficient and cleaner, and allows easier management of multi-configuration.

**Comment by michkrom** [comment]
Thanks for prompt answer.  It is still disturbing that the behavior changes, getting us constantly surprised.

My current workaround is similar:
```
        package_folder = ''
        for require, dependency in self.dependencies.items():
            if 'MyPackage' in dependency.ref:
                package_folder = dependency.package_folder        

         self.copy(src=f'{package_folder}/bin', dst='tools',  pattern='myexe')

```

The `build_require` package is in the `self.dependencies` anyway, as this is afaiu superset of all dependencies?

**Comment by memsharded** [comment]
> Thanks for prompt answer. It is still disturbing that the behavior changes, getting us constantly surprised.

It is not a breaking change. It is a completely new feature and new behavior, that is opted-in with the ``profile:build`` command line argument. The cross-compilation model had some flaws and broken things that needed to be changed, and this was the way to introduce the new solution. If you don't want, you are not forced to use the ``profile:build`` feature, and things will keep the same.

> The build_require package is in the self.dependencies anyway, as this is afaiu superset of all dependencies?

Yes, the ``self.dependencies`` contains all of them, the ``self.dependencies.build`` will contain only those in the "build" context.

**Comment by michkrom** [comment]
Ok, sure - a lot of it is working great for us, thanks!

So better question would be - what is the right way to handle this kind of `import()` in the presents or absence of -pr:h (multi host os and normal and cross build targets; we copy an executable that is suitable for the host arch/os - the dependency is just a package of a few os-specific binaries).

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, where `imports()` has been dropped in favour of a generate() approach
