### ISSUE TITLE
[2.0] [feature/feedback] conans.model.version.Version needs to be converted to str

### ISSUE THREAD

**Issue by babariviere** [conan-io/conan#10372]
When downloading source using `conan.tools.files.get`, we are using the conandata.yml to store url depending on the recipe version.

This result in this pattern:

```python
class MyPackageConan(ConanFile):
    name = "my-package"
    version = "1.0.0"

    def source(self):
        files.get(self, **self.conan_data["sources"][self.version], strip_root=True)
```

However, in this case, conan will complain with this error:

```
ERROR: my-package/1.0.0: Error in source() method, line 20
	files.get(self, **self.conan_data["sources"][self.version], strip_root=True)
	KeyError: 1.0.0
```

Proposition:

Make `Version` convert to str as we had for 1.0.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> Make Version convert to str as we had for 1.0.

To clarify, you want the new ``Version`` class to have a ``__str__`` method, or you want ``self.version`` to always be an object of ``str`` class?

**Comment by babariviere** [comment]
I want the `Version` class to have a `__str__`

**Comment by memsharded** [comment]
It already has one 😄 

```python
    def __str__(self):
        return self._value
```
The problem is that having a ``str`` method does not automatically convert it to string when used as a dictionary key, which is the use you are doing.

**Comment by babariviere** [comment]
So, we are stuck at converting Version to str everytime? 😢

**Comment by memsharded** [comment]
The problem is that it also contains a ``__eq__`` and ``__hash__`` methods, to be able to do version comparison, for example, ``1.0 == 1.0.0``, and that means that ``dict[Version("1.0") == dict[Version("1.0.0")`` (same key in the dict).

It seems that we cannot have both things at the same time, we cannot have smart comparison and hash, to treat it as a version (something that users will also want, to be able to write things like ``if self.version > "1.0"``), and also as a bare dictionary key, assuming an exact string comparison will be performed.

**Comment by babariviere** [comment]
I guess there is nothing that can be done then. Thanks!

**Comment by memsharded** [comment]
We have discussed this, and we have decided to leave the "str" type as base.
People wanting to use ``self.version`` for full comparisons can:

- Explicitly convert to ``Version(self.version)``
- Use ``self.ref.version``

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/10519, to be in next alpha 4

**Comment by babariviere** [comment]
Thanks!
