### ISSUE TITLE
[feature] Source caching

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#10397]
One risk of the conan model is that the recipes require sources which are held in a different place. e.g. a git repository or a zip download. If that place breaks or goes away at some point in the future, the recipe will break. I'm sure there are practical issues, but at a high level it would be nice if the sources could be cached and pulled from a conan remote directly rather than the original source.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @rconde01 

This issue was requested in https://github.com/conan-io/conan/issues/10379, and we already have a proof of concept in https://github.com/conan-io/conan/pull/8211. Please track that PR for progress about this feature (will most likely not happen before 2.0, but it is something we will probably resume work for 2.X)

I'll close this, and lets follow up https://github.com/conan-io/conan/pull/8211
