### ISSUE TITLE
Consider bintray as a conan backend

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#104]
Hi,

A bit of a speculative one - if its not of interest let me know and the ticket can be closed.

I just bumped into a new service around GitHub today that may be of interest to conan: bintray[1]. It has good GitHub integration and as such it seems like a convenient place to push packages to. However, it seems the range of supported services is limited at present with Maven and Nuget being the most conan-like options. Maybe you guys could reach out to them for conan support? 

Many thanks

Marco

[1] https://bintray.com/

**Comment by lasote** [comment]
Hi Marco!

It's an interesting service. I will take a look to it when I get a little time. My first impression is that it can be interesting but maybe a little later.

Thanks!

**Comment by malikkirchner** [comment]
I am very interested in integration with binary repositories. BinTray is nice, but I think Artifactory is a more appropriate end-point for Conan, because only release grade packages should be promoted to BinTray after a QA audit.

**Comment by titan-ae** [comment]
Up vote for Artifactory backend :-)

**Comment by mcraveiro** [comment]
@malikkirchner When you say:

```
because only release grade packages should be promoted to Bintray after a QA audit. 
```

Is this a BinTray policy or your particular company's? I thought you could push anything you wanted to into BinTray, if not its not as useful then...

@titan-ae the great thing about BinTray is that conan wouldn't have to worry about it - BinTray would provide the artifactory support. But yes, I too agree that direct NuGet/Artifactory support for conan would be a killer feature, since these systems are already so popular. 

Cheers

**Comment by malikkirchner** [comment]
@mcraveiro yes, you are right. Sure you can push packages of any quality to Bintray, if you choose to. Bintray is a distribution system targeted at the end-user of a software. The role of a binary repository for developers takes Artifactory.

**Comment by mcraveiro** [comment]
@malikkirchner well, to be fair BinTray supports both Maven and NuGet backends, technologies that are very similar to Artifactory. Personally, I think they are aiming to become more of a generic distribution mechanism, applicable to both end users and developers. But then again, I'm inferring all that from their main page, and I have never used it, so take my opinions with a grain of salt.

**Comment by malikkirchner** [comment]
@mcraveiro Suppose you have some libraries and a final executable using those libraries. You could put the executable in a public spot at Bintray and your libraries into some private area, possible. Or you want to distribute your library from a NuGet repository to anybody, also possible. The Artifactory use-case is different.
Imagine you want to build a CI infrastructure and your companies policy is, that you have to revision internal artifacts on your own servers. Only the final product is supposed to leave the intranet. That is not possible with Bintray. Because it is a cloud service; no self-hosting possible. Or did I miss something? In this case you would use Artifactory to do the internal handling of artifacts and would promote some production ready artifacts to Bintray for distribution. Since Artifactory and Bintray integrate nicely, it would be sufficient to support Artifactory. 
But this is just my use-case. Maybe Bintray is the better choice for the majority of users?

**Comment by Xaltotun** [comment]
+1 for artifactory

I am currently investigating using conan in an enterprise setting, but one of our requirements is storing binaries in artifactory.  It seems like it would be easier to adapt this project to our build system instead of recreating it on top of a project like ivy.  I would be interested in helping implement the artifactory backend.

**Comment by memsharded** [comment]
There are two approaches here:
- Use the conan server as proxy, and implement a backend in artifactory. This would be relatively easy, I see no special problems. The main disadvantage is that you still need the conan_server app running, though this app is quite easy to run.
- Directly implement protocol to talk directly to artifactory from conan client. This is more complicated and could require a lot of work, especially if we don't want to break things and maintain things working. It will not need the conan_server app.
We are seriously considering this issue, it is definitely in our roadmap, thanks for the help offer @Xaltotun, we'll update on this.

**Comment by chales** [comment]
Another +1 for Artifactory support.

**Comment by gesellc** [comment]
+1 for Artifactory Support.

**Comment by Duduitto** [comment]
[JFrog Acquires Conan](https://www.jfrog.com/support-service/jfrog-acquires-conan-bringing-devops-cc/)!!!

**# Congratulations**

**Comment by sourcedelica** [comment]
Awesome news!  I hope this means that Conan will keep getting better, only faster!  👍

**Comment by GamePad64** [comment]
So, maybe, mark this as "resolved"? :grin:

**Comment by memsharded** [comment]
Yeah!!!!!
Both bintray & artifactory support for conan. Closing issue, thanks for telling :D
