### ISSUE TITLE
[question] Access to outdated packages

### ISSUE THREAD

**Issue by alexandre-marinkovic** [conan-io/conan#10449]
Hi,
I have a dependency on icu/69.1 and I was able to retrieve it on conan-center 1 month ago.

Now since the recipe of icu have changed, the package that I was using is considered as outdated and there is no package on conan-center with the new recipe and with my options/settings.
I know that I can build icu with the new recipe but I was wondering if it was possible to search for outdated packages as dependencies when calling "conan install" or "conan create".
Thanks. 

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @amarinko 

I am not sure if this is what you want, but do you know that you can pin the exact revision to use? Doing a requires to ``pkg/version#exact_revision`` will pin to that revision and will not be affected by new ones. It is also possible to use lockfiles, but that might be a bit more complicated.

In any case the new changes to recipes are typically good things, sometimes necessary fixes, etc., so in general it is recommended to update to the latest one when possible.

**Comment by alexandre-marinkovic** [comment]
Thanks for the quick answer.

_> Doing a requires to pkg/version#exact_revision_
It means that I have to change my recipe for that ?
It's not a change that I would like in my recipe since I know that icu package will be available one day. 
Is it possible to change the dependencies requirements when calling "conan install"/"conan create" to specify a revision ?

 _> In any case the new changes to recipes are typically good things, sometimes necessary fixes, etc., so in general it is recommended to update to the latest one when possible._
I understand and most of the time I prefer to have the last version. But sometimes when you are in a hurry, you don't want to build dependencies, specially if you have an outdated version which is available.

**Comment by memsharded** [comment]
> t means that I have to change my recipe for that ?
It's not a change that I would like in my recipe since I know that icu package will be available one day.
Is it possible to change the dependencies requirements when calling "conan install"/"conan create" to specify a revision ?

ConanCenter recipes get frequent updates, fixes, etc. If you want to freeze it to a previous version there are several alternatives:

- Specify it explicitly in your recipe, yes this requires adding it in your recipe.
- You might specify on the command line a ``--require-override=pkg/version#exact_revision``, but this can be also inconvenient, to type always in the command line, that was the reason I was suggesting to put it in the recipe.
- Capturing lockfiles when it is working, and apply them later to be using those locked dependencies

In any case, it is necessary to specify the exact revision you want to use.

Another approach that many users are doing, specially large companies with strict policies is fork conan-center-index, and rebuild the binaries themselves, putting them in their own server. When they upgrade the repo, they test and update what is necessary in order to use the new latest state from ConanCenter, but they can do it in a controlled way.

**Comment by alexandre-marinkovic** [comment]
I tried your solution 2 by calling --require-override=icu/69.1#58b8d8ffb1d460eb92d3f938d6adbc4116ffeeae

And it seems that overriding of icu is understood but it still search for the other revision.
![image](https://user-images.githubusercontent.com/35067563/151563223-c7e46e35-2b34-4bf4-a3b3-b57c3a29933e.png)

--require-override should work with revision ?

**Comment by memsharded** [comment]
No, what you are highlight below is not the "recipe_revision" (the hash of the recipe, like internal automatic version of the recipe). It is the "package_id", which is the hash of the settings + options. It is likely that ConanCenter doesn't have a pre-compiled binary for your current settings and options

**Comment by alexandre-marinkovic** [comment]
Ah ok thanks! I'm not an expert yet! 
And is it possible to provide the "package id" of my outdated version to conan install instead of the "recipe version" ?

**Comment by memsharded** [comment]
>Ah ok thanks! I'm not an expert yet!

No problem, don't hesitate to ask if something is not clear, we are here to help 😄 

> And is it possible to provide the "package id" of my outdated version to conan install instead of the "recipe version" ?

No, the package_id cannot be directly forced to install (you might ``conan download`` it explicitly, but that only retrieves it, do not prepare it for being used). The ``package_id`` is a computation over your inputs, you define from your profile the ``os``, the compiler, compiler.version, architecture, build_type, etc. ``package_id`` and ``recipe_revision`` are completely different things, it is not one OR the other, but one after the other. First the ``recipe_revision`` determines basically the original source recipe that was originating a package. Once a recipe with its revision is fixed, the look for a binary compatible with your current profile (settings) starts, and Conan feeds the settings into that specific recipe (and that specific revision), to compute a ``package_id``, then looks for the ``package_id`` in the servers.

**Comment by alexandre-marinkovic** [comment]
Thanks a lot, it's all clear now!
