### ISSUE TITLE
[question] version ranges using same package multiple times

### ISSUE THREAD

**Issue by RolfBippus** [conan-io/conan#10454]
I got the following problem:

I have project **A** that requires a specific **libA** and **libB**.
Project **libA** also requires **libB**.

For versioning I use version ranges that only match major and minor version, namely:
`libB/[== 1.3.x]@user/channel`

in both project **A** and **libA**.

for conan install, I now get the following error:

`ERROR: libA/1.3.0@user/channel: requirement libB/[== 1.3.x]@user/channel overridden by A/1.0.0 to libB/1.3.0@user/channel`

Thus, obviously conan is unable to detect that 1.3.0 satisfies 1.3.x and believes this is a clash.
Although `semver.satisfies('1.3.0', '1.3.x')` correctly delivers True.

Remark: there is exactly one recipe for libB available, namely for 1.3.0.

- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @RolfBippus 

This has been already solved in 2.0. 
Meanwhile, I think I'd try to switch the order in which A depends on libA and libB, have you already tried that?

**Comment by RolfBippus** [comment]
The direct solution was to set general.error_on_override=False in conan.conf. Sorry I did not see this from the start.

The order was correct, first specifying libB, which then gets set to a concrete version and then overrides all other version of libB in the remaining requirements.

Still, ideally I would like to allow the override only if the new version (1.3.0) satisfies the range imposed by the overridden version. I would assume this is what you referred to as being resolved?

**Comment by memsharded** [comment]
> The direct solution was to set general.error_on_override=False in conan.conf. Sorry I did not see this from the start.

Ah, sure, of course, if that config is True, it is totally expected to raise. No prob, glad to hear you found it.

> Still, ideally I would like to allow the override only if the new version (1.3.0) satisfies the range imposed by the overridden version. I would assume this is what you referred to as being resolved?

Yes, the behavior of 2.0 is more or less:
- If there is a diamond, and one fixed version in the diamond, satisfies the range in another branch of the diamond, that version can be taken as valid (as opposed to resolve the version range to the latest existing matching version, and then conflicting or overriding the other)
- If there is a diamond with 2 different version ranges in 2 branches, if the solution to the first branch that is resolved fits into the version range of the other branch, it will taken as good. Conflicts will be then very reduced for this scenario.
- Both ``override`` and ``force`` are explicit traits. By default Conan will raise when there is a conflict, it will never override unless explicitly told to.

Just a side note, in Conan 2.0 we are implementing the version ranges, instead of depending on an external library. At the moment we have only implemented the ``[>xxx <=yyy]`` syntax, not the ``[1.3.x]`` one. Not saying that we will not do it, but until we do it, the second might not work, and in the general case the first one will be always recommended.

**Comment by RolfBippus** [comment]
Sounds good!
I like the 1.3.x syntax, since for semantic versioning this is somewhat more readable (all bugfixes are ok, if you do not break your versioning).
Assuming there will not be thousands of bugfix releases however, the first syntax will definitely suffice.
Thanks.
