### ISSUE TITLE
[question] Is there a way of building the test_package when the package is built as a transitive dependency?

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#10521]
When you build a package with `conan create`,  the `test package` is built and run to test that everything worked correclty.
But if a given package is being built because it is a dependency of the package you're building with `conan create` (considering a build policy that triggers this) then the test packages of the dependencies are ignored.
I understand how this could be the desired behavior most of the time, but is there some flag that makes conan build the test package of the dependencies as well?

An example may make it clearer. Since I'm passing `build=*` all the dependencies will be built from sources.
```
$ conan create recipes/libarchive/all libarchive/3.5.2@eric/testing --build=\*
...
...
Requirements
    libarchive/3.5.2@eric/testing from local cache - Cache
    libiconv/1.16 from 'conan-center' - Downloaded
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    libarchive/3.5.2@eric/testing:e8d12759fe94f61449796c065e7303c925d38ea3 - Build
    libiconv/1.16:1d877a3df840030e6a8abb74c5ffb9088d08b47a - Build
    zlib/1.2.11:1d877a3df840030e6a8abb74c5ffb9088d08b47a - Build
...
...
libiconv/1.16 package(): Packaged 3 '.h' files: iconv.h, localcharset.h, libcharset.h
libiconv/1.16 package(): Packaged 1 file: iconv
libiconv/1.16 package(): Packaged 2 '.a' files: libcharset.a, libiconv.a
libiconv/1.16 package(): Packaged 1 '.LIB' file: COPYING.LIB
libiconv/1.16: Package '1d877a3df840030e6a8abb74c5ffb9088d08b47a' created
libiconv/1.16: Created package revision e6d1a105c2b2a3f1a820aaf41e1c9038
libiconv/1.16: Appending PATH environment var: /home/eric/.conan/data/libiconv/1.16/_/_/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/bin
Downloading conan_sources.tgz completed [1.13k]                                          
Decompressing conan_sources.tgz completed [0.00k]                                        
zlib/1.2.11: Configuring sources in /home/eric/.conan/data/zlib/1.2.11/_/_/source
Downloading zlib-1.2.11.tar.gz completed [593.46k]                                       

zlib/1.2.11: Copying sources to build folder
zlib/1.2.11: Building your package in /home/eric/.conan/data/zlib/1.2.11/_/_/build/1d877a3df840030e6a8abb74c5ffb9088d08b47a
...
...
```

As you can see, `libiconv` and `zlib` as marked to be built, but their test package is ignored. Only `libarchive`s test package is built. 

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @ericriff 

This is basically impossible. The ``test_package`` folder is just a local folder, it is not exported with the recipe, it is not uploaded to any server. Basically to Conan, it doesn't exist, as it is not a package, it is a pure consumer.

When you are building transitive dependencies with ``--build=xxxx``, they are using the recipe from the server to call the source, build, package methods. But the local ``test_package`` doesn't exist, and there is no reference to it, the package itself doesn't know about it. The relationship is exclusively in the test_package -> package direction, not the opposite.

In theory, the ``test_package`` functionality is to guarantee that the package is correctly created. That it packaged the artifacts correctly and that they can be used. It is not intended for any functionality testing. That responsibility would be also easily covered by any consumer actually using that package for something real. Actually, the coverage of the real consumers will be better than the ``test_package`` one, because it is the real consumption and usage of that package, while the ``test_package`` could be a very simplistic use of the package.

**Comment by ericriff** [comment]
Thanks for getting back to me. I didn't know this part of the conan world.
