### ISSUE TITLE
[question] Error accessing new `dependencies` attribute in `build` method

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#10535]
Hi there,

Our company uses Conan extensively and the bulk of our recipes currently need to access the `deps_cpp_info` attribute in the `build` method. In beginning to evaluate the road to Conan 2.0 I have attempted to switch to using the the `dependencies` attribute as per the [migration guide](https://docs.conan.io/en/latest/conan_v2.html#self-dependencies-to-access-information-about-dependencies), however any attempt to do so using 1.45 results in an error. Consider the following code and output:

``` python
...
def build(self):
    for require, dependency in self.dependencies.items():
        self.output.info("Dependency is direct={}: {} {}".format(require.direct, dependency.ref ,dependency.pref))
```
```
conan build .
...
conanfile.py: Calling build()
ERROR: conanfile.py: Error in build() method, line 28
        for require, dependency in self.dependencies.items():
        AttributeError: 'NoneType' object has no attribute 'dependencies'
```

The current [documentation](https://docs.conan.io/en/latest/reference/conanfile/dependencies.html#dependencies-interface) states:
> At the moment, this information should only be used in generate() and validate() methods. Any other use, please submit a Github issue.

Hence why I am seeking clarification on whether there are plans to support the new `dependencies` attribute in `build` method of Conan recipes in Conan 2.0. 

To provide a bit more context about our use case, we have a custom build helper class (based on `conans.MSBuild`) which is used by the bulk of our recipes in their `build` method. Part of the logic in this helper requires access to the `deps_cpp_info` attribute of the relevant conanfile. Note this information it is not required for compilation purposes, but is required to allow correct integration with a 3rd-party tool and this must be done during the build phase.

Thanks in advance,

Sam

**Comment by czoido** [comment]
Hi @santhonisz,
The problem is not that you can't access `dependencies` attribute in `build` method, if you do a `conan create` instead of a `conan build` you will see that you can access your dependencies.
If you check the proposal to the [Conan Tribe about the "local flow"](https://github.com/conan-io/tribe/blob/main/design/019-local_development_flow.md) you can see that `conan build` in Conan 1.X relies in a previous saved state while in Conan 2.0 will do a computation of the graph. That difference in behavior makes your example fail because in Conan 1.X there's no information about those dependencies using that command.
Hope this helps.

**Comment by santhonisz** [comment]
Hi @czoido 

That makes perfect sense, thanks for the prompt reply!
