### ISSUE TITLE
[question] Conan 2.0 migration - consuming existing 1.x packages

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#10542]
Hi there,

I've been doing a bit of experimentation with Conan 2.0 and have come across an issue which I'd like
some clarification on. This is in the context of https://github.com/conan-io/tribe/blob/main/design/013-migration-path.md

One of the key breaking changes is the refactoring of namespaces e.g. moving `ConanFile` and `tools` etc. from the `conans` namespace to `conan`. While there is already the ability to migrate recipes to the new namespace in the latest 1.x releases, this really only solves the problem from a "future-compatibility" perspective. We are still left with a situation where all existing packages using the `conans` namespace cannot be consumed in a recipe under Conan 2.x

For example, under 2.0 if you define the simple requirement `gtest/1.8.1` in a recipe, an error such as the following occurs:

```
gtest/1.8.1: Not found in local cache, looking in remotes...
gtest/1.8.1: Checking remote: conancenter
gtest/1.8.1: Trying with 'conancenter'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
Decompressing conan_export.tgz
gtest/1.8.1: Downloaded recipe revision a68c7a96d668242114b772f28235f004
Traceback (most recent call last):
  File "c:\devel\conan-2.0\.conan-2.0\lib\site-packages\conans\client\loader.py", line 313, in load_python_file
    spec.loader.exec_module(loaded)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\santhonisz\.conan2\p\8ce8e12e386d168c\e\conanfile.py", line 2, in <module>
    from conans import ConanFile, CMake, tools
ImportError: cannot import name 'ConanFile' from 'conans' (c:\devel\conan-2.0\.conan-2.0\lib\site-packages\conans\__init__.py)
```

I totally understand why this is occurring - the recipe for the dependency hasn't been updated to be 2.x forwards-compatible and hence can't be loaded during the dependency resolution.

So to clarify, does this render every package, either on `conancenter` or in private Artifactory repos, unusable in 2.x until it is updated? Consider that this means every version of packages too i.e. not all consumers will want the latest version of a package.

If so, the effort involved for our company to update every recipe in our private repos is **enormous**; we have 1000s of active packages/versions and each of these would effectively need to be rebuilt in order to update them. You can probably guess at the expected internal push-back over such a requirement.

What is the expectation for existing packages in `conancenter` in this regard?

Any clarification on this would be greatly appreciated.

Thanks,

Sam

**Comment by memsharded** [comment]
Hi @santhonisz 

Yes, current ConanCenter packages are not ready for 2.0 consumption. They need to be updated to use the modern 1.X build system integrations (like CMakeToolchain, CMakeDeps), the new ``conan.tools``, the new environment management, etc. This effort has started, and during the alpha and beta we will temporarily have another "ConanCenter2" repo for experimentation, and then start to upgrade ConanCenter recipes to be 1.X and 2.0 compatible.

> So to clarify, does this render every package, either on conancenter or in private Artifactory repos, unusable in 2.x until it is updated? Consider that this means every version of packages too i.e. not all consumers will want the latest version of a package.

In ConanCenter, most of the time, updating one recipe updates all the previous versions too, that is not a big problem.
And yes, recipes must be updated in 1.X to the new above mentioned tools and integrations in order to be ready for 2.0. It is the only possible way to move forward. We have been doing a huge effort to provide everything that is needed in 1.X releases so this can happen, and we will continue doing this so the transition can be as smooth as possible. We have started to introduce these things more than 1 year ago (see for example mentions to CMakeToolchain in 1.30.1 (09-Oct-2020) release)), so the transition can be gradual, and there will be more time while 1.X and 2.0 are maintained. But moving forward with such a major version like 2.0 is basically impossible without deprecating and removing legacy things.

**Comment by santhonisz** [comment]
Hi @memsharded,

Thanks for the reply. It's good to have some clarification around the approach for ConanCenter and what can be expected in that regard.

Moving back to privately-hosted packages such as ours, we now also have some clarity in regards to having to upgrade our recipes. I understand the reasons why the decisions were made as they were and appreciate the efforts to date to make commencing the transition possible. 

In light of that, I do need to mention that the biggest blocker from us proceeding in transitioning at this point is the "experimental" status of the upcoming replacements for a lot of existing generators, compilers etc. The vast majority of our packages are Visual C++ and hence are using the `Visual Studio` compiler settings along with the `visual_studio/visual_studio_multi` generators and `conans.MSBuild` build helper. As it stands the intended replacements e.g. the `msvc` compiler settings and `conan.tools.microsoft` tools are all marked experimental and subject to breaking changes in the documentation. As an enterprise user obviously this presents a risk that is hard to accept compared to the current stable tools. Are there any (broad) timelines for the stabilisation of these components, and indeed for the expected release of Conan 2.0?

**Comment by memsharded** [comment]
> As an enterprise user obviously this presents a risk that is hard to accept compared to the current stable tools. Are there any (broad) timelines for the stabilisation of these components, and indeed for the expected release of Conan 2.0?

That is a fair question. Even if we don't have a very fixed timeline, let me summarize our current view:

- Some of the new integrations, as ``MSBuildDeps`` and ``MSBuildToolchain`` (also ``CMakeDeps``, etc), are already more feature rich, flexible and powerful than the previous ones. For example ``MSBuildDeps`` can generate one file per dependency, so it allows multi-projects to select the specific dependencies they need per-project, and it also allows custom configurations, like ``ReleaseDll`` and ``ReleaseStatic`` that can be often found in VS projects.
- Even if they are experimental, they are already relatively stable, the basic interfaces are not expected to change that much. (Depending on the integration, CMake and MSBuild are more mature than Meson or Autotools, for example). 
- The moment we start to accept PRs to ConanCenter using them, and that is happening in the next month hopefully, we will be even extra careful to not break them, even if "experimental" means that we still might do it if very necessary.
- The very final stabilization will come when Conan 2.0 is GA (hopefully mid-year), because that moment by our stability commitment we will not break them in 2.X, and that means that such interface (backported to 1.X) will also be stable. Conan 1.X and 2.0 will co-exist for some time, so there will be time to update things in 1.X while testing that things are 2.0 ready, for a smooth transition.

A possibility that many of our users that want to use the latest features do, is to use them with some care, and then control strictly the Conan version in their CI and systems. When a new Conan version is released, they check everything first, and only upgrade Conan version if successful, to avoid potential breakings of experimental things. In general, having a CI pipeline that the Conan version is an argument, and that can fire more than 1 version, might be useful in general but super useful for the 1->2 ugprade.

**Comment by santhonisz** [comment]
Thanks very much for providing that information, it certainly gives us a bit more clarity of what's ahead.

We do already control access to the version of Conan used by both our developers and CI via an internal Python package which has Conan (and Conan Package Tools) as a dependency; as you suggest this allows us to thoroughly test prior to rolling out new versions 👍🏼.

**Comment by SaarYogev** [comment]
Hi @memsharded, thanks for the information.
Do we currently have a "ConanCenter2" for experimation in the current alpha release, or is that planned for a future release?
If it isn't ready yet, are there any issues related to its development that we can follow/contribute to?

**Comment by memsharded** [comment]
> Do we currently have a "ConanCenter2" for experimation in the current alpha release, or is that planned for a future release?

We have a private instance we are using for experimentation during the alpha stage. We will make it public in beta. The recipes will be a fork of conan-center-index first, and then directly in conan-center-index (keeping 1.X compatibility, of course)

**Comment by db4** [comment]
> > Do we currently have a "ConanCenter2" for experimation in the current alpha release, or is that planned for a future release?
> 
> We have a private instance we are using for experimentation during the alpha stage. We will make it public in beta. The recipes will be a fork of conan-center-index first, and then directly in conan-center-index (keeping 1.X compatibility, of course)

Why don't make that ConanCenter2 public right now? No one expects it to be stable, but that would make experiments with Conan 2.0 outside the team much easier. Currently, Conan 2.0 alpha6 just adds the same `https://center.conan.io` as `conancenter` remote that's quite misleading.

**Comment by memsharded** [comment]
It has been made available. It is already documented in https://docs.conan.io/en/2.0-alpha/tutorial/consuming_packages/getting_started/build_simple_cmake_project.html

**Comment by fisher-m** [comment]
> It has been made available. It is already documented in https://docs.conan.io/en/2.0-alpha/tutorial/consuming_packages/getting_started/build_simple_cmake_project.html

The above URL is no longer available.  When I click on the link, I get a "Page Not Found" error.  Can you please post the new ConanCenter2 URL here?

**Comment by fisher-m** [comment]
I found the new page here:  https://docs.conan.io/en/2.0/tutorial/consuming_packages/build_simple_cmake_project.html.

The ConanCenter2 URL is:  https://conanv2beta.jfrog.io/artifactory/api/conan/conan

**Comment by memsharded** [comment]
Yes, the new entry point is https://docs.conan.io/en/2.0/ (it doesn't make sense to maintain docs for the alpha live, 2.0 docs will be a moving target until 2.0 GA, and from there docs will be versioned again as 2.1, 2.2, etc
