### ISSUE TITLE
[bug] layout: self.folders.generators not working like --install-folder

### ISSUE THREAD

**Issue by heili77** [conan-io/conan#10559]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS, Windows
  * Compiler+version: Any
  * Conan version: 1.45/1.42
  * Python version: 3.9.10/3.6.6

### Steps to reproduce (Include if Applicable)
Conanfile:
```
from conans import ConanFile

class file (ConanFile):
    
    name = "Testlib"
    version = "1.2.3"

    generators = "cmake_paths"

    default_channel = "testing"
    default_user = "local"

    def layout(self):
        self.folders.generators = "conan"
```

`conan install . `

Current result in file system:
```
conan.lock
conan_paths.cmake
conanbuildinfo.txt
conanfile.py
conaninfo.txt
graph_info.json
```

Expected result in file system:
```
conan
+- conan.lock
+- conan_paths.cmake
+- conanbuildinfo.txt
+- conaninfo.txt
+- graph_info.json
conanfile.py
```

So layout self.folders.generators cannot replace  `conan install . -if conan`.

According to https://docs.conan.io/en/latest/developing_packages/package_layout.html#example-everything-together

**Comment by memsharded** [comment]
Hi @heili77 

This is expected. 
The new ``layout()`` generators folder only applies to the new generators, those in ``from conan.tools.xxxx``, like ``CMakeDeps``
It doesn't apply to legacy generators like ``cmake`` or ``cmake_paths``. It also doesn't apply to the Conan generated files like ``conaninfo.txt``.

Quick hint about the future 2.0:
- ``install-folder`` disappears. The new ``--output-folder``, introduced in 1.45 will replace it. It has slightly different behavior too.
- All the conan generated files like ``conaninfo.txt``, ``conanbuildinfo.txt``, ``graphinfo.json`` have been already removed from 2.0, they are not generated anymore, only the explicitly called generators will create files.

**Comment by heili77** [comment]
Thanks for the quick answer

**Comment by heili77** [comment]
Is there an equivalent for cmake_paths working with layout?

**Comment by memsharded** [comment]
> Is there an equivalent for cmake_paths working with layout?

Yes, the ``CMakeToolchain`` generator already adds the paths to the packages, equivalent to ``cmake_paths`` functionality

**Comment by samuel-emrys** [comment]
> * `install-folder` disappears. The new `--output-folder`, introduced in 1.45 will replace it. It has slightly different behavior too.

If I have a `conanfile.py` that contains the following:

```python
    ...
    generators = (
        "ycm",
        "virtualrunenv",
    )
    ...
```
And I attempt to install:

```
$ conan install . -of conan -pr:b=default
```

I end up with a structure that looks like the following:

```bash
.
├── activate_run.ps1
├── activate_run.sh
├── CMakeLists.txt
├── conan
│   └── cmake-build-release
├── conanbuildinfo.txt
├── conanfile.py
├── conaninfo.txt
├── conan.lock
├── conan_ycm_extra_conf.py
├── conan_ycm_flags.json
├── deactivate_run.ps1
├── deactivate_run.sh
├── environment_run.ps1.env
├── environment_run.sh.env
├── graph_info.json
└── ...
```
As you say, `conaninfo.txt`, `conanbuildinfo.txt`, and `graphinfo.json` will be removed. This still leaves the outputs of a number of other generators (which I would imagine will survive the transition to 2.0?). Are there plans to facilitate their placement into the `output-folder`?

Also, it looks like `conan build` doesn't currently support the use of `output-folder` in the installation method? Running `conan build .` after the above yields the following error:

```
Using lockfile: '/home/user/projects/project/conan.lock'
Using cached profile from lockfile                                   
conanfile.py (project/0.1): Calling build()                           
ERROR: conanfile.py (project/0.1): Error in build() method, line 128                                                                        
        cmake = CMake(self)                                          
        ConanException: The file /home/user/projects/project/cmake-build-release/conan/conanbuild.conf does not exist. Please, make sure
 that it was not generated in another folder.   
```

As you can see, it's looking in `/home/user/projects/project/cmake-build-release/conan/` for `conanbuild.conf`, which is a directory that doesn't exist. Because I specified an output directory, this should be `/home/user/projects/project/conan/cmake-build-release/conan/conanbuild.conf`. Does it stand to reason then that `conan build` should also have a `--output-folder` argument that it can accept?

Or am I doing something wrong here? I'm just trying to stop my project root from getting polluted with build files, and I'm having a hard go of it.
