### ISSUE TITLE
Set scopes from conanfile.txt

### ISSUE THREAD

**Issue by lewie-donckers** [conan-io/conan#1055]
I would like to be able to set scopes in `conanfile.txt`. This would be similar to how one can set options in `conanfile.txt`.

To me this seems a logical feature as scopes are similar to options from a package user perspective.

**Comment by memsharded** [comment]
I think that scopes are more like settings, is not something to be defaulted by a conanfile but to be defined by users/consumers. Actually, conanfile.txt is just a simplification of conanfile.py, and then, it cannot store *values* for settings, just check those settings for implementing different logic, but the settings are always defined by users. If conanfile.txt could declare scope default values, we should also provide a way to declare those default values in conanfile.py. The same way, the natural default state for a scope is disabled(not defined), and is something that end users could activate for specific behavior.

Could it make sense to be able to declare them in ```profiles`` instead? That way you can have profiles defined for settings+options+envvars+scopes, as many as you want, with a meaningful high-level name. Or maybe both ways?

**Comment by lewie-donckers** [comment]
Maybe I misunderstood the intent of scopes but I thought of Conan's different configuration items as follows:

- settings: cross-recipe configuration items that affect package selection
- options: recipe-specific configuration items that affect package selection
- scopes: recipe-specific configuration items that do not affect package selection

If that's correct, I think default scopes should be treated just like options. Default values should configurable in a package recipe by a package creator. Package users should be able to set scope values in a `conanfile.txt` for a project that has Conan dependencies.

-----

In any case, your proposal would not solve my particular problem to my liking. Perhaps I should have led with that instead of suggesting a fix for it.

I have created a Conan recipe for third party (pre-built) libraries we use at work. They come in a few varieties (Windows/Linux, debug/release, dynamic/static) and I was able to setup the recipe to accommodate that just fine. So far, so good.

One of the libraries is optional and I would like the recipe to setup the `cpp_info` to link with it depending on a configuration item that can be specified together with the source code of any project that uses the recipe. Obviously I can do this with Conan options but I this would result in even more different packages and I would like to avoid this. Based on what I read about Conan scopes, I thought this would allow me to do just that. So I was surprised to find out I could not specify scopes in `conanfile.txt` as I can do with options.

Your thoughts?

**Comment by memsharded** [comment]
Thanks for the feedback. Yes, I am not opposed to this feature request, just thinking out loud and considering other things. Maybe it can be done and packages can provide defaults for scopes, I was just saying that if done in conanfile.txt, it should also be done in conanfile.py

I am not fully sure if I understood your original case, but maybe the new multi-config packages could be a possibility for you (now working for cmake generator): http://docs.conan.io/en/latest/packaging/package_info.html#multi-configuration. With them you could specify configuration specific variables, and let the consumer use what they want. Something like:

```python
def package_info(self):
    self.cpp_info.optional.libs = ["myoptlib1", "myoptlib2"]
```

This will translate in the generated ``conanbuildinfo.cmake`` to:
```cmake
set(CONAN_LIBS_MYPKG_OPTIONAL myoptlib1 myoptlib2)
```
But this CONAN_LIBS_MYPKG_OPTIONAL will not be linked by default. You can use any name or any number of alternative configs. It shouldn't be difficult to add it conditionally in the consumer CMakeLists.txt. With this method you don't need to do the round-trip and trigger an extra unnecessary ``conan install`` to define a new configuration because one scope has changed. Does this make sense?

**Comment by lewie-donckers** [comment]
Thanks for the suggestion. I wasn't aware of the multi-configuration feature but I think it's exactly what I'm looking for.

**Comment by memsharded** [comment]
Great, let me know how it works. A good summary of packaging strategies: http://blog.conan.io/2017/03/07/Supporting-Different-C-C++-Package-Paradigms-with-conan.html

**Comment by memsharded** [comment]
Is this feature still wanted? I am quite happy with the possibility to add ``scopes`` to profiles, and I like it more than adding them to ``conanfiles``. Did the multi-config packages solved your issue @lewie-donckers ?

**Comment by lewie-donckers** [comment]
To be honest, I haven't had time to try it yet. (They have me working on something else at the moment.) I'm confident the multi-config package will solve my problem though.

So, if you want you can close this issue or put it on hold or something. Then I'll get back to you in case things do not work out.

**Comment by memsharded** [comment]
Yes, great. I will close it by now, you can re-open, comment or submit a new one if necessary. Thanks!
