### ISSUE TITLE
[question] Excluding a package?

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#10554]
I'm trying to build the libgpiod package on my systems but the internet I'm on blocks gnu.org and thus fails the libtool dependency, is there a way I can either disable build_requirements or disable a specific dependency.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
If a recipe directly ``requires`` a package, it is not possible to avoid that. That basically means that if that package is not retrieved, the consumer package will not work.
If it is a ``build_requirement``, it is enough to not build the consumer, but if the consumer needs to be built, then it also requires that build requirement, otherwise it will not be able to build correctly.

That seems an unfortunate block. If you are going to have that block in production, I'd recommend to:

- Fork the recipe for that package from ``conan-center-index``.
- Modify the source origin to point to other origin that you have access
- Build the package. Recommended to store it in your own server to avoid rebuilding

Then you will be using your own package. Alternatively you can also do, instead of a fork, a replacement recipe that will be just a proxy to a system installed package.

**Comment by wbehrens-on-gh** [comment]
maybe an option to exclude build_requirements and have the consumer install them on their own system. I'm on ubuntu 21.10 with libtool installed yet it still tries to pull and build it.
