### ISSUE TITLE
[question] Is it possible to determine the recipe revision hash without exporting it to the cache?

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#10601]
I'm working on improving how we manage of some internal recipes that live outside of the source (we don't control the source). All the recipes live together in one repo and what I want to do it get the recipe revision number for each recipe to determine if the package needs to rebuild or fail a CI/CD job cause it shouldn't have changed. All the packages use `revision_mode = hash` and I'd like to be able to know what the hash is to determine what should be done.

The one approach I came up with is to just export the package and parse the console output and then remove it after but I was wondering if there might be another way to get the revision number that doesn't rely on the recipe being exported.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @nichmj01 

It is necessary to export the package, because the hash of the contents of the recipe is the result of evaluating the ``exports`` and ``exports_sources`` attributes, and doing the copy, then executing the ``export()`` and ``export_sources()`` method, possibly running hooks, and finally computing the hash of the contents. These operations need to happen to know what will be the final hash, the only way to do it reliable is actually do it. It would be possible to do it to another temporary folder, just to compute the revision, but that seems unnecessary. There is no need to remove it from the cache after it, the good thing of the revision=hash is that it guarantees the contents are the same.

> All the recipes live together in one repo and what I want to do it get the recipe revision number for each recipe to determine if the package needs to rebuild 

Conan has some tools that allows for a good modelling of what needs to be built from sources, based on what changed. For that case, it is necessary to export the recipes to the cache anyway, and let the ``package_id_mode``, possibly ``recipe_revision_mode`` if you want to decide to rebuild for every source code change, irrespective of versions. If you are removing the recipes later, it seems that you are not using this?

**Comment by nichmj01** [comment]
> There is no need to remove it from the cache after ...

Hmmmm.. I was focused on just getting the revision number, so I was thinking in terms of leaving the system in its original state (that is the cache is the same at the end as it is at the start). In the actual scenario I want to address leaving it in the cache is probably fine.

> If you are removing the recipes later, it seems that you are not using this?

We're using `recipe_revision_mode` to determine binary compatibility. This is related to #10514 where we have a DepsPkg recipe that "locks" down all the recipe revisions being used for all dependencies. The recipe for this DepsPkg lives on the same repo as all the other recipes we manage (there is no C++ source for DepsPkg). 

So we have on a git repo:
+ DepsPkg recipe --> requires LibA#1, LibB#4
+ LibA recipe --> requires LibB
+ LibB recipe

The thought is to automate the creation of these packages as part of a CI/CD process where the job would get triggered by a change to the repo. Since anything could have changed, including the LibA or LibB recipes (maybe accidentally, maybe on purpose), I want to check that the recipe revisions for all packages are what is expected since I want to know if the recipe accidentally got changed somehow. Also, some of them can take hours to build. For example: if `"conan export LibA"  != revision 1`, the job will fail. 

There are also times when we will intentionally change a recipe and update DepsPkg and in those cases I want the recipes to be built across all platforms. 

So if things change such that:
+ DepsPkg recipe --> requires LibA#2, LibB#4
+ LibA recipe --> requires LibB
+ LibB recipe

In the job, if `"conan export LibA" != revision 2`, fail; if `"conan export LibA" == revision 2`, build LibA ('conan create LibA`), and DepsPkg (`conan create DepsPkg`).

I hadn't thought through everything, but your response has helped me see an approach. I think it will be fine to leave the exported recipes in the cache and always call `conan create DepsPkg --build=missing` at the end. Since DepsPkg has no source, the `create` step is usually fast so there's minimal overhead always building it. If all the dependency packages exist, they'll be downloaded, if they're missing, they'll be built. If the DepsPkg already exists, we just won't upload anything when we call `conan upload` (it's all text files so I believe even the PREV won't change).

I guess the only downside is that we'll be downloading the packages every time, but I can probably short circuit that and only call `conan create DepsPkg` if `"conan export DepsPkg" != {expected revision}`

Thanks for the info!
