### ISSUE TITLE
[question] How to avoid generating canoe config files for dependencies

### ISSUE THREAD

**Issue by heili77** [conan-io/conan#10627]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I use conan 1.42

I have legacy packages with cmake config files included. When I use the CMakeDeps, there are config files generate for these dependencies and, as those packages do not describe their layout, the content of those generated config files is useless. Those files cause errors, if they are found by CMake.

Can I modify the CMakeDeps generator in the root package to avoid generation of those config files?

I only found a way to this in the dependent package:
```
self.cpp_info.set_property(„cmake_find_mode“, “none“)
```

**Comment by memsharded** [comment]
Yes, using the ``dep.cpp_info.set_property("cmake_find_mode", "none")`` is the correct way, because if the package is not going to work, you better say it once in the package, that have every single consumer failing and having to repeat the same fix over and over.

If you want to get rid of them once they have been generated by ``CMakeDeps``, then, have you tried to do a remove of the ones that you don't want? it would be a remove in ``generate()`` method, something like:

```python
def generate(self):
     deps = CMakeDeps(self)
     deps.generate()
     for pkg in ("pkg1_notwanted", "pkg2_notwanted", ..):
           # remove files matching *{pkg}*.cmake
```

**Comment by heili77** [comment]
I thought of a more integrated way to avoid those files. Thanks for the pragmatic solution.
