### ISSUE TITLE
[question] Using layout() with workspace

### ISSUE THREAD

**Issue by heili77** [conan-io/conan#10621]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
I use conan 1.42

I describe my packages with the Lay-out function in the recipe. Is there a workspace_generator using the layout information from the recipe?

The cmake workspace generator returns missing folders and according to documentation it is the only one available for workspaces.

**Comment by memsharded** [comment]
The ``workspace`` feature has been put on hold for more than 2 years now, and we have actually removed it in the 2.0-alpha releases. The goal was to stabilize ``layout()`` and editable first, instead of juggling with a half baked feature. Users will probably be way more effective by creating their own script that configures their "workspace" using some command commands and some scripting. 

We will resume work on the workspace feature sometime after 2.0 is stabilized, like a later 2.X version.
