### ISSUE TITLE
[bug] Incorrect version in lockfile when deduced from other lockfile on package with non Sermver Versions

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#10647]
I am having two conanfiles, and i want to derive a lockfile for `OtherApp` from the lockfile of `App`.

```
conanfile.py

class App(ConanFile):
    name = "app"
    version = "1.0.0"

    def requirements(self):
        self.requires("openssl/1.1.1i@")
```

```
conanfile.py

class OtherApp(ConanFile):
   name = "otherapp"

    def requirements(self):
        self.requires("openssl/[*]@")
```

`App/1.0.0@` is in the cache, the `conanfile.py` for `OtherApp` is in my local folder.

```
conan lock create --reference=App/1.0.0@ --base --lockfile-out=app.lock
conan lock create conanfile.py --lockfile=app.lock --lockfile-out=otherapp.lock
```

## The bug:
`app.lock` contains `openssl/1.1.1i@` (correct)
`otherapp.lock` contains `openssl/1.1.1@` (incorrect, the `i`postfix is missing)

## What i expect
Both lockfiles contain `openssl/1.1.1i@`.

## Screenshot
comparison of lockfiles
![image](https://user-images.githubusercontent.com/13848742/155364408-dfe81963-c944-41ad-9c51-ed8a480d390c.png)

and on the console:
creation of first lock
![image](https://user-images.githubusercontent.com/13848742/155364731-3ea80239-e2ee-4687-a80b-95eddfdb020e.png)

creation of second lock
![image](https://user-images.githubusercontent.com/13848742/155365153-3d72f434-29f3-4904-ac48-9847eae43c5e.png)

### Environment Details (include every applicable attribute)
  * Conan version: 1.45.0

**Comment by memsharded** [comment]
Hi @KerstinKeller 

I think this is intrinsic to the way lockfiles are extended in Conan 1.X. When you are creating one lockfile passing an initial lockfile as argument, such lockfile should belong to the dependency graph.
You cannot apply the ``App`` lockfile to something that doesn't depend on ``App``. It will be simply disregarded. The locked ``openssl/1.1.1i`` will only be used when ``App`` is in the dependency graph. If you inspect the actual generated ``app.lock`` you will see this relation is explicit.

So when the lockfile is applied to ``otherapp``, it nevers reach the locked openssl, because that only happens if ``App`` is a dependency of ``OtherApp``.

This is one of the things that have greatly improved in 2.0, and it will work as you are expecting.

**Comment by KerstinKeller** [comment]
@memsharded, your statement is really interesting, because it is not the behavior I am seeing.
All other dependencies are taken from the `app.lock`, and not freely from the cache, except for the `openssl` case (with non-semver versions - though I am not sure if it is taken freely, or just the `i` is dropped).

E.g. `App` requires `protobuf/3.11.4@` and `OtherApp` requires  `protobuf/[*]@` then `otherapp.lock` contains `protobuf/3.11.4@` although I have a newer `protobuf/3.12.1@` in the cache.

**Comment by memsharded** [comment]
Sorry this wasn't managed back then @KerstinKeller 

This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
