### ISSUE TITLE
[bug] Cannot make work basic Bazel example on Windows 10 with Bazel 5

### ISSUE THREAD

**Issue by denjmpr** [conan-io/conan#10676]
Firstly, I want to thank you for providing basic support of Bazel, this is great news!

But I cannot make the bazel-example integration sample work - https://docs.conan.io/en/1.44/integrations/build_system/bazel.html .
Looks like some key information is missing for this page and probably BazelDeps generator doesn't provide right output for Bazel 5.

About missing parts:
1. I had to create 'conandeps' folder and put there conanfile.py file.
I didn't know that just running `conan install .` on conanfile.py which is inside the root folder (Bazel workspace) will not create this folder and/or
`load("@//conandeps:dependencies.bzl", "load_conan_dependencies")
load_conan_dependencies()`
will not do some magic to make dependencies work.
Probably some steps to explain this process should be provided here.
2. I had to call `conan install . --build missing`, because boost binaries of version 1.76.0 for my OS and compiler doesn't exist in the ConanCenter.
Probably some link here to some page will make easier this step.
3. I cannot build boost 1.76.0 for my OS and compiler due to some error from b2.exe, so I had to switch boost version to 1.78.0.
Not sure what can be done here, but maybe some note will also help.
4. I had to add BazelDeps generator from this page - https://github.com/conan-io/conan/issues/10399 to conanfile.py to make Bazel/Conan integration work.

After some kind of success I tried to build my project with boost dependency:
`bazel-5.0.0-windows-x86_64.exe build //main:bazel-example`
and started to obtain such errors:
`ERROR: C:/users/denjm/_bazel_denjm/xv66akve/external/boost/BUILD.bazel:7:26: invalid escape sequence: \.. Use '\\' to insert '\'.`

I tried to google the problem, possibly found a solution by setting of `--incompatible_restrict_string_escapes` Bazel flag to false.
But looks like Bazel 5 doesn't support this flag anymore - https://github.com/bazelbuild/bazel/commit/21b4b1a489c991682b9fcc9a10b468b9ea18e931 .

So, I think that BazelDeps generator should be fixed to provide proper Bazel files.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Pro build 19043.1526
  * Compiler+version: Visual Studio 17
  * Conan version: 1.45.0
  * Python version: 3.10.2
  * Bazel version: 5.0.0

### Steps to reproduce (Include if Applicable)
1. Download and unzip attached project 
[bazel-example.zip](https://github.com/conan-io/conan/files/8155226/bazel-example.zip)
2. Install dependencies with Conan inside of conandeps folder.
3. Try to build project with Bazel 5:
`bazel-5.0.0-windows-x86_64.exe build //main:bazel-example`

### Logs (Executed commands with output) (Include/Attach if Applicable)
[command.log](https://github.com/conan-io/conan/files/8155209/command.log)

**Comment by memsharded** [comment]
Hi @denjmpr 

Thanks for the detailed report. 
I see https://github.com/bazelbuild/bazel/releases/tag/5.0.0 that the 5.0 release is very recent. 

Regarding the escaping of strings, it seems https://github.com/conan-io/conan/pull/10581 is related, but it is still red. We would try to help there when possible to make it green.

Regarding some of the other issues:
 > I had to create 'conandeps' folder and put there conanfile.py file.

For some reason that was hardcoded. But it has been fixed, will be released in next 1.46, pointing to the right ``generators_folder``


> I had to call conan install . --build missing, because boost binaries of version 1.76.0 for my OS and compiler doesn't exist in the ConanCenter.
Probably some link here to some page will make easier this step.

The thing is that if that binary was missing you should get a clear error message, indicating about the ``--build`` solution and with a link to https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package. Didn't you get it?

>  cannot build boost 1.76.0 for my OS and compiler due to some error from b2.exe, so I had to switch boost version to 1.78.0.

This can be reported to the https://github.com/conan-io/conan-center-index repository, in case it can be fixed by the recipe. Maybe it is a Boost issue that older versions don't built with latest MSVC, or maybe it is a recipe issue and something can be fixed there to provide support for it.

**Comment by denjmpr** [comment]
Hi @memsharded,
> The thing is that if that binary was missing you should get a clear error message, indicating about the --build solution and with a link to https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package. Didn't you get it?

Yes, you are right, everything appears - sorry, I forgot about this message after resolving problem with boost 1.76.0.
Thank you for pointing it out.

**Comment by lasote** [comment]
Hi! I'm working with a [branch](https://github.com/conan-io/conan/pull/10812) containing some improvements for the Bazel integration. I gave a try to your `zip` file and even changed the "hello world" with a real Boost usage and now it is working fine. It will be released at Conan 1.47.
The only thing you need to take into account is apply the "build" profile when calling `conan install` command:

```sh
cd conandeps
conan install . -pr:b=default
```

If you don't specify the build profile it will mess with the "b2" build requirement of boost. The build profile will be automatically applied in Conan 2.0 and we encourage to use it with the new generators.
