### ISSUE TITLE
[feature] Meson : set wrap_mode = nofallback by default?

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10671]
[wrap](https://mesonbuild.com/Wrap-dependency-system-manual.html) downloads some packages from the outside during the build, with I think is not desirable in many cases, for source immutability, and to control dependencies (avoid ODR violation and so on).
right now, I have to add
```
def generate(self):
    tc = MesonToolchain(self)
    tc.project_options["wrap_mode"] = "nofallback"
    ....
    tc.generate()
```

I'd like it if it could be automatic, or maybe have some built-in way to control it.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sounds reasonable, lets change the default, and leave a configuration point open for changing it.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/10884, will be in 1.47

**Comment by pfirsich** [comment]
I am not sure if this was a good idea. What's the recommended way to deal with internal dependencies now? I.e. if I have a few of my own libraries that I have previously used as a subproject (as meson docs recommend afaik)? Do I have to add a conanfile.py for this now? Do I have to build conan packages for them? I think both of these options are a bit annoying. I think this seems like a fairly common case too. Also you won't really have subprojects download by accident, because you have to add a wrap file to your subprojects directory.

**Comment by memsharded** [comment]
Hi @pfirsich 

I don't know enough about Meson wrap system. I understood the original idea was that if Conan is being used for dependency management, then avoiding fetching dependencies via Wrap made sense, to avoid collisions. I was not aware that wrap is also used for subproject management, I understood it was only used for external dependencies. 
It is true that if we remove this, users should be extra careful to avoid collisions and ODR violations due to repeated dependencies in both systems, but I guess it is doable.

**Comment by franramirez688** [comment]
Hi @pfirsich 

First of all, sorry for the delay in reviewing this issue, I completely forgot it.

I'm just wondering that in that case (having internal subprojects managed by Meson), shouldn't it be enough to drop that option from your current recipe?

```python
def generate(self):
    tc = MesonToolchain(self)
    tc.project_options.pop("wrap_mode")
    tc.generate()
```
Another thing is if you depend on another dependency it'd already be using that default value, but, anyway, IMO, I think it's better to have that default value for most of the cases, isn't it? Do you have any repo to show your use case?

**Comment by memsharded** [comment]
Proposing https://github.com/conan-io/conan/pull/14124 with the test suggested above to close this ticket. The recommended solution is:

- keep the ``wrap_mode = nofallback`` by default, it is a safe one when using Conan.
- Projects that need to rely on wrap_mode different, they can configure it easily in the recipe with ``MesonToolchain.project_options``.

The PR above https://github.com/conan-io/conan/pull/14124 will serve also as a base to explicitly document this.
