### ISSUE TITLE
[question] Profile variables not expanding properly

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#10678]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Profile:
```
include(default)

toolchain=arm-none-linux-gnueabi
toolchain_root=/opt/none/version/sysroots/
cross_root=$toolchain_root/armv7-none-linux-gnueabi
sys_root=$toolchain_root/x86_64-linux
toolchain_path=$sys_root/usr/bin/$toolchain/$toolchain

[settings]
arch=armv7
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux

[build_requires]
cmake/3.19.8
ninja/1.10.2

[env]
CONAN_CMAKE_GENERATOR="Ninja"
CONAN_CPU_COUNT={{os.cpu_count()}}
CONAN_CMAKE_FIND_ROOT_PATH=$cross_root
CONAN_CMAKE_SYSROOT=$cross_root
# Set toolchain
CC=$toolchain_path-gcc
CXX=$toolchain_path-g++
RANLIB=$toolchain_path-ranlib
STRIP=$toolchain_path-strip
AR=$toolchain_path-ar
LD=$toolchain_path-ld
AS=$toolchain_path-as
```

I'm trying to cross compile some packages using a custom profile and toolchain but conan seems to be expanding the variables in the profile incorrectly as I get the error: 
```
  Could not find compiler set in environment variable CC:

  arm-none-linux-gnueabi_path-gcc.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)
```

according to the [cross building page](https://docs.conan.io/en/latest/systems_cross_building/cross_building.html) this should be valid. why is it escaping at the underscore?

**Comment by memsharded** [comment]
I think the issue is that you have 2 colliding vars:
```
$toolchain
$toolchain_path
```

You cannot use the second, as the textual replacement is replacing the ``$toolchain`` within ``$toolchain_path`` first, before the other (the full ``$toolchain_path``) is even checked. 

I think this is intrinsic to this textual replacement paradigm, and the solution would be to use variables that avoid such collision, such ``$path_toolchain``.

As you are using jinja already (it seems so with ``{{os.cpu_count()}}``), you can probably also leverage jinja for a more powerful or idiomatic variable management.
