### ISSUE TITLE
[question] Our Hero's perilous journey of installing a package from source

### ISSUE THREAD

**Issue by codedump** [conan-io/conan#10698]
Hello,

Installing a package from source into live production (e.g. from `~/package-src` to `/usr/local`) via Conan is a journey full of folklore, legends and perils ;-)

I'm fairly new to Conan and still trying out to figure the details. This is what I came up with so far, so I'm posting this here in the hope that it will be useful, and that, maybe, some poor soul will have mercy on this mere peasant and let him know if he's missing something obvious and could be doing things more elegantly.

Anyway, as far as I understand:

   - `conan export <conanfile>` registers the recipe described by `<conanfile>` with the local Conan cache. Useful to make a dependency known, so it can be used later.

   - `conan install <conanfile>` is actually meant to install the dependencies into the cache, not the package binaries into the filesystem. It also downloads recipes form remote servers, so it's useful to set the stage for building of a final product.

   - But behold: `conan install Package/version@` actually *does* install the package, i.e.    if called with a full package reference. *However* `conan install <conanfile>` does _not_     install the package itself, directly from source. As far as this peasant can tell, there's     no way to do that using s one-liner in the Conan CLI, right?

   - `conan build <conanfile>` builds the current source tree (no reference), locally.   Useful e.g. for daily development, or for running (non-installable) unit tests, but not     for actually getting the binaries into the production tree.

   - `conan create <conanfile>` creates (i.e. compiles) the package and     stores (installs?) it into the local cache. It can do so freshly from     a source, no need to call `conan export <conanfile>` prior to that.

   - `conan inspect <conanfile>` finally gives all kinds of useful info about the product.

So, in essence, if I want a Conan package installed into the current system's `/usr/local`, the only way is to call `conan install Package/Ref@` on it.

If that package isn't known to the local cache (e.g. because I have a source tree with a conanfile in front of me), I need to make sure that package lands in the local cache _first_. So to put a source tree into production, I need to follow this protocol:

  - call `conan create <conanfile>` to install/compile dependencies into local cache
  - call `conan inspect <conanfile>` twice to construct the correct reference `Package/ver`
  - call `conan install -if /usr/local Package/ref@` on the _reference_ I just obtained.

So... the question: is that correct? Or am I just "doing it wrong" and there is another, more elegant, preferred solution to going about it?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

PS: Tongue-in-cheek humor and joking aside, you guys did a formidable job with developing Conan! Hats off and thanks a ton for all your time! :-)

**Comment by memsharded** [comment]
> So... the question: is that correct? Or am I just "doing it wrong" and there is another, more elegant, preferred solution to going about it?

What you are exposing is mostly right. The key point in that journey is that Conan was born as a language (C/C++) package manager for developers and development. It was never intended to install or deploy things at the system level. With the time, it gained some features that can be used/abused for that, like the ``deploy()`` method, which was intended to collect things from the cache in a user folder, but that can be used to collect those things and put them directly into the system.

> call conan inspect <conanfile> twice to construct the correct reference Package/ver

This might be unnecessary, why do you need it. You can get directly from the output of the ``conan create`` (which IIRC can also output some json if necessary)

> So, in essence, if I want a Conan package installed into the current system's /usr/local, the only way is to call conan install Package/Ref@ on it.

The thing is that a conanfile.py in your user folder is NOT a package. It is just a package recipe. Until it is given a Conan "reference" or "entity" or "name", it is not a package yet. As we call it, it is a pure ``consumer``, but not a package. And as such, it cannot be installed, and when a ``conan install <path>`` is called over a consumer conanfile, it can only install its dependencies, but not itself, because it is not even a package. It didn't even built binaries, or might not have the details (like a conanfile.txt) to build a binary at all.

Conan 2.0 is improving the CLI, so the install will be:
```bash
$ conan install <path/to/conanfile.py>
$ conan install --requires=<reference, like pkg/version>
```
This illustrates better in the second case, that it is equivalent to have a local conanfile.txt with a ``[requires]`` section that includes ``pkg/version``

Conan 2.0 will also have a new thing: "deployers". Which is user code that can be used to do any operation also at ``conan install`` time. It might still be useless on a consumer conanfile if it didn't manually build something, but the flexibility will be there. Probably the flow to create something and deploy it will be just like:

```
$ conan create . --name=pkg --version=0.1
$ conan install --requires=pkg/0.1 --deploy=mydeploy
```

**Comment by codedump** [comment]
Thanks for the clarification!

In particular this:

> The thing is that a conanfile.py in your user folder is NOT a package. It is just a package recipe. 

makes a lot of sense. It's easy to forget that conceptual background when you put your `conanfile.py` within your source tree.

Cheers.
