### ISSUE TITLE
[question] Migration pathway for IDE integration generators in conan 2.0

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#10751]
Recently, there has been a migration of a number of generators to the `conan.tools` namespace, presumably in preparation for conan 2.0. I've [read recently](https://github.com/conan-io/conan/issues/10559#issuecomment-1036662992) that the `layout()` method will only apply to generators in this new namespace. This leaves me wondering, what will happen to existing generators that don't seem to have had a replacement in this migration? The rumor mill has indicated they will be deprecated, so I'm seeking some clarity here.

I'm thinking specifically of IDE integration generators such as the [ycm](https://docs.conan.io/en/latest/integrations/ide/youcompleteme.html) or [visual_studio](https://docs.conan.io/en/latest/reference/generators/visualstudio.html) generators, which play an integral part of my tooling (especially ycm though) - what is the future these kinds of generators in conan 2.0?

I might have completely misread the situation here, but either way it would be good to get some clarity.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
- ``visual_studio`` generator is superseded by ``MSBuildDeps`` and ``MSBuildToolchain`` generators. Those two already implements the ``visual_studio`` capabilities (and more).
- ``ycm`` will be possible via a "deployer". Deployers are different in the sense that they are only for consumer local flow, but recipes don't declare a ``ycm`` generator, because they don't need it at all. The syntax will be as ``conan install --deploy=ycm``. Deployers will be more flexible, users will be able to provide their own ones easily (via ``conan config install``)

**Comment by samuel-emrys** [comment]
Perfect, that sounds great, thanks for the clarification @memsharded.
