### ISSUE TITLE
[question] What does requires package status `no remote` mean?

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#10772]
When you run `conan install` and the requirements are resolved, they will be listed with their current status: `Cache`, `Downloaded`, and `No remote`. What does `No remote` mean and how can I get into this state?

Example:
```
LibA/1.2.0 from 'myserver' - Cache
LibB/3.31.0 from 'myserver' - Downloaded
LibC/9.1.0 from local cache - No remote
```

We've run into issues with binaries not being found for the recipes listed as `No remote` cause the package id isn't what we expect; presumably cause the recipe isn't the one we expect. 

We're using package_id_mode = recipe_revision_mode and we're specifying the recipe revision for all the requires packages.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The ``No remote`` means that the package was created locally, with a ``conan export`` or ``conan create``, so it was not retrieved from a server (and it was also not uploaded to a server).

This could happen also when a package is retrieved from a remote, and the remote is removed (``conan remote remove``), then the connection to the remote is lost.

**Comment by nichmj01** [comment]
Ah.. I see. 

If I export a recipe locally using `conan export` such that the export is "newer" than the recipe on the server, then my guess is that `conan install --update` will not download from the server?

That is, say `my_package/1.0.0#10` is the latest recipe and was uploaded to the server at 9:00am. I use `conan export` to export `my_package/1.0.0#5` (an older version of the recipe such that `#10` should be used) at 10:00am. If I run `conan install --update` `my_package/1.0.0#10` will not be downloaded? Either because `#5` is considered "newer" in the cache or because there is no remote associated with `my_package`?

**Comment by memsharded** [comment]
Hi @nichmj01 

Sorry this was not followed up back then

> If I export a recipe locally using conan export such that the export is "newer" than the recipe on the server, then my guess is that conan install --update will not download from the server?

The ``--update`` will always update from the server in Conan 2, this has changed, because Conan 1 behavior of tracking remotes was overall confusing

> That is, say my_package/1.0.0#10 is the latest recipe and was uploaded to the server at 9:00am. I use conan export to export my_package/1.0.0#5 (an older version of the recipe such that #10 should be used) at 10:00am. If I run conan install --update my_package/1.0.0#10 will not be downloaded? Either because #5 is considered "newer" in the cache or because there is no remote associated with my_package?

Yes, the local exported is considered "newer", and it will not be updated with a ``--update``. This was also necessary to preserve the general user expectations, that were very confused by getting their just exported thing with a newer timestamp to be replaced by an older one from one of the server remotes

I am closing this ticket as outdated (it referred to Conan 1 back then), but please create new tickets for any further question. Thanks for your feedback.
