### ISSUE TITLE
[bug] `conan remote list_ref` and `conan remote list_pref` don't work if you have editable packages

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#10776]
If you try to use `conan remote list_ref` or `conan remote list_pref` while you have any editable packages you get:
`ERROR: Operation not allowed on a package installed as editable`

It seems like you should be able to skip over the editable packages or list them as editable in the output?

This is especially strange with `list_pref` since it gives the error even when the provided reference is not editable.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2017
  * Conan version: 1.44.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)

* Verify there are no editable packages
* Run `conan remote list_ref`
* Add editable package
* Run `conan remote list_ref` --> error

**Comment by memsharded** [comment]
These commands were removed in Conan 2, closing this ticket as outdated.

**Comment by datalogics-robl** [comment]
What's the equivalent replacement for `conan remote list_ref` in Conan 2? How do you specifically get a list of all packages in the local cache along with which remotes they came from?

**Comment by memsharded** [comment]
Hi @datalogics-robl 

Conan 2 removed the association between a package/recipe in the cache and the remote they were downloaded from, because it was quite problematic.

With ``revisions``, which are always enabled in Conan 2, this is not really necessary anymore.

You can do ``conan list pkg/version#revision -r="*"`` to find a specific recipe revision in all servers. You can use its json output for automation.

You also have the ``conan pkglist find-remote`` command for this purpose.

Still, in theory this practice of finding the remotes for packages in the cache shouldn't be that necessary in Conan 2, see for example the CI tutorial in https://docs.conan.io/2/ci_tutorial/tutorial.html, to see how remotes and pkg-lists can work together in CI.
