### ISSUE TITLE
[bug] Packages not compatible with cmake's `install(IMPORTED_RUNTIME_ARTIFACTS ...)`

### ISSUE THREAD

**Issue by SimonHeybrock** [conan-io/conan#10788]
cmake-3.21 added [IMPORTED_RUNTIME_ARTIFACTS](https://cmake.org/cmake/help/latest/command/install.html#imported-runtime-artifacts). This can be used something like this (TBB is just an example here) to install:

```
find_package(TBB CONFIG REQUIRED)
install(IMPORTED_RUNTIME_ARTIFACTS TBB::tbb RUNTIME DESTINATION ${MYDIR})
```

This does not appear to work with targets from packages that are installed by conan.

As a concrete example: The above code snippet works fine with TBB installed via `conda`, but *not* when TBB is installed with `conan`. The error is the same as described in https://gitlab.kitware.com/cmake/cmake/-/issues/22406:

```
CMake Error at CMakeLists.txt:5 (install):
  install IMPORTED_RUNTIME_ARTIFACTS given target "TBB::tbb" which is not
  an executable, library, or module.
```

- As far as I can tell this is not specific to certain packages.
- As far as I can tell, this comes from the `*Target-release.cmake` that is generated by `conan`, which defines targets with type `UNKNOWN`.

**Comment by memsharded** [comment]
I think this issue is duplicated with https://github.com/conan-io/conan/issues/10181, and there is an initial attempt to fix it in https://github.com/conan-io/conan/pull/10497, because it is related to the fact that Conan is using UNKNOWN targets.

So closing this, please track those tickets.

I would also recommend having a look to the ``imports()`` and ``deploy()`` Conan 1.X features, but more importantly to the 2.0 new ``deployers``, which will be very flexible and powerful for this kind of tasks.
