### ISSUE TITLE
[question] Declare system library dependency for a single component only

### ISSUE THREAD

**Issue by steromano87** [conan-io/conan#10833]
I'm developing a library (let's call it `myLib`) that is split in multiple components (let's assume, for simplicity, `compA` and `compB`).
Component A needs a system library during compilation and runtime (`libssl`), while component B does not need it.

In the `package_info` and `system_requirements` sections of my Conanfile, now I write something like this:

```python
from conans import ConanFile

class MyConanFile(Conanfile):
    def package_info(self):
        self.cpp_info.components["compA"].system_libs = ["ssl"]
        # Nothing added for component B

    def system_requirements(self):
        # This system dependency applies only to Component A
        Apt(self).install(["libssl-dev"], update=True, check=True)
```

However, when I consume my library in another package, the system dependency is installed even if I only declare as required dependency the `compB` component.

Is there a way to limit the scope of the system dependency only to a single component (or to a subset of components)?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @steromano87 

This is not possible, because package installation is decoupled from package consumption. You install one package, with all its files, binaries and headers. All the components are always installed. The components declaration is used for consumption, to avoid linking with more libraries than needed. But once the package is installed, it can be used in different projects, with different components usage, without reinstalling it.

Then, the installation of system requirements for the package also needs to be irrespective of components. ``system_requirements()`` will not be re-evaluated differently depending on the components usage.

**Comment by steromano87** [comment]
Hi @memsharded, thanks a lot for the answer.

One last question, in case of build-only system packages requirements, is there a way to skip the installation of such packages in consumer projects, since some of them may break existing installations?

Let's assume that my original package `myLib` requires a system package at compile time only (but not at runtime), and installing the same system package in the environment where a consumer project is built breaks the environment itself (due to package incompatibility).
Is there a way (apart from installing the required dependency outside Conan) to avoid the system package requirement to leak into the consumer package?

**Comment by memsharded** [comment]
> Is there a way (apart from installing the required dependency outside Conan) to avoid the system package requirement to leak into the consumer package?

Yes, I think this would be a case for putting that system_requirement inside a "proxy" ``mysystempkg/system`` package, that then can be used as a ``tool_require`` for other recipes. As ``tool_require`` will not be used if not necessary to build from source, you will achieve that behavior.

**Comment by steromano87** [comment]
Thanks a lot! I'll try this way.
