### ISSUE TITLE
[question] Support of percent-encoded passwords for tools.Git

### ISSUE THREAD

**Issue by beutlich** [conan-io/conan#10854]
Does the Git tool support percent-encoded passwords? It looks to me that it was supported by Conan 1.32.0, but no longer by later versions. Thanks for your clarification.

```py
from conans import tools
import urllib
password = urllib.parse.quote('special!$%', safe='')
git = tools.Git('path/to/repo', username='user', password=password)
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
I don't see at first sight anything evident in code that changed regarding that.

In any case, that tools is being superseded by new ``from conan.tools.scm import Git``, introduced in https://github.com/conan-io/conan/pull/10594, docs in https://github.com/conan-io/docs/pull/2419. At this moment, it doesn't have any feature regarding authentication, this is an important thing that needs to be taken carefully. We are going to try to avoid using user/password auth if possible, specially as all Git providers are deprecating it (might still be possible with user/password env-vars, not with the values directly). We are trying to avoid at all costs to have a password leak due to some Conan logging, printing, etc. If you can briefly summarize your needed auth and plans regarding this, it would be useful.

**Comment by beutlich** [comment]
Thanks for the fast reply. I analysed some more details and finally found that 5c09f3ec15c4f5e69b131ea0c99196780a28e29b (for 1.33.0) broke our workflow where we already passed percent-encoded passwords to the SCM tool.

@danimtb FYI

**Comment by memsharded** [comment]
Yes, apparently it was declared as a bug, and fixed in https://github.com/conan-io/conan/pull/8355 (long time ago).

In any case, the feedback over the new integration ``from conan.tools.scm import Git`` is appreciated if possible.
