### ISSUE TITLE
[question] How to use Conan with C# Projects?

### ISSUE THREAD

**Issue by Bassem-Ramzy** [conan-io/conan#10852]
Hi,
I know that Conan is designed to target C/C++ projects, but I can't think of reasons why it can't be used with `C#`, and I didn't really find documentation illustrating that _in specific_.

So, my questions is:
Can I use Conan with C# projects? if yes, then how? e.g. following [How to create and reuse packages based on Visual Studio](https://docs.conan.io/en/latest/howtos/visual_studio_packages.html) for C# projects.

Thanks,

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Bassem-Ramzy 

Yes, there is no reason Conan couldn't be used for other languages. We had solid examples about using it for Go projects before go modules existed. There are users using it for LabView for example (https://www.youtube.com/watch?v=HtXDkFVo56s), and we have seen it also used for Matlab, to manage full OS iso images, or for Fortran too.

For C# we are not aware of extended usage, but it should be possible, don't know what amount of custom integrations would be necessary. Not sure about the overall value, because nuget is already very extended for that, and it seems it is already kind of the industry standard, so no matter if good or bad, but probably overall is worth to stick to it.
