### ISSUE TITLE
[question] How to set `cmaketoolchain:user_toolchain` for dependency?

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#10850]
We have the following profile:

```
[settings]
os=Macos
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=12
compiler.libcxx=libstdc++11
build_type=Release

sdl:compiler=apple-clang
sdl:compiler.version=12.0
sdl:compiler.libcxx=libstdc++

[env]
sdl:CC=/usr/bin/clang
sdl:CXX=/usr/bin/clang++

[conf]
tools.cmake.cmaketoolchain:user_toolchain = path-to-our-toolchain.cmake // defines the clang compiler... (NOT APPLE CLANG)
```

1. Is is possible to set these overwrite for `sdl` also inside the `conanfile.py` ? This would be very nice, we have not found a way in the documentation which shows that? Is it not possible?

2. How can we inspect the invocation of CMake when conan builds the package? 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by franramirez688** [comment]
Hi @gabyx 

You can set the `[conf]` for any dependency as well:

* If you're using Conan >= 1.46, the configuration field `tools.cmake.cmaketoolchain:user_toolchain` only admits a list-like python-format:
```
[conf]
sdl:tools.cmake.cmaketoolchain:user_toolchain = ["path-to-our-toolchain.cmake"]
```
* Otherwise:
```
[conf]
sdl:tools.cmake.cmaketoolchain:user_toolchain = path-to-our-toolchain.cmake
```
And, no, it's not possible to set this value for your dependencies inside of your `conanfile.py` because of the possible rising of conflicts.

**Comment by gabyx** [comment]
Thanks alot!
