### ISSUE TITLE
[bug] .gitignore preventing .git internal files being copied to cache

### ISSUE THREAD

**Issue by ldobinson** [conan-io/conan#10861]
It seems that adding a path to the .gitignore of an scm conan recipe with sources can cause files under the actual .git directory itself to be excluded from the conan cache. Recipes relying on git info at build time could potentially be broken by this.

### Environment Details:
  * Operating System+version: Ubuntu 18.04 LTS
  * Compiler+version: N/A
  * Conan version: 1.46.2
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)
```
mkdir temp && cd temp
conan new foo/1.2.3 -s

Add the following to the conanfile:
scm = {
    "type": "git",
    "subfolder": ".",
    "revision": "auto",
    "url": None
}

echo '*test*' > .gitignore

git init && git add . && git commit -m "Init"

git checkout -b test

ls .git/refs/heads # this should show master and test refs

conan create .

ll /path/to/conan/cache/foo/1.2.3/_/_/build/packageID/.git/refs/heads
You will see only the master ref.

```
#### Expected behavior
I would expect the .git directory in the cache build dir to have the same contents as the recipe dir.

**Comment by memsharded** [comment]
The ``scm`` feature is being removed in Conan 2.0. I would recommend having a look to https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html new feature that will replace it. It will no longer do file copies, but it will always be a ``git clone`` in the cache, so that problem should be gone.

**Comment by memsharded** [comment]
Closing this ticket as inactive. Some summary:

- It is not expected to export/copy the full .git folder to the Conan cache, this is an anti-pattern.
- The recipe shouldn't rely on this.
- There are features like https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html to handle the checkout from repos instead of the ``export`` of files

Please create new tickets if necessary, thanks for the feedback
