### ISSUE TITLE
CONAN_CXX_FLAGS are not set in case of CMake targets

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#1087]
I've noticed CONAN_CXX_FLAGS are not set in case of CMake targets, is it by intention/design or just overlook?

for example, if I clone https://github.com/lasote/conan-zlib.git and add the following two lines into **test_package/CMakeLists.txt**:
```
message(STATUS "CONAN_CXX_FLAGS ${CONAN_CXX_FLAGS}")
message(STATUS "CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS}")
```
**conan test_package** command will output (on linux x64):
```
-- CONAN_CXX_FLAGS  -m64
-- CMAKE_CXX_FLAGS   -m64
```
changing **test_package/CMakeLists.txt**:
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
CONAN_BASIC_SETUP(TARGETS)
```
will produce
```
-- CONAN_CXX_FLAGS  -m64
-- CMAKE_CXX_FLAGS 
```

**Comment by memsharded** [comment]
It is by design. The setting of global C++ flags is done in the ``conan_global_flags`` macro:
https://github.com/conan-io/conan/blob/develop/conans/client/generators/cmake_common.py#L304

This is only called if not using ``TARGETS``. The main purpose of using targets is precisely not having to set the flags, include_dirs, libs, etc at the global level, but per package/target, and let CMake target transitivity handle it, so you could end with different flags in different consumer executables, because they are linking different packages/targets, even if they are declared in the same dependency graph.

**Comment by SSE4** [comment]
@memsharded thanks for the explanation! ticket can be closed
