### ISSUE TITLE
[question] How do we build dependencies with sanitizer flags?

### ISSUE THREAD

**Issue by Zephilinox** [conan-io/conan#10895]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Currently we're using Conan and CMake and we have enabled sanitizer flags (asan, ubsan, tsan, etc) for our cmake targets. Some sanitizers (such as thread sanitizer) require that all libraries we link to are also built with sanitizers enabled.

We use `conan_cmake_run` with `BUILD missing` to build dependencies locally and on CI as needed.

I've done some looking around and I'm confused how to achieve this without modifying every single dependencies `conanfile.py` or `CMakeLists.txt` to build with sanitizer support (e.g by appending to the `CFLAGS`, `CXXFLAGS`, and `LDFLAGS`). The information on https://docs.conan.io/en/latest/howtos/sanitizers.html seems to suggest modifying the profile, but as far as I can tell the profile doesn't determine anything about how the dependencies will link to these sanitizers, and many dependencies will be lacking support for it.

The hook suggested on that documenation page seems interesting if it only needs to be applied to our projects `conanfile.py`, which would be nice, however modifying these environment variables means CMake will overwrite its default (or per-dependency specialised) flags, where as we need to append to them (please correct me if I'm wrong however)

**Comment by memsharded** [comment]
Hi @Zephilinox 

Yes, Conan is a package manager, not a build system. You cannot tell Conan some compiler flags, and they will be magically passed to every recipe, because the recipes and the build systems might not use them at all. It is the responsibility of every recipe and every CMakeLists to define compiler flags. The challenge there is the variability on how every build system allows passing information, and Conan hasn't had anything built-in so far.

The good news is that we are finally adding something. It will still be a challenge for recipe creators when the build system scripts are complicated, but we will at least propose some standard way to define the information in Conan and how that information is provided to recipes and toolchains. We will try to implement it in our controlled toolchains like ``CMakeToolchain`` or ``AutotoolsToolchain``. 

This has been merged https://github.com/conan-io/conan/pull/10800 and will be released in Conan 1.47 very soon. So I am considering this issue closed and implemented by it. Please try it when released, and create new issues for it if necessary, feedback will be welcome.

**Comment by Zephilinox** [comment]
Thanks :)

**Comment by johnmcfarlane** [comment]
Is it wise to put toolchain-specific information (i.e. compiler flags) in the build system configuration (i.e. CMake files) or package management (conanfile)? These seem like something which should be put in profiles in order to avoid coupling projects to toolchains.

**Comment by memsharded** [comment]
> s it wise to put toolchain-specific information (i.e. compiler flags) in the build system configuration (i.e. CMake files) or package management (conanfile)?

In general, it is not recommended to put specific compiler flags in ``CMakeLists.txt`` files, but they should belong to CMake toolchain.cmake files that are passed to CMake, so it is easier to build the same project with different sets of flags, compiler, or toolchains in general without having to touch the project ``CMakeLists.txt``. This is kind of good practice from CMake, not something specific to Conan.

Once that flags are in a CMake toolchain file, that file can be automatically injected by Conan with:
```
[conf]
tools.cmake.cmaketoolchain:user_toolchain+=rpi_toolchain.cmake
```
(Note the ``+``, as it is a list, and multiple toolchains can be injected. Also relative paths are allowed with ``{{profile_dir}}`` so the toolchains can be distributed together with profiles with ``conan config install`` easily if desired.

The limitation of this approach is if there are dependencies not using CMake as build system. In that case, yes, it would be necessary to define ``tools.build:cxxflags`` or similar mechanisms in the profile, to be able to inject those compiler flags into those dependencies too.

**Comment by johnmcfarlane** [comment]
Thanks. Glad we agree that CMakeFiles are the wrong place for compiler flags.
