### ISSUE TITLE
[bug] deps_env_info is empty when calling package_info()

### ISSUE THREAD

**Issue by smoofra** [conan-io/conan#10893]
I'm not sure if this is a bug or a feature request, but here's what I'm trying to do.

The docs say private requirements "might be necessary in some extreme cases, like having to use two different versions of the same library".   That's what I'm trying to do.     I have a package called "go", which contains the golang toolchain.  I have another package that wants to use two different versions of it.   This is what I thought would work.   I introduce a new package called "go_1_11" that includes "go", and re-exports its PATH.

The root package can then require `go_1_11/[~1.11]` and `go/[~1.18]`.  This almost seems to work.    The root package does have both versions of go in its dependency graph.   But the part about re-exporting PATH doesn't work.    `deps_env_info` is empty when `package_info()` is called.

```
from conans import ConanFile, tools

class Go_1_11_Conan(ConanFile):
    name = "go_1_11"
    version = "1.11"
    settings = ("os", "arch")

    requires = [('go/[~1.11]', 'private')]

    def package_info(self):
        self.env_info.path.extend(
            self.deps_env_info['go'].path. # raises KeyError('go') here
        )
```

**Comment by memsharded** [comment]
Hi @smoofra 

I think the initial assumption is wrong. The ``private`` packages should be completely private, you cannot simply re-export its path. When private packages are not required, because they are transitively hidden, they will not be fetched/downloaded at all. In this case when ``go_1_11`` is already there, as ``go/1.11`` is a private version, it will not be used at all, and its information will not be there, so you cannot re-export it.

Why not just packaging the golang, exactly in the same way? You might use exactly the same recipe of ``go`` package, just remove the ``name`` attribute and package like:

```bash
conan create . go/1.11@
conan create . go_1_11/version@
...
```

**Comment by smoofra** [comment]
> they will not be fetched/downloaded at all

@memsharded  Are you sure that's right?    I tried creating a package that depends on `go_1_11` and `go/1.11` was still included in the `conan.lock` file for that parent project.  If it's completely hidden it shouldn't be visible at all right?

**Comment by memsharded** [comment]
``private`` dependencies are discouraged, because they have so many rough edges. It might be possible that lockfiles still references them, but they do not propagate any kind of ``xxxx_info`` downstream

**Comment by smoofra** [comment]
I get that they're discouraged but I am trying to use them for the one thing the documentation says they're good for.    If they can't be used for that maybe the documentation should be changed?

I'm a bit confused by what private dependencies are for.   If they can only be used at build time  by packages that directly require them, isn't that the same behavior as `tool_requires` dependencies?    

The way I thought they worked was that they were present in the dependency graph of packages that transitively require them, but that the xxx_info was not propagated out.   But if that's the case, and there is no way to manually propagate information from them, then what's  the point?   What can you do with them?    Do you know of any example of private dependencies being used correctly that I could learn from?

thanks :)

**Comment by memsharded** [comment]
> I'm a bit confused by what private dependencies are for. If they can only be used at build time by packages that directly require them, isn't that the same behavior as tool_requires dependencies?

the main difference is that ``tool_requires`` live in the "build" context. They will get injected the build profile. A ``private`` dependency is similar to a ``tool_require`` in the sense that is not propagated downstream, but it will get the "host" context and profile.

As a dependency in the "host" context, it is intended to propagate the c++ build information, like ``cpp_info.libs``, ``cpp_info.includedirs``, but not to propagate the ``env_info`` because the information from environment is intended for build tools (in the build context). So when the docs say that it is good for multiple versions, it means for multiple "library" dependencies versions, typically hidden ("private") behind some binary artifact, like a static library linked inside a shared library, that is the consumed artifacts.


For you use case, I think you want to explore all the new integrations and 2.0 ready mechanisms (already available in 1.X):

- ``self.dependencies`` to explicitly navigate and get information from dependencies, filtering by context if you want to like ``self.dependencies.build``: https://docs.conan.io/en/latest/reference/conanfile/dependencies.html
- The new ``buildenv_info`` and ``runenv_info`` definitions, together with the new ``VirtualBuildEnv`` and ``VirtualRunEnv`` generators. https://docs.conan.io/en/latest/reference/conanfile/tools.html

Or, the more pragmatic suggested above creation of ``go_1_11`` package that doesn't depend at all on the ``go`` one.

**Comment by smoofra** [comment]
thanks for the explanation

**Comment by smoofra** [comment]
@memsharded I've turned this into a [feature request](https://github.com/conan-io/conan/issues/10937)
