### ISSUE TITLE
Case-Sensitive package opencv causes problems

### ISSUE THREAD

**Issue by Brunni** [conan-io/conan#1090]
Hi,

on my windows machine I have issues when switching between different opencv versions, as the folder ".conan\data\OpenCV\" exists with casing and if I then switch to opencv/3.1.0@lasote/vcpkg I get an error message by conan, that the folder already exists but with different casing.

So actually you should prohibit to upload different packages with different casing, I guess.

Greets
Michael

**Comment by memsharded** [comment]
Yes, this is an issue, but a Windows limitation, not a conan issue. The thing is that you cannot prohibit to upload different packages with different cases because conan is decentralized. You might get different packages from different remotes too, and is totally impossible to check all remotes. The only way would be to enforce the case (probably lowercase) for all packages, always, which is not feasible.

Also, we try very hard to not impose other constraints. Linux users they don't have such problem, and they are happy with different case packages. Should we forbid them to do so?

So the possible solutions if you are working in Windows and have this limitation could be:
- Remove the old package prior to installing the conflicting case one with ``conan remove``
- Use a different cache, setting a different ``CONAN_USER_HOME`` and switch when necessary.
