### ISSUE TITLE
Python 2 vs Python 3 version issues with "print"

### ISSUE THREAD

**Issue by Brunni** [conan-io/conan#1091]
Hi,

I just discovered after installing python 3 that some of the packages are not working anymore as the python file contains print command instead of print function:

https://conan.io/source/OpenCV/3.1.0/oslh/stable

So I had to remove the print statements locally, but then I cannot publish it, as it would not have the binary packages anymore.

How can we deal with this?

Greets
Michael

**Comment by lasote** [comment]
You should open an issue in the recipe repository (if exists), and ask for use always braces with print.
There is no way to always guarantee the recipes compatibility between py2 and py3.

**Comment by memsharded** [comment]
If you are using recipes from conan.io, you might be safer using python 2, as it seems is the most popular one among conan users. Otherwise, yes, for those simple issues, the best is:
1. Fork the original package recipe in github
2. Clone your fork
3. Fix the recipe
4. conan test_package, check everything works
5. Commit changes, push to your fork in github and do a PR to the original package author
6. Typically the original package author would have travis & appveyor builds, so binaries will be regenerated automatically after merge. If not, check how to do it, and collaborate with them to do it, much more convenient than generating binaries manually.
