### ISSUE TITLE
[question] How to use conan as executable package manager

### ISSUE THREAD

**Issue by netheril96** [conan-io/conan#10949]
I read many parts of conan.io docs, but still cannot wrap my heads around its management of executables. Surely it has been a great project for managing libraries and dependencies, but what about using it for executables? Like I can install cmake with Homebrew `brew install cmake` or apt easily `sudo apt install cmake`, but how do I do that in conan? It seems to me that I have to write it in a `conanfile.txt`, and when I install it, the installed cmake will reside in a obscure directory only accessible to my current build, not available globally.

In addition, if I want to package my repository whose end product is an executable for users to run, instead of a library other programmers depend on, how do I do it? I cannot find the answers in the docs.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @netheril96 

It is true that Conan is a package manager for developers. It is not intended to install applications at the system level, but to install libraries, and occasionally executables at the user level. Conan will never modify your system, adding anything to the path, or putting files in another location rather than the Cache folder.

Said that, there are various tools and functionalities to achieve that. And some others will come in next Conan 2.0 (now in alpha).

The first one, I'd recommend is:

```
$ conan install cmake/3.20.0@ -g VirtualRunEnv
$ conanrun.bat # or source conanrun.sh for nix systems
$ cmake --version  # will run the cmake/3.20 from Conan
$ deactivate_conanrun  # to deactivate the virtual environment
```

**Comment by netheril96** [comment]
Well, I hope conan 2 will address this use case. Then I can tell my users to simply run `conan install myexecutablepackage` instead of dealing with homebrew choco apt yum pacman one by one.

**Comment by memsharded** [comment]
> Well, I hope conan 2 will address this use case. 

Conan 2 implement the ``deployers`` strategy, with ``conan install --requires=myexe/version --deploy=xxxx`` it is able to deploy the package in different ways. There are builtin deployers that will do a copy to the local user folder, but if you want to write a deployer that install system-wide, you will be able to do it.
