### ISSUE TITLE
[feature] conan download to target directory

### ISSUE THREAD

**Issue by eirikb** [conan-io/conan#10942]
It would be nice if [conan download](https://docs.conan.io/en/latest/reference/commands/misc/download.html) could have an option to specify target directory for the download.

1. We want this for our legacy build system that will look for a library source by folder. This way we can support both `conan install` and legacy `make` files using same `conanfile.txt`
2. Makes it easier to peek into a package by making it end up in current directory
3. Makes it easier to compare against package already downloaded to `.conan` folder

**Comment by memsharded** [comment]
Some related things:

- Conan 2.0 use the deployers (as ``--deploy=full_deploy``) to ``conan install`` command to do local copies in user folder (as specified by the deployer, it could be a copy, or just selected files).
- Conan 2.0 deployers only work for ``conan install``, they visit the ``conanfile.dependencies``, doing copy over them.
- Then, they will not work over ``conan download`` because that doesn't even parse the conanfile, and it doesn't compute the ``.dependencies`` at all
- We have discussed in the past how a ``conan cache path <pkg-ref>`` could be useful for this kind of flow. Basically a ``conan download <pkg-ref>`` + ``cp -R 'conan cache path <pkg-ref>' mycopy`` could work. Maybe it is time to discuss it again.
- A one step command that implements both ``download+copy`` would be straightforward with the 2.0 user custom commands + Conan PythonAPI

**Comment by memsharded** [comment]
``conan cache path`` command implemented in 2.0 in https://github.com/conan-io/conan/pull/11017, will be released next alpha.7.
