### ISSUE TITLE
[bug] version is not set correctly when using layout

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#10956]
When layout is being used, recipe version is not set correctly somehow using json generator, it seems that version is not being fetched from package metadata when running conan install command!

### Environment Details
  * Operating System+version: macos
  * Compiler+version:  apple-clang 12.0
  * Conan version: Conan version 1.47.0
  * Python version: 3.9

### Steps to reproduce 
* create a conan demo project using `conan new demo/1.0.0 --template=cmake_lib` 
* create a local conan package `conan create .`
* generate deps using json generator `conan install demo/1.0.0@ -g json`
* inspect conanbuildinfo.json, version is set to null, however it should be 1.0.0

* remove the layout method from the conanfile.py and try again
* now version is set correctly 

btw, it seems to be the same issue for the description attribute, maybe other attributes as well

![Screen Shot 2022-04-04 at 12 29 24 PM](https://user-images.githubusercontent.com/7117696/161534756-188564f8-7041-46aa-a774-df0c0d848296.png)

**Comment by boussaffawalid** [comment]
@lasote do you have any idea how difficult is this to fix ? or any temporary workaround I could use?

**Comment by lasote** [comment]
The fix is easy but very very dirty. The thing is, the layout() feature is part of the Conan 2 functionality and the "json" generator is currently not migrated to the 2.0 model, I don't think we are going to provide one at the core conan at 2.0, it might be suggested as an extension, but it would need to be implemented following the new dependencies model. If we can limit this fix to the `version` field, it might be ok, but the description is not available anymore at this point.
Anway if we finally decide to fix the `version` field it won't be available until the next release at the end of the month.

**Comment by boussaffawalid** [comment]
will be any alternative for json generator ? The thing we rely on the json generator for the final installer but at the same time we want to migrate to the new layout feature. Well at least fixing the version will be much appreciated.

**Comment by memsharded** [comment]
Yes. The ``--json`` output formatters of some commands might contain the whole graph information. If not, a built-in deployer can be added.
