### ISSUE TITLE
[question] How to share/reuse common scripts among multiple packages?

### ISSUE THREAD

**Issue by Bassem-Ramzy** [conan-io/conan#10950]
Hi,
I have common scripts (non-code: batches, configuration files, others) used by multiple projects AS IS, I want to have a single copy of those scripts somehow shared between and reused by the different packages, instead of having a copy of those scripts in every package. What is the best practice for that using Conan?

BTW, I need a copy of those scripts on the project local folder, and not only on conan cache, so they can be used by the project (build script/CMake/Visual Studio/etc...) during development.

Thanks,

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @Bassem-Ramzy,
There are a couple of approaches to do that. For example, you could package your scripts in a package that you can later require as a [tool_requires](https://docs.conan.io/en/latest/devtools/build_requires.html), in that package you can prepend the package folder where you store those scripts to the [buildenv_info](https://docs.conan.io/en/latest/reference/conanfile/tools/env/virtualbuildenv.html), so that you have those scripts in the path when you are building a consumer that tool_requires those scripts. For a simple case that you have a **consumer/1.0** that depends on **myscripts/1.0**:

myscripts recipe:

```python
...
class MyscriptsConan(ConanFile):
    name = "myscripts"
    version = "0.1"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "myscripts/*"

    def configure(self):
        del self.settings.compiler
        del self.settings.build_type
        del self.settings.arch

    def package(self):
        copy(self, "*.sh", self.source_folder, os.path.join(self.package_folder, "bin"), keep_path=False)
        bindir = os.path.join(self.package_folder, "bin")
        self.output.info("Appending PATH environment variable: {}".format(bindir))
        self.buildenv_info.prepend_path("PATH", bindir)
```

and the consumer:

```python
class ConsumerConan(ConanFile):
    name = "consumer"
    version = "1.0"
    tool_requires = "myscripts/0.1"
    ...
    def build(self):
        self.run("hello.sh")
```

Note that if you want to have the build environment available in your consumer you should set the [configuration](https://docs.conan.io/en/latest/reference/config_files/global_conf.html) variable: `tools.env.virtualenv:auto_use=True` 

You can also use the `generate()` method in the consumer recipe to bring files from the myscript tool_requires to the build folder, for example doing something like:

```python
class ConsumerConan(ConanFile):
    name = "consumer"
    version = "1.0"
    tool_requires = "myscripts/0.1"
    ...
    def generate(self):
        for dep in self.dependencies.values():
            copy(self, "*.sh", dep.cpp_info.bindirs[0], self.build_folder)

    def build(self):
        self.run("./hello.sh")
```

Hope this helps
