### ISSUE TITLE
[question] How to know value of the passed `-of OUTPUT_FOLDER` in `deploy()`?

### ISSUE THREAD

**Issue by Bassem-Ramzy** [conan-io/conan#10996]
Hi,
One of the arguments to `conan install` is `-of OUTPUT_FOLDER`. How to know its value in `deploy()` method? e.g. any attribute is available for it.
Thanks,

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Bassem-Ramzy 

It is not available, because the ``--output-folder`` intended usage is the new ``layout()`` to prepare things for 2.0, and ``deploy()`` is dissapearing in 2.0, so it is still using the legacy ``--install-folder`` (and that cannot be changed, because it will be breaking. If you pass also the ``--install-folder`` with the same value as ``--output-folder`` you can assume the ``cwd`` inside the ``deploy()`` method is that one.
