### ISSUE TITLE
Is it possible to Instruct Conan to download only direct dependencies

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#10990]
For Example:

demo_new/1.0.0 
requires 
demo_new2/1.0.0 
requires 
demo_new3/1.0.0

When running install . conan will download all transitive dependencies.
As such this command also download demo_new3/1.0.0

Is it possible to instruct conan to download only direct dependencies during this conan install . command.

**Comment by czoido** [comment]
Hi @VarunTej106,
It is not possible to not install transitive dependencies through a Conan install because those are needed for Conan to calculate the graph, possible inconsistencies and so on.
Maybe if you want to just download a dependency with no transitive dependencies, you can do that using the [conan download](https://docs.conan.io/en/latest/reference/commands/misc/download.html) command. With that command you can download **all** the binaries for all configurations on the server or just some specific packages. Please check the [docs](https://docs.conan.io/en/latest/reference/commands/misc/download.html) for more information.

**Comment by memsharded** [comment]
I think it is relevant to highlight that Conan 2.0 will download only the recipes for the whole graph (downloading the recipes is fast), but it will not download those binaries not needed for building or running, so it will be able to save a lot of download&unzip time. In any case, @czoido recommendation ``conan download`` is probably what you want now.

**Comment by ghost** [comment]
Have to Instruct Conan to use a different test dependency depending on pipeline mode.

In the test packages can be very huge and not in every step during the integration pipeline required. As such we would like to download these test dependencies only when required.

**Comment by memsharded** [comment]
> In the test packages can be very huge and not in every step during the integration pipeline required. As such we would like to download these test dependencies only when required.

Both ``test_requires`` and ``tool_requires`` they are only downloaded when the package needs to be built from sources. If the package is being installed, then they will not be fetched.

I think we can close this question, as the OP seems to have abandoned Github
