### ISSUE TITLE
[question] How to use self.run and VirtualBuildEnv to capture the output

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#11009]
Hi,

when using the `VirtualBuildEnv` generator, is it still possible to capture the output of a `self.run` command properly without any additional steps? At present the output of the `run` method starts with

```
Capturing current environment in /some_path/deactivate_conanbuildenv-<arch>.sh': 'Configuring environment variables'
<output I am interested in>
```

Setting `env` to `None` doesn't work as it implicitly activates `conanbuild`. Or is the idea to use redirection in future - but then the question is if it would be better to remove the `output` argument?

Best regards,
Markus

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by gpxricky** [comment]
A simple workaround would be to use any non existing name for the `env` argument, e.g. `Dummy`. But this looks like a very bad design, isn't it?

**Comment by lasote** [comment]
Maybe `env=""` but I think I didn't understand the underlying issue, Do you need to capture the output of a command to a variable or file? is something failing and not being printed to stdout? I don't know, how is that related to the VirtualBuildEnv generator.

EDIT: I tried and the `env=""` won't work. I'll open a PR to default to "conanbuild" instead of `None` to see if is there any other reason for that.

**Comment by memsharded** [comment]
Yes, I don't think that disabling the environment is the solution. If the environment file was generated in the first place, it is very likely that it is still needed. And the ``self.run()`` command will run the command prefixed with the environment script, so yes, that will probably output that information too. I guess the only alternative is to let the capturer filter the first lines if they don't want them. Because even if 2.0 uses redirection instead of ``output`` (and it does, it gets an ``stdout`` argument instead), you will still get that in the stdout stream.

**Comment by gpxricky** [comment]
Allowing `None` is fine for me at the moment, therefore I'll close this issue.
