### ISSUE TITLE
[question] tools.check_min_cppstd don't work as expected?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#11003]
I don't have `compiler.cppstd` setting in my profile.  Having read [the docs](https://docs.conan.io/en/latest/reference/tools.html#tools-check-min-cppstd) I expected

```python
    def configure(self):
        tools.check_min_cppstd(self, "17")
```
would succeed for gcc8 and msvc15 (they both support C++ 17). But that's not the case:
gcc8: `Invalid configuration: Current cppstd (gnu14) is lower than the required C++ standard (17).`
msvc15: `Invalid configuration: Current cppstd (14) is lower than the required C++ standard (17).`
Why?

**Comment by memsharded** [comment]
Hi @db4 

That tool is not about the current compiler supporting the C++ standard, but about the current configuration satisfying the constraint defined by the recipe. If not ``compiler.cppstd`` is specified in the profile, then the current compiler default (c++14 or gnu14 in your case9 is being used in the profile, and that is not enough to use that package, so it fails.

Just realized that we haven't backported the new ``from conan.tools.build import check_min_cppstd, valid_min_cppstd`` to 1.X, so adding this as a feature for 1.48

**Comment by db4** [comment]
Hi @memsharded 
 
> That tool is not about the current compiler supporting the C++ standard, but about the current configuration satisfying the constraint defined by the recipe. If not `compiler.cppstd` is specified in the profile, then the current compiler default (c++14 or gnu14 in your case) is being used in the profile, and that is not enough to use that package, so it fails.

OK. But what if I need  to check the maximum C++ standard supported by the current compiler, not the default one? I see in CCI recipes something like

```python
    @property
    def _compilers_minimum_version(self):
        return {
            "gcc": "7",
            "clang": "5",
            "apple-clang": "10",
            "Visual Studio": "15.7",
        }

    def validate(self):
        if self.settings.compiler.get_safe("cppstd"):
            tools.check_min_cppstd(self, "17")

        def loose_lt_semver(v1, v2):
            lv1 = [int(v) for v in v1.split(".")]
            lv2 = [int(v) for v in v2.split(".")]
            min_length = min(len(lv1), len(lv2))
            return lv1[:min_length] < lv2[:min_length]

        minimum_version = self._compilers_minimum_version.get(str(self.settings.compiler), False)
        if minimum_version and loose_lt_semver(str(self.settings.compiler.version), minimum_version):
            raise ConanInvalidConfiguration(
                "{} requires C++17, which your compiler does not support.".format(self.name)
            )
```
(each CCI recipe does it slightly differently) . A standard method of  doing that would be greatly appreciated!

And one more question if you don't mind. Raising `ConanInvalidConfiguration` in `configure` and `validate` methods is handled differently by `conan info` (returning exit code 6 and reporting INVALID ID respectively). Is it expected behavior?

**Comment by memsharded** [comment]
> OK. But what if I need to check the maximum C++ standard supported by the current compiler, not the default one? I see in CCI recipes something like

With our current thinking, this is not something that needs to be in Conan code. The maximum C++ standard that is supported by the compiler is written somewhere in the compiler documentation, so it doesn't need to be guessed or queried. Conan 2.0 will make the ``cppstd`` subsetting compulsory, it will no longer default to None being the one that is the compiler default one, but it will actually require ``c++14``, if the compiler default is c++14. And if you want another standard you will declare it explicitly in the profiles. If you provide a standard that is not supported by that compiler, then it will eventually fail, because it will not recognize the resulting compiler flag. 

Conan 1.X recipes need that code because they are changing on the fly the c++ standard they can be used, harcoded in the build system and irrespective of what Conan setting or default c++ standard is provided. This was a limitation in Conan 1.X that doesn't have a global mechanism to define that different c++ standard binaries are actually compatible. Conan 2.0 will provide this (at least this is what we are trying)

**Comment by lasote** [comment]
related https://github.com/conan-io/conan/issues/11062

**Comment by lasote** [comment]
We have merged this [PR](https://github.com/conan-io/conan/issues/11062) for the next conan2 alpha version. That contains a plugin (by default) that will check if the passed cppstd is valid for the selected compiler.
