### ISSUE TITLE
[question] test package fails to link

### ISSUE THREAD

**Issue by lambtonr** [conan-io/conan#11025]
Hi, i have created a library with a out of source recipe, under GCC my library is build and links in the test package, however under clang i get a linker error in the test package. 

i have made a minimal reproducible example [library](https://github.com/lambtonr/conan_library) and [recipe](https://github.com/lambtonr/conan_recipe). i think the issue lies in the fact i have used [project_options](https://github.com/aminya/project_options) repository for handling some cmake build stuff. Specifically i was wondering if [this](https://github.com/aminya/project_options/blob/main/src/Conan.cmake) is the cause. 

gcc ``conan create ./all 0.0.1@lambtonr/testing``
```sh
[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
[100%] Linking CXX executable bin/example
[100%] Built target example
HelloWorld/0.0.1@lambtonr/testing (test package): Running test()
Hello World! Release!
```

clang ``conan create ./all 0.0.1@lambtonr/testing``
```sh
[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
[100%] Linking CXX executable bin/example
CMakeFiles/example.dir/example.cpp.o: In function `main':
example.cpp:(.text+0xd): undefined reference to `ConanLibrary::HelloWorld()'
```
i assume the root cause is the `compiler.libcxx` i can see at the during the `create` the libstd differs:

```sh
HelloWorld/0.0.1@lambtonr/testing: Exported revision: 01f05fbe569d19a6a19806bc4eff8edf
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++
compiler.version=13
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

......

Conan executing: /home/ross/.local/bin/conan install /home/ross/.conan/data/HelloWorld/0.0.1/lambtonr/testing/build/80d3c8d077516ce6e7dc913ef92912e9172eae4c/source_subfolder --build missing --env CC= --env CXX=/usr/bin/clang++ --settings build_type=Release --settings compiler=clang --settings compiler.version=13 --settings compiler.libcxx=libstdc++11 --settings compiler.cppstd=11
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.cppstd=11
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=
CXX=/usr/bin/clang++
conanfile.txt: Installing package
```
i was wondering if (if this is the cause) i can rectify this in my recipe or if i would have to make a change to the project options implementation?

**Comment by lambtonr** [comment]
ok, fresh look at this and i understand what is happening, the conan ''create'' command uses the default profile as set up in the docker image:

```sh
$ conan profile show default                
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=13
compiler.libcxx=libstdc++
build_type=Release
```
where as calling 'build' from the recipe, the [conan.cmake](https://github.com/conan-io/cmake-conan) ``conan_cmake_detect_unix_libcxx`` makes the following configuration: 

```sh
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.cppstd=11
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=
CXX=/usr/bin/clang++
```

still not sure how to get around this, as i wish to use the [conan_package_tools](https://github.com/conan-io/conan-package-tools) to create a matrix build.

maybe this  this question is better directed to [cmake-conan](https://github.com/conan-io/cmake-conan).

**Comment by memsharded** [comment]
Hi @lambtonr 

Well, when I have seen errors because of ``compiler.libcxx`` differences, they are mostly link errors about the cxx11abi of std::string, not a missing library one, so not completely sure about that is the root cause.

Instead, I suspect that the double Conan usage could be related. It seems that the recipe calling ``build()`` which is calling the ``CMakeLists.txt`` of the library, which in turn is calling internally Conan again to resolve the dependencies because it happens to use the conan.cmake stuff. It is necessary to make sure that when building the package that is not used, I have had a quick look to the CMakeLists.txt and doesn't seem the case, but I might be missing something.

A couple of quick questions for context:
- Are you trying to contribute your library to ConanCenter, or is this just for your own purposes?
- Have you considered using a ``conanfile.py`` in your ``conan_library`` project? This is definitely possible, and while it might diverge a little from what you will submit to ConanCenter, it allows way more easy testing and development.
- ConanCenter reviewers might not accept a build that is using conan.cmake in the internal build, is it the first library you try to contribute?

**Comment by lambtonr** [comment]
Hi @memsharded 

Sorry for the late response, was away for the long weekend. 

As to answer you questions first: 
- I am not try to contribute these packages to the ConanCenter, the ones i am currently having these problems with are a proprietary code base (hence making the example). There are a few upcoming 3rd party libraries that i will be making recipes for that if permitted, and there is interest for i will contribute to ConanCenter. 
- Originally this is what i had done, and it worked back then, however between then and now i have rewritten all the cmake, not sure if the conanfile.py i had back then would have the same issue. The reason i migrated to follow a similar layout to ConanCenter is to limit the package creation single pipeline, rather than having to update all pipeline for a new compiler etc....
- The library that has this issue will not be submitted to ConanCenter and i have not come across any of our 3rd party libraries that used conan to manage its dependencies. 

I have found a solution to the problem: 

i have forked the [project_options](https://github.com/aminya/project_options) repository and added the following [code](https://github.com/lambtonr/project_options/blob/main/src/Conan.cmake)

```c++
if(CONAN_EXPORTED)
    #standard conan installation, deps will be defined in conanfile and not necessary 
    # to call conan again, conan is alreay running.
    include(${CMAKE_BINARY_DIR}/../conanbuildinfo.cmake)
    conan_basic_setup()
  else()
    # Detects current build settings to pass into conan
    conan_cmake_autodetect(settings BUILD_TYPE ${TYPE})
    ...
```

This seems to rectify the problem:

clang ``conan create ./all 0.0.1@lambtonr/testing``
```sh
[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
[100%] Linking CXX executable bin/example
[100%] Built target example
HelloWorld/0.0.1@lambtonr/testing (test package): Running test()
Hello World! Release!
```
and the build settings now match between the build and test package calls:
```sh
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++
compiler.version=13
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

....

HelloWorld/0.0.1@lambtonr/testing (test package): Calling build()
-- The CXX compiler identification is Clang 13.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: Compiler Clang>=8, checking major version 13
-- Conan: Checking correct version: 13
-- Conan: C++ stdlib: libstdc++
-- Configuring done
-- Generating done
```

**Comment by memsharded** [comment]
Hi @lambtonr 

Happy to know that you found a solution.

I would also like to take the chance to suggest some good practices and other suggestions:

- For your own libraries, it is probably better to handle them with a ``conanfile.py`` in the same repo that contains the source code. That simplifies the flows and the maintenance.
- I don't love the ``conan.cmake`` integration. I known calling Conan explicitly  with ``conan install`` + ``cmake ...`` requires a bit more effort, but in the long term it is usually better, more clean, less problems. 
- Also, for production usage, it is recommended to use your own defined profiles (and managed them with ``conan config install``), rather than relying on auto-detection or on the ``conan.cmake``. I would even 

If this is now solved, can we close the issue? Do not hesitate to open new issues if you have any further question. Thanks!

**Comment by lambtonr** [comment]
@memsharded thanks for the advice. 

i understand the ``conanfile.py`` in source implementation is a lot easier to work with, and that was my starting point, before migrating to out of source recipes. I will consider the trade off between this ease of implementation vs updating multiple pipelines for compiler releases.

 i will try this with one of my implementation to see how it works. I was not primarily using the project options repository for its conan implementation more so for its other features. 

i will look into this, in my pipeline implementation i am using [conan_package_tools](https://github.com/conan-io/conan-package-tools) to generate a matrix build for the library, it is my understanding that this will define its own profiles, so the ``conan.cmake`` and ``conan_cmake_autodetect`` will only really be used at development time not in the production pipeline.

Many thanks for you advice, i will close off this question.
