### ISSUE TITLE
[feature] Explicit patch() step addition for OSS Legal clearing

### ISSUE THREAD

**Issue by KarrokDC** [conan-io/conan#11049]
Conan currently defines a source() and a build() step (among others). But no separate patch().

This means that currently patching is either done in either the source() or build() step. This is inconsistent between recipes.

The issue this brings forward comes from OSS clearance processes within companies. For this process we need to provide the fully patched sources (without build artifacts).

If the patching happens to be done in the source() call, it allows is to create a neat patched-sources zip. If it happens to get patched in the build folder the in-source-building libraries generate the usual litany of build artifacts within the source folder.

In an effort to have distinct steps, I think it might be good to have a patch() step after source() and before build() to allow companies to gather clean patched-source packages for legal clearing.

Aside from the OSS clearing, it might also be good for other use to have this step explicitly defined and implemented across all existing recipes.

So far I've not found a good, consistent way to gather clean patched sources.

While I only have knowledge of the OSS process within my company, it might be good to gather feedback on this from others as well.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @KarrokDC 

This happens because there are 2 different ways to apply patches, not one, and both are reasonable use cases:

- Patching in ``source()`` method happens when the sources receive the same patches for all different configurations. As the contents of the "source" folder in the cache is just one, patches are applied to the source
- Patching in ``build()`` method is necessary when different patches are applied for different configurations. The "build" folder contains its own copy of the sources, so it is valid to patch it there, and the original contents of the "source" folder will not be modified, as this would be destructive for this use case.

So adding a ``patch()`` method does not eliminate the 2 different use cases, and would require to define at least a ``patch_source()`` and a ``patch_source_build()`` to differentiate them. As they would be called contiguously to the ``source()`` and ``build()`` methods respectively, there is not much value in adding them, and the effort to change all existing recipes for this new convention is big, so doesn't seem worth it.


> In an effort to have distinct steps, I think it might be good to have a patch() step after source() and before build() to allow companies to gather clean patched-source packages for legal clearing.

It is not clear how this would help for legal clearing. The patched sources are not re-packaged, only the final artifacts. And if you want to re-package the sources, it is just one ``copy()`` in the ``package()`` method, the possible existence of such a ``patch()`` method doesn't imply that such sources become part of the final package.

**Comment by KarrokDC** [comment]
First off, thanks for the elaboration.

The patched sources are a legal requirement for using OSS (at least that is what legal tells us ;-) ), in most cases, OSS requires the developer to provide the actual sources that were used for the binaries in their product, to check whether the licenses are properly adhered to. This includes a traceable process of applied patches (if any). A clean, patched source collection would allow that legal team to verify the "claims" of the developers regarding modifications on the base source of a particular library.
And said team would then be able to inform developers on actions to be taken to ensure adherence to whichever license.

The aim would also be to have 2 artifacts, one being the package() with binaries etc for building the product, and the separate zip/tar with the patched sources to enter into OSS clearance.

Binaries are not accepted in this validation process since it is impossible to verify whether modifications have been done to the original source.

copy() would in many cases still have a "polluted" state, for libs that build in-source, is that correct?

My proposal had the following in mind, where a user could do:
```
conan --source
conan --patch
MyPatchedSourcesZipperFunction()
conan --build
conan --package
```
or basically some user-defined stuff in-between stages, if they existed in this form.

I did already realize that it would not be a trivial thing to do before I made the initial ticket, and even if it was a proper solution it would take a long time for it to filter through to the recipes.

However in lieu of the above proposal, would there be any other way to retrieve post-patch sources without in-source building libraries dumping the source folder itself full of build-related files?

The only other alternative I would see is to copy the post-build source folder and have a massive list of things to delete from it to clean up build-related artifacts, which will likely be different for each library.

Thank you for your time and consideration either way.

**Comment by memsharded** [comment]
> The patched sources are a legal requirement for using OSS (at least that is what legal tells us ;-) ), in most cases, OSS requires the developer to provide the actual sources that were used for the binaries in their product, to check whether the licenses are properly adhered to.

This is not true for many of the most common licenses like MIT, and other permissive ones. For the ones that are not that permissive, like GPL, they are usually so problematic that they are avoided, because it doesn't imply that you should provide the patches, but you should also make your own source code open source with the same GPL license.

I think that gathering the Conan recipes that are used to create the packages is enough legal evidence in case it is necessary, they provide the full truth of the source code, which patches are applied, in which order and under what conditions. I really don't see the legal value of creating a tarball with the patched sources.

In any case, I think that such a process of gathering the patches could be a separate and decoupled one. You can for example write a ``generate()`` method in the consumer package that will iterate all the ``self.dependencies``, and for each one, obtain its ``conan_data``, because that is the place where the patches are declared, and generating a report file with all of them, in some desired format. Conan 2.0 already implement custom ``--deploy=mydeployer`` deployers to do this kind of tasks.

What you are suggesting in the middle of source and build is complicated, that might be doable only in the local flow, but the most common way to create packages with ``conan create`` will not allow that easily to do that.

**Comment by KarrokDC** [comment]
GNU (A)GPL has conditions where source disclosure is required
LGPL has requirements to add notifications of modified sources.
Apache requires notifications on modified files
CDDL has an explicit distribution obligation and notice requirement

GPL by default is indeed unusable for any commercial projects.

I think I will see if the conan recipe, and maybe a lock file would indeed provide enough information, if the patched sources are a no-go from a practical point of view (on either side :) )

Feel free to close, or keep it in mind if someone else with similar needs runs into a similar requirement.

Cheers

**Comment by memsharded** [comment]
> I think I will see if the conan recipe, and maybe a lock file would indeed provide enough information, if the patched sources are a no-go from a practical point of view (on either side :) )

Yes, I think this would be very complicated to be managed in the package creation flow, because there is no infrastructure for this (no folder in the cache, no location in the server, no protocol to handle the patched sources storage...). But I think there are other alternatives to implement a solution, for example:

- You can add an ``option`` to recipes, like ``sources: [True, False]`` (by default ``False``), and by enabling this option, the build does nothing and the package packages the sources (patched) in the final package. In this way you have a dependency graph of patched sources "binaries" for your products.
- I have been thinking about the 2.0 deployers, but it is true that they would be useful to collect the patches from the conandata.yml definitions, but not the actual patched files, for that you would need to file a ``--build=*``, and that is probably very heavy and slow, and don't want to do it. But if you are good collecting the patches, this would be a good alternative.
- There are Conan hooks, and you have a ``post_source()`` hook. This could be a good place to implement something that captures the patched sources, create a zip and put it somewhere.

Please have a look at those alternatives, and if you have any specific question about any of those, feel free to submit a new issue. I am closing this, as at the moment seems too much to implement this built-in. Thanks!
