### ISSUE TITLE
[question] How to generate CONAN_<PKG-NAME>_ROOT with CMakeToolchain

### ISSUE THREAD

**Issue by kulleradam** [conan-io/conan#11058]
I try to replace `cmake_paths` generator with `CMakeToolchain` in my project, but most of my dependencies were patched with `cmake.patch_config_paths()` so the absolute path in cmake files was replaced with `CONAN_<PKG-NAME>_ROOT`. 

Is it possible to generate `CONAN_<PKG-NAME>_ROOT` variables for the dependencies with `CMakeToolchain` or `CMakeDeps` to solve this issue?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @kulleradam 

No, ``CMakeToolchain`` doesn't have anything like that (``CMakeDeps`` is irrelevant here, because I assume you are trying to use your xxx-config.cmake files packaged inside the packages, aren't you?)

The thing is that it shouldn't be necessary anymore with the modern integrations. ``CMakeToolchain`` will add the paths to the packages directly in the CMAKE_ variables (like CMAKE_PREFIX_PATH, CMAKE_MODULE_PATH) as necessary, so the config.cmake scripts will be found with normal CMake code, nothing conan specific should be done. Maybe you want to elaborate a bit further what you are trying to do. Thanks!
