### ISSUE TITLE
[question] revisions_enabled = True + semver_direct_mode possible?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#11070]
Hi,
I have a strange question. we'd like to use package revisions in our Conan Artifactory. The background reason is that
we create several aliases whenever we release a package to Artifactory (e.g. create an alias to 'master' of the package, which points to the latest / last built version of the package, create an alias to '1.2.3' which would point to the latest v1.2.3 version of the given package).
Because of this we didn't want to "endanger" overwriting previous packages, so that a symlink would "accidentally" point to a rebuilt, changed package.
However we don't really want to use package_revision_mode, but would simply like to stick with the default semver_direct_mode.
What we see though in this case is that we can't really search for the individual packages via conan search, e.g. conan search doesn't list the package revisions (even if --revisions provided), also during "conan install" (during package build) we don't really see which exact package revision was picked up by Conan.

So the actual question: Can we use package_revisions with semver_direct_mode?
Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

I don't fully understand the issue. Once revisions are enabled, then both recipes and package binaries start to be revisioned. They will automatically get a new revision if their content changes. However not all changes are equal. The recipe revisions are expected to happen often, when source code or recipe changes happen. On the other hand, package revisions should never happen in a sane environment. Please read https://github.com/conan-io/tribe/pull/30 for further discussion, but the idea is that if you already have an existing binary, for a given configuration (that implies a given package_id), there is no need to rebuild that package binary from source, that would only be a waste of resources.

``requires`` and any reference to another dependency, like an ``alias`` can only be done to the "recipe reference", including the recipe revision, but not to a specific binary, it is not possible to depend on ``requires = "pkg/version#recipe_revision:package_id"``, because the ``package_id`` is an evaluated property that changes when the configuration changes, and as such, it cannot be defined in the recipes. In the same way, it is not possible to reference a given package revision, but as said above, it doesn't matter much, because package revision should only exist one in the general case.

Then, the ``package_id_mode`` is a different thing, how the ``package_id`` is computed, based on the dependencies versions. You can still keep using ``semver_direct_mode`` even when enabling revisions, and the dependencies get both recipe and package revisions.

**Comment by harsszegi** [comment]
Well I just wanted to have a confirmation that this setup (e.g. revisions_enabled + semver_direct_mode is compatible with each other. However in this case I have one single questions: why doesn't 'conan search --revisions --remote xxx' show the package revisions from Artifactory? Why only the recipe revision is shown?

**Comment by memsharded** [comment]
It depends what you pass as an argument. If you pass a reference that includes down to the ``package_id``, you will get listed the package revisions, instead of the recipe revisions:

```
conan search zlib/1.2.11@#6fcaa61190cb5889704d322e95698630:ff82a1e70ba8430648a79986385b20a3648f8c19 --remote=conancenter --revisions
87a77f65799576be1020c7044e2ca761 (2022-03-30 07:07:55 UTC)
```

As opposed to recipe revisions:
```
conan search zlib/1.2.11@ --revisions --remote=conancenter
Revisions for 'zlib/1.2.11' at remote 'conancenter':
6fcaa61190cb5889704d322e95698630 (2022-03-29 15:47:45 UTC)
4b38406da00104befece594b529fd155 (2022-03-17 13:48:56 UTC)
b46bf663179824c23085bb71666ba8e6 (2022-01-25 01:25:38 UTC)
683857dbd5377d65f26795d4023858f9 (2021-12-14 16:35:09 UTC)
b3eaf63da20a8606f3d84602c2cfa854 (2021-08-27 20:02:46 UTC)
08c5163c8e302d1482d8fa2be93736af (2021-05-05 16:17:39 UTC)
b291478a29f383b998e1633bee1c0536 (2021-03-25 10:03:21 UTC)
514b772abf9c36ad9be48b84cfc6fdc2 (2021-02-19 14:33:26 UTC)
25dad5342ca50f8d7b9e30f669c7ad37 (2021-02-03 14:33:18 UTC)
1a67b713610ae745694aa4df1725451d (2020-11-19 20:33:36 UTC)
1579680eade7cc27626667ca4b143529 (2020-09-04 14:01:09 UTC)
c39ae6b4e9f752e46539badf1317ec06 (2020-08-20 15:19:28 UTC)
aced1fdf3a0872e757163d023ff0c612 (2020-08-19 17:43:57 UTC)
0df31fd24179543f5720ec7beb2a88d7 (2020-07-31 10:32:52 UTC)
be59e4b426fc4b137e10bf481ef8dc17 (2020-07-02 16:41:49 UTC)
9e0c292b60ce77402bd9be60dd68266f (2020-06-09 17:04:37 UTC)
e69eb26137def0a77953bb0afe1bcb54 (2020-05-18 13:55:28 UTC)
e0df2b44162c49e6d43f59db38e18253 (2020-05-05 16:22:11 UTC)
f3b17fb16cd1b7fbc969400a2ba1bc08 (2020-04-16 10:21:19 UTC)
ddccdddea098293f5202c5e8eb29967b (2020-03-13 17:07:28 UTC)
419994c54789da229ef991be6c2563b3 (2020-01-08 09:07:41 UTC)
0c5984f24444d0e6538433d51fd6b15c (2019-12-26 12:05:42 UTC)
1cd4a227e1b846f961bf91fcb6f3980f (2019-12-19 09:00:24 UTC)
822edf85d3c647748f9e5df4153f3d44 (2019-10-24 12:02:33 UTC)
c9e88c4e6af218eddd574a31b7a200ac (2019-10-24 11:10:39 UTC)
5f4917ce0a630b102f472afd00102d40 (2019-10-13 09:46:08 UTC)
```

**Comment by harsszegi** [comment]
Oh, I thought I could query all package's all revisions via conan search. Thanks for clarifying it, closing it!

**Comment by memsharded** [comment]
> Oh, I thought I could query all package's all revisions via conan search. Thanks for clarifying it, closing it!

No, that would be quite slow for many cases, this is a relatively slow operation in the server, so better ask for the package revision of only one recipe revision by default.
