### ISSUE TITLE
[question] How can I produce packages without building phase and not cause "missing prebuilt package" error in conanfile.txt?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#11124]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I make a artifacfatory just for storing cuda, cudnn, tensorrt, etc. These pacakges don't have source code, so I just store their binaries and headers. After I upload, I use conanfile.txt to install those, it reports:
![image](https://user-images.githubusercontent.com/27768261/165723475-a6c036b8-25e1-4d5f-8802-16f32002e144.png)

But these packages don't hava source code, so don't have build stage ... How can I erase these error when downloading dependency for my own project using these packages?

**Comment by Tumb1eweed** [comment]
cublas:
from conans import ConanFile, CMake, tools


class CublasConan(ConanFile):
    name = "cublas"
    license = "NVIDIA EULA"
    url = "https://docs.nvidia.com/cuda/cublas"
    description = "CUDA Basic Linear Algebra Subroutine library"
    settings = "os", "compiler", "build_type", "arch"
    no_copy_source = True
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    def source(self):
        tools.get(
            **self.conan_data["sources"][self.version],
            destination=self.source_folder,
            strip_root=True
        )

    def requirements(self):
        self.requires("cudart/[>=11.6.55]")

    def package(self):
        self.copy("*", dst="include", src=self.source_folder + "/include")
        self.copy("*", dst="lib", src=self.source_folder + "/lib")
        self.copy("LICENSE", dst="LICENSE", src=self.source_folder)

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)

**Comment by czoido** [comment]
Hi @Tumb1eweed,

Please, have a look to the https://docs.conan.io/en/latest/reference/commands/creator/export-pkg.html command. That is used to create conan packages from prebuilt binaries. You should take care that the binaries that you package match with the settings and options you use when you do the `export-pkg` (build_type, os, architecture...)
What is happening to you is that you created the **cublas** package with a set of options and settings and the consumer you are trying to build does not match with those settings and options (for example building the consumer in _Debug_ but you don't have _Debug_ packages for **cublas**). You can [set the binary compatibility](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html) in the `package_id` method so that Conan does not try to build anything.
