### ISSUE TITLE
[question] Linux and Windows packages on same channel?

### ISSUE THREAD

**Issue by skoolkid** [conan-io/conan#11156]
I maintain an application that runs on Windows and Linux, and I use conan to package its third-party library dependencies for each OS platform. At the moment I upload the Windows conan packages to a user/windows channel, and the Linux conan packages to a user/linux channel.

I would like to upload both Windows and Linux conan packages to the same channel (for simplicity), but so far I haven't been able to make that work. If I upload a Windows package and then a Linux package (for the same library, built from the same conanfile) to the same channel, the Windows package is "lost" - `conan install` can no longer find it. Likewise, if I upload the Linux package first and then the Windows package, the Linux package is lost.

Is there a way to have Windows and Linux packages peacefully coexisting on a single channel, or is separate channels the way to go?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @skoolkid 

Yes, using different channels for different platforms is not the right approach, it is an anti-pattern.
Conan is able to model correctly the different binaries for the different platforms, the binary management is one of its capabilities.

I'd say that you are seeing one of these behaviors:

- Your ``conanfile.py`` is omitting the ``settings = "os", "compiler", "arch", "build_type"`` line, so it cannot model the different binaries that happen when you change those settings, and assumes "no settings", which means the binary is supposed to be the same. To avoid this, I always recommend to start from one of the predefined templates, like: ``conan new hello/0.1 --template=cmake_lib``, then ``conan create .``. 
- The other possibility is that you have activated revisions, and when doing the ``conan create`` you have checked-out from git something different because line endings are different. Read this FAQ for more details: https://docs.conan.io/en/latest/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine


Please let me know if this helps, and if it is one of the above cases.

**Comment by skoolkid** [comment]
Hi @memsharded 

Yes, it was indeed the second issue you described. I've fixed it by adding some `.gitattributes` files to the repository, to make sure that line endings in any text files that will end up in a conan package are forced to LF, even on Windows.

Thanks!

**Comment by vincesp** [comment]
Hint: when making changes to `.gitattributes` and building with Azure pipelines, you might want to add 
```yaml
workspace:
  clean: all
```
to your jobs. Otherwise, the build agent won't update the line endings for files that have already been cloned. `checkout` with `clean: "true"` seems not to be sufficient.
