### ISSUE TITLE
[feature] Share credentials between remotes

### ISSUE THREAD

**Issue by naggerx** [conan-io/conan#11173]
We have over 10 different conan-remotes on one artifactory instance. All the remotes are using the same user/password.
But I have to type over 10 times the very same password for every single remote.
(I dont know why, but I must about every two weeks retype my password - for every remote)

It would be nice if different remotes could share the same credentials. 

Like:
```
    conan user -r firstremote myuser -p mypass  # like today
    conan user -r secondremote --use-same-as firstremote  # new
    conan user -r thirdremote --use-same-as firstremote   # new
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @naggerx 

The thing is that Conan does not (and probably will not ever) store an Artifactory password. Internally, it uses tokens (JWT), to repeateadly auth against the different remotes. The fact that it is the same user/password doesn't imply that the tokens will be the same, and the level of permissions such tokens can have for different repos can also be varying.

So I don't think this is doable. Maybe an alternative for you would be to define ``CONAN_PASSWORD`` and ``CONAN_LOGIN_USERNAME`` environment variables, as they will be automatically used if defined instead of being requested in the command line.

Also, if you have so many remotes, a possibility to consider would be to group them into a virtual repository in Artifactory, so clients see only 1 remote that aggregates the others.

**Comment by memsharded** [comment]
Conan 2 now has:

- ``credentials.json`` files that can store credentials: https://docs.conan.io/2/reference/config_files/credentials.html#credentials-json. These files support jinja2 evaluation and rendering, so they can be dynamic too
- New authorization plugins that allow to define any logic on the user side: https://docs.conan.io/2/reference/extensions/authorization_plugins.html. These plugins can also be installed with ``conan config install/install-pkg``, this is a powerful feature.
- Also the server Artifactory I think it has more configuration over the time to expire tokens, so it can be increased.

So closing this proposal as implemented in Conan 2, please create new tickets for any further question. Thanks for the feedback!
