### ISSUE TITLE
Add option to use binaries provided by the system package-manager

### ISSUE THREAD

**Issue by denesb** [conan-io/conan#1117]
I would like an option to use the system-provided binaries for certain dependencies, instead of the binaries provided by the conan package-repository.

_Why_?
My project depends on Qt. Now Ubuntu for example ships a heavily patched version of Qt (e.g. global menus) and I'd like to test my application against all those patches. I'd also like my application to be easily packaged for Ubuntu (and other distros), and this means linking against system binaries.
On other platforms that are not as well managed (think Windows) using the conan-provided binaries is perfectly suitable.

Is there such an option already out there? I couldn't find anything related to this in the documentation, and google were of no help either.

**Comment by memsharded** [comment]
Hi @denesb 

First some clarification: there is no "conan package-repository". Conan.io is a public service that hosts conan packages for free, without moderation or review. Anyone can upload their own packages there, so it is not to be considered the "single and only source of truth for packages". Actually most conan heavy users are just using their own conan_server and not relying on conan.io packages.

Maybe ``system_requirements()`` is what you are looking for, have a look at http://docs.conan.io/en/latest/reference/conanfile.html#system-requirements

and ``SystemPackageTool``: http://docs.conan.io/en/latest/reference/tools.html#osinfo-and-systempackagetool

The idea is to simply create a package recipe that wraps the installation of the package with the system tool, but it can also define useful information for consumers in its ``package_info()`` method, and use that recipe instead of the one providing their own binaries.

Also, package recipes are very powerful, you can do many things. If you don't want to call the installation of the system package, because you assume it is already there for some reason, you can just package for the package name and ``package_info()`` method. 

Please tell me if this makes sense or if you have any further question.

**Comment by denesb** [comment]
Thanks @memsharded, this is what I was looking for. I don't know how I missed this, I seem to remember skimming through that chapter in the docs too. :grin:

**Comment by memsharded** [comment]
No worries. Big changes are undergoing to the docs, maybe we moved something. Don't hesitate to ask any further question :)
