### ISSUE TITLE
[question] ConanCenter hooks summary

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11221]
For 2.0 we plan to review the Hooks api, it would be great to know better:

- Which hooks are used in ConanCenter (pre-build, post_package,..?) with a brief description of the usage/purpose
- For the used ones, which parameters passed in the hook call are unused (if some are unused)

**Comment by uilianries** [comment]
> Which hooks are used in ConanCenter (pre-build, post_package,..?) with a brief description of the usage/purpose

The only hook used on Conan Center Index is [conan-center.py](https://github.com/conan-io/hooks/blob/master/hooks/conan-center.py), which does not require any external python package.

So far, we have been using:

- pre_export
  - Most of hooks are here. It can be a linter related to cci rules, or missing files, etc ...	
- post_export
  - processed options and license. Some recipes may the license name according to the version  
- pre_source
  - Validates recipe content. It could be moved to pre_export ...
- post_source
  - Validate all files extensions, if they are c/c++. Some of them are generated by cmake, that's why we need to wait here
- pre_build
  - Validate fPIC usage. As it can be removed, depending the recipe or configuration. 
- post_package
  - Most related to packaged files: license, pdb, cmake, pkgconfig. When shared, dll and .so must be packaged
- post_package_info
  - Validate components listed in cpp_info, but not installed in libdir;  

> For the used ones, which parameters passed in the hook call are unused (if some are unused)

All. output, conanfile, conanfile_path and reference. 
- Output we use for logs
- conanfile we load and access attributes and methods
- conanfile_path gives us the build folder path, etc
- reference gives us name and version

As it requires some time to read conan-center hook, we have a list of possible errors filter by that hook. Most of hooks are listed there: https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md

**Comment by datalogics-kam** [comment]
Excuse me for being an interloper here... We're using pre_build and post_build, which is also mentioned in the [documentation](https://docs.conan.io/en/latest/howtos/sanitizers.html), and referenced in #11094.

I think hooks are useful for end users of Conan to implement site-wide policies and customizations, more or less how you'd be using them in conan-center. Having a good hook system relieves the Conan project of having to implement and maintain a lot of finely-detailed features to meet end-user concerns.

**Comment by memsharded** [comment]
> I think hooks are useful for end users of Conan to implement site-wide policies and customizations, more or less how you'd be using them in conan-center. Having a good hook system relieves the Conan project of having to implement and maintain a lot of finely-detailed features to meet end-user concerns.

Sure, we are not planning to remove the hooks functionality, or even modifying all of the existing hooks. Some hooks might remain intact. But not all hooks are equal, and there are some hooks APIs that are a bit unclear. In Conan 2.0 we have a new extension point that is called "plugins", which could be a better place for some of these. This is why we are trying to understand first which ones are used most typically and how.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/11368
