### ISSUE TITLE
[question] cleanup huge CONAN_USER_HOME (dl directories?)

### ISSUE THREAD

**Issue by thorsten-klein** [conan-io/conan#11236]
Hello,
when I analyze my `CONAN_USER_HOME` directory, then I can find a lot of files which could actually be removed.

For some of my packages (which are both build from source or for some packages downloaded prebuilt), I can find following files:
- `<conan_download_cache>/<hash>.tar.gz`
- `dl/export/conan_export.tgz`
- `dl/export/conan_sources.tgz`
- `dl/pkg/<hash>/conan_package.tar.gz`
- `export_source/` (which is actually the unpacked `conan_sources.tgz`)
- `source/` (which is actually same as `export_source/`)
- (`build/` (which is actually the same as `source/` if not using `no_copy_source=True`))
- `package/<hash>/` (which is actually the unpacked `conan_package.tgz`

**Background:**
We always have to use `exports_source` to upload everything what we need alongside with the `conanfile.py` to the same remote artifactory. We need this to ensure that our packages always can be built from source in future (e.g. if a remote is mirrored, if the actual URL is not available anymore on github.com, ...). Therefore our `conan_sources.tgz` may be very large. For Example: `clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz` = 520MB (unpacked: 3.5GB)

**Note** regarding the download_cache `<conan_download_cache>/<hash>.tar.gz` (1.5GB): This file we do not need to consider for now, since it is of course our job to cleanup the download_cache from time to time...

In my `CONAN_USER_HOME` this conan package requires more space than expected (I would expect 3.5GB all in all).
- `dl/export/conan_export.tgz` 1kB
- `dl/pkg/<hash>/conan_package.tar.gz` 1.5GB
- `export_source/` 1.5GB
- `source/` 1.5GB (Note: This file we can remove in our `source()` after we have unpacked it)
- `build/` 0kB (we use `no_copy_source=True`)
- `package/<hash>/` 3.5GB

Is it a bug, that the `dl/*` files are not automatically removed after they have been unpacked?

What is the easiest way for now to cleanup all files in the conan cache  which are actually not required anymore (especially the `export_source`, `source`, `build` and `dl` directories)? 

Will following command make the conan cache corrupt?
```
cd ~/.conan/data
find . -mindepth 5 -maxdepth 5 -type d -name 'dl' -o -name 'build' -o -name 'source' -o -name 'export_source' -exec rm -rf {} +
```

**Comment by thorsten-klein** [comment]
Hello @jcar87 , 
do you have any hints for me 👍🏻  ?

**Comment by jcar87** [comment]
Hi @thorsten-klein  - thanks for raising this question.

If I understand correctly, once you download a package from the remote or building from source, you no longer need the sources or the cached downloaded folder or the build folders.

In the case of the sources and builds, you could use the `conan remove` (docs [here](https://docs.conan.io/en/1.48/reference/commands/misc/remove.html)) to remove the sources, for example:
```
conan remove --src --builds '*'
```

This should prompt you to remove the sources for each package and ask for confirmation.

I believe with these two flags most things you have listed would be removed, except for the contents of the `dl` folder. This is indeed a feature - there are some workflows that may require re-using those files (e.g. for re-uploading to a different remote), and in it can be beneficial to just cache these instead of waiting time re-compressing the potentially large folders. It should otherwise be safe to remove the `dl` folder (perhaps with the `find` command as you describe) if you no longer use it - the only penalty would be the time needed to re-generate it if needed.

**Comment by thorsten-klein** [comment]
Hello @jcar87 ,

Actually I do not want to run this `conan remove` by myself. I would expect, that conan is cleaning up these files correctly by default (e.g. after they were copied / unpacked). 

Wouldn't it make sense to cache these `dl` files in any other folder , e.g. inside the `download_cache` ?

**Comment by memsharded** [comment]
Quick note: Not removing the .tgz files after download is a feature. Initially they were removed, but that meant that install/download + upload operations were too slow, because they need to re-zip, which is a big bottleneck. So users requested that these files were not removed, and now those flows are definitely much faster, (and users that want to remove those files and free space, they can remove them)

**Comment by jcar87** [comment]
Hi @thorsten-klein thanks for the quick reply!!

I believe running conan remove in a way that it preserves the packages would address your initial concern of ensuring that the the cache is not corrupted, by avoiding accidental manual file system operations. 

As for Conan automatically deleting certain files, it is difficult Conan to predict which files may be needed to satisfy future operations, and thus, a conservative approach is taken as file deletion is a destructive operation and in those cases where the files can be regenerated the time spent doing this could be significant.

**Comment by IceflowRE** [comment]
Is there a way to remove all cached packages except the ones required by a recipe/conanfile.py?

**Comment by memsharded** [comment]
> Is there a way to remove all cached packages except the ones required by a recipe/conanfile.py?

Not yet. 

At some point in Conan 2.X, when the LRU cache metadata is managed, it will be possible to ``conan install`` one conanfile, and then removed everything that was not used in the last 5 minutes or something like that.
