### ISSUE TITLE
[feature] allow dyanamic user/channel in `python_requires`

### ISSUE THREAD

**Issue by mattyclarkson** [conan-io/conan#11311]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

When using [`python_requires`](https://docs.conan.io/en/latest/extending/python_requires.html#python-requires) it would be useful to propagate the current user/channel into the reference.

The naive way to do it would be to do:

```py
from conans import ConanFile

class Pkg(ConanFile):
    @property
    def python_requires(self) -> None:
        return f"pyreq/0.1@{self.user}/{self.channel}"
```

This isn't possible because the `python_requires` is accessed as a attribute on the class.

Another option would be do allow `{user}`/`{channel}` replacements:

```py
from conans import ConanFile

class Pkg(ConanFile):
    python_requires = "pyreq/0.1@{user}/{channel}"
```

**Comment by memsharded** [comment]
Hi @mattyclarkson 

We are aware of this, but this is a difficult to solve chicken and egg problem
The problem is that ``python_requires`` is evaluated the very first thing when a recipe is loaded by Python interpreter, in case it is necessary to extend from a base class in that ``python_requires``. Then everything else happens, from loading the ``conandata.yml``, calling ``set_name()`` and ``set_version()`` methods, that could also be used to define the current user and channel. So, it is impossible to use in the general way the current user and channel (or name or version, or anything else really) in the resolution of ``python_requires``.

In any case, the recommendation moving to Conan 2.0 is let the user and channel be constant. Always, no variability of them over ``require`` either. The different "stages" of testing, alpha, stable, etc, are achieved using different remote repositories, and doing promotions (copies) of packages between repositories, not by changing user/channel.

**Comment by mattyclarkson** [comment]
> In any case, the recommendation moving to Conan 2.0 is let the user and channel be constant. Always, no variability of them over `require` either. The different "stages" of testing, alpha, stable, etc, are achieved using different remote repositories, and doing promotions (copies) of packages between repositories, not by changing user/channel.

Interesting to know, we can probably repivot to not need different channels but they are useful for staging packages right now in the same package repository.

**Comment by memsharded** [comment]
> Interesting to know, we can probably repivot to not need different channels but they are useful for staging packages right now in the same package repository.

Good, let me know if you have any further question around this. The thing is that there are multiple benefits of splitting stages into multiple repositories, from easier maintenance (can more confidently remove old packages from a "staging" repo), security (to give less permissions to production repos), etc.
