### ISSUE TITLE
[bug] `conan lock create` always uses LF instead of the system endline convention

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#11323]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: n/a
  * Conan version: 1.4
  * Python version: 3.10.1

### Steps to reproduce (Include if Applicable)
`conan lock create myconanfile.py --lockfile-out mylock.lock --base`

mylock.lock has LF endlines instead of CRLF (on windows). 

This is an issue when you commit your base lock files and have autocrlf enabled in git. When you regenerate your base lock files, you get git diffs due to this bug.

**Comment by SSE4** [comment]
I assume lockfiles created on different systems should be absolutely identical (bitwise), given the same input - same profile(s).

**Comment by rconde01** [comment]
As you don’t have “lock file revisions”, I’m not sure why this would be an expectation or desire particularly.

**Comment by memsharded** [comment]
Exactly the same argument could be said by someone that doesn't have ``autocrlf`` and will complain that Conan is generating a file with different line feeds, and it is causing constant diffs.

So this is by design. All files generated by Conan are generated always with LF, not CRLF. 
It is also important to know that in general using different line feeds in different platforms is bad because it creates different recipe revisions, so it is recommended to use always LFs: https://docs.conan.io/en/latest/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine

**Comment by rconde01** [comment]
I think you could argue autocrlf is typical? I'm actually not sure. But in any case it's not a big deal for us to handle I was just surprised. Maybe something to document.
