### ISSUE TITLE
conan generated FindXXX does not export pack_component_LIBRARIES

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#11329]
I feel there is a bug in Conan's cmake finder generator (FindHDF5.cmake)

netcdf key part:
https://github.com/Unidata/netcdf-c/blob/be0cbfdbbeca8ed7d6b44d4cf45fa928a02e3a4e/liblib/CMakeLists.txt#L119

netcdf is trying to use `${HDF5_HL_LIBRARIES},  ${HDF5_C_LIBRARIES}`,
but HDF5's conan recipe doesn't export any of those.
instead it exports:
- HDF5_LIBS
- HDF5_C_LIBS
- HDF5_LIBRARIES
- but *not* HDF5_C_LIBRARIES

Why doesn't it export package_component_LIBRARIES ?
It seems like existing software expects this from the standard cmake finders.
https://cmake.org/cmake/help/latest/module/FindHDF5.html
```
HDF5_C_LIBRARIES
    Required libraries for the HDF5 C bindings
```

_Originally posted by @paulharris in https://github.com/conan-io/conan-center-index/issues/10851#issuecomment-1137205735_

**Comment by memsharded** [comment]
This issue is related to ``cmake_find_package`` which will no longer be modified, unless there are very serious regressions.

If anything, this should be reported against ``CMakeDeps`` generator.

**Comment by paulharris** [comment]
I had a go at upgrading netcdf to CMakeDeps, and yes the same problem occurs (ie no HDF5_component_LIBRARIES defined)

And, there is even less exported, I don't see a HDF5_C_INCLUDE_DIR or HDF5_C_LIBS anymore.  I think.

---

What is the conan policy, going forward?   Try and allow old CMake files to continue to work (ie define a broad and unending set of variations of variables to match cmake/kitware's FindHDF5 and other)?

Or, patch everything to use the new targets?  (or at least, a variable that has been exported by conan)

The problem with netcdf, is every time there is a new version to package, the patches will have to be adjusted and re-done by hand.

Are we actively pushing patches upstream?

**Comment by paulharris** [comment]
I'm going to close this, and assume we have to patch libraries and push upstream where possible.

**Comment by jcar87** [comment]
Hi @paulharris  - thanks for looking into this issue.

The primary goal, as reflected in the CMakeDeps default behaviour, is to generate _config_ files with imported targets that have the correct transitive usage requirements. Conan can still generate find modules if required, which will also define modern cmake targets, from the cmake [documentation](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules):

> The more modern approach is to behave as much like [config file packages](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#config-file-packages) files as possible, by providing [imported target](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#imported-targets).

One of the issues with the _legacy_ behaviour of defining variables, is standarizing what those variables should be called. CMake _does_ define a convention [here](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#standard-variable-names).
If HDF5 were to follow the convention described by cmake, we would have:
* `HDF5_LIBRARIES` - this can be passed to the linker, but should not be used as the result of a find_library and not be cached.
* `HDF5_LIBRARY` (where we have a single main library)
* `HDF5_C_LIBRARY` where we have components 

Interestingly, I cannot see in CMake's documentation a convention where `HDF5_C_LIBRARIES` would have to be defined as a variable, although I can infer that might be in the intention. One thing I can see, however, is that perhaps Conan could use the `_LIBRARIES` suffix rather than `_LIBS` to be better aligned with CMake's convention.

In netcdf, you can see that they have to reflect an evolving convention, especially for the windows case:
https://github.com/Unidata/netcdf-c/blob/be0cbfdbbeca8ed7d6b44d4cf45fa928a02e3a4e/liblib/CMakeLists.txt#L107-L113 

Using variables instead of imported targets also means that the consumer may need to carefully specify the transitive dependencies (which might be private!) - especially to cover the case where static libraries are being linked:
https://github.com/Unidata/netcdf-c/blob/be0cbfdbbeca8ed7d6b44d4cf45fa928a02e3a4e/liblib/CMakeLists.txt#L119

So we would be inclined to give preference to imported targets and align ourselves with the now preferred cmake modern practices. From what I can see, CMake's built-in FindHDF5 module was updated to add imported targets around version 3.19, and HDF5 itself generates config files these days - although once again and unfortunately the target names do not match 1:1.  This is unfortunate as it the discrepancy hinders modernisation efforts - ideally a `find_package(HDF5)` can be satisfied by _either_ a modern find module, or a config provided by the library, without any changes in the calling code. Otherwise we'll find ourselves trying to cover diverging conventions that will inevitable lead to conflicts when our goal is to have a self-consistent repository of packages like conan center. My first suggestion would be to try to contribute upstream to hdf5 such that the targets defined by the generated configs match those defined by the modernised FindHDF5 provided by CMake.

**Comment by jcar87** [comment]
> Or, patch everything to use the new targets? (or at least, a variable that has been exported by conan)
> The problem with netcdf, is every time there is a new version to package, the patches will have to be adjusted and re-done by hand.

If this is the case, I'd say it may be preferable to patch this via the recipe (e.g. `tools.replace_in_file()`) rather than having to generate a new patch file per version update. I think it would be safe to assume that this logic is in a single place and that it tends to remain the same across versions.

**Comment by paulharris** [comment]
I had forgotten about tools.replace_in_file(), that should work with HDF5_C_LIBRARIES --> HDF5_LIBRARIES

Thanks for the long detailed explanation,
you should add a link to that on some page of "notes about things" as I'm sure it is going to come up again!

So, does "modern" cmake drop the whole idea of defining variables like CURL_STATIC or whatever other cmake-level variables?   Sounds like all the variables are tied to the imported target instead?  Namespaced?
