### ISSUE TITLE
[develop2][feature] Remove subprocess.list2cmdline usage

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11358]
Apparently this is not documented, most likely we shouldn't use it

**Comment by lasote** [comment]
I investigated a bit:

In Conan it is used in:

1. `args_to_string` function to escape some arguments only in Windows. This usage is double creepy because it is not even processing the whole command line string but isolated lists of arguments. But eventually is the same and it is very likely needed for Windows.
3. Prepare the commands before calling `Popen`. This is funny because internally, the windows implementation of Popen is using `list2cmdline` but only if you pass a list of arguments to `Popen` instead of the string with the command, but I didn't manage to keep a list of commands to the calls to Popen, for example, the calls where we append the "> output_file" are not working (should be a way), and looks challenging to make it all work and not enough to get rid of the `list2cmdline` so I stopped.

I searched if there is an alternative documented in Python, and the answer is, that there is not. There is a `shlex` module to do the same for Unix shells but it warns about the Windows argument parsing.

We are mostly using it both for Windows and Unix shells, looks like it is not affecting apparently the Unix shells, but it is a bit creepy too.

My opinion is, I'm sure some builds (conan center for example) will fail if we just remove this, because of the escaping of quotes, paths, and all that mess in windows cmd. I would propose to just copy and paste the Python `list2cmdline` function (not dependencies, purely algorithmic and not so complex) to our code base to avoid depending on an undocumented function from Python. And maybe only for not windows, using the shlex alternative (that is new in 3.8 but only this implementation using quote that is > 3.3):

```
def join(split_command):
    """Return a shell-escaped string from *split_command*."""
    return ' '.join(quote(arg) for arg in split_command)
```

WDYT?

**Comment by memsharded** [comment]
The thing is that I see that most of the time, those functions don't even receive a list, but already a string, so they have already collapsed most of the information, and it is likely that some paths and stuff already comes quoted? Splitting that list based on spaces and then quoting might not be the best "escaping" of those strings, like if you get some ``command -a value --other=othervalue``, it might quote ``"command" "-a" "value"...`` which might be weird?

**Comment by lasote** [comment]
well, it is indeed not the main purpose of that function because, if you have already joined the arguments, you already lost information. 

>  and it is likely that some paths and stuff already comes quoted?

Yes, but also there might be arguments quoted that need to keep the quotes (double quote in the command line) and this is why we will break many things if we just remove it.

> like if you get some command -a value --other=othervalue, it might quote "command" "-a" "value"... which might be weird?

No, it doesn't work like that. If you split by spaces "command -a value --other=othervalue" and pass it to list2cmdline it will return exactly the same command because there is nothing to escape.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/11553
