### ISSUE TITLE
[bug] AutoToolsDeps sets includes to CPPFLAGS, but MesonToolchain reads only CFLAGS/CXXFLAGS?

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#11397]
related to #10683, coming from https://github.com/conan-io/conan-center-index/pull/11053

in an attempt to migrate `Glib` to `MesonToolchain` I had to put the following workaround:
```
        cppflags = tc.vars().get("CPPFLAGS")
        tc.environment.append('CFLAGS', cppflags)
        tc.environment.append('CXXFLAGS', cppflags)
```
to propagate `CPPFLAGS` into `CFLAGS`/`CXXFLAGS`.
`AutoToolsDeps` sets includedirs to `CPPFLAGS` only: 
https://github.com/conan-io/conan/blob/1.48.2/conan/tools/gnu/autotoolsdeps.py#L46
https://github.com/conan-io/conan/blob/1.48.2/conan/tools/gnu/autotoolsdeps.py#L74
while `MesonToolchain` currently only reads from `CFLAGS`/`CXXFLAGS`:
https://github.com/conan-io/conan/blob/1.48.2/conan/tools/meson/toolchain.py#L154-L157

so they kinda cannot connect to each other as is, which is disappointing. I don't know where shoud be the right fix, in `MesonToolchain` or `AutoToolsDeps`.

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version:
  * Python version:

**Comment by jcar87** [comment]
According to: https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html#Implicit-Variables


* `CXXFLAGS` are for the C++ compiler
* `CFLAGS` for the C compiler
* `CPPFLAGS` are for the C and Fortran preprocessor - that said, this is a bit confusing - because most flags that control the preprocessor https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html - can be passed directly to the compiler as far as I'm aware

Meson only listens to `CXXFLAGS` (similar to cmake) - but they recommend not using these: https://mesonbuild.com/Reference-tables.html#compiler-and-linker-flag-environment-variables
