### ISSUE TITLE
Cross build: Profiles with build_requires

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#1141]
- Profiles accepting [build_requires]
- Conan will install first the build requires (using also the settings, env etc declared in the profile), then the real dependency tree.
- A build require can be also pacakge level: zlib:cmake/2.8@lasote/testing
- Both cpp_info and env_info should be inherited to real dependency tree
- We have to define somehow the build_policy for build requires.
- That way each build require could declare their own env info or cpp flags like:
    - env_info.PATH
    - env_info.CXX, env_info.CC
    - cpp_info.cflags = "--sysroot XXX"
etc

- That way we could avoid managing virtual environment for cross building, custom compilers like mingw etc
- Users can make packages for custom toolchains/compilers based on settings.

**Comment by tamboril** [comment]
I think this is a good idea, as most consumers do not want to build, even if it were possible.  They usually will accidentally trigger a build due to having incorrect settings or options (such as `build_type`).

I wonder whether a "synthetic", or "ephemeral" requirement would be useful.  Let's say you don't want to package up `gcc` and `cmake` and such just to bring together a build environment, but rather, you could just verify that they're there, like some variation of:

        self.add_ephemeral_package('cmake/2.8@jharris/testing', my_cmake_detect())

...then reference that ephemeral package in the build_requires.

Just a thought.  In any case, I like the distinction between the build context and the simpler, more common consumption context.

**Comment by memsharded** [comment]
Yes, that is a good idea, we have considered it while current development of the feature. 
The disadvantage is that explicit dependency to build tools in code packages couples things in an inconvenient way. With the current ``build_requires`` that @lasote is proposing in profiles, you can cross-build for Androd libraries like Zlib, that doesn't have any idea about the android toolchain or requirements. Otherwise, you should add the package dependency to every single recipe that was to be cross-compiled to Android. And repeat the process for other toolchains too.

**Comment by lasote** [comment]
The **build_requires** feature has been released in conan 0.22.0. Any feedback is very welcome!
