### ISSUE TITLE
[question] cross compiling from x86_64 to x86_64

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#11437]
Hi,

I bumped into a strange issue. I have a strange Yocto SDK based x86_64 Linux 64 bit compiler, which poduces executables that can't be executed under Ubuntu 21.10 for example. Haven't checked, might be glibc issue. So this calls for cross-compilation.
I have created a profile which sets os_build, arch_build, os, arch, BUT they are obviously the same, e.g. (Linux,86_64) vs (Linux,x86_64).

And obviously autoconf fails big time detecting that this is a cross compilation environment indeed (hence no --host, --target is provided).
Any idea how could I overcome this?
Thanks,

**Comment by jcar87** [comment]
Hi @harsszegi, thanks for using Conan for your cross-building needs!

If you are targeting Yocto Linux x86_64 from Ubuntu Linux x86_64, I would be inclined to say this may not be strictly cross-building (as you are pointing out the build OS/arch are the same as the host ones). You may be dealing with the case of creating binaries that are compatible across Linux distros of the same architecture, in the same way that binaries built for Ubuntu 21.10 are unlikely to be compatible with Debian 10 buster.

The Yocto wiki mentions this case: https://wiki.yoctoproject.org/wiki/TipsAndTricks/Running_YP_binaries_on_Ubuntu_and_Vice_Versa - and the ability to run YP-generated binaries on Ubuntu depends on: 
* the executables pointing to the right dynamic linker (which can be overridden via `patchelf`)
* the dependencies dependencies existing on the system that is doing the loading (`LD_LIBRARY_PATH` may help at runtime)
* (and implicitly, the version of glibc that a binary was built against, vs the one available at runtime)
 
So there's a chance that the same binaries will not run without modification. This is not _always_ the case across Linux distros and it is sometimes possible to create binaries that are compatible with many distros.

If what you intend is to generate _two_ sets of binaries with conan, one set targetting Yocto/x86_64, and another one targetting Ubuntu x86_64, perhaps a possible approach is to tweak your `settings.yml` to account for different target distros or systems. For example: https://docs.conan.io/en/latest/integrations/cross_platform/yocto.html?highlight=linux%20version#architecture-conversion-table 

```
os:
    Linux:
        machine: [None, "qemux86_64"]
```

or a similar construct, and then your conan profile to create yocto binaries can define the `os.machine` setting, and your profile to target ubuntu-comaptible binaries can leave it empty so that it maps to `None` (so that you retain compatibility with other Linux/x86_64 binaries, for example those from conan center).

The goal here would be to ensure we get a different package ID for each set of binaries (yocto or ubuntu), and each profile sets the required environment variables to ensure the binaries are built with the correct SDK or compiler. 

Let me know if this works!

**Comment by harsszegi** [comment]
Hi @jcar87,
thanks for the suggestion, will try it out, but please note that the issue is not really related to package ids.
I am providing build and host profiles to conan install, however "get_gnu_triplet" treats this environment as
NOT a cross-build environment (as get_gnu_triplet purely checks os, arch, os_build and arch_build, disregards
the fact that I provide two different profiles for build and host.
Anyhow i'll try your suggestion and will keep you posted.
Thanks,

**Comment by harsszegi** [comment]
Hi,
it doesn't work, tested with xz_utils, gnu triplet is not passed at all

**Comment by harsszegi** [comment]
Btw, if I change "os" to FreeBSD for example in any of the profiles, then GNU triplets are passed properly, however this is wrong for multiple reasons (like Boost is tried to be compiled like it was on FreeBSD really, which fails big time)

How hard would it be to add CONAN_AUTOTOOLS_BUILD, CONAN_AUTOTOOLS_HOST, CONAN_AUTOTOOLS_TARGET environment variables handling to autotools_environment.py? This way I could force this in the profile, so Conan wouldn't have to "figure it out" by itself.

Tagging @memsharded maybe he has some other ideas here?
Thanks,

**Comment by jcar87** [comment]
Hi @harsszegi  - thank you for investigating this further.

I would need a bit more information to try to replicate this on our end. Could you confirm the following:

>  I have a strange Yocto SDK based x86_64 Linux 64 bit compiler, which poduces executables that can't be executed under Ubuntu 21.10 for example. Haven't checked, might be glibc issue. 
1) At what stage do the executables fail running? By this I mean, are we dealing with executables that are built _during_ the build of a package, but are also run during the same build - or the package contains an executable and you're trying to run that executable explicitly afterwards?  Or are packages that use Autootools not building with an error similar to "cannot run executables"?

2) What are the GNU triplets that you expect Conan to pass in this instance? Any chance you can run `gcc -dumpmachine` from both toolchains and provide the returned values?

3) Could you provide the two different conan profiles that you are passing as `--profile:build` and `--profile:host`? 

3) Conan will assume it is cross-compiling when between the two profiles, there are differences in `os` or `arch` - and it will use these values to construct the GNU triplet passed to Autotools, irrespective of whether these come from two different profiles. 
However, the `configure()` method of the Autotools build helper allows you to override the arguments passed to the configure script, including the build and host triplets. So if there is enough information in your profile settings to determine the different triplets, you could try to override them in the `build()` method.

> Btw, if I change "os" to FreeBSD for example in any of the profiles, then GNU triplets are passed properly, 

I would imagine that this causes the effect of the Conan Autotools build helper to pass _two_ different values to `--build` and `--host` (since conan assumes cross building) - irrespective of whether one of the triplets is not accurate (since we're not dealing with FreeBSD).

**Comment by harsszegi** [comment]
Thank you @jcar87 for looking into this.
Re 1: This is the configure stage of xz_utils, when conigure does "checking whether we are cross compiling", so it produces a "conftest" executable, then it tries to run it:
source_subfolder/configure: line 5467: ./conftest: No such file or directory
Please note that I'm still trying to cross-compile, e.g. haven't yet done the QEMU "hack" you mentioned. Also note that
no --host or --build is passed to "configure" (fo the aformentioned reasons)

Re 2: The build compiler is clang13 on Ubuntu 21.10, nothing fancy clang -dumpmachine -> x86_64-pc-linux-gnu
The host compiler is a closed source Yocto build: opt/oxidia/3.1.0/sysroots/x86_64-tdjsdk-linux/usr/bin/x86_64-tdj-linux/x86_64-tdj-linux-gcc -dumpmachine -> x86_64-tdj-linux, so actually the "build" parameter afaik should be "x86_64-tdjsdk-linux" (this is actually the variant that can be executed on Ubuntu, and the "host" should be "x86_64-tdj-linux" (as that is what sysroot provides)

Re 3: host profile:
[settings]
os=Linux
arch=x86_64
compiler=clang
compiler.version=13
compiler.libcxx=libstdc++11
[env]
CC=clang
CXX=clang++

build profile:
toolchain_name=x86_64-tdj-linux
toolchain_sdk_name=x86_64-tdjsdk-linux/usr/bin/$toolchain_name
toolchain_root=/opt/oxidia/3.1.0/sysroots/$toolchain_name

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9.3
compiler.libcxx=libstdc++11

[env]
CONAN_CMAKE_SYSTEM_NAME=Linux
CONAN_CMAKE_FIND_ROOT_PATH=$toolchain_sdk_name
CONAN_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH
CONAN_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH
CONAN_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=ONLY
CONAN_CMAKE_SYSROOT=$toolchain_root
PATH=[$toolchain_root/$toolchain_sdk_name]
CC=$toolchain_name-gcc
CXX=$toolchain_name-g++
LD=$toolchain_name-ld
CCFLAGS=--sysroot=$toolchain_root -O2 -pipe -m64 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security
CXXFLAGS=--sysroot=$toolchain_root -O2 -pipe -m64 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security
CPPFLAGS=--sysroot=$toolchain_root -O2 -pipe -m64 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security
LDFLAGS=--sysroot=$toolchain_root -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now

Re 4. Sadly I need to use https://github.com/conan-io/cmake-conan, also I only consume "xz-tuils" as transitive dependency (e.g. conan install) so I don't really think I have much control over it -> e.g. the "main" package only uses the lzma stuf in xz_utils

Thank you very much!

**Comment by harsszegi** [comment]
This ld-linux-x86_64.so.2 + LD_LIBRARY_PATH hack kinda freaks me out, as I have zero idea when to set the LD_LIBRARY_PATH so that autotools stuff would finish, as I can't do it from the start, as practically nothing would work (not even a "cd build" command anymoe)

**Comment by jcar87** [comment]
Hi @harsszegi  - Thanks for the detailed answer. I think I have a much clearer picture of what is going on now.

The key information has to do with how Autootools will try to build an executable and try to run it immediately after, where you might see an error like this:
```
 error: cannot run C compiled programs.
```
when the active toolchain is not generating executables that can be run (regardless of the reason). In your case, you get `source_subfolder/configure: line 5467: ./conftest: No such file or directory` - which is a bit misleading, but it is the error you are going to get when the generated executable points to a dynamic linker that is not present in the current system, which is what [this wiki page](https://wiki.yoctoproject.org/wiki/TipsAndTricks/Running_YP_binaries_on_Ubuntu_and_Vice_Versa) aludes to. Please disregard the advice regarding hacking the entry of the dynamic linker in order to run the executables - while that is the underlying reason why the binaries don't run, it would be rather difficult to 

Interestingly, when autootols knows or thinks that it is cross-compiling, it will typically skip the step of trying to run the conftest executable. Chances are it doesn't need to run any executable built with the local toolchain at all. In this case, passing different values to `--host` and `--build` to autotools is sufficient, and in most scenarios the specific values passed are not particularly relevant as long as they are different.

I think the ideal strategy would involve: expressing the Linux-variant in `settings.yaml` as a sub-option to the `os` setting _and_ using that information to cause the Conan Autotools integrations to detect that, and pass different values to `--host` and `--build`.

Your suggestion about being able to define the triples in the profiles is also a step in the right direction - we are already experimenting with a feature like this that would enable you to specify custom settings in profiles that affect the integrations, for example:
https://docs.conan.io/en/latest/reference/profiles.html#tools-configurations

You are unlikely to experience similar issues with projects built with CMake (unless the projects explicitly invokes executables built from source as part of the build). 

We'll look into this issue to see if there's something we can do to improve this use case.


In terms of a more immediate workaround, I think your intuition is correct in terms of modifying the profile to use a different `os` - as that will cause Conan to pass different `--build` and `--host` values, but as you mention, building other recipes that evaluate the value of the `os` setting may be an issue (as you have experienced with Boost).

My only other advice in terms of an intermediate solution until we have a proper one in place, would be to add a new sub-setting (see docs [here](https://docs.conan.io/en/latest/extending/custom_settings.html#adding-new-sub-settings)), reflect it in the relevant profile, and modify the recipes that use the Autootols build helper (docs [here](https://docs.conan.io/en/latest/reference/build_helpers/autotools.html#configure))

In settings.yml:
```
os:
    Linux:
        distro: [None, "tdj-linux"]
```

In your _host_ profile (the one for the target platform):
```
os=Linux
os.distro=linux-tdj
```

in the `build()` method of a recipe that uses the Autootols build helper:
```
# setting this to None will cause conan
# to automatically deduce them in most scenarios
build=None
host=None
if self.settings.get_safe("os.distro") == "tdj-linux": 
   build="x86_64-tdjsdk-linux"
   host="x86_64-tdj-linux"

env_build = AutoToolsBuildEnvironment(self))
env_build.configure(build=build, host=host)
env_build.make()
```

**Comment by harsszegi** [comment]
Thanks @jcar87  for the suggestion, I actually went for the “easier” solution, added CONAN_AUTOTOOLS_BUILD and _HOST to the profile and patched xz_utils to read it up and pass the —host amd —build flags directly to autoconfigure. It appears to solve the issue for now :)
Thanks
