### ISSUE TITLE
[bug] conan 1.48 broken for gcc 12

### ISSUE THREAD

**Issue by tcanabrava** [conan-io/conan#11459]
Making sure I have no profile and used the automatically generated one:

```         
➜  testconan rm ~/.conan/profiles/default
```

now I try to run `conan install .` on a dummy project:

```
  testconan conan install . --build=missing
Auto detecting your dev setup to initialize the default profile (/home/tcanabrava/.conan/profiles/default)
Found gcc 12.1
Found clang 13.0
gcc>=5, using the major as version
Default settings
        os=Linux
        os_build=Linux
        arch=x86_64
        arch_build=x86_64
        compiler=gcc
        compiler.version=12
        compiler.libcxx=libstdc++
        build_type=Release
*** You can change them in /home/tcanabrava/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


ERROR: Invalid setting '12' is not a valid 'settings.compiler.version' value.
Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '6.5', '7', '7.1', '7.2', '7.3', '7.4', '7.5', '8', '8.1', '8.2', '8.3', '8.4', '9', '9.1', '9.2', '9.3', '10', '10.1', '10.2', '10.3', '11', '11.1']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

Conan version:
```
➜  testconan conan --version
Conan version 1.48.1
```

Now, there's a patch for conan 1.46 that adds support for gcc 12:

https://github.com/conan-io/conan/pull/10595/commits/520f1ef54e3da588efba42c1d7da15b3cb0d28ab

and I looked at the files it modifies, and my installed version of conan *has* that modification.

What should I do / where should I fix things?

**Comment by memsharded** [comment]
Hi @tcanabrava 

Your ``settings.yml`` didn't migrate automatically most likely because you had some local changes. You should find in your cache a copy of the updated settings.yml.new that indicate this.

You can just remove your ``settings.yml``, they will be regenerated to add the new gcc versions.

**Comment by tcanabrava** [comment]
what about adding this information to the error message?

```your ~/.conan/settings.yml source differs from the conan internal settings.yml, delete this to be re-generated```

**Comment by memsharded** [comment]
This is the message that is being printed now:
```python
self.out.warn("*" * 40)
self.out.warn("settings.yml is locally modified, can't be updated")
self.out.warn("The new settings.yml has been stored in: %s" % new_path)
self.out.warn("*" * 40)
```

We don't want users to always remove it, because if they have local changes, what they want to do is to check the new things and update theirs.

Just in case: if users have custom settings.yml, the recommended way is to put them in a repo and use ``conan config install``

**Comment by tcanabrava** [comment]
@memsharded if that's the message being printed, feel free to close this bug report. on my case this was not being printed (1.48.1)

**Comment by memsharded** [comment]
> @memsharded if that's the message being printed, feel free to close this bug report. on my case this was not being printed (1.48.1)

Yeah, that is a bit weird, this seems to be sufficiently covered by tests. Please keep an eye on your next Conan version upgrade. The first time you run Conan after upgrade, you should see a message, at least ``Migration: Updating settings.yml``, and then some success or error message. If you have local modifications, you should see the above error message. If you don't please re-open and let us know and we will try to have a second look to see why it is not working in your installation.

**Comment by tcanabrava** [comment]
the problem about showing the message when an upgrade happens is that (on linux at least) most of the updates are done by the package manager, and there's a lot of noise.
I'd argue that *if* something fails because of a setting mismatch, we could show that message again (because settings.yml is not really touched by the developer for a while, he can forget that it exists, like I did)

**Comment by memsharded** [comment]
> I'd argue that if something fails because of a setting mismatch, we could show that message again (because settings.yml is not really touched by the developer for a while, he can forget that it exists, like I did)

That is the thing. Having this file modified directly by developers is bad practice, that shouldn't happen. If custom settings.yml are to be defined, they should be put in a repo and managed via ``conan config install`` so everywhere, CI, dev machines, they can keep in sync easily, not only for settings.yml, but all other things: remotes definitions, profiles, hooks, etc. This recommended flow will make those upgrade issues irrelevant, Conan tries to be not overly defensive against those user errors, because they have an impact on code readability, tests, maintenance, etc.
