### ISSUE TITLE
[question] Future Chalet support

### ISSUE THREAD

**Issue by jay-tux** [conan-io/conan#11468]
My friends recently recommended me to use [Chalet](https://github.com/chalet-org/chalet). Are there future plans to include Chalet generators? Or is this to be considered only once the project has grown.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jay-tux** [comment]
Just noticed this: chalet-org/chalet#12 and chalet-org/chalet#16 (last comment)

> Poor choice of words in the title -- this is referring to individual cpp file dependency checking (getting a list of headers) in the "native" build strategy (ie. without ninja/makefile behind the scenes).

> At the moment, you can invoke vcpkg and Conan with [process targets](https://www.chalet-work.space/docs/creating-targets?id=process-targets), but integration with those isn't really planned. The main issue is getting the toolchain info to the package managers and ensuring they work with the build. vcpkg is probably the most likely of the two to get integrated.

> Questions like this should go in [discussions](https://github.com/chalet-org/chalet/discussions) though.

(Quote copied June 16th, 2022, 11:17AM CET)

**Comment by memsharded** [comment]
Hi @jay-tux 

Yes, chalet is very new, we just very recently heard about it.
We don't plan at the moment to include built-in generators for Chalet, but mostly because we need to prioritize other things like Conan 2.0 and we do not have enough knowledge or experience about Chalet. But developing integration for Conan should be relatively easy, as Conan is designed to integrate natively with any other build systems (not necessarily via CMake). See for example https://docs.conan.io/en/latest/integrations/build_system.html.

There are a few resources (probably a bit outdated, but worth reading as a reference) creating an integration for Waf:
- https://docs.conan.io/en/latest/extending/custom_build_helper.html
- https://blog.conan.io/2019/07/24/C++-build-systems-new-integrations-in-Conan-package-manager.html

If the chalet maintainers or community are willing to contribute and maintain integrations for Chalet, we will be happy to support them. My recommendation would be:
- Create a "generator" for dependencies information, a "generator" for toolchain, and a "cli" wrapper to call the build commands.
- Put the 3 of them in a Conan ``conanfile.py`` recipe, to be used as ``python_requires``. The integration can be this way easily and most importantly, matured quickly, as the development will not be coupled to the Conan monthly releases.
- Once things are looking a bit more stable, contribute a PR to Conan client.

**Comment by jay-tux** [comment]
Thank you so much @memsharded

**Comment by memsharded** [comment]
Closing this as not planned at the moment.

However, if the Chalet community would like to have Conan support, and they are willing to contribute and collaborate, we will be happy to support, just let us know.
