### ISSUE TITLE
[question] Mixing artifacts of different build_type during development.

### ISSUE THREAD

**Issue by dkumsh** [conan-io/conan#11464]
We are trying to use conan (currenly 1.46.2) internally for both development and in CI/CD pipelines.
I have a number of third party dependencies which are currently building in the pipeline with **Release** build type.
My project is using these dependencies and I can build it with 'conan create' without any problem 

### A bit of background:
When attempted  to setup my project in CLion I ran into a problem:

I generated _conan_toolchain.cmake_ file and configured CMake in CLion to use it.
CLion loaded CMake configuration successfully however  when it started  building it threw a lot of errors where some #include statements not finding header files from these third party dependencies. 
I noticed that CMake did not generate -system/-I options for these includes. 

After several days of investigation I have found that the  problem is related to different build_type between conan  and CLion:   
- when I ran 'conan install' to generate _conan_toolchain.cmake_ file it used **Release** build_type from the profile 
`conan install  .. -pr=my-profile` - using **Release**
- in CLion by default I used a Debug profile, so that CLion ran  the following command to generate makefiles:  
   `cmake CMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake`
   (note that `CMAKE_BUILD_TYPE=Debug` part of the command was generated by CLion out of my control)

Unfortunately this mismatch (as it also was implicit) went unnoticed by me, by conan and cmake. 

**Question1 (or suggestion):**
Maybe it would be reasonable to have some checks in the generated `conan_toolchain.cmake`, to make sure that it cannot be used  with a different CMAKE_BUILD_TYPE, than the one which was used when `conan_toolchain.cmake` was generated.

**Question2:**
Does conan allow mixing artifacts of different build types. Normally in development process we would build the project in Debug mode have it's dependencies built in Release mode, and potentially with ability to switch some of them selectively to Debug if necessary.  
 

- [ X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @dkumsh 

yes, Conan allows to mix artifacts that belong to different settings. For example, lets say that you have multiple dependencies, ``lib_a``, ``lib_b``.... ``lib_z``, you can do something like:

```
conan install . -s lib_c:build_type=Debug -s build_type=Release
```

That will install all dependencies, and current consumer in ``Release``, but ``lib_c`` binary will be a ``Debug`` one. It is up to the user to define something that makes sense. In some systems, like Windows, it is more likely that that will be rejected by the compiler (incompatible runtime libraries), but in other systems like Linux, this might work ok

Note, you can also use patterns, like ``-s *:build_type=Debug -s &:build_type=Release``, where ``&`` means the "consumer" conanfile.


So Conan tries hard to not be overly protective, because there are many situations and users that would like to twist it in ways that we cannot anticipate. We have a design principle which is "do not block the user, let them do what they want to do". In general it is the responsibility of the user to be consistent, and only in very clear situations that we are almost 100% sure that something is an error, Conan will raise, because false positives are typically user blockers.


BTW, if you are using the modern integrations, I would recommend to upgrade to 1.49 and try the new genereated ``CMakePresets`` (generated by ``CMakeToolchain``), it is becoming super useful and friendly.

**Comment by dkumsh** [comment]
Thanks for you quick reply. 
That partially explains my questions (i.e. how I can install artifacts of different build types and use them together).

Probably my issue is specifically with conan_toolchain.cmake generator  

\# This command generates conan_toolchain.cmake with all dependencies built as **Release** :
`conan install .. -pr=my-profile -s build_type=Release`
\# And this command uses conan_toolchain.cmake, but it  uses **Debug**
 `cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake`
  
As a result when I build it (by running ninja in my case), cmake find_package commands fail to find the DEBUG packages (as it conan_toolchain.cmake is pointing to  DEBUG packages and accesses different path in conan cache) - that is my theory.

Addition: if in the second command I change Debug to Release, it works

**Comment by memsharded** [comment]
Yes, I see that can happen, and Conan will not find dependencies if provided the wrong inputs.

But it is also important to note that the toolchain is intended to be multi-config.
You might run:
```
conan install .. -pr=my-profile -s build_type=Release
conan install .. -pr=my-profile -s build_type=Debug
```
And if you are using the ``layout`` correctly, for example, those will not overwrite, and then issuing the right. In platforms like Visual Studio yo don't even provide ``CMAKE_BUILD_TYPE`` at configure time, only at build time, and thus it is impossible for Conan to give an error because the build type is not yet specified. For single-config environments ``CMAKE_BUILD_TYPE=xxxx`` is the responsibility of the user, in the right location. It is not that straightforward to know that it is a "wrong" build type, because it might happen that there are no dependencies, or similar things. Recent COnan version 1.48 or 1.49 introduced a new `` check_build_type_defined()`` check into the ``CMakeDeps`` generated code to verify that for single-config environments it is defined, but checking the actual value to match the provided data would be a bit more cumbersome.

So the idea is that the usage of ``CMakePresets`` automate this, removing the need to keep the ``CMAKE_BUILD_TYPE`` in sync manually, because that is already managed by the presets, instead of trying to provide a lot of defensive checks against potential incorrect configurations.

**Comment by dkumsh** [comment]
Indeed changing the first command as follows and leaving the second one unchanged fixes the CLion problem: 

`conan install .. -pr=gsr-default -s '*:build_type=Release' -s '&:build_type=Debug'`
`cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake`

My issue was that the second command was actually generated by CLion and I did not realise what was going on under the hood. 

Thanks for very detailed explanation.
