### ISSUE TITLE
[question] Enforcing conan info working from Conan cache only? 

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#11514]
Hi,

is it possible to use "conan info" in a way so that it only works from the local cache and doesn't try to go out to the remotes?
Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

``conan info`` operates in exactly the same way as ``conan install`` or ``conan create`` do, but without retrieven the binaries. It will construct the dependency graph, with exactly the same logic, because its purpose is exactly that. Then, if it can resolve things in the Conan cache, it will be fine, and it will not go to the remotes. If it cannot resolve things in the cache, and it is not allowed to go to the remotes (because for example you have disabled the remotes), it would fail, because it will not be able to resolve the dependency graph.

For all commands ``conan remote disable`` allows blocking Conan going to the remotes, you can certainly disable all the remotes before a ``conan info`` command, and see what happens.

**Comment by harsszegi** [comment]
Is it possible that aliases modify this behavior? I have emptied my remotes.json and tried to execute a "conan info foo/1.0.0@user/channel --paths" and 1.0.0 is actually an alias to another version of the same "foo" package. But when I emptied the remotes, conan info complained that there were no remotes defined.

**Comment by memsharded** [comment]
In theory it shouldn't, if the alias is able to resolve to the actual package it is pointing in the cache.

I have just tried with a small proof of concept, aliasing a package in my cache, disabling remotes and then ``conan install`` it, and it works without hitting remotes.

**Comment by harsszegi** [comment]
Whoa, it appears to be working, I had to clean my cache though, redownload the package, then disable the remote and info works fine. Thanks @memsharded again !!

**Comment by memsharded** [comment]
Glad to help :)
