### ISSUE TITLE
Question: Multi-core builds with conan cmake build

### ISSUE THREAD

**Issue by Brunni** [conan-io/conan#1151]
Hi,

what is the best pratice to allow multicore builds on linux system with "make"?
I have a 24 core server here and want to use all the cores :)

My current approach is this in the conanfile.py
```
 if self.settings.os == "Windows":
                        self.run("cmake --build . %s " % cmake.build_config)
                else:
                        env_build = AutoToolsBuildEnvironment(self)
                        with tools.environment_append(env_build.vars):
                                self.run("make -j25")
```

But I hope there is some better way still using cmake --build?

**Comment by Brunni** [comment]
Ok. I just found this code here https://www.conan.io/source/OpenCV/3.1.0-0/piponazo/testing
```
 compile_command = 'cd %s && cmake --build . %s' % (build_path, cmake.build_config)
        if self.settings.os != 'Windows':
            n_cores = tools.cpu_count()
            compile_command = compile_command + ' -- -j%s' % n_cores
```

This seems a better approach than mine. Is there some documentation or some example conanfile.py with best practices? e.g. git clone --depth 1 etc.

**Comment by memsharded** [comment]
Hi, 
Yes, so far automatic support for multicore builds is only provided in the ``CMake`` helper (and only for the Makefile generator).

I think the ``AutoToolsBuildEnvironment`` will also implement ``configure`` and ``build`` methods for the general case, so this is a valid feature request to take into account. Meanwhile, and for special cases, ``tools.cpu_count()`` is the way to manage it, because it will detect cores and also is user-configurable in ``conan.conf`` and with environment variables.


This is something to be documented, you can use:
- env var ``CONAN_CPU_COUNT``
- ``cpu_count`` var in conan.conf
- Do not specify= will use all the cores

**Comment by memsharded** [comment]
Now both the ``CMake`` and ``AutotoolsBuildEnvironment`` helpers will set the necessary flags for parallel build, even for Win MSVC (via /MP flag), and Makefile (via -jX).

Both are automatically handled if using the ``configure()`` and ``build()`` or ``make()`` methods. The Autotools one is still undocumented, but I have opened an issue for it. In the meantime, from the source code comments:

```python
 def configure(self, configure_dir=None, args=None, build=None, host=None, target=None):
        """
        :param configure_dir: Absolute or relative path to the configure script
        :param args: Optional arguments to pass to configure.
        :param build: In which system the program will be built. "False" skips the --build flag
        :param host: In which system the generated program will run.  "False" skips the --host flag
        :param target: This option is only used to build a cross-compiling toolchain.  "False" skips the --target flag
                       When the tool chain generates executable program, in which target system the program will run.
```

Please ask if you have further questions. Thanks!
