### ISSUE TITLE
How to promote a certain package revision to different channel without package download?

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#11535]
Using the copy command like described [here](https://docs.conan.io/en/1.44/reference/commands/misc/copy.html) all package variants (and revisions?) for a given package can be "copied" to a different channel.
I would like to use this functionality to promote a dedicated Conan package variant and revision from an "untested" channel to a "stable" channel once the testing was done at a later point of time. I would like to use the copy command but some information is missing in the docs before I am sure this is the right way:

1. Is the copy command requiring to have the package variant and revision to promote downloaded in the local Conan package cache?
2. Can I give also (recipe and pkg) revision information in the "reference" of the copy command?
3. If the answer to 1 is "Yes" Is there another way to copy a package directly on the remote (without download) from one channel to another?

[X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @MTomBosch 

sorry for the delay in answering.

For some context please read: https://github.com/conan-io/tribe/pull/16

``conan copy`` and channel promotions of Conan 1.X have been already removed from Conan 2.0, because they break the promise of immutability.

The recommended approach is using server repositories. You can upload "testing" things to a "testing" repository in the server. Once all the artifacts there have been approved, tests passing, etc, they can be promoted (copied) to the "develop" (development production) server repository. Servers like Artifactory can do this with API calls, in a fast and very efficient way, as artifact deduplication will not take extra storage space and won't do any actual copy.

In this way, the artifacts, packages and their references keep 100% immutables.

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
