### ISSUE TITLE
[question] Best workflow to use pipeline in jenkins

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#11546]
Hello Conan Folks, Thanks for helping me two times already.
I have 
We use Windows, github  and jenkins in my use case. 
I see there are many ways of using jenkins pipeline with conan but again what is the recommended way  : 
- https://docs.conan.io/en/latest/integrations/ci/jenkins.html 
  Here I already find a flaw that it does upload --all meaning that it will all possible packages to be published while I like probably
to upload only the package that just ran succesfully.
- https://github.com/conan-io/conan-package-tools#jenkins-ci-integration

I think there are common use-cases that may be same across development teams. Some of the common use-cases in my view are:
-  jenkins shall automatically be trigger for every commit on branch , PR or tag created.
-  jenkins shall differentiate between branch builds / tag builds and PR builds. 
- jenkins shall not publish any artifacts or packages generated from branches to conan release repositories  and vice versa.
-  jenkins shall automatically trigger the package dependencies. Example: A→ B → C a new revision of A automatically triggers B, C and publishes their new revisions if successful.
-  jenkins nodes shall update the conan cache as often as possible
- conan  cache gets locked when running parallel jobs on a node
What is the recommended way to seperate conan repositories: Meaning seperate ones for branch, PR and tag builds.
I would really like to avoid writing too much tooling on top of conan as this would make it difficult to move if there are new versions and/or interface changes with respect to conan. 
Could you guys please help me with some documentation or let me know if there is anything available  in that regard ?
Sorry if I may have missed any documentation on this regard.

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @maitrey 

Yes, the https://docs.conan.io/en/latest/integrations/ci/jenkins.html integration is mostly a thin wrapper that could help with the authentication/credentials of Artifactory, but regarding Conan commands it is not doing much. The commands are still very explicit, like:
```
stage("Upload packages"){
        String command = "upload \"*\" --all -r ${serverName} --confirm"
        def b = client.run(command: command)
        server.publishBuildInfo b
    }
```
So you can safely drop the --all if you don't want it, and you can do an upload for a specific ``package_id`` that was just created. Typically is not a big issue, because in your cache there will be just the package that you created, and if there is a previous package that you uploaded, it will know it and Conan will not reupload it again.


Regarding the CI flows, this is a complicated thing (using or not using Conan), and it really depends on what you need, the size of your projects and teams, the build times, company policies, etc. There are too many decisions to make, and certainly not a one size fits all. For example you can decide, for a given change, that you want to build first your product in Linux, and only if that passes, then build the Windows variant. Or want to build for example, package zlib/1.2.12, for both Linux and Windows, and if some of them fails, completely stop the build downstream for both platforms.
You might need to parallelize as much as possible builds, because you have very big dependency graphs that change often, or you might be fine with building the product in one single machine.
The re-build policies have to be defined, very typically very tied to versioning. For example, if I have my library ``pkg/1.0.0`` which is a static library, and I release ``pkg/1.0.1``, do I need to rebuild everything that depends on that, even other static libraries? If your versioning convention means that a patch should only change implementation, then certainly you don't need to rebuild all the consumers of ``pkg/1.0.1`` (which could have a version range like ``requires = "pkg/[~1.0]"`` to be able to get the latest patches of the upstream dependencies automatically).

There are some good practices, for example, using multiple server repositories to upload things while being built, but only promoting the packages from one repo to another when everything is green.

Also, the Conan cache is not concurrent. Instead of locking it, you probably want to use a separate cache (CONAN_USER_HOME env-var) for concurrent CI tasks. It will mean extra transfer, but not locking will be much faster.

This could be a good starting point: https://docs.conan.io/en/latest/versioning.html, and more specifically https://docs.conan.io/en/latest/versioning/lockfiles/ci.html. Be aware that lockfiles is a complicated feature in Conan 1.X, we did a great effort to simplify it in Conan 2.0. 

From there, we can probably start getting deeper in some of your above questions, maybe we can even discuss or chat some time if necessary and that could help.

**Comment by maitrey** [comment]
Hello @memsharded , thank you for your reply. I am evaluating if we could perhaps use conan for our use-cases. I will go through the links and would appreciate if you could discuss or chat at a suitable time. Thanks in advance!

**Comment by memsharded** [comment]
Great, I am closing this issue as a responded question at the moment, but please reopen to continue the conversation, or create new tickets for more specific questions. And you  can reach us at info@conan.io if you want to talk. Thanks!
