### ISSUE TITLE
[Binary Linters] Compiler check

### ISSUE THREAD

**Issue by opilar** [conan-io/conan#1156]
Is there any way to check compiler settings while building conan package?

Example: I'm on Windows and using `i686-4.8.3-win32-dwarf-rt_v3-rev2` toolchain and my .conan/conanfile.conf contains settings of `x86_64-4.8.3-win32-seh-rt_v3-rev2` toolchain:
```
[settings_defaults]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=4.8
os=Windows
```

Now I just building a package without knowing that my settings is incorrect.
I managed to make a mingw64 package with mingw32 settings.

**Comment by memsharded** [comment]
Conan is orthogonal and decoupled from the build system, and it is the responsibility of the package creator to be consistent. Conan can hardly do nothing if a package creator hardcodes in the ``build()`` method something like ``cmake -G "Visual Studio 14 Win64"``.

It is true, that whenever the build system allows it, checks can be introduced. They exist in the ``cmake`` generated ``conanbuildinfo.cmake`` file, so if the compiler and version mismatch from the one used at ``conan install`` time, it will raise an Error.

It is very recommended to use the ``profiles`` features, and also take advantage that for example compilers can be specified with environment variables, that can also be defined in profiles. Check for example:

- http://docs.conan.io/en/latest/mastering/profiles.html
- http://docs.conan.io/en/latest/howtos/cross_building.html

**Comment by ovidiub13** [comment]
The related problem that I've found is that profiles can lie. 

For example: If I set in the profile that I'm using gcc version 6.4, but my system has 7.2, conan has no idea of this, and the package will be created with it's settings stating the it was compiled using 6.4.

Now, durring the test phase of the package, cmake can catch this inconsistency, but, if someone doesn't se CMake?

The issue that I'm pointing out is not just about the compiler version. You can lie about pretty much everything in a profile file. Or better said, you can select the wrong profile by mistake, and don't realize until you get a crash on some other system that your app failed to link the right glibc, because one of it's dependencies was built on the wrong system, even though its package stated differently.

We should implement some checking in conan.

**Comment by lasote** [comment]
@ovidiub13 But with a profile you don't specify only settings, you can also specify environment variables and build requires, that can change the location of your compiler or even the standard library in a toolchain, so there is no way conan can be smart enough to make the right checks. 
If would require a lot of effort and maintenance work and it won't be good enough, unfortunately we don't have unlimited resources.

**Comment by ovidiub13** [comment]
I've proposed a solution for this in #1626

**Comment by lasote** [comment]
Recently we have been thinking about implementing a way to extend conan with binary linters, that will be able to perform this kind of checks, but it is not even in assigned roadmap. I'm renaming the issue to keep it tracked.

**Comment by memsharded** [comment]
Conan hooks has enabled this, and https://github.com/conan-io/hooks/pull/4/files contains such checks, which can be extended and customized too. So I think this can be closed, thanks.
