### ISSUE TITLE
[bug] self.info.settings.compiler is not present during validate (2.0 compatibility)

### ISSUE THREAD

**Issue by sobczyk** [conan-io/conan#11565]
When switching to the info object, `compiler` is missing.
Either the 2.0 recipe upgrade documentation is missing information that compiler can't be checked, or that part of information is missing

### Environment Details (include every applicable attribute)
  * Conan version: 1.50

### Steps to reproduce (Include if Applicable)

Switch from `self.settings.compiler` to `self.info.settings.compiler` in validate step
good example is the cmake recipe

**Comment by czoido** [comment]
Hi @sobczyk,
Yes, looks like in Conan 1 `package_id()` is executed before `validate()` so if you delete the compiler it fails when you try to check those values. In Conan 2 it does not fail because among other things the `package_id()` is executed after the `validate()`.
I'll mark this as `look-into` so we can check the problem and think of the solution for the migration process. 
Thanks for reporting.

**Comment by czoido** [comment]
Let's open a PR to check what would happen in Conan 1.X if we swap the order of the `package_id()` and the `validate()` and see what happens.

**Comment by memsharded** [comment]
It seems that it might be possible: https://github.com/conan-io/conan/pull/11576, at least tests are not breaking, we need to think further if there could be something not covered by tests.

**Comment by memsharded** [comment]
This will be solved by https://github.com/conan-io/conan/pull/11580, which defines a new ``validate_build()`` method, that runs before ``package_id()`` removes things, so will use ``self.settings`` without problem. Will be released in 1.51, testing and feedback once released would be appreciated
