### ISSUE TITLE
[bug] conan remove can't cleanup local cache (2.0)

### ISSUE THREAD

**Issue by sobczyk** [conan-io/conan#11562]
missing equvalent of `conan remove -b ref`

Conan 1.x has a feature to remove source folders and build folders
Conan 2.0 lacks that feature.

The feature would be needed for CI, where building large number of packages can exhaust disk space

**Comment by czoido** [comment]
Hi @sobczyk,

As you say this feature is not available in the `conan remove` command for Conan 2.0 but we have just documented one of the new features in Conan 2.0: Conan custom commands.

- https://docs.conan.io/en/2.0/examples/extensions/commands/clean/custom_command_clean_revisions.html
- https://docs.conan.io/en/2.0/reference/extensions/custom_commands.html#reference-commands-custom-commands

With this new feature you can create your own custom commands, on top of the new PythonAPI. So if one feature is not implemented with the released Conan version you can always implement one command that covers your needs for ci or other environments. 
Please note that the Conan PythonAPI is still in development and may change, but the idea is to document it and that it will be stable in the near future. 
One of the examples in the docs is to create a `conan clean` command that removes all package and recipe revisions but the latest, that could serve as a starting point to your command removing build and source folders. 
Hope this helps!

**Comment by fschoenm** [comment]
> As you say this feature is not available in the `conan remove` command for Conan 2.0 but we have just documented one of the new features in Conan 2.0: Conan custom commands.

Sorry, but is the idea of Conan 2.0 that basic functionality is not going to be implemented and everybody has to implement their own custom commands to get back to the same feature set that Conan 1.0 already had?

That leaves a very bad impression.

**Comment by czoido** [comment]
Hi @fschoenm,

Thanks for the feedback. With my mention of the custom commands, I just wanted to point out that we can now provide users with a powerful mechanism to develop their customized commands and unblock them in certain situations. 

We are not saying that this functionality or others will not be built-in in Conan because you can do it yourself, if most users consider that this or other feature must be there we will implement them. 

In this specific case we thought that as build folders do not exist in the remotes it would make more sense to have another separate command to clean the cache (that's why we added the [conan clean](https://docs.conan.io/en/2.0/examples/extensions/commands/clean/custom_command_clean_revisions.html) example to the 2.0 docs) but we also wanted to know if users demanded that funcionality before adding new commands. Probably I should have explained this more in detail in my comment above, sorry for that.

**Comment by db4** [comment]
> Sorry, but is the idea of Conan 2.0 that basic functionality is not going to be implemented and everybody has to implement their own custom commands to get back to the same feature set that Conan 1.0 already had?

Totally agree. Cleaning the local cache from sources and builds is the very basic functionality that allows to maintain the size of the cache within acceptable limits.  Why ask users to reinvent the wheel that they already had in version 1.x?

**Comment by memsharded** [comment]
Lets do the following:
- ``conan cache clean "*" -s -b -d`` is the basic command that removes all build folders and all source folders and downloads from the cache

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/13050, for next beta-10 (or 2.0 GA)
