### ISSUE TITLE
[question] Install spdlog/1.10.0 on a docker container with gcc and clang installed

### ISSUE THREAD

**Issue by TorstenRobitzki** [conan-io/conan#11581]
I have a docker container with GCC 12 and CLANG 11 being installed. I run conan 1.50 to install the following:

    [requires]
    spdlog/1.10.0

    [generators]
    CMakeDeps
    CMakeToolchain

with the following command:

    conan install .. --build missing -s compiler=gcc -s compiler.version=12 -s compiler.libcxx=libstdc++11 -s build_type=Release

This fails:

    CMake Error at conanbuildinfo.cmake:584 (message):
      Incorrect 'gcc', is not the one detected by CMake: 'Clang'

The configuration that is prompted by conan is what I expect:

    Configuration:
    [settings]
    arch=armv8
    arch_build=armv8
    build_type=Release
    compiler=gcc
    compiler.libcxx=libstdc++11
    compiler.version=12
    os=Linux
    os_build=Linux
    [options]
    [build_requires]
    [env]

Conan tries to build one of the dependencies from source (fmt/8.1.1) and there, CMake detects the GCC as the C compiler and CLANG as the C++ compiler :-/ :

    fmt/8.1.1: Copying sources to build folder
    fmt/8.1.1: Building your package in /root/.conan/data/fmt/8.1.1/_/_/build/4c7544f91af6003a3a63eff07df4071a450eec27
    fmt/8.1.1: Generator cmake created conanbuildinfo.cmake
    fmt/8.1.1: Aggregating env generators
    fmt/8.1.1: Calling build()
    -- The C compiler identification is GNU 12.1.0
    -- The CXX compiler identification is Clang 11.0.1
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Conan: called by CMake conan helper
    -- Conan: called inside local cache
    -- Conan: Adjusting output directories
    -- Conan: Using cmake global configuration
    -- Conan: Adjusting language standard
    -- Conan: Adjusting fPIC flag (ON)
    CMake Error at conanbuildinfo.cmake:584 (message):
      Incorrect 'gcc', is not the one detected by CMake: 'Clang'
    Call Stack (most recent call first):
      conanbuildinfo.cmake:141 (conan_check_compiler)
      CMakeLists.txt:5 (conan_basic_setup)

What can cause this mixture of compilers? Where do I have to search for a solution? Any ideas, pointers?

Thanks in advance,

Torsten

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jcar87** [comment]
Hi @TorstenRobitzki  - thanks for reporting this issue!

I believe CMake will check for the `c++` executable for the compiler, which in most cases will be `/usr/bin/c++`

Is it at all possible that this is pointing to clang? If you have the ability to drop into a shell inside that docker container, could you could run `/usr/bin/c++ -v` to check if `clang` or `gcc` is reported?

**Comment by TorstenRobitzki** [comment]
Hi @jcar87,
thanks a lot for looking into this! The output looks confusing to me :

    # /usr/bin/c++ -v
    Debian clang version 11.0.1-2
    Target: aarch64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin
    Found candidate GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/10
    Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/10
    Selected GCC installation: /usr/bin/../lib/gcc/aarch64-linux-gnu/10
    Candidate multilib: .;@m64
    Selected multilib: .;@m64

And here is the output of `cc -v`:

    # /usr/bin/cc -v
    Using built-in specs.
    COLLECT_GCC=/usr/bin/cc
    COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/aarch64-linux-gnu/12.1.0/lto-wrapper
    Target: aarch64-linux-gnu
    Configured with: /usr/src/gcc/configure --build=aarch64-linux-gnu --disable-multilib --enable-languages=c,c++,fortran,go
    Thread model: posix
    Supported LTO compression algorithms: zlib
    gcc version 12.1.0 (GCC) 

Shouldn't the build of `fmt` be somehow be configured to use a very specific compiler?

**Comment by jcar87** [comment]
Hi @TorstenRobitzki - thanks for checking the output of those commands.

It would indeed appear that `/usr/bin/c++` is configured to point to `clang`, while `cc` is gcc - this would explain why CMake is picking those up.

By default Conan will not configure the CMake builds with any specific compiler, but rather, it assumes that when you create a package with a specific configuration, you are making sure the underlying tools are the correct versions. As you can see however, the logic in the `cmake` generator when building `fmt` from source is correctly detecting the mismatch.

The solution in your case will depend on how `gcc` and `clang` where installed. Some suggestions:
* Make sure that `g++-12` is actually installed and available. You can try checking with `g++-12 -v`. I believe it's typical for `gcc` and `g++` to be provided by different system packages, there's a chance `g++` is not installed but `gcc` is.

* On Ubuntu systems, `/usr/bin/c++` is a symlink to ` /etc/alternatives/c++` - on a system with multiple C++ compilers, you would have to use the `update-alternatives` command to point `c++` to the correct `g++` executable, so that `c++` points to `g++-12`. This would ensure that CMake uses that compiler by default for C++. Additional information [here](https://askubuntu.com/questions/26498/how-to-choose-the-default-gcc-and-g-version).

* Alternatively, once you locate the desired `g++` executable, you can configure your Conan profile such that it will define the `CC` and `CXX` environment variables to point to the correct compilers. CMake will take these as a hint instead of falling back to `/usr/bin/c++` (CMake documentation [here](https://cmake.org/cmake/help/latest/envvar/CXX.html)). For an example on how to define environment variables in a profile, see [here ](https://docs.conan.io/en/latest/reference/profiles.html#examples) in the Conan documentation.

**Comment by TorstenRobitzki** [comment]
Hi @jcar87 

> By default Conan will not configure the CMake builds with any specific compiler, but rather, it assumes that when you create a package with a specific configuration, you are making sure the underlying tools are the correct versions. 

would that mean, that if I configure Conan to use GCC and try to install one single package A. Given that A depends on a second package B. Conan would then install B, but would let B choose what ever compiler it find suitable?

Thanks a lot for your suggestions! I will try them and will report, if one of them solves my problem.

**Comment by memsharded** [comment]
> would that mean, that if I configure Conan to use GCC and try to install one single package A. Given that A depends on a second package B. Conan would then install B, but would let B choose what ever compiler it find suitable?

There is an important clarification here, that might be important for other readers too. Defining ``settings.compiler=gcc`` in profile or in command line is not configuring Conan to use Gcc. It is just telling Conan that gcc will be used for building. But Conan will not setup the environment with that compiler or anything like that. 

There are other ways to help configuring the environment for example with
```
[settings]
compiler=gcc
...
[buildenv]
CXX=g++
```
Which will activate the ``CXX`` environment variable when ``self.run()`` is executed in recipes. If the build systems respect that env-var, they will use ``g++``. 

But still the configuration of the environment is independent of the declaration of the configuration.

**Comment by TorstenRobitzki** [comment]
Hi @memsharded,

now, everything makes much more sense to me. That was the point, I was missing. I've just build my two configurations with:

`conan install -e CC=clang -e CXX=clang++ --build=missing -s compiler=clang -s compiler.version=11  ..`
and 
`conan install -e CC=gcc -e CXX=g++ --build=missing -s compiler=gcc -s compiler.version=12  ..`

and everything was fine!

Thanks a lot!

**Comment by memsharded** [comment]
Great!

Just recall, that the modern tools for environment management do not use that way of specifying the environment (`-e CC=` not valid), and it will need the ``[buildenv]`` definition in the profile (profile usage super recommended instead of command line parameters), to be Conan 2.0 ready. 

Thanks for the feedback and following up!
