### ISSUE TITLE
[feature] Please provide all methods in base ConanFile

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#11592]
Currently, `ConanFile` base class doesn't provide methods which need to be overridden by user (for example `package()`), this makes writing mixins which add different steps to "common" flow harder.

Consider example:
```python

class MixinHeaders(ConanFile):
    def package():
        super().package() # < See below
        self.copy("*.h")

class MixinLibraries(ConanFile):
    def package():
        super().package() # < See below
        self.copy("*.so*");

# Consumer:
class MyConan(ConanFIle):
    python_requires_extend = ["shared.MixinHeaders", "shared.MixinLibraries"]
```

As I understand, in order for this to work with arbitrary set of mixins all of them should call `super().package()` (something called MRO involved). The problem is that for one of them `super()` will be `ConanFile` which doesn't have `package()` and recipe fails with `AttributeError`.

To work this around I had to use something like in every mixin:
```python
try:
    super_package = getattr(super(), "package")
except AttributeError:
    pass
else:
    super_package()
```
which is bit ugly.

Maybe I get something wrong.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Not related, but I think it is important, feedback: Please try to avoid complex inheritance schemes, like transitive inheritance or multiple inheritance. The ``python_requires_extend`` mechanism might be limited and not be able to support some of the Python standard inheritance. 

My general recommendation for all readers would be:
- Prefer composition over inheritance (that is a known design pattern, not only for this). In this case, it means explicitly calling the ``python_required`` modules, instead of extending them.
- Avoid multiple inheritance, including transitive inheritance. Try to reduce as much as possible the number of different python_requires packages to maintain


For this specific feature, I am not sure. I have been lately considering going the other way, as it has some advantages to not have the methods declared in the base ``ConanFile`` class, as it is more evident and explicit when the user is providing a given method or not, and that can be easily used to code behavior.

**Comment by ytimenkov** [comment]
I do agree that aggregation is to prefer. I just thought that since this mechanism is provided it should be used for these purposes. Was much skeptical myself about sharing python code as base classes when they were first introduced.

> For this specific feature, I am not sure. I have been lately considering going the other way

Yes, I noticed that conan prints / warns if there is no user-provided method. Was not sure about how important that feature was or mere convenience.

Let's close this one. Thanks for sharing your vision.

**Comment by memsharded** [comment]
> I do agree that aggregation is to prefer. I just thought that since this mechanism is provided it should be used for these purposes. Was much skeptical myself about sharing python code as base classes when they were first introduced.

We introduced it because of high pressure by some users, but it is one of those features that we don't love, because we feel that in general it adds little value (avoiding to type a couple of lines, 2 per method), but makes things more obscure (as you don't know by reading a recipe if it is just missing a ``package_info()`` method, or it might be reusing an existing one from the base class, that you need to go elsewhere to read). So in that regard, it is fine that the feature is there, but we will try to limit its use as much as possible, and definitely try to limit it to simple cases.

**Comment by memsharded** [comment]
I have added the ticket to discuss for 2.0-beta, to make a formal decision if we want to have some uniform criteria for this, because at the moment there are methods like ``genarate()`` or ``layout()`` that don't exist. Whatever is done, I think that having the same approach for all makes sense.

**Comment by memsharded** [comment]
Lets try:
- Remove blank methods in the base ConanFile
- Use the existence of the method in the user derived class to run them

**Comment by memsharded** [comment]
As the previous message suggest, we are going to try removing the methods from the base ``ConanFile``.
In any case, I don't fully see the above, because the ``ConanFile`` does actually have an empty ``package()``, so it is not a matter of providing the method in the base ``ConanFile``, it is already there?

**Comment by memsharded** [comment]
This ticket is being closed for 2.0-beta 2 by https://github.com/conan-io/conan/pull/11612, which removes the methods from the base class.

Please check the above comments, because it seems this issue was unrelated, as the base class already had the ``package()`` method, but the issue was still there.

**Comment by ytimenkov** [comment]
Sorry for late reply, was traveling...

> In any case, I don't fully see the above, because the ConanFile does actually have an empty package(), so it is not a matter of providing the method in the base ConanFile, it is already there?

Maybe it was not the best example. Or looking at the current file I see that `build_requires()` and `requires()` which are missing, but the idea behind is the same - call `super().build_requires()` from mixins (in case there are other mixins adding more requirements). In my case one mixin was for build system (we historically use waf) and another one is for running tests. In some cases they were used together, in some weren't.

But as discussed, I will go away from inheritance (In fact I already had "toolchain"-like helpers, but provided mixins for convenience). A bit of explicitness won't hurt.

**Comment by memsharded** [comment]
> Sorry for late reply, was traveling...

No prob, thanks for the feedback.

Ok, the ``build_requires`` method made more sense, as it was not defined.
In any case, if you can go explicit, we believe it is better in the midterm, even if not nasty super() tricks would be necessary, with multiple inheritance many different behaviors like order of evaluations, etc can easily bite you.

Thanks!
