### ISSUE TITLE
[question] Create packages and create a .tgz to upload.

### ISSUE THREAD

**Issue by gabyx** [conan-io/conan#11634]
Is it possible to create `conan create` a package in the local cache
in different CI agents (parallel process with different architectures), then archive the `.conan/data/...` folder structure, and at then end
push the package in a dedicated single agent where the `.conan/data` is recreated from the different archives and the `conan upload`ed?

We would like a functionality to store the `.tgz` which conan uploads somewhere on the disc, is that possible? Such that we can then upload it all together. Or do you know which folders need to be captured to be able to reassemble the `.conan/data` folder to succesfully upload all built packages?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @gabyx 

At the moment it is not possible, there is even some metadata both in an sqlite database and in disk, spread in some json files interleaved with packages, that would not be correct to transfer to another place, but it is still necessary, etc, it is complicated. There are more files than the .tgz too, and they are in different locations. Those .tgz are often not created until they are going to be uploaded, so it is not that they are always there in the cache either.

For Conan 2.0, we have cleaned a lot of things, and one of the things is making more available the process of upload, and how packages are prepared, zipped, etc in disk, so that will allow better to get access to the packages files. Still very preliminary and ongoing, but this will definitely help towards this goal.

So the recommendation at the moment would be to gather packages in temporary server repos with a ``conan upload``, and do a promotion (copy) of the contents of that repo to the definitive repo after all builds have completed.

**Comment by gabyx** [comment]
@memsharded: Thanks for the very nice answer and the solution therein.

**Comment by gabyx** [comment]
Is there a nice way with conan to move packages from lets say `@test/prepare` namespace/user to
`_/_` or do we need to do that with `jfrog` CLI ?
