### ISSUE TITLE
[question] Avoid error of `conan build` with dynamic package `version`?

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#11633]
We are using a dynamic package version derived from the Git hash.
Since the version is stored in the lockfile and checked by `conan build` this often leads to an error when working on the files in the repo (not on the conanfile itself). I understand that this should prevent cases of outdated conanfiles  but since it rarely changes we would prefer to not having this check performed.
Is there some way to avoid this check/error that i have overseen?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @petermbauer 

It is not clear what check are you talking about.
It is true that the ``conan build`` in Conan 1.X relies on some state saved in files, like ``conanbuildinfo.txt`` and others. Also will partially use the lockfile if it is there. Maybe renaming the lockfile file could serve as a workaround if that is the source of the issue?

**Comment by petermbauer** [comment]
sorry for the vague description, here is an example workflow and the resulting error:
```
$ mkdir build && cd build
$ git checkout mybranch
$ conan install ..
...
$ git checkout develop
$ conan build ..
Using lockfile: 'XYZ\build/conan.lock'
Using cached profile from lockfile
ERROR: Package recipe with version 84efc51!=b2e9eed
```

Conan 1.43.1 is used

**Comment by memsharded** [comment]
What happens if you run a ``conan install`` after ``git checkout develop``? If you change the branch, the commit, etc, it is expected that things might change, and a ``conan install`` will update things to match the checkout out branch?

**Comment by petermbauer** [comment]
After `conan install` it works again of course but in most cases the conanfile has not changed so it is redundant and just annoying.

**Comment by memsharded** [comment]
But you are effectively changing the version of the conanfile when you change branch, at least that is what it seems with ``ERROR: Package recipe with version 84efc51!=b2e9eed``, isn't it? So the ``conanfile`` always effectively change in this case, as it ``self.version`` has changed, and Conan need to be aware of that change? That is the only solution that I see, because this is not a check, this is how the ``conan build`` finds itself in the ``lockfile`` to extract the information from there. If the version is different, it is impossible to get it (even the name could be different, by the way). So the only alternatives that I see, is doing a ``conan install`` after changing branches (which is a good practice in any case, because there are so many things that can change in a recipe in different branch, like new or removed requirements, updated requirements, etc), or dropping the lockfile (remove the file)
