### ISSUE TITLE
[question] conan on windows-2022 in github actions

### ISSUE THREAD

**Issue by andiwand** [conan-io/conan#11698]
I noticed that conan will not work on an windows-2022 runner in github actions. see https://github.com/opendocument-app/OpenDocument.core/runs/7490830229?check_suite_focus=true#step:8:27

```
Conan: Unknown MSVC compiler version [1932]
```

Is this the expected behavior currently?

Do you know any easy solution to fix that? I thought of using sed on the `settings.yaml` but I fear it will be quite unstable in case of conan updates.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jcar87** [comment]
Hi @andiwand  - thanks for raising this issue.

That error would be coming from the [cmake-conan](https://github.com/conan-io/cmake-conan) integration. However, I can see that Visual Studio 2022 is supported in `cmake-conan` since version 0.17, and in Conan itself since version 1.40, so this error is not expected on recent versions.

Could you confirm which versions you are running?

**Comment by andiwand** [comment]
Hey @jcar87 ! I am running conan 1.50 https://github.com/opendocument-app/OpenDocument.core/runs/7490830229?check_suite_focus=true#step:5:8

Looking at cmake-conan here https://github.com/conan-io/cmake-conan/blob/develop/conan.cmake#L58 supports your argument. I haven't updated the script in a while and didn't know it would have an effect on compiler versions. https://github.com/opendocument-app/OpenDocument.core/blob/main/cmake/conan.cmake#L57

I will update and try again, thank you!

**Comment by andiwand** [comment]
now it works :tada: https://github.com/opendocument-app/OpenDocument.core/runs/7496078244?check_suite_focus=true

thank you @jcar87 and sorry for the noise!
