### ISSUE TITLE
Scope used in test_package

### ISSUE THREAD

**Issue by KalleDK** [conan-io/conan#1170]
In the Scope chapter you talk about using scopes to build tests

http://conanio.readthedocs.io/en/latest/mastering/scopes.html#scopes-vs-options

My thought was then that the test_package ofcourse could use this feature, so that ```conan test_package``` or the conanfile.py in the test_package could set the scope parameter build_tests. 

I know I can do a ```conan test_package -sc mypkg:build_tests=True```, but this is not a possible to do via the build.py file.

I could do all of this via options, but as you state, that would not be the correct way of doing it.

**Comment by memsharded** [comment]
I think maybe the best way to do it would be with profiles. In profiles you can declare settings, options, scopes, and environment variables. And you can even put them inside your project or in a shared repo, so all the team make sure to use the same profiles. 

So the most adequate call could be:
```bash
$ conan test_package -pr=myprofile
```
Furthermore, we are adding to profiles an interesting new field ``[build_requires]`` that will be able to inject dependencies only for build time, like a testing framework. Packages might use some environment variable for the package to run the test when defined, instead of having to define another input in form of a scope.

**Comment by KalleDK** [comment]
I see. Though I would have thought that a ```conan test_package``` would be the default a user would run. And that the conanfile could signal the main conanfile, that the tests should be build also.

**Comment by memsharded** [comment]
But, that is right. The ``conan test_package`` will run the default package construction and testing, that for most users it doesn't mean to run the full test suite on the library, but the fastest package build you can have. Maybe the semantics could be changed, if you want by default the unit tests for the source code to be always run, you might want a scope ``skip_tests`` that can be enabled for those wanting to skip the tests.

In any case, we will check if it makes sense to change the defaulting for scopes, somewhere. Not sure, but at least we will revisit this issue for next 0.23 release.

**Comment by KalleDK** [comment]
That makes sense, as a package manager.

Right now I use the suggested

```
conan install .. -sc build_tests=True
conan build ..
```

And then have the build() part to run the ctest

Though I would love to have that as a single line ala ```conan test_package```

**Comment by memsharded** [comment]
Sure, we will consider the possibility to add the default values. 
But if you want the ``conan test_package`` working right now, you also can, just by inverting the logic of the scope, use ``skip_tests`` and in your code ``if not skipe_tests:``. That way, the default will be running the tests, which is exactly the effect you want to achieve, by defining the default. Don't you think it is a viable option?

**Comment by memsharded** [comment]
Hi @KalleDK,

I am checking this. Actually, I am reviewing the whole approach about scopes. They were introduced in conan very early, much earlier than having environment variables. But then env-vars were introduced, and they are more widely used than scopes. They are well understood, can be set at many levels, including OS level, conan already has support for command line args, env-vars per package, etc. Regarding your use case, they are also very easy to be defaulted inside the package recipe, like:

```python
build_tests = os.environ.get("CONAN_BUILD_TEST")
```
What do you think?

**Comment by KalleDK** [comment]
I'll have to think it more through - it might solve the problem. I'll return when I have it tested.

**Comment by memsharded** [comment]
Ok, @KalleDK, thanks, please do so.

**Comment by memsharded** [comment]
We are going to speed the current release, so it doesn't take too much time, and there are some critical features, we would like to release soon as RC. I think this one can wait until 0.24. Thanks!

**Comment by memsharded** [comment]
Hi @KalleDK 

Did you have the chance to check environment variables? Did they solve your issue? 
Every day I am more inclined to deprecate, or at least do not recommend scopes and use environment variables instead.

Please tell me, because this issue is planned for next release, has been delayed a couple of releases, I would like to solve it. Thanks!

**Comment by KalleDK** [comment]
You can close it... Never found a really good way, but I would suggest removing scopes as you say.

I did what some have recommended, putting the unit tests in the build step. Though I feel some mismatch between conan being able to build and package - but not have any real way of integrating unittesting into the process.

As in:
git clone ... ( Get the source )
conan install .. get depends
cmake ..
cmake / ctest to run unit tests
conan test_package

Would love to see a "workflow" documentation for developers of a library, that wants to allow conan to be used with it.

**Comment by memsharded** [comment]
Yes, definitely improving the docs to clarify the flow for developers is on our TODO list.

In any case, please note that unittests cannot be run in ``test_package`` anyway, in a general sense, because the package will typically export only a thin API of its functionality, while unit-testing of the package requires to have access to internal implementation details that are not available in the package API.

That is why they should be integrated in the "build" step of the package. In any case, it could make sense to define a ``unittest()`` method in the recipe, that could be optionally run given some input. I will try to gather some feedback regarding this new possibility, and open a new issue to discuss it if necessary.

Thanks!
