### ISSUE TITLE
[question] How to choose which cmake version to use for build()?

### ISSUE THREAD

**Issue by alexisfrjp** [conan-io/conan#11741]
* `conan install .. --build missing`
* Centos 7 (cmake is defaulted to cmake2)

How can I change the command to use?

Adding `conan_cmake_program = cmake3         # environment CONAN_CMAKE_PROGRAM (overrides the make program used in CMake.cmake_program)` in **conan.conf** didn't change anything, it still uses `cmake`.

**Comment by czoido** [comment]
Hi @alexisfrjp,

Be aware that the `CONAN_CMAKE_PROGRAM` environment variable does not work with the [new integrations](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake.html) that are imported from the module `conan`, just for the [old one](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#cmake-reference) that is imported from the module `conans` (note the extra 's'). So if you have in your recipe something like "from conan.tools.cmake import CMake" that may be the reason that the variable is not affecting the cmake run by build().

Anyway, at Conan level, what you can do is use a [tool_requires](https://docs.conan.io/en/latest/devtools/build_requires.html) in your profile, so that it will affect all the packages that need to be built. You can do that by adding setting something like:

```
[tool_requires]
cmake/3.23.2
```

Conan Center Index has CMake packages for versions that vary from 3.15, to 3.23, so you can select the one that is more adequate for you.

Hope this helps.

**Comment by alexisfrjp** [comment]
@czoido Thank you for the fast answer.

* cmake3 version 3.17.5

I get this error when fmt library is built from conan:
```
fmt/8.1.1: Calling build()
fmt/8.1.1: CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/alexis/.conan/data/fmt/8.1.1/_/_/build/555df5705c3b9330f67f649abbe1b8662e37c16a/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/alexis/.conan/data/fmt/8.1.1/_/_/package/555df5705c3b9330f67f649abbe1b8662e37c16a" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" -DFMT_DOC="False" -DFMT_TEST="False" -DFMT_INSTALL="True" -DFMT_LIB_DIR="lib" -DFMT_OS="True" "/home/alexis/.conan/data/fmt/8.1.1/_/_/build/555df5705c3b9330f67f649abbe1b8662e37c16a/."
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.1...3.18 or higher is required.  You are running version 2.8.12.2
```

I just want Conan to use `cmake3` available on my computer instead of `cmake`.
tool_requires doesn't seem to support wildcard such as `cmake/3.*`.  That means I'll have to change all my profiles when cmake3 is updated to a higher minor version.

I tried to set it to the version available on my computer but I get errors:
```
cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by cmake)
cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by cmake)
```
It doesn't seem to be the way to go.

Also, I don't know why it stopped suddenly working (within July 2022) without having to do all that.

Regards,

**Comment by czoido** [comment]
Hi @alexisfrjp, 

Changing the default CMake version available system wide is something that is not directly related to Conan. You should probably do something like uninstalling the old cmake and do a symlink to cmake3... like `ln -s /usr/bin/cmake3 /usr/bin/cmake`
You will find more detailed information on how to that in the Internet (search for _Install cmake3 on CentOS 7_ or something similar).

By the way, the [tool_requires](https://docs.conan.io/en/latest/devtools/build_requires.html) syntax in profile allows [version ranges](https://docs.conan.io/en/latest/versioning/version_ranges.html), so you could use it like:

```
[tool_requires]
cmake/[>3.15]
```

**Comment by alexisfrjp** [comment]
I don't want to use cmake3 system-wide, I'd like Conan to use the cmake executable I want.

Using `[tool_requires]` doesn't work since it expects glibcxx versions that don't exist. 
I'm used to change cmake with a symbolic link in docker container but I don't want to do it on my local machine.

I give up and exclusively use docker to build my app until I move away from conan.

Thank you for your help anyway!

**Comment by czoido** [comment]
Hi @alexisfrjp,

In that case, you can try to prepend a path to the `PATH` where you create a symbolink link to the cmake3 binary and then add a `[buildenv]` section to your profile. For example:

```
mkdir ~/cmake3_symfolder
ln -s /usr/bin/cmake3 ~/cmake3_symfolder/cmake
```

Add the `buildenv` section to your profile, the folder will be prepended to the path each time Conan invokes the `build()` method (the `(path)` keyword stands for the current `PATH` variable):

```
[settings]
...
[buildenv]
PATH=+(path)~/cmake3_symfolder
```

Be aware that you have to set: `tools.env.virtualenv:auto_use=True` configuration so that this is automatically applied to the build. You can do that in the command line:

```
conan create . --profile=./<profile_with_buildenv> -c tools.env.virtualenv:auto_use=True
```

or adding it to the [global.conf](https://docs.conan.io/en/latest/reference/config_files/global_conf.html) file.

Hope this helps.
