### ISSUE TITLE
Is find_package (find_library, etc.) supposed to work with cmake_multi?

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#1177]
I've installed release and debug configurations with cmake_multi generator, however my find module does not find required libraries. I would expect it to find debug libraries in case of CMAKE_BUILD_TYPE=Debug and release libraries for CMAKE_BUILD_TYPE=Release

**Comment by memsharded** [comment]
This is a known limitation of cmake find modules, it is not implemented that way, because it cannot handle multi-config systems. If you really need such functionality, maybe you might be interested in multi-config packages: http://docs.conan.io/en/latest/packaging/package_info.html#multi-configuration-packages

**Comment by annulen** [comment]
Got it working by adding this code after `conan_basic_setup`:

    # Make find_package() to work with cmake_multi
    if (${CMAKE_BUILD_TYPE} MATCHES "Debug")
        set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH_DEBUG} ${CMAKE_PREFIX_PATH})
    else ()
        set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH_RELEASE} ${CMAKE_PREFIX_PATH})
    endif ()

I still think it might be useful to have `conan_set_find_paths` macro in cmake_multi to be able to call it manually, or maybe even do it automatically in case of makefile or ninja generator.

**Comment by annulen** [comment]
Multi-config packages may be indeed a way to go, but in most of cases it means having to do 2 builds in one recipe, which increases complexity of recipes.

**Comment by memsharded** [comment]
The ``conan_set_find_paths`` was removed from cmake_multi because it was problematic, I can't remember exactly what happened, but something related to the cmake management of ``CMAKE_BUILD_TYPE``. 

Agree, let's try to incorporate your lines and automate it whenever possible (make, ninja).

**Comment by memsharded** [comment]
Ok, I have added your lines in a macro (#1294) with a small modification:

```cmake
macro(conan_set_find_paths)
    if (${CMAKE_BUILD_TYPE} MATCHES "Debug")
        set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH_DEBUG} ${CMAKE_PREFIX_PATH})
    endif ()
    if (${CMAKE_BUILD_TYPE} MATCHES "Release")
        set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH_RELEASE} ${CMAKE_PREFIX_PATH})
    endif ()
endmacro()
```
Multi-config environments will not declare the ``CMAKE_BUILD_TYPE`` at configure time, so it will remain without effect (as is now), but it should work for makefile and ninja. I have added the call to the macro by default. What do you think?

**Comment by annulen** [comment]
My original intention was to make "", "RelWithDebInfo", and "MinSizeRel" to use "release" libraries, as well as any other user-defined build type

**Comment by memsharded** [comment]
I guess I can just make one ``if(CMAKE_BUILD_TYPE)`` and leave your if as it was, sounds good?

**Comment by annulen** [comment]
Yes

**Comment by memsharded** [comment]
I have added a test too: https://github.com/conan-io/conan/pull/1294/files

I have had to add set of ``CMAKE_MODULE_PATH`` too:

```cmake
 if(${CMAKE_BUILD_TYPE} MATCHES "Debug")
      set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH_DEBUG} ${CMAKE_PREFIX_PATH})
      set(CMAKE_MODULE_PATH ${CONAN_CMAKE_MODULE_PATH_DEBUG} ${CMAKE_MODULE_PATH})
 else()
```

**Comment by memsharded** [comment]
Released in 0.23

**Comment by packadal** [comment]
Hi,

I'm having a small issue with find_modules not working in cmake_multi, directly related to the `conan_set_find_paths` macro.

As far as I understand, `cmake_multi` is intended for Visual Studio and similar, who can have multiple configurations switched at build-time rather than configure-time. In CMake, those generators do not fill the `CMAKE_BUILD_TYPE` variable.

However, the `conan_set_find_paths` macro only adds to the `CMAKE_MODULE_PATH` **if** the `CMAKE_BUILD_TYPE` is set, which means never for Visual Studio. Thus my CMakeLists cannot find my package with the cmake_multi generator.


IMHO what makes most sense for Visual Studio is to have multi-config packages, and cmake_multi as generator, as VS users are used to be able to change build type on the fly. But this configuration does not work natively, and we had to add a workaround for CMake to be able to find packages.

**Comment by memsharded** [comment]
Yes, the problem, as I said before, is that cmake find functionality is not able to handle debug and release find paths. So using them, while it might work in some cases, is at least problematic. IMHO, find_packages is not the way to go, and it has more problems than advantages. For me it makes little sense to find things when you perfectly know where things are, because the package manager has installed them. 

Not sure about what you meant, if using ``multi-config`` packages, you shouldn't need the ``cmake_multi`` generator. 

> But this configuration does not work natively, and we had to add a workaround for CMake to be able to find packages

What do you mean? What is the workaround and why didn't it work "natively"?

Also, have you checked the recently added ``visual_studio_multi`` generator?

Many thanks!

**Comment by packadal** [comment]
Sorry, i was not clear.

Not all of our packages are multi-config, but some are (especially Qt, since having it single config is a pain for our windows users).

Which forces us to use the `cmake_multi` generator, and maybe this is where our error lies, in mixing things up.

`find_package` has more flexibility than conan in some case. e.g.  I can find some of Qt and link against some of it, whereas with conan it links against all libs defined in `CONAN_PKG::Qt`, which is not the behavior I want (to ensure a new dependency is introduced willingly, not by mistake).


The workaround I refer to is adding a path to the `CMAKE_MODULE_PATH` so the `find_package` works.

I have not checked the new generator just yet, but I don;t see how it will help the CMake side of things.

**Comment by memsharded** [comment]
Yes, you are right, sorry, if using cmake all around ``visual_studio_multi`` doesn't make sense

So, I think it is not a problem of mixing, it is just the limitation that cmake find doesn't work with multiple configurations, so it is only able to find either the debug or release package. The above fixes are just for ninja or make, not for Visual Studio.

I think that the best way to support this would be via a Visual Studio add-on, or something like this, that would do the switch of dependencies, when the build type is changed in the IDE.  There is some ongoing effort towards this, though it might take some time. Meanwhile, the alternatives could be:
- Use ``cmake`` generator and switch dependencies in the command line when you switch build-type in the IDE
- Use ``cmake`` generator and create 2 different project configurations in two different folders, and open the two solutions. Switch solution to switch build-type
- Use ``cmake_multi``, do the filtering of Qt libraries in the consumer cmake script, instead of ``find_package``. Should be just a few lines, selecting the libraries you really want, that will make sure that no other libraries are used.

**Comment by packadal** [comment]
Would using only multi-configuration packages work with the `cmake` generator ?

And the limitation really comes from Qt's `QtConfig.cmake` as it is the file that does all the finding, and it assumes Qt's standard layout of libraries, not a custom build with debug and release in separate folders.

Instead of filtering the list of libs, I'd really like conan to create a target per lib in a package, but that would open a whole new can of worms of dependencies between libs (e.g. QtWidgets and QtCore).
That would be the only way as far as I can see to have selective linking and not using CMake's `find`.

**Comment by memsharded** [comment]
> Would using only multi-configuration packages work with the cmake generator ?

Yes, they should work

>Instead of filtering the list of libs, I'd really like conan to create a target per lib in a package, but that would open a whole new can of worms of dependencies between libs (e.g. QtWidgets and QtCore).

Exactly, we have started a couple of times this path, and it goes directly to a hell of developing a complete dependency manager within the package manager, which is a bit insane. The issue behind this is that probably Qt shouldn't be one package, but probably modularized into packages, so users will use only those packages (and libraries) they really want, and will benefit in all senses (faster build times, less disk space, faster downloads, etc)
