### ISSUE TITLE
Support cmake_multi in conan imports command

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#1180]
`conan imports` command currently depends on `conanbuildinfo.txt` that has information only about one of cofigurations. That's why if cmake_multi is used, `conan imports` can do only half of work.

It might be a good idea to generalize multiconfig thing, e.g. by adding ability to generate all conan's output files with configuration suffix

**Comment by memsharded** [comment]
I think this might be a duplicated of: https://github.com/conan-io/conan/issues/851

In short: ``imports`` functionality is totally decoupled from generators. Then it is impossible to apply different logic for different generators that might be applied at conan install time ``conan install -g cmake_multi``, also because there is an independent ``conan imports`` command that will not use generators at all.

Please check the other issue.

**Comment by annulen** [comment]
What I want to do is to import both debug and release packages into one destination in a "multi" setup

**Comment by memsharded** [comment]
This is what the other issue, in the last comments, is about, to imports both debug and release packages into the user project. The ``cmake_multi`` approach actually installs 2 dependency graphs, the "Debug" and the "Release" one, in two different steps:

```bash
$ conan install -g cmake_multi -s build_type=Release -s compiler.runtime=MD ...
$ conan install -g cmake_multi -s build_type=Debug -s compiler.runtime=MDd ...
```

And then the generated ``conanbuildinfo_multi.cmake`` file will manage to mix both ``conanbuildinfo_xxxx.cmake``. 

If you want to import both from debug and release, the proposal with an environment variable can be easily applied:

```bash
$ conan install -g cmake_multi -s build_type=Release -e CONAN_IMPORTS_PATH=ReleaseX64
$ conan install -g cmake_multi -s build_type=Debug -e CONAN_IMPORTS_PATH=DebugX64
```
