### ISSUE TITLE
[question] cpp_info.system_libs usage

### ISSUE THREAD

**Issue by huso113** [conan-io/conan#11815]
Does it necessary to add cpp_info.system_libs attribute if I use system package as dependency?
How does it used afterwards?
I've built some packages without adding such info, and it works.. Am I missing something?
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jcar87** [comment]
Hi @huso113  - thanks for raising this question.

The `cpp_info` as defined in a recipe inside the `package_info()` method, expresses what system libraries a _consumer_ should also link against (as transitive dependencies) when linking against the libraries in the package (which are themselves specified in `cpp_info.libs`). 

This information is then used by generators (for example during `conan install` to consume it from a different place) to correctly populate the relevant linker flags. 

There are situations, as you point out, in which omitting this information from the `package_info()` still results in working packages, even if they depend on system libraries. Typically, this could happen when:
* your package contains shared libraries on Linux
* that have a transitive dependency on a system library 
* the system library can be found in the linker's default search path

In other cases, for example if the package contains a static library that depends on a system library, omitting this information will typically result in an error at link time when consuming the library due to missing symbols. It's also worth mentioning that on Linux you're more likely to see the problem once an executable is being linked. 

Would need more details to be able to advise further, but if you are certain your package contains libraries that have dependencies on system packages, it may be advisable to express this in `cpp_info.system_libs` for completeness. You may also want to look at the `system_requirements()` method (docs [here](https://docs.conan.io/en/latest/reference/conanfile/methods.html#method-system-requirements) and the newer `package_manager` integration (docs [here](https://docs.conan.io/en/latest/reference/conanfile/tools/system/package_manager.html#configuration-properties-that-affect-how-system-package-managers-are-invoked)), so that the consumers of your recipe can also ensure the relevant system package is installed.

**Comment by huso113** [comment]
Thanks,
I'll add `cpp_info.system_libs` for completeness, it good enough reason.

**Comment by jcar87** [comment]
Thanks @huso113! 

Will close this issue, but please let us know if something does not work as expected :)
