### ISSUE TITLE
[bug] most commands fail with "Specify the 'user' and the 'channel' or neither of them" even for "conan search"

### ISSUE THREAD

**Issue by zjufish** [conan-io/conan#11855]
i have this very weird issue since last week when using conan. for any conan command like conan search  or conan export i  get this error message that i dont understand. 

`
conan search openssl*   
ERROR: Specify the 'user' and the 'channel' or neither of them
`
`
conan export conanfile.py openssl/1.3.2u@user/channel
ERROR: Specify the 'user' and the 'channel' or neither of them
`
however it works with `conan search openssl -r all`

Tried 1.48* and 1.51*, all same error messages.  wondering why?

**Comment by czoido** [comment]
Hi @zjufish,

Thanks a lot for reporting. Could you provide the output before that error and some extra information like for example:

- Do you have more repositories than conancenter? 
  - If those are Artifactory instances, do you know which version? Did you recently update?
  - In case you have them, does it still happen if you remove those?
- Does it also happen if you use a clean cache?

I think that this may be related to these issues: 
- https://github.com/conan-io/conan/issues/11764 
- https://github.com/conan-io/conan/issues/10913#issuecomment-1083356588

**Comment by zjufish** [comment]
1. i have more repos than conan center. conanio + 3 company provided repo
2.We are using Enterprise Plus 7.38.10 rev 73810900  JFROG. 

3. the error msg is very misleading. why it needs user/channel even i run conan seach? 
and when im exporting package, i have the user/channel, why it complains about it? 
**conan export conanfile.py openssl/version@user/channel**
4. what do u mean by clean cache? should i remove .conan folder at my home dir?

**Comment by czoido** [comment]
> 1. i have more repos than conan center. conanio + 3 company provided repo
>    2.We are using Enterprise Plus 7.38.10 rev 73810900  JFROG.
> 2. the error msg is very misleading. why it needs user/channel even i run conan seach?
>    and when im exporting package, i have the user/channel, why it complains about it?
>    **conan export conanfile.py openssl/version@user/channel**

@zjufish  I suspect that something could be corrupt in the local cache, in Conan 1.X all packages that have the user defined must have also the channel and viceversa. Maybe, for some reason, there's a corrupt package that is only defining one of those and when you do a `conan search` and Conan loads that reference raises because of an invalid name. Maybe you can try the same search only against the Conan cache without remotes defined, or to separate remotes with the `-r` argument and we may find something useful.

Also, maybe you can use the [CONAN_TRACE_FILE](https://docs.conan.io/en/latest/reference/env_vars.html#conan-trace-file) to provide some traces of the API calls?


> 3. what do u mean by clean cache? should i remove .conan folder at my home dir?

Yes, doing the same in a clean cache could give us information about the origin of the problem (local cache or remotes) if you do not want to delete your cache, you can make Conan point to another folder for the cache using the environment variable [CONAN_USER_HOME](https://docs.conan.io/en/latest/reference/env_vars.html#conan-user-home).

Thanks!

**Comment by zjufish** [comment]
awseome. problem solved. i removed the bad cache and conan search is fine now.

**Comment by zjufish** [comment]
another question i have: 
build_info.py L147, 

ef _filter_paths(self, paths):
146         abs_paths = [os.path.join(self.rootpath, p)
147                      if not os.path.isabs(p) else p for p in paths]
148         if self.filter_empty:
149             return [p for p in abs_paths if os.path.isdir(p)]
150         else:
151             return abs_paths

should not the L147 be :
`
 if not os.path.isabs(p) else p for p in paths if p]
`

we have openssl package broke on this, after i applied the patch it seems to work.  for some reason, p is None in one case with openssl/1.0.2u. 

the error looks like: 
File "/somepath/python3.8/site-packages/conans/model/build_info.py", line 147, in <listcomp>
    if not os.path.isabs(p) else p for p in paths]
  File "/somepath/rh-python38/root/usr/lib64/python3.8/posixpath.py", line 62, in isabs
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType

can u confirm if this is bug or sth else?

**Comment by memsharded** [comment]
Hi @zjufish 

The last comment seems a completely new issue. I'd recommend closing this one as solved and opening a new one with a matching title.

Update, it seems https://github.com/conan-io/conan/issues/11856 is already that. Closing this issue.
