### ISSUE TITLE
[bug] Version object is no longer subscriptable

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan#11850]
Since https://github.com/conan-io/conan/pull/11830 `Version` is no longer subscriptable.

## Steps to reproduce

```
print(Version(self.version)[0])
```

See for example the CCI libtiff recipe and also https://github.com/conan-io/conan-center-index/issues/12155

**Comment by Adnn** [comment]
Probably related to conan-io/conan-center-index#12159

**Comment by jcar87** [comment]
Hi @planetmarshall  - Thank you for reporting this. Indeed as @Adnn kindly points out, this is a related issue.

This was an oversight on our part when updating these recipes, as the public API of `conan.tools.scm.Version` did not intend for this subscriptable and this was fixed in the Conan client to reflect the intended interface.

I will be issuing a fix for the `libtiff` recipe, many apologies for this.

**Comment by jcar87** [comment]
The issue with `libtiff` has now been fixed in Conan Center: https://github.com/conan-io/conan-center-index/pull/12160

Closing this issue but please feel free to add new comments if something does not work as expected. Thanks for your help!
