### ISSUE TITLE
[question] capture cmake commandline options?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#11864]
Hi,
I have a task that for a project, which defines its conanfile.py properly, the primary entrypoint for development should be its CMakeLists.txt so that it can still ve developed via Visual Studio or VA Code.
The idea is to inject manually everything in a CMAKE_PROJECT_INCLUDE_BEFORE, how Conan would do for cmake build —configure (that obviously still means I must provide some minimal set of CMake variables, like Conan profile, build type, etc.)
That would make it possible to setup CMAKE_TOOLCHAIN_FILE at least.
then, after the project() call is finished, I can do a conan install in CMake configure time, then the build could continue “normally”.
Is there a way to capture all CMake parameters that would be provided to CMake when conan build —configure is executed?
Thanks,

**Comment by harsszegi** [comment]
Closed because of missing response

**Comment by memsharded** [comment]
Hi @harsszegi 

Sorry this was not responded back then. Sometimes happen when team is very busy and some tickets fall through the cracks.

For reference to other readers,  the current recomendation for users wanting to launch ``conan install`` from CMake would be using the CMake dependency providers feature. Conan implemented a dependency provider in https://github.com/conan-io/cmake-conan. That means that the ``conan_toolchain.cmake`` cannot be used anymore, because CMake is driving the build and it would already use their own toolchains, but the dependencies location works well. 

Sorry again and thanks for your feedback.
