### ISSUE TITLE
[question] Recommended way to handle package requirements' conflicts

### ISSUE THREAD

**Issue by jlemein** [conan-io/conan#11882]
We are using conan now for some time and it works pretty nice. Now that our repository get's larger with more dependencies, it also becomes more difficult to update some of our dependencies, e.g. requirements.

* Newer versions of conan causes newer recipes of the same package to get uploaded. We use hashes and lockfiles to handle this. However many of our required packages do not specify hashes of their requirements. We need to override those requirements one by one. Over time this we end up with a long list of requirements that we override.
* As our list of dependencies get larger, the more likely we have dependencies that have conflicting lower level dependencies, such as zlib. For example one package requires: `zlib/1.2.12`, the other one `zlib/1.2.11`. By overriding one or the other, it causes another package to not have a prebuilt package available, because of `zlib/1.Y.Z`. I have found no other way than puzzling around what packages might need an upgrade, or do a local build with `--build` or store a custom build on our own artifactory server.

Are there any better ways to handle the second bullet point? 

What I can think of is splitting repositories and wrapping the requirements as private dependencies. However that is not really the recommend way to do as far as I understand. Moreover, our requirements' recipes also contain requirements that are not private.

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jlemein 

Those are very good questions.
The thing is that there is no perfect answer for everyone. It really depends on every user needs, the size of the teams, the desired speed, the acceptance of occasional failures in the main build branch or not, development practices, policies, regulations...

There are also 2 issues being mixed, lets make them explicit:
- One issue is potential versions or revisions conflicts, due to mismatches in declared versions or revisions in recipes, that fail when the dependency graph is being built, as a consistent graph cannot be computed
- The other issue is when a dependency graph has been computed, but some packages do not have existing binaries because some of its dependencies have been upgraded and due to policies or "modes" (like ``recipe_revision_mode``), they need to be built from sources.

Indeed making them private is not the way to go in the general case, that should be only done in very specific cases, and when you are very sure that it can be done at the linkage level: like a shared library, linking a static library as pure implementation detail, no exposed through public headers, nor any object being transmitted over its public API, etc. In any other case, it is likely to be causing problems, from ODR violations easily raised at link time to complicated runtime errors.

It seems that you are in the moment in the "conservative" part of the development speed, where all the dependencies are explicitly pinned, even down to revisions, and moving forward requires to update ``requires`` in recipes to the newer ones.
To start balancing to the side of more speed (but remember, it is always a trade-off, more speed might also mean some more "accidents" from time to time), the way to go is to start using version-ranges. That allows to move faster because it doesn't require to bump recipes ``requires`` of consumers. But it needs more automation in the CI side, to build the binaries of the consumers that would be affected, before users need them. For this we like the "products" approach: to have defined some critical important consumer projects, that can be used to build the dependency graph of binaries that should be built, and build them. If you have been using lockfiles, then you might have read https://docs.conan.io/en/latest/versioning/lockfiles/ci.html, that summarizes more or less the ideas. We know that lockfiles are challenging in 1.X, and we have made a great effort in 2.0 to simplify them.

**Comment by jlemein** [comment]
Thanks a lot. I appreciate your help and time you take to answer all of my questions so far. Without your help we would not have gotten this far with conan.

**Comment by memsharded** [comment]
> Thanks a lot. I appreciate your help and time you take to answer all of my questions so far. Without your help we would not have gotten this far with conan.

Glad to help. We just try to do what we would expect others to do for when using other tools, and we also love supporting our community of users :) 

If you consider this question responded, please close it, and don't hesitate to open new issues for any other further question that you might have. Thanks!
