### ISSUE TITLE
Access package folder from generate(self) function

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#11909]
I would like to package a toolchain in a conan package.

In my conanfile.py i have the `def generate(self)` function.
In here I would like to generate some custom stuff for a consuming project (much like the conan.cmake project/file).
For that purpose I need to know the package folder inside the `def generate(self)` function, but it is nowhere to be found.

Actually when i first install the package and it is created then the path is set, but subsequent calls to `conan install ./conanfile.py` calls the `generate(self)` function, but the paths are not set.

So how can I access the self.package_folder of this package every time `generate(self)` is called?

Rgds
Klaus

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Please note that ``generate()`` runs at install time, not at creation time. So when it runs, the package folder doesn't exist yet. Before that the ``build()`` method will be run, and finally the ``package()`` method. Only at this later step the package folder is created. Note that ``generate()`` even runs for a conanfile.py when executing a ``conan install .`` locally, not even creating a package, so the package folder is never created in this case.

So what you need to do is use the ``generators_folder`` to put stuff there, which the ``build()`` method can use, modify, manipulate if needed, and then the ``package()`` method will put it in the package folder.

**Comment by klausholstjacobsen** [comment]
I see the problem with `generate(self)` being called before the package folder exists.

I am not sure how to "use the `generators_folder`". I cannot seem to find any documentation.

So here's what I would like to do:
I would like to generate a file in the install folder (same folder as where the conanbuildinfo.cmake goes). This file should, among other things contain info about the whereabouts of the package we're installing (more specifically the package_folder).
How can I achieve this? Is there a method being called every time install is being called on a package even though the package is already installed (`package_info(self)` seems to be such a method) from where I have access to the install folder and package folder (`package_info(self)`does not seem to know the install folder).

Rgds 
Klaus

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

You can read some hints about it in the migration guide: https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html?highlight=generators_folder#the-generate-method. Basically you can use the ``self.generators_folder`` in the ``generate()`` method to get the location of that folder. It will typically be inside the "build" folder.

The problem with ``package_info()`` is that it runs exclusively for the dependencies, but not for the current package. When you are installing some dependencies, the ``package_info()`` of each dep will run, but not their ``generate()`` method. And for the consumer conanfile, the one used in the install, it will be the opposite, it will run its ``generate()`` method, but not its ``package_info()`` (as it will not have consumers).

You can definitely get the package folder of your dependencies, with ``self.dependencies["mydep"].package_folder`` in the ``generate()`` method of the consumer. But I think I am missing something, if your generated file needs to know the final location of the package, it might be possible to try to generate it in the ``package()`` method, but it still sounds like an antipattern, because packages need to be relocatable, they cannot contain absolute paths, otherwise those packages will not be usable in other computers, or even in the same computer in another cache location.

**Comment by klausholstjacobsen** [comment]
Yes, I might have left out important details due to missing knowledge. :-)

My consumer conanfile.txt basically looks like this:
```
[requires]
boost/1.73.0
openssl/1.1.1k


[generators]
cmake

[tool_requires]
MyToolChainPackage/1.0.0
```

It is in the conanfile.py of MyToolChainPackage that I wish to generate a file in the install dir of the consumer conanfile.txt.
The file to be generated is basically a cmake-toolchain file for the consumer project. This cmake-toolchain file must contain paths to compiler, sysroot etc. within the MyToolChainPackage package dir. The file generated by the existing CMakeToolchain generator is not adequate for my consumer project. 

Can this be done?

**Altenative idea 1:**
Maybe the way forward is to actually implement my own generator and then require that when using this generator the consumer project must also require the MyToolChainPackage.
With a consumer conanfile like this:
```
[requires]
boost/1.73.0
openssl/1.1.1k


[generators]
cmake
MyToolChainGenerator

[tool_requires]
MyToolChainPackage/1.0.0
```
Then MyToolChainGenerator would be able to access the package folder of the dependency MyToolChainPackage, correct?
And the generator would be able to generate the file in the install dir of the cosumer project, correct?

**Altenative idea 2:**
Maybe change the consumer conanfile.txt to a conanfile.py and the do the generate stuff there?

Rgds 
Klaus

**Comment by memsharded** [comment]
Yes, I'd recommend a variant from idea 2:

- Have the toolchain package itself create as much as it can. It is the "expert" in the toolchain, so everything that can be encoded there the better. If it happens that for some reason there is something in the toolchain files that need an absolute path, and can't be coded as relocatable, leave it open (a placeholder, a variable...)
- Use a ``conanfile.py`` for your consumer, and implement there a ``generate()`` method, that will do the bare minimum to prepare for the build, in this case, if it needs to replace something in the toolchain (do it on a local copy of the toolchain, instead of changing the package, packages are intended to be immutable).

I recommend this, because custom generators in that form have been removed in 2.0, in favor of ``generate()`` and ``python_requires``

**Comment by klausholstjacobsen** [comment]
Works like a charm, thank you.

To recap:
the host profile:
```
[settings]
...

[env]
MY_VAR = 123

[tool_requires]
MyToolChainPackage/1.0.0
```
conanfile.py of MyToolChainPackage
```
...
    def package_info(self):
        self.env_info.CC = os.path.join(toolchain_folder, "host/linux/x86_64/usr/bin/some-gcc")
...
```


Then from `generate(self)` in the consumer conanfile.py I can access `self.deps_env_info.CC`

I hope this is the correct way.

Bonus question:
Is there a way to access `MY_VAR` defined on the host profile from `generate(self)`in the consumer conanfile.py?

Rgds
Klaus

**Comment by memsharded** [comment]
Almost there :)

but still a small detail. You used the old, legacy environment management. I'd recommend:
- Use ``self.buildenv_info`` instead of ``self.env_info`` it is more powerful and expressive
- Use ``self.dependencies`` to access dependencies information instead of ``self.deps_cpp_info`` or ``self.deps_env_info``. Or use directly a pre-defined generator as ``VirtualBuildEnv`` to collect and get access to environment (also including profile ``[buildenv]``, which can be used to override conanfile defined ones if necessary)

Please have a look at: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html, and let me know (there it also explains how to get access to env-vars)

**Comment by memsharded** [comment]
It seems that this issue was solved correctly (please keep an eye on those recommendations, they are mandatory now for Conan 2.0), so closing this ticket, but feel free to create new tickets for any further question, thanks!
