### ISSUE TITLE
[question] requirements in a new recipe gathered from conanfile.txt

### ISSUE THREAD

**Issue by JeffHough** [conan-io/conan#11946]
I'm rather new to conan (I've only been using it for a few days), so I hope this question doesn't have too obvious of an answer that I'm just missing:

I had an existing project (project A) that I'm now using conan to manage the dependencies for. It has the following `conanfile.txt`:
```
[requires]
# list of dependencies and versions:
eigen/3.4.0
gtest/1.10.0
...

[generators]
cmake_find_package

[options]
gtest:fPIC=True
...
```

I would now like to create a second library (project B) which will depend on project A. So, I've started to create a recipe for project A. 

I noticed that as part of the recipe for project A, I have to list out the dependencies and options (i.e., `requires` list). However, all of that information is already available in the `conanfile.txt` of project A. 

So my question is: is there anyways to pass the `conanfile.txt` of project A to the `conanfile.py` recipe for project A? That way, the recipe will always use the same package versions and options that I define in `conanfile.txt`? Or, do I need to list out all of the dependencies twice (once in the `conanfile.txt` when I am consuming packages **from** project A, and once in the `conanfile.py` when I am writing out dependencies for project A so that it can be consumed by project B).

Thanks!

**Comment by memsharded** [comment]
Hi @JeffHough 

First, some advice, try to use the modern integrations, ``CMakeToolchain`` and ``CMakeDeps``, instead of ``cmake_find_package`` (legacy), as those are the new ones that will survive in 2.0 (already in beta). Check https://docs.conan.io/en/latest/reference/conanfile/tools.html

Regarding your question, the recommended way is to fully drop the ``conanfile.txt`` in favor of ``conanfile.py``, which can be used to ``conan install`` exactly in the same way. You shouldn't be using or trying to use both. The ``conanfile.txt`` is intended only for simple consumer cases, for all other cases a ``conanfile.py`` should be used instead. Maybe this part of the Conan 2.0 tutorial can clarify a bit: https://docs.conan.io/en/2.0/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html

**Comment by JeffHough** [comment]
Hello @memsharded - thank you for the quick response.

I've been reading up on the documentation, and it seems to be working well for compiling project A. That is, I'm able to:
`cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release` and everything builds perfectly.

However, it seems as though the cmake configuration flags that I set for the CMakeToolchain get ignored when I try to build project A into a conan package? Is there some way to tell `conan create .` to use the cmake toolchain file that gets generated by the recipe?

**Comment by memsharded** [comment]
Hi @JeffHough 

Yes, it seems you could be missing something in your ``build()`` method, like not using the modern ``from conan.tools.cmake import CMake`` that works together with ``CMakeToolchain``. If you want to share your ``conanfile.py``, we could have a look. Otherwise, the ``conan new hello/0.1 --template=cmake_lib`` (in an empty folder) is a good starting point of a project that works, you could do ``conan create .``.

**Comment by JeffHough** [comment]
@memsharded yes, that was it! I was still using `from conans import CMake`, rather than `from conan.tools.cmake import CMake`. I didn't realized there were two different `CMake` imports. I made the switch and the packaging is working well now.
Thanks for the help!

**Comment by memsharded** [comment]
Happy to hear that it is working now! 😃
