### ISSUE TITLE
[question] Conan 2.0 dependency (requirements) management concept

### ISSUE THREAD

**Issue by johschmitz** [conan-io/conan#11953]
I am not yet 100% familiar with the Conan 2.0 API so far I but also could not find extensive documentation on this particular topic so I want to ask this question and start a little discussion to see what details around dependency management have been considered in Conan 2.0.

So consider this list of the different requirement classes that we usually have to deal with (when Conan is used as build+deployment tool):

- Build time compiler/linker requirements
- Transitive build time compiler/linker requirements
- Build time tool requirements
- Runtime tool requirements
- "Optional" runtime tool requirements (making tool requirements (and thereby large downloads) optional without building lots of package variants)
- Runtime "data" requirements (sometimes input data, models and such are supplied via Conan packages, can probably be handled as "tool requirements" or so but might make the recipe code less intuitively understandable)
- Downstream build time compiler/linker requirements
- Downstream build time tool requirements
- Downstream runtime tool requirements
- Embedded (header only, copied shared or statically linked) "private" libraries
- Shared (via Conan sourced environment) libraries

I hope I did not forget or mixup anything (probably I did, please correct me with regard to completeness as well as terminology).

So my question is if all of this is possible to manage explicitly and cleanly with the Conan 2.0 requirements API?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @johschmitz 

Have you read this summary? https://docs.conan.io/en/2.0/whatsnew.html#new-graph-model

The first link is a video of a +1hr long talk about all these concepts. The other links are discussions in the Tribe where you can see some of the design decissions.

**Comment by johschmitz** [comment]
@memsharded Thx a lot for the answer, the trait approach (https://github.com/conan-io/tribe/blob/main/design/026-requirements_traits.md) and the package class approach (https://github.com/conan-io/tribe/blob/main/design/027-package_types.md) look promising for the problem at hand.

(Also now after reading this I am a bit concerned that the topic of build caching still does not seem to be a complete first-class citizen in 2.0 but that is for another discussion I guess...)

**Comment by memsharded** [comment]
> (Also now after reading this I am a bit concerned that the topic of build caching still does not seem to be a complete first-class citizen in 2.0 but that is for another discussion I guess...)

It is true that there is nothing explicit for build caching in Conan, but this is mainly because that part is way more connected to the build systems than to Conan. Conan 2.0 has added for example a plugin that can wrap any command run with ``self.run()`` in any recipe with a new command, which is a typical approach that some build tools like IncrediBuild follow. We are also aware of some users using build caching with Conan, and we listen to possible recommendations or features request that could help with that, but we haven't had many. Yes, that would be another topic, if you have some specific feedback, willing to hear it (in a new issue better, if this one is solved with the above links, it can be closed, and if you have new questions in the future, don't hesitate to open new issues)

**Comment by johschmitz** [comment]
I would maybe leave this open for a while such that people with the same question find it more easily until there is a beta or final release of 2.0 Closed issues tend to be overlooked, hence my personal strategy for question issues is to leave them open for a while unlike solved bug issues.

I am going to open a new issue for the caching topic.

**Comment by memsharded** [comment]
> until there is a beta or final release of 2.0

There is already a beta 😅 . Actually we have already released 2.0-beta.1, 2.0-beta.2 and we are working in the 2.0-beta.3. The docs at https://docs.conan.io/en/2.0 are for the latest released beta.

**Comment by johschmitz** [comment]
Okay good to know. When I see these version numbers I do wonder though if Conan 2.0 has full support for semver 2.0 version names/strings now? Like abc/1.23.0-beta.2@foo/bar

**Comment by memsharded** [comment]
> Like abc/1.23.0-beta.2@foo/bar

Yes, though we went a bit further, we have implemented ourselves an extension to semver, that admits any number of digits (1.2.3.4.5), and also mixing letters (1.2.3.a-beta.2), because that was very requested by users. With 3 digits, it should be semver compatible (version ranges syntax might be not fully complete, but enough for most cases)

**Comment by johschmitz** [comment]
I see. Could you maybe add this extra bit of information/explanation about the version string to the summary link above under this section https://docs.conan.io/en/2.0/whatsnew.html#new-package-id
It was a bit unclear to me without your additional explanation. 

Other than that I guess this issue is complete/done.

**Comment by memsharded** [comment]
Yes, we are writing new docs from scratch for 2.0, this will hopefully be improved there directly
Thanks!
