### ISSUE TITLE
[question] Lockfiles experimental feature status?

### ISSUE THREAD

**Issue by dmsurti** [conan-io/conan#11950]
When do we expect Lockfiles to move out of experimental status? We are planning to use Lockfiles for reproducible builds so would appreciate any inputs on it and how frequent are the breaking changes if any?

Thanks!

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @dmsurti 

Lockfiles in 1.X are extremely unlikely to break now. They have been completely renovated in 2.0, because we are aware that lockfiles in 1.X can be quite challenging for advanced and complete Continuous Integration flows. They have been greatly simplified in 2.0, and we expect that they will also be more useful, flexible and powerful.

If you haven't adopted yet lockfiles, I'd probably wait until upgrading to 2.0.

**Comment by dmsurti** [comment]
@memsharded Thanks for your inputs. Just as a user of conan and not a recipe author, do you think it can be useful to adopt/experiment Lockfiles now (we are currently using conan 1.51.3, the latest release) or is 2.0 release planned soon enough that it's worth the wait?

**Comment by memsharded** [comment]
We have done already tons of alpha releases and we are in 2.0-beta.2, about to release 2.0-beta.3. So yes, 2.0 is close.

If you are only a consumer of packages, the basics of lockfiles doesn't change that much. You can definitely start experimenting and using them in 1.X for the consumer case, where they get more challenging is for the creating packages cases when lockfiles need to evolve and change.

**Comment by dmsurti** [comment]
perfect. thanks for the clarifications. I am closing this ticket now.
