### ISSUE TITLE
[feature] Port `conans.tools.get_env()` to `conan.tools.env`

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11969]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

It's widely used in conan-center recipes (more than 10% of recipes).

**Comment by memsharded** [comment]
I'd say not to port this at the moment, because using it in recipes could be hiding things that will not work correctly.

I have been checking usage in recipes, and, out of 254 occurrences:
- 135 are ``tools.get_env("CONAN_BASH_PATH")``. This env-var does not exist anymore in 2.0
- 4 are Android related, like ANDROID_NDK_HOME, which now there are confs like ``tools.android:ndk_path`` to be used
- Around 20 are CC/CXX/CXXFLAGS variables. Note that if these variables are defined in ``[buildenv]`` sections in profiles, they are not activated in the Python process environment, it goes directly to generated environment scripts, or need to be accessed via ``VirtualBuildEnv()``
- 8 are ``CONAN_MAKE_PROGRAM``. This env-var also disappears in 2.0
- 49 are ``AUTORECONF``. If this comes from a Conan package, like it seems, the same, the env-var will not be activated in the Python process, but will go directly to files, or need to be read via ``VirtualBuildEnv``. I think for this case, it would run out of the box, if ``autoreconf`` is in the ``bin`` folder, the ``VirtualBuildEnv`` will add it automatically to the generated file PATH env-var, and every ``self.run()`` will use that file, so ``autoreconf`` will automatically work

**Comment by SpaceIm** [comment]
I understand the rational.

>     * 135 are `tools.get_env("CONAN_BASH_PATH")`. This env-var does not exist anymore in 2.0
>     * 4 are Android related, like ANDROID_NDK_HOME, which now there are confs like `tools.android:ndk_path` to be used

But if a recipe can't check anymore these variables, it can break users expecting these variables to be honored in a cross-compatible v1/v2 recipe (during the transition). It already happened indirectly to folks using recipes like `emsdk` & `android-ndk` in conancenter, when recipes they were relying on have been migrated to `CMakeToolchain`, while `emsdk` & `android-ndk` were still injecting their CMake toolchain to `CONAN_CMAKE_TOOLCHAIN_FILE` only. In the meantime, `env_info` is still honored (https://github.com/conan-io/conan/issues/11974#issuecomment-1229553132), so there are some discrepancies in the migration which are not obvious to follow for non-experimented users I think.

**Comment by SSE4** [comment]
how about something like?
```

.. conan/tools/env.py

ENV_MAPPING = {"ANDROID_NDK_HOME": "tools.android:ndk_path",
                               "CONAN_BASH_PATH": "tools.microsoft.bash:path",
                               ... MANY OTHER VALUES ... }

def get_env(conanfile, name):
    value = os.environ.get(name)
    if not value:
        return conanfile.conf.get(ENV_MAPPING[name])
    else:
        conanfile.conf.set(ENV_MAPPING[name], value)
        return value

```

**Comment by SpaceIm** [comment]
It's exactly what I had in mind. If someone is in conan v1 mode, fallack to conan v1 equivalent if conan v2 stuff is not set (or the opposite, I don't know).

**Comment by memsharded** [comment]
In any case, the ``tools.get_env()`` was only providing some (very basic) value if there were arguments that could be float, ints, etc. As basically all arguments that I am seeing are strings, I'd replace it for a python ``os.getenv()``

**Comment by SSE4** [comment]
unfortunately, pure `os.getenv()` wouldn't be a drop-in-replacement, for several reasons:
- it won't read from `VirtualBuildEnv` (cases of `xxxFLAGS` and `AUTORECONF`)
- it won't read from `conf` (cases of `ANDROID_NDK_HOME` and `CONAN_BASH_PATH`)

as a result, switching to `os.getenv()` in recipes will cause breakages for consumers.

**Comment by memsharded** [comment]
I think it is necessary to go case by case.

Lets start with ``CONAN_BASH_PATH``. This is an env-var that is being superseded by a conf ``tools.microsoft.bash:path``. So it is perfectly fine if recipes that are modernized check directly this conf.
Users using ConanCenter and relying on this, will need to modernize their profiles anyway to be 2.0 ready. So their profiles will look like:

```
[env]
CONAN_BASH_PATH=...

[conf]
tools.microsoft.bash:path=(path)...
```
Note, this profile is necessary anyways if we want to be able to migrate to 2.0. Then, recipes can safely upgrade to a clean ``self.conf.get("tools.microsoft.bash:path")`` without issues, no need to keep processing the legacy CONAN_BASH_PATH env-var.

Also note that if you want to explicitly keep an ``os.getenv("CONAN_BASH_PATH") or self.conf.get(...)`` it will not harm and it will not break. But I think it is much cleaner than having a somewhat obscure ``get_env()`` wrapper that is internally not getting environment but getting the information from a conf, and letting it survive in Conan 2.0 (because it would be breaking to remove it).

The other cases, like AUTORECONF, lets discuss them in separate comments.

**Comment by SSE4** [comment]
we cannot expect all conan center users to upgrade their profiles. they simply do not know about necessity to update. most of them just do `conan install` and keep using conan center binaries, and then it suddenly breaks (=stops reading from `CONAN_BASH_PATH`). in fact, it already happened a couple of times, when users were disappointed by these sudden changes (example - https://github.com/conan-io/conan-center-index/issues/11936).

anyway, if such drop-in-replacement cannot be provided, I don't see a better way besides recipes doing `os.getenv("CONAN_BASH_PATH") or self.conf.get("tools.microsoft.bash:path")` (plus similar code for other env variables).

**Comment by paulharris** [comment]
So what about this case in libvpx
```
def _patch_sources(self):
        # Disable LTO for Visual Studio when CFLAGS doesn't contain -GL
        if is_msvc(self):
            lto = any(re.finditer("(^| )[/-]GL($| )", tools.get_env("CFLAGS", "")))
            if not lto:
                replace_in_file(self,
                    os.path.join(self.source_folder, "build", "make", "gen_msvs_vcxproj.sh"),
                    "tag_content WholeProgramOptimization true",
                    "tag_content WholeProgramOptimization false",
                )
```

Check VirtualBuildEnv ?  How would I do that from within `def build(self)` ?

**Comment by paulharris** [comment]
I should mention I used `ld = os.getenv("LD","ld")` in `nasm/test_package/conanfile.py`, I guess that should change too.

**Comment by SpaceIm** [comment]
> So what about this case in libvpx
> 
> ```
> def _patch_sources(self):
>         # Disable LTO for Visual Studio when CFLAGS doesn't contain -GL
>         if is_msvc(self):
>             lto = any(re.finditer("(^| )[/-]GL($| )", tools.get_env("CFLAGS", "")))
>             if not lto:
>                 replace_in_file(self,
>                     os.path.join(self.source_folder, "build", "make", "gen_msvs_vcxproj.sh"),
>                     "tag_content WholeProgramOptimization true",
>                     "tag_content WholeProgramOptimization false",
>                 )
> ```
> 
> Check VirtualBuildEnv ? How would I do that from within `def build(self)` ?

You can create a VirtualBuildEnv instance and query variables, without calling generate. Though, the conan v2 way to inject cflags for users would be through `tools.build.cflags` conf.

**Comment by 0000matteo0000** [comment]
here's a very ugly workaround:

```
from io import StringIO
from conan import ConanFile, conan_version


def get_env(conanfile: ConanFile, variable: str, *args: list, **kwargs: dict) -> str:
    if "default" in kwargs:
        default = kwargs.pop("default")
        default_set = True
    else:
        default = None
        default_set = False
    unset_token = f"{variable}_is_unset"  # possibly make this a big random
    output = StringIO()
    if conan_version.major == 2:
        conanfile.run(
            f'echo -n "${{{variable}-"{unset_token}"}}"', *args, stdout=output, **kwargs)
    else:
        conanfile.run(
            f'echo -n "${{{variable}-"{unset_token}"}}', *args, output=output, **kwargs)
    value = output.getvalue()
    if value == unset_token:
        if default_set:
            return default
        raise ConanException(f"Variable {variable!r} is not set")
    return value
```

**Comment by memsharded** [comment]
Closing as not planned.
