### ISSUE TITLE
[bug] `buildenv_info` of `tool_requires` from host profile are not automatically injected to "build scope"

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11974]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Monterey
  * Compiler+version: Apple Clang 13
  * Conan version: 1.51.3
  * Python version: 3.10.6

### Steps to reproduce (Include if Applicable)

- Create a recipe A intended to be used as a build requirement, and inject a `FOO` env variable with some custom value (like "conan") in `self.buildenv_info` of its `package_info()`.
- create a profile `host_profile` with this recipe A in its `tool_requires`.
- Create a "conan v2" recipe B with a custom CMakeLists and write inside `message(STATUS "FOO: $ENV{FOO}")`. In its conanfile, don't add `VirtualBuildEnv` generator (because recipe B doesn't have `tool_requires` internally).
- call `conan create <path/to/recipeB> recipeB/1.0.0@ -pr:b default -pr:h host_profile`

=> `FOO` value is empty, and it shouldn't because I believe conan should inject `buildenv_info` of `tool_requires` from host profile automatically into "build scope" (indeed, a recipe can't predict tool_requires of host profile, so it shouldn't be its responsibility to hardcode VirtualBuildEnv generator if it doesn't have tool_requires internally).

If I add `FOO` in the legacy `self.env_info` of recipe A, it's properly displayed during CMake configuration of recipe B.

(I'm not in CONAN_V2 mode)

**Comment by memsharded** [comment]
> don't add VirtualBuildEnv generator (because recipe B doesn't have tool_requires internally).

this is the part that is missing.
The new integrations, declaring ``buildenv_info`` requires the consumers in 1.X to either:
- Explicitly declare ``VirtualBuildEnv`` , to generate the new environment files
- Use the new conf ``tools.env.virtualenv:auto_use=True`` to not need to explicitly declare the ``VirtualBuildEnv``, emulating the future Conan 2.0 behavior

This done this way, as opt-in, because otherwise there were chances (if new environment scripts were generated always) of breaking users.
