### ISSUE TITLE
[question] conan_package.tgz and providing permissions inside it in Artifactory

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#12038]
Dear Conan Folks,
I have a use-case that based on the user I need to provide access to headers or binaries.
When I create a package, contents of the package are:
- include/myheader.h
- bin/mybinary.exe
All of this is the content of conan_package.tgz uploaded into artifactory.
I understood that Permissions inside the artifactory repositories can be managed at file level.
In that case, what is the way to provide access to certain groups only to include headers and the others only to binaries ?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @maitrey 

I don't think it is possible to define permissions at a file level as you are suggesting, and I also strongly think it is not possible inside a ``tgz`` file. The Conan client will always be able to download the ``conan_package.tgz``, with whatever permissions are granted (which are permissions at the repo level, up to my knowledge), so it is impossible to restrict access to some partial contents inside a tgz file.

If anything, it seems that you want some package model around it, like splitting in different packages or something like that.

**Comment by maitrey** [comment]
Hello @memsharded , Thanks for replying so fast.
I would not like to split the contents of the package for the obivious reason that packages are split based on platform/variant.
Also the number of packages getting unmanageable. 
Is it possible to copy the contents of the conan_package.tar.gz (in a final step) by extracting it and then manage access rights via groups?

**Comment by memsharded** [comment]
> Is it possible to copy the contents of the conan_package.tar.gz (in a final step) by extracting it and then manage access rights via groups?

This is not possible, either in the server or in the client. Server side, servers don't have such power or capabilities to process files in that way based on some custom logic. Client side is useless, once the conan_package.tgz can be downloaded, any kind of division of files inside based on permissions is flawed.

I still think it is something that sounds that require a bit more model, not an infra-based solution. What about an option that says ``header_only: [True, False]`` or something like that? If the option is True, only the headers are packaged, and if it is False, only the exe is packaged.

**Comment by maitrey** [comment]
I could do that but it will lead to the issue that : I have model, documentation , include headers, binaries and because of all this , at the moment we have 3 different flavors of paltforms. If I include all of the above combinations it will lead to 3 * 4 =12 different packages. Doing this for 180-200 components meaning 200 * 12=2400 different packages making the packages unmanageable. Also might hit into Windows Path limitation .

**Comment by memsharded** [comment]
ConanCenter manages +130 different binaries for each one of the 1400 recipes x several versions. Package binaries (variants, flavors) in Conan scale without issues, not adding practically any extra burden. You don't manage 2400 packages, you manage 180 packages/components (and they will take care of the binaries inside them). This is one of the core value propositions of Conan, that it seems you are trying to avoid to use while requesting some kind of infrastructure related solution, which would be naturally order of magnitude more complex.

The short paths limitation has nothing to do with this, how is it related?

**Comment by maitrey** [comment]
In principle , 180 packages/components , however if something is NOT working as expected, one needs to debug. In that case, wouldnot it get cubersome to investigate the source of the problem? And if all for these packages are consumed by another package, it might hit into the windows path limitation.

**Comment by memsharded** [comment]
> In principle , 180 packages/components , however if something is NOT working as expected, one needs to debug. In that case, wouldnot it get cubersome to investigate the source of the problem? 

No, it will not be more cumbersome than with the way you are proposing. Installing dependencies built for debug mode is typically ``conan install . -s build_type=Debug``, and you can re-build locally from sources the package ``mypkg`` that you want to step into like ``conan install -s build_type=Debug --build=mypkg``, and you will typically be able to step into the source code of that binary. 

Using Conan built-in mechanisms to model things helps a lot. For example ``options`` are displayed in Artifactory server for each package binary, and it might be leveraged in server API and devops processes beyond Conan. The ``conan search ... --table=file.html`` will create a table with existing binaries that can use settings and options to filter binaries. Many commands understand ``options`` as arguments. All those built-in, commonly used mechanisms to model the different variants of packages, which seems what you are trying to achieve will help to debug, understand, reproduce and fix issues. 

> And if all for these packages are consumed by another package, it might hit into the windows path limitation.

The path length will not increase because having more package variants, this is not how it works. The Windows path limitation happens when some library source code contains multiple levels of nested folders, making the paths for building too long. Having hundreds of binary package variants will not change that, but still will not produce longer paths for consumers.

**Comment by maitrey** [comment]
Thanks for the explanation. I will create the variants and also try the steps with build_type=Debug and check.
