### ISSUE TITLE
[question] What's the difference between using generators cmake and CMakeDeps, CMakeToolchain?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#12040]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by maitrey** [comment]
Purpose of CMake generator is to prepare the build, generating the necessary files.
CMake Toolchain is the toolchain generator for cmake. It translates the current package configuration, settings and options into CMaketoolchain syntax.
CMakeDeps generates XXX-config .cmake or FindXXX.cmake files per dependency, together with other necessary cmake files like version flags and directory data or configuration.
To understand this, it is important to understand CMake stages.

**Comment by lasote** [comment]
*Note: `cmake` (lowecase) is a deprecated generator that is removed in Conan 2.X.
`CMake` is the "build-helper" to call the `cmake` tool taking advantage of the information generated in the `CMakeToolchain`. 
You can follow the 2.0 tutorial here, maybe it helps to understand: https://docs.conan.io/en/2.0/tutorial.html

**Comment by SpaceIm** [comment]
1. **`cmake` vs `CMakeToolchain` generators**

   `CMakeToolchain` generator is the successor of the legacy `cmake` (or it's weak equivalent `cmake_paths`) generator.
   It's important to understand their goals:
   - being the glue between dependencies installed by conan and CMake, so that:
     - all `find_*` commands (`find_package()`, `find_program()` etc) in a CMakeLists related to dependencies can succeed and find conan dependencies before any other dependencies on the system.
     - CMake build modules packaged in dependencies can be added to CMakeLists with `include()` directive.
   - propagate configuration from your host profile or global conf: C++ standard, CMake generator, vc runtime, libcxx, custom toolchain file etc

   Legacy `cmake` generators was intrusive (making the CMakeLists tied to conan details), and by default `conan_basic_setup()` was injecting too much things (global injection of all include & lib dirs for example, manipulation of several global CMake variables).
  `CMakeToolchain` is not intrusive, it only generates a toolchain file (and CMakePresets file?) which can be externally injected through cmake command line (you can do this manually or by using `conan.tools.cmake.CMake` in a build fully managed by conan). It allows to write a "package manager agnostic" CMakeLists, and it tries to be as minimalistic as possible to ensure its "glue responsibility".

   Another difference is that the mapping between recipes options and CMake options is done through `CMakeToolchain` while with `cmake` generator this task was delegated to `conans.tools.CMake` build helper.

2. **`cmake_find_package`/`cmake_find_package_multi` vs `CMakeDeps`**

   `CMakeDeps` generator is the replacement of `cmake_find_package`/`cmake_find_package_multi` generators, so basically it creates CMake config files and eventually Find module files. The main difference in `CMakeDeps` is that consumers can't decide anymore if a CMake Find module file or a CMake config file or both or none are created, it's fully controlled in the conanfile.py of each dependency.

3. **`conans.CMake` vs `conan.tools.cmake.CMake`**

   `conans.CMake` is a legacy build helper supposed to be used in a conanfile.py in conjunction with `cmake` generator and assuming `conanbuildinfo.cmake` (and conan_basic_setup() called afterwards) was included in a CMakeLists.

   `conan.tools.cmake.CMake` is the new build helper supposed to be used in a conanfile.py in conjunction with `CMakeToolchain` generator.

**Comment by risa2000** [comment]
@Tumb1eweed 
There are like 5 CMake supporting generators documented here:
https://docs.conan.io/en/latest/integrations/build_system/cmake.html
which basically **you do not want to use** as they  are the "legacy" generators.

The generators you want to use are `CMakeToolchain` and `CMakeDeps`, which are documented here:
https://docs.conan.io/en/latest/reference/conanfile/tools/cmake.html

It is confusing and it took me quite some time to realize that, partciularly also because the off-site documentation is usually written around those legacy generators and they are not compatible.

Also as suggested by @SpaceIm watch for the imported namespace name. If it is `conans` (with the ending `s`) you probably do not want to follow that and should look for some other doc/example which imports the Conan modules from `conan` (without the ending `s`).

**Comment by Tumb1eweed** [comment]
> @Tumb1eweed There are like 5 CMake supporting generators documented here: https://docs.conan.io/en/latest/integrations/build_system/cmake.html which basically **you do not want to use** as they are the "legacy" generators.
> 
> The generators you want to use are `CMakeToolchain` and `CMakeDeps`, which are documented here: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake.html
> 
> It is confusing and it took me quite some time to realize that, partciularly also because the off-site documentation is usually written around those legacy generators and they are not compatible.
> 
> Also as suggested by @SpaceIm watch for the imported namespace name. If it is `conans` (with the ending `s`) you probably do not want to follow that and should look for some other doc/example which imports the Conan modules from `conan` (without the ending `s`).

thanks!

**Comment by memsharded** [comment]
Closing as responded
