### ISSUE TITLE
[Feature] Adding option for system_requirements to "conan info" graphs

### ISSUE THREAD

**Issue by zlacelle** [conan-io/conan#12058]
It would be very helpful to also be able to see the dependency tree for Conan project system-level dependencies, either through SystemPackageTool or the new Conan 2.0 package_manager package.

**Comment by memsharded** [comment]
Even if I understand this request, I think this is very complicated at the moment, for a reason: these dependencies are not modeled at all by Conan. Conan doesn't know, it only executes some ``system_requirements()`` method (which will not be executed at ``info`` time, because ``info`` doesn't install things), and inside there there could be conditionals and other stuff, including calling helpers like ``Apt`` or ``Brew``, to call for  installation of those system dependencies.

At this moment, I think building model around that is simply too much, it is not worth the effort for the value. I'd recommend users wanting something more structure:
- To declare their system deps in ``conandata.yml``
- To use ``self.conan_data`` inside their recipe ``system_requirements()``
- To use some automation (a Conan 2.0 deployer, or simply some code in a ``generate()`` helper could be good) to collect and display that information.

**Comment by zlacelle** [comment]
Ah, OK, this makes sense. Basically, you pass the system_requirements() calls through SystemPackageTool directly to Python, so you're not actually aware of what these are. Ideally, I would love for them simply to live in the dependency tree by string; they do get resolved if you have multiple options listed, so I'd like to track these. But, understand that this is a hard feature how it's structured now.
