### ISSUE TITLE
[question] Correct way to use XCrun in Conan v2

### ISSUE THREAD

**Issue by paulocoutinhox** [conan-io/conan#12071]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Hi,

What is the correct way to use XCRun in conan v1/v2 compatible?

I made this:
https://github.com/nativium/nativium/pull/21/files#diff-46d8e7b650df6bb59541dab2a0fc2c56436aeb97a5c4079e18a6831515164bddR3-R7

But it is ugly:
`from conan.tools.apple.apple import XCRun`

Thanks.

**Comment by czoido** [comment]
Hi @paulocoutinhox,

We did not make the XCRun tool public yet on purpouse. You can check the comments [in the sources](https://github.com/conan-io/conan/blob/develop/conan/tools/apple/__init__.py).
In conan2 we tried to make everything more explicit, so the idea is that instead of using XCRun, you use the configuration `tools.apple:sdk_path`. This value is used inside the generators to set the path for the sdk location and will be passed as `SDKROOT` or `-isysroot` depending on the generator used.
Hope this helps, please tell me if this would fit your needs.
Thanks for the question.

**Comment by paulocoutinhox** [comment]
Hi,

Ok, i see that you have a method that return it:

```
def apple_sdk_path(conanfile):
    sdk_path = conanfile.conf.get("tools.apple:sdk_path")
    if not sdk_path:
        sdk_path = XCRun(conanfile.settings).sdk_path
    return sdk_path
```

But how i can use it in practice?

Or i need use XcodeBuild, like this:

```
x = XcodeBuild(self)
sysroot = x.sdkroot
```

?

Thanks.

**Comment by czoido** [comment]
Hi @paulocoutinhox,

The `apple_sdk_path` tool is not meant to be used in recipes, only documented tools should be used. For the moment, the valid apple tools are `fix_apple_shared_install_name`, `is_apple_os`, `to_apple_arch`, `XcodeDeps`, `XcodeDeps` and `XcodeToolchain`.

The recommended use is that instead of doing something like:

```
path = apple_sdk_path(self)
```

or

```
xb = XcodeBuild(self)
path = xb.sdkroot
```

you do:

```
path = self.conf.get("tools.apple:sdk_path")
```

To set that [configuration](https://docs.conan.io/en/latest/reference/config_files/global_conf.html) you can do it in your profiles in the `[conf]` section:

```
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=Macos
....

[conf]
tools.apple:sdk_path=path/to/sdk
```
or directly in the command line:

```
conan create . -c tools.apple:sdk_path=path/to/sdk
```

Hope this helps.

**Comment by paulocoutinhox** [comment]
Hi @czoido 

The only necessary code is this?
```
path = self.conf.get("tools.apple:sdk_path")
```

Because inside conan it has a fallback:

```
def apple_sdk_path(conanfile):
    sdk_path = conanfile.conf.get("tools.apple:sdk_path")
    if not sdk_path:
        sdk_path = XCRun(conanfile.settings).sdk_path
    return sdk_path
```

It is here:
https://github.com/conan-io/conan/blob/9c4487efc26118dc5953720bddd3eb265c2f485e/conan/tools/apple/apple.py#L73-L77

I cant set on conf, i need set on my toolchain to make it work automatically.

I can't keep making my process worse because of Conan version 2. I need to keep getting the SDK path correct as it was before.

I need only replace it here:
https://github.com/nativium/nativium/blob/main/conan/darwin-toolchain/conanfile.py#L102

I need a way that don't will change in v2.

**Comment by czoido** [comment]
Hi @paulocoutinhox,

Let me mark this issue as look-into and check with the team so we can discuss what how we should approach these cases.
Thanks a lot for the feedback.

**Comment by czoido** [comment]
Hi @paulocoutinhox,

After having a look at this with the team and checking that some Conan Center recipes also use `XCRun` we will make it public, so I'm marking this issue with the label feature for the next release. We also talked about adding some internal code or arguments to [address this](https://github.com/nativium/nativium/blob/1b138e8b5098aae94009f59561926fc98f112716/conan/darwin-toolchain/conanfile.py#L94-L99).

I would like to comment as well that in [Conan 1.48](https://github.com/conan-io/conan/pull/10985) we added support for the CMakeToolchain for several of the flags and CMake variables that you are using in the toolchain with the intention of replace those toolchains and have built-in support for that.  You can check the support in CMakeToolchain [in the docs](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#conf). It has not support for AutotoolsToolchain yet but we will add it soon.

**Comment by paulocoutinhox** [comment]
Thanks @czoido 

Autotools use this part?
https://github.com/nativium/nativium/blob/main/conan/darwin-toolchain/conanfile.py#L105-L106

And CMake use this part?
https://github.com/nativium/nativium/blob/main/conan/darwin-toolchain/conanfile.py#L108-L115

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12172, will be in 1.53

**Comment by paulocoutinhox** [comment]
Nice and thanks!
