### ISSUE TITLE
Transitive dependencies for required system libraries

### ISSUE THREAD

**Issue by betheev** [conan-io/conan#12079]
Hi,

say I want to create a conan package for mylib and mylib depends on Poco which  is installed as a system library by the consumer of mylib. In mylib's conan recipe, I:

* define the `system_requirements()` method, where I call `SystemPackageTool(default_mode="verify").install("libpoco-dev")` to make sure that's the case.
* set the `self.cpp_info.components["myLibComponent"].system_libs` attribute to ` ["Poco::Foundation"]` in the `package_info()` method to indicate the dependency of mylib on Poco::Foundation.

Then, I create a test package and in its CMakeLists.txt file I call `find_package(mylib REQUIRED)`.

When I build test_package, I get the following error:
```
  Target "test_package" links to target "Poco::Foundation" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```
Of course, if I add the line `find_package(Poco REQUIRED COMPONENTS Foundation)` to the CMakeLists.txt file of test_package, the error goes away.

My question is, how do I specify in mylib's conan recipe that mylib depends on the Foundation component of the Poco system library so that the CMakeDeps generator includes something link `find_dependency(Poco REQUIRED COMPONENT Foundation)` in the files it generates?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @betheev 

I think the issue lies in here:
> self.cpp_info.components["myLibComponent"].system_libs attribute to ["Poco::Foundation"]

This is not possible, the ``system_libs`` is a raw "libraries" field, meaning it should be something like ``.system_libs = ["m", "pthread"]``. If you want to define some poco library, you need to specify its name, like ``poco_foundation`` or whatever actual library name. The ``xxx::yyyy`` syntax is only used for Conan package components.

Also, it should only be used for system libraries, what do you mean by:

> Poco which is installed as a system library by the consumer of mylib. 

You mean like ``apt-get install poco`` or something like that? The consumer of mylib will run after mylib, so this might not work as you expected. System libraries should be in the system already, or installed in the recipe that declares the ``system_libs``, but not in others.

**Comment by betheev** [comment]
Hi @memsharded,

yes, by system libraries I meant libraries that are installed via the OS package manager, for example, `apt get libpoco-dev`. I had also tried using the `system_libs` attribute with the "raw library", but it didn't work because I had misspelled the name. I used `.system_libs[pocofoundation]` instead of `.system_libs[PocoFoundation]`. Now it works! Thanks for your response. It helped me narrow down the problem.
