### ISSUE TITLE
Downloaded files corrupted when installing package

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#12082]
conan 1.51.3
OS: Ubuntu 20.04 wsl

I am seeing strange behaviour which I cannot explain.
I have a packgae which essentially downloads a tar.gz file containing a toolchain from artifactory.
Installing the package is successful, and all file permissions in the unzipped toolchain folder looks good.

Then, if I force conan to install the package again suddenly file permissions have changed in the unzipped toolchain in the build folder and I get `ERROR: [Errno 13] Permission denied: '.../.conan/data/my_package/0.0.1/_/_/build/4db1be536558d833e52e862fd84d64d75c2b3656/x86_64-linux-gnu/include`

Permissions before installing for the second time:
```
dr-xr-xr-x 2 khj khj 4.0K Dec 27  2021 include
```
permissions after conan have tried to remove the folder (I presume):
```
d-w------- 2 khj khj 4.0K Dec 27  2021 include
```

The strange thing is that this happens before the recipe is invoked for the second time, so I expect that this is not related to the recipe itself. The very odd thing is that it only happens to this specific folder....which, by the way, is completely empty.

Does someone have a clue as to what could be wrong here?

Rgds
Klaus

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Could you please check if you have something like ``https://docs.conan.io/en/latest/reference/env_vars.html#conan-read-only-cache`` CONAN_READ_ONLY_CACHE defined?

Also, what command are your using to unzip? It would be great if there were something that we could reproduce. Thanks!

**Comment by klausholstjacobsen** [comment]
read-only cache not defined in environment or in conan.conf

The recipe looks looks like this:
```
    def source(self):
        url = "https://artifactory.hidden/conan/x86_64-linux-gnu.tar.gz"
        tools.get(url)

    def package(self):
        self.copy("*", symlinks=True)
```

**Comment by memsharded** [comment]
It seems it is related to the specific contents of that .tgz, for some reason Conan tries to remove the folder, it fails, it tries to set the permissions to remove it, it still fails, and then it is left with the changed permissions.

Without fully knowing yet what is happening, I think I would try this:

- Add ``no_copy_source = True`` attribute to the recipe. That will save one huge copy from source -> build folder
- Use the new ``copy(self, ...)`` instead of ``self.copy()`` (deprecated in 2.0), to explicitly copy from source folder
- Alternatively you could also do the download in the ``build()`` method and "build" folder directly.

In both cases it will be much faster, saving 1 copy, and the permissions and folder removal might also improve

**Comment by klausholstjacobsen** [comment]
Yes, it was directory permissions without write permissions that caused the error.

Thanks for the additional advise on copying files!
