### ISSUE TITLE
conan upload is very slow if you export many small files

### ISSUE THREAD

**Issue by TyRoXx** [conan-io/conan#121]
``conan upload`` takes several minutes for my library https://github.com/TyRoXx/silicium. It is a smallish, header-only library, so I simply try to export the headers like this to avoid the dependency on Github:
```Python
class SiliciumConan(ConanFile):
    name = "silicium"
    version = "0.2"
    generators = "cmake"
    requires = "Boost/1.59.0@lasote/stable", "sqlite3/3.10.2@TyRoXx/stable"
    url="http://github.com/tyroxx/silicium"
    license="MIT"
    exports="silicium/*"
```
The upload succeeds after a few minutes. Conan uploads approximately one or two files per second. Most files are a few KiB each. This could be much faster even on my slow Internet connection.

I understand that ``exports`` was designed for helper files like a ``CMakeLists.txt``, not whole directories of source code. I still think that this is a valid use case that should not be more inconvenient than necessary.

**Comment by memsharded** [comment]
Yes, this issue should already be fixed in: https://github.com/conan-io/conan/pull/95
This is inteded for 0.7 release, scheduled for next Monday. You might want to try to run from source (develop branch) if it is urgent, otherwise, I'd like if you could report back after 0.7 release and close this issue if everything ok. Thanks very much for reporting!

**Comment by memsharded** [comment]
Hi @TyRoXx , release 0.7 is out, including this issue, I have tested it myself and seems everything ok, but it would be great if you want to check it too, and update the issue accordingly, thanks!

**Comment by TyRoXx** [comment]
Thank you. Uploading and downloading are much quicker now.
