### ISSUE TITLE
System requirements is executed more than once

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1210]
Hi, guys! Happy holiday!  
I bring a gift, but is not chocolate eggs, it's maybe a bug. Okay, no more jokes.  

I have a little package called **foo** that produces a dummy library. In the recipe, I invoke `system_requirements` to install *htop* (a flavor of top command). So far, so good, this package is working well.  
So, I have a second package, called **bar**. This project requires **foo**, and produces a new dummy library (just for this context).  
And finally, I have **foobar**, just a executable that print some dummy message. Anyway, **foobar** requires **bar**. When I build **foobar**, the `system_requirements` from **foo** is invoked again.  

Invoke `system_requirements` again, from another package, is it a expected behavior?

To clarify better this scenario, I created a small project: https://gitlab.com/uilianries/conan-system-requirements.  
And, the steps were reproduced here: https://gitlab.com/uilianries/conan-system-requirements/builds/14431043

Regards!

**Comment by lasote** [comment]
Hi! Happy holiday to you too!

If the package is already installed and in your local cache the system requirements should not be called twice but looking at your execution traces here `https://gitlab.com/uilianries/conan-system-requirements/builds/14431043` It looks like the package `foo` is being downloaded from conan.io:

```
foo/0.1.0@uilianries/testing: Not found, looking in remotes...
foo/0.1.0@uilianries/testing: Trying with 'conan.io'...
Downloading conanmanifest.txt

Downloading conanfile.py

```

In that case yes, the system requirements will be called, because you don't know if the computer where it's being installed have those system requirements.

Please, tell me if I'm wrong

**Comment by uilianries** [comment]
Yes, you are correctly, and make sense for me.

Okay, was a false alarm :v:
