### ISSUE TITLE
[bug] Conan 2.0 beta 3 will not perform export_sources on uncommitted changes

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan#12137]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Monterey 12.3
  * Compiler+version: apple-clang 13.1
  * Conan version: 2.0.0-beta3
  * Python version: Python 3.10.7

### Steps to reproduce (Include if Applicable)
1. `pip3 install conan==2.0.0b3`
1. `git clone https://github.com/ssrobins/conan-recipes.git`
1. `cd conan-recipes/recipes/box2d`
1. In the CMakeLists.txt in this folder, add `message(FATAL_ERROR "Error")`
1. Run `./conan.py macos`.  I would expect that CMake generation fails and prints "Error" to the screen, but instead, the build completes.
1. Locally commit the change to git
1. Re-run the conan create command. Now the generation fails and shows the "Error" output, as expected.

Error also occurs when using the `export_sources()` method instead of the `export_sources` attribute:
```
 def export_sources(self):
        copy(self, "CMakeLists.txt", self.recipe_folder, self.export_sources_folder)
```

If you run `pip3 install conan==2.0.0b2` and redo the steps above, the build always fails with "Error" output, as expected.

**Comment by memsharded** [comment]
Hi @ssrobins 

I am not sure what is failing, I am following the steps, except that I just call ``conan create .`` instead your script, and I get:
```
CMake Error at CMakeLists.txt:16 (message):
  Error


-- Configuring incomplete, errors occurred!
See also "C:/Users/memsharded/.conan2/p/tmp/c7f4ea5e77d5d92f/b/build/CMakeFiles/CMakeOutput.log".
box2d/2.3.1: ERROR:
Package '4f267380690f99b3ef385199826c268f63147457' build failed
box2d/2.3.1: WARN: Build folder C:\Users\memsharded\.conan2\p\tmp\c7f4ea5e77d5d92f\b\build
ERROR: box2d/2.3.1: Error in build() method, line 51
        cmake.configure()
        ConanException: Error 1 while executing
```

I am running the branch "main" of the repo.

**Comment by memsharded** [comment]
I have managed to reproduce.
The issue is that you are defining ``revision_mode = "scm"``. It seems then this behavior is expected.
As you are defining ``scm`` as the revision mode, and Conan 2.0 is working with the hypothesis of immutability (https://github.com/conan-io/tribe/pull/16), it is not updating the contents of the exported files, because same revision == same contents.

**Comment by ssrobins** [comment]
Given that https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#the-scm-attribute stated that the scm attribute won't exist in Conan 2.0, maybe it should have been a Conan error that I had it?

Anyway, thanks for the explanation. Since this isn't a bug, I'm closing this.

**Comment by memsharded** [comment]
> Given that https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#the-scm-attribute stated that the scm attribute won't exist in Conan 2.0, maybe it should have been a Conan error that I had it?

It is different. The ``scm`` attribute that is defining is the attribute (the ``scm = {"url": ..., "type": ...}``), not the value to ``revision_mode = "scm"``. The later is remaining in 2.0, but will be subject to the immutability principle, it is only valid for new commits, otherwise exported files will not be updated.
