### ISSUE TITLE
[bug] conan user --password "-..." can't begin with "-"

### ISSUE THREAD

**Issue by jusito** [conan-io/conan#12162]
Temporary passwords generated in the CI beginning with "-" cannot be used directly.

Workaround from #2502 :
```
CONAN_PASSWORD="-my_ci_pw" conan user -r conancenter "user" -p
```

I would expect that:
- This is fixed, or:
- Documentation would note about this, e.g. `conan user --help` would note this behavior and points to an alternative way

### Environment Details
  * Operating System+version: Linux version 5.4.0-1075-kvm (buildd@lcy02-amd64-082) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1))
  * Compiler+version: clang 14.0.6
  * Conan version: 1.52.0
  * Python version: 3.8.10

### Steps to reproduce
`conan user --remote conancenter --password "-my_ci_pw" user`

### Logs
```
ubuntu@gitlabrunner:~$ conan user --remote conancenter --password "-my_ci_pw" user
usage: conan user [-h] [-c] [-p [PASSWORD]] [-r REMOTE] [-j JSON] [-s] [name]
conan user: error: unrecognized arguments: -my_ci_pw
ERROR: Exiting with code: 2
```

**Comment by memsharded** [comment]
This is unfortunately out of our control, as this is standard CLI parsing, in this case, implemented by Python argparse, so nothing that we can fix.

There are ways to escape the ``-`` in different terminals like bash. I am not sure where can be this documented, because it happens also for other places in the CLI, not just this command.

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you in a while - if anyone has any other question or request, please feel free to create a new issue, we're always happy to help! :)
