### ISSUE TITLE
List binaries in package_info

### ISSUE THREAD

**Issue by Floofy-KH** [conan-io/conan#1218]
I'm looking into integrating Conan into out current build system, which uses CMake. Something I've been wanting to do, but haven't yet found any way to do, is to import a package's binaries for shared libraries (mostly .dlls on Windows) into the consumer project. The ways I've seen to do that is to use _imports_ in the consuming project. But to me, this feels wrong, as the package should first specify what binaries are available to import, which I haven't found any way to do.

The kind of functionality I was thinking of was to add to the package_info method in each package's conanfile.py so I could write something along the lines of
```
def package_info(self):
        self.cpp_info.debug.binaries = ["foo_d.dll"]
        self.cpp_info.release.binaries = ["foo.dll"]
```

Which would populate the generated conanbuildinfo file (.cmake in my case) for the consuming project, which will then use those specified binaries to import however to wherever it wishes. Ideally it would populate by package, by configuration, and the entire collection of binaries across all imported packages.

Does any functionality like this exist and I've missed it? And if not, any thoughts on it being implemented?

**Comment by memsharded** [comment]
The thing with importing is that it is not a decision by the package creator, but by the package consumer. Typically DLLs can be consumed directly in the package folder (from the local cache), without copying the DLLs to the user space via ``imports``. This can be done by defining ``self.env_info.PATH`` for example, and using a virtualenv generator or a RunEnvironment, depending on the consumer flow.

So, why would it be necessary that each package in a dependency graph has to define which DLLs it has inside? It is typical to have a few tenths of packages, so that would mean to have to declare DLLs in several tenths of recipes. Then, if a bug is made (imagine you misspelled foo => fou), fix it in tenths of recipes. In contrast, bugs in the consumer imports are just fixed in the consumer. In many cases it is not necessary to translate this information to the build system, as it is mostly a run-time thing, not a build-time thing, so it works for all build systems without extra code. And with a single ``imports`` you can retrieve artifacts from any number of packages. And it already works to imports to any desired user destination. It scales much better.

It is also the consumer choice, if they want to ``imports`` also the static libs into their project, they can do it. Or maybe they want to import an executable. Maybe they want to create a bundle to redistribute or whatever other reason. If ``imports`` wouldn't work that way, and packages had to declare such artifacts available for "importing", that will unintentionally block easy consuming.

A totally different use case, that we consider from time to time, is adding a ``deploy()`` method to recipes, that would allow recipes to specify post-install actions, that could be for example, to copy the DLLs to C:/Windows/system32, or any other location in the path. However this feature is controversial and has many potential edges, so still not in the roadmap.

I suggest trying to focus on the problem to solve: are you having trouble to run your applications? Maybe try the PATH and environments solutions. They work pretty well, and have much better composability (they can be made transitive in dependency graphs, and have package reuse them easily). Are you having troubles redistributing your app, and you need to gather your dependencies DLLs? Which is exactly the problem? You can do it right now and redistribute DLLs for packages like Boost, Poco and many others that didn't have to care to declare such list of availables DLLs.

**Comment by Floofy-KH** [comment]
You make good points. I'll try and explain what it is I would like to solve. We're developing an application with some dependencies, and would like to use Conan to manage these dependencies. We will write the packages ourselves so that they can be built,stored and used in a way that suits us. While adding to the PATH is a good solution, it is not appropriate for us, as we wish to package our product as a standalone application, with all necessary 3rd party libraries along with it. And that part is the reason why allowing packages to list binaries would be beneficial in this case. 

We do currently already specify and copy over DLLs for our application in our build scripts, but ideally I'd like the names of the binaries that a package has to be made available to the consuming application, as then the application's build system and the package can be decoupled more. The only things that the application would depend on are the CMake variables (in my case) that the package generates. Then if a package is updated which causes a change to the outputted file names, no maintenance is required in the application. 

In the end, it is the consumers choice whether they wish to import these binaries, just as it is its choice whether to import static libraries. I agree that a `deploy` method would not be very appropriate, as a package shouldn't necessarily be able to install itself wherever it likes. It should be up to the consumer. But as a consumer as well, I would like the option to be able to list the binaries each package has so that I can import them as I wish. 

As I said, we do currently already copy DLLs manually by specifying their names in our build scripts, so we can continue on this path with Conan, but it doesn't seem like the cleanest solution to me as it's the package that determines what the DLLs and any other binaries, libraries or resources are called, not the consuming application.

**Comment by memsharded** [comment]
Ok, got the use case.

Then, I think the feature request you are interested in would be https://github.com/conan-io/conan/issues/1100

This would allow declaring arbitrary variables, like a list of files, that would be later translated to the conanbuildinfo, that would cover 100% your use case. The feature request is being evaluated for next release, go an upvote it :), and conversation can continue there (current issue is redundant and can be closed). Thanks!
