### ISSUE TITLE
[question] How to propagate compiler.version to CMake?

### ISSUE THREAD

**Issue by Ahajha** [conan-io/conan#12202]
OS: Ubuntu 22.04
Conan: 1.52
CMake: 3.22.1

Hello, I'm trying to override compiler.version to test different versions of GCC (10, 11, and 12 for my case), and it doesn't seem to be propagated to CMake no matter what I do. Is there something I'm doing wrong here? I have the following small example:

main.cpp:
```c++
// Print the compiler version
#if __GNUC__ == 10
#error 10
#elif __GNUC__ == 11
#error 11
#elif __GNUC__ == 12
#error 12
#endif
```
CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.15)
project(change-compiler)

add_executable(main main.cpp)
```
conanfile.py:
```python
from conan import ConanFile
from conan.tools.cmake import CMake

class ChangeCompilerConan(ConanFile):
    name = 'change-compiler'
    settings = 'os', 'compiler', 'build_type', 'arch'
    generators = "CMakeDeps", "CMakeToolchain"

    exports_sources = [
        "CMakeLists.txt",
        "main.cpp",
    ]

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```
My system default is GCC 10, and I can't seem to get it to use anything else. I've tried the following, none work:
```
conan create . 0.1.0@test/test -s compiler.version=11
conan create . 0.1.0@test/test -s compiler.version=12
conan create . 0.1.0@test/test -s:b compiler.version=12
conan create . 0.1.0@test/test -s:h compiler.version=12
conan create . 0.1.0@test/test -s:h compiler.version=12 -s:b compiler.version=12
conan create . 0.1.0@test/test -pr default -s:h compiler.version=12 -s:b compiler.version=12
```
Is there something I'm missing here? Do I need to specify `CMAKE_CXX_COMPILER` and `CMAKE_C_COMPILER` myself?

Thanks in advance!

(BTW - it was great seeing some of you at CppCon!)

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by fschoenm** [comment]
See also #11842.

**Comment by memsharded** [comment]
Hi @Ahajha 

The definition of ``compiler.version`` in the ``settings`` profile, it is a declaration to Conan of what is the compiler version being used, but not an instruction for Conan to setup the environment or the compiler. Conan does not automatically set up any tool or environment based on the inputs. So there are different ways to define your environment, depending on the platform:

- If you make the compiler version the main default one with some system-wide ``alternatives`` or symlinking or whatever other strategy
- Defining CC/CXX env-vars is good in most Linux and OSX systems (not in Windows CMake Visual genenerators). This is typically better than trying to define the CMake specific ``CMAKE_CXX_COMPILER`` one, because that is specific for CMake, if you have dependencies that use Autotools, it won't work.

**Comment by memsharded** [comment]
(As @fschoenm suggested, there are some ongoing ideas about adding a higher level Conan abstraction over it, but at the moment some of the existing CMake ones)

**Comment by jcar87** [comment]
Hi @Ahajha  - if this is for the `conan create` workflow, you could try the following:

1. Define multiple named profiles (e.g.  `gcc11`, `gcc12`), where the `CC` and `CXX` variables are defined in the `[buildenv]` section, pointing to the location of the compiler executables for that version. More information on `buildenv` can be found [here](https://docs.conan.io/en/latest/reference/profiles.html#buildenv).

The contents would be like this:
```
[settings]
compiler=gcc
compiler.version=11
...
[buildenv]
CC=/usr/bin/gcc-11
CXX=/usr/bin/g++-11
```

(and the same for gcc-12)

2. In the recipe itself, add the `VirtualBuildEnv` as a generator, e.g.
```
generators = "CMakeDeps", "CMakeToolchain", "VirtualBuildEnv"
```

3. When invoking `conan create`, specify the profile for each compiler version, e.g.
```
conan create . 0.1.0@test/test -pr:h gcc11
conan create . 0.1.0@test/test -pr:h gcc12
```

Provided that the executables can be found in the locations that were defined in the profiles, you should now see during the `conan create` command that CMake finds the specific version of the compiler.


While some users indeed expect Conan to "do this for you", the reality is that Conan does not have enough information to  locate a specific versioned compiler. There is no universal convention on having multiple versions of the same compiler installed on the system. Ubuntu/Debian would typically have `g++-XX` where `XX` is the major version, but other distros do not follow this convention (and certainly not other OSs like macOS or Windows).

What some users are requesting recently, is the ability for Conan to somehow set the compiler in the generated CMakeTooclahin, even if that requires the user to specify this in the profile as a `conf` as a conf value. This would allow the following:
```
conan install .
cmake . -DCMAKE_TOOLCHAIN_FILE=...
```

Currently users would have to explicitly do `source conanbuild.sh` in order to set the environment with the compiler specified from the profile. This is what we are currently looking into in other reported issues.

PS: it was great seeing you at CppCon too :)

**Comment by Ahajha** [comment]
Thanks everyone for the responses!

So my understanding is those settings in the profile are more de-scriptive rather than pre-scriptive.

@jcar87 It looks like your suggestion would require an update to every recipe, correct? Would it be possible to just make a single virtual environment with proper CC/CXX variables, and run `conan create` in there?

I'll play around with this and see what I can do, it's not gamebreaking for me but I was just wondering why it didn't work, and that has sufficiently been answered.

**Comment by jcar87** [comment]
> Thanks everyone for the responses!

> @jcar87 It looks like your suggestion would require an update to every recipe, correct? Would it be possible to just make a single virtual environment with proper CC/CXX variables, and run `conan create` in there?

There's an alternative that doesn't require to modify the recipes. You can add the following to the `[conf]` section in the profiles:
```
tools.env.virtualenv:auto_use=True
```

And this would use it automatically without having to explicitly list it as a generator in the recipes.

Otherwise, I think if the shell environment in which you invoke `conan create` has CC/CXX defined, and there is nothing anywhere that causes Conan to override those values, those should be respected by the time `conan` invokes `cmake`.
