### ISSUE TITLE
[question] Add file to Conan download cache manually

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#12208]
We are heavily using the Conan download cache to save traffic from Artifactory towards our CI/CD machines.

In order to fill the cache with packages a package need to be uploaded first and then downloaded again to "prefill" the cache for subsequent CI/CD jobs. This means at least once uploading and downloading the package.

Is there a way to manually upload the files into the cache to save that one download?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @MTomBosch 

> Is there a way to manually upload the files into the cache to save that one download?

No, there is no way, and we think it wouldn't be a good thing that there is no way. At the moment the ``FileDownloadCache`` is very well defined and even quite concurrent safe, because it is clearly a one-directional cache, from the server to the package cache. The moment you enable the opposite flow, keeping the consistency of the cache, synchronizing things becomes way more complicated, and can lead to very confusing issues, like thinking that you have packages already in the server, then losing information because they were not uploaded, but everything looked good in the CI build machine, because everything worked locally.

**Comment by MTomBosch** [comment]
Thanks for the fast response. I know that it would be hard to offer this capability as well in a safe way but I though asking does not cost a lot and then I know for sure if it is there or not.

Thx once again. 

I will close this question then.
