### ISSUE TITLE
[question] Replace alias versions in conanfile.py during export?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#12207]
Hi,

is there an existing infrastructure in Conan which could replace alias versions ina conanfile.py's build_requires/python_requires/requires clauses and could replace the alias version to the exact version to which the alias points to?
E.g. if I have a foo/1.0.0@user/master version, but that is actually an alias for foo/1.0.0+1234+deadbeef@user/master, is there a way
to "auto-replace" "foo/1.0.0@user/master" with  "foo/1.0.0+1234+deadbeef@user/master" during conan export (so that a resolved alias is installed into the cache)?
Thanks,

**Comment by memsharded** [comment]
Hi  @harsszegi 

> to "auto-replace" "foo/1.0.0@user/master" with "foo/1.0.0+1234+deadbeef@user/master" during conan export (so that a resolved alias is installed into the cache)?

Sorry, I don't know what you mean, I would need some further explanations.

In any case, it sounds that this could be some abuse. The ``alias`` feature should be used sparingly for some very especial and exceptional use cases. If you need to add some kind of automation on top of that it doesn't look like great (without fully understanding the issue yet)

**Comment by harsszegi** [comment]
We release packages with a "rolling version" (these are usually build helper packages and the python_requires base class for all of our recipes we maintain). So to "ease the pain" and not enforcing every package using these "build helper packages" to update the build-package-version in the consuming package's build_requires every time we release a new build-helper-package, but we simply "adjust" the alias version pointing now to the new version of the build-helper-package.

E.g.

build-helper-package is released as "build-helper-package/1.0.0+1234+deadbeef@user/master"

we create an alias "build-helper-package/1.0.0@user/master" pointing to "build-helper-package/1.0.0+1234+deadbeef@user/master".

Package "foo" has in its conanfile.py build_requires = "build-helper-package/1.0.0@user/master"

We release a new version of build-helper-package, which is still 1.0.0 compatible, e.g:
"build-helper-package/1.0.0+5678+deadcafe@user/master"

As this being still 1.0.0 compatible, we update the alias, so that now "build-helper-package/1.0.0@user/master" points to "build-helper-package/1.0.0+5678+deadcafe@user/master"

So if "foo" is recompiled now it automatically picks up the bugfixes from "build-helper-package" without modifying "foo"'s conanfile.py.

Obviously there is still the way for the "slow track" users to lock them to an explicit version of "build-package-helper".

With the "rolling version" there is an issue. The information to which the alias is pointing to, e.g. what was the exact
build-helper-package used at the time when foo was built, is completely lost.

So this is what I'm after whether we can "resolve" the alias in the conanfile.py and replace it during export (similar to the scm's "auto" attributes).

Thanks,

**Comment by memsharded** [comment]
Quick question, why using alias and not version-ranges, which is more of an industry standard?

You want packages using that helper to do:
```python
python_requires = "build-helper/[>=1.0.0 <2.0.0]@user/master"
```

Then, when new versions of the build-helper are released, they will be automatically picked, no need to do anything. And there are few advantages:
- Consumers that want to do that, they can still explicitly pin the exact version that they want
- The ``python_requires`` package_id logic still allows you to define what happens with the consumers, if they need to rebuild because of the changes or not. If you bump the patch version of the ``build-helper``, consumers will not require to rebuild, but if you bump the minor, then they will need to rebuild.
- If you want to use pre-releases beyond the ``1.0.0``, still possible, just need to use ``1.0.0-1234`` and ``include_prerelease=True`` in the version range.

**Comment by harsszegi** [comment]
Well our version format seems to be not really semver compliant afaik, e.g. we indeed have this format:

package_name/semver+gitcount-githash@user/channel

which is afaik not 100% semver compliant, so we can't use ranges.
Anyhow thanks for the info @memsharded , closing the issue for now

**Comment by memsharded** [comment]
Thanks for the feedback.

In any case, to the original question:

> to "auto-replace" "foo/1.0.0@user/master" with "foo/1.0.0+1234+deadbeef@user/master" during conan export (so that a resolved alias is installed into the cache)?

No, it is not possible. We had some functionality in the past that edited ``conanfile.py`` (the ``scm`` feature), and it was a total nightmare, tons of corner cases. So Conan will no longer do that in 2.0, and it will never edit ``conanfile.py``. Furthermore, the ``export`` command does not evaluate the graph at all, so it would be impossible to do such replacement, because it doesn't have the information. To have that information you would need the whole inputs, the profiles, etc, to be able to evaluate the graph, and that would make the ``export`` conditioned to the configuration, which is a design flaw, because it should be independent. Put in other words, you could have a conditional requirements in your ``requirements()`` method, using an alias. But that alias will only be resolved if it is evaluated in that specific branch of the configuration, so all potential configurations should be evaluated in order to be able to guarantee such replacement.
