### ISSUE TITLE
[question] Conan integration with custom architectures

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#12217]
We use "custom architectures" which are actually aliases to real archs. For example, when we build for the `NVIDIA Jeston Nano` we set the `arch` in the conan profile to `nano`. To do this we need to tweak the `settings.yml` file to include all our our custom archs.
We do this since our build system differentiates all the platforms we target using `CMAKE_SYSTEM_PROCESSOR`, which following the previous example, gets set to `nano` when we target that platform. This may not be the best way of doing it, but it is the way it is done, so we adapted conan to our needs. 

This has worked fine for us for over two years, with only some small changes required to the autotools based recipes to pass a `host=actualTriplet` to the configure method of `AutoToolsBuildEnvironment` object.

```py
    @property
    def _host(self):
        """Get host from conan profile. If None conan will try to detect it automatically"""
        return os.environ.get("CHOST")

.....

    self._autotools.configure(args=args, host=self._host)
```
Where `CHOST` is set on the host profile. 

Recently I tried to build a new Conan 2.x-compatible recipe and realized this is no longer possible since the `AutotoolsToolchain` errors out because it doesn't know how to generate the triplet. Again following the `nano` example, we get:
```
	tc = AutotoolsToolchain(self)
	ConanException: Unknown 'nano' machine, Conan doesn't know how to translate it to the GNU triplet, please report at  https://github.com/conan-io/conan/issues
```

I'm wondering if you have any recommendations on how to move forward with this. Would it be possible to make `AutotoolsToolchain` honor the `CHOST` env variable? I'm not really sure if that variable is widely adopted as standard. But any method of specifying the triplet instead of relying on conan to figure it out would work for us. I'd love to see something that can be specified on the profiles so I don't have to keep tweaking the autotools-based recipes to include the snippet above.

Thanks in advance.

**Comment by ericriff** [comment]
BTW I just tried build `glog` which is also conan 2.0-compatible, but uses cmake to build. That worked fine for us. So this only applies to the autotools-based recipes.

**Comment by jcar87** [comment]
Hi @ericriff  - thanks for reporting this issue. If I'm not mistaken, if one were to run CMake on the Jetson Nano, the `CMAKE_SYSTEM_PROCESSOR` automatically detected by CMake would be `aarch64`.  This architecture in Conan settings is `armv8`.

If I understand correctly, you need it in such a way that when (cross)building CMake projects, the value of `CMAKE_SYSTEM_PROCESSOR` is `nano` instead of `aarch64` to follow your own conventions.

> I'm wondering if you have any recommendations on how to move forward with this. Would it be possible to make AutotoolsToolchain honor the CHOST env variable? I'm not really sure if that variable is widely adopted as standard. 

Perhaps I would propose doing it the other way around: rely on the configuration features of `CMakeToolchain` to set a custom value to `CMAKE_SYSTEM_PROCESSOR`, but leave the Conan `arch` setting as `armv8`, for example, in the host profile:

```
[settings]
os=Linux
arch=armv8

[conf]
tools.cmake.cmaketoolchain:system_processor="nano"
```

This would result in the generated CMake toolchain file to set the `CMAKE_SYSTEM_PROCESSOR` variable to `nano` - while leaving other integrations the same. The `arch` setting being `armv8` means that the `AutotoolsToolchain` would be able to derive correct `--host` and `--build`.


As for the ability for the `AutotoolsToolchain` to be able to use custom `host` / `build` (e.g. like CHOST) - I will leave a note for us to look into this, as it is true that custom arch values are not covered, and some platforms have their own _specific_/custom triplet values which Conan would not know about, so we need to expose a way for the users to configure this.

**Comment by ericriff** [comment]
Maybe I mislead you with my comments about `CMAKE_SYSTEM_PROCESSOR`, I just mentioned that to explain you guys that internally on our repos we use aliases for the archs, and that's why we use those aliases on conan as well. CMake-based recipes work just fine for us. The issue is with the autotools-based recipes, particularly around the conan 2.0 generators, where we can't specify a custom triplet like we can with the conan 1.x generators.

What I'd need is a way of specifying a custom triplet on `AutotoolsToolchain()`, like we can do with the older 
 `AutoToolsBuildEnvironment` which take a `host` argument.
As I mention I'd like to be able to set that from the profile so we don't have to modify the recipes. Based on you example above, something along the lines of
```
[settings]
os=Linux
arch=nano

[conf]
tools.autotools.autotoolstoolchain:triplet="my-custom-triplet"
```
But if that's too much to ask, a backport of the host argument that I'd have to specify on the recipes would also work. But having to modify all autoconf-based recipes has been a burden for me for years and I'd like to avoid it if possible.

**Comment by ericriff** [comment]
I'm still stuck on this. I'm wondering if you guys will be backporting the `host` argument to the new autotools generators or if I should try to come up with some hack on my own.
