### ISSUE TITLE
[bug] TemplateAssertionError: no test named 'boolean'

### ISSUE THREAD

**Issue by xakod** [conan-io/conan#12226]
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux Ubuntu 20.04
  * Compiler+version: GCC 9.3.0
  * Conan version: conan 1.52.0
  * Python version: Python 3.8.2

### Steps to reproduce (Include if Applicable)

Full steps is available here https://github.com/conan-io/conan-center-index/issues/13249

**Comment by memsharded** [comment]
You can read in your log:
```
ERROR: conan 1.52.0 has requirement Jinja2<4.0.0,>=3.0; python_version >= "3", but you'll have jinja2 2.10.1 which is incompatible.
```
So it seems an error in your setup, and your dependency on an older jinja2.

**Comment by wdobbe** [comment]
I got the same error when conan 1.57.0 tries to install package double-conversion/3.2.1 from CCI.
My Linux distribution contained indeed jinja2 2.10.1. After installing jinja2 3.0.3 the problem was solved. 
But I didn't see the above error anywhere in the Conan output. If not for this bug report I would probably never have found the cause. 
@memsharded can you please let me know where I should be able to see the error message regarding the outdated Jinja2 version ?
