### ISSUE TITLE
[bug] (Linux) Package with two shared components fails to link both at same time

### ISSUE THREAD

**Issue by Ahajha** [conan-io/conan#12221]
First off, I'm not 100% certain if this is a bug, it very well could be a misunderstanding of how shared libraries work, please correct me if any of my assumptions are incorrect, however, this seems like a bug to me.

I have a single package with two components, pkg1 and pkg2, both shared, and pkg2 depends on pkg1. In my test package, I test two executables, one linking against pkg1, and one linking against pkg2 (and pkg1, implicitly). In the second executable, it fails to find the shared library for the first package.

### Environment Details (include every applicable attribute)
Ubuntu 22.04
Python 3.10
Conan 1.52 (seems to have the same behavior since 1.46)
GCC 11 (10 has the same behavior)

### Steps to reproduce (Include if Applicable)

I have a repo [here](https://github.com/Ahajha/double-shared-library-conan) showing a minimum reproducible example.

From there, run `conan create . 0.0.1@test/test`

Thanks in advance!

**Comment by Ahajha** [comment]
Some extra info, I ran verbose output for a normal build (I included a main file that links against both), and for the test package, and they have similar link scripts:

main:
```
/usr/bin/c++ -g  CMakeFiles/test.dir/main.cpp.o -o test  -Wl,-rpath,/home/alex/Documents/double-share/build  liblib2.so  liblib1.so
```
(shortened, not accurate but cleans up the output)
```
/usr/bin/c++ -g  main.cpp.o -o test -Wl,-rpath,double-share/build liblib2.so liblib1.so
```
test package:
```
/usr/bin/c++ -m64 -O3 -DNDEBUG -m64 CMakeFiles/test_pkg2.dir/test_pkg2.cpp.o -o bin/test_pkg2  -Wl,-rpath,/home/alex/.conan/data/double-share/0.0.1/test/test/package/062863c92a5a0a247840166e9f84ebe8d10786b9/lib /home/alex/.conan/data/double-share/0.0.1/test/test/package/062863c92a5a0a247840166e9f84ebe8d10786b9/lib/liblib2.so /home/alex/.conan/data/double-share/0.0.1/test/test/package/062863c92a5a0a247840166e9f84ebe8d10786b9/lib/liblib1.so
```
(shortened, not accurate but cleans up the output)
```
/usr/bin/c++ -m64 -O3 -DNDEBUG -m64 test_pkg2.cpp.o -o bin/test_pkg2  -Wl,-rpath,<conan-lib-path> <conan-lib-path>/liblib2.so <conan-lib-path>/liblib1.so
```

**Comment by memsharded** [comment]
Hi @Ahajha 

It is not clear if it fails at link time or at runtime.
For runtime, you might need to add the ``VirtualRunEnv`` generator in your ``test_package/conanfile.py`` (or enable the conf ``tools.env.virtualenv:auto_use=True`` to emulate the 2.0 behavior in which this generator will be implicit).

**Comment by Ahajha** [comment]
Out of curiosity, I tested this with conan 2.0-beta3 and the same behavior occurs.

**Comment by jcar87** [comment]
Hi @Ahajha  - thanks for reporting this one!

I think this is failing during the `test()` stage in the `test_package`, rather than the linker.

The "static" ("build time") linker would have failed with an error like this due to an indirect dependency:
```
/usr/bin/ld: warning: liblib1.so, needed by liblib2.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../libbar/liblib2.so: undefined reference to `foo'
```

What is failing from your example, from what I can see, is the dynamic/runtime linker, with an error that looks like this:
```
bin/test_pkg2: error while loading shared libraries: liblib1.so: cannot open shared object file: No such file or directory
```

And this is happening during the test run (so, after CMake has already correctly linked the test executables).

The reason this is failing (and also the reason why it doesn't fail on macOS), is a combination of factors.
* we are running the executable `test_pkg2` directly from the build directory - for the build tree, CMake places hardcoded RPATHs - in this case, that executable has the following `DT_RUNPATH` entry in its ELF header:
```
 0x000000000000001d (RUNPATH)            Library runpath: [/root/.conan/data/double-share/0.0.1/test/test/package/4a203d0229ccf4bbdf5647e9672f724eb122d443/lib]
```
* The executable only directly depends on `liblib2.so`, so that's the only dependency recorded in its `ELF` header
* The runtime linker finds `liblib2.so` in the directory specified by the `RUNPATH`, and then it sees that it needs `liblib1.so` - it doesn't know where to find it, and it fails. The reason it's a bit convoluted, by `RUNPATH` only applies to direct dependencies so the runtime linker will *not* look for indirect dependencies (like `liblib2.so`) in the `RUNPATH` directories.  The search logic for the runtime linker is documented in `man ld.so`.


You can fix this in a number of ways, take your pick :) Each of the following is an alternative:

* In the `CMakeLists.txt` of the **test package**, you can add `add_link_options("-Wl,--disable-new-dtags")` somewhere near the top (before `add_executable()` - this will cause CMake to tell the linker to encode `DT_RPATH` instead of `DT_RUNPATH` - the behaviour is different, as explained in `man ld.so`, it means that the runtime linker _will_ look for indirect dependencies in the rpath of the main executable. This is pretty much how it works on macOS and how Linux used to work. Distros started defaulting to the new tag (RUNPATH instead of RPATH) around 2018. Note that this will only work if the libraries _don't_ have a `RUNPATH` entry themselves.

* In the `CMakeLists.txt` of the actual library, you can add `set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib")` near the top (before `add_library()`) - this will tell CMake to add a `DT_RUNPATH` entry to both libraries, that basically says: "relative to the directory from which this file was loaded" - so when the runtime linker finds `liblib2.so`, it will read its `RUNPATH` entry and look for `liblib1.so` in there, "relative to it", and it will work. This works fine for most libraries that have dependencies within the same Conan package, but might cause issue for libraries where the dependencies are provided by a different Conan package (and thus, a different folder).

* Let conan define `LD_LIBRARY_PATH` for you when running the test. This environment variable is yet another way to tell the runtime linker where to locate libraries. In your case, what's missing is the `VirtualRunEnv` generator in the generators list in the `conanfile.py` for the `test_package`, as well as `env="conanrun"` in the `self.run()` calls. With these two things, conan will create a `conanrun.sh` script (and other helper files), that it will "source" on the shell subprocess during `self.run()`, to expose an `LD_LIBRARY_PATH` env var with the list of library directories from the recipe.


We recommend the last option, and it is likely to work across most scenarios, in particular if Conan is the one launching the executables. Your mileage may vary if you are invoking the executables yourself, but we do recommend sourcing `conanrun.sh` in these cases.

**Comment by Ahajha** [comment]
I think now that VirtualRunEnv is fairly common (and also I understand it now :) ), this isn't really an issue anymore.
