### ISSUE TITLE
[question] Usage of `conan_toolchain.cmake` and `CMakePresets.json` generated by CMakeToolchain.

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#12248]
There are some conclusions that I want to confirm about CMakeToolchain generator:

1.  It is **NOT** necessary that we have to use the `CMakePreset.json` genereated by CMakeToolchain.
2.  All we need to do is to include `conan_toolchain.cmake` **BEFORE** the invocation of the first `project()` command in the root `CMakeLists.txt` file.
3.  Using the generated `CMakePresets.json` file is just a **METHOD** that can help us to do the **2nd** point.

Am I correct?

**Comment by memsharded** [comment]
Hi @hwhsu1231 

Yes, that is correct, that is the intention of the feature.
There is one edge case, and it is the variables that cannot go to the ``conan_toolchain.cmake``, because they are ignore from there, at this moment they are:
- CMAKE_SH: Used for MinGW with bash in the path
- CMAKE_MAKE_PROGRAM
- CMAKE_POLICY_DEFAULT_CMP0091
- BUILD_TESTING

Note that at the developer level these might not be important in a majority of cases, but there might be some corner case that the developer would still need to pass those in the command line, because they are in Presets, but not in the ``conan_toolchain.cmake``

**Comment by hwhsu1231** [comment]
@memsharded Got it. Thanks!

**Comment by mikeb-ah** [comment]
What is the intended handling of CMP0091? I have a build where CMake is failing because it is not set and I've been asked to remove all policy settings from the command line, but if that is required to be handed in directly to CMake, I'll have to mention that.

**Comment by memsharded** [comment]
CMP0091 is set to make sure ``CMAKE_MSVC_RUNTIME_LIBRARY`` is followed to define the VS runtime. It might not be completely necessary in all cases, depends on the CMake version and cmake_minimum_required, but helps in the general case
