### ISSUE TITLE
[bug] Is gcc 12.1, 12.2 missing?

### ISSUE THREAD

**Issue by H-G-Hristov** [conan-io/conan#12255]
![Screenshot 2022-10-06 at 14 36 49](https://user-images.githubusercontent.com/47526411/194302916-caacc3a2-156c-4739-a31c-715a2ec101ef.png)

While creating a custom `settings.yml` file I noticed that the support for current gcc versions 12.1, 12.2 might be missing.

**Comment by memsharded** [comment]
Yes, it is. 
Not a big deal, because Conan by default uses the major ``12`` version, it is only necessary for users who want to explicitly manage binary compatibility at the minor version level, and those users in the majority of cases manage their own ``settings.yml`` file.

If you want to submit a PR to add those, it will be welcome.

**Comment by hwhsu1231** [comment]
@memsharded 

I met an error when using MinGW because the version of its compiler is `12.2.0`.

![image](https://user-images.githubusercontent.com/71438617/194376324-7032527a-ce11-4e19-843f-1a1d32884ed4.png)

**Comment by memsharded** [comment]
@hwhsu1231 as suggested above, you can fix it by adding it to your ``settings.yml``. Recall that you can manage your custom ``settings.yml`` (and profiles, remotes, conf, etc), with ``conan config install``

Also, this check is only done by the legacy ``cmake`` generator. The new recommended ``CMakeDeps`` and ``CMakeToolchain``, which are the necessary ones to be 2.0-ready, no longer do this check.

**Comment by hwhsu1231** [comment]
@memsharded What do you mean **"this check"**? I only use `CMakeDeps` and `CMakeToolchain` in my conan recipe, not including `cmake` generator.

**Comment by memsharded** [comment]
> @memsharded What do you mean "this check"? I only use CMakeDeps and CMakeToolchain in my conan recipe, not including cmake generator.

Oh, sorry, I was confused by the output, you are right.

Nevermind, as it seems you are using your own profile to explicitly opt-in to use the minor ``12.2`` instead of Conan default to use just ``12``, if you are managing your profiles with ``conan config install``, it will already be easier to drop there the ``settings.yml`` with the addition too.

**Comment by memsharded** [comment]
This is not a blocker, moving it to 1.55.
Recall that you can add your own settings to ``settings.yml`` and also automate it with ``conan config install``

**Comment by IceflowRE** [comment]
> This is not a blocker, moving it to 1.55. Recall that you can add your own settings to `settings.yml` and also automate it with `conan config install`

What?
This settings compiler version check are so messy, it is always breaking the CIs. Always. I do not want to update the version manually everytime a new compiler version is out.
I need an option to skip those checks on my own risk or conan updates asap.

But looking at Conan 2.0, it does not seem to be viable to implement it tho. Is there already an release date range?

**Comment by memsharded** [comment]
Hi @IceflowRE 

>What?
>This settings compiler version check are so messy, it is always breaking the CIs. Always. I do not want to update the version manually everytime a new compiler version is out.

It is not necessary to update the version manually in every Conan instance, it should be updated (while Conan does not update it) in one settings.yml file and use it everywhere with ``conan config install``. Using your own profiles and distributing them with ``conan config install`` is the recommended way for production anyway. Using a new compiler version typically includes installing the compiler in the machines (developers and CI agents), and updating or adding a new profile with the new compiler version.

> I need an option to skip those checks on my own risk or conan updates asap.

It is not possible to skip this check, it is very deep in Conan, it is not just one simple place that "validates" the value, but it is very hardcoded inside the ``settings`` model, how assignment, comparison, "contains", etc. are computed. This was done this way, because as the settings are part of the ``package_id``, it is very important to have a well defined set of values, otherwise the mismatches for ``package_id`` are a much bigger pain.

I am very sorry that we didn't manage to add this for 1.54, we are absolutely swamped at the moment. This is why I labeled it as "PR welcome", thinking that if it was important enough for someone, they could put some time to contribute it.


> But looking at Conan 2.0, it does not seem to be viable to implement it tho. Is there already an release date range?

Conan 2.0 does not change this behavior of Conan, the settings values will still be equally restricted. The release date is still not fully defined for the same reason, it is difficult to estimate with the huge load of work to do. Hopefully before the end of the year.
