### ISSUE TITLE
[question] How to disable the warning of "without specifying a build profile"?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#12271]
### Problem Descriptions

If we don't specify a build profile in `conan install` command with `CMakeDeps` or `CMakeToolchain` generator, then it will show a warning message and encourage us to use one:

```cmd
conanfile.py: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
```

I'm wondering that is there any method to **DISABLE** this warning?

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/194620688-2e80844a-04eb-4753-bac4-07498b46820f.png)

**Comment by memsharded** [comment]
Yes, there is a method to disable the warning, to pass the ``-pr:b=default`` profile. 😄 

This is important to be ready for Conan 2.0, which will always compute the dependency graph using the build profile by default. So to answer your question, no, it is not possible to disable this warning, because it is very important to do what is recommending to do, instead of just hiding it.

**Comment by hwhsu1231** [comment]
If I specify a default profile in `conan install` command, will the **PROFILE** conflict with those other **ARGUMENTS** I specify in CLI? Which one is prior than the other one?

**Comment by memsharded** [comment]
CLI arguments form a profile that is composed with the other profiles, in the same way several profiles can be specified in the command line, and they all compose/accumulate into one "effective" profile that will be printed to terminal

**Comment by Karlinde** [comment]
I'm jumping in here with a related question: I'm curious if anything actually changes when specifying to use the `default` profile as build profile using `-pr:b=default` compared to letting the settings be default as would seem to be the case when omitting it and getting the warning? If I as a developer am aware that if a build profile is not specified then the default settings will be used, then what is gained by requiring the default profile to be specified, apart from having to type more?

Would it be possible to regard the presence of `-pr:h=xxx` as proof that the developer is aware of the fact that the host and build contexts will be different, and that if they haven't specified `-pr:b=xxx` then they implicitly want the build settings to be default without needing a warning?

**Comment by memsharded** [comment]
Hi @Karlinde 

Yes, there are some internal changes, on how the information from dependencies propagate if "build" profile is enabled. For example build_requires will only propagate environment, but not ``cpp_info``. Or there can be versions conflicts that are avoided, because pkg->(tool_requires)->cmake-(requires)->zlib/1.2.8 might be possible even if ``pkg-(requires)->lib-(requires)->zlib/1.2.11, because the "build" context doesn't necessarily always conflict with the "host" context, but if you don't use it, they will always conflict.

The ``pr:h`` the problem is that it is an alias to the other, and it is now not possible to change it without breaking other users.
The recommended way if you don't want to specify a full build profile, you can always use something obvious like ``-s:b os=Windows`` and that will force the build profile too.
