### ISSUE TITLE
conans.model.version.Version sorts private version identifier backwards

### ISSUE THREAD

**Issue by smoofra** [conan-io/conan#12288]
Versions with a [PEP 440 private version identifier][pep] are sorted backwards by `conans.model.version.Version`

### Environment Details (include every applicable attribute)
  * Operating System+version: Mac OS 12.6 (21G115)
  * Conan version: 1.53.0
  * Python version: 3.9.13

### Steps to reproduce 

```
In [1]: from conans.model.version import Version

In [2]: Version("1.0+foo.1")  < Version("1.0+foo.2")
Out[2]: False
```

[pep]: https://peps.python.org/pep-0440/#local-version-identifiers

**Comment by czoido** [comment]
Hi @smoofra,

Thanks for the question. A couple of comments:

- Please use the Version class under `conan.tools.scm` instead of the one from `conans.model.version` Check the docs for that class here: https://docs.conan.io/en/latest/reference/conanfile/tools/scm/other.html#version
- We are not adhering to PEP440 for this Version object, it just implements basic version comparison between objects. It's similar to semver but not fully implemented.

In this case of versions with build metadata if the two versions are equal in X.Y.Z the Version class will sort them alphabetically so I think it already behaves the same as PEP440. 

Hope this helps!

**Comment by smoofra** [comment]
ah, thanks!   why are there two different versions of the Version class?

**Comment by czoido** [comment]
> ah, thanks! why are there two different versions of the Version class?

Hi! All the new tools that are public and can be imported in recipes are in `conan.tools` thinking in providing compatibility and a migration path to 2.0. The legacy implementations are there to not break users but we are encouraging all users to remove those imports from recipes (please, [check the Conan 2.0 migration guide](https://docs.conan.io/en/latest/conan_v2.html))

**Comment by memsharded** [comment]
I'd say that the new ``Version`` class for 2.0 might actually return the right order for ``+<build>`` versions too. Not guaranteed by the semver, but a least our 2.0 implementation behave like this IIRC:
