### ISSUE TITLE
[question] How to create profile that sets libcxx for all compilers that support it

### ISSUE THREAD

**Issue by jpfeuffer** [conan-io/conan#12286]
I want *one* profile that inherits from default and sets libcxx for e.g., g++ and clang++.
I do *not* want to specify all possible compilers.
My first attempt of just adding 
`compiler.libcxx=libstdc++11`
 fails when the default is found to be e.g., Visual Studio.
Why can't conan just ignore it when it does not affect a compiler? Can I turn the ERROR into a WARNING?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @jpfeuffer,

Thanks for the question. Since Conan 1.38 Conan profiles support Jinja2 syntax, so maybe you can make use of that to achieve what you want. You could have a _myprofile.jinja_ file similar to this:

```
include(default)
{% if platform.system() == "Linux" %}
[settings]
compiler.libcxx=libstdc++11
{% endif %}
```

Please check the docs: https://docs.conan.io/en/latest/reference/profiles.html#profile-templates

Hope this helps!

**Comment by jpfeuffer** [comment]
Interesting. Can I access variables like the compiler, too?

**Comment by memsharded** [comment]
The compiler is not something that is globally defined. You might try to do something like ``os.getenv("CC")``, but that is not guarantee to be defined, nor to point to the compiler that you would expect.

**Comment by jpfeuffer** [comment]
Thanks a lot! As you might have seen, I might need to switch to a conanfile.py due to another issue anyway, so I will use the dynamic settings capabilities there. Thanks for your input.

**Comment by memsharded** [comment]
> Thanks a lot! As you might have seen, I might need to switch to a conanfile.py due to another issue anyway, so I will use the dynamic settings capabilities there. Thanks for your input.

Just one clarification: settings cannot be changed in recipes. They are pure input, read-only in recipes, and trying to change them is undefined behavior. The compiler definition needs to come defined by the profile/command line inputs.

**Comment by jpfeuffer** [comment]
Ok but I can change e.g. libcxx depending on the compiler that comes from a profile, right?

**Comment by memsharded** [comment]
> Ok but I can change e.g. libcxx depending on the compiler that comes from a profile, right?

No, not in recipes. Settings, and profile in general is read-only in recipes, and should be treated as such (even if Python allows to change things), because it can be undefined behavior.

The recommended way for production is to have a well defined set of profiles for the configurations that you want to manage, do not rely at all on any Conan auto-detection of the profile (this auto-detection has been even disabled by default in 2.0). These profiles can be easily managed, shared and installed in CI and developer machines with ``conan config install``

**Comment by jpfeuffer** [comment]
But won't this mean hundreds of profiles? There is a combinatorial explosion in the values for compiler, version, OS, c standards. I do not have any requirements except for the ABI (actually not even this is strictly necessary) and want to support everything.

**Comment by memsharded** [comment]
> But won't this mean hundreds of profiles? There is a combinatorial explosion in the values for compiler, version, OS, c standards. I do not have any requirements except for the ABI (actually not even this is strictly necessary) and want to support everything.

Not necessarily, how many platforms are you building binaries for? what is the size of your CI system? Most of our users typically build binaries for something between a few (4-6) to many (20-30), but definitely not hundreds.

**Comment by jpfeuffer** [comment]
Yes, in our own CI not so many. But I do not want to restrict users when building it for their own configuration. I want to make sure however, when they create their own profile that it matches certain standards. I.e., if they use gcc/clang in any version (even if we do not have a profile for our CI) that it uses a certain C++ standard or ABI.

**Comment by memsharded** [comment]
You don't have to, that is the idea, not restrict the users to try different configurations. Sometimes they will work, and sometimes a certain configuration will not work, and they can report it.

For things that really, really are not supported, you can raise in the ``validate()`` method, like:
```python
def validate(self):
     if self.settings.os == "Windows":
           raise ConanInvalidConfiguration("This package doesn't build or work in Windows")
```
To help users fail-fast and understand what is happening. 

But trying to restrict the ``libcxx`` for example, in our experience it is too much. It is incredible how many different variants are out there, and things that might work, because it happens to be a patched ``libstdc++`` that is patched to not fail with C++11 things, etc. Or even other users trying to use other variants of the libcxx that are not even modeled.

Also, having your own profiles clearly defined and advertised "this is the set of profiles that we test in our CI" really help consumers of your software to reproduce things, be sure what configs have been tested already, etc. Note that if you put those profiles in a git repo, for example, your users can also ``conan config install`` it, and get those profiles automatically.

**Comment by memsharded** [comment]
As a note, we create +130 different binaries in ConanCenter for the packages there, and besides the ``validate()`` method, there is nothing else there that tries to force settings.

**Comment by jpfeuffer** [comment]
I see, I see. I am starting to get an understanding of some conan best practices now. Thanks a lot for your guidance.

**Comment by memsharded** [comment]
> I see, I see. I am starting to get an understanding of some conan best practices now. Thanks a lot for your guidance.

Happy to help, do not hesitate to open new tickets to ask further questions.
