### ISSUE TITLE
[question] reproducible builds and version ranges?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#12297]
Hi,

we maintain ~80 packages and we have two packages for python_requires (base Conan recipe) and build_requires (CMake scripts) which are shared accross all ~80 packages.
We don't want to go over every packages whenever we do a fix / change in the base recipe or in the CMake scripts. 
If we were to use version ranges in the recipes how does it work when I have to rebuild a package from ~1 month ago?
E.g. assume a month ago I had:
* version 1.0.1 base_recipe
* version 2.0.3 cmake_scripts
* version 3.0.0 foo, which has python_requires >=1.0.0 <2.0.0 for base_recipe and build_requires >=2.0.0 < 3.0.0 for cmake_scripts

Let's assume a month goes by and I have to rebuild "foo" 3.0.0 for some reason. Currently I have:
* version 1.5.0 base_recipe
* version 2.7.0 cmake_scripts

If I get it right because of the "python_requires >=1.0.0 <2.0.0 for base_recipe and build_requires >=2.0.0 < 3.0.0 for cmake_scripts"
when I rebuild 3.0.0 of foo now, it'll pick up 1.5.0 from base_recipe and 2.7.0 from cmake_scripts.

Am I get it right? If yes, is there a way with Conan to:
* have reproducible builds (e.g. whenever I rebuild an old version of a package, the very same dependencies are used, that were used at the time of the original build)
* still have some sorts of way of using version ranges? (e.g. not so keen on going over ~80 packages whenever we do a commit on either base_recipe, cmake_scripts)

Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

There are 2 ways to achieve this:

- Use multiple server repositories, storing a subset of the packages that were use at that release, and you maintain one repo per every release you want to be able to reproduce. 
- Use lockfiles: https://docs.conan.io/en/latest/versioning/lockfiles.html. Note that lockfiles can be a bit complicated in 1.X for some advanced cases, if you haven't use them yet, you probably want to wait until upgrading to 2.0, because lockfiles have been greatly simplified there.

While the first approach is possible, certainly not typical, the approach using lockfiles is more common (not only for Conan, but also for other package managers)

**Comment by harsszegi** [comment]
Awesome, thanks a lot @memsharded, lockfiles it is then (I completely forgot about them)
