### ISSUE TITLE
[bug] `conan imports --undo`: "File doesn't exist" for symlinks

### ISSUE THREAD

**Issue by BobIsOnFire** [conan-io/conan#12301]
### Environment Details (include every applicable attribute)
  * Operating System+version: RHEL 8.4
  * Compiler+version: gcc 8.4
  * Conan version: 1.52.0
  * Python version: 3.6.8

### Steps to reproduce + Logs

`conanfile.txt`:

```
[requires]
xz_utils/5.2.5

[imports]
bin, * -> ./bin
```

Commands:
```
$ conan install ~/test/conanfile.txt
...
conanfile.txt imports(): Copied 23 files
$ conan imports --undo .
WARN: File doesn't exist: /home/user/test/build/bin/xzcat
Removed 23 imported files
Removed imports manifest file: /home/user/test/build/conan_imports_manifest.txt
```

`xzcat` is a symlink for `xz`, and `xz` gets deleted before its symlink, leaving `xzcat` broken. It also does not remove `xzcat` from the folder (since it does not exist, according to conan)

https://github.com/conan-io/conan/blob/develop/conans/client/importer.py#L33 uses [`os.path.exists`](https://docs.python.org/3/library/os.path.html#os.path.exists), which returns `False` for broken symlinks. Maybe it is safe to use [`os.path.lexists`](https://docs.python.org/3/library/os.path.html#os.path.lexists) here?

**Comment by memsharded** [comment]
Hi @BobIsOnFire 

The ``imports`` feature as such is being deprecated, and it has already been removed in 2.0. Then it is unlikely that it will be prioritized, so I'd like to suggest a path to move forward:

- Change your ``conanfile.txt`` to a ``conanfile.py``
- In the conanfile.py, implement a ``generate()`` method that iterates ``self.dependencies`` and do a ``copy(self, ...)`` (from ``from conan.tools.files import copy``) to copy to the desired location
- If you want a manifest of what is being copied, you can generate too in the ``generate()`` method
- The ``undo`` functionality will not be built-in, but if you created the manifest in the previous step, it should be easy to use it. You can also generate directly a script that uninstall those files in the ``generate()`` method instead of just a manifest.

**Comment by BobIsOnFire** [comment]
Hi @memsharded, thanks for the advice! Managed to implement this functionality, works fine.

**Comment by memsharded** [comment]
Thanks for the feedback @BobIsOnFire and for following up and closing the issue!
