### ISSUE TITLE
[bug] conan export-pkg suggests to use invalid option

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#12317]
"conan export-pkg" suggests to use "--update" but "--update" isn't a valid option for "export-pkg"

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version:
  * Conan version: 1.53.0
  * Python version:

### Steps to reproduce (Include if Applicable)
conan export-pkg -pf /mnt/c/conan/linux_debug -f -s os=Linux -s build_type=Debug -s compiler.cppstd=17 -pr /mnt/c/conan/profiles/host_unix /mnt/c/conan/test_conan/recipes/library/all/conanfile.py library/2020.0.1@user/channel

Recipe has requirements with recipe revision
```
self.requires("libxml2/2.9.14@user/channel#00b261c680d69a8bf53425b15b38c58a")
self.requires("zlib/1.2.12@user/channel#15ff7db1ab5b19debc62bfb6c2c77299")
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
ERROR: Failed requirement 'zlib/1.2.12@user/channel' from 'libxml2/2.9.14@user/channel'
ERROR: The 'c0563e53bec60677ce8447f7d440e5e5' revision recipe in the local cache doesn't match the requested 'zlib/1.2.12@user/channel#15ff7db1ab5b19debc62bfb6c2c77299'. Use '--update' to check in the remote.

If I add --update, I'm getting
"conan export-pkg: error: unrecognized arguments: --update"

**Comment by memsharded** [comment]
Hi @Nekto89 

Yes, this might happen in Conan 1.X, as the cache can only host 1 revision at a time, and if the ``export-pkg`` command requires some revision not in the cache, the internals will fire this error.

If a package has dependencies, in theory a previous ``conan install`` must happen in order to be able to build the current binary, that it will be later ``export-pkg``. At this first ``conan install`` step, it is possible to pass the ``--update`` argument if necessary, so the next ``conan export-pkg`` will not need it. If there are concurrent Conan processes changing the status of the cache, probably it is more recommended to use different caches.

I have been checking, and it would be a bit risky to change this at this moment, because that error is raised not in the ``export-pkg``, but in the core of the dependencies resolution, it cannot stop being raised, and providing an ``--update`` argument to ``export-pkg`` seems weird given the above expected flow. As this is not an issue anymore in Conan 2.0, I think requiring a previous ``conan install --update`` would be a good enough workaround at the moment.

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2 - Conan 1 is not receiving many more features as we fully focus on the newer version - The proposed workaround works solidly for this case :)
