### ISSUE TITLE
[question] Unable to use editable package as a dependency 

### ISSUE THREAD

**Issue by aacebedo** [conan-io/conan#12316]
Hi,

I am currently trying to use editable package with conan 1.53.0
I made a small example here : https://github.com/aacebedo/conan_example

If I try to create the package `cmp2` after having created the `cmp1` package everything is fine:
```bash
$> cd <clone directory>
$> conan create ./cmp1
$> conan create ./cmp2
```

However if I add `cmp1` as an editable package and try the same command, it ends up with a cmake error complaining about the fact it does not find the package (`cmp1` appears in the cache when I run `conan search`:

```bash
$> cd <clone directory>
$> conan editable add ./cmp1 cmp1/0.1
$> conan create ./cmp2
```

```bash
-- Conan: Target declared 'cmp1'
CMake Error at build/generators/cmakedeps_macros.cmake:39 (message):
  Library 'cmp1' not found in package.  If 'cmp1' is a system library,
  declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
  build/generators/cmp1-Target-release.cmake:34 (conan_package_library_targets)
  build/generators/cmp1Targets.cmake:26 (include)
  build/generators/cmp1-config.cmake:10 (include)
  CMakeLists.txt:4 (find_package)
```

What am I missing here ?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @aacebedo 

I am trying to reproduce this, but it also fails, even if I don't use the editable, it also fails for the normal case.
I am trying in Windows, and the problem is that the ``.lib`` file is not being packaged, so it doesn't work. You haven't reported your OS, please do, sometimes it can be relevant to know what is happening.

Then, I managed to make it work, changing the cmp1 header to:
```c
#ifdef _WIN32
  #define cmp1_EXPORT __declspec(dllexport)
#else
  #define cmp1_EXPORT
#endif

cmp1_EXPORT void cmp1_func();
```
to make sure the ``.lib`` is created.

Then, it works with the normal ``create`` flow, and the editable too, but please note that the editable need to do a local build in order to create the binaries, otherwise the consumer will not be able to find it:
```bash
$ cd cmp1
$ conan editable add . cmp1/0.1
$ conan install .
$ conan build . # a local build with cmake ... should work too
$ cd ../cmp2
$ conan create .
```
Note the last ``create`` is not recommended. If you have ``cmp1`` in ``editable`` mode, is because you want to do changes simultaneously in cmp1 and cmp2. But having changes in ``cmp1`` only, and creating packages in the cache for ``cmp2`` that depends on the edited state of the ``cmp1`` is certainly a bad pattern. Typically you will do more like ``conan install + cmake ...`` in ``cmp2`` too.

Other notes:
- Recommended to use the ``test_package`` functionality. It really helps to debug package issues, without needing to consume from another project. Just ``conan create .`` is good to create and test the package
- Recommended to start from a working template like: ``conan new hello/0.1 -m=cmake_lib`` and work from there, step by step.

**Comment by aacebedo** [comment]
Thanks for the info !

I am running the example on Linux.

I think I did not built the cmp1 before so It may explain why the targets are not found.

**Comment by memsharded** [comment]
> I think I did not built the cmp1 before so It may explain why the targets are not found.

yes, and in Linux, the code above is not necessary, because all symbols are exported by default to shared libraries.

If you managed to make it work doing the build, please close this issue as resolved, thanks!

**Comment by aacebedo** [comment]
Agreed I close this. Thanks !
