### ISSUE TITLE
[question] Is it possible to track usage of certain package

### ISSUE THREAD

**Issue by mafes** [conan-io/conan#12333]
Hi all,
I plan to use conan in combination with jfrog artifactory. Can you please tell me if it is possible to track the usage of a particular package.
For example, I want to determine in which other packages of the same Artifactory repository, a particular package is used in the defined version. This would be helpful to track bugs or security vulnerabilities.

thank you in advance!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @mafes 

Artifactory, or any Conan server do not store the "inverse" dependency model, because this is more challenging than it seems:

- Conan implement "conditional dependencies", a dependency that can exist only in a certain OS, or for a given configuration. Then, the dependency graph is different for every different configuration. This is a very common case. So in general it cannot be said that ``pkga`` is required by ``pkgb``, but the "inverse" model would mean to understand and reverse all the possible conditional logic in recipes, which is impossible.
- Then, it is very typical to have an explosion of consumers. You will have zlib/1.2.11#revision1 which quickly is required by tenths of different revisions of ``pkga/1.2.0``, and ```pkgb/2.3.4``, and each one of these revisions might be used by many other revisions downstream. That means that in practice, any operation that you want to do from one package to all the consumers become quickly very challenging to scale.

What Conan has been recommending is the "products" approach. You can define a set of applications, or consumers you want to maintain, that includes different versions, for example your products are ``app1/1.0``, ``app1/2.1``, ``app2/3.2``, etc. For each one is easy to construct the dependency graph, for different configurations and analyze the dependencies. Conan has tools to print the dependency graph, or even to calculate the build order, in levels that allow parallelism, for the things that need to be rebuilt in case something changes in the graph.

**Comment by mafes** [comment]
@memsharded, thank you for your detailed answer!
Can you please give me a hint where the "products" approach is described?

**Comment by memsharded** [comment]
Yes, you might find some explanation in the https://docs.conan.io/en/latest/versioning/lockfiles/ci.html, when it describes a "package" pipeline and a "product" pipeline.

It is true that the CI approaches described there rely on the lockfiles, and lockfiles in 1.X are complicated for advanced cases like the CI one, but Conan 2.0 has greatly simplified the lockfiles and it will be easier and more understandable.

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
