### ISSUE TITLE
What attribute/flag controls upload to artifactory remote repository subfolder/path?

### ISSUE THREAD

**Issue by whitefluffypenguin** [conan-io/conan#12366]
Hi there,

What attribute/flag controls upload to artifactory remote repository subfolder/path?

**Comment by memsharded** [comment]
Hi @whitefluffypenguin 

Please check https://docs.conan.io/en/latest/uploading_packages.html, and https://docs.conan.io/en/latest/uploading_packages.html

Conan uses its own repository type, you create a Conan repo there, and the layout/path/folders is automatically managed, it is not possible to upload things to a specific path, because the layout is important to determine what are the recipes, what are the different binaries, etc.

**Comment by whitefluffypenguin** [comment]
I read everything (both links looks identical) however it didn't become clearer. When i run "conan upload" command - it succeeds to deploy into certain artifactory remote subfolder (not the one i need to deploy into). Is this subfolder set somewhere?

**Comment by memsharded** [comment]
That is the thing, it is not possible to put things in the server in a random/configurable folder, because the server layout has a very important meaning, and the Conan protocol relies on it for working. If you do ``conan upload`` some packages, with binaries, you will see the folder structure is:
```
/user
   / pkg_name
           / version
                 /channel
                       /recipe_revision
                                 /package_id
                                          /package_revision
```
All the ``conan search``, ``conan install``, ``conan upload``, ``conan info``, etc. use this folder structure to resolve things. This is similar for example to the ``pool`` folder necessary convention for Debian packages.

You can change the root folder by using a different username, which is a recommended way to differentiate your own packages, or packages by team of your org, for example.

Also, it is important that it is generally not a recommended approach to use server folder locations to resolve things directly. The Conan commands provide a level of abstraction for this storage, and in order to extract things from Conan packages there are Conan mechanisms, like imports/deploy (in Conan 1.X) or the new ``deployers`` in Conan 2.0

**Comment by whitefluffypenguin** [comment]
Clarifying. I ran the following command: "conan upload first/1.0.0.0 -r=<remote_name> --confirm". Next i found the following structure in artifactory artifacts pane. All question-marked folders (btw they don't look like user (_), channel (_), ...) are out of user control and always auto chosen and managed by conan automatically no matter what server package goes to - understood.
The root folder looks like <remote_name>, there is an 'underscore' under it - is it a username? I ran this upload under certain username (it wasn't an 'underscore') but the package was placed under 'underscore'. I am a little confused. Shall i try uploading under different (my) user?  
<img width="185" alt="20221021_conan_artifactory_01" src="https://user-images.githubusercontent.com/113041499/197315972-26c52db9-f327-47b9-9ce3-695368af6836.png">
<img width="274" alt="20221021_conan_artifactory_02" src="https://user-images.githubusercontent.com/113041499/197315977-df0e31c8-ff13-46eb-b2d5-d05b5c1f89c3.png">

**Comment by memsharded** [comment]
Yes, good observation.
When conan packages do not specifying user or channel, like the ConanCenter packages, in the conan model and recipes they will be ``user=None`` and ``channel=None`` to model they are not defined.
But in a folder layout, those are replaced by underscore ``_``, as the empty string ``""`` is not valid folder name, to keep a consistent layout for all packages, both those defining user and those do not defining it.

**Comment by whitefluffypenguin** [comment]
Got it - thank you! As soon as i specified 'user' (not to mix with artifactory user 'username') and 'channel' conanfile.py recipe attributes i was able to change and tune up the upload target location!

**Comment by memsharded** [comment]
Good to know, happy that it is working. If you notice something not working as expected, please consider checking if that customization had something to do, I am not aware of other users doing this.

I guess we can close this question as responded now? Thanks!

**Comment by whitefluffypenguin** [comment]
yes - thank you - please close!
