### ISSUE TITLE
[bug] setting default generator for cmaketoolchain in the configuration does not work

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan#12382]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 11
  * Compiler+version: MSVC 16
  * Conan version: 1.53
  * Python version: 3.10

### Steps to reproduce (Include if Applicable)
`conan create all pacakge/x.x.x@ -c tools.cmake.cmaketoolchain:generator=Ninja` => use correctly the ninja generator
but 
```
conan config set tools.cmake.cmaketoolchain:generator=Ninja`
conan create all pacakge/x.x.x@
```
=> the configuration is not taken into account and the default Visual Studio generator is used

**Comment by czoido** [comment]
Hi @fdgStilla,

Thanks for the question. The problem here is that `tools.cmake.cmaketoolchain:generator` is a configuration that should be set in the [global.conf](https://docs.conan.io/en/latest/reference/config_files/global_conf.html) file (this is the new configuration system that is compatible with Conan 2.0) and `conan config set` affects the _conan.conf_ configuration file that will be removed in Conan 2.0.
To solve the issue, please create a _global.conf_ file (if it's not there yet) in the Conan Home (you can get this folder with `conan config home`) and add the line for the configuration with a text editor: 

```
tools.cmake.cmaketoolchain:generator=Ninja
```

Hope this helps.

**Comment by fdgStilla** [comment]
Great it works thanks!
