### ISSUE TITLE
Package revision storage

### ISSUE THREAD

**Issue by whitefluffypenguin** [conan-io/conan#12398]
I noticed each package revision is stored in dedicated export (and package) sub-folders. 
I assume, this is done by design. Please confirm - is there a way to configure to store (overwrite or with history/delta changes) different package revisions in single export/package folder?
Also to have them downloaded and installed as deltas?

**Comment by memsharded** [comment]
Hi @whitefluffypenguin 

No, the packages artifacts are stored completely, not as deltas, in every different revision folder.
It is not possible to change this, the way the server stores and uses this information is hardcoded, it is not possible to overwrite it.

However, Artifactory storage is efficient, and implements de-duplication. If for some reason some artifacts would be identical in different revisions (a bit unlikely anyway, because a revision means that something changed), then Artifactory only will store 1 copy internally.

I am not aware of any other package manager for any other language that stores deltas (also because binary deltas are typically complicated and fragile), so the general approach in all cases is to implement retention and removal policies and algorithms that maintain storage controlled. For example, a very common approach is to make sure to put temporary packages in some repos, and do a promotion (copy) of the final/approved/good packages to a repository that is stored for long time, while the temporary repos can be very aggressive to remove old packages.

**Comment by whitefluffypenguin** [comment]
Please review https://octopus.com/docs/deployments/packages/delta-compression-for-package-transfers.

**Comment by memsharded** [comment]
Interesting, I didn't know about https://octopus.com/. 
But I was talking about common package managers (maven, cargo, apt, pip, etc), up to my knowledge no one of them implements anything like that. 
The complexities that such an approach would bring are huge, definitely not something in our scope.

**Comment by AbrilRBS** [comment]
Closing as not planned, thanks a lot for your suggestion, we appreciate the time you took :)
