### ISSUE TITLE
[question] write error: stdout when calling conan create

### ISSUE THREAD

**Issue by dillydill123** [conan-io/conan#12417]
I'm attempting to use `tee` to log the `conan create` command:

```console
    conan create \
    --profile:host ${PROFILE_FILE_HOST} \
    --profile:build ${PROFILE_FILE_BUILD} \
    ${ROOT_DIR}/src @user/${channel} 2>&1 | tee -a ${LOG_FILE_PATH}
```

And every so often, I get this error during the build step. It's not every time, and the chance of it occurring increases with a higher number of parallel jobs.

```console
make[1]: write error: stdout
make: *** [Makefile:139: all] Error 1
```

Here is my `configure` and `build` commands in `conanfile.py`

```console
cmake.configure(source_dir=source_dir, build_dir=self.build_folder)
cmake.build(build_dir=self.build_folder)
```

I'm using conan version 1.53, Ubuntu 20.04.4 LTS, GNU Make 4.2.1, cmake version 3.22.0.

I'm aware that this might not be an issue with conan itself. So instead I want to ask if there's a better way I can log output from `conan`, or if there are any better solutions which will avoid this issue. Thank you

**Comment by memsharded** [comment]
Hi @dillydill123 

Thanks for the report. It seems a challenging one to reproduce, because it is not deterministic and caused by concurrency. A couple of ideas:
- Parallel jobs run with separate independent caches via CONAN_USER_HOME? Because the conan cache is not concurrent in general
- You have a legacy conf https://docs.conan.io/en/latest/mastering/logging.html#how-to-log-the-build-process the ``conan_run.log`` or the ``CONAN_LOG_RUN_TO_FILE`` that will redirect things to files. Not very sure if it is robust for concurrent use to log to the same file, but if every job has a different file, might help

I can try to give some other insights that might be related:
- It seems you are using the legacy ``cmake`` integration, instead you should be using the ``from conan.tools.cmake import CMake`` and ``CMakeDeps`` and ``CMakeToolchain``. This will allow you to be ready for Conan 2.0, which is already in beta.4, and final release is approaching very quickly
- Conan 2.0 itself might alleviate this issue as well, because we have greatly simplified some code related to managing stdout and stderr, we have removed things like the progress bars which also introduced some challenges.
- Conan 2.0 also redirects all messages to ``stderr``, while it keep to ``stdout`` exclusively the valuable final result of the message.

**Comment by dillydill123** [comment]
Thank you for the response. To be clear, when I say parallel jobs I meant `make -j`. So in this sense I suppose all the jobs are outputting to the same logfile. It's one `conan create` command with one cache that's receiving this error. Looking up this issue, I find that it existed before https://bugs.launchpad.net/ubuntu/+source/linux-signed/+bug/1814393, but I am well past the versions mentioned in the link.

I'm now using `from conan.tools.cmake import CMake` but unfortunately still experiencing the same issue. I'm not sure if `CONAN_LOG_RUN_TO_FILE` will help me since I'm not using `self.run` anywhere in my `conanfile.py`

**Comment by memsharded** [comment]
> I'm now using from conan.tools.cmake import CMake but unfortunately still experiencing the same issue. I'm not sure if CONAN_LOG_RUN_TO_FILE will help me since I'm not using self.run anywhere in my conanfile.py

It might still help, because ``CMake.build()`` still runs ``conanfile.run()`` internally, please try it and let us know.

**Comment by dillydill123** [comment]
Still no luck with the following:

```console
    export CONAN_LOG_RUN_TO_FILE=1
    conan create \
    --profile:host ${PROFILE_FILE_HOST} \
    --profile:build ${PROFILE_FILE_BUILD} \
    ${ROOT_DIR}/src @user/${channel}
```

I can see the `conan_run.log` but still getting the same `make` error

**Comment by dillydill123** [comment]
I don't have time today, but I was thinking of a test to verify that it is `conan`. My plan is to disable the `CMake.build()` step and call `cmake --build ...` in a separate script with the same `tee` command. This way I can isolate whether or not it really is `conan` causing the issue, because it's not so clear to me.

**Comment by memsharded** [comment]
Ok @dillydill123, yes, that would be helpful, let us know how it goes.

**Comment by dillydill123** [comment]
Unable to reproduce the error anymore. I assume it was due to something outside of Conan (too much output in the log file). So I will close this

**Comment by memsharded** [comment]
Thanks for following up and closing @dillydill123, don't hesitate to create a new ticket if it happens again.
