### ISSUE TITLE
[question] About cmake.configure()

### ISSUE THREAD

**Issue by hamham240** [conan-io/conan#12420]
I am currently using conan 2.0, and it seems like in previous versions the `CMake.configure()` function allowed you to specify the build folder via the `build_folder` parameter. This parameter has been deprecated in version 2.0 and I wanted to know if there is still any way to specify which directory CMake will produce the build.

I know that the N configurations -> 1 package approach is discouraged, but my motivation behind this question is so that I can set up a single conan package that has subfolders for every different type of configuration. It would make my life easier if I could achieve this because the project I am working on expects this kind of structure.

Thanks

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @hamham240 

Yes, have you checked how the ``layout()`` and different helpers like ``cmake_layout()`` work? they allow defining the build folders. It is true that it works for single-configuration packages mostly.

> I know that the N configurations -> 1 package approach is discouraged, but my motivation behind this question is so that I can set up a single conan package that has subfolders for every different type of configuration. It would make my life easier if I could achieve this because the project I am working on expects this kind of structure.

It is not only discouraged, the remains of ``cpp_info.debug``, ``cpp_info.release`` that provided some attempt to support it, have been removed in 2.0. Packages will be strongly recommended to be single-config always. But it would be better to clarify what you mean that the project expects this structure, because there might be other ways to achieve it, like via generators, which is probably the recommended approach. So a custom generator can be done that puts all different configurations (from multiple single-config packages), into a location like your project expects to find.

**Comment by memsharded** [comment]
Closing ticket as solved/staled, please create new ones if there is any further question.
