### ISSUE TITLE
[feature] Additions to settings.yml through additional files in directory "settings.d"

### ISSUE THREAD

**Issue by solosuper** [conan-io/conan#12422]
Hi,
I wanted to air an idea regarding official updates of `settings.yml` in combination with customized versions through  `conan config install`.

Searching through existing issues I found https://github.com/conan-io/conan/issues/8261, which addresses the same problem but with a different approach.
The problem is to keep a custom version of `settings.yml` in sync with eventual updated versions that is received through upgrades of conan.

Would it be a feasible solution to allow some `~/.conan/settings.d/` directory where partial additions could reside across updates of conan version?

My concrete use case is the addition of
```yml
cuda:
    None:
    True:
        compute_capability: ANY
        version: ANY
```
to `settings.yml`.

The suggestion is that conan concatenates `~/.conan/settings.yml` with all files in `~/.conan/settings.d/*` before finally parsing the merged settings.

I'll admit that this would not easily facilitate the _removal_ of settings like perhaps the suggestion in #8261 could manage, but maintaining custom additions like my example should be fairly simple.

There are probably corner cases that would complicate things that I have not thought about, though.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @solosuper 

We have considered this, but after some discussions, this is the approach that we will propose for 2.X:

- We don't want Conan client to be merging different settings on the fly for every Conan invocation, because if something fails in that merge, it will have a very bad UX to fix it and get out of it, it will be very bad for users.
- So we will still propose the distribution of a merged ``settings.yml`` as a full file in ``conan config install``
- And the feature will be a tool or custom command that allows merging such ``settings.d`` with the current default ``settings.yml``, and produce a new merged ``settings.yml`` to be distributed.
- This tool can be used by the owners of the configuration for ``conan config install``, even be automated (together with the typical automation used to start using the next Conan version in the team and in CI). Merge conflicts should be handled there, before distributing the file.

**Comment by solosuper** [comment]
Hi,
Thank you for your quick response and clear explanation. 

That seems like a very good solution and I'm looking forward to Conan 2.x 👍 

Feel free to close this issue.

**Comment by memsharded** [comment]
> Feel free to close this issue.

It is good to leave it open, I think this has been mentioned before in other issues, but this is the one that is defined more explicitly, so it is fine to have it assigned to the 2.X target, so it can be pulled from the queue after 2.0 is out.

**Comment by memsharded** [comment]
I am proposing this for 2.0, but only for 1 file, not for applying many in a directory. The problem with that is the possible potential errors because of the order in which those files are applied, it is not fully determined, it could be alphabetical, but that isn't intuitive for users either. I think that with 1 ``settings_user.yml`` file should be more than enough, and maintaining several different files would be even more complicated for users.

**Comment by memsharded** [comment]
Implemented https://github.com/conan-io/conan/pull/12980 for beta.9, closing this as this would solve the main issue with merging user settings.yml
