### ISSUE TITLE
[question] What is the canonical way to specify runtime requirements?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12435]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

In https://github.com/conan-io/conan-center-index/pull/13904, I need to pass the information that `gnuplot` is a runtime requirement of `matplotplusplus` (`gnuplot` executable is called under the hood by some functions at runtime).
Indeed `gnuplot` and its dependencies are not required a build time and I don't want to see its dependency graph propagated to include/definition/link interface of `matplotplusplus` in conan generators (and regardless of shared/static), I only want to propagate its env to `matplotplusplus`.

How to do this in conan? Shouldn't there be a dedicated `runtime_requires` (useful for runtime dependencies to executables or plugins)?

**Comment by memsharded** [comment]
Hi @SpaceIm 

> I need to pass the information that gnuplot is a runtime requirement of matplotplusplus (gnuplot executable is called under the hood by some functions at runtime).

Can you please clarify this? You mean that ``matplotplusplus`` library calls as a subprocess ``gnuplot`` executable?

I don't think this is possible in Conan 1.X, but might be doable in Conan 2.0. I have tried with this test:
```python
def test_pure_runtime_dep():
    c = TestClient()
    c.save({"tooldep/conanfile.py": GenConanfile("tooldep", "0.1").with_package_file("bin/mysh",
                                                                                     "myshared")
                                                                  .with_package_type("shared-library"),
            "tool/conanfile.py": GenConanfile("tool", "0.1").with_requirement("tooldep/0.1")
                                                            .with_package_file("bin/myexe", "exe"),
            "lib/conanfile.py": GenConanfile("lib", "0.1").with_requirement("tool/0.1",
                                                                            headers=False,
                                                                            libs=False, run=True),
            "consumer/conanfile.py": GenConanfile().with_settings("build_type", "os",
                                                                  "compiler", "arch")
                                                   .with_requires("lib/0.1")})

    c.run("create tooldep")
    c.run("create tool")
    c.run("create lib")
    c.run("install consumer")
```
And it looks good in terms of the generated ``virtualrunenv``.

But I am not sure that this should be a modeled thing in Conan. If a library is launching things via subprocesses execution, it is not a C++ dependency anymore. The fact that such executable can be also contained in a Conan package doesn't mean that a ``requirement`` should be introduced, because Conan ``requires`` are build-time requires. Conan never intended to work as a runtime-only dependency management. The above kind of works in 2.0, but it also potentially opens too many questions and concerns:

- The default ``package_id`` is not correct, it needs to be customized, because clearly the gnuplot executable do not affect the binary compatibility of the matplot library
- What happens with version conflicts? If gnuplot is also required by someone else, should it raise a conflict if the version is different? I can see users being confused by this.
- When using other generators like CMakeDeps, they will still generate ``gnuplot-config.cmake`` files, even if they dont have any headers nor libraries, they will still define binary folders.
- If libraries launch other executables, that are not Conan packages, but installed differently, how would it work? I don't think creating ``executable/system`` Conan package wrappers around such system executables should be done in order to support this case

I am labeling this as "look-into", to discuss with the team. In any case, it is something that definitely will not be possible in 1.X, and the discussion will be centered around which would be the recommended approach for 2.0 and ConanCenter

**Comment by SpaceIm** [comment]
> > I need to pass the information that gnuplot is a runtime requirement of matplotplusplus (gnuplot executable is called under the hood by some functions at runtime).
> 
> Can you please clarify this? You mean that `matplotplusplus` library calls as a subprocess `gnuplot` executable?

Yes: https://github.com/alandefreitas/matplotplusplus/blob/58d3994f5c5a82d03f3e825aadaa77300f4a8365/source/matplot/backend/gnuplot.cpp#L66-L78

In dependencies list of their README:

```
Gnuplot 5.2.6+

Install Gnuplot 5.2.6+ (Required at runtime)
```

Otherwise yes your diagnostic is correct. I would like to mention that runtime dependencies may also be recipes providing only plugins loaded at runtime, so I think it makes sense in conan to have a dedicated way to handle runtime dependencies.

**Comment by memsharded** [comment]
> Otherwise yes your diagnostic is correct. I would like to mention that runtime dependencies may also be recipes providing only plugins loaded at runtime, so I think it makes sense in conan to have a dedicated way to handle runtime dependencies.

Not necessarily, this is exactly the nature of plugins, they are runtime things. You can develop them in isolation, and most importantly you can define the consumers of these plugins completely in isolation, without any connection to the plugins. In any case the plugins might have a dependency to some common library used to provide the plugin interface, for the consumers, but not the consumer depends on the plugins.

This is what Conan should capture, as Conan is a "development" tool, not a deploy tool, so introducing a dependency from one application that might use some plugins or not at development time is not correct. As it is a runtime thing only, it should be managed at runtime, in the case of Conan, it would be managed with different ``conan install app/1.0``, then you can install plugins: ``conan install myplugin/1.1 --deploy=myplugin_deployer``, but in any case installing the app should bring a runtime dependency to the plugin. Otherwise it is not a plugin, it is a regular library dependency of the application.

**Comment by SpaceIm** [comment]
Maybe not the good word, I meant modules or basically any shared lib loaded at runtime only and mandatory.

Let's take an example:

- recipeA provides only a module (shared lib without exported symbols), intended to be loaded at runtime
- recipeB is an executable, and recipeA is a mandatory runtime dependency of recipe B.
- recipeC has recipeB in tool_requires

If you can't propagate recipeA shared lib location when executable of recipeB is called during build of recipeC, it breaks, so I think conan should provide a way to model this runtime dependency, it's not just a deployment consideration. Any lib or executable packaged by conan may be executed during build of other recipes, so they must be usable at runtime in a "conan development context". They also must be testable in "conan context" or I miss something.

**Comment by memsharded** [comment]
> If you can't propagate recipeA shared lib location when executable of recipeB is called during build of recipeC, it breaks, so I think conan should provide a way to model this runtime dependency, it's not just a deployment consideration. Any lib or executable packaged by conan may be executed during build of other recipes, so they must be usable at runtime in a "conan development context". They also must be testable in "conan context" or I miss something.

Yes, those cases can be managed in 2.0, using the adequate ``traits``, like ``run=True`` trait, as shown in the example test above, this is exactly the reason for this trait, to model runtime dependencies. My comments above were about the cases where an "inversion" happens, and a library is calling an executable as a  subprocess. 

As this is supported already in 2.0, at the moment it is not necessary to do anything else for beta.5, so I am closing this issue. Any further feedback on the behavior of the requirement trait is appreciated.

**Comment by SpaceIm** [comment]
So for a recipeA with recipeB as runtime requirement it would be:

```python
    def requirements(self):
        self.requires("recipeB/x.y.z", headers=False, libs=False, run=True)
```

and during build or recipeA, conan v2 won't add cpp_info of recipeB in cflags, ldflags of build helpers? I want to be sure that a shared lib recipeB won't be part of loadable shared libs of any shared lib or executable of recipeA.

**Comment by memsharded** [comment]
> and during build or recipeA, conan v2 won't add cpp_info of recipeB in cflags, ldflags of build helpers? I want to be sure that a shared lib recipeB won't be part of loadable shared libs of any shared lib or executable of recipeA.

Yes, that is the idea
