### ISSUE TITLE
[bug] Package name might affect Conan behaviour

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#12430]
The documentation for `conan create` states that default option for `--build` is the package name. It seems that Conan does literally that and doesn't care about package name being one of reserved values. It makes it possible to create a misleading package for Conan

### Environment Details
  * Conan version: 1.53.0
  * Python version: 3.8.9

### Steps to reproduce 
* Create a directory with a single `conanfile.py` with the following context
```python
from conans import ConanFile

class NeverConan(ConanFile):
    name = "never"
    version = "0.1"
    settings = "os"

    exports_sources = "*"

    def generate(self):
        print("generate")

    def build(self):
        print("build")

    def package_info(self):
        print("package_info")
```
* Invoke `conan create .` from the directory containing `conanfile.py`

### Logs

```
...
Installing package: never/0.1
Requirements
    never/0.1 from local cache - Cache
Packages
    never/0.1:cc471ed355602ffa7007968c83aa4e7e648a38b5 - Missing

Installing (downloading, building) binaries...
ERROR: Missing binary: never/0.1:cc471ed355602ffa7007968c83aa4e7e648a38b5

never/0.1: WARN: Can't find a 'never/0.1' package for the specified settings, options and dependencies:
- Settings: os=Macos
- Options:
- Dependencies:
- Requirements:
- Package ID: cc471ed355602ffa7007968c83aa4e7e648a38b5

ERROR: Missing prebuilt package for 'never/0.1'
Use 'conan search never/0.1@ --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=never'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

**Comment by memsharded** [comment]
This is expected, because if you want a package name pattern, it is necessary to define ``--build=never*``, and not only ``--build=never``.

This has been made explicit in 2.0, so it is always necessary to add ``*`` for all package name patterns, so the test in https://github.com/conan-io/conan/pull/12433 validates it.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/12433

**Comment by ghost** [comment]
If that's a known quirk, would it make sense for `--build` option to have the default value of `<package_name>*` instead of `<package_name>`? Here the policy is resolved to be `never` by Conan itself. If I understood you correctly, having Conan to resolve it as `never*` by default would not cause an error.

**Comment by memsharded** [comment]
> If that's a known quirk, would it make sense for --build option to have the default value of <package_name>* instead of <package_name>? Here the policy is resolved to be never by Conan itself. If I understood you correctly, having Conan to resolve it as never* by default would not cause an error.

Well, it is a bit trickier, because Conan 1.X also runs a exact package name comparison, and it results that changing to automatically add ``*``, converting ``--build=never`` to ``--build=never*``, might match other previously unexpected things, like ``never_say/1.0`` package. This is the reason we removed the exact package name comparison in 2.0 and forced to explicit patterns always.
