### ISSUE TITLE
[feature] Configuration to prevent downloading pre-compiled binaries from remotes

### ISSUE THREAD

**Issue by jzinn** [conan-io/conan#12441]
If a package can be built from source, I would like to build it locally and not download pre-compiled binaries from a remote, while still avoiding repeated builds from source.

This does not seem possible, except possibly by hacking package id values using a new setting.

`conan install --build="*"` will build everything from source, but this does not avoid repeated builds.  Everything will be built every time, which is not desirable.

If the absence of this feature is deliberate, it would be nice to update the documentation to explain why.

A [relevant Stack Overflow question](https://stackoverflow.com/questions/66487350/how-to-force-conan-to-build-from-source-but-only-if-it-is-not-in-the-cache).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jzinn 

Thanks for your suggestion. 
This topic has been also treated in https://github.com/conan-io/conan/issues/12414.

Still the answer would the same, it is a model thing. If you settings match, you shouldn't rebuild, but get the existing pre-compiled binary. So, as you point out, the solution is to customize the ``settings``, most likely with a subsetting.

One of the reasons this would also be a challenging feature to implement is that it would introduce state in the Conan cache: packages that having a full matching model do one thing or the other depending on what happened in the past. We know from experience this is harder than it seems, and require a lot of effort to maintain and introduces large complexities in the code, adding extra burden on future maintenance. Some remnants of state in 1.X have already been removed in 2.0, making it "stateless" wrt to non-modeled things.

We could make it a FAQ, I am not sure it is easy to put it inline in any docs page.

**Comment by jzinn** [comment]
> If your settings match, you shouldn't rebuild, but get the existing pre-compiled binary.

In an ideal world with universal reproducible builds, I might agree.  However, I'm not so trustful of remote binaries.  Also, I like to look at build logs like `conan_run.log`.  And I think there is value in packages being built more than the minimal number of times.

> One of the reasons this would also be a challenging feature to implement is that it would introduce state in the Conan cache: packages that having a full matching model do one thing or the other depending on what happened in the past.

What new state is necessary?  I don't see how the past history would affect a decision to download pre-built binaries or not, but I could easily be missing something.

---

For the project I'm beginning to work on, there are many dependencies.  I would like to get through a complete local build using `conan install --build` at least once.

Every time a package fails to build, I make some changes and try again.  I would like to essentially resume the previous `conan install --build` run, but that rebuilds all of the many dependencies.

I've tried `conan install --build the_one_that_failed`.  But, once I get that package to build, I then follow it up with `conan remove "*" -f` and start my `conan install --build` from scratch again.

Do you have any suggestions to improve this workflow?

Is there a way to do a `conan install` but target only one dependency to build (and do nothing for any other dependency)?

**Comment by memsharded** [comment]
> In an ideal world with universal reproducible builds, I might agree. However, I'm not so trustful of remote binaries. Also, I like to look at build logs like conan_run.log. And I think there is value in packages being built more than the minimal number of times.

It is perfectly fine to not trust remote binaries from some repositories, and we are happy that many of conan users are building from source their own binaries. But one of the most important Conan features is the capability of managing your own binaries, and storing them in your own repos. Then, it would be necessary for this feature to also specify, "I want to build from source packages that comes from this repo and this other repo, but to use the precompiled binaries that come from this third repo". And the package immutability assumptions that are used thoroughly in Conan 2.0 would be broken, because even if the exact same thing is in two different servers, the action to do with them would be different.


> Every time a package fails to build, I make some changes and try again. I would like to essentially resume the previous conan install --build run, but that rebuilds all of the many dependencies.

You make some changes to the package recipe or source code? Then, it should work perfectly fine with ``--build=missing``, because changes in a recipe or source code, produce a new ``recipe_revision``, that by construction will not have binaries associated, so it will need to rebuild

> I've tried conan install --build the_one_that_failed. But, once I get that package to build, I then follow it up with conan remove "*" -f and start my conan install --build from scratch again.

I am not sure why you would do a ``conan remove "*" -f`` to remove all existing package binaries, including the one that you just built, and start from scratch, this doesn't make much sense.

> Is there a way to do a conan install but target only one dependency to build (and do nothing for any other dependency)?

Yes, the ``conan install --build=dependency`` will only build that dependency, and not the others, not sure what you mean here.


> Do you have any suggestions to improve this workflow?

Are you running your own Conan server? If your project and environment is important enough to be concerned about the binaries, it seems it is a "production" environment. For production environment it is extremely recommended, a best practice to run your own Conan server and store there your own binaries, to avoid re-building from source again and again, and to control adequately your production pipelines. Using package recipes from ConanCenter directly is not a recommended practice, they are changed over time, they will break your builds when the community pushes changes there with the latest Conan version you have still not upgraded to, or will occasionally introduce some bugs. 
Furthermore, for production, it is not recommended to rely on the auto-detected profile, but manage your profiles, settings, remotes, conf explicitly, and you can manage it with ``conan config install``. With that, having a model that manages the binaries at your will is zero extra effort.

**Comment by jzinn** [comment]
> > Every time a package fails to build, I make some changes and try again. I would like to essentially resume the previous conan install --build run, but that rebuilds all of the many dependencies.
> 
> You make some changes to the package recipe or source code? Then, it should work perfectly fine with `--build=missing`, because changes in a recipe or source code, produce a new `recipe_revision`, that by construction will not have binaries associated, so it will need to rebuild

Currently only updating dependency versions, but soon updating dependency recipes and patching dependency sources.

> > I've tried conan install --build the_one_that_failed. But, once I get that package to build, I then follow it up with conan remove "*" -f and start my conan install --build from scratch again.
> 
> I am not sure why you would do a `conan remove "*" -f` to remove all existing package binaries, including the one that you just built, and start from scratch, this doesn't make much sense.

If the dependency builds successfully, then Conan will continue to build other dependencies, at which time it will pull down pre-built binaries.  The `conan remove` is to remove any pre-built binaries that were downloaded.

> > Is there a way to do a conan install but target only one dependency to build (and do nothing for any other dependency)?
> 
> Yes, the `conan install --build=dependency` will only build that dependency, and not the others, not sure what you mean here.

Maybe I'm confused.  I thought Conan, after building `dependency`, would continue on installing any subsequent dependencies.

In any case, building only `dependency` doesn't actually help me, so I shouldn't have asked about this.

> > Do you have any suggestions to improve this workflow?
> 
> Are you running your own Conan server? If your project and environment is important enough to be concerned about the binaries, it seems it is a "production" environment. For production environment it is extremely recommended, a best practice to run your own Conan server and store there your own binaries, to avoid re-building from source again and again, and to control adequately your production pipelines.

Yes, we use Artifactory.  It's great that our production pipelines can reuse binaries that they built.  I just don't want to reuse them on my local machine.

I could probably set up something on our Artifactory for me to use privately, but I'd rather explore other options before trying that.

Should I run a local `conan_server` and have that be my only remote?

> Using package recipes from ConanCenter directly is not a recommended practice, they are changed over time, they will break your builds when the community pushes changes there with the latest Conan version you have still not upgraded to, or will occasionally introduce some bugs.

I'm glad you brought this up, because I have questions.

At the moment, my team uses two remotes: Artifactory first and ConanCenter second.  We forked [conan-io/conan-center-index](https://github.com/conan-io/conan-center-index), modified a few recipes, and pushed them to a user/channel in Artifactory.  Our code then depends on those modified packages by specifying the `dependency/version@user/channel`.

I assume the unmodified recipes that we use were uploaded to Artifactory (without user/channel), so the versions of the recipes we use are whatever ConanCenter had at the time when we copied them to Artifactory.  I'm not 100% sure how all this works.

My questions have to do with how to manage this over time.

Should we keep the fork of conan-center-index, periodically rebase, and then push recipes to Artifactory?

Should we not maintain the fork, but instead copy the recipes we need to our source code repo and periodically replace them with new versions from conan-center-index?

Should we use only the Artifactory remote and remove ConanCenter as a remote?

There are some ConanCenter recipes that don't have the versions we need.  What's the best way to work so that we can upstream minor version updates and other changes that make sense to upstream?

I did a rebase of the conan-center-index fork yesterday, and saw some of the potentially build breaking changes you mentioned.  For instance [this one](https://github.com/conan-io/conan-center-index/commit/27c938b90b33f1b751f25db09b9f14a006adc396) that updates for Conan v2 by removing `base_path` for patches.  I was wondering if that recipe still worked for Conan v1.

> Furthermore, for production, it is not recommended to rely on the auto-detected profile, but manage your profiles, settings, remotes, conf explicitly, and you can manage it with `conan config install`. With that, having a model that manages the binaries at your will is zero extra effort.

Our production pipelines do use custom profiles.  Locally, I am still using the default profile, but will soon write some new ones.

Thank you for your time.

**Comment by memsharded** [comment]
> Currently only updating dependency versions, but soon updating dependency recipes and patching dependency sources.

That should be fine. Just changing a ``requires = "zlib/1.2.11"`` to ``requires = "zlib/1.2.12"`` creates a new recipe revision that necessarily require building new binaries for that change. 

> If the dependency builds successfully, then Conan will continue to build other dependencies, at which time it will pull down pre-built binaries. The conan remove is to remove any pre-built binaries that were downloaded.

That really depends on the ``package_id_mode``. The default one is not that good for production, and it is recommended to change it. Conan 2.0 is changing it. So if some other package depends on the one that you changed, it will force a rebuild from sources for it, it will not download a pre-compiled binary.

In any case, doing a ``conan --build=something`` followed by a ``conan remove "*" -f`` doesn't make much sense, because you are also removing the package that you just built from source, not only the dependencies.

> Yes, we use Artifactory. It's great that our production pipelines can reuse binaries that they built. I just don't want to reuse them on my local machine.

That is a total surprise. Why would you want to build boost, opencv, or many other third party libraries as developer every time you need them? This is one of the major reasons Conan exists, and it is known to be a best practice in package management and devops for other technologies and languages. I agree on not using binaries from the internet, but not re-using your own binaries sounds like an anti-pattern.

> I could probably set up something on our Artifactory for me to use privately, but I'd rather explore other options before trying that.

Of course, there are different approaches on how binaries are managed in Artifactory. It is a best practice and totally recommended to have multiple repositories in Artifactory, and run promotions (copy) between repositories when we want to move our products through a pipeline. You can surely have a user repo if IT creates it, where you can store your own binaries, and typically Pull Requests will also create binaries in a "build" repo and not use the main "production" repo to put those binaries. Only when the PR is merged, it might make sense (if it is a fast-forward in code) to run a promotion copy of the packages from "build" repo to "production" repo.

> Should I run a local conan_server and have that be my only remote?

conan_server is not as performant as Artifactory, if you already have Artifactory, the best would be to use it


> My questions have to do with how to manage this over time.

> Should we keep the fork of conan-center-index, periodically rebase, and then push recipes to Artifactory?

Yes, if you have your custom modifications, patches, etc, this is the way to go. Not only push recipes, but also build the different  binary configurations that you will need and push them there. Make sure they are used by developers, in testing, in CI, etc. This is the best practice to guarantee robustness: the same artifacts are never rebuilt, but used everywhere, from development to release.

> Should we not maintain the fork, but instead copy the recipes we need to our source code repo and periodically replace them with new versions from conan-center-index?

It sounds easier to maintain the fork

> Should we use only the Artifactory remote and remove ConanCenter as a remote?

Yes, probably, once that you have the fork in place, and CI to build your own binaries for it, taking ownership of all your dependencies is not a huge effort, and it will give you full control over everything, more security, robustness and readiness to react quickly in the future if necessary.

> There are some ConanCenter recipes that don't have the versions we need. What's the best way to work so that we can upstream minor version updates and other changes that make sense to upstream?

Sure, if you want to contribute back changes that make sense to upstream, that would be great. You can request access and submit PRs to the ``conan-center-index`` repo. There might be some criteria to be met, for example, only release tags can be done, not any arbitrary release-candidate or alpha, beta tag, specially if the project is very active and creates tons of them, only official final releases are packaged.

> I did a rebase of the conan-center-index fork yesterday, and saw some of the potentially build breaking changes you mentioned. For instance [this one](https://github.com/conan-io/conan-center-index/commit/27c938b90b33f1b751f25db09b9f14a006adc396) that updates for Conan v2 by removing base_path for patches. I was wondering if that recipe still worked for Conan v1.

Sure, all PRs in conancenter are processed in Conan 1.X, for all configurations. Conan 2.0 is still not there yet, there is a parallel CI pipeline for it, but the main 1.X will stay for a while. It should work updating to latest Conan, probably some of the tools used are simplified now and can handle that.

**Comment by jzinn** [comment]
> That is a total surprise. Why would you want to build boost, opencv, or many other third party libraries as developer every time you need them? This is one of the major reasons Conan exists, and it is known to be a best practice in package management and devops for other technologies and languages. I agree on not using binaries from the internet, but not re-using your own binaries sounds like an anti-pattern.

I don't want to build them every time, I want to build them once.  It doesn't take that long, and only needs to happen when dependencies are updated.

Verifying that all dependencies build locally seems like a basic task, especially when the local build environment is unlikely to be identical to the build pipeline environment.  In my case, our remote binaries are built by an older CentOS, and my local machine is a newer Fedora.  (The compiler versions are the same.)  Maybe the solution is to create the `os.distro` subsetting when `os` is `Linux`, as the documentation mentions.  Until that configuration is in place, I would like a way to build locally and make sure the recipes work for both environments.

Over time as my confidence grows that everything is configured correctly, I might decide to use the remote binaries.  But to start with I trust local builds first.  I suppose we'd also need to set up a build pipeline using Fedora for there to be any remote binaries, unless developers push them.

Additionally for debugging purposes, the Conan documentation says to build a dependency when you want to step into the dependency's source.  Always building all packages locally makes this step unnecessary.

---

Assuming we use only our Artifactory as a remote and not ConanCenter, what do you recommend for setting user/channel values?  Should we mimic ConanCenter and not set user or channel, for both modified and unmodified recipes we've taken from conan-center-index?  Should we always set some values like mycorp/stable?

---

We have two teams working on two products, where team 2 depends on some packages produced by team 1.  I assume it's best for each team to have an independent Artifactory repo, with team 2 using both teams' remotes.  I also assume common dependencies should be satisfied by team 1's repo.

Should user/channel values play a role in managing this situation?  What about if team 2 wants to override a dependency, for instance to use BoringSSL instead of OpenSSL?

I don't have a specific enough question here, sorry, but do you have any guidance for this situation?

**Comment by memsharded** [comment]
> Assuming we use only our Artifactory as a remote and not ConanCenter, what do you recommend for setting user/channel values? Should we mimic ConanCenter and not set user or channel, for both modified and unmodified recipes we've taken from conan-center-index? Should we always set some values like mycorp/stable?

Yes, the recommendation is to have them immutable to ``mycompany/stable`` or something like that. It is possible to use team/division names if there is strong ownership of different packages

> We have two teams working on two products, where team 2 depends on some packages produced by team 1. I assume it's best for each team to have an independent Artifactory repo, with team 2 using both teams' remotes. I also assume common dependencies should be satisfied by team 1's repo.

I'd say that each team needs to have at least several repos:
- One "develop" repo, the team internal stable state of development, for developers of team only that expect to find the latest stable development binaries there
- One "builds" repo, with binaries built by CI for branches and pull-requests, so they can be tested, etc (lockfiles will be necessary for this to use the right binaries for a given PR)
- One "playground" repo, this is the only one devs have upload permissions, and they can use it for sharing a package temporarily with a colleague, etc
- One "share/release" repo, where they put binaries, typically copying them form the "develop" repo, to share with the other teams.

> BoringSSL instead of OpenSSL?

This override is not trivial, because if the packages have different name, they cannot be overriden, but it needs to actually change the ``requires = xxxx`` to point to the adequate package. There is no magic that allows to override arbitrary packages upstream for other packages with different names.

**Comment by jzinn** [comment]
Thanks so much for your advice.  That really helps.
