### ISSUE TITLE
Review requirements

### ISSUE THREAD

**Issue by bmgandre** [conan-io/conan#1245]
Conan has been including dependencies from time to time in new releases.
Version 0.22.2 has the following list of requirements:
```
PyJWT>=1.4.0, <1.5.0
requests>=2.7.0, <2.14.0
colorama>=0.3.3, <0.4.0
PyYAML>=3.11, <3.13.0
patch==1.16
fasteners>=0.14.1
six>=1.10.0
node-semver==0.1.1
distro>=1.0.2, <1.1.0
pylint==1.6.5
future==0.16.0
```
PyJWT has a new release, 1.5.0. Is 1.5.0 supported?
Why PyJWT requirement was specific about major version, and why fastners not?
Why patch, node-semver, pylint and future are so specific about the supported version?

Distros like Slackware and Arch Linux are creating packages of conan requirements.
```
https://slackbuilds.org/repository/14.2/development/conan/?search=conan
https://aur.archlinux.org/packages/conan/
```
These requirements can also be a dependence of other distro packages.
So, It is very important to maintain the requirements updated and track compatibility.
For example, currently pylint version in Slackware database is 1.5.2 <https://slackbuilds.org/repository/14.2/development/pylint/>. Is this version supported? About a newer pylint, version 1.7.1?

**Comment by memsharded** [comment]
Yes, you are right, it would be nice to review and update requirements.
The thing is that we have had some undesired behaviors, maybe some compatibility with Py2/Py3, I can't remember the issue, but that could be one reason that some versions are fixed or constrained.
We will have a look, thanks for pointing out!

**Comment by tivek** [comment]
Hi, I package Conan for Arch Linux. I see two potential issues at play here.

The first is tracking newer versions of Conan's dependencies and as far as I can see it is being taken care of organically. For instance, when packaging for Arch I make it a point to check if Conan's tests pass with newest versions of its dependencies. This usually means patching requirements.txt and then running Conan's test suite to see if everything is ok (for 0.22.2 see my [Travis CI](https://travis-ci.org/tivek/conan/builds/224285187) and [AppVeyor](https://ci.appveyor.com/project/tivek/conan/build/1.0.21) builds). If both the latest patched release and patched develop branches pass, I also send an upstream pull request to Conan so that I have less work for the next version of Conan :)

The second issue concerns Conan's tests which only check the latest and greatest dependencies available for a given Python version. Should we make sure that older versions of dependencies are also tested? Apart from the combinatorial explosion of testing time, building a matrix of all version combinations can be tricky. There are tools to mitigate this (tox, tox-matrix, tox-travis, appveyor-utils), still it will take quite a bit of tweaking to catch all the corner cases, eg. if there are combinations of dep versions that don't work at all with a given Python version. Which users on which OS configurations would benefit from this?

**Comment by tivek** [comment]
Out of all the dependencies, I've found at least PyJWT and requests follow semantic versioning:
https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.md
http://docs.python-requests.org/en/master/dev/philosophy/#semantic-versioning
This means that they do not intend to break their API or functionality within a single major verision

Previously I've had to patch Conan to accomodate new versions when Arch Linux introduced the latest versions of these two libraries. So, relaxing their requirements a bit would be a good start here.

I've made a branch to track what I have found out about the versioning policies of these and other Conan's dependencies:  https://github.com/tivek/conan/tree/requirements_cleanup

**Comment by tivek** [comment]
Btw. Conan 0.22 is currently patched on Arch to work with PyJWT up to 1.6.0 (Arch is at 1.5.0) and Pylint >=1.6.5 (Arch is on 1.7.1). A simple edit to requirements.txt usually does it. Just to be sure everything is ok I have Travis CI run tests on the patched Code. 

Still, it's a bit uncomfortable when yet another Arch update rolls in, and then Conan's requirements block the upgrade, so I jump in to make and test a patch, then worry if Travis CI tests maybe missed something... :D

**Comment by lasote** [comment]
Thanks @tivek, feel free to open a PR with the changes that you consider reasonable, you can comment on it the reasons for each case. I'm sure we can relax/update/downgrade some requirements without any problem.

**Comment by lasote** [comment]
Hi all, 

I've been reviewing why **node-semver**, **six**, **patch** and others are fixed versions, and they are actually the latest published version (no more versions have been published).

For the PyJWT and the requests, we have relaxed the constrictions, if ANY upgrade is needed please report in a new issue and we will be glad of review/update them.

It feels arbitrary to relax the dependencies that are pretty stalled on pypi.
