### ISSUE TITLE
Is there a way to extract sources of all dependencies? 

### ISSUE THREAD

**Issue by schmidjo82** [conan-io/conan#12463]
For some of our customers it is relevant to have a medium (DVD or stick) with all sources of third-party libraries used to build our product. 
Is there a way to extract all sources of the requirements of our product-build? 
I am already able to get a full list of dependencies by conan, but how can I get the sources?

**Comment by memsharded** [comment]
Hi @schmidjo82 

The first important point is to have the URLs of those sources modeled in ``conandata.yml``, otherwise it will not be possible, as it cannot be extracted from arbitrary Python code. Do you have the ``conandata.yml`` with that definition?

**Comment by schmidjo82** [comment]
Yes, I have these conandata.yml files. It was necessary to copy all recipes to our local repository and push the binary packages to our own artifactory space, since we need to be able to rebuild our products up to 10 years. 
We also push the sources to that artifactory space to be able to rebuild locally without IT problems ;-). 
I was already thinking about a way, where if try to fetch it from there. But I thought, conan should also be able to do this. I already tried to use the conan source command, but there, i can not specify a version. Maybe you guys have a better solution.

**Comment by memsharded** [comment]
Yes, ``conan source`` is only a "local" command, it needs to run in the repo where the ``conanfile.py`` is, it will not help with that.

Another quick question: do you need to store the sources tarball as downloaded, the uncompressed tarball, or in case you are applying any patches, the patched sources? Or it would be enough to store the patches themselves? Generated code in case some code generators are running?

Storing the patched sources might be very challenging without modifying recipes and doing an actual ``package()`` of those sources, because patches and code generation can actually happen in the ``build()`` step, so the only way would be to do a rebuild from source and package the sources.

While doing a copy of the tarballs as defined in ``conandata.yml`` would be pretty straightforward, can be elegantly done with a Conan 2.0 ``--deploy=mysources_download`` deployer, and in Conan 1.X we can probably automate it in some ``generate()`` method.

**Comment by memsharded** [comment]
Conan 2.0 beta9 is getting a new way of getting sources of all dependencies: https://github.com/conan-io/conan/pull/13003

This will allow forcing the ``source()`` method even for ``conan graph info`` command.
Gathering the sources will be straightforward with a custom new ``deployer`` that iterates ``dep.source_folder``. So I am closing this ticket as implemented for 2.0b9, please try when released, thanks!
