### ISSUE TITLE
[bug] conan lock does not include default user & channel

### ISSUE THREAD

**Issue by codetent** [conan-io/conan#12469]
Creating a lockfile using `conan lock create` ignores the user and channel if the `default_user` and `default_channel` attributes are set. All the other information (name, version) is taken from the conanfile.

My current workaround is reading the values using `conan inspect` from the recipe before and supplying it with the parameters `--user` and `--channel`. This works but seems to be a little bit inconvenient and increases the execution time because of the two additional commands.

### Environment Details (include every applicable attribute)
  * Conan version: 1.53.0
  * Python version: 3.8.8

### Steps to reproduce (Include if Applicable)
- conanfile.py with `default_channel` & `default_user` attributes
- call `conan lock create`

**Comment by memsharded** [comment]
Hi @codetent 

I have been having a look at this, and indeed the ``default_user`` and ``default_channel`` are not used at this point. Apparently they were designed to be used only to define the user and channel at ``export`` time (``conan export`` and ``conan create``), but they are not used when the ``conanfile.py`` is a consumer one, like this case (``conan lock create conanfile.py``) where the conanfile.py is a local one, not a package one.

I haven't been able to find a solution for this that wouldn't be breaking, but there is a potential workaround, the ``conan lock create`` command also admits the ``--user=<myuser> --channel=<mychannel>`` to define it, in a similar way than the ``conan install`` command.

I would also like to give a heads up regarding these attributes for 2.0. They have been removed in 2.0, because user/channel shouldn't be considered variables anymore, but more constant. The command ``conan copy`` has been removed, because it also breaks the promise of package immutability, and package promotions should be done doing copies of packages between one server repository and another server repository. Recipes will allow the ``user`` and ``channel`` attributes, in the same way as ``name`` and ``version``, to define user and channel.

**Comment by memsharded** [comment]
Closing this ticket as not planned, now that Conan 2 was released more than one year ago and it solves these issues. Please create new tickets for any questions you might have, thanks!
