### ISSUE TITLE
[bug] conan 1.54.0 incorrectly reports wrong requires

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#12487]
I'll try and explain, and then we can narrow down the test case if required.

I have a (draft) recipe in the works for VTK, it requires `proj/9.0.1` and `sqlite3/3.38.5`
Note that VTK's recipe requires an older sqlite3

I have a recipe up for review for proj, it requires `sqlite3/3.39.4`
Note that proj requires the most recent sqlite3.

I am using the latest CCI recipe for QT it requires `sqlite3/3.39.2`
Note that this is a different sqlite3 version to the others, so we'll get a conflict.

My simple test recipe requires vtk, proj, and QT.
`requires = [ "qt/6.3.1", "vtk/9.1.0" ]`

I run this install command in my test recipe folder, with a few overrides to work around some irrelevant version issues:
`conan install . -if build --require-override openal/1.22.2 --require-override libffi/3.4.3`

The key part of the message I get is:
`'proj/9.0.1' requires 'sqlite3/3.38.5' while 'qt/6.3.1' requires 'sqlite3/3.39.2'.`
Full message below.

Note that `test <-- vtk <-- proj`
Technically, proj requires sqlite3/3.39.4.
It is VTK's recipe that is overriding proj's requirement to an older sqlite/3.38.5 (and requires it for itself).
But the error message reports that it is proj's fault.
This was very confusing to debug!

```
WARN: qt/6.3.1: requirement openal/1.22.1 overridden by test/1.0.0 to openal/1.22.2 
WARN: glib/2.73.3: requirement zlib/1.2.13 overridden by harfbuzz/4.4.1 to zlib/1.2.12 
WARN: glib/2.73.3: requirement pcre2/10.40 overridden by harfbuzz/4.4.1 to pcre2/10.37 
WARN: libxml2/2.9.14: requirement zlib/1.2.13 overridden by xkbcommon/1.4.1 to zlib/1.2.12 
WARN: wayland/1.20.0: requirement libffi/3.4.2 overridden by xkbcommon/1.4.1 to libffi/3.4.3 
WARN: vtk/9.1.0: requirement qt/6.2.4 overridden by test/1.0.0 to qt/6.3.1 
ERROR: Conflict in proj/9.0.1:
    'proj/9.0.1' requires 'sqlite3/3.38.5' while 'qt/6.3.1' requires 'sqlite3/3.39.2'.
    To fix this conflict you need to override the package 'sqlite3' in your root package.
```

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu Una / Mint 20.3
  * Conan version: 1.54.0
  * Python version: 3.8.10

**Comment by memsharded** [comment]
Hi @paulharris 

> But the error message reports that it is proj's fault.
This was very confusing to debug!

Yes, I totally agree on that. There is an implementation issue, and it is that Conan doesn't have the information internally to know the exact culprits of the conflict, and it is quite challenging to distribute it, because it needs re-exploring the dependency graph, and it was quite a large effort for this.

We have tried to improve over this in 2.0, and for example it will be possible to print full dependency graph with conflicts, so it is possible to visualize the potential origins for the conflicts. I will check that these error messages are at least better in 2.0, thanks very much for reporting!

**Comment by AbrilRBS** [comment]
Closing as solved in Conan 2, which has vastly superior error reporting for these kind of cases than Conan 1, in which as mentioned, was not feasible to implement features like this easily
