### ISSUE TITLE
[question] How do I call deploy() for a local conanfile.py?

### ISSUE THREAD

**Issue by stas-neverov** [conan-io/conan#12482]
Hi,

Is there a convenient way to call the `deploy()` method for a local conanfile.py?

When I develop a `package()` method I can run `conan package .` and check the result in a local folder. I'd like to do the same testing when developing a `deploy()` method. As far as I know, `deploy()` is only called by `conan install`. And `conan install .` for the local conanfile.py installs the dependencies and so it doesn't call the `deploy()` method for the local conanfile.py, which makes sense. Do we need some package development command like `conan deploy .` to test the `deploy()`?

My current workaround is to create the package and then deploy it:
```shell
conan create .
conan install <ref>
```

Thanks!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @stas-neverov 

I am afraid it is not possible to call ``deploy()`` for a local ``conanfile.py``, because it only knows how to operate from a created package, but not from local binaries. It is not only about the existence of a ``conan deploy`` command, the challenge here is that locally, the binaries of the current package could be in a completely different location, there is no guarantee they will be in the same relative path as when the package is in the cache.

It seems that you can highly speed up your workaround with ``conan export-pkg`` instead. If you were calling ``conan package`` locally, you mean that you already did a local build, so no need to rebuild from scratch to test the deploy, but you can put the local built binaries in the cache with ``conan export-pkg``, then run the ``conan install``.

As a heads up of Conan 2.0, which is coming soon, these are some of the changes related to the ``deploy()``:
- The ``deploy()`` and ``imports()`` method are removed in 2.0
- The ``conan package`` command is removed, it is replaced by ``conan export-pkg`` 
- To replace some local ``imports``, the approach would be to do a explicit ``copy()`` in the ``generate()`` method
- In Conan 2.0 there are new ``deployer`` extensions, which are in the Conan cache, can be installed with ``conan config install`` and called over any package with ``--deploy=mydeploy``

These deployers might be coded in a way that know how to handle a local package too, but that still sounds a bit tricky, so probably going with the ``conan export-pkg`` might be the best approach.

**Comment by stas-neverov** [comment]
@memsharded, thanks for the quick response!
