### ISSUE TITLE
Add contributing packages to README

### ISSUE THREAD

**Issue by willyd** [conan-io/conan#125]
Hi,

I recently discovered conan and would be interested in contributing some conanfile.py for a few OSS packages I use. Is there an official conan-packages repo we can fork? What is the current way of contributing new conanfile.py files?

Thanks 

P.S. Thanks for the good work. This tool seems to address a good nummber of issues I have with packaging C++ dependencies on Windows.

**Comment by memsharded** [comment]
Hi Guillaume,

You are welcome! Thanks to you for your interest.

Conanfiles.py are python scripts, "recipes" that explain how to build some source code and create binaries from them, how to upload both the recipes and the binaries, and also how to consume such package from another project. There is no such conan-packages repo, because storing binaries in repos would be a bad thing. Instead there are "remotes", i.e. conan servers. We run a conan server in conan.io, that can be used for free.

The bare minimum to contribute a conanfile.py would be:
- Create a folder and create such conanfile.py inside
- ``conan export your_user/channel``. This would register your conanfile in your local computer conan storage (your ~/.conan/data folder). It can be used from there to consume such package, without contributing it, uploading or sharing it.
- ``conan upload YourLib/version@your_user/channel``. This will upload from your local computer conan storage to the conan.io remote, **just the conanfile.py**, but not possible binaries you had built locally. 

If you want to contribute binaries too, you could do ``conan upload YourLib/version@your_user/channel --all``. You can upload it to your own remote too, if you want to run it in your premises, without requiring connection to the conan.io server.

In practice, it is necessary to check that your package is properly created and configured, and thus the ``conan test`` functionality is provided. You can add a ``test`` folder besides your main **conanfile.py** file, that will contain a small project actually consuming and linking against your package, with its own **conanfile.py**. This command helps to create and test locally new packages before uploading and sharing them.

It is also typical, if you want to build many different configurations, to use a small python script (just python, nothing related to conan, it could be bat file or shell script), to launch as many packages as you want. You could check: https://github.com/memsharded/conan-zmqcpp/blob/master/build.py

I recommend reading and running (it is tutorial like, you could follow it step by step), this section from the docs: http://docs.conan.io/en/latest/packaging.html. Write me if you find any problem while running it.

I am closing this issue, I would say that no special action is needed, just tell me (for regular doubts, questions, etc, info@conan.io can be also used), if you have any further question or doubt, or feel free to re-open the issue or creating a new one for other bugs, issues, and features requests. Cheers!

**Comment by willyd** [comment]
Hi @memsharded, thanks for the detailed answer. However, my question was more about a central github repo where one could put his conanfile.py and other files. I see that you and @lasote have some packages in your own repos but I was just wondering if having a central repository or organization for all the package recipes would be useful. Maybe it goes against the distributed nature of the project but as long as you can have many of them I guess it is ok. Thanks!

**Comment by memsharded** [comment]
I'd say it is not about the distributed nature, but about scale and management. Every package (conanfile.py) could have their own issues, quite unrelated to issues from other packages, and managed by different people. Also, some kind of management should be done on such repo, with maintainers accepting PRs from contributors, and so on, so they might have to wait until management. Also, some packages require extra files, not just the conanfile.py, in fact, some packages can upload the whole source code (and that can be also a lot of Mbs to be handled conveniently by a repo) to a remote. Thus the repo should have an adequate layout that avoids package name collisions, somewhat replicating the conan local storage layout, I guess. Moreover, some package conanfiles will be inside the original sources repos, especially when developers also use conan to handle their own dependencies. Such conanfiles doesn't make a lot of sense in a central repository.

So I think the best way is letting each package creator handle their own repos.  The reference of all contributed conanfiles could be the "search" utility (both in web and in command line), probably it still has to improve a lot, adding some more meta-information about the packages like description, keywords, etc.

What do you think? :)
