### ISSUE TITLE
[bug] cmake generator ignores private requirements if build profile is set

### ISSUE THREAD

**Issue by db4** [conan-io/conan#12500]
### Environment Details (include every applicable attribute)
  * Conan version: 1.54.0

Consider the following test recipe:
```
from conans import ConanFile

class TestConan(ConanFile):
    generators = "cmake"

    def requirements(self):
        self.requires("zlib/1.2.13", private=True)
```
Let's try to generate `conanbuildinfo.cmake` from it:
```
conan install .
```
The resulting `conanbuildinfo.cmake` contains something like
```
#################
###  ZLIB
#################
set(CONAN_ZLIB_ROOT "D:/.conan/data/zlib/1.2.13/_/_/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7")
set(CONAN_INCLUDE_DIRS_ZLIB "D:/.conan/data/zlib/1.2.13/_/_/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/include")
set(CONAN_LIB_DIRS_ZLIB "D:/.conan/data/zlib/1.2.13/_/_/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/lib")
...
```
OK, good. Now explicitly set build profile:
```
conan install -pr:b=default .
```
and look into `conanbuildinfo.cmake`. No ZLIB settings! Why?

**Comment by czoido** [comment]
Hi @db4,

Thanks for the question. That's probably happening because you are marking your requirement as private and when using the two profiles approach it's correctly not generating that info because of that. A couple of comments:
- Please check the docs about [setting the requires as private](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#requires) because the use is discouraged unless some specific cases.
- I would recommend you to start using the new CMake tools: `CMakeToolchain` and `CMakeDeps`  instead the `cmake` generator that is going to disappear in Conan 2.0. Those are more advanced and provide you the ability to use Conan more transparently without having to change your _CMakeLists.txt_

**Comment by db4** [comment]
Hi @czoido. Thanks for the answer. Yes, this happens only for private requirements and yes, I need some requirements to be private. If something doesn't work properly under some specific conditions (while it's supposed to) isn't it called a bug? I hit this in my old 1.x recipes that use `cmake` generator and `self.user_info` and immediate switch to CMakeDeps and Conan 2.0 unfortunately is not an option.

**Comment by memsharded** [comment]
Closing this ticket as outdated (legacy ``cmake`` generator removed in Conan 2)
