### ISSUE TITLE
Does tool packages cpp_info propagate into package build helpers

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#12512]
Conan 1.54
OS: Linux

I have a tool package with defines like this:
```
class MyTool(ConanFile):
    ....
    def package_info(self):
        ...
        self.cpp_info.defines += ["MYDEFINE1", "MYDEFINE2"]
        ...
```

I have a consumer package that include the tool package and another package like this:
```
class MyConsumer(ConanFile):
    ...
    requires = [("MyPackage/1.0.0")]
    ...
    tool_requires = "MyTool/1.0.0"
    ...
```

Then I have MyPackage built on behalf of the consumer package:
```
class MyPackage(ConanFile):
...
    def build(self):
        cmake = CMake(self)
        cmake.build()
...
```
I would expect `MYDEFINEx` to be add as preprocessor defines in MyPackage CMake environment when building, but it does not seem to be.

Should it be, and is it simply me who made some silly mistake?
If not, then how can I make a define in my tools package which will propagate to all packages and their build helpers?

Rgds
Klaus

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

I am afraid it doesn't work that way. ``tool_requires`` do not provide ``cpp_info``, because that is dedicated mostly to libraries, with ``includedirs``, ``libdirs``, etc. The information from ``cpp_info`` ends for example in ``xxx-config.cmake`` files generated by ``CMakeDeps``.

But ``tool_requires`` is oriented to use tools and executables in the "build" context, so it cannot really provide information via ``cpp_info``, which is "host" context. There could be other mechanisms for this:

- Defining a ``mytool_toolchain.cmake`` file and pass this toolchain file as ``tools.cmake.cmaketoolchain:user_toolchain`` conf, via ``self.conf_info`` in the ``package_info()`` method
- Defining directly ``tools.build:defines`` flags in ``self.conf_info``
- Defining environment variables (doesn't seem the best for this use case), and letting the consumer read them from the environment.

I would start trying any of the first two approaches, please have a look and let me know.

**Comment by klausholstjacobsen** [comment]
If there only were official env variables that would make cmake use it like CC, CXX or LD.
So what you're saying is that this cpp_info would also not work with the autotools helper? Damn, I was under the impression that it worked there.

regarding the custon toolchain approach there are challenges. I real life I wish to cross build protobuf/3.21.1 from conan center with the cross compiler provided by the tools package. In order to make that happen I need to define "_QNX_SOURCE" because I'm cross compiling for the qnx platform. I'm affraId that providing my own toolchain file will break the build because the protobuf recipe also does its custom cmake stuff. But I will give it a go.

//Klaus

**Comment by klausholstjacobsen** [comment]
The solution was as simple as can be:
In the toolchain package recipe: `self.env_info.CXXFLAGS = "... -DMyDefine1 -DMyDefine2"`

Works like a charm!

I must admit I find it very difficult to understand the conan cmake intergration.
Just to name a few of my confusions:
What are cmake helper and generators and in which situations are they to be used. How do the various helpers and generator interact.
What variables and where can I set them to influence how these helper and generator work when build software.
How can i influence a package from conan center using cmake to build.
On top of that we have the whole build context vs host context etc.

The documentation is detailed and extensive, but sometimes it feels like I'm getting random small pieces to my puzzle on different pages of the docuemntation, making if difficult to put together the whole puzzle.

But I learn a bit every day. :-)

Thanks for your quick responses....again.

Rgds
Klaus
