### ISSUE TITLE
[question] CMake specifics polluting cpp_info

### ISSUE THREAD

**Issue by stevn** [conan-io/conan#12534]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

It seems to me that most package recipes are now setting many cmake generator specific entries on the self.cpp_info. This seems wrong from a conceptual perspective to me. Shouldn't the cpp_info only hold information about the libraries, directories and flags in a generic way?

The package creator cannot know which build system the package consumer will be using, so setting cmake specifics on the cpp_info for the case when the package consumer does use cmake feels very weird to me.

For example: self.cpp_info.set_property("cmake_find_mode", "both")

Why should the package creator care which cmake_find_mode is used by the consumer? Shouldn't the package consumer decide which cmake_find_mode is used? And if the package consumer uses meson or something else, this setting is useless anyway?

**Comment by memsharded** [comment]
Hi @stevn 

> It seems to me that most package recipes are now setting many cmake generator specific entries on the self.cpp_info. This seems wrong from a conceptual perspective to me. Shouldn't the cpp_info only hold information about the libraries, directories and flags in a generic way?

I wish it was that way. But the CMake ecosystem is sometimes very inconsistent, so in order to be able to generate downstream for the consumers, the equivalent ``xxxx-config.cmake`` files that they would expect, it is necessary to add that information. 

All this information shouldn't be necessary at all for your own projects, it is just a necessary thing for the open source ecosystem and ConanCenter recipes.

> For example: self.cpp_info.set_property("cmake_find_mode", "both")

This, applied for a open source library like "curl", for example, means: Hey there are users out there that they will be expecting to use ``libcurl-config.cmake`` but there are also other users that expect to have the ``findcurl.cmake``, so lets generate both so they will have what they want. Because the thing is that the consumer recipe writer probably doesn't care which one is using the ``CMakeLists.txt`` of the library, so that is a detail that they don't want to reflect. And yes, if the consumer is using a different build system, this is not used. 

But I totally understand your question, and we are reviewing now CMakeDeps, so we will take it into account.

**Comment by memsharded** [comment]
@czoido will develop some consumer-side (``CMakeDeps``) selection and customization of dependencies information, so it is less necessary to specify it in the source repos.

**Comment by SpaceIm** [comment]
> Why should the package creator care which cmake_find_mode is used by the consumer? Shouldn't the package consumer decide which cmake_find_mode is used? And if the package consumer uses meson or something else, this setting is useless anyway?

Because package (not consumer) knows what should be set to properly mimic official interface build files of library. If consumer uses Meson, it won't use CMakeDeps, so cmake_find_mode doesn't matter.
