### ISSUE TITLE
[feature] conan info --raw

### ISSUE THREAD

**Issue by naggerx** [conan-io/conan#12544]
Just like "conan inspect --raw" I would really like to see a "conan info --raw".

We repeatedly have to query the package_path of a package in various scripts.

--raw should accept any attribute from --only, additionally:
* Print just the value of the requested attribute
* Automatically add "--package-filter <same_ref>" (only output direct infos from 'path_or_reference')
* Automatically add '--paths', when requesting an attribute which requires the '--paths' option
* Suppress any other conan warning or hints
* Combination with most (all of?) the other options can be disallowed

So instead of: 
`conan info zlib/1.2.12@user/stable --paths --only package_folder --package-filter 'zlib/*' | tr '\n' ' ' | tr -s ' ' | cut -d ' ' -f 3`

Just use:
`conan info zlib/1.2.12@user/stable --raw package_folder`

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @naggerx 

The ``--raw`` argument has a different meaning, it means, "do not mix or add Conan status or info messages to the stdout".
This argument has been dropped in Conan 2.0, because it is no longer necessary, as all the status messages will be sent to ``stderr``, and only the final information will be sent to ``stdout``.

Also for the purpose of obtaining paths, which seems exactly your use case, Conan 2.0 has developed a new ``conan cache path <ref>`` command for exactly this. It would be great if you could have a look, try it, and give feedback. Thanks!

**Comment by memsharded** [comment]
all the output has been redesigned in conan 2.0:

- all the information messages go to stderr, so it doesn't pollute the ``stdout``
- There is a new concept of formatters ``--format=json``, still outputing to ``stdout``, can use stdout redirect to file
- The ``--raw`` argument has been dropped from all commands, no longer necessary

So closing this as solved in 2.0 released betas

**Comment by Adnn** [comment]
@memsharded I am reaching this issue as a search result regarding the removal of `--raw` from Conan 2.

I understand that requested information is not mixed with status anymore. But `--raw` also allowed `conan inspect` to query the value for a single attribute. Is it still feasible in Conan 2?

**Comment by memsharded** [comment]
It is still possible to list just 1 attribute:
```bash
$ conan graph info --requires=zlib/1.2.13 --package-filter=zlib/* --filter=license > license.txt
```

But the stdout will now contain more information, like the full recipe revision for the package in the graph
```
$ cat license.txt
zlib/1.2.13#97d5730b529b4224045fe7090592d4c1:
  ref: zlib/1.2.13#97d5730b529b4224045fe7090592d4c1
  license: Zlib
```
For non output-trivial commands (like ``conan cache path``), the text-format to stdout is not meant to be automatically used in CI, because it doesn't make sense that it is just a printe value, and it needs more context. The recommendation would be to use the ``--format=json`` output, and if you need some easy extraction from the resulting json, the use ``jq``.
