### ISSUE TITLE
Conan search when uploading

### ISSUE THREAD

**Issue by gsemet** [conan-io/conan#12563]
Hello,

When I upload large packages, it seems like `conan search` "finds" this not-so-ready package, and `conan download` or `conan install` fails (rightfully) to retrieve it.

Is there a way to tell this package is being upload, do not take it yet ?

Thanks

**Comment by memsharded** [comment]
Hi @gsemet 

I am afraid it is not. We are studying some possibilities to reduce this impact, but that might involved work in the server, and that always take a more lot of time.

If possible, this can be reduced by a 2 step process, automated a bit in the server, first upload to an "upload" repo, which is write-only, and only when it finished, do a copy in the server (which is very fast, because it doesn't copy files because of file de-duplication) to the repo that others do ``search`` and ``install``

**Comment by memsharded** [comment]
Probably the issue to track is https://github.com/conan-io/conan/issues/6870, and we could close this one as duplicate?

**Comment by AbrilRBS** [comment]
Closing as duplicate, thanks a lot for taking the time to originally report the issue, we appreciate it :)
