### ISSUE TITLE
[question] cmake configure prepends Visual Studio devenv to PATH?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#12566]
Hi,

I have an issue, we are using Code Coverage, which means that ths coverage compiler must be the first on PATH when configure + build is executed. However I've noticed that when running with "Ninja", Conan prelaunches (quite properly) the development console. However it appears that it is forcefully prepended to PATH, which means that our PATH setup (which puts the coverage compiler to the front) gets ruined, as after running the development console, cl.exe gets to be the first compiler on PATH.

Any idea how to overcome this?
Thanks,

**Comment by jcar87** [comment]
HI @harsszegi  - thanks for raising this question.

From what you are saying, I'm assuming:
* You are building a project that uses CMake, but specifying Ninja as the CMake generator
* This coverage compiler is _also_ called `cl.exe`, but it is not the one provided by Microsoft.

If you are using CMake you could probably nudge CMake in the direction of finding a different compiler, for example:
* `CC` and `CXX` environment variables being defined - This could also be defined in the `[buildenv]` section if you have a Conan profile that is specific to code coverage.
* Point the `CMakeToolchain` Conan generator to a user-defined toolchain that will be side-loaded by the Conan generated one (docs [here](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#using-a-custom-toolchain-file)) - This custom user toolchain would have to define `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER`  to point to the coverage compiler.
* If this is limited to a single recipe, you could implement in the `generate()` method logic to cause Conan to define `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` in `conantoolchain.cmake` as generated by Conan.

**Comment by harsszegi** [comment]
Thanks @jcar87,
I'll try the CMAKE_C_COMPILER / CMAKE_CXX_COMPILER first (we have CXX/CC set in profiles already)

**Comment by petermbauer** [comment]
Same issue here with the Bullseye Coverage tool. I tried to use `conan install -e PATH=[<BULLSEYEBIN>]` but this is also overridden by the `vcvarsall.bat` executed directly before CMake is launched.
The drawback of setting CC/CXX or the CXX_COMPILER variables is that this needs to be implemented in the conanfile and that some logic needs to be implemented for determining the compiler executable name, e.g. `cl.exe`, while setting the `PATH` only does not require this specific information.

**Comment by memsharded** [comment]
Hi @petermbauer 

Sorry, the original post didn't include much details about their integration, so if you could provide it, that would be better:
- What integrations are you using? ``CMakeToolchain``?
- You should also probably use the ``[buildenv]`` definition of environment instead of the ``-e`` cli arg, and then the ``VirtualBuildEnv`` generator
- Conan 1.55 defined also a new conf ``compiler_executables`` that will inject CMAKE_CXX_COMPILER into ``CMakeToolchain``, that might help?

If you can provide a recipe or something that we can reproduce, that would help

**Comment by petermbauer** [comment]
Hi @memsharded 

The use-case is quite easy to describe i think. I could switch to any implementation variant if it helps.

The "Bullseye Coverage" tool and probably other similar tools work like this: It provides "compiler interceptor" executables like `cl.exe`, `gcc`, ... with its installation which are supposed to be used instead of the "original" compiler executable so they can instrument the produced binaries for recording which parts of the code have actually been executed when running e.g. the unittests.
So technically it would be sufficient to prepend the `bin` folder of the "Bullseye Coverage" installation to the `PATH` so that the respective build tool finds the "compiler interceptor" instead of the original compiler executable and uses it for the build.

As already mentioned, i would like to avoid implementing/maintaining a mapping from the `settings.compiler` to the actual compiler exectuable name (e.g. "Visual Studio" -> "cl.exe", ...) and only replace the path of the executable.

thx,
Peter
