### ISSUE TITLE
I am trying to convert 1 particular component to conan 2.0, but I am facing some kind of issues.

### ISSUE THREAD

**Issue by disha123-bm** [conan-io/conan#12579]
These 3 are the errors I am getting

*ERROR: Error reading 'conan_profiles/x86_64' profile: ConfigParser: Unrecognized field 'build_requires'

*ERROR: Error loading conanfile at '/home/dibm/bird_routing/conanfile.py': Unable to load conanfile in /home/dibm/bird_routing/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dibm/bird_routing/conanfile.py", line 1, in <module>
    from conan import ConanFile, tools, AutoToolsBuildEnvironment, load
ImportError: cannot import name 'AutoToolsBuildEnvironment' from 'conan' (/home/dibm/.local/lib/python3.7/site-packages/conan/__init__.py)

*ERROR: Error reading 'conan_profiles/x86_64' profile: ConfigParser: Unrecognized field 'env'

**Comment by memsharded** [comment]
Hi @disha123-bm 

Conan 2.0 has removed some legacy tools. Here is the migration guide to help you prepare for 2.0: https://docs.conan.io/en/latest/conan_v2.html
- AutotoolsBuildEnvironment has been removed. You need to update to the new tools in: https://docs.conan.io/en/latest/reference/conanfile/tools.html
- The environment management has changed, you need to use ``[buildenv]`` and ``[runenv]``: https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#removed-self-env-info
- The ``[build_requires]`` has been replaced by ``[tool_requires]``: https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#requirements

All those changes, you can do them in 1.X, they are already there to allow an easier upgrade to 2.0.

**Comment by disha123-bm** [comment]
What changes we need to do in the set_version() method in conan 2.0?

* Exporting the recipe
ERROR: conanfile.py: Error in set_version() method, line 24
        self.version = "%s_%s" % (git.get_branch(), git.get_revision())
        AttributeError: 'Git' object has no attribute 'get_branch'

*ERROR: Invalid package version 'git.get_branch()_git.get_revision()'

**Comment by memsharded** [comment]
These are the docs for the new ``Git`` object: https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html

It doesn't contain a ``get_branch()`` helper, and the replacement for ``get_revision()`` would be ``get_commit()``. You have the ``git.run(...)`` helper to run any git command that you want, you could do it to get the branch.


I would like to comment, however, that maybe using the branch and commit as package version, depending on the flow, would not be the best approach. Because in order to use that package, it is necessary to change the ``requires`` of the downstream consumer packages, start using ``overrides`` or similar things. There are other possibilities that would require less effort, for example, if the same version is kept, but the package is uploaded to another repository in the server, and lockfiles are used (lockfiles will be greatly simplified and more powerful in 2.0) then it is possible to create, test and promote packages with the same version in a more automated way. Not saying that what you are doing is wrong at all, it might perfect for your needs and use case. Just something to have in mind if at some point you struggle with something related to this.

**Comment by memsharded** [comment]
Closing this ticket as solved and staled, but don't hesitate to create new tickets if there are any further questions.
