### ISSUE TITLE
[question] How to update a specific dependency in your lock file?

### ISSUE THREAD

**Issue by emricolSICKAG** [conan-io/conan#12582]
Scenario: 
- You are working on a release and you have to fix a bug in a single direct dependency. 
- You update the bug fixed version in your conan file.
- Now I want to update that dependency in my lock file without updating all other transitive dependencies.

There is a workflow in the [documentation](https://docs.conan.io/en/latest/versioning/lockfiles/ci.html#products-pipeline) solving some aspects but it has limitations. The workflow does not work if you have fixed direct dependencies instead of version ranges and you have to create your snapshots of your subgraphs before new versions are deployed.

Is it possible to update a single dependency in a lock file?

Thank you in advance

Best regards,
Oliver

**Comment by memsharded** [comment]
Hi @OEmrich 

I am afraid that in Conan 1.X this might be very challenging, and also likely to break something. Lockfiles in 1.X store the full dependency graph, so it would be necessary to know which dependency needs to be changed, and replace it. I wouldn't recommend it.

Conan 2.0 lockfiles are a very different story. They even contain a ``conan lock add <ref>``, so you can manually add a dependency to your lockfile, though it might not be even necessary, because the lockfile can be directly passed to a ``conan create`` and it will automatically add the created new reference to update the lockfile, that can be later used by downstream consumers without issues.

**Comment by emricolSICKAG** [comment]
@memsharded Thank you for your response. Your reaction time is amazing.

I think I m looking forward for conan 2.0 then.
