### ISSUE TITLE
What changes we need to do in the set_version() method in conan 2.0?

### ISSUE THREAD

**Issue by disha123-bm** [conan-io/conan#12592]
*Exporting the recipe
ERROR: conanfile.py: Error in set_version() method, line 24
self.version = "%s_%s" % (git.get_branch(), git.get_revision())
AttributeError: 'Git' object has no attribute 'get_branch'

*ERROR: Invalid package version 'git.get_branch()_git.get_revision()'

**Comment by czoido** [comment]
Hi @disha123-bm,

Thanks for the question. It's failing because you are using the `Git` implementation from `conans.tools` (notice the `s` in conan`s`) for 2.0 only the tools under `conan.tools` will work. You can find them all here: https://docs.conan.io/en/latest/reference/conanfile/tools.html

You can find the new implementation for the Git helper [here](https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html).

It's worth also mentioning that we have a Conan migration guide to 2.0 in the conan documentation: https://docs.conan.io/en/latest/conan_v2.html

Please check that and ping us again if you have any more questions on how it works.

**Comment by memsharded** [comment]
Closing this question as responded, but please re-open or create a new ticket if there are any further issues. Thanks!
