### ISSUE TITLE
[question] Is it possible to install the lower border of your version ranges?

### ISSUE THREAD

**Issue by emricolSICKAG** [conan-io/conan#12593]
If I'm using version ranges in my conan file and install my dependencies the latest compatible versions will be used or at least I can force it with --update.
Is it somehow possible to achieve the opposite and use the lowest compatible versions in your version ranges to make sure the lowest borders are set correctly?

The only workaround we came up with was duplicating all requires and setting the lowest version as fixed version. The different requires can now be switched with an option.

Best Regards

Oliver

**Comment by memsharded** [comment]
Hi @OEmrich 

I am afraid it is not possible, and it would be almost impossible to do it, because Conan dependency resolution algorithm highly depend on this behavior. Even the greatly simplified lockfiles in 2.0 rely on the assumption that version ranges resolve to latest (in the same way revisions always resolve to latest too).

We decided on this approach based on other package managers, and also the increasing push towards continuous updates and securities. Staying in the lower bound of a range basically defies the whole purpose of defining a range and it is equivalent to pinning the lower bound. Note that in Conan version range resolution is not full joint-compatibility of all the defined ranges, because that is a SAT problem, known to be NP hard, and we have estimated that in practice (given the cost of fetching recipes, loading the python files and interpreting them, evaluating, etc) it would be intractable in practice. So version-ranges resolution is "greedy" in its most part. It can do some partial joint resolution over diamond structures, but definitely not full one.

**Comment by emricolSICKAG** [comment]
Hi @memsharded 
for this use case the behavior of the version resolution does not have to be changed.
This is just a feature to verify the ranges of direct dependencies. The greedy default behavior is totally fine.
All I want to check is if the lower borders that I set are actually compatible with my code before I release my component. As a component developer I guarantee that my component is compatible with the lower borders but there is no easy possibility to actually check that.
Most likely I'm underestimating the complexity but wouldn't it be enough to find the lowest border for my direct dependencies and write them to a lock file or pass them as new input as fixed requires to the normal and greedy version resolution?
If now new version conflicts with transitive dependencies are found I know that my lower borders are wrong and that I have to fix them.

**Comment by memsharded** [comment]
Oh I see.

> Most likely I'm underestimating the complexity but wouldn't it be enough to find the lowest border for my direct dependencies and write them to a lock file or pass them as new input as fixed requires to the normal and greedy version resolution?

Yes, I think for that purpose, the new lockfiles of 2.0 might be a possible approach, as they will allow manual definition, and can be used to force certain versions within declared ranges. If collecting the ranges from the component being managed at that point is good enough (assuming that the transitive dependencies have already been checked by their respective components), then it could be more doable, indeed.  Also, the whole of it could be implemented in a custom command (https://docs.conan.io/en/2.0/reference/extensions/custom_commands.html)

In Conan 1.X it can be super challenging, because lockfiles cannot be defined or managed this way. There is a command line ``--require-overrides`` argument, but that is also a bit tricky.

**Comment by emricolSICKAG** [comment]
Thank you for your answers and the hint with the custom commands. Maybe I can implement something that fits our needs.

Best Regards

Oliver
