### ISSUE TITLE
Getting Started Question

### ISSUE THREAD

**Issue by KurtWAndrews** [conan-io/conan#12590]
Hello, 

I'm trying to get started using Conan for package management of a C++ development project using CMake and developing on Mac OS Ventura.  I do a lot of Python development for as part of my job and always create a virtualenv inside each project to provide the python environment.  This is the first time I've tried to use an application developed with python to manage package dependencies for a C++ project.  The installation instructions for Conan in the getting started guide seem to be saying that the prefered method for installing Conan is using pip in a virtualenv.  What I need help with is understanding whether I should install Conan in a global virtualenv or in separate virtualenvs for each C++ project.

The version of python that I'm using is Python 3.10.0.

Thanks,

Kurt

**Comment by memsharded** [comment]
Hi @KurtWAndrews 

You are fine with just one virtualenv for Conan, unless you would like to manage simultaneously several Conan versions (like to prepare an upgrade), in that case, indeed using one virtualenv for each Conan version makes sense (pipx also good).

Then, the Conan cache, containing all Conan configuration, files and package binaries cache, is by default in ``<userhome>/.conan``. This cache can be used by multiple projects, as long as they don't operate concurrently (the cache is not concurrent safe), because the cache can store different versions and also different flavors (shared/static, release/debug, different architectures, etc), in the cache without conflict, each different version is in a different folder, and each different binary is inside another different folder too. So multiple projects can be using different versions of the same library (or the same version too, of course), from the Conan cache.

If there are projects that are very different, so they have different configurations (use different remote server, different custom settings, different conf, etc., it is possible to define a different cache for different projects with the CONAN_USER_HOME env-var (for 1.X) and CONAN_HOME or .conanrc file in the project (for Conan 2.0)

**Comment by KurtWAndrews** [comment]
Thanks for the education and the quick response.
