### ISSUE TITLE
[bug] Faulty edge comparison in graph.py

### ISSUE THREAD

**Issue by frank-schmidtner** [conan-io/conan#12621]
I stumbled across this [comparison operator definition](https://github.com/conan-io/conan/blob/develop/conans/client/graph/graph.py#L241) while debugging. The comparison is
```
def __eq__(self, other):
   return self.src == self.src and self.dst == other.dst
```
but should be
```
def __eq__(self, other):
   return self.src == other.src and self.dst == other.dst
```

As an additional question: Why does this not have an additional comparsion `self.src.require.build_require == self.other.require.build_require`?

Shouldn't an edge that represents a build require be distinguishable from an edge that represents a normal require?

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc8
  * Conan version: 1.54
  * Python version: 3.8.10

**Comment by memsharded** [comment]
Hi @frank-schmidtner 

Thanks for reporting, indeed a bug. I am submitting a fix in https://github.com/conan-io/conan/pull/12622.

I am having a look, and  apparently this bug is not in any critical path, because that ``__eq__`` is mostly not used for anything critical. If you have some case that made this work, it would be great to know it, to see if we can add a test that would fire this bug.


> As an additional question: Why does this not have an additional comparsion self.src.require.build_require == self.other.require.build_require?

> Shouldn't an edge that represents a build require be distinguishable from an edge that represents a normal require?

``build_requires`` are managed in a completely different member attribute, so they cannot conflict or be compared with the regular requires, and the nodes they connect are also different to the ones pointed by regular requires ("build" and "host" context, recall that it is very recommended to use the ``--profile:build`` in 1.X). 
(in Conan 2.0 they are in the same collection, but all the rules for equality have changed)

**Comment by frank-schmidtner** [comment]
@memsharded 
I don't have any special test case you could add, I just stumbled over it while analyzing the code.

Thanks for the explanation. I know that build and host context are recommended, but we have some sort of "hybrid" workflow in our project because we could not solve some issues related to dual profile use. Currently we use the dual profile approach for cross compilation but for non-cross compilation we build/use some additional packages which can only be built with single profile atm. This leads to problems if a dependency is defined as require AND build_require and a lockfile is used. It works for dual profile, but for single profile it throws an error that the build_require is not available in the lockfile.

However, I guess the proper solution on our side is to get dual profile working for all use cases.

**Comment by memsharded** [comment]
> I don't have any special test case you could add, I just stumbled over it while analyzing the code.

Ok, as anything else seems to break with the change, I'll merge it and it will close this ticket automatically. But if there are any further question, don't hesitate to ask or create new tickets.

> I know that build and host context are recommended, but we have some sort of "hybrid" workflow in our project because we could not solve some issues related to dual profile use. Currently we use the dual profile approach for cross compilation but for non-cross compilation we build/use some additional packages which can only be built with single profile atm. This leads to problems if a dependency is defined as require AND build_require and a lockfile is used. It works for dual profile, but for single profile it throws an error that the build_require is not available in the lockfile.

This error, I have seen it a few times, might be fixed by making sure the appropriate ``--build=xxx`` flags are being passed at lockfile creation time. Otherwise, the build_requires will not be stored in the lockfile, because the graph doesn't expand at all the build_requires. Please try that, and if there is some other reported issue, link it here too.

> However, I guess the proper solution on our side is to get dual profile working for all use cases.

Yes, this is definitely the way to go, because Conan 2.0, which is very close, will work always with the 2 profiles approach.
