### ISSUE TITLE
[bug] Locally working with multiple hosts at the same time not supported?

### ISSUE THREAD

**Issue by Chnossos** [conan-io/conan#12626]
I have a library that I have to compile for Windows x64 **and** Windows ARMv7.

Thus, I use three profiles like so:

default (build):
```ini
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=16
compiler.runtime=MD
build_type=Release
[options]
[build_requires]
[env]
```

default-static (host 1):
```ini
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=16
compiler.runtime=MD
build_type=Release
[options]
[build_requires]
[env]
```

arm-static (host 2):
```ini
[settings]
os=Windows
arch=armv7
compiler=Visual Studio
compiler.version=16
compiler.runtime=MT
build_type=Release
[options]
[build_requires]
[env]
```

global.conf:
```init
core:default_build_profile=default
tools.cmake.cmaketoolchain:generator=Ninja
```
---
I thought this would be easy by just running this...
```shell
conan install -if build/desktop-release -pr:h default-static .
conan install -if build/arm-release -pr:h arm-static .
conan build -if build/desktop-release .
conan build -if build/arm-release .
```
...but it didn't work out the way I thought it would.

I have encountered multiple problems:

1. Both host profiles target a Release build, so running 'conan install' sequentially overrides `CMakePresets.json` with a single configure preset named `release` while I would need two presets.
   This prevents using presets completely, so I had to set CLion up manually, but it didn't stop there,
2. The `conan_toolchain.cmake` contains this: `set(CMAKE_MSVC_RUNTIME_LIBRARY "$<$<CONFIG:Release>:MultiThreaded>")` but this value should be different depending on the profile I'm currently building with, meaning it should probably be written inside the preset instead.
3. The rest of the `conan_toolchain.cmake` doesn't seem really ready for multiple hosts either way. Each time I run 'conan install' it will get overriden then the IDE will complain that the architecture doesn't match when linking one build or the other depending on the order of the conan installs.

It seems to me that only one host target is supported at the same time. Ideas:

* It should be possible to tweak the generation of the presets' name. It works fine when doing 'conan create' because only one configuration is built at a time, but when working in a tight loop this becomes burdensome.
* Having a 'preset-naming-mode' conf option that we can change to generate more complex preset names by default (`<build_type>`, `<arch>-<build_type>`, `<platform>-<arch>-<build_type>`, etc)
* `conan_toolchain.cmake` should also be renamed depending on those parameters, so we can link to the right libraries when using the right toolchain, even when not using presets, **inside the IDEs**.

**Comment by memsharded** [comment]
Hi @Chnossos 

I think this is a cmake limitation. CMake can only generate projects with multi-configuration for Debug/Release, but not for multiple architectures. Managing different architectures requires different projects (or cleaning and regenerating the project).

What Conan can do for you is to install and manage multiple configurations, including architecture, but they won't be in the same VS IDE. The steps are:

- The recipe you use to consume the dependencies is important, it requires to define a good layout, probably the built-in ``cmake_layout``. Can you share your consumer conanfile?
- You can define with ``tools.cmake.cmake_layout:build_folder_vars`` which settings and options are part of the folder structure and presets name. Seems you want to add at least ``settings.arch``
- Make sure to pass the ``-pr:b=xxxx`` to specify the build profile, otherwise it is not using it by default (it will be used by default in 2.0)

**Comment by Chnossos** [comment]
Oh wow `tools.cmake.cmake_layout:build_folder_vars=["settings.arch"]` solved my problems entirely!

Now both installations live in separate directories inside `build/` and CLion can manage both independently.
