### ISSUE TITLE
[bug] Powershell scripts for virtualenv do not escape paths correctly

### ISSUE THREAD

**Issue by fuchse-ego** [conan-io/conan#12648]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: --
  * Conan version: 1.55
  * Python version: 3.10
  * Powershell version: 5.1.19041.1682

### Steps to reproduce (Include if Applicable)
 * Create a folder with square brackets
 * Install a package that provides a virtual (run) env
 * try to activate it with Powershell

### Logs (Executed commands with output) (Include/Attach if Applicable)
 Powershell error:

```
In C:\development\GIT\[EGO] dd\UnitTest\install\activate.ps1:4 Zeichen:19
+ ... h ($line in Get-Content "C:\development\GIT\[EGO] dd\UnitTest\install ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (System.String[]:String[]) [Get-Content], Exception
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```

**Comment by memsharded** [comment]
Thanks for reporting @fuchse-ego 

I have been having a look, and indeed it seems powershell generated files do not support paths with spaces and other special characters.

I have done a PR to fix it in https://github.com/conan-io/conan/pull/12653, for next 1.56 release.
Note, however, that this only applies to the new environment management (https://docs.conan.io/en/latest/reference/conanfile/tools.html, section "env"), that will remain in Conan 2.0, and it seems you are still using the legacy environment generators, which will only get fixes for regressions (this seems it was always there), because today it was the 2.0-beta.6, and the intention is that it will be the latest beta, so very close to final 2.0.

**Comment by memsharded** [comment]
Hi @fuchse-ego 

I am having another related powershell issue, and I have realized that having square brackets in paths is a bad idea, because they are wildcard patterns in powershell. I am finding that even some powershell functions like ``Push-Location "$PSScriptRoot"`` fails because of this. I'd strongly recommend paths with ``[]`` if using powershell.
