### ISSUE TITLE
[question] Is there an option to install package dependencies with sources and debugging symbols (but not build)

### ISSUE THREAD

**Issue by hpe-ykoehler** [conan-io/conan#12659]
As a developer, we often have to understand the logic of the libraries we used.  As such, installing the library source code and symbols is often important to navigate the code in the IDE or to analyze core dumps (yet re-compiling may have a high cost, as such not desirable).

I was therefore wondering if there was an option available for conan install to include the source and debugging symbols info from the dependencies package and set them in a path logic that could be used by gdb or IDE such as VScode?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
It is up to the recipes to decide what they package. Packaging sources can be easily done in the ``package()`` method.
Same happens with symbols. But packages in ConanCenter by default do not package sources or files like PDB on Windows, because they are huge and not needed by the vast majority of users. Not only not needed, but adding them would make installation of debug packages much, much slower and take way more disk space, so most users would be annoyed by this default. 

Also it is not that easy to make symbols and the connection between sources and the binaries relocatable (some debuggers might require a re-mapping, or not allow it easily at all). This is the reason why the most pragmatic approach is to fire a local re-build with ``--build=pkg-to-debug``.

**Comment by hpe-ykoehler** [comment]
Thanks.

I do get that as default behavior those would not be appropriate, but having to capability to change that would be nice.  Like basically how rpmsrc package works or -devel (but maybe -debug).

I get the point about relocation and will go with the build-local approach.

**Comment by memsharded** [comment]
This has changed since then.

- The sources can be forced to be downloaded with Conan 2.0 with ``conf`` ``-c tools.build:download_source=True``
- For debugging symbols, maybe the new metadata files https://blog.conan.io/2023/10/24/Conan-launches-metadata-files.html could help to store extra files without affecting normal package installation. 

I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
