### ISSUE TITLE
[feature] Let search command provide full references without wildcards

### ISSUE THREAD

**Issue by cassava** [conan-io/conan#12721]
### What is your suggestion?

I would like to be able to re-use the output from the `search` command in other Conan commands, such as `download`. This is not possible right now, since the output from `search` looks like this:

```console
$ conan search --raw
autoconf/2.71
automake/1.16.5
b2/4.9.2
boost/1.69.0
```

And when using one of these references with other Conan commands, like `download`, it complains:

```console
$ conan download -re autoconf/2.71
ERROR: Provide a valid full reference without wildcards.
```

This is very inconvenient.

One potential solution would be add a flag that makes the conan `search` command provide full references:

```console
$ conan search --raw --full-refs # hypothetical option
autoconf/2.71@_/_
automake/1.16.5@_/_
b2/4.9.2@_/_
boost/1.69.0@_/_
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @cassava 

Thanks very much for your suggestion. This would be a bit difficult to fix in 1.X without breaking (or it would need yet another extra argument to opt-in), but I think the references are now way more consistent in Conan 2.0, and it is expected that you will be able to use them in the way you expect. 

There are a couple of fixes to be done to the ``conan list`` command (implements some of the functionality of the ``conan search`` command in 2.0), but after that is fixed, I think it will be good to document and test.

**Comment by cassava** [comment]
Hi @memsharded, thanks for the response. (Honestly, you're always so on top of these issues and provide such high quality responses! Respect!)

I guess this is a good impetus for me to test the 2.0 beta, although since we're using Conan within an organization for deployment, I'm not sure what this means for our users. Is it possible to upload packages with Conan 2.0 to an Artifactory that are consumed by users with an older version of Conan?

Otherwise, if someone were to provide a PR that provided the functionality via an opt-in flag, would that be something that the Conan team would be interested in? I imagine you want to focus on 2.0, so I can understand that you would be hesitant to add some flag that then is removed in in 2.0.

**Comment by memsharded** [comment]
> Hi @memsharded, thanks for the response. (Honestly, you're always so on top of these issues and provide such high quality responses! Respect!)

Many thanks :)

> I guess this is a good impetus for me to test the 2.0 beta, although since we're using Conan within an organization for deployment, I'm not sure what this means for our users. Is it possible to upload packages with Conan 2.0 to an Artifactory that are consumed by users with an older version of Conan?

Yes, the idea is that the same recipe, once updated to latest 1.X modern integrations, can be used to create binary packages both with Conan 1.X and 2.0. With exactly the same recipe, and the same recipe revisions. The binaries of Conan 1.X and 2.0 will have different package_ids, so they do not conflict with each other. They can live in the same artifactory repo, but commands like ``conan search <ref>`` (1.X) ``conan list packages <ref>`` (2.0) will only list the binaries built with the respective Conan versions, and each version will be able to keep ``conan install`` their dependencies from the same Artifactory repo.

> Otherwise, if someone were to provide a PR that provided the functionality via an opt-in flag, would that be something that the Conan team would be interested in? I imagine you want to focus on 2.0, so I can understand that you would be hesitant to add some flag that then is removed in in 2.0.

Yes, this is more about the review time, documentation, maintenance... just the merges we keep doing from 1.X branches to 2.0 branches have conflicts, often break our 2.0 CI jobs... so unless something is quite important to allow a smooth migration from 1.X to 2.0 (mostly things that goes to recipes), we are hesitant to prioritize or put time, because honestly, we are swamped with this transition, as Conan 2.0 is a really major release (many of core Conan functionality is new, like the dependency graph or the lockfiles).

**Comment by memsharded** [comment]
This was assigned to beta-7, but I think it can be closed as implemented, as it has been working like that in previous betas too. Thanks!
