### ISSUE TITLE
[feature] Allow toolchain packages to disable CMakeToolchain Blocks as they may interfere with the toolchains intention

### ISSUE THREAD

**Issue by KarstenB** [conan-io/conan#12734]
### What is your suggestion?

I just wrote a toolchain for X32 (x86_64, but with 32 bit pointers) as a conan package to be used with CMakeToolchain, and it kind of works, but I need to disable the `arch_flags` block with `tc.blocks.remove("arch_flags")` because the `-m32` or `-m64` flag is confusing the compilers and causing it generate the wrong output.

It would be nice if I could either disable a toolchain block via config from the profile, or from the user_toolchain(preferred), or override it from a user_toolchain that is included at the end (least preferred).

Otherwise I would need to modify the conan recipes that will be used, and I only need to do that for certain toolchains, which makes this even more annoying. 

On a much higher level, I would prefer to be able to set the target triple (x86_64-linux-gnux32 for X32, armv8.5-a+crypto-linux-gnu_ilp32 for my Macbook, or a plain x86_64-linux-gnu for anybody else) instead of having os and arch as this would give a much cleaner command line for clang, and would potentially allow to find a proper GCC to be used.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by mcandre** [comment]
conan (v1) generally integrates poorly with C/C++ toolchains. Instead of passing through `-target <triple>` to clang, it frequently requires me to uninstall clang and manually separate the standard triple name into conan-specific OS and architecture pairs. I plan to avoid third party dependencies in more of my C/C++ projects, so that I can just use toolchains directly without conan's leaky abstraction layer.

**Comment by memsharded** [comment]
Hi all,

It would be good to understand better if there are still gaps in Conan 2 (and also Conan 1.X). There is a ``conf`` in both versions called ``tools.gnu:host_triplet`` that allow to pass directly the triplet you want. Isn't this what you need?

**Comment by memsharded** [comment]
A new ``conf`` has been recently introduced in Conan 2, ``tools.cmake.cmaketoolchain:enabled_blocks``, that allows exactly this, to define which blocks are enabled. Toolchain packages used as ``tool_requires`` can use this conf in ``self.conf_info`` to control this.

Closing as implemented, please create new tickets for any further question, thanks!

**Comment by felixjulianheitmann** [comment]
Sorry to revive this already closed ticket but is there also a way to disable specific blocks? In our case conan_toolchain.cmake sets the CMAKE_CXX_COMPILER variable which we would like to have CMake figure out itself. 

Is there a way to define `tools.cmake.cmaketoolchain:disabled_blocks` to invert that logic?

Otherwise we have to explicitly list every other block that is perfectly fine.

**Comment by memsharded** [comment]
Hi @felixjulianheitmann 

Could you please clarify this? This ``CMAKE_CXX_COMPILER`` is only set for ``tools.build:compiler_executables`` conf, so if you don't define the conf, then it should be fine?

**Comment by felixjulianheitmann** [comment]
Hi @memsharded,

I just noticed that you said to not respond to this thread but rather reopen a ticket. Sorry for that.

My Conan config looks like this:
```
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=23
compiler.runtime=static
compiler.version=194
os=Windows


[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.cmake.cmaketoolchain:user_presets=False
```

After running `conan install` it generates a `conan_toolchain.cmake` that contains
```
########## 'compilers' block #############

set(CMAKE_C_COMPILER "cl")
set(CMAKE_CXX_COMPILER "cl")
```

The explicit setting of `cl` requires this to be on PATH, though. CMake by default detects and configures absolute paths. (Or at least it does when using the CMake extensions in VS code)

To be fair, I am fairly new to Conan ... Maybe I am just missing something.

Currently, we fix our build by setting:
```
include("${CMAKE_BINARY_DIR}/conan/conan_toolchain.cmake")
unset(CMAKE_C_COMPILER)
unset(CMAKE_CXX_COMPILER)
```

**Comment by memsharded** [comment]
Thanks for the feedback.

That is true the definition of ``cl`` as CMAKE_CXX_COMPILER is the only exception to the general ``tools.build:compiler_executables`` case, under this condition:
```python
        if compiler == "msvc" and "Ninja" in str(self._toolchain.generator):
            # None of them defined, if one is defined by user, user should define the other too
            if "c" not in compilers_by_conf and "cpp" not in compilers_by_conf:
                compilers["C"] = "cl"
                compilers["CXX"] = "cl"
```

> The explicit setting of cl requires this to be on PATH, though. CMake by default detects and configures absolute paths. (Or at least it does when using the CMake extensions in VS code)

Yes, but Conan creates the ``conanvcvars.bat``, called by ``conanbuild.bat`` that will activate the VS environment so not only the compiler, but all the necessary configuration to use the ``msvc`` compiler is activated.

> CMake by default detects and configures absolute paths. (Or at least it does when using the CMake extensions in VS code)

So far, the VS code cmake-tools activate the VS environment if it finds that definition in the ``CMakePresets.json`` file in, that Conan generates too:

```json
"configurePresets": [
        {
            "name": "conan-release",
            "displayName": "'conan-release' config",
            "description": "'conan-release' configure using 'Ninja' generator",
            "generator": "Ninja",
            "cacheVariables": {
                "CMAKE_POLICY_DEFAULT_CMP0091": "NEW",
                "CMAKE_BUILD_TYPE": "Release",
                "CMAKE_C_COMPILER": "cl",
                "CMAKE_CXX_COMPILER": "cl"
            },
```
If Conan don't generate that presets with that value, then the cmake-tools will not activate automatically the vcvars, and the ``msvc`` compiler will not be found.

So that CMAKE_CXX_COMPILER=cl is consistent with the toolchain.

Note that with ``tools.build:compiler_executables`` you can configure and define there the value that you want.

Still it is not clear what are you trying to achieve, what is the issue that you need to unset the compiler, for ``msvc``, which should be ``cl``, isn't it?

**Comment by felixjulianheitmann** [comment]
You are right, when using the generated CMake preset, the project builds fine and the environment seems to be populated correctly. Our issue was that after running `conan install` the actual calls to `cmake` would look for `cl` instead of `C:\Program Files\.....\cl`. That was breaking our build because the env wasn't setup to find the compiler like this.

Consider this request closed as this is more a user error on our end.

Thanks for the quick and helpful support! 👍🏽

**Comment by memsharded** [comment]
> Our issue was that after running conan install the actual calls to cmake would look for cl instead of C:\Program Files\.....\cl. That was breaking our build because the env wasn't setup to find the compiler like this.

Note that you can for example leverage the ``conan build`` command, that will automatically do the ``conan install`` plus call the ``build()`` method, that typically contains a ``cmake.configure()`` and ``cmake.build()``, which is super easy and convenient, as it does automatically activate the ``conanbuild.bat -> conanvcvars.bat -> vcvars.bat`` that activate VS, in a subprocess, so it doesn't pollute the current environment

Thanks to you for the feedback!
