### ISSUE TITLE
Any way to push binaries

### ISSUE THREAD

**Issue by kmaragon** [conan-io/conan#1274]
I imagine this has been asked before but I couldn't find it.

Is there any way to push just binary packages to a conan server without changing the identity of the package?

For example, I have a CI build system that *must* run in docker. Many of the packages I am using don't have prebuilt binaries for the set of options that I use. So every build takes about 100x longer than it would need to because it's rebuilding conan packages. There is already an internal server for some internal stuff. Is there any way to push *just* the binaries from these builds to that server without changing the identity of the package.

i.e. OpenSSL/1.0.2j@lasote/stable not having the be changed to OpenSSL/1.0.2j@myinternalusername/stable everywhere that it's being used?

I mean, all the same I'm fine with binaries being pushed to directly conan.io but I can't imagine that flies from a security / reliability perspective.

**Comment by memsharded** [comment]
I guess that you are using conan_server, right? Because by default Artifactory permissions will allow you to publish binaries without changing the username.

You are totally right, from the security/reliability point of view, you shouldn't rely on conan.io. You should run your own server, securily on-premises, for fully independent and controlled builds.

So if it is a thing of permissions of conan_server, you should configure them in your ``<userhome>/.conan_server/server.conf``. There you will have some permissions sections:

```
[write_permissions]
# "opencv/2.3.4@lasote/testing": default_user,default_user2

[read_permissions]
# opencv/1.2.3@lasote/testing: default_user default_user2
# By default all users can read all blocks
*/*@*/*: *
```
As you can see, the default permissions (any) is just to allow writing for the same user that is authenticated. You can add your own rules there, so something like:
```
[write_permissions]
*/*@*/*: ci_user
```
will allow to the ci_user to write any package with any username.

Please tell me if I understood correctly, and if this solves the issue. Thanks!

**Comment by kmaragon** [comment]
That's fantastic. Thanks so much

**Comment by memsharded** [comment]
You are welcome :)
