### ISSUE TITLE
[Meson] Add support for subproject settings

### ISSUE THREAD

**Issue by larshg** [conan-io/conan#12774]
### What is your suggestion?

Currently you can only set main project settings and not subproject settings:
See https://mesonbuild.com/Machine-files.html#project-specific-options:

GStreamer has recently changed to be a single project, with many subprojects.
And here its not possible to turn off Benchmarks / Tools for the gstreamer subproject.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by franramirez688** [comment]
Hi @larshg - Thanks for reporting it!

Since Conan 1.55, you can inject your own [Meson machine files](https://docs.conan.io/en/latest/reference/conanfile/tools/meson/meson.html#configure), so I think it could do the trick for you.
On the other hand, we could discuss adding some way to add those sub-project options via MesonToolchain without creating another machine file.

For now, it'd look like this:

*profile*
``` 
....
[conf]
tools.meson.mesontoolchain:extra_machine_files=["/path/to/your/meson_options.ini"]
```

*conanfile.py*
```python
# .....

def build(self):
    meson = Meson(self)
    meson.configure()  # <- will load the Conan machine files with your files
    meson.build()
```

**Comment by larshg** [comment]
Ahh - I'll see if I can get it work. Thanks for quick answer!

**Comment by franramirez688** [comment]
Hi @larshg 

Did this issue get solved? Could we close the issue?

**Comment by larshg** [comment]
I'm no longer working on this project, so lets just close it.
