### ISSUE TITLE
[question] Shouldn't conan check if a tool is available instead of just looking at the cache?

### ISSUE THREAD

**Issue by famastefano** [conan-io/conan#12809]
### What is your question?

Hello,
I've added CMake as the required tools to consume my recipe, precisely `tool_requires = "cmake/[>=3.21]"`.
I already have CMake installed, but via my local package manager (winget, as I'm on Windows), but maybe the package's consumer hasn't, so conan will handle that.
But for me, it's useless to download _and build_ CMake... Not to mention that his happens on WSL2 as it's a separate ecosystem.
So, while I have installed CMake on both Windows and WSL2, I had to _build it twice_.

I'm asking this as a question as I don't know if it's a good design choice but, shouldn't conan try to find already installed tools, and building them only as a last resort measure?
Even a simple "let's see if it's in the PATH"?
And assuming it will be done, does it mean conan now have to handle all the possible quirks a tool has to extrapolate their version?
Like, having a separate function for each possible and immaginable tool, like:
```python
def check_existing_cmake():
    # invoke cmake --version from CLI
    # parse CLI result

def check_existing_ninja():
    # invoke ninja --version from CLI
    # parse CLI result

def check_existing_fancytool():
    # invoke fancytool -v from CLI if on Linux, fancytool /Version on Windows etc.
    # parse CLI result
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @famastefano 

Yes, this is by design. Conan does not try to be smart, and fallback to system packages. If you tell conan ``tool_requires = "cmake/[>=3.21]"`` that means that you want to use the Conan package, otherwise, don't tell Conan to use that ``tool_requires``. The "just check if the tool is there in the system" is not as simple as it seems, at it can actually become very fragile and problematic. Trying to be "smart" and auto-detect things has always led to lots of pain and suffering, so in 2.0 we are even going further and remove some of the Conan "smart" detections and convert them to explicit ``conf`` inputs by the users.

Simple example with that ``cmake`` package: the Conan ``cmake`` recipe can have a conditional dependency to ``openssl``, that can be a modern one, maybe more modern than the one the underlying system has. Now, a version of CMake that is compatible is found in the system: should we use that CMake from the system, that it might be using a different openssl version that the one we would like to use? How to check that? 

For common tools, it is also typical to not add them explicitly to recipes, but define them in the ``[tool_requires]`` section of the profiles. That way, you let the users to decide if they want to use the Conan package or they want to use the system one, just by defining it or not in their profiles.

**Comment by famastefano** [comment]
Thank you for the detailed answer!
