### ISSUE TITLE
[question] Events/conferences planned for 2023

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#12821]
### What is your question?

Dear Conan Folks,

Happy New Year!
I would like to know what Conan events/conferences are planned for this year especially in/around Europe.
Also wanted to ask if tech webinars here are free: https://leap.jfrog.com/WN-Sec-2023-01-Identifying-and-Avoiding-Malicious-Packages-EMEA-LP.html 

Many thanks and keep up the good work!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

The agenda for next year is not closed yet, because it also depends on talks submissions and acceptance at major conferences. But it is common that we try to participate in ACCU (Bristol), using std::cpp (Madrid), CoreC++ (IL), CppCon (Denver), MeetingC++ (Berlin). We have participated in the past in ItalianC++ too. Those are C++ conferences that we might sponsor, have a booth, do talks if accepted, etc.

Conan specific events, we were planning a conference on March 2020, but the pandemic hit and we canceled it. We might resume it at some point, but that is not decided yet. It is more likely that we will do other kind of smaller events like trainings. The best way to keep updated is to follow our social (Twitter) and subscribe to our release mailing list (very low traffic, only releases, and if we do something big like our own event, it will be announced there).

Yes, the JFrog webinars are free, you just need to register to attend.

**Comment by maitrey** [comment]
Hi @memsharded ,
I just now subscribed to the release mailing list.
I will keep an eye on all the above events and hopefully be able to attend one or two of them.
Many thanks for your reply.

**Comment by tomasz-wezyk** [comment]
Hi @memsharded

Do you have some list of conferences that you know that you will be and have some lectures?

Br,
Tomasz

**Comment by memsharded** [comment]
We will go to CoreC++ in Israel as sponsors, but no talks.
The other are still unknown, we will most likely submit talks to CppCon, but can't guarantee yet.

**Comment by maitrey** [comment]
Hi James,
I am interested in the talks :). 
Thanks for keeping me posted.
