### ISSUE TITLE
[bug] problem in conan export-pkg with build-folder option

### ISSUE THREAD

**Issue by jayoh-dev** [conan-io/conan#12831]
Hello Conan guys,

I would like to use `export-pkg` command to export a local package.
Everything is ok when default path is used in most of commands, but when I specify output folder in `install` command the `export-pkg` does not work as expected.
I just wanted to use one out directory to organized slightly.

Conan is really helpful to solve complex problems to build for various embedded targets.
Many thanks for your efforts. 

### Environment details

* Conan version: 1.55

### Steps to reproduce

```
conan new test/0.1 --template=cmake_lib
conan install . --output-folder out --install-folder out
conan build . --build-folder out --install-folder out
conan export-pkg . --build-folder out --install-folder out
```

### Logs

```
Exporting package recipe
test/0.1 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
test/0.1 exports_sources: Copied 1 '.cpp' file: test.cpp
test/0.1 exports_sources: Copied 1 '.h' file: test.h
test/0.1: The stored package has not changed
test/0.1: Exported revision: e1bc0eeb0cf46505eaad77a94ac6561e
test/0.1: Forced build from source
Packaging to d8d8aba822aaa76849d2f1bafe4a2a62a9f83b74
test/0.1: Generating the package
test/0.1: Package folder /home/jay/.conan/data/test/0.1/_/_/package/d8d8aba822aaa76849d2f1bafe4a2a62a9f83b74
test/0.1: Calling package()
ERROR: 
	FileNotFoundError: [Errno 2] No such file or directory: '/home/jay/Temp/conan/build/Release'
```

**Comment by memsharded** [comment]
Hi @jayoh-dev 

Thanks for your feedback and for your report.

Probably the documentation is not fully clear in this aspect. The new integrations (the generated with ``conan new -m=cmake_lib``), do not support the ``--build-folder`` argument anymore (it has been removed in 2.0). You should be using ``--output-folder`` instead, please try that and let us know.

**Comment by jayoh-dev** [comment]
Thank you for the response.

Do you mean using `--output-folder` option in `export-pkg` command?
The option is not provided for `build` and `export-pkg` command in version 1.56.
The `export-pkg` seems that always try to find package in default path though `--build-folder` is specified.

**Comment by memsharded** [comment]
Yes, that is true, sorry about that. The ``--output-folder`` is available for ``export-pkg`` in 2.0 only, but not 1.X.

Quick question: Have you tried dropping the arguments completely? The new template already contains a ``cmake_layout()`` that manages to do this automatically, so command line can be way easier, just the bare commands. If you want to customize the layout you can pass arguments to ``cmake_layout(build="out")`` too.

**Comment by jayoh-dev** [comment]
WOW! The suggestion like using `cmake_layout(build_folder='out')` solve everything.
The commands could be much simpler like:
```
conan install . --install-folder out
conan build . --install-folder out
conan export-pkg . --install-folder out
```

Thanks for your feedback!

**Comment by memsharded** [comment]
Yes, that is totally the intention of the new ``layout()`` feature: to be able to forget about it. The ``cmake_layout()`` even has some other capabilities, like being able to automatically generate different folders for different compilers, compiler versions, architectures (based on conf ``tools.cmake.cmake_layout:build_folder_vars`` like ``tools.cmake.cmake_layout:build_folder_vars='[\"settings.compiler.cppstd\"]'``). And Conan 2.0 removes ``install-folder`` argument, because it is no longer necessary as those extra files are no longer generated so ``conan build .`` (it already does the install too) + ``conan export-pkg .`` will do it too.
Furthermore the ``layout()`` feature also enables easier ``editable``, so you can work simultaneously on different packages without needing to export them to the cache, and even creating projects containing those multiple packages in one IDE.

**Comment by memsharded** [comment]
If the above solves your issue, maybe we can close this ticket, not worth trying to do something else, as 2.0 is very close.

**Comment by jayoh-dev** [comment]
Agree. I will close the ticket and look forward to the 2.0.
