### ISSUE TITLE
[question] Best practice to set configuration in conan 2.0

### ISSUE THREAD

**Issue by MaxandreOgeret** [conan-io/conan#12833]
### What is your question?

Hello,
I am migrating my conan docker images to conan 2.0. I am using `conan profile new default --detect --force` to detect and set the default config automatically.

I then use `conan profile update` to set the following profile keys:
```
conf.tools.system.package_manager:mode=install
conf.tools.system.package_manager:sudo=True
settings.compiler.libcxx=libstdc++11
```

In conan 2.0, detecting the profile automatically is easy : `conan profile detect --force --name default` but there is no way to set specific profile keys. What is the alternative using vonan 2.0?

Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MaxandreOgeret 


Thanks for your question.
In Conan 2.0 you shouldn't need to update to ``libstdc++11``, that should be already the default.

It is true that we removed the ``conan profile update`` command, we have removed all commands that basically were implementing some kind of text editing.
If you want to add configuration to the profile you can perfectly do an append of:
```
[conf]
your conf items
```
to the profile file.

Recall that you also have the ``global.conf`` file, that you can also manage with ``conan config install``, and that you might also use to define global behavior for your Conan instance, for all profiles.

**Comment by memsharded** [comment]
Closing this question as responded.

**Comment by sburton84** [comment]
> It is true that we removed the `conan profile update` command, we have removed all commands that basically were implementing some kind of text editing.

This makes setting these options on a CI a bit awkward, instead of just running a `conan profile update` I have to use something like using `sed` to do manual text replacement on the file?

**Comment by memsharded** [comment]
Hi @sburton84 

The main question would be why do you need to modify a profile in CI on the fly, when there are better recommended approaches to manage this:

- Use your own profiles, installed with ``conan config install``. You perfectly define in your profiles what you want. This has always been the recommended approach for production. Conan 2.0 explicitly defines auto-detected profiles as non-stable.
- Profiles can be jinja templates, which gives them extra power to be more expressive. Profiles can also be included() and composed
- For specific variability in CI, it is not necessary to modify the profile, you can modify arguments on the fly, like ``-pr=myprofile -s build_type=Debug`` will do a Debug build even if the profile defines a Release one, because the ``-s build_type=Debug`` has precedence.

Please let me know if this helps

**Comment by SamJ69** [comment]
So, I've installed a set of profiles from my organization using `conan config install`, so now how do I select a specific profile from the (in my case) 3 options.
I used to be able to do `conan config set general.default_profile=my-profile-name`. What do I do now??

**Comment by ujos** [comment]
> So, I've installed a set of profiles from my organization using `conan config install`, so now how do I select a specific profile from the (in my case) 3 options. I used to be able to do `conan config set general.default_profile=my-profile-name`. What do I do now??

You can pass the profile name as a command line parameter to the `conan install`:

```
conan install \
  --profile=your-personal-profile \
...
  ../conanfile.txt
```

**Comment by memsharded** [comment]
> I used to be able to do conan config set general.default_profile=my-profile-name. What do I do now??

Or if you are talking about profiles for Windows, Linux, OSX, the ``global.conf`` that defines the default profile is also a ``jinja`` template, that can use the ``os``, ``platform``, ``distro`` Python modules to decide which one is the default profile for the current machine. 

And then a single ``conan config install`` works transparently for all platforms, without any need to do a extra ``conan profile  update`` specific for that machine.

**Comment by Tw31n** [comment]
@MaxandreOgeret , I feel your pain.

It's not even about convention over configuration.
Conan 2 configuration doesn't even work out of the box. You have to:
1.  create conanfile.txt;
3. create default profile;
4. change IDE runtime from Debug to Release OR manually update default profile to use debug mode OR create own profile using text editor.

What I want:
```bash
conan profile create MyApp_release -s build_type=Release
conan profile create MyApp_debug -s build_type=Debug
conan init
```

What I can:
```bash
cd ~/.conan2/profiles

conan profile detect
cp default MyApp_release
cat default | sed 's/Release/Debug/g' > MyApp_debug

conan install ~/MyApp --build=missing --profile=MyApp_debug
conan install ~/MyApp --build=missing --profile=MyApp_release
```

**Comment by memsharded** [comment]
Hi @Tw31n 

Sorry, it is not very clear what is the issue.

The following works:
1. ``conan profile detect``
2. write your conanfile.txt
3. ``conan install`` # by default it will be Release
4. ``conan install -s build_type=Debug`` if you want Debug configuration

It is not necessary to change the default profile ``build_type``, if you define ``-s build_type`` it in the command line, it overwrites the profile one.

**Comment by Tw31n** [comment]
> Sorry, it is not very clear what is the issue.

Short answer: inconsistency and hard to support.

A little bit of context: I'm new to C++ and have spent the last 2 days reading the Conan 2 documentation and trying different approaches to work with Conan.

Long answer:
I did have this variant:
```bash
conan install . --settings=build_type=Release
conan install . --settings=build_type=Debug
```

> conan install -s build_type=Debug

but what the point of profiles if you can set all settings inline? What if you have more them one setting?

Inconsistency:
1. Why do you need to have `build_type` in the profile and in command line? Maybe it's good to combine these approaches for CI/CD pipelines in order to avoid one more profile, but in developing workflow it feels off;
2. You can use command line approach to set everything you need, but you can't use it without a profile, at least without default one.

Hard to support:
1. Command line approach: basic `conan install .` is not enough and IDE won't detect settings by its own + you have to prepare README.md section with all settings that should be used in command line, so other developers know how to work with this project;
2. Profile approach:
- variant 1: prepare settings in profiles but why are profiles not in the project folder? Should there be another README.md section with the next code:
```bash
cat <<EOF >> ~/.conan2/profiles/MyApp_release
...
EOF
```
- variant 2: create profiles in the project folder and create a script that will duplicate them into `.conan2/profiles` folder.
- variant 3: you have to replace conanfile.txt by conanfile.py and use profile contents as strings inside conanfile.py.

Everything above is easy to do, but again, it feels off: overcomplicated and redundant.

**Comment by memsharded** [comment]
> but what the point of profiles if you can set all settings inline? What if you have more them one setting?

You don't want to type in the command line full profiles such as:
```
[settings]
# Just an example, you need to use your real settings
os=Android
os.api_level=21
arch=armv8
compiler=clang
compiler.version=12
compiler.libcxx=c++_shared
compiler.cppstd=14

[conf]
# Use your path here
tools.android:ndk_path=/usr/local/share/android-ndk
```

That would be horrible, a really bad UX. Note that you will have to define 2 sets of settings, both the "host" settings and the "build" settings.

On the other hand you are not forced to create 2 "android" profiles, one ``android_release`` and one ``android_debug``, you can have just one, default it to release or debug, or neither, then use in the command line:

```
conan install . -pr=android -s build_type=Debug
conan install . -pr=android -s build_type=Release
```
This is very aligned with other tools like build systems that will have a toolchain define, then the type, like:
```
cmake -DCMAKE_TOOLCHAIN_FILE=myarmtoochain.cmake -DCMAKE_BUILD_TYPE=Debug
```

> Why do you need to have build_type in the profile and in command line? Maybe it's good to combine these approaches for CI/CD pipelines in order to avoid one more profile, but in developing workflow it feels off;
You can use command line approach to set everything you need, but you can't use it without a profile, at least without default one.

This is not inconsistency, this is flexibility. You can do whatever you like, if you really want to have huge command lines with all those arguments, you can do it, don't use profiles. But I can guarantee that will be extremely inconvenient, really annoying UX. 



> Command line approach: basic conan install . is not enough and IDE won't detect settings by its own + you have to prepare README.md section with all settings that should be used in command line, so other developers know how to work with this project;
Profile approach:


You are missing the ``conan config install/install-pkg`` functionality. This is how profiles are shared, distributed and updated to keep the Conan configuration in sync, not only about profiles, but also custom settings, remotes definitions, custom deployers, hooks, etc. etc. Check https://docs.conan.io/2/reference/commands/config.html#conan-config-install for more information.

**Comment by Tw31n** [comment]
Thanks for pointing that out!

I’ve carefully read the doc about `config install`, and now I can do stuff like this:
```bash
conan config install -tf profiles/ profiles/macos_macos_MyApp_*
# or
conan config install -tf profiles/ profiles/macos_linux_MyApp_*
```

Previously, I've skimmed through the doc and tried 2 variants:
```bash
conan config install MyApp_debug
conan config install --out-file=~/.conan2/profiles/ MyApp_debug
```
and got strange result. Then, checked:
```bash
  -tf TARGET_FOLDER, --target-folder TARGET_FOLDER
                        Install to that path in the conan cache
```
and saw 'cache' word and skipped it, because not interested in any cache, need Conan configs folder only.

**Comment by memsharded** [comment]
> conan config install -tf profiles/ profiles/macos_macos_MyApp_*

This might work, but in general it shouldn't be necessary to provide those arguments, but just install all profiles. It will take the same time, and it is harmless to have more than one profile installed. Plus, it is very often useful to install other configuration too, like the remotes or custom settings. So ``conan config install <url>`` is generally the recommended way to go.
