### ISSUE TITLE
[question] Can  conan fetch recipes directly from conan-center-index?

### ISSUE THREAD

**Issue by chenyuanrun** [conan-io/conan#12866]
### What is your question?

If conan can just download recipes from conan-center-index(or any other git repo/local dir that hold the recipes), parse the recipes and download extract sources, and then build the source in local, we can deploy conan with just a git repo, without Artifactory(or a conan server), which will make using conan simpler to deploy (in a private deployment especially).

I do not hate to building source in my local machine by the way (rust and golang do this thing), but I do hope conan could be more direct, cleaner, and simpler. I think conan server(and the undocumented restful api, which always need a special server to work) bring lots of complexity here.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by chenyuanrun** [comment]
bazel have a index center holding just the recipes now: https://github.com/bazelbuild/bazel-central-registry.git , but lacks lots of packages, someone could just fetch recipes from bcr, then download the source from some urls, and start building.

**Comment by memsharded** [comment]
Hi @chenyuanrun 

Thanks for your question

> I do not hate to building source in my local machine by the way (rust and golang do this thing), but I do hope conan could be more direct, cleaner, and simpler.

Some C++ projects take a huge time to build. Many of our users have builds that take many hours, and re-building from source all the time is just not possible. And in any case, if having a server can save a lot of time and resources, because reusing binaries avoid a lot of re-builds from source, why not use it?

> I think conan server(and the undocumented restful api, which always need a special server to work) bring lots of complexity here.

Why does it bring complexity? The API is hidden, called by the application, in exactly the same way Python pip, Java Maven, Rust Cargo, and basically practically all other language package manager do. You do not need to know the API of maven to use it, and the same for Conan. And Maven also needs a server (Nexus, Artifactory, etc).


In any case, if you want to use recipes directly from the repo, it is very simple. We will probably provide some built-in integration in 2.X, but in the meantime it requires just a few lines of a script. I have a proof of concept in my branch in:
https://github.com/memsharded/conan-center-index/tree/mycustom

- Have a ``mypkgs.list`` (or any other format) file with the list of packages and version that you want to use 
- Have a script that iterate that list and call ``conan export`` over the list of packages (I have ``mybuild.py`` script):
``` python
import os


def run(cmd):
    ret = os.system(cmd)
    if ret != 0:
        raise Exception(f"Failed cmd: {cmd}")

def load(f):
    return open(f, "r").read()

def export_pkgs(pkgs):
    for pkg in pkgs:
        name, version = pkg.split("/")
        run(f"conan export recipes/{name}/all {version}@")

pkgs = load("mypkgs.list").splitlines()
export_pkgs(pkgs)
```

And done. You have your packages ready to be used. Then when you want to consume them, you can do ``--build=missing``, to build from source what you need and what needs to be built (but nothing else)

**Comment by chenyuanrun** [comment]
Thanks for reply! @memsharded 

> In any case, if you want to use recipes directly from the repo, it is very simple. We will probably provide some built-in integration in 2.X,

I am very exciting to hear that there is such integration plan, it would be great if conan could config conan-center-index as the only single source to work.

I will close this issue and thanks for your great work!!
