### ISSUE TITLE
[question] "private" package option for build_requirements?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#12892]
### What is your question?

Hi,

I have two packages "foo" and "bar". Both are used by a top level "app". Both use Google Test 1.10.0 for tests. "foo" uses a patched version of it (memory allocation test fixes), while the other doesn't need these changes. One trivial solution would be to add a package option to GoogleTest, to enable or disable these patches.
However I have a problem with that: we build obviously "foo", "bar" and "app" with the same profile, which means if I add the "googletest:enable_path=True" then both "foo" and "bar" will pull in the patched version from GoogleTest.

Is there a way to "constrain" package options somehow so that "googletest:enable_path=True" would only be used if it is consumed by "foo". 
Or the only option is to generate a different version from GoogleTest (e.g. embed somehow the "patched" attribute in the version number - which is a bit cringy).

Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

No, it is not possible to define in the profile an option that applies only to a given graph branch. Note that the syntax for it would be quite complex, because it is not even enough to tell the name of the consumer package, but also possibly the context, or even different branches in the graph.

Instead of creating a different version of googletest, have you considered defining the ``option`` in the consumer recipe? Like everyone uses the default, but that specific recipe that needs googletest in that variant, is the one who has the knowledge, so it specifies in its ``default_options = {"googletest:myoption": "mynondefaultvalue"}``

**Comment by harsszegi** [comment]
Hehe, that's pretty neat, I haven't thought about that :) Thanks @memsharded , closing this for now.
