### ISSUE TITLE
[bug] Breaking change introduced relating to deprecated MsBuild  in 1.57.0

### ISSUE THREAD

**Issue by AshleighAdams** [conan-io/conan#12897]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: v141_xp
* Conan version: 1.57.0
* Python version: builtin

### Steps to reproduce

```
from conans import ConanFile, MSBuild, tools
from conan.tools.microsoft import MSBuildToolchain
```

A project with the above structure fails to under 1.57.0. Works on 1.56.0.

### Logs

```
$ conan install -g deploy raptor/12.2.11@inseinc/stable --build=missing --profile=debug_141
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MTd
compiler.toolset=v141_xp
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

raptor/12.2.11@inseinc/stable: Not found in local cache, looking in remotes...
raptor/12.2.11@inseinc/stable: Trying with 'inseinc'...
Downloading conanmanifest.txt completed [0.15k]
Downloading conanfile.py completed [6.82k]
Downloading conan_export.tgz completed [2.97k]
Decompressing conan_export.tgz completed [0.00k]
raptor/12.2.11@inseinc/stable: Downloaded recipe revision 603ddac7099f35393983cf3c894a6fd0
Installing package: raptor/12.2.11@inseinc/stable
Requirements
    boost/1.71.0@conan/stable from 'inseinc' - Cache
    bzip2/1.0.8@conan/stable from 'inseinc' - Cache
    cryptopp/5.6.5@inseinc/stable from 'inseinc' - Cache
    directx/9.0.0-2@inseinc/stable from 'inseinc' - Cache
    icu/58.3@inseinc/stable from 'inseinc' - Cache
    libb64/1.2.1-1@inseinc/stable from 'inseinc' - Cache
    mpir/2.7.0-2@inseinc/stable from 'inseinc' - Cache
    novolineage/1.1.37@inseinc/stable from 'inseinc' - Cache
    ogapi/2.24.1@inseinc/stable from 'inseinc' - Cache
    raptor/12.2.11@inseinc/stable from 'inseinc' - Downloaded
    tinyxml/2.6.2@inseinc/stable from 'inseinc' - Cache
    xvid/1.3.7@inseinc/stable from 'inseinc' - Cache
    zlib/1.2.11@conan/stable from 'inseinc' - Cache
Python requires
    version-calculator/1.0.1@inseinc/stable
Packages
    boost/1.71.0@conan/stable:d7ffa9e297e83b28e60a025c92fe4920da0910bd - Cache
    bzip2/1.0.8@conan/stable:86b2aac9fd4b7bb0f6eb25f1a636b1876d9e5d28 - Cache
    cryptopp/5.6.5@inseinc/stable:bfbe0a039702cfd8f54032276416635413b39052 - Cache
    directx/9.0.0-2@inseinc/stable:45b43bcd991ec89baf1eb618b595ca3227a3cf0b - Cache
    icu/58.3@inseinc/stable:4bb79ee642e42e148fb304236d2d4b4e901b55a6 - Cache
    libb64/1.2.1-1@inseinc/stable:bfbe0a039702cfd8f54032276416635413b39052 - Cache
    mpir/2.7.0-2@inseinc/stable:bfbe0a039702cfd8f54032276416635413b39052 - Cache
    novolineage/1.1.37@inseinc/stable:c1bee5dbaade32063b1c8a277ff3975af4993d4c - Cache
    ogapi/2.24.1@inseinc/stable:a010013fac2b1bfaff6ac23bbc89b20a065c65d7 - Cache
    raptor/12.2.11@inseinc/stable:86d70a3c64071db8d6b1189af14b259ad10cc7ba - Build
    tinyxml/2.6.2@inseinc/stable:bfbe0a039702cfd8f54032276416635413b39052 - Cache
    xvid/1.3.7@inseinc/stable:bfbe0a039702cfd8f54032276416635413b39052 - Cache
    zlib/1.2.11@conan/stable:fb466dfd43375561fcec289ed252bcf8185c4253 - Cache
Build requirements
    crc-calculator/1.0.1@inseinc/stable from 'inseinc' - Cache
    doctest/1.2.6@bincrafters/stable from 'inseinc' - Cache
Build requirements packages
    crc-calculator/1.0.1@inseinc/stable:11e6a84a7894f41df553e7c92534c3bf26896802 - Cache
    doctest/1.2.6@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Cross-build from 'Windows:x86_64' to 'Windows:x86'
Installing (downloading, building) binaries...
bzip2/1.0.8@conan/stable: Already installed!
crc-calculator/1.0.1@inseinc/stable: Already installed!
cryptopp/5.6.5@inseinc/stable: Already installed!
directx/9.0.0-2@inseinc/stable: Already installed!
doctest/1.2.6@bincrafters/stable: Already installed!
icu/58.3@inseinc/stable: Already installed!
libb64/1.2.1-1@inseinc/stable: Already installed!
mpir/2.7.0-2@inseinc/stable: Already installed!
novolineage/1.1.37@inseinc/stable: Already installed!
ogapi/2.24.1@inseinc/stable: Already installed!
tinyxml/2.6.2@inseinc/stable: Already installed!
xvid/1.3.7@inseinc/stable: Already installed!
zlib/1.2.11@conan/stable: Already installed!
boost/1.71.0@conan/stable: Already installed!
boost/1.71.0@conan/stable: LIBRARIES: ['libboost_wave', 'libboost_container', 'libboost_contract', 'libboost_exception', 'libboost_graph', 'libboost_iostreams', 'libboost_locale', 'libboost_log', 'libboost_program_options', 'libboost_random', 'libboost_regex', 'libboost_serialization', 'libboost_wserialization', 'libboost_coroutine', 'libboost_fiber', 'libboost_context', 'libboost_timer', 'libboost_thread', 'libboost_chrono', 'libboost_date_time', 'libboost_atomic', 'libboost_filesystem', 'libboost_system', 'libboost_type_erasure', 'libboost_log_setup', 'libboost_math_c99', 'libboost_math_c99f', 'libboost_math_c99l', 'libboost_math_tr1', 'libboost_math_tr1f', 'libboost_math_tr1l', 'libboost_stacktrace_noop', 'libboost_stacktrace_windbg', 'libboost_stacktrace_windbg_cached', 'libboost_unit_test_framework']
boost/1.71.0@conan/stable: Package folder: D:\.conan\6ff637b\1
boost/1.71.0@conan/stable: Disabled magic autolinking (smart and magic decisions)
raptor/12.2.11@inseinc/stable: Applying build-requirement: crc-calculator/1.0.1@inseinc/stable
raptor/12.2.11@inseinc/stable: Applying build-requirement: doctest/1.2.6@bincrafters/stable
raptor/12.2.11@inseinc/stable: Configuring sources in D:\.conan\ccf20c\1
raptor/12.2.11@inseinc/stable: SCM: Getting sources from url: 'snip'
raptor/12.2.11@inseinc/stable: Copying sources to build folder
raptor/12.2.11@inseinc/stable: Building your package in D:\.conan\b09911\1
raptor/12.2.11@inseinc/stable: Generator visual_studio_multi created conanbuildinfo_multi.props
raptor/12.2.11@inseinc/stable: Generator visual_studio_multi created conanbuildinfo_debug_v141_win32_v141_xp.props
raptor/12.2.11@inseinc/stable: Calling generate()
raptor/12.2.11@inseinc/stable: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
raptor/12.2.11@inseinc/stable: MSBuildToolchain created conantoolchain_debug_v141_win32.props
raptor/12.2.11@inseinc/stable: MSBuildToolchain writing conantoolchain.props
raptor/12.2.11@inseinc/stable: Aggregating env generators
raptor/12.2.11@inseinc/stable imports(): Copied 1 '.exe' file: CrcCalculator.exe
raptor/12.2.11@inseinc/stable: Calling build()
raptor/12.2.11@inseinc/stable:
raptor/12.2.11@inseinc/stable: ERROR: Package '86d70a3c64071db8d6b1189af14b259ad10cc7ba' build failed
raptor/12.2.11@inseinc/stable: WARN: Build folder D:\.conan\b09911\1
ERROR: raptor/12.2.11@inseinc/stable: Error in build() method, line 104
        msbuild = MSBuild(self)
        ConanException: Using the wrong 'MSBuild' helper. To use MSBuildDeps, MSBuildToolchain you should use 'from conan.tools.microsoft import MSBuild'
```

The existing recipe in question uses the following import structure:

```
from conans import ConanFile, MSBuild, tools
from conan.tools.microsoft import MSBuildToolchain
```

It's been some time now, but if I recall correctly, the legacy MsBuild import was used as the new one uses a slightly different method that resulted in the compiler running out of heap memory. Retroactively releasing new recipe revisions would be a no go for us, due to regulatory issues it creates, and the number of them that exist.

The breaking change was introduced in 79100038f289553bbe09c9543a7080936ded4e27

**Comment by memsharded** [comment]
Hi @AshleighAdams 

Thanks very much for your report.
I am afraid this is not a breaking change, but the ``MSBuildToolchain`` is designed to work only with the new ``from conan.tools.microsoft import MSBuild`` helper. Please try upgrading to it to make it work.

Sorry, I didn't read well enough

> It's been some time now, but if I recall correctly, the legacy MsBuild import was used as the new one uses a slightly different method that resulted in the compiler running out of heap memory. 

If you can please check that and report that error, we will have a look, that should be fixed if it is not working correctly. Thanks!

**Comment by AshleighAdams** [comment]
I'm sorry but I can't agree with that, intentional or not, it is a breaking change which should be limited to major versions, especially if noticed, assuming conan is following SemVer?

We would be happy to opt out of the breaking change via our conan settings or some other means, but without such, we won't be able to update beyond 1.56, and I suspect this may also be the case for many other organizations out there too.

**Comment by memsharded** [comment]
Hi @AshleighAdams 

I am very sorry for the inconvenience,  I'd like to clarify first a bit the usage of these features, and why we added this new check in 1.57.

We have been receiving many reports, issues, and spending a lot of time trying to help many users, investigating and debugging issues, and the reason was that they were mixing the new generators with the legacy helpers. The thing is that often they apparently work fine, but internally they might be misbehaving many times, like providing the wrong flags, using the wrong architecture, etc.

We tried to clearly define the rules to use the new tools in https://docs.conan.io/en/latest/reference/conanfile/tools.html:

- Imports must be in the form ``from conan.tools.xxx import yyy``, or ``from conan.tools import xxx``. Do not use ``from conan import tools`` nor ``from conan.tools.xxx.yyy import zzz``.
- Everything that recipes can use belong to ``from conan.tools``. Any other import is private implementation and shouldn’t be used in recipes (except ``from conan import ConanFile`` and ``from conan.errors``)
- Only documented tools with explicitly documented imports can be used in recipes. **Do not use any other import not found in this section of the documentation, even if they are in the from ``conan.tools`` namespace.**

But it was clearly not enough, and users were still importing the legacy helpers, and it was costing the team countless hours.  This has been a nightmare of support.

This was why we decided to introduce a check that validates and enforces the already documented rules. We never saw it as a breaking change, but as a protection measure to help users easily identify something that was already broken. 

We think that the correct way to approach this is to upgrade to the new ``from conan.tools.microsoft import MSBuild`` while in Conan 1.56, then finally upgrade to 1.57. 
This would be similar to upgrading the compiler version. If the source code has some subtle bug, UB, or relying on some non-standard behavior, the next compiler version can easily break the build, and it is necessary to update the code in order to be able to use the new compiler version.

In order to help a bit with the transition, we might consider to add lets say an env-var that says "CONAN_TEMPORARILY_ALLOW_MISMATCH_HELPERS", and that would skip the check, while in 1.57 and then it is possible to upgrade the recipes to use the new helpers before the next 1.58, because that is most likely going to be the last one before Conan 2.0, and it should be fully aligned with the 2.0 release (that is, no longer allow the mismatch, because the legacy ``MSBuild`` helper has been already completely removed in Conan 2.0)

**Comment by AshleighAdams** [comment]
I agree that it's a good to have, don't get me wrong, it's just that builds with the mismatched helpers in recipes are already out there, and can't be retroactively fixed. We often get live issues, and have to work on old projects using old libraries, so while the project itself could be updated, the library it uses cannot without possibly imposing a significant certification cost.

Perhaps this functionality can be enabled only for new `export`s or `create`s, instead of complete opt-out or opt-in? Or perhaps something akin to Rust's epochs could be a way to prevent old recipes from breaking going forward?

**Comment by Tails86** [comment]
I know that this thread is a bit old now, but I wanted to point out that I have no way to use cpython 3.10 in Windows at the moment from conancenter. If I build with `shared=False`, I get this error:
`cpython/3.10.0: Invalid ID: Static msvc build disabled (>=3.10) due to "AttributeError: module 'sys' has no attribute 'winver'"`
If I build with `shared=True`, I get this error:
`ConanException: Using the wrong 'MSBuild' helper. To use MSBuildDeps, MSBuildToolchain you should use 'from conan.tools.microsoft import MSBuild'`

I need to roll my own recipe to get this to work right.

**Comment by memsharded** [comment]
Hi @Tails86 

It seems you are mixing legacy cmd line wrapper ``MSBuild``, mixing it with the new generators ``MSBuildDeps/Toolchain``, and this is not allowed, it is expected to use the new one ``from conan.tools.microsoft``.

The ``winver`` seems something specific to the ``cpython/3.10.0`` recipe, I cannot found any reference to ``winver`` in the whole Conan codebase.

**Comment by Tails86** [comment]
What I was trying to get at is that I have no control over the recipe here: https://conan.io/center/cpython?tab=recipe

Which means that, if I'm understanding things correctly, a new conan version was rolled out which broke their own recipes in conancenter. My own recipe doesn't use MSBuild but depends on something within conancenter which does.

Is there anything that I can do to help fix a recipe on conancenter?

**Comment by memsharded** [comment]
Yes, Conan 2.0 is out since a few months ago, and a large part of ConanCenter has already updated to be 2.0-compatible.
But it seems that https://github.com/conan-io/conan-center-index/blob/master/recipes/cpython/all/conanfile.py is still using quite legacy integrations. It is likely that given the complexity of this recipe, nobody managed to put the effort yet.

But this doesn't mean that Conan 1.X would be broken, recipes in ConanCenter should keep working the same with Conan 1.X versions. The limitation here is something intrinsic to the recipe, for some reason "static" library + Python3.10 won't build. And the other is a "bug" in the recipe. For some reason that change didn't originally fail, even if it was a documented bug, but apparently there weren't enough built-in protections, and the review didn't catch it. So following Conan releases simply made this bug more visible.

Thanks for offering to help, but I think that if you haven't contributed to ConanCenter before or don't have high expertise in complex Conan recipes, I'd probably discourage it, as this recipe is one of the most complex ones, and as it has too many dependencies, it is possible that some of them are still not 2.0-ready, so it can be a down-the-rabbit-hole, and it can be a bit frustrating.

It is a pity, because I know that this recipe in particular there are a bunch of Conan users having their own forks, but they are not allowed to contribute it back to open source by company policies. We might try to put some initial effort from our side, and see how it goes, I can't guarantee, the team is a bit swamped atm...

**Comment by memsharded** [comment]
Closing this ticket as outdated, referring to Conan 1.X integrations.
