### ISSUE TITLE
[question] Package outdated

### ISSUE THREAD

**Issue by paulross80** [conan-io/conan#12906]
### What is your question?

Hello, I'm starting with Conan 2.x, I have no previous experience using it
I'm trying to use the **SDL** multimedia library, it's version at conan center is very recent
But **SDL_mixer** is terribly outdated: sdl_mixer/2.0.4
Current version at github is 2.6.2

Can I report the outdated package?
Or ... Can I compile it from source? In that case, can I have two classes in my _conanfile.py_? Example:

`# -*- coding: utf-8 -*-`
`class SDLMixerRecipe(ConanFile):`
`    # follow tutorial: Handle sources in packages`
`    # https://docs.conan.io/en/2.0/tutorial/creating_packages/handle_sources_in_packages.html`

`class MyAppRecipe(ConanFile):`
`    def requirements(self):`
`        self.requires('sdl/[>2.26.0 <3.0]')`
`        self.requires('sdl_mixer/2.6.2')`

Or do I need to make another _conanfile.py_ in another folder. In that case, where?
I've tried to find all my questions in google and in Conan 2.x documentation, but I didn't find anything

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @paulross80 

Yes, the recipes from ConanCenter are not in a good state right now to be used by Conan 2.0. 
A large effort is being done to migrate some of the most popular recipes there to be ready for 2.0: https://github.com/conan-io/conan-center-index/issues/12888, and it covers around 100 recipes (out of > 1400 in the center) because those accounts for a large number of downloads (80%). But it is totally expected that many recipes are not there, I still see a warning sign in that list for SDL, and sdl_mixer is not even there.

My suggestion for using ConanCenter recipes today is to start with 1.X, as 2.0 is still in beta. Make sure to use the latest 2.0 ready syntax, so it is easy to upgrade to 2.0 when possible: https://docs.conan.io/en/latest/conan_v2.html, as there is a modern common syntax of recipes in 1.X that should cleanly work in 2.0. Then keep an eye on the maturity of the migration of ConanCenter, testing your project from time to time with a Conan 2.0 client, to check how things go, and collaborate if necessary in the repo in  https://github.com/conan-io/conan-center-index. At this point reporting that some recipe doesn't work in Conan 2.0 is probably not very useful, it is a known thing, but maybe look for open issues and upvote if existing, and of course helping the community (once some experience in Conan has been obtained, as a very newbie it is probably too much).

**Comment by paulross80** [comment]
Thanks for your answer, @memsharded 
I saw a talk by Diego at cppcon 22, he recommended using Conan 2.0 beta, so I went for it
But you are right, maybe I should start learning Conan 1.x first
