### ISSUE TITLE
[Question] conan with existing build process

### ISSUE THREAD

**Issue by FlYnN91** [conan-io/conan#1291]
Hi I am trying to improve our C library management and from the first look seems like Conan does what I'd like to do, but just wanted to check that I am understanding all correctly.
I have number of projects that build via a CMake process.  Some of the projects depends on each other which creates a little bit of a mess. 

I'd like to still use my existing build process, but upload/manage the generate library files via Conan to manage dependencies between the projects. I don't need Conan to compile/build source. I'd like to add information to a project allowing Conan to pull the required dependencies (libs).

Could any one point me in the right direction? 

Much appreciated.

**Comment by memsharded** [comment]
Hi Dainius,

Usually, conan is responsible to call the build process, in order to control the different package binaries built from a given package recipe. However, as conan is quite flexible and allows to reproduce the whole package creation locally, probably what you are looking for is the ``package_files`` command (http://conanio.readthedocs.io/en/latest/reference/commands/package_files.html).  This command allows to directly define the binaries for a given package and configuration (settings like compiler, version, and options like shared/static). 

You might be interested in reading this howto: http://conanio.readthedocs.io/en/latest/howtos/existing_binaries.html?highlight=conan%20new#packaging-local-binaries

Once the packages are created, consuming them can be done with text ``conanfile.txt`` files, or even directly installing them with ``conan install``, using the required generator, in this case, ``cmake``.

Please tell me if the above helps, or need further info. Thanks!

**Comment by FlYnN91** [comment]
Hi,

Yeah this does seem to make sense to me. However the Conan 0.21.2 does not seem to know command `package_files`.

**Comment by memsharded** [comment]
Yes, that is true, they were introduced in conan 0.22. Is there any specific issue stopping you from updating conan? Please note that, even though we make great efforts to not break things, conan is still 0.X, so not be the considered stable, really recommended to keep upgrading until 1.0 is released.

**Comment by FlYnN91** [comment]
@memsharded Thank you for the info. I got the packaging and uploading to remote server working. Your links really helped me. I wrote a bunch of cmake functions that call conan for various things and does some validation on its responses. 
Now I just need to do the seconds part of getting my build process to request the dependencies from the remote through my build process. I imagine some more functions will be required.

**Comment by memsharded** [comment]
You are welcome. If you are writing cmake calls, you might also be interested in the https://github.com/conan-io/cmake-conan repo and tools. I am not a big fan of calling conan from cmake, but those can help, please have a look.

**Comment by FlYnN91** [comment]
oh great, thanks. I will look at that too. I've looked at some info about using packages, but I seem to fail to download the required packages via `conan install`:
- cd into existing project
- conan new <name>/<version>@<user>/<channel> --bare
- create a new `conanfile.txt` with the `[requires]` section and required package
- execute `conan install`
It finds package in the remote but cannot download it due to a missing Package folder: ```WARN: Package folder doesn't exist, can't collect libraries```. what is this Package folder?

**Comment by memsharded** [comment]
You are creating a ``conan new --bare`` conanfile.py. That will have precedence over the text ``conanfile.txt`` one. You only need one of them, typically conanfile.txt for  simple cases, if wanted more advanced automation, then conanfile.py.

About the missing package folder, not sure what was happening, I think it is because of the usage of collects_libs in the conanfile.py, which is probably not intended for just consuming.

**Comment by FlYnN91** [comment]
Thanks for the info. I got things working now. Still using the conanfile.txt but will advance toward the conanfile.py in the future.
Really like conan even though I am not using it the way it was intended and utilizing only maybe 5% of its capabilities.

**Comment by memsharded** [comment]
Thanks very much, glad you like it. We put a lot of effort in having something flexible enough to accommodate most workflows, packaging paradigms, build systems, etc. So appreciate your comments :)
