### ISSUE TITLE
[question] how to force tool_requires libffi/3.4.3 to use a user/channel

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan#12929]
### What is your question?

Conan 1.57.0

I have a custom automake and libffi, with user/channels
The standard recipes don't build, but the custom ones do.

I'm using two profiles (host, build), but the same profile for both.

When I build my project, I can't make conan use my custom libffi.

This is the key bit in my profile:
```
[tool_requires]
# libffi requires automake
automake/1.16.5@cci-bugfix/sysarch-1-2023-01-19
!automake*: libffi/3.4.3@cci-fix/automake-2023-01-19
```

No matter what I try and do, conan still insists on using libffi/3.4.3@_/_ ie the standard libffi.

It is happy to use my custom automake...

```
Build requirements
    autoconf/2.71 from 'myrepo' - Cache
    automake/1.16.5@cci-bugfix/sysarch-1-2023-01-19 from local cache - Cache
    bzip2/1.0.8 from 'myrepo' - Cache
    cmake/3.25.0 from 'myrepo' - Cache
    glib/2.75.0 from 'myrepo' - Cache
    libffi/3.4.3 from 'myrepo' - Cache
    libgettext/0.21 from 'myrepo' - Cache
... and more
```

What is the magic sauce I'm missing please?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @paulharris 

This is because regular requires cannot be overriden/injected from profiles.
If you want to override libffi, you need to declare a dependency on it with ``self.requires(..., override=True)`` in your consumer recipes.

Just in case, current Conan best practices recommend not to use user/channel for information that changes overtime, but consider them to be immutable part of the package reference. Having a date in the channel might not be the best approach. We have also recently seen similar cases when mixing ConanCenter recipes with user forked and modified recipes. It is very likely that the simplest approach there would be to override packages without user/channel, in that way it is not necessary to artificially having to inject overrides anywhere.

**Comment by paulharris** [comment]
I don't directly require libffi, it is somewhere deep in the dependency tree.
And if my top-level package requires libffi, does that override the transient dependencies of other packages?

I am using a user/channel with a date because it is (hopefully) a short term override while the CCI recipe is fixed up (there is a PR for it already).
The date is there to help me remember which fork of the recipe I'm using, and to watch for CCI updates that are more recent than my fork.

So, right now all I'm trying to do is build my project with my current recipe fixes, so I can get on with my work.
I don't like overriding with no user/channel because then I can't have multiple active copies of (eg) libffi.

I have an older build of my software that works with an older set recipes, using a different set of user/channels.
I am able to build my software with updated recipes, without disrupting the older build - as long as I use different user/channels.

If I did not use user/channel, then if I replace the libffi in my cache with a new one, the old build will no longer work and I would be completely stuck!

Am I really forced to override the base libffi/3.4.3@_/_ package in order to build?
ie I can only use one libffi for one cache?

**Comment by memsharded** [comment]
> I am using a user/channel with a date because it is (hopefully) a short term override while the CCI recipe is fixed up (there is a PR for it already).
The date is there to help me remember which fork of the recipe I'm using, and to watch for CCI updates that are more recent than my fork.

Have you ever considered directly building all your dependencies from your fork of conan-center-index? That is super robust, and once you have fixes for some recipes, building the ones that you need in production is not much work, only a bit more of CI, but it pays off in robustness and having full control. My suggestion there is to keep the conan-center-index fork as close to the upstream as possible, so not using user/channel anywhere. When things are built, they are built together. Reusing robustly older builds can be done with a lockfile.

> Am I really forced to override the base libffi/3.4.3@/ package in order to build?

You can do the ``override=True`` in your final consumer. It will manage to inject your own user/channel up in the dependency graph, even if you don't directly depend on it. If for some reason the ``libffi`` were not a dependency (for example in some platform, due to a conditional dependency), then it will not be added as a real dependency, as it is only an "override".

> ie I can only use one libffi for one cache?

No, you can have as many libffi versions and for each version as many users and channels as you want, they will not conflict. The user/channel and versions are not related to the cache, it is how a particular instance of the dependency graph is resolved.

Does this clarify the ``override`` behavior? please let me know.

**Comment by paulharris** [comment]
Hi Memsharded, thanks I appreciate the discussion,

> > I am using a user/channel with a date because it is (hopefully) a short term override while the CCI recipe is fixed up (there is a PR for it already).
> > The date is there to help me remember which fork of the recipe I'm using, and to watch for CCI updates that are more recent than my fork.
> 
> Have you ever considered directly building all your dependencies from your fork of conan-center-index? That is super robust, and once you have fixes for some recipes, building the ones that you need in production is not much work, only a bit more of CI, but it pays off in robustness and having full control. My suggestion there is to keep the conan-center-index fork as close to the upstream as possible, so not using user/channel anywhere. When things are built, they are built together. Reusing robustly older builds can be done with a lockfile.

I'm not sure how I'd do that, I'm not using CI at my end at the moment, so how would that be done purely from a client point of view?
Sounds like I would have to conan-export everything into the cache?

And it sounds like I'd need a different cache each time I upgrade a recipe.

To be clear, I've been hacking on the recipes to get CCI working for conan 2, so that in a few months (when things have settled) I can be sure I can use the latest CCI without problems.
So really I just want full control over which recipes are used to build each library version.
I have that power, except for the tool_requires.

I can have multiple builds with multiple versions of libxyz/1.2.3 with different recipes, and I can upgrade and downgrade the recipe version that is used to build, without overwriting what is already in the cache.

I tried the v1 lock files but it didn't give me that level of control.

> 
> > Am I really forced to override the base libffi/3.4.3@/ package in order to build?
> 
> You can do the `override=True` in your final consumer. It will manage to inject your own user/channel up in the dependency graph, even if you don't directly depend on it. If for some reason the `libffi` were not a dependency (for example in some platform, due to a conditional dependency), then it will not be added as a real dependency, as it is only an "override".

Surely override=True will introduce the requirement on libffi to the host dependency graph, not the build dep graph?
Or should I be adding it as a tool_override instead?

I am able to do this same thing with --require-override on the command line, and I have a script which helps to maintain the list of overrides - a bit like a lock file I suppose, except I have some extra features to search for updates from CCI.

> 
> > ie I can only use one libffi for one cache?
> 
> No, you can have as many libffi versions and for each version as many users and channels as you want, they will not conflict. The user/channel and versions are not related to the cache, it is how a particular instance of the dependency graph is resolved.

Yes but only one version of the recipe for one version of libffi, for each user/channel.
So that means within the local cache, there can only be one way of building a particular version of libffi for the no-user-channel scenario.

> 
> Does this clarify the `override` behavior? please let me know.

Not really, I don't think you addressed the situation when the requirement is a build/tool requirement, only for the host requirements.

**Comment by paulharris** [comment]
I wanted to check if I could override tool_requires for packages I consume.
There may be a particular version of the library that won't execute or build on my platform, or perhaps a bug I need to avoid.
Or perhaps I want everyone to use ONE version of a tool, rather than 3 different versions (I've had this situation with cmake).

Currently, my dependencies are insisting on building with cmake 3.25.0.
I tried to force it to use cmake 3.25.1.
I tried using self.requires("cmake/3.25.1", override=True) in my top level recipe, but it had no effect.

I had the same issue with libffi, as described above.  I have a version that I've built, with effort, and I wanted to use that.

This is the use-case I'm trying to address in this issue...

**Comment by mmomtchev** [comment]
I have a similar problem - Github (and many others) seems to have switched to Python 3.12 by default and when building on macOS, `meson` needs to be at least 1.2.3 to work without `distutils`. I need to force all my recipes to use it, but I don't see any way to override it from the top recipe.

**Comment by memsharded** [comment]
This situation has changed with Conan 2, I think this issue might have already been solved:

- ``[replace_requires]`` and ``[replace_tool_requires]`` in profiles allow to override the dependencies.
- It is only intended as a temporary workaround, recipes must be fixed for the long term

Please check it in https://docs.conan.io/2/reference/config_files/profiles.html#replace-requires

**Comment by paulharris** [comment]
I'm closing this, I am using the replace_requires approach now.
