### ISSUE TITLE
[feature] MesonToolchain: guess Apple SDK path in case of cross-build if `tools.apple:sdk_path` not set

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#12921]
### What is your suggestion?

Currently `MesonToolchain` raises if we try to cross-build on macOS and `tools.apple:sdk_path` is not set: https://github.com/conan-io/conan/blob/31e26422bbd92ec3a77bd2c701c82c077ba2512d/conan/tools/meson/toolchain.py#L244-L247
It works out of the box with other generators families, and it can be surprising for users to have to set this conf only because Meson is used under the hood: https://github.com/conan-io/conan-center-index/issues/15339.
From what I see `conan.tools.apple.apple.apple_sdk_path()` can guess Apple SDK path when `tools.apple:sdk_path` is not set (by relying on `XCRun`), it could be called in `MesonToolchain`. It's exactly how `AutotoolsToolchain` finds Apple SDK path.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
> It works out of the box with other generators families, and it can be surprising for users to have to set this conf only because Meson is used under the hood: https://github.com/conan-io/conan-center-index/issues/15339.

In Conan 2.0 no generator automatically deduce/detect the ``sdk_path`` anymore.
It is split in 2:
- CMake, Xcode can default the sdk, as identifier, because they know how to obtain the ``sdk_path`` themselves
- Meson, Autotools, need the ``-isysroot``, as an absolute path, and this will be passed via ``conf``.

So we are not willing to rely more on the automatic detection of the ``sdk_path``, until we fully agree on the strategy for all.
I am labeling this for ``look into`` with the team.
