### ISSUE TITLE
[feature] Add Cmake config and installation generation support

### ISSUE THREAD

**Issue by liarokapisv** [conan-io/conan#12926]
### What is your suggestion?

Add support for generating native Cmake-config files and installation scripts. 

### Background

We maintain many private libraries for internal consumption, and we use Conan extensively for all of our projects.
One very annoying part of the whole process has been maintaining the CMake-native installation support, this mainly includes the config files and a `installation.cmake` script which contains EXPORT and INSTALL commands, which we source from the project root.

While we use Conan extensively, we wanted to keep the native CMake installation support available for easier public consumption if we decide to make these public. Not everyone uses Conan and since we use CMake as our build system we wanted to try and keep things up to date with the best packaging practices.

We recently decided to completely remove all the native CMake support from our internal libraries.

This is due to the fact that the custom config files are at odds with the incredible CMakeDeps generator config files. The native vs generated config files differ in general feature-completeness, and we have to basically expend a lot of effort just to keep the hand-crafted native config files up to date.

### Details

I thought that it would be incredibly useful for library writers that already maintain feature-complete Conan recipes to use these recipes as an underlying model to generate their Cmake native config files and also installation support. I believe that the Conan underlying model is rich enough to express most use cases. 

Basically, the library provider leans on the Conan support to generate the Cmake installation and config files that end-users can use. This helps with adoption since it prevents the library authors from having to expend effort for both Conan and native Cmake consumption. It would probably also solve compatibility issues with adding conan-center-index support, which purges the custom config files.

I would imagine that the config-file part of the feature wouldn't be very hard to implement, since this is inherently very similar to what the CmakeDeps generator does. The main difference being that the config file cannot be aware of transitive dependencies.
 
For this feature to be complete it would also have to provide custom INSTALL/EXPORT commands which the library provider could then include from the project root, this part should be harder to generate since I am not aware of anything remotely similar so far, but it should be mostly straightforward.

Any thoughts are welcome!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @liarokapisv 

Thanks for your suggestion.
I am not sure that I fully understood it. Do you mean that Conan could automatically generate CMake code that implements the CMake ``install()`` based on the ``package()`` method implementation? And that it could generate the ``-config.cmake`` files inside the package itself based on the ``package_info()``? 
If you mean that, I think this would be super challenging, a very large effort. The process would actually be more doable in the other direction, automatically deducing the ``package_info()`` from the CMake build. We have already done some exploratory feature using the CMake FileAPI but it seems it is not very feature complete, and it is still not enough.

We are also involved in some standardization work towards a unified package description, but that will take time. This would be a more viable approach to avoiding this kind of repetition.

**Comment by liarokapisv** [comment]
Yes that's exactly what I mean. I figured that the `install` stuff could perhaps be hard to implement, I don't know much about the conan internals to be honest, I would assume one could deduce things from the package folder structure, but I can see how this easily turns non-trivial with more complex projects. 

The opposite direction is also a good solution to the `install` problem but it doesn't solve the incompatibility issue with the CMakeDeps generated config files. No matter what one does, they can't replicate the CMakeDeps config file behavior unless conan itself takes advantage of its own model to generate something similar.
 
> We are also involved in some standardization work towards a unified package description, but that will take time. This would be a more viable approach to avoiding this kind of repetition.

This would probably be the best solution in the long term, it would probably work even if just Conan supports it. I would assume generating build-system specific packaging from that would be easy even from the Conan side with such a description available.

**Comment by memsharded** [comment]
> Yes that's exactly what I mean. I figured that the install stuff could perhaps be hard to implement, I don't know much about the conan internals to be honest, I would assume one could deduce things from the package folder structure, but I can see how this easily turns non-trivial with more complex projects.

We have been there, it happens to be an extremely challenging functionality. There is still not AI able to do this in a reasonable way for a reasonable amount of non absolutely trivial projects.

> This would probably be the best solution in the long term, it would probably work even if just Conan supports it. I would assume generating build-system specific packaging from that would be easy even from the Conan side with such a description available.

Yes, this is what we are already doing in every generator, transforming the "cpp_info" into some other representation. But the goal for this is the opposite flow: the build system is the one responsible for generating a standard report of what it built, that can be used by package managers to redistribute that package, without having to guess what is inside. The build system is the one having all information about artifacts being built, so it should be its responsibility.

**Comment by code-affinity** [comment]
I have been trying to create Conan recipes for open-source libraries that are already using CMake and already produce and install their own CMake configuration files.  I have a lot of application project (CMake) build code that was previously consuming these libraries using the CMake configuration that they produced natively.  In the transition to Conan, I have been frustrated by the requirement to teach Conan to produce configuration files for the libraries that are interchangeable with the "native" configuration files.  If I understand correctly, that is the problem being discussed here.

Today I discovered this note:  https://docs.conan.io/2/reference/tools/cmake/cmakedeps.html#disable-cmakedeps-for-installed-cmake-configuration-files

Is this a new development since the issue was opened?  When creating a recipe for an existing third-party library, in the package_info for that recipe I can call self.cpp_info.set_property("cmake_find_mode", "none"), and append the path to the natively generated CMake configuration files to self.cpp_info.builddirs.

Now my consuming projects can continue to consume the very same CMake configuration files they were already consuming for these libraries.

**Comment by memsharded** [comment]
Hi @code-affinity 

Using the packaged, cmake-generated xxx-config.cmake has been possible for a long time, using different approaches. It is likely that Conan 2.0 just documented it a bit more explicitely.

It is just ConanCenter the one that is restricting the xxx-config.cmake files from the build to be packaged for some reasons:
- Those files are not multi-config, so can't be valid for Visual Studio and XCode users (lots of people)
- Those files might have issues, locating dependencies in the system rather than in other Conan packages as expected
- Doing that in ConanCenter makes the support for other build systems rather than CMake much worse, and we think it is not the most fair approach

I also think that ``self.cpp_info.set_property("cmake_find_mode", "none"`` might not be even necessary, if in the consumer you don't use the ``CMakeDeps`` generator. Using just the ``CMakeToolchain`` generator, it will be able to locate the packaged ``config.cmake`` files inside the packages.

**Comment by code-affinity** [comment]
Thank you for your quick response.  

> Those files are not multi-config, so can't be valid for Visual Studio and XCode users (lots of people)

Are you saying they are _necessarily_ not multi-config, or just potentially?  Our application is cross-platform and is built using both of the multi-config CMake generators you cited, in addition to several single-config generators.  The libraries we are consuming seem to be handling that just fine.  For example, they are producing (library)-targets.cmake, which refers to (library)-targets-release.cmake and (library)-targets-debug.cmake.  And the multi-config generation of our application projects is resolving those correctly.

I understand your other points.  I see that this is only working for us because we are only consuming these CMake-based projects from CMake-based projects of our own.  ConanCenter has to accommodate heterogeneous build systems.

>in the consumer you don't use the CMakeDeps generator

Oh, right.  Of course that would be even easier!  Thank you.

[Edit:  We are consuming other packages for which we do depend on CMakeDeps to generate CMake configuration files, including many that we obtain from ConanCenter.]

**Comment by memsharded** [comment]
> Are you saying they are necessarily not multi-config, or just potentially? Our application is cross-platform and is built using both of the multi-config CMake generators you cited, in addition to several single-config generators. The libraries we are consuming seem to be handling that just fine. For example, they are producing (library)-targets.cmake, which refers to (library)-targets-release.cmake and (library)-targets-debug.cmake. And the multi-config generation of our application projects is resolving those correctly.

There is a CMake limitation, a ``find_package(pkg)`` doesn't allow generator expressions, cannot be conditioned on ``build_type`` Release/Debug. So it cannot locate the Debug and Release packages simultaneously. This limits the dev experience, that is not able to switch in the IDE from Debug/Release in the dropbox, without needing to call Conan or touch anything.

Unless you have some black magic in your generated config.cmake files? Is that the case?

**Comment by code-affinity** [comment]
>Unless you have some black magic in your generated config.cmake files? Is that the case?

I don't think so. Maybe we are talking about two different things.

For example, we are working with a modified version of an ancient snapshot of Apache Thrift (so we can't use the very nice ConanCenter version.)  Its CMake install step produces (among other things) a directory named (prefix)/lib/cmake/thrift, which contains CMake configuration files such as thrift_static-targets-debug.cmake and thrift_static-targets.release.cmake.

In our application CMakeLists.txt file, we have 

```
find_package(
  thrift REQUIRED thrift::thrift_static
  PATHS
  ${PREFIX}
)

target_link_libraries(my_application thrift::thrift_static)
```

When I run CMake on this CMakeLists.txt file with the Visual Studio generator, it generates a multi-configuration Visual Studio vcxproj file.  Reviewing the linker properties for this project, I see the release configuration of the project is properly linked to the release version of the thrift_static library, and the debug configuration of the project is properly linked to the debug version of the thrift_static library.

From the Visual Studio IDE I can select either the debug or release configuration and build the project without re-invoking CMake.  

That is everything I ever wanted from a multi-config generator.

[Edit:  On further experimentation with this approach, I have realized other limitations that I don't fully understand yet, so I am no longer confident that the following statement is correct.   Perhaps black magic is required after all.]

From that starting point, if I create a Conan recipe wrapper for the Thrift project, which uses the cmake_layout, and whose package_info sets cmake_find_mode to "none", I still seem to get those same benefits on the consuming (application) side when it obtains the Thrift library from Conan.

**Comment by memsharded** [comment]
> When I run CMake on this CMakeLists.txt file with the Visual Studio generator, it generates a multi-configuration Visual Studio vcxproj file. Reviewing the linker properties for this project, I see the release configuration of the project is properly linked to the release version of the thrift_static library, and the debug configuration of the project is properly linked to the debug version of the thrift_static library.

Yes, there might be something that I am missing. 
Conan packages are single-config, because that is the only way to really scale, but also for other reasons like security (not leaking Debug binaries). So when some Conan package is installed in the cache, the Debug and Release configurations will be in different folders, containing different separated files. The ``find_package()`` locating the ``xxx-config.cmake`` files is only able to find 1 of them, either the Release or the Debug one.

So what I think could make sense is that your apache thrift Conan package is actually building both Debug and Release binaries inside the same Conan package binary (1 ``package_id`` containing both Debug and Release, instead of 2 different ``package_id`` one for each config). Is this the case? If that works for you, then happy to know it!

**Comment by code-affinity** [comment]
You are right.  My claims about the pure CMake process were correct.  But I was wrong to claim that I could wrap this process in a simple Conan recipe that re-used the CMake-generated config files.

When we use a pure CMake process, we build and install both debug and release configurations for Thrift, specifying the same CMAKE_INSTALL_PREFIX in both cases.  The result is that ${CMAKE_INSTALL_PREFIX}/lib/cmake contains CMake configuration files for both debug and release configurations.  When consuming that library from a multi-config CMake application project, the resulting multi-config Visual Studio project properly matches the application build type to the Thrift library build type.

But as you say, when you build and export-pkg a Conan project with two different build types like this:
```
conan export-pkg . -s build_type=Release
conan export-pkg . -s build_type=Debug
```

the result is two independent Conan packages, not a single combined package.  There is no easy way to correctly consume these separate packages from a single multi-configuration application project.  I guess this is the problem described in the last note for issue #11326.

I don't understand yet how we avoid this same problem when using CMake configuration files generated by CMakeDeps in a multi-configuration application.  (I'll keep learning.)  But since it evidently does work, I'll just bite the bullet and add the necessary conanfile.py code to support CMakeDeps for our Thrift snapshot.

**Comment by memsharded** [comment]
> I don't understand yet how we avoid this same problem when using CMake configuration files generated by CMakeDeps in a multi-configuration application. (I'll keep learning.) But since it evidently does work, I'll just bite the bullet and add the necessary conanfile.py code to support CMakeDeps for our Thrift snapshot.

To clarify, when users/developers want to develop in their multi-config IDE like Visual Studio, it is needed to do 2 installs, like:
```bash
conan install . # Typically default release = -s build_type=Release
conan install . -s build_type=Debug
```
Two conan installations will happen, the CMakeDeps will be generating first ``xxx-release-data.cmake`` (and other) files, and the second run will create the ``xxx-debug-data.cmake`` files. Each set of files will be able to locate the respective Conan package, and the entry ``xxx-config.cmake`` aggregates all generated configurations.

**Comment by memsharded** [comment]
Closing this ticket as outdated and not planned (the OP feature request to automatically deduce code in one direction or the other is too complex for the value, and in any case, this would be better covered by the CPS standardization effort).

Please create new tickets for any further question or issue as necessary, thanks for the feedback!
