### ISSUE TITLE
Conan deos not respect proxy settings in conan.conf

### ISSUE THREAD

**Issue by tobi-tobsen** [conan-io/conan#1293]
With conan 0.21 (linux, ubuntu 14.04), disabling proxy doesn't work when http_proxy / https_proxy is exported for the current user: 

the conan.config file reads: 

> # If don't want proxy at all, remove section `[proxies]`

When removing the` [proxies] ` it doesn't disable the proxy but instead uses the system proxy defined in exported http(s)_proxy (e.g. form ~/.bashrc)
This is what a user expects if an empty [proxies] section exists since the comment suggests that

> # Empty section will try to use system proxies.

**Comment by memsharded** [comment]
Hi @tobi-tobsen 

Thanks for the feedback. Still not clear to me, but I'd say that the issue is that proxies enabled with user environment variables in e.g. .bashrc, are not exactly the same as system proxies.

Conan is using the python-requests library for networking, and the usage of proxies is controlled via environment variables. If you remove the ``[proxies]`` section, but you have environment variables declared, python-requests will use them, and there is little conan can do. I think that conan should not remove an environment variable defined by the user/system regarding proxies, that could break things.

Maybe the writing should be improved: "if don't want proxy at all, remove section" => If you dont want conan to configure a proxy, remove section, however, if you have proxies configured at the user or system level, they will still be used.

**Comment by tobi-tobsen** [comment]
Well, I think improving the writing would good and solve the issue from a Conan perspective.

The issue wasn't that bad if python-requests library respected no_proxy entries (also defined in basrc or via etc/environment), but unfortunately it only uses HTTP(S)_PROXY  entries as far as I can tell. Maybe I ll open a bug report there.

**Comment by memsharded** [comment]
Great, submitted a docs issue: https://github.com/conan-io/docs/issues/215
Yes, I think submitting an issue to python-requests is fine, maybe they can address there.

Thanks for the feedback!
