### ISSUE TITLE
[question] How does imports() work exactly?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#12968]
### What is your question?

Hi,

I know that both deploy() and imports() is deprecated in 2.0, but we are still using 1.x at my company.
I'd like to install both dependencies of the package and package artifacts into a specific folder.
E.g. I'd like to copy all produced .so*s (by the package) and all its dependencies to the given folder (the purpose of
it is to be able to executes certain tests of the package). We've tried imports() but it appears like it skips the main package's build artifacts, only copies the artifacts of the dependencies. 
We are doing something like this:

self.copy("*.so*", src="lib", dst="bin", keep_path=False, symlinks=True)

Any idea? Thanks,

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

> E.g. I'd like to copy all produced .so*s (by the package) and all its dependencies to the given folder

You cannot do it with ``imports()``. It executes very early, like at the "generate" step, and it runs even before ``build()`` and ``package()`` are called. So when ``imports()`` is executed, the binaries of the current package are not even there.

For that purpose, the ``deploy()`` method is a better alternative, it can copy from itself and from the dependencies, because ``deploy()`` method executes after the package has been built. Please check https://docs.conan.io/en/latest/devtools/running_packages.html#deployable-packages to see if it helps

**Comment by harsszegi** [comment]
Actually we execute “conan install” with “—no-imports” and then separately we run a “conan imports” step after build

**Comment by harsszegi** [comment]
Anyhow closing it, as we can switch to deploy as well :). Thanks @memsharded
