### ISSUE TITLE
[question] build library for `settings_target` in build context

### ISSUE THREAD

**Issue by mattyclarkson** [conan-io/conan#12989]
### What is your question?

I would like to do the following:

```
def build_requirements(self) -> None:
    self.????_requires("library/0.0.0")
```

And have that library built for the `setting_target`.

It needs to be in the `build` context as I only need it when _building_ the parent package.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by mattyclarkson** [comment]
Something that does:

parent (`host` context):
- target: aarch64-linux-gnu
- host: x86_64-linux-gnu
- build: x86_64-linux-gnu

child (`build` context):
- target: none
- host: aarch64-linux-gnu
- build: x86_64-linux-gnu

Currently, the other options are:

`test_requires` (`build` context)
- target: none
- host: x86_64-linux-gnu
- build: x86_64-linux-gnu

`tool_requires` (`build` context)
- target: x86_64-linux-gnu
- host: x86_64-linux-gnu
- build: x86_64-linux-gnu

I need the dependent library in the target context:

`????_requires` (`build` context)
- target: none
- host: aarch64-linux-gnu
- build: x86_64-linux-gnu

**Comment by memsharded** [comment]
Hi @mattyclarkson 

Lets try to clarify a bit:

- A library can only be used in the same context that the one requiring it. That means that it can be used as ``self.requires()`` or as ``self.test_requires()`` (to avoid propagation to consumers).
- If a library is being required by something that is already in the "build" context, like ``app`` -(tool_requires)->``cmake``-(requires)->``lib``, then ``lib`` will be in the build context, even if it is a regular ``requires`` from ``cmake``.
- A ``requires`` relation means a "include library headers + link" relation, implying always the same context as the consumer. A ``tool_requires`` relation means "I need some application to run to build myself", so that implies always the "build" context.
- There is no way back from the "build" context to the "host" context. As it is impossible to link a library from the host context into something in the build context, it cannot be a requirement.

So I would say that what you are trying to achieve (just a guess, not fully clear what is your final intention) is to create a "toolchain" package that contains libraries for the target (same as host) context while being in the build context, but from Conan packages. This is not a supported scenario out of the box, so your best bet would be something like a "re-package" approach:
- Something client side that "conan install" the things you want to repackage, with the "host" profile
- Copy the binaries, with ``generate()`` ``copy()`` calls or something similar
- Create the package, re-packaging those binaries with the "build" profile. Now that package will contain executables for the build profile, plus libraries from the host profile, that when being used, they will match the target settings.
- This can be highly automated in Conan 2.0 with a custom command.

Please let me know if this clarifies a bit.

**Comment by mattyclarkson** [comment]
All makes sense, it felt like I was pushing against what Conan wanted to do. Thank you for the detailed explaination 🙇 

I am indeed attempting to package up dependencies into a `sysroot` package.

Trying to get Conan to fully bootstrap itself. 

> Something client side that "conan install" the things you want to repackage, with the "host" profile

That makes sense now you mention it. I'm unsure how to reinvoke Conan with the same settings as the current Conan package.

What is the _best_ way to do that within Conan?

Currently I have:

```py
    def requirements(self) -> None:
        self.requires(f"glibc/{self.settings_target.libc.version}")

    def source(self) -> None:
        pass

    def build(self) -> None:
        sysroot = self.build_path / "usr"

        linux = Path(self.deps_cpp_info["linux-headers"].rootpath)
        glibc = Path(self.deps_cpp_info["glibc"].rootpath)

        copy(self, "*", linux, sysroot, excludes="conan*.txt")
        copy(self, "*", glibc, sysroot, excludes="conan*.txt")

    def package(self) -> None:
        copy(self, "*", self.build_path / "usr", self.package_path / "usr")

    def package_info(self) -> None:
        self.conf_info.define("tools.build:sysroot", f"{self.package_path}")
```

So this could move towards something like:

```py
    def source(self) -> None:
        pass

    def build(self) -> None:
        # The `deploy` generator seems mostly ideal for this?
        # How do I know what profiles/options to pass??
        # Can I re-use the Python APIs to do this automatically?
        self.run(f"conan install -g deploy glibc/{self.settings_target.libc.version}")

    def package(self) -> None:
        copy(self, "*", self.build_path / "usr", self.package_path / "usr")

    def package_info(self) -> None:
        self.conf_info.define("tools.build:sysroot", f"{self.package_path}")
```

In terms of full bootstrapping, I need to add `gcc` to both the `host`/`build` as a `tool_requires` so that I can get a host compiler and a target compiler. That is currently blocked by [this](https://github.com/conan-io/conan/blob/86839177b48ca20f0e92aace1b1d599d7e31d336/conans/client/graph/graph_builder.py#L241). Is there a tracking ticket for that at all?

**Comment by mattyclarkson** [comment]
Feels hacky but works:

```py
    def generate(self) -> None:
        # The system root needs to be for the `target`
        # There is no way in Conan to get back into the host context from the build context
        # We must repackage the other packages in the correct context
        # TODO: use the Conan Python API rather than reinvoking Conan
        # _Probably_, using `conans.client.manager.deps_install`
        from sys import argv
        from shlex import join
        conan, *rest = argv
        ref = f"glibc/{self.settings_target.libc.version}@{self._channel}"
        host = (f"--settings:host={k}={v}" for k, v in self.settings_target.items())
        build = (f"--settings:build={k}={v}" for k, v in self.settings_build.items())
        # TODO: need to forward on the original arguments but _not_ the profiles to prevent circular invocations
        install = (conan, "install", ref, "--generator=deploy", *host, *build)
        self.output.info(f"Repackaging: {ref}")
        self.run(join(install))
```

**Comment by mattyclarkson** [comment]
That works when adding the package to the profile `[tool_requires]`

However, doing `conan create --build-requires recipe/sysroot 0.0.0@` does not add the `settings_target`.

From the documentation, that seems to the reason for `--build-requires`.

**Comment by mattyclarkson** [comment]
Gonna close this as have something working.

Still not sure how `--build-requires` works with `conan create` but that can be another question sometime.
