### ISSUE TITLE
Copy files instead of git clone in source() method 

### ISSUE THREAD

**Issue by stevn** [conan-io/conan#12993]
### What is your question?

In the source() method of my conanfile.py I need to know where the original directory of the original conanfile was located when I called conan create.

I need this because I need to copy files from a relative path from this “origin” dir to a relative path in the Conan source dir.

I cannot just call git clone in this case.

And I also cannot export all sources together with the package. The package can only hold compiled binaries and shall not hold the sources.

I can access the location of the conanfile.py via self.recipe_folder. However this points to the exported conanfile.py, not the original one, at least in the source() method.

So I have observed that the recipe_folder points to different locations based on the phase of the Conan package creation. This is a bit confusing sometimes and I wonder if this is a good idea. Maybe using different variable names for different things would be better.

I have found a workaround by storing the original recipe_folder in the first call to the init() function, but I consider that to be a bad hack.

Maybe there should be something like a self.origin_folder which is available at least in the source() method.

I might also be missing something else. I sometimes get confused what the current working directory is in which function for example. It seems to be adjusted as well, based on the phase of the Conan package creation, if I recall correctly.

It is my understanding that the source() method is required for compatibility with Conan 2.0 and it replaces the scm attribute. However it seems that copying files from the “origin” dir (dir of the original conanfile.py) to the source folder was done automatically with the scm attribute, while it is not supported in the source() method.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @stevn 

Thanks for your question.
It is not possible to have access from the source method to the original source folder in user space in the general case.
I think you are looking for the scm approach, that executes in the ``export()`` method. Please have a look to: https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature

- In the ``export()`` method you capture the "coordinates" of the git repo (url and commit), and store them in the ``conandata.yml``
- In the ``source()`` method, the "coordinates" of the git repo can be loaded from ``conandata.yml`` to do a clone & checkout from the repo.
- This method will not store the source code in the recipe or package, so it is safe, code is not distributed.
- This method achieves reproducible builds, which are very important for Conan. If a given package binary is missing later in time for some reason (like adding a new configuration, a new compiler version...), it is very easy to build that new binary from the recipe, just ``--build=missing``, and the recipe will know how to checkout the sources

Please try that and let us know.

**Comment by stevn** [comment]
Hi @memsharded,

thanks for your quick answer!

Yeah that's basically what I'm doing.

The thing is that in certain situations Conan isn't the only tool doing the builds. Other tools may be involved that provide some other files.

I can write those relative paths to these temporary files into the conandata.yml via update_conandata(), and then copy the files in the source() method. However this means that if I run the Conan create command from different relative paths (i.e. on different machines/OSs) I don't get the same conandata.yml file, which means I get multiple recipe revisions.

I understand that the origin folder isn't always available in the general case. However, in those cases where it is available, it should be accessible IMHO.

**Comment by memsharded** [comment]
> I can write those relative paths to these temporary files into the conandata.yml via update_conandata(), and then copy the files in the source() method. However this means that if I run the Conan create command from different relative paths (i.e. on different machines/OSs) I don't get the same conandata.yml file, which means I get multiple recipe revisions.

Yes, certainly the update_conandata() should be reproducible, as the Conan ``source()`` assumes uniqueness of sources for all configurations and builds. The problem with escaping the uniqueness of sources is that the immutability assumption, and thus all the ``revisions`` management would be broken. Having a pointer to the "origin" folder in the ``source()`` method means that the sources can change and be something different at different invocations with exactly the same recipe revision. This will certainly not work, because once a revision exist, Conan will assume that things are there, and it will no longer execute methods like ``source()``, resulting in users extremely confused changing their code in their folder and Conan not taking the changes.


If the process really needs local information, it means that it is not reproducible in other machines with ``conan install --build=*``, because it will not be able to access the "origin folder" anymore. In that case, have you considered the ``conan install . `` + ``conan build .`` (locally in user folder), and ``conan export-pkg`` instead?

**Comment by emnkoksal** [comment]
@memsharded  I have needed to do exactly the same with @stevn . Let me explain why. I have 2 scenarios:

1- I develop locally on my development enviroment. 

I do almost every thing manually. Conan is only used maybe to retrieve some binaries that are on our repo.
But also before uploading to git, I try to build the project with "conan create". I do not care about the final package, nor recipes,  if reproducible, etc. nothing! Why do I do that then? It is just a "test" before our CI/CD tools to mostly ensure that my conanfile.py is correct and there is not silly error or some thing. I want to catch it before CI/CD fails before that way is longer and disturb other developers and pushing on git some thing that will fail is not desirable.

So, in this case, I just want to build through conanfile.py using sources on my local folder and that's all!

I could just copy sources from my original folder to conan cache folders in source() method, but for some reason I can't explain this copy process (even just one CMakeLists.txt file, through export, export_sources, copy, does not matter) takes minutes (We had already begun to discuss this here: https://stackoverflow.com/questions/76456294/how-can-build-my-project-with-conan-without-copying-sources/76456746), so it is unusable and I could not do it. Thus, I must do the same hack: taking original source folder path at the beginning, then use it in later calls of conanfile methods.

In conanfile.py itself also I do not care about retrieving the source code from git. Why? Let see 2. scenario.

2- Our CI/CD tools triggers pushes on git and when it detects, it starts doing these steps:

- Prepare its own docker.
- Create a new docker container that is used to build my project from indicated docker image.
- Retrieve the source code from GIT repos that is being triggered
- So, at this point, every thing is "fresh", there is nothing on cache, and now starts running our scripts that we provide for CI/CD. Guess what our script calls: conan create:
In CI/CD also I did not care downloading source codes in conanfile methods, because as you see, CI/CD already does it preparing build environment.
- Thus, for CI/CD also the only thing I need is that conan uses what it finds where it is launched! So, the same hack that I do in my local works also here! I keep original source folder and use it in next steps.
- Finally, when the package is created, it is uploaded to conan server.
  Here maybe I need to learn some more: Doing this way, if there is no change configuration-settings-options but there is change only in sources which are not being exported, then conan generates the same recipe (or should we call it hash? or package_id? or? Here also I am not clear, they look so similar)? 
Should recipe change also when source codes changes? What would happen if recipe is the same?
Anyway, to not deal with all these doubts (and it is not intuitive to get all these reading only conan documents), before uploading, through scripts I am checking if there is the same version in our conan server, to not accidentally overwrite it.

From conan documents, it is possible to get some good practices but, when we have different scenarios, as you see, we are being lost a little, then we have to "solve" it somehow on our own.
Of course, I would like to clear these concepts, these steps, but...

**Comment by memsharded** [comment]
I think the above is summarized by:

> Should recipe change also when source codes changes? What would happen if recipe is the same?

The answer is yes. There must be something in the recipe that uniquely identifies the original source, and as it becomes part of the recipe it will create a new recipe revision. Please check https://docs.conan.io/2/tutorial/versioning/revisions.html if you haven't yet.

The case where the recipe do not uniquely address the original source code is not considered (there is the ``export-pkg`` for creating binaries directly without source, but if the recipe contains a build() from source, then the source must be uniquely identified). Because once a package is in the cache it must be possible to do a ``conan install .. --build=mypkg/*`` and force the rebuild from source from any machine. If you don't want that reproducibility, then you can safely use ``conan build`` + ``conan export-pkg`` in Conan 2.0 (``conan build`` already does a previous ``conan install`` in 2.0), and you won't need to care about sources at all. But if we want packages to be able to build from sources there are only 2 alternatives (irrespective of Conan, just as a work flow):

- Do a copy of the files
- Capture some absolute "coordinates" of the code, like git url and commit, or use any other absolute and unique coordinates of the code that can be used to uniquely reproduce from that exact source the same package binary.

As a principle: if the source code changes, but the recipe revision doesn't change, that is an error and the packages are not reproducible. The Conan docs already contains warnings against this, for example if using just the HEAD of a git repo, check the ``Important`` note in the link above.

So based on your inputs and:

> So, in this case, I just want to build through conanfile.py using sources on my local folder and that's all!

It seems that what you want is freedom to build as you want and then create the binary, so ``conan build`` + ``conan export-pkg`` will achieve exactly that without violating the promise of reproducibility and immutability (note the ``export-pkg`` can define ``build_policy = "never"`` to express this, and fail with a better error if consumers try to build it from source)

**Comment by emnkoksal** [comment]
Thanks for your comments.

You have skipped the second part (CI/CD) of my comments but I think that was the main part because it explains why I do not care about reproducibility when working in my local: Usage of conan in local is just a pre-test before CD/CI.
Otherwise, to build and export and generate package, locally cmake (and cpack) is sufficient and we do not need another dependency, like conan (consider that 95% of developers do not know about conan).

I see that the conan aims to be only-responsible of "reproducibility", but in our case our CI/CD tools already do some (or most) of the job. CI/CD triggers git commits and for every commit, it prepares the development environment and build from source of that commit. So, there, the main concern is to use conan correctly together with CI/CD to generate unique packages.

Then I also saw this:
[https://docs.conan.io/1/developing_packages/package_dev_flow.html](url)

It tells about local development scenario. It was useful.

> as it becomes part of the recipe it will create a new recipe revision

I am thinking `recipe == conanfile.py` (Am I right about this?). Thus, change in source code does not necessarily mean change in conanfile.py, so does not change recipe. The link that you provided about revisions seems that it will make me understand this better. Thanks!

> you won't need to care about sources at all

You mean that "no need to care copying sources to cache", right? Because when doing `build` we need source codes but this would not happen in conan cache, so, directly use from source_folder that I provide.

**Comment by memsharded** [comment]
> Otherwise, to build and export and generate package, locally cmake (and cpack) is sufficient and we do not need another dependency, like conan (consider that 95% of developers do not know about conan).

> I see that the conan aims to be only-responsible of "reproducibility", but in our case our CI/CD tools already do some (or most) of the job. CI/CD triggers git commits and for every commit, it prepares the development environment and build from source of that commit. So, there, the main concern is to use conan correctly together with CI/CD to generate unique packages.

One of the advantages of using Conan is that any developer can easily build and reproduce things locally in their machines without needing the CI. Just ``xxxx install`` and get your local dependencies to develop. This is how it works in basically every other programming languages, so it is well proved to work.

Also, for CI flows, Conan focus and can be used to create CI flows at scale, in which modifying a package in the middle of a dependency graph with hundreds of packages can be processed optimally (``conan graph build-order`` and using lockfiles) to re-build only what is necessary down the graph, in the right parallel order, without needing to duplicate the whole dependency graph in the CI system. But it also relies on ``--build=xxxx`` in which Conan should be able to build things in the cache with reproducibility of the source origin.

> I am thinking recipe == conanfile.py (Am I right about this?).

Not exactly. recipe == conanfile.py + conandata.yml + any other file that is exported (exports or exports_sources.

Even if the conanfile.py doesn't change, the exported files will change or the conandata.yml. The ``conandata.yml`` can also be modified dynamically, capturing the current commit dinamically with ``Git()`` helper in the ``export()`` method.

It is indeed possible that the code changes, but the recipe not. The easiest example is ``Git(self).clone("https://github.com.../repo")``. That will always get the latest HEAD which is a moving target. This is undefined behavior for Conan and not allowed (users can still do it, but it is documented that it shouldn't be done).

> You mean that "no need to care copying sources to cache", right? Because when doing build we need source codes but this would not happen in conan cache, so, directly use from source_folder that I provide.

Yes, with the ``build + export-pkg`` flow, the sources are never copied to the cache, and the build happens locally in user folder not in the cache, so all the temporary build files are not in the cache either. It seems for your CI-only workflow it would be the best approach.
