### ISSUE TITLE
[suggestion] Add ability to specify python_requires (like tool_requires) in the profile

### ISSUE THREAD

**Issue by timviola-cmi** [conan-io/conan#13009]
### What is your suggestion?

In our context there are some methods we are supplying as python_requires for users to call as part of their conan package build process. However, we'd like to specify the python_requires as part of our profiles (just like tool_requires) which we deploy via conan config install so that users are not responsible for knowing the correct version of the python requires, just the correct conan config.

I'm looking for feedback as to whether this can be considered and if it is not feasible (or just simply not a good idea).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @timviola-cmi 

We have considered this in the past, but it seems that it wouldn't be the best approach. The fact that it might be ok for ``tool_requires`` in some occasions, is because it allows to use system installed tools, and inject them cleanly, for example ``cmake`` is something that developers might have in their system, and prefer to use it over the Conan package one. And this is the reason ``tool_requires`` can be defined in profiles.

On the other hand, ``python_requires`` are completely exclusive of Conan, not something that would be installed in the system.
The flow that you define might be implemented better with classic version-range approach:

- Use version-ranges to define in-recipe ``python_requires = "mytool/[>=1.0 <2.0]"``
- The version that users will use is determined by the version that you publish to the server.
- Versioning schemes might allow fine tuning and testing of new versions, for example, python_requires within a valid range, can also be managed by lockfiles, so they can be introduced, tested at scale without breaking the builds and ongoing things, and only merged and made available once the build is green.

This approach has several advantages, for example it allows fine control and gradual updates, when introducing a breaking ``mytool/2.0`` new version, it will not be necessary to fix all recipes at once, which can be an extremely painful process (you cannot put that easily ``mytool/2.0`` in the profile without breaking everything, and you cannot either fix locally a recipe to use it, because the version that you use would be overriden by the profile one). We have seen this, and pushing breaking changes of something like a basic tool (and it will happen) over a whole dependency graph at the global level, can be a big pain. Also, as defining it per-recipe, it means that it is not strictly necessary that all recipes use that python-requires, that mean it will be more efficient. Otherwise, when introducing a change in the "tool" python-require, you might be enforcing a re-build of all packages, even those that do not really use the ``python_require`` functionality, but as it was injected to the whole graph, it will happen this way.

In general, the idea is what you said ``users are not responsible for knowing the correct version of the python requires``, and indeed, the only thing they should know is that they are using the "tool" in the current active/valid range (that can last months, until next breaking change), and the maintainers of the "tool" control what is being pulled in the builds by managing the versioning they release.

**Comment by timviola-cmi** [comment]
Appreciate the quick response @memsharded. I'll close this issue for now and we'll look into the approach you've recommended
