### ISSUE TITLE
[feature] conan search (and conan list) should make the reference option and when omitted treat the reference as "*"

### ISSUE THREAD

**Issue by hpe-ykoehler** [conan-io/conan#13025]
### What is your suggestion?

Passing * in command is sometimes problematic, since shell can interpret those and convert them to list of files in the present folder.

Using something like "all" or "" is better, for example

"conan search *" <-- can cause issue"
"conan search --all" or "conan search all" would never cause issue
"conan search" would be also backward compatible with conan1 where the reference was optional.

```
$ conan search -r all --raw
usage: conan search [-h] [-f FORMAT] [-v [V]] [--logger] [-r REMOTE] reference
```
Suggesting to convert to:
```
$ conan search -r all --raw
usage: conan search [-h] [-f FORMAT] [-v [V]] [--logger] [-r REMOTE] [reference]
```

same for conan list

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @hpe-ykoehler 

Thanks for your suggestion

We have re-built the command line for 2.0, and we did the ``conan list`` command to use patterns. And the ``*`` is a pattern, it is not just a place holder. You can ``conan list z*`` and it will list ``zlib``, ``zlib-ng``, ``zscale``, etc. It is not possible to use a different placeholder, because ``conan list zall`` cannot be parsed, and it has risk of conflicting with real package names. So the ``*`` is necessary and it is the most expected pattern characters for users.

We didn't default those commands to "*" to align them with ``upload``, ``download`` and ``remove``, which in 2.0 will take exactly the same pattern expressions. If we allow ``conan list`` to default the argument to ``*``, we should also default (we did some good effort in 2.0 so the commands are more consistent) ``conan remove`` and ``conan download`` and ``conan upload`` to ``*``, and that is probably not good.

I'll check with the team to get more opinions on this UX.

**Comment by hpe-ykoehler** [comment]
I think there is a difference to be made for conan list and conan search in term of when a reference is not specificied.  I do not think it would make sense to have "conan remove" have a default such as "*", as the command is disruptive.  Where is command such as search or list normally assume that no argument means all, in the same way "ls" and "rm" works in linux, you can still do "rm *" but "rm" will never default to that.

Same for upload/download because those impact the disk.

**Comment by memsharded** [comment]
I have been discussing with the team, and it seems the "consistent" form of mandating always the pattern argument is generally preferred (75%-25%). As with all things UX, it is also a matter of taste, personal experience, different platforms, etc.

So:
- Both commands will require ``conan list "*"`` and ``conan search "*"`` (if searching all references is the desired behavior, of course)
- We will do our best to document always with the "quotes"
- Quoting "*" will still be extensively needed in Conan command line, it is used in many arguments, so knowing that shell expands unquoted *, would be necessary knowledge in any case

Thanks very much for the suggestion!
