### ISSUE TITLE
[bug] sometimes `conan info` wants to download a binary package

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#13024]
### Environment details

* Conan version: 1.58.0
* Python version: 3.9.9

### Steps to reproduce

Our workflow is to do a 
```
conan remote disable *
conan info --profile default pkga/0.9.9@ 
conan remote enable *
```

Usually this works perfectly, and it makes sure that our internal CCI does not have any recipes removed.
Yet when I don't modify the recipe, but a file which is exported with `export sources`,  I sometimes get some kind of error:
```
conan info --profile default pkga/0.9.9@ 
pkga/0.9.9@: WARN: The package pkga/0.9.9@:96f5122383318fb0b29bd75a76b20a51004d12d4 doesn't belong to the installed recipe revision, removing folder
pkga/0.9.9@: ERROR: Error downloading binary package: 'pkga/0.9.9@:96f5122383318fb0b29bd75a76b20a51004d12d4'
ERROR: Remote 'artifactory' is disabled
ERROR: Command 'conan info --profile default pkga/0.9.9@' has failed
```

After deleting the `pkga` folder from the cache, everything works as expected.

**Comment by memsharded** [comment]
Hi @KerstinKeller 

I think I know what is happening, first the error message ``Error downloading binary package`` is wrong. It is not actually trying to download the binary package, but it is trying to get the metadata (like existence or not) data from the remote. 

This is necessary because doing changes in the sources creates a new recipe revision, that invalidates the existing binaries in the cache, and then the ``conan info`` will need to look for the binaries in the remotes. As the metadata for the recipe keeps the association to the remote, it will track it and fail because it is disabled.

The most immediate workaround that I could think at the moment is doing a ``conan remote remove_ref pkga/0.9.9`` when you do the ``conan export`` of the source changes. I will try to look for something more automatic, but seems unlikely, because this association is very in the core of 1.X. (Also, this will not happen in Conan 2.0, because that association with remotes have been removed)

**Comment by KerstinKeller** [comment]
Hi thanks for the quick update. Ok, the reasoning makes sense.
It is not critical for us, as we can "just" clean the cache, and I will also try the `conan remote remove_ref`.
If this is not an issue in 2.0 then I will close this issue.
