### ISSUE TITLE
[bug] Deprecate MesonDeps

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#13048]
### Environment details

Latest 1.58, all OSs and versions

### Steps to reproduce

MesonDeps cannot transmit transitive dependencies information, so it seems quite useless:

- It is not used in ConanCenter yet
- It is not tested in the test suite to cover the case of transitive dependencies

So it is not clear the value proposition of MesonDeps then, better remove it, at least from 2.0, until it becomes clear.

**Comment by SSE4** [comment]
MesonDeps as a new generator to create an extra file with all the GNU flags from all the dependencies.
I think it was initially added by @franramirez688 to fix https://github.com/conan-io/conan/issues/10683 https://github.com/conan-io/conan/issues/11397 https://github.com/conan-io/conan/issues/11398.
a PR adding it was https://github.com/conan-io/conan/pull/11557
I don't think it should be removed, as it will introduce a massive breakage to recipes using it.
e.g. it's a part of our [template](https://github.com/conan-io/conan-center-index/blob/7ed30a9de72fb9f3b3be9a8ff19b5a2e61c4d902/docs/package_templates/meson_package/all/conanfile.py#L118). therefore, everyone who copied from this template would be affected.
if it's strictly needed to remove, there should be some clear drop-in replacement (e.g. `MesonDeps2` or whatever).
perhaps, a major use-case is to locate dependencies, which are not normally found via `pkg-config`. you just add some include and link directories (`-I` and `-L`), and they are found directly.

> MesonDeps cannot transmit transitive dependencies information

according to [doc](https://docs.conan.io/en/latest/reference/conanfile/tools/meson/mesondeps.html):

[MesonToolchain](https://docs.conan.io/en/latest/reference/conanfile/tools/meson/mesontoolchain.html#conan-meson-toolchain) normally works together with [PkgConfigDeps](https://docs.conan.io/en/latest/reference/conanfile/tools/gnu/pkgconfigdeps.html#id1) to manage all the dependencies, but sometimes we need to gather some flags coming from Autotools tool so that’s what MesonDeps is meant for. In other words, it is typically used when Meson cannot find a dependency using the already known [detection mechanisms](https://mesonbuild.com/Dependencies.html) like: pkg-config, cmake, config-tool, etc. For instance, if we’d have these lines in your meson.build file, you might need MesonDeps to find that dependency and inject the correct flags to the compiler:

**Comment by memsharded** [comment]
> I don't think it should be removed, as it will introduce a massive breakage to recipes using it.

It is used solely by 1 recipe in the whole ConanCenter, so this is not massive breakage, but would completely negligible.

**Comment by SSE4** [comment]
> It is used solely by 1 recipe in the whole ConanCenter, so this is not massive breakage, but would completely negligible.

there are also forked recipes and private recipes in enterprise environments

**Comment by memsharded** [comment]
If there are forks, they will contain at most 1 package with it.
And I do tons of conversations and calls with enterprises, still to find one that is using this very new and experimental component.

This wouldn't be a massive breakage. And I am considering it for a reason: it doesn't work as it advertises. It cannot propagate link information by itself. When used together with PkgConfigDeps there will be most likely duplicated paths and flags. So the whole thing needs to be reconsidered.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan-center-index/pull/16014 works without MesonDeps, so no recipe in ConanCenter actually depends on MesonDeps

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/13134
