### ISSUE TITLE
[question] Setting shared=True using python_requires

### ISSUE THREAD

**Issue by Tobulus** [conan-io/conan#13058]
### What is your question?

Hi!

We have a "base" recipe used by all our conanfiles using python_requires to define some basic stuff.
In general we link our direct dependent libs dynamically, so I wanted to handle this there.

Using `default_options` and `*:shared=True` is not what I want as this doesn't influence just the "direct" dependencies.
Doing this dynamically in some of the methods seems also not possible as the dependency infos are only available when the options are read-only.

Am I missing a possibility to handle this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tobulus 

Thanks for your question.

I think I'd need a bit more of detail. You say that you don't want all dependencies to be shared, only direct ones. But you also want to do that in a ``python_requires`` that will be reused by all other recipes, so that means that it will be applied to all of them, and it will make all ``shared=True`` in practice.

You also need to ensure you are not using the legacy python-requires but the new ones. It would also be useful to see if you are using the extension mechanism of ``python_requires_extend`` or not.

Without a clear idea of what you need, maybe the missing piece you are looking for is the ``init()`` method, that allows to perform some logic over the base extension: https://docs.conan.io/en/latest/reference/conanfile/methods.html#init

**Comment by Tobulus** [comment]
A typical module looks like this:
```
class ModuleConan(ConanFile):

    python_requires = "conan-base/1.0.0"
    python_requires_extend = "conan-base.FooBarCmakeConanFile"
    requires = ("libbsd/0.10.0", "libsystemd/251.4")
    default_options = {
        "libbsd:shared" : True,
        "libsystemd:shared" : True
    }
```
As I don't want to define in every module that my dependencies should be `shared`, I wanted to move this into the module we are extending from.

To my understanding the `init()` method will not work as you [can't iterate](https://docs.conan.io/en/latest/reference/conanfile/dependencies.html) the dependencies there.

In theory something like this:
```

​for require, dependency in self.dependencies.items():
            depShort = dependency.ref.name + ':shared'
            depLong = dependency.ref + ':shared'
            # link direct dependencies dynamic per default: don't touch the setting if it was
            # set manually in a projects recipe
            if not (self.options[depShort] or self.options[depLong]) and (require.direct or require.test):
                self.options[dependency.ref + ':shared'] = True
```

**Comment by memsharded** [comment]
Maybe defining a ``configure()`` method in the base class that iterates ``requires`` (might need to split them, they would be in raw format at this point) and define ``self.options[myreq].shared=True``?

Still the net effect seems the same as a very simple ``*:shared=True``, if that ``python_require`` will be used by all other recipes, everything will become shared.

Also, in the general case, it is recommended that recipes do not mess too much with options values, and instead those are defined at the ``profile`` level.

**Comment by Tobulus** [comment]
> Maybe defining a configure() method in the base class that iterates requires (might need to split them, they would be in raw format at this point) and define self.options[myreq].shared=True?

Thanks, I will take a look!

> Still the net effect seems the same as a very simple *:shared=True, if that python_require will be used by all other recipes, everything will become shared.

Yes, but for 3rd party libs I don't want to do this. `*:shared=True` propagates down the whole dependency chain (right?) and from time to time libs don't even support to link their dependencies shared.

Thats why I only want the direct dependencies to be linked dynamic. For the others I want to use  the default or configured in their recipes.

> Also, in the general case, it is recommended that recipes do not mess too much with options values, and instead those are defined at the profile level.

Hm, thats a good hint.

**Comment by memsharded** [comment]
> Yes, but for 3rd party libs I don't want to do this. *:shared=True propagates down the whole dependency chain (right?) and from time to time libs don't even support to link their dependencies shared.

> Thats why I only want the direct dependencies to be linked dynamic. For the others I want to use the default or configured in their recipes.

Just in case, be aware that mixing shared with static libraries is typically challenging, and it can be even very evil and have multitude problems, because every shared library will contain a copy of the static libraries they are using (binary size bloat), and if the static libraries have some kind of global state, then their usage might be broken. Linking shared libraries to static libraries is a kind of encapsulation of the static library that must be managed carefully. 

At least, Conan 2.0 will have better handling and modeling of these shared->static relations, but in Conan 1.X it might also be quite challenging at times.
