### ISSUE TITLE
Ask a simple question

### ISSUE THREAD

**Issue by dbyoung720** [conan-io/conan#13064]
### Environment details

* Operating System+version: Win10X64
* Compiler+version: VS2022
* Conan version:1.58.0
* Python version:3.9

I create test.cmd :

@echo off
set HostParam=--settings:host
conan.exe install f:\zlib\1.2.13 --build missing %HostParam% arch=x86 %HostParam% build_type=Release %HostParam% "compiler=Visual Studio" %HostParam% compiler.version=17 %HostParam% compiler.runtime=MT %HostParam% compiler.toolset=v143 %HostParam% compiler.cppstd=17
pause

Why compilation cannot be triggered. What other commands need to be executed?
Thank！

**Comment by memsharded** [comment]
Hi @dbyoung720 

Thanks for your question
It would be needed a bit more of detail. Please provide:
- Provide a bare ``conan install ...`` command without the .cmd file artifacts, to rule out possible issues with that
- Provide the input file you have in ``f:/zlib/1.2.13``
- Provide the command line output of running the command, including the error messages

**Comment by dbyoung720** [comment]
f:/zlib/1.2.13, Put the source code of zlib 1.2.13.
No errors. There is only no compilation process. I expect to see the compilation process.
![Untitled](https://user-images.githubusercontent.com/11304997/217203582-a8261802-3959-43b2-818d-802cbaa1bc21.png)

**Comment by memsharded** [comment]
Thanks for the info.
I was interested in the ``conanfile.py`` that should be located in the ``f:/zlib/1.2.13``, because that is the main file to be used.

Also, the issue seems that you are confusing the ``install`` command with the ``create`` one.
- ``conan install`` will install the **dependencies** of the file you are feeding. In this case it would install the dependencies of your ``conanfile.py`` for zlib, and it it doesn't have any dependencies it will install nothing
- ``conan create`` would be the command actually creating a Conan package from the user ``conanfile.py``.

If you are learning Conan at this moment, I'd suggest to follow the 2.0 new tutorial first: https://docs.conan.io/en/2.0/tutorial.html (it is in beta, but will be final this month).
If for some reason you are forced to use 1.X, you need to check:
- https://docs.conan.io/en/latest/getting_started.html
- https://docs.conan.io/en/latest/creating_packages.html

And there is also a great free video course in: https://academy.jfrog.com/path/conan

**Comment by dbyoung720** [comment]
Yes, I learning Conan just.
OK, Thanks!

**Comment by dbyoung720** [comment]
I Copy dir "conan-center-index\recipes\zlib\all" files  to f:/zlib/1.2.13.
The above prompt will appear
![Untitled](https://user-images.githubusercontent.com/11304997/217207446-af7b867b-5b70-4935-b024-0782bf2ecbca.png)

**Comment by memsharded** [comment]
> I Copy dir "conan-center-index\recipes\zlib\all" files to f:/zlib/1.2.13.

I suggest not copying folders, but instead run directly from your conan-center-index fork, cloned into your folder.
