### ISSUE TITLE
[feature] add an os.version settings so that we can indicate against which kernel header app is compiled.

### ISSUE THREAD

**Issue by hpe-ykoehler** [conan-io/conan#13079]
### What is your suggestion?

On Linux, we need to understand what kernel header was used if the application or component query kernel API, on Windows I believe there is the same concept.

Like conan does for settings.compiler.version, I think there should be an settings.os.version to ensure that the pre-compiled binaries are compatible.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @hpe-ykoehler 

The thing with ``os.version`` is that it is not that well defined, compared with compiler versions. It can vary wildly among OS and distros. So the only possible range of values would be ``version = [None, "ANY"]``. This could be a disaster in terms of binary compatibility, if there is not some convention about values, packages created this way can only be consumed by the same team/company of the people creating this binary. And also it happens that this value would not be used at all by Conan. The built-in default ``settings.yml`` values are there because they are used somewhere by build system integrations or other parts of Conan.

Then, for this use case, the recommendation is not to add them to the default ``settings.yml``, but instead users to maintain their own ``settings.yml`` and distribute it via ``conan config install``. Please check https://docs.conan.io/en/latest/extending/custom_settings.html. 
Conan 2.0 made this even easier with a custom ``settings_user.yml`` (to be documented soon).

**Comment by hpe-ykoehler** [comment]
@memsharded I disagree with you on this.  os is Linux or Windows, those have specific versions that are well known.  This is not a Distro, but an OS, and all Debian/CentOs/Fedora, etc. all use Linux as the OS which has a single version stream.  Same for Windows, each Windows version have a specific version.

And not tracking the version is in my opinion is how you can get into a binary compatibility issue since an application compiled with 4.4.10 may not work on an OS running 3.12.19, as the API that the application may be using may not be there and the binary may be installed and crash on that platform.  It is the same for Windows, an app written for Windows 10 is not going to work necessarily well on Windows 7, depending on which API is being used and if the app has a way to determine availability at runtime.

Syscalls from user space to kernel are often hidden inside a library (libc or others),   So even when the app doesn't appear to have direct OS dependencies it still has via its library dependencies.  Some APIs are more stable than others and will be forward-compatible while others may not be.

**Comment by hpe-ykoehler** [comment]
I will check the custom settings stuff, and see if I can achieve my need with it, thanks.

**Comment by hpe-ykoehler** [comment]
Looking at the ~/.conan/settings.yml, I see:
```
os:
    Windows:
        subsystem: [None, cygwin, msys, msys2, wsl]
    Linux:
    Macos:
        version: [None, "10.6", "10.7", "10.8", "10.9", "10.10", "10.11", "10.12", "10.13", "10.14"]
```


As such it seems that os.macos.version is supported, but not for windows or linux.  Which seems to indicate my point, I think that this macos version should be just os.version and that the value should depend on linux/windows.  As with Mac, both Windows and Linux have specific version, it is just important to track the OS (kernel) and not the Distro version.

**Comment by hpe-ykoehler** [comment]
closing this as being able to change what goes in settings is good enough for me.
