### ISSUE TITLE
[bug] 'conan profile show' skips package settings

### ISSUE THREAD

**Issue by chulup** [conan-io/conan#13126]
### Environment details

* Operating System+version: MacOS 12.6
* Compiler+version: apple-clang 13
* Conan version: conan 1.58.0
* Python version: python3 3.10.6

### Steps to reproduce

```
conan profile new A --force
conan profile update settings.libA:os=Windows A
conan profile show A
```
Actual output:
```
Empty profile created: /Users/me/.conan/profiles/A
Configuration for profile A:

[settings]
[options]
[conf]
[build_requires]
[env]
```

Expected output:
```
Empty profile created: /Users/me/.conan/profiles/A
Configuration for profile A:

[settings]
libA:os=Windows
[options]
[build_requires]
[env]
```

**Comment by memsharded** [comment]
Hi @chulup 

Thanks for your report.
This seems indeed a bug. 
However, this will probably not be fixed, because the recommended approach is no longer depending on the auto detected profile and modifying it with Conan command. Instead the recommended approach is:

- Do not auto-detect profile, but write your own for production. Manage and distribute them with ``conan config install``
- To modify text files like profiles, use text editing commands, but normal text file editors. Conan 2.0 has dropped this kind of commands already.

Also note a couple of other related recommendations:
- All package names must be lowercase
- Patterns should be explicit, like ``pkga*:os=Windows``

**Comment by AbrilRBS** [comment]
Closing this as solved, feel free to reopen/create a new issue should you have any other questions or requests, thanks!
