### ISSUE TITLE
[bug] conan config install does not ask for credentials when cloning repository

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#13122]
### Environment details

* Operating System+version: Windows
* Conan version: 1.58.0
* Python version: 3.10.9

### Steps to reproduce

Attempt to install a shared configuration from a git repository, which requires authentication. Git is configured correctly to access the repository and will ask for the passphrase of an SSH key to access the repository. Conan config install will NOT do that.

Have a repository that contains conan configuration, which is private and requires a passphrase protected SSH key to access.
Run `conan config install github.com:private/profiles.git`
The command will error out with an error about being denied access (Permission denied (publickey,keyboard-interactive))
If the correct SSH key is added to an SSH Agent (or Windows Credentials Helper) prior to running the command, it works just fine.

The command should ask for the passphrase to the SSH key, just like a regular git clone on the repository would.

**Comment by memsharded** [comment]
Hi @Sil3ntStorm 

Thanks for your report.
Yes, it seems this could be an issue, the way the ``git clone`` is run is not interactive (I am a bit concerned about making it interactive, because that is the thing that easily block CI pipelines forever, but that is a different story).

The thing is that it is not something easy to test and reproduce, I am asking @RubenRBS for help with this. I'd say the best way to test it, and then fix it would be:

- Have a test that compiles from source a ``git`` executable that does nothing except asking for some user input and then printing it. Possibly creating an empty folder
- The test would put that executable in the PATH, so subsequent calls will use that instead
- Test the ``conan config install`` functionality with that. 
- Replace the ``detect_runner`` with a full piped cin/cout Popen subprocess
- Test also the new ``from conan.tools.scm import Git`` ``Git.run()`` functionality would be ok and interactive
- Finally, try to provide a way so the subprocess fails if the "interactive" conf is set to False

**Comment by AbrilRBS** [comment]
Hi @Sil3ntStorm, thanks for your patience :). After looking at it and how Conan/Python handle this, I don't think we can do much on our end to help with situations like this. Having interactive subprocesses is a tricky thing and supporting them would add quite a bit of complexity, with high chances of breaking more stuff down the line.

My suggestion here would be to then solve this from the opposite angle if possible and add the key to your SSH Agent as needed before the operation, just as you mentioned. While this might not be ideal, it seems that logging beforehand is the only factible solution. Happy to learn about your usecase further if you feel strongly against doing this!

**Comment by Sil3ntStorm** [comment]
Sorry for the delay. I have worked around this by using an https clone when running on CI, which the CI has access to and is authenticated to access, and expecting developers to have a setup that just allows them access to the repository (ie. running an SSH agent or other means so they're not asked for it all the time).
