### ISSUE TITLE
[question] Using external CMake project with Conan requirements

### ISSUE THREAD

**Issue by skaveti** [conan-io/conan#13166]
### How to use external CMake project in conan project ?

I have a project which uses OpenCV and PCL(Pointcloud library). OpenCV can be downloaded from ConanCenter. I had to manually download PCL from the project website. PCL includes cmake files. I am getting an error when I try to build a project including OpenCV and PCL.

The following `conanfile.py` and `CMakeLists.txt` builds successfully using `conan install` and `conan build`.

<h4>conanfile.py</h4>

```py
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps

class ThirdConan(ConanFile):
    name = "third"
    version = "0.1"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    requires = "fmt/[^9, loose=False]", "opencv/[~4.5]"
    default_options = {"opencv/*:shared" : True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "src/*", "include/*"

    def layout(self):
        cmake_layout(self)

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()
```

<h4>CMakeLists.txt</h4>

```cmake
cmake_minimum_required(VERSION 3.15)
project(third CXX)

find_package(fmt REQUIRED)
find_package(OpenCV REQUIRED)

add_executable(third src/third.cpp src/main.cpp)
target_include_directories(third PUBLIC include)
target_link_libraries(third fmt::fmt opencv::opencv)
# target_link_libraries(third fmt::fmt opencv::opencv ${PCL_LIBRARIES})

install(TARGETS third)
```

After including PCL, I am not able to build the project. The modified `CMakeLists.txt` file is shown below:

<h4>CMakeLists.txt with PCL</h4>

```cmake
cmake_minimum_required(VERSION 3.15)
project(third CXX)

# message(--------------------------------------------------------------------------------)
# message(${CMAKE_MODULE_PATH})

# set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR} ${CMAKE_MODULE_PATH})
# set(CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR} ${CMAKE_PREFIX_PATH})

find_package(fmt REQUIRED)
find_package(OpenCV REQUIRED)
find_package(PCL 1.13.0 REQUIRED)

# include_directories( ${OpenCV_INCLUDE_DIRS} )
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})


add_executable(third src/third.cpp src/main.cpp)
target_include_directories(third PUBLIC include)
# target_link_libraries(third fmt::fmt opencv::opencv)
target_link_libraries(third fmt::fmt opencv::opencv ${PCL_LIBRARIES})

install(TARGETS third)
```

The error log is shown below:

```code
-- Checking for module 'flann'
--
-- Found FLANN: C:/Program Files/PCL 1.13.0/3rdParty/FLANN/lib/flann_cpp_s.lib
-- FLANN found (include: C:/Program Files/PCL 1.13.0/3rdParty/FLANN/include, lib: C:/Program Files/PCL 1.13.0/3rdParty/FLANN/lib/flann_cpp_s.lib)
CMake Error at C:/Program Files/PCL 1.13.0/cmake/PCLConfig.cmake:59 (message):
  search is required but flann was not found
Call Stack (most recent call first):
  C:/Program Files/PCL 1.13.0/cmake/PCLConfig.cmake:354 (pcl_report_not_found)
  C:/Program Files/PCL 1.13.0/cmake/PCLConfig.cmake:538 (find_external_library)
  CMakeLists.txt:12 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/abc123/source/repos/2023/cpp/third/build/CMakeFiles/CMakeOutput.log".
ERROR: conanfile.py (third/0.1): Error in build() method, line 36
        cmake.configure()
        ConanException: Error 1 while executing cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="C:/Users/abc123/source/repos/2023/cpp/third/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\abc123\source\repos\2023\cpp\third\."
```

I think my usage of PCL is correct. I created a simple CMake project and it builds successfully (with conan) using `cmake` and `cmake --build`.

<h4>CMakeLists.txt with PCL without conan</h4>

```cmake
cmake_minimum_required(VERSION 3.10)

# set the project name and version
project(Tutorial VERSION 1.0)

# specify the C++ standard
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

# configure a header file to pass some of the CMake settings
# to the source code
configure_file(TutorialConfig.h.in TutorialConfig.h)

find_package(PCL 1.13.0 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

# add the executable
add_executable(Tutorial tutorial.cxx)

# add the binary tree to the search path for include files
# so that we will find TutorialConfig.h
target_include_directories(Tutorial PUBLIC
                           "${PROJECT_BINARY_DIR}"
                           )
target_link_libraries(Tutorial ${PCL_LIBRARIES})
```

How do I use external CMake projects in conan project ?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Just in case you want to track it: https://github.com/conan-io/conan-center-index/pull/1891 is trying to add PCL to ConanCenter, but apparently there are some challenges, like the huge amount of memory it needs to compile, so it hits infrastructure issues.

To make sure I understand it correctly. Your ``CMakeLists.txt with PCL without conan`` is able to use the PCL library without problems? (You say ``(with conan)``, but I guess you meant ``(without conan)``). The same PCL library built that you are trying to use in the Conan project?

I don't know much about the details of using PCL, what is exactly the ``configure_file(TutorialConfig.h.in TutorialConfig.h)`` in the working case? What happens if you remove it? What happens if you add it to the Conan CMakeLists.txt?

**Comment by skaveti** [comment]
Thanks for the reply.

Yes, I am using the same PCL library. I downloaded the library from [Downloads](https://pointclouds.org/downloads/). In the second example (`CMakeLists.txt with PCL`), I tried to use downloaded PCL with other dependencies from ConanProject. This does not build. In third example(`CMakeLists.txt with PCL without conan`), I used same PCL but but with simple CMake project. I was able to build with similar `CMakeLists.txt`. I am guessing that conan generator is changing cmake module path,

You can ignore `configure_file(TutorialConfig.h.in TutorialConfig.h)`. I copied the code from `CMake` tutorial. It is used for version number and is not relevant. Similarily, the following include directory related code can be ignored.

```cmake
# add the binary tree to the search path for include files
# so that we will find TutorialConfig.h
target_include_directories(Tutorial PUBLIC
                           "${PROJECT_BINARY_DIR}"
                           )
```

**Comment by memsharded** [comment]
>  I am guessing that conan generator is changing cmake module path,

yes, the CMakeToolchain generated ``conan_toolchain.cmake`` is designed to find Conan generated files, but not others. You might need to add somehow the PCL ``cmake`` folder or something like that.

The thing is that there might be library conflicts. OpenCV depends on many other libraries, packages from ConanCenter (more than 30). If PCL tries to link with other libraries that are vendored in PCL, but also exist as OpenCV dependencies, there will be conflicts, duplicated symbols, or other similar issues, because trying to link with 2 different builds of the same transitive dependency. From the code in https://github.com/conan-io/conan-center-index/pull/1891/files, I see that it might easily happen for eigen and libpng. This problem is not straightforward to solve, because it might require patching PCL so the vendored libs are not used, and the packages are preferred. The best bet would probably comment on the conan-center-index PR and request if this could be move forward. We are now super busy with the Conan 2.0 launch, but I hope this will eventually be solved and PCL would be on ConanCenter.

**Comment by skaveti** [comment]
Thank you for the explanation.
