### ISSUE TITLE
Write protect packages

### ISSUE THREAD

**Issue by GrimSqueaker** [conan-io/conan#1317]
Is it possible to write protect headers and source files in the Conan packages?
Sometimes our developers accidentally make changes in the files provided via Conan, because they do not notice where they went via Visual Studio...

**Comment by xylosper** [comment]
What about protect `.conan` folder using permission?
Of course, the user have to acquire permission when installing a conan package in that case.

**Comment by GrimSqueaker** [comment]
I would prefer a solution with as little human interaction as possible.
At the moment our CMake scripts are set up to run "conan install --update" s.t. no developer needs to interact directly with Conan. No need to consult the command line.
I understand that this is probably more out of convenience instead of necessity, but in general: Is there a use case in which the packages should be writable? Only the Conan operations should require write access to the packages, right?

**Comment by memsharded** [comment]
That is an interesting issue, indeed. 
Actually, this is an old-problem in Windows, or in any OS when develoepers installed dependencies manually in user spaces (folders), because accidental modification can happen.

Yes, in theory only conan operations need write access.

The problem I see is that messing with permissions is usually complicated and problematic, always come back to you to bite you later. Consider that conan doesn't require root permissions, so conan is running under the user account, not sure if disabled writes are possible under your own account. Also, depending on the filesystem, it might even not be possible. We have a strong conan design criteria, which is "try never blocking the users". A bug or mistake in the permissions, will block users (can be workaround, but so inconvenient in practice that it is a blocker).

Maybe the issue can be minimized in a couple of ways:
- First, one thing is local development, but packages to be shared with the team should be built and tested by CI, not in developers machine.
- Conan has integrity checks built-in that allows to capture and later verify package manifests for modifications. This is not exactly this use case, but maybe some other option could be added, so modifications in packages are checked and warned. However, if they are not using conan in the command line, then this is not a good approach.

If someone with big Windows-fu knows some way to make the .conan folder only writeable to the "conan" application, that would be useful, please feedback!

**Comment by jcar87** [comment]
What about conanmanifest.txt? 
I'm assuming the values there are hashes of the files ? Perhaps as part of "conan install" checks could be performed to validate the integrity of the files? 

@GrimSqueaker  says that conan install is being called from cmake. If installed returned an error if the packages are invalid, or there was some "conan install --validate-packages", that error could be printed in the cmake configuration stage, perhaps fail it, and alert the users. Or there could be a behaviour in conan where packages are re-fetched (or re-built) if they fail the validation.

**Comment by memsharded** [comment]
@jcar87 I think ``conan install --manifests`` already run a check of the integrity, using the manifests, have you tried it?

**Comment by memsharded** [comment]
I am giving this +1, even if I know it can be problematic and difficult to implement. I don't tend to use the IDE that much or navigate to included headers, but it is true that modifying them is easier than it should be.

Lets try to do some research for 0.26, not guaranteed to implement it, but at least give it some time and have further understanding of the issue.

**Comment by lasote** [comment]
We reached some problems with the permissions management, like uploaded packages with zipped read only permissions. We are not fully sure about the way to resolve it so we are moving it to 0.27 to see if we can find a better solution.

**Comment by memsharded** [comment]
For further reference, this is the ongoing effort: https://github.com/conan-io/conan/compare/develop...memsharded:feature/read_only_folder?expand=1

The thing is that it is impossible to keep clients state consistent, some clients may use the "READ_ONLY" mode, others don't. And there are many ways something could break..

Also as a reference, other package managers like python/pip, does not write protect installed dependencies. I know protecting against errors is good, but I also like the python "zen" about programmers being "adult", so in general I would trust developers not modifying dependencies headers while navigating to them from the IDE.

**Comment by memsharded** [comment]
Added as opt-in, and experimental. Might have issues if developers upload conan packages created with read-only to servers and share with others developers.

**Comment by memsharded** [comment]
CONAN_READ_ONLY_CACHE can be used now for this. Please read:

http://docs.conan.io/en/latest/reference/env_vars.html#conan-read-only-cache

Take into account that  most likely it is not a good idea to upload packages from developer machines that have this activated (not that it won't work, but it might have some side effects)
