### ISSUE TITLE
[feature] `conan profile update`

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#13205]
### What is your suggestion?

Please port `conan profile update` to Conan 2.0. Being able to efficiently update a profile in CI makes command lines shorter and conditional logic much easier. Trying to do that with `sed` is much harder as we have to account for duplications, appending a new entry, making sure that the entry is provided in the correct section, etc.

Here are some example usage scenarios:
https://github.com/mpusz/units/blob/d46377ee160d57b2006ca56ef0f10b169b69dc70/.github/workflows/ci-conan.yml#L244-L250

https://github.com/mpusz/units/blob/d46377ee160d57b2006ca56ef0f10b169b69dc70/.gitpod.yml#L71-L102

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mpusz 

Thanks for your request.

I am afraid that this was a very deliberate thing. We decided that Conan 2.0 will no longer provide commands that are basically doing some editing of text files.

One of the main reasons is that profiles, for example, are now jinja templates. Any kind of loading-modify-save cycle will destroy user profiles. I know that in some cases there will not be jinja template artifacts, but having removed things like the text variable literal macro replacement, using jinja will be more necessary, and having commands that only work in some cases is very problematic.

**Comment by uilianries** [comment]
@memsharded I see more people asking for it on Cpplang Slack too (3 people at least). As Conan team is not inclined to adopt it right now, maybe we could suggest them adding a custom command to mimic `profile update` command.

**Comment by a4z** [comment]
I prefer updating profiles on the fly than having longer command lines.

If a custom command can archive by adding an update command, that would be an awesome tutorial, and I have a valid reason to spend time getting started with custom commands. (sometimes a god reason is essential to get a ticket on the board ;-)

**Comment by memsharded** [comment]
I have some feedback (some learnings from previous experiences) that I'd like to share:

The previous time we did something similar was with the early ``scm`` feature that did some replacement in the ``conanfile.py`` file itself for ``"auto"`` values. Even if we had the Python built-in AST, which is super cool, it was a nightmare of feature. Super fragile and problematic, tons of rough edges, like when using function calls instead of direct values, spacing/tabs being lost, comments, etc.,etc.

We really don't want to go this route again, and if doing Python parsing was hard, doing the equivalent with ``jinja`` would be even more challenging. Note that the ``scm`` scope was very limited, it only applied to a first level class attribute that had to be a ``dict``. The global.conf and profile files jinja syntax can go to any extent in their respective files: variables, nested conditionals,  functions calls, for loops, etc, etc.

**Comment by AbrilRBS** [comment]
Closing, we feel like not providing these features in the CLI is the safest approach now that Jinja2 can be fully leveraged

**Comment by madduci** [comment]
Hello

is there any way to get around this limitation, for CI systems, such as GitHub Workflows, where some properties (e.g. build_type or compiler.libcxx) are overridden on the fly?

**Comment by memsharded** [comment]
Hi @madduci 

It would be good to understand the issue a bit better. In CI workflows, it is good enough to overrides in command line:
```
conan install ... -pr=myprofile_with_release -s build_type=Debug
```
will effectively override the profile build_type with ``Debug``. Why isn't it better than modifying the profile with release on the fly, which might not be even safe in case some other package would be using it?
Furthermore there are a bunch of improvements and features around profiles that you can leverage:
- It is recommended to use ``conan config install`` to manage your profiles. Having a ``myprofile_with_debug`` there should be straightforward
- Profiles are jinja templates, you can do things like ``build_type = {{ os.getenv("MYBUILDTYPE") }}`` if you want to, or have conditionals
- You can have profile composition on the fly, with ``conan install -pr=profile1 -pr=profile2...``

**Comment by valgur** [comment]
I don't have a take on the utility of the profile modification commands, but I think the dropping of Conan config modification commands had the same justification of the added complexity of supporting Jinja making it impractical.

However, isn't the use of Jinja expressions in the config files and profiles more of an advanced use case? I doubt the majority of Conan users have ever made use of them. I'm wondering why you chose not to check for the presence of Jinja expressions in these files and fail gracefully in that case, while keeping the existing config modification commands around for the likely common case of them not being present?

I still kind of miss them and saw it as a step backwards when migrating to version 2.0, even with the added config installation commands.

**Comment by memsharded** [comment]
> I don't have a take on the utility of the profile modification commands,

Profile modification commands were often in 1.X an indicator that too much reliance on the profile automatic detection was being done, instead of using predefined profiles managed with ``conan configuration install``, which is the recommended approach. As commented above it could easily create confusing or problematic situations.

> However, isn't the use of Jinja expressions in the config files and profiles more of an advanced use case? I doubt the majority of Conan users have ever made use of them. I'm wondering why you chose not to check for the presence of Jinja expressions in these files and fail gracefully in that case, while keeping the existing config modification commands around for the likely common case of them not being present?

Here, it would be very good to understand the use case, which are the configurations that are better modified with a Conan command instead of passing them in command line? Why isn't it more convenient to just define things in ``global.conf`` and manage it with ``conan config install``? Do you have any specific scenario, any particular ``conf`` that you are typically setting this way?

**Comment by a4z** [comment]
The automatic profile detection + some Conan profile update commands were for many people precisely what they needed.
That in an ideal world you would have all profiles managed in an extra git repo is another topic, small team, or workflows like the OP linked to, live in a different reality. A reality, that the Conan team seems not respect since the move to 2.0,  as shown again in this story.

**Comment by madduci** [comment]
>     * It is recommended to use `conan config install` to manage your profiles. Having a `myprofile_with_debug` there should be straightforward
> 
>     * Profiles are jinja templates, you can do things like `build_type = {{ os.getenv("MYBUILDTYPE") }}` if you want to, or have conditionals
> 
>     * You can have profile composition on the fly, with `conan install -pr=profile1 -pr=profile2...`

Hi @memsharded, 

thanks for the clarification, but i don't have pre-configured profiles, since i rely on target machine Compiler installation and i don't know in advance which compiler version is installed there, therefore i try to create a profile dynamically, tailored for that remote target. That is my use-case e.g. with GitHub Actions, where i don't know which version of `gcc` or `clang` is available. 

A way to detect the profile and customise it on the fly (switching between dynamic/static runtime for example) would be really a great addition and it's one of the most useful features i miss from Conan 1.x

**Comment by memsharded** [comment]
> That is my use-case e.g. with GitHub Actions, where i don't know which version of gcc or clang is available.

If you are using Github actions, there shouldn't be much of a difference? like between:
```
conan profile update default compiler.runtime=static
conan install ...
```
or
```
conan install ... -s compiler.runtime=static
```
?
Like the second is cleaner and more recommended. If you have more tweaks, you can still put them in a "myprofile" like:
```
include(default)
compiler.runtime=static
# other stuff
```
And then use it as:
```
conan install --pr=myprofile
```
Enjoying both the machine auto-detection and custom configuration with full control and flexibility. In case you need to build more than one package in the same machine or job with different configurations, changing the default profile for that purpose is a very bad idea.

Furthermore you can also use the ``jinja`` templating plus the new ``detect_api`` available to the jinja templates for profiles, so you can also create your profiles that are able to detect the machine compiler with the same logic as Conan and still customize the result at your will. This is more powerful than the ``conan profile update`` command.

**Comment by madduci** [comment]
indeed i'm using now the syntax :

`conan create . --build=missing -s build_type=${{ matrix.build_type }} -s compiler.cppstd=17 -s compiler.runtime=${{ matrix.runtime_type }}`

to cover my needs, the only thing is that's much more verbose.
