### ISSUE TITLE
[bug] Options for tool requires aren't respected in profiles

### ISSUE THREAD

**Issue by sfackler** [conan-io/conan#13215]
### Environment details

* Conan version: 2.0.0
* Python version: 3.10.9

### Steps to reproduce

1. Create a profile that adds a tool requirement and sets an option for it (here I'm just picking zlib arbitrarily because it has an option I can set):

testprofile:
```
include(default)

[options]
zlib*:shared=True

[tool_requires]
zlib/1.2.13
```

2. Install an empty conanfile.txt using testprofile as the host profile:

```
$ conan install --profile:build default --profile:host ./testprofile .
```

### Logs

```

======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=14
os=Macos
[options]
zlib*:shared=True
[tool_requires]
*: zlib/1.2.13
[conf]


Profile build:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=14
os=Macos
[conf]



======== Computing dependency graph ========
zlib/1.2.13: Not found in local cache, looking in remotes...
zlib/1.2.13: Checking remote: conancenter
Decompressing conan_export.tgz
zlib/1.2.13: Downloaded recipe revision 13c96f538b52e1600c40b88994de240f
Graph root
    conanfile.txt: /Users/sfackler/test/conanfile.txt
Build requirements
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Downloaded (conancenter)

======== Computing necessary packages ========
Build requirements
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f:76f7d863f21b130b4e6527af3b1d430f7f8edbea - Missing

======== Installing packages ========
ERROR: Missing binary: zlib/1.2.13:76f7d863f21b130b4e6527af3b1d430f7f8edbea

zlib/1.2.13: WARN: Can't find a 'zlib/1.2.13' package binary '76f7d863f21b130b4e6527af3b1d430f7f8edbea' for the configuration:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.version=14
os=Macos
[options]
fPIC=True
shared=False

ERROR: Missing prebuilt package for 'zlib/1.2.13'
Check the available packages using 'conan list zlib/1.2.13:* -r=remote'
or try to build locally from sources using the '--build=zlib/1.2.13' argument

More Info at 'https://docs.conan.io/en/2/knowledge/faq.html#error-missing-prebuilt-package'
```

Note that the resolved options for zlib has `shared=False` even though the profile selected it to be `True`.

This is a regression from Conan 1.x, where settings for tool requires in profiles are respected.

**Comment by memsharded** [comment]
Hi @sfackler 

Thanks for your report.
I think there is some confusion regarding the profiles:

- The ``options`` defined in the "host" profile, are applied to recipes/packages in the "host" context
- The ``options`` defined in the "build" profile, are applied to recipes/packages in the "build" context

This way, allows to define different options for zlib, for example, in the build and host contexts.

You are trying to define it in the "host" profile. Please move it to the build profile (or ``-o:b zlib*:shared=True``) and let us know. Thanks!

**Comment by sfackler** [comment]
Sorry, my use of zlib there may have made things confusing. In reality, I have a Conan package that containing cross compilers, and an option that selects what the cross toolchain should target. The idea is that I can have a self contained profile looking something like e.g.

```
[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release

[tool_requires]
cross-toolchain/1.2.3

[options]
cross-toolchain*:target=x86_64-linux-gnu
```

And I'd then use that as the host profile in a `conan install`. I think this is the right setup, where I want this cross-toolchain package (which exports CC,CXX, etc variables appropriately) to be used when building any packages for the host architecture. In Conan 2, the build fails trying to install cross-toolchain as the target option isn't ending up being set.

**Comment by memsharded** [comment]
Yes, that is what I meant.

```
[options]
cross-toolchain*:target=x86_64-linux-gnu
```
should go to the "build" profile, not to the "host" profile. The "host" profile applies to recipes in "host" context.

The example with the zlib is important, because it is something that really happens often. There are recipes like openssl, zlib, protobuf, and others that can be well part of the host and build context. The only way to correctly define the right options for each one is that the options for each one are defined in different profiles, otherwise there is no way to distinguish if you want ``protobuf`` or ``zlib`` as a "shared" library in the "host" context, but as "static" library in the build context. Or if you want to build "Debug" for the "host" context, but your build tools and their dependencies should be naturally "Release", the ``build_type=Debug`` goes to the "host" profile and the ``build_type=Release`` goes to the "build" profile.

**Comment by memsharded** [comment]
By the way, I am not sure if you really need to pass the target as an option. The ``settings_target`` will exist for the toolchain package too, and if ``x86_64`` and ``linux`` is what is needed, it sounds this could be automatic.

**Comment by sfackler** [comment]
Ah I see. Would a `[tool_options]` section make sense to avoid having to split the package requirement and option? Otherwise I can adjust how I'm setting up the profiles.

EDIT: Wouldn't you need something like `[tool_options]` to be able to set options for tool requires in the build profile for example?

**Comment by memsharded** [comment]
> Ah I see. Would a [tool_options] section make sense to avoid having to split the package requirement and option? Otherwise I can adjust how I'm setting up the profiles.

The thing is that the internal propagation of profiles is complicated, and it is necessary to have clear boundaries to maintain sanity. Something like that could make things quite complicated. And following some good practices, if possible we prefer to have just 1 way to do 1 thing, having 2 different mechanisms for the same purpose ends being a maintenance and support nightmare, confusing for users... not worth it. But as always if this keep being an issue, we can re-evaluate this, but at the moment it is too early.

> EDIT: Wouldn't you need something like [tool_options] to be able to set options for tool requires in the build profile for example?

Not really necessary, ``tool_requires`` for packages in the "build" context are already in the build context, so the likelihood of being an issue is way lower. The real problem is that host and build contexts very often have different options, and having the correct ones in each one is critical, errors are very bad. 
Also, having ``tool_requires`` for packages that are already ``tool_requires`` is less common. And they tend to be quite simple, like ``cmake`` or something like that, not something that needs options often. 
Furthermore, the recommendation would be to define these options in the recipes themselves, like ``self.tool_requires(..., options=xxxx)``, not in the profile. Profile ``[tool_requires]`` should probably be for some very general things, that typically apply to all packages, like cmake or a toolchain.

I would still investigate the possibility of dropping the ``option`` to define the target, if the ``settings_target`` can be leveraged for that. Recall that in 2.0, it is possible to make ``settings_target`` part of the ``package_id`` too.

**Comment by sfackler** [comment]
Got it, thanks!
