### ISSUE TITLE
revision_mode=explicit

### ISSUE THREAD

**Issue by tsondergaard** [conan-io/conan#13238]
The new Conan 2.0 support for recipe revisions is a great improvement. Comparing Conan to other package management systems like e.g rpm it has always bothered me that a package version is entirely based on the upstream software version, which meant that package consumers had very little insight into which particular package revision they get, and we cannot pretend that doesn’t matter as recipes can contain patches. In Conan Center Index they often do. But it is my impression that hash and scm-sha based revision identities are still quite weak as it is something we care about as humans. They lack the natural ordering of traditional version and revision numbers.

Wouldn’t it be better to allow explicit revision numbers with revision_mode=explicit and then have an extra field revision that developers set in the conanfile.py? Exactly as rpm does it with the Revision attribute in .soec files.

https://rpm-software-management.github.io/rpm/manual/spec.html

**Comment by memsharded** [comment]
Hi @tsondergaard 

This is a very interesting issue.
We have indeed thought a lot about it, we have talked to dozens of users, and discuss about it.
These is a summary of our conclusions:
- Providing a centralized single source of truth to provide some incremental, ordered reference, is not possible. The nature of modern package management, devops, decentralized teams, is that you have developers, in different locations, using different servers, but doing pull requests with changes to the same package, that CI pipelines have to test and integrate sometimes quite asynchronously. 
- Relying on humans to provide a correct, robust, incremental reference to revisions is even more unlikely, because some of the above (distributed teams), but also human errors. Conflicts will eventually happen.

So then:
- If humans want to provide "manually" their inputs, it is always possible to add more digits to the version. This is why we have implemented an extended semver model in 2.0, that is able to process versions and version ranges for any number of digits, not only the 3 that semver specifies. Also for pre-releases and builds, they can also have any numbers. We also allow letters, with alphabetical order, instead of digits, for more flexibility. 
- For revisions to be robust, they need to be fully automatic and fully decentralized, so that leaves us with content based hashes, that guarantee not only uniqueness, but also allows being robust against time issues (no matter if the windows build agent got a different time, and it is taking 2 hours more to create the package, the recipe revision it exported locally will be robust)

These are the reasons why we haven't considered the possibility of an ``explicit`` revision mode.

**Comment by tsondergaard** [comment]
@memsharded, Thanks for the prompt and detailed reply. I looked at the docs for [revisions](https://docs.conan.io/2/tutorial/consuming_packages/intro_to_versioning.html?highlight=recipe%20revisions#revisions):

> Revisions always resolve to the latest (chronological order of creation or upload to the server) revision.

Using upload/creation time for chronological ordering is scary to me. It feels “uncertain” - I must take exceedingly good care of what is in my conan cache.

It also looks like I cannot require a package revision of <foo> or newer as the ordering of revisions is not meaningful.

**Comment by memsharded** [comment]
> Using upload/creation time for chronological ordering is scary to me. It feels “uncertain” - I must take exceedingly good care of what is in my conan cache.

Yes, we know it doesn't sound perfect, but the truth is that this mode has been operating several years now, majority of our users, including many in very large setups have been using revisions, and it seems to be working reasonably well.

The rationale is that once we cannot trust a single centralized source of truth for ordering, every order is local. The order of the revisions in your cache is local to your cache, and the order of revisions in the server is local to that repository. This has some advantages that makes it a little bit scary:
- Everything can be checked locally: listing revisions of a remote or a cache, and it is very evident which revision is older and newer. No complicated logic.
- We have battle tested this a bit for user expectations, for example, when a new revision is installed from a remote it should become the latest in the cache, so it becomes the one used (unless it was already in the cache from some time ago). It doesn't matter than in the server it might be in a different order, installing it in the cache and not being used automatically because the relative time of the server revision is older than the existing revisions in the cache is super confusing. The "last one being created/transferred becomes the latest" seems to be relatively intuitive for users.

> It also looks like I cannot require a package revision of or newer as the ordering of revisions is not meaningful.

Not sure what you mean, but only newer revisions can be required. The ``--update`` will do a relatively ordering of different remotes, but "bring me the latest revision" is basically what ``--update`` do.

**Comment by tsondergaard** [comment]
> > It also looks like I cannot require a package revision of or newer as the ordering of revisions is not meaningful.
> 
> Not sure what you mean, but only newer revisions can be required. The `--update` will do a relatively ordering of different remotes, but "bring me the latest revision" is basically what `--update` do.

I just meant that I cannot express that I want version `>= 5.15.8-7`, where the 7 after the dash is the revision. I might want that because I know there is something in the revision 7 recipe that fixes an issue I have, but I also want to allow newer versions+revisions. If revisions are hashes they only have a local ordering and therefore `>= 5.15.8-<revision-hash>` (I know the syntax in conan is different) doesn't make sense.

Thank you again for patiently explaining the position of the Conan project on this matter. I still feel uneasy about the decision, but some times you have to use something for a while and get use to it.

**Comment by memsharded** [comment]
> I just meant that I cannot express that I want version >= 5.15.8-7, where the 7 after the dash is the revision. I might want that because I know there is something in the revision 7 recipe that fixes an issue I have, but I also want to allow newer versions+revisions. If revisions are hashes they only have a local ordering and therefore >= 5.15.8-<revision-hash> (I know the syntax in conan is different) doesn't make sense.

Yes, definitely we thought a lot about this trade-off, as the "revisions" project was a many months effort, that also involved doing a client-server API v2, involving different teams with previous experience in other package managers protocols. 

As you said, lets see how it goes, if at some point it is not enough for you, I think it is quite feasible and not that complex to develop your own versioning approach with your automatic revisions, using version ranges, the multiple digits versions described above, and automation via ``set_version()``.
