### ISSUE TITLE
conan 2.0: can we still use the imports method or an equivalent when consuming packages?

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#13239]
### What is your question?

Hello!

I was wondering if there is an equivalent for the conanfile.py imports method (discussed here for example https://github.com/conan-io/conan/issues/1267) in conan 2.0, for copying files (e.g. text configuration files, shaders, etc) from a package to a consuming application. I have an imports method in the conanfile.py of one of my applications but it does not seem to get launched any more.

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by samuel-emrys** [comment]
The replacement feature for the `imports()` method is [deployers](https://docs.conan.io/2/reference/extensions/deployers.html)

**Comment by dimi309** [comment]
I was searching and searching... 😭 Thanks a lot!!! 👍 👍 👍

**Comment by samuel-emrys** [comment]
Also see [this section of the 2.0 migration guide](https://docs.conan.io/1/migrating_to_2.0/recipes.html#removed-imports-method) - you can use the `generate()` function:

```python
from conan.tools.files import copy

def generate(self):
    for dep in self.dependencies.values():
        copy(self, "*.dylib", dep.cpp_info.libdirs[0], self.build_folder)
        copy(self, "*.dll", dep.cpp_info.libdirs[0], self.build_folder)
```

**Comment by dimi309** [comment]
This one is even more straightforward and I was actually using it for packaging. What stopped me from using it for deployments to applications is that I didn't know about `self.build_folder`. Thanks again!!

**Comment by memsharded** [comment]
Thanks @samuel-emrys!

**Comment by nextsilicon-itay-bookstein** [comment]
It's not obvious to me from [the documentation](https://docs.conan.io/2/reference/commands/install.html) whether there's a built-in deployer for licenses or whether I need to write one myself - what was the verdict here, did you write a custom deployer?

**Comment by samuel-emrys** [comment]
> It's not obvious to me from [the documentation](https://docs.conan.io/2/reference/commands/install.html) whether there's a built-in deployer for licenses or whether I need to write one myself - what was the verdict here, did you write a custom deployer?

https://github.com/conan-io/conan-extensions/blob/main/extensions%2Fdeployers%2FREADME.md

**Comment by nextsilicon-itay-bookstein** [comment]
Awesome, thanks!

**Comment by johan-boule** [comment]
There seems to be a big quiproquo/misunderstanding about the intended goals of these features, as they are designed, and the expectations of the users. It was the same in Conan 1, we had to abuse the `imports` command to actually *deploy* a self contained application.
Conan seems to have a "blind spot" in its feature-set and misses the equivalent of traditional `make install`.
I read the documentation, and I'm still clueless about how we can deploy runtime dependencies along with our application.

**Comment by memsharded** [comment]
Hi @johan-boule 

I am not sure what you mean, Conan 2 got the new ``deployers`` and the ``deploy()`` method, which easily allow to deploy apps, for example using the built-in runtime deployer, for a example to deploy an existing app like:
```
$ conan new cmake_exe -d name=myapp -d version=0.1
$ conan create . 
````
It is just 
```
$ conan install --requires=myapp/0.1 --deployer=runtime_deploy
```
(the ``runtime_deploy`` is a bit new and experimental, it might need still a bit of iteration, but the intention is there).
And deployers are now also user-defined (and can be shared with ``conan config install`` too.

So maybe you want to create a new issue with more accurate details of the flow you want to implement, and your attempts using ``deployers`` or ``deploy()`` method?

**Comment by johan-boule** [comment]
> ```
> $ conan install --requires=myapp/0.1 --deployer=runtime_deploy
> ```
> 
> (the `runtime_deploy` is a bit new and experimental, it might need still a bit of iteration, but the intention is there). And deployers are now also user-defined (and can be shared with `conan config install` too.

Thanks a lot for mentioning this new builtin deployer. When we did the preliminary work to switch to Conan 2 a few months ago, we were at version 2.4.0 and this one seem to have been added in 2.5.0, so that would explain why we didn't see it :-)
 
> So maybe you want to create a new issue with more accurate details of the flow you want to implement, and your attempts using `deployers` or `deploy()` method?

From the description of the runtime_deploy, it says "into a flat directory structure", so there's a chance it matches my expectation of what a `make install` does, i.e. merging all things together into a standard unix tree layout. I'll check it out. Thanks again.

**Comment by samuel-emrys** [comment]
@johan-boule if that doesn't satisfy your use case, you can either write a custom deployer (if the logic applies to many packages and you want reusability) or implement the `deploy()` method (if the logic only applies to the software being packaged/deployed), and these allow you to do almost literally anything you would care to from a deployment perspective.

**Comment by memsharded** [comment]
> Thanks a lot for mentioning this new builtin deployer. When we did the preliminary work to switch to Conan 2 a few months ago, we were at version 2.4.0 and this one seem to have been added in 2.5.0, so that would explain why we didn't see it :-)

yes, that makes sense :)

We keep working very hard to keep improving Conan. Conan 2.0 was not only the major version, but also a new architecture that allowed us to develop a lot of new features that have been requested for a long time, so definitely worth checking from time to time the release notes and our blog (https://blog.conan.io/) for new features.


> From the description of the runtime_deploy, it says "into a flat directory structure", so there's a chance it matches my expectation of what a make install does, i.e. merging all things together into a standard unix tree layout. I'll check it out.

Feel free to create new tickets if you see any issue, there is already this pending ticket https://github.com/conan-io/conan/issues/16938, you can comment there if you find related problems.

**Comment by Talkless** [comment]
> I am not sure what you mean, Conan 2 got the new deployers and the deploy() method, which easily allow to deploy apps

"easily" was to just have `conanfile.txt` with section:

```
[imports]
bin, libcrypto*.dll -> .
bin, libssl*.dll -> .
lib, libcrypto.so* -> .
lib, libssl.so* -> .
```

So with Conan 2.0, one either has convert `conanfile.txt` into `conanfile.py` and utilize `generate()` with `copy()` calls, or implement and invoke (pass one more argument) custom deployers?

I would not call that "easily", unless default deployer works ok for most of the cases.

**Comment by memsharded** [comment]
> "easily" was to just have conanfile.txt with section:

Except we did a UX research experiment. 
Very few devs could successfully write ``[imports]`` section at the first try correctly without reading the docs. Even most of the Conan maintainers failed to do this.
But a majority of devs could successfully write the equivalent ``generate()`` + ``copy()`` under the same conditions.

There are some reasons that would explain this. For example, that Python is the second language for most C/C++ developers, with a very large % of users knowing how to write Python, and using it frequently. In that regard, it feels more natural to them to write Python than learning a custom invented DSL syntax for ``[imports]`` in a text file.
Also, leveraging an existing ``copy()`` method, that many users already know, because it is very common in the ``package()`` method helped in this regard.

As almost everything in SW, it is a matter of opinions and there will be people that would prefer one way or the other. But the experience of supporting thousands of users over the years, led to conclude that the overall experience (with its trade-offs, of course) is generally better with a conanfile.py, this is why this section exists now in the Conan 2 explicitly: https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html

It is important to be aware that this approach also unleash a lot of flexibility needed by many users. The ``[imports]`` system had several limitations that made it useless for a bunch of users. So it was necessary to have a solution for their cases anyway, and the combination of ``generate()`` with ``copy()`` makes it also a way more complete solution.

These decisions are not taken lightly. We do a lot of effort in understanding all different users needs and try to provide the vast majority of them with solutions. We spent huge amounts of times talking and receiving feedback from tons of users, thinking about possible design and UX alternatives, understanding the trade-offs and iterating on the solutions.

**Comment by Talkless** [comment]
> It is important to be aware that this approach also unleash a lot of flexibility needed by many users. 

Sure, I'm all for extra advanced features for custom needs, Conan's customization abilities does help a lot, including *sometimes* writing custom `conanfile.py`, but `[imports]` could have been left as an option, or maybe making "imports" ready-to-use deployer for keeping old behaviour.

**Comment by glennaycock** [comment]
We are still struggling with the dissociation of cmake shared imported targets from their corresponding files. Doing a bulk copy of all a package's files isn't our ideal solution for deployment. For example, both Boost and Qt have a lot of components. Is there any way to limit which component files are deployed with Deployers? Our preferred method to stage deployment of our applications is "cmake install," for both compiled products and third-party dependencies, rather than have to write a bunch of new, platform-specific deployment logic.

**Comment by johan-boule** [comment]
> We are still struggling with the dissociation of cmake shared imported targets from their corresponding files. Doing a bulk copy of all a package's files isn't our ideal solution for deployment. For example, both Boost and Qt have a lot of components. Is there any way to limit which component files are deployed with Deployers?

That's a good question. I think the root of the problem is that giant source repositories are usually treated as one package, to limit the amount of maintenance work. If the package options permits it, it's possible to disable the building of the components you don't need, but that leads to a combinatory explosion of the number of binary packages. The ideal design would be to treat components as individual downloadable sub-packages (like Linux distros do).

**Comment by memsharded** [comment]
@glennaycock if you want the CMake way of deploying shared libraries, the CMake ``install()`` ``RUNTIME_DEPENDENCY_SET`` https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#conan-runtime-lib-dirs might be useful, that will collect exclusively the used shared libs by a specific executables.

The other comments, is nothing that Conan can do much, users can split their multi-lib packages in several single-lib packages, but that is not something that Conan will do automatically.
