### ISSUE TITLE
[bug] Unable to set options on build requirements using `configure`

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#13236]
### Environment details

* Operating System+version: Arch Linux 
* Compiler+version: clang 15
* Conan version: 2.0.0
* Python version: 3.11.1

### Steps to reproduce

In 1.x, I've been using the following method of setting options on my build requirements:

```python
def build_requirements(self):
    self.tool_requires("mytool/version@user/channel")
    
def configure(self):
    self.options["mytool"].optA = "value"
```

However, this no longer appears to work in conan 2.0. I just wanted confirmation - is this intended behaviour? If so, what are the alternatives? I thought I'd seen an issue that addressed this in detail but I can't seem to find it at the moment, and none of this seems to be documented yet.

I've managed to work around this at the moment with `self.tool_requires("mytool/version@user/channel", options={"optA": "value})`, but this doesn't seem robust to setting options based on logic.

For completeness, I've raised https://github.com/conan-io/docs/issues/3026 to document the part of the solution that i have found.

**Comment by memsharded** [comment]
Hi @samuel-emrys 

yes, this is intended behavior. The problem becomes more evident if we do:
```python
def requirements(self):
    self.requires("mytool/version@user/channel")

def build_requirements(self):
    self.tool_requires("mytool/version@user/channel")
    
def configure(self):
    self.options["mytool"].optA = "value"
```
Which is a common case for packages like ``protobuf``. This would be ok if we wanted the same values for both host and build, but this is often not the case. The problem is more subtle but even more problematic when instead of a direct dependency it is a transitive dependency, which is unlikely to be desired, because that could mean to propagate options to tool-requires of dependencies, which shouldn't happen.

So we left the ``configure()`` ``self.options`` mechanism for the "host" context, and if options of the ``tool_requires`` are necessary, it can be done explicitly as an argument, making it clear that it is an option for it.

**Comment by samuel-emrys** [comment]
Thanks for the clarification @memsharded. The additional use case helps put this into context. It makes sense, but I can see that it may be confusing that you configure `requires` and `tool_requires` differently. Hopefully this makes it into the documentation soon.
