### ISSUE TITLE
[question] conan v2 necessary packages

### ISSUE THREAD

**Issue by FaerHack** [conan-io/conan#13235]
### What is your question?

Hi,
What are the reasons for a recipe requirement to be marked as skipped in "Computing necessary packages" step?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @FaerHack 

If the package is a dependency but ``headers=False``, ``libs=False``, ``run=False``, then basically there is nothing in the package that it is needed by this consumer, so the binary can be skipped. Maybe this link could be of some help: https://youtu.be/kKGglzm5ous (linked in https://docs.conan.io/2/knowledge/videos.html)

Examples:
mypkg -(tool_requires)->cmake/3.15 -(requires)-> zlib/1.2.13

If cmake links statically zlib, then when mypkg requires as a tool cmake, it might get that it transitively depend on zlib, but with  ``headers=False``, ``libs=False``, ``run=False``, so it doesn't need at all the zlib binary in order to build. If cmake links dyamically zlib, then ``mypkg`` will get a ``run=True`` to ``zlib`` and it will be necessary and not skipped.

**Comment by FaerHack** [comment]
I also noticed that if a package is created with `shared=True`, then all of its dependencies compiled with `shared=False` will be marked as skipped when you try to consume that package. Is this intended behavior?

**Comment by memsharded** [comment]
> I also noticed that if a package is created with shared=True, then all of its dependencies compiled with shared=False will be marked as skipped when you try to consume that package. Is this intended behavior?

Yes, exactly. When a shared library links a static one, it gets a copy of the static library binary inside its own binary. So it is not necessary for an executable linking the shared library to link with the static one at all (it is even wrong to link it!). 

A different case happens if the headers of the static library are used in the public headers of the shared library. In this case, the shared library should do ``self.requires("staticlib/1.0", transitive_headers=True)`` to specify it.
