### ISSUE TITLE
[question] Conan package requires pip packages

### ISSUE THREAD

**Issue by xakod** [conan-io/conan#13244]
### What is your question?

Does conan provide any way to install pip packages? For example, I need some pip packages only for test package. So I don't want to install it globally. I know, I can use ```pip install pkg``` from conanfile but maybe conan provide something by default. Thanx

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Jihadist 

Thanks for your question.
Installing ``pip`` packages is not a simple thing, because you need a Python installation to install them. If that is the installation that is running Conan, ``pip`` easily cause version conflicts and other problems. If Conan is running with the self-contained executable, no ``pip`` packages can be installed there, because it is a bundled executable without a ``site-packages``.

I think this is a duplicate question, and it is being managed already in this proposal for 2.X roadmap in https://github.com/conan-io/conan/pull/11601. It is based on the idea of creating virtualenvs on the fly to be able to install ``pip`` packages there. I am closing this issue, please track the efforts in that issue, progress will be reported there when the 2.X roadmap issue gets prioritized. Thanks!
