### ISSUE TITLE
[feature] `conan config set` for Conan 2.0

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#13254]
### What is your suggestion?

Hi, 

I think something like `conan config set` is still very useful for Conan 2.0. Imagine a CI builds wants to run in isolated mode and wants to use the project's conan configuration. However, development builds shall share a single package folder on the disk which can be realized via `core.cache:storage_path`. From my point of view a command like `conan config set core.cache:storage_path xyz` would be very useful here - or is there any other official approach that Conan is in favor of (if so, it would be great if you could mention that in the documentation)?

Best regards,
gpxricky

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by gpxricky** [comment]
It is not mentioned in the documentation, but if `conan config install` does not overwite an existing `global.conf`, but merges them, then a solution could be to run `conan config install my_global.conf` on top of the configured cache.

**Comment by memsharded** [comment]
Hi @gpxricky 

We decided to not implement commands in 2.0 that do text files basic editing.
There are some reasons for it, but one of the major blockers is that now the ``global.conf`` file is always a jinja template that is rendered. As such, it is not possible to do round-trip load+add+save with that file without destroying the file functionality. Either you evaluate the jinja template and lose the template (broken), or trying to do edition over a raw template would require a full AST of jinja, which would be extremely problematic and very fragile in the best case.

The approach would be to use such feature: https://docs.conan.io/2/reference/config_files/global_conf.html#configuration-file-template

If you have per-machine configuration for the storage path, for example, something like the following would make sense:
- Use a ``jinja`` ``global.conf`` with something in the line ``storage_path = os.getenv("MYSTORAGE_PATH")``
- Define the env-vars in the CI, instead of executing ``conan config set`` commands
- This way the process is self-contained and documented in files that developers can see, and that you can even make fail with helpful messages if something is not defined correctly.

**Comment by gpxricky** [comment]
Hi @memsharded,

many thanks for sharing the approach. That should work in most cases, although it is much more complex than before.

By the way, I've created a `global.conf` with the following content:

```
core.cache:storage_path=path_to\my_packages\
core.cache:storage_path=path_to\my_packages2\
```

It seems, Conan V2.0.0 is using the second entry, so last one wins. Can you confirm that this is a hidden, but well-defined behavior? Would make sense to me. If so, this would also be an option to solve the issue, although in a different and less elegant way. And maybe the docs should mention that last entry wins for duplicated items.

**Comment by memsharded** [comment]
> It seems, Conan V2.0.0 is using the second entry, so last one wins. Can you confirm that this is a hidden, but well-defined behavior?

It is an "implementation defined behavior", because the file is parsed line by line, and the result is basically a ``dict`` of keys-values, so last line is definitely the one that will have priority.
I am not sure if this is something to consider "well-defined" behavior, because it doesn't look great that a file contain 2 different values for the same conf. It will definitely raise questions, it is not that clear that it shouldn't be an error, and it is super likely that some users will even ask for this to be an error precisely to avoid human errors that will eventually happen.

I'd definitely aim to have a single ``core.cache:storage_path`` definition, if you don't want to leverage the jinja template and env-vars, you can define some ``core.cache:storage_path=%MYPATH%`` placeholder and do a text replace of the placeholder on the command line.

**Comment by AbrilRBS** [comment]
Closing, we feel like Conan 2 not providing direct text replacement CLI options is the safest approach now that profiles can leverage Jinja2
