### ISSUE TITLE
[question] Is it safe to use conan install --format json for getting dependencies description?

### ISSUE THREAD

**Issue by lo1ol** [conan-io/conan#13261]
### What is your question?

Hi!

I want to use conan 2.0 with my qbs projects. But conan 2.0 doesn't have json  and QbsDeps generators  anymore. I don't want to wait for adding support of conan 2.0 to qbs, so I'm thinking about using custom Qbs.Probe.

This Probe uses output of `conan install --format json` for getting package_folder, settings and options of dependencies (cpp options is set up by myself, not by conan).

Everything is work, but I noticed that output of `install --format=json` is marked as unstable at the documentation. May you suggest more stable approach for getting this properties?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lo1ol 

I think it would be more stable using a custom generator that traverse the ``self.dependencies`` information to gather it and generate the files. 

But this is also a chicken and egg problem, it is "experimental" because we need more feedback to confirm the data is correct and useful in its form, if we don't get people to use it and report, then it is a bit difficult to consider it stable. The idea of the graph format json is that it should be stabilized in a few months, not years.

**Comment by lo1ol** [comment]
Thank you!
