### ISSUE TITLE
[question] non-visible require recipes are visible

### ISSUE THREAD

**Issue by lo1ol** [conan-io/conan#13276]
### What is your question?

Hi!

I notices that recipe of `test_requires` are visible for consumers of this package. Download of binary packages for test_requires is skipped, but recipe is still visible. Is it normal behavior?   

Example:
```python
from conan import ConanFile

class RtcryptConanfile(ConanFile):
    name = "pkg_a"
    version = "0.0.1"
    settings = "os", "compiler", "arch", "build_type", "libc"
```

```python
from conan import ConanFile

class RtcryptConanfile(ConanFile):
    name = "pkg_b"
    version = "0.0.1"
    settings = "os", "compiler", "arch", "build_type", "libc"

    def build_requirements(self):
        self.test_requires("pkgA/0.0.1")
```

```python
from conan import ConanFile

class RtcryptConanfile(ConanFile):
    name = "pkg_c"
    version = "0.0.1"
    settings = "os", "compiler", "arch", "build_type", "libc"

    def requirements(self):
        self.requires("pkgB/0.0.1")
```

```console
$ conan export-pkg ./pkgA.py
$ conan export-pkg ./pkgB.py
$ conan install ./pkgC.py


======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

======== Computing dependency graph ========
Graph root
    pkgC.py (pkg_c/0.0.1): /home/lo1ol/Documents/work/test-conan/pkgC.py
Requirements
    pkg_b/0.0.1#acaebda87a6bced99c85d5fe6cc86ff0 - Cache
Test requirements
    pkg_a/0.0.1#ab03c2ba10c50f74b6e46de0e5dd268d - Cache

======== Computing necessary packages ========
Requirements
    pkg_b/0.0.1#acaebda87a6bced99c85d5fe6cc86ff0:a757fbef93fba37567071311c0c28420eecccfe6#ddddfc651bb6dc1c428ac3721dac6e59 - Cache
Test requirements
    pkg_a/0.0.1#ab03c2ba10c50f74b6e46de0e5dd268d:f25c077f6d57a1b97b973e5b5d940be33a5cdc41#d70d39ed2af989acf0378f4c8327734d - Skip

======== Installing packages ========
pkg_b/0.0.1: Already installed!

======== Finalizing install (deploy, generators) ========
pkgC.py (pkg_c/0.0.1): Generating aggregated env files
pkgC.py (pkg_c/0.0.1): Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished succesfully
```

I think that non-visible requires should be non-visible at all. Isn't it?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lo1ol 

Thanks for your question.
The ``visible=True`` trait is about the propagation of build information, like includedirs, and also the possibility of conflicting if different versions of the same package are used. But it doesn't mean that the recipe is fully skipped.

The dependency graph in Conan 2.0 will always be complete, containing all recipes for all tool requires and test_requires. This is very important, Conan 1.X didn't expand the graph at all for tool-requires and test-requires if it was not necessary to build, but that created several important structural problems, like tool-requires not being able to affect the ``package_id`` of consumers, and multitude of problems with dependency graph reproducibility and lockfiles and distributed builds.

So it was decided that Conan 2.0 will always compute the full dependency graph, also because the "tool-requires" and "test-requires" are not that numerous, just a very few (2-7 typical cases) recipes, which are very fast to download if not already cached (because the heavy part which is the binary is skipped), so the possible impact on performance is negligible and the advantages are very worth it.

**Comment by lo1ol** [comment]
Got it. Thanks!
