### ISSUE TITLE
[question] Does package_type header-library automatically set the package_id?

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#13289]
### What is your question?

When using `package_type = "header-library"` for package, does it automatically set the package_id appropriately, i.e. `self.info.clear()`?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jwillikers 

No, it does not automatically do that. 
The reason is that there are out there header-only libraries, but with generated headers that might be os-specific. The ``package_type`` defines how the information is propagated to the consumers, but not the current ``package_id`` (it an still affect the ``package_id`` of the consumers)

**Comment by jwillikers** [comment]
@memsharded Perfect, thanks!

**Comment by AbrilRBS** [comment]
Conan 2 addes the new [`implements`](https://docs.conan.io/2/reference/conanfile/attributes.html?highlight=implements#implements) class attribute that can help with this and future automatic management of Conan. Closing as solved
