### ISSUE TITLE
[bug] conan 2.0 editable package conf information

### ISSUE THREAD

**Issue by ShuangLiu1992** [conan-io/conan#13309]
### Environment details

in editable packges, their tool_requires dependencies doesn't seem to set up conf, causing generators to fail when another package that depends on these editable packges calls install.

for example tools.android:ndk_path becomes None when "installing" an editable package that depends on android_ndk

**Comment by memsharded** [comment]
Hi @ShuangLiu1992 

If you want to put a package in editable that has ``conf_info`` that depends on ``package_folder``, you need to define the correct ``layout()``, because when in "editable" mode, there is simply no ``package_folder``, because there is no package. Using the ``self.cpp.build`` and ``self.cpp.source`` is the way to define it, something like this:

```python
 class Dep(ConanFile):
            def layout(self):
                self.folders.source = "mysource"
                self.folders.build = "mybuild"
                self.layouts.source.conf_info.append_path("user.myconf", "mylocalsrc")
                self.layouts.build.conf_info.append_path("user.myconf", "mylocalbuild")
                self.layouts.build.conf_info.update_path("user.mydictconf", {"a": "mypatha", "b": "mypathb"})
                self.layouts.build.conf_info.define_path("user.mydictconf2", {"c": "mypathc"})
```

I am submitting this test in https://github.com/conan-io/conan/pull/13310 that will close this ticket as resolved, and I am working in adding some more info to the docs as well

**Comment by memsharded** [comment]
Docs PR in https://github.com/conan-io/docs/pull/3053
