### ISSUE TITLE
[question] How to handle non-standard library names (ie not lib[name].a) in 2.0

### ISSUE THREAD

**Issue by daltonv** [conan-io/conan#13366]
I am packaging a sdk I did not make and it has non standard library names, so I cannot set 
`self.cpp_info.libs` as the consuming cmake project cannot find the libs.

I tried to change the `package_info()` function in the sdk package to have:
```python
self.cpp_info.exelinkflags = ["-static", "-l:drivers_mspm0g150x_g350x_nortos.a", "-l:driverlib.a"]
```
However that seems too clever. As in the consuming project the object files are being linked on the link line AFTER the 
static library my package is shipping. This causes linker errors.

It works if in the packaging stage I rename the libs to the "standard" naming convention and add them into `self.cpp_info.libs`, but it seems like there should be a better way of adding these kind of libraries. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @daltonv 

Thanks for your question.

I think this is not Conan 2.0 specific, but the same issue would happen in 1.X too, or is it only 2.0 for you?

Conan had some provisions to accept the name in ``self.cpp_info.libs = ["myname.a"]``, but it is true that this might still be problematic, depending on the compiler (and mostly the linker). Did you try this approach?

Otherwise, to be honest, if it is possible to rename the library to something more standard that would work automatically and better, this seems a legit use case, I think distros system package managers would also rename libs if they don't comply with their standard. Do you see any problem doing this rename?

**Comment by daltonv** [comment]
Hi @memsharded 

I'm new to Conan and have only used 2.0. Just wanted to be clear which version I'm on :).

Yes I did try the approach of setting `self.cpp_info.libs = ["myname.a"]`. It broke down for me cmake. I think it was the cmake test to ensure the compiler is working that broke. 

I'm totally fine with renaming the library. Just wanted to make sure there wasn't another way to approach this.

Thanks for the help!
