### ISSUE TITLE
[suggestion] Suggestion for Discussion Form

### ISSUE THREAD

**Issue by mert-kurttutan** [conan-io/conan#13360]
### What is your suggestion?

Hi,
I just want to make the suggestion for opening up discussion section as I see that there are a lot of question type of issues.
I think separating questions from bugs/issues would give more precise idea of what issues section stands for, (Unless you have some completely different view in your mind).

When I first look at the number of issues, it was around 2.1k, which seems high (e.g. in comparison to vcpkg), but then discovered that there are a lot of issues with tag question, around 0.9k.

I think moving issues with tag question to discussion would :
- give more idea precise about the current state of bugs/problems
- clear separation of concerns

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @mert-kurttutan, thanks for taking the time to propose this change. Could you give us some examples as to what kind of issues you'd think would deserve to be their own discussions?

It's true that we have many tagged questions that have remained open just because we wait for the author to do so in case they have further input, but that's something thats we're changing and are in the process of closing those that are no longer relevant or have become too stale, which might help alleviate some of the pain points you mention. We also discussed internally and will definitely use the discussions if we need to gather feedback from users, but we fear that opening it for simple questions would just duplicate the places we need to keep an eye for to support our users, instead of being used as a discussion forum :)

**Comment by mert-kurttutan** [comment]
Hi,
In my opinion, any kind of question without any bug, problem should go to the discussion section. 

I think even simple questions being inside discussion would just provide better separation of concerns, not a duplicate of placesm

I guess it makes sense to keep questions in the issues if you want to really prioritize them, or integrate them with workflow in a way that is not available via discussion section.

**Comment by AbrilRBS** [comment]
Hi @mert-kurttutan
Ultimately we have decided against using discussions in a day to day basis, and will instead prefer to use the usual issues for both questions and bug reports.

If there is ever the need to have open discussions with the community we will then consider using them as we see they fit that specific use-case quite well :)

Thanks a lot for your suggestion, it is great to think about our processes from time to time to ensure we are comfortable in how we run things!
