### ISSUE TITLE
[question] Lockfile handling when running conan install (1.x)

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#13398]
### What is your question?

We want to use lockfiles and we have two questions in that regard:

- Is the parameter "-u" having an effect if the conan install command is used together with the -l (lockfile) parameter?
- If a lockfile is given (without the -u parameter in case it has an effect) I would assume that the installation time for the dependencies should go down as all dependency version/revisions etc. have been resolved already. Is this assumption correct?

Thank you

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Sorry this was not responded back then @MTomBosch 

> Is the parameter "-u" having an effect if the conan install command is used together with the -l (lockfile) parameter?

No, in theory no, because the lockfile forces a specific version and revision, there is no "update"

> If a lockfile is given (without the -u parameter in case it has an effect) I would assume that the installation time for the dependencies should go down as all dependency version/revisions etc. have been resolved already. Is this assumption correct?

If all necessary things are in the cache, it should be as fast as a normal ``install`` without lockfile and without ``--update``. The ``--lockfile`` doesn't guarantee itself that things are already in the Conan cache.

This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
