### ISSUE TITLE
[Windows] LINK : fatal error LNK1158: cannot run 'rc.exe'

### ISSUE THREAD

**Issue by p-groarke** [conan-io/conan#1340]
Had issues building custom Debug zlib on windows. CMake output it couldn't find the C/CXX compiler. A little digging revealed it had issues finding rc.exe.

LINK : fatal error LNK1158: cannot run 'rc.exe'

Copied my rc.exe to the VS binary dir to hack a fix. Win 10, MSVC 2015 & 2017 installed. Latest cmake.

**Comment by lasote** [comment]
Please specify the package reference that you are trying to build and your settings.
If it's related with a concrete package open the issue in the package recipe repository, maybe lasote/conan-zlib?

**Comment by memsharded** [comment]
Please read the comment: https://github.com/conan-io/conan/issues/1402#issuecomment-327949466

The missing ``rc.exe`` is the installation of VS2017 messing up with the Win SDK (even for VS2015). It is solved re-installing the SDK (both for VS2017 and VS2015).

So the issue is not related with conan, but VS + CMake, it can be closed
