### ISSUE TITLE
[feature] Allow relative paths in global.conf or mention its usage in docs

### ISSUE THREAD

**Issue by gpxricky** [conan-io/conan#13413]
### What is your suggestion?

Hi,

unfortunately I wasn't able to use relative paths in the `global.conf` file. Neither

```
core.net.http:cacert_path=cacert.pem
```

nor

```
core.net.http:cacert_path=/cacert.pem
```

nor 

```
core.net.http:cacert_path=~/cacert.pem
```

worked for me when running under Windows. Did I miss some information or is it not supported at present?

In case it is not supported, I highly recommend to add this functionality in order to support company wide configurations. If it is already supported and I just don't know how to use it, then I would highly recommend to provide some example in the documentation.

Many thanks and best regards,
gpxricky

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @gpxricky 

You are right, it is not easy to get access to the current ``global.conf`` location from the file, to represent relative paths.
The trick is that relative paths cannot be really managed, they have to be absolute, so they need to be made absolute directly in the template (because the reader of the ``conf`` has no idea about what is a path or not, or if it should be relative to what location. A conf might even come defined from the command line, so that means the only way is that absolute paths is what is transmitted.

I have done https://github.com/conan-io/conan/pull/13415 to contribute this feature to next 2.0.2. The idea is the same as ``profile`` jinja templates, there is a variable called ``conan_home_folder`` that you can use to compute the full path:

```jinja2
user.mycompany:myfile = {{os.path.join(conan_home_folder, "myfile")}}
```

**Comment by gpxricky** [comment]
Hi @memsharded

this solution would be fine for me. If I may provide some extension to this, I would propose to provide a `conan` variable for the Jinja2 templates that at present just has a property `home_folder`. That might be easier to extend in the future in case someone requests other information to be added.

Many thanks,
gpxricky
