### ISSUE TITLE
[question] max_schema_version not supported in conan 2?

### ISSUE THREAD

**Issue by edwardvandevorst-philips** [conan-io/conan#13425]
### What is your question?

In conan 1.5x I had `tools.cmake.cmaketoolchain.presets:max_schema_version=3`
in my profile. But in conan 2.0.1 it gives an error.  This setting was mainly in my profiles due to visual studio not accepting higher versions. How to deal with this in conan 2?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @edwardvandevorst-philips 

Thanks for your question

This wouldn't be a VS limitation, but a CMake version limitation. Updating CMake would solve the issue. I guess that you are relying on the CMake version bundled with VS?

This was done because the multiple schema variability was seriously affecting maintenance and development of the CMakePresets integration, specially when some of the latest features were added, that also had serious limitations with older schemas. Furthermore, some of the ongoing work in the cmake-conan repo integration might also rely on more modern CMake versions, so it seems that users that want to use modern CMake integrations would need to move to newer versions of CMake.

**Comment by mzukovec** [comment]
[Visual Studio 2022 version 17.4 preview 2 adds support for schema versions 4 and 5.](https://learn.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170#supported-cmake-and--cmakepresetsjson-versions)

**Comment by edwardvandevorst-philips** [comment]
Ok, clear. Thanks.
