### ISSUE TITLE
[question] CI workflow for lockfiles

### ISSUE THREAD

**Issue by praetorian20** [conan-io/conan#13438]
### What is your question?

Hi, I've recently started experimenting with conan 2.0, and wanted to get your thoughts on how to go about integrating lockfile generation into automated CI builds.

I have a private repo with a small subset of recipes from conan-center-index. My intent with this repo is to build a few packages that we use in various projects in my company and upload the binary packages to artifactory. Along with creating the binary, I also want to generate a lockfile from the CI build and commit it, either into the same repo or a dedicated repo for lockfiles. So consumers can then copy the lockfile to their projects and use `conan lock merge` to create a consolidated lockfile of all dependencies needed by their project.

I have two issues with this

1. Since timestamp is part of the package reference, every CI build leaves me with a modified lockfile even though everything about the 2 builds is functionally identical. Is there a way to avoid having the timestamp, or should I add code for ignoring timestamp only differences giving me the ability to ignore lockfile modifications where everything else remains the same?
2. There's no indication of the build configuration for a package by looking at a lockfile, which makes it difficult for consumers to pick one that matches the build configuration that they want. Is there a plan to add all the build configuration settings that go into creating a package revision hash into the lockfile?

Maybe the workflow I have in my head is not the right way to go about this, so please let me know if there's an alternate way I should be approaching this.

Finally, great job on conan 2.0. Everything feels a lot more intuitive and congruous, especially the new `conan *` commands.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @praetorian20 

Thanks for your question.

I am having a look to your first question with timestamps. They are necessary in the lockfiles, because revisions need ordering too, and they are sorted by timestamps, so they cannot be just dropped without breaking the functionality of lockfiles. I am having a look to see about the stability of those timestamps, but in any case, they are necessary.

> There's no indication of the build configuration for a package by looking at a lockfile, which makes it difficult for consumers to pick one that matches the build configuration that they want. Is there a plan to add all the build configuration settings that go into creating a package revision hash into the lockfile?

Regarding your second question, no, lockfiles in 2.0 will not contain configuration, they only will contain strictly the versions and revisions. This is much closer to what other package managers in other languages do, and it is more intuitive. The idea is that it is not necessary to know which lockfile creates which binary, because 1 lockfile is good to lock multiple configurations and binaries, even multiple products if they are version-aligned. Maintaining, storing, referencing and managing that lockfile will be much easier than the equivalent in 1.X. Furthermore, it is also not necessary to manage intermediate lockfiles from a partial graph, as the same lockfile can easily be applied to subgraphs, and subgraph lockfiles can also be applied to parent graphs.

In this way lockfiles become very orthogonal to the normal operation. Lets say that if you have an application ``myapp1``, and you are installing its dependencies it is just:

```bash
conan install .  -pr=androidv1  #without lockfile
conan install .  -pr=linux 
conan install . -pr=androidv1  --lockfile=myapp1.lock
conan install . -pr=linux  --lockfile=myapp1.lock
conan install . -pr=linux --lockfile=previous_app1.lock  # to debug something in the past with older deps
```

**Comment by memsharded** [comment]
I have been having an extra look to:

> So consumers can then copy the lockfile to their projects and use conan lock merge to create a consolidated lockfile of all dependencies needed by their project.

``conan lock merge`` might not be the best approach, if you are computing the lockfile for different binary configurations. The recommendation would be to do several consecutive ``conan lock create`` for the different configurations, in the same machine, that will create a consolidated lockfile, and without possibilities of divergences that could happen because not exact synchronization between the different agents. Feeding the lockfile as input and output of ``conan lock create`` will guarantee stability over the subset of common dependencies for all different configurations.

> Since timestamp is part of the package reference, every CI build leaves me with a modified lockfile even though everything about the 2 builds is functionally identical. Is there a way to avoid having the timestamp, or should I add code for ignoring timestamp only differences giving me the ability to ignore lockfile modifications where everything else remains the same?

Dropping the timestamp wouldn't be possible without breaking lockfiles, because the sorted order provided by that timestamp is totally necessary to resolve when more than 1 revision happens in the graph (which can happen). If the lockfile is expected not to change, then it is possible to only provide it as input ``--lockfile``, but not as output ``--lockfile-out``.

**Comment by praetorian20** [comment]
Thanks for the detailed explanations @memsharded, really appreciate it. I'm still confused about the need for the timestamp in the revisions though. Agreed that multiple revisions may appear in the graph but if everything but the timestamp portion matches, doesn't that necessarily mean that the two revisions identify binaries that are identical? By identical I mean they have the same source revision and build settings.

I'm going with your advice of not distributing intermediate lockfiles. So my mini conan-center-index project will only build and upload binaries for the configurations we want to support, it won't produce any lockfiles. Consumer projects can `conan install` and `conan lock create` to create and then commit their own lockfiles.

The only issue I still don't have a solution for is for the following problem. We have added a conanfile.py to [DPDK](https://git.dpdk.org/dpdk-stable) and our fork of the project is included by consumer projects as a git submodule. During the CMake configure step we call `conan create` and `conan install`. For the vast majority of cases `conan create` will find binaries in artifactory and download them. But every once in a while, the consumer project will be testing a change to DPDK source and our current process makes it trivial for them to rebuild the conan package and test the change. This has been working great with conan 1.x, but with 2.0 I can't use a lockfile for DPDK package anymore because the `conan create` step will *always* modify the timestamp in the package revision, whether the DPDK source/build settings have changed or not.

For now, I've decided not to include DPDK in the lockfile because of this issue. This is not a big deal because the version of the package is tied to the git submodule version and we don't have a bunch of build configurations we support for each commit, just `Debug` and `RelWithDebInfo`. But still, it would be nice to allow the flexibility of easily rebuilding the package from source and using a lockfile. I suspect my problem would be easier to solve if we managed the conan package creation manually, but we have it baked into CMake right now and we like it that way because it *just works* for consumers, they don't really need to learn conan.

**Comment by memsharded** [comment]
> Thanks for the detailed explanations @memsharded, really appreciate it. I'm still confused about the need for the timestamp in the revisions though. Agreed that multiple revisions may appear in the graph but if everything but the timestamp portion matches, doesn't that necessarily mean that the two revisions identify binaries that are identical? By identical I mean they have the same source revision and build settings.

Not really, a different recipe revision means exactly that: that something has changed in the recipe, source code or build scripts, and you cannot guarantee that the binaries will be identical, or even correct. A example: adding a "patch" to the recipe of a third party library. The version is still the same, because it correspond to the upstream version, but that patch will be hashed into the ``recipe revision``, creating a different recipe revision. Such revision will need to build its own binaries, which might be completely different to the previous one as an effect of the patch.

> This has been working great with conan 1.x, but with 2.0 I can't use a lockfile for DPDK package anymore because the conan create step will always modify the timestamp in the package revision, whether the DPDK source/build settings have changed or not.

I think that behavior should be the same in both 1.X and 2.0, maybe there could be something different in the configuration or setup.
In any case, the logic is that you shouldn't have a package with more than 1 package revision for a given ``package_id``. If that happens it means something not right in the process, because you re-built from exactly the same sources (recipe-revision) and for exactly the same configuration (package-id), the same binary. It resulted in a different package-revision, because typical non-deterministic C++ builds, but otherwise it should be exactly the same package-revision.
You can avoid this, but first checking if the binary exist (with ``conan graph info`` for example), or directly doing a ``conan create . --build=missing``. This command is able to skip the re-build of the package if a binary already exist locally or in the server side.

**Comment by memsharded** [comment]
Hi @praetorian20 

Is this question responded, may we close it? Is there any pending clarification or question? Thanks!

**Comment by praetorian20** [comment]
Hi @memsharded, sorry the delay in responding, I've been working on other things and conan2.0 upgrade has taken a backseat for now. I think you've answered the lockfile workflow questions, I have a path forward on that. So thank you once again for the detailed answers.

My experience with `conan create` doesn't match what you said in your previous comment, even when nothing in the package has changed the lockfile gets an updated timestamp if I rerun `conan create`. I'll try this out once again when I get back to the conan work, and open a new question if needed with more details.
