### ISSUE TITLE
[bug] Configure doesn't apply options for external libraries anymore since conan 2.0.1

### ISSUE THREAD

**Issue by twantonie** [conan-io/conan#13465]
### Environment details

* Conan version: 2.0.1/2.0.2

### Steps to reproduce

With a new cmake_lib template with the boost library added to it but with zlib excluded in configure.
[conanfile.zip](https://github.com/conan-io/conan/files/10995653/conanfile.zip)

boost graph info .

### Logs

On conan 2.0.0 it produces the following correct output:
[graph_info_2_0_0.txt](https://github.com/conan-io/conan/files/10995674/graph_info_2_0_0.txt)
On conan 2.0.2 it produces the following output, see here that zlib is included even though it shouldn't be included according to the options.
[graph_info_2_0_2.txt](https://github.com/conan-io/conan/files/10995678/graph_info_2_0_2.txt)

**Comment by memsharded** [comment]
Thanks very much for reporting @twantonie 

You are right this used to work in 2.0.0, but some other related bug got it removed. I think this is also not the first issue related this so we gave it a second look, and we are trying to recover it in https://github.com/conan-io/conan/pull/13467, for the next patch 2.0.3. It is not fully sure that it will be merged, because the intention is that it needs to be explicit, like:
```python
self.options["zlib/*"].option = "value"
```
but there was some help there in 2.0.0 apparently intended to easy the transition from 1.X -> 2.0 that got removed while working on other bug, because the intention is that the explict way is the recommended one. Please keep tuned to https://github.com/conan-io/conan/pull/13467

**Comment by twantonie** [comment]
Thanks for the explanation. If that pull request doesn't make it through, I'd recommend failing the configure step, since now it just silently does the wrong thing. Which is what tripped me up, whereas specifying the options in default_options it does raise an error I believe.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/13467 was merged, it will be in 2.0.3

**Comment by memsharded** [comment]
The PR was merged for next 2.0.3
