### ISSUE TITLE
[question] Aliases, user/channel in Conan 2.0?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#13474]
Hi,
I've read the migration guide and I'm a but puzzled. I remember from previous issues reported, that user/channel and alias handling would be somewhat changed (e.g. aliasing is against package immutability, user/channel was a "leftover" from the old ages, when it was not pobbile to have multiple remotes(?, I might be wrong on that, but it was related to some sort of server limitations).

But currently I find not much information in the migration guide about those items. Is user/channel still suppored? Is there a way to override user/channel on a per-package / global level? What is the situation with aliases, are they fully supported and will be supported still?
Thanks,

**Comment by memsharded** [comment]
Hi @harsszegi 

Thanks for your question.

Regarding ``alias`` it is true that it is not documented yet in 2.0. It has not been removed in 2.0, and there are no plans to remove it, to ease the transition from 1.X to 2.0 from users relying on it. But ``alias`` was created long time ago, before there were ``version-ranges``, ``lockfiles``, and many other Conan features. Conan 2.0 is also adding a new mechanism to select pre-releases dynamically to be able to test more easily new pre-releases. In theory ``alias`` should not be necessary, as we are not aware that other package managers in other languages have something similar. It will probably be recommended to migrate to those mechanisms during 2.0. We will wait for users feedback regarding these alias, so if you have a brief summary of your use case and if you have considered other approaches, that would help.


Regarding user/channel, they are still recommended, specially the user, but just as a naming convention, not to be used as a parametrization of the graph or dependencies. It is very useful to have your own packages named like ``pkg/version@myteam`` (Conan 2.0 allows defining only the user), because that allows to define patterns for example to differentiate between your own packages and third party packages. Override dependencies with different user/channel will still be possible, but using that as versioning approach is not recommended, either in 1.X anymore.

**Comment by harsszegi** [comment]
Awesome, thanks a lot for the clarification, appreciate it!

**Comment by jasonbeach** [comment]
I see that for the user and channel, you can specify them either on the command line or in the `conanfile.py`. What's the right to specify it in the conanfile but then be able to override it from the command line?  It doesn't look like there's a `set_channel` hook like there is for `set_version`.  What looks like it works is if I set the channel in the `set_version` function. , i.e. 

```
    def set_version(self):
        self.version = load(self, "version.txt").strip()
        self.channel = self.channel or "test"
```
but I don't have any idea if that has unintended effects (i.e. sets the channel at the right time during the package creation process.)

**Comment by memsharded** [comment]
Hi @jasonbeach 

Conan 2.0 is no longer recommending to use variable users and channels, and as such the best is to leave them constant. Conan 2.0 can even drop the channel and use only the user name if necessary (the user name can be convenient for some scenarios). But the channel is mostly not necessary anymore. Instead, defining different repositories in the server side and using them, copying packages between repositories is the way to manage different stages of maturity of packages, but always keeping the same package reference. In that regard the ``conan copy`` command has been dropped from Conan 2.0, and packages will always be considered immutable, including their references (pkg/version@user/channel#revision)

**Comment by aander80** [comment]
Hello!

> Conan 2.0 is also adding a new mechanism to select pre-releases dynamically to be able to test more easily new pre-releases.

@memsharded could you point me to where I can read more about this?

**Comment by aander80** [comment]
> Hello!
> 
> > Conan 2.0 is also adding a new mechanism to select pre-releases dynamically to be able to test more easily new pre-releases.
> 
> @memsharded could you point me to where I can read more about this?

I suppose this is `core.version_ranges:resolve_prereleases`.
