### ISSUE TITLE
[question] How to test a tool with an option (Conan v2)?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#13481]
### What is your question?

Consider a test tool recipe that needs an option ([tool_test.zip](https://github.com/conan-io/conan/files/11010618/tool_test.zip)). If I try to create a package for Conan v1 with
```
conan create . -o tool_test/*:option=True
```
everything goes fine. But then I do the same with Conan v2, it fails to find a binary package:
```
conan create . -o tool_test/*:option=True
...
ERROR: Missing binary: tool_test/0.1:e3e483926f5ed233c3789e683c93c4b2a68b5876

tool_test/0.1: WARN: Can't find a 'tool_test/0.1' package binary 'e3e483926f5ed233c3789e683c93c4b2a68b5876' for the configuration:
[options]
option=False

ERROR: Missing prebuilt package for 'tool_test/0.1'
Check the available packages using 'conan list tool_test/0.1:* -r=remote'
or try to build locally from sources using the '--build=tool_test/0.1' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'
```
Is it expected? Is there any workaround except passing a profile with the option set?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your report.
Conan 2.0 has completely decoupled the ``test_package`` step from the package creation step. In other words, it doesn't matter if the ``test_package`` does a ``tool_requires`` to the tested package, that is not forcing the build context, because the ``test_package`` is not even checked in the first stage creating the package.

The goal is that the package that is created is exactly the same with or without the ``test_package`` folder:
```
conan create . -o *:option=True
conan create . -o *:option=True --test-folder=""
```
Should be identical. It was not in Conan 1.

So it is necessary at the moment to indicate it is a build-require with:
```bash
conan create . -o *:option=True --build-require
```
Please try that and et us know.

**Comment by db4** [comment]
Hi @memsharded,

Thanks a lot for your help, now I understand it better. And yes, a recipe attribute instead of a command line option that you proposed elsewhere would be quite useful.

**Comment by memsharded** [comment]
Ok, I think you want to track https://github.com/conan-io/conan/issues/13440 to see more about this.
