### ISSUE TITLE
[question] How to use conan.tools.scm Git with a proxy?

### ISSUE THREAD

**Issue by gabeblack** [conan-io/conan#13493]
### What is your question?

I have configured my `global.conf` with http/https proxies (i.e. `core.net.http:proxies`). The proxies are used if I use the `get` module from `conan.tools.files`. However, it seems the proxies are ignored using `conan.tools.scm`'s Git. 

Is there something I need to do to have conan's scm module honor/use the proxies configured in `global.conf`?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @gabeblack 

Thanks for your question.

The problem is that the ``proxies`` config can only be used by own Conan ``http`` calls, when it downloads, uploads, etc. 

But ``git`` is an external binary. Conan has no way to configure proxies or any other kind of configuration to git. So ``git`` configuration has to be system wide, it is assumed that command line invocation of ``git``, without Conan at all should work, because this is what developers do anyway. Something similar to ``git`` auth, it is expected that it will be provided system wide (ssh-keys or similar).

Please let me know if this makes sense.

**Comment by gabeblack** [comment]
ok, I didn't want to set up a global config for git in order to clone, but rather have it sandboxed to conan's global.conf.

I found that I can do `git.clone(url=GIT_URL, args=["-c", MY_PROXY])`. It would be nice if conan had an api to get the configured proxy set in global.conf, so I could pass in the args something like `args=["-c", conan.config.http_proxy]`.

**Comment by gabeblack** [comment]
Actually, thinking of it further, if I do that, it kind of breaks the recipe. If someone doesn't have a proxy, the recipe will use one because it's hardcoded to use it. So it is probably best to do what you suggest, where I have git configured to "just work" in the normal shell.

**Comment by memsharded** [comment]
> Actually, thinking of it further, if I do that, it kind of breaks the recipe. If someone doesn't have a proxy, the recipe will use one because it's hardcoded to use it. So it is probably best to do what you suggest, where I have git configured to "just work" in the normal shell.

yes, exactly, we have learned that the more decoupled and orthogonal is the Git configuration, the better. Conan shouldn't be responsible for setting up git correctly, because also in most cases git will be even ran before Conan itself, like in CI, to fetch sources, then ``conan install`` or ``conan create``, etc
