### ISSUE TITLE
[suggestion] allow dyanamic user/channel

### ISSUE THREAD

**Issue by hubertba** [conan-io/conan#13507]
### What is your suggestion?

Hello 

We currently map the GitHub Org our package is developed in onto the user to express a sense of CodeOwnerShip ( and also detect if the package was forked ) and the channel onto the branch to express a certain maturity which we can guarantee over branch protection rules.

Is there a specific reason to not allow setting user and channel dynamically as previously?
Would that be something we could contribute if it matches the goals of conan2

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @hubertba 

Thanks for your question.
But I am sorry, I am not sure what you mean. Conan 2.0 also allows defining dynamically the user and channel with ``conan create --user=myuser --channel=mychannel``, is that what you are looking for?

It also allows to use only the user but not the channel, if desired.

**Comment by hubertba** [comment]
Hi @memsharded 

Thanks for your answer, but this was not what I was searching for.
In conan 1.X we were able to assign the user and the cannel via an @property and a function like def default_user(self): to set the user at creation time of the package. [link to 1.x docu](https://docs.conan.io/1/reference/conanfile/attributes.html?highlight=default_user#default-user-default-channel)

Is there a similar feature in conan 2 ? because I did not find it yet.

**Comment by memsharded** [comment]
Conan 2.0 contains now the ``user=xxx`` and ``channel=yyyy`` class attributes in recipes. It is not a function, but an attribute, but it allows to define it in recipes and forget about it. I guess it might be possible to use the method ``set_name()`` to define them too. Please let me know if this is what you are looking for.

It is not a function, because the idea is that user/channel is not that dynamic anymore, it is something that should be fixed in the recipe and forget about it. No promotions can be used based on user/channel (no ``conan copy`` command anymore), and doing conditional requirements or dynamic requirements based on user/channel is not recommended either.

**Comment by hubertba** [comment]
Hi

Sorry for the long waiting time. I had a chat with a colleague and I finally got it. We will set the user in the pipeline and I am happy.

**Comment by memsharded** [comment]
Thanks for the feedback and following up!
