### ISSUE TITLE
[question] what is the difference between module 'conan' and 'conans'

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#13501]
### What is your question?

I saw that the [migration guide](https://docs.conan.io/1/migrating_to_2.0/recipes.html#python-import-statements) says that 
`All the imports from the conans package have to be replaced. The Conan 2.0 ones are in the conan package. Note the plural.`
but i still see that there is a module called `conans`, and there are still things need to be imported there. e.g, `from conans.model.version import Version`

so my question is what is the purpose of having moudel `conan` and `conans`? how things are separated for them?
I didnt find any info regarding this in the documentation or the source code.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @shelper thanks for your question.
The distinction comes from early in the lifetime of Conan which supported Python 2.7 in which it was risky to have an import folder named the same as the project, and so `conans` was born.
Once that restriction was lifted, a decision was made to leave the private/legacy/old imports in `conans` and have everything new/which we want users to be able to use in the new `conan` folder, as simply renaming it would have been a breaking change.

The current idea is that public facing APIs are available from `conan` and the implementations go to `conans`, but as you noted there are a few things that live in the "wrong" place (Because they were not expected to be useful outside Conan itself for recipes, for example). Note that the idea is to eventually merge both (afaik, I think I can remember discussing this with @memsharded) but nothing yet.

Hope this was helpful, feel free to ask any other question should you have more :)

**Comment by shelper** [comment]
thanks @RubenRBS, this is clear, but i think the migration guide still needs some adjustment as according to your reply, i think the wording `All the imports from the conans package have to be replaced. The Conan 2.0 ones are in the conan package. Note the plural.` seems to be overstated...

**Comment by memsharded** [comment]
> Note that the idea is to eventually merge both (afaik, I think I can remember discussing this with @memsharded) but nothing yet.

Yes, in Conan 2.0, recipes will only import from ``from conan.tools`` and ``from conan.errors`` and ``from conan import ConanFile``. 
The remains in Conan 2.0 of ``from conans`` is totally internal implementation detail, and it will eventually moved to ``from conan.internal`` scope.

**Comment by shelper** [comment]
so, if all i need in my conanfile.py is `from conan.*`, then is there any suggestion/workaround for this [package_id trick](https://docs.conan.io/2/reference/conanfile/methods/package_id.html?highlight=package_id#partial-information-erasure
)? 'cus this `Version` function is from `conans`.

**Comment by memsharded** [comment]
There is a new ``from conan.tools.scm import Version``
