### ISSUE TITLE
[feature] Provide ability to suppress Conan 1.x legacy warnings

### ISSUE THREAD

**Issue by marc-mw** [conan-io/conan#13517]
### What is your suggestion?

While I certainly see the value of issuing warnings about deprecated features when developing or porting Conan 2.0 recipes, these warnings are noise when running a CI pipeline. For example:

> zlib/1.2.13: Already installed! (4 of 4)
> WARN: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
> WARN:     'env_info' used in: cmake/3.25.1, gcc/10.3.0
> WARN:     'cpp_info.names' used in: zlib/1.2.13

It would be nice if there was an easy way to globally suppress this type of warning--that is warnings that will go away when the Conan 1.x support is stripped out of Conan 2.0 compatible recipes. Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @marc-mw 

Thanks for your suggestion

The truth is that we get tons of complains whenever something changes and breaks something. So these warnings are very important, because those things will be removed in 2.1, 2.2 or 2.X, and it will break recipes if they are not removed on time. Being able to hide those warnings is no good for anyone, users will forget about it, and then complain if the next release cause these warnings will become hard errors. The warnings were limited to a very few lines, probably 3-5 lines only, it is not that it is making the pipeline output very noisy. In my opinion, this is the type of warning that we never want to hide, but I'll get some feedback from the team. It would be good to understand if there is some other reason, beyond the "it would be nice not to see them":

**Comment by marc-mw** [comment]
Hi @memsharded,

Thanks for your insights. To clarify, I didn't mean to suppress them in CCI but only in custom CI workflows where the CCI recipes are being re-used but (ideally) not modified and only when a special flag would enable such behavior. This would make the output from Conan 2.0 cleaner until the CCI recipes drop their legacy 1.x support. Today, when demo'ing Conan 2.0, observers question why they see so many warnings go flying by.

**Comment by memsharded** [comment]
This was implemented in #13706 for next 2.0.5
