### ISSUE TITLE
[question] Update flag of conan install should fetch the latest version of the package even without version ranges ?

### ISSUE THREAD

**Issue by sandeshhardikar** [conan-io/conan#13572]
### What is your question?

Dear Team ,

This is a question and a suggestion .

I read the `--update` parameter help description as follows in `conan install` command

`-u, --update    Will check the remote and in case a newer version and/or revision of the dependencies exists there, it
                        will install those in the local cache. When using version ranges, it will install the latest version that
                        satisfies the range. Also, if using revisions, it will update to the latest revision for the resolved
                        version range.`

The first part of the statement `Will check the remote and in case a newer version and/or revision of the dependencies exists there, it will install those in the local cache.` makes me understand that it will fetch a newer version of my package even though i dont specify the version ranges and this is exactly what i need . 

### My usecase : 

1. During the normal `ci` build (i.e during Pull requests) , I shall be able to able to fetch the exact version of the package
2. During the nightly `ci` build , I want to be able to fetch the latest version of the package with `--update` flag . 

I do not want to use version ranges since I want my builds to be deterministic when not doing nightly builds . 

### Suggestions : 

- `--update` parameter should be able to fetch the latest version and revision of the package , without the presence of version ranges
                                                                                       OR
- A new parameter to enable and disable version ranges ?

I am also open to any other hints to solve the usecase mentioned above

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandeshhardikar 

Thanks for your comments

> he first part of the statement Will check the remote and in case a newer version and/or revision of the dependencies exists there, it will install those in the local cache. makes me understand that it will fetch a newer version of my package even though i dont specify the version ranges and this is exactly what i need .

This might need some clarification, but the behavior is correct. Conan will not fetch "latest" version of something if some package is defining ``self.requires("zlib/1.2.11")``, it will always be requiring ``zlib/1.2.11``, and not other version, even if the new version is already installed in the cache, and was downloaded already, the dependency will be done to ``1.2.11`` and not to other versions. 

If you want recipes to resolve and behave differently, then use the range expression: ``self.requires("zlib/[>1.2 <1.3]")`` for example. There is no need for extra parameters, the users can already define the behavior they want. Enabling what you propose, would be massively breaking, because it will introduce breaking versions all the time, like if you depend on ``opencv/2.3``, and then you will be automatically upgraded to the very breaking ``opencv/4.5``? That doesn't make sense. Version ranges need to be explicitly defined to define the valid version ranges to which a recipe can update.

**Comment by sandeshhardikar** [comment]
Thanks for your super fast response as usual . 

`There is no need for extra parameters, the users can already define the behavior they want. `

my desired behaviour would be to enable version ranges for nightly build  and disable the version ranges and have a pinned version for normal builds . I see no other way than defining the dependencies twice depending on the type of build  in the recipe . Thanks again for the explanation and clarification.

**Comment by memsharded** [comment]
I think you are looking for lockfiles, please have a look to the lockfile docs in https://docs.conan.io/2/tutorial/versioning.html

This is standard mechanism across package managers like npm and others: version ranges to be able to pull the latest in the valid range, then lockfiles to achieve exact reproducibility of versions.
