### ISSUE TITLE
consumer can not download packages which I packed.

### ISSUE THREAD

**Issue by fancygit** [conan-io/conan#13614]
### What is your question?

Here is my recipe
from conan import ConanFile
from conan.tools.files import copy
import os

class HfvInspect(ConanFile):
    name = "hfvinspect"
    version = "2.0.1"

    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}

    default_options = {"shared": False, "fPIC": True}
    requires = ["hfvlibrary/2.0.1"]
    generators = "CMakeDeps"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def baseName(self):
        return "HfvInspect"
        
    def package(self):
        arch = self.settings.get_safe("arch", default="x86")
        if arch == "x86":
            arch = "Win32"

        build_type = self.settings.get_safe("build_type", default="Release")

        print("=======================")
        print("Build/%s_%s/%s.lib"%(arch, build_type, self.baseName()))
        copy(self, pattern="*.h", src='.', dst=os.path.join(self.package_folder, "include"), keep_path=False)
        copy(self, pattern="Build/%s_%s/%s.lib"%(arch, build_type, self.baseName()), src='.', dst=os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, pattern="Build/%s_%s/%s.dll"%(arch, build_type, self.baseName()), src='.', dst=os.path.join(self.package_folder, "bin"), keep_path=False)

    def package_info(self):
        self.cpp_info.libs = [self.baseName()]

I packed the binary lib and include folders, then I uploaded them to the JFrog.

PS C:\Users\harry> conan list hfvlibrary:* -r txww
txww
  hfvlibrary
    hfvlibrary/2.0.1
      revisions
        818bd761d49adc9289527d690e91ef79 (2023-03-27 16:22:46 UTC)
          packages
            ae4d4001e234191236108e2b6891c7a3025ec5d2
              info
                settings
                  arch: x86
                  build_type: Debug
                  compiler: msvc
                  compiler.runtime: dynamic
                  compiler.runtime_type: Debug
                  compiler.version: 192
                  os: Windows
                options
                  shared: True
                requires
                  jbig/20160605#2d29fa02aacd76902e0d2cbbc24631ef:e4dca085a89e4ca00f3ca82c801662d36aceac70
                  libdeflate/1.17#71f492ef993b45d9b961b36fb85e801f:1feaaaa4dde6c13b4d5e0b75ae078ac9e4ab2b1a
                  libjpeg/9e#68269859e4325ddc3f995d1fd3fc9187:1feaaaa4dde6c13b4d5e0b75ae078ac9e4ab2b1a
                  libpng/1.6.39#deca555b0890e584fc895ba756e83c06:865a1b19ae9d207da564337b643cc893805258a0
                  libtiff/4.4.0#e6d8942022c89a22dfbe1a9b77289c7e:99678841da3608293a8492ef038829e422a111f7
                  libwebp/1.3.0#d92654dbce1f8cb8ae45d5388f86fcfe:632480428c56e7fc7fdf67a82ffa55e70d0034d3
                  xz_utils/5.4.0#186e94237b66f785e4ea095f2f621a56:1feaaaa4dde6c13b4d5e0b75ae078ac9e4ab2b1a
                  zlib/1.2.13#13c96f538b52e1600c40b88994de240f:1feaaaa4dde6c13b4d5e0b75ae078ac9e4ab2b1a
                  zstd/1.5.4#15ac0bc440f89247276d78ea4fdf8b14:f7eda18446204245ddca91e447f21659ee8b6afb
            6ada2b1b18527439763f90baeaf118496b7b8327
              info
                settings
                  arch: x86_64
                  build_type: Debug
                  compiler: msvc
                  compiler.runtime: dynamic
                  compiler.runtime_type: Debug
                  compiler.version: 192
                  os: Windows
                options
                  shared: True
                requires
                  jbig/20160605#2d29fa02aacd76902e0d2cbbc24631ef:4c98541369841e147ebbba95651a111a25ce24da
                  libdeflate/1.17#71f492ef993b45d9b961b36fb85e801f:25f93aaacbebaa913a6aaecd4fa01e3ef49c798a
                  libjpeg/9e#68269859e4325ddc3f995d1fd3fc9187:25f93aaacbebaa913a6aaecd4fa01e3ef49c798a
                  libpng/1.6.39#deca555b0890e584fc895ba756e83c06:779a65a699f8fbb8c725ae5b03b7a21f30a7d3b5
                  libtiff/4.4.0#e6d8942022c89a22dfbe1a9b77289c7e:1470b2f48a7f48badc53836536c41fa714a3d728
                  libwebp/1.3.0#d92654dbce1f8cb8ae45d5388f86fcfe:69e41dedfc7f97155bcfd2aeb65197708fd1aee7
                  xz_utils/5.4.0#186e94237b66f785e4ea095f2f621a56:25f93aaacbebaa913a6aaecd4fa01e3ef49c798a
                  zlib/1.2.13#13c96f538b52e1600c40b88994de240f:25f93aaacbebaa913a6aaecd4fa01e3ef49c798a
                  zstd/1.5.4#15ac0bc440f89247276d78ea4fdf8b14:bc2a8dd1fd7ca5bf802db9f67e874e986d8b8f1c
            3967b599fc5754a562617a7a5bfdaa4b52df193a
              info
                settings
                  arch: x86_64
                  build_type: Release
                  compiler: msvc
                  compiler.runtime: dynamic
                  compiler.runtime_type: Release
                  compiler.version: 192
                  os: Windows
                options
                  shared: True
                requires
                  jbig/20160605#2d29fa02aacd76902e0d2cbbc24631ef:cce0638b24486ce38229e298351f25f1373c8986
                  libdeflate/1.17#71f492ef993b45d9b961b36fb85e801f:41ad450120fdab2266b1185a967d298f7ae52595
                  libjpeg/9e#68269859e4325ddc3f995d1fd3fc9187:41ad450120fdab2266b1185a967d298f7ae52595
                  libpng/1.6.39#deca555b0890e584fc895ba756e83c06:e5fe0b6535d74eb6994abd4674a39f9ab96055f1
                  libtiff/4.4.0#e6d8942022c89a22dfbe1a9b77289c7e:a2b0a68d062c3daca42a7b277a10552de8c27ff6
                  libwebp/1.3.0#d92654dbce1f8cb8ae45d5388f86fcfe:108623af8e2ffcc15db6c3d7d44e673780f612c7
                  xz_utils/5.4.0#186e94237b66f785e4ea095f2f621a56:41ad450120fdab2266b1185a967d298f7ae52595
                  zlib/1.2.13#13c96f538b52e1600c40b88994de240f:41ad450120fdab2266b1185a967d298f7ae52595
                  zstd/1.5.4#15ac0bc440f89247276d78ea4fdf8b14:43819e6b96c119efbb6462ca6fe82f587b56d528
            4664824d02fd894072b9964f3868e46e5b973e0f
              info
                settings
                  arch: x86
                  build_type: Release
                  compiler: msvc
                  compiler.runtime: dynamic
                  compiler.runtime_type: Release
                  compiler.version: 192
                  os: Windows
                options
                  shared: True
                requires
                  jbig/20160605#2d29fa02aacd76902e0d2cbbc24631ef:bf99faa1d6cdd0228c4a2d9ca724c80ab2070cd8
                  libdeflate/1.17#71f492ef993b45d9b961b36fb85e801f:7ab1c199a1c5aa3d35bb43d7a45168d0ef29cf50
                  libjpeg/9e#68269859e4325ddc3f995d1fd3fc9187:7ab1c199a1c5aa3d35bb43d7a45168d0ef29cf50
                  libpng/1.6.39#deca555b0890e584fc895ba756e83c06:a638816844af5ce46ad834a94313845434e1c7e6
                  libtiff/4.4.0#e6d8942022c89a22dfbe1a9b77289c7e:014ad25bf34f4b05fe927e23c92844b70bacb52c
                  libwebp/1.3.0#d92654dbce1f8cb8ae45d5388f86fcfe:ad37ba069488c9a6236f93482e445d8d92760473
                  xz_utils/5.4.0#186e94237b66f785e4ea095f2f621a56:7ab1c199a1c5aa3d35bb43d7a45168d0ef29cf50
                  zlib/1.2.13#13c96f538b52e1600c40b88994de240f:7ab1c199a1c5aa3d35bb43d7a45168d0ef29cf50
                  zstd/1.5.4#15ac0bc440f89247276d78ea4fdf8b14:70b39e617b27576562366d24164e00fb19e96495

Test1: When I do the command "conan install --requires=hfvlibrary/2.01 -r txww",  everything is ok. [Win10]
Test2: But when others try to do the samething to install the recipy,  conan report that [Missing pre-build binary]. [Win11]

The profile is exactly the same:

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.version=192
os=Windows

I found that the difference between "Test1" and "Test2" is that the [package id] is different. Is there somethig wrong when I packed it?
I just wanna know how to pack my package, so others can use it well.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fancygit 

Thanks for your report.
I am not sure what could be happening.
If the ``package_id`` is different that could be because:
- The settings are different. Having the full output for both the execution of ``Test1`` and ``Test2`` could help to make sure, I suspect there could be some differences in the profiles. (The logs can be uploaded as files, no need to copy & paste the whole output)
- The options are different, like someone is passing a ``-o *:shared=True`` to request shared libraries or something like that
- The dependencies are different. If they are installed from ConanCenter, and they are not locked, they can be getting new revisions or even new versions, that would require re-building your package to take into account those new dependencies. Close comparation of the logs could help to know if this is the case. In general it can be a good practice to upload a copy of your dependencies to your repo together with your package, so installing your package from it will always get that exact set of dependencies, and help with reproducibility and having more robust installations (as it will not be affected by possible changes in ConanCenter)

Please try to upload the logs for Test1 and Test2, and we will try to have a look. Thanks!

**Comment by fancygit** [comment]
[Test1.txt](https://github.com/conan-io/conan/files/11154303/Test1.txt)
[Test2.txt](https://github.com/conan-io/conan/files/11154304/Test2.txt)

After compared these two files,  I found the dependency package **"libpng/1.6.39"**   's package-id  are different.
About this package,  it is missing when I locally installed it. So conan help me **build it from source** of the version 1.6.39.
And then I **upload it into my own repo**.
![image](https://user-images.githubusercontent.com/2269316/229957611-8d55a787-a46d-4c16-bb19-3acc6eb8680c.png)

Then I tried :(**In Computer Test2**)
1. I **remove** the remote "conancenter" first, and then **add** it back. ( Just put my own remote to the top). And it works.
2. I don't know **if it is the correct solution**.

**Comment by memsharded** [comment]
Ok, that makes sense.
Indeed, if one of the dependencies had to be built because it changed, it is also expected in many cases that will also require building a new binary for the consumer of that package, in this case your package.

Yes, the setup that you did with your remotes ordered that way (first yours, then ConanCenter), also makes sense, but that also depends on the use case, the constraints, policies, development practices at the org, etc. There are some possible setups that we have seen from our users:

- Not having the ``conancenter`` remote at all, but build packages directly from a fork of the Github ``conan-center-index`` repo, and upload to your own private repo. This is relatively doable, and achieve the most secure and robust setup.
- Having kind of "air-gap" setup, in which someone, like CI or a maintainer, gets some packages from ConanCenter, test and validate them, and upload them to a private repo. Typically getting the recipes, but building from source their own binaries.
- Using some of the server features like Artifactory virtual and remote repos that allow aggregation of ConanCenter into a single repo. This can be convenient, and has some advantages, but don't fully isolate from the upstream ConanCenter, if new recipe changes break your build, they will still be pulled, and if ConanCenter is down, this will still be a problem
- Using a client-side based remote ordering approach, similar to what you are doing.

**Comment by AbrilRBS** [comment]
Hi @fancygit, I'm closing this as stale as we didn't hear back from you for a while now.

Feel free to reopen/create a new issue if this is a problem again, thanks!
