### ISSUE TITLE
[question] How to keep syncing conan package locally without re-create package

### ISSUE THREAD

**Issue by xuantambk** [conan-io/conan#13619]
### What is your question?

Hi ,
I've got a new request from my team member , he doing kind of integration stuff in our project who dealing with many conan package. Sometime he need to change something in some conan packages.. then he need to do `conan create . pkg` for all changed package.. and then start using it from other component.

We just moved to conan setup recently where we split up big project into multiple part (libs, components...) with multiple conan package setup.

The question is is there any way to keep the working model same with Cmake in single project setup, so if you change 1 line of code in any Component (included in CMakeList.txt) then if other component in CMakeList want it it can just rebuild what they need.
In Conan setup it is always
1. Made changes in package
2. Create new package (with newer version maybe)
3. Start using it.. somewhere..
What we need sound like a instant development changes and working model for that with conan.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @xuantambk 

Thanks for your question.
Your question is not specific to Conan, but it is a known thing in all package management, for all languages. It is a tradeoff that is made between the 2 major paradigms:
- Monorepo, where everything is in a single repo, and everything builds from source, in a monolithic way. Versions are not that important, only 1 version, the repo commit is really necessary.
- Component or package based, in which every library/component of the system can be developed and released independently of the others. Managing versions correctly is critical.

When going component-based development, the problem of what to do when a new package version is released is a problem of Continuous Integration. At a very high level it consists of something like:
- Teams should have a set of "products", the final applications or products they are actually concerned about and need to be working. The deliverables. In Conan terms, it could be something like ``myapp/1.2``, ``myotherapp/3.4`` and ``somesdk/12.1``.
- When a new version of a dependency, like ``pkg/1.3`` is released that fixes some bugs from previous ``pkg/1.2`` (and the dependency doesn't need to be a third party, it can be a package that we just created with a new version and put in in the server), we need to test if that new package integrates cleanly in our products, and if something needs to be rebuilt from sources, rebuilt it to account for the dependency change
- So for every "product" we launch a build, that will check if that new ``pkg/1.3`` is used or not (this can be done with ``conan graph build-order`` command. If the new version is outside of my products ranges, for example ``somesdk/12.1``, has ``requires = "pkg/1.2"`` it will not be used in ``somesdk``, but if other product like ``myapp/1.2`` has ``requires = "pkg/[>=1.0 <2]"`` then, ``pkg/1.3`` will fit in the range
- We can integrate all build orders into a consolidated one, to avoid duplicated builds. In conan: ``conan graph build-order-merge``
- Then, the builds for the affected consumers of ``pkg/1.3`` needs to be done. Iterating the above build order, every consumer is rebuilt from sources. Packages are uploaded to a temporary server repo, like "build" repo.
- If everything is green, all builds correctly, ``pkg/1.3`` integrates cleanly, the binaries in the "build" repo can be copied to the main "develop" repo
- If something fails, because ``pkg/1.3`` breaks some consumers there is a version issue. If it is breaking changes, the package should have been versioned like ``pkg/2.0``, so it is not used by default by consumers version ranges, and that would allow developers to change the consumers code to adapt to the new ``pkg/2.0``.

It is true that our docs are missing this information at the moment, it is a pending item, we will work on this as soon as possible.

**Comment by memsharded** [comment]
Closing this question as responded. Please do not hesitate to open new issues for any further follow up or question you might have.
