### ISSUE TITLE
[question] How to download remote artifact by options?

### ISSUE THREAD

**Issue by donlk** [conan-io/conan#13617]
### What is your question?

Hi!
I would like to download built packages from a self-hosted remote. Also, I would like to download only the packages that have had certain options/settings during their build.
Let's say I have two **P** packages. One was built with the **with_gpu_support** option **True** and the other with **False**. I want to be able to specify to `conan download` to only consider packages of **P** that were built with GPU support.

I couldn't find any option specifiers for the download command, not any other for that matter. I searched around, and it was somewhat possible to do this previous of conan 2.0 by listing all **P** package config options:
`conan search P --remote=my_remote --options`
and then cherry picking the correct artifacts after parsing them in python for example. 

Why was this removed in 2.0 and is there a solution to my problem? I think it is a rather common use case.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @donlk 

Thanks for your report.
Indeed the ``conan download`` command in 2.0 has a ``-p PACKAGE_QUERY`` argument intended for this purpose. Same behavior as ``conan remove``, ``conan list`` and ``conan upload``.

If you tried that and it didn't work is because there is a small bug there, and the patttern ``-p options.with_gpu_support=somevalue`` was not matching. I have submitted a fix in https://github.com/conan-io/conan/pull/13618, it will be released in next 2.0.4. Thanks very much again for reporting this.

**Comment by donlk** [comment]
I'm glad I could pinpoint that bug, but sadly the package query discards even the `settings` attribute. A command like this only downloads the package sources in my case, without the prebuilt binaries, despite having a Linux build:
`conan download <project>/<version>@<user>/<channel> -p settings.os=Linux -r <remote>`

**EDIT:**
I've managed to solve this by omitting the `settings` prefix, only using `os=Linux`.
However, this is a rather confusing syntax. In one case it requires a certain "namespace", in other cases is explicitly does not. Shouldn't it be a bit more consistent to always require a namespace, be it `options` or `settings`?

**Comment by memsharded** [comment]
> I've managed to solve this by omitting the settings prefix, only using os=Linux.
However, this is a rather confusing syntax. In one case it requires a certain "namespace", in other cases is explicitly does not. Shouldn't it be a bit more consistent to always require a namespace, be it options or settings?

This was done because a few reasons:
- The most common queries are by ``settings``. Having to write ``-p settings.compiler=gcc AND settings.compiler.version=9`` makes the CLI longer and more tedious to write
- The ``settings`` are quite structured and known
- Historical reasons, the first package query only implemented settings, options were added later. Even if the changes to the cli are large in 2.0, we tried to not further break in this query too.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/13618, this will be in next 2.0.4 release, thanks again

**Comment by donlk** [comment]
Thank you.
One other thing though: How do you specify to download only the latest artifact if multiple exists with the same package query?

**Comment by memsharded** [comment]
By default the pattern of ``conan download`` is "latest" revision:

- ``conan download zlib/1.2.11:*`` => ``conan download zlib/1.2.11#latest:*:#latest``
- The ``latest`` placeholder can also be used explicitly in the pattern
- If you want to download like all the binaries for all the recipe-revisions you could do: ``conan download zlib/1.2.11#*:*``
