### ISSUE TITLE
[bug] Conanfile.py hash is sensitive to line-endings on Windows

### ISSUE THREAD

**Issue by garyo** [conan-io/conan#13627]
### Environment details

* Operating System+version: Windows 11
* Compiler+version: MSVC 17 (2022)
* Conan version: 1.59.0
* Python version: 2.9.6

### Steps to reproduce

1. Create a `conanfile.py` recipe for something, with CRLF line endings (or use an existing package)
2. `conan export` it
3. Build it, and `conan upload` the built package
4. Change the line endings of `conanfile.py`, for example using `dos2unix conanfile.py`
5. Try to install it as a requirement
6. You will see something like `WARN: The package mypackage/1.0:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b doesn't belong to the installed recipe revision, removing folder` and it will not download the previously uploaded package.

I think the `conanfile.py` hash should be computed after normalizing line endings (for instance, strip `\r`) to avoid needless rebuilds.

**Comment by memsharded** [comment]
Hi @garyo 

Thanks very much for your report.

I am afraid this wouldn't be a bug, but this is documented behavior, you can find it for example in https://docs.conan.io/2/knowledge/guidelines.html#good-practices: 

> All input sources must be common for all binary configurations: All the “source” inputs, including the conanfile.py, the conandata.yml, the exports and exports_source, the source() method, patches applied in the source() method, cannot be conditional to anything, platform, OS or compiler, as they are shared among all configurations. Furthermore, the line endings for all these things should be the same, it is recommended to use always just line-feeds in all platforms, and do not convert or checkout to crlf in Windows, as that will cause different recipe revisions.

Also in Conan 1.X FAQ: https://docs.conan.io/1/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine

> If you want to make the solution self-contained, you can add a .git/config file in your project that sets the core.autocrlf property (for the whole repo), or if you need a per-file configuration, you could use the .gitattributes file to set the text eol=lf for every file you want.

There are some reasons for this behavior. The ``recipe revision`` is the hash of the ``conanfile.py``, but also of every other file exported via ``exports`` and ``exports_sources`` with the recipe, so if the sources change, the ``recipe revision`` also change. It is very problematic to try to normalize line endings on such exported files, because it is practically impossible to know for sure which files are text files and which ones are not. Users would be exporting everything, files without extensions, with wrong extensions, text, binary, with different chmod flags, etc. So the only viable possibility is Conan not manipulating those at all and this is why the recommended approach is to configure Git to use the same LF in every platform.

**Comment by garyo** [comment]
That's totally fair -- I get it. I'll close this. But perhaps it would be nice if it could have been a bit more verbose about the mismatch: what file is mismatched (if you know -- maybe it's just one hash for the whole dir), or where to look for errors? Until an expert friend looked at my error log, I didn't even know that warning was the source of it. I just saw it rebuilding when I could see that "obviously" the package ID was the same. 
Maybe "rebuilding mypackage because mypackage/1.0:5a61a8... exists on the server but local recipe in `<dir>` has a mismatched hash for that package. Check line endings?"?

**Comment by memsharded** [comment]
Thanks for the suggestion.
We have also considered trying to improve this, but this is also more challenging than it seems.  When a recipe is exported into the cache, it will get a new recipe revisions as a hash (this is typically the first step of the ``conan create`` process). But a change in revision per-se doesn't indicate anything, actually the most natural reason of a recipe revision change is that something was actually changed in the conanfile.py or sources, it happens all the time. But to detect if this new revision would match previous different revisions it would be necessary:
- To ask servers for their existing older recipe revisions
- For each revision in each server (revisions can be interleaved, not necessary the latest), download the files of that recipe, and compare the contents with the current ones, applying some normalization.
This would be a super slow operation, that is to be done all the time for an error that just happens once to a very few users.
As always, this is a trade-off, too much overhead, plus the complexity of the added code, and the bugs and maintenance it would bring, for a very low frequency potential error.

Thanks very much again for your feedback.
