### ISSUE TITLE
[question] conan2 CMakeToolchain CMAKE_INSTALL_INCLUDEDIR not set

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#13677]
Hi,
I'm using conan2 with CMake and CMakeToolchain and have the following block as part of my `CMakeLists.txt`:

```
install(DIRECTORY include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
    FILES_MATCHING
        PATTERN "*.hpp"
)
```

Using `conan create .` everything builds as expected, however when using `conan install .` and `conan build .` a CMake error occurs `CMake Error at CMakeLists.txt:16 (install): install DIRECTORY given no DESTINATION!`.

I've found that this is due to conan not setting `CMAKE_INSTALL_INCLUDEDIR` in this case.

I would expect conan to set the `CMAKE_INSTALL_INCLUDEDIR` by default to `include` in both cases.

Now I'm left wondering is this intended behavior and if so what would be the correct approach to work around this? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @AxelZi 

Thanks for your question.

Quick hint: the ``conan install`` and ``conan build`` shouldn't be calling the ``cmake`` install functionality. This should only be called in the ``package()`` method (not the ``build()`` method), because only the ``package_folder`` is defined for the ``package()`` method, but in the local ``conan build`` the package folder is not defined, it doesn't exist.

Could you please make sure that the ``cmake.install()`` call is in the ``package()`` method?

**Comment by ghost** [comment]
Yes the call to `cmake.install()` is in the `package()` method.

My conanfile looks like this:

```python
from conan import ConanFile
from conan.tools.build import check_min_cppstd
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout

required_conan_version = ">=1.53.0"


class MySerializerConan(ConanFile):
    name = "my-serializer"
    version = "latest"
    default_user = "place-holder"
    default_channel = "develop"
    license = "Proprietary"
    description = "serializer component"
    topics = ("serializer", "serialization")
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps"

    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    exports_sources = "package/*"

    def validate(self):
        check_min_cppstd(self, "17")

    def config_options(self):
        if self.settings.os == "Windows":
            self.options.rm_safe("fPIC")

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def layout(self):
        cmake_layout(self, src_folder="package")

    def generate(self):
        tc = CMakeToolchain(self)
        # creates a compile_commands.json file in the build folder for IDE tools like VS Code and clang-tidy
        tc.variables["CMAKE_EXPORT_COMPILE_COMMANDS"] = "ON"
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["my-serializer"]
        self.cpp_info.set_property("cmake_file_name", "my-serializer")
        self.cpp_info.set_property("cmake_target_name", "my-serializer::my-serializer")

```

And my `CMakeLists.txt` like so:

```cmake
cmake_minimum_required(VERSION 3.10.2)
project(my-serializer)

# set C++ standard to version 17 for all targets
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(SOURCES
    src/serializer/Serializer.cpp
)

add_library(my-serializer ${SOURCES})

target_include_directories(my-serializer PRIVATE include)

install(DIRECTORY include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
    FILES_MATCHING
        PATTERN "*.hpp"
)

install(TARGETS my-serializer
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
)
```

**Comment by memsharded** [comment]
Thanks for the feedback.

Quick hint:
```python
self.cpp_info.set_property("cmake_file_name", "my-serializer")
self.cpp_info.set_property("cmake_target_name", "my-serializer::my-serializer")
```
Aren't necessary. Those are already the defaults, so no need to specify them in the recipe.

I see what you mean now. The code in the ``CMakeToolchain`` is like:
```cmake
 {% if default_include %}
           set(CMAKE_INSTALL_INCLUDEDIR "{{default_include}}")
           set(CMAKE_INSTALL_OLDINCLUDEDIR "{{default_include}}")
{% endif %}
```
Which should be defined as ``default_include`` should be "include". Could you please check the generated ``conan_toolchain.cmake`` file (the location should be in the output) and share it?

**Comment by ghost** [comment]
`conan_toolchain.cmake` gets generated like this:

```cmake


# Conan automatically generated toolchain file
# DO NOT EDIT MANUALLY, it will be overwritten

# Avoid including toolchain file several times (bad if appending to variables like
#   CMAKE_CXX_FLAGS. See https://github.com/android/ndk/issues/323
include_guard()

message(STATUS "Using Conan toolchain: ${CMAKE_CURRENT_LIST_FILE}")

if(${CMAKE_VERSION} VERSION_LESS "3.15")
    message(FATAL_ERROR "The 'CMakeToolchain' generator only works with CMake >= 3.15")
endif()










message(STATUS "Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)")
set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "Position independent code")


string(APPEND CONAN_CXX_FLAGS " -m64")
string(APPEND CONAN_C_FLAGS " -m64")
string(APPEND CONAN_SHARED_LINKER_FLAGS " -m64")
string(APPEND CONAN_EXE_LINKER_FLAGS " -m64")



message(STATUS "Conan toolchain: C++ Standard 17 with extensions ON")
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Extra c, cxx, linkflags and defines


if(DEFINED CONAN_CXX_FLAGS)
  string(APPEND CMAKE_CXX_FLAGS_INIT " ${CONAN_CXX_FLAGS}")
endif()
if(DEFINED CONAN_C_FLAGS)
  string(APPEND CMAKE_C_FLAGS_INIT " ${CONAN_C_FLAGS}")
endif()
if(DEFINED CONAN_SHARED_LINKER_FLAGS)
  string(APPEND CMAKE_SHARED_LINKER_FLAGS_INIT " ${CONAN_SHARED_LINKER_FLAGS}")
endif()
if(DEFINED CONAN_EXE_LINKER_FLAGS)
  string(APPEND CMAKE_EXE_LINKER_FLAGS_INIT " ${CONAN_EXE_LINKER_FLAGS}")
endif()

get_property( _CMAKE_IN_TRY_COMPILE GLOBAL PROPERTY IN_TRY_COMPILE )
if(_CMAKE_IN_TRY_COMPILE)
    message(STATUS "Running toolchain IN_TRY_COMPILE")
    return()
endif()

set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)

# Definition of CMAKE_MODULE_PATH
# the generators folder (where conan generates files, like this toolchain)
list(PREPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

# Definition of CMAKE_PREFIX_PATH, CMAKE_XXXXX_PATH
# The Conan local "generators" folder, where this toolchain is saved.
list(PREPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_LIST_DIR} )



if (DEFINED ENV{PKG_CONFIG_PATH})
set(ENV{PKG_CONFIG_PATH} "${CMAKE_CURRENT_LIST_DIR}:$ENV{PKG_CONFIG_PATH}")
else()
set(ENV{PKG_CONFIG_PATH} "${CMAKE_CURRENT_LIST_DIR}:")
endif()




message(STATUS "Conan toolchain: Setting BUILD_SHARED_LIBS = OFF")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared libraries")

# Variables
set(CMAKE_EXPORT_COMPILE_COMMANDS "ON" CACHE STRING "Variable CMAKE_EXPORT_COMPILE_COMMANDS conan-toolchain defined")
# Variables  per configuration


# Preprocessor definitions
# Preprocessor definitions per configuration
```

I've been looking through the conan source a bit and to me it looks like `default_include` is only set if `self._conanfile.package_folder` is also set [see](https://github.com/conan-io/conan/blob/release/2.0/conan/tools/cmake/toolchain/blocks.py#L793)

**Comment by memsharded** [comment]
Hi @AxelZi 

Thanks very much for the details, now I understand it a bit better.

The issue is the explicit usage of ``${CMAKE_INSTALL_INCLUDEDIR}`` in ``install(DIRECTORY include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}``:

- When you execute ``conan build .`` this is a local command. There is no ``package_folder``, it doesn't exist, so the ``CMAKE_INSTALL_XXX`` variables cannot be defined.
- The ``install(DIRECTORY `` is not capable of not working if the variable is not defined and it fails
- This haven't hit us before, because we always use the ``install(TARGETS mytarget)`` which is enough to install things, and it manages automatically the packaging of headers, libs, etc

So the approaches to handle this case could be:
- Abstract away the usage ``CMAKE_INSTALL_INCLUDEDIR``, it should be able to work without making it explicit
- Add a conditional in CMakeLists.txt to check if the variable is defined or nor before calling ``install()``
- If you want to inject locally your own variables in the ``generate()`` method in ``CMakeToolchain``, it would be possible to define variable values to point to wherever you want. You can also inject your own xxx_toolchain.cmake file via conf ``tools.cmake.cmaketoolchain:user_toolchain``.

**Comment by Linux13524** [comment]
Hi @memsharded and thanks for your explanations!

So you say the explicit usage of `${CMAKE_INSTALL_INCLUDEDIR}` in `install` is the problem and I see why. I also found the section in the documentation that suggests the usage of `set_target_properties(hello PROPERTIES PUBLIC_HEADER ...)`, but the problem that we have with this is that we would need to specify every single header separately or is it possible to define a whole directory? I couldn't find anything while searching...

So are there any suggestions how to use the CMake install functionality together with Conan and use a directory of headers, or even a wildcard to be installed?

**Comment by memsharded** [comment]
My suggestion would be:

```python
def package(self):
     copy(self, "*.h", ....)
```
Partly kidding 😂 . I know that it is good to reuse the existing CMake functionality. But I sometimes despair how complicated is to do something in CMake, that can be pretty simple in Python.

I think the key is a good definition of what are the target sources and the interfaces, check for example: https://discourse.cmake.org/t/installing-headers-the-modern-way-regurgitated-and-revisited/3238. Note the sarcasm in the first comments, and the despair of the authors because this is not easy at all, then the last one seems to indicate that CMake 3.23 has a better way to do it.

Other possibly pragmatic approach could be something like:
```cmake
install(DIRECTORY "${CMAKE_SOURCE_DIR}/" # source directory
        DESTINATION "include" # target directory
        FILES_MATCHING # install only matched files
        PATTERN "*.h" # select header files
)
```
In which the Destination is ``include``, to don't rely on the ``CMAKE_INSTALL_INCLUDEDIR`` variable.

**Comment by Linux13524** [comment]
```python
def package(self):
     copy(self, "*.h", ....)
```
Well.. That's what we had before :sweat_smile: 

I think we will then just go with the `install(DIRECTORY` with hardcoded include dir.

Thanks for your help!

**Comment by memsharded** [comment]
No prob, glad to help!

Waiting for @AxelZi OP feedback to close the issue then.

**Comment by ghost** [comment]
`include` instead of `CMAKE_INSTALL_INCLUDEDIR` it is then.

Thank you for your time and effort @memsharded.
