### ISSUE TITLE
[question] Version attribute null when using dynamic versioning

### ISSUE THREAD

**Issue by donlk** [conan-io/conan#13690]
### What is your question?

Hi!
I'm unsure if this is a bug or I'm missing something.
When using dynamic versioning by using `set_version(...)` (to retrieve the branch name for example) instead of the version `attribute`and then running `conan inspect .` on the project's root directory (not in the exported directory) version does not show up. If we invoke the command with `-f json` version is clearly shown as `null`.

Is this intended? Shouldn't the conanfile inspection take dynamic versioning generation into account?

For example:
```
def set_version(self):
	git = Git(conanfile=self, folder=self.recipe_folder)
	self.version = git.run("some magic command")
```
Inspect result:
```
    "user": null,
    "version": null,
    "win_bash": null,
    "win_bash_run": null
}
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @donlk 

I think this is expected at the moment, because ``conan inspect`` doesn't evaluate the recipe.
However this has been reported already a couple of times (I am closing this ticket as duplicated), so we will be checking this soon, to see how can it be improved. Please track this ticket: https://github.com/conan-io/conan/issues/13654. Thanks!
