### ISSUE TITLE
Installing packages to local project

### ISSUE THREAD

**Issue by nlbutts** [conan-io/conan#137]
I would like to use Conan as a package manager, but not so much as a build system. For example, in an embedded microcontroller project I would like to run "conan install" and have it install a toolchain, libraries, header files, etc in the local project directory. I don't want the header files hidden in the ~/.conan directory. I also don't want the application conanfile.py to have to have the knowledge of how to copy the files from the package into the local directory. I've tried to use the package_info function to copy the files, but when that function runs within the context of the package, I don't seem to have knowledge of the project directory.

**Comment by memsharded** [comment]
Yes, can be done, it can be used as a package manager, not building at all (e.g. the go-lang example, all builds are always done in the project).

The ``package_info()`` is a method just for gathering information (lib names, compile flags) about the package it references, so it has no knowledge of the project directory, as such project directory might not exist at all ``conan install MyLib/0.1@user/channel`` runs without a project requiring it.

Maybe a greedy ``imports`` could help. Such ``imports`` copies files from ~/.conan directory to the current project, as specified by its patterns. Thus, with two lines you might be able to copy all your dependencies (headers, libs), to your current project. Just add this to your **conanfile.txt** or the equivalent in a conanfile.py:

```
[imports]
include, * -> ./deps/include
lib, * -> ./deps/lib
```

The patterns are "package_folder, file pattern -> destination_folder_in_project"

This assumes that the deps folder exists in your current folder. This approach, as is, might produce some file collisions, if two different libraries contain the same "header.h" file name, in their root folder, and they are not prefixed by "LibA/header.h", and "LibB/header.h". If this happens, it could be avoided with some more elaborated patterns. Of course, if you have control over the packages you depend on cause you are creating them, just using a include/MyLib/headersfiles.h in your packages, which is a good practice anyway, will avoid all problems.

Is this what you are looking for? If you are looking for a way to automatically declare in the packages that they have to copy some date into the consumer user project folder, that cannot be done. It is a design decision, to avoid packages cluttering user projects. This has to be done proactively by the package consumers, if they want to import things into their projects, they have to declare so (just adding those two lines described above).

Please tell me if this approach is good for you or not, so we can try to address that issue.  Thanks for your interest in conan!

**Comment by nlbutts** [comment]
Yes, I think I can make that work. The packages will be packages that we create and maintain. 

Could you explain the concept differences between the build, export, package, and source directories? The steps are unclear if I have a package or toolchain I want to install. For example, I have a toolchain I want to install as part of an application project. First I've 7z the toolchain. Then I run
conan export toolchain/stable

This pushes the 7z, conanfile.py, and creates a few other files. Then in my application project I have a conanfile.py that depends on the depends on that library:
requires = "gcc_arm_none_eabi/4.8.4@toolchain/stable"

When I run:
conan install

I get an error message that:
Requirements
    gcc_arm_none_eabi/4.8.4@toolchain/stable
Packages
    gcc_arm_none_eabi/4.8.4@toolchain/stable:5691b97f2ee756cc202dd1b3481751e7d6357c14
Installing requirements
package_info
linux
Package for gcc_arm_none_eabi/4.8.4@toolchain/stable does not exist
Looking for package in remotes
WARN: Unable to connect to appareo=http://192.168.70.110:9300
WARN: Binary for gcc_arm_none_eabi/4.8.4@toolchain/stable:5691b97f2ee756cc202dd1b3481751e7d6357c14 not in remote: 
ERROR: Can't find a 'gcc_arm_none_eabi/4.8.4@toolchain/stable' package for the specified options and settings. 

- Try to build from sources with "--build gcc_arm_none_eabi" parameter
- If it fails, you could try to contact the package author, report your configuration and try to collaborate to support it.

Package configuration:
- Settings: arch=x86, build_type=Release, compiler=gcc, compiler.version=4.8, os=Linux
- Options: 

What I expected is the package to be pulled down locally. I'm attaching my conanfile.py for the toolchain and my conanfile.py for my app code.

[ztemp.zip](https://github.com/conan-io/conan/files/118351/ztemp.zip)

**Comment by memsharded** [comment]
It goes like this (all are folders in the conan local store):
- The ``export`` directory is where the conanfile.py and possibly other source files as directed by the  ``exports`` attribute in the conanfile are stored when you ``conan export user/channel``. This is the first step to create a package, consider it like the seed or recipe for a package. The idea is that export is from your user folder => conan local store
- The ``source`` folder is a copy of the ``export`` one plus possibly some other files retrieved from the internet while executing the ``source()`` method. It is typical that a conanfile.py implements in such method the retrieval with git clone, or download&unzip of some source code from github, sourceforge....
- The ``build`` directory has different builds inside, one for each configuration, defined by its SHA, so there are builds build/sha1, build/sha2... Each of them is a copy of the ``source`` folder, in which the conanfile ``build()`` method is invoked.
- The ``package`` directory has different packages inside, one for each configuration, duplicating the structure in the ``build`` folder, i.e.: package/sha1, package/sha2... The contents of these package directories is the result of executing the ``package()`` conanfile.py method, which typically extracts headers, libs, and dlls from an inner build folder to this package folder.


About the other issue, the problem is that packages have to be built from the package seed or recipe that you have exported, which will progress from one to one in the above 4 folders. If you don't want to create binaries, because you are always compiling everything from source, it is not a problem: just remove all your ``settings`` from the conanfile.py. Then, just a package will be created from the seed, and that package will be always the used one, irrespective of the settings (you will have your project settings to define how the code is built locally, right?). If you don't have a build() step in your conanfile, you are just moving your sources from the ``export`` to the ``package`` folder. The ``import`` is always execute from package folders to the user project folder.

 Are you doing that, or do you want to actually pre-package binaries? Is your project OSS? If so, put it to github and tell me, so I can have a look to the whole project. Also feel free to contact me by email (james@conan.io) for further questions. Cheers!
