### ISSUE TITLE
[question] Run just compiled executable

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#13710]
### What is your question?

OS: Windows 10 22H2
Python: 3.9.13
Conan: 2.0.4

Profile:
```shell
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

[conf]
tools.build:skip_test=True
```

Hello,

I have a project which compiles several libraries and executables. Some of these executables are actually only needed to compile the rest of the libraries (still within the same project).
On Linux, this works fine. ConanRunEnv & ConanBuildEnv generators create the proper files and the executables run without any issue.
On the other end, on Windows, it looks like the environment does not get overloaded properly. In fact, whether I build using powershell with ```conan build -verror . --options "&:shared=True" --build=missing --conf "tools.env.virtualenv:powershell=True"``` or using cmd with ```conan build -verror . --options "&:shared=True" --build=missing```, I get the same error, which is:
```batch
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB80
66: Custom build for 'C:\Users\RCO\Documents\framework\build\Release\CMakeFiles\d6d64fbee777e0a41b08f2fd644e57c0\generate_headers.ru
le;C:\Users\RCO\Documents\framework\MetaModelMetaValues\CMakeLists.txt' exited with code -1073741515. [C:\Users\RCO\Documents\framew
ork\build\Release\MetaModelMetaValues\generate_headers.vcxproj]
ERROR: conanfile.py (castframework/1.0): Error in build() method, line 121
        cmake.build()
        ConanException: Error 1 while executing
```

From what I understand, the exit code -1073741515 means that the executable (just built) could not load its libraries.

My ```generate()``` and ```build()``` methods are as easy as they can get:
```python
def generate(self):
	ct = CMakeToolchain(self)
	ct.generate()
	cd = CMakeDeps(self)
	cd.generate()

def build(self):
	cmake = CMake(self)
	cmake.configure()
	cmake.build()
```

I also specified a ```config_options()``` method, just to be sure (may not be sufficient):
```python
def config_options(self):
	if self.settings.os == "Windows":
		del self.options.fPIC
```

Am I missing something? Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your report.

If I understood the issue correctly, I think this could clarify a bit:
- Conan generators like ``VirtualBuildEnv`` generate scripts with env-vars for the dependencies information, but they do not manage at all the current package
- It seems that you have a build, lets say it is a CMakeLists.txt that builds some executables and some libraries, inside a package
- In Linux/OSX this might work because the RPATH mechanism, and executables and shared libraries they have encoded the path to shared libraries they linked against. But it is not because Conan generators are doing something with them
- In Windows shared DLLs are only found if they are in the PATH, or located in the same folder as the executable. It seems this is not the case for the project build that you are doing
- Conan does not have enough information about this, at build() time. It only knows a bit about the artifacts once they have been packaged with ``package()``. But this is not the case, the only one that knows about location of shared libs is the build itself, like CMakeLists.txt

So I think that this should be approached by tuning the build (CMakeLists.txt or equivalent) to do some of the following:
- Do a copy  in Windows of the DLLs to the folder where the executables are created
- Customize the OUTPUT dirs, so both executables and dlls goes to the same output folder

Please let me know if this makes sense.

**Comment by Todiq** [comment]
Hello @memsharded 

Thank you for your clarification. I edited this [repo](https://github.com/Todiq/test_conan) to create a reproducible case.
Please, in a cmd, run ```conan create -verror alpha/ --options "&:shared=True" --build=missing -nr```, then ```conan build -verror beta/ --options "&:shared=True" --build=missing -nr```.
Notice that in Linux, this works fine, as LD_LIBRARY_PATH and PATH contain the alpha library location (loaded through generators).
I thought this would work the same way on Windows, since we link with an external library (built with conan), and that the generators files are created the same way.
I am probably mistaken on something. I'll let you enlighten me. Thanks in advance.

**Comment by memsharded** [comment]
A couple of quick notes:

- The first command line, I need to drop the ``-nr``, as I need zlib to be downloaded
- Beware that when using ``--build=missing`` in ``conan create`` will not build the package if a binary already exists for it, it is not only for dependencies, but for the current created package too


Now I see the issue, thanks for your repro code.
The issue is that you are executing the executable directly in the "build()" step. By default, ``cmake.build()`` runs with ``env="conanbuild"``, that is, it only uses the "build environment", that contains the necessary tools to build the code. But you are trying to actually execute the binary inside the build (I'd probably try to avoid this, the build should just build, something that runs the built thing should happen later, like in testing), so it needs the "run environment" too, not only the "build environment".

This could be injected with:
```python
	def build(self):
		cmake = CMake(self)
		cmake.configure()
		with VirtualRunEnv(self).vars().apply():
			cmake.build()
```
There could be other approaches, like doing: ``self.run("cmake ....", env=["conanbuild", "conanrun"])``, but you would need to create the ``cmake`` command line string correctly.
But in any case, I'd probably try to avoid running the built executable in the build stage. If such executable is just something need for the build, I'd explore other mechanisms like ``tool_requires``.

**Comment by Todiq** [comment]
Adding
```python
with VirtualRunEnv(self).vars().apply():
			cmake.build()
```
did fix the issue.
For this conan package (not the repro case), I am unfortunately forced to run my exe within the build stage, since it produces header files, which other sources rely on. I'll explore the possibilities you mentionned. However, for packages that depend on this one, I may be able to run otherwise.
Thank you very much for the trick, I could not have guessed it by myself. I am thus closing the ticket.
