### ISSUE TITLE
[question] Conan 2.0 custom deployer + output folder

### ISSUE THREAD

**Issue by malonsorightware** [conan-io/conan#13728]
### What is your question?

Hi, I am trying to deploy the binaries of a package with Conan 2.0. I created a simple custom deployer (my_deployer.py) that basically copies the binaries directly to the output folder:

```
from conan.tools.files import copy

def deploy(graph, output_folder, **kwargs):
    for name, dep in graph.root.conanfile.dependencies.items():
        source_folder = str(dep.folders.package_folder)
        copy(dep, "*.dll", source_folder, output_folder)

```
According to Conan 2.0 I should be specifiying the custom deployer together AND the output folder as arguments to the install command like:

`conan install --requires my_package/1.0.0@foo/testing  --deploy my_deployer --output-folder <path_to_output_folder> `

The problem is that by specifying --output-folder argument alone the install command will deploy generated files (like conanbuild.bat) in addition to the files my custom deployer copies to the very same output folder. I am trying to reproduce the same behavior deploy() method had in Conan 1.x, that´s it, deploying ONLY the files my custom deployer deploys.  However I did not figure out yet how to that.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @malonsorightware, thanks for your question.
The deployers do not get an independent output folder from the install one. The trick here would be to change your custom deployer to something relative to the `output_folder`. This is also how the built-in ones do it:

```
import os
from conan.tools.files import copy

def deploy(graph, output_folder, **kwargs):
    out = os.path.join(output_folder, "my_dlls")
    for name, dep in graph.root.conanfile.dependencies.items():
        source_folder = str(dep.folders.package_folder)
        copy(dep, "*.dll", source_folder, out)
```

But you're right in that the docs could be a bit more clear as to what's the expected behaviour. For `conan install` it's the base build folder of the conanfile, that is where the build files are generated, and for `conan graph` it's the current working directory

Nevertheless the behaviour you're expecting is something I think that should be discussed with the whole team, as in, maybe having `--deploy-output-folder`, so let me ask them and see what the opinion is :)

**Comment by malonsorightware** [comment]
Thank you very much for the prompt answer. I understood that the trick to isolate the deployed artifacts to a dedicated folder is to bring them to a relative path to the output folder. However the aim of deployment is to serve as installer for plugins to a specific version of a product, and for that to happen the binaries need to live in a path that contains the version for that product. In order to achieve this in Conan 2.0 deployers is to pass the path to the --output-folder parameter. Making deployment relative to the value passed to --output-folder parameter means that we end up either with as many custom deployers as versions of our product there are or we end up with mutiple copies of generated build files.

One workaround would be creating a custom deployer for each version of the product the plugin targets, that´s it, hardcoding the path that contains the version in the deployer,. But it defies the very same purpose of Conan 2.0 deployers. 

In Conan 1.x this was straight as the deploy() method had direct access to the product version. I understand the purpose of Conan 2.0 deployers and I see how Conan 1.x could co-exist with the former one for the sake of flexibility, it does not need to be either-or. 

There is a dedicated section of Conan (1.x or 2.0) documentation explaining the use of Conan as means to deploy pre-built binaries and this capability enables us to create purely installer packages that do not require any build. 

Cheers :)

**Comment by AbrilRBS** [comment]
Thanks for the detailed followup. I might not be seeing the whole picture, but from what I understand, is on of your painpoints not being able to access the version of the package being deployed?

If so, I have added a test as to how that's possible in https://github.com/conan-io/conan/pull/13731 which might help in this situation until we decide on the mentioned `--deploy-output-folder`

**Comment by malonsorightware** [comment]
The main painpoint is still the common output folder for both custom deployers and the generated build artifacts. I just added a little bit of context to understand it better, though I might have over-extended myself :)

**Comment by czoido** [comment]
Hi @malonsorightware,
Thanks a lot for the question. I think I'm missing something here and I would like to understand the issue better, because you always can configure the output path in the custom deployer. Could you please provide a practical example that we can reproduce of the structure that you get with Conan and what would be the desired output for the command?
Thanks a lot!

**Comment by memsharded** [comment]
Hi @malonsorightware 

Any comment on this? We don't have fully clear if the main issue was that the folder had some generated .bat/.sh files in it that were "polluting" it or if it was other issue? Because if it is the former, we might add some ``conf`` to avoid the generation of those environment files, and the problem would be solved?. Please let us know.

**Comment by malonsorightware** [comment]
I managed to create a custom deployer that copies files to a path that contains the version of the package. I figured out how to obtain the version through the graph passed as parameter to the deployer and build the destination path with it. 

In a first implementation I tried to use --output-folder parameter as means to pass the deployment path, the issue was that the destination folder ended up with copies of the files I intended to deploy and a plethora of  build related files that I did not need. Output folder is shared by both the build phase and deployers. Now I´ve solved the problem with a workaround but it seems odd to have this kind of unexpected behavior.

Also related to the topic: I see the point of having custom deployers, however I do not understand why deploy() method had to go. Could not coexist?.  Is there any alternative to that, is there a way to deploy artifacts without having deployers previously configured in Conan?.

**Comment by memsharded** [comment]
> and a plethora of build related files that I did not need.

I guess those files should be only those with .bat or .sh environment scripts. These files might be needed to activate environment and locate the executables. These are the files that we might implement a new ``conf`` to avoid being generated, but the thing is that they are needed in the general case, so it is correct to output them to the output folder (and they can contain relative paths to the deployed artifacts). An idea to explore is that a custom deployer that just removes ``.bat`` and ``.sh`` files from the folder would also automatically do the cleanup of the files.

> Also related to the topic: I see the point of having custom deployers, however I do not understand why deploy() method had to go. Could not coexist?. Is there any alternative to that, is there a way to deploy artifacts without having deployers previously configured in Conan?.

Conan 2.0 is trying to provide one way to solve a problem not several. Because providing several ways to achieve the same not only takes extra effort on the team to develop, maintain, document and support, but it also creates confusion on users on what approach would be better for them. 
In this case, we were basically decoupling the problem of deployment from the problem of developing, letting the users to install recipes without being deployed and also deploy them at will. We also learned that most users were basically copy&pasting a very similar ``deploy()`` method to many recipes, that looked like an anti-pattern. As deployers are very easy to install with ``conan config install`` and that is something that basically needs to be done for many other things (remotes, profiles, etc), then having the deployers external to recipes made a lot of sense.

**Comment by malonsorightware** [comment]
Thanks a lot for the responses!

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/13757 implements ``--deployer-folder`` for Conan 2.0.7
