### ISSUE TITLE
Very slow version range resolving

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#1373]
Hi,

we currently encounter problems with version ranges. We use them everywhere, to always get the latest bugfix version. 
When I retrieve a package using version ranges, it takes up to 72 seconds to resolve the range to the correct version of a single! package. Without the version range, it is instantaneous. Yo can image how log it takes to resolve a dependency tree with a depth of 10 and a lot of downstream requirements (over an hour).

I cleaned some packages from the artifactory, wich brought the resolve time down to 20 seconds. however, I am not able to do more cleanup, as we need to keep the other packages.

We use artifactory v 5.1.3. Our conan repository has around 70.000 artifacts (by the time a had 72 seconds it had 114.000 artifacts). for the tests, the computers where on the same switch without a proxy or anything in between and a 10GBit connection.

The package I want to download has ~700 packages in various channels and various users.
The trace of the command `conan install CMakeMacros/[~0.3]@cab/unstable` is here:
[trace1.txt](https://github.com/conan-io/conan/files/1064329/trace1.txt)
The trace of the command `conan install CMakeMacros/0.3.1-build.60@cab/unstable` is here:
[trace2.txt](https://github.com/conan-io/conan/files/1064331/trace2.txt)

Cheers 
Claas

**Comment by memsharded** [comment]
Yes, version ranges require doing a search in the server to get the best matching version. This is the main reason I want to be very careful with the "package revisions" feature request: https://github.com/conan-io/conan/issues/798

Lets have a look.

This is why I was also considering some different approach to the problem, maybe more server-based or link-based, kind of having a version that is a copy or a link to the latest one (let it be package-revision or latest bugfix), to achieve constant time retrieval (avoiding the search).

**Comment by memsharded** [comment]
Hi @claasd 

We are trying to look what is happening with the performance in Artifactory, and how could be improved. This might take some time.

I would like to propose a different approach, that is very closely related to: https://github.com/conan-io/conan/issues/798

The insight into this is that we are using version-ranges for something that aren't really ranges. We don't want any version in a given range, we want to make sure that we are using the "latest" one, and that latest could be changing. So I would like to consider this very simple approach, but I think it could be very effective:

- Not use version-ranges at all, version retrieval will be exact
- Latest version will be a copy of the latest generated version, managed client-side.

Lets say we want to have Pkg/1.0.1, 1.0.2, ... 1.0.N, and we want consumers of "Pkg" to always use the latest one by default, but still be able to explicitly use any of the previous ones
- Create Pkg/1.0.1, locally
- ``conan copy Pkg/1.0.1@user/channel Pkg/1.0.X@user/channel``
- ``conan upload Pkg/1.0.*``  Will upload the 2 copies. Upload and storage is efficient, because Artifactory has checksum-deploy and de-duplication, so in practice only 1 copy is uploaded
- Users can now directly depend on ``Pkg/1.0.X`` which will be a copy of Pkg/1.0.1

Then, you can repeat the process for next Pkg/1.0.2, 1.0.3...

It has the disadvantage that in the dependency graph, the version is reported as "1.0.X" not as "1.0.1". But I think a good advantage (besides the much better performance O(1) w the size of the repo) is that errors can be managed, for example if published a buggy 1.0.X for 1.0.5, you can revert all your users just by making 1.0.X point to 1.0.4 again, leaving 1.0.5 there intact for inspection and debugging. You couldn't do that with version ranges.

I also think that this could be also a valid approach for **package revisions**.

What do you think?

**Comment by claasd** [comment]
Hi,
thanks for the suggestions. First, I have one question:
Does conan `copy Pkg/1.0.1@user/channel Pkg/1.0.X@user/channel` even work? The version 1.0.X would have a conanfile.py with a version number 1.0.1 in it. Furthermore, I would loose the andvantage of knowing against which version I built. (Maybe the switch from 1.0.0 to 1.0.1 broke something)

Second, I would propose a different but similar approach:
I would still have Pkg/1.0.0, 1.0.1 ... and publish them.
I would then have a Pkg/1.0-latest (or 1.0.x) wich has `settings=None` and `requires="MyPkg/1.0.1@user/channel`. I would then update this version on every publish.
It is kind of similar, but I would get the real version in my logfiles.

I have one issue with both: When I build different configurations pf MyPkg2, which requires MyPkg (lets say vc14/vc15, x64/x86, Release/Debug). it might happen that MyPkg2 vc14/x64/Release builds against MyPkg/1.0.0 and vc14/x86/Release builds against MyPkg/1.0.1. Same problem with version ranges though.

**Comment by memsharded** [comment]
Hi!

No, the ``copy`` I suggested is a proposal. We could implement it, shouldn't be difficult.

Yes, what you are telling is true, it is what I pointed out, about depending on "1.0.X" instead of "1.0.3". Maybe it would be possible to access the meta-information, the version declared inside the conanfile which is not modified (the 1.0.X comes from the path/storage). I have to have a look at that idea, if possible, that would be a good solution.

Your "proxy" package is a good idea too. I will think about it too, to check what corner cases it could have.

The problems about depending on different versions, indeed it is not new. It can also happen with version ranges. This is one of the reasons I am slightly more inclined to explicit versioning. I know that if having a lot of packages, it could require some automation, but implicit versions also have their problems, specially in C/C++.

**Comment by memsharded** [comment]
Hi @claasd 

We have been trying the performance, and going up to 40K artifacts with 1k matching results to the search query had produced searches of about 3 seconds. It is true that it is an order of magnitude slower than a direct retrieval of packages, but still a bit distant of those 20seconds. We are going to try to scale the tests to 70K artifacts and see how it goes.

**Comment by claasd** [comment]
Do you use artifactory or conan source server? 
When I went from 114.000 artifacts to 70.000 artifacts performance went from 70 seconds to 20 seconds; therefore it does not seem linear.

Best,
Claas

**Comment by claasd** [comment]
Just wanted to mention, I really like the idea of being able to copy from one version to another. 
Use cases:  CI creates versions `MyPkg/1.8.0-build.42`, `MyPkg/1.8.0-build.43` and so on. With the new feature, I would be able to create a `MyPkg/1.8.0-rc1` from such a version. Or even promote an arbitrary build of a component to a release.
The version number not matching the version number in the conanfile.py is not really an issue. I can set the version in the conanfile programmatically, therefore it can be different from the real version at the current state. (e.g. `version=create_version_from_env()`

**Comment by memsharded** [comment]
Good to know, thanks for the feedback. Actually, we are considering also the possibility that the version and name attributes are not necessary at all, and could be defined from the command line. This would be useful only for packages with source embedded (``exports_sources`` instead of ``source()``), otherwise, the ``source()`` method will not have the required information to run the adequate retrieval of source code.

**Comment by memsharded** [comment]
Hi @claasd 
Regarding your latest ideas, I have come up with a proposal in https://github.com/conan-io/conan/issues/798#issuecomment-312925329 that might be interesting, it has the advantages of the proxy without the disadvantages. Feedback welcome :)

**Comment by claasd** [comment]
Hi, I rolled out the alias command for all of our packages. Resolving now is pretty fast.

**Comment by memsharded** [comment]
Excellent! Glad that the feature has been useful, thanks for the update
This doesn't mean that we won't keep working on speeding up the search in Artifactory for large repos, just it is something that will take more time.
