### ISSUE TITLE
[question] How to override recipe?

### ISSUE THREAD

**Issue by wrightleft** [conan-io/conan#13743]
### What is your question?

I need to modify a library with some specific requirements for my use-case. I would like to apply a patch to the source code and to add some options to the recipe.

I have tried to figure out how to do this for several hours now. I have found some information online about "overriding recipes". Like [the second option in this previous question](https://github.com/conan-io/conan/issues/9418#issuecomment-898290380). Or [the third option in this response](https://www.reddit.com/r/cpp_questions/comments/tqkabx/comment/i2j9xuk/?utm_source=reddit&utm_medium=web2x&context=3).

They all make it sound so easy. Just "make a local copy of the recipe". Just "magically override the recipe". But I can't even figure out how to get the recipe. I tried `conan copy`, but it doesn't exist. (So many of the ideas online don't seem to work with conan 2.x). I tried `conan download`, but that seems to squirrel the files away in some cache. And how to override a recipe? I see stuff about `@user/stable`, but I can't figure how to get that work.

When I finally find the files in the cache (`~/.conan2`), in a couple different directories (patches weren't next to the recipe, conandata.yml, etc. files), copy them all to one directly, and run `conan create` in the directory, it builds the library, but nothing seems to really change. `conan search` only shows the one library from `conancenter`.

I was expecting some `user/stable` version of the library that I could pass to `self.requires`.

What am I missing?

I would love for a way to download all of the recipe files into a directory, make changes, add patches, and add that directory as a requirement (i.e., `self.requires("conan/foo_library")`). Is it possible to get close to that?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @wrightleft 

Thanks for your question.

First, nothing is that easy ever, specially in C++ and building C++ 😅 Sometimes it is easy to forget when we explain things that we already know to others.

Let me try to clarify a bit. If you want to do modifications to a recipe, that is source code, and then the recommended "copy" would be often a fork of the git repo, for example if we are talking about ConanCenter recipes. If you need to do modifications (even if you don't, but you want to have full control over your binaries, as many of our users do), the "production-level" process would be:
- Fork ``conan-center-index`` repository
- For the recipe you want, do the necessary modifications in your fork
- Do the ``conan create . --version=xxx`` (conan 2.0 syntax) in the folder of the recipe you want to create
- Repeat for the different configurations you want to build
- ``conan upload`` to your private server (like the free ArtifactoryCE)
- Put your own server the first one, or even remove the ``conancenter`` remote from your client (recall that you can use ``conan config install`` to manage configuration, including remotes definitions)
- When you want, pull the upstream new changes, and recreate and re-upload the package, to stay in sync with the upstream ``conan-center-index``
- The recommended approach is to keep the packages without user/channel, same as ConanCenter. That will minimize conflicts and other possible inconveniences that might require extra effort. As you are pulling

These are the basics, but depending on the needs this might have some variants:
- If you need to do that for different recipes and version, the typical approach is to have a ``mypkgs.list`` in the repo, and a small script that iterates it, creating the necessary binaries. I have a small poc in: https://github.com/memsharded/conan-center-index/tree/mycustom, check ``mybuild.py``. Conan knows when it doesn't need to re-build binaries because they already exist, so that simple script is actually efficient.
- For being extra robust in production, when upgrading the repo and starting to build for different configuration, including different platforms (Linux, Win, Android...), do not upload the binaries directly to the "production" server repo. Instead, create a secondary "build" server repo, and you upload there from the different build agents when they build. Only when all of them are green and everything is working, you do a copy from server repo to the "production" server repo. This way it can be ensured that no broken packages affect production builds. This is a common recommended devops practice, not only for Conan.

Please let me know if this clarifies a bit, and if you have any further question.

PS: We have in the roadmap some potential features that might streamline the above, but in any case the above is quite doable, and it is being already done by many enterprise Conan users

**Comment by wrightleft** [comment]
I appreciate the detailed answer. Thanks.

It sounds to me like "just override a recipe" entails creating a new remote. I'll have to talk to our IS/IT guys to see if this is something they are interested in.

**Comment by memsharded** [comment]
Creating a remote/server to host packages is an extremely recommended practice anyway for production, not only for Conan/C++, but mostly for every other package management technology out there. We don't recommend ourselves to depend on ConanCenter in production for any serious Conan usage, but on a copy of the packages, even if you don't build it yourselves, storing a copy of the dependencies in your own server is a very good security measurement and great for reproducibility and robustness.

Thanks for the feedback!

**Comment by W4RH4WK** [comment]
@memsharded I just discovered your answer now after spending quite some time looking through the docs and StackOverflow.

It appears to me as if this use-case is pretty essential for anyone looking to adopt Conan for non-trivial projects. [Packages in editable mode](https://docs.conan.io/2/tutorial/developing_packages/editable_packages.html) is the closest to this in the current documentation from what I've found.

I think there should be a tutorial that starts you off with a project that uses a single dependency from Conan Center and walks you through:

1. Getting the source of the dependency (+ existing patches).
2. Building and using the dependency (without modifications) with the project.
3. Modifying and rebuilding the dependency along with your project to iteratively develop a fix.
4. Extracting the modifications as one or multiple patches.
5. Forking the dependency such that the additional patches are included.
6. Using the fork instead of the original dependency in your project.
   Not just locally, but for your whole team.
7. Updating the fork, maintaining the added patches, when upstream releases a new version which still contains the bug.
8. Retiring the fork once upstream has fixed the bug.
   (Note that this step should not break old builds.)

If this workflow requires setting up any server component, the tutorial must point to the corresponding installation manual.

What do you think?

**Comment by memsharded** [comment]
This is the intent of the new docs section in https://docs.conan.io/2/devops/using_conancenter.html, and subsection https://docs.conan.io/2/devops/conancenter/hosting_binaries.html

There are still some challenges that makes this not only a documentation effort. For example, most recipes in ConanCenter (``conan-center-index`` github repo) are not really prepared to be editable. Correct ``layout()`` methods are necessary for this, but most recipes in ConanCenter do not implement it. They rely on local development of the package in isolation (with ``test_package``) and CI. So documentation explaining to put such recipes in editable will be problematic. And also it is not expected that the community nor us will implement those ``layout()`` for the whole ConanCenter, that would be a huge effort with relatively small value (most users do not need to put it in editable mode to modify and do edits to the recipes)

That would be the challenge for points 3-4. The rest of the points are mostly what is described in https://docs.conan.io/2/devops/conancenter/hosting_binaries.html, and that guide is planned to get new additions, explanations and even new tools to improve the usage.

**Comment by wrightleft** [comment]
My biggest hurdle so far has been finding up-to-date documentation. Everything seems to be conan v1. Even the proof-of-concept repository provided above (https://github.com/memsharded/conan-center-index/tree/mycustom) has commands that don't work for conan v2.

C++ packaging is hard.

I'm just starting on step 6 today. I finally got a local conan index created with the modified recipe (with a patch). Now, I just have to use it. I'm afraid I'm going to get bitten by not using `--user` and `--channel` when creating my local conan index, but I don't know. It's hard to understand.

With how hard things have been, I'll never get to steps 7 & 8 just because I don't want to break anything.

This "hardness" also has a side effect of causing imposter syndrom. I would like to push my changes upstream to the actual conan center index. I created 5 new recipes for opensaml, xmltooling, xml-security-c, etc, but I have no confidence that they are any good because everything was so hard.

**Comment by memsharded** [comment]
Totally understandable.

We are aware that there are challenges there, and this is why we are planning to improve things and even add new tools to help in the process. Also because it also happens that packaging some of the third party libraries out there is incredibly challenging, because building them is challenging in the first place, and that can cause a lot of frustration. Packaging your own libraries is typically way easier than packaging some third parties.

> I'm just starting on step 6 today. I finally got a local conan index created with the modified recipe (with a patch). Now, I just have to use it. I'm afraid I'm going to get bitten by not using --user and --channel when creating my local conan index, but I don't know. It's hard to understand.

This one, we tried to explicitly document it in https://docs.conan.io/2/devops/conancenter/hosting_binaries.html#devops-conancenter-hosting-your-own-conancenter-fork

> Do not add user/channel to these packages, it is way simpler to use them as zlib/1.2.13 without user-channel. The user/channel part would be mostly recommended for your own proprietary packages, but not for open source ConanCenter packages.

So our current plans are something like:

- Adding new tools, commands, scripts, etc. that helps to automate to work on your fork of ``conan-center-index``.
- Improving the CI of ``conan-center-index`` (this is a long term effort, much to do here), so it is faster and more informative, and helps us also to streamline the review process.
- Improving and completing the docs. This is an ongoing effort, the "Devops guide" itself is very new, and we keep working on the docs when possible.

**Comment by W4RH4WK** [comment]
> most recipes in ConanCenter [...] are not really prepared to be editable. Correct layout() methods are necessary for this

I've been thinking about this, and it's unclear to me why this is the case. All recipes in ConanCenter define the required build steps. Even if they don't have a `layout()`, they can still be built. Why is `layout()` necessary? I am not trying to interface with the dependency in any special way. All I need Conan to do is:

- Download and extract the sources.
- Stop there, letting me edit the sources.
- Continue with the build process as usual.
- Letting me invoke the build process again, after having made additional changes to the source.

**Comment by garyo** [comment]
I have maybe a simpler issue, on the same topic. I know there's a PR waiting for inclusion in conancenter (it's https://github.com/conan-io/conan-center-index/pull/22953). If I wait long enough, someone will review it and I can just pull it via `conan install --update spdlog .` and then use the new options. 
But if I want to use it today (in development), is there any way for me to just copy that recipe from the PR somewhere and make my local conan use it instead of the one on conancenter? Or point my conanfile.py to that PR's URL?

**Comment by memsharded** [comment]
> I've been thinking about this, and it's unclear to me why this is the case. All recipes in ConanCenter define the required build steps. Even if they don't have a layout(), they can still be built. Why is layout() necessary? I am not trying to interface with the dependency in any special way. All I need Conan to do is:

Being able to be built and being able to package is not the same as knowing where the artifacts are in the source and build tree. That detail is only known by the build system scripts, Conan cannot know where the necessary artifacts are. This is the reason why a ``layout()`` is necessary, via the ``self.cpp.source`` and ``self.cpp.build`` will define where the artifacts are, so consumer can use them.

If you need only that from Conan, then you don't need ``editable`` at all in the first place. If you want to have any arbitrary consumer, with any arbitrary build system use a "build-tree", not a package, from another folder in user space (not a package in the Conan cache), then yes, Conan needs a definition of where things are.

**Comment by memsharded** [comment]
As a side note, commenting in a closed issue might often pass unnoticed by the maintainers, the notifications are just too many, and closed tickets are less visible.

**Comment by memsharded** [comment]
> I have maybe a simpler issue, on the same topic. I know there's a PR waiting for inclusion in conancenter (it's https://github.com/conan-io/conan-center-index/pull/22953). If I wait long enough, someone will review it and I can just pull it via conan install --update spdlog . and then use the new options.

In general, for production usage it is often recommended to create your own binaries yourself, see https://docs.conan.io/2/devops/using_conancenter.html, specially in those case that you might want to be able to use changes that are not merged in ConanCenter (or can't ever be merged, for some reasons, those changes only apply to your usage).
