### ISSUE TITLE
[bug] invalid dependency of libpcap with clang under windows os

### ISSUE THREAD

**Issue by Saigut** [conan-io/conan#13754]
### Environment details

* Operating System+version:
  Windows 10
* Compiler+version:
  Clang 15.0.1
* Conan version:
  1.56.0
* Python version:
  3.9.4

### Steps to reproduce

conanfile.txt:
```
[requires]
libpcap/1.10.1

[generators]
cmake
CMakeDeps
```

command line:
```
conan.exe install /path/to/conanfile.txt -scompiler=clang -scompiler.version=15 -sbuild_type=Debug --build=missing
```

Then, the flex is wrong be depended: **`flex/2.6.4: Invalid ID: Flex package is not compatible with Windows. Consider using winflexbison instead.`**

### Logs

```
conan.exe install /path/to/conanfile.txt -scompiler=clang -scompiler.version=15 -sbuild_type=Debug --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    libpcap/1.10.1 from 'conancenter' - Cache
Packages
    libpcap/1.10.1:01822c8126f3805e61534fa72215516497c36eb2 - Build
Build requirements
    bison/3.8.2 from 'conancenter' - Cache
    flex/2.6.4 from 'conancenter' - Cache
    m4/1.4.19 from 'conancenter' - Cache
    msys2/cci.latest from 'conancenter' - Cache
Build requirements packages
    bison/3.8.2:7ee56fe57d3791708fcafe4891c9ff546bcad342 - Build
    flex/2.6.4:INVALID - Invalid
    m4/1.4.19:01edd76db8e16db9b38c3cca44ec466a9444c388 - Download
    msys2/cci.latest:eee3fba89db6d777329de604625af8c30d46f080 - Download

Installing (downloading, building) binaries...
ERROR: There are invalid packages (packages that cannot exist for this configuration):
flex/2.6.4: Invalid ID: Flex package is not compatible with Windows. Consider using winflexbison instead.

```

**Comment by memsharded** [comment]
Hi @Saigut 

Thanks for your report.
Some preliminary feedback:

```
[generators]
cmake
CMakeDeps
```
It is not possible to mix legacy generators like ``cmake`` with new ones like ``CMakeDeps``. Please use the ``CMakeToolchain`` generator instead of the ``cmake`` one.


Regarding your issue, this is failing because you are still using the legacy 1 profile approach, and these recipes require already the 2 profiles (using the 2 profiles is always by default in Conan 2.0 already, and it is very recommended in 1.X for any scenario that uses ``tool_requires``, which is the case here).
So please add something like ``-pr:b=default``, like:
```bash
$ conan install . -s compiler=clang -s compiler.version=15 --build=missing -pr:b=default
```
And it will no longer show that error.
In my case I managed to pass that error, and failed later because I didn't provide a CMAKE_MAKE_PROGRAM (mingw, to process makefiles). Note that some of the recipes in ConanCenter might not be fully ready to build with ``clang`` compiler on Windows. Even if Conan tries to support it, some build scripts might have hardcoded assumptions, and Windows+clang is not required in ConanCenter, so not tested there.

**Comment by Saigut** [comment]
@memsharded  Hello, my case is `Native building`, so when I use 2 profiles, I use two same profiles like `-pr:h=win_clang -pr:b=win_clang`. And then I met the same dependency problem: the wrongly dependency to `flex`.

And for generators, `cmake` works well for me now.

**Comment by SpaceIm** [comment]
It was a recipe issue, fixed in https://github.com/conan-io/conan-center-index/pull/17187
