### ISSUE TITLE
[question] editable packages and self.folders.root 

### ISSUE THREAD

**Issue by asafor** [conan-io/conan#13766]
### What is your question?

Hi, 
I am using editable packages with conan 1.59. In my layout() I am setting self.folders.root (as my recipe is located in a sub folder and not in the root) and it seems to work fine for then defining my include, bin and lib dirs. But when my consumer package is built in this editable package I can see that [rootpath_package] (as it appears in conanbuildinfo.txt) is still set to my package folder containing the conan.py recipe and not the folder I have defined as root with self.folders.root. 
Is that a bug or the desired behavior? 
Is there any other way that I can set the [rootpath_package] to be the real root of my package as I set it and not the recipe folder?

Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @asafor 

Thanks for your question.

The ``layout()`` feature and ``self.folders.root`` is a "modern" feature that works in tandem with the "modern" build system integrations and generators.

All the legacy generators, including the ``txt`` one (the one that generates by default the ``conanbuildinfo.txt``) do not know about the layout, and they will not follow it. In general it shouldn't be a problem, because these generators shouldn't be used anymore, and the auto generated `conanbuildinfo.txt`` can be disregarded or removed.

It is important for the ``layout()`` and modern recipes to also separate correctly the responsibilities, with ``generate()`` managing the creation of necessary files for the build, and the ``build()`` just executing the build, but not really managing information from dependencies.

Please let us know if this helps.

**Comment by asafor** [comment]
Hi,

Thank you for the fast and detailed reply.
I am trying to introduce the usage of editable packages to a legacy project with a complex build system.
I was hoping to do that with minimal changes to current code and layout() almost did the trick. But this issue seems like an obstacle. I could trick it by exporting the recipe itself to the layout root and use it as the reference for the editable package although it was not created from there, but that would not be an elegant solution.

**Comment by memsharded** [comment]
Thanks for the feedback.
No, it doesn't seem possible to keep the legacy generators with the modern ``layout()``, we considered it, but it was challenging to do that without breaking existing usage of the legacy generators, and the risk was simply too high, so it was implemented together with the new integrations.

In any case, please recall that Conan 2.0 is there, the community is moving fast (for example updating recipes in ConanCenter), so it is necessary to do some planning on legacy projects, if they are going to be updated or not, and if not, considering the necessary backup mechanism if using ConanCenter directly, because at some point it will drop Conan 1.X support (not soon, will take some time, but will happen).

**Comment by asafor** [comment]
Thanks. We will take that into account.
