### ISSUE TITLE
[feature] Expose self.dependencies from build() and more places

### ISSUE THREAD

**Issue by tmatheson-arm** [conan-io/conan#13768]
### What is your suggestion?

For various reasons involving version ranges, we use `build_requires` and `tool_requires` rather than `requires` for our recipes. We also run the `conan install` before `conan source` because the source required may depend on the options and settings. However, we want to keep track of both the package dependencies and the source used to build the package. To do this we construct a file `origins.json`. 

We used to generate `origins.json` in the `build()` step, using `self.deps_cpp_info` to fetch the `build_requires` dependency info (regardless of host or build context), and the source information is also available at this stage.

However, since switching to separate build+host profiles, there is no nice way to do this. The `tool_requires` dependencies do not show up in `self.deps_cpp_info`, so we need to use `self.dependencies`. However this is only available from the `generate()` method, which means we need to split the creation of `origin.json` into two parts: first part in `generate()` which will store the dependency information, and then update it in `build()` once we have the source information.

As you can imagine this is pretty awkward. It would be good to make `self.dependencies` with the entire set of dependency information available in the `build()` method (and perhaps anywhere else where it is technically possible, unless there is a good reason to restrict it).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tmatheson-arm 

Thanks for your suggestion.

I think you are referring to Conan 1.X, and also while running the ``conan build`` command, not the ``conan create`` command. The problem is that in Conan 1.X, ``conan build`` doesn't really build the graph, but a partial representation from some serialized state created in previous ``conan install``, but that is not enough to reconstruct the ``self.dependencies``. This cannot be changed in 1.X scope, as it would require a huge effort, and it will also be very breaking, so not possible.

Conan 2.0 has already solved this, and ``self.dependencies`` is available in the ``build()`` method (for both ``conan build`` command and ``conan create``)

In any case your comment:
> However this is only available from the generate() method, which means we need to split the creation of origin.json into two parts: first part in generate() which will store the dependency information, and then update it in build() once we have the source information.

Doesn't sound that bad. The ``generate()`` purpose is precisely to manage dependencies information and to prepare the build, so collecting information from dependencies there, serializing it to a json file, and then completing that json with the build information in the ``build()`` method, sounds very reasonable to me.

**Comment by tmatheson-arm** [comment]
> Conan 2.0 has already solved this, and self.dependencies is available in the build() method

That's great, I'll look into upgrading then. Thanks for the explanation.
