### ISSUE TITLE
[question] How to use tool_requires in source() method?

### ISSUE THREAD

**Issue by woidpointer** [conan-io/conan#13782]
### What is your question?

Hi, 
is it somehow possible to use tool_requires in the `source()` method. In my use case I need a tool (here gradle) to get the source code. But it seems using the tool in the `source()` method failes because the virtualenv is not setup in the  `self.run()` call. When I put the call to the tool to the `build()` method, the call is successful so I would exclude a recipe error. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @woidpointer,

Thanks a lot for the question. Accessing tool_requires in the `source()` method is not possible, as you say you could get the sources in the `build()` method. If you could provide us with more details about your specific use case, we would be better equipped to offer assistance.

**Comment by memsharded** [comment]
Hi @woidpointer 

I think it should be possible. I am doing this test and seems to work:
```python

def test_complete_source(client):
    conanfile = textwrap.dedent("""
        import os, platform
        from conan import ConanFile

        class Pkg(ConanFile):
            settings = "os"
            tool_requires = "mycmake/1.0"

            def source(self):
                mybuild_cmd = "mycmake.bat" if platform.system() == "Windows" else "mycmake.sh"
                self.run(mybuild_cmd)
       """)

    client.save({"conanfile.py": conanfile})
    client.run("install . --build=missing")
    client.run("source .")
    msg = {"Darwin": "Macos"}.get(platform.system(), platform.system())
    assert f"MYCMAKE={msg}!!" in client.out
    assert f"MYOPENSSL={msg}!!" in client.out
``` 
(Conan 2.0). 
I will submit a PR for it, to make sure it is covered

**Comment by memsharded** [comment]
Uhmm, it seems there could be something... It works locally, with ``install + source``, but it fails at ``create``. I will check it

**Comment by memsharded** [comment]
Ok, @czoido was completely right, this is the rationale:

- ``tool_requires`` are dependencies that are evaluated per-configuration, one configuration (e.g. Release, might have a specific ``tool_requires()`` that the Debug configuration doesn't need)
- The generated files, including the environment files like ``conanbuild.bat|.sh`` are generated per-configuration in the "build" folder, specific for a particular build configuration
- But the ``source()`` method executes configuration-independent because it should be exactly the same source code for all different configuration, this is documented.
- So the ``source()`` stage in the cache doesn't have access to ``tool_requires`` defined environments, because they are specific for given configurations.
- In Conan 2.0 it is even possible to retrieve the sources without building from source or without requiring the ``tool_requires`` there is a new ``conf`` that allows to do that even with the ``conan graph info`` command. If that command doesn't try to fetch at all the binaries for any package in the graph, it becomes more evident why ``source()`` cannot rely on things defined in ``tool_requires``.

That fact that it worked in the above test was just a lucky coincidence, because I was doing a dirty recipe without ``layout()`` that was dumping everything just to the root folder, and then source accidentally accessed it, but in reality recipes would have layout and would fail, adding a simple one like this, will make the test fail:
```python
 def layout(self):
                self.folders.build = "build"
                self.folders.generators = "build/generators"
```

**Comment by memsharded** [comment]
What is the tool that you want to run in ``source()`` that will be defined in a ``tool_require()`` @woidpointer ?

**Comment by woidpointer** [comment]
@memsharded @czoido Thank you for your responds. I have to use a proprietary source deployment solution, i.e. no git, svn, no zip or something like that. I have call a gradle task and there I created a gradle package which shall be called in `source()` instead for git.

**Comment by memsharded** [comment]
I guess that if you have gradle itself as a ``tool_require``, then yes, the solution would be to call it directly in the ``build()`` method, not in the ``source()`` one. Definitely the ``source()`` method is not designed to support this use case, but for doing plain ``git`` or ``download`` commands no more. It shouldn't be a big issue, at the end of the day the ``source()`` method is nothing but an optimization to fetch the sources only once, but fetching the sources is not that expensive compared to building them, so it should be reasonable to download the sources in ``build()`` for this case.

**Comment by woidpointer** [comment]
@memsharded @czoido Thank you for your support. I will go the download in `build()` way.
