### ISSUE TITLE
[question] Conan prepare new Package_ID without corresponding package

### ISSUE THREAD

**Issue by Wizradus** [conan-io/conan#13785]
### What is your question?

Hi there. I have sometimes observed some weird behavior with our Conan...
I will try describe this as much as I best can and someone may be familiar or maybe it is an error, because I have no much details currently.
Conan: 1.51.2
Python: 3.8.0
Artifactory: Conan edition 7.49.3

Configuration:
arch: x86
build_type: Debug
compiler: Visual Studio
compiler.version: 9
os: Windows

During some build we have seen message for required package (let it be ourlibA and ourlibB) that is missing.
ERROR: Missing binary: ourlibA/trunk@test/dev:b5079243edc8db2a161b1735e11e657e499a8f45
ERROR: Missing binary: ourlibB/trunk@test/dev:b5079243edc8db2a161b1735e11e657e499a8f45

When I have take a look to Artifactory via `conan search ourlibA/trunk@test/dev` I saw only:
    Package_ID: 6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
        [settings]
            arch: x86
            build_type: Debug
            compiler: Visual Studio
            compiler.runtime: MDd
            compiler.version: 9
            os: Windows
        Outdated from recipe: True

And for `conan search ourlibB/trunk@test/dev` I saw:
    Package_ID: 6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
        [settings]
            arch: x86
            build_type: Release
            compiler: Visual Studio
            compiler.runtime: MD
            compiler.version: 9
            os: Windows
        Outdated from recipe: False
When I have rebuilt mentioned modules ourlibA and outlibB problem has been solved.
But... there wasn't created new Package_ID - new built packages got just number, what was missing.

So here are some questions:

- Is it truly possible that 2 packages can get same ID?
- How is possible that is requested as dependency package any with ID, which does not exist, while there another valid?
- Is it OK if is used for building only outdated package and valid (outdated=false) is missing?
- Thing, which is most weird for me, is question, how much is possible, when will be package suddenly deleted from Artifactory, then new one will get same ID?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Wizradus 

Thanks for your questions

> Is it truly possible that 2 packages can get same ID?

Yes, the ``package_id`` is the hash of settings + options + dependencies versions. If the settings are the same, and they don't have options or have the same options and they have no dependencies (or have the exact same depenencies), then the package_id can be exactly the same.

> How is possible that is requested as dependency package any with ID, which does not exist, while there another valid?

The package_id resolution is taking your inputs, like the profile settings, options, etc, and computing the ``package_id`` that results from them. If that ``package_id`` exists, then it is returned, and if it doesn't exist it is a "missing binary". There is not internal smart behavior that would try to resolve to an "approximately equal" binary package, because that "approximately equal" is not something that can be generalized, and every user has a different concept for it. So there are some more advanced techniques, like using ``package_id()`` method to change the hash computation, using ``compatible_packages`` feature or in Conan 2.0 there is a new global ``compatibility.py`` plugin to define your custom binary compatibility rules.


> Is it OK if is used for building only outdated package and valid (outdated=false) is missing?

The ``outdated=True`` only happens when NOT using revisions. Revisions is a very recommended feature that has been there for years in 1.X, that is mandatory and always active in Conan 2.0. You can activate it in Conan 1.X setting ``conan config set general.revisions_enabled=True``. Using a binary that is outdated is very undefined, anything could happen, depending on the changes that you did to the recipe that caused the binary to be outdated.

> Thing, which is most weird for me, is question, how much is possible, when will be package suddenly deleted from Artifactory, then new one will get same ID?

Packages should not be suddenly deleted from Artifactory, they are only removed by explicit ``conan remove`` commands, or using the Artifactory UI or API. It is possible that not using revisions, you will be overwriting previously existing packages if not bumping versions, when not activating the revisions.


I hope this clarifies a bit the issue.

Finally, I'd like to recommend having a look to https://docs.conan.io/1/conan_v2.html. Conan 2.0 has already been released, dependencies in ConanCenter are being updated to support 2.0, and at some point they will drop Conan 1.X support. Not immediately, but better putting the upgrade to 2.0 in the planning.

**Comment by Wizradus** [comment]
Hi, @memsharded. 
Thanks for quick and valued response.
Currently I understood a bit what happened. Due some change in building environment Conan computed Package_ID and request from Artifactory, but it was never built yet and created, so we got error about missing binary package.
I expect that this issue could be solved by `conan install --build`, right?

I have another question regarding "outdated packages"... We temporary are doing some cleanings from Artifactory for these packages. Is it good idea? Shall we rather keep them as are?

My last (I hope) doubt is related again to generate Package_ID. When we don't use Options and Settings are on build server unchanged, so only possibility are dependencies versions as you wrote. Can you a little clarify this?
It's mean when I add/remove dependency from conan recipe or will change dependency file?

Thanks in advance and all the best for you.

**Comment by memsharded** [comment]
Thanks for your feedback.

> conan install --build

This will build from sources all packages, in general ``--build=missing`` would be the recommended approach.
But this has some disadvantages, that all developers and CI jobs missing the binary, would be building it from source again and again. So the best way to address this is to consider this as a CI job, fix the missing binary in CI for the offending package pipeline, not in the consumers.

In general to avoid this situation, what you want to do is to upload the created binaries to a secondary repo (like "build" server repo) and only when the full CI, all variants have built correctly, then you do a copy of the packages from the "build" artifactory repo to the production or "develop" repo used by devs and other CI.

> I have another question regarding "outdated packages"... We temporary are doing some cleanings from Artifactory for these packages. Is it good idea? Shall we rather keep them as are?

It depends on your needs, it is fine to remove it, and you can build from source again when necessary.

> My last (I hope) doubt is related again to generate Package_ID. When we don't use Options and Settings are on build server unchanged, so only possibility are dependencies versions as you wrote. Can you a little clarify this?
It's mean when I add/remove dependency from conan recipe or will change dependency file?

What do you mean that "settings are on build server unchanged"?
You might be checking this talk for example: https://youtu.be/kKGglzm5ous it will contain some information about the package_ids, it is an advanced talk focused on Conan 2.0, but might be useful

In general it means that yes, when the dependencies change, even if you don't change your ``conanfile.py`` recipe, for example if you have a version range like ``requires = "mypkg/[>1.0 <2.0]"``, and you were depending on ``mypkg/1.1`` latest version, if ``mypkg/1.2`` gets released, and you rebuild the consumer it will start building against ``mypkg/1.2`` and it will get a new ``package_id`` for the new dependency, and you will have 2 different package_ids for your consumer package, one built for ``mypkg/1.1`` and other built for ``mypkg/1.2``. (The behavior is different in 1.X and 2.0, and it can also be customized and depend on user configuration too)

**Comment by Wizradus** [comment]
> What do you mean that "settings are on build server unchanged"?

We have only one configuration per server e.g. arch=x86, build_type=Debug, compiler,version=9 so is basically impossible to get change from settings.

But anyway thank you for your response and time.

Wiz

**Comment by memsharded** [comment]
> We have only one configuration per server e.g. arch=x86, build_type=Debug, compiler,version=9 so is basically impossible to get change from settings.

Thanks for the clarification.

I think this issue can be closed then as responded and solved? Any further issue or question? Thanks!

**Comment by Wizradus** [comment]
Sure. Closing it.
