### ISSUE TITLE
[question] Conan create command fails to find dependency

### ISSUE THREAD

**Issue by darcamo** [conan-io/conan#13797]
### What is your question?

Consider a recipe generated with the `conan new` command that has at least one dependency. For instance, the result of running the command below
```bash
conan new cmake_lib -d name=mylib -d version=1.0 -d requires="hdf5/1.14.0"
```

This creates a recipe with the correct `requirements` method that adds hdf5 as a dependency and a CMakeLists.txt file containing `find_package(hdf5 CONFIG REQUIRED)`. However, trying to install `mylib` to the cache with
```bash
conan create . --build=missing
```
fails during the `configure` step with the error
```
CMake Error at CMakeLists.txt:4 (find_package):
  Could not find a package configuration file provided by "hdf5" with any of
  the following names:

    hdf5Config.cmake
    hdf5-config.cmake

  Add the installation prefix of "hdf5" to CMAKE_PREFIX_PATH or set
  "hdf5_DIR" to a directory containing one of the above files.  If "hdf5"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Doesn't Conan set the necessary path to allow CMake to find the dependencies? I'm probably missing something here.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @darcamo 

Thanks for your question.

I think this is because the cmake file generated by Conan is called ``HDF5Config.cmake`` with upper case. Conan recipes do this, customize the name to match the original project ones, so they match their documentation, etc. That means that in case-sensitive systems you might need to do
```cmake
find_package(HDF5 ...)
```

This will happen for some packages in ConanCenter, you need to check both the file name and the generated targets names, they won't always match exactly the package name.

**Comment by darcamo** [comment]
That was indeed the problem. Thank you for the help.
