### ISSUE TITLE
[question] how to batch build specific project for a visual studio solution with MSBuild

### ISSUE THREAD

**Issue by himankpathak** [conan-io/conan#13803]
### Description

I wanted to know how to batch-build specific project configurations with [MSBuild](https://docs.conan.io/2/reference/tools/microsoft/msbuild.html)

<img width="493" alt="image" src="https://user-images.githubusercontent.com/26011845/235822880-59b22c01-ba1d-4db0-8c44-781ba29ff820.png">

My build function currently looks like this:
```
def build(self):
        self.run("cmake -G \"Visual Studio 17 2022\" -A x64 -S ../aburn/eng/src/aftr -B ../aburn/eng/cwin64")

        msbuild = MSBuild(self)
        msbuild.build_type = "Debug"
        msbuild.platform = "x64"
        msbuild.build("./aburn/eng/cwin64/MyProject.sln")
```

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by franramirez688** [comment]
Hi @himankpathak 

Thanks for reporting the issue.

In summary, as I've read about that batch-build with Visual Studio, this is not going to be possible because Conan recipes work in single-configuration mode, so talking about multi-configuration for one recipe does not make sense at all.

Checking your code above, let me propose some best practices to enhance your Conan recipe:

* Don't run CMake via CLI. Use the [CMake build helper](https://docs.conan.io/2/reference/tools/cmake/cmake.html) to do that instead.
* `MSBuild` is supposed to be used by native VS projects, not for CMake ones. More info [here](https://docs.conan.io/2/reference/tools/microsoft/msbuild.html).
* Use the Conan profiles, or even the CLI, to put global settings, options, build type, etc. Check the [Profiles section](https://docs.conan.io/2/reference/config_files/profiles.html).

Here are more links to learn how Conan works:

* [Buidl a simple CMake project](https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html).
* [Visual Studio integration](https://docs.conan.io/2/integrations/visual_studio.html).

I hope it helps!

**Comment by himankpathak** [comment]
Thank you so much for the tips @franramirez688. I updated my code 👍

```
        cmake = CMake(self)
        cmake.configure(
            cli_args=[
                "-S ./aburn/eng/src/aftr",
                "-B ./aburn/eng/cwin64",
            ]
        )
        cmake.build(target="INSTALL")
```

And I trigger the batch build using a separate init.py file

```
import subprocess

def RunConan(build_type):
    subprocess.run(
        (
            "conan", "create", ".",
            "--build=missing",
            f"--settings=build_type={build_type}",
            "-tf=",  # Skip tests for now
        )
    )

if __name__ == "__main__":
    RunConan("MinSizeRel")
    RunConan("Debug")

```

**Comment by memsharded** [comment]
A couple of hints:

- The ``cmake.build(target="INSTALL")`` shouldn't be in the ``build()`` method, but in the ``package()`` method. And there is already a ``cmake.install()`` function that would be better in general.
- Typically you won't need to define the S and B folders to CMake via ``cli_args``. Recipes will define the right folders with ``layout()``.  Please check the ``conan new cmake_lib -d name=pkg -d version=0.1`` (conan 2.0 syntax), which creates a fully functional recipe and project with CMake that works out of the box and you can ``conan create .`` and it will work, without needing that.

**Comment by himankpathak** [comment]
Thanks @memsharded for the tips. I will surely update these things.

I had one more question. I am uploading my recipe on local `conan-server`. 
`conan upload package_name -r=localserver --only-recipe `

- Is there a way to upload and trigger init.py?
- Instead of `conan install` can I call `conan create` to directly build from remote?

**Comment by memsharded** [comment]
Not sure what you mean here.

A  recommendation: ArtifactoryCE is completely free, and is more powerful that conanserver, including WebUI, better auth, etc.

- Upload only works with packages created already in the cache, it is not using the local files for anything at all, you need to create/build the packages first in the cache, then call ``conan upload``
- ``conan create`` works from your local files to create a new package in the cache, but the start point are the files in your current folder. ``conan install`` assumes that the package already exist in the cache or in the server. Very different behavior.

**Comment by himankpathak** [comment]
Thanks @memsharded . 
I was just trying to do some unnecessary optimizations. Everything is working for me.
