### ISSUE TITLE
Upload without force overwrites server with local package

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#1381]
I always thought that if you try to push a local package to remote without the `--force` option, Conan looks up the remote server and if there already is a package with the same version, no matter what the package date is, it will not let you upload the package. 

I was testing this feature today and I realized I am wrong. I can successfully, which is very unfortunate, push my local packages to the server and overwrite perfectly good/stable packages with untested packages without using the `--force` option. In our workflow we use `--force` on our testing channels and when the tests and integrations are successfully passed we move the package to the stable channel. This workflow lets us have something that we can always trust and get back to easily, what we have on the stable channel, and also lets us overwrite the server testing channel without having to update conanfile.txt's version and channel all the time.

I am not sure how this was designed to work but I believe it is really scary that you can push anything to the server and the only thing that stops you from overwriting a package is the package date. 

Is there any way to protect a package once it is on a stable channel?

**Comment by memsharded** [comment]
Yes, the ``--force`` checks whether the recipe has newer changes than those you have on your local cache. It is intended to avoid concurrent overwrite, i.e. another developer of your team, happen to have uploaded a new version, that will be overwritten if you upload yours. Otherwise, you are allowed to overwrite versions.

There are good reasons for this, mainly there are users who want to be able to overwrite packages, so this is the default behavior. For specific workflows, like protecting certain channels (note that "stable" is just a random example string, there is absolutely no logic associated to it in the conan codebase) there are several things you might do:
- First, "stable" packages shouldn't probably be uploaded by developers, but only by the CI system, which has its own user, and is the only user with write permissions over those packages.
- Permissions can be controlled in Artifactory and conan_server. In Artifactory you could try to remove the "delete" permissions to packages with "stable" channel. With conan_server, it might still be doable, but could require some more manual operation.

**Comment by AliAskari** [comment]
I totally understand why ``--force` is useful but my main concern is uploading without the `--force` flag. I believe if the force flag is not used we should not be able to overwrite remote packages if the version has not changed. 

We are already releasing all packages through a CI but versioning is not automated (I think it should not be). I was testing our CI to make sure if a developer forgets to increment the version then the **Conan Server** will refuse to overwrite the remote package if `--force` flag is not used. Much to my surprise I could overwrite the remote package without using `--force`.  Based on your reply it seems this is the intended behavior :(

So I have to add some logic to our CI, for stable channels, to get a list of available versions on the remote server and make sure not to upload if the current version already exists on the server.

**Comment by memsharded** [comment]
Changing that logic in the servers (in all of them: conan_server, Artifactory, Bintray) might be difficult and take a long time. But I understand the issue, and also that it seems logical to have a server-side solution. Lets consider it, analyse if viable.

**Comment by amogkram** [comment]
This has been a surprise that we've also run into this week as we attempt to provision a conan server and integrate it into our CI. What about a workaround such as a `--weak` flag that will not attempt to overwrite existing packages?

Regarding your comment about permissions for conan_server: the most granular levels for permissions that I see are for reading and writing. Is there a `[delete_permissions]` heading that exists for this purpose?

**Comment by memsharded** [comment]
Yes, maybe that is a good idea, at least provision something in the client that check package existence. That could be helpful, and easier to deploy than a server side solution. We will check it, thanks @amogkram  very much for the tip!

**Comment by memsharded** [comment]
This was solved long time with revisions. Overwrites will not happen, as revisions will add a unique id to the package reference in the server. Closing this as solved.
