### ISSUE TITLE
[feature] Allow exports without affecting recipe timestamps

### ISSUE THREAD

**Issue by sfackler** [conan-io/conan#13819]
### What is your suggestion?

I have a project that contains multiple Conan recipes, with some dependencies between them. To update the lockfiles for the packages in an automated fashion, I first export all of the recipes and then generate lockfiles. However, this causes the lockfiles to change every time since each export of a recipe updates its revision timestamp which is included in the lockfile.

I'd like to have some way to do an "export if necessary" (i.e. if the recipe revision is not already in my cache or a remote), or alternatively, an export that does not adjust the timestamp if that revision has already been exported.

Does that seem reasonable? Is there some other way to have a stable lockfile in this kind of setup?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sfackler 

Thanks for your comments

> I'd like to have some way to do an "export if necessary" (i.e. if the recipe revision is not already in my cache or a remote), or alternatively, an export that does not adjust the timestamp if that revision has already been exported.

This is almost impossible by definition: the ``revision`` cannot be computed until the package is exported, because it needs to execute the ``exports``, ``exports_sources`` (and the methods too), to process hooks that could affect, etc, etc. So until it is exported and everything is computed it is not possible to know if it will be the same revision or not. 

Then, for stability reasons it is necessary to make it the "latest" revision, that is, to update the revision timestamp, because if it not updated and made the latest, the behavior is highly confusing.

So overall I think this is expected behavior, and I don't see a way to change it that wouldn't create other bigger problems.

**Comment by sfackler** [comment]
> Then, for stability reasons it is necessary to make it the "latest" revision, that is, to update the revision timestamp, because if it not updated and made the latest, the behavior is highly confusing.

But how can the behavior be confusing if you're explicitly opting into it? `conan export --only-if-needed .` or whatever.

Alternatively, can't it not update the timestamp if it's already the latest revision?

**Comment by sfackler** [comment]
Alternatively, does the timestamp even need to be stored in the lockfile? Once the revision is locked, the ordering of it compared to any other revisions wouldn't matter, right?

**Comment by memsharded** [comment]
> Alternatively, does the timestamp even need to be stored in the lockfile? Once the revision is locked, the ordering of it compared to any other revisions wouldn't matter, right?

Yes, it is critical for lockfiles to contain timestamps, check the "Important" note in the docs in: https://docs.conan.io/2/tutorial/versioning/lockfiles.html

Lockfiles are sorted by versions and revisions time. This is critical to be able to correctly resolve ``requires`` against the lockfile, note that it is possible to have "free" requires (without pinned revisions) that need to resolve to the latest, and also pinned requires that explicitly define the revision, pointing to different revisions, in the same dependency graph. Thus, maintaining the order of the lockfile is critical, in the same way that maintaining the versions ordered (to correctly resolve version-range, exactly the same behavior, but with versions instead of revisions) is completely necessary.

**Comment by sfackler** [comment]
It looks like making the local packages editable before creating the lockfile causes them to be recorded without a revision, which makes things nicely stable.
