### ISSUE TITLE
Uncertain if conan can do what I'm interested in?

### ISSUE THREAD

**Issue by M2tM** [conan-io/conan#1385]
I'm unfamiliar with conan.io except in passing, so forgive my ignorance.

I'm interested in unifying my build process across ios (emulator or device), android (emulator or device), osx, and windows.

I want to be able to generate, with one click, a project for each platform (or a multi solution project for Xcode and one for Visual Studio which can target each platform easily) which I can open up and run on the target hardware. This means I would like to be able to, from a conan file, generate my Visual Studio 2017 project to run on windows or android possibly, or xcode for osx or iphone.

I have the following dependencies:

boost.asio
boost.filesystem
boost.uuid
OpenSSL
SDL2
SDL2_Image
SDL2_Mixer
SDL2_TTF
OpenGL
Chaiscript
Cereal (with some customizations locally, I can just include the headers directly)

And then I have my own source files on top of that.

Would anyone be willing to help out? I would be happy to offer monetary compensation if it's more than a few minutes to create the initial conan project for me which can run an SDL program with boost on the following:

iOS (emulator + device), Android (emulator + device), OSX, Windows.  Stretch goal: Windows Phone.

I honestly just don't know where to start exactly, I'm taking an existing project I've manually gotten running on the iOS emulator about 4 years ago, but haven't tried again since, and am mostly doing development in windows.  Any help would be greatly appreciated. If conan is not the tool for the job, any suggestions would be appreciated too.

As one indie programmer it's hard to manage the build system on top of just getting the project to work.

Thanks again. Seriously, I'll offer cash for anyone willing to take the time, just let me know what you think a fair price would be.

Also, is there a more appropriate place to request help like this?

**Comment by memsharded** [comment]
This is a good place to ask things, ask for help and advice, no problem.

I am not sure if conan is what you are looking for. Have you had the chance to have a quick look to the getting started, for example?

So conan is a package manager, but not a build system. From your description it seems that you want something like a meta-build system, the closest I can think of would be CMake. CMake takes CMakeLists.txt file and generates for you Visual Studio projects, XCode projects, Makefile projects, etc., for different OS, compilers and IDEs.

So conan will not generate build scripts or projects for you. You still to have your build system, or build system, and conan will wrap it. Conan is very agnostic about the build system, it can handle any one. It has better integration with known one, like cmake, visual studio or makefiles, but it can do any. But conan will basically call the build system to generate the artifacts.

Then, the dependencies are a different problem. There are many packages in bintray ``conan-transit`` repository (just migrated from old conan.io repository), Boost, SDL and OpenSSL included. But the existing packages might work well for PC based systems, but maybe they are not well tested for mobile, and they need some tweaks or adaptations. Usually, companies using conan will fork those package recipes and customize them for their needs.

So I would say than an initial setup for your project, with those dependencies and the platforms you want so support, it will require quite a lot of time. Most of it will not be related to conan, but just to update the packages to support those platforms. One of the goals of the migration to bintray, and the new ``conan-center`` repository, is to improve the quality of the packages, so it is easier for consumers getting started using many different dependencies.

I encourage you to run the "getting started", that will setup a project using cmake that will depend on Boost, Poco, OpenSSL and ZLib and works quite seamlessly in Windows, to get a flavor of how conan works and what it does.

On the monetary side, we are very sorry, we can't accept it. We are serving quite a large community, trying to prioritize the community as a whole, so unfortunately taking these assignments is not possible for us. I suggest you run the getting started, get the idea, then submit a new issue explicitly asking for it, maybe someone from the community can get it.

If you think this question is solved, please close the issue, otherwise, looking forward your feedback. Cheers!

**Comment by M2tM** [comment]
Yeah, understood. It sounds like more of what I'm looking for is involved in CMake than Conan, your answer was very clear and helps a lot. Thank you!

I'm not as concerned with downloading the correct dependencies, so much as, given a directory with all of them already fetched, building the correct project files and setting up the configuration for various builds. This is something I've always shied away from, and as you say, it will require quite a lot of time.

**Comment by memsharded** [comment]
Got it, that makes sense. Indeed for an indie developer, having a simple setup for an small and stable set of dependencies is not a huge problem. If there were very mature conan packages for them, tested in multi-platform, I would definitely recommend using conan, but being honest, the package ecosystem is still young, so you rather wait a bit until ``conan-center`` repo in bintray matures a bit. You should definitely start with CMake first. And prepare to suffer anyway, this will be not easy task. Good luck!
