### ISSUE TITLE
[question] None or null?

### ISSUE THREAD

**Issue by marausch** [conan-io/conan#13860]
### What is your question?

Hi!
Looking at the new _settings.yml_ file as generated by **Conan 2.0.4**, seems that the value `None` has been replaced by `null`.
Are they equivalent? Is the same true for options?
Sorry for this maybe silly question.
BR

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Yes, in Conan 2.0, the ``settings.yml`` will be parsed as pure yaml. In the past the ``None`` was processed internally and converted, it was ugly and error prone. Also confusing because of users wanting to have a literal "none". So the yaml ``null`` means: this settings doesnt need to be defined, in recipes/python it will be Python ``None``.
