### ISSUE TITLE
[question] Estimation on a release (esp. 1.60)

### ISSUE THREAD

**Issue by SzBosch** [conan-io/conan#13871]
### What is your question?

Dear Conan,

how/where can I get an estimation on when a release will be available?

Especially I am interested in the version 1.60 for which all PRs for the milestone are green since a couple of days.
Now I is unclear to me of what is going on in the background in the conan project release process and maybe what are current blockers/delays.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @SzBosch 1.60 is to be released today :)

**Comment by SzBosch** [comment]
Hi @RubenRBS, that is great.

Just for the future: Here no due date is visible: https://github.com/conan-io/conan/milestones

How can we now the dates for future releases?

**Comment by memsharded** [comment]
Hi @SzBosch 

We don't do closed dates for releases at this moment, because the variability is very high. When we had 1.X only, the release train was one 1.X release per month, end of the month. We don't commit to dates either, so this was approximately end of the month, but could be changed.

Now we are transitioning to 2.0, so at the moment 2.0.X releases will be more frequent and 1.X will be less frequent, but they also depend on the importance of merged things, syncing both 1.X and 2.0 trains, etc.

**Comment by SzBosch** [comment]
Thank you for the information.

**Comment by czoido** [comment]
@SzBosch Conan 1.60 has just been released: https://github.com/conan-io/conan/releases/tag/1.60.0
