### ISSUE TITLE
[question] `build_folder` and `package_folder` always empty in `conan graph info . -f json`

### ISSUE THREAD

**Issue by meghfossa** [conan-io/conan#13939]
### What is your question?

**Question: Why is `build_folder` and `package_folder` always null in `conan graph info . -f json -c tools.build:download_source=True`?** (conan v2)

```json
{
            "ref": "openssl/3.1.0#25925a18588e030e406a15da96c4d32b",
            "id": 3,
            "recipe": "Cache",
            "package_id": "c6f0d27a6f6fc6a1f1861a5b4bf6b5001d4a6565",
            "name": "openssl",
            "url": "https://github.com/conan-io/conan-center-index",
            "license": "Apache-2.0",
            "description": "A toolkit for the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols",
            "homepage": "https://github.com/openssl/openssl",
            "revision_mode": "hash",
            "version": "3.1.0",
            "package_type": "static-library",
            "settings": {
                "os": "Macos",
                "arch": "armv8",
                "compiler": "clang",
                "compiler.version": "13",
                "build_type": "Release"
            },
            "requires": {
                "4": "zlib/1.2.13#e377bee636333ae348d51ca90874e353"
            },
            "system_requires": {},
            "recipe_folder": "/Users/dev/.conan2/p/opens4d8b8eb2b5350/e",
            "source_folder": "/Users/dev/.conan2/p/opens4d8b8eb2b5350/s/src",
            "build_folder": null,
            "generators_folder": null,
            "package_folder": null,
            "label": "openssl/3.1.0",
            "context": "build",
            "test": false
        },
```

I'm thinking of doing this at the moment to get around this issue:

(1) Read lockfile
(2) Identify cache db from `$CONAN_HOME/p/cache.sqlite3`
(3) Retrieve packages directories by doing: 
```sql 
-- select pkgid, path from packages where pkgid in ('c6f0d27a6f6fc6a1f1861a5b4bf6b5001d4a6565')
select pkgid, path from packages where pkgid in ${packageIds}
```
Reading the conan code, I'm seeing that package directories are written in `${path}/p/`, and build directories are written in `${path}/b/`. 

- Does the aforementioned approach work across various package types and conditions (conan v2 only)? 
- Is there a better way to retrieve the dependency graph with _non-null_ artifact directory and _non-null_ source directory?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @meghfossa 

Thanks for your question.

The build folder and package folder are None/empty, because those folders do not necessarily exist for the ``conan graph info`` command. For example if the command executes in an empty cache, the graph will be computed, downloading all the recipes, but the binaries will not be downloaded nor built. The binaries don't exist at all in the Conan cache, the folders containing them do not exist.

Furthermore, the location in the cache of a package that is going to be built from source cannot be known in advance, as they get some random new identifier at the time of the build, and they will get a new location when the final package is built and the ``package revision`` can be evaluated, but it is impossible to predict what package revision will result.


It is not very clear what you are trying to achieve, but for sure reading the internal sqlite DB is not allowed and can result in undefined behavior and crashes.

If you are trying to do some operation on the package binaries for a given graph, it cannot be done with the ``graph`` command, it must be done with the ``conan install`` command, and I'd recommend checking the deployers https://docs.conan.io/2/reference/extensions/deployers.html (for low variability tasks) and custom commands https://docs.conan.io/2/reference/extensions/custom_commands.html (for high variability/heavily parameterized tasks)

**Comment by meghfossa** [comment]
Thanks for the ans. @memsharded  

> For example if the command executes in an empty cache, the graph will be computed, downloading all the recipes, but the binaries will not be downloaded nor built. The binaries don't exist at all in the Conan cache, the folders containing them do not exist.

I understand that, if cache is empty - package or build directory will be empty. However, in my case cache is not empty (I'm looking at `cache.sqlite3` to know if cache is empty or not). Is it expected behaviour that `build_folder`, and `package_folder` will always be null, regardless of cache state? 

> It is not very clear what you are trying to achieve, but for sure reading the internal sqlite DB is not allowed and can result in undefined behavior and crashes.

What I want to achieve is following, 

```
 node: 
    id: 0
    pkgLabel: ``
    pkgId: `...` 
    srcDir: `...`
    pkgDir: `...`
    pkgType: `...`
    packageType: `...`
    test: bool
    requires: 
       - nodeId: pkgId
```

This is so I can ultimately, create software bill of materials (sbom). Would I be able to achieve this using [generators](https://docs.conan.io/2/reference/extensions/custom_generators.html#using-global-custom-generators)? It's hard to know what API generator would have access to i.e. type of conanfile.

**Comment by memsharded** [comment]
> I understand that, if cache is empty - package or build directory will be empty. However, in my case cache is not empty (I'm looking at cache.sqlite3 to know if cache is empty or not). Is it expected behaviour that build_folder, and package_folder will always be null, regardless of cache state?

Yes, it is expected. Even for previously existing packages, a ``--build`` could be discarding that and building new binaries from source, that will be located in a new folder. All the "binary" part of the graph is simply not evaluated in the ``conan graph info`` command, because it is expected to achieve exactly the same results irrespective of the binaries.

> This is so I can ultimately, create software bill of materials (sbom). Would I be able to achieve this using [generators](https://docs.conan.io/2/reference/extensions/custom_generators.html#using-global-custom-generators)? It's hard to know what API generator would have access to i.e. type of conanfile.

Absolutely, this is a perfect case for a custom deployer, or a custom command. I know the docs at this moment are still work in progress, but https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html should be a good start point. Only if the deployer feels short of functionality (need more knobs to control the output), then I would consider a custom command.

The source code of our builtin ``full_deploy`` could be useful too: https://github.com/conan-io/conan/blob/release/2.0/conan/internal/deploy.py#L47. The interface for dependencies via ``conanfile.dependencies.values()`` is the same you can get in your ``generate()`` methods, this could help: https://docs.conan.io/2/reference/conanfile/methods/generate.html#self-dependencies

Then you can manage your deployer with ``conan config install`` and use it like:
```
conan install . --deployer=mysbomdeployer
```

**Comment by memsharded** [comment]
Btw, the ``conan install --format=json`` will also output the same dependency graph, but more complete (note the json is not publicly documented yet, not stable, it will change in next 2.0.6 release and then we will start documenting it for public usage)
However, even if you could use this json, I'd probably recommend the ``deployer`` approach.

**Comment by meghfossa** [comment]
Thank you @memsharded - feel free to close this issue. I think I have a path forward now.

**Comment by memsharded** [comment]
Great, you are welcome. Don't hesitate to create new tickets if you have any further questions. Thanks!
