### ISSUE TITLE
[question] Dependency graph computation for tool_requires in conan 2.0

### ISSUE THREAD

**Issue by sandeshhardikar** [conan-io/conan#13959]
### What is your question?

Dear Conan Team,

 we are facing issues while migrating some of our recipes to `conan 2.x`. We have some base tooling which is used in all our packages inclusive in the base tooling one.

- Lets say we have 2 packages named `my-build-tool` and `my-doc-tool` which are `tool_requires` on each other. They are building fine in `conan 1.x`.

- I updated and released both packages after making the recipes compatible with `conan 1.x` and `conan 2.x` by changing for example the legacy `from conans` import to `from conan`.

- When I try to build `my-build-tool` and `my-doc-tool` using `conan 2.x`, it fails because conan tries to load the recipes all the way down the dependency graph and ultimately hits the `from conans` import from old packages.

I tried to show this in the picture:

![image](https://github.com/conan-io/conan/assets/5364255/18a7c1bd-7115-4e69-904d-6ece1eeeeded)

How do we deal with such a situation? Can you suggest if there is any way to support this use case?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandeshhardikar 

Thanks for your question.
It seems that you are in a complicated cased of "bootstraping" in which there is a cycle of dependencies, but not a real cycle because basically you are requiring the older version of the tool to build the other.

Basically your dependency graph is as follows:
```
build/20 -> doc/10 -> build/19 -> doc/9 -> build/18 -> doc8 ->    ..... ????
```
Where all the arrows are ``tool_requires``. 

This is obviously a chicken-and-egg problem, or "bootstrapping", that should end somewhere, where does it stop? Who was first ``doc`` or ``build``? How was the first package created?

Conan 2.0 will indeed compute the whole graph, down to the initial package that didn't have further dependencies.

One of the possibilities would be to update the recipes in place, without bumping the version. Updating the recipes will create a new "recipe-revision" that is used by default, so it is possible to update the recipes to Conan 2.0 without bumping the version. Still it would be necessary to re-consider the approach, as this cannot extend to infinity. The bootstrapping scenarios should be quite limited, otherwise the recursion length can be a bit problematic if you keep generating many new versions of those 2 packages.

One of the other typical solutions is try to break the cycle, by indirection, like an extra third package that consumes both or something. In that regard, understanding the contents of the package, and why and how they depend on each other to be built, would help to try to think possible approaches.

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you in a while - if anyone has any other question or request, please feel free to create a new issue, we're always happy to help! :)
