### ISSUE TITLE
[bug] conan install error in python 3.10

### ISSUE THREAD

**Issue by chezgi** [conan-io/conan#13987]
### Environment details

* Operating System+version: ubuntu 22.04.2
* Compiler+version:
* Conan version: 1.60
* Python version: 3.10

### Steps to reproduce

conan install  -r conancenter  boost/1.69.0

### Logs

ERROR: Invalid settings.yml format: module 'collections' has no attribute 'Hashable'

**Comment by memsharded** [comment]
Hi @chezgi 

Thanks for reporting.
This looks like some kind of corruption in your Python or Conan installation.
I'd try the following:

- Remove your Conan cache completely, and start from scratch (remove the .conan folder). Also possible to define ``CONAN_USER_HOME`` env-var pointing to another empty folder.
- Please share the full output log, not only the error message, just in case.
- How did you install Python and Conan? In a Python virtualenv? Conan via ``pip install conan``? Please share the details.
- Does it work with other packages? what if you try ``zlib/1.2.13`` package instead?

**Comment by chezgi** [comment]
Hi @memsharded 
thanks for your quick reply

python is the default python installed on ubuntu.
i used `pip install "conan<2"` for installing conan itself.
removing .conan cache dosn't solve the problem.
 
running `conan install  zlib/1.2.13` results:
```
Auto detecting your dev setup to initialize the default profile (/home/chezgi/.conan/profiles/default)
Found gcc 11
Found clang 14.0
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit '/home/chezgi/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************



Default settings
	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	compiler=gcc
	compiler.version=11
	compiler.libcxx=libstdc++
	build_type=Release
*** You can change them in /home/chezgi/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


ERROR: Invalid settings.yml format: module 'collections' has no attribute 'Hashable'
```

**Comment by chezgi** [comment]
debug mode output:
```
DEBUG :conan_api.py   [176]: INIT: Using config '/home/chezgi/.conan/conan.conf' [2023-05-29 08:26:46,738]
DEBUG :tracer.py      [156]: CONAN_API: install(path=zlib/1.2.13,name=None,version=None,user=None,channel=None,settings=None,options=None,env=None,profile_names=None,conf=None,profile_build=ProfileData(profiles=None, settings=None, options=None, env=None, conf=None),remote_name=None,verify=None,manifests=None,manifests_interactive=None,build=None,update=False,generators=None,no_imports=False,install_folder=None,output_folder=None,lockfile=None,lockfile_out=None,require_overrides=None) [2023-05-29 08:26:46,738]
DEBUG :profile_loader.py[121]: PROFILE LOAD: /home/chezgi/.conan/profiles/default [2023-05-29 08:26:46,739]
ERROR: Invalid settings.yml format: module 'collections' has no attribute 'Hashable'
```

**Comment by memsharded** [comment]
Can you please list what PyYaml version do you have installed? https://github.com/yaml/pyyaml/issues/622

(``pip list`` or something like that)

It is very likely that newer Pythons are breaking older PyYaml releases. The default ``PyYAML>=3.11, <=6.0`` range is for the base Python3.6 we are still maintaining. Maybe try to update your PyYaml and report.

**Comment by chezgi** [comment]
PyYAML                  5.4.1

**Comment by chezgi** [comment]
updating PyYAML to 6.0, it worked.
thanks @memsharded

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/13990, will enforce pyyaml>=6, from next Conan 2.0.7

**Comment by Katze719** [comment]
updating PyYaml to 6.0 did not work for me, is the somethin else im missing ?
@memsharded

**Comment by memsharded** [comment]
Hi @Katze719 

It might be worth creating a new issue, or at least adding a few extra details, just in case:

- Still the exact same error? ``ERROR: Invalid settings.yml format: module 'collections' has no attribute 'Hashable'``. Or a different one? Please share the commands you use and the output.
- The fix was for Conan 2.0.7, are you trying that version? Or did you just installed manually PyYaml 6.0 on your environment?
- What OS? Conan installed with regular ``pip install``?

**Comment by Katze719** [comment]
- still the exact same error
- conan 1.60
- ubuntu 22.04

but i fixed it by using conan 1.57 and my old settings.yml file

**Comment by memsharded** [comment]
``conan 1.60`` didn't get this fix, only 2.0. Did you manually force the installation of PyYaml>=6 yourself on your 1.60 installation and still the same issue? Are you completely sure that that PyYaml version was installed? (you can check it with a ``pip list``)

**Comment by Katze719** [comment]
i forced PyYaml myself to version 6.0.0

**Comment by memsharded** [comment]
I don't know what could be happening in your case. I have just tried and I can't reproduce. If I install PyYaml 6 in 1.60 with Python 3.10, everything seems to work fine.

Edit: I have tried both in Linux (Ubuntu) and Windows, just in case, still cannot reproduce the environment.

Maybe it would be great to have some environment, like a docker image when we could reproduce it, do you think it is possible? (I am trying in our images ``conanio/gccXX`` without luck)

**Comment by Katze719** [comment]
im using a fresh install from a wsl2 ubuntu-22.04 from today,

steps i did:

- sudo pip install conan==1.6
- conan remote add conancenter: https://center.conan.io
- echo 'export CONAN_HOME=$HOME/.conan/' >> \~/.bash_profile
- echo 'export CONAN_USER_HOME=$HOME/' >> \~/.bash_profile
- conan install zlib/1.2.13

results in ERROR: Invalid settings.yml format: module 'collections' has no attribute 'Hashable'

but still, using conan 1.57 everything works fine for me, as long as i use my old settings.yml file

**Comment by memsharded** [comment]
Hi @Katze719 

I see several potential problems there:
- Are you installing Conan 1.6? That is a super old version. I guess you meant 1.60, but please check it
- Why are you adding conancenter? That is always added by default
- ``echo 'export CONAN_HOME=$HOME/.conan/' >> ~/.bash_profile`` This is super dangerous. That is the Conan 2.0 cache, and that will overwrite the Conan 1.X cache. They are incompatible, and this will destroy things. Please don't do that
- ``conan install zlib/1.2.13`` is a CLI error in Conan 1.X. I guess you meant ``conan install zlib/1.2.13@``?

The third point is specially problematic, and probably what is causing the issue here. Can you please try the steps above, in a fresh wsl2 ubuntu, without adding that to the ``bash_profile``? I have just tested in the same wsl2 ubuntu with a normal flow and it seems to work without issues here.

**Comment by Katze719** [comment]
yep, that fixed it, i wanted to install `conan 1.60` but installed `conan 1.6` 
thanks for your help
@memsharded

**Comment by tbeu** [comment]
Still broken in Conan 1.64 and Py 3.10 due to `PyYAML>=3.11, <6.1`.

**Comment by memsharded** [comment]
Hi @tbeu 

This issue is closed, that means it is not planned to change this in Conan 1.X scope, it has been solved in Conan 2.
For Conan 1.X and Python 3.10, it might be necessary to force the installation of a newer PyYAML version, or to use an older Python.

**Comment by tbeu** [comment]
Sure, it helps to upgrade pyyaml. That's the easy part. But as a consumer it is more hassle to figure out first why it is broken. In my opinion Conan 1.X  - even if deprecated - should not allow a known broken combination of package dependencies.

**Comment by memsharded** [comment]
> Sure, it helps to upgrade pyyaml. That's the easy part. But as a consumer it is more hassle to figure out first why it is broken. In my opinion Conan 1.X - even if deprecated - should not allow a known broken combination of package dependencies.

They are not broken dependencies for Python < 3.10. The problem is that it is not that easy to keep supporting newer and newer Python versions, because also Conan dependencies change, they might not be supported either, they can break for newer versions, etc. That is not only a lot of work, but also sometimes result in breaking behavior, which it is not possible under Conan stability commitment, and resources are not infinite. Conan 2 was released more than 1 year ago now, and it was previously in beta for 2.5 years. Last year alone ConanCenter received almost 6000 PRs, it is simply not possible to maintain everything with the same priority, and at some point, some prioritization and trade-offs are made, and in this case, we apologize for the inconvenience, but supporting the legacy Conan 1.X for newer Python versions was not possible
