### ISSUE TITLE
cpprestsdk/2.8.0@lasote/vcpkg with MT/MTd runtime

### ISSUE THREAD

**Issue by definename** [conan-io/conan#1398]
I am trying to build 'cpprestsdk/2.8.0@lasote/vcpkg' with MT/MTd runtime. That is my conanfile.txt:

> [requires]
> cpprestsdk/2.8.0@lasote/vcpkg
> 
> [generators]
> cmake
> 
> [options]
> cpprestsdk:shared=false

That is conan args:
> conan ^
> 	 install ^
> 	 ../.. ^
> 	 -s arch=x86 ^
> 	 -s build_type=Debug ^
> 	 -s compiler="Visual Studio" ^
> 	 -s compiler.runtime=MTd ^
> 	 -s compiler.version=14 ^
> 	 -s os=Windows ^
> 	 --build missing

During configuring project I have this [error](http://i.imgur.com/SFSNaTL.png). **My question is how to build MT/MTd cpprestsdk with conan**. Looks like this package does not support MT/MTd at all. Is there another cpprestsdk package, I found only this one.
Thanks.

**Comment by memsharded** [comment]
Hi @definename 

Yes, this package is a wrap of the vcpkg one, that just provides support for MD.

You can try some other packages from https://bintray.com/conan/conan-transit, search for ``cpprestsdk`` in the **Package Name** box, you should see 3 other recipes, which seem native, they might support MT. 

I have checked the first one, and it seems they have a github repository associated, like https://github.com/BleuGamer/conan-cpprestsdk, so questions and requests for that package could be submitted there, to collaborate with the package creators.

I think this issue can be closed now, because it is just related to a package, not a conan (tool) issue, and no action is required by us, but please comment or ask if you have further questions.

**Comment by definename** [comment]
Thanks for the answer.

> I have checked the first one, and it seems they have a github repository associated, like https://github.com/BleuGamer/conan-cpprestsdk

How did you check it? Is it possible to check it from my side?
