### ISSUE TITLE
False error message from server on recipe date

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#1400]
I am getting an error from Conan about the date of the recipes during package upload:

    ERROR: Remote recipe is newer than local recipe: 
     Remote date: 1497631534
     Local date: 1497631533

I have two questions:

 - The ID of the package to be uploaded is `8b4785d057bc63d4eaaf651d24408163e3623ad7` and this package does not exist under any of the channels. What does that remote date mean when there is no such package on the server?

 - I am running the Conan server in a docker container and our CI is using Windows/Linux docker containers. They are all using the same time server. What is causing such a small difference in Remote/Local dates? Is there a configurable option, server side, to ignore small time differences? 

BTW, I don't want to use the `--force` flag to get around this problem.

**Comment by memsharded** [comment]
What you are seeing is the result of an inconsistency in the package recipe, not the binary. Typically you don't want to accidentally overwrite a package recipe that has been uploaded with some changes. It is not a matter of the binary, when the binaries are uploaded, also the package recipe is uploaded for consistency, and such package recipe is throwing an error, because it has been changed in the server concurrently.

This might appear precisely when doing concurrent builds and uploads and there is some inconsistency in the package recipes, because some mistake in the slaves (possible using an outdated recipe). Between different OS, it could be that some process, like ``git clone`` is changing the package recipe files CRLF, and then producing a different package recipe manifest.

Precisely the way to ignore such changes is the ``--force`` argument. But I agree, you probably shouldn't use it, but rather investigate why your CI slaves are trying to upload different package recipes when creating the packages. You might try to inspect the conan local cache of the slaves and the server, read the ``conanmanifests.txt`` and check which files are the offending/changing ones and why, what changes do they have.

**Comment by AliAskari** [comment]
I didn't know that different line endings is important. However, I don't believe this is the problem because in our git set up we check out source code with Linux line endings on all platforms. 

I faced this problem multiple times and every time simply re-running the failed job resolved the problem. I did not modify a single byte in the package and everything worked as expected. 

I have put a 10 second delay between our Windows and Linux jobs and it seems to have fixed the problem. Since this issue only pops up in concurrent uploads in our CI it makes me believe that the issue is not related to the points you have raised. I am not sure how conan server handles concurrent uploads but it seems it has issues.

**Comment by memsharded** [comment]
Yes, it is very important. Git itself has different configurations for it, because cloning a project in Windows can accidentally change all files because introducing/replacing all line feeds with CRLF, and then it appears that your whole project has been modified. If you are using the same checkout with line endings, indeed it shouldn't be the problem.

This is very weird. I will have a look to conan_server to check what could be happening. Thanks for the suggestions.

**Comment by memsharded** [comment]
BTW, if next time it happens, you are able to capture the "export" folder of the failing package, both in the conan server and in the slaves, and send it to info@conan.io for analysis, that could help diagnosing the problem, as you know this concurrency issues are difficult to replicate. Thanks!

**Comment by conradjones** [comment]
I just had this issue, it actually was timezone differences between the differing windows and linux CI machines. the windows VM was picking up time from the host when booting (and you can bet the windows one reboots more frequently) and the host was configured with the incorrect timezone. Where as the linux VM seemed to recifty it's time correctly as soon as it booted.

**Comment by memsharded** [comment]
Thanks for the feedback @conradjones 

If possible, please capture the "export" folders for that package in the cache and in the server. The timestamp is totally irrelevant if there are no changes in the recipe, so this only happens when there are some changes in the recipe itself. And if there are changes, then this is desired behavior.

Something that could be happening is using different CRLF checkout (git) in Windows than in Linux, so then the file checksums are different and the system understand that the recipe has changes. Could that be the case? Thanks!

**Comment by conradjones** [comment]
This makes sense given the behaviour I've been observing over the last few days.
Just so I'm uploading the correct folder. Where would I find this folder, there are a few created by a build. 
(I'm running jenkins and this build on a jenkins windows slave)

I have a c:\.conan folder and various folders under c:\jenkins\workspace

What would the export folder in the cache contain ? So I can identify it easily.

On the server end I'm running Artifactory CE/CPP.

Thanks.

**Comment by memsharded** [comment]
Hi!

From Artifactory, you can just download the files directly in the web UI, navigate the Artifacts->Repo->package->version->files->export, there should be 3 files: conanfile.py, conanmanifest.txt, conan_export.tgz (maybe conan_export_sources.tgz)

In the local cache (not sure if your c:/.conan or in the workspace) the folder is data/pkg/version/user/channel/export.

Thanks!

**Comment by conradjones** [comment]
Diffing the conanfile.py it's clearly the line ending differences between the OSs as there is no visible character differences

conrad@conrad-arch:~/Desktop/aubio (copy)$ diff conanfile.py conanfilew.py
1,25c1,25
< from conans import ConanFile, CMake, tools
<
<
< class AubioConan(ConanFile):
<     name = "Aubio"
<     version = "0.4.6"
<     license = "GPL License"
<     url = "<snipped internal>"
<     description = "Audio processing library for C++."
<     settings = "os", "compiler", "build_type", "arch"
<     options = {"shared": [True, False]}
<     default_options = "shared=False"
<     generators = "cmake"
<     exports_sources = "src/*"
<
<     def build(self):
<         cmake = CMake(self)
<         cmake.verbose = True
<         cmake.configure(source_folder="src")
<         cmake.build()
<
<     def package(self):
<         self.copy(pattern="aubio.h", dst="include", src="src")
<         self.copy(pattern="libaubio.a", dst="lib", src="lib")
<         self.copy(pattern="aubio.lib", dst="lib", src="lib")
---
> from conans import ConanFile, CMake, tools
>
>
> class AubioConan(ConanFile):
>     name = "Aubio"
>     version = "0.4.6"
>     license = "GPL License"
>     url = "<snipped internal>"
>     description = "Audio processing library for C++."
>     settings = "os", "compiler", "build_type", "arch"
>     options = {"shared": [True, False]}
>     default_options = "shared=False"
>     generators = "cmake"
>     exports_sources = "src/*"
>
>     def build(self):
>         cmake = CMake(self)
>         cmake.verbose = True
>         cmake.configure(source_folder="src")
>         cmake.build()
>
>     def package(self):
>         self.copy(pattern="aubio.h", dst="include", src="src")
>         self.copy(pattern="libaubio.a", dst="lib", src="lib")
>         self.copy(pattern="aubio.lib", dst="lib", src="lib")

**Comment by conradjones** [comment]
thanks. I'll do that with my repos/ and and add the .gitattributes to my tempate.

**Comment by danimtb** [comment]
I think this was answered and there are some other issues related. I have opened an issue in the docs repo to add this answer. Thanks!
