### ISSUE TITLE
[question] Error while uploading a conan package to JFrog Artifactory

### ISSUE THREAD

**Issue by atijoriwala** [conan-io/conan#14012]
### What is your question?

Could you please clarify why am I getting this error? What I maybe doing wrong? I have a conan package in my cache. I just want to upload this package to a remote artifactory. I am getting the error:
The command I am executing is : **conan upload pkg/1.1.1@user/dev -r artifactory-name --all --confirm**
ERROR: pkg/1.1.1@user/dev: Upload recipe to jfrog artifactory failed: Not found: https://artifactory-test.cloud.com/artifactory/api/conan/artifactory-name/v2/conans/mta_gateway_getk-p/1.1.1/user/dev/revisions/a59be930031752919382b1a0322539e5/files/conan_sources.tgz. [Remote: artifactory-name] The 'pkg/1.1.1@user/dev' package has 'exports_sources' but sources not found in local cache. Probably it was installed from a remote that is no longer available.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by atijoriwala** [comment]
I am on conan version 1.54.0

**Comment by atijoriwala** [comment]
I was able to figure out the issue. It was an artifactory issue with virtual repos

**Comment by memsharded** [comment]
Ok, great that you found the solution

> The 'pkg/1.1.1@user/dev' package has 'exports_sources' but sources not found in local cache. Probably it was installed from a remote that is no longer available.

In any case this means:
- You installed some package in teh cache, but without building it from sources. So the sources are not downloaded
- The remote you installed that package is no longer available
- You try to upload that package to other repo. Conan will try to fetch the sources, because otherwise the package is incomplete. If the repo is not available it will fail.
