### ISSUE TITLE
[bug] Artifactory Community Edition for C/C++ failed to start

### ISSUE THREAD

**Issue by yijianshuangdiao** [conan-io/conan#14015]
### Steps to reproduce

I downloaded the application through the link below and completed the decompression on my local machine.
[jfrog-artifactory-cpp-ce-7.59.9-windows](https://conan.io/downloads.html)
Then I ran artifactory.bat as an administrator(I haven’t done anything else apart from this.), but the console frequently displays error messages. It seems that it cannot be started properly.Could you help me take a look at this problem?I can provide all the logs.Thanks.

### Logs

From the access-service.log file.
```shell
2023-06-02T02:43:05.434Z [jfac ] [ERROR] [45b195bff37fa387] [.s.b.w.s.s.ErrorPageFilter:184] [27.0.0.1-8040-exec-1] - Forwarding to error page from request [/api/v1/system/ping] due to exception [The request was rejected because the header value "ç��é��" is not allowed.]
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the header value "ç��é��" is not allowed.
	at org.springframework.security.web.firewall.StrictHttpFirewall$StrictFirewalledRequest.validateAllowedHeaderValue(StrictHttpFirewall.java:833)
...
2023-06-02T02:43:06.836Z [jfac ] [ERROR] [1c05319b66a89254] [.s.b.w.s.s.ErrorPageFilter:184] [27.0.0.1-8040-exec-2] - Forwarding to error page from request [/api/v1/system/ping] due to exception [The request was rejected because the header value "ç��é��" is not allowed.]
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the header value "ç��é��" is not allowed.
...
2023-06-02T02:43:11.881Z [jfac ] [WARN ] [f3570b6fec3d726c] [o.j.c.ExecutionUtils:177      ] [jf-common-pool-1    ] - Retry 20 Elapsed 9.4 secs failed: Registration with router on URL http://localhost:8046 failed with error: UNAVAILABLE: io exception. Trying again
2023-06-02T02:43:16.901Z [jfac ] [WARN ] [f3570b6fec3d726c] [o.j.c.ExecutionUtils:177      ] [jf-common-pool-1    ] - Retry 30 Elapsed 14.41 secs failed: Registration with router on URL http://localhost:8046 failed with error: UNAVAILABLE: io exception. Trying again
...
```

**Comment by memsharded** [comment]
Hi @yijianshuangdiao 

Thanks for your report.
This could happen because of several reasons:
- Try not to run as administrator. I run ArtifactoryCE in Windows, and I don't need Admin permissions for that if I recall correctly
- Your computer might be platformed/provisioned with some company tools (firewalls, antivirus, etc) that are causing the issues. Maybe talk to IT to check it (I would start by trying in my personal computer to check)
- It could be an encoding issue, in that case it might be an issue to report to the JFrog Artifactory team

**Comment by yijianshuangdiao** [comment]
@memsharded Thank you for your response. After encountering the aforementioned problem, I tested the program on another machine (both machines are not connected to the Internet), and it ran smoothly. Therefore, I suspect that the error is caused by a local environment issue, but I am unsure of the specific reasons. Would it be possible to provide a general troubleshooting guide? Is it possible that the problem is related to hardware configuration? I can follow the guide to restore some local settings and gradually identify the issue.

**Comment by memsharded** [comment]
I think you might try the official Artifactory documentation troubleshoot in: https://jfrog.com/help/r/jfrog-platform-administration-documentation/troubleshooting. These kind of issues is often related to java environment.

**Comment by memsharded** [comment]
Hi @yijianshuangdiao 

Any update here? Did you manage to make it work in that machine?

**Comment by yijianshuangdiao** [comment]
@memsharded Thank you for following up on this issue.I still haven't resolved the issue mentioned earlier. I'm currently using ArtifactoryCE on a different machine. If you have any better ideas to try and solve the problem, I can provide more logs. Additionally, I've encountered a new issue where I'm trying to download remote library files using Python's "requests.get(url="http://10.17.22.102:8082/ui/native/...", stream=True)" on another machine in the local network (the remote repository is an ArtifactoryCE local repository running on that machine). I'm receiving an error message saying "sorry but jfrog webapp doesn't work properly without JavaScript enabled. Please enable it to continue." I'm not sure what is causing this request error. If you have any solutions, could you please share them? Thank you very much for your assistance.

**Comment by memsharded** [comment]
> Then I ran artifactory.bat as an administrator(I haven’t done anything else apart from this.)

I certainly don't need to run it as administrator, maybe trying without it?

Also, if you can provide the full log while launching Artifactory on the failing machine, that could help.

> requests.get(url="http://10.17.22.102:8082/ui/native/...", stream=True

You cannot use the Web UI urls for downloads. The recommended way to download things is the right API. For Conan it will be with the Conan client, and for generic repos it will be the URL that you might find there in the UI, that will looks more like https://xxx.xxx.xxx.xx/artifactory/generic/file.txt

**Comment by yijianshuangdiao** [comment]
>I certainly don't need to run it as administrator, maybe trying without it? 

I tried running it without administrator privileges, but I still encountered the same problem.I will take some time later to organize the logs and put them here. Thank you for your help.

The issue with downloading the file using the URL has been resolved.

In addition, the directory structure of the remote repository is as follows:
```txt
--export
--package
     |--e2f5662ef4c3efe47f6cc8ed6a3edc1cb4b1d8a4
             |--1fb09ce617a311cfef924eb779eaad32    ······Ⅰ
                       |--.timestamp
                       |--conan_package.tgz
                                |--xxx
                       |--conaninfo.txt
                       |--conanmanifest.txt
             |--index.json
```
Is it possible to directly download the entire directory through “URL to file” in Ⅰ, and then calculate its hash value using some algorithm (is it MD5?) and compare it with the current hash value to verify the integrity of the downloaded files? If only downloading conan_package.tgz separately, I need to calculate its hash value myself and save it.

BTW, is it possible to change the file extension of conan_package.tgz to .zip?

**Comment by memsharded** [comment]
> Is it possible to directly download the entire directory through “URL to file” in Ⅰ, and then calculate its hash value using some algorithm (is it MD5?) and compare it with the current hash value to verify the integrity of the downloaded files? If only downloading conan_package.tgz separately, I need to calculate its hash value myself and save it.

I don't know, this might be possible via some Artifactory API, but not an expert, might be worth checking the Artifactory docs.
In any case, it is not recommended to download directly these artifacts from the server, as these are internal implementation and storage details. If you want to extract things from Conan, the recommended approach is with ``conan install --deployer=xxxx``

> BTW, is it possible to change the file extension of conan_package.tgz to .zip?

all of these are internal implementation details. You shouldn't be using the ``conan_package.tgz`` directly from the server, and it cannot be changed to .zip, because it is not intended for users usage.

**Comment by yijianshuangdiao** [comment]
For [Package prebuilt binaries](https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.html#package-prebuilt-binaries) I think it’s better to record the url for conan_package.tgz and download it directly via url when the library is needed (using the same directory structure when building the package and integrating the library into the project), without introducing Conan into the project. Otherwise, Conan needs to be maintained on each machine running the project.

**Comment by memsharded** [comment]
> For [Package prebuilt binaries](https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.html#package-prebuilt-binaries) I think it’s better to record the url for conan_package.tgz and download it directly via url when the library is needed (using the same directory structure when building the package and integrating the library into the project), without introducing Conan into the project. Otherwise, Conan needs to be maintained on each machine running the project.

I don't think that is the best way. That is an implementation detail, that depends on very specific knowledge of recipe revision + package id + package revision.
Not to say that you lose all transitivity, and will have to handle it manually. If you have opencv dependency, but you download only the ``opencv`` ``conan_package.tgz``, projects will not be able to link against it, because it will be missing all the transitive dependencies. And ``opencv`` has a few tenths of transitive dependencies, so you will need to download all of them, handle the unzip of the conan_package.tgz (where? there can be issues and collisions in this process), make sure you use the right combinations of ``package_ids`` that matches the exact revisions.

So please don't do that, it is not supported and not recommended.

The recommended ways are:
- Use Conan to ``conan install`` the dependencies. Yes, it needs to install Conan in the machines running the project, but it might be totally worth compared with the effort of doing things manually.
- Generate a Conan agnostic deploy: https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html. With that deploy you can do whatever you want, if you want to put in an Artifactory generic repo, under a friendly name like "windows_x64_sdk_1.1.zip" for consumption, that is fine. But that will not be a Conan package, but your own .zip.

**Comment by yijianshuangdiao** [comment]
Due to some security regulations, I cannot provide all the logs on the testing machine. I will continue to investigate the root cause of the problem, and I will inform you if it can be located. Thank you again for your suggestion.

**Comment by memsharded** [comment]
I am closing this as staled, but please feel free to re-open or create new tickets for any further questions or issues. Thanks for the feedback.
