### ISSUE TITLE
[question] Version range for existing package in the remote cannot be resolved

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#14032]
### What is your question?

I'm experimenting with Conan 2.x and migrated our recipes. Now I have a problem that I cannot solve:

    $ conan install . -s build_type=Debug -pr default -pr:b default
    [...]
    ERROR: Package 'detector-processing-api/[~=4.0.0]@vsdk/stable' not resolved: Version range '~=4.0.0' from requirement 'detector-processing-api/[~=4.0.0]@vsdk/stable, Traits: build=False, headers=True, libs=True, run=False, visible=True' required by 'tensorrt-wrapper/5.0.0@vsdk/stable' could not be resolved.

However, conan search tells me that the package exists (in the remote and in my local cache):

    $ conan search -r vsdk detector-processing-api/4.0.0@vsdk/stable
    vsdk
      detector-processing-api
        detector-processing-api/4.0.0@vsdk/stable

    $ conan2 list detector-processing-api/4.0.0@vsdk/stable
    Local Cache
      detector-processing-api
        detector-processing-api/4.0.0@vsdk/stable

What could be the problem in that case? Why can conan not resolve the dependency?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fschoenm 

This might be related to the new implementation of version ranges.
Have you tried dropping the ``=`` and writing the constraint as ``~4.0.0``?

**Comment by fschoenm** [comment]
@memsharded Thanks, that worked. Seems like the previous implementation allowed both, ~ and ~= for version ranges. Maybe you can think about allowing it again for compatibility reasons :)

**Comment by memsharded** [comment]
Yeah, we need to check that, the previous implementation was from a third party that we dropped because some issues, but lets check if that notation can be supported and make sense.

**Comment by AbrilRBS** [comment]
Hi @fschoenm thanks a lot for your suggestion. The `~=` syntax is most popularly described in [PEP 440](https://peps.python.org/pep-0440/), while other sources prefer the `~` (See [npm](https://semver.npmjs.com/), [rust](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements))
While it's true that Conan _used to_ support this syntax due to its usage of https://github.com/podhmo/python-node-semver/ as @memsharded mentioned, as removing the `=` has the same meaning as the old one, we're therefore unlikely to add this syntax back.

The reasoning comes from a simplification perspective. Having two different ways to express the same idea, specially with something as ill documented as version ranges (I wish semver.org had this in its specification!), can lead users to confusion (I had to double check that there was not just a minor semantic difference between `~`, `~=`) So I think the best approach is to gravitate towards only 1 way to express compatibility, and keeping the currently supported one seems the best path forward :)

Again, thanks a lot for your report, feel free to open more issues if you find any other problems with your Conan 2 exprimentation!
