### ISSUE TITLE
[question] Looking for a way to access to dependencies from configure() or config_options()

### ISSUE THREAD

**Issue by sbouchex** [conan-io/conan#14033]
### What is your question?

Our conandata.yml data is missing "header_only" and standard dependencies. For example:

```
requirements:
  - deps-a/1.0.0@test/stable
  - deps-b/2.0.0@test/stable
```

In config_options(), we need to inject options (i.e. conan options) for standard dependencies only and not for the "header_only" one, so we need to have the list of dependencies and which one has been declared "header_only".

The final result after the injection would look like:
```
requirements:
  - deps-a/1.0.0@test/stable
  - deps-b/2.0.0@test/stable
options:
  - deps-a:option_a=xxx
```

Is there a way to have access to theses structures ?

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sbouchex 

Thanks for your question.

Please note that what you are trying to achieve is physically impossible. These methods are evaluated when the graph is being computed and expanded, they are like the very first method that a recipe evaluates, even before the recipe evaluates the ``requirements()`` method. So at the moment of evaluation, it is not that the dependencies are unknown or not accessible, is that they don't exist at all yet. They might not exist in disk at all. And it is impossible to know which versions or dependencies will be used, because it is common to have conditionals in the ``requirements()`` method based on settings and options.

You might still set options for dependencies without breaking things. Doing a ``self.options["dep-a/*"].myoption=value`` in the ``configure()`` method will try to define that option for dependencies that match, without failing if they don't exist. Note that this is not an absolute priority, if someone else is trying to define that option to a different value, it might have higher precedence.

In any case, note that options are not intended to be used that way, with that level of reasoning, but as an absolute thing. And mostly commanded and defined in profiles. So if I want to build some applications with shared linkage, I would define a ``*:shared=True`` in my profile. But I shouldn't need to know which of my dependencies are header-only to define or not some options to them. Note that when using patterns, if a package doesn't define that options is not an error.

I hope this clarifies a bit.

**Comment by sbouchex** [comment]
@memsharded thanks for the clarification

As options are impacting the hash computation, we wanted to avoid having options on header-only packages at all and only see deps-a having variable options.

One idea is be to split conandata.yaml like:
```
requirements:
  - deps-a/1.0.0@test/stable
requirements_header_only:
  - deps-b/2.0.0@test/stable
```
and manage the data differently in requirements()

**Comment by memsharded** [comment]
> As options are impacting the hash computation, we wanted to avoid having options on header-only packages at all and only see deps-a having variable options.

It is not clear what your problem is, and what are you using options for. You can define options in a header-only package, as soon as it defines the ``self.info.clear()`` in the ``package_id()`` method, it will not affect the hash and package_id, but still the ``package_info()`` can act accordingly. It is certainly unusual but possible.

But maybe it is not necessary. Lets say that those packages have an option called ``myoption``. Just setting ``*:myoption=somevalue`` in a profile or in a ``configure()`` method, will have no effect over those dependencies that do not define the ``myoption`` option.
