### ISSUE TITLE
how to use conan_set_libcxx/CONAN_LIBCXX?

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#1404]
Hi all,

for instance, I want to build my CMake-based project with clang and libc++ (instead of libstdc++).
so I am basically using something like this:
```
conan install .. -g cmake -s compiler=clang -s compiler.version=4.0 -s compiler.libcxx=libc++
cmake .. -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
```
as far as I understand, **conan install** command generates **conanbuildinfo.cmake** with all conan settings applied.

on other side, I have typical CMakeLists.txt which calls **conan_basic_setup**, and it internally invokes **conan_set_libcxx** macro. the problem here is that **conan_set_libcxx** uses variable **CONAN_LIBCXX** which is never set to anything (I see tools.CMake helper sets this value, but CMake generator never does), so **conan_set_libcxx* effectively does nothing.

is it oversight or by intention? if it is by design, what's the workflow of setting **CONAN_LIBCXX** properly, just specify **-DCONAN_LIBCXX=libc++** in CMake command line? that sounds like a wasteful duplication.

**Comment by lasote** [comment]
Hi @SSE4,

The conan install command generates **conanbuildinfo.cmake**, but with the requirements information. 
The build system arguments are managed by the conan build helpers, in this case, the `CMake()` helper (the same way the recipes of your requirements are doing). As you are building your project manually, not build helper is involved, so no one is setting the **-DCONAN_LIBCXX**.

You could create a dummy recipe (hopefully the beginning of a new recipe for your project) and use in the ``build()`` method the ``CMake`` helper. Then, instead of call `cmake .. -G.....` you can call just `conan build` to build your project.

It is the same for the `build_type`, you will need to specify the `-DCMAKE_BUILD_TYPE` or use the right generator for your architecture if you are using Visual Studio, the runtime etc.

We try to differentiate the `conan install` that means, install the requirements with these settings and give me information using this generator, and the building of your own project, that can be managed by your IDE or whatever, if you want to translate the settings into definitions you have the `CMake()` helper.

So every library package has the control about how to build the inner library. I'm wondering if declare some defaults in the `conanbuildinfo.cmake` based on the settings and then be able to override them with the `CMake` helper makes sense, but I'm not sure at all that we want to mix them, furthermore I'm sure I'm missing some more reasons to do it separately. What do you think @memsharded ?

**Comment by SSE4** [comment]
@lasote well, it may sound reasonable, but currently many modern IDEs (e.g. CLion and Visual Studio 2017) are working with CMake-based projects out of the box (you just point IDE where CMakeLists.txt is located, and everything is set up). so while conan build may be suitable for CI cases, for local development that doesn't fit well. if I am supplying libcxx setting to conan install, why not write CONAN_LIBCXX into conanbuildinfo.cmake? this definetely makes things much easier and working out of the box.

**Comment by lasote** [comment]
@SSE4 yes, but that precisely a reason to keep it isolated, if your IDE is telling to your CMakeLists.txt "use libc++" automatically, why conan should interfere there?

**Comment by ErofeevK** [comment]
Hi

It is great topic in general (how to synchronize build system and conan). I also faced with this issue.
The binary packages from conan and my code should be configured in a consistent way. And conan is very good in providing binaries according to options. Usually it is necessary to write some shell script to run conan and cmake in a consistent way. This is inconvenient but acceptable.
When using CLion or latest VS which use `CMakeLists.txt` natively this becomes unacceptable (run conan manually with options take from IDE will be error prone).

I agree, the idea of running cmake and taking configurations from `conanbuildinfo.cmake` is not good at all.

The proposal with additional receipt wrapper is interesting and it is common and useful during conan package development. But this force us to use conan as a build system.
Conan was started as package manager for developers. And that was great. But this proposal turns conan into build system (or meta-build system). Are you going to push conan in this direction? I hope  conan will stay package manager.

So I'd prefer to setup configuration for build system and then force build system to run conan with proper options (i.e. `conan install` is yet another part of build process)   

But how to use conan as a part of build process (i.e. as a configure step of cmake in our case)?  Is possible with conan right now?  Or this is will be not possible due some cmake restrictions? (I cannot realize how to run conan from cmake and than include results back to cmake)

Thank you.

**Comment by lasote** [comment]
> Conan was started as a package manager for developers. And that was great. But this proposal turns conan into build system (or meta-build system). Are you going to push conan in this direction? I hope conan will stay package manager.

Not at all, don't worry about it. But if you are going to write a script to manage your build, maybe you can use also conan for that purpose.

> But how to use conan as a part of build process (i.e. as a configure step of cmake in our case)? Is possible with conan right now?

Do you know the [cmake-conan](https://github.com/conan-io/cmake-conan) project? actually we don't like it... but users consider that calling conan from CMake is a useful thing, so we provided that project.

My personal opinion is that the integration with IDEs (and in general with CMake) should be including different `conanbuildinfo.cmake` from different configurations, maybe managing different run configurations in the IDE or something similar. Similar to the approach we show in the docs: http://docs.conan.io/en/latest/integrations/clion.html

I agree that the IDE integration is not optimal, maybe could be improved with some efforts or customization/plugin from the IDEs to automatically call the "conan install", maybe managing different profiles or something similar, but I still don't see a big pain here, but please, help us to understand.

You only need to call `conan install` command when you change your dependencies or the settings/options, so, if it's a pain for you, it is because:

- Do you change a lot the configuration in the development process?
- Do you have a lot of different configurations?
- Are your dependencies changing very often?
- Don't you want to manage the logic of include one or other conanbuildinfo.cmake?  can it be error prone if you don't automate it?
- Do you prefer to not keep different conanbuildinfo files and perform an install every time?


Thanks!

**Comment by ErofeevK** [comment]
I've checked the `cmake-conan`. This looks like something I expected though not all my colleagues like the solution. 
And probably I can agree,  conan should set up environment as a step before `cmake`.
The pain is because I can forget  (and thus keep in mind about non automated step) to run `conan install` after change something in CLion.

So in general my pain was keeping two lists of options in sync.
My current solution is:
- For local development with CLion use another CMakeLists.txt which rely on `cmake-conan` and wraps original one
- for CI  use script as single point for changing build options.

Thanks!

**Comment by memsharded** [comment]
For further reference about this issue:

``conanbuildinfo.cmake`` now defines variables for all settings, like:

```cmake
set(CONAN_SETTINGS_ARCH "x86_64")
set(CONAN_SETTINGS_BUILD_TYPE "Release")
set(CONAN_SETTINGS_COMPILER "Visual Studio")
set(CONAN_SETTINGS_COMPILER_RUNTIME "MD")
set(CONAN_SETTINGS_COMPILER_VERSION "9")
set(CONAN_SETTINGS_OS "Windows")
```

So the variable ``CONAN_SETTINGS_COMPILER_LIBCXX`` will be there for g++, and can be used by the main project CMakeLists.txt if desired.
