### ISSUE TITLE
[bug] conanfile.conf is always empty

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#14046]
### Environment details

* Operating System+version: Win 10
* Compiler+version: any
* Conan version: 1.60.1
* Python version: 3.10

### Steps to reproduce

have a conan.conf which contains
```
[conf]
user.some.option = True
tools.custom.option = True
```

Then have a conanfile.py which contains the following:

```
self.output.info(f'conanfile.conf = {self.conf}')
if self.conf.get('user.some.option'):
    self.output.info('Custom option is enabled')
```

### Logs

The output is 

```
conanfile.conf = Conf OrderedDict()
```

I expected it to contain something along the lines of 

```
{'user.some.option': True, 'tools.custom.option': True}
```

**Comment by czoido** [comment]
Hi @Sil3ntStorm, thanks for the question.

The problem here is that you are mixing the legacy `conan.conf` with the [new configuration system](https://docs.conan.io/1/reference/config_files/global_conf.html#global-conf).
To make it work, please create the `global.conf` file and add those values to it (no need to add the `[conf]` section in the file, you can just put the values in the file).
Hope this helps.

**Comment by Sil3ntStorm** [comment]
Thanks that works.
