### ISSUE TITLE
[question] how to copy folder from package to the build folder

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14059]
### What is your question?

Hi,

My package has folder with object files. I need to copy it to the build_folder. How can I do it?

```py
class TestPackage(ConanFile):
    name = "test-package"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps"
    requires = "mypackage/1.0"

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()

    def build(self):
        shutil.copytree(os.path.join(mypackage.package_folder,  "object_files"), os.path.join(self.build_folder, "object_files"))
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()
```

Best Regards

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by damian-tomczak** [comment]
I did a mistake: I have to specify that I would like to have access to the folder not only while creating a package from test-package. I want to have this in my build folder after conan install . --output-folder=build --build=missing command in test-package folder.

**Comment by memsharded** [comment]
Hi @damian-tomczak 

Just in case, to manage objects there are already some built-in functionality. The package can declare ``self.cpp_info.objects``, and that information will be automatically consumed by the generators and pulled into the build. The idea is that in general it shouldn't be necessary to do an extra copy of the object files, in the same way it is not necessary to do a copy of static and shared libraries into the project to link with them.  Is there any specific reason you want to do this copy? Are you aware of ``self.cpp_info.objects``?

In general, the access to the dependencies information, and the copy of files should be done in ``generate()``, accessing via ``self.dependencies`` (see https://docs.conan.io/2/reference/conanfile/methods/generate.html):

```python
def generate(self):
      root_folder = self.dependencies["mydep"].package_folder
      copy(self, ...)
```
But, as commented above, this would be discouraged in most "build" cases.

**Comment by damian-tomczak** [comment]
I don't want to link those object files into the library or executable. They are needed to send them into the kernel.
So I think self.cpp_info.objects isn't correct for this case.

**Comment by memsharded** [comment]
> I don't want to link those object files into the library or executable. They are needed to send them into the kernel.
So I think self.cpp_info.objects isn't correct for this case.

Thanks for the clarification. Cause you are kind of "re-packaging" them into the current binary?
In any case, the ``self.cpp_info.objects`` would be a list of the abstract location of the objects, so you can iterate it and copy them, like:
```python
def generate(self):
      for obj in self.dependencies["mypackage"].cpp_info.objects:
              copy(self, src=obj, ...
```
(just the idea, not tested)

If it is slow because thousands of them, then the ``shutil`` would be faster, and you can access it ``self.dependencies["mypkg"].package_folder`` + your folder inside the package.

**Comment by KingKiller100** [comment]
@memsharded 
Shouldn't this be done using the `imports()` stage. I thought the responsibility of that stage is to localize the dependency's artifacts from the cache? So that the consuming project can use them if needed

**Comment by memsharded** [comment]
The ``imports()`` is deprecated in 1.X and it has already been removed in Conan 2.0, so not recommended to use it. The recommendations are:

- For normal usage/linking at development time, leave the artifacts in their packages, consume them with generators from their original location. Testing at run-execution can use ``VirtualRunEnv``
- Deployment is recommended only for extraction of artifacts from Conan packages for final release/deployment outside of Conan. The recommendation is to use custom ``--deployer``. The usage of ``generate()`` in recipes would be an alternative if compatibility with 1.X is necessary.

**Comment by KingKiller100** [comment]
@memsharded 

> The `imports()` is deprecated in 1.X and it has already been removed in Conan 2.0, so not recommended to use it. The recommendations are:

This is very interesting to know. My company still uses the imports function for all our projects to localise non-lib and non-include-files artifacts from dependencies. We are still using v1.60.1 atm but considering upgrading to v2.x at some point 


> * Deployment is recommended only for extraction of artifacts from Conan packages for final release/deployment outside of Conan. The recommendation is to use custom `--deployer`. The usage of `generate()` in recipes would be an alternative if compatibility with 1.X is necessary.

As an example, if my project needs to grab DLL files or redist files or documentation files from one of its dependencies, what are we expected to do?

**Comment by KingKiller100** [comment]
Also, sorry for my naivety but what was the reason for deprecating imports? What version was the deprecation introduced and the alternative method documented?

**Comment by memsharded** [comment]
> what was the reason for deprecating imports?

Several reasons:
- It had a confusing and limited interface. Ok for some simple cases, but not enough for more advanced cases, because the iteration was completely hidden. It is better to have the iteration of ``self.dependencies``, with all the folders, attributes, etc exposed to really control what is being copied. 
- The syntax in ``conanfile.txt`` was specially terrible, even ourselves couldn't write it without reading the docs
- It was being abused for simple build and run tests tasks, instead of correctly defining environment variables like PATH, LD_LIBRARY_PATH, files were being copied around, making things slower. The automatic (but necessary, otherwise accidental re-packaging was a problem) removal of imported files after ``build()`` method was super confusing for users.
- It had some overlap with the ``deploy()`` method, very similar, but still not the same, kind of confusing and redundant for users.
- Was causing repetition of users wanting to copy artifacts from packages to the user space, adding same in all recipes.


> What version was the deprecation introduced and the alternative method documented?

The ``generate()`` method was introduced in Dec 2020 (https://docs.conan.io/1/changelog.html).
The removal of ``imports()`` has been documented in https://docs.conan.io/1/migrating_to_2.0/recipes.html#removed-imports-method since 2022-03-25
