### ISSUE TITLE
[feature] Allow users to specify the remote from which a requirement should be downloaded

### ISSUE THREAD

**Issue by zillemarco** [conan-io/conan#14069]
### What is your suggestion?

Other package managers allow users to specify from which remote a package should be downloaded.

For example, on NPM, if you specify a dependency with `@company_name/dependency_name` it will download that package from the `company_name` remote.

Conan doesn't have such feature and it would be very useful in a very specific scenario (and maybe more?): let's say the same requirement is hosted in more than one remote, `R1` and `R2`. If `R1` is Conan-Index and `R2` a company managed remote (self managed), and we have the same dependency on both remotes there are cases where the installation could have issue:
- if the recipe on `R1` is "old" and does not support Conan v2 yet, while the one on `R2` is Conan v2 ready, the installation could check on `R1` first and error out without even trying on `R2` (this happens to me right now)
- the recipe on `R2` might have been packaged with a configuration more in line with what a company needs, and it stores is in their own remote to speed up builds: if the installation searches on `R1` first, if will find a valid recipe but won't have it precompiled, so it will compile it locally.

A workaround is to use `@user/channel`, but having a "proper" way to tell Conan which remote user for specific requirements would be awesome 🙂 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @zillemarco 

Thanks for your suggestion.

> Conan doesn't have such feature and it would be very useful in a very specific scenario (and maybe more?): let's say the same requirement is hosted in more than one remote, R1 and R2. If R1 is Conan-Index and R2 a company managed remote (self managed)

This scenario is not even recommended. It is not great that the same Conan package can be resolved differently in different repos. For managing this scenario there are different possibilities:
- Use explicit recipe revisions, (via ``requires =`` or lockfiles), so it is deterministic which exact revision will be used
- Use ``--update`` to guarantee that the latest recipe revision found in all repos is fetched.

But in general, I'd recommend avoiding having this setup. For robust and secure usage of ConanCenter recipes, building your own binaries from your own fork is a very extended approach, and we see users quite happy with it. Doing that, you will have only 1 server repository with your binaries, not two of them. Even if you are using binaries from ConanCenter, and you are adding new binaries, the recommended approach is to put all binaries in the same repo. 

> A workaround is to use @user/channel, but having a "proper" way to tell Conan which remote user for specific requirements would be awesome 🙂

Conan 1.X had some remote "tracking" capabilities, and with ``conan remote add_ref`` it was possible exactly that, to define from which remote a given reference is being downloaded. It was removed in Conan 2.0 because it was way more problematic and confusing than the benefit it was supposed to bring. So in principle this is not a feature that will be considered at this moment, it adds more complexity than expected, more rough edges and confusion to users than it seems. 

Please consider avoiding that setup in the first place. Feel free to open a new ticket discussing that setup, the problem that it tries to solve with that setup, so we can talk there about the alternatives.

**Comment by zillemarco** [comment]
Thanks for the feedback @memsharded, much appreciated 🙂

> building your own binaries from your own fork is a very extended approach, and we see users quite happy with it. Doing that, you will have only 1 server repository with your binaries, not two of them.

I don't fully understand what you mean by this 🤔 We are indeed building the binaries for the same version of a package, only with a different configuration, and stroring that in our own registry server, so I don't really get what you mean with `you will have only 1 server repository with your binaries, not two of them` 🤔

**Comment by memsharded** [comment]
The recommended approach for most robust enterprise usage is not mixing binaries retrieved from ConanCenter and your own binaries built in your CI, but extend your CI builds to also build binaries for all your used configurations, even if they already exist in ConanCenter. Then put all the binaries in 1 repo, not 2. So no actual usage of ConanCenter repo in production at all. There are several advantages with this:

- Full control and build from your fork. If you have that CI in place, and one day you need to quickly add a patch to some of your dependencies, do it in your fork, fire the build, and done quickly. If you need the binaries from ConanCenter to be re-built after sending a fix, that can take much, much longer time.
- No confusion or misunderstanding of binaries origin. They always come from your CI. That also guarantees full control over the system setup, down to the compiler patch versions, systems sdks versions, etc.
- As the CI is already in place, because you already are building your own stuff, it typically doesn't require much extra infra setup or configuration, just some more built time initially.
- Perfect tracking of the git commit of your fork producing the packages, and perfect robustness, nothing in ConanCenter like upgrades to recipes and new binaries can break your builds, which will be fully deterministic. The upgrades to include latest changes from the upstream conan-center-index git repo can be controlled (like a merge from upstream, doing a build, putting packages in a temporary repo, launching your builds against that new repo, and only using the new binaries if everything is working fine)

**Comment by zillemarco** [comment]
Thanks for the detailed explanation, I know understand what you mean, and it makes perfect sense as well 🙂 

In fact, that would also allow us to "store" all the needed prebuilt packages that we need for our builds, which are not always present on conan center 🙂

**Comment by memsharded** [comment]
> In fact, that would also allow us to "store" all the needed prebuilt packages that we need for our builds, which are not always present on conan center 🙂

yes, exactly. Explicitly creating the binaries you need for third-parties, as a pre-condition for the rest of the builds, makes things fast, robust and predictable.

**Comment by zillemarco** [comment]
Hi @memsharded, I have a little update on what you suggested, and a couple of questions 😅 

What I tried to set up now works like this:
- I have a repo where I store a `conanfile.txt` for each dependency we have
- In our CI I run `conan install ...` for each one of the dependencies with our own configurations that changed (I detect those using Git)
- After the `conan install ...` finishes, I use `conan upload * ...` to upload all the local cached packages to our own remote

My idea was using Conan center as the source for the recipes because all the ones we need are already there, and we don't need to customize them in any way at the moment.

But this method as shortcomings:
- Let's say I have `lib_a` that depends on `lib_base`
- The first time I build `lib_a`, this will download and build `lib_base` and then upload both `lib_a` and `lib_base` to our remote
- If I then change `lib_a` again, `lib_base` would already be present in our remote, but it will build it again using the recipe on conan center instead of trying to fetch the matching configuration from our remote

Is this setup "correct" in your opinion or can it be improved?

Another idea I have, which would solve the issue I described above, would be to ditch conan center as a repository for the recipes and "copy" those to our own repository, but that would mean managing all the dependency tree, not only the direct ones, which would be a hassle 😓

**Comment by memsharded** [comment]
> I have a repo where I store a conanfile.txt for each dependency we have
In our CI I run conan install ... for each one of the dependencies with our own configurations that changed (I detect those using Git)

Why would you have this? Why not just one conanfile.txt for all dependencies?

> My idea was using Conan center as the source for the recipes because all the ones we need are already there, and we don't need to customize them in any way at the moment.

It is fine if you don't customize them at all. It is the control and knowing that you can customize them at any moment with 0 efforts, what is important.

Maybe this could help:

- The idea is that you don't have the ``conancenter`` remote at all. Remove it from your conf (you can do it with the remotes files and ``conan config install``)
- The idea of having a ``conanfile.txt`` or similar with all the dependencies you need is good.
- The best way to avoid order issues is to do a ``conan export`` of each one first. Then once all are exported, the ``--build=missing`` will work without issues

I have a small proof of concept in my repo branch:  https://github.com/memsharded/conan-center-index/tree/mycustom

- My ``mypkgs.list`` is the list of packages and versions I need to create. It is fine to have multiple versions of the same recipe
- The ``myprofiles`` folder contains the folder of the configurations profile I want to build
- The ``mybuild.py`` is a simple script that will do the export + build missing + upload

Note that the process is quite simple, but it is also very efficient, thanks to Conan model of revisions and binaries, it will not build binaries that you have already built and uploaded to your own private repo, so if there are no changes in recipes, it will be quite fast.

Please let me know if this makes sense and if you have any question.

**Comment by zillemarco** [comment]
Thanks a again for your explanation @memsharded 🙇 I really appreciate it 🙂 

> Why would you have this? Why not just one conanfile.txt for all dependencies?

Because I want to be able to install/build only the dependency (and its dependencies) that I change, not all the ones I have. Does it make sense? 🙂 I know that it wouldn't build them if the package already exists, but it would still download the prebuilt ones even if not needed 🙂 

> I have a small proof of concept in my repo branch...

This example really helps a lot to understand the concept, thank you!

I do have a couple of questions though:
- You mentioned that I can ditch the conancenter remote completely, and that's fine, but that also would require a for of conan-center-index, like you have on the example, right?
- Why do you need to run `conan export` before doing the `conan install`? 🤔

**Comment by memsharded** [comment]
> Because I want to be able to install/build only the dependency (and its dependencies) that I change, not all the ones I have. Does it make sense? 🙂 I know that it wouldn't build them if the package already exists, but it would still download the prebuilt ones even if not needed 🙂

I am afraid still not clear... I'd need a bit more to understand, like clarify 1 conanfile.txt containing only 1 requires? 1 conanfile.txt for each subfolder, but with multiple requires? How are they used?

> You mentioned that I can ditch the conancenter remote completely, and that's fine, but that also would require a for of conan-center-index, like you have on the example, right?

Yes, exactly you operate from a fork, that you have full control over it. You can still merge it from the upstream whenever you want, and fire a new build to create updated binaries, but you are the one deciding when and how, and how to validate it, not being forced everytime that something changes in ConanCenter

> Why do you need to run conan export before doing the conan install? 

To not care about the order. ``conan export`` works irrespective of the order. If you have ``yourapp -> boost -> openssl -> zlib``, you would need to be careful to build first zlib, then openssl then boost, in the right order, or something can be inconsistent. If you export them all first, then it doesn't matter, and ``install --build=missing`` will work fine.

**Comment by zillemarco** [comment]
> To not care about the order

Oooh, I see 👍 🙂 

> I am afraid still not clear... I'd need a bit more to understand, like clarify 1 conanfile.txt containing only 1 requires? 1 conanfile.txt for each subfolder, but with multiple requires? How are they used?

What I wanted to set up is exactly what you described. My structure would be somewhat like this:
- `dependencies`
  - `boost`
    - `conanfile.txt` with the required boost version
  - `openssl`
    - `conanfile.txt` with the required openssl version
  - `zlib`
    - `conanfile.txt` with the required zlib version

This way when, for example, we want to bump the required version of `boost` we'd change the `conanfile.txt` for that requirement.
Using Git diff I can know which dependency got bumped and only build that and its eventual dependencies, without building all our dependencies.
It is true that if a dependency is already in our cache, even if we try to rebuild it, it won't because it's already there, but the `conan install` command would still download it locally without any need for it.

Does this better explain what I'm trying to achieve @memsharded? 🙂

**Comment by memsharded** [comment]
> Does this better explain what I'm trying to achieve @memsharded? 🙂

Yes, it is more clear.
However it seems it is more general to have just 1 file with all packages and versions. Because eventually you will have 2 different projects, one of them needs to keep working with boost/1.80 and the other will need boost/1.81. So it is not only that you want 1 boost version. The approach that I described with 1 ``mypkg.list`` file could contain:
```
boost/1.80
boost/1.81
zlib/1.2.12
zlib/1.2.13
...
```
And the process will work to create/update those versions too (plus it is easier and cleaner to maintain just 1 file)

**Comment by zillemarco** [comment]
> plus it is easier and cleaner to maintain just 1 file

That is definitely a bonus 🙂 

Thanks for your advice @memsharded, I'll go with your suggestion and see how impactful the "unnecessary" `conan install` for deps that don't need to get updated even though, in all honestly, updating deps doesn't happen that often so we could do with a little overhead in favor of a easier to maintain workflow 🙂 

Thanks you so much once again. I'll let you know how it plays out! 🙇 🙂

**Comment by memsharded** [comment]
Excellent!

I am going to close the ticket as responded at the moment, no further action necessary from our side.

But please, re-open it when you have further insights, feedback, or want to discuss something more (if the topic is different enough, better create a new ticket and follow up there).

Thanks very much to you for all your feedback! 🙂

**Comment by zillemarco** [comment]
Sorry @memsharded, only one last question (famous last words 😅) 🙂 

I set up the project like in your example, and it's looking promising but I encountered a little issue that I want to get feedback before banging my head too much on the wall coming up with the wrong approach 😅 

Like you suggested, I removed (disabled actually) the `conancenter` remote, but how would the `conan install` comman run for one of our direct dependecies find the recipe for one of the derived dependencies? 🤔 

Take `libcurl` as an example: we depend on that library so it's in the list of packages to compile, and that package depends on a few others, for example `openssl`. Runnin `conan install` for `libcurl` fails because it cannot find `openssl` in any remote (because we removed `conancenter`).

So, two options I though of:
- add **all** the dependency tree to the list of packages to build
- use `conan graph` to "scan" our direct dependencies and find out what other dependencies we have to build at "runtime"

What is your advice for this situation? 🙂

**Comment by memsharded** [comment]
In purity the first one, but in practice you can leverage the second option to reduce a bit the manual work:

- You can easily scan with ``conan graph info --requires=libcurl/version`` (against ConanCenter, for quick resultes)
- And then copy & paste the result in the list of packages to build (without ConanCenter, for being self-contained)

In practice, the list of third parties, including transitive dependencies is not that large in practice, so maintaining the list of all deps including third parties is not a big deal.

Also, we are working on some ideas trying to improve this flow, not sure if they will move forward, but we are on it.
