### ISSUE TITLE
[question/support] Installing Qt, using Conan 2 and cmake

### ISSUE THREAD

**Issue by Womps** [conan-io/conan#14098]
### What is your question?

Hi !

Hope you all are well :)

I'm trying to create a simple Windows app, using Qt (6.5.0), conan, and cmake. I've disabled opengl, as I don't need it.

When I try to install and build a simple program, with cmake as a build tool, which just write "Hello World", without including the Qt library in conan, it works. I can execute my HelloWorld.exe, and it works. But when I add the Qt library in my conanfile.py, everything goes wrong. So I'm looking for some help here, to find what am I doing wrong.

When I'm doing a `conan install . -of build`, conan says "Missing prebuilt package for [...] qt/6.5.0 [...]"

To fix this problem, I added --build=missing at the end of my conan install command.

But, with the command `conan install . -of build --build=missing`
When conan tries to do a "RUN: cmake [...]", on the first library that needs to be built, I got a 'cmake' is not recognized as an internal or external command error in my cmd prompt, and it stops. 

As I can see that cmake is installed, in the requirements. The only thing I can see is that the cmake path is not added in the path automatically, like when I'm building my app without Qt. But I don't understand why...

I just wanted to notify that, I tried to install cmake directly on my Windows, and as I was expecting, it works, when cmake is in the system path. I was expecting that if conan had cmake in its requirements, then it would use it to build dependencies ?

This is my conanfile.py :

```
from conan import ConanFile
from conan.tools.cmake import CMake


class HelloWorldRecipe(ConanFile):
    name = "HelloWorld"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"

    def configure(self):
        self.options["qt"].opengl = "no"

    def requirements(self):
        self.requires("qt/6.5.0")

    def build_requirements(self):
        self.tool_requires("cmake/3.25.3")
        
    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Womps 

Thanks for your question. I'll try to clarify the behavior:

- When a recipe like yours add ``self.tool_requires("cmake/3.25.3")``, it is a "private" requirement, intended exclusively for the current package. Other packages can use other build systems, different versions of CMake etc. (Note, in general it might be better to define ``self.tool_requires("cmake/[>=3.25.3 <4]")``)
- Recipes in ConanCenter assume the basic toolchain is installed in the system, that is compiler + CMake>=3.15. Recipes that require a more modern CMake will have a explicit ``tool_requires``, but not all recipes in ConanCenter explicitly add a tool_requires to ``cmake`` because it is assumed as a system tool.
- Indeed, if you dont have cmake installed in the system, then, some recipes in ConanCenter will fail to build from sources.

There is a way you can "inject" tool_requires to your dependencies, adding this section in your profile:
```
include(default) 
# or define your own settings, instead of including default
[tool_requires]
cmake/[>3.25 <4]
```
And then passing the profile in command line ``-pr=myprofile`` argument.

Please let me know if this helps.

**Comment by Womps** [comment]
Ok, I see, it makes sense, now :) cmake is now installed in the system, so it works ;)

Thank you for the clarification !

**Comment by memsharded** [comment]
Happy to help :)

I am closing this ticket as responded, but please don't hesitate to re-open or create a new ticket for any further question. Thanks!
