### ISSUE TITLE
[feature] Allow customizing CMAKE_GENERATOR_TOOLSET in CMakeToolchain

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#14100]
### What is your suggestion?

Currently, it's not possible to customize `CMAKE_GENERATOR_TOOLSET`. It's only possible to influence toolset architecture via `tools.cmake.cmaketoolchain:toolset_arch`, but not the toolset itself.

Furthermore, if using `clang`, conan hardcodes `CMAKE_GENERATOR_TOOLSET` to `ClangCL`, which is correct only in case when using Clang provided by Visual Studio installation.

However, when dealing with custom LLVM toolchains, specifically those packaged into a conan package, we need the ability to define a custom toolset.

My current workaround is to have a custom command that patches the generated `conan_toolchain.cmake`.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DoDoENT 

Thanks for the feedback. I am trying to follow up on some tickets related to the Clang toolset.

Since then, Conan has learned the new ``tools.cmake.cmaketoolchain:extra_variables`` that allows to define any CMake variable, and as this block happens later than the others, I think it might be able to override and define the ``CMAKE_GENERATOR_TOOLSET`` too. Have you tried this new feature?

**Comment by DoDoENT** [comment]
In the meantime, we stopped supporting ClangCL and while we did, the workaround I had worked OK.

I think we can close this now, as it's no longer relevant for us, and also, as you said, using `extra_variables` may indeed work in case somebody else finds this GitHub issue searching for the solution for same/similar problem.

**Comment by memsharded** [comment]
Thanks for the feedback!

**Comment by parched** [comment]
If anyone else comes across this and wonders why something like this doesn't work
```
    def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["CMAKE_GENERATOR_TOOLSET"] = "fortran=ifx"
        tc.generate()
```
it's because `tc.variable` sets a `CACHE` variable after it has already been set without using `FORCE`.

Try this instead
```
    def generate(self):
        tc = CMakeToolchain(self)
        tc.blocks["generic_system"].values["toolset"] += ",fortran=ifx"
        tc.generate()
```

**Comment by kambala-decapitator** [comment]
> Since then, Conan has learned the new tools.cmake.cmaketoolchain:extra_variables that allows to define any CMake variable, and as this block happens later than the others, I think it might be able to override and define the CMAKE_GENERATOR_TOOLSET too. Have you tried this new feature?

@memsharded thanks, this does work to override the toolset. For example, to reset it to the VS default, empty string should be used:
```
-c tools.cmake.cmaketoolchain:extra_variables="{'CMAKE_GENERATOR_TOOLSET': ''}"
```

But there're a few inconsistencies with such workaround:
1. the generated presets file doesn't contain the changed `CMAKE_GENERATOR_TOOLSET` and the toolset section still contains the original one
2. CMake configure output still shows message `Conan toolchain: CMAKE_GENERATOR_TOOLSET=<original value>` - it's just a message, but may confuse a user

In my case I have the following in the profile that is used to build project dependencies:
```
compiler.update=9
compiler.version=192
```

but locally I have just VS 2026 (v145 / 195) that I want to build project and consume its dependencies. And so the generated presets have
```
"toolset": {
    "value": "v142,version=14.29",
    "strategy": "external"
}
```

The proper way to use my local VS / toolset is
```
-s "&:compiler.version=195" -s "&:compiler.update=~"
```

but end users may find it difficult to use as they need to figure out the proper version instead of 195 for their environment.

**Comment by memsharded** [comment]
What about ``compiler.toolset``? At the moment it only contains values for legacy xp toolsets, but adding more values with ``settings_user.yml`` could allow to explicitly define the desired toolset, if the computed one is not desired?

**Comment by kambala-decapitator** [comment]
> What about `compiler.toolset`? At the moment it only contains values for legacy xp toolsets, but adding more values with `settings_user.yml` could allow to explicitly define the desired toolset, if the computed one is not desired?

thanks, such approach also works (`-s "&:compiler.toolset=v145"`). But this is not much different from
```
-s "&:compiler.version=195" -s "&:compiler.update=~"
```
and the same also applies:
> but end users may find it difficult to use as they need to figure out the proper version instead of 195 for their environment.

besides, a user has to create an additional file.

I'm looking for ways to simplify project setup for other external devs, especially since most of them don't even know what Conan is, but without copy-pasting a lot of Conan documentation. And the amount of "magic" numbers required to be used (and explained) in MSVC / VS case is kinda annoying, since average dev only knows that his VS is "2022" or "2026". I'm actually thinking that a script is needed that will infer all this info from environment automatically to be a no-brainer setup.

**Comment by memsharded** [comment]
The thing is that VS has a few different knobs and tweaks, like it is possible to install different toolsets in different IDE versions, etc.

But typically the idea is that users only have to do ``conan config install/install-pkg`` to retrieve a set of configurations, including profiles. Those profiles can also use the ``detect_api`` and the jinja2 syntax to implement some variability, including detection of different visual studio settings. Is the variability that large in your organization that cannot be represented by some profiles with the detect_api and jinja?

**Comment by kambala-decapitator** [comment]
> Those profiles can also use the `detect_api` and the jinja2 syntax to implement some variability, including detection of different visual studio settings

nice, thanks for pointing to that! Seems it's indeed an elegant solution: simply have the following in profile:
```
{% set compiler, version, _ = detect_api.detect_default_compiler() %}
&:compiler.version={{ detect_api.default_compiler_version(compiler, version) }}
```

> But typically the idea is that users only have to do conan config install/install-pkg to retrieve a set of configurations, including profiles
> Is the variability that large in your organization that cannot be represented by some profiles with the detect_api and jinja?

it's not about an organization, I'm working on an open-source project that uses Conan to provide prebuilt binaries for anyone willing to participate (as a fast way to get started on the project). And of course we have no idea about environment of each dev, we only know that the minimum possible working toolset is v142 (our CI uses it to produce Windows 7-compatible dependencies and builds) and we provide respective profiles. Telling people "hey, install v142 or even VS 2019" doesn't really sound wise and my expectation is that all should work with default toolset, e.g. from VS 2022 or 2026.

here are the profiles in case you are interested: https://github.com/vcmi/vcmi-dependencies/tree/main/conan_profiles
