### ISSUE TITLE
GENie Support

### ISSUE THREAD

**Issue by Type1J** [conan-io/conan#1410]
The GENie build system is used by a good number of projects including MAME. I'd like to use Conan in a large existing codebase to remove some embedded dependencies, but I'd like a file to be generated that contains the include and libs simmilar to the cmake generator in Conan.

https://github.com/bkaradzic/GENie

Please leave a comment linking to docs or source lines that might help me create such a generator myself.

**Comment by memsharded** [comment]
Hi @Type1J 

You can find about how to create your own generators here: http://docs.conan.io/en/latest/integrations/other.html#create-your-own-generator

It is easy to start creating them, because they can be managed as packages, check http://docs.conan.io/en/latest/howtos/dyn_generators.html#dyn-generators but I am not opposed to integrate it as a built-in generator to conan, so if you are more confortable working in a conan fork, it is fine too. 

Please ask if you need more help during the process. Many thanks!

**Comment by Type1J** [comment]
Thanks!

**Comment by memsharded** [comment]
Hi @Type1J 

Did you manage to create a generator for GENie? Would you like some help with it?
Also, if it is something you want to share, we could consider adding it to the conan codebase.

Thanks!

**Comment by Type1J** [comment]
I was asked to help with another project, and I haven't made it back to this one, yet. I'll let you know when I get around to it. If you know anyone else intrested in adding support, then please encourgage them to do so.

**Comment by anton-matosov** [comment]
> Since `Conan 1.9.0` the `premake generator` is built-in and works with `premake5`
https://docs.conan.io/en/latest/integrations/premake.html
That can be a good starting point as `GENie` is a fork of `premake`

**Comment by memsharded** [comment]
Seems this never got enough support/requests, closing, thanks
