### ISSUE TITLE
[question] clarification about using "[imports]" in Conan 2

### ISSUE THREAD

**Issue by penguin-madagascar** [conan-io/conan#14103]
### What is your question?

I am a beginner of Conan, and I am using Conan to manage my own pre-built binary packages. I want to move all "*.dll" files in the downloaded package to where my executable is.

I notice that in the document, Conan 2 has intergrated "[imports]" in _conanfile.txt_ into generator(self), this is the _conanfile.py_ I wrote:
```
import os
from conan.tools.files import copy
from conan import ConanFile

class CompressorRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"

    def requirements(self):
        self.requires("mypkg/1.0")

    def generate(self):
        for dep in self.dependencies.values():
            copy(self, "*.dll", dep.cpp_info.libdirs[0], self.build_folder)
```

after executing `conan install . `, I can't find any dll files in local directory, how do I fix this?

Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @penguin-madagascar 

Thanks for your question.

First one note: If you are "importing" the dlls to the local folder, note that the generated files like ``conanbuild.bat`` and ``conanrun.bat`` will still point to the local cache folder. If you want to have them pointing to a local copy, you might want to "deploy" the files from dependencies, have a look: https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html

Then, your code is not copying anything, because *.dll in Windows packages are located inside ``bindirs``, not ``libdirs``. So doing this works:
```python
for dep in self.dependencies.values():
      copy(self, "*.dll", dep.cpp_info.bindir, self.build_folder)
```

If you need to investigate what is happening, the easiest is just to add some prints:
```python
for dep in self.dependencies.values():
      print("BINDIR PATH", dep.cpp_info.bindir) # Or libdir in your case, and you will see it doesn't contain any *.dll
      copy(self, "*.dll", dep.cpp_info.bindir, self.build_folder)
```

You can also easily inspect the packages, call:
```bash
$ conan cache path zlib/1.2.13:f7dcd1cec4586c154a242a765a1de011300db8e2
/path/to/package/in/cache
```
So you can go to the folder and inspect the files there (read-only, do not modify them)

**Comment by penguin-madagascar** [comment]
Thank you so much!
