### ISSUE TITLE
[bug] Duplicate Version comparison unittests

### ISSUE THREAD

**Issue by jputcu** [conan-io/conan#14112]
### Environment details

I've noticed there is a large overlap between `/conans/test/unittests/model/version_test.py` and `conans/test/unittests/model/version/test_version_comparison.py`.

I can make the changes and create a pull request?

**Comment by AbrilRBS** [comment]
Hi @jputcu thanks a lot for your proposal, we would love it if you did this yes!

Only 1 note: make sure to keep test cases that check for regressions, or make it explicit in what test they end up from, they are usually marked by a link to a gh issue or a message explaining the reason for the tests :)

Let us know if we can help you in any way!

**Comment by memsharded** [comment]
Yes, be aware that even in the surface they look very similar, they are testing different aspects, for example one is testing ``_VersionRepr`` internal helper, which ``assert vr.major() == "1.Y.Z"``, and the other is testing ``assert minor == 2`` (coming from ``v.minor, without () because in this case it is a property, and not ``Y``). Those are different functionalities used in different places.

**Comment by jputcu** [comment]
@memsharded Currently I've kept the tests related to `_VersionRepr` in the original file. Will take it step by step.

**Comment by jputcu** [comment]
@memsharded  Currently, `"+build2"` doesn't generate a valid `Version` object, new test is failing.
Is it suppose to fail, because there is a test with `_VersionRepr` which uses this?

**Comment by memsharded** [comment]
``_VersionRepr`` might be a bit more permissive than ``Version``, which could be unnecessary. I think that ``+build2`` alone is a non allowed version.
