### ISSUE TITLE
[bug] CMakeToolchain: CMAKE_SYSTEM_PROCESSOR and CMAKE_SYSTEM_NAME not set properly

### ISSUE THREAD

**Issue by nicosmd** [conan-io/conan#14126]
### Environment details

* Operating System+version: Ubuntu 20.04
* Compiler+version: gcc 10.2
* Conan version: 2.0.6
* Python version: 3.10.9

### Steps to reproduce

Hey, 

I encountered the issue described in this issue: #13914

When I use a toolchain package with a `package_info` method looking like

```python
  def package_info(self):
      self.buildenv_info.append_path("PATH", join(self.package_folder, "bin"))

      vars = {
          "CC": "aarch64-linux-gnu-gcc",
          "CXX": "aarch64-linux-gnu-g++",
          "LD": "aarch64-linux-gnu-ld",
          "AS": "aarch64-linux-gnu-as",
          "AR": "aarch64-linux-gnu-ar",
          "STRIP": "aarch64-linux-gnu-strip",
          "RANDLIB": "aarch64-linux-gnu-randlib",
          "NM": "aarch64-linux-gnu-nm",
      }

      for env_var, value in vars.items():
          app_path = join(self.package_folder, "bin", f"{value}")
          self.buildenv_info.define(env_var, app_path)

      self.conf_info.define("tools.cmake.cmaketoolchain:system_name", "Linux")
      self.conf_info.define("tools.cmake.cmaketoolchain:system_processor", "aarch64")
      self.conf_info.define("tools.build:compiler_executables", {"c": vars["CC"], "cpp": vars["CXX"]})
```
using a profile similar to

```
[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=10.2
os=Linux

[tool_requires]
toolchain/1.0
sysroot/1.0
```

the conan_toolchain.cmake contains

```
...
# Cross building
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
```
, which is as expected.

But as far as I add 

```
[conf]
tools.cmake.cmaketoolchain:user_toolchain = ['{{ os.path.join(profile_dir, "extras", "toolchain_extras.cmake") }}']
```
to the profile, both variables aren't set anymore in the conan_toolchain.cmake.
The toolchain_extras.cmake basically contains only some project specific variables, nothing special. 

In both cases
```
...
set(CMAKE_C_COMPILER "aarch64-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "aarch64-linux-gnu-g++")
```

is set properly.

What could I do wrong?

Thanks!

**Comment by memsharded** [comment]
Hi @nicosmd 

The current definition of CMAKE_SYSTEM_NAME is:

```python
 def _get_cross_build(self):
        user_toolchain = self._conanfile.conf.get("tools.cmake.cmaketoolchain:user_toolchain")
        if user_toolchain is not None:
            return None, None, None  # Will be provided by user_toolchain
        system_name = self._conanfile.conf.get("tools.cmake.cmaketoolchain:system_name")


def context(self):
        system_name, system_version, system_processor = self._get_cross_build()
        ...
        return {"toolset": toolset,
                "generator_platform": generator_platform,
                "cmake_system_name": system_name,
```

So it seems this is by design. Once the ``user_toolchain`` is provided, it is expected to control those variables directly to avoid having to define extra ``confs`` in Conan maybe, in the original PR: https://github.com/conan-io/conan/pull/10856/files


But it is true that if the ``tools.cmake.cmaketoolchain:system_name`` is defined, why not just use it? I'll bring the issue to the team to discuss the current behavior and if it can be changed.

**Comment by memsharded** [comment]
It seems that it makes sense to listen to ``system_name`` in all cases, even if ``user_toolchain`` is defined, lets fix it.

**Comment by fschoenm** [comment]
Lucky that I found this ticket. I just ran into the same issue when experimenting with packaging Clang (see #14542). In that case, the same package can be used for (cross)compiling to different target architectures and because of that, an included toolchain file cannot even know the correct system processor/name.

**Comment by memsharded** [comment]
Here goes the PR for it https://github.com/conan-io/conan/pull/14556, for next 2.0.10
