### ISSUE TITLE
[question] How to extract resources from a conan package?

### ISSUE THREAD

**Issue by mildsenseofdoom** [conan-io/conan#14143]
### What is your question?

I have a conan package which has some resource files in it, and I can see them in conan's cache. Is there any way I can either (i) ask conan to extract those files somewhere (I'd have thought this would/could happen with `conan install`?) or (ii) give me the path to them within the cache so I can see them/copy them out? Preferably the former so there's no chance of changing what's in the cache.

The `conanfile.py` is something like:

```py
class EthSoaRelConan(ConanFile):
    # Name, version etc...

    exports_sources = "share/*"
    no_copy_source = True

    def package(self):
        copy(self, "share/important-file-i-want-to-get-out", self.source_folder, self.package_folder)

    def package_info(self):
        self.cpp_info.bindirs = []
        self.cpp_info.libdirs = []
        self.cpp_info.includedirs = []
        self.cpp_info.resdirs = ["share"]
```

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @johngavingraham thanks a lot for your question.

This seems like a perfect fit for deployers, [see their docs here](https://docs.conan.io/2/reference/extensions/deployers.html), which are exactly what you need, 
_a mechanism to facilitate copying files from one folder, usually the Conan cache, to user folders_, and can be run in `conan install` or in `conan graph info`.

For your specific user case, you'll want to create a custom deployer, [see an example here](https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html), and maybe take inspiration from [the `full_deploy` built-in one's code](https://github.com/conan-io/conan/blob/release/2.0/conan/internal/deploy.py#L48), but instead of copying the whole package, only target your specific needs. Note that you can then use `--deployer-folder` to tell Conan where to put the resulting files (Will be passed as `output_folder` named argument to your deployer function)

Let me know if that helps, else feel free to ask should you find any more issues :)

**Comment by johngavingraham** [comment]
> Hi @johngavingraham thanks a lot for your question.
> 
> This seems like a perfect fit for deployers, [see their docs here](https://docs.conan.io/2/reference/extensions/deployers.html), which are exactly what you need, _a mechanism to facilitate copying files from one folder, usually the Conan cache, to user folders_, and can be run in `conan install` or in `conan graph info`.
> 
> For your specific user case, you'll want to create a custom deployer, [see an example here](https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html), and maybe take inspiration from [the `full_deploy` built-in one's code](https://github.com/conan-io/conan/blob/release/2.0/conan/internal/deploy.py#L48), but instead of copying the whole package, only target your specific needs. Note that you can then use `--deployer-folder` to tell Conan where to put the resulting files (Will be passed as `output_folder` named argument to your deployer function)
> 
> Let me know if that helps, else feel free to ask should you find any more issues :)

**Comment by mildsenseofdoom** [comment]
Thanks @RubenRBS, I totally missed them when reading the docs - will give that a go and let you know!

**Comment by mildsenseofdoom** [comment]
@RubenRBS, that was indeed what I needed, and after playing for a bit I found that actually doing a `full_deploy` was enough for what we wanted so no need for custom anything, which is nice. Thanks for the help :)

**Comment by AbrilRBS** [comment]
Great to hear! Feel free to open more issues  in the future should you have any more questions :)
