### ISSUE TITLE
[question] Committing lockfiles to repositories

### ISSUE THREAD

**Issue by aander80** [conan-io/conan#14150]
### What is your question?

Hello,

I am wondering what your view on committing lockfiles to (Git) repositories is? The idea would be that you commit a set of dependencies that you know is stable, so that you at any point in time can return to a commit and build it effortlessly without having to download lockfiles from another source. A downside is of course that this can potentially hinder you from testing the latest versions of packages, to know if something breaks or not, although this can be avoided by having a CI job that actively ignores the lockfile.

In e.g. Poetry, it is recommended to commit lockfiles to VCS (https://python-poetry.org/docs/basic-usage/#committing-your-poetrylock-file-to-version-control), do you think this is a bad approach for conan?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aander80 

Thanks for your question.
In Conan 1.X, definitely no. Lockfiles in 1.X are quite complicated, and need multiple files to lock different configurations, and that is quite a burden.

In Conan 2.0, one single lockfile file can lock multiple configurations. For typical "consumer" projects, that use dependencies, but do not create packages themselves, it should be pretty straightforward to commit a lockfile in the git repo and use it (by default ``conan install`` and other commands will use a ``conan.lock`` lockfile file if present)

When creating packages for that project, the situation is a bit more complicated, because the problem is more complicated. See for example the difference in package.lock and shrinkwrap in NPM. It might still be possible to commit a local lockfile in the repo, but the problem is that this repo doesn't work in isolation anymore, and downstream dependencies might have a different lockfile. Keeping these things in sync is challenging, and typically requires a big effort in CI. Conan 2.0 has developed some tools and flows for CI at scale with lockfiles, still pending to document.

**Comment by aander80** [comment]
Thank you for your reply! I will have a look at the NPM suggestions! Keeping the package dependencies in sync for different repos in CI is not something I had considered, apart from the case where we test everything latest (i.e. ignoring lockfiles) in addition to using committed lockfiles, will have to see if we can figure something out whenever I find the time for it...

Closing this for now, can re-open if needed.
