### ISSUE TITLE
[question] Cannot store package build with different profiles in local cache.

### ISSUE THREAD

**Issue by DmitriiBurnaev** [conan-io/conan#14155]
I have a local recipe for oatpp package.
I also have 2 profiles for Release and Debug build types.
_clang16deb_
```
[settings]
arch=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=16
os=Linux

[buildenv]
CC=/usr/bin/clang-16
CXX=/usr/bin/clang++-16
```

_clang16rel_
```
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=16
os=Linux

[buildenv]
CC=/usr/bin/clang-16
CXX=/usr/bin/clang++-16
```

The only difference is a build type.
I want to have both Release and Debug versions of package in the local cache.

I build them the next way:
```
conan create . --profile:host=clang16rel --profile:build=clang16rel
conan create . --profile:host=clang16deb --profile:build=clang16deb
```

After building 'deb' version. when I try to use 'rel' version, conan says that there is no suitable package, please build it.

After rel build I see the next output:
```
conan list oatpp/1.3.0.45:* -c
Local Cache
  oatpp
    oatpp/1.3.0.45
      revisions
        b1467203440e0cca2e25d62cefb37985 (2023-06-22 18:47:14 UTC)
          packages
            b52fea044570951589640efb5ffff507f4980dc2
              info
                settings
                  arch: x86_64
                  build_type: Release
                  compiler: clang
                  compiler.cppstd: 20
                  compiler.libcxx: libstdc++11
                  compiler.version: 16
                  os: Linux
                options
                  shared: False
```

After deb build:
```
conan list oatpp/1.3.0.45:* -c
Local Cache
  oatpp
    oatpp/1.3.0.45
      revisions
        0fefe92f65c0f0a26451e16152ff20a4 (2023-06-22 18:45:16 UTC)
          packages
            0f83a2fbbe4b4434759a125ad2ef60c421067895
              info
                settings
                  arch: x86_64
                  build_type: Debug
                  compiler: clang
                  compiler.cppstd: 20
                  compiler.libcxx: libstdc++11
                  compiler.version: 16
                  os: Linux
                options
                  shared: False
```

What do I do incorrect? I expect that both packages should be available.

Thank you in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @DmitriiBurnaev 

Thanks for your question.

The problem here is the ``recipe revision``. You are not exporting the same thing for both configurations. It is likely that your ``exports`` is too permissive (you can see the files exported in the output message, and also with ``conan cache path`` you can inspect the actual files that have been exported.

This could be a similar effect that the one explained in https://docs.conan.io/2/knowledge/faq.html#error-obtaining-different-revisions-in-linux-and-windows. If the exported files are different, it is a new thing, under a new ``recipe revision`` and it requires new binaries. You can also list all existing revisions with ``conan list mypkg*#*``, and for each one you can list its binaries with ``conan list mypkg/*#myrevision:*``

Please let us know if this helps.

**Comment by DmitriiBurnaev** [comment]
Hello @memsharded 

Thank you for your help!
It helped!

**Comment by memsharded** [comment]
Great, if that answers the question, I am closing this ticket as solved, but don't hesitate to re-open or create new tickets for any further questions. Thanks!
