### ISSUE TITLE
CTestTestfile.cmake is not imported from tested module but from other module that is a dependency

### ISSUE THREAD

**Issue by mschmid** [conan-io/conan#1416]
Hi,
I have a strange mix of exported files when I import them again for the test_package step.
Given two different modules A and B, B is dependent of A.
Both have unittests that are called by the CTest Framework. Therefore they both package their CTestTestfile.cmake in the package()-method.
Both modules also have a test_package folder that import the CTestTestfile.cmake and call ctest in the test()-method.
The test_package()-call on A works perfect, the test_package() on B however does call the unittests of A, because the CTestTestfile of module A gets imported. The package of B in the cache in fact contains the correct CTestTestfile.cmake, therefore there must be a bug in the implementation of imports()?

**Comment by memsharded** [comment]
I am not sure about your testing approach. Typically the **library** tests, defined in CTest or other testing framework, are run while building the library, that is, in the ``build()`` method of the root conanfile.py. So, if the tests do not pass, the package is not created at all.

The ``test_package`` functionality is mainly oriented to check that the package is correctly created, that it has packaged the headers, the libraries are there, the library names are correct, and users are able to link them and run a test app without errors. But not to run the full unit tests over the package, very often, the unit tests cannot be run, because the package just exposes a small API, not all headers of the package.

Said that, it is totally possible to run an extensive suite test written in CTest in the ``test_package``. 
I think you want to be restrictive on the files you are importing, something like:

```python
def imports(self):
      self.copy("CTest*.cmake", root_package="MyPkgName")
```

Please try it and tell me. Thanks!

The complete reference for the ``copy`` inside ``imports`` can be found in: http://docs.conan.io/en/latest/reference/conanfile/methods.html#imports

**Comment by mschmid** [comment]
Hi, thanks for the fast answer. We are currently experimenting whether it is better to run the unit tests during the build step or during the test_package step. Anyway we want to use test_package on our CI-server (Jenkins) to create packages and upload them to artifactory.
Thank you for the hint regarding the root_package attribute, I will try out tomorrow.

**Comment by memsharded** [comment]
Good! Yes, test_package is definitely the recommend way to create and test packages even for jenkins. You can see in http://docs.conan.io/en/latest/integrations/jenkins.html#example-build-a-conan-package-and-upload-it-to-artifactory that we are also using it for that. Let me know tomorrow how it goes. Cheers!

**Comment by mschmid** [comment]
Thank you, the documentation is really great, I was able to setup everything with it!
Regarding the issue: The root_package attribute did fix it!
Without it, somehow a CMake-File from another package gets imported. For me this is not a big issue - knowing that it can be fixed with the root_package attribute.

**Comment by memsharded** [comment]
Yes, the general behavior of the ``imports`` feature is "bring me all *.dll from all my dependencies, because I want them besides my executable to ship them". For bringing specific files from specific packages, you have to specify it, because that is a less common pattern. 
Great the you were able to make this work! :) Thanks for telling.
