### ISSUE TITLE
[question] Read/Forward system requirements

### ISSUE THREAD

**Issue by TTrambi** [conan-io/conan#14189]
### What is your question?

Hi, I implemented a custom deployer for my project to create a debian package. 

My application requires some packages that have system requirements, in my case OpenCV which depends on GTK/system.
Is there a way to read out the system requirements and forward them be dependencies of my debian packge?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @TTrambi 

This is a very good question.

We already made available the ``system_requires`` information in the json output. If you use:
```
conan install/create ... -c tools.system.package_manager:mode=report --format=json > graph.json
```
Then you will see in the ``graph.json`` a ``system_requires`` reporting the necessary system requirements for the used system package manager. https://docs.conan.io/2/reference/commands/formatters/graph_info_json_formatter.html?highlight=system_requires and https://docs.conan.io/2/reference/conanfile/methods/system_requirements.html?highlight=system_requires


For deployers programmatic access, you might access it with:

```python
def deploy(graph, output_folder, **kwargs):
    # Note the kwargs argument is mandatory to be robust against future changes.
    for node in  graph.nodes:
           system_requires = node.conanfile.system_requires # This is a dict {"Apt": [list of packages]}
```
You might want to filter some nodes, for example only ``node.context == "host"``.

This might not be documented yet, so we might need to add this to the public documented ``ConanFileInterface``, so it is also accessible via ``from req, dep in conanfile.dependencies.items()``, because this way you can access the relevant dependencies of the current conanfile, that already filters some indirect and build dependencies. Or you could directly call ``node.serialize()`` to get the json representation and get it from there.


Please give the above a try and let us know, and we will proceed to document this publicly.

**Comment by memsharded** [comment]
Closing as responded back then. Please don't hesitate to re-open or create new tickets if necessary for any further question. Thanks for the feedback.
