### ISSUE TITLE
[question] package with the project using git submodules

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14201]
### What is your question?

Hello,
I would like to create a package from a project using git submodule:

So far I wanted to resolve it by something like that:
my conandata.yml
```py
sources:
  "f1.3.1":
    url: "https://github.com/xdp-project/xdp-tools/archive/v1.3.1.tar.gz"
    sha256: "de24fcc8a5f7d8007369d59e034e69fb870528902c761262bdbd4b9e5422c326"
```

conanfile.py
```py
    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)

    def build(self):
        subprocess.check_call(["git", "init"])
        subprocess.check_call(["git", "submodule", "update", "--init", "--recursive"])
        autotools = Autotools(self)
        autotools.configure(args=self.args)
        autotools.make(args=self.args)
```

but it doesn't work because .git is obligatory to call git submodule but on the other hand it screws up git submodule because it won't download modules.

Can you propose a solution how to resolve it?

If something is misunderstand please let me know.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by damian-tomczak** [comment]
is it possible to specify in conandata.yml more archives for single version - i mean about dependencies of the project?

**Comment by memsharded** [comment]
Hi @damian-tomczak 

The ``conandata.yml`` is actually free-form. You can put the data you want there with the structure you want. Using a tarball like ``https://github.com/xdp-project/xdp-tools/archive/v1.3.1.tar.gz`` is mostly for third parties and ConanCenter, but for something like checking out a project with its submodules it is better to directly clone the sources, not download them, so using ``git.clone()`` in ``source()``, instead of ``get(..)``

Please let me know if this clarifies it (it is not clear if this is something you want to do for ConanCenter or for your own recipes).

Some other hints:
- Do not call ``subprocess`` directly. Using ``self.run()`` is the recommended approach for recipes. 
- The recommended way to run ``git`` commands would be https://docs.conan.io/2/reference/tools/scm/git.html. Using ``clone(..., args)`` you might do the submodules checkout.
- The recommended place to checkout submodules is ``source()``, not ``build()`` method.

**Comment by damian-tomczak** [comment]
> Hi @damian-tomczak
> 
> The `conandata.yml` is actually free-form. You can put the data you want there with the structure you want. Using a tarball like `https://github.com/xdp-project/xdp-tools/archive/v1.3.1.tar.gz` is mostly for third parties and ConanCenter, but for something like checking out a project with its submodules it is better to directly clone the sources, not download them, so using `git.clone()` in `source()`, instead of `get(..)`
> 
> Please let me know if this clarifies it (it is not clear if this is something you want to do for ConanCenter or for your own recipes).
> 
> Some other hints:
> 
> * Do not call `subprocess` directly. Using `self.run()` is the recommended approach for recipes.
> * The recommended way to run `git` commands would be https://docs.conan.io/2/reference/tools/scm/git.html. Using `clone(..., args)` you might do the submodules checkout.
> * The recommended place to checkout submodules is `source()`, not `build()` method.

Thanks <3
