### ISSUE TITLE
[question] Usage with conanfile and toolchain without extra install command

### ISSUE THREAD

**Issue by 0verEngineer** [conan-io/conan#14224]
### What is your question?

Hey, i am currently experimenting with Conan 2 and vcpkg to decide what to use in the future. Currently i use Conan 1 with the old cmake integration.

In Conan 2 i have to run the `conan install` command and then do the cmake init and build. With vcpkg i do not need to run a install command before cmake init, this leads to easier IDE integration as it just works and installs the stuff on cmake configure when you open the Project (you can pass stuff like `-DVCPKG_TARGET_TRIPLET=x64-windows-release` to change the target).

Is there something similar in Conan 2?

It is not a big deal and i kinda like the install command approach more BUT if your IDE createss a build directory for debug and release you have to do `conan install` twice with different modes on different directories and with the vcpkg approach it just works.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @0verEngineer 

Thanks for your question.

Beyond the "canonical" usage of ``conan install``+ ``cmake ...`` usage, there are a few other integrations that might be worth checking:

- The ``cmake-conan`` integration. It existed for Conan 1.X, but for Conan 2.0 we have implemented a new integration based on the new CMake providers. This allows for a transparent integration (not modification to ``CMakeLists.txt`` necessary), and ``conan install`` will be automatically called when ``cmake ...`` is called. It is still experimental, but thanks to feedback and contributions from users testing it, it is improving quickly, check it in this branch: https://github.com/conan-io/cmake-conan/tree/develop2
- CLion IDE has its own integration too, that helps users of this IDE. Under the hood it will also use the ``cmake-conan`` integration to automatically install dependencies. It is being re-written from scratch for Conan 2.0, we are putting good efforts in this one at this moment: https://github.com/conan-io/conan-clion-plugin/tree/develop2
- There was a Visual Studio integration, but this one is still on hold. The idea is that it can support native MSBuild projects (no CMake), and automatically call ``conan install`` to avoid users having to go to the command line to install dependencies. We will resume work on this integration when we finalize some of the ongoing efforts and can prioritize this again.

Please let me know if this clarifies a bit the issue. If you are using CMake, probably the ``cmake-conan`` integration would be what you are interested in, but feedback welcome. Thanks!


Note: Personally, I am a big fan of the explicit ``conan install`` + ``cmake`` flow. It makes things evident, and developers understanding what they are doing, learning a bit about the tools instead of hiding the details is a big plus quickly (initially they can push back a bit, because of changing their flows), because otherwise then bottlenecks happen, the build doesn't work, and devs cannot understand if it is a dependency failure or an issue in the CMake build scripts, so they just report "my build is broken". Shared ownership over the tools used to develop works much better in my opinion than complete specialization where some devs touch exclusively C++ code, but won't touch anything in the build/test/ci/flow at all (and viceversa)

**Comment by 0verEngineer** [comment]
Hey, thanks a lot this does indeed clarify my issue, but also raises a new one:

If i am using `CMakeDeps` and `CMakeToolchain` integration and i later want to use the Conan CLion Plugin do i need to switch integration?

I am personally also a fan of the explicit conan install + cmake flow.

**Comment by memsharded** [comment]
Not necessarily. The ``CMakeToolchain`` integration becomes unnecessary and not used, but it is good that it is there in case the current ``conanfile.py`` is also used to create a package (``conan create``) and not only for consumption, because in that case, you don't want CMake to be the "driver" and call ``conan install``, but Conan will be the driver and CMake will not call internally ``conan install`` again, that would be a caos of recursion if building every package in the dependency graph).


So you are good with using ``CMakeDeps`` and ``CMakeToolchain`` in your ``generators`` or ``generate``, just the ``CMakeToolchain`` part will not be used for the local "consumer" developer flow that uses the ``cmake-conan`` integration (CMake being the driver and calling ``conan install`` internally)

**Comment by 0verEngineer** [comment]
Thanks again for your help, have a nice day! :)

**Comment by memsharded** [comment]
Happy to help 🙂 
Don't hesitate to create new tickets for any further question you might have. Thanks!
