### ISSUE TITLE
conan import does not copy artifacts into current directory

### ISSUE THREAD

**Issue by justinpa-asg** [conan-io/conan#1422]
I exported conanfile.py with def imports(self) into local cache and ran install --build. Why can I not copy artifacts from local cache using [conan imports](http://docs.conan.io/en/latest/reference/commands/imports.html)?

> $ conan --version
> Conan version 0.22.3
>$ conan search MyPackage/1.2@user/channel
>Existing packages for recipe MyPackage/1.2@user/channel:
>
>    Package_ID: 31..33
>
> $ conan imports MyPackage/1.2@user/channel
> ERROR: conanbuildinfo.txt file not found in C:\MyPackage
> It is required for this command
> You can generate it using 'conan install -g txt'

Is this a bug in imports? Is there another way to copy artifacts from local cache into a directory?

**Comment by memsharded** [comment]
imports is a feature to bring artifacts from the local cache, from all the dependency graph of the package. Does MyPackage/1.2 have dependencies? ``conan imports`` will bring artifacts from it dependencies, not from MyPackage itself.

I think it can be understood better with the conanfile in user space. If you write a conanfile.txt in your user space, with a [requires] section and an [imports] section. When you run ``conan install`` it will import artifacts from the dependencies of your conanfile.txt, including transitive dependencies. It is a way to collect for example shared libraries from all the dependency graph.

In your second error, it is because to import something, first the dependency graph for a given set of settings and options has to be computed. So for the command ``conan imports`` first a ``conan install`` is necessary to provide the settings and options, and the result is stored in a text file with the ``-g txt`` generator, so the later ``conan imports`` is able to know the full dependency graph to collect artifacts.

Note that for every different setting and option you get a different dependency graph, and the the artifacts to be collected might vary. 

Maybe you are looking for something more like a "deploy" functionality that would allow to copy the artifacts from a given package?

**Comment by memsharded** [comment]
Old issue, no response.
In any case, imports are being removed in 2.0, recommendation is to move to explicit copy() (in ``generate()`` method)

**Comment by Makogan** [comment]
@memsharded Could you please explain how to use the generate() method? I don't see it on the 1.48 documentation. I use imports to gather the imgui backends from the res folder of the package your comment seems to suggest this is not the way to go about it moving forward.

**Comment by franramirez688** [comment]
@Makogan 
You can find out more information [in this section](https://docs.conan.io/en/latest/reference/conanfile/methods.html#generate) but I also recommend you to have a look at the [Migration Guide to 2.0](https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#the-generate-method). We're improving this last one because there are a lot of tips to understand all the differences between both versions and wide explanations about some methods as well.
