### ISSUE TITLE
Having an issue building a package on Windows

### ISSUE THREAD

**Issue by executionByFork** [conan-io/conan#1423]
Hi, I'm trying to build a conan package of Boost 1.63.0 on a windows machine and am getting strange results. The recipe file I'm using is modeled off of [lasote's conan-boost example](https://github.com/lasote/conan-boost).

Basically, when I run `conan test_package`, the Boost library is built, but when `cmake --build` gets is invoked it can't find Boost. In `conanbuildinfo.cmake,` the `CONAN_BOOST_ROOT` directory is set to ```/home/tleach/.conan/data/Boost/1.63.0/tleach/testing/package/a45de...755c27```.

However I've noticed the package is being build elsewhere. As shows in the logs: ```Boost/1.63.0@tleach/testing: Building your package in C:/.conan\2skkns\1```
In fact, conan is building in one directory and packaging in another:
```
Boost/1.63.0@tleach/testing: Package '85f780d0530411a64b0be4407b381706014b445d' built
Boost/1.63.0@tleach/testing: Build folder C:/.conan\2skkns\1
Boost/1.63.0@tleach/testing: Generated conaninfo.txt
Boost/1.63.0@tleach/testing: Generated conanbuildinfo.txt
Boost/1.63.0@tleach/testing: Generated conanenv.txt
Boost/1.63.0@tleach/testing: Generating the package
Boost/1.63.0@tleach/testing: Package folder C:/.conan\buhgis\1
```
This looks like a bug to me. Conan is auto generating two different conan home directories, building in one and searching for the package in another. Leading to this error:
```
-- The CXX compiler identification is MSVC 16.0.30319.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: Using cmake global configuration
-- Could NOT find Boost
CMake Error at CMakeLists.txt:13 (MESSAGE):
  ERROR! BOOST NOT FOUND!

-- Configuring incomplete, errors occurred!
See also "C:/Users/tleach/Documents/boost/test_package/build/da39a3ee5e6b4b0d325
5bfef95601890afd80709/CMakeFiles/CMakeOutput.log".
ERROR: Error 1 while executing cmake "C:\Users\tleach\Documents\boost\test_packa
ge" -G "Visual Studio 10 2010 Win64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_EXPORTED
="1" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="10" -DCONAN_CXX_
FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -Wno-dev
```
This is my `conan.conf` file for reference:
(located in the folder at `C:\Users\tleach\.conan`. There is no config file in `C:\.conan\`)
```
[storage]
# This is the default path, but you can write your own
path = ~/.conan/data

[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = 50                  # environment CONAN_LOGGING_LEVEL
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
compression_level = 9                 # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = True               # environment CONAN_SYSREQUIRES_SUDO

[settings_defaults]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=10
os=Windows
```

**Comment by memsharded** [comment]
Yes, that could be a bug in the conan ``shorts_paths`` feature that deals with the annoying Windows limitation of path lengths. There is some bug in the feature, we have been looking for for a while, without success, see: https://github.com/conan-io/conan/issues/1229

Maybe this is related. I have check locally, and I get ``set(CONAN_BOOST_ROOT "C:/.conan/drnlx6/1")`` in the cmake file, pointing correctly to the short-paths folder.

Do you have your recipe in a repo, so I could have a look to the full package recipe and try and debug it? Thanks!

**Comment by tleachman1234** [comment]
Yes, this is in a repo, but unfortunately it is a private one. What files would you like to look at? You mentioned the conan recipe file, but anything else? I could possibly copy the repo from gitlab into my account here on github, however I'll have to comb through it before hand and omit some things, because there might be some host names or file paths that our company doesn't want exposed to the public.

**Comment by tleachman1234** [comment]
I think I will go ahead and turn the repo into a public one. If you need any of the details that are omitted then I can possibly send those details to you over a private channel.

**Comment by memsharded** [comment]
If you prefer to close the repo and send it in a zip, by email, it is also fine.
I will have a look when possible, thanks!

**Comment by tleachman1234** [comment]
I've run `conan test_package` again, without changing anything, and now in `conanbuildinfo.cmake`, I see `set(CONAN_BOOST_ROOT "C:/.conan/buhgis/1")`. I'm not sure why it was previously pointing to the`.conan/` folder in my user directory, I wonder if I accidentally copied from the wrong `conanbuildinfo.cmake` file, since I also have a `cygwin` terminal open on the windows machine.

But this just makes the issue stranger then, because conan is still failing to find boost after it is built. And the variable in `conanbuildinfo.cmake` seems to be set to the right directory. This same repository works fine on a linux machine.

**Comment by lasote** [comment]
On Windows, the Boost libraries take very original names with prefixes for visual version, runtime etc. It is a possibility that the findCMake of that recipe is not working correctly. 
For the recipes in conan-center I'm trying to change the approach, and do not provide a FindXXX.cmake custom package, just package library names that the original CMake script can find. 
To debug it, Take a look at the package folder and ensure that the libraries are there (package built ok), then you can try to debug the findBoost.cmake but it is an extremely tedious task, try to enable `Boost_DEBUG` variable and see what it prints.

**Comment by tleachman1234** [comment]
Alright, I could see how the naming scheme could be the issue. Inside the conan build folder, I'm seeing the boost libraries, but are you saying that I am going to have to rename **every** library file to the appropriate name, for anything that gets built on Windows?
```
C:\.conan\buhgis\1\lib>ls
libboost_atomic-vc100-mt-1_63.lib
libboost_chrono-vc100-mt-1_63.lib
libboost_container-vc100-mt-1_63.lib
...
libboost_wave-vc100-mt-1_63.lib
libboost_wserialization-vc100-mt-1_63.lib
```
This seems like a bad workaround, especially because it won't scale well at all. We have a bunch of libraries we want to eventually package up with conan, and they need to be compatible on both Windows and Linux machines.

**Comment by memsharded** [comment]
A good question is if you really need to rely on the "find.cmake" feature.
Conan already provides all the needed information in the ``conanbuildinfo.cmake``, it knows where is everything, so it is not necessary to find anything, just including that file and doing the setup works for most cases.

**Comment by lasote** [comment]
Yo do not need to rename all... Just the names that the kitware CMake module find package files are not able to locate. Is not a Conan problem and not even a recipe problem. The problem is that the Cmake find package do not work for all possible configurations. I just realized that provide a custom findpackage is not maintainable, kitware introduce improvements like targets in  every version, and many other things. Probably the way to go is  a open an issue or PR in the Cmake repository.

**Comment by lasote** [comment]
And yes, the problem is specific for Boost or any other supported by the findXXXX Cmake installation files. For your libraries there is no problem.

**Comment by tleachman1234** [comment]
Yeah, I wasn't originally using the `FindBoost.cmake` feature, but added it in when I was having problems with this error on Windows. I will see what I can do with this and let you guys know

**Comment by cleeland** [comment]
Could you ensure that `b2` gets invoked with `--layout=system` in order to avoid decorating the library names?

**Comment by lasote** [comment]
Didn't know that trick, I'll take into account when I prepare the Boost recipe for conan-center. Thks

**Comment by cleeland** [comment]
I would think that you'd want to offer the layout as an option for using the library, and it would be one of the values of `settings`.  I'm not sure how that would actually work.

**Comment by lasote** [comment]
The layout or library name doesn't care at all while the package info method declare the right library names/include directories etc. You only need to link with CONAN_LIBS in your build system, set the include paths etc.

 The issue with CMake findPackage is that you don't use the information that conan already knows, and you trust that CMake will be able to locate them in some directory, so, in this case, following some common layout is important. I prefer to just link with CONAN_LIBS , and if I want compatibility in the same project without using Conan, introduce a `if(CONAN)` .

**Comment by memsharded** [comment]
In general it is not recommended to add settings or options that doesn't affect the resulting binaries, because they create an explosion of binaries. A short example:
- You can add an option, lets call it "include_dir" in package A, with a value of "ANY", that means that it can take any value that the user wants: "include", "inc", "headers.
- For every different option, conan will create a different package binary, with the headers in a different subfolder. That is, it can have infinite variants of the same package just to change that path
- That path is irrelevant. The system already provides the consumer with variables telling: "this is the include directory for package A.

**Comment by jcar87** [comment]
Hi @tleachman1234, based on your `onan-boost/test_package/CMakeLists.txt` file, on line 7 you have:
```
find_package(Boost COMPONENTS regex)
```

Now unless `conan_basic_setup()` is overriding CMake's own module path, I am guessing it is using CMake's built-in FindBoost.cmake (which should be the same or similar as OriginalFindBoost_3_4_3.cmake)

If you have a look at that file, around line 42 it says that it takes a hint from the CMake variable `BOOST_ROOT`

So I would simply add the following add to your CMakeLists.txt, right before the call to find package.
```
set(BOOST_ROOT "${CONAN_BOOST_ROOT}")
```

**Comment by memsharded** [comment]
Closing this as inactive
