### ISSUE TITLE
[feature] conan remove should have a --dry-run option

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#14245]
### What is your suggestion?

`conan remove` asks for every package if it really should be deleted. This is really bothersome when removing many packages (e.g. when removing all but the last revision with `conan remove '*#!latest'`). 

However, it would be nice to see what is deleted before actually executing `conan remove -c`. It would be nice to have a `--dry-run` option for that use cases.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @fschoenm thanks for your request.

Do you know about the packages lists feature? ([Release blog here](https://blog.conan.io/2023/06/28/Conan-bulk-package-operations.html))

It's a way to have the output of some commands be the input of a few others. [See here for an example of your use case](https://docs.conan.io/2/examples/commands/pkglists.html#removing-packages-lists), which lets you know exactly what will be removed.

Hope this helps you with your problem, let me know otherwise :)

**Comment by fschoenm** [comment]
@RubenRBS Yes, I've heard of it but it seems awkward for such a common use case. Almost nobody is going to use such a convoluted way of doing things.

IMO every destructive command ought to have a `--dry-run` option.

**Comment by AbrilRBS** [comment]
Adding as a look-into to see what the team thinks, as I don't quite see it that way and think that our current approach is ok, will let you know once I can ask the team :)

**Comment by AbrilRBS** [comment]
Some of the team thinks that this might be a nice addition even when using pkglists, so we'll look into implementing it! Thanks a lot for your request!

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/14760, for next 2.0.12
