### ISSUE TITLE
[bug] Conan editables : Incomplete path in conanrunenv-release-x86_64.ps1

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#14258]
### Environment details

* Operating System+version: W10 22H2
* Compiler+version: VS2022
* Conan version: 2.0.7
* Python version: 3.9.13

### Steps to reproduce

Hello,

1. Please clone this [repo](https://github.com/Todiq/test_conan.git) and `cd test_conan`
2. Build `Test/alpha` using `conan build -verror Test/alpha`
3. Set alpha as an editable package with `conan editable add Test/alpha`
4. Build beta using `conan build -verror Test/beta -nr`
5. Both alpha and beta compile successfully
6. Run `.\Test\beta\build\generators\conanrunenv-release-x86_64.ps1` to load the path containing the locations of the dependencies.
7. Notice that the locations of the `alpha` package's libraries, previously set as editable, are missing

If alpha is built using `conan create` or exported using `conan export-pkg` after being compiled instead of being set as editable, the path will contain alpha's location from the conan cache, as expected.
Furthermore, this issue does not seem to be happening on Linux, where the path of the libs from the editable package will be properly loaded in `LD_LIBRARY_PATH`.

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks very much for your report, and for putting together a reproducible case. It really helps.

It seems the problem is that you are missing the definition of ``bindirs`` in your "alpha" ``layout()`` method, something like:
```python
def layout(self):
      self.cpp.build.components["alpha2"].bindirs = [os.path.join("alpha2", bt)]
```
Then, paths to ``alpha`` will appear in ``beta`` environment scripts. Libdirs are not added by default to PATH envvars by ``VirtualRunEnv``, it is the ``bindirs`` that is added to the run environment.

**Comment by Todiq** [comment]
Indeed, that fixed the issue. Sorry for inconvenience!

**Comment by memsharded** [comment]
No prob, happy to help! 🙂
