### ISSUE TITLE
[question] Some dependencies show package_folder as None

### ISSUE THREAD

**Issue by retroandchill** [conan-io/conan#14299]
### What is your question?

I've been using conan for a little while now and we've been using it with a CI/CD setup, currently I've been trying to figure out how to make a full copy of all of the dependency packages into a local folder (so they can then be exported as job artifacts). I've noticed that full_deploy gets close to what I want, but is not quite exactly what I'm looking for, but gives me enough of a baseline to go off of. 

Either way my major issue is that some of the dependencies of the dependencies report a package_folder of type None, which means I can't locate the package to copy their files over. Is there a way to force conan to report the recipe and package folders of ALL the dependencies?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fcorso2016 

Thanks for your question.

Conan 2.0, when some packages binaries are not necessary, it will mark them as ``Skip``, and avoid downloading or building the binary. As there is no package binary, the ``package_folder`` will be ``None``. Can you please confirm this is the case, and the "skipped" binaries are those you are seeing without ``package_folder``?

It seems you are doing something like https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html, if that is the case, the Conan behavior is still correct. If a dependency is ``Skip``, it is because that package binary is really not necessary, it shouldn't be used, it shouldn't be linked, etc. Trying to use the artifacts of that skipped package inside a build wouldn't be correct.

What is exactly your use case, could you please elaborate a bit more?

**Comment by memsharded** [comment]
Hi @fcorso2016 

Did the above clarify a bit the issue? Please let us know.

**Comment by memsharded** [comment]
Closing as staled, please re-open if there are any further questions.
