### ISSUE TITLE
How is user/channel applied when calculating requirements

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#14328]
Conan 2.0.6

I have built a package mypackage which depends on popt/1.19
conancenter only have popt/1.16, so I have created my own version of popt (based on the existing conancenter recipe) and uploaded it to my remote as popt/1.19@myuser/mychannel

I have a consumer recipe with these dependencies explicitly overriding popt to my version:
```
    def requirements(self):
        self.requires("mypackage/1.0.0")
        self.requires("popt/1.19@myuser/mychannel")
```

If I i have the following requirements in the recipe for mypackage everything resolves ok as expected and popt/1.19@myuser/mychannel is used:
```
    def requirements(self):
        self.requires("popt/1.19@myuser/mychannel")
```

But I do not like putting explicit user/channel on my requirements in my packages, only in my final consumer recipe, because if I decide to contribute to conancenter with popt/1.19 I would have to change the mypackage recipe and not only my consumer recipe.

If I do this: 
```
    def requirements(self):
        self.requires("popt/1.19")
```

Then conan complains `ERROR: Version conflict: mypackage/1.0.0->popt/1.19, consumerrecipe/None->popt/1.19@myuser/mychannel`. Which is kind of understandable.

But if I do this in mypakcage:
```
    def requirements(self):
        self.requires("popt/[~1]") #or self.requires("popt/[>=1.19]")
```
Then dependencies are actually resolved properly and everything seems to work.
That indicates to me that user/channel is actually seen as a part of the version string when resolving dependencies. Is that correct?
Is there a recommended way of using user/channel in dependencies. 

My personal preference would be to never put user/channel in requirements in package recipes, only use user/channel in consumer recipes to make explicit overrides?

//Klaus

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Thanks for your question.

> conancenter only have popt/1.16, so I have created my own version of popt (based on the existing conancenter recipe) and uploaded it to my remote as popt/1.19@myuser/mychannel

Probably the best approach is to not add ``user/channel`` to recipes that are created from ConanCenter. It will add a lot of extra work, specially if you are using other recipes from ConanCenter.

I'd like to suggest another flow for using ConanCenter recipes, when control and customization is necessary: using a ``conan-center-index`` Github repo fork:

- Fork conan-center-index repo
- Define a list of the packages and versions that you want, like mypkgs.lst
- Have a simple script that export your list, then build them, then upload them to your artifactory

You can find a simple mybuild.py script in https://github.com/memsharded/conan-center-index/tree/mycustom. This script is already very efficient, as the --build=missing guarantees that it will not rebuild unnecessarily.

This approach is being successfully used by many Conan users, as it has many advantages:

- Full control over the inputs. Total robustness, it is impossible that changes in ConanCenter breaks your build, only you have control over the updates of recipes
- Total customization. If you need a patch, a new version, an update... you can apply it in your fork, and have it immediately, no need to wait for it being merged upstream
- Quite simple to implement. Very understandable and reproducible by developers locally, without infrastructure, easy to debug.
- No unnecessary builds, you make sure both that your binaries are yours, and that no waste of resources or CI happens because rebuilding from sources again.


In all of this process, you keep all the packages from ``conan-center-index`` **without** user/channel, exactly as they are built in ConanCenter. The less divergence from the upstream the better.

**Comment by klausholstjacobsen** [comment]
James, Thanks a log for your, as usual, swift response.

Actually what you suggest is more or less exactly what we decided to move towards just last week with these conancenter-copy recipes.
I have one more advantage to add:

- Easy to contribute and integrate back into conan-center because PRs can be created by just a few clicks.

Regards
Klaus

**Comment by memsharded** [comment]
Fantastic, great to hear that you had decided to go this way, thanks for the feedback!
