### ISSUE TITLE
[feature] Add authentication option with .netrc file

### ISSUE THREAD

**Issue by klimkin** [conan-io/conan#14354]
### What is your suggestion?

Using `.netrc` file for authentication will complement current options:
* When using Git LFS with Artifactory, Git LFS already uses `.netrc`, so we can keep credentials in one place.
* Can avoid secret tokens in environment variables. Environment variables are more prone to exposure compared to the dot-files.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your suggestion @klimkin 

Lets think about this with the team, and also consider if a ``users.json``, similar to the already existing https://docs.conan.io/2/reference/config_files/source_credentials.html would make more sense

**Comment by memsharded** [comment]
We have finally implemented this in a ``credentials.json`` approach in https://github.com/conan-io/conan/pull/14392 for next Conan 2.0.10. We have gone this approach because it aligns better with the existing ``source_credentials.json``, and it also feels a better match, as .netrc seems to inject credentials into http calls, while this ``credentials.json`` injects them into the Conan auth protocol that will use them for obtaining the actual JWT used in the http api.

Closing this as solved, thanks for the suggestion!
