### ISSUE TITLE
[potential bug] 'conan graph build-order' misses build-requirement

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#14350]
### Environment details

* Conan version: 2.0.7
* Python version: 3.11

### Steps to reproduce

I'm using `conan lock create --requires some-module/4.2.0 '--build=*' -pr:h armv8 -pr:b x86_64 --lockfile-out build.lock` to create a lockfile and afterwards `conan graph build-order --requires some-module/4.2.0 -pr:h armv8 -pr:b x86_64  -l build.lock --format=json'` to output the build order.

My module `some-module` defines direct build dependencies:
```
build_requires = (
        "bison/3.7.6",
        "flex/2.6.4"
    )
```

Now the creation of the lockfile correctly lists e.g. bison and the file itself also contains the entry.
```
Build requirements
    bison/3.7.6#8588fa44091e2318aea1ee752a5bd64e:53097b7b57d45875f2bf3a9fd424bbc057dac38a - Build
```

But afterwards when creating the build-order:
```
Skipped binaries
   ... bison/3.7.6 ...
```
The output of the build-order misses e.g. bison.

As a consequence the build of `some-module` will fail due to:
```
ERROR: Missing binary: bison/3.7.6:53097b7b57d45875f2bf3a9fd424bbc057dac38a
```

Am I using the commands wrongly or is this a potential problem?

### Logs

See above.

**Comment by memsharded** [comment]
Hi @tbsuht 

The ``build-order`` commands needs the ``--build`` argument too, to decide what is going to be built.
Please try that (in principle, the one to be used is ``--build=missing``, to avoid unnecessary re-builds from source, in Conan 2.0, with the better ``package_id`` computation and a bit of care defining versions, this should be the default)

**Comment by tbsuht** [comment]
@memsharded Thanks! Working now!

One more question: if I want to build bison as a build requirement for the armv8 platform, isn't this the right way to do so?
`conan install --requires=bison/3.7.6#8588fa44091e2318aea1ee752a5bd64e --build missing --build-require -pr:h armv8 -pr:b x86_64 -s build_type=Release`

Although I provide `--build-require` it is compiling bison with the armv8 profile.

**Comment by memsharded** [comment]
That ``--build-require`` is not really intented for the dependency, but for your current consumer. I think we might want to protect its usage and throw an error for your case.

Your case should be done with ``--tool-requires=bison/...`` instead (no need to define the ``--build-require`` at all here), try that and let us know.

**Comment by tbsuht** [comment]
@memsharded looks good, thanks for the fast support!

But I didn't really understand what the `--build-require` is intended for, is there somewhere a good example in the docs?

**Comment by memsharded** [comment]
Apparently not, I'll check and try to add something to the docs.

The ``--build-require`` is used to make sure that a package that you are ``conan create .`` is created as a ``tool_require``. Quick example:

- Lets say you are cross building your app from Windows to Linux, so typically ``-pr:b=mywindows.profile -pr:h=mylinux.profile``.
- One of the packages that you need to build your app is ``cmake/3.25``. If you build it with ``-pr:b=mywindows.profile -pr:h=mylinux.profile`` you will be creating a Linux binary that you cannot use later for your build-requires, as you are building in a Windows machine.
- You could manually change your profiles, and for that ``cmake`` package do ``-pr:b=mywindows.profile -pr:h=mywindows.profile``. This will work for ``cmake``, but if you are building a cross-compiler like ``gcc-arm/1.0``, then this will not be valid, because the information that the ``target`` will be Linux-arm is not anywhere in the profiles
- So the solution, is to specify at ``conan create . --build-require -pr:b=mywindows.profile -pr:h=mylinux.profile``. This will understand that it needs to build a Windows binary.

**Comment by tbsuht** [comment]
@memsharded I see, for `conan create` this makes sense. But what about `conan install`? I don't understand the difference between using `--tool-requires` and `--build-require` + `--requires`. Or is this equivalent?

**Comment by memsharded** [comment]
``conan install`` doesn't need it when you don't specify a path argument, because you can do ``conan install --tool-requires=mypkg/myversion --build=mypkg/*`` to specify that you want to build that as a tool-requirement.

The problem is when you work with a path, like ``conan install <path>`` or ``conan create <path>``, because the information that such installation or creation is intended to be done as a tool-require is not there. In those cases the ``--build-require`` argument provides the extra information

**Comment by tbsuht** [comment]
Got it, thanks!
