### ISSUE TITLE
[question] Sharing sources across dependencies

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#14356]
### What is your question?

Dear Conan Folks,

I have the use-case that Component X contains:
- A simulink model in github 
- I generate source code from the model and create an executable 
- Package source code, header and executable 
- Why all three ?
- Because it is up to the consumer how they like to consume this package.
In the package_info method of component X , I have this:
```
def package_info(self):
        self.cpp_info.includedirs = ['include']
        self.cpp_info.libdirs = ['lib']
        self.cpp_info.objects = [os.path.join("lib", "IOps.c.obj")]
# EOF

```
Since the consumer decides, what he likes to consume either binary + header or source code, how do I expose the source code in the package_info method? Which variable to use that consumer can reference it?
The other ways I could think of is:
- In the generate method of the consumer , use copy and copy the sources to the build folder and then use glob 
```
file(GLOB SRC_FILES ${CMAKE_SOURCE_DIR}/*.cpp)
```
Is this the right way to proceed forward?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

the ``cpp_info`` contains a ``srcdirs`` variable similar to the ``includedirs``, ``libdirs``. The packages can define it to specify folders containing source code.

However, the only problem is that at the moment the ``CMakeDeps`` generator didn't define a variable for it, because it wouldn't be used by the standard library targets intended for pre-compiled binaries. 

There could be a couple of different approaches:

- We could add some variable like ``CONAN_MYDEP_SRCDIRS_RELEASE`` (and DEBUG) pointing to those folders, so the users can do ``find_package()`` and use the variable
- Users that want to consume those, read in their ``generate()`` method the ``self.dependencies["mydep"].cpp_info.srcdirs`` and generate their own variables, do their own copy or handle that code folders however they like

In the second case, it is still useful to use the convention of ``cpp_info.srcdirs``, as this is the built-in way to specify that some package contain some sources.

**Comment by maitrey** [comment]
The second method avoids the copy and still maintains single source of truth. I assume that the first method is not yet implemnted, right?

**Comment by memsharded** [comment]
No, the first method ``CONAN_MYDEP_SRCDIRS_RELEASE`` variables are not implemented yet, because the use case is not very clear yet.

**Comment by maitrey** [comment]
This solution works for me , ticket can be closed. Many thanks.
