### ISSUE TITLE
[question] 2.0 migration - Settings type annotation

### ISSUE THREAD

**Issue by agesome** [conan-io/conan#14380]
### What is your question?

Hello,

I use type annotations in my project and do the following with Conan 1.x to make `mypy` happy:
```python
from conans.model.settings import Settings
...
class Recipe(ConanFile):
    settings: Settings = "os"
```
Otherwise it thinks `settings` is a string and is confused by access like `settings.os`.

2.0 migration guide tells me to drop all imports from `conans`. However there does not seem to be a 2.0 alternative and internally 2.0 appears to still use `conans` imports for `Settings`.

Is there a way to keep the type annotation in 2.0? Such as continuing to use the `conans` import until it is replaced by something from `conan`.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @agesome 

the problem is that ``settings`` is initially not a ``Settings`` object, but it is defined as a tuple, and type changed dynamically on the fly when converted to object attribute instead of class attribute. So ``settings: Settings = "os"`` wouldn't be completely correct.

Yes, it is very important to not use ``from conans``. This will 100% change in future 2.X versions and break your recipes, so please use strictly ``from conan`` in your recipes from now on.

I am not sure if the ``Settings`` object will be exposed to the public interface just for the shake of typing. Exposing those objects require documentation and opens the door to users abusing those things in recipes in cases that were not intended and that ends creating issues and support tickets that we need to handle. So we really prefer to keep the public interface as reduced as possible.

**Comment by agesome** [comment]
Thanks! I guess ignoring `mypy` errors in this case is the way.
edit: an alternative is:
```python
from typing import Any
...
    settings: Any = "os"
```
