### ISSUE TITLE
[question] (Major) Dependency conflicts

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#14412]
### What is your question?

Hi,

I have a question about resolving dependency conflicts in the major part of the version according to semver definition (== breaking API changes).

Some background infos:
- We are using Conan 2.x
- Software components developed by ourselves, we stick to the semver definiton
- We only use version ranges for our software when defining dependencies
- We link dynamic(!) per default

So basically as long as a developer sticks to the semver definiton and only breaks an API when bumping the major version, Conan will basically prevent us from manual interaction due to version ranges.

Now major bumps are a different topic. I've watched [this explanation(~23:04)](https://www.youtube.com/watch?v=kKGglzm5ous) and I'm not sure how to handle this topic practically.

If we have a dependency graph with multiple major versions of a software component(see slide at ~23:57 above), conan will report an error and stop.

How to handle this in practice?

"ai" and "engine" are probably maintained by different persons/teams. So there might be no fast shifting possible for "engine" to use "math/2.0"
Worse: basically all our integration pipelines will stop at this situation and we can't integrate the whole product any more (conflict when installing "game").

What if a "engine" developer wants to test "math/2.0" in a complete integration("game") but can't change "ai"?

Worse: what if those conflicts origin in 3rd-party components used by "ai" and "engine"?

I can understand the concerns mentioned, but have not understood which possibilities are available especially for dynamic linking (~25:10 suggests static linking of "math", which is quite some effort or not possible).

~23:57 mentions that "game" can't link against different versions of "math": if we provide properly versioned libraries ("math.so.1" & "math.so.2") this should be doable or am I wrong?

Do you have some solutions how to work with this situation?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tbsuht 

Thanks for your detailed question and explanation of the case.

> If we have a dependency graph with multiple major versions of a software component(see slide at ~23:57 above), conan will report an error and stop.

Not sure if this is accurate, let me clarify, just in case:
- The next major version should be default be excluded in version ranges. So if your ``math`` is currently in the ``2.xxx`` train, your requires should look like ``math/[>=2.0 <3.0]``.
- when the team maintaining ``math`` do a breaking ``3.0`` release, they can do it confidently. It means it is breaking and require changes in code of the consumers. As it is excluded from the consumers valid ranges, nothing will break, and downstream consumers and products will keep safely building against the latest 2.X version
- when a breaking change and ``math/3.0`` is release, then downstream consumers will need to change and fix their code, which means releasing new versions of themselves. If ``engine/1.2`` do the changes, accept the new ``math/3.0`` and publishes a new ``engine/2.0`` of itself. This new version won't fit in the consumer game app that contains a requires to ``engine/[>=1.0 <2.0]`` too.
- It is true that game won't be able to integrate and test ``math/3.0`` until all intermediate packages in the graph have updated themselves and do the necessary code changes to use ``math/3.0``. But this is not a Conan issue, that is a pure code/development issue. ``ai`` needs code changes and a new release in order to be able to use ``math/3.0``, and it is impossible to test the ``game`` without updating ``ai`` code first.
- When ``ai`` updates to the new ``math/3.0``, then, it will be possible to test and update the ``game`` consumer application that integrates the new math version.

Not sure if I could be missing something, please let me know if this helps.

**Comment by tbsuht** [comment]
Thanks for the fast reply!

> * The next major version should be default be excluded in version ranges. So if your `math` is currently in the `2.xxx` train, your requires should look like `math/[>=2.0 <3.0]`.
> * when the team maintaining `math` do a breaking `3.0` release, they can do it confidently. It means it is breaking and require changes in code of the consumers. As it is excluded from the consumers valid ranges, nothing will break, and downstream consumers and products will keep safely building against the latest 2.X version

Correct, releasing new major versions of "math" is no problem. They will not be picked up by an existing version range.

> * when a breaking change and `math/3.0` is release, then downstream consumers will need to change and fix their code, which means releasing new versions of themselves. If `engine/1.2` do the changes, accept the new `math/3.0` and publishes a new `engine/2.0` of itself. This new version won't fit in the consumer game app that contains a requires to `engine/[>=1.0 <2.0]` too.

This point I don't get: when "engine" integrates "math/3.0.0", why would it provide a new major version? Assuming, that the API of engine is not changed, e.g. "engine/1.3.0" could be released, And this version could be picked up by game, which is the origin of my problem described above.

> * It is true that game won't be able to integrate and test `math/3.0` until all intermediate packages in the graph have updated themselves and do the necessary code changes to use `math/3.0`. But this is not a Conan issue, that is a pure code/development issue. `ai` needs code changes and a new release in order to be able to use `math/3.0`, and it is impossible to test the `game` without updating `ai` code first.

As asked above:  "if we provide properly versioned libraries (e.g. "math.so.1" and "math.so.2") this should be doable or am I wrong?" If "engine" linked against math.so.1 and "ai" against math.so.2 ... than it is ok to have two different major versions of "math" in the graph? (assuming that I'm careful about the usage)

Otherwise: if these were 3rd-party components, and they would use a common lib. If one of them updates to a new major version of the common lib, I will never be able to update until the other component also integrates the commonly used lib?

**Comment by memsharded** [comment]
> This point I don't get: when "engine" integrates "math/3.0.0", why would it provide a new major version? Assuming, that the API of engine is not changed, e.g. "engine/1.3.0" could be released, And this version could be picked up by game, which is the origin of my problem described above.

Yes, that is true, but even if the API of engine has not changed, its implementation changed enough to consider it incompatible with the previous versions, because now it is using a completely new math kernel, which could result in different engine results, faster computations, or even new bugs due to the new version dependency. Of course it is up to the developers and the engineering teams to agree on the version propagation strategy beyond the pure semver interpreation. If creating a major version of ``engine`` helps to move everything forward faster and without breaking, why not doing it?

> As asked above: "if we provide properly versioned libraries (e.g. "math.so.1" and "math.so.2") this should be doable or am I wrong?" If "engine" linked against math.so.1 and "ai" against math.so.2 ... than it is ok to have two different major versions of "math" in the graph? (assuming that I'm careful about the usage)

Yes, this is possible with Conan, but not the default, because it is quite challenging to do it right without having problems. The strategy is as follow:
- The default by Conan for regular ``requires()`` is assume that the same package and artifacts are going to be shared and used. If ``engine`` and ``ai`` both ``requires("math/2.0")`` they will find, include and link exactly the same files and libraries, or produce an error (a version conflict). This is a "diamond" structure in the dependency graph. 
- This is the safe approach by default. If not a complete encapsulation of the ``math`` library happens, and something leaks in the APIs or in the ABI, there will be compile, link or even worse, runtime errors. ODR can be easily violated.

But:
- If both ``engine`` and ``ai`` can and want to use a different version of ``math``, it is possible by not sharing it and declaring it as non visible down the graph with ``requires("math/2.0", visible=False)``. This will break the "diamond" structure in the dependency graph, and there will be 2 different ``math`` nodes in the graph, one required by ``engine`` and the other required by ``ai``.
- This means that whoever is downstream the dependency graph of ``engine`` and ``ai`` must be absolutely isolated from ``math``. This can typically be achieved only with:
  - ``math`` is a static library
  - ``engine`` and ``ai`` are shared libraries, linking and embedding the ``math`` static library 
  - No ``math`` header, symbol, object, or anything can escape or leak the ``engine`` and ``ai`` binaries. ``math`` must strictly be an implementation detail of the libraries, with zero visibility in the headers, and very careful management of objects (the ``ai`` library cannot return an object that contains in memory results, structures, data from ``math``, and use it in the ``engine`` library). 
- With ``math`` being a ``shared`` library it might be done, but it could be super challenging to do it. It can have many problems in common situations, for example, lets assume that both ``ai`` and ``engine`` depends on ``math/2.1``, so the library would be ``libmath2.1.dll``. But it happens that ``ai`` did an ``default_options = {"math*:precision": "double"}`` while ``engine`` did ``default_options = {"math*:precision": "single"}``. That means that there are actually 2 different shared libraries, both named ``libmath2.1.dll`` but one is build with double precision and the other with single precision, and now it is impossible for the ``engine.dll`` and the ``ai.dll`` to differentiate them and to use the correct one.

So going the ``visible=False`` path should be done only for exceptional cases where there are no other solutions. For the vast majority of cases, using "diamond" structures and regular ``requires()`` where only 1 package for ``math`` is used is what makes more sense. And the way to propagate breaking changes downstream is an organization and engineering issue (not really something specific of the Conan tool, it would happen if manually done with .zip folders in a shared drive): In this case, if I had to do it, it seems that the advantages to bump the major version of ``engine`` and ``ai`` to follow the major versions of  ``math`` is what makes sense. 

Another alternative would be to edit the ``game`` conanfile to ``requires("engine/[>=1.0 <1.3")`` and ``requires("ai/[>=1.0 <1.5]")`` to explicitly exclude the next ``engine/1.3`` and ``ai/1.5`` releases that will bring the new ``math/3.0`` with them, and only relax the constraint when both ``engine/1.3`` and ``ai/1.5`` are ready.

**Comment by tbsuht** [comment]
Thanks for the detailed answer!
