### ISSUE TITLE
[question] How to allow prerelease version for dependencies without changing recipe

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#14420]
### What is your question?

Looking at this documentation https://docs.conan.io/2/tutorial/versioning/version_ranges.html and the conan install command reference I have the impression that allowing to use prerelease versions can only be enabled by adapting the recipe where the dependencies have been specified.

Is there another way to externally define (e.g. via env var) that for all dependencies also prerelease versions are allowed.

Following use case I would like to support: I know that the target version of my dependency is 2.0.0 but I want already to test a prerelease version of it on let's say my own feature branch. Once I merge my feature branch to main the non-prerelease version of the dep shall be taken. The pipeline that is processing the branches of my repo could easily say for feature branches "prerelease allowed" and for main branches "prerelease not allowed".

As of today I (or the pipeline) would need to change the recipe file to enable and then disable again the use of prerelease versions.

Is my understanding correct or is just the documentation (or my search results) lacking the desired information how to externally enabled/disable the usage of prerelease versions?

Thank you

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MTomBosch 

I am glad you asked this :)

Yes, we have exactly a ``conf`` called ``core.version_ranges:resolve_prereleases`` for this purpose: globally enabling or disabling prereleases. We haven't documented and launched it properly because we wanted to write and validate further the full flow, but if you want to give it a try, it would be great to have your feedback.

The only minor UX inconvenience is that ``core.xxx`` confs cannot be set in profiles or command line yet. We will be considering to add them somehow to command line (more difficult than expected), but at the moment it needs to edit the ``global.conf``. Maybe using jinja template with some env-var you control would be more convenient to toggle it.

**Comment by MTomBosch** [comment]
Nice, then my memories did not fool me ;)
Can this be toggled using env vars or only via conf file entry? Via env vars would be also totally sufficient from my point of view.

**Comment by memsharded** [comment]
Only ``conf``. Env-vars is no longer a configuration mechanism for Conan, everything goes via ``conf``

**Comment by MTomBosch** [comment]
Ok. Thx. Is there already a ticket for requesting this "allow prerelease version usage via cmd line"?

**Comment by memsharded** [comment]
It would be this one: https://github.com/conan-io/conan/issues/13410

**Comment by MTomBosch** [comment]
Thx for the link
