### ISSUE TITLE
[question] self.recipe_folder is different from export() function to other functions

### ISSUE THREAD

**Issue by tfloodeenjr** [conan-io/conan#14479]
### What is your question?

Hello,

I am wondering why the self.recipe_folder is not the same throughout conanfile.py. I am attempting to build boost and put the artifacts in my own Artifactory repository.

https://github.com/conan-io/conan-center-index/tree/master/recipes/boost/all

I added some print statements to try to understand the issue:

======== Computing dependency graph ========
ERROR: boost/1.8.0: Error in config_options() method, line 274
	for opt_name in self._configure_options:
while calling '_configure_options', line 388
	return self._dependencies["configure_options"]
while calling '_dependencies', line 209
	raise ConanException(f"Cannot find {dependencies_filepath}")
	ConanException: Cannot find C:\.conan\p\boost9e36d55361fe6\e\dependencies\dependencies-1.8.0.yml
self.recipe_folder 1 = C:\builds\ebs\infra\boost\all
self.export_folder 1 = C:\.conan\p\t\boost56b9a059004f5\e
self.recipe_folder 2 = C:\.conan\p\boost9e36d55361fe6\e

In the export() function, the recipe folder is as expected. (self.recipe_folder 1)
In the _dependencies() function, it is in the cache. (self.recipe_folder 2)

The boost package wants to use a dependency file, but cannot find it.

copy(self, f"dependencies/{self._dependency_filename}", src=self.recipe_folder, dst=self.export_folder)

But this file is not found, since the locations are different. I was trying to hack-around the problem by copying the file again and putting it where the _dependencies() function expects it. Except I cannot get a hold of the location. Any insight into this boost conanfile.py?

Why is the self.recipe_folder different? Is there a way to get a hold of the original location?

Thanks,
-Tom

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by tfloodeenjr** [comment]
I found the version I was using is wrong. I had 1.8.0, when it should be 1.80.0.

**Comment by memsharded** [comment]
Hi @tfloodeenjr 

Version 1.80.0 doesn't exist, there is still something wrong there.

The explanation in latest Conan 1.60 and Conan 2.0 is that in the ``export`` process, the recipe is the one in user space, the original source user folder. This happens in the ``conan export`` and first stage of the ``conan create`` and ``conan export-pkg`` commands. When the package is being built in the cache, the ``conanfile.py`` is indeed the one in the Conan cache, not the one in user space or folder. This happens because the ``build()``, ``package()`` and other methods besides the ``export()`` are executed also when there is no user folder at all, and the recipes is downloaded from a server. This happens all the time with ``conan install`` and ``conan install --build=missing``.
