### ISSUE TITLE
[bug] settings.yml missing MSVC toolsets.

### ISSUE THREAD

**Issue by p-groarke** [conan-io/conan#14477]
### Environment details

* Operating System+version: Windows 11
* Compiler+version: VS 2022 17.6.5 (193)
* Conan version: 2.0.9
* Python version: None (self-contained conan)

### Steps to reproduce

After running conan2 for the first time, `settings.yml` is missing the visual studio toolsets. It only has `_xp` versions. These toolsets should be added : `v110, v120, v140, v141, v142, v143`

https://docs.conan.io/2.0/reference/config_files/settings.html is also missing them

**Comment by jcar87** [comment]
hi @p-groarke - thanks for raising this.

For the `msvc` compiler setting, this is intentional, and the toolset is intended to be captured by the `compiler.version` setting. Bear in mind that the settings capture the "variability" of binary packages. Something compiled with Visual Studio 2022 with the v142 toolset would be using exactly the same compiler as "Visual Studio 2019" uses by default - so in both of these cases, we capture this with `compiler.version=192`. The `_xp` toolsets are different as they do result in different binaries.

If what you want is to use a given version of Visual Studio to target an earlier toolset than its default,  this can achieved by specifying the compiler version for the toolset you are using, in combination with the `tools.microsoft.msbuild:vs_version` configuration.

This is explained in the following section in the documentation:
https://docs.conan.io/2/reference/config_files/settings.html?highlight=tools%20microsoft%20msbuild%20vs_version#msvc

For example, on a system where you have Visual Studio 2019 (toolset v142) installed:
```
compiler=msvc
compiler.version=192
```

But if you want to produce the same binaries on a system with Visual Studio 2022 that also has toolset v142 installed:

```
[settings]
compiler=msvc
compiler.version=192
[conf]
tools.microsoft.msbuild:vs_version = 17
```

This will instruct Conan to use Visual Studio 2022 with the v142 toolset (Conan keeps an internal table with the mapping between `compiler.version` and toolset version).

**Comment by p-groarke** [comment]
Hey @jcar87, thanks for clarifying. I didn't see it mentioned in the docs, but I'm guessing we can pass this through the command line as a setting? We use the toolset to generate multiple packages on our CI matrix.

**Comment by p-groarke** [comment]
closing with feature request to bring back some funcionality https://github.com/conan-io/conan/issues/14487
