### ISSUE TITLE
[question] search.py: search_recipes，why always call cache.all_refs, cost too much time!

### ISSUE THREAD

**Issue by Anytious** [conan-io/conan#14475]
### What is your question?

Operating System+version:ubuntu20.04
Compiler+version:gcc9.3
Conan version:1.59
Python version:3.8

hi，I have a few question about conans/search/search.py.
in this function, it always call cache.all_refs(), but get the same result, it may be a waste of time.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by Anytious** [comment]
Can I modify it like this?![f70e5016-d6c0-4c7f-a4b0-c8db4258613e](https://github.com/conan-io/conan/assets/43919146/7c82e16b-1eba-49dc-a947-cc865afcc8c5)

**Comment by memsharded** [comment]
Hi @Anytious 

Thanks for your question.

The first important point is that this kind of optimization will no longer be considered for Conan 1.X train release, only important back fixes and necessary things for the upgrade to 2.0.

It is still possible that this is the same in Conan 2.0. If you would like to report against it, the first important bit is the data: how long does it take? There are things that are not as efficient as they could be, or that might benefit from caching. But it is necessary to understand the pain a bit more, if it is not that long or it is called only once in a command, then it is not an important issue. Please let us know, some actual timings (together with the size of the cache) and the usage patterns might be useful.

**Comment by Anytious** [comment]
I'm so glad that you answered my question.
In my project，there are 9000 conan packages in the NFS file system，It cost me 30mins when I use conan info tool.
After  I modify it, It only cost 4mins when I use conan info tool. 
![image](https://github.com/conan-io/conan/assets/43919146/d7926bfe-3db9-4827-b5e0-aa4d3c0935cd)

**Comment by Anytious** [comment]
I wonder if this is a reasonable change.

**Comment by memsharded** [comment]
> I wonder if this is a reasonable change.

I am afraid for Conan 1.X it is not. Every change has its risks, and caching is one of the most complex things in SW engineer, so even if it looks a simple change, it can have side effects and other problems that could be breaking users. So, as commented above, we are not considering at the moment these kind of changes for 1.X anymore, only important regressions, bugfixes or necessary things to upgrade to 2.0. Potential performance issues that have been like that for years in 1.X won't be addressed anymore

A possible workaround would be to clean the Conan cache. As its name implies, it is only a cache, so unless 9000 packages are used at the same time, maybe it can be cleaned and re-populated as necessary for the project?

Conan 2.0 works with a DB instead of filesystem for this purpose. Maybe this is almost instantaneous in Conan 2.0, so as suggested above, the recommendation would be to test it against 2.0 and let use know, we can consider performance improvements for the 2.0 train release. Thanks!

**Comment by Anytious** [comment]
> > I wonder if this is a reasonable change.
> 
> I am afraid for Conan 1.X it is not. Every change has its risks, and caching is one of the most complex things in SW engineer, so even if it looks a simple change, it can have side effects and other problems that could be breaking users. So, as commented above, we are not considering at the moment these kind of changes for 1.X anymore, only important regressions, bugfixes or necessary things to upgrade to 2.0. Potential performance issues that have been like that for years in 1.X won't be addressed anymore
> 
> A possible workaround would be to clean the Conan cache. As its name implies, it is only a cache, so unless 9000 packages are used at the same time, maybe it can be cleaned and re-populated as necessary for the project?
> 
> Conan 2.0 works with a DB instead of filesystem for this purpose. Maybe this is almost instantaneous in Conan 2.0, so as suggested above, the recommendation would be to test it against 2.0 and let use know, we can consider performance improvements for the 2.0 train release. Thanks!

Thans a lot!

**Comment by memsharded** [comment]
Closing as responded and most likely solved in Conan 2.
But please create new tickets reporting against Conan 2 if there are any further issues or questions. Thanks for the feedback!
