### ISSUE TITLE
[question] Skipped binaries & compatible configurations

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#14486]
### What is your question?

When a binary of a C++ package is skipped during a conan install (for example because it's a tool requires of a package already available in cache), I see that there is still a compatible configuration check of this skipped package. These checks are very slow (when I have many C++ dependencies I really want to remove compiler.cppstd from my profile honestly) and the only way to speed up conan install in this case is to install these skipped binaries in cache so that compatible configuration is not run anymore for these packages, but it defeats a little bit the concept of skipped binaries.

Could these compatible configurations checks be skipped if conan already knows that package is not necessary?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
I am afraid it is not possible, this would be a chicken and egg problem.
You don't know that a package will not be needed until the consumers of the package are checked, and we know if they have to be built or not. But to compute the ``package_id`` of the consumers in order to know if they exist or not, it is necessary to know first the ``package_id`` of the dependencies, because they can be used in the computation of the consumers ``package_id``.

So the computation of compatible configurations must happen before knowing if binaries can be skipped or not.

**Comment by SpaceIm** [comment]
Thanks, I see. Wouldn't be possible to check candidates to skip binaries in a second step? If they are only part of tool_requires of binaries already available, it's useless to check their package id.

**Comment by memsharded** [comment]
The candidates to skip binaries is computed the last step in the computation of binaries. But compatible_configurations still need to be computed first, it is necessary to compute the ``package_ids`` and without the ``package_ids`` it is impossible to know which binaries exist and what not, and then it is impossible to compute which binaries to skip. As commented above, it is simply impossible, by definition of the problem. The only possibility is to improve the speed of computing the compatible configurations, which is already planned.

**Comment by memsharded** [comment]
Closing as responded and inactive.
