### ISSUE TITLE
[bug] Environment variables paths created relative instead of absolute paths

### ISSUE THREAD

**Issue by mikirothman** [conan-io/conan#14484]
### Environment details

* Operating System: windows
* Compiler+version: msvc 191
* Conan version: 2.0.5
* Python version: 3.9.13

### Steps to reproduce

1. conan install . --profile vs2017_64_release.
2. MYPATH variable at testerrunenv-release-x86_64.bat generated script is relative.
3. I've added a print to make sure that the variable to define_path is absolute.

[test.zip](https://github.com/conan-io/conan/files/12344410/test.zip)

**Comment by memsharded** [comment]
Hi @mikirothman 

Thanks for your report.

Not sure what could be the problem here. Some paths are made relative as explained in:
- https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html
- https://docs.conan.io/2/examples/extensions/deployers/dev/development_deploy.html

The paths are made relative to the current .bat file (which in practice make them absolute) using the ``~dp0`` idiom pointing to the current script. This is important to make the scripts relocatable, in your case it is ``set "MYPAYH=%~dp0\..\..\data"``, but this shouldn't be a problem, because that is still an absolute path pointing to the right folder, when the ``.bat`` file is called the ``~dp0`` will expand to the absolute path.

**Comment by mikirothman** [comment]
Thanks for the clarification,
I wasn't aware of the mechanism behind ~dp0 and it's path expansion.

**Comment by memsharded** [comment]
No problem, glad to help.
Don't hesitate to open new tickets if you have any further question or issue.
