### ISSUE TITLE
Why does `package_files` command require a package reference?

### ISSUE THREAD

**Issue by cleeland** [conan-io/conan#1449]
The package information is already embedded in the required `conanfile.py`, so why must I repeat myself on the command line?

**Comment by cleeland** [comment]
Your second point is very interesting. This decoupling aspect--the fact that the recipes operated upon are in the repository--is not well-communicated, IMHO, and may explain some fundamental disconnect I have been having with experimenting with conan.

I'm not sure I *like* the decoupling, and it doesn't seem to be consistent throughout all the commands/actions.  But *understanding* that it's there is critical to "thinking like conan", so I would encourage you to document this far more clearly.

**Comment by cleeland** [comment]
To the first point, it seems that, like `export`, everything except the 'user' could be optional if the recipe is in the current directory.

**Comment by memsharded** [comment]
It is not a matter of ``liking`` it or not. I am not a big fan of ``conan package_files`` either, as well as other parts of conan, like ``conan-cmake``, the ``scopes``, etc. But even though, I implemented it.

I much prefer the regular flow with ``build()`` and ``package()`` methods in the package recipe because it is much more reproducible and explicit than ``package_files`` command.

But ``conan package_files`` is the way it is, because it was requested this way. In this case, there is a github issue: https://github.com/conan-io/conan/issues/1112. I also remember some conversations, slacks, chats and emails about this topic with different users. And it made sense the way it is right now.

It is not only the user, you also must specify the channel. So in the worst case we are discussing about these two alternatives:
```bash
$ conan package_files PkgName/1.2@user/channel
vs
$ conan package_files user/channel
```
That is, we would be saving like 10-30 keystrokes? And this is a simple case. In real cases, those external builds are big monolithic builds that they want to split the different artifacts into different packages. And those big builds are already being done in CI, so no need to re-type anything, as it will be scripted in the CI job. This is a real use case. So the python zen: "better explicit than implicit" sounds like a good decision here.

**Comment by cleeland** [comment]
For `export`, the channel defaults to `testing`.  I see no reason thus far that `package_files` could not do the same.

This is not about saving keystrokes, but about violating DRY (don't repeat yourself). Whether done in CI or not, violating DRY is a maintenance issue.

In my case, I have exactly what you're describing--a giant monolithic repo that I'm try to evolve to something more manageable.

**Comment by memsharded** [comment]
> For export, the channel defaults to testing. I see no reason thus far that package_files could not do the same.

That is a bad default, supported only for legacy reasons. I'd say that it is not documented, and in the docs, it should appear everywhere the full version ``conan export user/channel``

I cannot agree more about DRY. Actually, you are repeating yourself much more if for every ``conan package_files`` that you are running in quite different places you also have to run a ``git clone`` or get the recipe from somewhere else, create a duplicated of the file, that will be used **only** to get the package name and version, because the recipe is already in the local cache and you don't need to export it every time you are doing ``conan test_package``. In my opinion it involves less repetition and is more explicit and clear to use directly the package name and version than having to clone the recipe to get them.

**Comment by cleeland** [comment]
> That is a bad default, supported only for legacy reasons. I'd say that it is not documented

It's in the output of `canon export -h`

**Comment by cleeland** [comment]
> you are repeating yourself much more if for every conan package_files that you are running in quite different places you also have to run a git clone or get the recipe from somewhere else, create a duplicated of the file, that will be used only to get the package name and version, because the recipe is already in the local cache

The way I was __thinking__ that I'd be using `package_files`, my monolithic legacy build system would add a new step that generated a conanfile.py filling in all of the information.  My monolithic legacy repository would effectively be the "local cache" and own conanfile, etc.  I would export every time from each build because the recipe could change from run to run (based on what those who maintain that subset of the legacy repository decide).

Having the `conanfile.py` in the local cache, decoupled from the "owning" project seems like an opportunity for skew-induced error.

**Comment by memsharded** [comment]
The ``package_files`` command was deprecated in favor of ``export-pkg``, with most of the feedback in this thread incorporated:

- Now ``export-pkg`` requires a *conanfile.py* in user space, not in the conan-cache. It is more aligned with the rest of the local development flow commands.
- ``export-pkg`` is able to do exact copies of a folder, but also to execute the ``package()`` method to filter files and define package layout

So I think this issue can be closed now, please open a new issue referring to the new ``export-pkg`` command if necessary. Thanks!
