### ISSUE TITLE
[question] When can one use the "visible=False" requires trait

### ISSUE THREAD

**Issue by tgurriet** [conan-io/conan#14498]
### What is your question?

Hello,

I have a question regarding what's explained in this [ACCU talk](https://youtu.be/kKGglzm5ous?t=1508).

In particular, what are the different cases under which it's safe to use the "visible=False" trait in a requires clause?

The video talks about the case where engine/1.0 is a shared library.

In the case where engine/1.0 is a static library, isn't it still OK provided that the math library simultaneously:
- is header only
- is used fully privately by ai/1.0 and engine/1.0
- uses symbol versioning

?

Are there other cases where it's OK to use the "visible=False" trait that I'm missing?

Conversely, if there are configurations where it's absolutely not possible, it could be useful to generate an error at the conan level. Like maybe if engine/1.0 and math are both static libs?

Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tgurriet 

Thanks for your question

> In the case where engine/1.0 is a static library, isn't it still OK provided that the math library simultaneously:

yes, the case you expose with header-only, with symbol versions, full private, etc. can also be used with ``visible=False``, and it will allow to use different versions of ``math`` upstream. The diamond structure of the graph breaks, and it will be a tree structure with 2 nodes (leaves) of the ``math`` library (even if it is the same version, there will be 2 nodes in the graph).

Note that there is also difference in "being able to" and "wanting to". Even if in this case it would be possible, most of the time it can cause issues, and the divergence of versions cause confusion and more work to developers. I would only use it when it is very necessary to do the version divergence for strategic or organizational reasons.

> Conversely, if there are configurations where it's absolutely not possible, it could be useful to generate an error at the conan level. Like maybe if engine/1.0 and math are both static libs?

The converse is not possible, and Conan could raise false positives, which are very bad because they are blocking users.
It is possible, for example ``math`` can be a static library, ``engine`` be a static library that re-archives the ``math`` one inside it and they want to avoid the double propagation and linking errors that it can produce. Not a very common case, but I have seen a couple of times in production.

**Comment by tgurriet** [comment]
@memsharded Thanks for the insight!

So you confirm that without re-archiving `math`, it will cause issues?
Also isn't the case of the dynamic library also dependent on how this library is loaded (RTLD_GLOBAL vs RTLD_LOCAL)?

Indeed, I'm not suggesting it's a good idea to do so. For us it's an issue that arises when we're deploying our conan package to be consumed outside of the conan ecosystem, alongside other libraries that we don't have a lot of control over.

Makes sense that if conan doesn't have all the info necessary to determine this with 100% certainty it shouldn't be generating errors.

Maybe a warning could be generated, with the list of things to check depending on what type of library it is and how it is being consumed?

Also

**Comment by memsharded** [comment]
> So you confirm that without re-archiving math, it will cause issues?

Yes, if everything is static libraries, and normal linkage downstream, it will most likely cause missing symbols.

> Also isn't the case of the dynamic library also dependent on how this library is loaded (RTLD_GLOBAL vs RTLD_LOCAL)?

yes, dynamic libraries are also visible, they cannot be made invisible unless you copy them (re-package), in the consumer (something that also happens).


> Maybe a warning could be generated, with the list of things to check depending on what type of library it is and how it is being consumed?

The ``visible=False`` trait is not recommended for most cases, and I think it is documented as such. If it isn't then maybe we should clarify that in the docs. But if it is something that is opt-in and it is clearly explained in the docs the possible pitfalls, then it is not necessary to generate warnings (these warnings take too much effort to implement, for little value, as very few users actually read the warnings and act to fix them). But thanks for the suggestion, we will check the docs and try to improve them if necessary.
