### ISSUE TITLE
[question] build_policy = "missing" in conanfile.py does not seem to work

### ISSUE THREAD

**Issue by tmiseikis** [conan-io/conan#14500]
### What is your question?

Hi,

My assumption was that specifying:
`build_policy = "missing"`

in conanfile.py meant that the dependencies that do not exist in my specified configuration would be built automatically, however, it seems like this is not the case. I get the following error:

```
ERROR: Missing prebuilt package for 'argon2/20190702''
Check the available packages using 'conan list argon2/20190702:* -r=remote'
or try to build locally from sources using the '--build=missing' argument

More Info at 'https://docs.conan.io/2/knowledge/faq.html#error-missing-prebuilt-package'
```

So essentially I have to manually specify **--build=missing** setting when running the conan command even though I have already specified it in my conanfile.py.

Is this a bug or have I misunderstood something?

Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tmiseikis 

Thanks for your question.
Yes, the ``build_policy`` (same the ``upload_policy``) applies only to the current recipe package, check  the docs in 
 https://docs.conan.io/2/reference/conanfile/attributes.html#build-policy

Allowing this to propagate the graph upstream will easily create conflicts, with different competing policies in diamond structures. The reason why the command line ``--build`` is required is that by default, in production, binaries should be found for the builds. The ``--build=missing`` is dangerous for production, because CI jobs can be rebuilding over and over the same things from source because some initial job failed to create and upload the right binary. The ``build_policy`` is not intended to remove the need to add ``--build=xxx`` in the command line when necessary, it is intended for packages that contains things like drivers or anything that really must be compiled in the final target machine (working together with the ``upload_policy``)

**Comment by tmiseikis** [comment]
I see. Thank you for the explanation @memsharded !
