### ISSUE TITLE
[question] Can conan check all remote then download the package from server without building from source?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan#14514]
### What is your question?

Suppose I already upload boost/1.75.0 to my own server and conan remote add , then I write boost/1.75.0 in my conanfile.py requirements, can conan download first check all remote server and get the package from my own server not build from source? 
I need to achieve this in cicd docker, so maybe achieve this by modifing conanfile.py?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tumb1eweed 

Thanks for your question.

Yes, Conan can download the pre-compiled binaries from your own server, just by adding it with ``conan remote add`` (and making sure the package you need is there). No need to modify the ``conanfiles`` at all, one thing is the "abstract" requires of ``boost/1.75.0``, and other decoupled thing is the definition of remotes where to fetch packages.

There are several possibilities:

- Insert your remote with top priority, the first one in the list with ``--index=0``
- Explicitly use your ``-r=myremote`` in commands to prioritize it

In practice, for production environments it is even recommended to drop the ``conancenter`` remote and use only your own server, that can store a copy of the packages you need in production. You can pre-populate it from packages from ConanCenter, then remove the remote, but depending on the use case, even compiling your own binaries for all the packages you want instead of using those in ConanCenter can be very recommended.

Please let me know if this clarifies the question.

**Comment by Tumb1eweed** [comment]
> Hi @Tumb1eweed
> 
> Thanks for your question.
> 
> Yes, Conan can download the pre-compiled binaries from your own server, just by adding it with `conan remote add` (and making sure the package you need is there). No need to modify the `conanfiles` at all, one thing is the "abstract" requires of `boost/1.75.0`, and other decoupled thing is the definition of remotes where to fetch packages.
> 
> There are several possibilities:
> 
> * Insert your remote with top priority, the first one in the list with `--index=0`
> * Explicitly use your `-r=myremote` in commands to prioritize it
> 
> In practice, for production environments it is even recommended to drop the `conancenter` remote and use only your own server, that can store a copy of the packages you need in production. You can pre-populate it from packages from ConanCenter, then remove the remote, but depending on the use case, even compiling your own binaries for all the packages you want instead of using those in ConanCenter can be very recommended.
> 
> Please let me know if this clarifies the question.

Very helpful, thank you!
