### ISSUE TITLE
MSVC compiler check fails

### ISSUE THREAD

**Issue by vadixidav** [conan-io/conan#1451]
I am trying to build this project. This is on Windows 7. I have tried in the MSYS MINGW64 shell and powershell and get the same results. I have Visual Studio 2015 Professional installed, and `cl.exe` is on the system (I have built other things in cmake with it). I have tried this with and without `cl.exe`.

This is my `conanfile.txt`:
```
[requires]
Boost/1.63.0@eliaskousk/stable
Qt/5.7.1@osechet/stable
gtest/1.8.0@lasote/stable
OpenSSL/1.0.2h@lasote/stable

[generators]
cmake
```

This is my command line output:
```
$ cmake -G "Visual Studio 14 2015 Win64" ..
CMake Error at build/conanbuildinfo.cmake:583 (message):
  This project seems to be plain C, but no compiler defined
Call Stack (most recent call first):
  build/conanbuildinfo.cmake:372 (conan_check_compiler)
  CMakeLists.txt:5 (conan_basic_setup)


-- Configuring incomplete, errors occurred!
```

[This](https://gist.github.com/vadixidav/cbda6fd2fbf74f546f82221d9e0cf434) is the offending function.

**Comment by memsharded** [comment]
Hi @vadixidav ,

I would need more info, specially regarding the installation. First, when you executed conan the first time, it detected some defaults about your environment, and printed them. Do you remember them? You can check them in your ``<userhome>/.conan/conan.conf`` file.

This were probably the settings used when you installed the dependencies from your ``conanfile.txt``, and it seems that when you are running cmake with Visual Studio 14, it is complaining, because the dependencies were installed for a different configuration than yours.

This has several solutions:
- Change your default settings in conan.conf to be the ones you want to use
- Provide your settings in the command line while installing
- Define a ``profile`` and use it in the command line while installing.

**Comment by vadixidav** [comment]
[This is my conan.conf file](https://gist.github.com/vadixidav/c860ce0c1c8843ec0552c9079c3ca9d8). Each time I've ran it, it has been in the same manner. I have also tried clearing out the build directory.

My suspicion is that, when looking at the CMake file conan generated, that it is expecting `Visual Studio 14 Win64`, whereas my CMake seems to have the generator `Visual Studio 14 2015 Win64`. I am not sure if that would throw it off. As far as I can tell, the conan configuration is probably right, but I am no expert.

**Comment by memsharded** [comment]
Could you try adding ``CXX`` in your CMakeLists.txt file? Something like:

```cmake
project(MYPROJECT CXX)
```

If you could please copy the whole output of the cmake command, that would help too. Thanks!

**Comment by vadixidav** [comment]
[Here](https://gist.github.com/vadixidav/3f4a081a68f9f805fe055c144e3dfd9b) is what it looks like on the command line. I added that CXX thing to my project and that gave the same results.

**Comment by vadixidav** [comment]
[This](https://gist.github.com/vadixidav/d290d9dddebfc0cdf9609c1fbc4208be) is the CMakeLists.txt, which I know is not currently correct, but I wan't to be able to get to that stage at least.

**Comment by memsharded** [comment]
Yes, you need to put the include and ``conan_basic_setup()`` lines after the ``project()`` declaration.

**Comment by vadixidav** [comment]
Oh, I see, that was indeed the issue. Thanks, I'll close this.

**Comment by memsharded** [comment]
Great! :)
