### ISSUE TITLE
Simplify package maintenance in conan-center

### ISSUE THREAD

**Issue by GamePad64** [conan-io/conan#1453]
So, the documentation states clearly, that conan-center's policy is to include only a single version of a library. I think, it would be way better to use only "conan" for conan-center, because the current package maintainer may become unavailable, and the package may become abandoned. So, I propose use only "conan" as username in conan-center packages to provide a way to transfer package maintainence to another person without changing the package name.

**Comment by memsharded** [comment]
Good suggestion, we also thought about it. But the thing is that the package maintenance can be only transferred if the packages come from an organization. So the suggested approach is to create organization for packages, rather than to use "conan" as user name. The name "conan" is being used to identify packages created by the conan team, because we will be maintaining many of them, and need to identify our own packages easily. Then, for organizations, the package user would typically match the name of the organization providing the package, not usernames.

That also allows us to manage transitory states. When the original author of a library wants to create conan packages in conan-center, it is not possible to directly remove the existing package (it might have older versions that the author don't want to create packages for) without breaking users. So in that case, 2 packages for the same library might co-exist. What will not happen is to have 2 different packages for the same library from third-party packagers.

**Comment by GamePad64** [comment]
What if the third-party packager abandons the library, and there is a new packager, that wants to continue the package maintainance, but the first packager doesn't want to collaborate, denying or ignoring all help requests?

**Comment by memsharded** [comment]
That is why we reserve the right to unlink from conan-center, for that extreme cases. Then new packagers will be welcomed, and become the reference package in conan-center. 
In that case, the correct thing is breaking users, otherwise it would be a similar situation than the "leftpad" NPM disaster. Users have to know that the package they were depending has been removed because of that, and a new package creator is provide packages now. But we feel it is not ok replacing packages from someone user decided to trust, without either the original author or the users knowing. Of course we hope that this only happen in very extreme cases

**Comment by GamePad64** [comment]
The problem here is that after removing a package, many other packages may have unsatisfied dependencies.

**Comment by memsharded** [comment]
There is another issue to consider. People might want to contribute packages they have for their own purposes in their projects and organizations. So forcing them to change the name doesn't look the best approach, specially if later that name will be taken from them and given to another package maintainer, that will overlap with their name, and they will have to be extra careful to make sure they are still using their package and not the one from conan-center.

> The problem here is that after removing a package, many other packages may have unsatisfied dependencies

Yes, that is true, and terrible. Sure we don't want to get there, breaking tons of user projects. But I don't feel that just replacing the dependency they were using with a new one, from another provider/packager, without them knowing, should be the right approach.  The good new is that conan, with its decentralized architecture, makes easy to make a copy of your dependencies in your own server, that ensures no one can break your builds.

**Comment by memsharded** [comment]
In any case, thanks very much for the interesting discussion and ideas. The truth is that "predictions are difficult especially about the future" (N. Bohr, I think). There are many trade-offs to consider, and we think that with the current info it is slightly more balanced towards not using "conan" for all usernames. But your points were very valid, and maybe we are wrong, and in the future this has to change. Lets see...
Cheers!

**Comment by GamePad64** [comment]
Thank you, too!

**Comment by GamePad64** [comment]
I am now watching at [Homebrew](https://github.com/Homebrew/homebrew-core/tree/master/Formula) and [MSYS2](https://github.com/Alexpux/MINGW-packages) central repositories, and their repository approach seems more simple and "collaborative" to me.

The point is: sometimes, I really do not want to maintain the package. I don't want to create my own repo, issue tracker, reply to issues, review all the pull requests and so on.
So, I just want to create an initial package recipe, without further maintaining it. Is there any movement in this direction?

**Comment by memsharded** [comment]
I am not sure what you mean. For sure you can create conan packages in bintray, just create your own bintray repo and upload your packages there. That is not moderated, so you can do it freely. You can use that packages and also other people can use them, just by adding your bintray repo as remote. 

But for conan-center, this is definitely to be avoided, please note that people was getting packages from old conan.io and discouraged because they didn't work and they were undermaintained. 
Homebrew and MSYS2 are a different story, as they only serve a very specific community, and it is much easier to achieve properly working packages. But what happens if you upload a famous library to conan-center, and only provide support for 1 OS, like Windows, and refuse to collaborate to provide other binaries. All users from other OSs will be annoyed, because they will be blocked with a useless package in conan-center.

**Comment by cleeland** [comment]
>what happens if you upload a famous library to conan-center, and only provide support for 1 OS, like Windows, and refuse to collaborate to provide other binaries. All users from other OSs will be annoyed, because they will be blocked with a useless package in conan-center.

This sounds like a different problem to me, almost like recipes for different "platforms" should not be required to all be lumped together into a single recipe class as they are now.  For example, I look at the official recipe for boost and it's really complicated--and it has a very script-like feel to it rather than being declarative.  Things that are that complicated have to be tested and debugged, and that starts to sound like more than what a recipe should be.

**Comment by GamePad64** [comment]
> But what happens if you upload a famous library to conan-center, and only provide support for 1 OS, like Windows, and refuse to collaborate to provide other binaries.

I want to be able to add famous libraries to conan without being responsible for maintaining them **forever**.

Look, conan had a problem, that it had multiple copies of a single library, but all the copies were undermaintained in various places. Now, the rules are much stricter (mandatory cross-platform binary packages, CI, etc.), and no one wants to contribute the third-party libs to conan because they don't want to take the whole responsibility for these libraries. This is a huge problem because now conan-center is empty, and people don't have much motivation to fill it.

**Comment by memsharded** [comment]
> I want to be able to add famous libraries to conan without being responsible for maintaining them forever.

Of course you can. There is no "contract", "liability" or nothing related that forces you to maintain packages forever. But a minimum commitment is recommended, it doesn't make sense to provide them and forget about it. If that is the plan, yes it makes more sense try to collaborate with the library authors, or with someone else that might help in the task, and put it under an username that might make sense to others as well. The worse it can happen if you decide in a while not to maintain that library anymore, is that it might be removed from conan-center to leave space to a better maintained one.

> no one wants to contribute the third-party libs to conan because they don't want to take the whole responsibility for these libraries. This is a huge problem because now conan-center is empty, 

That is not true. There are already a few tenths of libraries for inclusion requests pending to process, it is just that we didn't have the time to review them, and I apologize for that. 

We had to provide new CI scripts for travis and appveyor, that were released just 3 weeks ago, and have been making several releases since then to conan-package-tools, because there were bugs related to the new upload to bintray and the changes in travis and appveyor. And now, we are starting to have official packages, like the Poco one, provided by the original authors, and Catch, which some conan users are collaborating with them to also provide official packages, something that didn't exist in conan.io, just 3 weeks after the release.

So it is not because of lack of motivation, as the quality requirements are much higher, it simply takes more time.

**Comment by GamePad64** [comment]
Maybe, I am a bit critical about the fate of conan-center. I would like to see lots of high-quality packages out there, but it will take some more time.

**Comment by memsharded** [comment]
It is good to be critical, and thanks very much for your feedback on this. We really learn from it and take it into account. Cheers!
