### ISSUE TITLE
[question] Reusing conan cache across multiple conan versions

### ISSUE THREAD

**Issue by SzBosch** [conan-io/conan#14547]
### What is your question?

Hello together,

is it ok, to reuse the same conan cache across multiple conan versions or can there be any trouble?

Scenario:

1. Single machine with a directory e.g. /conan_cache
2. Multiple Docker images with different conan versions e.g.: 1.47.0, 1.59.0, 1.60.1
3. When a short-running docker container is created, the /conan_cache is mounted into the container as volume and conan is configured to use this as storage/cache path
4. Within the container a workflow is processed with install ... export-pkg, upload.
5. a) Only one docker container is running at the same time.
    b) Multiple docker containers running at the same time in parallel.

Regarding 5. a): Is it safe, that e.g. a conan install with version 1.59.0 is using a package from the cache which was previously populated with 1.60.1 or 1.47.0?
Are the metadata files like conaninfo and conanmanifest compatible across versions?

Regarding 5. b) Would cache locking work in this scenario or could there be race conditions?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @SzBosch 

The Conan cache has a migration mechanism that will run automatically when it detects a new Conan version and using an old Conan cache: https://github.com/conan-io/conan/blob/develop/conans/client/migrations.py

The latest big migration happened in 1.40, but for example the ``settings.yml`` is automatically migrated at every new version. This can produce issues. In general adding new things to the ``settings.yml`` will not be breaking, but it could at some point. I think for the range of versions you are describing, it should be possible, but not strictly guaranteed. At the very least it will create some instability, because different versions will be overwriting the cache ``version.txt`` file that stores the current Conan version, and it can force a new overwrite of the ``settings.yml`` file too.

In any case, exclusive access is needed. Multiple docker images running concurrently will likely produce race conditions and other problems.

**Comment by SzBosch** [comment]
@memsharded: Thank You for your answer.

The settings.yml and other files are not in the directory which I meant as "conan cache". I mean only the "data" directory itself which is located at /conan_cache and reused.
The other files in the conan home are always setup from scratch in each docker container run within the container only.

So can we rely on file files like conaninfo and conanmanifest are compatible across versions (within the same major of conan)?

**Comment by memsharded** [comment]
If only the package storage is reused, then it might be ok, for that range of versions, but not for the same major of Conan.
For example Conan 2.0.11 will be adding a migration to the package storage, to allow the DB in that package storage to have the LRU timestamp column. That means that you cannot apply this strategy for Conan version <2.0.11 and >=2.0.11

**Comment by memsharded** [comment]
Hi @SzBosch 

Any further question here? Can we close this ticket as resolved?
