### ISSUE TITLE
[question] error in `conan list pkg -p `

### ISSUE THREAD

**Issue by BrainLyh** [conan-io/conan#14544]
### What is your question?

Hi, I encountered an error when I ran `conan list openssl/3.0.5:* -p arch=x86_64 AND \(build_type=
Release or os=Linux\)`.

I'm trying to select some specific pkgs and follow instructions：
 ```
-p PACKAGE_QUERY, --package-query PACKAGE_QUERY
                        List only the packages matching a specific query, e.g, os=Windows
                        AND (arch=x86 OR compiler=gcc)
```
but got error:
```
conan list: error: unrecognized arguments: AND (build_type=Release or os=Linux)
```

conan version：2.0.9

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @BrainLyh thanks for your question.

You probably need to quote the whole contents of the package query, like so:
`conan list openssl/3.0.5:* -p "arch=x86_64 AND \(build_type= Release or os=Linux\)"` to differenciate it from it being a new argument to the program itself instead of part of the query :)

Let me know if that helps!

**Comment by BrainLyh** [comment]
Hi @RubenRBS thanks for your quickly reply !

It works! And don’t need the `'\'`
```
conan list openssl/3.0.5:* -p "arch=x86_64 AND (build_type=Release or os=Linux)"
Local Cache
  openssl
    openssl/3.0.5
      revisions
        a50b5d6f715a0d90c4d9e3c5d1fe3b16 (2023-08-21 14:27:55 UTC)
          packages
            2b010f4baf8e367a9e2df7f714b35852aa8fa5aa
              info
                settings
                  arch: x86_64
                  build_type: Release
                  ...
```
