### ISSUE TITLE
[feature] System Provided Packages

### ISSUE THREAD

**Issue by nicosmd** [conan-io/conan#14566]
### What is your suggestion?

Hey, I'm thinking about this kind of issue for a long time now and finally decided to create a feature request for this since I think there are also others struggling with that.

When dealing with `sysroots` it is a very common scenario that users consuming recipes from conan-center but want to have fine-grained control over which dependency is provided by the sysroot and therefore should not be consumed using conan. This could be the case when any vendor is providing closed-source libraries which are already linked against specific versions of Open Source dependencies in the sysroot ( https://github.com/conan-io/conan/issues/12597 ) or there are dependencies which needs to be consumed as a system package for other reasons ( https://github.com/conan-io/conan-center-index/issues/17101 ). In my project we are currently using ugly workarounds (heavily mis)using `override` and custom system package to deal with this and I would be really glad to get rid of them in future, since they are not scaling. 

There are several unresolved issues which goes in a similar direction:
- https://github.com/conan-io/conan/issues/14343
- https://github.com/conan-io/conan/issues/12478
- https://github.com/conan-io/conan/issues/12597
- https://github.com/conan-io/conan/issues/12459

and I would guess there are even more since this is a quite common use case.

Conan currently does not provide any convenient feature to archive this goal easily, which is really a pain point for us at the moment. That's why I want to already try to come up with a rough idea how this might be modeled into conan. Let's call this feature idea `System Provided Packages` for the moment.

System Provided Packages is inspired by the recently introduced system_tools feature, which allows users to define which tools are already provided by the system. Therefore I hope that the feasibility in general is given. 

Similar to `system_tools`, a new section needs to be introduced in the profile called e.g. [system_provided] where users can define, which version of any dependency is provided by the system or the sysroot and should neither be build by conan nor consumed from the conan cache. The version defined under [system_provided] should either override the version for a particular dependency in the whole graph, so that it is guaranteed that the system provided packages are being used, or show show up conflicts, which needs to be resolved upstream to have a more explicit solution.

In order to provide conan all information needed to find the system libraries and header files, a dedicated mechanism needs to be used. For this purpose pkg-config could be considered. When a dependency is specified as system provided, conan could use the pkg-config executable defined by `tools.gnu:pkg_config` in order to search for the corresponding *.pc file. The search location can be controlled using a wrapper for pkg-config by providing the necessary Environment Variables like `PKG_CONFIG_LIBDIR` and `PKG_CONFIG_SYSROOT` (see https://autotools.info/pkgconfig/cross-compiling.html). It should be possbile to define the `tools.gnu:pkg_config` in either profiles or tool requirements to allow sysroot packages and system-wide installed sysroot respectively. Conan will then search for the pkg-config file named like the dependency (zlib/x.y.z -> zlib.pc) and invoke them using the existing PkgConfig helper internally (it might yield an error if the version defined in the profile and the version of the pc file does not match). 

With the information retrieved from the `*.pc` files, conan can add some kind of virtual dependency to the graph. This might be important to make sure, that the system used packages influences the package_id of all consuming packages. Otherwise, it might be not guaranteed that the graph is going to be rebuild when the dependency provided by a sysroot changes. The original dependency would be ignored upfront or removed from the graph afterwards.

It might be a bit controversial that this feature is then bound to pkg-config but the information about the system packages needs to be somehow retrieved, I guess and pkg-config files are a very easy to write and a frequently used standard for sysroots already.

I'm super excited what you think about the idea and the general feasibility, since a feature like this would really improve the build system of our project a lot and we could get rid of some ugly workarounds. Conan has helped us so much already to improve our build system and this is the last missing feature to become nearly perfect for us.

Thank you very much for this awesome tool you have build and I'm looking forward to your response!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nicosmd 

Thanks for your suggestion, and specially for such an elaborate reasoning and explanations.

There are 2 different things in this proposal:

- The injection, similar to ``system_tools`` of libraries-packages, not only tools. This is relatively easy and doable. The reason is that it hasn't been done yet is mostly the second point.
- The automatic extraction of package information from system sources by Conan. This is the real challenge and something that we don't consider feasible. While the pkg-config is reasonably extended in Linux world, we cannot simply implement a solution that will only work for Linux, leaving out more than one third of Conan users in Windows. Because it will not work for Windows. Even in Linux the approach will have many rough edges

> For this purpose pkg-config could be considered. When a dependency is specified as system provided, conan could use the pkg-config executable defined by tools.gnu:pkg_config in order to search for the corresponding *.pc file. The search location can be controlled using a wrapper for pkg-config by providing the necessary Environment Variables like PKG_CONFIG_LIBDIR and PKG_CONFIG_SYSROOT (see https://autotools.info/pkgconfig/cross-compiling.html). It should be possbile to define the tools.gnu:pkg_config in either profiles or tool requirements to allow sysroot packages and system-wide installed sysroot respectively. Conan will then search for the pkg-config file named like the dependency (zlib/x.y.z -> zlib.pc) and invoke them using the existing PkgConfig helper internally (it might yield an error if the version defined in the profile and the version of the pc file does not match).

This is exactly my concern. We have been there in the past, similar approaches for very similar problems. It tends to be quite problematic, too many corner cases, unhappy users because of feeling like half-baked thing, etc. This is one of the reasons why Conan is so explicit and it requires the users writing their own ``cpp_info`` inside their ``package_info()`` methods, even for packages that create their own .pc or .cmake scripts with that information. The extraction of that information is typically complicated and challenging, very fragile, too many corner cases.

> With the information retrieved from the *.pc files, conan can add some kind of virtual dependency to the graph. This might be important to make sure, that the system used packages influences the package_id of all consuming packages. Otherwise, it might be not guaranteed that the graph is going to be rebuild when the dependency provided by a sysroot changes. The original dependency would be ignored upfront or removed from the graph afterwards.

This is already done by the ``[system_tools]`` approach, and it would be the same for other library packages, exactly as you describe, an "empty" dependency with that name and version is added to the graph, and other packages depend on it. A few extra things might need to be tuned, but this makes sense. However it is important that the right versions of the sysroot are encoded in the information passed to Conan, otherwise it can be challenging to obtain them too.

> It might be a bit controversial that this feature is then bound to pkg-config but the information about the system packages needs to be somehow retrieved, I guess and pkg-config files are a very easy to write and a frequently used standard for sysroots already.

Exactly, this is one of the pain points, the scope is quite limited, and users will inevitably want and demand Conan to provide a general solution for this.


In short, I'd be happy to move this idea forward, because I understand the use case and it makes sense, but with the following principles:
- The definition of the ``[system_packages]`` could be similar to ``[system_tools]`` and similar behavior but for host libraries
- Conan will not try to be smart and detect from the system, but will need user definition of it, with some plugin, api, conan recipes or whatever. This is probably close to the ``xxx/system`` recipes that we already have in ConanCenter, but not exactly the same, because they need some kind of versioning and also some different approach to define the ``override`` of the dependency. This is the main thing that requires investigation and design and architecture it.

This wouldn't be a high priority at this moment, assigning this to the 2.X roadmap for discussion after finishing the stabilization of the 2.0 train release (once 2.1, 2.2 start and also ConanCenter deprecates 1.X)

**Comment by memsharded** [comment]
This https://github.com/conan-io/conan/pull/14871 PR could be addressing this

**Comment by nicosmd** [comment]
Hey @memsharded,

I've already observed the PR and I think it would address the core of the feature request.

As I understand it would be possible to set something like

```text
[system_deps]
zlib/*: zlib/system
```

right? So every requires of zlib would be resolved using the system package. That would be exactly what we need in order to get rid of the overrides and if/else in all the conanfiles where this is needed. I really like the simplicity compared to the solution I had in mind. 

What still would not be possible is that if I have system package like zlib/system, which uses e.g. PkgConfig to find the lib, the headers and the actual version of zlib found in the sysroot, that I can somehow tell conan what the actual version of zlib is. That could be helpful to still be able to use version ranges to specify compatibility. For example: liba requires `zlib/[>2.0]` and I use now the new feature to inject zlib/system instead, it would be great to get an error, when the found zlib version in the sysroot was below 2.0. Do you think a mechansim for this could be feasible? However, I think it is not super crucial to have something like this and the PR is really covering the most we need to be able to better handle sysroots in future. I'm super glad that you have found the time already to investigate a solution. Thank you very much!

**Comment by memsharded** [comment]
The idea is that in most cases the right approach would be:
```
zlib/1.2.13: zlib/system
```
When the system lib is 1.2.13. Then if there are recipes requiring another version or a version range not including it, it will fail.

**Comment by nicosmd** [comment]
That makes perfect sense. And since I have different profiles for every cross-compilation platform, I can still reuse the same system package for all and just set the exact version of the sysroot in the `system_deps` section of that profile. It's so ingeniously simple and covers 100% of what we need. That's so great! I'm looking forward to the PR being merged. Thank you so much!

**Comment by jasal82** [comment]
Is there any chance that this feature can be backported to 1.x?

**Comment by memsharded** [comment]
I'd say it is almost impossible to have this in Conan 1.X.
The dependency resolution algorithm is completely new in Conan 2.0. The new architecture and design in Conan 2.0 is what allows to add these new features with relatively low risk and medium effort. Doing the equivalent in Conan 1.X is high effort and high risk in general, so this is why this is very unlikely to be backported to 1.X.

**Comment by KerstinKeller** [comment]
I would love to see this happen. Basically this is what I was talking about when I asked about "default-versions" a year or two ago. We also have workarounds atm to somewhat model it, but this would be way cleaner.

It would be especially great, to modify a system recipe for a system dependency which contains additional (meta) information:
``` 
boost/1.71.1: boost/ubuntu-20
```

The `boost/ubuntu-20` package can contain additional information about the actual system packages (e.g. the names of their dev and runtime versions), and this information can be accessed by custom generators, e.g. to generate dependency information for packages being deployed in .deb format.

Also, I would see the platform as something static - unmodifyable, the base on which the software is being build. If it did change, it would have to result in more or less all packages having to be rebuild. However Conan doesn't really know all that much about the platform being used, so everything really that results in compatiblity breaks - eg. package hashes, needs to be reflected in the profile.

**Comment by memsharded** [comment]
This has been closed by https://github.com/conan-io/conan/pull/14871, for next 2.0.15.

Still there is another potential part for this in https://github.com/conan-io/conan/pull/15136, more related to the last comment by @KerstinKeller too, please track that one.

**Comment by nicosmd** [comment]
Thank you very much @memsharded ! It's so great that this feature already made it into the next release.
