### ISSUE TITLE
[bug] Package_Id could be differ for same options if default value for options is None

### ISSUE THREAD

**Issue by xandox** [conan-io/conan#14574]
### Environment details

* Operating System+version: Ubuntu 22.04 #  not sure it's matter
* Compiler+version: gcc 11 # not sure it's matter
* Conan version: 2.0.9
* Python version: 3.9  # not sure it's matter

### Steps to reproduce

1. take a recipe with option with default value is None, for example ICU (it has option `dat_package_file` which is None by default) 
2. make a package without setting options `conan create . --version 73.2 -f json > no_options.json`
3. make a package with setting options `conan create . --version 73.2 -f json -o 'icu/*:dat_package_file=None' > with_options.json`
4. `diff no_options.json with_options.json`
5. package_ids will be different 

I have not found any way to set option from command line to make package_ids same despite the 'None' value acts as false if casted to bool  `if self.options.dat_package_file: ....`

**Comment by memsharded** [comment]
Hi @xandox 

Thanks for your report.

The special ``None`` value for options has a special meaning that is "not defined". As such, it is not possible to define it via command line with ``-o 'icu/*:dat_package_file=None'``, as it will be understood as the literal ``"None"`` and not fail because the option accepts any value ,as it is defined in the ICU recipe as ``"dat_package_file": [None, "ANY"],``. If you check with ``conan list *:*`` you will see that the option is the literal string ``"None"`` instead of not being there at all.

This doesn't seem a bug then, but expected behavior. The expectation is not to pass ``-o 'icu/*:dat_package_file=None'`` in the command line.

**Comment by xandox** [comment]
Ok, Is there any documentation mention that behaviour?

**Comment by memsharded** [comment]
In https://docs.conan.io/2/reference/conanfile/attributes.html#options, we can find:

```
By default any value change in an option, changes the package_id. Check the default_options field to define default values for the options.

Values for each option can be typed or plain strings ("value", True, 42,…).

There are two special values:

None: Allow the option to have a None value (not specified) without erroring.
"ANY": For options that can take any value, not restricted to a set.
```

It is not that explicit that a ``None`` value cannot be passed in command line, it was implicit in the ``not specified`` definition

**Comment by xandox** [comment]
Ok, if it by desine.
