### ISSUE TITLE
[question] Checking changes in Conan recipe

### ISSUE THREAD

**Issue by Wizradus** [conan-io/conan#14592]
### Checking changes in Conan recipe

Hi, I have question regarding to checking changes for Conan recipes (we're using version 1.60.2).
I'll try describe situation what I have observed and hope so someone point me to the right way, how to manage this.
We have two version of settings, one for 32b architecture and one for 64b. This setting is taken from system variables in commandline. Recipe is shared for both architectures. Packages are in Artifactory.
Sometimes when we manually rebuilt 32b version, recipe was not changed, package ID didn't change, but 64b package has been marked as outdated. And this state hasn't changed after build of 64b.
We supposed that is because we are stored SCM information directly in recipe. So we have set _scm_to_conandata = True_ in conan.conf. Currently we store scmdata in conandata,yml, but change in this file still have impact to conanmanifest.txt.
Hash of _conandata.yml_ is used to identify changes.

- Am I possible remove conandata.yml from using in conanmanifest.txt?
- Can I remove this "outdated" behavior in other way?
- Do I have possibility to keep things unchanged until there will be direct change in recipe?

Thank in advance for your information and ideas.
BR Rad

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Wizradus 

> Sometimes when we manually rebuilt 32b version, recipe was not changed, package ID didn't change, but 64b package has been marked as outdated. And this state hasn't changed after build of 64b.
We supposed that is because we are stored SCM information directly in recipe. So we have set scm_to_conandata = True in conan.conf. Currently we store scmdata in conandata,yml, but change in this file still have impact to conanmanifest.txt.
Hash of conandata.yml is used to identify changes.

Yes, the ``scm`` information must be identical for the 32b and 64b builds. The same source builds different binaries, it is not allowed to do otherwise.

At this point, you should have revisions enabled. This is very important, as Conan 2.0 always uses revisions, and it is the recommended approach for 1.X. It means that if you change something, including the ``scm`` information stored in the ``conandata.yml`` you will get a new recipe revision and it will be mandatory to build the 64b binaries for that exact recipe revision.

> Am I possible remove conandata.yml from using in conanmanifest.txt?

This is not possible, and it would be breaking any immutability and reproducibility promise. It is critical that ``conandata.yml`` is used in the ``conanmanifest.txt`` and in the recipe revision

> Can I remove this "outdated" behavior in other way?

Using revisions ``outdated`` shouldn't happen anymore. But it will be mandatory to build binaries for the different configurations for every new recipe revision.

> Do I have possibility to keep things unchanged until there will be direct change in recipe?

The key is guaranteeing that the right ``exports`` and the right ``scm`` is managed, to make sure the same sources are used for all different binary configurations being build. Having different sources for different binary configurations is a model error and should be avoided.


I hope this clarifies a bit the issue, please let us know. Thanks!

**Comment by Wizradus** [comment]
Thank you @memsharded for your information.

As I have checked some time ago, so problem is really in SCM information in conandata.yml in automated revision.

```
.conan:
  scm:
    revision: '253262'
    type: svn
    url: https://svn... ____ java@253262
```
   
```
.conan:
  scm:
    revision: '253264'
    type: svn
    url: https://svn... ____ java@253264
```

I want to clarify one thing, when we'll switch to revision, still will be possible to see "outdated" in information about package. But this information won't be relevant anymore. Then we should also get rid job which is cleaning the outdated packages, because it can cause troubles?

**Comment by memsharded** [comment]
Yes, for some reason the url and the revision is changing and it shouldn't. Both 32b and 64b variants should build from the same revision, not different revisions.

> I want to clarify one thing, when we'll switch to revision, still will be possible to see "outdated" in information about package. But this information won't be relevant anymore.

With revisions enabled in theory it is not possible to get ``outdated`` binaries. Because every recipe revision need to have its own binaries. It is not that it can be reusing binaries from previous revisions if you have revisions enabled, there will be no binaries for the new recipe revision. No need to have a job to clean outdated binaries, in any case it might make sense to remove old, unused recipe-revisions with its associated unused binaries.

A couple of extra important issues:
- Conan 2.0 has not implemented support for SVN. So far, all of the Conan users that were using SVN have completed their migrations to Git.
- The ``scm`` approach in Conan 1.X is also legacy. The recommended modern approach that will be Conan 2.0 compatible is in https://docs.conan.io/1/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature. It might be possible to implement it without the built-in ``SVN`` helper, just running ``self.run("svn ...")`` commands, as the ``Git`` new helper is only a thin wrapper around ``git`` command line.

**Comment by Wizradus** [comment]
Hi, again.
Sorry for keeping it open without any response. I have been testing revisions on testing environment.
As I have found revisions can help to us with lot of problems. I solved also problem with SVN revision number - I'm taking last commit number for current module and not for entire repo.
But my leading colleague reformulated goals - currently want to make Conan recipe in src folder more simple, so decided get rid scm definition here and put it automatically only in Conan cache in package export folder.
I would like ask kindly for some details...
Do we can change it in version 1.x in this way? Or scm part need to be always set in recipe?
Is it good way for this to extend class Export from conans?

Sincerelly Rad

**Comment by memsharded** [comment]
> As I have found revisions can help to us with lot of problems. I solved also problem with SVN revision number - I'm taking last commit number for current module and not for entire repo.

Thanks for the feedback @Wizradus, happy to hear that revisions can solve problems!

> Do we can change it in version 1.x in this way? Or scm part need to be always set in recipe?

Yes. There is a common syntax between 1.X and 2.0 for recipes, you are supposed to be able to write a "modern" 1.X recipe, and this recipe should work already with Conan 2.0 (the binaries are different and not overlapping/colliding, but the recipe and the recipe revision can be exactly the same)

> Is it good way for this to extend class Export from conans?

Not sure what you mean with that. In general inheritance should be avoided as much as possible. Did you mean inheriting from a ``python_requires`` via the ``python_requires_extend``?

**Comment by Wizradus** [comment]
Yes. I meant extend as inherit and override. 
There is step export in conan build, so I guessed, I can change something in this step. As I observed in src, there is not in real class Export probably. I saw some methods in export.py e.g. cmd_export(). But would be welcome any advice for best way how to change recipe in conan cache (/export/conanfile.py) and how to get path for original recipe from source code.

Thank you in advance.

**Comment by memsharded** [comment]
> here is step export in conan build, so I guessed, I can change something in this step

You can do some things in this step, yes. The ``export()`` and ``export_source()`` methods are available to do interesting things at ``export`` time. For common operations like automatically obtaining the version at ``export`` time, there is the ``set_name()`` and ``set_version()`` methods too.

>  But would be welcome any advice for best way how to change recipe in conan cache (/export/conanfile.py) and how to get path for original recipe from source code.

The recommendation is definitely do **not** modify the ``conanfile.py`` at any point not in users space, nor in the cache. The recommendation is to store dynamic information in the ``conandata.yml``, which is formatted yaml in order to be able to do automatic additions, removals, etc. Trying to modify recipe ``conanfile.py`` source code is very problematic, we have don't it in the past, it was quite painful.

> how to get path for original recipe from source code.

export methods do have access via ``self.recipe_folder`` to the user folder.

**Comment by Wizradus** [comment]
Hi, James ( @memsharded )
Thanks for yours previous advices. `self.recipe_folder` I have used successfully, we'll be using `conandata.yml` as you suggest.
Now I have last "stupid" question...
I found right place, what I want replace. It is `get_scm_data(conanfile)` in `scm.py`. I'm planning set as return value result of my working function, which is returning scm data. 
So I have package with class ConanBase(ConanFile). Inside I have created 
```
def export (self):
   path = self.recipe_folder
        scm_data = get_scm_with_svn_last_commit(path)
        self.output.info("Extending export() method with external SCM data:\n " + str(scm_data))
        self.output.info("End")
```
  This is working as expected and I got all information what I want in Export step.
  But I'm not experienced in Python and I'm stuck here, how to override original get_scm_data with my version.
  I did import from `conans.client.tools.scm import get_scm_data`,
  created new `def get_scm_data(self, path)` but I have found that still is called and executed  original code.
  Could you help  me somehow with it? I really need to find right way for this.

**Comment by Wizradus** [comment]
Finally I have solved this by changing scm variable directly in our base class. So it is working like before, but without manipulating scm directly in recipe.
I'm using export() step only as place for generating our scm values. This have, I guess, minimal impact on current code.

**Comment by memsharded** [comment]
> Now I have last "stupid" question...

No questions are ever stupid, don't hesitate to ask the questions you need 🙂 

> I found right place, what I want replace. It is get_scm_data(conanfile) in scm.py. I'm planning set as return value result of my working function, which is returning scm data.

The idea with the new approach is that it is not necessary to replace it. The recommendation is to make it explicit in your recipe, do not rely on the ``scm`` feature at all:

- Capture the info that you need in ``export()``
- Store that information in the ``conandata.yml`` yourself, explicitly, calling ``update_conandata()`` tool
- Read the information in ``source()`` method from ``self.conan_data`` to explicitly checkout yourself what you need

You have a full example in https://docs.conan.io/1/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature, I hope it helps

**Comment by Wizradus** [comment]
Hi. 
Thanks for latest information. I will play with it when I get again some spare time. 😉

I have tried to create short flow, what Conan is doing in background, because I don't found this somewhere.
Can you please take look if my information are valid:
Conan working phases:

1. Conan info: Take a list of available packages from many sources – local cache, remote repositories or Artifactory (--update switch), otherwise is looking only in local cache or Artifactory.
2. Evaluate all data necessary for computing Package_ID as option, settings and requirements (package_id() method is used). This information is created on basis of content conanfile.py in project folder.
3. Generating conaninfo.txt in project folder or Conan working folder with information about required packages.
4. Obtaining metadata for required packages with their Package_ID’s.
5. Conan try to find in packages metadata Package_ID’s, which are match Package_ID’s in conaninfo.txt.
6. If Package_ID from conaninfo.txt don’t match any of available packages, Conan can on base of its configuration finish with error about missing necessary package or try to rebuild this.
7. If needed package exist in local Conan cache, will be reused from remote downloading instead.
8. If package going to be recompiled, this might mean obtaining new source, recompute dependencies and creation package with new Package_ID.
9. New conaninfo.txt will be created and new package will be installed in cache – Conan install.

Big thanks in advance

**Comment by Wizradus** [comment]
Thanks for all information.

**Comment by memsharded** [comment]
Hi @Wizradus 

Sorry, we couldn't give feedback 2 weeks ago about your detailed flow.
It is approximately that way, but not exactly:

1. Compute the dependency graph
   - Every recipe, starting from the root one is loaded.
   - For that recipe, the settings and options, confs, are injected
   - ``requirements()`` (and build_requires) are evaluated, conditioned on the settings and options
   - The requires are expanded depth-first
2. Compute the ``package_ids`` 
  - Compute the ``package_id`` of every recipe
  - run ``validate()`` to see if the binaries are valid (can exist or can be used) o rnot
  - Compute if those binaries have to be built, downloaded from the server, are found on the cache, etc.
3. Install the binaries
  - Download pre-compiled binaries from servers
  - Build from source necessary packages if instructed.
