### ISSUE TITLE
[question] Why is CMake not finding header from transitive requirement?

### ISSUE THREAD

**Issue by wayneph01** [conan-io/conan#14600]
### What is your question?

I am using Conan 2.0.9 and assume I am missing something, but it's not obvious to me what that is...

For the first time, I am trying to build a library that references a library that also has it's own required libraries defined.
- LibA requires Sqlite3 (built locally using our profile from ConanCenter)
- LibB requires LibA

When I was building all of this in a single CMake project, all I had to do was declare Sqlite3 publicly in the LibA's target_link_libraries and all of the Sqlite includes/libs would be transitively included when compiling/linking LibB. 

Now, I am trying to build LibA and LibB in their own separate repositories/cmake projects using Conan for dependency management.  I have the following defined in conanfile.py for LibA:
```python
    def requirements(self):
        self.requires("sqlite3/3.42.0")
```
and the following for CMakeLists.txt for LibA:
```
find_package(SQLite3 REQUIRED CONFIG)

target_link_libraries(LibA
  PUBLIC SQLite::SQLite3)
``` 

In LibB, I have the following configuration in the two files:
``` python
    def requirements(self):
        self.requires("library_a/0.1.0")
```
```
find_package(library_a REQUIRED)
target_link_libraries(LibB
  PRIVATE LibA)
```

Everything in LibA installs, configures, builds, exports and is successfully uploaded to Artifactory.
In LibB, I can successfully install and configure, but run into an issue building.  When compiling a file that has a `#include "LibA.h"`, I get an error that it can't find sqlite3.h.  (I want to update the library such that the public interface doesn't have a direct requirement to expose Sqlite, but that's outside the scope of this.  For now I need to try and work with what I have.)

During the conan install step of LibB, I see `sqlite3/3.42.0: Already installed! (3 of 9)` in the cache.  During the cmake configure step, I also see `-- Conan: Component target declared 'SQLite::SQLite3'`, so it looks like everything is available...  How can I get LibA to define all the things that a Consumer will need (paths to Sqlite) so that LibB is successfully built?  I shouldn't have to explicitly find and link Sqlite, as LibA requirements will change over time, and I don't want to have to touch each consumer unnecessarily.

What am I missing?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by fschoenm** [comment]
See here in the documentation: https://docs.conan.io/2.0/reference/conanfile/methods/requirements.html#transitive-headers

**Comment by AbrilRBS** [comment]
Hi @wayneph01 thanks for your question. As @fschoenm points out, this is due to Conan not propagating the transitive dependencies headers by default.

Have you taken a look into [requirement traits](https://docs.conan.io/2/reference/conanfile/methods/requirements.html#requirement-traits)? They define how different information about a requirement is treated an propagated by Conan, and looking into your issue, it looks like that's where you will need to look into

To give a bit more context, say your dependency graph looks something like:
```mermaid
graph LR;
    libb-->liba;
    liba-->sqlite3;
```

For the general case, there are two possible cases here:
 * If `libb` directly uses functionality implemented in `sqlite3` headers, then it should properly declare that `sqlite3` is a direct dependency of itself, such that the graph looks like:
```mermaid
graph LR;
    libb-->liba;
    libb-.->sqlite3;
    liba-->sqlite3;
```
 * If `libb` does not directly use `sqlite3` but its types are part of the API of `liba`, then `liba` should set the requirement trait `transitive_headers` to `True` (And `transitive_libs` for those libs that also need the libs in the general case).
```mermaid
graph LR;
    libb-->liba;
    liba-. transitive_headers=True .->sqlite3;
```

To get a better understanding on how traits work, I'd also recommend watching [this video](https://www.youtube.com/watch?v=kKGglzm5ous) by @memsharded which deals with how Conan models this.


Let me know if this helps :)

**Comment by wayneph01** [comment]
Thank you both.  I knew I was missing something.  I'll take a look at the requirements help page and the video.

**Comment by AbrilRBS** [comment]
Great to hear! Closing as solved, feel free to re-open/create a new issue if you have further questions :)
