### ISSUE TITLE
[question] SHORT DESCRIPTION

### ISSUE THREAD

**Issue by AndersGnistrup** [conan-io/conan#14619]
### What is your question?

This might be a bug but could be a misunderstanding.

I am using conan 2.0.10 and have a conanfile.py using different build platforms (arm/intel)
During some development I needed to add support for ssl and first attempt was OpenSSL3. This works fine for host build but for target it failed due to missing FindBin.pm. Perl is in host but not om my target/SDK so I tried libreSSL instead.
Note, I also have libcurl for host for some testing

ie.
```
if self.options.model_type == 'host':
    self.requires(libcurl/7.88.1)
self.requires(libressl/3.5.3)

```
but this did not work for host since libcurl requires OpenSSL, So I added override=True to libressl.
But now I got an error telling that CMAKE could not find LibreSSLConfig.cmake ?

I did some trail and error and tried this:
```
if self.options.model_type == 'host':
    self.requires(libcurl/7.88.1)
    self.requires(libressl/3.5.3, override=True)
else:
    self.requires(libressl/3.5.3)
```
Now it compiled for target, but not for host. LibreSSLConfig.cmake was present in the /build/\<cmake-build-type\>/generators/ for target but no for host.

From the doc override should select the version, compile and, if required, generate CMake config etc but. When override is used the LibreSSLConfig.cmake seems to be missing

Is this be a bug in the recipe, a bug in conan 2.0 or just me reading doc wrong?
I suspect error is triggered when provide from two packages provide the same item, in this case openssl is present in both libressl and openssl recipe. 
  

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @AndersGnistrup 

I think there might be some misunderstanding on how dependency resolution works.
The ``libcurl`` contains an option that is defined as:
```python
"with_ssl": [False, "openssl", "wolfssl", "schannel", "darwinssl"],
```
and default to ``with_ssl="openssl"``
This resolves in the recipe as:
```python
def requirements(self):
        if self.options.with_ssl == "openssl":
            self.requires("openssl/[>=1.1 <4]")
        elif self.options.with_ssl == "wolfssl":
            self.requires("wolfssl/5.6.3")
```

The ``override=True`` can only override different versions of the same dependency, either ``openssl`` or ``wolfssl`` depending on the one that is selected using the ``option``. But magically injecting ``libressl`` is not possible, because the package name is not the same, and ``libcurl`` has no notion that this could be a replacement for ``openssl``.

Please let me know if this clarifies the issue.
Then we need to check the possible alternatives:

>  This works fine for host build but for target it failed due to missing FindBin.pm. Perl is in host but not om my target/SDK
This is not sure what is the problem, ``openssl`` has ``tool_requires`` to ``self.tool_requires("strawberryperl/5.32.1.1")`` for some cases, so this might be extended, or maybe injected via profiles ``[tool_requires]``. But probably it makes sense to solve the root issue instead of trying to change the ssl provider to an unsupported (by libcurl recipe) one.

**Comment by AndersGnistrup** [comment]
The problem is that application should link libressl and curl.
I did read the recipe for curl and noticed the option"with_ssl". Looking a bit further in in recipe only openssl and wolfssl is valid for a Linux host (I am using Linux).

So using:
```
self.requires(libcurl/7.88.1)
self.requires(libressl/3.5.3, override=True)
```
Is not possible since curl does not link to libressl.
I beleived that when libressl recipe had provides="openssl" this would be OK.

What confused me was that no error is triggered, but during build cmake can't find the libressl CMAKE config file since it is not generated. And thats what pussels me 
=> Why is the LibreSSLConfig.cmake not generated when override is used?

**Comment by memsharded** [comment]
> I beleived that when libressl recipe had provides="openssl" this would be OK.

If the recipe has the ``provides`` it will raise an error if using simultenously with ``openssl```. But you defined the ``override=True``, that means "If libressl exist somewhere in the dependencies, no matter what version it is, use 3.5.3 instead, but if it is not in the dependencies, do nothing".

**Comment by AndersGnistrup** [comment]
Thanks!
It was me not reading the docs correctly, I missed the part:
If there is no transitive dependency to override, this require will be discarded.
I should use force to get the librassl in the system but this is a bad solution.
For now I have solved it by using "libcurl/*:with_ssl": False, in my conanfile.py.

**Comment by AndersGnistrup** [comment]
Wrong, did some testing, I can not use force.

```
self.requires('libcurl/8.2.1')
self.requires('libressl/3.5.3', force=True)
```
result:
```
ERROR: Provide Conflict: Both 'openssl/3.1.2' and 'libressl/3.5.3' provide 'None'.
FATAL ERROR: conan install failed

```
So, it seems that there are two solutions.
1) Fix my SDK and provide FindBin.pm and use OpenSSL
2) add libressl to the curl recipe

**Comment by memsharded** [comment]
Indeed, if you ``force`` the dependency (even if you don't force it), it will create a conflict because it will collide with ``openssl``. The ``provides`` feature is just a "fail fast" feature to provide meaningful error messages, before getting to weird linking errors because of duplicate symbols and the like (or what is worse, runtime errors)

Your analysis is correct, those are the two possible solutions. If you think that adding ``libressl`` to curl makes sense, could be useful for more Conan users, and specially, if it is officially supported by libcurl or not, then it might be worth doing a PR to conan-center-index to add support for it. The other solution seems also relevant, not being able to use ``openssl`` for some SDK issues doesn't look great, I think I'd try to fix that.
