### ISSUE TITLE
[feature] Bring back CMake targets generator for Conan 2

### ISSUE THREAD

**Issue by ltjax** [conan-io/conan#14623]
### What is your suggestion?

The new way of injecting dependency information into CMake is a lot more verbose, complex and error prone on the CMake side than conan 1's `conan_basic_setup(TARGETS)`.

1. Need to use find_package for each dependency instead of a single include. (more verbose)
2. The name in find_package is often slightly different, e.g. ZLIB (CMake) instead of zlib (conan). (error prone, complex)
3. The find scripts often do things in a non package-manager friendly way via extra options, e.g. boosts autolinking option. Conan 1's way neatly sidestepped that unnecessary complexity. (error prone, complex, verbose)
4. find_package falls back to looking for system libs silently if not configured correctly (error prone, complex)

I'd very much like to have an option to import targets the conan 1 way with conan 2, be it as an option or a separate generator. I can see how the new way works better for 'unintrusive' conan support in libraries. But I maintain several applications that are specifically built on conan with 10-20 dependencies that are a huge pain to port to conan 2 right now.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ltjax 

Thanks for your feedback.

Conan decided to follow the ``CMakeDeps`` "transparent integration" approach in Conan 1.X (this is not exclusive of Conan 2.0, the migration to ``CMakeDeps`` should be done while in Conan 1.X, then move to 2.0), based on massive feedback against the non-transparent integration of the legacy ``cmake`` integration.

> Need to use find_package for each dependency instead of a single include. (more verbose)

It is not more verbose, it is standard, CMake recommended and Conan-agnostic way to do it. The idea is that it is not more verbose because it is not necessary to modify your existing ``CMakeLists.txt`` at all, using the standard existing ``find_package()`` calls

> The name in find_package is often slightly different, e.g. ZLIB (CMake) instead of zlib (conan). (error prone, complex)

Another massive push of the community, to have target names that matches the "upstream" target names (the one provided by the original projects or CMake). This also means that you can use Conan with existing projects without changing a single line of your ``CMakeLists.txt``


Then, there was a thing that was also super confusing for users, is having more than 1, different integrations. That was causing lots of questions, problems, support tickets, etc. People was complaining in social, reddit, etc, because Conan CMake integration was intrusive.

Finally, there is the issue that resources are not infinite. Every generator requires a lot of development, testing, documentation, support and further maintenance along years. We simply cannot have 2 different CMake integrations, it is too much effort. So we had to decide in one direction, and it was the transparent, standard CMake ``find_package()`` integration. We understand that some users preferred the explicit, custom Conan targets one, actually I liked it, but it is impossible in practice to satisfy those 2 radically opposite approaches with the resources we have.

All the necessary mechanisms for users to use custom generators are there, from using ``python-requires``, to global custom generators in the cache.

> But I maintain several applications that are specifically built on conan with 10-20 dependencies that are a huge pain to port to conan 2 right now.

in ConanCenter we had to migrate many hundreds of recipes to the new generators, we can understand the pain to migrate recipes. Still, this upgrade is independent of Conan 2.0 migration, this should happen first, (it can be done gradually, one at a time) in Conan 1.X, and once things are ready, migrating to Conan 2.0 will be way easier. We are willing to help as much as possible in the migration, don't hesitate to ask as many questions and report issues as you need.

Thanks very much for your feedback!

**Comment by ltjax** [comment]
I might not have been explicit enough what my use case is: I'm mostly (but not exclusively) building applications that are consuming conan packages. Most of them even just use a `conanfile.txt`, not a `conanfile.py`. When I add a dependency, I have to change the CMake and the C++ code anyways to use it, so it is intrusive anyways. I want my builds to be deterministic (which `find_package` is horrible for) and I prefer to have less code and less complexity to maintain. I was very happy with the old generator.

> It is not more verbose, it is standard, CMake recommended and Conan-agnostic way to do it. The idea is that it is not more verbose because it is not necessary to modify your existing `CMakeLists.txt` at all, using the standard existing `find_package()` calls

I don't see how 'being standard' makes it not more verbose. Less code makes it less verbose, and the old way was typically less code to write/read and less code executed. I just had to add the dependency to my `conanfile.txt` and my `target_link_libraries`. Now I need `find_package`s and an additional translation step too.
Again, I can see how all this does makes sense from a recipe-maintainer's perspective, but it does not for my application developer's.

The targets generator does not even have to be another generator at all. Maybe it can be done via one or two options to CMakeDeps?

**Comment by memsharded** [comment]
Thanks for your feedback.

I totally understand you, I created that ``cmake`` generator, I was an advocate of that integration and I think it had advantages, and I think you make valid points about the verbosity of the code. However, I'm afraid this approach was not necessarily well received by the vast majority of the wider C++ community as it made adopting Conan more challenging for most existing projects, and would have caused new projects to converge to a Conan-only approach, with many projects and companies not willing to take this risk while Conan was in its infancy. Modifying the ``CMakeLists.txt`` to integrate Conan was a blocker and deal-breaker for the largest part of the C++ community. I really tried to advocate for the advantages of the other approach, but there was a massive push back from the community. It is even very possible that Conan wouldn't existed today if we had decided to stuck with that approach.


> The targets generator does not even have to be another generator at all. Maybe it can be done via one or two options to CMakeDeps?

There are some hybrid options that we are exploring that could emulate the legacy behavior of the ``cmake`` generator, and we will consult with the team how best to proceed. Can't promise anything, as there many challenges and we want to avoid fragmentation in our user base, but we are investigating this and will update this issue accordingly.

**Comment by AneGris** [comment]
We are investigating the impact of migrating our SW projects (with many small modules) from Conan 1.x to 2.x and this topic is one of the bigger "oh crap" moments we have experienced.

I am making this post to point out, that you may now have satisfied a vocal group of Conan users, which was unhappy, but on the other hand have upset a previously silent group of happy users.

For what it's worth, our developers don't care about CMake "purity", they just want things to work with low effort. From their perspective, when they want to consume a new package/library, they now have to add three seemingly redundant pieces of code in separate locations (requires, find_package, target_link_libraries), where it was previously enough to add it in just one place (requires). Some even opted to use conandata.yml so that a) recipes are not cluttered with a large number of requires entries and b) (more importantly) developers don't have to touch the "scary parts" i.e. conan recipe, cmakelists.txt.

I hope that I will be able to write a custom generator that just iterates over the dependencies and creates the appropriate find_package and target_link_libraries statements, but I haven't thought too much about the feasibility/pitfalls of that plan yet.

**Comment by memsharded** [comment]
I am proposing https://github.com/conan-io/conan/pull/15207 for an aggregated form of using all dependencies with an explicit ``include(conandeps.cmake)``

The PR https://github.com/conan-io/conan/pull/15207 is for 2.0, are you upgrading directly to Conan 2.0 with CMakeDeps, or you need this feature also in 1.X for the upgrade?

**Comment by memsharded** [comment]
Hi! Any feedback here regarding #15207? Need it in 1.X too?

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/15207, for next Conan 2.0.15, feedback welcome.
