### ISSUE TITLE
[question] Environment variables for remotes in conan install

### ISSUE THREAD

**Issue by KarstenErnert** [conan-io/conan#14625]
### What is your question?

Hello everyone,

today I was working on a generic pipeline snippet for the conan usage in my company. Currently I am using version 1.60.2.
I wanted to use a conan install with the environment variables CONAN_LOGIN_USERNAME and CONAN_PASSWORD to authenticate against all my remotes. Unfortunately it didn't work and I am quite clueless, only when I used the conan user command to explicitly authenticate against the remotes, the conan install worked. Since the pipeline should be fairly generic, that would not be an option that I would like to continue with though.
Does anyone know if I may have forgotten a parameter or does the conan install simply not work with the environmental variables?

Thanks in advance.

BR,
Karsten

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @KarstenErnert 

Thanks for your question.

The way that the env-vars work, is that they are used whenever an auth challenge is launched from a server, and instead of prompting the user interactively in the command line, it will get the values from the env-vars.

In theory, remotes that don't have permissions should throw that challenge, but it is possible, depending on the security configuration of the server (which server are you using? Can you check with your server admins the server configuration?) that such an auth request will not be launched, and instead return a 404. This type of server configuration, indeed requires a prior ``conan user`` (``conan remote login`` in Conan 2.0) command, to actively get credentials to the server before a ``conan install``.

**Comment by KarstenErnert** [comment]
Hi @memsharded 
we are currently using an Artifactory Enterprise 6.19.1 rev 61901900.
Generally I think its strange, since I am having an other pipeline running, that is packaging header libs and upload them to the same instance. Here the environment variables work quite fine and I never had issues with it.
I am simply confused, why the `conan upload` behaves different then the `conan install` in my case.
From that upload pipeline I also reused most of the code for the install one.

BR,
Karsten

**Comment by memsharded** [comment]
It might be because of permissions. It is typical that an ``upload`` request triggers an authentication request from the server, and once authenticated, the tokens are cached and might be reused for other ``install`` commands? While it is possible that a pure ``install`` command doesn't even try to authenticate at all. Does this make sense?

**Comment by KarstenErnert** [comment]
strangely it somehow does. I guess then I will write a small powershell snippet to automatically authenticate here. That seems for me currently the best solution, also going further into the future.

**Comment by memsharded** [comment]
Another possibility is talk to your server admins. I think disabling anonymous usage in the repo, it should probably throw the auth request for regular ``install`` flows too.

Thanks for the feedback!
