### ISSUE TITLE
[bug] Version resolution when some parts of the graph contain fixed versions fails

### ISSUE THREAD

**Issue by antoinebardoz** [conan-io/conan#14666]
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: N/A
* Conan version: 2.0.10
* Python version: 3.10.8

### Steps to reproduce

We have a package with the following dependency graph:
```
     TOP
    /   \
 DEP    |
  \     |
   \    |
     DEPDEP
```
I tried the following:
1. TOP/conanfile.py requires ```DEP[>=0 <1]``` and ```DEPDEP[>=0 <1]```
2. DEP/conanfile.py requires ```DEPDEP/0.0.2``` (fixed version)
3. I created ```DEPDEP/0.0.2``` and ```DEPDEP/0.0.3```, both were in my cache.
4. I tried creating a lockfile for TOP (```conan lock create .```). Result:
```
ERROR: Version conflict: DEP/0.0.1->DEPDEP/0.0.2, TOP/0.0.1->DEPDEP/0.0.3.
```
This doesn't seem right to me. There is a version of DEPDEP which falls within the version range for TOP, and the version range for DEP. Why wouldn't that be picked? Is this a bug?

**Comment by memsharded** [comment]
Hi @antoinebardoz 

Thanks for your feedback.

This is expected, the graph resolution algorithm in Conan is not a full SAT-solver, it is not able to backtrack certain scenarios. 
The recommended approach would be:
- Try to converge the different dependencies to the same version ranges. If depending on ``liba/[>=1 <2]``, it is expected that  the different packages use the same expression everywhere, not different packages depending in different specific versions, because that would easily become fully incompatible, not even a full solver can solve that.
- When pinning exact dependencies, depend on those first in the order of requires. The first ``requires`` are always prioritized. In your case, if you ``requires`` first DEP, and then DEPDEP, it will be able to solve the graph to ``0.0.2`` without conflicts.

Please try that and let me know.

**Comment by antoinebardoz** [comment]
Thanks, that makes sense. Changing the order of the dependencies fixes the issue.

We do want to try to use the same version ranges everywhere, and this example was something kind of phony I created because I was trying to better understand the version resolution. This answer definitely helps.

**Comment by memsharded** [comment]
> We do want to try to use the same version ranges everywhere, and this example was something kind of phony I created because I was trying to better understand the version resolution.

It is not mandatory, but we have learned that it is a very desired property in a dependency graph in a stable state. When upgrading things to new dependencies gradually, in the transitory there might be different ranges, but the typical final goal is to be able to use the same ranges in the whole graph that allows to release new patches or minors and integrate them quickly in the whole graph without changing recipes.

Also, in order to clarify: the rule that the first requires have precedence also applies to version ranges. When different packages uses different version ranges, and some of them might be partially incompatible, the first one to be resolved wins.

Thanks for the feedback!
