### ISSUE TITLE
[question] ERROR: Missing prebuilt package for boost/1.71.0…

### ISSUE THREAD

**Issue by LukasBecks** [conan-io/conan#14690]
### What is your question?

Hello,
I am trying to set up a C++ repository for vivoka. For this I need Conan and a version lower than 2.0. I installed it according to the documentation, but when I run the compiler I always get the error 'Still the error:
ERROR: Missing prebuilt package for boost/1.71.0@vivoka/customer',
*vsdk/8.0.0@vivoka/customer,
*vsdk-csdk/4.0.1@vivoka/customer',
use conan search boost/1.71.00vivoka/customer --table-table.html
vsdk-exception/1.2.6@vivoka/customer
-p=remote
and open the file table.html to see the available packages
Or try building locally from source with '--build-boost --build=vsdk --build=vsdk-csdk --build=vsdk-exception'.
More info at https://docs.conanio/en/latest/faq/troubleshooting-html#error-missing-prebuilt-package'". Every conceivable attempt to fix the error has failed so far.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by db4** [comment]
I don't know what "vivoka" is but "boost/1.71.0@vivoka/customer" is surely some non-standard package that Conan Center doesn't distribute. So it's your responsibility to create the necessary binary package. Why not just follow the advice in the error message and add extra flags to build the package locally?

**Comment by memsharded** [comment]
Thanks @db4 for the response!

That is correct. The expectation when installing packages is that a pre-compiled binary package for that configuration exists. Someone (typically CI) is the responsible to create that binary and upload it to the server (vivoka private server in this case), so developers will have it available when doing ``conan install``. If the package is not existing, developers can do something like ``--build=pkg`` or ``--build=missing`` to build all missing binaries, but that is a sub-optimal flow, because all developers in the org will be rebuilding from source again and again the same thing.

**Comment by memsharded** [comment]
Closing as staled, please create new tickets for any further question. Thanks.
