### ISSUE TITLE
[question] How to properly set `tool_requires` for a tool dependency?

### ISSUE THREAD

**Issue by gegles** [conan-io/conan#14699]
### What is your question?

Hello,

I am trying to only require Python/Conan as an installed prerequisite and have `cmake`, `ccache` and `ninja` come from conan.

I use the following command:
```
conan create -b missing -u -pr macos-x86_64 .
```

I use the following profiles:
```
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=20
compiler.libcxx=libc++
compiler.version=14
os=Macos
os.version=11.0
[tool_requires]
*: cmake/3.27.4, ninja/1.11.1, ccache/4.8.3
[conf]
faspio*:tools.cmake.cmake_layout:build_folder_vars=['settings.os', 'settings.arch']
faspio*:tools.cmake.cmaketoolchain:generator=Ninja Multi-Config


Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=17
compiler.libcxx=libc++
compiler.version=14
os=Macos
[conf]
```

on macOS, I get the following error when it tries to build `ccache` (`hiredis` is a dep of ccache) from source:
```
hiredis/1.1.0: Apply patch (portability): support AIX build
hiredis/1.1.0: WARN: /Users/gegles/Workspaces/aspera/faspio-sdk/.conan2/p/hired363e8c4e08eb1/s/patches/0002-fix-aix.patch: file 1/1:     b'fmacros.h'
hiredis/1.1.0: WARN: /Users/gegles/Workspaces/aspera/faspio-sdk/.conan2/p/hired363e8c4e08eb1/s/patches/0002-fix-aix.patch:  hunk no.1 doesn't match source file at line 4
hiredis/1.1.0: WARN: /Users/gegles/Workspaces/aspera/faspio-sdk/.conan2/p/hired363e8c4e08eb1/s/patches/0002-fix-aix.patch:   expected: b'#define _XOPEN_SOURCE 600'
hiredis/1.1.0: WARN: /Users/gegles/Workspaces/aspera/faspio-sdk/.conan2/p/hired363e8c4e08eb1/s/patches/0002-fix-aix.patch:   actual  : b'#ifndef _AIX'
hiredis/1.1.0: WARN: /Users/gegles/Workspaces/aspera/faspio-sdk/.conan2/p/hired363e8c4e08eb1/s/patches/0002-fix-aix.patch: already patched  b'fmacros.h'
hiredis/1.1.0: Running CMake.configure()
hiredis/1.1.0: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/Users/gegles/Workspaces/aspera/faspio-sdk/.conan2/p/b/hirede22eb3ebb6a5b/b/build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/gegles/Workspaces/aspera/faspio-sdk/.conan2/p/b/hirede22eb3ebb6a5b/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/gegles/Workspaces/aspera/faspio-sdk/.conan2/p/b/hirede22eb3ebb6a5b/b/src"
/bin/sh: cmake: command not found
```

My question is, how do I set things up so that `cmake` is also a treated as a `tool_requires` of `ccache` and associated deps.. so that it can be found when building the `ccache` tool from source?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @gegles 

Thanks for  your question.
I think the problem is that you also need to define the ``tool_requires`` in the "build" profile. As you defined them in the "host" profile, they will be applied to regular "host" libraries. But ``ccache`` is a ``tool_require`` package that lives in the "build" context, and same for its transitive dependencies.

The problem with this is that you need to be a bit careful to not define recursive dependencies. If all ``tool_requires`` apply to all ``tool_requires`` in the "build" context, they will end creating an infinite loop. The way to break the loop is to define them a bit more carefully, like:
```
# build profile
[tool_requires]
ccache*: cmake/[>3.23 <4]
hiredis*: cmake/[>3.23 <4]
```
 It is assumed that the ``cmake`` package binaries have been pre-created. In general it is desired that the ``--build=missing`` is not necessary, and only the package being created is the one built from source, and the others are re-used from previous ``conan create`` of their respective packages. Or at least the ``tool_requires`` like ``cmake`` are pre-created and uploaded and not built as part of such ``conan create . --build=missing``.
Please try that and let us know.

**Comment by gegles** [comment]
Thanks @memsharded, that worked!

I had toyed with these options but couldn't figure out exactly where to put them (build vs. host profiles).

Here are my profiles now:
```
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=20
compiler.libcxx=libc++
compiler.version=14
os=Macos
os.version=11.0
[tool_requires]
*: cmake/3.27.4, ninja/1.11.1, ccache/4.8.3
[conf]
faspio*:tools.cmake.cmake_layout:build_folder_vars=['settings.os', 'settings.arch']
faspio*:tools.cmake.cmaketoolchain:generator=Ninja Multi-Config

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=17
compiler.libcxx=libc++
compiler.version=14
os=Macos
[tool_requires]
ccache*: cmake/[>3.23 <4]
hiredis*: cmake/[>3.23 <4]
zstd*: cmake/[>3.23 <4]
[conf]
```

**Comment by memsharded** [comment]
Excellent! :) Thanks for the feedback!
