### ISSUE TITLE
[question] Apt.install() check kwarg has different default than _SystemPackageManagerTool

### ISSUE THREAD

**Issue by lukester1975** [conan-io/conan#14708]
### What is your question?

Not sure if it's intentional or not (and if not, presumably too risky to change anyway...) but I noticed `Apt.install()` has `check=False` whereas other package managers will get `check=True` from `_SystemPackageManagerTool._install()`.

On the off chance it's useful: https://github.com/lukester1975/conan/commit/ed6e525bbf78d4257ceeef3933e56cf5755e955c

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for the feedback @lukester1975 

I recall vaguely this was intentional, and necessary because ``apt`` update was too slow or something like that. Let's ask @czoido

**Comment by czoido** [comment]
> I recall vaguely this was intentional, and necessary because `apt` update was too slow or something like that. Let's ask @czoido

Yes, I think that was the reason to make it the default, but I'm not sure now why the other have `check=False` I'll try to dig into the commit history to check if I can find anything.

**Comment by czoido** [comment]
Hi @lukester1975,
Finally, we decided to declare this as a bug since there was no evident reason for that to be the default. The logical value for that default seems like it should be "True". I believe this change should not affect many users negatively, as every `Apt.install()` call in Conan Center sets `check=True`. This change has been merged and is expected to be released in version 2.0.11. 
Thank you for reporting!

Closed by: https://github.com/conan-io/conan/pull/14728
