### ISSUE TITLE
[question] Conan2.0 just destroy every thing!!!!

### ISSUE THREAD

**Issue by ZhengCaiyi** [conan-io/conan#14722]
### What is your question?

All changed in conan 2.0.
Have you guys consider the impact of users????
Need to change all conanfile, upload script, pipelines after upgrade.
It's a disaster。

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ZhengCaiyi 

- Yes, we have considered it, and we even voted it with the committee representing the Conan users: https://github.com/conan-io/tribe/pull/13
- Conan 2.0 is not fully breaking. We are running ConanCenter at scale with many hundreds of recipes that can be built simultaneously with Conan 1.X and Conan 2.0, with exactly the same recipe
- There is a comprehensive migration guide in https://docs.conan.io/1/conan_v2.html to help preparing your recipes to be jointly compatible in Conan 1.X and Conan 2.0

This issue is being closed as not constructive and not compliant with the **Code of Conduct**: https://github.com/conan-io/conan/blob/release/2.0/.github/CONTRIBUTING.md#code-of-conduct. 

Please open another ticket with constructive feedback or specific migration questions, we will be glad to help there.
