### ISSUE TITLE
[question] Given a package ref, how to deploy what is packaged during the package step?

### ISSUE THREAD

**Issue by geir-t** [conan-io/conan#14723]
### What is your question?

Hi!

In conan1 I could do:
`conan install pkgA/1.0.0@company -r .. -pr:b ... -pr:h -if [package_folder_path] `
and if I had defined the conanfile.py deploy method it would copy the package artifacts to package_folder_path

In conan2 I try with:
`conan install --requires pkgA/1.0.0@company -r .. -pr:b ... -pr:h --lockfile=''  --deployer direct_deploy --deployer-folder [package_folder_path] `
but it complains with 
```
ERROR: Missing binary: pkgA/1.0.0@company:bbc2af66f67beed6ce25a965a3c7a23de7fd9076

pkgA/1.0.0@company: WARN: Can't find a 'pkgA/1.0.0@company' package binary 'bbc2af66f67beed6ce25a965a3c7a23de7fd9076' for the configuration:
[settings]
...
[python_requires]
hud_tool/0.1.Z@company

```
because I have hud_tool 0.1.0 in cache but pkgA is build with hud_tool 0.2.0. It works if I delete the hud_tool from cache or run conan install with --update.

All I want is to copy the package files given a pkg reference and profiles to a folder. Any tips for how to achieve this?

Regards

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @geir-t 

Thanks for your question.

If you have the ``package_id`` of the binary you want to copy, the ``conan cache path pkg/version:package_id`` will give you that path, and it will be easier to copy things from there, if that is what you want.

If you don't have the ``package_id`` and just the profiles, than it is necessary to compute the dependency graph, as the ``package_id`` is a function of the dependencies versions too. This wouldn't be connected then to the ``deploy`` case, but to the fact that it is necessary to compute the dependency graph. 

And the dependency graph resolution depends on several factors, like what packages you have in the cache, if you are using lockfiles, the remotes you have enabled, if you are using ``--update`` or not, etc.

> because I have hud_tool 0.1.0 in cache but pkgA is build with hud_tool 0.2.0. It works if I delete the hud_tool from cache or run conan install with --update.

This is expected behavior, and very necessary. The version of ``hud_tool`` that you are depending on can easily affect your ``package_id``, and then, it can point to different files to copy to your user space. So what you want to do is to guarantee that you are using the ``hud_tool`` version that you want to use to evaluate the graph. The options are:
- Use ``--update`` or remove packages from the cache if what you want is to always use the latest version from the server
- Use a lockfile, if you want to use always a specific version, irrespective of what you have in the cache or in the servers

If you don't want ``hud_tool`` to affect that way to the packages using that as ``python_requires`` you can:
- Do not bump the ``minor`` ``hud_tool`` version if it is not producing different binaries, but bump its patch version instead, and that will not induce a different ``package_id``
- Change the ``core.package_id:default_python_mode`` to define the behavior how do you want your ``python-requires`` new versions to their consumers ``package_ids``

Please let me know if this clarifies it. Thanks!

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
