### ISSUE TITLE
[bug] Conan 1.60.0 uses python_requires to compute package_id, but does not list them in requirements when errors occur

### ISSUE THREAD

**Issue by antoinebardoz** [conan-io/conan#14726]
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: N/A
* Conan version: 1.60.0
* Python version: 3.10.8

### Steps to reproduce

1. Build package DEP, which has a python_require PYDEP with a version range (not fixed)
2. Create a new version of PYDEP
3. Try to build a package which depends on DEP

 Notice in the log below how the package lists zero dependencies, even though there IS a dependency: PYDEP

This caused several hours of debugging, since we had no idea what we were looking for. I don't believe this would have been an issue with Conan 2, as I've seen Conan 2 list python requires in such situations.

### Logs

```
ERROR: Missing binary: DEP/0.0.1@company/latest:76777cd535eb9e2203d7321abd74929798755a4f

DEP/0.0.1@company/latest: WARN: Can't find a 'DEP/0.0.1@company/latest' package for the specified settings, options and dependencies:
- Settings: arch=armv8, build_type=Release, compiler=gcc, compiler.libcxx=libstdc++11, compiler.version=10, os=Linux
- Options: fPIC=True, shared=False
- Dependencies: 
- Requirements: 
- Package ID: 76777cd535eb9e2203d7321abd74929798755a4f
```

**Comment by memsharded** [comment]
Hi @antoinebardoz 

Thanks for the feedback.
Yes, it seems that the "Missing binary" message is not printing the python-requires.

As you pointed out, it is true that Conan 2.0 is doing better here, that is part of the structural change over the ``package_id`` and ``conaninfo.txt`` computation. Conan 2.0 will print directly the contents of ``conaninfo.txt``, because ``package_id`` is just the hash of that file now, making way more evident what are the influence of things over this ``package_id``.

It would be nice to add this information to Conan 1.X to improve the ux, Let's see if this can be done (the backlog is quite large, with other higher priorities)

**Comment by AbrilRBS** [comment]
Closing as won't-do ourselves, as we're currently fully focused on Conan 2 as Conan 1 slowly transitions into a support only state, thanks for understanding :)
