### ISSUE TITLE
xray scanning on Conan package

### ISSUE THREAD

**Issue by psamadda** [conan-io/conan#14745]
### What is your question?

I am using Conan 1.60.2. I have followed https://blog.conan.io/2021/09/07/Conan-XRay-Integration.html to upload openssl package to my jfrog artifactory server. But the xray report is not generated. It shows In Progress state and remains the same. Even I have followed https://stackoverflow.com/questions/65888471/conan-artifactory-jenkins-integration-fails to publish build artifact and upload conan package from Jenkins. The build is successful but the xray report is In Progress state for uploaded package. The jfrog artifactory is enterprise version. Can you guide me on this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @psamadda 

Thanks for your question.
If you managed to create the "buildInfo" and upload it, and then XRay is in progress, but doesn't really finish, I think you might want to file a support ticket for JFrog, specially if you are using some enterprise version. It might be the version of the XRay is related, but in any case it is a bit out of the scope of this repo, where we work on the Conan client and associated open source tools, but we don't really deal with XRay.

In any case, I'd like to take a chance to comment on a couple of updates:
- We managed to do some improvements and create a new, more complete "buildInfo" in Conan 2.0, with the new dedicated custom commands in https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/art. It might be possible that the new "buildInfo" works better than the previous one.
- The jenkins plugin for Conan will not move forward for Conan 2.0. The recommendation will be to call ``conan ...`` commands directly from jenkins, at the end of the day, the Artifactory-Jenkins abstraction over Conan is a very thin layer over Conan commands, it doesn't bring a ton of value just some small convenience. Everything should be doable with bare Conan commands. I comment on this because I don't think the Jenkins plugin itself could be related to this issue (and also for awareness moving forward)

**Comment by memsharded** [comment]
Closing this ticket as responded back then and stale.
If you have any further question please re-open or create a new ticket. Thanks for the feedback!
