### ISSUE TITLE
Cannot call git.clone() from source() when building from a MSYS2 MINGW64 shell window

### ISSUE THREAD

**Issue by acolwell** [conan-io/conan#14754]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: gcc 13.2.0
* Conan version: 2.0.10
* Python version: python 3.11.4

### Steps to reproduce

1. Try to build a recipe that has a git.clone() command in the recipe's source() method when building from inside a MSYS2 MINGW64 shell window.
2. Observe the "conans.errors.ConanException: 'self.settings' access in 'source()' method is forbidden" error message.

This worked fine in 2.0.9. I believe the issue is caused by [this change](https://github.com/conan-io/conan/pull/14326/files#diff-9af4758943b5275fbbff9c15f170e7ee81d3ac7f258652be9b4ac222e57158aeR29) causing [this line](https://github.com/conan-io/conan/blob/release/2.0/conans/client/subsystems.py#L79) to trigger the exception.

Unfortunately I'm not familiar enough with the code to know what the proper fix for this should be.

### Logs

Here is a stack trace from the conan command when I run it with -vvv

```
Traceback (most recent call last):
  File "C:/tools/msys64/home/aaron/src/conan2-env/lib/python3.11/site-packages/conans/errors.py", line 52, in conanfile_exception_formatter
    yield
  File "C:/tools/msys64/home/aaron/src/conan2-env/lib/python3.11/site-packages/conans/client/source.py", line 82, in run_source_method
    conanfile.source()
  File "C:/Users/aaron/.conan2/p/openfa3473a8ec710d/e/conanfile.py", line 31, in source
    git.clone(url="https://github.com/NatronGitHub/openfx-misc.git", target=".")
  File "C:/tools/msys64/home/aaron/src/conan2-env/lib/python3.11/site-packages/conan/tools/scm/git.py", line 168, in clone
    self.run('clone "{}" {} {}'.format(url, " ".join(args), target_path))
  File "C:/tools/msys64/home/aaron/src/conan2-env/lib/python3.11/site-packages/conan/tools/scm/git.py", line 29, in run
    self._conanfile.run(f"git {cmd}", stdout=output, quiet=True)
  File "C:/tools/msys64/home/aaron/src/conan2-env/lib/python3.11/site-packages/conans/model/conan_file.py", line 331, in run
    wrapped_cmd = command_env_wrapper(self, command, env, envfiles_folder=envfiles_folder)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/tools/msys64/home/aaron/src/conan2-env/lib/python3.11/site-packages/conans/client/subsystems.py", line 56, in command_env_wrapper
    wrapped_cmd = _windows_bash_wrapper(conanfile, command, envfiles, envfiles_folder)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/tools/msys64/home/aaron/src/conan2-env/lib/python3.11/site-packages/conans/client/subsystems.py", line 79, in _windows_bash_wrapper
    _msystem = {"x86": "MINGW32"}.get(conanfile.settings.get_safe("arch"), "MINGW64")
                                      ^^^^^^^^^^^^^^^^^^
  File "C:/tools/msys64/home/aaron/src/conan2-env/lib/python3.11/site-packages/conans/errors.py", line 23, in _m
    raise ConanException(f"'self.{attr_name}' access in '{method}()' method is forbidden")
conans.errors.ConanException: 'self.settings' access in 'source()' method is forbidden
```

**Comment by memsharded** [comment]
Hi @acolwell 

Thanks for reporting.

You are right, indeed that change introduced that bug, lets see how it can be fixed. Quick question:

- When using the ``msys2``, is it expected that the ``git`` used is the git inside the ``msys2`` environment? Like the credentials, configuration, etc, will be the one defined in ``msys2``, or the native one? (I suspect not, if it worked in 2.0.9)

**Comment by memsharded** [comment]
As a quick workaround you can try doing something like:
```python
def source(self):
      self.win_bash = False
      git = Git(self)
      git....
      self.win_bash = True
```

**Comment by acolwell** [comment]
> Hi @acolwell
> 
> Thanks for reporting.
> 
> You are right, indeed that change introduced that bug, lets see how it can be fixed. Quick question:
> 
> * When using the `msys2`, is it expected that the `git` used is the git inside the `msys2` environment? Like the credentials, configuration, etc, will be the one defined in `msys2`, or the native one? (I suspect not, if it worked in 2.0.9)

I don't know what others might expect, but I'd expect it to run the git in the msys2 environment. I think of msys2 mainly like being on Linux. If I run conan from the msys2 bash shell then I'd expect it to run the git that would be available from that shell. I don't really know if this is how it was before 2.0.10, but that is the what I'd expect. Right now at least, I'm not doing anything particularly tricky and am accessing public repos so I don't have to worry about auth. If I did have to access a private repo though, I'd expect whatever git that runs to be able to access the keys held by the shell's ssh-agent just like if I ran git from the prompt myself. I totally understand if that is a separate long term ask. For now I'd just like the simple case restored.

Thank you for looking into this for me. :)

**Comment by memsharded** [comment]
> If I run conan from the msys2 bash shell then I'd expect it to run the git that would be available

This is one of the things that I wanted to know. If running from an msys2 bash shell, (conan is launched already in the shell), the ``conf`` ``tools.microsoft.bash:active=True`` is expected, to avoid Conan to force launching the command in ``bash``, because it is already running in that bash. If that conf is active, I think that Conan will not fail, can you please try it?

The other possible scenario, the most common one for most users and users of ConanCenter recipes is:
- Users are running from a normal Windows cmd (or compatible) terminal
- The recipe must build in bash, because using autotools, for example
- Using ``win_bash=True`` in the recipe and conf ``tools.microsoft.bash:subsystem``, the recipe will run the build commands inside bash
- The ``Git()`` helper pre 2.0.10 was using a normal ``subprocess`` execution, completely unconditional to all Conan tool-requires, profile ``[buildenv]`` and using bash. It was always running a bare ``git`` command inside the terminal you are running.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/14756 has been merged, closing this issue, to be released in 2.0.11 today, please update.

The comments above are still valid, and your feedback there will be appreciated, thanks!

**Comment by acolwell** [comment]
> > If I run conan from the msys2 bash shell then I'd expect it to run the git that would be available
> 
> This is one of the things that I wanted to know. If running from an msys2 bash shell, (conan is launched already in the shell), the `conf` `tools.microsoft.bash:active=True` is expected, to avoid Conan to force launching the command in `bash`, because it is already running in that bash. If that conf is active, I think that Conan will not fail, can you please try it?
> 

I tried this and you are correct that it worked if I removed win_bash=True from my recipe. I did run into other unrelated issues caused by conan calling mingw32-make instead of make, but I discovered that I could make it stop doing that if I specified os.subsystem=msys2 in my profile.

> The other possible scenario, the most common one for most users and users of ConanCenter recipes is:
> 
> * Users are running from a normal Windows cmd (or compatible) terminal
> * The recipe must build in bash, because using autotools, for example
> * Using `win_bash=True` in the recipe and conf `tools.microsoft.bash:subsystem`, the recipe will run the build commands inside bash

My recipe also fell into this scenario as well since I had to use autotools and I had win_base=True set. This allowed me to also build from the normal windows cmd as you said.

> * The `Git()` helper pre 2.0.10 was using a normal `subprocess` execution, completely unconditional to all Conan tool-requires, profile `[buildenv]` and using bash. It was always running a bare `git` command inside the terminal you are running.

I did verify that it appeared to be running a bare git. When run from the mingw64 window it used msys2's git and when I ran from the Windows cmd it expected a git binary to be available from the windows shell. I can kind of understand why this would be, but if I'm forcing a recipe to build in a bash shell w/ win_bash=True, part of me would expect that conan would use the git available in the bash shell. I fully admit I don't understand the implications of that so please take this opinion w/ a grain of salt.

Anyways... I installed 2.0.11 and verified that I am not seeing the exception anymore. Thank you for your quick response. I really appreciate it.  I hope you have a wonderful day/evening. :)

**Comment by memsharded** [comment]
> I did verify that it appeared to be running a bare git. When run from the mingw64 window it used msys2's git and when I ran from the Windows cmd it expected a git binary to be available from the windows shell. I can kind of understand why this would be, but if I'm forcing a recipe to build in a bash shell w/ win_bash=True, part of me would expect that conan would use the git available in the bash shell. I fully admit I don't understand the implications of that so please take this opinion w/ a grain of salt.

Yes, this is the possible "feature request" that I am trying to understand if makes sense. So far the ``source()`` method and ``Git()`` in particular don't do this, because of some challenges like:
- When using ``msys2`` as a ``tool_requires`` it is necessary to inject it in the ``source()`` method, but as the ``source()`` method is also common to all binary configuration, does not take anything that makes it conditional to a specific binary configuration, including ``tool_requires``
- For the same reason ``source()`` does not receive the environment from profiles or from dependencies, because ``source()`` should be able to run without dependencies, like in ``conan source`` command.

This makes very difficult to generalize the injection of the necessary things into ``Git()`` in ``source()`` method, and this was the ultimate reason of the failure that you reported. If it doesn't seem necessary because the host "git" also works, then we might put this possibility on hold at the moment

> Anyways... I installed 2.0.11 and verified that I am not seeing the exception anymore. Thank you for your quick response. I really appreciate it. I hope you have a wonderful day/evening. :)

It is our pleasure to help and to try to serve users the best we can. Don't hesitate to submit new issues for any further question or issue you might have. Thanks for all the feedback!
