### ISSUE TITLE
[question] How to temporary append current environment in conan 2.X?

### ISSUE THREAD

**Issue by huysentr** [conan-io/conan#14770]
### What is your question?

I wrote some code to run my build step in a modified environment:

```python
...
    def make_env(self):
        myenv= tools.env.Environment()

        # Copy all existing vars into the new environment
        for name, value in os.environ.items():
            value = value.split(os.pathsep)
            myenv.define(name, value)

        myenv.define("FOO", "BAR")
       

    def build(self):
        with self.make_env().vars(self).apply():
            cmake = CMake(self)
            cmake.configure()
            cmake.build()
...
```

However this is far more convoluted than what I use to do in conan 1.X
I have been reading the resources however none explains me how I can do this easier in conan 2.X.
Is this the correct way? Or am I making things to convoluted? If anyone knows, let me know.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @huysentr 

Thanks for your question.
It would be great to understand what is the use case. What environment variable are you injecting directly in the recipe, and why?

The idea is that the ``CMake`` cmd line wrapper should require little environment, because things have been already defined in either the toolchain or in environment files in the ``generate()`` step. This way, developers developing locally can obtain the exact same build they do when the package is created. If the build depends on env-var that are passed exclusively in ``build()`` time, then it becomes impossible for developers with their IDE to obtain the same results.

**Comment by huysentr** [comment]
Hi @memsharded 

There are two contexts in which I feel like I am making things to convoluted.
The first one is a bash script being ran and the env vars are then added to the cmd env.

```python
    def make_env(self):
        intel_root = os.environ["ONEAPI_ROOT"]
        if self.settings.os == "Windows":
            bat = "setvars.bat"
            bat = os.path.join(intel_root, bat)
            command = f'cmd.exe /V /C "{bat} && set"'
        else:
            sh = "setvars.sh"
            sh = os.path.join(intel_root, sh)
            command = f'/bin/sh -c ". {sh} && env"'

        output = subprocess.check_output(command, shell=True).decode()
        lines = output.splitlines()
        oneapi_env = tools.env.Environment()

        # Copy all existing vars into the new environment
        for name, value in os.environ.items():
            value = value.split(os.pathsep)
            oneapi_env.define(name, value)

        # Copy all the ones set by the command
        for line in lines:
            name, _, value = map(str.strip, line.partition('='))
            if name:  # only add if name is not empty
                oneapi_env.define(name, value)

        return oneapi_env

```

The second example is where I am making a  1.X conanfile compatible with both 1.54+ and 2.X.
Where I have to replace things such as:
`self.run("{} -fiv".format(tools.get_env("AUTORECONF")), run_environment=True, win_bash=tools.os_info.is_windows)`
And

```python
    @contextmanager
    def _msvc_context(self):
        env = {
            "FOO_INSTALL_DIR": self.package_folder,
        }
        with tools.environment_append(env):
            with tools.vcvars(self.settings):
                yield
```
   
Note that I can make these work using the former implementations. However I wanted to ask for a better way.

**Comment by memsharded** [comment]
Thanks for the feedback.
I think the approach, that can also work both in Conan 1.X and Conan 2.0 is the following:

- Leverage the ``generate()`` method, the idea is to create a ``conanintel.bat|sh`` file at ``generate()`` time.
- The ``generate()`` method can instantiate an ``Environment()`` and then call the ``env.vars.save_script("conanintel")``. This will contain your ``subprocess.check_output`` logic above, it seems that this would be the same everywhere.
- The ``build()`` method and the ``self.run()`` commands in it, will automatically load and apply the ``conanintel`` script with the defined env-vars, transparently, no need to do anything
- The developers just need to activate the ``conanbuild`` script locally (it will call the ``conanintel`` one internally), to have everything defined in the same way, so when they call the build system, the environment is correct, and they can achieve the exact same build, because everything is correctly configured for them.

Going a bit beyond, I think that the part with
```python
         intel_root = os.environ["ONEAPI_ROOT"]
        if self.settings.os == "Windows":
            bat = "setvars.bat"
            bat = os.path.join(intel_root, bat)
            command = f'cmd.exe /V /C "{bat} && set"'
       ...
```
Doesn't really belong to the recipes. It is part of the profile definition. You can run that outside the recipe and create a ``myprofileintel`` profile that contains the necessary ``[buildenv]`` section that can be applied to recipes. Recipes would be simpler and easier to maintain. There are possibilities in Conan 2.0 to automate this task, for example with the ``profile.py`` plugin, so lets say that this automatic processing of the system setup is done just once, per profile, and not for every recipe that is being built.

Please let me know what you think.

**Comment by huysentr** [comment]
Hello. I tried following your advice at it works. My code is now compatible with 2.X and 1.61:
```python

      intel_root = os.environ["ONEAPI_ROOT"]
      if self.settings.os == "Windows":
          bat = "setvars.bat"
          self.run(os.path.join(intel_root, bat))
      else:
          sh = "setvars.sh"
          self.run("sh " + os.path.join(intel_root, sh))

      conanintel = tools.env.Environment()
      conanintel.vars(self).save_script("conanintel")
```
and I used this:
```python
    def generate(self):
        if self.settings.os == "Windows":
            ms = VCVars(self)
            ms.generate()
        conankrb5env = tools.env.Environment()
        conankrb5env.define("KRB_INSTALL_DIR", self.package_folder)
        conankrb5env.append_path("PATH", os.environ.get("PATH", ""))
        conankrb5env.vars(self).save_script("conankrb5env")
```
Do these look right to you? (well they work, but are they the intended conan way?)
About the ONE_API script running, I am phasing that out.

**Comment by memsharded** [comment]
It is not clear the intent of ``conankrb5env.append_path("PATH", os.environ.get("PATH", ""))``. It seems to be defining just the existing PATH, that shouldn't be necessary? It looks like a no-op

**Comment by huysentr** [comment]
Correct, it was an artifact from trying to get my local win env to work. However I required VCVars instead. It works fine when removing the line.

**Comment by memsharded** [comment]
Ok, sounds good. Is this question solved then? Maybe we can close it? Thanks!
