### ISSUE TITLE
[feature] Add `required_conan_version` field to graph info response

### ISSUE THREAD

**Issue by franramirez688** [conan-io/conan#14786]
### What is your suggestion?

Let's look into if it'd make sense (and even if's feasible) to add the `required_conan_version` field to the `conan graph info` response.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
I am having a quick look, this would require extracting the version from the module, assigning it to ConanFile derived class in the ``ConanFileLoader``, to later be able to serialize it in the json.

Seems a bit too much specific for this special use case, as in general knowing the min versions of a graph that is being computed is a bit pointless, because in order to compute the graph you already need a modern enough Conan version, or it will fail. So it is not that much forward analysis can be done with the serialized info. I am trying to think of a use case beyond our own one in which users can use this information

**Comment by memsharded** [comment]
After discussing, we are not moving this forward, little value.
