### ISSUE TITLE
[question] conan build without installing dependencies

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#14816]
### What is your question?

Dear Conan Folks,

My use-case is:
- I am using conan-2.0.6. I have some dependencies in a component that need to be copied to a folder structure where the source code is cloned.
I am using generate method for the same. So, the user workflow at the moment is such that , I am using build command so that I can specify output folder like this:
```
conan build . -of kdp  --user autosar --channel release-local  -pr:b=default -pr:h=kdp
```
build command in 2.0.6 installs the dependencies and builds the components.
What I expect is. a workflow like this:
- clone the source code
- use conan install to install the dependencies and 
- use conan build to build the component
But I understand that build without install is no more possible. 
Could someone please help me?

Thanks!
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

This is true, ``conan build`` now also install the dependencies, because the ``build()`` often needs the dependencies information to work, so it is impossible to avoid that. In Conan 1.X there were too many broken cases and limitations it was not worth.
But:
- The installation of dependencies when things are cached is very fast, it shouldn't be a problem
- The flow is just reduced to ``conan source`` + ``conan build``, one step less
- In general it is intended that for the developer experience, ``conan build`` is not that necessary, but instead developers could do ``conan install`` + call native build system.

I am not sure what would be the issue with this, if you could please clarify.


> I am using conan-2.0.6.

PS: please recall that only the latest patch of each minor is supported, and 2.0.11 is already there, please try to update when possible

**Comment by maitrey** [comment]
I mention the version just in case I miss on features available from the latest versions.

**Comment by maitrey** [comment]
Thank you !
Actually I tried with conan install --build-missing but this does not exactly fit to what actually the use-case.
Thanks for confirming the options.
Issue can be closed.

**Comment by memsharded** [comment]
Thanks for the feedback!, closing the issue
