### ISSUE TITLE
Enabling `force_host_context` on packages in the profile

### ISSUE THREAD

**Issue by clanghans** [conan-io/conan#14827]
### What is your question?

I am looking to understand if there's a way to enable the force_host_context attribute for specific packages directly within a profile. Profiles are centrally maintained and would improve maintainability a lot. 

Currently, I am working towards migrating to Conan2 and know that it is possible there with a `[test_requires]` section in the profile. But is it also possible with Conan 1.x, even a temporary workaround could be considered?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @clanghans 

Thanks for your question.

I think there might be some misunderstanding. Conan 2 allows ``[test_requires]`` in the ``conanfile.txt``, not in the profiles.

The rationale is that test_requires as gtest or catch2 are very specific to the package using them, mostly as any other regular requires library like depending on zlib or openssl. It is not like a ``tool_requires`` like ``cmake`` that is more a tool that can be (and often is) installed in the system.

So there is no way to force ``test_requires`` from the profiles, neither in Conan 1 or 2. The solution, that should work in both Conan 1 and 2 is that recipes do ``self.test_requires()`` in the ``build_requirements()`` method, both in Conan 1 and Conan 2. The syntax is available in both and will be compatible, no need to define any ``force_host_context`` attribute at all. 

Please let me know if this helps.

**Comment by clanghans** [comment]
yes, this was a misunderstanding then. Well, thanks for clarifying. I thought the profile sections are the same as in the conanfile.txt. 

May I rephrase my question? 
In a project of about 50 conan packages, what would be the recommended way to ensure a `test_requires` in the same version for every package? For example, I want to ensure every team in the project works with the correct googletest version.

**Comment by memsharded** [comment]
> In a project of about 50 conan packages, what would be the recommended way to ensure a test_requires in the same version for every package? For example, I want to ensure every team in the project works with the correct googletest version.

This is not really a tooling problem, but a definition problem. If you want everyone in the org to use the same version, you define it and everyone will put the same version. Same as every other library, not only ``gtest``, but same for other libraries. There is no point to force it from the downstream profile, because a developer can still put its ``self.test_requires()`` with the version they want in the recipe, and use it, and it will work, until someone else forces the new version from downstream profile and then it breaks?

In practice, to have everyone to use the same version while allowing new versions of ``gtest`` to be used, the approach is to use the same ``self.test_requires("gtest/[>=1 <2]")`` version-range, so when new versions are created, they will be automatically used by every package too. Note that one of the good things of this approach, is that when a new ``gtest`` breaking version is released, lets say the ``2.0`` version that was excluded from the range above, it is possible to upgrade one package recipe at a time. This is very necessary for this kind of update, the only maintainable approach. Other approaches trying to override from the downstream basically breaks every one of those 50 packages until all of them have upgraded, that can take a while. It is totally fine, and very often desirable that different ``gtest`` versions can be used in the same graph.

**Comment by MTomBosch** [comment]
I can see your point and for googletest we are actually doing it like that. The use case for which we need a solution is following.
We are using a codecoverage tool suite for the instrumentation and report generation. For the report generation we are adding the tool for reporting as build requirement. Now for the instrumentation we need to add a library (similar like googletest but created using that codecoverage toolsuite) in host context. This library is also a Conan package. Now we have the problem that the coverage reporting tool is centrally defined but the instrumentation library can only be specified in every recipe. 

And unfortunately the versions of these two Conan packages shall be compatible. When defining both centrally in the profile this would be a quick win but since it is not possible we are searching for alternatives.

Do you have any other idea how we could check in an automatic (Conan python magic) way that the version of the Conan package for the reporting (build requires resp. tool_requires) is compatible with the instrumentation lib package (build requires with host context resp. test_requires)?

**Comment by memsharded** [comment]
We introduced the ``<host_version>`` versioning approach in 1.X and 2.0 recently, which is very close to what you intend, but probably like in the opposite direction. It allows ``tool_requires`` to use the versions defined in "host" requires.

This is done this way for 2 reasons:
- The important version is typically the "runtime" host version, and the ``tool_requires`` should follow to be compatible with it.
- The host requirements are resolved before the build requirements. So the only possible order is that one, that the "build" requires follow and take the version of the previously resolved "host" requires.

In your use case, does the instrumentation library gets injected magically in the build? or the build has some provision to inject it? Maybe something like:
```python
def build_requirements(self):
      self.test_requires("instrumentation_lib/[>=1 <2]")
      self.tool_requires("codecoveragetool/<host_version>")
```
would make some sense?
If not, the way to control this kind of thing would be using user confs, maybe something like:
```python
def build_requirements(self):
       inst_version = self.conf.get("user.mycomp:inst_version")
       if inst_version:
              self.test_requires(f"instrumentation_lib/{inst_version}")
```
Then inject it in the profile or command line with ``-c user.mycomp:inst_version=X.Y.Z``?

Just some quick ideas...

**Comment by clanghans** [comment]
Thanks, this was very valuable for us. 

Closing the issue
