### ISSUE TITLE
Please add GCC13 and Clang 17 to list of supported compilers

### ISSUE THREAD

**Issue by AntonRechkov** [conan-io/conan#14839]
### What is your suggestion?

Hello, currently Conan doesn't list GCC13 and Clang17 as supported compilers. Please add new compiler versions.

[settings]
compiler=gcc
compiler.version=13
compiler.libcxx=libstdc++11
compiler.cppstd=gnu17

   ERROR: Invalid setting '13' is not a valid 'settings.compiler.version' value.
   Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '6.5', '7', '7.1', '7.2', '7.3', '7.4', '7.5', '8', '8.1', '8.2', '8.3', '8.4', '8.5', '9', '9.1', '9.2', '9.3', '9.4', '9.5', '10', '10.1', '10.2', '10.3', '10.4', '11', '11.1', '11.2', '11.3', '12', '12.1', '12.2']

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @AntonRechkov thanks a lot for your question:

What version of Conan are you using? GCC 13 has been available in Conan 2 since 2.0.5 and in Conan 1 since 1.60

If the issue arises from not being able to update your Conan 2 version, then you'll need to use a `settings_user.yml` file ([Docs here](https://docs.conan.io/2/examples/config_files/settings/settings_user.html)) - as we do not backport support for newer compilers to older v2 releases

If you're in Conan 1, as the settings_user feature was not backported, your way forward is to directly modify your `settings.yml` file ([Docs here](https://docs.conan.io/en/1.61/extending/custom_settings.html))

Let me know if that helps :)

**Comment by AbrilRBS** [comment]
Closing as solved - the new compilers have been supported for a while now and the proposed solutions for v1 work well enough
