### ISSUE TITLE
[question] Python 3.7+ Upgrade

### ISSUE THREAD

**Issue by stackfun** [conan-io/conan#14834]
### What is your question?

Wondering whether Conan will raise the minimum version of python3 anytime soon. According to [this proposal](https://github.com/conan-io/tribe/pull/35)

> we propose a moving minimum supported Python version, that will extend 12 months over the official Python EOL

Python3.6 has been EOL for over a year now, and if the minimum python version for Conan does change, I’m sure this will impact a lot of Conan users

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @stackfun 

Thanks for your question.

There is nothing really holding the development of Conan because of using Python 3.6. So we have decided to wait for this deprecation of Python 3.6. as you said, it can impact many users. We are not planning to remove support for 3.6 anytime soon, unless some unexpected serious security issue associated to 3.6 happens that really forces us to force the upgrade. So still the recommendation is to plan your upgrades for more modern Python versions, but from the Conan side there are no plans to remove it.

**Comment by stackfun** [comment]
At least for our internal python packages, it's getting harder to support python 3.6 and the latest python releases since they seem to be more aggressively deprecating API's, so it's a pain point that the Conan team might encounter too.

Also, this statement from [this source](https://endoflife.date/python) is relevant.

> A Python release only supports a Windows platform while Microsoft considers the platform under extended support. Python 3.8 was the last version to support Windows 7.

Closing this question for now since it has been adequately answered, thanks for the quick response! :)
