### ISSUE TITLE
[question] Should we execute tests by default, even if the tools.build:skip_test config is not set?

### ISSUE THREAD

**Issue by jakubgros** [conan-io/conan#14830]
### What is your question?

Hello. I found that there is the `tools.build:skip_test` option available in Conan, which determines whether tests should be run or not when a recipe calls "cmake.test()". It's used [here](https://github.com/conan-io/conan/blob/844f112c6c5cdb84dd9b6ae665a4b7873a35cf54/conan/tools/cmake/cmake.py#L208):
```
  def test(self, build_type=None, target=None, cli_args=None, build_tool_args=None, env=""):
        # ... some code that I removed for clarity ...
        if self._conanfile.conf.get("tools.build:skip_test", check_type=bool):
            return
```

By default, the `tools.build:skip_test` config's value is not set in Conan's config, thus the method `self._conanfile.conf.get` above returns falsy object, which causes that tests are not skipped by default.

The option could be switched by adding the "default=True" parameter to the method call. But I'm not sure if the current behaviour is deliberate or not. Maybe we should we assume that the package was already tested by the library provider, so the tests shouldn't be executed by default unless explicitly requested through the config?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jakubgros 

Thanks for your question.

The overall idea and rationale is that a ``build()`` method that looks like this:
```python
def build(self):
     cmake = CMake(self)
     cmake.configure()
     cmake.build()
     cmake.test()
```
by default, with the default config, produces the most expected behavior. And given the imperative style, the expectation would be that the tests are executed. Configurations like ``skip_test`` can modify the default behavior, and inhibit the execution of ``.test()``. But the defaults should be to execute them if the recipe is written that way.

Of course, users that want different default can do conditionals in the ``build()`` method to conditionally run or not ``cmake.test()``. 

> that the package was already tested by the library provider,

The ``build()`` method is the actual building of the library binary. For many cases, the library provider is not a different entity than the current recipe, the library provider and the package provider is the same build being run by Conan. Running the unittests when building this specific binary for this package makes sense by default.

If we are talking about packaging third-party, open source libraries like in ConanCenter, then we can decide to completely avoid the ``cmake.test()``, and not put it in the ``build()`` at all.

There might be other cases that you don't want the tests to run, like when building dependencies with ``--build=missing``. Note that this is not the default Conan behavior either, it is a explicit opt-in to build them. The default is to expect to have pre-compiled binaries and error if not. So the build for this binary happens just once, in CI, and in that ``build()``, it makes sense to run the unittests.

**Comment by Todiq** [comment]
Hello @memsharded

I also have a few questions regarding the same topic.

> So the build for this binary happens just once, in CI, and in that build(), it makes sense to run the unit tests.

In CI/CD, these steps are usually decoupled, in order to being quickly able to check whether an issue occurred at the building or a the testing stage.

- How could one take advantage of calling `cmake.test()` in the `build` method and have the environment properly loaded (conanrun & conanbuild.bat | .sh ran automatically) and still have two distincts stages in CI/CD?

- If I have tests that require a particular environment (for my use case, I need to do a `cmake install X —prefix Y`, then move the tests executables to the created folder) for them to succeed, should I prepare it within the `build` method as well?

**Comment by jakubgros** [comment]
Hello @memsharded,

Thank you for your insightful response.

At first, I was taken aback by the default behaviour, as I had never observed any tests running during my Conan package builds. I thought that I implemented my recipe incorrectly. Upon exploring the [Conan center index recipes](https://github.com/conan-io/conan-center-index), I discovered that only a handful of recipes are configured to execute tests.

My initial concern revolved around the build time, especially when constructing a package with numerous dependencies and using the "--build=missing" parameter. I had assumed that running tests might be redundant, believing that library providers would have already tested their packages. Given this, I thought there wouldn't be any discrepancies that could lead to test failures. However, later I realized that I missed on important thing. When using "build=missing", it implies that the library hasn't been built for the current configuration, and its behaviour in that configuration remains uncertain. 

I'm sure you're well-acquainted with the concept of configuration. However, for those unfamiliar, let me highlight some potential challenges.

When building in a distinct environment, such as a different operating system or CPU architecture, there's a possibility that preprocessor definitions might be interpreted differently. This can lead to variations in the library's behaviour. Another potential issue arises when overriding a library version. Consider the following dependency graph:
```
     |---->  other_dependency -> boost 1.0
my app ---> boost 2.0 (override)
```

In this example, my app takes precedence with its boost 2.0 version, causing other_dependency to rely on a different version of boost. This version shift can lead to unexpected behaviours. 

Due to the above, I believe it makes sense to run unit tests on the package built and the current default behaviour makes sense.

**Comment by memsharded** [comment]
Yes, this is just an issue of trade-offs, that are not the same for everyone. Some will want and expect to go faster, not run tests, while others will realize that changes in configurations can have relevant effects, and prefer to be more comprehensive on the unit test and run them more often. It really depends on the needs and constraints of different users. 
Conan tried to provide some default that could made sense and easy to configure, but we know it might not be perfect for everyone.

Maybe if this is clear we could close the issue now? Thanks everyone for the feedback!

**Comment by jakubgros** [comment]
Sure, let's close this. Thank you for your assistance. 

@Todiq, I think it's worth creating a separate thread, as it isn't closely related to the topic I initiated.
