### ISSUE TITLE
[bug] CPack fails to resolve runtime dependencies for conan v2 packages with transient dependencies

### ISSUE THREAD

**Issue by dovydas-girdvainis** [conan-io/conan#14849]
### Environment details

* Operating System+version: Debian Bookworm
* Compiler+version:  GCC 12.2.0
* Conan version: 2.0.10
* Python version:  3.11.2

### Steps to reproduce

Hello everyone,

I might be doing something wrong or misunderstanding something, but when I try to use `cpack -G TGZ` on a project that uses conan packages to create a distributable tar.gz archive, **cpack** command fails to resolve runtime dependencies. However, it only fails for some conan packages and not all of them. It seems that transient dependencies from some library packages are not being resolved, while others are. I am not sure as to why...

I am using [`RUNTIME_DEPENDENCIES`](https://cmake.org/cmake/help/latest/command/install.html#install-runtime-dependency-set) options as part of cmake  [`install`](https://cmake.org/cmake/help/latest/command/install.html#installing-targets) command to tell **cmake_install** to gather all of the linked libraries and package them in my tarball. 

I created an example repository to showcase this issue so simply clone the [conan2_pkg_test](https://github.com/Hahn-Schickard/conan2_pkg_test) repository and follow the provided instructions to test locally or via docker.  Default cmake configuration produces the failure shown in the log below, while  `cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_NANODBC=OFF -DWITH_CURL=OFF -DWITH_SUBPROJECT=OFF ..` configuration works as expected.

### Logs

```bash
CPack: Create package using TGZ
CPack: Install projects
CPack: - Run preinstall target for: conan2_pkg_test
CPack: - Install project: conan2_pkg_test []
CMake Error at /conan2_pkg_test/build/sources/cmake_install.cmake:66 (file):
  file Could not resolve runtime dependencies:

    libcassandra.so.2
Call Stack (most recent call first):
  /conan2_pkg_test/build/cmake_install.cmake:47 (include)


CPack Error: Error when generating package: conan2_pkg_test
```

**Comment by memsharded** [comment]
Hi @saukijan 

I think this is a side effect of this https://github.com/conan-io/conan/issues/12654. If that is the case, we could close this as duplicate and follow up on that other ticket.

In short: Conan does not have enough information to define all ``IMPORTED`` locations for shared libraries for all platforms correctly. This is implemented in ``CMakeDeps``, but it is not easy to fix, because ``CMakeDeps`` is also lacking some information upstream.

Until this is improved (it is planned for 2.X roadmap, but this can take a while), maybe ``deployers`` can help to collect shared libraries from transitive dependencies? This is a related example of a deployer for runtime: https://github.com/conan-io/conan-extensions/blob/main/extensions/deployers/runtime_zip_deploy.py that could be used as an inspiration.

**Comment by dovydas-girdvainis** [comment]
Thanks @memsharded  for the info! I did not know `deployers` were a thing. I'll need to refresh my conan knowledge.

I decided to slightly modify [conan_provider.cmake](https://github.com/conan-io/cmake-conan/blob/develop2/conan_provider.cmake) module to use [`full-deploy`](https://docs.conan.io/2/reference/extensions/deployers.html?highlight=full_deploy#full-deploy) deployer and gather dependencies with a script. Not the cleanest solution, but it works. 

Best of luck improving the `CMakeDeps` generator!
