### ISSUE TITLE
What are techniques for producing recipes for in-house projects?

### ISSUE THREAD

**Issue by cleeland** [conan-io/conan#1486]
It seems that the motivating use-case for conan is packaging something produced by someone else and making that package available for use by consumers in a standard way.  In other words, defining and writing the recipe is wholly decoupled from producing and releasing the software on which the recipe acts. 
 That is definitely an under-served market, but it is not the only one.

In my case, the "something" is produced in-house and is consumed in-house.  Philosophically, we want to treat these packages as if each package's lifecycle is distinct from its requisite consumers' lifecycles, but from a production/packaging perspective, it does not make sense to decouple the release of these things from the recipe creation--at the time of release, we know everything we need in order to create a recipe.

It does not seem that conan works well with this model in its current form.  It seems that in order to do this with conan 0.24.0 I would need to do something along the following lines:

1. generate a temporary `conanfile.py` from a template, filling in version information
2. `conan export _user_/_channel_`, although I'd like to discuss what sort of best-practices there are for _user_ and _channel_
3. package using either `conan package_files` (for local binaries)

Am I off the mark?  Are others driving this with CI somehow (jenkins or gitlab ci)?  Is using a template (jinja?) to generate conanfile.py the right way to go, or is there a better way?

**Comment by mschmid** [comment]
We currently follow the approach to host a separate git repository with all our recipes. They all derive from a base class, therefore a single recipe can be kept relatively short.
Our Jenkins checks out the repository and builds the packages on a regular basis.
I don't think that this is overkill for in-house products, because you need to manage dependencies anyway. They cannot yet be generated automatically.

**Comment by memsharded** [comment]
Closing this ticket as very outdated, Conan has evolved a lot since then, with even new tools, practices, docs, and experience:

- ``conan new`` templates, both built-in and user templates
- Conan ``python_requires`` to re-use code
- Documentation for in-source (first party) and out-of-source (third party) recipes
- Extensive experience in conan-center-index Github repo that is used for ConanCenter, with +5000 PRs per year from the community.
