### ISSUE TITLE
[feature] ability to query the cmake file-api from the CMake build helper

### ISSUE THREAD

**Issue by weatherhead99** [conan-io/conan#14861]
### What is your suggestion?

Hello all,

long post below, TL:DR: I think we should have the ability to use the [cmake file-api] (https://cmake.org/cmake/help/latest/manual/cmake-file-api.7.html) from the `CMake()` build helper. This might allow all sorts of useful checks, automation, and higher level features that will save a lot of recipe typing in the future

recently I've been wrapping a few projects which have pretty reasonable modern CMake buildsystems (makes a change!). 
In one particular project, the compile definitions consumers need depend strongly on what the build options and settings are. The project in question also generates a quite nice "*Config.cmake" file as part of the build process. I should note this project has around 20 build options all of which get passed into cmake. The logic to determine which compiler options need to be set is basically as complicated as  the cmake build system of the project itself therefore.

My thought was to, instead of working out these compile definitions by hand (very easy to get wrong for so many options), that I would parse the generated .cmake file (kind of how we have a facility to do for .pc files), and extract the string. After all, the CMake build system knows better than me writing a conanfile what compile definitions we want. If they are wrong, it's an error in that build system and should be fixed there.

Whilst looking into this I stumbled across the cmake-file-api. Basically it allows us to cause cmake to output JSON files which semantically describe things like targets, files that have been visited and used, compile error logs etc.

Imagine I could write code something like this:

`def build(self):
    cm = CMake(self)
    cm.configure(api_query=True)
    cm.build()

...

def package_info(self):
    cm = CMake(self)
    res = cm.api_results()
    if res is not None:
        compile_defs = res["targets"]["MYtargetName"].... <some complicated query>

`
unfortunately, as it turns out, this JSON doesn't actually give you access to the target properties, I think some other approach might be a good idea for that though. 

Anyway for now I am submitting for consideration the idae that it might be a good idea to be able to parse the output of the cmake file-api into a dictionary like structure, so that we can query it for package information.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @weatherhead99 

Thanks for the suggestion. We had a tool in Conan 1, not documented, https://github.com/conan-io/conan/blob/develop/conan/tools/cmake/file_api.py, but this has been removed at the moment in Conan 2.0, because even if useful for some cases, it was not able to do the job completely, and it ended in ugly hybrids of some automatic information and some manual information on top of that.

We are trying to contribute to the standardization of some Common Package Specification that hopefully could render this unnecessary. But at the moment it this wouldn't be a high priority, as the value compared with the effort, and particularly the fact that it is not possible to have complete information, seems to be quite high. We will be happy to reconsider in the future if the CMake File API improves and gets enough information for this.

**Comment by weatherhead99** [comment]
ok, understood.
