### ISSUE TITLE
[question] Download all dependency sources (incl. transitive)

### ISSUE THREAD

**Issue by IvanRibakov** [conan-io/conan#14892]
### What is your question?

I would like to run my project through SCA (Software Composition Analysis) solution that checks for vulnerabilities from OSS components as well as checks for licensing issues. For that I need to fetch sources of all my dependencies (including transitive dependencies).

The closest I was able to get so far is the `conan install --build` command, but even with it I'm not sure if it will build transitive dependencies as well or only direct. And obviously I really don't want to wait for all the dependencies to build when I just need their sources.

Can what I'm looking for be achieved using Conan CLI?

P.S. I'm using Conan 1.x in my project.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @IvanRibakov 

Thanks for your question.

Collecting all sources without building is explained in this docs section: https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html

Basically using the ``-c tools.build:download_source=True`` forces the download of sources, then collecting those sources with a deployer, or from another recipe ``generate()`` is relatively straightforward.

> P.S. I'm using Conan 1.x in my project.

I am afraid it is not possible in Conan 1.X, the above is only in Conan 2.0. Conan 1.X had too much legacy to be able to add these things, and this is one of the reasons why Conan 2.0 was very necessary, to be able to implement and provide for these demanded use cases. 

As you pointed out the only way in 1.X is by forcing the build with ``--build``. That will do the build of all dependencies including transitive, yes, but the problem is that it can take long to build everything from source.
