### ISSUE TITLE
[question] Which binaries are provided by conan-center-index

### ISSUE THREAD

**Issue by Jean1995** [conan-io/conan#14907]
### What is your question?

Hi! I have a question regarding conan-center-index.

For a project for which we plan a release, we think about fixing the revisions of the recipes inside the conanfile.txt.

My question is: Will conan-center-index provide binaries built with this revision of the recipe, or does conan-center-index only provide binaries built with the most recent revision?
Because in the latter case, this would mean that at some point, all packages would need to be built locally, because the binaries won't be available on conan-center-index anymore, right?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Jean1995 

Thanks for your question. This could be moved to ``conan-center-index`` repo.

Things that are uploaded to ConanCenter are not removed. Binaries that exist for an older recipe revision will stay there, even if the new recipe revision doesn't build that configuration anymore. Said that, I think this is relevant:

- adding recipe revisions in ``conanfile.txt`` is not enough, because transitive dependencies will not lock the revisions, and can change
- Lockfiles would be a better solution for this. It is true that lockfiles are easier in 2.0, because in 1.X they can be a bit challenging.
- Depending on the business needs, building and uploading your own binaries to your own private server is more secure and way more robust. 
- A full guideline about using packages from ConanCenter in prod can be found in https://docs.conan.io/2/devops/using_conancenter.html, please have a look

Let me know if this clarifies it.

**Comment by Jean1995** [comment]
Thanks, this answers my original question and helps me to think further about this problem.

Would it also be possible to use lockfiles with conan 1.X. for this? From what I can see, lockfiles in conan 1.X are always specific to a certain profile. But if we want to ship a specific lockfile for a specific release of our software, this lockfile would depend on a specific profile, which is not what we want.

**Comment by memsharded** [comment]
> Would it also be possible to use lockfiles with conan 1.X. for this? From what I can see, lockfiles in conan 1.X are always specific to a certain profile. But if we want to ship a specific lockfile for a specific release of our software, this lockfile would depend on a specific profile, which is not what we want.

Yes, this is what I meant with my comment about lockfiles being more complex in 1.X than in 2.0. Yes, in 1.X it is necessary to have 1 lockfile per configuration/profile, while in Conan 2.0 it is good to have 1 single profile for all profiles.
In Conan 1.X it is possible to have a ``--base`` profile and then derive the profile-specific lockfiles from it to use them (but yeah, it is more convoluted)

**Comment by memsharded** [comment]
Closing this question as responded, don't hesitate to create new tickets for any further question, thanks!
