### ISSUE TITLE
[bug] unexpected version resolving conflict with range

### ISSUE THREAD

**Issue by X1aomu** [conan-io/conan#14905]
### Environment details

* Operating System+version: Windows 11 21H2
* Compiler+version: no matter
* Conan version: 2.0.10
* Python version: 3.10.8

### Steps to reproduce

1. write a simple conanfile.txt:

```
[requires]
paho-mqtt-cpp/[>=1.2.0 <2]
openssl/[>=1.1.1 <2]
```

2. run `conan install conanfile.txt` or `conan graph info conanfile.txt`
3. version conflict

However, this conanfile.txt (using qualified version) works:

```
[requires]
paho-mqtt-cpp/[>=1.2.0 <2]
openssl/1.1.1w
```

and this (just change the order) works too:

```
[requires]
openssl/[>=1.1.1 <2]
paho-mqtt-cpp/[>=1.2.0 <2]
```

The `paho-mqtt-cpp` actually requires `openssl/[>=1.1 <4]`

As i understand, version range in downstream will (and should) take precedence (this is [documented in Conan 1](https://docs.conan.io/1/versioning/version_ranges.html) but not mentioned in Conan 2 Doc). Those three conanfile.txt show some inconsistency.

We may need a bugfix or clarifying in document.

### Logs

Here is the log showing conflict:

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows
[conf]
tools.cmake.cmake_layout:build_folder_vars=['settings.arch']

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows
[conf]
tools.cmake.cmake_layout:build_folder_vars=['settings.arch']


======== Computing dependency graph ========
Graph root
    conanfile.txt: D:\src\test_conan\fuck_range\conanfile.txt
Requirements
    openssl/3.1.2#8879e931d726a8aad7f372e28470faa1 - Cache
    paho-mqtt-c/1.3.9#3bec15070efa4907c9750d43afce9040 - Cache
    paho-mqtt-cpp/1.2.0#8fb67b3e02d623651be24b62cbae0d8b - Cache
    zlib/1.3#06023034579559bb64357db3a53f88a4 - Cache
Build requirements
    nasm/2.15.05#ca1c14c2060af0ec151048b54ced9262 - Cache
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47 - Cache
Resolved version ranges
    openssl/[>=1.1 <4]: openssl/3.1.2
    paho-mqtt-cpp/[>=1.2.0 <2]: paho-mqtt-cpp/1.2.0
    zlib/[>=1.2.11 <2]: zlib/1.3
ERROR: Version conflict: Conflict between openssl/[>=1.1.1 <2] and openssl/3.1.2 in the graph.
Run conan graph info with your recipe and add --format=html to inspect the graph errors in an easier to visualize way.
```

**Comment by Kairo-Dai** [comment]
I'm having the same problem, the environment is the same

**Comment by memsharded** [comment]
Hi @Kairo-Dai @Kairo-Dai 

Thanks for your report.

What you are reporting makes sense, and it is the current implemented dependency resolution in Conan (both 1 and 2).
The dependency resolution follows the priority defined by the order of dependencies you define in your ``conanfile``. It allows to do some version-range validation, but it will not compute a full joint-compatibility (SAT solver problem, NP-hard) to find the joint intersection of valid versions (this has been discussed before, in this context, it easily become an intractable problem). 

So the way Conan expands the dependency graph is depth-first. In the case of having first ``paho-mqtt-cpp/[>=1.2.0 <2]``, what happens is:

- It resolves first to ``paho-mqtt-cpp/1.2.0``
- As you noted, this goes depth-first, finds a ``openssl/[>=1.1 <4]`` and resolves it to ``openssl/3.1.2``
- It continues graph expansion, now gets to ``openssl/[>=1.1.1 <2]``
- ``openssl/3.1.2`` is not in that range, and then it raise and invalid.

Then, if you change the order, and declare ``openssl`` first, it works, because the stricter constraint is evaluated first and then it fits in the range >1 <4.

I think there can be some further improvement for this case and we can try to extend a bit the joint compatibility for ranges for this specific case (without entering a full SAT solver), I'll give it a try and update here.

Just in case, please recall that openssl 1.1.1 has reached End Of Life (https://www.openssl.org/blog/blog/2023/09/11/eol-111/), and is not recommended anymore, please try to upgrade to openssl 3.X when possible.

**Comment by X1aomu** [comment]
@memsharded   Thanks for your explanation. It makes sense, and I've just believe that's how the 1st and 3rd `conanfile.txt` go on its way. 

Can you talk more about the second conanfile.txt? It seems both `[>=1.1.1 <2]` and `1.1.1w` are conflict with the `3.1.2`. It's not that clear why `[>=1.1.1 <2]` is bad but the other is okay. Is there something has been made to improve the joint campatibility for the `1.1.1w` case?

As for the EOL of openssl/1, I will upgrade it later. Though this problem is not specific to openssl, thanks for mention.

**Comment by memsharded** [comment]
Regarding the second case, it seems correct to me. The ``openssl/[>=1.1 <4]`` range is compatible with the ``openss/1.1.1w`` fixed version and it accepts it, isn't it?
This is indeed one of the improvements that Conan 2.0 has implemented in version ranges joint compatibility, if a fixed version is inside a valid range, it can be accepted as joint solution without really needing to expand to the latest in the version range that will be later conflicting.

What I am investigating with @RubenRBS is if the same can be done for 2 version ranges. It seems a bit more challenging, because it involves algebra over the restrictions of the version-ranges, but we think it is possible to come up with some pragmatic implementation that will cover a vast majority of cases.

**Comment by memsharded** [comment]
I have done an early draft in https://github.com/conan-io/conan/pull/14912, not guaranteed to move forward, but lets at least try it.

**Comment by X1aomu** [comment]
Good to know this was considered carefully, and even better that it might be improved further.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/14912, that will do better version-range intersection to further minimize conflicts. That doesn't mean that every conflict will be solved, but that a bunch of previous cases that were conflicting before, Conan will look and return the joint-compatible version range and solution without conflicting.

**Comment by X1aomu** [comment]
Big thanks for improving this :) @memsharded
