### ISSUE TITLE
[question] Override during package build

### ISSUE THREAD

**Issue by igorquest** [conan-io/conan#14918]
### What is your question?

I'm trying to build a package from source modified by the other team, so it's using custom local packages. Our local zlib is zlib/1.2.13@devops/stable but I can't figure out how to override during build. I tried requires("zlib/1.2.13@devops/stable", "override"), and build_requires("zlib/1.2.13@devops/stable", "override"), I tried adding it to build_requires in the build profile, nothing works. I'm still getting:

ERROR: Conflict in pcre2/10.42:
    'pcre2/10.42' requires 'zlib/1.3' while 'openssl/3.0.10@devops/stable' requires 'zlib/1.2.13@devops/stable'.
    To fix this conflict you need to override the package 'zlib' in your root package.

How do you override the package 'zlib' in the root package?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @igorquest 

Thanks for your question.
The answer might depend on the Conan version. It seems that you are still using Conan 1, but it is not fully clear.

In any case ``tool_requires`` cannot be overridden, as they are private to the dependencies that use them. It doesn't make sense to do ``build_requires("zlib/1.2.13@devops/stable")`` at all because ``zlib`` is a library, not a tool-requires, and tool-requires are exclusively for tools like "cmake", not for libraries.

Maybe if we had something that we could reproduce, that would help to try to check the issue and why the override might not be working.

As a side recommendation, when building packages for open source libraries, also used in ConanCenter, it is not recommended to add the ``user/channel`` at all, but keep the ``zlib/version`` without user and channel, with the same name and version as the ConanCenter packages. This new guide might be relevant to have a look too: https://docs.conan.io/2/devops/using_conancenter.html

**Comment by memsharded** [comment]
> Maybe if we had something that we could reproduce, that would help to try to check the issue and why the override might not be working.

Don't you want to provide some further details so we could fully understand what is happening and try to check for possible solutions?

**Comment by igorquest** [comment]
Not sure if what I'm trying to do is reasonable. It's a pretty big package and has lots of requires in requirements method which are conan center packages. Normally we don't even have conan center on our list, and it looks like those requirements are build time dependencies, so the proposed solution was to make them private, i.e. change requires to build_requires and move them to build_requirements. As long as they were in requirements, zlib override worked. As soon as they moved to build_requirements, it stopped working.

**Comment by memsharded** [comment]
> Not sure if what I'm trying to do is reasonable. It's a pretty big package and has lots of requires in requirements method which are conan center packages. Normally we don't even have conan center on our list, and it looks like those requirements are build time dependencies, so the proposed solution was to make them private, i.e. change requires to build_requires and move them to build_requirements. As long as they were in requirements, zlib override worked. As soon as they moved to build_requirements, it stopped working.

Yeah, moving them to "build_requirements" from regular "requirements" will most likely not work, it is not just about being private, but build-requires/tool-requires work very differently than the others, they are intended only for executables, not for libraries, so they will not propagate library information for example.
