### ISSUE TITLE
[feature] Add `uninstall` to package manager interface

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#14913]
### What is your suggestion?

The existence of a package on a system can change how it is built. Therefore you may need to uninstall a package when building. It would be nice to have interfaces for this.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by xandox** [comment]
why does `conan remove` not enough?

**Comment by rconde01** [comment]
this refers not to a conan package, but a system package. e.g. via PacMan

**Comment by memsharded** [comment]
Thanks for your suggestion @rconde01 

We did consider and discussed this in the past, and we discarded it because of being quite a risky feature.
The reason is that installing packages, even with ``sudo`` is relatively safe, as adding new non-installed packages is unlikely to break existing builds. But on the other hand, uninstalling already installed packages in a system is quite a risky operation. Why are the packages there in the first place? Having some dependency recipe to remove system packages sounds risky and likely to unexpectedly break when that recipe is not used in the right system.

For example if this feature was implemented, we should actively forbid this from ConanCenter, with some automated check to avoid such a removal to ever happen in ConanCenter packages. Such thing is an indicator that this is at least a controversial feature.

Do you have some real example of a package that would require some system package to be uninstalled? Some detailed use cases could contribute to the discussion.

**Comment by rconde01** [comment]
Everything you're saying makes sense...I do have a package which I believe will use certain functionally conditionally based on the library being on the system...but i probably should just request they add a switch to control this. In the meantime I can just call the command line to remove the package for this special case. Feel free to close.

**Comment by memsharded** [comment]
Ok, sounds good, I'll close.

If you still find yourself with this problem again for more than this very specific package, feel free to re-open, illustrate about the specific packages you want to remove, and the command line to remove them and we can reconsider and discuss. Thanks for the feedback!
