### ISSUE TITLE
[question] Why does export_sources copy to the repository root?

### ISSUE THREAD

**Issue by jastich** [conan-io/conan#14937]
### What is your question?

Using Conan 1.61, I have a project structure like this:

```
all/
    patches/
    conanfile.py
```

The conanfile contains an `exports_sources` attribute and also implements a `source()` to pull some files from Artifactory.

`exports_sources = "patches/*"`

My package also defines a `self.layout` with:

```python
    def layout(self):
        self.folders.root = os.pardir
        self.folders.source = 'src'
        self.folders.build = 'build'
```

When executing the `conan source` command, I want Conan to copy the exported source (`patches/*`) into the `src/` folder, like this:

```
all/
    patches/
    conanfile.py
src/
    src_from_artifactory/
    patches/
```

However, it copies it into the root of the project instead:

```
all/
    patches/
    conanfile.py
patches/
src/
    src_from_artifactory/
```

I see the similar behavior in the cache when calling `conan create`, where `patches/` is adjacent to the `src/` directory instead of within it:

```
export_source/
    patches/
source/
    patches/
    src/
```

I believe the code that causes this behavior is this:
https://github.com/conan-io/conan/blob/release/1.61/conans/client/source.py#L65

What's the rationale, or what should I be doing differently?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @jastich 

Thanks for your question:

> When executing the conan source command, I want Conan to copy the exported source (patches/*) into the src/ folder, like this:

Note that in Conan 2.0 the ``conan source`` command will no longer do any ``export`` functionality. It is expected that all things, including the patches are already in the correct relative location.

I think I might not fully understand your layout, specially why you have ``self.folders.root = os.pardir``, because your conanfile seems to be in the root. Maybe you could clarify the full project local layout? I'd say that if that line is dropped, everything might fit better.

**Comment by memsharded** [comment]
Closing this ticket as staled, never got feedback or clarifications of the local layout.

Please create new tickets for any further question you might have. Thanks for the feedback.
