### ISSUE TITLE
[question] Is Conan v1 still supported?

### ISSUE THREAD

**Issue by spakarl** [conan-io/conan#14941]
### What is your question?

I have a very big project and need the qmake generator. That generator is not available with Conan v2. Can I still use Conan v1 these days? The project has a lot of dependencies to libraries stored in Conan Center.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @spakarl 

Thanks for your question.

Yes, definitely, Conan 1.X is still supported:
- All PRs to ConanCenter still build with Conan 1.X, and not planned to drop 1.X at this moment.
- Conan 1.X releases still happen, less frequently, and only some bugs, updates and backports to ease the migration, but still happen
- There is no plan to break ConanCenter for 1.X, but actually to have a mechanism that it can still be used for some more time.

But please bear in mind:
- It is important that in Conan 1.X there are both legacy generators (cmake, cmake_find_package) and new generators (CMakeDeps, CMakeToolchain). Even if not intentional, it is possible that legacy generators might eventually break
- Less configurations are built for 1.X than they were in the past. That means that if you depend on some specific compilers or configurations, new builds might drop them and you will find no binaries.
- It is expected that updates to ConanCenter for 1.X will stop happening at some point. Packages will not be removed for some time, but new PRs will only build for Conan 2.0. ConanCenter for 1.X will be "frozen"

If you depend on ConanCenter in production, depending on your needs, you might want to read https://docs.conan.io/2/devops/using_conancenter.html and follow the guidelines, maybe use lockfiles, or maybe do a copy of the packages you depend on.

And in general, the upgrade to Conan 2.0 should be prioritized. It was launched in February already after 2 years of alphas and beta releases. If the generator ``qmake`` is a blocker, please try to push for it, maybe creating your own custom new ``QMakeDeps`` in a python-require, maybe contribute it to built-in, or at least explicitly request it here as a ticket.

Many thanks for your feedback!

**Comment by spakarl** [comment]
Thanks for the clarification @memsharded. I tried to convert the pkg-config.pc files into a qmake configuration. But I failed, as I could not find the DEFINE flags that used to be there in Conan 1.  Unfortunately I can't create my own implementation of the generator because I don't have the knowledge to do so. I did program in python before, but I don't have a picture of all that conan internals. So I will create a request ticket for qmake integration in Conan V2.
