### ISSUE TITLE
[question] How to collect information about upload event in Conan v2

### ISSUE THREAD

**Issue by rjulius23** [conan-io/conan#14942]
### What is your question?

Currently we are using conan post_upload hook to collect information about the package after successful upload like:
```
    payload = {
        "remote_name": remote.name,
        "remote_url": remote.url,
        "repo_url": repo_url,
        "merge_commit_id": commit_id,
        "conan_package_id": package_id,
        "conan_recipe_hash": package_revision,
        "conan_package_reference": str(reference),
        "conan_package_full_reference": reference.full_str(),
        "git_branch": active_branch,
        "duration": duration_in_millis,
        "timestamp": str(finished_time),
        "conaninfo_dependencies": conaninfo_dependencies,
    }
```

If someone can point me towards a solution to collect the same info in conan v2 on event basis that would be appreciated.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rjulius23 

Thanks for your question.
As you have probably realized, the upload hooks have been removed at the moment in conan 2.0, and only pre/post recipe methods hooks are maintained.
We were waiting for users feedback around these use cases, because in Conan 2.0, things that are not tied to recipe methods have been moved to "plugins" instead. So it would be very interesting to know a bit more of your use case, to discuss what would be the best way moving forward this in Conan 2.0:

- What are you doing with that data that the hook collects?  Is it stored in file format, maybe json? Where is it stored?
- How do you use later that information?
- Is it possible that you would like to store package information as metadata files together with the package (there is a new feature called "metadata files", already released, pending to be publicly launched, specifically designed to be used as storage of this kind of metadata associated to packages.

Many thanks for your feedback!

**Comment by rjulius23** [comment]
**What are you doing with that data that the hook collects? Is it stored in file format, maybe json? Where is it stored?**

We are pushing the data in JSON format to a cloud based proprietary service(which scales by the number of events) of our own which eventually stores the info in a PostgreSQL Database. 

**How do you use later that information?**

We are monitoring Software Value Stream Lead Times based on Conan package upload information (checking if new version is pushed and also checking if any dependencies changed compared to the previous upload event.) In case of dependency change we can assume it is a new integration(delivery event). The reason it is important, is that we have 100s of packages, and with an event based approach we can scale way better. The alternative is to store the data next to the packages and pull it regularly, but that is way more costly. This way we only get trigggered if there is an actual new version uploaded. Another thing is that we only monitor uploads from CI pipelines.

**Is it possible that you would like to store package information as metadata files together with the package (there is a new feature called "metadata files", already released, pending to be publicly launched, specifically designed to be used as storage of this kind of metadata associated to packages.**

See my answer above about this approach. It is not optimal compared to what we have now in conan v1.

**Comment by rjulius23** [comment]
based on this @memsharded what do you think, what would be the best approach from our side ? Contribution to the code base? Create a custom plugin that basically implements the upload hook ?

**Comment by memsharded** [comment]
Thanks very much for explaining the use case, I understand it better.

I can explain a bit the rationale of the removal of those hooks:
- Recipe methods hooks like pre-build and post-build need to happen more synchronously with the package building. There is not specific isolated "build" functionality when a package is being created in the cache, but actually all steps like source + build + package happens in the cache when the package is ``conan create``
- Other hooks have been dropped, because it is very likely that other new features could be more adequate. For example the ``conan upload`` functionality is working over already existing packages, which are immutable, so they cannot be changed, only read. I think that something like this could be a better approach than a hook:
  - Do the ``conan upload`` and capture the resulting ``package list`` (with ``conan upload ...--format=json``)
  - Do a custom command ``conan myteam:upload_info upload_pkg_list.json ...`` that iterates the package list and perform the desired collection and upload of the data.

Some potential advantages:
- The custom commands are managed with ``conan config install``, so no difference in convenience here.
- The custom commands are more ergonomic and parametrizable. You can very easily add arguments like ``--server-url=xxx`` or other stuff, in a more natural way (parametrization of hooks is not natural).
- Output is cleaner, and easier to debug, as it is a bit more decoupled from the package upload.
- Data upload to the external service can be more atomic and efficient, for example, it might accept one upload with all the data for multiple packages, instead of one at a time.

**Comment by memsharded** [comment]
Hi @rjulius23 

Any feedback regarding the proposed flow above with custom commands?

**Comment by czinegeandris** [comment]
Hello @memsharded,

I am a colleague of @rjulius23 also involved in this topic. Thank you for picking up our issue and dealing with it.
Even after reading through your extensive answer I am still not 100% sure whether our use case with Conan 1.x can be covered in Conan 2.x with the solution you've suggested, and I would appreciate your opinion about this.

So if I understood correctly, the best way to capture upload data would be to implement a custom command that takes the list of uploaded packages as input thanks to the `conan upload ... --format=json` command, and in our custom command we could use the Conan API from Python to "query" the desired information of the uploaded packages that we need and then finally send the information to our service however we want.

To understand our context better, we are a developer team responsible for developing "plug-and-play" solutions for monitoring certain activities for other teams. With Conan 1.x, simply developing a Python hook module for custom use and installing it with the `conan config install` was quite convenient, but now it seems that Conan 2.x would change this to installing the hooks/commands, and then adjusting the CI/CD pipelines accordingly to achieve the same functionality.
This sounds easy, but in our case these solutions are requested by other teams dealing with Conan packages, and this would also require them to change their setups as well to achieve a certain functionality, and with tens of teams to look after, this is not so convenient anymore.

**Comment by memsharded** [comment]
Thanks for the feedback @czinegeandris 

> With Conan 1.x, simply developing a Python hook module for custom use and installing it with the conan config install was quite convenient, but now it seems that Conan 2.x would change this to installing the hooks/commands, and then adjusting the CI/CD pipelines accordingly to achieve the same functionality.

Yes, I was thinking that adjustments to the pipelines are necessary in any case, because the commands are not the same in Conan 2.0, and specifically some important features like lockfiles have been completely revamped and they can imply important simplifications to the pipelines too. So I was thinking that adding one extra command call after the ``conan upload`` commands was not a big inconvenience. But I understand your point of view, let me take it again to the team and discuss it.

**Comment by memsharded** [comment]
I am having a new look to this, thinking about the "plugin approach".

There is one very important aspect that I have not mentioned: Custom commands can be implemented that overwrite the built-ins ones. So it is perfectly possible to implement a ``conan upload`` command, customizing it, put it in the ``conan config install`` repo, and then all the users will automatically get that command that executes the additional upload tasks of that data to your server. 

In this way, you can still deliver the functionality you want to all the teams you are serving without requiring them to change a single comma anywhere.

What do you think? Maybe this would be the best solution? At the end of the day, the ``upload`` command code is 150 lines of Python code, the level of control and power you have to implement things would be higher than possible plugin approaches, and maintenance should be very reasonable.

**Comment by rjulius23** [comment]
This sounds great. Just a question. When distributing the custom command across different projects what is the best way ? I mean now with the hooks we give them the repo URL and they run the conan hook install command. With custom commands is it similar ?

**Comment by memsharded** [comment]
> This sounds great. Just a question. When distributing the custom command across different projects what is the best way ? I mean now with the hooks we give them the repo URL and they run the conan hook install command. With custom commands is it similar ?

Yes, the process is the same, ``conan config install <url>``, and then the only thing to take into account is that custom commands will live in a specific folder, and it will be installed in the Conan cache and run from there. It can be updated executing ``conan config install <url>`` again.

**Comment by memsharded** [comment]
Ok, I'd say that the custom command ``upload`` to overwrite the Conan built-in command is the way to go, so at the moment we are not planning to add any new hooks or plugins for upload, there is no immediate action from our side.

I am closing this ticket as responded, but please do not hesitate to re-open or create a new ticket if you have any further question or need help with the implementation of the custom command. Many thanks!
