### ISSUE TITLE
[question] How to create and use alias packages with Conan v2?

### ISSUE THREAD

**Issue by tonichedgehog** [conan-io/conan#14956]
### What is your question?

Hi, I have a question on how to create and use alias packages with Conan v2, as I'm experiencing some unexpected behavior while trying. In my example I have two packages:
 - A Conan package of a shared library, Foo, referenced as `foo/22.1`
 - An application, Bar, that uses Foo as a dependency, requiring `foo/22.1`

In this example, Foo provide its own FooConfig.cmake, which is copied to the package folder, so generation of foo-config.cmake  by Conan is turned off using the following `package_info()` for Foo's conanfile.py:
```
    def package_info(self):
        self.buildenv_info.define('Foo_ROOT', self.package_folder)
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.builddirs.append(self.package_folder)
```
The basic use case here (installing Foo as a dependency for Bar) works as expected. But, if I instead:
 - build the Foo package as `foo/22.1@foobot/ci`, and
 - create an alias package `foo/22.1`, pointing to `foo/22.1@foobot/ci`

I would expect Conan to pick up the alias during the `conan install` step for Bar, and and install the dependency as above. But in this case the `cmake_find_mode property` seems to be lost, as foo-config.cmake is generated (and consequently, CMake configure fails). Am I missing something essential here when creating the alias package?

[repro.zip](https://github.com/conan-io/conan/files/12999403/repro.zip)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tonichedgehog 

Thanks for your question and the repro code.

> create an alias package foo/22.1, pointing to foo/22.1@foobot/ci

The first important comment is that ``alias`` is practically not documented in Conan 2.0. This is because ``alias`` packages will no longer be recommended. Conan 2.0 has improved over the limitations of Conan 1.X regarding versions and version ranges, and using standard versioning would be the recommended approach. ``alias`` was created as a workaround before Conan 1.X implemented version ranges.

Regarding your question there are a couple of issues:

- Alias ``pkg/(alias)`` syntax was introduced in Conan 1.X as a mechanism to explicit the alias requirement
- Conan 2.0 has made this syntax compulsory for alias. If the ``/(...)`` parenthesis is not there, it will be resolved as a normal package, not as an alias (and then fail, because it will not forward to the other one)
- It seems you have a typo in your alias recipe with ``alias = "foo/foo/22.1@foobot/ci"`` (double foo)


With the ``(...)`` syntax you might make it work, but still it would be very recommended to drop the alias and use versioning. Furthermore, it is no longer recommended to use ``user/channel`` qualifiers as something dynamic, and they should be treated as immutable. The ``foo/version`` package should have the same user/channel always in the same project and CI (it is possible to have a "testing" channel at some stage in the life in the project, and then replace it for a "stable" one, but not using different channels of the same thing in the same project, like using ``foo/version`` with and without user and channel).

**Comment by tonichedgehog** [comment]
Hi, and thanks for your response, and spotting the typo (although it didn't make much of a difference). I take your answer that I _might_ get it to work, as aliasing is becoming sort of deprecated? If so, perhaps it's worth mentioning in the migration guide.

I'll follow your advice and drop aliasing.

Thanks,
/T

**Comment by memsharded** [comment]
> I take your answer that I might get it to work, as aliasing is becoming sort of deprecated?

I think that making your ``requires = foo/(22.1)`` and fixing the typo will make it work (and also work in Conan 1.X).

So depending on the needs, it is good to keep using it, finish the migration to Conan 2.0, then in a later stage, try to drop the alias. Doing the migration as well as a change of versioning strategy might be too much, and this is the reason we maintained the ``alias`` in 2.0, albeit poorly documented. My advice was more thinking in mid-long term, but of course if it is possible to drop the alias in the short term, that is good too.

Maybe we can close this ticket as responded? You can open new tickets too for any further new or follow up questions. Thanks!

**Comment by tonichedgehog** [comment]
Yes, my question is answered, so I'm closing it. Thanks for your time and effort.
