### ISSUE TITLE
[question] Migration to Conan 2.x - How to get package root via CLI

### ISSUE THREAD

**Issue by MichalCermakx** [conan-io/conan#14974]
### What is your question?

Hi,

In Conan 1.x I have been using "conan info --paths ." command, which gives me a path set (export, source, build, package folders) for all dependencies referenced in the root conanfile.py:
sqlite-tools/3.40.1.0
    ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    BuildID: None
    Context: host
    export_folder: D:\.conan\data\sqlite-tools\3.40.1.0\_\_\export
    source_folder: D:\.conan_short\17863a\1
    build_folder: D:\.conan_short\c9fd7d\1
    package_folder: D:\.conan_short\e4d2ad\1
    
Currently, I am migrating this into Conan 2.x. When I run "conan graph info ." command, I am getting only recipe_folder populated, but not the others (This is after conan install, therefore at least package_folder should not be None):
  recipe_folder: C:\Users\<Name>\.conan2\p\sqlita94438b3fe3c6\e
  source_folder: None
  build_folder: None
  generators_folder: None
  package_folder: None
  
Even in the example here https://docs.conan.io/2/reference/commands/graph/info.html, those paths are None: 
  
The only option I found is to call conan cache path <ref>, but this gives me only a single package path. Ideally, I would like to get it via a single call. Is this possible? Is there a way to get for example package_folder filled via graph info?

Unrelated question - I do not want to make another post: I really like the tqdm progress bar usage in Conan 1.x. I noticed this is no longer there in Conan 2.x. Is there a way to enable it? If not, do you plan to add it in the future?

Thanks,
Michal 
 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MichalCermakx 

Thanks for your question.

There are a couple of different approaches to get paths from the Conan cache.

The first one is the one that you mentioned is using the ``conan cache path pkg/version`` command, very simple and straightforward, and can return the ``--folder`` that you want. Using that argument for "recipe" folders like export or source, and use ``conan cache path pkg/version:package_id`` to get the folders for a package binary.

The second one, is getting the information from the graph. The ``conan graph info`` do not install binaries at all only recipes, this is the reason that the different build and package folders are ``None``, because the binaries don't even need to be downloaded. If you want to get the build and package folders you need to use the ``conan install --format=json`` instead.

But probably, the preferred approach is not using command to get access to folders, but if you are automating some task to copy files from the cache, for the whole dependency graph, the recommendation would be to use deployers: https://docs.conan.io/2/reference/extensions/deployers.html, there are built-in deployers, and you can also easily create your own custom deployer, and use it with ``conan install ... --deployer=mydeployer``, in an integrated way (and distribute it with ``conan config install``)


> Unrelated question - I do not want to make another post: I really like the tqdm progress bar usage in Conan 1.x. I noticed this is no longer there in Conan 2.x. Is there a way to enable it? If not, do you plan to add it in the future?

Progress bars were actually quite problematic in 1.X and we had to add a few workarounds for those issues, and still was causing problems from time to time. We decided to fully remove them, it is simply not worth the codebase complexity and introduced extra fragility, at the moment there are not plans to add progress bars again. There might be some slow operation that we might want to add further progress messages, but not in progress bar form.

**Comment by memsharded** [comment]
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!
