### ISSUE TITLE
CMAKE_MODULE_PATH not updated in multi-configuration project

### ISSUE THREAD

**Issue by miqelm** [conan-io/conan#1498]
Hello,
I'd like to create Visual Studio project with Debug and Release mode. In CMakeLists.txt file I have searching for Protobuf (since I have to generate necessary files from *.proto file). Without explicitly setting CMAKE_BUILD_TYPE to either Debug or Release CMAKE_MODULE_PATH isn't updated with packages root paths and due to that fact searching for library fails.

Code in conanbuildinfo_multi.cmake:
```
macro(conan_set_find_paths)
    if(CMAKE_BUILD_TYPE)
        if(${CMAKE_BUILD_TYPE} MATCHES "Debug")
            set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH_DEBUG} ${CMAKE_PREFIX_PATH})
            set(CMAKE_MODULE_PATH ${CONAN_CMAKE_MODULE_PATH_DEBUG} ${CMAKE_MODULE_PATH})
        else()
            set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH_RELEASE} ${CMAKE_PREFIX_PATH})
            set(CMAKE_MODULE_PATH ${CONAN_CMAKE_MODULE_PATH_RELEASE} ${CMAKE_MODULE_PATH})
        endif()
    endif()
endmacro()
```

For my needs, I had to hack it to this form:
```
macro(conan_set_find_paths)
    set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH_RELEASE} ${CMAKE_PREFIX_PATH})
    set(CMAKE_MODULE_PATH ${CONAN_CMAKE_MODULE_PATH_RELEASE} ${CMAKE_MODULE_PATH})
endmacro()
```

Do you think, that something should be improved? I don't want to specify CMAKE_BUILD_TYPE, because it will enable only one configuration in Visual project.

**Comment by memsharded** [comment]
This is a known limitation of cmake. Paths for modules, and cmake config files, cannot be multiple, they don't work for multi-config environments like visual studio. So the ``cmake_multi`` generator cannot help with this, because CMake is only able to find the path to 1 variant, the debug or the release one, but not both.

I suggest to try these two different approaches:
- Do not use cmake Find features at all. Conan already models all the information needed to locate and use the package, so no need to "find" them. You can directly use the conan created variables.
- Use multi-configuration packages. You can try creating your own packages that  package together the debug and release artifacts: http://docs.conan.io/en/latest/packaging/package_info.html#multi-configuration-packages

It is possible that what you might be suffering (regarding the first approach), is something related to the protobuf package. If the protobuf package just adds itself to the path in ``env_info`` consumers can directly invoke ``protoc`` without having to do anything special, directly in the conanfile, something that I find really convenient.

**Comment by memsharded** [comment]
The fix you are proposing works just in your case for executables, but will fail for libraries. So it doesnt matter if you call the release ``protoc`` while building a debug package. The correct solution might be to create a specific package just for ``protoc`` and remove the unnecessary configurations.

**Comment by KalleDK** [comment]
Hi @memsharded - I came just for this edge case - as I develop/pack libraries and try to make it as "open" as possibble. 

The reason for me to use find_package is that I deliver compile options / definitions via the target. Which does not get propegated via conan (afaik).

It also makes conan "optional" if people have the library installed the won't need conan. But if they don't conan provides an easy way for them to optain it.

**Comment by memsharded** [comment]
> The reason for me to use find_package is that I deliver compile options / definitions via the target. Which does not get propegated via conan (afaik).

Yes, you can have compile definitions propagated to consumers from the conanfile, and they are fully propagated in the dependency graph, so something like:

```python
def package_info(self):
     if self.settings.build_type=="Debug":
            self.cpp_info.defines = ["MYLIB_DEBUG"]
            self.cpp_info.cppflags = ["--some-debug-flag"]
     if not self.options.shared:
            self.cpp_info.defines.append("MY_LIBSTATIC")
```

I understand find_package is convenient to be transparent/optional for users, but still not something we can fix it, it is a known limitation of cmake, so if using ``find_package`` functionality, then ``cmake_multi`` will not work. My best guess for unblocking this is a full VS add-on/plugin that manages switching the conan build_type, but that will take time.

Thanks for your feedback!

**Comment by KalleDK** [comment]
I know it's a corner case with the multi and find_package, and I rather "force" to single and then have consistency.

About the propagation - I've made a small example (as small as I could) to show what I mean

https://github.com/KalleDK/TargetDef

if you try doing conan create xxx/1.0

It will fail due to missing flags, but if you switch to find_package (prepared with an if) in the test_package/CMakeLists.txt it will work

This is tested with cmake_installer from conan and Visual Studio 17

Yes you could add the defines via conan, but my concerns are
* Is the flag then added to all their libraries?
* If they themself is a library then consumes my library PRIVATE, will this define stay private (Not polute users of their library)
* I would now need to keep track of my flags from both conan and CMake - If they use find_package I need to distribute flags via targets, if they use conan, then flags from there.

**Comment by KalleDK** [comment]
Maybe conan could consume the targedefConfig.cmake files and use that when it creates it's .cmake file - Have not looked into it, but a stray thougt.

**Comment by KalleDK** [comment]
I made a few updates to the demo so that it "fails" both on windows and linux, but works if you use find_package

**Comment by KalleDK** [comment]
Aaah I just realised that some consumers of my lib could not be using cmake, and and only downloading the binary/headers, and then conan needs to provide the definitions.

Thought it would still be great if somehow conan could consume the definitions via the EXPORT, as it already can consume the headerfiles and lib with the INSTALL

**Comment by memsharded** [comment]
> Aaah I just realised that some consumers of my lib could not be using cmake, and and only downloading the binary/headers, and then conan needs to provide the definitions.

Yes, that is a good point. Indeed, conan decouples the package build system from the consumers, so even if it is possible to reuse some specific files from build systems, it is much more general to provide a ``package_info()`` method.

> Thought it would still be great if somehow conan could consume the definitions via the EXPORT, as it already can consume the headerfiles and lib with the INSTALL

Not sure what you mean here, but it sounds this is basically the role of conan generators. The information in ``conanbuildinfo.cmake`` comes from the ``package_info()`` of dependencies (when selecting ``cmake`` generator, but the same can be said for .pc files from the ``pkg_config`` generator. Can you please clarify? Thanks!

**Comment by KalleDK** [comment]
I already "use" it in the demo lib I linked. What I mean is that if you use `cmake.install()` in you `build()` you don't need to do any copy or anything in your `package()`. It would be nice if it also could look in the .cmake files genereated

share/targetdef/cmake/targetdefConfig.cmake
```
add_library(targetdef SHARED IMPORTED)

set_target_properties(targetdef PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "TARGET_A"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```

share/targetdef/cmake/targetdefConfig-debug.cmake
```
set_property(TARGET targetdef APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(targetdef PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/lib/targetdef.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bin/targetdef.dll"
  )
```

That way you would "easily" could create a target that would match find_package targets - and also provide defines etc to other build systems

**Comment by memsharded** [comment]
The problem with those files is that they only exist at build time, but the ``package_info()`` method need the information at usage time (you might be just reusing a binary retrieved from a remote, without a local build). 

So the responsible of doing this must be the ``package_info()``, which means that those ``targedef.cmake`` files must be packaged too (with the cmake install feature, or with the ``package()`` method), which already feels a bit dirty IMHO. Then, you need parsing those files, which is typically harder than it seems, and then it might be also fragile due to changes in those files, maybe while upgrading cmake version, and of course dealing with all different platforms variants (.lib, .a, .so, .dll, etc). That could require a bunch of code inside conan to maintain and support. 

As usual, it is a trade-off. In practice, the repetition of flags and defines you have to do in ``package_info()`` is typically very little, just a few lines. It is totally explicit, easy to maintain, easy to debug and understand, so consumers might have easier time detecting and reporting bugs. And most times doesn't require any change when releasing new package versions.

**Comment by KalleDK** [comment]
The installation of the cmake files is quite normal feature for cmake, so that find_package can be used easily by others that have your lib installed.

I do get that the parse part could be troublesome. Maybe the CMake Class could have methods to extracts it - thereby making it optional / explicit

```
package_info()
    with cmake.target(targetdef) as targetdef:  # I don't know if you already have a model for a cmake target
        self.cpp_info.defines = targetdef.defines
        self.cpp_info.cppflags = targetdef.cppflags
```

**Comment by sourcedelica** [comment]
I just ran into this (we are starting to use Conan for VS projects).  Is there a solution now for `find_package` with `cmake_multi`?   If we don’t use `find_package` we will need to “fork” the CMake macros that the Protobuf package provides. They depend on `find_package` being run.

**Comment by memsharded** [comment]
Basically, it is not possible to run standard find_packages with multi-configuration, that is a limitation of cmake find_packages. This is the reason the ``cmake_find_package_multi`` generator is relatively complex, to implement a multi-config replacement of cmake stock find_packages.

**Comment by sourcedelica** [comment]
Thanks.  I've replaced `cmake_multi` with `cmake_find_package_multi` in our project `conanfile.py` and it works.  I kept the `cmake` generator to avoid having to add lots of `find_package`s.  I only need `find_package` for a couple of libraries: Protobuf and Poco.  Poco because we are using `CONAN_LIB` to use individual libraries.  For example:
```
if (MSVC)
    if ($<CONFIG>) 
        find_package(Poco)
        set(POCO_ODBC_LIB CONAN_LIB::Poco_PocoDataODBC$<$<CONFIG:Debug>:mdd_DEBUG>$<$<CONFIG:Release>:md_RELEASE>)
    endif()
else()
    set(POCO_ODBC_LIB CONAN_LIB::Poco_PocoDataODBC$<$<CONFIG:Debug>:d>)
endif()

target_link_libraries(data-service PRIVATE data-service-lib ${POCO_ODBC_LIB})
```

**Comment by memsharded** [comment]
Hi @sourcedelica 

Then certainly you want to keep an eye and try the 1.27 release that will provide ``components`` support for ``cmake_find_package_multi``, so when the Poco recipe implements components, then integration should be even more transparent.

**Comment by sourcedelica** [comment]
Awesome!  Will do.

**Comment by memsharded** [comment]
Closing this ticket as outdated, the above mentioned generators have been removed in Conan 2.0, new generators like ``CMakeDeps`` are already multi-config by default
