### ISSUE TITLE
Provide means in configuration to override CMAKE_CXX_FLAGS_XXX

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#14985]
Hello
Conan 2.0.9

I'm specifying compile flags in my profile with

```
...
[conf]
tools.build:cxxflags=[...]
...
```

This works great. But cmake still adds its default debug/release flags.
I would like a configuration parameter to set the `CMAKE_CXX_FLAGS_XXX` flags.
This could be a general configuration like `tools.build:cxxflags_xxx` or a cmake specific one like `tools.cmake.cmaketoolchain:cxxflags_xxx`.

What is the current recommended way of setting these flags?

Doing it in my recipe does not seem to do the job as the cache variables created in the toolchain on behalf of the code below will add the specified flags but not remove the default flags:
```
tc = CMakeToolchain(self)
tc.variables["CMAKE_CXX_FLAGS_DEBUG"] = "-O0 -ggdb"
tc.variables["CMAKE_CXX_FLAGS_RELEASE"] = "-s -Os"
tc.generate()
```
Resulting compile flags (which is a combination of my flags and the default flags):
```
... -s -Os -O3 -DNDEBUG ...
```

Regards
Klaus

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Thanks for your question.

> Conan 2.0.9

Please try to stay always in the last patch of every minor release. Only that last patch is recommended.

> I would like a configuration parameter to set the CMAKE_CXX_FLAGS_XXX flags.
This could be a general configuration like tools.build:cxxflags_xxx or a cmake specific one like tools.cmake.cmaketoolchain:cxxflags_xxx.

I think this is a "toolchain" job. You are trying to change how the CMake default toolchain works.
Conan allows you to inject any arbitrary toolchain file, with any arbitrary CMake variables. I think this can work also for CMAKE_CXX_FLAGS variables.

You can inject any arbitrary toolchain with the conf ``tools.cmake.cmaketoolchain:user_toolchain=[]``. Please check the docs in https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/inject_cmake_variables.html, and let me know.

**Comment by klausholstjacobsen** [comment]
@memsharded I get your point. But I think your argument would apply to tools.build:cxxflags as well. So why is this a part of the default toolchain?

If I should take your advice I should remove tools.build:cxxflags from my profile as well, or?

My reasoning was/is that these flags, general or build type specific, are tightly coupled to the profile as different OS, compiler or compiler version will result in different flag values.

Regards
Klaus

**Comment by memsharded** [comment]
> If I should take your advice I should remove tools.build:cxxflags from my profile as well, or?

I am not sure, and specially if you are setting some flags that overlap with the default CMake flags, you might not want to not pass flags, but something like this:

- ``tools.build:cxxflags`` aims to apply to all build systems. You could have dependencies that do not use CMake at all, and you might need to inject some variables (Conan integrations might try to add the equivalent to CMake default flags, in AutotoolsToolchain, for example)
- The CMake toolchain injection is exclusive for CMake, and in this case it seems you want the opposite, basically to remove the defaults, or define empty CMAKE_CXX_FLAGS, so the ``tools.build:cxxflags`` will be listened to without overlap.

Of course it depends if you are not using any dependency that is using other build system rather than CMake, then it could be limited to CMake, and you might drop ``tools.build:cxxflags`` and define the final flags in the cmake toolchain file.

**Comment by klausholstjacobsen** [comment]
Affirmative. Thanks!
