### ISSUE TITLE
conan_package_library_targets is not finding the library even though it is built successfully

### ISSUE THREAD

**Issue by i-lina** [conan-io/conan#15021]
### Environment details

* Operating System+version: Windows ARM64
* Compiler+version: Cmake 3.27.1 / Visual studio 17 2022
* Conan version: 2.0.13
* Python version:3.11.3

[env.txt](https://github.com/conan-io/conan/files/13191517/env.txt)

### Steps to reproduce

I am trying to build audacity package that uses Conan for its dependencies. One of the dependency is the wxwidgets. I do see the wxmsw31ud.lib is built and available in the package folder .conan2/p/b. Yet the function return an error
CMake Error at build/generators/cmakedeps_macros.cmake:67 (message):
  Library 'wxmsw31ud_xrc' not found in package.  If 'wxmsw31ud_xrc' is a
  system library, declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
  build/generators/wxwidgets-Target-debug.cmake:24 (conan_package_library_targets)
  build/generators/wxwidgetsTargets.cmake:26 (include)
  build/generators/wxwidgets-config.cmake:16 (include)
  build/find_package_include.cmake:6 (find_package)
  cmake-proxies/cmake-modules/AudacityDependencies.cmake:224 (include)
  CMakeLists.txt:578 (include)

### Logs

[build.zip](https://github.com/conan-io/conan/files/13191460/build.zip)

**Comment by memsharded** [comment]
Hi @i-lina 

Thanks for your report.
I think what we could be seeing here is more a limitation of the ``wxwidgets`` recipe in ConanCenter that a bug in Conan itself.
The issue could be that the ``wxwidges`` recipe is not prepared (or maybe the library itself) for building in Win-ARM64. ConanCenter builds in x64, and ARM64 in Windows is not that mainstream yet, so it is possible to have some limitations there.

From what I see the package is building:
```
-- Installing: C:/Users/ilina/.conan2/p/b/wxwideeeaae264b854/p/lib/vc_x64_dll/wxmsw31ud_xrc.lib
-- Installing: C:/Users/ilina/.conan2/p/b/wxwideeeaae264b854/p/lib/vc_x64_dll/wxmsw313ud_xrc_vc_x64_custom.dll
```
But at consumption it is complaining about:
```
CMake Error at build/generators/cmakedeps_macros.cmake:67 (message):
  Library 'wxmsw31ud_xrc' not found in package.  If 'wxmsw31ud_xrc' is a
  system library, declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
```
It is very possible that the offender is the ``vc_x64_dll`` in the middle. The recipe might be incorrectly assuming a different folder, maybe ``vc_arm_dll``, but it is not the case.
If it is a recipe issue, it should be checked against the recipe. This doesn't look a recipe from ConanCenter, because it has the ``@audacity/stable`` user/channel. Do you know where are these recipes?

**Comment by i-lina** [comment]
Thanks @memsharded ,
I also came to the same conclusion. The audacity recipe for wxwidgets seems to be coming from 
https://artifactory.audacityteam.org/ui/repos/tree/General/audacity-recipes-conan2%2Faudacity%2Fwxwidgets%2F3.1.3.4-audacity

I am looking to setup a local repository with a fix in the recipe such that the `x64` gets added in the middle. However, after initializing the conan 2.0.13 server, when I try to access the server, the access returned a 404. I am looking at local firewall settings to see why the :9300 port is not reachable. If that works, then I could try a local recipe for audacity to pull from.

Any alternate/easier ideas?

**Comment by i-lina** [comment]
I figured out the wxWidgets recipe pulled in for audacity needed to setup the PLATFORM_ARCH correctly. Thanks for the help. This can be closed.

**Comment by memsharded** [comment]
Thanks for following up @i-lina ! Happy that you found the solution.
