### ISSUE TITLE
conanfile.txt is present in root dir and in subfolder

### ISSUE THREAD

**Issue by laxmij-cmd** [conan-io/conan#15032]
### What is your question?

I have a requirement where conanfile.txt needs to be present in root and subfolder as shown below:

| CMakeLists.txt
| conanfile.txt
| abc  ---- it is a subfolder
   |  CMakeLists.txt
   |  conanfile.txt

To install required libs mentioned in both the conanfile.txt, currently I do following:

conan install .
conan install ./abc/conanfile.txt

Question : 1.  Is there a way that using single "conan install" command installs libs from both the conanfile.txt?
2.  I would be using conan from CMake, so it would be helpful to know if this is doable in conan from CMake also?

Best Regards
Laxmi

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @laxmij-cmd 

Thanks for your question:

> Question : 1. Is there a way that using single "conan install" command installs libs from both the conanfile.txt?

No, it is not possible, you need 2 ``conan install`` commands.

Note that if you are building a single project with sub-project, this could be a problematic setup. If the versions in the ``conanfile.txt`` or the transitive dependencies versions do not match, you can easily have incompatibilities that Conan will not be able to detect, because they are not part of the same dependency graph (each ``conan install`` computes a different dependency graph), and you will only hit at build time, or worse, at runtime.

If the subfolder is a subproject of something bigger, it is recommended to use just 1 ``conanfile`` for all the dependencies. As Conan will be generating different ``dep-config.cmake``, each subproject can perfectly do "include only what you use" and do the ``find_package(mydep)`` of its own dependencies, but not all. 

> 2. I would be using conan from CMake, so it would be helpful to know if this is doable in conan from CMake also?

Not, the ``cmake-conan`` integration also assumes 1 single ``conanfile``. The above also applies, having more than one for the same project can be very problematic.

**Comment by laxmij-cmd** [comment]
Thanks for the prompt response!
