### ISSUE TITLE
[question] Recommended way to get Git information from a package

### ISSUE THREAD

**Issue by aander80** [conan-io/conan#15035]
### What is your question?

Hello,

Is there a recommended/suggested way to define and retrieve Git information for a package, i.e. where the sources come from (URL, repo name, revision, branch/tag etc.)? Preferably something that works in conan 1 and 2 but if it's only valid in conan 2 that's fine.

For my use-case, you can assume that the sources and the conanfile are located in the same repo.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aander80 

Thanks for your question. I think you might be interested in this example in the docs? https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html

Please have a look and let me know. Most of it should work both in Conan 1 and Conan 2.

**Comment by aander80** [comment]
I am not quite sure how to use that information. Perhaps I was a bit unclear. What I am after is a way for a consumer to find out Git information about how a conan package was created. Let's say I have a `lib` and an `app` package. When building `app`, I want to know which Git revision and remote was used to build `lib`. Is there a recommended way to pass this information from `lib` to `app`, e.g. via `package_info()`? This could also be useful for pure consumer conanfiles, if we e.g. want to get the Git information for a complete build graph.

**Comment by memsharded** [comment]
I think the link above can help. Let me try to clarify:

- The source information must be captured at ``export`` time, and that is what the above link is showing. The ``export()`` method can capture that information and should put it in the ``conandata.yml`` file. Because the information has to be stored somewhere. That information might be used or not in the ``source()`` method, but it has to be stored explicitly if you want it.
- There is no need to explicitly pass that information to consumers. Consumers can directly read it via the ``self.dependencies`` and the ``conan_data`` interface. You can do something like this in a consumer:
```python
def generate(self):
      for req, dep in self.dependencies.host.items():
           data = dep.conan_data
           # data is the conandata.yml in memory, you can read information from it
```
Just a few tips:
- The dependencies information is read-only. It shouldn't be modified
- You don't need to put that code in recipes, for example to capture information in of depedencies and creating a file like a report, it can be automated with ``deployers`` and applied to every ``conan install`` for example

Please let me know if this clarifies the issue.

**Comment by aander80** [comment]
This helps a lot, thank you! I was under the impression that conan_data was not supposed to be used by consumers, not sure why really :) But now I know, thank you!

**Comment by memsharded** [comment]
``conandata`` is intended to be relevant information of a package, kind of the "parametrization" of a package. Most times it will not be necessary for consumers to know it, but gathering all information from dependencies is a valid use case, and gathering information from ``conandata`` (besides ``cpp_info``, etc), is valid.

Thanks for the feedback!
