### ISSUE TITLE
[question] Problem understanding a dependency in conancenter

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#15040]
### What is your question?

For a while now, I try to get a new version of _mold_ into conancenter (see PR conan-io/conan-center-index#19152). The problem is, that one dependency seems to be missing. The package requires _onetbb/2021.3.0_, which in turn requires _hwloc/2.9.3_. But the _mold_ build cannot find the correct _onetbb_ package it's looking for (i.e. the one depending on exactly _hwloc/2.9.3_, see below for details).

Weirdly, the existing prebuilt _onetbb_ package on conancenter requires _hwloc/2.9.Z_, which conflicts with the following section in the documentation if I understand it correctly:

> **Embed mode**: When an application or a shared library depends on a header-only or a static-library, the dependencies binaries are copied or partially copied (depending on the linker) in the consumer binary. Also when a static library depends on a header-only library, it is considered that there will be embedding in the consumer binary of such headers, as they will also contain the implementation, it is impossible that they are a pure interface.

Unfortunately, nobody over there seems to know what's going on. Maybe somebody here can explain to me what's the problem and how to solve it?

This is the existing _onetbb_ packages on conancenter:
```
fbd41063c30b49345892a94c8747c6efed28b489
  info
    settings
      arch: x86_64
      build_type: Release
      compiler: gcc
      compiler.cppstd: 17
      compiler.libcxx: libstdc++11
      compiler.version: 11
      os: Linux
    options
      shared: True
      tbbbind: True
      tbbmalloc: True
      tbbproxy: True
    requires
      hwloc/2.9.Z
```

But this is the dependency, the _mold_ build expects:
```
onetbb/2021.3.0: WARN: Can't find a 'onetbb/2021.3.0' package binary 'd7a9f73b4f7a501a35ebea3234d4801bf5740350' for the configuration:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
shared=True
tbbbind=True
tbbmalloc=True
tbbproxy=True
[requires]
hwloc/2.9.3#30511a65bbe6044dab2139ab73cbbe2c:f651771e3392d8c689d4fdd4b39be363dfe184d3
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by SpaceIm** [comment]
I guess because `onetbb` shared option is True by default, therefore the "header-only branch" of recipes depending on `onetbb` drags a dependency graph where onetbb is shared, and its dependencies static, leading to a full package mode of hwloc in this specific onetbb package. So if hwloc recipe is updated, it invalidates current package id of this specific flavor of onetbb package available in conancenter, and conancenter should regenerate these onetbb packages, which is not done automatically AFAIK. It's a flaw of current v2 pipeline implementation.

Another explanation is that onetbb package with default options (shared True) and dependencies default option (shared False) is never built by c3i in v2 pipeline since it enforces either all shared or all static.
But header-only recipes are built in v2 pipeline with default options of dependencies.
Therefore it would be another flaw of v2 pipeline, where recipes with shared=True AND having dependencies with shared=False by default break soon or later c3i for downstream recipes.

Honeslty, since onetbb raises anyway for shared=False with versions >= 2021.6.0, and highly discourages shared=False anyway for all versions, shared option should be removed to avoid all this mess.

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/20897 proposes to remove this shared option in onetbb recipe.

**Comment by AbrilRBS** [comment]
Closing as solved, the PRs have been merged for a while now, thanks to both! :)
