### ISSUE TITLE
[question] Conan packages 1.x <-> 2.x compatibility

### ISSUE THREAD

**Issue by Tricksam** [conan-io/conan#15057]
### What is your question?

Hi,
we are working doing the switch from Conan 1.x to Conan 2.x. As we have a lot of packages created and in use, I would like to clarify the back and forth compatibility of the packages consumed by the opposite Conan version.
The comment in the documentation leaves some room for interpretation, maybe you can specify it a little sharper for us.

_Also, a lot of effort has been made to backport necessary things to Conan 1.X to make the upgrade easier: Recipes using latest 1.X integrations will be compatible with Conan 2.0, and binaries for both versions will not collide and be able to live in the same server repositories._

Internally we fixed the Conan version to 1.51 means all packages should be created with the Conan API of that version. A quick try of consuming a package of this version with Conan v2.x failed.

Can you state since which version the compatibility should work seamlessly? 

many Thanks, Sam

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Tricksam 

Thanks for your question.
I'll try to clarify it:

> Also, a lot of effort has been made to backport necessary things to Conan 1.X to make the upgrade easier: Recipes using latest 1.X integrations will be compatible with Conan 2.0, and binaries for both versions will not collide and be able to live in the same server repositories.

The important bit is the "Using the latest 1.X integrations".
As per our stability policy, it is not possible to remove legacy integrations even in the latest Conan 1.61, the legacy ``cmake``, ``cmake_find_package`` generators will still be working. Using the legacy environment management (``env_info`` instead of ``buildenv_info`` and ``runenv_info``) will still be working. But those integrations have been removed in Conan 2.0.

So it means that recipes in a Conan version modern enough (it is possible that you might need to go to 1.61) to contain the necessary backports, that use the new integrations, will be able to build correctly in Conan 2.0 too. There is no guarantee that using just a specific Conan version will enforce the recipes to be compatible with 2.0, because that would be breaking in the 1.X release series. 

There is a summary of the things that need to be modernized while in 1.X to be ready for 2.0 in https://docs.conan.io/1/conan_v2.html

**Comment by memsharded** [comment]
Closing as responded, but please don't hesitate to re-open or create new tickets for any further questions. Thanks for your feedback.
