### ISSUE TITLE
[question] How to handle Visual Studio Runtime Setting

### ISSUE THREAD

**Issue by ottmar-zittlau** [conan-io/conan#15062]
### What is your question?

Hi!

I'm trying to create a simple local protobuf package that only provides static libs.
On Windows, I have some problems compiling it together with the abseil dependency - and the reason is the MSVC runtime setting.

My default settings look like this:
```
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
compiler.runtime=MD
[options]
[conf]
[build_requires]
[env]
```

My abseil-recipe looks like this:
```
from conans import ConanFile, tools
from conan.tools.cmake import CMake, CMakeToolchain
import os


class Package(ConanFile):
    name = "absl"
    version = "20230802.1"
    url = "https://github.com/abseil/abseil-cpp.git"

    homepage = "https://github.com/abseil/abseil-cpp"
    description = "Abseil is an open-source collection of C++ code (compliant to C++14) designed to augment the C++ standard library."
    topics = (name,)
    license = ("Custom")

    settings = "os", "arch", "compiler", "build_type"

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.builddirs.append(os.path.join("lib", "cmake", "absl"))
   
    def source(self):
        git = tools.Git()
        git.clone(self.url, "20230802.1", shallow=True)

    def generate(self):
        tc = CMakeToolchain(self)
        tc.cache_variables["CMAKE_POSITION_INDEPENDENT_CODE"] = "ON"
        tc.cache_variables["ABSL_PROPAGATE_CXX_STD"] = "ON" 
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        cmake.install()

    def package(self):
        self.copy("*", dst="", src="install")
```
My protobuf recipe looks like this:
```
from conans import ConanFile, tools
from conan.tools.cmake import CMake, CMakeToolchain

import os

class Package(ConanFile):
    name = "protobuf"
    version = "25.0"
    url = "https://github.com/protocolbuffers/protobuf.git"

    homepage = "https://developers.google.com/protocol-buffers/"
    description = "Protocol buffers are a language-neutral, platform-neutral extensible mechanism for serializing structured data."
    topics = (name, "protocol", "buffers", "message")
    license = ("Custom")

    requires = "absl/20230802.1@test/local"

    settings = "os", "arch", "compiler", "build_type"

    def package_info(self):
        self.cpp_info.set_property("cmake_find_mode", "none")
        self.cpp_info.builddirs.append(os.path.join("lib", "cmake", "utf8_range"))

        if self.settings.compiler == "Visual Studio":
            self.cpp_info.builddirs.append(os.path.join("cmake"))
        else:
            self.cpp_info.builddirs.append(os.path.join("lib", "cmake", "protobuf"))
            
    def source(self):
        git = tools.Git()
        git.clone(self.url, "v25.0", shallow=True)
        apply_conandata_patches(self)

    def generate(self):
        tc = CMakeToolchain(self)
        tc.cache_variables["protobuf_ABSL_PROVIDER"] = "package"
        tc.cache_variables["protobuf_BUILD_TESTS"] = "OFF"
        tc.cache_variables["protobuf_BUILD_SHARED_LIBS"] = "OFF"
        tc.cache_variables["CMAKE_POSITION_INDEPENDENT_CODE"] = "ON"
        tc.generate()


    def build(self):          
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        cmake.install()

    def package(self):
        self.copy("*", dst="", src="install")
        self.copy("*", dst="", src="python/build")
```

When building the package (by running `conan create`) I encounter a lot of linking errors of the type:
`.... value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in main.obj ....`

If I set the runtime in my profile to MT
`conan profile update "settings.compiler.runtime=MT" default`
and repeat the whole build process everything runs fine.

However, if consumers of my packages have MD set in their profiles, they won't find my pre-built packages (that have been built with MT) and I want to enforce the usage of pre-built packages in certain situations (in particular within CI-builds).

Is there a way to create these packages independent of the runtime setting?
I tried to use
```
    def package_id(self):
        if self.settings.compiler == "Visual Studio":
            del self.settings.compiler.runtime
            self.info.settings.compiler.runtime = "MT/MTd"
```
in my abseil receipe, but that didn't help.

Thanks and best regards,
oz

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ottmar-zittlau 

Thanks for your question.

First, a quick question: which Conan version are you using? This is very important. If you are starting with Conan, it is strongly recommended to use Conan 2.0.

In case you are using Conan 1.X, a couple of quick recommendations:
- ``os_build=Windows`` is the very legacy cross-build support. The recommended way, even in Conan 1.X is not to use ``os_build`` and ``arch_build`` and use the 2 profiles approach
- Avoid ``if self.settings.compiler == "Visual Studio":`` and use ``is_msvc()`` helper, because it is forward compatible with Conan 2.0
- Use ``copy()`` instead of ``self.copy()`` also, to be compatible with 2.0
- Try to avoid ``from conans`` completely, you should only be importing ``from conan``

It is very possible that the build scripts of some of those libraries is hardcoding the runtime, and this is the reason that only when defining ``conan profile update "settings.compiler.runtime=MT" default`` to link static runtime. Many recipes in ConanCenter contains patches that fix these things. It would be recommended to start from those recipes and adapt or simplify if necessary better than starting from scratch, there is ton of knowledge already integrated in ``conan-center-index`` recipes.

It is also possible that if you are not using CMakeDeps generated .cmake files, and deciding to use the .cmake inside the package and enabling that such files propagate things (``tc.cache_variables["ABSL_PROPAGATE_CXX_STD"] = "ON"``) then those scripts might be deciding to define things a bit beyond their responsibility. Also, looking towards Conan 2.0, it is not intended that packages propagate the ``cppstd`` to their consumers, because ``cppstd`` is a Conan input in the profiles. Recipes can raise a ``ConanInvalidConfiguration`` error in ``validate()`` if the ``cppstd`` defined by users do not satisfy that package required cppstd, but propagating cppstd from dependencies to consumers has some side issues that is better to avoid.

In order to validate if Conan client (and not possible issues in recipes) would be failing to manage something, it is very recommended to try things with "simple" recipes like the ones created with ``conan new hello/0.1 -m=cmake_lib``.

**Comment by ottmar-zittlau** [comment]
Hi @memsharded,

thanks a lot for your detailed and quick reply.
I'm using conan 1.61 due to legacy reasons - but your compatibility recommendations are very valuable, because I wanted to write the recipes as close to 2.0 as possible.

I checked the protobuf recipe in the conan center (https://github.com/conan-io/conan-center-index/blob/master/recipes/protobuf/all/conanfile.py) and found another flag called `protobuf_MSVC_STATIC_RUNTIME`. Setting this to `OFF` solved my problem.

The two-profile approach you mentioned is only necessary for cross-building correct? I don't do that - I always build on the same platform on which the package is later used (windows and linux).
I haven't created the default profile myself - it's the one auto-generated by conan. Is there any benefit in removing the `*_build` options? Or can I just keep it like that?

Thanks again and best regards
oz

**Comment by memsharded** [comment]
>  found another flag called protobuf_MSVC_STATIC_RUNTIME. Setting this to OFF solved my problem.

Great! Happy you found the issue

> The two-profile approach you mentioned is only necessary for cross-building correct? I don't do that - I always build on the same platform on which the package is later used (windows and linux).

Not only for cross-building it is very important also if you are using ``tool_requires`` (or ``build_requires``, it is equivalent), as they behave differently when using the 2 profiles. Only if you are not using any ``tool_requires``, it would be the same.

> I haven't created the default profile myself - it's the one auto-generated by conan. Is there any benefit in removing the *_build options? Or can I just keep it like that?

It is fine, not necessary to remove them, if recipes don't use them like ``self.settings.os_build`` or ``settings = ..., "os_build"`` and if using the modern build system integrations, and using the 2 profiles, it shouldn't be an issue, you can use that profile without issues.
