### ISSUE TITLE
Make gcc 6.4 default one for 6.X

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#1506]
Right now we have 6.3. Should we change?
- CI scripts for ``conan new``
- conan-package-tools?
- define policy for supported packages in conan-center?

**Comment by GamePad64** [comment]
Yes, why not? The current policy (latest from every major version) seems reasonable.

**Comment by memsharded** [comment]
+1

**Comment by lasote** [comment]
For conan-package-tools first we need a docker image ready with 6.4

**Comment by Croydon** [comment]
I believe this is done (or can be done easily now)

**Comment by lasote** [comment]
I've pushed an image for gcc 6.4 to  https://github.com/conan-io/conan-docker-tools and dockerhub.
I also update the gcc 6 image to point to the 6.4
In conan it is not needed to update anything, because the CI scripts are already using "6", in pacakge tools it will use the version you specify, so "6" => "6.4"
We can close this issue
