### ISSUE TITLE
[question] Handle data package

### ISSUE THREAD

**Issue by mikirothman** [conan-io/conan#15064]
### What is your question?

Hi ! 

I'm looking for a solution that will support our design regarding our packaging and propagation of package information.
we use in our projects many different types of packages, in many platforms. most of them are shared libs, some of them are CMake modules packages and application packages for build tools.
we are looking for a solution for 2 types of packages:
1. data/assets packages - packages that doesn't hold any libraries, just data for the executable, loaded via Environment variable, so we need to add an information to runenv_info, how should this package look like ? package_type ? 
2. runtime tools package - some applications for debug purposes or emulators, so we only need them for the runenv_info in the path, and to not propogate to consumers ?  what is the correct way to handle this kind of package ?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mikirothman 

Thanks for your question

> data/assets packages - packages that doesn't hold any libraries, just data for the executable, loaded via Environment variable, so we need to add an information to runenv_info, how should this package look like ? package_type ?

I think for this package type:
- It should be a ``requires``, and not a ``tool_requires`` as it is intended to run in the "host" context
- It doesn't propagate any ``includedirs`` or anything like that, I'd recommend to explicit it in the ``package_info()`` method with ``self.cpp_info.includedirs = []`` etc
- You can probably leave ``package_type`` as undefined (internally it will be "unknown"). This will use ``semver_mode``, which means that changes in these packages won't require re-building anything that consumes it unless the major version changes.

> runtime tools package - some applications for debug purposes or emulators, so we only need them for the runenv_info in the path, and to not propogate to consumers ? what is the correct way to handle this kind of package ?

I'd say these are ``tool_requires``? But the only thing is that these wouldn't set the ``runenv_info``, but the ``buildenv_info``, because the running context is still the "build" one. Let's put an example, to see if I understood correctly: If I am cross-building an Android library from my Windows machine to Android, I can use ``android-ndk`` as a ``tool_requires``, and such ``android-ndk`` will be binaries that run in Windows. If I need to debug or emulate, I still need the ``android-ndk`` for my Windows machine, in the Windows "build" context. This is ``buildenv_info``. If I deploy the real application into an Android machine, my emulator won't even run there, so it is not ``runenv_info``. The idea of ``runenv_info`` is that it contains only "host" code for production.
