### ISSUE TITLE
[question] Is there a reason why a conan 2.0.1 package would disturb a conan 1.54 package with the same name/version?

### ISSUE THREAD

**Issue by eyal-ronel** [conan-io/conan#15063]
### What is your question?

Hi,
We have a project that uses conan 1 to store packages in Artifactory using `conan export-pkg`.
I'm experimenting with conan 2 and uploaded one of those packages via `export-pkg` using conan 2.

Once I did that, while the package in conan 2 responds correctly to conan install,    
in conan 1.54 the same package only goes half way: Its metadata is downloaded to conan cache but the package contents do not, resulting in several errors of "missing binary" and "missing prebuilt package". conan search discovers the package in local cache, but the package is corrupted. Deleting the conan 2.0 package from Artifactory makes the conan 1 package install correctly again.

What could I've done wrong to cause such behavior?
Thanks.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @eyal-ronel 

Thanks for your question.
Package binaries for both 1.X and 2.0 can perfectly co-exist without collision both in remote repos and in the Conan cache. Conan 1.X ``conan search`` will only list binaries created with Conan 1.X and Conan 2.0 ``conan list`` will only list binaries created with Conan 2.0.

A different issue, and I think this is what you are seeing, is that when a new recipe revision is created it requires building new binaries for it. This is independent of Conan 2.0, whenever you do a modification of a recipe or source code of a package, it will result in a new recipe revision, and every new recipe revision requires its own binaries. Maybe you are doing changes to the recipe to update something to make it compatible with Conan 2.0 and not building the binaries for Conan 1.X? When developing packages for both 1.X and 2.0, every new recipe revision should be building their binaries for both 1.X and 2.0.

Please let me know if this clarifies the issue.

**Comment by memsharded** [comment]
Also, please take into account that only last patch of each minor is recommended. In this case, Conan 2.0.13 should be used, it contains tons of fixes that might still bite you in Conan 2.0.1, not to say also very important improvements. Check https://docs.conan.io/2/introduction.html#stable recommendations about using the last patch for Conan.

**Comment by eyal-ronel** [comment]
It seems that the most recent package that I upload takes precedent.   
If I upload using conan2 and afterwards upload using conan1, then I can conan install only using conan 1 and conan 2 fails.   
If I do it in the opposite order, then conan 2 succeeds and conan 1 fails.

To iterate how I created these packages, in the same binaries folder (a folder with /include and /lib) I created two recipes: conanfile1.py (from conans import ConanFile etc,) and conanfile2.py (from conan import ConanFile etc.)
I `export-pkg` and `upload` for each version of conan. Then I `remove` the local package and attempt to install.
So the binaries are the same.

Do you have other ideas what went wrong?
Thanks again.

**Comment by memsharded** [comment]
> It seems that the most recent package that I upload takes precedent.
If I upload using conan2 and afterwards upload using conan1, then I can conan install only using conan 1 and conan 2 fails.
If I do it in the opposite order, then conan 2 succeeds and conan 1 fails.

Could you please share the logs of those flows? I really think that you are creating different recipe revisions in both flows. There might be something that is different. It is necessary that both flows results in the same recipe revision when you ``conan create`` and ``conan upload`` them. Otherwise, it is true, the last revision uploaded is the one taking precedence and the one that is downloaded by default. As you created

> To iterate how I created these packages, in the same binaries folder (a folder with /include and /lib) I created two recipes: conanfile1.py (from conans import ConanFile etc,) and conanfile2.py (from conan import ConanFile etc.)

Ok, that explains the issue, disregard the above. The recipe should be the same, otherwise, yes, it will be creating different recipe revisions, and only the latest one has precedence. There is a common syntax that works both in Conan 1.X and Conan 2.0, you can perfectly (and should) use ``from conan`` also in Conan 1.X, that is the way that compatibility in Conan 1.X and Conan 2.0 is achieved. If you want to have separate recipes you would need to also have different remote repos for 1.X and 2.0. That is also possible if you want to do it that way, but in general it is recommended to use exactly the same recipe (that produces the same recipe revision) for both Conan 1.X and 2.0. This is what ConanCenter is doing for +1500 recipes.

**Comment by eyal-ronel** [comment]
Yes, that did the trick! Thanks so much for your responsiveness and your patience.

**Comment by memsharded** [comment]
No problem, thanks for the feedback and follow up! 🙂 

Do not hesitate to open new tickets for any further question or issue that you might have. Thanks!
