### ISSUE TITLE
[question] How to set "package_type" attribute dynamically?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#15061]
### What is your question?

I'd like to set `package_type` attribute dynamically in `python_requires` based on the recipe's name. How to do that? Is init() method suitable for that?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your question.

In general conditionality for those things happen in ``configure()`` method because ``init()`` does not get ``settings`` and ``options``, so it is difficult to define conditionals without those values. But if it only depends on the actual package name, maybe the ``init()`` is possible.

In general, I prefer to be explicit and define ``package_type = xxxx`` directly in the derived class not the base class, to be able to understand the behavior of a recipe without having to read the base class code. Having to maintain the "mapping" between package names and their package types in a place different than the package recipe seems a bit too much indirection for something that is just an attribute value definition. But besides this possible design discussion, I think from the behavior point of view, ``init()`` could work without issues.

**Comment by db4** [comment]
@memsharded Thanks a lot for the answer. At the time of Conan 1.x, it was a common mistake to store any state in Conanfile object. What about now? Can I write
```python
    def init(self):
        ...
        self.package_type = "shared-library"
```
or modifying the class itself via
```python
    def init(self):
        ...
        type(self).package_type = "shared-library"
```
is more appropriate?

**Comment by memsharded** [comment]
> At the time of Conan 1.x, it was a common mistake to store any state in Conanfile object.

It is still not recommended to store user state and temporary information in the object to try to pass it around to the different methods, like trying to reuse something between the build() and the package() method.

But for Conan built-in attributes it is fine to assign them a value in the designated init() or configure() methods (not in others). So ``self.package_type = xxx`` sounds good.
