### ISSUE TITLE
[question] How to enable sanitizers

### ISSUE THREAD

**Issue by skhaz** [conan-io/conan#15075]
### What is your question?

In version 1 of Conan, there was documentation on how to enable sanitizers like the address sanitizer.

My question is: How do I do this in version **2**? There is no mention of it in the documentation.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @skhaz 

Thanks for your question.
In reality Conan 1.X docs only explains how to extend the ``settings.yml`` to model the sanitizers. But there are no built-in model or features in Conan 1.X to manage sanitizers. So basically the same docs would apply to Conan 2.0 as well.

We haven't documented yet it in Conan 2.0 because we are trying to have a more thorough approach in 2.0, with full working examples and more tutorial-like documentation, so it would take some more time to do it.
