### ISSUE TITLE
[bug] validate_build does not raise exceptions during install, conan 1.X

### ISSUE THREAD

**Issue by yarcod** [conan-io/conan#15083]
### Environment details

* Operating System+version: Linux, (K)ubuntu 23.10
* Compiler+version: gcc-13
* Conan version: 1.61.0
* Python version: 3.11.6

### Steps to reproduce

Minimal example to get error:

```python
from conans import ConanFile, tools
from conan.errors import ConanInvalidConfiguration

class CrashConan(ConanFile):
    name = "crash"
    version = "0.1.0"
    settings = "os", "compiler", "build_type", "arch"
    description = "<Description of Crash here>"
    url = "None"
    license = "None"
    author = "None"
    topics = None

    def validate_build(self):
        raise ConanInvalidConfiguration("some message")

    def package(self):
        self.copy("*")

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
```

Running the above with `conan install .` will not `raise` any exception, but will correctly do so when ran with `conan create .`

**Comment by memsharded** [comment]
Hi @yarcod 

Thanks for reporting.
This is a known issue. It is expected that it doesn't raise an error in conan 1.X. We had to take this decision, because it was breaking behavior at some point, and there were users relying on being able to run ``conan install`` without getting an error there, and only ``conan create`` (when the package is actually "built", recall that ``conan install`` is only about dependencies in Conan 1.X, not the current package build) would raise an error.

The behavior has been changed in Conan 2.0, and it will raise an error for ``conan install`` too.

**Comment by yarcod** [comment]
That explains it -- thanks -- and I think it sounds reasonable that the behaviour was changed for Conan 2.
Has there been any other good/recommended work-arounds for this other than explicitly calling `validate_build` from the `generate` method?

**Comment by memsharded** [comment]
> Has there been any other good/recommended work-arounds for this other than explicitly calling validate_build from the generate method?

No elegant workaround (putting it in the ``generate()`` will probably have issues, specially when trying to upgrade to Conan 2.0), so probably not very recommended.

As the process will fail later when the package is actually created ``conan create``, it is not a critical thing, it can be inconvenient for developers not "failing fast" for an invalid configuration, but the invalid will be catched later at create time.

I'd also strongly encourage to start the migration to be ready with Conan 2.0, like ``self.copy`` => ``copy(self, )``, avoid the ``from conans`` and use only ``from conan``, etc.
