### ISSUE TITLE
[feature] Adding a new run_tests conf

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#15086]
### What is your suggestion?

Hello,

I have a cmake package that requires to prepare a specific environment to run the tests

I prefer always building the tests, considering that they are part of the project. However, I don’t necessarily want to prepare their environment, nor to run them every time `tools.build:skip_tests` is set to `True`

Would it be possible to add a new config variable `tools.whatever.run_tests` to be able to choose when to do so?

Another solution could be to add a new method to the `CMake` helper called `run_tests`

I think many Conan users could benefit from it. Thanks in advance

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your suggestion

> Another solution could be to add a new method to the CMake helper called run_tests

The ``cmake.test()`` helper is doing this. It is not building the tests, the tests are still being built at ``cmake.build()``. That helper is for running the tests.

> I prefer always building the tests, considering that they are part of the project. However, I don’t necessarily want to prepare their environment, nor to run them every time tools.build:skip_tests is set to True

This seems a bit too specific, it is not expected that many users will want to build the tests if they are not executing the tests later, because most of the times, the tests are not packaged either.

You can always use your own user confs, are you aware of that? So you could easily do something like:
```python
def build(self):
     cmake = CMake(self)
     ...
     if self.conf.get("user.myorg:run_tests", check_type=bool):
         cmake.test()
```

**Comment by Todiq** [comment]
Hello,

I wasn't aware of the custom user confs, thanks for the info. It suits my needs. Thank you very much.

**Comment by memsharded** [comment]
Thanks for the feedback!
