### ISSUE TITLE
[bug] Cannot run conan.tools.files.get in export()

### ISSUE THREAD

**Issue by aander80** [conan-io/conan#15090]
### Environment details

* Operating System+version: WSL Ubuntu 22.04 LTS
* Compiler+version: N/A
* Conan version: 2.0.13
* Python version: 3.10.12

### Steps to reproduce

Hello,

When trying to download a package of Python source code to be used as `python_requires`, I get an error message when using `get` or `download` from `conan.tools.files` inside `export()`: `AttributeError: 'ConanRecipe' object has no attribute 'conf'`.

To reproduce, create the following example `conanfile.py` trying to create a `python-require` of Sphinx:

``` python
from conan import ConanFile
from conan.tools.files import get


class ConanRecipe(ConanFile):
    name = "sphinx"
    version = "7.2.6"
    package_type = "python-require"

    def export(self):
        get(
            self,
            "https://github.com/sphinx-doc/sphinx/archive/refs/tags/v7.2.6.tar.gz",
            destination=self.export_folder,
        )
```

When running `conan create /path/to/conanfile.py`, the error message `AttributeError: 'ConanRecipe' object has no attribute 'conf'` is printed. This is because the function `download` expected the conanfile to have config set in this context, which it has not.

What is your suggestion in this case? Is this a bug to be resolved, or is this working as intended? Should tools not be used in this way in `export()`?

The use-case for us is to be able to use shared Python code from third-parties inside the Conan recipe in contexts before "actual" packages are available to us.

### Logs

```
❯ conan create conanfile.py

======== Exporting recipe to the cache ========
sphinx/7.2.6: Exporting package recipe: /home/<user>/tmp/conanfile.py
sphinx/7.2.6: Calling export()
ERROR: sphinx/7.2.6: Error in export() method, line 11
        get(
        AttributeError: 'ConanRecipe' object has no attribute 'conf'
```

**Comment by memsharded** [comment]
Hi @aander80 

Thanks for your report.
I think this wouldn't be a bug, but expected behavior.
The ``export()`` method cannot download things, the ``export()`` method is limited to copying files from your user folders to the cache "recipe" folder, and then it doesn't receive ``conf`` information, this is why you are seeing it failing (we could try to improve the error message to something more evident or explicit)

If you want to download something, this should be done in the ``source()`` method. If you are concerned about doing a copy of the internet downloaded file, you might want to use the automatic backup feature (have a look at https://blog.conan.io/2023/10/03/backup-sources-feature.html)

Please let me know if this clarifies the behavior, thanks!

**Comment by aander80** [comment]
Files in `source_folder` is not available to us when consuming via `python_requires`, if we want to run code in a consuming recipe in `init()`, `set_name()`, `set_version()` etc., is it?

**Comment by memsharded** [comment]
Maybe the issue is the usage of ``python_requires`` instead of ``tool_requires``?

- ``python_requires`` is intended mostly for your own python snippets, things that you are repeating among recipes. In this regard ``python_requires`` is not prepared to "package" external source code, only ``exports`` your own source code in the repo of the ``python_requires``.
- You can perfectly have a tool that is written in python in a ``tool_requires``, if you want to use it as a tool at build time, it is totally doable. This is for example what the ConanCenter ``meson`` package is doing it if you want to have a look.

**Comment by aander80** [comment]
I think I may be a bit unclear on my use-case.

I want to share code which uses a third-party Python package, and use that inside early conan callback methods before any `tool_requires` is available to us.

As an example, let's assume we have rules for setting name and version depending on Git repo remote and tags, and we use a third-party Python package for this. In this case, we want to use the code inside `set_name` and `set_version` in the consumer, hence `tool_requires` would not work for us. Our code can easily be distributed via `python_requires`, but then there is the question on how to handle the third-party Python package. We want to avoid consumers having to install any third-party Python packages; installing Conan and our config should suffice and anything else should be ideally handled via Conan recipes. Hence, my idea was to "package" the Python library together with our code in the `export_folder` so that we can easily use it; it is fine in our use-cases to keep the library isolated from the consumer and only call it from within the `python-require` `conanfile.py`.

What is your suggestion for our problem? We can use `requests.get` directly to download the package directly (since this is available to us as a Python package dependency via Conan) and put in the `export_folder` without using `conan.tools.files` (I just thought it would be neater to use the helpers 😄) but perhaps I am approaching this problem incorrectly?

**Comment by aander80** [comment]
> (have a look at https://blog.conan.io/2023/10/03/backup-sources-feature.html)

By the way, thanks for mentioning this! 😄

**Comment by memsharded** [comment]
Ok, I understand better now.

It is true that ``python-requires``, due to its nature, do not implement the use case of fetching sources from elsewhere and integrating them into the ``python-requires`` as part of the recipe. This is not doable at the moment.

As possible solutions you could:
- Create a repo for the ``python_requires`` recipe, add the source code as submodule
- Implement a custom flow with ``conan source`` to do the download to the recipe folder, then ``conan export`` that will export the local copy
- Workaround the limitation with ``request.get`` The possible issues with this is that this will not inject any of the conan configuration, as it is not defined there yet. But if it works for you, might be doable.

We could have a look and consider passing the ``conf``, but the problem that it has is that it can cause a lot of confusion, when a user is doing a ``conan create``, that does an "export" as a first stage, passing some profiles with some configurations, and then the ``export()`` method will not see the configurations of the profiles, only the global one (which does not include yet the command line).

**Comment by aander80** [comment]
Alright, that explains the reasons for not changing `get` and `download`. Thank you for the possible solutions, I will see what suits us the best!
