### ISSUE TITLE
[bug] !!!! Release URLs don't specify architecture.

### ISSUE THREAD

**Issue by jacobfriedman** [conan-io/conan#15120]
### Environment details

[Edited]...

* Operating System+version: Ubuntu 20.04 arm64v8
* Compiler+version:  N/a
* Conan version: 2.0.13
* Python version: N/A

Should there be a conanfile to build conan?

### Steps to reproduce

1. Boot up your favourite arm64 linux 20.04 docker image
2. Go to releases page
3. Download the [debian package for Linux/64](https://github.com/conan-io/conan/releases/download/2.0.13/conan-ubuntu-64.deb)
4. Try to install the .deb package

### Logs

 > [base  8/17] RUN dpkg -i conan-ubuntu-64.deb:
#12 2.001 dpkg: error processing archive conan-ubuntu-64.deb (--install):
#12 2.001  package architecture (amd64) does not match system (arm64)
#12 2.007 Errors were encountered while processing:
#12 2.007  conan-ubuntu-64.deb

**Comment by memsharded** [comment]
Hi @jacobfriedman 

Thanks for your report.
The truth is that we have the .deb installer creator there since like, I don't know 7 years, before that arm was that mainstream.

Our naming for releases binaries is:
- conan-linux-64.tar.gz
- conan-macos-arm64.tar.gz
- conan-ubuntu-64.deb

The "64" alone represents intel/amd 64, if an installer is for arm, it will contain explicitly "arm" in the name.

So this wouldn't be a bug, the ``conan-ubuntu-64.deb`` is correct, but more that you are missing a debian package for arm64, if I understood correctly? Or is there something intrinsically bad in the debian package metadata that should be changed? Should we rename the ``conan-ubuntu-64.deb`` name to something more standard?

**Comment by jacobfriedman** [comment]
Thank you for clarifying. Please use the `uname` standard output for architectures & operating systems:

conan-ubuntu-aarch64 (deb)
conan-ubuntu-x86_64 (deb) 
conan-linux-x86_64 (.tar.gz)
conan-linux-aarch64 (deb)

For non-fat libraries:
conan-darwin-x86_64 (.tar.gz; dylibs)
conan-darwin-aarch64 (.tar.gz; dylibs)

Fat libraries: both links should link to the same file.

Even worse:
conan-darwin (dylib)
conan-macos (dylib) <-- not ideal

**Comment by jcar87** [comment]
Hi @jacobfriedman  - we currently do not publish the .deb package for arm64. We will revisit the file names to adhere to Debian's recommendations (https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html#pkgname), apologies for the confusion.

Conan itself is architecture independent python files, however, some of the dependencies have compiled loadable python modules. The binary packages we provide also contain a minimal cpython interpreter, hence the architecture.

In the meantime, if you'd like to install Conan on an Ubuntu system running aarch64, here are a couple of suggestions:
* install Conan in a Python virtual environment (requires `python3` and `python3-venv` system packages, which are likely to already be installed unless you are on a minimal/core version) Please let me know if you need assistance with this. 
* Install Conan using pipx, which requires the `pipx` package to be installed, e.g.:
```
sudo apt-get install pipx
pipx ensurepath
# (re-enter shell)
pipx install conan
```

If you need to install it at the system level, please let us know.

**Comment by jacobfriedman** [comment]
Thank you for the quick feedback. This impetus was towards getting a bundled (offline) conan install. Ideally, a conan ...conanfile... would make the process easier, since I could pull from my own compiled dependencies. 

It's a chicken-and-egg scenario (something LLVM has yet to completely solve), and I understand conan is based in Python (ironic, since it's a c++ package manager).

I may have to create a pip package and stuff the setup/requirements in a non-gitignored repo, decorating compiled dependencies (if needed) with some kind of python virtualenv conan install, which is not what this is intended to do, but it solves my problem.

**Comment by jcar87** [comment]
Hi @jacobfriedman  - perhaps the instructions in the documentation may be useful:  https://docs.conan.io/2/installation.html#use-a-system-installer-or-create-a-self-contained-executable

You should be able to generate a self-contained bundle that is decoupled from any python installation on the system. This is what we use to generate what goes in the Debian file, but it currently has a limitation of not being able to cross build.

**Comment by jacobfriedman** [comment]
Thank you - I'll try that.

**Comment by SSE4** [comment]
> conan-ubuntu-64.deb

the name on releases page on its own definitely doesn't say much for users. 64 might be x86_64, ARM64, or Sparc, MIPS, RISC-V, PowerPC, Elbrus, LoongArch...

I suggest to use [official](https://wiki.debian.org/SupportedArchitectures) architecture name (hence, `amd64` here) as a part of the filename.

next, it doesn't say for what ubuntu version it was built for (is it trusty or xenial or something else)? as package includes executables, it's pretty important for user to know (because of glibc compatibility).

I think it's worth including ubuntu version and conan version into package name, so released artifact could be named like `conan_2.0.14_trusty_amd64.deb`, which is much more self-descriptive and obvious for users.

> The binary packages we provide also contain a minimal cpython interpreter, hence the architecture.

I personally think it doesn't fully follow [Embedded Copies](https://www.debian.org/doc/debian-policy/ch-source.html#embedded-code-copies) policy (see also [EmbeddedCopies](https://wiki.debian.org/EmbeddedCopies)). instead of including minimal cpython interpreter, conan package should have a reference (dependency) to [python-minimal](https://packages.ubuntu.com/focal/python3-minimal) package.

this way user can benefit from system security updates; NOTE conan binary doesn't update itself via `apt-get update` - e.g. it doesn't contain `/etc/apt/sources.list.d` entry inside the package; so user has to install security updates for conan manually (and try not to forget).

for example, conan debian package includes embedded OpenSSL copy:
```
-rwxr-xr-x root/root   3386208 2023-11-14 20:56 ./opt/conan/_internal/libcrypto.so.1.1
-rwxr-xr-x root/root    690355 2023-11-14 20:56 ./opt/conan/_internal/libssl.so.1.1
```
which is actually 1.1.1l from year 2021:
```
OpenSSL 1.1.1l  24 Aug 2021
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
built on: Thu Mar  2 14:21:46 2023 UTC
platform: linux-x86_64
OPENSSLDIR: "/openssl"
ENGINESDIR: "/openssl/lib/engines-1.1"
```
NOTE that OpenSSL 1.1.1 is already [EOL](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/). and there is no easy way to update this copy. e.g. latest version for 1.1.1 branch is 1.1.1w, while 1.1.1l is a subject for many security issues (including HIGH and CRITICAL [vulnerabilities](https://www.openssl.org/news/openssl-1.1.1-notes.html)). this might introduce some risk for users running conan server. and there is no clear way to upgrade.

even if conan eventually releases needed updates in next version, many users might not want to upgrade to latest 2.x release, so they stuck forever with vulnerable conan server.

**Comment by memsharded** [comment]
Naming of Conan releases has been changed (see https://github.com/conan-io/conan/releases/tag/2.5.0), I think we can close this ticket now. Thanks for the feedback.

**Comment by jacobfriedman** [comment]
Great work, thank you very much!
