### ISSUE TITLE
Change in self.cpp_info.defines does generate new package but does not trigger rebuild of dependent modules

### ISSUE THREAD

**Issue by mschmid** [conan-io/conan#1515]
In order to get my dependency tree of custom modules rebuild with logging, I introduced in the package_info of the logging module a build define via self.cpp_info.defines = ["-DLOG_ENABLED"].
The same define is used by dependent modules also.
This indeed generates a new package hash, but the dependent modules do not get rebuilt.

Is this behavior by intent?
If yes, how can I advice Conan to rebuild the dependent modules from source and use the build define?

**Comment by memsharded** [comment]
I am not sure what you mean. Can you give more details about your setup? From my understanding you have:
- Package "Logging", which defines ``LOG_ENABLED`` to its consumers.
- Package "MyLib" which depends on "Logging"

The package binary hash of "MyLib" does not change because of "Logging" defines some variables or not. It changes when the settings change, the options change, or its requirements change. By default, requirements affect the hash in a semver fashion, ``Logging/1.X`` would be used in the hash, so minor versions do not affect the hash. This can be configured.

It is different for ``build_requires`` which do not affect the hash. 

Also, I guess that you want "MyLib" rebuild when you are installing it, or some other project that depends on it? Like "MyApp" which depends on "MyLib", which depends on "Logging". In that case, you can define that you want "MyLib" built from source specifying ``--build=MyLib``

Please provide more details about your project, and I will try to help. Thanks!

**Comment by mschmid** [comment]
Your understanding is quite correct.
From what I understand right now I have to introduce a setting named "enable_logging" in the package "Logging" and set the build define in this package accordingly, to make the change become visible in the package MyLib and e.g. MyApp.
I will tell you if this worked out for me.

**Comment by memsharded** [comment]
Yes, modeling via configuration is the way to go. I might recommend using ``options`` instead of settings for that use case, seems logging is more an option (can be defaulted), and do not require customizing ``settings.yml``. But should be also possible with settings if you really want to.

Labeling as question, looking forward your feedback.

**Comment by mschmid** [comment]
Hi, I ended up in defining an option "scm_reference" which is used to defined the branch/hash/revision that is built.

**Comment by memsharded** [comment]
Good.

Maybe, related to this issue, you want to check the ``package_id()`` functionality: http://docs.conan.io/en/latest/howtos/define_abi_compatibility.html

If you want dependent packages to always rebuild a new binary for any upstream change, you could use something like:

```python
def package_id(self):
     self.info.requires["MyRequiredLib"].full_package_mode()
```
