### ISSUE TITLE
What is the best way to create a "baseline" over a dependency tree?

### ISSUE THREAD

**Issue by mschmid** [conan-io/conan#1516]
Hi, it is very interesting to see Conan evolving in the last months.
Currently I am migrating our dependency management to Conan. I am not yet finished, but quite sure Conan will do a good Job.

In my opinion only two big points are still open:
The Conan "Project" Feature, see issue #1377 and
a way to change dependencies with tool support in several recipes at once if some base package changes and therefore 100 dependant packages need to be given a new version and dependencies.

For me the question arises: Which are your goals / planned features for the next releases?

**Comment by memsharded** [comment]
We are using github milestones to manage short-term goals: https://github.com/conan-io/conan/milestones

I totally agree, the "conan-project" has become a top priority, so we will most likely include it (a first approach) in 0.26 (0.25 is to be released this week, no time)

Could you please elaborate a bit further about the scenario you are describing about the dependencies change? Right now, conan implements dependency overriding, so if you have a full dependency graph depending on "LibA/1.0@user/channel" (many other packages), and you add "LibA/1.2@user/channel", to your end-consumer project, it will be propagated upstream, overriding LibA/1.0, so the full dependency graph will depend on "LibA/1.2", without needing to touch/edit the recipes. Also, depending on the configuration of ``package_id()``, it will require some of them to build a new binary or not.

**Comment by mschmid** [comment]
Thank you for the hint regarding the git milestones. I was just curious about the long term planning. On the other hand, Conan seems nearly feature complete.

I renamed the ticket to point out the open question regarding the dependency change.
The use case is, disregarding the package references (because the package contents could be overwritten), to fix a software release so that it cannot be changed anymore. E.g. to create a "baseline".

I understand that, in my end-consumer package, I can overwrite all the requirements including the transitive ones in a big list over the full dependency tree.
Additionally it could be necessary, to also fix the SCM-hash for all packages like this:

def requirements(self):
       self.requires("LibA/2.1@memsharded/testing") # overriding existing dependency
       self.requires("LibB/0.7@memsharded/testing") # overriding existing dependency
       self.requires("LibB/1.2@memsharded/testing") # overriding existing dependency

def configure(self):
       self.options["LibA"].git-hash = "XXXXXXXX"
       self.options["LibB"].git-hash = "YYYYYYYY"
       self.options["LibC"].git-hash = "ZZZZZZZZ"

What do you think? Are there better approaches?

**Comment by memsharded** [comment]
Can you please clarify the ``git-hash`` thing? Why not decouple it from the package manager. I strongly believe that LibA/2.1 should be tagged in git as 2.1, so the tag (or branch) can be used to retrieve the exact code, but not necessarily using the commits hash. Am I missing something? Thanks!

**Comment by mschmid** [comment]
Hi, this comes from the documentation:
http://conanio.readthedocs.io/en/latest/reference/conanfile/attributes.html

`class HelloConan(ConanFile):
   ...
   options = {"commit": "ANY"}
   default_options = "commit=1234abcd"`
"This could be useful, for example, if you want to have an option so a package can actually reference any specific commit of a git repository."

A tag for a single package is a good idea. But I am thinking of a huge dependency tree of >100 packages, that has to be conserved as it is.
I thought Conan could help here using the approach above.

**Comment by marco-m** [comment]
What do you mean exactly by: "Assume that several packages have been changed locally on a developers machine" ? Changed how? And what? The package source or the recipe pointing to them?

If the package source has changed, then the only way to have a sane workflow is to bump the version number of the package, so that the corresponding recipe refers to it.

If the recipe has changed and not the package it points to, then again, the only sane way is to bump something, what in my team call recipe revision. The goal is always to NEVER overwrite a conan package once it reaches the conan server.

Imagine you have LibFoo/1.2.3@pippo/stable

We introduce the revision as LibFoo/1.2.3-0@pippo/stable. Starting from that:
- the package changes? It will be consumed as LibFoo/1.2.4-0@pippo/stable
- the recipe changes? It will be consumed as LibFoo/1.2.3-1@pippo/stable

It is not clear to me if you own the package or if it is a 3rd party dependency.

If you own, then we don't use the revision, we keep package and recipe in the same repo, each time there is a merge to master we bump the version:
1.2.3 ==> 1.2.4 or 1.2.3 ==> 1.3.0 depending on the change. 

Hope this help

**Comment by mschmid** [comment]
Yes, I talk about owned packages. And yes, I mainly talk about package changes, recipe changes are not to common in my use case.

Currently I use a base recipe, which specific package recipes derive from, so I am not able to bump the revision while merging to master. However, this is a very good proposal. Do you have some automatism for this, e.g. git-hooks?
How do you organize all the carry-over parts the without a base recipe?
Is it feasible, in your opinion, to work with a python tool package which brings all the methods for checkout, build, etc., that are common steps over all packages?

**Comment by mschmid** [comment]
Probably outdated.
