### ISSUE TITLE
[question] ConanException: 'self.options' access in 'package_id()' method is forbidden

### ISSUE THREAD

**Issue by petwu** [conan-io/conan#15163]
### What is your question?

The [package_id](https://docs.conan.io/2.0/reference/conanfile/methods/package_id.html) documentation provides the following example:

> If you need to implement custom behaviors in your recipes but also need this logic, it must be explicitly declared:
> ```python
> def package_id(self):
>     if conanfile.options.get_safe("header_only") or conanfile.package_type is PackageType.HEADER:
>         conanfile.info.clear()
>     self.info.settings.rm_safe("compiler.libcxx")
>     self.info.settings.rm_safe("compiler.cppstd")
> ```
(`conanfile` needs to be replaced by `self`; probably a copy-paste mistake)

Similarly the [conan-center-index docs](https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/conanfile_attributes.md) state:

> Recipes with such option should include the following in their package_id method
> ```python
> def package_id(self):
>    if self.options.header_only:
>       self.info.clear()
> ```
> ensuring that, when the option is active, the recipe ignores all the settings and only one package ID is generated.

But using any of these approaches raises the following error:
```
ConanException: 'self.options' access in 'package_id()' method is forbidden
```

By looking at some conan center recipes and through some trial and error I figured out, that the following works:
```python
if self.info.options.header_only: ...
# or
if self.info.options.get_safe("header_only") or self.package_type is PackageType.HEADER: ...
```
I am fairly new to conan, so I am not quite sure if this is the correct/recommended way? If so, then the docs should be corrected. If not, what is? The documentation of the [info](https://docs.conan.io/2.0/reference/conanfile/attributes.html#info) attribute unfortunately does not provide any information on what methods and attributes it has.

Thanks for your help!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @petwu 

Thanks for your question.

> if conanfile.options.get_safe("header_only") or conanfile.package_type is PackageType.HEADER:
        conanfile.info.clear()

This can be probably simplified to just checking ``self.package_type == "header-library"``, because in Conan 2.0, Conan will be computing this from defined ``options``, even if the package type is not explicitly declared. Note you don't need to import ``PackageType`` for ``HEADER`` either, you can use plain strings, they are still checked and validated, so typos are not a problem here.

> Similarly the [conan-center-index docs](https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/conanfile_attributes.md) state:

Those docs from ConanCenter are a bit outdated and refer mostly to Conan 1.X, not Conan 2.0


> ConanException: 'self.options' access in 'package_id()' method is forbidden
> By looking at some conan center recipes and through some trial and error I figured out, that the following works:

Yes, your solution is the correct one. Recipes should be checking ``self.info.options`` in ``package_id()``, not ``self.options``


> I am fairly new to conan, so I am not quite sure if this is the correct/recommended way? If so, then the docs should be corrected. If not, what is? The documentation of the [info](https://docs.conan.io/2.0/reference/conanfile/attributes.html#info) attribute unfortunately does not provide any information on what methods and attributes it has.

Yes, your solution is correct, and the ConanCenter docs need to be updated (probably even removed and referred to the main Conan docs, not much sense to have things duplicated there). The Conan docs for ``package_id()`` method in https://docs.conan.io/2/reference/conanfile/methods/package_id.html should contain only explicit ``self.info.options`` usages. In general it is better to approach the docs by functionality=methods like ``package_id()`` than by data=attributes like ``info``

**Comment by AbrilRBS** [comment]
Closing as solved, the Conan 2 docs has now for a while properly mentioned the `self.info` access :)
