### ISSUE TITLE
[question] Is the timestamp during 'conan upload' updated if the revision/package id already exists?

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan#15167]
### What is your question?

Hi,

short question as I couldn't easily find it in the code: if I do a `conan upload` and it is detected, that the packages are already on the server, is the timestamp of the recipe revision updated?

This is e.g. the case when building 3rd-party components, where we are reverting changes on a recipe (reverting the bump of a dependency).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tbsuht 

Thanks for your question.

No, the revision timestamps and order in the server are preserved when there are subsequent uploads of the same thing. This is very necessary for stability of the solution, if the uploads update the timestamp (and order of the revision), the behavior when there are several parallel jobs uploading things is chaotic.

For reverting to previous revisions in time there are a couple of possibilities:
- To remove the server existing revision first, to force it become the latest again
- To move forward, instead of going back exactly to the same recipe revision, introduce something, a comment in the recipe ``//reverted to previous blah blah`` that will force the creation of a new recipe revision

**Comment by tbsuht** [comment]
Hi @memsharded ,

thanks for the fast answer!

These were actually also the solutions we came up with.

The problems with them is:
Can 1) be automated? I don't see an easy way to detect this scenario.
2) seems quite ugly, although working.

The problem with both of them is (at least if 1) is not automated), that it's hard to explain to other developers which are no 'experts' with using conan.

**Comment by memsharded** [comment]
The truth is that this scenario is equivalent and as ugly as a source code revert, a ``git reset`` and doing things like push force to rewrite history, kind of needing a manual push force (you don't want to do force push by default by developers and CI), and then some subsequent cleanup and maybe developers consuming those branches/commit would need to do some new checkouts or clean something locally to keep working.

The thing is that there is no good automated alternative:
- There is really nothing in an upload that has the same hash as an upload in the past that can be used to decide that such upload has to be made latest.
- Uploads cannot be made latest by default without creating a huge instability, mostly chaos when there is some concurrency
- So making all uploads latest by default is something that can't be automated without creating the problem.
- It is not reasonable to force re-upload at every step either, it is extremely inefficient and costly (Conan avoids re-uploading hashes that already exist in the server)

So the solutions in my experience that work best are the same as the ones in git. It is often better to have a linear history, undoing the work in new commits (creating new hashes), than breaking history (the equivalent of altering the order of package revisions). So doing some changes that forces new revisions is quite simple and works solidly, while leaving a clear trace of the revert both in source code and in Conan packages revision history. 

The main difference between the 2 solutions is that the first one, removing and re-uploading should only be doable by admins, because that is destroying history, while the second one can be easily done by any developer that can submit source code changes to CI, without anyone else intervention, because it respect history.

Also, I understand these things are not easy to explain to developers, but the analogy of messing with git still holds, it is simply not an easy problem to understand and address cleanly without some knowledge on the subject.
