### ISSUE TITLE
[question] `conan upload --only-recipe` doesn't work with `--list`

### ISSUE THREAD

**Issue by PeteAudinate** [conan-io/conan#15169]
### What is your question?

The docs for `conan upload` say:
>  --only-recipe         Upload only the recipe/s, not the binary packages.

However when using the `--list` argument, if the package list contains binary packages then they are uploaded regardless.

https://github.com/conan-io/conan/blob/release/2.0/conan/cli/commands/upload.py#L93 seems to confirm that `--only-recipe` is only used when converting from a pattern to a package list.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @PeteAudinate 

The ``--only-recipe`` is there in the ``upload`` and ``download`` commands to counter balance the default ``package_id="*"``. Because that is the default ``conan upload *`` will upload all the binaries, there is need for an option to upload only the recipe, and that cannot be done with just the "pattern" approach, and an explicit argument is required.

On the other hand, the ``conan list`` command do not default to list all binaries, and ``conan list *`` only list recipes, not binaries. Opting-in to list binaries is easy with a pattern approach ``conan list *:*``.

This difference is because the expected default behavior and common user errors are different for different commands. ``conan upload`` not uploading binaries by default is confusing and unexpected, while ``conan list *`` listing all binaries for all versions for all recipes is both very slow and unexpected in the vast majority of cases.

**Comment by PeteAudinate** [comment]
Thanks @memsharded, that makes sense.

We're using the following from https://docs.conan.io/2.0/examples/commands/pkglists.html#building-and-uploading-packages:

```
conan create . --format=json > create.json
conan list --graph=create.json --graph-binaries=build --format=json > pkglist.json
conan upload --list=pkglist.json -r=myremote -c
```

But in some cases we wanted to only upload the recipe that was built, but we couldn't find a way using the above.

The conan upload docs made us confident that adding `--only-recipe` to the above should only upload recipes. Your explanation for why it doesn't work makes sense, but isn't reflected in the docs.

**Comment by PeteAudinate** [comment]
In our case, since we know the names of the package we want to upload, we can:
```
conan upload package_name --only-recipe -r=myremote
```

**Comment by memsharded** [comment]
I think what you are looking for is the creating of ``pkglist.json``.
Instead of 
```
conan list --graph=create.json --graph-binaries=build --format=json > pkglist.json
```
using
```
conan list --graph=create.json --graph-recipes="*" --format=json > pkglist.json
```
will give you a ``pkglist.json`` that contains only the recipes, but not the binaries.

> The conan upload docs made us confident that adding --only-recipe to the above should only upload recipes. Your explanation for why it doesn't work makes sense, but isn't reflected in the docs.

yes, this might need some clarification, or maybe even some UX fix, raising an error. The ``--only-recipe`` is an argument that applies to "pattern" based selection of packages. When the argument is a pkglist, this argument is not used.

**Comment by PeteAudinate** [comment]
> using
> ```
> conan list --graph=create.json --graph-recipes="*" --format=json > pkglist.json
> ```
> will give you a pkglist.json that contains only the recipes, but not the binaries

That seems to emit all recipes, not just the one that was built. So it's not quite equivalent to `--graph-binaries=build`. I tried `--graph-recipes=build`, but that emits `"Local Cache": {}`.

**Comment by memsharded** [comment]
I see. There is no concept of "recipes that were built", only the packages are built, so only ``--graph-binaries`` can be used to filter based on that concept, and ``--graph-recipes`` can be used to filter by recipe status (with values as ``"Downloaded"``, etc).

In any case, is it really a problem? Conan avoids transfers completely if the revision already exist in the server, so uploading all graph dependencies recipes shouldn't be slow, as it will skip most of them. And recipes need to be in the server anyway, otherwise the graph and those packages will not be possible to be installed, because they will fail because of missing dependencies?

**Comment by PeteAudinate** [comment]
Ha, good point! You're quite right, what we were attempting wasn't very sensible. Thanks :-).

**Comment by memsharded** [comment]
Hi @PeteAudinate 

Any further feedback here? Can we close the issue? Thanks!

**Comment by PeteAudinate** [comment]
Thanks, happy to close. Though as you noted above, the docs or UX should make it clear that --only-recipes is ignored if --list is used.

**Comment by memsharded** [comment]
Sure, I missed that part, lets fix that quickly.

**Comment by AbrilRBS** [comment]
We have decided to make `--list` and `--recipe-only` able to work together, in Conan 2.1 only the recipes for the listed packages will be uploaded if used with the `--recipe-only` option, thanks a lot for your feeback

**Comment by PeteAudinate** [comment]
That's great, thanks!
