### ISSUE TITLE
[question] Is Conan compatible with python setup.py build_ext?

### ISSUE THREAD

**Issue by monchin** [conan-io/conan#15187]
### What is your question?

Hi! I have a python project with some C++ and cython codes, and the cpp part depends on some third party projects such as `spdlog` and `cppzmq`. The project is a little complicated that it uses cython code from other project so that I need to 
```python
# setup.py
import inspect
import project_I_need
import sys
from pathlib import Path
sys.path.append(str(Path(inspect.getfile(project_I_need)).parent/"cython"))
```
in `setup.py` file, so it is a little hard for me to switch `setup.py` to cmake.

Managing cpp dependencies is really necessary for me, so I think maybe Conan could help me. But I read the document briefly, and only found that Conan supports for cmake/meson/ninja... which all are cpp project manage tools, but no python setuptools.

My hope is that I can use a `conanfile.txt`, and just add `[requirements]` but no `[generators]`, and I can somehow use something like cmake's `find_package` in `setup.py`, and Conan can automatically manage `[requirements]` and add `include_dirs` and `lib_dirs` of `[requirements]`, and I could simply run `python setup.py build_ext`  then everything would be okay.  Is it possible to do so? If not, can I just use Conan to manage cpp dependencies but not compile, and add cpp dependencies include_dirs and lib_dirs manually to `setup.py`?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @monchin 

Thanks for your question.

We know from users that are using Conan to manage their C++ dependencies within Python projects. Conan is highly customizable, so it can be tuned for different use cases:
- The Python setup code should indeed run ``conan install`` to install the Conan C++ package dependencies. The profile might need to be detected with ``conan profile detect``, though if it can be pre-defined for different configurations, that is usually the recommendation for C++ in production
- You can disable and not use Conan generated files, and you can use a ``conanfile.py`` with a ``generate()`` method to automate the creation of any file that you want, to copy binaries around to simplify their usage from your Python code
- You can also use ``deployers`` to copy things from Conan packages to your desired location if that helps to use them from Python

It is something possible, because we have seen users doing it, but it might require learning and understanding a bit how Conan work, and there is no out-of-the-box integration, so it might need writing some adaptors to integrate it in the way you want.

**Comment by valgur** [comment]
You should really consider switching to a more modern and capable `pyproject.toml` + `scikit-build-core` + `CMake` approach. You will thank me later.
See https://scikit-build-core.readthedocs.io/en/latest/getting_started.html

**Comment by memsharded** [comment]
That is a good point.
For a more modern approach like that, maybe the ``cmake-conan`` integration here: https://github.com/conan-io/cmake-conan/tree/develop2 might help to automate the ``conan install``, so maybe something worth checking (note that it is in the ``develop2`` branch.

**Comment by monchin** [comment]
Thank you all for your kind and quick reply! I'll try.

**Comment by monchin** [comment]
> You should really consider switching to a more modern and capable `pyproject.toml` + `scikit-build-core` + `CMake` approach. You will thank me later. See https://scikit-build-core.readthedocs.io/en/latest/getting_started.html

I have considered to user `scikit-build-core` and `cmake`, but the main point that confused me is that this project depends on `.pxd` files from other projects, which means I need `from other_cython_project cimport what_I_need` in `.pyx` file in this project. The route of `other_cython_project` shouldn't be added in cpp's `include_dirs`, but should be added in `sys.path`, and I use `pdm` to manage my python projects before, the `other_cython_project` maybe in `.venv` or just in my local Projects-fils directory with `pip install -e`, so I'd like to `import inspect; sys.path.append(inspect.getfile(other_cython_project))` to dynamically find the route. Writing `cmake` to do this is now a little hard for me now (⊙﹏⊙ )

**Comment by czoido** [comment]
Hi @monchin! 

We recently launched **[conan-py-build](https://github.com/conan-io/conan-py-build)**, a PEP 517 build backend that integrates Conan directly into the Python packaging workflow, you don't need `setup.py` or manual `conan install`.

You can check the launch post here: https://blog.conan.io/cpp/conan/python/2026/05/05/Introducing-conan-py-build.html

For your use case (Cython + C++ deps managed by Conan), I'm in the process of adding an example that covers exactly this: [basic-cython (PR #52)](https://github.com/conan-io/conan-py-build/pull/52). The idea is that `conan build` resolves the C++ deps and drives CMake, which compiles the `.pyx` files. Cython just needs to be in `build-system.requires` and pip handles the rest.

I think it's worth giving it a look if you haven't already!
