### ISSUE TITLE
[question] How do you access the build profile from a conanfile?

### ISSUE THREAD

**Issue by ohanar** [conan-io/conan#15191]
### What is your question?

We are working on migrating our company's usage of conan from 1.x to 2.x, and in particular taking advantage of the cleaner distinction between the build and host context. What isn't clear though is how to access the build profile from a conanfile. It seems like there is an undocumented `settings_build` to access the build settings, but I haven't seen anything similar for `options` or `conf`.

Related to this, it seems like many of the builtin `conf` should look at the build profile, rather than the host profile. For instance, suppose we create a cmake package that sets `tools.cmake.cmaketoolchain:generator` as part of its `conf_info`. Consumers that use the package as a tool require don't utilize the specified generator as conan's built-in integration only examines the host profile's conf. Changing this is a breaking change, so I don't know what the solution is here (maybe look at the build conf before the host conf), but not having the ability to set relevant conf from such a package is annoying.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ohanar 

Thanks for your questions

> We are working on migrating our company's usage of conan from 1.x to 2.x, and in particular taking advantage of the cleaner distinction between the build and host context. What isn't clear though is how to access the build profile from a conanfile. It seems like there is an undocumented settings_build to access the build settings, but I haven't seen anything similar for options or conf.

In principle, recipes have 2 settings, their "host" ``settings`` and their "build" ``settings_build``, their own ``options`` (only one set, because there is only one package with one set of options), and its own ``conf`` (only one set).

The idea is that the options and conf are per-package, and as such, it doesn't make any sense to use the options of the build context in a recipe. For example, if we have a "build" profile that defines ``*:shared=False`` and a "host" profile that defines ``*:shared=True``, the current package ``self.options`` will only get their own value, if it is a "host" package it will be ``shared=True``. But having some ``self.build_options`` with ``shared=False`` is completely meaningless for the current package. Same reasoning with ``conf``.

> Related to this, it seems like many of the builtin conf should look at the build profile, rather than the host profile. For instance, suppose we create a cmake package that sets tools.cmake.cmaketoolchain:generator as part of its conf_info. Consumers that use the package as a tool require don't utilize the specified generator as conan's built-in integration only examines the host profile's conf. Changing this is a breaking change, so I don't know what the solution is here (maybe look at the build conf before the host conf), but not having the ability to set relevant conf from such a package is annoying.

I think this part is not accurate:

> Consumers that use the package as a tool require don't utilize the specified generator as conan's built-in integration only examines the host profile's conf.

The ``CMakeToolchain`` integration will check just the ``self.conf`` values. And these values will come both from the "host" profile and from the ``tool_requires`` ``conf_info``. So I think this should work, I have just tried in a test, and seems to work fine.

**Comment by memsharded** [comment]
Hi @ohanar 

Any feedback here? Is the question responded or do you have any further questions? Can we close the issue? Thanks!
