### ISSUE TITLE
[question] Use of the package metadata in conan 2.X

### ISSUE THREAD

**Issue by docbrown1955** [conan-io/conan#15202]
### What is your question?

Hi,

I am currently searching for a solution to package and distribute debug symbols of (internal) conan packages. The point here is not to trigger the discussion on pdbs that can be found elsewhere, but rather discussing the metadata feature itself.

I think metadata is a great way to solve the issue of debug symbols and more generally a lot of similar problems as the conan documentation suggests (and thanks a lot for that!).

My question is rather simple:
As this metadata feature is said to be experimental, how much can I trust it to use in a production environment ? Do we already have an idea of when it could become a stable feature ?

To be a bit more precise, I'm mostly concerned about breaking changes in the metadata storage on Artifactory (that would require some sort of migration), or even a possible removal as it was done for some conan 1.X features. Breaking changes in recipes or even the commands to fetch metadata can be more easily accomodated so would be less of a problem.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @docbrown1955 

(I like your "back to the future" github user name, btw 😄 )

> My question is rather simple:
As this metadata feature is said to be experimental, how much can I trust it to use in a production environment ? Do we already have an idea of when it could become a stable feature ?

That is an excellent question. 
The truth is that this is a chicken and egg, we cannot declare it fully stable unless there is enough evidence and feedback of users using it in production, and we totally understand that users don't want to use it in production until it is stable.

Said that, we have designed the feature with this issue in mind. 

The server storage is really pretty straightforward, an extra "metadata" folder. The heavy lifting has been done in the client to not download this folder by default. In that regard it should be quite unlikely that we need to change the server storage layout in a breaking way, and we always take into account that breaking something in the server side is orders of magnitude more challenging than breaking on the client side. This is why the full Conan 2.0 migration has been done without any special change in the server side, which keeps simultaneously compatible with Conan 1.X and Conan 2.0, and even the metadata feature has not required any changes in the server either.

So the idea is that we won't break the server side metadata storage unless there is some very serious flaw in the design that compromises the feature stability or security or Conan behavior in general. Otherwise, even if we want to move forward changes in the metadata server side, we will try our best to make them opt-in, and provide migrations tools to help.

Just one word of caution: using the feature is not simultaneously compatible with legacy Conan 1.X clients, which might download the metadata files, because this feature hasn't been backported to 1.X (it was basically impossible). That means that it should only be used in Conan 2.0 packages (they are decoupled from 1.X packages), but "recipe-metadata" might be downloaded by Conan 1.X clients.

**Comment by docbrown1955** [comment]
Hi @memsharded,
Thanks for your detailed answer.

> So the idea is that we won't break the server side metadata storage unless there is some very serious flaw in the design that compromises the feature stability or security or Conan behavior in general. Otherwise, even if we want to move forward changes in the metadata server side, we will try our best to make them opt-in, and provide migrations tools to help.

This is what I expected, I am quite fine then.

> Just one word of caution: using the feature is not simultaneously compatible with legacy Conan 1.X clients, which might download the metadata files, because this feature hasn't been backported to 1.X (it was basically impossible). That means that it should only be used in Conan 2.0 packages (they are decoupled from 1.X packages), but "recipe-metadata" might be downloaded by Conan 1.X clients.

This is not a problem for us as we started off with Conan 2.0 already, we do not have any legacy Conan 1.0 client. Good to know however in general.

> The truth is that this is a chicken and egg, we cannot declare it fully stable unless there is enough evidence and feedback of users using it in production, and we totally understand that users don't want to use it in production until it is stable.

Ok then, let's try it out ;)

**Comment by memsharded** [comment]
> Ok then, let's try it out ;)

Great, looking forward your feedback then.

As the question seems answered, and no immediate action from us, I am closing it, but do not hesitate to open or create a new ticket for any feedback, question or issue you might have. Thanks!
