### ISSUE TITLE
[question] Is is possible to use conan to describe libraries packaged as source-code?

### ISSUE THREAD

**Issue by woidpointer** [conan-io/conan#15205]
### What is your question?

Hi all,
  
I try to package a SDK where some libraries are not intended to be installed as a binary library but provides static source files as a somehow source-library which intentionally have to be compiled directly into the executable or 
 consuming library.

  The example below depicts the basic structure:
  - include and lib are used for headers and libraries
  - in the share folder the source libraries are packaged
  - share/Lib1 is for example the mentioned source-library.

```
  include/
  lib/
  share/
  └── Lib1
      ├── include
      │   └── my_source.hpp
      └── src
          └── my_source.cpp

```

Is there a possibility to describe such package layout in package_info() to enable the consumer to use the source files and compile it directory into the build target?

Something like:

```
  self.cpp_info.components["Lib1"].includedirs = ["share/Lib1/include"]
  self.cpp_info.components["Lib1"].sources = ["share/Lib1/src/my_source.cpp"]
```

is not supported, but describes what I have in mind to tackle this problem.

Thanks for your help.
wp

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @woidpointer 

Thanks for your question.

> is not supported, but describes what I have in mind to tackle this problem.

Why do you say it is not supported? Those attributes are there to represent sources. You have both:
- ``sources``: individual files
- ``srcdirs``: source folders
- And you can always use the ``.package_folder`` and some convention to access the packaged sources

What is impossible to have is an automatic way in generators to integrate those sources, because there is no standard way to compile the sources (this is one of the reasons why package management with compiled libraries make sense). Those sources might need a ``CMakeLists.txt`` to compile, or some other specific knowledge how to build them. There is definitely not a way in which Conan could know what to do with those sources. So it is up to the consumer package recipe, and to the conventions stablished between the package containing the sources and its consumers what to do with those sources.

The consumers can typically use the ``generate()`` method, to access the dependency folders ``self.dependencies.host["mydep"]...`` then do whatever they want with those sources. Maybe typically just copy them to some location in the current project, so the build of the current project can use them

Please let me know if this helps, thanks

**Comment by woidpointer** [comment]
Hi @memsharded ,

thank you for your answer. 
I am not sure if I understand your answer. Do you mean a custom generator https://docs.conan.io/2/reference/extensions/custom_generators.html  which knows how to interpret the file structure is the direction to go?

**Comment by memsharded** [comment]
Well, depends on the complexity of the generation, how many "consumers" will be using it, if the usage pattern is always the same or not, there could be different approaches. If this is only consumed by 1 other recipe, then coding the usage in the ``generate()``. But yes, if you are using the same pattern of usage many times, using your own custom generator can help not repeating yourself and maintaining the code more easily.

It would be good to know why you are doing this, because this approach of source code requires building again and again from source the same thing in all the consumers, why not creating a static library for that?

**Comment by woidpointer** [comment]
hi @memsharded 

sorry for the late reply. I have to do this because this SDK is a legacy package and the install provides the files exactly this way. So I am currently not sure what is best approch here, changing the packaging scheme of the legacy package or provide a generator for the internal use which knows how to deal with such package layout. 
At the moment I tend to custom generators because the usage pattern is always the same.

Thank you for help and advices.

**Comment by memsharded** [comment]
> At the moment I tend to custom generators because the usage pattern is always the same.

Ok, sounds good.

I think we can close this question as responded at the moment? You can open new tickets for any further question or issue you might have. Thanks!
