### ISSUE TITLE
[question] conan2: using jinja within recipe

### ISSUE THREAD

**Issue by iaavo** [conan-io/conan#15217]
### What is your question?

So Conan uses internally `Jinja2>=3.0, <4.0.0`. I would now like to make a custom generator recipe which uses jinja for templating. Can I rely on Conan to keep using this version of jinja or can I expect that some future version of Conan will bump to the next major version of it and then break the recipe.

Or alternatively, is there a public API through which Conan exposes jinja or some kind of templating mechanism?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @iaavo 

This is indeed a good question, but unfortunately we don't have a very closed answer yet:
- We don't have a "stable" wrapper around jinja2. But we use it a lot in many places of the Conan codebase. That means that if we use a newer breaking jinja2 version, we will be the first ones to realize it, and consider how this update could be done in a less breaking way.
- In general we tend to be very stable in our usage of dependencies, it is not that we continuously update them, unless there are very important reasons
- For a generator, the jinja2 templating code should be quite possible to centralize it in one place, so in the worst case if in the future it would change, it could be fixed with some ``if conan_version >= xxx``
- Finally, I don't think that jinja will change badly, this is the current plan (https://github.com/pallets/jinja/milestones), so it is very unlikely that they will break anytime soon either.

So overall, I'd consider the jinja2 dependency relatively stable, and can be used without a high risk of breakage, and the value/risk ratio is good enough to use it.

**Comment by iaavo** [comment]
Thanks for the in-depth reply! This really helps in my considerations on using jinja for my recipe. Question closed :)
