### ISSUE TITLE
Why does conan 2.0 MSBuildDeps generator generate too many files unlike conan 1.6

### ISSUE THREAD

**Issue by sandybhat16** [conan-io/conan#15231]
### Why does conan 2.0 MSBuildDeps generator generate too many files unlike conan 1.6

I am installing a boost header only package with generator(MSBuildDeps). After installing the generators generate too many files like below:
**conanbuild.bat
conanbuildenv-release-x86_64.bat
conandeps.props
conanrun.bat
conanrunenv-release-x86_64.bat
conan_boost.props
conan_boost_headers.props
conan_boost_headers_release_x64.props
conan_boost_headers_vars_release_x64.props
conan_boost__boost_cmake.props
conan_boost__boost_cmake_release_x64.props
conan_boost__boost_cmake_vars_release_x64.props
deactivate_conanbuild.bat
deactivate_conanrun.bat**

I know from conan version 1.6 the generator visual_studio used to generate only 1 file called **conanbuildinfo.props**

Is there anyway in conan version 2.0 I can generate only 1 file that has all the information?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandybhat16 

Thanks for your question.

To clarify, this is not a 2.0 question, but the MSBuildDeps exists already in 1.X and it is recommended to move to it in 1.X, and then move to 2.0.

MSBuildDeps generates more files because it is way more powerful and structured than the previous one. It allows things like having multiple subprojects and having each subproject to chose the specific dependencies they use, no more, and avoid potential overlinking or slow link times.

> Is there anyway in conan version 2.0 I can generate only 1 file that has all the information?

Not one file, but it is possible and recommended to use 1 folder, and this can be done with the ``layout()`` method, so all generated files will not be in the root, but in a dedicated subfolder that can be gitignored. For MSBuildDeps, the ``vs_layout()`` (see https://docs.conan.io/2/reference/tools/microsoft/visual_layout.html) does this, putting generated files in a subfolder called "conan".

**Comment by sandybhat16** [comment]
Thank you @memsharded . This I have already seen about how to use layouts to structure the files.
I think my actual question should've been - What is the equivalent of conan 1.6 visual_studio generator in conan 2.0?

**Comment by memsharded** [comment]
> I think my actual question should've been - What is the equivalent of conan 1.6 visual_studio generator in conan 2.0?

The ``visual_studio`` generator has been superseded already by ``MSBuildDeps`` and ``MSBuildToolchain`` in Conan 1.X. The recommendation is to use them already in 1.X even before upgrading in Conan 2.0

**Comment by sandybhat16** [comment]
@memsharded  Thank you for the recommendation. Appreciate it!
