### ISSUE TITLE
[question] CMakeToolchain + self.copy in import interaction

### ISSUE THREAD

**Issue by VladyslavSan** [conan-io/conan#15248]
### What is your question?

So let's say I have a recipe that picks up the ImGUI library. ImGUI library itself is build okay and is pretty simply. However, it contains some sources as resources. Basically just files that you copy to your project and compile only those you need.

In the imports method I call something like this: `self.copy(pattern="*glfw*", dst="backends", src="@srcdirs")`.

Let's say project root is X. I'm calling `conan install ...` and set install-folder+output-folder to `cmake-build-debug`, meaning that build folder is `X/cmake-build-debug'. However, when I run then `cmake --preset debug` and try to reference those files using cmake variable like `CMAKE_BINARY_DIR` I cannot find those files because it is set to `X/cmake-build-debug/build/Debug` while files that I've copied in `imports` using `self.copy(...)` are copied into `X/cmake-build-debug/".

Could somebody explain how it works and how to do what I want properly. I feel like I'm lost because it is hard to find any info in conan docs about that. I'm currently trying to migrate the project recipe from old style conan to the new one (use CMakeToolchain+CMakeDeps). Previously everything worked okay because all the build files and files that I'm copying were placed in `X/cmake-build-debug` and `CMAKE_BINARY_DIR` was set to exactly same folder so referencing copied files in cmake was easy. Currently I cannot find any way except referencing those files using `CMAKE_BINARY_DIR/../.." but it looks ugly. I personally expect some variable that provides more aligned path so either specify something in the python script to place copied files to the `CMAKE_BINARY_DIR` or another cmake variable set by conan to reference `CMAKE_BINARY_DIR/../..`.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @VladyslavSan 

Thanks for your question.

It might be that you are trying to use some legacy approaches while moving to the new things, but only partially. The recommendation would be:

- Do not use the ``imports()`` method anymore, use the ``generate()``  method
- Inside ``generate()`` use the ``self.dependencies["imgui"]`` to access the dependency, and then ``copy(self,  ...)`` instead of ``self.copy()``
- Define a ``layout()`` method expliciting your project layout. If you are using cmake, you might use the ``cmake_layout()`` built-in
- Do not rely on ``--install-folder`` or ``--output-folder`` for behavior, the ``layout()`` can be self-contained.

If after those things, you cannot make it work as you want, maybe the best would be to share a minimal ``conanfile.py`` that we can also reproduce here, and we could suggest changes over it. Thanks!

**Comment by VladyslavSan** [comment]
@memsharded thanks for helping, indeed moving copy to the `generate` method and using `copy(self, ...)` fixed the problem!

**Comment by memsharded** [comment]
Great, thanks for the feedback!

**Comment by VladyslavOdobesku-TomTom** [comment]
@memsharded btw, I've got one more question about modernisation.
In pre conan 2.0 times `conan install` has 2 flags that confuse me quite hard: `--install-folder` and `--output-folder`.
In conan 2.0 only `--output-folder` is left and I like that. Is there any tricks for conan 1.X to mimic that behaviour? Or maybe again I'm using something outdated and that's the reason some files are being output to `install-folder` and some to `output-folder`?

**Comment by memsharded** [comment]
- ``--install-folder`` is for the legacy files (``conaninfo.txt``, ``conanbuildinfo.cmake``, ``graph-info.json``...). These files cannot follow the ``layout()`` and ``--output-folder`` without breaking
- The ``--output-folder`` only applies to modern ``layout()`` and modern generators like CMakeDeps
- The above legacy files have been removed in Conan 2.0, so that is the reason ``--install-folder`` dissapears in 2.0.

So in the transition in 1.X, it is necessary to define the 2 arguments, specially if you need the legacy files for something (like local flow with ``conan build``). It is a bit ugly, but it was the only way to introduce the ``layout()`` feature in 1.X without breaking.
