### ISSUE TITLE
[question] Is it possible to check if a recipe is a test_package?

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#15247]
We have seen the `package_type` attribute, but it does not seem to allow a value for test_package recipes.

Is there any recommended attribute or method that could be used to detect whether the current recipe is a test_package?

**Comment by memsharded** [comment]
Hi @Adnn 

Yes, there is a simple trick. If ``self.tested_reference_str`` is defined, it is a test_package.

However, in general it shouldn't be necessary or recommended to make this kind of distinction in recipes. If you could elaborate a bit further what problem are you trying to solve, maybe there is some other better approach.

**Comment by Adnn** [comment]
Hi @memsharded, and thank you for the response!

We are trying to have a uniform `python_require` base recipe for both our "normal" recipes (located in a `conan/` subfolder from the repo root) and our "test_package" recipes.

For the first case, we have to set `self.folder.root = "conan"`, but for the second, we need to use the default value.
We hoped to handle this with a trivial `if ... else` flow of control in the base recipe, instead of forcing the consumer to override `layout()`.

**Comment by memsharded** [comment]
Thanks for the feedback!

> We are trying to have a uniform python_require base recipe for both our "normal" recipes (located in a conan/ subfolder from the repo root) and our "test_package" recipes.

I'd probably re-consider the main idea, because normal recipes and test_package recipes are quite different:
- Only ``test_package()`` have a ``test()`` method
- Only normal recipe have ``set_version()``, ``set_name()`` (or name and version in general), ``export()``, probably ``source()``, etc.
- Only ``test_package()`` define ``requirements()`` based on ``self.tested_reference_str``
- Only normal recipe uses ``conandata.yml`` 
- Only normal recipes need a ``layout()`` that would implement ``editable`` packages, so ``test_package`` layout can be way simpler.

There are a couple of things that I try to have in mind:
- I try to avoid inheritance whenever possible, use composition better
- For inheritance based, if some of the variables or methods of the base class do not apply to some of the derived classes, even if not used, it is an indicator than inheritance is not great.

So if it is a single ``if self.tested_reference_str ...`` then that might be ok, but if some of the other above things are a bit unclear, then maybe that would be an indicator to split the base class in 2, one for normal recipes and the other for test_package recipes.

**Comment by Adnn** [comment]
Thank you for your detailed explanations!

As it turns out, since the set of methods used by test_package and normal recipe are mostly distinct, a trivial base recipe defining them all works for both (it does not mean it was a good idea, just that, to our surprise, it worked without special handling, since unused method seem to be ignored instead of triggering an error). We will nonetheless follow your recommendation to split the base in two.

Out of curiosity, how do you use composition in recipes?
Do you mean the standard `import` mechanism?
Would not it imply to still define all required methods? (Even if they can be trivial, simply forwarding to the imported functionality, that is still several lines we do not need with inheritance.)

**Comment by memsharded** [comment]
> Out of curiosity, how do you use composition in recipes?

Yes, I mean avoiding the ``python_requires_extend``, and using explicit calling of functions coming from the ``python_requires`` inside your own derived recipes. It requires more code by default in the derived classes, but in my experience it tends to be more robust and easy to evolve the base class without breaking consumers (because adding new opt-in arguments, adding new superseding free functions, etc, is easy and clean, while trying to do the same with default inherited methods becomes almost impossible). As always, it is just a trade-off, depends on every case, but in general I tend to favor composition as my first go-to solution, and only consider inheritance after it becomes super-evident it is the best solution.

**Comment by memsharded** [comment]
Hi @Adnn 

Any further question here, or maybe we can close this ticket? Thanks
