### ISSUE TITLE
[bug] New package in requirement version range breaks the package ID

### ISSUE THREAD

**Issue by apyvovar** [conan-io/conan#15293]
### Environment details

* Operating System+version: macOS 14.2
* Compiler+version: apple-clang 15.0
* Conan version: 2.0.14
* Python version: 3.11.4

### Steps to reproduce

Let's assume, we have `MyPackage` with the following requirements:
```
    def requirements(self):
        # other packages
        self.requires("some_dependency/[>=2.0.0 <3.0.0]")
```

Now, when building it, I has the following output:
```
MyPackage/4.0.1: Package '8da3749f0f96e223baa5af5348c796b30f23f39e' created
```
I also have the `MyProject`, which consumes `MyPackage` and everything is working fine at the moment.

Now, the new **minor** version of `some_dependency` is introduced. And `MyProject` begins to fail (without any changes to it or to `MyPackage`) with the following error:
```
======== Computing necessary packages ========
MyPackage/4.0.1: Compatible package ID 2f3314d7e5c6b5d302dfb5490274610638d2f958 equal to the default package ID: Skipping it.
Requirements
    MyPackage/4.0.1#8b812bac22a56208cfdba9e41744fde5:2f3314d7e5c6b5d302dfb5490274610638d2f958 - Missing
    some_dependency/2.1.0#6ab680b34fa6d1719c40c849bdd2cd85:9322f4872c1fef242d872ecfc97a47fc08e16fcb#641eb664ec7463eb4532332ca236f157 - Cache

======== Installing packages ========
ERROR: Missing binary: MyPackage/4.0.1:2f3314d7e5c6b5d302dfb5490274610638d2f958

MyPackage/4.0.1: WARN: Can't find a 'MyPackage/4.0.1' package binary '2f3314d7e5c6b5d302dfb5490274610638d2f958' for the configuration:
```
Notice: now, conan requires package ID of `MyPackage` to be `2f3314d7e5c6b5d302dfb5490274610638d2f958`, which is NOT the same as was created before.

As far as I can see, new version of `some_dependency` somehow alters the package ID of `MyPackage`, because, if I try to rebuild (without any changes!!!) `MyPackage`, now the build output:
```
MyPackage/4.0.1: Created package revision 173a28482805e6e15e5924d6f90711fd
MyPackage/4.0.1: Package '2f3314d7e5c6b5d302dfb5490274610638d2f958' created
MyPackage/4.0.1: Full package reference: MyPackage/4.0.1#8b812bac22a56208cfdba9e41744fde5:2f3314d7e5c6b5d302dfb5490274610638d2f958#173a28482805e6e15e5924d6f90711fd
```
Notice: package ID is now `2f3314d7e5c6b5d302dfb5490274610638d2f958`, which is exactly what is required by `MyProject` and now it works again.

IMO, it's the bug, because in version range I explicitly states, that `some_dependency` is compatible and so rebuilding of `MyPackage` is not required.

I understand, that such cases were tested before, and it's possible, that the problem is somewhere in my conan recipes. If so, could you please guide me where it could potintially be.

Thank you in advance

**Comment by memsharded** [comment]
Hi @apyvovar 

Thanks for your feedback and detailed report.

If I understood it correctly, this is not a bug, but expected behavior. Conan uses the versions of dependencies as a factor in the ``package_id`` computation, and by default, bumping the minor requires rebuilding consumers. You can read more about it here https://docs.conan.io/2/reference/binary_model/package_id.html and here: https://docs.conan.io/2/reference/binary_model/dependencies.html

The system is designed to deal with C++ compilation model, semver version-ranges are good for API compatible changes, but not necessarily (and most times they don't) for needing to rebuild packages (new ``package_id`` when dependencies change).

**Comment by apyvovar** [comment]
Looks like I indeed was not fully aware of compatibility logic in conan.

Thank you and sorry for troubles.

**Comment by memsharded** [comment]
> Looks like I indeed was not fully aware of compatibility logic in conan.

Yeah, the main problem is compilation model of C/C++, that can do things like inlining (embedding) code in headers from dependencies in a binary artifact of the consumer, or even full binaries like static libraries can be fully embedded in the binaries of the consumers like shared libraries. Then it is not enough that the API is fully compatible, but the downstream consumers must be re-built in order to incorporate the changes of the dependencies, otherwise they will be running with older versions!
This it the reason we chose "minor_mode" in 2.0 as the default, as it allows full control:
- Bumping the patch: It is API and ABI compatible, no need to rebuild. When changes are done only in .cpp files of the dependency, might be good
- Bumping the minor: It is API compatible, but not ABI valid, need to rebuild the consumer. If the changes modify header files, that can contain templates, inline functions, etc, recommended to bump the minor. Consumers shouldn't need to modify their code, only to re-build
- Bumping the major: When there are breaking API changes that requires modifying the code of the consumers.


> Thank you and sorry for troubles.

No prob! Don't hesitate to report or to ask as many issues and questions you might have, feedback is always useful, and we are glad to help as much as we can

**Comment by robindegen** [comment]
I'm still a little confused about the behavior. Are you sure there wasn't a bug introduced in 2.0.15? 

With Conan 2.0.14 this package worked on windows, linux and macos. With Conan 2.0.15 I get the following message:

Conan 2.0.15 (https://github.com/aleya-dev/libaeon/actions/runs/7282180560/job/19844092808):
```
asio/1.29.0@aleya/public: Compatible package ID da39a3ee5e6b4b0d3255bfef95601890afd80709 equal to the default package ID: Skipping it.
```

I ran a build of the exact same thing on conan 2.0.14 (https://github.com/aleya-dev/libaeon/actions/runs/7282554627/job/19845101294):
```
asio/1.29.0@aleya/public#bafe0390378ec0f1c1782cff24ab63c0:cb836a521fc8494ecf80498fd71e4aa2dc66157d#5117d4e3cc2c109e5a78b21adf7ee89c - Download (aleya)
```

Why is the computed hash different? Why did the package stop working? Did something change in Conan 2.0.15 in the way these hashes are computed?

Artifactory with package:
https://artifactory.aleya.dev/ui/repos/tree/General/aleya/aleya/asio

Package itself:
https://github.com/aleya-dev/mirror-package-asio

**Comment by memsharded** [comment]
Hi @robindegen

Thanks for the report.
This might be a different ticket, if it is 2.0.15 it is not related to the previous one.

Conan 2.0.15 did a bug fix in the computation of ``package_id`` of header-only libraries that could be wrongly affected by python-requires and tool-requires in some cases, while it shouldn't. This hadn't been detected before because it is quite unusual to use ``python_requires`` for header-only libraries, as they are so simple they rarely need such python-requires

**Comment by robindegen** [comment]
I moved it over to a new one. You beat me to it. #15318
