### ISSUE TITLE
[feature] Improve Conan 2.0 install command design

### ISSUE THREAD

**Issue by redradist** [conan-io/conan#15329]
### What is your suggestion?

For me current Conan 2.0 design of install command is a bit strange ...
For example, previously it was possible to 
```console
conan install flatbuffers/22.10.26@
```
It was consistent with existing package managers in other languages, for example:
```console
pip install aiohttp # for Python
cargo install ripgrep # for Rust
```
But currently Conan 2.0 has the following way:
```console
conan install --requires=flatbuffers/22.10.26@
conan install . # if in current directory we have conanfile.txt or conanfile.py
```
For me it would be better to do it posit way like it is done in `pip` and `cargo`.
My suggestion is to change the following options:
`conan install --requires=flatbuffers/22.10.26@` -> `conan install flatbuffers/22.10.26@`
`conan install .` -> `conan install --path .`

Lets see how it will be compared with other languages:
```console
conan install flatbuffers/22.10.26@
pip install aiohttp
cargo install ripgrep
apt-get install libcurl

conan install --path .
pip install -r ./<path_to>/requirements.txt
cargo install --path .
```
After those changes it more consistent with other package managers and also less typing :)))

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @redradist 

Thanks for your feedback.
There are some reasons why the Conan CLI is that way:

- We learned the lessons from Conan 1.X, in which we had something similar to your proposal. It had some ambiguities that were causing user errors, tickets, etc, like the challenges to differentiate a reference from a path. The current 2.0 syntax is built on top of years of experience and users feedback, it is a carefully designed and discussed CLI syntax by the whole team.
- Conan has the concept of ``tool-requires`` too, and it is important to install them as such so the syntax ``--requires=zlib/1.2.13 --tool-requires=cmake/3.25.1`` allows exactly that
- It makes easier to provide multiple inputs in the same line with multiple ``--requires`` clauses
- The largest use case by far is installing by path, not the opposite, using a ``conanfile`` file. This is why the default syntax prioritize this case and not the ``--requires`` one. This is due to other languages like python installing in an environment that somehow tracks graph consistence (in a poor way, just flattening the graph). But for C++ and Conan graphs that allows to have different versions even in the same graph, installing all the needed dependencies simultaneously is critical, and this is achieved far easier with a ``conanfile`` than providing requires directly in command line.

Finally, it is not possible to change the command line now, it would be breaking massively, and creating a parallel syntax would be too much for the value at this moment. So I am closing this ticket as not planned at the moment, but we will take it into account for future re-designs of the CLI syntax, thanks very much again for your suggestions and your feedback!

**Comment by redradist** [comment]
@memsharded 
>
>  We learned the lessons from Conan 1.X, in which we had something similar to your proposal. It had some ambiguities that were causing user errors, tickets, etc, like the challenges to differentiate a reference from a path. The current 2.0 syntax is built on top of years of experience and users feedback, it is a carefully designed and discussed CLI syntax by the whole team.
>

It was an issue because you used single variable for two purposes `path_or_reference`
My suggestion is to split them, but in another way that you did. Provide `--path` option for real file and allow to use library `reference` without additional `--require` parameter

> It makes easier to provide multiple inputs in the same line with multiple --requires clauses

It would be the same in case changing options:
```console
conan install zlib/1.2.13 cmake/3.25.1
conan install --path . # For conanfile.txt or conanfile.py
```

> Finally, it is not possible to change the command line now, it would be breaking massively, and creating a parallel syntax would be too much for the value at this moment. So I am closing this ticket as not planned at the moment, but we will take it into account for future re-designs of the CLI syntax, thanks very much again for your suggestions and your feedback!

I would say that Conan 2.0 is already big breaking change for old packages. By breaking it now for Conan 2.0, you will add big compatability with Conan 1.X

**Comment by memsharded** [comment]
> My suggestion is to split them, but in another way that you did. Provide --path option for real file and allow to use library reference without additional --require parameter

I commented about it above. The largest use case by far is providing the path of a conanfile, so ``conan install .`` is the most used command in Conan. We don't want to make it opt-in as ``conan install --path``, that will make the UX worse.

> I would say that Conan 2.0 is already big breaking change for old packages. By breaking it now for Conan 2.0, you will add big compatability with Conan 1.X

Conan 2.0 was released in February. We have already done 16 new 2.0.X releases with tons of improvements and awaited features, and Conan 2.0 is already used in production by users, so I am afraid it is too late to consider this breaking change. We did 7 alpha releases and 10 beta releases with this syntax along 18 months before the 2.0 release. We will consider the ideas for future re-designs of the CLI, but as commented above, at the moment it is not possible to consider this change.

**Comment by redradist** [comment]
> > My suggestion is to split them, but in another way that you did. Provide --path option for real file and allow to use library reference without additional --require parameter
> 
> I commented about it above. The largest use case by far is providing the path of a conanfile, so `conan install .` is the most used command in Conan. We don't want to make it opt-in as `conan install --path`, that will make the UX worse.
> 
> > I would say that Conan 2.0 is already big breaking change for old packages. By breaking it now for Conan 2.0, you will add big compatability with Conan 1.X
> 
> Conan 2.0 was released in February. We have already done 16 new 2.0.X releases with tons of improvements and awaited features, and Conan 2.0 is already used in production by users, so I am afraid it is too late to consider this breaking change. We did 7 alpha releases and 10 beta releases with this syntax along 18 months before the 2.0 release. We will consider the ideas for future re-designs of the CLI, but as commented above, at the moment it is not possible to consider this change.

@memsharded Okay, then I suggest you to add the following option:
`-p, --packages [PACKAGE [PACKAGE]]`

It will allow to install multiple packages with less typing:
```console
conan install -p zlib/1.2.13 cmake/3.25.1
conan install --packages zlib/1.2.13 cmake/3.25.1
conan install . # Still for conanfile.txt or conanfile.py
```

What do you think ?

**Comment by memsharded** [comment]
``cmake`` cannot be installed as a regular require in general, it has to be specified as a tool-requires. Also multi-value syntax for a single arg is not working when there are other positional and optional arguments, so each value must have its own ``-x`` key anyway.

The following syntax is already working fine:
```bash
conan install --req=zlib/1.2.13 --t=cmake/3.25.1
```

The ``-p`` would be confusing, because ``-pr`` argument already exist for profile. ``--packages`` doesn't make sense, we already have the ``--requires`` already for exactly that, that aligns with all the other naming, like ``[requires]`` in conanfile.txt. ``-r`` cannot be used either because it is already taken for ``--remote``.

So it seems we are talking mostly about saving 3 key presses, from ``--req``, to something else in the form ``-x``, and we don't even have a clear alternative for the "x".

**Comment by redradist** [comment]
> ```shell
> conan install --req=zlib/1.2.13 --t=cmake/3.25.1
> ```

@memsharded Unfortunatlly it is not as flexible as simple iteration `conan install --packages zlib/1.2.13 flatbuffer/3.25.1`

Also in `conan install` all options are named expect `[path]`. As for me it is acceptable that `[path]` cannot be used inside of `install --packages` command. I mean the following:
```console
conan install --packages zlib/1.2.13 flatbuffer/3.25.1 # Works
conan install --packages zlib/1.2.13 flatbuffer/3.25.1 . # DO NOT WORK
```
