### ISSUE TITLE
Relative paths not working in exports_sources the way they do in exports

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#1537]
I have started using the `exports_sources` variable in this branch of glm:

https://github.com/dimi309/glm/tree/develop/conan-center

Here is the conanfile:

https://github.com/dimi309/glm/blob/develop/conan-center/util/conan-package/conanfile.py

After executing `conan create dimi309/stable` from the util/conan-package subdirectory of the project, I noticed that the sources pointed to by the relative path `os.sep.join([".", "..", "..", "*"])` are not copied to the `export_source` directory in conan data. Using the same relative path in the `exports` variable was resulting in a copy to the `export` directory. Would it be possible to make the behaviour of relative paths in exports_sources the same as the one in exports? 

Being able to copy sources this way is quite important when asking developers of existing libraries to include a conan setup in their repositories because they often ask that the conan configuration be placed in a subdirectory of their project.

**Comment by memsharded** [comment]
Could be a bug, yes, I will have a look right now

**Comment by memsharded** [comment]
I think it is because of the first "." , which is totally uninformative for parents paths. You should be fine with: 
``exports_sources = os.sep.join(["..", "..", "*"])``

Also, it is very likely that you don't need to ``exports_sources`` all the repo files, but you will be fine exporting only the sources inside ``glm`` subfolder. 
Maybe something like: ``exports_sources = os.sep.join(["..", "..", "glm*"])``. Note that the final path, ``glm*``  might have a different behavior than ``glm/*``, because of the base path taken.

Please, tell me if this works.

**Comment by dimi309** [comment]
Everything works as suggested. Thanks a lot! I have merged the develop/conan-center branch into master and have introduced a pull request to the main library repository:

https://github.com/g-truc/glm/pull/662
