### ISSUE TITLE
[question] Conan build pipeline also runs linter and code coverage measurements?

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#15389]
### What is your question?

When looking at the Conan Jenkins pipeline I can see that unit tests are being executed. But I did not see any linter or code coverage reports being published.

Did I look at the wrong place or is the Conan code base not linted and also no code coverage measurements are done?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MTomBosch 

We had both coverage and linter some time ago, but it was not providing enough value and at some point in some maintenance or migration they were dropped. We maintained very good coverage, reported > 93% but probably more because the aggregation of multiple platforms and testing levels were not completely accurate. I think current coverage will keep around that.

Linters, we have them typically in our IDEs, and we try to fix things while doing normal work, problem with linters is the very high amount of false positives or unimportant issues, not worth the effort, so having them in CI was even less useful than coverage. 

I think we will add them back once we deprecate Conan 1.X and can do large scale refactors on the codebase testing suite that we don't want to do it yet because we keep merging from 1.X to 2.0.

**Comment by MTomBosch** [comment]
Ok. Thank you for the honest words ;)
