### ISSUE TITLE
[question] is there a way to detect misspelt/unused options in the profile?

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan#15401]
### What is your question?

It may happen that an option is defined in the profile but never actually used, and no warning is sent to the output.

It would be useful to have this warning to detect the following errors:
- an option was misspelt in the profile
- an option was removed or renamed in the recipe

Is there already a way to detect these errors? Or is it a new request for conan?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fdgStilla 

This is already a Conan feature, note fore example:
```bash
$ conan install --requires=zlib/1.3 -o zlib/1.3:sahred=True
                                                                       
======== Input profiles ========                                       
Profile host:                                                          
[settings]                                                             
arch=x86_64                                                            
build_type=Release                                                     
compiler=msvc                                                          
compiler.cppstd=14                                                     
compiler.runtime=dynamic                                               
compiler.runtime_type=Release                                          
compiler.version=193                                                   
os=Windows                                                             
[options]                                                              
zlib/1.3:sahred=True                                                   
                                                                       
Profile build:                                                         
[settings]                                                             
arch=x86_64                                                            
build_type=Release                                                     
compiler=msvc                                                          
compiler.cppstd=14                                                     
compiler.runtime=dynamic                                               
compiler.runtime_type=Release                                          
compiler.version=193                                                   
os=Windows                                                             
                                                                       
                                                                       
======== Computing dependency graph ========                           
ERROR: option 'sahred' doesn't exist                                   
Possible options are ['shared']                                        
```

Only when the references are patterns like ``zlib/*:option=value`` it will not fail, because patterns can apply to different recipes that  might not define those options at all, so it is not possible to error and even warnings are very annoying and false positives, so Conan doesn't report anything.

**Comment by fdgStilla** [comment]
We try to only use patterns to avoid having to update the profiles when we bump the versions that's why we do not get the warning, thanks for the explanation.

But the warning does not seem to be raised if it fully specified but does not apply to any package:
`conan install --requires=zlib/1.3 -o foo/1.1:shared=True` does not raise any warning.

We had this issue for example when we changed our dependency from tbb to onetbb, we forgot to update all the profiles, some options were useless and we were not warned to update them.

**Comment by memsharded** [comment]
> But the warning does not seem to be raised if it fully specified but does not apply to any package:
conan install --requires=zlib/1.3 -o foo/1.1:shared=True does not raise any warning.

Oh, yes, the warnings can only be raised when the pattern is a perfect match and the option doesn't exist. For other cases it is not possible to do warnings or errors, we tried in the past, but it didn't work. The problem is that many users will define those options in profiles files, and there are many times that those options do not apply, for example, imagine you have a profile that define ``boost/1.2:shared=True``, ``opencv/2.3:other=42``, etc, but you use that profile just to install ``zlib``, because you need to check something just on zlib package. Conan doing warnings for every option that cannot be found in dependencies is annoying, and considered as noise or false positives by users, this is why it is not possible to warn against these non-matches.

**Comment by fdgStilla** [comment]
Ok thanks for the clarification
