### ISSUE TITLE
Does conan install support calling external scripts at command line?

### ISSUE THREAD

**Issue by sandybhat16** [conan-io/conan#15400]
Hi,

I am using cmake file to install boost. It also builds during the install. However, for building I want to use the bootstrapping script  of boost and  the b2 library from the boost src folder to build it, hence I want to call an external script to build. Is this possible?

Part of my Cmake file:

```
SET(Boost_Package_name "boost")
SET(Boost_Version "1.71.0")
SET(Boost_Header_Only "False")

SET(ARCH "x86")
SET(Remote_Server "conancenter")
SET(Debug_Output_Folder "${CMAKE_CURRENT_SOURCE_DIR}\\..\\generated\\Debug\\")
SET(Release_Output_Folder "${CMAKE_CURRENT_SOURCE_DIR}\\..\\generated\\Release\\")

execute_process(COMMAND conan install --requires=${Boost_Package_name}/${Boost_Version} -o ${Boost_Package_name}*:header_only=${Boost_Header_Only} -s arch=${ARCH} -s build_type=Debug -r ${Remote_Server} -g CMakeDeps -of ${Debug_Output_Folder} -b missing
			OUTPUT_QUIET
		)
```

External script that I want to invoke  from the downloaded boost src folder:

```
bootstrap.bat

b2 --build-dir=build\x86\debug   address-model=32 threading=multi --stagedir=.\bin\x86\debug   --toolset=msvc -j 8 link=static runtime-link=shared --variant=debug
b2 --build-dir=build\x86\release address-model=32 threading=multi --stagedir=.\bin\x86\release --toolset=msvc -j 8 link=static runtime-link=shared --variant=release
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @sandybhat16 

Thanks for your question.

There are two different approaches here:

- If your approach is that everything is driven from CMake, and calling ``conan install`` from your CMakeLists.txt, then the right place to do automation is your CMakeLists.txt. If you plan to do this approach, then, instead of doing it yourself, I suggest having a look to our cmake-conan integration that helps calling Conan from CMake, in a transparent manner, thanks to the CMake providers. Please check: https://github.com/conan-io/cmake-conan
- The other approach is to call Conan explicitly, then CMake or your build system. This is the "canonical" documented way to use Conan to install dependencies. When you are doing this, you are writing your our ``conanfile.py``. In that ``conanfile.py`` you can write extra logic, for example in the ``generate()`` method that runs after your dependencies have been installed.

It is true that you can use a ``conanfile.py`` with your own custom logic for the first approach using the ``cmake-conan`` integration, because that still uses a local ``conanfile`` to define the requirements, so the ``generate()`` method can still be used there to run after the installation of dependencies, and before your build. But in general the first approach, driven by CMake tends to put less logic on conanfiles and more on CMakeLists.txt, because this is done by users who want to automate using CMakeLists.txt.

**Comment by sandybhat16** [comment]
@memsharded Thanks for your response. I somehow wanted to avoid using a recipe file. But nevertheless, if this is the only way then I would like to go ahead with 2nd approach as in the near future we may replace CMake with Visual studio soultion. 
But to go ahead I'm stuck with 2 bugs where the build fails since yesterday. Have reported it below:

[https://github.com/conan-io/conan/issues/15420](https://github.com/conan-io/conan/issues/15420)

[https://github.com/conan-io/conan-center-index/issues/22213](https://github.com/conan-io/conan-center-index/issues/22213)

**Comment by sandybhat16** [comment]
Alright, Now that the issues are solved, coming back to generate method. Like I mentioned I want to invoke a script  from the extracted boost src folder:

In my generate method I am able to access the package folder using` self.dependencies["boost"].package_folder`. But how can I access the extracted folder? 

With ` self.dependencies["boost"].package_folder` I get 

> C:\Users\myuser\\.conan2\p\b\boosta0ef96159d715\p

But I want to get - 

> C:\Users\myuser\\.conan2\p\boost6bb638233755b\s

I was able to find some documentation regarding deploy [here](https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html).

But this might be overkill. There should be an easier way to get the extracted folder.

**Comment by memsharded** [comment]
> In my generate method I am able to access the package folder using self.dependencies["boost"].package_folder. But how can I access the extracted folder?

If you mean the "source" folder, I am afraid it is not possible. Note that by default Conan install the boost pre-compiled package, this is what you get in your ``package_folder``. The sources might not be in the computer at all, because they were not fetched, and the ``b2`` is not part of the boost package, it belongs to another package that is a ``tool_require`` of ``boost`` itself, check https://github.com/conan-io/conan-center-index/blob/5231449deb69f6067ac2f31bd9a484fcf9128183/recipes/boost/all/conanfile.py#L562

Note that a package manager decouples the build systems of the dependencies. It doesn't matter if a dependency was built with CMake or with B2 or with autotools. Those details, source files, build scripts by default are non-existing to the consumers, because they are only used when the package is built from sources.


If you want to use ``b2`` as a tool in your package, you should do a ``tool_requires("b2/...`` yourself.
It also looks like that you want to download the sources scripts that you need as well (I am not sure ,maybe those are packaged in the ``b2`` package? 

Another alternative, if you follow the guidelines and practices in https://docs.conan.io/2/devops/using_conancenter.html and you build packages from your own fork of ``conan-center-index`` repo is that you can modify the ``boost`` recipe and make it package together with the headers and libraries, other files that you might want, and then they will be accessible in the ``package_folder``.

Still, it sounds that the above solution wiht ``tool_requires("b2/..`` and downloading directly the files that you might need for your current package would be the way to go.

**Comment by memsharded** [comment]
I am closing this ticket as staled, but please re-open or create a new one if there are further questions. Thanks for your feedback.
