### ISSUE TITLE
[question] SConsDeps generator does not generate informations about tools_requires

### ISSUE THREAD

**Issue by Jsbjr** [conan-io/conan#15425]
### What is your question?

Hello,

I am using SCons for building and using conan1. We want to migrate to conan2
In our profiles, we have some build requirements like this:
[build_requires]
some-compiler/1.0.0@...
some-post-processing-tool/1.0.0@....
...
We have been using the deprecated scons generator to give SCons the path to the tools ( BINPATH, ...)

We tried to use tools_requires and and the SConsDep generator but the tools requirement are filtered out.
Is there another intended way to retrieve these paths. Or would it be possible to have another generator for these something like SConsBuildDeps?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Jsbjr 

Thanks for your report.
It is true that in the first iteration of ``SConsDeps`` the tool-requires were left out, mainly because we didn't have enough feedback about how these tools are used within SCons, what would be the risks of putting all build-requires in the dependencies information, because there are ugly situations when for example a ``tool_requires`` depends on a library like ``zlib`` it could unexpectedly bring that incorrect and possibly incompatible library into the information to link for the consumer and that breaks. So we wanted to have the feedback first.

As a note, Conan automatically puts the "bin" path of ``tool_requires`` in the PATH environment variable. That means that running anything in the consumers like ``self.run("mypostprocessingtool ...")`` will automatically work and same if run internally by any build system, because the tools will be automatically put in the PATH.

So it would be great to understand and know the usage patterns, why the automatic injection in the PATH wouldn't be enough and what would be the SCons constructs to use those applications. Many thanks!

**Comment by Jsbjr** [comment]
hi @memsharded,

I understand that having every dependencies in the same array may break things, that is why I thought that having a different generator for the build dependencies would be a good idea.

Using the PATH would work for part of our dependencies, but not for all. Because our (build) dependencies have configuration/header/libs/... files for the tools which are not in the BINPATH and we need to provide when calling the tools.

For context we build a library to include into an SDK for embedded devices. We use the current conan package of our SDK to build our library which will then be included into the next version of our SDK package.


Actually the build_requires we have don't map perfectly to tool_requires and/or test_requires. Some of them should probably be simple requires but hidden, because we don't want the user of our package to be forced to use the SDK we used for building.
But requires can not be added into the profiles where they where currently tracked so we will have to change that and maybe use conandata.

**Comment by memsharded** [comment]
> Using the PATH would work for part of our dependencies, but not for all. Because our (build) dependencies have configuration/header/libs/... files for the tools which are not in the BINPATH and we need to provide when calling the tools.

Typically, ``tool_requires`` manage their internal "toolchain" libraries in some way, without exposing them as regular libraries to the consumers. The main problem is the mismatch of binaries, specially in cross-compilation environment. If there is a cross-build scenario, lets say we are cross-compiling from a Windows-x64 machine to a Linux-armv8 one. Our "tool_requires`` will be installed for the profile ``os=Windows, arch=x86_64``, because it will contain binary tools, the compiler, cmake, ninja, etc that must run in Windows-x64 machine. If those tools link some internal libraries for their own build, then those libraries will be libraries built for Windows-x64. So by default, libraries in a ``tool_requires`` package are also assumed to have the architecture of the "build" context. So Conan cannot propagate them to the consumers in the "host" context so they can link them, because they will fail to link.

If there are packages that contain libraries both for the build and host context, like ``protobuf``, then the way to use them is the one explained in https://docs.conan.io/2/examples/graph/tool_requires/using_protobuf.html

Finally, the case at hand, "toolchains" containing both binary tools to be executed in the "build" context and libraries to be linked in the "host" context, which in the recipe of that package will be the ``settings_target`` information, is a special case. Conan cannot automatically propagate linking information of libraries found there, but in many cases it doesn't make sense. For example, it is not necessary to explicitly pass every library that is linked by default by compilers, and it is not expected that users of a compiler will have to do a ``find_package()`` in their CMakeLists.txt to find the compiler standard library or every system header.

We want to improve this use case, but so far we have seen that it depends on the sdk/toolchain/tools a lot, and usage patterns might vary a lot. Some encode the information they need in their binary tools, so those tools when execute, they know how to find the libraries, headers that they need

**Comment by memsharded** [comment]
Did you manage to get it working some way @Jsbjr ? Maybe via environment?

Don't hesitate to open new tickets if you have any further question. Thanks!
