### ISSUE TITLE
[question] Is it possible to ignore upstream dependencies for tool_requires?

### ISSUE THREAD

**Issue by realbogart** [conan-io/conan#15433]
### What is your question?

We are using tool_requires to install some binaries that are used to build our project. These tools are compiled in our CI/CD system and are expected to be available when our developers consume them. The problem that we have is that sometimes the upstream dependencies of these tools change, and then the binaries have to be recompiled. For example, `cppcheck/2.13` depends on `pcre/8.45` which depends on `bzip2/1.0.8`. We are only interested in getting the binaries for cppcheck, and we never want to build it locally. 

We have a recipe called `external_tools`, that adds a list of tool_requires like this:
```self.tool_requires(ref, visible=True)```

We then consume it like this:
```conan install --requires "external_tools/[<2.0.0]@internal/stable" -pr:a windows-msvc-16-release-x86_64```

`external_tools` has a version range and we want it to automatically install the latest version that satisfy the range. Do we then have to add `-u` to the install command? Adding `-u` is what caused the problem for us when Conan found new revisions/patches upstream.

Is there a way to ignore the upstream dependencies? Do we have to use a lockfile to avoid this issue?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @realbogart 

Thanks for your question.

Could you please clarify the usage of ``external_tools``? Do you plan to use it in production as ``tool_requires("external_tools/..."`` of other packages? Because that is the case, things might not work as you think. Having ``external_tool``->(tool-requires)->``othertool`` doesn't mean that the ``othertools`` will be available to the consumers, that is not the intention. It seems you are trying to circumvent that with ``visible=True``, but the visibility can affect to conflicts, for example, but there might be things like ``conf_info`` or environment that is only propagated from **direct** ``tool_requires`` not indirect ones.

> For example, cppcheck/2.13 depends on pcre/8.45 which depends on bzip2/1.0.8. We are only interested in getting the binaries for cppcheck, and we never want to build it locally.

Conan is able to "skip" fetching the binaries from the servers if they are not needed, this should work already automatically

> external_tools has a version range and we want it to automatically install the latest version that satisfy the range. Do we then have to add -u to the install command? Adding -u is what caused the problem for us when Conan found new revisions/patches upstream.

That might be a different issue. If there are new versions or revisions of ``bzip2`` or ``pcre`` then, it can be necessary to rebuild ``cppcheck`` if there is no binary for it yet. Sometimes in ConanCenter it takes some time until the binaries of consumers are built after some upstream dependency is changed. While we are right not prioritizing to improve ConanCenter CI to reduce this, it will take time, and in any case, this is the guide to use package from ConanCenter when these kind of production issues happen, please have a look: https://docs.conan.io/2/devops/using_conancenter.html

**Comment by realbogart** [comment]
Hi @memsharded, thank you for the quick reply.

Our first approach was to have `external_tools` be a base class that we use with `python_requires`. However, we have many projects that need to use these tools and we wanted to avoid adding a `conanfile.py` to every repository. The idea was to just `conan install` the `external_tools` package directly instead of having many duplicated `conanfile.py` that just reference the base recipe. The recipe for `external_tools` contains a `deploy()` method and some logic which parses a config file in the repository. I realize that adding `visible=True` to enable us to do this might not be ideal, but that's how we ended up here.

We primarily rely on our own CI/CD system to build the binaries, and not the pre-built ones from ConanCenter. Once a binary is built we are happy to use it forever, and we are worried about the stability if all of a sudded Conan decides that it needs new binaries. I guess the answer here is to just use a lockfile?

Thank you for your help.

**Comment by memsharded** [comment]
> conan install the external_tools package directly instead of having many duplicated conanfile.py that just reference the base recipe. The recipe for external_tools contains a deploy() method and some logic which parses a config file in the repository. I realize that adding visible=True to enable us to do this might not be ideal, but that's how we ended up here.

Thanks for the feedback.
Directly installing something like this is possible, it is not a bad flow per-se, I was just trying to understand the usage.
But maybe in those case the recommendation could be to do:
```bash
conan install --tool-requires=external_tools ...
```
Instead of ``--requires``. Because it will put those tools in the "build" context, which can also affect how the generators like ``VirtualBuildEnv`` behave, and overall aligns much better when the package is used from other recipes as ``tool_requires("external_tools/...")``

For your command line use case the ``visible=True`` might not be bad, you might keep using it.


> We primarily rely on our own CI/CD system to build the binaries, and not the pre-built ones from ConanCenter. Once a binary is built we are happy to use it forever, and we are worried about the stability if all of a sudded Conan decides that it needs new binaries.

This is perfectly fine, it is great, it is the recommended way in https://docs.conan.io/2/devops/using_conancenter.html to use packages from ConanCenter in production and achieve more stability.

But it seems that you are just building the binaries, but still having the dependency on ConanCenter for the recipes. By building them from a fork of ``conan-center-index`` recipe, which is not difficult, and we will be also adding tools in 2.1 to help with this, then you can get perfect control, no need of lockfiles, because you will update your fork and re-build your binaries when you want, and without affecting your main CI pipelines for your products. Please let me know if you want more details how to do this, I think it can be a good solution for your use case.

**Comment by realbogart** [comment]
@memsharded  Right, that makes sense! I think that answers all of our questions for now. Forking `conan-center-index` sounds interesting but we decided to go with lockfiles for now. 

Thank you for all the help!

**Comment by realbogart** [comment]
@memsharded  Actually, one more thing that I forgot to mention. The reason why we are using `--requires` instead of `--tool-requires` is that we were unable to pass options to `external_tools`  when we used `--tool-requires`.

The `external_tools` recipe contains the following:
```
    options = {``
        "ToolRequiresFilter": ["ANY"]
    }

    default_options = {
        "ToolRequiresFilter": ""
    }
```

We then pass something like this on the command line `-o *:ToolRequiresFilter=cmake`. When using `--requires` it picks up the option and can use it, but when using `--tool-requires` it doesn't see the value passed in for some reason. Is this maybe a bug in Conan?

**Comment by memsharded** [comment]
> We then pass something like this on the command line -o *:ToolRequiresFilter=cmake. When using --requires it picks up the option and can use it, but when using --tool-requires it doesn't see the value passed in for some reason. Is this maybe a bug in Conan?

Recipes can define options for its tool-requires with ``default_build_options`` (similar to ``default_options`` for host dependencies).
Also options that you define in the built context with ``-o:b option=value`` (``--option:build option=value``) will be applied for tool-requires. Note this is the same for ``-s:b`` settings and ``-pr:b`` profiles. Tool-requires get the information of the "build" context.

**Comment by realbogart** [comment]
That worked! Thanks again!👍
