### ISSUE TITLE
[question] Struggling with compatibility() method

### ISSUE THREAD

**Issue by db4** [conan-io/conan#15443]
### What is your question?

Consider the following test recipes:

pkg1.py
```python
from conan import ConanFile


class Pkg1Conan(ConanFile):
    settings = "os", "compiler", "arch", "build_type"

    def compatibility(self):
        return [{"settings": [("build_type", "Release")]}]
```

pkg2.py
```python
from conan import ConanFile


class Pkg2Conan(ConanFile):
    settings = "os", "arch", "build_type", "compiler"

    def requirements(self):
        self.requires("pkg1/1.0")
```

Create the packages with
```
conan create pkg1.py --name pkg1 --version 1.0
conan create pkg2.py --name pkg2 --version 1.0 -s build_type=Debug
```
and the second command fails with `ERROR: Missing prebuilt package for 'pkg1/1.0'`. Why? Am I missing something obvious?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your question.
I assume this is 2.0, and also that this problem is happening in Windows, isn't it?

The ``compatibility()`` that you might need for ``msvc`` Windows compiler is:
```python
def compatibility(self):
        return [{"settings": [("build_type", "Release"),
                                       ("compiler.runtime_type", "Release")]}]
```

The issue is that the package is created with both build-type Release and also it links the VS runtime in release
If msvc allowed it, it would also work with explicit:
```
conan create pkg2.py --name pkg2 --version 1.0 -s build_type=Debug -s compiler.runtime=Release
```

Note that the default ``profile.py`` plugin automatically fills the ``compiler.runtime=build_type`` when it is not defined, because in the vast majority of cases, it should align.

**Comment by samuel-emrys** [comment]
I'm not sure about in recipes as simple as this, but when experimenting with this in the `doxygen` recipe, I found that the way in which a dependency influences the package id of the consumer matters. I had to set `self.info.requires.minor_mode()` to break this: https://github.com/conan-io/conan-center-index/pull/18415/files#diff-cbfb36af247c5a661634bfa630c3f276104e89b382d6a6a1335e62e4b2d99930R67

I would be keen to see if changing your second command to the following fixes your issue:

```
conan create pkg2.py --name pkg2 --version 1.0 -s "&:build_type=Debug"
```

which would leave you with `pkg1/*:build_type=Release` and `pkg2/*:build_type=Debug`

**Comment by db4** [comment]
Hi @memsharded
Oh yes, you are right, it's msvc, so setting `compiler.runtime_type` is a must. Thank you very much.
There is a related question. The following doesn't work:
```python
from conan import ConanFile
from conan.errors import ConanInvalidConfiguration


class Pkg1Conan(ConanFile):
    settings = "os", "compiler", "arch", "build_type"

    def validate(self):
        if self.settings.build_type == 'Debug':
            raise ConanInvalidConfiguration(f"{self.settings.build_type} build is not supported")

    def compatibility(self):
        return [{"settings": [("build_type", "Release"),
                              ("compiler.runtime_type", "Release")]}]
```
(`pkg1/1.0: Invalid: Debug build is not supported`), should it?

**Comment by db4** [comment]
Hi @samuel-emrys 
I borrowed
```python
    def compatibility(self):
        return [{"settings": [("build_type", "Release")]}]
```
from CCI doxygen recipe :) Probably, it should be fixed as well according to @memsharded recommendations?

**Comment by memsharded** [comment]
> rom CCI doxygen recipe :) Probably, it should be fixed as well according to @memsharded recommendations?

It depends. The thing is that Debug-Release compatibility is not a thing in Windows in general, so that should be at least conditioned to the compiler/OS? Also it depends if it just the tool, it is not an issue, the build-profile will tell to install Release in the general case too, irrespective of host build-type. If it is for a library to be linked, probably shouldn't be there in ConanCenter either and per-package settings is preferred if that is the case, not having that in every recipe.

**Comment by memsharded** [comment]
@db4 the ``validate()`` above is correct, and it is expected to fail. It is stating that this package cannot work for a Debug configuration (consumer configuration). If you want to define that the Debug package of this package can't exist, then the ``validate_build()`` method is necessary:
```python
           def validate_build(self):
                    if self.settings.build_type == 'Debug':
                        raise ConanInvalidConfiguration(f"This package can't be built in Debug mode")
```

**Comment by db4** [comment]
@memsharded thanks a lot again!
