### ISSUE TITLE
[bug] Invalid package folder when using editable package with library in subfolder

### ISSUE THREAD

**Issue by Holt59** [conan-io/conan#15440]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: MSVC 19.36.32535.0
* Conan version: 2.0.16
* Python version: 3.10.5

### Steps to reproduce

When trying to use a package installed in editable mode, if the package is organized as follows:

```
src/
    CMakeLists.txt
    library.cpp
include/
    library.h
CMakeLists.txt
conanfile.py
```

The library is not found when trying to use it. 

The issue is that the library is built at `build/src/Debug/library.lib` instead of `build/Debug/ilbrary.lib` so `library_LIB_DIRS_DEBUG` is incorrect in the generated `.cmake` file.

The following repository reproduces the issue: https://github.com/Holt59/conan-issue-15440 

```
conan add editable say
cd say
conan install . -s build_type=Debug
cmake --preset conan-default
cmake --build --preset conan-debug
cd ../hello
conan install . -s build_type=Debug
cmake --preset conan-default  # this fails
```

**Comment by memsharded** [comment]
Hi @Holt59 

Thanks for your report, and many thanks for putting a reproducible case, that really helps!

This doesn't seem a bug in Conan. The problem is that the ``layout()`` of the ``say`` package doesn't match your project ``CMakeLists.txt``. The default ``cmake_layout()`` assumes a one-level structure of binary directories, if your nested ``add_subdirectory()`` create nested folders for each subdirectory, then the layout doesn't match. There are 2 ways to define this:
- Adapt the recipe ``layout()`` method and customize it to represent your project layout
- Modify the project CMakeLists.txt script to put libraries of the different subdirectories in the same place

In your repo I have tried to do:
```cmake
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
add_subdirectory(src)
```
And it works fine now. Please try it and let us know. Thanks!

**Comment by memsharded** [comment]
Any further feedback here? Did the above clarify the issue?

**Comment by Holt59** [comment]
> Any further feedback here? Did the above clarify the issue?

I've moved away from the project where I had the issue so this can be closed.
