### ISSUE TITLE
[question] Cannot build .sln generated by CMake

### ISSUE THREAD

**Issue by Blinue** [conan-io/conan#15454]
### What is your question?

I am following [this web tutorial](https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html) to integrate conan. The command `cmake --build . --config Release` works fine, and opening the folder with Visual Studio also works. But if I directly open `build/compressor.sln`, it fails to compile because msbuild cannot find zlib.h. Is this a design or a bug? The commands I used are as follows:

```
conan install . --output-folder=build --build=missing
cd build
cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
msbuild compressor.sln  ← fail
```
**environment:**
OS: Win10 22H2
Conan version: 2.0.17
CMake version: 3.28.1
Visual Studio version: 17.8.4

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Blinue 

Thanks for your question.

This might be because ``msbuild`` compiles by default in Debug mode? As ``conan install`` by default install Release artifacts and prepare for Release build, this is why ``cmake --build  . --config Release`` works, the IDE also works (changing the type to Release, if you try it in Debug, it will fail too), and ``msbuild`` in command line fails, try:
```
msbuild compressor.sln /property:Configuration=Release
```

**Comment by Blinue** [comment]
> msbuild compressor.sln /property:Configuration=Release

This works, thank you! Due to various problems with vcpkg, I plan to try migrating to conan, thank you very much for your excellent work!

**Comment by memsharded** [comment]
Thanks for the feedback!
Don't hesitate to open new tickets for any further question or issue that you might have.
