### ISSUE TITLE
[bug] Visual Studio Intellisense is broken in clang-cl projects

### ISSUE THREAD

**Issue by Blinue** [conan-io/conan#15463]
### Environment details

* Operating System+version: Win10 22H2
* Compiler+version: Visual Studio 17.8.4
* Conan version: 2.0.17
* Python version: 3.11.1

### Steps to reproduce

1. Change working directory to [simple_cmake_project](https://github.com/conan-io/examples2/tree/main/tutorial/consuming_packages/simple_cmake_project)
2. Create clang.profile with the following content:
```
[settings]
os=Windows
arch=x86_64
compiler=clang
build_type=Release
compiler.version=16
compiler.cppstd=gnu17
compiler.runtime=static
compiler.runtime_version=v143

[conf]
tools.cmake.cmaketoolchain:generator=Visual Studio 17
```
4. Generate sln
```bash
conan install . --output-folder=build --build=missing -pr clang.profile
cd build
cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
```
5. Open build/compressor.sln, switch to Release configuration. The project can be successfully compiled, but Intellisense is broken.
![image](https://github.com/conan-io/conan/assets/34770031/8353eb6c-f31c-4f33-9be1-5bf0adefaae4)

\<AdditionalIncludeDirectories\> is missing when using clang-cl as compiler, and this is probably why Intellisense does not work.

**Comment by memsharded** [comment]
Hi @Blinue 

Thanks for your report.
I am afraid that this is not a Conan issue, but a CMake<->VS issue

Because the project builds and executes:
```
$ cmake --build . --config Release
... builds ok
$ Release\compressor.exe
Uncompressed size is: 207
Compressed size is: 19
ZLIB VERSION: 1.2.11
```

Furthermore, the project builds and re-builds correctly in VS IDE too.
Also, the syntax highlighting works fine for msvc compiler and not clang, for exactly the same Conan inputs (same Zlib target, same include paths)

So I cannot find anywhere where this could be fixed within Conan and seems to belong in the intersection of CMake and VS (both Intellisense and clang-cl compiler). I suggest reporting to them, and I think this issue can be closed here. Thanks for the feedback!

**Comment by Blinue** [comment]
Thank you for your investigation, I found that this error was caused by /external:I, which Intellisense broke support for again. I have found a temporary workaround to prevent CMake from generating /external:I, see https://discourse.cmake.org/t/imported-projects-dont-resolve-include-paths-in-intellisense/9185.
