### ISSUE TITLE
[question] Can I use other languages with Conan ?

### ISSUE THREAD

**Issue by emina-mirvic-bl** [conan-io/conan#15469]
### What is your question?

Is it possible to use Conan 2.0 with other languages except C and C++ ?
In Conan 1.* python and go are mentioned, but in a new documentation there is nothing about it: https://docs.conan.io/1/howtos/other_languages_package_manager.html
I am wondering why ?
Thank you in advance for your answer. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @emina-mirvic-bl 

Thanks for your question.
Yes, Conan 2.0 is even more flexible and customizable than 1.X, so it is possible to use it to package different things, and we keep having users in 2.0 that package data, python, matlab, labview, java, os-like binary images and many more.
It is removed from the docs because the docs have been re-written from the scratch and time is limited, and there are still many other priorities to complete docs.

**Comment by memsharded** [comment]
Closing this ticket as responded, don't hesitate to create new tickets for any further question, thanks!
