### ISSUE TITLE
[bug] CMake fails to find proper protoc app

### ISSUE THREAD

**Issue by gouriano** [conan-io/conan#15495]
### Environment details

I believe the following is a bug. And, if not, I would appreciate any advice.

Operating system is Ubuntu (any Unix, probably)
conan: 2.0.17
cmake 3.28.1

### Steps to reproduce

I want to install protobuf package, but I also have protoc app in PATH - in /usr/bin/protoc
The problem is that CMake always finds the one in PATH, and never - the one in Conan cache.

I have the following conanfile.txt:

    [requires]
    protobuf/3.21.12
    [generators]
    CMakeDeps

and CMakeLists.txt:

    cmake_minimum_required(VERSION 3.15)
    project(conanapp)
    set(CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR})
    find_package(protobuf REQUIRED)
    get_property(_PROTOC_APP TARGET protobuf::protoc PROPERTY IMPORTED_LOCATION)
    message(FATAL_ERROR "_PROTOC_APP = ${_PROTOC_APP}")

I do:

    mkdir build
    cd build
    conan install .. --build missing -of .
    cmake .. -DCMAKE_BUILD_TYPE=Debug

and see:

    _PROTOC_APP = /usr/bin/protoc

The problem seems to be in find_program(PROTOC_PROGRAM NAMES protoc) call in

    ${CONAN_HOME}/p/b/protod17df02793082/p/lib/cmake/protobuf/protobuf-generate.cmake

But I have no idea how fix it. I tried to set CMake "ignore path" variables, but they do not seem to have any effect.
Maybe this behavior is by design...? The problem is that the "default" protoc is too old, and I have no power to change that.

**Comment by memsharded** [comment]
Hi @gouriano 

Protobuf version of the library must be the same than the ``protoc`` executable, which is something complicated if using the system path.

I assume that you want to use the Conan ``protoc`` executable, so it keeps aligned with the library. You can do it with:

```
[requires]
protobuf/3.21.12
[tool_requires]
protobuf/3.21.12
[generators]
CMakeDeps
CMakeToolchain
```
(Recall that ``CMakeToolchain`` is recommended in most cases)

With this, Conan will create a ``conanbuild.bat|.sh`` file that can be activated and it will put ``protoc`` executable from the Conan package in the path with higher precedence.

is this what you mean? Can you please give it a try?

You have this example in code, with a ``conanfile.py``, that is related to this: https://docs.conan.io/2/examples/graph/tool_requires/using_protobuf.html

**Comment by memsharded** [comment]
Some other side notes:

If using ``cmake .. -DCMAKE_BUILD_TYPE=Debug`` to build debug, you should do ``conan install .. --build missing -of . -s build_type=Debug``, otherwise dependencies will not be found correctly.

Also, ``-of`` should be optional for most cases, to specify different layouts, it is recommended to use a ``conanfile.py`` recipe with a ``layout()`` method.

As suggested above, it is more recommended to use the ``CMakeToolchain`` and avoid doing ``set(CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR})``

The conan package containing ``protoc`` will not define the target, but ``protoc`` will be put in the path. You can probably use ``find_program()`` but ``get_property(_PROTOC_APP TARGET protobuf::protoc PROPERTY IMPORTED_LOCATION)`` will probably not work

**Comment by gouriano** [comment]
So, I add _tool_requires_, do _conan install_, then _source conanbuild.sh_, and "which protoc" says
${CONAN_HOME}/p/b/protod17df02793082/p/bin/protoc
And **now** my unchanged CMakeLists.txt says the same: 
_PROTOC_APP = ${CONAN_HOME}/p/b/protod17df02793082/p/bin/protoc
Ok. Thanks...
Not a bug then.

**Comment by memsharded** [comment]
Good to know, then I think we can close the issue. 
Don't hesitate to create new tickets for any further question, thanks!
