### ISSUE TITLE
[question] lockfiles: conan install requires root dependency to be locked

### ISSUE THREAD

**Issue by nicosmd** [conan-io/conan#15506]
### What is your question?

Hey, I have a question about lockfiles in conan2. I'm on current latest version 2.0.17.

When I create a lockfile for an app like

```
conan lock create . --lockfile-out conan.lock
```

and I want to use the produced lockfile somewhere else in order to install that package using the lockfile, I expected 

```
conan install --requires=app/1.0 --lockfile conan.lock --lockfile-out new.lock
```

to work. But instead conan is complaining about that the app can't be found in the lockfile. Now, I can add a --lockfile-partial to make it running but it feels wrong as I know, that all requirements are in the lockfile except the entry for the app itself and I don't want other not locked dependencies to sneak in. 

It feels that I have some misconception how to evolve and use lockfiles. How would the right flow look like so that I can rebuild the app somewhere else with the previously created and potentially evolved lockfile?

Thank you very much!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nicosmd 

Thanks for your question.

When you do 
```
conan lock create . --lockfile-out conan.lock
```
I suggest to have a look to the content of the generated ``conan.lock`` file (it is json)

It will not contain a reference to ``app`` at all. Why? Because the ``app`` package doesn't exist at all. It hasn't been created, it didn't get its version (can be dynamic with ``set_version()``), and it was definitely impossible to compute its recipe-revision, as it hasn't been exported to the cache yet. So it will only be capable of locking the dependencies of the current ``conanfile`` (it also works with a ``conanfile.txt`` that doesn't even define name or version)

If you want to capture the lockfile that includes the ``app`` package, you have several different options, but the core idea is that the ``app`` package must have been exported or created:
- First ``conan create `` + ``conan lock create --requires=app/version ...``
- ``conan create . --lockfile-out=conan.lock``
- ``conan export . `` + ``conan lock create --requires=app/version`` + ``conan install --requires=app/version --lockfile=conan.lock --build=missing``

Please let me know if this helps, give it a try and let me know. Thanks!

**Comment by nicosmd** [comment]
Thank you very much @memsharded , that makes totally sense and works like a charm. I wanted to avoid to build anything when creating the lockfile but it makes sense that I need to do it.
