### ISSUE TITLE
[question] Express a weak dependency?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#15524]
### What is your question?

Suppose I have `pkg_a` that can use `pkg_b` (e.g. `pkg_b` is a dll that can be used by `pkg_a` but is not strictly necessary), and `pkg_c` that strongly **requires** `pkg_b`. Can I describe this with Conan? I would like `pkg_a` to check the whole graph and report a conflict if there is `pkg_b` of an incompatible version. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Not sure what you mean

>  I would like pkg_a to check the whole graph and report a conflict if there is pkg_b of an incompatible version.

You can check dependencies versions and raise ``ConanInvalidConfiguration`` in the ``validate()`` method of ``pkg_a``, is this what you want?

In general, Conan is imperative, if ``pkg_a`` wants to use ``pkg_b`` it needs to declare as dependency. It can be optional, managed with ``options`` or conditional to the platform, but there is someone deciding if it wants to use it ``pkg_b`` or not. But if it is not ``required``, then it will not be a dependency.

**Comment by db4** [comment]
Hi @memsharded

> In general, Conan is imperative, if `pkg_a` wants to use `pkg_b` it needs to declare as dependency

A simpler example: `pkg/1.0` and `pkg_plugins/1.0`. I would like to avoid installing `pkg_plugins` binaries when `pkg` is installed (they are heavy and usually not necessary), but I would like to check the version compatibility of `pkg` and `pkg_plugins`. Maybe it's possible to skip `pkg_plugins` binaries when `pkg_plugins` is only directly required by `pkg`? Just an idea. I don't insist that something like that should be implemented.

**Comment by memsharded** [comment]
I am afraid this is still not very clear. Plugins, understood as extensions to a given package are not a dependency of the package, but of the consumers, so something like:

- consumer -> pkg/1.0
- consumer -> pkg_plugins/1.0

It is the full decision of the ``consumer`` to depend or not on the plugins. Also, if the consumer wants to enforce the same version for both, it can also either define the version or if there are version ranges it could verify it in ``validate()``

I am still most likely not understanding the setup

**Comment by db4** [comment]
> I am afraid this is still not very clear. Plugins, understood as extensions to a given package are not a dependency of the package, but of the consumers, so something like:
> 
>     * consumer -> pkg/1.0
>     * consumer -> pkg_plugins/1.0

Exactly. pkg/1.0 and pkg_plugins/1.0 are compatible so everything is good. But what if one would require pkg/2.0 and pkg_plugins/1.0 together? Conan won't detect any conflict so a runtime error (or crash) will happen. Of course, I can check compatibility in consumer's `validate()` but it's not very convenient for big graphs; after all, it's pkg who knows which version of pkg_plugin is acceptable or not.

**Comment by memsharded** [comment]
> Of course, I can check compatibility in consumer's validate() but it's not very convenient for big graphs; after all, it's pkg who knows which version of pkg_plugin is acceptable or not.

I see. But I think it is the opposite in most scenarios. It is the plugins that know to which ``pkg`` versions they are compatible with. Because ``pkg_plugins`` development comes after ``pkg``, they cannot exist without ``pkg`` and they are designed, built and tested against one or several ``pkg`` versions, not the other way around.

It is also common that plugins need at build time some interface defined in the ``pkg`` package. If that is the case, the ``pkg_plugins`` -> ``pkg`` dependency with a version range will be the one that would be raising conflicts if the versions are not aligned.

The problematic scenario is that both packages don't have visibility over each other, in this case the ``pkg_plugins`` package can be developed without any dependency at all to the ``pkg`` package, and then the two packages will be basically independent "siblings" in the graph, and neither of them will have visibility over the other, packages only have visibilities over their dependencies.

Things that I would try for this problem:
- Check if it makes sense to define a ``pkg_plugins`` -> ``pkg`` dependency
- If there is not, let them be independent siblings in the graph. Define some general policy to use the same version ranges for both, so versions are naturally aligned
- If you want to detect versions incompatibilities you could do it:
  - In some consumers ``validate()``
  - Added as an external ``deployer`` (can be used to check in CI, for example, without polluting recipes)

**Comment by db4** [comment]
@memsharded, thanks for your suggestions. When I opened this issue, I thought it would make sense to support such kind of dependency directly on the recipe level. Something like `self.requires("pkg_plugins/[~1.0]", constrain=True)`. We already have `override` trait that doesn't create a direct dependency. `constrain` trait could be used just to check the graph for a possible conflict. I don't know how hard it is to implement this, but the feature seems convenient.

**Comment by memsharded** [comment]
>  I thought it would make sense to support such kind of dependency directly on the recipe level. Something like self.requires("pkg_plugins/[~1.0]", constrain=True). We already have override trait that doesn't create a direct dependency. constrain trait could be used just to check the graph for a possible conflict. I don't know how hard it is to implement this, but the feature seems convenient.

It is not just challenging, at this moment is almost physically impossible. The graph is expanded depth-first. If the other "plugins" package is not a dependency, and just comes as a sibling or in a sibling branch, it is possible that such branch hasn't be expanded yet, that means the ``pkg_plugins`` will not even exist yet when that ``requires()`` execute, and the requires is only able to propagate up to its dependencies. The ``override`` only influences its dependencies, never down the graph or in parallel branches, that is more manageable, something that would need to propagate along the whole graph would be extremely complex to implement, and might also have much higher computational cost.

**Comment by db4** [comment]
Thanks for the detailed explanation, closing the issue.
