### ISSUE TITLE
[question] Artifactory Integration, mirror source instead of just recipe

### ISSUE THREAD

**Issue by haleyk10198** [conan-io/conan#15547]
### What is your question?

Hi, I am trying out Conan 2.0.17 at my workplace. The firewall forbids our UAT & PROD to communicate with external websites unless explicitly whitelisted. For Conan-Center remote, we have mirrored it using Artifactory to workaround that rule. However, recipes may contain dependencies that are hosted externally, e.g. bzip2 is hosted on sourceware.org, which is not on the whitelist. So whenever I try to install bzip2 it prompts urllib3 failing DNS lookup. While I could apply for a whitelist, it's counter-productive to do so per new dependency host added. Instead, I could see there are two common workarounds that other pkg-manager / build-tools take, yet I am not aware of its counterpart in Conan.

- Is it possible to set artifactory plugins to mirror sources in place of the consumer? 
- Is it possible to manually specify proxy mappings, in our artifactory `github.com` is mapped under `github-release`

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @haleyk10198 

Thanks for your question.

I think you might want to have a look to https://docs.conan.io/2/devops/using_conancenter.html, where for these cases, it would be recommended to build your own binaries from your ``conan-center-index`` fork. If you have those strong security requirements that you can't communicate with external sites, I think that your policies wouldn't recommend to use pre-compiled binaries from the internet either.

When building your own binaries, then there would be a couple of mechanisms that can be done for ``conan-center-index`` recipes:

The first, one is to automate the sources copy, by scanning the ``conandata.yml`` metadata files in the repo. They contain the URLs of the sources, so you can download them, store those tarballs in your own server, then change the ``conandata.yml``. When you do the ``conan create`` to create your packages, it will be using your own copy.

We have also automated that flow with the ``sources-backup`` feature. Please have a look to:
- https://blog.conan.io/2023/10/03/backup-sources-feature.html
- https://docs.conan.io/2/devops/backup_sources/sources_backup.html

Conan is able to do a backup of the sources the first time they are needed to build, then when the packages are uploaded, it will automatically upload them with the packages. It is true that the first time it needs access to the internet to download the tarball, but that would be the same that if you do the task manually as described above.

In Artifactory it is not possible to do anything in the Conan repos, because these requests are not routed through Artifactory, they go from the client to the server. If you own your network firewall/router, you might implement there some routing rules.

**Comment by memsharded** [comment]
Closing this ticket as responded, don't hesitate to create new tickets for any further question, thanks!
