### ISSUE TITLE
[question] How to make dependency of dependency unvisible

### ISSUE THREAD

**Issue by xyz1001** [conan-io/conan#15559]
### What is your question?

I have a shared library A, which depend spdlog/1.13.0, and spdlog depend fmt/10.2.1. A make spdlog unvisible with `visisble=False`. Now another B depend A and fmt/8.1.1, which will cause conflict. 

> │ERROR: Version conflict: spdlog/1.13.0->fmt/10.2.1, B/None->fmt/8.1.1

How to totally hide dependencies like `self.build_requires("spdlog/1.13.0", force_host_context=True)` in conan 1.x. The library A is shared library and hide all denpendencies symbols, I am sure that this behavior will not cause any problems.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @xyz1001 

Thanks for your question.

The first important thing to consider is that in most cases in C and C++ it is not possible to ignore the conflicts, because basically it is not possible to link together 2 different libraries for the same code. These conflicts are preventing later and more challenging problems at link time or even worse, at runtime.

Even in the cases where there is full hiding of a dependency, like a shared library linking a static library as a pure implementation detail, making sure it doesn't leak any API or ABI, it is still recommended to depend on the same version of the transitive dependency when there are diamond structures in the graph.

For the exceptional cases where we want to hide the transitive dependency, under the user responsibility, it would be the ``private=True`` argument in Conan 1.X, which is not recommended in most cases, it has its challenges, and using the new ``visible=False`` trait in Conan 2.0 (but making sure using ``self.requires(..., visible=False)``, not build-requires)

**Comment by xyz1001** [comment]
My shared library A has beem mark spdlog/1.13.0 as unvisible with `self.requires("spdlog/1.13.0", visible=False)`. However
 another library B which depend A and fmt/8.1.1 still has conflict.

**Comment by memsharded** [comment]
Could you please provide something that we can reproduce? Providing a few very simple ``conanfile.py`` files, and instructions to reproduce really helps.

Please also report your Conan version, OS, etc.

**Comment by xyz1001** [comment]
Here is the demo repo: https://github.com/xyz1001/conan_hide_dependency
reproduce command:
`cd a && conan create .`
`cd .. && cd b && conan create .`

conan version: 2.0.17
OS: macOS 14.2.1

**Comment by memsharded** [comment]
Thanks very much for the reproducible case, it really helped a lot! 🙂 

There was indeed an unfortunate subtle bug that happens when the transitive library behind ``visible=False`` is a header-only library that has transitive dependencies. 

I have submitted already a PR in https://github.com/conan-io/conan/pull/15564 that hopefully fix it for next release (2.1 most like, but we don't discard a 2.0.18 yet).

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/15564 has been merged, it will be in next release

**Comment by xyz1001** [comment]
Thank you very much.
