### ISSUE TITLE
[question] Is there a way to run the cmake.configure without cmake.build?

### ISSUE THREAD

**Issue by RochaStratovan** [conan-io/conan#15565]
### What is your question?

# Is there a way to run the `build` method's `cmake.configure` without `cmake.build`?

I read the [2.0 Package Development Flow](https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html)

Which I summarize as follows:

1. `conan source .` will cause the `source` and `layout` methods of the recipe to be used. It causes the local source code to be updated/setup.

1. `conan install .` will cause the `generate` and `layout` methods of the recipe to be used. It's purpose is to ensure packages that we depend upon are installed in the local cache and create the conan toolchain, etc.

1. `conan build .` will configure the build infrastructure and then compiling it.

This is similar to what our manual work flow is, however, we've split the the `conan build` step into two. (1) Creating the build infrastructure and (2) compiling it.

We develop products for both Windows and Linux, and some of the products are on both platforms. We have are approximately a 50/50 split between Windows and Linux developers.

The Windows developers strongly prefer to compile via Visual Studio's IDE. For package development they want the ability to use CMake to generate their VS solution file, do their editing and compilation in VS, and then when the changes are ready for commit, do the complete recipe `build`.

In short, they don't want to wait for the projects to build via the command line.

Is there a way to split this functionality without having them comment the `cmake.build` line from the recipe's `build` method?

I thought about moving the `cmake.configure` logic to the recipe's `generate` method. Then this would become part of the `conan install` step. However, I'd prefer to not have this bound to a step that might also update my dependencies.

I'm toying with the idea of adding a custom setting like `build_action` that can be `config_only` or `all` [default]. I think this might be possible by extending the settings, and then the `build` method can check `build_action` and stop after `cmake.configure()`. Then I believe this could be controlled with an `-s build_action=config_only` command line option.

Is there a better way to do this?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @RochaStratovan 

Thanks for your question.

The "canonical" flow in Conan 2.0 is ``conan install`` + "native build system" steps. All the ``generate()`` logic is intended to allow developers to use the standard build system flow, in the case of cmake, it would be both cmake configure (which can be as short as ``cmake --preset conan-default``) and cmake build. This is also designed this way because in many cases, it won't even be necessary to do that, for example I configure and build with VS Code cmake-tools plugin directly after ``conan install``, no need for Conan to execute the cmake configure step, because the extension is already doing it.

> I thought about moving the cmake.configure logic to the recipe's generate method. Then this would become part of the conan install step. However, I'd prefer to not have this bound to a step that might also update my dependencies.

That sounds possible, and we have been also considering this possibility, to add a ``pre-build()`` method or the like that executes after ``generate()``. But mostly it would be the equivalent to running it when ``conan install`` is called (and it will only contain the call to ``cmake.configure()`` typically, but not the ``cmake.build()``)

> I'm toying with the idea of adding a custom setting like build_action that can be config_only or all [default]. I think this might be possible by extending the settings, and then the build method can check build_action and stop after cmake.configure(). Then I believe this could be controlled with an -s build_action=config_only command line option.

Yes, settings are not the recommended way to do this. ``settings`` and ``options`` should only be added when they really affect the final packaged binary, not for this kind of ux configuration. For this purpose you can use the ``conf`` system, that allows defining things like ``-c user.myteam:skip_build=True`` in the command line or in the profile, and then the recipes can do just a:
```python
if not self.conf.get("user.myteam:skip_build", check_type=bool):
     cmake.build()
```
       
Note that if you put it in every recipe, and you intend to build dependencies with ``--build=missing`` it will break the dependencies build, so you'd want to do ``-c &:user.myteam:skip_build=True`` to only affect the current consumer recipe, not the whole graph.

**Comment by RochaStratovan** [comment]
Thank you for clarifying! I got so wrapped in `conan` I was thinking we would just use `conan` as the command layer.

We cannot use conan's VSCode solution because we have very advanced CMakefiles that do things we need. So we must go through CMake for Windows and Linux.

Well, I suppose, I could figure out how to get this to work with pure VS Code configuration modifications, but we solved that long ago with `cmake` and don't want to go through that effort again.

**Comment by memsharded** [comment]
> Thank you for clarifying! I got so wrapped in conan I was thinking we would just use conan as the command layer.

Yeah, I understand that :) that is why we were also considering the possibility of doing the cmake generate step at ``conan install`` time, which can be convenient too. If you want to give a try to the ``generate()`` approach, it is not that bad, it you do it, please let us know, it can be very valuable feedback for considering a future feature built-in. Just a couple of hints if you are going to try:

- Do ``cmake = CMake(self) + cmake.configure()`` as the very last steps in ``generate()``
- Do a explicit instantiate of the generators you need plus call ``xxx.generate()`` for each of them
- If you are using ``tool_requires`` you might need to also instantiate explicitly ``VirtualBuildEnv(self).generate()``

**Comment by RochaStratovan** [comment]
😡 😡 AAAARRRRGGGGHHHHH!

I was editing the top-level `conanfile.py` file not `test_package/conanfile.py`
