### ISSUE TITLE
Packaging header only library with conan 2

### ISSUE THREAD

**Issue by lstoffer** [conan-io/conan#15569]
### What is your question?

Hi! I have a question regarding packaging a header only library with conan2 and cmake:
We have implemented the following `generate()` method to generate the conan_toolchain.cmake file:
```python
def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()
```

The `package()` function looks as follows:
```python
def package(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.install()
```

Using this everything seems to work on linux. However, on Windows we get the following error messages stating that the `CMAKE_C_COMPILER`, `CMAKE_CXX_COMPILER` and `CMAKE_MAKE_PROGRAM` couldn't be found.

```
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

The question is, why these settings are even necessary for a header only library. Is there a possibility to configure everything in a way that those are not required? Or are we doing something completely wrong?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lstoffer 

Thanks for your question.

The thing is that if you are using CMake, it still needs configuration to work properly, that is, you need to define ``settings = "os", "compiler", ...`` like other packages. Then as it is a header-only, you can do ``self.info.clear()`` in its ``package_id()`` method.

Otherwise, for header-only it is typically much simpler and faster to do a couple of ``copy()`` calls in the ``package()`` method.
