### ISSUE TITLE
conan.settings is ignored.

### ISSUE THREAD

**Issue by mikea** [conan-io/conan#1558]
I am trying to build conan package with emscripten. I tried changing conan.settings according to documentation but I can't make conan see it:

```
$ pip search conan
conan (0.25.1)                     - Conan C/C++ package manager
  INSTALLED: 0.25.1 (latest)
conan_ldap_authentication (0.1.3)  - LDAP authenticator for Conan C/C++ package manager
conan_package_tools (0.5.3)        - Packaging tools for Conan C/C++ package manager

$ cat ~/.conan/conan.settings
os:
    Linux:
arch: [emcc]
compiler:
    emcc:
       version: ["5.10", "5.11", "5.12", "5.13", "5.14"]
       threads: [None, posix]
       libcxx: [libCstd, libstdcxx, libstlport, libstdc++]

build_type: [Debug, Release]

$ cat src/emscripten.profile
[settings]
compiler=emcc

$ conan install src --build=missing --profile src/emscripten.profile
ERROR: Invalid setting 'emcc' is not a valid 'settings.compiler' value.
Possible values are ['Visual Studio', 'apple-clang', 'clang', 'gcc', 'sun-cc']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

```

**Comment by memsharded** [comment]
The file with the settings is ``$ cat ~/.conan/settings.yml``

**Comment by mikea** [comment]
@memsharded my fault. Not sure where I got the `conan.settings` file name. Seems to work with `settings.yml`. I only wish there was a way to specify settings.yml in command line. Distributing the file among the time otherwise might be tedious.

I'll try to let you know if I am successful using emcc with conan.

**Comment by mikea** [comment]
@memsharded it looks like distributing settings is a bigger problem than I thought. Apparently if I write `if self.settings.compiler == "emcc"` in `conanfile.py`, then conan complains if emcc is not in settings:

```
17:31:50.909 	if self.settings.compiler == "emcc":
17:31:50.909 	ConanException: Invalid setting 'emcc' is not a valid 'settings.compiler' value.
```

This means that even if you are not interested in emcc builds (most people in our team) you still have to have proper `settings.yml` file.

**Comment by memsharded** [comment]
No worries :)

Yes, settings.yml are used to validate inputs and recipes, because otherwise, if it would do a normal string comparison, typos like ``self.settings.compiler == "emc"`` or ``Emcc`` or whatever will be inconvenient to debug. Same for options.

Regarding the distribution of settings.yml, I totally agree. We are considering different ways to sync teams, regarding settings, remotes, and configuration, and it will become a conan feature. Not high priority, because it has an easy workaround (just share the settings.yml with your team), but it will be a nice to have feature for teams and companies.

**Comment by mikea** [comment]
I created a PR with settings necessary for emscripten: #1565
