### ISSUE TITLE
[question]Handle precompiled headers in package_info

### ISSUE THREAD

**Issue by tomasz-wezyk** [conan-io/conan#15595]
### What is your question?

Hi, I'm using cmake build-in mechanism to generate export header file:

cmake code:

```
include(GenerateExportHeader)
generate_export_header(${PROJECT_NAME}
    EXPORT_MACRO_NAME LIBRARY_DLL_API
    EXPORT_FILE_NAME ${PROJECT_NAME}_export.h
)

target_precompile_headers(${PROJECT_NAME} 
       INTERFACE $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}/${PROJECT_NAME}_export.h>
       INTERFACE $<INSTALL_INTERFACE:include/${PROJECT_NAME}_export.h>
)
```

When I call cmake install I have (in file libraryTargets.cmake):

```
set_target_properties(<project_name> PROPERTIES
.
.
.
  INTERFACE_PRECOMPILE_HEADERS "include/<project_name>_export.h"
)
```

How can I define **INTERFACE_PRECOMPILE_HEADERS** in conan package_info?

Due to dependencies between projects I'm using conan 1.x (1.62).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @tomasz-wezyk 

Thanks for your question.

This is not directly possible (fully automated) with the current CMake integration.

The reason is that this is discouraged in the general case. From https://cmake.org/cmake/help/latest/command/target_precompile_headers.html#command:target_precompile_headers

> Projects should generally avoid using PUBLIC or INTERFACE for targets that will be [exported](https://cmake.org/cmake/help/latest/command/install.html#export), or they should at least use the [$<BUILD_INTERFACE:...>](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:BUILD_INTERFACE) generator expression to prevent precompile headers from appearing in an installed exported target. Consumers of a target should typically be in control of what precompile headers they use, not have precompile headers forced on them by the targets being consumed (since precompile headers are not typically usage requirements).

So Conan does not have a mechanism to propagate precompiled headers from dependencies packages to consumers.

If you still want to try this, I'd probably recommend the ``cpp_info.set_property()`` mechanism:
- The package ``conanfile`` can define its own properties, like ``self.cpp_info.set_property("precompiled_headers", [list, of headers])``
- The consumer recipe can read from its dependencies the ``self.dependencies["mydep"].cpp_info.get_property("precompiled_headers")`` and do what it wants to do with it. The recommended place would be the ``generate()`` method and you can generate .cmake files or something with the information that you want.

I hope this helps, please let me know.

**Comment by memsharded** [comment]
Any further question @tomasz-wezyk ?

If not I think we can close this ticket, you can always re-open or open new ones for any new question or issue. Thanks!
