### ISSUE TITLE
[question] How do I make a private requires/requirement?

### ISSUE THREAD

**Issue by RochaStratovan** [conan-io/conan#15603]
### What is your question?

We occasionally embed libraries inside of each other. However, when I use the child library that includes the parent library, `conan install` is pulling in both dependencies.

For example, `lib-B` embeds `lib-A` so that `lib-B` has all of its symbols as well as `lib-A`'s symbols.

I simulated this as follows:

1. Create a conan library `lib-A` and export to my local cache.

1. Create a conan library `lib-B` that uses `lib-A` and export to my local cache

   Its `conanfile.py` has logic such as:

   ```python
       def requirements(self):
           self.requires("lib-a/1.0")
   ```
1. Create a dummy exe to test lib-B.

    Its `conanfile.py` has logic such as:

   ```python
       def requirements(self):
           self.requires("lib-b/1.0")
   ```

   When I run `conan install .` at this point I see that it's pulling in both lib-A and lib-B

   ```bash
   ======== Computing necessary packages ========
   Requirements
       lib-b/1.0#2dd27db6c953354cf7435da800489d16:bafca93ddfe493a19e984d64b7e18818eb317e72#8e5d2b52a9e5670284dfbbd1af58516d - Cache
       lib-a/2.10.4#c69fd0d36d7061c6e6466a6f986b4812:9bdee485ef71c14ac5f8a657202632bdb8b4482b#b6192da7c63462357d1eb266cf3f1fc3 - Cache
   ```

How can make this not happen? I don't need `lib-A` because it's already in `lib-B`. This makes sense for a traditional library dependency but it's not what I want for my scenario.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @RochaStratovan 

There are several factors that affect how linkage requirements are propagated:

- The explicit requirements traits: https://docs.conan.io/2/reference/conanfile/methods/requirements.html#requirement-traits
- The package type https://docs.conan.io/2/reference/conanfile/attributes.html#package-type (which can in turn be deduced from option ``shared`` if existing)


If you are doing the typical shared library linking a static and fully embedding it, just defining the package-types will be enough, Conan will not propagate linkage downstream.

**Comment by RochaStratovan** [comment]
@memsharded,

Thank you.

**Package Type:**<br>I see the value of the _package type_ solution, however that is not applicable to our situation. We are embedding static library `lib-A` into **_static_** library `lib-B`. 
> _Yes, I know this not a good idea, I'm still working on convincing the deciding powers to either change to a shared library or just not do this and link with all the libs._.

**Requirements Traits:**<br>The _requirements traits_ helped me to achieve this. Especially [the video](https://www.youtube.com/watch?v=kKGglzm5ous) linked from the documentation you shared!

I was able to achieve this by modifying the `conanfile.py` for `lib-b` in two different ways:

Option 1:

```python
    def requirements(self):
        self.requires("lib-a/1.0.0",
                      transitive_libs=False,      # <<<<<<<<<<<<
                      transitive_headers=False)   # <<<<<<<<<<<<
```

Option 2:

```python
    def requirements(self):
        self.requires("lib-a/1.0.0",
                      visible=False)   # <<<<<<<<<<<<
```

Both of these achieved what I wanted.

Can you help me understand why I would choose one over the other? I read the docs for `visible` and `transitive_{headers,libs}` and I'm not quite grasping the difference.

**Comment by memsharded** [comment]
> I see the value of the package type solution, however that is not applicable to our situation. We are embedding static library lib-A into static library lib-B.

Oh, I see now. Yes, this is exactly one of the special cases for using these requirement traits, good point.
Yeah, probably not that great, but it is not the first time I have seen this, and it was one of the reasons that brought the duo ``transitive_headers/transitive_libs`` with 4 states instead of the ``public/interface/private`` with 3 states.


Even if both traits combinations achieve what you want in your current case, they are slightly different:

- The ``transitive_xxx=False`` do not propagate the headers + libs, but it does propagate the reference itself down the graph. If there are other visible ``lib-a`` dependencies down the graph with different versions, Conan will be able to raise a version conflict
- The ``visible=False`` implies that headers and libs will not be transitive, because it breaks the propagation down the graph. So ``lib-a/1.0.0`` will remain as a purely implementation detail or your package, and other packages and consumers in the graph should be able to freely use and link other ``lib-a`` versions if they want to.

I think in this case, it is more the first case, because bundled/accumulated static libraries do not really hide the dependency as implementation detail (as a shared lib linking a static one can do), and link errors will appear downstream if someone tries to link another version of ``lib-a``, so better have ``transitive_xxx=False`` while keeping the visibility so Conan can error fast and detect early these version conflicts better than having later weird link or runtime errors. 

Is this the case? please let me know if this helps.

**Comment by RochaStratovan** [comment]
I understand. Thank you for the additional details on the nuances between the two.

I agree with your thoughts that this is a visibility=True, transitive_xxx=False situation, for exactly the reasons you stated.
