### ISSUE TITLE
[question] Difference in CMakeDeps  generated files in Conan 1.x.x and Conan 2.0

### ISSUE THREAD

**Issue by hdnn** [conan-io/conan#15607]
### What is your question?

Hi! In my project I have a dependency similar to: my_app -> my_lib -> bzip2. 
**my_lib** is also a conan package.
In conan 1.x.x if I want to use bzip2 in **my_app**(CMake based), I don't need to add a bzip2 requirement in the conanfile of my_app, because it's already in conanfile of my_lib. CMakeDeps generator makes all required config files.
In conan 2.0 CMakeDeps also makes config files, but INCLUDE_DIRS variable  declared in generated .cmake files is empty until I explicitly add bzib2 requirement to conanfile of **my_app**. 

Without explicit bzip2:
![image](https://github.com/conan-io/conan/assets/8512124/e4b10aad-d5d3-4274-8c5e-3c1c7d596d66)

With explicit bzip2:
![image](https://github.com/conan-io/conan/assets/8512124/9cabbfc3-b9b3-4244-bffd-fad8ec67f28d)

Is this expected behavior, forcing me to explicitly write my dependencies, or a bug? From my point of view, either the correct file should be created or not created at all

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @hdnn 

Thanks for your question.

This is due to the default propagation of headers in Conan 2.0, which now defaults to a better SW engineering practice.
By default, headers are not transitive accross intermediate dependencies, as the best when possible is to have the headers as internal implementation detail in the package, and have them invisible to downstream consumers.

If there are packages that include the dependencies headers in their public headers, then the dependency must be declared as:
```python
def requirements(self):
     self.requires("mydep/myversion", transitive_headers=True)
```
This is one of the new traits in Conan 2.0 https://docs.conan.io/2/reference/conanfile/methods/requirements.html that allows to better model the dependencies in C and C++ packages. This talk also explain about this: https://www.youtube.com/watch?v=NM-xp3tob2Q

**Comment by hdnn** [comment]
Thank you for explanation, @memsharded
