### ISSUE TITLE
[question] Multiple packages of different version in same conanfile.txt

### ISSUE THREAD

**Issue by dev-joss** [conan-io/conan#15622]
### What is your question?

I have a project that depends on two versions of the same dependencies. Its monolith with a single build system for multiple tools so theres only a single conanfile.txt

Is there a way to have multiple packages of the same version in a single conanfile, or any tips for handling this? Can you have multiple conanfiles?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @eclazi 

Thanks for your question.

A conanfile is intended to represent one dependency graph, but if you have different applications that have different sets of versions of the same packages, then there is not 1 dependency graph, but multiple different dependency graphs, one per tool.

The best would probably be to have one different ``conanfile.txt``  per tool. There could be two approaches, you can both put them in different folders, or you could have them with different names and do ``conan install myconanfile1.txt`` for example. The problem is that the ``conan install`` generates files for your build system to locate the dependencies, so having multiple conanfiles in the same folder can be problematic, as those files would overwrite each other. It sounds that it would be much better to have one ``conanfile.txt`` per tool in a different subfolder.

If you want all conanfiles to be at the same root level, then you can write ``conanfile1.py``, ``conanfile2.py``, one per tool, and in each one write a parameterized ``layout()`` method, so the generated files goes to a different location without overwriting each other.

If you are not using generators, you might use a single ``conanfile.py``, where you can define ``requirements`` traits so they don't collide/conflict, but then using and linking with the libraries from those dependencies would be completely on your own, and it can be difficult without the generated files to locate those libraries.

Please let me know if this helps.
Relevant links:
- https://docs.conan.io/2/tutorial/consuming_packages/the_flexibility_of_conanfile_py.html
- https://docs.conan.io/2/reference/conanfile/methods/requirements.html

**Comment by dev-joss** [comment]
@memsharded thanks for your answer!
