### ISSUE TITLE
[question] Can you explain "channel" and how it would be used?

### ISSUE THREAD

**Issue by RochaStratovan** [conan-io/conan#15629]
### What is your question?

The 2.0 documentation for [Revisions](https://docs.conan.io/2/tutorial/consuming_packages/intro_to_versioning.html#revisions) identifies a revision that includes user and channel such as

```bash
pkgname/version@user/channel#recipe_revision
```

Can you provide an example for how this is used? Why this is used? What it actually means?

I searched the 2.0 documentation and found references to channel as a ConanFile [attribute](https://docs.conan.io/2/reference/conanfile/attributes.html#channel).

It's also mentioned in the `user` attribute. However, I don't understand what it actually does for us and how it should/could be used.

I ask because my manager saw this and suggested it as a solution for a branching problem where having, but I don't know what this actually does.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your question.
It is true that it could be better and more explicitly documented. I will add some notes to the docs and to the guidelines.

In short, better forget about ``channel`` and ``user`` as most as you can. 
From the docs:
> https://docs.conan.io/2/reference/conanfile/attributes.html#channel
A valid string for the channel field follows the same rules than the name attribute. This is an optional attribute. It is sometimes used to identify a maturity of the package (“stable”, “testing”…), but in general this is not necessary, and the maturity of packages is better managed by putting them in different server repositories.

Channels is mostly a historic, legacy thing from the very early days when only 1 server repository was supported. 

If using a channel, it should be something very immutable, basically always the same for the same package name if you use it. Not used for branching or anything like that, that is quite problematic, because changing the channel requires changing the dependants ``requires``, and things can become quite messy very quickly.

The recommendation is to use what basically most other package mangers in other languages, use versions/revisions and different server repositories to store different stages of binaries.

For the ``user``, it can be used to label all your own packages, to differentiate them from third party packages from ConanCenter. In general for ConanCenter it is recommended to leave the packages without user/channel, otherwise it would be necessary to modify every recipe too to change their ``requires``, not worth it.

**Comment by RochaStratovan** [comment]
Thank you for the update.
