### ISSUE TITLE
settings_defaults not working in 0.25.1

### ISSUE THREAD

**Issue by tamboril** [conan-io/conan#1563]
A team member just got 0.25.1, and all of a sudden the settings_defaults in `conan.conf` no longer
work.

Specifying the settings on the command line works correctly.

This may be related to #1298

**Comment by tamboril** [comment]
OK.  I see that this has been changed to "default profile" feature, apparently without backward compatibility.  Reading through the docs, it is not apparent to me which profile is the "default".

**Comment by tamboril** [comment]
Well, I see that there is one called `default` that had a setting that was not right.

**Comment by memsharded** [comment]
Hi @tamboril 

We added a migration, that would copy the current settings from conan.conf to that default profile, so in theory, conan should keep working and not break. Sorry if we did, probably some case we didn't consider. Could you please add more details about how we broke it? 

Maybe this issue is related, it is planned for next release, to add some command to make easier configuration of profiles, mainly for CI purposes: https://github.com/conan-io/conan/issues/1463

**Comment by tamboril** [comment]
I created a clean account (no `.conan` directory) and attempted to install a package that requires gcc 7.1.  It failed with `Error while initializing settings. Invalid setting '4.8' is not a valid 'settings.compiler.version' value.
Possible values are ['7.1']`.  So I added the `[settings_default]` section in `conan.conf` with the right settings, (which is the procedure I instructed the other developers to use).

That had no effect. It seems that the settings created in the first-run `profiles/default` file (`compiler.version=4.8`) are not replaced with those from `conan.conf` once the profile has been generated for the first time.

**Comment by memsharded** [comment]
Oh, I see. That is true. Clean installations will only migrate the first run (conan keeps the current version in a version.txt file in .conan directory, and is used to compare, migrate, then update version.txt), so further changes to conan.conf will not be checked after that. Thanks for telling.
