### ISSUE TITLE
[question] How to force to use the same depencencies

### ISSUE THREAD

**Issue by yekmen** [conan-io/conan#15661]
### What is your question?

Hi guys ! 

I have a question about the dependencies which is compiled by Conan 2.0. 
On the same computer with the same Profile some dependencies has been recompiled for unknown reason.
The only things which is different is the generator. 

First project use : 
```
ms = MSBuildDeps(self)
ms.generate()
```

Seconde project use: 
```
tc = CMakeToolchain(self)
tc.user_presets_path = 'CMakePresets.json'
tc.generate()
deps = CMakeDeps(self)
deps.generate()
```

The difference is for instance on cpprestsdk output file name which is `cpprest143_2_10d.dll `for the first project and `cpprest_2_10d.dll` for the second. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @yekmen 

Thanks for your question.

I am quite sure that the generators of the consumer shouldn't affect whether the dependencies need to be rebuild or not. 
Maybe you have hit an update of some dependencies in ConanCenter that happened just in between your different ``conan install`` commands?

Otherwise, it would be great to have something to reproduce, like a couple of simple ``conanfile`` and the exact commands to reproduce the issue. Thanks!

**Comment by yekmen** [comment]
Hi @memsharded 

I using internal source repos instead to use ConanCenter, (artifactory server)

First project use : 
`conan install . -s build_type=Release -of $outdir --build missing --profile $profileFolder\windows_msvc.profile"`

Second project use:
`conan install . -s build_type=Release --build missing -pr Conan_Profiles\windows_msvc.profile`


First project conan file:
```
import os
from conan.tools.env import Environment
from conan import ConanFile, tools
from conan.tools.files import get, copy, rmdir
import sys
sys.path.append('..\\..\\..\\CommonInternals\\Build\\VSProject')
import conanhelper
from conan.tools.cmake import CMakeToolchain,CMakeDeps
from conan.tools.microsoft import MSBuildDeps
from conan.tools.env import VirtualBuildEnv


class GoLionFramework(ConanFile):
    version = "1.0.0.0"
    generators_folder = "conan_propertysheet"	#solution dir
    settings = "os", "compiler", "build_type", "arch"
    def requirements(self):
        self.requires(conanhelper.getVersion("libjpeg-turbo",self), force = True)
        self.requires(conanhelper.getVersion("ade",self))
        self.requires(conanhelper.getVersion("zlib",self))
        self.requires(conanhelper.getVersion("opencv",self))
        self.requires(conanhelper.getVersion("boost",self))
        self.requires(conanhelper.getVersion("cpprestsdk", self))
        self.requires(conanhelper.getVersion('glew',self))
        self.requires(conanhelper.getVersion("eigen", self))
        self.requires(conanhelper.getVersion("bzip2", self))

    def generate(self):
        env = VirtualBuildEnv(self)
        env.generate()
        ms = MSBuildDeps(self)
        ms.generate()
        #copy artefact from Conan to local folder
        outputFolder = os.getcwd() + "\..\conan_libs"
        rmdir(self, outputFolder)
        conanhelper.copyDependencies(self, outputFolder)

    def config_options(self):
        conanhelper.setOptions(self)
        
    def configure(self):    #need to be defined ! settings = "os", "compiler", "build_type", "arch"
        if self.settings.os == "Windows":
           self.settings.compiler.version = "193"

    def package_info(self):
        if self.settings.os == "Windows":
           self.cpp_info.cxxflags = "-runtime-link=shared"
```


Second project conan file:

```
import os
from conan.tools.env import Environment
from conan import ConanFile, tools
from conan.tools.files import get, copy, rmdir
import sys
sys.path.append('..\\..\\CommonInternals\\Build\\VSProject')
import conanhelper
from conan.tools.cmake import CMakeToolchain,CMakeDeps, cmake_layout
from conan.tools.env import VirtualBuildEnv

class GoLionUI(ConanFile):
    default_options = {}
    version = "1.0.0.0"
    settings = "os", "compiler", "build_type", "arch"
    def requirements(self):
        self.requires(conanhelper.getVersion("libjpeg-turbo",self), force = True)
        self.requires(conanhelper.getVersion("ade",self))
        self.requires(conanhelper.getVersion("zlib",self))
        self.requires(conanhelper.getVersion("opencv", self))
        self.requires(conanhelper.getVersion("boost", self))
        self.requires(conanhelper.getVersion('cpprestsdk', self))
        self.requires(conanhelper.getVersion('libzippp', self))
        self.requires(conanhelper.getVersion('libtiff', self))
        self.requires(conanhelper.getVersion('libpng', self))
        self.requires(conanhelper.getVersion("x12converter", self))
    def configure(self):    #need to be defined ! settings = "os", "compiler", "build_type", "arch"
        self.settings.compiler.version = "193"
        
    def generate(self):
        tc = CMakeToolchain(self)
        tc.user_presets_path = 'CMakePresets.json'
        tc.generate()
        deps = CMakeDeps(self)
        deps.generate()
        #copy artefact from Conan to local folder
        outputFolder = os.getcwd() + "\..\..\conan_libs"
        rmdir(self, outputFolder)
        conanhelper.copyDependencies(self, outputFolder)
        
    def layout(self):
        cmake_layout(self)
        
    def package_info(self):
        self.cpp_info.cxxflags = "-runtime-link=shared"

```

**Comment by memsharded** [comment]
Oh, then it is kind of expected. The 2 projects don't use the same dependencies or the same options. So it is possible and most likely that the dependencies are actually different and some need to be built because they are not the same binary, because of having different dependencies.

If you want to have the same dependencies, then it is highly recommended to use the same ``conanfile.py``, and you can add the 2 different generators in the same conanfile, with some care I think it is possible to make it work.

Let me also suggest some other important issues:

- This ``sys.path.append('..\\..\\..\\CommonInternals\\Build\\VSProject')`` looks very problematic, as it depends on a relative path, if you create a package out of this ``conanfile`` it will not work, this is only valid for consumer. Depending on what you are trying to solve, this needs another approach (if you have questions about this, please open a new, dedicated ticket for this)
- The ``package_info()`` and ``self.cpp_info.cxxflags = "-runtime-link=shared"`` is information exclusively for consumers of this package. But you are not creating a package with these conanfiles, so this info is not used at all. If you want to inject some compilation flags, needs to be done via the toolchain in the ``generate()`` method.
- Having an external python ``import conanhelper`` that contains logic that changes how recipes are evaluated can be problematic, because recipes must be mostly inmmutable, when they are creating packages. If you ever intend to create packages I'd recommend using ``python_requires`` feature to account for this. Specifically if the ``conanhelper.getVersion("libjpeg-turbo",self)`` is getting the version from somewhere that is not self-contained in the project, this is breaking encapsulation of the package too, and should be avoided.
- It is **forbidden** to set ``settings`` in recipes. This ``self.settings.compiler.version = "193"`` is not allowed. The definition of settings must always come externally from ``profiles`` or command line.
- The ``tc.user_presets_path = 'CMakePresets.json'`` is not recommended. Better leave the default ``CMakeUserPresets.json`` or a custom one like ``ConanPresets.json``. The ``CMakePresets.json`` is explicitly documented in CMake to be commited to scm, but this is an autogenerated file by Conan that shouldn't be committed to scm. Seems incorrect.
- The ``#copy artefact from Conan to local folder`` might be unnecessary or problematic, depending on what you are trying to do. Using dependencies from the cache is recommended in the majority of cases.

I'd suggest to open tickets for any question (one ticket per question) related to these issues. Many thanks!

**Comment by yekmen** [comment]
Woaw thx for the code review @memsharded 

I have a question about the last point. _Copy binairies to output folder_ I will open a new ticket for that...

But about this question, I remark that for the same project but different computer (cpu different, etc) the dependencies are rebuilded even is the binairies are available on Artifactory. 

For Instance: 
- First compilation on my compteur Windows 11, Intel i9 11th etc
- Push binaires to Artifactory

- Build the project on another PC which OS = Windows 10 and CPU = Intel i7 4th 
- Conan check the dependencies on Artifactory, but get only the sources and rebuild

I would like to have all the time the same binaires.

**Comment by memsharded** [comment]
Conan should indeed re-use those binaries. If it is  not doing that there is something different that is affecting. There could be the options or something that differ.

We would need some more information to try to understand what is happening. If you can please share the exact commands and the full output used in each of the 2 conanfiles, that might help. Thanks!

**Comment by yekmen** [comment]
After making the modification that you mention before. 
The issue is now fixed ! 

Thx @memsharded 
I removed these line. 

```
    def config_options(self):
        conanhelper.setOptions(self)
        
    def configure(self):    #need to be defined ! settings = "os", "compiler", "build_type", "arch"
        if self.settings.os == "Windows":
           self.settings.compiler.version = "193"

    def package_info(self):
        if self.settings.os == "Windows":
           self.cpp_info.cxxflags = "-runtime-link=shared"
```

**Comment by memsharded** [comment]
Happy that it is working now thanks for the feedback!
