### ISSUE TITLE
[question] Is there a simple way of getting Visual Studio 17 binary packages for conan 1?

### ISSUE THREAD

**Issue by forry** [conan-io/conan#15679]
### What is your question?

Hi,
we are still using conan 1 and the deprecated cmake-multi generator. We have our own conan server with lots of packages but we also use the conan center where we can. Now we would like to switch from VS toolset 142 to 143 for which the old conan.cmake detect_compiler infer the Visual Studio 17 compiler and version. There are not any of those binaries available for conan 1 on conan center. Technically they are there but for msvc compiler ID for conan 2. Since there is no compatibility extension in conan 1, is there a way to trick the conan 1 into requesting msvc v193 where it can't find the Visual Studio 17 package? All of our packages have the correct compatibility() method in the recipe, I wonder why that is not the case for conan center recipes. 

Ofc, I'm talking about the packages that are failing to build from source.

The transfer to conan 2 is a lot of work and most of it still seems to be experimental and not very well documented. So it is very bad for production. The other hard way around would be to manually download the binaries for msvc and reexport them to our server as VS binaries. I would appreciate it if I didn't need to do that.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @forry. As Conan 2.0 was released nearly a year ago, it is API and feature stable and Conan 2.1 will be released imminently. In Conan Center we are focusing our efforts to provide binaries for newer platforms (such as Visual Studio 2022) for Conan 2.0 only. 

> The transfer to conan 2 is a lot of work and most of it still seems to be experimental and not very well documented. 

Conan 2.0 is API stable - except for anywhere in the documentation that says otherwise (some specific sub-features may be experimental). If you have any questions regarding a specific feature, don't hesitate to open an issue. 

We have several users in enterprise already using Conan 2.0 in production, and it is our recommended way. 

> All of our packages have the correct compatibility() method in the recipe, I wonder why that is not the case for conan center recipes.

Binary compatibility has factors that are _external_ to the recipe - for instance, if a Visual Studio 2024 were to be released that is still compatible with older ones, we would have to modify _all_ recipes to express this. Hence the new compatibility.py extension in Conan 2.0 works better to express this when necessary.

**Comment by forry** [comment]
> Binary compatibility has factors that are external to the recipe - for instance, if a Visual Studio 2024 were to be released that is still compatible with older ones, we would have to modify all recipes to express this. Hence the new compatibility.py extension in Conan 2.0 works better to express this when necessary.

Yes but sadly this is for me the most anticipated feature and it is still experimental and not very well documented. In that regard, it would be very helpful if the algorithm of what exactly happens with the values of the array returned from the compatibility.py. Like how it merges with the requested settings, how the order of the values plays out, and so on.
Also, this would be a great thing to get backported to conan 1, but I guess it is not happening.

Anyway, thanks for the quick answer.
