### ISSUE TITLE
[feature] Define preferred and other compatible options for dependencies

### ISSUE THREAD

**Issue by stevenwdv** [conan-io/conan#15690]
### What is your suggestion?

Sometimes built packages are available from the cache or from Conan center, while sometimes they need to be built from source. When building from source, it is often desirable to switch off unnecessary feature options, speeding up build time. When prebuilt packages are available, it may be faster to use these, even if they contain unnecessary features. This even more applicable when we have cached an already built version that has these unnecessary features.

I think it would be nice if there were a way to instruct conan to do something like: "Please use these package options if you have to build from source, but I don't really care about these specific options; if you have a built version available with other values for these, then use that one."
I guess it's not 100% as simple as that, because we probably do not want to use the already-built version if one if its dependencies still has to be built from source (or is that not possible?).

Example: compiling Qt/Boost takes a lot of time, so it makes sense to exclude unnecessary features, e.g. `'without_program_options': True`, when a pre-built package is not available for our profile. But this means that a pre-built binary cannot be downloaded from conan center anymore.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your suggestion @stevenwdv 

> I think it would be nice if there were a way to instruct conan to do something like: "Please use these package options if you have to build from source, but I don't really care about these specific options; if you have a built version available with other values for these, then use that one."
I guess it's not 100% as simple as that, because we probably do not want to use the already-built version if one if its dependencies still has to be built from source (or is that not possible?).

One important problem is that not every ``option`` is a "feature-toggle". Yes, maybe some are called, ``with`` or ``without``, but those are just common cases, not a standard. And there are multitude of options that cannot just be fall-back to another package with other options.

Another important problem is the search space. Defining the "closest-distance" binary is not trivial, this is being done now in the ``conan graph explain``, but it is good as it is not really used in dependency resolution.


The approaches to manage this could be:
- Make sure you build your binaries with the options you need and want, this would be the optimal, and store them in your own repo. This is the recommended flow in https://docs.conan.io/2/devops/using_conancenter.html
- If you know your rules for a given package binary compatibility, it is possible to define those rules in the ``compatibility.py`` plugin, with a conditional for that package. The plugin logic will manage to download an alternate binary based on your rules if the main requested one is not found in the remote repos.

I think the first one is way easier, more robust and optimal, so I'd probably try that approach first.

**Comment by stevenwdv** [comment]
Thanks!

> One important problem is that not every option is a "feature-toggle".

That's why I proposed entering a list with such options.

---
Didn't know about compatibility.py, and I also hope may recipes will implement the new `compatibility()` method for their feature options!

Hosting our own binaries could be a solution which I'll discuss.

You can close this if you want

**Comment by memsharded** [comment]
Good, thanks for the feedback!
