### ISSUE TITLE
[question] retrieve additional information from graph build-order output 

### ISSUE THREAD

**Issue by nicosmd** [conan-io/conan#15703]
### What is your question?

Hey,

I have a question regarding the output of conan graph build-order. 

I'm trying to filter packages which have set the `upload_policy` to `skip` in order to not build packages in our CI which needs to be rebuild anyway. Beside that I would like to use the output of the build-order json to get all packages which can be promoted from a test remote to a develop remote, when the build in the CI job was successful. It would be possible to get the necessary information by using `graph info` before and afterwards because there the fields `upload_policy` and `binary_remote` are available, which are needed for both use-cases. 

Would it be possible to retrieve the additional information directly from the build-order json as well or do I have to make the additional calls to `graph info` to get them?

I'm using the latest conan version 2.1.

Thanks a lot!

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nicosmd 

Thanks for your question.

This is indeed an interesting one. At the moment we are envisioning the "PackageList" as the format that should be used for the example that you are proposing: promoting packages from one remote to another. In fact, we were thinking of providing this as a Conan extension command.

Then the question would be what is the flow to create, maintain and use a package-list file with this purpose. This is something we also need to consider ourselves for ConanCenter and in general to document for Conan CI flows. I think something in the line:
- conan graph build-order ...
- Execute the build order:
   - conan install/create ... --format=json > graph.json
   - conan list --graph=graph.json  ... --format=json > pkglist.json
- Aggregate pkglist.json for all creations
- conan extension:promote myfinalpkglist.json -r=remote1 -r=remote2


I will bring this topic to the team to discuss.

**Comment by nicosmd** [comment]
Hey @memsharded, 

thank you very much, especially for addressing this issue in the team.

I've read a bit about the "PackageList" feature but was not yet sure how to utilize them correctly. Most difficult for me was how to read them properly. For example when I call something `conan list --graph=graph.json --graph-binaries=download` what exactly does it mean when packages are listed under 'Local Cache' or the name of the remotes. 

However, I will play a bit with the workflow you have proposed. What I don't yet understand is how the following situation is covered: When I have created a PR, our application is build with the new dependency and everything is finally uploaded to a test remote. After merging the PR into master, nothing will be rebuild as soon as nothing has changed in the meantime. So I only want to promote the packages found in the test remote to the dev remote. In the flow you have proposed, when nothing needs to be rebuild, no PackageList will be created at all. Where would I get the list of packages to promote from in this case?

**Comment by memsharded** [comment]
When you are executing ``conan install/create ... --format=json > graph.json``, the ``graph.json`` contains the full graph.

Then, when you are doing ``conan list --graph=graph.json`` you can select which things go to the package-list with the ``--graph-recipes`` and ``--graph-binaries`` arguments, like ``--graph-binaries=download --graph-binaries=build`` will get in the package list all packages dowloaded and all packages built from source.

**Comment by nicosmd** [comment]
hm, but as I've understood the first command I'm using is `conan graph build-order` and when there is no package which needs to be rebuild because everything was found in the test remote from my previous PR build, I wouldn't call `conan install.. ` at all, right? I mean I could run it anyway for the final application but then I'm basically at my initial issue that there is an additional `conan install` or `conan graph info` necessary which feels a bit redundant to the already created build order json. So I'm wondering if it could be possible to create a `PackageList` directly from the build-order json or is this basically not very useful?

**Comment by memsharded** [comment]
I have been reviewing this ticket, after some extra information was added to the ``build-order.json``:

- The ``profile_args`` in https://github.com/conan-io/conan/pull/17102
- The ``info`` in https://github.com/conan-io/conan/pull/17068

We have considered the above, but at the moment it is not planned to add that information to the build-order. The reason is that the build-order is an intermediate representation for the build. To decide which things need to be uploaded or not, the recommandation is not necessarily an extra ``conan graph info``, but the same ``conan install --build`` or ``conan create`` that executes the build defined by the "build-order.json" is the one that can easily output directly its dependency graph with the ``--format=json > graph.json``, and this graph.json contains all the necessary information, even down to the ``package_revision`` that was just built (which is unknown in the ``conan graph info``, because it hadn't been built yet). 

Then, tools like ``conan list`` and ``conan pkglist`` are designed to be able to work on the ``graph.json`` or to merge previously computed "package list" and the package lists can be used both for the ``conan upload`` command, but also for the new ``conan art:promote`` command in the ``conan-extensions`` repo, intended to do efficient promotions via the Artifactory API (no actual download/upload transfers).


I am closing this ticket as responded, but please don't hesitate to re-open or create new tickets for any further question or issue. Thanks for the feedback!
