### ISSUE TITLE
[question] Parallel binary download from download cache supported?

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#15700]
### What is your question?

In the conan configuration parallel download of package binaries can be enabled.

Is this parallelization then also applied when the Conan download cache is enabled?
Or is this only working when fetching the binaries from the remote repository (into the Conan download cache)?

Thank you

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MTomBosch 

I am not sure if I understood. Which ``conf`` are you talking about?

> Is this parallelization then also applied when the Conan download cache is enabled?

The Conan download cache is a per-file caching mechanism, a bit orthogonal to the parallel download when installing things. If the download is parallel, the caching will be parallel.

> Or is this only working when fetching the binaries from the remote repository (into the Conan download cache)?

If the package files are not in the current cache, but they are in the download cache, Conan will see them as a download too, but it will get them from the cache instead of an actual download.

**Comment by MTomBosch** [comment]
It is this flag that I am referring to: parallel_download resp. core.download:parallel

> If the package files are not in the current cache, but they are in the download cache, Conan will see them as a download too, but it will get them from the cache instead of an actual download.

That means that the binary files are then copied in parallel from the download cache to the local package cache folder, correct?

**Comment by memsharded** [comment]
> core.download:parallel

Ok, that is used in ``conan download`` command and also while installing packages with ``conan install/build/create``

> That means that the binary files are then copied in parallel from the download cache to the local package cache folder, correct?

Yes, correct. Still, the disk copy & unzip operations here are typically a bit of bottleneck, so not much speedups are obtained with parallelism here.

**Comment by MTomBosch** [comment]
Ok. Thank you for the quick reply.
