### ISSUE TITLE
[question] Overriding package requirements forces rebuild of consumed package

### ISSUE THREAD

**Issue by mum4ply** [conan-io/conan#15719]
### What is your question?

Here is my scenario:
PkgA/0.1@pkg/test
requires("new_pkg/0.1@pkg/test")

I have another recipe for PkgB:
PkgB/0.1@pkg/test
requires("PkgA/0.1@pkg/test")
requires("new_pkg/0.2@pkg/test") // overriding PkgA/0.1@pkg/test for some new features

When I create my lock file: (Inside folder PkgB/)
conan lock create conanfile.py --lockout locks/pkgb_dep.lock

and then install:
conan install --lock locks/pkgb_dep.lock

I am causing a rebuild of PkgA because my current recipe overrides the requirement _new_pkg/0.1@pkg/test_ inside PkgA with _new_pkg/0.2@pkg/test_.

Is it possible, within my PkgB recipe, to force the usage of the already built PkgA, which was built and uploaded using _new_pkg/0.1@pkg/test_, if I'm confident that it will still be compatible with PkgB? The situation here is that _new_pkg/0.2@pkg/test_ contains other features needed for PkgB to function properly. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mum4ply 

It is not clear what Conan version you are using, and that is very important to try to help.
I am assuming you are still using Conan 1.X because of some hints. Please try to upgrade to Conan 2.0 as soon as possible.

A quick hint: Do not use package names in upper case, but always ``pkga/version`` in lowercase, this is recommended from long time ago, and Conan  2 mandates lowercase. Also, using channels to qualify stages like "testing" or "stable" is no longer recommended, but using different server repositories instead for the different stages.


Regarding your ``package_id`` question, it is definitely possible. Recipes can define in their ``package_id()`` method how their dependencies affect them. Something like ``self.info.requires.major_mode()`` will require a new binary for that package when the dependency bumps the major version, not the minor. You need to be really sure that this is the case, in many cases avoiding to build the consumer with the new version of the dependency will result in problems, misbehaviors even later at runtime, like everything building correctly, but the last bug that you fixed in ``new_pkg/0.2`` is really not into production because the consumers of that package were not rebuilt and did not incorporate that bugfix into their own binaries, so still running with older non-fixed code.

**Comment by mum4ply** [comment]
Thanks for responding so quickly @memsharded!
We're currently using conan 1.x and have plans to update to conan 2, but for the foreseeable future we're using conan 1.x. 

For the `pacakge_id()`, we have the scenario where `pkga/0.1` isn't maintained by us and its recipe updates lag behind the `pkgb/0.1` recipe in regards to this `requires("new_pkg/version")`. So, while `pkga` maintainers may update they're `requires("new_pkg/version")`, it's likely it would still be behind the `pkgb` recipe.  

In this case, it would be preferable to take the existing build for `pkga/0.1`, whose `package_id` is calculated using `requires("new_pkg/0.1")` even though `pkgb` overwrites this requirement with `requires("new_pkg/0.2")`.

Can this be done from the recipe of `pkgb`?

**Comment by memsharded** [comment]
> We're currently using conan 1.x and have plans to update to conan 2, but for the foreseeable future we're using conan 1.x.

Sure, that is not a problem per se, but please note that Conan 2 was released 1 year ago already (2.5 years before that in beta), and while Conan 1.X will keep working, packages in ConanCenter will soon stop building updates for Conan 1.X, and those resources will be finally transferred to Conan 2. That doesn't mean that ConanCenter will break for 1.X, it will continue working, but in a "frozen" state, it will no longer get new versions or fixes. 

> Can this be done from the recipe of pkgb?

No, this cannot be done from ``pkgb``, how a dependency affects other packages.

You can manage this at the global level, via conan.conf ``default_package_id_mode``, but that changes things globally, and that would affect all binaries for all packages, requiring new binaries, and might be breaking things. Most likely not recommended.

The recommendation is just let ``pkgb`` build a new binary against the new dependency, or ask the maintainers of ``pkgb`` to create that binary.

**Comment by mum4ply** [comment]
Thanks for the Conan 2 information!

you're correct, a global level change wouldn't be desired. This is good information though and getting a concrete answer is helpful! 

I'll take your recommendation. This question can be closed :)

**Comment by memsharded** [comment]
Thanks for the feedback and following up!
Don't hesitate to create new tickets for any further question or issue that you might have.
