### ISSUE TITLE
Replacement for conans.client.conan_api in Conan 2

### ISSUE THREAD

**Issue by lstoffer** [conan-io/conan#15730]
### What is your question?

We are using `conans.client.conan_api` to download conan packages:
```python
from conans.client.conan_api import Conan
conan, _, _ = Conan.factory()
conan.download(...)
```
Is there a replacement for this functionality in conan2?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Yes, the api in Conan 1 was actually undocumented and not recommended for production as unstable.

We are creating a full public Python API in Conan 2: https://docs.conan.io/2/reference/extensions/python_api.html

The docs are still ongoing process, because we are still stabilizing it, but we are progressing since 2.1 we will be adding new subapis docs, like the recent https://docs.conan.io/2/reference/extensions/python_api/RemotesAPI.html.

In the meantime you can have a look to the implementation of the ``download()`` command and you will see how the download api is used. Still not stable, might change in the future, but we are on it to stabilize and document it properly

**Comment by memsharded** [comment]
Closing this question as responded, don't hesitate to open new tickets for any further question, thanks!
