### ISSUE TITLE
Does conan detect conflicting compiler switches?

### ISSUE THREAD

**Issue by mschmid** [conan-io/conan#1576]
Hi, assume a dependency from libA -> libB.
libB sets cpp_info.cxxflags to "-O0", libA sets cpp_info.cxxflags to "-O3".
If App depends on libA, is there a way to detect this conflict?
Is it possible to control the order of the flags?

**Comment by memsharded** [comment]
Conan is able to detect conflicting options, over diamond structures. So if you have a diamond A->B, A->C, B->D, C->D, and different options get to D in different paths, it will be a conflict and will be reported.

Conan doesn't have a way to detect such downstream compiler switch conflicts, because conan is actually agnostic about them. And it is agnostic, because there is no general solution to the problem that you are defining, it depends on the flag, on the way different compilers treat them...

It is the packages responsibility to manage them coherently. Maybe, if you have that situation is because of some underlying issue in the model. Some ideas:

- It doesn't seem the best that upstream packages will be controlling the optimizer flags for downstream packages. Typically these are controlled by the ``build_type`` setting, if Release or Debug, it will use different optimizer flags.
- If you want to control your optimization level, you should probably model it with some optimization setting or option. Why would a package use a ``-O0`` and another one ``-O3``. That reads like an inconsistency in the build model, they shouldn't decide to use that flag unless they had some input that told them to do so. If they have such an input, managing the consistency downstream is easy, because you have the input too.
- Package recipes also can do any process they want for the flags. From reading ``self.deps_cpp_info.cxxflags``, extracting the values and filtering them, to check ``self.deps_cpp_info["LibA"].cxxflags`` and ``self.deps_cpp_info["LibB"].cxxflags``

I think that I'd would go for explicit modeling of the optimizer level if you are not using the default defined by Debug/Release

**Comment by memsharded** [comment]
This has been inactive for a long time, I think it can be closed.
Please @mschmid re-open or open a new issue if you have further questions. Thanks!
