### ISSUE TITLE
[question] How to call generator without install command

### ISSUE THREAD

**Issue by steffenroeber** [conan-io/conan#15793]
### What is your question?

Hi, can I somehow trigger a generator without using conan install, which downloads all binaries?
Also conan lock install downloads either binaries or if using --recipes doesn't call the generator.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
> Hi, can I somehow trigger a generator without using conan install, which downloads all binaries?

``conan install`` doesn't download binaries if they are already in the cache, in that case it will be very cheap and fast

The generators work over the dependency graph, so it needs the dependencies installed, otherwise they have not enough inputs to generate its information. Generators operate over ``dependency.cpp_info.includedirs``, ``dependency.cpp_info.libdirs``, ``dependency.cpp_info.libs``, etc. If the package binaries are not there, the ``cpp_info`` is not there, and generators will not work.

In Conan 2, the ``conan graph info`` command, with the ``--format=json`` will give you a thorough view of the dependency graph without downloading the binaries. Still cannot generate or call generators, same rationale as above applies.

**Comment by memsharded** [comment]
Any further question here @steffenroeber ?

Can we close the ticket as solved? Thanks!
