### ISSUE TITLE
[question] why tool_required installs cmake as package while it is installed in the system?

### ISSUE THREAD

**Issue by subbota-a** [conan-io/conan#15800]
### What is your question?

Hi! I'm wondering why canon installs `cmake` as package if 
- There is a system wide cmake 3.25
- The recipe looks like `self.tool_requires("cmake/[>=3.16.3 <4]")`

I sure that `cmake 3.25` is eligible for this requirement, so why `conan` does redundant installation?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @subbota-a 

Please have a look to https://blog.conan.io/2024/02/20/Conan-2-graph-features.html

``[platform_tool_requires]`` seems to be what you are looking for.

In general, Conan will not auto-detect or try to be smart, but it is necessary to explicitly define the behavior. If a package defines a ``requires`` it will be honored, downloaded and used, unless the user says otherwise in ``[platform_tool_requires]``
