### ISSUE TITLE
[question] When will Conan 1.x go EOL?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#15816]
### What is your question?

Hi, as in the subject :)
When will Conan 1.x be permanently EOL receiving no further updates?
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
At the moment there is no planned EOL date.
It is true that the 1.X releases will be less and less frequent, because of being less prioritized than 2.X

The first thing that will be officially EOL will be ConanCenter updates. It is not that ConanCenter will remove Conan 1.X packages, but soon it will stop processing new changes, so it will be effectively frozen, no more updates, fixes or new versions for Conan 1.X packages. If someone needs to keep doing changes to ConanCenter recipes beyond this freeze, they will need to work on their own fork and build their own binaries from their fork (which is a recommended approach anyway, documented in https://docs.conan.io/2/devops/using_conancenter.html)

**Comment by harsszegi** [comment]
Awesome, thanks a lot @memsharded !
