### ISSUE TITLE
[question] How do I get conan's build(self) step to use the environment set by tool_requires?

### ISSUE THREAD

**Issue by RochaStratovan** [conan-io/conan#15824]
### What is your question?

We use CMake to build our source code, but for company specific reasons CMake commands are not done directly. We have a `cmakeBuild` script that does stuff and then invokes the cmake commands for configuration and building.

I've been able to hack the following python code together to get it to use our build script 

```python
    def build(self):
        conan_toolchain = "-DCMAKE_TOOLCHAIN_FILE=" + \
            os.path.join(self.folders.generators, "conan_toolchain.cmake")
        old_dir = os.getcwd()
        os.chdir(self.source_folder) # Our script is at source level
        subprocess.call(["cmakeBuild.bat",
                         "parm1",
                         "parm2",
                         ...
                         "--CMAKEGEN", conan_toolchain,
                         "--CMAKEGEN", "-DCMAKE_POLICY_DEFAULT_CMP0091=NEW"])
        os.chdir(old_dir)
```

<br>

This triggers our script and almost does exactly what I want. The problem is it's not using an environment variable that would be set from our `tool_requires` setting.

I explored this and if I use the a slightly modified conan demo `build()` sequence such as the following:

```python
    def build(self):
        my_install_folder = os.path.join(self.recipe_folder, "INSTALL")

        cmake = CMake(self)
        cmake.configure(cli_args=self._get_cmake_arch_flags())
        cmake.build()
        cmake.install(cli_args=["--prefix", my_install_folder])
```

It works fine. I'm guessing that the Conan CMake class is doing some magic to cause the tool_requires values to be used.

While I can use the above for a proof of concept, it's not acceptable for our code base.

How would I do this so that the tool_requires logic is available when using our company build script?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @RochaStratovan 

The key to run with environment from tool-requires is using the 
```python
def build(self):
     self.run(<cmd>, ... , env="conanbuild")
```
The ``env`` argument will already default to ``conanbuild`` so no need to specify it. This ``self.run()`` also does some other tasks, like manage the output, etc. This is pending to document it properly in an independent location, it can be found in different places like in https://docs.conan.io/2/reference/tools/env/envvars.html#running-with-environment-files

Maybe there might be other less intrusive approaches, like https://docs.conan.io/2/reference/extensions/command_wrapper.html, you can intercept ``cmake`` calls and replace them by the call to your script, if it is a drop-in replacement for ``cmake``. Or the args manipulation is doable, it might also allow to map the arguments. This would have the advantage to not have to modify recipes at all.

It also sounds that if you use this everywhere, you might want to put it in a ``python_requires`` to reuse it from there.

Extra tips:
- do not do ``cmake.install()`` in the ``build()`` method, but in the ``package()`` method, otherwise it can fail in local flow

**Comment by RochaStratovan** [comment]
Thank you! As soon as you said `self.run()` I remembered reading that section.

Converting from `subprocess.call()` to `self.run()` took care of this.

**re: command_wrapper** - good tip, however we wouldn't be able to replace `cmake` with our `cmakeBuild` script. This is a _situation_ that is regularly discussed (dropping that script), and I anticipate it will happen when we are able to fully deprecate some legacy functionality.

**re: don't do `cmake.install()` during `build()`**. Can you clarify more on this, how it can fail in local flow?

We do `cmake install` in our `cmakeBuild` script during the `build()`. For us installation means writing the complete _deployment_ to the `<repository-root>/INSTALL` folder. Where it has the following general layout

```bash
├───bin
├───cmake
├───dependencies
├───include
├───lib
├───license
└───tests
```

In our legacy system the entire INSTALL folder is copied to our file share to be used by everyone (we don't have multiple versions). For our introduction into conan, our `package()` method is simply "copy the contents of the `INSTALL` folder to conan package folder.

Using the `INSTALL` folder and installing during build has also simplified our settings for _editable packages_

```python
        self.cpp.source.includedirs = ["INSTALL/include"]
        self.cpp.source.libdirs = ["INSTALL/lib"]
        self.cpp.source.bindirs = ["INSTALL/bin"]
        self.cpp.source.builddirs.append("./INSTALL")
        self.cpp.source.set_property("cmake_find_mode", "none")
```

I like this at the `build()` stage because I can manually verify that everything was correctly installed to my local folder location.

Originally I had it in the `package()` method and we wouldn't see this until the `conan export-pkg` stage.

I would like to learn more about your warning though. How would it cause a failure in the local flow? I don't understand the nuances of that statement.

**Comment by memsharded** [comment]
> re: don't do cmake.install() during build(). Can you clarify more on this, how it can fail in local flow?

Ok, I see it makes sense in your case, because you are not installing to the "final" folder, but to a local folder.

In the local-flow the ``self.package_folder`` is not defined, it is ``None``, because there is no package folder at all (for Conan). A package can only be in the cache (it needs checksum, entry in the DB, manifests, etc, not possible to do it locally). The ``cmake.install()`` built-in is using ``self.package_folder`` and it will fail in the local flow.

If your own flow does a "local" install, and then the ``package()`` method just copies this install to the final ``package_folder``, then it sounds good, and I understand the value of having the local copy of the "clean" artifacts for debugging.


Does this clarify the issue?

**Comment by memsharded** [comment]
Hi @RochaStratovan 

Did the above clarified the issue? Any further question or issue? Thanks for your feedback.

**Comment by RochaStratovan** [comment]
Hello @memsharded ,

Thank you for your patience and follow up. Yes this answered my questions.

**Comment by memsharded** [comment]
Nice, thanks for the info.

Then I am closing the question as responded, don't hesitate to re-open or create new tickets if there are any further question. Thanks for the feedback!
