### ISSUE TITLE
Linking dynamic libraries

### ISSUE THREAD

**Issue by dix75** [conan-io/conan#15831]
### What is your question?

Good afternoon!
I have the live555 library created by conan2, which creates the live555.so and live555.so.1 dynamic library.

I am building a project that depends on this library. 
Everything builds fine, but the application does not see the live555.so library!

```
import os
from conan import ConanFile
from conan.tools.cmake import cmake_layout
from conan.tools.files import copy
from conan.tools.env import VirtualRunEnv

class CompressorRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"

    def requirements(self):
        self.requires("catch2/3.5.3")
        self.requires("live555/112.0.4")

    def layout(self):
        cmake_layout(self)

    def generate(self):
        ms = VirtualRunEnv(self)
        ms.generate()

        path = os.path.dirname(os.path.abspath(__file__))
        libs = "*.dll" if self.settings.os == "Windows" else "*.so*"
        for dep in self.dependencies.values():
            if len(dep.cpp_info.bindirs) > 0:
                copy(
                    self,
                    libs,
                    dep.cpp_info.bindirs[0],
                    os.path.join(path, "bin"),
                    keep_path=False,
                )

```

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @dix75 

There could be different reasons why your application is not seeing the shared libraries, and also these reasons can be different in different OS. I assume you are talking about Linux.

In Linux it shouldn't be necessary to copy the .so. Actually copy them can be pointless, because unlike Windows, shared libraries in Linux are not found just because they are sitting close to the executable. They rely on:
- rpaths
- DYLD_LIBRARY_PATH

If relying on the second, it might be necessary to activate the ``conanrun`` virtualenv before running it.

So if you could please provide full reproduction steps with a minimal example, that could clarify:
- The OS/platform
- The conanfile.py + CMakeLists.txt + cpp code of the consumer
- The exact ``conan install`` command and output
- The exact ``cmake`` command and output
- The exact execution command and output.

Thanks very much.

**Comment by memsharded** [comment]
Any further feedback or question here @dix75 ?
