### ISSUE TITLE
[question] How should a hard required option for a dependency be specified

### ISSUE THREAD

**Issue by shannonbooth** [conan-io/conan#15843]
### What is your question?

Hi,

I have a recipe which makes use of protobuf, and specifically has a hard requirement on using protobuf lite. This means that it is required for the "lite" option in the protobuf recipe to be set in the build tree, otherwise it will fail at configure time.

From reading the documentation on options (and searching around on other github issues), it seems preferred to use profiles for setting the values of options, which does make sense.

However, in this specific case, it seems to me that it would be ideal for the recipe to specify that it has a hard requirement on the "lite" option being set. Ideally (in my mind), if a downstream recipe tries overriding "lite" to false conan would detect that settings are mismatched somewhere in the build graph, and immediately fail the build before even trying to invoke the build system.

Is there a preferred way of achieving this in conan? Or is there some underlying problem in the behaviour which I am looking for.

The following options I have been considering (or some mixture of them):

- Only put `protobuf/*:lite=True` in the `[options]` section of my profile
- Put `default_options = {"shared": False, "fPIC": True, "protobuf/*:lite", True}` in my recipe
- Put `default_options = {"shared": False, "fPIC": True, "protobuf/*:lite!", True}` in my recipe (important syntax)
- Use options in `requires` in the requirements of my recipe: `self.requires("protobuf/3.21.12", options={'lite': True})`

Based on the name alone, `self.requires("protobuf/3.21.12", options={'lite': True})` seems like it should do what I would want, but from testing it doesn't (I also can't seem to find any docs for this option, hopefully I haven't missed something).

I would appreciate any guidance on achieving the desired behaviour, with conan, or some clarification on the downside wanting this. Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @shannonbooth 

Thanks for your question.

In the general case, it is not possible to enforce a hard requirement on dependencies, because Conan has a design policy that the user/consumer should always have full control. If the user wants to have some specific option for its dependencies, no matter what the intermediate recipes are saying, it will be overriden from the "downstream" user.

A couple of other related hints:

- Introducing a ``validate()`` method is always good, that raises if the dependency option is not correct. This way, at least the invalid configuration is always detected and raised early
- You can always change the recipe default, if you always need some recipe with a fixed option, you can just remove the option from the recipe. The flow recommended in https://docs.conan.io/2/devops/using_conancenter.html for working with customized recipes from ConanCenter might help.

Regarding your case, it is important to highlight that the graph resolution happens ``depth-first``. The first expansion of the graph that expands each package/node in the graph, will be the one with higher priority and defining the package ``options`` values, both for ``self.requires()`` and ``default_options``.

That means that you want to make sure that your own recipe is the first one in the downstream ``requires()``, so it will be prioritized against the others. I'll probably go for:

- Using ``important!`` options definition
- Making sure the option is correct with a ``validate()``
- Review the graph downstream to make sure my recipe is expanded before any other recipe that requires ``protobuf``

**Comment by shannonbooth** [comment]
Hi @memsharded, thanks for the quick (and detailed) response!

That explanation makes a lot of sense. I think the `validate` method in particular, is the bit I was missing.

I will apply those suggested changes, appreciate it :^)

**Comment by memsharded** [comment]
Happy to help! 🙂
