### ISSUE TITLE
[feature] compatibility check when overrides the dependency

### ISSUE THREAD

**Issue by bethmal** [conan-io/conan#15855]
### What is your suggestion?

Hi, I'm using conan 1.x. Seems conan would not perform dependency correctness check for downstream package when overrides downstream package dependency.
Would it be possible that conan checks dependency compatibility and reports compatibility error when overrides the dependency?
Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @bethmal 

Thanks for your suggestion.

If you are asking about Conan 1 raising on overrides, then maybe https://docs.conan.io/en/1.63/reference/env_vars.html#conan-error-on-override helps.

Otherwise, Conan 2 was released now more than 1 year ago, after 2.5 years in beta, so it is not receiving anymore this kind of large features. One of the reasons it was really necessary to do a Conan 2 release is that all the legacy and defaults in Conan 1 made impossible to develop these features in Conan 1 without breaking and risk of introducing too much fragility.

If you are asking about dependencies custom binary compatibility, I guess that the ``compatibility.py`` plugin is what you are looking for. But it is not fully clear, please clarify what you mean. Thanks!

**Comment by bethmal** [comment]
Hi @memsharded 

Thanks for the reply.

Please look at below 3 warnings.

1. WARN: pkg_a/1.2.1@user/stable: requirement pkg_b/[~=1]@user/stable overridden by gen/App to pkg_b/1.1.2@user/stable
2. WARN: pkg_a/1.2.1@user/stable: requirement pkg_c/[>=2.6.0]@user/stable overridden by gen/App to pkg_c/2.8.0@user/stable
3. WARN: pkg_a/1.2.1@user/stable: requirement pkg_d/[~=2]@user/stable overridden by gen/App to pkg_d/3.0.1@user/stable

We think warning 1 is acceptable overriding, since pkg_b/1.1.2 is in the compatible version range - pkg_b/[~=1].

We think warning 2 is also acceptable overriding, since pkg_c/2.8.0 is in the compatible version range - pkg_c/[>=2.6.0].

However, we do NOT think warning 3 is acceptable overriding, since pkg_d/3.0.1 is not in the compatible version range - pkg_d/[~=2].

Hope this example could clarify our requirement, basically we expect unacceptable overriding could be detected and reported.

Thanks.

**Comment by memsharded** [comment]
Thanks for the feedback @bethmal 

The graph resolution algorithm has changed a lot in Conan 2, including the reporting of overrides.
Now all overrides are reported directly as errors. If the version is in the range, it is not considered an override, but if not it will be directly raising an exception. 
The users that want to opt-in to force the override, can do it with ``override=True`` or ``force=True``.

So I think this is addressed in Conan 2.0, I think this issue could be closed as solved. If you have any further question about it when you update, don't hesitate to open new tickets as necessary. Thanks for the feedback!
