### ISSUE TITLE
[question] how to consume semver_direct_mode package when using recipe_revision_mode?

### ISSUE THREAD

**Issue by wuziq** [conan-io/conan#15862]
### What is your question?

If I have a package, packageA, that was built with `semver_direct_mode` using `conan export-pkg` long ago, but now consumers are using `recipe_revision_mode`, how can the consumers still use the same package?

Using `--build=missing` doesn't work, I think because the package was created with `conan export-pkg`.

Is it even possible?  We are using Conan 1.62.

Does packageA's original recipe need to be changed?  If so, would it require the need to ignore the minor and patch versions of packageA's requirements (among other things)?  If so, how does one do that?

It wasn't clear from this similar thread:  https://github.com/conan-io/conan/issues/7220

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @wuziq 

Thanks for your question.

Does ``packageA`` has dependencies? If it has dependencies, how is it that it was built with ``conan export-pkg`` and not ``conan create``? Typically the ``conan export-pkg`` is for pre-compiled artifacts, that most typically implies no dependencies.

If it doesn't have dependencies, you should be ok, because the ``mode`` doesn't really affect it. But I guess this is not the case.

It is not possible to mix different global ``package_id_mode`` values. If it is changed, it requires a re-build of the packages to compute the new ``package_id``

> Does packageA's original recipe need to be changed? If so, would it require the need to ignore the minor and patch versions of packageA's requirements (among other things)? If so, how does one do that?

No, it wouldn't be necessary to change ``packageA`` recipe. Just to execute ``conan export-pkg`` again, with the new configuration that changes the ``package_id_mode``. Isn't this possible? This would be the easiest way to address the issue.

**Comment by wuziq** [comment]
Ah, yes, I did some digging and found out that packageA does have `requires`.  But after digging further I found out that the dependency isn't actually needed!  Maybe that's how `export-pkg` was able to work?

> Just to execute `conan export-pkg` again, with the new configuration that changes the `package_id_mode`. Isn't this possible? This would be the easiest way to address the issue.

I can do this, but I suspect that I need to accommodate the `requires` somehow during `export-pkg`.  Is that correct?

If not, my other guess is that I may need to modify the recipe by removing the `requires`.  I suppose I then run `export-pkg` twice, once for `semver_direct_mode` and another for `recipe_revision_mode`, and then `conan upload --force`.  Maybe?

**Comment by memsharded** [comment]
Sure, it sounds that if the ``requires`` are not needed, you should most likely remove it.

Once the package doesn't have any ``requires``, the ``xxx_mode`` will not matter, it will have just 1 ``package_id`` irrespective of the mode, no need to run ``conan export-pkg`` twice?

**Comment by wuziq** [comment]
Got it.  I'll pursue the path of removing the `requires`.  Thank you!

Out of curiosity, though:  If I were to leave the `requires` alone, what would the course of action need to be?

**Comment by memsharded** [comment]
> Out of curiosity, though: If I were to leave the requires alone, what would the course of action need to be?

Yes, building twice with the 2 different modes could help with that.

For Conan 2.0, it is likely that keeping the defaults for ``package_id_mode`` will be good in most cases, as the computation of ``package_id()`` is more thorough and correct in Conan 2

I think we can close the issue now? You can always open new tickets for any further question. Thanks for the feedback!
