### ISSUE TITLE
[question] Can sources be added into the consumer build process (similar to header-only packages)?

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#15889]
### What is your question?

Is it possible with Conan to deliver packages containing source files (and documentation) for integration into consumers' build processes?  I am not able to deliver pre-compiled libraries due to compile time configuration set by the consumer, but I would very much like to make use of Conan's features for packaging, version management, and automatic integration into build processes.  I see that header-only packages are supported but I can't see where .c files would be added.

Trying to understand if this a valid use-case, or if am I better to continue delivering via zip files for manual integration.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @GordonJess 

Thanks for your question.

Conan defines the ``cpp_info.srcdirs`` that is intended for this use case: to specify folders containing sources.
The issue is that there is no standard integration mechanism in build systems to use sources from elsewhere, and it is needed to have some strong conventions between the package sources and the consumers of those sources. 

The consumers can directly access the location of the sources via ``self.dependencies[]``.

A different issue is how to model the dependency, there could be the idea of saying "this is only needed for build, so it is a build_require". But build-requires do not affect by default the ``package_id`` of the consumers, so this might not be the best default. Also, they are private, so it is easy to have different packages in the dependency graph to depend on different versions of that "source" package, and this would be undesired too. So it sounds a regular ``requires(..., libs=False, headers=False)`` or something in that line could make sense. Maybe these packages are used only by 1 other package in the graph? Because if used by several packages, then it would be easy to have duplicated symbols because the same source code being compiled in different other places and finally linked together?

**Comment by memsharded** [comment]
Hi @GordonJess 

Any further question or comment here? Maybe we can close the ticket as responded?
