### ISSUE TITLE
[bug] conan export-pkg uses the state of conan rather than the state of workspace when declaring it's requirements

### ISSUE THREAD

**Issue by RochaStratovan** [conan-io/conan#15899]
### Describe the bug

`conan export-pkg` is setting the package requirements based on the current state of conan, and not upon the state of the workspace that was used to actually create the package.

Consider the following dependency

```bash
foo <-- blarg
```

1. `conan create foo --version 1.0.0`

   Creates `foo/1.0.0` and adds it to the conan cache.

1. `mkdir blarg`

1. `cd blarg`

1. `conan install .`

   Project `blarg` is now configured to use `foo/1.0.0`

1. Developer does development stuff for project blarg

1. Developer has an interrupt and works on some other issue that cause a `foo/1.1.0` to be generated and stored in the local conan cache.

1. Developer goes back to working on project `blarg.`

   At this point `blarg` is still configured to use `foo/1.0.0`, because it's cmake build infrastructure is using conan generated files that are referencing `foo/1.0.0`

1. Developer generates a package from project `blarg` and exports it to the conan cache

   `conan export-pkg . --version 1.0.0.1`

The problem I have observed is that project `blarg`'s workspace was configured for `foo/1.0.0` the compilation and such was done with `foo/1.0.0`. However, when `conan export-pkg` is done, it doesn't use the current state of the workspace, it uses the current state of conan. Meaning it creates a package for blarg that indicates it was build with `foo/1.1.0` even though it was really built with `foo/1.0.0`

### How to reproduce it

See the steps in the _description_.

# Environment

| what | version |
| - | - |
| os: |  Windows 11  Pro N 22631.3296 | 
| conan version: |  2.1.0 | 
| python version: |  3.12.1 | 
| git version: |  2.42.0.windows.2 | 
| cmake version: |  3.23.1 | 
| compiler: |  Visual Studio 2022 |

**Comment by memsharded** [comment]
Hi @RochaStratovan 

This wouldn't be a bug, but expected behavior. The local development flow doesn't intend to track state automatically by default.

The recommended way to enforce fully reproducible dependencies is to use lockfiles. 

In your workflow above use while installing ``blargh``:

```
$ conan install . --lockfile-out=conan.lock
```

And from there, the following commands, like ``conan build``, ``conan install`` and ``conan export-pkg`` will automatically use that lockfile and pin the ``foo/1.0.0`` dependency (implicit using ``--lockfile=conan.lock`` if ``conan.lock`` exists), irrespective of other possible new versions of dependencies that would be introduced to the cache.


As a clarification the ``conan export-pkg`` command is intended for packaging pre-compiled binaries (from other vendors, for example). If the package has dependencies installed with Conan and it is built against those Conan dependencies, then writing a ``build()`` method is the recommended way to go, so achieving a fully reproducible and self-contained build via ``conan create `` is possible. This also would be the recommended approach in CI, and it has several other advantages, like allowing easier CI at scale with ``conan graph build-order`` + ``conan install --requires=mypkg/version --build=mypkg/version``

**Comment by RochaStratovan** [comment]
This is hard to convey without it feeling emotional. Please forgive me if my words come out poorly.

I believe you are saying that this is a known way that Conan can lead to packages with incorrect dependencies, and that's a bit hard for me to accept.

As a user, when I'm working on a workspace and I'm using a tools to build and deploy a package I expect that that information is accurate to the state of my workspace, not to the global state of the tool.

However, Conan doesn't track the state of the workspace and instead creates package based on the global state of Conan, where the state of Conan may not match state of the workspace.

You mentioned that this wouldn't happen if the intended development flow is used (where is this intended workflow documented) and that `conan export-pkg` isn't really intended for this sort of use, but rather for packaging pre-compiled binaries.

I don't think this statement is quite correct. I say that based on the documentation for [Package Development Flow](https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html).

The high level steps documented for the Conan documented package development flow is:

1. conan source
1. conan install
1. conan build
1. conan export-pkg

The existing documentation says we should be using export-pkg for this situation.

Moreover, in other Conan issues that you've helped with you've mentioned that we should not be using `conan build` for local development, but instead using our local cmake commands combined with the conan provided build flags.

I understand that this could be alleviated with conan lockfiles. However, that's not documented that way.

If we switch to conan my devs will read the documentation and use conan based on the documentation -- which leads to problems like this.

**Comment by memsharded** [comment]
>  (where is this intended workflow documented)

From https://docs.conan.io/2/reference/commands/export-pkg.html#conan-export-pkg

Relevant quotes:

- ``Create a package directly from pre-compiled binaries.`` This is for pre-compiled binaries, not a standard method for package creation from sources
- ``When testing some recipe locally in the [local development flow](https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html#local-package-development-flow), it can be used to quickly put the locally built binaries in the cache to make them available to other packages for testing, without needing to go through a full conan create that would be slower.``. This means it is a local flow for testing, not a method to actually create and upload packages.

The key is accepting that the Conan cache is not concurrent, and it cannot be used as shared accross concurrent tasks. Then the flow:
```
conan source
conan install
conan build
conan export-pkg
```
Works well. The cache is the representation of the state.

What it doesn't work well is if someone is concurrently modifying cache packages of the dependencies in-between those commands, that is equivalent to a concurrent modification to the cache in practice. The fact that it can take days in your example, doesn't preclude of the fact that the above flow is actually broken and interrupted, and another task concurrently changes the state of the cache in an unforeseen way.

I think we can do a better effort in clarifying this, when doing the ``conan export-pkg`` of something that has been built locally with dependencies from the cache, it is the user responsibility to not do concurrent modifications to the cache. And for the case the user wants to do those modifications, then there is just a ``--lockfile-out`` there that allows to easily enable this flow. 
But this cannot be made automatic by default, because it would be breaking behavior, there are users that want to be able to keep updating their local project without a lockfile blocking them.

**Comment by RochaStratovan** [comment]
Thank you for the additional explanation. I don't like this functionality, but I understand it is "the conan way."

**Comment by memsharded** [comment]
> Thank you for the additional explanation. I don't like this functionality, but I understand it is "the conan way."

To be fair, I'd like to say that I understand what you are saying, and it is something that makes sense. Thinking that this shouldn't be allowed, and Conan should protect against this automatically by default is a fair request.

The problem is, as always, the trade-offs that have to be made. For implementing this protective feature, it would be necessary to store kind of "hidden" state in the local project with ``conan install`` happens  (note that this has to be done always, for every ``conan install``, because it is not possible to know if this will be used for export-pkg later or not). Then this local state should be compared with the cache state in the ``conan export-pkg``. The thing is that we had local state in Conan 1.X, several files containing information, like ``graph_info.json``, ``conaninfo.txt`` and ``conanbuildinfo.txt``, that Conan commands read to recover state from previous commands. But managing these files was always too dirty and problematic, tons of edge cases, maintenance, etc. So in Conan 2 we decided to make Conan local user projects as stateless as possible. Overall the situation has improved a lot, compared with the previous approach. This of ``export-pkg`` with concurrent modifications of dependencies would be one of the edge-cases, but given there is already a strong mechanism to avoid it (lockfiles), seems a good enough trade-off to recommend this to cover this case, compared with the complexity and resulting fragility of having to add that much state generation and management. 

We have learned during the years that it is often better to fail on the "not protective/smart/automatic enough" than the opposite. The technical complexity compounds very quickly, technical debt piles up and the commitment to stability in Conan makes almost impossible to change many things, slowing a lot the team progress and causing a much larger negative impact on the overall project, disabling the possibility to add important and demanded features, slowing down the fixing and releasing of bugs, etc.

Thanks very much for the feedback!

**Comment by RochaStratovan** [comment]
Thanks for the additional insights.

I first came across this as part one of the investigations where I did these steps, but instead of `conan export pkg` I did a `conan graph info` and I knew my workspace was configured for `foo/1.0.0` and instead got the results `foo/1.1.0`. 

So I started playing around with different conan commands, etc.

Thank you again.
