### ISSUE TITLE
[question] Conan 2 best practices for large scale software development

### ISSUE THREAD

**Issue by mattangus** [conan-io/conan#15910]
### What is your question?

Whenever I search for how to do something with conan there seem to be multiple ways to do it. This is a good thing in terms of it's flexibility, for existing conan project. However when starting new conan packages I would like to "do things the right way". Is there a place where some of these best practices, particularly at scale. A lot of the examples are great for getting started and learning conan. But when it comes to multiple interconnected complex packages, there doesn't seem to be a lot of information about it. The only package management experience I have is from the python world of `pip` and there are plenty of ways to do things, but the PEPs are quite opinionated as to what the right way to do it (as well as providing lots of warnings about deprecation).

A few couple general dev ops questions that I can't find answers to in the docs are:
1. managing settings/profiles/configs/options for teams of people
   1. Libraries should have customization points, but when developing on a team we should all use the same options/settings. Ideally tracked with git somehow so that CI can easily reference those same customizations.
   2. this is especially important for the final application being deployed. The libraries can have sensible defaults, but the application that's going to run will have a set of settings for each deployment. Ideally these settings would be shared amongst the other packages so the final downstream app only gets the binaries and doesn't have to build any of the dependencies. 
3. How to deal with monrepos

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mattangus 

Thanks for your question.

> Whenever I search for how to do something with conan there seem to be multiple ways to do it. This is a good thing in terms of it's flexibility, for existing conan project. However when starting new conan packages I would like to "do things the right way". Is there a place where some of these best practices, particularly at scale.

You are right, the documentation contains mostly the basics, and it is very recently that we are moving to more advanced topics, but still lots to do. We have thought about 2 different lines:

- Expanding and organizing the knowledge base, specially the "guidelines" part: https://docs.conan.io/2/knowledge.html
- New contents in https://docs.conan.io/2/devops.html, this is the section intended for "scale". We have started thinking the outline of doing CI at scale for this section.


> managing settings/profiles/configs/options for teams of people
Libraries should have customization points, but when developing on a team we should all use the same options/settings. Ideally tracked with git somehow so that CI can easily reference those same customizations.
this is especially important for the final application being deployed. The libraries can have sensible defaults, but the application that's going to run will have a set of settings for each deployment. Ideally these settings would be shared amongst the other packages so the final downstream app only gets the binaries and doesn't have to build any of the dependencies.

This is the reason we implemented ``conan config install`` functionality, to be able to share and install the same remotes, settings, profiles, plugins, hooks, global.conf, etc. If you haven't please have a look to https://docs.conan.io/2/reference/commands/config.html#conan-config-install

We have further added more new functionality with ``conan config install-pkg`` that allows to install configuration stored in a Conan package: https://docs.conan.io/2/reference/commands/config.html#conan-config-install-pkg, which allows to define version ranges, update more easily and efficiently, use lockfiles...

> How to deal with monrepos

This topic could take pages to discuss 😅 

The very short answer is that mono-repos and package/component based development are opposite paradigms of organizing and creating SW, both at the code and build level but also at the organization and people level. 
Mono-repos and package based development have different pros and cons, and it really depends on the organization and projects constraints and priorities to balance towards one or the other.

What is extremely challenging is to have both things at the same time. It is not possible to have a monorepo so developers can modify code in many different components at a time, and yet have a single and unified development project, and also have every one of those components to be independent and isolated packages that are built and published independently of each other. For monorepos, what is more important is having strong compilation caching tools and strategies, and a more "live-at-head" development philosophy.  Which is opposite to the package-based development that focus on developing and releasing the different packages in isolation, use versions to not break consumers of those packages, have more backwards and long time version maintenance, etc.

In general I would only recommend using Conan for a package-based development strategy. It is true that Conan contains some features, mainly the ``editable`` packages, that allow to work simultaneously on different interdependent packages in user space, in something more resembling a monolith. And we have started work on the "workspace" feature, basically an orchestration of several "editable" packages. But still the development experience would still not be as good as a real monolith with a single project build.

If at some point you'd like to talk with us, to discuss a bit more deeply these matters, please write to info@conan.io

**Comment by mattangus** [comment]
Thanks for the quick reply! I haven't read much from those two links so that's very useful thank you!

Just to make sure that we are talking about the same thing. I am not [meaning monolith, mono-repo](https://medium.com/@magenta2127/monorepo-vs-multi-repo-vs-monolith-7c4a5f476009) to me is a nice middle ground, and I think it can work with conan. I've been testing some of the different things available like `editable` to see how well it will all work together.

Anyway, I think you've answered the main reason I posted with the links, so I'll close this issue.
