### ISSUE TITLE
[question] Does conan download not have an option to download inside a given folder??

### ISSUE THREAD

**Issue by lupuleasa-core** [conan-io/conan#15913]
### What is your question?

Hi,

I noticed the `conan download` command does not have a "download to this folder" functionality
It only places it in the obscure conan cache, which if you are new to conan is not easy to visualize for demos
I want to send the command to my managers and colleagues to demo how easy conan is to use

I have performed this command

```conan download "myApplication/*" -r myRemote```

The binaries for the application are built and exported conan packages exist on our company Artifactory repo

I've been searching for a way to place the binaries in a folder without having to do a whole script for it. 
Does the conan download command not support "download to a folder"?

(for reference, I know conan install has deployers, for both runtime and build requirements, but I want something simpler to demo to my colleagues and to utilize for testing purposes)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @lupuleasa-core  - thanks for raising this question.

The `conan download` command is indeed intended to place the downloaded artifacts in the Conan cache.
 However, you have a couple of options:
 
* Use the `deployers` functionality, example:
```
conan install --require "cmake/3.28.1" -r conancenter --deployer=full_deploy --deployer-folder=./ 
```

(Have added the `--deployer-folder` for illustration purposes, that lets you control the output folder). Docs [here](https://docs.conan.io/2.0/reference/extensions/deployers.html).

* You can pipe the output of a `conan install` (or `conan download`) to the `jq` query tool, to print the location into which the package contents was downloaded (thanks @RubenRBS  for the hint!) , for example:
```
conan install --require "cmake/3.28.1" -r conancenter --format=json | jq '.graph.nodes[] | select(.ref | startswith("cmake/3.28.1")) | .package_folder'
```

The very last line printed will be the folder where it was downloaded.

**Comment by memsharded** [comment]
I'd like to add, that for packages with dependencies, there exist also the ``--direct-deploy`` to copy exactly that one package, but not its dependencies, for faster and cleaner deploy.

> It only places it in the obscure conan cache, which if you are new to conan is not easy to visualize for demos

I' also like to suggest considering too not copying the files, but running from the cache, thanks to the virtualenvs.
When ``conan install`` runs, it can generate ``conanrun.sh|.bat`` scripts, that can be sourced/activated and it will enable the execution of applications directly from the cache. This might have some advantages:
- Faster, because it doesn't need to copy anything
- Might work better in case of shared libraries, because the environment will also manage the paths and variables to locate the shared libraries
- It can be interesting to support running simultaneously (different terminals) different versions of the same app, or even the same version with different versions of the dependencies (different lockfile), or different binary configurations of the same app

Note that ``conan download "myApplication/*" -r myRemote`` will download multiple binaries, if there are more than 1 binary for different configurations, so it won't be clear which one is the one that you would like to run. The advantage of ``conan install --deployer`` is that it receives profiles as inputs, so it is completely explicit which specific binary configuration you want to test/run.

**Comment by lupuleasa-core** [comment]
Thanks everyone

**Comment by memsharded** [comment]
Closing the ticket as solved, don't hesitate to create new tickets for any further questions, thanks!
