### ISSUE TITLE
test_basic_parallel_install sometimes fail: `sqlite3.OperationalError: database is locked`

### ISSUE THREAD

**Issue by vivienreports** [conan-io/conan#15936]
### Describe the bug

Hello! Sometimes, the test_basic_parallel_install fail in conan 2.0.9. I believe https://github.com/conan-io/conan/pull/12930 is relevant, but not sufficient.

The full output https://bordeaux.guix.gnu.org/build/1c323339-9194-4e81-8624-d03e54964be5/log shows that this exception is thrown: `sqlite3.OperationalError: database is locked`

Best regards,

Vivien

### How to reproduce it

It only happens from time to time. We have a full backtrace here: https://bordeaux.guix.gnu.org/build/1c323339-9194-4e81-8624-d03e54964be5/log.

**Comment by memsharded** [comment]
Hi @vivienreports 

Thanks for your report.
Please upgrade to latest Conan, recall that only the latest patch of every minor is supported, that means that 2.0.9 is not supported, and 2.0.17 would be the minimal recommended. Conan 2.2.1 is already out, so this would be the most recommended one.

What you are reporting was fixed in https://github.com/conan-io/conan/pull/15029, for 2.0.14, so I think that if you upgrade, this should be gone.

Thanks again for your report.

**Comment by memsharded** [comment]
Did you manage to update @vivienreports ?

Can we close this ticket? Thanks.

**Comment by memsharded** [comment]
Closing ticket as solved
