### ISSUE TITLE
[question] How to disable recipe revisions in remote server?

### ISSUE THREAD

**Issue by mhabibav** [conan-io/conan#15937]
### What is your question?

I have a remote server set up and users can upload recipes and packages to it. How can I prevent uploading a different recipe revision of the same version of a package? _(How to do it from either the server side or the client side.)_

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mhabibav 

Thanks for your question

>  users can upload recipes and packages to it

Please not this is not recommended in the general case: https://docs.conan.io/2/knowledge/guidelines.html. In the majority of cases, only CI should upload packages to servers.

> How can I prevent uploading a different recipe revision of the same version of a package? (How to do it from either the server side or the client side.)

The server side, it might depend on the server, but I am not aware of this capability in most servers.
In the client side, it is not built-in, but it should be relatively easy to do a custom command that checks the server before upload with the ``list`` api, and the only ``upload`` if the server doesn't contain it.

However, I am not sure this would be a recommended practice in most cases, why would you want to block the possibility to do fixes and improvements to recipes? It is a very common scenario that some package needs some fixes to support a new platform or architecture, or maybe some improvements, or adding some extra files like licenses. These changes do not necessarily imply changes in the source code, and as such, it is not desired to create a new package version, because that would cause a misalignment between the original source, like specially while packaging third party open source libraries.

**Comment by mhabibav** [comment]
Thanks a lot for the detailed answer.
