### ISSUE TITLE
[question] How to build Poco MT library using conan 2.x

### ISSUE THREAD

**Issue by gjxo12** [conan-io/conan#15987]
### What is your question?

Hi, I am now trying to use poco library by applying conan to my project.
The environment is Windows 10 / Visual Studio 2022.
Profile settings are as follows.
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.version=193
os=Windows

I attach conanfile.py below.

```python
# https://github.com/conan-io/conan-center-index/blob/6e9c38af5640fc6dc1ba3dbd33ea6d7745a7c5a5/recipes/poco/all/conanfile.py
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMakeDeps, CMake, cmake_layout
from conan.tools.files import copy, load
from datetime import datetime
import os


class PocoConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

    def requirements(self):
        self.requires("poco/1.10.1")

    def layout(self):
        cmake_layout(self)
        

    def configure(self):
        self.options["poco/*"].enable_data = False
        self.options["poco/*"].enable_data_postgresql = False
        self.options["poco/*"].enable_data_mysql = False
        self.options["poco/*"].enable_data_sqlite = False
        self.options["poco/*"].enable_data_odbc = False
        self.options["poco/*"].enable_mongodb = False
        self.options["poco/*"].enable_redis = False
        self.options["poco/*"].enable_crypto = False
        self.options["poco/*"].enable_jwt = False
        self.options["poco/*"].enable_netssl = False
        self.options["poco/*"].enable_zip = False
        self.options["poco/*"].enable_active_record = False
        
        
    def package_info(self):
        print("package info....")
        if self.settings.os == "Windows" and self.settings.compiler == "msvc":  # MT or MTd
             self.cpp_info.defines = ["POCO_MT=ON"]
    

    def package(self):
        copy(self, pattern="*.lib", src=self.build_folder, dst=os.path.join(self.package_folder, "lib"), keep_path=False)
    
``` 

If you apply this file and build the Poco library with the `conan install conanfile.py --build=missing` command, it will be created as a .mdd file.

So, even if you try changing compiler.runtime in .profile and using cpp_infol.defines in package_info of conanfile.py, it is created as an MD library rather than an MT library.

I think I need to do something in `def configure`, but even looking at the documentation, it's not easy to solve.

Can I get some advice on this??

Lastly, I would like to know how to copy and paste libraries, .h files, and .cmake files created in paths such as C:\Users\name\.conan2\p\b\poco2d921cfcf79be\p\lib to a specific path.

Thanks.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @gjxo12 

Thanks for your question.

I think there is some misunderstandings:

- The ``package_info()`` is information for the consumers of the current package, not for the dependencies, neither for the current package. So this place is incorrect to define something like ``self.cpp_info.defines = ["POCO_MT=ON"]``. I'd recommend doing the full tutorial in the docs, but in this case this is the relevant section: https://docs.conan.io/2/tutorial/creating_packages/define_package_information.html
- The one defining if the Visual static runtime (MT) is used is the profile. In your case you have ``compiler.runtime=dynamic``, it should be ``compiler.runtime=static``.

As something to be aware, recipes in ConanCenter are not tested for all possible configurations. For example they are only built for the default, which is the dynamic runtime. It might be a possibility that some recipe in ConanCenter fails to build the binary when using different settings. In that case, it should be reported as something to improve in the recipe in ``conan-center-index`` (only if sure that is a recipe issue, otherwise you can report here and we will transfer the ticket if necessary)

**Comment by gjxo12** [comment]
@memsharded 
Okay, Thanks to your advise.
I'll check library and apply my C++ project.

**Comment by memsharded** [comment]
Thanks for the feedback.

If you don't have any pending question, you might close the ticket. 
You can open new tickets for any later question or issue. Thanks!
