### ISSUE TITLE
[question] No build info - includes paths etc

### ISSUE THREAD

**Issue by Aleksei-Badyaev** [conan-io/conan#15990]
### What is your question?

I need all the paths to the included project files, for which I previously used the file
conanbuildinfo.txt
This file is no longer available in the new version of Conan 2.
How do I get the necessary information that was previously in the file conanbuildinfo.txt ?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Aleksei-Badyaev 

Thanks for your question.

The ``--format=json`` of ``conan install/create`` commands will output a json file with all the graph information, including the package-folders. https://docs.conan.io/2/reference/commands/formatters/graph_info_json_formatter.html#formatter-graph-info-json

However, it is likely that there might be other ways to automate tasks in Conan 2, rather than reading the json file to gather the package-folders, like using a custom deployer (https://docs.conan.io/2/reference/extensions/deployers.html) or a custom command (https://docs.conan.io/2/reference/extensions/custom_commands.html) (which can be shared with ``conan config install``

Please let me know if this helps.

**Comment by Aleksei-Badyaev** [comment]
Hi @memsharded thank you very much for your explanation!

**Comment by memsharded** [comment]
Happy to help! 🙂 

Closing this ticket as responded, but please don't hesitate to create new tickets for any further question you might have. Thanks!
