### ISSUE TITLE
[question] Is there a mechanic to prevent packages being uploaded to public repos

### ISSUE THREAD

**Issue by LouChiSoft** [conan-io/conan#16019]
### What is your question?

What is the best method to prevent both accidental and malicious attempts to upload a package to somewhere other than our internal repo. Right now we just ask users to be careful when uploading, but something more concrete that prevents this from being able to happen would be nice

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @LouChiSoft 

Thanks for your question.

> What is the best method to prevent both accidental and malicious attempts to upload a package to somewhere other than our internal repo. Right now we just ask users to be careful when uploading, but something more concrete that prevents this from being able to happen would be nice

I am not sure what you mean. Repos need to be explicitly added by users, with ``conan remote add``, it is not that it is possible to upload something by accident to an arbitrary repo.

Then, repositories always have credentials, otherwise that would be a critical security flaw of the repo, and the repo would be taken down quickly by attackers, bots, etc. So even if you try to ``conan upload`` to a certain repo, the repo will almost surely block the upload, unless the user has write credentials.

Same model as Git, and github/gitlab, etc, it is not that easy to ``git push`` your code to an arbitrary remote that happens to be unprotected without credentials.

**Comment by LouChiSoft** [comment]
Sorry, to add more context. What I mean is that we have a repository that only people with the right permissions can pull from, same with git. But in the event that someone wanted to pull a repository, then push it to Conan Center for example, is there anything we can put in the conan.py file that will error out and say that it can't be pushed to that repository. I realise that this is a bit of an open ended question, I'm just fearful of someone accidentally pushing a protected IP to the conan center 😂

**Comment by memsharded** [comment]
> Sorry, to add more context. What I mean is that we have a repository that only people with the right permissions can pull from, same with git. But in the event that someone wanted to pull a repository, then push it to Conan Center for example, is there anything we can put in the conan.py file that will error out and say that it can't be pushed to that repository.

That would never be a problem, ConanCenter will reject the ``upload``. If ConanCenter allowed any user to upload anything without credentials, imagine the huge mess that it will be, like a complete disaster, this cannot happen. Even the maintainers cannot upload to ConanCenter, only a very specific job in CI can upload to ConanCenter.

This is why it doesn't make sense to try to protect it from the client side, this is not a problem that can happen.
In any case, depending on the production requirements you might want:
- Drop ``conancenter`` remote (you can do it in your ``remotes`` files, and share it with ``conan config install``.
- Build your own packages from ``conan-center-index`` fork, as recommended in https://docs.conan.io/2/devops/using_conancenter.html, and upload them to your own private server too.

**Comment by LouChiSoft** [comment]
Okay, that's good to know. I will forward that on to the rest of my team so we can be assured that that won't happen. Thanks
