### ISSUE TITLE
Dependency Manager NOT Package Manager

### ISSUE THREAD

**Issue by Yousha** [conan-io/conan#1602]
According to the Wiki definition(and SO answers), this **conan** project is a **Dependency Manager**, not Package Manager.
Package Manager is used for SYSTEM and **Dependency Manager for PROJECT**

> WIKI: A package manager or package management system is a collection of software tools that automates the process of installing, upgrading, configuring, and removing computer programs for a computer's operating system in a consistent manner.

https://en.wikipedia.org/wiki/Package_manager
https://stackoverflow.com/a/27290095/1429432

**Comment by memsharded** [comment]
clibs project??

Conan packages are not installed per-project, but they are shared between all projects.

Also, if we follow wikipedia, here you can find conan classified as a package manager: https://en.wikipedia.org/wiki/List_of_software_package_management_systems#Application-level_package_managers

You can find NPM, defined in https://www.npmjs.com as a package manager too.

**Comment by JPGygax68** [comment]
This is kinda interesting, because intuitively, I would have classified Conan as a dependency manager too, owing to its declarative way of specifying dependencies.

**Comment by Yousha** [comment]
I would like to know the difference between **apt yum pacman rpm** AND **conan**...
While they installs system Package and conan installs a just Source Library!

And AFIK, Maven Ant Gradle etc called Dependency Management not package management.

**Comment by lasote** [comment]
> While they installs system Package and conan installs a just Source Library!
Not source, binary libraries mostly. For me, the difference is just the location of where the libraries are installed. A path should determine the name? So in /usr/lib is a package manager but in other path is a dependency manager? 
Sorry but I think this conversation is not going anywhere.

Thanks for your interest.

**Comment by JPGygax68** [comment]
If I understood things correctly, Conan does not install sources only: when a binary is available for your platform, it will download that and won't bother rebuilding.

"Dependency management" of course can mean several things. Build systems have dependency management so that they know in what order to build targets. Conan has dependency management so that it knows what packages to download to deliver a top-level, programmer-specified dependency.

The way I see it, the main difference between Conan and the other package managers is that Conan aims to help programmers, exclusively. That is probably why it attempts to interface directly with build systems such as CMake, so that the programmer shouldn't have to worry about install locations.
