### ISSUE TITLE
[question] Is there a conan list command to list the latest reciperevison/pkgid/pkg revisions for a package?

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#16044]
### What is your question?

Hi!
If I have the package name is it possible to list the latest reciperevision/pkgid7pkgrevision for a package?
Is this correct : conan list * #latest
Thanks!
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @maitrey thanks a lot for the question

The `conan list` command by default already only looks into the latest revisions of each reference, so that `conan list "zlib/1.3.1:*"` for example shows, for the latest revision of 1.3.1, for each of its packages, only the latest package revision (That is, it's exactly identical in meaning to `conan list "zlib/1.3.1#latest:*#latest"`)

Note that here the `#latest` bit is inside the pattern query in the revision fields, and can be omitted as in the first example. Hope this helps :)

**Comment by maitrey** [comment]
So it should be used with a packagename and version? Is it not possible to query for latest versions of packages given a remote?

**Comment by memsharded** [comment]
``conan list zlib/* -r=myremote`` will give you the versions of ``zlib`` in that remote (sorted)

**Comment by maitrey** [comment]
Thanks! Ticket can be closed!
