### ISSUE TITLE
Check if it makes sense to guard against mistypes in certain properties

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#16042]
@valgur That's the second time I've been bitten by that exact problem, yes a check for that would be wonderful. [..]

_Originally posted by @Ahajha in https://github.com/conan-io/conan-center-index/issues/22599#issuecomment-2040323063_
            

if this seems like something that some people are falling for, maybe it's worth a check to whether we can help there, either a warning/error o silently fixing it

**Comment by Ahajha** [comment]
FWIW, searching through CCI I don't see this happening anywhere else, so either it was just a blunder on my part twice or the reviews have been good enough to catch it. That said, I still think it worth checking for, since currently the (cryptic) error will occur at package consumption time which is not ideal.

**Comment by memsharded** [comment]
Let's add ``check_type=`` argument to ``.get_property()``, similar to ``conf`` system
