### ISSUE TITLE
Managing lockfiles across Conan 1 and 2

### ISSUE THREAD

**Issue by santhonisz** [conan-io/conan#16056]
### What is your question?

Hi there,

Our organisation has a large number of private Conan 1 recipes. These are managed by a number of different product teams with some recipes belonging to "shared" packages that provide common functionality across teams. These teams will soon be moving to using Conan 2, though at different points in time i.e. some may not start the process for many months.

An interesting conundrum has arisen with our desire to start using lockfiles in Conan 2 - we have not used them at all in Conan 1. 

Consider the following:
- We have a recipe for a shared package that supports both Conan 1 and Conan 2.
- We wish to generate a `conan.lock` for Conan 2 and commit it to the repository.

The issue with this approach is if a product team that is (still) using Conan 1 contributes to the package, they will likely cause the `conan.lock` to be overwritten locally when they run `conan install` as it appears that command just regenerates the file using the Conan 1 schema. If the developer then commits that file, it breaks the ability for others to use the recipe under Conan 2 as it correctly identifies that the version of the lockfile is incompatible.

I realise we could use a non-standard lockfile name for Conan 2, but we don't want our large number of developers having to constantly remember to pass the `--lockfile` arg everywhere.

I see that Conan 2 no longer generates a `conan.lock` file when running `conan install`. I wonder if there's any scope to add a global.conf option to disable the auto-generation behaviour in Conan 1? Alternatively, in Conan 2 would it be possible to add a global.conf option to configure the default lockfile name e.g. something other than `conan.lock`?
 
Look forward to your thoughts.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @santhonisz 

Thanks for your question.

> I see that Conan 2 no longer generates a conan.lock file when running conan install. I wonder if there's any scope to add a global.conf option to disable the auto-generation behaviour in Conan 1? 

I have been having a look at this, but the problem is that there is some functionality in Conan 1 that relies on this file to be generated, for example all the "local flow" commands like ``conan build`` or even the ``test_package`` expect it to be there.

> Alternatively, in Conan 2 would it be possible to add a global.conf option to configure the default lockfile name e.g. something other than conan.lock?

Adding this conf in Conan 2 is not trivial either, and I don't love that this would be not a "real" Conan 2 solution, but adding something to the Conan 2 codebase to solve a problem of Conan 1.


Maybe the best approach would be to use a global env-var if that is possible in Conan 1, to change the default lockfile name from ``conan.lock`` to something different ``conan1.lock`` or the like, as it is not possible to just disable its generation. It is still not trivial, it must be added in several place, but could be. The reason it cannot be a conf is that it will be quite challenging to propagate the conf to all the places it is necessary, so a system (not a Conan one) environment variable would be the most effective.

Depending on many other factors, I'd probably try to trust developers to not commit the ``conan.lock`` while they are in Conan 1, but I don't know how big this pain might be. Maybe a pre-commit git hook that ``git checkout -- conan.lock`` or something similar in Conan 1 could be quite effective too.

**Comment by santhonisz** [comment]
Hi @memsharded,

Thanks for the prompt reply.

Based on your feedback I think it's fair to say that the burden for managing this probably falls on us. I had considered the notion of a pre-commit hook and I think we'll investigate it further to see if we can come up with a workable solution. 

Thanks again.

**Comment by memsharded** [comment]
Sounds good, many thanks!

If you find the burden as a git hook is also too much, or there is some big blocker, please let us know and we can reconsider an env-var based solution for Conan 1.
