### ISSUE TITLE
[question] Creating new files in a Visual Studio Solution using CMake

### ISSUE THREAD

**Issue by gitandeee** [conan-io/conan#16052]
### What is your question?

Hi!
If I create a new project, e.g. with 
`conan new -d name=foo -d version=1.0 cmake_exe`
then install and build it
`conan install . -s build_type=Debug`
`conan build . --build=missing -s build_type=Debug`

using these profiles

> Profile host:
> [settings]
> arch=x86_64
> build_type=Debug
> compiler=msvc
> compiler.cppstd=17
> compiler.runtime=dynamic
> compiler.runtime_type=Debug
> compiler.version=193
> os=Windows
> 
> Profile build:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=msvc
> compiler.cppstd=17
> compiler.runtime=dynamic
> compiler.runtime_type=Release
> compiler.version=193
> os=Windows

then I get a Solution file for Visual Studio in the `build` directory. When opening it and creating a new file, the file however ends up in the `build` directory and not in the `src` directory, like the other files. How can I create from within the solution the files in the `src` directory? If I switch to cmake view, then the project can't be compiled anymore.

Thank you in advance! Any feedback is appreciated!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @gitandeee 

Thanks for your question.

However, this wouldn't be specifically a Conan question, but a CMake+VS one.

When you are doing a CMake project, things need to be managed in the ``CMakeLists.txt`` file. You cannot add files in the IDE, because the VS project is a temporary artifact, that will get deleted and it is not committed to git.

So you need to add files in the ``CMakeLists.txt`` file.

**Comment by gitandeee** [comment]
Thank you very much!
