### ISSUE TITLE
[question] Providing shared libraries transitively 

### ISSUE THREAD

**Issue by MichaelDBendel** [conan-io/conan#16061]
### What is your question?

Hi!

Our structure is as follows:
* PackageA containing shared library `aa`
* PackageB containing shared library `bb`, which is depending on `aa`
* PackageC containing shared library `cc`, which is depending on `bb` plus executable `ccTest`, that links against `cc`.

During the build of `cc`, we execute the `ccTest` to validate it.

Issue can be reproduced using [this](https://github.com/MichaelDBendel/conantest/tree/main).

If its built on Windows with msvc (`/profiles/default` in the linked example), there is an `Error 3221225781 while executing` while `ccTest` is run.

We analyzed using Visual Studio:
`dumpbin /dependents .../cc.dll`
 -> shows dependency to `bb.dll` as expected, but not the transitive dependency to `aa.dll`
`dumpbin /dependents .../ccTest.exe`
 -> shows dependency to `bb.dll` (prosumably because only bb is used in the test executable and it inherits this dependency from `cc` which in return links agains `bb::bb` - so the dependency to `bb.dll` is already resolved instead of the dependency resulting from `packC/unittest/CMakeLists.txt` to `cc.dll`). But in order to use `bb.dll`, `aa.dll` has to be present as well.

If it is built for Linux (`/profiles/gcc-linux` in the linked example), we see: `.../ccTest: error while loading shared libraries: libaa.so: cannot open shared object file: No such file or directory`. So in fact the shared library of `aa` is missing for the execution of `ccTest`.

Our assumption was, that this could be resolved by adding `transitive_libs=True` to the `self.requires()` calls in packB or packC in order for the transitive dependency on `aa` (via `bb`) to be provided, but this didnt help the issue.

Used conan version on Windows: v2.1.0
Used conan version on Linux: v2.2.2

What is the correct way to resolve this without explicitly requiring `aa` from `cc` as well?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MichaelDBendel 

Thanks for your question and your reproducible code, that really helps a lot.

With this change I can make it work:
```diff
--- a/packC/conanfile.py                                                                
+++ b/packC/conanfile.py                                                                
@@ -45,10 +45,10 @@ class ccRecipe(ConanFile):                                          
         cmake.build()                                                                  
         if self.settings.os == "Windows":                                              
             test_folder = pathlib.Path.cwd().joinpath("unittest").joinpath("Release")  
-            self.run(f"{test_folder.joinpath('ccTest.exe')}")                          
+            self.run(f"{test_folder.joinpath('ccTest.exe')}", env="conanrun")          
         else:                                                                          
             test_folder = pathlib.Path.cwd().joinpath("unittest")                      
-            self.run(f"{test_folder.joinpath('ccTest')}")                              
+            self.run(f"{test_folder.joinpath('ccTest')}", env="conanrun")              
```

They key is that executing things needs the "run" environment activated, but by default Conan activates the "build" environment instead. If you check the folders when you ``conan install`` something, you will see that you have both ``conanbuild`` and ``conanrun`` environment scripts. The build one is intended for build time and it will typically contain the PATH of the ``tool_requires`` in the build context, like ``cmake`` etc, in order to find them to build. The ``conanrun`` will contain the PATH to the ``requires`` in the host context that are needed to run applications in the host context.

> Our assumption was, that this could be resolved by adding transitive_libs=True to the self.requires() calls in packB or packC in order for the transitive dependency on aa (via bb) to be provided, but this didnt help the issue.

No, this will be propagating the linkage requirement, but as you are using shared libraries, unless there is something very specific in the headers that requires static linkage from the consumers of those transitive headers, you don't want to put ``transitive_libs=True``, you should omit this. I have tested dropping it in Windows and it works.


Please let me know if this helps.

**Comment by MichaelDBendel** [comment]
Hi @memsharded 

Thank you for the extremely fast response!
This actually resolved the issue in the minmal example (both for Windows and Linux), but sadly not in my real code.

I will close this issue and reopen it, if I am able to reproduce it also in the minimal example again.
Thanks a lot!

**Comment by memsharded** [comment]
> I will close this issue and reopen it, if I am able to reproduce it also in the minimal example again.

Great, thanks for your feedback!
