### ISSUE TITLE
[question] Transitive options

### ISSUE THREAD

**Issue by BjarneLorenzen** [conan-io/conan#16062]
### What is your question?

I'm trying to automatically propagate the options set in my conanfile through the dependency graph.
In the configure method for each recipe I'd pass down the options to all requirements.
Something like :

```
def configure(self):
    for key, val in self.options.items():
      for req, dep in self.dependencies.items():
        self.options[dep].key = val
```

Is there any elegant way to do something like that?

Thanks!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @BjarneLorenzen 

Thanks for your question

> I'm trying to automatically propagate the options set in my conanfile through the dependency graph.
In the configure method for each recipe I'd pass down the options to all requirements.
Something like :

In general it is not recommended to setting options values in ``conanfiles`` as a general thing. It is much better to define options values in profile files instead. There are many reasons for this, but an important one, for example, is that options defined in recipes might not always work, because there can be conflicting values in different branches of the dependency graph, and the precedence and evaluation is not that trivial.

Also, instead of propagating the same exact values of options upstream in the graph, which might be problematic because it might require dependencies to define the exact same options, you can easily set the options for the whole graph with patterns. For example adding ``*:shared=True`` will apply to the whole dependency graph (host context and build context separately), for those packages defining the ``shared`` option, but not failing for those packages not defining the ``shared`` option.

**Comment by BjarneLorenzen** [comment]
Thanks for the quick answer, that approach sounds good!
