### ISSUE TITLE
[question] Is it possible to upload a package without adding it to the local cache first?

### ISSUE THREAD

**Issue by ottmar-zittlau** [conan-io/conan#16067]
### What is your question?

Hi,

I would like to build a package in a CI job - and also remove it afterwards.
Additionally I want to keep a conan cache on the runner (we currently can't use prebuilt packages), so this is supposed to avoid building all dependencies each time.
If multiple jobs are running on this machine in parallel I want to avoid that they somehow conflict with each other (in particular the situation that one job requires a package that has been deleted by another job).

I tried so far to locally create my package by doing the following:

```
[I'm starting in the folder where my conanfile.py is]
mkdir build
cd build
conan install ..
conan build ..
conan package ..
```
At this point I have a folder containing my package.

Can I now upload this package to a remote registry with `conan upload`?
From the documentation it seems that the upload always requires packages to come from the local cache.

Thanks and best regards
oz

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ottmar-zittlau 

Thanks for your question.

I deduce you are talking about Conan 1, because the command ``conan package`` has been removed in Conan 2.

It is not possible to upload directly from the user space, it is necessary to put packages first in the cache. 

There are some mechanisms that could help in your case:
- If you have the package locally, you can put it in the cache easily and fast with ``conan export-pkg``
- You can use a different local cache with the CONAN_HOME (CONAN_USER_HOME in Conan 1), you can even point it to a local folder in your project if you prefer.

> If multiple jobs are running on this machine in parallel I want to avoid that they somehow conflict with each other (in particular the situation that one job requires a package that has been deleted by another job).

The Conan cache is not concurrent in any case (it might be in the future, but not yet), so in general for parallel jobs in CI the recommendation is that every job has its own cache to avoid race conditions in the cache. Using the new ``conan cache save/restore`` functionality in Conan 2 can help moving packages from one cache to another.

> Additionally I want to keep a conan cache on the runner (we currently can't use prebuilt packages), so this is supposed to avoid building all dependencies each time.

The recommendation is to use a package server, a cache is just that, a cache, it is not designed as a replacement of using a package server, specifically when there is parallelism and concurrency like in a CI server.

**Comment by ottmar-zittlau** [comment]
Thanks a lot for the quick reply. I think that the CONAN_USER_HOME approach is the most promising for my purpose at the moment.
