### ISSUE TITLE
[question] Prevent installation of Static dependencies if binary exists

### ISSUE THREAD

**Issue by huysentr** [conan-io/conan#16072]
### What is your question?

Greetings I was wondering the following. 
Lets say I have a conan package Foo, Foo requires A, B and C but they are all statically linked. I have uploaded Foo to a remote. With binary and everything. 

I have project Bar. Bar requires Foo. Can I prevent Bar requiring A, B and C? Since I would only need A, B and C If I were to rebuild Foo. But the Foo binary is available.

Can I prevent requirements of statically linked packages that are at least one level deep? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @huysentr 

> I have project Bar. Bar requires Foo. Can I prevent Bar requiring A, B and C? Since I would only need A, B and C If I were to rebuild Foo. But the Foo binary is available.

Conan will automatically model and manage that, given that ``option shared`` is defined or the ``package_type`` is correctly defined. When Conan detects and executable or shared library depending on static libraries, by default will be able to mark those dependencies "Skip" and avoid completely the download of that dependency static library binary, and also to link (it would be overlinking in most cases) to it.

Still the dependency graph of "recipes" is computed. This is relatively quick, as recipes are very lightweight, it is not a big overhead, but it is critical for the correct behavior. Because Conan also knows that it the dependency version or revision of the static library has changed, then it actually needs to re-build from source the executable or shared library to make sure it re-links the static library dependency with the changes. But as long as the dependency doesn't change and a binary exist for the executable/shared library, Conan will skip downloading the binaries of those static libraries.

**Comment by huysentr** [comment]
Hi @memsharded 

Thank you, that is clear. Now a follow-up on this case. What if:
Bar does have a dependency on A. However it is shared, and it is a different version as well. What are my options here? Foo is not a shared-lib it is a executable, that is ran at some stage after Bar is finished building, preferably Foo and Bar are shipped together to some install folder.

**Comment by memsharded** [comment]
I'd need to understand better your dependency graph.

Above you say:

> Bar requires Foo.

But if ``Foo`` is an executable, it doesn't make sense, it would only make sense if it is a ``tool_requires``.

If you can please make a bit more explicit and clear the full dependency graph, with the type of every package in the graph, that would help. Thanks!

**Comment by huysentr** [comment]
You are correct, I suppose that could solve the issue. Thank you.

**Comment by huysentr** [comment]
If Foo were a shared-lib and not an executable would that pose an issue?

**Comment by memsharded** [comment]
> If Foo were a shared-lib and not an executable would that pose an issue?

Not sure, I don't fully understand the whole picture. If you can please specify the full graph, with the type of each package, that would help. Please try something like:

app/1.0(exe) -(requires)-> liba/1.0(static) -(requires)-> libb/2.0(shared)
app/1.0(exe) -(tool_requires)-> cmake/3.25(exe)

**Comment by huysentr** [comment]
app/1.0 -(requires)-> liba/1.0(shared) - >(requires)-> libb/1.0(static)
app/1.0 -(requires) ->libb/2.0(shared)

**Comment by memsharded** [comment]
I see.

If ``liba`` is able to fully embed and isolate ``libb`` as an implementation detail, mostly no headers of ``libb`` included in public headers of ``liba`` and no API or ABI leakage of ``libb`` over ``liba`` interfaces, then it is possible.

The way is ``liba`` declaring:
```python
self.requires("libb/1.0", visible=False)
```
that avoids the propagation of ``libb`` over ``liba`` and reaching ``app/1.0`` with a different version.

It is just important to recall that there can be different things inside libraries such ``libb`` such as static or globally initialized objects, system singletons access, etc, that might break the above assumptions and are not as evident as the public headers being propagated and colliding.

**Comment by huysentr** [comment]
Okay that is clear. Thank you.

**Comment by memsharded** [comment]
Thanks for the feedback, can we close the ticket as solved then? Thanks
