### ISSUE TITLE
External repository fetch / link

### ISSUE THREAD

**Issue by yoni386** [conan-io/conan#1610]
Can Conan fetch and link library from external repository for c++ (e.g. github)? 
As in Cargo (Rust), go, nodejs and etc?

Example:
gem "nokogiri", :git => "git://github.com/tenderlove/nokogiri.git", :branch => "1.4"
1) Is this something Gradle would consider supporting in the future (or does it already)?

dependencies {
     compile git: "git://github.com/someproject/someproject.git", branch: "1.4"
}

**Comment by memsharded** [comment]
No, it is not possible. Conan packages have to be retrieved from a conan remote repository (conan_server, bintray, Artifactory). One of the most important reasons for this, is that conan packages also store pre-compiled binary packages, not only sources as other package managers, and also binaries for many different platforms, so the size can be huge, and not feasible in git repos.

Conan recipes, however can retrieve the source code from a git repo, to build from sources. Examples are in the conan docs.

**Comment by target-san** [comment]
Though, can't Conan support Git as a source for no-binary case? IMO need to set up completely separate server is sometimes not very feasible, or even not possible. Maybe some convention like storing recipe descriptor in separate repo's branch like 'conan' ? This way, some tiny company can setup just local git repo and have dependency management out of the box.

No C++ package managers I've seen so far allow to use bare repo as package source. All of them require to either use public repo or setup your own server - for no obvious reason. And this utterly hinders their usage.

**Comment by memsharded** [comment]
What would be the mapping from PackageName, PackageVersion, PackageUser and PackageChannel to a git repo?

**Comment by target-san** [comment]
PackageVersion can be mapped from version number to commit hash, using a mapping file stored in a branch with conventional name.
Other pieces seem to be used to identify package and thus all three are replaced with Git repo path.

**Comment by memsharded** [comment]
Who is the one defining the map? Where is such map stored? Lets say you are a conan user, and you want to install: ``Pkg/1.2@myteam/stable``. There will be also other versions, and you also can change the user and channel, and those are different packages.

With conan, using a conan server, right now you can do:
```
[requires]
Pkg/1.2@myteam/stable
```
Then, ``conan install``

This also works for transitive dependencies. So ``Pkg/1.2@myteam/stable`` can have a dependency to other package declared as ``Lib/1.0@mycompany/production``, and so on.

Then, it has to be possible to override dependencies, so from downstream, you could do:
```
[requires]
Pkg/1.2@myteam/stable
Lib/1.1@mycompany/testing
```
then ``conan install``, and the new Lib/1.1 will be used instead of the previous one.

What would be your proposed UI?

**Comment by target-san** [comment]
If I'm not mistaken `<PackageUser>/<PackageName>` is in fact the full name of package, which consists of namespace part and actual name part. Next, `<PackageVersion>-<PackageChannel>` is in fact full version of package, if roughly mapped to semver.
Thus, we'll have roughly this:
```
[requires]
Pkg = { git = "<path-to-repo>", version = "<version>@<channel>" }
```
or
```
[requires.Pkg]
git = "<repository>"
version = <version>
channel = <channel>
```
Or whatever syntax will be used.

**Comment by memsharded** [comment]
I am not sure about what you mean. 

Lets say you are the developer of "LibraryA", and you you have it in ``http://mygithub.net/myuseraccount/libraryA`` repo. Which branches will you have in your repo to create packages for:

- LibraryA/1.0@myuser/testing
- LibraryA/1.0@myteam/testing
- LibraryA/1.0@myteam/stable
- LibraryA/1.0@myteam/production
- LibraryA/1.0@mycompany/production
- LibraryA/1.1@myuser/testing
- LibraryA/1.1@myteam/testing
- ...

**Comment by target-san** [comment]
Then, according to your layout, it will be 3 repos

* `https://mygithub.net/myuser/libraryA`
* `https://mygithub.net/myteam/libraryA`
* `https://mygithub.net/mycompany/libraryA`

Each of these repos can have branch named `conan` or `conan.io` or whatever conventional name.
Then, this branch will have proper declaration of all package versions stored in this repo
```
# https://mygithub.net/myuser/libraryA/conan/versions.txt
1.0@testing <git object name or commit hash>
1.1@testing <git object name or commit hash>
```

```
# https://mygithub.net/myteam/libraryA/conan/versions.txt
1.0@testing <git object name or commit hash>
1.0@stable <git object name or commit hash>
1.0@production <git object name or commit hash>
1.1@testing <git object name or commit hash>
```

```
# https://mygithub.net/mycompany/libraryA/conan/versions.txt
1.0@production <git object name or commit hash>
```

Anyway, as I said, this is more intended for simple one-repo, one-maintainer package. Users wishing for sophisticated behavior can run Conan repository locally. Although, why not have simple scenario for simple uses?

**Comment by memsharded** [comment]
Still not defined. If LibraryA now depends on LibraryB, how would it declare such dependency in its own ``conanfile.py``, how it will be overriden from downstream, or conflicts resolved when the version doesn't match? Then you have to do recursive git clones to get the recipes that have to be evaluated, remove the clones... 

We have already evaluated this a few times, the complexity skyrockets, for very little added value in real world use cases. It is not a simple scenario, as soon as you start to deep dive into the problem, things get ugly. You are only talking about addressing dependencies for one package without dependencies, and you are already splitting the repo into 3 forks, and creating some branches named by convention, to redirect to other git objects, forcing users to hardcode channels in repos (something that with the current model it is not necessary at all, you can easily promote packages from testing->stable->etc without changing a single line of code or modifying any repo).

I use java and python a lot. I have never, ever, retrieved a single dependency from git with pip. Maven for java, used by millions of developers, and the most stablished tool in development of huge projects in enterprise (the closest to C and C++ market), doesn't implement the retrieval of packages from git repos from sources.

**Comment by target-san** [comment]
> Still not defined. If LibraryA now depends on LibraryB, how would it declare such dependency in its own conanfile.py,

The same as today, no?

> how it will be overriden from downstream, or conflicts resolved when the version doesn't match?

The same as today, no? How does Conan resolve conflicts where there are A, B, C, D, and A depends on B and C, and B and C depend on D, but of different versions?

> and you are already splitting the repo into 3 forks

As I said, if one would want to wake such complexity upon his head, he'd deploy Conan repository. I'm talking about small cases where there are no multi-user quirks and complexities. Just several versions inside single repository.

>  you can easily promote packages from testing->stable->etc without changing a single line of code or modifying any repo

You're doing this in fact, just hiding changes to config inside server.

> I use java and python a lot. I have never, ever, retrieved a single dependency from git with pip. Maven for java, used by millions of developers, and the most stablished tool in development of huge projects in enterprise (the closest to C and C++ market), doesn't implement the retrieval of packages from git repos from sources.

On the contrary, `npm`, `go get`, `cargo` either do exactly this or allow this as an option. This way they effectively leverage existing infrastructure.

The problem is, C++ world is heavily fragmented in terms of tools. There's no C++ Maven, and every small company reinvents its own wheel. And each package manager for C++ I've seen requires to store package in its own repository format. I'm not even talking about adding side package declaration to existing repository without changing its code. So, why would I choose Conan, over something like Hunter? Requirements are the same, but Hunter requires only CMake and no sidekick dependencies like Python.

**Comment by lasote** [comment]
> So, why would I choose Conan, over something like Hunter? Requirements are the same, but Hunter requires only CMake and no sidekick dependencies like Python.

Well, there are many other interesting features, but if the only important for you is not depending on python and grab git repositories, yeah, use Hunter. 📦

**Comment by target-san** [comment]
> Well, there are many other interesting features, but if the only important for you is not depending on python and grab git repositories, yeah, use Hunter. 📦

Because it has the same limitation. Only through package repository.

**Comment by memsharded** [comment]
> The same as today, no?

No, you want to make possible to depend directly on git repos. So this also has to change.

> The same as today, no? How does Conan resolve conflicts where there are A, B, C, D, and A depends on B and C, and B and C depend on D, but of different versions?

No. Conflicts can be resolved, because finding, retrieving, overwriting upstream dependencies is much simpler if things are just done with one API call. You can just override the package references, and propagate them, which is semantically easy. But how would you handle conflicts of the same package reference dependency that is using two different repos?

This is extremely complex feature for the value it provides. But I might be totally wrong, if you think this is a simple feature to implement and maintain, PRs are welcome.
