### ISSUE TITLE
[bug] ConanFile.run() expects command to be a string (not a list of strings), even when shell=False

### ISSUE THREAD

**Issue by Tails86** [conan-io/conan#16100]
### Describe the bug

conan version: 2.2.3

I've been updating my conanfiles for conan 2, and I have found that I can no longer use subprocess directly in order for reports to work correctly (need to output directly to stdout instead of any potential pipped stdout). I've been trying to instead use Conanfile.run(), but I can't seem to run this:
```py
self.run(['./custom_script.sh', 'arg1'], shell=False)
```

The output I get is this:
```
Error: [Errno 2] No such file or directory: '. "/path/to/project/conanbuild.sh" && [\'./custom_script.sh', \'arg1\', ]'
```

It looks like ConanFile.run() expects `command` to be a string, regardless of the value of `shell`. Normally, if I set `shell=False` for subprocess (the default in that case), I can pass a list of strings and not have to worry about quoting things. I have to use `self.run(subprocess.list2cmdline(['./custom_script.sh', 'arg1']), shell=True)` as a workaround.

**Comment by memsharded** [comment]
Hi @Tails86 

Thanks for your report.

This wouldn't be a bug, but this change was deliberate.

The ``ConanFile.run()`` input goes through different stages before being forwarded to the ``subprocess``:

- The CommandWrapper plugin is applied
- The environment scripts are applied, wrapping the command
- The Windows subsystem scripts are applied, further wrapping the command.

Each stage creates different wrappers, and forwarding the list of arguments to the ``subprocess`` is not possible, it needs to be already a string for this wrapping to occur.

Also, it is not possible to rely internally on ``subprocess.list2cmdline`` because that is undocumented and we cannot take the risk inside Conan to rely on undocumented Python api, it can break anytime.

So this has been delegated in Conan 2 to be a recipe responsibility. In the vast majority of cases assembling the command would be very easy. If users want to rely on ``subprocess.list2cmdline`` that is up to them.
