### ISSUE TITLE
[bug] `[platform_requires]` does not work with `ConanFile.dependencies`

### ISSUE THREAD

**Issue by stevenwdv** [conan-io/conan#16124]
### Describe the bug

When marking a package `mypkg` as provided by the system using `[platform_requires]` in the profile, a package depending on `mypkg` may use `self.dependencies['mypkg']`, which then crashes.

I'm not sure if there's a good solution for this, because it's not clear what should happen when the package then uses `self.dependencies['mypkg'].options.some_option`.
A workaround may be to use `[replace_requires]` instead, but although it allows specifying the right option values for the platform package, it is more work.

Related to #15685

### How to reproduce it

- Add to Conan profile:
  ```
  [platform_requires]
  openssl/3.2.0
  ```
- Install `libcurl`
- Get error: [\[`libcurl` conanfile.py\]](https://github.com/conan-io/conan-center-index/blob/181ce6deec30a6570c1fcabdd36e3b6280ffa95a/recipes/libcurl/all/conanfile.py#L201-L202)
  ```
  ERROR: libcurl/8.6.0: Error in validate() method, line 201
          openssl = self.dependencies["openssl"]
          KeyError: "'openssl' not found in the dependency set"
  ```

**Comment by memsharded** [comment]
Hi @stevenwdv 

Thanks for your report.

This wouldn't be a bug, but expected behavior.

``platform_requires`` can only work if the consumers are abstracted away of the details of the package. Any consumer that needs specific information from the package, like the ``curl`` recipe via ``self.dependencies["openssl"]`` cannot work and won't work with ``platform_requires``, there is nothing Conan can do about it check in libcurl recipe:

```python
if self.options.with_ssl == "openssl":
            path = unix_path(self, self.dependencies["openssl"].package_folder)
            tc.configure_args.append(f"--with-openssl={path}")
```

Conan cannot automagically produce, detect or invent a ``package_folder`` to a system installed openssl (or any other library) for every platform out there. This is just an example, the amount of information that might be necessary can vary a lot, and there is no way that Conan can deduce it. So the only possibilities are:

- Make the recipes like ``libcurl`` completely agnostic of the dependency
- Use the recommended ``[replace_requires]``, as suggested in the docs

> A workaround may be to use [replace_requires] instead, but although it allows specifying the right option values for the platform package, it is more work.

This is not a workaround, this is the right approach, the only possible one. Please read the details in https://blog.conan.io/2024/02/20/Conan-2-graph-features.html

**Comment by stevenwdv** [comment]
I see, Ok thanks for the info!
