### ISSUE TITLE
Support chocolatey package manager

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1612]
![Chocolatey support](http://i.imgur.com/nT8Fo63.jpg)

Hi!

We have a great support for Linux, Solaris and FreeBSD now, but not for Windows.  
My intention is include `choco` as default package manager for Windows on Conan.

Regards.

**Comment by memsharded** [comment]
You mean as a ``SystemPackageTool`` right? That would be great.

**Comment by uilianries** [comment]
That's it.

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by uilianries** [comment]
@memsharded Could you include this issue on 0.26?

**Comment by memsharded** [comment]
Currently, the tests fail in my machine because I don't have choco installed myself. 
Not sure about the approach, if we should change the test

**Comment by uilianries** [comment]
Of course, but Appveyor has Choco by default. We to add a test to an environment without choco.

Anyway, choco could be optional. It is not a native package manager:

```python
# tools.py:626
elif os_info.is_windows and is_choco_installed():
    return ChocolateyTool()
```

**Comment by memsharded** [comment]
Yes, something like that. As choco is optional, and in fact, won't be in many user machines, we need to throw an Error, saying that choco is not installed, if the package author intends to use choco and it is not installed.

I am also just thinking that this feature could have broken something: for recipes that were relying on the fact that in Windows there was no tool, then the ``NullTool`` was being used, and it silently skipped packages that would be installed in other OSs, now they will fail:
- Because choco is not installed
- Maybe choco is installed, but the package doesn't exist in choco.

**Comment by uilianries** [comment]
Yes, you are correct. I didn't check that NullTool doesn't raise an error on Windows, just a warning message. My fault. 

So, I'll revert to use NullTool by default on Windows. ChocoTool will be present only as optional.

Thanks for the feedback. I fix ASAP.

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
