### ISSUE TITLE
[bug] Transitive package's header is NOT visible

### ISSUE THREAD

**Issue by littleangel0309** [conan-io/conan#16139]
### Describe the bug

OS: Windows 10 WSL2 Debian
Compiler: Clang 18
Conan version: 2.2.3
Conan profile:
```
[settings]
os=Linux
arch=x86_64
build_type=Release
compiler=clang
compiler.version=18
compiler.libcxx=libc++
```
Description:
I am creating a library based on Google Protocol Buffer. I `#include` its header in my header. Then test_package will fail when compiling, saying protobuf's header not found.

### How to reproduce it

1. Create brand new packge. `conan new -d name=bug-example -d version=1.0.0 cmake_lib`
2. Add requires `protobuf/3.21.12` to conanfile.py.
3. Add `find_package(protobuf)` then link `target_link_libraries(bug-example PUBLIC protobuf::libprotobuf)` to CMakeLists.txt.
4. Include its header in my header. `#include <google/protobuf/message.h>` in include/bug-example.h
5. Create Conan package. `conan create -b missing .`
6. It succeed when installing package itself. But fail when compiling test_package.
   ```
   In file included from /xxx/test_package/src/example.cpp:1:
   /home/xxx/.conan2/p/b/bug-e8befe5daa5436/p/include/bug-example.h:6:10: fatal error: 'google/protobuf/message.h' file not found
       6 | #include <google/protobuf/message.h>
         |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
   1 error generated.
   ```

**Comment by littleangel0309** [comment]
Oh. I figure it out. I should add transitive_headers and transitive_libs trait to the requires.

**Comment by memsharded** [comment]
Hi @littleangel0309 

Thanks for the question and for following up and closing.

Just a clarification:

- ``transitive_headers=True`` is relatively common, it happens when headers from the dependencies are included in public headers of the current package, effectively  making them required and exposed in the interface, then "transitive" to the consumers.
- ``transitive_libs=True`` would be a way more exceptional situation. Conan already knows how to correctly propagate linkage requirements of the different package types, for example an executable linking a static library package "liba" that in turns depends on another static library package "libb", doesn't require "liba" to do a ``self.requires("libb..", transitive_libs=True)``, and Conan will progate to the executable that it needs to link with ``libb``.

**Comment by littleangel0309** [comment]
You are right. The question above should only add transitive_headers.
