### ISSUE TITLE
[question] `conan remove` pattern format

### ISSUE THREAD

**Issue by db4** [conan-io/conan#16165]
### What is your question?

From `conan remove --help` output:
```
positional arguments:
  pattern               A pattern in the form 'pkg/version#revision:package_id#revision', e.g: zlib/1.2.13:* means all binaries for zlib/1.2.13. If revision is not specified, it is assumed latest one.
  ```
What does the second `revision` in the pattern mean? I could assume it's PREV, but they have been removed from Conan 2. Can you clarify?
  

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @db4 

Thanks for your question.

> What does the second revision in the pattern mean? I could assume it's PREV, but they have been removed from Conan 2. Can you clarify?

The package-revisions have not been removed, they already exist and they can be listed with ``conan list`` as the pattern help describes.

What has been removed in Conan 2 is the influence of package-revisions into the consumers ``package_id``, or the ability to lock a specific package revisions, because they are assumed to be unnecessary and mostly a result of a process or model error. But they are still stored and visible, so it is possible to be aware of such process or model error (or for extreme cases of environment malfunctions that is necessary to force the rebuild of binaries without a model change).
