### ISSUE TITLE
[question] how to ignore compiler version in package resolution?

### ISSUE THREAD

**Issue by igagis** [conan-io/conan#16185]
### What is your question?

For example, `conan-central` only provides binray packages of `zlib` for `macos` built with compiler version 13, while on my system I have 14, so I cannot use those packages. But, I think likely the ABI wil be the same, so I don't care that much about which version of `clang` was used to build the `zlib` binaries and would like to install the package which is available, i.e. built with `clang` version 13. But `conan` doesn't allow that at the moment.

See example build:
https://github.com/cppfw/papki/actions/runs/8893510760/job/24419841050#step:10:87

Is there a way to tell conan to exclude compile version from consideration when identifying a package?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @igagis 

Thanks for your question.

Yes, there are different ways that Conan can manage this:

- You can specify your dependencies version with ``-s compiler.version=13 -s &:compiler.version=14``, which means, use ``compiler.version=13`` for your dependencies, but use 14 for your current consumer.
- If you want to define different versions for different packages, it is also possible, you can do it too using the package names as patterns. Check https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns for more info.
- You can explicitly define the fallback binary compatibility between binaries, you can add a rule to the ``compatibility.py`` plugin that implements a fallback from ``compiler.version=14`` to ``compiler.version=13``. Check https://docs.conan.io/2/reference/extensions/binary_compatibility.html
- A very recommended approach is to build your dependencies for ``compiler.version=14`` and store your own binaries in your own server. This is the most recommended approach for production environments, not only for this use case, but for all different platforms, and binaries. See https://docs.conan.io/2/devops/using_conancenter.html

Please let me know if this clarifies the question.

**Comment by igagis** [comment]
Hi, thanks for reply. Sorry for long delay.

Actually, ideally I'd like to have some per-package solution, like tell that for this package it doesn't matter what is the compiler version of dependent packages.

Right now, in the `conanfile.py` of the package I create there is a line `settings = "os", "compiler", "build_type", "arch"`. What does it mean? Does it mean that this package will resolve dependencies with matching os, compiler, build_type, arch?
I tried to remove `compiler` for there, but it made no difference. It still wants `zlib` with compiler version 14 and does not find it.

Is there a way to make the solution per package instead of system wide?

**Comment by memsharded** [comment]
The configuration of settings is already per package, you can specify the settings you want for every package in the dependencies.

What is not possible is to make that consumers of a package will automatically be independent of the compiler version. I am still not sure if I get the use case, because those things doesn't seem related. The fact that some package is requiring ``zlib`` for example with a ``requires("zlib/1.3")`` doesn't make its binaries independent of the ``compiler.version``, like those are completely unrelated things. The ``compiler.version`` affects the binary of every package that is built (not header-only, of course), together with other different settings and options. Requiring one dependency doesn't change that at all

> Right now, in the conanfile.py of the package I create there is a line settings = "os", "compiler", "build_type", "arch". What does it mean? Does it mean that this package will resolve dependencies with matching os, compiler, build_type, arch?

Those are the settings that have effect on the ``package_id`` or in the binary built for the current package. It is not related to other packages that could define other ``settings``, for example ``header-library`` packages can define no ``settings`` at all.

> It still wants zlib with compiler version 14 and does not find it.

You can do ``-s zlib/*:compiler.version=xxx`` to specify the compiler version you want for ``zlib``.

I think I still don't fully understand the use case.

**Comment by igagis** [comment]
Well, the question is more conceptual. It doesn't matter which compiler version was used to build the binary. What matters is the ABI compatibility. And if it is known that ABI breaks, then the package version should be incremented. So, I see no reason to divide package binaries by the version of compiler used to build them.

Of course it matters which compiler is used, i.e. binaries for MSVC are not compatible with GCC. But the version of the compiler does not matter.

As far as I can see right now it is not that easy to tell `conan` to ignore compiler version in package binaries resolution. I mean not saying that even though I have 14, please use 13 for this and that package, but ignore at all for all packages.

**Comment by memsharded** [comment]
>  It doesn't matter which compiler version was used to build the binary. What matters is the ABI compatibility. And if it is known that ABI breaks, then the package version should be incremented. So, I see no reason to divide package binaries by the version of compiler used to build them.

It doesn't matter in an ideal world. In a real world there is too much code out there that contains conditional preprocessor #ifdefs conditioned on the compiler version that changes not only the ABIs, but sometimes even the APIs. So Conan defaults to taking into account the ``compiler.version`` into the default binary model.

However, that is only the Conan default, but as commented above there are different approaches in Conan to change and customize this binary model. None of them are related to dependencies, because it doesn't matter if you depend on zlib or not to model our own binary compatibility.

> As far as I can see right now it is not that easy to tell conan to ignore compiler version in package binaries resolution. I mean not saying that even though I have 14, please use 13 for this and that package, but ignore at all for all packages.

I am not sure what is the gap here. This is completely straightforward, it is enough to specify it to conan directly on the profiles, for example, if we want to use 14 for all packages but 13 for zlib and bzip2:
```
[settings]
...
compiler.version=14
zlib/*:compiler.version=13
bzip2/*:compiler.version=13
...
```

And that is all, just direct specification of what you want.

Then, you also have the ``compatibility.py`` plugin that allows you to explicitly model your binary compatibility, with a few lines you can define the binary compatibility rules that you want.

**Comment by igagis** [comment]
Ok, my point is also on the usability side. I'm building a package of my library which depends on `zlib`. So, when building my package I want to ignore compiler version of dependencies. Also, when using the package I want that compiler version of `zlib` would not be considered.

I can achieve this by modifying conan profile specifically saying compiler version for `zlib`, or modify `compatibility.py`.
Now, imagine how to do it on CI. Probably I have to use `sed` for profiles to add those `zlib` specific lines, or even better, for adding snippets of code to `compatibility.py`. This definitely looks like a hackish way.
Also, this adds additional requirements for the usage of my library package, i.e. user must specify `zlib` compiler version on their profile. This is not user-friendly.

What would be acceptable is if it was possible to add those `zlib` compiler version exceptions straight to `conanfile.py` of my library, so that on CI conan would take this into account when installing build dependencies. Also, users of my library package would not have to worry about customizing their conan profile.

**Comment by igagis** [comment]
Sorry if I possibly still misunderstand something :)

**Comment by memsharded** [comment]
> I can achieve this by modifying conan profile specifically saying compiler version for zlib, or modify compatibility.py.
Now, imagine how to do it on CI. Probably I have to use sed for profiles to add those zlib specific lines, or even better, for adding snippets of code to compatibility.py. This definitely looks like a hackish way.

No, this is not recommended. The way it works is you define the profiles you want, or the ``compatibility.py`` you want, and you share it with your team/users and install it (together with other configuration, like remotes, custom settings, etc), with ``conan config install/install-pkg``. This way it is very easy to keep all your users and CI agents using the same binary compatibility rules, either if defined in profiles or if defined in ``compatibility.py``, for the users, it is transparent.

> Also, this adds additional requirements for the usage of my library package, i.e. user must specify zlib compiler version on their profile. This is not user-friendly.

If we are talking about open-source usage, like ConanCenter, this wouldn't be recommended. As described above, there are many cases that there will be no binary compatibility, and the errors derived from it will be order of magnitude more difficult to understand and debug. They might also be errors that are not detected until runtime. 

The way this is approached is by letting the user know that there is not binary for their current settings "Missing binary", and they can easily build a binary for their settings with ``--build=missing``. This is way more robust than trying to assume that any package compiled with any compiler version will work for users using any other compiler version.


> What would be acceptable is if it was possible to add those zlib compiler version exceptions straight to conanfile.py of my library, so that on CI conan would take this into account when installing build dependencies. Also, users of my library package would not have to worry about customizing their conan profile.

This is not possible, because this is not a function/responsibility of the ``conanfile``. For your package it might be acceptable, but in a larger dependency graph with other packages also requiring a dependency like ``zlib``, there can be other kinds of incompatibilities, so forcing that from a specific package to all other packages using ``zlib`` is not intended.


To summarize, depending on the usage:

- For open-source, the current default model has been working quite robustly, with very little ABI errors. For users using different compiler versions that could result in "Binary missing" error, because some dependency was not built with the same ``compiler.version``, the ``--build=missing`` to build from source has also been working well
- For internal/private usage within organizations, the control is absolute, via your own ``profile`` files where you can specify exactly what you want or with a custom ``compatibility.py`` binary model specifying the behavior you want. Both ways are mostly transparent to users of the packages, because they will get both things automatically with ``conan config install`` and everyone, including CI can be easily aligned on that.

**Comment by igagis** [comment]
Thanks for discussion! I will use `--build=missing` for now.

**Comment by memsharded** [comment]
Thanks for the feedback!
