### ISSUE TITLE
[question]  profile argument not working

### ISSUE THREAD

**Issue by SaverioCode** [conan-io/conan#16184]
### What is your question?

I'm using **conan 2.2.3**, And I'm trying to run the command:

`conan install ${CONAN_DIR} --profile:build=${CONAN_PROFILE} --output-folder=${BUILD_FOLDER} --build=missing`

I also tried:

`conan install ${CONAN_DIR} --profile=${CONAN_PROFILE} --output-folder=${BUILD_FOLDER} --build=missing`

and other variants. But I always got the same two errros:

```
ERROR: The default build profile '/home/dev/.conan2/profiles/default' doesn't exist.
You need to create a default profile (type 'conan profile detect' command)
or specify your own profile with '--profile:build=<myprofile>'
```
or
```
ERROR: The default build profile '/home/dev/.conan2/profiles/default' doesn't exist.
You need to create a default profile (type 'conan profile detect' command)
or specify your own profile with '--profile:host=<myprofile>'
```
Seems like is still trying to get the default profile even if I'm giving instruction to take a custom one. As the documentation says I tried with to use either the absolute and relative path to the custom profile, but I always get the same result.
The command without the **--profile** option is working properly, but even If I try to run only:
`conan install ${CONAN_DIR} --profile:build=${CONAN_PROFILE}`  
I'm not getting what I'm doing wrong  

Notes:  
CONAN_DIR is an absolute path to the conanfile.py folder

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi, thanks for the question :)

- What's the value of `CONAN_PROFILE`? We have not seen issues with profile loading specified as paths, so it's a bit confusing what could be happening here

**Comment by SaverioCode** [comment]
I tried with the absolute and relative path of the profile
Eg:
/folder1/folder2/customProfile
./customProfile

**Comment by AbrilRBS** [comment]
Thanks. I just rechecked your original comment and realized that the issue comes from only defining one of the profiles in both cases.
The first command you are setting the build profile, and the other one is setting the host one.
When you dont define one of the profiles, its value is `default` by default, which explains the behaviour you are seeing.

If you want to set both profiles at once to the same value, you can use the `-pr:a` (`--profile:all`) syntax so you dont need to specify both `--profile:build` and `--profile:host` 


Let me know if that helps!

**Comment by SaverioCode** [comment]
Yes, it's working! Thanks
