### ISSUE TITLE
Cache Gets wrong package[bug]

### ISSUE THREAD

**Issue by Codinablack** [conan-io/conan#16207]
### Describe the bug

The bug is evident when trying to use the same conanfile.py for the exact same project, but on two different windows computers.

What happens is on one computer it finds one package, on another computer it cannot, so it resolves to using an outdated version. Specifically it is settling on a version of the package meant for a different target language (c++14 instead of c++20). 

Like this:
`fmt/10.2.1: Main binary package 'cec3aa1676100e3891c40534e5ce782591987448' missing. Using compatible package '242c2889ffbb34b5cb5b8e66f6891e9db8cb71fe': compiler.cppstd=14`

### How to reproduce it

Take a project and give it these requires in a conanfile.py

`        self.requires("cryptopp/8.9.0")
        self.requires("fmt/10.2.1")
        self.requires("mariadb-connector-c/3.3.3")
        self.requires("pugixml/1.14")
        self.requires("boost/1.84.0")
        self.requires("luajit/2.1.0-beta3") 
        `
        
        Specifically the pugi, fmt, and cryptopp.
        
        Make sure to set the target language for c++20
       Try that on multiple windows pc's. Here is my results
       
       `======== Computing necessary packages ========
fmt/10.2.1: Checking 3 compatible configurations
fmt/10.2.1: Main binary package 'cec3aa1676100e3891c40534e5ce782591987448' missing. Using compatible package '242c2889ffbb34b5cb5b8e66f6891e9db8cb71fe': compiler.cppstd=14
pugixml/1.14: Checking 3 compatible configurations
pugixml/1.14: Main binary package '9e1c835afa3bbcd41c8804e968cb9aa8dccf91ef' missing. Using compatible package 'c72a7956a4dab5bcbaf9f6be0ceed1e2b390be3b': compiler.cppstd=14
cryptopp/8.9.0: Checking 3 compatible configurations
cryptopp/8.9.0: Main binary package '3e9241b8bca8d7d0cd1d864535a2c18a3b684955' missing. Using compatible package '50fe70044e3c72d6a4f241321a30e60d64994bea': compiler.cppstd=14`

on another pc it works just fine

`======== Computing necessary packages ========
fmt/10.2.1: Checking 3 compatible configurations
fmt/10.2.1: Compatible configurations not found in cache, checking servers
fmt/10.2.1: '242c2889ffbb34b5cb5b8e66f6891e9db8cb71fe': compiler.cppstd=14
fmt/10.2.1: 'f134d4c4e8c78a64bfdbe69deb29a8569e822900': compiler.cppstd=17
fmt/10.2.1: '0064fe4a074ed23d32fa0d03f4be7f475b75f96b': compiler.cppstd=23
pugixml/1.14: Checking 3 compatible configurations
pugixml/1.14: Compatible configurations not found in cache, checking servers
pugixml/1.14: 'c72a7956a4dab5bcbaf9f6be0ceed1e2b390be3b': compiler.cppstd=14
pugixml/1.14: 'b30f7204b06a35ebd7165fd6dd80dcfe038b1cf8': compiler.cppstd=17
pugixml/1.14: '9ace05640c7336448b8109cc6ef5528c9c3b0b4c': compiler.cppstd=23
boost/1.84.0: Checking 3 compatible configurations
boost/1.84.0: Compatible configurations not found in cache, checking servers
boost/1.84.0: '99f25f38d02541f2195075c5d3eb12006bcd5dfa': compiler.cppstd=14
boost/1.84.0: 'b8393b560ed1e34ff81cdb6d81d495e2bd4969ff': compiler.cppstd=17
boost/1.84.0: '0e7d37e1526ac2804229b0425d1cb6c3c3702692': compiler.cppstd=23
cryptopp/8.9.0: Checking 3 compatible configurations
cryptopp/8.9.0: Compatible configurations not found in cache, checking servers
cryptopp/8.9.0: '50fe70044e3c72d6a4f241321a30e60d64994bea': compiler.cppstd=14
cryptopp/8.9.0: '7b737f1649e252dd60b2aefeabe5b6ef5e1a4750': compiler.cppstd=17
cryptopp/8.9.0: '702c4dfe38a1871adb09bfccdb7130a39a1fced9': compiler.cppstd=23`

**Comment by memsharded** [comment]
Hi @Codinablack 

Thanks for your report.

I don't think this is a bug, but expected behavior.

The first important bit to take into account: please don't share the same cache among different machines. The Conan cache is not concurrent, so having 2 machines accessing the same cache can easily result in race conditions. The recommended flow is to upload the binary packages built with one machine to a package server, like the free ArtifactoryCE in our downloads page.

Then, what you are seeing seems to be the default behavior of the default ``compatibility.py`` plugin. Please check: https://docs.conan.io/2/reference/binary_model/custom_compatibility.html#the-compatibility-py-plugin, but in general the whole section is relevant: https://docs.conan.io/2/reference/binary_model

That is, packages built with different ``compiler.cppstd`` are assumed to be binary compatible. This is a good default that works well in the majority of cases. For other use cases you can:
- Change the default behavior of the ``compatibility.py`` plugin
- Disable in the package ``conanfile.py`` recipe the default compatibility with ``extension_properties = {"compatibility_cppstd": False}`` (read https://docs.conan.io/2/reference/extensions/binary_compatibility.html#reference-extensions-binary-compatibility)

Please let me know if this clarifies the behavior.

**Comment by Codinablack** [comment]
Thanks for the quick response, but I feel there is a bit of confusion here. I am not sharing binaries. I am only sharing sources and conanfile.py, along with a setup_build.py, and a premake5.lua (premake is the build app I use, instead of cmake). These are the only things shared between the two machines, and the setup_build.py just runs conan and premake for me.

I am not using any custom recipes, I am only using the conan center. I would expect when using the conanfile.py, on two windows machines, to get the same packages...

**Comment by memsharded** [comment]
Ok, I understood it wrong.

Can you please share the full output of the ``conan install`` command for those 2 different computers?
Also I understand you are using packages from ConanCenter?

Please make sure to completely wipe the Conan cache in both computers before trying the ``conan install``, to make sure you don't have anything different cached in those computers.

**Comment by Codinablack** [comment]
How can I completely wipe the conan cache? One computer is fine, everything works perfectly and as expected, the other however, not so much.

I am using the packages from conan center from the example for each of those packages, the conanfile.py example. Here to clarify what my file looks like..
[conanfile.txt](https://github.com/conan-io/conan/files/15221370/conanfile.txt)

I had to change it to a text file because python files are not allowed to be uploaded

**Comment by memsharded** [comment]
> How can I completely wipe the conan cache? One computer is fine, everything works perfectly and as expected, the other however, not so much.

The packages cache can be done with ``conan remove "*" -c``. Completely wiping everything is just removing the ``~/.conan2`` folder (or wherever the CONAN_HOME is pointing to)

Yeah, you can wipe the one that is not working and then repeat the ``conan install`` and share the full output.

**Comment by Codinablack** [comment]
[message(3).txt](https://github.com/conan-io/conan/files/15228978/message.3.txt)
Here is a text file containing the output from the machine I am having a problem with. It was a friend who was issueing the commands and such, it appears he may have used the same notepad to copy multiple outputs. Anyways, it seems that clearing the cache fixed the problem with the three libs it was issueing the wrong versions for, but for some reason, there is still a conflict with zlib for some reason, which is keeping my friend from being able to compile.

**Comment by memsharded** [comment]
What I see in that message is an error building boost, I don't see any conflict:

```
[ERROR:vcvars.bat] Toolset directory for version '14.3' was not found.
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
```
It could be that they don't have that toolset installed in their Visual Studio installation?

In any case, this would be a different thing. The original issue about the package seems to have been solved, and the issue was that your friend had some stale/old packages in their cache, updating it seems to solve the issue.

I'd recommend to close this ticket as solved, and open a new one specific for the new issue (not sure if it is boost not building or a conflict with zlib, but please provide the specific output and the new details to reproduce). Thanks!

**Comment by Codinablack** [comment]
Thanks man, you are right about the original issue being fixed! I will see if we can't work out the reason he is not able to build boost before opening a new ticket.
