### ISSUE TITLE
[question] autotools with CFLAGS/LDFLAGS

### ISSUE THREAD

**Issue by nikoladsp** [conan-io/conan#16202]
### What is your question?

Hi,
I have to use a library (_GraphicsMagick_) that does not have CMake/Conan recipe. It depends on couple of other libraries that **_do_** have Conan recipe: _libpng_ and _libwebp_ (to name just a few).

I would like to make a Conan package so I can use it as other libraries - something like:

```
class ConanGraphicsMagick(ConanFile):
    name = "graphicsmagick"
    version = "1.3.42"
    package_type = "library"

    # Optional metadata
    license = "MIT"
    author = "Nikola Radovanovic <nikoladsp@gmail.com>"
    homepage = "http://www.graphicsmagick.org/"
    description = "GraphicsMagick is the swiss army knife of image processing"
    topics = ("image", "processing", "portable")

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": True, "fPIC": False}

    implicit_deps = {
        "libwebp/1.4.0": {"shared": True},
        "libpng/1.6.43": {"shared": True},
    }

    def source(self):
        zip_name = f"GraphicsMagick-{self.version}.tar.xz"
        download(self, f"https://deac-fra.dl.sourceforge.net/project/{self.name}/{self.name}/{self.version}/{zip_name}?viasf=1", zip_name)
        # check_sha1(self, zip_name, "a48ec3fa59d9ca0915e1e6f78fd8bda55e9e0c6f")
        unzip(self, zip_name, strip_root=True)
        os.unlink(zip_name)

    def requirements(self):
        for dep, opts in self.implicit_deps.items():
            self.requires(dep, options=opts)

    def build(self):
        print("BUILD")

        # export CFLAGS and LFLAGS
        #self.run("./configure --enable-shared --disable-static --with-magick-plus-plus --with-webp --with-png --with-jpg --without-xml --without-x --without-perl --without-gs")
        #self.run("make V=1")

    def package(self):
        print("PACKAGE")

```

But I need to find out libpng and libwebp include and library directories in Conan cache prior running **_./configure_**. Those have to match "shared" version (since "static" version of these libraries maybe exists in cache). Also, how to set output folder path/name?

Many thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nikoladsp 

Thanks for your question.

The responsibility of extracting the information from dependencies and generating the necessary files for the build systems to locate the dependencies is the one of ``generators()`` and the ``generate()`` method. You can experiment a bit with:

```python
def generate(self):
     deps = CMakeDeps(self)  # or deps = MSBuildDeps(self), or deps = PkgConfigDeps(self)...
     deps.generate()
```
And see how it works.
Then you need to do your own mapping from dependencies to your specific build system, you can access the dependencies via:
```python
def generate(self):
     for require, dep in self.dependencies.host.items():
          dep.package_folder
          dep.cpp_info.includedirs
          dep.cpp_info.libdirs
          ...
```

Check https://docs.conan.io/2/reference/conanfile/methods/generate.html#conan-conanfile-model-dependencies for more information about dependencies and ``cpp_info`` in https://docs.conan.io/2/reference/conanfile/methods/generate.html#dependencies-cpp-info-interface

Don't worry about the ``shared`` one, the ``self.dependencies`` will contain the information of the specific packages that have been resolved, if you specified ``shared``, it will be pointing to the shared binaries of the dependencies.

Then, when you know how to generate the files that you want, if you want to reuse it, the recommendation would be to put the code in a common ``python_requires`` and reuse it from there in all recipes that you want.


About the ``"libwebp/1.4.0": {"shared": True},`` definition of "shared=True" inside the recipes, please not that in general, it is more robust and easier to specify those things in ``profile`` files instead. The reason is that there might be other recipes competing for having ``shared=False``, and the first one to specify it wins, so the only guarantee to have them as shared is to specify that in the profile files.


Please let me know if this helps.

**Comment by nikoladsp** [comment]
Many thanks for your answer - I will try it later today or tomorrow morning. 

Just to check my understanding: I need to get package location (where include and lib are stored) so I can prepend CFLAGS and LDFLAGS when doing **_./configure_** - so autotools can find it? Also, what I have to set `--prefix` to?

Kindest regards

**Comment by memsharded** [comment]
> Just to check my understanding: I need to get package location (where include and lib are stored) so I can prepend CFLAGS and LDFLAGS when doing ./configure - so autotools can find it? Also, what I have to set --prefix to?

Well, we already have the ``AutotoolsDeps`` generator, which is very close what you are trying to do, if I understand correctly. It is true that it doesn't work for Windows yet, but it does in Linux. Please check https://docs.conan.io/2/reference/tools/gnu/autotoolsdeps.html and try it, to see how it works.

You have the implementation here if you want to start from there: https://github.com/conan-io/conan/blob/develop2/conan/tools/gnu/autotoolsdeps.py


> Also, what I have to set --prefix to?

The ``--prefix`` is for the current installation of the current package, isn't it? Note that you can also use bare ``copy()`` inside the ``package()`` method, very often it is easier than implementing installation steps, depending on the project.

In the case of the ``Autotools`` helper, it is using ``DESTDIR`` for this purpose: https://github.com/conan-io/conan/blob/66ef385b6bc8ee3b85d31c81e676d2c3fdc0dedf/conan/tools/gnu/autotools.py#L84

**Comment by nikoladsp** [comment]
I did play a bit with suggested readings and realized that maybe I should of ask: "Is it possible to build package with autotools but in such way it can be consumed by CMake"? Majority of packages I am using are available via Conan recipes - but there will be couple of exceptions to this rule. Shall I make custom **_generate()_** method based on say **_PkgConfigDeps_** or completely custom generator that will help other team members to consume packages from their CMake projects?

**Comment by memsharded** [comment]
> I did play a bit with suggested readings and realized that maybe I should of ask: "Is it possible to build package with autotools but in such way it can be consumed by CMake"?

Absolutely. Conan packages are intended to be created with any build system and be consumed with any other build system. All packages in ConanCenter use different build systems, and there are already tons of packages using CMake consuming packages built with autotools, meson, etc.

> Shall I make custom generate() method based on say PkgConfigDeps or completely custom generator that will help other team members to consume packages from their CMake projects?

The key here is the ``package_info()`` and the ``cpp_info`` abstractions. As long as it is filled correctly, the generators on the consumers side will be able to map that information to their respective build systems. ``PkgConfigDeps`` generates ``.pc`` files from the information in ``package_info()`` of its depenencies, and ``CMakeDeps`` generates ``.cmake`` files from exactly the same information of the dependencies.

If using CMake, they might be able to use the built-in ``CMakeToolchain`` and ``CMakeDeps``, as recommended in the documentation, they can achieve transparent integration (no need to modify their ``CMakeListst.xt`` to add Conan-specific things, just using standard CMake)

**Comment by nikoladsp** [comment]
Sorry, I forgot on this one. I ended up with following:

```
import os

from conan import ConanFile
from conan.tools.files import check_sha1, download, unzip
from conan.tools.gnu import Autotools, AutotoolsToolchain
from conan.tools.microsoft import unix_path


class GraphicsMagick(ConanFile):
    name = "graphicsmagick"
    version = "1.3.43"
    version_hash = "21ecdbffb15239458aa288321d726f41b795cec9"
    package_type = "library"

    settings = "os", "arch", "compiler", "build_type"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
    }
    default_options = {
        "shared": True,
        "fPIC": True,
    }

    # Optional metadata
    license = "MIT"
    author = "Nikola Radovanovic <nikoladsp@gmail.com>"
    homepage = "http://www.graphicsmagick.org/"
    description = "GraphicsMagick is the swiss army knife of image processing"
    topics = ("image", "processing", "portable")

    def _flags(self):
        incdirs = []
        libdirs = []
        for dep in self.dependencies.host.values():
            incdirs.extend(dep.cpp_info.includedirs)
            libdirs.extend(dep.cpp_info.libdirs)

        cflags = ' '.join(map('-I{0}'.format, incdirs))
        ldflags = ' '.join(map('-L{0}'.format, libdirs))

        return cflags, ldflags
        
    def requirements(self):
        deps = [
            'libwebp/1.4.0',
            'libpng/1.6.43',
            'libjpeg/9e'
        ]
        for dep in deps:
            self.requires(dep)

    def source(self):
        zip_name = f"GraphicsMagick-{self.version}.tar.xz"
        download(self, f"https://deac-fra.dl.sourceforge.net/project/{self.name}/{self.name}/{self.version}/{zip_name}?viasf=1", zip_name)
        check_sha1(self, zip_name, self.version_hash)
        unzip(self, zip_name, strip_root=True)
        os.unlink(zip_name)

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            del self.options.fPIC

    def generate(self):
        tc = AutotoolsToolchain(self)
        env = tc.environment()

        cflags, ldflags = self._flags()
        env.define("CFLAGS", cflags)
        env.define("CXXFLAGS", cflags)
        env.define("LDFLAGS", ldflags)

        tc.generate(env)

    def build(self):
        autotools = Autotools(self)
        autotools.configure()
        autotools.make()

    def package(self):
        autotools = Autotools(self)
        autotools.install(args=[f"DESTDIR={unix_path(self, self.package_folder)}"])

    def package_info(self):
        self.cpp_info.libs = ["GraphicsMagick", "GraphicsMagick++"]
        self.cpp_info.includedirs = ["include/GraphicsMagick"]
```

I am  not sure do I need these 2 lines at all (I kept them commented out)
```
cmake = CMakeDeps(self)
cmake.generate()
```

I used profiles as suggested, say `profiles/gcc`
```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.version=13
compiler.libcxx=libstdc++11
compiler.cppstd=17
os=Linux
[options]
*:shared=True
```

If this is ok, maybe can be a reference to others... in which case I will close this issue?

Thank you kindly

**Comment by memsharded** [comment]
If you are not using ``CMake`` in your recipe, no, you shouldn't be using ``CMakeDeps`` in your recipe. Not in the ``generate()`` method, but also using it in the ``_flags()`` method is not recommended.

There are other integrations like ``AutotoolsDeps`` or ``PkgConfigDeps`` that are more native to autotools than that, and you can use it instead of having to define your raw flags.


Other hints and recommendations:

- In Conan 2 it is not necessary to instantiante and call ``env = VirtualBuildEnv(self)``, it is done automatically
- If you have conflicts in requires, consider using version-ranges. Specially if contributing back to ConanCenter at some point, using a version range similar to the existing ones in ConanCenter will be needed
- ``self.env_info.path.append(os.path.join(self.package_folder, "bin"))`` this is legacy Conan 1.x syntax that shouldn't be used anymore, but instead using ``self.buildenv_info`` or ``self.runenv_info``. Also, in general it is not necessary to add the ``bin`` folder to the environment, Conan ``VirtualXXXEnv`` do it automatically when necessary.
- ``self.cpp_info.includedirs = ["include/GraphicsMagick"]`` In most cases ``self.cpp_info.includedirs = ["include"]`` is recommended, and forcing users to do a ``#incldue "GrpahicsMagick/image.h`` or the like. That solves any possible conflicts of names with other libraries that might provide a header named the same as ``image.h``

**Comment by nikoladsp** [comment]
I have updated the "sample" above. Had to keep/add:
```
self.cpp_info.system_libs =["webp", "png", "jpeg"]
self.cpp_info.includedirs = ["include/GraphicsMagick"]
```
I had issues when using "just" `self.cpp_info.includedirs = ["include"]` since the way library includes other files. Not sure can this be done differently bbut this works.
As for `self.cpp_info.system_libs =["webp", "png", "jpeg"]` it is just to make sure libraries from dependencies were linked instead of systems.

I don't have enough words to express my gratitude for your help/insights. Personally, I am more of a book/video guy and reading/connecting pieces of extensive docs was overwhelming - but you provided more help I could possibly imagine. Hopefully, I would be able to repay in some way, maybe through some contributions.

**Comment by memsharded** [comment]
> self.cpp_info.system_libs =["webp", "png", "jpeg"]


This is incorrect. If you are transitively depending on those packages, they are not system-libraries, they are regular transitive libraries. So you might be creating potential link or runtime issues.

What you want to do is to make sure you have the correct modeling and usage of dependencies. If your package is a ``shared`` library, because you defaulted ``shared=True``, but then the dependencies are static libraries they will be embedded inside the shared library and remain as in internal implementation detail. It is possible that you might want to do some of these:

- Make sure the dependencies are also shared libraries by defining ``*:shared=True`` option in your profiles. This is relatively common, to use dependencies all as shared libraries or all as static libraries, but mixing them is usually more complicated and advanced use case that should be treated more carefully.
- Change your library to be a static library by default.
- Check why the consumer is needing to link with those libraries. If it is depending on them directly then the consumer should also have its own ``requires`` to those libraries, not inherit them via your package linkage.
- In the exceptional cases where the linkage needs to be propagated down, use the ``self.requires("...", transitive_libs=True)`` trait in the requirements definition. This ends with 2 copies of the static libraries of the transitive dependencies, one inside the shared library and another inside the downstream executables, which can be not optimal.


> I don't have enough words to express my gratitude for your help/insights. Personally, I am more of a book/video guy and reading/connecting pieces of extensive docs was overwhelming - but you provided more help I could possibly imagine. Hopefully, I would be able to repay in some way, maybe through some contributions.

Thanks very much for your kind words 🙂 Always happy to help!

We had a video course in the past, but it became obsolete with Conan 2. We will try to do a new one for Conan 2 in the future, but it will take some time. Don't hesitate to ask the questions you need in the meantime.

**Comment by nikoladsp** [comment]
I will close the issue/question now!
