### ISSUE TITLE
[question] Compatibility Issues

### ISSUE THREAD

**Issue by peddaahh** [conan-io/conan#16219]
### What is your question?

I am not able to correctly use the compatibility() method: Therefore I may ask for help again.. So it's still a conan file to wrap LabVIEW PPLs (something like DLLs) into a conan package. The LabVIEW version (e.g. 2020) and the arch (e.g. win64) is set via options. So the compiled PPLs are useable in future version so e.g. compiled in 2020 will be working for 2024 but NOT vice versa. But when executing, this does not work. I'll add a simplified conanfile and the bash output below:
Console:
```sh
conan graph explain --requires=lvPPL/5.0.0-6-g835604e -o lv="2021" -o arch="win32"

======== Computing dependency graph ========
Graph root
    cli
Requirements
    lvPPL/5.0.0-6-g835604e#5995e92bc7f4dfb56681aaa3d5e4a062 - Cache

======== Computing necessary packages ========
lvPPL/5.0.0-6-g835604e: Compatible package ID 31aea52075a222389d5dda7d4da0f4fb0ddea4b0 equal to the default package ID: Skipping it.
lvPPL/5.0.0-6-g835604e: Checking 4 compatible configurations
lvPPL/5.0.0-6-g835604e: Compatible configurations not found in cache, checking servers
lvPPL/5.0.0-6-g835604e: '728416796586b58a395d75832f664d6bbba6b254': lv=2022
lvPPL/5.0.0-6-g835604e: 'eeb316e14769b512514c95d3ab17184446e903d7': lv=2023
lvPPL/5.0.0-6-g835604e: '2a8e1b806f6928b7c919edf1cc8499a8fe3c3f0c': lv=2024
lvPPL/5.0.0-6-g835604e: '3d83f9f77dfa5f245eed384bd0298233f631e9a0': lv=2025
Requirements
    lvPPL/5.0.0-6-g835604e#5995e92bc7f4dfb56681aaa3d5e4a062:31aea52075a222389d5dda7d4da0f4fb0ddea4b0 - Missing

======== Retrieving and computing closest binaries ========
Missing binary: lvPPL/5.0.0-6-g835604e
With conaninfo.txt (package_id):
[options]
arch=win32
lv=2021

Finding binaries in the cache
Finding binaries in remote conancenter
Finding binaries in remote conan-other-local

======== Closest binaries ========
lvPPL/5.0.0-6-g835604e
  lvPPL/5.0.0-6-g835604e#5995e92bc7f4dfb56681aaa3d5e4a062%1715151932.076 (2024-05-08 07:05:32 UTC)
    lvPPL/5.0.0-6-g835604e#5995e92bc7f4dfb56681aaa3d5e4a062:acaf1d858589ec287000b848ce8863b8339498b5
      remote: conan-other-local
      options: arch=win32, lv=2020
      diff
        options
          expected: lv=2021
          existing: lv=2020
        explanation: This binary was built with the same settings, but different options
```

conanfile.py
```py
import datetime
import os
import subprocess
import glob

import xml.dom.minidom
from conan import ConanFile
from conan.tools.env import VirtualBuildEnv, VirtualRunEnv
from conan.tools.files import copy
from conan.tools.files.symlinks import absolute_to_relative_symlinks


class LabVIEWBuild(ConanFile):
    exports_sources = "*"

    # Metadata
    license = "foo bar"  # Default, will be read out from lvproj below
    author = "foo bar"
    description = "<Description of hello package here>"

    # Binary config #

    # Range does not include last year in range so + one year
    # We want to be future-proof (e.g. pre-releases) so + another year
    _current_year = datetime.date.today().year + 2
    _years = []
    for v in range(2018, _current_year):
        _years.append(str(v))

    options = {
        "lv": _years,
        "arch": ['win32', 'win64', 'som32', 'som64']
    }

    def set_name(self):
        repo = subprocess.getoutput('git config --get remote.origin.url')
        self.name = 'kai_' + subprocess.getoutput('basename -s .git ' + repo)

    def set_version(self):
        self.version = subprocess.getoutput('git describe --tags --always')

    def configure(self):
        folder = os.path.join('..', 'es') if os.path.exists(os.path.join('..', 'es')) else '.'
        lvf = [filename for filename in os.listdir(folder) if filename.startswith("_LV")][0]  # e.g. _LV2020-win64
        lvf = lvf[3:].split('-')
        if len(lvf) == 2:
            arch = lvf[1]
        else:
            arch = "win32"

        self.options.lv = lvf[0]
        self.options.arch = arch

    def requirements(self):
        pass

    def generate(self):
        VirtualBuildEnv(self, auto_generate=False)
        VirtualRunEnv(self, auto_generate=False)

    def layout(self):
        _build_type = self.options.lv
        _arch = self.options.arch
        self.folders.package = os.path.join(str(_build_type), str(_arch))

    def compatibility(self):
        _future_years = []
        for v in range(int(self.options.lv), self._current_year):
            _future_years.append(str(v))
        return [{"options": [("lv", v)]}
                for v in _future_years]


    def build(self):
        lvproj = glob.glob(os.path.join(self.source_folder, "*.lvproj"))
        xml_doc = xml.dom.minidom.parse(lvproj[0])
        lic = xml_doc.getElementsByTagName('Property')
        for element in lic:
            if element.getAttribute('Name') == "TgtF_legalCopyright":
                lic = element.childNodes[0].data
        self.license = lic if lic is not None else self.license

        # self.run('sh ' + os.path.join(self.source_folder, 'lv_builder', 'run-build.sh'))
        # self.run('mv ./build/*', '${./build/*%%:*}')

    def package(self):
        copy(self, "*.lvlibp", src=os.path.join(self.source_folder, 'build'), dst=self.package_folder)
        absolute_to_relative_symlinks(self, self.package_folder)

    def deploy(self):
        copy(self, "*.lvlibp", src=self.package_folder, dst='lib')
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Peddaahh 

Thanks for your question.

> The LabVIEW version (e.g. 2020) and the arch (e.g. win64) is set via options.

Why? Why not using ``settings`` instead? It would be recommended to use settings, if those need to match for all dependencies.

> self.options.lv = lvf[0]
        self.options.arch = arch

There is a misconception in this. The ``options`` cannot be defined from file contents. ``options`` and ``settings`` are "inputs". It is something that the user define the value, in an "imperative" way, for example in the ``profile`` and the package will follow. Trying to read the value from a file is against this and will most likely cause issues. As an example, a recipe cannot decide that it is ``options.shared=True`` based on some file contents, it is the opposite, when I say ``-o mypkg*:shared=True`` the final package must be a shared library, no matter what the files say.

> -o lv="2021" -o arch="win32"

Please recall that for the general case it is necessary to use the package name or a pattern, like ``-o *:lv="2021" -o *:arch="win32"``. This would be easier if using settings instead of options.

Regarding the ``compatibility()`` thing I think it goes like this:

- You are passing ``lv=2021`` as input
- The compatibility ``for v in range(int(self.options.lv), self._current_year):`` defines from that year to the future that is 2021, 2022, ... 2024
- The existing binary is ``lv=2020``, as said in the output: ``existing: lv=2020``
- So the existing binary ``existing: lv=2020`` is clearly not in the range of compatible binaries that you defined [2021-2024]

So the range is incorrect, it needs to go backwards. If someone asks for ``2021``, you want the valid range [2021, 2020], not the other one+2021-2024]. So an inverse range from the current ``option.lv`` to the oldest possible one, in that inverse order, like if lv=2023, you want [2022, 2021, 2020] in this order, to prioritize more modern packages. The range defines the "fallback" order of compatibility: "if I dont have a 2023 binary, then I will try 2022, 2021, 2020 in this order"

Please try that and let us know.

**Comment by peddaahh** [comment]
Thank you! Just for clarification before I'll try out the rest:
I did it this way, because that's how I managed dependencies in the past. There was a shell script which looked the version and arch up using this file. Then I saw I could use settings, however I did see that I can only put in predefined values for predefined settings. Then I came across the options an thought it could work that way. So I implemented it according to this: https://docs.conan.io/2/reference/conanfile/attributes.html#default-options

**Comment by memsharded** [comment]
> I did it this way, because that's how I managed dependencies in the past. There was a shell script which looked the version and arch up using this file. Then I saw I could use settings, however I did see that I can only put in predefined values for predefined settings. Then I came across the options an thought it could work that way. So I implemented it according to this:

Settings are extensible too. You can add the settings and values that you want to your ``settings.yml``, and you can share it via ``conan config install/install-pkg`` together with the rest of your configuration (remotes, profiles, etc). Conan 2 even has a ``settings_user.yml`` that allows easier extension and maintenance.

Check https://docs.conan.io/en/1.64/extending/custom_settings.html for more info. 

Read this discussion to help deciding which is the best: https://docs.conan.io/2/reference/binary_model/extending.html#settings-vs-options-vs-conf

**Comment by peddaahh** [comment]
Okay thanks for the help
I did adapt it to your suggestions, and also works now

**Comment by memsharded** [comment]
Great, thanks for the feedback!
