### ISSUE TITLE
[question] How to use editable library with cmake's conan provider file 

### ISSUE THREAD

**Issue by Sickeroni** [conan-io/conan#16216]
### What is your question?

# brief
I have a cmake projects and use the provider file
The lib i'm developing and consuming is in editable mode.
The provider file was modified and has `--build=editable`, to build all editable libs 

# The problem
So far this works. 
BUT that is only when i'm configuring the project

callgraph is 
cmake configure -> conan install -> end 
cmake build -> end

If the cmakefile is changed, it will again reconfigure. 

If i'm just editing the .hpp or .cpp files of the lib, no cmake configure gets triggered. 
As a consequence we also never build the lib again and are using an outdated version.

# documentation way
Documentation is more clear and uses
```shell
# line edited because it was wrongly cmake, not conan
conan build --build=editable 
```
This is sadly not an option for us. 

Also always typing in `conan install . --build=editable` would be suboptimal.
# Question 
What is the best practice, except using the alternative shown above? 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Sickeroni 

Having a project in ``editable`` mode doesn't mean that it becomes part of the consumer project. It is still an external dependency, and the consumer project cannot track source code changes there. Note that it is also totally possible that the dependency is even with a different build system than the consumer one, it could be a Meson project or Autotools, while the consumer is a CMake one (with the provider).

So any changes in the ``editable`` dependency still need to be built from source, and the only way to achieve this is:
- In the project itself, fire a build with ``conan build .``, or ``cmake --build ...`` or ``meson ...`` or ``make``, or whatever builds the project.
- From the consumer side, fire the build with ``--build=editable``.

The problem is that there is no magic here, the editable and the consumer are still different projects. There is no physical way to make the consumer project aware of the source changes of the dependency project and automatically fire a rebuild of the dependency, unless ``conan install --build=editable`` is called. But the build systems don't have such a mechanism, once something is a dependency, it doesn't control its build.

**Comment by Sickeroni** [comment]
Thanks, 
I assumed that already, but hoped for a different answer nad that i missed something.
Still fast and good answer and therefore big thanks (again)!
(closed therefore)
