### ISSUE TITLE
Files are not removed in export_source folder 

### ISSUE THREAD

**Issue by ringgelerch** [conan-io/conan#1623]
I manage the conan recipe along with the source code in one repository. That's why I'm using the exports_sources feature to export my sources with the recipe.

If I run conan create the sources are exported as expected.  Fine so far. When I delete a file in my source folder after the export was executed once it won't be deleted in the locale cache after the second export.

Result are some zombi files in locale chache, which should be deleted IMHO.

**Comment by memsharded** [comment]
You are right. That is a bug in the current release. It has already been fixed in this PR: https://github.com/conan-io/conan/pull/1596/files

That PR/issue was related to permissions, but was a symptom of the same problem. Now the exports_source folder will be completely removed at every export.

Will be released in 0.26. Thanks very much for reporting!

**Comment by memsharded** [comment]
Released in 0.26
