### ISSUE TITLE
[feature] batch export for performance?

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#16257]
### What is your suggestion?

Currently I have a large number of recipes that I periodically need to export. This could possibly be addressed in parallel if the cache was concurrent, but I wondered if this could be more narrowly addressed by updating the export command to allow multiple exports at once.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rconde01 

Thanks for your suggestion.

This is one of the use cases that we use as an example of a custom command: https://docs.conan.io/2/reference/extensions/custom_commands.html#reference-commands-custom-commands

We even have a "export-all-versions" custom command in https://github.com/conan-io/conan-extensions/blob/main/extensions/commands/cci/cmd_export_all_versions.py for usage with ConanCenter.

The reason this is a good candidate for a custom command is that the implementation is fairly simple (`` ref = conan_api.export.export(os.path.abspath(conanfile), recipe_name, version, None, None)``, the above ConanCenter command has lots of logic to deal with the specifics of ConanCenter files), but there are as many different cases as users, because users might have different layouts, different rules for defining versions to export, etc.

I don't think parallelism is that critical here, once using the API, exporting multiple recipes is pretty fast.

**Comment by rconde01** [comment]
The docs could be better, but worked really well and indeed is significantly faster. I attached my script.
[cmd_batch_export.zip](https://github.com/conan-io/conan/files/15323980/cmd_batch_export.zip)

**Comment by memsharded** [comment]
Thanks for sharing your command.

> lockfile = conan_api.lockfile.update_lockfile_export

Please note that this might not work for all situations. A lockfile needs to be "realizable" or a snapshot of a real dependency graph. For example if you are exporting ``pkga/1.0#rev1`` that has a ``requires("pkgb/2.0")`` and are also exporting ``pkgb/1.0#rev2``, the lockfile will not be consistent. It might still resolve with ``--lockfile-partial`` but there is no guarantee that it will force the exported recipes to depend on each other.
