### ISSUE TITLE
[feature] `tools.system.package_manager:sudo=True` skip if sudo not installed

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#16264]
### What is your suggestion?

I ran into the case where I set `sudo` to be true, but for msys sudo is not installed so it leads to an error. Maybe it's reasonable to skip it in this case...

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by rconde01** [comment]
I worked around it by just creating a passthough script `/usr/bin/sudo` with just `"$@"`

**Comment by memsharded** [comment]
Thanks for the suggestion @rconde01 

We'd prefer not to do this, in our experience this ends being problematic. In general in Conan we try to detect as little as possible and rely on explicit definitions. If the conf ``....:sudo=True`` is defined, it must add ``sudo``. Because if Conan tries to be smart, detect if sudo is there it will eventually find some cases that it fails to detect sudo, omit it, and it will result not only in a failure, but most importantly, in a blocker. Users will not be able to move forward until that specific detection bug is fixed in one of the following releases.

So we think that it is the responsibility of the profile to decide/know if there is sudo or not in that platform and if it should be used to install system packages.

**Comment by rconde01** [comment]
Totally fair...
