### ISSUE TITLE
[question] Static linking, transitive dependences, and licenses

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#16353]
### What is your question?

I am updating a project from conan v1 to v2. I am using the conan center GDAL recipe, but the v1 build is locked to an older recipe revision. I noticed that when GDAL is set to statically link, the v1 version builds GDAL dynamically linking to geos while the v2 is statically linking to geos. This is notable because while GDAL is MIT, geos is LGPL. I tried to compare the recipes to determine when the change was introduced - but I couldn't see anything relevant - the recipe is a bit of a beast. I was able to successfully revert the behavior by adding an option to my profile but this brings me to my questions:

- Was this change intentional or "accidental"? If it was intentional, what was the motivation?
- Is there any policy here on how a library license should influence default linking behaviors? I feel like I've seen such things in other cases.
- For libraries which have transitive dependencies with potentially restrictive licenses, what is the general approach on surfacing that information to users of that library?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @rconde01 

> Was this change intentional or "accidental"? If it was intentional, what was the motivation?

This was intentional, the builds in ConanCenter in Conan 1 were a bit incorrect, for example when doing shared builds, the transitive dependencies were static libraries, then it is possible to have multiple copies of the same static libraries copied inside different shared libraries. 

So we changed to 2 different modes: all dependencies static or all dependencies shared (as much as possible, there are some libraries that don't allow that)

> Is there any policy here on how a library license should influence default linking behaviors? I feel like I've seen such things in other cases.

No, licenses don't play a role in ConanCenter CI regarding what binaries are built. Only the ``shared`` option is taken into account

> For libraries which have transitive dependencies with potentially restrictive licenses, what is the general approach on surfacing that information to users of that library?

The information of dependencies including transitive dependencies is always there in the graph, the graph of recipes is always complete, irrespective of the package types, so it is possible to do a quick check on the dependencies licenses, for example in the resulting ``--format=json`` graph output of the end consumer.

**Comment by memsharded** [comment]
Any further question or feedback here @rconde01 ? May we close the issue? Thanks.
