### ISSUE TITLE
[question] Local cache vs. Artifactory

### ISSUE THREAD

**Issue by dwswingle** [conan-io/conan#16367]
### What is your question?

I have a use case where each user having their own local cache is challenging due to disk space. What is the best approach for pulling packages directly from Artifactory vs. local storage? CMake is the de facto build system if that's of any help. Thanks

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
> I have a use case where each user having their own local cache is challenging due to disk space. 

Having a copy of the dependencies local in disk is necessary to link with them. The "ground truth" storage is the server side such as Artifactory, and the client side, the cache is just a temporary storage that can be cleaned at any time and it will be re-populated from the server automatically. But dependencies must be in the disk (in the local cache) to be used in C/C++ builds, there is no way that dependencies can be used otherwise. So every machine, developer or CI machine must have a populated cache with the dependencies they need to build.
Disk space is very rarely an issue, unless you let the Conan caches to grow forever without cleaning them from time to time.

There are some very simple strategies that you can do:

- Just clean the cache at every job or periodically.
- Put the cache in a temporary storage location that is wiped everyday, for example when the computer is shutdown
- Use the Conan 2 ``--lru`` (least recently used) feature to remove packages that haven't been used in a while to be even more efficient.

**Comment by memsharded** [comment]
Closing the question as responded, but don't hesitate to re-open or create new tickets for any further question, thanks!
