### ISSUE TITLE
[question] Creating lockfile with conan 2 API

### ISSUE THREAD

**Issue by lstoffer** [conan-io/conan#16372]
### What is your question?

Hi! I have a question regarding the creation of lockfiles with the new conan 2 API.
In conan 1 I used the lock_create(...) function in order to create a lockfile based on a given conanfile and a list of changed packages that should be considered for this lockfile. Is there a similar functionality in the conan 2 API?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lstoffer 

In Conan 2, the PythonAPI has the ``CommandAPI`` that allows basically to call any Conan command: https://docs.conan.io/2/reference/extensions/python_api/CommandAPI.html

the problem is that is not yet documented, but it would be something like 
```python
    api = ConanAPI()
    cli = Cli(api)
    cli.add_commands()
    result = api.command.run(["remote", "list"])
    assert result[0].name == "conancenter"
```

If you want to use the lower-level real PythonAPI, the you can have a look to the implementation of the ``conan lock create`` command in https://github.com/conan-io/conan/blob/5abec94cfc014c94c02e8ed51f21b7d779245072/conan/cli/commands/lock.py#L21. As you can see, it is not that huge, around 30 lines, and removing some of the extra validation, arguments, and options, it can be probably condensed to 15-20 lines.

**Comment by lstoffer** [comment]
Thank you very much, using the command API worked.
