### ISSUE TITLE
[bug] Version range: missing prebuild package 

### ISSUE THREAD

**Issue by RobinMaub** [conan-io/conan#16375]
### Describe the bug

OS: Linux Ubuntu 22.04
Conan: tested on 1.63.0 and 1.64.1
Package repositories: tested on Gitea (1.21.11 & 1.22.0) and Artifactory (Cloud)

revisions_range is enabled (same behavior if disabled)

I want to use version range to avoid to modify all the dependencies when moving a low level on.
I have 3 libraries/packages, A, B, C, A being the lower level.
C depends on B, B depends on A.

C conanfile.py contains `self.requires("B/[~0]@conan/stable")`, B conanfile.py contains `self.requires("A/[~0]@conan/stable")`

### How to reproduce it

First, create all the packages:
* publish A in version 0.0.3
* publish B in version 0.0.12
* publish C in version 0.0.21

The issue appears when you create a new version of the package A
* publish A in version 0.0.4

Then try to install with to build C with `conan install ..` in the C build directory (in C repo)
It computes correctly the dependency tree:
```
Version range '~0' required by 'conanfile.py (X)' resolved to 'B/0.0.12@conan/stable' in local cache
Version range '~0' required by 'conanfile.py (XX)' resolved to 'A/0.0.4@conan/stable' in local cache
```
But at install step, it complains about a missing binary, missing prebuilt package:
```
ERROR: Missing binary: B/0.0.12@conan/stable:myPackageId
```
then
```
B/0.0.12@conan/stable: WARN: Can't find a 'B/0.0.12@conan/stable' package for the specified settings, options and dependencies:
- Settings: XXX
- Options: XXX
- Dependencies: A/0.0.4@conan/stable
- Requirements: A/0.0.4
- Package ID: myPackageId
```
It is true, there is no package with this packageId in the remote but version range is valid,

What am I missing to get these version range working ?

Thanks in advance

**Comment by memsharded** [comment]
Hi @RobinMaub 

Thanks for your question.

This doesn't seem a bug so far, but expected behavior. There are two different aspects here:

- The first stage that conan does is to compute the dependency graph, resolve version ranges, propagate information, evaluate conditional dependencies, etc, until the dependency graph of recipes with version + revision for every package in the graph is done.
- The second step is to evaluate if there are existing binaries for these package versions, or if some need to be built from source. Due to the compilation model of C and C++ when dependencies get new versions, sometimes it is necessary to re-build from source the consumers of those dependencies. This is expected.

In your case, it seems it could be because of some reasons, for example the ``0.X.Y`` versions, under the semver specification are considered non-stable, and in Conan 1, new versions of dependencies will require re-building the consumers.
If you move to ``1.0`` instead of ``0.0`` you might see different behavior.

Conan 2 has changed that and dropped it, using exactly the same behavior for both ''0.X.Y'' and "1.X.Y" versions.

If you want to read more about the effect of dependencies you can read https://docs.conan.io/2/reference/binary_model/dependencies.html (it is for Conan 2, that has a much better model of binary compatibility regarding dependencies versions, but still it might be a good general explanation of how things work).

**Comment by RobinMaub** [comment]
Using >=1 versions solved the thing, thanks to that link too https://docs.conan.io/1/creating_packages/define_abi_compatibility.html#versioning-schema
