### ISSUE TITLE
Complex library hierarchy

### ISSUE THREAD

**Issue by Dimitrius-dev** [conan-io/conan#16387]
It's might be a weird question, but i'll give it a try. Conan provides a `cmake` component system for complex libraries. Currently using github or gitlab it looks like this:

![d1](https://github.com/conan-io/examples2/assets/56197018/095187a4-8460-4ab4-b445-f506f39287a5)
___
One git repo contains entire lib with all of components. Every component has unique cmake `target`. The `conanfile.py` declares them as cmake components of the `lib`.
After a long time lib increases and every lib component increases too. This is due to the fact that each component adds it's functionality. Therefore, the main repo should be split into multiply repos. And the schema:
![d2](https://github.com/conan-io/examples2/assets/56197018/58597790-bf8c-48ea-bf85-a909e961f383)

___
So everything is fine, i can use `cmake` `FetchContent` or other tool in `def source(self)` method in `lib` to get `lib component`. What if components depend on external lib (boost, spdlog....). I suppose it can use conan too). I mean it kind of this:
![d3](https://github.com/conan-io/examples2/assets/56197018/80b91a06-9324-4d20-aeb4-c780205cde52)
To the main question. In this case the top library does not have any code, it only links other libs and declares them like components.
___
Does it make sense?
Does it possible to compose a `conanfile.py` in the top lib to include some other libs (comp1,..) and set these libs (comp1,..) as components of the `lib`?
I know that each component lib looks like a separate lib.
Does conan consider it or should some internal developer tool do it?

**Comment by memsharded** [comment]
Hi @Dimitrius-dev 

I am moving this to the main Conan client repo, I don't think this is related to the examples2 repo.

**Comment by memsharded** [comment]
Thanks for your question.

> So everything is fine, i can use cmake FetchContent or other tool in def source(self) method in lib to get lib component. What if components depend on external lib (boost, spdlog....). I suppose it can use conan too). I mean it kind of this:

Every ``conanfile.py`` represents a package, and if packaging a third party (very different than if packaging your own code), then it will use a ``source()`` method that typically either ``download()`` a tarball with the sources or does a ``git.clone()`` of those sources. ``FetchContent`` is something specific to CMake, but this is not related, every package could have its own build system, and every package is an isolated unit, it builds and package from source its own binaries, it doesn't share the build with other packages.

> To the main question. In this case the top library does not have any code, it only links other libs and declares them like components.

What do you mean? A static library doing a re-archive of the dependencies static libraries? This is something very unusual, but I have seen it a couple of times. Or a shared library linking those static libraries into it? When talking about packages we have artifacts, either headers or headers and compiled libraries, or executables.

It seems that in that second case, mostly you wouldn't need the "top" library at all. If the other components become independent packages, then no need to aggregate all of them together into a single virtual entity that just aggregates them. If that is the use case, then why not just letting them inside the same package and using the ``self.info.components`` definition.

**Comment by Dimitrius-dev** [comment]
I realized that every package is independent unit and "virtual" top library (without sources) is a bad idea.

Conan recipe contains the instructions that depends on build system. So the build system defines library component hierarchy (comp1, comp2...), not conan, doesn't it? For example `boost` lib has a lot of components placed into separated repositories. Build system `b2` consider all of sources and build them. Conan recipe declares how to use b2 and collect artifacts. Is it right?

**Comment by memsharded** [comment]
> I realized that every package is independent unit and "virtual" top library (without sources) is a bad idea.

That is the essence of the "package management" or "package based development". Packages are independent and isolated units of development. The moment a package can define its own version, it has to be able to be developed completely independently of the rest, including having a different build system if the package wants.

This is a completely different paradigm than "mono-repo" or "monolith based development", where all parts are in the same repo using mostly a unified build system and being developed with a "live-at-head" strategy.

> Conan recipe contains the instructions that depends on build system. So the build system defines library component hierarchy (comp1, comp2...), not conan, doesn't it? For example boost lib has a lot of components placed into separated repositories. Build system b2 consider all of sources and build them. Conan recipe declares how to use b2 and collect artifacts. Is it right?

Yes, conan recipes implement the full flow: collect the sources with ``source()``, call the build with ``build()``, extract the final artifacts with ``package()``. Conan recipes can also define and inject tools like ``b2`` via ``tool_requires``.

Conan recipes will have the ``package_info()`` method that provides the description of the package in an abstract way. At the moment it is not possible to automatically deduce that from the build, so it is necessary to write it in the recipe. For example the ``boost`` recipe will define a ``package_info()`` method that defines multiple ``self.cpp_info.components["regex"]...``, instead of a single ``self.cpp_info.libs = ["zlib"]`` that other package such as zlib would do.

**Comment by Dimitrius-dev** [comment]
Thank you for detailed explanation. It helped me to understand conan functionality for building complex library.
