### ISSUE TITLE
[feature] `host` sematic is quite confusing, I suggest changing it to another word!

### ISSUE THREAD

**Issue by aiyolo** [conan-io/conan#16385]
### What is your suggestion?

In conan, the `host`  represents the machine that our program will run, and `build` represents the machine where the programs is built. 

However, this sematic is quite different from others.

For example, msvc compiler path is `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe`, the host means where the program is built, which has the same sematic as `build` in conan. In other places, the `host` also means the machine where we develop program on.

Therefore, I suggest chaning `host` to another word, maybe `target` is enough clear.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @aiyolo 

Thanks for your suggestion.

This has been largely discussed already, and we have decided to stick with the GNU definition of host-build-target contexts.
In any case, even if we wanted to move to that Microsoft naming, it wouldn't be possible, because it would be breaking, we cannot change all the places where "host" and "build" appear without breaking, as it appears even in the command line arguments.

Thanks for your suggestion anyway!

**Comment by RubenRBS** [comment]
Hi @aiyolo thanks a lot for your feedback, we appreciate it.

While we understand that these terms might be confusing at first if not already familiar with the terminology (which we didnt come up with! Gcc being the most popular example, see https://gcc.gnu.org/onlinedocs/gccint/Configure-Terms.html), we are pretty unlikely to change this ever, as the Conan ecosystem has adopted this for quite a while and changing it would be pretty confusing at this point.

Either way, thanks a lot for taking the time to write the suggestion, we appreciate it :)

**Comment by aiyolo** [comment]
Thanks for your reply.
