### ISSUE TITLE
[question] Tool with requires

### ISSUE THREAD

**Issue by MichalCermakx** [conan-io/conan#16413]
### What is your question?

Hi,

I have a Conan tool (tool_requires), that is a composite wrapper for multiple smaller build tools. In other words, I am releasing a single version of this wrapper tool to simplify versioning on the consumer side. Users can point to a single tool instead of tracking multiple sub-tools.

I have a model, where this composite wrapper tool is consumed as tool_requires and has multiple **requires** defining subtools.
This worked in Conan1, but Conan2 detects this and skips binaries for subtools.
I still want to have the wrapper and sub-tools local (In the build context) of a direct consumer of a wrapper.

Is there a way to get a behavior I have with Conan1? I understand that I cannot mark sub-tools as tool_requires, because those will be used only for wrapper tool build.

Thank you.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @MichalCermakx 

Thanks for your question.

If the transitive packages are being skipped is maybe  because it is not enough specified. There could be some ways to specify this:
- Have you defined the ``package_type`` of the packages to be ``application``?
- The ``requires`` of the aggregator package should probably use ``self.requires("dep/0.1", ..., run=True)``, the ``run=True`` trait specifies that the dependency is needed to run, and it will not be skipped.

Besides that, Conan 2.4 released "vendor" packages that might be useful for aggregation/vendorization cases.

**Comment by memsharded** [comment]
Hi @MichalCermakx 

Any further question or comment here? Thanks for your feedback.

**Comment by MichalCermak123** [comment]
No further questions.

I checked https://blog.conan.io/2024/07/09/Introducing-vendoring-packages.html and it is exactly what I need, thank you very much.
Michal

**Comment by memsharded** [comment]
Great, thanks for your feedback!
