### ISSUE TITLE
[bug] Unable to find dependencies' headers

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan#16421]
### Describe the bug

version: 2.4.0
conan_path: D:\venv\Scripts\conan
python
  version: 3.9.13
  sys_version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
  sys_executable: D:\venv\Scripts\python.exe
  is_frozen: False
  architecture: AMD64
system
  version: 10.0.22631
  platform: Windows-10-10.0.22631-SP0
  system: Windows
  release: 10
  cpu: Intel64 Family 6 Model 186 Stepping 3, GenuineIntel

### How to reproduce it

Hello.

I am not entirely sure whether this belongs to conan-center-index or here. Let's see.

Please follow these steps:

- `git clone https://github.com/Todiq/test_conan.git`
- Install the `msvc` profile inside the `profiles` folder
- Run `build.py` (windows or linux)

Although `rapidjson` is linked to `hello` as a public library, it is not visible to `beta` for some reason. It is like the `.cmake` files dedicated to find the headers are not propagated to `beta` (or generated at all?). 
Could you have a look into it?

Thanks in advance!

**Comment by AbrilRBS** [comment]
Hi @Todiq thanks a lot for taking the time to open the report, and for creating a repro to share your use-case, it's really appreciated! :)

This would not be a bug, but expected behaviour from Conan. Requirements can specify how and what of its contents is propagated by using traits ([docs here](https://docs.conan.io/2/reference/conanfile/methods/requirements.html#requirement-traits))
In this case, as `alpha` exposes `rapidjson` headers in its public api, its requirement clause should set the `transitive_headers=True` trait, like `self.requires("rapidjson/cci.20230929", transitive_headers=True)`, which will tell Conan that this dependency's headers should be propagated downstream.

Let me know if any of this makes sense and helps with your issue, happy to answer further questions if not :)

**Comment by Todiq** [comment]
Thank you! That indeed works now.

My real project's tree is quite complex and it looked like this issue happened specifically with `rapidjson`.

It was actually because the downstream packages had direct dependencies to the other requirements, but not that one, hence the false hint.

Thanks a lot once again!
