### ISSUE TITLE
Versioning strategies 

### ISSUE THREAD

**Issue by shiva7214** [conan-io/conan#16442]
### What is your question?

What is the best versioning method can be adopted if we have dependent libraries for multiple projects 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @shiva7214 

Versioning is a large and complex topic, there is no "best" versioning strategy for all cases, and every organization, team and project might use different versioning strategies.

If you want to read more about it, you can find: https://docs.conan.io/2/tutorial/versioning.html

In C and C++ the topic is even more complicated than in other programming languages, because of the ABI and binary compatibility. This section https://docs.conan.io/2/reference/binary_model.html will cover this aspect in Conan

You can see for example the default ``minor_mode`` effect of ``python_requires`` on the package binaries in https://docs.conan.io/2/reference/extensions/python_requires.html#effect-in-package-id, the effect of regular requires will also be very similar.

**Comment by memsharded** [comment]
Any further feedback or question here @shiva7214 ?

If not, lets close the ticket, you can always create new tickets for any further questions.

**Comment by memsharded** [comment]
Closing, please create new tickets for any further question, thanks!
