### ISSUE TITLE
[Alexa Auto Error 2] Command '['conan', 'config', 'init']' returned non-zero exit status 2

### ISSUE THREAD

**Issue by LuRomano22** [conan-io/conan#16474]
### What is your question?

Environment details - 
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
python3 --version  -  Python 3.10.12
Conan version 2.4.1

Step - 
$ ./builder/build.py

Log
[BUILDER] INFO: Python version: 3.10.12
[BUILDER] INFO: Builder home: /home/amarante/Downloads/alexa-auto-sdk-4.3/builder/.builder
[BUILDER] INFO: Configuring Conan...
[BUILDER] ERROR: Command '['conan', 'config', 'init']' returned non-zero exit status 2.

Info-
export PATH="$PATH:/usr/bin"

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi! usually for these kinds of issues we need better error info, but in this case the issue is easy enough:

You're running `conan config init`, which is a Conan v1 command, but as per your report, you're running Conan 2.4.1, for which this command has disappeared. Are you unexpectedly using an updated Conan version while your scripts still asume Conan 1?

**Comment by LuRomano22** [comment]
Thank you! Worked!
