### ISSUE TITLE
[question] Dependency loop when including gcc as a profile tool_requires

### ISSUE THREAD

**Issue by kristofferkoch** [conan-io/conan#16598]
### What is your question?

Hi

I've built a x86_64 gcc toolchain I want to use in a conan profile via tool_requires. I've used the gcc recipie in conan-center-index, that again have some dependencies such as mpfr. It would be very nice in our company if we could ensure that everyone is using the same compiler, and it would help us reducing the pain in developers flow when we change compilers.

```
[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++11
build_type=Release
[options]

[tool_requires]
gcc/12.2.0@company
```

So there's kind of a bootstrap issue here, because if I try to use this profile with `gcc/12.2.0`, I get a "ERROR: There is a cycle/loop in the graph", because, as I understand it, using that profile will require e.g. mpfr or m4 to also require gcc/12.

So my question is:
- Is it a bad idea to make a profile with gcc like this?  
- Using the tool_requires like `&:gcc/12.2.0` seems to break the loop and fix the problem. Is this a good idea?
- Am I missing something or trying to solve the wrong problem?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @kristofferkoch 

Thanks for your question.

> So there's kind of a bootstrap issue here, because if I try to use this profile with gcc/12.2.0, I get a "ERROR: There is a cycle/loop in the graph", because, as I understand it, using that profile will require e.g. mpfr or m4 to also require gcc/12.

Yes, this is expected. Bootstrapping with the same profile might be an issue. It seems this could be a good candidate for "vendoring" package for ``gcc``, like in https://docs.conan.io/2/devops/vendoring.html (it is a very new feature, we are writing now a blog post to explain it more thoroughly). With this, you can bootstrap your ``gcc/12`` compiler using a previous version or a system compiler, then forget about the dependencies of ``gcc/12`` for normal usage.

> Is it a bad idea to make a profile with gcc like this?

No, it is not a bad idea to have a profile like this, to apply it for the ``host`` environment as ``host`` profile. Trying to use this profile to build ``gcc/12`` itself is not possible.

> Using the tool_requires like &:gcc/12.2.0 seems to break the loop and fix the problem. Is this a good idea?

The ``&`` placeholder means the "current consumer". If the consumer is ``gcc/12`` then maybe not a great idea, it depends on how exactly you are trying to build ``gcc/12``.

> Am I missing something or trying to solve the wrong problem?

Have you considered using a different "build" profile? So your build profile does not contain ``tool_requires`` to ``gcc/12``?
Then you can perfectly build packages in the build context. Maybe the main issue is that to ``conan create`` the ``gcc`` package the right syntax would be:
```
conan create <path to gcc recipe> --profile:build=default --profile:host=myprofileabove --build-require
```
Note the ``--build-require`` arg will manage to put the creation of the ``gcc/12`` as a ``tool_require`` in the "build" context and receive the "build" (default) profile, instead of the profile with ``gcc/12`` as tool-require.

**Comment by kristofferkoch** [comment]
Thanks for helping on the thought process here.

I think the right approach for us is to use the profile with `tool_requires` on `--profile:host` only, and then lean on the system (ubuntu) compiler for the build profiles.

Also thanks for pointing me towards the vendoring things. That will probably be very useful for other things :)

**Comment by memsharded** [comment]
Happy to help! :) 

Don't hesitate to create new tickets if you have any further questions.
