### ISSUE TITLE
[question] how can I download prebuild binarys in a remote repository to a given path rather than the cache path

### ISSUE THREAD

**Issue by Anchorli** [conan-io/conan#16622]
### What is your question?

how can I download prebuild binarys in a remote repository to a given path rather than the cache path

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Anchorli 

To copy binaries to your user space instead of the cache you can use deployers, see https://docs.conan.io/2/reference/extensions/deployers.html#deployers

You can also write your own custom deployers: https://docs.conan.io/2/examples/extensions/deployers/custom_deployers.html#custom-deployers

Note that in most cases, it is recommended to use packages from the cache, because the cache structure guarantees there are no collisions or overwrite of different package versions or package binaries.

**Comment by Anchorli** [comment]
> Hi @Anchorli
> 
> To copy binaries to your user space instead of the cache you can use deployers, see https://docs.conan.io/2/reference/extensions/deployers.html#deployers
> 
> You can also write your own custom deployers: https://docs.conan.io/2/examples/extensions/deployers/custom_deployers.html#custom-deployers
> 
> Note that in most cases, it is recommended to use packages from the cache, because the cache structure guarantees there are no collisions or overwrite of different package versions or package binaries.

Thanks. The question has been resolved
