### ISSUE TITLE
[question] mixing recipes for different conan versions (1 and 2) based on revisions.

### ISSUE THREAD

**Issue by forry** [conan-io/conan#16645]
### What is your question?

Hi,
on our private remote using conan 1, I'm now trying to migrate packages to conan 2. We don't use revisions in conan 1 so every package is under `#0` or a 0 folder on Artifactory (AF). So I was thinking that, when I change the recipe for the same version of a package and export it by conan 2, conan 1 will not see it. Sadly I used required_conan_version = ">=2.0" in those packages, and one of my colleagues now reporting that he is not able to download the package since he has only 1.61. So it seems that even with revisions turned off the server is trying to give him the one that was created by the conan 2.

I was hoping that I could migrate slowly one package at a time and that this was somehow solved on the conan client side. When all of the work/testing is done we just switch to conan 2 and then it will start downloading the non-0 revisions and everything will work.

How to approach this problem?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @forry 

Thanks for your question.

The transition using the same repositories can only happen if revisions are enabled in Conan 1. The revisions feature has been in Conan 1 since 5 years ago, and it has been recommended since then.

The way the migration is intended to be done in most cases is using the same recipes, with the same revision for both Conan 1 and Conan 2. No need to do a ``required_conan_version = ">=2.0"``, the full ConanCenter +1500 recipes was updated without adding this, as there is a common recipe syntax that works both in Conan 1 and Conan2. Then the binaries are different for Conan 1 and Conan 2, but having the same recipe for both cases simplifies a lot. 

But that requires having revisions enabled in Conan 1. If you don't have revisions enabled in Conan 1, the best approach would be to use separate server repositories.

The migration can still be done one package at a time, from the dependency graph top to the bottom, but using different repositories. As the configuration files (``settings.ml``, profiles, ``global.conf``, etc) are different in Conan 1 and 2, it would make sense to have different configuration repos for ``conan config install`` in Conan 1 and Conan 2, and then adding a ``remotes`` file to the config pointing to different repos would be part of the configuration anyway.

**Comment by forry** [comment]
Thank you very much. I suspected having a different repository would be the easiest way in our case.
