### ISSUE TITLE
[question] multiple "flavors" of same package depending on preprocessor

### ISSUE THREAD

**Issue by nikoladsp** [conan-io/conan#16651]
### Multiple flavors of same package

Hi,
lets say I have a rather complex package `MyLib` which provides different functionalities: `A`, `B` and `C`, controlled by preprocessing directives. Client buys some (or all) functionalities from available: `A`, `B` and `C`. So it is still the same package but different binary output(s). 

I am not sure if my choice of words is correct, but:  is it possible to somehow build the same package (same name) but different  "metadata" so client that bough  `B` and `C` gets `MyLib` with  `B` and `C` enabled and client bought 'A' gets `MyLib` with  `A` enabled? Or we have to store on different JFrog instances (per client)?

Kindest regards

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @nikoladsp 

Thanks for your question.

There are 2 different aspects here. The first one is the creation and management of different binaries. In this case, if preprocessor directives are creating different binaries, the typical approach is something:
- Define some ``option`` in the package (unless those preprocessor are more system-wide, in that case a custom setting might be better). There is also the possibility to use a ``conf`` like ``tools.build:defines``, and another conf to make ``tools.build:defines`` part of the ``pacakge_id``. In general I'd say the ``options`` approach is the most natural.
- Create the different binaries with the different options values.
- Upload and usage of those binaries by other packages and projects on your side.

Then, a different problem is the distribution of those binaries to different customers that should have different access permissions to those different binaries. This is something that belongs more to the server side capabilities than to the Conan client.
When using Artifactory the permissions are mostly set per-repository, not per-package binary. So yes, it would be necessary to set different Artifactory repositories for the different customers. Note that this is not an issue, because Artifactory has package de-duplication, so having the same packages in multiple repositories will not use extra storage. Up to my knowledge it is not necessary to use different instances, just different repositories, but those kind of questions is better to ask JFrog support directly.

**Comment by nikoladsp** [comment]
Thank you very much!
