### ISSUE TITLE
[question] Conan2 / Conan1 profile compatibility?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#16669]
### What is your question?

Hi,

I'm trying to come-up with a plan how to migrate from Conan1 to Conan2 on a step-by-step basis.
My very first issue is the profile compatibility.

E.g. for the "msvc" compiler for Conan2 there is

tools.microsoft.msbuild:vs_version=16 (https://github.com/conan-io/conan/issues/16649#issuecomment-2224132218)

but it doesn't seem to be working with Conan1.

So my question is it possible to use the same profiles for Conan1 and Conan2?

Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

> So my question is it possible to use the same profiles for Conan1 and Conan2?

In some simple cases, it might be possible to have the same profiles, but in the general case, it isn't:

- Visual compiler has changed from ``Visual Studio`` => ``msvc``
- The ``compiler.cppstd`` is totally recommended in Conan 2, almost necessary.

In any case, the recommended way to share configuration, including profiles is with ``conan config install`` (or ``conan config install-pkg`` using Conan packages in Conan2), because there are many other configuration files that might need to be shared as well, from custom ``settings.yml``, profile files, hooks, many of the new ``plugin`` extensions in Conan 2, the ``global.conf``...). So it is expected that the configurations in general will be different in Conan 1 and Conan 2.

**Comment by harsszegi** [comment]
Awesome, thanks a lot for the quick response @memsharded , closing it!
