### ISSUE TITLE
[question] Need help to understand the packaging mechanism in Conan 2

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#16663]
Hi,

I have hard time understand how packaging works now in Conan 2.

I see: https://github.com/conan-io/conan/issues/13722
and https://github.com/conan-io/conan/issues/9414 and both confuse me a lot.

My use case is as follows:

* We are maintaining several open source packages that are used also in Yocto and in Conan (different build environments)
* Because of the item above we can't realy on Conan generated find_package .cmake files

My workflow:

* I do conan build
* I did conan package - which is not available anymore
* I do conan export-pkg

As I need to rely on the normal .cmake scripts generated by the package maintainers, CMAKE_INSTALL_PREFIX must be consistent across the whole workflow, meaning it is flat-out wrong that during CMake --configure you set it to a value,
and later during cmake --install you set it to something completely different.
The end result is that we end up semi-broken packages, as because of the wrong CMAKE_INSTALL_PREFIX being used in the --configure step, some of the find_package .cmake files generated by CMake are at the wrong location.

Even if that is fixed, I still need to be able to "revive" the cmake_paths generator use case, e.g. for me the Conan / CMakeDeps generated find_package .cmake files are not usable (mostly because they are not following the maintainers intention and they place the CMake targets into different namespace - which breaks Yocto/Conan interop) and not to mention that forcing Conan's CMAKE_TOOLCHAIN_FILE usage is somewhat an overkill as it blocks out custom CMAKE_TOOLCHAIN_FILE usage (again Yocto/Conan interop).

So my question:
* Why was "conan package" removed? - as that solved the inconsistency between the CMAKE_INSTALL_PREFIX between steps, as a complete package was produced in a user given given folder location, which later could be properly exported to the cache
* How can the current inconsistent CMAKE_INSTALL_PREFIX behaviour be resolved?
* How can the thinnest cmake_paths generator behaviour revived (e.g. no CMAKE_TOOLCHAIN_FILE, only CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH being used for dependency location)

Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

Thanks for your question.

> Because of the item above we can't realy on Conan generated find_package .cmake files

Not a problem, it is possible to use .cmake files inside packages, see https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html (just beware of the limitations)

> I do conan build
I did conan package - which is not available anymore
I do conan export-pkg

This workflow is not really intended for "production" creation of packages, instead the ``conan create`` is more recommended. That is the "local developer flow" intended for local testing by developers, but in general it is easier and more robust to do ``conan create`` to create the packages.

In any case, it is not an issue, it is possible to do just ``conan build`` + ``conan export-pkg`` without the intermediate ``package``, because Conan 2 knows how to package from the "build layout". Please see https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html

Note the example in that tutorial section uses 
```python
    def package(self):
        cmake = CMake(self)
        cmake.install()
```
And it works correctly with a ``conan build`` + ``conan export-pkg``.


> Even if that is fixed, I still need to be able to "revive" the cmake_paths generator use case, e.g. for me the Conan / CMakeDeps generated find_package .cmake files are not usable (mostly because they are not following the maintainers intention and they place the CMake targets into different namespace - which breaks Yocto/Conan interop)

You have full control over what the ``CMakeToolchain`` is creating, you can use just the "find-paths" block if you want: see https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#extending-and-advanced-customization

You can even configure from the profile which blocks are enabled with ``tools.cmake.cmaketoolchain:enabled_blocks=["generic_system"]``, so you can use the full Conan toolchain for more native builds and use the blocks that you want, maybe just the ``find_paths`` one for another configuration such as Yocto.

**Comment by harsszegi** [comment]
Thanks you very much @memsharded for the quick response, closing it!
