### ISSUE TITLE
Conan2 Config Uninstall

### ISSUE THREAD

**Issue by alund-mt** [conan-io/conan#16674]
### What is your question?

Hello!

What is the recommended way to uninstall conan 2 configurations? Previously, in conan 1, there was the [conan config](https://docs.conan.io/1/reference/commands/consumer/config.html) command with the `rm` param, but it doesn't seem like the same thing exists for conan 2.

There is the [conan remove](https://docs.conan.io/2/reference/commands/remove.html) command, but this seems like it's for packages, and not configurations.

Cheers!

Andy

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @alund-mt 

Thanks for your question.

There is no method to uninstall configuration. This is due to the fact that configuration can be additive and overlapping. For example, it is possible to do consecutive ``conan config install`` from different URLs or ``conan config install-pkg`` from different packages, to install different things, like installing profiles from one origin, then installing ``settings_user.yml`` and plugins from other origin etc.

Those ``config install`` can also have overlapping and overwriting files, for example if two different origins install the same profile file with the same name, they will overwrite each other. 

Then tracking to which "origin" every change in the Conan home comes from is nearly impossible.

In Conan 1, the ``conan config rm`` was only useful to remove a specific entry in the ``conan.conf`` file, but not to uninstall different configurations from ``conan config install``, if this is what you meant in your question, so in this regard nothing has changed with respect to Conan 1.

The recommendation would be to clean the cache (a ``rm -rf <cache-folder>``) and then ``conan config install`` the configuration again.

Please let me know if this helps.

**Comment by alund-mt** [comment]
Thanks `memsharded`!!

Just to be sure, when you say, clean the cache, you don't mean via `[conan cache clean](https://docs.conan.io/2/reference/commands/cache.html#conan-cache-clean)` right?

Cheers!

**Comment by memsharded** [comment]
> Just to be sure, when you say, clean the cache, you don't mean via [conan cache clean]

No, the ``conan cache clean`` is intended to remove the temporary folders and files (like the build folders) that are no longer necessary in the cache, while retaining the important files (conanfile recipes, package binaries), to save some space.

I meant to full remove the current Conan home. In practice, in CI scenarios, a blank cache will be used anyway (the Conan cache is not concurrent at this moment, cannot be reused by multiple CI concurrent jobs). For developers that went into some dirty state in their cache and want to start fresh it would be:

- Remove the current conan home with ``rm -rf <conan-home>`` (typically <userhome>/.conan2)
- Re-install the organization configuration with ``conan config install`` or ``conan config install-pkg``.

Though in general the full removal shouldn't be necessary in most cases, as the ``conan config install`` commands can be repeated, and as they overwrite the previously existing configuration files, it will be almost equivalent to a clean state. Only in some scenarios where some trailing old files not used anymore are left there a full clean might be necessary.

**Comment by memsharded** [comment]
Hi @alund-mt, any further question, or maybe we can close the ticket as responded? Thanks!

**Comment by alund-mt** [comment]
We can close this!
