### ISSUE TITLE
[question] Conan1 vs Conan2 package id compatibility + possibility of Artifactory hash collision?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#16673]
Hi,

as I understand profiles / settings cannot be considered 100% compatible between Conan1 and Conan2.

Is the same logic applicable to package ids? I want to figure out whether we can safely use our one-and-only Conan Artifactory remote for both Conan1 and Conan2 packages without worrying that because of hash collision Conan1 package uploads might overwrite a Conan2 package and vice-versa.

Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Thanks for your question @harsszegi 

> s the same logic applicable to package ids? I want to figure out whether we can safely use our one-and-only Conan Artifactory remote for both Conan1 and Conan2 packages without worrying that because of hash collision Conan1 package uploads might overwrite a Conan2 package and vice-versa.

``package_ids`` are exclusively disjoint between Conan 1 and Conan 2. They should never have the same ids.
Furthermore, package binaries are only exclusively visible from each respective version. Package binaries built with Conan 1 are only visible (``conan search``) in Conan 1 and package binaries built with Conan 2 are only visible (``conan list``) in Conan 2.

This allows to use the same server repositories for Conan 1 and Conan 2, and ease the transition. 
The main thing to be taken into account is that the recipe must be the same, generating exactly the same **recipe revision**. If the recipe is not exactly the same and creating the same recipe revision, then it would be necessary to use different server repositories for the respective packages. But in general, using the same recipe for both Conan 1 and 2 is the recommended approach, it is what +1500 recipes in ConanCenter have done, because there is this common syntax in Conan 1 and 2 that allows having exactly the same recipe for both.

**Comment by harsszegi** [comment]
Awesome, thanks a lot for the quick response @memsharded , closing it!
