### ISSUE TITLE
[feature] Extend revision_mode 'scm_folder' to allow for multiple folders

### ISSUE THREAD

**Issue by fredrikkz** [conan-io/conan#16677]
### What is your suggestion?

Hi! I would like for `conan` to be able to optionally consider multiple folders for calculating the latest git commit hash when using `revision_mode = "scm_folder"` (or add a new revision mode, or even a function `set_revision()` in `conanfile.py`)

My motivation for this use case is as follows:

* I have a monorepo
* This monorepo contains multiple `conanfiles.py`, each describing static/dynamic libs and executables
* Some folders in the monorepo is shared by multiple different libs and exes

My usage pattern is very similar to the subproject example found here: https://docs.conan.io/2/examples/conanfile/layout/multiple_subprojects.html

Expected behavior, using the subproject example from above:
Revision of `hello` would be the latest commit to either `hello` or `common` folder. Likewise for `bye`, i.e. any edits to `common` would create new package revisions for both `hello` and `bye`

I don't know if this is possible to do already, but from my brief look at the `revision_mode` code, it doesn't look like it.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by fredrikkz** [comment]
NOTE: I'm not a git expert by any means, but the comparison could possibly be made by `git rev-list <first_hash>..<second_hash> -n 1`, and if one get any output, `second_hash` is newer than `first_hash`. But there might be better ways, so grain of salt.

**Comment by memsharded** [comment]
Hi @fredrikkz 

Thanks for your suggestion.

Though it seems a valid feature request at first sight, I'd need to understand better the use case for the reproducibility:

- When using the ``revision_mode != "hash"`` it typically also means using something like the ``scm`` approach for sources: https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html, that is, capturing the url+commit of the sources in order to be able to build from sources.
- How are you implementing your source approach, via ``export_sources`` or via the ``scm`` capture of coordinates?
  - If using the ``export_source``, why would you want to change the revision to be a combination of git commits that cannot be used for reproducibility?


A couple of questions about possible implementation:
- What would be the computation of the revision, maybe adding all the commits for all folders and hashing them again?
- What would be the UI to define it? It seems a new attribute such as ``revision_mode_folders = ["../mycommon", ".", ...]`` would be the best way?
- I understand that it is fine that ``revision_mode_folders`` could be defined relative to the current ``conanfile.py`` location?

**Comment by fredrikkz** [comment]
> Hi @fredrikkz
> 
> Thanks for your suggestion.
> 
> Though it seems a valid feature request at first sight, I'd need to understand better the use case for the reproducibility:
> 
> * When using the `revision_mode != "hash"` it typically also means using something like the `scm` approach for sources: https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html, that is, capturing the url+commit of the sources in order to be able to build from sources.
> * How are you implementing your source approach, via `export_sources` or via the `scm` capture of coordinates?
>   
>   * If using the `export_source`, why would you want to change the revision to be a combination of git commits that cannot be used for reproducibility?

I currently _do not_ use `scm` mode, and I have as of today switched over from the `export_sources` attribute to the `export_sources()` function (setting `self.folders.subproject` and so on)

My use-case is as follows: We have a large monorepo with many users, moving at rapid pace. We intend on using the git commit hash as a "version" of sorts, without the need to explicitly update a manual number.

A user then syncs the repo. When building, we wish to check if a binary has been built by the build servers for the current state of the local git repo. If one can be found, it will be downloaded, and if not, a local build will kick off. Therefore, we are only interested in the _latest_ commit hash that affected a library. So it's important that we don't get a hashed value as the revision, rather, we need it to be the latest valid git commit that somehow influenced a particular binary (be it shared script CMake files, or actual code)

I.e. conan is actually integrated into our build process and CI/CD pipelines.
> 
> A couple of questions about possible implementation:
> 
> * What would be the computation of the revision, maybe adding all the commits for all folders and hashing them again?

For our use case, it's important that the revision corresponds to an actual git commit hash, and that would be the latest hash to affect a particular binary

> * What would be the UI to define it? It seems a new attribute such as `revision_mode_folders = ["../mycommon", ".", ...]` would be the best way?

Yes, a list of folders like that would be preferable, as that would allow us to re-use that list in other functions (such as `export_sources()`, for example)
> * I understand that it is fine that `revision_mode_folders` could be defined relative to the current `conanfile.py` location?

Yeah, I don't see any problems with that, as of now

**Comment by memsharded** [comment]
> I currently do not use scm mode, and I have as of today switched over from the export_sources attribute to the export_sources() function (setting self.folders.subproject and so on)

If you are using exports_sources, then the revision will already be unique and automatic, I am not fully sure what problem you are trying to solve then.

> My use-case is as follows: We have a large monorepo with many users, moving at rapid pace. We intend on using the git commit hash as a "version" of sorts, without the need to explicitly update a manual number.

The git commit of the repo? Then it is not related to the recipe-revision, this is a different thing. For automatic versioning, the typical approach is to use the ``set_version()``

> A user then syncs the repo. When building, we wish to check if a binary has been built by the build servers for the current state of the local git repo. If one can be found, it will be downloaded, and if not, a local build will kick off. 

This should be automatic with Conan a simple ``conan create --build=missing`` would be enough to download the package if existing or build if if not existing.


> For our use case, it's important that the revision corresponds to an actual git commit hash, and that would be the latest hash to affect a particular binary

Why? Reproducibility is achieved by ``exports_sources`` in this case. In any case, there is not a unique latest hash to affect a particular binary, if the binary comes from different folder, either the top level folder commit is used, or otherwise it is necessary to take the different commits of the different folders and hash them together to obtain a new and unique recipe revision.


So overall, I think I might not have understood the problems to solve. Is it expected to have automatic versions with ``set_version()``? What are the expected update strategies from downstream consumers of the packages, are they using version ranges? Or do you expect to use the "latest" recipe revision resolution as an update strategy? Also, the mentioned "latest commit" doesn't seem aligned with the feature request that allows to specify multiple folders, maybe this can be clarified.


As some side feedback: We have discarded in the past the possibility of allowing defining ``recipe revision`` from recipes. The likelihood that users will use non unique revisions or not mapped 1:1 to code changes are too high, and when this happen it will result in confusion and lots of issues and support tickets. Basically we consider it a shotgun, and we are reluctant to add it because it will certainly cause problems.

**Comment by fredrikkz** [comment]
> > I currently do not use scm mode, and I have as of today switched over from the export_sources attribute to the export_sources() function (setting self.folders.subproject and so on)
> 
> If you are using exports_sources, then the revision will already be unique and automatic, I am not fully sure what problem you are trying to solve then.

We've been trying to avoid the export_sources hash as it relies on files being copied and present in order to calculate it. I thought that using `revision_mode = scm_folder` would be a good workaround for that problem. Case in point, each artifact can consume and output gigabytes of data, and we'd like to skip pullling files unless needed, for example. With `scm_folder`, we need git history, but not actual files

> 
> > My use-case is as follows: We have a large monorepo with many users, moving at rapid pace. We intend on using the git commit hash as a "version" of sorts, without the need to explicitly update a manual number.
> 
> The git commit of the repo? Then it is not related to the recipe-revision, this is a different thing. For automatic versioning, the typical approach is to use the `set_version()`

I think you are correct here, that we should use `set_version` instead of `revision_mode = scm_folder`. I did not realize that the first hash of the package was the recipe hash, but now that you spell it out, it makes sense

> 
> > A user then syncs the repo. When building, we wish to check if a binary has been built by the build servers for the current state of the local git repo. If one can be found, it will be downloaded, and if not, a local build will kick off.
> 
> This should be automatic with Conan a simple `conan create --build=missing` would be enough to download the package if existing or build if if not existing.
> 

Side-note, we did try it at first, but didn't manage to get it working properly (this was probably due to us running `conan export` prior, which made some packages show up as `Installed` but not `Missing`, causing a local build of those even tho they existed on the build server, IIRC. We ran `conan export` in order to run `conan inspect`, but that path is removed now, so perhaps we can simply switch back now. Memory is a bit fuzzy on this one, however

> > For our use case, it's important that the revision corresponds to an actual git commit hash, and that would be the latest hash to affect a particular binary
> 
> Why? Reproducibility is achieved by `exports_sources` in this case. In any case, there is not a unique latest hash to affect a particular binary, if the binary comes from different folder, either the top level folder commit is used, or otherwise it is necessary to take the different commits of the different folders and hash them together to obtain a new and unique recipe revision.
> 
> So overall, I think I might not have understood the problems to solve. Is it expected to have automatic versions with `set_version()`? What are the expected update strategies from downstream consumers of the packages, are they using version ranges? Or do you expect to use the "latest" recipe revision resolution as an update strategy? Also, the mentioned "latest commit" doesn't seem aligned with the feature request that allows to specify multiple folders, maybe this can be clarified.

I actually think `set_version()` will solve our problems now. I did not realize we were actually messing around with the recipe hash, but got it mixed up with the export_sources one. Furthermore, I did not realize that a version could contain alphanumeric characters. This seems like the correct approach for how to version the artifacts, rather than our previous approach, as having a scheme of `my_lib/1.0.<some hash>` would both allow for a unique ID as well as providing version range support for the first two digits. I will give it a whirl, and if it works, close down this ticket

> 
> As some side feedback: We have discarded in the past the possibility of allowing defining `recipe revision` from recipes. The likelihood that users will use non unique revisions or not mapped 1:1 to code changes are too high, and when this happen it will result in confusion and lots of issues and support tickets. Basically we consider it a shotgun, and we are reluctant to add it because it will certainly cause problems.

Yeah, I felt that it was a bad suggestion when I wrote it, as well :)

**Comment by fredrikkz** [comment]
Switching over to `set_version()` was indeed a much better approach, and solved all our issues. Thanks!
