### ISSUE TITLE
[question] Header library automatic downstream header propagation

### ISSUE THREAD

**Issue by forry** [conan-io/conan#16694]
Hi,
I have a typical graph `app -> sharedlib -> functionalplus/0.2.24` (header-library from conan center). The fplus is a public dependency of `sharedlib` so the app needs it. In other questions like #16485 you advise using `transitive_headers=True` in the requirements of `sharedlib`. But in the [doc](https://docs.conan.io/2.4/reference/conanfile/methods/requirements.html#package-type-trait-inferring)  in the last paragraph it seems that it should be inferred automatically for this package_type (and it is correctly set in fplus recipe). What am I missing here? Also, why are the `transitive_libs=True` in the header-library, I'm confused.

Also on a side note, it would be nice to have a system similar to cmake's public/private notation simplification.

conan 2.4.1

**Comment by AbrilRBS** [comment]
> But in the [doc](https://docs.conan.io/2.4/reference/conanfile/methods/requirements.html#package-type-trait-inferring) in the last paragraph it seems that it should be inferred automatically for this package_type

In the docs, the section about inferred value based on the dependant's package_type
> Additionally, some additional traits are inferred on top of the above mentioned based on the package_type of the dependant

Refers to the current recipe, so that if I have `header-only` -> `library`, the requirement in `header-only` for `library` will by default have the inferred `transitive_headers` trait already set

This could probably be clarified a bit better in the docs, will try to find better wording for this section, thanks for the feedback!

(The other way around is not desirable as that would cause over-propagation in cases where the header-only dependency was not part of the API of your library)

**Comment by forry** [comment]
Thanks! Still a bit confused. Better wording and examples would be appreciated. I was also looking at the HTML graph generated by conan trying to see if there is a way to get the final traits of the dependency with respect to the graph root. That would also be nice. Either way, it seems that the safest way is to overspecify everything in the requirements() method.

**Comment by AbrilRBS** [comment]
By clicking the edges themselves you can get info about the requirement, with the traits being part of it :)

**Comment by forry** [comment]
Very nice, thanks! But sadly the transitive stuff isn't here, so I don't know what gets to the "bottom of the graph" from that particular package.
