### ISSUE TITLE
[bug] `self.source_folder` varies whether building with `conan create .` or `conan build .`.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16699]
### Describe the bug

Hello,

I'm trying to build Qt 5.15.14 with Conan 2.  The first time, I tried to build it with a `conan create .` and somewhere in the middle there was an error.  After making the necessary ammendments, I resumed building with a `conan build .` .  I do this because Qt's source base is very large (5GB decompressed).  I wanted to skip all the source decompression part which takes more than an hour to complete. 

When I run `conan create .`, the configure line starts with:

```bash
C:\conan_packages\qtd005d536259ca\s\qt5\configure -shared -confirm-license -silent ...
```
which is correct (in the directory with the Qt package).  However, when running `conan build .`, the configure command starts with:

```bash
c:\git_repository\conan_recipes\qt\5.15.14\qt5\configure -shared -confirm-license -silent ...
```
which is wrong.  The `c:\git_repository\conan_recipes\qt\5.15.14` part is the Git local repository with the source code, not Conan's workspace, it is the directory where I run both `conan ...` commands and it is being incorrectly assigned to `self.source_folder` according to my current understanding of how Conan work.

thank you,

PC

### How to reproduce it

OS: **Windows**
Toolset: **Visual Studio 2022**
Conan: **2.3.2**
Python: **3.12.3**

**Comment by memsharded** [comment]
Hi @PauloCarvalhoRJ 

This doesn't seem a Conan issue, but a specific ``qt`` recipe issue (from ConanCenter).
I see that ``qt/5.X.X`` recipe there doesn't define any kind of ``layout``. This means the recipe is mostly not prepared for the local development flow, and is only intended to be built in the cache with ``conan create``.

If you want to reproduce this with a simpler recipe, such as a ``conan new cmake_lib`` template one, then we can keep the ticket in this repo, otherwise it can be moved to ``conan-center-index``. Note that even if moved, it might not be changed, as ``conan-center-index`` doesn't mandate recipes to support the local development flow, and qt recipe can be complicated.

**Comment by PauloCarvalhoRJ** [comment]
Hello,

That makes sense.  Indeed, there are packages developer-oriented and packages designed for deployment.  I didn't know Qt was such case.  I guess that note of yours could be added to the docs (https://docs.conan.io/2/reference/commands/build.html#conan-build).  The way it is written, it likely leads users into believing `conan build .` can be used in all cases to bypass callbacks such as `source()` which takes more than an hour for Qt.

best,

PC
