### ISSUE TITLE
[question] compatibility strategy for Conan 1 between "Visual Studio" and "msvc"?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#16704]
Hi,

we are migrating to Conan 2 and as part of this, we are switching to "msvc" from "Visual Studio".
However we have tons of binary packages built and would like to use them as "compatible ones" for msvc (as indeed they are).
Is there a guide somewhere explaining how could I make them "compatible"?
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @harsszegi 

The package binaries in Conan 1 and Conan 2 are disjoint sets.
Even for exactly the same configuration (Linux, gcc, 11, Release, etc), the ``package_ids`` in Conan 1 and Conan 2 for that same configuration are different. This is because the ``package_id`` computation has been completely re-vamped. 
It is not possible to fallback or say that the binary from Conan 1 is compatible and can be used in Conan 2.
The recommended process is to enable a Conan 2 CI pipeline, and while changes to recipes are pushed to make them compatible with Conan 2, the Conan 2 pipeline will make sure to build and publish the Conan 2 binaries. We know that this is the only way that it can be fully verified that the recipes are working in Conan 2, and it will not be a future problem when dropping Conan 1 and then trying to build the binaries with Conan 2 only.

**Comment by harsszegi** [comment]
Sorry :) you misunderstood me @memsharded , I meant compatibility within Conan 1 itself :) I wish to switch our Conan profiles to msvc completely, however for Conan 1 packages I’d like to mark the “Visual Studio” packages compatible with the “msvc” ones.
For Conan 2 I don’t care, we need to build new packages anyhow.
Thanks,

**Comment by harsszegi** [comment]
Meh, it was easier than I thought, simply done via adding a new entry to compatible_packages in package_id(), converting the information in the Visual Studio compiler to the appropriate 'msvc' one.  Even further, this compatibility appears to be available by default in Conan 1. Closing it
