### ISSUE TITLE
[question] Support for gcc 14 in Conan 1

### ISSUE THREAD

**Issue by ottmar-zittlau** [conan-io/conan#16722]
### What is your question?

Hi,

I just noticed that conan 1.64.1 doesn't support gcc v14.1. 
(I think the relevant file is https://github.com/conan-io/conan/blob/1.64.1/conans/client/conf/__init__.py)

Are there any plans to add this version?
What could happen if I added this version to my local settings.yaml?
Would this only be a problem if the interface of gcc changed since the last supported version?

Thanks in advance and best regards!
oz

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @ottmar-zittlau 

Thanks for your question.

Conan 1.X releases are much slower these days, so the update of the default ``settings.yml`` doesn't happen fast either. This is expected. Conan 2 was already released 1 year and a half ago, and Conan 2 is the one getting fast releases and changes.

So there are no specific plans to add this version to the default settings, or when 1.65 will be released.
I think it is pretty safe to add it to your local ``settings.yml`` (in production, this shouldn't be done, but instead managing the ``settings.yml`` file via ``conan config install``). Conan also defaults to use ``compiler.version=14`` for gcc, so this would be something that you would be opting-in explicitly via your profile I guess, and I don't think anything has really changed that would break because of this.

**Comment by ottmar-zittlau** [comment]
Thanks again for the quick reply @memsharded ,

Unfortunately, we still haven't been able to migrate to Conan 2.0, yet.
I was not aware of `conan config install` - that's good to know.

Best regards,
oz

**Comment by memsharded** [comment]
> Unfortunately, we still haven't been able to migrate to Conan 2.0, yet.

Please note that this would be an important priority. ConanCenter will soon stop getting updates for new recipes, version and fixes for Conan 1.X. It will not break, as we will do a freeze, but it will not be updated.


> I was not aware of conan config install - that's good to know.

In Conan 2, there is even better, a new ``conan config install-pkg`` that can install configuration from a Conan package, and resolve using version-ranges to update to the latest, lock the specific version of the config in a lockfile, be made part of ``package_ids``...:  https://docs.conan.io/2/reference/commands/config.html#conan-config-install-pkg


Thanks for the feedback!
