### ISSUE TITLE
[question] requirements defined from a file and lockfiles

### ISSUE THREAD

**Issue by lstoffer** [conan-io/conan#16730]
### What is your question?

Hi! I have a questing regarding lockfiles.

I have a project in whick i have a conanfile called `conan_project.py`. In the `conan_project.py` file i am calling the requirements() function as follows:

```python
def requirements(self):
    for it in conan_requirements.get_requirements(self.version, library_only=False):
        self.requires(it)
```
Where the get_requirements function is some self written function that gathers the requirement strings from another file.
Calling conan install just with the `conan_project.py` file just works fine and the dependencies are resolved as expected.

However, if I try to call conan install with a lockfile, where one of dependencies is different in the `conan_project.py` file and the lockfile, it will always try to install the dependency from the `conan_project.py` file instead of the one from the lockfile.
Is this intended behaviour? Because what I would expect is that the dependency from the lockfile overrides the cone from the `conan_project.py` file.

I am calling conan install as follows:
`conan install conan_project.py --lockfile project_lock.lock --lockfile-partial`

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lstoffer 

Thanks for your question

> Where the get_requirements function is some self written function that gathers the requirement strings from another file.
Calling conan install just with the conan_project.py file just works fine and the dependencies are resolved as expected.

The recommended way to do this is adding those requirements in the ``conandata.yml`` file, and recovering this from the ``self.conan_data`` estructure:
- The ``conandata.yml`` is kind of standard storage for recipe configuration
- It is automatically exported
- It is automatically loaded and parsed into the ``self.conan_data``
- There is a hook and a helper ``trim_conandata()`` that can trim the conandata file when using it for multiple versions, to avoid new versions modifying the revisions of existing old versions


> However, if I try to call conan install with a lockfile, where one of dependencies is different in the conan_project.py file and the lockfile, it will always try to install the dependency from the conan_project.py file instead of the one from the lockfile.
Is this intended behaviour? Because what I would expect is that the dependency from the lockfile overrides the cone from the conan_project.py file.

Dependencies information stored in lockfiles (Conan 2) do not overwrite or modify existing ``requires``, they just constraint existing requires. For a locked version in the lockfile to be used, it must be inside valid version-ranges in ``requires()`` in recipes, or it must be a valid recipe revision for an existing version. In other words, a ``lockfile`` is a snapshot of a dependency graph that can be instantiated, kind of a picture of the reality that helps to reproduce the reality later in time, but it cannot change the reality (the reality would be the recipe ``requires()``) by modifying the stored picture.

**Comment by memsharded** [comment]
Please note that in order to have correct and consistent behavior, the definition of requirements, the file that is used to get the dependencies, must be exported together with the ``conanfile.py`` into the recipe, that is, it must be stored and "frozen" inside the recipe to achieve reproducibility and have immutable recipe-revisions matching 1:1 with package source inputs.

**Comment by lstoffer** [comment]
Thank you very much for your responses.
It seems that my understanding of lockfiles was not quiet right and that caused the issue.
