### ISSUE TITLE
[question] How to make meson find my windres binary?

### ISSUE THREAD

**Issue by Pibben** [conan-io/conan#16741]
### What is your question?

I'm building freetype 2.13.2 (along other dependencies) using conan, in  cross-compiling setting (using mingw32 on a linux host).

I get the following error message 

    ../src/meson.build:239:11: ERROR: Could not find Windows resource compiler

As I understand, meson looks for a binary called `windres` whereas my binary is called `x86_64-w64-mingw32-windres`.

**How do I tell meson (via conan) the name of my windres binary?**

My conan command line is 

     conan install .. -pr:b=default -pr:h=windows-cross --build=missing
```
$ cat ~/.conan/profiles/default
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

```
$ cat ~/.conan/profiles/windows-cross
[settings]
os=Windows
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release

[env]
CONAN_CMAKE_TOOLCHAIN_FILE=/home/per/mingw-w64-x86_64.cmake
CC=x86_64-w64-mingw32-gcc
CXX=x86_64-w64-mingw32-g++
AR=x86_64-w64-mingw32-ar
AS=x86_64-w64-mingw32-as
RANLIB=x86_64-w64-mingw32-ranlib
STRIP=x86_64-w64-mingw32-strip
RC=x86_64-w64-mingw32-windres
CONAN_CMAKE_GENERATOR=MinGW Makefiles
```

```
$ cat /home/per/mingw-w64-x86_64.cmake
set(CMAKE_SYSTEM_NAME Windows)
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

# cross compilers to use for C, C++ and Fortran
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_Fortran_COMPILER ${TOOLCHAIN_PREFIX}-gfortran)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)

# target environment on the build host system
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})

# modify default behavior of FIND_XXX() commands
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Pibben 

Thanks for your question.

Some quick comments:

- You are using ``[env]`` in profiles, then I assume you are talking about Conan 1.X, but please note that ``[env]`` is also considered legacy in Conan 1 and the recommendation is to use ``[buildenv]`` and ``[runenv]`` definitions in profiles.
- the configuration of tools based on env-vars, like ``CONAN_CMAKE_TOOLCHAIN_FILE`` or ``CONAN_CMAKE_GENERATOR`` is also legacy, and it has been superseded by new ``conf`` (also in Conan 1.X) like ``tools.cmake.cmaketoolchin:generator``
- This new ``conf`` also works with the new integrations, like ``CMakeToolchain``, ``MesonToolchain``, not the legacy generators ``cmake``, ``cmake_find_package``


I see in https://stackoverflow.com/questions/78803094/how-to-make-meson-find-my-windres-binary, the approved solution is setting the ``WINDRES`` env-var, because ``MesonToolchain`` uses it. This is correct, but I am a bit confused from your profile above, are you setting it in ``[buildenv]`` section or in ``[env]`` legacy section to make it work?

**Comment by Pibben** [comment]
Thanks for your comments!

As you understand, I'm still in Conan 1. I added the line `WINDRES=i686-w64-mingw32-windres` to the `[env]` section.

**Comment by memsharded** [comment]
> As you understand, I'm still in Conan 1. I added the line WINDRES=i686-w64-mingw32-windres to the [env] section.

Ok, good, this might work for you at the moment, but please take into account the above comments. Conan 1.X is legacy now, and while it will not break, ConanCenter packages will soon stop getting fixes and updates for Conan 1.X, so migration to Conan 2 is important. 

Thanks for the feedback, I think we can close the ticket now if it works, feel free to open new tickets for any further question or issue.
