### ISSUE TITLE
[feature] Think about opt-in for always generating `conan.lock`

### ISSUE THREAD

**Issue by AbrilRBS** [conan-io/conan#16767]
### What is your suggestion?

In conversations with @perseoGI we were exploring the lockfile mechanisim and the idea was raised about having an opt-in for always generating the `conan.lock` file, which might be quite verbose, but was good enough of an idea to at least consider it.

Something like:
```diff
diff --git a/conan/api/subapi/lockfile.py b/conan/api/subapi/lockfile.py
index 1d193bbcd..cb65da8b5 100644
--- a/conan/api/subapi/lockfile.py
+++ b/conan/api/subapi/lockfile.py
@@ -97,8 +97,8 @@ class LockfileAPI:
                         python_requires=python_requires, config_requires=config_requires)
         return lockfile
 
-    @staticmethod
-    def save_lockfile(lockfile, lockfile_out, path=None):
+    def save_lockfile(self, lockfile, lockfile_out, path=None):
+        lockfile_out = lockfile_out or (LOCKFILE if self.conan_api.config.global_conf.get("core.lockfile:autogenerate", default=False, check_type=bool) else None)
         if lockfile_out is not None:
             lockfile_out = make_abs_path(lockfile_out, path)
             lockfile.save(lockfile_out)

```

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
I am interested in the user-stories for this feature request. Specially given that the ``core`` conf should be pre-configured before, something that is more often configured by the organization than individual users, and shared with ``conan config install``.

**Comment by memsharded** [comment]
We have discussed this:

- it is not possible to make it default, it would be breaking
- For consumer side, the case of multi-configuration will be challenging, with ``conan install`` suddenly failing because the automatically generated lockfile is missing some deps for the new configuration, and automatically adding ``--lockfile-partial`` would be breaking too (and risky)
- The user story of implementing an opt-in, via ``conf``, something that devops/build engineers will set via ``global.conf`` for the team, doesn't make much sense, as they control the dependencies in the server side alreday
- Generating a lockfile is always just a ``--lockfile-out`` argument to the command, not a big deal.

I am closing this as unplanned, we can re-consider this default for Conan 3.0. Thanks for the feedback!
