### ISSUE TITLE
[bug] `CMake.variables` doesn't exist despite the docs saying so.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [conan-io/conan#16783]
### Describe the bug

Hello,

I have a recipe that has the following code in `build()` callback:
```python
            cmake = CMake(self)
            cmake.variables["BUILD_TESTING"] = "OFF"
```
that throws the following error:
```bash
AttributeError: 'CMake' object has no attribute 'variables'
```
However, according to the docs: https://docs.conan.io/2/reference/tools/cmake/cmake.html the `CMake` class has such attribute.  Hence, this seems to be either a bug or incorrect documentation.  If the later is the case, then how do I pass CMake definitions (e.g. `-DBUILD_TESTING=OFF` in Conan 2 API?

thanks,

PC

**Comment by czoido** [comment]
Hi @PauloCarvalhoRJ,

Thanks for the question.
The problem is that you are trying to set an attribute that is not from [CMake](https://docs.conan.io/2/reference/tools/cmake/cmake.html) that is the _build helper_ (a wrapper around the cmake executable) but from `CMakeToolchain` that is the one responsible to configure this kind of information. Please check the docs [here](https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html). You can use it in the generate method like this:

```python
def generate(self):
    tc = CMakeToolchain(self)
    tc.variables["MYVAR"] = "MyValue"
    tc.variables.debug["MYCONFIGVAR"] = "MyDebugValue"
    tc.variables.release["MYCONFIGVAR"] = "MyReleaseValue"
    tc.generate()
```

If you want to pass `-D` arguments to CMake use [CMakeToolchain.cache_variables](https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#cache-variables) instead of `CMakeToolchain.variables`:

```python
def generate(self):
    tc = CMakeToolchain(self)
    tc.cache_variables["BUILD_TESTING"] = False
    tc.generate()
```

Hope this helps.

**Comment by PauloCarvalhoRJ** [comment]
Thank you!  That helped me out.
