### ISSUE TITLE
[question] package_id_embed_mode in configure() method

### ISSUE THREAD

**Issue by lstoffer** [conan-io/conan#16786]
### What is your question?

Hi! I have a question regarding the `package_id_embed_mode` attribute.

Would it be possible to set the `package_id_embed_mode` in the `package_id()` method based on certain conditions. And is the `package_id()` method the right place to do it?

Kind regards

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @lstoffer thanks a lot for your question. I'm taking a look at the code, and while it seems like it could possibly be set in the `package_id()` method, my recommendation would be to set in the `configure()` one.

Is there a specific reason to for the `package_id()` usage need?

**Comment by lstoffer** [comment]
Hi @AbrilRBS 
Thanks a lot for your answer. No it does not have to be in the `package_id()` method fpr my use case I think the `configure()` method would also be fine. What I try to do is to set the `package_id_emved_mode` attribute when I call `conan create` dynamically based one the condition if it is a feature package or a stable one that I am trying to crate.

**Comment by lstoffer** [comment]
So what I actually need to know is if `conan install` in a project further up in the stack will call the `configure()` method of the conan package where I want to set `package_id_embed_mode`.

**Comment by memsharded** [comment]
Yes, the ``configure()`` method of every recipe in the graph will be always called when doing a ``conan install`` (or ``conan create`` or ``conan graph info``, ``conan lock create``, etc)

Also the ``package_id()`` will be called for every package in the graph, but I agree with @AbrilRBS here, it makes more sense in ``configure()``, because ``package_id()`` method is designed for the computation of the current package ``package_id``, while ``configure()`` is general for the package, and it also for consumers.

**Comment by lstoffer** [comment]
Thank you very much for your reply!
