### ISSUE TITLE
[bug] Non-zero exit code expected on conan list/search failure

### ISSUE THREAD

**Issue by sharpepd** [conan-io/conan#16794]
### Describe the bug

In Conan 1.x if I run a `conan search` that fails to find the specified package the exit code "1" is returned. If I do the same in Conan 2.x (latest version I checked is 2.6.0), the exit code is 0. I have tested on a windows system.
I would expect a non-zero exit code in the case of failure.

### How to reproduce it

```
(conan2) w:\temp>conan search foo -rconancenter
conancenter
  ERROR: Recipe 'foo' not found

(conan2) w:\temp>echo %ERRORLEVEL%
0
```

**Comment by memsharded** [comment]
Hi @sharpepd 

Thanks for your feedback.

This is not a bug, but by design and intended in Conan 2.

If the ``conan list`` (``conan search`` is basically the same, a simplification of this command) is able to contact the remote, and the remote doesn't contain any package matching that pattern, returns an empty list. But the whole command execution was successful, and not really a failure or error condition. 

In Conan 2 for automation, exit codes != 0 mean something bad happened and execution must be interrupted. For other purposes, the commands provide the  ``--format=json > myoutput.json``, and checking that json file is the recommended approach.

**Comment by sharpepd** [comment]
Ok. I had a feeling that might be the case. I understand the philosophy, but now I need a few more lines in my pipeline :(
I accept this can be closed.
