### ISSUE TITLE
[bug] conan inspect is not showing requirements

### ISSUE THREAD

**Issue by yasslbk** [conan-io/conan#16813]
**[description]**
Running `conan inspect` on a simple `conanfile.py` does not show `requires` field even if it is not empty.

**[env]**
``` 
conan -v
Conan version 2.6.0
```

### How to reproduce it

**conanfile.py**
```
import os
from conan import ConanFile

class MyProjectNameRecipe(ConanFile):
    name = "myproj"
    version = "2.2"
    license = "legal"
    author = "Auth"
    description = "Desc"

    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"
    python_requires = "cmake/[>=1.0.0]"

    def requirements(self):
        self.requires("zlib/1.2.11")

    def build_requirements(self):
        self.tool_requires("cmake/3.22.6")
        self.tool_requires("mingw-builds/12.2.0")
        self.tool_requires("ninja/1.11.1")

    def layout(self):
        self.folders.generators = os.path.join("build", "generators")
        self.folders.build = "build"
```

**Inspect**
```
$ conan inspect .
author: Auth
description: Desc
generators: ['CMakeToolchain', 'CMakeDeps']
label:
languages: []
license: legal
name: myproj
options:
options_definitions:
package_type: None
python_requires:
    cmake/3.26.4#0b40747e190e755932767f2ec4768ff5: {'remote': None, 'recipe': 'Cache', 'path': '/home/yalambar/.conan2/p/cmake866ac203ce714/e'}
requires: []
revision_mode: hash
settings: ['os', 'compiler', 'build_type', 'arch']
vendor: False
version: 2.2
```

**Comment by yasslbk** [comment]
How is the conanfile parsed and which method gives each attribute its value ?
I tried to play around with `_parse_conanfile` but couldn't find how attributes (requirements, author ...) are affected

**Comment by memsharded** [comment]
Hi @YassineLambarki 

Thanks for your feedback.

This is not a bug, this is expected behavior. ``conan inspect`` does not fully evaluate the recipe, it only loads the class and is able to  provide the class members, but not any dynamically computed member. ``requirements()`` is a method that can have conditional requirements, like based on ``settings``, something that ``conan inspect`` does not provide.

If you want to evaluate the full recipe, with profile, etc, you can use the ``conan graph info`` command, and its ``--format=json`` output.

**Comment by yasslbk** [comment]
In such case, why would inspect even print `requires: []` ?

**Comment by memsharded** [comment]
> In such case, why would inspect even print requires: [] ?

Unconditional class attributes requires such as ``requires = "zlib/1.3.1", "..."``
