### ISSUE TITLE
Add optional parameter for destination folder on tools.get()

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#1682]
Currently the implementation looks like this: 
```
def get(url):
    filename = os.path.basename(url)
    download(url, filename)
    unzip(filename)
    os.unlink(filename)
```
It will be fairly simple to add an optional parameter to get() which allows the user to pass in the filename parameter, overriding the derived filename. 

This will make it easier to write generic code in the `build()` method which needs to reference files into the extracted sources.  For example, authors could then just set the filename to the generic name "sources" for most recipes.  Then, when they need to access files and run commands in the extracted directory, they won't have to factor in variables for the package name and version number.  It cuts down a lot of os.path.join().  Also, frustratingly, github url's for archives can be in format v1.2.3 or v.1.2.3., another variable that gets eliminated.

**Comment by lasote** [comment]
I realized that this feature request could be invalid. The "get" method just downloads a file, uncompress it and finally removes it. But it doesn't care the name of the file because it will be removed. The important thing is the name of the folder inside the zip, but could be many folders or just archives inside the zip!

I agree that in the most cases the zip name contains a folder name that matches (or it's similar) to the zip name, but the feature then is different, we would need to detect if the unzipped folder has the same name than the file and rename it? Sounds a little weak and weird. Maybe the user should rename it explicitly in their recipes if it helps with the ugly name.

WDYT?

**Comment by solvingj** [comment]
To put it in perspective, this change isn't a new idea, it simply extends the argument list and behavior for `tools.get()` to be consistent with `tools.download()`, allowing the replacement below:
  
```
        tools.download(url, filename)
        tools.unzip(filename)
        os.unlink(filename)
```
```
        tools.get(url, filename)
```

Indeed, the ultimate goal is for the name of the extracted folder to be controllable to the caller, but the file determines the name of the folder.

**Comment by lasote** [comment]
> but the file determines the name of the folder.

That is not true, take a look at this example:

```
import os
from conans import ConanFile, tools


class LibConan(ConanFile):
    name = "lib"
    version = "1.0"

    def source(self):
	tools.get("https://bintray.com/lasote/Files/download_file?file_path=other%2Fexample.zip")
        print(os.listdir("."))
```

```
$ conan source
```
```
Output: 

PROJECT: Configuring sources in /private/tmp/folder
[==================================================] 188B/188B        
Unzipping 13B
Unzipping 100 %                                                      
 ['conanfile.py', 'conanfile.pyc', 'example.c']
```
There is no subfolder here, because the `example.zip` has no folders inside. The zip with a folder with a same name inside is just a common practice. The file name has nothing to do with the zip contents.

So, actually, in this case, the file was temporally named `file_path=other example.zip` but it doesn't care because it's removed when unzip is completed.

**Comment by solvingj** [comment]
I see, TIL, thanks for looking into it.

**Comment by memsharded** [comment]
I am not sure if we are discussing the same thing. Is this what we are talking about?:

```python
def get(url, md5='', sha1='', sha256='', destination="."):
    """ high level downloader + unzipper + (optional hash checker) + delete temporary zip
    """
    filename = os.path.basename(url)
    download(url, filename)

    ...

    unzip(filename, destination=destination)
    os.unlink(filename)
```

**Comment by solvingj** [comment]
Well, my original goal was to be able to control the final unzipped directory, and i think the conclusion was that even the original `tools.unzip` didn't guarantee this, it only happened to work out that way most of the time due to github convention.  So, the conclusion was that the feature I was requesting didn't work exactly how I would have wanted it to, and I closed the ticket.  But perhaps it still makes sense as a simple feature , even if just for consistency with `tools.unzip`.
