### ISSUE TITLE
[question] How to access `package_folder` in an extension command with settings/profiles

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#16826]
### What is your question?

I'm experimenting with an SBOM generator based on the one in conan-extensions (https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/sbom). I would like to access the `package_folder` for the profiles/settings/options specified on the command line, however the property is `None` in that context.

The command already has all the parameters to specify exactly which package would be used (similar to `conan install`). I'm wondering what makes a `ConanFile` object in a command have access to the `package_folder` and what not. Is there a simple way to achieve this or would that require some extensive changes to the command's implementation?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by jcar87** [comment]
Hi @fschoenm 

I suspect the current sbom custom command is set to simply analyse the graph of dependencies without the specific binary packages.

https://github.com/conan-io/conan/blob/f357f8169c1e4ecf2bee5ca0b5fb723fc36d82b0/conan/cli/commands/graph.py#L227-L229

I think the `deps_graph` will correctly populate the `package_folder` after this, assuming the packages all resolve to an existing package.

**Comment by memsharded** [comment]
Thanks @fschoenm for the question and thanks @jcar87 for the support.

The ``conan_api.graph.analyze_binaries`` does the computation of the ``package_id`` and if they are being built, downloaded, etc. To define the ``package_folder``, that only happens when the packages are "installed", so it will be necessary to call to the ``install_binaries`` api too:

https://github.com/conan-io/conan/blob/f357f8169c1e4ecf2bee5ca0b5fb723fc36d82b0/conan/cli/commands/install.py#L73

**Comment by fschoenm** [comment]
Thank you @jcar87 and @memsharded, that was very helpful and not it seems to be working as I intended :)
