### ISSUE TITLE
[question] How can I set config `conan config set core.upload:parallel 10` in conan v2?

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#16837]
### What is your question?

How can I set config `conan config set core.upload:parallel 10` in conan v2?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by DmitrySokolov** [comment]
It looks like I can use `-cc ` option of a command, right? (to overwrite conf)

**Comment by memsharded** [comment]
Hi @DmitrySokolov 

Thanks for your question.

Profile files and ``global.conf`` files cannot be edited/modified in Conan 2 with commands, because those files are now ``jinja`` templates, that basically do not allow easy round-trip load-modify-save cycles.

As you found, the ``-cc core.xxx`` can be used in command line to overwrite on the fly the values from ``global.conf``

**Comment by DmitrySokolov** [comment]
OK, thanks!
