### ISSUE TITLE
[bug] `conan list -r` do not list packages

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#16832]
### Describe the bug

```
conan list -r itc_server "Qt6/6.5.3-6@itc/stable:*" -f json
{
    "itc_server": {
        "Qt6/6.5.3-6@itc/stable": {
            "revisions": {
                "51d9644837eb05559ec7a5eb8d179713": {
                    "timestamp": 1713300069.195,
                    "packages": {}
                }
            }
        }
    }
}
```
![conan_list](https://github.com/user-attachments/assets/a9065f5b-2b0c-439a-bf1a-994d33b41368)

conan 2.6.0

**Comment by DmitrySokolov** [comment]
Meanwhile, using conan 1.62

```
.\conan search -r itc_server "Qt6/6.5.3-6@itc/stable"
Existing packages for recipe Qt6/6.5.3-6@itc/stable:

Existing recipe in remote 'itc_server':

    Package_ID: 25fc653b78c09168362316598084e26531a7f5d0
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: Visual Studio
            compiler.cppstd: 17
            compiler.runtime: MDd
            compiler.version: 16
            os: Windows
        Outdated from recipe: False

    Package_ID: ...
```

**Comment by AbrilRBS** [comment]
Hi @DmitrySokolov thanks a lot for your report.

This would not be a bug, but expected behaviour. Packages built with Conan 1 are not visible/usable in Conan 2, and vice-versa. So what you're seeing here is that Conan 2 has no packages built for that version/recipe revision, and instead all are built with Conan 1. Note that what _is_ shared between Conan 1 and Conan 2 are _recipe revisions_, those can coexist just fine

I hope this helps, let me know if you have any follow-up questions :)

**Comment by DmitrySokolov** [comment]
OK, thanks!

P.S.
It looks like you step into the same problem as Python 2 / 3
