### ISSUE TITLE
[question] How to deploy several builds of one package (different host profiles) in one deployer?

### ISSUE THREAD

**Issue by irieger** [conan-io/conan#16865]
### What is your question?

Hey,

I'm currently looking for a way to deploy some build artifacts. The project(s) related build some plugins for a software, which are basically shared libs with a specific extension and only link to static libs themselves. So what I'm searching for is basically something like a deployer, but instead of collecting dependencies, I want to collect all artifacts for the current package (meaning all the builds for different platforms) from our Artifactory to pack them together. Is there a way to do this with conan? From the stuff I found about the deployers, I wasn't really finding that this would be possible, but is there a way to do this?

Example rough structure of the packages and where I want to land:
```
project-a [macOS arm64 build]:
    lib/myPlugin.pluginMacA64
project-a [macOS intel build]:
    lib/myPlugin.pluginMacX64
project-a [Linux x64 build]:
    lib/myPlugin.pluginLinuxX64

Resulting deploy:
    whatever-I-want/myPlugin.pluginMacA64
    whatever-I-want/myPlugin.pluginMacX64
    whatever-I-want/myPlugin.pluginLinuxX64
```

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @irieger 

Thanks for your question.

Deployers acts on ``conan install`` which defines a dependency graph for a given configuration. A ``conan install`` receives an effective profile (can be the combination of some files) and install that specific configuration, because the dependency graph is often conditional to the configuration (different settings, options, etc, produce a different dependency graph).

So it is not possible to use deployers on just a single package to deploy all its different binaries, and it would be necessary to do this operation iteratively, one profile at a time.

If you would still like to do this operation in one single command, I think the best would be to do a custom command, see https://docs.conan.io/2/reference/extensions/custom_commands.html. In such a command I would do:
- Call the ``list`` api to get all the different binaries for a given reference, as the ``conan list mypkg/myversion:* -r myremote`` would do
- Download those packages from the server with the ``download`` api (not the install api)
- Get the path to each one with the cache (``conan cache path`` command, `` path = conan_api.cache.package_path(pref)`` api), and do whatever you want (copy them to your location or whatever)

The custom commands is very powerful and convenient, one of the great features of Conan 2. The API is still not fully documented, we are doing it when possible, but difficult to prioritize, the best would be to check the source code, and don't hesitate to ask any further questions as necessary. Thanks!

**Comment by memsharded** [comment]
The API reference is here: https://docs.conan.io/2/reference/extensions/python_api.html

The ``CommandAPI`` is special, it allows to run other commands directly, which can be convenient, you can check the Conan tests, but something like:
```python
@conan_command(group="custom commands")
def mycommand(conan_api, parser, *args, **kwargs):
    """ mycommand help """
    parser.add_argument("remote", help="remote")
    parser.add_argument("url", help="url")
    args = parser.parse_args(*args)
    conan_api.command.run(["remote", "add", args.remote, args.url])
    result = conan_api.command.run(["remote", "list"])
    result = {r.name: r.url for r in result}
    cli_out_write(json.dumps(result, indent=2))
```

**Comment by irieger** [comment]
Thank you very much. Got it working with the mentioned commands like list, download etc.

**Comment by memsharded** [comment]
Happy to hear that and happy to help :)

Don't hesitate to create new tickets for any further question you might have. Thanks for the feedback!
