### ISSUE TITLE
[question] Version range leads to conflict, recipe bug or Conan bug?

### ISSUE THREAD

**Issue by cubanpit** [conan-io/conan#16867]
I have a `conanfile.txt` which requires `zlib` through different flows:

1. `swig/4.1.1` -requires-> `pcre2/10.43` -requires-> `zlib/[>=1.2.11 <2]`
2. `cpython/3.11.9` -requires-> `zlib/[>=1.2.11 <2]`
3. `pkg_a/1.0` -requires-> `zlib/1.2.13`

When installing this conanfile it seems that the range is resolved to `zlib/1.3.1` and then a conflict arises:
```
ERROR: Version conflict: Conflict between zlib/1.2.13 and zlib/1.3.1 in the graph.
Conflict originates from pkg_a/1.0
```

My understanding of version ranges is that they should be resolved to the version which satisfies all requirements, but it does not seem to be happening here.

I attach [conan_error_demo.zip](https://github.com/user-attachments/files/16728569/conan_error_demo.zip) which reproduces the issue.

Environment:
Conan version 2.6.0
Python 3.9.2

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @cubanpit 

Thanks for your question.

Conan dependency resolution is complicated, because it has to take into account many factors, propagating the ``requires`` with their ``traits`` (https://docs.conan.io/2/reference/conanfile/methods/requirements.html#requirement-traits), checking for conflicts based on those traits, etc. Expanding the dependency graph is then relatively quite costly, expanding every node in the graph requires downloading the recipe, unzipping it, loading the files and python-parsing and evaluating them, then evaluating the recipe logic.

As a result, the version-ranges resolution is not a full SAT solver, because that is an NP problem and having to evaluate all the possible hypothesis in the version ranges, multiplied for the recipe-revisions, will make it easy intractable problem. So the algorithm is a greedy simplification, with some provisions to try to handle version ranges and pinned versions in a way to reduce conflicts but not always possible.

The graph is expanded depth-first, that means that requirements that are declared first take priority and are evaluated first. In your case that means that if you put the ``pkg_a`` first in your requirements, that will solve the issue and resolve to the version of zlib that ``pkg_a/1.0`` requires (without needing to use any other version conflict mechanism like ``override`` or ``force``):

```
[requires]
pkg_a/1.0
swig/4.1.1
cpython/3.11.9
```

Please try that and let me know.

Side note: use strings to define versions, like ``version = "1.0"`` better than ``version = 1.0`` which would initially make it a float number.

**Comment by cubanpit** [comment]
Thank you for the clear explanation, it does seem to work as expected when changing the order, at least the version resolution step finishes.
```
======== Computing necessary packages ========
Requirements
    bzip2/1.0.8#457c272f7da34cb9c67456dd217d36c4:1af550ca966a22f3d163e81ebf4db6fa2b06e005 - Missing
    cpython/3.11.9#f8df05195fb5f433c9c86a1702959834:da85a3a72aae24933476f664a3b1d82d16de6e37 - Missing
    expat/2.6.2#2d385d0d50eb5561006a7ff9e356656b:451878afb3f35ea3db67687b36ae7a11cc688dc6 - Missing
    fontconfig/2.13.93#79873ceed529a0b15799beb200a4c313:65bf0560058115f32e6e3d1023ec589a08c75763 - Missing
    freetype/2.13.2#7934d59c447d72edcd56025dc60e1aeb:164fec9c288cf8e277f8868cf554b1805cfd78c5 - Missing
    libffi/3.4.4#72cccac6139293b6e97ec9cd676547ff:fe9e1de4159fa660fa3e039f788e44f2ca185dab - Missing
    libpng/1.6.43#c219d8f01983bac10c404fc613605eef:c2b577331b5065df2ed00ee5fc207cb3f17557c1 - Missing
    mpdecimal/2.5.1#5ea215d2c261afaa9a739fb74fd1f338:7c3aacf3f688e7b680581ec74bb5086abaac5d83 - Missing
    ncurses/6.4#78908f3ed548f188cf15e415f8949f2f:c0c5df4aadc513e59a3bbac2306079c2bb1e0d86 - Missing
    openssl/3.3.1#279e86dc2a7dded8c1fe8512e775bdb1:cea5477bc37c2a2bc9a2320c4a9ad31ec73989ba - Missing
    pcre2/10.43#0780a1a0085fff3e494b2c222c0b7a9a:01447e398802c1f6bf651b0fffc045b983530c7c - Missing
    pkg_a/1.0#5ce080de2f2adc57ebf27e64a1f2df1c:d6e461c6f8d74e6acaac8d02c4eca3982ce141f8 - Missing
    sqlite3/3.45.2#60f2d3278e7bc12c8ef02ac75119c137:629ddf0030ab150ffa6bc3cd0603d52bbf889c09 - Missing
    swig/4.1.1#07c7c263cc895d5c0065273fae2b9c40:c61cf82a2235c150958bf6b3cf2bc08b162d7193 - Missing
    tcl/8.6.10#d694cc97f48640f0d66aa90b16cdc5cd:8994e0760231c7807af907b1bf4ed0fe2ef75d66 - Missing
    tk/8.6.10#1e8cbe0b5d8257de6bc6904da048766f:f38acd18786418a52d219b7f707e37f1b4cd6834 - Missing
    util-linux-libuuid/2.39.2#339f80aea7e5cf507b5b9839a128909f:fe9e1de4159fa660fa3e039f788e44f2ca185dab - Missing
    xorg/system#f626cbdd0ba57d9c53bce2d8b9362fad:da39a3ee5e6b4b0d3255bfef95601890afd80709#0ba8627bd47edc3a501e8f0eb9a79e5e - Download (conancenter)
    xz_utils/5.4.5#b885d1d79c9d30cff3803f7f551dbe66:fe9e1de4159fa660fa3e039f788e44f2ca185dab - Missing
    zlib/1.2.13#4e74ebf1361fe6fb60326f473f276eb5:e6fa39dce7f4ca6a97326d1949a5dc5c06683e43 - Missing
```
I cannot find this information in the docs, I think it would fit nicely inside (or linked in) the documentation about version ranges, because other users might have similar expectations.
Thanks for the tip about the version as well, I do not usually hard-code versions in recipes so I did not think much about it.

**Comment by memsharded** [comment]
> I cannot find this information in the docs, I think it would fit nicely inside (or linked in) the documentation about version ranges, because other users might have similar expectations.

You are right, thanks for the suggestion. Adding this info in the docs in https://github.com/conan-io/docs/pull/3817 as FAQ, and also linked from the version conflicts tutorial section.
