### ISSUE TITLE
[bug] configure_options_settings tutorial doesn't work as expected

### ISSUE THREAD

**Issue by Longosz** [conan-io/conan#16881]
### Describe the bug

Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows

### How to reproduce it

Hi!

when executing:
conan create . --build=missing -o shared=True -o fPIC=True -tf=""
from https://docs.conan.io/2/tutorial/creating_packages/configure_options_settings.html 

instead of getting:
![image](https://github.com/user-attachments/assets/c8ac6827-e2f3-451f-b0d1-490e81082d68)

I have:
![image](https://github.com/user-attachments/assets/9411f9a9-1b69-4ea0-9caf-e16d4ba60238)

also I found a small discrepancy in 'configure' methods between the repo (https://github.com/conan-io/examples2/blob/main/tutorial/creating_packages/configure_options_settings/conanfile.py) and what is published in your tutorial (https://docs.conan.io/2/tutorial/creating_packages/configure_options_settings.html).

REPO:
```
    def configure(self):
        if self.options.shared:
            del self.options.fPIC
```

TUTORIAL:
```
    def configure(self):
        if self.options.shared:
            # If os=Windows, fPIC will have been removed in config_options()
            # use rm_safe to avoid double delete errors
            self.options.rm_safe("fPIC")

```
Regards,
Longosz

**Comment by ErniGH** [comment]
Hello @Longosz , first of all, thank you very much for reporting the error.

Two things are happening here. 
Firstly, our example is not up-to-date, and it should indeed be `self.options.rm_safe("fPIC")` to prevent an error when trying to remove the "fPIC" option twice: once because it's Windows, and another because the "shared=True" option is set.

Secondly, the documentation currently shows only one command, but it should differentiate between Linux and Windows. In Windows, the `-o fPIC=True` part should be excluded because it is not a valid option there.

In your case, the command would look like: `conan create . --build=missing -o shared=True -tf=""`.

We are currently updating the documentation and examples to fix these errors.
I hope this clears up your doubts. ❤️

**Comment by Longosz** [comment]
Hi @ErniGH ,

Thank you for quick reply and explanation, I will confirm tomorrow morning that it's working correct on my end but I'm sure we can close this ticket already:)

Regards,
Longosz
