### ISSUE TITLE
[bug] when running conan install --deploy it always deploy the generators, how to remove that?

### ISSUE THREAD

**Issue by hpe-ykoehler** [conan-io/conan#16887]
### Describe the bug

Even if I write my own deployer script, a "build/" folder is always generated by conan which contains the generators.

But, I do not want those, as my goal is not to provide the deployed file to another developer to work on the package but to install the deployed files on a system or docker image

How can I tell conan install --deploy not to export the generator?

**Comment by memsharded** [comment]
Thanks for your question @hpe-ykoehler 

The ``build`` folder is not a product of the ``--deployer``, this is the default behavior when generators are declared, which they are in the recipe. If you don't want them, maybe remove them from the recipe?

If we are talking about the automatic "VirtualBuildEnv" and "VirtualRunEnv" generators, which are the only ones that are implicit, there is already some ongoing work in https://github.com/conan-io/conan/pull/16863 to define a ``conf`` that will inhibit the creation of these files if the user prefers not to have them.

**Comment by hpe-ykoehler** [comment]
I may need the generator to build my recipe but I may not need them to deploy the package, not sure what you mean here.  If I remove them from the recipe, it will not work anymore.

(I am not a Conan expert here)

Those files are not part of my "package" instruction or "package_info" so I am not sure why they are produced in the --deploy-folder which seems explicit that it should only relate to deployer-related files, yet my deployer script is not copying them, so Conan decided to use the deploy-folder to store non-deployer script generated files, that to me is a bug.

my deployer is a copy of the Conan runtime deployer function with an additional call to strip debug symbols out of those runtimes.

Note also that many packages I used are not mine, some come from conan-center-index, so I cannot go and change their content to remove generators.

**Comment by hpe-ykoehler** [comment]
I was trying to repro and I cannot... once I do I will re-open with the content of the build folder.

**Comment by memsharded** [comment]
> I may need the generator to build my recipe but I may not need them to deploy the package, not sure what you mean here. If I remove them from the recipe, it will not work anymore.

Sure, and ``conan install`` must generate those generators files, because they are needed to build the ``app`` binaries in the first place. So they cannot be omitted from the ``conan install``

> Those files are not part of my "package" instruction or "package_info" so I am not sure why they are produced in the --deploy-folder which seems explicit that it should only relate to deployer-related files, yet my deployer script is not copying them, so Conan decided to use the deploy-folder to store non-deployer script generated files, that to me is a bug.

``conan install --requires=app/1.0`` will not create any generators files, except the ``conanbuild/conanrun`` environment scripts, and those are the ones that https://github.com/conan-io/conan/pull/16863 will allow to opt-out. 

> Note also that many packages I used are not mine, some come from conan-center-index, so I cannot go and change their content to remove generators.

No need to remove generators from the dependencies at all. Only from the consumer ``conanfile.py``, if you are not really building it, but as said before, if I understood it correctly, you can't because the binaries for ``app`` haven't been built yet.

So overall I think this is not a bug, but still some misunderstanding of what is a "consumer" conanfile.py (the one referenced with ``conan install .``, and what is a real package (the one referenced with ``--requires=pkg/version``). If you are using the ``conan install .`` that is not a package, it really needs to create the generators files, the build folder, everything because it needs to build the binaries, which don't exist yet, and this ``conan install .`` cannot deploy the binaries of the consumer ``conanfile.py`` because those binaries do not exist yet.

**Comment by hpe-ykoehler** [comment]
When I run conan build . and then conan install . the binaries do exists... also somehow we run cmake install so they not only exists but are avail in a form that is accessible to be deployed somewhere.

Like if I compile from scratch a program after make install the program is installed on my system.  Same for cmake install no?

What would be the way to deploy a developer build if we cannot use conan install . ?

**Comment by hpe-ykoehler** [comment]
also, if the generator are require for build, can't they be installed in the build folder instead of the deployer-folder ?

**Comment by memsharded** [comment]
> When I run conan build . and then conan install . the binaries do exists...

It is just accidental, they exist because a ``conan install`` was called first followed by a ``build()``. But commands should be invariants, and not rely that much on state. The ``conan install <path> --deployer`` command over a path should do the same the first time it is called and the second and third time, even if something called locally. 

> Like if I compile from scratch a program after make install the program is installed on my system. Same for cmake install no?

That is the thing, nobody is calling ``cmake.install()`` here, because it belongs to the ``package()`` method, and that is not called in any place in this flow (moving it to the ``build()`` method is a hack, not a solution). 

> What would be the way to deploy a developer build if we cannot use conan install . ?

You have the files just there, that is your local folder, you can do whatever you want with those files. ``graph.root.conanfile.build_folder`` gives access to the build folder from the ``deploy()`` deployer code if you want to. 

As suggested, the ``editable`` would also be a way, the fact that ConanCenter recipes do not implement ``layout()`` to support editable is a different thing, but also, it is not expected to be deploying things from ConanCenter from local builds, from paths, because there are packages, so deploying them would be recommended always from ``conan install --requires=pkg/version --deployer=xxx`` not from a local build from the ``conan-center-index`` fork.

**Comment by hpe-ykoehler** [comment]
> You have the files just there, that is your local folder, you can do whatever you want with those files. graph.root.conanfile.build_folder gives access to the build folder from the deploy() deployer code if you want to.

Yes, the files are there but the issue is that if I use the file from the build folder the script then has to be specific to the recipe, and it kind of repeat the logic from the package function.

Where as if I re-use the code from the package, the files will be installed to common locations such as /bin, /lib and any custom code a recipe require to execute during package to make that happen will be re-used.

That is the reason I want to re-use this, it feels inefficient to re-do the package() logic in the context of deploying the same recipe but locally from the build folder.

I would prefer to run the package function but within a given folder and use it from there, for example I think there is a command call conan export-pkg but such function doesn't support the deployer...

I think the "conan install" function is badly name and is quite misleading, it mostly "import" package into the local conan db, it doesn't install anything that can be used outside of conan, I would recommend

- conan install be renamed conan import
- conan install (or import) be remove of the functionality of deployer)
- a real conan install command be created which really install package to something (kind of forcing the use of deployer, similar to how apt install would install stuff)

then conan install could have support for local build since its usage would always be at the end and not intended to be run before conan build (as conan import would).

it would also be a nice counter-part to conan export

it feels to me that conan install is having two roles that do not apply at the same stage, conan install will install package to conan db for being consume by your recipe and can also deploy, but then only for recipe already installed in the db, which I really think should be a different command, as the first one must be done before the build stage and the next one can only be done after the build stage.

I think this is why I am so confuse about conan behavior, other system do better at this level and are more intuitive (there are no confusing "install" command that can only works certain way, they always works only as the last stage of "any" recipe)

I see also conan try to follow a lot of similarities from python, and in python, but kind it seems this idea / similarities was only thought of for libraries.  If I install an app with python, after pip install I can use the app on my system.  With conan, if I install a package, I can link with it, but if it is a binary, I still cannot use it on my system.  Adjusting PATH= to point to some random .conan2/p folder make no sense.  In that way, I think the conan install is really not working as one would expect an "install" command to work.

**Comment by memsharded** [comment]
> I would prefer to run the package function but within a given folder and use it from there, for example I think there is a command call conan export-pkg but such function doesn't support the deployer...

Yes, the flow would be:
- ``conan build .``
- ``conan export-pkg ...``
- ``conan install --requires=myapp/myversion --deployer``


> I think the "conan install" function is badly name and is quite misleading, it mostly "import" package into the local conan db, it doesn't install anything that can be used outside of conan, I would recommend

This is not correct. The ``conan install`` just install dependencies. It doesn't import anything into the ConanDB. It will install dependencies, either from a local ``conanfile.txt`` or from a direct ``--requires``.
This command is almost identical to many other package managers, for example:

```bash
# installing pkg/version and its dependencies
pip install pkg==version
# installing the dependencies declared in file
pip install -r requirements.txt
```

This is the same, it install dependencies, it doesn't import anything.

> conan install be renamed conan import

I am sorry, but no way this will happen, this will break all Conan users in the world

> a real conan install command be created which really install package to something (kind of forcing the use of deployer, similar to how apt install would install stuff)

And how would that work with a ``conanfile.txt`` that doesn't build or package or anything? That would be impossible.

> I see also conan try to follow a lot of similarities from python, and in python, but kind it seems this idea / similarities was only thought of for libraries. If I install an app with python, after pip install I can use the app on my system. With conan, if I install a package, I can link with it, but if it is a binary, I still cannot use it on my system. Adjusting PATH= to point to some random .conan2/p folder make no sense. In that way, I think the conan install is really not working as one would expect an "install" command to work.

I think this is not accurate. The above:

``` bash
# installing pkg/version by name and its dependencies
pip install pkg==version
# installing the dependencies declared in file by path
pip install -r requirements.txt
```

Does not do absolutely anything with the current project. They don't build the current project, they don't deploy or make available or install the current project. There might not even be a current project, just an empty ``requirements.txt`` with no Python code. They just install dependencies of the current project. Exactly the same as ``conan install``, that can install dependencies from a ``conanfile`` but that doesn't even require that there is C++ code or a build script in the current project.
The way Conan works with ``conan install <path-to-conanfile>`` is identical to ``pip install -r <path-to-requirements.txt>``.
