### ISSUE TITLE
[bug] Generated file locations not consistent

### ISSUE THREAD

**Issue by rollebolle** [conan-io/conan#16922]
### Describe the bug

Conan 2.7.0, Linux

The files generated with the conan install commando is not consistent depending on command line args and location of the conan files.

### How to reproduce it

Example 1:
Given a source code tree in ., containing a conanfile.py and a CMakeLists.txt

```
mkdir build && cd build
conan install ..
```
When conanfile.py is in same dir as the `CMakeLists.txt`, the resulting structure is a `CMakeUserPresets.json` in the source folder, and a Release map in the `build `folder This is a result I would expect and that works the best.

Example 2:
```
mkdir conan && mv conanfile.py conan
mkdir build && cd build
conan install ../conan
```
Now there is no `CMakeUserPresets.json` and the Release folder ends upp in the conan map (unexpected!) build folder empty.

Example 3

```
mkdir conan && mv conanfile.py conan
mkdir build
conan install conan -of build
```

Now we get the files under `build/build`, and no CMakeUserPresets.json. With the of option there seem to be no way to strip the default "build" part. Probably not what people expect.

We are dependent on CMakeUserPresets.json to be generated to make the integration smooth. Also it would be nice to set the output path without having a hardcoded "build" element in it. 

Especially important, I would expect the first and second example to generate files in the exact same places.

**Comment by memsharded** [comment]
Hi @rollebolle 

Thanks for your report.
This depends on 2 things:
- the ``layout`` declared in the ``conanfile``.
- The ``CMakeUserPresets.json`` can only be generated besides the root ``CMakeLists.txt``. If it is not possible to identify this root CMakeLists.txt, then no file will be generated, because this file is pointless in other folder, as CMake will only read it if it is located besides the root ``CMakeLists.txt``. With the right ``layout``, I think it should be possible to identify this, irrespective of the ``cwd``


Can you please clarify what is your full conanfile.py, with its ``layout()``? Thanks.

**Comment by rollebolle** [comment]
Contents of conanfile.py:

```
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMakeDeps, CMake, cmake_layout


class InventoryConan(ConanFile):
    settings = "os", "arch", "compiler", "build_type"
    tool_requires = "exe2/0.1"

    def layout(self):
        cmake_layout(self)

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()
        deps = CMakeDeps(self)
        deps.build_context_activated = ["exe2"]
        deps.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

The problematic thing with having no CMakeUserPresets.json is that there is no way I found to run cmake and specify the --preset option in another directory than the root `CMakeLists.txt`. This makes the generated `CMakePresets.json` in the `generators` folder unusable (again, at least from what I found).

**Comment by memsharded** [comment]
Thanks for the feedback.

If the ``conanfile.py`` is not located in the root of the repo together with the ``CMakeLists.txt``, that is a different layout that must be specified with ``self.folders.root = ".."``, see https://docs.conan.io/2/reference/conanfile/methods/layout.html

> The problematic thing with having no CMakeUserPresets.json is that there is no way I found to run cmake and specify the --preset option in another directory than the root CMakeLists.txt. This makes the generated CMakePresets.json in the generators folder unusable (again, at least from what I found).

With ``self.folders.root``, Conan will know the location of ``CMakeLists.txt`` and will generate the ``CMakeUserPresets.json``

> Now we get the files under build/build, and no CMakeUserPresets.json. With the of option there seem to be no way to strip the default "build" part. Probably not what people expect.

There is the ``tools.cmake.cmake_layout:build_folder`` configuration that allows a full override of that ``build`` folder, this seems what you are looking for.

**Comment by rollebolle** [comment]
Thanks. The usecase we have is many different "modules" that should be buildable by themselves (each with their own root CMakeLists.txt). Then we also have a number of conanfiles in another location - for example we have different conanfiles for building for target and another for building for an emulator (host). Therefore, the conanfile and source code are **completely decoupled**, which is also what we want.

For example, module C should be buildable with conanfile A,B,C and D, etc. And the location of the modules are free - we simply want to point to a Conanfile to use during each build scenario, and the conanfile should not have to know anything about the source location. Is there any way to achieve this now?

**Comment by memsharded** [comment]
> Thanks. The usecase we have is many different "modules" that should be buildable by themselves (each with their own root CMakeLists.txt). Then we also have a number of conanfiles in another location - for example we have different conanfiles for building for target and another for building for an emulator (host). Therefore, the conanfile and source code are completely decoupled, which is also what we want.

But they are not decoupled, they are very coupled, the ``conanfile.py`` contains instructions how to build and package some sources. That ``conanfile.py`` can be located in the sources tree, in that sense, its relative position to the root ``CMakeLists.txt`` is fixed and should be defined in ``layout()``. Or it can be located in a different repo, and treat sources as third-party, downloading the sources in the ``source()`` method, but that is an approach that works for third-party, not first-party code development.

> For example, module C should be buildable with conanfile A,B,C and D, etc. And the location of the modules are free - we simply want to point to a Conanfile to use during each build scenario, and the conanfile should not have to know anything about the source location. Is there any way to achieve this now?

I am afraid that I don't understand the setup. I am not sure what "module C" means, or what does it mean to have such a module buildable with different conanfiles, does "conanfile C" has any relation with "module C"?

By definition it is impossible that a conanfile does not know anything about the source location, if you want to be able to create packages, the conanfile must perfectly know which sources it is packaging, not only that, but also have a 1:1 relation with the sources uniqueness, like a git commit sha. Are you talking only about "consuming" conanfiles just to install dependencies?


Most likely I am not understanding the project setup, but I'd say that maybe there are some things that are not clear:

> for example we have different conanfiles for building for target and another for building for an emulator (host).

Why? You can perfectly use the same conanfile to build for different platforms (emulator, real targets, etc). This is the actual recommended approach, Conan manages the different binaries for different platforms automatically. If the "app" is the same, then 1 conanfile for such app will be the way to go, even if the app works in different platforms, architectures, OSs, emulators, or the like. 

If the app is really not the same app, but very different applications, you can still have them as ``conanfile_app.py``, ``conanfile_target.py`` etc. in the same source tree, and if they are in a subfolder, with the ``self.folders.root = ".."``

Or if you want Conan to just install the dependencies, then a simple ``conanfile.txt`` with the ``[requires]`` section and then using the ``--output-folder`` argument will be enough, but then, it has to be ran in the right folder so ``CMakeLists.txt`` is found. But Conan needs to be aware of the source location to be able to generate the ``CMakeUserPresets.json`` in the right place, as commented this is a CMake limitation, such file cannot be generated in another location different than the root ``CMakeLists.txt`` folder, otherwise it doesn't work, there is nothing Conan can do about it.

So you can keep your ``conanfiles`` and the source code completely decoupled if it is what you want, but if Conan is not aware of the location of the source code, then it will not be able to create the ``CMakeUserPresets.json``. Not sure what I could be missing

> The problematic thing with having no CMakeUserPresets.json is that there is no way I found to run cmake and specify the --preset option in another directory than the root CMakeLists.txt.

Just to make sure this is clear, this is not a Conan limitation, this is a CMake limitation, there is no way CMakeUserPresets.json works if it is not located besides the root CMakeLists.txt. So Conan will only generate it if it knows about such CMakeLists.txt, and for that if has to encode the correct ``layout()``, possible with ``self.folders.root=".."``.

**Comment by rollebolle** [comment]
Sorry for being unclear. And before I answer I want to point out that there are ways to work around the issues Im having, but it requires some restructuring.

I am indeed talking about only the consuming scenario. I understand that in the producing case Conan must be aware about the structure. In the consuming case I don't see same need. I realize (more or less) how `CMakePreset` works - so my question is more why whe need to use CMakePresets at all, as we didn't have to use it before. Because it does create a harder coupling to the source code tree.

I also think my rambling about different conan files etc in the last reply added more confusion. Let's condens the problem it to a extremely simple scenario I want to acheive:

I have a `conanfile.txt` somewhere. Given this conanfile, I want to generate a folder with all needed files to build an application with `CMake`, _regardless of the application_. Imagine that I don't even know, at the `conan install` command time, which app is going to use it. This was very easy before but it is not any longer. From what I understand, what has in reality been added is a harder requirement to have the conanfile in the same place as the source code (at least in the CMake case).

I totally understand if this is not possible now, and maybe its for good reasons. In that case I need to find another approach to the problem.

**Comment by memsharded** [comment]
> so my question is more why whe need to use CMakePresets at all, as we didn't have to use it before. Because it does create a harder coupling to the source code tree.

Oh, sorry, I didn't understand that. You definitely don't need to use presets at all. Presets are an optional feature for users using modern CMake>3.23. But Conan works with CMake 3.15, and the majority of our docs uses the syntax without presets, using the toolchain file, so something like:

````
cmake <path> -DCMAKE_TOOLCHAIN_FILE=<path/to/>conan_toolchain.cmake ...
````

With this there will be no coupling between the conanfiles and the sources, because you can fully control the output with ``--output-folder``.

> I totally understand if this is not possible now, and maybe its for good reasons. In that case I need to find another approach to the problem.

Yes, it should be fairly easy if not using presets, which is optional.
There are also different ways to customize the location of generated files to be fully consistent:
- Using ``--output-folder``, when no ``layout`` is defined at all
- When using ``layout()`` and something like ``cmake_layout`` you can use ``--output-folder``, but also the new conf ``tools.cmake.cmake_layout:build_folder`` can overwrite the base ``cmake_layout`` folder and point to the folder of your convenience.

Please let me know if this helps.

**Comment by rollebolle** [comment]
Thanks, I can now generate what I want

**Comment by memsharded** [comment]
Sounds good, then I am closing this ticket as solved question.
Thanks very much for your feedback!
