### ISSUE TITLE
Modify settings.yml at runtime

### ISSUE THREAD

**Issue by oblique** [conan-io/conan#1692]
After the #1684 question, I added `os.glibc` and `os.libstdcpp` in my `settings.yml`.
I would like to hide this step from the rest of my colleagues if possible, but I couldn't find a way to modify `settings` of `ClientCache` on runtime or just reload `settings.yml`.

Is there any way? Or I should introduce them the extra step?

**Comment by lasote** [comment]
Currently there is no way to do it. In our roadmap, there is a feature to distribute common configuration files like the settings.yml, but not implemented yet.

**Comment by himikof** [comment]
This is related to #1463.

**Comment by lasote** [comment]
Alter settings.yml file at runtime looks complex because of the nested format. 
We were thinking about the possibility of getting the custom settings.yml from a remote URL, that could be specified in the conan.conf file (or maybe in another file or env var2 to also get the conan.conf?). So, in CI you could do something similar to:

`conan config set general.config_url=http://user:pass@url`

Then conan could get a custom settings (and other configs). This could be useful for organizations that want to share some config files like the settings. 
Could it work for you @himikof @oblique? Please give us feedback.

**Comment by oblique** [comment]
Yes this works for me.

**Comment by memsharded** [comment]
I think modifying the settings shouldn't be extremely difficult, because the model might support it.

However I agree that the use case of "syncing" settings (not only settings, also remotes, maybe profiles, etc) with some upstream source, is much more demanded. Lets try to address this first, and if still necessary the hot-definition of settings, we could go for it.

**Comment by memsharded** [comment]
Hi @oblique 

Please check the proposal for ``conan config install`` at https://github.com/conan-io/conan/pull/1705

This wouldn't be a field by field modification of settings.yml, but a whole definition of it, from a remote. We think this could be more maintainable and robust. What do you think?

**Comment by memsharded** [comment]
I am tentatively going to label this as fixed, #1705 will be released in 0.27. If it doesn't solve the issue, we can follow up later.

**Comment by memsharded** [comment]
``conan config install`` has been released in 0.27: http://docs.conan.io/en/latest/reference/commands/config.html#conan-config-install

Please try it, and give feedback, re-open or comment if necessary.

**Comment by johnmcfarlane** [comment]
Hi @memsharded 

That link isn't working for me. I'm guessing it pulls down a fully-formed settings.yml. That's not much help to me.

[Once again](https://github.com/conan-io/conan/issues/6910) I'm in the situation where I cannot use new or pre-released compiler versions easily because they are missing from settings.yml. I want to see gcc 11 and clang 12 appear just as soon as gcc 10 and clang 11 are released, because that is what those compilers will self-identify as at HEAD. The result is that I'm am impeded from testing my library with very latest compilers and I see no simple fix: it involves editing settings.yml.

I'm not the slightest bit interested in binary compatibility or generating binary packages, so I am disadvantaged for reasons expressed in [this discussion](https://github.com/conan-io/conan/issues/7223). 

Assuming my problem is not going to go away, I'd like to 'hack' the existing settings.yml in my CI script or Dockerfile. Three possibilities...

## 1. Directly make the edit via a conan command

e.g.:

```bash
conan settings append compiler.gcc.version 11
conan settings append compiler.clang.version 12
```

## 2. Tell conan to accept what is sees as truth

Given:

```bash
$ c++ --version
c++ (GCC) 11.0.0 20201019 (experimental)
Copyright © 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

provide a command which updates settings.yml with this information. Rather than implying that the compiler version is wrong, accept that the Conan settings are outdated and fix those automatically.

## 3. (In case Conan fixes are not acceptable)

Recommend users locate a YAML command-line manipulation utility that will do the insertion in a somewhat more brittle way.

Thanks!
John

**Comment by memsharded** [comment]
Hi @johnmcfarlane 

I am trying to put a Proof of Concept of the ``conan config settings append`` command in https://github.com/memsharded/conan/pull/new/poc/config_settings. I have hit a blocker in the yaml format. The Yaml library that we are using, which is the mainstream one for Python projects, do not support round-trip editing, so something as simple as appending a value will completely the format of the file (removing comments, changing lists for items, indent, flow...). This is  unaceptable, if we want to continue in this line, we would need to consider alternatives like https://yaml.readthedocs.io/en/latest/overview.html (ruamel.yaml), but switching third parties is also a risk. I will re-open this and discuss with the team to see what can be done, possible alternatives:
- Implement our own dumper in ``Settings`` class
- Switch to ``ruamel.yaml``.

In any case, I would also like to understand better why the ``conan config install`` is not a viable alternative, many users are relying on that, seems to work well. It could be as easy as copying the ``settings.yml``, and putting it (modified) in a gist. This works well for example (I have already updated the gist to contain the newer versions, you can try the line as-is):

```bash
$ conan config install https://gist.github.com/b3e851895ce33727666f81b7f0d6e761.git
```
And you have 1 single line command with the following advantages:
- It works well in all your CI and Dockerfiles
- Only 1 line to do as many changes to the Settings.yml as you want (clang, gcc)
- You don't need to update your CI scripts or Dockerfiles when new compiler versions are released, just modify the repo/gist settings.yml, all CI will pull from it
- The ``conan config install`` can also serve for many other purposes, lets say that at some point you need to configure your own remote, different to ConanCenter. Or need to provide some environment variables, or do more complex builds, like cross-build, something that needs profiles beyond the automatically detected one.

**Comment by johnmcfarlane** [comment]
@memsharded thanks for looking into option 1). I may well use your gist line as the current quickest solution. 

To answer your question, assuming [this description](https://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install), it effectively copies the whole file over. I did consider adding a `cp` line to my Dockerfile to achieve much the same result, but I was concerned about what happens if Conan's default _settings.yml_ changes with a fix, enhancement or format change. Then this older version would be regressive or breaking. It seems that either the configuration format is difficult for you to change or I need to peg my version of conan in the `pip3` command.

The trouble you describe with your YAML library sounds like the kind of thing where -- if it is risky work to replace it then -- it might only be worth proceeding once there are a number of low-priority issues depending on ruamel.yaml. However, it's helpful that you identified this library. In the case I pursue option 3) I may use it to perform the insertion.

But on reflection, 2) seems like the most robust avenue of exploration. It doesn't involve fiddling with configuration files and it tackles the root of the problem: sub-setting profiles to `compiler.X.version` is an problematic constraint. Yes, that list is good for deciding what it is practical to build and upload to Bintray. It is helpful for users to choose from a safe set of versions. But using it to limit functionality ...?

I appreciate that this constraint may be integral to Conan (in many ways of which I am blissfully unaware). I appreciate it may be far beyond the realms of the possible to lift it. But from my point of view, it is the gate I would wish to walk through.

Perhaps there could be a `system`, `default` or `unspecified` entry with 'magical' properties:

```yaml
    clang:
        version: ["3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "4.0",
                  "5.0", "6.0", "7.0", "7.1",
                  "8", "9", "10", "11", "system"]
```

Perhaps it would be safer to make it a hidden, implicit element so that users don't think it is a wise choice. Either way it could be chosen:

```cfg
[settings]
...
compiler=clang
compiler.version=system
...
```

And this would correspond to whatever `clang` and `clang++` are/do. Or maybe no such mechanism is needed. Maybe it can just be accepted that sometimes the value in the profile is not in the list from _settings.yml_. Perhaps this would be accompanied by a warning or some other mechanism which protected against accidental error or breaking backward compatibility.

Either way, I'd be interested to know exactly what catastrophe I am unwittingly proposing or whether this is simply a difference between the way build-from-source and download-from-binary developers operate.

**Comment by johnmcfarlane** [comment]
Hi! Hope you're well. One last thought. (I just hit this again because Clang-12 came out!)

What about:

```sh
conan profile update --force settings.compiler.version=12 default
```

?

**Comment by memsharded** [comment]
Conan 2.0 learned a new ``settings_user.yml`` to be able to provide user custom settings (additions only). 
This file can also be managed with ``conan config install``. Closing this issue as addressed by it.
