### ISSUE TITLE
[question] Superproject setup

### ISSUE THREAD

**Issue by arturngomes** [conan-io/conan#16933]
### What is your question?

Hi,

Sorry if this question has been asked already in another place but I've been trying to find it but having trouble getting to where I want.
I've found this https://github.com/conan-io/conan/issues/11067 but still having trouble making it to work the way I want. 

This is ideally what I would like to achieve:

1. Have a CMakeLists.txt that builds the whole project
2. Have multiple subprojects that each one has a CMakeLists.txt
3. One single conanfile.txt in the project root which installs are the required dependencies.
4. Be able to create for each subproject it's own build folder and use use cmake to configure it while being able to use the root conanfile.

Essentially the project structure would be something like this:
```bash
.
│   CMakeLists.txt
│   conanfile.txt
│
├───client
│       client.cpp
│       CMakeLists.txt
│       CMakeUserPresets.json
│       helloworld.proto
│
└───server
        CMakeLists.txt
        helloworld.proto
        server.cpp
```

Here's an example of the project setup:
[test.zip](https://github.com/user-attachments/files/16871130/test.zip)

The dependencies are the same for all the subprojects.

What I can do:

```bash 
cd <project_root>
conan install . --output-folder=build --build=missing
cd build
cmake --preset conan-release ..
make -j
```

What I want to be able to do:
```bash 
cd <project_root>
conan install . --output-folder=build --build=missing
mkdir -p client/build
cd client/build
cmake --preset conan-release ..
make -j
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Couple of quick comments and recommendations:

- Hardcoding ``set(CMAKE_BUILD_TYPE Release)`` in ``CMakeLists.txt`` is not a good practice. This is an input parameter when necessary, shouldn't be defined from CMakeLists
- This ``target_include_directories(client PUBLIC ${protobuf_INCLUDE_DIRS} ${absl_INCLUDE_DIRS} ${gRPC_INCLUDE_DIRS})`` isn't necessary. The include directories are already defined by the targets, using ``target_link_libraries()`` is enough to find the include headers from dependencies.


> What I want to be able to do:

I am not sure if this is a Conan question at all, but a CMake one
It seems you are just missing an extra ``..``, so:
```
cmake --preset conan-release ../..
```
instead of ``cmake --preset conan-release ..``, because you went down 2 levels

**Comment by arturngomes** [comment]
Thanks for the recommendations.

Without conan I would sometimes simply use cmake to configure the project I'm working on without having to configure the whole project. Which can be useful if you have a massive project with more than 20 subprojects for example and there are some tasks that might take extra time.

Is there a way to do that? Or would I have to have a conanfile for each of the subprojects in that case?

**Comment by memsharded** [comment]
> Is there a way to do that? Or would I have to have a conanfile for each of the subprojects in that case?

Not really, you can have a conanfile for each subproject, but then that means that different subprojects can have different dependencies, or depend on different versions of the same package, even if you don't want that, but it would be the user responsibility to align the versions of the different subprojects. And then they become first-level projects (but if I understood correctly this is what you are doing already, configuring and building sub-projects without the super project?). If there are inter-dependencies between the subprojects this would be very challenging.

Basically, adding a conanfile.txt for each subfolder defines different dependencies, different ``conan install`` for each subfolder, with potentially conflicting dependencies and even different configurations (different toolchain files). Moving the ``conanfile.txt`` to a ``conanfile.py`` means that each subproject could be released as an independent package (even with its own and different version to other packages).

This is a tension between mono-repo development approach and package-based development approach. Having both at the same time (one mono-repo, with multiple subprojects, but also expecting every subproject to be an independent package) is quite incompatible, at least with the current technology.

This is more or less what the "workspace" feature, planned for 2.X roadmap (see https://github.com/conan-io/conan/issues/15992) intends to investigate and try to improve. Still quite challenging, because the way CMake models the dependencies to packages and internal are very different and incompatible, so this cannot be done easily with standard CMake files.

From your comments, I think you might not want to go there yet, so probably what I would try is:
- One ``conanfile`` at the root of the repo, that install dependencies for all subprojects
- Have options/cmake-variables/toggles to activate or deactivate different parts of the projects, like ``-DMYPROJ_SUBPROJ_1=False`` or something like that (maybe with some higher abstraction over sets of subprojects)

**Comment by arturngomes** [comment]
Thanks for the quick reply.
On the main project I already have a way to specify which projects I want to build. Some of the subprojects depend on others but I've set it up with CMake so that each project build all of its dependencies.

All the subprojects should have the same set of third party dependencies. 
The main thing I was looking for was to be able to use the conan preset from the superproject to provide the paths to the third party libraries for each of the subprojects' without having to reconfigure the whole project. (This worked well when I wasn't using the preset and installed each of the third party dependencies in another folder).

The idea is that I can use cmake to build just one of the subprojects and it's dependencies when I'm working on it but also give me the flexibility to build the whole project before doing a commit to make sure I didn't break anything.

I guess I might have made my build a bit over complicated.

For now I'll just try to filter out the project I want to build with the cmake option.

**Comment by memsharded** [comment]
The Conan generated presets are not that complex.

Maybe you want to define your own presets that do what you want, and then include from them the Conan ``conan_toolchain.cmake`` file? Or directly define the toolchain with ``-DCMAKE_TOOLCHAIN_FILE=...``?

**Comment by arturngomes** [comment]
Thanks. 
I was trying this before to run it but I probably mistyped something.
I now managed to get it to work by following the arguments shown in the conan install command:

```bash
cd client/build
cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=../../build/conan_toolchain.cmake  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
```

Thank you very much :)

**Comment by memsharded** [comment]
Great, happy to help! 🙂 

> cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=../../build/conan_toolchain.cmake  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release

Now, you can also put those easily in a preset file and have ``cmake --preset my-preset`` to make it even more convenient.

Thanks to you for the feedback!

**Comment by memsharded** [comment]
The new Conan 2 ``Workspace`` feature is already out there. Please give it a try, and create new tickets for any question, issue or suggestion.

It is in incubating: https://docs.conan.io/2/incubating.html, so please give your feedback in https://github.com/conan-io/conan/issues/18263 even if everything works smoothly and you have no other comments. Thanks for your feedback!
