### ISSUE TITLE
[feature] Backport fix for `VCVars` for `clang` with `runtime_version=v144` to Conan 1

### ISSUE THREAD

**Issue by glebov-andrey** [conan-io/conan#16930]
### What is your suggestion?

Hi,

Would it be possible to backport #16374 to Conan 1?
I've seen multiple comments that there is no plan to backport changes to the `msvc` compiler, however could it be done with for `clang`?
The `Visual Studio` compiler seems to work just fine (with no `toolset` specified), as well as all the legacy `vcvars` helpers, but the modern `VCVars` generator breaks with `clang`.

I can provide a PR if it is decided that this is acceptable.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @glebov-andrey 

Thanks for the offer to contribute.
We are trying to reduce to the very minimum the backports, and slowing down Conan 1.X releases, because Conan 2 is already 19 months old, and dev efforts have fully shifted to it, because there is no time enough for everything. It is very strongly recommended to prioritize the upgrade to Conan 2.

If you think that https://github.com/conan-io/conan/pull/16374 has 0 chance to break any existing Conan 1.X users feel free to do a PR with it, and we will have a look. Thanks!

**Comment by glebov-andrey** [comment]
@memsharded That's quite understandable. We are going to prioritize switching to Conan 2 in the foreseeable future, but with a few hundred recipes of various quality, it will take some time.

I've created a PR with the minimum required changes to get it to work.
Thanks for taking a look!

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/16932
