### ISSUE TITLE
[question] Dont export sources to public and  dont use scm to manage source alone at same time？

### ISSUE THREAD

**Issue by followtheart** [conan-io/conan#16943]
### What is your question?

Hi！
    I have my source and conanfile.py at same place without using of scm(like git/svn);
     Is there any way ONLY publish the binaries,and keep sources in private?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @followtheart 

Thanks for your question

> I have my source and conanfile.py at same place without using of scm(like git/svn);

I am curious, how is this possible? Where do you keep your code?

> Is there any way ONLY publish the binaries,and keep sources in private?

There are some possibilities:

- You could be building locally, like ``conan install`` + local build (could be ``conan build``) + ``conan export-pkg``

- You could also run whatever you want in your ``source()`` method, if you want to hardcode an absolute path to retrieve the sources, basically doing a copy of your sources to the ``self.source_folder`` (that folder is not uploaded)

However, you must be very careful, because packages created this way do not keep the 1:1 relationship of the recipe version + recipe revision with the source code, meaning that many features could be broken. It would be very strongly encouraged to at least compute a checksum of all source code involved and store that checksum in the ``conandata.yml``, to guarantee a unique correspondence of recipe-revision with actual sources

**Comment by followtheart** [comment]
Thx for your quick reply！In fact，I managed my source and `conanfile.py` in same svn repo(seems no difference with no scm),
and file structre like
```
conan-template
  │  CMakeLists.txt
  │  conanfile.py
  │
  ├─3rd
  │  ├─include
  │  └─lib
  ├─include
  ├─src
  └─test_package
      │  CMakeLists.txt
      │  conanfile.py
      │
      └─src
              example.cpp
```
And,I'm using `exports_sources = "CMakeLists.txt", "src/*", "include/*"` for the build process;
and build/package/upload like:
```
conan install . -pr:a relwithdebinfo
conan build . -pr:a relwithdebinfo
conan export-pkg . -pr:a relwithdebinfo
conan upload xxx -r xxx
```
But,the problem is the source code(should be private,only access by package developer) is published to the remote jfrog;
Any demo usage of `source()` to avoid the sources' leak?

**Comment by memsharded** [comment]
> And,I'm using exports_sources = "CMakeLists.txt", "src/*", "include/*" for the build process;

You can completely drop the ``exports_sources`` if you are using that flow with ``build + export-pkg``, not necessary at all, and your sources will not be uploaded to the server.
Furthermore, you can also drop the ``conan install``, as ``conan build`` already calls ``conan install`` internally.


For having a full reproducible package build, including ``conan create`` and the possibility of building this package as a dependency for a new binary configuration, I would advice to follow the same as in https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html, but for your svn, it shouldn't be very difficult:

- Capture the url and revision/number in the ``export()`` method and store it in ``conandata.yml``
- Use in your ``source()`` method the information from ``self.conan_data`` to do a retrieval of the source code from ``svn``.

Please check that doc and let me know if this helps.

**Comment by followtheart** [comment]
> Capture the url and revision/number in the `export()` method and store it in `conandata.yml`

Its a good idea to using a `conandata.yml` to store the `svn revision/number` for reproducible build;
But，because we put `conanfile.py` and source code and also the `conandata.yml` with revision info in same repo;
So, every time we change the code,we will need two submit;
* first time to submit the real source code to get a svn revision/nubmer;
* second time to submit the update in `conandata.yml` with new svn revison/number（got in first submit）;

It seems not convenient as we expected.

But,Can i using the current version of code like this idea?
> if you want to hardcode an absolute path to retrieve the sources, basically doing a copy of your sources to the self.source_folder (that folder is not uploaded)

With:
```
def source(self):
    copy("src/*",self.source_folder)
    copy("include/*",self.source_folder)
    copy("3rd/*",self.source_folder)
```

**Comment by memsharded** [comment]
> So, every time we change the code,we will need two submit;

first time to submit the real source code to get a svn revision/nubmer;
second time to submit the update in conandata.yml with new svn revison/number（got in first submit）;

Not really. The way the ``Git`` implementation works is something like this:

- When capturing the url+commit information in the ``export()``, check the status. If the commit is not in the server yet, then store instead the path to the folder
- When calling ``source()`` check what is in the conandata. If it is a server url and revision, then get it from the server, if it is just a local path, do a copy from the local path.

This achieves both goals automatically: you can get reproducible builds, with unique identifiers recipe<->code, and you also allow developers to test locally without having to upload the changes to the servers.

> But,Can i using the current version of code like this idea?

Yes, you can, but you might need the full abs path, a rough idea (not tested):

```python
def source(self):
     copy(self, "*.h", src="/full/path/to/your/src", dst=self.source_folder)
```
Because the ``cwd`` will be the source-folder already so the path to your code in user space need to be absolute.
This is why this is better done dynamically, the ``export()`` method can save this absolute path in ``conandata.yml``, and ``source()`` will only read it.

**Comment by followtheart** [comment]
@memsharded 
First, thx for your suggestion of the magic internal variable `self.source_folder`,which not been uploaded,and solve my problem.
Second ,thx for you tips of:
> Furthermore, you can also drop the `conan install`, as `conan build` already calls `conan install` internally.

which simplify my build process.

Finally,
I have tried this(releative path works fine.):
```
def source(self):
    copy(self, "*.c", src=".", dst=self.source_folder, keep_path=True)
    copy(self, "CMakeLists.txt", src=".", dst=self.source_folder, keep_path=True)
    copy(self, "*", src="include", dst=self.source_folder, keep_path=True)
```
And issue closed.

**Comment by memsharded** [comment]
> I have tried this(releative path works fine.):

Uhm, but are you sure you removed the ``exports_sources``? I am not that sure that such relative paths would work in the ``conan create`` case, I think it will fail, and in the local flow (``conan build + conan export-pkg``) the ``source()`` method in your case is irrelevant, you don't need it at all.

**Comment by followtheart** [comment]
Okay, you're absolutely right...I have removed the `exports_sources`,but only tested the local flow `conan build + conan export-pkg` and the `source()` method doing nothing for local flow.
After remove the `export_sources`,the `conan create ` case ,not working.
Though,the local flow is enough for my solution.
As an additional discussion,to support the `conan create `  with scm(like my case: svn); I would like to point out some differences between Git and SVN.
* Using git,you can get the commit id BEFORE submit to code sever
* For svn,you can only get a version number AFTER submit to code server.

and if we place `conandata.yml` in the same way with `conanfile.py` as part of source code;when is the suitable time for update the `conandata.yml`? It seems the build process should not change the recipe or source code?

**Comment by memsharded** [comment]
> Though,the local flow is enough for my solution.

Ok, sounds good, you are fine at the moment.

> As an additional discussion,to support the conan create  with scm(like my case: svn); I would like to point out some differences between Git and SVN.

I used SVN, but that was like +15 years ago, I don't recall that much 😅 

But yes, I see the issue, it is difficult to get an immutable reference inside the ``conandata.yml``. Maybe, IIRC, the svn versions where incremental integers, so maybe it is possible to check from the server something and "predict" the version that will be obtained from the server, save that in the ``conandata.yml``? Just an idea to consider for the future if you need ``conan create`` support, feel free to create a new ticket then if that happens to discuss.

In any case, aren't you considering moving to git? We used to have built-in svn support in Conan 1, but we have seen basically all of the orgs that were using svn finally moving to git in the last few years, so svn was no longer supported in Conan 2.
