### ISSUE TITLE
[question] How to package  *.dll with datas in a package and consume it ?

### ISSUE THREAD

**Issue by followtheart** [conan-io/conan#16989]
### What is your question?

I have a dll with some data(*.dat) can i pacakge it in a conan pacakge?and consumer it in some other app?
Here is the package's  `conanfile.py`:
```
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps
from conan.tools.files import copy
import os

class libxxxRecipe(ConanFile):
    name = "libxxx"
    version = "5.9.1"
    # package_type = "shared-library" 
    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"

    def package(self):
        copy(self, "data.dat", os.path.join(self.build_folder, "."), os.path.join(self.package_folder, "include"), keep_path=False)
        copy(self, "libxxx.dll", os.path.join(self.build_folder, "."), os.path.join(self.package_folder, "bin"), keep_path=False)

    def package_info(self):
        self.cpp_info.libs =["libxxx"]
```
and then `conan export-pkg . `
and consumer's `conanfile.py`:
```
    def requirements(self):
        self.requires("libxxx/[>=1.0.0]")
```
and comsumer `CMakeLists.txt`:
```
find_package(libxxx REQUIRED)
```

and the error is:
```
-- CMake-Conan: find_package(libxxx) found, 'conan install' already ran
-- Conan: Target declared 'libxxx::libxxx'
CMake Error at consumer/conan/build/generators/cmakedeps_macros.cmake:67 (message):
  Library 'libxxx' not found in package.  If
  'libxxx' is a system library, declare it with
  'cpp_info.system_libs' property
Call Stack (most recent call first):
  consumer/conan/build/generators/libxxx-Target-debug.cmake:23 (conan_package_library_targets)
  consumer/conan/build/generators/libxxxTargets.cmake:24 (include)
  consumer/conan/build/generators/libxxx-config.cmake:16 (include)
  conan_provider.cmake:618 (find_package)
  platform/cmake/AppConfig.cmake:2 (find_package)
  src/CMakeLists.txt:52 (include)
```
Any advice for thie situation?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by czoido** [comment]
Hi @followtheart,
Thanks for the question. As your example seems a bit incomplete, I have made a repo with an example to achieve what you are looking for. You can check it here:

https://github.com/czoido/conan-issue-16989

You can see [there](https://github.com/czoido/conan-issue-16989/blob/44a583551ee0c080202a26b366750bb9063679c8/conanfile.py#L52) that we can copy the `data.dat` to the `res` folder to be packaged:

```
copy(self, "data.dat", src=self.source_folder, dst=os.path.join(self.package_folder, "res"), keep_path=False)
```

Then, [at the time of consuming](https://github.com/czoido/conan-issue-16989/blob/44a583551ee0c080202a26b366750bb9063679c8/test_package/conanfile.py#L16-L18) (in the repo `test_package` is the consumer of the library) with a `conanfile.py` you can use the `generate` method to make that file available at runtime:

```
def generate(self):
    copy(self, "data.dat", os.path.join(self.dependencies["libxxx"].package_folder,
        "res"), os.path.join(self.build_folder))
```

You could also package the data.dat along with you dynamic library files and load the data from there, it's just a matter of changing to package the folder in the cache where the dll's are packaged.

```
copy(self, "data.dat", src=self.source_folder, dst=os.path.join(self.package_folder, "lib"), keep_path=False)
```

And then having the C++ code that loads the data from that place.

Hope this helps.

**Comment by followtheart** [comment]
@czoido Thx for your quick reply.
Sorry, I may not have described it clearly at front of the issue.
Both of `res` folder and copy to `lib` are good advice for using lib with data.
But, 
- Maybe the problem in current is the `consumer` cannot find the `libxxx` package(which  has only a `libxxx.dll` and a `data.dat`)

And I create a minimal repo [https://github.com/followtheart/conan-issue-16989](https://github.com/followtheart/conan-issue-16989)  to reproduce the problem.

**Comment by memsharded** [comment]
Thanks for the repo with the code it helps.

I think the issue is that if the package only contains the ``.dll``, it is not a build-time package, it is exclusively a runtime package. If it doesn't contain an import library, in Windows it is not possible to link it, everything will be dynamic. So it doesn't make sense to do a ``find_package()`` of it, because it will not create any targets that we can ``target_link_libraries()``.

So it would be basically removing the ``find_package()`` from the consumer CMakeLists.txt?

Conan will still create the ``conanrun.bat`` files that contain the PATH environment variable containing the folder of the .dll, so activating that file will allow consumers at runtime to execute the .dll.

Please let me know if this makes sense.

**Comment by followtheart** [comment]
@memsharded Thx for pointing out the difference of build-time and runtime package.
Maybe I can create a `libxxxConfig.cmake` manually,and passing some variables to consumer in it.
And pack the `libxxxConfig.cmake` into `libxxx` package.
But ,I dont know how to make it visible to consumer's `find_pacakge`(whether it's  possible?) or replace one of `*.cmake` files generated by conan with it ?

**Comment by memsharded** [comment]
Yes, you can use config.cmake files from inside packages, there is a full example here: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html

I am still curious, what variables are you defining for that package, and how do you use them in the consumer? If it is just a dll, then it is pure runtime, and not needed at all by the consumer CMakeLists.txt?

**Comment by followtheart** [comment]
Well,just some strange variables defined by some other guy🐶 . 
And I will try this demo [https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html](https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html)
and I also found another way to pass the variables
- First, in package's `conanfile.py`,point the `cpp_info.builddirs` to `cmake\` (which contains the `libxxxConfig` we need.)
```python
    def package_info(self):
        self.cpp_info.builddirs = ["cmake"]
```
- Second,in consumer's `CMakeLists.txt`, replace `find_package(libxxx)` with `include(libxxxConfig)`
- Finally,the variables are visible to consumer.

Thx again.
Issue closed.

**Comment by memsharded** [comment]
Sounds good, happy that you made it work, thanks to you for the feedback!

**Comment by followtheart** [comment]
I'm sorry that there is still some problem... 😭 

When consume the pacakge with conan directly:
- with `include(libxxxConfig)`,just works;
- with `find_package(libxxx)`,***Failed***.;

When consume the package with [cmake-conan](https://github.com/conan-io/cmake-conan/tree/develop2):
- both  `include(libxxxConfig)` and  `find_package(libxxx)` fails. 😢 

I have update the [`conan-issue-16989`](https://github.com/followtheart/conan-issue-16989.git)

I have tried [https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html](https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html)
the package does NOT have a `CMakeLists.txt`

Any help?

**Comment by memsharded** [comment]
> When consume the package with [cmake-conan](https://github.com/conan-io/cmake-conan/tree/develop2):

This is kind of expected. The ``conan_toolchain.cmake`` generated by CMakeToolchain is the one containing the necessary location of packages for ``find_package()`` to work when trying to use ``config.cmake`` files inside Conan packages. 

The ``cmake-conan`` integration works without CMakeToolchain, because as cmake runs first, it cannot inject the ``conan_toolchain.cmake`` is generated later. The way ``cmake-conan`` works is via the recommended CMake "dependency providers" that are a hook that is called when ``find_package()`` is called. So until ``find_package()`` is called, conan is not even called. 

I'll try to have a look to the repo code, thanks for updating it.

**Comment by memsharded** [comment]
Not sure what is happening, it works for me:

```diff
diff --git a/consumer/CMakeLists.txt b/consumer/CMakeLists.txt
index 160e487..5be406a 100644
--- a/consumer/CMakeLists.txt
+++ b/consumer/CMakeLists.txt
@@ -1,8 +1,9 @@
+cmake_minimum_required(VERSION 3.15)
 project(consumer CXX)


-# find_package(libxxx)  # not working `conan build`
-include(libxxxConfig)   # working in `conan build`
+find_package(libxxx)  # not working `conan build`
+# include(libxxxConfig)   # working in `conan build`

 add_executable(consumer src/consumer.cpp src/main.cpp)

diff --git a/consumer/profile b/consumer/profile
index 0140d95..4313eb2 100644
--- a/consumer/profile
+++ b/consumer/profile
@@ -4,5 +4,5 @@ build_type=Release
 compiler=msvc
 compiler.cppstd=14
 compiler.runtime=dynamic
-compiler.version=191
+compiler.version=193
 os=Windows
\ No newline at end of file
diff --git a/package/profile b/package/profile
index 0140d95..4313eb2 100644
--- a/package/profile
+++ b/package/profile
@@ -4,5 +4,5 @@ build_type=Release
 compiler=msvc
 compiler.cppstd=14
 compiler.runtime=dynamic
-compiler.version=191
+compiler.version=193
 os=Windows
\ No newline at end of file
```

I just changed the compiler version (I don't have installed that VS) and added the cmake_minimum_required and it works

**Comment by memsharded** [comment]
Some other potential issues:

- ``package_type = "build-scripts"`` doesn't look correct, as this contains binary artifacts. ``shared-library`` would be closer
- It seems you are missing ``self.cpp_info.set_property("cmake_find_mode", "none")`` in the "package" to avoid consumers generating the ``packageConfig.cmake`` on the consumer side on the fly.

**Comment by followtheart** [comment]
@memsharded thx for your advice.
Yes，the consumer works fine now，both `find_package` and `include`;(In test early, I missing `conan build` before `conan export-pkg` when build the `libxxx` package.

However, the real problem I am facing is about `cmake-conan` ; Because this is the transitional plan we are planning to use to migrate from cmake build to conan build; This will continue for a period of time; If `cmake-conan` cannot package pure DLLs, should I revert back to using conan directly?

**Comment by memsharded** [comment]
> However, the real problem I am facing is about cmake-conan ; Because this is the transitional plan we are planning to use to migrate from cmake build to conan build; This will continue for a period of time; If cmake-conan cannot package pure DLLs, should I revert back to using conan directly?

It is not exactly that cmake-conan cannot package DLLs, it is about the usage of dependencies that do not follow the standard ``find_package()`` with CMakeDeps generated packages, because ``cmake-conan`` cannot inject the necessary information without passing a toolchain file.

I think there are a couple of things worth trying:
- Try again with the ``find_package()`` approach, using the CMakeDeps generated one, and letting the package define a ``cmake_build_module``, which are automatically loaded by ``find_package()`` and that could allow you to define the variables you want. Something like https://docs.conan.io/2/examples/graph/tool_requires/use_cmake_modules.html, but for a regular ``requires``
- If that doesn't work, I'd reconsider the "canonical" ``conan install`` + ``cmake --preset`` approach. It works quite well in practice because it eliminates an extra layer (cmake-conan), makes devs more aware of the difference between the dependencies install and the actual build (otherwise, for them everything becomes a "build-error", and then rely on someone else to investigate, while being explicit gives them more ownership and that helps a lot in the mid term), and also because some tools work very nicely with presets, for example VSCode don't even need to type ``cmake ...`` can be done from the IDE.

We will keep working on cmake-conan to try to improve somehow these things, but the truth is that the intrinsic limitations of the inversion of control makes things a bit challenging when getting out of the beaten path (tool-requires, special requires, etc)

**Comment by followtheart** [comment]
@memsharded thx; https://docs.conan.io/2/examples/graph/tool_requires/use_cmake_modules.html; this works for me!
It is worth noting that:
In package‘s `conanfile.py`,should NOT have the line,like:
```
self.cpp_info.libs =["libxxx"]
```

**Comment by memsharded** [comment]
> @memsharded thx; https://docs.conan.io/2/examples/graph/tool_requires/use_cmake_modules.html; this works for me!

Excellent! Happy to hear that it working.

> self.cpp_info.libs =["libxxx"]

Yes, that seems correct, that would only be for linking library

Always happy to help!
