### ISSUE TITLE
[bug] Adding shared option to conanfile breaks dependency propagation on MacOS

### ISSUE THREAD

**Issue by lia-viam** [conan-io/conan#16994]
### What is your question?

Hello!

I'm not sure if this may be a bug or the expected behavior, so I'll try to include more info
```shell
$ conan --version
Conan version 2.7.1

$conan profile show
Host profile:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=17
compiler.libcxx=libc++
compiler.version=15
os=Macos

Build profile:
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=17
compiler.libcxx=libc++
compiler.version=15
os=Macos
```

Basically, I have a library that I'm packaging with a `conanfile.py`, and the library itself has a CMake build that defaults to `BUILD_SHARED_LIBS=ON` so I did not initially add a `shared` option to the `[default_]options` of the package. The package and `test_package` were building fine with `conan create .`, but adding `shared` to the options broke the build, regardless of whether shared was `True` or `False`, or whether `package_type = "library"` was present or not.

I was able to reduce it to the following MWE which still fails on Mac, see here for a diff showing how it was modified from a call to `conan create new cmake_lib ...`:
https://github.com/lia-viam/conan-mwe/commit/72a3d4dfca796d8df22c568df0f94a2c881b41b4?diff=split&w=0

If the lines above are uncommented it fails at the `#include` statements for boost, full error 
[here](https://github.com/lia-viam/conan-mwe/blob/main/error_out.txt)

As mentioned, this is an MWE reduced from a more complex project. The MWE "fails successfully" on Mac, but works on a Debian docker container, whereas the original code was breaking on both mac and the debian container.

The full conanfile in question is here in case anything else jumps out:
https://github.com/lia-viam/viam-cpp-sdk/blob/feature/conan-deps/conanfile.py

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @lia-viam 

Thanks for your report

I think the reason for this is the inclusion of the boost headers in the public headers of ``mwe``, this would be expected behavior.

By default Conan does not propagate headers from dependencies to the consumer of the package, it assumes they are "private" to the package by default. If a package has ``#include`` to its dependencies in its public headers, then it needs to define it in the ``requires`` with:

```
self.requires("boost/...", transitive_headers=True)
```
This will make available the boost headers to the consumers of the ``mwe`` package.

Could you please try that?

The reason why this is happening when defining ``shared`` options is because when Conan knows the "package-type" it assumes this model. If the package type is unknown, then the propagation will happen. You should be able to get the issue just by adding ``package_type = "shared-library"`` (without adding the ``shared`` option), which would be recommended for libraries that "hardcode" being shared ones (same for ``package_type = "static-library"``)

**Comment by lia-viam** [comment]
@memsharded thanks for the explanation, that makes sense and fixed the issue in my original project. 

Just before I close the issue--as an etiquette question similar to not deleting stack overflow questions, would you prefer if I didn't delete the mwe repository "for posterity" or is it OK to nuke it

**Comment by memsharded** [comment]
No, don't worry, I think you can remove the repo without problem. Thanks for asking!

**Comment by lia-viam** [comment]
Cool thanks again!
