### ISSUE TITLE
exclude obsolete versions from search by default

### ISSUE THREAD

**Issue by TyRoXx** [conan-io/conan#170]
I would like to deprecate package versions without having to remove them entirely. If you are just searching for a library name, you should only get useful results.

At the moment search results appear in seemingly random order and you have to figure out by yourself what is the appropriate one:
![unbenannt](https://cloud.githubusercontent.com/assets/941829/13189070/8bf93662-d755-11e5-9547-97be9ae0c6a7.png)

**Comment by aurelienrb** [comment]
Same thing for me.

Conan failed to build locally because cmake is missing. So I tried to install it... with Conan :)

The page [https://conan.io/search?q=cmake](https://conan.io/search?q=cmake) show many results... that are all empty => **[ No packages ]**. Could you provide a way to ignore such results?

And may be an easy way as well to install cmake :)

**Comment by lasote** [comment]
@TyRoXx @aurelienrb [We are moving to Bintray](http://docs.conan.io/en/latest/move_to_bintray.html) In bintray each user will have (totally free as conan.io is) an unlimited number of personal repositories, and will provide a central `conan-center` with only curated recipes. Also the recipes are grouped by version and channel so the search is not affected by obsolete versions. I think this issue will be solved very well with Bintray support. Thanks!
