### ISSUE TITLE
[bug] Dependencies aren't populated at source time for `build`

### ISSUE THREAD

**Issue by mtribiere** [conan-io/conan#17016]
### Describe the bug

**Environment** 
- OS: Linux
- Conan version: v2.6.0

**Description**
In my `source()` method, I generate C code that is shared between all my configuration. 
For this I need a Python launcher, and I need to access a reference configuration located in a dependency. I have this code:

```python
[...]
python_requires = "my_launcher/0.1.0rc4"

def source(self):
    
    # Generate source files
    my_launcher = self.python_requires["my_launcher"].module.My_Launcher(self)
    my_launcher.generate(
        self.dependencies["gacng_symb"].package_path,
        self.source_path.joinpath("SCADE.zip")
    )
    my_launcher.scheduling(self.source_path.joinpath("gen_session"))
    my_launcher.generate_interface(self.source_path.joinpath("gen_session"))        
[...]
```

With `conan create .` it works, but with `conan build .` errors out with:
```python
ERROR: conanfile.py (lib_sfcp/1.2.0): Error in source() method, line 35
      self.dependencies["gacng_symb"].package_path,
      AttributeError: 'NoneType' object has no attribute 'transitive_deps'
```

Am I using this wrong or this is a bug?

**Comment by AbrilRBS** [comment]
Hi @mtribiere thanks a lot for your question.

This would not be a bug, but expected behaviour. The `source()` method is executed without context of its dependencies, nor the configuration it's being called from, and as such, it can not depend on anything most of the time, see our best practices in https://docs.conan.io/2/reference/conanfile/methods/source.html#source

As for your issue, I'd recommend moving this code to the `generate()` method, which is meant for just this use-case of preparing the source for building, see https://docs.conan.io/2/reference/conanfile/methods/generate for some examples

I hope this helps, let me know if you have any further questions, happy to help :)

**Comment by mtribiere** [comment]
Hello @AbrilRBS,

Thank you for the quick response. I do have a few more questions:

- If `source()` is context-less, why does `conan create .` works and `conan build .` doesn't?

- I originally had the call to the code generator in the `generate()` method as you suggested. However, it is a very long process (several hours), and this code need to be compiled for different configurations (AARCH64, X86_64,...). So each `conan create . -pr=<my_profile>` would regenerate the code which is not very efficient.  </br> My objective is to generate the C code first, share it with all configurations, then perform a build for each profile. How should I go about this? 

Thank you for your help :)

**Comment by memsharded** [comment]
I'd chime in :)

> If source() is context-less, why does conan create . works and conan build . doesn't?

That is more an accidental "leakage" of the information than a feature. As ``conan create/build`` do compute the full dependency graph before calling the respectives ``source()`` method, it will happen that the ``self.dependencies`` is there and ``source()`` might try to be able to use it. Still any attempt of doing that would be ill-formed, next ``conan create/build``, even if it some different dependencies, will result in the re-usage of a now outdated generated code, because the ``source_folder`` is always considered invariant.

In practice it means that we will most likely want to block the usage of ``self.dependencies`` in the ``source()`` method to avoid these issues.

> I originally had the call to the code generator in the generate() method as you suggested. However, it is a very long process (several hours),

Have you considered creating this generated code in its own Conan package, then ``require`` that package from the other package that will be using it?  Maybe that decoupling helps to keep things more organized? The resultant generated code would be part of the ``package()``, and the consumer of it can just access its location via ``dependencies["src_dep/versn"].package_folder``.

**Comment by mtribiere** [comment]
Hi @memsharded,

Thanks your answers, the separation as a dedicated packages that generate sources is definitely a good idea.
The code generator is generating a CMake file for easy integration with the rest of the build process. How could I pass this `dependencies["src_dep/versn"].package_folder` to CMake and use the `add_subdirectory()` method?

Again thank you for you help :)

**Comment by memsharded** [comment]
> The code generator is generating a CMake file for easy integration with the rest of the build process. How could I pass this dependencies["src_dep/versn"].package_folder to CMake and use the add_subdirectory() method?

I think that for the ``add_subdirectory()`` it needs to be located as a child folder, not sure if ``add_subdirectory()`` works with absolute paths. So maybe the way is to do a copy of the contents of ``dependencies["src_dep/versn"].package_folder`` in the ``generate()`` method of the consumer, so when the ``build()`` runs, it will find the sources there in a folder as if they were always there?

**Comment by mtribiere** [comment]
That do makes sense, copying the folder from the dependency to the `self.source_folder` works for me.
Thank you for your help!

**Comment by memsharded** [comment]
Happy to help, thanks for the feedback!
