### ISSUE TITLE
[bug] Package type doesn't make sense for package that holds a library with an accompanying application

### ISSUE THREAD

**Issue by stevn** [conan-io/conan#17031]
### Describe the bug

MacOS 13 Intel
Conan 2.6.0
Apple clang 15

I am not sure how to handle Conan packages that hold one or multiple libraries and one or multiple applications.
It seems too much overhead to create separate Conan packages, since these are usually developed together as one project.

Example project which demonstrates the issue:
<https://github.com/stevn/conan_pkg_type_test/tree/main>

Note the `package_type` is set to `unknown` in root `conanfile.py`. It can also be set to `library` or `application` but in all cases there is some error.

I am not sure what the best solution for this common problem would be? I would like to be able to link the library / libraries, but also would like to be able to quickly use some simple tools on the command line to check certain functions quickly & easily. I don't really feel like creating a different git repo + conanfile package etc just for the tool(s).

### How to reproduce it

$ git clone https://github.com/stevn/conan_pkg_type_test
$ cd conan_pkg_type_test
$ conan create .
...
[100%] Built target stufftestpkg

======== Testing the package: Executing test ========
stuff/1.0.0 (test package): Running test()
stuff/1.0.0 (test package): RUN: ./stufftestpkg
stufftestpkg: It works!

stuff/1.0.0 (test package): RUN: stufftool
/bin/sh: stufftool: command not found

ERROR: stuff/1.0.0 (test package): Error in test() method, line 28
        self.run("stufftool", env="conanrun")
        ConanException: Error 127 while executing

**Comment by stevn** [comment]
I guess the current workaround is to set the `package_type` to `library`:

https://github.com/stevn/conan_pkg_type_test/blob/main/conanfile.py#L19

And disable (comment out) running the tool in the test_package, since the `conanrun` environment will not contain the bin dir in which the executable is located when `package_type=='library'`:

https://github.com/stevn/conan_pkg_type_test/blob/main/test_package/conanfile.py#L28

**Comment by memsharded** [comment]
Hi @stevn 

Thanks for your feedback.

This would be the typical case of the ``protobuf`` library + application, we have an example here: https://docs.conan.io/2/examples/graph/tool_requires/different_options.html

The recommendation is to define it as a ``library`` as you already guessed, because when you want to use the applications from another Conan package at build time it needs to be a ``tool_require`` and the ``tool_require`` already defines the "intention" of usage (that is the correct traits, ``build=True``, ``headers=False``, ``libs=False``...), so it works too.

Regarding the ``test_package``, there might be different options, depending on what you want to test, you can add it as a ``tool_require`` there, or you can force the ``run=True`` trait, even if it is a static library.

Please let me know if this helps.

**Comment by stevn** [comment]
Thanks! I also found another workaround:

Add this line to package_info():

    self.runenv_info.append_path("PATH", os.path.join(self.package_folder, 'bin'))

**Comment by stevn** [comment]
But run=True is probably a better solution. Thanks!

See:

https://github.com/stevn/conan_pkg_type_test/commit/bd781f1aa229f1c66fd3900c85dd6db5392f2018

**Comment by memsharded** [comment]
> But run=True is probably a better solution. Thanks!

It depends on the needs. In one case is the package who is deciding to inject some runtime info, and in the other case, it is the consumer deciding to use the runtime info of the package. The second might be "safer" in some cases, because accidentally getting in the PATH something that might not be possible to run (different arch in cross-compiling) might be problematic.


Thanks for the feedback!
