### ISSUE TITLE
[bug] target_compile_option is not correct recognized 

### ISSUE THREAD

**Issue by JSchmid6** [conan-io/conan#17040]
### Describe the bug

As cmake says, there schon be add SHELL: to each option from self.cpp_info otherwise we get compile error on generated <PKG>Conf.cmake files. We uses this to enforce include files for protobuf on windows. 

New in version 3.12: While beneficial for individual options, the de-duplication step can break up option groups. For example, -option A -option B becomes -option A B. One may specify a group of options using shell-like quoting along with a SHELL: prefix. The SHELL: prefix is dropped, and the rest of the option string is parsed using the [separate_arguments()](https://cmake.org/cmake/help/latest/command/separate_arguments.html#command:separate_arguments) UNIX_COMMAND mode. For example, "SHELL:-option A" "SHELL:-option B" becomes -option A -option B.

**Comment by memsharded** [comment]
Hi @JSchmid6 

I am sorry, but your report is not very clear.
Please make sure to provide:
- The Conan version, your current platform details: OS, compiler, etc
- ``conanfile.py`` and other auxiliary files you might need to reproduce the issue.  You can use the ``conan new`` templates as a recommended starting point.
- The exact commands to reproduce the issue
- The full output of those commands, explaining what was the expected behavior, and how it differs from the resulting one.

Many thanks.

**Comment by memsharded** [comment]
Hi @JSchmid6 

Any further feedback here? 
Please let us know if you can provide more details to understand what could be happening. Thanks for your feedback.

**Comment by memsharded** [comment]
Closing as staled, please re-open or create a new ticket if you have any further feedback.
