### ISSUE TITLE
[bug] Eset antivirus livegrid blocking the official installer from github

### ISSUE THREAD

**Issue by MarioVolarevic** [conan-io/conan#17060]
### Describe the bug

OS: Windows 10 22h2
Conan ver: 2.7.1

### How to reproduce it

Does anyone have an issue where  Eset antivirus (popup says Eset livegrid) is blocking this link and installer:
https://github.com/conan-io/conan/releases/download/2.7.1/conan-2.7.1-windows-x86_64-installer.exe 

or this zip
https://github.com/conan-io/conan/releases/download/2.7.1/conan-2.7.1-windows-x86_64.zip 

I see that long time ago similar issue was reported for Windows Defender:
https://github.com/conan-io/conan/issues/8305
but this was closed.

When I use the link on virustotal, it seems fine, but I guess it's not scanned by livegrid component there.

**Comment by memsharded** [comment]
Hi @MarioVolarevic 

Thanks for your feedback.

As described in https://github.com/conan-io/conan/issues/8305#issuecomment-757437848, this is not a Conan bug, but misdetection of AVs due to the fact that some malicious apps are also using ``pyinstaller``, and then the AVs flags all apps created with ``pyinstaller`` as malicious. But there is very little we can do there, the recommended approach would be to report to the AVs with a request to allow-list the Conan installer.

**Comment by memsharded** [comment]
Any further feedback here? I am closing this ticket as responded, as the Conan installer doesn't seem to be affected by any real issue, and there is little we can do from our side. As other potential approaches to this:

- Use the ``pip install`` flow
- Create your own self-contained executable in-house with the ``python pyinstaller.py`` utility in the root of the repo
- Request the AV vendors to allow-list the Conan installer so it is not reported or blocked.

Thanks very much for the feedback.
