### ISSUE TITLE
[question] How to remove duplicated options in the environment(conan/conan/tools/env/environment.py) variable?

### ISSUE THREAD

**Issue by Bo-Liu-BL** [conan-io/conan#17081]
### What is your question?

Hi experts,
I have a question on the environment(conan/conan/tools/env/environment.py):
**How to remove the duplicated values from the environment variable with a loop such as `for`?**

For example, I have `CXXFLAGS` in the environment variable and it contains two or more `-MDd` options in it.
From [the source code](https://github.com/conan-io/conan/blob/97ab818c45b5db10bb37cce8175a8b86d1dcf17c/conan/tools/env/environment.py#L281C9-L281C15), we couldn't remove the duplicated ones within a `for` loop but have to manually remove it one by one.
Namely, use the following format:
```
env.remove("CXXFLAGS", "-MDd")
```

If it contains 3 or even more, I have to use the above code twice or more times. And it is rigid if `-MDd` would be present more times in the future.

**Is there any existing way for me to remove the duplicated options?**

Thank you!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Bo-Liu-BL 

Thanks for your question.

In general the approach would be try to avoid the situation in the first place. Why there are several ``MD`` flags there?
In many situations, profiles shouldn't be setting this flag at all, for example, ``CMake`` integration will map directly the ``compiler.runtime`` to the ``CMAKE_MSVC_RUNTIME_LIBRARY`` which is the recommended approach. For other toolchains, like ``AutotoolsToolchain``, it is Conan the one setting the variable, if Conan is setting it more than once, then it should be reported, it is probably unexpected/undesired.

If you are thinking about removing env-variables defined in recipe ``conanfile.py`` code, this shouldn't be possible in general. Because with Conan design, the downstream "consumer" or user always has precedence. If the profile is defining some env-vars, those env-vars will be defined in the recipes. Recipes might try to append or define variables, but the profiles always have priority, so they can prepend, append, overwrite or unset completely the values that recipes are receiving.

**Comment by Bo-Liu-BL** [comment]
Thank you @memsharded .

Looks I need to make out other ways to avoid the duplicated options.
