### ISSUE TITLE
[question] Profile information in merged build-order files

### ISSUE THREAD

**Issue by NilsKlimanis** [conan-io/conan#17089]
### What is your question?

Hi!
In our workflow, we merge the two build-order JSON files for the Release and Debug profile and then go through the build-order hierarchy and build the packages by using the `build_args` flags from the according JSON entry for a `conan install` command.
Two questions on this procedure:

1) Is the `conan install`command the correct (the intended) way of processing a build-order file?
2) Is there a way to extract the profile information out of merged build-order files? I can only see, that the origin of a package is listed in the `filenames` entry, but from there I have to do some manual processing to retrieve the information, which profile to use for building that package.

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @NilsKlimanis 

Thanks for your question.

I am just trying to finalize the docs new CI tutorial covering these aspects, see ongoing work in https://github.com/conan-io/docs/pull/3799

It is true that it is not that straightforward to recover the profile information from the build-order files, it assumes that the build-order filename itself encodes or maps back to a given profile or configuration, because in practice multiple profiles can be passed.

I will be trying (no guarantees, I have no idea if possible), to add profile and input arguments information in the build order files for next release, please keep tuned

**Comment by memsharded** [comment]
Btw, Conan 2.8 added a new ``info`` section in the build order, that contains the ``package_id`` relevant configuration. In theory it should be possible to create a profile from it and apply it, but I also think that probably keeping the original profile arguments is more intuitive and straightforward.

**Comment by NilsKlimanis** [comment]
Hi @memsharded, 
thanks for the quick reply!
I've tried out Version 2.8 with the according `info` section, and it looks quite good!
However, I can see, that the `build_type` (e.g. `Debug`/`Release`) is not always included.
It seems though, that these are only cases, where the package doesn't need compiling...
Can you confirm this?

**Comment by memsharded** [comment]
> However, I can see, that the build_type (e.g. Debug/Release) is not always included.
It seems though, that these are only cases, where the package doesn't need compiling...
Can you confirm this?

Yes, exactly, the information that is in ``info`` is the minimal information that is necessary to reproduce this specific ``package_id``. For example for a ``header-library`` that is independent of everything, the ``info`` should be empty.
It basically means that you can use any profile or settings, and it will still produce the same final package binary.

In any case, the release cadence is every month, it means that if things go well, there might be the profiles argument information in just a few weeks, so maybe it can wait it a bit.

**Comment by memsharded** [comment]
Proposing addition of profile arguments to build-order in https://github.com/conan-io/conan/pull/17102, if you want to give it a try, try it running from sources, etc.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/17102 was merged, so the profile args will be in the graph-build-order json output. This will be in next Conan 2.9, thanks for your feedback.

**Comment by NilsKlimanis** [comment]
Thanks for your comments and your effort! The ability to use just the profile will be very valuable - but I have not tested it yet, since we are bound to official releases.
But I still have two questions on that:
1) I observed, that although I provide all the settings and options in the build command ( `conan install ...` ), it still requires me to provide a host profile. Can you confirm that? That's a little confusing, since I thought, all necessary parameters are already contained in the settings and options.
2) In your documentation (e.g. here: https://github.com/conan-io/docs/blob/62edc7e5d840c6b7c5a663fe6321dcc8826ff4be/ci_tutorial/products_pipeline/full_pipeline.rst) I can see, that you also use `conan install ...` to build the packages in the distributed build order approach (see also my question there). Can you elaborate on why you use `conan install` here instead of `conan create`, especially since `conan install` does not seem to execute `conan test` ?

**Comment by memsharded** [comment]
> I observed, that although I provide all the settings and options in the build command ( conan install ... ), it still requires me to provide a host profile. Can you confirm that? That's a little confusing, since I thought, all necessary parameters are already contained in the settings and options.

Yes, I can confirm this. This is a default that comes from UX and user expectations. In practice it is almost impossible to know if a profile is "complete", and it will not fail later because some thing is undefined. And the most common usage by far of cli arg ``--settings`` is providing not complete information, but variations over the default profile, like:

```
conan create . -s build_type=Debug
```

In other words, if you are specifying all parameters in command line, that is not the case to which the UX is optimized for, and the recommended way is to put them in a profile file. This has multiple advantages, from tracking, being able to share that profile with devs and CI with ``conan config install``, the ability to use the profile name in jinja templates for ``build_folder_vars`` for example, etc.

> In your documentation (e.g. here: https://github.com/conan-io/docs/blob/62edc7e5d840c6b7c5a663fe6321dcc8826ff4be/ci_tutorial/products_pipeline/full_pipeline.rst) I can see, that you also use conan install ... to build the packages in the distributed build order approach (see also my question there). Can you elaborate on why you use conan install here instead of conan create, especially since conan install does not seem to execute conan test ?

Yes, it is way easier to build binaries from existing recipes without having to recover the exact commit for that recipe, clone it, and do a ``conan create``. As recipes contain the necessary information, doing ``conan install`` builds is way simpler.
The ``test_package`` functionality is not intended for unit or functional testing (as stated in the docs), but as a verification that the package is correctly created, like it contains the necessary headers, libs, etc. As this is almost impossible to break or change from a rebuild from source of a package that was previously created, there is little loss or interest in the value provided by ``test_package`` for this kind of CI integration.

In any case, the ``workspace`` command for Conan 2, which we already resumed, will most likely contain helpers that will help to do the same case but with ``conan create``, by helping to recover/git-clone the source for a existing recipe revision from a Conan repo.
