### ISSUE TITLE
[feature] Make attribute `user` more flexible

### ISSUE THREAD

**Issue by mtribiere** [conan-io/conan#17082]
### What is your suggestion?

Hi, I was wondering if adding a bit of flexibility to the `user` attribute was possible.

**My use case/issue:**
I need to specify a `channel` for a given package, but by conan design I have to also specify a user. Which depending on the context, doesn't always make sense.

**Some solutions ideas:**
A. Make user optional
B. Create a parameter `core:default_user=<project_name>` in the `global.conf`
C. ?

Thank you for your help

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @mtribiere 

Thanks for your suggestion.

I am afraid this is not possible, there are some limitations in the structure of package references, storage in disk, URLs in APIs, etc, that makes this very challenging, because it relies on the order and structure of ``@user/channel``, and making channel options is possible but making user not.

In any case, usage of ``channel`` is very discouraged in most cases nowadays. Both ``user/channel`` should be pretty static and immutable, the recommendation is to use neither of them, or maybe just the ``user``, and if using the ``channel`` just use it with something very fixed, like ``stable`` and forget about it, do not use for any quality, stage or any other kind of meta information of the package. There are other mechanisms recommended for that, like using multiple server repositories.

**Comment by mtribiere** [comment]
Hi @memsharded 

Thank you for your quick answer.  
What I was trying to accomplish is a promoting system. It's a pretty typical workflow where we take a package that is fresh out of the CI (`<package>@<user>/unstable`), test it, and promote if tests are conclusive (i.e move it to `<package>@<user>/release`).

As I understand, you now discourage this approach and instead advise a "multiple server repositories" approach.
So I have a few subsequent questions:

- Could you elaborate a little on this recommendation? How would a promoting system work on modern Conan?
- If we have the requirement to have only one registry for all packages of a project, would this approach still be applicable? 
- Is currently a default user inside the `conan_home` configuration possible/planned?

Thank you for your help

**Comment by memsharded** [comment]
> What I was trying to accomplish is a promoting system. It's a pretty typical workflow where we take a package that is fresh out of the CI (<package>@<user>/unstable), test it, and promote if tests are conclusive (i.e move it to <package>@<user>/release).

Yes, this is exactly the usage that is discouraged.

> As I understand, you now discourage this approach and instead advise a "multiple server repositories" approach.

> Could you elaborate a little on this recommendation? How would a promoting system work on modern Conan?

We are working right now in these docs: https://github.com/conan-io/docs/pull/3799, hopefully they can be published soon, I think they might help with this issue. We even have extensions commands like ``conan art:promote`` for promotions among server repositories.

> If we have the requirement to have only one registry for all packages of a project, would this approach still be applicable?

It is enough to have 1 server, but at least 2 different server repos are necessary. This is a known well practice in devops, not just a Conan thing, so it should already be allowed by the organization for other package types as well.

> Is currently a default user inside the conan_home configuration possible/planned?

What do you mean a default user? Creating and requiring packages with ``@user`` by default in a transparent way? No, I am afraid not, the ``@user/channel`` part must be always both explicitly defined and required.

**Comment by mtribiere** [comment]
I see, I will follow that DevOps guide progress it's a valuable resource. 

Thank you for your helpful answers
