### ISSUE TITLE
[question] Lockfile - what's after the '%' and why is it changing

### ISSUE THREAD

**Issue by forry** [conan-io/conan#17091]
### What is your question?

Hi,
we've started using lockfile recently. We are using cmake to drive our process so cmake-conan script is modified to call `conan install` with the `--lockfile-partial --lockfile-out=${CMAKE_SOURCE_DIR}/conan.lock --lockfile-clean`. So far so good but in the lockfile after each package there is a part after the '%' which for some reason gets changed even when the conanfile doesn't. First, I couldn't find anything about that in the documentation of the lockfiles. Second, it is annoying. 

So what is it, why is it there, why is it changing so often, what could be done about that?

Thanks

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @forry 

Thanks for your question.

That number there after ``%`` is the timestamp of the revision. It needs to be there to be able to sort by time different revisions of the same version in the lockfile, something that can happen in some scenarios.

When the revision is downloaded from a server, it will get the timestamp from the server and it will be constant, because that timestamp is already server defined.

But if you are re-exporting with ``conan export`` or ``conan create`` or ``conan export-pkg`` the same revision again, this creates a new timestamp with the current time. If you use those new exported revisions in the lockfile, then the timestamps will be updated. This behavior is important, when exporting locally the user expectation is that such revision becomes the "latest" available in the local cache, and Conan will resolve to that revision. If it doesn't update the timestamp to make it the latest one, this will not happen and it becomes quite confusing, users doing changes to their local ``conanfile.py``, but then when using it those changes are not effective because Conan would be resolving to another different revision which is really the latest.

**Comment by forry** [comment]
Thanks for your answer.

I'm pretty sure that none of the guys reporting this issue to me had done any reexporting or re-uploading to the server or their local cache. Does that timestamp get updated even when your `conan install` have `--update` switch thus looking for the new revisions even if there are none and then updating the timestamp for the old ones for some reason?

I removed the --update as soon as I started to use the lock files, but it could be lurking in someone's old cmake cache, although it seems unlikely, and certainly is not on my machine. So is there any other way for the timestamp to get updated and overwritten?

**Comment by memsharded** [comment]
I have re-checked, and in theory ``--update`` shouldn't change it either, unless obviously there is a new updated revision in the servers, which is being used and updated by the client. But ``--update``, as long as it resolves to the same server revisions, wouldn't change the timestamps either.

**Comment by forry** [comment]
Thanks, I will monitor it and if needed, I will reopen with the follow-up questions.

**Comment by forry** [comment]
We have tracked down probable cause, but I'm not sure. It seems that I have different timestamps than everybody else. Could it be because I'm the one that created the packages and then uploaded them to the server? Does that mean that the server used the timestamps not from me but from the time they were uploaded perhaps? If that is true, why is that?

So for me to not rewrite the lockfile every time I need to commit something, I need to delete whole cache and download it again from the server?

This seems like a plausible explanation, but the result is somewhat unfortunate. Is there another way if that is the case?

**Comment by memsharded** [comment]
> We have tracked down probable cause, but I'm not sure. It seems that I have different timestamps than everybody else. Could it be because I'm the one that created the packages and then uploaded them to the server? Does that mean that the server used the timestamps not from me but from the time they were uploaded perhaps? If that is true, why is that?

Yes, that is correct. 
The servers assign a new timestamp the first time a revision is uploaded to that server. This is also necessary to keep some consistency, otherwise packages created in different places, at different times and with decentralized and possible misaligned clocks would be defining a global time order, and that doesn't work well in practice and confused users that expect a new revision just uploaded to a server to become that latest one in that server.

This is aligned with the guidelines in https://docs.conan.io/2/knowledge/guidelines.html:

> Developers should not be able to upload to “development” and “production” repositories in the server. Only CI builds have write permissions in the server. 

And in CI the local cache timestamps are not a problem, because builds and caches there are isolated and temporary, being cleaned in new jobs.

**Comment by forry** [comment]
> Developers should not be able to upload to “development” and “production” repositories in the server. Only CI builds have write permissions in the server.

This is practically not doable since many of our packages come as prebuild binaries frequently from a private site of another company that only some have access to. So the way for us to do it is to export it to local cache and then upload the new version. I can't think of a way that using a CI server in the middle will be a net gain in any way.

I guess this is you trying to solve the problem the git is solving with a parent-child relationship in commits.

So since I can't find a good way around it let me just clarify one more thing. If you upload a package to the server the revision will get new timestamp when it arrives but when you download a package from a server you get the same timestamp the server has, so unlike in git the server is kind of an authority for that? What happens if you reupload an old revision to the server, will its timestamp refresh so now it's the newest again?

**Comment by memsharded** [comment]
> This is practically not doable since many of our packages come as prebuild binaries frequently from a private site of another company that only some have access to. So the way for us to do it is to export it to local cache and then upload the new version. I can't think of a way that using a CI server in the middle will be a net gain in any way.

Because that guarantees things are traceable and reproducible. If the download of the private site is encoded in a recipe, or even if it is directly encoded in the CI, it is somewhere. Next developer that comes to the team that needs to package the new binary from the other company will have an automated process to do it.

Still, I understand there are cases that it is more pragmatic to do it manually in your local computer and upload it.

> I guess this is you trying to solve the problem the git is solving with a parent-child relationship in commits.

> So since I can't find a good way around it let me just clarify one more thing. If you upload a package to the server the revision will get new timestamp when it arrives but when you download a package from a server you get the same timestamp the server has, so unlike in git the server is kind of an authority for that? What happens if you reupload an old revision to the server, will its timestamp refresh so now it's the newest again?

Yes, this happens because of the decentralized and distributed nature of the C++ builds, and the 1:N relationship between recipes and binaries. Imagine 2 different PRs with some different changes to the recipe that trigger some CI job, which will trigger different builds in different agents, lets say Linux and Windows agents. If the server is not an authority in the order of revisions, every time a new build finishes and get an upload, the timestamp of the local build will be used, in practice it makes the "last" available revisions to be continuously swapping between the 2 different PRs, and this creates lots of instability and issues. 
So uploading again an existing revision in the server will keep the existing revision with its initial timestamp, this behavior has proven to be the most stable and user-expected one.

**Comment by forry** [comment]
Fine, so now if I want to have the same timestamp I need to download the packages from the server. Or is there another way of doing that without evicting my entire cache? I just need to update a timestamp for revision which I already have. Is there a way to do just that?

(edit)
Also, on our server, the conan cache is not temporary but permanent to save resources. So the server would then face the same issue.

**Comment by memsharded** [comment]
Yes, I think a ``conan install ... --update`` after the upload will get the new timestamp from the server without needing to clean the package nor downloading anything.

**Comment by forry** [comment]
Many thanks!
