### ISSUE TITLE
[question] How to replace conanbuildinfo.cmake

### ISSUE THREAD

**Issue by diogomatos3** [conan-io/conan#17097]
### What is your question?

Hello community,

In my project, we still generate conanbuildinfo.cmake and run conan_basic_setup().
We would like to migrate and use CMakeToolchain and CMakeDeps instead.

But unfortunately, we get now several "No such file or directory" errors. So the path to the header files seems to be unknown. Something that conan_basic_setup() macro was covering.

How to proceed?

I am basically following https://docs.conan.io/en/1.64/reference/conanfile/tools/cmake/cmake.html#cmake

Thanks in advance.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @diogomatos3 

The important bit is the "generators". In your linked doc page, you can see:

```python
from conan.tools.cmake import CMake, CMakeToolchain, CMakeDeps

 def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()
        deps = CMakeDeps(self)
        deps.generate()
```
Because the recipe is using the new ``CMakeToolchain`` and ``CMakeDeps`` generators.
These generators are fully transparent, meaning that nothing should be added to the ``CMakeLists.txt``, so the ``include(conanbuildinf.cmake)`` and other related code must be removed.

When you remove them, things should work. 
You can see a full working example with the ``conan new hello/0.1 -m=cmake_lib`` template, that you can execute in an empty folder, then do ``conan create .``

**Comment by memsharded** [comment]
Hi @diogomatos3 

Any further question here? Thanks for the feedback.

**Comment by memsharded** [comment]
I am closing as responded, but please don't hesitate to reopen or create new tickets if necessary for any further question. Thanks for the feedback.
