### ISSUE TITLE
[question] package_id not found, hash different?

### ISSUE THREAD

**Issue by dwswingle** [conan-io/conan#17104]
### What is your question?

I have a package that has been successfully building with "--build=missing" argument. I'm opting not to use build missing for this particular package and use binaries that are already generated in artifactory. For some reason, this is missing:

![image](https://github.com/user-attachments/assets/c224a6ac-6646-4e86-8460-2fc65c83d5e2)

Here is where it's stored in Artifactory (first HASH is different):

![image](https://github.com/user-attachments/assets/ab771ab4-09b8-441b-9cd1-89cbf877bc48)

The "edb6c59d" first hash exists, but it contains another package (RelWithDebInfo, what I'm looking for is the Debug)

![image](https://github.com/user-attachments/assets/4233e1c9-aaec-479d-933c-e7a46978c869)

What could be causing this? Is there more context I need to give? Thanks!

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @dwswingle 

Thanks for your question.

That first hash is the ``recipe_revision``:  https://docs.conan.io/2/tutorial/versioning/revisions.html

It changes when there is any change to the recipe. This can happen for example:
- If doing a git checkout in Windows with different LF: https://docs.conan.io/2/knowledge/faq.html#error-obtaining-different-revisions-in-linux-and-windows
- If the recipe has some ``exports`` or ``exports_sources`` that includes local changes files, like temporary files

It is possible to compare what has changed between 2 revisions by getting the ``conanmanifest.txt`` that is inside the ``export`` folder and doing a diff.

In your case it is possible that there was some subtle difference between the recipe revision that created some configs like RelWithDebInfo and the recipe revision  that creates the Debug config.

Please let me know if this helps.

**Comment by dwswingle** [comment]
Ah. I was looking at only the conaninfo.txt. Let me look at the manifest to see if there are differences.

**Comment by memsharded** [comment]
Make sure to check the manifest in the ``export`` folder, not the one inside the ``package`` folder.

**Comment by dwswingle** [comment]
It looks like some wires are crossed somewhere. the manifest is showing RelWithDebInfo when I would be expecting to see Debug lines instead for the build directory. About to walk through the cmakelists/conanfile to see where something could be going wrong.

**Comment by dwswingle** [comment]
Another thing that may be worth mentioning. The second and third screenshots are **two different** conan remotes. The second screenshot is "conan-prod" and the third is "conan-sandbox". "conan-prod" is above "conan-sandbox" on the remote list (i believe order matters).

**Comment by memsharded** [comment]
If we are talking about different remotes, it seems this could be something in the process.

The issue is not that much the specific configuration if Debug or not, but the fact that the ``recipe-revision``, which should be the same for the same sources for all different configurations, is not the same. Not sure what ``conanmanifest.txt`` are you checking, but it should be a list of source files with their checksums, but it is a bit surprising that they contain anything related to Debug or RelWithDebInfo, because those things are specific to the specific binaries, not to the source code, which should be the same and common to both Debug and RelWithDebInfo binaries.

**Comment by dwswingle** [comment]
example of what I'm seeing in the manifests:

![image](https://github.com/user-attachments/assets/27e521f8-5e26-45d1-99ab-ad8224e1176f)

**Comment by memsharded** [comment]
Ok that explains this. The ``exports_sources`` seems to be incorrect.
You are exporting as "source" the temporary build files you have locally.
You need to make sure that the exported files are exclusively the ``.cpp``, ``.h``, ``CMakeLists.txt`` and source files, but not binaries.

Check for example the behavior of the ``conan new cmake_lib -d name=mypkg -d version=0.1``. No matter what you have locally, like a local "build" folder, the exported ``recipe_revision`` will always be the same because such "build" folder is not exported.

**Comment by dwswingle** [comment]
oooooof I think I get it. I have some wildcards in exports sources that I think I need to remove.

**Comment by dwswingle** [comment]
I had a *.cmake wildcard that was pulling all of those files in. I will rerun everything and open a new question if I need to ask additional. thank you!

**Comment by memsharded** [comment]
Happy that we identified the issue.
Thanks for the feedback!
