### ISSUE TITLE
[bug] Conan is not propagating cxxflags to dependencies

### ISSUE THREAD

**Issue by quantbox-will** [conan-io/conan#17149]
### Describe the bug

I'm trying to build a project with conan2 and I want to build my dependencies with certain compiler flags (e.g. -march or -fsanitize=...).
I've tried setting
```
tools.build:cflags=["-march=znver2", "-mno-hle"]
tools.build:cxxflags=["-march=znver2", "-mno-hle"]
```
In the profile I'm configuring for and adding `tools.info.package_id:confs=["tools.build:cflags", "tools.build:cxxflags", "tools.build:exelinkflags", "tools.build:sharedlinkflags"]` to the `global.conf` file. It doesn't seem to be rebuilding the dependencies though: Running the command `conan install -of build -pr:a path/to/profile --build=missing conanfile.py` results in existing artefacts being picked up (even when I put a meaningless cxx flag in the profile, which should cause compilation to fail)

**Comment by memsharded** [comment]
Hi @quantbox-will 

Thanks for your report.

First, let me try to suggest that this approach might not be the most recommended one for the majority of cases. For most cases, it is better to build an abstraction over a set of flags with some custom ``settings``, by defining your own in ``settings_user.yml``. That helps much better in tracking and modeling things.

Second suggestion is not using the same profile for both build and host context with ``-pr:a path/to/profile`` , specially if defining special builds with sanitizers, etc, unless you want to build things like ``cmake`` itself with sanitizing.

Can you please do a quick check?:

```bash
$ conan new cmake_lib -d name=pkg -d version=0.1
$ conan create . -tf=""``  & ``conan list "pkg:*"
$ conan create . -tf="" -c tools.info.package_id:confs="['tools.build:cxxflags']" && conan list "pkg:*"
$ conan create . -tf="" -c tools.info.package_id:confs="['tools.build:cxxflags']" -c tools.build:cxxflags="['/GA']" && conan list "pkg:*"
```

NOTE: You might need to adapt the flag, /GA is for windows.

```bash
$ rm -rf *
$ conan new cmake_lib -d name=app -d version=0.1 -d requires=pkg/0.1
$ conan create . -tf="" && conan list "app:*"
$ conan create . -tf=""  -c tools.info.package_id:confs="['tools.build:cxxflags']" && conan list "app:*"
$ conan create . -tf=""  -c tools.info.package_id:confs="['tools.build:cxxflags']" -c tools.build:cxxflags="['/GA']" && conan list "app:*"
```

And now:
``` bash
$ conan create . -tf=""  -c tools.info.package_id:confs="['tools.build:cxxflags']" -c tools.build:cxxflags="['/GL']" && conan list "app:*"
```

This will fail with ``Missing prebuilt package for 'pkg/0.1'`` because it sems to be working fine. Then repeat with ``--build=missing`` and it will work.

With this, it seems that it is working fine, can you please check it?

**Comment by quantbox-will** [comment]
Ah, I see. I was adding the cxxflags to the `settings` section of the profile. I didn't realise the `conf` section existed. I've fixed that now and it appears to be working. Thank you for all of your help!

**Comment by memsharded** [comment]
Great, happy to help, thanks for the feedback!
