### ISSUE TITLE
[question] conan cache clean

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#17158]
### What is your question?

Dear Conan Folks,

We use Windows mainly.
Sometimes the conan cache has GB's of data and needs to be deleted manually.
There is a command:
'''
conan cache clean *
'''
Doesnot seem to delete the contents of the p folder.
Or am I using the wrong way?
My expectation is that the .conan2 folder is cleaned up from all the downloads and locally generated packages.

Thanks!
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @maitrey thanks for your question.

You might be looking for the `conan remove` command ([docs here](https://docs.conan.io/2/reference/commands/remove.html)), which is meant to remove the packages in your local cache, and it supports patterns to control which ones, and useful filters such as the `--lru` flag to remove packages not used since a certain time.

Note that the `conan cache clean` as documented [here](https://docs.conan.io/2/reference/commands/cache.html#conan-cache-clean) is meant to remove temp files from Conan, such as the downloaded source files, build folders etc.

Let me know if this helps :)

**Comment by maitrey** [comment]
Thank you! It helps!

**Comment by AbrilRBS** [comment]
Great to hear! Closing this as solved, but feel free to create new issues if you have any additional question, thanks!
