### ISSUE TITLE
[question] How to publish mulitple package in parallel? 

### ISSUE THREAD

**Issue by barnou-psee** [conan-io/conan#17211]
### What is your question?

Hello, in our CI we're building for different profiles and we're uploading them. Each profile is built in parallel and when published it happens that the upload steps doesn't see the recipe uploaded but when uploading it, another profile have done it already. How do you handle those cases? I saw there is a `--only-recipe` option that can be used to upload only the recipe, is there an opposite? liks `--only-package` maybe? Is it the objective of the `-p` option? 

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @barnou-psee 

Thanks for your question.

This is indeed a known issue, we have this ticket to track it: https://github.com/conan-io/conan/issues/16703
As you can see there, it is labeled as "complex:huge", because it is mostly a server-side issue, and that can be challenging and require time.

>  I saw there is a --only-recipe option that can be used to upload only the recipe, is there an opposite? liks --only-package maybe? Is it the objective of the -p option?

I think you are close to what would solve it.
As Conan has checks to avoid uploading things that are already in the server, it is possible to do the following:
- First upload with ``--only-recipe`` in a single job, all the relevant recipes. The recipes are the ones that might case race conditions if uploaded concurrently at the very same time
- Then, once the recipes are there, you are good to upload concurrently all the packages. As the recipe is already there, Conan will know it and will not re-upload again, so not producing race conditions.

There could be other possible related approaches:
- use the ``conan cache save/restore`` together with Conan package-lists, to gather everything in CI side, then do a single upload with the recipe plus all the binaries, in a single job
- retry the upload when failed. If it is due to race conditions, basically the next retry in a few seconds will manage to work fine. This is not a very elegant approach but works relatively well in practice, we have seen users doing this with success (still some of the above would be recommended, this could be like a quick temporary workaround in existing pipelines, as the above might take a bit more to implement)

**Comment by strattist** [comment]
Thanks a lot for your quick answer! I'll watch the future releases then. Do you have CI examples on this issue, preferably using Github Action but any other CI tool will do?

**Comment by memsharded** [comment]
Hi @barnou-psee 

Did the above help? Please let us know if you have any further question or issue. Thanks for the feedback!

**Comment by barnou-psee** [comment]
Hello @memsharded I'm sorry I haven't answered. I chose the retry option. Your suggestion using the `--only-recipe` options wasn't an option to me since it would complexify my CI. While a simple retry seem to always work. I didn't have any issue with that. This is what I've done using [this action](https://github.com/nick-fields/retry): 

```
      - uses: nick-fields/retry@v3
        if: |
          github.event_name == 'push' &&
          github.ref_type == 'tag'
        with:
          timeout_seconds: 60
          max_attempts: 3
          retry_on: error
          command: conan upload X -r=Y
```

**Comment by memsharded** [comment]
Thanks for the feedback, glad to know that this approach is working, as I suggested above this indeed seems a very simple and pragmatic approach that works pretty well.

I think we can close this ticket then, and for future improvements over this, you can track ticket https://github.com/conan-io/conan/issues/16703. Thanks!
