### ISSUE TITLE
[bug] fail  while  compiler xz_utils

### ISSUE THREAD

**Issue by rodingbao** [conan-io/conan#17229]
### Describe the bug

```
xz_utils/5.4.5: ERROR:
Package '0534efa715363b456efc91df5dd071bc6eefb323' build failed
xz_utils/5.4.5: WARN: Build folder C:\Users\rodin\.conan2\p\b\xz_utc88b6dccd7411\b\build-release
ERROR: xz_utils/5.4.5: Error in build() method, line 156
        autotools.make()
        ConanException: Error 2 while executing
```

os: windows11
complier: msys2 mingw 
conan: 2.0
profile:
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=14
os=Windows

**Comment by memsharded** [comment]
Hi @rodingbao 

This might not be a Conan issue, but a ConanCenter issue.
ConanCenter does not build and test recipes for MinGW, but in Windows, only for ``msvc`` compiler. In general it is recommended to use the ``msvc`` compiler, as support for MinGW in ConanCenter might vary, there are user contributions to try to support it but it is not as tested as guaranteed as for ``msvc``.

Otherwise we would need more details.
I have just tried with:
```
conan install --requires="xz_utils/[*]" --build=xz_utils* -pr=profile
```
with  my profile:
```
[settings]
os=Windows
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++11
build_type=Release
arch=x86_64

[buildenv]
PATH+=(path)C:/ws/msys64/mingw64/bin

[conf]
tools.microsoft.bash:subsystem=msys2
tools.microsoft.bash:path=C:/ws/msys64/usr/bin/bash
```
And it worked. My setup:
- Latest Conan 2.8.1 in Windows 11
- Running from a Windows cmder terminal (not msys2, important)

**Comment by rodingbao** [comment]
it works. thank you.
