### ISSUE TITLE
[question] Prevent download of headeronly and tool_requires

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [conan-io/conan#17239]
### What is your question?

Hi!

 i wanted to build everything from source as per my company's policy.
i already read  #12441 and #12414

which lead me to add a subsettings in "Linux" and "Windows"
```yml
download: [null, artifactory]
```
and in my profile
```toml
os.download="artifactory"
```

sadly adding this settings still generate a lot of download such as pocketff, meson, autoconf, automake...

idealy i would want only recipes to be downloaded.

im using conan 2.8.1.

ideally i would want a flag like in conan download --recipe-only.

Best regards,
Marc barbier.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Marc-Pierre-Barbier 

Thanks for your question.

I am not sure if I understood the issue.
If you are using packages from ConanCenter, indeed the majority of organizations using Conan will not download binaries from ConanCenter, but use their own built binaries. To use packages from ConanCenter the recommendation is: https://docs.conan.io/2/devops/using_conancenter.html

- Do not use ``conancenter`` as remote
- Work directly from the sources, from the ``conan-center-index`` Github repo
- Build your own binaries from there, upload them to your own private server

With this flow, it is not an issue, because no binaries are downloaded from ConanCenter because ConanCenter is not a remote at all. The subsetting doesn't look like the best approach for this issue.

Please let me know if this makes sense.
