### ISSUE TITLE
[question] How to use a package as build and normal requirement with different settings

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#17243]
### What is your question?

I have a question regarding how to handle package IDs for packages that are used as a lib and as a tool in different scenarios. My example: thrift (see https://github.com/conan-io/conan-center-index/blob/master/recipes/thrift/all/conanfile.py). It includes a tool (code generator) to be executed and a lib to link against.

This is the package info of the thrift package:
```sh
$ conan list thrift/0.20.0:*
Local Cache
  thrift
    thrift/0.20.0
      revisions
        560fdab2e1636d4d8a0556fcf6470b89 (2024-08-14 16:22:07 UTC)
          packages
            8d034f2c26289df8b03a42bd251f0aeb658fe163
              info
                settings
                  arch: x86_64
                  build_type: Release
                  compiler: gcc
                  compiler.libcxx: libstdc++11
                  compiler.version: 12
                  os: Linux
                  os.glibc: 2.35
                options
                  fPIC: True
                  shared: False
                  with_c_glib: False
                  with_cpp: True
                  with_haskell: False
                  with_java: False
                  with_libevent: True
                  with_openssl: True
                  with_python: False
                  with_qt5: False
                  with_zlib: True
                requires
                  boost/1.85.0#3add30047e4245e29efe86ba14014e76:da39a3ee5e6b4b0d3255bfef95601890afd80709
                  libevent/2.1.Z
                  openssl/3.3.Z
                  zlib/1.3.Z
```

My problem is that what people have in their build profiles can be somewhat different (e.g. no `compiler` setting or a different version) so it is kind of difficult to provide a thrift package for all possible combinations. IMO the correct way would be to get rid of all options and settings in the package ID that don't have an impact of using thrift as a build tool (as described [here](https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/tool_requires_packages.html#removing-settings-in-package-id)).

How would this situation be handled correctly? I'd need the "normal" thrift packages depending on my host profile but only one or two thrift packages (Linux, Windows) to use it as a tool in my build context. Is it a "bug" in the thrift conanfile that the package ID is not set correctly for using it in the build context or is this a limitation of Conan?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @fschoenm 

In general this is not an issue. The default ``build`` profile in most cases is a profile auto-detected with ``conan profile detect`` or a quite standard one, using the normal compilers in the platform. Because not everything is a cross build, so having a ``default`` profile with more than the ``os`` and ``arch`` should be the default in most cases, then there will be enough information to retrieve the thrift package that you need.

This is the same case as ``protobuf``, as documented in this example https://docs.conan.io/2/examples/graph/tool_requires/using_protobuf.html.

This wouldn't be considered a bug in the thrift conanfile, it is not mandatory for packages in ConanCenter to optimize the usage as ``tool_requires``, and in the vast majority of cases the default works well enough, and if anything happens the approach is to use a default profile with the standard compiler/arch/build_type information.

If you need to further optimize this, it might be possible to create packages to be used as "tool-requires" with stripped ``package_id`` requirements. For example, by conditioning in the ``package_id()`` method on the ``self.context == "build"``, or by adding a new option called ``is_tool``, that could be activated in the "build" profile to leave the binary depending on just ``os`` and ``arch``

**Comment by fschoenm** [comment]
@memshared Thanks for the quick answer. 

We have developers with different compiler versions, depending on their system, e.g. GCC versions between 10 and 14. Does that mean that in this case I would have to hold available the thrift package for all these compilers? (We're only using it in embedded projects so the lib dependency is always going to be an ARM package and cannot be used as code generator.)

**Comment by memsharded** [comment]
> We have developers with different compiler versions, depending on their system, e.g. GCC versions between 10 and 14. Does that mean that in this case I would have to hold available the thrift package for all these compilers? (We're only using it in embedded projects so the lib dependency is always going to be an ARM package and cannot be used as code generator.)

Depending on what you need, it might be the most pragmatic approach. Building thrift for different compiler versions, for example if you have some docker images it relatively trivial. As this package probably don't change that often, it might be minimally disruptive, very cheap and simple.

If you really need to optimize this, it might be doable with either the approach above, customize the ``package_id()`` (this most likely is overkill for ConanCenter, so not expected to be there), or you can also do a ``compiler.version`` fallback for this package in the ``compatibility.py`` with a few lines. Probably this second approach is most effective and less intrusive, not requiring changes to recipes.

**Comment by fschoenm** [comment]
@memsharded I see, thanks for taking the time to answer. The `compatibility.py` way seems like a good idea, maybe I'll try that approach as we're already using that for different use cases.

**Comment by memsharded** [comment]
Sounds good. Recall that you might want to check ``conanfile.context`` to only provide fallback for the "build" context, but keep strict compiler.version match for the host context.

If there are no further question, I think we might close this issue, you can re-open later or create a new one for any further question about the ``compatibility.py`` or any other issue.
