### ISSUE TITLE
conan packages revision

### ISSUE THREAD

**Issue by danielhalati** [conan-io/conan#17255]
### What is your question?

Hello, 

I have another question regarding conan revisions. I enabled recently revisions and lockfiles in order to achieve package immutability.

What I am experiencing now is that I am building and packaging the same library but I see a new package generated. This is how revisions are supposed to work?

My initial guess was that a new package will be generated if the contents change

e.g I am building boost 3 times -> I see 3 packages in artifactory

The thing is that I am building it 3 times from different docker containers and from different folder location. Can this have an impact?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @danielhalati 

The issue is that most C++ builds are not deterministic. So building the exact same thing will results in slightly different binaries that have different checksums (then different package-revisions), even if the recipe-revision and package-id is the same.

The approach to avoid this is to use ``conan create . --build=missing``. This will not re-build an existing binary that already exists, being more efficient while being safe as the ``recipe-revisions`` and ``package-id`` already account for source-code variability and configuration variability respectively.

You can read more about it in https://docs.conan.io/2/tutorial/versioning/revisions.html#package-revisions

**Comment by danielhalati** [comment]
Thanks for the reply. But I am not using conan to build from sources. I am packaging existing prebuilt binaries. 

Is there a way I can work with this ?

**Comment by memsharded** [comment]
> Thanks for the reply. But I am not using conan to build from sources. I am packaging existing prebuilt binaries.

But you are rebuilding from source the same things externally to conan, or you are given by some other vendor those binaries?

If the binaries are just different for the same version, they will mean new ``package-revisions`` indeed. This is not great, because it means there is some un-modeled variability that Conan is not aware of and then cannot correctly model. If you are given new binaries, then they should have a new version, not produce a new package-revision. What is the case of getting new binaries for the same thing repeatedly?

**Comment by danielhalati** [comment]
I am building the binaries with the help of some in house scripts. The binary is exactly the same. 

I discovered this behaviour while running repeated tests. 

As mentioned in the 1st comment, when building the binary is some other folder I get a new revision

If I rebuild on & on in the same folder I don't get new revision. Maybe the compiler is inserting something path dependant in the binaries

**Comment by memsharded** [comment]
> I am building the binaries with the help of some in house scripts. The binary is exactly the same.

Is the binary exactly the same, bit by bit? This only happens for deterministic builds, but it is challenging to achieve them in the general case.
If the binary is exactly the same, then the resulting ``package-revision`` should be the same. If it is not, it is because some other file that you are packaging is different.

> As mentioned in the 1st comment, when building the binary is some other folder I get a new revision

> If I rebuild on & on in the same folder I don't get new revision. Maybe the compiler is inserting something path dependant in the binaries

Yes, exactly, one of the sources of non-determinism is the compiler embedding some full paths in some binary artifacts, so the built binaries are not really deterministic.
