### ISSUE TITLE
[question] if I have copied a file using a pre export hook to the export folder and then deleted it using a post build hook does this file contribute to the calculation of the Recipe Revision ?  

### ISSUE THREAD

**Issue by M0rtalPhe0nix** [conan-io/conan#17298]
### What is your question?

I have a use case where I am considering using hooks to copy a file that contributes to the build but I don't want it to be a part of the exports or the exported sources or the package. so I considered using a pre export hook that copies the file to the export folder and use a post build hook to delete the file . but I wanted to validate that this file wont be a part of the Recipe Revision calculated as I don't want this package to be forced to be build from sources (as I am not packaging this file).

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @M0rtalPhe0nix 

Yes, everything that is exported gets into the ``recipe-revision`` computation.

May I ask the use case for this? Maybe you want to put it into the ``recipe-metadata`` folder instead, that is not used for the recipe-revision computation? 
The problem is that if it contributes to the build, then it should be part of the ``recipe-revision``, otherwise you could be having different sources without really having different sources, and that breaks the revisions system assumption, this is why I am asking about the use case.
