### ISSUE TITLE
[question] How to trigger a rebuild of all packages when updating the cross-compilation sysroot

### ISSUE THREAD

**Issue by JKniep** [conan-io/conan#17320]
### What is your question?

We are using a toolchain for cross-compiling as described in https://docs.conan.io/2/examples/cross_build/toolchain_packages.html, with the only notable difference that we have an additional conan package for the cross-compilation sysroot. We use it pretty much the same like the toolchain.

The toolchain and sysroot are referenced in our conan profile for the target as [tool_requires], and the compiler version of the toolchain is given in the settings:

```
[settings]
arch=armv7
...
compiler.version=7.3

[tool_requires]
arm-toolchain/13.2
arm-sysroot/13.2
```

When we receive an updated toolchain from our supplier, we update the arm-toolchain version in the profile (in the tool_requires section), and typically, we then also update the compiler.version. In this case, conan will generate a new package id because of the changed settings, and all conan packages will be rebuilt automatically with the new toolchain as soon as we use the new profile. But if we just update the sysroot (e.g. bump arm-sysroot to 14.0 in order to address vulnerabilities of system libs), conan will re-use existing packages that have been built against the older sysroot, which often doesn't work.

Now we could add a custom setting like sysroot.version (similar to the existing sdk_versions e.g. for iOS), and update it every time we update the sysroot. But I feel this not enough, because it may easily be forgotten to update sysroot.version. Would you rather recommend to somehow add a check for sysroot.version (maybe using profile.py?), or is there some way to reflect tool_requires in the package id? I know this is possible for configurations via tools.info.package_id:confs, but I didn't find any equivalent for tool_requires.

I am using conan 2.2.2 on Ubuntu 20.04.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @JKniep 

Thanks for your question.

There are indeed several mechanisms in Conan to make the ``tool_requires`` affect their consumers ``package_id``.

- You have a default ``core.package_id:default_build_mode`` conf that you can set: https://docs.conan.io/2/reference/binary_model/custom_compatibility.html#global-default-package-id-modes This will apply to all ``tool_requires``, not sure if this is what you are looking for, or it is too much. 
- At a higher level, it is possible to affect the ``package_id`` of all packages that use a given configuration version, see the docs on https://docs.conan.io/2/reference/commands/config.html#conan-config-install-pkg (still experimental) including the ``core.package_id:config_mode``

> Now we could add a custom setting like sysroot.version

If you define for example the ``sysroot`` as a sub-setting of ``compiler``, and you don't allow and empty value (by not providing ``null`` in the ``settings_user.yml``) then it will complain if profiles don't define it.
If this is not possible in general, because you have cases not using sysroot for the same compiler, then it is likely that a check in the ``profile.py`` plugin, conditioned to the logic you have to know which scenarios use a sysroot, and raising if the sub-setting is not defined, as you suggest, that could also be a good solution.


Please let me know if this helps.

**Comment by memsharded** [comment]
Uhm, this is interesting.
It seems Conan already has the ``build_mode`` attribute in the codebase, same as https://docs.conan.io/2/reference/conanfile/attributes.html#reference-conanfile-attributes-package-id-modes, but for ``tool_requires``, but it is not documented yet.  You can try it, defining it in your ``sysroot`` recipe, and checking if it becomes part of the consumers of that package. Maybe it is time to make this public.

**Comment by JKniep** [comment]
Hi @memsharded, thanks, good to know that we have so many options. Probably we won't change the `core.package_id:default_build_mode`, because we have quite a lot of tools_requires which don't require a rebuild, but it's still good to know that this is possible. We'll need to experiment a bit with the `core.package_id:config_mode` to fully understand it, but from my point of view, you can already close this issue. Thank you.

**Comment by memsharded** [comment]
But the most important one, have you experimented with the ``build_mode = "xxxx"`` attribute in your toolchain recipe? That will allow to define the effect directly in the recipe you want.

As commented above, this is not documented, but it is there, so if working fine and with your feedback, it might be the necessary push to document it.

**Comment by JKniep** [comment]
Thanks, we'll try that, but it'll take some time. I'll update this ticket when we are ready.

**Comment by memsharded** [comment]
Sounds good. I'll close the ticket in the meantime, as it doesn't require any further action from us, but please re-open it or create a new ticket if you have any further feedback or question. Thanks!

**Comment by JKniep** [comment]
`build_mode = "full_mode"` works like a charm :-)

**Comment by memsharded** [comment]
Excellent, happy to know @JKniep 

As a possible hint, please recall that selecting a different mode, like ``minor_mode`` you will have better control of when packages need to re-build, so you can do patch releases to the toolchain without requiring consumers to rebuild and when you want them to force the rebuild you bump the minor of the toolchain. So more control.

Thanks for the feedback!

**Comment by myzb** [comment]
The `build_mode` attribute is exactly what I was looking for as well. It was hard to find since it's named differently than the other `package_id_*_mode` attributes.

@memsharded I would like to add my vote to have this attribute added to the doc's. :)

---

I'll add a few details to our use-case for this in case it helps others. 

We are packaging an SDK for an embedded device and that SDK contains the compiler tools as well as the libraries. Different teams use the toolchain to develop their own apps, which are then delivered as conan packages to a central repo. That central repo is responsible for creating the flashable image for the embedded device, in addition to some core system apps. Due to the libs/headers in the SDK, as well as some traceability needed regarding the used build tools, we had to prevent people from using the wrong SDK by mistake. 

We were considering splitting the SDK into build and host package (like the protobuf example), but
1. We wanted to keep that externally delivered SDK "unmodified" in the sense as being one single directory.
2. Did not want each toolchain consumer having to push (or forget to push) an updated package/recipe to our internal remote.

We settled for deploying a centralized conan config (settings, profiles, etc.), which also would give the flexibility to trigger package updates once the "tool_requires" changes, without needing the package owner's intervention.

This is what we've now come up with:

```py
class ConanPackage(ConanFile):
    name = "my-toolchain"
    version = "1.0.0"
    build_mode = "major_mode"

   # rest as the toolchain example from conan-io
...
```

And a consumer then gets the info embedded like so:
```
conan list "my-app:*"
Found 1 pkg/version recipes matching my-app in local cache
Local Cache
  my-app
    my-app/1.0.0
      revisions
        e89b72a36317a374aff4f118694fe1f2 (2025-02-05 08:18:17 UTC)
          packages
            e378b1e80ae9d9cbb0f1883f00a510e9a4e2e0e7
              info
                settings
                  arch: armv8
                  ...
                build_requires
                  my-toolchain/1.Y.Z
```

**Comment by memsharded** [comment]
I have opened https://github.com/conan-io/docs/issues/3979, assigned to the "2" milestone list of pending things in the docs, hopefully we can dedicate some time soon to this backlog.

Thanks very much for the feedback @myzb !
