### ISSUE TITLE
Speed-up "conan list" with wildcards

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan#17356]
Hello fellow Conanators!

I have a project where the conanfile.py has `revision_mode = "scm"`.
Our pipeline produces conan packages whenever required.

The workflow is that sometimes an consumer project has a commit hash in hand and need to translate that to a conan pakcage name.
I can do this by executing `conan list "mypackage/*#[commit_hash]` as the recipe revision is indeed the commit hash......but it takes several minutes for conan to resolve it. At the moment it finds 276 packages to iterate through, and that number will just keep growing:

```
Found 276 pkg/version recipes matching mypakcage/* in my-remote
Listing revisions of mypackage/1.0.85in my-remote (9/276)
Listing revisions of mypackage/1.0.94 in my-remote (18/276)
...
Listing revisions of mypackage/1.2.3 in my-remote (269/276)
my-remote
    mypackage/1.2.3
      revisions
        aabbccddeeff112233445566778899 (2024-11-19 17:44:24 UTC)
```

Is there a way to speed it up...or is there some alternative method to resolve the package name from a recipe revision?

Regards
Klaus

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @klausholstjacobsen 

Thanks for your question.

This is intrinsically slow, because the conan protocol does 1 api call to the server per package version. This is extremely difficult to change, the protocol with the server takes a lot of time to evolve.

As a first initial idea I would suggest the following:
- Do a custom command that does the following
- First do a ``conan list mypkg/*``, without the revision, this will be much faster
- Then iterate the versions returned in reverse order. My experience is that this will faster for 2 reasons:
   - when looking for such a commit, this typically is relative new, so it will be in newer versions
   - it can stop when it finds the occurence. The conan protocol will always iterate all versions looking for all matches

**Comment by klausholstjacobsen** [comment]
You saved the day....again!

Thanks

**Comment by memsharded** [comment]
Thanks for your feedback!

If that isn't enough, please re-open or create a new ticket. I think it might be possible to try other alternatives, like doing an advanced AQL to the Artifactory API, for example.

**Comment by klausholstjacobsen** [comment]
Yeah, I was going down the path of "curl"ing my way through the artifactory folders.
Now that would be an ugly child wouldn't it :-)
