### ISSUE TITLE
[question] Conan Cache Clean

### ISSUE THREAD

**Issue by Vasile-Creuco** [conan-io/conan#17375]
### What is your question?

Hello everyone,

I wanna remove all packages from time to time from "p" folder which is located in "C:\Users\UserName\.conan2" and I need the correct command because I wanna implement in a script which will do automatically. Don't want to do it manually.
I tried `conan cache clean` command but it didn't remove anything. What is the correct command to remove all folders (packages)?

Thank you!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @Vasile-Creuco thanks a lot for your question.

The command you're looking for is `conan remove` ([docs here](https://docs.conan.io/2/reference/commands/remove.html)), which is used to remove actual packages from your Conan cache, while on the other hand, `conan cache clean` is used to remove temporary cache files, such as build and source folders of previous compilations (Although I understand where the confussion comes from due to the command names!)

Some comments on `conan remove`:

* You might find useful to remove only packages you haven't used in a while. For that, you can use the `--lru` argument, such that for example `conan remove * --lru=4w` will remove everything not used in the last month
* You can also remove old revisions of recipes and their corresponding binaries, which if updates are frequent for your recipes, can save also lots of spaces without removing useful, currently-in-use packages, with the `conan remove *#!latest` syntaxt

Let me know if this helps :)

**Comment by Vasile-Creuco** [comment]
Yes, it works.

Thanks a lot for your help @AbrilRBS!
