### ISSUE TITLE
How to resolve dependency conflict from two packages in Conan version 2.9.1

### ISSUE THREAD

**Issue by qashoou** [conan-io/conan#17383]
### What is your question?

I am using two packages, one of which uses fmt/11.0.2 and the other uses fmt/10.2.1.
`ERROR: Version conflict: Conflict between fmt/10.2.1 and fmt/11.0.2 in the graph.
Conflict originates from spdlog/1.14.1`
In conan 1.x, I would just simply override it by adding fmt/11.0.2 in my conanfile.txt. but I am unable to do it now.
how to accomplish the same on conan 2.9.1?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @qashoou 

Thanks for your question.

There are different possibilities in Conan 2 to solve conflicts:

- First and recommended one is try to align on the recipes themselves, use consistent version ranges, etc. If the recipes come from ConanCenter, feel free to report these conflicts, we are gradually introducing version ranges in ConanCenter and aligning them to reduce conflicts
- To solve conflicts from recipes, ``conanfile.txt`` is not enough, because in Conan 2 conflict resolution needs to be explicit. So the recommendation is to use a ``conanfile.py`` and add a ``self.requires(dep, override=True)`` (or use the new ``force=True`` requirement trait to define that it is both a direct dependency and an override)
- To use the new ``[replace_requires]`` section in the profile to force the replacement of the packages you want, see https://docs.conan.io/2/reference/config_files/profiles.html#replace-requires

Please let us know if this helps.

**Comment by qashoou** [comment]
Thanks mate. 
I figured it out myself last night after banging my head against the conanfile.txt for a very long time :D

**Comment by spjuanjoc** [comment]
This issue helped me solve the error:
```console
ERROR: Version conflict: Conflict between flac/1.4.2 and flac/1.4.3 in the graph.
Conflict originates from libsndfile/1.2.2
````

By setting the override=True in the conanfile.py
```python
from conan import ConanFile
from conan.tools.cmake import cmake_layout


class ExampleRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps"

    def requirements(self):
        self.requires("fmt/11.2.0")
        self.requires("imgui-sfml/2.6.1")
        self.requires("opencv/4.11.0")
        self.requires("flac/1.4.2", override=True)

    def layout(self):
        cmake_layout(self)
```

I wonder if there is a new way to do this in a text `conanfile.txt`
@memsharded do you know if this is now possible?

**Comment by memsharded** [comment]
Hi @spjuanjoc 

No, it is not possible to resolve conflicts with ``conanfile.txt``. Conan 2 requires conflict resolution to be explicit, and the ``conanfile.txt`` doesn't have a syntax to do that, and inventing some new text-based syntax for this is too much, this is why Python is recommended for this.

What might be possible is to use ``[replace_requires]`` in the profile as a temporary resolution.

Note that in both cases, this should be considered a temporary fix, in general the number of ``override/force=True`` should tend to zero. The recommended solution is to update the version requirements upstream to converge.
