### ISSUE TITLE
[question] Conan 1 and Conan 2 package coexistence in Artifactory for header-only packages?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#17392]
Hi,

our company is running on-premise Artifactory 7.98.7. We are migrating to Conan 2, but bumped into an issue.

I have:
* Conan 1.65.0 and Conan 2.5.0 installed
* default_package_id_mode = semver_direct_mode + revisions_enabled = True in my Conan 1 conan.conf
* core.package_id:default_non_embed_mode = full_mode in my Conan 2 global.conf

I have a package that:
* doesn't have any 'scm' in it
* it has self.info.clear() in its package_id

Currently two different package ids are generated: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 for Conan 1 and da39a3ee5e6b4b0d3255bfef95601890afd80709 for Conan 2.

It appears that if I upload first the Conan 1 version and then the Conan 2 version, I can't build Conan 1 anymore, 5ab8...
is not found by Conan 1 anymore

Any idea?
Thanks,

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment]
Hi @harsszegi.

This might be a case of the Conan 2 recipe having a different _recipe revision_ than when being built in Conan 1. Recall that Conan 1 & 2 share the recipe revisions, but not the package ids.

What is most likely happening is any of:
- In any of the versions, you're modifying the recipe in a way that the other is not. The most common case is `conandata.yml` trimming of versions by a post-export hook in any of the versions
- Another usual suspect is for recipe revisions to be different because one might be created in a system with different line endings than the other, generating a different hash for the file, see here for more information https://docs.conan.io/2/knowledge/faq.html#error-obtaining-different-revisions-in-linux-and-windows

Those are just some tips to look out for, as this is not an issue we expect to happen otherwise,  as Conan Center Index was running for close to 2 years following the same approach of having the same recipe revision for Conan 1 and 2 packages

**Comment by harsszegi** [comment]
Understood, thanks I’ll keep on digging
