### ISSUE TITLE
[feature] Propagate runenv section to CMAKE_VS_DEBUGGER_ENVIRONMENT in CMakeToolchain

### ISSUE THREAD

**Issue by softgate-fabian-guenther** [conan-io/conan#17418]
### What is your suggestion?

Hi i have a library where I use conan for most of my dependencies. Recently we have introduced a proprietary library dependency with a closed source that we only have as a binary package. The library supports cmake find_package integration, so it is quite straight forward. 

We develop mainly on Windows using the Visual Studio generators of conan. For running the application, we use the VirtualRunEnv, which we "inject" the libraries bin folder for finding dlls at runtime using the our profiles [runenv] section like this:

```ini
[runenv]
PATH+=(path){{ os.path.normpath(os.path.join(profile_dir, os.path.normcase("../../external/LibraryName/x64-Release/bin"))) }}
```

Using the gnerated `conanrun.ps1`  before executing the built executable works fine and is able resolve all dlls, however, when running from the IDEs Debugger, the application is unable to resolve our external dependencies. This looked weird to me and I investigated some more and found out, that the CMAKE_VS_DEBUGGER_ENVIRONMENT variable set in the conan_toolchain.cmake did not contain our injected path. Is it possible to include the path here aswell without having to manually extract it from the VirtualRunEnv.environment() and insert it into the CMakeToolchain in our conanfile.py?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @softgate-fabian-guenther 

Thanks for your report.

To see if I understood it correctly: you have some pre-compiled library, and you created a Conan package from it, that you are using together with other dependencies in your visual studio project (consumer is using CMake, and using the Conan CMakeToolchian generator). 

And then you don't see the path of your library? That is unexpected. Maybe if you can share the ``conanfile.py`` you are using to package that library, that could help.

**Comment by softgate-fabian-guenther** [comment]
Hey @memsharded, thanks for the quick answer

The pre-compiled library is just located in a folder in my repository, not a conan package, but comes with it's own FindPackage config for cmake, but apart from that is only a lib, include and bin folder (the latter containing multiple dlls required for running)

I am not sure how much I can share, as our project is proprietary. I think the relevant part is that i set the runenv in my profile, I can confirm that the path is part of the VirtualRunEnv by printing the environment().dumps() method in the generate() step of my conanfile.py, the conanrunenv-release-x86_64.ps1 contains the correctly setup path, but the visual studio debugger does not know about the adde path of the runenv.


This is my profile:
```ini 
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.version=194
os=Windows

[conf]
tools.microsoft.msbuild:vs_version=17

[runenv]
PATH+=(path){{ os.path.normpath(os.path.join(profile_dir, os.path.normcase("../../external/MyLibrary/x64-Release/bin"))) }}
```
This is the content of my conanrunenv-release-x86_64.ps1:

```PS
Push-Location $PSScriptRoot
"echo `"Restoring environment`"" | Out-File -FilePath "deactivate_conanrunenv-release-x86_64.ps1"
$vars = (Get-ChildItem env:*).name
$updated_vars = @("PATH")

foreach ($var in $updated_vars)
{
    if ($var -in $vars)
    {
        $var_value = (Get-ChildItem env:$var).value
        Add-Content "deactivate_conanrunenv-release-x86_64.ps1" "`n`$env:$var = `"$var_value`""
    }
    else
    {
        Add-Content "deactivate_conanrunenv-release-x86_64.ps1" "`nif (Test-Path env:$var) { Remove-Item env:$var }"
    }
}
Pop-Location


$env:PATH="$env:PATH;$PSScriptRoot\..\..\external\mylibrary\x64-release\bin"
```

This is the dump in the generate() step of my conanfile
print(str(VirtualRunEnv(self).environment().dumps()))

`PATH+=(path)C:\Users\myuser\source\repos\myproject\external\mylibrary\x64-release\bin`

Yet my generated conan_toolchain.cmake does not contain the given path

```cmake
########## 'vs_debugger_environment' block #############
# Definition of CMAKE_VS_DEBUGGER_ENVIRONMENT from "bindirs" folders of dependencies
# for execution of applications with shared libraries within the VS IDE

set(CMAKE_VS_DEBUGGER_ENVIRONMENT "PATH=$<$<CONFIG:Debug>:C:/Users/myuser/.conan2/p/b/aws-s08e07b36c5fb8/p/bin;C:/Users/myuser/.conan2/p/b/aws-c40c48b2058675/p/bin;C:/Users/myuser/.conan2/p/b/aws-c5dc5ad935c17c/p/bin;C:/Users/myuser/.conan2/p/b/aws-cf630a4f16b9ed/p/bin;C:/Users/myuser/.conan2/p/b/aws-ce0dd90919255b/p/bin;C:/Users/myuser/.conan2/p/b/aws-c9f26ad205381e/p/bin;C:/Users/myuser/.conan2/p/b/aws-c35272d53586f5/p/bin;C:/Users/myuser/.conan2/p/b/aws-c555f64eaa3bea/p/bin;C:/Users/myuser/.conan2/p/b/aws-c0159a48e899b5/p/bin;C:/Users/myuser/.conan2/p/b/aws-cb1d6185503baa/p/bin;C:/Users/myuser/.conan2/p/b/aws-c7875e252d658d/p/bin;C:/Users/myuser/.conan2/p/b/aws-c00e2ae2e3bb1b/p/bin;C:/Users/myuser/.conan2/p/b/aws-c5d784c9330539/p/bin;C:/Users/myuser/.conan2/p/zlib58f9ffd7f770b/p/bin>$<$<CONFIG:Release>:C:/Users/myuser/.conan2/p/aws-seb5fd1ca9393c/p/bin;C:/Users/myuser/.conan2/p/aws-cad94c58e5ca51/p/bin;C:/Users/myuser/.conan2/p/aws-cef9a244af0315/p/bin;C:/Users/myuser/.conan2/p/aws-c6280e45b00c63/p/bin;C:/Users/myuser/.conan2/p/aws-c197403e4ba021/p/bin;C:/Users/myuser/.conan2/p/aws-c71fc86da666c9/p/bin;C:/Users/myuser/.conan2/p/aws-c1a94c060b0b76/p/bin;C:/Users/myuser/.conan2/p/aws-c991565bae70aa/p/bin;C:/Users/myuser/.conan2/p/aws-c9b8843875bb37/p/bin;C:/Users/myuser/.conan2/p/aws-cd88abb43899c7/p/bin;C:/Users/myuser/.conan2/p/aws-cd85a5a7e4121a/p/bin;C:/Users/myuser/.conan2/p/aws-c2e99dbaf9e32d/p/bin;C:/Users/myuser/.conan2/p/aws-c01e08a42fa1cb/p/bin;C:/Users/myuser/.conan2/p/zlib6f797a4dd16fb/p/bin>;%PATH%")
```

So my debugger is able to find all bindirs of my conan dependencies, but not my provided runenv.

**Comment by memsharded** [comment]
> The pre-compiled library is just located in a folder in my repository, not a conan package, but comes with it's own FindPackage config for cmake, but apart from that is only a lib, include and bin folder (the latter containing multiple dlls required for running)

But why don't you put it inside a Conan package, with its ``xxx-config.cmake`` inside the package, and then treat it as any other dependency? That way you manage versions, and other stuff. This is possible, see for example: https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/use_package_config_cmake.html, and most likely very recommended in most cases. At the end of the day it doesn't matter if the package is built from source or not, packages are consumed from binaries.

**Comment by softgate-fabian-guenther** [comment]
Oh, I was not aware the one could create a package from binaries alone.

I was under the assumption that a package need to be able to be built from source. Can I create a conan package just with a package() and package_config() method? 

How would I manage revisions in that case? I assumed revisions are created from recipe + the exported sources. If I do not export sources and have no source() method, how is the revision generated?

The binaries are not publicly available but are under development, so changes to the binaries occur relatively frequently and keeping the right revision available is crucial.

Sorry for derailing, feel free to close

**Comment by memsharded** [comment]
> Oh, I was not aware the one could create a package from binaries alone.

> I was under the assumption that a package need to be able to be built from source. Can I create a conan package just with a package() and package_config() method?

Yes, absolutely, this is a great feature, it is not necessary to build from source to create Conan packages, see for example: https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.html#packaging-already-pre-built-binaries

This allows to put versions, revisions, package_info, etc. into the package, and use it homogeneously and automatically, managing updates, lockfiles, enjoying version-ranges, etc. etc.

> How would I manage revisions in that case? I assumed revisions are created from recipe + the exported sources. If I do not export sources and have no source() method, how is the revision generated?

Yes, that is correct. But if there are no sources, then sources will not change, and unless you modify the ``conanfile.py`` you will not get a revision. And if the binaries are really modify what you get is a new version. So everything works well regarding revisions.

> The binaries are not publicly available but are under development, so changes to the binaries occur relatively frequently and keeping the right revision available is crucial.

Do you mean that the binaries change often, but you don't want to change the version of the binary? That would be the recommended approach in most cases, because as those binaries are generated outside Conan, putting some number on them that correlates them explicitly with the creator of those binaries would be a great thing for traceability and reproducibility. I'd for example recommend to request such a number from the creators of the package, if they put it inside a file together with the binaries, the recipe could automatically load it with ``set_version()`` method.

Also note that changing the binaries should never change the "recipe-revision", because different binary configurations as the ones described in the linked above example should belong to the same "recipe-revision". So packaging one binary for Windows and another for Linux from pre-compiled binaries, both should still belong to the same "recipe-revision".

> Sorry for derailing, feel free to close

No problem at all 🙂 we can keep this open to talk about this, I think there is good potential there to improve the flow, we have seen tons of Conan users very happily putting pre-compiled binaries inside Conan packages.

**Comment by softgate-fabian-guenther** [comment]
Thank you very much for the detailed explanation @memsharded .

Yes, you got that correctly. The other team is making regular changes to their library and we are working with the "cutting edge" revision of their binaries. I figure we can come to an arrangement, maybe use their git commit SHA. 

Just making sure, using `set_version()` only allows us to set the `version` property, not the package revision, right?

Yeah, I understand the part that changing settings/options does not affect the package revision. 

We will need to discuss how to solve this internally. We probably have to setup a shared conan repository, so that we can consume their packages.

Thank you a lot again, I learned a lot from your answers!

**Comment by memsharded** [comment]
> Just making sure, using set_version() only allows us to set the version property, not the package revision, right?

Correct, this method allows to define only the ``version``, but not the recipe-revision or the package-revision. Those are always the hash of the contents.

> Yeah, I understand the part that changing settings/options does not affect the package revision.

Changing settings/options do modify generally the ``package_id``, yes, but not the ``recipe-revision``. Regarding the ``package-revision``, that is a different story, in general they should be avoided, as having more than a package-revision for the same version+recipe-revision+package-id indicates like a process error, when a binary that already existed is unnecessarily re-built again from sources, and the non-determinism of the builds generates a new hash, but otherwise it would be the exact same binary.

> We will need to discuss how to solve this internally. We probably have to setup a shared conan repository, so that we can consume their packages.

That is generally ideal, it works pretty well. And they don't need to change much things, as they are providing pre-compiled binaries, no need to change their build at all, for them adding a ``conanfile.py`` at the end of the pipeline, creating and uploading the packages to a repo should be relatively straightforward. And having these binaries properly modeled, versioned, traced in a server repo has tons of advantages.

> Thank you a lot again, I learned a lot from your answers!

You are very welcome, happy to help! Don't hesitate to open new tickets for any further question, thanks to you for your feedback!
