### ISSUE TITLE
[question] Specifying tool_requires options in host profile

### ISSUE THREAD

**Issue by tttapa** [conan-io/conan#17427]
### What is your question?

Hi, is there a way to specify options for the `tool_requires` dependencies in the `host` profile?

For example, when cross-compiling, the host profile could contain the cross-compiler as a `tool_requires` (`my-cross-gcc` in this case), and then the compiler executables would be set to the ones provided by this cross-compiler package.

```ini
{% set host_triplet = "aarch64-rpi3-linux-gnu" %}

[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=gnu23
compiler.libcxx=libstdc++11
compiler.version=14
os=Linux

[tool_requires]
my-cross-gcc/14.2.0

[???]
my-cross-gcc/*:target={{ host_triplet }}

[conf]
tools.cmake.cmaketoolchain:system_name=Linux
tools.cmake.cmaketoolchain:system_processor=aarch64
tools.gnu:host_triplet={{ host_triplet }}
tools.build:compiler_executables={ "c": "{{ host_triplet }}-gcc", "cpp": "{{ host_triplet }}-g++", "fortran": "{{ host_triplet }}-gfortran" }
tools.build.cross_building:cross_build=true
tools.build.cross_building:can_run=false
```

However, there doesn't seem to be a way to configure the options of the cross-compiler (or any other `tool_requires`) without resorting to a separate `build` profile. In this scenario, the `my-cross-gcc/*:target` option is fully determined by the `host` profile (in Autotools terms, the `target_triple` of the `build` context should be the `host_triple` of the `host` context), and treating it as an option of the `build` context doesn't really make sense IMO.

Is there any way to set `my-cross-gcc/*:target` in the `host` profile?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by tttapa** [comment]
I'm working my way through https://docs.conan.io/2/examples/cross_build/toolchain_packages.html right now, which hopefully provides a solution.

**Comment by memsharded** [comment]
Hi @tttapa 

Thanks for your question.

> Hi, is there a way to specify options for the tool_requires dependencies in the host profile?

No, options for ``tool_requires`` have to be defined in the "build" profile. 

> For example, when cross-compiling, the host profile could contain the cross-compiler as a tool_requires (my-cross-gcc in this case), and then the compiler executables would be set to the ones provided by this cross-compiler package.

If the package is actually packaging all different compilers instead of packaging just the compiler that the option is defining, the recommended method would be a ``user.xxx`` conf, not an option, as the option you would have to remember to remove it in the ``package_id()`` method to avoid having an effect in the ``package_id``. Maybe, if the compilers are actually different, you could easily package them in ``my-cross-gcc-rpi3`` and use the ``settings_target`` for defining the rest of the inputs, that would probably work pretty smoothly. 

I see that this very specific use case of the target-triplet seems convenient, but we already came from Conan 1 when everything was defined in 1 profile, and we learned that it doesn't scale well, and that the line should be defined somewhere. 

The current definition is quite simple and unambiguous: all the inputs for packages in the "build" context come from the "build" profile. Breaking this rule would easily go down the rabbit hole, why defining some ``[build_options]`` in the host profile, and why not also ``[build_settings]``? And ``[build_conf]`` (so you can pass it via ``conf`` as suggested above, not via an ``option``)? Some other users will find convenient for some other cases to define the ``[build_tool_requires]`` there too. Not to say that this way of defining things will bring a new cause of confusion: in case of overlap, which inputs will have higher priority, the ``[build_options]`` ones from the "host" profile ``[build_options]`` or the ``[options]`` from the "build" profile? I am totally sure that there will be users reporting bugs because of this, and then there will be arguments that one of them has more priority than the other, and different users will argue the opposite than the others.

**Comment by tttapa** [comment]
@memsharded Thanks for the the detailed response!

> if the compilers are actually different, you could easily package them in `my-cross-gcc-rpi3` and use the `settings_target` for defining the rest of the inputs, that would probably work pretty smoothly.

That's what I currently have working, based on the https://docs.conan.io/2/examples/cross_build/toolchain_packages.html tutorial: https://github.com/tttapa/conan-recipes/blob/1f42472f06ab59cfc7a127d458b17fd0b2790b7b/recipes/tttapa-toolchains/binary/conanfile.py

The main limitation I've hit right now is that for my actual use case, the values in `settings_target` do not uniquely determine the correct toolchain. There are other aspects such as ARM extensions, vectorization, hard/soft float ABIs, GLIBC versions, Linux versions etc. that are not captured by the default [settings.yml](https://docs.conan.io/2/reference/config_files/settings.html).

Would you recommend adding custom settings in `settings_user.yml`? I assume they would need to be sub-options of `arch` and `os` to make sure they're added to the package ID, is that correct?

The downside of `settings_user.yml` is that I haven't found a way to automate the installation of these custom settings. I'll either have to tell users to manually edit the file, or risk overwriting their existing global settings_user.  
Ideally, the installation instructions would be a handful of bash commands to copy and paste, along the lines of `conan remote add ... && conan install . -pr ./profiles/system-a && cmake --preset ...`.
What would you recommend here? Maybe settings `CONAN_HOME` to a project-specific directory to avoid overwriting the global `settings_user.yml` file?

**Comment by memsharded** [comment]
Thanks for the feedback!

The recommended way to manage custom settings (and custom profiles, custom conf, custom remotes, custom command, custom extensions, etc) is using ``conan config install`` (for putting things inside git repos) or ``conan config install-pkg`` for putting things inside Conan packages. Basically the "maintainer" or "devops main responsible" defines and puts the common Conan configuration in one of those places, so everyone, including CI machines and developers they only have to do a single ``conan config install/install-pkg`` command to get everything at once (and also can repeat it to get updates).

Please check that and let us know.

Regarding the custom settings definition, it is always a trade-off, adding too much, if they don't really don't change the binary model, is counter productive, for those cases using user confs like ``user.conf`` might be better, as a different way to inject information that do not affect the ``package_id``. 

If you are targeting some embedded domain, it is indeed very common for users to have some custom settings that model their deployment targets, boards, special architectures, etc, as the final binaries are really dependant on the hardware they will be running, even if the same os/compiler/arch, binaries can change based on the specific board pinout.

**Comment by tttapa** [comment]
> using `conan config install`

Thanks, this indeed seems more ergonomic than managing them manually. I'll consider using this for CI and sharing profiles with colleagues. The main concern I have is that _“Files in the current Conan home will be replaced by the ones from the installation source”_, so this is not something one could put as a one-liner in a README without some caveats to the user or without recommending a project-specific conan home.

Which approach would you recommend for a public project on GitHub? My specific goal and the reason for the original question is for others to be able to reproduce any published results exactly, so ideally, they'd use the same (cross-)compiler with the same vectorization settings etc., which would be specified in Conan profiles in the same Git repository.

> Regarding the custom settings definition, it is always a trade-off, adding too much, if they don't really don't change the binary model, is counter productive, for those cases using user confs like `user.conf` might be better, as a different way to inject information that do not affect the `package_id`.

The problem is that most of those settings _do_ change the binary model:
 - ARMv6 vs ARMv6K changes the `std::shared_ptr` ABI;
 - Vectorization settings restrict the supported hardware, and affect the ABI and alignment of containers in libraries such as Eigen;
 - Soft/hard float use different calling conventions;
 - Static linking of core libraries such as `libgcc` may break propagation of exceptions between libraries;
 - Binaries compiled using a newer GLIBC or Linux version are not ABI-compatible with older versions of GLIBC/Linux, etc. 

Unfortunately, there doesn't seem to be a standard way to represent these properties in Conan, and it requires some manual intervention, if I understood your comment in https://github.com/conan-io/docs/issues/3960 correctly.

Even if ABI compatibility weren't an issue, I wouldn't want to silently pull in a cached binary without vectorization when compiling a project for AVX512, because that would negatively affect performance.

>  for those cases using user confs like `user.conf` might be better, as a different way to inject information that do not affect the `package_id`.

Could you give an example where `user.conf` would be appropriate? If I understand correctly, when I set `user.confvar:foo=True` in my profile, but a version of a dependency that was built with `foo=False` is already available in the cache, then Conan will use the latter. Doesn't that kind of defeat the purpose of setting the confvar in the first place?

**Comment by memsharded** [comment]
> Thanks, this indeed seems more ergonomic than managing them manually. I'll consider using this for CI and sharing profiles with colleagues. The main concern I have is that “Files in the current Conan home will be replaced by the ones from the installation source”, so this is not something one could put as a one-liner in a README without some caveats to the user or without recommending a project-specific conan home.

Indeed, this should be used by consensus, understanding that it defines the current conan configuration. If the same configuration is not used in all projects, then it would be adviced to have a different CONAN_HOME for each project (for convenience, the CONAN_HOME can also be automatically defined in folders, by the ``.conanrc`` file, that will soon be deprecated by a full ``conanws`` workspace file, see https://docs.conan.io/2/incubating.html)

> Which approach would you recommend for a public project on GitHub? My specific goal and the reason for the original question is for others to be able to reproduce any published results exactly, so ideally, they'd use the same (cross-)compiler with the same vectorization settings etc., which would be specified in Conan profiles in the same Git repository.

For this purpose, the most important file is probably a ``lockfile``. Including a lockfile in your repo, named ``conan.lock``, so it is used automatically if users do a ``conan install``, really helps to improve reliability and reproducibility.

Besides that, you might also provide a local "profiles" folder, user profiles can also be used from local folders so ``-pr=./profiles/myprofile``, without necessarily installing them in the cache. So it depends on the amount of configuration, if you don't need to define anything else, then the ``conan config install`` might not be necessary. If you are running your own server and want users to use specifically your server and not ConanCenter, or have any other extra configuration, then the ``conan config install`` can be beneficial. The ``conan config install`` can also operate on local folders, so if you put something like a ``config`` or ``conanconfig`` folder in your repo, it can be installed too with ``conan config install <path> -t=dir``.

> Unfortunately, there doesn't seem to be a standard way to represent these properties in Conan, and it requires some manual intervention, if I understood your comment in https://github.com/conan-io/docs/issues/3960 correctly.

Exactly, there is no general perfect binary model. So what Conan does is to implement the tools to let users to define the binary model they need. ConanCenter and the Conan default ``settings.yml`` are pretty good for a majority of users, but they cannot cover 100% of the cases.

> Even if ABI compatibility weren't an issue, I wouldn't want to silently pull in a cached binary without vectorization when compiling a project for AVX512, because that would negatively affect performance.

That is fine, if you define some custom settings, and add for example micro-architecture definitions as sub-settings to ``arch`` architectures, then Conan will know that there is no binary for that configuration and fail with ``Binary missing``, and then let the users build it from source with ``--build=missing``, without needing to modify the recipes, and allowing different binaries for different micro-architectures to coexist simultaneously on the same machine without problems. 

But yes, defining what are the limits, and the exact binary model if the default one is not enough, needs to be done by the user, and used as a convention in the specific projects.


> Could you give an example where user.conf would be appropriate? If I understand correctly, when I set user.confvar:foo=True in my profile, but a version of a dependency that was built with foo=False is already available in the cache, then Conan will use the latter. Doesn't that kind of defeat the purpose of setting the confvar in the first place?

The ``conf`` usages are intended for cases when the binary compatibility is not affected. For example ``tools.cmake.cmaketoolchain:generator=Ninja`` is a conf, because it doesn't really matter if you use Ninja or MSVC CMake generator, the final binary should be the same. Or ``tools.build:skip_test``, as building or not the unit tests do not have any impact on the final package binary.

For ``user.`` confs, it would be the same. Any inputs that you want to provide to recipes for convenience, but that do not affect the binary model, can be "confs". If they affect the binary model, in general ``settings`` or ``options`` are preferred (though there are mechanisms to make the ``conf`` be part of the ``package_id`` and as such, be part of the binary model)

**Comment by tttapa** [comment]
That clears things up for now. Thanks a lot, I really appreciate the detailed answers!

**Comment by memsharded** [comment]
Sounds good, don't hesitate to re-open or create new tickets for any further question. Thanks for the feedback!
