### ISSUE TITLE
[question] Treating multi-config generators like single-config generators

### ISSUE THREAD

**Issue by proceduralnoisy** [conan-io/conan#17439]
### What is your question?

Hello,

**Context**

We are exploring a Conan-centric rethink of our C/C++ build and test infrastructure at a large-ish (several thousand developers) company supporting products on multiple platforms. To make this a manageable effort, we need to define the boundary between necessary and unnecessary variation in our development environment and workflows.

One source of variation is the distinction between single-config and multi-config generators. Multi-config generators introduce complexities for automation and workflows. A couple examples:
- Different layouts for build artifacts: Single-config generators use a simple top-level partitioning (e.g. 'build/Release'), but multi-config generators require careful sub-partitioning that impact any config-specific data (e.g. 'build/libs/Release', 'build/my-custom-test-output/Release', ...)
- 'Invalid' configurations: If an MSVC user runs `conan install` with `build_type=Release`, all CMake configurations are listed (Debug, RelWithDebInfo, etc.) in the IDE, but only the Release configuration will work. This could be a common point of confusion (especially given that 'Debug' is the default configuration in Visual Studio). 

It's possible to manage these complexities, but it would certainly be _simpler_ if we could adopt the convention of treating multi-config generators the same as single-config generators (e.g. separate top-level 'build/\<config\>' folders for MSVC, each with its own .sln file).

That leads to a few questions:

**Question 1: Implementation**
It seems we can achieve our basic aim through the use of `build_folder_vars`:
```
[conf]
tools.cmake.cmake_layout:build_folder_vars=['settings.build_type']
```
Is this an appropriate use of this feature? 

In my initial testing, this seems to yield reasonable workflows for MSVC (tested using VS Code with [CMake Tools](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/README.md) and Visual Studio with [C++ CMake tools](https://learn.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170)). 

**Question 2: conanfile vs. profile/conf**
Assuming build_folder_vars is the right feature, we can alternatively use conanfile.py:
```
    def layout(self):
        self.folders.build_folder_vars = ["settings.build_type"]
        cmake_layout(self)
```

Presumably we'll want this to be our company-wide default, and users may wish to override or further customize the behavior. It seems that both options could provide those capabilities:

-  Option 1: global.conf, injected via [conan config install-pkg](https://docs.conan.io/2/reference/commands/config.html#conan-config-install-pkg)
- Option 2: conanfile.py, injected via [python_requires_extend](https://docs.conan.io/2/reference/conanfile/attributes.html#python-requires) 

Should we favor one option over the other? 

**Question 3: Configuration erasure**
If users wish to open .sln files with Visual Studio (instead of using [C++ CMake tools](https://learn.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170)), it would be nice if the IDE showed only a single configuration. 

That can be achieved with the following changes:

(in conanfile.py)
```
    def generate(self):
        ...
        tc = CMakeToolchain(self)
        tc.variables["CMAKE_BUILD_TYPE"] = self.settings.build_type
        ...
```
and (in CMakeLists.txt)
```
set(CMAKE_CONFIGURATION_TYPES ${CMAKE_BUILD_TYPE})
```

Is it acceptable to set `CMAKE_BUILD_TYPE` in this specific case (one configuration per folder)? #14773 suggests it doesn't work, but it works fine for me as of 2.8.1. 

**Question 4: Strategic sanity check**
Are there any big downsides to this approach that we should be considering?  This is a decision that could be difficult to walk-back after broader adoption (for example: CMake code is unlikely to be written with config-based generator expressions in mind). 

Clearly any configuration-independent processing would be unnecessarily duplicated for each configuration. I'm thinking of aspects like CMake [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) and [protoc](https://grpc.io/docs/protoc-installation/) code generation. But that seems like a relatively small price to pay in exchange for more predictable, uniform workflows. 

Thanks for all your awesome work in building this great tooling and community!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @proceduralnoisy 

Thanks for your question.

> One source of variation is the distinction between single-config and multi-config generators. Multi-config generators introduce complexities for automation and workflows. A couple examples:

I agree. I wish all systems would have adopted the same single-config approach, the advantages of the multi-config are not enough compared with the variability it introduces.

> tools.cmake.cmake_layout:build_folder_vars=['settings.build_type']

I have a quick question first, have you considered using ``tools.cmake.cmaketoolchain:generator=Ninja`` even for Visual? That is a single-config generator, and it is popular because of being faster. 

> Is this an appropriate use of this feature?

Yes, this is one of the intents of this feature. Conan will create separate "build" folders for debug/release/etc, effectively implementing a single-config. It even works with ``editables`` packages.


> Question 2: conanfile vs. profile/conf

A quick note first: If you decided to put ``self.folders.build_folder_vars = ["settings.build_type"]`` in the recipes, directly or via python-requires, note that it is still possible to override that from profiles/conf. In Conan, the "consumer" closest to the user always has precedence, in this case, a user profile or conf has priority over what is defined in recipes.

I think in this case I'd go for profile/conf. Not necessarily in ``global.conf``, but maybe in profiles ``[conf]`` section. Because this is mostly a ``conf`` by nature, something intended to be customized by users, the recipe doesn't really care about this folder, so users can change it at their will. There is no silver bullet, it really depends on the case, but I'd tend to use conf with the information I have so far. Also, note that recipe code is in general harder to change and maintain, because it spreads across hundreds of files, while configuration is way easier to change.

> Question 3: Configuration erasure

Probably no need or recommended to modify the ``CMakeLists.txt``. It is also not necessary to do ``tc.variables["CMAKE_BUILD_TYPE"] = self.settings.build_type`` in the recipe.

You can achieve the equivalent to ``set(CMAKE_CONFIGURATION_TYPES Release)``, by injecting ``tools.cmake.cmaketoolchain:extra_variables`` which can be defined in the profile too. So it would be configuration driven, no need to hardcode the CMakeLists.txt


> Question 4: Strategic sanity check

I think with the recommendations above, there is relatively little risk. Nothing needs to be changed or hardcoded neither in recipes nor in CMakeLists.txt, so it will be easier to maintain and change, and even let developers that want for some reason at their own risk to use multi-config VS IDE.

> Clearly any configuration-independent processing would be unnecessarily duplicated for each configuration. I'm thinking of aspects like CMake [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) and [protoc](https://grpc.io/docs/protoc-installation/) code generation. But that seems like a relatively small price to pay in exchange for more predictable, uniform workflows.

Yes, I agree, the duplicated "configure" steps seems a reasonable price to pay in my opinion too.

> Thanks for all your awesome work in building this great tooling and community!

Thanks very much for your kind words! 🙂

**Comment by proceduralnoisy** [comment]
Thanks @memsharded for the rapid and detailed reply! I will close this issue.

> I have a quick question first, have you considered using `tools.cmake.cmaketoolchain:generator=Ninja` even for Visual? That is a single-config generator, and it is popular because of being faster.

Thanks for this suggestion. We will definitely explore the Ninja generator. 

> You can achieve the equivalent to set(CMAKE_CONFIGURATION_TYPES Release), by injecting tools.cmake.cmaketoolchain:extra_variables which can be defined in the profile too. So it would be configuration driven, no need to hardcode the CMakeLists.txt

Ah, of course (forehead slap).

**Comment by memsharded** [comment]
Happy to help!

Don't hesitate to create new tickets for any further question or issue, thanks for your feedback!
