### ISSUE TITLE
[question] I encountered an dependencies issue and would like to ask for your advice.

### ISSUE THREAD

**Issue by crystalsky** [conan-io/conan#17466]
### What is your question?

I encountered an issue and would like to ask for your advice.
# I have two library module projects
## ProjectA:
- depends on glog， and glog depends on gflags. Both glog and gflags use shared libraries. 
- Project A contains an executable program execA, and when running conan create in the environment of Project A, all the targets linking is successful.
## Project B: 
- depends on Project A
- but when running conan create . --build=A in Project B Environment.
- the executable execA from Project A cannot link successed Because Env Hasn't find gflag.so, which is required by glog."

How To Solve This Dependenise Error.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @crystalsky 

Thanks for your question.

This kind of problem is very difficult to know what is happening without code to reproduce. Because most of those things depends on the recipes, the build-system integrations used, etc.

I would recommend to report using a repo with code, or something like that, with clear details to reproduce.
For example, you can do:
```
$ mkdir liba && cd liba
$ conan new cmake_lib -d name=liba
$ conan create . -o "*:shared=True"
$ cd ..
$ mkdir libb && cd libb
$ conan new cmake_lib -d name=libb -d requires=liba/0.1
$ conan create . -o "*:shared=True"
```
And everything should work. You will have there the full recipes to inspect and check.

**Comment by memsharded** [comment]
Hi @crystalsky 

Any further details or feedback here? Thanks.

**Comment by crystalsky** [comment]
thanks. These Days I had out my Company for other projects. I have No Time To Do this Problem. I will Try It In 5 days And Make The Copy Of Package Reciepe At Here. @memsharded

**Comment by memsharded** [comment]
Sure, no rush, just trying to understand if something was missing, if no longer an issue and the ticket can be closed, etc. Take your time, thanks for the feedback.
