### ISSUE TITLE
[question] Issue Downloading Package Binaries in Conan 2

### ISSUE THREAD

**Issue by Arora-Shivam** [conan-io/conan#17475]
### What is your question?

Hi,

I am migrating Conan artifacts from a repository containing both Conan 2 and Conan 1 artifacts to their respective remotes (Conan 2 artifacts to Conan 2 remote and Conan 1 artifact to Conan 1 remote).

**The approach I followed was:**

- Search for the package reference (<package_ref>) in the source remote.
- Download the recipe and its binaries.
- Upload the recipe and binaries to the destination remote

I used Conan 1.59.0 for Conan 1 artifacts and Conan 2.10.2 for Conan 2 artifacts.

This worked well for Conan 1, but I ran into issues with Conan 2 when trying to download package binaries.

**Problem in Conan 2:**

- The command `conan download <package_ref> -r <remote>` only downloads the recipe revision but not the binaries. In Conan 1, there is an option(--all) to download all binaries for a recipe, but I couldn’t find an equivalent for Conan 2. I also tried `conan download <package_ref>#*:* -r <remote>` to target all revisions and binaries, but it didn’t work.

Additional Attempts:
I used the conan list command to get package details:

`conan list <package_ref>#*:* -r <remote>`
However, the output only showed the package revisions but no details about the binaries:
```

remote_name  
  pkg  
    pkg/ver  
      revisions  
        d77ee68739fcbe5bf37b8a4690eea6ea (2022-08-05 17:17:30 UTC)  
          packages  
```
According to the [documentation](https://docs.conan.io/2/reference/commands/list.html#listing-package-ids), this command should list the package binaries, but it didn’t.

**Request:**
Could you help me figure out:

- How to list all binaries for a recipe in Conan 2?
- How to download all binaries for a given package recipe so I can re-upload them to the destination remote?
- If there’s a better way to migrate Conan artifacts between remotes, I would appreciate your suggestions.

Thank you!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @Arora-Shivam 

Thanks for your question.

> I am migrating Conan artifacts from a repository containing both Conan 2 and Conan 1 artifacts to their respective remotes (Conan 2 artifacts to Conan 2 remote and Conan 1 artifact to Conan 1 remote).

This shouldn't be necessary. Conan package binaries use different ``package_ids`` in Conan 1 and Conan 2, so it is designed so they can coexist in the same repo without collision, and that is easier to maintain in most cases. In general it is the recommended approach, unless for some reason the recipes really diverge in Conan 1 and 2 (which is not recommended, but if happens, that would need different repos).

> The command conan download <package_ref> -r <remote> only downloads the recipe revision but not the binaries. In Conan 1, there is an option(--all) to download all binaries for a recipe, but I couldn’t find an equivalent for Conan 2. I also tried conan download <package_ref>#*:* -r <remote> to target all revisions and binaries, but it didn’t work.

The ``conan download`` command by default download all the binaries from the server. So:
```
conan download zlib/1.3.1 -r=conancenter
```
you can try it and you will see how it download the different binaries from the server.

What it doesn't download is binaries from Conan 1. Binaries created with Conan 1 are only visible with ``conan search`` in Conan 1, and binaries created with Conan 2 are only visible with ``conan list`` command in Conan 2. This is by design, and one of the features that allow to use the same repository for hosting binaries for Conan 1 and Conan 2 simultaneously.

> conan list <package_ref>#*:* -r <remote>

Same happens with ``conan list``. It only lists binaries created with Conan 2, but not binaries created with Conan 1.

Please let me know if this clarifies the question.

**Comment by memsharded** [comment]
Hi @Arora-Shivam 

Any further question or feedback here? Did the above helped?

**Comment by Arora-Shivam** [comment]
Hi @memsharded The above feedback does help. I am closing this ticket

**Comment by memsharded** [comment]
Thanks for the feedback!
