### ISSUE TITLE
[question] Need advice on code generators

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#17490]
### What is your question?

Dear Conan Folks,

I am looking out for advice. We do have some tools that are used before build for code generation. We have been using them as tool_requires and this is in build context. However, in the core guidelines : https://docs.conan.io/2/knowledge/guidelines.html It is mentioned not to use tool_requires. If I use requires this changes the package to host context and this is also not correct. As the code generator is really a tool and not anything to do with the host context. Could you pleas eprovide guidance on:
- Such tools can be used/absused as tool_requires or more fit to requires?

Thank You for your guidance!
Br,
Maitrey

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Hi @maitrey 

Thanks for your question.

Code generators are a valid use case for ``tool_requires``. They are mostly tools, tools that generate code. Typical example is ``protoc``, the protobuf code generator, that can be perfectly used as ``tool_requires("protobuf/version")`` to use the protoc executable. The important point is that in general, it shouldn't use the libraries, or tool-requires shouldn't be used for libraries that are linked into the package in the "host" context. So when actually linking with protobuf libraries another ``requires("protobuf/version")`` is needed, besides the ``tool_requires``

What the core guideline mentions is not to not use them. But to not abuse them for other things that are not tools. Like some users tend to incorrectly try to use them for regular libraries, because they think it means "only needed at build time", like an executable linking with a static library, the library is only needed at build time, but not at runtime. This is not the meaning of ``tool_requires``, which are needed at build time, yes, but they are also "tools" that run in the "build" context.

So I'd say your usage of ``tool_requires`` is correct. 
Does this clarify the issue?

**Comment by maitrey** [comment]
Yes thanks a lot for your advice. Issue can be closed!
