### ISSUE TITLE
[feature] Optionally keep old test_package build files

### ISSUE THREAD

**Issue by Tails86** [conan-io/conan#17522]
### What is your suggestion?

Currently, Conan always deletes the test directory before rebuilding tests as long as the build folder is not the source folder:
https://github.com/conan-io/conan/blob/develop2/conan/cli/commands/create.py#L176
```py
    if conanfile.build_folder and conanfile.build_folder != conanfile.source_folder:
        # should be the same as build folder, but we can remove it
        out.info("Removing previously existing 'test_package' build folder: "
        #[...]
```

I understand this is probably done for consistency - to ensure tests always rebuild off of any new source. I think this was problematic in Conan 1.x (at least from what I remember). 

My `test_package` takes several minutes to rebuild. Sometimes during development, I just want to build one new test to ensure it works before moving on to making more tests. In that case, I only want to build the new test code.

Minimally, can a configuration value (for `-c`) be added to optionally skip this check? Ideally, there would be a smarter way to determine if the entire test package build directory needs to be obliterated and rebuilt. That doesn't seem entirely possible though unless Conan had intimate knowledge of the generator/build.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by Tails86** [comment]
FYI: The current workaround I'm using is `-c tools.cmake.cmake_layout:test_folder=.` to make `conanfile.build_folder != conanfile.source_folder` equate to false, but that causes all test build artifacts to be placed next to source which is messy.

**Comment by memsharded** [comment]
Hi @Tails86 

Thanks for your feedback.

> My test_package takes several minutes to rebuild. Sometimes during development, I just want to build one new test to ensure it works before moving on to making more tests. In that case, I only want to build the new test code.

This is probably beyond the scope of ``test_package``, which is intended to test the consistency of the package. See for example https://docs.conan.io/2/knowledge/guidelines.html#good-practices:

> The test_package purpose is to validate the correct creation of the package, not for functional testing. The test_package purpose is to check that the package has been correctly created (that is, that it has correctly packaged the headers, the libraries, etc, in the right folders), not that the functionality of the package is correct. Then, it should be kept as simple as possible, like building and running an executable that uses the headers and links against a packaged library should be enough. Such execution should be as simple as possible too. Any kind of unit and functional tests should be done in the build() method.


So I would like to understand better the use case before deciding. Could you please elaborate about your use case? What tests are you doing here? Why not doing the tests included in the regular test suite of the package as recommended (and can be switch on/off with conan ``conf``), as this allows running the tests even when the package is built as a dependency, which can be very convenient for CI.

Our experience is basically that it is impossible to know when the folder must be deleted, but in too many situations it needs to be deleted, otherwise issues due to the build cache and differences with a newer configuration will happen. This is why the behavior is to delete it.

**Comment by Tails86** [comment]
It sounds like we are using `test_package` outside of what is recommended. My use-case does indeed contain functional testing of code. We originally created the architecture of the package with Conan 1.x where `test_package` seemed to be the best place for unit tests at the time for our needs, so maybe it's time to reassess that. I assume the conf variable you're referring to is `tools.build:skip_test`, is that right?

Feel free to close this if you feel like it's out of scope.

**Comment by memsharded** [comment]
> It sounds like we are using test_package outside of what is recommended. My use-case does indeed contain functional testing of code. We originally created the architecture of the package with Conan 1.x where test_package seemed to be the best place for unit tests at the time for our needs, so maybe it's time to reassess that. I assume the conf variable you're referring to is tools.build:skip_test, is that right?

Don't you have any unit testing that requires access to the internal headers that are not part of the package? Because the issue with those tests is that it is impossible to run then from the ``test_package``, so they naturally force users to have them inside the package themselves.

Yes, ``tools.build:skip_test`` and recently ``tools.graph:skip_test`` for fully skipping ``test_requires()`` dependencies can help to control when unit tests are built and executed or not.

> Feel free to close this if you feel like it's out of scope.

Not out of scope, I am still interested in learning if there is some other use case that could support this feature request. Maybe this would be a case for the ``conan test`` command, as it is a bit too dev-flow of a use case to do it via ``conf`` that would also affect the ``conan create``.
So lets do the following, I am closing this at the moment as unplanned, but please re-open it or create a new ticket if you have any further feedback, if you re-asses the usage of ``test_package`` and try the in-recipe testing, or any other related question or issue, and we can resume the conversation. Thanks very much for your feedback!

**Comment by Tails86** [comment]
> Don't you have any unit testing that requires access to the internal headers that are not part of the package? Because the issue with those tests is that it is impossible to run then from the test_package, so they naturally force users to have them inside the package themselves.

I see your point. We do have components in the package that don't really need to be packaged. Not just headers, but static libraries that are used exclusively for building executables. I hadn't given that a second thought until now.

Thanks for your consideration and help. I think my issue will be resolved by doing things the recommended way instead.

**Comment by memsharded** [comment]
Always happy to help! 🙂 

Don't hesitate to create new tickets for further suggestions or discussion, as you can see, even if they don't always lead to implementing a new feature, they can bring good learnings in both directions.
