### ISSUE TITLE
Why are user_info transformed and stored as string? 

### ISSUE THREAD

**Issue by danieleTrimarchi** [conan-io/conan#1781]
Hi, 

We have noticed that when we define values for UserInfo, their string representation is stored instead of the actual values. 

For example, if we assign a list of JAR files for a Java package : 
`    self.user_info.jars = ['JAR1.jar','JAR2.jar','JAR3.jar']`

this gets transformed into a string in [user_info.py](https://github.com/conan-io/conan/blob/f96a816d83a12da4a54c838e6a65e4a064e08f3a/conans/model/user_info.py), in UserInfo::__setattr__ :
`    l19:    self._values_[name] = str(value)`
    
in this case, when we retrieve the user info we get the string:
 ` >>> conanfile.deps_user_info.vars `
 `"['JAR1.jar','JAR2.jar','JAR3.jar']"`

What is the reason for this? Wouldn't it be preferable to leave the object 'value' as is? 

We are writing a custom generator and we would like to keep the list as is. 
We can of course work around this by re-transforming the string to a list using ast.literal_eval.

Thanks, 
        Daniele

**Comment by memsharded** [comment]
The ``UserInfo`` has the semantics of environment variables, so they are key: value strings. These variables are serialized to disk, to the ``conanbuildinfo.txt`` file, that is necessary to support the local commands (build, package, package_files, imports) without needing to recompute the whole dependency graph for each command. So they are converted to strings early to ensure that everything serializes/deserializes and is afterwards consumed always as string.

The alternative would be to implement user-side serialization/deserialization with a specified interface, doesn't seem difficult for lists, but what happens if users give other structures (dicts, or custom classes), then the complexity will highly increase. 
The alternative is maybe not perfect, but easily understandable by package creators:

```python
self.user_info.jars="jar1.jar, jar2.jar, jar3.jar"
...
jars = self.deps_user_info["Pkg"].jars
jar_list = jars.replace(" ", "").split(",")  # I try to avoid eval/exec
```

**Comment by solvingj** [comment]
I ran into this 6 months ago also, and went to open a ticket today and found this. 

I understand the challenge about passing other types.  I also wish we could define python list literals on `user_info`.  I used the manual string split method for now. 

I'm sure it's too late at this point to change the semantics, so might as well close this ticket .

**Comment by danimtb** [comment]
Opened an issue here https://github.com/conan-io/docs/issues/920 with its PR. Closing this due so innactivity but please feel free to comment or reopen 😄
