### ISSUE TITLE
Set profile without using -p

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#1792]
Profiles are great.   Before you had to pass a bunch of `-s` and `-o` command line options.  They were easy to forget or get wrong.  Now you just need to pass one `-p` option.  

We would like to be able to set the profile in source control, rather than rely on a human to provide it on the command line.  Some options:

- Set in `conanfile.txt` / `conanfile.py`
- A separate `conanprofile.txt` file

These would contain references to the profile for that project, for example, if it were in `conanfile.txt`:

    [profile]
    ../profiles/default

This relative path would be to a profile in the same source control repo.

Is there a way to do something like this already?

**Comment by lasote** [comment]
But, what information do you want to include in that "shared" profile? If users have different settings, like operating systems, or compilers, it has no much sense to default it.

**Comment by sourcedelica** [comment]
For settings it would be `compiler` and `libcxx`.  Our dev machines have a number of compilers installed.  I was thinking it would be useful for options too, but those will mostly be set in `conanfile.{py,txt}`.

My main concern is using `~/.conan/profiles` for anything that is specific to a particular project.  I want anything related to the project defined in source control.   Our developers are notorious for not following directions :), and I would not expect their `~/.conan` to be set up correctly.   

We can probably script our way around this.  We can have a script that runs `conan install` with the correct parameters.   And scripting the new `conan config install` feature could help.

**Comment by memsharded** [comment]
Still something that I am missing. Like, why you would hardcode your recipes to a given compiler and libcxx. The current design decouples them, because the core idea is that a given recipe can produce many binaries, one different binary for each different configuration (profile). So you are building for one and just one configuration?

Profiles can be also added in source control in the project. If you use relative paths, while specifying them, then, they will be loaded from the current folder, which is perfect for maintaining different profiles for different projects.

You might also be interested in the new ``conan config install <url or git repo>`` functionality, as you can create a default configuration, including profiles (but also remotes, etc), for every project. Then, your developers, all they have to do while working on a project is to:
```bash
$ conan config install https://git-repo-url/project1
```
That can change the ``default`` profile.
Please tell me if that makes sense, or a bit more feedback about your use case if you are just building one configuration, and don't plan to change it or support other compiler versions in the future.

**Comment by sourcedelica** [comment]
Yes, we're building using a single configuration.  It's for in-house software which is developed and deployed across the same configuration of OS and compiler.   I realize we are atypical.  

`conan config install` could probably work for us though I am always skeptical about depending on anything in a developer's environment.  For example, many times I've had trouble getting one of our applications to start because it depends on some environment variable that was in the original developer's `.bashrc` :)

**Comment by memsharded** [comment]
Yes, got it, "it works on my machine!" :)

There could be some ways to implement this in the recipes, but I don't feel they would be very clean (though the same applies for hardcoding a profile in the recipe):

The thing I can think of is a restriction of the settings in the recipes, that can be done. So you can define in your recipe:

```python
class MyPkg(ConanFile):
      settings = {"os": ["Windows"], "compiler": {"gcc":  {"version": ["5.4"]....
```
In that way:
- Any attempt to build with different, non allowed setting will raise an Error
- The build helpers, like ``CMake`` will keep working the same.
- If some day, you want to expand to more configurations, lets say, you want to add gcc 6.1, you could just do a search and replace in your recipes for ``"version": ["5.4"]```

It will only be for settings,though.

**Comment by sourcedelica** [comment]
Ok - I will give that a try.  Thanks!
