### ISSUE TITLE
Conan test failure Cmake version incorrect.

### ISSUE THREAD

**Issue by luckielordie** [conan-io/conan#1795]
I'm trying to get all the tests to pass on my machine. I've only got Visual Studio 2017 installed. 
When I setup the tests I ran.
```
export CONAN_COMPILER="Visual Studio"
export CONAN_COMPILER_VERSION=17
```
however on examining the output of the failing test "conans.test.command.build_test.ConanBuildTest" it looks like Conan is selecting the wrong version of Visual Studio for Cmake.

![image](https://user-images.githubusercontent.com/2615305/30781881-3b1791fe-a11f-11e7-9488-998893fa9e6b.png)

I'm not *that* familiar with Cmake so maybe I'm getting it wrong, but hopefully I've provided enough information to be useful.

**Comment by memsharded** [comment]
We are still using VS 14 (2015) as the reference version for tests, because it is still the most used one, and we want to make sure it works. There are other tests that will use the default, so if you have VS2017 installed, they will run with it. But VS 2015 is still necessary. We recently removed tests using VS12, and it is very likely that in a few months we will move to VS2017, but not yet.

The variables you are using won't be necessarily honored along the test suite, where did you get the info for those variables regarding the tests? Probably that documentation is outdated and it has to be improved.

**Comment by luckielordie** [comment]
Ah okay, I got it from the Readme for the project towards the bottom when it describes running tests. I'm assuming the best way to solve this is to just go ahead and install VS2015 so I have the Platform Toolset?

**Comment by memsharded** [comment]
Yeah, at the moment it is the best. We will be doing a further effort to label with nosetests attributes the test suite for easier testing without installing all the tools, but at the moment, it is necessary.

**Comment by memsharded** [comment]
Hi @luckielordie 

Did you manage to install the necessary tools to run the test suite? Do you need further help with this issue, or can we close it? Thank you!

**Comment by luckielordie** [comment]
Hi! @memsharded 
Sorry this totally slipped my mind, once I installed the correct Platform Toolsets I was able to run the test suite, Thanks for your help!

**Comment by memsharded** [comment]
Great! Thanks for telling :)
