### ISSUE TITLE
Independent/Dependent options for more flexible build resolution

### ISSUE THREAD

**Issue by kenfred** [conan-io/conan#1809]
I don't believe the provided methods of build_id and package_id can be used for the following use case. If they do, please advise how. Thanks!

Assume I have a package that can optionally include add-on modules A and B. Options to include A and/or B are completely independent of each other.
```python
options = {
    "a": [True, False],
    "b": [True, False]
}

default_options = "a=False", "b=False",
````

This leaves me 4 combinations of options. If I run `conan install -o a=True`, it must pick options corresponding to a=True and b=False.

It would be convenient if I could specify in my recipe that options a and b are independent of one another. That way when I run `conan install -o a=True`, the value for option b is a don't-care. I can now resolve to 2 of the 4 possible combinations.

Of course this is a trivial example. What if the recipe has 6 independent options? That's 64 options combinations. If I could mark them as independent, there would be a far greater chance I could find an available binary and not have to build. For example, if I care about 1 option and the rest are don't-cares, than 32 of the 64 combinations would satisfy the request.

Consider a [Qt recipe][1] that has over a dozen options, many of them independent. Qt is especially painful to fetch and build. I hate having to start over because I decided to enable/disable a single option. I want to increase the odds that a option combination I've already built can be used. I could even do an initial build with all the add-ons enabled and then most of the combinations would resolve to that superset.

  [1]: https://github.com/osechet/conan-qt

**Comment by lasote** [comment]
You could use two approaches:

1. Use the `configure` method to control the activated options. In the following example, it's controlled that only one option is activated and any other is removed from the options.

```
    def configure(self):
        activated = [(opt, value) for opt, value in self.options.values.as_list() if value]
        if len(activated) > 1:
            raise Exception("Only one option can be activated: %s" % activated)
        for name, value in self.options.values.as_list():
            if not value:
                self.options.remove(name)
```

2. Use an open value option to specify the module to be activated:

```
class MyPkg(ConanFile):
    ...
    options = {"shared": [True, False], "modules": "ANY"}
```

You could give any value to "modules" and use the `configure()` method to limit the possible values/control invalid values.

**Comment by kenfred** [comment]
@lasote Thanks for your response. I think there is a misunderstanding. I do not wish to create mutually-exclusive options. My desire is for conan to pick a package that is sufficient for my options, rather than exact, to avoid the build.

Currently, conan will pick the package that matches the exact set of options. However, there are some options for which I don't care their value. In which case, I'd rather conan prioritize a package that is already built over fetching and building a new one.

In order for the conan to resolve to "sufficient" package , it needs to know which options are don't-cares. When I specify a subset of options during `conan install`, rather than unrelated options reverting to their defaults, they can revert to "anything"/don't-care, thus expanding the set of packages conan can resolve to. Of course, some options are interdependent, so it would not be appropriate to revert the ones I don't specify to a don't-care - they need to revert to default.

I'm suggesting a paradigm where I indicate in the recipe subsets of options. Something like this:

```python
class FooConan(ConanFile):
    options = {
        "group 1": { "a" = [True, False], "b" = [True, False]},
        "group 2": {"c" = [True, False], "d" = [True, False]}
    }
```
If I do `conan install <path> -o a False`, `a` would be False, `b` would revert to its default, and `c` and `d` would be don't-cares. Therefore conan is free to pick any package that has `a`=False, `b`=its default, regardless of `c` and `d`.

Here's another way to ensure backward compatibility:
```python
class FooConan(ConanFile):
    options = { "a" = [True, False], "b" = [True, False],"c" = [True, False], "d" = [True, False]}
    
    # This member is normally False. When set to True, all options are don't-cares unless
    # specified during install or are part of an option group with an option that was
    # specified during install 
    independent_options = True

    #  Create groups to show which options are interdependent.
    option_groups = [["a", "b"], ["c", "d"]] # 
```

Or perhaps this would need to be more programmatic in `config_options` so I can do more sophisticated things.

My motivation behind this is Qt, where the fetch is long, the build is long, and the resulting output is large. I don't want many copies of Qt on my PC. I want my Qt projects to resolve to the Qt package that is already built and available on my system, provided its options do not conflict with my options. I don't care if it happens to have an extra dll for some component I'm not using. It is sufficient, even if not exact.

Perhaps there could be a switch on `install` that tells conan to be more permissive in resolving the package. Without the switch, it is the current, "exact match" behavior.

**Comment by memsharded** [comment]
The thing with options is that by definition, they affect the output of the binary package being created. So any configuration of possible options should produce a unique final package being created. For packages defining such modules, do you really want to have different binaries, some of them with some modules, and without the others, and all possible combinations?

I think this might not the use case, and you are interested in creating a package that will contain all modules, aren't you?

For options, you might consider the special value ``None``, which is some value that doesn't affect the binary package ID at all. Thus, a package with ``option1=None`` and ``option2=None`` should have the same package ID as if those options were not defined at all.  Still don't know how would you manage the combinatoric explosion.

What you are suggesting is quite unfeasible, what would be the criteria, that the binary exist in the local cache? That the binary exist in the default remote? In any of the remotes? Having to check that for the permutations that are possible can't be done without too much overhead.

The root problem here is the existence of huge monoliths that are indeed a full ecosystem of libraries. The correct approach to this problem is to modularize it, something like has been done here for boost: https://bincrafters.github.io/2017/09/22/boost-modular-packages-conan/

I know that it is not a solution in the short term, as it takes time, but what you are suggesting is not possible either. Even with ``config_options`` you would still need to check the existence of such binaries (locally and remote), for a combinatoric number of permutations.

The short term clean solution is just to create packages without those options. Always build all libraries, have one package per configuration (os, compiler, arch). It will just come with some unused libraries, but that is not a problem at all.

**Comment by kenfred** [comment]
@memsharded Thanks for your response. This isn't a trivial thing to tackle, but it is a definite pain point I think is worth thinking about and find ways to mitigate.

I want to retain the existing behavior where the package hash is tied to the set of options. The "permissive" mode of `conan install` I described would mostly be used when I'm first integrating a new package and I'm not yet sure which options I want. It would be a big time saver if it could pick a "sufficient" package rather than a exact package. Then, when I have finalized my options, I would use the normal mode of `conan install` and make sure I'm using the exact package.

> What you are suggesting is quite unfeasible, what would be the criteria, that the binary exist in the local cache? That the binary exist in the default remote? In any of the remotes? Having to check that for the permutations that are possible can't be done without too much overhead.

I may be overlooking some details, but seems like a simple procedure would be:
1. Compute a list of package hashes that are "sufficient". 
2. Compare the list of sufficient hashes to packages in the local cache. If one of the packages exists, choose it.
3. If none found in the local cache, do the same for each of the remotes
4. If none found in the remotes, go ahead and build with the exact option set.

> The root problem here is the existence of huge monoliths that are indeed a full ecosystem of libraries. The correct approach to this problem is to modularize it, something like has been done here for boost

I agree. When you think of the most popular libraries (Qt, Poco, Boost come to mind) they often are a loose collection of unrelated modules. That's sort of what makes them go-to's: people like to reduce their dependencies and pick mature libs that do everything. 

Boost is a perfect example of where this feature would shine. The boost libs are mostly independent from one another. If I do a "default" boost build, it's a full build comprising all modules. If I send in a `--without-<module>` switch, I'm saying I don't need that module. Since the modules are independent, this switch is really only an optimization to reduce build time. That is a great thing to do when my build has stabilized and I'm trying to reduce CI build times. But when I'm first bringing in Boost and still figuring out when I need, conan penalizes me heavily for experimenting with options. For boost, the default/full/super-set build is the most convenient thing to choose during development. But that doesn't mean I want to cripple my recipe to ignore options altogether - I still want to optimize build times when it has stabilized.

> I know that it is not a solution in the short term, as it takes time, but what you are suggesting is not possible either. Even with config_options you would still need to check the existence of such binaries (locally and remote), for a combinatoric number of permutations.

The order of options isn't important, so the number of sets is the combination of don't-care options, not permutations, but yeah it could get big. For binary options the number of combinations would be 2^(d), where d is the number of independent, don't-care options. For most recipes, I'd wager this to be few than 64. Just a guess. Of course this would be per settings set, so it grows quickly. We could design a multi-hash scheme that would make searching much faster, but it would probably be a breaking change.

The combinations of these become bigger as the number of options grows. However, as the number of options grow, that's when I waste the most time futzing around with options and doing lots of rebuilding. I'd be fine with a somewhat longer operation to compute a set of sufficient hashes - much better than suffering a rebuild if I tweak an option. For big libraries the time it takes to compute and compare hashes is dwarfed by downloading and building.

There may be opportunities to make this "permissive" mode smarter. Step 1 could assign a score to each of the "sufficient" hashes. Option sets whose don't-care options are at their default value will be preferred over others because it's closer to what you requested in `conan install`. You could run the procedure with the high scoring options first to reduce the number of sets to compare and then rerun with the lower scoring sets if none found.

> The short term clean solution is just to create packages without those options. Always build all libraries, have one package per configuration (os, compiler, arch). It will just come with some unused libraries, but that is not a problem at all.

Once again, I still want to use my options. I only want to temporarily choose a "sufficient" package while I'm figuring out what I need. However, if I was going to do what you suggest, I could go about it by implementing `build_id` to ignore the options and unconditionally do the full build during the build step. Then, during the `package` step, package ids still corresponding to my options. It's a one-build-to-many-packages approach.

**Comment by memsharded** [comment]
Searching, specially in the servers (but also in the local client), can be quite slow, check https://github.com/conan-io/conan/issues/1373, for example. And search is required in order to obtain and compare the different IDs for a given reference.

I am sorry, but what you are suggesting still looks to me as extremely complex for the value it gives. Conan is growing quite fast, and we must be very careful about later maintenance, fixes and new features. I still think that the best approach for this kind of libraries is just to build AND package all the optional libraries together, without any further options. Adding such options is IMHO not only premature optimization, but in practice largely the opposite, trying to save a few bits of disk space and transfer, but then having to build many times, or have packages with many redundant binaries (remember that most of those frameworks libraries are still packaged, it is just a few optional libraries that might not be packaged).

If we invest time to improve this, such time is better invested in doing real modularizations of those packages.

**Comment by kenfred** [comment]
Ok. Thanks for considering it.

**Comment by KalleDK** [comment]
@memsharded I've run into the somewhat same "problem". One of my projects uses boost - or rather 3 modules from boost, and I care about if these modules are header only etc. All the other modules/options I don't really care for. My problem is that my project is in itself a library, and if someone uses me with their own lib/what ever that uses boost I now "force" options.

One solution is marking the different options as don't care in comments so that the user know they can override it without any trouble, but it seems. So for me is it not the build process but the dependency problem (diamond problem) where my lib "forces" options in that I don't care about

**Comment by memsharded** [comment]
Hi @KalleDK 

I am not sure I fully understand. In many cases, a package recipe shouldn't be defining options of their dependencies. You library package can define some defaults for the boost options, but they can be safely overriden downstream if the consumer of your library needs boost with different options because of the diamonds in the dependency graph.

Could you please elaborate a bit further, maybe with an smaller example, or with specific options? Thanks

**Comment by KalleDK** [comment]
App (created by User)
Liba ( created by me)
Libb (created by random)
Boost

App requires Liba & Libb

Liba only have boost as requirements ( no options set, but I have to read how boost is configured to set my own flags - If boost is header only, I have to be header only)

Libb requires boost also, but also require options C is set.

Now App would complain because liba don't set C but libb set's C

And the User have to know that liba don't care about C, so he can override liba's option

**Comment by memsharded** [comment]
> If boost is header only, I have to be header only

Not really. You can perfectly create a compiled library that requires a header only library.

And in any case, if there is a conflict, it is the end user (App) that has to decide the definite value of the option C to be used by everybody. Still not sure if I understand :)

**Comment by KalleDK** [comment]
>>If boost is header only, I have to be header only
>
> Not really. You can perfectly create a compiled library that requires a header only library.
My library has to, as it's an "extension" to boost. The users use my library alongside boost, so I can't consume it :) But I get what you mean.

And even though you are not sure - you answered with
>  It is the end user (App) that has to decide the definite value of the option C 

I would just like a way to communicate to the user, that I don't care about C, to make his choice easier.

**Comment by memsharded** [comment]
I would say that the way to tell the users that you don't care about some option of your dependencies, is simply not doing anything. This is the default. 

What you can do, is to manage the options that you do care:
- Define some defaults for your dependencies. If nobody else defines those options, they will be the ones that will be used
- Raise for incompatible options. You can try to check values in the ``configure()`` method, and raise an Exception accordingly, if your library is incompatible with the options that are being provided from downstream.

**Comment by memsharded** [comment]
Closing this conversation as inactive:

- For advanced binary compatibility resolution Conan 2.0 provides both the ``compatibility()`` method per recipe, and a global ``compatibility.py`` plugin, both able to define any custom logic regarding options that affect binaries or not.
