### ISSUE TITLE
dev_requires attribute is removed in 0.27.0 update but still in documentation

### ISSUE THREAD

**Issue by hamparawa** [conan-io/conan#1846]
In my project, there are unit tests are built only in development, and are not part of exported package. To setup the unit test dependency libraries, dev_requires attribute is used. 

However, after the update to 0.27.0, packages mentioned in dev_requires are no longer added to the project when doing a local conan install.

When looking at the changelog for[ 0.27.0](http://conanio.readthedocs.io/en/latest/changelog.html#september-2017), states

> Deprecation: dev_requires have been removed (it was not documented, but accesible via the requires(dev=True) parameter. Superseded by build_requires. 

Even though the latest documentation still advises to use dev_requires attribute.
[http://conanio.readthedocs.io/en/latest/mastering/scopes.html#dev-scope](http://conanio.readthedocs.io/en/latest/mastering/scopes.html#dev-scope)

**Comment by memsharded** [comment]
It is weird, we removed the documentation, you can check it is not in the index anymore: http://conanio.readthedocs.io/en/latest/mastering.html. It seems that you have to remove the page as well, will do. Also check the note at the beginning of the page, has been there for a couple of releases now.

So the thing is that we are doing a great effort to stabilize conan out of beta, and ``dev_requires`` was a complex feature in the codebase that was adding nothing that couldn't be done with ``build_requires`` and environment variables instead of scopes. Sorry that this has broken your project. Please have a look to them, it should be relatively easy to update to them, ask if necessary, would like to help in this update.

**Comment by lasote** [comment]
Removed from master.
