### ISSUE TITLE
Use env variables for detect Visual Studio 

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#186]
Should be coherent to use the environment variables defined by vcvarsall.bat command to detect the right visual studio version in detect.py. 
It's not an urgent issue but conan package tools will look a little more clean and homogeneous with the changes i'm currently doing for gcc builds.

**Comment by memsharded** [comment]
Wondering if this is still a feature. Now, ``tools`` support ``vcvars_command`` that is an good way to load the environment. If detecting the current Visual Studio version from current environment variable, could lead to packages working locally (because of the environment defined), but failing in other machines.

So if the user runs on a VS12 environment, but conan detects too a VS14 and uses it as default, that might help in spotting such potential problem.
