### ISSUE TITLE
Add local cppflags into conanbuildinfo.cmake

### ISSUE THREAD

**Issue by Tedlar** [conan-io/conan#1908]
Hi,
I cannot find any solution for adding cppflags from conanfile.py into conanbuildinfo.cmake.
I'm trying to place all information needed to build sources into conanfile.py so I can use generic CMakeLists.txt file (same in all projects).
If I add cppflags as cmake generator's "definitions", sources are build with proper flags using conan build() method. 
But when I clone project and try to build it with CLion it fails because those flags are not stored in conanbuildinfo.cmake (of course after 'cmake install').
Is there any way to for example push cmake definitions from conanfile.py into conanbuildinfo.cmake ?

**Comment by memsharded** [comment]
Are you trying to add cppflags, from your self conanfile.py?

The information you declare in ``self.cpp_info`` in the ``package_info()`` method is for consumers of the package only, not for the same package. If you want to add cppflags to your current ``build()`` you probably need to add them to your CMakeLists.txt. If you want to directly pass them in the command line, I think you could do something like:

```python
def build(self):
    cmake = CMake(self)
    cmake.definitions["CMAKE_CXX_FLAGS"] = "your flags"
    ...
```
Please tell me if this helps, thanks!

**Comment by Tedlar** [comment]
Right now I'm using this method and it's working in current `build()`:
```
def build(self):
    cmake = CMake(self)
    cmake.definitions["CMAKE_CXX_FLAGS"] = "your flags"
    ...
```
What I want to achieve is to propagate `cppflags` for current build from `conanfile.py` into `conanbuilinfo.cmake`.
That way same git repository could be cloned, build and packed by Jenkins CI (using conan abstraction methods) and by developer using just CMake without placing custom cppflags into `CMakeLists.txt`.

It would be much easier to store them (`cppflags`) only in one place (`conanfile.py`).
After `conan install` aggregated `cppflags` (local and from requires) would be placed into `conanbuildinfo.cmake`.
For example it could be done by setting some flag to force `self.cpp_info.cppflags` to be added into `CONAN_CXX_FLAGS` CMake variable.

**Comment by memsharded** [comment]
But there is an important issue, here. Is that ``cppflags`` are those declared for the consumers, which might not be the same that those used for the current build. As you know, it is typical to have private/public configuration, not only for ``cppflags``, but also for other fields. For example, the ``self.cpp_info.includedirs = ["include"]``, it is telling the consumers about the public header directory of the final package, to consumers. 

If we follow the same reasoning, then, should we allow ``self.cpp_info.includedirs = ["include", "private_includes"]`` in ``package_info()`` and that should be defined in conanbuildinfo.cmake, so it can be used by CMakeLists.txt of the package? I don't think so, it will be a mess, and also fail, because the "private_includes" won't be packaged at all.

**Comment by Tedlar** [comment]
Then maybe something like:
`self.settings.cppflags`
where we could set private flags strictly for current build.
If we see need to show some of them to consumers, then we can also place them in:
`self.cpp_info.cppflags`

**Comment by memsharded** [comment]
The settings are a completely different thing, and they have to be pre-defined in ``settings.yml``, so it is not a good place for such flags.

Still not sure why you think:

```cmake
def build(self):
    cmake = CMake(self)
    cmake.definitions["CMAKE_CXX_FLAGS"] = "your flags"
```
is not a good approach to the problem. It is very evident, easy to understand, highly configurable (you can easily set CMAKE_C_FLAGS, CMAKE_CPP_FLAGS, etc, very easily too. For me, it is the right place to have it. Of course, if you like your flags to be as class attributes, you can:

```python

class Pkg(ConanFile):
     cppflags = "myc++ flags here"

     def build(self):
         cmake = CMake(self)
         cmake.definitions["CMAKE_CXX_FLAGS"] = self.cppflags
```

**Comment by Tedlar** [comment]
I'm lazy and don't want to do same things twice.
While setting `cmake.definitions["XXX"]` works well for `conan build()`,
I have to pass the same configuration when invoking `CMake` manually or through IDE like `CLion`.

At the same time setting `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} XXX")` in `CMakeLists.txt`
sets default cppflags for manual invocation of `CMake` but I need to look in both `CMakeLists.txt` and `conanfile.py` to check if everything is ok.

If local cppflags could be stored in `cmakebuildinfo.cmake`, then I would be able to create `CMakeLists.txt` template same for almost all of my projects (few hundreds) significantly reducing the work to be done and needed for maintenance.

**Comment by memsharded** [comment]
I understand what you are proposing, but still don't think that it would be a feature that would be interesting for many other conan users. Also, if this was to be implemented, it had to be implemented for all generators, not only cmake.

Please consider when you have a conanfile.py in your user folder, to be opened with CMake or CLion, you typically run: ``conan install``. But you don't have a package at all. That ``conan install`` just brings the ``requires`` and install them. But the ``package_info()`` method might not be meaningful at all, because you still don't have a package for that recipe. In fact, it is not guaranteed that ``package_info()`` will be ran at all (in the same way that source() or build() won't be run when you execute ``conan install``)

Though, while I understand that it could seem to be more convenient, I still think that it is better to keep the decoupling between these items. Maybe the important thing here is what ``cppflags`` are you passing from packages to consumers? In my experience, it is a rarely used field, only for some special cases. Normally, most of cppflags config is directly managed by cmake, not necessary to put it in conan.

**Comment by Tedlar** [comment]
Thanks for all information.
I think i will just create few presets of `cppflags` and move between them through `build_type` or `options`.
More generic solution would be better for easier adjustment but hey, you work with what you have.
Conan is already awesome as it is ;)

**Comment by memsharded** [comment]
Thanks for your understanding. We'd love to implement every user feature request, but now that we start to serve a big community and already have quite a few contributors, we also have to care about the codebase, keep things as simple as possible, be sure that every feature adding many lines of code (as this could be) really makes sense to many users...

Please keep us updated about your usage of cppflags. Which cppflags are you passing around. Once your conan integration advance, which are the patterns that you see most repeated.... the fact that right now would be too much doesn't mean that we won't consider it again in the future. Please keep giving feedback :) Many thanks!!

**Comment by AliAskari** [comment]
@memsharded I am kinda interested in this issue. I am trying to figure out how I can use one source to set the compilation flags for both the conan package of my libraries and also when I build the library directly with CMake. I cannot seem to find a way to have write and maintain one set of flags. The best thing I have found is to add a new `flags.toml` file where I write the flags for different configurations and then read from the toml file from the conan recipe and my CMakeLists.txt and then compile my code. I have not started implementing it so I was wondering what would you recommend? 

I want to save one set of flags for both Conan and CMake to use. Maintaining the flags in two different files does not look like a good idea.

What do you recommend? Do you know of a better way for settings the flags?
