### ISSUE TITLE
conan create doesn't pass settings to test_package

### ISSUE THREAD

**Issue by Boulougou** [conan-io/conan#1930]
Reproducing the issue:

1. Create an empty package using -t option:
```
conan new Hello/0.1 -t
```

2. Build the package using custom settings (different from the settings in `~/.conan/profiles/default`). E.g.
```
conan create demo/testing -s build_type=Debug -s compiler=clang -s compiler.version=5.0 -s compiler.libcxx=libstdc++
```

Notice that an error is printed because test_package cmake ran using gcc (the default compiler), while the conan settings use clang. Here is the full output:

```
[george@george-manjaro-desktop temp]$ conan create demo/testing -s build_type=Debug -s compiler=clang -s compiler.version=5.0 -s compiler.libcxx=libstdc++
Hello/0.1@demo/testing: Exporting package recipe
Hello/0.1@demo/testing: A new conanfile.py version was exported
Hello/0.1@demo/testing: Folder: /home/george/.conan/data/Hello/0.1/demo/testing/export
Hello/0.1@demo/testing: Installing package
Requirements
    Hello/0.1@demo/testing from local
Packages
    Hello/0.1@demo/testing:d1bb7aa92cfc7788069af25615975729fa2c4938

Hello/0.1@demo/testing: WARN: Forced build from source
Hello/0.1@demo/testing: Building your package in /home/george/.conan/data/Hello/0.1/demo/testing/build/d1bb7aa92cfc7788069af25615975729fa2c4938
Hello/0.1@demo/testing: Configuring sources in /home/george/.conan/data/Hello/0.1/demo/testing/source
Cloning into 'hello'...
remote: Counting objects: 17, done.
remote: Total 17 (delta 0), reused 0 (delta 0), pack-reused 17
Unpacking objects: 100% (17/17), done.
Branch static_shared set up to track remote branch static_shared from origin.
Switched to a new branch 'static_shared'
Hello/0.1@demo/testing: Copying sources to build folder
Hello/0.1@demo/testing: Generator cmake created conanbuildinfo.cmake
Hello/0.1@demo/testing: Calling build()
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
CMake Error at ../conanbuildinfo.cmake:302 (message):
  Incorrect 'clang', is not the one detected by CMake: 'GNU'
Call Stack (most recent call first):
  ../conanbuildinfo.cmake:58 (conan_check_compiler)
  CMakeLists.txt:3 (conan_basic_setup)


-- Configuring incomplete, errors occurred!
See also "/home/george/.conan/data/Hello/0.1/demo/testing/build/d1bb7aa92cfc7788069af25615975729fa2c4938/CMakeFiles/CMakeOutput.log".
Hello/0.1@demo/testing: 
Hello/0.1@demo/testing: ERROR: Package 'd1bb7aa92cfc7788069af25615975729fa2c4938' build failed
Hello/0.1@demo/testing: WARN: Build folder /home/george/.conan/data/Hello/0.1/demo/testing/build/d1bb7aa92cfc7788069af25615975729fa2c4938
ERROR: Hello/0.1@demo/testing: Error in build() method, line 26
	self.run('cmake hello %s' % cmake.command_line)
	ConanException: Error 256 while executing cmake hello -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="clang" -DCONAN_COMPILER_VERSION="5.0" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/home/george/.conan/data/Hello/0.1/demo/testing/package/d1bb7aa92cfc7788069af25615975729fa2c4938" -Wno-dev

```

Shouldn't test_package cmake respect the settings passed to `conan create`? I am using`Conan version 0.27.0`.

**Comment by memsharded** [comment]
Conan doesn't configure the environment for you. When you are telling conan ``conan create -s compiler=clang`` it doesnt mean that conan should configure a clang compiler for you. Conan will just call your package ``build()`` method and if it is using ``cmake`` it will probably take the `CC`` and ``CXX`` environment variables and use them. In other words, conan doesn't mess with your build system unless you tell it to do it. But it will manage your package as a "clang" package, because you declared it as such, and it will detect the failure when building the testing app. So a good thing that this mistake was detected, just check the build log, it is using gcc instead of clang to build the package.

So if you want to use your clang compiler you have some alternatives:
- Set it as the default compiler in your system, because it is in the path with higher priority
- Set the environment env-vars CC and CXX to point to clang compiler
- Configure conan env-vars (in profiles, or also in command line with ``-e Pkg:CC=/path/to compiler``, to point to the compiler you want to use.

Please check this, see if it helps and ask if you need further help. Thanks!

**Comment by Boulougou** [comment]
Indeed, I understand that conan does not mess with the build system of the package (it would be almost impossible with so many build systems in C/C++ world). My question is specifically for the test package generated by `conan new -t`. Since the generated `test_package/conanfile.py` always uses cmake as the build system, I would expect that necessary settings (e.g. `CMAKE_CXX_COMPILER`) are passed to cmake when building the test. I probably have to modify `test_package/conanfile.py` by hand so it passes the settings to cmake, but it would be convenient if the generated file worked out of the box.

**Comment by memsharded** [comment]
No, no, it is not a test_package issue. If you check the output, you can read, that your package is being built with gcc, not clang:

> -- The C compiler identification is GNU 7.2.0

This if for the package itself, the ``test_package`` functionality is not being used at all (yet). You can remove the ``test_package`` folder and you will get the same result. Please try it, and tell me. Then, if the problem is the same, as I would expect, please read carefully my comments above. Conan will not try to set compiler based on the ``settings.compiler=clang`` information, and your CC and CXX variables might be configured to use gcc. So you might need to configure the environment accordingly.

**Comment by Boulougou** [comment]
You are right, the error printed is about the package itself, not the test_package. I tried to create a minimal reproducible example, but failed to notice that the error printed was not about the test package. Sorry for the confusion caused.

My main point was that since `conan new` auto-generates `conanfile.py` that use cmake, it would be convenient if the generated `conanfile.py` passed all the necessary parameters to cmake (so it worked out of the box). At least for the test_package which is usually created from scratch even for existing projects that may not use cmake.

I am closing this issue though, since clearly there is no bug. Thanks for your time!

**Comment by memsharded** [comment]
You are very welcome, no problem at all, glad to help, you can ask anything!

Yes, I agree that it could be better if it could work for all cases out-of-the-box. While it works this way for many standard configurations, it is extremely complicated to do it robustly for other non-standard configurations, like clang. And if you try to do it automatically, then at some point you fail and inevitably block some users. So we prefer to be on the safe side: not to be very smart, but always allow user configuration. Said that, there are some users working with clang that migth contribute improvements, just it will take some time. 

Many thanks!
