### ISSUE TITLE
Conan in jenkins uses other Build direcory

### ISSUE THREAD

**Issue by gnobbi** [conan-io/conan#1946]
Hello first of all thanks for this create tool :)

I try to use conan + jenkins on a local Windows Pc

conan version 0.28.0  also tested it with 0.27.0
jenkins version 2.73.2
windows 8.1
python 2.7.13

I use this pipline script for jenkins

```groovy
def repo_url = 'https://github.com/lasote/conan-zlib.git'
def repo_branch = "release/1.2.11"

node {
    stage("Get recipe"){
        git branch: repo_branch, url: repo_url
    }

    stage("Test recipe"){
        bat "conan create channel/testing"
    }

    stage("Upload packages"){
        bat  "conan upload * --all -r local--confirm"
    }
}
```

Which fail. If I do the same command conan create channel/testing on cmdline it works.

The problem is the building directory:
I don't know where the following **C:\Windows\system32\config\systemprofile\.conan\data** dir comes from. it does not exist.

Jenkins output  - fail:
```
E:\CI\Jenkins\workspace\conan_ci_tutorial>conan create dnicklaus/testing 
zlib/1.2.11@channel/testing: Exporting package recipe
...
zlib/1.2.11@channel/testing: Building your package in C:\Windows\system32\config\systemprofile\.conan\data\zlib\1.2.11\dnicklaus\testing\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
``` 

cmd output - success:
```
E:\CI\Jenkins\workspace\conan_ci_tutorial> conan create channel/testing
zlib/1.2.11@channel/testing: Exporting package recipe
...
zlib/1.2.11@channel/testing: Building your package in E:\CI\Conan\zlib\1.2.11\dnicklaus\testing\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
``` 
which is in my conan.conf:

``` 
[storage]
path = E:/CI/Conan
``` 

Im not sure if this is a conan or a jenkins issue. But thanks for helping.
If yout need more information let me know

**Comment by memsharded** [comment]
> Hello first of all thanks for this create tool :)

You are very welcome :) :)

So it seems some problem related to the expansion of the "user-home" folder in your Windows under Jenkins, most likely because it is running under a different user, which home folder is not defined properly.

You might check the HOME, USERPROFILE environment variables, most likely the second point to: ``C:\Windows\system32\config\systemprofile``

I think you might be able to properly configure it if you set the CONAN_USER_HOME environment variable to the folder you want to use as a home. For Jenkins it could very well be a temporary folder that will be removed after the job is finished. 

Please tell me if this makes sense and helps. Thanks!

**Comment by gnobbi** [comment]
Thank you that works
