### ISSUE TITLE
Semantic naming in package names?

### ISSUE THREAD

**Issue by aurelienrb** [conan-io/conan#195]
Hello,

You probably know about “semantic naming” which is the hype word to use when you talk about packages and dependency management :)

So I would expect Conan to allow me to do that:
`conan.exe install “Boost/1.60.0@lasote/stable/Windows/x86_64/Visual Studio 14/Release”`
as an equivalent of:
`conan.exe install Boost/1.60.0@lasote/stable -s compiler="Visual Studio" -s compiler.version=14 -s arch=x86_64 -s build_type=Release`

Actually, Conan accepts this input but **silently ignores** my “semantic” parameters... and I get a different package than the one I expect :(

It's disapointing me because the web-site supports and displays this feature. I just copy-pasted what I found on the website (where packages are listed)! IMHO it's confusing to have a different syntax between the tool and the website.

Aurelien

**Comment by lasote** [comment]
Hi Aurelien,

In *conan.io* the urls are like this: https://www.conan.io/source/silicium/0.8/TyRoXx/master 
Website never specify settings in URL like OS, arch, compiler or any other.
Settings in conan are very flexible and give an established order to the settings in an URL or a reference seems to me arbitrary.

In addition to this, it's not very frequently need to specify (all) the settings in the command line. Usually the detected in ~/.conan/conan.conf should match. If don't you can edit the defaults and specify in the command line just the settings that differ from defaults:

e.g:
`conan.exe install Boost/1.60.0@lasote/stable -s build_type=Debug`

**Comment by aurelienrb** [comment]
@lasote Let me give you my requirement: I need to have a set of configs that can be used to target specific builds on a CI system. For example, I want to be able to build for _clang 3.4 32 bits release_ or _g++ 5.3 64 bits debug_ simply by selecting a specific entry point that will configure my (newly installed) system with all the dependencies needed.

That's why Conan is of interest for me: having a tool that manages getting or building the many versions I need to target many systems. In other words, I don't want any random setting (auto detected / configured) because I want to check what happen with my code on a specific compiler / library version. Imagin that I am developing a cross-platform library that is used by many people with many different configs, and I need to build and test them all.

So, as a newbie, the first thing I did was to find the package I want in http://conan.io and copy-paste it's configuration as it appears on the web site:

![image](https://cloud.githubusercontent.com/assets/8517069/13781455/b4a32678-eac3-11e5-9c74-a45495bf2513.png)

But that's not the input the tool expects (which is sad IMHO). So the first problem is the difference of convention between the website and the tool : it creates confusion.

The more embarrassing issue is such settings are **silently ignored** by the tool. I suggest to change this behavior: explicitly fail if I give an invalid "source" (how do you call that BTW?). For example:
```
conan.exe install "Boost/1.60.0@lasote/stable"
OK
```

```
conan.exe install "Boost/1.60.0@lasote/stable/Windows/x86_64/Visual Studio 14/Release"
ERROR: invalid source name
```

**Comment by memsharded** [comment]
Hi @aurelienrb ,

Since then, the web site has changed. Now there is no copy&paste command, and the initial "info" tab show much clearer instructions how to setup your project with the dependency.

There are a couple of issues with the name as you propose:

- There is no fixed settings structure. You could just omit the ``arch`` setting, so you will not have a ``x86_64`` element. That is an example. The settings can (and usually are) be even customized by the users for their own purposes, so detection based on values is very difficult too.
- Furthermore, the level of nesting is variable, some compilers have ``runtime`` sub-setting, while others have ``libcxx`` subsetting.
- There are no restrictions on the "channel" field. If one user wants to label their channel as ``stable/production`` or ``stable/distribution`` they can do that. Your use case is just an extension on this.

So the only way to provide clear an unambiguous input of user intention is with "key=value" pairs in the form of ``-s compiler=gcc`` command line arguments.

In fact, the specification of the full settings is now rarely done, as the ``profiles`` is a ver convenient feature that allows to robustly and easily define and set different configurations. Read: http://conanio.readthedocs.io/en/latest/reference/config_files.html#profiles

So I think this issue can be closed, thanks very much for your feedback!
