### ISSUE TITLE
Is it possible to build multiple packages from single conanfile.py?

### ISSUE THREAD

**Issue by bc-lee** [conan-io/conan#1957]
I'm new to use conan and trying to convert CMake / shell based open-source library building scripts to `conanfile.py`.

Some open-source libraries like `zlib` can build multiple different libraries, like `zlib` and [`minizip`](http://pkgs.fedoraproject.org/cgit/rpms/zlib.git/tree/zlib.spec?h=f26&id=9f014e30021753dbf9ee115487fcfa9d3f0fbc0a) However, i could not find any recipes for making multiple packages from single `conanfile.py`.

If I trying to subclassing class `ConanFile` multiple times in `conanfile.py`, `conan build` command won't work. Any suggestions, or workarounds?

**Comment by memsharded** [comment]
I am not sure what you are trying to achieve, but no, you cannot have more than one recipe (for 1 package), in one conanfile.py. 
Just use a different conanfile.py for each package.

**Comment by Aalmann** [comment]
Concerning the zlib use case:
It sounds a little bit like http://conanio.readthedocs.io/en/latest/packaging/package_info.html#n-configs-1-build-n-packages

Concerning subclassing:
You can subclass and reuse the code of other recipes.
One can define a "base recipe" (e.g. my_base_conan.py) containing all the common stuff which is always the same for all your products/packages (e.g. CMake-Handling). This file has to be exported as well and the Python path has to be extended in your conanfile.py. In your conanfile.py you subclass from your base class in my_base_conan.py.
From a developer perspective the Python path extension solves your find_module issue. From a package creator perspective both files (my_base_conan.py and conanfile.py) are first exported to the local repo into the export directory and the Python path extension is no longer required.

**Comment by memsharded** [comment]
> Concerning the zlib use case:
It sounds a little bit like http://conanio.readthedocs.io/en/latest/packaging/package_info.html#n-configs-1-build-n-packages

But that section is talking about the same package. So you are always building pakcage "PkgName/version@user/channel", with just 1 conanfile, with just 1 class deriving from ``ConanFile``. What you are getting with that approach is just to avoid rebuilding the binaries, because the build system is already building different flavours (lets say Debug/Release, 32/64 bits) in the same run, but you want to package the different binaries separately. So when you install the 64bits-Release package for ``PkgName/version@user/channel`` you get only the binaries for 64bits and Release configuration. But the package will always be ``PkgName/version...```


For re-using python code from packages you want to read the current docs: http://docs.conan.io/en/latest/howtos/package_manager/python.html#reusing-python-code-in-your-recipes (which doesn't cover inheriting, because that would be a chicken and egg problem)

And check this open issue: https://github.com/conan-io/conan/issues/1271 (follow conversation there for this topic)

**Comment by memsharded** [comment]
Hi @bc-lee 

Unless there are further questions, I think this issue can be closed now. Please re-open or comment if necessary. Thanks!

**Comment by sigiesec** [comment]
The link does http://conanio.readthedocs.io/en/latest/packaging/package_info.html#n-configs-1-build-n-packages does not work anymore. I wasn't able to map this to the current documentation. Can you provide an updated link?

**Comment by lasote** [comment]
https://docs.conan.io/en/latest/creating_packages/package_approaches.html
