### ISSUE TITLE
Rebuilding a package with a different hash without changing the library version

### ISSUE THREAD

**Issue by tareqsiraj** [conan-io/conan#1981]
Let say I have a package `foo/1.0.4@bar/release`. Everything is working fine until I find that I need to re-build the package with an additional compiler flag, lets say `-fvisibility=hidden` but I don't want that to become an option for the downstream users. So I go ahead, modify the package to compile with `-fvisibility=hidden` but the resulting package has the same hash as the previous one. Now my downstream users are not getting updated with the new package because the hash didn't change. Is it possible to generate a new hash or even better, add a build id that doesn't affect the versioning of the library I am packaging (e.g. something like `foo/1.0.4-5@bar/release`)?

**Comment by memsharded** [comment]
Not sure if I understand what you mean. Of course you can bump the version number of the library and your users will be able to update to the latest version, and get the changes. But I think that is not what you want.

So if you change something just in the build system, but conan is not aware of that change, it will generate the packages with the same hash. These updates are not automatically done in the client (it would be very costly to do it always), but users can check for latest with the ``conan install --update`` flag, have you tried it? This update is not hash-based, but content based, if the server files are different, they will be retrieved and replace the old ones.

Please tell me if this helps, or if you are looking for a different thing. Thanks!

**Comment by tareqsiraj** [comment]
@memsharded Sweet, `conan install --update` solves my current problem.

Just a thought, would it be difficult to introduce a `build_number` where the `major.minor.patch` version of the package remain unchanged? e.g. `foo/1.0.4-5@bar/release`. I'm asking because if an older revision of my code relies on an older built package, I can specify that in my `conanfile.txt` and reliably build any commit in my repo.

**Comment by memsharded** [comment]
You can do whatever you want with the ``version`` field, in the general case it is a string, you can put anything there. To introduce a variable number, you might want to NOT specify the ``version`` field in the recipe and use:

```bash
$ conan create Pkg/version@user/channel
```

But the version field, besides a string, can also have special meaning, following semver specification, X.Y.Z-W, means that W is a **prerelease** of X.Y.Z. If you are using version range specification as ``Pkg/[~X.Y]@user/testing`` you might be able to get different versions of X.Y.1, X.Y.2, etc... If at any moment you want to especify an exact version, of course you can, just specifying the complete version without ``[]``. You can access the **prereleases** specifying ``Pkg/[~X.Y.Z-]@user/testing`` (because pre-releases are considered testing/lower quality, and users have to explicitly opt-in for using them)

Also, if you are interested, there is a ``conan alias`` feature that allows to define which version to used, but not controlled by the consumer, but controlled by the package creator: http://conanio.readthedocs.io/en/latest/reference/commands/misc/alias.html

Please have a look and tell me.

**Comment by tareqsiraj** [comment]
@memsharded Thanks for the info. For now `conan install --update` is simple and solves our problems. I'll give the other options a time when I have some bandwidth and let you guys know if I run into problems. Should I close this issue or leave it up to you. Thanks for the prompt response.

**Comment by memsharded** [comment]
If no action from us is required at the moment, we can close it. But of course, feel free to re-open or comment if you have further questions. Many thanks!
