### ISSUE TITLE
Variable "conan_package" is not set in v0.28.1

### ISSUE THREAD

**Issue by CausticYarn** [conan-io/conan#1984]
I have several packages that use cmake to copy files directly to the package folder as detailed here:

http://conanio.readthedocs.io/en/latest/howtos/cmake_install.html?highlight=self.package_folder

However, in v0.28.x the `self.package_folder`  member variable returns `None`

Is this a bug or is there a new way to do this in 0.28.x?

**Comment by memsharded** [comment]
Do you mean ``conan_package`` (from the issue title) or ``package_folder``? 

Here it seems to work (with ``self.package_folder``), both with "conan create", and also using the local flow (install + build). Can you please provide reproducible steps? Thanks!

**Comment by CausticYarn** [comment]
I see, it still works in the "build" method.  Actually, I was using it in the "source" method because I have packages that are pre-built binaries and I simply extract them directly to the package folder.

Is this no longer supported in 0.28.x? Is there a better way to do this?

**Comment by memsharded** [comment]
Yes, it was removed from there for consistency. The thing is that the ``source()`` method is executed just once, for all the packages. So subsequents calls with different settings/options will use the previously cached sources, which will correspond to the old settings/options, and a tears and painful debugging.

Sorry for breaking, but we are doing a great effort to stabilize, get rid of some technical debt, in order to get out of beta. We prefered to do this now than later.

The solution is simple, just move that code to the ``build()`` method. Note that its naming is for building the package, not necessarily compiling binaries from source code. So the packages with pre-binaries can perfectly go there.  What do you think?

**Comment by CausticYarn** [comment]
Yes, that works just fine. Just wanted to see if this was expected behavior or a bug. You can close this ticket.
