### ISSUE TITLE
undocumented 'scope' argument

### ISSUE THREAD

**Issue by jeroendv** [conan-io/conan#1991]
The documentation on the --scope argument is rather thin.
what is is used for?
what values does it accepts?

a [search](http://conanio.readthedocs.io/en/latest/search.html?q=scope&check_keywords=yes&area=default) in the documentation only reveals that 
+ that 'test', 'create', 'info' and 'install' have such an argument.
+ a profile has  [scopes] section

But that is basically it.

**Comment by memsharded** [comment]
The scope is about to be deprecated, please don't use it. Everything it does could be done easier with environment variables, and if there is a specific need you think it is not addressed by env-vars, please submit a feature proposal. Thanks!

**Comment by jeroendv** [comment]
ok thx

I saw the following  in my default profile 
`
[scopes]
    dev=True
`
and just wondered what it was

**Comment by memsharded** [comment]
Yes, we cannot remove that yet, because of backwards compat, but will be a breaking change soon (if you use it)

**Comment by Aalmann** [comment]
Hi @memsharded 

Please do not remove scopes. Env vars are like global variables. Yes you can use them, but it is not a good design pattern.
I like to have something, which can only be used in recipes and which are not part of the hash. ==> scopes
Env vars could be used everywhere and it is hard to determine which tools uses which env var.

We are currently using scopes to:
* stop conan build after CMake configure ==> use case: the developer just wants to create a Visual Studio solution for developing the package without previous build (useful for large packages). This is done with a scope because there is no "configure_build()" method and command available.
* open the IDE after CMake configure ==> same as configure_build but with additional start of Visual Studio (or Eclipse if CMake generator is Eclipse CDT)
* enable and control test behavior: Because of long running tests we separated the tests from the package recipe (concurrent ci jobs), but to get them all in one solution for development, we have to setup CMake in a different way for that use case.

For sure, everything can be done with env vars, but you can also write a lot of code using global variables. ;-)

**Comment by memsharded** [comment]
> Env vars are like global variables. Yes you can use them, but it is not a good design pattern.

No, they are not. They are per-package (you can set them globally too). But per-package env-vars have exactly the same "scope" :) as scopes. Just in case, the syntax is ``PkgName:env_var=value`` (both in command line, and in profiles)

Please also check the attributes ``develop`` (http://docs.conan.io/en/latest/reference/conanfile/attributes.html#develop), and ``in_local_cache`` (http://docs.conan.io/en/latest/reference/conanfile/attributes.html#in-local-cache), I think they can cover the use cases you are talking about.

**Comment by Aalmann** [comment]
You are right, setting env-vars as command line parameter is nearly the same as scope. 
But imho env vars are very error prone. Some user will set them system wide, some will set them within the current session, probably a tool will (re-)set the environment variable, some user will set them in profiles and the rest will use the command line. So they are probably accidentally or not explicitly set. With scopes there are only 2 ways (not sure if there are more), using the command line and using profiles.
Concerning the attributes:
* develop: does not really work for me to determine if the create command is called by the user/developer or by the CI system. So I can't use it to enable/disable tests in the same package.
* in_local_cache: I have seen it  (that is what I would expect from "develop"), but that's only one flag and I need some more. That's why  I setup the scopes.

**Comment by memsharded** [comment]
I totally understand your point of view, and I am really, really sorry that we had to do this, but it was necessary to keep conan codebase maintainable, it is growing quickly, and the scopes feature wasn't adding any value that couldn't be implemented with env-vars. Of course, with the much bigger flexibility than env-vars propose (they can be set at different levels), there are some disadvantages, being its potentially large scope one of them. Being aware of this potential disadvantage, we took the decission because we weren't seeing issues in practice from our users, so they are not that problematic in real life. Actually we had some previous stories of users moving from scopes to env-vars, and they were happy with the movement.

For activating/deactivating tests, let me suggest another approach, that I think is interesting: using ``build_requires`` from profiles. Many times, tests are built and run using some framework that is defined as a build-requirement. If this dependency is expressed in a profile:
```
[build_requirements]
gtest/...@user/channel
```

Then you can easily use it from code: 
```python
def build(self):
        cmake = CMake(self)
        enable_testing = "gtest" in self.deps_cpp_info.deps
        cmake.configure(defs={"ENABLE_TESTING": enable_testing})
        cmake.build()
        if enable_testing:
            cmake.test()
```
This is very clean. If you don't have the build_requirement in your profile, then it won't be used, and tests won't run, without needing any scope or env-var configuration.

Again, I am sorry that this deprecation is an inconvenience for you, we sometimes have to take decissions regarding the wider community, and we still believe this is a correct one. Please let us know if we can help somehow else in the process. Many thanks!
