### ISSUE TITLE
Conan recipe "homepage" field

### ISSUE THREAD

**Issue by sigmoidal** [conan-io/conan#2048]
It would be great to provide a common method to include the homepage of the packaged lib/software. 

The 'url' field, according to [Conan docs](http://conanio.readthedocs.io/en/latest/reference/conanfile/attributes.html?highlight=url#url)  seems to be exclusively used in recipes to point to the repository of the recipe itself. A lot of these recipes (especially forks etc.) do not include any information about the location/origin of the project being packaged.

This however is not intuitive, sometimes the sources are not in the same place as the project homepage and are more often than not nowhere near the conan package recipe repo. Also some projects are outdated, have moved to new websites, yet the search engines will point them to the old site. This multiplies the amount of time users need to find the correct site.

I propose that a 'homepage' (or similar) field is introduced as a convention to allow (or imho even mandate) recipe authors to point to the original project website of a package. This will:

 - Save tons of time, since right now one will have to perform a web search to find the actual page (sometimes with mixed success)
 - Allow for meta-tools and recipe processors to provided richer information to users in a uniform way.
 - This is standard in just about every package manager. One actually almost never gets a url pointing to the repo of the package recipe itself, you get the homepage of the package. (look at Gentoo's Emerge, aptitude, yum)

**Comment by memsharded** [comment]
We cannot mandate that, because in many cases it won't make sense at all (for your own packages, or when packaging from the same repo).

But I agree it would be nice to define and document what would be the source URL of the original library, specially for OSS libraries. 

You suggest ``homepage``, don't know why, but not 100% sure. Any other ideas?

**Comment by sigmoidal** [comment]
'homepage' is used in many package managers and I think it is very intuitive and clear. Ones not using homepage, rely on 'url', which you already utilize.

I agree it cannot be mandated per se, but it is essential to include that in OSS recipes for building a quality repository of dependencies that is information rich.

You could introduce 'something_else' to be more verbose, but why not 'homepage' ?

**Comment by memsharded** [comment]
I didn't know other package managers used it. Then, yes, it might be a good name, thanks for telling.

**Comment by theirix** [comment]
Debian uses 'homepage' for an upstream location and 'Vcs-Git' for package sources. Homebrew also uses 'homepage' and 'url' accordingly. BSD ports are using 'WWW' but it is not clearly defined in a port file but parsed from pkg-descr. Even Bintray itself needs a link to an upstream website for a package - Website field and it can be filled automatically from the proposed field.
So the separation of upstream / package URls is pretty common and a 'homepage' is a widespread variant.

**Comment by solvingj** [comment]
This is parallel/relevant to another initiative/issue, which is focused on adding support to Conan to populate all the various metadata fields for all Bintray packages. My experience began with uploading RPM, DEB, MSI, and Nuget packages to Bintray from Travis, before I even used Conan. 

Thus, I've thought about this a lot and want to share my perspective before anybody starts coding anything.  

It's very important in this case to start by recognizing that Bintray supports multiple package/repo formats, RPM/Yum, DEB/Apt, Conan, Nuget, Maven, NPM, Docker.    While they all have some common metadata fields, we should begin by accepting that these formats are all different and unique, and will not ever converge to a common metadata. The respective package clients will never be able to support the additional Bintray metadata fields for uploading.  So, for full Bintray metadata support across all package formats, a separate call to the proprietary Bintray REST API seems the best approach.   

With that said **the Conan package definition is unique**.  First, Conan is now part of JFrog/Bintray.  Second, the Conan definition format is still in Beta, and still flexible compared to the others.  It COULD be updated to support Bintray's current metadata.  Alternatively, the Conan definition could be left alone, and the Conan client could have functions added to automatically make a separate Bintray REST API call, but then a separate "bintray definition" file would need to hold the extra metadata.

The second important thing we must acknowledge, is that the JFrog team has been working on this problem already for all the other package formats, and so we should not try to solve it in a vacuum.  The [JFrog CLI](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Bintray#CLIforJFrogBintray-UpdatingaPackage) is an important piece of the puzzle.  It provides a universal API for managing Bintray package metadata, and crucially it also distinguishes provides Artifactory support in addition to Bintray through the same CLI.  So, rather than Conan client calling the Bintray REST API separately, maybe someday it can leverage the JFrog CLI, although that dependency would not be feasible the way things are today.  Currently, I just perform `conan upload` and then manually perform `jfrog bt update-package ...` after to set all the metadata.  When handling boost packages, I script this.  

Currently, all metadata for the JFrog CLI have to be passed as CLI arguments.  There is no "jfrog.yml" or "bintray.yml" format yet, but perhaps they are working on such a thing.  In either case, I think engaging the JFrog CLI team to come up with something that fits into the bigger picture is better than adding fields to the Conan file to try and line up with Bintray. 

At least, that's my current perspective based on my work with multiple package formats.

**Comment by lasote** [comment]
Thanks for your feedback, good points.

**Comment by memsharded** [comment]
I agree that "homepage" could be added to the docs as the recommended way to address the original library (specially for third-parties) URL. Lets add it for next release.

**Comment by memsharded** [comment]
It has been already added to the docs: http://docs.conan.io/en/latest/reference/conanfile/attributes.html#homepage

As right now, conan is not processing it, as I don't think it needs a warning when not present, and is still not being processed by servers (it would be nice to have it processed in Bintray in the future), I think we are done here, but please re-open or comment if necessary. Thanks!
