### ISSUE TITLE
Building a mix of Release/Debug

### ISSUE THREAD

**Issue by Israphel** [conan-io/conan#2089]
I have a recipe for boost that depends on zlib and bzip2. All of them work great in shared, static, release and debug.

If I run this:
`conan install -s compiler.version=4.8 -o shared=True -s build_type=Debug`

The final package uses everything in Debug (Boost, zlib, bzip2).

If I run this:
`conan install -s compiler.version=4.8 -o shared=True -s build_type=Debug -s zlib:build_type=Release -s bzip2:build_type=Release`

I get different files (according to md5sum), but when I try to export the package the conan hash is the same.

Is it possible to do what I'm trying or I got it wrong?

**Comment by memsharded** [comment]
I think you want to make sure to which package are you applying the ``shared`` option. Please use the recommended syntax: ``-o PkgName:shared=True``

The md5sum for the final files (the lib, dll, etc) can be different for many different factors, compiler/linker might embed information about times, or absolute paths in the system in the final binary. That doesn't mean that the final package is ABI incompatible (because of embedding the paths, but it might be ABI incompatible because of linking with dependencies in Release mode)

The conan packageID, or hash, is an abstract, user defined identifier for the binary, constructed from the settings, options and dependencies information for the package. By default, the settings applied to dependencies do NOT change the current package ID. If you want to achieve that, you can use the ``package_id()`` method to define exactly which different binaries you want to build for your package. Please have a look at: http://docs.conan.io/en/latest/howtos/define_abi_compatibility.html (in your case, the ``full_version_mode`` could be what you are looking for), and tell me if you have further questions. Thanks!

**Comment by Israphel** [comment]
About the shared option, I'm "cheating" because I have this:

```
def configure(self):
    self.options["bzip2"].shared = self.options.shared
    self.options["zlib"].shared = self.options.shared
```

But I get your point, the recommended syntax is better.

I thought that dependency settings altered the packageID, like the option does.

About that link, that's great to know. But how can I export my two versions if they have the same packageID?

**Comment by memsharded** [comment]
Yeah, you don't need to propagate options anymore, now that you can set them with patterns, like:

```bash
$ conan install -o *:shared=True
```

Dependencies affect, but by default only the ``PkgName/MajorVersion``. So ``PkgName/1.3`` and ``PkgName/1.4`` still hash to the same packageID. You might be interested in CppCon talk:  https://www.youtube.com/watch?v=xA9yRX4Mdz0

They will not have the same packageID once you implement your ``package_id()`` method (maybe with the ``full_version_mode``), so you will have 2 different binaries, and you will upload both.

**Comment by Israphel** [comment]
I saw Diego's video when I started with Conan, that's how I started to be honest, but I should watch it again.
Thanks!

**Comment by memsharded** [comment]
Closing this question as stale, but please create a new ticket if there are further questions
