### ISSUE TITLE
Confusing 'conan info' output

### ISSUE THREAD

**Issue by jamezmoran** [conan-io/conan#2097]
Hi,

I've been trying to find a way to generate a list of depend**ent** packages given a package reference, although I'm getting a bit confused by the output of the 'conan info' command. When conman info is called on the dependent package, it lists the dependencies and within the output for those dependencies, it lists a "Required by:" section which displays expected output:

    $ conan info libcurl/7.56.1@mmi/stable
    Version range '>=1.8.0' required by 'libcurl/7.56.1@mmi/stable' resolved to 'libssh2/1.8.1@mmi/stable'
    libcurl/7.56.1@mmi/stable
    		ID: e7f4e58f064fd79ef7a1ff249dbe6fca37bf6f32
    		BuildID: None
    		Remote: None
    		URL: <Package recipe repository url here, for issues about the package>
    		License: <Put the package license here>
    		Updates: Version not checked
    		Creation date: 2017-11-29 12:06:24
    		Required by:
    				None
    		Requires:
    				libssh2/1.8.1@mmi/stable
    libssh2/1.8.1@mmi/stable
    		ID: 63da998e3642b50bee33f4449826b2d623661505
    		BuildID: None
    		Remote: None
    		URL: <Package recipe repository url here, for issues about the package>
    		License: <Put the package license here>
    		Updates: Version not checked
    		Creation date: 2017-11-29 12:02:04
    		Required by:
    				libcurl/7.56.1@mmi/stable

However, when the command is called on the dependency, the 'Required by:' section changes to 'None' which is not what I expected:

    $ conan info libssh2/1.8.1@mmi/stable
    libssh2/1.8.1@mmi/stable
    		ID: 63da998e3642b50bee33f4449826b2d623661505
    		BuildID: None
    		Remote: None
    		URL: <Package recipe repository url here, for issues about the package>
    		License: <Put the package license here>
    		Updates: Version not checked
    		Creation date: 2017-11-29 12:02:04
    		Required by:
    				None

Is this expected behaviour? Essentially, all I'd like to do is generate a list of the immediately dependent modules that will need to rebuilt if the root package is changed/upgraded. Currently, it seems to me the only way to do this is call 'conan info' on every package in the repository to generate a global dependency tree. I might also be doing things wrong as I've only just picked this up, so feel free to point me in the correct direction if I am.

Thanks,
James

**Comment by memsharded** [comment]
Yes, it is expected. The inverse model is not explicit in conan, you always need to define the downstream or "consumer" package or project that is the root node of the dependency graph. ``conan info`` follows the same logic than ``conan install``, the main difference is that it doesn't retrieve binaries or build them from sources, it just operates on package recipes.

The reasons are simplicity and scalability. The inverse model is not simple to obtain for conan packages, because the dependency graph is not unique, it changes for every configuration, it can (and often is) be different in different OSs, or just by changing some package options. Then you cannot query which packages are dependent on ``MyLib/0.1@user/channel``, the query could be which packages are dependent on ``MyLib/0.1@user/channel:63da998e3642b50bee33f4449826b2d623661505`` binary package, and the response can contain many different binary packages for the same recipe, like ``MyDependent/0.1@user/channel:packageID1``... ``MyDependent/0.1@user/channel:packageIDN``

So the actual query can be done, given to inputs: which are the packages that I need to rebuild if ``MyLib/0.1@user/channel`` changes for a given configuration, if my downstream is ``MyProject/2.0@user/channel``:

```bash
 $ conan info MyProject/2.0@user/channel --build-older MyLib/0.1@user/channel --profile=myprofile
```
That will give you a lists of lists of packages in the right order (packages in the same inner list are independent, so they can be built in parallel) to be processed.

I hope this helps, please tell me if you have further questions. Thanks!

**Comment by jamezmoran** [comment]
Thanks for the detailed response! Our scale isn't too large so we can probably work around this with some custom build scripts. It _might_ be worth making an FAQ question about though, I feel a lot of people will be wondering about conan's support for identifying/rebuilding dependants since it's required to keep the ABIs consistent between packages.
Cheers!

**Comment by memsharded** [comment]
Btw, you might find this video interesting if you didn't watch it yet: https://www.youtube.com/watch?v=xA9yRX4Mdz0

Also create issue in docs: https://github.com/conan-io/docs/issues/388

So at the moment it seems there is nothing to be fixed inmediatly in conan codebase, so I think this issue could be closed, wdyt? Many thanks!

**Comment by jamezmoran** [comment]
Thanks for the link, I'll definitely take a look at it when I get some time.

Thanks!
