### ISSUE TITLE
AttributeError: 'module' object has no attribute 'X509_up_ref'

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#2102]
Hi everyone,

We have this error, which has started occurring consistently across all MacOS builds on travis:

https://travis-ci.org/bincrafters/conan-glfw/jobs/310371917

Any help would be appreciated.

**Comment by lasote** [comment]
Thanks for reporting, it confirms an issue we spoted yesterday. The pyOpenSSL package has been updated, and now it requires a cryptography that is not in the valid specified range for the conan requirements. At the end it fails because of the missing module updated.
We need to release a minor version, will try to do it asap.

**Comment by lasote** [comment]
From https://pypi.python.org/pypi/pyOpenSSL

```
Release Information

17.5.0 (2017-11-30)
Backward-incompatible changes:
The minimum cryptography version is now 2.1.4.
```

**Comment by dimi309** [comment]
Thanks for the quick response!

**Comment by lasote** [comment]
Relaunch the build, it should be ok now!

**Comment by dimi309** [comment]
Ok, thanks a lot! I'll report back with the results 😃

**Comment by theirix** [comment]
Works now, thanks!

**Comment by dimi309** [comment]
Great then! Thanks @lasote !!
And thank you too, @theirix my builds were stuck in the queue 😄

**Comment by lasote** [comment]
Thanks both for reporting the error and confirming the fix!!!!!
