### ISSUE TITLE
Can you parameterize a build on the compiler.libcxx setting?

### ISSUE THREAD

**Issue by ohz10** [conan-io/conan#2115]
Last week I spent a significant amount of time tracking down an issue that turned out to be an incorrect `compiler.libcxx` setting in my default profile. See Issue #1788. 

The symptom was a linker error. 

I was wondering if there's a way to parameterize a build on this setting, like we might do with `settings = "os", "compiler", "build_type", "arch"`. Reason being, I'd like a `conan install ..` to fail when there is no matching binary libs rather than generating linker errors.

**Comment by memsharded** [comment]
Hi Austin!

I am not sure of what you mean. You can do:

```bash
$ conan install .. -s compiler=gcc -s compiler.libcxx=libstdc++11
```
Is that what you mean?
The ``conan install`` you did, can't fail, because there is a matching binary. A binary compiled for ``libstdc++``, which is the binary you requested. It is impossible to know that you are going to consume it with a libstdc++11, unless you tell the system. Please note that the building/linking is actually decoupled from conan.

I know that ``libstdc++`` is not the best default always, but as usual, it is a tradeoff, we think it is not bad for many cases, or at least it is the least bad choice. Of course, the real way to go is use your own profiles, not the default one.

**Comment by paxos1977** [comment]
@memsharded I mean, is there a way to encode the `compiler.libcxx` setting as meta data in the conan packages such that `conan install ..` would fail if my current `compiler.libcxx` didn't match a pre-built binary? 

We're currently considering going down the profile path, but that has its own drawbacks. E.g. managing and deploying a standardized set of profiles that will work for the entire team, and we're a motley crew.

**Comment by memsharded** [comment]
Conan already fails if your current ``compiler.libcxx`` doesn't match a pre-built binary. You can easily try, for example, against conan-center:

```bash
conan install Poco/1.8.0.1@pocoproject/stable -s compiler="Visual Studio" -s compiler.version=9
...
zlib/1.2.11@conan/stable: WARN: Can't find a 'zlib/1.2.11@conan/stable' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=9, os=Windows
- Options: shared=False

ERROR: Missing prebuilt package for 'zlib/1.2.11@conan/stable'
Try to build it from sources with "--build zlib"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```
It think there is something we are both failing to understand each other :)

Regarding the profiles, don't worry, you have ``conan config install``, not only for profiles, but other conan config. It is very useful, have a look: http://docs.conan.io/en/latest/reference/commands/consumer/config.html#conan-config-install  The docs are a bit sparse yet, but you can do many things with that, in next release, even provide your own conan extensions. Please do not hesitate to ask if you have questions about it!

**Comment by cleeland** [comment]
> It is impossible to know that you are going to consume it with a libstdc++11, unless you tell the system.
That sounds like a flaw of omission.  It seems that the pre-built binary of a library ought to declare to the consuming environment HOW it was built and what flags need to be set in order to use that binary properly.  `conan` already recognizes this by capturing `#define` settings.

It seems this same issue has been encountered in the past and no real resolution: #217, #551

**Comment by niosHD** [comment]
Hi all, yesterday I spent several hours to hunt down exactly the same issue which was described in the first post.

More concretely, my default profile has been automatically generated as `compiler.libcxx=libstdc++` which seems to be intentional according to #1788. At the beginning everything worked fine as I tested out various community maintained packages. However, as soon as I started to package and use my own library and use it from a consuming project, linking started to fail.

The reason is very simple. Since the library I packaged does not have any dependencies I did neither inject `include(conanbuildinfo.cmake)` nor called `conan_basic_setup()` in the cmake build system of the library. However, exactly these operations are needed in order to actually support building the library with the old ABI. Retrospectively, it was simply my fault/inexperience which lead to this problem. However, given that already several people had this problem indicates that there is a demand for a solution.

James proposed in [#217](https://github.com/conan-io/conan/issues/217#issuecomment-283506936) that something like the following code snippet can be used to diagnose/prevent the confusion:
```python
def configure(self):
    if self.settings.compiler.libcxx == "libstdc++":
        raise Exception("This package is only compatible with libstdc++11")
```
Now that I know about the problem, I agree that this is a suitable way to express the ABI constraint. However, the problem is that I need to be aware of the possibility to use different libstdc++ versions in order to get it right. I for example knew nothing about it until I had to hunt this bug down and I am pretty sure that most other (first time) users do not know either. I think that it is therefore important that the default behavior of conan protects the user from such faults.

It would, for example, be an idea to use a white listing approach for the supported `compiler.libcxx` settings. More concretely, the idea would be that the writer of the `conanfile.py` has to explicitly enable the support of different libcxx versions for the package. Without it, only the default ABI of the compiler would be supported by the package and the previously `configure` check could be automatically done by conan. What do you think?

Best,
Mario

**Comment by memsharded** [comment]
This ticket is stale. A few things have changed since then:

- The new ``validate()`` methods allow to define not supported configurations
- Better profile detection in Conan 2.0, with detection of libstdc++11, and warnings about it

Otherwise, the idea of having recipes defining their "supported" settings never didn't fly. There was some syntax to support it, constraining the available values, but users really never used it, and it was complicated. We have learned also in this time that this approach will not scale, beyond the ``validate()`` method.

In practice, this has not been necessary, and once the libstdc++11 thing is known and changed, things are smoother. Closing this ticket as not planned, thanks for the feedback.
