### ISSUE TITLE
Selective retrieve submodules from a big package

### ISSUE THREAD

**Issue by danielhalati** [conan-io/conan#2121]
This a question. Assume that I have QT 5.7.1 as a conan package. Can I request parts of QT, like Core and Widgets only even if the package is bigger? I don't want to link the whole package

**Comment by lasote** [comment]
No, the conan package will be retrieved (for your specific configuration) as a whole. That's why the community is willing to split "monster" libraries like Qt and Boost (that @bincrafters already split) into smaller packages.

**Comment by memsharded** [comment]
Also, one thing is to retrieve a whole package and another is to link it. Conan usually provides information in the generators that could help to link with only some libraries. For example, you could filter the ``${CONAN_LIBS}`` cmake variable of the cmake generator to use only the libraries you want, that can be done in very few lines of cmake code.

**Comment by tonka3000** [comment]
@memsharded how can i filter it? Mostly i use cmake targets (which is the recommended approach from cmake) to link my targets. Is there any possibility to make sub target in one recipe?

**Comment by memsharded** [comment]
@tonka3000  The package authors doesn't have access to the targets that are created, because, as you know, the ``package_info()`` method is agnostic about the build system use to consume that package, that can be many, not just cmake.

But, for the ``cmake`` generator and ``conanbuildinfo.cmake`` we have just added a new section to the docs, explaining the targets that are created: http://docs.conan.io/en/latest/reference/generators/cmake.html#targets-generated-by-conanbuildinfo-cmake
So, the way to filter would be with some cmake code, that will keep only the desired targets. 
I am curious, the linker usually makes a good job, and if anything is just a matter of optimizing the linking time, but many times the overall effect on building time for this optimization is small. Are you having a performance problem?

**Comment by tonka3000** [comment]
Hey @memsharded 
, no, i have no performance problem. I try to build a Qt recipe, which cover all of Qt. I try to make multiple recipes like bincrafters has done that for boost, but that is not really a working approach for Qt (the whole framework) because there is no one to one relationship between shared lib and a package.
So now i've started with the qtbase recipe, which is the core framework for the rest of Qt. I want to make the libs which are in Qtbase available as single entities (in cmake targets) because of clarity. When i build a dependency tree, i always get one Qt dependency for each of my module, which is very untransparent. The are also some kind of projects (like google test) f.e. where you have a static lib which adds a main function to your lib, and so i can compile some projects without some troubles (my own project has to static libs with main functions for import and i can't provide them in conanfile.py, because when i use the target from conan my two main's are clashing).

The `CONAN_LIB::PkgName_LibName` approach sound interesting, but i'm not sure if that could handle debug/release config as well (i also have to try it out 😄 ). I would be very nice if conan could offer something like a "submodules" like you did it with debug/release variables in package_info and self.cpp_info, because i think that would be also compiler agnostic, because in cmake you can create multiple targets/variables, in Visual Studio you can create multiple props files and i think that would be possible for any build system. If some build system does not support that you can simply fallback to combine the given submodules as one. With that approach it would be also possible to set different settings for different submodules/targets.
Would such thing possible?

**Comment by solvingj** [comment]
We recently had a great contribution in the form of a custom findBoost.cmake that works with the bincrafters modular boost packages. Specifically, it translates the individual Boost targets into components of a parent target. 

https://github.com/bincrafters/community/issues/26

First, it seems likely that we would need a custom findQt.cmake for Qt packages.  Furthermore, it's possible that this approach would give you a different type of granularity when compared to the current Conan targets approach, which might let you get around your problem.  I have to admit, I'm not sure if it will or won't, but things like this often open new doors.
