### ISSUE TITLE
Default meson building fails

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2133]
The docs describe: 

```python
    def build(self):
        meson = Meson(self)
        meson.configure()
        meson.build()
```

But this fails in a conan create with:

```bash
Error during basic setup:

Source and build directories must not be the same. Create a pristine build directory.
```

**Comment by memsharded** [comment]
```python
def build(self):
        meson = Meson(self)
        meson.configure(source_dir="src", build_dir="build")
        meson.build()
```
This seems to work (for code exported in ``src`` folder). Maybe convert this to the default?

**Comment by memsharded** [comment]
The correct line that works for both ``conan create`` and the local flow is:

```python
def build(self):
    meson = Meson(self)
    meson.configure(source_dir="%s/src" % self.source_folder, build_dir="build")
    meson.build()
```

This is identical to what is necessary in the ``CMake`` helper. Maybe the confusing part is that ``meson.configure(source_dir="src", build_dir="build")`` doesn't automatically use ``self.source_folder`` and ``self.build_folder`` as prefix. Can this be improved without breaking @lasote?

**Comment by memsharded** [comment]
I have submitted a PR with a full example in the docs: https://github.com/conan-io/docs/pull/399

**Comment by lasote** [comment]
In the CMake build helper the custom directories are not prefixed either with `self.source_folder`or `self.build_folder`. But CMake doesn't require a different directory for src and build. It could be done for both, but I don't like it, I think it's more clear to explicitly use `self.source_folder` if you want to change the `source_dir`.  

About the example, `build_dir="build"` works, because the build() method guarantee that the cwd is the self.build_folder, same reason than above, for me is much more clear to use `self.build_folder` explicitly.

**Comment by memsharded** [comment]
Just another idea to discuss:

```python
def build(self):
    meson = Meson(self)
    meson.configure(cache_src_dir="src", cache_build_dir="build")
```
They will be used when in local cache, and disregarded otherwise.
Same for ``CMake`` helper. I think with this it is explicit, it is simple, it doesn't break existing recipes and is fully compatible with cache and local flows. What do you think?

**Comment by agauniyal** [comment]
Out of source builds are preferred regardless of choice of build system 😄 I think every generator would benefit from this(not just meson) and will fix meson as well 👍

**Comment by lasote** [comment]
Ok @memsharded. I'm ok with that.
