### ISSUE TITLE
Add the --file parameter to conan source and conan package commands

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#2143]
The install and the build command have the --file parameter. However, package and source have not. When having two conanfiles in the workspace, the --file parameter would be convenient to have.

**Comment by memsharded** [comment]
We are most likely moving to a different UI, because the current one is a bit redundant. All commands have a path, like ``conan source ..``, or ``conan package ..``, and then the ``file`` argument. For conan 1.0 we are planning all commands be able to do ``conan source ../myconanfile.py``, or ``conan install myconanfile.txt``.

**Comment by memsharded** [comment]
The command line UI has been revamped for conan 1.0.0-beta:  http://docs.conan.io/en/latest/conan1.0.html 

Please have a look, try it, and report as soon as possible, so things can be fixed before the final release. Thanks very much!
