### ISSUE TITLE
Deprecate conanfile_directory

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2145]
The only place really use is virtualenv.py, for something not very important.

It will break existing recipes using it.

**Comment by mpdelbuono** [comment]
Hmm... we currently have a package that exports a batch file via exports_sources. It then calls that batch file during the build step via:

```py
        buildFolder = os.path.join(os.path.abspath(self.conanfile_directory), "Build.cmd")
        if self.settings.build_type == "Debug":
            self.run(str(buildFolder) + " /config Debug")
        elif self.settings.build_type == "Release":
            self.run(str(buildFolder) + " /config Release")
```

I'm not opposed to getting rid of conanfile_directory, but do you have a recommendation on how to approach this? We used conanfile_directory here because it was the only way we could identify to get the build directory where the Build.cmd file was exported to during `conan create` or where the file is located during `conan build`.

Note that while the current working directory is often the correct location, if `conan install --install-folder .build` and a following `conan build --build-folder .build` is run, then the current working directory would not be correct (however self.conanfile_directory would point us to the sources correctly).

I think this is our only use of conanfile_directory to date.

**Comment by memsharded** [comment]
Yes, I think that file should be copied both to the source folder, and to the build folder (in general, the source folder is the same as the build folder, unless you defined ``no_copy_source``). So I would say that this should work:

```python
buildFolder = os.path.join(self.source_folder, "Build.cmd")
```
Please note also that in the local commands you can specify the source folder too if you want, because locally it is a different one from the build or the one containing the conanfile: ``conan build .. --source_folder=...```

Please have a try and tell me, thanks!

**Comment by mpdelbuono** [comment]
I ran through all of our workflow test cases and it looks like this works, thanks!

(We do occasionally use no_copy_source, but I have also verified we can correctly select source vs. build folder in these cases.)

**Comment by memsharded** [comment]
Excellent, thanks very much for the feedback @mpdelbuono
