### ISSUE TITLE
Switch from node-semver to python-semver

### ISSUE THREAD

**Issue by xvitaly** [conan-io/conan#2172]
Switch from [node-semver](https://github.com/podhmo/python-semver) to [python-semver](https://github.com/k-bx/python-semver) because node-semver:
1. no longer support Python 2;
2. unpopular.

**Comment by memsharded** [comment]
Thanks for the suggestion. I wish it would be possible, but [python-semver](https://github.com/k-bx/python-semver/blob/master/semver.py) does not implement some needed features that node-semver does:

- Ranges matching
- ``max_satisfying`` logic for sets of versions and a range expression

So I would love to see python-semver implements those and we could switch, but at the moment it is not possible.

**Comment by jnnnnn** [comment]
We also need this. The fact that node-semver does not allow pre-release tags as part of its range matching forces our CI process to be quite contorted. At least python-semver's admittedly basic range matching allows this:

```
In [2]: semver.match("3.4.5-pre.2+build.4", ">=1.0.0")
Out[2]: True
```

I will investigate implementing the max_satisfying logic and `.X` logic in python-semver. I guess we will also need a way to specify whether to include pre-release builds as part of the range specification... perhaps a trailing `-`?

**Comment by memsharded** [comment]
Hi @jnnnnn 

Thanks very much for your offer, it would be great if possible (though last time I checked seemed non obvious)

Just for your info, the current way to specify pre-releases is already done with the trailing "-". You can check tests in 
https://github.com/conan-io/conan/blob/8f9f56496249247ec619d9e973b6b6a73031e433/conans/test/model/version_ranges_test.py#L22

**Comment by jnnnnn** [comment]
Thanks, that is very helpful! I will look at implementing the required functions in python-semver.

**Comment by jnnnnn** [comment]
I am very surprised about the `-` thing to specify pre-releases. This seems to go against the specification that `node-semver` is implementing: https://github.com/npm/node-semver#prerelease-tags

**Comment by jnnnnn** [comment]
I would also like to mention python's `packaging.version` [core library](https://packaging.pypa.io/en/latest/version/). It looks like it also satisfies most of the requirements of #640.

**Comment by jnnnnn** [comment]
Regarding the trailing `-` (https://github.com/conan-io/conan/issues/2172#issuecomment-385645677):

This only matches against pre-release tags if the actual semver is fully specified. For example, a specifier of `~19-` or `19.X.X-` will not match the version `19.3.2-pre.1`.

This doesn't really work for us, because we have more than three thousand projects (about 1000 libraries and 2000 leaf projects). Updating dependencies manually every time something gets released is not practical. We would like our CI to always be building against the latest versions, even if it is a pre-release.

I would much prefer that we had more reliable tests for each library, and could guarantee releases without having to perform integration testing with downstream consumers of the library. That is not the case for us at the moment.

I am aware that python's `packaging.version` also does not allow our desired behaviour, which makes me think that this may be an unreasonable request.

Our current solution is to do each CI build as a new `patch` release -- the build after `19.3.2` would be labelled `19.3.3`.

**Comment by memsharded** [comment]
> This only matches against pre-release tags if the actual semver is fully specified. For example, a specifier of ~19- or 19.X.X- will not match the version 19.3.2-pre.1.

I understand, but I think that would be explicitly against semver that clearly states:

> "For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by 3.4.5-alpha.9, even though 3.4.5-alpha.9 is technically "greater than" 1.2.3-alpha.3"

I have sometimes been tempted to define a 4th number. Maybe your use case is more the one of "package revisions", not sure if you are already following it, please check: https://github.com/conan-io/conan/issues/798

**Comment by jack-sanchez** [comment]
Just thought I'd swing by with an update to bump this issue.

I just wroteup this issue report on the node-semver pip module which Conan uses.
https://github.com/podhmo/python-semver/issues/39

There is an annoying conflict which set me back a couple days before I uncovered that our internal version script based on the _actual_ [python-semver module](https://github.com/python-semver/python-semver) will not work in an environment with Conan installed because Conan uses a versioning library which has poor naming.

Obviously a PR to the podhmo/python-semver module would be a breaking change for any downstream project (including those which I have no knowledge of) and I cannot simply suggest the PR with the appropriate changes. However, changing the name of the module appears to be the least disruptive solution to everyone involved, so that Conan does not have to change their implementation details, simply update an import statement and requirements.txt when the podhmo/python-semver module has been corrected.

**Comment by raphaelzulliger** [comment]
Just partly related to this issue, I as well run into problems with podhmo/python-semver while using Conan, see podhmo/python-semver/issues/37. To be honest, I'm surprised no other Conan users run into these issues. At least I couldn't find a related bug report.

Unfortunately, there was no feedback from the author yet. Maybe it would be helpful if more people up-vote that issue.

Also: I wonder whether I should open a Conan issue to address these "range issues" explicitly, which may be helpful for other Conan users running into this.

**Comment by identify3d-joe** [comment]
The fact that node-semver and semver cannot be in the same environment is a real pain. For example, I am trying to run both conan and nexus3-cli in the very regular use case of trying to query both artifactory and nexus in the same script. Can't do it......semver conflict. I am sure this same issue is related to any other library that uses python-semver.

**Comment by memsharded** [comment]
Sorry @identify3d-joe can you clarify this a bit? So you can't install Conan and nexus3-cli in the same python environment with pip? Which pip dependencies are raising a conflict?

**Comment by identify3d-joe** [comment]
If you do the following:

pip install nexus3-cli
pip install conan

then try to run:

nexus3 -version

You will get a semver error because node-semver just clobbered semver

This is a documented error in the node-semver issue list from March of this year:

https://github.com/podhmo/python-semver/issues/39

Unfortunately, there doesn't seem to be a work-around. 

As a side note, that was a quick response. :)

**Comment by memsharded** [comment]
Ok, I got it, thanks for explaining, I was not aware of of https://github.com/podhmo/python-semver/issues/39
This is unfortunate. At the moment it seems extremely unlikely that we could do this switch without breaking behavior, and also it seems that there are some gaps in ``python-semver`` or ``semver`` wrt the ``node-semver``, like the resolution of a version range from a list of available version, so we would need to implement that, with also high changes that we would be introducing bugs. 

Lets try to do the switch in Conan 2.0.

At the moment, the only workaround I could imagine is running the "pyinstaller" version of Conan with the python interpreter bundled. It will run as an executable and not interfere with other python things. If the Windows or Deb installers are not enough, you can build a self-contained .exe with the ``pyinstaller.py`` that exists in the root of the repo.

**Comment by identify3d-joe** [comment]
This seems reasonable. 

The installer version that you suggest won't work because I actually am using the your python interface to do some interesting things in python such as implementing a "get latest version" function to mirror the functionality in Maven.

However, in this case, the functionality of nexus3-cli is easy enough that I spent an hour or so and just wrote the minor functions I needed using the requests library and the raw API. Not ideal, but better than the alternatives.

Keep up the good work.

**Comment by memsharded** [comment]
Ok, good to know you could workaround even the pyinstaller was not an option and thanks for the kind words!

**Comment by Viatorus** [comment]
Today. we also got a collision using (python-)semver and conan because of the package name conflict. The project node-semver seems to be no longer maintained. I hope you can switch to python-semver in 2.0!

**Comment by memsharded** [comment]
We have finally decided to implement our own semver functionality inside Conan, including flexible versioning (any number of digits, mixing letters and numbers) and version ranges. The move has already been done in ``develop2`` and will be available in next alpha2 (you can already get alpha1 in PyPI), so no dependency anymore to either node-semver nor python-semver. So this can be closed. Please report any issues of the new implementation using the ``[develop2]`` or ``[conan2]`` tags in title, thanks!

**Comment by Viatorus** [comment]
Good move! Thank you. :)
