### ISSUE TITLE
Default --source-folder in export-pkg

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2174]
it is:
 ``` 
--source-folder SOURCE_FOLDER, --source_folder SOURCE_FOLDER, -sf SOURCE_FOLDER
                        local folder containing the sources. Defaulted to
                        --build-folder. A relative path to the current dir can
                        also be specified
```

Maybe it is better to default it to the ``path`` directory, where the conanfile.py is, whish by default is similar to the cache build folder.

**Comment by lasote** [comment]
I'm not sure. It depends on how are you using the local methods. Probably the default to `build_folder` is not the most accurate for most cases, where the build folder is a clean folder without sources, but defaulting it to `path` is not either accurate. It depends on the parameter `--source-folder` of the `conan source` command. In the local cache, the sources are there because it is the `build_folder` with a copy of the sources, not because is the folder containing the `conanfile`. Maybe it shouldn't default to anything.

**Comment by lasote** [comment]
You were right, the default of the build is also relative to conanfile, so it's ok. Please add it to the beta5 branch
