### ISSUE TITLE
What exactly are the problems with conan standalone installer (in Windows)?

### ISSUE THREAD

**Issue by mmatrosov** [conan-io/conan#2196]
We are going to utilize conan for our Visual Studio solutions. We have ~100 of Windows dev machines. We would like to have a centralized way to control state of conan on all dev machines. Our IT department can issue some tasks and execute some scripts on all machines via Software Center. But the most convenient way to use it is to have a dedicated installer for conan as a stand-alone application. Otherwise, there are a lot of problems to solve:
* What if different users have different versions of python?
* What if a user accidentally updates his python packages and end up having different version of conan?
* What if when we are going to deploy conan, a user already has python installed? What if it is installed in a non-default location?
* What if we are going to update version of python, in which conan is installed?
* What if user messes with his own installation of python for experiments, and breaks conan for some reason?

All these problems would become irrelevant if we used stand-alone conan application. However, documentation strongly discourages this option. Why? I have tried it for some time, and it worked fine. What exactly are the problems? Maybe they are not relevant for our environment? Maybe we can compile conan ourselves with Py2Exe or something, so we don't have such problems?

**Comment by mpdelbuono** [comment]
Well I can at least tell you one, (#2184)

I'll admit until this point I have been using the Windows installer and have not run into other issues, but obviously that does not mean they do not exist, as my use cases are limited.

That being said, I'm hard-pressed to think of a reason why a user messing with python themselves would somehow break conan. The use of pip should guarantee that the requirements are satisfied, no matter what the user does (unless they totally break python to begin with). This also solves your 'user already has python installed' and 'user has different version of conan installed' questions because pip should take care of that. In fact, I think pip might be better here, because the windows installer would have trouble detecting that conan is already installed if the user already installed it via pip. You would then potentially have a PATH conflict.

**Comment by memsharded** [comment]
Other issues that you might have with installers:
- They might not embed the full python standard library. One issue we had in the past is users trying to use python ``glob`` in their recipes, failing in the installed (as non-existing module) and ok in the ``pip`` one.
- You cannot integrate with other python tools, or packages. One of the reasons conan uses python recipes is because many users were already using python and developing tools for C++ in python. With the ``pip`` package, you can use any other python library and package installed in that interpreter. With the installed version, it is not possible to extend
- Some minor differences in the way the command line is parsed, requiring quotes or misunderstandings about arguments if not using ``--arg=value`` (i.e. failing for ``--arg value``)

Regarding your questions:
> What if different users have different versions of python?

Conan runs in different python versions, from 2.7 to 3.6: Changing the python version shouldn't have effect on the functionality. Conan includes a py2to3 linter that will warn if working in py2 and introducing py3 incompatibilities.

> What if a user accidentally updates his python packages and end up having different version of conan?

Updating python packages might affect in very limited cases for conan dependencies. As conan is mostly a "end-user" tool, there are no other popular python packages requiring conan as a package. The only way to change the conan version is a ``pip install conan --upgrade``, which is quite explicit.

In any case, if using python, not just for conan, but for any use of python, we strongly recommend using virtualenvs (I use ``virtualenvwrapper`` tool).

> What if when we are going to deploy conan, a user already has python installed? What if it is installed in a non-default location?

Conan should work with most "normal" python distributions. If not, creating a virtualenv to run conan would solve it.

> What if we are going to update version of python, in which conan is installed?

I am not sure python upgrades in-place that easily (not just for conan). But as I said, we try hard to keep conan compatibility with the most widely used python versions.

> What if user messes with his own installation of python for experiments, and breaks conan for some reason?

Any experiment with python and other projects should be done using virtualenvs. This is not a conan thing, of course.


I know that running conan in the system python installation might not be 100% rock solid (but what is). In practice we haven't been reported any incident. For better management of a python based tool, using virtualenvs much it much more robust.

I know that such virtualenv is an extra step, and that could introduce some friction. This is why we are releasing the installers. As you said, they work quite well, and should be problem free 97% of the use cases. But we suggest the python-pip installation as the "ground-truth" one, the one we know run with less issues. But if you are in a controlled environment, an installer should be good. The strong discourage for it is mostly because that 3% of the time can still generate quite a few support requests, people wasting time debugging something that is not really conan related, but some limitation of the installer version, etc. 

You don't need to figure out how to create the "exes", we had already open-sourced the creation of the executable too, this is the script used for that (using pyinstaller): https://github.com/conan-io/conan/blob/develop/pyinstaller.py. Overall and despite those cited limitations, it works pretty well, I doubt that an exe created with py2exe or other tool would have less issues.

Please let me know if the above makes sense and if you have further questions :)

Cheers!

**Comment by mmatrosov** [comment]
> In any case, if using python, not just for conan, but for any use of python, we strongly recommend using virtualenvs (I use virtualenvwrapper tool).

Cool, I will learn this stuff and maybe return with more questions :)

> As you said, they work quite well, and should be problem free 97% of the use cases. 

Hm. I just thought. The installer will only be used for _consumers_. Only few developers will be creators. And they can install conan with pip manually. How do you think, if we are only talking about consumers (i.e. `conan install`), is this 97% still the case? Or maybe it will be more close to 100%?

**Comment by memsharded** [comment]
> Cool, I will learn this stuff and maybe return with more questions :)

Sure, glad to help :)

Yes, for consumers the ratio can be higher, indeed, because they are using less functionality. But if the creators are still using the full-fledged python installation, and lets say, they add an ``import to.my.tool`` in package recipes, of course that will fail in consumers, because such module will not be in their systems. 

But when I am talking about that percentage is not in terms of time, but of use cases. If your environment is controlled, lets say you don't have huge packages (>Gb), you don't use other python tools that you want to integrate in conan, etc., you can be good 100% of the time.

**Comment by memsharded** [comment]
If this is more or less answered, maybe this could be closed an open a new issue, to discuss and track it: https://github.com/conan-io/conan/issues/2207

**Comment by mmatrosov** [comment]
Agree. thanks for the info.
