### ISSUE TITLE
'conan install --build never' having problems with upstream 'build_policy = "always"'

### ISSUE THREAD

**Issue by hamparawa** [conan-io/conan#2203]
Hi,
In the `conan install` command help documentation, in the `--build`  section

> Optional, use it to choose if you want to build from sources: --build Build all from sources, do not use binary packages. --build=never Default option. Never build, use binary packages or fail if a binary package is not found. 

Eventhough it is stated that `--build=never` is the default option, I'm seeing two different behaviors when any of upstream packages has defined `build_policy = "always"` in the recipe.

When using `--build=never`, nothing is re-built. And the command successfully executes when there are already pre-built binaries present in the cache.
However, when not using `--build` option, the upstream package is rebuilt.

If this is intended behavior, stating it in the documentation would be much helpful.

Thanks.

**Comment by memsharded** [comment]
Yes, this is intended behavior the logic is:

- The end-user should always have control. If they say ``never`` it should be never. Lets say this is the highest priority
- Then package recipes have second priority. They can override and change default behaviors
- Finally, it is the default behavior of not building binaries, unless someone else (recipe or end-user) explicitly declare it

(Side note: I am not a big fan of ``build_policy="always"``, it should be used only for "develop" packages that are continuously overwritten, and with cautions)

Then, yes, that can be clarified, the default option is not exactly ``never``, because recipes can define an alternative build-policy. This is is the ``conan install --help`` right? Thanks for raising this!

**Comment by hamparawa** [comment]
Yes. It is the `conan install --help` output.
Thanks.

**Comment by memsharded** [comment]
Good! Suggesting new help text in #2205
