### ISSUE TITLE
Windows installer for 64 bits

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2207]
Current self-extracting windows installer is py2.7 based (and 32bits, which is the windows default).

Maybe it should be moved to py3.6 (64bits)? 

Please, users using the installer, feedback appreciated!

**Comment by mmatrosov** [comment]
Totally agree, it seems strange that there is only one installer for older python and older platform. You might provide several installers, but latest (3.6) python and latest (64-bit) platform should definitely be among them.

**Comment by mpdelbuono** [comment]
While I have since moved onto the aforementioned pypi proxy model, I expect there are users that will be unable to use that model while having a similar use case to mine. In those cases, a 64-bit installer would be helpful.

I also expect those users don't care what version of Python is bundled (only that it's 64-bit) and so a Py3 version should be fine. It will also make unicode issues work better too.

**Comment by lasote** [comment]
I generated an installer with python 3.6 and x64, it requires some changes so, please, if anyone can try it will be very welcomed. It's on the release page:

https://github.com/conan-io/conan/releases/download/1.0.0-beta.2/conan-win_1_0_0-beta_2_x64.exe

@memsharded if you can recall some problem we had with the windows installer please try it, I had to change many things in the pyinstaller invocation and iss scripts.

**Comment by memsharded** [comment]
The installer doesn't work, can't find the exe. I am investigating if it is only a path issue.

**Comment by memsharded** [comment]
@mpdelbuono @mmatrosov @Croydon @BattleBas

Py3-64bits installers for Windows are available for conan 1.0-beta4 at: https://github.com/conan-io/conan/releases

It would be great if you could test them and report if something fails. Many thanks!
