### ISSUE TITLE
Conditional build_id

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2225]
Hi,

I have a question about the `build_id` method, I only need it on Windows to avoid building twice `Release/RelWithDebInfo` packages.

However it seems to be active on other OS as well, which is quite annoying when debugging recipes on Linux for example.

Indeed, each time there is an error when building/packaging, the next invocation of `conan create` will go directly to the `test` step.

Is there a way to prevent this behavior without removing `package`/`build` folders each time? I understand that this will still happen on Windows, but I'm fine with that.

**Comment by memsharded** [comment]
Yes, that is totally true. 
This is because the existence of the ``build_id()`` method is the criteria used for triggering this behavior, but the contents of the ``build_id()`` method are more difficult to know if they affect or not, unless you fully evaluate it. Right now there is now way to prevent this behavior, so the removal is necessary.

I think it could be analyzed if a check of the resulting "build_id" and a comparison with the unmodified "package_id" could be used for a smarter trigger. But this requires careful analysis and testing, lets aim for conan 1.1 or 1.2. Thanks for the feedback!

**Comment by theodelrieu** [comment]
Glad to hear!
