### ISSUE TITLE
Enhancement: Remote fallback to earlier version

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#2244]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 0.30.3

If all of the following conditions are true:
- A requirement is specified using a version range
- A version exists in the local conan cache
- The local conan cache version is ineligible for use (i.e., no sources, no prebuilt package matching settings)
- That version does not exist in the remote, but another version exists

Conan will go to the remote to find the exact version matched locally, but then fail to find it on the remote, and then give up with an error message, despite the fact that a matching version is available.

I think conan should instead attempt a search on the remote and pick a version. This way it acts the same as if the package didn't exist in the local cache at all. Note that probably the most significant use case for this is when a newer version hasn't yet been uploaded to the remote, and so conan will simply fail to find the newer package, rather than selecting an older package which is available and still matches.

(This is related to #2243 but I decided to keep this separate because this is more of a feature request than a defect, and the root cause is different.)

**Comment by memsharded** [comment]
I think the main difficulty is that the existence or non-existence of binaries should be handled separately from picking up the version. 

For 2 reasons: first, the management of binaries is very decoupled from the construction of the dependency graph, and this would highly complicate the code and its maintainability. 

But second and more important, is that this would destroy performance. Version-ranges are quite slow right now, because a search in remotes is necessary. If it was necessary to check for binaries too, it would quickly become intractable. Please note, that it is not enough to check that another version exists in the remote, but that it has a compatible binary. That would require one search per package-version-user-channel.

The current behavior, using ``--update`` explicitly opt-in into updating the dependency version and disregarding the local one. Isn't this behavior enough for this use case?

Many thanks!

**Comment by mpdelbuono** [comment]
Yeah I expected the performance problem (though I hadn't evaluated that much). What I hadn't realized is that `--update` is a valid opt-in. I had (incorrectly) assumed that `--update` will always look for a newer version, so I had assumed that if 0.1.1 exists on my machine, but is ineligible, then it would reject 0.1.0 on the remote as older. But after testing, it turns out it is willing to fall back to 0.1.0.

I also understand that management of the dependency graph would become very complicated in this case after thinking it through, so you make some good points and I withdraw my request :+1:

**Comment by memsharded** [comment]
Yes, exactly. We thought that for version ranges ``--update`` would mean "update to the latest version that satisfies the range", but not strictly to update a local version. Thanks for your understanding, keeping conan code complexity bounded is important, yes. I think this issue can be closed now, thanks for the feedback!
