### ISSUE TITLE
How to do local development of a library without commiting

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#2247]
I've been trying all afternoon and much of the evening trying to figure this out and I can't. I seem to have found a number of similar questions but none of them have worked or explained in simply enough for me. I have an existing library that my company has been using for a while and I want to migrate it to Conan. I perform the following steps:

```.sh
git clone git@bitbucket.org:redlionstl/c-nviewparser.git
cd c-nviewparser
# Create conanfile.py, update CMakeLists.txt to use Conan
mkdir bin
cd bin
conan install ..
conan build ..
ctest --output-on-failure
cd ..
conan create wsbu/testing
```

But that last command, `conan create`, throws errors because it uses the `source()` method from `conanfile.py` to clone the repository from Git. Well.... I haven't committed to Git, so of course it fails because the necessary CMake changes don't exist in the newly cloned source code.

Here's my `conanfile.py` file.

```.py
import os
from conans import ConanFile, CMake


class CjsonConan(ConanFile):
    name = 'NViewParser'
    version = '0.0.1'
    license = 'Proprietary'
    url = 'https://bitbucket.org/redlionstl/c-nviewparser.git'
    description = 'Parse NView packets'
    settings = 'os', 'compiler', 'build_type', 'arch'
    generators = 'cmake'

    requires = 'googletest/1.8.0@wsbu/testing', 'cJSON/1.7.0@wsbu/testing', 'cryptopp/5.6.5@wsbu/testing'

    def source(self):
        self.run('git clone --depth 1 git@bitbucket.org:redlionstl/c-nviewparser.git -b master')

    def build(self):
        cmake = CMake(self)

        if os.path.exists(os.path.join(self.conanfile_directory, 'CMakeLists.txt')):
            src = self.conanfile_directory
        else:
            src = 'c-nviewparser'
        cmake.configure(source_dir=src)
        cmake.build()
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ['NViewParser']
```

**Comment by mpdelbuono** [comment]
Based on your workflow, I don't think you want `conan create`, I think you want `conan export-pkg`. The difference is that `conan create` actually goes and creates a totally clean location, builds, packages, and exports. While this is the preferred way to create a package (because it's guaranteed clean), if your recipe is going to go clone a repository, then that's not going to work for your testing.

Instead of `conan create wsbu/testing` try

```
conan package
conan export-pkg wsbu/testing
```

This will have the same effect as (the second half of) your `conan create` command, but instead use the locally built and packaged files. Note that both of these commands take parameters to adjust where the package intermediate folder lives, if needed.

**Comment by memsharded** [comment]
You also want to know about the different source approaches:

- Packaging source in another repository, typically uses ``source()`` method
- Packaging source in the same repository/location of the package recipe "conanfile.py", you use ``exports_sources``, to copy the source code (like snapshot), into the recipe itself, so it is self contained. And it does not depend on the state of the repository, because as you said, it might not have been committed. have a look to: http://docs.conan.io/en/latest/packaging/package_repo.html

The approach by @mpdelbuono is valid too, it is using the "local development flow". But if you want to make sure the process is fully repeatable in the cache, and then in other computers too, doing a ``conan create`` is a good way to check it.

Please tell me if this helps, or if you have other questions

**Comment by DavidZemon** [comment]
The `exports_sources` method seems like potentially a good solution. Checking out a tag instead of a branch should resolve the reproducibility issue of `source()` though, so long as good VCS practices are followed.

That being said, I haven't gotten mpdelbuono's method to work. I tried that before, but the `conan package` invocation doesn't work. It doesn't end up packaging anything because I utilize CMake's `install` target in the `build()` method:

```
david@balrog:~/reusable/Documents/Programming/RedLion/NViewParser/bin/Debug$ ls package/
include  lib
david@balrog:~/reusable/Documents/Programming/RedLion/NViewParser/bin/Debug$ conan package ../..
PROJECT: Generating the package
PROJECT: Package folder /home/david/reusable/Documents/Programming/RedLion/NViewParser/bin/Debug/package
PROJECT: Calling package()
PROJECT: WARN: This conanfile has no package step
PROJECT package(): WARN: No files copied!
PROJECT: WARN: This conanfile has no package step
PROJECT package(): WARN: No files copied!
PROJECT: Package 'package' created
david@balrog:~/reusable/Documents/Programming/RedLion/NViewParser/bin/Debug$ conan export-pkg ../.. wsbu/testing
NViewParser/0.0.1@wsbu/testing: A new conanfile.py version was exported
NViewParser/0.0.1@wsbu/testing: Folder: /home/david/.conan/data/NViewParser/0.0.1/wsbu/testing/export
Packaging to f9b95eb25edb64c60850deecfef320eaa0c2a684
NViewParser/0.0.1@wsbu/testing: Generating the package
NViewParser/0.0.1@wsbu/testing: Package folder /home/david/.conan/data/NViewParser/0.0.1/wsbu/testing/package/f9b95eb25edb64c60850deecfef320eaa0c2a684
NViewParser/0.0.1@wsbu/testing: Calling package()
NViewParser/0.0.1@wsbu/testing: WARN: This conanfile has no package step
NViewParser/0.0.1@wsbu/testing package(): WARN: No files copied!
NViewParser/0.0.1@wsbu/testing: Package 'f9b95eb25edb64c60850deecfef320eaa0c2a684' created
david@balrog:~/reusable/Documents/Programming/RedLion/NViewParser/bin/Debug$ ls /home/david/.conan/data/NViewParser/0.0.1/wsbu/testing/package/f9b95eb25edb64c60850deecfef320eaa0c2a684
conaninfo.txt  conanmanifest.txt
david@balrog:~/reusable/Documents/Programming/RedLion/NViewParser/bin/Debug$ 
```

So I'm trying to get `exports_sources`  to work, but I'm running into a compilation problem revolving around `compiler.libcxx` being different depending on whether or not I use `conan install .. && conan build ..` or `conan install .. && cmake .. && make`. When I use `conan build`, conan uses `compiler.libcxx=libstdc++` and throws a linker error, but when I use `cmake .. && make`, conan uses `compiler.libcxx=libstdc++11` and compiles successfully. I am using conan cmake (https://github.com/conan-io/cmake-conan).

I'll report back in a bit if I can figure anything else out.

**Comment by DavidZemon** [comment]
I'm not sure if this is the best way to resolve the problem or not... but I found a StackOverflow question saying that `libstdc++11` is the default for GCC >= 5, and since I'm on Ubuntu 17.10 with GCC 7.2, it didn't make sense that `~/.conan/profiles/default` was set to `libstdc++`. So... I just changed `~/.conan/profiles/default` to use `libstdc++11` and now life is good (using `exports_sources`... still don't know how to get the first method working).

**Comment by memsharded** [comment]
>  it didn't make sense that ~/.conan/profiles/default was set to libstdc++

It makes sense regarding compatibility. Building with gcc>5, you can link with libstdc++. Those binaries, you will be able to use them while using gcc>5 both in old and new distros. But if you use libstdc++11, when trying to use those binaries in old distros, you will get a link error, because even if you upgrade the compiler to gcc>5, it happens that the distro is not able to upgrade libstdc++ without breaking other apps. 

In any case, it is just that, an automatically proposed "default". The recommended approach for production usage is to use your own profiles, put them in the repo, in a dedicated repo or install them via ``conan config install``.

Regarding the other solution, that is right. If you use CMake install feature, which is actually called by the ``build()`` method, then the ``conan package`` command does nothing. But the ``conan build`` command should work and create the package, as long as you provide a ``--package-folder=your_pkg_folder``.

**Comment by DavidZemon** [comment]
As I've let this knowledge simmer more, I realize the `exports_sources` method really is the right solution here, so I've proceeded with that and changing the deafult `libcxx` value and life is good. Thanks for the help.

**Comment by memsharded** [comment]
No problem :)
We are here to help, glad to be useful!
