### ISSUE TITLE
Conanfile folder attributes not available in custom generators.

### ISSUE THREAD

**Issue by adigie** [conan-io/conan#2257]
Hi,  I have an issue with folder attributes. They are not available in custom generators.

Minimal example:
```
import conans

class custom_generator(conans.model.Generator):
    @property
    def filename(self):
        return 'file.txt'

    @property
    def content(self):
        self.conanfile.output.info(self.conanfile.source_folder)
        return ''

class Example(conans.ConanFile):
    name = 'example'
    generators = 'custom_generator'

    def build(self):
        self.output.info(self.source_folder)
```
Output:
```
$ conan install .
PROJECT: Installing D:\temp
Requirements
Packages

PROJECT: ERROR: Generator custom_generator(file:file.txt) failed
'Example' object has no attribute 'source_folder'
ERROR: 'Example' object has no attribute 'source_folder'
```

I tested it on 0.30.3 and 1.0.0b3. Is this a desired behaviour? Earlier I used conanfile_directory but now it is deprecated/removed.

I use it to generate IDE project file containing cmake arguments, e.g. -DCONANFILE_DIRECTORY=... . Then in CMakeLists.txt I can include conanbuildinfo.cmake with:

`include(${CONANFILE_DIRECTORY}/conanbuildinfo.cmake)`

The main reason for that is difference in directory structure when doing local build and building package.

**Comment by memsharded** [comment]
Yes, this is desired behavior. As you point out the reason is that conanfiles are used in different context, and the behavior must be consistent among them. So for example, generators should work also for a conanfile.txt file, and a ``conan install`` command. As you can see, the conanfile does not have source, build or package folders at all.

Even, if you use a *conanfile.py*, it might happen that a pre-built binary package has been installed, so for example the *source* folder or the *build* folder won't exist at all even in the local cache.

So the criteria is that generators generate information exclusively for the installed dependencies, but they should not contain any information about the current package. The package recipes and package build scripts will have that information when necessary in the respective methods.

I am not sure I understand your approach, why don't you use:

```bash
$ conan install . --install-folder=myfolder
```
In order to put the files in your desired build folder, so the standard ``include(${CMAKE_BINARY_DIR}/...)`` will work for you. Thanks for your feedback!

**Comment by adigie** [comment]
Thanks for explanation. I think that I just switch to exports_sources approach to get rid of inconsistency in local/cache directory structure.

**Comment by memsharded** [comment]
Ok, good. Also note that differences between the cache and user local layouts are parameterized in commands. So all locall commands (source, install, build, package, export-pkg) have arguments for specifying the source, build and package folders, so the layout can be different to the one in the cache. Do not hesitate to ask any further question. Thanks!
