### ISSUE TITLE
Recommended way of "enabling tests" in cmake projects?

### ISSUE THREAD

**Issue by philsuess** [conan-io/conan#2263]
Hi,

this is a question for best practice. In version 0.24.0, there was a mention how testing should be enabled using scopes (`conan install --scope build_test=False/True`). But scopes were removed, and now I can't find any hint in the references on what best practice should be to enable testing in projects.

In CMakeLists.txt, I always have:

```
option(BUILD_TESTING "Build unit tests" OFF)
if(BUILD_TESTING)
    enable_testing()
    add_subdirectory(unittests)
endif()
```

How should I pass down `BUILD_TESTING` from conan now (for conan 0.30.3)?

Thanks,

Phil

**Comment by memsharded** [comment]
Hi Phil,

Good question.
It depends on what you want to do. For example, now there is the ``self.develop`` variable, that will be True if  you are ``conan create`` that recipe, or if you are building it ``conan build`` in your own folder. One of its more typical uses is exactly to enable tests.

Otherwise, you want to use environment variables, they are more general than scopes, can be set per-package too, they can be set in profiles, in command line and in the environment itself, and accessed just with ``os.getenv("YOUR_ENV_VAR")``

Cheers!

**Comment by memsharded** [comment]
This question is outdated.

Conan 1.X already gained the conf ``tools.build:skip_test`` that ``CMakeToolchain`` integration and ``CMake`` helper are listening, to avoid building and running tests. For more specific usages, a ``user.xxxx`` conf would be recommended. Closing this as solved.
