### ISSUE TITLE
conan source is not always ran

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2265]
Hi,

Since a few releases I had the impression that sources were not always fetched, maybe since 0.30.

Running `conan create` with different settings on a given package sometimes skip the `source` step.

The thing is I have patches that I conditionally apply (e.g. depending on the architecture for example). Could that be the origin of my issue?

The workaround is to remove the local cache folder each time, which is a bit annoying.

Thanks!

**Comment by memsharded** [comment]
Yes, that is true. The logic is: If the recipe itself has not changed at all, and the sources are there, it is not necessary to re-download them (which is usually slow). That makes fixing ``build()`` problems smoother.

Remember that the sources must be the same irrespective of the settings. That is the meaning of the source step. The sources are common for all builds that will be executed in that machine. Typically the only logic that might make sense is something like: ``if self.settings.os == "Windows": tools.download("....zip")`` because all the builds that will be done in that machine will use exactly the same code. But if possible, even this conditional logic should be avoided.

So, if you have patches that apply depending on the architecture, then it is very important that you apply them in the ``build()`` step, not in the ``source()`` one. The build will have a dedicated and clean folder, and there you can safely patch the code. Also code generation, config.h file generation, should always be done in ``build()``

**Comment by theodelrieu** [comment]
Indeed that makes sense, thanks!
