### ISSUE TITLE
[bug] conan profile update not working for env section

### ISSUE THREAD

**Issue by verbatom** [conan-io/conan#2294]
When trying to update a value for an existing key in a profile's `env` section, the command returns without an error but the key still has its old value. Updating values for existing keys in other sections, e.g. `options`, `scopes` and `settings`, works as expected.

Example:

1. `conan profile show default` -> `env.foo` does not exist
2. `conan profile update env.foo=bar default`
3. `conan profile show default` -> `env.foo` with value `bar` exists
5. `conan profile update env.foo=baz default`
6. `conan profile show default` -> `env.foo` still has old value `bar` instead of expected value `baz`

Conan 1.0.0 (bug persists at least since version 0.28.1)
Python 2.7.6 64-bit
Linux Mint 17.3 64-bit

and

Conan 0.30.3
Python 3.6.4 64-bit
Windows 10 64-bit

**Comment by memsharded** [comment]
Thanks for the report, I have been able to reproduce it.

The issue is that for this update, this code is being used:

https://github.com/conan-io/conan/blob/f4d49d5ec4c2b05ab7fe8f16633c52bd02066e9b/conans/model/env_info.py#L112

This code is shared with the update that is done from dependencies, in which the existing value should not be replaced, because it has higher priority. That makes sense in the propagation stage, but for this command line functionality I agree it can be unexpected. What do yo think @lasote?

**Comment by memsharded** [comment]
In the meantime @verbatom there could be some workarounds: It seems that you might be generating profiles on-the-fly for CI? Is this the case? Then you can consider maybe using the ``conan config install`` feauture, and install profiles instead of generating them? Thanks!

**Comment by verbatom** [comment]
In my case this problem is not a big issue. I wanted to use the `conan profile update` functionality for making the build instructions for the cross-compilation of our software cleaner. The current workaround is to manually edit the corresponding profile file. Nevertheless, I wanted to report this issue.

**Comment by memsharded** [comment]
Ok, good, I have scheduled it for 1.2, many thanks!
