### ISSUE TITLE
Options and settings in conanbuildinfo.cmake

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#2304]
I need to read some option of a consumed package in CMake. I know that `user_info` can be used to pass the information to CMake, but I dont want to modify the package recipe. How can I do that? Could the cmake generator write all options and settings to conanbuildinfo.cmake? Something like `CONAN_OPTION_MYPACKAGE_my_option`?

My use case is an option that is assigned dynamically in package_id(). So the consumer does not know it.

Conan 1.0, Windows
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
This might be possible, yes.
However, this can be related to an ongoing idea of better capturing the install state as part of the install process, so that can be later reused to build intermediate nodes in the graph with full reproducibility. In that sense, this information would likely go first to some other file. Reading from there can be a method in the conanbuildinfo.cmake, that should be doable and a nice to have feature.

**Comment by memsharded** [comment]
``cmake`` generator integration superseded by CMakeToolchain and CMakeDeps
