### ISSUE TITLE
CFLAGS/CPPFLAGS don't seem to be populated.

### ISSUE THREAD

**Issue by dnikishov** [conan-io/conan#233]
ConfigureEnvironment(), when invoked from conanfile.py doesn't seem to set paths to include directories etc of required libraries in CFLAGS/CPPFLAGS environment variables for the current library build.

I've tried running grep through the conan source code and it doesn't seem like DepsCppInfo.cflags (cppflags) are set anywhere.

Is this a bug?

dn@dev-box:~/conan$ pip freeze | grep conan
conan==0.8.6

**Comment by memsharded** [comment]
from https://github.com/conan-io/conan/blob/develop/conans/client/configure_environment.py#L51

```python
include_paths = ":".join(['"%s"' % lib for lib in self._deps_cpp_info.include_paths])
headers_flags = 'C_INCLUDE_PATH=%s CPP_INCLUDE_PATH=%s' % (include_paths, include_paths)

command = "env %s %s %s %s %s" % (libs, ldflags, cflags, cpp_flags, headers_flags)
```
it seems that it is defining include paths in variables C_INCLUDE_PATH, CPP_INCLUDE_PATH. So it doesn't seem a bug, but to be defined that way. Would you expect them in CFLAGS/CPPFLAGS? Usually (such as in other build systems as cmake), such flags are for real flags, and the include paths are managed separately. Could you use those path variables? Thanks for the feedback.

**Comment by dnikishov** [comment]
I'm trying to package exiv2 for Linux as an exercise. This library depends on zlib and uses libtool to build itself. Libtool seems to actually expect raw compiler flags in CFLAGS/CPPFLAGS.

I have put a workaround into my conanfile.py for now and I'm curious if this is expected behavior.

**Comment by memsharded** [comment]
Great, actually, all generators and build helpers as "CMake" and "ConfigureEnvironment", are just that, helpers. You always have in conanfiles ``self.deps_cpp_info``, ``self.settings``, etc. so you can configure your build and customize it as much as you want. Glad you could put a workaround.

If ConfigureEnvironment should be changed and add by default the include paths to CFLAGS/CPPFLAGS, I would say no, but I am not sure. Maybe other users, or @lasote can give more insights into this issue, lets wait for some further feedback?

**Comment by lasote** [comment]
According to this:
https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html
The use of C_INCLUDE_PATH should be enought.
Maybe there is another problem. Could I see the conanfile and take a look?

**Comment by dnikishov** [comment]
Yeah,

https://gist.github.com/dnikishov/515b14139b35f97bcc4c34ee96aa07e3

**Comment by lasote** [comment]
It looks great. How did you realize that the compiler was not finding the zlib paths? Do you use a compilation environment without zlib?
About the --with-zlib option, it's very very common this kind of variables, and it should work with ConfigureEnvironment, but maybe the configure script is doing something tricky.

I can investigate this, but I need to reproduce the compilation error, the problem is that zlib is almost always in every linux so it's always found. If you can help me with that I can investigate the issue. In general, my suggestion is that if it works with --with-zlib option, just use it, the workaround is ok, sometimes it's needed to set this kind of variables and even to replace some line codes in configure to undo some bad tricks.

**Comment by dnikishov** [comment]
I'm using an Ubuntu 14.04 instance for this. In fact, I didn't install zlib1g-dev, so it was pretty obvious, when compilation process failed with "<zlib.h> ... No such file or directory".

After that, I've took a dive into conan source code and found that it has some sort of support for CPPFLAGS: DepsCppInfo.cppflags. A further investigation revealed that it doesn't actually use/update "cflags", "cppflags" attributes.

**Comment by memsharded** [comment]
DepsCppInfo.cppflags will contain something if the upstream packages define so. For example, one package using c++11 in its header could define -std=c++11 in the package_info():

```python
def package_info(self):
    self.cpp_info.cppflags=["-std=c++11"]
```

This is defining to consumers that they have to have this flag, otherwise they would probably fail compiling. Of course, it is up to the consumers to use it or not, but can be provided from upstream for convenience.

I think that zlib is not defining any cflags, cppflags (https://github.com/lasote/conan-zlib/blob/master/conanfile.py), so it makes sense that those fields are actually empty. Is that what you meant?

**Comment by dnikishov** [comment]
Huh, I didn't know that, thanks. I'll continue using --with-zlib.

**Comment by memsharded** [comment]
ConfigureEnvironment has been deprecated in conan 0.20 in favor of new AutotoolsBuildEnvironment and VisualStudioBuildEnvironment and much better handling of environment variables. Check http://conanio.readthedocs.io/en/latest/conanfile_py.html#building-with-autotools. So this issue can be closed, please open a new one for the new helpers if necessary. Thanks!
