### ISSUE TITLE
[question][enhancement] check open source licenses using spdx-lookup

### ISSUE THREAD

**Issue by weatherhead99** [conan-io/conan#2342]
- [X ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Using conan 1.0.2
I think it might be a good idea to incorporate license checking using spkdx-lookup (https://pypi.python.org/pypi/spdx-lookup). E.g. when a user writes a recipe that has a "license" tag, check that the tag used is a valid SPDX identifier. When a user tries to upload to a public repository, validate the license of the stuff being packaged.

This would enforce consistency of the licensing tags in packages, and provide a check that a license conforms to the requirements for uploading to a public repository.

Possible extra idea: warn the user when building a package if the dependencies of the package contain incompatible licenses, e.g. warning the user that it might be illegal to distribute the resulting binaries without source if it links against any GPL dependency, etc etc.

I am happy to try and implement this, but would require guidance about where it is best to be put.

**Comment by memsharded** [comment]
It doesn't look a bad idea, but I have a few questions (also for other contributors and @lasote too):
- It depends on an external service, the SPDX database. What happens if not possible to connect to it?
- Is it something that should be done at upload time, not at export time (to not annoy users innecesarily). What to do if the license is not conformant? Reject it?
- In any case, this is very easily skipped (it is in user side code, it is not going to be implemented server side), so at the end it is a convenience for users, right?
- How to differentiate that this goes to a public or private repository in bintray? Private could use no license, but there is nothing in the API that tells if private or public, just permissions control
- How to evaluate the dependencies? The dependency graph is different under different OS and configurations. For example you could be using in Windows a third party lib that you are not using in LInux. Evaluating all the possible dependency graphs for all configurations is unfeasible.

**Comment by weatherhead99** [comment]
to answer the first point: there is no net activity to check a license, since the entire database (couple of MB) is included in the package install.

I bring this up because it is what e.g. rpmlint does, and it seems a good idea to try and nudge people to use what is becoming the somewhat officially supported id codes for licenses.

The plan would be it would simply be an extra part of the export lint/checking, which would give a warning like "WARN: This package doesn't have a recognised license, it can not be put into a public repository". I can imagine trying to write many other such checks, e.g. absolute file paths in configuration files, does any shared library link to a shared library outside conan, etc etc. I think it would greatly improve packaging standard if people bought into it. It doesn't need to be as heavy handed as rpmlint, but some of that functionality would be very useful. I mention this as what I see to be one of the simplest of such checks.

What would also be needed I think is a  way to silence various warnings (i.e. in the package recipe I can say "yes I know this does't have an OSI license, ignore it". In this case it would be more permissive than rpmlint but work in a way analagous to e.g. silencing compiler warnings with #pragmas .

The suggestion about warning about incompatible licenses, would be an install time check. e.g. at install time, a package goes through its dependency graph, queries all the licenses of dependencies and asks spdx if they are compatible.

**Comment by memsharded** [comment]
> to answer the first point: there is no net activity to check a license, since the entire database (couple of MB) is included in the package install.

Great, perfect then. From a quick overview of the packages I thought it was checking the DB online

>The plan would be it would simply be an extra part of the export lint/checking, which would give a warning like "WARN: This package doesn't have a recognised license, it can not be put into a public repository"

I think this warning cannot be made the default. The truth is that so far conan is used way more privately (in companies with private servers) than for open-source public packages. So putting this warning always might be unwanted for many users, so shouldn't be opt-out, if anything should be opt-in.

> The suggestion about warning about incompatible licenses, would be an install time check. e.g. at install time, a package goes through its dependency graph, queries all the licenses of dependencies and asks spdx if they are compatible.

Yes, I like this idea more. It would be needed a way to differentiate your own custom packages (propietary) vs third parties. Most of the users interested in this utility would have a mix of them.

Regarding linting for package quality there was this issue: https://github.com/conan-io/conan/issues/1115. I did some initial job, but it turned out that it was too complex and not that robust to be worth implementing, because false positives, blocking users, introducing bugs, future maintenance could be more a disadvantage than a benefit. So I put development on-hold. I like very much the idea, but up to now I haven't seen a clear solution. Maybe this should also be another point of extensibility, so linters could be developed and plugged-in by users easily.

**Comment by liberforce** [comment]
I did a proposal in #3498 to expose the license information without entering the linter world for the moment, so that it gives minimal work and the situation can improve quickly.

**Comment by jgsogo** [comment]
This functionality should be implemented using plugins, I think, @danimtb can tell us more about it. You will be able to create a plugin to use in your company and check for the type of licenses that fits your use-case.

Keep this issue open until we have a working draft about the plugins feature and you can implement it following that way. It would be a really valuable plugin.

**Comment by danimtb** [comment]
There is now a SPDX checker hook that has already been merged to the conan-io/hooks repository https://github.com/conan-io/hooks#spdx-checker

It is still very preliminar but it implements the requested functionality and follows the desired approach for implementation.

Please give it a try and report in the hooks issue tracker and we will be more than willing to improve it! 😄 thanks a lot
