### ISSUE TITLE
How to handle different updates of Visual Studio?

### ISSUE THREAD

**Issue by youcefl** [conan-io/conan#236]
How to handle cases where two different builds use different updates of Visual Studio (e.g.
build A uses VS2013 update 1, build B uses VS2013 update 4 and both A and B depend on a package X)?.
Shouldn't the compiler version also include the update number? Can I suffix the compiler version with the update number (e.g. A uses compiler.version=12.1 and B uses compiler.version=12.4)?

**Comment by memsharded** [comment]
That is a good point. Actually we haven't had such problem, as the versions are mostly to guarantee binary compatibility, which is not a problem for updates, afaik. Have you detected some binary incompatibilities between such updates? The same happens for gcc, we only handle minors, not patches, i.e.: gcc 4.8, gcc 4.9, not necessary yet gcc 4.8.3, gcc 4.8.4. Moreover, having those defined as default in the settings, will introduce a larger explosion of packages, mostly unnecessary. We have a mechanism for that, which is the conan_info() method that can be used mostly to narrow settings values, which for that case could look like:

```python
def conan_info(self):
    if str(self.info.settings.compiler.version).startswith("4.8"):
        self.info.settings.compiler.version = "4.8"
```
But this will be another thing to be taken into account by package creators, so that is why we decided to use the main versions for the settings.

Also, it is very difficult (maybe even not possible), to build and test a package against different updates. Conan settings are intended to be that, something that can be defined, and the system will act accordingly. You can specify "Visual Studio", "14", "x86_64", "Release", and the system (not even conan, but the underlying system as CMake) knows how to build that package. Now use "Visual Studio", "12", "x86", "Debug", and as long as you have the version 12 of visual studio installed, it will work, and create a different package. Is it possible to do the same with VS14 updates? I am not sure, but probably not doable.

If there are not actual binay incompatibilities, I wouldn't be concerned myself of such updates, maybe if there are performance improvements, you might be able to regenerate the packages and overwrite them.

In any case, if you want to specifically create different packages for different VS updates of the same versions, i.e. 14.1, 14.2, the definition of settings is open, you can add the versions you want in the **C:/Users/youruser/.conan/settings.yml** file. The problem with this is that most of conan users will not have such version defined. So, if the packages are for you or your colleagues, and they also agree to modify the settings.yml file, that will make it for your use case.

Another possibility would be to define an option into your package, something like:

```python
...
    options = {"vs_update": ["None", "1", "2", "3"]}
    options_values = "vs_update=None"
```

Note that I have introduced the None as an option, as you probably will not need to set it for other OS as linux. The options are included in the package SHA ID, so that would produce and maintain different package binaries for different options. Note, however, that such *vs_update* value, will not be checked by conan, it would be your responsibility to check that it matches your current version (probably querying the win registry)

Please tell me if any of this helps, or if you have further questions, thanks!

**Comment by youcefl** [comment]
I did not run into binary incompatibility, I just thought may be it could become a problem. If for example one version of our product is shipped with binaries built using a certain version of Visual Studio in update 1 and then months or years later if we want to produce a patch then we should do it with the same VS version with same update level and same packages.
The issue is that strictly speaking what we should use is the compiler version, because I can use VS2015 to compile source code written for VS2013, it is just a matter of using the right toolset (v120, or v120_xp).
The compiler version is the one output by cl.exe e.g. 18.00.31101 for VS2013 update 4, 19.00.23506 for VS2015 update 1.
Anyway I don't think MS would introduce binary incompatibility between updates of VS and I think you provided the solution, I like the last possibility you gave and that's what I would use if I were to ensure coexistence of packages built using different updates of the same VS version.
Thank you for helping.

**Comment by memsharded** [comment]
Ok, glad you found the information useful. I think we can close this issue by now, then. Just reopen it or submit a new one if you think extra help or some fix is required. Thanks to you!

**Comment by sigiesec** [comment]
I fear the problem of binary incompatibility exists with the different minor versions of Visual Studio 2017 at least when using libraries built with whole-program optimization (/GL). This binary incompatibility was indicated as "by-design" here by Microsoft: https://developercommunity.visualstudio.com/comments/115395/view.html

**Comment by sigiesec** [comment]
The reported incompatibility is about 2017.2 vs 2017.3

How would I add a specific requirement to the settings.yml?

**Comment by memsharded** [comment]
I see now in the last comment, not in the title, thanks.

If you want to add "update", I think the best would be something like adding to the settings.yml file (you can share this file via ``conan config install``):

```yaml
compiler:
    sun-cc:
        ...
    Visual Studio:
        runtime: [MD, MT, MTd, MDd]
        version: ["8", "9", "10", "11", "12", "14", "15"]
        update: [None, 1, 2, 3, 4]
```
There could be other alternatives:
- Adding 15.1, 15.2, etc to the ``version`` setting directly. This might have the inconvenience that some build helpers like ``CMake`` might not work out of the box.
- You can add the updates specific for each version, like: 
    Visual Studio:
        runtime: [MD, MT, MTd, MDd]
        version:
              12: None
              15:
                  update: [1, 2, 3, 4]
```

Some things:
- Not providing ``None`` as a setting, forces its definition
- Providing ``None`` as a setting, and having that value doesn't change the package binary IDs (retro-compatible with existing packages)

**Comment by sigiesec** [comment]
Thanks for this detailed guide. However, do I understand you right that this is purely a convention I could use in my scope? What if I want to get packages from bincrafters, e.g. Wouldn't there need to be a standard conan way to handle this?

**Comment by lasote** [comment]
@sigiesec The conan center goal is to cover most cases, this issue has not been so far a real concern for the users. The same that happens with Linux and different glibc versions, we have to limit the binaries created in a sane limit, otherwise, it would be unmaintainable.

But, you can use the bincrafters recipes and generate binaries for your own settings structure without any problem, just build your binaries and store them in a local Artifactory.
