### ISSUE TITLE
SIGINT handler returns 0, should return non-zero

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#2360]
Can you return a non-zero exit code when SIGINT is passed in? I don't think it's normal for a program to return 0 when ctrl+c is pressed. I don't know the SIGBREAK signal, but perhaps the same applies there as well.

https://github.com/conan-io/conan/blob/develop/conans/client/command.py#L1216

**Comment by DavidZemon** [comment]
This problem arose because I'm writing a Python script to automate (a complex version of) `conan install .. && conan build ..`. The install command is failing and I exit out with `ctrl+c`, but then the build command tries to run anyway because Python is looking at the exit code and thinks all is good.

**Comment by memsharded** [comment]
Yes, it is true, there are some inconsistencies in the returned codes:

- If a migration or something in the ConanFactory fails (-1) is returned
- Normal operation is returned with True/False, which I guess are converted to 1/0 depending on the OS
- Signals return 0

This has to be improved, though it is true that it might break some users that would be already using existing error codes. However, it might not be a contract breakage because:
- Process return error codes are not documented in the docs
- The "internal" conan API has not been released yet.
- It might be considered a bug. Depending on bugs incorrect output is undefined behavior, and cannot be considered part of the contract of stability.

We need to be careful with this, feedback welcome.
