### ISSUE TITLE
Initialize conan_server's home directory (~/.conan_server) without launching the server itself

### ISSUE THREAD

**Issue by matlo607** [conan-io/conan#2405]
```
*Bottle v0.12.13 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:9300/
Hit Ctrl-C to quit.
```
Running just ```conan``` is enough for the client.
Would it be possible to have something similar for the server ?

**Comment by memsharded** [comment]
Yes, it might be possible, I don't think it will be very complex to add some argument.
But I would like to fully understand your use case, what are you trying to do with such functionality? Thanks!

**Comment by matlo607** [comment]
I am trying to deploy a conan server and its dependencies with ansible on a RedHat server.
I would like the conan server's home directory to be initialized by a default configuration before overwriting the file server.conf

**Comment by matlo607** [comment]
Actually I would prefer to initialize conan_server as it is done for the client --> [conan config](http://docs.conan.io/en/latest/reference/commands/consumer/config.html)
```conan_server config install http://url/to/some/config.zip``` would be very handy too.

**Comment by memsharded** [comment]
Thanks for the feedback.
In the client, it makes more sense because there are many things to be configured: remotes, conan.conf, profiles, pylint files, etc. For the server, it is just one server.conf file, so adding a specific command to do what a ``wget`` + ``unzip`` can do seems a bit overkill. Maybe I am missing something, please tell me. Thanks!

**Comment by matlo607** [comment]
Actually you are right, it is overkill. I think it is a useless feature.
