### ISSUE TITLE
Package content should be sorted (or sortable) when uploading

### ISSUE THREAD

**Issue by mdegel** [conan-io/conan#2414]
Tested combinations:
Conan Version: 1.0.3, 1.0.4
OS: Ubuntu, CentOS

When uploading packages to a remote, conan will package the corresponding directory content in a .tgz file.
https://github.com/conan-io/conan/blob/ed927b7b949102a9a9a01d7ab8e105adc37add59/conans/client/remote_manager.py#L108

 This content is resolved by an `os.walk()`, see:
https://github.com/conan-io/conan/blob/ed927b7b949102a9a9a01d7ab8e105adc37add59/conans/client/remote_manager.py#L95
and
https://github.com/conan-io/conan/blob/5eb46242b4f139bf4e23b176c7ef70967e41c8aa/conans/model/manifest.py#L18

`os.walk()` however resolves files in arbitrary order (maybe depending on the underlying filesystem?).
(see https://stackoverflow.com/questions/18282370/os-walk-iterates-in-what-order for reference)

Due to the arbitrary order, the generated tgz file can differ in order, thus the checksum for this tgz can differ as well. This means, the checksum for the same conan package may differ depending on what OS/Filesystem (or other side effects?) someone uses.

For a better view on this problem, assume the following situation:

1. Package A is built by a Buildserver using several different Slaves (Windows, Ubuntu, CentOS, ...)
2. After running the tests, the Buildserver is supposed to promote the packages from channel `testing` to `stable`
3. The Buildserver installs the packages (thus extracting them)
4. The Buildserver uses `conan copy` to create the promoted package
5. The Buildserver uploads the packages back to the remote (thus compressing them again)
6. Now some or all of those packages in `stable` will have different checksums than their counterparts in `testing`
7. This contradicts the usage of artifactory (No compression of the same artifacts, due to the different checksums), as well as leaving the user to check by hand if these packages are _**really**_ equal.

In order to solve this issue I would propose to either:
- Always sort the contents before compressing it by using `sorted(os.walk(...))`
- Make sorting optional by providing either an option `--sort=[True|False]` or an environment variable `CONAN_SORTED_TARFILE=[True|False]`

**Comment by memsharded** [comment]
You are right, though in many cases it is not a huge issue, because the order is kept the same for the same OS and configuration (no strong guarantees, I know, but in practice many times it is).

The solution ``sorted(os.walk(...))`` could be a nice one, but has the penalty of destroying the generator performance, some conan packages might contain many thousands of files. If implemented, probably shouldn't be optional, but builtin.

Regarding the use case of promotion for Artifactory, I think it would be much better to directly use Artifactory features to promote it directly in Artifactory, orders of magnitudes more efficient and secure. There might be some current restriction, but the way to go is indeed this, not via ``conan copy``.

We'll have a look and discuss about how to approach this.

**Comment by mdegel** [comment]
Thanks for the quick response.

As for promotion, Artifactory was the first place I started looking, however artifact promotion directly on the server does not seem to be possible currently (at least for the GUI part), which was the reason I checked out the basic conan options to promote packages. This was where I stumbled upon the checksum mismatches due to our differences in used architectures for building code ;)

**Comment by memsharded** [comment]
> As for promotion, Artifactory was the first place I started looking, however artifact promotion directly on the server does not seem to be possible currently (at least for the GUI part), which was the reason I checked out the basic conan options to promote packages. This was where I stumbled upon the checksum mismatches due to our differences in used architectures for building code ;).

Yes, this might be the restriction I was talking about. But lets try to improve that in the first place, as that was the original cause, and the promotion mechanism is something that we definitely want in Artifactory.

I have opened https://github.com/conan-io/conan/issues/2415, please follow up and comment there. Thanks!

**Comment by memsharded** [comment]
This has been stale for a while.
Many things have changed since then, for example with revisions, a given .tgz will only be zipped once, never re-zipped, so the order shouldn't be an issue. Furthermore, the checksums of the .tgz are no longer used to define ``--update`` flows, and there have been no other reports regarding this.

I am closing this as no longer an issue, but please create a new ticket if necessary for further discussion.
