### ISSUE TITLE
imports/copy question

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2418]
Suppose I have
```
x86
  vc15
    bin
      opencv_core310.dll 
      ...
```
directory structure in my package. Is it possible to import `opencv_core310.dll` and friends to project's `bin` folder forgetting all the directory structure? I tried
```python
def imports(self):
   self.copy("*.dll", "", "bin")
```
but it creates `x86/vc15/bin/opencv_core310.dll` while I would like to get `bin/opencv_core310.dll`
Probably  import/copy should have `keep_path` parameter like package/copy does?

**Comment by danimtb** [comment]
Hi @db4!

Thank you for reporting.
Yes you are right, there is no `keep_path` parameter in for the copy object inside the `imports()` method and this could be introduced without further issue in a following release.

However, I would like to note one thing here. There is no need to maintain that folder structure when you are packagin the generated binaries in the `package()` method because the settings of the package are already stored in the package ID.

Indeed, as a convention it is normally used like this:

```
def package(self):
        self.copy("*.h", dst="include", src="hello")
        self.copy("*hello.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)
```

Have you found any issue packagin the binaries as above? Please try that an tell me what you think.
Thanks! 😃

**Comment by db4** [comment]
@danimtb , for OpenCV I would like to preserve directory structure to be able to use its `OpenCVConfig.cmake`. Otherwise cmake find_package() will not be possible. But you are right - I can copy `*.dll`/`*.so` to bin folder and keep paths for `*.h`/`*.lib`/`*.cmake`. Then no changes is needed, at least for my case.

BTW, does anyone know which OpenCV package considered "mainstream" for conan? What it the best way to contribute - create my own hundredth fork of some conan-opencv repo or choose an arbitrary one and make a PR?

**Comment by danimtb** [comment]
Yes @db4 I understand. We will add keep_path parameter to fit your use case.

Note sure what you are asking about regarding OpenCV, I would say the official repo is[ this one](https://github.com/opencv/opencv). Best way would be to fork and create a PR there with the minimum files for conan package support. Or you can create your standalone repo with the conan files...

**Comment by danimtb** [comment]
I think I understand better now. I think you mean what OpenCV package would be the best to use with Conan.

Currently there are no good quality packages for OpenCV. I guess there might be outdated and not fully-featured packages in the old conan-transit bit I'd suggest not to use them as they would probably be depreprecated.

We are more than willing to help anyone develop a good package for OpenCV and include it in conan-center repository. It would be awesome for the Conan users!

**Comment by db4** [comment]
> We are more than willing to help anyone develop a good package for OpenCV and include it in conan-center repository. It would be awesome for the Conan users!

I'm quite new to conan.io, so some things are not very obvious to me. How do you know that something is  good enough for conan-center? How other users expected to find new packages (not yet included into conan repos), test them and contribute to their development? There is at least one "stable" conan packages repository (bincrafters). How do you coordinate your efforts with them? These questions are probably very common, but I have not found answers in your FAQ or other conan.io docs.

**Comment by memsharded** [comment]
No problem, in fact conan-center is just starting to be populated, and we are all learning in the process.
If you haven't, you might read this guide: http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html

The bincrafters are doing a great job, but I don't think all the packages they have can be considered stable. They will be doing inclusions requests to conan-center, and we will collaborate to review and help improving them, so conan-center will be the main reference for stable packages.

Some community has concentrated in the CppLang slack team (https://cpplang.now.sh/) there is "conan" channel with lots of conan users, and also a "bincrafters" channel. They are both very very active and you can find in them people willing to help, discuss, learn, and collaborate.

For packages as important as OpenCV I'd expect to be managed by more than just 1 individual. Ideally, and due to its importance, it would be great that the OpenCV maintainers would collaborate and help with the task. I had myself some recipes for OpenCV that could be a good start, I might try to prioritize it, and I think I know some other users that would be interested in helping.

**Comment by db4** [comment]
@memsharded, thanks for the clarification. As for OpenCV, [I've  done my own attempt](https://github.com/db4/conan-opencv), I believe resulting conanfile.py is more flexible than others - it auto-detects OpenCV link options ans is sutable for building at least versions 3.1-3.4 editing a single line. As it forked from your/xmar repo, I would like to know you opinion on that.

**Comment by memsharded** [comment]
Thanks @db4 this is very interesting. We have started a package for OpenCV in conan-community (packages mantained by us): https://github.com/conan-community. We will keep yours as a reference too, there are some neat ideas there. Other things could be improved I think. Lets collaborate in that repo if you feel so: https://github.com/conan-community/conan-opencv
