### ISSUE TITLE
os_target should have the same structure than os

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2428]
Hi,

I'm using Conan 1.0.4.
I encountered a problem while specifying settings for the `android-toolchain` recipe.

The settings I need are: 
* `os/arch_build`, since this will be used as a build_requirement
* `compiler`, to know which of gcc/clang to use (and the libcxx)
* `os/arch_target`, since the toolchain's compiler will produce an output for a different target than the build/host.

However, I need to access the `os_target.api_level` in my recipe, but there's no such setting defined by default.

Indeed, the `os_build/os_target` settings are defined as a list, not as an object.

I believe those settings should have the same structure than `os`. What do you think about it?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I think you are right, in general, we detected that the current approach is not enough. It is a clear example. 
Related to https://github.com/conan-io/conan/issues/2301

We have some ideas of how to solve it, but it looks like instead of declaring different settings for target/build/host, we should consider the whole settings definition as a "context" to apply to target/build/host. 
Unfortunately, this feature will require hard work.

**Comment by memsharded** [comment]
os_target dissapears in the new cross-build model with host-build profiles
