### ISSUE TITLE
Partial rebuild of packages

### ISSUE THREAD

**Issue by Lyberta** [conan-io/conan#2462]
When invoking `conan create . User/Channel` Conan always does full rebuild of the package which can be very slow. Is there a way to only rebuild files that were changed?

**Comment by lasote** [comment]
The way to achieve that is to use the conan local methods described in the [package development flow](http://docs.conan.io/en/latest/creating_packages/package_local_dev_flow.html).
Instead of doing create you go step by step specifing the destination folders, source, install, build, package... So the build can be done in the same folder, so the build system can take benefit of already built files.

**Comment by Lyberta** [comment]
So here's what I use right now to do a test build of my library:

```
mkdir -p Build
cd Build
conan install ..
cmake ..
make
```

Does this mean I need to change last 2 lines to:
```
conan build ..
conan export-pkg .. User/Channel
```
?

**Comment by lasote** [comment]
I would recommend using the `conan build`, yes, because if you are using the CMake() build helper it will inject some variables to translate the settings into flags. But for your initial question, I understood that you were always using `conan create` to test your package if you are building it with cmake, you are already building only the changed files, right?

About the export-pkg, it depends on what you want to do, I usually don't use it, when I'm sure that my package is developed ok I call `conan create`. Al the flow and the rationale is described in the docs of package development flow.

**Comment by Lyberta** [comment]
My test application is separate so I always need to have the latest build in local cache. I want conan to instruct cmake to only rebuild changed files and then upload package to local cache.

**Comment by lasote** [comment]
Then I think yes, you have to perform the `conan build` and `conan export-pkg` locally.

**Comment by Lyberta** [comment]
I'm getting:
    ERROR: Package already exists. Please use --force, -f to overwrite it

This doesn't happen during `conan create`. Should I just `--force` it in my case?

**Comment by lasote** [comment]
Yes ``--force`` it.

**Comment by Lyberta** [comment]
Thanks, seems to work.
