### ISSUE TITLE
Custom arguments for conan build

### ISSUE THREAD

**Issue by Lyberta** [conan-io/conan#2470]
I use `conan build` to build my package but I want to build only specific CMake target. Is there a way to forward custom arguments with `conan build`?

**Comment by memsharded** [comment]
There is no direct interface for controlling that, because ``conan build`` is intended to be similar to the ``conan create`` flow, and thus reproducible, and using custom arguments should only be done via conan parameterization (settings, options, env-vars).

One common approach is to use ``not self.in_local_cache`` or some custom env-var to run the ``cmake.configure()`` only in ``build()``, but not the ``cmake.build()``, so then you can directly invoke cmake with any custom target or configuration you want.

**Comment by Lyberta** [comment]
I know now you are in backward compatibility land but maybe it would be possible to add `configure()` command and tutorial would put just `cmake.configure()` there so that it would be easier to develop packages.

**Comment by memsharded** [comment]
Thanks for your feedback. Do you mean a ``conan configure`` command? And then, internally the ``cmake.build()`` being skipped because it knows it is in "configure" mode only? (what do you mean by "tutorial" would put configure()?)

It sounds a bit too specific for this use case and will not work in many scenarios, for example if the user is using other build-system, or calling ``self.run("cmake ...`` directly. If we can't draw a clear and general enough use case, I see complicated that this command will be possible.

**Comment by Lyberta** [comment]
Here's what the usual `conanfile.py` looks like:

```
	def build(self):
		cmake = CMake(self)
		cmake.configure(source_dir = self.source_folder)
		cmake.build()
```

I'm thinking to change it to something like this:
```
	def configure(self):
		cmake = CMake(self)
		cmake.configure(source_dir = self.source_folder)

	def build(self):
		cmake = CMake(self)
		cmake.build()
```

This means adding `conan configure` command that would call `configure()`. `conan create` will also be calling `configure` between `install` and `build`.

An upside is that this will actually be backwards compatible with packages that do everything inside `build()`.

My use case is that I'm now fully migrating all my code to Conan and `conan build` passes important info to CMake so now I can't call CMake directly. If there would be a `configure()` step, I would just call `conan configure` and then during development I would call CMake or Make directly instead of `conan build`.

**Comment by memsharded** [comment]
Quick note: the ``configure()`` method is already used for another purpose: http://docs.conan.io/en/latest/reference/conanfile/methods.html#configure-config-options

I think the following:

```python
def build(self):
    cmake = CMake(self)
    cmake.configure(source_dir = self.source_folder)
    if self.in_local_cache:
         cmake.build()
```
will do what you want, without needing extra methods, commands or configuration.

**Comment by Lyberta** [comment]
But that would remove the ability to do `conan build` to do partial rebuild and then `conan export-pkg` to export that build to local cache. Or is there another workaround?

**Comment by lasote** [comment]
Nope. You are right. Now you cannot do it without doing a trick using env vars or something like this. It could be a nice thing, but I also would like to have more feedback from the community before introducing a new method, that introduces more complexity.

**Comment by Lyberta** [comment]
Should we rename the issue or make another one?

**Comment by memsharded** [comment]
Good, lets continue conversation in the other issue, and I think this one can be closed now. Thanks!
