### ISSUE TITLE
Add a metadata in conanfile.py to check the compatibility between the recipe and conan's version

### ISSUE THREAD

**Issue by matlo607** [conan-io/conan#2475]
Lastly, with the quick release cycle of conan, a lot of conan's users installed a version of conan and a couple of weeks later, they had an outdated version with compatibility issues.
They downloaded a recipe from the conan server that was written for a newer version of conan and got error messages from python when they tried to build it.
There was no message from conan itself to tell the user that he is trying to build a recipe published for a newer version of conan.

I had 2 ideas to solve this issue.
- conan could export in the local cache (~/.conan/data/...) a metadata containing its version at the same time it exports a recipe. If the same user on the same machine upgrades conan and then try to build the recipe, it should be at least warned of possible issues. Idem for the upload of the recipe on the conan server when another user download this recipe with an older or newer version of conan, it should be warned. If the build succeeded, the metadata  could be updated to the newer conan version to not display the warning message anymore.
- embed in conanfile.py an attribute informing about supported conan's versions (a range, a specific version) for the recipe. If the user try to build it with another version of conan, it should be warned.

What do you think about it ?
Have others users passed you this issue when you released versions with breaking changes in the past ?

**Comment by memsharded** [comment]
Conan 1.0 was released just one month ago. Before that, it was beta, and there was not commitment to stability, in fact, adding and managing and being backwards compatible with previous versions is a bad idea for a beta, because it slows you down a lot, and makes impossible to iterate and improve fast.

Now, with conan 1.0, there is a commitment of stability. Recipes and public interfaces shouldn't break. If they break, that will be considered a bug and reverted. If at some point it is necessary to introduce something that would be potentially breaking to previous (>=1.0) versions, of course we will introduce the conan version metadata to recipes and packages so they can coexist safely.

At the moment, this is not necessary, but if it is for some new feature or change, we will definitely use one of either of your suggested approaches. Actually not only to warn or error, but to really provide compatibility, and do a different processing of recipes from different versions if necessary.

I am closing this issue, because it is not something like a real feature, but an implementation detail we might need to do for some future feature, and it will be done associated to that breaking change.

Thanks very much for your feedback!

**Comment by matlo607** [comment]
Thanks for your detailed answer.
It will be reassuring for some persons in my company.
