### ISSUE TITLE
Provide a separate step for 2 step build systems such as CMake and AutoTools

### ISSUE THREAD

**Issue by Lyberta** [conan-io/conan#2499]
As discussed in #2470, it would be very helpful to have a separate step that would only call `configure()` function of `CMake` and `AutoToolsBuildEnvironment` because Conan passes useful information to them so calling them directly without Conan will probably configure them incorrectly and always calling `conan build` is very impractical.

**Comment by memsharded** [comment]
To summarize alternatives.

OP proposition:

```python
def configbuild(self):  # configure() can't be used, already in use
    cmake = CMake(self)
    cmake.configure(source_dir = self.source_folder)

def build(self):
    cmake = CMake(self)
    cmake.build()
```
Commands:
```
$ conan install .
$ conan configbuild .
$ conan build .
```

The current solution would be something in the line:

```python
def build(self):
    cmake = CMake(self)
    cmake.configure(source_dir = self.source_folder)
    if not os.getenv("CONAN_CONFIG"):
         cmake.build()
```
Commands:
```
$ conan install .
$ CONAN_CONFIG=1 conan build .
$ conan build .
```

This requires further feedback from the community:

- Approach 1 will require adding an extra step to the local flow, and also adding extra method (and complexity) to the package recipe. I would like to avoid it.
- Approach 2 might be slightlier inconvenient in Windows, where setting env-vars is more inconvenient. I agree it could be improved.

There could be other alternatives. Actually calling ``conan build`` always is definitely impractical, but you shouldn't be doing it always. Just the first time, then open your IDE, or use directly ``make``. The build files will be there.

Feedback welcome!

**Comment by mpdelbuono** [comment]
Dare I offer a counter-argument? :)

I've actually been working on the side on a feature for connecting conan to a feature of CMake called "cmake server". By using the cmake server, I can extract all kinds of information out of the build process automatically. This greatly simplifies the package_info method by allowing me to automatically identify the various directories and binaries that get created.

However, part of this implies that splitting up the steps is actually problematic. We "want" to maintain the connection to cmake server between all these steps to get the full set of information:

1. Connect to cmake server
2. Run configure
3. Run generate
4. Run build
5. Extract information

I was doing that connection via a 'with' block, so that I know that cmake terminates if an exception occurs, but this would be impossible if split across two methods unless I disconnect and reconnect. If we disconnect in between steps 3 and 4, then steps 2 and 3 need to be run again.  Admittedly, it is likely to be very fast because much of the information will be cached at that point, but it is still "weird" and will likely make the definition of the build() and configbuild() steps as proposed a bit ugly.

All that being said, I recognize that making design decisions against a feature that doesn't exist isn't the best idea, but I wanted to throw that out there just to put it on the table. Of course, another alternative is simply that CMake Server users just don't use configbuild(). (CMake users already tend not to use the package() method, anyway, so this would not be unheard of.)

**Comment by Lyberta** [comment]
Yeah, nobody forces to use configbuild(). The backwards compatibility is still there.

**Comment by lasote** [comment]
I would try to avoid a new local method unless there is a big demand for this feature. The same for the recipe new method, but it worries me less than the new local method. If we decide to introduce this feature I would prefer a new parameter to `conan build` to only run the configbuild.

**Comment by Lyberta** [comment]
I'm fine with parameter to `conan build`.

**Comment by memsharded** [comment]
I think that with a parameter to ``conan build``, it could be used *inside* the ``cmake.build()`` and ``autotools.build()`` methods to early return. In that way, no extra method is required, and no changes to existing package recipes, all could work as-is, with the new argument.

**Comment by Lyberta** [comment]
What if the user uses some other obscure build system? Should we add argument to recipe file like I wanted in the initial issue?

**Comment by memsharded** [comment]
So yes, you might be right :) Sorry for going back and forth, but sometimes we need to consider different alternatives, about other usage patterns, etc. So to summarize the best could be:

- Having an extra argument to ``$ conan build --only-configure`` (just an example)
- This would translate to a ``conanfile self.only_configure`` variable.
- This variable can be used by default by build helpers as ``CMake``, etc.
- This variable can be explicitly used by other ``build()`` methods with custom builds.

I think it is not difficult to implement, I am temptatively approving it. Thanks again for your feedback and help!

**Comment by Lyberta** [comment]
Actually, the most flexible solution is to have a separate command. Here's the example from my intended workflow. First, I would do `conan install` and `conan configbuild`. This will install dependencies and configure CMake in my case. Then I would call CMake or Make directly during development. After I'm satisfied, I would like to call `conan build` that will only build and not configure CMake and then `conan export-pkg` to export package into the local cache. So, recap:

* `conan install`
* `conan configbuild` that will **only** call `CMake.configure()`
* Calling CMake or Make directly
* `conan build` that will **only** call `CMake.build()`
* `conan export-pkg`

**Comment by memsharded** [comment]
If the issue is ``configure`` being called twice, then I would think of having an argument with different values ``--configure_build={configure, build}?``, and that can be use to inhibit ``configure`` execution the second run if necessary, and only run the build, or to just run the configure code the first execution. But I still think that this use case doesn't have the entity to justify a separate command or a separate method, IMHO.

**Comment by Lyberta** [comment]
Something like `--configure_build` is fine by me. Maybe just a better name.

**Comment by Lyberta** [comment]
How will the value will be transferred to the recipe though?

**Comment by memsharded** [comment]
Lets say:

```bash
$ conan build
# calls both cmake.configure() and cmake.build()
# self.configure_build = None

$ conan build --configure-build=configure
# calls cmake.configure() only
# self.configure_build = "configure"

$ conan build --configure-build=build
# calls cmake.build()
# self.configure_build = "build"
```

Just the idea. The naming is terrible, to find something better. And waiting for @lasote feedback

**Comment by lasote** [comment]
I think I would prefer `--configure-only` and `--build-only` and available `self.configure_only` and `self.build_only` in the recipes.

**Comment by Lyberta** [comment]
The command line parameters are fine but for the recipe I would to suggest something like `self.should_configure` and `self.should_build` so the recipe would become something like this:

```
def build(self):
    cmake = CMake(self)
    if (self.should_configure)
        cmake.configure(source_dir = self.source_folder)
    if (self.should_build)
         cmake.build()
```

**Comment by memsharded** [comment]
I still think that we should look for the same name or value both in the command line and in the recipe. That helps users to understand the purpose, it is more intuitive. In any case, it shouldn't be necessary for the ``CMake`` helper, as the check will be done inside ``cmake.configure()`` and ``cmake.build()`` methods.

**Comment by ytimenkov** [comment]
The discussion above assumes that `configure` is part of "Package development commands" however I would rather have it as a consumer command (together with `install`).

Now conan can't help with consistency between install step and building of consuming code. Say if I do install with profile targeting MingGW but my following CMake configure step finds Visual Studio.

I'd like to have better integration between conan install and configure commands for consuming packages, which is exactly where I see use of `configure`, especially if it's generator-specific and can forward/adapt generator arguments. Would be extremely useful when combined with build-time requirements and shipping toolchains as packages.

**Comment by ytimenkov** [comment]
Let's take a look at "Getting started" documentation:
 * Step 1: "Installing dependencies":
`conan install . -s os="Linux" -s compiler="gcc"`

* Step 2: "Building the timer example":
`cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release`

On step 2 how can I be ensure that CMake will use configuration which is consistent with step 1? E.g. that it has found right compiler, etc? On linux I can run one command via `scl enable devtoolset-X` and forget for the other.

That's why I'm thinking about something like install+buildconfigure for consuming packages, where conan generator may not only create a script for generator, but actually invoke it.

**Comment by memsharded** [comment]
But that is exactly what the proposal is about. It will be possible:

```
$ conan install .. -s os=...
$ conan build .. --configure_only
$ cmake --build . --config Release #or cmake, or open VS
```

Btw, regarding:
> E.g. that it has found right compiler, etc?

The generated ``conanbuildinfo.cmake`` already has some compiler checks to make sure it matches the installed dependencies.

**Comment by ytimenkov** [comment]
Just a question: will `conan build --configure_only` work with text files? (If this is needed)

**Comment by memsharded** [comment]
No, only with ``conanfile.py``. If there is no logic to call cmake, it is impossible to do. A conanfile.txt is basically a declaration of dependencies, but it is impossible to control the build of the user, which might be in any location.

**Comment by Aalmann** [comment]
@memsharded 
Because of your last comment it would be better and more clear for users to have a new method and a new command instead of flags at build-command.
The only thing with that is backward compatibility to older conan versions. But having an additional flag in the recipe (like `self.should_build`) will end up with the same problem.

**Comment by memsharded** [comment]
I have proposed in https://github.com/conan-io/conan/pull/2600 the following syntax:

```bash
$ conan build . --configure, -c  #only configure
$ conan build . --build, -b #only build
$ conan build . --install, -i #only install
```
They can be combined:
```bash
$ conan build . -c -b
```

The variables in the conanfile are:
```python
self.should_configure
self.should_build
self.should_install
```
Defaulted to true, unless some of the above arguments is passed.

Feedback welcome

**Comment by Aalmann** [comment]
Is there a good way to determine the current/running conan version within the recipe? Otherwise it could be complicated to use these variables with older conan versions. (Hard to upgrade all users at the same time to latest and greatest)

**Comment by danimtb** [comment]
@Aalmann Yes, you can check the conan version inside a recipe. Take `mingw_installer` as an examle: https://github.com/conan-community/conan-mingw-installer/blob/master/conanfile.py

**Comment by memsharded** [comment]
You can check the version, but I'd suggest to be more version agnostic. Use:

```python
def build(self):
     if getattr(self, "should_build", True):
          #do the build
```

That should be backwards compatible, no need to check the version.

**Comment by Aalmann** [comment]
@danimtb and @memsharded 
Thanks for the hints. `getattr()` is not my favorite but quite shorter than checking the version.

**Comment by ytimenkov** [comment]
Although this is good for testing conanfile it's not very convenient to use when consuming packages because it requires not just to write conanfile.py but also to write it with support for separate steps.
I see that build system helpers do some work, but it doesn't scale well.

**Comment by memsharded** [comment]
Hi @ytimenkov 

Not sure what you mean.

> I see that build system helpers do some work

It is not that they do some work. It is that you can use this feature, without having to modify any existing recipe using the build helpers (which seems to be the large majority). I think it is a very interesting feature.

> it requires not just to write conanfile.py but also to write it with support for separate steps

Yes, it is a feature for the ``build()`` method of conanfile.py. Whatever the approach, if you have a custom build and not using the build helper you will have to do something anyway.

If you could please outline what you have in mind as a solution, that could help. Thanks!

**Comment by ytimenkov** [comment]
Let me try :)
First, we use Waf, that's why I have to do little extra work, but thanks to awesome docs it was easy to integrate them.

Ultimately I want to use Conan for deploying everything, including compiler toolchain. So once I've ran `conan install` I need to run generator in modified environment. It could be `CC` or even `PATH` if I choose to ship waf (or think CMake and ninja) with Conan. If generator ran after separately, there is a risk that it picks up wrong dependencies or tools. I want to have solution as foolproof as possible.

At the moment I'm not convinced that we should use build functionality of Conan (not for first party libraries) because when I develop code I need fast incremental builds, predictable code location for switching branches and integration with IDE. Build command should be simple and I want to build diferent targets (in contrast to thinking of package). So I'd like to limit Conan use for pulling dependencies and pushing built binaries.

Probably I could (or have to or will) use virtualenv generator for this purpose.
I'm still investigating potential workflows and open for suggestions.

**Comment by memsharded** [comment]
> So once I've ran conan install I need to run generator in modified environment. 

You mean to activate an environment script? Because conan generators that create files for the dependencies (conanbuildinfo.cmake) run at install time.

If you are using your own build system, you might be very interested in creating your own generator for it. It is not very difficult, and can be managed like a conan package (I am not opposed to add a WAF generator as built-in into conan either). That might help automating lots of things and could automate the pass of the environment, including CC, etc to WAF, so user end is very foolproof. Please have a look to: http://docs.conan.io/en/latest/howtos/custom_generators.html#dyn-generators

> At the moment I'm not convinced that we should use build functionality of Conan (not for first party libraries) because when I develop code I need fast incremental builds, predictable code location for switching branches and integration with IDE. Build command should be simple and I want to build diferent targets (in contrast to thinking of package). So I'd like to limit Conan use for pulling dependencies and pushing built binaries.

Yes, you should be pretty good with the local flow install + build (either conan build, or just directly your build system) + <optional conan package> + conan export-pkg. With this you develop locally, so you have your incremental build, IDE, etc. 

This is not incompatible with trying to have reproducible package creation with ``conan create`` too. Kind of pre CI checks, that guarantees that everything reproduces well in the conan cache, and the packages are not from just local changes of the developer in their user folder. This is the final step recommended in http://docs.conan.io/en/latest/creating_packages/package_dev_flow.html. But for developing your own code, of course the "local flow" is the recommended approach.

Cheers!

**Comment by ytimenkov** [comment]
You're right that in generator (especially custom) it's possible capture in generated file not only what comes from packages but also part of environment. Although I think toolchain package should set variables like `CC`.
I was thinking back and forth what should drive what: generator drives Conan (as the CMake script calling `conan install`, producing settings accordingly to selected compiler and toolchain) or vice versa, Conan should drive generator.

With your input now I think the latter approach has good potential. Just need to keep in mind that generator should do as little detection as possible and pull most from conanfile.
For example, debug/release settings could be injected via appropriate profile and transformed into compiler flags. Probably via some metapackage declared in dev dependency in profile.

So for developer the workflow could be as simple as running conan install with required profile and then running configure with minimal set of arguments.

Sorry for cumbersome explanation and thanks!

**Comment by memsharded** [comment]
> With your input now I think the latter approach has good potential. Just need to keep in mind that generator should do as little detection as possible and pull most from conanfile.
For example, debug/release settings could be injected via appropriate profile and transformed into compiler flags. Probably via some metapackage declared in dev dependency in profile.

Yes, that is my preferred approach, I prefer to be declarative to the process, and tell what I am using, that letting the build tools to guess what is my setup. That also allows much nicer decoupling. The build system knows nothing about the package manager, it just receives some input information (include-dirs, etc) how to build. The package manager "install" knows nothing about the build system of the dependencies, it just fetches packages, put them somewhere, and generate the information to the build system. 
Thanks to you for the feedback!
