### ISSUE TITLE
Need better support for build tools

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#2505]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan v1.0.4

First, it's possible I'm missing something, so please let me know if that's the case.

For the first time today I'm trying to create Conan packages for two executables (libtool and automake) which are needed to build the libuv library. I'm using the docs on [Cross Building](http://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-settings) to help me out.

If I understand it correctly, this process means I need two different libtool recipes. The first is required for building libuv and uses `settings = 'os_build', 'arch_build'`, and the second is required for building libtool for the end-goal (a custom embedded Linux OS running on ARM) and it will use `settings = 'os', 'arch', 'build_type', 'compiler'`. I guess this happens because `os_build` and `arch_build` are not treated any differently than any other setting.

What I was really hoping to find was some way to write syntax like this:

```py
class libuvRecipe(ConanFile):
    host_build_requires = 'libtool/2.4.6@foo/bar', 'automake/1.2.3@foo/bar'
    build_requires = 'googletest/1.8.0@foo/bar'
    requires = 'libA/4.5.6@foo/bar'
```

And in this case, I would expect Conan to know that the `os_build` in my profile should be used to select the `os` setting for libtool and automake.

**Comment by mpdelbuono** [comment]
If I understand correctly, I think this is the same kind of problem I reported in #2497 which is, itself, being discussed in #2301. 

For now, I'm working around the issue by handling "host build" settings via options, and defaulting those options in a manner that makes sense for the ultimate consumers. (For example, the host build build_type setting defaults to "Release", because most people will want the release version of those tools. Only the tool developers themselves would ever want the debug version.)

Does that help?

**Comment by lasote** [comment]
Yes, I think it is the same issue. Please, close this and comment in 2301 if you agree.
