### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#2526]
`conan` shouldn't create a `$HOME/.conan` directory and use `$XDG_CONFIG_HOME/conan` instead, following the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html). This can [nicely be applied to Windows too](https://stackoverflow.com/questions/43853548/xdg-basedir-directories-for-windows).

This avoids cluttering `$HOME`, is friendly to other operating systems, and allows backup and synchronization systems to just work if they look at the standard locations.

Using conan 1.0.4 on Ubuntu 14.04.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Sorry my ignorance, it is the first time I heard about the XDG specification. And I am afraid that the majority of conan users might be the same as me. The fact that you can define custom env-vars in Windows to follow that specification, doesn't mean that most conan users in Windows will follow it.

In any case, it is just a default, you can easily change that and put whenever you want with CONAN_USER_HOME env var.

I have checked my current HOME folder and I have folders for CLion, VirtualBox, git, eclipse, vim, VS code, just to name a few... So I wouldn't say that conan is not aligned with the current leaders practices, and I strongly think that conan should do the same as them. 

Thanks very much for your suggestion anyway!

**Comment by liberforce** [comment]
```
$ ls -1 ~/.config
compiz-1
dconf
enchant
eog
evince
evolution
gedit
gnome-session
gnote
goa-1.0
gtg
gtk-2.0
gtk-3.0
htop
ibus
Kitware
libaccounts-glib
libreoffice
menus
nautilus
pdfmod
pulse
qi
QtProject.conf
software-center
totem
tracker
Trolltech.conf
unity
update-notifier
upstart
user-dirs.dirs
user-dirs.locale
VirtualBox
yelp
```
Vim does not follow it for historical reasons, as it predates the standard. This is a [freedesktop](https://en.wikipedia.org/wiki/Freedesktop.org) standard, not something made out of the blue.
You'll notice that Virtualbox follows the XDG spec however, as well as other cross-platform tools, like gtk, qt, libreoffice, cmake, and pip (try running a pip install --user conan).

I totally understand if you don't want to implement this, but being able to find projects that don't follow the standard misses the point of **why** that standard was created and is useful.

**Comment by grisumbras** [comment]
Actually, Git does follow XDG dir spec. It used to _not_ follow it, because git itself is older then the spec. Because of that, it first tries to load its global configuration from `$XDG_CONFIG_HOME/git/config` (falling back to `$HOME/.config/git/config`, then from `~/.gitconfig`. Something like that could be implemented for Conan.

Note, that in order to actually conform to the spec, Conan will have to store only _static_ configuration in `$XDG_CONFIG_HOME/conan/`. All files that normally get changed by the program itself should go into `$XDG_DATA_HOME/conan` or other similar directories. For example:

* `$XDG_CONFIG_HOME/conan/cacert.pem`
* `$XDG_CONFIG_HOME/conan/conan.conf`
* `$XDG_CONFIG_HOME/conan/settings.yml`
* `$XDG_CONFIG_HOME/conan/profiles/`

* `$XDG_DATA_HOME/conan/registry.txt`
* `$XDG_DATA_HOME/conan/version.txt`
* `$XDG_DATA_HOME/conan/data/`

* `$XDG_RUNTIME_DIR/conan/registry.lock`

**Comment by memsharded** [comment]
Hi @grisumbras 

Thanks very much for the feedback. Yes, I think this might be doable without breaking, and it makes sense.

Just a quick question, the profiles, the settings.yml, the conan.conf are for example installed via ``conan config install``. Still should be considered config and not data, right?

Thanks!

**Comment by grisumbras** [comment]
Yes, similar to `git config --global`.

**Comment by ruzito** [comment]
I think that it would be also apreciated if at least the default directory was `~/.config/conan` instead of `~/.conan` on linux.

And for backwards compatibility you just check if `~/.config/conan` exists if it does, use it, if not check if  `~/.conan` exists if it does, use it, if not create `~/.config/conan`

With this aproach it would be easy to just move the directory where one wants it. (Unless actually following the XDG isn't so easy that this quick dirty fix is just a hassle)

**Comment by memsharded** [comment]
I am reviewing this issue again in preparation for 2.0, and I am struggling to see how to make this work nicely for a very common Conan usage pattern, that is defining different homes for different projects. This happens in several situations:
- In CI servers, every job has to use a different cache. At the moment, it is easy for them to define just CONAN_USER_HOME, and everything related to that job is stored there. Following this spec, CI jobs will have to set several env-vars for each job, most likely all of them referring to a single folder and then adding the "conf", "data", "home" subfolder
- In Developers machines, this is also frequently used. Switching home from one project to another is relatively simple, changing just one env-var, but if they had to change several env-vars every time, I can see how many of them would be annoyed. 

How would this be handled?  I don't think the XDG spec has this use case in mind at all. So to summarize:

- This would be very inconvenient, even annoying for many Conan users that use multiple Conan homes in their machines.
- This spec is still not really mainstream in OSs like Windows (still seeing most popular dev apps, like Docker or VSCode use the same approach as Conan).
- The complexity of implementing this spec in Conan shouldn't be underestimated. For example, the home automatic migration that happens at every Conan version upgrade, relies on a ``version.txt``, and applies patches and updates relative to it. Having to distribute the updates to several different folders will be more complicated and fragile. 
- Any attempt to reuse folders between instances, for example, trying to use the same config folder for different data folders would result in the migrations being confused or failing. Also, the data consistency might be easily broken, for example the package binaries in the cache should match the ``settings.yml`` in the conf, and if because trying to reuse folder it doesn't match, it is extremely likely that this will result in many undefined behaviors, more tickets for us and painful debugging support sessions and investigations trying to understand what is happening.

I will submit this for a final decision to the whole team.

**Comment by jwillikers** [comment]
@memsharded I don't think the XDG Base Directory Specification takes multiple installations of the same application into account, which is what is effectively being done in CI / developer machines as you mention. I think that it probably makes the most sense to allow overriding all of the directories together with `CONAN_USER_HOME`, but on Linux when this variable is not set, then maybe follow the XDG Base Directory specification. I don't have more than one Conan installation at a time, generally, nor do I ever really modify my XDG paths from the defaults, so I probably wouldn't run into any of the issues of things ending up out of sync, but that certainly could lead to some more complicated scenarios.

**Comment by grisumbras** [comment]
It would require setting 2 env vars: XDG_CONFIG_HOME and XDG_DATA_HOME. But it wouldn't be of any use for devs having multiple conan homes, as it would break almost all other software. It would probably be less problematic for CI jobs, but still not very useful. A possible solution is to approach it like git does: presence of CONAN_USER_HOME overrides looking at XDG variables. E.g.

If `CONAN_USER_HOME` is present, than everything is put into `CONAN_USER_HOME/.conan`.

Otherwise, if `XDG_CONFIG_HOME` is present, than configuration files are put into `XDG_CONFIG_HOME/conan`. If it's not present, than configuration files are put into `$HOME/.config/conan`

Also, if `XDG_DATA_HOME` is present, than data files are put into `XDG_DATA_HOME/conan`. If it's not present, than data files are put into `$HOME/.local/share/conan`.

FInally, if `XDG_RUNTIME_DIR` is present, than runtime files are put into `XDG_RUNTIME_DIR/conan`. If it's not present, than runtime files are put into an appropriate directory, e.g.  `/tmp`.

I'm not sure if there's any reason to also try loading anything from `XDG_CONFIG_DIRS` and `XDG_DATA_DIRS`. In theory, OS vendors could start putting Conan profiles and configs into e.g. `/etc/conan`, but with the exception of employer-provided deb/rpm packages I seriously doubt that would happen.

**Comment by memsharded** [comment]
> If CONAN_USER_HOME is present, than everything is put into CONAN_USER_HOME/.conan.

> Otherwise, if XDG_CONFIG_HOME is present, than configuration files are put into XDG_CONFIG_HOME/conan. If it's not present, than configuration files are put into $HOME/.config/conan

This is exactly one of the issues, that this is a matter of opinion. Once the XDG spec would be supported this way, I am sure that there will be users reporting that Conan is not putting things in the defined XDG folder even if the XDG env-var is correctly defined, and if we tell them that it is because another env-var CONAN_XX is defined, they will respond that the XDG is a standard and as such should have higher priority and it should be respected, very annoyed that Conan is not respecting the XDG spec. I have been there many times...

We have discussed this, the whole team, and besides the fact that support for it in different OSs vary, it is not a standard and still very popular tools like VSCode will put things in a ``.vscode`` in the user home, the inconvenience for many Conan users using different Conan homes for different tasks, builds or projects, and that it will be difficult to document (e.g., in all places in our docs that we reference the `<userhome>/.conan` will no longer be valid), explain and maintain, there is a major blocker for this: The distribution of the Conan home in different folders breaks the necessary home consistence for tasks like installing config or applying migrations. With the XDG specification it is very easy to violate many Conan home working hypothesis, like the packages stored are consistent with the settings.yml, or that the DB format belongs to a given Conan version. The effort and pain of many support and debugging hours that this will cause (and I can guarantee that it will eventually happen) is not worth it. 

Thanks very much all for all the feedback and discussion.

**Comment by grisumbras** [comment]
While I ultimately understand that the approach I described increases maintenance cost, I disagree with the notion that it is somehow bad. I've never heard anyone complaining about git doing it that way. The fact that various software (even new) continues to ignore XDG dir spec is lamentable. But again, maintenance burden is a valid argument, and since keeping several conan homes have become a popular approach, the value of supporting XDG dir spec has reduced. It's probably only relevant now for people like me, who wish to keep their home directories clean and to back up their configs with git.

**Comment by memsharded** [comment]
>  It's probably only relevant now for people like me, who wish to keep their home directories clean and to back up their configs with git.

The thing is that Conan proposes a different flow direction for this. The config should definitely be backed-up in git, but not from a live installation. Config is put in a clean git repo, and then installed into the current Conan home with ``conan config install``.
