### ISSUE TITLE
"Skipping version checking of not detected compiler" when using Clang

### ISSUE THREAD

**Issue by arnemertz** [conan-io/conan#253]
Trying to build a project with Conan, CMake and Clang, I noticed that CMake gave me the suspicious output shown above. Investigating I found the following lines in conanbuildinfo.cmake:

    function(check_compiler_version)
        # ...
      elseif(CONAN_COMPILER STREQUAL "gcc" OR CONAN_COMPILER MATCHES "Clang")
        # ...
      else()
        message("Skipping version checking of not detected compiler...")
      endif()
    endfunction()

The problem seems to be that CONAN_COMPILER is lowercase "clang" as far as I can see, "Clang" is not supported.

**Comment by memsharded** [comment]
Hi Arne,

This is only a check, trying to make sure that the correct compiler and version are being used in the build, that matches the ones used at install time. Indeed it is a bug, I will correct it asap, but it shouldn't be blocking. Is it blocking your build or totally failing? Or can it proceed and build? Thanks!

**Comment by memsharded** [comment]
I have fixed it, and checked with clang, and now it correctly detects version mismatches between the declared clang version and the used one. Fixed in: https://github.com/conan-io/conan/commit/3055837ebf2e587a3650cdb0e0951bfb961f1a95

Fortunately, it seemed that this bug is not blocking, so you might keep working with clang with care, this fix will be released in next 0.10 release. I thing this issue can be closed, but tell me if you want this bug fix available to you right now, because I can create a custom cmake generator for you with the fix included, and you can use it without having to wait till the next release.

Thanks very much for reporting this bug!

**Comment by arnemertz** [comment]
Hi James, sorry for the late reply. It was no blocker, just a minor hick up I saw when getting to the bottom of something else.

**Comment by memsharded** [comment]
Ok, thanks for telling. It should have been released in latest conan 0.9.2, I think.
