### ISSUE TITLE
Support multiple versions on requires

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#2601]
Hi!

Running Conan 1.1.1 I would like to use the same package twice, but using totally different versions:

```python
class Foobar(ConanFile):
    name = "foobar"
    version = "0.1.0"
    settings = "os", "compiler", "build_type", "arch"
    requires = "bar/1.0.0@user/stable", "bar/0.1.0@user/stable"
    
    ...
```

`ERROR: conanfile.py: Error while initializing requirements. Duplicated requirement bar/1.0.0@user/stable != bar/0.1.0@user/stable`

Why I need such behavior?
Well, some few projects (libusb), when the major version was updated, the project was complete reformulated. Even headers, libraries and all others files have different names, as a new project.

In my case, I have a project using both versions -- Okay, I should update the project. However, I'm able to link when I solve my dependencies by distro package manager.

Could be possible to add a flag to run both versions together. WDYT?

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
It is almost impossible.
All the conan dependency graph computation is mostly based by the package name. The version and the rest of information is overriden.

Even if the graph could be computed for your example, and both "bar" package versions are in the graph, it could be a total mess of include directories, library directories, library names... etc. To which targets/libraries you will link?

In order to be able to do such a thing, it is expected that the name of the package would be different, like Catch/Catch2, otherwise it is a guaranteed path to hell :) :)

**Comment by uilianries** [comment]
I see. So would prefer to split the original package, as you commented.

In my case, I'm using libusb 1.0.21 and libusb 0.1.12. The same project here uses both two versions :man_facepalming:

Thanks for you quick answer, regards!

**Comment by memsharded** [comment]
Yes, I'd recommend to package "libusb0", and "libusb", for example, 200%.
So then in your consumer code, you explicitly link e.g. with ``CONAN_PKG::libusb0`` target, when you want to.

**Comment by SzBosch** [comment]
Is the answer still valid with conan 2?
Referring to https://docs.conan.io/2.0/reference/conanfile/methods/requirements.html#visible I understood it should be possible by setting the **trait "visible=False"**.
But this is unfortunately not working. I tried with Conan 2.0.16 and 2.10.

I would like to have 2 different packages, lets say pkgA and pkgB as direct dependencies (normal require, no tool_require) with each having a dependency to the same 3rd package, lets say pkgC, but with different versions in the graph, like:

```
myprj:
  pkgA/1.0.0 (visible=False)
    pkgC/2.0.0
  pkgB/1.0.0 (visible=False)
    pkgC/3.0.0
```
Error message on "conan graph info" command:

```
...
Graph error
    Version conflict: pkgB/1.0.0->pkgC/3.0.0, myprj ->pkgC/2.0.0.
ERROR: Version conflict: pkgB/1.0.0->pkgC/3.0.0, myprj ->pkgC/2.0.0.
```

What is strange to me, this direct dependency in the error message: myprj ->pkgC/2.0.0
Any explanation?

Note: This problem is only on normal required. If I change to "tool_require" it works, but I need the normal requires.

**Comment by memsharded** [comment]
Hi @SzBosch 

Sorry it took a while to respond this, it is typically better to create new tickets than commenting in closed ones, as that can go unnoticed.

This should work, for example this simple test works:
```python
    def test_visible_false_no_conflict(self):
        c = TestClient(light=True)
        c.save({"math/conanfile.py": GenConanfile("math"),
                "engine/conanfile.py": GenConanfile("engine", "1.0").with_requirement("math/1.0", visible=False),
                "ai/conanfile.py": GenConanfile("ai", "1.0").with_requirement("math/2.0", visible=False),
                "game/conanfile.py": GenConanfile("game", "1.0").with_requires("engine/1.0",
                                                                               "ai/1.0"),
                })
        c.run("create math --version=1.0")
        c.run("create math --version=2.0")
        c.run("create engine")
        c.run("create ai")
        c.run("create game")
```
This doesn't raise a conflict. If you are still seen this issue, it would be necessary to have further details to reproduce, please open a new ticket for that. Thanks for the feedback.
