### ISSUE TITLE
GPL question

### ISSUE THREAD

**Issue by dawidcha** [conan-io/conan#2609]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I'm looking to recommend use of Conan in a large organization, and I'm doing due diligence on licensing

Some concern has been raised over the way pylint is used. Could a version be cut which doesn't import pylint directly (i.e. invokes it out of process), or which doesn't depend on pylint at all?

**Comment by memsharded** [comment]
Hi!

This is very interesting question. What would be the problem of installing pylint as a dependency of conan? Please note:
- Nothing in the conan code or conan dependencies "contaminate" your source code, your binary packages.
- It is just a tool, used locally to manage things. The use case would be exactly the same as using git, which is also GPL, wouldn't it? Are you using git?

We can't remove the linter and release different versions with and without pylint, that would be too much overload, but I think it is something relatively easy to do an maintain yourself, if this is critical for you, I could help. But first, please let me know about the above, willing to learn about your use case.

**Comment by dawidcha** [comment]
I found a recent relevant discussion here, which lays out some of the uncertainties.

https://github.com/PyCQA/meta/issues/24

**Comment by memsharded** [comment]
Quick observation, just in case: pylint does not work on applications created with pyinstaller (i.e. the installers .exe, .deb, etc in the downloads page), so pylint has been removed from those already. So for conan installed via installers, pylint will not be installed nor used at all.

Having a deeper look to your link and reading a bit about the issue, for the pip installed conan.

**Comment by memsharded** [comment]
Just in case there could be something not completely clear, we have just improved it in #2611: This PR loads pylint in a subprocess, and will gently fail if it is not installed. It then becomes an external tool which is not linked at all to our application, so the license shouldn't be an issue at all.

Thanks very much for raising this concern!

**Comment by tony** [comment]
(I was in the PyCQA thread linked in this issue)

If GPL code is used via a subprocess, my interpretation is that's okay.

So Conan is fine as long as it executes it that way. But if Conan were to need to access pylint programatically, through Python, it wouldn't be so clear. A project like this, since it is in python, may want to access an internal part that isn't normally available via CLI. That's when it becomes a problem. It opens up a platform of plausible ways someone can make a credible facial allegation a derivative work was created.

So keep an eye on that.

I still disagree with incorporating GPL code in python. I don't think it's a sustainable thing, because if it's found to be a limitation later on, it's very very stressful to dig a project out of it. The complications it brings aren't worth the assurances.

I feel GPL makes more sense for a large conglomerated effort that's insulated, for a compiled programming language. Like KDE, Linux kernel. In this cases, GPL let's you see the source code of the built application. It also ensures that contributions are kept within and prevents forking (although observation can tell people happily contribute back anyway to projects without any derivative terms).

**Comment by memsharded** [comment]
Hi @tony 
Thanks for the feedback. Yes, conan executes pylint as a subprocess. No import at all to pylint, so no access to internals either. It is also not redistributed in the pre-compiled versions of conan (created with pyinstaller), which has this feature disabled. Furthermore, running pylint as subprocess is quite slow, so we have plans to remove it, and implement it as an optional plugin, outside of the conan codebase.
