### ISSUE TITLE
conan_multi generator does not seem to work with find_package

### ISSUE THREAD

**Issue by jamezmoran** [conan-io/conan#2617]
Hi,

I've tried to switch a project to using the conan_multi generator, but it was not able to detect libraries like boost via the find_package method, whereas using the normal generator it was. 

Steps to reproduce:
1. Make a basic conanfile with a library like Boost or Googletest as a requirement and with both cmake and cmake_multi generators.
2. Make a basic CMakeLists that includes  the standard boilerplate for cmake_multi and a find_package() declaration for the library.
3. conan install for debug and release, then run the cmake configure command. This should fail to find the library.
4. Change the boilerplate in the CMakeLists to the boilerplate for the normal cmake generator and repeat step 3. This should succeed in finding the library.

Thanks.

**Comment by jamezmoran** [comment]
Now that I think about it, it doesn't really make sense for find_package to work since conan has no way of knowing in advance what configuration the user is going to be building. I think it might be worth mentioning it as a caveat on the cmake_multi docs since I don't think it's immediately obvious.

**Comment by memsharded** [comment]
Yes, exactly, this is a known limitation of cmake. ``find_package()`` cannot be parameterized (cmake generator expressions) to find multiple configurations of the same package, like debug/release x86/x86_64, etc., so it is not possible to use ``cmake_multi`` at the same time as ``find_package()``.

Alternatives are:
- Not using ``find_package()``, and use the conan provided targets and variables, which is the recommended way to consume packages for most cases
- Do not use the ``cmake_multi`` generator. The only inconvenience is that it requires to manage the different configurations, but depending on the tools, it can be easily automated, like: http://docs.conan.io/en/latest/howtos/vs2017_cmake.html. I much prefer using ``cmake`` than ``cmake_multi``. Ongoing efforts, like addons for IDEs will further improve the usability.

As this issue is not really solvable by us, I think this issue can be closed if you don't have further questions. Thanks!

**Comment by lasote** [comment]
> I think it might be worth mentioning it as a caveat on the cmake_multi docs.

Sure, I'll open an issue in the docs repository.

**Comment by jamezmoran** [comment]
Thanks! Closing
