### ISSUE TITLE
Support for gcc 6.1 and clang 3.8

### ISSUE THREAD

**Issue by darthdeus** [conan-io/conan#262]
I've tried building the sample project in the Getting started section, but at first I ran into connan not finding any compiler on my system (arch linux with both gcc 6.1 and clang 3.8 installed)

```
$ conan

It seems to be the first time you run conan
Auto detecting your dev setup to initialize conan.conf
ERROR: Unable to find a working compiler
Default conan.conf settings
        os=Linux
        arch=x86_64
        build_type=Release
*** You can change them in ~/.conan/conan.conf ***
*** Or override with -s compiler='other' -s ...s***
```

I tried fixing this by specifying the settings manually as the error message suggests, but it wouldn't let me use a newer version of both GCC and Clang than the ones conan knows about.

```
$ conan install .. -s compiler=gcc -s compiler.libcxx=libstdc++11 -s compiler.version=6.1 --build                                                              ERROR: '6.1' is not a valid 'settings.compiler.version' value.
Possible values are ['4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5.1', '5.2', '5.3']
```

and

```
$ conan install .. -s compiler=clang -s compiler.libcxx=libc++ -s compiler.version=3.8 --build                                                                 ERROR: '3.8' is not a valid 'settings.compiler.version' value.
Possible values are ['3.3', '3.4', '3.5', '3.6', '3.7']
```

Is there a way to work around this? It seems reasonable to use any compiler/version I want, no?

**Comment by memsharded** [comment]
Yes, there is a way to do it. The default settings are defined in **~/.conan/settings.yml**. They are defined this way, so they are common ground for most use cases, but this file can be user defined. Just add your settings to this file. Custom settings are also allowed, a few notes:
- Settings are something that are project-wide, as the architecture or the compiler. All packages/dependencies should have the same settings to build, otherwise binary (ABI) incompatibility, linking errors or runtime errors (e.g. sometimes using debug artifacts in release mode) can occur.
- For package-specific things, you can use **options**, check the documentation how to define and use them
- You can define in your **~/.conan/conan.conf** the default settings you want to use in your projects, so you dont have to fully specify them at ``conan install`` with ``-s`` parameters. They can be overriden for a specific invocation using the parameters.
- When modifying *settings.yml*, if you want to share your packages with  other developers, they have to modify their own *settings.yml* too.

In any case, it is true that our default settings have not been updated to use the latest gcc and clang versions, I will add them. Thanks very much for pointing this out!

**Comment by qmenoret** [comment]
I tried to use custom settings too for both GCC 6.1 and clang 3.8, but conan just won't let me use a compiler version which is not defined in the list you updated in your commit.
I just can't work on my project with conan right now, until a new version is released, while all was working fine weeks ago.
We should be able to run conan with any compiler, even if it is not listed in this file. I run archlinux, I will always have the latest version of GCC / clang installed... I cannot wait for a new version of conan everytime I update my system.

Is there any way to bypass the compiler version check ?

**Comment by memsharded** [comment]
Yes! Have you read the posts above? add them to your ~/.conan/settings.yml file, and you will be fine. This issue was closed while merging the PR that added them to the default settings.yml, but they have not been released yest. Please add them to the settings.yml file.

**Comment by memsharded** [comment]
Not sure if I understood correctly. So you had it working for gcc 6.1 in the past? Did you modified the settings.yml to do it? If that file was reverted, then it would be a bug. Is it possible that you had it working with a previous version of gcc?

**Comment by qmenoret** [comment]
Oops, i thought the setting.yml was the project wide settings, i just misread, my bad.
And no, all was working before I upgraded GCC (5.8 to 6.1).

Thank's for the quick reply, I'm trying to build everything right now !

**Comment by memsharded** [comment]
Great, thanks for telling, I thought you were talking about a conan upgrade, not a gcc upgrade.
Let us know any other issues or questions, thanks to you for reporting!

**Comment by cpbotha** [comment]
I ran into this same issue with conan 0.9.4 installed from PyPI.

For what I'm doing now I can just downgrade to g++ 5.3, but I'm curious when this fix will land in an official conan release?

**Comment by memsharded** [comment]
Hi @cpbotha , 
No, you dont need to downgrade to g++5.3!
Just add 6.1 to your home/.conan/settings.yml.

Next release, 0.10, will probably be next week anyway, 6.1 is already in the default settings.yml in develop branch, so it will be in 0.10.
