### ISSUE TITLE
cmake_multi does not work with 'conan create'

### ISSUE THREAD

**Issue by jamezmoran** [conan-io/conan#2623]
I received this error when running conan create:

    CMake Error at ../conanbuildinfo_multi.cmake:462 (message):
    No conanbuildinfo_debug.cmake, please install the Debug conf first

This appears to be because cmake_multi requires that both conanbuildinfo_release.cmake and conanbuildinfo_debug.cmake needs to exist in advance, but only release is generated in this case:

    : Generator cmake_multi created conanbuildinfo_release.cmake
    : Generator cmake_multi created conanbuildinfo_multi.cmake

As far as I know there is no way to get around this, and this means conan create cannot be used with cmake_multi (and hence cmake_multi is not a viable generator for general purpose development). Is there a way to get around this? In the case of conan create we already know in advance which configuration to build, so I think this constraint of having both debug and release being installed can be relaxed.

Thanks!

**Comment by memsharded** [comment]
Yes, you are totaly right, our bad. There should be something in the docs that clarifies that, together with some cmake code to manage that. Will open an issue for it right now.

The idea is that cmake_multi is a convenience for users while developing, but just as a consumers. For creating packages, the ``cmake`` generator is still necessary. They can coexist without problems. We'll add more details to the docs. Thanks very much for raising this issue.

**Comment by jamezmoran** [comment]
@memsharded I think the problem is that because cmake_multi cannot be used for conan create, it also cannot be a convenient solution for development either as that would require changing potentially many CMakeLists files due to the differences in usage for the library linkage. I feel like right now, it doesn't really suit either purpose.

Right now I'm in the middle of implementing conan for my company, and I'm positive that the question of configuration management in VS is going to come up more than once. You mentioned in a previous thread that there is work going on that improves the usability of conan in IDEs such as Visual Studio through the use of addons and such, and I think this would go a long way in answering those concerns. Therefore, in these circumstances it might be worth thinking about whether cmake_multi qualifies as deprecated functionality, as it doesn't appear to fit the objectives for which it's intended and it's not something I can reasonably recommend for any production or development system.

Thanks!
James

**Comment by memsharded** [comment]
The truth is @jamezmoran is that I agree with you. I am not a big fan of ``cmake_multi`` and I never use it myself. This was mostly driven by the community and some users really willing to make those changes to the CMakeLists.txt if they could avoid having to go to the terminal to type ``conan install`` to switch debug<->release configurations.

So this is something that we highly respect. The good thing about generators is that they are absolutely in the edge, so they don't affect the rest of conan. So I don't think it should be marked as deprecated, because it is still providing some functionality to some users that they depend on, and there is no better alternative right now. So we certainly have to wait at the moment, lets see how it goes when the addons mature.

I am at least going to document this properly and put a more evident warning. Many thanks for your feedback!
