### ISSUE TITLE
[question] How conan handles deep option dependencies?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2628]
Suppose there is `LibA` package that requires `LibB`. `LibA` and `LibB` have option `shared`. There are also binary packages
(1) `LibA(shared=False)` built with `LibB(shared=True)`
(2) `LibA(shared=True)` built with `LibB(shared=True)`
(3) `LibB(shared=False)`
(4) `LibB(shared=True)`
Now I need a fully static app using `LibA`, so a do
`conan install . -o LibA:shared=False -o LibB:shared=False`
conan will use packages (1) and (3) but that won't link because (1) requires (4), not (3).

**Comment by memsharded** [comment]
Good question.

Options, depending on how are defined, are also propagated from downstream (consumer) to upstream (dependencies), overriding when necessary and conflicting (raising errors) if they differ.

In your case, the downstream is requiring both LibA and LibB to be shared=False. The resulting dependency graph will contain both LibA and LibB shared=False, without conflicts, because the user defined it downstream (command line has priority over conanfiles).

The remaining question is if LibA will error because of not having a compatible binary for the current graph. This depends on the ``package_id()`` result. The default one uses a combination of settings + options for the package + requires with semver (1.X). The values used for computing the package ID hash are in the ``conaninfo.txt`` file. If everything is correctly defined, the error would be that there is no binary for LibA, because it needs to build against LibB(shared=False).

**Comment by memsharded** [comment]
Btw, the way to define this binary compatibility is specifying it in the package_id(), you probably want something like:

```python
def package_id(self):
    # All the options of my dependencies affect my binary ID
    self.info.options = self.info.full_options
    # OR
    # Changing the dependent binary reference, changes my binary ID
    # anything in pkgName-version-user-channel-binaryID of the dependency
    self.info.requires.full_package_mode()
```

**Comment by db4** [comment]
> This depends on the package_id() result. The default one uses a combination of settings + options for the package + requires with semver (1.X)

And that' the problem. Let't take as an example OpenSSL from conan-center. In depends on zlib. Here are their defaults:

OpenSSL:shared=False
zlib:shared=False

Both packages don't define custom package_id(). Now I would like to build an app with OpenSSL:shared=True and zlib:shared=True. How to do that? I Have
```python
class TestConan(ConanFile):
    requires = "OpenSSL/1.0.2n@conan/stable"
```
and do `conan install . -o OpenSSL:shared=True -o zlib:shared=True` but zlib is linked statically. It's better than link error that would happen in case of default `shared=True` in the required package but still not what I expected to see.

**Comment by memsharded** [comment]
Yes, you are right. The reason is that historically, packages for OSS libraries had been prepared for having the same mode (all static or all shared). In fact, many package recipes where hardcoding their dependencies ``shared`` option in their ``configure()`` method, so this was never an issue.

We should have a look to the default ``package_id()``, check if some improvement or maybe add some helper like ``manage_shared_static_id()`` to be added in the recipes... Lets look into this deeper.

**Comment by db4** [comment]
I see. All shared/static approach looks like an acceptable trade-off. So if I package LibA that requires LibB, LibC, what should I do now to implement it? Something like
```python
    def requirements(self):
        self.requires("LibB")
        self.options["LibB"].shared = self.options.shared
        self.requires("LibC")
        self.options["LibC"].shared = self.options.shared
```
?

**Comment by danimtb** [comment]
I think that if requirements are not conditional, best way would be:

```
requires = "LibB", "LibC"

def config_options:
    self.options["LibB"].shared = self.options.shared
    self.options["LibC"].shared = self.options.shared
```

Have a look at the docs (not your exact case but it could help): http://docs.conan.io/en/latest/mastering/conditional.html

**Comment by yangcha** [comment]
> Yes, you are right. The reason is that historically, packages for OSS libraries had been prepared for having the same mode (all static or all shared). In fact, many package recipes where hardcoding their dependencies `shared` option in their `configure()` method, so this was never an issue.
> 
> We should have a look to the default `package_id()`, check if some improvement or maybe add some helper like `manage_shared_static_id()` to be added in the recipes... Lets look into this deeper.

To stretch this idea, I think conan's default behavior should be to propagate the options from downstreams(consumer) to upstreams(packages). Otherwise there will be a combinatorial explosion in number of binaries. It is kind of like the inheritance in OOP.

**Comment by memsharded** [comment]
All the shared/static options propagation has changed a lot in Conan 2.0, closing this as outdated.
