### ISSUE TITLE
'conan upload' should provide an option to skip 'corrupted packages'

### ISSUE THREAD

**Issue by jamezmoran** [conan-io/conan#2647]
Right now, conan upload will fail on the spot if it detects a package is "corrupted". I have a feeling this happens when a build fails for a particular configuration and the package reference is left dangling, so while a build folder exists for it, a package directory does not:

    Uploading Grpc/1.9.0@3rdparty/stable
    Uploading conanmanifest.txt
    [==================================================] 58B/58B
    Uploading conanfile.py
    [==================================================] 3.0KB/3.0KB
    Uploaded conan recipe 'Grpc/1.9.0@3rdparty/stable' to 'conanbuild': url
    Uploading package 1/3: 0beb1537b05ec660bc0ef1b22d1b39d63b3ed1f8
    ERROR: Cannot upload corrupted package 
    'Grpc/1.9.0@3rdparty/stable:0beb1537b05ec660bc0ef1b22d1b39d63b3ed1f8'

You'll notice that it is package #1 out of 3, although there is only one package folder in my conan directory for this package. I don't think there's a way to get around this without manually deleting the individual references, although it would be acceptable for me to skip the upload of this particular reference and continue on.

**Comment by memsharded** [comment]
I am not sure the way to go would be to implement this feature to skip, but I think it is necessary to address the root cause. In theory the build folder is irrelvant, only the package folders would be used, so I have no idea why it tries to upload 3 binaries. Can you please try the output of ``conan search <pkg-ref>``? Also, can you double check that in your conan cache, folder ``Grpc/1.9.0/3rdparty/stable/package`` there is only one subfolder with the ``0beb1537b05ec660bc0ef1b22d1b39d63b3ed1f8`` hash as name? Many thanks

**Comment by memsharded** [comment]
Closing this as stale without response to request for details.

In any case, with conan 2.0, package integrity check is only done if ``upload --check``, otherwise it will  not be mandatory, so this wouldn't be a problem anymore.
