### ISSUE TITLE
Gitlab CI runner: Incorrect default config path

### ISSUE THREAD

**Issue by n-bes** [conan-io/conan#2673]
I use conan with [gitlab ci runner](https://docs.gitlab.com/runner/#features) which runs under root/system user. 

First conan call shows this output:

```
Auto detecting your dev setup to initialize the default profile (C:\Windows\system32\config\systemprofile.conan\profiles\default)

Found Visual Studio 15
Default settings
	os=Windows
	os_build=Windows
	arch=x86_64
	arch_build=x86_64
	compiler=Visual Studio
	compiler.version=15
	build_type=Release

You can change them in C:\Windows\system32\config\systemprofile\.conan\profiles\default
```

Folder ``` C:\Windows\system32\config\systemprofile\.conan\ ``` doesn't exists, real path to config is ``` C:\Windows\SysWOW64\config\systemprofile\.conan\profiles\default``` 

Also, I had a similar problem, MSbuild can't find the library (I can find lib inside ```SysWOW64```). 

```text
LINK : fatal error LNK1181: cannot open input file 'C:/Windows/system32/config/systemprofile/.conan/data/Poco/1.9.0/pocoproject/stable/package/09378ed7f51185386e9f04b212b79fe2d12d005c/lib\PocoUtilmd.lib' 
```

Conan version: ```1.1.1```
Host: ``` Windows 10 Pro x64```

**Comment by memsharded** [comment]
Hi @013ez 
Thanks for the report. Yes, this might be an unexpected issue with the userprofile & userhome Windows environment variables.

We need to check it, but in the meantime I would suggest:
- Try not running as root/system. Conan doesn't need root permissions to operate.
- If it is CI, it is very likely that you want to work on a different, clean folder for each job. Otherwise concurrency might be a big issue. The correct way is to setup a new temporary folder for each job, then define CONAN_USER_HOME to point to that folder, before launching conan.

Please let me know if this helps, thanks!

**Comment by memsharded** [comment]
Also, could you please check your python and conan installation? Did you install conan with pip? Is your python 2.7, 3.X, 32 or 64 bits? If you are running with a 32 bits python, you might try to use the 64 bits one, it might work.

**Comment by 013ez** [comment]
> Try not running as root/system. Conan doesn't need root permissions to operate. 

I have problem with start CI agent as not system user.

> define CONAN_USER_HOME to point to that folder, before launching conan.

Thank you. I was set CONAN_USER_HOME and PATH windows  environment variables from gui (from cli not working) and it helped me. I reinstall python from 2 to 3, working versions:
- Python ```3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32```
- conan ```1.1.1```

**Comment by memsharded** [comment]
Ok, great, so with CONAN_USER_HOME and PATH and Py3.6, now you are able to work, right?

Still we need to have a look to those confusing paths, it won't be very common, but it still can happen to some other user. Thanks for following up.

**Comment by memsharded** [comment]
I have tried to run from my Administrator account in Windows 10, still the paths are mapped to ``C:\Users\Administrator``, so can't reproduce from here. Not saying that it is not an issue, only that I cannot make it fail.

If anyone can help with some configuration tip, or a fix or something, it will be very welcome. Thanks!

**Comment by liberforce** [comment]
The gitlab-runner seems to use a system-kind of user.

When running as Administrator, I have this environment:

```
USERNAME=Administrator
USERPROFILE=C:\Users\Administrator
```

When in the runner job, I have:

```
USERNAME=(machine name)
USERPROFILE=C:\Windows\system32\config\systemprofile
```
The `.conan` dir is created as `%USERPROFILE%\.conan`, so you probably want to change the value of `USERPROFILE` to reproduce the issue.

**Comment by memsharded** [comment]
I am getting some access permissions error with that path.

In any case @013ez, @liberforce, it desired that the conan local cache with that context is stored in ``C:\Windows\system32\config\systemprofile`` or ``C:\Windows\SysWOW64\config\systemprofile``?

Because I am not sure I would store my conan local cache (also, my temporary builds from different jobs), there. So still, the solution is to define a CONAN_USER_HOME anyway, isn't it?

Thanks for the feedback!

**Comment by liberforce** [comment]
FIY, I don't trigger @013ez 's bug (my build fails for other reasons I'm still sorting out), but I'm on Windows Server 2016 on AWS, so the environment is different.

@memsharded: gitlab-runner clones the code under `C:\Users\Administrator\builds\`, it's just the `.conan` that goes inside `C:\Windows\system32\config\systemprofile`. I agree that using `CONAN_USER_HOME` should avoid the problem entirely, but it's not the default configuration, so some people like @013ez will still trigger this bug by default, which is bad.

Anyway, conan should read and write configuration at the same location. If you decide that guesswork is not supported, it should display an error message telling to solve the problem running as a real user, or using `CONAN_USER_HOME`.

I'm pretty sure every user of gitlab-ci on Windows will fall on this one, just because running the runner using a system machine account is the default. Using a specific user requires more search and configuration work around the rights for that user and using `gitlab-runner install` with the `--user` option.

**Comment by memsharded** [comment]
More than 4 years since this issue, I am closing this ticket as stale.
Not sure if gitlab-ci changed their configuration, or Conan users learned about the CONAN_USER_HOME, but we haven't got any further report. Closing, please report if this is still raising errors. Thanks!

**Comment by FDK45** [comment]
Hi, when using the current version of gitlab-runner the issue remains. Without a change of CONAN_HOME, conan looks for a profile in `C:\Windows\System32\config\systemprofile\.conan2`. I am on Windows 10.

**Comment by memsharded** [comment]
Hi @Splixz00 

Conan 2.0 uses the home ".conan2", to avoid conflicts with Conan 1.X user home, so both can be used at the same time.
