### ISSUE TITLE
exports_sources loses part of relative path when ../ is used

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#2675]
When `../` is used in the path for a path in the `export_sources` attribute of a conanfile, the relative directory structure in the generated package under the `exports_sources` directory behaves "unexpectedly".  It's actually unclear what the "expected" behavior would be when the `../` is used, as it's not intuitive or obvious when you consider that we're passing a pattern and not `source` or `destination` parameters. 

_Note that this is a corner case, as the vast majority of uses of `exports_sources` involve the `conanfile.py` existing in the root of the sources, not some external subdirectory of a parent directory as in this example   It's possible that the use of `../` in `exports_sources` should simply be unsupported if a predictable/sensible behavior cannot be agreed upon ._

Expected/desired directory structure in `exports_sources` directory: 
`hello/src/file.c`

Actual directory structure:
`file.c`

```
from conans import ConanFile, CMake
class HelloConan(ConanFile):
    name = "hello"
    version = "0.1"
    exports_sources = "../../hello/src/file.c",

```

If I were to define the behavior that makes the most sense for my use case, it would be to retain the directory structure with all `../`'s stripped from it, but I'm not even sure that makes sense for all cases. 

This is not a blocking issue for me, as I can define where i want the files to go with the `package()` step in my case. 

[exports_sources_ssue.zip](https://github.com/conan-io/conan/files/1844723/exports_sources_ssue.zip)

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Submitted https://github.com/conan-io/conan/pull/2676, but not sure if breaking.

In the meantime you might try to workaround it with:

```python
class HelloConan(ConanFile):
    name = "hello"
    version = "0.1"
    exports_sources = "../../hello*src*file.c",
```

**Comment by sourcedelica** [comment]
Related to this, we need a way to `exports` a Python script from a common directory which could be a parent or sibling to the `conanfile` directory (also discussed in #1271).   The Python script could contain a `Conanfile` base class and/or functions.

**Comment by lasote** [comment]
I think we should postpone to 1.5 at least because the fix is not very clear for me and the exports method, that could be a fix for this issue, it is neither clear.

**Comment by memsharded** [comment]
The solution to this issue would be breaking, so delaying it until 2.0.

If someone requests this as an important and urgent feature, we might try to re-evaluate and see if there are other solutions, like the mentioned ``export()`` method, so far it seems there is not enough evidence to move it forward.

**Comment by dieterrosch** [comment]
I also find it quite confusing that the directory structure does not get kept in a corner case. I expected that exports_sources = "../src/*" would keep the /src/ directory structure intact, as this seems to be the case when I have the recipe in the same directory as the ./src/  subdir. Some possible solutions I can think of:

My use case:
We develop custom software for a number of different client across many different industries. We have a number of existing libraries. Do keep the source directories clean, we want the conanfile.py, as well as the test_package folder, in a separate subdir, so that projects that do not use conan, do not need to pollute their base source dirs with them. Projects that want to leverage conan, must simply run the conan recipe from the subdir to create and test a package.

1. add an additional attribute export_source_tree (or export_sources_full etc) = "../src/*.h" which will parse the entire tree specified and copy the files that are expressioned, keeping the tree intact. 

2. Pass a decorator  to export sources that tells it to keep the tree such as:
exports_sources = FullPath("../src/*")
The FullPath decorator could be a generator that just returns a list or tuple of files (with full path names) that satisfy the expression.

3. Set some parameter such to force the behaviour, eg:
exports_sources = FullPath("../src/*")
export_sources_keep_full_path = True

Personally i prefer option 2, it seems the cleanest and most explicit, doesn't require the underlying infrastructure code to be changed and it can be expanded to other decorators if needed.

**Comment by dieterrosch** [comment]
Looking at this further, I have come up with the following:

conanfile.py:
```py
from conans import ConanFile, CMake
import os
import glob
import fnmatch

def FullPath(path, pattern):    
    files = []

    # lookup recursive
    for dirpath, dirnames, filenames in os.walk(path):

        if not filenames:
            continue
        pythonic_files = fnmatch.filter(filenames, pattern)
        if pythonic_files:
            for file in pythonic_files:
                print('{}/{}'.format(dirpath, file))    
                files.append('{}/{}'.format(dirpath, file))
    #items = (item for item in files)
    return files


class MainConan(ConanFile):
    name = "libMain"
    version = "2.0"
    license = "custom"
    description = "libMain Library by BBD"
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=False"
    generators = "cmake","txt"
    exports_sources = FullPath("../src/","*"),"../CMakeLists.txt", FullPath("../padgen/","*")
```

And change in conan_file.py:
```py
#Added the flatten() function to flatten a list/tuple recursively, based on
#http://rightfootin.blogspot.com/2006/09/more-on-python-flatten.html and
#http://basicproperty.sourceforge.net/
def flatten(l, ltypes=(list, tuple)):
    ltype = type(l)
    l = list(l)
    i = 0
    while i < len(l):
        while isinstance(l[i], ltypes):
            if not l[i]:
                l.pop(i)
                i -= 1
                break
            else:
                l[i:i + 1] = l[i]
        i += 1
    return ltype(l)

def create_exports_sources(conanfile):
    if not hasattr(conanfile, "exports_sources"):
        return None
    else:
        if isinstance(conanfile.exports_sources, str):
            return (conanfile.exports_sources, )
        #Changed the line below to use flatten function
        return flatten(conanfile.exports_sources)
```

Seems minimally invasive, and solves the problem at hand, while allowing extension by having other functions that return tuples/lists/iterators.

If you're happy with the approach, I'm happy to make a pull-request, and move FullPath into it's own file.

**Comment by sourcedelica** [comment]
Is there an issue for the aforementioned `export()` method ?  It would be a nice way to avoid the limitations of `exports_sources` without requiring a breaking change.   Having a `self.copy()` in `export()` would put it on par with `imports()` and `package()`.

**Comment by drozel** [comment]
Conan 1.9.0
The same issue?

`exports_sources` = ["../../include.pri", "*.cpp", "*.h", "*.pro"]`

client/cmd/export.py:232:
`for pattern in included_sources:
    233         copier(pattern, links=True, excludes=excluded_sources)`

client/file_copier:77:
`src = os.path.join(base_src, src)
      = os.path.join(self._base_dst, dst)
     print(' xxxx    ' + ' ' + str(src) + ' ' + str(pattern) + ' ' + str(links) + ' ' + str(excludes)) #debug from me
     , link_folders = self._filter_files(src, pattern, links, excludes,
`
gives me:
` /home/vitaly/projects/myProj/ include.pri True []`
it means, it taking also all symlinks in the  /home/vitaly/projects/myProj/ but i need only inlude.pri!

**Comment by memsharded** [comment]
The PR https://github.com/conan-io/conan/pull/2676 has been there for a very long time, but was not merged because it was dangerous and could be breaking.

In the meantime, conan has learned the ``export()`` and ``export_sources()`` methods in Conan 1.26: https://docs.conan.io/en/latest/reference/conanfile/methods.html#export

As they have the ``src`` argument, they can specify the root folder, including parent folders that should be used explicitly. This would be the recomended approach when having to deal with this issue. So I think this issue can be considered fixed by this functionality and can be closed. But please try it, and if it doesn't work for your case let us know, reopen, or create a new issue. Thanks!
