### ISSUE TITLE
Final space in [requires] causes an error

### ISSUE THREAD

**Issue by fpelliccioni** [conan-io/conan#268]
If I write an extra space in a [requires] line, I got:

ERROR: 'stable ' is an invalid name. Valid names MUST begin with a letter or number, have between 2-40 chars, including letters, numbers, underscore, dot and dash

I think it could be trimmed.

Ie:
[requires]
zmqcpp/4.1.1@memsharded/stable 

(There is an space after "/stable".)

EDIT: It seems to work properly on Linux but not on OSX and Windows.

Thanks and regards,
Fernando Pelliccioni.

**Comment by memsharded** [comment]
The requirements are already stripped when parsed from conanfile.txt: https://github.com/conan-io/conan/blob/develop/conans/client/loader.py#L152 I have tried to reproduce this error, but still not able, investigating it.

**Comment by memsharded** [comment]
I have tried to reproduce this issue in Win, Linux, Mac, not possible.
I guess it was not whitespace but some special or control character that got there, maybe by copy & paste. I will close the issue by now, and if the problem comes again and you are able to reproduce, a snippet, a repository or whatever, we'll have a look. Thanks!
