### ISSUE TITLE
cppstd setting has no default value

### ISSUE THREAD

**Issue by T1T4N** [conan-io/conan#2694]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hello,

First off, I would like to say thank you to everyone involved in this awesome project.

I have read the [how-to article about managing the C++ standard](http://docs.conan.io/en/latest/howtos/manage_cpp_standard.html#package-compatibility), where it is stated that "By default Conan will detect the default standard of your compiler to not generate different binary packages."

My conan package uses a custom build system for which I need to manually parse and pass the CXX flags.
I caught the error when I tried to pass a flag for the standard with the following code:
```python
if "gnu" in self.settings.cppstd:
    cxx_flags.append("-std=gnu++%s" % str(self.settings.cppstd).replace("gnu", ""))
else:
    cxx_flags.append("-std=c++%s" % str(self.settings.cppstd))
```
```python
cxx_flags.append("-std=c++%s" % str(self.settings.cppstd))
TypeError: __str__ returned non-string (type NoneType)
```

Upon further debugging I spotted the following custom warning being outputted:
```python
if not self.settings.cppstd:
    self.output.warn("cppstd empty")
```

My recipe specified cppstd in the settings and I did not pass a command line argument and the settings.cppstd was None instead of a detected default value.
I ended up with the following temporary workaround in my ```configure``` method:
```python
 if not self.settings.cppstd:
     self.output.warn("cppstd empty, setting default")
     from conans.client.build.cppstd_flags import cppstd_default
     self.settings.cppstd = cppstd_default(self.settings.get_safe("compiler"),
                                           self.settings.get_safe("compiler.version"))
```

I would assume that the default value should be set for the user as well as internally when no cppstd command line argument is given but it is specified in the recipe.

For the record, not having the cppstd specified in the recipe, (properly) throws an exception on the following line:
```python
if not self.settings.cppstd:
        ConanException: 'settings.cppstd' doesn't exist
```

Software information:
I'm currently using ```Conan version 1.2.0``` on
```
ProductName:    Mac OS X
ProductVersion: 10.13.3
BuildVersion:   17D102
```
with
```
Xcode 9.2
Build version 9C40b
```
and ```Python 3.6.4``` installed from brew

**Comment by lasote** [comment]
Hi! I'm glad you like the project, many thanks.

About the `cppstd`, following the Conan model or correct way to do the things, you should declare the `cppstd` in your profile (or default profile). In general, forcing a setting in the `configure` method is not a good idea. This way, you can control the different packages generated by changing the profile.

In your build method, `if not self.settings.cppstd` you can omit the flag `-std`, and the compiler will use the default. Otherwise, adjust it.

So, the sentence: `By default Conan will detect the default standard of your compiler to not generate different binary packages.` means that you can generate packages without specifying any `cppstd` setting value (so no -std flag will be used in your compilation), but if later, you specify a `cppstd` value, if this value is the default of your compiler, the `package id` will be the same as the previous generated package.

About `from conans.client.build.cppstd_flags import cppstd_default`, it is ok, but please, take into account that we could break any function not documented in the reference: build helpers, tools module, conanfile methods and vars and so on.

Hope it makes sense for you!

**Comment by T1T4N** [comment]
Hi @lasote,

Thank you very much for the quick reply.
Also thank you for the tip about removing the ```-std``` flag.

I understand that the ```cppstd_default``` function might change at any time and that was just a quick fix I made after examining conan's source code.

Still, I do think that IF the author specified ```cppstd``` in the conanfile, that would make it mandatory for that recipe and an error should be properly thrown if it is not supplied.

Similarly how, for example, if I intentionally remove the ```arch``` from my conan profile and try a build, conan reports the following error message:
```ERROR: Conanfile: 'settings.arch' value not defined```

**Comment by lasote** [comment]
The `cppstd` is a special case, it has to have a default None value because the None means: "The compiler default".

**Comment by memsharded** [comment]
Also, the ``None`` settings do not require to be set explicitly, its value is None by default. This allows a smoother introduction of such new settings (``cppstd`` was introduced very recently)

**Comment by danimtb** [comment]
Hi @T1T4N!

Yes, there is already an issue opened in the docs repo to document this: conan-io/docs#474

**Comment by T1T4N** [comment]
Awesome! Once again, a big thank you to everyone who is involved with the development of this project.

**Comment by memsharded** [comment]
Great!
You might also try the generic conan function:

```python
        cppstd_flag = cppstd_flag(conanfile.settings.get_safe("compiler"), 
               conanfile.settings.get_safe("compiler.version"),
               conanfile.settings.get_safe("cppstd"))
```
