### ISSUE TITLE
Remotes management with Artifactory Jenkins plugin

### ISSUE THREAD

**Issue by madpipeline** [conan-io/conan#2696]
Conan version: `1.1.1`
Jenkins version: `2.89.4`
Artifactory plugin version: `2.15.0`

The Artifactory remote is used both by Jenkins and by the developers.

We're using `conan config install` to share the remotes and profiles.

Pipeline snippet:
```
def server = Artifactory.server env.ARTIFACTORY_ID
def client = Artifactory.newConanClient userHome: "${env.WORKSPACE}/conan_home".toString()
String server_name = client.remote.add server: server, repo: env.ARTIFACTORY_REPO

client.run(command: "config install ${env.CONAN_SETTINGS_URL}".toString())
client.run(command: "create --profile Linux-Release . myteam/unstable")
client.run(command: "upload myproject/*@myteam/unstable --all -r ${server_name} --confirm".toString())
```

When adding the server using the Artifactory plugin the authentification for that server is also done, so we can't remove that step.
When adding the same remote from `conan config install`, we loose the remote the plugin added, which causes the build to fail in the upload step, as the remote name the plugin uses does not exist anymore.

If we reverse the adding, doing `conan config install` before the `client.remote.add server: ...` then the plugin server add fails, because a server with the same URL already exists.

There currently is no way to tell the Artifactory Jenkins plugin to use a specific name for a remote, so we may use the same remote.

**Comment by memsharded** [comment]
Trying to understand the issue. What if you don't declare ``server`` at all, and if you have the remotes defined in your ``conan config install``, which means that you know the remotes, just hardcode the upload?
```
client.run(command: "upload pkg/0.1@user/channel --all -r=myremote --confirm" ...)
```
For authentication you could use the ``CONAN_LOGIN`` and ``CONAN_PASSWORD`` environment variables maybe?

Or the other way round, would be not put ``remotes.txt`` in the ``conan config install`` and configure the remotes in the pipeline.

If you could please ellaborate how  do you think would be the best approach. Thanks!

**Comment by ovidiub13** [comment]
The remote needs to be defined in the `remotes.txt` that get's pulled with `conan config install`, because those settings are used by the developers. So removing this isn't an option.

Not declaring the `server `is and using the environment variables is an option, but as I've noticed with this plugin, if I run the job in a docker container the plugin breaks the Jenkins workflow and prints out every environment variable.

Even if not using docker, any developer could print the environment, or the environment is getting passed to Artifactory, and the password is stored there in clear text.

IMO that is a security issue. The safest thing is to use the credentials plugin for Jenkins, and declare the `server`.

A possible fix for this is to not overwrite all remotes (perhaps optional), or allowing to have two names for the same remote. I"m not happy with the second option, but it's an idea.

**Comment by memsharded** [comment]
> The remote needs to be defined in the remotes.txt that get's pulled with conan config install, because those settings are used by the developers. So removing this isn't an option.


Having 2 names for the same remote could indeed be very confusing, I am not very happy with the idea either. The current behavior of "remotes.txt" for ``conan config install`` can't be changed, that would be breaking. When you say not overwrite, does it mean that it will keep existing remotes with the existing URL with the old name, and only add new ones?

Here is another possible idea: Maybe use 2 different URLs for conan config install? One for developers and one for CI?

**Comment by ovidiub13** [comment]
Using 2 different RULs means using 2 different repos. What would be the point of that?

Then jenkins will upload the packages to one repo and how would the developers get to use those packages?

Regarding the change to `remotes.txt`, my proposal is: have an option to `conan config install` that allows to append remotes, not overwrite the whole list.

In relation to the same URL being added twice... IMO, the Artifactory plugin should detect that the URL is already added, and just use it. I think this is the best approach.

**Comment by Aalmann** [comment]
Hi,

in #2690 a similar problem with workaround is described.
The best solution would be to fix the artifactory plugin by providing the possibility to set the remote name (e.g. `def serverName = client.remote.add server: server, repo: reponame, remoteName: "my-remote"`) which will lead to `serverName == remoteName`. Or better to completely remove the UUID-thing. However, then a `conan config install` will "update" the remotes (or in this case not update because it is already set correctly) and one can reuse the remotes. Not sure if there would be a problem with the already "logged in" user after the `conan config install` and remote update.

:+1: for the config install append approach. There are some other use cases like special CI settings in conan.conf or switching developers between teams which need something like that. It would be nice to have such a feature to be able to provide a general-config and a project specific setup which could be appended.

**Comment by ovidiub13** [comment]
The server session remains active and the upload works after overwriting, and using the "my-remote" name.

**Comment by memsharded** [comment]
The Artifactory Jenkins plugin will not provide integration for Conan anymore.
We have realized that it was a really thin layer providing almost no value, and producing more problems than advantages. Calling ``conan ...`` directly from Jenkins is very straightforward, we do it a lot in our own CIs for ConanCenter, we dropped the plugin long time ago ourselves.

Closing this ticket as not planned.
