### ISSUE TITLE
conan profile for gcc "compiler.version=5" does not resolve packages with "compiler.version=5.4"

### ISSUE THREAD

**Issue by Aalmann** [conan-io/conan#2726]
Hi,

we found an issue concerning the gcc-compiler (version) and the package resolving algo.
**History:**
Our CI system created packages using the conan settings at command line like `conan create . MyProduct1/1.0.0@user/channel -s compiler=gcc -s compiler.version=5.4 ...`. When searching for these packages the output contains `compiler.version: 5.4`. Because all jobs used the same command line, everything works as expected and everything was fine. I know this was probably not the best idea due to gcc 5 compatibility but on the other hand it is not completely incorrect.
**Now:**
After the discussion in another issue we switched to `conan profiles` as suggested by @memsharded which are distributed through a zip file and installed using the `conan config install`. Therefor I collected all default profiles of all our different slaves (Windows & Linux with different compiler versions) and put them into that zip file.
But now packages which are formerly built with the same gcc and with the command line setting `-s compiler.version=5.4` can no longer be found, (I think) because `"compiler.version=5.4" != "compiler.version=5"`.

But IMHO these packages (with `compiler.version=5.4`) should also be found when a depending package is built with `compiler.version=5`. 

Best Aalmann

**Comment by lasote** [comment]
Hi!

The reason is that we want to keep the distinction between "5" and "5.4" because, even being compatible, "5.4" could have improvements from "5.2". And it matters for some users.

Said that to be able to do what you suggest we would need to exclude the "minor" part of the version (5.4 => 5.X), but then we won't be able to generate different binary packages for 5.1, 5.2, 5.3, 5.4... and so on. All the packages would have the same ID.

The easiest way would be to change the CI and use the `compiler.version=5` in the profile. Is that possible for you?
Otherwise, you would need to change your `package_id()` method in all your recipes to only take into account the major version of GCC.

**Comment by Aalmann** [comment]
Hi @lasote 

for sure it is easy for me to add the `compiler.version=5.4` to the profile in the config package. But when a user is just using the default profile which is generated with `compiler.version=5` he won't be able to resolve any packages which are built with `compiler.version=5.4` even the packages are compatible/usable in that case. It was more obvious with gcc 4 which also contains the minor versions in conan profile. From gcc 5 the default is "just" major version which looks to the user as it is always compatible and all minors are included. It is something like a "version range".

I would expect the following behaviors (package_B requires package_A):
- package_A was built with `compiler.version=5.4` and package_B will be built with `compiler.version=5` ==> conan resolves package_A because it was built with a "gcc 5" and is compatible
- package_A was built with `compiler.version=5` and package_B will be built with `compiler.version=5.4` ==> conan resolves package_A because it was built with a "gcc 5" and is compatible
- package_A was built with `compiler.version=5.2` and package_B will be built with `compiler.version=5.4`  ==> from a user point of view conan should resolve but there are probably some use cases where it is important to have the exact gcc version (and that's the reason why the minor version is specified). So it would be fine if conan fails.
- package_A was built with `compiler.version=5.4` and package_B will be built with `compiler.version=5.2`  ==> because the package was built with a newer gcc version, conan should fail even the packages may be compatible. The version is set explicitly so everything is fine and every user will understand why it fails.

**Comment by lasote** [comment]
> for sure it is easy for me to add the compiler.version=5.4 to the profile in the config package. But when a user is just using the default profile which is generated with compiler.version=5 he won't be able to resolve any packages which are built with compiler.version=5.4 even the packages are compatible/usable in that case. 

What I suggested is to generate the packages with the profile using `compile.version=5`, if you are not interested in differentiating the GCC minors, just generate packages for gcc=5.

**Comment by milancpp** [comment]
While I agree that packages that do not require any specific compiler minor version should just be built with compiler.version=5, I also think that the resolver logic described by @Aalmann would both be useful and correct.

Then again, I'm not sure why the general "5" or "6" is a dedicated compiler version in Conan. Isn't it a version range of sorts?

**Comment by Aalmann** [comment]
@lasote any thoughts about it? Currently one can not combine packages built for `gcc=5` and `gcc=5.4` because they can't be resolved (see my example list above). So when user A is building with `gcc=5.4` and user B with `gcc=5` (conan default setup) and user B wants to use a package of user A, user B has to recompile the packages which might produce exactly the same output.

**Comment by PiJ82** [comment]
In general I agree with the approach @Aalmann proposed [in an earlier comment](https://github.com/conan-io/conan/issues/2726#issuecomment-379713744).
Additionally it should be pointed out, that at least in my understanding `compiler.version=5` and `compiler.version=5.0` would also have different semantics following this approach, meaning the explicitly given minor version adds another constraint.

Nonetheless, - while being a little counter intuitive - implementing the `package_id()´ as suggested by @lasote  in the previous comment does indeed seem to do the necessary magic.
Further information about that might also be found in the documentation [here](http://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#defining-a-custom-package-id)

**Comment by lasote** [comment]
This could be related with the GLIBC issue, where it matters the retro-compatibility. I add this to the 2.0 milestone to see if we can improve the settings model to support this use case of "compatible" possible values of settings.

**Comment by Smit-tay** [comment]
I think I have a similar situation.
Using a package built with gcc version 7, but my current gcc version is 9

I can't even retrieve the package, even though it will probably work fine.

Seems to me that Conan is reinventing the wheel, and of course re-discovering all the edge cases that make package management so difficult.

Anyway, what is wrong with a compiler.minversion ?

At least let me retrieve the package and attempt to build with it !

**Comment by Smit-tay** [comment]
Editing ~/.conan/profiles/default  and "lying" about my compiler version allows me to build a solution that relies upon a package that claims to require a specific GCC version. The package is relatively insignificant, and so is my compiler version (really).

I guess it's easier to pretend those kind of issues simply don't exist !

But then, that's pretty much the history of Python from what I can tell.  Superficial solutions to complex problems.

Maybe that's whay python 3 and python 2 don't work well together.

But then neither does Python 3.7.2.1 and Python 3.7.2.3 - where's the surprise?

**Comment by Lyberta** [comment]
> I think I have a similar situation.
> Using a package built with gcc version 7, but my current gcc version is 9

You are not supposed to link code built with different major versions together. This is a foot gun and Conan is protecting you from shooting yourself.

**Comment by Smit-tay** [comment]
Where is that documented ?

**Comment by memsharded** [comment]
@Smit-tay 

If you want to force some package to use a specific setting, you can do it:

```bash
$ conan install ..... -s mypkg:compiler.version=7
```
Even if your profile, or your current default is version 9, that ``mypkg`` package will be installed with version 7

If you want to define a custom logic for your own packages, because you are absolutely sure that packages built with one compiler version will work with other compiler versions, you can use ``compatible_packages`` feature in the ``package_id()`` method: https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#compatible-packages

Although in theory, and with some environment conditions (for example, less an issue with C, but easier to bite you in C++), you can have ABI compatibility for forward compiler versions, we have learnt that in practice it is a much safer default to require binaries to be built with the same compiler major version at least, and this is the Conan default. If you are going to be using a newer compiler version, it really makes sense to build the dependencies with that newer compiler version too, and Conan will manage the binaries of those dependencies with both the previous compiler versions and the new one, without conflicts.

As usual, that is the Conan default, but Conan tries to provide as much configuration as possible. The whole settings can be customized: https://docs.conan.io/en/latest/extending/custom_settings.html, and with the ``package_id()`` method you can define any ABI compatibility you want.

**Comment by memsharded** [comment]
Hi @Aalmann 

I think that the use case described above:

> But now packages which are formerly built with the same gcc and with the command line setting -s compiler.version=5.4 can no longer be found, (I think) because "compiler.version=5.4" != "compiler.version=5".

Might be satisfied with the ``compatible_packages`` https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#compatible-packages feature, implementing a fallback to all the lower minor versions. That will allow both using packages built with previous minors, and also rebuilt binaries with latest minors, without breaking the flow. It is not implemented as the default, but probably takes just a few lines in your ``package_id()`` method. Please have a look at it, and let me know if it helps. Thanks!

**Comment by Smit-tay** [comment]
I am building and running - without any detectable issue - with cc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)

And the packages are specified as gcc 7

All that was required to enable this was 
set(CONAN_DISABLE_CHECK_COMPILER TRUE)

I'm not going to try to pretend that I know better than you, but, it seems unlikely that this is a fluke.

I'm pretty sure that it would take more than just a major version change to cause problems.  

I would expect that a library built with the compiler setting to C++20 might not behave with other libraries built against C++11, for example, there being significant changes to the behavior of the language itself.  But if all binaries agree on the language version, I would expect compatibility, regadless which compiler version was generaing the code.  You likely know more.

**Comment by memsharded** [comment]
Certainly there a a few things that cause big and noticeable ABI incompatibilities. The stdlib one of them, and using ``libstdc++`` and ``libstdc++11`` in the same link, will get linker errors. Runtime, exceptions, build_type... there are many different configurations (all of them are Conan settings), that will likely result in ABI incompatibility and easily detectable at link time.

Though compiler version is way more unlikely to produce link errors when moving forward, we have been reported issues at runtime, more occasional, but also extremely more difficult to debug. Some of those cases were due to bugs in compilers, and not really intended incompatibilities, but they hit the users. So we opted into a default that is "safer", especially because with Conan is easy to upgrade dependencies to new compilers without breaking, so most users once they are using a modern compiler version for the apps, they also build binaries of their dependencies with the new compiler version. As many times in SW engineering, it is a trade-off, and for this one we went for what seemed to be the more conservative or "safest" approach that in practice works very well, while trying to provide tools to specify other ABI compatibilities, for those who want a different model.

**Comment by bog-dan-ro** [comment]
This issue looks very similar with this #7664 one

**Comment by memsharded** [comment]
It is expected that Conan will not implement a default compatibility between different settings, including the fallback from major compiler versions to minor compiler versions.

But Conan 2.0 introduces a new ``compatibility.py`` external plugin in which users will be able to easily define the binary compatibility they want for all their packages (this plugin can be updated and distributed with ``conan config install``). This way users will have full control of compatibility without conan trying to define a potentially unsafe one.

Conan 2.0 is already in beta.9, soon to be GA, closing this issue as solved, thanks very much for all the feedback.
