### ISSUE TITLE
Support for SVN Externals? [question]

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#2732]
I am currently using svn:externals to define which sources are fetched into my projects.

My current understanding is that if I migrate to Conan, I need to provide Conan with a list of svn urls (for each external repo) in the source() method.  Please correct me if I'm wrong, but I suppose Conan makes use of this information to record exactly what input is used to [re]produce the artifact.  

The problem with this approach is that I would need to remove the svn:externals definition.  Svn:externals is very useful for development environment for many reasons, and I would like to preserve this setting.

Is it feasible to have Conan parse the svn externals property to collect this information?

**Comment by lasote** [comment]
I barely know how the "svn:externals" works, and I would need more information about your concrete use case. Do you need these "svn:externals" even modularizing your projects and dependencies?

> My current understanding is that if I migrate to Conan, I need to provide Conan with a list of svn urls (for each external repo) in the source() method. 

Conan will run in the source() method whatever you need to get the sources, as I don't know much about the svn:externals I don't know if it makes much sense. 

> Please correct me if I'm wrong, but I suppose Conan makes use of this information to record exactly what input is used to [re]produce the artifact.

Conan won't record anything, if a user request to build from sources the Conan package it will perform the `source()` method again, if the files in the origin repository have changed, it will retrieve the new ones. That's why (with git) we recommend to checkout a TAG or at least a branch or a commit to achieve reproducible builds. 

But you can avoid the `source()` method usage and export all the needed source code together with the recipe using the `export_sources` feature. That way it doesn't matter how you got the files, it copy the specified sources together with the Conan recipe and any following recipe building will use the "frozen" source files.

> Is it feasible to have Conan parse the svn externals property to collect this information?

I would need to know a little more about the externals and your use case to understand this, but if you can do it in the command line, you can tell conan to do it for you.

**Comment by Aalmann** [comment]
@lasote `svn:externals` are nearly the same as `git:submodules`. They just point to other repos and include them into your source tree. 

@GordonJess you should get rid of `svn:externals` (we already did it with a lot of pain). Create a recipe for each repo and add them as requirements if not already done. I guess you are using `svn:externals` for development to have all packages in one single solution/project. Have a look at #1377 which could be the answer. With that approach you are also able to mix different scm systems (assuming that you want to switch to git step by step).

For the meantime: 
Provide the scm information (url, branch, etc.) in each `package_info` of your requirements as `user_info`. Then you are able to collect them in your source method evaluating the `self.in_local_cache` attribute to detect the developer mode and run `svn propset` commands. Add a flag to you build system layer to switch between your `svn:externals` and the usage of already deployed packages.

**Comment by danimtb** [comment]
Suggestion above seems the way to go. Currently we have SVN wrapper tool that might also help "cloning" a svn repo with externals in the source() method or maybe it could be considered for the SCM feature. Anyway, please if you try SVN wrapper and SCM and it does not fit your use case, feel free to open a new issue with the information updated. Thanks!
