### ISSUE TITLE
SettingsItem equality checks too strict, raises errors

### ISSUE THREAD

**Issue by Lnk2past** [conan-io/conan#2744]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

---------------------------------------------------

I am working on Windows 7 with Conan v1.0.4, but the source code is the same in that version as the code in 1.2.3/latest. Stumbled upon this issue when trying to build [this Boost recipe](https://github.com/conan-community/conan-boost).

I recently started modifying our group's settings.yml file to be more appropriate and aligned with our environment. This meant removing all of the extra stuff that was not applicable and adding a few extra things. Unfortunately, the ```__eq__``` and ```__neq__``` methods of ```SettingsItem``` ultimately bomb out in some pretty common cases.

conans\model\settings.py:89-95
```
    def __eq__(self, other):
        if other is None:
            return self._value is None
        other = str(other)
        if self._definition != "ANY" and other not in self.values_range:
            raise ConanException(bad_value_msg(self._name, other, self.values_range))
        return other == self.__str__()
```

The offending line in the recipe is:
```
if self.settings.os != "Android":
```

Because I removed "Android" as an valid entry for the os setting, the exception gets raised. This seems like it should be a warning rather than an exception.

I can certainly put the removed values back into my settings.yml file, but that seems like a workaround rather than a fix. Similarly, I do not want to have to modify the recipe as I do not want to have to maintain my own.

**Comment by memsharded** [comment]
Hi @Lnk2past 

Thanks very much for your feedback. 

The thing is that we still think that this is a very valid feature. The recipe you are using is expecting to be able to evaluate the OS against "Android", and if that is not defined in the settings.yml file, then it is an error. It is precisely its purpose. 

What happens if you decide to edit your settings.yml and rename it to "android" in lowercase? If the system was relaxed it will just warn (difficult to notice), and fail later in a stranger way, more difficult to debug and waste more users time.

It is perfectly reasonable that you don't want to change the existing recipes, but you have to provide those recipes with the minimum "vocabulary" they need to evaluate, and that is precisely the ``settings.yml`` file. There is nothing wrong to have a ``settings.yml`` file with more values that you need, in fact it is very reasonable. Those settings are not your configuration or your available configurations, it is more a "dictionary" of existing configurations in the general domain. There is no gain in restricting them. The definition of configurations is not given by the ``settings.yml``, it is given by "profiles". Profiles are the 100% recommended feature to define your package configurations.

**Comment by Lnk2past** [comment]
Hey @memsharded, thank you for the response.

I find it sort of misplaced that when building with os='Windows' that a conditional that is checking for 'Android' results in the exception. I just would have expected the recipe to carry on with the content of that conditional block, as my os was not 'Android', thus satisfying the conditional.

Based on your response, I guess I am a little lost on why settings.yml exists at all? (I'm not asking, sort of, just seems redundant to have settings.yml at this point).

**Comment by memsharded** [comment]
It is not redundant. ``settings.yml`` was introduced as a necessary common ground and vocabulary, in order to have some agreement for names. Otherwise, it could happen that people started to use in their recipes:

``ìf self.settings.os == "Win",  if self.setting.os=="androidOS"``

You will end with recipes for different packages requiring Win, Windows, windows, Win32 as ``self.settings.os``, and that is impossible. Same happens also for compilers, etc. 

So when a recipe is created, it is created against a certain vocabulary. The Boost recipe requires to have ``settings.os`` with possible values ``Android``, ``Windows``, etc. All other possible incompatibilities between recipes and settings will be inmediatly detected and raised, avoiding lots of later pain. ``settings.yml`` is something that appeared to solve a problem, not an arbitrary design decision. Think of it as the XML-Schema (the setings.yml) for an XML document (the recipe settings).

**Comment by Lnk2past** [comment]
I understand why we need settings.yml, that makes a lot of sense.

(the rest of this post is all strictly opinion on my part, just voicing it)

I'm just getting held up on the rigidity of changing that file. In my case I wanted to remove things; I really I should't be doing that though, as this would restrict my usage of recipes that may rely on some of those parameters. If I add something to my settings.yml (perhaps a build type), then no one would be able to use my recipe without changing their own settings.yml to understand that new build_type. On that same note, I have been seeing some issues pop up about the settings files being reverted and overwritten.

I think that establishing a common vocabulary is a great idea, but I think forcing exceptions out is troublesome. To remove some of the ambiguity, the settings could all be converted to lowercase (are there any example of this causing some amount of ambiguity?), but I don't think you could get around someone specifying ```Win``` or ```androidOS``` instead of ```Windows``` and ```Android``` respectively. If anything I would want Conan to provide an obnoxious warning, not an error.

Perhaps an even better solution would be to just keep the default settings that Conan manages embedded in the code base, rather than made "available" for modifications. There could still exist a ```~/.conan/settings.yml``` file that would provide additions (at runtime, Conan could merge the embedded settings with the user settings). This would allow someone to maintain their own simplified settings without needing to worry about mucking up the established language that Conan uses.

**Comment by memsharded** [comment]
I also understand your opinion. Actually there is some other ongoing discussion in: https://github.com/conan-io/conan/issues/2718. I understand that overwriting the settings.yml at conan upgrade is a bit inconvenient, and as outlined there, one possible solution could be to run such a merge (though I think that it would be better to do it only at upgrade time, not at each command run).

It is not that such merge will be easy, but we will be exploring improvements for this. Thanks for the feedback!

**Comment by Lnk2past** [comment]
Closing this to continue the discussion over in #2718
