### ISSUE TITLE
CPU cores with visual studio/devenv and fortran code

### ISSUE THREAD

**Issue by kylemacfarlan** [conan-io/conan#2747]
I encountered this issue when building a package from fortran code (with the intel fortran compiler):

> ----Running------
> > cmake --build C:\Users\Kyle\.conan\data\pkglib\0.1\kylemacfarlan\testing\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 --config Release -- /m:8
> -----------------
> 
> Microsoft Visual Studio 2017 Version 15.0.27130.2027.
> Copyright (C) Microsoft Corp. All rights reserved.
> 
> Invalid Command Line. Unknown Switch : m:8.

Based on this, it seems like the /m:n or /maxcpucount:n commands don't work with fortran code.

The workaround was to change the build routine to this:
```python
   def build(self):
        cmake = CMake(self)
        #cmake.configure()
        #cmake.build()
        self.run('cmake "%s" %s' % (self.source_folder, cmake.command_line))
        self.run("cmake --build . %s " % cmake.build_config)
```

**Comment by memsharded** [comment]
Yes, this is quite likely. The ``CMake`` build helper is mostly developed for C and C++, not fortran. 

Probably it could be improved, but for that, it would be first necessary to model the settings, maybe it is necessary to add a fortran compiler to ``settings.yml``. Or at least define some convention, how this settings would be called, even if it is not in the default settings.yml.

The workaround you did is nice. We always try to make conan configurable, so that kind of things can be done. However, in this case, there is a flag that would provide for this, you can try:

```python
def build(self):
    cmake = CMake(self, parallel=False)
    # or set it later, conditionally to the compiler, for example.
    # cmake.parallel = False
    cmake.configure()
    ....
```

**Comment by kylemacfarlan** [comment]
Thanks for the more elegant workaround. 

I can't comment on the best way of handling this is in the long term, as I don't have enough experience with conan to say. But in the short term the workaround is perfectly sufficient. I opened the issue mostly so that other people could find it if they had a similar issue.

**Comment by memsharded** [comment]
Ok, I will close this issue at the moment.
Still, I would like to provide some built-in utilities for fortran, I'll ping if this move forwards in the future.

Thanks for the feedback!
