### ISSUE TITLE
Useless warning when calling conan package

### ISSUE THREAD

**Issue by ovidiub13** [conan-io/conan#2753]
Conan version: `1.2.3`
With the command:
```
conan package --source-folder /path/to/myProject --build-folder /path/to/myProject/build --package-folder /path/to/myPorject/../../Staging /path/to/myProject
```
And the `package()` in `/path/to/myProject/conanfile.py`:
```
    def package(self):
        self.copy("myProject", src="bin", dst="linux64/bin")
        self.copy("myProject.exe", src="bin", dst="win32/bin")
```
The following output is produced:
```
PROJECT: Generating the package
PROJECT: Package folder /path/to/myPorject/../../Staging
PROJECT: Calling package()
PROJECT package(): WARN: No files copied!
PROJECT package(): Copied 1 '' files: myProject
PROJECT: Package 'Pre-release' created
```

The warning: `PROJECT package(): WARN: No files copied!` in this scenario is useless, and even misleading.

**Comment by memsharded** [comment]
I think it is accurate and matching the specification. You are telling conan to copy a file/pattern. One of the files/patterns specified is not there, and it is telling that it didn't copy anything. I would say it is a total valid warning. If you want to get rid of your warning, you should code it accordingly:
```python
def package(self):
    if self.settings.os == "Windows":
        self.copy("myProject.exe", ...)
    else: ...
```

**Comment by danimtb** [comment]
I think this waring is there because when in local flow, the package method is actually called twice:

https://github.com/conan-io/conan/blob/ac25c8994878706bac23efd009ae74bc294c1add/conans/client/packager.py#L52

In the case of the `''` this is indicating the extensions of the file. As you are building an executable in linux, it has no extension.

I think both messages could be improved for the local flow
