### ISSUE TITLE
Enhancement: Target for executing UnitTests 

### ISSUE THREAD

**Issue by RReymann** [conan-io/conan#2767]
Hi,

Using Conan for awhile and migrating our in-house solution to conan, having a specific target for running unit/System tests could be a useful enhancements: Something like

def test(self):

cheers,
Renaud

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
Hi! For that purpose we have the [CONAN_RUN_TESTS](http://docs.conan.io/en/latest/reference/env_vars.html#conan-run-tests) environment variable. Could it work for you?

**Comment by RReymann** [comment]
Hi,
I am already using this one, it does the job but having a specific target (i.e test) could really provide useful integration with Jenkins Pipeline for instance. 

Cheers,
Renaud

**Comment by lasote** [comment]
What is your idea of that `target`? a method in the Conanfile? 

The thing is, the tests depends on the implementation of the recipe, if you want to test the package, you have the `test` method and the `conan test` command (automatically executed when calling `conan create` if `test_package` folder is present).

In the other hand, if you want to run unit-test after build, you have to build the libraries first, so, why is it better for a Jenkins pipeline to have a separate method if you have to run the regular "build" or "create"?

**Comment by RReymann** [comment]
One of the best practices for Jenkins pipeline is to stage all work, That's mean segmentation of build, test and deploy for instance. One idea behind that is to be able to run tests in parallel (aka split tests) for big projects. Having such segmentation in conan will really simplify Jenkins pipeline integration.  By the way, cmake has already it (correct me if  I am wrong) 

Cheers,
Renaud

**Comment by lasote** [comment]
I understand, thanks for the explanation. Currently, you can follow any of these two approaches:

- The CONAN_RUN_TESTS env var that you already know. 
- Increase the `test_package` functionality to run the tests of the library but against the already built library. This approach can be harder or simpler depending on how the tests are organized in the source code or coupled to the build system, but doing that you could run additional and parallel jenkins steps running `conan test <ref> test_package` for all the needed packages.

I don't like the idea of creating another method to run the tests, because, if it depends on doing first the `build()` then it is almost the same than using the `CONAN_RUN_TESTS` and if it doesn't require the build is because is running against the built package, so you are in the second case, using the `conan test` command with the `test_package` folder.

**Comment by RReymann** [comment]
Thanks for your feedback, your point of view makes sense., I will try the second approach. 
Cheers,
Renaud
