### ISSUE TITLE
pip install meet Mac OS X 10.11 System Integrity Protection error

### ISSUE THREAD

**Issue by vvhh2002** [conan-io/conan#277]
we can't install conan on mac OS X 10.11. cause os use System Integrity Protection tech.

**Comment by memsharded** [comment]
There is a homebrew recipe as well, could you please try to install it with brew (remember brew update first)? Or have you already tried it?

**Comment by memsharded** [comment]
Hi @vvhh2002,
Did you manage to install conan with the brew recipe? any feedback on this?
Please tell me, maybe the docs could be updated. Thanks very much!

**Comment by Xaltotun** [comment]
if you want to use pip, I would use either a virtualenv, or `pip install --user conan`

**Comment by memsharded** [comment]
I hope you have been able to install conan. I have updated the docs install section, to clearly explain installation possible problems (including this one, thanks for reporting!) and solutions: https://github.com/conan-io/docs/commit/f65268377c3bf7ac17f60c5458f8eae630e7c207

It is already published: http://docs.conan.io/en/latest/installation.html

It also cites the brew installation. I think with these improvements in the docs, this issue is properly addressed, so I am closing it, but please @vvhh2002 tell me otherwise or reopen if necessary. Thanks very much for reporting this issue!
