### ISSUE TITLE
Consume the same library name as upstream although with different options?

### ISSUE THREAD

**Issue by Twoflower2** [conan-io/conan#2810]
Conan 1.2.3

How can I specify in the conanfile.py or in the conan install to consume the same library name as upstream although with different options?

**Example**

**Lib1** consumes libA with libA.option:variation=default
**Appl1** consumes Lib1 and libA with libA.option:variation=secure

`conan install` on **Appl1** complains because Lib1 consumes libA and itself consumes libA although with different options on libA.

Is this a bug or how can this be remedied?

**Comment by memsharded** [comment]
It doesn't seem a bug, but a typical conflict in options. To resolve conflicts, you can always override, define the options you want from downstream. It can be done in the conanfiles, and also in command line and profiles. Try:

```bash
$ conan install . -o LibA:option=variation=secure
```
That should force LibA ``option`` is ``variation=secure`` in the whole graph. Unless there is some recipe harcoding the values in the ``configure()`` method. In that case, the recipe should be modified, when they are hardcoded that way is because such package really need that option and if changed it will fail.
