### ISSUE TITLE
Storing environment variables in the conaninfo file breaks with --no-overwrite and arch-independent packages

### ISSUE THREAD

**Issue by tru** [conan-io/conan#2862]
We are now uploading all packages with `--no-overwrite` and that caused problems for the packages that are arch-independent (header only packages for example). The problem in the root is that the built packages contains a conaninfo.txt file which contains the environment variables from the profile. This means that our first build slave will upload a package with CFLAGS and friends that are not matched on any of the other packages.

@memsharded should have more context on how this should be fixed for the future.

**Comment by memsharded** [comment]
We have done an attempt to clear the ``self.info.env_values`` in ``package_id()``, but it is not enough, as this information is also propagated afterwards from upstream packages.

Most likely the solution is in the line of using a manifest based upload/download diff, instead of a md5 snapshot diff, but this should be researched. Also if this is the case, still the conaninfo.txt appears in the manifest, so it would still be considered a change. 

This issue is also related to https://github.com/conan-io/conan/issues/2750, and the reproducibility of the builds. It seems impossible to know if certain env flags will affect the build, needs research.

**Comment by memsharded** [comment]
Closing as outdated, conaninfo.txt is no longer generated locally in 2.0
