### ISSUE TITLE
Unclear documentation with workflow when packaging in-source build only projects

### ISSUE THREAD

**Issue by yeswalrus** [conan-io/conan#2864]
I'm trying to create a conan recipe for libusb which does not appear to support out of source builds. The documentation states in a few different places that conan will copy the contents of the source folder to the build folder, however this seems rather strange since it would mandate a copy for libraries that *do* support them and further does not match what I'm seeing. There doesn't seem to be anything in the tutorial for building packages about what to do in this situation, but I think I need to copy the sources into the build folder manually during the build step. Is there a tool or helper to do this?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @yeswalrus 

Sorry, it is not fully clear if you are talking about the local flow (in user space, conan install + build), or about the normal package creation flow (in cache, conan create). The second one does the copy by default. The first one, does not do the copy, because it was very confusing, specially for packages living in source control, as the build was being done on a copy, and source changes over the working copy wouldn't be tracked by source control. I think you should be able to directly point ``source-folder`` and ``build-folder`` to the same location. Please clarify (and if you have a recipe I could check, that would be useful too). Thanks!

**Comment by yeswalrus** [comment]
I was referring to local flow. I think a note in the section on build flow
detailing this difference and recommending a single folder for source and
build during local development would help alleviate some confusion for
package authors.

**Comment by memsharded** [comment]
Closing as outdated, conan 2.0 has complete new docs.
