### ISSUE TITLE
Add C++2a standard

### ISSUE THREAD

**Issue by Lyberta** [conan-io/conan#2866]
GCC 8 was released a few days ago and added some useful C++2a features such as `std::endian`. I really want to migrate all my Conan packages to `-std=c++2a`.

I think `2a` and `gnu2a` should be added to `cppstd` and then be renamed to `20` and `gnu20` after the publication. This would require support for aliases so packages' hashes won't be changed but we still have several years to develop this feature.

**Comment by lasote** [comment]
We will try to add it in 1.4, but it is already packed so not sure if we are able to do it.
Thanks for the report!

**Comment by danimtb** [comment]
As reported by @leugenea in #2872: GCC 8.1 should be added to *settings.yml*

**Comment by lasote** [comment]
Hi @lyberta, we have been discussing how to name the `cppstd` and  we should call it "gnu20" and "20". Because if you specify `gcc=8` and `cppstd=gnu20` it already means: The partial support of the gnu20 that gcc8 has. If you change your compiler to gcc 9 in the future,  some features of the language will change and won't be compatible, for sure, but it is already modeled specifying the compiler version.
For me is the same that happened/happens when there was/is pending c++17 features.
WDYT?

**Comment by Lyberta** [comment]
The main motivation behind C++2a name is to be prepared for the case when the ISO committee will be late and it actually becomes C++21 or 22.

**Comment by lasote** [comment]
AFAIK the commitment of the committee is to release every 3 years no matter what's in the release, so the standard will be c++20.

**Comment by Lyberta** [comment]
Maybe but I prefer to be prepared for the worst.
