### ISSUE TITLE
Passing settings to `conan build`

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#2899]
We have a conanfile that is building a C++ application. We would like to be able to install packages with one build_type, but call `conan build` with another. This is useful for on-demand debug symbols in packages. Normally, we don't build the debug configurations for our packages because they cost us a lot of build resources, but they are rarely useful. With non-msvc compilers we can link a debug build of our application to non-debug dependencies just fine.

However, we sometimes do want to be able to debug a dependency, in which case our developers would install the debug profiles with `--build missing` and build them locally. 

We would like to separate the build_type for the consuming conanfile and dependencies. The proposal is to be able to do this:

```
$ conan install .. -s build_type=Release
$ conan build .. -s build_type=Debug # only applies to the consuming conanfile.
```

When `build_type` is not is set for `conan build` it should inherit whatever it was set to during `install` time (which is the current behavior). This enables the "on-demand debug deps" this way:

```
$ conan install .. -s build_type=Debug --build missing  # no binaries in remotes, build locally
$ conan build ..
```

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
@Sebiee I think it can't work because the install will generate the `conaninfo` for the requirements not for the consumer itself.

**Comment by Sebiee** [comment]
I tested my approach and it works. It is true that I find in the conaninfo.txt no record about `build_type=Release`, but the dependencies packages all have `build_type=Release`, while in the conaninfo.txt the settings contain `build_type=Debug`.

**Comment by memsharded** [comment]
I have considered to use ``wildcard`` per package settings, but not convinced. Here is an idea: https://github.com/memsharded/conan/tree/feature/wildcard_settings

It has several issues:
- It can be breaking, as ``-s MyPkg:mysetting=value`` will start unexpectedly matching and applying to package named ``MyPkgXXX``
- It will be slower to evaluate
- It is not very well defined what happens when more than one match happens.

I am delaying this issue until we have some better insight on how the dependencies information is stored after a ``conan install``

**Comment by memsharded** [comment]
Yes, the behavior described by @Sebiee works well, and I see no disadvantages to it.

I am adding it as a test in https://github.com/conan-io/conan/pull/4989, and proposing to close this issue with it. Thanks!
