### ISSUE TITLE
Read/Write conan.conf from conanfile.py

### ISSUE THREAD

**Issue by benlau** [conan-io/conan#2901]
Hello,

Is there any API that could read/write the content of conan.conf from conanfile.py? I would like to save a global configuration to that file and change the behaviour of conanfile.py according to the value. I only need to read/write a particular field. 

Thanks

**Comment by danimtb** [comment]
Hi @benlau,

All configuration variables in *conan.conf* are loaded as [environment variables](https://docs.conan.io/en/latest/reference/env_vars.html) when calling conan commands. To read them inside a *conanfile.py* you can use [tool.get_env()](https://docs.conan.io/en/latest/reference/tools.html#tools-get-env)

You can find an example of this in the conan-tbb recipe: https://github.com/conan-community/conan-tbb/blob/6063dcb244292463e96f2ded80f1035bb56376e9/conanfile.py#L36

Hope that helps to solve your issue! 😄

**Comment by danimtb** [comment]
If you are trying to use a custom variable in the *conan.conf* file it will not get loaded as an environment variable. *conan.conf* usage is intended to have only configuration for the conan client.

Why dont you use an enviaronment variable directly? or maybe you could use a variable declared in the [[env] section of a profile](https://docs.conan.io/en/latest/reference/profiles.html#examples).

Please elaborate a little bit more your use case and I will try to find a better solution :) Thanks!

**Comment by benlau** [comment]
I am building a Qt application and would like to use conan as a part of the automated deployment process. That may run on different kind of machines and OS.

It needs to define few configuration variables.

1. The path of qmake for selecting the Qt version
2.  The archive path, where to store the built-artifact.
3. The deployment key

They are all environment specific that should not be saved in the VCS. 

The previous version stores all the values into a file called "build.env",  use "source build.env" to obtain the values, then run the build script.

So now I would like to migrate to use conan's virtualenv generator. For example,

```
conan config set MyApp.deploymentKey 123456
conan install . 
source activate.sh # or run activate.bat on Windows
#run build script
```

I think that may use profile, but that is a bit troublesome as it must add "--profile" every time to run `conan install`. So I would like to find a one-time method. Thx

**Comment by danimtb** [comment]
So, if I understood you use case well:

You want to deploy a Qt application that needs 3 things to run:
- Path to qmake on the system.
- Path where to put the application ?
- A deployment key

If you know already the value of this 3 things before deploying (not decided by cosumers), you could set those variables in the `package_info()` environment variables. See [example](https://github.com/conan-community/conan-mingw-installer/blob/7e03ef870ed0b4dcc37f347af96ce501b22f240a/conanfile.py#L57). Note you can target here the different platforms and use different values for all the 3 variables.

You could then set the virtualenv generator and those variables will get loaded after coing activate. Then users could run the final app and it will found the needed variables.

Did I understand your use case well?

I trully believe storing donfigurations of your app in the conan.conf is not the way to go because this should be used to store only conan-related config and you would also have to "deploy" that config file to the users...

Another way to go would be packaging that *build.env* file or any other platform related file and deploy the right one.

You may find the [deploy()](https://docs.conan.io/en/latest/reference/conanfile/methods.html#deploy) method useful for your use case too.

Hope this all makes sense to you!
Thanks

**Comment by benlau** [comment]
Thanks for your reply. But those information can not be stored in the version control system .  So I couldn't use the `package_info()` solution. 

Moreover, In my use-case, it won't "deploy" the config file to users. I will let them set the value according to their machine. Because, we don't have a policy to enforce the development environment be exactly the same among developers. 

So probably I will think of another solution. 

Thanks!

**Comment by memsharded** [comment]
Hi @benlau 

The conan.conf is not intended for that use case, but for core configuration of the conan client.

What about creating a custom generator? If I understood it correctly, it might be what you want, have you checked them? Please have a look and tell me: https://docs.conan.io/en/latest/howtos/custom_generators.html#dyn-generators.

If not, then I probably misunderstood your use case, please ellaborate a bit further so I can try to help. Thanks!

**Comment by benlau** [comment]
Hi @memsharded ,

yes, probably I may write my own generator / plugin. My plan:

1. Read per-project configuration from $SRCDIR/config.ini
2. Let's virtualenv genreate activate.sh
3. Custom generator for another config files for compilation.
