### ISSUE TITLE
Another hash collision (GCC flags)

### ISSUE THREAD

**Issue by guyguy333** [conan-io/conan#2911]
Hello,

Initially, we got random errors like that when linking our project to another Conan package:
```
relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
```
The (ugliest) solution was to rebuilt the dependency, upload it again using Conan and cross the fingers.

I think we finally figured out why. Let's consider two Linux distributions : Debian 9 and Fedora 25. Both have the same Conan profile with GCC. Indeed, they're using the same version. It results in a similar hash for Conan package. So when upload is done, one overwrite the other one.

However, there is a difference between both compilers. One GCC is configured with  `--enable-default-pie` flag (Debian 9) while the other is not. We believe it is why we have this random error about `fPIC` that we shouldn't need to enable.

I guess Conan should produce different package hashes depending of some GCC flags.

Thanks,

- Conan version: 1.3.3
- OS: Various Linux distributions

**Comment by danimtb** [comment]
HI @guyguy333,

As Conan is decoupled from the build systems it is not aware of all the flags the compiler is using that could lead to ABI compatibility issues.

In the case of -fPIC flag there has been long discussions about it in #2476 and we are awre of providing a full-fledged fully-managed solution.

For now, the best way is to model this is as an option in your package `"fPIC": [True, False]` to get different package IDs. Since Conan 1.30 this option is managed automatically using CMake and AutoTools build helpers.

**Comment by guyguy333** [comment]
Thanks @danimtb 

> In the case of -fPIC flag there has been long discussions about it in #2476 and we are awre of providing a full-fledged fully-managed solution.

In fact, we don't need `-fPIC` in both cases if the right library (compiled on the same OS and so the same GCC) is used. The reported error is not really relevant.

> For now, the best way is to model this is as an option in your package "fPIC": [True, False] to get different package IDs. Since Conan 1.30 this option is managed automatically using CMake and AutoTools build helpers.

If I understand right, the idea is to have a flag `"fPIE"` option. However, to apply this flag, I need to know compiler flags (what Conan is not aware). It doesn't look so easy.

**Comment by danimtb** [comment]
Maybe you should compile always with `-no-pie` flag for gcc in both Debian and Fedora. Or use and fPIE option that is activated in Debian and deactivated in Fedrora, that way you would en with different package IDs.

Apparently that should solve the issue.

**Comment by memsharded** [comment]
As a quick recap of this issue:

- Different binaries are being produced in different distros, because of different default compiler flags. As the default conan model doesn't model these flags or distros, they end up with the same binary package-ID or hash, and overwrite each other.
- There are a couple of possible approaches:
   - Model the compiler flags that make the binaries different. To be used if you want binaries portable accross Linux distros. The way to go for this case could be to add an option to model PIE, and make sure this option is correctly applied in the ``build()`` methods to the builds of the packages, to match the inputs.
   - Model just the distro, as a setting (add it to *settings.yml* instead of to options in every recipe). This could be a subsetting of the ``Linux`` ``os`` setting, so it is automatically applied to all binary package-IDs. Package binaries won't be portable across distros, each distro will have its own binaries. The good part is that it will model any other minor difference than the distros may have, like different libc versions, or other different default compiler flags.

**Comment by danimtb** [comment]
Yes, sorry for closing without giving a proper conclusion.

I think the distro approach would be the easiest one to implement and manage and will avoid the package ID collision.

As this a common question, I have opened an issue in the docs to add it to the FAQ: conan-io/docs#1137
Thanks
