### ISSUE TITLE
Single Settings Filters throw with incorrect error message

### ISSUE THREAD

**Issue by Troy1010** [conan-io/conan#2918]
To reproduce the issue,
1- download an example conan package
`conan new Hello/0.1 -t`
2- replace the "settings" attribute in conanfile.py with this:
```
    settings = {
    "os":None,
    "compiler":None,
    "build_type":None,
    "arch":["x86"]
    }
```
3- install package
`conan install .`
You get this error:
```
ERROR: C:\Example Package\conanfile.py: Error while initializing settings. Invalid setting 'x86_64' is not a valid 'settings.arch' value.
Possible values are ['x86']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

Not only do I expect this code not throw an error, but the error is also incorrect.
The actual Possible Values - if I copy-paste from my settings.yml - are:
`arch: [x86, x86_64, ppc64le, ppc64, armv6, armv7, armv7hf, armv8, sparc, sparcv9, mips, mips64, avr, armv7s, armv7k]`
The error also indicates `'x86_64' is not a valid 'settings.arch' value.`
But x86 was given, not x86_64. Also, x86_64 -is- a valid settings.arch value.

Details..
Conan V: 1.3.3
OS: Windows
Compiler: VisualStudio2017
Python V: 3.6.5
pip V: 10.0.1

The library I am packaging is only buildable in x86.
One possible solution for me is to just do this:
```
    def configure(self):
        self.settings.arch = "x86"
```
but then the consumer might be annoyed when they explicitly use the x64 option and it is still building x86.

It is interesting to note that the following settings work just fine:
```
    settings = {
    "os":None,
    "compiler":None,
    "build_type":None,
    "arch":["x86","x86_64"]
    }
```
This leads me to believe this problem only appears for singular filters.

**Comment by memsharded** [comment]
I think the behavior is totally correct:

- You are constraining your recipe settings to accept only x86, not x86_64. (By the way, this is not necessary for most cases, please comment why would you want to do this).
- You are doing a ``conan install`` with your default settings which most likely are ``arch=x86_64``
- The recipe is throwing you an error, telling that it is not a valid value, as expected.

The actual possible values are NOT anymore ``arch: [x86, x86_64, ppc64le, ppc64, armv6, armv7, armv7hf, armv8, sparc, sparcv9, mips, mips64, avr, armv7s, armv7k]``, but only ``arch: [x86]`` as you defined it in the recipe. What you are defining in the recipe are constraints to the values, you cannot define there the values themselves. Values for settings come from command line or profiles. 

Please check and ask if you have further questions.

**Comment by memsharded** [comment]
Ok, good.
The fact that you will later link the library in a x86 application doesn't necessarily mean that you need to constraint the settings. Same even if you are using just one compiler and compiler version. Just create exactly 1 package binary with the settings you want and use it. If in the future you need for some reason to support new compilers or architectures, your recipe will be OK, no need to modify it to create binaries for them.

Constraining settings in recipes (which can be also done raising Exception in the ``configure()`` method, typically is more convenient), is only recommended for exceptional cases: for example if some C++ code will not compile in Windows MSVC at all, then it is fine to raise an Exception in ``configure()`` so users of this package will get a fast error instead of a later, more obscure error message while trying to build the libray with MSVC.

Are you ok with the answer then? Could this issue be closed? Thanks!

**Comment by Troy1010** [comment]
Yeah you can close the issue.
