### ISSUE TITLE
Think about a way to avoid unnecessary rebuilds due to changing package id's

### ISSUE THREAD

**Issue by tru** [conan-io/conan#2925]
Currently if you depend on something like `zlib/1.2.8` the cmake generator will insert a `-I` or `-system` path that looks something like: `/home/tobias/.conan/data/zlib/1.2.8/plex/stable/XXYYYZZ/include` into the build flags.

Any change to this package would change the path which will lead CMake/Ninja to rebuild all targets. If we could present a stable path to the package instead of one with the package id in it ninja could instead figure out what files depends on the changed headers instead of just rebuilding everything.

This could be done with symlinking into the build directory or something other cleaver that I can't think of for the moment.

**Comment by memsharded** [comment]
What do you mean with "a change in the path"? I think the path ``/home/tobias/.conan/data/zlib/1.2.8/plex/stable/XXYYYZZ/include`` will remain exactly the same when zlib is rebuilt, or are you talking about something different?

**Comment by tru** [comment]
consider our case - we add revision numbers in the conanfile right - so when we touch the conanfile script for zlib that would cause a total rebuild of the client app even if it's only 5 files that include zlib.h - I mean this is the reason for ninja to hash all the include files to detect when changes happen. but changing the cflags forces a rebuild of the whole app if we include zlib.

**Comment by lasote** [comment]
I don't know what are you suggesting, but if you change the recipe reference, of course, the path has to change. Probably the real issue is changing the version to model a revision. The latest approach we have in mind for revisions should avoid this problem because only 1 recipe (between all the revisions that a server could have stored) will live in the local cache, with the reference containing nothing about the revision number.

**Comment by memsharded** [comment]
The ``package_id`` computation has been fully re-vamped in Conan 2.0, so I think we can close this ticket, and open new ones if necessary, thanks!
