### ISSUE TITLE
GCC Link order 

### ISSUE THREAD

**Issue by lbakman** [conan-io/conan#3006]
Hi

Sorry about the weak problem description, but I have yet to find out what is really causing it. 

Tools: GCC, CMake, Linux (and MingW-64 on Windows), using conan BASIC and not TARGET.

When I moved from conan 1.3.3 to conan 1.4.2 (also tried with 1.4.0 and 1.4.3) my builds where unable to link. The ordering of the libraries to link has changed.

I have a project A that depends on B and C and where project B also depends on C. B and C are both static libraries where A is a shared library.

When linking A, I get an undefined reference from project B to project C. 

When looking at the generated link.txt file I can see that the order of the libraries in the file have changed from 1.3.3 to 1.4.x. In version 1.3.3 I had library C twice in the link.txt file, in version 1.4.x it is only listed once, and unfortunately not after library B.

I have tried to establish a small test project to see if I could recreate it in a way where you could see the problem, but I have not been able to so far.

Do you have any thoughts about changes in the link ordering determination that might help me locate my issue. And possibly provide you with a working example (or rather not working)

Regards
Lau

**Comment by memsharded** [comment]
Hi @lbakman 

There was a small change in 1.4, that changes the order of libraries from alphabetical to the order they are declared in the recipe, which is the correct behavior (alphabetical makes no sense). But this only applies when they are in the same dependency level, i.e, if A => C, B, it will make A link with C, B in that order. But only if C, B do not depend on each other. If they depend on each other, then that order will be respected, as before. In your case the link order should keep being the same A, B, C.

You might try to change the order in which your dependencies are declared, too, just an idea, in theory it shouldn't affect.

You can also try to send what you have, privately to info@conan.io, and we could investigate in your project. But of course a minimal reproducible example would be much better.

Thanks for reporting this!

**Comment by lbakman** [comment]
Hi @memsharded 

Thank you for your response. Changing the order of the dependencies in project A fixes the problem for me in this specific case. 

It would still be good to find out why the new ordering takes precedence over multiple dependencies, so I will try to create a minimal reproducible example today. Otherwise I will gather as much information as I can about the problem and send it privately. 

Regards

Lau

**Comment by lbakman** [comment]
Hi

Made some progress. I have created an example that works using conan 1.3.3 but does not work using conan 1.4.x. 

The undefined reference occurs for functions declared globally or in a namespace, not for classes. 

The example includes LibA, LibB and LibC. LibC has no dependencies, LibB depends on LibC and LibA depends on LibB and LibC. LibC declares and implements a function in the namespace LibC. LibB calls this function. When linking LibA (shared library and executable) the linker fails with an undefined reference til the function. If you change the order of the requirements in the conanfile.py for LibA, the problem is resolved. Notice that removing the "private" flag from the libc reference also resolves the problem. This is also the case if using the def requirements(self): method. If private=True the build also fails.

Regards Lau

[gcc_link_order.zip](https://github.com/conan-io/conan/files/2080350/gcc_link_order.zip)

**Comment by danimtb** [comment]
Hi @lbakman,

Thank you for the example.
I have just tested it in Windows with conan 1.3.0, 1.3.3 and 1.4.3 and it did not work for me. I got link errors in LibA.

Let's wait for @memsharded and see what he thinks

**Comment by lbakman** [comment]
Hi @danimtb 

Right, sorry. Did not check with Visual Studio. I can see that my "testsuite" does not link properly to the dll. Will try to fix that. But my original problem was with the GCC compiler.

I have used the following profile for windows (profiles/mingw64):
```
[settings]
os=Windows
arch=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
compiler.threads=win32
compiler.exception=seh
build_type=Release
os_build=Windows
arch_build=x86_64

[build_requires]
mingw_installer/1.0@conan/stable
```

Also I perform the following steps:

```
cd LibC
conan export . lba/testing
cd ..
cd LibB
conan export . lba/testing
cd ..
cd LibA
conan create . lba/testing --profile=mingw64 --build=missing
```

Regards Lau

**Comment by lbakman** [comment]
Hi

I have added the test project to github at the following URL: https://github.com/lbakman/conan_link_order

The example now builds using Visual Studio as well (on my machine I guess), but it does not fail as it does using GCC.

Regards Lau

**Comment by danimtb** [comment]
thank you so much for the feedback @lbakman.

FInally I was able to reproduce your issue with the mingw profile you provided. Seems this in fack a link problem the way you are definin your requirements.

In LibA I see:
```
    requires = (
        ("deps.libc/1.0@lba/testing", "private"),
        "deps.libb/1.0@lba/testing",
    )
```

As linkage order matters, you would need to link LibA with LibB first and then LibC. Changing the requierments order to this should solve your issue:

```
    requires = (
        "deps.libb/1.0@lba/testing",
        ("deps.libc/1.0@lba/testing", "private"),
    )
```

We have realized though that there is room for improvement here and will look into it a little bit more for next releases.

Thanks a lot for the feedback and for help with this issue!! 😄

**Comment by lbakman** [comment]
Hi

Sure, and that is how I have fixed it for my "real" projects. It just took some time to figure out why it changed all of a sudden.

Also, why does it work if you keep the original ordering and remove the "private" flag? 

And finally (From https://docs.conan.io/en/latest/changelog.html): "Conan 1.4 shouldn’t break any existing 1.0 recipe, or command line invocation. If it does, please report in github." :wink:

Regards Lau

**Comment by memsharded** [comment]
The PR #3014 has been merged, so this should be fix.

However, I have been thinking about this issue and the problem is that the dependencies are ill-formed.

Consider the case
- A=>(depends on)=>B=>C, and A=(privately)=>C
- B can depend on version C1, and the A can privately depend on version C2
- When A is going to be linked, C1 is transitively propagated, so A will link with LibB and LibC(v1)
- Also, A tries to link with the private C2.
- But A cannot link with two different versions, in two different paths of the same library.

In short: it is not possible to depend privately on a package that is already depended publicly, as a transitive dependency. It has to be private on both sides or public on both sides. 
As long as the private dependency version is the same as the transitive public version, then, there is no big issue. But by definition, private dependencies do not generate version conflicts, so it becomes a ill-formed configuration of dependencies.

Please have a look to your dependencies definition. I would like to learn and understand what you are trying to model with them, maybe there is a better way to model that, or there is something that would be a new feature. If you prefer to discuss in slack, please join our CppLang slack #conan channel.

**Comment by lbakman** [comment]
Thank you very much for your feedback. It got me thinking about why I did it the way I did. 

If I remember correctly, it is related to my "deploy" method. The current solution is something that I have ended up with through experimentation over time since conan 0.3, so my recipes have evolved over time as our usage have expanded. If there are more correct ways to do it, I will of course be happy to change my recipes.

My idea of the "private" property is that it is a dependency of the project, but it is not visible to anyone using that project. So in my example, because I have a dependency on LibC that is linked statically and its usage is contained entirely within LibA, I mark it "private". So if (or when) i use copy_deps() from "deploy", it is never copied. In our actual project we have (1) dependencies that we link statically and are contained entirely within our "LibA", (2) dependencies that we link statically, but where certain classes may be exported through "LibA" and (3) dependencies which are dynamically linked and should be deployed with "LibA".

1: These are the dependencies I have marked as "private".
2: These dependencies are not marked as "private".
3: These dependencies are not marked as "private".

In the example: In LibB, the dependency on LibC is not marked as "private" because anyone depending on LibB needs to know that LibB depends on LibC at link time. The fact that LibA also depends directly on LibC may be coincidental - in our specific case LibA had a dependency on LibC first, and later on LibB was modified and the dependency on LibC was added.

Come to think of it, perhaps dependencies (1) should just be in build_requirements instead of requirements and the result would be the same? 

Regards Lau

**Comment by memsharded** [comment]
Hi Lau!

> My idea of the "private" property is that it is a dependency of the project, but it is not visible to anyone using that project. So in my example, because I have a dependency on LibC that is linked statically and its usage is contained entirely within LibA, I mark it "private"

Yes, this is true. However, I'd suggest trying to avoid private dependencies unless they are totally necessary (like having to deal with different versions of the same library)

> So if (or when) i use copy_deps() from "deploy", it is never copied. 

That won't be a problem, if you are statically linking, the ``deploy()`` method will typically deploy only the dlls and so shared libraries, and static libraries are not copied


Even if all of the above could make sense, defining that dependency "private", if you are already depending on it publicly, is where the problem lies. The public transitive dependency will already be propagated to consumers, will be deployed by the ``deploy()``, etc. So in the best case, if the versions match, everything will work, but if the versions of the private and public doesn't match, then the result is undefined.

Yes, you could also use build_requires, but build_requires, for example, do not affect the binary ID. You can arbitrarily use any build_require version, and the resulting ID won't change. This is typically not expected when linking libraries, specially when linking static libraries into shared libraries, which in fact, you probably want to go to ``full_mode`` in your ``package_id()`` (depending how you are versioning your packages).

My suggestion would be to use normal ``requires`` as much as possible. They avoid later problems that are difficult to debug (like private versions mistmatches). Even for statically linked libraries into shared ones, it is difficult to guarantee that some information is not leaking transitively via the public headers, or via the API in form of some object in memory. And operations like ``deploy()`` can easily filter and get the artifacts you want from the dependencies you want, for final deployments.

Please let me know what you think. Thanks!

**Comment by lbakman** [comment]
Hi @memsharded 

That sounds very reasonable. I will go through my recipes and check up on my dependencies and see if the "private" properties are in fact just "leftovers" from some of my experiments. I am sure I can find a good solution without using "private"

Thank you very much for your time!

Regards Lau

**Comment by memsharded** [comment]
Great! You are welcome, glad to be of some help.
Please let us know how it goes and if you have any further question or issue. Cheers!
