### ISSUE TITLE
Dynamically linking to shared libraries for unit testing

### ISSUE THREAD

**Issue by stefan-pdx** [conan-io/conan#3018]
Hi,

I'm using Conan 1.4.3 to develop a package on Windows using the Visual Studio generator to link to upstream Conan dependencies. As part of my Visual Studio solution, I'm wanting to run unit tests (outside of Conan's build in `test` command) that dynamically links to a .dll for a specific package (located in its .bin directory). I'm a tad confused as to how to either copy the .dll to an appropriate location or update my PATH. Note: running `conan install .` or `conan imports .` apparently doesn't copy the .dll to the local directory.

In the docs relating to [how to manage shared libraries](https://docs.conan.io/en/latest/howtos/manage_shared_libraries/env_vars.html#using-shared-libraries-from-dependencies), I see:

> If you are executing something that depends on shared libraries belonging to your dependencies, such shared libraries have to be found at runtime. In Windows, it is enough if the package added its binary folder to the system `PATH`.

+ How does the package add its binary folder to the system path?

However, in the [using packages](https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#imports) docs:

> It is possible to add the folders of the libraries to the path (dynamic linker LD_LIBRARY_PATH path in Linux, DYLD_LIBRARY_PATH in OSX, or system PATH in Windows), or copy those shared libraries to some system folder, so they are found by the OS. But those are typical operations of deploys or final installation of apps, not desired while developing, and conan is intended for developers, so it tries not to mess with the OS.

+ How do I copy shared libraries from dependencies when working out of a Conan package folder? Running `conan install .` or `conan imports .` doesn't copy appear to copy the target .dll into the project's `bin` folder.

Do you have any recommendations on how to collect .dlls from upstream dependencies into the development environment (user space)?

Thanks! 👋

**Comment by memsharded** [comment]
Hi @slnovak !!

Quick question, because I am a bit confused. Do you mean the ``conan test`` command? But typically it is not possible to run **unit** tests with that, because the package only exposes the public API, and unit tests most of the times also needs visibility over internal components. Am I missing something?

**Comment by slnovak** [comment]
Hi @memsharded,

So, I made a bit of progress understanding the problem. I understand that package tests (i.e., `conan test`) should not be used for unit tests. I'm trying to figure out how to use the Conan-generated VS property sheet to append the `ConanBinaryDirectories` property to `PATH` when the Google Test project (in Visual Studio) I have containing unit tests is run. I opened up an issue with the VS/GT integration (csoltenborn/GoogleTestAdapter#175) to see if their "PATH extension" option can read variables from the Conan-generate property sheet, but apparently that's not supported at the moment.

So, the TL;DR is that it's up to the developer/test framework to configure itself to extend `PATH` to include Conan package binaries.

Do you think it's feasible to add support to Conan which will export an environmental variable containing the binary paths for a Conan project/profile? (Think of how tools like `rbenv` and `pyenv` allow you to switch across different Ruby/Python version.) Windows has a `setx.exe` that you can use to persist user environmental variables (that are accessible via other programs). Granted you can only configure this environmental variable once across the system at any given time, it would make it a lot easier to bind that environmental variable to `PATH`. The VS/GT integration will be supporting environmental variables in the upcoming release, so that would allow for better support between Conan and VS/GT.

I'm not all that familiar with what the appropriate workflow would be for Linux/MacOS -- I think that this can already be handled via CMake-based workflows.

Let me know what your thoughts are!

**Comment by lasote** [comment]
@slnovak maybe the `virtualrunenv` https://docs.conan.io/en/latest/reference/generators/virtualrunenv.html could help you?

**Comment by slnovak** [comment]
Thanks, @lasote. I think that could potentially work. However in my current flow I open up Visual Studio outside of the command line environment, hence having to use `setx.exe` to set user environmental variables (outside of the command line environment.) It's good to know that's an option though!

**Comment by memsharded** [comment]
A lot of things have changed since then, with new generators like ``VirtualRunEnv``, new toolchain management, etc.  I am closing this ticket as outdated, please open new ones if necessary, thanks!
