### ISSUE TITLE
conan.exe detected as Virus Artemis!B7A9D1872A48 

### ISSUE THREAD

**Issue by stefanklug** [conan-io/conan#305]
Hi,

our corporate virus scanner (McAfee) thinks conan.exe is a Virus named Artemis!B7A9D1872A48 
I downloaded the current installer from conan.io
I hope this is a false positive but nevertheless wanted you to know that.

Installing conan with pip doesn't Trigger this behavior.

Best regards
Stefan

**Comment by memsharded** [comment]
Hi Stefan!
Thanks for reporting. Yes, it is very weird. Virustotal doesn't report problems on the conan installer: https://www.virustotal.com/en/file/7199a5b325c31fc137e378cab3b5b903d7935ec33903a6daf1acf8582aee4ae2/analysis/

But then, some generic trojans are reported: https://www.virustotal.com/en/file/92f60382fe74ad0c967d66f6352056fd7ada71dc19bca4b616110e5f693f94bd/analysis/1465203416/

We have checked it several times, and seems the conan.exe is fine. All reports are "generic trojans", I think that as conan actually downloads/uploads, write to disk, remove from disk... it is too much suspicious activity for some AV. I think the only thing to do on our side is to report the AV vendors, so they whitelist the app or something, but so far my findings is that this can be slow and many times unsuccessful :(

So, yes, I recommend the pip version, not only because of that, but having a python installation and running there, especially in a virtualenv (virtualenvwrapper-win), is really useful for a programmer, at least IMHO). 

I am closing the issue, as this is almost nothing we can do on our side (I will submit to vendors, but doesn't make sense to have an issue open here for months), but please reopen if you feel something else can be done. Thanks a lot for reporting!
