### ISSUE TITLE
CMake helper does not add architecture flags to CMAKE_ASM_FLAGS

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#3083]
Hey,

I'm trying to package CPython using [python-cmake-buildsystem](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem).

My progress can be found on https://github.com/madebr/conan-cpython/tree/alpha

Python contains assembly files which should also be assembled in the correct architecture.
Therefore, `CMAKE_ASM_FLAGS` must be set.

Currently, only `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` are set to the architecture flags (when passing `set_cmake_flags=True` to the constructor of `CMake`.
https://github.com/conan-io/conan/blob/120e64ba2d7a182c7274016bc3dee82bf6e0409c/conans/client/build/cmake.py#L301-L308

I propose to also set `CMAKE_ASM_FLAGS` to the `arch_flag`.
Likewise for the `CONAN_ASM_FLAGS`, if that one is used)

**Comment by memsharded** [comment]
I have tried to look for that var in the CMake docs, and found nothing. In other online resources there are some comments. But it is difficult to know the full meaning and usage of this variable, so I would prefer to have a better understanding before modifying the helper. Do you have some relevant link, please?

In the meantime, the easy workaround would be something like:

```python
def build(self):
    cmake = CMake(self)
    cmake.definitions["CMAKE_ASM_FLAGS"] = cmake.definitions["CONAN_CXX_FLAGS"]
```
Would that work at the moment? Thanks!

**Comment by madebr** [comment]
That's the workaround I am using atm, which is working.
I think the var is this one: https://cmake.org/cmake/help/git-master/variable/CMAKE_LANG_FLAGS.html

The cmake build system uses C and ASM: https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/c3b8d532242efed85fb3cd77b0e39e424b6db475/CMakeLists.txt#L26

**Comment by lasote** [comment]
I would like to find a better fix than just set `CMAKE_ASM_FLAGS` blindly. If the variable is `CMAKE_<LANG>_FLAGS`,  the flags could potentially not be the same flags that you are setting in the `self.cpp_info` in the dependencies. But I'm not proposing to create a `self.asm_info`, at least until it becomes a general use case.
 
I think the proposed workaround is enough, better than just always set the cxx_flags to asm_flags.

**Comment by helmesjo** [comment]
Having a similar issue, I stumbled upon `set_cmake_flags`, setting it to `True` instead of the default `False` (`cmake = CMake(self, set_cmake_flags=True)`). Thus I could avoid the rather ugly `        cmake.definitions['CMAKE_CXX_FLAGS']=cmake.definitions['CONAN_CXX_FLAGS']`.

When would I _not_ want that flag to be `True`? Don't I always (or close to) want conan, given the settings I pass, to control how cmake compiles all it's targets?

Here I've been specifying `arch=x86` but cmake has continued to compile as x86_64 non the less...

**Comment by SSE4** [comment]
this is an interesting feature request, however, I have doubts about it.
there are plenty of popular assemblers used (GAS, NASM, YASM, MASM, etc.), and in general assembler in use is independent to the compiler in use. also, each assembler has its own flags I believe, and in general they are not fully compatible. currently conan doesn't know which assembler is in use, so it might be hard to set up assembler flags properly without introducing additional settings.

**Comment by SSE4** [comment]
@helmesjo your problem seems to be different from assembler flags.
the issue with CONAN_CXX_FLAGS vs CMAKE_CXX_FLAGS is tricky - CMake has to know some flags prior to the project generation in order to set certain variables correctly. see this issue for the detailed information:  https://github.com/conan-io/conan/issues/2384

**Comment by memsharded** [comment]
Closing as outdated, this ticket refers to legacy CMake integration
