### ISSUE TITLE
Short names and Qt Creator

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#3093]
Qt Creator understands Qt versions and expects to have direct visibility to the Qt libraries. I am using Bincrafters Qt packages (about 10 of them).  As Conan installs these libs it goes into "short name" mode, which is a bit of slight of hand.

As I understand it.... under: .conan\data\Qt\5.9.6\bincrafters\stable\package\10a9d7a3ddf8e2b6deaf463bf9993491ef2e48c3 you find a .conan_link file, not the library you downloaded. The contents of the .conan_link file is the "real" location of the lib. In this case D:/.conan\pkb1ara8\1.  Going to D:/.conan\pkb1ara8\1 and yes, there is the library and a conaninfo.txt file, which provides the build info but NO reference to the project data (i.e. Qt, 5.9.6)

Now can I get to where I want to be yes, just walk the .conan tree writing down the short links, go to the short links open the conaninfo.txt get the build data (compiler, and build) write that down. And repeat the process 10 times. 

Since many IDEs are likely to run into a similar process it would seem reasonable to have a convenience function to make this easier.  

May I request either:
1) include project name/version in the conaninfo.txt so I can just look in the short names
2) provide a conan utility to show the mapping. Possibly an update to "conan search  project --table=file.html"  so that it show the short path.

**Comment by memsharded** [comment]
Hi @ShamanTcler 

Yes, the short_paths features is a bit of inconvenience, but so far the only way to deal with the Win path limits. The current problem is that it is very decoupled from the conan logic, so it is mostly transparent. That makes point 2 relatively difficult.

Byt point 1 is definitely in our roadmap. We are now trying to model which added information conan needs to capture in the binaries, and it will certainly include things like the name/version.

This may take a while. In the meantime, I would like to try to find some workaround, and understanding the use case might help. I think it is not necessary to do such a manual mapping, because IDEs will already have the path to the shorten version. E.g. if you are using the cmake generator, you will get things like:

```cmake
set(CONAN_INCLUDE_DIRS_MYLIB D:/.conan/xxxx/1/include)
```

**Comment by ShamanTcler** [comment]
So what about a little utility that maps it out. This is a little ditty I banged out .... please ignore code quality, but it works.


[resolveShortLinks.txt](https://github.com/conan-io/conan/files/2127315/resolveShortLinks.txt)


Yielding:
Data> resolveShortLinks.sh
Processing ./Qt/5.11.0/bincrafters/stable/export_source/.conan_link
Qt
     5.11.0
______________________
Processing ./Qt/5.11.0/bincrafters/stable/package/10a9d7a3ddf8e2b6deaf463bf9993491ef2e48c3/.conan_link
Qt
     5.11.0
         D:/.conan/21996hht/1/conaninfo.txt     compiler=Visual Studio     compiler.version=15     build_type=Release
______________________
Processing ./Qt/5.11.0/bincrafters/stable/package/dec6aed42d1959fd3cfb66d107cdd2ca54bcdef7/.conan_link
Qt
     5.11.0
         D:/.conan/3kq3_n52/1/conaninfo.txt     compiler=Visual Studio     compiler.version=15     build_type=Debug
______________________
Processing ./Qt/5.6.3/bincrafters/stable/export_source/.conan_link
Qt
     5.6.3
______________________
