### ISSUE TITLE
[SCM] Support svn

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#3130]
We currently use Subversion and want to make use of the source() method for retrieving the _exact_ source for the package i.e. we don’t want to use exports_sources due to it only being a snapshot and we can’t use the scm attribute. We also want our source co-located with the recipe. Therefore we would like something similar to the following in our repo:

- conanfile.py
- include
    - foo.h
- lib
    - foo.cpp

Within the recipe we would have something like:

NOTE: pseudo code
```
def source(self):
    svn co url-to-check-out .

def build(self)
    # make sure we have the latest source
    svn update

    # now build
    cmake = CMake(self)
    …
```
Question 1: This appears to be against recommended practice, i.e. exports_sources appears to be recommended for co-located source and recipe. So, is this a bad idea? If so, why?

Question 2: For active development, we think we will need to do ‘svn update’ within the build() method due to the caching of source. Is this a bad idea? We actually agree with @liberforce and the issue described within #3084, in that it appears strange there is no way to override the caching of source as during active development the source will change often (tracking HEAD) but the recipe will not.

**Comment by lasote** [comment]
> Question 1: This appears to be against recommended practice, i.e. exports_sources appears to be recommended for co-located source and recipe. So, is this a bad idea? If so, why?

Well, if it works for you, it is ok, but probably it doesn't. You need to check out a specific revision, but if you change the revision in the recipe (source method) you would need to "commit" again, so you will be changing again the revision (chicken-egg issue).

> Question 2: 

Probably It is a bad idea to specify it in the `build()` method. I agree during development is the behavior you want, but otherwise, it is not recommended just to check out the latest code because you would be losing the reproducibility of your build.

In general, the answer to both questions is `you need scm for svn`. it would solve both the chicken-egg mentioned issue and also during development, the sources are fetched (fresh every time) during development, because are copied from your local repository folder, without the need of committing changes.

**Comment by keithrob91** [comment]
While trying to understand how we would want to use Conan I asked a previous question #3042 where scm for svn was discussed. That question and your response to this question means (I think) we definitely want this feature as exports_sources is not acceptable and we can't (yet) move to git.

Thank you for the response.
