### ISSUE TITLE
cmake_find_package generates invalid *_FOUND varable names

### ISSUE THREAD

**Issue by Ri0n** [conan-io/conan#3148]
I have just one example. It's OpenSSL

Generated OpenSSL find module has
```
SET(OpenSSL_FOUND 1)
```

After this, code like
```
if(OPENSSL_FOUND)
```
doesn't work.

If I change it to
```
if(OpenSSL_FOUND)
```
it starts working.

So the comparisons are case sensitive and the fully uppercase variant is correct. Official OpenSSL find module also has `if(OPENSSL_FOUND)`

**Comment by Ri0n** [comment]
I've added `replace_in_file("FindOpenSSL.cmake", "OpenSSL_", "OPENSSL_")` as a workaround

**Comment by Ri0n** [comment]
Oh that was far from enough.. No idea what to do with openssl

**Comment by lasote** [comment]
Hi @Ri0n !

I think I need more information about what are you trying to do. Are you using the `cmake_find_package` generator, right?  I think the issue is you are trying to use it like the "official" OpenSSL find package script. The `cmake_find_package` do not pretend to replace any official module, so the variables won't be the same and the usage has to be changed.

**Comment by lasote** [comment]
If you want to use the official you can rely on the `cmake_paths` generator. It will indicate CMake where to find your libraries using the official one.

**Comment by SSE4** [comment]
CMake's find_package always drives me crazy. it's case-sensitive, and actually package name is case sensitive, as well as variable names are case-sensitive too. so, module is called **FindOpenSSL.cmake**, while variable are named like **OPENSSL_FOUND**.
meanwhile, if we take a look at an another package, e.g. boost, then package name is **FindBoost.cmake**, while variables are named like **Boost_FOUND**.
there is no logic, and it makes impossible to implement automation of generation of FindXXX.cmake modules properly (each module will require its own quirks, unfortunately).
question to vcpkg users - how does it work for vcpkg? how do they solve this problem?

**Comment by eliasdaler** [comment]
Agreed. It's now too simple to be really useful. I think that generator should support the following fields to be changed manually by user before generating FindX.cmake:

* library name - e.g. OpenSSL. Right now we have custom "openssl" Conan package which generates Findopenssl.cmake instead of FindOpenSSL.cmake.

* library name in variables - in the OpenSSL case we need to set it to "OPENSSL", in Boost case it'll be "Boost", etc. Generator should then set "OPENSSL_FOUND" and "Boost_FOUND". The default should be the library name in uppercase which seems to me most default Find* modules prefer.

**Comment by lasote** [comment]
It requires a parameter mechanism for the generators, but I agree for this generator is very very useful.

**Comment by eliasdaler** [comment]
Does it require big API changes? If this is a feature tha will be added on top of existing API, then maybe I may help implement this somehow? :)

**Comment by lasote** [comment]
It will require some deep analysis, I wouldn't recommend you to implement this one, but many thanks.

**Comment by memsharded** [comment]
``cmake_find_package`` superseded by ``CMakeDeps`` and ``CMakeToolchain`` integrations
