### ISSUE TITLE
[build system] [cmake] Passing a preprocessor definition from conanfile. Consumer recipe

### ISSUE THREAD

**Issue by chreniuc** [conan-io/conan#3167]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Short version:
I want to pass from the conanfile(consumer recipe, building an executable) a preprocessor definition which will be used in the building of the current project(will be used in `build()` method), just like `cpp_info.defines` does in the `package_info` method. 

Long version:
Let's say I have a library **libA** that has those options : 
```python
"build_time": [True, False],
"build_file": [True, False],
"build_settings": [True, False],
"build_log": [True, False],
"build_email": [True, False]
```
In the test package(or any consumer recipe that is building an executable) i want to test the package based on those options:
```c++
// main.cpp
.....
#ifdef build_time
 do_this_time();
#endif

#ifdef build_log
 do_this_log();
#endif
...
```
Those are not unit tests, they are some calls that demonstrate that the library is working correctly. How can i pass those preprocessor definitions from the conanfile of the consumer recipe? 

I don't want to pass them from the recipe of **libA**(using **self.cpp_info.defines**) or using `cmake.defines["CMAKE_CXX_FLAGS"]="build_time"` in the consumer recipe, or even `cmake.defines["build_time""]="build_time"` in the consumer recipe and then in `CMakeLists.txt` : `if(DEFINED build_time) add_definition(build_time) endif()`.

I am wondering if there is way to pass them as we do it with `self.cpp_info.defines` in the `package_info` method, but in the `build()` method.

If there isn't, would it be helpful to have it? Or it doesn't make any sense to have this feature.

I'm thinking of something like this:

```python
def build():
    ...
    cmake.cpp_defines.append("build_log");
    cmake.configure()
    cmake.build()
....
```

**Comment by memsharded** [comment]
No, it is not possible. If you check from the docs (https://docs.conan.io/en/latest/reference/commands/consumer/install.html) the evaluation order of the recipes is:

```
build()
package()
package_info()
```

The ``package_info()`` method is the information provided to the consumers of the package. It is not called until the package is build, because actually it could use some information that is generated at build time. So it is not something that could be implemented, it is impossible by definition.

I am missing some motivation, why do you want to put ``cmake.cpp_defines.append("build_log")`` in ``package_info()`` vs putting ``cmake.definitions["..."]=...`` in the ``build()`` method? What does it really matters for your use case? As a general rule, conan is not a build systems, and does not call directly the compilers, everything is done via the build systems, so conan cannot provide preprocessor directives to the compilers if not via the build system.

Please tell a bit more about your use case. Thanks!

**Comment by chreniuc** [comment]
You misunderstood me. I don't want `cmake.cpp_defines.append("build_log")` in package_info(), I want it in method `build()`. I was just giving an example of how something already exists in the  `package_info` method. This is a consumer recipe, it has only the `build()` method. A test package.

```python
class test_package_libA(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"

    def build(self):
        cmake = CMake(self)
        cmake.parallel = True
        cmake.verbose = True
        if self.options["libA"].build_log == True:
            cmake.cpp_defines.append("build_log")
        cmake.configure()
        cmake.build()
   
 def test(self):
        if not tools.cross_building(self.settings):
            os.chdir("bin")
            self.run(".%stest_package" % os.sep)
``` 

Or another case where it isn't a test package, only a consumer app:
```python
class test_package_libA(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    requires = ("libA/1.0.0@user/stable")

    def build(self):
        cmake = CMake(self)
        cmake.parallel = True
        cmake.verbose = True
        if self.options["libA"].build_log == True:
            cmake.cpp_defines.append("build_log")
        cmake.configure()
        cmake.build()
```

**Comment by memsharded** [comment]
Thanks for clarifying. So if I understood correctly the problem with:

```python
class test_package_libA(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    requires = ("libA/1.0.0@user/stable")

    def build(self):
        cmake = CMake(self)
        cmake.parallel = True
        cmake.verbose = True
        cmake.definitions["BUILD_LOG"] = self.options["libA"].build_log
        cmake.configure()
        cmake.build()
```
Is that you need to add to your CMakeLists.txt the ``if(DEFINED build_time) add_definition(build_time) endif()``, and you would like not to have to do that.

Unfortunately, it is not possible to do this. Conan does not do any "magic" with the build system, it basically calls it, or wraps it execution. There is no  way (even without conan) that such definition can be "injected" in a CMake build, so it doesn't seem a feature that conan could implement.

**Comment by chreniuc** [comment]
@memsharded Thanks :)
I still wonder, if this can be done in the `package_info` method(this will be passed to the project that will be using this package), why couldn't be done in the build method for the current project?

Having this recipe:

```python
class libA_recipe_conan(ConanFile):
    name = "libA"
    version = "1.0.0"
    ....
    def package_info():
        self.cpp_info.defines = ["build_log", "build_time"]
```

And this consumer recipe:
```python
class consumer_package(ConanFile):
    name="executable"
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    requires = ("libA/1.0.0@user/stable")

    def build(self):
        cmake = CMake(self)
        cmake.parallel = True
        cmake.verbose = True
        cmake.configure()
        cmake.build()
```

`build_log` and `build_time` will be passed as preprocessor definitions(because they were defined in the `package_info` method in **libA**), when building this consumer recipe(`executable`).

Now what happens behind the scenes of this line `self.cpp_info.defines = ["build_log", "build_time"]` from the **libA** recipe? How  does conan pass those preprocessor definitions to the compiler and why we couldn't apply the same thing in the `build()` method for the current build?

I'm sorry that i keep insisting, but it seems to me that the line `self.cpp_info.defines = ["build_log", "build_time"]` in the `package_info()` does exactly what you said conan couldn't do :
>There is no way (even without conan) that such definition can be "injected" in a CMake build, so it doesn't seem a feature that conan could implement.

**Comment by memsharded** [comment]
Hi @chreniuc 

Now I understand what you mean. The separation of the generators/build-helpers is the reason for the current behavior: generators estrictly generated information about the dependencies, not the current package/consumer, and build-helpers (like ``CMake``) dealt only with the current package/consumer build system invocation, but not the dependencies. 

The build-helpers doesn't define (so far) any means to modify the build besides the strictly required invocation, translating conan settings (os, compiler) to the correspondent cmake command line arguments or flags (like ``-s arch=x86`` might translate to ``-m32``).

So conan doesn't provide a high level abstraction over the current build, besides that. And the information that comes in the generator files is from dependencies only. So right now, you should use some build-system modifications.

The good news, is that we are aware of this demand. Users are asking conan for such high-level abstraction over the build systems and we are going to provide it. There are still many unknowns, and it is still not a top priority, so it might take a while. 

Please stay tuned, I am renaming the title and labeling accordingly. Thanks for your feedback!

**Comment by mjschuster** [comment]
I recently stumbled upon the same issue ... are there any news on this?

Could preprocessor definitions maybe just be passed via the ```CMAKE_CXX_FLAGS```? 
(see https://stackoverflow.com/a/55564298 and https://stackoverflow.com/a/52179619)
As far as I can see, the CMAKE_CXX_FLAGS are already optionally used to pass architecture flags in https://github.com/conan-io/conan/blob/master/conans/client/build/cmake_flags.py#L320

Would it be an easy solution to have another cmake-build-helper function or parameter to pass additional CMAKE_CXX_FLAGS or, having a nicer interface, a dictionary of preprocessor macros that are converted to CMAKE_CXX_FLAGS? 

If that could work, maybe the issue doesn't need to be labelled / seen as "complex: high" and could easily be resolved? Or am I missing some potential problems here?

Thanks in advance for any help or comments here!

**Comment by egendron93** [comment]
> I recently stumbled upon the same issue ... are there any news on this?
> 
> Could preprocessor definitions maybe just be passed via the `CMAKE_CXX_FLAGS`?
> (see https://stackoverflow.com/a/55564298 and https://stackoverflow.com/a/52179619)
> As far as I can see, the CMAKE_CXX_FLAGS are already optionally used to pass architecture flags in https://github.com/conan-io/conan/blob/master/conans/client/build/cmake_flags.py#L320
> 
> Would it be an easy solution to have another cmake-build-helper function or parameter to pass additional CMAKE_CXX_FLAGS or, having a nicer interface, a dictionary of preprocessor macros that are converted to CMAKE_CXX_FLAGS?
> 
> If that could work, maybe the issue doesn't need to be labelled / seen as "complex: high" and could easily be resolved? Or am I missing some potential problems here?
> 
> Thanks in advance for any help or comments here!

I believe the issue with using CMAKE_CXX_FLAGS is the fact that it is a global environment variable and against the [modern cmake](https://youtu.be/ztrnb-bVVPo) best practices. I also think that it makes the conan developers job more difficult by providing a way for the user to inject anything into the build commands without affecting the package id.

I'm also struggling with a proper solution to this issue. Like @memsharded said there is no cmake provided interface to add compile definitions to a cmake target without adding to the cmakes source code itself.

The ABI implications of this problem seem to be overwhelming. I am wondering if there is a recommended way to handle this solution prior to Conan 2.0?

**Comment by memsharded** [comment]
> The ABI implications of this problem seem to be overwhelming. For example, if a recipe uses some preprocessor definitions that affect public facing code and then the consumer project uses that public facing code and compiles without the same preprocessor definitions undefined behavior may occur.

That is what the ``package_info()`` method is for, check https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-info. If a package needs its consumer to enable some preprocessor definition, they should be declared:

```python
def package_info(self):
     self.cpp_info.defines = ["MY_PREPROCESSOR_DEFINITION"]
```

As commented above, there is no magic in the build system that Conan could exploit, so the only way as today is:

- Define some option to the recipe, to allow pass configuration that change the build. It can be even generic, not validated input with "ANY"
- Options by definition affect the package-ID, so we are good. You can also process the granularity of binaries you want based on that option inputs (you can use the ``package_id()`` method for that) 
- Pass this option, or compute in the recipe the necessary flags, and pass them to the underlying build system
- Let the build system know and process those inputs.

Yes, some general flags mechanism can be used, like some kind of CMAKE_CXX_FLAGS, but that might be against best practices. In general, it seems to work better to model the variability of the binaries explicitly (either with settings or options). For example if you directly manage the optimization level, instead of trying to pass some CXX_FLAGS, you model ``optimization = [1, 2, 3, 4, 5]`` which depending on the scope could be in the settings (maybe a subsetting of compiler) or as an option. Then you let the recipes and/or the build helpers to translate that information to respective ``/OX`` flags or whatever they mean for the different compilers and systems.

**Comment by mjschuster** [comment]
Thank you for your answers. I'm not sure if we are talking about the same thing here. To clarify my comment:
I understand and agree that Conan settings or options would in most cases be the best way to pass flags *into* Conan and that they should be exported via package_info if required by consumer packages. 
My question, however, is on how to pass C++ preprocessor definitions *from* Conan into the CMake-based build without having to modify the `CMakeLists.txt`?

**Comment by memsharded** [comment]
> My question, however, is on how to pass C++ preprocessor definitions from Conan into the CMake-based build without having to modify the CMakeLists.txt?

That is the point, CMake doesn't have any magic mechanism that allows to do so. It is not intrisically a Conan thing, as pointed here https://stackoverflow.com/questions/8564337/how-to-define-a-c-preprocessor-macro-through-the-command-line-with-cmake the options are:
- Mess with the environment variables (system dependent, requires hacking and adaptation to every different system) to inject it
- Pass it as global CXX_FLAGS ``-D CMAKE_CXX_FLAGS=/DMY_MACRO=1`` (global to all CMakeLists.txt script, not "modern" cmake)
- Modify the CMakeLists.txt

I was summarizing, just in case, how different information can be brought to the ``build()`` method from the outside if necessary, but in the boundary with CMake, the above is what can be done.

**Comment by egendron93** [comment]
> That is what the `package_info()` method is for, check https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-info. If a package needs its consumer to enable some preprocessor definition, they should be declared:
> 
> ```python
> def package_info(self):
>      self.cpp_info.defines = ["MY_PREPROCESSOR_DEFINITION"]
> ```
> 
> As commented above, there is no magic in the build system that Conan could exploit, so the only way as today is:
> 
>     * Define some option to the recipe, to allow pass configuration that change the build. It can be even generic, not validated input with "ANY"
> 
>     * Options by definition affect the package-ID, so we are good. You can also process the granularity of binaries you want based on that option inputs (you can use the `package_id()` method for that)
> 
>     * Pass this option, or compute in the recipe the necessary flags, and pass them to the underlying build system
> 
>     * Let the build system know and process those inputs.

@memsharded A variation of this approach is what I had planned on using for the recipes that I manage. Hearing it come from you is more reassuring that I'm headed in the right direction.

One of the main issues I've run into is for package recipes that I do not manage. The boost recipe in the conan center provides a limited amount of options compared to all the actual preprocessor definitions available throughout the boost libraries. For example BOOST_BEAST_USE_STD_STRING_VIEW is not represented as a package option. The boost recipe provides an additional_b2_flags option that uses the not validated "ANY" input. This is where I set the beast string view definition. The definitions added to the additional_b2_flags option do not get added to the cpp_defines member, therefore will not be accessible to consuming projects.

I guess this is more of a recipe specific design issue and I should make an issue for the boost recipe. Is creating the issue the next move or am I missing something?

**Comment by Ahajha** [comment]
I'm guessing not much progress has been made on this front, but I wonder if a subset of this could be implemented for header-only libraries? They seem to be the most likely type of libraries to use this sort of preprocessor-based configuration, and it requires no messing with the build system, effectively it's just retroactively adding to the package info preprocessor defines.

**Comment by memsharded** [comment]
Hi all


Long time has passed since this thread was last active. Many things have changed in Conan, and now there is 2.0

One of the comments above is about a way to pass compiler flags or definitions, that now can happen via ``tools.build:cxx_flags`` and others similar ``conf`` items, that can be defined directly in the profiles, and also in ``tool_requires`` for their consumers. For definitions ``tools.build:defines`` should be able to inject such definitions into build systems directly from Conan profiles. This feature has been already in 1.X for several releases.

I think this is what this issue was about, isn't it?

**Comment by Ahajha** [comment]
For me personally (I won't speak for others, but from the title I think they want similar), I would prefer it to be on a conanfile basis, not a profile basis. Though perhaps that could be achieved by modifying `tools.build:defines` in the conanfile? Is that possible/advised?

**Comment by memsharded** [comment]
I see.

Then, I am afraid it is not possible, and also it won't happen.
The only thing that can be propagated from the consumers to the dependencies are ``options``. And that is already too complicated, confusing and sometimes fragile, even if it has a known well defined space (limited options values) that can be validated and checked. Propagating arbitrary things as compiler flags from consumers would be a source of many issues, imagine for examples, the problems when different recipes are defining different compiler flags for the same dependencies.

So, to summarize, the ways that compiler flags for a package can be defined are:

- A recipe itself fully controls its build. It can define CMake variables in ``CMakeToolchain`` for example, conditioned to its own options 
- Packages containing toolchains, and consumed via ``tool_requires``, can define compiler flags for their dependencies via ``self.conf_info.append("tools.build:cxxflags", [some, flags])``
- Defined directly from the profiles via the ``[conf]`` section with ``tools.build:cxxflags``. Also the same via command line with ``-c tools.build:cxxflags=...``
- Defined globally with ``tools.build:cxxflags``for all profiles in the ``global.conf`` file. Probably not a practical approach for this specific conf, as it is unlikely that same compile flags will be used absolutely for every build.

I am closing this ticket as resolved, but don't hesitate to comment or file new tickets if you have any other further question.

**Comment by Ahajha** [comment]
This is unfortunate, but reasonable. I suppose the proper way to do this would be to add each recognized flag as an option?

Perhaps there could be a utility for this, but that would be a separate issue.

**Comment by memsharded** [comment]
> I suppose the proper way to do this would be to add each recognized flag as an option?

Not really. The really recommended way is to use profiles for this. The separation of concerns is defined as:

- Recipes define the "what". Who depends on what, the relationships at a high level. There is complete abstraction over the dependencies details, you can consume dependencies without even knowing the build system they are using, or in most cases, without knowing if it is a shared or a static library. It is not the responsibility of a recipe to define if its dependencies are shared or static libraries in the general case, but to be able to build correctly for both cases (or to raise an Invalid error if it is not supported).
- Profiles define "how". A specific instance of the dependency graph. The current configuration, settings, if you want shared or static dependencies, the type of binaries you want, etc. Compiler flags belong here.

Compiler flags of a dependency should never be defined by a recipe. This is the equivalent as hardcoding compiler flags in a CMakeLists.txt instead of defining them in CMake toolchains (or presets, or command lines), which is the recommended practice.

So mapping all recognized flags to options to be able to define them from recipes is still not the best approach, and could easily lead to many problems in practice, this would be discouraged.

**Comment by Ahajha** [comment]
That seems a bit strange to me, I go about things a bit differently:

1. Recipes completely encapsulate the "what" and "how". If my library Foo requires that its dependency Bar have option Baz=True, that's Foo's responsibility, not Bar's. For optional things, either approach seems fine.
2. Profiles are for global settings, and in my team we only deal with one (the default, plus or minus personal tweaks).

The problem I have with profile-based configuration is that if I specify an option, I now have to tell my team to also add that option to their profiles. If I recall there's a way to upload a profile and then sync it with others, but that's just adding another step. Additionally, now I need multiple profiles for different, independent projects. In both cases, keeping those restrictions to the conanfiles keeps things self-contained.

I'm of course not saying "you're using it wrong", but for me it just seems like an extra step that gets in the way.

**Comment by memsharded** [comment]
Lets say that you have an executable in a Conan package, an application that depends on one library "openssl/3.1" in another Conan package.
There could be 2 approaches:

- You have 2 conanfiles and 1 profile:
   - Both conanfiles contains a ``requires = "openssl/3.1"``
   - One conanfile that defines ``self.options["openssl"].shared = True``. You call this package ``name= "app_dynamic"``, and it creates ``app_dynamic/1.0`` with 1 single binary with 1 ``package_id``
   - Other conanfile that defines ``self.options["openss"].shared = False``. You call this package ``name = "app_static"`` and it creates ``app_static/1.0`` with 1 single binary with 1 ``package_id``
   - One profile that does not define anything regarding openssl
- You have 1 conanfile and 2 profiles:
   - One conanfile with a ``require = "openssl/3.1"``, but nothing to set the dependency options
   - One profile called "dynamic" that defines ``*:shared=True``
   - One profile called "shared" that defines ``*:shared=False``
   - When the app package is created it creates ``app/1.0`` with 2 different ``package_id``, one for the statically linked executable and the other for the dynamically linked executable.

The first approach is incorrect, while the second approach is the correct one.
It doesn't matter that initially you only support 1 of the cases, either the static or the shared one. The approach should be identical for 1 or N configurations. It also doesn't matter if you are not creating a package from the consumer application or not, it should be consistent in both cases (and be future proof, when you realize that you want that executable also inside a Conan package, because it helps with traceability, testing and reusing in other places, etc, this is super typical too)

Exactly the same rationale applies for things like compiler flags, and any other **configuration** items. In exactly the same way you don't want to embed magic constants in your C++ application code, so don't do this:
```c++
int main(){
      int server_port = 8000;
      launch_htpp_server(server_port);
```
Even if you only have 1 application and it runs in port 8000, this is not good practice for SW engineering, and the ``server_port`` is a configuration item that should be defined in an external configuration file, and loaded by the executable when it runs.

> The problem I have with profile-based configuration is that if I specify an option, I now have to tell my team to also add that option to their profiles.

You should be automatically having the same profiles files, sharing and synchronizing them with the team with ``conan config install``. The team should not be editing their own profiles locally. Also the CI machines should use as well the same profiles. 

It is very unusual to have just 1 profile. Every different compiler version, building for Debug or Release, even Linux or Windows means different profiles. Are you building only 1 platform Windows or Linux? Only 1 compiler, with only 1 compiler version (with no intention to upgrade compiler at any time)? You really won't update to a newer compiler version ever? Only 1 build type, like only building for Release but not Debug?


> I'm of course not saying "you're using it wrong", but for me it just seems like an extra step that gets in the way.

Well, I am Conan co-founder and project leader, it would be very difficult that "I am using it wrong" 😄 
I am trying to explain the design of the tool, how it is intended to be used, known pitfalls and problems of the approach you are trying to follow and why they are not supported (and why they won't be supported) that way.

**Comment by Ahajha** [comment]
I think we might be describing two slightly different usages - I'm interested in the case where it's not an arbitrary choice, but rather a strict requirement. For example, suppose there's an optional feature in a library that we need to enable. For yours, it's an open-ended configuration option. The way I would approach that is sort of similar (maybe even technically identical), that being having an option in my application, and then setting it on the CLI `-o my_app:port=8000`, I think you would suggest the same except put it in a profile.

I'll refrain from digging myself further into a hole on the topic, and yes, I'm aware you're one of the co-founders, just consider me a user that's 'doing it wrong' 😄 

Also to answer your question regarding profiles: It's more of one profile per machine, and we just set the options as we need them. So on a Linux machine we might use the default profile, which has, say, GCC 12. If we want to use debug mode, we add `-s:h build_type=Debug` to the CLI. I could see how this would be easier with profiles. We support Windows, Linux, and (somewhat) MacOS, but to be fair we're still working on building up more robust CI infrastructure (multiple compilers per OS, etc), so it's something we're still working on.

To give a concrete example of something I would be interested in, in Vulkan-Hpp (part of the vulkan-headers package), there's a preprocessor config option `VULKAN_HPP_NO_CONSTRUCTORS`, and I have a small (single file) personal project that requires it to be enabled (it uses C++20 designated initializers). For now, I just have the macro defined in the single source file, I would just want to know how to make sure if I have multiple sources, that it's defined the same everywhere (either defined or not).

So based on my understanding, I think there are a few ways I could go about this:
1. Add an option `no_constructors` to vulkan-headers, set to true in the conanfile (bad?)
2. Add an option `no_constructors` to vulkan-headers, set to true in the profile (good?)
3. Add the define `VULKAN_HPP_NO_CONSTRUCTORS` directly in my profile (good?)
