### ISSUE TITLE
Build helper specification

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#3189]
Reposting what I wrote in Slack earlier with @memsharded:

Yesterday I tried to make bincrafters' boost work with `darwin-toolchain` (with no luck, again...).
And one of the reasons it failed was that the `boost_generator` recipe splits the `CFLAGS` env variable on whitespaces.

The flag responsible for this is `-arch x86_64`, which would work fine if it was `-arch=x86_64`, but Apple decided to put a whitespace here.
The problem is that, except by checking specifically for that flag, there is no way to give something correct to Boost.Build.

So instead of trying to workaround it, I remembered that the only reason why I needed to set the environment variable `CFLAGS` was because the CMake build helper does not read flags from `deps_cpp_info`.

After looking at the code of every build helper, it seems that only `autotools_environment.py` and `visual_environment.py` read from `deps_cpp_info`.

At first I thought that CMake was the only one concerned, so writing a custom CMake Toolchain file would have solved the problem.
However since most build helpers are in the same case I was wondering what could be done to solve it for everyone.

At SwampUp, I did mumble a bit about a "Build Helper Specification", which would specify things like:

* Where to take flags from.
* Where to take the sysroot from.
* (I don't have much more to be honest :P)

If it could use the same source than consumer packages (i.e. `deps_cpp_info`).

I have no idea if such a change would break recipes, I hope not!

I'm using Conan 1.5.2.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
We are aware of this issue, there are some other related issues at https://github.com/conan-io/conan/issues/2956 for example.

We don't want to introduce dependency information in the build helpers when not needed, we still think that the "generator" files should contain information about the dependencies and the "build helper" should manage the information about the current build. But we are aware we are doing it in some cases like you mentioned, in the case of AutoTools we didn't find a way to "include a generated file" into a configure/make script, so we used directly the build helper for that.

The `deps_cpp_info` information should be applied by including the generated file. I can't recall why you needed to set the `CFLAGS` in the toolchain recipe, I remember we were talking about it and I told you "you are right, you need to declare CFLAGS". Please, help me to remember.

On the other hand, we are aware that the reproducibility of a build without calling "conan build" or "conan create" is not possible because the build helper is injecting dynamically flags to the build system, so now we tend to think that maybe another file should be generated instead of injecting information dynamically. But it is just an idea and it is very very challenging. Probably for Conan 2.0.

**Comment by theodelrieu** [comment]
>The `deps_cpp_info` information should be applied by including the generated file.

To build the end-consumer project, I agree. However my use-case is applying a set of common flags to other packages, and IIRC there is no generated file (e.g. `conanbuildinfo.cmake`) at this point. Even then, I don't know how it could be used here.

I did not consider the **regular** use-case at all, I hope this clarifies what I'm trying to do :)

>Please, help me to remember.

Sure, so the only way to apply flags to other packages with a `build_requirement` is to set `self.cpp_info.cflags` & co in the build requirement package.

But since the `CMake` does not read those flags, I must declare them in the environment too (I could write a CMake Toolchain file, but that would just "fix" the CMake-based packages).

And most build helpers do not read those flags as well (I only have packages based on CMake and Autotools, so I did check the build helpers' code to be sure).
So writing a recipe like `darwin-toolchain` is quite hard, because of the lack of standard way to pass compiler flags.

That's why I keep using `self.env_info.CFLAGS`. Which did cause the aforementioned issue with `boost_generator`.

**Comment by theodelrieu** [comment]
>they don't know about a build_require of a toolchain being applied to them

Exactly.

There is quite a lot to think about on this issue, and I believe it should be linked with #2974.
It seems to me that taking both into account could give some leads on the way to follow.

>Should we somehow force it?

I'm not sure about that, having no control in the recipe could be problematic (I don't have an example in mind, but we could ask their opinion to bincrafters' people).

OTOH, build_requirements like `darwin-toolchain` should only add flags that are global to **every** package, so forcing it should not cause problems in that specific case...

**Comment by memsharded** [comment]
This issue is outdated, the new integrations have superseded all the mentioned ones.
