### ISSUE TITLE
Problem when linking with the created library in a package test

### ISSUE THREAD

**Issue by darcamo** [conan-io/conan#3191]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

------

I'm building a recipe for the openblas library but I'm having some problems with linking.
The library seems to be correctly installed in the conan local cache after the package is created, but the test fails stating that it cannot find openblas library when it tries to compile the test. 

I'm currently trying to make the package creation work on travis with the lasote/conangcc7 docker image for GCC7 and another image based on Arch Linux for GCC8. Everything works with the Arch Linux docker image, but not with the lasote/conangcc7 image (based on ubuntu).

- (Host) Operation System: Arch Linux (but the problem actually occur when running conan in the lasote/conangcc7 docker image)
- Conan version: 1.5.2 (I have updated conan inside the docker container)
- Compiler: gcc7 (in the docker image)
- Recipe location: https://github.com/darcamo/conan-openblas

## Steps to reproduce:
- Clone the recipe repository
- From the recipe folder run docker with the command
```sh
docker run -it --rm -v $(pwd):/home/conan/project lasote/conangcc7 bash
```
- Inside the docker container from the `/home/conan/project` folder, create the package with 
```sh
conan create . <username>/stable
```

## What happens:
- Package is built correctly and installed in the conan cache inside the docker, but the test fails to compile with a linker error stating that it cannot find openblas library.

**Comment by darcamo** [comment]
That solved the problem. Just a silly mistake in the end.

Originally I was using 
```python
def package_info(self):
        self.cpp_info.libdirs = ["lib64", "lib"]
```
but I had other problems in my recipe and in my attempts to fix them I changed to only lib64. Now I changed back to include both lib and lib64 again and it is working. Thanks!


Ps: One of the problems I had was a wrong version of gfortran lib when I built the binary in the lasote/conangcc8 image and later installed the package in my Arch Linux machine, since lasote/conangcc8 is based on ubuntu and there it has version 4 for gfortran library, while Arch has version 5. With so many trick parts to make everything work I end up leaving a silly mistake in the end.
That is, for this particular recipe Linux distribution matter, but it is not part of the settings. But that is another issue.

**Comment by memsharded** [comment]
Hi @darcamo !

Glad to know that it is working now.

Regarding the other issue, when the distribution matters, and really 2 different binaries are needed for those different distributions, then the correct way to handle that is using custom settings. You can add something like ``distro`` to the ``settings.yml`` file. Then, to share it and sync with your team and CI, you could use the ``conan config install`` functionality. 
If the recipe is for OSS and sharing it in Bintray, then it might be a bit more difficult. There are no distro settings in the default settings.yml because we wanted to avoid binary explosion for the open source users, and they are defaulted to support the "mainstream" configurations. Please feel free to open a new github issue to further comment on this.

I think this issue can be closed now. Many thanks!
