### ISSUE TITLE
Conan upload the package after installing the "missing-build"

### ISSUE THREAD

**Issue by kumarsameer** [conan-io/conan#3225]
I am building a library which requires a **_missing_** library. conan already allows "missing-build". is there any way to **_upload_** that missing package just built ?

**Comment by memsharded** [comment]
Hi @kumarsameer 

Do you mean, just that missing package and not other packages? There is no syntax for that, because the install/create and the upload commands are decoupled, and they don't have memory or state. 

You can use get the output (json) from the install/create command, and there you will find information of which packages have been built, which downloaded, so you can decide what to do which each of them.

**Comment by kumarsameer** [comment]
Thanks James.
I was looking to upload _all_ built packages. Would do as suggested by you.

**Comment by Defvyb** [comment]
Would it be possible to implement uploading by json output.
It would be useful in case of CI building, to automatically upload to artifactory all missing dependencies for target platform.

**Comment by danimtb** [comment]
Hi @Defvyb,

Thanks a lot for sharing your script to upload missing pre-built dependencies. That is exactly waht @memsharded was suggesting.

Currently there is no feature planned for what you are suggesting and as you have done, Conan provides enough tools right now to do the job. However we will be reviewing the CI flows and it could be improved in the future.
