### ISSUE TITLE
Enable python 3.7 in CI 

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#3253]
At least for Linux

**Comment by darcamo** [comment]
This is specially important for Arch Linux users.

After an update in Arch Linux it now uses python 3.7. This broke conan which was installed system-wide with PIP (I don't like installing system-wide with PIP, but I wanted to use conan-cmake) and I cannot install conan anymore. That is, after the update trying to compile my C++ code now fails due to conan not running.

In the end I had to create a conda environment, which allows me to specify the python version (and give up conan-cmake for now). From there I could make my code work again.

**Comment by lasote** [comment]
It will be solved in 1.7. Thanks for the feedback.
