### ISSUE TITLE
What might be the possible issues by adding export-pkg as a post build step for local development?

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#3271]
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I'm using Conan 1.6 on Windows/Linux. 

I am thinking of adding `export-pkg` as a post build step to my CMakeLists.txt so that I don't have to manually export the package and the post build step does it for me when I am doing local development and for debugging purposes. I have tried it and it seems to be working. However I couldn't find any place in the docs where you recommend this approach. Are there any side effects that I should be aware of?

**Comment by memsharded** [comment]
Actually I think it is a good approach, and if it was widely used, it would avoid some issues and complications in the local flow. We haven't done or documented it because in general there is reluctance to change the build scripts with conan related things, so we try to keep those changes very minimal.

Just beware of protecting the call to ``export-pkg``, so it is not executed when the package is normally being build in the local cache. Maybe the macro/function doing it would be a good addition to the cmake-conan wrapper, please consider contributing it. Thanks!

**Comment by AliAskari** [comment]
Thanks. The post build is a python script that does it but I will try to write a CMake equivalent and add it.
