### ISSUE TITLE
[workspaces] Expects the recipe files to be called conanfile.py

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#3276]
conan 1.5.2

Hi, there appears no way to specify the name of the recipe files to use with the workspaces feature.

e.g. given 2 packages to work on called A and B
A/conan_some_other_name.py
B/conan_yet_some_other_name.py

Could the yaml file be extended to specify this, defaulting to conanfile.py if not supplied?

**Comment by niosHD** [comment]
Hi,

I think I just stumbled across a similar issue in Conan 1.18.3. To the best of my knowledge, it is still not possible to use workspaces in combination with custom recipe file names. We have monorepos, where multiple recipe files are located in the same directory, which can not directly use workspaces due to this limitation at the moment. Considering that all other conan commands can be used with the full path to the respective recipe I assume that this is an oversight.

On the technical side, the problem seems that the `path` property within the [workspace yaml](https://docs.conan.io/en/latest/developing_packages/workspaces.html#conan-workspace-definition) only accepts directory paths. I would suggest that specifying file paths to the recipe should also be supported.

Is this observation correct and what is the opinion of the Conan team on the issue?

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
