### ISSUE TITLE
conan download only respects the first repository in remotes.txt

### ISSUE THREAD

**Issue by ahauan4** [conan-io/conan#3279]
Scenario:
I want to download a package from an Artifactory repository called 'conan-local' with the following command
`conan download package/version@user/channel`

But the package gets downloaded only if the repository which contains the package is the first in the list of remotes in registry.txt.

registry.txt:
```
conan-local http://...
other-repo http://...
```

If the repository which contains the package is not the first in the list of remotes, the following error occurs:
`ERROR: 'package/version@user/channel' not found in remote`

registry.txt:
```
other-repo http://...
conan-local http://...
```

I think there is also a mistake in the documentation for the conan download command: 
"Only if a *reference* is specified, it will download all packages from the specified remote. Otherwise, it will search sequentially in the configured remotes."
should be:
"Only if a **remote** is specified, it will download all packages from the specified remote. Otherwise, it will search sequentially in the configured remotes."

Tested with Conan 1.5.0 + Conan 1.6.0 using Python 3.6.5 running in Windows 7 and Ubuntu 14.04

**Comment by ahauan4** [comment]
Hello memsharded,

I would expect that not specifying a remote would "search sequentially in the configured remotes" as stated in the documentation.

Text from hopefully corrected documentation:
 "Only if a **remote** is specified, it will download all packages from the specified remote. Otherwise, it will search sequentially in the configured remotes"
Which means for me: "If a remote is not specified, it will search sequentially in the configured remotes"?

You said "Not specifying the remote equals to defaulting to the first remote in the list". I could not find this in the documentation.
 
I hope you can help me clarify this.

Best regards

**Comment by memsharded** [comment]
Hi @ahauan4 

I think this is somehow outdated documentation, the behavior is not intended to be the same. The ``conan download`` behavior is not transitive, and it is not configuration (settings/profile) based. It just downloads the recipe and the binaries. It is mainly used for maintenance and mirroring operations like ``conan download`` from a specific remote + ``conan upload`` to a different remote. 

This is why the behavior is not the same as install, it doesn't make much sense to start looking for the packages in different remotes. So I would say that such docs could be because of some copy & paste from "conan install" or something like that.

Thanks for the feedback!
