### ISSUE TITLE
How to upload a package with an updated recipe without rebuilding?

### ISSUE THREAD

**Issue by AliAskari** [conan-io/conan#3283]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I have faced some cases that we need to update a recipe which is usually a dependency change, i.e. from 3.4.1 to 3.4.2, which doesn't require a rebuild of the current package but only the recipe must be updated to point to the new requirement. I know that we can use version ranges but it is not possible for different reasons so I am forced to rebuild the package and uploaded but only one file has changed in the package, the recipe. 

I am looking for a way to upload a new package with the same binary but different recipe without rebuilding the entire library. Is it possible?

**Comment by memsharded** [comment]
Hi,

Well, it is possible. You can:

- Do the changes to the recipe
- ``conan export . user/channel``
- ``conan upload Pkg/version@user/channel -r=myremote`` # Without --all it uploads recipe only

The only side effect is that it makes the current binaries "outdated", but that is exactly the meaning. The recipe hash changes, because of the edits. The package binaries they store the hash of the recipe they used to be built, so they know the current recipe has changes. It is a reasonable state, as actually changing a dependency version could produce, depending on the dependency changes, a different binary.

**Comment by AliAskari** [comment]
Thanks, but this wasn't exactly what I was looking for. I should have been more clear, I am changing the package version. You see, in our workflow we update the version of a library when any of its dependencies changes, regardless of the nature of the change i.e. either major, minor or patch. However, if it's a patch change we do not require to rebuild the library, we just have to update the version number. 

So, consider the case where I have `Pkg/0.0.1@user/channel` in my server, but I want to release `Pkg/0.0.2@user/channel` with the exact same binaries as  version 0.0.1 without rebuilding. Basically we want to download a package, then use its binaries for another package. Is this possible?

**Comment by danimtb** [comment]
@AliAskari I think that behavior is not possible. As you are changing the package version, that implies it is change in the source code of the library, so package IDs are computed taking the version into account and those from version 0.0.1 will not match 0.0.2.
