### ISSUE TITLE
Support for CMake multi-configuration (for Visual Studio projects)

### ISSUE THREAD

**Issue by WimK** [conan-io/conan#330]
Currently Conan requires explicitly specifying the build type (i.e. release or debug) at the moment of calling 'conan install'. When no build type is specified 'release' is assumed. 

However, CMake (mostly in combination with Visual Studio projects) supports multi-configuration projects. Where by specifying either 'debug' or 'optimized' in front of the library name CMake is able to generate a Visual Studio project with both a debug and optimized configuration.

See: https://cmake.org/cmake/help/v3.0/command/target_link_libraries.html

It would be convenient to be allowed to specify a multi-configuration project in Conan. For instance by doing 'conan install -s build_type=Debug;Release' would retrieve both the debug and release versions of the packages and the cmake generator would create corresponding CMake library variables containing 'debug' and 'optimized' statements. 

(This feature is of particular interest for Windows projects in which debug libraries using the C++ standard library cannot be mixed with release build of the executable and vice versa (i.e. _ITERATOR_DEBUG_LEVEL mismatch))

**Comment by tru** [comment]
Seconded, this is something I will need as well in my environment.

**Comment by memsharded** [comment]
So far, we implemented the most requested workflow, that is a folder per configuration, something like:

```bash
$ mkdir build_debug && cd build_debug
$ conan install .. -s build_type=Debug ...
$ cmake .. -G ...
$ cmake --build . --config Debug
$ cd ..
$ mkdir build_release && cd build_release
$ conan install .. -s build_type=Release...
$ cmake .. -G ...
$ cmake --build . --config Release
```
Many times this task is also automated with a small script.
The reason is that this approach is generic, work always, for multi and single configuration.

I am not opposed to implement this feature request, but would also like to keep the conan codebase as terse as possible. What should be done if the user requests -s build_type=Debug;Release;DebugWithRelInfo -s arch=x86;x86_64;armv6? Should the conanbuildinfocmake contain all the possible combinations? Why wouldn't it be applied for compiler versions? Do we want a cmake variable named CONAN_INCLUDE_DIRS_X86_DEBUG_VISUAL_14?

 I think this approach doesn't scale for a generic use case, while the folder one, every one can set their own "builds", and including the selecting logic in the main CMakeLists.txt to select the appropriate ``conanbuildinfo.cmake`` is very straightforward. It even makes more sense if using the ``visual_studio`` generator, as you can load a diferent ``conanbuildinfo.vsprops`` for each project configuration.

What do you think?

**Comment by WimK** [comment]
Your point is definitely a good one, doing this generically is a challenge. 

However, with regard to Visual Studio workflows, having a working debug and release switch is a convenient thing to have. CMake has been set up specifically to allow setting these debug and release options in a single CMake project. Using this CMake functionality in combination with Conan is currently not practically possible, which is a shame. 

One option might be to generate variable names based on the options passed (maybe this is what you meant already). For instance, if you do:

`conan install .. -s build_type=Release`

You get: 

`CONAN_INCLUDE_DIRS, CONAN_LIBS` 

This works because there is only one configuration specified. No need to append _RELEASE, etc.

Only when you start specifying multi-configurations:

`conan install .. -s build_type=Release;Debug -s arch=x86;x86_64`

you get multi-configuration variables:

`CONAN_INCLUDE_DIRS_RELEASE_X86, CONAN_LIBS_RELEASE_X86, CONAN_INCLUDE_DIRS_RELEASE_X86_64, CONAN_LIBS_RELEASE_X86_64, CONAN_LIBS_DEBUG_X86, etc.` 

(In this case the Conan's CMake generator could be smart and 'fold' the two CONAN_LIBS_RELEASE/DEBUG_X86 into a CONAN_LIBS_X86 with CMake's 'debug' and 'optimized'). 

With this scheme it is possible to keep simple variable names for simple configurations, but to get flexible but slightly more complex variable names for multi-configurations. Users that require multi-configurations are probably fine with more complex naming anyway.

**Comment by memsharded** [comment]
Yes, that can definitely be done. It is not an impossible problem for conan, but it will be much more difficult for the consumers, so they have to know all the conventions we decide to implement into the variables names. I disagree with the fact that consumers will be fine with a more complex naming approach. I have seen it many times, the less they have to check the ``conanbuildinfo.cmake`` and conan cmake variables, the better. 
Event the smart contractions for the use cases we decide, they will not fit their use case everytime some setting is added, or managed. Consider that there are users using their own settings. 

So how would the logic of the consumer look like? I am imagining myself some CMake scripts and certainly don't want to be a consumer having to write and deal with it. Can you provide some pseudo-cmake of the consumer side?

I also have the question, how the switch will be handled. So you want to change the IDE selector from Debug->Release, and use different variables. Even if you have the variables, I think this is not possible with cmake, as it is not reloaded.

In any case, I am not saying not trying to implement it. I am saying that a better solution might be, instead of managing the naming for all the variables, use that name as a global "scope" in the file or folder name, and use that at a higher level. So the consumer side would be like (pseudo-cmake):

```cmake
if(${CMAKE_BUILD_TYPE} == "Debug)
   if(${CMAKE_ARCH} == 32)
      include(${CMAKE_BINARY_DIR}/debug_32/conanbuildinfo.cmake)
   else()
      include(${CMAKE_BINARY_DIR}/debug_64/conanbuildinfo.cmake)
   endif()
else()
 if(${CMAKE_ARCH} == 32)
      include(${CMAKE_BINARY_DIR}/release_32/conanbuildinfo.cmake)
   else()
      include(${CMAKE_BINARY_DIR}/release_64/conanbuildinfo.cmake)
   endif()
endif()
```

You know, like a C++ namespace, instead of the old C style of prefixing the name of the library to every method and struct :)

With an approach like this, any combination could be easily managed, even new ones, and both the conan and the consumer sides are easy to manage. My only concern, but it would be also for the variable names, is that the IDE does not reload cmake on configuration selector.

**Comment by WimK** [comment]
> I also have the question, how the switch will be handled. So you want to change the IDE selector from Debug->Release, and use different variables. Even if you have the variables, I think this is not possible with cmake, as it is not reloaded.

This is actually possible with CMake. All relevant functions in CMake have a way of specifying the configuration for which it is going to be used. Exactly to support multi-configurations in tools like Visual Studio.

See: https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html (which explains why CMAKE_BUILD_TYPE is only relevant for single-configuration generators)

Or as a specific example: https://cmake.org/cmake/help/v3.0/command/set_target_properties.html - set_target_properties allows you to set a <CONFIG> for every property. So for instance: 

```
target_link_libraries(${TARGET_NAME} PROPERTIES 
	DEBUG_POSTFIX "S")
target_link_libraries(${TARGET_NAME} PROPERTIES 
	RELEASE_POSTFIX "D")
```

Attached I have a CMakeLists.txt that creates a multi-configuration project. When picking Visual Studio as its generator it will create a single Visual Studio project with configuration specific libraries, postfixes (D for debug, S for release) and definitions. All of which can be selected in VS by picking a configuration from the drop drop list. 

[CMakeLists.txt](https://github.com/conan-io/conan/files/318330/CMakeLists.txt)

The 'namespace' solution could work, but it requires, in my opinion, a workflow that is much more complicated than it should be. Especially since I expect the Conan -> CMake -> Visual Studio workflow to be very common. It would mean multiple Conan calls, multiple directories to separate conanbuildinfo.cmake files, and a quite complicated CMakeLists.txt. 

At CMake they have made the choice to allow debug or release to be specified in a single CMakeLists.txt. Architecture (x86, amd64, etc) though cannot be switched and you will have to generate a new project. For me this is a logical separation as it allows for the most common Visual Studio workflow (i.e. switching between debug and release during development). Switching between architecture is less common during development.

**Comment by memsharded** [comment]
If it is only for debug/release, then it is fair enough. And I agree it is a common use case.
Also, I was not opposed to conan handling the -s arch=Debug;Release automatically, just that it would create automatically 2 files.
I will have a second thought at it. Probably consider also to create a new custom cmake generator (like cmake_multi), through generator packages, that allows us to test it without having to wait till the next conan release.

**Comment by jcar87** [comment]
I guess on Linux the current workflow make sense because there isn't a convention regarding the naming  of libraries in different build configurations. But on windows it is quite typical to bundle both debug and release versions in the same folder, and simply use a different filename (e.g. tbb.dll , tbb_debug.dll ).
a lot of Find_XXXX modules in CMake are coded to find both release and debug on windows, and libraries like OpenCV (which builds using CMake), produce an OpenCV-config.cmake that supports the configurations for which it was built, on the same directory structure (still talking about windows). How does conan handle these cases?

Having cmake use a different conanbuildinfo.cmake depending on the 'build type' sounds like a good solution, however, when using generators such as Visual Studio, the CMAKE_BUILD_TYPE variable has no effect whatsoever, as the type of build is decided at build time, and not at configure time (unlike makefile generators). 

You would be forced to select a build configuration at configure time (e.g. Debug), and then make sure the projects in visual studio are built in Debug only. But building this project in 'Release' will cause the runtime mismatch. At best, the iterator_debug_level problem will trigger and error  and alert you, and at best, it will compile and link, but crash at runtime whenever objects cross CRT boundaries between debug (libraries) and release (your executables using those libraries).

**Comment by memsharded** [comment]
I have an idea that could be interesting, developing a ``cmake_multi`` generator that would append configurations to the ``conanbuildinfo.cmake`` file. That can work. But now, I am investigating if we can do that with cmake. I haven't found an idiom to use different include_directories for debug and release configurations. And they have to be different, as it sometimes happens that the packages have generated headers, different for debug and release configurations.

I have checked, and the cmake conditional approach:
```cmake
if(${CMAKE_BUILD_TYPE} == "Debug)
   include_directories(...)
else()
   include_directories(...)
endif()
```
It is not valid, as it is evaluated just once at cmake configuration time, but not changed when selected in the IDE. So we would need a cmake ``include_directories`` per configuration, which up to my knowledge, is still not available. Any ideas on this?

**Comment by WimK** [comment]
CMake does support setting different include_directories based on generator expressions.

For instance, adding the following will generate a VS project with the 'include_release and include_common' in the release configuration and 'include_debug and include_common' in the debug configuration (minsizerel and relwithdebinfo only have common):

```
include_directories(
	"$<$<CONFIG:Release>:${CMAKE_CURRENT_SOURCE_DIR}/include_release>"
	"$<$<CONFIG:Debug>:${CMAKE_CURRENT_SOURCE_DIR}/include_debug>"
	"${CMAKE_CURRENT_SOURCE_DIR}/include_common")
```

Admittedly, the syntax is a bit clumsy (it is CMake after all). It also requires an absolute path (hence  ${CMAKE_CURRENT_SOURCE_DIR}) due to the way generator expressions work. Technically it does work very well though.

**Comment by memsharded** [comment]
Perfect, I'll try to come up with a proposal in the next days. Thanks for the info!

**Comment by memsharded** [comment]
Here is my initial proof of concept: https://github.com/memsharded/conan-cmake-multi
It is generating:
- a ``conanbuildinfo_multi.cmake`` which includes other files and define the common helper macros
- one ``conanbuildinfo_<config>.cmake`` for each different <config> = Release, Debug that is installed

The include_directories with generators work great, but the link_directories does not accept generators. 
I have created full paths in the generator for LIBS, so they can be used as:

```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo_multi.cmake)
conan_basic_setup()

ADD_EXECUTABLE(example example.cpp)
TARGET_LINK_LIBRARIES(example debug ${CONAN_LIBS_DEBUG}
                              optimized ${CONAN_LIBS_RELEASE})
```

It still has some hacks, and missing FLAGS and other stuff, but I think that in general it is looking good. I doubt also that the CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH will work nicely with this feature, but I'll check it later.

**Comment by monsdar** [comment]
As far as the example CMake-code goes it looks exactly like I would have imagined such a feature. Hope the hacks and quirks can get solved somehow.

**Comment by memsharded** [comment]
I think I can solve most hacks and quirks, but the inherent to CMake one pointed out in my last comment: It seems that it is not possible to achieve a transparent use of FindXXX.cmake with this approach. With the cmake built-in generator, the FindPackage is able to work for conan packages, because it has to find one lib or set of libs. But the FindPackage is not designed to find in two different locations, so it is not possible to issue an e.g. find_boost in the consumer CMakeLists.txt and that it will work for the debug and release dependencies.

However, that issue is really not required, and was integrated to make easier for consumers already having their cmake working with Find.cmake. It is totally possible to use regular conan cmake vars (CONAN_INCLUDE_DIRS_DEBUG, CONAN_LIBS_RELEASE...) in the consumer CMakeLists.txt to link to the dependencies. What do you think?

**Comment by memsharded** [comment]
Just an added comment to clarify things about the internals:
- Find.cmake can works sometimes with some packages to get both debug and release artifacts because **both debug and release artifacts are bundled together**, (typically in win).
- Conan generates different package binaries for debug and release. They are created, uploaded and installed independently, and it is not possible to change this.
- So any multi-configuration approach has to manage to locate them in different locations. In the Find.cmake case, it would mean that CMAKE_MODULE_PATH, CMAKE_PREFIX_PATH, CMAKE_INCLUDE_PATH, CMAKE_LIBRARY_PATH could support Debug/Release generator expressions, but it seems that it doesnt.

**Comment by KindDragon** [comment]
Related to #114

**Comment by KindDragon** [comment]
The main issue with Conan for me

**Comment by memsharded** [comment]
Thanks @WimK !

Yes, I totally agree. It is a limitation of CMake, but yes, we are willing to do as much as possible to improve over this. So I am looking forward to seeing your Find stuff, maybe there is something we could do. And we could collaborate with package creators to implement the new feature inside their find_packages if it is the case.

In any case, I would like to recall a couple of things:

Let's remember that with conan, find_packages are actually not necessary, and such usage of find_package is provided for a transparent integration with previously existing CMakeLists. With a cmake ``if()`` and a few lines, the problem is gone. Moreover, the cmake code necessary to integrate an existing library is less with conan that having to write a custom find_package for the library.

Lets also remember for a moment that all this work that we are doing with this generator is to avoid going to the terminal and typing:
```
$ conan install -s build_type=Debug
```
when switching from Release=>Debug in the IDE. So we are trying to optimize away just a very few seconds of typing (plus the inconvenience to remember doing it, I know). 
There are also other solutions, of course, as generating two different VS solutions from cmake, one for debug and one for release, in different folders.

I am trying to put the issue in perspective so let's not get burnt with this, if it is too much work for you. 

Thanks again!

**Comment by WimK** [comment]
Took a little bit longer than expected (and had some issues with the pushing to the repositories). But I have committed an example with multi-configuration. Please note that it has some issues (which I will explain), but the general idea works. 

The cmakemulti generator:  https://github.com/WimK/conan-cmake-multi 
Slightly adjusted from the version by @memsharded. I had to revert some changes in the most recent version as I got some erros. I also changed the check for existence of the conanbuildinfo_\<...\>.cmake in conanbuildinfo_multi.cmake as it would not work with out of source builds. 
(Originally I also added some utility CMake macro's to the generator, but later decided to remove it from here). 

LibXML2 conan package: https://github.com/WimK/conan-libxml2
I have adjusted the LibXML2 from @lasote as a demonstration of a package with support for multi-configuration. It uses a config mode find_package script (LIBXML2Config.cmake). (On a side note: config mode find_package are, in my opinion, a better choice for conan packages than the module mode find_package scripts that most conan packages currently use). 

Project that uses the LibXML2 conan package: https://github.com/WimK/conan_multi_xml
This project makes use of the multi-configuration version of the LibXML2 conan package. It includes a ConanFindUtilities.cmake that contains two CMake find utility macros. 

Things to note: 
- I do not use "conan_basic_setup()" in CMake because it sets some variables (include_directories and link_directories) that I want to set based on the find_package scripts variables.
- ConanFindUtilities.cmake should probably be located at a different location. But as a proof of concept I just packaged it with the project. 
- This setup works with both single and multi-configuration projects 
- The main problem with this setup is that the find_package script (LIBXML2Config.cmake) is packaged with a single package, but it is used to find other package as well (e.g. the debug package will also attempt to find the debug package based on variables from the conanbuildinfo files).

**Comment by a-teammate** [comment]
Nice that you try to get multiconfiguration support done :+1:

(Although I could probably live with a single configuration, since switches between build types are rare on my side).
In the maintime we would have a useless switch field in the IDEs:
You can "choose" between Debug and Release and possibly more although only one is working.
This is error-prone imo.

It would be great if we could get some addition to conan to disable any configuration but the one we used with `conan install`.
For the CMake integration this would be pretty easy:
* ~~Parse conaninfo.txt for the build type~~
   * ~~(so we dont rely on cmake being invoked from python)~~
   * ~~same regex as in conan_get_compiler()~~
* ~~set CMAKE_CONFIGURATION_TYPES to the "Debug" or "Release" depending on that~~
   * ~~somewhere inside conan_basic_setup() so we got it globally for every modded package~~

**EDIT:** I just noticed that CMAKE_CONFIGURATION_TYPES just does something if set before `project()`..
So there is no way around requiring CMake being invoked with conans.CMake.command_line stuff anyways.. well but we could 

Maybe is it possible to disable multiconfiguration support inside the Visual Studio and XCode integrations as well (for VS it could be easy but ugly, since we're basically working on xml files here)

**Comment by yeswalrus** [comment]
Just a +1 on this feature request from me - As a visual Studio / XCode user this is rather problematic

**Comment by memsharded** [comment]
Hi @yeswalrus , just in case please remember, that the worst case scenario workaround for this limitation is just going to the terminal and typing:

```bash
$ conan install -s build_type=Debug
```
and

```bash
$ conan install -s build_type=Release
```
When these commands are in the history, switching from Debug to Release dependencies and viceversa is about 3 keystrokes.

I typically switch branches in git in the terminal much often than switching from Debug to Release.

**Comment by monsdar** [comment]
Please keep in mind that you probably also would like to build MDd when
building Debug.

There's an issue with more details, I'm on mobile so please forgive me not
linking it directly :)

James <notifications@github.com> schrieb am Do., 1. Dez. 2016, 10:18:

**Comment by memsharded** [comment]
Yes, that is true. You probably want to use profiles instead:

```bash
$ conan install --profile=VS14_dbg
```

and

```bash
$ conan install --profile=VS14_release
```

Inside the profile, you can make sure that the correct VS runtime is set

**Comment by definename** [comment]
Hi, all. I am using conan version 0.16.1. As I understood currently there is no way to link correct Debug and Release libraries by switching in IDE (Microsoft Visual Studio)? Is this issue is will be added in future?
Thanks.

**Comment by memsharded** [comment]
No, integration with the IDE is still not there.

Could be technically possible if the package creators bundled Debug and Release artifacts in the same package, but this is not usual. If you are just consuming your own packages, you might be able to do it.

Might be added in the future, but still a low priority issue, as it can be properly managed by just 3 key strokes in the terminal. In fact it can be better managed, as it can also switch from architecture and other settings and options in just 3 keystrokes. And the terminal is still necessary for all the other conan commands. So no big issue IMHO.

**Comment by definename** [comment]
Got it. Thanks.

**Comment by memsharded** [comment]
I am resuming work on this, moving the external generator to a built-in generator.  Will try to have a proposal for conan 0.18, but not sure. Will just not use "FindCmake" utilities, with the modern cmake generation of targets per package, it certainly doesn't make too much sense to rely on FindCMake to find dependencies that conan perfectly knows where they are.

**Comment by WimK** [comment]
@memsharded I am not entirely sure what you mean exactly when you say FindCmake utilities. But in CMake, find_package commands are also used when retrieving dependencies for which the location is already known. Especially in modern target-based CMake the scripts that are run after a call to find_package are used to set properties on the imported targets  (it does much more than just locating the library includes/library files). It would in my opinion be a mistake not to use find_package. 

For instance Qt5 comes with a big collection of find_package (config/no_module) scripts that are used to setup the exact properties of the requested libraries (transitive dependencies, run time dependencies, compile definitions, etc). This only works when you already indicated the location of Qt5 to CMake, so in that case find_package(Qt5... is not used to locate Qt5, but to set it up correctly. The same goes for Boost.

**Comment by memsharded** [comment]
The new "cmake-targets" feature of conan already automatically generate targets for the dependencies packages, so no need to look for libraries or define targets yourself: http://docs.conan.io/en/latest/integrations/cmake.html#consuming-conanbuildinfo-cmake

Please have a look and tell me if it makes sense.

**Comment by memsharded** [comment]
I have some preliminary working proposal at: https://github.com/memsharded/conan/tree/feature/cmake_multi

If running from source, you might try it:

First add generator ``cmake_multi``

Then:

```bash
$ conan install -s build_type=Debug -s compiler="Visual Studio" -s compiler.runtime=MDd
$ conan install -s build_type=Release -s compiler="Visual Studio" - s compiler.runtime=MD
```

Only the global configuration works (not the modern-cmake-with-targets), so you might use it as:

```cmake
project(MyHello)
cmake_minimum_required(VERSION 2.8.12)

include(${CMAKE_BINARY_DIR}/conanbuildinfo_multi.cmake)
conan_basic_setup()

add_executable(say_hello main.cpp)
target_link_libraries(say_hello debug ${CONAN_LIBS_DEBUG} optimized ${CONAN_LIBS_RELEASE})
```

Then it is possible to just do:
```bash
$ cmake -G "Visual Studio 14 Win64"
# And then build both configurations without regenerating, like the switch
$ cmake --build . --config Release
$ cmake --build . --config Debug
```

I will keep working on this, to provide the modern cmake-targets implementation, but feedback very welcome.

**Comment by traceon** [comment]
@memsharded, as proposed in #799, maybe instead of:
```
$ conan install -s build_type=Debug -s compiler="Visual Studio" -s compiler.runtime=MDd
$ conan install -s build_type=Release -s compiler="Visual Studio" -s compiler.runtime=MD
```

Conan would be able to support something like that:
```
$ conan install -s build_type=Debug,Release -s compiler="Visual Studio" -s compiler.runtime=MDd,MD
```

or, better to say:
```
$ conan install --profile vs-debug,vs-release
```
where `vs-debug` and `vs-release` profile files provide all the appropriate toolset config?

And, `vs-debug` profile file, for example, in its turn might have `compiler.runtime=MDd,MD` to tell Conan to prepare both, debug packages linked with static release runtime, and static debug runtime.

**Comment by memsharded** [comment]
Yes, sure, no problem, that is just syntactic sugar, easy to implement, not a concern at all, compared with the rest of the feature. If everything goes well and this is approved to release, I'll check it (I think the comma syntax won't have issues) and implement it.
