### ISSUE TITLE
Scopes

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#331]
- Conan test command should offer scopes
- Would be great if you can self.output.warn(self.scope)
- conan install command caches "conaninfo.txt" file with the scopes variables, but you cannot remove the scopes vars unless you delete the conaninfo.txt. I suggest to do:

```
conan install --scope !somevar
```

- Would be great if you have a special pattern to specify "all the packages in the tree" so the scope is applied to all dependencies:

```
conan install --scope ALL:somevar
```

**Comment by memsharded** [comment]
I am changing, to a more general (and I think intuitive scope).
The syntax for user will be:

```bash
$ conan install --scope MyScope=True
$ conan install --scope MyScope=False # to negate, instead of weird !MyScope
```

Furthermore, arbitrary values are also allowed for scopes, not only True or False. Is this OK?

**Comment by memsharded** [comment]
For the ``ALL`` approach, I have tried some pattern approach, but too complicated, both implementation and usage, and handling corner cases. I have just implemented the ``ALL`` to refer to all dependencies. Note, it will be additive and specific scopes have precedence over the ALL, that is ALL:myscope=True, Hello:myscope=False => Hello:myscope will be False

**Comment by memsharded** [comment]
Question for the OUTPUT issue with ``self.output.info(self.scope)``. 
I have implemented the output as ``dev=True, other=False``. OK?

**Comment by lasote** [comment]
All in 0.10.0

**Comment by SumuduLansakara** [comment]
I have a related issue.

Say i'm exporting a package recipe. Now conan search gives this.

- mypackage/0.1.0@user/channel

I can install it locally (assume I'm building from source through conan) using following command.

- conan install mypackage/0.1.0@user/channel --build mypackage

Everything works fine up to this point. 

But it doesn't work if i try to pass a scope variable for the above install command. (no scope variable is set there)

- conan install mypackage/0.1.0@user/channel --build mypackage --scope key=value

I'm stuck here without being able to pass a flag that doesn't affect the package integrity :).Can you please you can explain this and provide any possible work around if this is the expected behavior.
