### ISSUE TITLE
Exporting a package throws "No linter available" error

### ISSUE THREAD

**Issue by ruimaciel** [conan-io/conan#3324]
I've installed conan 1.6.1 on Ubuntu 16.04 from conan's official DEB package, and followed the official [tutorial on creating packages](https://docs.conan.io/en/latest/creating_packages/getting_started.html) to create a package for a third-party library (pugixml).  

I've managed to create a package, but unfortunately when I've tried to export the package the following error was thrown:

    rui:~/conan_package_test$ conan export . demo/testing
    No linter available. Use a pip installed conan for recipe linting
    pugixml/1.9@demo/testing: The stored package has not changed

I've tried installing some pylint packages, but unfortunately that didn't solved the problem.

**Comment by memsharded** [comment]
What the message is saying is that the .deb conan installer does not have the linter included. It is a warning, not an error. It is not possible to include pylint in the .deb package, due to the restricted GPL license of the pylint, which doesn't allow to redistribute it (note that the .deb installer is a binary bundle with the python interpreter included in the bundle. So no matter what you install in the system, it won't be used).

The solution is to install conan with ``pip install conan``, not with the .deb package. We are also working to implemente a complete plugin system to conan, which might convert the linter to a plugin, and then be usable in all installations. But at the meantime, it is not possible, due to the GPL license of pylint.
