### ISSUE TITLE
[question] Versioning Schema Understanding

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#3344]
Hi,

I was reading the [Versioning schema](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#versioning-schema) section of the docs and got confused!

I may have mis-understood, but this section suggests to me that if you have a package with reference _MyOtherLib/2.0@lasote/stable_, and the MyOtherLib package version changes from 2.0 to 2.1 but the package reference **remains unchanged**, then Conan will re-build PkgConan if the following is added to the package_id() method:

`myotherlib.version = myotherlib.full_version`

1. Is this correct?

If the answer is yes, this raises a couple of other questions.

2. Are version numbers, when used like this (not version ranges), more than just strings? I thought they were just strings and that version ranges were required to get semver capability.

3. I'm trying to understand the use case for when changing a package version but keeping the reference the same makes sense?

**Comment by danimtb** [comment]
I am not use if I understand the scenario:

So you are saying you have a "Mylib" library that requires "MyOtherLib/2.0@lasote/stable" and then there is a new release 2.1 of "MyOtherLib" and require in "Mylib" recipe changes to "MyOtherLib/2.0@lasote/stable".

Is that right?

I am not sure what you mean about:

> but the package reference remains unchanged, then Conan will re-build PkgConan if the following is added to the package_id() method:

Please explain the scenario with detail so we can help you describing the Conan behavior accurately.

**Comment by keithrob91** [comment]
To be honest, I was just trying to understand that section of the document, and I'm struggling to do so! I'm also not sure what I asked makes much sense either, not surprising as I don't understand this section of the documentation.

Maybe I can ask a different question.

Does Conan use semver when _not_ using version ranges?

The Version Schema section does not use version ranges, but suggests Conan will rebuild MyLib in some situations.

What I would like to see in this section, is a proper worked example, showing the changes to MyLib and MyOtherLib and the steps taken that will cause MyLib to rebuild in a custom manner, for example, when a minor version number changes.

**Comment by lasote** [comment]
> Does Conan use semver when not using version ranges?

Yes, by default. Unless the "version" field cannot be "parsed" as a valid semver version.

To help you understand, the ID of `MyLib` is built with a hash of the settings + options + requires references. Any change in the settings or options will change the ID of a package, but, for the requires is a little different. By default, if `MyOtherLib/2.0` changes to `MyOtherLib/2.1`, following semver, conan won't change the ID of `MyLib` because is using `2.X` as the string being hashed.
If you change the versioning schema, you change the way the requirements reference is hashed in the ID. 

When the version doesn't follow semver, like `OpenSSL/1.0.2n`  (the n is not valid) the whole string is included in the hashed string, so any change in the "version" will change the ID of the packages requiring OpenSSL.

Hope it helps!

**Comment by lasote** [comment]
Yes, in that case, you need to solve the conflict by using version ranges or specifying a pinned version of `PkgA` in the consumer. That is not related with the versioning schema docs section.
Please write if you need further information.
