### ISSUE TITLE
[feature] Forward the OS X version to CMake helper

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#3346]
Following PR #3091 , there is now an optional `os.version` setting for OS X. Following [this comment](https://github.com/conan-io/conan/issues/2534#issuecomment-399117915) from @lasote, we plan to use it as the minimum osx version (the `-mmacosx-version-min` compiler flag).

CMake makes a provision for that thanks to the [`CMAKE_OSX_DEPLOYMENT_TARGET`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html).

Should `os.version` be automatically used by the CMake helper, like many other settings are implicitly used to define some CMake variables?

**Comment by jgsogo** [comment]
It looks like easy to pipe the value from settings `os.version` to CMake's [`CMAKE_OSX_DEPLOYMENT_TARGET`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html) (see PR associated).

Nevertheless, I wonder if it always should have the same value as [`CMAKE_SYSTEM_VERSION`](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_VERSION.html). Conan gets the value for `CMAKE_SYSTEM_VERSION` using this logic (extracted from [here](https://github.com/conan-io/conan/blob/82631b05304f07dddfbd9f2cb0721e10fcd43d17/conans/client/build/cmake_flags.py#L134)):

```python
os_ver_str = "os.api_level" if os_ == "Android" else "os.version"
op_system_version = self._ss(os_ver_str)
cmake_system_version = get_env("CONAN_CMAKE_SYSTEM_VERSION", op_system_version)
```

May be relevant too: https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling

**Comment by amerry** [comment]
Looking around the CMake code a bit, it looks like `CMAKE_SYSTEM_VERSION` on OSX is mostly used to determine toolset support. Specifically, it is used to determine support for linker flags ('-search_paths_first` and `-rpath`), as well as support for rewriting RPATHs at install time.

The intended semantics is a little unclear - if `CMAKE_SYSTEM_VERSION` indicates OSX pre-10.5, is rpath support disabled because we expect the compiler not to support it, or because we expect the system running the binaries not to support it?

So I don't really have an answer for you, sorry. I think it would probably be reasonable to set `CMAKE_OSX_DEPLOYMENT_TARGET` _instead of_ `CMAKE_SYSTEM_VERSION` on OSX, but that may break some edge cases. On the other hand, setting `CMAKE_SYSTEM_VERSION` might unnecessarily disable some features.

**Comment by lasote** [comment]
Many thanks for your investigation.
As the docs say: `CMAKE_SYSTEM_VERSION: The version of the operating system for which CMake is to build`, so it looks like should affect the target binary, not the building compiler (building machine). 
And I agree with changing the `CMAKE_SYSTEM_VERSION` behavior in Conan could be breaking.
So I would say we should adjust both with the same value from the setting and wait for more feedback/knowledge?

**Comment by jgsogo** [comment]
The PR has a test to check that `CMAKE_SYSTEM_VERSION` and `CMAKE_OSX_DEPLOYMENT_TARGET` are always the same, I think that all possibilities to give values to these variables are covered (check [here](https://github.com/conan-io/conan/pull/3486/files#diff-cd58cd0dfc3250b46311d65eb7f413d0R967)): environment, and settings. And I think that this is the correct behaviour.
