### ISSUE TITLE
conans.tools.unzip does not preserve symlinks breaking sfml builds on OSX

### ISSUE THREAD

**Issue by cpbotha** [conan-io/conan#336]
Installing sfml/2015.8.12@TyRoXx/develop with conan 0.9.4 (from pip) on OSX I just ran into this issue during compilation: http://en.sfml-dev.org/forums/index.php?topic=16674.0

In short, the SFML zip contains symlinks to nested frameworks that are used during compilation on OSX. The conans.tools.unzip() function does not appear to preserve these symlinks during extraction, so the build breaks. I checked some of the files, instead of being created as symlinks, the file _contents_ are what the symlink should have been.

For you reference, here is the spot where `.extract()` is called: https://github.com/conan-io/conan/blob/develop/conans/tools.py#L64

As far as I can see, Python's ZipFile does not by default support symlinks at extraction. I have not been able to find if there's a straight-forward method of adding this support.

P.S. It seems this is planned for Python 3.6. There's patch that could be repurposed for the conans utility function. https://bugs.python.org/issue27318

For Google's sake, here is an example warning, which later leads to termination, during the build:

```
ld: warning: ld: warning: ignoring file /extlibs/libs-osx/Frameworks/OpenAL.framework/OpenAL, file was built for unsupported file format ( 0x56 0x65 0x72 0x73 0x69 0x6F 0x6E 0x73 0x2F 0x43 0x75 0x72 0x72 0x65 0x6E 0x74 ) which is not the architecture being linked (x86_64): /extlibs/libs-osx/Frameworks/OpenAL.framework/OpenAL
```

**Comment by memsharded** [comment]
Yes, it is true, it seems there is no simple way to fix this using python ZipFile. 

Applying such a patch to the running python is not possible, we cannot mandate that to our users. Even if it was possible with the auto-installers, most users are using the pip package. I guess that you are suggesting to fully implement a compliant ZipFile that does the task from python+patch. Seems a bit too much for me, but might be doable.

I think the best would be to know why the SFML zip is doing symlinks at unzip time. Sounds weird to me. Probably it is depending on something supposedly to be there (freetype, soundfile), by symlinking? Not fully understand the SFML approach. Maybe the correct approach would be to provide those dependencies in conan and remove the symlinking? Just an idea, maybe @eXpl0it3r can give some advice here.

**Comment by cpbotha** [comment]
These are Mac frameworks that sfml requires and ships with. Internally, these frameworks seem to rely on symlinks, so at least on Mac, you're stuck with them.

Perhaps this issue can be addressed by warning conan package authors that tarballs are to be preferred on the Mac.

**Comment by cpbotha** [comment]
I tried modifying the SFML conanfile.py to use the 2.3.2 (latest stable) SFML tarball, which solves the symlink problem, but now those same extlibs frameworks (sfml dependencies) are causing problems because the SFML cmake install wants to put them in /Library/Frameworks, which results in permission denied.

Even changing their destination to ~/Library/Frameworks breaks slightly further on due to:

```
CMake Error at cmake_install.cmake:55 (file):
  file INSTALL cannot set permissions on
  "~/Library/Frameworks/FLAC.framework"
```

Oh well... Linux was always much more user-friendly than OSX.

**Comment by memsharded** [comment]
Yes, Linux more dev-friendly, indeed. 
So you mean the frameworks are bundled in the tarball? As binaries? Don't you think that having a package manager, a better way would be that the dependencies were provided by the package manager instead of being embedded in the sfml "sources"? This pattern is somewhat common, due to the lack of a package manager, so what we usually do is to provide the dependencies from conan, and patch the CMakeLists.txt at ``source()`` time to actually use the conan dependencies. It is true that this requires some more work, but is also the more correct approach.

So for the permissions problem, not sure what would be the approach. Do you have your modified SFML conanfile in a repo I can fork, to work with the same base? Won't be able to do it till Tuesday, though.

**Comment by cpbotha** [comment]
No rush, thanks! I'm really just testing conan out (discovered via the awesome CPPCast interview with Diego) with sfml, and thought other people might be bitten by this issue, hence this report.

I agree with your idea of handling the dependencies (flac, freetype, ogg vorbis, openal) with conan also.

**Comment by memsharded** [comment]
Excellent, thanks very much to you for reporting! In any case, SFML is something I want to do, used it in the past, think that it is great library. Will try to allocate some time to build SFML deps properly.

**Comment by eXpl0it3r** [comment]
@memsharded I have little knowledge in regards to what SFML does on OS X, for that you'd better consult @mantognini.

**Comment by memsharded** [comment]
Ok, thanks, so please, if @mantognini, you have some insight over this issue that could help us, that would be great.

**Comment by cpbotha** [comment]
@memsharded if you're going to play with sfml on osx using conan, you definitely want to checkout my other report: https://github.com/conan-io/conan/issues/337 :)

**Comment by mantognini** [comment]
@memsharded, I'll try to shed some light on what I can. :-)

> I think the best would be to know why the SFML zip is doing symlinks at unzip time.

I can confirm what @cpbotha said: this is due to the internal structure of frameworks on OS X.

> Maybe the correct approach would be to provide those dependencies in conan [...]?

That's what I had recommended when dealing with [SFML forumla](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sfml.rb) for homebrew. You can see in the linked code that after extracting the zip archive the provided extlibs are removed (except for headers).

Alternatively, you can configure manually each dependency using classic CMake variables -- I'd say it's even more elegant that way actually, especially since keeping the headers for non-header only is kind of strange...

HTH
