### ISSUE TITLE
What exactly is checked to say a package is up to date in a conan upload

### ISSUE THREAD

**Issue by keelerad** [conan-io/conan#3378]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

We are new to using conan and I want to make sure I understand what is checked when the following message appears:

Uploading package 1/1: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
Package is up to date, upload skipped

Now this is a component in development that has been rebuilt, with no changes to recipe or any setting that might cause the conan package hash to change

The package was rebuilt and may well have updated source, is the check that is done just the conan hash (which won't have changed)  or does it actually assemble the package tarball locally and sha1 it to compare with the sha1 for the one held in the artifactory ?

I would prefer to be able to force an upload to artifactory to be absolutely sure that the latest build is there, but that does not seem possible with upload (have tried --force, --no all and --all but all respond with the package is up to date message if you try and upload the same thing twice in a row, a pretty meaningless test I know but was trying to find something that means it will absolutely get uploaded)

If that message only appears if a full hash is done of the new local package tarball and that is compared with the full hash of the package tarball in artifactory i.e. they are byte by byte identical, then I understand what that message means

If it just means that the conan hash hasn't changed then we don't know they are byte for byte identical

If there is a really force an upload command, that never responds with "Package is up to date, upload skipped" I would feel a lot happier using that

Alec Keeler, Build and Release Engineer

**Comment by keelerad** [comment]
Conan version we are using is 1.6.1, but the question is applicable to any version

**Comment by keelerad** [comment]
This is similar to #2657 which suggested --all would force an upload, but it doesn't, if you try to upload the same package twice on the 2nd attempt you get the up to date message

**Comment by memsharded** [comment]
Hi Alec,

Thanks for your question. The relevant code is in this place: https://github.com/conan-io/conan/blob/3a695a1450b368f08117bb42ffda2c5fc0e60595/conans/client/rest/rest_client_v1.py#L254

It is using the md5 checksum from the actual files. If the message is shown and it is skipping the upload, it is because their are byte by byte identical. I guess you can always run a ``conan remove <pkg-ref> -r=your-remote`` first, if you want to force the transfer, but seems a bit unnecessary.

**Comment by keelerad** [comment]
Thanks for the reply, I was hoping that was what it was doing but didn't want to make the assumption and didn't want to suggest to devs that they needed to continually update version numbers on components in development to make sure they did get uploaded

**Comment by memsharded** [comment]
You are welcome. Regarding the "continually update version numbers", this is basically what the new **revisions** feature will be implementing, adding a hash (both to the recipe and binaries), that changes for every change on the recipe or binaries. So instead of overwriting packages, it will be creating different references automatically and transparently. (The ongoing work, it is an extremely complex feature, is in https://github.com/conan-io/conan/pull/3055)
