### ISSUE TITLE
SystemPackageTool is missing an add_repository() method

### ISSUE THREAD

**Issue by bryceschober** [conan-io/conan#3385]
Conan looks like it **almost** entirely handle all of our particular development environment setup, with one exception... it doesn't yet have a method for installing new repositories for system packages.

If `SystemPackageTool` had an `add_repository(repositories, repo_key=None, post_update=True)` method, then my hack-crap install script could be greatly improved. For example, with `AptTool` it would issue an `apt-add-repository <repo>` command for each repository in the list, if that repository was not already found in the system repository lists. Different styles of apt repositories could be supported, as in:
```python
if os_info.linux_distro == "ubuntu" and os_info.version < 16.04:
    installer.add_repository("ppa:jonathonf/gcc")
installer.install("g++-5")
installer.add_repository("deb http://opensource.wandisco.com/ubuntu trusty svn19", 
    repo_key="http://opensource.wandisco.com/wandisco-debian.gpg")
installer.install("subversion", "subversion-tools"])
```

**Comment by jgsogo** [comment]
I'm having a look at this issue and, as there are so many tools, it is not straightforward... let's document it a little bit (first approach):

- **Apt**: `apt-add-repository <url>`, then `apt-key`. We all are used to it. 
- **Yum**: `yum-config-manager --add-repo <url>` (requires `yum-utils`), no need for key, but if we want to add it it requires to create a new file and modify the repo file. ([link](https://www.cyberciti.biz/tips/rhel5-fedora-core-add-new-yum-repository.html))
- **Brew**: `brew tag <user/repo> <url>`, and nothing about key. Then you use `user/repo` to install a package from it... so client need to know the name for the repo in order to name the package properly ⚠️ 
- **Pkg**: I'm still looking for something related to 3rd-party repositories 👀 
- **PkgUtil**: instead of adding a repo, it is recomended to `pkgutil -t <url> -i <package>`, I suppose you can modify the `/opt/csw/etc/pkgutil.conf` and get the same effect.
- **Chocolatey**: you can add a repo, but also you can invoke the `install` command with a `-s <url>` parameter. ([link](https://github.com/chocolatey/choco/wiki/CommandsSources))
- **Pacman**: requires modification of `mirrorlist` file ([link](https://wiki.archlinux.org/index.php/Pacman#Repositories_and_mirrors)), order of repos matters, alternatively you can pass a fully qualified name for the package in `install` command.
- **Zypper**: repos can be added, but packages can be installed from external sources if the full url is provided. ([link](https://www.thegeekstuff.com/2015/04/zypper-examples/))

----

We can address this specific issue for the AptTool, but if we want to go for a general solution we need to think about it, list more use cases and provide a more generic interface. Some ideas to consider: 
- provide a list of tuples in `SystemPackageTool::install` function so each package is retrieved from the proper repo `[(repo-or-None, package-name), (repo-or-None, package-name), ...]`
- clean added repo after installing corresponding package
- differentiate between packages required to compile and those required to run the library; cleaning the first group after `conan build ...` would be desirable.

**Comment by memsharded** [comment]
Good research @jgsogo 

If it looks like doable for a significant number of systems, then I wouldn't mind to add a add_repository functionality to those that is straightforward and have a default generic implementation that raises an Exception saying that for that package type that is not implemented, and implement it when requested.

Installing with a list of tuples, as long as it doesn't break existing usage, could be a possibility. On the other hand, differentiating packages only required for build and cleaning them afterwards, seems a bit risky. Any bug or mistake could remove packages installed by the user, which would be very annoying. It seems that there is no strong usage evidence to implement this feature.

**Comment by jgsogo** [comment]
If we walk this way I think is more stable a solution like the list of tuples, I'm not sure that in the long run every tool could adopt the `add_repository` + `install` approach.

So we can change signature (backwards compatible) of `SystemPackageTool::install` from

```python
def install(self, packages, update=True, force=False):
```
where `packages` is a list of strings or just a single string, to something like:

```python
def install(self, packages, repo_keys=None, update=True, force=False):
```
where `packages` can be:
- single string: just one package from already installed repos
- list of strings: several packages from installed repos
- list of pairs (repo-id or None, package or list of packages): first install packages without repo, then each package from the specified repo.

and the information for the repos comes in the parameter `repo_info`, a dictionary with repo-url, repo-key, .... and whatever is needed. 

Let's ping @lasote, what do you think?

**Comment by lasote** [comment]
My opinion:

- Great investigation.
- Never clean system stuff.
- Implement a very basic version for apt as @bryceschober suggested, with an `add_repository`. Raise for the rest of the types.
- If at some point someone requires another type of package manager, consider using tuples in the install in a backward compatible way.
- If one of the future implementations doesn't support `add_repository + install` and someone requires it, we will manage.
