### ISSUE TITLE
[workspaces] Packages are not detected as local/development

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#3403]
Hello,

When using `conan install .. -if=.` in a Conan workspace, Conan detects the packages as being installed/consumed, which is not the case.

Furthermore, `self.develop` is `False`, while `self.in_local_cache` is `True`. I would expect the opposite to be correct.

I'm using Conan 1.6.1 on macOS High Sierra

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by puetzk** [comment]
Just a vote/report that I'm seeing this as well, on conan 1.8.4

I have a packages with options that enable extra requirements/API for an extended testsuite (these options should not be enabled for an released/exported package, and are therefore removed in config_options unless self.develop and not self.in_local_cache. This bug means those options also get removed when it's set up in a workspace, even for the root package (which ought to be completely the normal local-development flow, just with its dependencies pointed at other local builds).

Which is a bit annoying, because having several packages opened for local development is precisely when the extra test/experimentation harness would be handy...
