### ISSUE TITLE
[question] Conan on windows without short paths  

### ISSUE THREAD

**Issue by beuckbj** [conan-io/conan#3460]
Hello,
I have the following situation. One PC with access to a needed conan artifactory. It is running on Win7. An other PC with Ubuntu, with haven't access to this artifactory. Access to the Internet is available. Now I need to download all needed on the windows Pc and transfer it to the Linux PC.
My Idea was, to sync the conan folder with Nextcloud between the both devices. But when I download all the conan packages, it creates short links on the Windows PC. Can I deactivate this feature, without access to the recipes itself? So all files in the synced folder? I am only a user, not a creator of the packages.

Or any other Idea to share the conan packages between two clients?

Thanks for advice.
Bjoern

**Comment by memsharded** [comment]
Hi @beuckbj 

Yes, the conan local cache implementation is different in different systems, so it is not possible to directly synchronize it. Furthermore there could be concurrency issues, and other filesystem specifics that could affect.

Certainly, it seems very unfortunate that the Ubuntu PC doesn't have access to the main Artifactory.

``short_paths`` are a feature that only package recipes that need it, enable it. Basically, packages which recipes use this feature, cannot be stored at all in a Windows machine, because of the path limit. If you have a modern Windows 10, use latest python > 3.6, with the Windows long paths enabled, and then, deactivate the ``short_paths`` feature with environment variable ``CONAN_USER_HOME_SHORT=None``, then you might be able to get rid of the short paths in Windows. But beware of other possible sync issues.

I think the best would be to run a local Artifactory CE in either your Windows or Ubuntu PCs. Then you use it to ``conan upload`` from Windows, and then ``conan install`` from the Ubuntu. Might be slower, and require some automation, or manually doing ``conan upload`` to the local Artifactory CE, but might be very easy to setup and painless. Artifactory CE is free, and running it locally is done double-clicking a launcher.

**Comment by memsharded** [comment]
Alternatively, send some chocolate to your devops or sysadmin, so they give access to the Artifactory to the Ubuntu PC :) :) :) :) This might be the easiest one.

**Comment by weatherhead99** [comment]
@beuckbj  is it a possible alternative to run a local conan server on one of the machines, download the packages from Artifactory, then upload them to this server, and get access to this server from your other machine? You can run it on whatever port you like, and it sounds like your other machine has some form of network access.

**Comment by beuckbj** [comment]
Hi, I discover, I had a little chance to get direct access to the main artifactory. If this is at the end not possible, I make a local atrifactory and use this.

@memsharded My local admin totally agrees with you. Chocolate has been approved as an official bribe. Too bad he had nothing to do with it.

Thank you.
