### ISSUE TITLE
[OUTPUT] Machine readable output from conan info

### ISSUE THREAD

**Issue by GeorgeScrivener** [conan-io/conan#3492]
I'm using Conan version 1.7.1 on Linux
I'm trying to create a debian from the libraries built via Conan.  For this I need to read the direct dependencies of the library I'm building, so using `conan info` seems like the right tool to use.
There's a json option, but it only works in conjunction with the `-build-order` option.  It would be very useful to extend this option to create a json file representing all the information printed by `conan info`.

I also tried using the json generator, but that returns all the dependencies not just the direct dependencies.

**Comment by danimtb** [comment]
Hi @GeorgeScrivener,

Thanks for your suggestion. Yes, we have been adding json output for the conan commands to improve the machine readability in order to make CI configuration easier.

This discussion and work has been concentrated in conan-io/conan#1895 and next natural step would be to add this output to the info command as you pointed out.

Please follow conversation there and comment with your needs. Thanks!

**Comment by danimtb** [comment]
Closing this in favor of #1895
