### ISSUE TITLE
Different behavior for --update on conan info vs conan install

### ISSUE THREAD

**Issue by jpkolbush** [conan-io/conan#3494]
Conan version 1.5.2
Os: MacOs
Compiler: apple-clang 9.0.0

Hello,

I noticed an odd discrepancy between how `conan info` and `conan install` treat --update.
Suppose I want to get the dependency information for the latest version of a package. Lets say the latest version of the package is 0.1.2, and I have 0.1.1 in my cache. If I run `conan info myPackage[~0.1.0]@demo/testing --update` then It will output the dependency information about the package in my cache (0.1.1) , rather than downloading the latest version and outputting its information.
However, if I were to run `conan install myPackage[~0.1.0]@demo/testing --update` then it would install the latest version (0.1.2).

So right now if I want to get that desired output I have to run conan install followed by a conan info, thus requiring me to install the entire package when all I need is the dependency information.

Thank You,
Jason 

To help us debug your issue please explain:

- [x ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @jpkolbush Jason,

I see what you mean. The thing is that there might be some colliding design criteria. The original idea is that ``conan info`` didn't modified or actually updated the local cache, and the ``--update`` argument served to indicate the available updates for the binaries, but not really updating them. Because updates were meant for changes in a given package with a fixed version (package overwritten). Unfortunately, this collides with the version-ranges, and the dependency graph actually needs to perform a real update of the cache to be able to process it.

Will try to have a look at this issue, not sure if it will be possible to change it without breaking. Thanks for the feedback!

**Comment by claasd** [comment]
+1 here, how about adding an --update-cache to at least allow the behavior?

**Comment by sigiesec** [comment]
Stumbled upon this again right now. It would be really great to have this to check if a conan install -u call would be successful, without requiring to transfer and store all binaries. I am trying to write a script that checks this for a larger number of configurations/conanfile.py states, and being able to use conan info would speed up these checks a lot.

**Comment by jaques-sam** [comment]
Same issue for `conan graph lock --update`

**Comment by memsharded** [comment]
Conan 2.0 has completely revamped the ``--update`` behavior for all commands, closing this ticket as outdated, please create any new tickets for any further question you might have, thanks!
