### ISSUE TITLE
Override Conan build helpers functionallity using custom code

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#3501]
To keep it in mind and start discussing possibilities.

Some way, probably using plugins, to override code or whatever of the build helpers, to consider:

- Ideally without changing conanfile.py (Call MSBuild or CMake the same way)
- If we want to use inheritance to achieve this, we would need some trick to load the user build helpers instead of the Conan ones.
- ...

**Comment by solvingj** [comment]
This feature request was in-part inspired by a situation I described regarding MSBuild helper.  Here are the details of the current dilemma. 

**Whole Program Optimization ("WPO") - Corresponds to the `/GL` compiler flag**
https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2017

One of Conan's intended use-cases is pre-compiling components as static libs for large codebases using CI services.  Compiling with WPO makes pre-compiled static libs virtually unusable in many environments, because developers obviously will be using different minor versions of Visual Studio.   Meanwhile, in many environments, for the artifacts which will be used in production, and for scenarios such as automated benchmark tests., it is a requirement that all sources be compiled with WPO enabled, because it substantially impacts the runtime performance of the application. 

There seems to be only one feasible approach for getting the benefits of Conan's pre-compilation while also meeting the requirement of compiling with WPO: 
1. Pre-compile components without WPO using Conan on CI. 
2. When recompiling the artifacts that require WPO, build all components from source using Conan's `--build all` feature. 

The current difficulty is that even with MSBuild helper, there is no way native way to control the `/GL` flag. And, since there are a massive number of other compiler flags and linker flags, it doesn't seem feasible for the current MSBuild helper to implement special handling. 

Thus, I think @lasote suggestion with this issue is that organizations may want to override the `MSBuild` helper with internal implementations that might control such flags. 

The discussion also included the fact that there are at least two ways of interacting with compiler flags which would not require custom `MSBuild` behavior. 

https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2012/kezkeayy(v=vs.110)

https://stackoverflow.com/questions/17677076/how-to-pass-linker-options-to-msbuild-via-command-line/17677604

Personally, I will be looking for a way to pass arbitrary compiler and linker flags from Conan profiles, through Conan recipes, to the compiler and linker which does not involve modification of any current Conan behaviors or code.  We might implement a generator which creates a custom props file with our flags, or simply try to model the flags we care about as package options, and instrument them using environment variables.  

However, it's likely that more robust handling and overriding is still a worthwhile objective for this ticket.

**Comment by memsharded** [comment]
New integrations have now more configuration points with new ``conf`` system. 
At this moment, completely swapping a complete build system integration with user code will not be possible, if users want that level of customization, they need to fork the recipe and use their own code (can be reused via ``python_requires``)
