### ISSUE TITLE
2 small bugs during the registration on conan.io

### ISSUE THREAD

**Issue by tim-lebedkov** [conan-io/conan#354]
1. a user name with a dash is not accepted
2. it's not possible to see the "Terms and conditions" before registering

**Comment by memsharded** [comment]
Hi!
The first one is not a bug, is a feature ;) The problem is that the user name is used in the package references, and sometimes in paths in the filesystem, and some filesystems might be problematic for non alphanumeric characters. So we decided to be conservative in the user names accepted characters. Sorry for that, I guess that you wanted to use the same github user-name.

About the second, it is true, it is a bug. We'll fix it. Meanwhile, you can read them here https://www.conan.io/terms_conditions (the link is in the page footer).

Thanks for reporting!

**Comment by lasote** [comment]
Fixed, now the terms and conditions are available. Thanks
