### ISSUE TITLE
Integrate Continuous Code Quality with Conan

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3558]
Hi!

It would be nice to integrate a linter/analyser service on Conan.

There are many cloud services as, [codeclimate](https://codeclimate.com/), [codeship](https://codeship.com), [sonarqube](https://www.sonarqube.org/), [sonarcloud](https://sonarcloud.io), [codescan](https://www.codescan.io/), [codacy](https://www.codacy.com/), ...

But only two (AFAIK) are free for open source projects:
- [codacy](https://www.codacy.com/)
- [sonarcloud](https://sonarcloud.io)

The good thing is get grade on every new PR and show that grade on readme file.

I have used Codacy on [Bincrafters Remove Outdated](https://github.com/bincrafters/bincrafters-remove-outdated/blob/master/README.md)

Also, Sonacloud runs SonarQube as a service.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
I'm not opposed to integrate one of them and try if it really helps.

**Comment by lasote** [comment]
We agree on introduce pep8 checks, but only for the added/modified files, if that is possible it could be introduced.

**Comment by lasote** [comment]
So, code climate can be triggered by a PR and update the status if failing?

**Comment by uilianries** [comment]
Yes! And it has a badge to be used in README file :heart_eyes:

**Comment by lasote** [comment]
Nice! For the next release planning I would probably add this (to be done at the very beggining of the release). I think it would be a good idea to check the rules we want to exclude based on the results you got here: https://codeclimate.com/github/uilianries/conan/issues

I would prefer to exclude them using a generic [pep8 directive at an `ini` file](https://docs.codeclimate.com/docs/pep8) rather than exclude the rules in the codeclimate interface, so we can point the community the rules we matter.

Then open a big pull request fixing the pep8 detected issues in the whole repository and start failing each pull request with pep8 errors.

I unasigned the issue because it is again in the queue (and these are our rules), but probably it will be a good idea if you do that work.

Great work investigating!

**Comment by uilianries** [comment]
Could I run `yapf` to format all code? It could help us to fix some errors. Of course, I'm gonna use 100 columns instead of 80.

> I would prefer to exclude them using a generic pep8 directive at an ini file rather than exclude the rules in the codeclimate interface, so we can point the community the rules we matter.

Good point, I think rules from pep8 are not able to be disabled by web interface, because pep8 is a plugin on that case. Only Codeclimate engine is able to customized. Anyway, is totally possible to add a .ini file with pep8 rules.
