### ISSUE TITLE
[Commands] Validate remote URL

### ISSUE THREAD

**Issue by realbigflo** [conan-io/conan#3575]
Conan version: 1.7.3

Testing conan behind a proxy let me to an error when I specified a wrong URL for my conan remote. I simply forgot to specify the protocol in the remote configuration:

`conan remote update localhost 127.0.0.1:9300`
Should have been:
`conan remote update localhost http://127.0.0.1:9300`

The wrong remote specification together with the no_proxy information:
`echo $no_proxy`
`localhost,127.0.0.1,localaddress`
 or in conan.conf below `[proxies]`
`no_proxy_match = localhost,127.0.0.1,localaddress`

I got the error:
`conan upload <test_package> -r=localhost`
`ERROR: inet_aton() argument 1 must be string, not None`

It took me a while to track down the issue to `requests.utils.should_bypass_proxies(...)` where the url `127.0.0.1:9300/v1/ping` is parsed. Of course, if the request package handles this kind of url better, there is still an error from conan:
`ERROR: No connection adapters were found for 127.0.0.1:9300/v1/ping`
The error still is not clear enough IMHO. 

I think it would be more user friendly if the remote url is validated when added or the error message should be more clear what's wrong. (In addition to the package request, which should not fail that way ;-))

**Comment by memsharded** [comment]
Hi Florian, 

Thanks for the detailed report. We need to have a look at this, because it seems a good idea, but I am also afraid about pure validation checks. There is always a chance that they throw false positives, blocking someone to add their remote because it didn't pass some validation rule, even if it is valid for they case (custom DNS, local modification to hosts addresses, etc). For those cases I usually recommend a warning, not a blocking error.

Regarding the error later in the upload, yes, we will check it, the message might be improved.

**Comment by memsharded** [comment]
Ok, lets do a warning to ``conan remote`` commands, that would be easy and might help some users that did typos on the URL.

**Comment by uilianries** [comment]
Hi @realbigflo !

This issue will be available on Conan 1.17

https://github.com/conan-io/conan/commit/b56d74faf0adbc9da3a6e6c084af3abd84f6d1e1
