### ISSUE TITLE
Use a printer to dump AST back into a conanfile.py (after substituting SCM)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#3614]
Implementation of [`_replace_scm_data_in_conanfile`](https://github.com/jgsogo/conan/blob/85a41a2a502290879721c3e585672df292a1359b/conans/client/cmd/export.py#L98) function can be (must be) improved using some PST like asttokens, astpretty,... 

Before coding we habe to agree which library to use.

**Comment by niosHD** [comment]
FYI, I already implemented rewriting scm (beneath other members) with asttokens in POC #3255. In my manual testing and on the CI server on all platforms asttokens worked nicely. However, the POC was abandoned because it was considered too complex. Anyway, if you find anything useful in the PR, feel free to reuse any code.

**Comment by jgsogo** [comment]
Thanks! Now the logic to make the replacement is complex/ugly enough to need this refactor. Feel free to address again this issue, if not, I'm sure that the one who works on this will take great benefit from your code.

**Comment by memsharded** [comment]
``scm`` and modifying ``conanfile.py`` long time discouraged, and ``scm`` removed in 2.0, closing as outdated
