### ISSUE TITLE
Deleting a setting in a profile?

### ISSUE THREAD

**Issue by leohahn** [conan-io/conan#3652]
Is it possible to add a feature of deleting a setting in a profile? The reason for it is that for example, in Android, I do not use the setting `compiler.version`, since I always use `clang` and its version is dependent on the NDK. Because of that, any package that uses the android profile has to include this snippet of code, which is verbose and error prone:

```python
def configure(self):
    if self.settings.os == 'Android':
        del self.settings.compiler.version
```

By allowing a syntax such as `del settings.compiler.version` in the profile for example, such snippet could be avoided.

**Comment by memsharded** [comment]
Checking old issues. This issue was never responded, sorry for that.
This hasn't been apparently a problem for any other users, and there are many using Android. I haven't seen any recipes removing the version that way, I don't think that is the right approach, but just define the version number, as provided by the NDK. It is not that the version number doesn't exist, it exists and it has to be defined. If necessary extra logic can be put in profiles via jinja templates, or in Conan 2.0 with the "profile plugin".

Closing this, most likely not an issue anymore, but let us know
