### ISSUE TITLE
How to specify option of required packages in conanfile.py

### ISSUE THREAD

**Issue by frederikvannoote** [conan-io/conan#3663]
Library B has a conanfile.py where is referred to a Library A as a requirement.
This is a snippet from this conanfile.py:
```
requires = (
        "librarya/1.2.3@channel/user"
)
```

Library A has some options: exceptions, shared, ...

How can I specify these options of library A in the conanfile.py?

More info: I'm using conan 1.7.3

**Comment by uilianries** [comment]
Hi @frederikvannoote !

You could use `default_options` or `requirements` for that.

Using `default_options` you will be forcing some options from library:

```python
class LibraryB(conanfile):
    requires = "librarya/1.2.3@channel/user"
    default_options = "librarya:shared=True"
```

But if you are looking for conditional options, `requirements` is the best option:

```python
def requirements(self):
     self.options["librarya"].shared = platform.system() == "Linux"
```

Reference: https://docs.conan.io/en/latest/mastering/conditional.html

Regards!

**Comment by memsharded** [comment]
Thanks @uilianries !

Just a quick note: When you are using ``configure()`` method, the "options" are being hardcoded. That means, their value is fixed, and cannot be overriden/defined from downstream consumers. If there is conflict somewhere in the graph, because of diamonds, then it might be impossible to fix the conflict without modifying recipes. In that sense, it is better in general to use the ``default_options``, unless there is no chance that such package will work with those other options values.

**Comment by uilianries** [comment]
Thank you @memsharded !

**Comment by frederikvannoote** [comment]
Thank you. Works like a charm
