### ISSUE TITLE
conan info graph output to html should include local versions of vis library

### ISSUE THREAD

**Issue by chrahunt** [conan-io/conan#3667]
Conan version: 1.7.4

When running `conan info -g foo.html .` to generate a dependency graph, the generated HTML includes hard-coded links to cdnjs for `vis.min.js` and `vis.min.css`:

```html
<head>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.18.1/vis.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.18.1/vis.min.css" rel="stylesheet" type="text/css" />
</head>
```

In a corporate environment users may not have access to these URLs so the generated file is not useful. It would be nice if we could package these files in conan itself and output them alongside the generated html file if requested (via command-line flag, for example).

---

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @chrahunt 

I have submitted a PR https://github.com/conan-io/conan/pull/4133 for this.
The problem is embedding the vis library resources, it is more problematic than it should be (taking into account also the different ways conan is distributed). So I have proposed to workaround it by letting users provide their own vis.js resources in the local conan cache, so they can be installed with ``conan config install``
