### ISSUE TITLE
scm: use ssh link instead of http link

### ISSUE THREAD

**Issue by sunj1** [conan-io/conan#3688]
- I'm using scm feature
- When building packages from sources, conan does a git clone using the _**http link**_ of the repository
- I am using `url` field as `auto` in scm
- I would like to use _**ssh link**_ to do git clone (since I have ssh-keys added to git profile)

Please suggest how to go about it.
Thanks.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Yes, the user can always explicitly define the ``url`` field to whatever they want, and put ``auto`` in the revision field.

If ``url=="auto"``, then I think it makes sense to get the current remote for ``origin``, as the user defined it, I don't think any conversion would be the right thing to do here, don't you think?

**Comment by sunj1** [comment]
Yes, you are correct, and it seems to be the best default behavior.

But it would be helpful if there is an option available, since it would aid in CI pipelines, without having to care which way individual developer prefers to use git.

Please feel free to close the issue if this optional behavior does not fit in :-)

**Comment by memsharded** [comment]
If it is the CI the one building the packages, the way that the developers are using it shouldn't be a problem. The CI would have cloned the thing with the ``origin`` it wants to use, and that will be the one captured in the SCM field of the packages. It is not the developer who writes the recipe the one that defines the value, but the system building the package (CI). Am I missing something in your use case? :)

**Comment by sunj1** [comment]
My use-case:

- Lib-A
  - Developer uses http link to clone git
  - scm attribute has `url` set to `auto`
  - conan export uses this http-link url in recipe and it is uploaded to conan server

- LibB
  - It depends on Lib-A
  - It is built using gitlab runner on another machine (inside CI)
  - When it is required, it builds Lib-A from sources and tries to use http-link (which requires username and password to be provided)

**Comment by memsharded** [comment]
Ok, thanks I think that I understand it now. I also think that the described flow might not be the best approach. From what I have seen from most users is that developers either they are not allowed to upload packages to the server, and if they do, they should do the right thing, so LibA developer should provide the right ssh origin. They can do many other mistakes, and it is impossible to protect against all them. Here I like the "python zen" and "treat developers as adults" :)

Then, LibB, by default shouldn't be building A from sources. The recommended default is that packages for LibA should be already there, otherwise it is an error.

So in my opinion, yes, I think this feature would be too much of added complexity to conan codebase, to protect against one flow that seems to be not very recommended. Specially because there could be other scenarios that could be broken. What if someone is using http, explicitly and want to maintain that, because other developers won't have access to that code? There are other derivative errors and weird corner cases that could be raised by this feature.

So yes, I think I am going to close this issue, thanks very much for the feedback!
