### ISSUE TITLE
Error with "conan info" and v1.8.0

### ISSUE THREAD

**Issue by fpelliccioni** [conan-io/conan#3697]
Hello!

I have an issue with the newest version, v1.8.0:

To reproduce, please execute the following steps:

```
# Common steps
# --------------------------------------------------------

$ git clone https://github.com/bitprim/bitprim-core.git
$ cd bitprim-core
$ git checkout dev
$ git submodule init
$ git submodule update


# Using conan v1.7.4 (Everything is OK using this version)
# --------------------------------------------------------

$ pip install conan==1.7.4 --user

$ conan --version
    Conan version 1.7.4

$ conan info . --only requires -s compiler=gcc -s compiler.version=5 -s compiler.libcxx=libstdc++

    PROJECT: Detected microarchitecture (default): x86-64
    PROJECT: Compiling for currency: BCH
    boost/1.66.0@bitprim/stable: def config_options(self):
    boost/1.66.0@bitprim/stable: def configure(self):
    boost/1.66.0@bitprim/stable: def requirements(self):
    secp256k1/0.X@bitprim/staging: Not found in local cache, looking in remotes...
    secp256k1/0.X@bitprim/staging: Trying with 'conan-center'...
    secp256k1/0.X@bitprim/staging: Trying with 'bitprim'...
    Downloading conanmanifest.txt
    [==================================================] 58B/58B          
    Downloading conanfile.py
    [==================================================] 110B/110B        
    secp256k1/0.7.0@bitprim/staging: Provided microarchitecture (user defined): x86-64
    gmp/6.1.2@bitprim/stable: Provided microarchitecture (user defined): x86-64
    gmp/6.1.2@bitprim/stable: Corrected microarchitecture: x86_64
    Downloading conaninfo.txt
    [==================================================] 678B/678B        
    Downloading conaninfo.txt

    Downloading conaninfo.txt

    Downloading conaninfo.txt
    [==================================================] 580B/580B        
    PROJECT
        Requires:
            boost/1.66.0@bitprim/stable
            secp256k1/0.7.0@bitprim/staging
    boost/1.66.0@bitprim/stable
        Requires:
            icu/60.2@bitprim/stable
    gmp/6.1.2@bitprim/stable
    icu/60.2@bitprim/stable
    secp256k1/0.7.0@bitprim/staging
        Requires:
            gmp/6.1.2@bitprim/stable


# Using conan v1.8.0 (Something was broken)
# --------------------------------------------------------

# Remove the conan cache

$  pip install conan --user --upgrade

$  conan --version
    Conan version 1.8.0

$  conan info . --only requires -s compiler=gcc -s compiler.version=5 -s compiler.libcxx=libstdc++

    ROJECT: Detected microarchitecture (default): x86-64
    PROJECT: Compiling for currency: BCH
    ERROR: PROJECT: Error in requirements() method, line 83
        self.requires("secp256k1/0.X@%s/%s" % (self.user, self.channel))
        AttributeError: 'BitprimCoreConan' object has no attribute '_user'

```

Thanks and regards,

**Comment by uilianries** [comment]
Seems related to https://github.com/conan-io/conan/pull/3560

**Comment by memsharded** [comment]
Yes, seems a bug, thanks for reporting @fpelliccioni !
Will investigate it asap, and release a fix in 1.8.1 if it is really a bug.

**Comment by jgsogo** [comment]
As @uilianries says it is related to #3560, but the error is originated in the code that the bitprim-core package is using.

@fpelliccioni I see that you have overriden the method ``Conanfile::user`` here (https://github.com/bitprim/bitprim-ci-utils/blob/ee84ffbfac5b529f24ff921780dfa3cb351d3aab/utils.py#L1106), now we have renamed the internal member ``conanfile::_user`` to ``conanfile::_conan_user`` following the [guides in the docs](https://docs.conan.io/en/latest/reference/conanfile.html#conanfile-py) (new in v1.8).

Changing your implementation to something like:

```python
class BitprimConanFile(ConanFile):
    ...
    @property
    def user(self):
        if not self._conan_user:
            self._conan_user = os.getenv("CONAN_USERNAME")
            if not self._conan_user:
                self._conan_user = get_user()
            if not self._conan_user:
                raise ConanException("CONAN_USERNAME environment variable not defined, "
                                     "but self.user is used in conanfile")
        return self._conan_user

```

(same with ``ConanFile::channel`` or any other internal variable being used there)

----

Nevertheless I will go for a more pythonic implementation, so you won't rely on internal variables:

```python
class BitprimConanFile(ConanFile):
    ...
    @property
    def user(self):
        try:
            return super(BitprimConanFile, self).user
        except ConanException:
            # Implement the fallback behavior
            return get_user()
```

**Comment by jgsogo** [comment]
@fpelliccioni, is there anything we can do for you? shall we help you with the ``BitprimConanFile`` class? 🙋‍♂️

**Comment by fpelliccioni** [comment]
> @fpelliccioni, is there anything we can do for you? shall we help you with the `BitprimConanFile` class?

Don't worry, we will do it!
Thank you very much for your help!

**Comment by Aalmann** [comment]
Hi @memsharded and @lasote

renaming is/was a very bad idea. Of course, `self._user` and `self._channel` are "private", but we use them in a lot of recipes to make sure that the same user-name and channel is referenced. And this was only required because of the ConanException which is thrown if no user (e.g. when running conan create) or the env var is set. But the `user` and `channel` properties are not always set when running conan (e.g. when working locally as package developer). And not all developers set env variables for that. And it's hard to tell them to do so ("you have to set CONAN_USER and CONAN_CHANNEL only when using conan commands A,B,C but not when running X,Y,Z.")

This will break a lot of our recipes. :-1:

**Comment by lasote** [comment]
My opinion: if there is a need for a better public interface we must implement it, even we can try to do it in a patch version. But your recipes are "hacked" right now and they should be fixed. Of course, I want you to not have this issue again, so the way to go is to release a Conan version that gets rid of the need to access either "_user" and "_channel" and any other private attribute and then patch your recipes.

**Comment by Aalmann** [comment]
Yes of course it's a hack, but required to fit all use cases when using conan as creator and developer. I planned to switch to `python_requires` the next weeks and using the SVN feature of 1.8. Now I have to do and check a lot of other things. Btw currently you only have renamed the private attribute and leave the public property unchanged due to compatibility. So the renaming has no useful effect. It's just for you to have a conan prefix for a private attribute within the `ConanFile` class in `conans` package. What I want to say is, the renaming was not really required and useful because you still have the public one with the simple `user` and `channel` naming. 
You also renamed parameter in API methods like `remote` to `remote_name` in `search_package`. 

It would be very nice to have a stable api in 1.x.
