### ISSUE TITLE
Global installs

### ISSUE THREAD

**Issue by paulobrizolara** [conan-io/conan#372]
I have been thinking if would be possible to conan have a 'global install' option, similar to npm '-g'.

This would be nice to enable developers to publish tools in conan, or even any kind of program.
Also, this could allow use conan as a cross platform installer to c/c++ programs (i believe that do not exist one currently).  

I don't know how npm (or pip) handle global installs. But i had seen that, in Linux, some programs installed with those tools are copied to or linked from some system path (/usr/local/bin in my case).   

I don't know if there are some problems related to this, but i think that could be a nice feature to conan.

**Comment by memsharded** [comment]
Well, we are working in something very related: https://github.com/conan-io/conan/pull/370

This allows to install tools, the problem aroused while dealing with some MinGW configurations. It will not be a -g option, or global in any sense, as we think it is a bad practice. It will install tools in the conan local cache and define virtualenvs, similar to those in python, so you can easily change between different versions of tools, i.e. you can switch between mingw 4.8 and 4.9 and cmake 2.8.12 and cmake 3.5, just by switching the virtualenv. Using global installations means to mess in the the system path, which is not a good idea. Of course if someone wants to add some installed tool to the path, they can easily do it, but conan will not do it by default.

We are working to release it in next release 0.11, keep tuned :)

**Comment by paulobrizolara** [comment]
That will be very nice!

However, the advantage of a 'global' mechanism is that users does not need to enter a virtualenv to use a tool or program.
Conan itself is installed by pip like a global tool.

But i totally agree that it should not be a default behaviour. A user would need explicitly specify that a program will be installed globally. For example:

           conan install -g mytool/version@user/channel

And so, i could use it like

          mytool ...

What do you think?

**Comment by memsharded** [comment]
Actually, the default way to install conan would be in a python virtualenv. It is recommended in the installation guide: http://docs.conan.io/en/latest/installation.html. Not just for conan, but for anything python related. I cannot conceive any serious python development without using virtualenvs.

I would say that this should be the same for any other languages. Having dev tools installed globally can be a problem, especially if you want to test your code under different compilers and tools. 

In any case, let's release this feature, making it global is just adding the paths that are being added to the virtual env to the system path, so it will be easy to implement. Let's release and get the users feedback, and if still wanted (I believe users will love the virtualenvs), it could be made for next release. This is just my opinion, maybe @lasote, the author of this feature, thinks different.

Thanks very much for your feedback!

**Comment by lasote** [comment]
I think it can be tricky. We could easily make symbolic links to /usr/local/bin in linux (and even osx solving some issue with brew) but in windows it's not possible.
In addition to this, several conan commands will need to handle the "unlink" when a package is removed, or maybe updated etc. It adds a lot of complexity.

A simpler approach could be use the new feature coming, the virtualenv generator, and copy the lines in the ~/.bashrc file to execute those lines in every opened shell. You would have the reponsability of manage those lines and to keep the packages with your tools.

I don't think a global install is always a bad idea, but I agree with @memsharded that we would test the new feature first and get feedback from users, then maybe continue thinking about this issue.

**Comment by paulobrizolara** [comment]
Yeah, i think that adapting the virtualenvs feature (on the future, if possible and not harmful) to allow some tools and applications to be accessed "globally" (without needing to explicitly enter a virtualenv) would totally solve the question.

I keep dreaming use conan to also run/install and deploy some tools and applications (like pip or npm).
But i don't know if this is out of conan's scope.

Anyway, i will be waiting for those virtualenvs! I think that they will be great.

Thanks, guys!

**Comment by memsharded** [comment]
Hi @paulobrizolara ,

The feature has been released in 0.11. Check: http://docs.conan.io/en/latest/integrations/virtualenv.html
and http://docs.conan.io/en/latest/howtos/create_installer_packages.html

I think that it mostly address the issue of installing tools, and still think that messing with the system path could be problematic, so I am closing this issue. But please, try it, and if you still think it is needed, open a more specific issue, like "set system paths in virtualenv" or "instead of virtualenvs", and we will analyze it and see what could be done. 

Thank you!

**Comment by paulobrizolara** [comment]
Nice!

I will take a look on it.
If needed, i will try to look into the code and do a pull request (or ask for help in that).

Thanks!

**Comment by vkotovv** [comment]
@memsharded it looks like the link you've posted moved to http://conanio.readthedocs.io/en/latest/mastering/virtualenv.html

**Comment by vkotovv** [comment]
@memsharded @lasote how do I use Conan if I'm trying to deploy my software via it? Lets say I've created binary packages and would like to install them globally, so the tools I'm providing will be available for end users in `/usr/local/bin`, similar to Linux package managers. Not sure virtualenvs are suitable here, if end users just want to have binaries in their $PATH after installing via Conan.. Could you please advise?

**Comment by memsharded** [comment]
Yes, that is true. This issue was closed last August, a lot of development has been done since then, also the docs have suffered huge changes.

Regarding the deploy issue, conan is mainly focused on development. The user can build their applications and "imports" all shared libraries, binaries and data from the local conan package cache, i.e. to copy them to a user folder. From there, deploy is responsibility of the user, some will create .deb packages, or .exe autoinstallers in Win, or just copy them to somewhere in the filesystem and add them to the path. Deploy methods are very different and a bit out of the conan scope, so there are no explicit functionality for that.

However, this is a recurrent issue, in fact there might be some open issue, like this one: https://github.com/conan-io/conan/issues/1061. I suggest commenting there. Maybe it is time to start considering some standards ways to deploy apps, or to provide some helpers. Not sure about the approach or tools, ideas welcome, thanks for your feedback!

**Comment by vkotovv** [comment]
Thanks for the clarifications! For now I'm try to stick with `imports` feature.
