### ISSUE TITLE
[Question] Is tools.collect_libs() recommended?

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#3829]
I see a lot of examples of conanfile.py recipes out there which manually hardcode the list of ```cpp_info.libs```

e.g.:

https://github.com/conan-community/conan-zlib/blob/release/1.2.11/conanfile.py#L143
https://github.com/conan-community/conan-openssl/blob/release/1.1.1/conanfile.py#L332
https://github.com/grpc/grpc/issues/15363#issuecomment-389168642
https://github.com/bincrafters/conan-libcurl/blob/stable/7.61.1/conanfile.py#L169

whereas a few use ```tools.collect_libs(self)```:

e.g. 

https://github.com/conan-community/conan-boost/blob/release/1.68.0/conanfile.py#L375

What are the pros and cons of using ```collect_libs()```? What situations warrant manually populating that list instead of relying on an (arguably less brittle) tool do do so?

Thanks!

To help us debug your issue please explain:
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [Conan version 1.5.2, Windows Server 2012] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
IMO it is just a handy tool to get library names when those depend on arguments like options, configuration,... more or less what it is [documented](https://docs.conan.io/en/latest/reference/tools.html#tools-collect-libs):

> Useful to collect not inter-dependent libraries or with complex names like `libmylib-x86-debug-en.lib`

It comes to my mind library naming of [boost](https://stackoverflow.com/questions/2715164/how-can-i-decode-the-boost-library-naming) or [QuantLib](https://github.com/lballabio/QuantLib/blob/master/cmake/quantlib.cmake), where you would need to write several `if/else` clauses.

On the other hand, it is dangerous if the same `build` call generates different configurations/options with different names, because `collect_libs` will found all of them and add to the list more libraries than needed.

**Comment by jgsogo** [comment]
I'm closing this. In case there is a some more doubts, please open it again.

Thanks!
