### ISSUE TITLE
conan cmake will invalidate the old project test

### ISSUE THREAD

**Issue by calidion** [conan-io/conan#3873]
I want to add conan support to my project, but to found it will break my original test settings.

where you can found my cmakelist here:

https://github.com/vigcoin/coin/blob/master/CMakeLists.txt

i currently put to code to the end to ignore conan modules.

you can move it up and execute 

```
./build-debug.sh
```

to see what will happen under ubuntu 16.04.

**Comment by memsharded** [comment]
Hi @calidion 

Typically the lines:
```cmake
# Adding conan support
include(${CMAKE_SOURCE_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```
Should go very early in the project. Otherwise, the information of dependencies won't be used at all in the build, and it will result in build errors. Also, it is not enough to do ``conan_basic_setup()``, but it is also necesssary to do something like:
```cmake
target_link_libraries(mytarget ${CONAN_LIBS})
```
As described in the conan docs.

If doing that makes your previous CMakeLists.txt to break, you might want to research why, and if any, post that use case here in github, copying the platform (os, compiler, version, conan-version, etc), copying the console output, etc. You might also try to build the minimum test-case possible, trying to reproduce the issue with a clean "hello-world" simple project, really helps to report and get issues fixed. Thanks!

**Comment by calidion** [comment]
@memsharded 

this is the mininal workable script attached conan.
I have tested adding these instructions to the top of the project, but it won't work.
And also ${CONAN_LIBS} in target_link_libraries function.

I managed to compiler all src modules and tests.
But the tests could not be found.

**Comment by memsharded** [comment]
Hi!

I am trying to build that (Ubuntu 18), but executing the ``build_debug.sh`` fails:

```
CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost&apos;s headers.
Call Stack (most recent call first):
  CMakeLists.txt:125 (find_package)


CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenSSL.cmake:390 (find_package_handle_standard_args)
  CMakeLists.txt:126 (find_package)


-- Configuring incomplete, errors occurred!
```
This happens even if I remove the Conan lines at the end.

This is why I am suggesting to use what is know as a minimal reproducible case. The simplest possible set of files: CMakeLists.txt (usually it is with a "Hello world" library, *hello.cpp*, *hello.h*), with the exact steps to reproduce. Not a full project one with so many things, it makes testing and debugging very complicated for the maintainers.

Also, it is very confusing for me, because the ``conanfile.txt`` actually has NO dependencies declared, so I guess this is something that happens even before trying to pull conan dependencies, and some interaction of the ``conan_basic_setup()`` might be affecting you (like the definition of output directories which can be opted-out with NO_OUTPUT_DIRS). Just trying to guess.

**Comment by calidion** [comment]
18.04 is not supported.
please try with 16.04 .

**Comment by memsharded** [comment]
I don't have a 16.04 right now. This is one of the reasons it is important to produce something minimal, that will likely work in different platforms and contexts.

**Comment by calidion** [comment]
Ubuntu 18.04 and 16.04 is totally different because gcc  and cmake are of different versions. 
conan should support multiple platform with different gcc cmake versions,  if it want to be a real useful package management.

it may have nothing to do with ubuntu, but have relationship with different versions of gcc and/ or cmake.

**Comment by calidion** [comment]
18.04 with gcc7
where 16.04 with gcc5.

**Comment by calidion** [comment]
your problem seems that you don't have packages installed.

please try:

```
sudo apt update && sudo apt install -y build-essential cmake libboost-all-dev libssl-dev libsodium-dev python-pip python-dev lcov
```

**Comment by calidion** [comment]
move up conan to:

```
# Adding conan support
include(${CMAKE_SOURCE_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_subdirectory(external)
add_subdirectory(src)
add_subdirectory(tests)

```

result in no tests found:
```
[100%] Built target PerformanceTests
Running tests...
Test project /Users/eric/Documents/coin/build
      Start  1: BlockTests
Could not find executable block_tests
Looked in the following places:
block_tests
block_tests
Release/block_tests
Release/block_tests
Debug/block_tests
Debug/block_tests
MinSizeRel/block_tests
MinSizeRel/block_tests
RelWithDebInfo/block_tests
RelWithDebInfo/block_tests
Deployment/block_tests
Deployment/block_tests
Development/block_tests
Development/block_tests
Unable to find executable: block_tests
 1/14 Test  #1: BlockTests .......................***Not Run   0.00 sec
      Start  2: CliTests
Could not find executable cli_tests
Looked in the following places:
cli_tests
cli_tests
Release/cli_tests
Release/cli_tests
Debug/cli_tests
Debug/cli_tests
MinSizeRel/cli_tests
MinSizeRel/cli_tests
RelWithDebInfo/cli_tests
RelWithDebInfo/cli_tests
Deployment/cli_tests
Deployment/cli_tests
Development/cli_tests
Development/cli_tests
Unable to find executable: cli_tests
 2/14 Test  #2: CliTests .........................***Not Run   0.00 sec
      Start  3: AccountTests
Could not find executable account_tests
Looked in the following places:
account_tests
account_tests
Release/account_tests
Release/account_tests
Debug/account_tests
Debug/account_tests
MinSizeRel/account_tests
MinSizeRel/account_tests
RelWithDebInfo/account_tests
RelWithDebInfo/account_tests
Deployment/account_tests
Deployment/account_tests
Development/account_tests
Development/account_tests
Unable to find executable: account_tests
 3/14 Test  #3: AccountTests .....................***Not Run   0.00 sec
      Start  4: DifficultyTests
Could not find executable difficulty_tests
Looked in the following places:
difficulty_tests
difficulty_tests
Release/difficulty_tests
Release/difficulty_tests
Debug/difficulty_tests
Debug/difficulty_tests
MinSizeRel/difficulty_tests
MinSizeRel/difficulty_tests
RelWithDebInfo/difficulty_tests
RelWithDebInfo/difficulty_tests
Deployment/difficulty_tests
Deployment/difficulty_tests
Development/difficulty_tests
Development/difficulty_tests
Unable to find executable: difficulty_tests
 4/14 Test  #4: DifficultyTests ..................***Not Run   0.00 sec
      Start  5: hash-fast
Could not find executable hash_tests
Looked in the following places:
hash_tests
hash_tests
Release/hash_tests
Release/hash_tests
Debug/hash_tests
Debug/hash_tests
MinSizeRel/hash_tests
MinSizeRel/hash_tests
RelWithDebInfo/hash_tests
RelWithDebInfo/hash_tests
Deployment/hash_tests
Deployment/hash_tests
Development/hash_tests
Development/hash_tests
Unable to find executable: hash_tests
 5/14 Test  #5: hash-fast ........................***Not Run   0.00 sec
      Start  6: hash-slow
Could not find executable hash_tests
Looked in the following places:
hash_tests
hash_tests
Release/hash_tests
Release/hash_tests
Debug/hash_tests
Debug/hash_tests
MinSizeRel/hash_tests
MinSizeRel/hash_tests
RelWithDebInfo/hash_tests
RelWithDebInfo/hash_tests
Deployment/hash_tests
Deployment/hash_tests
Development/hash_tests
Development/hash_tests
Unable to find executable: hash_tests
 6/14 Test  #6: hash-slow ........................***Not Run   0.00 sec
      Start  7: hash-tree
Could not find executable hash_tests
Looked in the following places:
hash_tests
hash_tests
Release/hash_tests
Release/hash_tests
Debug/hash_tests
Debug/hash_tests
MinSizeRel/hash_tests
MinSizeRel/hash_tests
RelWithDebInfo/hash_tests
RelWithDebInfo/hash_tests
Deployment/hash_tests
Deployment/hash_tests
Development/hash_tests
Development/hash_tests
Unable to find executable: hash_tests
 7/14 Test  #7: hash-tree ........................***Not Run   0.00 sec
      Start  8: hash-extra-blake
Could not find executable hash_tests
Looked in the following places:
hash_tests
hash_tests
Release/hash_tests
Release/hash_tests
Debug/hash_tests
Debug/hash_tests
MinSizeRel/hash_tests
MinSizeRel/hash_tests
RelWithDebInfo/hash_tests
RelWithDebInfo/hash_tests
Deployment/hash_tests
Deployment/hash_tests
Development/hash_tests
Development/hash_tests
Unable to find executable: hash_tests
 8/14 Test  #8: hash-extra-blake .................***Not Run   0.00 sec
      Start  9: hash-extra-groestl
Could not find executable hash_tests
Looked in the following places:
hash_tests
hash_tests
Release/hash_tests
Release/hash_tests
Debug/hash_tests
Debug/hash_tests
MinSizeRel/hash_tests
MinSizeRel/hash_tests
RelWithDebInfo/hash_tests
RelWithDebInfo/hash_tests
Deployment/hash_tests
Deployment/hash_tests
Development/hash_tests
Development/hash_tests
Unable to find executable: hash_tests
 9/14 Test  #9: hash-extra-groestl ...............***Not Run   0.00 sec
      Start 10: hash-extra-jh
Could not find executable hash_tests
Looked in the following places:
hash_tests
hash_tests
Release/hash_tests
Release/hash_tests
Debug/hash_tests
Debug/hash_tests
MinSizeRel/hash_tests
MinSizeRel/hash_tests
RelWithDebInfo/hash_tests
RelWithDebInfo/hash_tests
Deployment/hash_tests
Deployment/hash_tests
Development/hash_tests
Development/hash_tests
Unable to find executable: hash_tests
10/14 Test #10: hash-extra-jh ....................***Not Run   0.00 sec
      Start 11: hash-extra-skein
Could not find executable hash_tests
Looked in the following places:
hash_tests
hash_tests
Release/hash_tests
Release/hash_tests
Debug/hash_tests
Debug/hash_tests
MinSizeRel/hash_tests
MinSizeRel/hash_tests
RelWithDebInfo/hash_tests
RelWithDebInfo/hash_tests
Deployment/hash_tests
Deployment/hash_tests
Development/hash_tests
Development/hash_tests
Unable to find executable: hash_tests
11/14 Test #11: hash-extra-skein .................***Not Run   0.00 sec
      Start 12: HashTargetTests
Could not find executable hash_target_tests
Looked in the following places:
hash_target_tests
hash_target_tests
Release/hash_target_tests
Release/hash_target_tests
Debug/hash_target_tests
Debug/hash_target_tests
MinSizeRel/hash_target_tests
MinSizeRel/hash_target_tests
RelWithDebInfo/hash_target_tests
RelWithDebInfo/hash_target_tests
Deployment/hash_target_tests
Deployment/hash_target_tests
Development/hash_target_tests
Development/hash_target_tests
Unable to find executable: hash_target_tests
12/14 Test #12: HashTargetTests ..................***Not Run   0.00 sec
      Start 13: SystemTests
Could not find executable system_tests
Looked in the following places:
system_tests
system_tests
Release/system_tests
Release/system_tests
Debug/system_tests
Debug/system_tests
MinSizeRel/system_tests
MinSizeRel/system_tests
RelWithDebInfo/system_tests
RelWithDebInfo/system_tests
Deployment/system_tests
Deployment/system_tests
Development/system_tests
Development/system_tests
Unable to find executable: system_tests
13/14 Test #13: SystemTests ......................***Not Run   0.00 sec
      Start 14: UnitTests
Could not find executable unit_tests
Looked in the following places:
unit_tests
unit_tests
Release/unit_tests
Release/unit_tests
Debug/unit_tests
Debug/unit_tests
MinSizeRel/unit_tests
MinSizeRel/unit_tests
RelWithDebInfo/unit_tests
RelWithDebInfo/unit_tests
Deployment/unit_tests
Deployment/unit_tests
Development/unit_tests
Development/unit_tests
Unable to find executable: unit_tests
14/14 Test #14: UnitTests ........................***Not Run   0.00 sec

0% tests passed, 14 tests failed out of 14

Total Test time (real) =   0.03 sec

The following tests FAILED:
	  1 - BlockTests (Not Run)
	  2 - CliTests (Not Run)
	  3 - AccountTests (Not Run)
	  4 - DifficultyTests (Not Run)
	  5 - hash-fast (Not Run)
	  6 - hash-slow (Not Run)
	  7 - hash-tree (Not Run)
	  8 - hash-extra-blake (Not Run)
	  9 - hash-extra-groestl (Not Run)
	 10 - hash-extra-jh (Not Run)
	 11 - hash-extra-skein (Not Run)
	 12 - HashTargetTests (Not Run)
	 13 - SystemTests (Not Run)
	 14 - UnitTests (Not Run)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by calidion** [comment]
back to the end, 
```
add_subdirectory(external)
add_subdirectory(src)
add_subdirectory(tests)

# Adding conan support
include(${CMAKE_SOURCE_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```

the result is:

```
[100%] Built target SystemTests
Running tests...
Test project /home/eric/vigcoin/coin/build
      Start  1: BlockTests
 1/14 Test  #1: BlockTests .......................   Passed    0.01 sec
      Start  2: CliTests
 2/14 Test  #2: CliTests .........................   Passed    0.01 sec
      Start  3: AccountTests
 3/14 Test  #3: AccountTests .....................   Passed    0.00 sec
      Start  4: DifficultyTests
 4/14 Test  #4: DifficultyTests ..................   Passed    0.02 sec
      Start  5: hash-fast
 5/14 Test  #5: hash-fast ........................   Passed    0.01 sec
      Start  6: hash-slow
 6/14 Test  #6: hash-slow ........................   Passed    0.13 sec
      Start  7: hash-tree
 7/14 Test  #7: hash-tree ........................   Passed    0.00 sec
      Start  8: hash-extra-blake
 8/14 Test  #8: hash-extra-blake .................   Passed    0.01 sec
      Start  9: hash-extra-groestl
 9/14 Test  #9: hash-extra-groestl ...............   Passed    0.01 sec
      Start 10: hash-extra-jh
10/14 Test #10: hash-extra-jh ....................   Passed    0.01 sec
      Start 11: hash-extra-skein
11/14 Test #11: hash-extra-skein .................   Passed    0.01 sec
      Start 12: HashTargetTests
12/14 Test #12: HashTargetTests ..................   Passed    0.05 sec
      Start 13: SystemTests
13/14 Test #13: SystemTests ......................   Passed    7.63 sec
      Start 14: UnitTests
14/14 Test #14: UnitTests ........................   Passed  132.10 sec

100% tests passed, 0 tests failed out of 14

Total Test time (real) = 140.05 sec
```

**Comment by jgsogo** [comment]
Hi @calidion!

_IMPORTANT.- All is being tested with `81b2bdd` revision of your repository_

I'm taking over this issue. I've being able to compile the project inside a docker image (`lasote/gcc5`) removing everything related to Conan. This is the first step. 👍 

**Next, let's use Conan** :arrow_heading_down:
Conan will help you to handle your dependencies, but we try to respect the original project and development flow as much as possible. You should we able to use Conan just writing those two _magical_ lines inside your `CMakeLists.txt` and the corresponding `conanfile.txt/py`.

I've seen you have already tried it, but there is something more to do: you have to declare your dependencies inside `conanfile.txt` (and those libs have to be available as Conan packages). You are requiring, according to the `find_packages` written in your `CMakeLists.txt`, the libraries `Boost` and `OpenSSL`, and optionally `Git`. The first two are available in the main Conan repositories, but I cannot find `Git`:

```
$ conan search boost* -r all
Remote 'conan-center':
boost/1.66.0@conan/stable
boost/1.67.0@conan/stable
boost/1.68.0@conan/stable
```

```
$ conan search OpenSSL* -r all
Remote 'conan-center':
OpenSSL/1.0.2@conan/stable
OpenSSL/1.0.2l@conan/stable
OpenSSL/1.0.2m@conan/stable
OpenSSL/1.0.2n@conan/stable
OpenSSL/1.0.2o@conan/stable
OpenSSL/1.0.2p@conan/stable
OpenSSL/1.1.0g@conan/stable
OpenSSL/1.1.0i@conan/stable
OpenSSL/1.1.1@conan/stable
```

Boost v1.55 is not available, but we can use another one. Besides this, I've seen in your code that you are using `libsoudium` too, it is available thanks to the bincrafters ([here it is in bintray](https://bintray.com/bincrafters/public-conan/libsodium%3Abincrafters)).
With this information, we need to write a proper `conanfile.txt` with the dependencies:

```
[requires]
boost/1.66.0@conan/stable
OpenSSL/1.1.1@conan/stable
libsodium/1.0.16@bincrafters/stable

[generators]
cmake
```

and modify your `CMakeLists.txt` to request version 1.66 for Boost libraries. Also, handle the options to avoid requiring Git library. Find the modified `CMakeLists.txt` file [here](https://gist.github.com/jgsogo/1bcf2a448b948e53619722f30c756f77) 🌟 

Now we can go for it and compile 💻.  I'll do it in `Debug` as I've seen you are using it in your scripts, and using the new ABI ([more info here about ABI compatibility](https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html)):

```
$ mkdir build && cd build
$ conan install .. -s build_type=Debug -s compiler.libcxx=libstdc++11
$ cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_GCOV=1 -DCOMMIT_ID_IN_VERSION:BOOL=OFF
```

Depending on your compiler (and maybe due to an issue with the generated binaries), you may need to rebuild boost for your compiler and make explicit the libcxx version. If this is the case, these are the commands to run instead of the previous ones:

```
$ mkdir build && cd build
$ conan install .. -s build_type=Debug -s compiler.libcxx=libstdc++11 --build boost
cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_GCOV=1 -DCOMMIT_ID_IN_VERSION:BOOL=OFF -DCONAN_LIBCXX=libstdc++11
```

Please, check that you can reproduce this steps, it did compile inside the docker container:

```
[ 99%] Building CXX object tests/CMakeFiles/SystemTests.dir/System/TcpListenerTests.cpp.o
[100%] Building CXX object tests/CMakeFiles/SystemTests.dir/System/TimerTests.cpp.o
[100%] Building CXX object tests/CMakeFiles/SystemTests.dir/System/main.cpp.o
[100%] Linking CXX executable ../bin/system_tests
[100%] Built target SystemTests
```

Thanks!

**Comment by calidion** [comment]
@jgsogo

I added lib boost using conan once  and it can be compiled.
The problem I am encountering is that by inserting conan instructions into CMakelist.txt, my tests can not be found and executed any more, not the code can't be compile with conan.

Thanks.

**Comment by jgsogo** [comment]
@calidion, in your previous examples you were not using Conan, you were compiling using the system installed libraries.

The issue with tests has nothing to do with Conan, it is just about how you are adding and executing tests. Try to substitute the way you are registering them to allow any kind of build (in my example/tuto I'm doing an out-of-source build, that is the reson why tests are not found):

[Here](https://github.com/vigcoin/coin/blob/81b2bddd63675af5580ab59482b2918f8be7c36b/tests/CMakeLists.txt#L112) you have to put the working directory to run the tests into:

```
add_test(NAME UnitTests COMMAND unit_tests WORKING_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
```

**Comment by calidion** [comment]
close it for i will not use conan in the near future.

**Comment by johnmcfarlane** [comment]
@jgsogo I'm seeing the same issue. [Other's are too](https://www.mail-archive.com/dev@qpid.apache.org/msg64260.html). I'm sure there's a reasonable workaround that fixes the problem but I don't think it's fair to say it's nothing to do with Conan. Without Conan, tests build and work with the simple usage pattern. With Conan, they suddenly break and it's not at all obvious why this should be.

**Comment by memsharded** [comment]
Hi @johnmcfarlane 

The issue you are linking is from 2017, Conan has widely changed since them. In the above thread I still find difficult to evaluate what is happening, as the case is very far from being minimal and requires a lot of changes and fixes even to build without Conan.

Could you provide some (hopefully relatively simple) example or pointer to project that could help us understand better the issue? That would really help, many thanks!

**Comment by johnmcfarlane** [comment]
Sure, perhaps -- once I've got my system set up with Conan. 

But I was just trying to make the point that I think Conan lost a user back there at the sentence: "The issue with tests has nothing to do with Conan". Simply by including the Conan cmake script and invoking the function, `conan_basic_setup()`, test executables get a different target directory which breaks stuff. It was happening in 2017 and is happening in 2019. Whatever the reason, it has *something* to do with Conan.

I'll try and remember to get back to you with a repro at some point. It may not be simple but hopefully it will at least be reproducible.

Thanks
John

**Comment by memsharded** [comment]
Hi John,

Yes, do you mean it could be related to the output dirs? By default ``conan_basic_setup()`` defines "bin" as the output directory for executables, could that be the thing? It is possible to opt-out that behavior with ``conan_basic_setup(NO_OUTPUT_DIRS)``. 

It is true that if the tests have hardcoded some directories in CMakeLists.txt, this might break, this could be the reason @jgsogo was suggesting a fix with ``add_test(NAME UnitTests COMMAND unit_tests WORKING_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})``.

Looking forward your feedback or some hints to reproduce this. Probably better as a new issue, please, sometimes already closed issues are more difficult to track and might skip the notifications. Hopefully this time we can clarify this better (in any case we are already investigating ways to improve the developer experience). Many thanks!

**Comment by johnmcfarlane** [comment]
Confirmed, thanks. No need to create a new issue. 

But again, in numerous projects past, using the simple `add_test(target, target)` was worked just fine (examples [1](https://github.com/johnmcfarlane/cnl/blob/develop/src/test/CMakeLists.txt#L232) [2](https://github.com/ericniebler/range-v3/blob/f1479721bf17dcb7c53fcb9793537866c89d4cc7/CMakeLists.txt#L43)). Calling this 'hardcoded', again, may not be the best approach when trying to coax timid CMake users out of their underground borrows!

**Comment by jgsogo** [comment]
Hi @johnmcfarlane. I'm sorry if I sounded too opinionated in my previous comment, it wasn't my intention. I'll be very pleased to help you with an example and investigate how Conan is affecting CMake variables and why the behavior changes (every hint in this direction can make Conan better). Thanks!

**Comment by johnmcfarlane** [comment]
No problem at all. You're all being very helpful. I just wanted to note how important tone can be. (Not directly related but here's [a great talk](https://www.youtube.com/watch?v=D7Sd8A6_fYU) about how to evangelise your favourite technology. It explains why being right is half the battle ... but only on a good day!)

And my particular issue is fixed now. In summary, when using Conan, if `ctest` cannot find tests because they have been moved to a *bin/* sub-directory, initialise Conan with `conan_basic_setup(NO_OUTPUT_DIRS)`. 

Thanks, John
