### ISSUE TITLE
Artifactory returns wrong code on search

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#3906]
From https://github.com/conan-io/conan/pull/3905#issuecomment-435763534

Conan server, when queried with conan search and not read permissions, ask for authentication (returns 401/403)

Artifactory, returns 200 OK and "no packages" (Repo without anonymous permission). This is an issue for resolving version-ranges, which uses a search to get versions from the server.

**Comment by visglz** [comment]
I hit for same issue as @puetzk in [3905](https://github.com/conan-io/conan/pull/3905#issuecomment-435763534).

On the devel branches in the requirements section in our conanfiles we use ranges like `pkg/[versionrange]/@user/channel` to always get the latest published version from the conan server. On the CI server we use  "conan install --update" so that conan asks the server for the latest version. The "--update" is important because the packages listed in the requirements might have been built by another build slave and might not be available in the local cache.

Since we moved from conan-server to artifactory the builds began breaking occasionally, because "conan install --update" doesn't resolve any longer  to the latest version, but sticks with the one which is accidently available in the local cache. (It breaks e.g. when the main package is using some functionality which is only availalable in the updated required one).

Interestingly once I am logged in (the token is stored in `~/.conan/.conandb`) it is working. But we pass CI credentials in environment variables and start conan usually in an freshly instantiated docker container. So conan doesn't have a prepoluated `.conandb`.

For the developers who didn't login before to the artifactory there is also an surprising effect that "conan search" returns an empty list without even asking for credentials:

```
$ conan search -r artifactory
There are no packages
# Doing some action which triggers login to the artifactory,
# e.g. conan install with pkgs which are not locally available
$ conan search -r artifactory
-> full list of packages
```

The version I tested are Artifactory Professional 6.6.3 rev 60603900 and conan 1.11.2.

Hm. I wonder if this issue is really something which should be fixed in conan. Looks more like an artifactory issue.

**Comment by fulara** [comment]
I am hitting very similar problem see below:

```
conan search '*boost*' -r conan-center
There are no packages matching the 'boost' pattern
```
However when trying to install particular package I get
```
conan install boost/1.65.1@conan/stable
....
boost/1.65.1@conan/stable: Trying with 'conan-center'...
ERROR: Permission denied for user: 'fulara'. [Remote: conan-center]
```
$ conan --version
Conan version 1.22.3

Artifactory Version 6.10.1


Very confusing behavior.

**Comment by fulara** [comment]
To expand on my previous statement,

The same happens when there is timeout internally within artifactory. 
What we have:
We have a local artifactory that has a mirror on bintray this is the behavior we observed:
```
conan search b2 -r mirror
Existing package recipes:

b2/4.0.0
b2/4.0.1
b2/4.1.0


conan search boost -r mirror
returns:
There are no packages matching the 'boost' pattern
```

We have increased a timeout from 15 sec to 60 sec and this started working.

**Comment by aleksa2808** [comment]
Observing the same issue as @fulara on a local artifactory with a conan-center remote cache. Doing a pattern search times out for conan-center after the default 15s and, even if I have matching packages in my local repository, I get a "no matching packages" message.

**Comment by alexanderLinear** [comment]
for me hitting a timeout would mean that the server is responding slower than that timeout.
this means under some conditions the server tends to respond slow - either due to "wake up" effects or due to other pending loads.
evidently using a 4x timeout value can mitigate that.
rationale:
hitting a timeout in such a server query is currently handled in a silent(!) fashion and thus behaves the same as a "no hit from server" result.

proposal:
please report if a timeout on the server query did happen - because its definitely a different response compared to "no hit from server".

**Comment by alexanderLinear** [comment]
Is this the right knob in conan.conf for tuning the timeout:

1.3.0 (30-April-2018)
"Feature: Timeout for downloading files from remotes is now configurable (defaulted to 60 seconds)"
https://docs.conan.io/en/latest/changelog.html#april-2018

request_timeout = 60                  # environment CONAN_REQUEST_TIMEOUT (seconds)
https://docs.conan.io/en/1.33/reference/config_files/conan.conf.html (already there in the docs since 1.5)

**Comment by memsharded** [comment]
These timeouts were solved some time ago in Artifactory and ConanCenter too, this should not longer be an issue, closing as outdated.
