### ISSUE TITLE
Conan search results in different outputs

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#3916]
To help us debug your issue please explain:

Hi!

When trying to search for **zlib/1.2.8@conan/stable** on Bintray, I have two different results based on my remotes. However, zlib/1.2.8 is linked to Conan Center.

    $ conan search -r conan-center zlib/1.2.8@conan/stable --table index.html

![zlib/1.2.8@conan/stable](https://camo.githubusercontent.com/30dcbda78b9674b522dbe57246b9213055d41fd2/68747470733a2f2f73637265656e73686f747363646e2e66697265666f7875736572636f6e74656e742e636f6d2f696d616765732f36356134623064392d333164662d343833652d613339362d6235333265316365643233312e706e67)

    $ conan search -r conan-community zlib/1.2.8@conan/stable --table index.html

![zlib/1.2.8@conan/stable](https://camo.githubusercontent.com/1f5379d454ff95d4e728746a4080f88c6187d577/68747470733a2f2f73637265656e73686f747363646e2e66697265666f7875736572636f6e74656e742e636f6d2f696d616765732f64323566666537322d353462622d343134612d383838342d6163323233643635373938612e706e67)

     $ conan remote list
       bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]
       conan-center: https://conan.bintray.com [Verify SSL: True]
       conan-community: https://api.bintray.com/conan/conan-community/conan [Verify SSL: True]

@SSE4 Also checked and he has the same result. Seems some Bintray problem, but few weeks ago we had trouble trying search zlib on Bintray.

Conan Version: 1.9.0

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
I think this is due to the fact that new packages take a little bit time to relink the rest of repositories. In this case ZLIB is uploaded to conan-community which makes packages available instantly through that remote, whereas packages through conan-center have to wait a little bit to be available.

I have followed the steps and had the same results, so I think this can be closed:

![image](https://user-images.githubusercontent.com/10808592/48143368-e3de8c80-e2ae-11e8-8c14-061216bf4fea.png)

**Comment by uilianries** [comment]
interesting :thinking: Thanks!
