### ISSUE TITLE
[build-system][CMake] Use CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE to follow build settings.

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#3919]
Right now, cmake defaults to HostX86, always, unless specified with the cmake variable: 
```
set(CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE "x64")
project(test CXX)
```

If the conan build-settings arch=x64, this should probably be activated automatically.

**Comment by lasote** [comment]
Added to the cross building model project: The "running machine architecture/operating system etc" has to be modeled and has to determine the build system behavior, also in MSBuild(). The build helpers cannot follow a build system default, they have to configure explicitly every flag that it is related with the input settings, in this case, the build machine architecture.

**Comment by Minimonium** [comment]
For readers - there is a possibility to override the behavior with `tools.cmake.cmaketoolchain:toolset_arch=xxx` in a `[conf]` setting.  Changing `CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE` would be incorrect since it's a generated value.

Should probably be propagaded from the host arch setting, since it's an important setting for `import` expression generation.

**Comment by memsharded** [comment]
With ``CMakeToolchain`` and ``tools.cmake.cmaketoolchain:toolset_arch`` this will already define CMAKE_GENERATOR_TOOLSET, so it seems this will not be necessary, nor recommended. So closing the issue, but please re-open if necessary.
