### ISSUE TITLE
Read license/URL without having the file exported

### ISSUE THREAD

**Issue by danielhalati** [conan-io/conan#3939]
Hello,

I try to create some conan packages and I am experiencing difficulties when trying to set the License and URL attributes. I have a file named ComponentInfo.txt where I can extract this information.

https://docs.conan.io/en/latest/howtos/capture_version.html#how-to-capture-package-version-from-text-or-build-files

I have read this topic here and I understood how it works for the version. Even if the version cannot be read anymore in the local cache, it is read from the folder layout.

My question is: how can I read license and URL from a text file without exporting the file in the package? Is this even possible at the moment?

**Comment by uilianries** [comment]
there is a section in docs where is explained how to extract the license from a header file: https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#recipe-quality

but as you can see is executed from `package` method. In your case is chicken and the egg problem. You will need to extract both license and url, and set using `configure` method. However, you need all sources before that, but `configure` runs first than `source`. You could download the specific file when running `configure` and extract all things, but it's tricky. I would prefer to set all attributes as hardcoded (except for version in your case) because commands like `inspect` will not be able to read those attributes if they are populated after to run `configure`.

**Comment by danielhalati** [comment]
I generated conanfile.py on the fly from a template with the exact values there. Probably there is no other solution for this

**Comment by lasote** [comment]
Yes, I think there is no other way. Thanks for your question!
