### ISSUE TITLE
Feature request conan.conf file

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#3943]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I have just been burnt by the same type of issue again.... a user was having connectivity issues with the Proxy devil.

I looked at the conan.conf file and read right over the fact that the variable "no_proxy" was set, but what needed to be set was "no_proxy_match"

Is it possible for conan to report:

"You have set the variable: 'XXXX' in the conan.conf file, but Conan does not understand that variable"

An error/warning message like that helps stupid people like me.

**Comment by memsharded** [comment]
The problem with ``no_proxy`` is that it is still a valid conan.conf, because some other users were using it, and it was enough for their purpose, so we didn't want to break them removing it. 
However, I think it should be ok to print a warning for this conf variable (saying that you probably want to use ``no_proxy_match`` instead). Should we consider deprecating/removing ``no_proxy`` totally in conan 2.0, lasote?

**Comment by lasote** [comment]
Yes, we should deprecate it because it is very buggy and unpredictable.
I'm ok showing a warning.
