### ISSUE TITLE
[SCM] pristine function get executed on initial export. 

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#3955]
> With conan 1.9.1 I just tried a `conan create . dev/dev` on a recipe that uses scm and svn and I got the warning when the initial export is performed, but everything worked fine.

_Originally posted by @keithrob91 in https://github.com/conan-io/conan/issues/3909#issuecomment-437328303_

**Comment by keithrob91** [comment]
May be some confusion here, but I wasn't suggesting there was a bug when the warning was issued in this situation.

Isn't the warning supposed to let a user know they may have uncommitted changes in their working copy? If so, when `conan create` is called, the warning should be output if their are local changes. In my case, because I have a prehistoric subversion, I have to always accept the warning whenever I call `conan create`, right?

**Comment by jgsogo** [comment]
I could happen when you do a `conan install` because Conan will clone the repo, but I'm not sure if it will call the `is_pristine` function. Anyway, you are right, if it does it will be ok for newer versions of SVN, there is _nothing_ we can do for prehistoric ones

Closing... :persevere:
