### ISSUE TITLE
conan install cannot generate configure file correctly.

### ISSUE THREAD

**Issue by calidion** [conan-io/conan#3958]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I have currently muted conan by putting conan at the endo of my cmake file for a while, but it stumbled me again because of my switching from ubuntu 16.04 to 18.04.

By executing
```
conan install .
```
I got the following:

```

Configuration:
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

PROJECT: Installing /home/eric/vigcoin/coin/conanfile.txt
Requirements
Packages

PROJECT: Generator cmake created conanbuildinfo.cmake
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
```

where 
```
gcc --version
```
got: 

```
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

apparently the `compiler.version=5` is wrong.

then CMake failed:

```
-- Conan: Checking correct version: 7
CMake Error at conanbuildinfo.cmake:298 (message):
  Incorrect 'gcc' version 'compiler.version=5' is not the one detected by
  CMake: 'GNU=7.3'
Call Stack (most recent call first):
  conanbuildinfo.cmake:350 (conan_error_compiler_version)
  conanbuildinfo.cmake:439 (check_compiler_version)
  conanbuildinfo.cmake:63 (conan_check_compiler)
  CMakeLists.txt:168 (conan_basic_setup)
```

**Comment by jgsogo** [comment]
Hi!

If you have moved Conan lines inside your _CMakeLists.txt_ to the end, Conan won't be able to apply the required variables in order to use the desired compiler, version and so on. You should put those lines at the beginning or remove them (you won't be using Conan then).

I'll recommend you to read docs about profiles here: https://docs.conan.io/en/latest/reference/profiles.html#profiles. By default your `conan install .` is using the _default_ profile.

Let me know if the docs are enough, and if you have more questions in order to start using Conan in your project, please, share them with me.

Thanks!

**Comment by calidion** [comment]
The problem is : 
gcc is 7.3, why conan generated cmake set the compiler version to 5?
