### ISSUE TITLE
Conflicts with child requirements

### ISSUE THREAD

**Issue by Linden-Ryuujin** [conan-io/conan#3977]
**Issue**
Project/1.0.0@owner/channel:
```
self.requires("RequirementOne/[=1.2.3]@owner/channel")
self.requires("RequirementTwo/[=4.5.6]@owner/channel")
```

RequirementOne/1.2.3@owner/channel
```
self.requires("ProblemRequirement/[=1.0.0]@owner/channel")
```

RequirementTwo/3.4.5@owner/channel
```
self.requires("ProblemRequirement/[~1]@owner/channel")
```

In artifactory:
```
ProblemRequirement/1.0.0@owner/channel
ProblemRequirement/1.1.0@owner/channel
```

Get Info:
```
$ conan info Project/1.0.0@owner/channel --only=None

Version range '=1.2.3' required by 'Project/1.0.0@owner/channel' resolved to 'RequirementOne/1.2.3@owner/channel'
Version range '=3.4.5' required by 'Project/1.0.0@owner/channel' resolved to 'RequirementTwo/3.4.5@owner/channel'
Detected OS: Windows 10/10.0
Version range '=1.0.0' required by 'RequirementOne/1.2.3@owner/channel' resolved to 'ProblemRequirement/1.0.0@owner/channel'
Version range '~1' required by 'RequirementTwo/3.4.5@owner/channel' resolved to 'ProblemRequirement/1.1.0@owner/channel'

ERROR: Conflict in RequirementTwo/3.4.5@owner/channel
    Requirement ProblemRequirement/1.1.0@owner/channel conflicts with already defined ProblemRequirement/1.0.0@owner/channel
    Keeping ProblemRequirement/1.0.0@owner/channel
    To change it, override it in your base requirements
```
The conan command drops out at this point, despite the fact it has worked out the correct behavior (1.0.0 is compatible with both sets of requirements). It seems that when resolving requirements it doesn't take in account the other tree of requirements. We've worked around it by adding a requirement for ProblemRequirement into Project but that's not ideal, it means we need to update it every time RequirementOne changes. I'm sure it could get even muddier if the requirement issue was further down the requirement chain.

**System Details**
- OS: Windows 10
- conan version: 1.9.2

**Comment by lasote** [comment]
Hi. Yes, unfortunately, this is the documented behavior for Conan version ranges. From [here](https://docs.conan.io/en/latest/mastering/version_ranges.html) you can read:

```
Version range expressions are evaluated at the time of building the dependency graph, from downstream to upstream dependencies. 

No joint-compatibility of the full graph is computed, instead, version ranges are evaluated when dependencies are first retrieved.

This means, that if a package A depends on another package B (A->B), and A has a requirement for C/[>1.2,<1.8], this requirement is evaluated first and it can lead to get the version C/1.7. If package B has the requirement to C/[>1.3,<1.6], this one will be overwritten by the downstream one, it will output a version incompatibility error. 

But the “joint” compatibility of the graph will not be obtained. 
Downstream packages or consumer projects can impose their own requirements to comply with upstream constraints, in this case a override dependency to C/[>1.3,<1.6] can be easily defined in the downstream package or project.
```

I've verifyied it with a test here: https://github.com/conan-io/conan/pull/3981

So you have two options, overriding from the consumer (you are already doing it) or change the order of the requirements to force first the resolution of the most restrictive, `[=1.0.0]`. You can take a look in the test.

By the way, why are you using `[=1.0.0]` instead of just`1.0.0` pinned versions?

**Comment by puetzk** [comment]
> By the way, why are you using `[=1.0.0]` instead of just `1.0.0` pinned versions?

Don't know about @Linden-Ryuujin but I do this sometimes because pinned versions get ignored if the consumer listed a different version (it turns into an override), but restrictive version ranges get verified against the final selected version. So to really mean "only this will work" as opposed to "I suggest version X", I think you have to use a version range (or just do a coded test and raise ConanInvalidConfiguration somewhere...)
