### ISSUE TITLE
Hard to debug error ERROR: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by nesc1** [conan-io/conan#3985]
Hi, first of all i want to congratulate you guys on this great project that is conan.

I performed some conan copy to rename the owner of the package on custom packages that some have sources other get the sources from git and so on, they all are different but now i'm getting this anoying error when i try to do a conan install on some packages:
```
ERROR: Expecting value: line 1 column 1 (char 0)
```
The problem is that it is very hard to know what package is creating this error.

I kind understand that the problem was that the conan copy does not copy sources or it seems... something like that i can't really explain, but doing the conan create again on the package seems to fix this... (when i find the package with error... but i got many and is hard to find the one in error or ones)

It will be nice to add the package name on the error to easily find the package that is creating the problem (many package dependencies create this hard to find package in error)

**Comment by nesc1** [comment]
Hi @memsharded, yes the steps is like that, but probably more true like:
```
conan create zlib/....
conan upload zlib/....
conan remove zlib/....
conan install zlib/....
conan copy zlib/...   otheruser/channel
conan install zlib/..@otheruser/channel
```
this for several packages... i can not reproduce it exacly because i'm in a midle of the transation packages from one server to another, but you are talking about some log that conan produces? if yes tell-me where it is that i will send you

**Comment by memsharded** [comment]
I have tried that and seems to be working good. 
Yes, please, when you finish doing that, try to reproduce the failure with a given specific package, and when it fails, take the terminal output, and copy it here too. Many thanks!

**Comment by mikjh** [comment]
I came to this issue after googling the same error message.
Although my problem maybe was not the same, what I experienced could be of help to someone with a similar problem:

I had added a Artifactory as a Conan remote , to which I could not connect to (error in network setup by my company). This remote was higher up in the list of remotes than another working remote. When doing ´conan install somepackage/1.0.0@package/stable´, it failed when searching for the package at the faulty remote, giving me

    ERROR: Failed requirement 'somepackage/1.0.0@package/stable' from 'PROJECT'
    ERROR: Expecting value: line 1 column 1 (char 0)

as error output. 

Incidentally, I saw that doing ´conan install somepackage/1.0.0@package/stable -r my_remote´ worked, so removing the faulty remote solved my problem.

**Comment by memsharded** [comment]
Hi @mikjh 

Thanks for your report, I have been further investigating this with all the feedback from @nesc1  too, and the problem seems to be when someone (not a conan server) is returning a 200-OK, and then some response that is usually html or text, but not json. I remember this happening once with a proxy server. 

I have been able to reproduce the issue in testing, fixed it. If it is a message from such a proxy server, that will be display in the terminal, and that would be more useful for understanding. I have submitted this as a PR in https://github.com/conan-io/conan/pull/4317/files.

Could you please confirm if this could be the case? Is it possible that you are behind a proxy, or that such faulty remote is actually returning 200-OK for any call? Thanks!

**Comment by mikjh** [comment]
This seems feasible. Yes, I am somehow behind a proxy, connected through a reverse proxy (not sure how the magic it is working, I do not work in IT).

When implementing the changes that you made in rest_client_common.py, instead of:
    
    ERROR: Expecting value: line 1 column 1 (char 0)
    
I get:

    ERROR: Remote responded with unexpected message: <!DOCTYPE HTML>
    [ lengthy html message ]
    
with the entire html message. Sorry, I had to leave out the rest of the message, as I do not know if anything secret is in there. But yes, it looks better!

Sorry, how do I check if it is returning a 200-OK?

**Comment by memsharded** [comment]
> with the entire html message. Sorry, I had to leave out the rest of the message, as I do not know if anything secret is in there. But yes, it looks better!

That is perfect, it is the best that can be done, output the message to the user, which will typically contain information to investigate what is happening.

You can't explicitly check the 200-OK, it is implicit. If the server is not found, or the server responds 404 or other error, they are already managed. The problem was when a conan-api endpoint is requested, and a non conan-api server responds with 200-OK, which it clearly shouldn't.

Looking good then. Assigned the fix for the next release 1.12. Thanks very much for testing!

**Comment by mikjh** [comment]
No problem, glad to be of help!

**Comment by nesc1** [comment]
Hi guys nice to see that the problem is being handled.
I must say that this error do not happear again.. don't know if it was the conan_server at the time that was returning some error or not, but the problem do not arise again... so i can't help you guys debugging this... sorry.

**Comment by memsharded** [comment]
No problem @nesc1, it was good information to spot this rare, but possible issue. So many thanks!
