### ISSUE TITLE
Strategy for addressing common USER and CHANNEL challenges

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#3988]
This is a suggestion of a concept to solve a group of related scaling challenges I've hit in both OSS and enterprise use cases. 

At my company, we have a requirement to compile all third party libs from source.  The adherence to this is so stringent, that we remove Conan Center from our remotes in our build containers.  Of course, we still want to make use of the Bincrafters and Conan Community recipes for building the software. 

So, for example, `openssl` and `zlib`.

I use "Bitbucket Import" to bring in `conan-openssl` and `conan-zlib` to our source control. 

I add a `Jenkinsfile`, and replace the `build.py` with our own custom.  Occasionally, we'll patch a source. 
 When Jenkins does our builds, the packages are create with OUR conan username: 

Example:  `zlib/1.2.11@mycompany/stable`

Jenkins then uploads this package to our repository. 

Now we do the same for OpenSSL.  However, of course it still references `zlib/1.2.11@conan/stable`.  

So, we have two choices.  Patch the conan-openssl recipe, or override it in the downstream package which consumes openssl.

Unfortunately, both of these are really rough for us.  Patching is no good, because we're going to be using about 40 of the `bincrafters`/`conan` recipes.  We would have to build and then patch our way up the dependency tree, one-by-one.  As for overriding the dependencies in the consuming recipes, we have roughly 20-25 "final product" recipes that go into our installers.  Separate executables.  Each of these recipes would have to set the overrides on every single transitive dependency it uses.  It almost defeats the purpose of having a transitive dependency tree to begin with. 

There is a similar problem with managing references to channel ( `testing` vs `stable`).  This one comes up very frequently when users are trying to fix or upgrade some intermediate dependency, so they push their changes to the `testing` channel package.  Now, they just want to run a build or locally execute a `stable` channel of some consuming package against the `testing` channel of this one dependency.  There are two possible solutions here.  First, maintain `testing` channel on all your packages, and in the `conanfile.py` on all your `testing` branches, reference the `testing` channel of all your dependencies. This is not fun because you can't really safely go on merging testing into stable the normal way without overwriting all your references.   Second, parameterize all references in all recipes with `user` and `channel` variables, which you can set at runtime with environment variables or something.  This is again undesirable for a few reasons... it's a lot of clever engineering, it basically forces all-dependencies-one-channel. Despite the drawbacks, I know there are enterprise people who do this today just to have a testing branch strategy that kind of works. 

The alternative mechanism I came up which addresses both reference segments in a way that is usable during both local Conan executions, AND continuous integration builds is shown below: 

`conan create . some/thing -u "zlib:mycompany" -u "openssl:mycompany" -c "openssl:testing"`

or, using the wildcard syntax, if the whole dependency tree is uniform, as it likely is in most enterprise codebases:

`conan create . some/thing -u "*:mycompany" -c "*:testing"`

And then in Conan Profiles, i'm not sure what section to put it in, or what to call a new section for these things if that is what is called for:
```
[user_overrides]
zlib:mycompany
openssl:mycompany
[channel_overrides]
openssl:testing
```
I think the concept is self-explanatory because it mimics the control of options and settings on a per-package basis at build time.  In theory, this could be implemented without any breaking changes because it's a brand-new feature.  As usual, with any "idea" for a new feature, there could be unforeseen implications which make this completely infeasible.  Thus, feedback welcome.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by theodelrieu** [comment]
I'm in favor of a solution like this, the only thing I'm afraid of is the confusion caused by the override itself.

This is an issue I already have with the current `override` feature though, because what you see if not necessarily what you get, i.e. you have to look at the final `conaninfo.txt` to get the real information.

Let's say you want to override one of your dependencies' requirement on `Boost/1.66.0@user/stable` like this:

```python
# top-level conanfile.py

def requirements(self):
    self.requires("Boost/1.67.0@user/stable", override=True)
```

Then you put the following in your profile:

```ini
[user_overrides]
Boost:bincrafters

[channel_overrides]
Boost:testing
```

That's what I call confusing... I do not have a solution in mind right now, it might require some thoughts on the `override` feature in the first place.

**Comment by keithrob91** [comment]
I am also in favour of a feature like this. Personally though, I don't like the profile part of the solution, but I do like the command line arguments bit!

> Then you put the following in your profile:

Doesn't the @solvingj solution mean that you no longer need the override in the top-level recipe? Just the command line or profile settings are required?

**Comment by solvingj** [comment]
@keithrob91 : preferences are fine.  It's simply natural for profiles to support all the same package-related parameters that the CLI does. Also, regarding overrides, indeed, the goal is to make override-in-recipe no-longer required, but provide an alternative mechanism to achieve the same.   

Profile/Recipe/CLI... each of the various places you can define variables are useful in different scenarios. I'm glad we have multiple. 

@theodelrieu : you certainly have more cross-building experience than I, so it's interesting to hear your insight about how recipes with cross-building logic make your life more difficult.  Are you encountering OSS recipes with this logic?  Or are these ones others have made in your company?

**Comment by solvingj** [comment]
@theodelrieu also a good point about multiple places to override.  This reminds me to request a "Bill of Materials" hook which pretty-prints something similar to conaninfo.txt, which would be very useful for CI logging.

**Comment by keithrob91** [comment]
My problem with some of this stuff being set in a profile is that it is hidden and not always obvious what settings are being used. This is normally a problem when something isn't working as expected and you're trying to find out why.

But if you like them, fine!

**Comment by solvingj** [comment]
It's not that i like them, it's that they're far more practical in guaranteeing consistent settings and options across teams and CI builds together.   However, to your point, the latest version of Conan seems to print out a nice "reconciled" list of settings and options by default.  Not sure if you've seen this, or if it's comprehensive.

**Comment by theodelrieu** [comment]
@solvingj 

>Are you encountering OSS recipes with this logic?

Mostly Autotools-based libraries, the worst being `OpenSSL` with no surprise.

I'd like to see recipes only dealing with specific stuff (e.g. if building for `Android`, add a specific file to compile), but leave more general things (e.g. `sysroot` and flag handling) to someone else.

It usually goes smoothly with CMake based libraries, although I have to use `tools.patch` from time to time...

**Comment by uilianries** [comment]
You touched on an old problem I had in my previous job. I liked your way to think and also I thought about taking advantage of the solution adding one option to override an entire dependency:

    conan create . some/thing --override "zlib/1.2.11@mycompany/testing"

**Comment by lasote** [comment]
So, let's try to summarize, we need a mechanism to override `user/channel`  in a dependency tree:

- We don't want to change the recipes, they will continue having "fixed" requirements to the transitive deps.
- We don't want to modify the `conanfile.py` from our project to override dependencies.
- We want to do it from a profile, so we can change the dependency tree (testing/stable) applying a different one. Also, if the "project" is a future conan package, introducing in the recipe the overrides would violate the first point.
- We want wildcards, to change globally N deps: `*:user/channel`
- We want to override only the channel or only the user but also both.

Let's think the feature looks like this (not even a real proposition, but useful to disscuss possible flaws):

**myprofile.txt**
```
[overrides]
zlib/1.2.8@[user]/[channel] # Regular override (not related with this feature request) of the zlib library to use the 1.2.8 with the same user and channel
zlib/[version]@my_user/my_channel # Will override any zlib version to use my_user/my_channel
*/[version]@my_user/[channel] # Will override all the packages to use `my_user`
```

Let's start the discussion!

**Comment by keithrob91** [comment]
@lasote Not sure if it is implicit in what you said above, but I would also want this sort of capability available from the command line, not just from a profile.

**Comment by solvingj** [comment]
I just had a thought, that another interesting reason one might want to add a "regular dependency" from a profile is to "quasi-override" uses of `system_requires`.  For example, a recipe might do a `system_requires` for `libusb` when on Linux.  In time, a Conan package for `libusb` might appear on Conan Center, or on an internal Artifactory server with custom patches for the organization.  While not technically an "override", if the `libusb` Conan package is "injected" into the dependency graph from a profile, it could be applied to any number of recipes that have `system_requires`. This would seem to provides nice migration path away from System Requires where possible, as more and more "system-like" dependencies get Conan recipes/packages.

**Comment by lasote** [comment]
I think that is a different use case/issue. It could work in the other way, if a recipe has a requirement for a conan package `libusb`, you could override it with one "proxy" package that only appends the `cpp_info.libs = ["usb"]` to make it work agains a system package.

Otherwise the issue would be very different, you would be injecting dependencies to an specific node, I know that the system requirements could be "the plug" that allows that kind of override but indeed it would be a very different issue.

Maybe the KIS way to achieve this is to recommend create always a proxy package when using system requires. The recommendation would be:

1) Create a recipe for the system requriements
2) In the recipe, call the system_requirements to install the needed stuff
3) declare the needed libs in the cppinfo

That way you could always override them.

**Comment by monsdar** [comment]
The situation @solvingj described initially is ours as well. Though we're altering the recipes to not download from the internet but use an internal server for that. So not only do we change the dependencies, but we also overwrite the `source()` method.

A feature that makes this easier would greatly help. I like the proposed solutions.

**Comment by lasote** [comment]
The `source()` method overwriting is also part of this discussion here: https://github.com/conan-io/conan/issues/4734
We don't have yet any idea to mitigate that.

**Comment by harendt** [comment]
> Let's think the feature looks like this (not even a real proposition, but useful to disscuss possible flaws):
> 
> **myprofile.txt**
> 
> ```
> [overrides]
> zlib/1.2.8@[user]/[channel] # Regular override (not related with this feature request) of the zlib library to use the 1.2.8 with the same user and channel
> zlib/[version]@my_user/my_channel # Will override any zlib version to use my_user/my_channel
> */[version]@my_user/[channel] # Will override all the packages to use `my_user`
> ```

I wonder why this issue was closed. That proposal looks like a very powerful feature.

In general I think that overrides in profiles are better than overrides in a `conanfile.py` as it keeps the `conanfile.py` clean and separates the recipe definition from the recipe consumption.

Allowing to override user and/or channel with wildcards would be very helpful as it allows to easily control user/channel of a whole dependency graph without explicitly mentioning every node of the dependency graph.

**Comment by retifrav** [comment]
I'm also interested to know why this issue has been closed, or rather: is there a solution/workaround, or is it planned for Conan 2.0, or is it something that (*sadly*) won't be worked on? Either is fine, it's just confusing that the issue was closed without some resolution/explanation.

**Comment by memsharded** [comment]
Hi @retifrav 

yes, a lot of things have changed since then, I'll try to summarize:

- user/channel should be considered an immutable part of the naming. They are not intended anymore as a quality stage or something that can be overriden and replaced.
- ``conan copy`` command has been removed in 2.0, as it violated the immutability principle.
- The idea is not overriding on user/channel. Instead, using packages from different remote repositories is the approach. Packages can be promoted (copied) from one "staging" repository to a "develop" or "production" repository, without changing their naming at all.

**Comment by retifrav** [comment]
Thank you for the clarification!
It makes sense to me that user/channel should be immutable, as the package maintainer likely meant to depend on this exact "fully-qualified" package reference.

So as I understand it, if user/channel is specified, then one cannot ignore/override them. And so then if some package depends on, for example, `zstd/1.5.2@some/thing` that is hosted in some remote repository, and a user of that package would like to fetch the package itself from that remote repository but at the same time to fetch `zstd/1.5.2` from Conan Center instead, then he won't be able to do it, would he, because Conan Center doesn't have `some/thing` user/channel for `zstd` package. And then the only way to "allow" user to fetch `zstd` dependency from Conan Center instead of that remote repository would be for the maintainer to drop the `some/thing` part from `zstd` reference in his package's conanfile, right?

**Comment by memsharded** [comment]
> So as I understand it, if user/channel is specified, then one cannot ignore/override them. And so then if some package depends on, for example, zstd/1.5.2@some/thing that is hosted in some remote repository, and a user of that package would like to fetch the package itself from that remote repository but at the same time to fetch zstd/1.5.2 from Conan Center instead, then he won't be able to do it, would he, because Conan Center doesn't have some/thing user/channel for zstd package. And then the only way to "allow" user to fetch zstd dependency from Conan Center instead of that remote repository would be for the maintainer to drop the some/thing part from zstd reference in his package's conanfile, right?

Yes, if your project is having one ``zstd`` package, the recommended way is to have one single instance of that package. Having some recipes in the graph requiring another user/channel, and then relying on it to be overriden to work is suboptimal. 

It can happen, for that case, overrides still work. You can define your specific ``zstd/....`` in the consumer, and that will override the upstream. But you need to be very careful with your ``package_id`` modes, because when you build the intermediate package alone, it will be built and linked against the ``zstd/1.5@user/channel`` different variant, and that can be a big problem in the later linkage, or even worse, at runtime. But if you control the build, the intermediate recipes cannot be changed easily, and as a temporary workaround, until the recipes are changed, it might be a possible approach.

What should be explicitly avoided is the usage of those overrides of user/channel as a promotion, versioning, or integration mechanism. It should be used just as a workaround, and it should be done with caution.

**Comment by technic** [comment]
Can you explain how to solve the problem explained in this issue with conan2 approach? To me having user/channel is fine because I see in the logs what is used. With the repositories it is hard to keep track what is coming from where.

**Comment by memsharded** [comment]
> Can you explain how to solve the problem explained in this issue with conan2 approach? To me having user/channel is fine because I see in the logs what is used. With the repositories it is hard to keep track what is coming from where.

This strategy is not something that we invented, it is a known good practice in the industry for all package management, in other languages and technologies. Packages in Conan 2.0 they always have revisions, that means they can be tracked in logs, lockfiles etc, with a unique identifier that guarantees its immutability no matter the origin of that package, if it is one remote repo or another repo. The multiple repositories strategy is not an identification strategy for packages, but a promotion (access, availability) of exactly the same package. Actually the package is exactly the same (which doesn't use extra storage space in servers like Artifactory, because of de-duplication) in different repos, when one package has been tested in CI, copied to the "QA" repo, tested and approved by the QA team, then copied to the final customer "releases" repo, you end with exactly the same reference of exactly the same package in at least 3 repos: the "develop" repo, the "QA" repo and the "release" repo.

**Comment by technic** [comment]
Ok. I am asking about first part of the question, where we want to override some package from conancenter. Or is it considered bad approach?

**Comment by memsharded** [comment]
> Ok. I am asking about first part of the question, where we want to override some package from conancenter. Or is it considered bad approach?

The issue with changing user/channel of packages from ConanCenter, is that it requires to change all the ``requires`` declarations of all recipes, increasing the diff/divergence from the upstream. So it is not necessary, it is perfectly fine to create your own package binaries from your own fork of ``conan-center-index``. The recommendation would be not to mix binaries from ConanCenter with your own binaries, if you are overriding some packages from ConanCenter, it is better to use your own binaries for all of them. So you will not really depend on the ConanCenter remote at all, but your own server, there will be no doubt at all where packages come from.

**Comment by technic** [comment]
@memsharded thanks a lot for your answer. I actually decided to open another issue https://github.com/conan-io/conan/issues/12729 where I described my problems in more details. I think you already answer part of it here.
