### ISSUE TITLE
[question] conan alias for all versions/channels of a package

### ISSUE THREAD

**Issue by jokram** [conan-io/conan#3989]
## Description
- I have a conan package with several versions on Artifactory which is used by several projects
- Now the conan user of that package shall be changed to reflect organizational changes without affecting the existing projects (they don't want to change the conan user name in the consumer recipes)
- I want to use conan copy to setup the new Artifactory repository with the new conan user name
- Now I would like to have a redirect from the old conan package name to the new for all versions (the old repository should only be a redirect to the new one), so that the old projects could still refer to the old conan user name which shall be redirected to the new one
- I was thinking about conan alias, but that only supports to redirect one version (or?)

=> Is there a way for one package to redirect from an old conan user name to a new conan user name **for all versions** (something like `conan alias Hello/*@olduser/* Hello/*@newuser/*`)?

## Environment
- OS: Windows 10 Enterprise
- Artifactory Enterprise 6.3.2
- Conan version 1.6.0

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @jokram 

No, there is no way to do such a redirect for all versions.

Regarding the promotions using user/channel, there are some ongoing discussions around it. We are considering some ways to be able to default them, or to set them at dependency graph level, but doesn't seem possible so far.

But specially if using Artifactory, it could be that the best flow would be to leave user/channel constant, and promote packages from Artifactory repository to Artifactory repository. Then switching them is as simple as switching remotes. This is considered good practice for other package types in Artifactory. Have you considered this possibility?

**Comment by memsharded** [comment]
I would say that there are 2 possible "clean" scenarios:

- Use a constant username, for all packages, and manage maturity, scope and permissions at the repository level. Do not change package usernames. Consumers define their repositories they want packages from. Everything is explicit. Extremely easy to control permissions, deprecate repositories, etc.

- Change the package usernames, change the consumers ``requires`` usernames. Everything is again explicit.

The problem with aliasing is that it basically cheats to the consumer. The consumer declares they are using "pkgA/version@devname/channel" and they will be getting "pkgA/version@companyname/channel", after two alias redirects from "devname"=>"teamname"=>"companyname". If there is some repository that contains the old "teamname" package, instead of the new alias "teamname" => "companyname", then that package would be retrieved instead, making it less deterministic. Furthermore, changing usernames might affect in some cases to the binaries IDs, if the consumers of that package defines so. 

We are considering some ways to be able to override user/channel at project scale, but still very preliminary. You might want to follow too: https://github.com/conan-io/conan/issues/3988

**Comment by memsharded** [comment]
Actually, I think this would be included in the ongoing discussion in #3988, please check and if true, close this issue, give feedback and follow up in the other one. Thanks!

**Comment by jokram** [comment]
I'm fine to continue any discussion in #3988.
