### ISSUE TITLE
[workspaces] make package_info() aware of workspace setup

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#4004]
When using the workspace feature and specifying `build` directories for the packages, the binaries are of course placed into these, e.g. executables are put into `<common parent dir>/mylib/build/bin`. In the `package_info()` of `mylib`'s conanfile.py though, `self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))` is done which works for the regular non-workspace setup but since `self.package_folder` points to the source folder in the workspace setup, it does not work there. Furthermore, `self.build_folder` is not set so it can not be used either.
Essentially the packaging step is naturally not performed in the workspace setup so there needs to be a way to deal with that e.g. in the `package_info()` method so e.g. the environment variables can be set accordingly since i don't see a way to make this transparent to the package. 
I don't know whether it would be better to let `self.package_folder` or `self.build_folder` to the build folder in the workspace setup or introduce another one like `self.workspace_build_folder`.

Conan 1.8.2 under Windows

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by solvingj** [comment]
This is the same quandry that came up in the initial consideration of the `--editable` feature.   

I've made the following recommendation to address both needs here:  https://github.com/conan-io/conan/issues/4142

**Comment by ytimenkov** [comment]
Another way to look at workspace is a generating of "umbrella" project which gathers all subprojects into a single generated build system as if they were just one single big project.

In this case there is an overlap between `package_info` and targets defined in build system: all compile and link flags come from their internal definitions.

I.e. for CMake `INTERFACE_*` / `PUBLIC_*` properties will be used instead (and they in fact should match ones defined by `package_info`).
Same true for `PATH`: targets produced by `add_executable` are automatically found by `add_custom_command` and dependencies are properly set.

Otherwise it won't be possible to set up dependencies properly (i.e. library or program built by one package should be treated as a dependency for a target built by other package).

**Comment by memsharded** [comment]
Hi @petermbauer 

I have had a look, and I think that the correct approach would actually be something like:

```python
def package_info(self):
      self.env_info.PATH.append(self.cpp_info.bin_paths)
```

This needs to be investigated, specifically what to do with ``self.package_folder`` (called ``rootpath`` in the ``cpp_info``)

**Comment by petermbauer** [comment]
Hi @memsharded 

with Conan workspaces as of version 1.9.2 i ran into a similar issue with a static library file being built by one of the packages in the workspaces setup:
As the file is not present when the initial `conan install` is done in the workspaces setup, CMake's `find_library` called in the `conan_package_library_targets()` does not find it so `-l<mylibrary>` is added to the compiler command which leads to an error since it is not found by the compiler.
Are such issues also solved with the new workspaces implementation?

Thanks

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
