### ISSUE TITLE
exports_sources with .gitignore support

### ISSUE THREAD

**Issue by GarrickLin** [conan-io/conan#4023]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I use conanfile.py in my own project and use `exports_sources = "*"` to export source code to conan. But there may be some data folders I don't need to export and in `.gitignore` file. Is there any way to support this feature to automatically ignore files already in `.gitignore` ?

**Comment by jgsogo** [comment]
Hi @GarrickLin 

Conan shouldn't being copying files that are being ignored. Our `Git` helper makes use of a function called `excluded_files()` ([docs here](https://docs.conan.io/en/latest/reference/tools.html#tools-git)) to filter out ignored files when copying to the cache.

In order to know which files our tool will be ignoring you can run this python lines:

```python
from conans.tools import  Git

p = "<path/to/your/repo>"
client = Git(p)
excluded_files = client.excluded_files()

# Variable `excluded_files` will contain all ignored files in your repo.
```

Please, let me know if those problematic files are inside the `excluded_files` variable

Thanks!

**Comment by GarrickLin** [comment]
`excluded_files` can correctly get all ignored filenames. But it still copy all files under source root dir to `export_source` folder while I am using `exports_sources = "*"`. I think there should one way to use variable `excluded_files` to prevent from copying excluded files. But I don't know how to use variable `excluded_files`.

**Comment by jgsogo** [comment]
Oh! Sorry, my bad. `export_sources` has nothing to do with the `scm` functionality (you only want both if you are working with an out-of-sources recipe to export license or helper files from the repo where the recipe is).

If you use `export_sources = "*"` Conan will export all mathching files (all of them) as you are telling Conan to do it explicitly. Use more concise expresion (or even a list) to select the files you want to copy. If your sources are in the same repo as your recipe, you can use just the SCM feature.

**Comment by jgsogo** [comment]
As you can read [here](https://docs.conan.io/en/latest/creating_packages/package_repo.html?highlight=scm#recipe-and-sources-in-the-same-repo), you can use _"the scm attribute of the conanfile to capture the remote and commit of your repository automatically."_. ([More doc here](https://docs.conan.io/en/latest/creating_packages/package_repo.html?highlight=scm#capturing-the-remote-and-commit-scm-experimental))

If the docs are not enough, or you find something that should be explained better, please let us know so we can improve the documentation. Thanks!

**Comment by jgsogo** [comment]
Hi @GarrickLin, did you try it? Does the SCM feature fit your needs?

**Comment by jgsogo** [comment]
Sorry, but I think I need more information about the recipe itself, the layout of the repository and the files that are included in the `.gitignore`. Can you copy here a minimum reproducible example?

In the mean time (just guessing). I suppose that your `subfolder` is something that is ignored in your repository and it gets copied to the local cache (and then it may get packaged if your `package` method matches those files).  There is an optimization related to the SCM, it does the following: if the repo is local Conan will copy it instead of cloning ([here is the line of code](https://github.com/conan-io/conan/blob/e731beeff8bda8c25843521fc9a9a8f5f06da548/conans/client/source.py#L202)), but it should ignore the same files as the repo.

**Comment by GarrickLin** [comment]
here is the 1 level folder tree of my project root:
```
.
├── build.py
├── build.yml
├── cmake-build-debug
├── cmake-build-debug-himix100
├── cmake-build-x64-tensorrt-debug
├── CMakeLists.txt
├── common
├── conanfile.py
├── data
├── examples
├── include
├── models
├── modules
├── python
├── README.md
├── scripts
├── tools
└── versioning
```
and here is my .gitignore file
```
.idea/
*.pyc
build*/
cmake-build*/
data/
```
and here is 1 level folder tree of my  `~/.conan/data/project/user/channel/source ` folder
```
.
├── build.py
├── build.yml
├── CMakeLists.txt
├── common
├── data
├── examples
├── include
├── models
├── modules
├── python
├── README.md
├── scripts
├── tools
└── versioning
```
it does ignored `cmake-build*/` but still contains `data/`

**Comment by GarrickLin** [comment]
Sorry, my bad! `data/` folder contains some tracked files before. It works after untracking all files under `data/` folder!

**Comment by jgsogo** [comment]
Oops! I didn't see your last answer, closing as it was no longer an issue.

Thanks.
