### ISSUE TITLE
Problem with C:\Users\<username>\.conan\conan.conf [general] user_home_short being ignored

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#4031]
We found that ```C:\Users\redacted_username\.conan\conan.conf``` with settings:

```
[log]
run_to_output = True        # environment CONAN_LOG_RUN_TO_OUTPUT
run_to_file = False         # environment CONAN_LOG_RUN_TO_FILE
level = 50                  # environment CONAN_LOGGING_LEVEL
print_run_commands = False  # environment CONAN_PRINT_RUN_COMMANDS

[general]
default_profile = default
compression_level = 9                 # environment CONAN_COMPRESSION_LEVEL
sysrequires_sudo = True               # environment CONAN_SYSREQUIRES_SUDO
request_timeout = 60                  # environment CONAN_REQUEST_TIMEOUT (seconds)
user_home_short = E:\redacted\redacted_username\.conan # environment CONAN_USER_HOME_SHORT

[storage]
path = ~/.conan/data

[proxies]
no_proxy_match = *.dev.redacted.com*
http = http://devproxy.redacted.com:82
https = http://devproxy.redacted.com:82

[plugins]
attribute_checker
```

is being ignored, and still writing short files in the default c:\ drive location.

This was witnessed in person by @lasote  ;-)

Perhaps https://github.com/conan-io/conan/issues/4030 would help us debug this?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [1.8.4 Windows] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
I think I might know one reason: If the cache is already populated, and have some pointers pointing already to ``C:\.conan``, changing the ``user_home_short`` won't automatically redirect them. It is necessary to remove the packages first, to break the links. Otherwise, packages in the cache will keep point to ``C:\.conan``

Please try completely removing the cache and the ``C:\.conan`` folders, and running again.

If confirmed we could try to think if it makes sense to try to put some warnings, something to be documented or what could be done.

**Comment by michaelmaguire** [comment]
We tried removing all the cache before but it didn't help.

**Comment by memsharded** [comment]
This seems inactive.
Also Conan 2.0 already completely removed ``short_paths``, so maybe this can be closed?

**Comment by memsharded** [comment]
Conan short paths in Windows and ``conan.conf`` config have been removed in Conan 2.0, closing this as non relevant anymore.
