### ISSUE TITLE
conan build command's --source-folder flag doesn't like ..

### ISSUE THREAD

**Issue by ehargitt** [conan-io/conan#4077]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan=1.10.0
OS=CentOS 7
Python=3.7.0

My goal is to build a local copy of my project in a folder called `build_native` in the top level of my source tree so that I can debug locally. Here is what it looks like:
```bash
.
├── build_native
│   ├── conanbuildinfo.cmake
│   ├── conanbuildinfo.txt
│   └── conaninfo.txt
├── cmake
│   ├── ...
├── CMakeLists.txt
├── conanfile.py
├── conanfile.txt
├── src
```

While inside the `build_native` folder, I run `conan install .. --build`. Works ok. Next I try to run `conan build ..` and I get an error that says:
```bash
(conan) -bash-4.2$ conan build ..
Project: Running build()
CMake Error: The source directory "/home/domain/ehargitt/Perforce/sw_products/unicorns/embedded/core/sparkles/main/build_native" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
ERROR: PROJECT: Error in build() method, line 17
        self.run('cmake -G"Unix Makefiles"')
        ConanException: Error 256 while executing cmake -G"Unix Makefiles"

```

In the help comments it states that the source folder defaults to the location of conanfile, which I specify with the positional argument. Adding the flag `-sf=..` results in the same error.

**Comment by memsharded** [comment]
I think the issue can be because you are using the ``self.run('cmake -G"Unix Makefiles"')``, and that runs in the current build folder if you don't specify otherwise, which is your current folder. The source folder is where the ``conanfile.py`` is, but the build folder is typically another one, a temporary one to not pollute the source folder, in your case, the ``build_native`` one.

Have you tried using the ``CMake`` helper? It helps to automate some of these tasks.
Otherwise, you might want to use ``self.build_folder`` and ``self.source_folder`` in your command line ``self.run("cmake...")`` to work correctly in different places (including the conan local cache if you later create a package with it).

please tell me if this helps. Thanks!

**Comment by ehargitt** [comment]
It looks like using the CMake helper functions fix this. Thanks for the info.

**Comment by memsharded** [comment]
You are welcome!

I think this issue can be closed then, but please re-open or comment if you have further questions or need more help. Thanks!
