### ISSUE TITLE
create tools.add_bin_to_path(self) method

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#4116]
This one seems easy to implement, it's just a question of whether or not it's worth it.  I'm not sure, but I can say that I've done the following more than 20 times, and still copy and paste from the documentation every single time: 

`self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))`

Maybe there's a better approach like `self.env_info.add_bin_to_path()`. I don't know.

It seems cosmetic, so I was asking myself "whats the difference?".  I see little advantages, but they're so minor it feels silly.  

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
The call should be ``self.env_info.add_bin_to_path(self)``, because it internally needs access to ``self.cpp_info.bindirs`` and ``self.package_folder``.

I think in this case, it is a level of abstraction that in 99% of cases won't make a difference in lines of code, but an abstraction that needs to be learned, to know what is doing inside... I'd say it is better to keep the explicit version, even if a bit more verbose it is evident what is doing.

That is my opinion, lets ask @jgsogo for feedback too to check.

**Comment by jgsogo** [comment]
Completely agree, I think it is better to have the explicit version.

**Comment by memsharded** [comment]
Ok, yes, this can be closed by now, unless the use case becomes more complex in the future, in that case, please reopen.
