### ISSUE TITLE
Add common method to get ConanFilePath from command line

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4157]
The implementation of ConanFilePath can be extended to other commands to parse command line arguments.

_Originally posted by @lasote in https://github.com/conan-io/conan/pull/4152_

--- edit with more info

The referenced PR (now superseded by #4181) introduces an argsparse Action to get the path to the `conanfile.py`, it is as follows. This approach can be used for other commands too:

```python

class ConanFilePath(argparse.Action):
     """ Expect a path to a conanfile.py file or to the directory where it is located """
     def __call__(self, parser, namespace, values, option_string=None):
         prospective_dir = values
         try:
             conanfile = _get_conanfile_path(path=prospective_dir, cwd=os.getcwd(), py=True)
             setattr(namespace, self.dest, conanfile)
         except ConanException:
             raise argparse.ArgumentError(None, "Editable package at {} must contain "
                                                "a 'conanfile.py' file".format(prospective_dir))
 
  
  class ConanFilePathOptional(ConanFilePath):
     def __call__(self, parser, namespace, values, option_string=None):
         if not values:
             setattr(namespace, self.dest, None)
         else:
             return super(ConanFilePathOptional, self).__call__(parser, namespace, values,
                                                                option_string=option_string)
 

```

Usage example can be:

```python
parser.add_argument('target', help='Path to the package folder in the user workspace',
                             nargs='?', action=ConanFilePathOptional)
```

**Comment by lasote** [comment]
I did what? Is there a `conan info --paths`. Please tag the issue correctly.

**Comment by memsharded** [comment]
From https://github.com/conan-io/conan/pull/4181#discussion_r243259310

> It definitely doesn't belong to this layer, but the the API one. As the conan_api can receive the same command, with a path, it will have to check anyway if the conanfile.py is there. And then it will be repeated code.
Please, leave command.py as simple as possible, almost no business logic, and defer the checks of arguments consistency to the conan_api.py

That is my opinion. The API (conan_api.py) should implement argument checking, not the ``command.py``, which responsibility is to capture user output, not to implement business logic. The path to a conanfile.py may exist or not, but it is not the responsibility of the ``command.py`` to know, but from the business logic implemented behind the API. E.g. for a given path, in one case the ``conanfile.py`` shouldn't exist, because it will be created (``new``), for another case, a ``conanfile.py`` must exists (``build``) and for other cases, either a ``conanfile.txt`` or ``conanfile.py`` could exist (``install``). This logic so far has belong to the ``conan_api``.

We could say that a "valid" conanfile, absolute path (including extension .txt, .py) should be provided always to the API. This is very evident for the path, but what happens with other business logic?:

- References: should the API assume that when a reference is passed it will always be valid? Can it fail with uncontrolled errors, or should validate the input. BTW, the input for the API for references are strings, so the users don't need to create ``ConanFileReference`` objects outside of the API. In theory the API only exposes primitives types, no internal conan types.
- Folders: ``build_folder``, ``install_folder``, ``source_folder``. In many cases, these should exist, in others they will be automatically created, so they don't need to exist. Should the API assume all these preconditions or check them internally to the API.

**Comment by jgsogo** [comment]
If the `whiteboard` is invocated, then it should be moved to `triaging`, it is not clear enough to start coding. 👨‍🏫

**Comment by lasote** [comment]
Well, I think there is a very narrow line here. We could play to the devil's advocate and say that when we are doing this in the command.py, is also "business logic":

```python
 try:
    try:
        reference = ConanFileReference.loads(args.path_or_reference)
    except ConanException:
        info = self._conan.install(path=args.path_or_reference...
    else:
        info = self._conan.install_reference(reference, ...
except ConanException as exc:
    info = exc.info
    raise
```
The difference here is the api provides two different endpoints `install` and `install_reference`, but it is indeed the same "business logic".

> BTW, the input for the API for references are strings, so the users don't need to create ConanFileReference objects outside of the API. In theory the API only exposes primitives types, no internal conan types.

In that example we are passing a parsed ConanFileReference to the `install_reference` and then the conan_api is validating again the reference.

I'm not saying that the check should belong to the `command.py` I'm saying that your arguments applied to other `command.py` parts are not totally valid/clear.

Said that, in this case I would prefer to move it to the `conan_api` because it is true that the arg check is a bit ugly and not much explicit. But I don't like much an API with open arguments as "a folder or a conanfile" but maybe more methods like the "install" and the "install_reference". What about a method in the api to get the target and then calling the method with the abs path to a conanfile?

**Comment by jgsogo** [comment]
> don't like much an API with open arguments as "a folder or a conanfile" but maybe more methods like the "install" and the "install_reference"

💯

**Comment by lasote** [comment]
I think we have enough development restrictions with the documented things, so for me everything that could be done before Conan 2.0 and without maintaining the two major feature branches, the better. But I would like to do it right, defining first exactly the changes, which layer has which responsibilities and eventually discussing/documenting the new API interface before doing any change. We should open a new issue for that.

**Comment by jgsogo** [comment]
If we have already agreed that the conan_api is a border which will only cross raw data (text, json format,...) I think that this issue makes no sense. The `_get_conanfile_path` should be enough inside the `conan_api` to handle a path a retrieve the proper conanfile (or raise a meaningful error), we don't need to check it too outside it.

So... closing in 3, 2,...
