### ISSUE TITLE
Make short paths more readable

### ISSUE THREAD

**Issue by wpalfi** [conan-io/conan#4163]
Short paths are currently something like ```C:/.conan/f1wnl4ap/```.
It would be helpful to add the package name to the folder name, e.g. ```C:/.conan/zlib_f1wnl4ap/```. 

Conan 1.10.2, Windows

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
We are going in this direction at the moment: https://github.com/conan-io/conan/issues/3971

Basically, using deterministic short-paths, but not necessarily including the package name. This wouldn't scale to many people that have very long names in their packages: ``MyCoolFunctionalPackageFactoryLibrary``. Furthermore, navigating the short-paths cache manually shouldn't be a use case (even navigating the normal cache, for most users shouldn't be a use case either), what problem are you trying to solve with that?

**Comment by wpalfi** [comment]
> navigating the short-paths cache manually shouldn't be a use case ... what problem are you trying to solve with that?

When we set up a new project with many dependencies, we often have some compiler/linker errors and need to find out why. Then we look at the CMake output and and the generated VS-files, but there are often only long lists of short paths. It would just be easier to find the problem if there would be some hint in the folder names.

> many people that have very long names in their packages

Just truncate the long names?

**Comment by memsharded** [comment]
Thanks for the feedback, now I understand better the issue. 

> Just truncate the long names?

To which length? Because one issue is that projects very often use naming scheme like ``MyProjectMyCoolPackage``. Truncating to lets say, 5 first characters, would reduce the entropy of the hash a lot, and that would require extending the hash by the same amount, and then increase the risk of hitting the limits of the long paths. Right now the short paths are implemented with just 7 chars, and there are users suffering with cases when that is very close to the limit already.

I understand that compiler/linker errors would give information about filenames or library symbols, which should be not perfect, but enough to understand which component they refer to, aren't they? 

I am having a look, and there is the further problem that the "path_shortener" is a complete abstraction over the paths, but it doesn't have knowledge about the conan model, or the package names. Adding them would probably make it very coupled and dirty, so we need to consider the introduced complexity for the value. I am very sorry, but I think that so far, it is not something that we could implement.

**Comment by wpalfi** [comment]
No big deal, was just an idea.

**Comment by memsharded** [comment]
Btw, current work in https://github.com/conan-io/conan/pull/4238, adds a "real_path.txt" file in the short-paths cache, that would make grepping for packages very simple, as the conan reference ``pkg/version/user/channel`` will be directly stored there in that path.
