### ISSUE TITLE
Metadata: store the installed system requirements? other things?

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4226]
It could replace the current files written in the local cache.
It could ease #3760
This could be part of the investigation of moving more things to the metadata.

**Comment by memsharded** [comment]
Other things that could make sense to be moved to metadata:

- The remote information. Instead of living in the ``registry.txt``. This would completely avoid locks over ``registry.txt``. I have done a small check into the codebase, not complicated, but would need to define storage and relation to ``Remotes`` in the registry.

There are some implementation things that could or maybe doesn't make sense to be part of "metadata":
- The ``scm_folder.txt`` link file: is an implementation detail, an optimization

**Comment by memsharded** [comment]
No longer relevant.
