### ISSUE TITLE
Version `x.y.z-pre` not included when using `[>=x.y.z, include_prerelease=True]`

### ISSUE THREAD

**Issue by robinmoussu** [conan-io/conan#4343]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.

conan 1.11.2
archlinux (up-to-date)

- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I don't understand why `>=` doesn't work in my conanfile.py with pre-release

```
➜  RollOrDie3 git:(master) ✗ conan search Catch2
Existing package recipes:

Catch2/2.5.0@catchorg/stable
Catch2/2.5.1-pre.1.34.g084b1d5f@local/testing
```

If I have the following lines in my conanfile.py, it works:

```
requires=(
    ...
    "Catch2/[>2.5.0, include_prerelease=True]@local/testing",
    ...
)
```

But if I replace the version by a `>=` range, it doesn't find it.
```
requires=(
    ...
    "Catch2/[>=2.5.1, include_prerelease=True]@local/testing",
    ...
)
```
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: Version range '>=2.5.1,include_prerelease=True' from requirement 'Catch2/[>=2.5.1,include_prerelease=True]@local/testing' required by 'PROJECT' could not be resolved
make: *** [/home/robin/dev/RollOrDie3/Makefile:18: /home/robin/dev/RollOrDie3/build/.dependencies_installed] Error 1
```

According to the [documentation](https://docs.conan.io/en/latest/mastering/version_ranges.html?highlight=ranges), it should take the pre-release into account when searching.

I think that either the documentation should be updated or the pre-release included when using `>=` with the flag `include_prerelease=True`.

---

I don't think it's related, but the version returned for my compiler isn't the right one
```
➜  RollOrDie3 git:(master) ✗ LANG=C gcc --version
gcc (GCC) 9.0.0 20190107 (experimental)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Unless it's related, don't commend on this to not flood the thread.

**Comment by Minimonium** [comment]
Just to clear things out a bit
```
I think that either the documentation should be updated or the pre-release included when using >= with the flag include_prerelease=True.
```
I think that the documentation stands correct. `include_prerelease` does what it does in the docs, but maybe it can misslead by its name into thinking that it includes prereleases of the current normal version into the range of allowed versions. But the precedence is `2.5.1-pre < 2.5.1 < ...` and according to the SemVer spec the `>=2.5.1` excludes the `2.5.1-pre` by the precedence rules. 

The questions here:
* Should Conan special-case situations where it needs to pull up closest prereleases into the valid range? 
* Can it be done now with existing tricks like `~x.y.z-0 || >=x.y.z`?
* Since the SemVer spec says `A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version` should it behave like you propose? 

For example, it could be done via an additional flag so it could:
1. Keep the expected precedence intact;
2. `include_prerelease` as before introduces prereleases to the range of evaluated versions without breaking the rules of the precedence;
3. `new_flag` to allow the prerelease into the resolving solution.

**Comment by robinmoussu** [comment]
> Let me know if you have doubts or any proposal around this issue, although I think that it is not worth to implement anything on top of current semver packages, it will lead to confussion about expected behavior.

@jgsogo If this was the expected behaviour, then I would just add a note on the documentation that `=` doesn't include the pre-release even with the flag `include_pre-release` and that you need to use `~` instead.

It could also be possible to use `[>~x.y.z, include_prerelease=True]` to include the prerelease of `x.y.z`, if it was considered something that should be develop (but I think that adding a note in the doc is enough).

**Comment by jgsogo** [comment]
Hi!

The library `node-semver` is working as expected: `2.5.1-pre` is a version previous compared to `2.5.1`, no matter the value of the argument _prerelease_.

If you want to include `2.5.1-pre` in your search, you have to start from a point previous or equal to that version, something like `2.5.0`, `2.5.1-pre`, `2.5.1-0`,... you can check this behavior online (i.e [here](https://semver.npmjs.com/)).

**Comment by rkeithhill** [comment]
This was a very helpful discussion. Thanks!d
