### ISSUE TITLE
cmake_multi & targets 

### ISSUE THREAD

**Issue by jano42** [conan-io/conan#4374]
## Context

I'm working on a c++ OSS projects; and I'm doing the migration to use conan !

I'm using conan with the cmake_multi generator, and I've followed the documentation:
https://docs.conan.io/en/latest/integrations/cmake/cmake_multi_generator.html#targets-approach

The documentation example works on a windows environnement; but it fails on linux.

````cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo_multi.cmake)
conan_basic_setup(TARGETS)
````

Conan : 1.11.2
CMake : 3.13.3
Windows : Windows 10 64 bits with VisualStudio 2017 (15.9.5)
Linux : Ubuntu 18.10 64 bits

## Error
The errors on linux : include dirs and link libraries are not added to my target.

When building I have the following error:
```
home/jmdecoret/dev/test/sources/main.cpp:1:10: fatal error: boost/format.hpp: No such file or directory
 #include <boost/format.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

If I manually add boost include dir; then I've link problems.
I don't understand what is going on.

## Reproduce & sample
In attached file, I've wrotten a sample program which illustrate failure. At root there are two scripts on for Windows and another for Linux. the aim of those scripts is to call conan, generate cmake files and build Debug and Release. (the only difference with example is that with Windows/MSVC it builds statically)
[test.zip](https://github.com/conan-io/conan/files/2790876/test.zip)

Could you help me and have a look 

## More
It also fails on travis-ci (Ubuntu 14.04.5 LTS)

**Comment by uilianries** [comment]
Hi @jano42 !

Since you are trying to build on Linux, the dynamic option `--config` is not supported, you will need to set the definition [CMAKE_BUILD_TYPE](https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html). It's a CMake feature, not a Conan limitation. I would say to use `cmake` generator instead, otherwise, you could update your bash script to:

```shell
#!/bin/bash

#move to project directory
BASEDIR=$(dirname $0);
set -e
echo "BASEDIR: $BASEDIR"
cd $BASEDIR/projects

echo "Run conan..."

conan install --build missing -s build_type=Debug -o boost:fPIC=True ../sources
conan install --build missing -s build_type=Release -o boost:fPIC=True ../sources

cmake ../../sources  -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
cmake --build .

cmake ../../sources  -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
cmake --build .
```
But there is a problem here, both Release and Debug will be generated over same folder.

You could use the trick in [cmake_multi_generator](https://docs.conan.io/en/latest/integrations/cmake/cmake_multi_generator.html#creating-packages) to include the correct cmake file.

**Comment by memsharded** [comment]
cmake_multi generator was deprecated long time ago in 1.X and removed in 2.0, closing this issue
