### ISSUE TITLE
question: compiler dependant linking

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#4387]
Hi there,
I have a thrid party package that contains C libs and C++ libs.
Is it possible in Conan to specify compiler specific libs? 

For example like this:
self.cpp_info.c.libs = ["abc_c", "def_c"]
self.cpp_info.cxx.libs = ["abc_cpp", "def_cpp"]

Best regards

**Comment by uilianries** [comment]
`cflags` and `cppflags` maybe?

https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info

**Comment by memsharded** [comment]
You could try with ``cflags`` and ``cppflags`` yes. 

The main problem is that there is no model of C and C++ consumer (settings). The compiler version and other things could be specified, but not "I am using C or C++". 

What you propose is correct, the only issue is that it is not fully automatic. That will translate in the consumers, e.g. with the "cmake "generator, to:

```cmake
SET(CONAN_MY_PKG_C_LIBS abc_c def_c)
SET(CONAN_MY_PKG_CPP_LIBS abc_cpp def_cpp)
```
with the automated default behavior, you will get link errors, as the consumer won't have CONAN_LIBS defined, and is the consumer the one that should explicitly opt to use one or the other.

Note that however, this will generate some incongruencies with the binary model, in theory, the package would have ``settings.compiler.libcxx`` setting, because it is building C++ libraries. But if a consumer would like to only link with the C version, it would still need to specify a ``libcxx`` value to be able to resolve to a package, even if its not being used. 
It might be possible to use the ``libcxx=None`` to identify C-only builds, and use the same library name, with the standard ``self.cpp_info.libs``, because then, when the package settings libcxx is None, it will be able to select the pure C version. So you won't have a binary package with both variants, but you could have something like:
- A binary package for the C variants
- A binary package for the C++ variant (with libcxx=libstdc++)
- A binary package for the C++ variant (with libcxx=libstdc++11)

**Comment by Johnnyxy** [comment]
@memsharded you are right about the runtime (libcxx) setting. With that it would be pointless to have C libs in a package. I oversaw this :). Thx.
