### ISSUE TITLE
How do I create a package and upload?

### ISSUE THREAD

**Issue by Meai1** [conan-io/conan#440]
Hi,
Currently I'm stuck at getting any of the sources and binaries into the export.

I tried:

```
[pc@localhost mytimer]$ conan export demo
WARN: Conanfile doesn't have 'url'.
It is recommended to add your repo URL as attribute
WARN: Conanfile doesn't have a 'license'.
It is recommended to add the package license as attribute
MyTestTimerXXX/1.0@demo/testing: A new conanfile.py version was exported
MyTestTimerXXX/1.0@demo/testing: Folder: /home/pc/.conan/data/MyTestTimerXXX/1.0/demo/testing/export
```
I tried:

```
[pc@localhost mytimer]$ conan upload MyTestTimerXXX/1.0@demo/testing --remote local
Uploading MyTestTimerXXX/1.0@demo/testing
Please log in to perform this action. Execute "conan user" command. If you don't have an account sign up here: http://www.conan.io
Remote 'local' username: demo
Please enter a password for "demo" account: 
Change 'local' user from None (anonymous) to demo
Uploading conanmanifest.txt                                           
[==================================================]                  
Uploading conanfile.py                                                
[==================================================]                  
Uploading conan_export.tgz                                            
[==================================================]                  

```

Ok sounds great but in both cases when I look into those folders there is a zip file with only the "conanfile.py".
I need the sources, the CMakeLists.txt file, the build output... right?
Apparently I need to do it somehow like this:

```
    def source(self):
        zip_name = "%s.zip" % self.branch
        download("https://github.com/lasote/electric-fence/archive/%s" % zip_name, zip_name)
        unzip(zip_name)
        os.unlink(zip_name)
```

But this downloads something from github? Can't I use sources that I have saved locally? 
And I still dont know how to add binaries...
I seriously dont understand the relationship between the 'copy', 'install', 'export', 'package' commands.

Also a question I have is how will this work when I want to deploy my application somewhere but it will have loading paths set to some ~/.conan folder. Is there a way to put all the libs into the same folder as the binary .. well does package do that?

**Comment by memsharded** [comment]
Yes, sure, there are two approaches for getting the source code to build the package:

1. The "external" repo. You create a package but the code is actually somewhere else, in a github repo, or you want to download from sourceforge: you use the ``source()`` method

2. The "internal" repo. You have the conanfile.py in the same place, repo, project than the source code, then you specify ``exports = "*"`` in your conanfile. That instructs to copy all the files from your folder, to the conan package storage (local to your computer you can inspect the folder in ``~/.conan/``), so it can be used from there as a package. Read carefully the guide in http://docs.conan.io/en/latest/packaging/creating_in.html, and check the  ``exports = "*"``

It is generally a good idea to first follow the docs, they are written in a tutorial like style, most things can be actually executed.

Consider these flows:

- Export: copy conanfile.py and possible other files like sources from the project folder, to the local conan storage
- Import: copy files (typically shared libraries) from the local conan storage to the project folder
- Upload: copy files from the local conan storage (project not needed) to a remote conan server (like conan.io)
- Install: copy files from a remote conan server to the local conan storage. Though in this case it can build binaries locally if instructed to,  instead of retrieving them from the remotes.


Then, don't worry too much about uploading to any remote, including conan.io, until you have a good grasp of how conan is working. Absolutely everything in package creation can be tested locally. The last step, when you have your package recipe working, and you have built some binaries, you might consider uploading them. It is also a good idea to check the functionality of ``test_package``, it is something really useful for package creators: http://docs.conan.io/en/latest/packaging/testing.html

If you want to deploy your application, you can use conan to do it, or maybe the ``imports`` feature (http://docs.conan.io/en/latest/manage_deps/conanfile_txt.html#imports, but also can be done in conanfile.py) is useful for you. It can collect the files you want (typically the shared libraries) and copy them to your project folder. Another possibility is to use the environment variable CONAN_USER_HOME, and set that for your project in a project ``deps`` folder, so all the dependencies are saved there, they will not be in ``~/.conan``.

I hope this clarifies a bit the issues. Cheers!

**Comment by memsharded** [comment]
Hi @Meai1, any new on this issue? Did my response help? Please tell me if worked (and the issue can be closed), or you need further help. Thanks!

**Comment by Meai1** [comment]
well this is all quite complicated and you didnt mention what the 'package' option does and i dont have an 'import' option on my cmdline.

i dont really understand the meaning of all these path options and the purpose, like why are there all these "testing" directories. Do i really have to set up all the include/lib/binary folders and basically copy them myself through the .py config file? it all seems very manual?

also i tried 

> conan new MyLib/1.2.3@user/testing

and i have no idea how to build this? like i said, 'import' doesnt exist. There is no source, just the config files

**Comment by memsharded** [comment]
Lets go step by step. I see two paths to learn how to create packages with conan:

1) Following the tutorial in the docs: http://docs.conan.io/en/latest/packaging/creating_in.html
2) Starting with someone else existing package and work with their package first to learn

I suggest starting with 1). In that case, it would be good if you could follow the steps given in the docs instructions, and stop in the first thing that fails, and report it here. That would give us a good insight of what is failing or what could be fixed or improved in the docs to explain it.

**Comment by memsharded** [comment]
I am closing this issue, as it is not a real bug/problem/feature request, but more of general questions and explanations about the tool usage. Please feel free to re-open again or just follow the conversation if you need more help, or contact through other channels (twitter, freenode #conan channel, email...) for assistance. Thank you!
