### ISSUE TITLE
Prevent conan alias from overwriting existing packages

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#4423]
When creating an alias package with `conan alias` it is easy to mix up the order of parameters:

* Correct: `conan alias boost/ALIAS@conan/stable boost/1.69.0@conan/stable`
* Wrong: `conan alias boost/1.69.0@conan/stable boost/ALIAS@conan/stable`

In case you're accidentally calling the wrong order you're overwriting the package you initially wanted to reference. If this happens you render your original package useless and need to remove it. Then you can start all over again.
It would be perfect to have a built-in check that tells the user that the existing package `boost/1.69.0@conan/stable` already exists and will be overwritten by an alias package - and if the user is really sure this is what he wants to do.

Happens to me with Conan 1.11.0.

**Comment by monsdar** [comment]
I just found that a similar feature has been discussed within #3805 - the issue is just named in a way that it's hard to see on first glance what's going on there.

**Comment by memsharded** [comment]
I have added it as "ux", because it is mostly a check. There are some possibilities:

- Throw an error if the package exists, and require ``--force``. Good, but will be breaking.
- Interactive: "are you sure you want to overwrite?". This might break also users using alias in CI (which is typical)
- Opt-in: define a ``--check`` argument (or something similar), that forces the alias to do this check, and will throw an error

It is a simple feature, but I see no way to do it both effectively and nonbreaking.
