### ISSUE TITLE
Bypass interactive password entry for CI system

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#445]
My CI system builds my component - if this was successful it should upload the package onto our Conan server. Problem is that conan asks for the user-password every now and then.

On the build machine itself I configured conan with `conan user -p MyPassword -r MyRemote MyUser`. But this does not seem to solve the issue.

Is there a way to store the password for certain users without timelimit? If not, is it possible to provide a password via script (no interactive interface)?

**Comment by memsharded** [comment]
Because of security, the conan_server is expiring the tokens periodically. If you setup in your ``server.conf`` the expiration tokens to a large enough amount, setting the user as you do in the build machine should work. Remember to reset the conan_server after changing the conf, it is not reloaded automatically.

**Comment by monsdar** [comment]
A way to give the user and password via parameter would be good. Like the following:
`conan upload --user MyUser --password MyPassword -r MyRemote Comp/1.0@MyUser/Channel`

For the moment I'll just put the user command into the CI scripts.

**Comment by monsdar** [comment]
Before having this closed too early: Would it be a good enhancement to extend the command line like I suggested? I had a quick look into the code, but I'm not a Python developer per se and couldn't find a fast way to implement this.

**Comment by memsharded** [comment]
It could be implemented, but it is a security issue. We had to implement a ``conan user -p MyPasswd``, because there should be some way for CI systems to specify the password, but each password that is not hidden increases the potential security problems. What is exactly the problem of issuing two commands, one after the other?

Maybe the issue is that you should set the user/password of your remote specifying it:

```bash
$ conan user MyUser -p MyPassword -r MyRemote
$ conan upload Mypackage/0.1@MyUser/stable -r MyRemote
```

**Comment by monsdar** [comment]
It's not an issue for me. I just felt that from a usability standpoint it could be better to enhance the `upload` command with this feature.

**Comment by memsharded** [comment]
Maybe for usability, but we have had another look and still think that having just one point (command) were the password is clear-text, is the best option, to minimize potential security hazards, so lets keep the tradeoff for this one. Thanks!
