### ISSUE TITLE
[suggestion] Provide a wrapper script which downloads a self-contained version like gradlew

### ISSUE THREAD

**Issue by htfy96** [conan-io/conan#4456]
The benefits of providing a wrapper script like [gradlew](https://docs.gradle.org/current/userguide/gradle_wrapper.html) and a self-contained version of conan are:
- Standardize conan version to build a project
- Better spreading of conan: new users can simply use conan with `./conanw build`, without spending time on installation

AppImage might be a good choice for bundling conan: https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps

**Comment by memsharded** [comment]
Hi @htfy96 

Not sure if I understand the whole of your feedback.

In most scenarios, it is solved with ``pip install conan==<version you want> --upgrade``, because many systems already come with python.

For a self-contained version of Conan, we are already doing that with pyinstaller, and release the self-contained binaries with .deb and .exe installers in our site. The pyinstaller code is in the root of the repo, to allow other users to create the self-contained conan for any platform.

**Comment by memsharded** [comment]
CLosing as inactive
