### ISSUE TITLE
Conan 0.11.1 can no longer detect my GCC 4.8.5 compiler

### ISSUE THREAD

**Issue by nathanaeljones** [conan-io/conan#448]
0.11.0 was working correctly

```
It seems to be the first time you run conan
Auto detecting your dev setup to initialize conan.conf
ERROR: Unable to find a working compiler
Default conan.conf settings
	os=Linux
	arch=x86_64
	build_type=Release
*** You can change them in ~/.conan/conan.conf ***
*** Or override with -s compiler='other' -s ...s***


WARN: config() has been deprecated. Use config_options and configure
ERROR: Conanfile: 'settings.compiler' value not defined
```

```
 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.5 (Ubuntu 4.8.5-2ubuntu1~14.04.1) 
```

**Comment by nathanaeljones** [comment]
Wait, there are other factors; ccache is involved.

**Comment by nathanaeljones** [comment]
Even stranger; this only happens when running a  bash script; when using an interactive terminal - `conan user` works!

**Comment by nathanaeljones** [comment]
ccache can break gcc when first run with insufficient permissions. Running `conan user` directly in Dockerfile avoids this.

**Comment by traceon** [comment]
Same happens if conan (0.17.1) is started from within cmake via execute_process(), and CONAN_USER_HOME is set to somedir, where somedir/.conan does not exists.
If the same is done from a bash prompt - everything works.

**Comment by memsharded** [comment]
Hi Denis,

I would need a bit more context for your issue:

- Are you running in your machine, or in CI server? Which OS, is it linux gcc? I guess CI, otherwise, it is not a big issue, as it is only used for the default, in ``conan.conf`` and that can be changed easily
- Maybe the detection from cmake is somewhat altered by cmake. Can you please run ``execute_process()`` gcc in your machine and check the output?
- I don't think that CONAN_USER_HOME is related, but as you told, being the first time that detection is launched due to the missing conan.conf. You can check the normal installation but just removing conan.conf.

Please tell me a bit more, to see if we can help to fix it. Thanks!

**Comment by traceon** [comment]
Hi James,

I am on macOS, my machine. Yes, indeed, it is related to missing `conan.conf`. At first run, when it is generated, `conan` fails to detect the compiler. I ran `env` from `execute_process()`and it turned out that `cmake` on first run (but not on subsequent ones) set `CC` and `CXX` to `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc` and `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++` respectively. This confuses `conan`'s compiler detection routine.
I worked around this by setting `CC` and `CXX` env vars to an empty string right before calling `execute_process()` (this doesn't unset them, at least when done from cmake script in macOS), which in its turn causes `cmake` not to set them, and pass to `conan` as-is. And in case of existing but empty `CC` and `CXX` `conan` is able to detect some default system compiler properly.

**Comment by memsharded** [comment]
Thanks very much for your detailed response, that clarifies a lot.

But now I am not sure what conan could do to improve over this:

- If conan sets CC and CXX to empty strings, it might be removing some valid CC and CXX vars that the user had set and would like to use as the system default.
- If not set, they will take the XCode default one, which might not be the intention.

So I think that the possible solutions are on the user side:
- Setting CC and CXX
- Adding some check in CMake code before calling conan, basically checking the env vars
- Changing the default value in conan.conf or using ``-s compiler`` command line arguments

Any idea about something that conan could do to improve this? Do you still think that conan should empty the CC and CXX env vars strings before the detection routine?

**Comment by traceon** [comment]
The environment before entering `execute_process()` doesn't contain `CC` or `CXX` - they are set "inside" that command by `cmake`, and only upon its first run, when there is no `CMakeCache.txt` yet. On reconfigure, those vars are not set (but `conan.conf` is already generated without detected compiler info). Strange behavior, but the CMake is strange and inelegant by itself, so no big surprise here.
Nevertheless, `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc` and `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++` are legit paths to compilers, so it looks reasonable for `conan` to recognize them and set compiler et al. settings in the `conan.conf` accordingly.

**Comment by traceon** [comment]
Probably `conan` should do deeper analysis of the compiler executables, which may be shell wrapper scripts, hard or symbolic links (which they very often are), or even renamed executables. Currently, if I understand correctly, `conan` looks at file names of the executables only.

**Comment by memsharded** [comment]
Ok, I think I see now. Maybe we should add this to the issue https://github.com/conan-io/conan/issues/665 (scheduled for next 0.18 release), which is launching conan from CMake, as this is totally related. 

Yes, regarding the deep analysis, this is a trade-off. We don't think that this auto-detection of compilers should be perfect, it is a small convenience, and any failure in it can be fixed in 10 seconds editing ``conan.conf``, so it certainly do not deserve wasting many hours in this. However, as I said, we can have a quick look in the #665 issue, and if it is easy to fix, lets do it.

Thanks again for your feedback!
