### ISSUE TITLE
Conan should throw an exception instead of a warning when it can't copy a source file because the path is too long on Windows

### ISSUE THREAD

**Issue by failshell** [conan-io/conan#4484]
I just spent a lot of time debugging an issue happening only on Windows. Basically, the build would fail to link when building with conan. But it worked when I built it manually. I eventually figured out that conan was skipping files while copying the sources to the build directory warning me like this:

WARN: Filename too long, file excluded:

I believe this should throw an error instead of a warning. I can't see a case where omitting source files would lead to good results. Enabling short_paths fixed the issue in the end. But I think conan should have stopped executing instead of moving on knowing full well it skipped some source files.

**Comment by memsharded** [comment]
Interesting thing: this issue was implemented this way, long, long time ago, and the offending package was failing to unzip some .html of the documentation. It was totally ok to ignore them.

I think it might be changed, but for that it should be considered a bug, because otherwise it might be breaking, and we cannot break existing users (unless until 2.0). Lets discuss it, thanks very much for raising this issue.

**Comment by memsharded** [comment]
Yes, this is totally a bug, it doesn't make sense that a unzip operation will be discarding files.
