### ISSUE TITLE
[lock] Locking alias dependencies

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#4499]
Here is the scenario: App  --> Lib
Whereas there is an alias package with `latest` as version used refering to the most recent version of the Lib package so 
conanfile.py of App:
`requires = Lib/latest@ci/somebranch`
So whenever App is built, the most recent versions of Lib is used. 
The problem with this setup is that in case a new version of Lib is created and the alias is updated, the previously built version of App can not be installed anymore since the reference to the alias Lib package is again resolved when trying to install App and there is no matching binary package of App built with the new Lib version the alias refers to. The longer the dependency chain gets, the more often this happens.
This could be solved by "locking" the dependency to the Lib version that has been used for building the App binary package. The problem obviously is that build a binary package would need to modify the recipe in some way ...
Would such a mechanism make sense though or is there maybe a better approach for CI like this?

**Comment by memsharded** [comment]
Hi @petermbauer 

Yes, providing "locks" of a certain install is something that we are currently working on. It is a very complex feature, so it will take time, but it is a high priority. It will be used not only for alias, but also for all dependencies, like version-ranges too (https://github.com/conan-io/conan/issues/1042).

**Comment by petermbauer** [comment]
Funny thing, i totally forgot about #1042 and my comment there and that already two years have passed since. And that we now already implemented the same workaround with saving/loading the resolved dependencies to/from some file as mentioned in the comments there :laughing:

thx,
Peter

**Comment by monsdar** [comment]
What is the current status of this issue @memsharded ? Do you still consider a way to lock references for a package before it gets uploaded? - so that when i rebuild the package it will not resolve the aliases but instead use the concrete refs it was built with originally?

**Comment by petermbauer** [comment]
In the meantime we developed a solution for this which can be used via `python_require`: A lockfile is created and added next to the recipe in the `package()` method. It contains the resolved (aliases, version ranges) references of selected (added with a custom `requires()` method) packages. Then in `requirements()`, the references from the lockfile are read in and used instead.
Its not 100% clean but works for us. If anyone is interested in this i think i could share the code.

**Comment by memsharded** [comment]
Hi @petermbauer @monsdar 

I am not sure if you have already checked the recently released lockfiles. They were designed with this goal in purpose, and yes, they can lock regular requires, python-requires, build-requires and alias.  It also captures the full effective profile used and the options of each node, together with the graph structure, in case there were conflicting versions (build-requires or private could have different versions of the same package in the same graph)

If not, please have a look at https://docs.conan.io/en/latest/versioning/lockfiles.html, and tell me. Thanks!

**Comment by monsdar** [comment]
I think the difference here is that the lock file would be part of the uploaded package. 

It is not possible to rebuild the exact same package without having an external logfile available, is it?

**Comment by memsharded** [comment]
Yes, so far we have realized that it is better to keep the lockfiles external. There are a few reasons:
- It is way easier to manage them, evolve them (even migrations can be applied), without breaking packages. Can't do that inside a package and that might make evolving the feature, that is early stage, way more complicated.
- It is not possible to store the lockfiles together with the recipe (in Conan cache or servers), in the general case there is more than 1 lockfile, there will be 1 lockfile per different configuration, as the dependency graph can be different for every configuration. Specifically the dependency graph will always be different in our lockfiles, because Conan locks down to the package revision, including the recipe revision, the binary package ID and the package revision. Storing the lockfiles inside the package binary has challenges, like it is not possible to recover it from a input configuration (profile), because you need the package ID, and the package ID can be different if the dependencies are not locked previously, so it becomes a chicken-and-egg problem.
- We have also learned from many users that the most requested pattern is to lock full products, and not individual packages. One lockfile applies to the whole dependency graph, exactly the same lockfile can be used to manage and re-build any package in the graph. Locking individual packages would be more complicated, because even more initial state should be stored and recovered. We tried that and proved to be more challenging.
- The most demanded usage of lockfiles so far is to achieve CI at scale, as explained in the docs. This is also doable only if the lockfiles are external.
- There is a very useful approach that avoids recovering initial lockfiles both for CI and developers. Keeping separate repositories for the "develop" state and "builds". So the way to get the same packages, without explicitly recovering a lockfile is to resolve against given repositories.
- The new "package_id_modes", especially the "package_revision_mode", which is "mathematically exact", guarantees that one binary will only be used if it was compiled against exactly the same upstream binaries. Not exactly reproducibility, but we believe it can be a very useful feature.

I am not saying that we will not store lockfiles inside packages at some point, just that so far it seems more convenient and maintainable, specially for evolving the feature and learning about it is adopted by users.

**Comment by petermbauer** [comment]
> I think the difference here is that the lock file would be part of the uploaded package.
> 
> It is not possible to rebuild the exact same package without having an external logfile available, is it?

This is the reason why we did not switch to the new feature yet. I totally understand why it is implemented like this but currently its more convenient not having to provide a separate lockfile for the consumer.
