### ISSUE TITLE
Modular packages/libraries: Optimizing number of package builds (boost, Qt, LLVM,...)

### ISSUE THREAD

**Issue by RobertHabrich** [conan-io/conan#4501]
When developing multiple projects all requiring similar packages, I find the number of package builds too high. There seems to be potential to optimize. However, I'm not sure about the solution and wanted to discuss this here.

# Example

I'll use the `Qt/5.11.2@bincrafters/stable` package for this example. The package provides a lot of options allowing to enable/disable different Qt modules. The example could also use other libraries like `boost/1.68.0@conan/stable`.

* AppA requires `Qt/5.11.2@bincrafters/stable` with two modules enabled (e.g. `self.options["Qt"].qttools = True` and `self.options["Qt"].qtsvg = True`)
* running `conan install` will produce a full Qt build with the selected modules
* AppB requires `Qt/5.11.2@bincrafters/stable` with one module enabled (e.g. `self.options["Qt"].qttools = True`)
* running `conan install` will produce a full Qt build with the selected module, **though the Qt build above could easily be reused**
* AppC requires `Qt/5.11.2@bincrafters/stable` without any additional module
* running `conan install` will produce a full Qt build without any module, **though the Qt builds above could easily be reused**

# Possible solution

In addition to providing the hard set of options required, also allow to say that your app "doesn't care" about other options. The conanfile for AppB above for example could include `self.options["Qt"].qtsvg = Any` (or maybe the `default_options` of the Qt package should set this to Any already). This would allow the second `conan install` command above to reuse the existing package of AppA.

**Comment by Johnnyxy** [comment]
The reason behind "_looks like multiple simlar packages_" this is that conan identifies a package by inspecting a generated hash value ([package_id](https://docs.conan.io/en/latest/reference/conanfile/methods.html?package-id#package-id)). This package_id is generated from the dependency graph describing every dependency and its settings and options.
If you change one setting/option in any dependency then the dependency graph changes and in turn the computed package_id.

A recipe can define which of its settings and options are used in the hash computation (see [here](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=package_id)).
So if a package defines something that is redundant of builds redundant files then conan cannot do anything about it as conan has no information about what generated files are needed or not. Only the recipe developer can know [that](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=cpp_info#cpp-info) and he has to ensure that the generated hash value uniquely identifies a specific package (combination of depdencies/settings/options) of his recipe.



"doesn't care"
--------------
If a recipe should not care about a option because it has no meaning for a specific package then one should remove the option from the package_id generation.
```python
def package_id(self):
    del self.info.options.THE_OPTION_TO_IGNORE
```

**Comment by jgsogo** [comment]
I found the same pain as you did a couple of weeks ago with Qt package too. There are several approaches for libraries that are divided into _modules_: one approach is the one you found here in `Qt`, another one is the `boost` modularized from @bincrafters ([here](https://github.com/bincrafters?utf8=%E2%9C%93&q=%22conan-boost_%22&type=&language=)) and I found the one by @Manu343726 for `LLVM/Clang` also worth considering ([here](https://gitlab.com/Manu343726/clang-conan-packages)).

This is an issue related to the recipe sources not to Conan itself, we cannot know what is the intention of an option if the recipe owner doesn't declare it; nevertheless IMHO we should think about pros/cons of each approach and write about them (here or in a blog post), that's the reason I'm marking this issue as `whiteboard`, to discuss it with the team.

Thanks for reporting it, thanks for sharing your concerns, it allows us to prioritize the queue of issues.

**Comment by Blubbz0r** [comment]
Just wanted to share another possible solution:

In addition to "options", "modules" could be provided as well by conan. "modules" would allow to list all modules of the package and allow clients to turn them on or off. It would also affect the package ID identical to "options". However, "modules" would act differently when performing the lookup for e.g. `conan install`. It would basically be treated as a bitmask checking for each available package if the subset of modules requested are on.

Both solutions obviously add further complexity to conan itself. So I'm not sure if they are "worth" it.

Meanwhile I guess the guideline would be that packages should default to turning all modules on? That's basically how the boost package is defined and is why the same problems are not as prevelent there.

**Comment by ovidiub13** [comment]
Possible relation to #3106.

**Comment by jgsogo** [comment]
We are introducing a new feature in Conan called _Components_. It will allow modeling a package with several libraries inside and the dependencies between those libraries. There is a draft of a pull request here: https://github.com/conan-io/conan/pull/5242, I think it fits what we are talking here for those use-cases where we want all the libraries to be in the same package.

Ping @danimtb, not sure if that PR shall close this one too, but I think that _Components_ is the best built-in functionality we can provide to solve this problem, any other approach will be built on top of existing Conan functionalities (and the very valuable comments from all of you).

**Comment by memsharded** [comment]
Conan 2 did a great effort to optimize the packages that need to be built. With the ``package_type``, the ``traits``, it can now avoid unnecessary builds from source while being very safe, and allow efficient use of versioning to define behavior. Closing as solved, please create new tickets for any further question or issue, thanks for the feedback.
