### ISSUE TITLE
How does --detect work?

### ISSUE THREAD

**Issue by skgbanga** [conan-io/conan#4520]
Hello,

I am curious as to how `--detect` flag in conan work. Any help on that would be appreciated!

The reason I am asking this is because when I run `conan profile new default --detect`, it correctly determines that I have a compiler with version 7 installed. 

However, when I do `conan install ..`, it (or rather cmake) picks `/usr/bin/c++` and I have to manually set my compiler via `CXX` on the command line.

**Comment by memsharded** [comment]
Hi @skgbanga 

You can read the whole source code of the detect functionality here: https://github.com/conan-io/conan/blob/develop/conans/client/conf/detect.py

It will try to use CXX env-var if defined, and otherwise will execute ``gcc --version`` to get that version.

``conan install`` doesn't deduce any compiler (actually Conan does not deduce configuration, besides that detect functionality), but rather takes it from the used profile (or the default one, if not specified). A different thing is what CMake or other build systems could do. In this case, it would be good to know if your CMake scripts have something related to the compiler configuration, and why it would be using a different compiler. How did you install that compiler? What is the cmake output? What is the most basic CMakeLists.txt that uses that compiler?

**Comment by skgbanga** [comment]
@memsharded That answers my question. To your questions:

1. I installed the compiler by building it from source and have a separate installation directory. 
2. I do not have any compiler setting in my cmake. When I am building make/ninja files, I specify everything (CXX, Build type) from command line. 

Thanks for the response. I am closing the ticket.

**Comment by memsharded** [comment]
Ah, that makes sense. 

For other readers reference: it is a possible case that the first time you run conan, it generates the default profile, it defines the system installed gcc version, but that profile never changes (unless you remove the file). Then, when you define later CXX, CMake is using it, but the applied profile is defining the system one.

Read the install output (the actual applied settings are there), and if using CMake, there are protections that should error if the CMake detected compiler is different to the profile one, and this is likely the cause.

Thanks @skgbanga for following up and closing!
