### ISSUE TITLE
cmake cross compilation does not set CMAKE_SYSTEM_NAME

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan#4550]
[Documentation ](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html?highlight=cmake_system_name#definitions)states that `CMAKE_SYSTEM_NAME` is `Set to self.settings.os value if cross-building is detected`, which is a good thing, because it will make [cmake set the `CMAKE_CROSSCOMPILING` variable automatically](https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING.html)
However, when trying to cross compile [mysql-connector-c](https://github.com/bincrafters/conan-mysql-connector-c) (linux x86_64 to linux armv7hf) [the build fails](https://github.com/bincrafters/community/issues/644), because `CMAKE_SYSTEM_NAME` is not set by conan. It looks like conan sets the CMAKE_SYSTEM_NAME variable only if the the host os is not the build os, which is wrong: we can cross compile to the same os with a different architecture.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Ignition** [comment]
Any chance a fix can be delivered? I hit this issue today and spent a long time trying to understand what wasn't working.

**Comment by a4z** [comment]
might be related, (I think it is)
when building for iOS, MAKE_SYSTEM_NAME is always set to Darwin, and this is not OK
this has been introduced with version 0.28.0 (26-October-2017) 
It should be, of course, set to `setting.os` since naturally I will have a profile for  iOS, tvOS, or watchOS.
please check also 
https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos
 why a hardcoded `-DCMAKE_SYSTEM_NAME=Darwin` that is passed to cmake is not sutiable.

**Comment by ericLemanissier** [comment]
fixed with https://github.com/conan-io/conan/pull/7827

**Comment by a4z** [comment]
but does this not still set the CMAKE_SYSTEM_NAME to Darwin in case of iOS ?
> Set to 1 when the target system (CMAKE_SYSTEM_NAME) is iOS
(https://cmake.org/cmake/help/latest/variable/IOS.html) 

so I guess there is still an issue ?

**Comment by ericLemanissier** [comment]
Yes, you should probably report this issue
