### ISSUE TITLE
Should the tests be distributed with the pip package?

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4563]
Question raised thinking about possible issues enabling warnings in tests #4548

**Comment by SSE4** [comment]
might have sense, if user/developer is running conan on some new platform (AIX, PowerPC, etc.) and want to ensure what it works properly. also, it would make it easier to report and debug such compatibility issues.

**Comment by memsharded** [comment]
@SSE4 is running tests from pip installed packages a thing? I thought for that the standard process was cloning the sources.

**Comment by uilianries** [comment]
The only possible case that I see is re-using some function/method from Conan tests for tests in a new plugin.

**Comment by SSE4** [comment]
@memsharded I've checked, and it seems like it's not a standard practice in python world to install tests with pip, so probably development workflow should be preferred (like clone, get requirements.txt, run tests)

**Comment by lasote** [comment]
So it looks you all already did the investigation. I remove the `look into`. (Friendly reminder, the task was only to investigate it, so you did a task without being assigned to a release)
Makes sense to remove them from the pip package I would say.

**Comment by nh2** [comment]
Hi @lasote,

many downstream distributions fetch packages from Pypi, and run the tests as part of the automatic build QA to ensure that everything is working (that is, tests should pass given the system and Python dependencies that the distribution has provided).

This gives packagers and users a high degree of confidence that everything is working. It has improved FOSS software over the last 20 years because lots of distros have found many issues this way, fixed them and contributed them back upstream.

By removing the tests from the package, you have removed this ability.

I recommend to re-introduce the tests into the source dist.

**Comment by memsharded** [comment]
Hi @nh2 

Conan test suite is extensive and slow, will require to have different tools installed in the machine: cmake at certain versions, compiler at certain versions, other build tools, etc.

I am not aware of any user that did that in the past or would like to do this. This has been closed for 1 year without any further request to reinstate those tests. Will you be running such tests when installing Conan from Pypi? 

Furthermore, I am not sure about that generalized practice. From Conan self dependencies I see:

Not including tests:
- Astroid
- certifi
- chardet
- codecov
- colorama
- coverage
- dateutil
- idna
- isort
- jinja2
- jwt
- lazy_object_proxy
- libfuturize
- libpasteurize
- markupsafe
- mesonbuild
- nose
- packaging
- pygments
- requests
- semver
- tqdm
- urllib3
- webob
- webtest
- yaml

Including tests:
- bs4
- fasteners
- future
- mock
- past
- typed_ast
- waitress


So unless there is a strong evidence that this is requested by some Conan users, it is better to keep the package lightweight, as it seems the majority of other pip packages are doing. Thanks for your feedback.

**Comment by nh2** [comment]
> I am not aware of any user that did that in the past or would like to do this. This has been closed for 1 year without any further request to reinstate those tests. Will you be running such tests when installing Conan from Pypi?

@memsharded `nixpkgs`/`NixOS` has been running the tests [until now](https://github.com/NixOS/nixpkgs/pull/83144/commits/f460e62d9b367a0bfd71148ef34f44421d0e82cb#diff-07a4c756069e63fb0c25a5573186e4d0R89). Them breaking is how I noticed this.

(Like most distros, it packages tens of thousands of packages across various programming languages, and its build system runs the tests as shipped by their source dists by default, unless explicitly disabled.)

> Furthermore, I am not sure about that generalized practice.

In the Python world, `numpy`, `scipy`, `Babel`, and lots of other significant projects all include their test suites in their pipy source dists. (It would be quite crazy if they did not.)

> Conan test suite is extensive and slow, will require to have different tools installed in the machine: cmake at certain versions, compiler at certain versions, other build tools, etc.

For clarification, as a distro packager one does not care what the default operation of `pip install` is; it's totally fine that a user who runs `pip install` does not have to run the tests or install the test dependencies.

The only thing that matters is that pipy releases contain the tests so that you can run e.g. `pytest` on them to check that all is well.
