### ISSUE TITLE
conan info broken on SLES 15

### ISSUE THREAD

**Issue by djeverett** [conan-io/conan#4566]
With this conanfile.py: 
```from conans import ConanFile

class FooConan(ConanFile):
    name = "Foo"
    version = "2.0"
```
running `conan info --only None .` usually gives `Foo/2.0@PROJECT`, but on SLES 15 the result is `conanfile.py (Foo/2.0@None/None)`.

**Comment by djeverett** [comment]
The was seen with conan 1.10.0

**Comment by memsharded** [comment]
Hi @djeverett 

Could you please check it twice. The new display name ``conanfile.py (Foo/2.0@None/None)`` has been added in latest releases, I think that it is possible that you are using an updated Conan in your SLES 15, and an older one in the other machine. Could you please have another look? Thanks.

**Comment by djeverett** [comment]
I've just checked - both machines have Conan 1.10.0 on.

**Comment by memsharded** [comment]
Yes, according to the changelog: https://docs.conan.io/en/latest/changelog.html, (feature https://github.com/conan-io/conan/pull/4197) this improved output has been released in conan 1.12. From now, the "consumer" conanfile will try to have something more meaningful and closer to a normal package reference (pkg/version@user/channel), instead of "PROJECT" (previous versions).

In which way are you parsing the conan output? Wouldn't you prefer to use some of the json output that the conan commands can generate for machine-reading?

**Comment by djeverett** [comment]
I am parsing the output in a Jenkins pipeline in order to obtain the name and version of the package being built (Foo and 2.0 in the above example).  The other output of `conan info` is ignored.  I think JSON output would suit better.

I'd like to try upgrading to the latest Conan and seeing if the `conan info` output is consistent across platforms before closing this ticket.

**Comment by memsharded** [comment]
I think you might be interested in the new ``conan inspect`` command, that will allow for easy and fast extraction of the name and version. It also has json output, please have a look too: https://docs.conan.io/en/latest/reference/commands/misc/inspect.html

there is also a request to simplify even further the ``conan inspect`` for this specific use case: https://github.com/conan-io/conan/issues/4498

**Comment by djeverett** [comment]
That's great - I think I'll start using that instead of conan info.  Thanks!

**Comment by memsharded** [comment]
Cool! Then, I am going to close this issue by now, don't hesitate to re-open or open new issues if you have further questions. Thanks!
