### ISSUE TITLE
[question] [scm] [svn] Can we rely on Conan supporting an old version of svn?

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#4578]
When svn was added as an option for the scm attribute feature, we were really pleased, but then quickly hit a few issues with the implementation and our old version of svn (1.7.14 as supplied with RHEL 7). Helpfully, these issues were fixed :smiley:, but, we have still not migrated to using scm with svn as we can't be sure the feature will continue to work going forward due to your issues supporting all the different versions of svn (see #3737 and #3909).

Is there any statement you can make regarding support for scm and my (old) version of svn? e.g.

- In Conan 1.x we guarantee support for 1.7.14 and newer
- In Conan 2.x we will not guarantee this

I appreciate it may be a bit of a nightmare supporting such an old version, but it is what ships with RHEL 7, and we have no choice but to stick with it!

**Comment by danimtb** [comment]
Hi @keithrob91,

We appreciate the observations and we are always trying to integrate with other tools specially to make developers life easier. Unfortunately we cannot commit to stability with SVN nor even with the SCM feature. It is something still experimental and we are constantly reevaluating it.

There is an ongoing and frequent discussion in the development team on how to deal with this kind of aggregated information and track it down to (maybe) the metadata of the packages. Also we got a different approach on the new revisions feature for Conan but still with the support of SVN and Git commit tracking in mind, although this is still something under development.

I think the SVN wrapper now supports even 1.6.X version, but not completely sure. Also new versions of SVN should be supported too and we tried to keep compatibility.

Maybe @jgsogo can give us more insight bout its status.

**Comment by jgsogo** [comment]
Hi!

IMO, there is no reason to deprecate support for some versions of SVN when we evolve Conan to 2.x or further. Once the functionality is there and it is contained inside a wrapper class in our Python codebase (like it is now), there is no reason to change it.

The problem here, as you know well from previous issues, is that we are not testing Conan with every version of every tool we provide wrappers to, so we need our users to do that testing when a new feature is introduced and they are facing those issues first (thank you all! 💯 ). Anyway, once we are able to reproduce the error we try to do our best to fix it, there is no reason to change that in the future.

**Comment by danimtb** [comment]
hi @keithrob91,

Do you need more information on this topic? Please ask any doubt you may have and we will try to solve it. Otherwise please close the issue. Thanks! 😄

**Comment by keithrob91** [comment]
I'm happy with the response. We are going to start using the feature, even with our prehistoric svn :smile:

**Comment by danimtb** [comment]
Glad to hear that! Thanks a lot for the response :)
