### ISSUE TITLE
Uncommon combinations of compilers and standard libraries

### ISSUE THREAD

**Issue by jeffw387** [conan-io/conan#4579]
It seems that it should be possible to specify settings for using clang with libstdc++(11) as well as gcc with libc++, and clang-cl with ms-stl. At present the default settings.yml doesn't seem to permit this. 

I'm trying to conditionally link to the c++ filesystem library (among others) but since some of the combinations I considered supporting aren't available in conan, I'm not sure how to handle them. 

My use case looks something like:
```
# helper package for filesystem library
...
def package_info(self):
    if (self.settings.compiler.libcxx == "libc++"):
        self.cpp_info.libs.append("c++fs")
    elif (self.settings.compiler.libcxx == "libstdc++") or (self.settings.compiler.libcxx == "libstdc++11"):
        self.cpp_info.libs.append("stdc++fs")
```

For now I suppose I'll just assume that each compiler uses its own standard library, as conan seems to.

**Comment by jgsogo** [comment]
Hi, @jeffw387, you can always edit your `.conan/settings.yml` to match your own needs and share it with your colleagues, Conan will create different packages for each set of settings. Also, take into account that some of the build helpers we are providing might not set the proper flags for those configurations.

**Comment by jgsogo** [comment]
Hi, @jeffw387, did you try the approach modifying the `settings.yml` file? Does it fit your needs? Thanks!

**Comment by jeffw387** [comment]
I felt that distributing a settings.yml to everyone who might download my
package is not an ideal solution so my current plan is to get by with
standard settings.

**Comment by jgsogo** [comment]
Oh! If it is about an open source library you are willing to upload to conan-center and distribute for everyone else to use, then I will really appreciate the opinion of @SSE4 and @uilianries, they can evaluate much better than me the combinations of settings that make sense for general purposes.

This should be taken into account carefully, as adding more combinations could impact all the packages already existing, because (ideally) they should be generated too. Nevertheless, let's hear what they have to say.

Thanks!

**Comment by uilianries** [comment]
To general propose I would say all combinations provided by conan-package-tools are enough. The cases where someone asks for exotic settings are rare.

Add black magic in package_info is not a good approach I think, since you could distribute your settings file and install by conan config. Even Bincrafters has a repo with settings and profiles [here](https://github.com/bincrafters/conan-config). The fact is that you are trying to add new libraries that supposed to change the package id, but they won't do that.

**Comment by jgsogo** [comment]
Let me know if you need something else related to this issue, thanks @jeffw387
