### ISSUE TITLE
Settings for conan consumers vs producers 

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#4590]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I have a very simple package that creates an executable.
Since for consuming the executable, only OS is relevant, the conanfile.py contains 
```
from conans import ConanFile, tools, CMake
import os

class SampleConan(ConanFile):
    name = "conan_sample"
    version = "0.0.1"
    #settings = "arch", "build_type", "compiler", "os"
    settings = "os"
    exports_sources = "CMakeLists.txt", "main.cpp"
    
    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        cmake.install()
```

If I now want to build this package with a given profile using CMake, I get a warning when creating the package 
```
conan_sample/0.0.1@myuser/whatever: WARN: CMake generator could not be deduced from settings
```

Since as settings only contains "os", compiler info and version are not propagated when constructing the `CMake` object in the `build` step, and thus it cannot deduct a generator.

https://github.com/conan-io/conan/blob/ab0870336550b7521da71595c6babf42d5690f7b/conans/client/build/cmake_flags.py#L28-L34

All `compiler`, `arch` and `compiler_version` all all `None`, if they are not specified in the package recipe and thus a default CMake generator cannot be deducted.

So my question is: 
How can I specify that CMake should use the generator which is specified with my profile instead of invoking CMake with no generator information?
Can I access my profile settings somehow from within the `build` method to pass it to the `CMake` object creation?

The package provider has more settings than the package consumer, because you're actually building something. Thus a binary compiled with VS2015 is different from one compiled with VS2017 64 bit, but the consumer package could use either one.

I hope the question is clear, I can provide a full working repo (including CMakeLists.txt file and main.cpp) if necessary.

**Comment by Johnnyxy** [comment]
Hi,

your question
--------------
To define the CMake generator for the CMake build helper you can use the [CMake-build-helper constructor](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#constructor).

```python
def build(self):
    cmake = CMake(self, generator="Unix Makefiles")
```

To modify this from a profile or command line you could use the [conan options](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#options). These options you can set on [commandline](https://docs.conan.io/en/latest/reference/commands/consumer/install.html#conan-install) or in your [profile](https://docs.conan.io/en/latest/reference/profiles.html#profiles).

```python
class recipe(ConanFile):
    ...
    options = {"my_generator": "ANY"} # or {"my_generator": ["Unix Makefiles", "Visual Studio ..."]}
    ...
    def build(self):
        cmake = CMake(self, generator=self.options.my_generator)
```

Be sure you want to do it this way. Because this way the option it is unverifiable by conan ("ANY") or a redundant collection of strings you have to sync with CMake's generators.

another way
-------------
You can build a binary with VS2015 (toolset v140) or VS2017 (toolset v141) and consume it with VS2017. But not build with VS2017 and consume with VS2015. As I am aware conan knows that the toolset can be compatible. Have a look at the docs [here](https://docs.conan.io/en/latest/reference/conanfile/methods.html#self-info-vs-toolset-compatible-self-info-vs-toolset-incompatible).
The recipe has to define the ```package_id``` function and specify that the toolset should be compatible (there is an example in the docs I have linked to).

**Comment by memsharded** [comment]
Hi @KerstinKeller 

The approach that you might be looking for is a custom ``package_id()``. Let me summarize it:

- You indeed need the full settings: ``os, compiler, arch, build_type``, because they are really the configuration you are going to use to feed the ``CMake`` build helper so it selects a generator (with a compiler) for you, defines the build_type to CMake, etc.
- The default ``package_id()`` will create a unique binary per configuration, but that you want to avoid, and you want to say that the same package can be used for other different configurations.
- So you can customize your ``package_id()``, for example you could try:

```python
def package_id(self):
     self.info.settings.compiler = "Any"
     self.info.settings.compiler.version = "Any"
     ... #More self.info.settings.xxxx subsettings
     self.info.settings.build_type = "Any"
```

Note that the package ID is computed based on the ``self.info.settings``, not the input ``self.settings``. Doing that way, you get always the same ID, and thus the same binary for different values of compilers and build_type, cause they will always be overwriten to "Any".

You might also just delete them:
```python
def package_id(self):
     del self.info.settings.compiler
     #No need to delete subsettings, they are automatically deleted too
     del self.info.settings.build_type
```

Extra tip: if you plan to use such executable in cross-building, you might want to define ``os_build`` and ``arch_build`` settings.

Please have a look to this method and try, and tell us.

**Comment by KerstinKeller** [comment]
Thank you @memsharded for the detailed explanation, indeed the `package_id` method seems to be exactly what I need in my case.

Is there a difference between deleting a setting, and setting it to "Any"?

**Comment by memsharded** [comment]
You are welcome :)

Yes, there are some of subtle differences:

- Removing a setting also removes all its children. So if you remove ``settings.compiler``, then ``settings.compiler.version``, ``settings.compiler.libcxx``, etc, are removed
- If removed, the setting won't appear in the meta-info of the package, when you search and display, or in the Artifactory web UI
- There is a conceptual difference, setting a setting to some string, means that the package has that setting, and the binary is generated with a given setting, but the final binary is compatible with other range of values. E.g.: you can compile a C library with some gcc and assume that is binary compatible with upper versions of the compiler and avoid generating more binaries. You can set a ``self.info.settings.compiler.version="4.9-6.3"``, even conditionally. A different case is a header-only library, that you can have ``settings.built_type`` because you want to build and run tests, and you need those tests to be built with an input setting. But when you are done, then you completely delete the ``settings.build_type``, because the final binary is independent of the build_type, not that it has a build_type but is compatible with other build_types.

**Comment by memsharded** [comment]
Closing as staled
