### ISSUE TITLE
[question] Wildcards and Options

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#4598]
Is there some way of achieving the following?

stable remote (all packages in here created with -o some_option=True):
PkgA/1.3.0@release/stable
PkgB/2.1.3@release/stable

local cache (all packages in here created with -o some_option=False):
PkgC/1.1.0@dev/dev

In PkgD directory (D requires A, B, and C):
`conan create . -o *release/stable:some_option=True -o *dev/dev:some_option=False some_option=False`

i.e. D and C (and everything else in dev/dev) use some_option=False, but A and B (and everything else in release/stable) use some_option=True

If there is, I'm failing miserably to find it! Thanks in advance

**Comment by uilianries** [comment]
Hi @keithrob91 !

It's not possible because an option is related to the package only (name + version). `release/stable` is the namespace of the package. Since there is no collision in your package names, you could use the regular option:

`conan create . -o PkgA:some_option=True -o PkgB:some_option=False -o PkgC:some_option=False`

Regards!

**Comment by keithrob91** [comment]
Thank you for the reply. Your solution is fine when the amount of packages is small (like in my example) but no good when the amount is large, like in our real case, as the number to specify on the command like is not practical.

However, when we understood our problem a bit better we realised the main issue was because different packages are created depending on what this option is set to, and if the dependent packages don't exist Conan will complain and ask you to build the missing ones. Hence, why we had to specify specific options for specific packages. Whilst we could have built versions of the packages with the option set and unset, we didn't really feel (in this case) that was appropriate, or scalable.

Therefore, we have opted for another approach, which is to remove this option in `package_id()` so that Conan does not create a new hash dependent on the option, and therefore, requests for dependent packages are satisfied regardless of this option.

**Comment by uilianries** [comment]
You can try [hooks](https://docs.conan.io/en/latest/extending/hooks.html). You will be able to change your options based on the reference. You can check the reference [here](https://docs.conan.io/en/latest/reference/hooks.html#hook-interface).

But again, the namespace should not be the main distinction for a package, it represents the author and the "branch". Since all dependencies are declared in the recipe, we can use wildcards like `conan install foo/0.1@bar/stable -o *:opt=True`. If you have some collision using namespaces, you could use multiple remotes on Bintray or Artifactory, to distribute the same package reference.

Also, both conanfile.txt and conanfile.py support dependencies options declaration, so you can specify in your recipe which options your dependencies should use, based in your context.

**Comment by AbrilRBS** [comment]
Closing as solved in Conan v2, which has an uniform interface for reference selection, both in the CLI and profiles, so that `conan install . -o"*@stable/stable:my_option=1" -o"*@dev/dev:my_option=2` works as expected.
