### ISSUE TITLE
conan create not rebuilding tree with scm "auto" and --build=outdated

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#4600]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan Version 1.12.2
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

When using `conan create` locally or remotely on a build server with `scm` `"revision": "auto"`, it seems that upstream packages do not see the changed recipe and rebuild the dependencies as expected (unless the version is changed). I'll focus on the remote workflow for now. The first time it's built, everything is fine, this is on subsequent rebuilds. My packages are currently using full_package_mode()
```
    def package_id(self):
        self.info.requires.full_package_mode()
```

So imagine
Lib A 1.0.0
Lib B 1.0.0 -> Lib A 1.0.0
Lib C 1.0.0 -> Lib B 1.0.0

As mentioned, these have already been built and everything (package and recipe already uploaded).

Then, I change Lib A, `git commit` without changing version, and rebuild it with `conan create` and upload it. It seems to be detecting the change, and rebuilds the package. New recipe is uploaded with new git commit hash id. `conan upload <package_name> --all -r <remote> -c`

I then go right to Lib C, and call `conan create . <package name> -u --build=outdated`

Since it has already been built against Lib A 1.0.0, it does not appear to automatically rebuild Lib B against the new Lib A. From what I understand, it should detect the rebuild due to the uploaded recipe being changed (by the git hash in the uploaded conanfile.py recipe)

If I change Lib A to 1.0.1, everything is detected, and Lib B and C are rebuilt.

This is the same when creating packages locally as well.

**Comment by memsharded** [comment]
Hi @Mark-Hatch-Bose 

It seems there is a small missunderstanding regarding the ``--build=outdated`` argument. It only affects the package that has had its recipe modified. So:

- You modify a recipe, it changes its manifest (md5 of the contents)
- The binaries that were created with a previous version of the recipe, know it, because they store such md5 of the recipe.
- ``--build=outdated`` tells the package with the recipe changed to recompile its binary
- But, the binaryID of the package doesn't change, because it is the hash of the settings, options, etc. That is, you could have done a change in the recipe that doesn't affect the binary. So a change in the recipe doesn't imply a change in the binaryID.
- So the consumers, they don't see they should be re-built, because one of their upstream dependencies has been rebuilt.

If you explicitly change the version of the package, then yes, the consumers know (if they are in ``full_package_mode()`` that they should be rebuilt, not because of the "outdated", but because they will be computing a different binaryID.

So it is not possible right now to achieve what you want. The good news, is that we are already working in some features that will allow this, in summary:
- Package revisions, they will generate a new binary Revision, everytime a binary is rebuilt. This is already merged and released, but deactivated by default. Still being stabilized, hopefully will be released mainstream soon.
- An "exact" binaryID that takes into account the upstream dependencies Revisions. That will force the rebuild of the downstream dependencies everytime you do a change upstream, which is the behavior you want. This is still early stage, but we are already working on it.

Keep tuned for next releases. Thanks for submitting this issue!

**Comment by Mark-Hatch-Bose** [comment]
This is very helpful, thanks for the explanation.
We are getting around this locally by using `tools.git()` and `is_pristine()` and updating the patch version to "time since epoch" to force rebuilds when it is "not pristine".
So I change Lib A locally and `conan create` Lib A -> Lib A v1.0.1152321333.
I do it again, a bit later. Lib A -> Lib A v1.0.1152321400

We are using version range `[>=]` to grab the latest package in most of our `requires`

Developers can then test cross repo changes easily locally, and know the tree is forced to rebuild to have matching libraries. These local packages are not intended to be uploaded.

But for our remote build server that uploads the packages, where we want to be frequently updating our large tree at various levels. I'm using the `conan info` `-bo` to get the build order of a tree, and then am walking up the tree rebuilding the individual repos. I think your explanation means we will just need to force a build with `--build outdated --build <thisrepo>` for the individual repos. This means that the cadence that the tree updates will be slower, as we need to rebuild every repo in the entire tree every time (requiring more build power). At least till the features you mentioned are available.

Anyway, this is interesting and complex! Thank you so much for the help!

**Comment by Mark-Hatch-Bose** [comment]
As a sidenote:

I tried using a full git tag in the package version.
I'm using the `git describe` to get the full git tag.

This resulted in the following packages being generated:
```
<package_name>/2.10.0-16-gf858aff@<user>/<channel>
<package_name>/2.10.0-17-g8612661@<user>/<channel>
<package_name>/2.10.0@<user>/<channel
```

When using `include_prerelease=True` in my version ranges, it always seems to resolve to 
`<package_name>/2.10.0@<user>/<channel`

Rather than the later generated `<package_name>/2.10.0-17-g8612661@<user>/<channel>`

I thought this might be a good workaround, but it's not detecting that the the `-17-g8612661` package is later than the `2.10.0` package. This would fix most of my problems, as we would be changing the version with every git commit.

I can open this as a separate issue if this is unintended behavior.

**Comment by Mark-Hatch-Bose** [comment]
Just updating this with some tests I've done on the package revision feature. It doesn't seem to be doing what I expect.

I expect that the "hash" generated by the `package` step() is used to generate each revision. I then want to detect and use the latest package revision when building.

So I have my repo, and I build and export it with some changes.
```
mh70023@mh-AMBI-VM:.../remote-conan/TestRepo$ conan export-pkg . mh/testing -f
Exporting package recipe
TestRepo/2.14.11-0+g4d37b68@mh/testing exports: Copied 1 '.json' file: depends.json
TestRepo/2.14.11-0+g4d37b68@mh/testing: WARN: Repo status is not pristine: there might be modified files
TestRepo/2.14.11-0+g4d37b68@mh/testing: Revision deduced by 'auto': 4d37b68880f3b8bc37a30c82c887fe9d7c2a6486
TestRepo/2.14.11-0+g4d37b68@mh/testing: The stored package has not changed
TestRepo/2.14.11-0+g4d37b68@mh/testing: Using the exported files summary hash as the recipe revision: 2ccb60c4bc38d72404941e8547964369 
Packaging to 5f034ec8c1ebae5265960b7c47426c464660330c
TestRepo/2.14.11-0+g4d37b68@mh/testing: Generating the package
TestRepo/2.14.11-0+g4d37b68@mh/testing: Package folder /home/mh70023/.conan/data/TestRepo/2.14.11-0+g4d37b68/mh/testing/package/5f034ec8c1ebae5265960b7c47426c464660330c
TestRepo/2.14.11-0+g4d37b68@mh/testing: Calling package()
TestRepo/2.14.11-0+g4d37b68@mh/testing package(): Packaged 11 '.proto' files
TestRepo/2.14.11-0+g4d37b68@mh/testing package(): Packaged 21 '.a' files
TestRepo/2.14.11-0+g4d37b68@mh/testing package(): Packaged 165 '.h' files
TestRepo/2.14.11-0+g4d37b68@mh/testing: Package '5f034ec8c1ebae5265960b7c47426c464660330c' created
Package revision 67d7607d2af5b3c2f15ae713a634f52e
```

I see three hashes generated there:

`Using the exported files summary hash as the recipe revision: 2ccb60c4bc38d72404941e8547964369`
`Packaging to 5f034ec8c1ebae5265960b7c47426c464660330c`
`Package revision 67d7607d2af5b3c2f15ae713a634f52e`

So I go ahead and modify some header files and rebuild it again with `conan build` and re-export.

```
mh70023@mh-AMBI-VM:.../remote-conan/TestRepo$ conan export-pkg . mh/testing -f
TestRepo/2.14.11-0+g4d37b68@mh/testing exports: Copied 1 '.json' file: depends.json
TestRepo/2.14.11-0+g4d37b68@mh/testing: WARN: Repo status is not pristine: there might be modified files
TestRepo/2.14.11-0+g4d37b68@mh/testing: Revision deduced by 'auto': 4d37b68880f3b8bc37a30c82c887fe9d7c2a6486
TestRepo/2.14.11-0+g4d37b68@mh/testing: The stored package has not changed
TestRepo/2.14.11-0+g4d37b68@mh/testing: Using the exported files summary hash as the recipe revision: 2ccb60c4bc38d72404941e8547964369 
TestRepo/2.14.11-0+g4d37b68@mh/testing: WARN: Forced build from source
Packaging to 5f034ec8c1ebae5265960b7c47426c464660330c
TestRepo/2.14.11-0+g4d37b68@mh/testing: Generating the package
TestRepo/2.14.11-0+g4d37b68@mh/testing: Package folder /home/mh70023/.conan/data/TestRepo/2.14.11-0+g4d37b68/mh/testing/package/5f034ec8c1ebae5265960b7c47426c464660330c
TestRepo/2.14.11-0+g4d37b68@mh/testing: Calling package()
TestRepo/2.14.11-0+g4d37b68@mh/testing package(): Packaged 165 '.h' files
TestRepo/2.14.11-0+g4d37b68@mh/testing package(): Packaged 11 '.proto' files
TestRepo/2.14.11-0+g4d37b68@mh/testing package(): Packaged 21 '.a' files
TestRepo/2.14.11-0+g4d37b68@mh/testing: Package '5f034ec8c1ebae5265960b7c47426c464660330c' created
Package revision ed1aeb41f316db40c024f5134dc78a1e

```

So I have not changed the recipe, or changed the version in any way. So it is expected that the recipe revision has not changed and as expected the package revision HAS changed cause I modified some files.

`Using the exported files summary hash as the recipe revision: 2ccb60c4bc38d72404941e8547964369 `
`Packaging to 5f034ec8c1ebae5265960b7c47426c464660330c`
`Package revision ed1aeb41f316db40c024f5134dc78a1e`

Here is the output of just running a local search:
```
conan search TestRepo/2.14.11-0+g4d37b68@mh/testing -rev
Revisions for 'TestRepo/2.14.11-0+g4d37b68@mh/testing':
2ccb60c4bc38d72404941e8547964369 (No time)
```

We use `full_package_mode()` to enforce that higher level things are rebuilt with any changes.
When I go to a higher level project and try to rebuild again with `-u` and `-b` outdated, it does not recognize that there has been a new package revision generated.

`TestRepo/2.14.11-0+g4d37b68@mh/testing:5f034ec8c1ebae5265960b7c47426c464660330c - Cache`

It is clear that is it using the same package location `5f034ec8c1ebae5265960b7c47426c464660330c `, but it does not seem to be tied in any way to the changed `package revision` 

I want to be able to detect that new package revision was generated and rebuild the top level (and anything in between).

**Comment by jgsogo** [comment]
Hi, I can guess what is happening with your [revision_mode](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#revision-mode):

**Expected behavior:** your `revision_mode=hash` and you modify some headers, as you have some attribute of the `scm` feature with an `"auto"` value the hash of the recipe itself should change (the `"auto"` would be resolving to a different commit). 

**What is happening:** you haven't committed those changes (in your log I can read the same line before and after: _"Revision deduced by 'auto': 4d37b68880f3b8bc37a30c82c887fe9d7c2a6486"_). 

Do the commit and you should get a different hash. The warning _"WARN: Repo status is not pristine:"_ is very important if you are using the scm feature (there are some requests to elevate it to error: https://github.com/conan-io/conan/issues/4633).

**Comment by Mark-Hatch-Bose** [comment]
Yes, for local testing you may not want to commit before rebuilding a series of packages.

Dependency Tree; A -> B -> C
Imagine I'm making a change that affects both A and C.
I want to build A locally, then go straight to C and rebuild B against new A.

As I'm iterating on my changes, I may not want yet to commit anything without testing.
We currently for this flow would have to commit every change we wish to test (before we've built!), which isn't ideal.

**Comment by Mark-Hatch-Bose** [comment]
To be clear - This would not be an issue with CI builds, as we would be committing changes (new revision in conanfile) which trigger the build (which we are always updating the version) and that would generate a new package ID which then would force rebuilds upstream.

**Comment by jgsogo** [comment]
So everything works as expected and CI/Jenkins will fall on the right side 😌 , now let's see how to deal with your use case:

Here you are talking about development flow, if you want to work on several packages at the same time  the best you can do is to work on them without `create`, without _uploading_ them to the cache and for that, **we have a couple of features under development that could work for you** (still experimental, but we do love them as C++ developers): [packages in editable mode](https://docs.conan.io/en/latest/developing_packages/editable_packages.html) and [workspaces](https://docs.conan.io/en/latest/developing_packages/workspaces.html).

Using these features you can work on several packages at the same time and include headers and link libraries that are in your local folders (in the local folders where you are working on the dependencies), so there is no need to call `create` (you get rid of that waste of time, because `create` would build your package from scratch).

Let me know if these features go in the right direction given your use case.

Thanks!

**Comment by Mark-Hatch-Bose** [comment]
@jgsogo thanks for the information.

Yes, I think we're all set on CI builds. Our current CI uses unique versioning per commit, so I believe it is basically accomplishing the same task as `package_revisions`. Correct me if I'm wrong. I'm not sure we are ready to switch over to `package revisions` just yet for use in production (as it's still an experimental feature).

I'll look into editable mode/ workspaces to see if it fits my needs for local workflows. It'll definitely be helpful and I'll experiment with it. However, I believe it still doesn't automatically detect the dependency tree and what needs to rebuilt on local change without commit (with -b `outdated`). Since we are using statically linked libraries, it could lead to subtle crashes when doing changes more than one build level apart. (B in example above is not rebuilt and is therefore compiled against a potentially different set of headers for A).

Imagine having 100 dependencies in the tree, and you want to make changes to A and Z which are 20 build levels apart. I believe with `workspaces` that means to rebuild it all correctly with local changes, you'd need a workspace with all the source code checked out and it would rebuild everything. I need to experiment to confirm.

I was expecting `package_revisions` to detect local changes (without commit) to change the output hash of a package and therefore force local rebuilds of the tree intelligently. (Whether using `create` or `export-pkg).
I understand now that the `package revision` hash is calculated AFTER the build is done, so it's already too late! The cache location has not changed.

Anyway thanks for the help. I think this particular issue can be closed now? It seems with either uniquely version packages, or with `package revisions` we are accomplishing the tree rebuilds desired, at least if there is a commit made.

**Comment by jgsogo** [comment]
Yes, you are right on your comments and your concerns. Intermediate libraries of a dependency tree should we compiled again (in the general case) if something upstream changes. To fully achieve this (with all the packages in the cache) you should investigate the different ways you can use to compute package_id ([1](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=full%20package%20mode)) and also you should take a look at this PR https://github.com/conan-io/conan/pull/4958 because it will introduce a new mode which will be affected by any change in a full Conan reference (`name/version@user/channel#recipe_revision:package_id#package_revision`), so Conan will compute a different id and will trigger a new build.

If you have modified your sources (or your recipe) in your local folder, the only way you can integrate them into Conan workflow is with _editables_ or _workspaces_, nevertheless, at this moment, you will need to take control of the modify/build cycle yourself, and also take care of all intermediate libraries.

We think that the _editables_ and _workspaces_ are a very powerful feature and we want to push them forwards as fast as we can, but they are hard, there are many subtilities and it will take us some time to implement them in a stable way.

Thanks for your time and feedback

**Comment by Mark-Hatch-Bose** [comment]
Okay, I came up with a pretty interesting way to get what I want, and it seems to be working!

If the repo is not pristine to change the version to `-dirty` and time.monotonic().
` TestRepo/2.14.11-dirty.7209.710166076@mh/testing`

Then in an upstream I can do `TestRepo/[>=2.10.3-0, include_prerelease=True]@mh/testing`, and it'll pick it up.
Since the package_id has changed because of the timestamp, any future build would get a new hash. Since the version is always increasing, the upstream will always grab the latest one from cache. I'm using `mh/testing` to differentiate my local builds from the official `BoseCorp/` user.

I was able to test this and Build A, export it, then go to C and build it, and it's automatically rebuilding B with `-b outdated`

This should not affect CI, since it will not be `dirty`, and I can add a check to catch `-dirty` builds in CI and error out

Let me know your thoughts.

**Comment by jgsogo** [comment]
Yes, that works for sure. The only caveat is that you have to do manual steps (build A and export it) instead of being able to run the build from C and get everything done. We are working in that direction, we only need some more time to get there 🏃

Meanwhile, your solution is a really nice one 👍

**Comment by Mark-Hatch-Bose** [comment]
Yes, we cannot use `--build X` unless a commit has been made, but I think it's far more powerful to be able to rebuild and change different levels of the dependency tree locally and accurate.

It's also a lot easier to teach/explain this workflow to 100s of engineers. Who may expect things to "just work" without knowing the details of conan caching and package_ids.

I'm going to close this ticket now now. We have multiple ways to force rebuilds of dependencies both locally and remotely.

Thanks again for the help! This is truly awesome.

**Comment by Mark-Hatch-Bose** [comment]
I found a problem with this @jgsogo. I can open a separate question ticket if that is preferred?

If I'm making changes at multiple (3+) levels of the build tree at the same time, all locally, It'll rebuild the middle repos from source. It'll detect SCM (revision: auto) and grab the last commit, rather than the local source repo. A co-worker actually experienced this, while trying to test some changes locally. So this is a real world scenario, believe it or not 💯 

Imagine scenario:
Repo A
Repo B
Repo C

C -> B -> A

Local Changes on Repo A - Build and export
Local Changes on Repo B - Build and export - last commit ID 1
Local Changes on Repo C - Build and export

Local Changes on Repo A (version has increased via time in version above)
Go straight to C and rebuild with `-b outdated`. It will checkout and rebuild with B commitID 1 against new A. This does not reflect the local changes in B

Here is the message outputted, where `scm` auto is detected, and the local source folder is removed:
```
RepoB/3.1.25-dirty.1557438730@mh/testing: WARN: Detected 'scm' auto in conanfile, trying to remove source folder
RepoB/3.1.25-dirty.1557438730@mh/testing: WARN: This can take a while for big packages
RepoB/3.1.25-dirty.1557438730@mh/testing: Configuring sources in /home/mh70023/.conan/data/RepoB/3.1.25-dirty.1557438730/mh/testing/source
RepoB/3.1.25-dirty.1557438730@mh/testing: Getting sources from url: 'git@github.com:BoseCorp/RepoB.git'
```

Is there a way we can control this?
Maybe add a flag in `scm` attribute to not remove (use) the local source folder for `dirty` builds?
Or even just put a "dirty revision" into conanfile.py that is exported. This forces the user to rebuild the repo again by hand, as the revision is invalid (not reflecting local changes)?

I want to duplicate the behavior of local builds in the actual repo basically. (If I was building a repo with local changes standalone). From https://docs.conan.io/en/1.6/creating_packages/package_repo.html#package-repo
> If you build your package locally it will use the local repository (in the local folder) instead of the remote URL, even if the local directory contains uncommited changes. It allows to speed up the development of your packages cloning from a local repository.

**Comment by Mark-Hatch-Bose** [comment]
I understand I could export the sources, and this would also solve my problem.
However, we don't want to export the source code with the output packages cause some of this code is highly confidential, and not all people have access to it. (Also large and cumbersome). Using `scm` auto means that people without source code access won't be able to grab source unless they have git access.

**Comment by Mark-Hatch-Bose** [comment]
Here is what I'm thinking:

```
def mark_dirty():
  git = tools.Git()
  if git.is_pristine():
    return "auto"
  else:
    return None #I WANT THIS TO FORCE IT TO USE LOCAL SOURCE

class RepoB(common.MakefilePackage):
    name = 'RepoB'
    version = common.get_version_git_tag()
    url = "https://github.com/Org/%s" % name
    scm = {
        "type": "git",
        "url": "git@github.com:Org/%s.git" % name,
        "revision": mark_dirty()
    }
```

**Comment by Mark-Hatch-Bose** [comment]
Created a fork with the desired changes, please check out new suggestion #5126
