### ISSUE TITLE
Issues packaging a library using "exports_sources"

### ISSUE THREAD

**Issue by tjwrona1992** [conan-io/conan#4631]
I'm trying to create a package from a CMake project with the following structure:

    CMakeLists.txt <-- uses cmake-conan to run conan and install the gtest dependency
    conanfile.py
    include/
        MyProject/
            <headers>
    src/
        CMakeLists.txt <-- Builds the sources
        <sources>
    test/
        CMakeLists.txt <-- Builds and adds tests
        <tests>
    test_package/

I'm attempting to create a package from it using `exports_sources` but things seem to get strange...

**conanfile.py:**

    class MyProjectConan(ConanFile):
        name = "MyProject"
        version = "0.1"
        settings = "os", "compiler", "build_type", "arch"
        requires = "gtest/1.8.1@bincrafters/stable"
        generators = "cmake"

        # Export the sources since this conanfile will be checked into the git repository with the project.
        # Note: I'm using "*" because I need it to build from the CMakeLists.txt in the current directory.
        exports_sources = "*"

        # This seems to copy all of my source files into ".conan\data\<package>\build\<hash>"
        # Then it proceeds to do a CMake in source build. This seems really messy.
        # I tried adding cmake.configure(build_folder="build") but it didn't have any effect
        # I checked the documentation for the CMake module using "help(CMake) but it isn't clear
        def build(self):
            cmake = CMake(self)
            cmake.configure(source_folder=".")
            cmake.build()

        def package(self):

            # This wont package my header files that are in an "include/MyProject" subfolder?
            # Also I want the "MyProject" subfolder to go with the header files
            # After the package is installed the headers should be referenced like this:
            # #include <MyProject/header_file.hpp>
            self.copy("*.h*", dst="include", src="MyProject")

            self.copy("*.a", dst="lib", keep_path=False)
            self.copy("*.dll", dst="bin", keep_path=False)
            self.copy("*.dylib", dst="lib", keep_path=False)
            self.copy("*.lib", dst="lib", keep_path=False)
            self.copy("*.so", dst="lib", keep_path=False)

        def package_info(self):
            self.cpp_info.libs = ["MyProject"]

To install/build the package in my local cache I do the following:

    conan export . tjwrona/testing
    conan install MyProject/0.1@tjwrona/testing --build MyProject

The two main issues I am having are:

1. The build step seems to just throw all of the sources into the `data\<package>\build\<hash>` folder and then does an in-source CMake build.
  - I would expect it to do an out of source build where it runs CMake from the build directory but executes it on `data\<package>\source`. This would leave only the build results in the build folder and no sources.
  - This seems particularly messy because after the build it now has all of the source files copied in 3 separate locations. They end up in `data\<package>\export_source`, `data\<package>\source`, and `data\<package>\build\<hash>`. I understand how it ends up in the first two locations, but how it ends up in the build folder has me stumped.

2. Since my header files are in an "include/MyProject" subdirectory the package command doesn't seem to handle them right. I have searched the documentation and can't seem to find any examples of how to package a library that has this project structure. I find it a little surprising that I can't find an example because most CMake projects are structured this way and don't have the headers and source files in the same directory.
  - Can someone point me to some documentation that explains how to use Conan with a project that is structured this way (that uses `exports_sources` so local sources can be used)
  - Ultimately I would also prefer to put the `conanfile.py` and `test_package` folder in a `conan` subdirectory but I can't seem to find any examples on how to do this either.

**Comment by uilianries** [comment]
Hi @tjwrona1992 !

> 1. The build step seems to just throw all of the sources into the `data\<package>\build\<hash>` folder and then does an in-source CMake build.

Actually, Conan copies from `data\<package>\source` to build folder to avoid contamination by caching files and binaries generated during the build. You can check on [Package development flow](https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html)

>  I would expect it to do an out of source build where it runs CMake from the build directory but executes it on `data\<package>\source`. This would leave only the build results in the build folder and no sources.

The source folder, as the name suggest, it's a folder only to keep the source code. It is useful when you build the project for a different configuration, but don't want to download all files again.

> This seems particularly messy because after the build it now has all of the source files copied in 3 separate locations. They end up in `data\<package>\export_source`, `data\<package>\source`, and `data\<package>\build\<hash>`. I understand how it ends up in the first two locations, but how it ends up in the build folder has me stumped.

Actually they have different proposes, you can read the [Package Creation Process](https://docs.conan.io/en/latest/creating_packages/understand_packaging.html#package-creation-process), but just for resuming: The `exports_sources` is folder used to store your sources when you want to install a package, but you need to build from sources. Since `exports_sources` is present in your remote, Conan will download from there and build the project on your host, so it works for distribution. The `source_folder` is the folder used to store the source code only and it makes more sense when you are building a package that the projects needs to be downloaded. It will be re-used when you need to build multiple configurations (1 source x N packages). And finally `build_folder`, it's a folder used to build the project. Since it could contains some cached files and all artifacts generated, we have one build folder by configuration. Conan provides the attribute [no_copy_source](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#no-copy-source) to avoid new copies from source to build folder, but it's only recommended for header-only projects, since the source will be re-used to package for all configurations.

> 1. Since my header files are in an "include/MyProject" subdirectory the package command doesn't seem to handle them right. I have searched the documentation and can't seem to find any examples of how to package a library that has this project structure. I find it a little surprising that I can't find an example because most CMake projects are structured this way and don't have the headers and source files in the same directory.

We have a description [how to build a package when sources and recipe are in same repo](https://docs.conan.io/en/latest/creating_packages/package_repo.html#recipe-and-sources-in-the-same-repo). If your commands are failing, I would suggest to check if your cmake file is calling `conan_basic_setup`. Also, check if your forcing cmake paths, like `CMAKE_SOURCE_FOLDER`. I would suggest to read the [cmake generator](https://docs.conan.io/en/latest/integrations/cmake/cmake_generator.html) section to understand how CMake works with Conan.

> * Can someone point me to some documentation that explains how to use Conan with a project that is structured this way (that uses `exports_sources` so local sources can be used)

We have many projects using this approach:
- https://github.com/taocpp/PEGTL/blob/master/conanfile.py
- https://github.com/google/flatbuffers/blob/master/conanfile.py
- https://github.com/civetweb/civetweb/blob/master/conanfile.py

> * Ultimately I would also prefer to put the `conanfile.py` and `test_package` folder in a `conan` subdirectory but I can't seem to find any examples on how to do this either.

Please, take a look on the projects described above, they use the `test_package` folder in a custom path. Also, if you can check the command reference, like [create](https://docs.conan.io/en/latest/reference/commands/creator/create.html), you will see the argument `--test-folder` which can be used for custom `test_Package` folder. Your recipe can be stored in any folder, since you pass the correct path for Conan commands.

Please, feel free to ask us any help, and take a look in Conan docs to get more details.

Regards!

**Comment by tjwrona1992** [comment]
Thank you for all of the useful feedback and links to more information!
