### ISSUE TITLE
Better action on warning or error

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#4633]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.12

Some CI systems (TeamCity in particular) has special handling of writes to stderr: the step which has non-empty stderr is highlighted and there is even an option to fail the build in this case.

However Conan writes both warnings and errors to stdout just with different color.
Given large outputs and the fact than no one continuously scans build logs manually this may hide warnings which otherwise would be really good to act upon.

Here are my ideas (pick any combination of them):
1. And opt-in (possibly via env variable) to write errors and warnings to stdout
2. `-Werror` analog
3. Integrate with hooks. Although it's trickier to pass context in which error occurred. I was thinking more about filtering: I want to avoid this warning: #4602, but at the same time "Repo status is not pristine:" is important.
4. Extension: number or name warnings to suppress / promote to fatal ones via configuration.

**Comment by jgsogo** [comment]
Hi, @ytimenkov 

IMO it makes sense to print the errors (and probably the warnings too) to the `sys.stderr` instead of `sys.stdout`. I'm not sure if this is something we can do out of the box or there is some usage that prevents us from doing it (probably not).

Nevertheless configuring which _errors/warnings_ should be informed or not, or promoted to errors or ignored is a little bit harder (add every warning an id, document, stability, configuration, filter them,...) and will require further discussion.

I'm tagging this as _look into_, I think it is worth considering (the first one) for a future release and then talk about the second one.

Thanks for the suggestion.

**Comment by ytimenkov** [comment]
I think this was addressed in #5206
