### ISSUE TITLE
[RFC] Use python_requires to set the base class of a conan file

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#4639]
Currently, a ConanFile class can use a conanfile of a python_require as follows:
```
base = python_requires('BasePackage/0.1@base_user/base_channel')

class MyConan(base.BasePackageConanFile):
    ...
```
But this will lock the dependency of MyConan to `BasePackage/0.1@base_user/base_channel`.
If some user wants to fork this MyConan recipe on his private some_user/some_channel,
this dependency cannot be changed easily. He must change all occurrences of python_requires with:
```
base = python_requires('BasePackage/0.1@some_user/some_channel)
```
It would be nice if a ConanFile can programatically set his base class.
I propose something as follows:
```
class MyConan(ConanFile):
    def python_requirements(self):
        base = python_requires('BasePackage/{}@{}/{}'.format(self.version, self.user, self.channel))
        self.conan_super_class = base.BasePackageConanFile
```

conan would need to divert all calls to source, build, package, configure, config_options, package_info, requirements, build_requirements, options, settings, name, version ... if the MyConan recipe does not have an implementation.

Also, the functions in `MyConan` should be able to specialize the functions of `BasePackageConanFile` and call its functions.

See bincrafters/conan-flex#5 for an application where this might be useful.
Having the ability to modify the python_requirement would allow a distinction between e.g. bincrafters/testing and bincrafters/stable.

**Comment by Johnnyxy** [comment]
I am using such a technique to provide a common base class for certain recipes. There I face the same problem that the ```python_requires``` cannot influenced from the inheriting recipe.
I did not see in other programming languages that a structure (e.g. class) could replace its base structure thus I do not think this is possible in Python.

A simpler approach would be to have a function that returns the conan-instance (conanfile object; class-instance).
```python
def get_conan_recipe(*args,**kwargs):
    base = python_requires(...)

    class MyRecipe(base.A_Common_Conan_Base_Class):
        pass

    return MyRecipe()
```

**Comment by jgsogo** [comment]
Python let you do crazy things, you can build classes dynamically, modify them,... almost anything is possible, but for the Conan logic POV it is compulsory to resolve first the full reference of a `python_requires` (`username` and `channel` too) before trying to load the `ConanFile` because they can affect to the recipe itself. Otherwise, it would be a chicken-and-egg problem.

You can even also have a function in the `python_requires` that returns a different implementation of a `ConanFile` depending on some variables (like @Johnnyxy suggested):

In the `python_requires` recipe:
```python
def build_conan_base(opt1, opt2,...):
    if opt1 == value1:
        class BaseConanfile(ConanFile):
            def source(self):
                # Implementation for opt1==value1
                ...
         return BaseConanfile

    elif opt1 == value2:
        class BaseConanfile(ConanFile):
            def source(self):
                # Implementation for opt1==value2
                ...
         return BaseConanfile

```

In your consuming `conanfile.py`

```python
base = python_requires("...")

class MyLib(base.build_conan_base(opt1, opt2)):
    ....
```

but once again, `opt1` and `opt2` cannot depend on a MyLib object, we need to know them before instantiating the MyLib class.

I think this cannot be done the other way around.

**Comment by jgsogo** [comment]
I'm closing this issue, there is not much to say about it. It is not possible for a ConanFile to inherit from a reference that depends on the ConanFile itself... it will create a circular dependency.
