### ISSUE TITLE
Do something after download of already build packages

### ISSUE THREAD

**Issue by Kretsch0** [conan-io/conan#465]
Hey,

my idea is to download my already build libs and executables and call a "AfterInstall"-Method.
-> This would be great to do a deployment of binaries to a system specific location. 

Second example is more complex.
If someone in my company tries to find my already build libs, he normally calls a cmake-find-script.
Unfortunately his development does not work with conan. So - how to know the packagefolder/hash?
-> if there would be a "AfterInstall"-Method I could export the findscript, lib, include, bin folder to a given path (argv)

Do you have any ideas?

**Comment by memsharded** [comment]
I am not sure if I understood, the packagefolder/hash is defined by conan, so if he is not working with conan, he will not have the package in their machine, and he will not be able to find it, because there is no path to point even with the cmake-find-script.

Probably the way to go could be to write a generator. It is not difficult, and is the main existing extension point for conan right now. 

- Have a look to: http://docs.conan.io/en/latest/howtos/dyn_generators.html
- You might also be interested in: http://docs.conan.io/en/latest/integrations/other.html

If you need, I could connect to the #conan freenode channel and talk.

**Comment by monsdar** [comment]
I recently talked to him about that feature - perhaps I can help:

What he would like to do is to trigger a certain action after a user performed `conan install foo/1.0.0@user/bar`. The conanfile.py could contain a new extension point like `def afterInstall()` where there could be custom code to copy some files onto the users computer.

Let's assume the user wants to install MyLibrary but he wants the DLLs in the directory `c:\temp\MyBoost\`. The `afterInstall` method could then copy it for him to the desired directory.

A workaround could be to put the copying into `def build()`, but that would mean that the component needs to be rebuilt instead of just copying it.

I'm not sure if the example with the Libs I gave is the best. This could be useful for copying files, setting up environments etc. It would be a very useful feature if you would like to use conan for deployment purposes.

This obviously is also a security risk, as there could be a `conanfile.py` that does `rm -rf` after installation.

**Comment by memsharded** [comment]
Hi @monsdar, thanks for the feedback and the ideas, but it might not be a manageable approach. 

There already exists the ``imports`` functionality to copy the DLLs and other files to folders outside the local conan cache.  Define in the **consumer** conanfile.txt or conanfile.py which files you want to copy and where, and run install as usual.

The issue is that letting a package defining a system path for its binaries would be complicated and error prone:
- The package author will have to consider all OS differences
- The host machine might not have certain paths, e.g. my win machine has not C: but D:
- Moreover, in general, consumers don't want from a package manager to install things around in their systems without they knowing. One of the good things of a package manager is that it provides a good known location for the installed binaries. Remove the local conan cache and your system will be completely clean. Handle different binaries in different caches without problems for concurrent usage or for separating projects. Let the packages put DLLs in different places in the system and you will have an unmanageable machine, not knowing with DLLs are being used in runtime.

The only issue that comes to my mind with the ``imports`` feature is that it might not be prepared to receive absolute paths, but this could be easily fixed. Otherwise, it is the way to go, and the way other users are doing this in production.

**Comment by memsharded** [comment]
Great, thank you! So @Kretsch0 , if you want to try the ``imports`` approach and have some question, please tell us.
