### ISSUE TITLE
copy during imports should have configurable behaviour regarding overwriting files

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#4684]
Calling self.copy during a conanfile's imports method should have configurable behaviour regarding the overwriting of existing files (i.e. the same files from multiple packages):
* Overwrite without any warning (this is the current behaviour)
* Overwrite but output a warning
* Do not overwrite but output a warning
* Fail with a ConanException

The existing "folder" option is related to this, but placing all such files into different locations may not be what is required to set up a usable workspace.

**Comment by jgsogo** [comment]
Hi @sigiesec!

This is not difficult to implement (without breaking current implementation) and some users may find it useful. I can't see any reason not to do it and it will prevent accidentally overriding some files.

I'm not sure, nevertheless, if we should create this new config parameter, or we should just print the warning if the file is being overwritten with different content and then allow the user to specify if some warnings should be treated as errors (this is somehow related to #4633 or #4681, or even #4473).

Would it be ok to follow the path proposed in #4633 instead of having a new config parameter?

**Comment by sigiesec** [comment]
For my uses, having this as a default warning would with the option to treat it as an error would be ok. In general, I think that it would be good to allow to disable the warning as well (same is true for any warning).

**Comment by jgsogo** [comment]
I'm adding this issue to the queue along with the others in the project [Output levels, warnings and errors](https://github.com/conan-io/conan/projects/16#card-18575471), although maybe we should summarize all the _warnings as errors_ request into a single issue (maybe https://github.com/conan-io/conan/issues/4633)

**Comment by memsharded** [comment]
The ``imports()`` method removed in 2.0, replaced in 1.X by ``generate()`` calls to ``copy()`` and 2.0 has ``deployers`` too. Closing as outdated.
