### ISSUE TITLE
[editable] Developing an Apple framework: compiler flags depend on layout

### ISSUE THREAD

**Issue by lordzsolt** [conan-io/conan#4729]
Conan Version: 1.12.2
Operating System: macOS 10.14

**Motivation:**
Avoiding the need to export new version or clear conan local cache by using [editable mode](https://docs.conan.io/en/latest/developing_packages/editable_packages.html).

**Problem:**
- The layout file passed through `--layout` to `conan editable add` is only parsed _after_ the `package_info` step. 
- `package_info` step is also used to specify the framework search path for Apple Frameworks, based on [this documentation](https://docs.conan.io/en/latest/howtos/link_apple_framework.html#how-to-package-apple-frameworks)
- Specifically, the `f_location = '-F "%s"' % self.package_folder` will not have access to the `libdirs` defined in the layout file.

**Possible solution:**
Have access to the `libdirs` from the layout file when running `package_info`

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment]
This is a use case where a compiler flag (not considered in the `layout` files) depends on a path of the same library which is in the `layout` file. 🤔  I'm sure we didn't think about this when we were discussing the layout files. We have to think about how to manage this situation, I'm not sure if there is clean implementation. 

Meanwhile, you can define the editable layout in the `package_info()` method, inside the recipe, using the `self.in_local_cache` member attribute, you can read about it [here](https://docs.conan.io/en/latest/developing_packages/editable_packages.html?highlight=in_local_cache#recipe-defined-layout). It is not the cleaner implementation, because you could end up with _local_ information in your recipe, but there you will have all the information needed to handle the situation.

Let me know if you can implement what you need with the help of `self.in_local_cache`. Thanks!

**Comment by lordzsolt** [comment]
Thank you for your reply. Yes, I thought about `if`-ing on `self.in_local_cache` and just use a hardcoded path (essentially the same as the one in the layout file) but I wasn't too fond of that solution, because in my use-case, there would be multiple layout files based on the IDE you're using.

If there's no cleaner solution, feel free to close the question and consider it a feature request 😄

**Comment by jgsogo** [comment]
I'm afraid that right now there is no cleaner solution :/ I'm removing the `[question]` part from the title and adding it to the queue, we have to consider this use case.

One more thing: I've never written a _framework_ for Apple, is there an easy example (with Conan recipe) you can share with us to have it as a reference when talking about this _feature request_? Also, having examples with several IDE layout files would be awesome! Thanks!

**Comment by jgsogo** [comment]
This PR is related: https://github.com/conan-io/conan/pull/5552. After merging that feature into Conan, some changes to _editables_ must be done and I think that this one should be easier to fix.

**Comment by memsharded** [comment]
Closing ticket as outdated, ``layout()`` deprecated this --layout arguments long time ago
