### ISSUE TITLE
CMake Windows debug builds with MSVC end up using /MD instead of /MDd

### ISSUE THREAD

**Issue by sunsided** [conan-io/conan#475]
For some reason, Conan forces the linking type to `/MD` or `/MT` on Windows when CMake with Visual Studio is selected, no matter the `build_type`. This leads to nasty situations where `build_type=Release` works fine, but builds using `build_type=Debug` fail. 

It basically boils down to [this section](https://github.com/conan-io/conan/blob/70c8ca3050dbe68cd608f31294ee1f17a44d6f92/conans/client/generators/cmake.py#L126-L139) in the generated `conanbuildinfo.cmake`. It seems the `cmake.command_line` already contains the `/MD` (or `/MT`) switch through `CONAN_LINK_RUNTIME`, even though `/MDd` and `/MTd` would have been used otherwise.

**Comment by sunsided** [comment]
If worked around this by defining

```python
if settings["compiler"] == "Visual Studio" and settings["build_type"] == "Debug":
    if not settings["compiler.runtime"].endswith("d"):
        settings["compiler.runtime"] += "d"
```

in `build.py` but wonder if this could be default behavior.

**Comment by memsharded** [comment]
Yes, it seems there is something wrong there, not sure why it has not been reported before. As you are using ``build.py``, I guess you are also using conan-package-tools? They also define the runtimes while generating the build combinations, could be an issue of conan-package-tools, not conan. I will have a closer look, thanks for reporting!

**Comment by sunsided** [comment]
It's still a bit of a puzzle to me. :sweat_smile:  I did manage to get it fail with `conan test_package --build -s build_type=Debug` as well though.

**Comment by memsharded** [comment]
I think I am starting to figure out:

- Conan does not enforce any linkage with ``/MD`` or ``/MT`` and matching ``d`` debug options.
- They are defined as a setting of "visual studio" compiler, so it can be defined as:

  ```bash
  $ conan install . -s compiler="Visual Studio" -s compiler.runtime="MTd" -s compiler.version="12" 
  ```
- The setting can be also defaulted in the ``conan.conf`` file
- They are defined as inputs, and not necessarily matching the debug/release ``build_type``, because they are not enforced by VS. You can link with ``MT`` or ``MD`` even if in debug mode. Must do if you are distributing your debug artifact. Maybe it is not the best, and the ``MXd`` versions are recommended, but seems possible.
- One general policy for conan is not to automatically decide or interfere with user configuration. So conan will never decide to use ``MDd`` because the ``build_type`` is ``debug``, it has to be explicitly defined by the user.
- It is possible that a package recipe doesn't honor ``CONAN_LINK_RUNTIME``, e.g. if not calling ``conan_basic_setup()``. In that case, the binary runtime is only defined by the build internals, and could be defaulted to match the debug/release config. Typically would be ``MD`` by default.

In your case, I'd say that the ``MD`` is not enforced, but defined in your ``conan.conf`` as default. Then the conflict can arise if your dependencies are not adequately managing the ``runtime`` input setting. I think you could fix it just by specifying the ``runtime`` in your command line. 

Does all of this make sense? Please tell me. Thanks very much for your feedback!

**Comment by sunsided** [comment]
It does. One situation for the `/MD` vs. `/MDd` madness is when linking against Python, which for some reason, never exists as a debug build.

Do you think it would make sense to introduce build type specific defaults, i.e. for release and debug given a specific generator? This way, `/MD` could be the default for release and `/MDd` the default for debug. It wouldn't help much with Python obviously, but it that might then just be the exception from the rule.

**Comment by memsharded** [comment]
Yes, it would make sense, but the fact is that conan does not define the build. The build is managed by the package creators build scripts. Or do you mean, add the ``-s compiler.runtime=MDd`` by default when the debug type is ``Debug``? Or maybe, just take the user default ``MX`` and do ``-s compiler.runtime=MXd`` for Debug ``build_type``?

**Comment by sunsided** [comment]
The first one, but by means of the configuration file. The idea is that conan wouldn't have to know about Visual Studio but rather understand a slightly more generic default configuration; basically the defaults would be per compiler, but conditional on the `build_type`.

**Comment by memsharded** [comment]
Maybe and idea could be having "profiles", something like:
```
VSdebug: "-s arch=x86 -s build_type=Debug -s compiler="Visual Studio" -s compiler.runtime=MDd"
VSrelease: "-s arch=x86 -s build_type=Release -s compiler="Visual Studio" -s compiler.runtime=MD"
MinGWrelease: "-s arch=x86 -s build_type=Release -s compiler="gcc"
...
```

Conan could have some of the pre-defined, but of course they could be manually edited/added/removed, probably in the ``conan.conf``.

In this way, conan does not have to implement any logic at all. Otherwise, even if it is per-compiler, conditional to ``build_type``, it would have to be implemented somewhere, messing with the runtime. From previous experience, I'd say that such approach fails at some point, doing something inconvenient for some user.

This feature has been discussed before, but was discarded because it was enough to have some OS specific solution, as shell variables. Maybe it can be reconsidered if this improves usability.

**Comment by sunsided** [comment]
Profiles actually sound awesome. :+1: 

(otherwise I think we can close this, it really seems to be "just" an UX thing)

**Comment by memsharded** [comment]
Yes, lets move it to #271, thanks again for your feedback!

**Comment by monsdar** [comment]
Just to give some input: I just encountered the exact same problem. I was compiling with `-s compiler="Visual Studio" -s build_type=Debug -s compiler.version=10 -s arch=x86` and did not set `-s compiler.runtime=MDd"`. This resulted in my DLL being in Debug and MD at the same time.
