### ISSUE TITLE
[feature request] deps_env_info should be passed to generators

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#4772]
Hello,

This feature request is motivated by #3303.

As of now, using a build requirement like [android-ndk](https://github.com/theodelrieu/conan-android-ndk) **requires** having a consumer `conanfile.py`, a `conanfile.txt` cannot be used.

The main problem is that `self.deps_env_info` are applied during the consumer's `build` method, but are not passed to generators.
In the case of `android-ndk`, I define a `CONAN_CMAKE_TOOLCHAIN_FILE` in the environment which is not present in `conanbuildinfo.cmake`.

Therefore, a user cannot keep a simple `conanfile.txt`, adding a `[build_requires]` section and cross build for android.

/cc @sztomi 

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment]
But even having the `CONAN_CMAKE_TOOLCHAIN_FILE` var somewhere in the `conanbuildinfo.cmake` file, it will be useless, because the `CMake()` build helper is the one using it to adjust the toolchain. You could modify the `CMakeLists.txt` to manage it but even though I think it won't work because it has to be injected to the `cmake` call as a definition.

I don't think exposing the env vars in a cmake generator has any sense. You can use the `virtualenv` generator to get that variable set, and then call `cmake` with `-DCMAKE_TOOLCHAIN_FILE=$CONAN_CMAKE_TOOLCHAIN_FILE`

**Comment by theodelrieu** [comment]
True... I didn't know about the virtualenv generator, I'll take a look

**Comment by theodelrieu** [comment]
Thanks, it seems to solve the issue for `conanfile.txt` projects.
