### ISSUE TITLE
fPIC flag not set automatically when building static library + fPIC option

### ISSUE THREAD

**Issue by newlawrence** [conan-io/conan#4773]
Hi, I was making my own packages for the **Xiph.org**'s libraries [**ogg**](https://github.com/xiph/ogg) and [**vorbis**](https://github.com/xiph/vorbis), when  I noticed a behavior that contradicts something that the documentation indicates.

I was trying a static build of **ogg** to build against a dynamic build of **vorbis**, for which I needed to enable the **position independent code** flag on the former. As stated in the [documentation for the attributes](https://docs.conan.io/en/latest/reference/conanfile/attributes.html), the **CMake build helper** should handle this automatically. But that isn't my case when creating the package while specifying `-o shared=False` + `-o fPIC=True`; I had to set the flag manually (you can also see that been taken into account in the [Bincrafter's recipe](https://github.com/bincrafters/conan-ogg/blob/stable/1.3.3/conanfile.py)).

My question is, am I misunderstanding something, or is it a bug? The flag is properly set when building using the **Autotools helper**.

My current setup is: **Linux** (*CentOS 7.6*), **Conan 1.13.1** (*Python 3.6.3*) and **CMake 3.13.4**.

Thank you so much for your time.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by uilianries** [comment]
Hi @newlawrence !

> I was trying a static build of ogg to build against a dynamic build of vorbis, for which I needed to enable the position independent code flag on the former.

Both libraries have `fPIC` enabled by default, you don't need to force it.

> As stated in the documentation for the attributes, the CMake build helper should handle this automatically.

Yes, that's true. Both `shared` and `fPIC` are automatically parsed by Conan CMake helper.

> But that isn't my case when creating the package while specifying -o shared=False + -o fPIC=True

You must specify <package>:<option> e.g. ogg:shared=True
But those recipes are old and `fPIC` will affect `CMAKE_POSITION_INDEPENDENT_CODE` with no line [38](https://github.com/bincrafters/conan-ogg/blob/stable/1.3.3/conanfile.py#L38) in the recipe.

I would say it is not a bug, otherwise many other recipes should also be broken.
Which commands did you use to build the packages? Please, describe all steps that you used to build.

Regards!

**Comment by newlawrence** [comment]
Hi @uilianries. I'm afraid I didn't explain myself precisely, so lets give it another try. I've managed to get a way to fast reproduce the (alleged) bug.

First, I wasn't using the recipe from **Bincrafters**, I was writing my own at work for consume **ogg** and **vorbis** internally, which is the reason of why I was enforcing **fPIC**; mine has that flag set to false by default. The rest of my recipe looks like more or less the same.

Ok, so, after I published my issue yesterday, I've been testing **Bincrafters**' comenting the lines where they manually set the **Cmake** definition and... surprise! If you look at the build commands being generated, the automatic specification of **fPIC** flag seems to being working.

Back to my code, one of the differences between those two recipes is in the configuration of the **CMake** project; given the way we are retrieving the sources internally I have to specify the sources folder. So, what in my recipe is `cmake.configure(source_folder=self.source_subfolder)` in **Brincrafters**' is just `cmake.configure()`. If I edit this line in **Brincrafters**' the bug appears again and **Conan** doesn't set the **fPIC** automatically.

### Way to reproduce the bug
* Under **Linux**, clone the **Bincrafters**' [recipe](https://github.com/bincrafters/conan-ogg).
* In **conanfile.py**, edit the `build` command to disable the manual specification of **fPIC** and make the build verbose to see the commands being executed. This is how my `build` method looks like:
```python
    def build(self):
        cmake = CMake(self)
        # if self.settings.os != "Windows":
        #    cmake.definitions["CMAKE_POSITION_INDEPENDENT_CODE"] = self.options.fPIC
        cmake.configure()
        cmake.build(args=['--', 'VERBOSE=1'])
        cmake.install()
```
* Create the package avoiding the tests with the following command (defaults will be set to: *shared*=**False** and *fPIC*=**True**, which is what I wanted):
```conan create . ogg/1.3.3@bincrafters -tf=None```

Following the previous steps, the flag is correctly set automatically as we can see in the output:
```
[ 33%] Building C object sources/CMakeFiles/ogg.dir/src/bitwise.c.o
cd /home/alberto/.conan/data/ogg/1.3.3/bincrafters/stable/build/d50a0d523d98c15bb147b18fa7d203887c38be8b/sources && /opt/rh/devtoolset-7/root/usr/bin/cc  -I/home/alberto/.conan/data/ogg/1.3.3/bincrafters/stable/build/d50a0d523d98c15bb147b18fa7d203887c38be8b/sources/include  -m64 -O3 -DNDEBUG  -fPIC   -o CMakeFiles/ogg.dir/src/bitwise.c.o   -c /home/alberto/.conan/data/ogg/1.3.3/bincrafters/stable/build/d50a0d523d98c15bb147b18fa7d203887c38be8b/sources/src/bitwise.c
```
But if we change the configure line to `cmake.configure(source_folder=self.source_subfolder)` (which shouldn't make a change at all in this case), we can see the **fPIC** flag is no longer set:
```
[ 33%] Building C object CMakeFiles/ogg.dir/src/bitwise.c.o
/opt/rh/devtoolset-7/root/usr/bin/cc  -I/home/alberto/.conan/data/ogg/1.3.3/bincrafters/stable/build/d50a0d523d98c15bb147b18fa7d203887c38be8b/sources/include -I/home/alberto/.conan/data/ogg/1.3.3/bincrafters/stable/build/d50a0d523d98c15bb147b18fa7d203887c38be8b/include  -O3 -DNDEBUG   -o CMakeFiles/ogg.dir/src/bitwise.c.o   -c /home/alberto/.conan/data/ogg/1.3.3/bincrafters/stable/build/d50a0d523d98c15bb147b18fa7d203887c38be8b/sources/src/bitwise.c
```

So, it seems that the **fPIC** flag is not automatically set when needed if keyword arguments are given to the `configure` method of the **CMake** build helper. By the way, the **-m64** flag seems to be missing too (I forgot to mention that I was compiling targeting **x86_64**).

**Comment by uilianries** [comment]
> So, it seems that the fPIC flag is not automatically set when needed if keyword arguments are given to the configure method of the CMake build helper. By the way, the -m64 flag seems to be missing too (I forgot to mention that I was compiling targeting x86_64).

I think you didn't understand the CMake helper. Let's take a look further.

The `cmake.configure()` it equivalent to:

    cd /home/alberto/.conan/data/ogg/1.3.3/bincrafters/stable/build/d50a0d523d98c15bb147b18fa7d203887c38be8b && cmake .

However, `cmake.configure(source_folder=self.source_subfolder)` is equivalent to:

    cd /home/alberto/.conan/data/ogg/1.3.3/bincrafters/stable/build/d50a0d523d98c15bb147b18fa7d203887c38be8b && cmake source_subfolder

What is the difference? Well, the build folder contains the CMake Wrapper, which imports `conanbuildinfo.cmake` AND call `conan_basic_setup()`, which will configure your build, including the `fPIC`.

Although, when you point cmake to use `source_subfolder`, it will load the original CMakeLists.txt from ogg and will skip all Conan steps.

It's important to understand that Conan will not make any black magic when calling cmake, that's why we use helpers. CMake is not the only "build system" for C/C++, that's why Conan is uncoupled from the build system.

We have two approaches to manipulate CMake + Conan:

- Execute `tools.replace_in_file()` to patch the original CMakeLists.txt, adding:
  ```
  include(conanbuildinfo.cmake)
  conan_basic_setup()
  ```
- Add CMakeLists.txt as an wrapper

Bincrafters prefer the second option because it is preferable to keep the source untouched.

So, keep in mind if you want to customize the source folder, you will need to load `conan_basic_setup()` anyway.

There is an excellent documentation about [CMake helper](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#cmake-reference) in docs.

Regards!

**Comment by newlawrence** [comment]
Oh, I have to admit that you're totally right!

I didn't understand well how **Conan** was handling **CMake**. Thanks to your explanation I comprehend now why **Bincrafters** ship their own **CMakeLists.txt** within the recipe and a bit better the "magic" behind the **source** and **build** steps.

Thank you so much for your kind response and your time.

**Comment by uilianries** [comment]
Nice!

Please let me know if you need anything else or we are good to close this issue.

Regards!

**Comment by newlawrence** [comment]
I think we're done. I'll close the issue!
