### ISSUE TITLE
[conanfile] Issue a warning when a copy command copies nothing

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#4791]
I just spent about 30 minutes trying to figure out why my package kept coming up empty after running conan create.

Turns out I was so used to dealing exclusively with header files I didn't make the connection that the header-only library I was packaging used the `.hpp` convention. I was running `self.copy("*.h")`.

It might be a good idea to issue a warning if no files are actually copied in a particular copy command. We already warn if the package ends up empty but some people like myself sometimes need a bit more of a hint :1st_place_medal:

**Comment by memsharded** [comment]
Uhmm, that might be a bit problematic, as there are users `(in fact it can be found in the docs and examples!) doing the following:

```python
def package(self):
    self.copy("*.a", .....)
    self.copy("*.lib", ....)
    self.copy("*.dll", ....)
    self.copy("*.so*", ....)
```

Which is very simple and works for all platforms. In each one it will collect the matching extensions.

If we make ``self.copy()`` to warn, then many users will start seen confusing warnings, and will be concerned, and start to complain.

A possibility would be to add an opt-in: ``self.copy("*.a", ...., warn=True)``, or maybe even launching an error ``self.copy("*.a", ..., error_if_empty=True)``. But still, the problem is with those opt-ins is that they are not the default, it would be a big ugly to change it everywhere in the docs and make the ``package()`` method more complex, and then people might still end up with the same debugging session "why my headers were not copied".

We thought that the copied files, summarized by extensions should be a sufficiently good indicator of what is happening. 

What do you think?

**Comment by Lawrencemm** [comment]
:thinking: 

Your are practically right, though I did always find this practice a bit inelegant. The whole catch-all thing and a big ream of platform-specific extensions there in your conanfile. 

I think it's always better to have the program do what is necessary for the particular situation it is in, than form a sort of big union of all possible scenarios and run them all. I'm sure you have your ideas about this. Alas there are better hills to die on at this point.
