### ISSUE TITLE
Editable packages should be built automatically?

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4837]
Related to #4836
For example, if A -> B -> C. If `C` is editable and you run `conan install . --build` from `A`: Should `C` be created? how? running conan local methods? obviously, it would require the layout of the package to declare at least the `[build_folder]` and optionally the `[source_folder]` and `[package_folder]`.

**Comment by g-radam** [comment]
This is something I would personally **_really_** like to see working in Conan. My thoughts currently:

Workspaces do the trick within a single folder hierarchy (when a project owns / knows where its dependency are located). However, if I have several common packages floating around on my PC not within any one workspace, I'd still like to see them be built as part of an application. (Of course, I would set these local packages as editable, so my other projects can locate & build them). 

My use case is really only for local development. I can just build my application, knowing it will build its library dependencies I'm also working on, without having to install/export all of those dependencies. I like the idea that my application does not know or care if it got its dependencies from a local editable package(it built from source), else pre-build release binaries from a remote repository. This will cover me as a developer using local files, and end users getting the final release packages.

Unless there is away to do this now (this issue is 1yr old), It hasn't been clear from the documentation.

**Comment by memsharded** [comment]
Hi @g-radam 

Editable packages and workspaces are something we definitely want to improve, and this is one of the things that we will seriously consider. The only problem is that at the moment there have been a few other higher priorities so we couldn't put time on this one. Thanks for the feedback, we will certainly take it into account when we revisit this.

**Comment by memsharded** [comment]
Editable packages got the capability in 2.0 of ``--build=editable``, so all packages in editable mode will do incremental builds as necessary. Closing as solved.
