### ISSUE TITLE
[Bug] Building depencency from dependant folder by conan create . --target dependency does not propagate all options

### ISSUE THREAD

**Issue by trondhe** [conan-io/conan#4861]
_Disclaimer: I am currently obvious on that using option to set a toolchain path in the profile would result in a new package ID if that path changes even if the toolchain is the same, which will be sub-optimal, will figure out a different solution for it. Problem still stands._

[options] defined in a profile will not propagate for all values/situations.
My given profile sets a few variables and a path to a *toolchain.cmake file which is then set as a definition by `cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = self.options.toolchain`.

Given library `foo` and library `bar`. `bar` does not depend on anything and can be build standalone, while `foo` depends only on `bar`.
In `bar` project folder, running `conan create . user/channel -pr=myprofile` builds it fine with all options correctly set.
`foo` has the given line in its conanfile.py `requires = "bar/version@user/channel"`. From `foo` project folder, then running the command `conan create . user/channel -pr=myprofile --build=bar`.
Looking at the output, in similar fashion to my issue reported here https://github.com/conan-io/conan/issues/4832, the command variable at line 195 in cmake.py is missing the define for `CMAKE_TOOLCHAIN_FILE`.

With further testing, adding a test options in the conanfile, and in the profile, but *no* default_options.
example conanfile.py:
```
    options = {
        "nativeBuild": [True, False],
        "toolchain": "ANY",
        "var2": "ANY",
        "var3": ["one", "two"]}
    default_options = {
        "nativeBuild": True,
        "toolchain": "",
        "var2": "woo"}
```
and in profile
```
[options]
nativeBuild=False
toolchain=D:/VxWorksToolchain/toolchain/vxworks_toolchain.cmake
var3=one
```
I do not even have to go through cmake to see the error, as conan will report that var3 is not defined for `bar`, even if it is specified in the profile.
This leads me to belive that *no* options set in the profile are propagated to `bar` while using `conan create . -pr=myprofile --build bar`.

**Comment by jgsogo** [comment]
Hi, @trondhe, and thanks for opening the issue with such a great report.

As we have been talking in Slack with other users this could be the expected behavior, and it would be different from the `settings` one... shame on me, I wasn't aware of that difference for the profiles 😓 , nevertheless I cannot find good documentation about it [[1]](https://docs.conan.io/en/latest/using_packages/using_profiles.html?highlight=profiles) [[2]](https://docs.conan.io/en/latest/reference/profiles.html#profiles), and I have also doubts about the behavior of the `build_requires`.

I need to double-check this is expected (and also need to confirm what happens when using `-s` or `-o` in the command line commands), so it won't be a bug and we wouldn't be able to change its behavior, but we do need to document it better.
