### ISSUE TITLE
Collecting licenses of private dependencies

### ISSUE THREAD

**Issue by hfn92** [conan-io/conan#4868]
I hope this is the correct place to ask such questions.

I'm trying to collect licenses of 3rd party libraries used by a package according to [https://docs.conan.io/en/latest/howtos/collect_licenses.html](https://docs.conan.io/en/latest/howtos/collect_licenses.html). This only seems to work for requirements with `private=False`. The licenses of private dependencies are not copied. Which absolutely makes sense when importing shared libraries.  But how can I collect licenses of private requirements?

We could just include the licenses in the package, but then we would need to filter the build_requirements and it would increase the complexity of the recipes. Or we could just make the requirements non private...

I was hoping that there is better way to do this that I just missed.

By the way is it possible to include the version of the package when setting `folder=True`?

**Comment by memsharded** [comment]
Hi @hfn92 

>I hope this is the correct place to ask such questions.

Yes, it is perfectly fine to use issues for questions about Conan usage

Regarding private dependencies usage: if you can avoid them, please don't use them. They should be restricted to the very corner cases when you really need to have like two different versions of the same library used in the same project, but that is kind of ill-formed case. Use normal requires for everything, build-requires for tools and frameworks (catch, gtest, for example)

The issue with private dependencies is that they are private. Downstream don't see them at all, so it is impossible to collect its licenses. It is the responsibility of the package that requires them to handle that. If it needs to re-package the private dependency license, it should do it (it is totally possible to repackage, check: https://docs.conan.io/en/latest/devtools/running_packages.html#repackage)

> By the way is it possible to include the version of the package when setting folder=True?

No, it is not possible, only the package name. We could analyze it if there is a compelling use case, don't know if it would be easy or not.

**Comment by hfn92** [comment]
Thank you @memsharded It seems I may have misunderstood private dependencies. In the doc it states
[https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=private#requires](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=private#requires) 

>[...] or the linking of a static library inside a dynamic one, in which the functionality or the objects of the linked static library are not exposed through the public interface of the dynamic library.

Should we still not use private dependencies even if all dependencies are linked static (without exposing the api)? How would conan handle two shared libraries linking conflicting version of the same static lib? Or do we just need to make sure everyone uses the same version?

**Comment by danimtb** [comment]
Hi @hfn92,

The idea of private dependencies is similar to the same concept in CMake targets: the interface with that dependency is going to be  **only** used by the dependant package.

Your example is legit if you don't expose the interface of the static library in the shared ones. And in fact that is the use case the private requirements is covering.

So, the use case is fine if you know what you are doing 😆 but if you want to really get a conlfict, the private requirements will prevent that from happening as a side effect.

Hope it makes sense

**Comment by badstoms** [comment]
Hello @memsharded ,

IMHO private dependencies should be pretty much default for static libs, because I do not want to force anyone using my shared libs to have a dependency to anything already compiled into my binaries. 
So the binaries of the private dependencies shall be invisible to any client, but not the dependency info. As hfn92 stated, license conditions and other information (obligations, author info etc.) may still be legally needed for any client using my shared lib.

I would love to see that as a feature for a future conan release.

**Comment by memsharded** [comment]
> IMHO private dependencies should be pretty much default for static libs, because I do not want to force anyone using my shared libs to have a dependency to anything already compiled into my binaries.
So the binaries of the private dependencies shall be invisible to any client, but not the dependency info. As hfn92 stated, license conditions and other information (obligations, author info etc.) may still be legally needed for any client using my shared lib.

This is already implemented in the new graph model for 2.0, and released in 2.0-alphas. The main proposal doc is in https://github.com/conan-io/tribe/blob/main/design/026-requirements_traits.md

The graph will always be computed completely. Linkage (binary) requirements will not be propagated, but the dependency will not necessarily be "private" (the new trait is called "visible").

Regarding the recolection of licenses, the meta-data will be there, as is part of the recipe, but the packaged license files (if packaged), might not be there, as if by the requirement above, the package binary was skipped because it is not necessary by the consumers. It is probably the responsibility of the shared library to recollect and to package the license files of its embedded dependencies.

**Comment by badstoms** [comment]
> It is probably the responsibility of the shared library to recollect and to package the license files of its embedded dependencies.

This is my work-around for now. That´s ok, because the lib with the direct dependency to a private lib must check the conditions anyway, so the extra effort for repackaging should be ok. 
Thanks for your answer and effort to improve conan!

**Comment by memsharded** [comment]
Conan 2.0 ``deployers`` receive the full graph as a parameter, it can traverse the whole graph:
- The graph always includes all tool-requires too, so it is possible to collect them. Also "private" (``visible=False`` in Conan 2.0 traits terms)
- For binaries that might be skipped, there is a new ``conf`` that allows not skipping the binaries (it can be slower to retrieve all of them, but if we want to collect all the license files, it is indeed mandatory to retrieve all dependencies binaries files).

We can close this ticket as solved
