### ISSUE TITLE
cmake_find_package_multi should set <package>_DIR for all dependencies

### ISSUE THREAD

**Issue by kyllingstad** [conan-io/conan#4889]
I've been trying out the new `cmake_find_package_multi` generator with Conan 1.14.1 (on Windows), and it seems to me that it doesn't enable `find_package()` to actually find any packages without extra work.

#### Steps to reproduce
First, set up a conanfile that lists `some_library` as a dependency, and a `CMakeLists.txt` that contains something like:
```.cmake
include("${CMAKE_BINARY_DIR}/conanbuildinfo.cmake")
conan_basic_setup(NO_OUTPUT_DIRS)
find_package(some_library REQUIRED CONFIG)
```
Then, run:
```
conan install /path/to/source -g cmake_find_package_multi
cmake /path/to/source
```

#### Expected result
Conan creates `my_libraryConfig.cmake` in the build root, and CMake finds it when `find_package()` is called.

#### Actual result
Conan creates `my_libraryConfig.cmake` in the build root, but CMake does **not** find it when `find_package()` is called.

#### Problem
It seems that `conanbuildinfo.cmake` defines a variable named `MY_LIBRARY_ROOT` (all uppercase), but not the `my_library_ROOT` (partly lowercase) that `find_package()` uses as one of its search prefixes, nor the `my_library_DIR` variable that would specify the actual location of `my_libraryConfig.cmake`.

#### Suggested solution
For each dependency, define `<package_lowercase>_DIR` with a value of `${CMAKE_BINARY_DIR}` in `conanbuildinfo.cmake`.

(`<package_lowercase>_ROOT` would also work, but it is less direct and only works on recent CMake versions.)

**Comment by lasote** [comment]
I'm confused, the `conanbuildinfo.cmake` is generated by the `cmake` generator, and it has nothing to do with the `cmake_find_package_multi`. If the issue is CMake locating the XXXConfig files, you can use the `cmake_paths` generator and inject it, or adjust manually the `CMAKE_PREFIX_PATH` and `CMAKE_MODULE_PATH` as it is explained here: https://docs.conan.io/en/latest/reference/generators/cmake_find_package_multi.html#cmake-find-package-multi-generator-reference

Do you think is there something wrong with that approach? Thanks

**Comment by kyllingstad** [comment]
Apologies, my mistake. I wrongly believed that `conanbuildinfo.cmake` had been generated by `cmake_find_package_multi`. I'll look more closely at the reference documentation. Thanks for the quick response!

**Comment by lasote** [comment]
No problem! happy to help
