### ISSUE TITLE
Find the latest package version with a certain configuration

### ISSUE THREAD

**Issue by rweickelt** [conan-io/conan#4904]
Assume I have a package that comes in multiple variants and is stored on artifactory. Not all versions come in all variants. Unfortunately, the package does not follow SemVer properly, but uses XX.YY.ZZ.BB_suffix.

I would now like to find the latest Conan package with a certain configuration in 2 ways:

- on command line
- in a Conan recipe

Is one or the other possible?

On command line I can do ``conan search <PACKAGE_NAME> -r artifactory`` but not ``conan search <PACKAGE_NAME> -r artifactory -q myoption=BLABLA`` because the latter expects a full package reference.

In recipes I could maybe use version ranges, but since the package does not follow SemVer, version ranges don't work, do they (Conan 1.6).

**Comment by memsharded** [comment]
Yes, there is no such functionality in Conan yet. We have considered it a few times, but not implemented it, first because it would be too slow. You can check that searching the binaries is relatively slow, because the metadata for the package, like options and settings has to be recovered for all binary packages. If that was done for all the possible versions of a given package, that would probably very impractical.

> In recipes I could maybe use version ranges, but since the package does not follow SemVer, version ranges don't work, do they (Conan 1.6).

Version ranges won't work either. They first select the latest version of the recipe, then compute the binary ID needed, then look if it exist or not. They cannot traverse the whole set of binaries of all versions trying to look for a matching one, because all the recipes of all the version would need to be evaluated to get the binary ID. That would be intractable.

But the main reason could be that such approach might not be a best practice. Search for a version with a given binary leads to problems, complexities and pains. It is recommended that the set of binaries that are created for a package are consistent, it is possible to add or to remove binaries configurations, but not finding a binary for a specific version of a project should be a red flag that something is not working fine.

**Comment by rweickelt** [comment]
Thanks for your reply. Got it. So is the recommendation:
- for each version, all variants of a package should be available
- in recipes use version ranges to get the latest version
- on command line use conan search to find the latest version and conan install with the desired configuration

2 remaining questions: 
- Given a certain package version and configuration options, is it possible to calculate the package hash? I would like to do it in a recipe, but also in another script.
- Is SemVer still a requirement for version ranges to work? The package uses XX.YY.ZZ.BB_suffix.

Thanks

**Comment by rweickelt** [comment]
@memsharded, any answer to my 2 remaining questions before we can close this ticket?

**Comment by memsharded** [comment]
Hi @rweickelt, sorry for the delay, this was buried in tons of notifications.

Regarding the usage of version ranges, it is not recommended not discouraged. There are different approaches to versioning, so it depends on the project, the development flows, etc. Recently the "package revisions" feature has been introduced to be able to use automatic, internal versioning (typically the hash of the recipe), in order to be able to not change the version of the package, but instead create a new revision of the package with the same version.

Computing a package version and configuration options, you might get its information, including the package hash with the ``conan info <ref>`` command. This can be called from a script, but I am not sure if that is what you mean. There is no access from a downstream dependency to the full graph, and thus, the full package reference, including the package_id of its dependencies, because there has not been so far a use case for that. If you could elaborate what is your pain and what are you trying to achieve, that would help to understand.

> Is SemVer still a requirement for version ranges to work? The package uses XX.YY.ZZ.BB_suffix.

Yes, semver is required. This is something that Conan does not compute, but relies on an implementation of the node semver specification. I have been trying and the result is undefined if the version does not follow the standard ``major.minor.patch-prerelease+build`` pattern.

**Comment by rweickelt** [comment]
> Computing a package version and configuration options, you might get its information, including the package hash with the conan info <ref> command. This can be called from a script, but I am not sure if that is what you mean. There is no access from a downstream dependency to the full graph, and thus, the full package reference, including the package_id of its dependencies, because there has not been so far a use case for that. If you could elaborate what is your pain and what are you trying to achieve, that would help to understand.

Thanks, I think ``conan info`` does very much what I want. I don't need access to the full graph, I just needed a programmatic way to calculate a package hash based upon a package name, version and options. I need the hash to directly access some files inside a package stored on an artifactory instance.

So I am good now. Thanks.

**Comment by memsharded** [comment]
We can close this, besides the responses above, Conan 2.0 interface is even more open and extensible, it might be possible to do custom commands that look for specific binaries, the ``self.dependencies`` interface for dependencies is way more complete, the ``json`` output of commands contains more information, etc.
