### ISSUE TITLE
Move memsharded/hello repository to the conan-io organization

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#4916]
When using the ``conan new`` command, the conanfile.py created points to https://github.com/memsharded/hello and it is a bit weird to use an example out of the organization.

We should move it to a isolated repo in the conan-io org and give it a better name, like: hello-cpp-lib-example

After that, the ``conan new`` command should be updated to use the new repo

**Comment by lasote** [comment]
@memsharded please, give us feedback about this.

**Comment by danimtb** [comment]
I would like to have this done as @jgsogo pointed out in https://github.com/conan-io/docs/pull/1262#discussion_r279651179

Do you agree on transferring the repo to the conan-io organization?

**Comment by danimtb** [comment]
I think having a "conan-hello" repo in conan-community and the binaries uploaded to Conan Center will be helpful for the examples in the documentation too

**Comment by memsharded** [comment]
Yes, I totally agree.

Probably it deserves a bit of clean-up, because it might have some weird patterns, like the "static_shared" branch, etc. The only problem is the moment I transfer it, it will be broken in develop. I suggest a completely new repo, deprecate mine (older versions of the doc would still use mine!)

**Comment by danimtb** [comment]
Ok, I will create a new repo with the static_shared contents in the master branch and we will keep your repo too for old references
