### ISSUE TITLE
Overriding the version in conanfile.py when putting a package into editable mode

### ISSUE THREAD

**Issue by KristianJerpetjon** [conan-io/conan#4968]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version >=1.13.1
When putting a package into editable mode we have to specify the version which is fine. However the version in [conanfile.py](https://github.com/includeos/IncludeOS/blob/dev/conanfile.py#L11 ) doesn't match. 

This caused us to do the following workaround:
` conan editable add . includeos/$(conan inspect -a version . | cut -d " " -f 2)@includeos/latest --layout=etc/layout.txt`

However this results in a different issue. 
When we want to get some new tooling or a newer dependency downloaded,  The developers use conan install with -u to get the latest. which in effect will download a newer version of the package in editable sometimes.

Having thought about these two issues and still wanting to use "semver" to resolve "dependencies" we came up with the following.. By setting the editable to a high enough version. Problem 2 will never happen. however problem 1 is the root cause of this. 

So the idea we had was what if we could add -f or --force when doing 
conan editable add to ignore the version in conanfile.py ?

'conan editable add mypackage/forcedversion@user/channel --force`
(warning version x.y.z in conanfile.py is ignored)

**Comment by KristianJerpetjon** [comment]
A second alternative althoug more complex would be to make the -u ignore updtated packages in local editable mode but we think that can cause a lot of "other" issues

**Comment by memsharded** [comment]
When we analyze this issue, it seems that we should check the workspaces too, because updates over workspaces would produce the same issue, and packages in the workspace would start pointing to updated caches with newer versions instead of the workspace package.

**Comment by jgsogo** [comment]
Hi, @KristianJerpetjon. Probably this use case is what _workspaces_ were being created for, although right now they will behave the same and won't solve your pain.

Your use case can be solved using an alias to the version you have in _editable mode_, an alias with a big version so any version_range will resolve to it. Instead of trying to force a version for the installed editable, you can create an alias to the editable reference:

```bash
conan editable add . includeos/<the-version>@includeos/latest
conan alias includeos/999999@includeos/latest includeos/<the-version>@includeos/latest
```

With this, any package using a version range like `includeos/[>0.0.0]@includeos/latest` will resolve to the alias which in turn will resolve to the package in editable mode.

[Here](https://github.com/jgsogo/conan/blob/32a58a24041a89c3d9f905238dc38412200aeadc/conans/test/integration/editable_package_test.py) I've written a test showing the effect of this _workaround_. Maybe it could work for you until we address this in workspaces (I think that is the way to go instead of forcing a version when putting the package into editable).

Could the _alias_ serve as a workaround?

**Comment by dvirtz** [comment]
setting the editable package to a high version does not work for me. looking at  the code in https://github.com/conan-io/conan/blob/a0d81b3fa18d57af2eda82203c78c79e09570c7a/conans/client/graph/range_resolver.py#L121-L125 I don't understand how it could work, as local cache is not considered if any valid version is found remotely.

**Comment by memsharded** [comment]
Workspaces are been introduced back in Conan 2.10: https://docs.conan.io/2/incubating.html

The new ``conanws.py`` allows logic to dynamically set the version of editable  packages in the workspace. I am closing this ticket as solved, but please create new tickets for any further question or issue. Thanks very much for the feedback!
