### ISSUE TITLE
How to pass argument to conan install?

### ISSUE THREAD

**Issue by tusharecmc** [conan-io/conan#4992]
there I have a package which is copying files into the root directory and for that I need root access. On doing conan install it is asking for a password. I don't want any user to put that password manually or to wait for that password option to pop up. Is there any way to pass password as argument when doing conan install.

**Comment by Johnnyxy** [comment]
hi there,
without looking into the issue if there could be another "golden" solution, you could use [options](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#options) for that.

```python
class Recipe(Conanfile):
    ...
    options = {"username": None, "password": None}
    ...
```

How do you initiate the copy procedure? To my knowledge with ```conan install``` alone you cannot (should not) do a copy of files by yourself except when you are building a package.
For a available package (built recipe) ```conan install``` executes no recipe functions where you should do any copying ([see](https://docs.conan.io/en/latest/reference/commands/consumer/install.html#conan-install)). 
- config_options()
- configure()
- requirements()
- package_id()
- package_info()

Except if you are ```deploying``` a package. Then you could do it with the ```options``` approach and use the ```def deploy(self)``` function.
- deploy()

**Comment by memsharded** [comment]
There is one issue with ``options`` is that they affect the binary, so changing an option will create a different binary by default, which is probably not intended with a password field. It would be better to use environment variables and python ``os.getenv()`` functionality to inject it into the relevant part of the recipe


@tusharecmc 

> there I have a package which is copying files into the root directory and for that I need root access. 

Could you clarify what part of your conanfile.py recipe is doing that? source() method, build() method? How would you inject the password to that specific part of the recipe to use it?

**Comment by Johnnyxy** [comment]
@memsharded  It depends. If one uses the ```def package_id``` function and deletes the options it will not influence the id. I would argue that the options approach would be more clear to the recipe user what it needs.
But yes with environment variables one could do the same.

```python
    def package_id(self):
        del self.info.options.username
        del self.info.options.password
```

**Comment by memsharded** [comment]
@memsharded yes, that is doable, but still probably not the most recommended thing, because conceptually they are designed for other purpose, and it might be weird that:

- The options are propagated, that means that some other packages downstream or upstream might be able to read the user and password. Some package might decide to dump all the options values for debugging purposes and suddenly you end with the password in clear text in the logs.
- Options value can be stored in other files, check for example the "graph_info.json" generated after install. Storing options will be done more when graph locks are released, as input options are necessary for reproducible builds. You don't want that password in some text files around.

So, the general advice would be to use options for public "model" things that explicitly affect the binary, like some build configuration (static/shared), etc. The non-modeled configuration, inputs, etc. we recommend to use env-vars.

**Comment by memsharded** [comment]
The solution for this question is to use env-vars. 
Furthermore Conan 1.39 provides a new mechanism to pass information from conan to conan recipes, the ``[conf]``, or command line argument. Probably the env-var is the most standard way to pass credentials, most tools use that approach.

I think this question was answered with a viable solution, so it can be closed, but please tell otherwise. Thanks!
