### ISSUE TITLE
Exporting same version does not change files in package dir

### ISSUE THREAD

**Issue by Phibedy** [conan-io/conan#500]
Hi,
I am not sure if this has already been but I can't find it anywhere.
Example on one computer:
- write some code
- export foo/1.0@bar/foba
- upload foo/1.0@bar/foba
- conan install foo/1.0@bar/foba --build foo (only src, no binaries)
- write some code
- export foo/1.0@bar/foba
- upload foo/1.0@bar/foba
- conan install foo/1.0@bar/foba -u

The package files do not change calling the second time `conan install <..> -u`. In addition it should complain as the new package has to be compiled. Deleting the directory  `.conan/data/foo` and installing the package works.
Maybe a hash could be stored in the package and in the export directory. If they don't match it could be detected that they are out of sync. I think that atm conan only checks if the remotes and the export directory  are synced (and they are so conan does not detect the change), but if the package is exported and used on the same machine, the package dir never gets updated.

Maybe I am doing something wrong, the conan file I used for this test: https://github.com/lms-org/lms/blob/develop/conanfile.py

**Comment by lasote** [comment]
Hi @Phibedy ,

This behavior is intended.  We don't want to invalidate all the packages if the recipe has any change.
This change could not affect to the packages (could be just add the license field), so we prefer to let the package creator delete them first or use `--build` when they want to regenerate them.

I usually generate the packages using the `test_package` feature, that will force the export + the install with --build, so my packages are always build. 

In your case, for the last `conan install foo/1.0@bar/foba -u` I would add the `--build` option to guarantee that the package is rebuilt.

**Comment by Phibedy** [comment]
I will have a look at ```test_packag```, thank you.
Does ```--build=missing``` rebuild the package, too?

**Comment by lasote** [comment]
`--build=missing` won't rebuild the package because the package already exists. (You created when you invoked install with ` --build foo`)

You can force build with `--build foo` or `--build`

**Comment by memsharded** [comment]
Hi @Phibedy , any further feedback with this issue? I think it was not a real bug/problem, but a clarification of the workflow design for package creators. It is is ok, then this issue might be closed.

Thanks for your help!

**Comment by Phibedy** [comment]
Oh sorry missed to answer it,
I wonder what happens if I use ```--upgrade --build=missing``` at some other remote, is it rebuild?

**Comment by memsharded** [comment]
No, it is not rebuilt. The flow is as follows:

1. Starting with the installed reference (``MyPackage/0.1@user/channel``) or ``conanfile``, the dependency tree is evaluated and built incrementally. For that purpose, it is necessary to retrieve the dependencies recipes (the conanfile.py of the dependencies, not the binaries).
2. For each node in the dependency tree, starting upstream (the packages that do not depend on anyone else, it is check for existence of a binary for that dependency that matches the current settings.
3. If such a binary is found in the local cache, it is used
4. If the ``-update`` argument is used, such local binary will be checked against the remote one, and if there is a remote binary newer than the local one, it will be retrieved and replace the old one. Note that this only happens when the same package reference ``MyPackage/0.1@user/channel`` is used, i.e., it does not upgrade to ``0.2`` or newer versions of the library, but only for newer builds of the same package.
5. If there is no binary, and ``--build=missing``, then it will build locally the package from sources

The remotes are search in order as defined in the remote list (``$ conan remote list``), or in the remote explicitly specified. If a package was retrieved from one remote, ``--update`` updates will look that specific remote by default, unless remote explicitly especified.

If we used ``--build`` or ``--build=MyPackage`` then it will always build from sources, it will not try to retrieve binaries from the remotes.

**Comment by Phibedy** [comment]
Thank you, didn't know that ```--update``` invokes the build and ```build=missing``` just allows the build from source.

**Comment by memsharded** [comment]
No, ``--update`` does not invoke the build, it just checks the existing precompiled binary against the remote precompiled binary, and updates the local one by removing it and retrieving the remote one. Sorry for the misunderstanding.

The build from source is invoked if:
- The ``--build`` argument is used (will build all dependencies)
- The ``--build=MyPackage``  is used (will build only MyPackage dependency, the rest have to exist a precompiled binary). This is the default used by ``conan test_package``
- The `` --build=missing`` will build from sources only those packages which it cannot find a precompiled binary, either local or in remotes

In any other case, conan will not try to build from sources.

**Comment by Phibedy** [comment]
Yes but for an src-only package, ```conan install <...>--update --build=missing```causes the packages to be rebuild if the same version was uploaded again by someone else, doesn't it? What happens to the binary check if there are no binaries?

**Comment by memsharded** [comment]
Actually it doesn't by default. For src-only packages, the ``build_policy=always`` is recommended, if the package creator intends to overwrite those package recipes, so they are always re-build at install time.

**Comment by Phibedy** [comment]
Ah ok, I seem to missunderstood some question related to #15. I have large source-only projects so compiling all modules every time isn't a good choice. (they have to be compiled on a small arm gpu).
As you said "by default", is there a way to already achieve it?

It could be solved by some function like 
```
conan checkRecipes(package):
    return <all out of sync packages used in package and itself if out of sync>
```
To recompile src-only packages
```
conan install <package> --update
conan install <package> --build=`conan checkRecipes <package>`
```
Conan would at first update all binary packages, afterwards only src-only packages are out of sync. Now we build them.

**Comment by memsharded** [comment]
Ok, I think now I understood the issue. 

The underlying design decision was made because we realized that sometimes, a package was built, but there was something missing in the ``package_info`` that doesnt require a full package rebuild (imagine boost, long times), so it is enough to change the recipe and export the recipe and it works. We let the package creators be responsible for that, and let them ``conan remove`` the binaries if they wanted to regenerate it.

Certainly, some information about the package binaries could help. Will have a look, thanks for your feedback!

**Comment by memsharded** [comment]
I think that this issue has been addressed by PR https://github.com/conan-io/conan/pull/611, with the ``--outdated`` option, and the tracking of the package recipe hash from the binaries (also reported as outdated in ``conan info``). It has already been merged to develop, so this functionality will be released in next 0.15. Do you think @Phibedy that such functionality addresses your issue? Thanks very much for your feedback.

**Comment by memsharded** [comment]
Hi @Phibedy , this functionality was released in 0.15, have you had the chance to try it? Do you think it solves your issue? Please have a look when possible.

**Comment by Phibedy** [comment]
Yes it does :+1: 
One thing I noticed is, that if I call:
```
conan export foo/bar
conan upload <foo/bar>
conan install <foo/bar> --build=outdated
```
it is not re-build. I don't think that this should be fixed as I installed it manually. I really should start using test_package and set up a build server :)

**Comment by memsharded** [comment]
If the export has actually changed the package recipe or associated exported files, then the ``--outdated`` should re-build it, if not, seems it could be a bug. Can you please paste here more detailed output of such commands sequence?

**Comment by Phibedy** [comment]
Hmm now it works like expected. Unluckily I can't reproduce it. Maybe it was because the server was running on a much older version then the client... . (It happened some time ago).
I think it was my fault, if it happens again I will write a bug report.
Thank you for support :)

**Comment by memsharded** [comment]
Thanks to you for your feedback! :)

So I think this issue could be closed now, if something new fails, just re-open it, or open a new issue more specific to the new error.
