### ISSUE TITLE
[conan config] Install hook requirements

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#5002]
To help us debug your issue please explain:

Hi!

As some hooks could require extra python packages, I think it would be nice when installing hooks, Conan could install their requirements too.

However, this feature is not easy I think, as Conan will need to call pip and install some packages. Is it possible to implement this?

Or, we could move this problem to hooks and put requirements.txt there, where the user will be able to install.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
It shouldn't be very difficult, but my concern is if Conan should do it, as it can be very problematic, might break users installed packages trying to install incompatible dependencies, etc. To be discussed

**Comment by lasote** [comment]
Are we talking about regular python packages?

**Comment by memsharded** [comment]
Yes, I have landed here while thinking about the recent astroid->typed-ast breakage in python 3.4. It happens that these problematic dependencies are used exclusively for the recipe linter, which could be very easily converted to a hook (and it will be for sure the latest in Conan 2.0, I'd prefer if could be done earlier). But installing it as a hook itself, without installing its dependencies (astroid) will cause weird exceptions of some missing not installed packages. 

So I understand the case of some automatic installation of a "requirements.txt" file that came with the hooks. Surely not a default, but maybe:
- Installing hooks that come with a requirements.txt will warn and prompt the user: "this hook needs this pip package to operate, do you want to install it? (y/n)"
- A ``--confirm``, ``--pip-requirements=auto`` or equivalent argument could be defined to opt-in to install those requirements without asking. Maybe a ``conan.conf`` configuration too.

What do you think @lasote

**Comment by lasote** [comment]
The same as my "beloved" system requirements, I don't think we should try to install anything. You don't know if Conan is installed in a virtualenv, if it requires root for global installation and so on, and we shouldn't try to play that game.

We could try to capture import errors and, if the requirements.txt file is present, fail and suggest the command to install it. 
Or maybe also at `conan config install` stage, but only saying: "This hook declares a requirements.txt file, make sure to install the dependencies in order to use it: `pip install -r path/to/requirements.txt`.

For a company, if they want to provide a complex hook requiring dependencies, the same they (IT department) provide conan, they should provide the rest of deps.

For the Conan linter, we can choose several options:

- Opt-in the linter (and of course it will require by the same mechanism to install manually the deps)
- Deactivate the linter if the deps are not there and print the warning.
- Opt-out the linter, failing by default (I don't like this, obviously)

**Comment by memsharded** [comment]
This is not planned at the moment. Conan will not try to install potential pip requirements of hooks, too problematic. If users want to have hooks that depend on pip packages, they should provide them in their python environments.
