### ISSUE TITLE
Add dependencies section inside Txt generator

### ISSUE THREAD

**Issue by holybrake** [conan-io/conan#5010]
Currently conanbuildinfo.txt doesn't provide the information about the dependencies of each package.
Please add sections like [pkgname_depends]

**Comment by memsharded** [comment]
Hi @holybrake 

This probably doesn't make sense. Conan is getting that information in the ``graph_info.json`` file, that would be in the form of a graph, because actually, there might be different versions upstream. The txt generator, and in general all generators are dedicated to "compiler information" like include dirs, lib dirs and library names. The dependencies information belongs somewhere else. In any case this information should be added to most generators for consistency, not to the txt generator only.

Please @lasote feedback, maybe we need to discuss.

**Comment by lasote** [comment]
@holybrake What is your use case?

**Comment by holybrake** [comment]
@lasote We need to parse the txt file directly by CMake to obtain all the needed information.
Conan's CMake generators provide this information, but we are not using them for few reasons

**Comment by memsharded** [comment]
@holybrake wouldn't you prefer to write your own generator that puts the information you want in the way you want? Like even cmake variables. That would save you a ton of work of parsing files in CMake code.

**Comment by holybrake** [comment]
@memsharded basically I have done this. But it is confusing why txt generator that should provide all the needed info lacks any dependencies information. I'm sure that Conan should provide it out-of-the-box

**Comment by memsharded** [comment]
Hi @holybrake 

I have checked the generators code. The generators don't have access to the dependency graph, only to the ``deps_cpp_info`` information. That means they cannot know the dependencies of the transitive dependencies, and all it could list would be the dependencies of the currently installed package/recipe.

I see that the ``cmake`` generator does exactly this, it contains just one variable ``CONAN_DEPENDENCIES`` with the list of all the dependencies that appear in the ``conanbuildinfo.cmake`` file. But not the dependencies for each one of the packages in the dependency graph. Furthermore, it only outputs the names of those dependencies, but not their versions. Changing that would be very challenging, because the interface to the generators don't receive the full dependency graph, just the consumer conanfile information, and changing that interface sounds complicated.

Would that be enough for your use case? Please tell, in that case we might be able to add it, to keep it consistent with the cmake generator.

**Comment by holybrake** [comment]
Hi @memsharded 
Currently, we are using the following custom generator for dependencies:
`class DepsTxt(Generator):
    @property
    def filename(self):
        return "depsinfo.txt"

    @property
    def content(self):
        print("starting")
        sections = []
        for name, info in self.conanfile.deps_cpp_info.dependencies:
            sections.append(
                "[depends_{}]\n{}".format(name, "\n".join(info.public_deps)))
        return "\n".join(sections)
`
The created dependecies information is consistent with  `cmake` generator and is enough for our case.
Please don't forget about the dependencies between CMake  targets, that are correctly created by `cmake` generator, see `generate_targets_section` function

**Comment by memsharded** [comment]
txt generator removed in 2.0, closing as outdated
