### ISSUE TITLE
Loop detection does not take user or channel into account.

### ISSUE THREAD

**Issue by StefanSchulz-Tesyo** [conan-io/conan#5018]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

conan version: 1.13.3, 1.14.3, It works correctly in 1.12.3

**Current behavior**

Assume that package 'PkgA/1.0@U2/C2' has the package 'PkgA/1.0@U1/C1' as a build requirement. Building the package results in the following error:
`ERROR: Loop detected: 'PkgA/1.0@U2/C2' requires 'PkgA/1.0@U1/C1' which is an ancestor too`

**Expected behavior**

No error message and the package simply builds. Different users/channels should be treated as different packages, see #3799 for the original feature request. It was accepted, implemented and works correctly up to version 1.12.3. 

**Steps to reproduce**

Here is a minimal conanfile to illustrate the problem:
```
from conans import ConanFile

class PkgA(ConanFile):
    name = "PkgA"
    version = "1.0"
    
    def build_requirements(self):
        if self.user != "U1" or self.channel != "C1":
            self.build_requires("PkgA/1.0@U1/C1")
```
Save it as`conanfile.py`. Then execute the following two commands:
```
conan create . PkgA/1.0@U1/C1
conan create . PkgA/1.0@U2/C2
```

**Comment by memsharded** [comment]
Hi @StefanSchulz-Tesyo 

I am afraid this is by design, I am not sure this could be disabled. In the conan dependency resolution packages are mostly addressed by name, like ``self.deps_cpp_info["MyPkg"]``, or how a dependency can be overriden from downstream by another one with a new version, user and channel.

In the past it might have worked by luck, because when 2 packages are in the same graph with the same name, the resolved include_dirs, lib_dirs, bin_dirs.... were being non-deterministically overwritten, inducing many subtle but bad and difficult to debug bugs. Latest changes in the graph fixed those bugs, and introduced a few more checks to make sure loops can't be formed.

Different user/channels are indeed different packages, but also different versions are different packages. The only way to know that lib/0.1->lib/0.2->lib/0.3->lib/0.1 is a loop that will infinitely (until stack crashes) recurse, is to restrict a package name to depends on another package with the same name.

Could you please describe a bit better what is your use case? Why do you need a package be a build-require of itself, are you doing some kind of bootstrapping? Why not using a different name for the "build_require"?

**Comment by StefanSchulz-Tesyo** [comment]
Thank you for the quick response. I can see your point there, especially with things like `self.deps_cpp_info["MyPkg"]`. I believe all our cases can be rewritten to use different names for the packages. Use cases include repackaging of third-party packages and creating separate source / binary packages (the binary package requires the source package).

I still find the design a little bit confusing. Especially an attribute like 'user' sounds like you could combine packages from different users into one package, even though they happen to have the same name.
