### ISSUE TITLE
[Question] passing installation directory to installed dependency

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#5024]
I am Conanizing a large legacy project (let's call it "platform") which already used a type of home-grown shared static library collection (let's call it "groups").  Jumping directly to full conan-style build against Conan's local cache proved too difficult, so for now I've created a `conan-groups` package that declares all required headers and libraries and whose `deploy()` method uses `copy_deps` to copy files into the specific directory structure required by the existing `platform` build.

My `conan-platform` project depends on `conan-groups`.  The existing platform build depends on an environment variable `SHARED_LIB` to decide where it should assume the `groups` directories are  so I have tried setting this in my `conan-groups`  using:

```
    def package_info(self):
        self.env_info.SHARED_LIB = self._SHARED_LIB
```

where the attribute:

```
    _SHARED_LIB = generateDeployDirectory(_rootDeployDirectory)
```

is set using a method that generates a new tmp install directory for the install:

```
def generateDeployDirectory(rootDeployDirectory):
    now = datetime.datetime.now()
    buildNumber = '{:04d}{:02d}{:02d}{:02d}{:02d}{:02d}'.format(now.year, now.month, now.day, now.hour, now.minute, now.second)
    userName = getpass.getuser()
    deployDirectory = "{}\\{}\\{}".format(rootDeployDirectory,userName,buildNumber)
    print ("generateDeployDirectory returning {}".format(deployDirectory))
    return deployDirectory
```

This almost works, in the sense that at least the `conan-platform` sees that SHARED_LIB environment variable.

However it's a bit broken, in that the generated buildNumber at `conan-platform` build time ends up being different to the one generated the first time the package was installed (which may have been earlier).

So e.g. my `conan-platform` build fails with:

```
"E:\TempConanLibraries\mmaguir1\20190424082601\nxgroups\unstable\lib\v140_xp\Debug_dynamic_64\BDE.props" 
```

because the `conan-groups` install was performed to:

```
E:\TempConanLibraries\mmaguir1\20190423103524\nxgroups\unstable\lib\v140_xp\Debug_dynamic_64
```

I think I thought `deploy()` would get called each time installation of the `conan-nxgroups` package was checked in the `conan-platform` project, but clearly there's some caching going on that results in this being a no-op on subsequent `conan create` calls for `conan-platform`.

Additionally, I'd like for my `conan-platform` build to be able to instruct my `conan-groups` package which rootDeployDirectory it should use to perform its install.

Is there a feature or pattern or here I should be following?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Windows 2012 Conan version 1.10.1

**Comment by jgsogo** [comment]
Hi, @michaelmaguire!

I think we can try to give you some ideas to workaround your issues, but it could require some hacking around Conan.

I think that it would be easier to achieve what you are trying to if you create the _custom deploy_ of your `conan-group` package from the `conan-platform` one, so it will be executed and generated each time you use the platform. I can think about different approaches:
 1. use the `imports()` function in the `conan-platform`, probably it won't be flexible enough
 2. write your custom generator (here you can find a proof of concept: https://github.com/conan-io/conan/pull/4972), it will be invoked from a `conan install <your/conan-platform> -g deploy_groups` and you can run code, copy files, create new files with useful variables,...
 3. create the deploy during the `build()` method of the `conan-platform`... this one could be the most tricky approach, but here you could do the same as in a custom generator: copy files to your deployment layout and use it for your build.

The best one would be approach (2) I think, but as you also need _"Additionally, I'd like for my conan-platform build to be able to instruct my conan-groups package which rootDeployDirectory it should use to perform its install."_ I think that you can only use (3) because you need that code to be executed with some information that only the `conan-platform` package knows about...

**Comment by michaelmaguire** [comment]
@lasote A relevant, related question, which I think explains the 'caching' I thought I was seeing above: 

I note from the deploy() method documentation:

> The deploy() method is designed to work on a package that is installed directly from its reference ... All other packages and dependencies, even transitive dependencies of “Pkg/0.1@user/testing” will not be deployed, it is the responsibility of the installed package to deploy what it needs from its dependencies.

https://docs.conan.io/en/latest/reference/conanfile/methods.html#deploy


Can I manually invoke the deploy(self) method in a the conanfile of the `groups` package I depend on from the build(self) methods of my conan-platform conanfile?

**Comment by lasote** [comment]
No, the `deploy` method of a dependency cannot be called within the conanfile.py

**Comment by memsharded** [comment]
Closing as outdated
