### ISSUE TITLE
Loop detection does not take version into account

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#5030]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version: 1.14.3
OS: Win10

The loop detection does not take the version into account (https://github.com/conan-io/conan/blob/9f1c4dfbf4c9897c34bc903cb62643a56b67fee9/conans/client/graph/graph_builder.py#L134) .

**It should be possible to use the own package name in a different version as a build requirement.**

In concrete, I want to build CMake using an older version of CMake.
Many things work like this  (e.g. also gcc is built using gcc).

(Similar ticket related to loop detection: https://github.com/conan-io/conan/issues/5018)

**Comment by jgsogo** [comment]
At this moment the answer is the same as #5018, it is by design, it creates a loop and it is not allowed. You need to assign a different name to the package in order to break the loop.

I'm not sure (and this is just my opinion) if, in a new version of the graph model, we could have the concept of `tool` to avoid breaking in these kinds of scenarios, it could make sense, the `tool` would have its own graph... this is something I have in mind, but there are other things with higher priority. 👷

**Comment by jgsogo** [comment]
Hi, @ghost! I'm already implementing the new cross building model (https://github.com/conan-io/conan/pull/5202), there are a lot of things to do yet, but some basic behavior is already available. Given the new implementation, there will be two different contexts (`host` and `build`) and those contexts are taken into account to identify the nodes in the graph, so in your use case it will be different the node in the `host` context (the `CMake` you are actually building) and the one in the `build` context (the `CMake` you are using to bootstrap).

It will take its time, but we are walking in the right direction, I think. 👟
