### ISSUE TITLE
Why doesn't conan build have a --profile option?

### ISSUE THREAD

**Issue by Jochen0x90h** [conan-io/conan#5037]
Hi!

I wonder why conan build doesn't have a --profile parameter (conan version 1.14.3). If I do something like

`conan build . --build-folder build-debug --profile Debug`

I get conan build: error: unrecognized arguments: --profile Debug
My current solution is calling build() inside package() and then using conan export-pkg which has the --profile parameter.

**Comment by Johnnyxy** [comment]
hi there,
the usual conan workflow is to issue a ```conan install``` first and provide the desired profile as command argument there. After that ```conan build``` uses the informations stored in the generated files (with settings retrieved from the profile) in the ```install-folder``` to build.

```conan build``` should be used only for development and should be replaced by ```conan create``` later ([see here](https://docs.conan.io/en/latest/reference/commands/creator/create.html#conan-create))

While using ```conan create``` be aware of a bug so that the behaviour of ```conan install, build, ...``` differs from ```conan create``` (https://github.com/conan-io/conan/issues/4784).

**Comment by memsharded** [comment]
Hi @Jochen0x90h 

The idea is that you install your requirement once, for one configuration, and then you can later build as many times as you want, with that configuration, without needing to install the dependencies again. Also, it is not possible to build for different configuration to the one that was used to install the dependencies, because binary incompatibilities.

So, ``conan install`` is the one that has configuration. That configuration will be captured, and ``conan build`` will use it later, without specifying it.

> My current solution is calling build() inside package() and then using conan export-pkg which has the --profile parameter.

You don't need to do that, just call ``conan install`` before calling ``conan build``. Even if you don't have dependencies, the "local flow" of using ``conan build`` should always have a ``conan install`` first.

**Comment by memsharded** [comment]
This has already been changed in "develop" branch, for Conan 2.0.

``conan build`` command will be a full installation, and as such will accept all settings, options, and profile arguments.

The local build, with the new toolchains like CMakeToolchain, etc (already available as experimental in 1.39), already achieves the exactly same build in the cache and in the user folder.


So I think this issue can be closed as fixed, to be released in 2.0. Thanks!
