### ISSUE TITLE
Can conan remove also requirement packages?

### ISSUE THREAD

**Issue by kahema** [conan-io/conan#5061]
Hi,
Is it possible to uninstall also packages that are installed as a 'requires'? For example if I call:
conan install script/6.6.0@my/final it will install the package + all requirements packages. But if I call
conan remove script/6.6.0@my/final it will remove only the specified package and all requirement packages are still installed.

**Comment by memsharded** [comment]
Hi @kahema 

No it is not possible, because the transitive dependencies can also be dependencies of other packages, and removing them would make the other packages needing to re-install or even re-build them, which would be very time consuming. Also, it would need to evaluate all possible binary configurations to see what are the real dependencies, because the dependency graph can be different with each different configuration (profile, settings, options), and that would make it very, very slow, or almost intractable.

If you are not concerned about needing to reinstall packages, you can always do a ``conan remove "*" -f`` to completely clean the cache.

**Comment by memsharded** [comment]
This is finally possible in Conan 2.0 with ``package lists`` feature: https://blog.conan.io/2023/06/28/Conan-bulk-package-operations.html
