### ISSUE TITLE
Conan Create (scm) copy source removing folder symlink

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#5080]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

```
Conan version 1.14.3
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

Hi there,
It appears when running `conan create` locally or remotely, folder symlinks are removed when source is copied to the build folder. This is not true for file symlinks. We are using the `scm` feature.

After running `conan create` and going to the build directory:
```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    Libs/prebuilt/Debug
```

```
lrwxrwxrwx  1 mh70023 bluetooth    8 Feb 21 14:14 Debug -> Release/
```

All other file symlinks are working as intended and are not deleted.
I have checked my .gitignore as well for errors.

**Comment by lasote** [comment]
I confirmed the bug and detected another one related. The common issue is that the `merge_directories` at the `source.py` is not managing correctly the linked folders. Here is a POC adding a test and modifying it to make it work, but I think we should consider use the `FileCopier` instead of the code at `merge_directories`. https://github.com/lasote/conan/pull/new/poc/folder_symlinks_copied
