### ISSUE TITLE
How do I use conan to just download packages and then get paths to headers and libraries?

### ISSUE THREAD

**Issue by jeking3** [conan-io/conan#5095]
Let's assume I am interested in using conan purely as a delivery vehicle for a large set of dependent libraries (like boost), with the goal to allow each of these libraries to release on their own schedule by using intelligent versioning rules (like pip).  Nevermind that bincrafters already has boost packages; I'm thinking about what happens after that.  I'm also thinking about how I would propose using conan as a means to finally break up the monolithic distribution model of boost.

The requirements for this would be:

1. A simple command must exist to download a package.  This exists today.  If I install conan and then run "~/.local/bin/conan install boost_uuid/1.69.0@bincrafters/stable" I get a LOT of packages.  All the direct and transitive dependencies are downloaded, and they also appear to be built when needed.  (ignoring how to control those builds and their options for now)

This would mean all the boost repositories would have to have conan files that allow for packages to be made.

Note:  Some dependencies are mandatory and others are optional.  For example from boost::uuid, serialization is optional.  It's more like another target that has its own header and that header depends on boost::serialization.  But we can brainstorm that later.

2. Lots of files get dropped into ~/.conan (why not ~/.cache/conan?  That would be more standard for linux)

3. Given I am not interested in using conan as a build system for the things consuming these downloaded modules (and in fact, have no control over how consuming systems actually consume these downloaded modules), how do I get a list of include paths and libraries that I need to add to a typical build command on different platforms?  The paths are rather complex, i.e.:

boost@7ef0dac58405:/tmp$ find ~ -name '*uuid*' -print
/home/boost/.conan/data/boost_uuid
/home/boost/.conan/data/boost_uuid/1.69.0/bincrafters/stable/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/uuid
/home/boost/.conan/data/boost_uuid/1.69.0/bincrafters/stable/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/uuid/include/boost/uuid
/home/boost/.conan/data/boost_uuid/1.69.0/bincrafters/stable/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/uuid/include/boost/uuid/detail/uuid_generic.ipp

(note: These long paths may screw up some windows systems which have path length limits.)

Can I ask conan on the command line for a list of "-I" and "-L" and "-l" data for gcc/clang, and the equivalent for Windows that would allow me to link something that uses what I installed with conan?  If I could do that, then integration with external build systems would be fairly easy since they can all run external commands and capture the output.  I just haven't seen a way to do that with conan yet.  Is there a way?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi @jeking3 

There are multiple questions, comments and suggestions in this issue, sometimes it is much better to write dedicated, very focused small issues, clarifying if they are suggestions, questions, bug reports, etc.

I'll try to answer some of the above:

> Lots of files get dropped into ~/.conan (why not ~/.cache/conan? That would be more standard for linux)

The conan "cache" contains not only the cache of installed packages, but also user configuration: custom settings, defined remotes, the user conan.conf, hooks, profiles.... The ``.cache`` in linux could be removed without destroying user data which is not the case. You might use ``conan.conf`` ``storage`` configuration variable to put the ``data`` folder containing the cached packages in another path rather than ``~/.conan/data``.

> Given I am not interested in using conan as a build system for the things consuming these downloaded modules (and in fact, have no control over how consuming systems actually consume these downloaded modules), how do I get a list of include paths and libraries that I need to add to a typical build command on different platforms?

This is what generators do. Try:

```bash
$ conan install Poco/1.9.0@pocoproject/stable -g cmake -g txt -g compiler_args
...
...
Generator compiler_args created conanbuildinfo.args
Generator txt created conanbuildinfo.txt
Generator cmake created conanbuildinfo.cmake
```
Three files will be generated, one for cmake, other as text and the other for command line compiler invocation. If you inspect them, for example, the later:

```
-DPOCO_STATIC=ON -DPOCO_NO_AUTOMATIC_LIBS -IC:\Users\memsharded\.conan\data\Poco\1.9.0\pocoproject\stable\package\09378ed7f51185386e9f04b212b79fe2d12d005c\include -IC:\Users\memsharded\.conan\data\OpenSSL\1.0.2o\conan\stable\package\606fdb601e335c2001bdf31d478826b644747077\include -IC:\Users\memsharded\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\include -O2 -Ob2 -DNDEBUG -MD -link -LIBPATH:C:\Users\memsharded\.conan\data\Poco\1.9.0\pocoproject\stable\package\09378ed7f51185386e9f04b212b79fe2d12d005c\lib -LIBPATH:C:\Users\memsharded\.conan\data\OpenSSL\1.0.2o\conan\stable\package\606fdb601e335c2001bdf31d478826b644747077\lib -LIBPATH:C:\Users\memsharded\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib PocoMongoDBmd.lib PocoNetmd.lib PocoNetSSLWinmd.lib PocoCryptomd.lib PocoDatamd.lib PocoDataSQLitemd.lib PocoZipmd.lib PocoUtilmd.lib PocoXMLmd.lib PocoJSONmd.lib PocoFoundationmd.lib Iphlpapi.lib Crypt32.lib ssleay32.lib libeay32.lib crypt32.lib msi.lib ws2_32.lib zlib.lib
```

Something similar for cmake and the text format (ini like). These generators are intended for integration in the respective build systems (there are generators for other build systems as MSbuild for Visual Studio), but if you want a different, customized output for any other build system, you can write your own: https://docs.conan.io/en/latest/howtos/custom_generators.html#dyn-generators

I would also suggest to follow the getting started (https://docs.conan.io/en/latest/getting_started.html), there, the ``cmake`` generator is used in an example.

Please tell me if this clarifies your doubts. Thanks.

**Comment by jeking3** [comment]
Looks good, I will close this given it looks like the mechanism is there already.  Thanks!

**Comment by memsharded** [comment]
Great. Do not hesitate to open new issues for further questions (better small and focused, as suggested above). Cheers!
