### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#51]

**Comment by skizzay** [comment]
:+1:

**Comment by malikkirchner** [comment]
+1

**Comment by rsvargas** [comment]
+1

**Comment by Kendos-Kenlen** [comment]
+1

**Comment by memsharded** [comment]
Hi everybody!

Python 3 support has already been released in latest 0.9. We kept this issue open, because its support is still "experimental", but it is already tested in travis-CI with python 3, and some users are already using it under python3, and reported issues and fixed a couple of things with PR, so it should work in most cases.

So go ahead and try it with Python 3!! So I think it is time we can close this issue, and if specific problems due to python 3 appear, let users report new specific issues. Thanks!

**Comment by nunojpg** [comment]
Hi @memsharded,

https://travis-ci.org/nunojpg/conan-botan/jobs/232453040

It seems there is a incompability on OSX between python 3.5 and the requirement: pyOpenSSL>=16.0.0, <16.1.0

On windows and linux it works fine. Is there a actual reason for this requirement?

**Comment by memsharded** [comment]
This is weird, we had testing with 3.5 until very recently, and it was OK, not sure what is happening. pyOpenSSL is required in OSX for https support I think, maybe @lasote can provide better insights.

**Comment by nunojpg** [comment]
I think this might only apply to conan-package-tools, so I opened the issue at:

https://github.com/conan-io/conan-package-tools/issues/68
