### ISSUE TITLE
CMake build helper should set CMAKE_X_OUTPUT_DIRECTORY_<CONFIG>

### ISSUE THREAD

**Issue by Ignition** [conan-io/conan#5122]
https://cmake.org/cmake/help/latest/prop_tgt/RUNTIME_OUTPUT_DIRECTORY.html

With visual studio if it is not set, then path isn't easy to code for which causes complexity for where you import the conan dependecies. It would be nice if this was consistant location, to make import easier.

**Comment by Ignition** [comment]
My current conanfile.py looks like
```
    def build(self):
        cmake = CMake(self)
        cmake.definitions["CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG"] = "lib"
        cmake.definitions["CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG"] = "lib"
        cmake.definitions["CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG"] = "bin"
        cmake.definitions["CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE"] = "lib"
        cmake.definitions["CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE"] = "lib"
        cmake.definitions["CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE"] = "bin"
        cmake.configure()
        cmake.build()

    def imports(self):
        self.copy("*.dll", dst="bin", src="bin")

    def test(self):
        if not tools.cross_building(self.settings):
            cmake = CMake(self)
            cmake.test()
```

**Comment by lasote** [comment]
Yes, you are totally right. Currently, (and wrongly) that work was done by the classic `cmake` generator. 
In this [project](https://github.com/conan-io/conan/projects/5) basically, we want to move some functionality from the generators to the build helper, and also make the build helper generate some file that could be injected to your `CMake` in case you want to build locally calling CMake directly (while you are developing the package, for example, https://docs.conan.io/en/latest/developing_packages.html).

I really like to see in your recipe the `generators = "cmake_find_package"` because I agree it should be the recommended way to "plug" the dependencies, but this kind of details and some other are still pending. Anyway please take a look at `cmake_find_package_multi`, in addition of supporting multi-config, it is more advanced and it is generating `Config` files with targets instead of old style `Find` cmake script. 

We will try to unify all the `cmake` generators in one for Conan 2.0, fix all this stuff and recommend the usage of `find_package` as you are doing. But still, the integration only find_package have some flaws..

Thanks for reporting!
