### ISSUE TITLE
Private requirements vs build requirements for deployment packages 

### ISSUE THREAD

**Issue by iakovn** [conan-io/conan#5139]
Hi, 

I am considering using conan for deployment packages and following docs here: https://docs.conan.io/en/latest/devtools/running_packages.html
I am wondering why you are recommending use of build requirements and not private requirements? It seems more natural to me that deployment package gets a new hash when version of requirements change which is not the case with build req. 
Thanks, Iakov

**Comment by jgsogo** [comment]
Hi @iakovn, it all depends on your use case, and I can tell you too that the graph model is evolving and we are preparing some changes for Conan v2.0 (some of those change might modify current behavior).

(I know that the following are not an answer, but... 😔)

Recipes corresponding to `build_requires` are only retrieved if the package that requires them has to be built, and this is the reason why they cannot affect the ID, this is by design and it is not going to change. We usually associate them with tools needed to compile: `protoc` executable to generate code, some tool to unzip the sources, `cmake` itself,... and it happens the same if you are repackaging.

There are several scenarios where a `build_requires` can change:
 1. Select a different package given different settings, your recipe will be different if it also has those settings.
 2. You are using version_ranges for a `build_requires` and it resolves to a different version. The [_revision_ of the recipe](https://docs.conan.io/en/latest/mastering/revisions.html?highlight=revisions) will change.
 3. You explicitly change the version of a `build_requires`, you can change the version of your recipe too.

Yes, there are scenarios where your package could be the same (ID) given a change in your `build_requires`. If this is a problem, if your tool (the `hello` executable) is different for different versions then you will need to model it: as you said you can change it to a _private_ requirement or you can model it through options (depending on the value of the option you choose the version of the `build_requires`).

I think that here there is no _one size fits all_, we can only provide the tools (and docs) to let you deal with your use case.

**Comment by iakovn** [comment]
Ok, thanks. I believe I understand. I was only confused that build_requires was used in this example without mentioning the other options and implications.
