### ISSUE TITLE
Question: how would I approach uploading different branches to artifactory?

### ISSUE THREAD

**Issue by Satus** [conan-io/conan#5147]
Hi,

I have a library for which I made a conan package. I have a CI system that runs when a new git branch or a new commit were pushed. I want to push artifacts to artifactory for every build or every branch that I have. How would I organize uploading in this case?

Should I have different channel for every branch?

**Comment by uilianries** [comment]
Yes, most cases we use channel names like "release", "stable", "testing", "ci".

You could use "release" or "stable" for verified branches, "testing" for unstable branches and "ci" for any build related to a new commit.

There is a documentation about Conan channels [here](https://bincrafters.readthedocs.io/en/latest/using_packages.html#understanding-conan-channels).

**Comment by Satus** [comment]
Thank for answering. So, if I have a testing channel, how would I differentiate between different branches withing it?

**Comment by uilianries** [comment]
depends who your git flow works ... for project releases you can use **stable**, for develop you could use **testing** (if both recipe and source are in same repo), and for any custom branch like feature/ or hotfix/ you could use **ci** channel.

BRANCH | CHANNEL
master: stable
develop: testing
feature/hotfix: ci

The channel **ci** is useful only if you want to upload any change for any build on you CI, otherwise, I would say both testing and stable are enough.

**Comment by danimtb** [comment]
Hi @Satus,

IMO, the most appropriate way to solve this is to create a separate repository for a feature branch so packages are not mixed with the "master" branch ones. Then when the branch is merged to master, CI will create the packages from the merged code and upload them to the main repository.

This is an approach I have seen in other projects using other package managers and using Artifactory for development.

You can also benefit from the user and channel scopes that Conan provides but probably is too much effort as references will change and those changes would need to be referenced in every recipe.

Hope that helps

**Comment by Satus** [comment]
Thanks, that clears things up a bit.
