### ISSUE TITLE
conan remove is unable to remove Qt

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#5187]
having both `Qt` and `qt` on Windows results in inability to remove it via `conan remove` command:
```
> conan remove qt* -f
WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: settings.yml is locally modified, can't be updated
WARN: The new settings.yml has been stored in: C:\Users\SSE4\.conan\settings.yml.new
WARN: ****************************************
WARN: registry.json has been deprecated. Migrating to remotes.json
ERROR: Cannot migrate old registry: Requested 'Qt/5.11.2@bincrafters/stable' but found case incompatible 'qt'
Case insensitive filesystem can't manage this
```
the only thing that helps is to manually remove it from the `%USERPROFILE%\.conan`
conan 1.15

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment]
This an old issue about casing in Windows and the only thing we can do is improving the help message to indicate to the user to proceed the same way you did

**Comment by tonka3000** [comment]
Hey @danimtb ,

there would be an better otpion inside conan.  
Use your own remove function (I know you have one) and use a powershell command instead of the python based one (maybe turn it of by an environment variable or a config entry). I do this with my python projects all the time on windows. This would solve the problem in most cases (python's remove of directories is really bad on windows if the are more files/folder).

The powershell command would be (remove CONAN_USER_HOME f.e.)
```ps1
powershell -c "Remove-Item '%CONAN_USER_HOME%' -Force -Recurse"
```

I've create an issue about the remove problem (#2593), so you can handle it as duplicate if you like. Also the referenced issue from @lasote #2170 could also be "solved" with a powershell trick (it's available since Windows 7 as far a I know).

**Comment by danimtb** [comment]
Thanks a lot for pointing those issues @tonka3000. Yes, it could be a possibility although I see it a bit fragile.

I think that is the reason @lasote said that this could be implemented in a ``post_remove`` Hook (previously called "plugin") to see how it works.

**Comment by memsharded** [comment]
Closing as inactive
