### ISSUE TITLE
[Question] Choose CMake variables for a specific package rather than for the whole recipe?

### ISSUE THREAD

**Issue by Philippe-Cote-Morneault** [conan-io/conan#5203]
To help us debug your issue please explain:

Hi,

I would like to know if there is a way to define CMake variables for a specific package rather than for the whole package. For instance, let's say that I have a package for Windows and one for OSX. Let's say the structure for the windows binaries is:

```
root/
├── win32/
   ├── a.cpp
   ├── b.cpp
   ├── a.h
   └── b.h
```

For OSX, I would have:
```
root/
├── macOS/
   ├── a.cpp
   ├── b.cpp
   ├── a.h
   └── b.h
```

I want to be able to copy everything in root and do not want to modify the structure of the folders to normalise everything. In my real use case, I have 2 libraries that have multiple folders and sub-folders that are completly different and are very complicated. I want to just be able to set a CMake variable such as 

`LIBRARY_DEBUG_ROOT = root/macOS` 

For mac and 

`LIBRARY_DEBUG_ROOT = root/win32`

for windows.

Whenever I install a package, I would like the CMake file generated to set these variables appropriatly depending on what I would specify in my conaninfo.txt for example, but there doesn't seem to be a way. All there seems to be is a way to set a CMake variable for a recipe, not a package. Is there a way to do what I am suggesting? 

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by Johnnyxy** [comment]
Hi there,
I am trying to understand your question but until now I am struggeling to see what your use case is.

At what Conan step do you need the information stored in this variable?
conan install/build/package/export-pkg/deploy?

Who should be using this variable? Your recipe/cmake code or a consumer's recipe/cmake code?

> I want to be able to copy everything in root

What do you want to copy from where and when?


In general you can set custom variables with the "cmake" generator for consumers to use. But I do not know if this is what you want.

Please elaborate a little bit more what, when and purpose oft this variable and its content.

**Comment by JigsawCorp** [comment]
@Johnnyxy 

Hi, basically when I am going to `export-pkg` or `upload` it, I would like to specify some CMake variables specific to that package, and not the recipe. Here's my use case: I currently set paths to certain folders of my libraries manually in a CMake file (This is the current situation without having Conan involved). I am adding all my libraries to my Conan repo as pre-built binaries. This is what my CMake currently looks like to set paths: 
![Capture](https://user-images.githubusercontent.com/15023263/58198639-aebee800-7c9c-11e9-8511-ad8b7a6d6cff.PNG)

As you can see, this isn't ideal. What I would like is a way that would set CRYPTOPP_LIBRARIES_DEBUG to the right path depending on what OS I am on, but having this being dealt with by Conan. I would like when I am either creating a package or uploading it to have somewhere to store these CMake variables somewhere that would change depending on what package I am in. In my example, the path is different whether I am on Linux, Mac, or Windows. 

I saw that you can set CMake variables, but in the recipe. This isn't what I want because the paths are different package to package. 

I already have all the files I want in my packages and everything is on Conan, the only thing left is finding a clean way to set my CMake variables.

**Comment by Johnnyxy** [comment]
Ah ok ... you have a package that contains multiple libraries and other files in different flavours (static, dynamic, release, debug, etc.). Now you want put this without any modifications into Conan.

First I will show you how Conan works and then how you can solve your issue and then a more general advice to this :).

how Conan works
--------------------
A Conan recipe gets executed every time you invoke Conan with the ```conanfile[.py;.txt]``` or if it is already in the repository every time your recipe is referenced in any way. This is due to the fact that Conan has to get certain informations (settings, options and dependencies) from the recipe to generate a dependency graph to know any relations from or to other the recipes.

All functions in the recipe are always executed with a specific configuration (settings, options, ...). This configuration defines a unique hash value (the id of every package) and the logic the recipe executes to build a package to provide data of it (like in ```def package_info(self)```).

how you could set CMake variables
---------------------------------------
With the function ```def package_info(self)``` a recipe specifies everything only specific to the package Conan has determined (like VS2017, dynamic, release).
This means any settings specified in the function ```def package_info(self)``` are always specific to a configuration which in turn means a single package:
```python
def package_info(self):    
    if (self.settings.os == "Windows"):
        p = os.path.join("Win32/Output", str(self.settings.build_type), "cryptlib-mt")
        if (not self.options.shared):
            p += "-s"
    elif (self.settings.os == "Linux"):
        ...
    elif (...)
        ...
    
    self.user_info.CRYPTOPP_ROOT = os.path.join(self.cpp_info.rootpath, p)
```

This code would set the ```user_info.CRYPTOPP_ROOT``` to a value specific to a package depending on the settings, options, etc. Conan has been invoked with.

my 2 cents
------------
I do not know how you want to integrate this CMake file you described in a package and how you want that consumers should find/parse/use it.
First it seems that you resemble something that Conan can already do for you. Show consumers where every file they would need to link to is and what [interface definitions](https://cmake.org/cmake/help/latest/command/target_compile_definitions.html) (macros/defines for consumers) they need to use for a specific configuration.
Second I would look into the install exports feature of CMake that could help you big time with providing informations about library files and interface definitions ([see here](https://cmake.org/cmake/help/latest/command/install.html?highlight=install#installing-exports)).

If what you are trying to achieve is to let the buildsystem describe the whole package to prevent duplication (like defining lib paths/names again in Conan) this is not the Conan way (at the moment). There are some ideas how to unify the description of a package but there is no "standard way" to describe a package at only one place and to avoid description duplication.

See here:
 - https://github.com/conan-io/conan/issues/4878
 - CPS from CMake developers (https://mwoehlke.github.io/cps/overview.html)
 - and a ISO proposal of CPS (https://isocpp.org/files/papers/p1313r0.html)

proposal
----------
Specify the paths and libs in the ```package_info``` function as those informations are given to the generators so they can provide consumers with the correct files they need specific to a package.

```python
def package_info(self):    
    if (self.settings.os == "Windows"):
        self.cpp_info.libdirs += [os.path.join("Win32/Output", str(self.settings.build_type))]
        if (self.options.shared):
            self.cpp_info.libs = ["cryptlib-mt"]
        else:
            self.cpp_info.libs = ["cryptlib-mt-s"]
    elif (self.settings.os == "Linux"):
        # self.cpp_info.libdirs += ["lib"] # not necessary as Conan's default is already "lib" 
        self.cpp_info.libs = ["cryptopp"] # I think one can omit the "lib" on unix-like systems as prepending lib is already "standard" on them
    elif (...)
        ...
```

**Comment by JigsawCorp** [comment]
@Johnnyxy 

Wow thanks for the quality and lengthy response!

I'll try to see if I can somehow make things work with one of the solutions you suggested. 

Unfortunately, I am working with a lot of legacy code for the CMake configuration of the project that I am on. The best I can do is seperate my Conan packages depending on OS type and compiler type. The existing CMake files make it so that I need both release and debug libraries together and that the paths are all different depending on what OS you are on. This is obviously not ideal, but it is what it is...

If I may make a suggestion, I noticed that Conan works mostly with the package recipe and doesn't let packages themselves define some configuration. To clarify, let me give you an example. In https://github.com/conan-io/conan/issues/5167, I wanted a way to be able to set settings for a package at the package level. I wanted a way that when I am creating a package, I could give an array of multiple settings values to it. For instance, I wanted to be able to say "Conan, create this package right here with these binaries. This package is compatible with compiler Visual Studio and compiler.version VS 13, 15 and 17." What you currently have to do is set a custom package_id with some logic depending on what compiler version you want at the recipe level. It would be a good addition to allow more logic and configuration at the package level, although this would change how Conan works completely. In that way, I could be able to set my CMake variables at the package-level rather than the recipe-level.

**Comment by Johnnyxy** [comment]
Yes you are right, API compatibility have to be set in the ```def package_id(self)``` function.
There you can specify wich which settings the hash (package id) is calculated. This means that if multiple settings result into the same package id the package is in turn compatible.

Be aware that the next example is a useless setting as the VS versions are now compatible between each other. It is to illustrate the general approach.
```python
def package_id(self):
    if (self.settings.compiler == "Visual Studio"):
        if (self.settings.compiler.version in ["10", "11", "12"]): # make VS2010,2012,2013 compatible (same package id)
            self.settings.compiler.version = "10"
```



Compatibility of Visual Studio
------------------------------
Have a look at the recipe setting ```compiler.toolset``` ([see here](https://docs.conan.io/en/latest/integrations/visual_studio.html?highlight=toolset#toolsets)). I did not actually test it as I am building for every supported compiler a package but the docs state that Conan does not build a package if it finds a compatible toolset package.

This means if you have a package built with VS2015 the toolset is v140. If you now request a package with ```-s compiler.toolset=v140``` then Conan should automatically use the VS2015 build instead of trying to build a VS2017/VS2019 version.

Any other compatibility cannot be guaranteed if you do not have a clean pure C interface.



Compatibility of native Windows builds (compiler independent)
-----------------------------------------------------------------
But if you have a pure C interface and just some DLLs/dynamic libs/headers then you can eleminate the compiler in the ```self.info.settings``` what in turn would make your package compatible with any compiler/linker that builds/works with native Windows binaries.
```python
def package_id(self):
    if (self.settings.os == "Windows"):
        del self.info.settings.compiler
```

**Comment by jgsogo** [comment]
Hi, @JigsawCorp 

Can we close this question?

**Comment by memsharded** [comment]
Closing as outdated. Since then a lot of things have changed in CMake integration.
