### ISSUE TITLE
Using conan to cross compile with Yocto toolchain

### ISSUE THREAD

**Issue by kevswims** [conan-io/conan#5253]
I am trying to use conan to cross compile using a yocto SDK that I have generated. I saw in issue: https://github.com/conan-io/conan/issues/5059 that @danimtb and @lasote have been using yocto but I cannot find any specific docs on how to setup the profile env. Can someone share their profile they are using for this? I would be happy to help contribute this back in a more general way to the documentation once I get this figured out.

My profile currently contains: 
```
toolchain=/opt/kevin-yocto-1/sysroots/aarch64-poky-linux
target_host=aarch64-poky-linux
[settings]
    os_build=Linux
    arch_build=x86_64
    os_target=Linux
    arch_target=armv8
    os=Linux
    arch=armv8
    compiler=gcc
    compiler.version=7
    compiler.libcxx=libstdc++11
    build_type=Release
[options]
[build_requires]
[env]
    CONAN_CMAKE_FIND_ROOT_PATH=$toolchain
    PATH=[$toolchain/bin]
    CHOST=$target_host
    AR=$target_host-ar
    AS=$target_host-as
    RANLIB=$target_host-ranlib
    LD=$target_host-ld
    STRIP=$target_host-strip
    CC=$target_host-gcc
    CXX=$target_host-g++
    CXXFLAGS=-I"$toolchain/$target_host/lib/include"
    CMAKE_PREFIX_PATH=$toolchain

```

but I am receiving errors running conan install where it cannot compile the cmake C compiler test program. It fails with 
```
cannot find crt1.o: No such file or directory
```

What am I missing in the env section to make this work?

**Comment by danimtb** [comment]
Hi @kevswims,

Yes, we haven't published any of the works related to Yocto yet but you can get the idea we did with the SDK wrapper recipe.

Regarding the profile, you may have two options:

1. Use the environment script provided by the toolchain and a simple profile with the specific architecture and compiler of the Yocto SDK.

2. Set all the information in the ``[env]`` section of the profile as you did. Notice that you would have to include all the variables declared in the env script provided by the SDK as some of them point to the directories to find specific libraries from the Yocto SDK and not from your host machine.

There are other details related to CMake variables that have to be set in order to make Yocto fully work with Conan. We will try to share the details in a blogpost soon and maybe provide the wrapper recipe for the most common SDKs already available.

**Comment by jasal82** [comment]
Take a look at my post in issue #5059. That approach might work for you as well if you create a package from your toolchain and then reference it as `build_requires` in the profile. That way you don‘t have to specify the env settings yourself.

**Comment by danimtb** [comment]
Thanks for sharing @jasal82. I think the way you did it makes a lot of sense. As this related to #5059 and seeking the same purpose, let's follow the conversation there if you don't mind @kevswims

**Comment by danimtb** [comment]
Hi! We have released a new page in our documentation about Yocto: https://docs.conan.io/en/latest/integrations/cross_platform/yocto.html

I think you would find it useful

**Comment by danimtb** [comment]
Closing this in favor of #5059. Please continue the conversation there 😄
