### ISSUE TITLE
cmake.is_multi_configuration stopped working in build_id()

### ISSUE THREAD

**Issue by bdegreve** [conan-io/conan#5268]
Using Conan 1.15.1, Windows 10, Visual Studio 2017, CMake 3.12.4, Python 3.7.0

I want to make use of the [N configs (1 build) -> N packages](https://docs.conan.io/en/latest/creating_packages/package_approaches.html#n-configs-1-build-n-packages) packaging approach, in case of Visual Studio on Windows, to share one build directory for release and debug builds. I do not want to build everything at once (so `def build(self)` is traditional), but I want to reuse the CMake configuration, since this is particular costly on Windows. And sharing one build directory for the different build_types accomplishes just that (each build type gets its own subdir anyway).

With makefile generators, I obviously can't do that, but the CMake configuration steps are also must faster so it's no problem.

Thus, since this obviously depends on the CMake generator being used, [I've added this to my conanfile.py](https://github.com/cocamware/lass/blob/master/conanfile.py):

```
    def build_id(self):
        cmake = CMake(self)
        if cmake.is_multi_configuration:
            self.info_build.settings.build_type = "Any"
```
This worked perfectly, up until at least Conan 1.12 (I believe 1.13 as well).

However, since at least Conan 1.15.1, I get the following error when performing:
```
conan create . cocamware/testing
```
```
ERROR: LassConan/1.9.0-189+gf6a49042@cocamware/testing: Error in build_id() method, line 139
        cmake = CMake(self)
        AttributeError: 'LassConan' object has no attribute 'install_folder'
```
Is this a bug? Can you advice on the approach taken? Should I using something other than `cmake.is_multi_configuration`? Can I do something about `install_folder`?

Thanks,
Bram

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Hi Bram,

Thanks for your detailed report!

It could be a bit of abuse of the ``CMake`` build helper for something that is not intended. You can verify that for earlier versions it will also crash if you try to use that recipe with other generators, like ``cmake_find_package`` or ``cmake_find_package_multi``

Quick question: why aren't you checking something more simple like:

```python
def build_id(self):
     if self.settings.compiler == "Visual Studio":
            ...
```

Also, I guess that you have a ``build()`` method that does different things for different systems? Because in Visual Studio you would need to call the build to both Debug and Release, irrespective of the defined ``settings.build_type``, and this is also a bit hacky, isn't it? How do you do that?

Lastly, the cmake configuration is usually not that expensive, compared with the actual building of the project, if the cmake configuration takes too long, it is usually a symptom that the build will actually be very long too? What are your times for it? Is it really worth it the complexity for saving that time?

Thanks for the feedback!

**Comment by bdegreve** [comment]
Hi memshared,

Could you elaborate on how that recipe fails with other generators? I'm not quite sure I understand what to test.

Yeah, I guess I could simply test `self.settings.compiler`, `cmake.is_multi_configuration` seemed the obvious thing to do, but this should work as well. I didn't see this as abusing the `CMake` helper, as the examples show how to use the same query in `build()`.

No, `build()` is traditional, packaging is also traditional. I still only build Debug or Release, depending on `settings.build_type`. It's still 1 build 1 build_type for 1 package: `conan create . cocamware/testing` creates a Release package, `conan create . cocamware/testing -s build_type=Debug` creates a Debug package. But if I do both, one after another, they will _share the same build tree_ (it is `is_multi_configuration` after all :-), and the second will reuse the CMake cache. Technically, the second create still _runs_ `cmake.configure()`, but since the build tree is shared, the CMake cache is already primed, and it goes much faster.

The CMake config step in an empty build tree takes somewhat more than a minute. On Windows, the different tests that CMake performs are quite slow in my experience. Much slower than on Linux.
Building one configuration takes somewhat less than a minute. So the CMake config step "from scratch" _is_ a considerable overhead. 

Being able to skip that when building multiple build_types (each with its proper `create . cocamware/testing -s build_type=<x>` call, significantly reduces the overal build time. And by only modifying `build_id()` to share the same build tree, this is otherwise fully transparent for the user. As far as the clients are concerned, each build is one build type, is one package.

**Comment by memsharded** [comment]
Hi Bram,

I think if you add ``generators = "cmake_find_package"`` to your recipe, you will see it crashing also in previous versions of Conan, not just the latest.

> No, build() is traditional, packaging is also traditional. I still only build Debug or Release, depending on settings.build_type. It's still 1 build 1 build_type for 1 package: conan create . cocamware/testing creates a Release package, conan create . cocamware/testing -s build_type=Debug creates a Debug package. But if I do both, one after another, they will share the same build tree (it is is_multi_configuration after all :-), and the second will reuse the CMake cache. Technically, the second create still runs cmake.configure(), but since the build tree is shared, the CMake cache is already primed, and it goes much faster.

I am not fully sure that this works, or maybe it seems it works but it is not doing exactly what you want:

- If two different package binaries, with different ``package_id`` IDs (Debug and Release), generate the same ``build_id``, then the recipe ``build()`` method will be called just once, and it will build, calling cmake, just once.
- By default, the configuration that will be injected in the ``build()`` method will be the one of the first call. If the first ``conan create`` uses the default Release, the binaries being built will be Release only.
- Subsequent calls with ``conan create -s build_type=Debug`` will resolve to the same ``build_id``, detect that the build_folder is already populated, and will not call ``build()`` again. It will only call ``package()`` again, and you might be incorrectly packaging Release artifacts as they were Debug ones
- The way ``build_id()`` should be used is guaranteeing that 2 builds are done, for the 2 different build types:
   - Having your ``build()`` method programmatically calling the ``cmake.build()`` helper twice, changing (hardcoding) the build_type, to force to use it irrespective of the ``settings`` input one.
  - Having your CMakeLists.txt scripts to be hardcoded to always generated Debug and Release artifacts, no matter what is passed to cmake.
- It is not that they share the same build tree in the cache, and a second ``build()`` is being called.

I'd like to make sure that you are using one of those ways, otherwise, I think it is not doing what you want. It is also very likely that I might be missing something because of ignorance of your recipes or your builds, but I think it is better to be sure, to avoid you problems in the future. Please let me know to better understand your use case and see what would be the best solution. Thanks!

**Comment by bdegreve** [comment]
Aha, now I see ...

I didn't notice before that `build()` was called only on the first `conan create`. I didn't notice, because my `package()` step simply calls `CMake.install`:
```
def package(self):
    cmake = self._cmake()
    cmake.install()
```
In the second call `conan create -s build_type=Debug`, this `cmake.install()` would find a build tree with missing Debug artifacts, and effectively taking over the role build step. Everyone happy ever after.

But this is of course a very ugly coincidence. Btw, I also had to set `compiler.runtime = "Any" to really match the build_id:
```
    def build_id(self):
        if self.settings.compiler == "Visual Studio":
            self.info_build.settings.build_type = "Any"
            self.info_build.settings.compiler.runtime = "Any"
```

One build that really builds both Release and Debug (and RelWithDebInfo is relevant too), is not worth the trouble, because as often as I need both, I want to build only one during development, and I'm wasting as much time waiting for the other build, as I was waiting on the duplicate CMake configure step.

It's a pity it didn't work as intended, because I thought it really nice to benefit from a shared build tree where CMake would allow it. "My way" worked because of an ugly side-effect, so I shouldn't be doing it, and one build building multiple configs is overhead in another way. So, in the end, I'll remove `build_id()` and revert to the default 1 build = 1 config = 1 package.

As far as I'm concerned, this case may be closed.

**Comment by memsharded** [comment]
Oh, now I understand! ``package()`` calling ``cmake.install()`` was not only installing but also building! So finally you were getting the right final result, but thanks to some "lucky" coincidences.

I think your decision of simplifying the recipe is a good one. Do not consider only the time saved from avoiding one cmake "configure" step, but also the possible future time of understanding how the package is created from that recipe from some future maintainer, or someone debugging the process... It might be worth keeping the recipe as simple as possible even if some extra time is spent in the package creation. Also, once a recipe is defined, is common practice that developers don't build it, but CI, and if CI runs parallel jobs for different configurations (also typical), they cannot reuse the same build (not concurrent safe).

Thanks very much for all the feedback and clarifications, if in the future this configure time becomes totally unmanageable, please tell and we might try to investigate some new solution for it :)

Cheers!
