### ISSUE TITLE
[system-package-tools] Add support for Brew cask

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#5287]
To help us debug your issue please explain:

Brew has the argument `cask`, which works like `-no-install-recommends`. It would be nice adding a new parameter to enable, or solving automatically when necessary.

XQuartz is a good example:

```
Running: brew update
Already up-to-date.
Running: brew install xquartz
Error: No available formula with the name "xquartz" 
Found a cask named "xquartz" instead.
freeglut/3.0.0@bincrafters/testing: ERROR: while executing system_requirements(): Command 'brew install xquartz' failed
```

As you can see, Brew warned about cask. Maybe SystemPackageTool could solve it, re-running the install command, but using cask.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
Brew support was added to SystemPackageTool time ago, closing.

**Comment by Croydon** [comment]
@memsharded Brew and brew cask work differently. Brew tries to build from source by default, cask lets you download and install binaries. 

This issue is about brew cask. [Freeglut still depends on X11 on macOS](https://github.com/FreeGLUTProject/freeglut/blob/edbdcbe75af5f7ad43278eecd377a078987bcb09/README.md#ports), and the best way to install it seems to be via brew cask. That is why we requested support for it

https://github.com/bincrafters/conan-freeglut/blob/51f645969924360c470e53c7553f70041803a4dc/conanfile.py#L65

https://github.com/conan-io/conan-center-index/blob/1949f5ad0b0082da85e3da5dce6fd80d5a36fb19/recipes/freeglut/all/conanfile.py#L67

**Comment by memsharded** [comment]
Thanks for the feedback, I misunderstood it. Re-opening.

**Comment by memsharded** [comment]
It seems brew cask at the moment doesn't have a large demand, and the workaround from https://github.com/bincrafters/conan-freeglut/blob/51f645969924360c470e53c7553f70041803a4dc/conanfile.py#L65 seems quite doable ``self.run("brew cask install xquartz")``, so at the moment I am closing this as not planned, it was opened for years without any other feedback or request.
