### ISSUE TITLE
[question] Check CMake version in conanfile

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#5292]
Is there an easy way to check the CMake version inside a conanfile? I need to set cmake options differently depending on the cmake version.

**Comment by Johnnyxy** [comment]
Hi there,
Conan has the same way of checking the CMake version as e.g. PowerShell has or Python itself has as CMake is an external software which just gets called by Conan.

**The following is untested code. Bugs and type-o mistakes included.**

version parsing
-----------------
CMake prints the following test if called like this ```cmake --version```:

>cmake version 3.14.5
>
>CMake suite maintained and supported by Kitware (kitware.com/cmake).

This output one could parse manually: 
```python
import os
from six import StringIO  # Python 2 and 3 compatible
from conans import tools



def get_cmake_version(self, cmake_executable=None):
    if (cmake_executable is None):
        cmake_command = 'cmake --version'
    else:
        cmake_command = os.path.normpath(cmake_executable) + ' --version'
    res = StringIO()
    try:
        self.run(cmake_command, output=res)
    except:
        self.output.error('{name}: could not execute CMake successfully ({{command: {command}}})'.format(name=self.name, command=cmake_command))
        raise
    res = str(res.getvalue())
    index = res.find('\n')
    if (index == -1):
        raise Exception('could not parse CMake version ({{value: {value}}})'.format(value=res))
    res = res[:index]
    index = res.rfind(' ')
    if (index == -1):
        raise Exception('could not parse CMake version ({{value: {value}}})'.format(value=res))
    return res[index+1:]

def build(self):    
    cmake_version_is_3_or_higher = tools.Version(self.get_cmake_version()) < "3.0.0"
```

Additonally since CMake 3.7 one has the ability to use a JSON output feature of CMake which returns the CMake version ([see here](https://cmake.org/cmake/help/v3.7/manual/cmake.1.html#command-line-tool-mode)).

execute CMake script
------------------------
A more defined approach would be to parse the actual [CMake version variables](https://cmake.org/cmake/help/latest/variable/CMAKE_VERSION.html#cmake-version). This will also work with old versions and does not rely on any _(maybe changing)_ output format.

- [CMAKE_MAJOR_VERSION](https://cmake.org/cmake/help/latest/variable/CMAKE_MAJOR_VERSION.html#variable:CMAKE_MAJOR_VERSION)
- [CMAKE_MINOR_VERSION](https://cmake.org/cmake/help/latest/variable/CMAKE_MINOR_VERSION.html#variable:CMAKE_MINOR_VERSION)
- [CMAKE_PATCH_VERSION](https://cmake.org/cmake/help/latest/variable/CMAKE_PATCH_VERSION.html#variable:CMAKE_PATCH_VERSION)

```python
import os
from six import StringIO  # Python 2 and 3 compatible
from conans import tools



def get_cmake_version(self, cmake_executable=None):
    cmake_script = os.path.join(self.build_folder, 'cmake_version.cmake')
    if (cmake_executable is None):
        cmake_command = 'cmake -P ' + cmake_script
    else:
        cmake_command = os.path.normpath(cmake_executable) + ' -P ' + cmake_script
    with open(cmake_script, 'w') as f:
        f.write('message ("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}.${CMAKE_PATCH_VERSION}")')
    res = StringIO()
    try:
        self.run(cmake_command, output=res)
    except:
        self.output.error('{name}: could not execute CMake successfully ({{command: {command}}})'.format(name=self.name, command=cmake_command))
        raise
    return str(res.getvalue())

def build(self):    
    cmake_version_is_3_or_higher = tools.Version(self.get_cmake_version()) < "3.0.0"
```

**Comment by sigiesec** [comment]
Thanks! I would have written something like that myself, but I thought that maybe there is something provided by conan since that might be a recurring issue. Nevertheless thanks a lot for the sample code!

**Comment by Johnnyxy** [comment]
The Conan devs could build in something like that as ```tool```.
The advantage would be that there would be only one place where specialized code exists that has to be maintained ... in the Conan repository.
If not, everyone who needs something like that will write his own implementation.


Can you elaborate what things you have to provide for differently for different CMake versions?

**Comment by sigiesec** [comment]
The particular cmake define I need to set is CMAKE_GENERATOR_TOOLSET with a value like version=14.14 for the Visual Studio 2017 generator which is only supported from cmake 3.12

**Comment by Johnnyxy** [comment]
Hm, if you use the CMake build helper it has a parameter for this ([see here](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#constructor)).
I am using this to get the real 64 bit compiler of Visual Studio (cl.exe). Not the normal 32bit to 64bit cross-compiler.

You could do it like this:
```python
toolset='version=v141'
if (self.settings.arch_build == "x86_64"):
    toolset += ',host=x64'
cmake = CMake(self, toolset=toolset)
```


Otherwise you could set the variable anyway even if CMake does not support this in an older version. It will just ignore it as CMake does not know it.

**Comment by sigiesec** [comment]
Unfortunately that's not the case. An older cmake (3.8.2) fails as it knows about CMAKE_GENERATOR_TOOLSET but not the version=... value

**Comment by Johnnyxy** [comment]
ah ok ... I did not know that as I have to do builds for all compiler version separately ...

**Comment by jgsogo** [comment]
CMake helper has a static function that returns the version: `CMake.get_version()` (documented here: https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#get-version) 😸

**Comment by Johnnyxy** [comment]
ouhhh double shame :)

**Comment by jgsogo** [comment]
Sometimes the docs are not clear enough and the search box doesn't help (btw, we are working on it). As it is documented we should maintain this function for every CMake version, if it fails, open an issue and we'll fix it (probably inspired by this snippet).

**Comment by memsharded** [comment]
Closing this as outdated. Conan 2.0 removed the ``CMake.get_version`` helper. Most of the cases, this shouldn't be that random, with Conan using a specific CMake version is very easy with ``tool_requires``. And if not a relatively simple ``self.run("cmake --version", ...)`` would be enough
