### ISSUE TITLE
SystemPackageTool and Packages

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#5347]
This is a question about the conceptional use of SystemPackageTools in recipes.

If I have a requirement that could be fullfilled by a system package on Linux I would have to write code like:

```
def requirements(self):
    if self.settings.os != "Linux":
        self.requires("mylib/1.0.0@user/channel")

def system_requirements(self):
    if self.settings.os == "Linux": 
        pack_name = "mylib-dev"
        installer = SystemPackageTool()
        installer.install(pack_name)
```

This is a lot of boilerplate code, and actually, if I am consuming the package, I don't quite care if the package is a system package or build or downloaded, as long as it fullfills my version requirements. 

But if I provide a package in a specific version, I might want to fall back to a system package if available. And actually I'd prefer to use a system package, if it does fullfill my version requirements. 
Additionally, I never want Conan to install any system packages for me, but rather tell me which ones I need to install instead.

So regarding this `mylib` example, is it possible to specify the requirement in the recipe for `mylib` instead of the recipe of the consumer?
And is it possible to only call some kind of `check` function (instead of `install`) on the SystemPackageTool(). 

PS: Is it better to check with `self.settings.os == "Linux"` or `os_info.is_linux`?

PPS: Does the `system_requirements` approach work with cross builds at all?

PPPS: Is there such a thing as `build_system_requirements` (e.g. I am thinking about e.g. doxygen which needs to be installed for documentation generation.)

**Comment by uilianries** [comment]
Hi @KerstinKeller !

`system_requirements` is lack when you don't have that specific package distributed but you need some library to build your packages, otherwise it won't work. Both should not be used together to install the same package.

> This is a lot of boilerplate code, and actually, if I am consuming the package, I don't quite care if the package is a system package or build or downloaded, as long as it fullfills my version requirements.

As a consumer, you just want to install your dependencies and build your project, but when developing a recipe is another scenario. System packages are really really hard to be maintained when distributing open source projects. For instance, think about a simple library, like zlib. Now you need to know how zlib is named in may distros, as Ubuntu, RedHat, Arch Linux, Brew ... But also a customer could want install a cross-compiled package, which means now we need to solve possible prefix/suffix in the package name and the arch name. Also, we can't set a specific version of package, because many distros removed any outdated version, which will break any package.

> But if I provide a package in a specific version, I might want to fall back to a system package if available. 

If I understand, if you have a Conan package for a specific library, you would like to remove a system package which is related to that library. It's not possible because we can't filter/search system package names based in project names.

> I never want Conan to install any system packages for me, but rather tell me which ones I need to install instead.

https://docs.conan.io/en/latest/reference/env_vars.html#conan-sysrequires-mode

You just need to set `CONAN_SYSREQUIRES_MODE=disabled`

> So regarding this mylib example, is it possible to specify the requirement in the recipe for mylib instead of the recipe of the consumer?

Do you mean override a system requirement? No, you can't. If you want to install a different version of any package, you will need to patch the upstream.

> And is it possible to only call some kind of check function (instead of install) on the SystemPackageTool().

What does mean check? Verify if the package exists or is it installed? 

When calling `SystemPackageTool.install()` you can specify to update your cache before installing, or forcing to install again if already installed.

https://docs.conan.io/en/latest/reference/conanfile/methods.html#systempackagetool

> Is it better to check with self.settings.os == "Linux" or os_info.is_linux

They are different things. `self.settings.os` is about your package id, `os_info.is_linux` is about your current platform. For this case, prefer using `os_info.is_linux` because the system package will be installed according the platform.

> Does the system_requirements approach work with cross builds at all?

`system_requirements` is just a method which is called when your recipe is parsed by Conan. It doesn't matter if your are cross-building or not, it will be executed.
For cross-building scenario, you will need to use the correct package name when installing:

```
def system_requirements(self):
    if self.settings.os == "Linux":
        package_name = "mylib-dev"
        if tools.cross_building(self.settings):
            platforms = {"x86": "i386", "armv7": "arm", "armv7hf": "armhf"}
            package_name += ":" + platforms[self.settings.arch]
        installer = SystemPackageTool()
        installer.install(pack_name)
```

>  Is there such a thing as build_system_requirements (e.g. I am thinking about e.g. doxygen which needs to be installed for documentation generation.)

I didn't understand well the idea, but there are "installer" packages. They are packages which contain executable instead of libraries. For example [doxygen_installer](https://github.com/bincrafters/conan-doxygen_installer)

Please, take a look in docs to have more information:

https://docs.conan.io/en/latest/reference/conanfile/methods.html#method-system-requirements

Regards

**Comment by KerstinKeller** [comment]
Hi @uilianries,

first thanks for the comprehensive answer!

So first, we're inside a corporate environment, so I will have to provide almost all the recipes (sometimes leaning on the bincrafter ones), but hosting everything inside our firewall.

Ok, maybe let's take the doxygen example. It will always be a build tool, so I will have it as a `build_requires = "doxygen/[>=]1.0@user/channel"`

So now I have to write a doxygen recipe, to provide doxygen. On Windows, the recipe would download prebuild artefacts (provided by doxygen) which I uploaded to an artifactory. But on Linux, I would just like to make sure, that doxygen is installed:


```
from conans import ConanFile, tools, python_requires
from conans.errors import ConanInvalidConfiguration
import os.path

class DoxygenConan(ConanFile):
    name = "doxygen"
    version = "1.8.15"
    license = "GNU General Public License"
    author = "Doxygen"
    url = "artifactory/doxygen/"
    origin = "http://www.doxygen.nl/download.html"
    description = "..."
    topics = "..."
    settings = "os_build"

    def system_requirements(self):
        if tools.os_info.is_linux:
            installer = SystemPackageTool() 
            installer.install("doxygen")
        
    def build(self):      
        if (self.settings.os_build == "Windows"):
            tools.get("{}{}-{}.windows.x64.bin.zip".format(self.url, self.name, self.version), verify=False, destination="bin")
            
    def package(self):
        if (self.settings.os_build == "Windows"):
            self.copy("bin/*")

    def package_info(self):
        if (self.settings.os_build == "Windows"):
            self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))
```

Is it feasible to do it like this? I have not seen the recipes to use this pattern. Usually I see consuming packages to require either a Conan package or a system package.

> https://docs.conan.io/en/latest/reference/env_vars.html#conan-sysrequires-mode

> You just need to set CONAN_SYSREQUIRES_MODE=disabled

Thank you, the `verify` option seems to be the right thing in my case. You can set these only as a environment variable or also as a conan setting?

### `system_build_requirements`
>> Is there such a thing as build_system_requirements (e.g. I am thinking about e.g. doxygen which needs to be installed for documentation generation.)

> I didn't understand well the idea, but there are "installer" packages. They are packages which contain executable instead of libraries. For example doxygen_installer

So I mean, conceptionally there is the `requires` and a `build_requires`, distinguishing, how a requirement will be propagated (`requires` -> propagate to consumers, `build_requires` -> only necessary when building the recipe). 

There is also a `system_requirements`, which is equivalent to `requires` (propagates to consumer), but will install / query a system package. But there is not such thing as `build_system_requires` e.g. a system requirement which is needed only during the build of a package, but not when consuming the package.

### How to continue
I will test the approach I mentioned above. As we are inside a corporate environment, I'd like to fall back on as many system packages on Ubuntu as possible, just for convience reasons. Especially complex packages like Qt are quite easy to install with apt-get and hard to build / create recipes for.

Also I fear to run into trouble when deploying my applications (without Conan).

**Comment by memsharded** [comment]
This ``SystemPackageTool`` was replaced in 1.X for a newer alternative in ``conan.tools.system``, and removed in 2.0, closing this as outdated.
