### ISSUE TITLE
conan install is failing when a same dependent package having multiple versions

### ISSUE THREAD

**Issue by deekshith-elear** [conan-io/conan#5379]
Hi,
I want to build a library Z it depends on X and Y library. X and Y depends on V library but they are using different versions. Is there any way that we can provide common version package and ignoring V library packages of X and Y library

**Comment by memsharded** [comment]
Yes, versions from the downstream consumers override the upstream declarations.

If Z declares a dependency to a given version of V, that will override the versions that both X and Y were declaring. If you don't want to induce a new, artificial edge to the dependency graph, you can make Z define it as an "override", explicitly. Have a look to https://docs.conan.io/en/latest/reference/conanfile/methods.html#requirements

**Comment by chreniuc** [comment]
@deekshith-elear if you are going to use `override`, please read the use case from this comment: https://github.com/conan-io/conan/issues/5394#issue-459897736

You may get a undefined reference if some of the methods from the `V` library are renamed in the newer version. This happened to us when we wanted to use the latest boost(because `X` and `Y` will not be rebuit, if there are already in the local case built with `V` of a specific version). The fix for this would be to use `--build` to rebuild all dependencies with the new version of the `V` library or to update each library(conanfile) to use the latest version of `V`, by launching a new version for `X` and `Y`.

**Comment by memsharded** [comment]
Closing as inactive
