### ISSUE TITLE
[2.0] self.cpp_info.builddirs default dir 

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5401]
It shouldn't be by default the root of the `package_folder` because:

1) It doesn't feel clean
2) Every file should be in a folder
3) Probably in the root means that any other subfolder is inside a builddir? e.g:
     - `/file.cmake` is in a build folder
     - `/whatever/file.cmake` is not in a build folder unless `whatever` is added to `builddirs`
     - `/whatever/other/file.cmake` is in a build_folder if `whatever` is added to `builddirs`, because it is a subdirectory, but `whatever` is already a subdirectory of "/".

**Comment by memsharded** [comment]
To take into account: cmake is able to find things in paths like package_folder/share/local/someConfig.cmake, if package_folder is a build-dir, and that happens naturally using ``cmake.install()`` because it will generate that path into the package_folder. Furthermore those packages might different in different OS, so adding them to builddirs might add some extra complexity.

**Comment by lasote** [comment]
So, what do you suggest?

**Comment by memsharded** [comment]
Done, already fixed in 2.0 beta
