### ISSUE TITLE
[Build helpers/Toolchain] CMake helper sets CMAKE_CXX_STANDARD variable

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#5403]
Hi there,
I have been searching the docs as well as here in the issues but did not find something that relates to this topic.

At the moment I am using only the ```cmake_find_package``` generator and the CMake build helper.
I noticed that when the ```settings.compiler.cppstd``` setting is set the appropriate variable in CMake ```CMAKE_CXX_STANDARD``` does not get set.

The docs state that this gets set with the ```cmake``` and ```cmake_multi``` generators. But in my case I do not get this benefit of the generators. So I have to rely on the CMake build helper.

There have been a discussion about the ```cppstd``` setting here: https://github.com/conan-io/conan/issues/1799

Can the CMake helper be extended to specify the CMake variable ```CMAKE_CXX_STANDARD``` or is it intentionally left out.

I could do a workaround by defining the variables by myself but this seems to be redundant:

```python
cmake = CMake(self)
if ('CONAN_CMAKE_CXX_STANDARD' in cmake.definitions):
    cmake.definitions['CMAKE_CXX_STANDARD'] = cmake.definitions['CONAN_CMAKE_CXX_STANDARD']
if ('CONAN_CMAKE_CXX_EXTENSIONS' in cmake.definitions):
    cmake.definitions['CMAKE_CXX_EXTENSIONS'] = cmake.definitions['CONAN_CMAKE_CXX_EXTENSIONS']
```

**Comment by jgsogo** [comment]
Hi, it is one of those things that Conan handles automagically with the `cmake` generator + `conan_basic_setup()` approach. It calls `conan_set_std` function where that logic is applied.

The `CMake` build helper only populates `CONAN_XXX` variables (except directories, build type and build_shared_libs). There is an optional [argument in the constructor](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#constructor), `set_cmake_flags`, that probably has a too vague documentation:

> set_cmake_flags (Optional, Defaulted to None): Whether or not to set CMake flags like CMAKE_CXX_FLAGS, CMAKE_C_FLAGS, etc.

IMO it is not clear if that flag should populate all the `CMAKE_XXXX` variables corresponding to flags (like the cxx_standard) or not. At this moment it only sets the flags for the architecture/compiler.

**Comment by Johnnyxy** [comment]
Thx, I will give it a try :-).

**Comment by Johnnyxy** [comment]
@jgsogo 
I took a peek into the Conan code (here: https://github.com/conan-io/conan/blob/b75300bb02f4e7111167719c7cf7999bb9812abc/conans/client/build/cmake_flags.py#L319).
It looks like the switch ```set_cmake_flags``` sets some CMake variables but not the ones I wanted.

Thus I have to set the variables in the ```cmake.definitions``` dictionary by myself.

**Comment by jgsogo** [comment]
Yes, this is something to add to the backlog and decide if all those variables should be populated when this flag is set.

Thanks!

**Comment by lasote** [comment]
This issue will be solved when we move forward to the "toolchain" idea. Now, the "find package" generators, as you described, are lacking adjustments that the `conan_basic_setup` is doing wrong because they don't belong to the dependencies but to the "settings" (current build) model. The idea is going to be: Generate/apply always a toolchain file and another one, probably included (if needed) when available from the toolchain, with the dependencies information, in this case, the find/config scripts. Related to: https://github.com/conan-io/conan/issues/2956 and many others

**Comment by lasote** [comment]
POC description: https://github.com/conan-io/conan/issues/5737

**Comment by johnmcfarlane** [comment]
Relates to #6692. For users wishing to reserve toolchain files for their originally-intended purpose only (specifying toolchain-specific variables), consistent setting of `cmake` command-line parameters would be much appreciated.

**Comment by memsharded** [comment]
Hi @johnmcfarlane 

I think this issue is now outdated. You would need to clarify:

- The legacy ``CMake`` build helper is no longer being develop, unless some regression happens or some very serious bug.
- Development is being done in ``CMakeToolchain`` and ``CMake`` in the ``from conan.tools.cmake`` space: https://docs.conan.io/en/latest/reference/conanfile/tools.html
- The new ``CMake`` helper is a very thin wrapper around the command line, it doesn't add any variable at all (except adding the generator and ``-DCMAKE_TOOLCHAIN_FILE``
- The new ``CMakeToolchain`` helper is way more flexible than the previous solution. It allows modifying every single part ("block") of the toolchain, replacing it by a user toolchain, or including a user toolchain.

Please have a look at those, and if there are questions file a new issue. Thanks!

**Comment by johnmcfarlane** [comment]
Hi @memsharded. Thanks for the info. 

Should [this page](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html) maybe also indicate that the feature should not be used? And can #6692 now be closed as obsolete?
