### ISSUE TITLE
Prescribe a single class name for recipes

### ISSUE THREAD

**Issue by thejohnfreeman** [conan-io/conan#5409]
This will have a few advantages:

- Simplifies the implementation of Conan. Instead of searching the module for a binding with a special type, just reference the exact expected binding.
- Simplifies the implementation of a Conan recipe. Instead of wringing my hands over "picking a good class name", I'll avoid the paradox of choice by having a prescription.
- Lets authors put recipe base classes in the same module, e.g. for `python_requires`, without hiding them behind a function like `get_conanfile`.

Yes, this will be a breaking change. I think it is ripe for Conan 2.0.

**Comment by jgsogo** [comment]
Hi, @thejohnfreeman , I think that any prescription should be just a recommendation. I'm not sure if it is a good idea to require that a class has a fixed name instead of checking the type, the second one is ensured by the language, so no human error is possible.

Also, the `get_conanfile` pattern for a `python_requires` is just a recommendation, you can use the same class for the `python_requires` package and for the imported class. There are no limitations on this and some people are already using it successfully.

I really think that prescriptions that cannot be ensured by the language could turn into an endless source of issues.

**Comment by thejohnfreeman** [comment]
The language does not guarantee that a binding that subclasses `ConanFile` exists in the module. *Conan's manual check* guarantees that. Not the language. I'm proposing that Conan change its check to pull a specific binding by name. Conan can still even check its type, if it wants to, even though that is not Pythonic either. Python uses [duck typing](https://en.wikipedia.org/wiki/Duck_typing): if it quacks like a `ConanFile`, then it's a `ConanFile`. Python discourages checking types. Just try to call the methods and access the attributes you need. If they're there, then who cares what the base classes are?

It's like the difference between calling a method on an object by name, and iterating over every method until we find one with the right signature. Or accessing an attribute on an object by name versus iterating over every attribute until we find one with the right type. No one does that. Just call the method or access the attribute by name. That's how we define interfaces. A Python module's interface is the names of its bindings, not their types. Conan is subverting the expectations of Python developers.

Even better, Conan could offer a main function that recipes call with the right class or object, instead of iterating over module bindings searching for it. Then users just invoke the recipe as a script. That's the most Pythonic technique.

`get_conanfile` is not just a recommendation. It is a requirement. Conan will trip on this:

```python
from conans import ConanFile

class RecipeForUsers(ConanFile):
    """This is the base class my users want to get from `python_requires`."""

class RecipeForThisPackage(ConanFile):
    """This is the recipe class for this package."""
```

I don't think a recommendation to follow not just Python best practices but general programming best practices can "turn into an endless source of issues". That's a hypothetical with no justification. What are the specific issues that could pop up? Again, Conan is already planning breaking changes for 2.0. It is the perfect time to correct this mistake.

**Comment by jgsogo** [comment]
I agree that now it is the perfect timing to take this kind of decisions, we can break _anything_ for 2.0, this is just my opinion and there are a lot of things to talk about in order to plan that major release.

IMO, relying on a name to identify which one is the `ConanFile` is not the way to go, I can't even imagine how to decide which one is the proper name for it.

If I had to put two _ConanFiles_ at the top level of a module and let Conan know which one is the _package_ `ConanFile` and which one corresponds to a `python_requiries`, I would vote to create classes with some custom implementations and rely on inheritance (lets say, a `LibConanFile`, a `PythonRequires`, a `HeaderOnly`,... all of them inheriting from a `ConanFile` parent class). For C++ developers I think it would be more natural than having different behaviors depending on the name of the class (we are not used to reflection).

Btw, when I said _ensured by the language_, I mean that a typo in the `ConanFile` id (`MyLib(ConanFi1e)`) will result in an import error, while a wrong name will just result in Conan not taking care of that specific class, but we cannot raise any error about it, we cannot know about the original intention of the recipe writer.

I've read some of your blogpost about standardizing a CMake+Conan packaging approach. Is this related to that? I would be interested to know why do you think this is needed. Thanks!

**Comment by thejohnfreeman** [comment]
Can't think of a name? Don't make it more complicated than it needs to be. Just call it `Recipe`.

This isn't C++. It's Python. Don't try to write C++ in Python. Write Python in Python. Developers can learn, even C++ developers. They're smart cookies. It's not a huge leap.

Even if you have multiple classes, if they all inherit from `ConanFile`, you *still* have the same problem! Re-read the example I wrote in [my last comment](https://github.com/conan-io/conan/issues/5409#issuecomment-506706995). It does exactly what you describe: "classes with some custom implementations and rely on inheritance (lets say, [a `RecipeForUsers`, a `RecipeForThisPackage`],... all of them inheriting from a `ConanFile` parent class)." Do you see? Conan's behavior has even confused you.

What I'm proposing does not allow different behaviors based on the name of the class. In this proposal, the class must always be named `Recipe`, and it always has the same behavior! *Conan as it exists today* is what lets you define a different named class in every recipe module, and use the same name in different recipe modules for different types.

```python
# package-a/conanfile.py
from conans import ConanFile
class MyRecipe(ConanFile):
    ...
```

```python
# package-b/conanfile.py
from conans import ConanFile
MyRecipe = 42
class PackageBConanFile(ConanFile)
    ...
```

You see? You should like this proposal, because it makes `Recipe` have the same meaning in every recipe module, and it makes every recipe module define a `Recipe` class. I'm proposing consistency, while Conan today does not have it.

A wrong name cannot be diagnosed? I'll need you to spell out an example. With this implementation for Conan, a missing `Recipe` *and* a `Recipe` with the wrong type are both diagnosed:

```python
def _parse_module(conanfile_module):
    try:
        if not issubclass(conanfile_module.Recipe, ConanFile):
            raise TypeError('Recipe is not a ConanFile')
    except TypeError:
        raise TypeError('Recipe is not a class')
    except AttributeError:
        raise NameError('class Recipe is missing')
    return conanfile_module.Recipe
```

This request is related to my project autorecipes. You can see that in my [`conanfile.py`](https://github.com/thejohnfreeman/autorecipes/blob/master/conanfile.py), I have to hide `CMakeConanFile` and `PythonConanFile` behind functions (a la `get_conanfile`) or within another module or prefix their names with `_`, because if I did not, then Conan would complain that my recipe has [`More than 1 conanfile in the file`](https://github.com/conan-io/conan/blob/develop/conans/client/loader.py#L241).

This proposal would make the implementation of [`_parse_module`](https://github.com/conan-io/conan/blob/develop/conans/client/loader.py#L225) that much shorter and easier to read (I already wrote it above), and it would make Conan more [Pythonic](https://www.python.org/dev/peps/pep-0020/).

**Comment by Minimonium** [comment]
Some thoughts. 
It was indeed confusing when I was just starting with Conan - does the Recipe name important. Should I encode the project name into the recipe class name? 
I was not the only one and some users from Slack experienced the same moment. 
Personally, I fall back to `ConanRecipe` name now every time. 
The non-breaking approach now could be to generate the default name on new recipes and allow Conan to search for the name first, check that it's a `ConanFile` subclass and fall back to the old behavior otherwise.

**Comment by memsharded** [comment]
Yes, I agree that it might be improved, and we could add some docs, checks and recommendations.

What it is impossible to do is to raise an error or relying in that being the mandatory name. That would break ALL the recipes in the world, for very little value, and even if in theory it is possible to break in Conan 2.0, we will definitely won't break all user recipes because of this.

**Comment by thejohnfreeman** [comment]
Is it impossible? Moving the `cppstd` setting to a subsetting of `compiler` was a breaking change, and it didn't even have to wait for 2.0. I think you have an existing deprecation / breaking change migration plan that this change could fall into like all the others. I'm prepared to wait, but I'd hate to see it written off completely.

Is there a way forward? How about this path: Give a warning to recipes that do not use the prescribed name. Fall back to existing behavior for them. Maintain this warning for one or more versions (however long you usually give, e.g. with the deprecation warning for `cppstd`). After enough time has been given for users to migrate, make the warning an error and remove the fallback behavior.

This is a very common, very popular migration plan. I think it can work here. Further, Conan might consider offering users a migration tool that will rewrite their recipe according to best practices, giving them a chance to review and accept the changes, or revert. This is another popular approach among software projects. Conan already migrates the settings file, for example.

**Comment by memsharded** [comment]
> Moving the cppstd setting to a subsetting of compiler was a breaking change, and it didn't even have to wait for 2.0.

No, it was definitely not breaking change. Users can keep their old global cppstd and keep working perfectly, both their recipes and profiles created with conan 1.0 will still work in latest conan 1.X. It is a new feature, a new alternative that users can decide to use it or not. 

> Conan already migrates the settings file, for example.
Conan only increases the settings file, if it detects that no change to the default was made, otherwise it leaves it untouched. So it never breaks users either.

We can start introducing checks and recommendations, but forcing this naming convention won't happen at least until conan 3.0, definitely not in conan 2.0. The amount of recipes out there is huge, it doesn't matter how many helper tools are provided, it will be a huge pain, so it should only be done for huge gains. So far we are doing way more complicated and valuable things with tons of extra effort to not break users and to not break them in the future. I am sorry but so far there is not enough evidence that this one deserves this massive breakage.

**Comment by thejohnfreeman** [comment]
Do we at least agree that this was a mistake in the design? Or do we not agree on that?

**Comment by memsharded** [comment]
Sure, it was probably a reasonable thing and non relevant detail at all when it started, and now it seems that it would have been better with other approach. A mistake at that time? It was impossible to foresee the amount of dynamic behavior that was going to be developed on top of the basic behavior, things like python_requires were not even a thought. The ``python_requires`` feature was introduced in Conan 1.7, when the stability commitment of 1.0 was already done.
