### ISSUE TITLE
conanfile.py is silently deleted by "conan create" in local "source" cache

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#5415]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I have Conan 1.16.1 installed on Windows 10.

I used the same example as in https://github.com/conan-io/conan/issues/4013.

Clone the test repo:
```
git clone https://github.com/db4/conan-scm_test.git
```
Execute

```
conan create . demo/testing
```

When looking into the source folder in the local cache, I get the following output of `git status`:

```bash
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    conanfile.py

no changes added to commit (use "git add" and/or "git commit -a")
```

So the removing of the `conanfile.py` leads for our automatic version numbering detection (based on `git describe --dirty`) to an dirty working copy.
What is the reason to remove the `conanfile.py` from the git source folder? All other files in our packages are always still there.

**Comment by jgsogo** [comment]
As you can see [here](https://github.com/conan-io/conan/blob/b6840ccfb53c1d0a38eec9f75df5caa8fd8aad5d/conans/client/source.py#L244) we are not sure about it, we have marked it to review for Conan 2.0, but as this issue has arised, we should investigate if it is possible to keep the `conanfile.py` in the source directory without breaking any workflow.

Nevertheless, any dynamic value in your recipe should be resolved during the `export` stage, can I see that `conanfile.py` to understand why are you calling `git` in the sources folder and check if it is possible to resolve that value during the export.

Thanks

**Comment by climblinne** [comment]
For automatic builds it would be fine to just generate the version number by Conan. The problem is, that when somebody build it locally, the version number would stay at the "timeslot", when we call `conan install`. So no detection for a dirty version locally. That's the reason, why we always have a prebuild script in our main projects, which check the current status of the git repo and generate a version header.

**Comment by jgsogo** [comment]
> That's the reason, why we always have a prebuild script in our main projects, which check the current status of the git repo and generate a version header.

Yes, I think this is a legit use case, and I agree that we should investigate if it is possible to not remove the `conanfile.py`. Let's allocate time for that.

**Comment by climblinne** [comment]
@jgsogo: Can I support here for this ticket?

**Comment by jgsogo** [comment]
If you want to submit a PR it will force us to have a look at it and see if any test fails (we should think about other use cases that might not be considered in the tests). After that, we would be sure if we can add it to 1.x or we need to wait for 2.0.

**Comment by planetmarshall** [comment]
> 
> Nevertheless, any dynamic value in your recipe should be resolved during the `export` stage, can I see that `conanfile.py` to understand why are you calling `git` in the sources folder and check if it is possible to resolve that value during the export.
> 
> Thanks

We are also being hit by this issue, not because we are calling git ourselves but because it is done indirectly using one of [Ryan Pavlik's CMake modules](https://github.com/rpavlik/cmake-modules).

**Comment by jgsogo** [comment]
Hi, @planetmarshall! Can you elaborate a little bit more on the issue with those CMake modules? What are they calling `git` for?

**Comment by planetmarshall** [comment]
> Hi, @planetmarshall! Can you elaborate a little bit more on the issue with those CMake modules? What are they calling git for?

They use git to make various source control data available in CMake cache variables, such as the branch and the commit SHA. This is not unusual usage for CMake based projects - OpenCV does the same.

**Comment by jgsogo** [comment]
I'm adding this to Conan v2.0 because this is something we need to check not after that, as it is stated in the comment line. We can investigate it before, but there are too many things to do for the next releases and there is no strong evidence that this is affecting many users (up to now).

We think that when you are using Conan that kind of information is something that the package manager has to provide to the build system, so Conan should get that information from Git and feed the build system with it. For example, if we are taking the version from the Git tag, Conan needs to know it in order to work with the proper reference, or to store the commit SHA in the `scm` dictionary.

This call to `git` is something you need or just something that Ryan Pavlik's CMake modules are doing? Are you actually using the information they retrieve from Git? (can you point me to the sources in the repo?)

**Comment by lexknuther** [comment]
This is preventing me from using cmake-conan since we are calling conan_cmake_install with PATH_OR_REFERENCE set to ./conanfile.py.  It looks like all you'd have to do is remove CONANFILE from the list of removed files.  All the other files are actually automatically generated.  Indeed the TODO comments like '# TODO: Why removing in the cache? There is no danger.' seem to indicated that the author was just as confused as I am.

**Comment by lexknuther** [comment]
Apparently, this change is related to #1717 and  #1720

**Comment by memsharded** [comment]
The ``scm`` has been deprecated in 1.X, replaced by the new flow (https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature), and removed in 2.0. Conan will no longer have the chance to remove files from user space, closing this ticket as solved.
