### ISSUE TITLE
Using Conan to deploy compiler toolchains?

### ISSUE THREAD

**Issue by BlamKiwi** [conan-io/conan#543]
With Conan its possible to create packages that contain libraries, headers and executables. It would be a desirable feature to be able to use this to deploy a particular compiler toolchain (such as LLVM or GCC) from a package and use it as the compiler for a CMake project. This would allow developers to test their code with different compilers and not have to affect their regular build chain. We can successfully package LLVM and have it downloaded by conan as a regular package. The package even works, using the compiler binary directly to build projects. 

If there was a way for conan to be able to apply the package concept to compilers, and have it be automatically integrated into CMake (or other tools), this would make conan a very invaluable tool. 

This is a summary of what we have been able to do so far:
- Add a toolchain package to our conan server, and update our conan file for the desired buildchain as a dependency. 
- Manually set CMAKE_CXX_COMPILER/CMAKE_C_COMPILER to point to the binary in the conan package. 
- Conan automatically picks up the standard library implementation as part of the lib filter for the package. 
- Add the standard library header locations as SYSTEM headers in CMake. 

The only issue we are stuck on is getting conan to be able to pick the compiler for CMake. Obviously you cannot run the conan step of CMake without first setting the compiler. So the compiler picking step would probably need to be supported by the conan tool itself. If conan was able to have a package aware version of the "system-alternatives" system in linux, this would work quite well. 

I could imagine a system working something like this:
- Binaries in conan packages can be anonated to declare that they are a "c compiler" or "c++ compiler".
- Conan exposes conanc and conan++ as executable smlinks in the filesystem.  
- Conan is extended with the ability to update this smlink `conan update-alternatives conanc++ LLVM-4.0`
- Conan downloads the package if required to the usual place.
- Conan updates the symlink to point to the new package binary. 

Conan has already helped us greatly by making our build process become more independent of distro repositories. The compiler itself is kind of the last step for self hosting conan build system.

**Comment by memsharded** [comment]
Hi @BlamKiwi ,

Thanks for your feeback, very glad that conan helped you in your build process!

Yes, that is true, the progress so far is that of packaging the tool, like MinGW for Win: http://docs.conan.io/en/latest/howtos/create_installer_packages.html

The feature that is missing would be the integration of the compiler, so far has been done with env variables CC, CXX,  manually by the user, but there are feature requests to integrate that too: 

- Profiles: https://github.com/conan-io/conan/issues/524 (those will include paths to compilers, which is related).
- Setting the compiler from settings: https://github.com/conan-io/conan/issues/271
- https://github.com/conan-io/conan/issues/199

I agree that is a desirable and requested feature. Will try to finish a little nightmare we have right now with Windows builds using ``ConfigureEnvironment`` (damn Win command line and batch syntax), and probably will be the first feature to address for next iteration. Thanks for your feedback!

**Comment by memsharded** [comment]
Hi @BlamKiwi,

I think this issue has been resolved since then, by different features, mainly:

- Profiles (http://docs.conan.io/en/latest/mastering/profiles.html)
- ``build_requires``. http://docs.conan.io/en/latest/mastering/build_requires.html
- Management of environment variables: http://docs.conan.io/en/latest/mastering/envvars.html

Check for example, how the Android toolchain is installed via a conan package and applied to cross-build different C/C++ libraries, in a decoupled way: http://docs.conan.io/en/latest/howtos/cross_building.html#android


I think this issue has been resolved, so it can be closed, but please ask any further question or re-open if necessary. Thanks!

**Comment by basejumpa** [comment]
Most recent links are dead. Here the currently working ones:

* Profiles (https://docs.conan.io/en/latest/reference/profiles.html)
* `build_requires` : https://docs.conan.io/en/latest/devtools/build_requires.html
* Management of environment variables: https://docs.conan.io/en/latest/mastering/envvars.html

Cross-building: https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#cross-building-with-conan

**Comment by memsharded** [comment]
yeah, that last comment was 2017, so many things changed since then.

Actually, it would be better to focus on the new tools that are 2.0 ready:

- Tools that should be used in recipes: https://docs.conan.io/en/latest/reference/conanfile/tools.html
- Management of environment variables: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html
- Migration guide to be 2.0 ready: https://docs.conan.io/en/latest/conan_v2.html
