### ISSUE TITLE
short_paths component is not used from c:\.conan

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#544]
I'm having a component with a very long name component where I need to put `short_paths = True` to be able to build it. If I do `conan export test` for this component it gets exported to `c:\<User>\.conan\data`. I then do `conan install ... --build=VeryLongComponentName` and it gets built in `c:\.conan\temp...`. This is probably what's expected (is it?).

I then have another component with a normal short name where I would like to use the long-name component. Problem is if i do `conan install ... --build=ShortComp` it installs the long-name-comp in `c:\<User>\.conan\data` and uses it from there. My compiler then gets problems with some of the headers that are included because the path limit is exceeded.

'c:\<Users>\.conan\data\...VeryLongName...\packages\...hash...\include/ThisGetsIncludedByShortNameComp.h(4): fatal error C1081: "c:\<Users>\.conan\data\...VeryLongName...\packages\...hash...\include\ThisGetsIncludedByLongCompHeader.h": Filename too long.'

Hope it's clear what's the problem, tried to give as much info as possible. Just ask if there's something unclear.

Microsoft is still living in the 80ies I guess...

**Comment by memsharded** [comment]
Totally clear. Yes, the behavior is expected.

When we implemented the short_paths solution, we decided to go just for the ``source`` and ``build`` folders, because those were the only ones that were failing and we were not reported by any project having issues with the export or the package. 

The export is from files that are typically in a folder which length is larger than the actual conan local cache, so this shouldn't be an issue. 

About the ``package`` folder, I see it is an issue for your use case, the bigger problem so far was the nested folders in the conan local cache from the package recipe + the lengthy sha1 hash folder. I think there were some reason for not shortening the ``package`` folder too, but I will have a second look.

**Comment by monsdar** [comment]
Yeah, I'm probably the first with a component name that long... It's one of those cases where someone wanted to make very clear what the component is doing - resulting in something like `ThisLibraryHelpsToCatchDivisionByZeroAndGivesSpanishOutputOnHalloween`... I'm wondering how close we've been to the path limit before using conan, must've been just a few characters 0.0

**Comment by memsharded** [comment]
Urgh, java like! LOL
I like the python policy: short names for packages, files/modules, large for symbols like classes and functions.
Don't worry, we'll have a look to check if we can do that.

**Comment by memsharded** [comment]
Sorry, was referencing bad issue, such PR do not address this isssue. I am working on it but it will be a different PR.

**Comment by memsharded** [comment]
I have been checking this issue. It doesn't look good.

The thing is that the ``package`` folder is used in many different contexts, as opposed to the ``source`` and ``build`` folders, that are using just in the install. But the most important thing is that the ``package`` folder is used in many places where the ``conanfile.py`` is not loaded/evaluated. And we need it to get the ``short_paths`` field value. 

As an example, when we run conan search, it just check for packages, but it does not require to load the respective ``conanfile``. This would be worse in the servers, to do a search in a remote, like conan.io, we would need to load the ``conanfile`` which is an important security issue.

We could maybe just parse/regex the conanfile for the value of ``short_paths``, but in any case it is a complicated feature, it will require a very large time investment to implement it. I keep working on it.

**Comment by monsdar** [comment]
I probably can work around this problem by setting the conan data directory to something like `c:\.conan`. That way I have the user directory out of the way and probably get back under the path length limit.

Unfortunately this just delays the problem until someone comes up with an even longer package-name than I have.

**Comment by memsharded** [comment]
We are on it. Been several hours, keep working on it. We don't want it to be a stopper if we can avoid it. Keep tuned :)

**Comment by memsharded** [comment]
Ok, so I have found a solution, just implemented and running tests. It implements it for the ``package`` folder.

But I read in your other thread, that you are not using the ``source()`` method, you are just embedding the sources in the package recipe, with ``exports``, right? And it didn't fail to properly export the recipe? Where the path length within limits, and the problem appeared just for the package, due to the ``package/long_sha_here`` subfolder?

**Comment by monsdar** [comment]
Right, I'm not using `source`, my sources are located along with the `conanfile.py` and will get exported. I just tried to make sure, exporting works without problems. Building worked too (it uses short_pathes for that).

The path to the package (including long_sha) has 156 characters in total. The path to the include file in that package has 240 characters (shouldn't the limit be around 255?), including filename.

**Comment by memsharded** [comment]
Ok, then it will be fine. Tests are already passing, so I think this will made into conan 0.14 next week, and you will be able to manage :)

About the 240 chars, sometimes it counts escape characters, don't know why, but seems to scape the ``\`` windows path backslash in the character count (maybe a python path implementation issue)

**Comment by memsharded** [comment]
Fixed in #563, will be released in conan 0.14

**Comment by monsdar** [comment]
Just tested it, works without problems now.
