### ISSUE TITLE
Parse dependencies versions from another file. 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#5445]
Hello,

Is there a way to fetch dependencies versions from a separate files? 
For instance, we can parse the conan package version from cmake as explained here [capture_version](https://docs.conan.io/en/1.4/howtos/capture_version.html)

I tried the same logic with requirements, something like
```
    def parse_from_file(package):
         versions = tools.load("deps.cmake")
        // some logic ..
        return version

    def requirements(self):
         self.requires('deps1/{version}@me/testing'.format( parse_from_file('deps1') ) )
         self.requires('deps1/{version}@me/testing'.format( parse_from_file('deps2') ) )
```
However this does not work, is this even feasible and do you recommend any alternative way to achieve this.

Thanks

**Comment by memsharded** [comment]
Hi @boussaffawalid 

Why wouldn't it work? I think you need to correctly parameterize the function, and not load always "deps.cmake", but load different files:

```python
    def parse_from_file(filepath):
         versions = tools.load(filepath)
        // some logic ..
        return version

    def requirements(self):
         # assuming files name "deps1" and "deps2"
         self.requires('deps1/{version}@me/testing'.format( parse_from_file('deps1') ) )
         self.requires('deps1/{version}@me/testing'.format( parse_from_file('deps2') ) )
```

In any case, I would recommend if possible trying to revert the situation. Let conan (the package and dependency manager) define the versions that you want, and if that information needs to be passed to
the build system, like cmake, pass it (via variables of the ``CMake`` build helper, via an auxiliary cmake file...)

**Comment by boussaffawalid** [comment]
That was just a pseudo code to illustrate what I want to achieve.

Basically, I’m trying to support building with and without conan, and to avoid having this duplicated versions  information in conanfile.py and CmakeList.txt, I choose to define the versions in a sperate file, for example deps.cmake, this file will be consumed by both cmake and conan.

The I issue I had with conan is that deps.cmake is not accessible in the conan requirement method

**Comment by memsharded** [comment]
But do you have it in your project, close to the conanfile.py? Have you done the `exports = "deps.cmake"` so the file is there? I think I am missing some context, please tell.

**Comment by boussaffawalid** [comment]
Yes I do have deps.cmake next to my conanfile.py
But it is not exprted, I will try to add it to the export list

**Comment by boussaffawalid** [comment]
Still it cannot find the file. 
Here is what I did:

Here is my conan workflow:
```
cd <build dir>
conan install <source dir> 
```
<source dir>  is the directory of the conanfile.py

My guess that it cannot find it because the current work directory *(cwd) is <build dir> however the file is in <source dir>.

and unfortunately the conan self.source_folder attribute is not accessible inside the requirements method

**Comment by memsharded** [comment]
Because in the local flow the layout might be different, indeed, and the ``exports`` do nothing, as exports is only when moving things to the local cache to create a package, but not used in the local flow.

Yes, the source_folder is for sources only, when it needs to build from sources, but the requirements need to be resolved even if you are using a precompiled binary, and the sources are not needed. Thus, the files to be used in ``requirements()`` method have to be there, besides the ``conanfile.py``, not only in the source folder. The layout has to be the same, when in the local flow or when creating a package in the cache.

This is why I am recommending to let Conan define the versions you need, and pass that information to the build system (if necessary at all, in general the build system should be good with the include folders, library names, etc, knowing the versions of the dependencies is usually not necessary)

In any case, with the correct layout, it is possible, there is no difference doing this than getting the version: https://docs.conan.io/en/latest/howtos/capture_version.html#how-to-capture-package-version-from-text-or-build-files, and I have done recipes that get the requirements information from a plain text file, so it is definitely doable. If you want to setup a Github repo with a simple proof of concept of this, I can try to help there.

**Comment by boussaffawalid** [comment]
@memsharded  here is a repo that illustrate the issue

https://github.com/boussaffawalid/conan_demo

**Comment by memsharded** [comment]
Thanks that was very useful.

You can build paths relative to the conanfile.py in pure python:

```python
def requirements(self):
        path = os.path.join(os.path.dirname(__file__), "deps.cmake")
        versions = tools.load(path)

        # just a dummy parser
        zlib_v = versions.split(' ')[2]
        print('parsed zlib version: {}'.format(zlib_v) )

        self.requires('zlib/{}@conan/stable'.format(zlib_v))
```

This seems to work both in the local flow and for ``conan create`` flow, please try and tell me. Thanks!

**Comment by AbrilRBS** [comment]
Closing as solved with newer Conan versions. Layouts, and even the `conandata` feature help a lot with this
