### ISSUE TITLE
Need to copy test sources in test_package

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#546]
When I run a `test_package` I would like to be able to copy some tests from the main package to  `test_package/build` and then run them to validate the build.  Currently I'm cloning the Git repo again but since it's a fairly large Git repo so I'd like to avoid it. I know the sources are available in the local Conan package repo because `test_package` does a build from source first.  It would be nice if there was a way to copy sources in the test package's `source` method like in the main package's `package` method.

**Comment by memsharded** [comment]
There could be a problem. ``test_package`` does the build from source by default, but it can be skipped, just to test pre-built packages, both local or retrieving them from remotes:

```bash
$ conan test_package --build=missing  # also --build=never
```
This command will override the default (``--build=MyPackage``) build from source, and try to use prebuild binaries, only building them from sources (``--build=missing``) or aborting with error (``--build=never``)

If it is a matter of speed, maybe doing a ``git clone --depth=1`` could help (most likely you already know it, but just in case). I think it might be possible to grab only some files with something like ``git archive --remote=<repo_url> <branch> <path> | tar xvf -``

If not enough, maybe the new (from 0.13) ``source()`` command could help, but seems a bit tricky. Could you please outline what would be the expected interface from the ``test_package/conanfile.py``. Please consider that it can have more than 1 dependency. Thank you!

**Comment by sourcedelica** [comment]
While running `test_package` I did a bunch of `build=none` because I only wanted to build and run the tests that I had copied manually.  But I knew the source was there from the previous time I did a full build with `test_package`.  

Ideally I could call a function that gives me read only access to the build directory for a specific requirement (typically the only requirement of the `test_package`) but only if there is a build that matches the settings that I used to run the `test_package`.  If the build is not there it would raise an exception or return `None`.  It's possible that the build directories are meant to be ephemeral.  Once I have a handle on the build directory I can navigate to where I cloned the project.

I haven't worked with `git archive` - I will have to try that out.  I also haven't played with `git clone --depth 1`.  My concern is that I want access to a particular tag.  I can experiment.  If it seems like something that is too obscure then I understand.  Cloning works, it's just slow.  And I found I needed to iterate a number of times to get the `test_package` working.

**Comment by memsharded** [comment]
It is a few lines, but indeed possible and effective:

```bash
git init myrepo
cd myrepo
git remote add origin <url>
git config core.sparseCheckout true
echo your/partial/folder >> .git/info/sparse-checkout
git pull origin yourbranch --depth 1
```
The ``echo`` might use quotes, just make sure that inside the ``sparse-checkout`` file it is stored without quotes. You can just write to that file with python too, instead of echo.

In conan source, could be like (not tested):
```python
from conans.util.files import save
self.run("git init myrepo")
self.run("cd myrepo && git remote add origin <url>")
self.run("cd myrepo && git config core.sparseCheckout true")
save("myrepo/.git/info/sparse-checkout", "your/partial/folder")
self.run("cd myrepo && git pull origin yourbranch --depth 1")
```

This will download just the desired files from that folder, from the desired branch/tag, with no history at all. It will allow to run full package tests for pre-built packages in a clean machine, where there will be no ``source`` neither ``build`` folders, so it will work for all cases. And I think it will be more robust than implementing such a copy from the local cache. What do you think?

**Comment by sourcedelica** [comment]
Works like a charm!  Very nice.  That will come in handy in a bunch of projects actually :)

Thanks!

**Comment by sourcedelica** [comment]
Actually - one other related question, in the docs it says that `test_package` shouldn't have all of your unit tests, so I'm wondering what tests you recommend it should have.  I'm assuming it should have enough tests to make sure that all of the pieces are there, (headers and libs).  But I'm guess it should be more of a smoke test?

**Comment by sourcedelica** [comment]
Here's the implementation of your approach.
https://github.com/sourcedelica/conan-recipes/blob/master/caf/test_package/conanfile.py#L23

**Comment by memsharded** [comment]
Well, it can have all of the unit tests if desired, and if they are exposed through the package (library) API, which in many cases won't be true. IMHO, my approach is:

- Full unit tests in the development cycle of the library, while adding features, fixing bugs, etc, re-running the full functional tests to ensure the **functionality** of the code is working. They would typically be normal gtests, cmake ctests, etc. in the normal develop-build-test cycle. If desired to be automated in CI, they could be run them inside the conan ``build()`` method, after the build, as a final build step.
- Package tests, in conan, to ensure that the package is correctly linked and working. Your approach about making sure that the "pieces" are there is just right. I would write a few tests to ensure that all my artifacts (a package might have several libs inside), are both correctly linked and executed at runtime (sometimes it links but due to differences in the ABI, like debug/release, it crashes at runtime). The invocation of a very few of the core functionalities of the library is more than enough.

**Comment by sourcedelica** [comment]
Cool - thanks!
