### ISSUE TITLE
bash completion for conan

### ISSUE THREAD

**Issue by agentdouble** [conan-io/conan#5483]
Hello, 
I'm a regular user of conan for both personal and professional projects.
Conan is an awesome tool. I want to thank the conan community for all the hard work you have done.

Since I'm typing a lot of conan commands I wrote a bash completion script of conan commands to increase UX experience. I don't think this feature exists so I cleaned my script and published it to my gitlab.
You can check it there and test it if you want to.
https://gitlab.com/akim.saidani/conan-bashcompletion

At work we are using it, I hope it will enhance your conan experience too and feel free to give me some feedbacks.

**Comment by uilianries** [comment]
related issue: https://github.com/conan-io/conan/issues/4507

**Comment by memsharded** [comment]
Hi @akanegally 

This is fantastic job, thanks very much for sharing!

Honestly, we did close https://github.com/conan-io/conan/issues/4507 mostly because it is about built-in autocompletion, and that is some extra complexity and burden we cannot afford right now.

But having it external/decoupled, I think it would be very interesting for some users. At least lets find some good place to link it from the conan docs or something like that. I'll check with the team what would make sense. Thanks again!

**Comment by akanegally** [comment]
Hi @memsharded, thank you for your answer.  
I agree with you for #4507 : a built-in completion using argcomplete will defnitely add some extra complexity. 
To be honest, at first I considered using argcomplete but I found it less 'responsive that built-in bash functions. Mostly due to the fact that python program can have huge startup time.
Moreover, I checked how other popular tools like "pip" and "docker" handle bash completions. Both use an external bash completion script.
It's actually interesting the way they link the life-cycle of their tool with the completion feature.
For instance, pip is able to generate the bash completion script using a command line :
"pip --bash-completion >> /etc/bash_completion.d/pip-completion"
The generation uses a script template so new commands are automatically handled. 
https://github.com/pypa/pip/blob/master/src/pip/_internal/commands/completion.py

On the other hand,  the docker team  provide a link to a static bash completion script for each version of the client.
The script is stored as a third contribution to the project
https://github.com/docker/docker-ce/tree/master/components/cli/contrib/completion/bash

Of course, what 'pip' or 'docker' do are just suggestions.
I think it will be great to have something like this for conan. 
It will helps the user to have the best completion script for a specific version of conan without being to much intrusive into the conan developpement workflow.

**Comment by lasote** [comment]
Hi! I took a look at the script, it is quite amazing the job you did!
I was wondering if we could easy the maintenance of the autocompletion script if it could leverage from the "conan --help" and the subcommands "--help" based on the python argparse. Is this project intended for that, correct? `https://argcomplete.readthedocs.io/en/latest/`. Maybe, if the code of the autocompletion is less "hardcoded" we could consider to maintain it in the code base.

**Comment by lasote** [comment]
By the way: https://github.com/conan-io/docs/pull/1425

**Comment by akanegally** [comment]
Hi @lasote , thank you for your feedback.
I think we can definitely ease the maintenance of the automation script using conan help output.
For exemple, for each command we need to know the following informations :
- subcommands (if any)
- positionnal, boolean and map  arguments
All these informations are already stored in variables and I think it can be parsed from help output 

Thougth I'm not sure how argcomplete is gonna help. Can you elaborate on this point ?

Nonetheless, I've created a request on my project and will think of a way to ease the maintenance 
https://gitlab.com/akim.saidani/conan-bashcompletion/issues/24

**Comment by memsharded** [comment]
Checking https://gitlab.com/akim.saidani/conan-bashcompletion, it seems at this point the effort and maintenance would be too high, and there would be many other higher priorities. I am closing this as not planned at the moment, we will re-open if at some point this can get some attention. Thanks!
