### ISSUE TITLE
[Feature Request] Use zstandard in addition to gzip

### ISSUE THREAD

**Issue by mietzen** [conan-io/conan#5538]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

After a quick look at the code of conans/util/files.py I think it would be easy to implement this. Is there any reason why you picked gzip over zstd? Especially for bigger artifacts zstd is faster and has better compression.

**Comment by danimtb** [comment]
HI @mietzen and thanks for the suggestion!

I don't know why gzip was used over zstandard, maybe because gzip is a built-in function? Maybe zstandard does not have support for `mtime=0` https://github.com/conan-io/conan/blob/1.17.2/conans/util/files.py#L276 ??

Anyway, I would like to know the reason behind this request change. Are you experiencing any trouble with the current implementation? Could you please give an example of the issue?

Normally the download takes longer than the compression/decompression and we know that Conan will benefit from paralllel donwloads as described here #1012

**Comment by danimtb** [comment]
closing this due to incativity

**Comment by Morwenn** [comment]
I guess that one argument that could be made for zstd is that for the same speed you could compress more, which would in turn make upload and download faster. Every article I've read so far seems to mention zstd as being a better alternative with no major downside (save for availability and the need adapt the existing code to use it of course).

**Comment by memsharded** [comment]
Yeah, at some point we will probably use this, but at the moment we have too many other way more critical things.

**Comment by Morwenn** [comment]
Oh, considering the current backlog I'm not surprised; you're totally right to prioritize most common feature requests and issues above this :)

**Comment by grossag** [comment]
A coworker and I are investigating adding zstd support to conan. I was going to file a new issue but he found this. Should I include my proposal here or should I file a new issue?

**Comment by memsharded** [comment]
Hi @grossag 

This ticket is too old. ``xz`` support for ``tools.files import unzip`` is already there. Are you talking about this?

**Comment by grossag** [comment]
@memsharded Sorry, I wasn't clear enough! We are looking into doing zstd compression for the actual Conan packages uploaded to Artifactory (e.g. having `conan upload` produce a `.tar.zst` file instead of a `.tar.gz` file). We want to speed up decompression of Conan packages for developers.

**Comment by memsharded** [comment]
Oh, I see.
This was discussed in the past, the ticket is https://github.com/conan-io/conan/issues/648, please have a look

We decided to not move it forward, the data didn't show impressive advantages over gz compression, and the fact that Python doesn't have built-in/truly portable zstd implementation is a big blocker in practice. It is also something more challenging than it could seem on the surface, as the filenames like ``conan_package.tgz`` are kind of hardcoded in some places.

Future optimizations will most likely try to improve parallelization (download + unzip can already be parallelized), rather than trying to change the compression algorithm
