### ISSUE TITLE
[Question] Surprising behaviour with upstream revisions vis-a-vis re-building

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#5567]
We have a `dowstream` recipe, with `upstream` as requirements.

Our Conan clients and server have revision enabled (we froze to v 1.15.0 a few weeks ago, you guys are quick updaters ; ).

We updated `upstream` recipe keeping the same version, thus creating a new recipe revision on the server.

Now, we build `downstream` with:

    conan install downstream --update --build=outdated --profile custom-profile

Looking at the logs, as expected `upstream` is rebuilt on the client, because it detected that the new revision was available. Yet, Conan did not rebuild `downstream`:

> downstream/1.0.0@com/test: Already installed!

Is it the expected behaviour? Is not that surprising, since the documentation states that with revision enabled, the latest revision will be used (when the requirement does not explicitly specify a revision, which is our case)

**Comment by jgsogo** [comment]
It is the expected behavior because nothing has changed related to your `downstream` package:
 * same recipe revision
 * same package ID, and it is already compiled

If you want to trigger a new build for the `downstream` in that scenario you need the package_id to depend on the revision of the `upstream` requirement (or anything that changes given your scenario). This is something you can get changing the _versioning schema_ to `package_revision_mode()` (it will get a different package_id for any change in the full reference including package revisions) ([docs](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#versioning-schema)).
