### ISSUE TITLE
[suggestion] Use pyproject.toml PEP 518 for Conan 2.0

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#5577]
To help us debug your issue please explain:

Hi!

Since [PEP 518](https://www.python.org/dev/peps/pep-0518/), Python is able to use a unique file for setup and requirements, which is great. On my last Python meetup it was showed as a natural evolution of setup.py and requirements.txt.

I think we could use this feature + [poetry](https://poetry.eustace.io/) for Conan 2.0 where Python3 should be the default one.

There is a short explanation on [black](https://black.readthedocs.io/en/stable/pyproject_toml.html) docs.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment]
I am not opposed to update to new tools, as long as they do not add extra steps to the current setup. I am concerned that tools like poetry will add extra layers, not that mainstream in the python community, and certainly unknown to most C++ developers. We will have a look for Conan 2.0, when we close on the python versions to be supported.

**Comment by Behemyth** [comment]
A transitional feature might be supporting conanfile.txt listings in the pyproject.toml file.

A pyproject.toml table might look like this:
```
[tool.conan.requires]
Poco = "1.9.0@pocoproject/stable"
zlib = "1.2.11@conan/stable"
```
...foregoing any other build system usage just yet.

**Comment by uilianries** [comment]
Hi @Behemyth the idea about this issue is related to replace setuptools + setup.py + requirement, not the conanfile.txt.

I would say for conanfile.txt we should open a new issue, since it will demand  extra effort.

**Comment by memsharded** [comment]
Some quick feedback about poetry. I was using it recently, and it was less straightforward, and still a bit unstable. It failed in different places, I needed to figure out workarounds.... doesn't seem ready for me.

**Comment by Behemyth** [comment]
Poetry hit 1.0 on Dec. 12th and might have addressed any stability concerns.

**Comment by memsharded** [comment]
After checking this a little bit more, I'd say to stay with the current setup:

- It seems pyproject.toml doesn't support the ``pip install -e`` case, that we use a lot
- In many cases, it needs an extra tool (poetry) in order to work, and that is inconvenient for our non-python-expert users
- Our current setup has been actually working very nicely without any issue for the last years. As we don't have "build-tools" (one of the apparent benefits of pyproject.tom), it seems we are relatively ok
- Our resources are limited, this is yet another thing to change, debug, iterate and support, better focus on 2.0 on Conan functionality, not this infra.

We can always revise this later, post 2.0, but atm I am closing it.
