### ISSUE TITLE
Ability to test python_requires package

### ISSUE THREAD

**Issue by maikelvdh** [conan-io/conan#5584]
It seems to be not trivial to test a package for a python_requires Conan recipe. The problematic part seems to be that the python_requires are resolved before the conanfile.py is parsed.

The reference of the item under test should likely be exposed before the actually `python_requires()` is loaded, e.g `import package_under_test` would already be helpful.

**Comment by memsharded** [comment]
Yes, this is an issue. The inversion of control that ``python_requires`` implements makes many things way more difficult. Not only testing, but also internal Conan development.

We are currently investigating ways to recover direct control of python_requires, which looks promising. We will be testing them, hopefully before Conan 2.0.

**Comment by maikelvdh** [comment]
Is there already a way to achieve this somehow on the current version before 2.0 will arrive? Any smart trick to do this?

**Comment by memsharded** [comment]
Hi @maikelvdh 

That is the thing, I don't think it is possible. The current model is using full inversion of control, it is the python interpreter who is executing the ``python_requires()`` function, which internally will be loading the dependencies modules, and returning them. 
Also, take into account that all the ``test_package`` current functionality is oriented to testing packages, while ``python-requires`` doesn't have packages at all, they are pure python code recipe, which are only "exported", but not "created". They don't have settings or any binary package. 
This is also general for recipes, you cannot "test" recipes with conan, only their resulting packages. Are you trying to do some kind of "unit testing" of recipes?

**Comment by maikelvdh** [comment]
Correct! Basically I would like to be able to test the `python_requires()` code within the development workflow of such python code recipe, to ensure that all abstracted functionality is working as expected.

**Comment by Setre14** [comment]
Hi, is there any update on this issue?

**Comment by memsharded** [comment]
Hi @Setre14 

Unfortunately not. I have also been checking this in 2.0, to see if it was more feasible, but it isn't, without a big investment.
This happens for example, because the ``test_package`` infrastructure might not be enough to test a ``python_require``, as it is not a full recipe, for example, extending a base class, or testing ``package_id()`` and ``package_info()`` functionality. In order to be able to test completely a ``python_requires``, full reusage is necessary.
So at the moment, python_requires need to be exported first, then reused by another package conanfile.py in order to test it. It is possible to have such a testing project ``test_pyrequires`` besides the ``conanfile.py`` of the ``python_requires``, then something like:

```bash
conan export .
conan create test_pyrequires
```

As this sounds more a UX/UI improvement, it doesn't seem critical core functionality for 2.0, so I think it can be moved to 2.X to think later about it.

**Comment by Setre14** [comment]
@memsharded Thanks for the update.

**Comment by stefansli** [comment]
@memsharded We successfully used a test_package to test one of our python base recipes. The only problem we had was how to inject the tested version into the test_package recipe. As a workaround, we generated a local file containing the version which we then read while the test_package is parsed

**Comment by memsharded** [comment]
This was made possible, built-in in Conan 2.0, closing as solved.
