### ISSUE TITLE
How to update local package with conan server

### ISSUE THREAD

**Issue by deekshith-elear** [conan-io/conan#5586]
Hi I was using conan io official remote server, I have doubt that How can I update my local cache packages with remote server, 
Can any one help me out to solve this issue.

**Comment by memsharded** [comment]
Hi @deekshith-elear 

Sorry, we don't have enough information. Do you mean the old conan.io server? That was deprecated like two years ago? Which version of Conan are you using? Do you want to install packages from conan-center? If it was a long time since you used Conan I would suggest a fresh start. Install latest Conan, remove your old ``<userhome>/.conan`` folder, and start from there.
