### ISSUE TITLE
Commit to conan-eigen overwrote package with different contents

### ISSUE THREAD

**Issue by spiderkeys** [conan-io/conan#5605]
Referencing: https://github.com/conan-community/conan-eigen/commit/2acc6acd3259af6fc7c76beada087e5f2fc52579

The above commit resulted in the contents of newly built packages containing different contents, which we noticed when we re-ran an old build that had previously succeeded and the new build failed.

Because of the way the install/copy steps changed, the contents of the include directory changed.
From commit: 6730c09
```sh
ls  ~/.conan/data/eigen/3.3.7/spiderkeys/test/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/eigen3/
Eigen  signature_of_eigen3_matrix_library  unsupported
```
From commit: 2acc6ac
```sh
ls ~/.conan/data/eigen/3.3.7/spiderkeys/test/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/eigen3/
Eigen
```
Our project depended on some of the contents in the unsupported folder, which caused the breakage. This was a bit surprising, as I wouldn't expect package contents to change for the same hash.

**Comment by memsharded** [comment]
Hi @spiderkeys 

Thanks for the report. 

Right now, the current conan-center is not using revisions. The binary-ID corresponds to a certain configuration, in this case, the only configuration available because it is header-only and all the configurations will resolve to the same binary-ID. When changes are done in recipes in conan-center with the same version and same configuration the resulting binaries are overwritten. This will probably change in the future, but right now is the current model.

So I think it is not a conan bug, and I think you should file an issue to that Eigen repository, so the recipe is fixed to package that ``unsupported`` folder too and a new binary is generated and uploaded.

Does this help? Please tell me if this issue could be closed, thanks!

**Comment by spiderkeys** [comment]
Hi @memsharded,

My bad, you are right; I meant to raise this on the bincrafters/community repo. I will close here and re-open there :slightly_smiling_face: 

Thanks
