### ISSUE TITLE
[suggestion] Provide list of python packages to be installed in virtualenv_python

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#5616]
I commented the same on issue [#5157](https://github.com/conan-io/conan/issues/5157#issuecomment-520786304), but thought I should create a dedicated ticket to request this feature.

I'd like to be able to specify a list of python packages which will be installed (using pip) in `virtualenv_python`.  We have conan pkgs which are dependent on several python packages which each have their own secondary python package dependencies. We have been struggling for some time on how to solve this. We don't want to install them to the system in case any other projects are using different versions of the python packages.

Ideally, something like:

```
generators = "cmake", "virtualenv", "virtualenv_python"
virtualenv_python_packages = (
    "requests/[>2.1]",
    "lxml/[>3.5]"
)
```

If two conan pkgs use incompatible versions of the same python package, the `install` should probably fail.

It would also be nice if the installed python packages could be added to the dependency graph, to have a complete view of dependencies.

**Comment by memsharded** [comment]
As much as I would like to be able to approach this problem I am afraid it is impossible.
Python dependency management is a huge topic by itself. It is a very large ecosystem, with many people working on it, and dedicated projects and teams to different tools like Pipenv or Poetry. And it is still not a solved problem. 

It is completely out of our scope and resources to consider it. Also consider other implications:

- Conflicts must fail, there is not other possibility. It is not possible to spin out a new different python virtualenv for each recipe. Furthermore each recipe needs to be evaluated in isolation, so it is not possible to resolve to a common valid dependency in a range, if a recipe uses lxml/>3.5 and that resolves to 3.8, if other conan recipe declares lxml/>3.5<3.7, it will already fail, it is not possible to backtrack and find 3.6 as the common one satisfying the constraints. 
- What happens if a recipe declares they want to use ``requests==2.2``, but the underlying Conan interpreter is already using a different requests versions (it will in most cases). Basically, trying to use any other version different to the installed ones will already be a conflict. This will change in every different OS and distro, as they might be resolving to different dependencies versions.
- What happens to bundled Conan installations (the ones that can be installed in Windows, Linux, etc, and come with a python interpreter bundled). This mechanism wouldn't work at all, as it is not possible to install packages in those interpreters.


The feature https://github.com/conan-io/conan/issues/5157 is not about installing python packages,  or even creating any kind of python virtualenv. It is a Conan virtualenv, which are just activate/activate scripts, but no python interpreter at all.

While I totally understand your pain, and would like to help (for myself too!) with it, it is not possible, so the best I could suggest now would be:
- Use python native tools to deal with python native dependencies.
- Maybe, at some point you might find it convenient to abuse Conan a bit, and use ``system_requirements()`` in some of your recipes to manually invoque such native tools (Pipenv, Poetry), as a thin automation and integration wrapper over it

Thanks for your suggestion!

**Comment by GordonJess** [comment]
Thanks a lot for your detailed reply - makes a lot of sense.  I'll look into your suggestions and let you know if I come up with anything!  I'll close this ticket now.

**Comment by GordonJess** [comment]
@memsharded,

While I accept there are still a whole range of other challenges you've already mentioned, I hope you won't mind elaborating a bit on this comment:

> It is not possible to spin out a new different python virtualenv for each recipe

What would be the main issue with this approach?  It would allow me to avoid installing system wide, and let each recipe be in control of it's own environment.  Am I missing something?
