### ISSUE TITLE
[question] install multiple packages in the cache

### ISSUE THREAD

**Issue by bmanga** [conan-io/conan#5627]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.18.1.

Hi, I was wondering if there is a way to install a list of packages without generating any files. The use case is to pre-build a series of packages so that when `conan install` is run for the project they are all already in the cache. Thanks!

**Comment by Minimonium** [comment]
Install by a full reference does exactly that (but `deploy` is running though). 
If you have a local recipe you can do `conan export .` on it and the do `conan install reference` for it. Or simply `conan create .` for each profile you need.

**Comment by jgsogo** [comment]
As @Minimonium says, the best you can do is (with the limitations mentioned):

```
conan install <reference> [--profile <your-profile>]
```

Is it valid for your use case?

**Comment by bmanga** [comment]
Yes I was aware of using a reference, but I was interested in installing all the references from a conanfile (or similar) so that conan would resolve and install all packages to compatible versions but would not generate any build files.

**Comment by jgsogo** [comment]
No, not directly, right now for a local conanfile (you could write a plain `conanfile.txt` with all the references you need) Conan will always generate some files in the install folder... because I assume you don't want to create a fake recipe with its own reference and declare all your packages as requirements so you can run `conan install <my-fake-recipe-reference>`. Thats the only thing that might work.

There is a feature request here that might solve your problem (https://github.com/conan-io/conan/issues/5545), but it is still not added to a release.

**Comment by bmanga** [comment]
@jgsogo that would be what I had in mind! I gave that issue a thumbs up :). I guess this can be closed.
