### ISSUE TITLE
MSYS2 and cmake_installer issues

### ISSUE THREAD

**Issue by Ignition** [conan-io/conan#5663]
This issue is that cmake_installer is providing a windows binary of cmake, but the `cmake_paths` generated by conan provides MSYS2 based paths. This causes cmake not to be able to find the libraries.

Can't use a MSYS2 version of cmake becuase it can't generate Visual Studio projects.

Not sure how to proceed.

**Comment by jgsogo** [comment]
Hi, @Ignition. Can you provide more information related to the error? I'm sure there are people currently using the `cmake_installer` for Windows successfully.

Thanks!

**Comment by Ignition** [comment]
The issue is with being within MSYS2. 
We are using python3 within MSYS2 `pacman -S python3 python3-pip`, along with conan `pip3 install --upgrade conan`. This means conan generates unix paths. The cmake_installer provides a windows version of CMake which does not understand these paths. So when we do stuff like :
```
include(${CMAKE_BINARY_DIR}/conan_paths.cmake) # fine - windows path
include(${CONAN_CATCH2_ROOT}/Catch.cmake) # not fine - MSYS2 unix path
```
We get CMake errors becasue the paths are alien.

**Comment by SSE4** [comment]
that's due to the python difference between MSYS python and native Windows python builds:
```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.sep
'\\'
>>> os.path.sep
'\\'
```
```
Python 3.7.2 (default, Dec 26 2018, 08:10:46)
[GCC 7.4.0] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.sep
'/'
>>> os.path.sep
'/'
```

**Comment by jgsogo** [comment]
I think I still need more information about this issue to understand what is happening here, also I need to know if this is a common use-case or something not working for a one-off.

Up to my understanding:
 * `Conan` runs inside msys2, so it is generating unix-like filepath in the CMake files (which settings/profile are you using?)
 * `CMake` runs in native Windows and consume the Conan generated files to create the VS solution.

I assume you run Conan inside msys2 because you need to generate some packages that will be consumed by the VS solution. The alternative would be to run a job with Conan inside msys2, share the cache with a Conan running in Windows and then use this last one to generate the VS solution consuming the packages previously generated.

Is this more or less what you are trying to do? Thanks!
