### ISSUE TITLE
Upgrade from Conan 1.18.1 to 1.18.2 breaking recipe revisions?

### ISSUE THREAD

**Issue by ssrobins** [conan-io/conan#5694]
I've been using `CONAN_REVISIONS_ENABLED` with `revision_mode = "scm"`:
https://gitlab.com/ssrobins/conan-sdl2

When upgrading from Conan 1.18.1 to 1.18.2, I now get this error when running conan install:
```
ERROR: Failed requirement 'sdl2/2.0.8' from 'conanfile.py'
ERROR: Unable to find 'sdl2/2.0.8#69c21e066605654a91aa48560889ada1b5e3913a' in remotes
```

But that revision was published to the remote:
https://gitlab.com/ssrobins/conan-sdl2/pipelines/76474068

When I downgrade back to Conan 1.18.1, everything is fine. The docs mention it was experimental and that it might break, but I'm curious if it's expected? Maybe related to https://github.com/conan-io/conan/pull/5671?

**Comment by jgsogo** [comment]
Hi, @ssrobins!

#5671 was fixing a bug, up to Conan `v1.18.1` packages without _user/channel_ were being uploaded as `None/None` values, we considered it a bug and now they are uploaded with `_/_` (it is the representation on disk we had chosen for those `None`).

The problem is that you CI is uploading the packages using Conan v1.18.1 (you get `None/None` in bintray) and you are trying to consume them using Conan v1.18.2 where this was fixed. New version looks for `_/_` and fails.

You need to upgrade Conan version in your docker images.

Thanks

**Comment by ssrobins** [comment]
After re-running the CI to rebuild and push the packages with Conan 1.18.2, all is good. In the future, it would be helpful if the changelog called out breaking changes like that, even with experimental features. No big deal though.
