### ISSUE TITLE
[question] cmake.configure() pathing issues

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [conan-io/conan#5711]
I am running into a conflict between using `conan create ..` and `conan build ..` which I am sure is due to me writing bad conanfiles.

We use a git repo for our source, i.e.
_def source(self):
    git clone ssh://git@url:foo.git
    cd foo && git checkout development_

The build method:
_def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()_

Ideally, we want to use `conan build ..` to build/package local code changes (i.e. no conan source call). And then `conan create ..` on our CI server to export and upload the package.

The issue is that the `create` ends up calling build from outside of the source folder, where no CMakeLists.txt exists.

How do I tell `create` that it needs to move into the source folder?

**Comment by jgsogo** [comment]
Hi, @Mirko-von-Leipzig 

Your use case is quite common, and you are not the only one having problems with the `create/build` commands. Once you get, it is easy, but we know it adds some friction and we are working to improve the developer experience (not even a POC I can link here yet).

The toy project we are autogeneration with `conan new hello/1.0` is very similar to your use case. This is the `conanfile.py` for it (I've stripped non-relevant parts):

```python
from conans import ConanFile, CMake, tools

class HelloConan(ConanFile):
    name = "hello"
    version = "1.0"

    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = "shared=False"
    generators = "cmake"

    def source(self):
        self.run("git clone https://github.com/conan-io/hello.git")
        # This replacement is needed if your sources are not prepared for Conan
        tools.replace_in_file("hello/CMakeLists.txt", "PROJECT(HelloWorld)",
                              '''PROJECT(HelloWorld)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()''')

    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder="hello")  # <- For your use case, this should be `source_folder="foo"`
        cmake.build()
```

* It works with `conan create .` out of the box
* For local development you need to explicitly set some folders. Starting in the folder where the `conanfile.py` is, these commands will work:
   ```bash
   ⇒  mkdir build && cd build
   ⇒  conan install ..
   ⇒  conan source ..
   ⇒  conan build .. --source_folder=.
   ``` 
   If you want to use different directories, all local commands (`source`,  `build`, `package`) accept arguments for `source-folder`, `build-folder`, `package-folder`and `install-folder`, you can inspect what they can be used for in docs or reading the help from each command.

**Comment by Mirko-von-Leipzig** [comment]
Maybe I'm missing the obvious. I'm still struggling. Using `cmake.configure(source_folder="foo")` lets `conan create .. foo/bar` complete successfully.

However, the `conan build .. --source_folder=.` still fails - the `cmake.configure(source_folder="foo")` is effectively adding `foo` to the specified source path. In my case running `conan build .. -sf ../..` is successful. This is however quite surprising as the sequence of commands is then (from project root)
`mkdir build && cd build`
`conan install ..`
`conan build .. -sf ../..` # -sf is one level above root now
`conan package ..` etc

Is that just a limitation of having the conanfile.py and CMakeLists.txt on the same level?

**Comment by jgsogo** [comment]
Hi, @Mirko-von-Leipzig. It all depends on how you are organizing your repository and the relative path from your `conanfile.py` and the root `CMakeLists.txt`. 

The path you are using in `cmake.configure(source_folder="foo")` is resolved as (for the `conan build` command):

```
[[<cwd>/]<source-folder>/]foo
```

but it is important to take into account that **the package has to work when building in the Conan cache** (that's the reason why the [test_package](https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html#conan-test) tests use the actual package). This is very important because, in the cache, the `conanfile.py` and the exported sources go to different folders.

From the answers, I think that your project layout should look like this toy repo I've prepared: https://github.com/jgsogo/5711-conan-project-layout
 * it works with `conan create <path/to/conanfile.py> issue/testing`
 * it also works with:
   ```bash
   git clone https://github.com/jgsogo/5711-conan-project-layout
   cd 5711-conan-project-layout/conan
   mkdir build && cd build
   conan install ..
   conan build .. -sf=../../foo
   ```

   So, yes, the `--source-folder` for the `conan build` will be different regarding your project layout and the current working directory.

We are aware that this is a bit inconvenient and we are trying to improve what we know as _"developer experience"_, it will require a complete refactor of current local commands, probably breaking, so it is something that should wait for Conan v2.0

**Comment by Mirko-von-Leipzig** [comment]
Okay thank you! That makes a lot of sense.
