### ISSUE TITLE
Imports copy behavoir

### ISSUE THREAD

**Issue by Phibedy** [conan-io/conan#573]
Why is `self.copy()` in `imports()` called after the imports method has finished?
I would like to call some binary that should be copied but I can't as it won't be there.
Related to: https://github.com/memsharded/conan-protobuf/issues/5

In addition it does not copy files into the build directory (it just says it in the console and creates the directories)

**Comment by memsharded** [comment]
It is designed that way for optimization. The imports() operation is a very slow one, and some users have requested some speed-ups, especially when they have large caches. Gathering all patterns and lazily executing them at once when the ``imports()`` is finished, can highly reduce time. It is not implemented yet that way internally, but the flow is already defined for this purpose.

About the second issue, do you mean the build directory of a user project? Or inside the build folder of the conan cache? For the build folder of the local cache, they are actually copied for building, then removed, as it doesn't make sense to re-package them again, they are already in other package, which is already a dependency of the given one, so that would be duplicating the artifacts.

**Comment by Phibedy** [comment]
Ah ok thank you, didn't know that.

I am calling `conan install ..` in my build directory and include the conan-cmake file like done in the example.
In that case, the build function is never called. So I can't execute imported binaries. Is there a way to call the build method as if the conan file sets some some attributes, they have to be typed in manually.

**Comment by memsharded** [comment]
If I understood you, you can execute the ``build()`` method of a project (not exported into the local cache) ``conanfile.py`` with:

```bash
$ conan build
```

It has no arguments, because it will take them from the temp files generated at ``conan install``. If you want to have available in the build command, it is necessary to use the ``text`` and ``env`` generators, that generate files with all the install data so it can be used at build command. You can specify both in your project conanfile, or as command line parameters:

```bash
$ conan install -g=txt -g=env
```

Is this what you need? Please tell me.

**Comment by Phibedy** [comment]
Thank you, I was looking for `conan build` :)
What is the beste way to look up things like "How does copy work". I had a look at the src but didn't find the copy method.
(this issue could be closed)

**Comment by memsharded** [comment]
Hi @Phibedy , 
There is no best way to look up these things other than reading the code. We try to continuously improve the docs, but we can hardly keep the pace with development and user support.
In any case, don't hesitate to ask us, here, in twitter, by email... we will be happy to comment and explain about the conan internals and design decisions.
Thanks!
