### ISSUE TITLE
[question] python_requires and deprecation of CONAN_USERNAME and CONAN_CHANNEL

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#5731]
_Originally posted by @Johnnyxy in https://github.com/conan-io/docs/issues/1368#issuecomment-515905595_

Hi there,
if ```CONAN_USERNAME``` and ```CONAN_CHANNEL``` are removed from Conan 2.0 is it possible to retrieve the username and channel outside of the class that inherits the ConanFile-class?

This would be important for ```python_requires```:
```python
_t_name = 'tlib'
_t_version = os.getenv('TLIB_VERSION', '0.0.0')
_t_user = os.getenv('TLIB_USERNAME', os.getenv('CONAN_USERNAME', 'user'))
_t_channel = os.getenv('TLIB_CHANNEL', os.getenv('CONAN_CHANNEL', 'testing'))
_t_reference = '{name}/{version}@{user}/{channel}'.format(name=_t_name, version=_t_version, user=_t_user, channel=_t_channel)
_tlib = python_requires(_t_reference)
```

**Comment by jgsogo** [comment]
Hi, @Johnnyxy, I've copied your comment from one issue in the docs repo. There are some problems associated to `python_requires` and the way Conan is handling them. I've just created a project in this repo to gather together issues related to that problem.

With the current implementation, what you pointed out it is indeed a problem, but if Conan is the one executing the `python_requires()` it should no longer be a problem (you would be able to get the user/channel like you would do for any other requirement).

**Comment by memsharded** [comment]
It seems this will not be possible. As ``python_requires`` are loaded even before the ``user`` and ``channel`` are assigned, it is impossible to do this. Then I think this issue can be closed.

In any case @Johnnyxy, the usage of user/channel in this way is no longer recommended. In the past, using channels for promotions and introducing this variability seemed to made sense. But since then we learned that it is better to have packages immutable (always same user/channel), and do promotions copying packages from one server repo to another. Conan 2.0 has already removed the ``conan copy`` command, for example, and is also making the channel optional (allowing user, but not channel)

**Comment by Johnnyxy** [comment]
It is okay, as this was based on the legacy python_requires feature.
