### ISSUE TITLE
dotenv generators

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan#5733]
I wish for equivalents to `virtualenv`, `virtualbuildenv `and `virtualrunenv` generators which do not create a script to run in the shell, but rather create plain text files that look like: 
```
ENV_VAR=ENV_VAR_VALUE
OTHER_ENV_VAR=OTHER_ENV_VAR_VALUE
```

My current purpose for this is to allow a Conan plugin for an IDE to be able to run a target in a conan virtual env programmatically.

See conan-io/conan-clion-plugin#61

**Comment by danimtb** [comment]
Hi @Lawrencemm,

I understand the issue as a need for the clion plugin. We haven't explored this approach before but maybe it is useful.

I think this could be very well done as a POC with a package generator to see if it fits in the plugin side. WDTY?

**Comment by Lawrencemm** [comment]
Right, generator packages are a thing, didn't think of that. Will see what I can do.

**Comment by jgsogo** [comment]
Hi, I opened this issue https://github.com/conan-io/conan/issues/5821 (and a project) to gather all the requests related to _virtualenvs_ in their different flavors. This issue is totally aligned with what we want to do (I will create a PR soon), I'm going to close this one so the conversation doesn't get diluted in different places.

And don't hesitate to provide feedback if you create the POC. 😉
