### ISSUE TITLE
"conan info --update" reads only from local cache

### ISSUE THREAD

**Issue by Grumpy7** [conan-io/conan#5738]
When calling "conan info --update" on a local conanfile with non-fixed versions, it returns the latest version satisfying the package requirements only from the list of installed packages in the local cache. 
Removing all local package versions does return the latest available version from remotes.
"conan install --update" does work as expected, regardless of the local cache contents. 
The current workaround is to always call "install" before "info". However, it's a tad annoying.

Using W10 (1903), conan 1.15.1

**Comment by memsharded** [comment]
Hi @Grumpy7 

I have reviewed the PR https://github.com/conan-io/conan/pull/5745, and even if I agree that the semantics are not the best, changing that might be breaking documented behavior.

> -u, --update Check updates exist from upstream remotes

It checks if they EXIST, but nowhere it says it will install and update them.

The info command is informational, it will produce the least changes it can to the conan cache. Fetching non-existing packages is necessary, to be able to parse them, but otherwise, it probably shouldn't be used to update the current installation, that will not be "information" anymore.

I wouldn't have much problem in changing it, I agree the semantics might not be very clear, but I know that there were users relying and using this functionality. You should probably rely on ``conan install`` only, the ``conan info`` command is intended for user occasional feedback, not in the main flow, so it shouldn't be a huge problem.

And in anycase, I would be fine with either:

- Adding a new argument that will force the update while calling ``conan info``, like ``--update-recipe``
- I think this should be changed and improved in Conan 2.0, when we can break.

**Comment by Grumpy7** [comment]
Hi @memsharded 

The current issue is the following:
      Package versions on remote:
         1.3.0
         1.2.0
         1.1.0
     Locally installed package versions:
         1.2.0
         1.1.0       

If my Conanfile contains a reference to version [^1.0.0], conan info --update, it returns 1.2.0 (highest in cache) instead of 1.3.0 (highest on remote).
The issue is that I DON'T WANT to install and update and I DON'T WANT to modify my local cache. However I MUST to call "conan install --update" before "conan info --update" in order to get it to return 1.3.0.
The problem is that is does not behave as documented - it does not tell me if any updates exist on the remote, it just tells me my highest local cache version.

**Comment by jgsogo** [comment]
Hi, @Grumpy7 

You are right, `conan info <conanfile> --update` doesn't look for newer versions in the remote. 

I've run this test to check it:
 * Using this _conanfile.py_:
   ```python
   from conans import ConanFile

   class MyLib(ConanFile):
       requires = "zlib/[>=1.2.8]"
   ```
 * `conan remove zlib/1.2.11` (just in case)
 * `conan install zlib/1.2.8`
 * `conan info conanfile.py --update`, nothing about the 1.2.11 version available in the remote.
   ```
   Version ranges solved
       Version range '>=1.2.8' required by 'conanfile.py' resolved to 'zlib/1.2.8' in local cache

   zlib/1.2.8
       ID: f74366f76f700cc6e991285892ad7a23c30e6d47
       BuildID: None
       Remote: conan-center=https://conan.bintray.com
       URL: https://github.com/conan-io/conan-center-index
       Homepage: https://zlib.net
       License: Zlib
       Recipe: Cache
       Revision: 0
       Binary: Cache
       Binary remote: conan-center
       Creation date: 2019-10-09 14:20:35
       Required by:
           conanfile.py
   conanfile.py
       ID: d3cb35098bed776c3c7b6c348a6c30ac27a7423b
       BuildID: None
       Requires:
           zlib/1.2.8
   ```
 * `conan install conanfile.py --update`, it retrieves the 1.2.11 version.
   ```
   zlib/1.2.11: Not found in local cache, looking in remotes...
   zlib/1.2.11: Trying with 'conan-center'...
   Downloading conanmanifest.txt: 100%|##########| 302/302 [00:00<00:00, 610kB/s]
   Downloading conanfile.py: 100%|##########| 7.47k/7.47k [00:00<00:00, 9.73MB/s]
   Downloading conan_export.tgz: 100%|##########| 276/276 [00:00<00:00, 919kB/s]
   Decompressing conan_export.tgz: 100%|##########| 276/276 [00:00<00:00, 206kB/s]
   zlib/1.2.11: Downloaded recipe revision 5f4917ce0a630b102f472afd00102d40
   Version ranges solved
       zlib/* versions found in 'conan-center' remote
       Version range '>=1.2.8' required by 'conanfile.py' resolved to 'zlib/1.2.11' in remote 'conan-center'

   conanfile.py: Installing package
   Requirements
       zlib/1.2.11 from 'conan-center' - Downloaded
   Packages
       zlib/1.2.11:f74366f76f700cc6e991285892ad7a23c30e6d47 - Download
   ```

We should take into account the comment by @memsharded. If we check the remote and use the new version, we would need to install it in the cache in order to parse the recipe and resolve the new graph... and then the new version will be available and it will be used by Conan unless the user provides a graphlock generated with the old version. So, running `conan info --update` may change the cache and subsequent commands, unless we revert the cache to the previous state.

I think we need to **do something for Conan 1.x**. Alternatives:
 1. Remove the `--update` argument from `conan info` help if it does nothing 
 2. Change/Fix the behavior: it will download the new recipe. It shouldn't be a big deal if we think that other projects using the same Conan cache may modify the cache and _my project_ could resolve a different version_range if installed again (lockfiles for the win!). For sure, it shouldn't modify any local file.

Depending on the resolution, we may need to fix/improve the situation for Conan 2.0.

**Comment by jgsogo** [comment]
⚠️  Sorry, I was misunderstanding the meaning of the help string. When it says _"Check updates exist from upstream remotes"_ it refers to **newer versions of the recipe or the binaries**, not to new versions in the sense of library-version.

So, _version-ranges_ only add noise to this issue: I agree that the different behavior between `install --update` and `info --update` could be an issue (not strictly what we are investigating here).

Probably the main issue here is about docs/help: it is not clear the intention of the `--update` argument. I'm going to doublecheck that it behaves as expected.

**Comment by jgsogo** [comment]
Hi, I'm running a test that should check what we are talking about here, see it in the following PR: https://github.com/conan-io/conan/pull/5911

(failing assert is marked in the snippet)
```python
    def test_update_recipe(self):
        server = TestServer(users={"user": "password"})
        t1 = TestClient(servers={"default": server}, users={"default": [("user", "password")]})
        t2 = TestClient(servers={"default": server}, users={"default": [("user", "password")]})

        ref = ConanFileReference.loads("name/version@user/channel")
        t1.save({"conanfile.py": GenConanfile().with_name("name").with_attribute("url", "first")})
        t1.run("create . {}".format(ref))
        t1.run("upload {} --all".format(ref))

        # Consume the package using the client t2
        t2.save({"conanfile.txt": "[requires]\n{}".format(ref)})
        t2.run("install .")
        t2.run("info . -n url")
        self.assertIn("URL: first", t2.out)

        # Create a new version for the recipe
        time.sleep(1)  # Make sure the new timestamp is later
        t1.save({"conanfile.py": GenConanfile().with_name("name").with_attribute("url", "second")})
        t1.run("create . {}".format(ref))
        t1.run("upload {} --all".format(ref))

        # Info should retrieve the updated information
        t2.run("info . --update -n url")
-->>>   self.assertIn("URL: second", t2.out)

        # After installing again, the newer recipe is available
        t2.run("install . --update")
        self.assertIn("name/version@user/channel: WARN: Current"
                      " package is older than remote upstream one", t2.out)
        t2.run("info . -n url")
        self.assertIn("URL: second", t2.out)
```

Please, @Grumpy7, confirm this is the issue you are referring to. Thanks!

**Comment by clayhill** [comment]
Quick question: are the reasons given above for not fetching a newer version from the remote with `conan info --update` the same for `conan graph --update`? We're running into identical problems and are looking for a solution that hopefully does not require `conan install`.

**Comment by jaques-sam** [comment]
> 
> 
> Quick question: are the reasons given above for not fetching a newer version from the remote with `conan info --update` the same for `conan graph --update`? We're running into identical problems and are looking for a solution that hopefully does not require `conan install`.

And furthermore, from the documentation it looks like `conan graph` works like a dry-run `conan install` ([as explained below for the `build` parameter](https://docs.conan.io/en/latest/reference/commands/misc/graph.html)). So for consistency, the `update` parameter should also work the same way, as one would expect.

**Comment by harsszegi** [comment]
Any update on this? This still appears to be broken. What is the canonical way of checking whether a given package already existing in the cache has a fresher version in the remote? (Without conan install)

**Comment by memsharded** [comment]
> Any update on this? This still appears to be broken. What is the canonical way of checking whether a given package already existing in the cache has a fresher version in the remote? (Without conan install)

Hi @harsszegi 

There is no way to check all installed packages in the cache against new versions in the servers. If you want to check what is in the servers, the way to go is ``conan search pkg/* -r=server``. This issue is not related to new versions, but modified artifacts of the same version (manifest changed). This will no longer be a thing with revisions enabled (the default for Conan 2.0), as changes in a recipe or source code will create a new recipe revision. Also, this only applies for current dependencies, not for any arbitrary package installed in the cache.

**Comment by harsszegi** [comment]
Thanks @memsharded , just a quick question. I wanted to use ‘conan info’ to figure out the exact resolved version for an alias package.
What should I use instead to figure out whether a.) the given package is available in the cache and b.) what is in the cache is the latest available in the remotes as well.
Thanks!

**Comment by memsharded** [comment]
The ``--update`` logic has been completely revamped in Conan 2.0, I am closing this as outdated, but please create new tickets as necessary for issues or questions about this, thanks!
