### ISSUE TITLE
Generate files recording the current reference

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#5744]
The general idea is to generate a `conan.ref` and `conan_package.ref` files (names to be determined) together with the other files like the `conan.lock` and so on.
This would be used to improve several situations. 
The first one is to pass the created ref to upload #5743  (https://github.com/conan-io/conan/issues/5197)

Please, @memsharded, this is a `look into` for this release, try to document here more details of the feature and in which other situations it will help having these ref files.

**Comment by memsharded** [comment]
The 2 scenarios it would be useful are:

- conan create & conan upload
- conan install (generate conan.ref file), later the conan.ref file is used as input in subsequent calls (like local conan build, conan package, conan export-pkg, conan test, conan alias, conan imports). Some of these might become even more necessary if they start computing the graph again, using the lockfiles: it is necessary to have the current reference to define in the lockfile the current node.

In the first scenario, ``conan create``, the problem is that some extra arg, like ``--ref`` is needed, right now it doesn't write any files, besides the lockfile, and only if ``--lockfile`` is used. This extra arguments looks a bit ugly?

In the second scenario, ``conan install``, there is usually a install folder (except for ``conan install <ref>``, but that is not a problem, because the ``<ref>`` is there already. The following commands, specially the local flow, would read the ``conan.ref`` file automatically, in the same way they would read the ``conan.lock`` file automatically, to use the same information that was used at ``conan install``.

Indeed the feature would generate 2 files:
- ``conan.ref`` containing the ``pkg/version@user/channel`` of the package
- ``conan.pref`` including the ref and the ``package_id``, only for ``conan create``

In the case of ``conan create``, both could contain revisions, but in the ``conan install`` case, it wouldn't, as the revisions are not defined locally. It seems that commands that use this info should be prepare to handle both with and without revisions.

In the case of ``conanfile.txt``, it seems ``conan.ref`` doesn't make a lot of sense, probably no files should be created.

**Comment by lasote** [comment]
> In the first scenario, conan create, the problem is that some extra arg, like --ref is needed, right now it doesn't write any files, besides the lockfile, and only if --lockfile is used. This extra arguments looks a bit ugly?

It is not pretty, definitely, but we need something.

**Comment by memsharded** [comment]
Lets explore if using a lockfile could be better and more generic

**Comment by memsharded** [comment]
Solved with ``PackagesLists`` in Conan 2.0
