### ISSUE TITLE
[bug] Conan supports empty user/channel, but throws on access

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#5749]
> I'm not sure what's the motivation for it right now that we can use references in the name/version@ form. Is it safe to omit that? It throws an Exception on inspect.getmembers otherwise and I'd like to avoid it.

Needed for https://github.com/conan-io/hooks/pull/76

**Comment by jgsogo** [comment]
I see the problem with the hook, but not the solution proposed in #5750, I think that the exception is important.

You can try to implement the hook with ``conanfile.__dir__()`` instead of the ``inspect.getmembers``, it is uglier, but it doesn't execute the property block (not sure about how much protable is accross different Python versions).

Let me know what you think, and feel free to move the discussion to the hook (just ping me).

Thanks!

**Comment by Minimonium** [comment]
Since the throwing behaviour is not a bug - I'll close the issue
