### ISSUE TITLE
Custom Authorizer plugin in conan_server

### ISSUE THREAD

**Issue by pleroux0** [conan-io/conan#5758]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Even on the develop branch, one needs to modify the `conans/server/launcher.py` to use a custom Authorizer. The BasicAuthorizer requires that all users' read and write permissions need to be coded into the `server.conf` file.

Adapting the code to use a custom authorizer is trivial. However, it would be much more convenient if one can use an authorization plugin, similar to how one would use an authenticator plugin, to handle the authorization.

Is something like this on the roadmap? Or is there a technical reason why this functionality is lacking?

**Comment by uilianries** [comment]
Hi @pleroux0 !

What kind of authorizer do you need? Some time ago I made one for LDAP:

https://docs.conan.io/en/latest/uploading_packages/running_your_server.html#authentication

> The BasicAuthorizer requires that all users' read and write permissions need to be coded into the server.conf file.

This is the regular flow, otherwise any user would be able to overwrite any package. For example, the user `foo` can write all packages `*/*@foo/*` by default.

> Is something like this on the roadmap? Or is there a technical reason why this functionality is lacking?

No because we see Artifactory as a best option, since the admin is able to manage all users individually. BTW, do you have some restriction to use Artifactory?

**Comment by danimtb** [comment]
The documentation of the authorization plugin for conan server can be found here https://docs.conan.io/en/latest/uploading_packages/running_your_server.html#authentication

For more fine-grained authorization settings I'd suggest you to try Artifactory CE for C/C++ free version with support for Conan repositories: https://conan.io/downloads.html

**Comment by pleroux0** [comment]
Thanks for the responses.

You are both referring to the Authenticator, but I want to extend the Authorizer. It is already an abstract class, but there is no way to extend it with a plugin. The server (without modifying the source code) always uses the BasicAuthorizer.

I already have a custom Authenticator which calls an internal rest endpoint to determine if a user is who he says he/she is. I want to do the same with the Authorizer allowing a call to be made to an internal endpoint to determine whether an authenticated user can read/write to a package.

As for not using Artifactory: I'm running a single virtual machine which everything needs to run on. The docker.bintray.io/jfrog/artifactory-cpp-ce image is over 800MB and uses more than a GB of RAM. A minimal conan_server docker image is under 100MB and uses just over 50MB RAM with two gunicorn workers. It is purely for cost-saving reasons. If cash were not an issue, I'd use a paid Artifactory instance, but that is not currently a practical option for me.

**Comment by danimtb** [comment]
Thanks for the clarification @pleroux0, now I understand the issue.

I am sure you know it but just in case, you can tune the package permissions in the configuration file or the server for write and read permissions: https://docs.conan.io/en/latest/uploading_packages/running_your_server.html#permissions-parameters

Anyway, now the issue is clear and it would require to implement the same plugin approach for the Authorizer that the Authenticator already has 👍

**Comment by uilianries** [comment]
@pleroux0 thanks for your clarification.

Now I see your point. We need to add hook for the Authorizer. I think it's not too complex to be done.

**Comment by pleroux0** [comment]
Thanks again.

In the meantime, I'll use the `server.conf` file for setting permissions, but having an Authorizer plugin will be ideal.
