### ISSUE TITLE
Generator needs to read a file next to the conanfile.py

### ISSUE THREAD

**Issue by rweickelt** [conan-io/conan#5759]
I am using Conan to install dependencies of a project and to generate build system files. I am not using it to build an actual package. Thus, I am only executing `conan install . -o opt=value ...` and nothing else.

I have written a custom generator that needs to read a file sitting next to the conanfile.py. The generator lives in a separate Conan package that my project depends on.

- How can I access this file from the generator if the file name is known in the conanfile?
- Is there a way to set the path to this data file from the conan command line during `conan install`?

**Comment by danimtb** [comment]
Hi @rweickelt,

I am not sure if I understood your case correctly but AFAIK the generators do not know the path of the *conanfile.py*. The main purpose of generators is to translate the information of the graph that Conan creates to the build system language.

I am not sure if the file next to the  conanfile you are talking about is the conanfile of the generator or the one of the consumer.

For the first case, the most common use case is to export a template file with the generator and use it later to create the content of the generated file like this: https://docs.conan.io/en/latest/howtos/custom_generators.html#using-template-files-for-custom-generators

Fo the latter, I think it is not possible.

Is that your use case? if not, could you explain it further? thanks 😄

**Comment by rweickelt** [comment]
Thanks for your reply.

my project folder contains:
- conanfile.py
- config.yml.tpl
- many many source files, build system files, etc.

conan install:
- shall read the config.yml.tpl from the project folder
- shall generate a config.yml by injecting information from the conan dependency graph into config.yml.tpl

The reason is that users run conan install quite often, but config.yml.tpl contains a lot of custom information. If I would do it the other way around (i.e. let conan install just create a basic config.yml and then enrich it with user data), then I would need to modify the build system. But I don't have any control over that, so I thought I let the generator do it.

**Comment by danimtb** [comment]
Ok, thanks for the clarification.

AS I replied later, the location of the sources is not directly available to the generator, the only location you can check is `self.output_path`, that points to the installation folder https://docs.conan.io/en/latest/reference/generators/custom.html#output-path

If you use always the same relative path for installation you could guess the path to the *config.yml.tpl* or try to figure it out accessing from the generator to ``self.conanfile.source_folder^^ but I haven't tried and actually don't know if that is possible

**Comment by memsharded** [comment]
Hi @rweickelt 

The purpose of generators was always to contain information just about dependencies, but not about the current package, this is the reason it cannot access that local path. You are trying to do build configuration at a step that was originally intended just to install dependencies, but not to configure your build.

There is ongoing work if you want to follow it, to generate toolchains (from a ``conan install``) files, this would be probably the place, such a task would be done: https://github.com/conan-io/conan/issues/5737. But this will take some time.

In the meantime, I think you might take advantage of the python dynamic types, and abuse it to do something like:

- Add a field like ``self.conanfile_folder = os.path.dirname(__FILE__)`` in the ``package_info()`` method.
- Use ``self.conanfile.conanfile_folder`` inside your generator.

Please let me know if you try this and if it works or not.

**Comment by rweickelt** [comment]
> Add a field like self.conanfile_folder = os.path.dirname(__FILE__) in the package_info() method.
> Use self.conanfile.conanfile_folder inside your generator.

Yes, I did that and it worked when running the generator with an ordinary package conanfile.py. But the same approach does not work in conan test packages. The custom property is undefined when accessing it from the generator.

**Comment by danimtb** [comment]
considering this question as answered. Please, if you are still facing some issue with the recommendation above, please open an new issue and we will take a closer look. Thank you!

**Comment by seanmlyons22** [comment]
@danimtb, sorry to come in after this issue was closed, but I believe it is still relevant. Should we reopen?

**Comment by memsharded** [comment]
Hi @seanmlyons22 

If you think this issue is still relevant, could you please provide further details? Do you have some example or specific comment about this? Please tell and we will check if re-opening makes sense, thanks!

**Comment by seanmlyons22** [comment]
@memsharded, coming back again. Hope you are doing well. I needed this again today in my work and found that I never followed up on this. My apologies.


The details are exactly @rweickelt explains. We have the following:

- Package A exposes some scripts and a generator.
- Package B consumes that package and its generator
- Inside the repository for package B, we have a config file


We would like to be able to read the config file in its deployment location and use that to make some decisions. Otherwise, we need to add conan options just to control the generator behavior which is not desirable. 

Even more concrete: Package A is a suite of scripts for styling code as well as their config files `.clang-format`. Generator deploys these config files to a repo upon install. We do that so that all repos in our org have the same code format config scripts. Package B is any package in our org. It has code that needs to be styled so it has package A as a dep.

**Comment by memsharded** [comment]
For a dependency, in the consumer:

```python
def generate(self):
      dep_folder = self.dependencies["pkga"].recipe_folder
      mydep_file = os.path.join(dep_folder, "myfile.txt")
```

If you move the functionality to a ``python_requires`` (sounds that this could be the way to go for generators, as the ``Generator`` base class is deprecated, and the way to use custom generators is via ``python_requires``), then it is very simple. Either the generator code can access its own ``self.recipe_folder``, or the consumers can access ``self.python_requires["pgka"].path``.

I hope this helps.

**Comment by seanmlyons22** [comment]
@memsharded, thanks for the quick reply! However, unfortunately I realize I had written it backwards. 

I would like for my generator inside package A to be able to read a file inside package B's repo. Basically I want the location of `conanfile.py` of the repo where I am running `conan install .` and I want to be able to evaluate that from the generator provided by package A.

**Comment by memsharded** [comment]
Ok, yes, this would be typically something in the form:
```python

# package A containing some helper functions
def myfunction(conanfile):
     folder = conanfile.recipe_folder  # access the caller recipe folder

class Pkg(ConanFile):
     name = "mygen"
     version = "1.0"
```

```python
class App(ConanFile):
      python_requires = "mygen/1.0"
      def generate(self):
            pr = self.python_requires["mygen"].module
            pr.myfunction(self)
```

If you check how we code all of our helpers and generators they are all ``CMakeToolchain(self)``, receiving ``self`` as first argument, even tools like ``save(self, ..)``, etc, receive always ``self``

**Comment by seanmlyons22** [comment]
Okay, this looks like it will work for me, specifically using `self.conanfile.recipe_folder` in the generator. I did some tests. 
Our org is using a bit older version(1.43.4) and still inheriting from `Generator`. It seems that this works regardless, but wanted to check with you if you think it should be safe.

We don't put our generators in `python_requires` because we had some issues with that (probably another discussion), so they're in `build_requires` now.

**Comment by memsharded** [comment]
Inheriting from ``Generator`` was fundamentally flawed, because if you have different requirements with different versions in different packages, specially with ``build_requires``, they will just overwrite each other without noticing or warnings. And the version that wins is arbitrary not even the latest. So having your ``build_requires`` diverge in version of the Generator is something that is there waiting to create bugs 😅 

So even if I guess that using the ``conanfile.recipe_folder`` in your legacy ``Generator``, I'd still recommend dropping that as soon as possible in favor of putting generator code in ``python_requires``

**Comment by seanmlyons22** [comment]
> Inheriting from `Generator` was fundamentally flawed, because if you have different requirements with different versions in different packages, specially with `build_requires`, they will just overwrite each other without noticing or warnings. And the version that wins is arbitrary not even the latest. So having your `build_requires` diverge in version of the Generator is something that is there waiting to create bugs 😅

This sounds like exactly what happened when we tried to move our generators to use `python_requires` while still inheriting from `Generator`. Different dependency versions in the tree could overwrite one another causing tons of problems. For some reason (maybe dumb luck), we don't see this when using `build_requires`.

So it looks like we have some work to do to migrate our generators away from inheriting from `Generator`.
Great information, glad I asked!

To come back to the original topic about reading a file it seems that `conanfile.recipe_folder` is exactly what was originally requested by this post. It provides the path to the `App`'s conanfile. From there we should be able to read a config file and control the generated content on a per-consumer basis by reading this config file. If that is true, then I think we can close this issue as the original question is answered.

**Comment by memsharded** [comment]
The issue was already closed :)  but thanks for the feedback.

For new questions, it is typically better to open a new issue, it is possible that posting on closed issues passes inadvertently, because of high traffic, so if you don't get a response in some other closed one, please file a new ticket.
