### ISSUE TITLE
Can not build against Boost after update

### ISSUE THREAD

**Issue by Hennaldo** [conan-io/conan#581]
After updating to conan 0.14 we are not able to build our components against Boost 1.59, the compiler can`t find the Header.

When downgrading to version 0.13.1 it is working again

**Comment by monsdar** [comment]
The package was created with Conan 0.13.1, our server also runs on 0.13.1.

The error message in like the following:
`....h(5): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "boost/shared_ptr.hpp": No such file or directory` (mid part is German for "cannot open file").

**Comment by memsharded** [comment]
Could you please provide me with more information about how your components are using Boost as dependency? Are they using ``ConfigureEnvironment``? In which OS and compiler? Thanks!

**Comment by monsdar** [comment]
* OS: Windows 7 Prof 64bit
* Compiler: Visual Studio 2013 64bit
* Dependency is `Boost/1.59.0@comp/thirdparty` which is based on `Boost/1.59.0@lasote/stable` bit instead of downloading the sources uses a local repo
* Component is built with CMake (using conan via include, `conan_basic_setup`, `CONAN_INCLUDE_DIRS` and `CONAN_LIBS`)
* We're not using `ConfigureEnvironment` (as far as I know)

**Comment by memsharded** [comment]
It is an issue with the new short_paths feature for the "package" folder. Debugging...

**Comment by memsharded** [comment]
Released 0.14.1, that should solve it, please try and give feedback. Thanks!

**Comment by monsdar** [comment]
Just tested it, works well :)
