### ISSUE TITLE
tools.replace_in_file() always converts to UTF-8

### ISSUE THREAD

**Issue by pwaehnert** [conan-io/conan#5840]
Conan-Version: Master, OS: Cross-plattform but especially under Windows

The function tools.replace_in_file() always converts the input to UTF-8 before writing it back to the file, as you can see here: https://github.com/conan-io/conan/blob/abca49f1a99cd4cf0d0f02dee6f09f68460a3b42/conans/client/tools/files.py#L257

In our case, we need to preserve the encoding of the original file and only replace a minimal ASCII portion of it. Of course, we simply can read, substitute and write the file by hand without tools.replace_in_file(), but using the function tools.replace_in_file() would be much more convenient.

**Comment by lasote** [comment]
The issue is to know which encoding to use, both for loading the file and then before writing to a file.
Maybe we could add a new argument to the tool to hardcode the encoding. That's why for reading, we are trying to decode detecting first some "bom" headers and then trying with `utf-8` and `"Windows-1252"` but then we are using always `utf-8` to store the contents. Managing this is very very complex, but as I said, a new optional argument couldn't break anything.

**Comment by SSE4** [comment]
I agree, some files are essential to have a particular encoding (e.g. `.rc` files are needed to be in `UTF-16` AFAIK)
I would apply the following changes:
```
tools.load(path, binary=False, encoding='auto`)
tools.save(path, content, append=False, encoding=`utf-8`)
tools.detect_encoding(path) - new method, might be private, uses BOM to detect encoding
tools.replace_in_file(file_path, search, replace, strict=True, encoding=`utf-8`)
```
