### ISSUE TITLE
Python requires feature

### ISSUE THREAD

**Issue by sneik555** [conan-io/conan#5845]
Hi,
I have question about [python requires](https://docs.conan.io/en/1.18/extending/python_requires.html). 
This feature is in EXPERIMENTAL from conan 1.9 - are you plan to do some changes in this? 

Thanks for help,
Tomasz

**Comment by memsharded** [comment]
Hi @sneik555 

yes, the truth is that the inversion of control that the current python_requires implementation does, is a total nightmare. Very difficult to do things like lock (lockfiles) them, and complicated and dirty internally. We have been struggling with this since the beginning, this is why it hasn't been moved out of experimental stage.

We are trying to recover control, and be able to declare them as class attribute: https://github.com/conan-io/conan/pull/5804. Please follow conversation there (I am closing this one ), thanks!
