### ISSUE TITLE
How does conan handle out of source builds?

### ISSUE THREAD

**Issue by ruipacheco** [conan-io/conan#5912]
To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

I'm not filling out the questionnaire above because this is not a bug.

The recommended way to build projects with CMake is to use out of source builds and this should be enforced at generation time with [two](https://stackoverflow.com/a/45106945/70600) [options](https://stackoverflow.com/a/37540734/70600) available to do that.

I do this on my scripts but to make it work with conan I had to hack something:

```
class KVVideoioConan(ConanFile):
    name = "kvvideoio"
    [...]
   generators = "virtualrunenv", "cmake_find_package"
   exports_sources = "src/*", "include/*", "cmake/*", "tests/*", "CMakeLists.txt", "Config.hpp.in"
   _build_folder = "build/"

    def _prep_build_folder(self):
        """
        Our CMakeLists.txt enforces out of source builds for safety reasons so we need to first                    create the 
        build folder and then copy the Find*.cmake files into it.
        """
        path = Path(self.source_folder)
        build = Path(path).joinpath(self._build_folder)
        if os.path.exists(build):
            shutil.rmtree(build)
        os.mkdir(build)
        with os.scandir(path) as entries:
            for entry in entries:
                if entry.is_file() and fnmatch.fnmatch(entry.name, "Find*.cmake"):
                    shutil.copy2(entry.path, build)

    def _configure_cmake(self):
        cmake = CMake(self)
        cmake.configure(build_folder=self._build_folder)
        return cmake

    def build(self):
        self._prep_build_folder()
        cmake = self._configure_cmake()
        cmake.build()
    [...]
```

I'm obviously uncomfortable with this. Is there a way to support out of source builds when creating a conan package?

**Comment by memsharded** [comment]
Hi @ruipacheco 

I totally understand your uncomfort. Unfortunately, right now it is not possible to do this without copying the files (well, you could point the cmake find paths to the parent folder, but that is not very elegant either).

The good news it that we have started to think how to improve this, and the answer will probably be by explicitly modeling the layout: https://github.com/conan-io/conan/compare/develop...memsharded:feature/new_toolchains?expand=1, which in recipes, could be something like:

```python
     class Pkg(ConanFile):
            ...
            def layout(self):
                mylayout = CMakeLayout(self)
                # Default, will be overriden by local "build-folder" arg
                mylayout.build = "build"
                return mylayout
```
Just a very preliminary idea, but at least you know that it is on our mind.
Thanks very much for reporting it.

**Comment by memsharded** [comment]
You might also be interested in tracking https://github.com/conan-io/conan/issues/5737

**Comment by johnmcfarlane** [comment]
Clarifying question: Conan doesn't prevent out-of-source, so is this specifically about enforcement?

**Comment by memsharded** [comment]
Hi all,

This ticket became outdated some time ago, ``layout()`` has been around for years, with features that include ``self.folders.root``, ``subproject`` definition, etc.

Conan will implement by default in layouts having the build in its own folder under the project, that has the benefits of not polluting the project folder (something as simple as adding ``build`` to ``.gitignore`` will handle it) and also keeping things reasonably clean when there are multiple repos around, multi-projects, etc, if every one decides to put their build in sibling folders instead of children folders, we have seen big mess. Because when using a package manager like Conan, this situation will become more and more frequent, and the flow of ``git clone + cd + build`` and all living in a single folder, not 2 folders can be way more convenient. Furthermore, this layout is very important to be able to achieve the exact same layout when packages are being built in the cache, when building in a sibling folder is not easy.

The new layouts also include the ``--output-folder`` argument that allows to put the build completely out of source if desired, so something like ``conan build . -of=../mybuild`` should achieve the goal of having an out-of-source build (just tested with ``conan new cmake_lib -d name=pkg -d version=0.1`` and it works fine. Also tested with ``conan install . -of=../mybuild`` and using the CMakePresets, also works fine.

I think this ticket can be closed as addressed by ``layout()`` and ``--output-folder``, but please don't hesitate to open new tickets for any further question or feedback that you might have.
