### ISSUE TITLE
conan search -r all

### ISSUE THREAD

**Issue by sdmg15** [conan-io/conan#5913]
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.20.0-dev
OS : Ubuntu 18.04 Bionic Beaver

When running `conan search -r all` i.e without specifying a `pattern_or_reference` , the command keeps running and finally stop with this error message 

Maybe related #2945
 ```
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.bintray.com', port=443): Read timed out. (read timeout=60.0)",))

Unable to connect to conan-center=https://conan.bintray.com 

```

**Expected behavior** : I expected conan to say that the pattern_or_reference parameter is required.

**Comment by memsharded** [comment]
Hi @sdmg15 !

Actually the issue is not that that an argument is not provided. I think you will get the same result if you provide ``conan search * -r=all``. Not providing an argument is the same as defining the "*" argument.

The problem is that Bintray search is slow, and then the query takes a lot of time to resolve and timeouts. There is little that we can do here, the message is correct, there was a timeout. We are working to improve the experience of Conan-center (as you can see in the new binary build service and the Conan-center-index repo in https://github.com/conan-io/conan-center-index), so this will eventually be solved in the server side.

I suggest the following workarounds in the meantime:
- Try to provide a more restricted search like ``conan search z* -r=all``
- Navigating the web directly in https://bintray.com/conan/conan-center


As we can't do much here (not a conan client issue), I'd suggest closing this issue (if the response was clear enough), and we have that already annotated for future server side improvements. Thanks for the report!

**Comment by sdmg15** [comment]
Yeah, the search is really slow. 
Do you not think to slightly improve the performance from conan  side if we at least treat the case when you run without any arguments and the case when you run with "*".  Because those are too greedy 

So when you run `conan search -r all ` we tell you that the pattern is required

and when you run also `conan search "*" -r all` we also tell you that. Just suggesting :smile:

**Comment by memsharded** [comment]
Yeah, that would be great, but the problem is that it would be breaking behavior. We will definitely change that as you suggested, making the argument obligatory (actually making it explicit if it is a recipe search or a binary search, because in one case it is a pattern, in the other it is a reference), for the next major Conan 2.0 release, but in the meantime, I am afraid we cannot change that 😞 

I am really looking forward to Conan 2.0! 😄

**Comment by sdmg15** [comment]
Alright keep it up :smile:
