### ISSUE TITLE
Setting env_info with cmake_multi

### ISSUE THREAD

**Issue by pgrohs** [conan-io/conan#5951]
Conan version 1.19.2

I have created a package which defines an environment variable in its `package_info` recipe method by setting `self.env_info.MY_VAR=VALUE`. This works well if the client of that package uses the `cmake` generator, but not if it uses `cmake_multi`. Do I have to do some extra stuff to make this transfer from variables from a package to the build environment of a client with the `cmake_multi` generator working?

**Comment by danimtb** [comment]
Hi @pgrohs,

Could you provide me with an example to reproduce the issue? How you check the environment var is set using the cmake generator?

**Comment by pgrohs** [comment]
Hi @danimtb,

this is the snippet from the package recipe:

```python
def package_info(self):
        self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))
        self.env_info.PACKAGE_PATH = self.package_folder
```

I am using these variables to find the package with cmake in the consuming package:

```cmake
find_package(MyPackage HINTS "$ENV{PACKAGE_PATH }/cmake")
```

That is working fine for the `cmake` generator but not with `cmake_multi`. I have checked by printing all environment variables within the cmake script which variables are set, but mine are not for `cmake_multi`.

**Comment by danimtb** [comment]
Thanks for the information. I will check it later today

**Comment by Mikayex** [comment]
Any news on this ? I'm also having the problem...

**Comment by memsharded** [comment]
Tons of things have changed since this issue in 2019:

- The new integrations, ``CMakeDeps`` is already "multi", and it will be the standard integration in 2.0 (already in alpha.4). Recommended to start upgrading to it
- The environment is also managed with the new Environment classes, something more explicit like ``self.buildenv_info.append_path("PATH", "xxxxx")``, that is used by the new ``VirtualBuildEnv`` generator. This ``VirtualBuildEnv`` is also "multi-config", which is what solves this issue (environment management with the previous integration was single-config)

As the legacy ``cmake_multi`` integration has already been removed in 2.0 and is no longer being maintained (unless there is a critical regression or something like that), I think this issue can be closed now. Thanks!
