### ISSUE TITLE
[question] Is it possible to list the system requirements for a package?

### ISSUE THREAD

**Issue by peter-moran** [conan-io/conan#5959]
Is it possible to list the system requirements for a package?

For example, I would like to find out what system packages `conan install qt/5.13.1@bincrafters/stable` would install.

The reason I need this is so I can build my binaries on one machine and then copy them to another machine for use, and I'd like a clean list of all the system packages needed on that other machine (I'm open to other ways of doing this if there are).

**Comment by nicememory** [comment]
I think conan is just the tool for it. Think about pip for Python. Conan is the 'pip' counterpart for C/C++.
Build the binaries with conan and upload the binaries to a conan server. Then download the binaries on the other machine from conan server.

**Comment by memsharded** [comment]
Hi @peter-moran 

Unfortunately, right now there is no way to get this list of system requirements.
At least, it is something that is in our roadmap. We don't like the fact that conan recipes are installing system packages by default (and suddenly a sudo permission is prompted to the user), so we are changing this. The new approach will list the things that are required and raise if they are not present. Maybe install, but probably that will be done as opt-in. 

We need to discuss and think about it. In any case, it won't be possible until Conan 2.0, because that would break too much.

Related issue: https://github.com/conan-io/conan/issues/4226 suggests to store the system requirements in metadata, for example to help uninstalling

**Comment by peter-moran** [comment]
Thanks for the response, completely understandable.

Is it currently possible to have conan run just the `system_requirements()` part of an `conan install`, or is just all or none? This could help me, say, set up a docker image with the system requirements automatically pre-installed.

**Comment by uilianries** [comment]
> Is it currently possible to have conan run just the system_requirements() part of an conan install, or is just all or none

Unfortunately, there is not way to run only system_requirements. If you are using docker or VM, you can try Ansible or something similar.

**Comment by memsharded** [comment]
I have been checking this that was pending for 2.0 milestone.
Unfortunately, the complexity is still very large for the value, and we don't have enough bandwidth to consider this for the final 2.0 release next month. So lets move it to 2.X roadmap, these would be more or less the necessary steps as I envision:

AlternativeA: declarative
- Define a known, structured format for the packages to install, most likely in ``conandata.yml``. This is a bit challenging, need to figure out the structure to account for all variability
- Define a high level wrapper of all "SystemPackageTools" that will call the right one according to the ``conandata.yml`` structure
- Have a way (generic) to collect data from ``conandata.yml``
This  would have the advantage to be platform independent, can collect all requirements for all platforms at once

Alternative B: Use a deployer
- Implement a fake collecter of packages to install, so all SystemPackageTool, store the ``install(pkgs)`` pkgs instead of actually installing them.
- Implement a ``deployer`` that can run the ``system_requirements()`` of all packages and generate a report from it
This will be a per-configuration approach, it can only collect the data for the current configuration

**Comment by memsharded** [comment]
I did an extra effort and implemented this in https://github.com/conan-io/conan/pull/12912, so this will be available in next beta.9.
