### ISSUE TITLE
[bug] conan.patch incorrectly applied

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#5963]
initial issue: https://github.com/conan-io/conan-center-index/issues/214
it turns out conan's `tools.patch` method applies patches incorrectly after the switch to `patch_ng` package. e.g. its behavior significantly differs from the `patch` command, or `git apply` / `git am`

test case to reproduce:
https://github.com/conan-io/conan/compare/develop...SSE4:patch_issue?expand=1#diff-11632e511bcb65a506566fb2157b051eR27
reduced (short) test case:
https://github.com/conan-io/conan/compare/develop...SSE4:patch_issue?expand=1#diff-11632e511bcb65a506566fb2157b051eR409

in terminal:
```
git clone git@github.com:boostorg/boost.git
cd boost
git checkout boost-1.70.0
curl https://raw.githubusercontent.com/conan-io/conan-center-index/5d3a76231eeab86d24dda08cb0ee92fa307ef50f/recipes/boost/all/patches/bcp_namespace_issues.patch > 1.patch
patch -p1 < 1.patch
cat Jamroot | grep "1\.70\.0"
cat Jamroot | grep "1\.71\.0"
```
there is no `1.71.0` in the output (but in case of conan, it is)

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Enterprise
  * Compiler+version: N/A
  * Conan version: 1.19.2
  * Python version: 3.7.3

**Comment by jgsogo** [comment]
Thanks, @SSE4. It is not working the same.

Talking about the `boost` example, the one copy/pasted in your comment, which is the one in your test `ToolsFilesPatchTest::test_patch1`:

 * the first issue is that the patch file doesn't match the original file: it the original `Jamroot` file it says `constant BOOST_VERSION : 1.70.0 ;`, but the patch contains `constant BOOST_VERSION : 1.71.0 ;`:

```patch
From d0586e88122f41cd5ac9666db70c37d6f0fc7480 Mon Sep 17 00:00:00 2001
From: Peter Dimov <pdimov@gmail.com>
Date: Sun, 26 May 2019 18:49:12 +0300
Subject: [PATCH] Fix `bcp --namespace` issues

---
 Jamroot | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/Jamroot b/Jamroot
index e0d7c90f51d..4e913c2b3f3 100644
--- a/Jamroot
+++ b/Jamroot
@@ -140,7 +140,8 @@ import "class" : new ;
 import property-set ;
 import threadapi-feature ;  ## Comment
 import option ;
-import tools/boost_install/boost-install ;
+# Backslash because of `bcp --namespace`
+import tools/boost\_install/boost-install ;
 
 path-constant BOOST_ROOT : . ;
 constant BOOST_VERSION : 1.71.0 ;
@@ -311,8 +312,8 @@ rule boost-install ( libraries * )
 # stage and install targets via boost-install, above.
 rule boost-lib ( name : sources * : requirements * : default-build * : usage-requirements * )
 {
+    autolink = <link>shared:<define>BOOST_$(name:U)_DYN_LINK=1 ;
     name = boost_$(name) ;
-    autolink = <link>shared:<define>$(name:U)_DYN_LINK=1 ;
     lib $(name)
         : $(sources)
         : $(requirements) $(autolink)

```

 * Git is able to patch the file with `fuzz 1` (it means that one thing doesn't match):
   ```
   ⇒  patch -p1 < 1.patch
   patching file Jamroot
   Hunk #1 succeeded at 140 with fuzz 1.
   ```
 * Our `patch-ng` says nothing about:
   ```
   p1.patch: reading p1.patch
   p1.patch: total files: 1  total hunks: 2
   p1.patch: stripping 1 leading component(s) from:
   p1.patch:    b'a/Jamroot'
   p1.patch:    b'b/Jamroot'
   p1.patch: processing 1/1:	 b'Jamroot'
   p1.patch:  hunk no.1 for file b'Jamroot'  -- is ready to be patched
   p1.patch:  hunk no.2 for file b'Jamroot'  -- is ready to be patched
   p1.patch: processing target file b'Jamroot'
   p1.patch: hunk 1
   p1.patch: hunk 2
   p1.patch: successfully patched 1/1:	 b'Jamroot'
   ```
   but substitutes, not only the lines to patch, **but all the remaining lines in the block!!**. That's why it substitutes the line `constant BOOST_VERSION : 1.71.0 ;` too.  (FYI, if the mismatch is before the lines to substitute, it does fails with `WARNING: source file is different - b'Jamroot'`).

If we are able to make `patch-ng` to inform about the fuzzy matches, we can fail if there is any (I think it would be ok to fail if the patch cannot be applied perfectly), but if we cannot detect this situation... problably we should revert https://github.com/conan-io/conan/pull/5761

**Comment by jgsogo** [comment]
@SSE4 If the issue https://github.com/conan-io/conan-center-index/issues/214 was already there, then the problem is with the original `python-patch`, not with the `patch-ng` fork we are going to introduce for `1.20`, right? So, reverting #5761 wouldn't fix anything...

**Comment by dorozhkin-stc** [comment]
Indeed, the issue https://github.com/conan-io/conan-center-index/issues/214 has triggered with conan 1.19.2, which uses patch=1.16.

**Comment by uilianries** [comment]
Recipe that reproduces the error:

```python
from conans import ConanFile, tools
import os


class FuzzConan(ConanFile):
    name = "fuzz"
    version = "1.70.0"
    scm = {
        "type": "git",
        "subfolder": "boost",
        "url": "git@github.com:boostorg/boost.git",
        "revision": "boost-1.70.0"
     }

    def build(self):
        url = "https://raw.githubusercontent.com/conan-io/conan-center-index/5d3a76231eeab86d24dda08cb0ee92fa307ef50f/recipes/boost/all/patches/bcp_namespace_issues.patch"
        patch = "bcp_namespace_issues.patch"
        tools.download(url, patch)
        tools.patch(base_path="boost", patch_file=patch)
        content = tools.load(os.path.join("boost", "Jamroot"))
        assert "1.70.0" in content
        assert "1.71.0" not in content

```

**Comment by uilianries** [comment]
Hi!

The project *python-patch-ng* doesn't offer fuzzy support and there is no comment/issue/pr about it. I found that when apply the patch, it uses the patch hunk as source and doesn't compare with the original source, that's it's overriding. I think I'll be able to release a fix today. I delay it because needed to understand first the rules for fuzzy patch, I found it on gnu patch project.

Also, I've thought to port GNU patch project, as it's complete in terms of features and is not a big project. I could do it as side project during the weekend, and maintaining it should not be a problem.

**Comment by jgsogo** [comment]
IMHO, unless it is extremely easy to fix and no other bugs may be introduced due to that fix (we are not providing a `patch` library, but something that works for the Conan purposes), I would detect the fuzzy patch and fail. Conan is about reproducibility, if the patch is not fuzzy and the sources change, then the patch should be updated too.

wdyt?

**Comment by lasote** [comment]
Totally agree!

**Comment by SSE4** [comment]
it's better if conan just refuses to apply patch rather applying it incorrectly

**Comment by uilianries** [comment]
well, the PR https://github.com/conan-io/python-patch-ng/pull/6 I ready and now it accepts fuzzy patches.

However, it's the default behavior now. I Could add a new parameter to accept or not fuzz. Although, gnu patch accepts fuzzy by default, so accepting any fuzzy patch now sounds more natural according gnu patch.

We can't consider git apply (it doesn't allow fuzzy patch), because this tool is a generic patch tool, which includes svn and mercurial.

**Comment by helmesjo** [comment]
Was this fixed? I'm still seeing this/similar issue for `boost/1.70.0@conan/stable` in `conan 1.21.0`:
```
Downloading boost_1_70_0.tar.bz2 completed [95592.83k]                                   

WARN: patches/bcp_namespace_issues.patch: file 1/1:      b'Jamroot'
WARN: patches/bcp_namespace_issues.patch:  hunk no.1 doesn't match source file at line 146
WARN: patches/bcp_namespace_issues.patch:   expected: b'constant BOOST_VERSION : 1.71.0 ;'
WARN: patches/bcp_namespace_issues.patch:   actual  : b'constant BOOST_VERSION : 1.70.0 ;'
patches/bcp_namespace_issues.patch: source file is different - b'Jamroot'
ERROR: boost/1.70.0@conan/stable: Error in source() method, line 162
        base_path=os.path.join(self.source_folder, self.folder_name))
        ConanException: Failed to apply patch: patches/bcp_namespace_issues.patch
```

**Comment by dorozhkin-stc** [comment]
@helmesjo Indeed the error you get is a correct behaviour now. Regarding `boost/1.70.0@conan/stable` recipe, there is a comment in the initial issue https://github.com/conan-io/conan-center-index/issues/214#issuecomment-564074114 which states that the recipe will remain broken forever and users should use `boost/1.70.0` (i.e. without user and channel).

**Comment by helmesjo** [comment]
Alright, thanks @dorozhkin-stc (_though I think you meant "users should use `boost/1.71.0`", which is what I did instead_).

**Comment by Firefly35** [comment]
How can we rely on conan for dependencies stability, when some evolutions break forever a recipe several developments depends on ? In industrial context, upgrading a package version is not done without prior regression tests ...
Knowing recipes for a specific package version can become broken forever implies to question the choice of conan as a dependency managing tool in industrial development software context.

**Comment by memsharded** [comment]
> How can we rely on conan for dependencies stability, when some evolutions break forever a recipe several developments depends on ? In industrial context, upgrading a package version is not done without prior regression tests ...
Knowing recipes for a specific package version can become broken forever implies to question the choice of conan as a dependency managing tool in industrial development software context.

We do our best effort to maintain stability, but with software, and specially free and open source software, sometimes it is difficult. For example we cannot control how Conan own dependencies evolve, and they sometimes might break Conan too. We have an extensive test suite which we also invest a lot of time maintaining. But the lack of maintenance of the ``patch`` library that we were using is something difficult to manage, and we needed to fork and maintain it.

If you @Firefly35 could you please elaborate what has been broken, specify the Conan version in which it worked, the Conan dependencies (pip freeze, pip list), the example code, and the Conan version that introduce the regression you are experiencing, we will check it and investigate how this can be fixed. Thanks.

**Comment by Firefly35** [comment]
The boost/1.70.0 recipe is broken and doesn't build on ubuntu 18.04.
Maybe the conan tool could deserve a rewrite, with lesser dependencies or with another language/framework with well supported dependencies.
For instance I develop and maintain a meta dependency management tool (https://github.com/b-com-software-basis/remaken), that has its own dependency binaries format. The dependencies definitions also support other packaging tools (including conan, vcpkg or other system tools).
I chose to use c++ to develop it, with boost as its main dependency and openssl.

**Comment by memsharded** [comment]
> The boost/1.70.0 recipe is broken and doesn't build on ubuntu 18.04.

It is possible. Conan does not guarantee "industrial" stability of the recipes maintained by the community in the ConanCenter repo. Most of the thousands of Conan users using Conan in production have a fork of the package recipes under their control, and we recommend that.
