### ISSUE TITLE
Include guards on conan_paths.cmake [Suggestion]

### ISSUE THREAD

**Issue by grifcj** [conan-io/conan#5975]
Suggestion: Use include guards where appropriate on generated cmake files so that multiple inclusion is idempotent or otherwise has no ill side-effects.

I came upon this after trying to inject conan_paths.cmake (from cmake_paths generator) via CMAKE_PROJECT_INCLUDE (available as of 3.15). There are other special variables for auto inclusion, but this one lets you do the job without needing a project name. It gets triggered on every call to project() hence append type assignments will accumulate repetitive paths (like those for module and prefix paths)

Didn't break anything; just tended to make the value of these path variables harder to inspect. I think you might run across this also composing multiple projects via add_subdirectory where one might expect a conan_paths include in each project. Might also impact other types of generated files meant to be included.

Adding something like the following to top of generated file could ensure single execution. There is include_guard(), but that requires cmake >3.10.

```cmake
if (DEFINED CONAN_CMAKE_PATHS_INCLUDE_GUARD)
    return()
endif()
set(CONAN_CMAKE_PATHS_INCLUDE_GUARD 1)
```

I could provide a PR if this turns out to be something to do.

- [ X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by KerstinKeller** [comment]
Hi @grifcj, I have also been thinking about using the new `CMAKE_PROJECT_INCLUDE` instead of `CMAKE_TOOLCHAIN_FILE` for the `conan_paths.cmake` file injection, because at some point we will certainly want to cross-compile and then the `CMAKE_TOOLCHAIN_FILE` will be needed for the actual toolchain file 😄 

However I wasn't aware that this file will be included with every subsequent `project()` call. Hence it would indeed make a lot of sense if the generated file had some kind of include guard.
It wouldn't break current usage either.

**Comment by memsharded** [comment]
conan_paths.cmake replaced by ``CMakeToolchain`` generator, closing this.
