### ISSUE TITLE
[question] Why doesn't conanbuildinfo.cmake actually invoke conan_basic_setup() itself?

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#6004]
Apologies if this has already been asked and an answer already provided elsewhere.

My understanding of CMake is that a file such as our current `conanbuildinfo.cmake` could just include a call to `conan_basic_setup()` at the end of the file, after the macro has been defined.
Is there a reason we don't do this?

Not only would this simplify the changes needed to include conan support in a CMakeLists.txt, but it might also facilitate some of our experiments with non-invasive cmake inclusion using, e.g. https://cmake.org/cmake/help/latest/command/project.html#code-injection

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by michaelmaguire** [comment]
Thanks for the explanation!

**Comment by mpnunez** [comment]
Here's a use case where I'm very glad that conan_basic_setup() is not called automatically.

If using [pybind11](https://pybind11.readthedocs.io/en/stable/compiling.html#building-with-cmake), then in order to use conan to link external libraries to the binding code, conan_basic_setup(NO_OUTPUT_DIRS) should be used. Otherwise, the build so file will end up in a place that setuptools cannot find it.

```
cmake_minimum_required(VERSION 3.15)
project(cmake_example)

# Add Conan dependencies
include(${CMAKE_SOURCE_DIR}/build/conanbuildinfo.cmake)
conan_basic_setup(NO_OUTPUT_DIRS)

add_subdirectory(pybind11)
pybind11_add_module(cmake_example src/main.cpp)
target_link_libraries(cmake_example ${CONAN_LIBS})

# EXAMPLE_VERSION_INFO is defined by setup.py and passed into the C++ code as a
# define (VERSION_INFO) here.
target_compile_definitions(cmake_example PRIVATE VERSION_INFO=${EXAMPLE_VERSION_INFO})

```
