### ISSUE TITLE
[question] What is the purpose of conan_output_dirs_setup()

### ISSUE THREAD

**Issue by peter-moran** [conan-io/conan#6012]
My (conan consumer) project recently realized that `conan_basic_setup()` was messing with our build directories, which was then messing with our build entirely. We've since found the [NO_OUTPUT_DIRS](https://docs.conan.io/en/latest/reference/generators/cmake.html#conan-basic-setup) fixes our build by skipping `conan_output_dirs_setup()`.

My questions are:

1. Why change the output directories in the first place? I'm sure there is a good reason, but it is not documented anywhere I can find.
2. Is there any downsides to using `NO_OUTPUT_DIRS`? I can't tell for myself due to not knowing the reason for conan_output_dirs_setup(). Is it just a helper function?
3. Could we get the docs updated to include this information (I can open another ticket if needed).

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @peter-moran 

Your observations are pretty good.

This "feature" is mostly due to historical reasons. Changing the directories in cmake, made way easier to write ``package()`` methods in recipes, because all artifacts were always found in the same locations. Otherwise, they will be found in ``x64/Release`` folders in Windows VS, and in other locations in Linux, etc.

The current job we are doing with new generators like ``cmake_find_package_multi``, and ongoing work like recipes defining toolchains, will most likely remove this behavior. 

So regarding 2), no, there is no downside, besides you need to make sure things are correctly packaged from the right place.

3) Yes please, open a specific ticket to document this. I thought NO_OUTPUT_DIRS was correctly documented, so please suggest in the ticket (in the docs repo) more specifically what should be clarify (feel free to open a Pull Request yourself with the contribution, the docs are open source too 😃 )

Thanks for the feedback!

**Comment by peter-moran** [comment]
Resolved by conan-io/docs#1474
