### ISSUE TITLE
[question] How do I install a package with optional user/channel

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan#6018]
`conan search openssl -r all` gives the following output:

```
Existing package recipes:

Remote 'conan-center':
openssl/1.0.2s
openssl/1.0.2t
openssl/1.1.0k
openssl/1.1.0l
openssl/1.1.1c
openssl/1.1.1d
```

However none of these packages specify a user and channel. Attempting to use conan install gives
```
conan install openssl/1.1.1d -r conan-center

ERROR: Conanfile not found at <working dir>/openssl/1.1.1d
```

So how do I install such a package?

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @planetmarshall 

Yes, to dissambiguate to calls that looks like a path or like a user/channel, it is necessary to add the @ at the end:

```bash
$ conan install openssl/1.1.1d@ -r conan-center
```
This will be fixed in Conan 2.0.

Note, however, that this is not a recommended way to install a dependency. The recommended way is to put it in a conanfile.txt or conanfile.py and do a ``conan install .`` to the conanfile. This is because if you have more than 1 dependency, they can become inconsistent with the others, unless they are installed from the same conanfile. Also, it helps to define the ``generators`` and other things.
