### ISSUE TITLE
[question] Depend on same package for current arch when cross compiling

### ISSUE THREAD

**Issue by osechet** [conan-io/conan#6040]
I'm working on a gRPC package for Conan. When compiling gRPC, the compilation process generates an executable that is later used to generate new files used by the compilation. When cross-compiling gRPC for ARM, the [documentation](https://github.com/grpc/grpc/blob/bdc86d36b77bb554a163f8b7aeab2e8d51ae9587/templates/Makefile.template#L301) asks to first build gRPC for the current platform and then to use the generated executable to run the cross-compilation.
To deal with this situation with Conan, I thought I could add a `build_requires` on the same package but with a different `arch` when cross-compilation was detected:
```
def build_requirements(self):
    if self.settings.arch != self.settings.arch_build:
        self.build_requires("gRPC/%s@user/channel" % (self.version), arch=self.settings.arch_build)
```

But the `build_requires()` method does not accept others arguments expect the package name and Conan detects a dependency loop.

Is there a way to deal with this case in a clean way or do I have to build the library twice when detecting cross-compilation?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @osechet . This is a limitation up to the current Conan version: there can be only one node in the graph for each library, so there can be only one _configuration_ per library, which means that you cannot have `gRPC` for the `host` and the `build` machine in the same graph. This is the same problem we have with `protobuf` (`protoc` is inside).

We are working on a new implementation of the cross-building feature for Conan (current one is not enough). There are some [PR already opened related to it](https://github.com/conan-io/conan/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+xbuild) and we really want to move them forward:
 * https://github.com/conan-io/conan/pull/5202 is a PR with the full POC, a draft not to be merged, but it works for the most common use cases (it doesn't work to cross-compile a cross-compiler). This PR is going to be split and reimplemented into the ther PRs. I've tested it with `protoc` and WASM and it was working ok.
 * https://github.com/conan-io/conan/pull/5592 the first to be merged, it adds support to cross-building into the graph: you can declare a `build_requires` and choose the context for it: `host_machine` or `build_machine` (default), and
 * https://github.com/conan-io/conan/pull/5594 will allow to feed Conan with two profiles, one for the `host_machine` (current one) and another one for the `build_machine`.

I really think that those PR will cover your use-case, if they are moving slow is just because we want to be very sure that this new cross-building model will work. 

---

As a workaround, you may divide your `gRPC` into two recipes: `gRPC`-library and `gRPC`-build-executable (using `os_build` and `arch_build` settings, like other `xxxx_installer` recipes you may find in Conan servers), so you can have both of them in the graph. Or you can build it first for the _build machie_ and the executable to the PATH while building the app for the _host machine_.... 
I know those are not good alternatives, but I think it is the best I can offer you right now.

**Comment by osechet** [comment]
@jgsogo Thanks for your answer. I will follow your advice for the workaround and try to separate the bin and the libs.

**Comment by jgsogo** [comment]
Hi, @osechet , Conan 1.24 will have a new feature, it will allow defining two different profiles: one for the _build machine_ and another one for the _host machine_, it should be enough for this kind of use cases (protoc/protobuf) as the same package can appear twice in the graph for those different profiles.

You can have a look at this feature https://github.com/conan-io/conan/pull/5594 before it is released, I would really appreciate your feedback. 

Thanks!
