### ISSUE TITLE
[bug] graph lock fails in test_package when build requirements are used

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#6067]
### Environment Details (include every applicable attribute)
  * Debian 10, amd64
  * GCC 8.3.0
  * Conan version: 1.20.3
  * Python version: 3.7.5

### Steps to reproduce (Include if Applicable)

* Unzip [graph_lock_test_package_bug.zip](https://github.com/conan-io/conan/files/3841964/graph_lock_test_package_bug.zip)

* Execute `./run.sh` (it will set some options in your `conan.conf`)

Removing the `test_package`, or removing the `build_requires` section "solves" the issue.

## Output

`ERROR: The node ID 550ddd86-0629-11ea-9a9b-e0d55e049a23 was not found in the lock`

**Comment by jgsogo** [comment]
Yes, this is a use-case we have to take into account. Thanks for submitting it.

In this scenario the `profile.txt` is applying a build_requires to every node (`*: ninja/1.9.0`). The _graphlock_ is generated for the whole project and then it is applied to generate one of the requirements (and fails).

At the moment of generating the graphlock for all the project the `test_package` of the requirements are not taken into account because they didn't belong to the project graph, but when using the graphlock to build one of the requirement the `test_package` appears as the root of the graph, the _build requires_ is applied to it and a new node `ninja/1.9.0` appears... but that node was not in the graphlock.

I can figure out some patches to fix this issue, but I'll need @memsharded advice to know which one is the best option.

**Comment by theodelrieu** [comment]
The workaround I'm using right now is to remove test_package folders

**Comment by memsharded** [comment]
I have done some work here in https://github.com/conan-io/conan/pull/6457, but challenging and risky, so not ready to be included in 1.22. Lets delay it for 1.23, sorry!

**Comment by memsharded** [comment]
We are releasing a ``general.relax_lockfile`` configuration in 1.23 to implement this behavior, because of concerns of breaking something. This config is highly experimental, most likely will be removed in future versions, but we wanted to at least provide an opt-in for this behavior to be able to move forward.
