### ISSUE TITLE
[feature]  In-house packages without spinning up a server

### ISSUE THREAD

**Issue by graph** [conan-io/conan#6102]
Same as this issue https://github.com/conan-io/conan/issues/3669 . I like how cocoapods does it, just simple git repo. For inhouse packages it's not in the order of millions so simplicity is valued.

> Any specific reason you don't want to manage binaries and always build from sources?

It's easier. The downside it is slower for compiling, but with ccache it's not so bad. And anyway with so many compiler configurations maintaining inhouse packages for each configuration is alot of work. Easier just to distribute sources for private packages.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @graph 

Reusing packages directly from git repos will not be possible. But having your recipes in a github repo and have there a script that populates the local cache with the recipe is very simple, just go through the repo folders, and issue a ``conan export <path>`` for every conanfile.py found. In python would be very few lines.

> And anyway with so many compiler configurations maintaining inhouse packages for each configuration is alot of work.

This is not really true. The packages are actually created and built locally, but that is always done. So "maintaining packages for each configuration is a lot of work" shouldn't be a reason, because the packages have to be created and maintained anyway to be able to be used. Just they are not being upload. And once they have been built locally, putting them in a server is literally a ``conan upload * -r=myrepo --all``. And running a server is not difficult either, it is typically more work to set up the ccache, specially for multi-platform projects. So I'd still totally recommend using a server to upload the packages.

**Comment by memsharded** [comment]
We have added a response in our documentation faq in https://docs.conan.io/en/latest/faq.html, for reference, see PR: https://github.com/conan-io/docs/pull/2076.
