### ISSUE TITLE
[bug] Build policy outdated builds test_package ever

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#6112]
Hi!

This issues came from https://github.com/conan-io/conan-package-tools/issues/434

As we know, [Build Policies](https://docs.conan.io/en/latest/mastering/policies.html#build-policies) can influence the build action to Conan client. One of these policies is `outdate`, which is used to build ONLY a package that is outdated.

When running Conan Package Tools to build a list of packages, and using the `outdated` policy to avoid unnecessary jobs, Conan builds and run test_package, even when a package is not outdated.

### Environment Details (include every applicable attribute)
  * Operating System+version: ANY
  * Compiler+version: ANY
  * Conan version: 1.20.4
  * Python version: 3.8.0

### Steps to reproduce (Include if Applicable)

    conan new -t foo/0.1.0
    conan create . 
    conan create . --build outdated

### Actual Result

Conan build and run test_package even when a package is up-to-date and the build policy is "outdated".

### Expected Result

Conan should not build/run test package when build policy is "outdated", and the current package is up-to-date.

### Logs (Executed commands with output) (Include/Attach if Applicable)

[conan-outdated.log](https://github.com/conan-io/conan/files/3871211/conan-outdated.log)

**Comment by memsharded** [comment]
The outdated is irrelevant. Conan will always build the ``test_package`` project, as it is not a package, and build policies apply only to packages. This is a consumer project. The way to skip its building is with ``--test_package_folder=None``.

Not sure if I understood the issue correctly, though.

**Comment by uilianries** [comment]
I see, but it sounds a bit wrong, for instance, you run `conan create --build outdated`, which you want to say to Conan, "You must build ONLY IF a package is outdated", So Conan follow the rule, but it build the test_package even if the package is up-to-date. Like, you don't need to build the test, if my package is not outdated.

Anyway, I see your point, we can avoid it by extra argument, but it could be implicit for this case.

**Comment by uilianries** [comment]
For CPT, I can added this new behavior, as we use Conan API there, but it would be better as default behavior from Conan client.

**Comment by memsharded** [comment]
> I see, but it sounds a bit wrong, for instance, you run conan create --build outdated, which you want to say to Conan, "You must build ONLY IF a package is outdated", So Conan follow the rule, but it build the test_package even if the package is up-to-date. Like, you don't need to build the test, if my package is not outdated.

You don't know if the test_package itself has changed or not. The ``outdated`` state cannot be extrapolated to the test_package, this is why it is always ran.

**Comment by uilianries** [comment]
I see, thanks for clarify it. I think it's enough for this issue.

**Comment by db4** [comment]
@memsharded 
> The way to skip its building is with --test_package_folder=None.

> You don't know if the test_package itself has changed or not. The outdated state cannot be extrapolated to the test_package, this is why it is always ran.

Can you add an option like --test-outdated-only (choose a better name) that will implement the desired behavior? Maybe not very useful for conan client, but for CPT it makes sense I think.

**Comment by memsharded** [comment]
Hi @db4 

It feels a bit like a corner case. I guess it will not be only for ``outdated`` but you really want to run the ``test_package`` if you are building that package (missing, or maybe explicit). Should the ``test_package`` be skipped if the package was not re-build (was not outdated), but some of its dependencies was outdated and was rebuilt? The complexity of this feature could be more than it seems, and more derived corner cases will appear. 

Is it a huge problem? Typically the ``test_package`` projects build in a very few seconds, compared with the creation of the package is usually fast.

**Comment by db4** [comment]
@memsharded
My original problem is described in https://github.com/conan-io/conan-package-tools/issues/434 Can you take a look?

**Comment by uilianries** [comment]
Well, we can customize it on CPT. We just need to know if the package is outdated or not and apply the test package as None.

**Comment by n-bes** [comment]
I researched a little bit. CI can't generate dynamic jobs out of the box. So i think that (similar with a [vcpkg](https://dev.azure.com/vcpkg/public/_build/results?buildId=22636&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=29b11093-f299-52c9-fc3e-b4e81abf4ac1) build pipeline) bug should be fixed 😄

**Comment by sboehmann** [comment]
Same problem here. I build more than 300 packages on a CI using conan, cpt and docker _(to isolate all builds)_. Well, even if nothing has changed, the whole pipeline takes ~1h. Sure, most of the time is lost with starting docker containers, downloading dependencies and so on and I certainly should cache more things. 

But every second I could save is very welcome. And since Conan already knows that it doesn't need to build the recipe, it might be possible to also skip the test_package. For me, this would save a lot of time in total, especially when using MSVC.

**Comment by memsharded** [comment]
Hi @sboehmann 

I am having a look at this. It might be possible, but very ugly and hacky in the internals right now, this is why I'd prefer to wait to improve this for Conan 2.0 (I would like to further decouple the ``test_package`` functionality in 2.0).

Still, I am not sure thi is the best way to go. With recent tools, like new ``package_id_mods``, lockfiles and the ``conan graph build-order``, the efficiency comes from really building what is really necessary to build, so probably not necessary to call ``conan create`` (that is the thing that fires ``test_package``, I guess, in your case?) because you know in advance what packages really need to be rebuilt or not. With this new approach, the ``--cascade`` and ``--outdated`` arguments aren't necessary anymore. Have you had a look to this approach?

**Comment by sboehmann** [comment]
Many thanks for your quick reply @memsharded 

I've never read about `package_id_mods`. What is it?

Well, maybe I only asked this because `conan graph build-order` didn't work for me. Because of that 
I took a different path and yes, I call `conan create` _(more precisely CPT's `build.py`)_ for each and every recipe. But now I think I really should use `conan graph build-order` - I just don't know how to use it. 

But please refer to my new issue #7086.

**Comment by memsharded** [comment]
``package_id_modes`` are the way to control what needs to be rebuilt downstream, based on the version and revision changes of the packages. Maybe have a look to:

- https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#using-package-id-for-package-dependencies
- https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#changing-the-default-package-id-mode

Lets have a look at ``conan graph build-order``, we can continue conversation in #7086 then.

**Comment by memsharded** [comment]
``outdated`` build strategy has been removed in Conan 2, with revisions and new ``package_id`` modes, no longer makes sense.
