### ISSUE TITLE
[feature] add PREV to export-pkg --json output

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#6127]
I want to be sure I am uploading the correct package after a build on my CI server.  If I am understanding package revisions correctly then I need to provide a full reference to the `conan upload` command, specifying the PREV (e.g. `lib/1.0@conan/stable#RREV:PACKAGE_ID#PREV`), in case any other package revisions are still existing in the build server's local cache. 

I am not able to find this PREV hash in any --json output before the `conan upload ...` command.  Can this be added?

**Comment by czoido** [comment]
Hi @GordonJess,
Currently, the upload command is only taking into account the `PACKAGE_ID` part of the full reference because only one recipe revision and one package revision can exist in the cache, so when you upload the package to the server it will always be the last `RREV` and `PREV` you created. Maybe we should consider validating those fields as well so you get an error if they don't match.

**Comment by GordonJess** [comment]
Ah okay, great! Thanks! At least I know I can safely upload using only PACKAGE_ID and RREV.

**Comment by czoido** [comment]
@GordonJess take into account that only `PACKAGE_ID` is going to be considered and `RREV` will be obviated. I have labeled this as a bug because that could lead to not raising an error using an invalid `RREV`. Thanks a lot for reporting

**Comment by czoido** [comment]
By the way, @GordonJess, if I understand correctly you mentioned the `export-pkg` command in the title of the issue because you wanted to get the `PREV` of the package installed in the cache before uploading it, am I right?
In that case, I forgot to mention that you can get the `RREV` and the `PREV` of a package installed in the cache with the `search` command doing:

```
# get recipe revision installed in the cache
conan search name/version@user/channel --revisions
# get package ids
conan search name/version@user/channel
# get package revision (installed in the cache) of a package id
conan search name/version@user/channel#rrev:pkgid --revisions
```

You can add the `--json` argument if you want to get the output in a json file.
You could also add the `-r` argument to the list in case you want to find out the list of revisions available in the remote.

Do you have any more doubts about this topic? Do you think that we could close this issue?

**Comment by czoido** [comment]
Closing this as Conan 2.0 provides several ways of getting that PREV for later use in the upload command. Something like a `conan create ... --format=json` will provide that information in json format to process it in the CI.
Also, patterns in conan list command make it much easier to extract this information, something like:
conan list `pkg/version#*:*#*` will provide all the package revisions with the creation date in the local cache.
