### ISSUE TITLE
[question] How to "merge" multiple Conan caches?

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#6128]
Is there a way to safely combine multiple cache data directories into one? Precondition being that revisions feature is enabled and packages with same name and version, e.g. <mylib/1.0@user/channel> in different caches/data directories have different RREV/PREV. Can one just safely copy the files? If destination data/ directory should contain existing files it should mean exact duplicate package (RREV and PPREV match) and could be safely overridden?

Or is it somehow possible to "conan upload *" from cache A to cache MAIN somehow using "-r <cache MAIN> ?

**Comment by memsharded** [comment]
Hi @unzap 

No, in general it is not safe to copy files between caches, or use caches concurrently. At the moment only 1 revision can live at the cache, so any mismatch of revisions will cause a mess, for example, as the metadata file is just one, the same for all the binaries.

I don't see this kind of feature in the short term. The safest approach would be to use the server as the source of truth. That is definitely more manageable, traceable and secure. We are working on several things that might help to improve speed: parallel uploads/downloads and caching downloads of .tgz files.

**Comment by unzap** [comment]
Thanks for the reply @memsharded,

Concurrent usage is out of scope, just combining existing caches on client side.

So the only "safe" way to combine multiple existing caches on single host would be to run local conan server with following steps:

# disk_storage_path: ~/.intended_main_cache/data
> start local conan server

> export CONAN_USER_HOME=/path/to/cache_1
> conan upload * -r <local_conan_server>

> export CONAN_USER_HOME=/path/to/cache_2
> conan upload * -r <local_conan_server>

> repeats...

In case of conflicting packages/revisions the server should catch those so at least the error won't happen without notification(?)

**Comment by memsharded** [comment]
> In case of conflicting packages/revisions the server should catch those so at least the error won't happen without notification(?)

I would recommend an Artifactory CE (it is free), because it will be way more efficient (it has deduplication of files, caching, better concurrency). Also, it is possible to configure there the "delete" permissions, so you can upload new revisions, but you might be able to also block the accidental overwrite of an existing revision, by disabling the "delete" permissions. In short, the permissions control in Artifactory is more complete.

However, I have not seen other users doing this before, I would say the most typical approach will be using the same Artifactory instance used for the dependencies, but using another temporary repo, as you can have there multiple repos. If something goes wrong and someone needs to debug something, accessing that temporary repo is usually easier.

**Comment by memsharded** [comment]
Merging caches is still not possible, and specially in Conan 2.0 that it uses a DB heavily.
But there are plans to be able to backup/copy packages in/out of a Conan cache, lets close this ticket and follow up in the one already assigned for the 2.X roadmap in https://github.com/conan-io/conan/issues/10740
