### ISSUE TITLE
[question] How to maintain daily build and packages over Jfrog Artifactory

### ISSUE THREAD

**Issue by Prasaddiwalkar** [conan-io/conan#6146]
I want to maintain the gitlab pipeline for my application. There could be daily build for application, that would generate daily conan packages.

Please let me know how to maintain daily build?
How it impact the package version conanfile,py file in required/requirements?
How to get always latest and greatest packages from artifactory?

If you have sample code would help me accelerate my work.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Hi @Prasaddiwalkar !

For Gitlab and Conan integration, you can read this [documentation](https://docs.conan.io/en/latest/integrations/ci/gitlab.html).

> Please let me know how to maintain daily build?

Actually, your build should be executed after each git push. Otherwise, you won't be able to know the branch build status. Gitlab CI starts a new build automatically after a new push event.

You can run a daily build by [pipeline schedules](https://gitlab.com/help/user/project/pipelines/schedules). It's useful if your repository is big and take hours for each build, so you can schedule a nightly build the check your repos.

I recommend [Conan Package Tools](https://github.com/conan-io/conan-package-tools) which can help you a lot for building your packages, also, you can use Conan to create a gitlab template for you:

    conan new -cis -ciglg -ciu <artifactory_repo_url> foo/0.1.0

You can obtain more information about the command `new` [here](https://docs.conan.io/en/latest/reference/commands/creator/new.html)

>  How it impact the package version conanfile,py file in required/requirements?

I recommend reading [versioning introduction](https://docs.conan.io/en/latest/versioning/introduction.html) to understand some ways to distribute your package. In summary, you can override the same package version, if you don't increment the package version, you can use [package revision](https://docs.conan.io/en/latest/versioning/introduction.html#package-revisions) to use a strict revision.

>  How to get always latest and greatest packages from artifactory?

By default, Conan client will download the latest revision available in Artifactory. However, if you want to download the latest number  version available, you can use [version ranges](https://docs.conan.io/en/latest/versioning/version_ranges.html) or [alias](https://docs.conan.io/en/latest/versioning/introduction.html#package-alias).

Regards!

**Comment by memsharded** [comment]
Closing this ticket as responded.
