### ISSUE TITLE
Wrong ordering of settings in website-provided install command

### ISSUE THREAD

**Issue by dimi309** [conan-io/conan#615]
Hi everyone,

I've found a case where the install command provided by the conan.io website does not work for a package. If we go to:

https://www.conan.io/source/small3d/1.0.11/coding3d/stable

and, from the Windows "Debug" version, click on "Copy install command to clipboard", we get:

`conan install small3d/1.0.11@coding3d/stable -s compiler.version="14" -s compiler.runtime="MDd" -s arch="x86_64" -s os="Windows" -s build_type="Debug" -s compiler="Visual Studio"`

Running this in Windows, we get an error:

```
ERROR: compiler not defined for compiler.version
Please define compiler value first too
```

The command works if, as suggested, we bring the "compiler" setting in front, like this (I also had to add --build missing, but that's not a bug):

`conan install small3d/1.0.11@coding3d/stable -s compiler="Visual Studio" -s compiler.version="14" -s compiler.runtime="MDd" -s arch="x86_64" -s os="Windows" -s build_type="Debug"`

It might be a good idea to make sure that this is the command provided by the website. It's not a big deal, but it would make things easier for new users. Again, for new users, maybe it would be good if "--build missing" is also provided by the website by default (it never hurts to use it) but that's a matter of personal opinion :)

... and, by the way, I think that the error would be more understandable if it said:

`ERROR: "compiler" setting should be defined before "compiler.version"`

Ok, I'll stop with my suggestions now :D

**Comment by lasote** [comment]
I'm fixing it. Thanks!

**Comment by dimi309** [comment]
Great! You're welcome!

**Comment by lasote** [comment]
Fixed!

**Comment by dcatonR1** [comment]
If I hadn't stumbled across dimi309's post here, I would probably still be struggling with this.  Some, if not most of the install command lines on https://conan.io/source/OpenSSL/1.0.2g/lasote/stable have the same problem.

Also, it's not clear (to me as a new user, anyhow) why there are so many packages labelled the same.  Set a filter for build_type=Release and compiler.version=14 and arch=x86 for example, and six packages show up with no clear distinction between them.  

It's also not clear why one should use the lengthy command line examples provided vs a conanfile.txt.  Is it simply a different format and largely personal preference or are there things you can only do from conanfile.txt that you can't on the command line, or vice versa?

**Comment by memsharded** [comment]
Hi @dcatonR1 ,

Yes, basically don't use the web page install command as the reference one. The canonical way to use conan, as you pointed out, is via a ``conanfile`` (either txt or py), and that is the way described in the documentation. Please refer to the docs for the reference use of conan. Those web shortcuts are just for people that want to directly get the binary, to do some manual checks, but without a conanfile, the utility for a real project is very little.

Regarding the question about many packages, there are other things that can change besides those settings. For example, the Windows runtime that the artifacts linked with (the static windows runtime MT, or the dynamic windows runtime MD).

But it is true that there are some duplicated artifacts. Probably due to old binaries built with previous conan versions, that are not referenced any more. I think it might be worth to submit an issue to the Zlib package github repository. Do you want to submit it yourself? Thanks for noticing this and reporting!
