### ISSUE TITLE
[bug] GCC version 9 on Windows is not supported

### ISSUE THREAD

**Issue by manhnt9** [conan-io/conan#6160]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: 9.2 (MSYS2's MinGW)
  * Conan version: 1.11.1
  * Python version: 3.8.0

### Steps to reproduce (Include if Applicable)
Export a package with these settings:
```
-s compiler=gcc -s compiler.version=9.2
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
ERROR: Invalid setting '9.2' is not a valid 'settings.compiler.version' value.
Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '7', '7.1', '7.2', '7.3', '8', '8.1', '8.2']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

**Comment by czoido** [comment]
Hi @manhnt9,
GCC 9 is supported since Conan version 1.15, so I would suggest you update your Conan version to a newer one.
If you can't update Conan there's the possibility of adding GCC 9 to the file settings.yml in the user home directory but take into account that you could run into problems if the build helper is not considering any new options for  GCC 9.

**Comment by manhnt9** [comment]
I'm using chocolatey so let's see if I can update in the next time I boot to Windows (I work on Linux mainly). Anyways I had to add GCC 9 to my config. Sorry for my slow reply, this mail got into my Junk folder somehow.
