### ISSUE TITLE
[question] Conditional conanfile.txt

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#6177]
We use a package P from an upstream repo.  The upstream is in our company but I don’t have write access to it.  The upstream provides Linux packages with certain options (eg. `P:python=True`) and Windows packages with `P:python=False` and VS 2019.   We can use the Linux packages but we have to create our own Windows packages because we use VS 2017.

I created a Windows version of the package and put it in our repository.  That caused a problem because our repository was listed before the upstream repository.  When the Linux developers tried to download the package from the upstream repo they found the Windows package in our repo.  

The only way around this problem I see is to 1) rename the Windows package when uploading to our repo and 2) using `conanfile.py`, but I would like to avoid that.   `conanfile.txt` is ideal for consuming.

Ideally i would like `conanfile.txt` to be able to say (in one way or the other) “only use this package for Windows".  Is this possible?

If it were possible then the next thing would be to be able to continue searching repositories if you find a non-matching package in a repo.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @sourcedelica 

No, *conanfile.txt* doesn't have any type of conditionality. The alternatives are:
- Use a *conanfile_windows.txt* and conanfile_nix.txt* and call them explicitly
- Use a *conanfile.py*

IMHO, it doesn't make sense to invent a custom language for supporting these things, we already have python, and opening the door to conditionals in *conanfile.txt* is just going down the rabbit hole.

**Comment by sourcedelica** [comment]
I considered separate  `conanfile_${os}.txt` but I didn't like the redundancy.  I can get DRY with `conanfile.py` but I'd like to avoid using that for consumers.   Ok - thanks.

**Comment by sourcedelica** [comment]
What about an `[include]` for `conanfile.txt`?  That would solve the redundancy with getting into conditionals.

**Comment by memsharded** [comment]
We have previous experience with this, implementing it for ``profiles``: https://github.com/conan-io/conan/blob/develop/conans/client/profile_loader.py

As you can see this is far from obvious:
- Need to resolve as many nested of includes() as existing
- Need to prioritize and merge. What if an included() conanfile.txt requires pkg/0.1@user/channel, and the current one requires pkg/0.2@user/channel. Should it raise an error? A warning? Keep the current one silently? I see users requesting ``--no-raise-conflict`` arguments to be able to resolve different policies. Same applies to options, they can also be conflicting.
- Is it possible to override imports from included() conanfiles.txt? How? Because requires we could use the package name, but for imports, not possible.

Furthermore, all these mechanisms need to have their own testing, documentation, users need to learn about the syntax, evaluation order and priorities, overrides... In my opinion, it is not worth it, when you can write today:

```python
from conans import ConanFile

class Pkg(ConanFile):
  settings = "os"

  def requirements(self):
    if self.settings.os == "Windows":
       self.requires("MyWinDep/1.0@user/channel")
```

This has many advantages:
- Everything in a single file, no need to read several files to understand what will happen
- Possibly the most popular scripting language, a vast majority of users can understand this code.
- Keep conan codebase as simple as possible. Less code, less bugs, less maintenance, less support, more time we can use for more critical things
- It is order of magnitudes more flexible than any other strategy (include() or DSL for conditionals)

So while I understand the proposed convenience that you are suggesting, I still think it is not worth the investment.

Thanks a lot for the feedback!

**Comment by sourcedelica** [comment]
Thanks @memsharded, that's a pretty compelling argument :)
