### ISSUE TITLE
[bug] test_package build failed while generating graphinfo

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#6187]
[error_log.txt](https://github.com/conan-io/conan/files/3928926/error_log.txt)
[error_log.txt](https://github.com/conan-io/conan/files/3928921/error_log.txt)
### Environment Details (include every applicable attribute)
  * Operating System+version:ubuntu 18.04
  * Compiler+version: clang8
  * Conan version: 1.20.3
  * Python version: 3.6.8

### Steps to reproduce (Include if Applicable)
I have created a own package for mono.

The problem appears when using mono as `requires` step in the consuming conan recipe of ThriftMe. Then I want to access mono in the test_package of ThriftMe.
It seems to be that the whole mono is copied into the test_package build folder.

[test_package_conanfile.txt](https://github.com/conan-io/conan/files/3927601/test_package_conanfile.txt)
[mono_conanfile.txt](https://github.com/conan-io/conan/files/3927602/mono_conanfile.txt)
[thriftme_conanfile.txt](https://github.com/conan-io/conan/files/3927603/thriftme_conanfile.txt)

### Logs (Executed commands with output) (Include/Attach if Applicable)

[error_log.txt](https://github.com/conan-io/conan/files/3928928/error_log.txt)

**Comment by memsharded** [comment]
There are several things here.

1. If you have imports() in your test_package/conanfile.py:

```python
    def imports(self):
        self.copy("*", dst="bin", src="bin")
```
This is telling to copy absolutely everything from all the dependencies "bin" folders to the current bin folder. So totally expected. There are ways to limit that, like using ``root_package`` argument.


Overall, it is not looking good that you want to use in your test_package something that clearly reads like a "build_require" of your "thrift" package, not as a normal require.

Are you actually linking with the mono libraries in your final product? Because I see ``self.cpp_info.libs = tools.collect_libs(self)`` in the recipe of mono, that means yes, mono is intended to be as a normal require, not as a build_require.

I would also need the output and the error traces, please. Thanks!

**Comment by derived-coder** [comment]
I added the error log.
No we are not linking against mono.

**Comment by memsharded** [comment]
The ``self.copy()`` has been deprecated in favor of new ``copy()`` function, ``tools.collect_libs()`` is also obsolete, and ``imports()`` method has been replaced by ``generate()`` and explicit calls to ``copy()`` (or the new 2.0 deployers). Closing this ticket as outdated, please create new tickets if necessary, thanks.
