### ISSUE TITLE
[question] how to recreate build environment of a specific package (scm attribute, lockfiles)

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#6188]
I'd like to be able to recreate the build environment on my local PC for any of my packages stored on Artifactory.  This is useful for being able to investigate reported bugs in specific versions.

I think this can be achieved through the `scm` attribute and `conan.lock` lockfiles, but I'm not entirely certain how to use them for this purpose.

I imagined something like the following steps:

1. Get the recipe from artifactory.
2. Use the recipe to checkout the source code that was used to create the package:
    `conan source ...`
3. Install the exact versions of the dependencies that were used to create the package:
    `conan install ... --lockfile=<lockfile>`

Is this something that is possible?

The issues I'm current facing are:

- where to store the `conan.lock` lockfile?  My instinct is to add it as an `export`, but I think it might make sense for it to be built-in feature to store it along side the recipe (similar to `conanmanifest.txt`).
- `conan source .` cannot authenticate when getting sources from http url without adding the username and password directly into the recipe, which I'd rather not.

Thanks in advance!

**Comment by jgsogo** [comment]
Hi! That's indeed one of the paths that we are following, and it is more or less as you have described it.
 * The `lockfile` is still experimental, but we are working hard on the edge cases where it has some flaws still. Also, we would need to capture the full graph in it (build_requires included). Once solved, one option would be to store it with the package itself or use a hook and store it in a different Artifactory repository.
   Right now, this is something that you should workaround, as the path to the lockfile is not know at any hook... but if you are running commands locally (`conan create`) it should be available close to your working directory and you can upload it to a generic repository associated with the reference+recipe_revision.
 * About sources, using SCM is the right way to go (better than uploading the sources with the package), but Conan cannot facilitate the credentials if they are not stored in the recipe. Nevertheless, your developers should have access to the repositories and they should be able to configure the Git/SVN client to store the credentials and checkout the sources without being asked for them.

Maybe I'm missing something, so please, let me know where I'm wrong because this is one issue I'm very interested in.

Thanks!

**Comment by GordonJess** [comment]
Hi, thankyou!

There is a cost involved for us to get additional artifactory repos so I will instead workaround by storing the lockfile in the package itself.  I think this makes sense anyway since I wouldn't have to trace which recipe it is associated with.

I am also experimenting with [using lockfiles for CI](https://docs.conan.io/en/latest/versioning/lockfiles.html?highlight=lockfiles#how-to-use-lockfiles-in-ci), and it is helpful to be able to return the most recent one using conan ref patterns.

**Comment by memsharded** [comment]
This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
