### ISSUE TITLE
Visual Studio incompatible between minor versions

### ISSUE THREAD

**Issue by a-teammate** [conan-io/conan#619]
If the cached version is built with a newer minor version of visual studio (e.g. VS15 update 3) it fails to build the solution when building with a lower version (e.g. vs15 update 1).
At least for me.
The error is http://stackoverflow.com/questions/837073/error-c1047-object-file-created-with-an-older-compiler-than-other-objects.

**Comment by memsharded** [comment]
Yes, that is possible, the ABI compatibility is AFAIK, only in forward direction. So far, we have not been reported these problems, as people updating their compilers with updates didn't break linking with packages created with old updates, and the opposite didn't happen. 

In any case, I think that running with an old update like VS15u1 wouldn't be recommended, and updating is encouraged. Is there any specific reason you need to keep with VS15u1?  Thanks for your feedback!

**Comment by a-teammate** [comment]
Yes you are right, updating vs is probably recommended.  I just reported this from a usability point of view (Besides that conan is already in pretty good shape there and I think it's the C++ tool the world needed the most).  So maybe it could get detected and make conan error directly?

We had issues e.g. after upgrading to vs15 bc of a broken stdlib (e.g. Min max had been broken until I think update 2). If something alike happened to in minor version updates, we could be forced to downgrade to an older update.  But I guess the best would be to disable those caches or provide the packages with older compilers in that case.

**Comment by memsharded** [comment]
Hi Malte!

Thanks very much, very glad that you find conan in good shape and useful.

The default settings are editable, so if somebody really needs to handle the updates inside their organization, they could add an ``update`` sub-field to ``Visual Studio`` in file ``.conan/settings.yml``. But yes, I would say the most pragmatic approach is avoiding that unnecessary extra-complexity, just regenerating the packages if it is necessary to downgrade the compiler, because actually those issues between minors are really rare, they are most a thing between majors.

Maybe detect it in the "detect" phase (when first conan.conf is generated with defaults) and warning (not error, as it is not a real error), but that could get deprecated too if new updates are released. Not sure about the cost/value ratio, I would suggest closing the issue at the moment, and reopen if this becomes more painful. Cheers!

**Comment by a-teammate** [comment]
kk
