### ISSUE TITLE
[feature] cmake_find_package does not define <LIB>_ROOT

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#6202]
It would be useful in `Find<LIB>.cmake` scripts would define a `<LIB>_ROOT` cmake variable.

When writing a cmake script, meant for use in `self.cpp_info.build_modules`,
it is useful to have a `<LIB>_ROOT` variable defined.
That way absolute paths inside the package can be defined.
Also it might is useful for consumers.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
Hi! I added some comments to the bullet recipe you are submitting. IMHO none of the additional cmake files you are providing should be necessary.

**Comment by madebr** [comment]
The additional file is providing copies of the variables defined by the generators.

**Comment by lasote** [comment]
For what?

**Comment by madebr** [comment]
For users of the bullet3 lbrary.
To have no differences between the `FindBullet.cmake` of CMake and the one generated by conan.

**Comment by Johnnyxy** [comment]
Hi,
I support that feature request as this would provide me with the ability to copy additional files in the CMake ```install``` step.

For everyone who is using bleeding edge CMake versions have a look at the new automatically runtime dependency resolution feature of CMake (see [here](https://cmake.org/cmake/help/latest/command/file.html#get-runtime-dependencies)).

**Comment by memsharded** [comment]
This issue was reporting the legacy CMake integration, which has been superseded by the new one in Conan 1.X https://docs.conan.io/1/reference/conanfile/tools.html, and removed in Conan 2.0: https://docs.conan.io/2/reference/tools/cmake.html. Closing this ticket as outdated.

Please update to use the modern CMake integration, and please don't hesitate to open new tickets as necessary. Thanks!
