### ISSUE TITLE
[feature] Conan Hook : Runtime Dependencies - List / Save-To-File 

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#6229]
I've recently been doing a lot of work in my company to resolve runtime dependency requirements and conflicts between various products.  This has led to a lot of analysis with `ldd` on linux, `dumpbin.exe` on windows, and this tool: https://github.com/lucasg/Dependencies

In #conan channel of Slack, someone else was asking about a related topic, trying to ensure no `exe` or `dll` links with `vcruntime140.dll`.

In theory, it would be fairly straightforward to create a hook that prints the information near the end of every build or package step.  The hook could contain a fair amount of python code to improve the output of these programs, and then also potentially convert it to JSON and write it to  file, so that it could be packaged along with the artifacts.  

I wouldn't say we need this hook, but we would definitely turn on the printing for our production/release builds so that we can easily compare two old CI build logs and find when a new DLL shows up in the dependency tree. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by awakecoding** [comment]
I was the one asking about I could ensure that Windows executables do not link to the dynamic MSVC runtime (VCRUNTIME140.dll in this case). dumpbin could be used, but we need to parse its output, and wouldn't work for cross-compilation use cases. I found a possible alternative that can be compiled on all platforms without no dependencies, peldd (https://github.com/viaduck/pe-util). It works like ldd, but for PE executables instead. I wrote my own conan recipe to build the command-line tool, next I'd write a python function to automatically call it, parse the output, and check for forbidden import libraries.

**Comment by awakecoding** [comment]
In this case, we are discussing the problem of enforcing MSVC static runtime linking. The reason why a downstream check is preferred over enforcing compilation settings upstream is that build systems often have issues with MSVC runtime options, leading to some libraries being built against the dynamic runtime instead. The same approach should be applied for other platforms: don't trust that you asked nicely for specific build options, make sure they were correctly applied in the resulting build artifacts. Otherwise, everything builds and links correctly, and you only catch the mistake when a customer asks about this missing VCRUNTIME140.dll issue on their non-developer system.

For iOS and macOS, we wrote out own lipo wrapper to ensure that static libraries have all the expected architectures in them. We didn't write otool, ldd and nm wrappers, but these would be nice additions to check for specific symbols and libraries.

**Comment by solvingj** [comment]
I saw that you were working toward "policy enforcement", whereas this request was simply for build-time "ETL" of the information.  I thought it would be more achievable and broadly useful in the OSS community to start with a hook for this simple case.  If/when someone publicly implements the simple case, enterprise folks like us can either fork and modify that hook code for our more advanced uses, or potentially help design it in such a way that it provides a building block for us.  That's was the hope for the json output, to be something that a policy enforcement hook could consume.

**Comment by jgsogo** [comment]
I really think this is a hook we need. It can be very useful for the users, but also for `conan-center-index`. On top of this hook we would be able to check that we are not linking system libraries (at least unexpected ones), something that has happened before, like https://github.com/conan-io/conan-center-index/pull/255#issuecomment-548352324

**Comment by solvingj** [comment]
I've just come across a related need, perhaps the same hook, perhaps it should be a separate hook.  There are various mechanisms related to RPATH, at the very least, printing out RPATH/RUNPATH where it exists would be very helpful.
