### ISSUE TITLE
Value of 'default_options' from the dependencies is not available in 'configure()'

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6231]
I'm sure that this issue has been reported before, but I cannot find it 😓 

---

Recently, working in a recipe for `cpr` I needed to check the value of an option of a requirement: if CPR was being generated with OpenSSL, libCURL need it too.

The better/easier approach would be to write:

```python
    def configure(self):
        if self.options.with_openssl and not self.options["libcurl"].with_openssl:
                raise ConanInvalidConfiguration("libcurl must be built with openssl support")
```

but the value of the option `libcurl:with_openssl` is not available in the `configure()` function if it hasn't been set downstream in another consumer or by the user in command line. I mean, the `default_options` value written in the `libcurl` recipe is not available there.

To workaround it, we can move the check to the `build()` function, but that's not possible if we want to use the exception `ConanInvalidConfiguration` for its purpose. The other option is to force the value we need if it doesn't been forced in the opposite direction downstream:

```python
    def configure(self):
        if self.options.with_openssl:
            # If using OpenSSL, we need it to be active in libcurl too
            if self.options["libcurl"].with_openssl == False:  # 'is False' doesn't work here
                raise ConanInvalidConfiguration("libcurl must be built with openssl support")
            self.options["libcurl"].with_openssl = True
```

This is what we did in https://github.com/jgsogo/conan-center-index/pull/3 and it is heading conan-center-index.

**Comment by memsharded** [comment]
> but the value of the option libcurl:with_openssl is not available in the configure() function if it hasn't been set downstream in another consumer or by the user in command line

Yes, the real value of upstream dependencies options are NOT available at configure() time. Consider the order of evaluation described in https://docs.conan.io/en/latest/reference/commands/creator/create.html for example. The configure() method is executed to configure the dependency while expanding the graph. The dependencies are not there yet, it is impossible to know their options values. And trying to delay that to be able to get the value is not possible without incurring in a chicken and egg problem.

So this is definitely not a bug, it is this way by design.

Failing in the build() method is also insufficient, as it will only reach that point if building from source. That can be left there, it is not a bad check, but doesn't guarantee protecting against all configuration errors.

What is being defined in https://github.com/jgsogo/conan-center-index/pull/3/files looks good, maybe the ``== False`` can be better changed for:

```python
def configure(self):
        if self.options.with_openssl:
            # If using OpenSSL, we need it to be active in libcurl too
            if not self.options["libcurl"].with_openssl:
                  raise ...
            self.options["libcurl"].with_openssl = True
```

**Comment by jgsogo** [comment]
That's right 🤦‍♂ 

Given this misunderstanding that some users and I may have from time to time, in order to avoid it we could consider forbidding access to the value of those options on the `configure` method, wdyt?

```python
def configure():
    # A setter is allowed:
    self.options["libcurl"].with_openssl = True

    # A getter will raise
    if self.options["libcurl"].with_openssl:   # Raise!
```

**Comment by memsharded** [comment]
> given this misunderstanding that some users and I may have from time to time, in order to avoid it we could consider forbidding access to the value of those options on the configure method, wdyt?

The thing is that the use case when you are checking if someone is trying to set that option from downstream (profile or command line) still works. Your code above is a good example, it has reasonable behavior! So given our big user base, I would expect someone else relying on this, so I'd prefer not to break them now, but probably something we want to somehow check for Conan 2.0.

BTW: A good place to raise InvalidConfigurationException based on the final values is ``package_id()``. I haven't tried it, but it should work.

**Comment by memsharded** [comment]
This is obsolete now that we have ``validate()`` methods, it can access ``self.dependencies["mydep"].options`` real values to check if necessary.
