### ISSUE TITLE
Attach Changelog to the Package

### ISSUE THREAD

**Issue by tirolerstefan** [conan-io/conan#6247]
I have searched for a possibility to append / attach a changelog to a conan package of a certain version (or at least a changes diff).
Currently we have to provide a changelog for an uploaded conan package to our users, separately. Artifactory as server provides properties (key=value), but these aren't really suitable for large files.

I would ask for a (by client retrievable) changelog residing in or beside the package (like it is seen in debian packages).

**Comment by memsharded** [comment]
Hi @tirolerstefan 

Within Conan, the only way to attach such files is to add them during the ``package()`` method. Because the files are stored in a manifest with their md5 checksums, so a package is "immutable". It is not possible to add files after it has been packaged. If you added them during ``package()``, then it is relatively simple to fetch them, with the ``conan get`` command.

If you can't add them during ``package()``, I would strongly recommend to use a generic repository in Artifactory. That is a common use case. You can perfectly store large files there in paths that match your Artifactory Conan package layout, or you could store them in any other layout of your convenience and then add a property (changelog=url) to the package that will point to it.

**Comment by tirolerstefan** [comment]
Thanks, we will try this with a separate changelog repository, storing the link to the changes file in an own property. Additionally, we can listen on this property within an own Artifactory plugin.

**Comment by memsharded** [comment]
Ok, sounds good. Closing this at the moment, let me know if you have any further question, or you can always open a new ticket. Thanks for the feedback!
