### ISSUE TITLE
[question] Using branch as channel

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#6257]
**Background:**
My team has several in-house applications and libraries. For example, let's say appX depends on  libA, libB, and libC. A monolithic repository would look like this:
repo/libA
repo/libB
repo/libC
repo/appX

We are not currently versioning each component as one ideally would. Thus, everything is version 1.0.0 from the Conan perspective. Instead, we are tying the source code to binary artifacts by the Git branch. 

My solution to migrate us to Conan has been to use Git branch as the channel in the Conan reference:
`<package>/1.0.0@company/<branch>`

This approach, combined with `package_revision_mode` has worked. Each package recipe has something like this:

```
    def requirements(self):
        branch = self.get_branch()
        self.requires("libA/1.0.0@company/{}".format(branch))
        self.requires("libB/1.0.0@company/{}".format(branch))
        self.requires("libC/1.0.0@company/{}".format(branch))
```
Where get_branch() looks like this:

```
    def get_branch(self):
        try:
            branch = self.channel
        except errors.ConanException:
            branch = tools.Git().get_branch()
        return branch
```
The very first build on a new branch incurs the cost of ultimately building everything. While not ideal, it works given our current constraint of not being able to implement proper versioning across all components.

**Problem:**
Migrating towards a GitFlow-inspired Git workflow has complicated things; the convention to use a slash '/' character in the branch name is breaking the above approach as the slash character interferes with the Conan reference syntax. Errors like this rightfully pop up:

`ERROR: The reference has too many '/'`

One obvious approach would be to remove the slash character from the Git branch when interacting with Conan: feature/JIRA-12345 would become featureJIRA-12345, for example. A CI server calling on Conan to build packages would need to do the substitution and the get_branch() function above would need to do the same.

I'm posting in hopes of getting better ideas.

Thank you

**Comment by jgsogo** [comment]
Hello, @radonish. I wouldn't recommend you to use the fields `user/channel` in the reference like `fork/branch` in Git. Those fields are intended just to avoid collisions, for example, if you maintain a modified `boost` in your company, you can have `boost/1.71@mycompany/stable`, otherwise it is even better to get rid of `user/channel` and create your packages without it.

The best way to tie your package to a commit is to use the [SCM feature](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#scm), it can automatically store in your recipe file the commit of the repo your package was generated from. Then, Conan provides the [`revisions` feature](https://docs.conan.io/en/latest/versioning/revisions.html#package-revisions) that will add a hash to the _reference_ so packages won't get overridden. These features, together with the flexibility of the [`package_revision_mode`](https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?highlight=abi%20compatibility) (also read [this blogpost](https://blog.conan.io/2019/09/27/package-id-modes.html)) will let you do whatever you want.

Ok, **I know that was too much information in a single paragraph**, but those are the building blocks to work on your solution and I need to be sure that you know them. With those blocks, different companies have implemented different solutions for their teams, and I'm sure we can think about something that fits your needs (let me link here [ConanDays](https://conandays.conan.io/) too, if you can attend there will people from different companies talking about their CIs).

For the general case, `scm` + `revisions` + `recipe_revision_mode` (+ `graphlock`) is the silver bullet.

---

In your use-case you mentioned something a little bit different, you said that you were _"tying the source code to binary artifacts by the Git branch"_ and that might introduce a completely different element in this conversation. Does it mean that you are somehow living-at-HEAD at each branch? That you want to consume the last package available per branch?

Please, let me know more about your use case so I can understand it, I'm very interested in all these CI stuff.

Thanks!

**Comment by radonish** [comment]
Thanks for your response, @jgsogo - I'm curious to learn more about the [SCM feature](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#scm). I'll play around with it some tomorrow.

We are indeed living-at-HEAD for each branch; consuming the last package available per branch is exactly what I was trying to accomplish with the solution I described in my initial post. 

Again, I understand it's not ideal, but it removes the complexity of having to version and track version compatibility of dozens of in-house library packages. Constant recipe updates to get the latest dependency reference are avoided. Instead, the understanding is that all libraries within the repo on the given branch head are compatible and updated in sync; the dynamic get_branch() function method above means most developers just do their thing within the IDE (CLion) without having to worry about recipe updates. 

Does that help explain our use case? Thanks again!

**Comment by KerstinKeller** [comment]
Hi @radonish,

as I understand, you want to compute your `channel` based on your branch / git commit, but why not do it differently and compute your `revision` based on that same information? 

We've implemented a `get_version()` function which basically computes a version identifier based on a git commit:

```
def get_version():
    git = tools.Git()
    try:
        tag = git.run("describe --tags --dirty")
        return tag.strip("v")
    except:
        return None
```

which leads to

```
 def requirements(self):
        version= get_version()
        self.requires("libA/{}@company/stable".format(version))
        self.requires("libB/{}@company/stable".format(version))
        self.requires("libC/{}@company/stable".format(version))
```

The version doesn't contain the branch name but it's a unique identifier based on the latest tag in your repo (see [git describe](https://git-scm.com/docs/git-describe) )
Maybe this helps!

**Comment by jgsogo** [comment]
Yes, that is a quite common approach too, to get the version from the last tag (some people is adding meta information like `1.2.3+32` meaning that it is 32 commits ahead of that tag).

The main reason to not use the branch name in the `channel` part of the Conan reference is that when you want to promote your packages from one branch to another you won't be able to reuse them because the reference will be different and, in consequence, they will be _different packages_. From the Conan perspective. although the `package_id_mode` are very flexible, a reference `name/version@user/branch-1` and `name/version@user/branch-2` are different packages and when you move a recipe, you will need to change all the references to point to the new branch. I agree that your approach, where you compute the `channel` dynamically can workaround the big drawback, but you will need to compile again all the binaries whenever you move the recipe to a new branch (and probably this is how your developers are working: fork, new branch, code, compile,...).

Maybe the solution commented by @KerstinKeller is a good starting point: you can add the branch name to the recipe version (maybe you can omit it for the _master_ branch)... but again, your developers will use a temporary name for their branches and the packages for those names won't be available and they will need to compile everything from sources.  😞 

I'll try to keep thinking about it. A repository where you have a recipe in different branches (like forks of the projects), but from time to time those branches might diverge or be merged,... and you want at any time to know which is the last package available for each branch. The thing that breaks all of this is your developers creating temporary branches, it breaks everything unless you force them a naming convention.

**Comment by radonish** [comment]
Thank you both @KerstinKeller and @jgsogo for the feedback!

That is an interesting take to incorporate the `revision` into the `version` part of the package reference. I'll play around with that idea some. 

One complication I omitted above is that we have packages across more than one repo - there is logical separation for things like embedded SW vs. UI SW, but there are some common interface pieces we have in separate repos so both development teams can access them independently of all the other SW. We already have the convention of ensuring common branch names across the repos to deal with that complication, so I suppose any scheme here would need to ensure that convention is followed.

Thanks!

**Comment by johnmcfarlane** [comment]
Observation: decorating the version with any other details breaks patching, because the [conan-data](https://docs.conan.io/1/reference/conanfile/attributes.html#conan-data) entry no longer matches.

**Comment by memsharded** [comment]
Closing this as outdated.
With modern Conan, using channels is discouraged, channel should be empty or just a fixed string.
