### ISSUE TITLE
How to build Multiple projects with different conanfile.py

### ISSUE THREAD

**Issue by Prasaddiwalkar** [conan-io/conan#6263]
I am working on enterprise application to build our C++ libraries where we need to build multiple C++ libraries project.
We are using gitlab for SCM.

Where project structure would be like.

Group
   -- Project A
   -- Project B (Depends A)
   -- Project C (Depends A)
   -- Project D (Depends A and B)

ans so on.

What would be the best strategy to build all the libraries in single pipeline.

**Comment by czoido** [comment]
Hi @Prasaddiwalkar,

There are several ways to approach this depending on whether you are updating your libraries' versions or if you are using the revisions feature or not and the **package ID mode** you are using.

- If you want to rebuild everything each time without taking into account if the version or anything in the source code change or not then first do a `conan export` of all the projects and then call `conan install` or `conan create` for the **_Project A_** with the `--build` argument so it rebuilds everything every time.

- You can play with the [**package ID modes**](https://blog.conan.io/2019/09/27/package-id-modes.html) and depending on whether you are using revisions or not and the **package ID mode**, changes in the dependent libraries will affect their package ID's so that when you `create` or `install` **_Project A_** with the `--build missing` argument the dependencies will be rebuilt only depending on those certain changes.

Hope this helps 🙂
