### ISSUE TITLE
[question] Vendorizing conan dependencies

### ISSUE THREAD

**Issue by y4n9squared** [conan-io/conan#6274]
The documentation states that the *strongly recommended* way of installing conan is through pip, with the implication that all Python scripts running on that host will need to be run in a virtual environment in order to isolate itself from Conan's own dependencies. On the opposite end of the spectrum, there are OS-specific installers that attempt to ship a 100% dependency-free binary, at the cost needing per-distribution maintenance and a larger size footprint.

I'm wondering why Conan doesn't take a popular approach for Python command line tools (e.g. `pip`) which is to vendorize its own dependencies (while still requiring a standard Python installation). 

Something like

```bash
curl https://conan.io/get-conan.py | python
```

where a binary and lib/ directory is dropped into `${HOME}/.conan` (or a different path to remain isolated from data files).

This would make simultaneously working with Conan and other Python projects a bit more frictionless.

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @y4n9squared 

We haven't gone this way, because it is too much extra job (I agree with https://www.activestate.com/blog/how-to-make-python-dependencies-manageable/, for example) and puts too much extra burden on the maintainers and releases.

pip with virtualenvs and pyinstaller binaries seems to provide the community a good balance, many users can configure their environment as they wish (note that we do not recommend to use virtualenvs for your other applications, but for Conan itself. This is standard python practice anyway, not for Conan only). Generating the self-contained binaries with pyinstaller is quite easy and doesn't require maintenance and it is very important to save the blocker of users that don't or cannot have python installed. Bundling the python interpreter is very useful for a big part of Conan users. Vendoring dependencies while still requiring a python installation seems to be in the middle ground where the effort is too much and the gain is not that big.

**Comment by y4n9squared** [comment]
> Note that we do not recommend to use virtualenvs for your other applications, but for Conan itself.

Ah, I misinterpreted this part in the documentation. 

So if I am understanding you correctly, the official recommendation is that we install Conan directly into a virtualenv via pip, and if an unrelated Python process needs to use it (e.g. a build script invoking conan via subprocess), the call invocation in the script would need to be something like:

```python
subprocess.run("/path/to/venv/bin/python -m conan ...", shell=True)
```

or to similar effect.

**Comment by danimtb** [comment]
Yes, that is the normal practice
