### ISSUE TITLE
[feature][cppstd] A tool to check a standard version support in the current compiler

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan#6282]
Right now we have a tool to check the `cppstd` setting:
https://docs.conan.io/en/latest/reference/tools.html#tools-check-min-cppstd

The problem with it is that it checks either the setting or the default version on the current compiler. 
But the CCI doesn't support the `cppstd` so we can't use it because it'll trigger an exception on compilers that do support the version needed.

Required for:
https://github.com/conan-io/conan-center-index/blob/master/recipes/nanorange/all/conanfile.py#L22
https://github.com/conan-io/conan-center-index/blob/master/recipes/stduuid/all/conanfile.py#L30
https://github.com/conan-io/conan-center-index/blob/master/recipes/libsolace/all/conanfile.py#L31
https://github.com/conan-io/conan-center-index/blob/master/recipes/libsigcpp/3.0.0/conanfile.py#L43
https://github.com/conan-io/conan-center-index/blob/master/recipes/eastl/all/conanfile.py#L37

CC @uilianries

**Comment by uilianries** [comment]
The `check-min-cppstd` tool will use the default cppstd version supported by the compiler, for example, gcc9 is c++14.

When a project requires c++17, it contains in its cmake or any build script a flag for c++17. So the current way is validating the compiler version instead of the cppstd.

I would say `check-min-cppstd` is not the best tool for what we need. I see something more related to check if the compiler supports a specific c++ standard.

Related issue: https://github.com/conan-io/conan/pull/5997

**Comment by jgsogo** [comment]
Hi! This is an issue that is getting more and more relevant, and we don't have a _final_ answer yet. The best we can do right now is to gather all the comments and all the information together in one single issue, think about the alternatives, balance pros and cons and decide something. 

---

IMO the way to go would be (these are MY main lines to think about this issue):
 * conan-center-index needs to generate packages for some profiles containing `compiler.cppstd=xyz`
 * Conan should preserve the information about stable-vs-experimental support for C++ compilers
 * Major compilers can link libraries compiled with different **stable** CXX standards (up to now, the exceptions are exceptions)
 * Conan should handle the CXX standard information:
   + no more `CXX_STANDARD` defined in `CMakeLists.txt`
   + Conan will supply the proper value given the settings to CMake for `CXX_STANDARD` variable
   + Use `compatible_package_ids` (automatic) for **all stable versions** of the cppstd supported by the compiler version

**Comment by KerstinKeller** [comment]
Maybe a good way to think about this whole problem are three different values:
- The standard actually used to compile the package
- The *minimum* standard required for the package code to compile
- The *maximum* standard supported by a given compiler

The actually used standard basically an input of the recipe, it posssibly translates to compiler flags, or `CXX_STANDARD` CMake variable.

Then the package itself has a requirement which needs to be fulfilled, e.g. that the code of the package requires at least standard X (e.g. C++98, C++11, C++14, C++17, ....). This  could be an attribute of the package, e.g. like it's name or version.

And then each compiler has a set of standards which it supports. (GCC 5 supports `cppstd <= cxx11`). Conan would have to be responsible to track that information.

If a selected compiler does not support the minimum version requested by the Conan package, Conan could automatically throw an `InvalidConfigurationException` in its `configure()` method.


CMake actually has a similar approach, possibly even more detailed. Instead of requesting one standard (which you can do), you can request compile features, see [here](https://cmake.org/cmake/help/v3.16/manual/cmake-compile-features.7.html) for the general processs, and [here](https://cmake.org/cmake/help/v3.16/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#prop_gbl:CMAKE_CXX_KNOWN_FEATURES) for a list of all actual features.

**Comment by Minimonium** [comment]
@KerstinKeller I've been informed pretty recently that CMake developers discourage using granular features. There weren't any new ones for quite some time now. Instead, we should opt to use the `cxx_std_*` variants.

@jgsogo The best practice would be to patch out the `CXX_STANDARD` (I see it in a lot of projects that write their CMakeLists for the development first) and pass it via a toolchain or the basic setup function. 

After initial experiments in the CCI and some discussions, I'm started to be pretty convinced that a standard version support check is very impractical. 

Compilers do add features in batches. But from version to version the range of features is very different. I don't see how one would be able to keep the list of all features used by a project with sufficient fidelity. 
At the same time, a C++11 on one compiler's version is not the same C++11 as on the other. For example, the `ranges-v3` library didn't support MSVC until very recently because of missing C++98 features even at the latest versions. 
Standard version restricted packages in the CCI sometimes require different compiler versions despite needing the same standard version - `cpp-taskflow` and `entt`.

How I see it being practical (at least in the context of the CCI):
* The check that we have now is a good one, we can sanitize resulted configurations to force the compatibility. We can have a blanket "requires C++XX" restriction.
* Have a dictionary of known supported compilers with minimal versions for a given recipe. Bailout early if we know that the compiler version is not supported.
* Otherwise, report a build failure on an unknown compiler as a possible(?) configuration error. We need some useful reporting on that one.

**Comment by Minimonium** [comment]
I'll close this issue since I no longer see the value in such a tool.
Please comment in https://github.com/conan-io/conan-center-index/issues/54#issuecomment-586006591 if you have an additional feedback on how to handle compatibility.

**Comment by jgsogo** [comment]
Great. I will block this thread too, so every comment should go to the issue you linked above. Thanks!
