### ISSUE TITLE
[question] How to support CMake "Interface" libraries and per-library cflags

### ISSUE THREAD

**Issue by nolange** [conan-io/conan#6329]
I have a [package](https://bintray.com/nolange79/conan/xenomai3%3Axenomai3#files/xenomai3%2Fxenomai3%2F3.0.9%2Ftesting%2F0%2Fexport) which generates a set of libraries and a set of interface targets, which don't have a real library behind them. See for example this target, whic just adss compiler and liner switches

```cmake
# Create imported target Xenomai::posix
add_library(Xenomai::posix INTERFACE IMPORTED)

set_target_properties(Xenomai::posix PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "__COBALT_WRAP__"
  INTERFACE_LINK_LIBRARIES "-Wl,@${_IMPORT_PREFIX}/${_xenomai_libdir}/cobalt.wrappers;Xenomai::cobalt"
)
```

I dont believe conan can currently create them?
Also those libraries have separate C/LD FLAGS, which again conan is not able to provide.

Note that the package would provide a full config for CMake, so all that would be needed to use those would be adding "usr/lib/cmake/xenomai" to the find_package path. (Also relevant: #4967)

```cmake
include(${CMAKE_BINARY_DIR}/conan_paths.cmake)
# not quite happy with conan not creating these...
set(Xenomai_DIR "${CONAN_XENOMAI3_ROOT}/usr/lib/cmake/xenomai")

find_package(Xenomai 3.0 REQUIRED)
```

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi! Your question has different approaches:

Talking about builtin generators that create CMake targets (`cmake`, `cmake_multi`, `cmake_find_package` and `cmake_find_package_multi`): Conan creates one target per library defined in `cpp_info.libs` (and one more target to group them all), all the information defined in the `cpp_info` object is applied to each one and every target. So that is something not doable in a single package (we would need the components feature to allow something like that: https://github.com/conan-io/conan/pull/5408)

Creating your own generator: you can access the information in the `cpp_info` object and interpret it according to your needs. I highly discourage this approach as your package won't work with other generators and it won't be reusable by the community.

Package your own `FindXenomai.cmake` (or the config equivalent) and consumers will use it. At this moment we have good reasons to [forbid `.cmake` files in `conan-center-index`](https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#kb-h016-cmake-modules-config-files) and use the Conan generated ones, but for your own library, if needed, this is likely the way to go right now.

**Comment by memsharded** [comment]
This ticket was using the old generators (legacy in 1.X, removed in 2.0), that have been superseded some time ago by new ones. Closing as outdated, please check the new ones and don't hesitate to open new tickets as necessary for any further question.
