### ISSUE TITLE
[question] Local dev workflow for multi-library packages

### ISSUE THREAD

**Issue by Manu343726** [conan-io/conan#6340]
Related to https://github.com/conan-io/conan/issues/2387 and https://github.com/conan-io/wishlist/issues/197

While working on my llvm packages I often find hard to `create` all packages from scratch, since the  inter-dependencies of the different libs pull their recipes either from my local cache or from bintray. This makes really hard to test a change in one of the package templates since I have to make sure I'm creating the packages in the right order so that deps are up to date. Of course this is a manual process that often ends up in mistakes and packaging bugs.

What do you think could be the best workflow for situations like this? I'm not asking specifically about a feature of the conan cli, even a simple idea or guideline would be really appreciated.

Thank you.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @Manu343726 .

You can compute the build order of your graph using the [graphlock feature](https://docs.conan.io/en/latest/reference/commands/misc/graph.html):

 1. Create the graphlock of all the libraries, call `conan graph lock` using the root of your graph with a clean installation of all your packages. You will get a `conan.lock` file listing all the references with the exact version and the package reference in that moment.
 2. Now, move to the working space where you are modifying one recipe, and use the graphlock when creating that library, use it with
    ```
    conan create .... -l conan.lock
    ```
    Conan will update that `conan.lock` with the reference that has been modified (the recipe you have just created), the JSON should contain a `"modified": "Build"` for that recipe.
 3. Now you can compute the build order: `conan graph build-order conan.lock`, Conan will list the list of libraries that have to be built considering the one you have modified (all downstream until the root of your graph). Indeed, it is a list of lists because some of them can be built in parallel.

FAQ.- _I've modified a library and Conan says that nothing has to be rebuilt, what's happening?_ Conan decides if a library has to be built based on the computed packageID. Depending on your `default_package_id_mode` (more about it [here](https://blog.conan.io/2019/09/27/package-id-modes.html)) it will need a new library or the old one will be valid.

These are more or less the steps we suggest for a CI too, to rebuild the full graph of dependencies (minimizing the build time) and decide if a PR to one library should be accepted or not.
