### ISSUE TITLE
[feature] A type of lockfile that only captures recipe IDs/revisions

### ISSUE THREAD

**Issue by Daniel-Roberts-Bose** [conan-io/conan#6345]
Currently lockfiles are designed to be able to reproduce a build, down to the RREV and PREV for that recipe and package. There are some use cases however, where you want to be able to reproduce a build based on the RREV but not the PREV or package ID. 

One such use case is where you have many dependencies and you want to "snapshot" a list of dependencies and the recipes that created them, but don't want to capture the package IDs so that later you can build them with different options and settings, while maintaining the same dependency graph (from the perspective of using the same source code). 

An example in my case would be that I have multiple profiles with different settings. I want a lockfile that is capable of being used between profiles, that simply locks the recipe version and revision.

It would be great if there was either another type of lockfile, or perhaps simply when using a lockfile (`conan install . --lockfile xyz.lock`) there is a way of telling the install command to only look at recipe version information and ignore any unique package information.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Daniel-Roberts-Bose 

The problem with this is that this kind of lockfile is impossible by definition. Every different profile evaluates to a different graph. Simple case:

```python
def requirements(self):
     if self.settings.os == "Windows":
         self.requires("MyWinDep/1.0")
     else:
         self.requires("MyXDep/2.3")
```
This can take many variants, changing based on options, even changing the upstream options as well (as propagating the ``shared`` options to upstream packages), or using different build_requires in different platforms.

It is not just ignoring or dropping the packageID, keeping the recipe/version. The topology of the graph can be quite different. 


The assumption that "in my graph I don't do that, so it is safe to do it", we have learned that is a sure road to huge pain, from the maintenance point of view, support, uncountable bugs and corner cases. It is already very difficult to keep the project moving forward with relatively strongly well-defined behavior, to introduce these type of cases, they would take us in practice to a halt.

This is the reason why the effective profile is also stored together with the lockfile. We have learned that maintaining the lockfiles without that profile information is way more complicated and error prone, difficult to manage in practice.

In reality, we haven't seen so far any problem with maintaining the resulting set of lockfiles, one per profile/configuration. I would strongly encourage to try to follow this recommended practice, it seems to work pretty well, with the only different to store N lockfiles instead of 1. Is there any strong pain that you are trying to solve with this proposal?

**Comment by Daniel-Roberts-Bose** [comment]
Hmm I definitely understand that this is a highly complex issue to solve, and I definitely agree that you should not be implementing generic features that are only useful to one or two edge cases. It is also very true that the graph could and likely will look very different between profiles, as highlighted by the simple example above. However, would it not be possible to have a simple check and if the requirement does not exist in the lockfile, include the new requirement and evaluate it with no constraints. On the flip side of that, if a requirement exists in the lockfile but is not part of the current graph then remove it from the graph lock?

I understand that this issue is highly complex and bordering on the impossible so let me try to fully explain my use case and issue :) I do have a solution that I am currently using to hack around the limitations of conan but I wanted to see your thoughts on a generic solution for mass use instead of my specialized one.

I have briefly explained this scenario before in previous posts but let me try and go somewhat in depth. I have a top level build that requires both 32 and 64 bit binaries. These are my two profiles, 32 and 64 bit, each one sets various cmake configurations based on the architecture, and some other internal settings we use. A quick and dirty solution is to simply build one entire graph and then build the other graph, then package up those individual binaries. However this in practice doesn't work for us for one very simple reason, a constantly moving release train, let me try and explain with this scenario.

1. `conan create . -u -pr 32bit -j create32.json` is run
2. While this create is running (sometimes up to 4 hours). A change gets committed to some dependency within that tree that affects ABI compatibility
3. `conan create . - u -pr 64bit -j create64.json` is now run and pulls in the new dependency
4. The overall build is now inconsistent because the 32 and 64 bit binaries are no longer compatible

In reality, we are actually running 3 different profiles that all need to be consistent also, further increasing the likelihood of a compatibility problem cropping up. Furthermore, we also have some shared objects and libraries that we use between the binaries which has potential to cause more serious problems than simple API incompatibility.

In order to ensure we don't run into any sort of compatibility problems, we need to guarantee that all create commands are run with the same versions on each dependency. (the same source code)

The solution we have in place right now is to parse the `create32.json` and then include requirements based upon the versions we obtain from that, but this method is hacky and I was hoping for a more generic solution that works across any conan command. 

A couple of solutions and notes that we also tried:
1. Don't pass `-u` on the subsequent create commands. In practice this didn't work because we have some dependencies unique to each graph we did need to update
2. Try use the lockfile between profiles. This one clearly doesn't work for obvious reasons :) 

If you can suggest any alternative solutions to this problem that would be great too!

**Comment by nioncode** [comment]
I'm also very interested in something like this.

Let me briefly describe my (simplified) use case: I build a library that consumes `libcurl`, which itself requires `openssl` (though I don't care about this transitive dependency from my program point of view). When I now `conan install` at different times, I will get different `openssl` versions, since the `libcurl` recipe regularly gets updated to link against the latest `openssl` version. So clearly I need some way of pinning all transitive dependencies to ensure that our CI builds always build with the same dependency versions.

This is exactly what lockfiles are there for. However, as far as I know from reading up on them the last hour, they are quite complicated to use. From a developer perspective, I'd assume a workflow like this:
```bash
# in my source tree
conan lock > conan.lock
# later, whenever I want to build
mkdir build && cd build
conan install --lockfile ../conan.lock ..
```

However, as lockfiles currently work, it seems they have the following downsides:

1) Lockfiles must be created on the machine that wants to use the lockfile in the future (I think). This means I would have to create a CI task that generates the lockfile on each build machine (e.g. we have windows-x86, windows-x64, Android, and a couple Linux distros) and checks it into git (or modify the build script to do this in case the lockfile does not exist, yet, which leads to the problem in 2). I cannot generate the lockfiles manually, since I would need to have the exact system configuration of the target machine at hand, which is unfeasible if having 10+ different machines.

2) When adding a new build machine (e.g. for a new Linux Distro with a different compiler requirement), I have to recreate the lock file on this machine. Imagine I add this new machine 1 year after I created the lockfiles of the other machines. Is there a way to get the same dependency versions for this lockfile as I did for the other lockfiles or do I have to choose between a) possibly getting newer revisions in this lockfile and thus this single machine builds with different revisions, but is then locked to those going further, or b) regenerate all lockfiles again (at the same time) to ensure that all resolve to the same revisions, which would then potentially bump the dependencies for all build machines and thus potentially break the compatibility of previous builds?

From a developer's perspective, what I'm really looking for is a way to say 'these are the dependency versions I tested with, please lock the graph' and not be required to do this on every possible build machine that I might add in the future.

Am I correct that I can achieve this feature by using Package Revisions in my `conanfile.txt` and overriding each transitive dependency with a fixed revision? This would still be way easier for me to maintain (assuming we only have a few dependency, which is currently the case) compared to creating and maintaining lock files for 10+ build configurations.

Is there some kind of blog post / example on how to use lockfiles on a sample project with multiple dependencies + build machines in the real world that might show how I can solve my pain points outlined above?

**Comment by memsharded** [comment]
This was done some time ago, for some reason this issue was not closed.
Lockfiles already support the ``--base`` argument, that allow to capture lockfiles with only package reference and revisions, but without package-id, package revisions or profiles, so these lockfiles are generic for any configuration, and can be used to instantiate any configuration specific lockfile later. We keep iterating the lockfiles, and for sure many things to improve, but I think this feature can be considered implemented.

**Comment by nioncode** [comment]
@memsharded I had a look at the documentation of the `--base` option (https://docs.conan.io/en/latest/versioning/lockfiles/configurations.html#base-lockfiles), but I cannot get them to work for my use case (where I just want to capture the package graph and then apply it later on for different configurations):

```
conan lock create conanfile.txt --lockfile-out=conan_release.lock --base
mkdir build && cd build
conan install .. --lockfile=../conan_release.lock
ERROR: Lockfiles with --base do not contain profile information, cannot be used. Create a full lockfile
```

So now I'm back at the start and have to create a full lockfile for each architecture that I want to build for. What is your recommendation for handling this use case?

**Comment by memsharded** [comment]
Hi @nioncode 

Yes, the specific lockfile with the configuration needs to be computed, but the main difference is that you don't need to store it, for example. You can use the "base" lockfile for all configurations, and in any CI server that is going to build a specific configuration you call ``conan lock create --lockfile=input.lock --lockfile-out=output.lock`` to compute the new specific configuration lockfile for the profile you want, and then apply it.

We have considered trying to use it directly, but it had a couple of ugly cases, and problematic implementation in the internals, and we haven't succeeed so far. It is also true that we are trying to further iterate lockfiles as a whole to simplify the whole process, lets see if we manage to do so.

**Comment by johan-boule** [comment]
I'm still unsure the `--base` option prevents breakages that occur every time a new recipe revision is published on conancenter, especially the deadly bump of minimum conan client version requirement. We need to be able to reconstruct exact source and recipe dependencies over a decade. That's the slow pace which real-world projects deal with.

Ideally, conancenter should archive the full source code of every package, like linux distros do, and not rely on the ever-changing external websites from the wild internet, which will inevitably break anytime. In enterprise, having an immutable, self-contained archive is a requirement.

Reading the documentation page for the option, it doesn't seem to record the recipe revision in the lock file.
In an earlier comment in this issue, you said:

> `--base` argument, that allow to capture lockfiles with only package reference and revisions, but without package-id, package revisions or profiles

Did you mean _only package reference and **versions**_ ?

If I understand the terminology right, we want to capture the RREV but not the PREV.

I tried to create the lock file with the env var `CONAN_REVISIONS_ENABLED=1` but nearly all packages end up having a `#0` revision, which doesn't look right.

**Comment by memsharded** [comment]
Hi @johan-boule 

I'd say that you are getting the old, revision-less revision from your local cache, installed before you activated revisions. So please:

- conan remove * -f
- activate revisions
- conan lock create --reference=zlib/1.2.11@ --base
- The lockfile will contain the revisions

**Comment by johan-boule** [comment]
I actually had a second problem, which is I was using conancenter through a Nexus 3 proxy, which doesn't seem to handle revisions.
Thanks a lot for your prompt answer. It's working now :)
