### ISSUE TITLE
[feature] cookiecutter style templates with conan new command

### ISSUE THREAD

**Issue by AnticliMaxtic** [conan-io/conan#6346]
I would like to extend the concept introduced with  #5192 to include more than just the conanfile.py file. 

Basically, I would like to be able to call cookiecutter (or similar) from within Conan, so that I can generate package templates and include them in my conan config repo that I distribute to the rest of my team. 

As an example,  I could use https://github.com/AnticliMaxtic/conan_config 

``` 
$ conan config install --type git https://github.com/AnticliMaxtic/conan_config.git
$ conan new cpp_proj/0.0.1@AnticliMaxtic/stable -t cpp 
```

I obviously could just call 

```
$ cookiecutter ~/.conan/templates/cpp 
```
but the fewer tools I ask my developers to install and use explicitly, the better, even if I am directly calling cookiecutter from within conan. As a first step, the  

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Would it be just an extension of the file template to a folder? In that case it should be relatively easy to implement. If you know some python, would you like to give it a try?

**Comment by TheQwertiest** [comment]
@memsharded , I would like to implement this feature. I.e. ability to specify directory with multiple files as a template.

The main question is about CLI (since naming things is hard). Currently I'm thinking of smth like this:

`conan new package_name [-md, --template-directory TEMPLATE_DIR]`. (since currently it's `-m, --template` for template file)

TEMPLATE_DIR must contain `conanfile.py` and might have any other arbitrary files.
jinja is applied to all files in that directory.


Another thing that I want to do, (don't how to implement in this feature tho) is to somehow replace dir names in template. E.g.
- template
  - conanfile.py
  - Makefile
  - src
  - include
    - `{{package_name}}`

**Comment by TheQwertiest** [comment]
Further improvements for `--template-dir`:
`--overwrite-policy {overwrite, skip, ask}` - this would allow to convert existing non-conan projects.
