### ISSUE TITLE
Showing recipe creation date in conan info

### ISSUE THREAD

**Issue by Prinkesh** [conan-io/conan#635]
Adding package creating dates in these commands will help end users to look for packages easily , packages can then also be sorted by date in search command

**Comment by lasote** [comment]
Showing the creation date is a good idea. So let's tag it as approved. 
The search sorted by date, well, it can be handler later, it requires a little more thinking about user interface (command line options for sorting), website implication, search engine...

**Comment by Prinkesh** [comment]
What is better way of implementing this 
* reading time from conanmanifest.txt
* exposing the time in disk adapter search results itself by getting last modified time of the files

**Comment by lasote** [comment]
Reading the modified time of the files is not correct because it is not the creation date, just the "retrieve" date.
We should read it from the conanmanifest.txt, for the "info" command should not be a big problem, but with the "search" command I see a problem, recipes couldn't not be in local if we search in a remote, and the search interface doesn't retrieve the manifest.

**Comment by annulen** [comment]
Also, website should show modification date for each binary package and conanfile

**Comment by lasote** [comment]
Conan search command can't easily show the date of packages. It implies the indexer information and the modification of servers.
This feature will only show the date in the `info` command for recipes.
