### ISSUE TITLE
[question] how to access version passed from command line in conanfiles that dont specify version

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6356]
I have scenario where I have multiple files in my repository for example:
1.0.0.tgz
1.1.1.tgz

And I have conanfile that is to support multiple versions of these packages, hence  I am omitting the version from the conanfile and i am passing it via commandline.

Problem is: 
How do I access 'version' in the exports_sources? I do have version in the methods, but it seems its not accessible on attribute level
```
from conans import ConanFile, AutoToolsBuildEnvironment, tools

class MyConanfile(ConanFile):
    name = "my"
    exports_sources = "{0}.tgz".format(????.version)

```

I cant move do this in a 'source' step as I want to fetch directories from the repository where conanfile lives rather than externally.

I couldnt not find any help with regards that on the docs. 
And in your recipes - you use def source() for that and access external contents ( in relation to the conanfile origins. )

**Comment by memsharded** [comment]
Hi @fulara 

The problem is that ``exports_sources`` is a class attribute. It is not intended to have that level of dynamic assignment, as it is evaluated at python parse time, and unless the version is there explicitly, there is little that can be done.

Are those .tgz sources, and not binaries, right? Just to make sure.

The only possible automation that I see at the moment would be to copy the x.x.x.tgz to "source.tgz" just before the package creation/export, based on the version that you are going to use. To be automated in the recipe, I think we would need an ``export_sources()`` method, which we don't have yet. While seems valid and interesting, it also seems that we don't have the resources to prioritize it at the moment.

Another alternative, if you have the conanfile.py recipe and the set of x.x.x.tgz files in a source repo, would be to use the ``scm`` component. This does not use any copy of those sources in the recipe itself, it just stores the commit, so it can later reproduce builds. Using the right ``self.version`` inside the ``build()`` method, to decide which .tgz to explode to build should be straightforward. I think this would be a recommended approach, it seems the ``scm`` component is becoming the most used way to address sources, so I'd recommend to give this approach a try.

**Comment by fulara** [comment]
I need to learn how the 'scm' components works - as I totally missed introduction of it :).

In our particular solution we decided to solve it as follows:

exports_sources="package-*-.tgz"
and in place of '*' we are putting libraries.
This exports all tgz' to source dir, but then we select it in the `def source()` method.


Anyway - I am kinda surprised that conan does not have a method that has the `exports_sources` functionality. 

You can close this item if you wish.

**Comment by memsharded** [comment]
With this and the ``set_version()`` methods (were added later than this issue), I think this issue can be closed, but please re-open if I am wrong. Thanks!

**Comment by fulara** [comment]
Yes, that seems to be perfect fit, thanks.
