### ISSUE TITLE
[bug] Conan 1.21.1 breaks existing recipes using cmake targets

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan#6357]
CMake targets generated using 1.21.1 have changed from conan 1.21.0

Steps to reproduce:

```
pip install conan==1.21.0
conan install eigen/3.3.7@conan/stable -g cmake
grep CONAN_PKG:: conanbuildinfo.cmake
```

outputs

```
add_library(CONAN_PKG::Eigen3 INTERFACE IMPORTED)
```

Whereas

```
pip install conan==1.21.1
conan install eigen/3.3.7@conan/stable -g cmake
grep CONAN_PKG:: conanbuildinfo.cmake
```
outputs
```
add_library(CONAN_PKG::eigen INTERFACE IMPORTED)
```

**Comment by jgsogo** [comment]
Hi! This is not a bug nor a regression in this version. It is how we think we can bypass a misunderstanding we had with the `cpp_info.name` and `cpp_info.names` features in recipes in `conan-center-index`. You can read all the rationale starting in this comment and the links from there: https://github.com/conan-io/conan/issues/6269#issuecomment-570182130

In this version (v1.21.1), the `cmake`, `cmake_multi` and `cmake_paths` will use the name of the package **without taking into account `cpp_info.name`** (they also use `cpp_info.names["cmake"]` and `cpp_info.names["cmake_multi"]` if present).

**Comment by planetmarshall** [comment]
Thanks for the explanation, though it does contradict what is stated here on the [Conan Release Notes](https://docs.conan.io/en/latest/changelog.html) - 

> Conan 1.21 shouldn’t break any existing 1.0 recipe or command line invocation. If it does, please submit a report on GitHub. Read more about the Conan stability commitment.

As any recipe which uses `CONAN_PKG` cmake targets where the name has changed *will* break (as our CI did last night due to this change).

**Comment by jgsogo** [comment]
Yes, we knew it could break some users, but this misunderstanding was propagating bugs to the recipe files (those changes in `conan-center-index` were breaking users with each new revision). Now we know how we want this recipes to work and the community agree with it (many recipes has been changed from `cpp_info.name` to `cpp_info.names` thanks to this patch/fix/workaround).

The fix for your work environment is really easy, just declare the name for your generator:

```
def package_info(self):
    self.cpp_info.names["cmake"] = "Eigen3"
```

I'm sorry this has bitten you, are you using `eigen` from `conan-center-index`?

**Comment by planetmarshall** [comment]
We use our own fork of `conan-center-index` and cache the packages we use locally due to network issues. I'll apply your fix, thanks.
