### ISSUE TITLE
conan search doesn't show binaries for packages with short_paths=True

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#637]
Version: 0.14.1

Not sure when it was changed, but conan does no longer store the final package in the 'packages' folder, but only a .conan_link file pointing to C:\.conan\tmp... I guess that since that time, `conan search PACKAGE_REF` does no longer list the packages that use the .conan_link file. Packages created with an older version of conan, which still stored the complete final package in 'packages' folder work fine.

**Comment by memsharded** [comment]
Yes, aware of that, sorry for the inconvenience. Could you please try running from source, "develop" branch? There were a couple of issues with ``short_paths``, one important one being reported by users that required the package folder also to be shortened, as they had very long paths in the headers. This has been solved by PR #624, will be released in next 0.15 (hopefully very soon), together with some additional issues created by this new functionality, one of them, the search. Note: It will be necessary to clear the local conan cache, because of the new short_paths structure to be introduced in 0.15.

 If you can try running from source ("develop" branch), that would really help to test things before next release.

**Comment by Blubbz0r** [comment]
With "It will be necessary to clear the local conan cache" do you mean that I need to remove the local packages and simply install again to retrieve the binaries already in the remote? Or will I need to rebuilt and reupload the packages altogether?

I will see if I find the time to test running from source. The issue itself is not too critical. Uploading packages still works fine and searching them in a remote, too. So the general workflow is still working properly.

**Comment by memsharded** [comment]
Removing them from the local cache (``conan remove "*"``) and retrieving them from the remote should be enough. In remotes, packages are stored as tgz files, so the long paths are not an issue. The moment they are retrieved from the remote and unzipped, they will be put in a ``short_paths`` location in the local cache if needed. 

Ok, we plan to release it this week, so if you are fine waiting, it is ok. If you find time to test from source, please report.  Thanks!
