### ISSUE TITLE
[question] Why python_requires package_mode is global?

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6381]
Just tried to use new python_requires. and I am slightly confused by the choice behind impact on PackageID and actually lack of any clear statement hinting that it is intentional.

1) When using normal dependencies and you want to use different package_id_mode you have to do it like so:
```
self.info.requires["dependency_name"].patch_mode()
```
2) However in python requires the setting is global:
```
self.info.python_requires.patch_mode()
```
You cannot do:
```
self.info.python_requires["dependency_name"].patch_mode()
```

Considering that you explicitly give an exmaple of depending on multiple python_requires that seems confusing?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The reason is mostly to keep things simple.
With normal requires, different libraries can indeed affect in different ways, if they are header only, or static, or shared, depending on how they evolve.

With python_requires, initially it seems that such a fine grain to make your recipes change the package_id based on some python_requires and not others seems unnecessary. The proposed approach allows to have fine control over the effect managing the versions of the python_requires, because it is a dynamic language that behaves much better regarding semantic versioning, something that due to the compiled & linked packages is not possible with normal requires.

**Comment by fulara** [comment]
Hm, Interesting.

First thing I did though is to mark my package as `unrelated_mode`.  as this is intended to be a package that has 'common code' you can call it. 

Okay, I am hoping that I wont find a need to have a different kind of dependencies that should have impact package_id.
