### ISSUE TITLE
[bug] shell spawned by conan sees wrong shared libraries

### ISSUE THREAD

**Issue by matt-cross** [conan-io/conan#6425]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16.04.6 LTS
  * Compiler+version: n/a
  * Conan version: 1.21.1
  * Python version: 3.5

### Steps to reproduce (Include if Applicable)

1. On an Ubuntu 16.04 machine install the package conan-ubuntu-64_1_21_1.deb
 from https://github.com/conan-io/conan/releases/tag/1.21.1
2. Run "conan -v" to see the error message

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
mcross@mcross-desktop:~/tmp$ conan -v
/bin/sh: /opt/conan/libtinfo.so.5: no version information available (required by /bin/sh)
Conan version 1.21.1
```

When I run conan under strace, it looks like this is coming from a spawned instance of /bin/sh as it is loading shared libraries, and it seems to loading libtinfo from /opt/conan instead of the system libraries.  I suspect that conan (or perhaps the framework it is packaged in for this bundle) is setting `LD_LIBRARY_PATH` and that is leaking to the /bin/sh it spawns.

**Comment by memsharded** [comment]
Hi @matt-cross 

For 1.21.1 we had to do some changes in the CI for releasing the .deb. Actually there was an error with this that was recently fixed around the same time you have reported this issue: https://github.com/conan-io/conan/issues/6399, and the .deb has been updated too. It would be good if you could check that you used last installer file conan-ubuntu-64_1_21_1.deb

Please @czoido have a look when possible.

**Comment by czoido** [comment]
Hi @matt-cross,

I have not been able to reproduce this specific issue but is probably related to the generation of the binaries. The binaries in the deb package are generated with Pyinstaller that sets the `LD_LIBRARY_PATH` so all the bundled libraries can be found: https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#ld-library-path-libpath-considerations

- Could it be that you have a newer version of `libtinfo` installed in your system and that's why the warning is thrown?. 
- Could you check if this happens with the current deb package?

Thanks a lot.

**Comment by czoido** [comment]
@matt-cross, also, could you please test the deb package of the `1.21.0` version (https://github.com/conan-io/conan/releases/download/1.21.0/conan-ubuntu-64_1_21_0.deb) to check if the same warning is raised? 
Thanks a lot!

**Comment by matt-cross** [comment]
I found the issue with `conan-ubuntu-64_1_21_1.deb`:

```
mcross@mcross-desktop:~/tmp$ md5sum conan-ubuntu-64_1_21_1.deb 
6710db2225de10802a6d1d6c2f12e33d  conan-ubuntu-64_1_21_1.deb
```

I get the same warning with version `1.21.0` of the package:

```
mcross@mcross-desktop:~/tmp$ sudo dpkg -i conan-ubuntu-64_1_21_0.deb 
Selecting previously unselected package conan.
(Reading database ... 440822 files and directories currently installed.)
Preparing to unpack conan-ubuntu-64_1_21_0.deb ...
Unpacking conan (1.21.0) ...
Setting up conan (1.21.0) ...
mcross@mcross-desktop:~/tmp$ conan -v
/bin/sh: /opt/conan/libtinfo.so.5: no version information available (required by /bin/sh)
WARN: Migration: This conan installation doesn't have settings yet
WARN: Nothing to migrate here, settings will be generated automatically
Conan version 1.21.0
mcross@mcross-desktop:~/tmp$ md5sum conan-ubuntu-64_1_21_0.deb 
467b73af1bd3b5bb2de2b2ff1f4f4317  conan-ubuntu-64_1_21_0.deb
```

After some experimenting with a clean Ubuntu 16.04 docker container, I found a unique thing on my system that seems to be the cause.  My system has `/bin/sh` configured to point to `bash` and no the default shell `dash` as described near the bottom of this section of the Ubuntu wiki page: https://wiki.ubuntu.com/DashAsBinSh#My_production_system_has_broken_and_I_just_want_to_get_it_back_up.21

I can reproduce this with the following steps:

1. Start a clean Ubuntu 16.04 container with `docker run -it --rm ubuntu:16.04` (the rest of the commands are to be run inside that container)
2. Do `dpkg-reconfigure dash` and type `no` at the prompt - this switches `/bin/sh` to point to `bash`.
3. Run `apt-get update` and `apt-get install -y wget` to get the wget command into the container.
4. Run `wget https://github.com/conan-io/conan/releases/download/1.21.1/conan-ubuntu-64_1_21_1.deb` and then `dpkg -i conan-ubuntu-64_1_21_1.deb` to install the conan package.
5. Run `conan -v` to see the issue.

**Comment by czoido** [comment]
Hi @matt-cross,

Thanks for giving us the information to reproduce the issue.
Yes, It seems that `bash` is linking with `libtinfo.so.5` as conan binary is. 
Doing a `readelf -V /bin/bash` one can see that this binary requires a specific version of `libtinfo`:

`0x0030:   Name: NCURSES_TINFO_5.0.19991023  Flags: none  Version: 4`

The `libtinfo` bundled with Conan (that is the library that bash is taking because of the Pyinstaller change of the `LD_LIBRARY_PATH`) does not have that version defined so bash warns about of it.

This warning should not have any further implications if it is not already breaking anything. Although I would not recommend it, you could delete the `libtinfo` bundled with conan (in `/opt/conan/libtinfo.so.5`) to remove the warning. 

Anyway, we will give it a thought to see the ways we have to avoid further problems with this issue in the future. Thanks a lot!

**Comment by matt-cross** [comment]
So far it does not seem to be causing any other issues.

It seems to me that conan in general should not fork processes with `LD_LIBRARY_PATH` set pointing to `/opt/conan`, except I imagine it is complicated because if conan spawns another process that is part of the conan installation it may need that.

**Comment by memsharded** [comment]
LD_LIBRARY_PATH is automatically set up by pyinstaller, not Conan, which is the app used to create the self-bundled executable. It needs it to run the python interpreter bundled there. There is little we can do there... Of course this won't happen with the pip installed one.

**Comment by matt-cross** [comment]
I found this in the pyinstaller docs:  https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#ld-library-path-libpath-considerations

It's annoying that the pyinstaller framework does not handle this automatically.

**Comment by memsharded** [comment]
Yes, we have in conan a ``pyinstaller_bundle_env_cleaned()`` context that we apply for the ``self.run()`` command, and that we will also apply in SCM from next 1.22. But in this case we cannot do anything at all, because the issue appears just by invoking the bundled python interpreter by pyinstaller. 

We will consider also other possibilities of releasing a bundled Conan, but that will take a long time for sure.

The only thing that I could think right now is that you could create the pyinstaller executable in your platform, in that way, pyinstaller would do the right thing and package that tinfo library. If you are installing the .deb package in many machines or for many developers, it might be worth the effort.

**Comment by memsharded** [comment]
I have been reviewing this issue, and I think there is nothing we can do right now with the current context.

My recommendation would be to try some of the following:
- Use the ``pip install conan`` installation instead of the .deb one, based on pyinstaller.
- Workarounds at the system level with the libraries/shell
- Create your customized bundled Conan with the ``pyinstaller.py`` script that is in the root of the Conan repo, run in the system configured with the shell you plan to use, that should bundle the right libtinfo version.

Because trying to change the way the bundled Conan in .deb is created will produce the same error, but for users with the default shell, I think we cannot change it, so I guess this issue could be closed. Please @matt-cross let me know your thoughts.

**Comment by matt-cross** [comment]
I'm fine with closing this issue, as:

- It is specific to the bundled .deb package installer for conan
- It only affects some systems
- The effects (so far) seem to be simply a benign error message

We worked around it by repackaging the .deb bundle you released without the libtinfo library, and we use this repackaged bundle for our internal users.

**Comment by memsharded** [comment]
Great.

Thanks very much for all your feedback and collaboration. Cheers!
