### ISSUE TITLE
[question] Usage of Ninja + CL.exe with VS with CMake helper

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6447]
If I create a project:
```
$ conan new hello/0.1 -s
```
Then change 
```python
cmake = CMake(self, generator="Ninja")
```

And do 
```
$ conan create .
```
It fails, using my Gcc 4.9 compiler, even if my default settings are VS-15-Release-x64

I can workaround it, explicitly saying in the profile:
```
include(default)

[env]
CC=cl.exe
CXX=cl.exe
```

I am not sure if this is what we want, want to automate this?

**Comment by rasjani** [comment]
I've been talking and trying to debug this on and off for past month in slack, albeit, i dont use gcc, just msvc2017

Few observations from my futile attempts to find a proper fix:

When cmake is used with Ninja generator, in `_run()`,  `vcvars_dict()` is called which then proceeds to call `vcvars_command()` which tries to locate arch_build. 

This behaviour doesnt happen in with cmake if visual studio (default) is used as generator.

In my environment, i have fully loaded vcvars environment already so, trying to append or prepend vsvars is unnecessary but maybe some.

Before 1.24, when using Ninja as genrator for cmake, i was hit with #6674 - with 1.24 release and if i define arch_build in recipe settings: `conans.errors.ConanException: unsupported architecture x86_64`. And im not trying to cross compile so this seems a bit weird.

Now, at least for me, if i add fallback `or settings.get_safe("arch")` at the end of this line:

https://github.com/conan-io/conan/blob/develop/conans/client/tools/win.py#L365

I do get my ninja build working but im not sure if that causes issues elsewhere .. 

Worth mentioning is that our builds are fully driven by conan-package-tools but i can re-produce this with `conan build` too.


*EDIT* 

Additional information: The main issue for me was due to running Jenkins inside CYGWIN .. Host architecture detection in python relies to read the host architecture from environment variable: PROCESSOR_ARCHITECTURE which is automatically set on normal windows installation but cygwin removes this env.  CMake still works fine without this but using Ninja generator and build fails. Workaround was that we added correct PROCESSOR_ARCHITECTURE to slave environment configs in each slave in jenkins

**Comment by annulen** [comment]
>I can workaround it, explicitly saying in the profile:

Note that `CC=cl.exe CXX=cl.exe` workaround doesn't work properly when two versions of Visual Studio are installed - CMake will pick cl.exe according to its own search order, and `compiler.version` from profile is ignored.

**Comment by memsharded** [comment]
Related: there is an ongoing effort to modernize the integrations with the build systems, via toolchains. For this release the CMake+Ninja one is planned: https://github.com/conan-io/conan/issues/7814, at least at a very experimental level.

**Comment by annulen** [comment]
Sorry for the noise, `CC=cl CXX=cl` workaround seems to be enough in case of multiple VS installation, and problem was in my script which didnt't actually set variables.

Couldn't `CMake.configure()` be fixed to set CC and CXX variables, required for selected compiler?

**Comment by memsharded** [comment]
This was solved time ago with new integrations CMakeToolchain, etc, please upgrade and report in new tickets
