### ISSUE TITLE
[question] conan conandata.yml sources url not support file:// local or remote

### ISSUE THREAD

**Issue by leyewen** [conan-io/conan#6453]
I try to change `conandata.yml` sources download `url` to local file for testing, it seen to not working.
`tools.get(**self.conan_data["sources"][self.version])` shoud support `file:` mode to local or remote file.
eg:
linux: `file:/home/user/sources/conan.tar.gz`
windows: `file:C:\Users\Home\sources/conan.tar.gz`

tools download should be based on protocol:
`protocol://host:port/path?query#fragment`
protocol: `http:` `https:` `ftp:` `file:` `packagepath:`
if without protocol, default use local package path file .

**Comment by Minimonium** [comment]
The problem with that is that `conandata.yml` should be machine undependable. `conandata` is executed on _each_ build, not on export.
If a user installs your recipe and its `conandata` points somewhere locally - there is a huge chance that they wouldn't get the result they want.

**Comment by memsharded** [comment]
There are 2 different things here:

- conandata.yml is actually agnostic, it doesn't contain any logic regarding those sources, just a dict of values. conandata is written at ``export / create`` time, and loaded every time the ``conanfile.py`` is loaded.
- The ``conandata`` is used in the source() method if it is explicitly used in ``tools.get()`` or ``tools.download()`` or any other logic.
- The one not supporting the different protocols is ``tools.get()``. But this is totally unrelated to ``conandata.yml``. If you explicitly pass a ``ftp:`` url to ``tools.get()`` it will also fail.

So this is a feature request that ``tools.get()`` support different protocols. I guess this is doable, we already have a ``ftp_download`` helper, and the ``file:`` would be a copy. Probably deserves yet another level of access, and implement a ``tools.xxx_download()`` that can receive different protocols. Because ``tools.get()`` does other things like unzipping, etc, maybe not always desired.

**Comment by memsharded** [comment]
This feature makes sense, but it doesn't look like a high priority. If necessary, users can implement the logic in the ``source()`` method easily.

**Comment by derived-coder** [comment]
especially for testing, this feature is really appreciated. So I don't need to download a big source file from some server.

**Comment by kobi-ca** [comment]
hitting the exact same requirements trying to build gtest with local tarball :)

**Comment by memsharded** [comment]
> especially for testing, this feature is really appreciated. So I don't need to download a big source file from some server.

Regarding the download of big files from server, repeated times, now there is the file download cache, which can work across multiple Conan homes, and that will avoid downloading the same file multiple times from external servers: https://docs.conan.io/en/latest/configuration/download_cache.html

Not saying that this is a solution to the different protocols, but maybe it can alleviate some pain too.

**Comment by offa** [comment]
In the meantime there's a workaround using a minimal web server, eg. with python 3:

```sh
# run in the directory where the .tar.gz are

python -m http.server
```

##### conandata.yml

```yml
sources:
  "1.2.3":
    url: "http://localhost:8080/project-1.2.3-src.tar.gz"
    ...
```

**Comment by memsharded** [comment]
New ``from conan.tools.files import download/get`` support ``file:///``. Still not very recommended, instead the local flow would be recommended to avoid downloads while testing things, the ``file:///`` would be broken if the package is created with it and uploaded
