### ISSUE TITLE
[blocking bug] "Error 400 downloading" message while trying to *upload* to Artifactory

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#6454]
We are seeing in our Jenkins the error:

```
[Conan_pipeline] $ cmd.exe /C "conan upload pract/7.47.0.3110506605@PORT/stable#39384b0164d552e3ac2d04951388762d --all -r 5f5626fd-b9b4-43cb-a2af-8247374696cb --confirm --no-overwrite recipe && exit %%ERRORLEVEL%%"
Uploading to remote '5f5626fd-b9b4-43cb-a2af-8247374696cb':
Uploading pract/7.47.0.3110506605@PORT/stable to remote '5f5626fd-b9b4-43cb-a2af-8247374696cb'
Compressing recipe...
[==================================================]


ERROR: Error 400 downloading file https://artprod.dev.bloomberg.com/artifactory/api/conan/bb-conan-pract-stable/v2/conans/pract/7.47.0.3110506605/PORT/stable/revisions/39384b0164d552e3ac2d04951388762d/files/conanmanifest.txt. [Remote: 5f5626fd-b9b4-43cb-a2af-8247374696cb]
```

while trying to upload from Jenkins to a new Artifactory repo we have created.  We have previously been able to upload test packages to it:

![image](https://user-images.githubusercontent.com/2184330/73595118-017fbd80-4515-11ea-93eb-eca40bee812e.png)

### Environment Details (include every applicable attribute)
  * Windows Server 2012 R2
  * Conan version 1.20.4 

### Steps to reproduce (Include if Applicable)

Run Jenkins job and attempt to upload to Artifactory Version 6.12.1

**Comment by michaelmaguire** [comment]
Our Artifactory SRE has mentioned "Looks like an open issue with Jfrog" https://www.jfrog.com/jira/browse/RTFACT-20091 although I don't understand myself that connection.

**Comment by memsharded** [comment]
Hi @michaelmaguire 

It would be great to know a bit more of information, because not possible to reproduce the issue with the above:

- Can you deterministically reproduce the issue, creating a blank repository and uploading that same package from the server (without Jenkins)? Can you reproduce with any simple package (like one created with ``conan new mypkg/0.1 -s && conan create .``?
- Is it always the same package? Was the package created locally, or has it been downloaded from elsewhere?
- Can you obtain the traces from the server?
- Is that the full trace? I am a bit confused, I think we are not using ``[====....====]`` in that way, without text message anymore in our output in Conan 1.20

Please let us know, and we will try to help. Thanks!

**Comment by michaelmaguire** [comment]
It was a mistake on the repo name. We forgot to suffix -local for the Artifactory repo.

**Comment by memsharded** [comment]
Then it was indeed related to https://www.jfrog.com/jira/browse/RTFACT-20091, which says that a better error message would help to solve the issue. That JIRA ticket is still open, so hopefully it is improved.
