### ISSUE TITLE
[feature] Extend CONAN_DEFAULT_PROFILE_PATH  to support multiple profiles

### ISSUE THREAD

**Issue by thorntonryan** [conan-io/conan#6476]
### Request
Conan 1.12.0 extended a variety of conan commands to support multiple profiles #6430 , but `CONAN_DEFAULT_PROFILE_PATH` was not likewise extended.

Could `CONAN_DEFAULT_PROFILE_PATH` be extended to support  multiple profiles as well?

### Context
For example, we have variety of profiles configured to target different compilers:
* x86-windows-msvc141
* x86_64-windows-msvc141
* x86-windows-msvc142
* x86_64-windows-msvc142

I'd like to start taking Qt from a Conan package, but it comes with a large number of options that need to be configured (i.e. which Qt modules to optionally include and other settings).

This seems like a good fit for a shared qt profile:
```
[options]
# modules
qt:GUI=True
qt:qt3d=True
qt:qtactiveqt=True
qt:qtandroidextras=False
qt:qtcharts=True
...
```

To create a shared utility package with a dependency on Qt,  I could then do something like:
`conan create . MyQtLibrary@user/channel -pr x86-windows-msvc141 -pr qt`

Likewise, in a consuming application, I'd need to specify the same options to pick up the matching Qt package:
`conan install C:\projects\MyApp\conanfile.py -pr x86-windows-msvc141 -pr qt`

Inside MyApp's CMakeLists.txt, I could also pass in multiple profiles:

```
find_package(cmake-conan REQUIRED)
conan_cmake_run(CONANFILE conanfile.py
	PROFILE x86-windows-msvc141 qt
)
```

However, more often than not, we'll avoid hardcoding a profile in the call to `conan_cmake_run` and instead rely on `CONAN_DEFAULT_PROFILE_PATH=x86-windows-msvc141` to pick the right profile whenever CMake triggers a conan run.

 _FWIW, I don't want to hardcode what compiler profile I'm using (i.e.  x86-windows-msvc141 / VS2017) in my CMakeLists.txt so that way when I upgrade compilers (i.e.  x86-windows-msvc142 / VS2019) I can check out the source and go w/out making modifications. `CONAN_DEFAULT_PROFILE_PATH` somewhat alleviates this._

But `CONAN_DEFAULT_PROFILE_PATH` doesn't support multiple profiles...so I can't yet take this same approach.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, this feature makes sense. I tried to do a quick implementation, but not as direct as it seems: How several profiles are defined? A ";" separated list in Windows and ":" separated list in Linux? It is important to remember that ":" is a thing in Windows paths, and the profiles can be absolute paths.

But then the configuration is not portable among systems, and cannot be used in ``conan config install``?

Also, I would recommend stop using env-vars like CONAN_DEFAULT_PROFILE_PATH for Conan client configuration, and start using *conan.conf* configuration (like ``[general] default_profile``). It is very likely that env-vars will be deprecated in Conan 2.0.

**Comment by puetzk** [comment]
> A ";" separated list in Windows and ":" separated list in Linux? 

That's what I suggested this to Ryan when we were discussing this, and because it has lots of other precedent in conan.

> stop using env-vars [...] and start using conan.conf configuration (like [general] default_profile). 

But that's not really even a similar functionality... That's one per-machine default setting, not the ability have conan contextually know to do from context when called from an IDE (e.g. I originally requested `CONAN_DEFAULT_PROFILE_PATH` so there would be a way to connect conan to Qt creator's kit definitions, for the call to `conan install` done by conan-io/cmake-conan). It would be fine if you'd rather see things like cmake-conan do the environment-awareness of passing `--profile $ENV{CONAN_DEFAULT_PROFILE_PATH}`, that would work fine, but losing any ability to connect an IDE's cofiguration selector to a conan profile would really suck.  But there's a lot about the build_requires and settings for a cross-compiler kit that cmake-conan's `PROFILE_AUTO` has no realistic chance of probing.

My conan.conf default_profile is, very deliberately, just setting nearly everything to None (including the things that can't actually be None), so that it stands no chance actually working, ensuring that I've actually made a choice (either explicitly or at least inheriting from a GUI choice).

**Comment by memsharded** [comment]
Hi @puetzk 

I am not sure if I understood. Why would you lose the ability to connect an IDE to a conan profile? Nothing changes, in the same way you set the conan.conf ``general.default_profile=None``, you could set it to the profile you want, instead of defining it in a env-var. Plus defining it that way has the advantage that it will automatically configure it when you do a ``conan config install`` to install your profiles. And that works in every context: you are in the IDE, it works, you jump to a new terminal, it keeps working exactly the same.

I also fail to see how this would be connected to the ``conan.cmake`` functionality.

**Comment by thorntonryan** [comment]
> I am not sure if I understood. Why would you lose the ability to connect an IDE to a conan profile?

Maybe I can help elaborate some.

It's not uncommon for our IDE (e.g. Qt Creator) to be configured with multiple kits per target profile. For example, we have a profile and kit targeting the following:
* linux-bionic
* linux-embedded

Both Kits / profiles are used to compile the same source on the same build environment (e.g. bionic) but one is used to target the host (e.g. bionic) and the other to cross compile to our embedded environment. 

Each kit targets a different profile by setting a different value for `CONAN_DEFAULT_PROFILE_PATH`.

Since we target two (or more) different environments, with vastly different profiles, setting one system wide profile via `general.default_profile=None` isn't as appealing. You'd have to change this system wide setting each time you changed kits in your IDE.

The same could also be said between different versions of the compiler:
* x86-windows-msvc141
* x86-windows-msvc142
* x86-windows-msvc-preview

Depending on the project, we might have multiple kits configured, each with its own profile, depending on which environments are supported and/or under evaluation.

Relying on the system wide `general.default_profile` doesn't really help if you need to change the profile depending on what kit you're using. I'd view it as a loss of functionality.

> I also fail to see how this would be connected to the conan.cmake functionality.

I think he's saying that if you remove `CONAN_DEFAULT_PROFILE_PATH` from Conan 2.0. You could recover the same functionality by moving it to the `conan_cmake_run` helper from [cmake-conan](https://github.com/conan-io/cmake-conan).  `conan_cmake_run` could look for the same environment variable and explicitly pass it on the command line via `--profile` when calling into Conan.

**Comment by memsharded** [comment]
Closing this ticket as outdated:
- Conan 2.0 still got single-profile CONAN_DEFAULT_PROFILE env-var
- ``cmake-conan`` is a totally new integration, it accepts multiple profiles as argument as CMake-variable. Not sure if it helps, but if not it would be good to open a new ticket for an updated report. Thanks!
