### ISSUE TITLE
Better reporting when using the download cache

### ISSUE THREAD

**Issue by tru** [conan-io/conan#6481]
I am playing around with the new download cache and it seems to speed things up for sure. But it would be nice to have a way to see when a cached item is used - this is what conan outputs when the cache is used:

```
boost/1.69.0-25@plex/stable:a5e54483fc43f9598a9c980988856af5a25816df - Download
```

Which is not 100% true anymore. It should indicate that this will be fetched from the download cache.

If nothing else this following line should be changed when the cache is used:

```
boost/1.69.0-25@plex/stable: Retrieving package a5e54483fc43f9598a9c980988856af5a25816df from remote 'experimental'
Decompressing conan_package.tgz completed [0.00k]
boost/1.69.0-25@plex/stable: Package installed a5e54483fc43f9598a9c980988856af5a25816df
boost/1.69.0-25@plex/stable: Downloaded package revision 0
```

This simple change will make it easier to know when the download cache was used or not.

**Comment by jgsogo** [comment]
I agree that we should write a message about the actual operation: download vs copy-from-the-download-cache, that trace can be interesting, but I'm not sure if I'd change any of those messages:
 * The keyword `Download` has a meaning: the package is not in the cache and it will be retrieved from somewhere else. Changing the keyword when the optimization is enabled can be confusing (maybe `Donwload` is not the best keyword, but it should be a suggestion for Conan 2.0).
 * About the second message, I'd add a trace saying that the package is copied instead of downloaded, 
    + the _"from remote 'experimental'"_ still makes sense because the key in the download-cache contains the URL of the remote, so the optimization won't work if you are downloading the same file from a different remotes.
    + _"Decompressing conan_package.tgz completed [0.00k]"_ is about decompressing, this operation is needed with the download-cache too.

    ... but between these messages, we should say that the download-cache is activated and the file is retrieved from it (it should be a message substituting the progress bars).

**Comment by memsharded** [comment]
Yes, the 

```
boost/1.69.0-25@plex/stable:a5e54483fc43f9598a9c980988856af5a25816df - Download
```
should remain. This is still a download. Very fast one, because you have a local copy, but still considered conceptually a download of that package that was not previously in the package cache.

I agree that after that, we can add a message that would replace the transfer one, saying it was copied from the download cache instead of actually transferred from a remote.

**Comment by tru** [comment]
I am currently testing this on our CI and I don't see any real speed up compared to before - which is a bit surprising to me - but it's hard to know if it's actually using the cache or if our previous install was just super quick so the caching of download didn't really help.

I am fine with a new message as long as it's clear what's happening and if we are getting cache misses or not.

the output seems much harder to read when it's running piped to a file (like in jenkins) because it's missing some lines - is this intentional?

**Comment by jgsogo** [comment]
> I am currently testing this on our CI and I don't see any real speed up compared to before - which is a bit surprising to me - but it's hard to know if it's actually using the cache or if our previous install was just super quick so the caching of download didn't really help.

You should notice the speed up if you are downloading big files and your connection is not very good, otherwise you are substituting a download by a copy and you are still uncompressing the files... this is not a silver bullet, but it can help with some scenarios, and it is safe to share the same download-cache for different CI jobs (parallelization is arriving at Conan, one step at a time)



> the output seems much harder to read when it's running piped to a file (like in Jenkins) because it's missing some lines - is this intentional?

Conan detects if the output is going to a terminal or not, at some points we check for `is_terminal` in the source code and avoid some outputs (like progress bars), nevertheless the information in the logfile should be enough. Do you miss any important bit?

**Comment by memsharded** [comment]
> I am currently testing this on our CI and I don't see any real speed up compared to before - which is a bit surprising to me - but it's hard to know if it's actually using the cache or if our previous install was just super quick so the caching of download didn't really help.

I have measured reduced times for some ``conan install`` going down 35%. Indeed the bottleneck here might become the unzipping of .tgz, which is still done sequentially. If unzipping takes most of the time, then the speedup might be not great. Please keep reporting your findings @tru

**Comment by tru** [comment]
I want to add some trace debugging that shows how long times the different parts of an install takes. Any ideas where to add this?

**Comment by memsharded** [comment]
Closing this as inactive.
Also 2.0 has changed the whole output, with real log-levels, it should be easier now to add debug traces for timing if desired, plus the codebase is also clearer. Thanks!
