### ISSUE TITLE
[feature] 'conan config get' should return the default value even if it is not initialized

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6537]
On a fresh new Conan client:

```bash
⇒  conan config get general.revisions_enabled
ERROR: 'revisions_enabled' doesn't exist in [general]
```

It is true that the value is not written in the `conan.conf` yet, but for these built-in values Conan could return the default one **as it is doing when using `ConanClientConfigParser.revisions_enabled` property** in the sources.

This is important because the default value might change in Conan v2, if it is not defined (not written in `conan.conf`) different Conan versions should return a different value.

So, alternatives:
 * Return the default value even if it is not written in `conan.conf` (breaking?)
 * Keep this behavior, but write it down always in the initial `conan.conf` file

---

More like this:
`conan config get general.scm_to_conandata`
`conan config get general.default_python_requires_id_mode`
`...`

**Comment by memsharded** [comment]
I agree that ``conan config`` should act over the config itself, default or not, not the bare "file" parser. If the config is configuring a default ``revisions_enabled=False`` that is probably what the command ``conan config get`` should return instead of failing.

Probably not breaking, as it was raising an error, and writing an initial conan.conf value will not be possible in all cases, specially for Conan client updates, etc.

As this doesn't seem critical, I'd vote to implement this already in Conan 2.0

**Comment by memsharded** [comment]
``conan config get`` has been dropped in 2.0.
Reading the ``global.conf`` or the profiles is the way to go.
