### ISSUE TITLE
[feature] Channel length limit increase

### ISSUE THREAD

**Issue by radonish** [conan-io/conan#6552]
My group is using the git branch for the channel component of the package reference; we've run into the channel length limitation:

`ERROR: Value provided for channel, 'XXX' (type str), is too long. Valid names must contain at most 51 characters.`

It would be helpful to have more characters to work with for the channel.

Thanks!

**Comment by memsharded** [comment]
You mean, not the git commit, but the branch name, which happens to be too long?

We have considered to raise this in the past, but we don't fully control the implications that could have on the different servers, because the name-version-user-channel might be indexed in databases, or might assume length limits for performance. Another reason Conan limits the length of those fields is because they are mapped to filesystem paths. Even with the tricks of ``short_paths`` if these fields are too long, the cache will simply not work in Windows. 

So in the best case, it would take some time until this can be investigated, I'll put this to look in Conan 2.0, meanwhile, please keep your branch names shorter

**Comment by radonish** [comment]
Yes, I was referring to the actual branch name; we've had to use it for now as the channel in order to select the right "version" of a package.

Thanks for the feedback!

**Comment by memsharded** [comment]
Conan 2.0 makes the total length of the reference <200 chars, so channels might be longer.

Note, however, that using channels for something that changes is strongly discouraged. Most likely channels should only be None (not mandatory anymore), or "stable" and "testing", just to make sure that experiments with packages don't get into production. But ``conan copy`` has been dropped, and it is not recommended to do overrides over channels only, the default package_id will also change with this happens.

For running "stages" or "promotions" the recommended way is to use multiple server repositories, and do copies from one repo to another.
