### ISSUE TITLE
[feature] Make config set fail if variable not correct or misspelled

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6572]
```
$ conan config set general.revisions_enabled_typo=1
```

doesn't error, doesn't warn. Keeps going without effect.

**Comment by jgsogo** [comment]
...but it adds the variable to the file `conan.conf`.

I'm just writing here some thoughts I had about the future of the `config` object (and the persistence layer in the `conan.conf` file):
 * Build helpers, generators, or some tools might require the `config` object (now they are using lots of environment variables), if we pass the `config` object to these type of elements we will pass it to custom ones written by the user... and these ones will want to use configuration stored (shared and versioned) in a `conan.conf` file instead of environment variables.
 * Hooks, now they use lots of environment variables to opt-in/out some behaviors, probably we should adopt the same strategy and pass the `config` object to them so they can read their configuration for this file.

I mean, we cannot have an inventory of all the fields valid in `conan.conf`, I like the idea, but probably this can be done only for some sections... or maybe the Conan configuration should be grouped together in one single section.

🤔

**Comment by memsharded** [comment]
> I mean, we cannot have an inventory of all the fields valid in conan.conf, I like the idea, but probably this can be done only for some sections... or maybe the Conan configuration should be grouped together in one single section.

Ok, yes, this is definitely a valid use case, if we want to go that way for configuration. But as you pointed, definitely might be worth a ``[user]`` section or something, and have the other sections to be a bit more robust if possible against user errors. To be discussed when we think about the config.

**Comment by memsharded** [comment]
``conan config set`` has been completely dropped.
New ``conf`` system will raise errors if confs do not exist.
