### ISSUE TITLE
[scm] Do not copy ignored files to the cache (SCM optimization)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6617]
The SCM optimization that copies files from the user folder to the cache should take into account the ignored files/folders in the `.gitignore` (or SVN equivalent) and do not copy those files to the `scm_sources_folder`.

This applies also to SVN.

---

Taken from https://github.com/conan-io/conan/issues/6605#issuecomment-593837409

**Comment by aleksa2808** [comment]
Not doing this, including not ignoring empty folders like git does implicitly, can lead to a package being built fine locally with `conan create`, but failing to build from source after.

I encountered this exact issue today where an empty directory was for some reason needed for a certain test (built and ran as part of the build step). I had this empty directory locally in my project folder, but git and subsequently Conan of course looked at the project directory as clean. However, Conan copied over the empty directory to the source and built the package successfully. If I then tried to build the package from source again, this time the actual repo would be cloned and it wouldn't contain the empty folder in question and the test depending on it would fail. This is troublesome since to the package creator everything seems fine, but in reality the package is broken.

**Comment by n00b42** [comment]
A usecase: CI pipeline clones project. To not pollute the build server we set CONAN_HOME to the project folder and add ".conan/**" to .gitignore
However, currently, all contents of .conan are copied, resulting in an ever growing .conan folder (copies itself in itself)

**Comment by memsharded** [comment]
``scm`` feature deprecated in 1.X, removed in 2.0, closing this as outdated.
