### ISSUE TITLE
[feature] allow multiple scm attributes and attempt with each

### ISSUE THREAD

**Issue by peter-moran** [conan-io/conan#6619]
I really like the [scm attribute](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#scm) feature, however I have a project where the source code can be found in different git remotes depending on your permissions.

It would be awesome if the scm attribute could instead be a list, each providing the type, subfolder, url, revision etc. Then each could be attempted in order until one works.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @peter-moran 

The https://github.com/conan-io/conan/issues/6349 issue suggest using just a list of URLs, to be able to fallback (mirrors, network issues), but that doesn't consider different types, subfolders, etc, just a different URL, and it is for download, not for SCM.

I think that your use case might be a bit of a particular case. Another user could say that a list of SCM is what they want to retrieve sources from more than 1 origin, as their package needs sources from 2 different repos to build. Which is a valid use case too, from my knowledge, even more common than the one you expose. 

Even if we went for the "fallback" or "try until the first one works", I am concerned about the complexities this will bring:
- What happens to the ``auto`` SCM behavior? I guess it should be disabled, and an error should be raised.
- Maintaining versions over time of this recipe seems a bit error prone, as it needs to update all revisions/commits of all sources correctly at once, and typically most origins are really not tested, because CI will only build 1 origin, maybe the others can be broken because of a typo or whatever.

We also have the following logic:
```python
def get_scm_data(conanfile):
    data = getattr(conanfile, "scm", None)
    if data is not None and isinstance(data, dict):
        return SCMData(conanfile)
    else:
        return None
```
This is because when we introduced the ``scm`` there were users already using ``scm`` attribute for other purposes, and we didn't want to break (we hadn't documented the attributes rules for recipes yet). We minimized the conflict surface processing those that are dicts. If we start processing lists, we could be breaking users recipes.

For these reasons, I think it is difficult that we could provide this functionality with minimal guarantees. I would suggest exploring these options:

- Implement the logic yourself, it shouldn't be too long:

```python
class Pkg(ConanFile):
     _mygit = [{"url": "git@github.com", "tag": "1.2.3"}, {"url": "https://bitbucket....", ...}]

     def source(self):
           for g in self._mygit:
                git = tools.Git(verify_ssl=g["verify_ssl"], ...)
                try:
                    git.clone(url=g["url"], ...)
                    git.checkout(g["tag"])
                    break
                except:
                    pass
```

- Actually, I think that the if the sources could be unified in origin, that would be good. If I was in that situation, for every new version of the package I would create a tarball from one of the repos and put it in a generic Artifactory repo or something. But having a central source of truth for the sources of a package would probably remove some headaches.

**Comment by peter-moran** [comment]
Thanks for the detailed response. I totally understand this is a rare use case and because of that, plus the complexity that I did not realize, this may not work.

In my exact use case  I only need to provide alternate URLs. The example you provided, where we loop through a list of git repos and try `git.clone` on each is basically what I implemented as a stop-gap. It works very well, but the one disadvantage compared to the `scm` attribute is that it handles selecting the revision automatically, which I've found prevents people from accidentally packaging an outdated revision by accident.

In the end I've decided to use `exports_sources` which seems less error prone and removes any issues with handling multiple git repos.

---

If we were to allow multiple SCM, this is what I would suggest based on your questions:

> What happens to the auto SCM behavior? I guess it should be disabled, and an error should be raised

SCM `auto` should still work, as is. For example, the below would cause Conan to automatically fill in url and revision based on the current working copy for our first choice, and then the second choice would use a hard-coded url but with the same auto-detected revision.
```
     scm = [{
        "type": "git",
        "url": "auto",
        "revision": "auto"
     },{
        "type": "git",
        "url": "https://my/mirror.git",
        "revision": "auto"
     }]
```

> Maintaining versions over time of this recipe seems a bit error prone, as it needs to update all revisions/commits of all sources correctly at once, and typically most origins are really not tested, because CI will only build 1 origin, maybe the others can be broken because of a typo or whatever.

This is a really good point. In my situation I have to make sure all remotes stay in sync anyway (eg our on-site copy and off-site copy), but being able to force the alternatives for testing purposes is something that would be needed.

---

Ultimately I would be fine with closing this ticket and suggesting future viewers to either
1. Fix whatever problem is requiring you to use multiple git remotes
2. Use `export_sources` to remove git entirely
3. Write your own `source()` function which loops through git options and tries them one at a time.

**Comment by memsharded** [comment]
Thanks @peter-moran for your elaborated response and all the feedback. It might be useful to other users.

Agree, let's close this at the moment, if there is some extended feedback or support from the community, we can reconsider again later. Thanks!
