### ISSUE TITLE
[bug] Options passed by profile file ignored in conanfile.py's requirements(self) method

### ISSUE THREAD

**Issue by jegabe** [conan-io/conan#6644]
When a conan profile contains some user defined options, like for example:

file myProfile.profile:

[options]
myOptions=myValue

then, the options can be used from conanfile.py files when building with that profile.
However, when using the options inside of the requirements(self) method, getting the options will only work when using "conan install" for the conanfile.py. Wen using "conan create" or when the conan package is built as transitive dependency, the options aren't available in the requirements(self) method: The default value is used instead.

How to reproduce:
- Create a profile file with an [options] setting as shown above
- Create a conanfile.py file that queries the option in the requirements(self) method and print it out
- Call "conan create" on that conan file

Sample conanfile.py:

from conans import ConanFile

class MyConanFile(ConanFile):
    name = "someName"
    version = "0.1.0"
    license = ""
    url = ""
    description = ""
    no_copy_source = True
    options         = { "myOptions": "ANY" }
    default_options = { "myOptions": ""    }

    
    def requirements(self):
        my_options = str(self.options.myOptions)
        print("my_options=" + my_options) # Prints the passed options for "conan install", but an empty string for "conan create"

**Comment by jegabe** [comment]
Affected version: 1.22.3

**Comment by memsharded** [comment]
Hi @jegabe 

I think this could be due to a small inconsistency of how options are applied. Who is the consumer of the dependency graph. When doing ``conan create``, specially if you have a ``test_package/conanfile.py``, that test_package conanfile will become the "consumer" and non-scoped options will apply to it. This is something that we want to change, but at the moment it is not possible because it would be breaking for many users.

It is recommended to always scope options with the package they apply to. In this case try:

```
[options]
myPkgName:myOptions=myValue
```
That should make the ``conan create`` to assign the value. Please try and let me know if it works. Thanks!

**Comment by jegabe** [comment]
Hi @memsharded, I'll try this out and report it whether it worked. It was unscoped intentionally because I tried that as key for a package name that's applied globally, as described in #6646. When that's generally not a good think to do, that's fine for me. It was a workaround anyways for #6646.

**Comment by memsharded** [comment]
If applied to all packages, I would recommend:

```
[options]
*:myOptions=myValue
```
Unscoped options only apply to one conanfile, the "consumer" one in that command, while the above applies to all.

**Comment by jegabe** [comment]
That's interesting. Didn't know that syntax. I'll try it out.

**Comment by jegabe** [comment]
@memsharded: The "*:" variant seems to work. I'll close that issue.

**Comment by memsharded** [comment]
Cool! Thanks for following up!
