### ISSUE TITLE
[CONAN_V2_MODE] Another iteration

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6664]
This issue is to add all those things that should be activated with `CONAN_V2_MODE`, we need to keep shaping the future and stabilizing the present (post below and I'll add them to the list).

- [ ] Default behavior: https://github.com/conan-io/conan/pull/6451
- [ ] Until further evidence, probably this mode should be avoided: https://github.com/conan-io/conan/pull/6457
- [ ] Organize `meson` related functions https://github.com/conan-io/conan/pull/6574, Meson is not stable, do we want to take care of old versions that doesn't support `meson build`?
- [ ] Do not add the environment of the requirements to the `config...` and `requirements` calls (the graph is not built yet, so it is imposible to propagate the environment)
- [ ] Remove non stable cppstd flags (ABI is not stable) ([+info](https://github.com/conan-io/conan/issues/6664#issuecomment-650987879))

Not all these things have to be implemented for the next version, we are not even agree on all of them, but we need to keep track of these issues.

**Comment by czoido** [comment]
I don't know if we could think about changing the default mode for `CONAN_SYSREQUIRES_MODE` in Conan v2. 
I know we have lots of things to think about and the current way of handling system requirements completely changes for v2, but just to take into account I think that I would prefer to have a `CONAN_SYSREQUIRES_MODE` defaulted to `verify`, so that Conan will tell you which system requirements you need and how to install them. You'll always have the possibility to use `enabled` mode for example in the CI docker images if they have not the system requirements already installed. At least that way the user can choose and we could install system requirements in c3i docker images setting that variable to `enabled`.

**Comment by jgsogo** [comment]
Change default `filter_empty` (desired behavior: it shouldn't remove non-existing folders)

**Comment by jgsogo** [comment]
The options values should not be defined in the ``requirements()`` or ``build_requirements()`` methods. Have you tried setting the value in the ``configure()`` method instead?

_Originally posted by @memsharded in https://github.com/conan-io/conan/issues/6759#issuecomment-606019998_

**Comment by memsharded** [comment]
For next iteration of this feature I would like to have an opt-in Conan 2.0 command line:

- Use a new env-var to switch to the new CLI 2.0
- Use good package naming and put everything there: ``import ui.cli`` (just an idea)
- It can be just the scaffolding, and contain just 1 method (the search recipes one), that still does nothing.
- I am ok to explore if there could be simplifications to the command line arg parsing, the interactive help.

**Comment by TheQwertiest** [comment]
> Organize meson related functions #6574

It should be noted that a generic build-system-agnostic `meson compile` command was added in the latest `meson`. It's not yet on par with current `build` command though (e.g. it's currently impossible to specify target), since current `build` invokes `ninja` directly, while `meson compile` has to wrap around all build-systems.

**Comment by jgsogo** [comment]
`CONAN_V2_MODE` should remove non-stable cppstd flags... or it should add a non-stable flag to them. Using non-stable cppstd can lead to linking errors due to ABI incompatibilities.

Probably we can raise in the first iteration (cppstd not supported, it is the safest behavior), but users should be able to opt-out this exception and use at their own risk.

Question is, how to encode _non-stable_ flag in the settings?

**Comment by memsharded** [comment]
CONAN_V2_MODE no longer relevant.
