### ISSUE TITLE
[feature] conan search to return err code if it does not find packages.

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6704]
Currently conan search happily returns error code == 0 when it doesnt find any packages.

```
$ conan search abc
There are no packages matching the 'abc' pattern
$ echo $?
0
```

However conan upload returns error code when it doesnt find any packages:
```
$ conan upload abc
ERROR: No packages found matching pattern 'abc'
$ echo $?
1
```

Looks like an inconsitency, and because conan search is always happy to return '0' I am forced to do a string match on its result

```
if [[ $(conan search abc) =~ "There are no packages" ]]; then
...
fi
```
I didnt check how other package managers behave. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
The current behavior is consistent.
That the local cache or a remote doesn't have any package that matches a pattern, it is not an error. An error would be a network failure, or some configuration broken, or a corrupted package.

When you introduce ``conan search <pattern>`` it can return nothing found, but not an error.
If you introduce ``conan search <reference>`` :

```bash
conan search pkg/0.2@nothing/exist
ERROR: Recipe not found: 'pkg/0.2@nothing/exist'
```
That is indeed an error. You are searching the binaries of a package, because you introduced a a full reference, the exact coordinates of something, not a pattern.

The UI for the upload with a pattern is different. That command wants to upload something. Not uploading anything and not erroring, because there was a typo in the pattern is bad UX. It is about the semantics, a "conan search" might not found anything, but that is not an error, this is in the self definition of "search". While if you do a "conan upload", it is expected that something is uploaded, and otherwise an error.

**Comment by jgsogo** [comment]
I agree with @memsharded that a _search_ finding nothing couldn't be a failure. The command works as expected. Nevertheless this is valuable UX feedback for @czoido , who is thinking about a new CLI, all these comments are valuable.

**Comment by fulara** [comment]
thanks, 
This made me realise that adding '@' makes a difference here. closing.

**Comment by memsharded** [comment]
Adding the @ to force conversion of a pattern => package reference, will change in the new command line, to avoid ambiguities and avoid these issues.
