### ISSUE TITLE
[python-requires] allow loading of python_requires inside `def requirements()`

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6707]
Currently it seems that `python_requires` can be only loaded from an inside attribute.

I would like it to follow convention established by `requires` and others and to be able to load it from within for example `def requires():` or `def python_requirements()`

I need some condition code that would decide which version of `python_requirements` to load.
And I can not do this from within attribute.

It would be nice if python_requires behaved in more obvious ways than it does right now, it has its own unique behaviors that differ from `requires`.

I've checked now and it does not seem to work:
```
ERROR: something/3.1@test/test: Error in requirements() method, line 29
	self.python_requires["my-package"].module.requirements(self)
	AttributeError: 'SomethingConan' object has no attribute 'python_requires'
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Introducing conditionals to depend on different versions of python_requires seems to me like a risky thing, and more difficult to maintain, I would probably advise against it, even if it was possible (it is impossible to implement this).

The main problem with this is that many people want the python requires in order to extend from some class that is there. Including the ``requirements()`` and ``build_requirements()`` methods that are in the base class. 

So python_requires is the very first thing that is processed when the module of the conanfile.py is parsed, way before the object is created and ``self.requirements()`` and ``self.build_requirements()`` are called. Even before the ``settings`` and ``options`` values are assigned.

Yes, this is very different than other requirements, but because this is what users have requested. We tried hard to avoid the "inheritance from python_requires" use case, but the demand was too strong.

Given that existing constraint, this would be an impossible to solve chicken & egg problem.

**Comment by fulara** [comment]
Is there any way to load any code into recipe with different way than `python_requires`? 
It seems that legacy syntax of `python_requires` has achieved that. I am now considering using that legacy syntax, to actually extract a version of new `python_requires` that we want to want to use.
I need to process some code before my ConanFile is even processed.

> Introducing conditionals to depend on different versions of python_requires seems to me like a risky thing, and more difficult to maintain. 

Long story short we have a version.lst file that contains the version we want to load, we are not using conan wildcards nor lockfiles,

**Comment by memsharded** [comment]
> It seems that legacy syntax of python_requires has achieved that. I am now considering using that legacy syntax, to actually extract a version of new python_requires that we want to want to use.

They behave the same. They are resolved and fetched way before the recipe ``requirements()`` or ``build_requirements()`` are evaluated. So you won't be able to use any conditional based on recipe logic.



> Long story short we have a version.lst file that contains the version we want to load, we are not using conan wildcards nor lockfiles,

Maybe you can still use that:
- Load version.lst at file global scope
- Replace version in ``python_requires = "mydep/%s@user/channel" % version``

In any case you might also want to start having a look at lockfiles and consider using them.

**Comment by fulara** [comment]
> They behave the same. They are resolved and fetched way before the recipe requirements()
Well there was this functionality:
```
from conans import ConanFile, CMake, tools, python_requires

base_version = 'legacy-python-requires/0.1.4'
base = python_requires(base_version)
Conanfile ...
```
So it seemes as it was loaded before conanfile, any utilities function could be invoked before processing of Conanfile.

> Load version.lst at file global scope

Yep, this is what I would like the 'python_requires' code to produce us.

Yea, we have lockfiles on our radar, but we are only integrating conan apps into existing system, so we had to follow existing system, and only after we have proved that conan works we could start different aproach.


Thanks for your prompt responses, sorry to take so much of your time.

**Comment by memsharded** [comment]
> So it seemes as it was loaded before conanfile, any utilities function could be invoked before processing of Conanfile.

Yes, the old python_requires loads at module parsing time, while the new python_requires load just after module parsing time. I meant that in both cases, they are resolved and loaded way before ``requirements()`` or ``build_requirements()`` are called. Any logic that runs at the module scope could in theory be applied to both cases, but it will not be possible to use any ``settings``, ``options`` or any other recipe method.

> Thanks for your prompt responses, sorry to take so much of your time.

No apologies! Always glad to help, we really love to help, learn about use cases and try to implement solutions that are useful for as many users as possible. The only issue is that time is very limited and we cannot do everything we would like. Thanks to you for all your feedback and support!

**Comment by fulara** [comment]
After this conversation I see I am left with these choices really:
1) Just take that code duplication I wanted to avoid, and in every conanfile I would duplicate the code to load that one line from version.lst and use that to load the true python_requires. 
2) Use old_python_requires for this, well this really is not that much better than the 1) solution probably would be 1-3 lines shorter. 
3) Just hardcode the version of that package. Currently its [~1] probably because I am lazy.

Let me tell elaborate a bit on the story here, actually my colleague was planning to go on conandays and he would describe our story there - but unfortunatelly it does not seem like it will happen anytime soon.

Our current (pre-conan, conan is just in POC stages atm here ) deploy & package management system, allows full & very fine control of a dependencies, there is a total detachment from build & runtime version, we are basically telling upon app start which libraries to load. I dont want to talk about risk of that aproach, I dont like it - but it is what it is.
Thats the version.lst file - it contains lines that tell the app-runner which LD_LIBRARY_PATHs to load.
so for example:
``` # version lst contents:
zlib 1.2.8
internal 1.0.0
```
So before start of application the loader parses this file and  initializes app with dependencies. 
What we have done as a POC in conan, is that we have made it so that our `requirements` is also build based on this file.  this looks something like this:
```
Foo(Conanfile):
   # we dont use requires at all for our recipes that use this mechanism.
   our_requires = "zlib/1.2.0", "internal/1.0.0
   python_requires = "our-requires/[~1]"
   ...
   # def requirements(self):
   # here we parse the version.lst file and  match it against our_requires. 
   # if entry has been found we do something like: self.requires("zlib/" + version_from_lst)
   # def package_id(self):
   # here we use our-requires to define versioning_schema of every dependency based on a config   
   # baked into it - usually our internal packages are semver_mode but third party and some of ours  
   # are full_package_mode
```
Ignoring cons of the aproach, this looks decent.  
We have a direct control over the dependencies - Something that from my understanding we wont be able to achieve with lockfiles ever,  We can basically tell the system, now run app with that version of library. I would like to leave the question whether thats a good idea aside, its just something thats being done. 

So really my question here is about putting that `our-requires` version into version.lst. 
There is still ongoing question why are we even using [~1] without lockfiles - to be honest I cant think of a good reason why at the moment, it has stabilized now, so maybe just switching to a concrete version would be fine.


Thanks for your input - I'll close this one.

**Comment by memsharded** [comment]
> We have a direct control over the dependencies - Something that from my understanding we wont be able to achieve with lockfiles ever, 

yes, you are right, lockfiles are for immutability, capturing a dependency graph state, to be able to reproduce later, but not for definition. Definition of dependencies, versions, etc. are indeed done in the conanfiles.

I don't see a big stopper to not use an external file to define exact versions of the dependencies.
You might want to consider the ``conan_data.yml`` (https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html) as a place to define information for conanfiles. It has a couple of advantages: It is automatically exported with the conanfile, and it is automatically loaded into the ``conan_data`` attribute, that you can use in recipes. Still not possible to be used for ``python_requires`` because those are still evaluated even before loading ``conan_data``, but maybe for the other use cases it might help. Hardcoding the ``python_requires`` might be the most effective solution.

Thanks for the explanation of the use case!
