### ISSUE TITLE
[question] Select OpenSSL version

### ISSUE THREAD

**Issue by thegwydd** [conan-io/conan#6708]
Hi all, 

I' have same software that runs on several linux IoT platforms and I'm using OpenSSL to communicate over network.
As in examples I always used openssl requirement in conanfile.txt/py and all works except few things I don't like.

Apart that several software components that use openssl may have multiple static openssl (potentially of different versions) copies around increasing needed space for my software, the majoir issue is that on several of our devices we have secure element chips and the openssl that comes with the platform has beed customized/configured to use the secure element.

Our software do not care about platform it wants just to use openssl. Possibly the platform one but, if not present, the one from conan package.

This scenario may be extended to all platform libraries. 
Thinking that 99% of cases on linux platforms you're granted to have an openssl instance, telling conan to compile and link to a static version of openssl sounds like telling to compile and link to a specific libc version.

How would you manage such scenario?

**Comment by KerstinKeller** [comment]
Hi @thegwydd,

I've though about this issue many times, because, often, I'd prefer to use availabe, fitting system versions (as long as they fullfill the consumer requirements).

We use internal recipes, anyways, and have structured them in a way, that a Conan recipe can have different implementations. E.g. a `OpenSSLConanSource` and `OpenSSLConanSystem`. You can combine this with an option: `options = { "system": [True, False]}` 

The system one throws an `InvalidConfigurationError` if it's trying to be configured for a version, which is not the actual system version.

This allows you to always require "openssl/[>=x.y.z]", but then set in the profile you're building with if you fall back to a system version, or use an actual conan package.

**Comment by thegwydd** [comment]
Hi @KerstinKeller 

I was thinking about creating custom recipes but it would be nice to have some support from conan in order to avoid custom recipes.

In some scenarios custom recipes do not add too much work but in others it may add a lot.
For example I'm using mosquitto conan package with TLS enabled and I'd like to use system OpenSSL.
Even in this simple case there would be need to:
 -copy and modify mosquitto conan recipe
 -host a new server (I'm inside a company and can't use a private one) dedicated to conan
 -keep my custom recipe aligned to official one for future releases.

**Comment by czoido** [comment]
Hi @thegwydd,
I would suggest two ways of handling this scenario.
1. Creating your own openssl recipe so that it handles all the logic you need to decide which openssl you want to use: the one installed in the system, the one special for your chips or another one. This way the consumer of openssl will not have to take care of all this logic and this will be transparent for him.
2. You could make different packages for each of the possibilities, for example, some kind of proxy for the system package that adds all the flags and paths for the system installed one to the conan `cpp_info` so that consumers have all the required information and you can call this something like `openssl/system` for example. You could also make another package repackaging all the special binaries for the chips using the [export-pkg](https://docs.conan.io/en/latest/reference/commands/creator/export-pkg.html) command with the name `openssl/1.0.3-modified`. Then you could make an [override](https://docs.conan.io/en/latest/versioning/introduction.html#dependencies-overriding) in the downstream consumer package handling all the logic there to decide which one of those to consume: `openssl/system`, `openssl/1.0.3-modified,` or maybe other versions you generated from the recipes in conan-center-index.
Please, tell me if this helps.

**Comment by thegwydd** [comment]
Thank you @czoido 

I've managed to solve the problem without touching mosquitto or openssl library.
In my library CMakeLists I've set, for Linux only, the following options in conan_cmake_run call:
    
`
    REQUIRES mosquitto/1.4.15@bincrafters/stable
    OPTIONS mosquitto:with_srv=False mosquitto:with_tls=False mosquitto:with_binaries=False
`

Then, just after the call:

`
  find_package(PkgConfig REQUIRED)
  pkg_search_module(OPENSSL REQUIRED openssl)
  
  if( OPENSSL_FOUND )
      include_directories(${OPENSSL_INCLUDE_DIRS})
      message(STATUS "Using OpenSSL ${OPENSSL_VERSION}")
  else()
      # Error; with REQUIRED, pkg_search_module() will throw an error by it's own
  endif()

  # set conan libs in any case because projects will use this
  set(CONAN_LIBS ${OPENSSL_LIBRARIES})

  # in any case enable the variable needed by mosquitto to use openssl
  set(WITH_TLS TRUE)
`

**Comment by AbrilRBS** [comment]
Closing in Conan 2, which after the addition of some of the latest features such as `[replace_requires]` and `[platform_requires]` issues like this can be solved by substituing recipes in the graph as needed ([Docs here](https://docs.conan.io/2/reference/config_files/profiles.html))
