### ISSUE TITLE
[question] update multiple lockfiles with a newly built package

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#6710]
I'm following the [How to use lockfiles in CI](https://docs.conan.io/en/latest/versioning/lockfiles.html#how-to-use-lockfiles-in-ci) tutorial where the example shows that the integration lockfile is updated with the new package through the `conan create`:

```
// # lockfile in release/conan.lock is modified to contain PkgA/0.2
cd PkgA && conan create . PkgA/0.2@user/testing --lockfile=../release
```

In my case, I have multiple projects that I want to integrate my changes into, and don't want to have to necessarily rebuild `PkgA` for each of them.

So I tried to create a new lockfile with which to update all integration lockfiles using  `conan graph update` 

```
// create new package (with a lockfile in current dir)
cd PkgA && conan create . PkgA/0.2@user/testing

parallel projects.collectEntries {
    
    (name_version, user_channel) = it.split("@")
    
    // update lockfile with newly created package
    command("conan graph update-lock ./release/${name_version}/${user_channel} .")
}
```

But this somehow adds a new node to the lockfile and gives me an error when I try to compute affected packages:

```ERROR: There are 2 binaries with name PkgA```

How would you suggest updating multiple lockfiles with a new package?

**Comment by czoido** [comment]
Hi @GordonJess,
If you have a newly created package and different lockfiles that you want to update. Assuming that all the versions/revisions in those lockfiles are consistent between them, maybe you could update that specific library information in the lockfile using the `export` command.

`conan export . PkgA/0.2@user/testing --lockfile=conan.lock`

This will mark the node as `"modified": "exported"` in the lockfile if you are exporting a new revision of the recipe. If you are exporting this package in a lockfile that has a different revision for a dependency, depending on the package id mode that you are using (recipe_revision_mode for example) you could have inconsistencies in the lockfile because of the changes in the package id, that's why all the revisions and dependencies have to be consistent across the lockfiles.
Please tell me if this helps.

**Comment by GordonJess** [comment]
Hey @czoido, thanks it worked!

Though I do have a few remaining issues which are related.

I want to obtain a list of any built/rebuilt packages to be able to upload them to artifactory.  This should be any package marked as `modified: built` in the `conan.lock` file, but it seems the lockfile parsing is broken due to unescaped colons in the `options` field (bug?).

e.g. 
```
"graph_lock": {
  "nodes": {
   "1": {
    "pref": "App/1.0.0@Concepts/master#40ac7c1baeac7a70c6eb6289f49de0d87e536834:e8d4a2a2fe455ea9a4b6437ca848aa0dafd4b585#8d6b3d000c2f23057b388b730a47097e",
    "options": "target_type=static_lib\nPkgA:target_type=static_lib\nPkgB:target_type=static_lib\nPkgC:target_type=static_lib\nPkgZ:target_type=static_lib",
...
```

So as a workaround I tried to obtain the list through the json output obtained from the install command to rebuild the affected package:

```
conan install ${affected_pkg_ref} --build=${affected_pkg_ref} --lockfile=${affected_pkg_folder} --json conan_install_out.json
```

but the built files are not marked as 'exported' here.

Is there something I am missing here?

**Comment by GordonJess** [comment]
> but it seems the lockfile parsing is broken due to unescaped colons in the options field (bug?).

Sorry, actually it seems unrelated to the colon...  but parsing still fails, and I think it is somehow down to the lockfile format.

`graph_lock.nodes.findAll{ it.modified == "built" }`

**Comment by GordonJess** [comment]
I solved the second issue.  I didn't notice that the nodes themselves were key:value pairs.
```
readJSON(file: "${WORKSPACE}/build/conan.lock").graph_lock.nodes.findAll{ it.value.modified == "built" }.collect{ it.value.pref }
```

The issue can be closed!  Thanks a lot!

**Comment by czoido** [comment]
Great! Closing the issue then!
