### ISSUE TITLE
[question] Can the conan version used be determined from package contents?

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#6742]
Is there any place in recipe manifests or binary package info metadata where the Conan version used to build it is "stamped"?

If not, can we add something?

This would be handy when attempting to eliminate questions such as "Has there been a change in conan recently?" when trying to resolve build issues.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> If not, can we add something?

> This would be handy when attempting to eliminate questions such as "Has there been a change in conan recently?" when trying to resolve build issues.

Though this sounds an interesting idea, actually we are being pushed in the opposite direction: package immutability.

Creating a package now, with Conan 1.23 and later with newer Conan versions should result in exactly the same revisions. As revisions are built from the recipe and package contents, having different data embedded in the packages would break this. There could be some manually defined in-recipe definition of the minimum Conan version required to run this recipe (similar to ``cmake_minimum_required()``, but this would still be manual, and only works as a lower bound, not to define the actual version used to build those packages, so I think that renders this approach of very low value.

This sounds to me like something that the CI process might be able to manage via properties in Artifactory instead.

**Comment by michaelmaguire** [comment]
Hmmm.  I would have though stamping with version of a tool used was pretty standard and would have been uncontroversial as a feature request.

```
libpadlock.so:     file format elf64-x86-64

Contents of section .comment:
 0000 4743433a 2028474e 55292034 2e342e37  GCC: (GNU) 4.4.7
 0010 20323031 32303331 33202852 65642048   20120313 (Red H
 0020 61742034 2e342e37 2d313729 00474343  at 4.4.7-17).GCC
 0030 3a202847 4e552920 372e332e 31203230  : (GNU) 7.3.1 20
 0040 31383033 30332028 52656420 48617420  180303 (Red Hat 
 0050 372e332e 312d3529 00                 7.3.1-5).       
```

**Comment by memsharded** [comment]
Yes, because that is part of the compiler needed to compile that thing. This is also "timestamped" in Conan in the packageID. But you wouldn't find the cmake version or the make version or other things in that binary. Same same OS + same source code + same compiler = same binary. You might change the make version and still get exactly the same executable.

It depends what you consider immutable in the environment and what shouldn't affect such immutability.

If Conan captures the conan version in the recipe manifest, then everytime you upgrade the Conan version, your package revisions in the server aren't the same, and you need to completely rebuild everything. For every minor Conan 1.23.X patch version, too. You also need all the CI machines and developers machine to upgrade exactly at the same time, otherwise generated revisions will not match and can be continuously overwriting each other, resulting in missing binaries for those machines that were not the last to upload the latest revision to Artifactory.

**Comment by michaelmaguire** [comment]
> If Conan captures the conan version in the recipe manifest, then everytime you upgrade the Conan version, your package revisions in the server aren't the same, and you need to completely rebuild everything.

I totally buy the reason you'd want to *not* put Conan version in the recipe, so as to avoid RREV changes. 

Can you put it in the binary package though?  PREV changes make sense if you rebuilt with a new version of Conan, right?

**Comment by memsharded** [comment]
For example a header-only library would never change the package revision either.

For compiled libraries, now it is difficult, but that is the goal of deterministic builds (https://blog.conan.io/2019/09/02/Deterministic-builds-with-C-C++.html). At the moment is complicated, but Linux is doing good progress there. If a package could be rebuilt and get exactly the same package revision, that would be amazing, and save tons of CI time.

**Comment by AbrilRBS** [comment]
Closing as wont-do for the reasons explained above, Conan 2 also does not add its version to the packages
