### ISSUE TITLE
[question] Offline - Extracting dependency tree with conan_api (without remotes)

### ISSUE THREAD

**Issue by ranifisch** [conan-io/conan#6754]
Hi,

I want to to extract all dependencies specified in the `requirements(self)` function.
I would like to use the conan_api to do that(or any other function from the conan repo). I know I have the `info` function, but it is based on the packages on the remotes/local cache. I would like it to work offline.

How can I do it?

**Comment by memsharded** [comment]
Hi @ranifisch 

The local cache is offline, that is not an issue, why ``conan info`` wouldn't be a possibility. Could you elaborate a bit more on your use case? What problem are you trying to solve? You might want to have a look to the generated ``conan.lock`` lockfile when you do a ``conan install`` or similar. It has encoded the whole graph. There are other commands that will output a json with dependencies information too.

**Comment by ranifisch** [comment]
Hi @memsharded 

the use-case is this:
I have a project, with tens of micro-services, and few libraries(all of the micro-services and libraries have conanfile.py ofcourse).
All the micro-services depend on some of the libraries. Some of the libraries might depend on other libraries as well.

Suppose I'm updating library X from version 1.0.2 to 1.0.3, What I want to do is update all the libraries/microservices that depend on it.(update the self.requires in each of the micro-services/libraries that depend on X), then do auto-commit(only on non-breaking API update ofcourse)

I know that I can use the range feature in the requires statement, but because there are too many micro-services and libraries, and there are a lot of dependencies, many conflicts occur when running `conan install`.

because of the reason I mention above, I decided to change to the exact version and write a side script.

Thank you very much.

**Comment by memsharded** [comment]
Quick side question: if this is intended for rapid development, have you considered using revisions instead of bumping versions?

To inspect real dependency graph you could try:
```bash
$ conan install poco/1.9.4@
# The packages are in the cache
$ conan info poco/1.9.4@ --json=file.json
```
The ``file.json`` file will contain the dependencies. The ``conan info`` command will not use the internet if the packages are already in the cache.

The lockfile also contain this info, but in a more abstract way (a bit more difficult to parse maybe):

```bash
$ conan graph lock poco/1.9.4@  # inspect the conan.lock file
```

In any case it seems you are trying to automate this step, so it sounds more like a CI flow. We are right now putting a lot of time in defining recommended flows for this. Some will be explained in the ConanDays CI/CD training (will be online). The general idea is:

- Use package revisions for minor, continuous changes that need to be integrated automatically downstream. Manual versions don't play nicely for concurrent development, different developers.
- Changes in versions require manual adoption downstream, as they will typically require developer intervention.
- The way to integrate revisions is to use lockfiles to capture the state of the "develop" packages, typically in one Artifactory repository.
- The lockfile can be used to build with the changed package, and re-build consumers of that package as necessary. New built packages are uploaded to a "builds" Artifactory repo.
- Only when the changes are approved (merging the source code changes), because it is good, as it doesn't break downstream, the packages can be copied from the ``builds`` repo to the ``develop`` repo.

There are many pieces here, and features we are currently improving, as lockfiles, but this seems to be a good flow for fast and robust CI flows. Please be patience, there is still a lot of work we need to do here too, and keep tuned in next releases and to changes in the docs with more examples. Thanks!
