### ISSUE TITLE
Discuss custom generators requirements model

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#6790]
Right not custom generators are globally registered, but they can be packages that can be required. Most likely they could be python_requires, (and affect the package_id too?), but still what to do with the global registration?

Example: 2 different packages can have a ``requires = "mygen/0.1"`` and ``requires = "myothergen/0.2"``, but both can register globally exactly the same generator by name, and they will overwrite each other. This can happen also with "private" requirements or even "build_requires", which can require 2 different versions of the same generator, and will still overwrite each other without warning or error

It is also problematic that custom generators need to have a package binary, otherwise they raise a "Package not found" exception. Python-requires, on the contrary, do not need a package binary.

Related: https://github.com/conan-io/conan/issues/7432
Related: https://github.com/conan-io/conan/issues/7433

**Comment by jgsogo** [comment]
I think I need more information here about the pain/proposal/alternatives... if not me, our future "we" will need more text to understand this issue.

**Comment by memsharded** [comment]
Done

**Comment by maikelvdh** [comment]
@memsharded is there any way on how to handle this correctly? I am noticing on our side that it seems fairly random which version of the custom generator is globally registered, which is leading to surprises as it might be that certain version is not backwards compatible.

**Comment by markovandooren** [comment]
@jgsogo I just ran into this problem, so I can at least explain the 'pain' part ;).

I use a custom generator for dealing with C++, C#, and C++/CLI. I have packages A and B, and package A depends on package B. Both packages use a python_requires to get the custom generator. I was working on package A and noticed that I need to change the generator to get source server support working in Visual Studio. I changed the generator and updated my python_requires for package A. To my surprise, however, it is still using the old generator. 

After looking at the source code of Conan I noticed the global dictionary, which explains why it behaves like that. Package B, however, has no dependencies so it does not need to get any sources from a source server. There is no need for me to update package B other than to let package A use the new generator. It's not a big problem now since I'm just starting to integrate Conan into our infrastructure, but once we have a decent number of packages, having to bump dependencies all over the place will be a problem.

If the generators are linked to the python_requires version, then you can select the correct generator for each package.

**Comment by memsharded** [comment]
Global dictionary has been dropped for 2.0.
Custom generators will be implemented in ``python-requires`` only for 2.0, and not extending any ``Generator`` class.
