### ISSUE TITLE
[bug] example poco/md5 fails with "undefined reference"

### ISSUE THREAD

**Issue by GRASBOCK** [conan-io/conan#6808]
The example won't link.

### Environment Details
GCC Compiler (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Conan 1.24.0
Python 3.8

### Steps to reproduce
git clone https://github.com/conan-io/examples.git && cd examples/libraries/poco/md5
./build.sh

### Logs
```
...
[100%] Linking CXX executable bin/md5
CMakeFiles/md5.dir/md5.cpp.o: In function `main':
md5.cpp:(.text.startup+0x9b): undefined reference to `Poco::DigestEngine::digestToHex[abi:cxx11](std::vector<unsigned char, std::allocator<unsigned char> > const&)'
collect2: error: ld returned 1 exit status
```

**Comment by uilianries** [comment]
Hi @GRASBOCK ! Which profile did you use? Could you please share your entire log?

I though you need to configure the settings.compiler.libcxx to libstdc++11.

On the Getting started section, step 7, there is an explanation:
https://docs.conan.io/en/latest/getting_started.htm

Plus:
https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html

**Comment by GRASBOCK** [comment]
These are the contents of the default profile 
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

Changing compiler.libcxx=libstdc++ to compiler.libcxx=libstdc++11 in the configuration did the job. Thank you very much!

**Comment by memsharded** [comment]
Yes, please carefully read the docs, it is an "Important" green notice in https://docs.conan.io/en/latest/getting_started.html, saying:

```
Important

If you are using GCC compiler >= 5.1, Conan will set the compiler.libcxx to the old ABI for backwards compatibility. You can change this with the following commands:

$ conan profile new default --detect  # Generates default profile detecting GCC and sets old ABI
$ conan profile update settings.compiler.libcxx=libstdc++11 default  # Sets libcxx to C++11 ABI

You will find more information in How to manage the GCC >= 5 ABI.
```

**Comment by GRASBOCK** [comment]
I didn't know what it meant. Guess I should have researched first.

**Comment by memsharded** [comment]
> I didn't know what it meant. Guess I should have researched first.

Oh, that is an inconvenient thing, we wrote a bit about it a long time ago if you want to have a look: https://blog.conan.io/2016/03/22/From-CMake-syntax-to-libstdc++-ABI-incompatibiliy-migrations-are-always-hard.html

The problem is that there are 2 builds of the standard C++ library, the "classic" one ``libstdc++`` and the one with C++11, ``libstdc++11``. You need to use one or the other, and the resulting binaries are incompatible. In theory, older compilers than gcc 5.1 use ``libstdc++`` and newer versions use ``libstdc++11``. But unfortunately this is not always true, and older linux distros, as the ones used to run in Travis-CI, could update the compiler to gcc > 5.1, but they would use the old ``libstdc++``.

So we had to leave the ``libstdc++`` configuration as the default one in Conan, to be as "compatible" as possible. But for gcc>5.1 in newer linux distros, it means that you need to change the configuration if you are building with the newer one.

I hope this clarifies a bit the issue. Cheers!

**Comment by GRASBOCK** [comment]
thanks. I hope that conan will not get cluttered with such things in the future.

**Comment by linhanwang** [comment]
[root@462b46a40801 md5]# cat /root/.conan/profiles/default 
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

I think my configuration is correct. But I still have the problem.

centos 7.2;conan 1.27.0;Python 3.6.8

**Comment by memsharded** [comment]
Hi @linhanwang 

Are you using Devtoolset7? (I would say that is used in Centos7.2) It seems it is ignoring _GLIBCXX_USE_CXX11_ABI, so it will be defaulting to libstdc++ (https://bugzilla.redhat.com/show_bug.cgi?id=1546704). Have you tried changing your profile to ``compiler.libcxx=libstdc++``, do ``conan install`` again, and build again?

**Comment by skylight-hm** [comment]
Thanks a lot. Things are right now. Devtoolset7 and Devtoolset9 have the same problem.
