### ISSUE TITLE
Sub-package not found during build

### ISSUE THREAD

**Issue by punkcito1** [conan-io/conan#6820]
I'm attempting to create a conan package for a Visual Studio project that has a dependency.  This project is using the source and recipe in the same git repository scheme with the SCM attribute.  The source is retrieved separately after which conan install is called to install the dependency.  When calling conan create the source is copied to the cache and the build is started, however, the dependency information conanbuildinfo.props does not appear in the cache causing the build to fail.  

Is there a way to either get the dependency info in the cached copy of the source or build directly from the users source directory?

**Comment by jgsogo** [comment]
Hi, @punkcito1 

The command `conan create` should do all the job: retrieve the source, copy them to a build folder, install the dependencies (using the declared generators), build the library and gather the binaries to create the Conan package.

From what you say, I think that your build is failing in the cache because the `conanbuildinfo.props` file is not there. This file shouldn't be copied to the cache, but generated there by Conan. Are you declaring the generator for `visual_studio` in your recipe?

```python

class YourRecipe(ConanFile):
    ...
    generators = "visual_studio"
    ...
```

**Comment by punkcito1** [comment]
I found the problem.  Conan correctly obeys the gitignore list when copying files from the users local repository directory.  I had configured my setup to put the install files under an x64\Debug directory which would be ignored.
