### ISSUE TITLE
[bug] New init() recipe method runs before name/version attributes are assigned

### ISSUE THREAD

**Issue by himikof** [conan-io/conan#6826]
### Environment Details
  * Operating System + version: Linux, Fedora 30
  * Conan version: 1.24.0
  * Python version: 3.7.6

When the new `init()` method runs, the recipe object is currently in a partially initialized state. I was very surprised to find that the name/version attributes from the command line are assigned only after the `init()` is executed. I did not find any documentation on what attributes are safe to access in `init()`, and which should not be accessed. But at least the name/version attributes seem like ones that should always be available.

My use case that triggered the problem was to look some information up in `self.conan_data` based on the recipe name/version passed from the command line. The data from `conandata.yml` is fully loaded at this point, but, suprisingly, name/version are still not set.

**Comment by memsharded** [comment]
Hi @himikof 

As the documentation states, the init() function is intended for processing python_requires. It is the very first thing that is called when loading, if the ``name`` and ``version`` are not defined as class attributes, they will not be defined yet. If they are defined in ``set_version()`` for example, that runs after the ``init()`` indeed. It is very much like the ``__init__()`` python method, but controlled by Conan to serve for this purpose. 

What are you trying to do in the init() method? Something related to ``python_requires``?

**Comment by himikof** [comment]
I'm not exactly using `python_requires`, but I tried to append to some attributes using declarative data in `conandata.yml`, instead of a python base. I wanted the data in YAML be keyed by the name of the recipe passed from command line.

Is the `init()` method not the right method to use to set arbitrary attributes during initialization? It seems very much fitting for this purpose.

**Comment by memsharded** [comment]
> Is the init() method not the right method to use to set arbitrary attributes during initialization? It seems very much fitting for this purpose.

Yes, as explained in the docs, https://docs.conan.io/en/latest/reference/conanfile/methods.html#init, this method is designed for filling a void at class initialization from inherited ``python_requires``, and that is the documented use case.

If you could explained a bit more your use case, then maybe we could take it into account and provide and document other usages of the method, but we need to be sure, because this can open the doors to a new set of problems. It might be possible to use to define some attributes, but if it is declarative, it should be declarative, but it seems you are trying to apply also some conditional logic at the same time. Maybe trying to completely define the object model from the data in conandata.yml is also a bit of abuse of the conandata.yml. Some more explanation about the potential advantage to define such in conandata.yml instead of the recipe itself might be useful too, thanks.

**Comment by memsharded** [comment]
Closing as stale, likely outdated in Conan 2
