### ISSUE TITLE
[feature] Lumin OS support

### ISSUE THREAD

**Issue by strentler** [conan-io/conan#6850]
I miss support for Lumin OS in Conan.

1) Any plans to support this? 
2) What is a good workaround?

See:
https://www.magicleap.com/en-us/news/product-updates/lumin-os-0-98-10

**Comment by memsharded** [comment]
Hi @strentler 

Adding new OS, compilers, etc. to the model is pretty straightforward: https://docs.conan.io/en/latest/extending/custom_settings.html. That is enough to model different binaries for a different OS. If the toolchains in that os behave very differently to others, they might need their own build helpers and generators (https://blog.conan.io/2019/07/24/C++-build-systems-new-integrations-in-Conan-package-manager.html).

**Comment by strentler** [comment]
Thx for the feedback @memsharded.
They have their own build system based on .mabu files:
https://developer.magicleap.com/en-us/learn/guides/magic-leap-builder-overview

They also have some way of building the libs through CMake:
(Search for CMake) https://developer.magicleap.com/en-us/learn/guides/sdk-mabu-ref-build-and-link-libraries

I managed also to compile some third party libs through 'make' by setting the right environment variables.

**Comment by memsharded** [comment]
Thanks for the pointers @strentler 

Having a look at this, it doesn't seem that we might provide built-in support for Lumin, at least in the short term. It is a proprietary thing and a bit closed, not very mainstream yet, and we have zero experience with it. So it seems integrations should probably be in their end and they should maintain them (or a community of Lumin users wanting to use Conan too). I suggest reaching to them and asking, we would support any effort to integrate with Conan.

**Comment by strentler** [comment]
Hi @memsharded,

what do I need to do to make Lumin OS included by default in Conan?
Which criteria does such a PR need to fulfil? I mean having Lumin OS in settings.yml by default after installing conan from conan.io.

**Comment by memsharded** [comment]
Hi @strentler 

For including these things as built-in in Conan, they need to have a compelling evidence of community request.

Please take into account that having your own custom settings.yml and maintaining them for your company and developers is very easy with ``conan config install`` command. So the main point to include them in the default ``settings.yml`` is either because it is needed to generate packages in ConanCenter, which is not possible for obvious reasons, or that it is so mainstream that a large percentage of Conan users would benefit from these values.

So my recommendation is to put your settings in a repo or zip file and manage them with ``conan config install``, which in any case would be needed because the ``profiles`` need to be managed too in the same way, and it seems reasonable that the ``remotes.txt`` too, because the binaries for this system would be hosted in a private server too, not the public ConanCenter. If we see Conan is being used by users from LuminOS (that can be seen in activity, issues reported, etc), then we would consider adding them to the default.

**Comment by memsharded** [comment]
It has been a while, and there is no evidence of the wider community demand for supporting this platform. As explained, as it is very easy to add custom settings, and many users are maintaining their own settings.yml to manage their own OS and configurations, I don't think we should add Lumin OS support in the default settings.yml at the moment.

Do not hesitate to ask if you need help for managing your custom configuration. Thanks for the feedback!
