### ISSUE TITLE
[question] how to get the oringinal conan project path in the source() method?

### ISSUE THREAD

**Issue by joeysmart** [conan-io/conan#6868]
os.path.dirname(__file__) delivers the export path

**Comment by uilianries** [comment]
Hi @joeysmart ! Could detail why do you need it?

If you are looking for the source folder, because it's part of the project, you can use [self.source_folder](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#source-folder)

But if really want to find the Conan project path, because you want to execute some extra steps, you should try [hooks](https://docs.conan.io/en/latest/reference/hooks.html)

**Comment by memsharded** [comment]
You can't. When the source() method executes in the Conan cache, it cannot depend on anything external. Whatever is in the cache should have been exported via ``exports`` or ``exports_sources``, or the ``source()`` method should get it from somewhere that is reproducible, like an URL (git clone, tools.download(), etc). You might be interested in the SCM functionality, but that will still copy automatically things to the cache, you still don't have access to the user folders when you are inside of the Conan cache. This is the way to achieve reproducibility.

**Comment by matz1** [comment]
Hi @memsharded,
I have a similar problem, see: https://github.com/conan-io/conan/issues/6891
I wrote a generator which creates a configuration file for an code analyzer. In the configuration file I have to provide the path to the .git direcotry of the original conan project. The exports_sources attribute filters out the .git directory. Now I am searching for a good way to resolve this problem.
