### ISSUE TITLE
[Question] conan info for a specific package id

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#6885]
Hello, 

I have two packages with the same version, same options, same settings but different requirements.

output of conan search command
```
>conan search  my_package/1.0.0@walid/testing
Existing packages for recipe my_package/1.0.0@walid/testing:

    Package_ID: 2d49981400eb318185d516f42e43c993c066a3ed
        [options]
            shared: True
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.version: 14
            os: Windows
        [requires]
            zlib/1.2.11@walid/stable:4a139a8ef383e285d40e88301506605603e78c47
        Outdated from recipe: False

    Package_ID: c627d26513e4a9db441b6cffe3ecd67ac8401c01
        [options]
            shared: True
        [settings]
            arch: x86_64
            build_type: Release
            compiler: Visual Studio
            compiler.version: 14
            os: Windows
        [requires]
            zlib/1.2.11@walid/testing:4a139a8ef383e285d40e88301506605603e78c47
        Outdated from recipe: False
```

How can I inspect the package `2d49981400eb318185d516f42e43c993c066a3ed` using `conan info` ?

**Comment by memsharded** [comment]
> How can I inspect the package 2d49981400eb318185d516f42e43c993c066a3ed using conan info ?

Not sure what you mean. You want to go to the cache and inspect the files of this particular package?

I can deduce that you are using some ``default_package_id_mode`` or some ``package_id()`` that makes the user/channel included in the package_id hash, right?

**Comment by boussaffawalid** [comment]
The confusion I have, when I run `conan info my_package/1.0.0@walid/testing`, which package info  I will get `2d49981400eb318185d516f42e43c993c066a3ed` or `c627d26513e4a9db441b6cffe3ecd67ac8401c01` ?

in my case, user/channel are included in the package_id hash.

**Comment by memsharded** [comment]
It depends on your transitive dependencies.

- If ``my_package/1.0.0@walid/testing`` has a ``requires = "zlib/1.2.11@walid/stable``, you will get the package_id: ``2d49981400eb318185d516f42e43c993c066a3ed``
- if it ``requires = "zlib/1.2.11@walid/testing``, then the package_id will be ``c627d26513e4a9db441b6cffe3ecd67ac8401c01``

**Comment by boussaffawalid** [comment]
my idea was to provide the package id as argument to `conan info`, something like
`conan info my_package/1.0.0@walid/testing --id 2d49981400eb318185d516f42e43c993c066a3ed `

**Comment by gsemet** [comment]
i also would like to have information for a specific package id:
```
conan info my_package/1.0.0@walid/testing --id 2d49981400eb318185d516f42e43c993c066a3ed
```
I need the path in cache of the `package` folder.

**Comment by cboos** [comment]
Why not just the `conan info my_package/1.0.0@walid/testing:2d49981400eb318185d516f42e43c993c066a3ed`, already supported by other commands? (e.g., `conan upload`).

**Comment by memsharded** [comment]
Because ``conan upload`` doesn't need to evaluate the recipe. Just take the files and upload them.
In the same spirit ``conan inspect`` doesn't need to evaluate the recipe either.

The ``conan info`` command is a "graph" command. In Conan 2.0 it has been renamed to ``conan graph info``. As such, it needs to evaluate the full dependency graph, and a dependency graph to be evaluated need the inputs, basically the ``profiles``. Based on those profiles it can evaluate conditional requirements, conditional options, etc, and all of that will result in different ``package_id``. But knowing a ``package_id`` cannot be reverted to a given configuration, it is a one way hash. For example a header-only library will have the same ``package_id`` for all configurations, so knowing its ``package_id`` is insufficient to evaluate the dependency graph.

Also the command ``conan search mypkg/version`` is capable of giving ``conaninfo.txt`` information for existing package_ids.

**Comment by cboos** [comment]
Thanks for the detailed reply. Indeed, when you invoke it like `conan graph info`, I believe you'd think about using the profile.

I believe the user interface "problem" is more like:
-  `conan search packagename` → list of packages with version @ user / channel;
-  `conan search packagename/version@user/channel` → summary of each installed package, with the binary ids;
-  ... now what should I do next in order to get more information about a specific package id?

In particular, what would be a quick way to find the location of the binary packages, the paths shown by `conan info packageref -pr ... --paths`. The fact that for getting that information you have to switch to another command (which one? info, inspect, ah no, inspect is about the recipe only... so it must be info) and to another selection mode (hm, what is the profile that would get me to that binary package for which I just happen to see the precise id already...) seems not that user friendly!

But I just looked at the Conan 2.0 doc, and this is indeed all resolved in a nice way by the introduction of the `conan cache path` command, 👍 !

**Comment by memsharded** [comment]
> But I just looked at the Conan 2.0 doc, and this is indeed all resolved in a nice way by the introduction of the conan cache path command,

Yes, exactly! We are trying to decouple concerns, one thing is information about the graph, another is the location of a given package in the cache. 

Even if you have ``conan cache path``, Conan 2.0 provides a new abstraction: ``deployers``, that are intended to automate the task of extracting files from the cache and operating on them. ``conan cache path`` is more for devs and debugging, for automation, you might want to check ``deployers``.

**Comment by memsharded** [comment]
Closing as solved with Conan 2 (the new ``conan graph explain`` is also useful for some of these cases)
