### ISSUE TITLE
Path to current conanfile in custom generator

### ISSUE THREAD

**Issue by matz1** [conan-io/conan#6891]
Hello,

I have a question regarding custom conan generators. I wrote a generator like described here:
- https://docs.conan.io/en/latest/howtos/custom_generators.html

The generator creates a build file for an code analysis tool. In the build file I have to provide the path to the .git directory of the package. My question is:
- Is there a way to get the path of the currently executed conanfile
- I also tried to provide the source_folder in the conan cache with exports_sources='.git*' but the     .git directory seems to be ignored
- If there is no way to get the path of the conanfile do you have another solution for my 'problem'?

**Comment by danimtb** [comment]
Hi @matz1,

I think I don't fully understand what is the exact conanfile you would like to get the path to.
- The Conanfile from a reference you are installing? ``conan install mypkg/1.0@user/channel`` (the recipe of that reference)
- The conanfile of the consumer? ``conan install conanfile.py``

In the first case, maybe you can use https://docs.conan.io/en/latest/reference/generators/custom.html#conanfile deps_cpp_info rootpath.

For the second one, this https://docs.conan.io/en/latest/reference/generators/custom.html#output-path is the closer you can get to the path of the consumer conanfile

**Comment by boussaffawalid** [comment]
im facing the same issue. 
In my custom generator, I want to write scm info to a file and for that I'm trying to use `tools.Git(folder=<source folder>)`. 

I need to know the path of my conanfile.py (path of my source directory) so that I can pass it the tools.Git

I tried to use `git = tools.Git(folder=conanfile.source_folder)` but this only works when creating conan package but not when running `conan install conanfile.py`

**Comment by matz1** [comment]
Hi,

thanks for the help so far.

I first want to describe my problem more precise:
I am writing an generator which creates a configuration file for a
code analysis tool. In the configuration file I have to provide
the path to the .git directory of my conan package which uses the generator.
Since I always put my conanfile.py in the root directory I asked for the
path to the conanfile.

@danimtb
I need the path the the conanfile of the consumer (your second point) of the generator.
Not the copied one in the conan cache but that after cloning a package.
The output_path variable points to the build directory in the conan cache.
Is there a way to get the path to the conanfile which is specified
when you call
$ conan create [options] requested_path_to_conanfile [reference]?

Or is there a standard way to also automatically export the .git
directory to the source_folder of the conan cache? Then I could use the source_folder
attribute at least in the case of conan create.

**Comment by matz1** [comment]
@danimtb 
In https://github.com/conan-io/conan/blob/develop/conans/client/file_copier.py on line 133 the copying of the .git directory is prevented. Is there any possibility to access the .git directory of the package when building the package inside the conan cache.

**Comment by memsharded** [comment]
I am reopening this, I think this is still valid, and an interesting feature request.

Most likely this shouldn't be in the generators side, but on the toolchain one. Conan recipes are soon learning a new ``toolchain()`` method, that will take the functionality from the generators regarding the build configuration. Will probably not be enough for the fact that the .git folder is not copied to the cache (because it is not packaged), but will be surely a better approach.

For the .git folder, maybe the best approach could be:
- Capture what you need in the export stage (conan will learn new ``exports()`` and ``exports_sources()`` methods, from your current .git, and create a file
- If you have the info of what you want to do, use the ``toolchain()`` method to automatically generate information for the current build (and leave generators to generate info about dependencies)

**Comment by bldrvnlw** [comment]
Nice to see this reopened. We also have a similar situation where access to the git (specifically the current branch name) is used to derive information for the build. In our case that is the versioning for feature branches which need to be coordinated across projects. 

For the moment I can use the export() method route to communicate the necessary information.

**Comment by memsharded** [comment]
This was fixed in the ``generate()`` method, closing as solved
