### ISSUE TITLE
conan.exe does not observe non_interactive configuration for lock issues

### ISSUE THREAD

**Issue by gprosch** [conan-io/conan#6897]
If I run the conan executable with an install command I still get a prompt when there is a lock issue.

I shouldn't because I have set the CONAN_NON_INTERACTIVE environment variable to 1 and added non_interactive = True to the conan.conf file under the [general] section.

This is a major issue on our build server because the prompt causes the job to hang and jam up the build queue until the timeout interval of 90 minutes is reached.  I think the conan.exe should always honor the configuration.  

A better design IMHO would be to have an argument that can be passed to the executable.  The current implementation assumes that I will always want it a certain way but using an arg allows me to make that decision when I am running the conan command.  I will put in a feature request for this.

### Environment:

Windows 10 Build 19041
Conan v1.24.0
Python v3.8.2

### Steps to reproduce:

Add CONAN_NON_INTERACTIVE to your environment and value to 1 and/or set non_interactive = True in conan.conf
Do something that creates a lock issue.
Run a conan install command (e.g. conan install ".\conanfile.txt" -s arch="x86" -s build_type="Release" --build=missing)
Observe that a prompt regarding the lock issue appears.

**Comment by czoido** [comment]
Hi @gprosch,
Thanks a lot for reporting. I think that this issue is not related to the `CONAN_NON_INTERACTIVE` mode but to another possible bug. When the lock appears is not a prompt but a warning message but I have been able to reproduce that Conan gets stuck at that point under certain conditions so we will investigate this further. 
So Conan is still honoring `CONAN_NON_INTERACTIVE` there but the issue comes from another place. We'll investigate this issue further. Thanks a lot.

**Comment by czoido** [comment]
This is related to: https://github.com/conan-io/conan/issues/5500

**Comment by memsharded** [comment]
Closing as outdated:
- Conan 2 cache is not concurrent and doesn't use any locking
- The configuration system has also changed

Please create new tickets as necessary reporting against Conan 2.X
