### ISSUE TITLE
[bug] conan upload should also check stat of the files (file mods, like whether files are executable or not )

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#6903]
Conan upload does not check for stat of the apps, it probably just calculated checksum of the files to calculate whether local package is different than remote one.

How to reproduce:
Have a package  - upload it to artifactory.
do a chmod +x on one of the files, 
`conan create` and `conan upload `
Upload will be skipped and recipe wont be uploaded.

This causes problem in both upload and install -u. 

### Environment Details (include every applicable attribute)
  * Operating System+version: rh6/rh7
  * Conan version: 1.24.0
  * Python version: 3.6.10

**Comment by czoido** [comment]
Hi @fulara,
Could you please give me more details about the use case? 
Right now as you say conan is not going to take into account those changes, I think that the only case in which permissions are going to have influence over the created package reference is if you are using conan SCM mode for the recipe with `revision=auto` and git with `core.filemode true`. In that case if you have revisions enabled a change in a permission of the file and a subsequent commit will generate a new recipe revision.

**Comment by fulara** [comment]
Hm, the usecase. Slightly confused how the 'SCM' fits in the picture here. 
Minimalistic use case:
you have some kind of scripts on repositories, and these needs to be 'executable' but you have forgot to mark them as executable. 

Full process to reproduce:
```
$ cat conanfile.py 
from conans import ConanFile, tools

class Conan(ConanFile):
    name = "fulara-test"
    exports_sources = "script.sh"

    def package(self):
        self.copy("*")
    pass

$ ls
conanfile.py  script.sh

conan create . 1.0.0@mmt/fulara
# .. creates packages
conan upload 'fulara-test/1.0.0@mmt/fulara' --all
# upload packages..

#oops! you have realization i forgot to chmod +x one of the files, because of that my build is borked!
chmod +x script.sh
conan create . 1.0.0@mmt/fulara
# .. creates packages
conan upload 'fulara-test/1.0.0@mmt/fulara' --all
# UPLOAD SKIPPED! conan does not detect the files have changed.
```

**Comment by czoido** [comment]
> Hm, the usecase. Slightly confused how the 'SCM' fits in the picture here.

Yes, sorry if I introduced noise in the conversation, I said it in case you were using SCM mode, in that case, as git can be configured to detect changes in the file permissions, as a side effect conan would be too, because the commit affects the conan revision when exporting.

I don't know if this a thing to address right now but we will have a review at it for a possible feature like a mode that takes file permissions into account for Conan v2.

Thanks a lot for the suggestion!

**Comment by fulara** [comment]
SCM is something I have not explored yet.
I think SCM is very limiting because its an attribute, so its hard to use with dynamic versions etc :).
But one day I will try to use it.

**Comment by memsharded** [comment]
We have decided the following for Conan 2.0:

- By default only the recipe and package revisions will be taken into account. If the revision is already in the server, nothing will be uploaded
- The revision is still computed as the hash of all the files contents (from the ``conanmanifest.txt``). Only the file contents is used here
- Other stat of files will not be used. Because it changes between OSs, it is fragile, etc. It cannot be put into the revisions robustly across different platforms.
- If there is a change of permissions or something that needs to be fixed, the best is to do a change in the recipe
- Otherwise, it is necessary to ``--force`` the upload
