### ISSUE TITLE
[question] Access build_requirements of dependencies via conanfile.py

### ISSUE THREAD

**Issue by seanmlyons22** [conan-io/conan#6919]
Hello Conan Devs,

**Background**

We're currently using conan to package an SDK inside our company.
This SDK includes source code, libraries, and documentation for the "core" parts of our platform including drivers, kernel, etc.

We have a waterfall approach where this core SDK is consumed by higher level developers (e.g. RF stacks) who consume the core sdk and build their products on top of it.

Currently all the dependencies necessary to build this core SDK are defined in `build_requires` of the core sdk package.
The `build_requires` includes things like toolchains, configuration tools, as well as actual packaging tools for building the SDK such as doxygen to build documentation. Currently we keep these out of requirements to avoid the diamond dependency problem.

however, we want to have a "developer install" option that will pull in the toolchains and other requirements for building, but not those related to packaging such as doxygen. I feel this is similar to the discussion that is going on [here](https://github.com/conan-io/conan/issues/5610).

**Question**

In these questions, I will assume that we have a package called `RFStack` that depends on a package `CoreSDK`.

To achieve this, we have come up with a couple proposals/questions:

1. Is it possible to access `CoreSDK`'s `build_requirements` from `RFStack`'s  `conanfile.py`? The intent is peek inside the `build_requires` of the `CoreSDK` and install the toolchains needed if we're in developer mode.

1. Assuming the above, isn't possible, we're thinking of exporting toolchain information inside user_info, which we should be able to access from downstream packages such as `RFStack` via `deps_user_info`. Is this a good idea, is there a better way?

1. If none of the above work, we're thinking of running 
`conan inspect -a build_requires CoreSdk/ref@lib/channel` as a subprocess inside `RFStack`'s conanfile.py to grab these. This seems like a last resort.

Your inputs on the best approach will be much appreciated.
Thanks for making conan!
 

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @seanmlyons22 

> Is it possible to access CoreSDK's build_requirements from RFStack's conanfile.py? The intent is peek inside the build_requires of the CoreSDK and install the toolchains needed if we're in developer mode.

No, ``build_requires`` are private to each package, and they are not visible from downstream consumers. Furthermore, it is important to know that currently build_requires are only in the graph when that package that uses them needs to be built from sources. If you are using the CoreSDK and there is already a pre-compiled binary for it, the build_requires do not exist anywhere, they are not in the graph.

> Assuming the above, isn't possible, we're thinking of exporting toolchain information inside user_info, which we should be able to access from downstream packages such as RFStack via deps_user_info. Is this a good idea, is there a better way?

Have you considered defining ``build_requires`` in other location than the conanfile? There are 2 possibilities:
- Defining build_requires in the profile. Using profiles is totally recommended, and defining build_requires there is very convenient. They can be defined there for the whole graph or per-package too, and it is relatively easy to maintain.
- Defining a 2 step flow: Have a ``conanfile_tools.txt`` to define the environment, activate it with a ``-g virtualrunenv`` or ``-g virtualenv``, and then develop inside that environment. It requires like 3 commands, installing the tools, activating the environment, then developing, but we are aware of users successfully using this approach.

> conan inspect -a build_requires CoreSdk/ref@lib/channel as a subprocess inside RFStack's conanfile.py to grab these. This seems like a last resort.

Yes, I would discourage this approach, it will likely be problematic and error prone.


So at the moment I think I would go by defining them in the profiles instead of the conanfile. Please tell me what you think. Thanks!

**Comment by seanmlyons22** [comment]
@memsharded,

Thanks for suggestions and the quick response!

> They can be defined there for the whole graph or per-package too, and it is relatively easy to maintain 

I read up on profiles and they could work. Applying that to our example:

1. `CoreSDK` creates a build_profile file as part of its packaging process. Let's say one of the profiles defined is `arm_gcc_win`.
2. Downstream package `RFStack` consumes it. Developers can do 
`conan install .. -pr=arm_gcc_win` and they will get the tools defined by `arm_gcc_win` installed on their machine. Those who wish to consume the `CoreSDK`'s libraries instead of develop for it will specify no profile and thus get no additional tooling. Do I understand you correctly?

This sounds like a nice approach. Are there any benefits to using the two step flow that you mentioned over the build_profiles? Any other tradeoffs?

I'll take this with our team and get back to you.

**Comment by memsharded** [comment]
Hi @seanmlyons22 

> CoreSDK creates a build_profile file as part of its packaging process. Let's say one of the profiles defined is arm_gcc_win.

That seems an interesting approach, not what I had in mind, but I guess it might be possible to make it work (you might also implement a ``deploy()`` method to easily copy the profile to local folder? How do you plan to make ``arm_gcc_win`` available from the CoreSDK package?)

What I had in mind is defining the tools to build ``CoreSDK`` directly in the profile that you are using for it, and not in the ``CoreSDK`` recipe. You can also define different profiles, compose them, etc. So you could do:

```bash
$ conan install .. -pr=my_main_config_profile -pr=my_build_tools_profile
```
with ``my_build_tools_profile`` containing only something like:
```
[build_requires]
mytool/1.0@user/stble
mycompiler/2.0@user/stable
```
And they will nicely compose. And of course, you will also use this profile while building the CoreSDK too. Wouldn't this be a more direct solution and require less work on your side?

**Comment by seanmlyons22** [comment]
@memshared,

The motivation behind having the `CoreSDK` define the build profile `arm_gcc_win` is so that downstream consumers are using the right tools and compilers. Not so much the case with compilers, but usually there is a requirement that developers are using the right version of tools that match the `CoreSDK`. Put another way, the `CoreSDK` defines the tools for downstream packages.

Perhaps this is all just making a case for putting these critical dependencies in the `CoreSDK`'s `requires`. Our concern against this is that if another package specified these, we could run into a diamond problem.

Does that make sense?

**Comment by memsharded** [comment]
If the CoreSDK is a library that is being linked into your other products, then it is good to keep it as a regular ``requires = "core_sdk/version@user/channel"`` (btw, we recommend always lowercase for package names, that is the convention we use in ConanCenter), and then manage the tools as ``build_requires``. That approach is good that way.

What I am probably not understanding is because of missing some context, so the ``build_requires`` that you want to define for the consumers of ``CoreSDK`` are not exactly the same as the ``build_requires`` used to build ``CoreSDK`` itself? Or very very similar. In that case, you should probably be passing the ``build_requires`` to the command to create ``CoreSDK`` itself, and then you might be using that same input as the input for packages consuming ``CoreSDK``.

If this is a bit more dynamic, and you can be using a certain set of ``build_requires`` to build ``CoreSDK``, but it will impose other different ``build_requires`` to their consumers, then I think I could understand better your idea. In that case I would like to know a bit better the user story, and how do you envision how it would make more sense for your developers:

Ex. user story:
- I want to create an app that uses the CoreSDK functionality. So I write a conanfile and put there a requires to ``core_sdk/version@...``
- Now I need the build tools too to be able to build my own app. I could add an ``imports`` to my conanfile, to do a copy of some ``core_sdk_profile`` file from inside the ``core_sdk`` package
- I do the ``conan install .`` and I get the CoreSDK package installed in the cache, and a local file. (But this will be fetching the CoreSDK package for possibly a different configuration? Sure a different one if the ``core_sdk_profile`` contains other thing rather than ``[build_requires]``)
- Now repeat the ``conan install . -pr=core_sdk_profile`` to do the actual install I need

What is the user story for creating a package that depends on the CoreSDK? Because for that, you cannot use that profile internally in the ``build()`` method, and you need the profile first, maybe it is a bit non-ergonomic?

BTW, if you are in the CppLang slack, we usually hang around there. There is a #conan channel there, with more than one thousand users, the community there is amazing. If you want to talk directly to us, please write to info@conan.io, and I will put you in contact with some of the maintainers, that is usually very useful to discuss user cases more in depth.

**Comment by seanmlyons22** [comment]
@memsharded,

Thanks again for the detailed response!

> If the CoreSDK is a library that is being linked into your other products, then it is good to keep it as a regular requires = "core_sdk/version@user/channel"

This is a mistake on my part, I was copy-n-pasting the class name. Our package name is `coresdk`.

I thought a bit about our user story before getting back to you.

> so the build_requires that you want to define for the consumers of CoreSDK are not exactly the same as the build_requires used to build CoreSDK itself? Or very very similar.

The coresdk _should_ set the dependencies for downstream developers. Since we publish only a single set of tools in our customer facing SDK, everyone should be building and testing with the same. However, there are edge cases where this needs to be overwritten, but these are few.

So our user story would be this:

> I want to create an app that uses the CoreSDK functionality. So I write a conanfile and put there a requires to core_sdk/version@...

Exactly. Most of our downstream software is also packaged using conan, so each component would have a repo with a conan file that requires the coresdk.

> Now I need the build tools too to be able to build my own app.

Correct, and downstream packages should be using the same tools as the coresdk.
So what we want is a way for the coresdk to expose these tools (e.g. compiler and version) so that downstream packages can install them using conan. In the normal case some version of `conan install .` would take care of installing both the coresdk and tools so the developer is ready to begin working.

Less common cases, but still valid are:

- Someone who just wants to install the coresdk as a package (without tools) perhaps for inspection or test.
- Someone who wishes to depend on the coresdk, but use their own tools (perhaps grabbing them from conan). This case is very rare, but not out of the question.

Based on this story, what do you think is the cleanest way to implement in conan?

**Comment by seanmlyons22** [comment]
@memsharded, thanks so much for your help already.
Any thoughts on the last? Sorry for the delay in response.

**Comment by memsharded** [comment]
Sorry this was not followed up back then, sometimes the activity is so high some tickets fall through the cracks.

I am closing this ticket as staled.

I hope this was solved, if not, please reopen or create a new ticket to discuss it. Thanks!
