### ISSUE TITLE
[feature] Make the cache thread/process-safe for 'readonly' operations

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#6979]
Objective: compute `package_IDs` for different profiles in parallel.

Even though the Conan cache does not support parallelism/concurrency, we can improve some scenarios and maybe achieve some level of safety for some operations. Readonly operations, those that don't download anything, nor modify/remove a folder neither touch the metadata should be relatively easy to protect and run in parallel. 

Some examples are `inspect`, `info`, `graph lock`, `install`,... when all the packages are already in the cache. **This doesn't mean that we can state that those commands can be run in parallel, it is up to the user to know they won't trigger any download or modify any file and take the risk**.

Probably we only need to protect the function that loads and parses the conanfiles, and maybe little work around the `ReadLock` class.

**Comment by GeFrIt42** [comment]
Hi @jgsogo ,

According to the doc now the conan's cache now support concurrency for certain operation,
https://docs.conan.io/1/mastering/custom_cache.html paragraph **Concurrency** 

does this resolve this issue?

**Comment by memsharded** [comment]
Hi @GeFrIt42 

This issue was outdated. 
The Conan cache is  not concurrent safe either in 1.X or 2.0, there are no guarantees.
Conan 2.0 cache is not ready for parallelism yet, but it is a 2.X roadmap planned thing. The ticket that you need to track is this one: https://github.com/conan-io/conan/issues/6864. Please follow it to keep updated about future progress (it is not planned in the short term, it will take a bit), I am closing this ticket. Thanks!
