### ISSUE TITLE
[question] Override an indirect dependency in conanfile.txt

### ISSUE THREAD

**Issue by ailisp** [conan-io/conan#6999]
I'm trying to learn conan today and my goal is build this example: https://docs.opencv.org/trunk/d8/dfe/classcv_1_1VideoCapture.html

It depends on opencv and gtk3, so I found them online and create this conanfile.txt (I'd like to use scons for godot later, which has official scons support)
```
[requires]
opencv/4.1.1@conan/stable
gtk/3.24.18@bincrafters/stable

[generators]
scons
```
So it gives error:
Incompatible requirements obtained in different evaluations of 'requirements'.
The confliction is gtk requires `libjpeg/9d` but this opencv require `libjpeg/9c`

With help from conan doc I managed to override them with `libjpeg/9d` in conanfile.py:
```python
from conans import ConanFile

class PocoTimerConan(ConanFile):
    requires = (("opencv/4.1.1@conan/stable"),
                ("gtk/3.24.18@bincrafters/stable"))
    generators = "scons"

    def requirements(self):
        self.requires("libjpeg/9d", override=True)
```
And this works. My question is:
1. Is this possible to express override in conanfile?
2. Is it possible to ask conan try automatic resolve confliction (like show a warning and use the latest)
3. Is it possible to use both version of lib (like how cargo did this):
```
[dependencies]
rand = {version = "0.7"}
rand04 = { version = "0.4", package = "rand" }
```

Thank you!
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @ailisp 

You did a good investigation:

> 1. Is this possible to express override in conanfile?

At the moment, an ``override`` can only be expressed in python conanfile.py. But you can simplify the conanfile.py syntax with ``requires = (<ref>, "override"), <ref>, <ref>``, i.e., declaring tuples in the place of a reference, and adding "override". So you wouldn't need the ``requirements()`` method.

> 2. Is it possible to ask conan try automatic resolve confliction (like show a warning and use the latest)

No, we have decided not to go for automatic conflict resolution. The reason is that with C and C++ besides version conflicts there are also configuration conflicts. You can get a "shared" configuration conflict with a "static" configuration of the same library. And binary compatibility and other issues makes preferrable that users are aware of what conflicts are in the graph, and they explicitly decide what to use.

A diferent story is if you have conflicts in packages from ConanCenter. In that case, please report them, and we will try to fix them in the ConanCenter.

> 3. Is it possible to use both version of lib (like how cargo did this):

Not in the general case. There exist the ``private`` dependency, that is extremely discouraged, and should be use only as last resort. In that case, you might be linking different versions of the same static library into different shared libraries, if they completely hide and embed the static library. This could also imply ODR violations, but might work and some users cannot easily get out of this, so it is possible. But this is a situation that should be avoided as much as possible.

**Comment by ailisp** [comment]
Thanks, you answered all my questions and more!

> requires = (<ref>, "override"), <ref>, <ref>

This is good enough to me.

> And binary compatibility and other issues makes preferrable that users are aware of what conflicts are in the graph, and they explicitly decide what to use.

Makes sense, I like transparency control over creates more problem once auto conflict resolution cause runtime unexpected behavior

> A diferent story is if you have conflicts in packages from ConanCenter. In that case, please report them, and we will try to fix them in the ConanCenter.

Will do!

> In that case, you might be linking different versions of the same static library into different shared libraries, if they completely hide and embed the static library. This could also imply ODR violations, but might work and some users cannot easily get out of this, so it is possible. But this is a situation that should be avoided as much as possible.

I see the problems here, great explanation.

**Comment by memsharded** [comment]
Happy to help! 😄
