### ISSUE TITLE
[bug] Base Conanfiles don't affect --build cascade

### ISSUE THREAD

**Issue by cguldner** [conan-io/conan#7020]
It would be ideal if changes in a base conanfile would be considered when you do the `--build cascade` build policy on a package `create`. A base conanfile is an essential part of derived conanfiles, so I think it would be logical that a change in the base would cause a rebuild of derived.

Here is my setup:
* My base conanfile `BaseConan`
* `libA` which inherits `BaseConan`
* `libB` which inherits `BaseConan` and depends on `libA`

If I update `BaseConan` (without changing the `version`) and run `conan export base.py`, where `base.py` is where `BaseConan` is declared, it gets put in the cache successfully. Then if I run `conan create libB.py --build missing --build outdated --build cascade`, then `libA` just gets downloaded from Artifactory, instead of being rebuilt.

Furthermore, if I run `conan create libA.py --build missing --build outdated --build cascade`, then `libA` still just gets downloaded from Artifactory. So it seems the only way to get `libA` to be built in the case of a `BaseConan` update is `conan create libB.py --build libA`.

This is especially important in CI environments, as if someone updated `BaseConan`, then we'd want every package that is derived from it to be rebuilt to ensure the changes work. But we don't want to specify `--build <lib_name>` for every package, as then we are always rebuilding every package and losing one of the major benefits of using Conan.

Not entirely sure if this is a bug or a feature request.

### Environment Details (include every applicable attribute)
* Operating System+version: Ubuntu 14.04
* Conan version: 1.25.1
* Python version: 3.5
* `general.revisions_enabled` is off

**Comment by memsharded** [comment]
The current approach for this would be:

- Make sure to use the new ``python_requires``, that use a class attribute, not a function call
- The new ``python_requires`` when they are modified, they can affect their users ``package_id``
- Define a versioning convention for your python_requires, that define when they require a re-build of the consumers or not. The default ``package_id_mode`` is ``minor_mode``. (https://docs.conan.io/en/latest/extending/python_requires.html#packageid). That means that if you don't want your consumers to be rebuilt you bump the patch version, but if you want your consumers to be rebuilt you bump the minor version.
- With that the normal build strategy will work, no need to do ``--build=cascade``. The ``--build=cascade`` approach might completely be removed in Conan 2.0, because when using revisions and the right ``package_id_mode`` and versioning, things that need to be rebuild are naturally defined.

**Comment by cguldner** [comment]
@memsharded I am using the new `python_requires`, and I'm using `package_revision_mode` for fully deterministic builds. So you're saying in order to get other packages to rebuild, the only solution is to bump the version? Would this problem be solved if I had `general.revisions_enabled` turned on?

**Comment by memsharded** [comment]
If you want to use revisions for python_requires, you need to turn on the ``general.default_python_requires_id_mode=recipe_revision_mode``.

(Note it is a different variable ``default_python_requires_id_mode`` != ``default_package_id_mode``)

With that, every change to a python_require, even if you don't bump the version, will force a rebuild of its users.

We keep the package_id_mode of the python_requires in a separate configuration, to provide flexibility.

**Comment by cguldner** [comment]
@memsharded Does that require `general.revisions_enabled` to be turned on?

**Comment by memsharded** [comment]
> @memsharded Does that require general.revisions_enabled to be turned on?

Yes, otherwise the recipe revision is always "0". all "xxx_revision_mode" for regular packages and python-requires need revisions enabled.
