### ISSUE TITLE
[feature] Passing dependency version info to conanbuildinfo.cmake

### ISSUE THREAD

**Issue by dbenner** [conan-io/conan#7021]
Summarizing what I'd like to be able to do and where I am stuck:

1) Conan installs dependencies, e.g. zlib/1.2.3, boost/1.70.0, etc.
2) Conan puts the above version info into conanbuildinfo.cmake
3) CMake uses the variables passed in from conan to generate a .h file that documents which external dependencies are used in the build so that the application can display it, save the info, etc.

I am stuck at stage 2, i.e. I could not find a way for Conan to create variables documenting the version info of *my dependencies*. This is relevant for additional generators, not just CMake.

As per https://docs.conan.io/en/latest/reference/generators/cmake.html#cmake-generator , Conan will create CONAN_\<PKG-NAME>\_ROOT, CONAN_INCLUDE_DIRS_\<PKG-NAME\> ...

I would like to have a CONAN_\<PKG-NAME\>_VERSION variable added there.
****

**Comment by memsharded** [comment]
Hi @dbenner 

Yes, this feature might make sense. It is a bit inconvenient to add it now, so I'd suggest to improve this while we stabilize all the generators (probably the ``cmake_find_package`` generators too, not only the ``cmake`` one, and other build systems too), for Conan 2.0.

In the meantime, you can access easily the versions of the dependencies and pass them to your build system, something like this:

```python
def build(self):
    cmake = CMake(self)
    for k, v in self.deps_cpp_info.dependencies:
         cmake.definitions["CONAN_%s_VERSION" % k] = v.version
```

That will pass cmake variables in the command line. Please let me know if this helps.

**Comment by dbenner** [comment]
Looks like that should do the trick. Will give it a try.
Thanks @memsharded

**Comment by dbenner** [comment]
Hmmm, partial success.  Works on Linux where I just run `conan build`.

However when developing on Visual Studio (2017), VS calls CMake which uses [cmake-conan](https://github.com/conan-io/cmake-conan), so `build()` never gets called. Here's the Cmake code:

```
if(NOT CONAN_EXPORTED) 
    # when cmake is called by conan (Linux), dependencies are already installed
    # Otherwise (VS), need to run conan to get/build dependencies

	# https://github.com/conan-io/cmake-conan/raw/v0.15/conan.cmake
    include(conan)

    # Make sure to use conanfile.py to define dependencies, to stay consistent
    conan_cmake_run(
		CONANFILE conanfile.py
		PROFILE ${CONAN_PROFILE}
		BUILD missing
    )
endif()

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
```

That's why I wanted to get the version info into `conanbuildinfo`, as I just include that file after calling `conan_cmake_run()`.

**Comment by memsharded** [comment]
> That's why I wanted to get the version info into conanbuildinfo, as I just include that file after calling conan_cmake_run().

Ok, I understand, we will try to add it, but it seems challenging before 2.0, lets see what is possible.

What I would like to know more is why you are following a different flow in Linux and Windows, and why using cmake-conan in Win (even if I am the main contributor to cmake-conan I am not a big fan of it). The cmake-conan works when working as a consumer, but in the ``conan create`` flow, it will always be the ``build()`` method that works (and cmake-conan shouldn't be used at all, it has to be disabled), and it should work the same in all platforms. is it a pure consumer use case?

**Comment by dbenner** [comment]
> What I would like to know more is why you are following a different flow in Linux and Windows

Most development is on Windows/VS, the team has gotten used to doing everything in the studio. As VS only knows how to call CMake out of the box, I was glad to find cmake-conan to bridge the gap to Conan.

I am indeed purely a consumer, not building a Conan package, just consuming others. Not calling `create`, only `install` and `build`. On Linux cmake-conan does not get called.

**Comment by robindegen** [comment]
I too would like to see this feature very much. I'm in the process of converting to conan and we use the version of some packages in the code for backwards compatibility. I now have to add an additional header to do this, but knowing it from Cmake would be even better.

**Comment by memsharded** [comment]
Hi @robindegen 

A lot has changed since then, in the preparation for Conan 2.0:

- We already have developed and released a ``self.dependencies`` model that will allow full access to dependencies information. Not only the version, but even things as the recipe revision and the package id of the dependencies will be fully accessible.
- We have added a ``generate()`` method that is the perfect place to do custom things, like for example, collecting information from dependencies and generating a file that your build system can consume. This will also work perfectly for the local flow.
- Generators are evolving into more modern alternatives as ``CMakeDeps``, ``CMakeToolchain``, etc. that together with the ``generate()`` method provides better configurability (for example to pass arbitrary variables to CMake)

It was not fully clear if you want access to the information, or is about the ``conan.cmake`` cmake-conan integration (then we should follow up in its own repo). If not, I think this issue will be solved once we document ``self.dependencies``, hopefully this next 1.38 release.

**Comment by robindegen** [comment]
@memsharded Thanks for the update. I want to be able to access the version information about packages I use from the generated conanbuildinfo.cmake file. Would that also be possible with these changes?

**Comment by memsharded** [comment]
``conanbuildinfo.cmake`` is the file generated from the ``cmake`` generator, that is becoming legacy, and will be superseded by the ``CMakeToolchain`` + ``CMakeDeps`` generators.

It is very unlikely that ``cmake`` generator will get new features like this one, as the risk of breaking is too high. And in any case, it is likely that features like this one will not even be in the ``CMakeToolchain`` and ``CMakeDeps``, because those provide the "transparent" integration with CMake.

But there are some possibilities, that you could use, even if you want to maintain the ``cmake`` generator at the moment, and with little or no disruption:

- Use the ``generate()`` method and the ``dependencies`` access to create yourself a ``mydepsversions.cmake`` file. This should be doable in around 4-5 lines in your recipe.
- Do the ``include(mydepsversion.cmake)`` in your ``CMakeLists.txt
- If you need this in all your packages, you can put it in a ``python_require`` and reuse it.

Do you think this could be doable in your case?

**Comment by robindegen** [comment]
@memsharded Thank you very much for all the information. From what I think I understand from you it should indeed be doable with these newer CMakeToolchain and CMakeDeps generators. Basically what you are saying is that I can generate additional cmake files with my own information on top of what the default generators do. Is that correct?

I will need to investigate how those work and how to use them, but I think it's worth moving my infrastructure to the future conan design anyway.

**Comment by memsharded** [comment]
> From what I think I understand from you it should indeed be doable with these newer CMakeToolchain and CMakeDeps generators.

Yes, exactly. ``CMakeToolchain`` and ``CMakeDeps`` could add it, but as they aim to implement a transparent CMake integration, it is possible that such a functionality will not be implemented as built-in, but instead something like:

- A new custom block that extends ``CMakeToolchain`` https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#extending-and-customizing-cmaketoolchain
- A new custom generator like ``CMakeDepsInfo`` that would create a file with all the versions information of all dependencies. 

The problem with both is that it is likely that there would be different users wanting different things: some users might also want the revisions, or if those are build or host dependencies. So we will not implement them at the moment, specially when this is relatively easily doable by users (when we document the ``self.dependencies`` access), and wait a bit more to have more feedback and user experiences.

>  Basically what you are saying is that I can generate additional cmake files with my own information on top of what the default generators do. Is that correct?

Yes, this will be quite straightforward once ``self.dependencies`` is documented, it will probably be one of the canonical examples in our docs.

**Comment by robindegen** [comment]
@memsharded Clear thank you

**Comment by memsharded** [comment]
I think we can consider this issue implemented (and close the ticket):

- ``generate()`` method has access to all information of the graph, including versions. Users can explicitly create any kind of file with any format for consumers to use.
- Builtin generators like ``CMakeDeps`` already implement standard mechanisms, like a CMake var ``_VERSION_STRING`` for the package, that contain the specific Conan package version.

Both are already available in latest Conan 1.X, to prepare for a smooth migration to 2.0.
