### ISSUE TITLE
2 versions with one recipe

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#703]
Is it possible to maintain 2 (or more) versions of the same product (conanfile.py is out of the original source) with one recipe. I see that @lasote use 2 seperate branches in gtest, is this the only way?

**Comment by memsharded** [comment]
Sorry, but right now, this is not implemented by conan. The problem is that the package recipes must have a contained, fixed version number, it is not something that can be parameterized. Ideas welcome.

It sounds that you might be interested in templating your package recipe. It is straightforward, just use some ``conanfile.py.in`` or the like,  do a simple replace, format, jinja... Typically conan is orchestrated by some higher level layer, like CI, or project management level scripts. Doing that from CI or a simple python script, as a part of a process seems reasonable.

**Comment by tonka3000** [comment]
oh, templating is a good hint. This would be also great to split some logic into multiple files.

**Comment by memsharded** [comment]
Importing other python files [is also possible](http://docs.conan.io/en/latest/reference/conanfile.html#relative-imports), even inheritance, extending other classes might be possible, just remember to ``exports=otherfile.py``, so those other files are stored in the recipe.

As it seems that no further action is required by conan for this issue, I think this issue can be closed, but please re-open otherwise. Thank you!
