### ISSUE TITLE
[question] How to access deps from `build_requires` with `profile:build`?

### ISSUE THREAD

**Issue by TheQwertiest** [conan-io/conan#7031]
Let's say I have the following recipe that I want to build with `conan create . @ -p:b native -p:h cross`:
```py
from conans import ConanFile, Meson, tools

class Pkg(ConanFile):
    name = 'boost'
    version='1.0'
    exports_sources = ['*']
    build_requires = 'b2/4.2.0'

    def build(self):
        # Fails with KeyError
        app = os.path.join(self.deps_cpp_info['b2'].rootpath, 'bin', 'b2')

    def package(self):
        pass
```
How do I access info about `b2` dependency in such scenario?

Judging by the code, only *host* deps info is saved, but all info about *build* deps is *lost*: https://github.com/conan-io/conan/commit/33652d590a4eb32d0d29d8718c0c624010dae426#diff-763c60e9852172df23dc152b08051e53R503

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Yes, that was intended. If it is needed we might consider a way to implement this behavior, but we really think that it shouldn't be needed, if the package `b2` belongs to a different context, what else do you need besides the environment (likely the runtime)?

What is your scenario? How did you work around it?

Thanks!

**Comment by TheQwertiest** [comment]
@jgsogo , the problem is that deps from `build_requires` are treated VERY differently depending on a presence of  `--profile:build` (which will be illustrated in the example below).
I've first encountered this issue when trying to build `boost` package from conan central. I've had to hack the recipe to make it work with `--profile:build`:
```
def _b2_exe(self):
    # ...
    # A dirty hack to work around inability to get deps info with `profile:host`
    if self._conan_using_build_profile:
        return b2_exe
    else:
        return os.path.join(self.deps_cpp_info["b2"].rootpath, "bin", b2_exe)
```
This example show another problem (which I forgot to open an issue about): there is no proper way to identify if  we have a build profile specified without using non-documented internal conan variables.

**Comment by jgsogo** [comment]
There is a way to get that information based on the existence of the attributes `settings_build` and `settings_target` (https://github.com/conan-io/conan/pull/6769). I agree it is not the best way and maybe we need something explicit if both modes are being used with recipes in Conan Center. The alternative (the future Conan v2.0?) is to use a default autodetected profile for `profile:build` if the user doesn't provide it. Anyway, I would like to think twice if this knowledge is really needed for recipes in general (maybe for cross-compilers)


For a tool like `b2` I would expect its recipe to implement a `package_info` adding the executable to the path:

```
self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))
```

This should work for the old model and for the new one too. The `build()` method of the consumer should contain that value added to the environment.


Please, let us know if it works this way and you think it is a good way to use it. We really want to make this transition as smooth as possible.

PS.- I haven't tried it with the current `b2` recipe in Conan Center, but I will during these days.

Thanks for the feedback

**Comment by TheQwertiest** [comment]
> This should work for the old model and for the new one too. The build() method of the consumer should contain that value added to the environment.
Please, let us know if it works this way and you think it is a good way to use it. We really want to make this transition as smooth as possible.

Does it work the same ways for `.dll` as well? Will all the binaries from packages added through `build-require` be visible in PATH even without build profile?

**Comment by jgsogo** [comment]
Using `profile:build`:
---------------------


As you can see I the sources your linked (https://github.com/conan-io/conan/commit/33652d590a4eb32d0d29d8718c0c624010dae426#diff-763c60e9852172df23dc152b08051e53R510): 


![image](https://user-images.githubusercontent.com/1406456/82678405-d814aa00-9c49-11ea-8395-a9b2c27adeb8.png)

PATH is populated with the directories from `bin`, so shared libraries should be available (and the `DYLD_LIBRARY_PATH` and `LD_LIBRARY_PATH` are populated to). So, yes, it should work out-of-the-box.


Using only one profile:
----------------------

I think it is an issue when using just one profile and shared libraries are not available in the path (need to test it) during the `build()` call. In this scenarios Conan populates the environment only with the `env_info` from the requirements (and build_requirements) and usually shared libraries are not added to the PATH (and they shouldn't).

So, using one profile, this is probably a problem. I think that build_requires out there are working because they are statically linked... but again, I need to give it try, I must be wrong.

**Comment by jgsogo** [comment]
Does this answer your question? Do you think we can close the issue?

Thanks!

**Comment by TheQwertiest** [comment]
Yes, it does, thanks!
"Using only one profile" scenario worries me a bit, but my current workflow does not have have this scenario, so it doesn't matter much for me =)
