### ISSUE TITLE
[question] Reusing cmake for package method implementation

### ISSUE THREAD

**Issue by canatella** [conan-io/conan#7058]
The documentations says (https://docs.conan.io/en/latest/howtos/cmake_install.html):

    Mind that you need to configure CMake both in build() and in package(), since these methods are called independently.

This does not explain why the need to call `CMake` configure method again in the `package` method. I get that the method might be called "independently", but the `package` method will always be called after the `build` method as been executed otherwise there would be nothing to install. So why can't we assume that the cmake build tooling as been generated ? CMake is stateless as far as I know. It is reloading its state from the filesystem each time you run it. I'm asking this because my `CMakeLists.txt` generates some source code which then cause the `package` method to rebuild everything that depends on that source code (nearly every source), so my build time is multiplied by two. 

- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This is a very good question.

Indeed, at least part of the issue is that the ``CMake`` build helper keeps some state, that is defined in the ``configure()`` method.

We should definitely get rid of this. But it is a bit risky to do it with the current helper without breaking, I suggest to design the new ``toolchain()`` one with this in mind. (https://github.com/conan-io/conan/pull/5919)

**Comment by canatella** [comment]
I see that the PR related to this has been closed, is there still something missing for this ? The documentation still recommends the same thing. My codebase has grown since, and I can now feel the pain on my release build taking 2*15 minutes, for building and then rebuilding while packaging...

**Comment by memsharded** [comment]
Hi @canatella 

Yes, this has been fixed in the new integrations. If you do ``conan new hello/0.1 --template=cmake_lib`` in Conan 1.41, or check  https://docs.conan.io/en/latest/creating_packages/getting_started.html, you can see that ``package()`` method can use ``cmake.install()`` without configuration, leveraging both a cleaner implementation and modern cmake (needs CMake 3.15).

Please have a look, and I think this issue could be closed then.

**Comment by canatella** [comment]
Fixed in Conan 2.0
