### ISSUE TITLE
[bug] self.source_folder is empty in deploy()

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7072]
In some cases during deploy we still need to copy some data from source to output_path. For example, a script template which export some environment variables as LD_LIBRARY_PATH containing current absolute lib/ path. However, in deploy() the self.source_folder is set to None. It is preferred to set it to correct value.

### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu 20.04
  * Compiler+version:
  * Conan version: 1.25.2
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
create a conanfile containing:
```
def deploy(self):
    print('self.source_folder=', self.source_folder)

```
then export it and call conan install on it.
### Logs (Executed commands with output) (Include/Attach if Applicable)
```
self.source_folder= None
```

**Comment by memsharded** [comment]
Yes, the ``deploy()`` doesn't have access to the source folder. The source folder might not even exist, it will not exist if there were pre-compiled binaries, only the binary packages are downloaded from the servers.

So at the moment, this is by design, not a bug, you cannot collect/deploy sources from packages, unless those packages explicitly packaged their soruces in their ``package()`` method. We might improve the UX raising a more relevant error message.

**Comment by braindevices** [comment]
ok, make sense
