### ISSUE TITLE
[question] how to return the system requirements path?

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7081]
The `_handle_system_requirements()` seems save returned value from `conanfile.system_requirements()` to `system_reqs/<hash>/system_reqs.txt`. I wonder what is this file are used for. In the document it never mentioned the `system_requirements()` need return value and what kind of value it should return.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by braindevices** [comment]
After digging around, these files seem notify conan which packages are installed and will not be touched later. But it feels wrong, how would conan know if the admin removed those installed system packages at certain point?

**Comment by uilianries** [comment]
Hi @braindevices ! 

>  I wonder what is this file are used for. In the document it never mentioned the system_requirements() need return value and what kind of value it should return.

This kind of method is internal, that's why is not documented. What user should touch is what is under `system_requirements` method, like `SystemPackageTool`

> how would conan know if the admin removed those installed system packages at certain point?

Conan won't verify it. You need to run `SystemPackageTool.installed()` to check it.

Some references: 

https://docs.conan.io/en/latest/reference/conanfile/methods.html#systempackagetool

https://github.com/conan-io/conan-center-index/blob/a504b23f1bd435639e92bd063253ed922577395b/recipes/backward-cpp/all/conanfile.py#L88

**Comment by braindevices** [comment]
But still, the system_requirements() need to return some string, what the string is about?

**Comment by uilianries** [comment]
By default, it returns nothing. The string is a content to system_reqs.txt which is stored by package id, so again, it's empty.

As you are reading the source code, you can check it here: https://github.com/conan-io/conan/blob/174d6d529a455763a1457620e89faeb985521aef/conans/test/integration/system_reqs_test.py#L57

Is there any specific usage for your scenario?

**Comment by memsharded** [comment]
This file was removed in Conan 2, closing this ticket as outdated.
