### ISSUE TITLE
conan graph build-order and ConanInvalidConfiguration

### ISSUE THREAD

**Issue by sboehmann** [conan-io/conan#7086]
> I asked another question in #6112 but then I realized _(many thanks @memsharded)_ that I actually only asked for it because `conan graph build-order` didn't work for me.
 
I tried `conan graph build-order` before and it really sounds like this is the command I want to use. Still I could not figure out how. 

What I was looking for when I began working with Conan was a command to get the total build order of all recipes that need to be rebuilt _(or be built at all because it does not yet exist)_. 

The problem was that I just have a bunch of recipes locally - but nothing more _(i..e clean docker container, no cache or shared data)_. 

But for `conan graph build-order` I need a lockfile, if I understand correctly. So I tried to iterate over all recipes to extract the package name and version using `conan inspect` to create a master `conanfile.txt`. Something like this: 
```
echo "[requires]" > conanfile.txt
for r in $(find . -mindepth 2 -maxdepth 2  -iname conanfile.py); do 
    name=$(echo $(conan inspect -a name $r) | cut -d ':' -f2 | xargs); 
    version=$(echo $(conan inspect -a version $r) | cut -d ':' -f2 | xargs); 
    echo "$name/$version" >> conanfile.txt
done
conan graph lock -u .
conan graph build-order --build=outdated --json build.json .
```
I think `conan graph` really could work for me. But some recipes raise an `ConanInvalidConfiguration`, i.e.:
```
def configure(self):
    if self.settings.os != "Windows":
        raise ConanInvalidConfiguration("%s is only supported on Windows" % self.name)
```

How can I still get a build order _(across all platforms)_?

**Comment by memsharded** [comment]
> The problem was that I just have a bunch of recipes locally - but nothing more (i..e clean docker container, no cache or shared data).

For production, we recommend the ArtifactoryCE, it is free, and it enables not only hosting Conan packages and pre-built binaries, but it also have generic repos (to host any type of file), plus RestAPI, and many other useful things.

> But for conan graph build-order I need a lockfile, if I understand correctly. So I tried to iterate over all recipes to extract the package name and version using conan inspect to create a master conanfile.txt. Something like this:

If you have all your recipes in a common place, you can iterate the folders, I would try a different approach. You need first to ``conan export`` them. That doesn't need any order, just loop over the recipes and ``conan export`` in that folder. Then I would have a base/root ``conanfile.py`` or ``conanfile.txt`` in that same place. I don't think it is worth to automate it, you don't need to list all of your recipes, just your down consumers. It will take very little effort to list your packages in it. 

Then:

```bash
$ conan graph lock .  -pr=myprofile# the place of the base conanfile
$ conan graph build-order .  # it will use the "conan.lock" from previous step
```

the thing is that you don't have a build order for all platforms at the same time. You get a different lockfile and then a different build order for every different platform you support (we recommend using profiles to manage your different platforms). This is because the dependency graph can be, and in fact many times is, different for different platforms (conditional requirements based on options, settings). 

The ``ConanInvalidConfiguration`` will not hit you if you are not trying to instantiate that package for that profile.

Please let me know if this helps. Thanks!

**Comment by sboehmann** [comment]
The current setup is a "proof of concept" and uses the Conan Server. Though we will use Artifactory when we go into production mode _(other teams already use Artifactory for none Conan based projects)_.

> I don't think it is worth to automate it, you don't need to list all of your recipes, just your down consumers. It will take very little effort to list your packages in it.

Here's a little bit of the problem. Our third-party repository has almost the same layout as [conan-center-index](https://github.com/conan-io/conan-center-index). Now there are plenty of recipes, but there is no known downstream consumer. But if someone changes the `freetype` recipe for example, the CI has to rebuild it, as well as all those depending on it.

Btw: How does the Jenkins for conan-center-index figure out what needs to be build?

Now, my current solution is a little weird. I have a yml-file _(that I have to maintain manually)_ that lists all recipes and categorizes them. Something like this:
```
tier1:
  - zlib
  - zstd

tier2:
  - libpng
  - minizip
```
Every recipe in `tierN` only has dependencies to recipes in a previous `tier`. With this, I have a poor man's _build order_ _(`tier0`... `tierN`)_ but can still build some recipes _(all within the same `tier`)_ in parallel. But I also have to wait for `zstd`, although `minizip` would only have to wait for `zlib`. To be clear, this is a temporary hack and of course not a viable solution. ;)

Back to `conan graph build-order`. I understand that I need and likely will get a different build graph for each platform. This is fine, I can call it with different profiles, as you have shown. Still I'm not sure how to create a total build order without a handwritten master `conanfile.py` since I can't know if a recipe `foo` would throw a  `ConanInvalidConfiguration`. I don't think using `conan export` would help me here, right?

**Comment by memsharded** [comment]
> Btw: How does the Jenkins for conan-center-index figure out what needs to be build?

There is an important difference, in conan-center-index, the packages source code *never* changes. When something changes, is typically a change in the recipe, like to add support for Android, or the like. Then, the resulting packages are the same as before, and it is not necessary to actually re-build downstream. Which is completely different than needing to re-build because there are source code changes upstream, which happens in companies own code.

The problem with the top-bottom approach is that it will not scale because the accumulation of versions. Lets say that you have the following:

- App/1.0->LibC/1.0->LibB/1.0->LibA/1.0

This evolves over time, and you do a lot of changes in App and packages LibB and LibC, and you end with:

- App/3.5 -> LibC/4.23 -> LibB/2.12 -> LibA/1.0

Now you do a change on LibA/1.0, and want to trigger the rebuild downstream. It will start to rebuild tens of versions of LibB. Each one will in turn trigger the rebuild of tens of LibC versions downstream, and so on. If the dependency graph is big and dependencies change over time, the complexity is too much.

With the downstream approach, you can define one or more base definitions. For example in the above case we might have a couple of conanfile.txt that define ``App/2.4`` and ``App/3.5`` because they are the latest still supported. Then when LibA changes, the number of different versions to rebuild remain bounded in a natural way, which is the one that gives a higher value/cost ratio.


> Back to conan graph build-order. I understand that I need and likely will get a different build graph for each platform. This is fine, I can call it with different profiles, as you have shown. Still I'm not sure how to create a total build order without a handwritten master conanfile.py 

Yes, that is true. A "master" ``conanfile.py is still necessary for the ``conan graph build-order``

Also, with ConanCenter, there is not known downstream consumption pattern. Don't you have any pattern there? If you are maintaining this repository of dependencies is because they are consumed to build some products. Couldn't you use that information of those products for the CI, and help defining those "master" ``conanfile.py``?

**Comment by sboehmann** [comment]
Ah, I guess I wasn't clear. In fact, I'm looking for a solution for external third-party packages we use, so really comparable to conan-center-index. I.e I also try to build a lot of external third party libraries here. Therefore the source code does not change here either.

For our own code, your're absolute right. A top-bottom will not scale. But for external third-party libraries, I first want to update e.g. Qt from 5.14.x to 5.15.0 and want to build everything needed, before switching the dependency of our applications and own libraries.

**Comment by memsharded** [comment]
I see. Cool, lets invoke @jgsogo and @danimtb which are building some CI in conan-center-index right now to tackle a similar problem.

**Comment by jgsogo** [comment]
Hi! As any package manager, Conan builds the graph from the application to the dependencies, a package declares its requirements, doing it the other way around would be impossible. Thus, building the inverse dependency graph is challenging, and it is even more challenging in our use-case because the graph is different depending on the profile. 

IMO there are two scenarios:
 * In ConanCenter, what we do is to take advantage of Artifactory properties and store the _inverse  dependencies_ for each package. 

   For example, when we build `boost` we know it requires `zlib` and `bzip2` (we read the JSON output from the `create` command) and we store a property associated to `zlib` that says it is consumed by `boost` and do the same for `bzip2`. We do this for all the profiles we are building in ConanCenter (~130) so we really know which references are consuming each one of our references.

   Once you have all these properties, building the _inverse dependency graph_ is straightforward, you don't need Conan at all, you just need to read the properties. When a library changes, it is easy to rebuild just the consumers.

   In our case, we aggregate the dependencies for all the profiles, we don't know if the property is coming from a Windows, Linux or Mac profile, if we decide to build the consumers of a library, we'd build the ~130 profiles even if for some of them it wasn't a requirement. Something we could optimize but it would make things more complex.

   This is one approach: **build the dependency graph step by step and store it somewhere else** (an external database, a file, properties in Artifactory,...).

 * A completely different challenge is to **build it from scratch**, you just have a bunch of Conan recipes and you want to build the graph of dependencies to compute the build-order and... well, build them in order.

   Something that would work really well is to create a `conanfile.txt` with all the references and ask Conan to compute the graph... but you will always get a `ConanInvalidConfiguration` for every profile you run, eventually you will have recipes blocking all the profiles. So this won't work.

   The only approach I can figure out is to create this graph as ConanCenter is doing (no need to build binaries): recipe by recipe and profile by profile, gathering the information of the dependencies and storing it somewhere. This is the approach I'm following to build this graph from ConanCenter http://jgsogo.es/conan-center-index-graph/index.html Once again, if you have a directed acyclic graph it is easy to traverse it in one direction or the other, so what we know as build-order is easy to compute.

   Source code for that graph is available here (https://github.com/jgsogo/conan-center-index-graph), it is a personal project, not production code, but you can get some ideas from it. It is running daily using a Github Action, and it takes 2 minutes to compute all the graph. This is how it works:

    1. Export all the recipes to the cache (each and every version)
    2. Get all the profiles: in that project I'm using only one profile for each of the major OSs: one profile for Windows, another for Linux and another one for MacOS.
    3. Compute the packages to build: this is the most tricky part. 
       + I get the options for each and compute all the combinations taking into account some optimizations: I don't take into account options that [usually] doesn't affect to the graph: `fPIC`, `shared`,... options with names like `with_` or `enable_` are always `True`, the other way around for options starting with `disable_`, `without_`,...
       + All those options combinations are combined with the 3 profiles I already have (Windows, Linux, Mac)
    4. Yes, now for each recipe-version I have lots of profiles to run... and Conan doesn't support well parallelism/concurrency, so I'm using `--threads 1`. 😞 
    5. Now I run `conan graph lock` for each recipe-version for each profile for each of the options combinations. From the lockfile I get the `requires`, `build_requires` and `python_requires`. If I get a `ConanInvalidConfiguration` (exit code 6) then it is not an error, it is just this profile is not supported.
    6. With all that information I build the graph. Use your own representation or your preferred graph library.
    7. Use a visitor to draw the graph, compute the build order... or trigger builds in your CI...

   There are some optimizations that can be done, for example: if you already know the profiles you will be using, you can use all of them instead of computing the combinations (no need to inspect the options).

I hope this is somehow inspiring and help you to solve your problem. I know this is not an answer, but I really feel like there is not an answer that will work for all the users. If you find my side-project useful and want to ask questions about it, do it here or open issues there (or talk to me in Slack).

And let us know about your progress!

**Comment by sboehmann** [comment]
@memsharded and @jgsogo: Thanks a lot! I'm very impressed and grateful for all the help you have given me.

To be honest, I guess I need some time now to familiarize myself with all the information and inspiration. But I'll get back to you to share my solution - or more likely - with more questions. ;)

Thanks again to both of you!
