### ISSUE TITLE
[question] deploy() is not called when put in requires

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7088]
I have a package A defined a `deploy()` method. if I do following, the `deploy()` method is called.
```
conan install A/1.0@test/test -if <deploy location>
```
However, if I put the A in a conanfile.txt:
```
[requires]
A/1.0@test/test
```
the `deploy()` is only called at the first time I run the following command. After that, even I deleted the deployed files, the `deploy()` is never called unless I do `conan remove`
```
conan install .  -if <deploy location>
```
Is this expected behaviour? How can I make make sure the `deploy()` get called in this case?

`-g deploy` does not work for me, since it install each package to a their own subdirectory.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
> the deploy() is only called at the first time I run the following command. After that, even I deleted the deployed files, the deploy() is never called unless I do conan remove

Yes, this is by design. ``deploy()`` is only called when you ``conan install <reference>`` not when it is a transitive dependency, or a dependency of a conanfile.txt. It is very annoying to have things copied to your local folder, just because some transitive dependency declared an imports() or deploy() method.

> conan install .  -if <deploy location>

Are you sure this installs anything with deploy()? I don't think so. Please check again, it is possible that you had the files from the previous run. That shouldn't be calling the ``deploy()`` method.

> Is this expected behaviour? How can I make make sure the deploy() get called in this case?

Yes, you can't. ``deploy()`` will not be called for transitive dependencies.

If ``-g deploy`` is not what you want, you can run some script later that will arrange things in the way you want, or you might want to write your own custom generator, based on the deploy one.

**Comment by braindevices** [comment]
@memsharded Thanks!
