### ISSUE TITLE
[bug] Imported dependency licenses disappears from build folder

### ISSUE THREAD

**Issue by spoorendonk** [conan-io/conan#7096]
#6429 # Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: gcc 9.3.0
  * Conan version: 1.25.2
  * Python version: 3.8.2

### Steps to reproduce (Include if Applicable)
- Make a new package
- Require a package
- Import license for dependeny as in [docs](https://docs.conan.io/en/latest/howtos/collect_licenses.html?highlight=license)
```python
    def imports(self):
        self.copy("license*", dst="licenses", folder=True, ignore_case=True)
```
- Package dependency license
```python
    def package(self):
        self.copy("*", dst="licenses", src="licenses", ignore_case=True)
```
- Create package
- No license is packaged. `licenses/depency/licenses/` folder appears empty after `build()` and before `package()` is called?

**Comment by memsharded** [comment]
Hi @spoorendonk 

Files imported during building are automatically removed by design. If you want to keep them, you need to use ``keep_imports=True``. Please have a look to: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#keep-imports (it is probable that we will change this in Conan 2.0 and do not import automatically, but those who want to repackage artifacts from dependencies, will need to do it explicitly in the ``build()`` or ``package()`` steps.

**Comment by spoorendonk** [comment]
Nice. Missed that one. Thanks a lot
