### ISSUE TITLE
[feature] AWS S3 remote

### ISSUE THREAD

**Issue by kshpytsya** [conan-io/conan#7115]
In our team, we have previously successfully used Conan with a self-hosted remote running on a dedicated AWS EC2 instance. The problem is that at our scale (we currently use Conan for a couple of our stable proprietary libraries which get a new release at most once a month or so), having a dedicated server running Conan is an unjustifiable expense, esp. considering the fact that running Conan on the least expensive EC2 instance type often had some glitchy behavior even under our minor loads. In our case, ability to store Conan packages in an S3 bucket would make perfect sense. Had the remote REST API been documented and treated as public, it would be possible for me to just create a wrapper script implementing remote server storing the packages in s3, updating Conan's remotes config to point to this temporary server, and launching the build process which uses Conan. Alas, it is not public yet(?). My brief glance at Conan client code makes me believe there is no provision for plugable remotes. And it doesn't seem that hooks mechanism would allow to achieve this either.
So, this is a request for any practical way of achieving my goal. I am willing to implement this myself and submit it as PR provided some architectural guidance as to an acceptable integration point in Conan client code.

**Comment by jgsogo** [comment]
Hi, @kshpytsya 

Is it an option to use Artifactory? It is not only that it works, but it is the recommended server to use with Conan, the integration is up-to-date. There is a [free Artifactory CE for C/C++](https://conan.io/downloads.html), it fully supports Conan repositories, you can use it as long as you want without limitations. If it fits your needs, [other licenses include support for AWS S3 storage](https://www.jfrog.com/confluence/display/JFROG/S3+Object+Storage) out-of-the-box.

The alternative would be to create another server application that uses S3 behind the scenes, it is not something that can be implemented in the client, there are some operations that need to be run in the server.

**Comment by kshpytsya** [comment]
No, Artifactory is not an option. This request is about a way of having a private "remote" (repository) which doesn't require any server but only some object storage such as an S3, which is much cheaper both in initial setup and in maintanance.
Please clarify what kind of functionality is impossible to implement on the Conan client side. From [this](https://github.com/conan-io/conan/issues/1961) I understand that synchronization isn't really an issue, and even if it were, it would be possible to use AWS DynamoDB for locking (e.g. using [this](https://pypi.org/project/python-dynamodb-lock/) library).

**Comment by jgsogo** [comment]
There are no so many operations that are required for a Conan server, at least some search functionality and recipe revisions resolution, (and authentication). Besides that, everything is about putting and retrieving files to/from the storage.

**Comment by kshpytsya** [comment]
Any reason why those operations cannot run on client side? Authentication and access control is handled perfectly with S3.

**Comment by jgsogo** [comment]
A client could have the whole server indexed, and poll every remote continuously to keep its index synced... but it is much better and simpler to have that functionality implemented in the server.

**Comment by kshpytsya** [comment]
It is hard for me to ague, considering the client-server API being non-public and undocumented (correct me if I am wrong).
So, what is the conclusion on the issue? Is it completely out of scope of Conan project?
BTW, what do you mean by "poll every remote continuously"? Client, as opposed to server, is not running continuously, but rather when invoked via CLI. Had I implemented something like this from scratch (something that would provide functionality similar to that of Conan but with object storage backend instead of own server), I would have just devised object names (think of them as of file names) in a matter that would make search operations efficient.

**Comment by jgsogo** [comment]
Yes, the API client-server is not documented, but it is not hard to find it in the sources, and endpoints are quite straightforward. 
Right now, implementing a different backed for the conan-server or changing the way the conan client works in this regard is out-of-scope.

By polling continuously, I mean: with every command that now hits any remote, the client should reindex the packages there (new packages, new revisions,...) and it can take a lot of time. Conan packages number grows very quickly, i.e. right now Conan Center has several thousands.

**Comment by kshpytsya** [comment]
I am not suggesting replacement of Conan Center with s3 storage. It is my understanding that client can be configured with multiple remotes. My idea is that those remotes could be of different kinds: the current client-server protocol, and, additionally, s3 (or better yet, arbitrary remote backend, implemented as a plugin). s3 would make sense in cases where the number of packages stored in that repository is relatively small. Plus, I believe that not all client operations require knowledge of entire list of available packages, so most of the operations would be fairly efficient even with moderate number of packages stored on s3.

**Comment by jgsogo** [comment]
Of course the server can delegate the storage of the packages to any service: conan-server uses local filesystem, Artifactory can use almost any storage out there... and the client can connect to many of them and different types of remotes, the client doesn't need to know where the artifacts are stored. This is one of the reasons why clients and servers are different applications and use an HTTP API to interchange information.

We are not going to move the logic that is implemented in the server to the client. AWS S3 storage could be a request for a Conan server, but it is not something related to the Conan client. There are different Conan servers that provide facilities to store the artifacts in different servers, from our perspective the demand is covered enough and we need to prioritize features related to package management itself.

**Comment by kshpytsya** [comment]
I see your point. From a practical standpoint I would accept having a wrapper around Conan client (or entire build process) containing a Conan-compatible server (written by me) storing packages in S3. From architectural standpoint this would be IMHO an ugly kludge and subpar to a solution in which the client would have a plugable remote interface, HTTP REST API being the default implementation.
The problem, however is that since REST API is undocumented and, according to the fact that [this](https://github.com/conan-io/docs/issues/44) issue is closed, is intended to be kept that way, no one can reasonably rely on it being stable. This potentially makes any attempt at implementing an alternative compatible server an unwise moving target shooting exercise. Not to say that absence of official documentation means that developers of such servers cannot expect to be able to file any bugs regarding the client-server interaction.

**Comment by jgsogo** [comment]
I totally understand your concerns about breaking changes in the HTTP API, I can only say that changing the client is more or less fast (small team, only affecting Conan), but changing the implementation on the remote side will take much more time and efforts, especially if the remote is a general application and Conan is just a package type. If you search the internet you will find other servers that are already working with Conan.

**Comment by memsharded** [comment]
> The problem, however is that since REST API is undocumented and, according to the fact that this issue is closed, is intended to be kept that way, no one can reasonably rely on it being stable. 

Not only Artifactory CE and PRO edition depends on the stability of this API, but also users of conan_server and also other third party implementors (at least 2 other up to our knowledge) of the Conan package type out there. That means dozens of thousands of servers out there that will break if the API is changed. It might not be documented (but very straightforward to deduce, both in the client side and the conan_server side) but it is definitely stable. The HTTP API is versioned v1 and v2 at the moment, and if any change is necessary, it will learn a v3.

**Comment by kshpytsya** [comment]
I have implemented a proof of concept S3 remote. I have followed your advice of "deducing" the API. I have done it mostly with the help of [Wireshark](https://www.wireshark.org/) analyzing interactions of Conan client and `conan_server` and some reading of code. I would highly appreciate a glance review of at least [the routing map](https://github.com/kshpytsya/conan-client-remote-s3/blob/ff5e637b80870edf59aeb5c0fdc83841c7598433/src/conan_client_remote_s3/__init__.py#L152-L171) to make sure that I have not missed any critical functionality. Note that search is not yet implemented.

**Comment by jgsogo** [comment]
I think it should be enough for a basic server (just storage). You are missing a `delete` endpoint and, besides the `search`, surely it will be useful to have some kind of authentication/token mechanism to avoid anyone modifying files in the server.

**Comment by kshpytsya** [comment]
@jgsogo thank you for your review. I will implement `search` and `delete`. As for authentication, it is irrelevant here, as access control is handled by means provided by AWS. You may have missed the fact that the remote "server" I have implemented is actually executed in the same process as Conan client itself, therefore making it impossible to implement any custom access control other than in some "security through obscurity" fashion. Instead, the user of Conan client configured to access this s3 remote needs to possess an AWS access token which would allow read or read/write access to entire s3 bucket or to some subset thereof. Such tokens are provided to AWS SDK (boto3 in case of Python) via environment variables.

**Comment by takacsd** [comment]
I know I'm late to the party, but I have a very similar usecase. And I'm very much intend to give `conan-client-remote-s3` a try, but I was wandering, if the already existing `conan_server` fits the bill better.
To me it seems like it just needs a S3Adapter based on [ServerDiskAdapter](https://github.com/conan-io/conan/blob/0ad4f309f0a7fa2b1ca8e5fd22ce093bc66f2894/conans/server/store/disk_adapter.py#L10), which seems easy enough.
Did I miss something?
Is this something which has a chance of upstreaming?

**Comment by AlexRamallo** [comment]
I still don't see a good reason why the API is undocumented, especially if it is relatively stable? The Conan website already documents a bunch of client features [marked as "experimental"](https://docs.conan.io/en/latest/search.html?q=experimental), so I don't see why a similar warning couldn't be attached to the REST API, especially since it's not that complicated.

If there's a concern about someone building a product that competes with Artifactory (at least on the Conan side), anyone actually interested in doing that wouldn't mind going through the effort of reading the source or using Wireshark. Gitlab already has [an early implementation](https://docs.gitlab.com/ee/user/packages/conan_repository/) available, for example. But for everyone else, it's just an unnecessary hurdle/waste of time.

Aside: @kshpytsya's idea is awesome. Moving server logic into the client and treating remotes as dumb storage would vastly simplify some deployments.

**Comment by memsharded** [comment]
I think it is being severely underestimated:

- The efforts to document an api, even if marked as experimental. You know those issues marked as "experimental"? We still get a lot of support tickets, and user complaints when something break in those features, that require time to reproduce, debug and respond. And discrepancies from docs and real implementation also happens, and then the problem is also difficult to solve. We have had way more requests (like 50x times more) to document the client (the cli-tool) Python API, and we haven't managed to document it yet. We are planning to do so for Conan 2.0, but this is a major effort that has been running for more than 1 year, and will still take a few more months. We are happy that other servers are implementing Conan package support, not only Gitlab, also Nexus, Cloudsmith have implemented support, and we gladly have responded whatever questions were made about the api.
- The effort to move the server and storage logic to the client side. How many other package managers, for other languages and tools (pip, maven, cargo, npm, composer, docker...) implement direct upload and download of packages from S3, without server side? We managed to release Conan revisions a couple of years ago, thanks to the abstraction provided by servers, so servers managed to start storing multiple revisions. Two years later, we haven't managed to implement a multi-revision Conan client storage, and this will only become possible in the next major 2.0 version. Decoupling things via client-server architectures is not a random decision, it is really necessary to scale and maintain complexity bounded. As commented above, we have been working for more than 1 year now to prepare Conan 2.0, with very critical features, with massive demand, and released 2.0 GA and migrating will easily take another year. The complexity of trying to approach this functionality would certainly have a huge negative effect on the project.

So I am sorry, but it will not be possible to address this feature request, so I am closing this issue. Thanks very much for the feedback.
