### ISSUE TITLE
 [suggestion] Lowercase the search terms

### ISSUE THREAD

**Issue by JosuGZ** [conan-io/conan#7163]
I think search should lowercase the terms, it is probably easy to implement and it would improve the results:

![image](https://user-images.githubusercontent.com/25986871/84077971-658d2380-a9d8-11ea-9dd1-537d37717fa5.png)

**Comment by uilianries** [comment]
Hi @JosuGZ! I'm understand your suggestion, but we can't simple change it because it would break many users as `foobar` and `FooBar` are different packages.

For the current and future packages in Conan Center Index, I can sure you we only will have lowercase names: https://github.com/conan-io/conan-center-index/wiki#the-recipe-folder

We have more issues related to your idea:

- https://github.com/conan-io/conan/issues/6218
- https://github.com/conan-io/conan/issues/1557#issuecomment-389170899

**Comment by JosuGZ** [comment]
I understand. Although my sugestion was only about the search term, so the change should only add more results, it would be possible to differenciate them on the listing, where they would appear with the correct casing.

Fore example, it could show `openssl` and `OpenSSL` on the search results with no problems. But maybe it might break a script that searchs and downloads the last stable version that it finds I guess.

**Comment by uilianries** [comment]
@JosuGZ There are few problems, first the case sensitive depends on the OS, on Windows your first line would work for local cache. For example, when searching for openssl, you see 2 different names, and they are different packages indeed, but when installing, the case sensitive or may not be taken into account according the OS. To solve it, `search` offers the option `--case-sensitive`, which avoids non-cased search on Windows.

> so the change should only add more results, it would be possible to differenciate them on the listing, where they would appear with the correct casing.

As mentioned before, they are different packages, so it seems be wrong, now imagine you are looking for openssl, and you see *OpenSSL* and *openssl* in the results, but you install *OpenSSL* instead, and now you are using the wrong package. Believe, this situation happens.

If you are not sure about the correct name, go with lowercase for sure.

**Comment by memsharded** [comment]
Conan 2.0 is always lowercase, closing as outdated
