### ISSUE TITLE
[bug] conan remove -s does not remove export_source folder

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#7197]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: n/a
  * Conan version: 1.26.0
  * Python version: 3.8.2

### Steps to reproduce (Include if Applicable)

I wanted to remove temporary build and source folders from my local conan cache after building a package with ``conan remove -b -s package_reference``. However, I used ``exports_sources`` to use the source code next to my conanfile. 

Bug: The _export_source_ folder is not removed by the ``conan remove -s`` command and there also does not seem to be any flag to remove it.

**Comment by memsharded** [comment]
Hi @fschoenm 

This is not a bug, this is expected and by design:

- The removal of ``conan remove -s`` applies to any "redundant" source code in the cache that can be reproduced later. It means, something that is retrieved from the ``source()`` method, or as a result of the ``scm`` component.
- The ``exports_sources`` contain code that comes from exporting the recipe. It is a copy of the code that exists in user space. There is no way to obtain again this source code if deleted, as it would require exporting again the recipe. Then, it is not possible to remove it without breaking the recipe.

I hope this clarifies a bit the behavior, please let me know.

**Comment by memsharded** [comment]
Hi @fschoenm 

It hope the explanation was clear, so I think this issue can be closed. Please let me know otherwise, or if you have any further question. Thanks!
