### ISSUE TITLE
[bug] conan cannot find required package when channel is not specified

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7211]
When we specify like following:
```
self.requires('jsonformoderncpp/3.7.3')
```
We would expect it find any possible match in any channels. For this package we have:
```
Existing package recipes:

Remote 'conan-center':
jsonformoderncpp/2.1.1@vthiery/stable
jsonformoderncpp/3.0.0@vthiery/stable
jsonformoderncpp/3.0.1@vthiery/stable
jsonformoderncpp/3.1.0@vthiery/stable
jsonformoderncpp/3.1.1@vthiery/stable
jsonformoderncpp/3.1.2@vthiery/stable
jsonformoderncpp/3.2.0@vthiery/stable
jsonformoderncpp/3.3.0@vthiery/stable
jsonformoderncpp/3.4.0@vthiery/stable
jsonformoderncpp/3.5.0@vthiery/stable
jsonformoderncpp/3.6.0@vthiery/stable
jsonformoderncpp/3.6.1@vthiery/stable
jsonformoderncpp/3.7.0
jsonformoderncpp/3.7.0@vthiery/stable
jsonformoderncpp/3.7.1@vthiery/stable
jsonformoderncpp/3.7.2@vthiery/stable
jsonformoderncpp/3.7.3@vthiery/stable
```
Thus it should actually find last one. However, in conan 1.26 it cannot find it.
I have to specify the channel:
```
self.requires('jsonformoderncpp/3.7.3@vthiery/stable')
```
The `jsonformoderncpp/3.7.3` has same behaviour of `jsonformoderncpp/3.7.3@` which is unexpected.

### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu 20.04
  * Compiler+version: N/A
  * Conan version: 1.26.0
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
- create an example project, put following in requirements
```
self.requires('jsonformoderncpp/3.7.3')
```
- then conan export .
- then conan install
### Logs (Executed commands with output) (Include/Attach if Applicable)
```
ERROR: Failed requirement 'jsonformoderncpp/3.7.3' from 'Hello/0.1'
ERROR: Unable to find 'jsonformoderncpp/3.7.3' in remotes
```

**Comment by jgsogo** [comment]
Hi! From the POV of Conan, **packages with and without `user/channel` are completely different references, unrelated packages** (although they will conflict in the graph if both are present because the key for the graph is just the `name`).

We encourage to use packages without `user/channel` when available as they are coming from the curated ConanCenter repository (https://github.com/conan-io/conan-center-index). If authors themselves are providing their own version in a personal repository the recommendation is to add `@<author>/<channel>` to those packages (like it is done here) and the consumer should choose between one or the other reference explicitly.

Commands and functions taking a reference will work the same with `jsonformoderncpp/3.7.3` and  `jsonformoderncpp/3.7.3@` (prefer the former one as the latest shouldn't be valid in Conan 2.0), commands that accept a pattern or a reference need to use the trailing `@` to disambiguate and indicate it is a concrete reference (like `conan search`). This ambiguity should be removed in the new command-line interface we are already working on.

**Comment by braindevices** [comment]
@jgsogo thanks. This make sense.
