### ISSUE TITLE
[question] package compatibility with different package_id_mode

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7220]
So, I am reading the doc page at https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#compatible-packages
where it says: 
`For example, if you are generating binary packages with the default recipe_revision_mode, but you want these packages to be consumed from a client with a different mode activated, you can create a compatible package transforming the mode to recipe_revision_mode so the package generated with the recipe_revision_mode can be resolved if no package for the default mode is found:`

I am not clear on this, say if I  built pkgA with recipe_revision_mode, and i pushed to artifactory, and some one wants to use my pkgA, he has to have recipe_revision_mode to use pkgA?
if not, he has to rebuild the package on his machine so that he can use it, right?

I just dont understand how this works, say if he is building pkgB, that requires pkgA, how pkgB knows pkgA used a different package_id_mode?

Also regarding adding to compatible_packages below
```
    def package_id(self):
        p = self.info.clone()
        p.requires.recipe_revision_mode()
        self.compatible_packages.append(p)
```
for the case i mentioned above, should this be in pkgA's recipe or pkgB's recipe?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by shelper** [comment]
Also one related question: Do I have to set `general.revisions_enabled=1` to make `recipe_revision_mode` and `package_revision_mode` valid as `default_package_id_mode`? if so, why we need a separate switch `revisions_enabled` ?

**Comment by jgsogo** [comment]
Hi, @shelper 

There are two different things in your comments:
 * `revisions`: regarding your issue, the main difference about using revisions or not is how packages are stored in the server (explore the Artifactory repository). **Without revisions, all recipes/packages are associated to a `0` revision**, they are stored in the server in a single folder, and packages will the same package-id will override existing one (and only the last revision of the recipe will be available). When a client uses revision, it will find this revision `0` in the server, but it will compute a different revision when uploading it to the server (it actually uses revisions).

   Mixing clients using different configurations regarding revisions is possible (in Conan Center we store revisions, and clients without revisions are using existing packages), but it can be confusing.

 * `package_id`, `compatible_packages`, `package_id_modes`: here the important bit is to understand how Conan computes the packageID (recommended reading here: https://blog.conan.io/2019/09/27/package-id-modes.html). Conan basically computes the hash of options, settings and requirements (the package_id_mode is the mechanism to choose which part of the requirements to take into account: full reference, only the name, the name and the `major` from the version, all the reference together with the revisions,....). As you can imagine, different values of the `package_id_mode` will result in different `package_id`.

   Can a client with a `package_id_mode` consume packages created with a different `package_id_mode`? Yes, totally, as long as the computed `package_id` is the same. Each client will compute the package ID taking into account its configuration and the information from the recipe (this is the reason why we need to retrieve the recipes and build the graph with almost every command). Will the hash function compute the same `package_id` for different inputs (because of different configurations)? Very unlikely, we haven't found a hash-collision so far.

   `compatible_packages`: it is a mechanism to associate other `package_id`s to the same binary. It is not the binary, the package, that is stored with different package_ids. No. What happens is that the client (remember we retrieve the conanfiles, build the graph and run `package_id()` function all the time) gets a list of `package_id`s from the function `package_id()` and it can look in the server for different packages.

Please, let me know if this is clear enough. If not, ask, and if you have suggestion for the docs, please, they are more than welcome.

Thanks!

**Comment by shelper** [comment]
@jgsogo Thanks, that is clear. 
So if i understand correctly, the package_id will be different even if the only thing changed is the compiler.version. as that is part of the settings, which is used in hashing out the package id. Basically if a local calculated package_id is different from the one hosted on server, then, the package needs to be rebuilt locally. 

Say i have a package built with gcc 9 on the Artifactory server, and on my computer, i have gcc 8 configured in my profile. In such case, I cannot directly use the compiled package from the server because when i download the recipe for that package i will calculate a different package_id with my local settings.

In order to let people share the binary been built using different but ABI compatible gcc versions, all developers have to remove compiler.version from the equation of package_id generation. And the way to do that is to remove gcc version section from conan's settings.yml, and remove the compiler.version from the profile file, right?

**Comment by jgsogo** [comment]
Yes to all.

In order to reuse packages generated with a different ABI compatible GCC version you can remove `compiler.version` from your settings and Conan will compute the same package-id (or you can remove `compiler.version` inside the recipe, which affect that very single recipe ([example removing settings in recipe](https://github.com/conan-io/conan-center-index/blob/ad3f626bfdd2ce250a95846907908fd266240585/recipes/nng/all/conanfile.py#L38))). 

The only problem if you do it that way (removing settings) is that you are losing information, once the package is built, you cannot know if the package was generated with GCC 8 or GCC9. That's the reason why we added the `compatible_packages` feature. With this feature you don't remove `compiler.version`, each GCC version will generate a different package-ID, but you are telling Conan that for a given configuration (the input profile) it can use different package-IDs (first, the one matching the settings, and then the ones added as _compatible packages_). 

I usually prefer the second approach, not losing information, but every use-case is different and it might not be the best approach for your needs.

**Comment by shelper** [comment]
Thanks for the answers, that is clear and complete, i am closing this issue

**Comment by shelper** [comment]
Just have more question regarding the document on conan revision. In the documentation page: https://docs.conan.io/en/latest/versioning/revisions.html it says:

> How to activate the revisions
> You have to explicitly activate the feature by:
> 
> - Adding revisions_enabled=1 in the [general] section of your conan.conf file.
> - Setting the CONAN_REVISIONS_ENABLED=1 environment variable.

Do i have to do both config above or either of them will activate the revision mode?
Meanwhile, i am still not clear regarding revision on the server side.
In the documentation it only says that: 

> In the server
> By using a new folder layout and protocol it is able to store multiple revisions, both for recipes and binary packages.

Do i need to config server to enable revision?  and how the server handles variation of revision mode from client side?
1. If the server has a client with revision mode enabled, and another that disables revision mode, then how will the server handle this?
2. Client changed revision mode from disable to enable or vice versa, and upload previously uploaded package again, then how will the server handle this?

 I tried to up my conan package hosting on artifactory, i have my `revision_enabled` on and i tried to push packages to artifactory but i don't see the expected structure of subfolders for PREV and RREV:

![conan](https://user-images.githubusercontent.com/546163/85891662-7b169180-b7bd-11ea-9ae8-0b956c5a7b2d.png)

**Comment by jgsogo** [comment]
Hi! 

In the client, to activate revisions you can use config variable `general.revisions_enabled=1` or environment `CONAN_REVISIONS_ENABLED=1` (configuration one is preferred). I'm adding that extra bit of info here https://github.com/conan-io/docs/pull/1750.

You don't need to modify anything in the server... if it is new enough to support revisions. What Artifactory version are you using?

Using a server with clients that have revisions activated and other clients without them activated is not a problem from the server point of view (it is the client the one that computes the revision and uploads the packages to the proper _URL/directory_), but it will make it harder for the clients to share binaries because the will be assigned/uploaded to the explicit revision (those that are uploaded from the client with revisions activated) or to the general `0` revision (clients without revisions).

**Comment by shelper** [comment]
found out that i need artifactory > 6.9 to support revision and i have 6.3.2...
please let me know if there is any way to support that with this older version.. Otherwise, feel free to close this issue, thanks!

**Comment by wuziq** [comment]
Sorry, I'm still not clear from the thread.

If I have a package, packageA, that was built with `semver_direct_mode` using `conan export-pkg` long ago, but now consumers are using `recipe_revision_mode`, how can the consumers still use the same package?  Is it even possible?  I am using Conan 1.62.

Does packageA's original recipe need to be changed?  If so, would it require the need to ignore the minor and patch versions of packageA's requirements (among other things)?  If so, how does one do that?
