### ISSUE TITLE
[question] Conan doesn't pull automatically after a recipe revision change.

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#7235]
Hi Guys, 
I have a project where I specify all my dependencies with a `conanfile` and I run `conan install` using `conan_cmake_run`.
 Lets say I have a dependency that looks like this:
```
 self.requires("gtest/1.10.0@user/channel#RREV1")
```
Then, I update my recipe,  build it and update my recipe revision:
```
 self.requires("gtest/1.10.0@user/channel#RREV2")
```
When I try to build my project, I would expect conan to pull the new binaries from my conan server but instead it complains like this:
```
ERROR: Failed requirement 'gtest/1.10.0@user/channel' from 'conanfile.py (Project/1.0.0)'
ERROR: The recipe in the local cache doesn't match the specified revision. Use '--update' to check in the remote.
```
Is this the expected behavior? I know that I can add `UPDATE` to `conan_cmake_run` but it seems rather odd having to do that. I would expect conan to automatically pull a new binary after I change the RREV, just like it does when you change the version of the dependency.
The reason why I don't want to add the UPDATE parameter is because then it updates every package it can and sometimes I don't want that.
It may seem unrelated to this question but, can package revisions be deactivated? We use the recipe revisions but we have no use for the package revisions, and sometimes when we run Jenkins builds of our set of recipes it generates a lot of new packages, which is kind of annoying. And if I have `UPDATE` set, my next build is going to be really slow because it will pull a lot of new packages.

Thanks!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
I see it is the same issue as this one: https://github.com/conan-io/conan/issues/4712 (you commented there too). IMO, if conan retrieves the package when the reference is not in the cache, Conan should retrieve the package when the revision is explicit and it is not in the cache.

At this moment, package-revisions cannot be deactivated (when revisions are enabled). We really think that traceability is important, if the binary is different (the package revision is just a checksum of the files) Conan will store it as a different package revision (maybe the difference is due to some environment variable or config in the Jenkins job and it is important to know which one generated exactly each binary). Package revisions shouldn't slow down other jobs, because binaries will be downloaded only if the recipe revision changes.

Probably your request is a side-effect of the UPDATE which in turn is the workaround for the real issue. Let's fix the root cause.

**Comment by ericriff** [comment]
Let me see if I understand you correctly. What you're saying is that in the case where the RREV is explicit (and it changes) conan shouldn't need the `update` flag to retrieve a new package?  Just like it does when you change the dependency version?

I'm saying that having the `UPDATE` flag slows down our pipeline because we want the conan integration to be transparent to the developers, so we have to have it present all the time so when we update a package, the developers get it without doing anything. We're using `conan_cmake_run` so that means that in each `cmake configure` conan talks to the server to check for updates. Even worst, since we're building new package revisions all the time (still don't know what triggers a new one on Jenkins) sometimes when it check for updates it also downloads a set of new packages with newer package revisions.

Thanks for your time.

**Comment by memsharded** [comment]
Quick note about this, a problem to consider, make sure than when 2 different recipes provide explicitly 2 different recipe revisions, they conflict, instead of automatically updating and retrieving (overwriting the previous one, one after the other) different revisions.

**Comment by ericriff** [comment]
> Quick note about this, a problem to consider, make sure than when 2 different recipes provide explicitly 2 different recipe revisions, they conflict, instead of automatically updating and retrieving (overwriting the previous one, one after the other) different revisions.

I'm sorry but i didn't follow you.

**Comment by jgsogo** [comment]
> Let me see if I understand you correctly. What you're saying is that in the case where the RREV is explicit (and it changes) conan shouldn't need the `update` flag to retrieve a new package? Just like it does when you change the dependency version?

Yes, that's my opinion. I think that being explicit in the command line (or in a require) shouldn't require any extra argument... if you care about revisions you are listing them (or using lockfiles), if not you are ok with someone else's changing the revision in the cache. Yes, this will require downloading packages for the new revision (maybe compiling from sources if they are not available, but it is expected if your are changing revisions).

 @memsharded highlights a very important thing to take into account. If two different recipes that belong to the same graph declare different revisions for the same requirement it should raise a conflict
 * `libA` requires `gtest/1.10.0@user/channel#RREV1`
 * `libB` requires `gtest/1.10.0@user/channel#RREV2`
 * `consumer` requires `libA` and `libB`

**Comment by ericriff** [comment]
I completely agree with you.
 I'll add the `UPDATE` flag as a temp solution and when this feature is live I'll remove it.

**Comment by ericriff** [comment]
How can I track the progress of this? :thinking:

**Comment by ericriff** [comment]
Could someone please take a look at this?
I'm working on a large codebase that is using a lot of conan packages and using `--update` is annoying since it adds a small delay each time we build. It also means we can't build offline since the check for updates fail.

**Comment by memsharded** [comment]
Hi @ericriff 

I understand this might be inconvenient, so I am trying https://github.com/conan-io/conan/pull/9058. I cannot promise anything, this might be breaking, seems potentially problematic, but lets give it a try.

We are working hard in the new cache implementation for Conan 2.0 that will allow multiple revisions in the cache (and thus eliminating this problem), because we know this can be improved.

**Comment by ericriff** [comment]
Thank you very much, I really appreciate it.

**Comment by memsharded** [comment]
Hi @ericriff 

Finally, to avoid risks of breaking we will introduce this as opt-in with a [conf] ``core:allow_explicit_revision_update`` as you can see in https://github.com/conan-io/conan/pull/9058/files. I hope it is good enough, it might be released next 1.38

**Comment by ericriff** [comment]
This is amazing! THank you very much for the effort.
Which breaking risks are you worried about?

**Comment by memsharded** [comment]
> Which breaking risks are you worried about?

Some companies might consider it something not desired, like devs should be adding revisions explicitly in recipes, or due to some nature of the job, this might end in a loop, or different recipes competing with each other with different explicit revisions (and then probably the latest one wins, but this can be undefined, and the other one will be using a different revision without knowing). The current exception is something that might be protecting them into these behaviors. Beware yourself, that these could be problematic situations if you don't handle explicit revisions with care.

**Comment by ericriff** [comment]
Interesting.
Let's say I have a project that consumes `boost` and `zlib`,with both requirements locked to a specific RREV. Note that `boost` also depends on `zlib`, but its recipe is consumed `as is` in conan index, so no RREV lock for zlib there.

Is there a possibility of my project and boost using different versions of `zlib`? 
Will the behavior be similar to what would happen if I override a package dependency on my main conanfile? (That is, if boost's package requires zlib version A but my project requires version B, version B takes precedence).

**Comment by memsharded** [comment]
> Is there a possibility of my project and boost using different versions of zlib?

In theory, for regular requires, the only possibility is to be using ``private`` dependencies, which are not recommended except for very exceptional situations. Otherwise, different versions or different revisions will conflict and raise.

The situation is different for ``build_requires`` which are private per package. In theory you could have boost have a ``build_requires`` to ``cmake/1.0#rrev1`` and poco package another ``build_requires`` to ``cmake/1.0#rrev2``. This was not possible before the PR, and it would raise, but when we merge the PR, this might become possible, and the last recipe revision to be evaluated will be the one that would remain in the cache.
