### ISSUE TITLE
Recommendations for dealing with configuration for code ('build_requires')

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#7246]
I have several projects (e.g. projectA and projectB) which depend on a common code base (supplierCode).
This code base is configured by compiling with headers generated from config files (supplierCodeCfgA and supplierCodeCfgB).

What would be the preferred way to set these config packages as a `build_requires`?  
From what I can tell I have two options:

1. Use a dedicated `profile`:

    _.conan/profiles/supplierCodeCfgA_
```
[build_requires]
supplierCodeCfgA/[*]@user/channel
```
2. Use `options`:

   _conanfile.py_
```
name = supplierCode
options = {"config": ["A", "B"]}
   
def requirements(self):
    self.requires("supplierCodeCfg%s/[*]@user/channel" % self.options.config)
```

My concern with Option 1 is that since `build_requires` alone does not affect the `package_id`, supplierCode compiled with either of the configurations will share the same package reference and then overwrite each other on Artifactory.  But it also doesn't feel right to add it as an ordinary requirement.

Are there any advantages/disadvantages to either of these approaches that I should know about?  Or is there another option?

I'd be very grateful if you could give some feedback.

**Comment by jasal82** [comment]
We had the same problem and went with the second approach. Actually we encoded the complete requirement reference as option value instead of assembling the string later. I'd also like to know if there's a better approach to this.

**Comment by jgsogo** [comment]
Hi! I think I'm not able to fully understand the situation. I'll try to answer, but probably I need more information about it.

There is a codebase (`supplierCode`) that need to pass through some kind of code-generation tool (`supplierCodeCfgA` or `supplierCodeCfgB`) to generate the actual sources that some consumers downstream will use/link/...

I see these as facts:
 * the code-generation tool needs to be a `build_requires` because it is an executable that runs in the _build_ machine.
 * the `supplierCode` package is unusable without the code-generation tool, so the `build_requires` should be explicit in the recipe.
 * choosing one generator or the other is the responsibility of the consumers

From my POV, these are the recipes:

**supplierCodeCfgA/conanfile.py** (the same for `supplierCodeCfgB`)
```python
class Recipe(Conanfile):
    name = "supplier-code-cfg-a"

    def package_info(self):
        # The executable 'supplier-config' for this package is inside the 'bin' folder:
        bindir = os.path.join(self.package_folder, "bin")
        self.output.info('Appending PATH environment variable: {}'.format(bindir))
        self.env_info.PATH.append(bindir)
```

**supplierCode/conanfile.py**
```python
class Recipe(ConanFile):
    name = 'supplier-code'

    options = {"config": ["A", "B"]}

    def build_requirements(self):
        if self.options.config == "A":
            self.build_requires("supplier-code-cfg-a/...")
        else:
            self.build_requires("supplier-code-cfg-b/...")

    def build(self):
        # Conan will inject the PATH to the 'supplier-config' executable
        self.run("supplier-config ...", run_environment=True)

    def package(self):
        # Package the files after running the supplier-config job
        pass
```

**consumerA.py**
```python
class Recipe(Conanfile):
    name = 'consumer-a'

    requires = 'supplier-code/...'
    default_options = {'supplier-code:config': "A"}  # This consumer requires config-A of the supplier-code
```

**consumerB.py**
```python
class Recipe(Conanfile):
    name = 'consumer-b'

    requires = 'supplier-code/...'
    default_options = {'supplier-code:config': "B"}  # This consumer requires config-B of the supplier-code
```

Is this somehow related to your scenario?

**Comment by memsharded** [comment]
Closing as inactive and outdated, please create new tickets against latest Conan 2 if necessary, thanks for your feedback.
