### ISSUE TITLE
[bug] Can't create Conan package for Visual Studio projects if using git for source

### ISSUE THREAD

**Issue by T-Deuty** [conan-io/conan#7260]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 10.0.18362
  * Compiler+version: Visual Studio 2019 vc142
  * Conan version: Conan version 1.26.0
  * Python version: Python 3.7.4

### Steps to reproduce (Include if Applicable)

1. Using [this page](https://docs.conan.io/en/latest/howtos/visual_studio_packages.html) clone the two repos in the examples (hello_vs and chat_vs)
2. Create the hello_vs package that is required by chat_vs (Hello/0.1@memsharded/testing)
3. Modify the conanfile.py for chat_vs to obtain sources from the git repo instead of using `exports_sources` (see below example conanfile.py)
4. Attempt to run `conan create .` from top-level directory of chat_vs.
5. It will not be able to load the projects for MSBuild because the dependencies are not injected correctly.

Please see this stack overflow post where I go into more detail:
https://stackoverflow.com/q/62581390/4447195

Thank you!

Example conanfile.py:

```
from conans import ConanFile, MSBuild, tools


class ChatConan(ConanFile):
    name = "Chat"
    version = "0.1"
    license = "MIT"
    url = "https://github.com/memsharded/chat_vs"
    requires = "Hello/0.1@memsharded/testing"
    settings = "os", "compiler", "build_type", "arch"
    #exports_sources = "src/*", "build/*"
    generators = "visual_studio"

    def source(self):
        git = tools.Git(folder=self.name)
        git.clone("https://github.com/memsharded/chat_vs")

    def build(self):
        msbuild = MSBuild(self)
        msbuild.build(self.name+"/build/ChatLib/ChatLib.sln", upgrade_project=False)

    def package(self):
        self.copy("*.h", dst="include", src="src")
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="bin", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["ChatLib"]
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

conan create .
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
Chat/0.1: A new conanfile.py version was exported
Chat/0.1: Folder: C:\Users\tdeuty\.conan\data\Chat\0.1\_\_\export
Chat/0.1: Package recipe modified in export, forcing source folder removal
Chat/0.1: Use the --keep-source, -k option to skip it
Chat/0.1: Exported revision: df0b82632b06b79b7652bebb3f7cfd90
Configuration:
[settings]
arch=x86
arch_build=x86
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Chat/0.1: Forced build from source
Chat/0.1 (test package): Installing package
Requirements
    Chat/0.1 from local cache - Cache
    Hello/0.1@memsharded/testing from local cache - Cache
Packages
    Chat/0.1:e3e0f918b3003ba3042799af5e5c9bdffd1e3e4b - Build
    Hello/0.1@memsharded/testing:29d1f4003b3f7143826ef1988625574513d526ce - Cache

Cross-build from 'Windows:x86_64' to 'Windows:x86'
Installing (downloading, building) binaries...
Hello/0.1@memsharded/testing: Already installed!
Chat/0.1: WARN: Build folder is dirty, removing it: C:\Users\tdeuty\.conan\data\Chat\0.1\_\_\build\e3e0f918b3003ba3042799af5e5c9bdffd1e3e4b
Chat/0.1: Configuring sources in C:\Users\tdeuty\.conan\data\Chat\0.1\_\_\source
Chat/0.1: Copying sources to build folder
Chat/0.1: Building your package in C:\Users\tdeuty\.conan\data\Chat\0.1\_\_\build\e3e0f918b3003ba3042799af5e5c9bdffd1e3e4b
Chat/0.1: Generator visual_studio created conanbuildinfo.props
Chat/0.1: Calling build()
Chat/0.1: Skipped sln project upgrade
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.5.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\tdeuty\.conan\data\Chat\0.1\_\_\build\e3e0f918b3003ba3042799af5e5c9bdffd1e3e4b\Chat\build\ChatLib\ChatLib.vcxproj(65,5): error MSB4019: The imported project "C:\Users\tdeuty\.conan\data\Chat\0.1\_\_\build\e3e0f918b3003ba3042799af5e5c9bdffd1e3e4b\Chat\conanbuildinfo.props" was not found. Confirm that the expression in the Import declaration "..\..\conanbuildinfo.props" is correct, and that the file exists on disk.   
C:\Users\tdeuty\.conan\data\Chat\0.1\_\_\build\e3e0f918b3003ba3042799af5e5c9bdffd1e3e4b\Chat\build\MyChat\MyChat.vcxproj(65,5): error MSB4019: The imported project "C:\Users\tdeuty\.conan\data\Chat\0.1\_\_\build\e3e0f918b3003ba3042799af5e5c9bdffd1e3e4b\Chat\conanbuildinfo.props" was not found. Confirm that the expression in the Import declaration "..\..\conanbuildinfo.props" is correct, and that the file exists on disk.     
Chat/0.1: 
Chat/0.1: ERROR: Package 'e3e0f918b3003ba3042799af5e5c9bdffd1e3e4b' build failed
Chat/0.1: WARN: Build folder C:\Users\tdeuty\.conan\data\Chat\0.1\_\_\build\e3e0f918b3003ba3042799af5e5c9bdffd1e3e4b
ERROR: Chat/0.1: Error in build() method, line 20
        msbuild.build(self.name+"/build/ChatLib/ChatLib.sln", upgrade_project=False)
        ConanException: Error 1 while executing set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC/Auxiliary/Build/vcvarsall.bat" x86 && msbuild "Chat/build/ChatLib/ChatLib.sln" /p:Configuration="Release" /p:UseEnv=true /p:Platform="x86" /m:12 /p:PlatformToolset="v142" /verbosity:minimal /p:ForceImportBeforeCppTargets="C:\Users\tdeuty\.conan\data\Chat\0.1\_\_\build\e3e0f918b3003ba3042799af5e5c9bdffd1e3e4b\conan_build.props"

**Comment by Bernhard-L** [comment]
We're expecting the same problems.
The reason is ...
the conanbuildinfo.props will be created by shell command or by using the conan plugin from the configfile (conaninfo.txt|conanfile.py)

But the conanbuildinfo.props is referenced in the commited projectsettings.
If the project and the projectsettings are beeing loaded (without the file existing props file on the machine) Visual Studio refuses to load the entire project (including the (conaninfo.txt|conanfile.py)) and the conan plugin couldn't generate the needed props file.

Temporary solution is to manually generate the file by running "conan install" to generate the props file.
It's no option to include the conanbuildinfo.props in the git commit, because it includes references based on the local installation.

It would be nice, if the plugin would insert
`    <Import Project=".conan\conanbuildinfo.props" Condition="exists('.conan\conanbuildinfo.props')" Label="ConanSettings" />
` 
instead of

` <Import Project=".conan\conanbuildinfo.props" />`

**Comment by memsharded** [comment]
Hi @Bernhard-L 

Just to clarify, it seems that you are describing a problem with the VS-conan-extension/plugin? Conan does not insert anything into user projects, it is the users who should directly add the .props files they want into their projects.

@T-Deuty 

Regarding your issue, I am very sorry that we didn't respond to it. Sometimes it happens due to "overflow".
It seems that your case above was a folder name mismatch, and it needed to reference the .props file in another location.



In any case, for both @T-Deuty @Bernhard-L, I would like to point to the new MSBuild integration in: https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html

The MSBuildDeps has several advantages:
- It creates one .props file per dependency, but with the correct transitivity. For solutions with multiple sub-projects, you could add only the specific dependencies that you want for each subproject easily.
- It allows custom user configurations, like ``ReleaseShared``, ``MyCustomRelease``

The MSBuildToolchain:
- Is more explicit, and easy to use by developers, instead of the magic auto-generated on the fly that the previous ``MSBuild()`` helper did
- It will also generate a ``conanvcvars.bat`` with the right vcvars command for the current settings, so developers don't need to figure out which environment to activate.

They are both now open to further configuration and customization in the ``generate()`` method, and they are also starting to use the new ``[conf]`` configuration. 

Things are still experimental, but this one is quickly being matured, I would strongly suggest to have a look. This new integration will be the one used for Conan 2.0, and the previous ones will be removed.

**Comment by DreamSworK** [comment]
Yes, I have the same issue.
It seems like there is a bug inside the Visual Studio generator _(MSBuild)_.
I also followed the tutorial [How to create and reuse packages based on Visual Studio](https://docs.conan.io/en/latest/howtos/visual_studio_packages.html)
And when I use `conan create . memsharded/testing` it creates the wrong Visual Studio project _(HelloLib.vcxproj)_
But the bug presents only for the `Release|x64` configuration, other configurations are good.

```
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
    <Import Project="x64\Release\.conan\conanbuildinfo.props" />
  </ImportGroup>
```

The Visual Studio generator adds the import file `x64\Release\.conan\conanbuildinfo.props` that doesn't exist.
How you can see only for `Release|x64`

**Comment by memsharded** [comment]
Hi @DreamSworK 

It seems that this is a bit outdated:

- The referered integration is considered legacy, it has been superseded some time ago by the new ``from conan.tools.microsoft import MSBuildToolchain, MSBuildDeps, MSBuild``
- This new generator is more flexible, it is multi-config, creates .props files per dependency (so they can be added individually to subprojects if desired)
- Please check: https://docs.conan.io/en/latest/reference/conanfile/tools.html for the new tools in general (not only MSBuild, and the VS integration in particular)
- Working templates can be easily created with ``conan new hello/0.1 -m=msbuild_lib`` (and ``-m=msbuild_exe``), that is a good starting point for testing things


The failure in your reported issue could be that ``conan install`` was not called before opening the project, for the necessary configurations. For the new integration, it is still necessary, to do ``conan install `` as many times as supported configurations (Release/Debug, x64/x86).

I am closing this issue, please try using the new integration, and do not hesitate to open new tickets for any question or issue that you might have.

**Comment by DreamSworK** [comment]
Hi @memsharded
I tried to use `MSBuildDeps` as in this article https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html

When I use command `conan install conanfile.py # default is Release`, it will add the `.props` file as an import only for `Release|x64`, but the project file contains other configurations, but without `.props` file

Is the behaviour as expected?

**Comment by memsharded** [comment]
No, Conan will not modify your ``.vcxproj`` files or solution. The addition of the generated files need to be done explicitly by the user (the default ``conan new hello/0.1 -m=msbuild_deps`` already did that, adding the toolchain .props file to the vcxproj).

``MSBuildDeps`` generate multiple files, for VS you typically want to do:
```bash
$ conan install . -s build_type=Release  # Release is the default, can be omitted
$ conan install . -s build_type=Debug  # if you plan to eventually switch or use the Debug config
```
The files generated are:
- ``conandeps.props``: Contain all your dependencies, with all configurations
- ``conan_pkg.props``: Contain the info from ``pkg`` for all configurations, all dependencies

So typically adding all or specific .props files to all configs is good, as the ``.props`` files already contain the conditionals to use the right binaries for each configuration.
