### ISSUE TITLE
[bug] msbuild generator only works with Visual Studio compiler

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#7267]
When adding the experimental `msbuild` generator,
the recipe cannot be used anymore with other compilers.
This message is printed:
```
*** The 'msbuild' generator is EXPERIMENTAL ***
cpython/3.7.8: ERROR: Generator msbuild(file:None) failed
The 'msbuild' generator only works with Visual Studio compiler
ERROR: The 'msbuild' generator only works with Visual Studio compiler
```

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Compiler+version: gcc 9.3.1
  * Conan version: 1.26.1
  * Python version: 3.7.7

### Steps to reproduce (Include if Applicable)
Build a recipe with the msbuild generator on Linux with gcc.

Tagging @memsharded

**Comment by memsharded** [comment]
Not sure if a bug or a feature. This generator is a "multi" generator, and as such, it really needs the input settings, the ``Visual Studio`` compiler, etc, in order to be able to generate something meaningful.

So using it should be conditioned to ``if self.settings.compiler == "Visual Studio": self.generators = "msbuild"``. What is not clear is the UX/location of this conditional, so lets discuss it.

**Comment by madebr** [comment]
My only use of the `msbuild` generator to date is the cpython recipe at https://github.com/conan-io/conan-center-index/pull/1510

I would be happy to conditionally add the `msbuild` conditionally, if the compiler is `Visual Studio`. But I haven't seen this before and I don't know whether it is supported.
Should this conditional be added to `config_options` or `configure`?

On another side, msbuild is just a build system and can theoretically be used with any compiler.

**Comment by memsharded** [comment]
> Should this conditional be added to config_options or configure?

Should be possible in ``configure()`` I think it should work out of the box, but that was exactly my point, probably not the best UX, so we need to think what would be the best way to define conditional generators and document it accordingly.


> On another side, msbuild is just a build system and can theoretically be used with any compiler.

In that case, we would need to know real use cases, and know what values should  be used to build the conditions inside the .props files. Because right now, we are using the ``toolset`` for example, which I don't think exist in other compilers.

**Comment by madebr** [comment]
> In that case, we would need to know real use cases, and know what values should be used to build the conditions inside the .props files. Because right now, we are using the `toolset` for example, which I don't think exist in other compilers.

Visual Studio IDE provides support for linux, using gcc/clang, which does not have toolset.
I haven't used this yet, so I can't really tell how it works or should work.
Let's wait on an individual requiring this..

**Comment by memsharded** [comment]
I am considering ``configure()`` as the place to define conditional generators in https://github.com/conan-io/conan/pull/7359, it seems that adding a new method just for this is too much and ``configure()`` seems to work, lets discuss it in the PR.

**Comment by memsharded** [comment]
> Visual Studio IDE provides support for linux, using gcc/clang, which does not have toolset.

I have relaxed ``msbuild`` generator now doesn't fail in Linux: https://github.com/conan-io/conan/pull/7361
