### ISSUE TITLE
[bug] 'conan remove' doesn't work with a pattern (expected same behavior as 'conan search')

### ISSUE THREAD

**Issue by AkileshDS1994** [conan-io/conan#7291]
Hi Team,

We have **dev** and **prod** conan packages in our artifactory.

**_conan search -r sample-artifactory_**
Existing package recipes:

ABC/3.11.4_eb1@dev/4201ccae9274e22a9306ca9ce4907ca1a2ff7fcb
BCD/3.11.5_test@dev/054d64a961056031a6ab97f5f761281be0638a2b
EFG/3.11.6_test@dev/3ab6718bc5760f4871abb186e40c7b1f176c99a1
XYZ/3.11.4@prod/6201ccae9274e22a9306ca9ce4907da1a2ff7fce
PQR/3.11.5@prod/754d64a961056031z6ab97f5f761281bf0638g2b
RST/3.11.6@prod/3zb6718bc5790f4871agb186e40c7b1f176d99y1

**Note** : dev packages have pattern @dev in the package names. And similary prod packages have pattern @prod in the package names.

We want to clean up our conan **dev** packages all together once in a month.

**_conan search "*/*@dev/*" -r sample-artifactory_**
Existing package recipes:

ABC/3.11.4_eb1@dev/4201ccae9274e22a9306ca9ce4907ca1a2ff7fcb
BCD/3.11.4_test@dev/054d64a961056031a6ab97f5f761281be0638a2b
EFG/3.11.4_test@dev/3ab6718bc5760f4871abb186e40c7b1f176c99a1

When i try to remove the above packages using the below commands, it does not work.

**_conan remove "*/*@dev/*" -p -f -r sample-artifactory_**  --> does not work

**_conan remove "*/*@dev/*" -f -r sample-artifactory_** --> does not work

**Note** :  However, deletion of one conan package at a time works without any issue. But that is not our intention.
**_conan remove EFG/3.11.6_test@dev/3ab6718bc5760f4871abb186e40c7b1f176c99a1 -f -r sample-artifactory_**  --> works

Kindly help us delete only **dev** packages leaving behind the **prod** ones.

Thanks in advance!

Regards,
Akilesh D S

**Comment by jgsogo** [comment]
Hi! According to the documentation `conan remove` accepts a pattern, if it doesn't work the same way as `conan search` it is a bug.

---

Nevertheless, I would recommend you to have different repositories in your artifactory, one for the _production_ packages and another one for the _development_ ones. That way you don't need to use different references and when you consider a package ready for production you just need to promote (or copy) it to the _production_ repository instead of building it again. 

It totally depends on your workflow and your company policies, but it is our recommendation: use always the same reference but different repositories for _develop_, _staging_, _production_,... that way consumers will always `requires = "ABC/3.11.4_eb1@mycompany/stable"` and it depends on the remotes added to Conan (and their order) where the package will come from.

**Comment by AkileshDS1994** [comment]
Hi Javier,

What i noticed is the  above **conan remove** works with git bash client in my local but does not work when run in the Jenkins job in the **Execute shell** build step.
However **conan search** works with out any issue.

Its a wierd beahvior. Is this an escape issue in Jenkins step? then it should affect the conan search command also.

Thanks in advance!

Regards,
Akilesh D S

**Comment by jgsogo** [comment]
That's weird, it should be something related to Jenkins, then. Are you sure they are the same characters? Are both commands executed in the same node?

**Comment by AkileshDS1994** [comment]
Hi Javier,

Both the commands are the same, they have the same characters. They are running in the same node back to back. Works in git bash but does not work in Jenkins.

Please find attached the Jenkins configuration and console output.

Thanks in advance!

Regards,
Akilesh D S
[conan remove jenkins issue.txt](https://github.com/conan-io/conan/files/4877074/conan.remove.jenkins.issue.txt)

**Comment by AbrilRBS** [comment]
Closing - Sorry we couldn't help you further. The search/list/remove patterns have been overhauled in v2 and we feel confident they cover most cases. You specific issue fell out of our domain. Feel free to open new issues if anyone ever finds a similar one, thanks!
