### ISSUE TITLE
How to copy source code file of all packages in transitive dependencies?

### ISSUE THREAD

**Issue by kushalembsys** [conan-io/conan#7294]
Lets say my project is dependent on package `B` and the package `B` in turn depends on package `C`. Provided both these packages `B` and `C` have respective source code in it.

My project's `conanfile.txt` can be realized is as follow:
```
[requires]
B/1.0.0@kd/testing

[generators]
make

[imports]
B, * -> ../B
```
The `[imports]` copies only source files of package `B` and **not for `C`**.
If I explicitly write `C, * -> ../C` in `[imports]`, it copies source file of both packages. But this is not the way I need.

How can I copy source files of package `C` without mentioning it in my project's `conanfile.txt`?

**Comment by jgsogo** [comment]
Hi, @kushaldalsania 

There are several issues trying to retrieve sources from dependencies in order to compile them all together in the consumer package. This is something possible, but requires a little bit of work on your side... Conan is a package manager and we are focused on sharing binaries, this problem will take us some time before addressing the source-packages one.

Have a look to this issue and others that are linked from it: https://github.com/conan-io/conan/issues/6944, you might find many interesting comments.

The problem with your use-case could be related to the files packaged in `C` and/or `B` or to your `[imports]` declarations: you are telling Conan to copy files inside `B` folder to `../B`, but you are not saying anything about `C`, maybe you should add:

```
[imports]
B, * -> ../B
C, * -> ../C
```

and, of course, those sources must be available in the package.

**Comment by memsharded** [comment]
It seems that B is a folder inside the package B, so that pattern only matches for package B. If you want to automatically package from all dependencies, you might try:

```
[imports]
., * -> ..
```

**Comment by memsharded** [comment]
A lot of things have happened since this issue was last active:

- Conan 2.0 implements a new way to force the download of sources and execution of ``source()`` method, for dependencies, without really needing to build again from source, with the ``-c tools.build:download_source=True`` new configuration. It can also be used in ``conan graph info`` command, but also in ``conan install``
- The new ``deployer`` mechanisms allows to easily collect things from dependencies, including sources, which can be used for preparing some debugging, as they can also be used to automate tasks.

See for example: https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html

In any case, we have learned that the best for debugging is doing an actual local build, like ``conan install --build=pkg_to_debug*`` and that already allows to step-into that dependency.

So I am closing this as solved, please create new tickets for further questions.
