### ISSUE TITLE
[feature] Make latest revision the latest uploaded, not latest created

### ISSUE THREAD

**Issue by rddesmond** [conan-io/conan#7331]
## Overview

When uploading a recipe and package, the date of that upload is stored in revisions.txt (or similar for Artifactory).  If the recipe is reuploaded, this date is not uploaded.  This can be a problem if the recipe is erroneously changed and that change is reverted.  Since the reverted version's hash collides with the original version, it's date is not updated.  This means the erroneously created version remains the latest unless the erroneous version is deleted (which can be either time consuming or already have been used somewhere).

## Procedure

1. Start a conan server (both Artifactory and the baseline exhibit the same thing)
    ```bash
    conan_server &
    conan remote add local localhost:9300
    conan config set general.revisions_enabled=1
    ```

2. Upload a recipe, build it, and upload to the server
    ```bash
    conan new test/1.0
    conan create . user/testing
    conan upload test/1.0 -r local -c
    conan search test/1.0@user/testing -r local --rev
    ```
    Note that one revision exists
    ```
    Revisions for 'test/1.0@user/testing' at remote 'local':
    c824dd88adc7b3b1c644a87fd06c0807 (2020-07-08 22:13:27 UTC)
    ```

3.  Edit the recipe and reupload it
    ```bash
    cp conanfile.py conanfile.py.bak
    echo '# some edit' >> conanfile.py
    conan create . user/testing
    conan upload test/1.0 -r local -c
    conan search test/1.0@user/testing -r local --rev
    ```
    Note that two revisions now exists
    ```
    Revisions for 'test/1.0@user/testing' at remote 'local':
    21e503ad88875ca026c787a6d9027452 (2020-07-08 23:01:06 UTC)
    c824dd88adc7b3b1c644a87fd06c0807 (2020-07-08 22:13:27 UTC)
    ```

3.  Revert the revision and reupload it
    ```bash
    mv conanfile.py.bak conanfile.py
    conan create . user/testing
    conan upload test/1.0 -r local -c
    conan search test/1.0@user/testing -r local --rev
    ```
    Note that there is no change, so that the _latest upload isn't the default rrev, but the latest created is_.
    ```
    Revisions for 'test/1.0@user/testing' at remote 'local':
    21e503ad88875ca026c787a6d9027452 (2020-07-08 23:01:06 UTC)
    c824dd88adc7b3b1c644a87fd06c0807 (2020-07-08 22:13:27 UTC)

**Comment by memsharded** [comment]
Hi @rddesmond 

Thanks for the detailed description!

Quick suggestion: have you tried running a force in the upload?

```bash
$ conan upload test/1.0 -r local -c --force
```
That might avoid the checksum checks and might put that revision again as the latest one. If you manage to try please let us know.

**Comment by rddesmond** [comment]
Good suggestion!  Same result, though.

```bash
conan upload test/1.0 -r local -c --force
conan search test/1.0@user/testing -r local -rev
```
```
Revisions for 'test/1.0@user/testing' at remote 'a':
21e503ad88875ca026c787a6d9027452 (2020-07-08 23:01:06 UTC)
c824dd88adc7b3b1c644a87fd06c0807 (2020-07-08 22:13:27 UTC)
```

**Comment by jgsogo** [comment]
IMO this is something to be implemented in the server, maybe the `--force` suggested, as it is uploading again the recipe should compute a new timestamp for the recipe. The alternative would be to implement a workaround in the client (remove + upload).

I have a question about packages already uploaded to the server. If we re-upload a recipe revision and override the timestamp, what do we do with packages that already exist in the server? They belong to that recipe revision, but now they have a timestamp previous to the recipe one, which is totally unexpected. Should we remove existing packages like the workaround `conan remove`+`conan upload` will do?

**Comment by rddesmond** [comment]
For me, updating the timestamp without changing the packages is the most useful, despite the inconsistent timestamps.  The workflow I have here:

1. All 3rd party dependencies are in a single git repo.
1. At each check-in, they are all exported and uploaded to Artifactory.  The RREV collision causes most to be a no-op, but the ones that are updated cause a new RREV for downstream processes to pick up.
1. Things aren't built then (don't know what's useful, don't know options/settings, etc), but when a downstream process sees that the latest recipe for a given package is unbuilt, it automatically builds and uploads the package.

With this, an RREV collision happens a lot.  The problem in this story was that when a recipe was reverted to an old one (which is admittedly rare), and it wasn't signaled to downstream processes as the latest to build.

**Comment by memsharded** [comment]
I have been reviewing this, and I think:

- Yes, this might require a change in the server side, and that will take time. I suggest going with workarounds like forcing a new revision introducing some change in the recipe (even a comment)
- I would like to have confirmation from @lasote about this behavior, he implemented revisions, I would like to make sure there is nothing there we are not considering.
- I am considering removing timestamps in manifests for Conan 2.0. Now that revisions will be the default, everything is content or hash based, and timestamps only make sense for defining the latest one. As revisions "latest" is defined by server time, the manifests timestamps will probably be useless. (check discussion about updates with revisions here: https://github.com/conan-io/conan/issues/7436)

**Comment by lasote** [comment]
I understand your use case but I think it could be valid the other way around too. If something is built at moment X and some time later it is uploaded again, for instance, because of a bad retry in CI or something, you likely don't want it to become the new latest.

I find it more robust at it is, but I have not a strong opinion. Also it would be difficult (technical issues) to change it in Artifactory.

**Comment by memsharded** [comment]
After discussing this, it seems this is the current way of thinking:

- By default, uploads cannot change the position of a given revision. That would cause a lot of instability of "latest revision" specially when multiple CIs are uploading packages for different platforms to the server.
- We could define a ``--force`` mode, or ``really wipe and reupload`` mode, that would make the uploaded revision the latest one, because it would have removed the previous (same) one from the server. Certainly not something to be used in typical CI flows, but just for exceptional situations. 

At the moment, it seems that the workaround of doing some changes to the recipe and thus creating a new revision would be a good one, so I am moving this to Conan 2.0 where we can re-think about the whole upload process.

**Comment by kdsx** [comment]
I've faced the same issue. I've tried to rollback a "bad" revision, but CI builders didn't want to pick up an older "good" revision.

But then I've re-uploaded a "good" revision (deleted it from remote and uploaded again), and it surprisingly didn't help.
It looks like conan sees the newer revision but does not update the package to it for some reason. In the output I see the following:
```
conanfile.py: Installing package
Requirements
...
    rpi-firmware/1.20200601 from 'nx' - Newer
...
Packages
...
    rpi-firmware/1.20200601:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
```
It reports that it's "Newer", but not "Updating". Conan is invoked with `--update` flag.
Why conan does not update it?

**Comment by kdsx** [comment]
Ah, it looks like it was the exact situation from this issue title. Despite the fact that `conan search` displayed a newer timestamp of the package, conan compared a creation timestamp to local cache. After I rebuilt the package and re-uploaded it again, it was updated on CI builders automatically.

**Comment by FnGyula** [comment]
This issue is really devastating at times. It's always easy to publish immediately a revision of the same recipe, because then I also have to produce the binaries, which in some cases can take up to hours, keeping the builds, dependent on this package broken.

Lock-files would help on it, sure, but they aren't in use just yet. I would really appreciate a way to deal with this! At this point I'm considering to get some uber-account to our Artifactory instance, and switch around the time-stamps...

**Comment by memsharded** [comment]
I am submitting https://github.com/conan-io/conan/pull/13155 to further explicitly validate behavior.
It has been a long time and we have been learning and experiencing with this. These are the conclusions:

- Making it the latest by default for a normal ``upload``, when upload a revision, can never make it latest. We have been playing with that and it generated a ton of instability, a total unmaintainable mess.
- The ``--force`` flag behavior is to force the upload of files, but that doesn't alter the server ordering if the revision was already there. Having this command line argument to implement such a behavior would be a shotgun loaded waiting for a foot, as it would be super easy that users will use this in their CI scripts, leading to the behavior above.
- Trying to implement other arguments like ``--really-change-revision-order`` require  a new client-server API, and this is a many months long effort, not worth it, because there are easier ways already.
- Even if this was implemented, it should still never be used in CI, as said, this is an emergency thing, not something that can be done in CI automatically at each build, without entering the above mess.
- For cases when something went completely wrong, then there is already a simple and intuitive way: remove the offending revision, then re-upload it. This works perfectly fine, it is quite fast, and it is clear for readers that it will make the uploaded thing the latest one, because to the server eyes, it would be a new revision.

https://github.com/conan-io/conan/pull/13155 will close this. Thanks all for the feedback.

**Comment by memsharded** [comment]
Regarding 

> This issue is really devastating at times. It's always easy to publish immediately a revision of the same recipe, because then I also have to produce the binaries, which in some cases can take up to hours, keeping the builds, dependent on this package broken.

The recommended way is:

- Do not upload a recipe with binaries under construction to any repo that builds depend on it. If the builds depend on the "develop" server repo, the build of such a slow thing should go to the "builds" repo
- Only once all the build agents have built all the binaries for that specific revision, and uploaded it to the "builds" repo, then a promotion is run
- The promotion copies the new recipe revision and its binaries from the "builds" repo to the "develop" repo. This operation is fast and efficient, it doesn't use any extra storage. This makes available the package fully built for that revision to the other processes builds only when it is complete.

**Comment by memsharded** [comment]
Closed by https://github.com/conan-io/conan/pull/13155
