### ISSUE TITLE
[question] Specifying version and requires in a common file outside source folder

### ISSUE THREAD

**Issue by zebrajap** [conan-io/conan#7355]
We have a repository with a folder structure as below. I want to specify the version and the requires in the VersionInfo.txt which are common to all components. Is it possible?

Root
│── Component 1
│      ├── conanfile.py
│── Component 2
│      ├── conanfile.py
│
│── VersionInfo.txt

**Comment by memsharded** [comment]
Hi @zebrajap 

Yes, it is possible, but it will have a small inconvenience because of the different path in your local folder and in the cache (in the cache, every package needs to be independent and isolated, so it will contain its own copy of ``VersionInfo.txt``.

You would have something like:

- You need to ``exports`` the ``VersionInfo.txt`` file, so it is accessible also when the recipes are in the local cache. Something like:

```python
exports = "../VersionInfo.txt
```

- The ``requirements()`` method, you can read the file, something like:

```python
def requirements(self):
      # the path here is the path in the Conan cache. If you need it to work locally, you might need to provide a fallback path
      recipe_folder = os.path.dirname(__file__)  # this will probably be improved in next version, with explicit attribute
      versions = load(os.path.join(recipe_folder, "VersionInfo.txt")
      # parse and extract your info
      self.requires(.... data parsed from the file....)
```

- To especify the version of a package when it is being created, if that is what you want, you can leverage the ``set_version()`` method, it might be something similar to the above:

```python
def set_version(self):
      # The path here is the local path, before copying it to the Conan cache
      versions = load(os.path.join(self.recipe_folder, "..", "VersionInfo.txt")
      # parse and extract your info
      self.version = extracted version
```

As a hint, I think it could be simplified if each package contained its own .txt definition. Please let me know if the above helps. Thanks!

**Comment by zebrajap** [comment]
Hi @memsharded,

Thanks for the suggestion.
So when conan upload is executed, wouldn't it call requirements()? If it is called, it cannot find the file as the location is changed now.

**Comment by memsharded** [comment]
Hi!

No, ``conan upload`` will not execute any of the recipe methods, including ``requirements()``.
If you are seeing any issues not finding the file, that should happen earlier, like in the ``conan create`` command, but not in the upload. Also there will be only 2 different situations:

- The recipe is evaluated in the user folder, not in the cache. This happens if you execute ``conan install .`` in the directory containing the ``conanfile.py``, like in order to develop locally that package. The relative path in this case will be ``../VersionInfo.txt``. The ``set_version()`` executes always in user folder, because it is only necessary when the package is being created. When it is already in the cache, the version is known and this method is not evaluated.

- The recipe is evaluated in the Conan cache, like when it is consumed as a dependency, or when it is being created. Adding ``exports = "../VersionInfo.txt"`` will copy the file to the folder containing the ``conanfile.py``. The relative path is ``./VersionInfo.txt``. You can inspect your local cache in ``<userhome>/.conan/data``, it is relatively straightforward to navigate.


I would also like to recommend a built-in way that Conan has to load data from a ``conandata.yml`` file. It should be located besides every recipe, like:

- Root
│── Component 1
│ ├── conanfile.py
│ ├── conandata.yml
│── Component 2
│ ├── conanfile.py
│ ├── conandata.yml

The ``conandata.yml`` is automatically exported, automatically loaded too. 
Also, the versions can be defined directly in the command line. You can leave the ``version`` undefined in the recipes, then do:

```bash
$ conan create .   version@user/channel
```

**Comment by zebrajap** [comment]
Hi,
I tried this. It tries execute requirements() during export-pkg step and there it is referring local cache. Should I switch between paths based on executed command?

**Comment by memsharded** [comment]
No, I would still try to reconsider to use the same ``VersionInfo.txt`` shared for all packages, as this might have some undesired consequences down the road. For example, you can change some data in ``VersionInfo.txt``, that affects only to *Component1*. But as the file is also used by all components, all other components will create a new package, with a new ``VersionInfo.txt``, that will modify its recipe revision, and considered as a new thing, even if nothing really changed for that other components. 

These things can be very useful, for example, to achieve more efficient CI, re-building only what is necessary to rebuild. If the components change, even if it was not necessary, they will need a re-build to be fully sure. 

I don't know if this is clear, but please let me know. If you need we could also chat in CppLang slack or somewhere else.

If you want to still support that flow, I would implement it as follows:

```python
def _get_version_info(self):
      recipe_folder = os.path.dirname(__file__)  # this will probably be improved in next version, with explicit attribute
      path = os.path.join(recipe_folder, "VersionInfo.txt")
      if not os.path.exists(path):  # Then we are in the local user folder
           path = os.path.join(recipe_folder, "..", "VersionInfo.txt")
      versions = load(path)
      # process the data, as json or whatever "version_data"
      return version_data

def requirements(self):
      version_data = self._get_version_info()
      for require in version_data["requires"]:  # Just a naive assumption of the data
            self.requires(require)

def set_version(self):
      version_data = self._get_version_info()
      self.version = version_data[self.name]["version"]
```

I have not tested it, might have some minor syntax error or something, but that is the idea.

**Comment by zebrajap** [comment]
Hi @memsharded,

Sorry for not explaining my entire plan here. I was trying to keep few other information as well in the same file.
1. We do have dependent libraries coming as a pack with all having a single version. Hence keep that version here
2. Set of dependencies are taken as code from git repo using a tag. Hence to keep that tag here.

Both above are common for all our components. Therefore changing centrally is the most meaningful thing to do.

As you said above, we are fine with rebuilding whole repository as it is again delivered as a pack with a single version.

Above solution suggested by you tested and is working for me. Thanks for the support.

**Comment by memsharded** [comment]
HI @zebrajap 

Ok, good to know, thanks for the explanation!

Happy to know that the above solution worked, so I am going to close this issue as solved, don't hesitate to open more if you have further questions. Thanks!
