### ISSUE TITLE
[question] Invalid setting value

### ISSUE THREAD

**Issue by pvavercak** [conan-io/conan#7356]
Hello everybody,

I'm facing an issue with wrong arch value that is set by a profile.
I'm trying to build a package with Visual Studio compiler.
The package's settings are:

`settings = "os", "compiler", "build_type", "arch"`

and in $CONAN_USER_HOME/settings.yml is arch:["x86"] present.
When I try to build my package with the following settings

`[settings]
arch=x86
arch_build=x86
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Ninja`

it fails with the following log:

`ERROR: Error while initializing settings. Invalid setting 'x86' is not a valid 'settings.arch' value.
Possible values are ['x86_64']`

Is somebody familiar with such an issue?

I have read a suggested article from the error message.
Conan version is 1.22.1, but I would like to avoid updating it to a later one.

**Comment by memsharded** [comment]
Hi @pvavercak 

This is indeed very weird. What is the definition of ``arch_build`` in ``settings.yml`` file? Feel free to copy large parts of that file here? Also, to make sure: are you running in a 32bits machine? This is quite unusual nowadays, specially for Windows machines.

**Comment by pvavercak** [comment]
Hi @memsharded,
Thanks for the quick response.

Here's my arch_build line from settings.yml
`arch_build: [x86, x86_64, ppc32be, ppc32, ppc64le, ppc64, armv5el, armv5hf, armv6, armv7, armv7hf, armv7s, armv7k, armv8, armv8_32, armv8.3, sparc, sparcv9, mips, mips64, avr, s390, s390x, sh4le]`

I won't share the whole file because this file is identical with the default settins.yml available in conan docs.

I'm running on a 64bit Windows and I set up a command line using vcvarsall.bat script from VS build tools in case I want a 32bit build.

Another thing I want to mention is that if I try to build a different Conan package with a 32bit configuration, the build works.
This is happening only with one particular package.

**Comment by memsharded** [comment]
If you are using a 64 bits machine, please try the following:

Change your ``default`` profile in ``<userhome>/.conan/profiles``, and put there ``arch_build=x86_64`` (this is the architecture of the build system). You can directly edit the file, or you have the command ``conan profile`` that can be used to manage, change profiles. Then try again your package and let us know. It would be good if you shared the ``conanfile.py`` of your package, to have a look.

**Comment by pvavercak** [comment]
I have fixed the issue and it was caused by InnoSetup conanfile.
https://github.com/kwallner/conan-InnoSetup/blob/master/conanfile.py

In its conanfile.py is only x86_64 arch specified.

Anyway, the error message was not clear and it didn't inform me about a package that causes the issue.
I think this would be a great idea for a new feature. 

Thank you for your help @memsharded

**Comment by pvavercak** [comment]
I have one further question.

Is there a way how can I change settings of a dependent package right in conanfile.py?

I know it can be done in a conan comman.

**Comment by memsharded** [comment]
> Anyway, the error message was not clear and it didn't inform me about a package that causes the issue.
I think this would be a great idea for a new feature.

yes, the syntax ``settings = {"os": ["Windows"], "arch": ["x86_64"]}`` is already planned to be deprecated and removed in Conan 2.0. Now the recommended way is to raise ``ConanInvalidConfiguration`` in the ``configure()`` method, when a platform is not supported.


> Is there a way how can I change settings of a dependent package right in conanfile.py?

No, the idea is that the settings is something that cannot be defined in the recipes. As an obvious example you cannot define ``os=Windows`` value in a recipe, because that is something that depends on the system that you are running. Also, while exceptions are allowed with per-package settings, they should be seen mostly as "project-wide" configuration, all the packages in the dependencies should mostly be using the same settings. If it is something very specific for one package, then maybe consider ``options`` instead. ``options`` can be defaulted and assigned values in recipes.

The recommended way to manage configuration (conanfile.py recipes are "definition", settings are "configuration") is using profile files. You can specify per-package settings, using patterns, etc. You can compose and include() other profiles and use variable substitution. You can manage your profiles with ``conan config install`` putting the profiles in a git repo or zip in an http server, sharing the same profiles with the team, and to be used in CI processes.

**Comment by pvavercak** [comment]
This approach I'm already using and in CI we install profiles using `conan config install` but this case was that I wanted to use InnoSetup tool for creating an .EXE archive that is a classical windows installer. Since my CI is running on WIN64 host machine, it is alright that one package (specifically InnoSetup tool) would be configured as x86_64. It is only used for generating EXEs.
I have set the arch setting for InnoSetup in my pipeline script and everything works fine.
I think this thread can be closed.

Thank you so much for your time, appreciate it.

**Comment by memsharded** [comment]
Thanks for your feedback, do not hesitate to open new issues if you have further questions. Cheers!
