### ISSUE TITLE
Debug/release seaparate remotes

### ISSUE THREAD

**Issue by danielhalati** [conan-io/conan#7391]
I have the following scenario: I store 3rd party libraries in separate remoted depending on the build type (debug/release).

I have a script that helps me download the binaries and depending on the build type option, I copy a different remotes.json file to .conan folder.

The issue that I am facing is that when the local cache is empty I can pick up let's say to download debug binaries everything works fine, but then I want to download also release binaries and it doesn't work until I clear the local cache. It complains that 'debug' remote is not present in the remotes file, which is true because I just overwrite the file with a remote for release.

This works fine

```
Copy settings.yml to /home/user/.conan/settings.yml
Copy remotes-debug.json to /home/user/.conan/remotes.json
conan install requirements_BB1Cxxx.txt -pr /home/user/Desktop/newtoolchain/scripts/../conan/profiles/x86_64-Linux -s build_type=Debug -if _Sandbox_INSTALL_BB1Cxxx -v --no-imports
```

And then:

```
Copy settings.yml to /home/user/.conan/settings.yml
Copy remotes-release.json to /home/user/.conan/remotes.json
conan install requirements_BB1Cxxx.txt -pr /home/user/Desktop/newtoolchain/scripts/../conan/profiles/x86_64-Linux -s build_type=Release -if _Sandbox_INSTALL_BB1Cxxx -v --no-imports
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=4.8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: No remote 'artifactory-debug' defined in remotes
```

This is how remotes-debug.json looks like:

```
{
 "remotes": [
  {
   "name": "artifactory-debug",
   "url": "http://172.17.5.110:8081/artifactory/api/conan/debug-packages",
   "verify_ssl": true
  },
  {
   "name": "artifactory-headeronly",
   "url": "http://172.17.5.110:8081/artifactory/api/conan/headeronly-packages",
   "verify_ssl": true
  }
 ]
}
```

And remotes-release:

```
{
 "remotes": [
  {
   "name": "artifactory-release",
   "url": "http://172.17.5.110:8081/artifactory/api/conan/release-packages",
   "verify_ssl": true
  },
  {
   "name": "artifactory-headeronly",
   "url": "http://172.17.5.110:8081/artifactory/api/conan/headeronly-packages",
   "verify_ssl": true
  }
 ]
}
```

**Comment by memsharded** [comment]
Hi @danielhalati 

First, please let me say that what you are doing might be an antipattern. Unless you have some very strict regulatory or security constraints, and really need to separate packages based on the ``build_type``, this wouldn't be necessary. Conan can manage many different binaries, for different build_types in the same repo without problems. As it seems you are also separating header-only packages to their own repository, it doesn't seem the case. But please let us know about your use case, and why you are doing that, it seems your setup could be way simpler.


Besides that, the reason you might be seeing that behavior is that Conan (Api V1, i.e not using revisions), is not decentralized by package binaries. Once it finds one recipe in one remote, it will try to get the binaries from that remote. This is because, as revisions (changes to the recipe without bumping versions) are not enabled, it would be impossible to guarantee the consistency of the recipe among different remotes.

This problem should most likely go away if you enable revisions (Using revisions will be the default and only way in Conan 2.0), as revisions know how fetch binaries for the same recipe from different remotes. Please have a look and give it a try and let us know. (But please in any case, as commented above I would strongly suggest to reconsider your approach). Thanks!

**Comment by danielhalati** [comment]
I will reduce to only one remote then. Thanks for the quick reply

**Comment by memsharded** [comment]
Ok, great if you can do it. Recall that one repo can contain any number of binaries for the same recipe, for different OS, for different compilers, and compilers versions, and any variant of the package you want to store there.

Please let us know if you have any further question, cheers!
