### ISSUE TITLE
How to print plain list dependencies

### ISSUE THREAD

**Issue by Jochen0x90h** [conan-io/conan#7395]
Hi!

How do I print a plain list of dependencies?
with
`conan graph lock --build=missing .`
I get something like

    Requirements
        eigen/3.3.7@conan/stable from 'conan-center' - Cache
        jasper/2.0.14 from 'conan-center' - Cache
    Packages
        eigen/3.3.7@conan/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        jasper/2.0.14:350aeebd67798ae48a25688104439452e13c8c75 - Cache

But I just like something like

    eigen/3.3.7@conan/stable
    jasper/2.0.14@

to iterate over the list and e.g. conan upload all dependencies that were built to a repository. Is this possible?

Thanks,
Jochen

**Comment by memsharded** [comment]
Moved this to the main Conan repo, this is something we want to consider at the product level, not only at the docs.

**Comment by Jochen0x90h** [comment]
Thanks for making this a thing for the next milestone. My quick-fix solution will simply be manually uploading the 5 or 6 dependencies that I actually have, but some automated solution would be nice.

**Comment by Jochen0x90h** [comment]
Maybe the conan upload command should have a profile option so that only the package matching the profile is uploaded. Currently there is only --all for all packages or you have to give the hash of the package.

**Comment by jgsogo** [comment]
```
conan info <path> -n None
```

will give you almost what you are looking for:

```
eigen/3.3.7@conan/stable
jasper/2.0.14@
conanfile.py (app/None)
```

**Comment by memsharded** [comment]
> conan info <path> -n None

This will potentially add many lines in the output, related to the download of recipes, so parsing this output might be ugly. Using the ``conan info <path> -n None --json=file.json`` outputs everything in the json, but getting the information from there wouldn't care about extra fields, but still requires a bit of parsing code to extract the dependencies.

I have been thinking about it and it doesn't seem there is a short term immediate solution, so nothing we can do for 1.29. As I currently see it, maybe the best could be:

- The problem doesn't live in the ``conan upload`` itself. We could keep it accepting a single pattern and the user iterating over several references, or we could try to modify it to allow multiple references to be uploaded. The first case is good for CI or automated usage, the second one seems better if we want developers to upload things. As for most cases, developers shouldn't be directly uploading packages, except on exceptional occasions, it seems keeping the current 1 argument could be good enough.

- The problem lies in the definition/computation of "what needs to be uploaded". Lockfiles are getting more relevance, and they have features (like the "modified" flag) that summarize evolution, so that could probably be leveraged. Then maybe a ``conan lock list-modified`` command that returns the list of references that have been modified, or maybe with ``--all``, the whole set of dependencies, so that could be passed to the ``conan upload`` command would be good enough.

What do you think? 

cc/ @czoido as leader of the new CLI 2.0

**Comment by jgsogo** [comment]
> > conan info < path >  -n None
> 
> This will potentially add many lines in the output, related to the download of recipes, so parsing this output might be ugly.

This is the typical command you always run two times and parse the output from the second one

-- 101 CLI hackers course 😄

**Comment by memsharded** [comment]
Lockfiles in 2.0 will be a simple json files with some lists "host", "build" of dependencies. It can be perfectly used by some CI to define that those things can be uploaded.

Conan 2.0 also got the concept of ``deployers``, writing one that will output a list of dependencies should be very easy. In any case, I still think the best approach is to get the json output of the commands and get the information from there, there is no much advantage of outputing a flat text file with the information that is there. But if still desired, a ``deployer`` is most likely the way to go.
