### ISSUE TITLE
Wrong `conanbuildinfo` line ending on Windows

### ISSUE THREAD

**Issue by KindDragon** [conan-io/conan#74]
Conan generate file with LF line ending

**Comment by memsharded** [comment]
Yes, thanks for telling, it is true, not only for conanbuildinfo, but I'd say that all other files, output info... most of them are generated with LF always, irrespective of the OS. This can be fixed, but from my experience it introduces other problems and issues, for example more complexity in testing, with tests checking files or output, typically failing in other platforms, etc. For conan usage, this is not a problem, conan, cmake, and other tools are able to process it properly. Also, most modern editors and IDEs can also deal with LF in windows without problems. I'd like to know a bit more about the actual problem, if it only affects you for that "conanbuildinfo" file, or any other side effect or failure.

**Comment by KindDragon** [comment]
Just hard to read these files with Windows Notepad.

**Comment by memsharded** [comment]
I see... not sure what to do with this issue. Actually it could be a lot of work, and the gain is low, as those files are rarely read. On the other hand most windows developers (I develop 50/50 win/linux) use other lightweight editors instead of Notepad, besides the full featured IDEs. Is there any reason you don't use VSCode, Atom, Sublime, or even Notepad++ to open .txt or .cmake files? I strongly recommend using any of them, instead of the Notepad, the gains are very large (syntax highlighting, zoom, even auto-completion, and many other features), so it always pays off. It is really important for you to use Notepad or do you have restrictions about the other editors?

**Comment by KindDragon** [comment]
No so much. I just tried use conan on freshly installed OS with only Visual Studio installed.
I think this bug should stay but with low priority.
It may also be important on build agents with minimal software installed, when you try to debug build errors.

**Comment by memsharded** [comment]
Released in 0.7, and tested. Not only **conanbuildinfo.cmake**, but all generated files (with conan generators), and **conaninfo.txt** too. I am closing the issue, but if you experience any problem, please tell me or re-open it, thanks!

**Comment by KindDragon** [comment]
Nice!
