### ISSUE TITLE
[bug] Build modules not exported when using new xbuilding feature

### ISSUE THREAD

**Issue by mjvankampen** [conan-io/conan#7414]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: GCC 8.1.0 (MinGW)
  * Conan version: 1.27.1
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)

Consume the flatc package as a build_requirement when using --profile:host and --profile:build. The BuildFlatBuffers.cmake build module is not available as normally you get it through Findflatc.cmake which sets the correct module path and includes the right file.

I'm not sure if this requires a change in the xbuild, or in the [package](https://github.com/conan-io/conan-center-index/blob/master/recipes/flatc/all/conanfile.py)? I think you can fix it in the package but that is quite ugly.

@jgsogo do you know?

**Comment by jgsogo** [comment]
Hi, @mjvankampen 

When you are consuming a build-requires using two profiles, the files `xxxxx.cmake` for the build-requires are not generated. Those packages belong to the _build_ context and you are not expected to consume them in your build-system (include, link), only executables would be available (build-requires like `cmake`, `gcc`, `protoc`,... you want the tools, not the libraries that are compiled for a configuration different from the _host_ one).

**Comment by mjvankampen** [comment]
That seems reasonable. But I am still not entirely clear on what the best way to consume these packages in for example cmake is. I guess you would do ```find_program``` for flatc. I'm just not sure how you would use any cmake scripts that come with the package, scripts you use when building. Normally your ```find_package``` can take care of this. Is this now a thing for the virtualenv to do (add it to your cmake_module_path)? 

For example this cmake file https://github.com/google/flatbuffers/blob/master/CMake/BuildFlatBuffers.cmake

**Comment by jgsogo** [comment]
(I'll use `protobuf` as example because it is the library I have used most, but I'm pretty sure `flatbuffers` uses exactly the same approach).


Yes, this is a CMake problem related to cross-building: the package you find with the `find_package(protobuf)` provides the libraries to link and the `protobuf_generate_cpp` macro, this macro uses `protoc` executable to generate the sources from the `.proto` files (FlatBuffers uses the same approach).

The problem is the `protoc` executable. You certainly need one that runs in your _build_ machine, so it cannot be the same you find with the `find_package(protobuf)` (these are the libraries/executables/files for your _host_ machine). Here, `protobuf` itself forces you to use `protobuf::protoc` target ([link](https://github.com/protocolbuffers/protobuf/blob/1b18833f4f2a2f681f4e4a25cdf3b0a43115ec26/cmake/protobuf-config.cmake.in#L130)) which is the actual target found after the `find_package(protobuf)`. This is not going to work in a cross-compiling scenario.

One way to relax this restriction is to use `protoc` and let the operating system find the executable by name. At least you are not forcing it to use the executable for the _host_ context, but in turn you need to populate the `PATH` with the proper values so the `protoc` you need is found. This is what we do in the Conan recipe ([link](https://github.com/conan-io/conan-center-index/blob/7f2a200e121d0a206030aee7afbe1399e2247249/recipes/protobuf/all/patches/protobuf-3.9.1.patch#L220)), we are populating the environment and running `protoc .... <args>`. That way, if Conan populates the environment with the PATH to the executable that is built for the _build_ machine, it will be able to execute it and generate the sources.

So, you need something like this:

```python

class Recipe(ConanFile):
   def requirements(self):
      self.requires("protobuf/<version>")

   def build_requirements(self):
      self.build_requires("protobuf/<version>")

   def build(self):
      # If you are using two profiles, here the PATH already contains the path to the `protoc` from the build context
      self.output.write(os.environ["PATH"])
      cmake = CMake(self)
      cmake.configure(...)
      cmake.build(...)
```

And you need two profiles. Let's say you are working in Windows and you are generating binaries for Linux, then you will use:

```
conan create <conanfile.py> --profile:host=Linux --profile:build=Windows
```

---

I'm not sure if `flatbuffers` recipe is as mature as `protobuf` one, but both should use the same tricks and/or workarounds... l

---

There are still some issues related to Macos and SIP protection. Here you can find a nice workaround for this issue (for `flatcc` recipe): https://github.com/conan-io/conan-center-index/pull/2129/, if Macos and shared, it runs `flatcc` from the Conan recipe instead of running from inside CMake.

**Comment by mjvankampen** [comment]
Ah I see, so any cmake files are put into the host machine context and the binary in the build context. This feels a bit like cheating but it does make sense. I'll have a look at the protobuf package and I'll try to update the flatbuffers package.

**Comment by mjvankampen** [comment]
Looking at the protobuf example using protobuf as a require and build_require both include protoc for your platform correct? So in your example it will build protoc for Windows and for Linux, even though Linux (your host) doesn't need protoc?

For me that is tricky as I cannot build the package everytime for the platform I cross-compile to as it won't always work. In addition it seems not very efficient.

So I tried on a simpler package first (pc-lint plus a static analyser). It is basically an executable with a cmake file to help integration into cmake. I now try to detect if the package is used as a build_require (this builds the package with the executable, in this case downloads it) or a require (only packages the cmake file and deletes os and arch). It seems to work but I don't know how robust it is. It has hard to see which binary contains what. I tried using an option but that doesn't seem to work as you need to set it beforehand, is there a way to autodetect and set an option? I thought config_options() but couldn't get that to work. Do you have any tips?

```python
    def configure(self):
        settings_target = getattr(self, 'settings_target', None)
        self._build_require = settings_target is not None
```

Maybe I am doing something conan isn't build for, but now it contains all my build tools which is very nice, but based around os_build and arch_build (which do generate the FinXXX.cmake ones.

[edit]

Seems I lied the below works fine.

```python
    def configure(self):
        settings_target = getattr(self, 'settings_target', None)
        self.options.build_require = settings_target is not None
```

I think this is something you could also apply to the flatbuffers recipe (maybe change the name of the option and allow the user to override somehow). What do you think?

Something like this https://github.com/conan-io/conan-center-index/compare/master...mjvankampen:flatbuffers-flatc-integration

Please excuse the code style, but I think the general idea is clear. It works at least.

**Comment by mjvankampen** [comment]
Something like this https://github.com/conan-io/conan-center-index/compare/master...mjvankampen:flatbuffers-flatc-integration

Please excuse the code style, but I think the general idea is clear.

**Comment by mjvankampen** [comment]
Final question, would this also require a rewrite for packages such a gtest? For example https://docs.conan.io/en/latest/devtools/build_requires.html?highlight=gtest
