### ISSUE TITLE
[bug] deps_cpp_info doesn't get updated for editable packages

### ISSUE THREAD

**Issue by cguldner** [conan-io/conan#7417]
I have the same directory layout as described in #6896

On Conan 1.27.1, I'm trying to use editable packages in my recipes. For one of my recipes, I have a package that I need to copy over some of the source, so I use
```python
self.run("cp -r {} repo1".format(self.deps_cpp_info["repo1"].rootpath))
```
I put repo1 into editable mode, using a layout file that looks like
```jinja
[source_folder]
../../repo1
```
However, when my `cp` command above runs, I get
```
----Running------
> cp -r /accts/cguldner/devkit/recipes repo1
-----------------
```
but I would expect to see 
```
----Running------
> cp -r /accts/cguldner/repo1 repo1
-----------------
```

Am I doing something wrong, or is there a bug here?

**Comment by Ext3h** [comment]
Facing a quite similar issue. It does not appear to be possible to inject a different `rootpath` using layout files in any form.

Where as with a non-editable packages `cpp_info.rootpath` is derived from the original `self.package_folder`, and points to the installed package folder, with an editable package it points to the recipe instead.

Is there any specific reason as to why `rootpath` is not in the whitelist?:
https://github.com/conan-io/conan/blob/f230bf104842c160be6ea377497151fe1ea64c38/conans/model/editable_layout.py#L36

Respectively, and good reason why `package_folder` can't be specified the same way `BUILD_FOLDER ` and `SOURCE_FOLDER` are? (Which coincidentally renders all the other directories redundant for the workflow described next.)

In understand that the current set of whitelisted properties is sufficient to e.g. let the bin/lib/include directories etc. point into the source tree + compilation targets.

However, the set of properties is *not* sufficient to reflect workflows requiring the *install* step to produce a *consumable* package.

E.g. in combination with the CMake generator, and a standard CMake workflow, `CMake.install()` is necessary to  populate the `package` folder. The equivalent call to the install target is all well integrated with most IDEs (since editable mode is supposed to work without conan during development,  post-setup!).

But "editable" mode does not allow reusing the (standard) package folder layout for an out-of-source build, by simply specifying where the package folder is.

**Comment by memsharded** [comment]
``dep_cpp_info`` was removed in Conan 2, closing as outdated.
