### ISSUE TITLE
[question] Inconsistent behavior in the installation of the build_requirements when using the - profile:host and the old -pr flag

### ISSUE THREAD

**Issue by anagno** [conan-io/conan#7423]
Here is a simple demonstration example.

The conanfile.py:

```
from conans import ConanFile, CMake
import os


class TestPackageConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake_find_package"

    def build_requirements(self):
        self.build_requires("libxml2/2.9.9@#98c13df03fac70408756b07364074446")

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

The CMakeLists.txt file:

```
cmake_minimum_required(VERSION 2.8.11)
project(test_package)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_BINARY_DIR}")

find_package(LibXml2 2.9 REQUIRED)
find_program(LIBXML2_XMLLINT_EXECUTABLE xmllint REQUIRED)

add_executable(${PROJECT_NAME} test_package.cpp)
```

and the test_package.cpp program:

```
#include <iostream>

int main(int argc, char **argv)
{
    std::cout << "hello wordl";
    return 0;
}

```

The profile I am using is:

```
[settings]
os=Linux
arch=x86_64
cppstd=17
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release

[options]
[build_requires]
[env]
```

When I am using the old syntax:

```
conan install ../test_package/ -pr linux_build
conan build ../test_package/ 
```

everything compiles fine and the FindLibXml2 is generated without a problem.

But when I am using the new syntax:
```
conan install ../test_package/ --profile:build=linux_build --profile:host=linux_host
conan build ../test_package/
```

then the Find... cmake files are not generated.

This is a problem only in the case of libraries that you have to compile natively and at the same time you would like to cross compile them for an another platform. 

In this case I would imagine that you would define your profiles as suggested in the documentation (https://docs.conan.io/en/latest/devtools/build_requires.html#build-and-host-contexts). But for the natively build you would just use the same profile with the build profile. 

Am I missing something? Is it normal the build_requirement not being install with conan install ?

Kind regards,

Vasileios

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @anagno 

I think what you are reporting is the expected behavior.

Build-requires are for build tools that are only necessary at compilation time, and are not part of the final binary. By definition, they do not affect the package-id (this might change in the future Conan 2.0), because in theory they do not affect the final binary. The typical examples of ``build_requires`` are ``cmake`` or ``7zip``. Using a library as ``build_requires`` is not the intended usage, as is not recommended.

When you are using the ``--profile:build``, this spans a new context that will contain only build tools, and there are no libraries to be found with ``find_package``. However, there could be virtualenvs to run executables in those build_requires.

So the main reason seems to be that you are slightly abusing ``build_requires`` for something that was not designed for. We are aware of some limitations and will try to improve the graph model and requirement definition, but at the moment we would recommend to use normal ``requires``, and if needed, manage/control things at the build-system level

**Comment by anagno** [comment]
Hello @memsharded,


I have a couple of use cases that find_package could be used for including build tools:

* The first case is the one (more ore less) described in the pet example. libxml2 also comes with some tools and executables. So using find_package to be able to locate these tools is necessary. These tools are only used in the UTs. So they are not influencing the final binary. In a native build, you can also activate the these tools. When cross compiling you de-activate the UT. So in general, libxml2 should not be visible in the dependencies. I am guessing, in this category belong all the tools that can generate code that is included for generating the final binaries. This case, I am guessing, can also be addressed by removing the dependencies in the package_id ?!

* Another use case, that I have seen in production, is the creation of C interfaces from C++ libraries. For reasons (too complicated to explain), we had some projects that had to use different versions of the same compiler. But we wanted to share a common C++ library between these projects. That library did not want to maintain compatibility with really old compilers. So what we ended doing, was creating an extra library that included the C++ library and exposed a C interface with only basic types (i.e. int, bools, etc). So the C++ library was a private dependency of the new C library. The projects that could use the modern compilers were using the C++ library directly. The projects which could not, were using the C library. Probably this is also an extreme example, but if you are careful (i.e. naming of dlls and the dlls coming from your dependencies and a million other problems) it can be done. Should be this case be treated again in the same way, i.e. having it in the requirements list and then deleting it from the package_id?

* Finally an extremely hacky thing (even for the CMake standards -- and it is the use case of https://github.com/conan-io/conan/issues/7421). A 2 step build. In the first step, you are producing binaries that you are using in the 2nd step to create code, that is being included in the final binary. Theoretically the 1 first build step, could also be it`s own library. (I do not know if it is a valid use case. It could also be a pet project that has gone down the wrong path :) ) 

I am guessing that all these use cases are not intended for the build_requires. I though that build_requires are the dependencies that do not influence the signature of the final binaries. But probably this definition is too wide. Should I consider build_requires dependencies that can be access through virtualenv ?


If yes, then why when we are using the old syntax (i.e. `-pr linux_build`) somehow we end up also with the Find... cmakes of the build_requires ? Is it a bug?

Kind regards,

Vasileios

**Comment by anagno** [comment]
Probably one more category are UT frameworks. I do not think that the version of the GTest (or whatever framework someone is using), will influence the final binary. But probably you can not really replace it with any version of GTest during compilation of the library.

**Comment by anagno** [comment]
In the end, I found the mistake! So, I am documenting it for the next person that has a similar question.
In my case the problem was the 
```
find_package(LibXml2 2.9 REQUIRED)
```
The find_package forces the context and although technically I was not using the library anywhere, it is consider to be in the host context. My mistake was that I thought that it was necessary to call afterwards the 
```
find_program(LIBXML2_XMLLINT_EXECUTABLE xmllint REQUIRED)
```
However, I can call directly the `find_program` without the `find_package`. All the paths for the binaries are being imported correctly by conan. 

In general, I think that all the scenarios that I am mentioning are being cover by the existing tools. Even for my use case of 2 step cmake build, the build_requires seems to be working correct (when Cmake is used correctly).
Thanks for the comments! The push me towards the right direction to find the problem!

**Comment by Nipheris** [comment]
@memsharded I think I have got the idea about separate graph for all the build requirements, but anyway, we have `build_paths` and `build_modules_paths` in [deps-cpp-info](https://docs.conan.io/en/1.28/reference/conanfile/attributes.html#deps-cpp-info), that are NOT considered by the generators, when the build requirement is moved out to separate context using `--profile:build`. 

Looks like a bug in `cmake*` generators (and maybe the others too), because `build_paths` and `build_modules_paths` is for *build-time* tools and scripts by-design. What if I have a package containing ONLY build scripts for CMake? It should go to `build_requires` I think. This is our use case at this moment.
