### ISSUE TITLE
[bug] conan search should error if both -rev and -q  are set

### ISSUE THREAD

**Issue by timbrown5** [conan-io/conan#7434]
If I run a search with `-q` without `-rev` I get the expected result, which is only packages matching that query are returned. If I run it with `-rev` I get a list of all packages returned, regardless of if they match the query.

### Environment Details (include every applicable attribute)
  * Operating System+version: Mac 10.15.5
  * Compiler+version: 
  * Conan version: 1.27.1
  * Python version: 3.7.0

### Steps to reproduce (Include if Applicable)
If I run a Conan search with an invalid query (one which should return nothing), I get the expected message, saying there are no packages.  
```
conan search boost/1.70.0@conan/stable -q  'os=Macos AND arch=x86_64 AND compiler=ugabuga' -r conan-center
Existing packages for recipe boost/1.70.0@conan/stable:

Existing recipe in remote 'conan-center':

There are no packages for reference 'boost/1.70.0@conan/stable' matching the query 'os=Macos AND arch=x86_64 AND compiler=ugabuga'
```

If I run it with the `-rev` flag, I get a package erturned, which is not correct:
```
conan search boost/1.70.0@conan/stable -rev -q  'os=Macos AND arch=x86_64 AND compiler=ugabuga' -r conan-center
Revisions for 'boost/1.70.0@conan/stable' at remote 'conan-center':
0 (2019-09-10 09:56:30 UTC)
```

**Comment by memsharded** [comment]
Yes, this is true, at the moment the ``--revisions`` argument is incompatible with the ``-query`` one the reason is ``revisions`` listing is prioritized. For a search 2 revisions can be listed:

- ``conan search <ref> --revisions``: list the recipe revision of <ref> (``pkg/version@user/channel``). These revisions are independent of the settings, and options, query cannot apply here
- ``conan search <pref> --revisions``: list the package revisions of <pref> (``pkg/version@user/channel:package_id``). As the settings and options are the things that are encoded into the ``package_id``, it doesn't make much sense to do a query over this list of revisions either, as all revisions there would match or any would match the query.

So what can be done:

- Right now, raise an error if both arguments are passed.
- In CLI 2.0 (which has already started, and has some initial proposal for some commands), make sure that the commands are completely clear and incompatible arguments are avoided (cc/ @czoido )

**Comment by timbrown5** [comment]
So is there no way to find a list of packages RREVs which are applicable for our profile? Seems like this would be useful?

I have tried doing:
```
conan search llvm/9.0.0@graphcore/stable -r graphcore-conan -q 'os=Macos AND arch=x86_64'
Existing packages for recipe llvm/9.0.0@graphcore/stable:

Existing recipe in remote 'graphcore-conan':

    Package_ID: f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2
...
conan search llvm/9.0.0@graphcore/stable:f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2 -rev -r graphcore-conan
```
as you said above, this fails with
```
ERROR: Specify a recipe reference with revision
```

**Comment by memsharded** [comment]
> So is there no way to find a list of packages RREVs which are applicable for our profile? Seems like this would be useful?

No, this doesnt seem a use case. You need to find the ``package_id``s that are applicable to your profiles. Revisions are changes in the source code or build, but not variants of the configuration. The RREVs or recipe revisions apply to all configurations, so cannot be queried, and all the PREVs or package revisions of a given ``package_id`` will have the same configuration, so a query there seems useless. 

You can get the list of PREVS of a given RREV with:

```
conan search llvm/9.0.0@graphcore/stable#RREV:f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2 -rev -r graphcore-conan
```

**Comment by timbrown5** [comment]
Thanks for the feedback. I think we are going to try looping through each of the RREVs to see if there is a package for our query in there by doing:
`conan search llvm/9.0.0@graphcore/stable#RREV -rev -r graphcore-conan`

We looked at doing `conan search llvm/9.0.0@graphcore/stable#RREV:f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2 -rev -r graphcore-conan` as you said, but we would have to find both the Package_ID and RREV before looking and seems like a step we don't need as we need to loop through the RREVs anyway.

**Comment by timbrown5** [comment]
I think the workflow we have above will work for us. I think (as you said) the issue is that it silently ignores one of the flags. I have updated the title as per your previous comment.
> Right now, raise an error if both arguments are passed.

**Comment by AbrilRBS** [comment]
While we're not planning on releasing any new features for Conan 1, we can mark this as solved in Conan 2 with the recent addition in Conan 2.2 of the `--filter` args in `conan list`
