### ISSUE TITLE
[feature] Additional --build functionality for build_requires and requires

### ISSUE THREAD

**Issue by Lizabeth-Roberts-Bose** [conan-io/conan#7450]
There are really two types of dependencies and requirements modeled in conan, `requires` and `build_requires`. As noted in the conan documentation, these are intended for different purposes, however once you include either they get added to the graph in roughly the same way meaning they are treated basically the same from the perspective of most recipes. This is great for some purposes but not others.

I would like a way to build only my `requires` and leave my `build_requires` alone when performing a full graph build using `conan install <conanfile> --build` 

An example of what to implement could look something like `conan install <conanfile> --build=requires`

This would be extremely useful because it usually doesn't make sense to recompile or re export and package `build_requires` considering they are supposed to be build "tools" such as compilers and other such executables or packages. 

As an example of my use case, I have a custom compiler I import as a build requires. The only thing this recipe does is package the compiler and its requirements. It doesn't make sense to build this and re package it as part of an install command

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Sorry this was not responded back then.

Now, the recommendation would be never do something like ``--build=<pkg>``  except when clearly determined by ``conan graph build-order``. Otherwise, ``--build=missing:<pkg>`` or ``--build=missing`` would be way better, and it will not unnecessarily re-build what already exists.

Closing this ticket as not necessary, but please re-open or create new tickets if necessary for any further question or feedback. Thanks!
