### ISSUE TITLE
[question] Share python code to consumer recipe without python_requires

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#7463]
Original question from https://twitter.com/tonka_2000/status/1289151762264461312?s=20

I search for ways to share a python code with my recipe without the `python_requires` mechanism.

## My scenario
I have a bigger project (150+ shared libs) where I use conan to make it easy for the consumer to use our project (btw: thanks you for conan components), which works great. But what I see over time is that more and more consumers need to "duplicate" alot of code their conanfile.py. We need to do some heavy lifting in the `imports` method, because most of the time consumers build plugins for the main application and need a full copy of that application locally (we support multiple compilers, so there are multiple versions of the main application in different compiler versions at the same time), which we do with the `imports` method and it works really well (always copy with `self.copy` to f.e. `_mainapp` directory). We need to do this because we have additional non C++ files which are required for our loading mechanism and some other stuff too.

## My goal
So what I wanna do is to provide some helper functions (or maybe a whole Conanfile class) to the consumer conanfile so that we can get rid of the duplicated code (sometimes the code is not a exact copy but rather a slightly different version thanks to copy and paste).

## Options
As far as I know I have multiple options:
* use `python_requires`<br>
  I use that in other projects as well but in this project I have the problem that the helper code change sometimes alot from version to version, and I dont want to maintain a second repo just for the helper. I'm not sure if I should create the helper in a subdirectory of the main project and make a second export in the CI, but this does not feel right to me.
* use `tools.pythonpath(self)`<br>
  @danimtb already suggest that on my tweet. I use this mechanism already but I'm not sure if it also works in the `imports` method (I remember that this technic has some limitations back then, but maybe they are gone in more up2date versions of conan). Also I'm not sure if this mechanism will also be included in conan 2.0, because I think there was an issue about that topic.
* option https://docs.conan.io/en/latest/howtos/python_code_reuse.html#sharing-a-python-module<br>
  But this section is not 100% clear to me how it works.

So I'm searching for some hints and tips how to solve that kind of scenario which maybe also exist in conan 2.0.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @tonka3000 

- ``tools.pythonpath(self)``

Probably not. It is likely it will be removed, and in any case this enable the pythonpath to modules living inside other Conan packages, that needs to be there. So if you are going to depend on another Conan package, sounds ``python_requires`` will be better.

- https://docs.conan.io/en/latest/howtos/python_code_reuse.html#sharing-a-python-module

This is about exporting a .py file together with your recipe. Every package will contain a copy of that file at the moment of package creation. There is no magic, just a copy of some python code inside each package. It sounds doable, and maybe with the new ``export()`` method, you can export from a known local relative path without too much issue. Probably still need some kind of import fallback when you are in local development (``conan install``) and for the Conan cache (``conan create``)

- use ``python_requires``

This seems like the best approach to me, but I don't fully understand your use case yet. If you have the code that is going to be reused changing often, you can keep bumping the version of the ``python_requires`` that you are using. Consumers will be requiring a pinned version, so they can gradually adopt the new ones, or they could use version-ranges to automatically upgrade to newer versions. Besides, you have control over when do you want your helper bumps to force a re-build of the packages using it, with the ``default_python_requires_id_mode``


Please let me know a bit more about your use case, so I can understand the friction of the ``python_requires``. Thanks!

**Comment by tonka3000** [comment]
Hey @memsharded ,

my answer is a little bit late, but I'm working now to make my python code reusable.

I try the `python_requires` approach (I use the same recipe `MyBase` as in your [docs](https://docs.conan.io/en/latest/extending/python_requires.html#extending-base-classes)) because it make a lot of sense now. I just export my helper recipe (conanfile in a subdirectory of the project repo) in my CI step which has the same version as the project.

Most of `python_requires` the stuff works great, but I already learned that I can not use the `requires` mechanism (or the `requirements` method). My Idea was that I require the helper via `python_requires` and this will require the original project, so that I can make sure that the helper and the project always has the version in sync (e.g. `helper/0.1.0@` and `project/0.1.0@`). I don't like this approach because I only want to use my project and get the helper in the same move but when I have to recipes I need to make sure that the 2 versions are in sync. I can try some regex magic with python on the project recipe path but when the project is required indirectly via another project this would not end up with the same version because I don't know which version of the project is behind the required project before the whole dependencies are evaluated.

So I'm not sure which option I have left for that case so that I can make sure that the helper version always match the project version, any ideas?

My perfect solution would be that I can write my helper class `MyBase`  above the original conanfile class in the same `conanfile.py` so that I have just one recipe and I can ship the helper as well. I will also be easier to test my helper in `test_package` because I will only need one command line call.

```py
class MyBase(object):
    def build(self):
         print("build")
    # ... 

class Project(Conanfile):
     name = "project"
     version = "0.1.0"
     # ....

     def build(self):
           print("build project source")

```

and the consumer can use it like a normal `python_requires_extend`

```py
class Pkg(ConanFile):
    requires = "Project/0.1.0@zkw/develop"
    python_requires_extend = "Project.MyBase"

# ....

```

Greetings

Michael

**Comment by memsharded** [comment]
Hi @tonka3000 

The good thing is that you could do both, ``python_requires`` are independent from regular requires. So something like this might work:

```python
class Pkg(ConanFile):
    project_dep = "Project/0.1.0@zkw/develop"
    requires = project_dep
    python_requires = project_dep
    python_requires_extend = "Project.MyBase"
```

(Please also note that you should be using lowercase package names whenever possible, it is very likely that this will be required for Conan 2.0)

However the above has a big problem, if the ``requires`` is overridden from downstream, to something newer, like ``project/0.2.0@zkw/develop``, only the normal ``requires`` will change, but the ``python_requires`` will still be the older one, it will not be overriden.

The thing with ``python_requires`` is that they are processed in an extremely different way to normal requires, in order to be able to do the ``python_requires_extend``, so it is basically impossible than a normal ``requires`` can be used in that way. Moreover, it is very useful and make sense that a python_require is separated in its own package. For example, the way they affect the ``package_id`` is different, and is controlled by a different mode (``default_python_requires_id_mode``), which allows a better versioning scheme for python_requires than for C++ libraries.

So even if it is initially a bit less convenient, because it is needed to create one recipe for the python_requires and another for the recipe, but it will be better when some changes are required to the python_requires, and you can easily decide if you want to rebuild binaries of packages using that python_require.

**Comment by tonka3000** [comment]
The first version would be nice but the downsides is not really good. 2 recipes has the same downside as far as I can tell but there is more control over the `python_requires` package. So there is no real option to guarantee that the 2 versions will be the same AFAIK.

`python_requires` packages don't have any binary (only .py files), so the only way to change the package id is to change the version, right?

So the only option left for me is to decouple the version of the helper and the project. In this way I would manage this in a separated repo (why should I keep it in the same, any benefits?). The only real downside is that the recipe consumer don't know the exact version he/she should use and the recipe needs to handle the different version in one recipe (via `self.version`). This seems to be same situation (the version number) as with conan and [cmake-conan](https://github.com/conan-io/cmake-conan).

**Comment by memsharded** [comment]
Sorry this was not followed up since then.

> python_requires packages don't have any binary (only .py files), so the only way to change the package id is to change the version, right?

Yes, correct, changing the version of the python-requires is what affects the ``package_id`` of its consumers

> So the only option left for me is to decouple the version of the helper and the project. In this way I would manage this in a separated repo (why should I keep it in the same, any benefits?). The only real downside is that the recipe consumer don't know the exact version he/she should use and the recipe needs to handle the different version in one recipe (via self.version). This seems to be same situation (the version number) as with conan and [cmake-conan](https://github.com/conan-io/cmake-conan).

Not sure what you mean here, about the versions. It is possible to use version ranges ``python_requires = "mytool/[>=1.0 <2]"`` for automatic resolving to the latest within a range, and that would align automatically. In any case, it is totally expected that the versions can be separated and in practice this is the most common case we see in users, nothing wrong with it. 

I am tentatively closing the issue as stale, but please dont hesitate to create new tickets for further clarifications or questions.
