### ISSUE TITLE
[bug] Recursive, infinite imports

### ISSUE THREAD

**Issue by UnderSampled** [conan-io/conan#7468]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 
  * Compiler+version: N/A
  * Conan version: 1.22.1
  * Python version: 3.7.6

### Steps to reproduce (Include if Applicable)

1. Create a conanfile.txt which imports files from another package's @bindirs into 'bin/Release': `@bindirs, *.dll -> bin/Release @`
2. Run `conan install ..` from a build folder
3. Check the bin folder: it should contain one set of the imports
2. Run `conan imports`
3. Wait some amount of time while it seems like the imports has hung
4. Check the bin folder: it now contains a matroska set recursive copies of the imports

**Comment by memsharded** [comment]
Hi @UnderSampled 


I have tried to reproduce this issue, but so far no success. I have implemented this test following your instructions: https://github.com/conan-io/conan/pull/7470/files, but it passes ok. Could you please have a look at it and let me know if I am missing something? Thanks!

**Comment by memsharded** [comment]
Hi @UnderSampled 

We just released Conan 1.28, but it is likely there might be a 1.28.1, and also planning for 1.29. It would be good to be able to reproduce this, did you manage to have a look at the test in https://github.com/conan-io/conan/pull/7470/files?

**Comment by UnderSampled** [comment]
I tried reproducing this again using my own directions, and found it would only happen when importing from one of my packages. I couldn't figure out what the difference between the packages were. Both use this construct:

```
    def package_info(self):
        if not self.in_local_cache:
            self.cpp_info.bindirs = ["build/" + str(self.settings.build_type)]
            self.cpp_info.libdirs = ["build/" + str(self.settings.build_type)]

        self.cpp_info.libs = tools.collect_libs(self)
```

While package that had the issue (when chosen as the package to import from) originally had been set up as an editable when I first saw the issue, I tried without the editable and it still had the issue.

Let me know if you have any ideas one what I should look for that might be a difference between these packages. This is not an open source project, so I cannot just share the files directly without some paperwork.

**Comment by memsharded** [comment]
Hi @UnderSampled 

While I see that using editable packages could be a cause of this issue, I have been checking the code and the above constructs, and still no clue how this could happen with packages from the cache. So I suspect that the editable thing was still causing the issue, and maybe even if you removed the editable, there was something still around causing the issue. 

Could you please make sure that this still happens, from scratch (you can try to setup a temporary local cache with CONAN_USER_HOME pointing to a local temporary folder), when not using editables? Make sure than both the consumer and the dependency packages are not under editable mode. If the consumer can be a ``conanfile.txt`` as you described above, instead of an actual package, much better, one possible thing less to check. Many thanks!

**Comment by memsharded** [comment]
Hi @UnderSampled 

Any news from this issue? I still have https://github.com/conan-io/conan/pull/7470 open with the test validating the basic behavior, and I could not reproduce it with editables.
Have you managed to reproduce the issue somehow, or do you have any new information? Thanks!

**Comment by memsharded** [comment]
This became obsolete, and I just closed https://github.com/conan-io/conan/pull/7470 PR:

- imports are being removed in 2.0, replaced with explicit copies from dependencies
