### ISSUE TITLE
No warning when overriding dependency

### ISSUE THREAD

**Issue by osechet** [conan-io/conan#747]
Let's imagine an application that depends on 2 libraries, `A` and `B`. Both `A` and `B` depends on a third library, `C`.
<pre>
app -> A/1.0 -> C/1.0
    -> B/1.0 -> C/1.0
</pre>

`B` and `C` are modified and a new minor version of both is released. The application is updated to use the new `B`.
<pre>
app -> A/1.0 -> C/1.0
    -> B/1.1 -> C/1.1
</pre>

When calling `conan install`, a warning is displayed saying there is a conflict. Fine: as the developer of the application I have to decide what I want to do.

First problem: the version of `C` used by conan depends on the order of the requires field. If requires is `"A/1.0", "B/1.1"`, conan uses `C/1.0`. If requires is `"B/1.1", "A/1.0"`, conan uses `C/1.1`. It lacks of consistency and could be an issue. Maybe the new version feature of 0.16 could be used to let conan choose the best version (with a warning).

Whatever, I know using `C/1.1` is not a problem for my project, so I decide to force it and I update requires to be `"A/1.0", "B/1.1", "C/1.1"`. When I call `conan install`, there is no more warning.
I think it's a problem because even if the dependency is forced, there is still a conflict and the developer should be warned about it.

**Comment by memsharded** [comment]
Yes, that is a problem. We didn't want to break backwards compat, so we introduced the ``--werror`` option, that will throw an error and stop instead of warn.

Once the developer decides to "override" a dependency, there is no more warning, do you think that should be a warning? Can be done. I think that the downstream has priority, if the app decides to use C/1.1, because everything is fine, then it is fine, shouldn't warn about it. Note that the "override" flag should be better used in the downstream to not introduce artificial unnecessary dependencies or to change the dependencies order.

What would be your suggested message? Something like the following?

```bash
WARN: A/1.0 was depending on C/1.0, but has been overriden from "app" to depend on C/1.1
```

**Comment by claasd** [comment]
Hi,

when was this introduced? I am testing a similar setup, using the --werror option and still only get a warning (btw., I am on Windows, using conan 0.16.1)
`conan install --build=missing  --werror`
`WARN: Version range '~=1.8' required by 'Logging/1.8.0@cab/testing' not valid for downstream requirement 'Commons/1.7.12@cab/testing'`

**Comment by memsharded** [comment]
The ``werror`` option was introduced a couple of versions ago, but yes, probably it is a bug, and the incompatible version range is using ``warn`` instead of ``werror``, we will check if it can be fixed.

**Comment by memsharded** [comment]
It seems that with @claasd PR #1082 both cases should now be covered with ``werror``, and the case of @osechet for normal dependencies should be also addressed. Marking this issue as fixed, but please tell otherwise
