### ISSUE TITLE
[feature] Add support for bindir in cmake_find_package_multi generator

### ISSUE THREAD

**Issue by steffenroeber** [conan-io/conan#7491]
Currently only lib and include dirs are supported by cmake_find_package_multi generator.
It would be nice, to have bindirs too.
For example: 
According to already working
set(Qt5_Core_LIB_DIRS_DEBUG "C:/.conan/88f0be/1/lib")
->
set(Qt5_Core_BIN_DIRS_DEBUG "C:/.conan/88f0be/1/bin")

**Comment by memsharded** [comment]
This issue was reporting the legacy CMake integration, which has been superseded by the new one in Conan 1.X https://docs.conan.io/1/reference/conanfile/tools.html, and removed in Conan 2.0: https://docs.conan.io/2/reference/tools/cmake.html. Closing this ticket as outdated.

Please update to use the modern CMake integration, and please don't hesitate to open new tickets as necessary. Thanks!
