### ISSUE TITLE
[feature] components to have a 'provides' attribute

### ISSUE THREAD

**Issue by fulara** [conan-io/conan#7497]
This is a thought that came up from this really: https://github.com/conan-io/conan/issues/7475

Since [provides](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#provides) now exists, it may make sense to include the provides attribute in the .components as well.

For cases when we have packages, that deliver multiple libs that conflict with one another.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Quick feedback: ``provides`` will be extremely challenging to be defined by .components, because they are provided at dependency resolution time. At that time the ``package_info()`` is not evaluated at all, as for that, the binaries need to be downloaded and installed. That is much later in the process. So ``provides`` is a graph definition thing, like versions, while ``components`` are a build definition thing, like include-dirs. They belong and are processed in very different places, and moving it to ``components`` seems too much work for the value.

**Comment by fulara** [comment]
Hello @memsharded! - I was only thinking of `provides` at a single level of artifact, wouldnt that make it a build definition thing? 
They wouldnt block `provides` globally, but only between same subset of components, hm.

Anyway, it was just a random thought - for this case actually I would go maybe with an option instead of component.

**Comment by memsharded** [comment]
> Hello @memsharded! - I was only thinking of provides at a single level of artifact, wouldnt that make it a build definition thing?
They wouldnt block provides globally, but only between same subset of components, hm.

Yeah, that might be possible, but that evaluation at the components definition would make checking the collision more complicated than the current one. I think it would be better to wait until there is strong evidence of this scenario becoming a big pain (note the provides is still only a UX thing). If this is a real use case most likely it will happen again in ConanCenter, so I would say we could close this one at the moment if it is not clear we should take action now.

**Comment by jgsogo** [comment]
Yes, let's see how it works at the recipe level first, so far we haven't hear anything from people finding these conflicts and trying to fix them (and it will require some _proxy_ recipes that we don't have right now).

I'm closing this issue as suggested, let's open it again in the future if needed.

Thanks!
