### ISSUE TITLE
[bug] Conan client always downloads package with different package ID

### ISSUE THREAD

**Issue by utkarshmani1997** [conan-io/conan#7511]
### Environment Details (include every applicable attribute)
  * Operating System+version: MACOS Catalina
  * Compiler+version: clang 10.0.0
  * Conan version: 1.25.2
  * Python version: 2.7.16

### Steps to reproduce (Include if Applicable)
Download any package dependency like following and it will not respect the provided package id but pull different package ID
conan download -r conan-remote libcurl/7.70.0@#598c88ea694ccb5b6e6bf63c7891abbc:02e07a808670bdb29227c92839975a19da32851e:82930cc751904b34065c601e948c666e

Instead of downloading 82930cc751904b34065c601e948c666e its downloading 95e7e05d811089f3cecfebf4e582bf89.

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
conan download -r conan-remote libcurl/7.70.0@#598c88ea694ccb5b6e6bf63c7891abbc:02e07a808670bdb29227c92839975a19da32851e:82930cc751904b34065c601e948c666e
Downloading conanmanifest.txt completed [0.23k]
Downloading conanfile.py completed [21.97k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
libcurl/7.70.0: Retrieving package 02e07a808670bdb29227c92839975a19da32851e from remote 'conan-remote'
Downloading conanmanifest.txt completed [0.79k]
Downloading conaninfo.txt completed [1.55k]
Downloading conan_package.tgz completed [3757.67k]
Decompressing conan_package.tgz completed [0.00k]
libcurl/7.70.0: Package installed 02e07a808670bdb29227c92839975a19da32851e
```

**Comment by czoido** [comment]
Hi @utkarshmani1997 ,

I tried to reproduce this with no luck. 

As I can see in the log the downloaded `package ID` is correct (`02e07a808670bdb29227c92839975a19da32851e`).
How did you check that you downloaded `package revision` `95e7e05d811089f3cecfebf4e582bf89` instead of `82930cc751904b34065c601e948c666e`?

Could you please do this to check which package revision you have downloaded in the local cache?

`conan search "libcurl/7.70.0@#598c88ea694ccb5b6e6bf63c7891abbc: 02e07a808670bdb29227c92839975a19da32851e" --revisions`

That will output the package revision, if everything is correct after doing: `conan download -r conan-remote libcurl/7.70.0@#598c88ea694ccb5b6e6bf63c7891abbc:02e07a808670bdb29227c92839975a19da32851e#82930cc751904b34065c601e948c666e` the result should be: `82930cc751904b34065c601e948c666e`

Could you also please tell me which Artifactory version you are using.

Thanks a lot.

**Comment by utkarshmani1997** [comment]
Hi @czoido 

Thanks for the response,
Here is the output of search command
```
conan search "libcurl/7.70.0@#598c88ea694ccb5b6e6bf63c7891abbc: 02e07a808670bdb29227c92839975a19da32851e" --revisions
Revisions for 'None':
95e7e05d811089f3cecfebf4e582bf89 (No time)
```
and tried to download with given command but it displays package not found.
I don't remember how I picked up 82930cc751904b34065c601e948c666e (not sure if it is correct).
So closing for now, will open again if found this behaviour again.

**Comment by memsharded** [comment]
Hi @utkarshmani1997, @czoido 

I am confused, I get this:

```bash
conan download -r conan-center libcurl/7.70.0@#598c88ea694ccb5b6e6bf63c7891abbc:02e07a808670bdb29227c92839975a19da32851e#82930cc751904b34065c601e948c666e
Downloading conanmanifest.txt completed [0.23k]
Downloading conanfile.py completed [21.97k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
libcurl/7.70.0: Retrieving package 02e07a808670bdb29227c92839975a19da32851e from remote 'conan-center'
ERROR: Binary package not found: 'libcurl/7.70.0:02e07a808670bdb29227c92839975a19da32851e'
```
Then I am confused by the output:
```
Revisions for 'None':
95e7e05d811089f3cecfebf4e582bf89 (No time)
```
Having ``(No time)`` is very weird, I have a time, you should have a time if the package was downloaded.
