### ISSUE TITLE
[bug] build_requires for --profile:build profile does not respect build_requires

### ISSUE THREAD

**Issue by a4z** [conan-io/conan#7528]
### Environment Details (include every applicable attribute)
  * Operating System+version: OSX 10.15.6
  * Compiler+version: apple clang (not relevant for this problem)
  * Conan version: 1.28.0
  * Python version: 3.8.3

### Steps to reproduce (Include if Applicable)

create a default profile, name it default

install cmake/3.18.1@ for this profile

copy the default profile to default2

edit default2 and add a build requirement for the cmake pacakge, 
```
[build_requires]
cmake/3.18.1@

```

edit some-recipe, and add a `print (os.environ["PATH"].split(os.pathsep))`  , for example where cmake is configured, or in the build.

run
`conan create --profile:build default2 --profile:host default some-recipe`
 
check the output of the $PATH, the cmake package cmake is not in the path

`conan create --profile:build default --profile:host default2 somerecipe`

the cmake package cmake is in the path

I am pretty sure this is not how it is supposed to work, the cmake must be picked up from the build platform, therefore, for the profile that is used in --profile:build, and this is not the case

**Comment by lasote** [comment]
Where is the `print (os.environ["PATH"].split(os.pathsep))` located inside the conanfile? I mean, in which method?

**Comment by a4z** [comment]
> Where is the `print (os.environ["PATH"].split(os.pathsep))` located inside the conanfile? I mean, in which method?

I placed it, for example, here
https://github.com/conan-io/conan-center-index/blob/962e68014197a6553be7f2be5106a70617126790/recipes/paho-mqtt-cpp/all/conanfile.py#L62
and here
https://github.com/conan-io/conan-center-index/blob/962e68014197a6553be7f2be5106a70617126790/recipes/paho-mqtt-cpp/all/conanfile.py#L72

where the first one is the more important one, I guess

( I use this package because it builds fast, uses cmake, and I have all the dependencies on my system anyway
and I tested this also with real cross compilation, using this https://github.com/conan-io/conan-center-index/pull/1137 one)

**Comment by jgsogo** [comment]
Hi, @a4z 

When you add a build-requires to the a profile, you are telling Conan to apply that build-requires to all the packages affected by that profile. It is the same principle when you are adding an option like `*:shared=True` to a profile, it applies to every package _affected_ by that profile.

If you want to add a build-requires to packages in the _host_ context, you need to add it to the `profile:host` (indeed this would be the same profile you'd use if you were using only one profile). When you add the build-requires to the `profile:build` it applies to all the packages in the _build_ context.

In your use case:

* 
   ```
   conan create --profile:build default2 --profile:host default some-recipe
   ```

   it is applying the `cmake` build-require to packages in the _build_ context. Unless, `some-recipe` has declared build-requires, the CMake package won't be used at all.

*
   ```
   conan create --profile:build default --profile:host default2 somerecipe
   ```

   Now `cmake` is declared as a build-require in the `profile:host` profile, it will be applied to packages in the _host_ context, so it is applied to `some-recipe`.

**Comment by a4z** [comment]
hm, ... OK, but what about 

say I have a build requirement
and this is not on my machine, (but a recipe can be found on a remote) 
and I say --build missing when building something, that requires the build_requirement, for a --profile:host

which profile is applied when the build requirement is build? the --profile:build one, or some default one? 
what if a build requirement would have some options I want to set, like use openssl or not, how would this be done? 
and what if I would like to configure openssl, but differently than for the host

would it not make more sense to separate everything what is on the host in the host profile, and everything for the build in the build profile? (I know this is a rhetoric question since the implementation is already done and will not change)

**Comment by jgsogo** [comment]
>  (I know this is a rhetoric question since the implementation is already done and will not change)

Implementation is there, but it is still an experimental feature and, with Conan 2.0 in the horizon, it is the best moment to receive any kind of feedback and consider breaking things for the better 😉 

---

Conan won't always be used in a cross-building scenario, for the regular scenario we can agree that the UX should be easy enough and something like: `conan create <my-lib> --profile=Windows` should be enough to build a `my-lib` in the Windows machine where I'm running Conan.

The recipe for `my-lib` can contain a build-requires, let's say it needs `strawberryperl` or `protoc` or something else. The recipe `my-lib` would contain a line like `build_requires = "strawberryper/1.0"`, but according to the previous statement it should work using the naïve `conan create <my-lib> --profile=Windows`.

If it were `cmake` we would add it to the `Windows` profile under a `[build_requires]` section, still the same command would work: `conan create <my-lib> --profile=Windows`, because I'm running on Windows and building for Windows.

---

Now let's crossbuild (easy one). I will build `my-lib` for ARM from my Windows machine. My recipe contains a `build_requires = "strawberryper/1.0"` so I need to provide settings for both machines:

```
conan create <my-lib> --profile:host=ARM --profile:build=Windows
```

 * `profile:host=ARM` applies to `my-lib`.
 * `profile:build=Windows` applies to `strawberryperl` declared inside the recipe.

---

One more step, now we want to use `cmake` from a Conan package. We don't want to modify the recipes, so the only option is to add it to one profile, which one?
 * if we want to use `cmake` to compile `my-lib` I would add it to the `profile:host=ARM` under the `[build-requires]` section. It is a build-requires of `my-lib`, but it uses the settings from the `profile:build` (exactly the same as the other build-require that is already declared in the recipe, the `strawberryperl`).
 * if we want to use `cmake` to compile `strawberryperl`, then I would add it to the `profile:build=Windows`. Which settings will it use? It will use settings from `profile:build` too because the _build machine_ for the tools that run in the _build machine_ is the same _build machine_.

![image](https://user-images.githubusercontent.com/1406456/89936953-b3aae700-dc14-11ea-9115-c911e599756b.png)


---

If we don't do it this way, like you are suggesting, `cmake` should be added to `profile:build` and there would be no way to _inject_ build-requires to packages that are already in the _"build context"_. Also, going back to the naïve scenario, it won't be possible to add build-requires to packages using only one profile.

Those would be just excuses if your approach were more sound than the one currently implemented, but IMHO current one is more powerful and easy to understand: you add a build-requires to packages in the host context using the profile that contain all the information for this context, then you need to provide a profile for all the packages that belong to the build context.

**Comment by a4z** [comment]
Thanks for your patience explaining me the details Javier!

When I understand you correct:  
If a build_requires package is missing ,either from the build_requires in the recipe or the --profile:host, and needs to be build,
in a x compile env, then the --profile:build profile is used to build this recipe?
And in a non x compile env, it does not matter since there is only 1 profile anyway and this will be used

And if there would be a build_requires in the --profile:build profile , it would be used to build the build_requires from either the recipe or the build_requires of the --profile:host ?

Did I get this right now?

**Comment by jgsogo** [comment]
You are welcome!

> If a build_requires package is missing ,either from the build_requires in the recipe or the --profile:host, and needs to be build, in a x compile env, then the --profile:build profile is used to build this recipe?

Yes

---

> And in a non x compile env, it does not matter since there is only 1 profile anyway and this will be used

If there is only one profile, it doesn't matter. But there can be two profiles with the same settings (**native compilation is just one realization of the more generic cross-building problem**):
 * **using only one profile**, it is the default behavior from Conan v1.x, there is only one context, a build-requires declare in the one-and-only profile will be applied to all the recipes in that one-and-only context.
 * **using two profiles** it is the new behavior (probably the default behavior for Conan v2.0), there are two contexts and the build-requires from the `--profile:host` will apply to recipes in the _host_ context, while the build-requires in the `--profile:build` will apply to recipes in the _build_ context.

---

> And if there would be a build_requires in the --profile:build profile , it would be used to build the build_requires from either the recipe or the build_requires of the --profile:host ?

Yes

**Comment by a4z** [comment]
awesome, finally it makes sense also to me :-) 
Thanks for the help! 
One more time the conan team surprises me positively with a well throughout concept.
