### ISSUE TITLE
[question] OS specific options in conanfile.txt

### ISSUE THREAD

**Issue by dFohlen** [conan-io/conan#7559]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Hi,

we use Conan (version 1.28.0) in our CMake project and have created a `conanfile.txt` for it, in which we have defined some libraries and their build options.

Now we are building the project on both Linux and macOS and have conflicts with some options in the `conanfile.txt`, since libraries like [libCurl](https://github.com/conan-io/conan-center-index/blob/4b88f87bef1c599cbd1cd41a51adf9e74e31e1c9/recipes/libcurl) simply delete operating system-specific options instead of setting them to false, e.g. [del self.options.darwin_ssl](https://github.com/conan-io/conan-center-index/blob/4b88f87bef1c599cbd1cd41a51adf9e74e31e1c9/recipes/libcurl/all/conanfile.py#L80) which leads to an error on Linux:  
```ERROR: libcurl/7.68.0: 'options.darwin_ssl' doesn't exist```

How can we handle this? Should this be changed in the official recipe of libCurl or is there another option on our side??

conanfile.txt:  
```
[requires]
libcurl/7.68.0

[generators]
cmake_find_package
xcode

[options]
libcurl:darwin_ssl=False # Default True
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.5)

if(EXISTS ${CMAKE_BINARY_DIR}/conaninfo.txt)
  set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR})

  find_package(CURL REQUIRED)
  target_link_libraries(test-project CURL::CURL)
```

**Comment by memsharded** [comment]
Hi @FohlenAFK 

Yes, there are two approaches for your case:

- You could leave the ``libcurl:darwin_ssl=False`` out of the ``conanfile.txt`` and pass it in command line instead:

```bash
$ conan install . -o libcurl:darwin_ssl=False
# or in other scenario:
$ conan install . -o libcurl:darwin_ssl=True
```
Actually the default option you don't need to specify it.

- The other approach, if you want to write conditionals or something, depending on the consumer platform, you could try porting your consumer ``conanfile.txt`` to a consumer ``conanfile.py``:

```python
class MyPkg(ConanFile):
    settings = "os", ...
    def configure(self):
        if self.settings.os == "Windows":
             self.options["libcurl"].darwin_ssl = True
```
You will use it as the ``conanfile.txt``, no need to create packages for it:

```bash
$ conan install .
```

We didn't want to add any custom DSL in the ``conanfile.txt``, because that would require to learn a new syntax, that will probably need in any case to evolve, it will eventually have bugs... it is much easier for everyone, including users to just use a full language like python and move to a ``conanfile.py``

Please let me know if this helps. Thanks!

**Comment by memsharded** [comment]
Hi @FohlenAFK 

I hope this response clarified the issue. I am closing it now, but please let me know or open a new issue if you have any further question. Thanks!
