### ISSUE TITLE
Patching sources tool

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#76]
This has been reported a few times, at least 2 publicly:
- @mcraveiro: https://github.com/conan-io/conan/issues/56
- @Klaim: http://boost.2283326.n4.nabble.com/Feedback-boost-conan-binary-packages-td4682377.html

I think this is a common use-case, maybe some helpers can be done to ease this task.

**Comment by Klaim** [comment]
Indeed.

By the way, at some point I tried to make a dependency repository for my project which would have used cmake's ExternalProject command. I failed to finish it because the imported target dance is so complex I can't even.
But you can look at the kind of complexity I have to manage day to day with this project: https://bitbucket.org/klaim/netrush-dependencies-cmake

There you can see a few use of patching of the dependencies after their download.
