### ISSUE TITLE
[question] update library dependency order without rebuilding the package.

### ISSUE THREAD

**Issue by shelper** [conan-io/conan#7617]
I have a big project that generates many .a files, and i messed up the library dependency order  of these .a files. I know there is a way to set the order using self.cpp_info.libs variable in the package_info()in the recipe file, but i dont want to rebuilds everything by running conan create again. is there a way to modify/update the order without rebuilding the project?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by kralicky** [comment]
You can try `conan create --keep-build`

**Comment by memsharded** [comment]
> I have a big project that generates many .a files, and i messed up the library dependency order of these .a files. I know there is a way to set the order using self.cpp_info.libs variable in the package_info()in the recipe file, but i dont want to rebuilds everything by running conan create again. is there a way to modify/update the order without rebuilding the project?

If you are not using revisions, updating the recipe and uploading it, without creating binaries, can fix the issue. The package binaries will be marked as "outdated from recipe", because they will know they were created with a different recipe. This is important to track, it is extremely recommended that binaries can perfectly match the recipe that was used to create them, otherwise the inconsistencies might produce almost impossible to debug problems. So even if it is going to take some extra CI time, it is recommended to re-build the packages. It is also very likely that in Conan 2.0, using revisions will be the only approach, and then rebuilding the binaries will be mandatory.

**Comment by shelper** [comment]
@memsharded thanks for the info, sounds good to me, I saw you put triaging label, so i am leaving this to you to close this issue.
