### ISSUE TITLE
[question] Building packages that are in build_requires in the default profile

### ISSUE THREAD

**Issue by kralicky** [conan-io/conan#7648]
Scenario: You have a build tool that you want to have as a default build_require (such as cmake, or another package that is always part of your toolchain). If that package itself has dependencies, you will never be able to build it using the default profile, because the dependencies will obtain the build_require of the package currently being built from the default profile, resulting in a loop. 

It may be useful to be able to specify in a profile build_require that it should not apply while building that package. Is this possible? Or, is this not really a valid use case?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Hi, @cobalt77 !

Using one single profile this can be challenging as Conan creates only one graph and packages from your build-require and the packages you are building will _mix_/_conflict_. It is the situation you are describing.

But, we added time ago the possibility of using two profiles, one for the _build_ context `--profile:build` (tools like build-requires and all their dependencies belong to this context) and another for the _host_ context `--profile:host` (the libraries you are actually building). With this approach you can even use CMake to build CMake itself:

![image](https://user-images.githubusercontent.com/1406456/92118007-35e29180-edf6-11ea-8360-b6936b2fa7b6.png)

**Comment by kralicky** [comment]
This would be tricky to do I think, because my CI system treats every package the same - to build, it just runs `conan create .` The build and host profile would only have to switch when building the packages that are in build_requires in the default profile.

Here's an interesting idea... profiles as python scripts:
```python
from conans import Profile

class TestProfile(Profile):
    name = "default"
    default = True
    
    def build_requires(self):
        self.build_requires("gcc/8.3.1")
        if self.conanfile.name != "cmake":
            self.build_requires("cmake/3.18.2")
        if tools.detected_os() == "Linux":
            ...
        if self.conanfile.is_consumer():
            ...
```

**Comment by jgsogo** [comment]
Your CI could use always the same `conan create . --profile:host=<the-one-your-are-using-now> --profile:build=default` and it will serve for all the packages you are compiling right now, taking advantage of the _build_ and _host_ contexts. With an additional advantage, it doesn't require to modify recipes at all.

We cannot make the two-profiles approach the default because it will change how people are generating packages right now and it would be considered breaking. Another reason is that the feature is still experimental and we need to polish some issues yet.

We think that the DSL for the profiles is powerful enough and still we can serialize it into the lockfiles (this is very important for reproducibility), I understand a Python script is more powerful, but taking advantage of wildcards and using different files for profiles that refer to different configurations is flexible enough and easier to understand.

Anyway, if you really think there is a strong use case for this  kind of feature, we would really need more concrete examples and real-case scenarios, as developers (and maintainers) we try to keep complexity under control 😄

**Comment by kralicky** [comment]
>  serialize it into the lockfiles (this is very important for reproducibility)

This definitely makes sense. Probably want to keep this simple then! Anyway, I think I have determined that it's probably an anti-pattern to have too many global build_requires, so we've moved those requirements into individual recipes. Thanks!
