### ISSUE TITLE
[bug] private requires are treated as build_requires

### ISSUE THREAD

**Issue by ohanar** [conan-io/conan#7660]
When using private requires, the conan seems to treat them as build_requires. E.g.

```python
class ConanFile(ConanFile):
    name = "my-code-generator"
    version = "1.2.3"
    requires = ("taocpp-pegtl/2.8.3", "private"),
    ...
```
When building you get:
```
my-code-generator/1.2.3@ohanar/testing: Applying build-requirement: taocpp-pegtl/2.8.3
```

This doesn't seem to be an issue if the host profile and build profile are the same, however, if they differ the `cmake_find_package` generator won't produce scripts for the private requires.

**Comment by memsharded** [comment]
Hi @ohanar 

Sorry this wasn't responded back then, sometimes there are too many things ongoing and some tickets might fall through the cracks.

This ticket was about legacy 1.X ``private`` requires, not very recommended in 1.X and got a better replacement with the 2.0 ``visible=False`` trait.

Also this issue was reporting the legacy CMake integration, which has been superseded by the new one in Conan 1.X https://docs.conan.io/1/reference/conanfile/tools.html, and removed in Conan 2.0: https://docs.conan.io/2/reference/tools/cmake.html. Closing this ticket as outdated.

Please don't hesitate to open new tickets as necessary. Thanks!
