### ISSUE TITLE
[question] How to test and debug without creating package

### ISSUE THREAD

**Issue by mgrandsire** [conan-io/conan#7666]
- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Hello the Conan community,

I’m discovering Conan and as it looks very powerfull, I’m tring to deploy it in my projects.

Unfortunately, I don’t succeed to keep my current development process.
As developer, I would like to implement my source code and to test it locally without packaging it because it takes more time to package and as the code is not mature, I have to do it several time. So many hours/days lost at the end…

I tried to use separately conan commands like install, build… to have the library in local but to test it with conan test, It is mandatory to package it.
In fact, it would be nice to have a conan test --build-folder=XXXX which will allow to use directly the required library without indicating package name with version. (But I have a concern with this method, "conan test" run the test and I would like to run it in debug mode via eclipse.

Next, I tried to use directly CMake file generated by conan install but when I call “conan install test_package”, conanbuildinfo.cmake doesn’t include the component, nor its required. It contains only test and its required

This last usage would be very useful because it would allow me to do the install from eclipse, next the build to CMake and to run the test.exe in debug mode easily

Would it be possible to generate the conanbuildinfo.cmake with all package information + the test information like conan test does it?
A kind of “conan install –test”. Therefore, I would be able to call Cmake in command line.

Thanks for your help
Mickaël

**Comment by memsharded** [comment]
Hi @mgrandsire 

Thanks for your interesting in Conan and your feedback. 

> I tried to use separately conan commands like install, build… to have the library in local but to test it with conan test, It is mandatory to package it.

Let me explain a little bit about the ``conan test`` intended design: It was implemented there to check and validate the packages, that all the headers were correctly copied, the libraries were copied and in the right place, etc. because the most common error in a package was not putting the final package files in the right final location.  And then, that the package defines the right settings, options, so it can be correctly resolved and consumed. Then, it is totally necessary to create the package. The possible binaries like ``test.exe`` that are a result of ``test_package`` functionality are not intended or recommended to be debugged, just for quickly detecting package errors.

I am not sure if you are using it with this purpose, in case you are thinking more of unit and automatic tests, the suggestion is to put them in the ``build()`` method of the main recipe, and use ``conan build . --test`` (after ``--configure``, ``--build``)

> Next, I tried to use directly CMake file generated by conan install but when I call “conan install test_package”, conanbuildinfo.cmake doesn’t include the component, nor its required. It contains only test and its required

The ``test_package`` *conanfile.py* is a bit special. It does not need to do a ``requires``, it is automatically injected when the ``test_package`` folder is launched by the ``conan create`` command. It is not intended to be consumed directly with ``conan install`` by users.

I would suggest to have a development flow that basically consists only on ``conan install``. Conan will generate the necessary files to consume dependencies, but the rest of the development experience should be as "native" as possible, using the build system, the IDE. This is what we are aiming to further improve with the ongoing effort with the toolchains and the ``toolchain()`` method. Only when the source code is debugged, changed and finalized, it makes sense to check the package locally, run a ``conan create`` to check the package still builds and packages correctly in the cache.

Please let me know if this makes sense, or you have any further question.

**Comment by mgrandsire** [comment]
Hi @memsharded,
Thanks a lot for your answer. 
I have completely understood the goal of test as it is currently implemented but generally, before packaging, we want to test our code. Therefore, I wanted to reuse the build description described in conanfile.py and CMakeLists.txt and to reuse also the tests to avoid two different configurations (One for package and one for development)
Today, I generate Eclipse configuration with conan new template and I call connan command individually but I always need to create a package for test.
I didn't know toolchain(), I will play with it to know if it answer to my need.
I keep you in touch

**Comment by mgrandsire** [comment]
Unfortunately, toolchain() doesn't really answer to my needs for the moment.
I'll check an another way to manage this.
You can close the ticket. Thanks for the feedback.

**Comment by memsharded** [comment]
Closing this ticket as stale.

Conan has improved a lot since then, specially the local flow in Conan 2.0 with the ``layout()`` definition, and local dev experience.
