### ISSUE TITLE
[bug] Search call is leaking package name details to Conan Center Index

### ISSUE THREAD

**Issue by maikelvdh** [conan-io/conan#7672]
### Environment Details
Artifactory 6.13.0
Conan 1.27.0

### Steps to reproduce (Include if Applicable)
If you have setup Artifactory on-prem with a virtual repository which is aggregating a local and remote Conan repository you are leaking package name information to Conan Center Index (https://conan.bintray.com) even if you have configured exclude patterns like `<user>/**`. This is a security gap as you don't want any requests to resolve internal, local artifacts are blocked, so requests containing any related sensitive information never get out of your organization.

This is the result of #5433 changes in context of #5432.

### Logs
Rest API call contain URL references like: `https://artifactory.acme.com/artifactory/api/conan/repo/v2/conans/search?q=<package_name>&ignorecase=False` so all information regarding the package name is leaked despite usage of a company specific user in the Conan reference.

**Comment by memsharded** [comment]
This would require to re-open the Artifactory issue regarding the resolution speed when user/channel is specified.
Please @czoido, this is high priority, both because of the security leakage, but also because it is related to customer very slow ``--update`` results when a virtual remote is aggregating a remote proxying ConanCenter
