### ISSUE TITLE
[question] Build-Order / Inverse Dependency Graph

### ISSUE THREAD

**Issue by Tiger077** [conan-io/conan#7676]
When having a product package with a fixed dependency graph (no version ranges), I want to know which packages **would** need to be built again and in which order if I released a new version of a package in the upstream. i.e. I want to get my consumers.
The conan lock build-order seems not to support this use case.

The scenario is as follows:
* let us say we have the same dependency graph as in https://docs.conan.io/en/latest/versioning/lockfiles/ci.html
![image](https://user-images.githubusercontent.com/41305589/92491533-a02e7400-f1f2-11ea-891c-b3d71fe016f0.png)
* No version ranges are used! the packages have only fixed versions!
* I want to make a new release of libb (e.g. 0.2) and I want to know/predict which packages in the downstream will be affected (need to be updated and rebuilt)

When I use the "conan lock build-order" command with a lockfile, I get an empty list, because all the packages have their binaries. 
But what I need to do is to inject a change in some nodes in this dependency-graph and then get the affected/consumer nodes back!

**Comment by memsharded** [comment]
Hi @Tiger077 


The key here is to have the right ``package_id_mode``:

- The binaries are modeled by their ``package_id``, which is computed as function of settings + options + dependencies versions
- The default "package_id_mode" is ``semver_direct_mode`` that means that the ``package_id`` of a given package, e.g. libd/0.1 only changes (requiring a new binary, and then a build) when the major version of the direct depedencies change, that is, when ``libb/0.1`` jumps at least to ``libb/1.0``. 
- You can do the test, and bump to ``libb/1.0`` instead, and you will see the right build-order
- Instead, you can change the package_id_mode. You can modify your conanfiles and customize ``package_id()`` method, or you could change the ``default_package_id_mode``.
- Define in *conan.conf* ``general.default_package_id_mode=minor_mode`` for example, and now repeat, bumping the version to ``libb/0.2``.


Please try this and let me know. Thanks!

**Comment by Tiger077** [comment]
Hi @memsharded 

My use case is a bit different. I need to know the consumers of a package, even when they use a fixed version of this package!
I use "full_version_mode" as default_package_id_mode. 
So concretely what I want to do is to identify the consumers of a package in a dependency graph of a product, in order to, for example:
* Inform the developers of the consumer packages that I released a new version of their dependency package and they can use it! 
* Update the version of the dependency package in all consumers myself to the new fixed version
I could use text search for that in all conanfile.py of the product, but this would not help me with getting the build-order.

To test if I can get this with lockfiles I downloaded the examples [from here](https://github.com/conan-io/examples/tree/master/features/lockfiles/ci) and I changed all the versions of the requirements to a fixed version (0.1). 
And then created a new version of libb (0.2) as indicated in [Lockfiles in Continuous Integration](https://docs.conan.io/en/latest/versioning/lockfiles/ci.html). When I use the command: 
`conan lock create --reference=app1/0.1@user/testing --lockfile=locks/libb_deps_base.lock --lockfile-out=locks/app1_base.lock --base`
I get the following error:
`ERROR: The provided lockfile was not used, there is no overlap. You might want to create a fresh lockfile`
This makes sense, as I am trying to use a lockfile of libb with a version (0.2) which is not used by app1. 

I hope I could explain well enough what I need to do :)

**Comment by memsharded** [comment]
Hi @Tiger077 

Yes, I think now it is more clear. I was a bit confused because I was understanding it as a real "build-order" thing, and not as general graph information.

Just in case, if you are not aware, the "revisions" mechanism allows to do changes in recipes without bumping the version, and the ``recipe_revision_mode`` allows to implement a efficient ``build-order`` in the same way than when manually bumping versions, and lockfiles are also able to lock revisions.

I would say this would be a feature request that lies more in the ``conan info`` command than in the ``conan lock`` command. Of course, a lockfile could be passed to the ``conan info`` command, but I see it as a request from information from the current graph. ``conan info --graph=file.html`` or ``--graph=file.dot`` is able to dump some format of the graph. It looks possible to implement some ``conan info descendants`` functionality that can return such information.

We have started already to design the Conan CLI for Conan 2.0, and it would be great if @czoido could take note of this feedback for the new ``conan info`` command. It seems a bit messy to introduce it now, so I would prefer to think about it in the new cli.

In the meantime, I would suggest the following approach:
- Use the ``conan info --json`` (like ``conan info poco/1.9.4@ --json=poco.json``)
- Write a script that reads the json and use the ``required_by`` field in the generated json file to navigate it down the graph.

I think it should be a relatively straighforward script, please let me know if you have any question or need help with it.

**Comment by memsharded** [comment]
In Conan 2.0 the following has been done:

- ``conan graph info``, including ``build-order`` have been decoupled from lockfiles. They can use lockfiles to guarantee versions and revision if desired, but still dependency graph and build orders are computed with ``conan graph`` command
- Still, obtaining the "consumers" of a given package will not be possible, because this is something that doesn't scale:
  - Builds and graphs very often distribute packages in different server repositories. Implementing infrastructure that can check this type of inverse dependency across distributed servers is a humongous effort
  - The task is even more complicated, because graphs are conditional to many inputs (like different OSs can have different dependencies). Responding the question "who depends on a given package" needs to be responded by applying all possible configurations to all possible consumer packages.
  - There is an exponential explosion of consumers down a graph, because more and more versions and revisions are created. For example in ConanCenter, there will be many hundreds of different revisions and versions that consume packages like zlib or openssl

So the only possible approach in practice is to compute the dependency graphs of the "products" that we want to maintain, and that graph will contain all that information. The ``conan graph info`` in 2.0, with its ``--format=json``, the ``conan graph build-order`` and ``conan graph build-order-merge``, the very improved ``package_id`` will resolve efficiently the question "what needs to be built" when something changes upstream in a graph.

So I am closing this as solved in 2.0, if there are further questions, please open new tickets targeting 2.0, thanks!
