### ISSUE TITLE
[recipe] Constrain on minor VS version

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#7680]
Now as C++20 rolls out is is important to be able to detect the minor version of VS and to constrain `configure()` on it. For example, my library requires at least 16.7 to successfully compile. How to require it in `configure()`?

**Comment by markovandooren** [comment]
To guarantee compatibility, I create a ToolSetVersion in configure() by parsing the VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.props file of Visual Studio for the toolset version. I then propagate that to all dependencies such that I am guaranteed to get the correction version for all packages. Depending on the build options, you can decide to define compatible configurations. Since these need to be enumerated explicitly, you have to hardcode them or read them from a custom configuration file.

**Comment by jgsogo** [comment]
From ConanCenter perspective (probably other CIs out there): we are running `conan info` to get the packageID in Linux machines for all the configurations, which means that `configure()` is executed in an environment where you cannot access/parse anything from VisualStudio. Everything needed should be input from the profile.

When considering this issue, it is also worth reading (> v16.8) https://developercommunity.visualstudio.com/t/how-to-select-vs-168-compiler-with-vcvars-after-up/1359197?from=email

**Comment by memsharded** [comment]
Closing as outdated.
