### ISSUE TITLE
troubleshooting: Unknown cmake generator for these settings

### ISSUE THREAD

**Issue by rollbear** [conan-io/conan#770]
I'm trying to set up conan for cross compilation to embedded devices, but things are not going well.

I expect troubles, but I find that conan is not very helpful in explaining to me what the problems are.

For example, I keep getting the message: `Unknown cmake generator for these settings.`

Which settings?

I've noticed that `conanbuildinfo.cmake` tries to be a bit too helpful and finds the native compiler in my PATH, sees a version mismatch and refuses. I've also seen that I can disable that check with the flag `-DCONAN_DISABLE_CHECK_COMPILER=yes` to cmake. This works in the sense that I can run cmake by hand, but when running from the `build` method in `conanfile.py`, I only get the unhelpful error message.

What ways are there to get information out of conan regarding what it is that fails?

Trouble shooting progress is slow when you don't know what is causing the troubles.

**Comment by memsharded** [comment]
Two different things here:

- The ``CMake`` helper is coded for common settings, so internally it might be checking the compiler, the OS, etc: check the code here: https://github.com/conan-io/conan/blob/develop/conans/client/cmake.py#L23

- If unknown settings are making```CMake`` helper fail, you might change and explicitly define the cmake generator for your build: 

  ```python
  def build(self):
       cmake = CMake(self.settings)
       cmake.generator = "Unix Makefiles"
  ```

- The ``conanbuildinfo.cmake`` is structured so it actually does nothing while including it, besides definining some ``CONAN_XXX```variables and macros. The ``conan_basic_setup()`` is the one doing the job, but internally is divided in other macros, so you can take what you need. Check: https://github.com/conan-io/conan/blob/develop/conans/client/generators/cmake.py#L123

- If you have a mistmatch between compilers in the path and the one actually used for building, you might be interested in the possibility to define environment variables, even per package. Conveniently defined to in ``profiles``. So you can set CC and CXX according to your conan settings.

It is true that conan build helpers are mostly for PC apps, while using it for embedded requires some extra work, as it is not very standardized into conan yet due to the wildly variability in embedded. Please keep asking for support, if you need also more interactive help, please tell, we can be available in chat too.

**Comment by MathMagique** [comment]
The fix you suggested in the second point does not work this way, since creating a `CMake` instance will fail with an exception propagated by `_generator()`. To avoid the exception in case the generator cannot be determined automatically, you need to set the `CONAN_CMAKE_GENERATOR` environment variable:

```python
import os

def build(self)
    os.environ['CONAN_CMAKE_GENERATOR'] = 'Unix Makefiles'
    cmake = CMake(self.settings)
```
One could change the semantics of `_generator()` to return `None` in case it cannot determine the generator automatically. Methods using the `generator` property then would have to issue proper error messages in case the generator is set to `None`. This way, the workaround you proposed would work.

**Comment by memsharded** [comment]
Yes, but this could be dangerous, setting the environment variable might affect other packages as well.

Environment variables can be set per package with: ``-e MyPkg:CONAN_CMAKE_GENERATOR="Unix Makefiles"``

In any case, if that raise an Exception, is a bug, lets have a look. Thanks for reporting.

**Comment by sixten-hilborn** [comment]
In my PR (#921) I've updated the constructor of `CMake` to receive a generator parameter:

```
def build(self):
     cmake = CMake(self.settings, generator="Unix Makefiles")  # Uses _generator() if none is specified
```

However this would only help you to fix a specific package. All packages building with cmake should be fixed if the settings you are using were handled by _generator().

**Comment by memsharded** [comment]
The ``CMake`` class has got many improvements since this issue, and also cross-building support in conan and the build helpers has been improved. 
This should not longer be an issue, but please report if necessary. Thanks!
