### ISSUE TITLE
Default files that can be overridden 

### ISSUE THREAD

**Issue by paostman** [conan-io/conan#7713]
Hi.

I would like to create a Conan recipe that installs files but only if files are not available in a local git clone.
In other terms I would like to install dependencies but files could be overridden by local versions. This too create inheritance, i.e. default files that can be replaced by project repo files.
Is this possible in Conan? Any other ways to achieve this behavior?

/Patrik

**Comment by memsharded** [comment]
Hi @paostman 

Not sure what you mean. Conan does not "install" files in your project, dependencies are installed in a local cache (typically ``<userhome>/.conan`` folder. So they will not overwrite anything that you have locally. 
The ``imports()`` and ``deploy()`` methods can be used to copy things from the cache to the current user folder. I haven't tried that, but maybe it is possible to do a copy of the files, instead of relying on the ``self.copy`` functionality (this will overwrite local files), doing the copy yourself, checking for files that exists first with ``if os.path.exists(path)``, while iterating the dependencies exploring the ``self.deps_cpp_info`` attribute. Does it sound like it could be good for your case?

**Comment by AbrilRBS** [comment]
Closing as solved as we didn't hear back from you in a while - if anyone has any other question or request, please feel free to create a new issue, we're always happy to help! :)
