### ISSUE TITLE
[question] Build log of resolved dependencies info

### ISSUE THREAD

**Issue by 4nti-7rust** [conan-io/conan#7735]
Hello,

I have a cmake ARM C++ project that is using multiple dependencies with version range.
We are using the [CMake wrapper](https://github.com/conan-io/cmake-conan) to automatically install the latest package version based on version range.
This project does not generate a conan package as it is a final deliverable that we publish manually. 

My issue is that I cannot find a way to automatically retrieve the versions (and other info) of the resolved dependencies in order to generate a build log that I wanted to include in the final deliverable for traceability.

I found some workarounds in #2451, but they are part of the build step, which does not happen in our case since we only use conan for the install / require steps.

I also tried to call conan info as part of the cmake build process, but it does not seems right, I need to give the profile again, etc.

Ideally, I wanted to get all the info either from cmake or as part of a conan install step.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @4nti-7rust 

Have you considered trying the new ``toolchain()`` method. You could use it, because it will execute in ``conan install``. It will have access to the ``self.deps_cpp_info`` data, each dependency there will contain the ``self.deps_cpp_info["dep"].version``. You could generate there and write to disk any file with any format you want that your build could use.

Please let me know if this helps. Thanks!

**Comment by 4nti-7rust** [comment]
Thanks for the quick answer. That's exactly what I was looking for !
That said, I still cannot find the user and channel for the dependencies, any idea where I could find this ?

**Comment by memsharded** [comment]
Great to know!

The short answer is that the user/channel of dependencies is not available yet in the ``deps_cpp_info`` data.

Just in case, I would like to advise against using variable user/channel in projects, or doing promotions based on changing the user/channel (like the ``conan copy`` command). Changing user/channel might be deprecated in Conan 2.0, as we have learnt that it is better to have packages immutable, and use different repositories in the server to run promotions.

Are you doing that? How critical is storing the user/channel, or could you just make it constant like "mycompany/stable" for your packages?

We are considering now what would be the best approach to make the general information from upstream dependencies available to consumers, and what information should be passed, but this might take some time. You might get some of it via the ``self.requires`` field, but that will be limited to direct dependencies, not transitive ones.

**Comment by 4nti-7rust** [comment]
> Just in case, I would like to advise against using variable user/channel in projects, or doing promotions based on changing the user/channel

Currently our CI system is building our deps projects using the git branch name to decide the channel name.
So we have the following pattern `my_dep/a.b.c@my_company/branch_name`.

In the "integration" projects (our final deliverables), we are following these stages :
- When a new deps is developed we point one project to the channel that correspond to the feature branch of the deps project
- Once tested by SQA the changes goes to develop branch / channel
- Then we wait for Field tests and merge the changes (and some other) into the master branch / channel
- All the project are then advice to point to the latest master channel

> we have learnt that it is better to have packages immutable, and use different repositories in the server to run promotions

I'm not sure I understand exactly what immutable mean in the context of conan packages ? Is it that _identical version_ mean identical package or that _identical version + channel_ mean identical package ?

Are suggesting that we should use servers the way we use channels ? And then how could I pick on dependency in testing and the other in stable ? Sorry, I am a bit confused...

> We are considering now what would be the best approach to make the general information from upstream dependencies available to consumers

IMO the need here is traceability.

As far as we are concerned, it could be done through full package information `name, version, user, channel, server` 
or using internal package build information like `git project remote url, commit hash`.

Also `conan info` seems to provide most informations I wanted, why not start with offering the same data into the `toolchain(self)` method ?

> You might get some of it via the self.requires field, but that will be limited to direct dependencies, not transitive ones.

I found that the `conainfo.txt` file is generated all the time, so I think I am going to parse the file to get the data I wanted...

**Comment by memsharded** [comment]
> When a new deps is developed we point one project to the channel that correspond to the feature branch of the deps project
Once tested by SQA the changes goes to develop branch / channel
Then we wait for Field tests and merge the changes (and some other) into the master branch / channel
All the project are then advice to point to the latest master channel

> I'm not sure I understand exactly what immutable mean in the context of conan packages ? Is it that identical version mean identical package or that identical version + channel mean identical package ?

Yes, there are some issues when using ``user/channel`` as something that changes, in this case, as the source branch changes.

Lets say that you have a project, in "develop" branch, containing:

App/1.0@team/stable=> LibC/1.0@team/stable=> LibB/1.0@team/stable=> LibA/1.0@team/stable

Now, some changes that we want to test are done in LibC, and lets say that they live in a source branch called "mybranch". Will the dependency graph change to? (I understand that you condition the ``requires`` to current package ``self.channel``?)

App/1.0@team/mybranch=> LibC/1.0@team/mybranch=> LibB/1.0@team/mybranch=> LibA/1.0@team/mybranch

Notice how LibA/1.0 and LibB/1.0 also change their channels, meaning they are different packages from the previous, even if they didn't have any change at all, nor themselves neither in their upstream. There could be different approaches:

- Build the LibB/1.0@team/mybranch, LibA/1.0@team/mybranch packages from source. This will be very inefficient and unnecessary.
- Do a ``conan copy`` to copy the existing packages from "develop" => "mybranch" channel. This changes the package names, but for example the information inside the packages, like the ``conaninfo.txt`` will not be updated. Furthermore, if you are using some ``package_id_mode`` like ``full_package_mode`` or higher, then all the ``package_ids`` can become invalid.

So, instead of changing channels, it is possible to define different repositories in the server, and have one "develop" repository, and then 1 "build" repository or 1 different repository for every branch that we want to test. Copying packages from one repository to another is a very efficient operation in Artifactory, for example, because it deduplicates files. This allows to reuse LibB/1.0@team/stable and LibA/1.0@team/stable in all branches builds, being completely immutable and consistent. They will always match their internal information, and even if using some of the most advanced modes, like ``recipe_revision_mode`` will not break the package_ids.

Maybe the information in https://docs.conan.io/en/latest/versioning/lockfiles/ci.html could provide some further insights.

Let me know if this clarifies a little bit the proposed alternative.

**Comment by 4nti-7rust** [comment]
> App/1.0@team/mybranch=> LibC/1.0@team/mybranch=> LibB/1.0@team/mybranch=> LibA/1.0@team/mybranch

Sorry, I wasn't clear, the branch of the project is not linked with the channel of the deps required. So only this could happen:
`App/1.0@team/my_integration_test_branch=> LibC/1.0@team/feature_new_function=> LibB/1.0@team/master=> LibA/1.0@team/master`


I override the channel of one deps inside the application, to make my integration tests. After the tests `LibC/1.0@team/feature_new_function` will be merge with other changes and become `LibC/1.0@team/master` (same version).

The issue I may have with _immutability_ in my scenario is when another branch / channel `LibC/1.0@team/other_branch` have been merged into master before this branch, then `LibC/1.0@team/master` could be different from `LibC/1.0@team/feature_new_function` (same version, but not the code). That's why I wanted to get the user channel in my build log.

Note that in that case we cannot merge `LibC/1.0@team/feature_new_function` in master as is, and we need to create a new `LibC/1.1@team/feature_new_function` and then merge it to create `LibC/1.1@team/master`.

I also thought about using a different version strategy for the feature branch (e.g. `1.1-branch_name`), but then if `LibB` is in test, `LibC` won't be able to use version range and I will need to create a new integration branch for it too... That's annoying.

> Build the LibB/1.0@team/mybranch, LibA/1.0@team/mybranch packages from source. This will be very inefficient and unnecessary.

That's what we do... Fair point.

> So, instead of changing channels, it is possible to define different repositories in the server, and have one "develop" repository, and then 1 "build" repository or 1 different repository for every branch that we want to test. 

So I guess in this scenario all of the deps will change of repository. That wouldn't be compatible with my use-case where I wanted to test only one package change against all the other being in stable branch. Or I am still not understanding your proposed alternative correctly ?

> Maybe the information in https://docs.conan.io/en/latest/versioning/lockfiles/ci.html could provide some further insights.

The lock mechanism is still a bit obscure, but I will spend some time to understand it. Thanks a lot of all these insights !

**Comment by AbrilRBS** [comment]
Closing this as solved in v2, `conan graph info` and the `pkglist` feature allow for full control over the discussed ideas :)
