### ISSUE TITLE
[bug][question] Conan lockfile behavior change between conan 1.26 and conan 1.29. 

### ISSUE THREAD

**Issue by fourbft** [conan-io/conan#7739]
We used conan.lock files from a CI build for a big set of comonents where all component versions were synchronized. Later developers used these lockfiles to build new versions of one of those components in the context of that lockfile locally, so they were not affected by new versions of upstreams that some other developer might have created in the meantime.

Simple example:
CA/1.0.0 <- CB/1.0.0  (read CB uses CA)

This combination was built in a CI job and the lockfile was generated. Then someone created a CA/2.0.0 package.
Now another developer works on a CB/2.0.0 package, but still wants to work in the context of the last successfull CI build, so he uses the lockfile and creates a CB/2.0.0 locally on his machine, but still wants to use CA/1.0.0 (which was locked in the CI lockfile).

This scenario used to work perfectly with conan 1.26, but fails with conan 1.29 with the error message: 
`ERROR: Couldn't find 'CB/2.0.0@local/testing' in lockfile`.

We need an alternative for the old behavior with the new conan version, but are at a loss how to do that, as lockfiles have become quite restrictive about building new versions of packages that were not previously locked.

I have attached a simple python script, that reproduces the case explained above. The script works with conan 1.26, but fails with the above error message with conan 1.29.

(Of course, our real word scenario involves a complete tree of sometimes dozens of upstream dependencies with potentially several version conflicts, not just one upstream package. That is why we need a way to fix the local environment to a known-good state until we push the new version of CB to the CI which then builds a new consistent state of all components.)

**Comment by fourbft** [comment]
Here ist the attachment:
[use_segment_build_lockfile_for_local_component_builds.py.gz](https://github.com/conan-io/conan/files/5262083/use_segment_build_lockfile_for_local_component_builds.py.gz)

**Comment by memsharded** [comment]
Hi @fourbft 

The lockfiles have become not more restrictive, but their checks more thorough and complete.
It is true, that now, if you capture a lockfile, and it locks ``CB/1.0.0``, you will not be able to change that, because it is locked. This was a bug fix, because if the lockfile contained other packages that depended on ``CB/1.0.0``, changing it will be automatically violating the locked version.

The new lockfiles should allow this flow, but in a more controlled way. I have hit a limitation of the commands to allow it, but the logic is almost there. I will be providing a pull request with this flow implemented and update here.

**Comment by fourbft** [comment]
> I will be providing a pull request with this flow implemented and update here.

Thanks @memsharded

**Comment by fourbft** [comment]
Apart from the workflow described above we also have implemented the workflow described in the former conan docs here:
https://docs.conan.io/en/1.26/versioning/lockfiles.html
in the chapter "How to use lockfiles in CI". Especially this step:

> Now we can safely create the new version of pkga/0.2, that will resolve to use pkgz/0.1 instead of the latest 0.2, if we use the lockfile:
> cd pkga && conan create . pkga/0.2@user/testing --lockfile=../release
> \# lockfile in release/conan.lock is modified to contain pkga/0.2

This workflow is different from the one above in that it modifies the lockfile during the "conan create". It would be great, if such a workflow would be possible again, too.

**Comment by memsharded** [comment]
Hi @fourbft 

I am proposing in https://github.com/conan-io/conan/pull/7763 to remove the check that raises when a lockfile that is created from another existing lockfile doesn't have any overlap with the former, which was the thing that was holding this possible flow.

Let me try to summarize here the possible flow with the new syntax:

- Lets say we have App/1.0->LibC/1.0->LibB/1.0->LibA/1.0
- A lockfile "app.lock" is captured that locks all 4 to those specific versions: (App/1.0, LibC/1.0, LibB/1.0, LibA/1.0)
- Now a developer comes and is doing changes on LibB. They are going to be developing locally LibB after a ``git clone libb``, and want to make sure they stick to the dependencies defined in the previous lockfile. They could do:

   ```bash
   $ conan lock create . --lockfile=app.lock --lockfile-out=libb.lock
   ```
   That will create a new lockfile *libb.lock* that will basically contain information only about libb and will have LibA/1.0 fully locked.

- After some happy changes, developer pushes changes to remote, which fires CI. Those changes bump the version to LibB/1.1.
- CI can build LibB/1.1, using the same "app.lock" as a base if desired.
- Now the goal is to integrate this downstream, the first important bit is to check that nothing breaks, and that we can build down to App/1.0.
- The first step is to create a new lockfile for App/1.0. Note that the previous one cannot be forced, as there is nothing that guarantees than LibB/1.1 is a real dependency of LibC, because it could have a hardcoded ``requires = "LibB/1.0"``. The ``package_ids`` of LibC and App could become different too. Or ``LibB/1.1`` could also introduce changes in the upstream dependencies, adding or removing dependencies. The only way to guarantee a consistent graph is to create a new lockfile:

   ```
   $ conan lock create --reference=App/1.0 --lockfile=libb.lock --lockfile-out=app_test_libb.lock
   ```
- With the new "app_test_libb.lock" lockfile we could perform a ``conan lock build-order``, deduce that both LibC and App needs a rebuild and launch such rebuild.
- If LibB/1.1 does not belong to the graph, because LibC doesn't depend on that version, the previous example will build nothing, as things would have already been built.
- It is always possible to check if LibB/1.1 belong to the "app_test_libb.lock" lockfile to deduce if the produced changes belong or not to the final product
- It is also possible to get the best possible closest solution to the initial lockfile while ensuring consistency, by installing it in the local cache, before locking ``app_test_libb.lock``. Doing first a ``conan install App/1.0@ --lockfile=app.lock`` will install things in the cache, when the lock is captured later, it will find and prioritize what is in the local cache while capturing the lock. We might want to do a ``conan lock install <lockfile>`` command for this purpose, but at the moment this would be merely an optimization.

Note that the ability of not automatically integrating things downstream, based on the version is an important feature to achieve both goals simultaneously:
- Continuous integration of changes that satisfy the version-range (or revisions), automatically rebuilding downstream.
- Possibility of evolving code breaking changes. When changes in LibB will require changes in LibC, it totally makes sense to bump the version so it is excluded from the final product build, and defer the integration until LibC picks up, is modified to start using LibB/1.1 at the same time it fixes its own code.

Please tell me if this helps, we are releasing 1.30 this week, and would like to include this fix.

**Comment by fourbft** [comment]
Hi @memsharded,
thanks a lot for the detailed explanation. It sounds like it could be a viable solution for our use cases! I'll try to adapt our CI scripts to the new lockfile mechanism when 1.30 is out.
And thank you very much for looking into this issue!
