### ISSUE TITLE
[question] Export package with python tool

### ISSUE THREAD

**Issue by Viatorus** [conan-io/conan#7744]
Is it possible to export a python tool (with setup.py) alongside a C++ library in one package?

I didn't find any good reference. All tools that I found and I know of (ninja, swig, cmake) are C/C++ build executables but not python modules. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by intelligide** [comment]
I don't think that's possible and I don't think Conan is designed for that use. Why not use pip and Pypi ?

**Comment by Viatorus** [comment]
I would like to use pip but than the C++ library and dependencies are not managed by conan.

But as it seems to be, I have to separate the project in pip and conan.

**Comment by memsharded** [comment]
Hi @Viatorus 

We are aware of some users that have been using Conan to manage other programming languages besides C and C++, including Java, C# and python.
We included some ideas in this section of the docs: https://docs.conan.io/en/latest/howtos/other_languages_package_manager/python.html. Were you aware of this?

Some important point is that if you use Conan for managing python code, most likely you cannot use at the same time the python native tools as ``setup.py``, because they have different purposes, mechanisms, etc.
