### ISSUE TITLE
[bug] `conan inspect` always prefers the package in the local cache

### ISSUE THREAD

**Issue by petermbauer** [conan-io/conan#7745]
### Environment Details (include every applicable attribute)
  * Windows 10:
  * Conan version: 1.29.2
  * Python version: 3.6.5

### Steps to reproduce (Include if Applicable)

Run `conan inspect` for a package that only exists in the Conan local cache and specify a remote, e.g.

`conan inspect -r conan-center openssl/1.1.1g@blabla/test`

This prints the results for the local package though a remote has been specified so i would expect that ONLY the remote is considered like with `conan search` and an error is printed since the package does not exist on the remote.
This also leads to issues with alias packages that are updated on the remote to point to a different target package while the old alias package is still in the local cache of other users.

**Comment by memsharded** [comment]
This issue is a bit complicated.

So far, the ``inspect`` logic for remote repos was following the ``install --update`` logic. It will not overwrite something that you have in the local cache, unless it would be an effective update.

Problem with ``conan inspect`` is that it requires the recipe to be fetched and installed in the client, to be loaded and parsed by the python interpreter (there are things that need to be resolved, like python_requires). So, if a more modern recipe exists in the local cache, the internal ``update`` will do nothing, and it will load the cached one, not the remote one.

The proposed PR forces the retrieval of the remote recipe every ``conan inspect`` invocation. I think this approach might have some new rough edges, so we need to consider them.

**Comment by petermbauer** [comment]
Thanks for taking care so quickly.
From a user perspective i think the expectation to `conan inspect` is that it has a "read-only" nature like e.g. `conan search`. Maybe the recipe and everything else that is required could be downloaded into a separate temporary "local cache" so the actual Conan local cache is not modified in any way?

**Comment by memsharded** [comment]
> Maybe the recipe and everything else that is required could be downloaded into a separate temporary "local cache" so the actual Conan local cache is not modified in any way?

Yeah, that is definitely an alternative approach that we should consider. So far we went with the simplest possible implementation, that reuse the existing fetch/install functionality.

**Comment by memsharded** [comment]
> Maybe the recipe and everything else that is required could be downloaded into a separate temporary "local cache" so the actual Conan local cache is not modified in any way?

I have been checking this, but seems quite complicated. It is not easy to hot-swap the cache, because that is the place where the whole configuration lives: the remotes that are going to be used, for example. Remotes might be necessary, because a recipe might need python-requires to be evaluated before inspection.

I would say go with this fix at the moment, and for Conan 2.0 I would like to think what is the overlap between the ``conan inspect`` and the ``conan info`` commands. Another possibility is to make ``conan inspect`` simpler, by removing evaluation of python-requires completely.
