### ISSUE TITLE
Reason for copying binaries to project directories?

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#776]
I noticed that this page shows that it's standard procedure is to copy binaries from Conan's "global download directories" in my home directory to each project as needed: 

http://conanio.readthedocs.io/en/latest/packaging/creating_out.html

It's very likely/possible this copy operation is necessary for C++, however I wanted to understand the reason.  I am not a C++ expert, but in the Maven workflows for Java, the build system simply refers back to Maven's "global download directories" during compile time, with no need to make copies of binaries.

**Comment by memsharded** [comment]
No, it is not really necessary, just very convenient:

- Imports helps to gather all shared libs to create packages, installers or deploys
- It is very convenient to avoid messing with the PATH, in order to let exes find the shared libs.

It can be avoided in different ways:
- Add the packages folders to the PATH. Using ``virtualenvs`` with generated files and ``activate|deactivate`` could do it (but we need that packages explicitely add binaries folders to the PATH)
- There is an open feature request to do this automatically for all packages; https://github.com/conan-io/conan/issues/408. 
- By now, you can just get the dependencies packages binaries paths (they are variables in cmake, or in plain text if you use the ``txt`` generator), and add them to the PATH environment variable.

**Comment by solvingJ** [comment]
Actually, now I'm really confused because I believe I was mistaken earlier.  Is Conan really copying binaries for a package from the conan cache in my profile directory (Users/jerry/.conan/data)  to every project where that package is referenced??  

I just happened to actually look into the "conanbuildinfo.gcc" file and noticed this, which indicates that those files are used in place, and not actually copied.  This would be exactly the behavior of Maven as well... so, maybe it's a non issue.

If so, please just close this ticket. 
 -IC:/Users/jerry/.conan/data/catch/1.3.0/TyRoXx/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -LC:/Users/jerry/.conan/data/catch/1.3.0/TyRoXx/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib -Wl,-rpath=C:/Users/jerry/.conan/data/catch/1.3.0/TyRoXx/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib

**Comment by memsharded** [comment]
Ok, lets try to clarify it:

- Conan is not copying artifacts by default from the conan cache (local in your computer <userhome>/.conan) to the user space (i.e. the project folders). Artifacts like headers are always used from the local conan cache, by setting the appropriate ``include_paths`` in the build system, but are not copied to the user projects.
- Different projects will use the same artifacts from the local cache. Note, however, that different projects might use different settings and options, and that might lead to different artifacts in the local cache. But if the configuration is exactly the same, the same headers and libs will be used, no point to waste disk space copying them.
- The only thing that can get copied to the user space, has to be explicit by the end user with the ``imports()`` feature. It is a typical mechanism to copy artifacts, mainly shared libraries to user space, as a convenience to avoid messing with the system paths, or to be able to redistribute the app.

Please tell me if this help, or ask again, glad to help. If everything clear, you can close the issue. Thanks for your feedback!

**Comment by solvingJ** [comment]
Ok, definitely helps a bit.  Can you explain a bit more about being able to redistribute the app and the system paths?  What is the limitation if not using imports()?

**Comment by memsharded** [comment]
If not using imports, the typical layout of a package would be in the local cache:

```
/home/<user>/.conan/data/pkg/version/user/channel/package/<sha>
 | - include / * .h, *.hpp
 | - lib/ * .a, *.lib, *.so
 | - bin/ * .exe, *.dll, *.dylib
```

If you link an app statically, no problem, but if you link your project app dinamically, it will require *.so, *.dll, or *.dylib files at runtime. Often they can also need other resource files, like bitmaps, sounds, etc. There are two options:
 - Use conan to install those packages to run (only valid for developer controlled environments)
 - Get all necessary files at runtime, and bundle them (like in a MSI installer) together with the app. ``imports()`` can help to gather files from the conan local cache and copy them to a folder where the installer can bundle them.
