### ISSUE TITLE
[feature] Validation of conan profiles

### ISSUE THREAD

**Issue by juba895** [conan-io/conan#7773]
In case there is e.g. a git repository which contains
-  a set of conan profiles
- and probably additionaly a project specific conan `settings.yml`

It would be helpful to validate this content for example when `conan config install git@path_to_git.git` will be executed by a users workspace. To be able to identify problems in the profiles or in the `settings.yml`.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @juba895 

It is not possible to do a general validation of those things, because they have meaning in a context. A profile could fail if it doesn't define enough settings that recipes are requiring, or changes in settings.yml can be broken because recipes or profiles still use older values. Profiles can be incomplete and only make sense when composed with other profiles, and so on.

So I think that this validation functionality should be done in the first place by the responsible person who is putting this information in the git repository. It is not something to do after the information is there. Most likely profiles and settings should be even tested, some  example packages to be built, etc., before putting them in a repository that will be used with ``conan config install``.

**Comment by juba895** [comment]
Hello @memsharded,
thanks for the fast reply. You are right, i totally agree that it's too late to do a validation / verification with `conan config install`.
But wouldn't it be possible to provide a kind of syntax verification for the (git) repository which contains the project specific `settings.yml` and the set of conan profiles? Thereby it could be at least checked if there are no problems in the definition of new fields in the `settings.yml` and its usage in the conan profiles?

Thank you!

**Comment by memsharded** [comment]
Conan 2.0 provides a ``profile.py`` plugin that can be used to do validation of profiles. 
"Cold" validation is not possible, now profiles are jinja templates, and they also have a ``detect_api`` available, so the only possibility is to validate it when fully parsed and loaded at usage time. 

Closing this as implemented in 2.0, thanks!
