### ISSUE TITLE
Support Visual Studio 2017

### ISSUE THREAD

**Issue by TimSimpson** [conan-io/conan#778]
It's pretty simple, see: https://github.com/conan-io/conan/pull/777

Also just a suggestion but VS2017 might make a good topic for a blog post due to it's new CMake integration, which appears to be incompatible with Conan on first glance but can be tweaked to work with it.

VS2017 supports using CMake directly (as in you can just open a folder with a CMake file and it figures everything out without having to create a solution file).  The problem is VS generates the build directory in some unique directory that cannot be predicted. That can be resolved easily by opening up the file `CMakeSettings.json` (created by Visual Studio when it first tries to open the folder) and changing the 'buildRoot' property to the path to any build directories you'd typically create manually (where you'd be able to run `conan install`).

**Comment by memsharded** [comment]
Sure, certainly it could be a nice post, or at very least to add those tips in the conan docs, thanks very much!

**Comment by memsharded** [comment]
I have submitted the PR for conan 0.18: https://github.com/conan-io/conan/pull/806. As you told me everything works fine, I am able to generate .sln from CMake, open it, works. Also test_package with new "15" version settings.

When doing the opening with CMake is when I have some differences. I don't have a ``CMakeSettings.json`` created, even if it opened the folder, recognized the CMakeLists.txt and processed it. It failed due to the missing ``conanbuildinfo.cmake``, but I changed the path to: include(${CMAKE_SOURCE_DIR}/conanbuildinfo.cmake), and it found it.

I see a ``.vs`` folder with a ``ProjectSettings.json`` file with just:

```
{
  "CurrentProjectSetting": "x64-Release"
}
```

Also, when I changed the path, it build the app, but it is not able to launch it, because the default conan output dir is just ``bin``, not ``bin/Release``. Maybe I should not use that path, but still it is confusing that having defined a CMAKE_OUTPUT_DIR properly, Visual is failing at finding the executables.

Any suggestion/idea? Thanks very much for your feedback

**Comment by NokiDev** [comment]
Hi @memsharded, @TimSimpson 

I ran into the same problem as @TimSimpson. The best solving idea is to integrate directly conan into VS as an addon. I'll try to do it, as soon as I can, and will notify you when it's done.

To answer your questions, VS_2017 don't generate automatically CMakeSettings.json file. 
By default it uses `C:\Users\<YouUserName>\CMakeBuilds\${workspace_hash}\build\${name}` as build_root

To generate it you need to go to
`Toolbar-> CMake -> Change CMake Settings -> Your Project`
and Visual will generate it.
You can then edit the file and change the build_root key.

Personally, I use this path : 
`${workspace_root}/builds/${name}`
it's not pur out of source but it satisfied the need. 
(_Be aware that you have to specify an absolute path so ./dir is forbidden and would have been too easy for a VS user I think and too hard for VS Dev to retrieve the absolute path before passing it to cmake_).

At work, we are integrating conan in our workflow, and we use cmake to format properly packages with Release paths. (even if it isn't necessary since we don't use multi features, they are leftovers of an old workflow.) 

The best things we have found now and use as workaround is to : 
- commit CMakeSettingsfile.json 
- run a script after git clone, that generate the CMakeSettingsfile.json for us with a common configuration. And run conan install for each configs. And then open VisualStudio.

But again the best ways is to have an integrated conan addon directly in visual studio (I prefer this one)
or that VS allow more flexibility with their system allowing us to change the default CMakeSettings in configs or compute the workspace hash but I don't believe it will happen someday and even it's still worth building a conan plugin.

**Comment by memsharded** [comment]
Hi @NokiDev 

Thanks very much for your input. Very useful, indeed!

I totally agree the best way could be the VS addon. I have created https://github.com/conan-io/conan/issues/2353 to centralize efforts there.

**Comment by ForNeVeR** [comment]
@NokiDev FYI: I am one of [conan-vs-extension](https://github.com/bincrafters/conan-vs-extension) authors (it's a draft of Visual Studio plugin that helps to work with Conan), and it already does somewhat what you describe: calls `conan install` for each project configuration (check out the docs and ask me any questions if you want), and also adds a small level of integration to project files.

Unfortunately, currently it works only for vcxproj-based projects, but we definitely want to support CMake-based integration, too (and maybe it'll be easy to add).

**Comment by NokiDev** [comment]
Hi @ForNeVeR 
I took a first look of your Vs-extension earlier this afternoon, it seems really nice. I haven't understood some of your UI/label choices.
I'll be happy to talk about it, but isn't the place to. 

Based on what I saw it won't be a big problem to integrate with CMake based project since logically conan is build system agnostic. In fact it should work with both, at the first layer of implementation and then be specialized with custom features.
I'll probably make a PR this Week end if I have some free time
