### ISSUE TITLE
[question] Get profile name inside conanfile.py

### ISSUE THREAD

**Issue by Morkxy** [conan-io/conan#7791]
Hi

Is there a solution to retrieve the name of the profile used in conanfile.py?
For example, if we install a package via:
conan install --profile=myProfile mypackage/stable

..To retrieve the given name "myProfile" in conanfile.py.
Something like "self.settings.profileName" ...

Thank-you

**Comment by memsharded** [comment]
Hi @Morkxy 

No, there is no way, because the actual settings, options, etc are a combination of multiple things:

- Command line arguments like ``-s`` and ``-o`` will overwrite the values defined in a profile
- Multiple profiles can be composed in the command line, applying multiple of them (priority the last one)
- Profiles can have the same name, just read from different locations. These locations will change in different computers or even in the same one if using different caches (like in CI), so the profile name will not be very informative

So if your recipe needs to check something, check the settings/options values directly, not the profile name. This will be much more robust, maintainable and clear.

**Comment by Morkxy** [comment]
Thank you for that answer :)
