### ISSUE TITLE
[feature] MSBuild command line helper

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#7824]
So far the toolchain PoC is there, but there is no command line helper.

**Comment by memsharded** [comment]
**Discussion:**

The mapping of Conan settings to MSBuild is more or less:

- ``settings.arch`` => ``Platform``
- ``settings.build_type`` => ``Configuration``

Where ``Configuration|Platform`` is what can be selected in the IDE to switch config, and typically is ``Release|x64`` or ``Debug|x86`` or similar.

There are other things that cannot be switched from the IDE:
- ``compiler.runtime`` => MT/MD/MTd...
- ``compiler.toolset`` => v140, v141,....

But the previous ``MSBuild`` helper can use some command line switches to inject and change for example the toolset on the fly, with ``/p:PlatformToolset=xxx``.
This introduces an assymetry, that the Conan ``build()`` is able to build a configuration that the user is not able to build as a developer from their IDE. Or is it expected that developers will call Visual from the command line with ``msbuild...... /p:PlatformToolset``? I dont think so

I would suggest:
- What a developer cannot change from the IDE, is hardcoded at ``conan install`` time. Cannot be switched by the build-helper.
- If a project wants to make variability available to developers, they could introduce custom configurations. Conan toolchains can allow custom logic to map from Conan settings to custom configurations (PoC already in: https://github.com/conan-io/conan/pull/7754)
- Check how this applies to other toolchains, specially CMake one.

Feedback appreciated team!

**Comment by solvingj** [comment]
Any command-line-wrapper for a build system should allow the passing of arbitrary build system variables (`/p` or `-D` or whatever).  Otherwise, it's just a really bad helper and users would very frequently resort to constructing their own command-line strings and sending them to `self.run()`. If they do that, then the build helper has lost any protection and usefulness it intended to give. 

In response to one of your bullets, no, not all build system variables are candidates for creating additional configurations in the project.  While thinking about one priority and design challenge here (trying to deliver some safety and guarantees around Visual Studio's unique "configuration" model), it seems we lost sight of some fundamentals here. 

If you need something concrete, "cosmetic string substitution" is a ubiquitous category of usage for  `msbuild` properties which is perfectly reasonable and necessary and doesn't conflict with the other goals.  People inject strings into builds and applications for all kinds of cosmetic reasons, such as putting the GIT commit hash or SVN revision in the "about" box of a program, or date built, etc.  It's very common to pass this in as a `msbuild` property and then have the `vcxproj` pass convert this to a preprocessor definition which is rendered in the code.  Very often, sometimes this is only passed in the CI builds, and the `vcxproj` has some default string value like `local` or `dev` or just an empty string.  

So, this just leaves the question of: 
- Should users be forced to put all such cases of build system variable definitions in the toolchain() method?

I think the answer is an obvious no. A command-line wrapper should stand on it's own and be able to do fundamental translations like this.  Also, not all recipes will want to use the toolchain.

**Comment by memsharded** [comment]
> Any command-line-wrapper for a build system should allow the passing of arbitrary build system variables (/p or -D or whatever). Otherwise, it's just a really bad helper and users would very frequently resort to constructing their own command-line strings and sending them to self.run(). If they do that, then the build helper has lost any protection and usefulness it intended to give.

I agree it is a good thing that command line wrappers allow passing all kind of things that are possible in the command line. And this should be doable with our new build helpers. 

My objection is that this shouldn't be the default (and possibly only) mechanism for injecting Conan necessary configuration and variability that is mandatory in the developer flow. It is not that the developer can build, run and debug with a toolset defined or a runtime defined. And if there is something that fails for a package for a given configuration, they must be able to develop and test that configuration as easily as possible. That part should be in the toolchain, so developer native experience matches what will be created when they do a local ``conan create``. Then of course, there might be some extra information and somethings that might be only injected in CI, but the basic build configuration shouldn't be part of it.

**Comment by solvingj** [comment]
It seems to me that build system variables should be supported in both the build helper and the toolchain, and I can see different uses for each. 

However, the above statement is only true assuming that the `toolchain.props` files will one-day be produced in the users working directory when calling `conan install` just like generator files are today with `-g`.  Otherwise (if `toolchain` files are never available outside the `build` directory in the conan cache) then there doesn't seem to be any difference between passing them using the `MSBuild` helper and the `toolchain.props` file.

**Comment by solvingj** [comment]
After speaking with @memsharded it seems that the `toolchain.props` is generated in the users working directory when using `conan install`.  So that's the important part.  The ad-hoc addition of toolchains via some command line flag like `-g` is done for generators is a separate feature and not critical (although may still make sense)
