### ISSUE TITLE
[feature] Include remote repo that package came from in lockfile

### ISSUE THREAD

**Issue by steve-thousand** [conan-io/conan#7828]
As far as I can tell, neither the lockfile, nor any of the other build-info files, will detail which remote that a given dependency came from. For example, I have "bincrafters" added as a remote repo, and when installing `boost_array/1.69.0@bincrafters/stable`, the resulting install output reads as checking conan-center first, followed by bincrafters
```
boost_array/1.69.0@bincrafters/stable: Not found in local cache, looking in remotes...
boost_array/1.69.0@bincrafters/stable: Trying with 'conan-center'...
boost_array/1.69.0@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt completed [0.10k]                                          
Downloading conanfile.py completed [0.51k]                                               
Downloading conan_export.tgz completed [0.74k]                                           
Decompressing conan_export.tgz completed [0.00k]                                         
boost_array/1.69.0@bincrafters/stable: Downloaded recipe revision 0
```
But the lockfile doesn't include that information
```
"1": {
    "ref": "boost_array/1.69.0@bincrafters/stable#0",
    "options": "",
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "prev": "0",
    "python_requires": [
     "boost_base/1.69.0@bincrafters/stable#0"
    ],
    "requires": [
     "2",
     "3",
     "4",
     "5",
     "6"
    ],
    "context": "host"
   }
```
Now I know that's not a great example because the "bincrafters" user in the reference is a pretty big hint, but might there be other cases where a reference found in one repo might be found in another remote repo? I am envisioning a scenario where i install `foo@1.0.0` which only exists in bincrafters, but sometime later another user attempts to install `foo@1.0.0` and by now someone has already added a `foo@1.0.0` to conan-center which may be significantly different. Is that a possibility?

**Comment by memsharded** [comment]
Hi @steve-thousand 

This is very by design, I don't think that this will be a feature. 
The idea is that things would be reproducible and immutable, while keeping the system decentralized. So you can capture a lockfile of those packages, including bincrafters one, upload everything to your own private Artifactory repo, and then you can disconnect from the bincrafters remote and use only your private one, and the lockfile will still be valid and keep working.

This makes even more sense if using revisions (revisions will be the default and most likely only mode in Conan 2.0). Revisions are a checksum of the contents. If the revision matches, then it really doesn't matter the remote, you can get it from another remote and it will be the same thing. This feature will be also used to make Conan 2.0 more agnostic about the remotes regarding the updates and existing binaries for a given recipe version (and revision)
