### ISSUE TITLE
Questions on using and abusing profiles with CMake

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan#7858]
- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Sorry for the generic question but I think you will see where I am going. Lets use a Protobuf application as an example. 

( I have Conanfied this example Protobuf project: https://github.com/leimao/Protocol_Buffer_Examples)

I am using CMake/Ninja with the Conan CMake "add-in"

```bash
conan_cmake_run(PROFILE
		WIN10-MSVS-15-Release.txt
		Protobuf_Win.txt
	REQUIRES
                protobuf/3.9.1@bincrafters/stable
                protoc_installer/3.9.1@bincrafters/stable
	IMPORTS ${CONANIMPORTS}
	BASIC_SETUP CMAKE_TARGETS
				)
```

So the WIN10-MSVS-15-Release.txt has some local settings, but the intent of Protobuf_Win.txt is to set the define variable of -D NOMINMAX for the compiler. It seems MSVS needs that flag to compile protobuf code on all versions.

So the way I try to do that is via

```Bash
[env]
*:CMAKE_C_FLAGS="-D NOMINMAX"
*:CMAKE_CXX_FLAGS="-D NOMINMAX"
```
Now I know I should be using 

```Bash
[env]
*:CMAKE_C_FLAGS=[ -D NOMINMAX ]
*:CMAKE_CXX_FLAGS=[ "-D NOMINMAX" ]
```

So that the -D is appended, but I can't seem to get the "" ( outright define) to work.

What I get from Conan look like:

```Bash
-- Conan executing: C:/Program Files/Conan/conan/conan.exe install . -pr=WIN10-MSVS-15-Release.txt -pr=Protobuf_Win.txt -g=cmake
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
*:CMAKE_CXX_FLAGS=-D NOMINMAX
*:CMAKE_C_FLAGS=-D NOMINMAX
*:CMAKE_Fortran_FLAGS_DEBUG="-nologo -c -Qzero -Qsave -Od -Z7 -MD -check:all -assume:nosource_include -assume:byterecl -warn:all -warn:nodeclarations -extend-source  -iface:default -iface:nomixed_str_len_arg -convert:big_endian  -traceback -fpe:0 -fpp -fpscomp:logicals -nopdbfile -debug:full -DUPPERCASE -DWIN -DWIN32X_11 -D USE_QT    -D USE_UG")
*:CMAKE_Fortran_FLAGS_RELEASE="-nologo -c -Qzero -Qsave -Od -Z7 -MD -check:all -assume:nosource_include -assume:byterecl -warn:all -warn:nodeclarations -extend-source  -iface:default -iface:nomixed_str_len_arg -convert:big_endian  -traceback -fpe:0 -fpp -fpscomp:logicals -nopdbfile -debug:full -DUPPERCASE -DWIN -DWIN32X_11 -D USE_QT  -D USE_UG")
conanfile.txt: Installing package
Requirements
    protobuf/3.9.1@bincrafters/stable from 'conan-center' - Cache
    protoc_installer/3.9.1@bincrafters/stable from 'conan-center' - Cache
Packages
    protobuf/3.9.1@bincrafters/stable:63da998e3642b50bee33f4449826b2d623661505 - Cache
    protoc_installer/3.9.1@bincrafters/stable:9e449b1ac4341c7bdc87f8a7efe81200c68c405b - Cache
```

But when I see the "ninja -v " compile line it looks like:

```bash
[2/7] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo /TP  -Iprotos -I..\protos -IC:\.conan\65f415\1\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /MD /O2 /Ob2 /DNDEBUG /showIncludes /Foprotos\CMakeFiles\addressbook.dir\addressbook.pb.cc.obj /Fdprotos\CMakeFiles\addressbook.dir\addressbook.pdb /FS -c protos\addressbook.pb.cc
```

So my "-D NOMINMAX" is no where in sight. 

I can only hope I am doing something stupid, because the concept of chaining profiles together seems EXTEREMLY powerful.

Maybe when I retire I can write a blog post.

Thanks and regards
Carl

**Comment by ShamanTcler** [comment]
Ok So I forgot the details ... duh

- Win 10, Version 1909 64 bit
- Conan version 1.29.2
- Cmake version 3.18.4
- Ninja version 1.10.1
- Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64 (though should not matter it is just the command line)

**Comment by memsharded** [comment]
Hi @ShamanTcler 

Sorry for the delay in responding.

I think the main issue is that CMake does not handle environment variables. What you are defining in your profile are pure env-vars, but CMake is not reading them at all. 

The recipes must explicitly read the environment if they want, and convert that to the adequate underlying build system variables. This means that the recipes you are using should probably be modified to do what you want. 

Please let me know if this makes sense and answers your question.

As some other recommendations, please let me point:

- The packages in ConanCenter without user/channel, are more maintained now, because they are automatically created from PR to https://github.com/conan-io/conan-center-index. For example the package https://conan.io/center/protobuf is now the one actively maintained by the community.

- We are proposing a new way to integrate with build systems, called the "toolchain()". It is very likely that we will propose some generic mechanism to pass arbitrary cxxflags to the underlying build systems. This effort is in early stage, but if you want to track it, please keep an eye on the changelog (every release there is progress in toolchains) and to the Github activity: https://github.com/conan-io/conan/issues?q=is%3Aissue+is%3Aopen+toolchain, as early design feedback is always very useful.

**Comment by ShamanTcler** [comment]
Thanks for the as always quick response.

For me the next step will be to modify the CMake to see if I can harvest environment variables that are being set. This is of course a work around until toolchains provide a way. (I read the change logs with every release)

Regarding your first bullet on user/channel ... yes we are all in a state of transition aren't we (Chuckle)

Again thanks for the response.

Regards
Carl
