### ISSUE TITLE
[question] "To fix this conflict you need to override the package 'gtest' in your root package." even though we have specified the version in root package

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#7864]
Our root package was recently changed from having:

```
        "gtest/1.8.0@PORT/stable", \
```

to:

```
        "gtest/1.8.1@bloomberg/stable", \
```

(Note: both patch change and different `user`)

Test builds with `--build=missing` of that change worked.

But in a recent attempt to rebuild that root package with an updated version of another package 'pal' we are seeing an error like:

```
version[1.1.42] commitAtVersion[4f28b4b]
ERROR: Conflict in scubaclient/1.6@PORT/stable:
    'scubaclient/1.6@PORT/stable' requires 'gtest/1.8.0@PORT/stable' while 'pal/2.15.0@PORT/stable' requires 'gtest/1.8.1@bloomberg/stable'.
    To fix this conflict you need to override the package 'gtest' in your root package.
gtest/1.8.0@PORT/stable: Not found in local cache, looking in remotes...
```

I understand from statements in tickets like https://github.com/conan-io/conan/issues/6812#issuecomment-610451941 that:

> Yes, the explanation of the error message ... is that there are different packages using different "zlib" packages. On one branch of the dependency graph, someone is still using the old zlib/1.2.11@conan/stable, while some other more modern dependency is using the newer zlib/1.2.11, and that is a conflict. Specifying which of the two ones you want, the conflict is resolved. 

But in this case we *are* specifying the version of gtest we want into our root package.  So why do we still see this error?

Conan version 1.26.0
Windows 2012 R2 Server
vs2015_14_v140_Debug
 
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This seems expected behavior. I am submitting a PR with a test that captures this, including the solution: https://github.com/conan-io/conan/pull/7880

**Comment by michaelmaguire** [comment]
Thanks for this. Do you think it would be possible to add a little extra info the the Conan error message in this case to make sure it's more evident in this case that it was a conflict between a requires= and a build_requires= ? It seems like a relatively easy mistake to make amongst a distributed group of developers.

**Comment by memsharded** [comment]
To explain the issue:

- The problem comes indeed because of mixing requires and build-requires of the same package in the same graph.
- Build-requires by definition are "private" to the package that declares them. They cannot and will not be affected by regular requires of the graph, they are not overriden by downstream requirements. This is the current behavior
- Regular requires are being correctly overriden to the new one.
- Even if they are not overriden, there is a protection mechanism, if 2 different dependencies, one regular require to gtest/1.8.0 and a build-require one to gtest/1.8.1 "land" at the same consumer (scubaclient), the protection mechanism will complain and block that, because when building it will be effectively impossible to link with both


The recommendation would be: do not mix the same package as requires and build-requires, specially if they are applied via those 2 different mechanisms to the same package.

As a short term solution for your issue, you still have a way: build-requires can be overriden from the profile [build_requires] section. You need to add there the same version you are putting in the recipe, and that will align all requires and build_requires of the whole graph to that same version and they will no longer conflict

But I would encourage to be consistent: if you plan to move gtest to "build_requires", you should start from the top, most upstream dependencies (those that do not depend on others) and move downstream, but not change it to a build-require directly in the middle of the graph when gtest can still be found upstream as a regular require.

I have had a look to the code, seems quite difficult to improve the error message, at the moment of the conflict the information is not there anymore, and it would need to backtrack a lot to recover it. Anyway, we are already planning the new graph resolution of Conan 2.0, so we will improve that there.

**Comment by ysmaoui** [comment]
related to this ticket 

I have currently the following situation
![build_requires_and_requires_overriding](https://user-images.githubusercontent.com/1141454/143257390-fe6e4778-c6df-4273-be77-1d1952d8d461.png)

someone has a hint  how to fix this ( maybe directly from the root conanfile.py, beacause it is difficult to change the other packages right now? ): How to make conan override the  requires for B ? 

Note: Version C/2.0 is needed by other packages, so I cannot really remove it from the root conanfile

**Comment by ysmaoui** [comment]
a more simplified abstraction of the problem I am facing 
![build_requires_and_requires_overriding_abstraction](https://user-images.githubusercontent.com/1141454/143265290-e623eaaf-398a-468a-a0e9-15ea24adf309.png)

**Comment by memsharded** [comment]
Hi @ysmaoui 

Maybe you want to open a new ticket, this one is closed.

I think the issue you are facing is that ``build_requires`` are private to the recipe ``requiring`` them. They are not overriden, the reason, as an example is that: "if I, "pkgA" needs to build cmake/3.15, I can ``build_require="cmake/3.15"``. The fact that some of my consumers need another version of cmake, and they could be ``build_require="cmake/other_version"``, doesn't mean that I am forced to use it".

The situation is very different to regular ``requires`` (libraries), because it is not that easy (in the general case it is impossible), to link against 2 separate instances of the same library.


If you want to redefine ``build_requires``, you can do it by adding a ``[build_requires]`` section in your profile.

**Comment by ysmaoui** [comment]
Thanks @memsharded   for your reply

I thought it might be better to keep the discussion in one ticket for future references. but if you prefer I can still open a new one :)


so a bit more context: in my case I am getting the same message "To fix this conflict you need to override the package 'C' in your root package."

and I am getting this error while trying to create a lock file ( with the option --build to consider all build requirements, in order to be able to build a system from scratch ( so build all requirements and build-requirements layer by layer until I get a full system )  -- the command I am using is `conan lock create ../conanfile.py -pr ${CONANPROFILE} --lockfile-out=${lockFile} --build`


the conan lock create command complains about B requires C/1.0 and  A1 requires C/2.0



> If you want to redefine build_requires, you can do it by adding a [build_requires] section in your profile. 

so this needs to be done directly in the profile? ( passed to conan lock create through -pr ? ) 
and overriding the build_requires cannot be done in the conanfile.py ?


thanks again for your support

**Comment by memsharded** [comment]
Yes, the issue is that you are mixing regular ``requires`` and ``build_requires`` of the same package. To better support this, Conan has developed the ``build`` and ``host`` context and profiles, which will be default in 2.0 and now you can opt-in doing ``--profile:build=myprofile --profile:host=myhostprofile``. Recommended for cross-building scenarios.  When doing this, the dependency graph can be different (with less conflicts), because build and host contexts are separated, and will not conflict.

> so this needs to be done directly in the profile? ( passed to conan lock create through -pr ? )
and overriding the build_requires cannot be done in the conanfile.py ?

Yes, it cannot be done in ``conanfile.py`` because defining there a ``build_requires`` has the meaning of defining it for yourself. As suggested above, the concept of overriding the transitive build_requires is not as evident as in the case of libraries. SO yes, you need to do it in the profile files.

**Comment by ysmaoui** [comment]
Thank you @memsharded  for your help,

using a [build_requires] section in the profile, helped indeed in overriding the build_requires requirements ( so package C/1.0 in my diagram above ) 

but it is not a solid solution.. better fix the mixture of requires and build_requires..

Thank you very much :)

**Comment by ysmaoui** [comment]
Hi @memsharded , 

one probably last question :P

the [build_requires] section  in the profile,  does it just override a build_require if it exists? 
or does it add the listed build_requires for all the packages ? 

asking because I started seeing errors like 
`ERROR: Loop detected in context host: 'X/xx.xx' requires 'Y/yy.yy' which is an ancestor too`

although X/xx.xx should not have any requirement ( it is a leaf in the dependency tree)

**Comment by ysmaoui** [comment]
replying to my previous question , I should read the documentation :)
https://docs.conan.io/en/latest/devtools/build_requires.html#declaring-build-requirements

we can specify build_requires for specific packages and not all the packages in the profile ( default is add to  all packages )

**Comment by ysmaoui** [comment]
ok.. as I have the situation describe here: https://github.com/conan-io/conan/issues/7864#issuecomment-977975058

A1 -- requires --> C
A1 --build_requires--> B --requires--> C 

the link B --requires--> C  was not really overridden by the [build_requires] section in the profile ( because it is a require not a build_require )  .. 

so back to square 0, not sure how to make conan override    B--requires-->C/1.0  with B--requires-->C/2.0

I believe the most straight forward way is to replace A1 --build_requires--> B  with A1 --requires--> B
