### ISSUE TITLE
[feature] Always declare CMAKE_BUILD_TYPE in the CMake build helper

### ISSUE THREAD

**Issue by uboot** [conan-io/conan#7884]
Currently the CMake build helper does not declare `CMAKE_BUILD_TYPE` for multi-configuration generators such as XCode or Visual Studio.

In our case however we have some CMake steps which rely on the `CMAKE_BUILD_TYPE` to be set. E.g. we copy files to `release/` or `debug/` depending on the build type. These steps do not work in case we generate for Visual Studio. As a workaround we currently set `CMAKE_BUILD_TYPE` explicitely in the Conan file but this feels more like a hack.

Note: our setup is such that we always only support one build type in a generated solution, i.e. we generate separate solutions for release and debug. We also deliberately chose not to use the Ninja generator because we are in the middle of a migration from Visual Studio solutions to CMake/Conan and want to keep the initial impact of this change as small as possible.

Are there reasons not to _always_ set the `CMAKE_BUILD_TYPE` if it is clear that there is only one build type involved (e.g. only debug dependencies have been installed)?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Johnnyxy** [comment]
Hi there,
for multi-configuration-generators this variable cannot be set. As at cmake-configuration-time the build_type is not known until actual compilation (CMake docs [here](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html#variable:CMAKE_BUILD_TYPE)).

You have to rely on CMake generator expressions like ```$<CONFIG>``` to get the actual build_type currently processed/built (CMake docs [here](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#variable-queries)).

Otherwise I would recommend that you set it on CMake invocation manually (e.g. via [CMake-build-helper](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html)). With this approach you can use this workaround as long as you need it until you have fully switched over to CMake.

```pyton

def build(self):
        cmake = CMake(self)
        cmake.definitions["CMAKE_BUILD_TYPE"] = str(self.settings.build_type).upper()
        cmake.configure()
        cmake.build()
        cmake.install()  # Build --target=install

```

**Comment by jgsogo** [comment]
@uboot you can print the commands Conan is running with the activating it in the config:

```
conan config set log.print_run_commands=1
```

As said in the previous comment, during the `configure` step of CMake that value is not known, but the proper value is provided in the `build` step via command line.

If this is still an issue, maybe you can share here a minimal reproducible example with the relevant bit of the `conanfile.py` and `CMakeLists.txt`.

**Comment by uboot** [comment]
Hi,
yes, the proposed workaround works for us. Thanks a lot!

**Comment by Alaeeala** [comment]
I am sorry but this is not a feature but a workaround. And there are two reasons why you shouldn't have done this:

1. You force the user to set a configuration which has no meaning for gcc, for example, but anyway one has to set it because otherwise conan complains. Instead of fixing the hack, now you impose a hack to the user. You could have set a default and deduce it from the build_type, that one has to use anyway

2. VS have the build type so that one has the freedom to choose between configurations, for example in the gui. I think that with this you are breaking that

3. Imposing conditions on the cmake commands of the user, which is a different interface,  just to satisfy your design needs, fells like a sign of a bad design

**Comment by memsharded** [comment]
Hi @Alaeeala 

This is a closed ticket from 2 years ago, about the legacy ``CMake`` build helpers that is legacy, superseded in 1.X by ``from conan.tools.cmake import CMake`` new helper and removed in 2.0.

If you have any question or issue about the new integration, please create a new ticket. Thanks!

**Comment by maxpla3** [comment]
> Hi @Alaeeala
> 
> This is a closed ticket from 2 years ago, about the legacy `CMake` build helpers that is legacy, superseded in 1.X by `from conan.tools.cmake import CMake` new helper and removed in 2.0.
> 
> If you have any question or issue about the new integration, please create a new ticket. Thanks!

I'm on conan 2.0 and CMAKE_BUILD_TYPE is still not set by conan.
```
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps


class HelloConan(ConanFile):
    name = "helloworld"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"

    # defines folder structure for configuration and build
    def layout(self):
        cmake_layout(self)

    # prepares cmake as generator
    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()
		

    # performs configuration and build with cmake
    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
		
    # installs package
    def package(self):
	    cmake = CMake(self)
	    cmake.install()
```
When executing `conan build . -s build_type=Debug` the cmake variable CMAKE_BUILD_TYPE remains unset.

**Comment by memsharded** [comment]
Hi @maxpla3 

Please create a new ticket for this. You'd need to report also:
- OS, compiler, compiler version
- Full output of the command

Please recall that in VS, the CMAKE_BUILD_TYPE is not defined, because it is a multi-config system
