### ISSUE TITLE
[question] deploy method not executed with conanfile.py path in conan install

### ISSUE THREAD

**Issue by sduraisamy** [conan-io/conan#7911]
I want to install dependencies package to the user path from the local cache. 

my recipe works when i give as package as reference in conan install but when i give the conanfile.py path its not executing the deploy method.

conan install pkg/version@user/channel(deploy method called - Working)
**conan install ./pkg/path_to_conan_recipe/conanfile.py (Not working)**

I have used copy_deps() to get the required data from dependencies.
self.copy_deps("*", src="data/", dst="data/", keep_path=True)

Could you clarify this?.

**Comment by memsharded** [comment]
Hi @sduraisamy 

Yes, that is exactly the difference between ``deploy()`` and ``imports()``.

- ``deploy()`` is for your own package, like ``conan install <pkg-ref>``.
- When you have a local conanfile.py, in a path, it is not a package. You cannot "deploy" it, because it is not packaged. 
- Local conanfile.py can ``imports()`` from their dependencies.

**Comment by sduraisamy** [comment]
@memsharded, Thanks for the quick answer. Now it clear for me.
