### ISSUE TITLE
[question] how to manage toolchain extensibility, specially by inheritance of CMakeToolchain

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#7912]
With the hierarchy defined, we have a factory function that does:

```python
def CMakeToolchain(conanfile, **kwargs):
    os_ = conanfile.settings.get_safe('os')
    if os_ == 'Android':
        # assert cross_building(conanfile)  # FIXME: Conan v2.0, two-profiles approach by default
        return CMakeAndroidToolchain(conanfile, **kwargs)
    else:
        return CMakeGenericToolchain(conanfile, **kwargs)
```

For users wanting to customize the built-in CMake toolchain, that would mean to provide their own factory function, with their custom derived classes too, which might not be very evident/ergonomic, I think we need to consider this.

**Comment by ohanar** [comment]
I would broaden this more generally to build helpers as well. When rolling our own custom support for the intel compiler, I managed this by introducing a conan package that contained a few subclasses of various build helpers that were used pervasively throughout our recipes via python_requires. This wasn't ideal as it was intrusive to the recipes when all I really wanted to do was extend support to fit our custom needs.

Just spitballing here, but one idea would be to introduce some sort of hook that would allow customizing the contents of the conans module. E.g.
```python
def pre_import(vanilla_conans):
    def CMakeToolchain(conanfile, **kwargs):
        # do custom stuff
        return vanilla_conans.CMakeToolchain(conanfile, **kwargs) # fallback to builtin one
    return locals()
```

**Comment by jgsogo** [comment]
It is a bit early as the architecture can (and should change) in future releases, so these are just speculations, but it is great to know about expectations and pros/cons we might not think ourselves alone.

---

I see different extensibility points:

## Providing Python source code:
 * **python_requires**: this is straightforward and doesn't require anything on our side, nothing Conan can affect:

   ```python

   class Recipe(ConanFile):
      python_requires = "toolchain/cool"

      def toolchain(self):
         CoolToolchainClass = self.python_requires["pyreq"].module.CoolToolchain
         tc = CoolToolchainClass(self)
         return tc.write_toolchain_files()
   ```

 * Something **pluggable** from the cache, like the custom generators. The user could place some Python code somewhere in the cache and Conan will load it and make it available for every recipe. This is to be defined, **how to extend Conan with Python**:
    + maybe Conan loads everything from a folder `<cache>/tools` into a module `conans.user` so you can use it in the recipes:

      ```python
      from conans.user import tools as user_tools

      class Recipe(ConanFile):
         def toolchain(self):
            tc = user_tools.MyToolchain(self)
            tc.my_custom_method()
      ``` 

     + maybe we decide a different way to extend Conan with Python code 🤷 

## Providing templates
 * **templates in the cache** (no need to modify the recipe, would affect every package): there is no need to know what is behind the _function-factory_ `conans.CMakeToolchain`. Depending on the settings, Conan should instantiate a different `toolchain` object and probably it should use different templates. Now these templates are hardcoded into those toolchain classes, but those classes should provide only the name of the template and Conan can look for it in the `<cache>/templates/` folder.

   For example, given `os:build=Windows + os:host=Android` Conan might look for template file at `templates/toolchains/android_win.cmake`, if it is found (**provided by the user**) it will use that template file, if it is not found Conan will use the hardcoded template we are currently using.

   This approach is the same we are already using for the `conan search --table` and `conan info --graph`

 * **Hardcode the template** in the recipe: 

   ```python
   class Recipe(ConanFile):
      def toolchain(self):
         tc = CMakeToolchain(self)
         tc.template_name = "toolchains/android.cmake"
         return tc.write_toolchain_files()
   ```

   Conan will look for the template in different folders: working directory (`build_folder`), then inside the cache folder.

 * Override the **template in the profile**: it would affect every recipe using this profile

   ```
   [settings]
   os=Android
   os.api_level=12

   [config|toolchain_template|...]
   toolchain=toolchains/android.cmake
   zlib:toolchain=toolchains/android_zlib.cmake
   ```

   Same resolution order as the previous one: working directory, then cache folder.

 * Override the **template from a `build-requires`**:

   ```python
   class AndroidNDK(ConanFile):
      def package_info(self):
         self.config.toolchain = os.path.join(self.package_folder, 'android.cmake')

   --- 

   class Recipe(ConanFile):
      build_requires = "android/version"

   ```

   The `build-requires` provides a template name, it will go into some kind of `config` data variable (like the one from the profile in the previous bullet point). It will be used by all recipes using the build-requires.

---

I'm really excited about the template-based ones, since they are really powerful if you want to play with the context and, at the same time, they work if the file provided doesn't contain any Jinja2 syntax at all (a plain CMake toolchain file).

**Comment by memsharded** [comment]
> Providing Python source code

The problem I see with this approach is this: I expect users wanting to do a small modification to our own toolchain files, because they want to add something here and there, and they would like to be able to code their logic in python. The approach with:

```python
def toolchain(self):
      CoolToolchainClass = self.python_requires["pyreq"].module.CoolToolchain
      tc = CoolToolchainClass(self)
```

Means that in their python code in the "pyreq", the ``CoolToolchain`` is NOT a class that extends anything, it is also a factory function that internally uses some other classes (Android, Generic, iOS), which extend from our built-in classes.
Doesn't seem very practical/ergonomic.

> Something pluggable from the cache, like the custom generators. The user could place some Python code somewhere in the cache and Conan will load it and make it available for every recipe. This is to be defined, how to extend Conan with Python:

This **is a feature already**. You can put python code inside  a ``python`` folder in the cache and it will be automatically in the path. You can natively ``import filename`` it from your recipes.

This is not very publicized, actually I would like to deprecate and remove it in Conan 2.0, in favor of python_requires. Having some code there that is not versioned, that can affect any recipe, etc., sounds a bit problematic. We can discuss it, maybe ask for feedback to the Tribe.

> Providing templates

For this approach, it seems that we would need to inject a lot more things into the templates rendering: settings, options, config... everything that the users might need to implement their custom logic of their toolchains.

**Comment by jgsogo** [comment]
> > Providing Python source code
> 
> The problem I see with this approach is this: I expect users wanting to do a small modification to our own toolchain files, because they want to add something here and there, and they would like to be able to code their logic in python. The approach with:
> 
> ```python
> def toolchain(self):
>       CoolToolchainClass = self.python_requires["pyreq"].module.CoolToolchain
>       tc = CoolToolchainClass(self)
> ```
> 
> Means that in their python code in the "pyreq", the `CoolToolchain` is NOT a class that extends anything, it is also a factory function that internally uses some other classes (Android, Generic, iOS), which extend from our built-in classes.
> Doesn't seem very practical/ergonomic.
> 

`CoolToolchain` can be a class or a factory function, as long as the _call_ to `CoolToolchainClass(self)` returns an object, it can be whatever the user wants it to be. Also, the implementation can inherit any of the classes we decide to document. One example using those different approaches:

 * it can be a class:
   ```python
   # Inside the python_requires

   from conans.client.toolchain.cmake.android import CMakeAndroidToolchain

   class CoolToolchain(CMakeAndroidToolchain):
       def _get_android_abi(self):
           return "my-very-loved-abi"
   
   ```

 * or it can be a function (with fallback to our factory):

   ```python
   from conans.client.toolchain.cmake import CMakeToolchain
   from conans import tools

   def CoolToolchain(conanfile, *args, **kwargs):
      if conanfile.settings.os == "Android":
         class MyCoolestToolchain:
            def write_toolchain_files(self):
               tools.save("mycoolest_toolchain.cmake", "my-content")

         return MyCoolestToolchain()

      return CMakeToolchain(conanfile, *args, **kwargs)

**Comment by memsharded** [comment]
This was solved some time ago by moving ``CMakeToolchain`` to a composition approach, based on extensible "blocks", please check latest docs, this can be closed.
