### ISSUE TITLE
[question] Empty CONAN_LIBS when use CONAN CENTER 

### ISSUE THREAD

**Issue by VladAdGad** [conan-io/conan#7928]
Hi! I found a strange relationship with repos and cannot solve it.
So. When I want to use boost or carch2 from the conan center repository my CONAN_LIBS is empty, still I can find in build forder some information about includes lib and root path.
If I change my conan.txt to using boost or catch2 from bintray jfrog repository everything works like a charm. I know there is a little different .py file "package_info". 
Could you explain to me what is going on with it, cuz I can't figure out.

**Comment by memsharded** [comment]
Hi @VladAdGad 

Sorry, it is not very clear. If you can clearly explain the steps to reproduce:

- Include first the steps that work (I assume using ConanCenter packages). The exact command line that you are using, specifying the conanfiles that you are using as well
- Then include the steps that do not work, which packages are you using and how?

We need something to reproduce in order to know what is happening. In many cases a very simplified or reduced conanfile is enough to show the behavior, but detailed instructions to reproduce are necessary.

**Comment by memsharded** [comment]
Closing as inactive
