### ISSUE TITLE
[feature] Restore support for : conan source <package_ref>

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#7959]
At some point, the ability to accept a package reference was removed from a number of commands including `conan source`. 

During recent discussions with several enterprise users and @memsharded , we recognized that Conan has a pretty exciting and powerful capability to address some common challenges for these use cases, which has currently gone un-explored.  When trying to explore it, we discovered that `conan source` doesn't accept the `package_ref` which would be required for these use cases. The request here is to restore that capability to unblock this category of use-cases. 

The general concept is to enable download and re-build specific versions and revisions of existing packages from source in user space without needing to manually and separately checkout the conanfile and/or sources manually.  We can already do everything involved in Conan cache with `conan install --build`.  This command is downloads the desired `conanfile.py` and required sources for any of the possible supported source mechanisms, which makes it really great and universal.  However, there is no reasonable way to get the sources into user space and build them from there.  There is a way to do this, which is to use other conan commands to determine the path to the `conanfile.py` in the conan cache, then copy it out to user space (and also copy/extract conan_sources.tgz if it's an `exports_sources` case), and then run `conan source` on the copy of the `conanfile.py`. However, this is pretty unreasonable. Restoring the `package_ref` support for the `conan source` command would make this process far more simple and robust. 

Of note. Restoring this feature for this case might also require some additional thought and implementation details. That is expected, and should not be a problem. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
If this is going to be considered, I would probably suggest 2 things, in order to simplify and make it tractable:

- This would only be available for recipes using the ``scm`` component, and Conan can do a checkout in user spaces of those coordinates. No fetching, copying things from the cache or from the server that can be modified without source tracking. Furthermore, the "export" processes are one way, it can be impossible to revert them, plus there can be many other things that will not be reproducible.
- Maybe we want to use a different name/command than ``source()`` because that is already too associated at executing the ``source()`` method locally, and it seems the first step of cloning the sources is a complete different thing.

**Comment by solvingj** [comment]
I'm glad to see there is any support at all for the idea. I'm sad you only want to support `scm`.  If not supporting `source()` and `exports_sources()`. I no longer think this is worth doing.

**Comment by memsharded** [comment]
> If not supporting source() and exports_sources()

The problem with them is that they are not reversible, not reproducible. I wish it would be possible, but I don't see how, as they are both 1 way mechanisms. After you got a local copy somehow from the Conan (cache/server), it will be unusable:

- Local changes you do locally in that copy will NOT be used when the ``source()`` method is called, as it will fetch the old copy from the server. You have no way to commit local changes to the code to the server, because you have no coordinates.
- Source from ``exports_sources()`` is also pattern based and includes removal of paths. Local changes to those files have a good chance of not being exported to the cache again when creating the package.

I think that if we standardize around SCM under these assumptions:
- We can assume that every recipe will live in source control somewhere.
- The SCM component can capture the coordinates from source-control.
- It has value to be able to "checkout" a package that you have on your dependency graph, based on the Conan package reference.
-  It is ok to use ``source()`` to do other stuff. It doesn't mean that the source must be in the same repo of the recipe. But the SCM can get the coordinates of the recipe, executing ``conan source`` will get the sources from the secondary location correctly again.
- So something like ``conan checkout <pkg-ref>`` + ``conan source`` would probably cover all cases, just by assuming the ``scm`` attribute is defined to get an entry point of the recipe sources, even if the package sources are elsewhere.

I'd say it is worth to discuss this case.
