### ISSUE TITLE
[feature] reuse existing shortened subdirectories in C:\.conan when using short_paths

### ISSUE THREAD

**Issue by Artalus** [conan-io/conan#7995]
**The setup**:
We run multiple Jenkins jobs on Windows building stuff with CMake and Conan, with `.conan` home for each job residing in its workspace. We have to use `short_paths` with a single shared `J:\.conan` shortener directory (we rely on fact that on each physical node there cannot be parallel tasks racing for this directory). Many jobs reuse the results of a previous build (repo already checked out, object files compiled, etc.), but have an option of a clean rebuild that simply wipes the workspace before build.

**Problem**:
On clean rebuild the CONAN_USER_HOME is wiped, making conan run a full reinstall process. However it also creates new subdirectories for packages in `C:\.conan`. A single `conan install` for a single `build_type` currently results in about 0.5G of binary data, which may soon skyrocket on its own as we move more stuff to Conan. Most jobs build both Debug and Release and can re-run with "clean" option multiple times a day, which quickly leads to even more space overhead than splitting `CONAN_USER_HOME` for each job separately.

**Cause**:
There is this code in the path shortener in `util/windows.py : hashed_redirect`:
```python
    for length in range(min_length, max_length):
        redirect = os.path.join(base, full_hash[:length])
        if not os.path.exists(redirect): # <<<
            return redirect
```
Since Jenkins basically runs `rm -rf $WORKSPACE` and does not account for `E:\.conan` contents, on the next run Conan will detect existing `E:\.conan\123abc` and instead of reusing will create new `E:\.conan\123abc4`, then `E:\.conan\123abc45` and so on.

**Expectations:**
IMO it'd be more reasonable to instead treat the folder as dirty, send a warning to the log and clean it up. If Conan couldn't identify the folder as the requested one (e.g. there was no real_path.txt or it pointed to another path than the one requested) - send another warning and resort to another name, or just exit immediately with an error.

**Comment by jgsogo** [comment]
Hi, @Artalus !

PR https://github.com/conan-io/conan/pull/7986 should fix the problem related to dangling folders in the short-paths directory when running ``conan remove``. Of course, it doesn't fix the issue if Jenkins is removing the Conan cache instead of using Conan to clean it.

The problem with the ``real_path.txt`` is that it only tells Conan about the folder in the local cache, we could identify it is the same folder for which we are trying to create the short-path and use it... BUT, folders in the Conan cache doesn't contain recipe/package-revision, the ``real_path.txt`` is lacking that information, we cannot safely reuse that short-path folder once the source one has been removed. In fact, we would need a full lockfile stored there to be sure that the files in the short folder can be used by the new instance (package binaries use short-paths too).

What about removing dangling short-paths folders? I'm not sure if we can face some edge cases trying to be too smart. Maybe that short-path belongs to another instance of Conan and we cannot check if the _real path_ exists (permissions, some link/mounted unit when the job starts,...).

Reusing short-paths directories can be very challenging (need to check a lockfile, environment,...) and removing dangling folders maybe is something to implement outside Conan if you know that they are not used if the _real path_ is not accessible.

**Comment by Artalus** [comment]
We are currently cleaning up the `short_paths` directory on timer along with all of the workspaces, yes. I was just hoping there could be another way of reducing its "expansion speed".

I do not fully understand though. Conan have some underlying mechanisms for detecting folder as "dirty", which leads to its removal and recreation. Can't the same be reused for short_paths and virtually everything? Like, if we realize that during `conan install` while actually installing/building binaries we end up "preparing" the already existing directory, and it contains some files, shouldn't Conan just always wipe those away with a warning anyway?

**Comment by jgsogo** [comment]
We mark folders as _dirty_ when we start an operation inside them, if something goes wrong the _dirty_ mark stays there and next time Conan runs it will remove the directory before using it again. I would expect Conan to remove the corresponding `short_paths` folder when removing a dirty one (after #7986).

Now I think I understand something that could be improved. If your CI uses a short_paths location outside the workspace and Conan fails, there will be some dirty folders in the Conan cache (removed by the CI itself), but there will be also many dirty folders in the short_paths location, it is true that they are dirty, they are not usable, and the dirty mark was removed together with the workspace. No one will ever know the folder is dirty and it won't ever be used by Conan.

I think that Conan shouldn't traverse all the short_paths location looking for dirty folders every time it runs (we can create a dedicated command, or you can write your own using the new experimental CLI), but if we leave the dirty mark there, your script (or the custom command) could look for those dirty folders and remove them, saving space, and removing only folders that won't be used. It will alleviate your pain a little bit. Yet, one big problem remains: what to do with folders that are not dirty, how to identify them.

**Comment by memsharded** [comment]
Short-paths were completely dropped in Conan 2.0, closing this as outdated.
