### ISSUE TITLE
More idiomatic definition of dev/production conditional dependencies

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#80]
The current mechanism is to define options for it, then use such options to conditionally require (or not) a certain dependency.

It could be easier and more idiomatic if a higher level of abstraction, as specifying a global (dev/production/package) scope for all packages, and packages could use such scope for conditionally defining dependencies.

Requested in https://github.com/conan-io/conan/issues/79, but it is not the first time, so I think it is an interesting feature to develop

**Comment by bjoernpollex** [comment]
Another possibility (besides scopes) is to add the concept of targets, which could have their own dependencies. I think this opens a bunch of interesting possibilities:
* targets could depend on each other, so that a target for the tests could depend on the target for the library
* projects could depend on specific targets, rather than all or nothing (e.g. in Boost)
* the `build`, `package` and `package_info` functions could take a list of targets and perform only the work required for these specific targets
This would is complex to implement, but I think immensely powerful. What do you think?

**Comment by memsharded** [comment]
Quite interesting. OTOH, I'm afraid about the complexity, both about the implementation, but also about end-users UX. Will users have to depend on Lib/version@user/channel:target? Doesn't seem a typical pattern in other package managers (other languages than C++, I mean). Let's think about the potential design of the solution and usage, thanks for the idea!

**Comment by bjoernpollex** [comment]
One possible solution to the UX problem is that packages could specify a default target (which could be `all`). The problem with C++ is that, due to the lack of proper package management (before Conan came along), we have a large amount of legacy projects that pack several artifacts (libraries, executables) into a single distribution. One way of managing this kind of legacy burden is to allow depending on specific targets. 
That being said, I fully acknowledge that this is quite complex to implement. The UX I think would not be a problem, because this feature would mostly be used by projects that are very complex in the first place.

**Comment by memsharded** [comment]
I have been thinking about this a bit, and it also seems to arise kind of required feature from usage. Package creators seems to be interested in differentiating the scopes of development and releases. Not only for the current opened project (may it be a package or not) under user folders, but also for packages being built in the local conan storage.

I have thought on a generic set of scopes, but realized that such design was speculative, so I think it is better to Keep It Simple (Stupid), and that a simple thing could be of great benefit without introducing huge complexity on conan codebase and user UX. So my proposal would be:

- Introduce a ``dev_mode`` attribute in each **conanfile** object. Each package will have its own ``dev_mode`` value.
- Package creators can just check ``self.dev_mode`` value to decide to depend on additional dependencies (in ``config()``) or to build and run tests (in ``build()``)
- It is the responsibility of the package creators to make sure that they do nothing that actually changes the package being created. That is, the hash (SHA1) of the binary package will not be affected by this ``dev_mode``. E.g.: depending on Catch to run some tests, shouldn't change the libraries at all.
- Normal dependencies **affect** the hash (SHA1). A new dependencies mode (similar to "private") could be introduced to handle this (the current mechanism is to remove them in ``conan_info()``, but it is not very intuitive). Maybe use "dev_requires" or the like.
- Conan will manage to assign the correct ``dev_mode`` value, by default ``True`` for the user consumer project and ``False`` otherwise (normal dependencies inside the conan cache)
- The user will be able to set ``dev_mode`` for any specific package inside the conan cache, in the command line. Something like ``conan install . --dev=MyPackage --dev=OtherPackage``

I think this should be simple enough, but cover most of it. Feedback welcome (cc/ @smspillaz , @lasote )

**Comment by smspillaz** [comment]
@memsharded To me this proposal makes sense.

I have started using `-o dev=True` in my own packages and it seems to work quite well for me, so it would be good to have a standard.

One thing which I would add to this proposal is that running `conan install` in a directory sets `dev_mode` for the top-level module and installs the `dev_dependencies` by default.

`dev_mode` should not get set for any other modules in the tree - only the top level one. The same should apply to `dev_dependencies`.

**Comment by lasote** [comment]
Sounds good but I'm not totally convinced about not having a generic mechanism to add other "scopes", maybe a flag or definition system for conanfiles. I mean:

conan install --fdev OpenSSL --fmyscope zlib

In the conanfile.py maybe you can access to flags:

if self.flags.dev:
   blablabla

(I don't like the "flag" name)

Totally agree about the need to specify the "scope" adding requirements, messing with the sha and conan_info is too complex.

Totally agree about having always present a "dev" flag, auto-setted in a project under construction.

I don't know, I think this way conan could be more generic and prepared for more complex use cases.

**Comment by memsharded** [comment]
@smspillaz Totally agree. Setting of dev_mode is automatic in the way you point out. 
@lasote Fair enough, I think I can do it without too much extra complexity. 

I will come with a proposal PR soon.

**Comment by memsharded** [comment]
Submitted PR: https://github.com/conan-io/conan/pull/290
