### ISSUE TITLE
[feature] Keep same paramenter pattern for build helpers (Conan 2.0)

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#8030]
When using a build helper, sometimes I need to check the documentation to remember if it uses `configure_dir` or `configure_folder`, or `source_folder` or `source_dir`.

I would like to see the same pattern, and keep the same names for any new build helper. I would say `configure_folder`, `build_folder` and `source_folder`.

[AutoToolsBuildEnvironment](https://docs.conan.io/en/latest/reference/build_helpers/autotools.html#configure):

```python
def configure(self, configure_dir=None, args=None, build=None, host=None, target=None,
              pkg_config_paths=None, vars=None)
```

[CMake](https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#configure)

```python
def configure(self, args=None, defs=None, source_dir=None, build_dir=None,
              source_folder=None, build_folder=None, cache_build_folder=None,
              pkg_config_paths=None)
```

[Meson](https://docs.conan.io/en/latest/reference/build_helpers/meson.html#configure)

```python
def configure(self, args=None, defs=None, source_folder=None, build_folder=None,
              pkg_config_paths=None, cache_build_folder=None, append_vcvars=False)
```

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Yes, this makes sense. Not for Conan 2.0, this is something that we want to make sure it is implemented correctly in the new toolchains.

**Comment by memsharded** [comment]
This issue is obsolete. There are completely new build system integrations, that don't define those parameters at all, the folders are specified in the ``layout()`` method instead. 

The legacy integrations that this issue refers to, won't be modified (that would be breaking), and instead the new ones in https://docs.conan.io/en/latest/reference/conanfile/tools.html should be used (available in 1.X), because they will be the only ones surviving in 2.0
