### ISSUE TITLE
[bug] Remove cryptography version restriction on macOS

### ISSUE THREAD

**Issue by alanb-sony** [conan-io/conan#8031]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 10.15.0
  * Compiler+version:
  * Conan version: 1.31.0
  * Python version:3.8.6

The latest version of the cryptography module now installs cleanly on macOS so should the restriction added due to issue #431 now be removed?
This causes a conflict with authlib which requires (though doesn't declare see https://github.com/lepture/authlib/issues/290) version 2.6.0 or later but conan requires less than 2.4.0

**Comment by memsharded** [comment]
Hi @alanb-sony 

This has been fixed already in https://github.com/conan-io/conan/pull/7962, and will be released in Conan 1.31.1 asap (hopefully tomorrow).

Is there a bug in your report, or you are actually referring to Conan 1.13 and not 1.31? We don't plan to backport this down to 1.13... 😅

**Comment by alanb-sony** [comment]
Yes sorry I was using 1.31.0. Is there a good reason for keeping a version restriction in for macOS? Wouldn't it be simpler to just remove the restriction and make it the same as other platforms?

**Comment by memsharded** [comment]
Yes, the cryptography dependency is added only for Darwin, not for other platforms, because that is the only platform that requires it, otherwise it will have issues communicating to servers. The valid ranges in Conan ``requirements.txt`` typically respond to the moment in time they are introduced, and to feedback of users about failures, incompatibilities, etc. Completely removing restrictions would indeed be simpler for us, but in practice it proved to be problematic. That means that as the ecosystem evolves, Conan also needs to evolve, and have its requirements updated too. 

I think this issue can be closed now, #7962 was merged, and this will be released today, please upgrade to 1.31.1 when it is out. Thanks!

**Comment by alanb-sony** [comment]
Ah OK, I was sure I saw an unrestricted requirement for cryptography for other platforms, maybe I imagined it or it was in a historical version when I was investigating the issue
