### ISSUE TITLE
[question] How to specify system lib dependency in conanfile.txt / conanfile.py

### ISSUE THREAD

**Issue by stephanvalentan** [conan-io/conan#8044]
Hello,

we are in the process of integrating conan into our cmake-based build system. In our case we have created some packages that have some system-dependencies which are handled via the `self.cpp_info.libs` and `self.cpp_info.system_libs` attributes of the `conanfile.py`.

I was wondering, is there a similar mechanism on the consumer side as well? Our consuming project depends on the packages but also on some system-libraries itself, and i haven't found a way to encode this information via conan.
So at the moment it is necessary to maintain the dependency information in two different places, the `conanfile.txt` and in the `CMakeLists.txt`, which is a bit surprising. 
I've also tried using a consumer-side `conanfile.py`, but this also didn't work, it seemed like the `package_info(self)` method wasn't even executed.

Is there a good way of handling this situation, or is it really needed to maintain the two different dependency information locations? 

Thanks a lot, Stephan

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @stephanvalentan 

> I was wondering, is there a similar mechanism on the consumer side as well? Our consuming project depends on the packages but also on some system-libraries itself, and i haven't found a way to encode this information via conan.

I am not sure what you mean. When you add some ``system_libs`` information, it will be encoded in the different generated files by generators, like the ``cmake`` generated ``conanbuildinfo.cmake`` or the ``xxxxConfig.cmake`` generated by ``cmake_find_package_multi``. Using those files will pull the information, no need to add them manually in your consumer CMakeLists.txt too.

> I've also tried using a consumer-side conanfile.py, but this also didn't work, it seemed like the package_info(self) method wasn't even executed.

The ``package_info()`` is a method to define the information for consumers only. When you define it in your local ``conanfile.py`` is not used, because you have no consumers, you are not even a package yet. It is only  used when you create a package for it, and someone depends on you. To define things for your current package, you need to use the ``toolchain()`` method.

So a couple of questions:

- Which generator are you using in the consumer side?
- Can you check in the generated files, and make sure that the system_libs information is there?

For things that require more modeling than just the ``-lsystem_lib``, it is possible and useful to define "proxy" recipes, a ``libname/system`` package recipe that can define its own ``package_info()`` pointing to the system resources you want, instead of building anything from source.

Please let me knows if this helps. Thanks!

**Comment by stephanvalentan** [comment]
Hi, thanks for the quick reply! 
I'm sorry for not making this clear, i was talking about the cmake(multi) generator.

I was already chatting with some guys in the slack channel, to clearify what I wanted to I wanted to achieve:
Our consuming project both depends on a conan package, as well as an _unrelated_ system lib, say `WinTrust.lib`. 
I thought it would be neat to be able to just write the consumer conanfile like: 
```
[requires]
package/1.2.3@whatever/stable
WinTrust.lib
```
So that the first line would be resolved using the cache/remote, while the second line would just be added to the `CONAN_LIBS` cmake variable. This way the consuming projects dependency information would be collected in one single place, the `conanfile.txt`. I hopes this makes clear what i would have hoped for.

The proxy-package approach also was suggested in the slack-channel, and it feels like a very conan-idiomatic and neat solution, but also a bit like an overkill for essentially just adding a `target_link_libraries()` call. 
So i guess i'll really just pass all package-dependencies to conan while handling all others to plain cmake's `find_library()` 😃

**Comment by memsharded** [comment]
> So that the first line would be resolved using the cache/remote, while the second line would just be added to the CONAN_LIBS cmake variable. This way the consuming projects dependency information would be collected in one single place, the conanfile.txt. I hopes this makes clear what i would have hoped for.

Yeah, but that would be much trickier and full of rough edges and corner cases than it seems:

- A ``conanfile`` can work for different configurations, profiles, settings, etc. Adding a library name directly in the conanfile will likely make it single-platform, as library names might change between platforms.
- There is no control to whom will receive that information. With modern generators like ``cmake_find_package``, you will get defined targets for each dependency and transitive dependency. Different apps or libs can decide which dependencies they are linking. How to model that for the ``WinTrust.lib``?

If you have such dependency, these would be the alternatives that make sense:
- If it is not a package, it is something that you really don't want to be managed by a package manager. You are doing a heavy coupling between build-system and package manager. It would be much better to keep ``WinTrust.lib`` in the realm of the build scripts only
- If you want, you can create an almost empty Conan package recipe for ``WinTrust`` that will add that information in the ``package_info()``. In that way you will have the right location so Conan can manage it in a multiplatform way if necessary, you can have other packages explicitly use it (because it is likely that it will become necessary to be used in other packages), things like version conflicts can be managed, etc.

**Comment by stephanvalentan** [comment]
I totally agree that there are a lot of issues, i just thought that with conan being as smart as it is, that there already exists a easy built-in way of handling this situation. 
E.g. what comes to my mind is that the `WinTrust.lib` dependency could be wrapped  in a lightweight proxy package as you suggested, but automatically such that the dependency just resides in the local cache. From this point on all usual conan-workflows would work and the dev of the consuming package wouldn't need to create a "real" package and upload it to the remote...
Anyways, i'll find a way of handling this, thanks for your help and for your work on conan 😃

**Comment by memsharded** [comment]
> I totally agree that there are a lot of issues, i just thought that with conan being as smart as it is, that there already exists a easy built-in way of handling this situation.

Conan is not that smart, it is a "barbarian"! 😄 Actually it is kind of true, we try hard to have Conan not be too smart, do not do magic, but try to be as explicit and simple as possible. Not always possible, but at least it is design intent.

>E.g. what comes to my mind is that the WinTrust.lib dependency could be wrapped in a lightweight proxy package as you suggested, but automatically such that the dependency just resides in the local cache. From this point on all usual conan-workflows would work and the dev of the consuming package wouldn't need to create a "real" package and upload it to the remote...

That is the kind of magic we have learned (sometimes the hard way) that it doesn't scale well, and having it explicitly solved in a user defined conanfile.py recipe quickly pays off. Initially sounds like an extra burden, but it will very quickly require to deal with some rough edges and you will end with a recipe for WinTrust like this:

```python
class WinTrust(ConanFile):
     def package_info(self):
         if self.settings.os == "Windows":
               self.cpp_info.includedirs = "C:/WinTrust/include"
               if self.settings.build_type == "Debug":
                      self.cpp_info.libs = ["WinTrustD"]
              else:
                     self.cpp_info.libs = ["WinTrust"] 
        else:
             self.cpp_info.libs = ["wintrust"]
```

Which would be something that otherwise would be extremely painful to model in the consumer side, and will create unnecessary complexities in different places of your build scripts.

> Anyways, i'll find a way of handling this, thanks for your help and for your work on conan 😃

Cool, thanks for the feedback and the kind words! I am going to close this at the moment, but don't hesitate to comment, re-open or open a new issue if you need further help.

**Comment by uilianries** [comment]
Hi @stephanvalentan !

You can take a look on [Xorg recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/xorg/all/conanfile.py), where a system package is packaged as a proxy, so you can declared it directly in your conanfile.txt or conanfile.py without problems.

**Comment by stephanvalentan** [comment]
Cool, thank you!
