### ISSUE TITLE
[question] find_package with cmake_path generator

### ISSUE THREAD

**Issue by blackliner** [conan-io/conan#8050]
According to https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_paths_generator.html, the main reason for using `cmake_paths` is to keep conan specific code out of the CMakeLists.txt

When I tried to get it running with Catch2, I immediately failed, because apparently the ConanCenterIndex is purging custom recipes (according to a comment [HERE](
https://github.com/catchorg/Catch2/issues/2080) ) and creating generic ones. This generic version of the recipe is somehow missing the very important `Catch2Config.cmake` file to make all of this work.

`conanfile.py`
```
from conans import ConanFile, CMake
class Deps(ConanFile):
   settings = "os", "compiler", "build_type", "arch"
   requires = "catch2/2.13.3"
   generators = "cmake_paths"
```

Errormessage from CMake
```
Could not find a package configuration file provided by "Catch2" with any
  of the following names:

    Catch2Config.cmake
    catch2-config.cmake
```

Content of `conan_paths.cmake` (replaced home with ~)
```
set(CONAN_CATCH2_ROOT "~/.conan/data/catch2/2.13.3/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9")
set(CMAKE_MODULE_PATH "~/.conan/data/catch2/2.13.3/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/Catch2" ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_LIST_DIR})
set(CMAKE_PREFIX_PATH "~/.conan/data/catch2/2.13.3/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/Catch2" ${CMAKE_PREFIX_PATH} ${CMAKE_CURRENT_LIST_DIR})
```

Content of `CONAN_CATCH2_ROOT `:
```
├── conaninfo.txt
├── conanmanifest.txt
├── include
│   └── catch2
│       ├── catch.hpp
│       ├── catch_reporter_automake.hpp
│       ├── catch_reporter_sonarqube.hpp
│       ├── catch_reporter_tap.hpp
│       └── catch_reporter_teamcity.hpp
├── lib
│   └── cmake
│       └── Catch2
│           ├── Catch.cmake
│           ├── CatchAddTests.cmake
│           └── ParseAndAddCatchTests.cmake
└── licenses
    └── LICENSE.txt
```
No `Catch2Config.cmake` 😢 

As I am new to conan and do not know if its a problem of conan or Catch2, I also created an issue at the Catch2 repo:
https://github.com/catchorg/Catch2/issues/2100

**Comment by memsharded** [comment]
Hi @blackliner 

This is expected and by design in ConanCenter. 

The fact is that the generated FindXXX.cmake or xxxConfig.cmake files, generated at build time by CMake have a number of limitations, mainly they can be problematic with transitive dependencies, and might fail to depend on other transitive conan packages, depending on an outdated library version found at the system level, and also they are not multi-configuration, they cannot find multiple binaries located in different folders, and they assume that both Debug/Release/RelWithDebInfo, etc artifacts are in the same location, which is not true.
Not to say that packages that are not built with CMake will not have these scripts, and then the approach will completely fail, and there are a bunch of them in ConanCenter.

So ConanCenter avoids these issues by not packaging these potentially broken files. Instead, Conan can generate these scripts with the ``cmake_find_package_multi`` generator, for all packages, even those that are not built with CMake, on the fly. They will handle transitivity right and they can handle multi-configurations.

The ``cmake_paths`` generators might be useful for users that fully control the build with CMake, that is for your own internal packages (assuming that all use CMake, that you handle correctly transitive dependencies and you don't want multi-configuration build systems, like Visual studio), you might be able to make this approach work.

The ``cmake_find_package_multi`` will most likely become the main canonical integration with CMake in next Conan 2.0, I would recommend start using it now.

**Comment by blackliner** [comment]
That would mean that in addition to using Conan as a package manager, I would also have to introduce it into my build system. I wanted to avoid that, to be able to stay independent.

We are in a evaluation phase (conan vs vcpkg), do have private artifactory/Jfrog/whatnot, and are willing to provide handwritten packages, use toolchain files. Oh, and also use Visual Studio 🙈 After watching [Mathieu Ropert's](https://www.youtube.com/watch?v=k99_qbB2FvM&ab_channel=ACCUConference) talk, I was convinced that conan could deliver all what we need and that it would be the perfect candidate. But it seems that it sounded too good to be true.

**Comment by memsharded** [comment]
> That would mean that in addition to using Conan as a package manager, I would also have to introduce it into my build system. I wanted to avoid that, to be able to stay independent.

I don't understand why. You don't need to change your build system at all, your CMakeLists.txt will still use the normal ``find_package()`` calls. There is no difference between the ``cmake_paths`` and the ``cmake_find_package_multi`` generator from the consumer CMakeLists.txt point of view, just the later provide more consistent and less fragile behavior. Could you please clarify what you mean?

**Comment by blackliner** [comment]
Oh, I was under the impression that I need to use `cmake_find_package_multi(Catch2 REQUIRED)` instead of `find_package(Catch2 REQUIRED)` 🤦  I will try out the `cmake_find_package_multi` generator 👍

**Comment by memsharded** [comment]
Oh, no that is only the name of the generator! 😄 

It is for your conanfile:
```
[requires]
dep/version

[generators]
cmake_find_package_multi
```

That is to differentiate it from the basic ``cmake`` generator that generates only a ``conanbuildinfo.cmake`` file to be included. Using the ``cmake_find_package_multi`` will generate regular find/config.cmake scripts, that can be use as usual with ``find_package()``. You only need to define, but that is standard cmake, the CMAKE_PREFIX_PATH, CMAKE_MODULE_PATH to point to CMAKE_BINARY_DIR or the location in which Conan genreated those find/config.cmake scripts.

**Comment by blackliner** [comment]
Alright, the files are generated correctly, and I am passing the CMAKE_PREFIX_PATH, CMAKE_MODULE_PATH seems to work. At least to find the Catch2 package. But it seems to be missing any include directory 🤷 
```
../third_party/catch2/catch2_main.cpp:3:10: fatal error: catch2/catch.hpp: No such file or directory
 #include <catch2/catch.hpp>
          ^~~~~~~~~~~~~~~~~~
```
In `compile_commands.json` you see that even that my target links to `Catch2::Catch2`, no -I / -isystem is passed to the compiler.
```
"command": "/usr/lib/ccache/c++ -o CMakeFiles/Catch2_main.dir/third_party/catch2/catch2_main.cpp.o -c <path>/third_party/catch2/catch2_main.cpp",
```

`catch2.cmake`
```
find_package(Catch2 REQUIRED)

add_library (Catch2_main STATIC ${CMAKE_CURRENT_LIST_DIR}/catch2_main.cpp)
target_link_libraries (Catch2_main PUBLIC Catch2::Catch2)
```

new `conanfile.py`
```
from conans import ConanFile, CMake
class Deps(ConanFile):
   settings = "os", "compiler", "build_type", "arch"
   requires = "catch2/2.13.3"
   generators = "cmake_find_package_multi"
```

**Comment by memsharded** [comment]
Can you please post or link the whole output of the build command? There might be messages previous to the error, related to the usage of the generated find/config.cmake scripts

I just tried it (in Windows atm), and it seems to work.
My CMakeLists:
```cmake
set(CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR} ${CMAKE_PREFIX_PATH})
set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR} ${CMAKE_MODULE_PATH})

find_package(Catch2 REQUIRED)

add_library (main STATIC ${CMAKE_CURRENT_LIST_DIR}/main.cpp)
target_link_libraries (main PUBLIC Catch2::Catch2)
```

My main.cpp
```cpp
 #include <catch2/catch.hpp>

 int main(){
}
```
Your conanfile, as-is. Then
```bash
$ mkdir build && cd build
$ conan install ..
$ cmake ..
$ cmake --build . --config Release
```
And it works here. It might be something weird in system, or related to the usage of ``compile_commands.json``. Could you try directly with those steps above?

**Comment by blackliner** [comment]
First, thanks a lot for helping me out!

Found it, I did not use `--config Release` (to be honest, I am trying it out in Ubuntu18.04 with gcc, so no multi_cfg needed at this stage). It looks like Catch2 recipe only provides the include dirs for Release type builds, but not for Debug (default).

As you can see, `conan install ..` does only create a `Catch2Target-release.cmake`
```bash
fberchtold@W10-RIG:~/workspace/conan/build$ conan install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py: Installing package
Requirements
    catch2/2.13.3 from 'conan-center' - Cache
Packages
    catch2/2.13.3:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
catch2/2.13.3: Already installed!
conanfile.py: Generator cmake_find_package_multi created Catch2ConfigVersion.cmake
conanfile.py: Generator cmake_find_package_multi created Catch2Config.cmake
conanfile.py: Generator cmake_find_package_multi created Catch2Targets.cmake
conanfile.py: Generator cmake_find_package_multi created Catch2Target-release.cmake
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
```

`cmake ..` aka `cmake .. -DCMAKE_BUILD_TYPE=Debug`
```bash
/usr/lib/ccache/c++   -g -o CMakeFiles/main.dir/main.cpp.o -c /home/fberchtold/workspace/conan/main.cpp
```

`cmake .. -DCMAKE_BUILD_TYPE=Release`
```bash
/usr/lib/ccache/c++  -isystem /home/fberchtold/.conan/data/catch2/2.13.3/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -O3 -DNDEBUG -o CMakeFiles/main.dir/main.cpp.o -c /home/fberchtold/workspace/conan/main.cpp
```
FYI, `compile_commands.json`  is just the collection of compile commands used, and you can see the include paths provided to the compiler there. Awesome for debugging such things. To get that file created by CMake, just add `set(CMAKE_EXPORT_COMPILE_COMMANDS ON)` to your `CMakeLists.txt`

**Comment by blackliner** [comment]
According to Internet, I can call `conan install .. -s build_type=Debug` which will then create the required `Catch2Target-debug.cmake` (only that, no release). Then `cmake ..` is not enough, it needs to be `cmake .. -DCMAKE_BUILD_TYPE=Debug`. Maybe different story.

I thought the `cmake_find_package_multi` is capable of outputting all 4 build types simultaneously?

My goal is to do `conan install .. && cmake .. && cmake --build .` to just work as a first step. Maybe I need to add all build types to the `conanfile.py` ?

**Comment by memsharded** [comment]
> Found it, I did not use --config Release (to be honest, I am trying it out in Ubuntu18.04 with gcc, so no multi_cfg needed at this stage). It looks like Catch2 recipe only provides the include dirs for Release type builds, but not for Debug (default).

Yes, that is true. The ``cmake_find_package_multi`` generator is a multi-configuration generator. I use it because I am in Windows, and Visual Studio is multi-configuration, so it is necessary if you want to be able to use that feature in the IDE. The ``cmake_find_package`` generator is single-config one, will not care about release/debug configurations, and assume you only have 1 valid active configuration. 

In any case, I think this is a point of improvement of the ``cmake_find_package_multi``, I will check if it is possible to improve this for header-only packages that will only contain 1 configuration. Thanks for the feedback!

**Comment by blackliner** [comment]
I also read https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_multi_generator.html#usage, and here it is mentioned to run both installs next to each other. So if I do the following, all required files are here:
```
conan install .. -s build_type=Release
conan install .. -s build_type=Debug
```
Our project will have to support Win64, Linux (x86 and aarch64), QNX (aarch64), thats why I would like to stick to the swiss army knife `cmake_find_package_multi`

**Comment by memsharded** [comment]
Yes, yes, totally, the ``cmake_find_package_multi`` is good, this would be a small optimization for packages without build_type (like header only packages)

> According to Internet, I can call conan install .. -s build_type=Debug which will then create the required Catch2Target-debug.cmake (only that, no release). Then cmake .. is not enough, it needs to be cmake .. -DCMAKE_BUILD_TYPE=Debug. Maybe different story.

> I thought the cmake_find_package_multi is capable of outputting all 4 build types simultaneously?

Yes, it does.

> My goal is to do conan install .. && cmake .. && cmake --build .

Yes, that should work except the default. The default conan profile is release, so if the cmake default is debug, you would need (in single-config envs):

```bash
$ conan install .. -s build_type=Debug && cmake .. && cmake --build .
```
I always do it explicitly. In single-config envs:

```bash
$ conan install .. -s build_type=Debug && cmake .. -DCMAKE_BUILD_TYPE=Debug && cmake --build .
```
And in multi-config:
```bash
$ conan install .. -s build_type=Debug && cmake .. -G "Visual Studio...:" && cmake --build . --config Release
```

**Comment by blackliner** [comment]
Cool, unfortunately `cmake ..` is not Debug, its no build type at all. Like the 5th build type.

Thanks alot for your help, I still have to figure out a way to introduce it to the folks without any manual work on their side, and also minimal conan dependencies inside the root `CMakeLists.txt`, but you gave me an awesome headstart! One more commercial project that might use conan 👍

**Comment by memsharded** [comment]
> Thanks alot for your help, I still have to figure out a way to introduce it to the folks without any manual work on their side, and also minimal conan dependencies inside the root CMakeLists.txt, but you gave me an awesome headstart! One more commercial project that might use conan 👍

Excellent! Happy to hear that. For more resources to get started with Conan I would recommend the Academy (https://academy.jfrog.com/path/conan), and the community in the CppLang slack (#conan channel) is really friendly and helpful too. And you can always open new issues here for further questions.

I am going to leave this issue open at the moment, because I want to have a look to the possibility of optimizing the case of header-only libraries in the cmake multi generator. Thanks again for the feedback!

**Comment by ytimenkov** [comment]
> Cool, unfortunately `cmake ..` is not Debug, its no build type at all. Like the 5th build type.
> 
> Thanks alot for your help, I still have to figure out a way to introduce it to the folks without any manual work on their side, and also minimal conan dependencies inside the root `CMakeLists.txt`, but you gave me an awesome headstart! One more commercial project that might use conan 👍

I suggest to run `conan build --configure` instead of CMake to get a consistent configuration. Especially if you use CMake helper or toolchain works really well.
(wrote some docs here: https://github.com/gerbera/gerbera/blob/master/doc/conan.rst#building-gerbera)

**Comment by blackliner** [comment]
@ytimenkov What step would you replace with `conan build --configure ..` ? The goal is to have a stupid, agnostic root `CMakeLists.txt` that relies purely on `find_package(...)`, so one could install all dependencies as system dependencies and just run `cmake .. && cmake --build .`

**Comment by ytimenkov** [comment]
This replaces step `cmake ..`.

Because there is a number of parameters which need to be passed to CMake and be consistent with `conan install` command.
Besides `BUILD_TYPE` there are compiler (`CC`/`CXX` variables which may be set in a profile) which needs to be initialized *before* the call to `project()` (or `enable_language` which is nested), architecture or toolset (for MSVC).

`conan build --configure` handles this nicely for you and it's a simple command which can be universally applied to all projects / components.

There is also toolchains but still invocation is more verbose.

**Comment by blackliner** [comment]
Ok, this sounds like a job for toolchain_files. I did not look into how conan handles those, just heard that instead of providing cmake toolchains, I'd have to describe them in python and conan exports them for the cmake build?

I do not know if I want to describe my toolchains in conan, I would rather like to provide them as `linux_gcc_8_aarch64_debug.cmake` to conan, if that is possible at all. Reasons are, I want conan to be mainly the provider for third party dependencies, not take control over the whole build system.

**Comment by gabyx** [comment]
@memsharded 

I have somewhat the same problem:
I use
```python
  def build_requirements(self):
      if Version(self.version) >= "0.0.0":
        self.build_requires("catch2/2.13.7")
```

And cmake calls conan by `conan_cmake_install`:
 
```shell
conan install /cmake-general/tests/project --install-folder /cmake-general/tests/project/build/conan --build missing --profile:build default --settings build_type=Release --settings compiler=clang --settings compiler.version=12 --settings compiler.libcxx=libstdc++
```
which installs Catch2 as I see

but any `find_package(Catch2 CONFIG REQUIRED)` fails because non is generated?

Why is that when using build_requirements?

**Comment by memsharded** [comment]
Hi all,

This issue is now a bit outdated. Let me summarize current status:

- Future of CMake integration is CMakeDeps and CMakeToolchain, to achieve transparent integration
- CMakeToolchain can generate a ``conan_toolchain.cmake`` file to pass the necessary information to CMake
- The limitation would be the usage of ``cmake-conan``, because it is a chicken and egg problem. It is not possible to have both a transparent integration and calling Conan from cmake. Users using ``cmake-conan`` should provide the equivalent information contained in ``conan_toolchain.cmake``, mostly the CMAKE_MODULE_PATH, CMAKE_PREFIX_PATH to point to the folder where Conan is creating the ``xxx-config.cmake`` files with CMakeDeps. This approach will still not work to locate config.cmake files inside Conan packages, because of that chicken-and-egg problem nature. 

I think this question can be closed now as responded, if there are issues with ``cmake-conan``, better report them in its repo. Thanks!
