### ISSUE TITLE
[question] difference between "cpp_info.libs" and "cpp_info.system_libs"

### ISSUE THREAD

**Issue by tharilya** [conan-io/conan#8104]
Hi,

what is the difference for the customer of a package if you define a dependency due "cpp_info.libs" or "cpp_info.system_libs"?

example:
I am creating a static-library-package "LIB" and a executeable-package "EXE", with "EXE" has "LIB" as build-requirement.
LIB has a dependency to the library "pthread", which is required for usage of LIB.

in the "package_info" method of the conanfile.py of LIB I have 2 variants:
Variant A)
* "self.cpp_info.libs.extend(["pthread"])"

Variant B)
* "self.cpp_info.system_libs.extend(["pthread"])"

what is the difference from the "EXE" point of view? Is there any difference for handling / linking? 
* in both cmake-files (LIB and EXE) "conan_basic_setup(TARGETS) && conan_target_link_libraries(<target-name>)" is used.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @tharilya 

The ``system_libs`` are for libraries that do not belong to this package, and are installed in the system, like ``pthread``.
Any library that it is built as part of the package, should go to ``libs``.

The difference is that package ``libs`` should be located in the ``libdirs`` and will define absolute paths to it, to guarantee that it is using the package one. Otherwise, it will pick whatever is found in the system.

**Comment by tharilya** [comment]
Hi @memsharded 

to be honest ... that kinda confuses me. Because:
you first say that `pthread` is a system library (of course nothing new ...) so I guess that `pthread` should go into the "system_lib"-section.

And you additionally wrote:
> Any library that it is built as part of the package, should go to libs.

So in my exampe `LIB` uses `pthread` directly and it is a static library, so in linking-time the symbols are just referenced. So I guess that `pthread` should also be inside the "lib"-section?

If I get you the correct way, ... the technically difference is path of the refences to `pthread` inside the compiled library `LIB`?

But nevertheless ...
What would be the correct settings in my example? set both? ...

**Comment by memsharded** [comment]
Hi @tharilya 

> So in my exampe LIB uses pthread directly and it is a static library, so in linking-time the symbols are just referenced. So I guess that pthread should also be inside the "lib"-section?

No, in your package "mycoolpkg" you build "mycoollibrary". This **depends** on the ``pthread`` system library, but ``pthread`` is not built in this package. Then:

```python
def package_info(self):
     self.cpp_info.libs = ["mycoollibrary"]
     self.cpp_info.system_libs = ["pthread"]
```

Conan generators, like ``cmake`` one, will search for ``mycoollibrary`` inside the package folder, to get the full path and ensure that library is found in the package you are requiring, but it will not process ``pthread`` and just assume it is somewhere in the system.

**Comment by tharilya** [comment]
Hi @memsharded 

thank you very much for the explanation!

**Comment by JNURay** [comment]
Hi @memsharded , then where would the cmake search for the system libs?
in my case, cross compiling, the system_libs are inside another consumed conan package. I have required this package and using find_package, target_link_libraries in CMakelists

**Comment by jcar87** [comment]
When it comes to system libs, I tend to have a mental model of "system libs are provided by the the toolchain and located by the relevant tool in their default or fallback search paths" . So this covers things like:
- headers and libraries inside the macOS SDK (which are actually in a sysroot passed to the compiler)
- likewise for Windows SDK, android NDK, etc
- headers and libraries in "system" locations in `/usr/lib`, `/usr/include` etc - this is where the "system" name comes from
- when crossbuilding and using a sysroot - things that are inside the sysroot (since it falls under "default or fallback search path")

With the above description, it is still possible to be a "system library" and inside a Conan package, for example Android NDK, or a conan package that contains a Linux sysroot when crossbuilding, etc. The important thing about system libraries is that they are found in the "fallback search paths" - Conan and other tools _must not_ add a `-L /path/to/lib` or `-I /path/to/include` 

Perhaps a rule of thumb:
- a `cpp_info.libs` will cause `-L /path/to/conan/cache/p/abc12149/lib -lfoo` - the tool _must_ be told where to find this library (or equivalent)
- a `cpp_info.system_libs` should _only_ cause `-lfoo` - because it should be locatable in the default/fallback search paths. 
    - The only exception to this would be cross-building _and_ using a separate sysroot, where the sysroot may or may not be a Conan package, eg. `--sysroot /path/to/conancache/p/sysroota1233 -lfoo`. 

> Hi @memsharded , then where would the cmake search for the system libs?
> in my case, cross compiling, the system_libs are inside another consumed conan package. I have required this package and using find_package, target_link_libraries in CMakelists

if CMake is using `find_library`, cmake will look in the default search paths - `/usr/lib` etc - or re-rooted in a sysroot if CMAKE_SYSROOT is provided. CMake should know to *not* pass `-L /usr/lib` for a "system" lib.
