### ISSUE TITLE
conan returns package not found whithout anonymous usage enabled in artifactory from #4930

### ISSUE THREAD

**Issue by TamiKra** [conan-io/conan#8127]
In #4930 the reason for "package not found" was in the artifactory-return-code-404 (instead of 403).
That is an explanation **why** the behavior of conan is wrong, but it does not remedy the behavior. i.e. it's **still broken**.

expected behavior:
- When trying to find a package on an artifactory-repository, but the permissions are insufficient for that request, conan must always behave accordingly:
-- if the user has logged in but does not have permissions, show "insufficient permissions"
-- if the user has NOT logged in (anonymous), conan must ask for credentials.

How this is done between artifactory, it's return-code and conan does not matter. The user must be **informed correctly** what is going on.

**Comment by TamiKra** [comment]
Note: we spent 3 people for 2 days debugging this behavior. When I suspected a bug, I didn't find one at first because it was closed a long time ago without a solution.

**Comment by memsharded** [comment]
Hi @TamiKra 

I am not sure I understand what you mean. #4930 explains that Conan servers are reporting 403 according to the specification of the W3.org: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.4

> 403 Forbidden

> If the server does not wish to make this information available to the client, the status code 404 (Not Found) can be used instead.

The current Conan behavior is totally correct, and following standards, if a server doesn't want to disclose if a package exists or not exists to non-authenticated users, it can return a 404. Otherwise, anonymous users can extract information of what packages exists and what packages do not exists in a server they don't have credentials. This is not acceptable from a security point of view, and most of our users do not want that behavior.

**Comment by AbrilRBS** [comment]
Closing as won't-do. This is something that has come up a few times since then and our position still remains the same: Conan is behaving as expected, and should not try to be clever in situations like these
