### ISSUE TITLE
[question] library with the only .o file?

### ISSUE THREAD

**Issue by db4** [conan-io/conan#8133]
The library I'm trying to package creates a single .o file: 
```
lib/libbase64.o: $(OBJS)
	$(LD) -r -o $@ $^
	$(OBJCOPY) --keep-global-symbols=lib/exports.txt $@
```
Can it be used without modification in a conan recipe? Or some Makefile patching is required?

**Comment by memsharded** [comment]
Hi @db4 

I think it is fine, you can put whatever file you want in a package. So you can do the ``self.copy("*libbase64.o")`` and package that file. I guess in the consumer side you might need to take that into account to link correctly with it, but I guess it is possible.

Why not creating a regular static library from the .o file? Is there any special requirement to keep it as an object file instead of a static library?

**Comment by db4** [comment]
> I guess in the consumer side you might need to take that into account to link correctly with it, but I guess it is possible.

So it's not suitable for general purpose Conan package.

> Why not creating a regular static library from the .o file? Is there any special requirement to keep it as an object file instead of a static library?

Because the library I'm trying package https://github.com/conan-io/conan-center-index/pull/3746 does not build .a file.  I would like to avoid Makefile patching but it became necessary anyway for other reasons.
