### ISSUE TITLE
[feature] Specialized type for ANY option

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#8136]
Hi!

The generic [option](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#options) `ANY` works pretty well for most cases, but some cases requires an extra check based on variable type, for instance, I can receive the CPU number, which is an integer:

```python
options = {"cpus": "ANY"}
default_options = {"cpus": 1}
```

Obvious, I can't receive strings.

A real case: https://github.com/conan-io/conan-center-index/pull/3630/files#diff-1efc27567d8001330759d73288b06baffddd3fd5793ac05d783e323e71bd077dR26

My suggestion is adding a built-in validation according the specialized type:

```python
options = {"cpus": "INT"}
default_options = {"cpus": 1}
```

    conan create . -o foo:cpus=bar
    ERROR: The option 'foo:cpus' only accepts 'int' values.

Internally, we could validate according the type:

```
types = {"INT": int, "STR": str, "FLOAT": float}
if option_type in types:
	if not isinstance(value, types[option_type]):
        raise ConanException("The option '{}' only accepts '{}' values.".format(option_name, option_type))
```

- [ X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This seems a lot of effort to provide a slightly better UX, that is only there to provide some better error messages when the user input in profiles or command line is wrong.

Because internally, everything is a string, and the final conversion to int() or float() has to be done anyway by the users, if they need the integer value in the recipes. I am ok if that raises because the input is not convertible.

**Comment by uilianries** [comment]
> Because internally, everything is a string, and the final conversion to int() or float() has to be done anyway by the users,

Indeed, closing this issue.
