### ISSUE TITLE
[question] "requirement overridden" warning appears for valid version range

### ISSUE THREAD

**Issue by apyvovar** [conan-io/conan#8148]
Consider the following prerequisites:
Package_A/1.0.0@user/stable:
`requires = "Package_B/[>=1.0.0 <3.0.0]@user/stable"`

Project_A:
```
[requires]
Package_A/1.0.0@user/stable
Package_B/2.0.0@user/stable
```

Since Package_A should work with any Package_B in range [>=1.0.0 <3.0.0], I'd expect Conan to process `conan install` command for Project_A, requesting Package_B of fixed version within range (e.g.: 2.0.0) without any problems.

Instead, the following warning appears:
`Package_A/1.0.0@user/stable: requirement Package_B/[>=1.0.0 <3.0.0]@user/stable overridden by your conanfile to Package_B/2.0.0@user/stable`

Please, clarify why requesting package within some range is considered as 'overriding' those range. 
This is very inconvenient in case environment variable `CONAN_ERROR_ON_OVERRIDE` is set to `True`.

**Comment by jgsogo** [comment]
Hi, @apyvovar 

I understand your concern and it is very unfortunate if using `CONAN_ERROR_ON_OVERRIDE` equals True. This is due to the graph resolution algorithm that Conan is using right now. We are already planning Conan v2.0 which will implement a different graph resolution algorithm with several improvements. Overrides and version-range should be something to take into account (I will label this issue for Conan 2.0 to not forget about it).

I'm not sure if we can fix it with the current graph algorithm implementation in an easy way, maybe it requires too much work for the value... and there are many things ongoing right now that we should focus on.

So far, no one has reported it as a bug, it looks like it is something people are suffering in silence or they are not using those two features together. If you think this is important we can try to allocate some time and have a closer look at the changes needed.

**Comment by crowe-imetrum** [comment]
Hi, I just wanted to add that my team is hit by this as well, we are using the form [0.X.X] for our use of semver but I imagine it comes down to the same issue. We were suffering in silence as this was raising the warning mentioned but not getting in the way of being able to build our solutions. I am considering that in the future we will need to make use of CONAN_ERROR_ON_OVERRIDE=True though so we would benefit from this fix in a future version of conan.

**Comment by memsharded** [comment]
Conan 2.0:

- Mades error on override the default
- Reduces or remove unnecessary warnings with valid version ranges.

2.0-beta.1 is already out, feedback welcome!
