### ISSUE TITLE
Is it possible to export a recipe from local cache and import it on another computer?

### ISSUE THREAD

**Issue by ngugcx** [conan-io/conan#8158]
I have to share recipes which are in my local cache with my team members.
But I don't have a running conan server which can be reached by others.
Is there a way to export recipes from my local cache, and send them to other people, then they can import on their computers?
Thanks!

**Comment by memsharded** [comment]
Hi @ngugcx 

I guess you figured out. Just in case, or for other readers, you can have the recipes in a git repo, and do ``conan export`` or ``conan create`` on them. If you have many, you can do a small script in the root of the repo that iterates all the recipes and do the operation. Typically it is better to do ``conan export``, because that doesn't require any order, then ``conan install --build=missing`` to build the binaries that you need as you go.
