### ISSUE TITLE
[bug] When using conan toolchains, cmake.verbose and cmake.parallel don't work anymore

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#8165]
For debugging purposes, it it useful to quickly set `cmake.parallel = False` and/or `cmake.verbose = True` in `build()`.
It seems that this does not do anything when using conan toolchains (=adding a `def toolchain(self)` method).

Also, `cmake.configure` does also not support adding extra arguments (`args` argument).
This is also useful to add extra debug arguments such as `--trace`, `--debug-trycompile`, ...

### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora Linux 31
  * Compiler+version: gcc 9
  * Conan version: 1.31.1
  * Python version: 3.7.7

**Comment by memsharded** [comment]
Hi @madebr 

This is on purpose. We are trying to minimize the scope and interface of the new toolchains. First, because they are quite experimental (just renamed ``toolchain()`` method to ``generate()``, for example). But also, because those things totally read like configuration, and then they should have a better way to define them, without needing to modify the recipe. We are studying how the configuration UX could be improved.

Regarding the ``cmake.configure()``, recall that the purpose of toolchains is basically that the user does not need to run ``conan build`` locally, but they can run ``cmake`` natively instead. Whatever argument that needs to be passed to ``configure`` should be done in the command line, and the recipe ``build()`` method should probably not contain things like ``--debug-trycompile``. We will certainly start adding back the UI when the core functionality is stabilized, but just in case, to explain how we are thinking.

**Comment by madebr** [comment]
Thanks for the reply.
I'm hoping that these convenience things for quickly getting extra debug information or building thinks in parallel/serial get added in the end.

**Comment by memsharded** [comment]
Hi @madebr 

Yes, they will be added, we are already working in a proof of concept for config here: https://github.com/conan-io/conan/compare/develop...memsharded:poc/config

A relevant question is what should always be configuration (sounds like verbose and parallel are) and what should be defined in recipes. I am starting trying with the config part, without definitions in recipes, and I think that things that really need to have a hardcoded value in the recipes will be identified.
