### ISSUE TITLE
Add option to export command to build the package

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#817]
Would be useful for package development. i.e. instead of:

```
conan export me/channel
conan install mypkg/version@me/channel --build
```

You do:

`conan export me/channel --build`

**Comment by memsharded** [comment]
Actually, the really useful for package development is ``conan test_package``, I really recommend it instead of your approach. ``conan test_package`` does:

```bash
$ conan export me/channel
$ conan install test_package --build=mypkg # does conan install mypkg/version@me/channel --build
$ conan build test_package # builds the consumer project
$ ./bin/test_app #run the consuming apps inside test_package
```

Besides ``test_package`` accepts all command line arguments (like settings, profiles), that ``install`` does. ``conan export`` do not accept those arguments, and allowing to pass those arguments would be inconsistent if not adding the ``--build``.

```bash
$ conan new mypkg/version@me/channel -t
```
writes a basic working example of a package with test_package. I strongly recommend to use it.

**Comment by rconde01** [comment]
Thanks I'll give that a try.

**Comment by memsharded** [comment]
I think that ``test_package`` is definitely the way to go, so it seems that there is no further action from our side here, closing issue. Thanks!
