### ISSUE TITLE
[bug] MSBuildDeps generator: build_requires not added to conan_deps.props

### ISSUE THREAD

**Issue by lieser** [conan-io/conan#8170]
Build requirements are not added to the generated `conan_foo.props` file.

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version: 1.32.0
  * Python version:

### Steps to reproduce (Include if Applicable)

1. add a library package (e.g. `foo`) to `build_requires`
2. execute `conan install` using the `MSBuildDeps`/`msbuild` generator

- `conan_foo.props` is generated
- generated `conan_deps.props` does not contain an import of `conan_foo.props`

Background:
We have a test helper library as a dependency that is only used in the test. Previously we added it as a private requirement, which showed up in the `conan_foo.props`. From our current understanding of Conan, it however is better written as a build requirements.

**Comment by memsharded** [comment]
Hi @lieser 

This could be a bug, but please take into account that the new ``MSBuildDeps`` generator is an experimental one and might change its behavior, and one of the things that might change is the management of ``build_requires``. As documented, explained in the trainings, etc: 

> build_requires are designed for packaging tools, utilities that only run at build-time, but are not part of the final binary code. Anything that is linked into consumer packages like all type of libraries (header only, static, shared) most likely are not build_requires but regular requires. The only exception would be testing libraries and frameworks, as long as the tests are not included in the final package.

So unless you are using it for things like ``cmake`` tool or the ``gtest`` testing library, I would suggest reconsidering your approach. The way that you can see how this could change is using the new ``profile:build`` and the build-context. When using it, the build-requires do NOT longer propagate things like ``includedirs``, ``libdirs``, ``libs``, etc. because those should be regular ``requires`` instead.

We will try to have a look and maybe fix it for next 1.33, but please keep an eye how it evolves regarding ``build_requires``. Thanks!

**Comment by lieser** [comment]
We are aware that `MSBuildDeps` is experimental, but thanks for reminding us.
Note that this is not an urgent/important bugfix for us (easy workaround available by simply adding another import).

I described our usage of `build_requires` more closely in #8176. Would be nice if you could take a look at it, as it currently still causes problems, and would be nice to know if we are maybe just misusing it.

**Comment by memsharded** [comment]
Hi @lieser I am proposing to add it in #8186
