### ISSUE TITLE
[question] Why is "fPIC" always set in conan if "shared" is activated?

### ISSUE THREAD

**Issue by tharilya** [conan-io/conan#8185]
Hi there,

I ran into some linker-issues with `fPIC` and have a question about a behavior which I didnt expected.

My situation:
I am building a library lets call it `my_libA`.
And I am building a library lets call it `my_libB` which link against `my_libA`.
(when builing, I mean the gcc54 compiler on a ubuntu 64-bit Plattform, I am not cross-compiling or something like that).
Both libraries have the `fPIC` and the `shared` option, because I want to provide the variants.

So when I am building the variant: 
`my_libA` (with options: `shared=False` && `fPIC=False`) and `my_libB` (with options: `shared=True` && `fPIC=False`)  
Which should be technically be possible linking a static lib into a shared one ...
-> I am getting a linker error which tells me, something like that:
```
<my_libA>: relocation R_X86_64_PC32 against symbol `<symbol-name>' can not be used when making a shared object; recompile with -fPIC
```

I assume, that it want's to tell me that I want to link one library without `fPIC` against one with `fPIC`.

I was looking into the log and was able to reproduce the behavior with a clean package. And now I come to my question:

Why is conan ignoring the option `fPIC` when the option shared is true, and `fPIC` is false?
* If both options `fPIC` && `shared` exists AND the `shared` option is on `true`, then `fPIC`-adjust log-msg always appears, even if fPIC is set to false!
* log message appears `-- Conan: Adjusting fPIC flag (ON)`

-> I assmune that results in fPIC is always set even if the option is set to false ...

Steps to reproduce:
1. create a clean package e.g. `conan new cool_name`
2. go into the recipy and add the fPIC option so the options should look something like that:
```
options = {"shared": [True, False], "fPIC": [True, False]}
default_options = {"shared": False, "fPIC": False}
```
3. build the package with the following options `conan create . user/channel -o cool_name:shared=True -o cool_name:fPIC=False`
4. terminal message appears. `-- Conan: Adjusting fPIC flag (ON)`

Is this behavior intended? how can I build a shared library in two variants? with & without fPIC?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

edit:
I found It is the code, but I still dont understand why this is done.
https://github.com/conan-io/conan/blob/edb3a4a1f7739027c0665749b82b1cc473453ab6/conans/client/build/cmake_flags.py#L367-L373

**Comment by jgsogo** [comment]
Hi, I've traced the implementation and it is there for more than two years now (https://github.com/conan-io/conan/pull/2818). You can avoid Conan setting this value using `SKIP_FPIC` if you are using the `conan_basic_setup()` macro in your CMake files. However, then you would need to handle this value yourself. This is something that we cannot change now because we will break some build out there of someone that relies on this behavior.

But, we are moving to a new paradigm to trigger the builds, using toolchain files, we are putting lots of effort on them now and they will likely be the default (and maybe only) way to pass information to the build_system about the compiler, flags and so (dependencies will have their own files as they have now, of course). Using these new _toolchain_ files we are managing `fPIC` in a different way, this is the [implementation right now](https://github.com/conan-io/conan/blob/489266ccdf2cbec69930e30557536718019031da/conan/tools/cmake/generic.py#L179):

```python
    def _deduce_fpic(self):
        fpic = self._conanfile.options.get_safe("fPIC")
        if fpic is None:
            return None
        os_ = self._conanfile.settings.get_safe("os")
        if os_ and "Windows" in os_:
            self._conanfile.output.warn("Toolchain: Ignoring fPIC option defined for Windows")
            return None
        shared = self._conanfile.options.get_safe("shared")
        if shared:
            self._conanfile.output.warn("Toolchain: Ignoring fPIC option defined "
                                        "for a shared library")
            return None
        return fpic
```

```cmake
            {% if fpic -%}
                message(STATUS "Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)")
                set(CMAKE_POSITION_INDEPENDENT_CODE ON)
            {%- endif %}
```

With this implementation, !Windows+shared won't set any value for `fPIC`.... so CMake will use whatever value is the default or the value if something is written in `CMakeLists.txt`.

The behavior with these new toolchains is intended, but **now it is the perfect time to discuss it and modify that behavior so we have something that satisfies all the use cases**.

**Comment by tharilya** [comment]
Hi @jgsogo,

thank you for the explanations. To be honest I am new to this topic with fPIC. I was just confused why it's set even if the option is false.

The reason of the implementation inside conan is that it's the technical behavior of the gcc.

I did some research and it seems like there is a `reason` that it makes technically no sense to build a "shared library" with the gcc without the `fPIC`-Option.  I assume that is the `reason` why you implemented it like that.

But I still do not understand the `reason`. It's like something of the `memory_managing_unit` or so....

nethertheless ... 

it seems to be an user-error of me, because building a shared library without fPIC is not intended by the compiler, so its not "conan-issue" ...

kind regards

**Comment by jgsogo** [comment]
Let's invoke @SSE4 , he knows much more about these issues, and I'm sure he can say something about `shared` and `fPIC` flag.

**Comment by memsharded** [comment]
Closing this ticket as outdated.

ConanCenter recipes now remove the ``fPIC`` when not relevant. 
Conan 2 also implemented an ``auto_fpic`` behavior to further automate this.
Build system integrations will avoid setting it if not necessary.

Please create new tickets if necessary, thanks for your feedback.
