### ISSUE TITLE
[feature] `conan lock update` should update package-ids of consumers when possible

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8199]
package-id mode: `package_revision_mode` 

When deriving new lockfiles for each configuration/profile of a change, the `package-id`s of the consumers are unknown.  If my understanding is correct this is because it is impossible to know the package revision `prev` of the changed package before it is built.

```
conan lock create ../conanfile.py --user=user --channel=channel --lockfile-out=locks/libb_deps_base.lock  --build --base
conan export .. libb/0.2@user/channel --lockfile=locks/libb_deps_base.lock --lockfile-out=locks/libb_base.lock
conan lock create --reference=libb/0.2@user/channel --lockfile=locks/libb_base.lock --lockfile-out=locks/release.lock -s build_type=Release --build=missing
conan lock build-order locks/release.lock --json=build_order/build_order.json

[[('libc/0.1@user/channel#0c089e63b9257da0f5c0e54b7ab7497c49be8943', 'b3fb0c7cc19cd0b04b840bafdf9e18adc3ca1246', 'host', '5')], [('libd/0.1@user/channel#dea4d51a7d43deadb40c226510cc2bedd6c22b77', 'Package_ID_unknown', 'host', '4')], [('app1/0.1@user/channel#7929e9808ff776b6afc5135394bf00b210a64c3b', 'Package_ID_unknown', 'host', '3')]]
```

Once I build the package and update the lockfile it should now be possible to determine the `package-id`:
```
conan install libc/0.1@user/channel#0c089e63b9257da0f5c0e54b7ab7497c49be8943 --build=libc/0.1@user/channel#0c089e63b9257da0f5c0e54b7ab7497c49be8943 --build=missing --lockfile=locks/release.lock --lockfile-out=locks/updated_release.lock
conan lock update locks/release.lock locks/updated_release.lock
```

I would like for the `Package_ID_unknown` entries to be updated accordingly when possible.

My main goal here is to ensure each entry in the top level of build-order has a known `package-id`.  Currently after building the first level, updating the main config lockfile, and recomputing the build-order, this is not the case. 

```
conan lock build-order locks/release.lock --json=build_order/build_order.json

[[('libd/0.1@user/channel#dea4d51a7d43deadb40c226510cc2bedd6c22b77', 'Package_ID_unknown', 'host', '4')]]
```

**Comment by memsharded** [comment]
Hi @GordonJess 

The commands ``conan lock build-order`` and ``conan lock update`` are actually very simple, they do pure operations on the lockfile itself, without requiring to compute the graph at all. I think this is nice, probably we want to keep it that way.

To re-compute a whole lockfile so it could update the ``Package_ID_unknown`` to the new package_ids, the ``conan lock create`` can be used, something like:

```bash
$ conan lock update conan.lock conan_new.lock
$ conan lock create --reference=app/version@user/channel --lockfile=conan.lock --lockfile-out=conan.lock
$ conan build-order conan.lock
```

That will give you the updated build-order. So the functionality is there, and I think that we just might want to simplify the UX, by having some way to specify the "root" reference (in the above example the consumer application ``app/version@user/channel`` which was the one used to capture the lockfile in the first place) only the first time, but then allowing the commands to deduce it from the lockfile itself. Maybe a ``conan lock recompute`` new subcommand? But seems having the functionality as a separate command is nice, because users can have fine control of what is happening, and it is a bit more explicit. I am open to suggestions.

**Comment by memsharded** [comment]
``conan lock update`` has disappeared in Conan 2, closing ticket as outdated, thanks!
