### ISSUE TITLE
[bug] conan package when consumed doesnt extract hidden files

### ISSUE THREAD

**Issue by sandeshhardikar** [conan-io/conan#8210]
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version:NA
  * Conan version: 1.30.1
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)
1. Upload a conan package with atleast one hidden file .
2. consume the package in conan recipe with 
build_requires = \
        "package1/0.0.1@author1/stable"
3. Look into the conan cache after running conan install . Ex : ls -al .conan/data/package1/0.0.1/author1/stable/package/commit_hash/ you will see all the files except the hidden one .

### Logs (Executed commands with output) (Include/Attach if Applicable)
NA

**Comment by memsharded** [comment]
Hi @sandeshhardikar 

We would need more information in order to classify this:
- How is the hidden file being created? Is it exported in the recipe? Is it retrieved/cloned in the source() method?
- Are you sure it is being packaged correctly? Do the ``ls -al`` before uploading the Conan package
- Is the file present in the ``conan_package.tgz``? Check it (Artifactory UI allows to navigate tgz files)

If you can provide a simple recipe that implements a reproducible case, that would really help. I don't think the fact that it is a ``build_require`` affects at all, I think a create + upload + install should be enough to reproduce.

**Comment by sandeshhardikar** [comment]
Hi @memsharded ,

First of all Apologies from my side . The issue was from my side when creating a package . 
I was using glob to copy the files and it resulted in ommiting the hidden file . https://stackoverflow.com/questions/49047402/python-3-6-glob-include-hidden-files-and-folders . Thanks for your time in investigating the issue and quick response .

**Comment by memsharded** [comment]
Hi @sandeshhardikar 

No problem! Do not hesitate to open new issues for further questions or problems, always glad to help if possible.
