### ISSUE TITLE
[question] Generators are not called for recipe defining custom build_id

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#8212]
Conan 1.31.1.

I'm trying to create a workflow which creates 2 binary packages in one go: one with tests and one without (pretty much one described in the https://docs.conan.io/en/latest/reference/conanfile/methods.html#build-id).

However I noticed that custom generators are not called when build directory already exists (only the built-in ones like `TXTGenerator`).

Somewhere in `installer.py` / `build_package`: generators are written in the `self._build(...)` which is not invoked if `skip_build`, however `TXTGenerator` is invoked in `_package()` right before calling recipe's `package()`.

This leads to inconsistent results.

My custom generator tries to capture all options / settings to minimize the number of command-line parameters which need to be passed. Even CMake generator exports `CONAN_SETTINGS_*` variables). Not to mention that requirements can be different.

However those differences are fine for the build because package will do incremental build anyways (most build systems do build missing stuff in `install` step). Or on contrary will skip building the "main" code if test package was built first.

Also I really don't want to build packages twice because the second build will be a wasted work in most cases and it will double the work needed to build already big number of configurations.

Since this is the question: what are the reasons for not calling generators when skipping the build?

**Comment by memsharded** [comment]
Hi @ytimenkov 

I am not sure I fully understand the issue. If the build is skipped, because the ``build_id`` computes just one ID, it doesn't matter if the generators would run again, because those files will not be used at all in the build. It is not an incremental build, the build is left intact, it assumes that whatever binaries are needed for every package_id already exist in the build_id. The "generators" step is executed after the dependency graph has been computed, and just before calling ``build()`` method, because they are consumed in the build, but die there, they are not further used in the ``package()`` step.

It is true that the TXTGenerator is called anyway, because that one is called outside of the "generators" logic, because that file is used in the local flow and other cases for other (legacy) purposes. It was not removed because it could be breaking for some users, but it will be removed in Conan 2.0.

Does the above clarifies a bit the question?

**Comment by ytimenkov** [comment]
> It was not removed because it could be breaking for some users, but it will be removed in Conan 2.0.

This does answer my question. At least the behavior will be consistent and it's good to know the direction.

Just few thoughts...

Unfortunately there is  very thin line between `build()` and `package()` and there were examples where build is performed in the `package()` (maybe still are).

Besides most of times it's out of control because for better encapsulation `<your build tool> install` command is used and most of build tools' `install` target depends on `all`. I.e. a build will be silently performed for missing targets.

Probably the most reliable way would be to avoid calling build tool at all in the `package()` method but instead install into some staging directory during the build and then use only `self.copy()` to package.

Will try further 🙂. Please close this issue unless you want to keep it as a reminder for 2.0.

**Comment by memsharded** [comment]
Closing this ticket as solved time ago, the TXT generator was fully removed in Conan 2.
