### ISSUE TITLE
[bug] Cant enter passwords in Mingw

### ISSUE THREAD

**Issue by chris-stones** [conan-io/conan#8219]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: i686-w64-mingw32 10.2.0
  * Conan version: 1.32.1
  * Python version: 3.8.6

### Steps to reproduce (Include if Applicable)
```bash
$ conan search "MyLib"  --remote=MyRemote
Please log in to "MyRemote" to perform this action. Execute "conan user" command.
Please enter a password for "MyToken" account:
```

Enter your credentials - hit return.
Wait for a very long time... nothing happens...
kill with ctrl+c
```bash
$ MySuperSecretCredentials
-bash: MySuperSecretCredentials: command not found
```

Looks like console input was not received by the program prompting for the password, and was instead received by bash, which then tried to execute it sa a command.

Work-wround is to re run `conan user <MyUser> -r MyRemote -p MyCredential` before each command.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```bash
export  CONAN_LOGGING_LEVEL=10
$ conan search "ConanTest"  --remote=conantest
DEBUG :conan_api.py   [177]: INIT: Using config 'C:/Users/Me/.conan/conan.conf' [2020-12-17 10:12:14,680]
DEBUG :tracer.py      [156]: CONAN_API: search_recipes(remote_name=conantest,case_sensitive=False) [2020-12-17 10:12:14,680]
DEBUG :rest_client_common.py[160]: REST: ping: https://MyServer.com/gitlab/api/v4/projects/489/packages/conan/v1/ping [2020-12-17 10:12:14,690]
DEBUG :rest_client_common.py[30]: REST ERROR: <class 'conans.errors.AuthenticationException'> [2020-12-17 10:12:14,908]
Please log in to "conantest" to perform this action. Execute "conan user" command.
Please enter a password for "conantest-token" account: 12312313
$ 12312313
-bash: 12312313: command not found
```

**Comment by memsharded** [comment]
Hi @chris-stones 

A couple of quick questions, to clarify:

- You mean that you are running under MSYS2 terminal in Windows? Because I usually refer to MinGW as the compiler suite (mingw32-make, gcc, etc), but in this case, it seems this is not related to the compiler at all, just to the fact that you are running Conan inside some terminal
- How did you install Conan inside that system? with ``pip``? The Windows installer?
- Does it work correctly in the same computer, but under a different system, like the "cmd" prompt?
- Does it communicate correctly with remotes? Can you do for example ``conan install zlib/1.2.11@ -r=conan-center``?

**Comment by sourcedelica** [comment]
Try installing `winpty` in msys2 and then run the Conan command like
```
winpty conan search "ConanTest"  --remote=conantest`
```
You can install `winpty` by running
```
pacboy sync msys/winpty
```

**Comment by chris-stones** [comment]
Thanks for the response.

@memsharded 
* Yes - MSYS2 In Windows 10. I installed the mingw compiler suite via msys2, and launched terminal i use conan with using the mingw32.exe that is installed by msys2.  
Default path c:\msys64\mingw32.exe.  
From what I gather, this is just a shortcut to launch the msys2 terminal with /mingw32 in the PATH.  
The naming IS a little confusing, but, this is NOT the very old mingw32 port... this is the latest msys2 (mingw64), but with the compiler that builds 32bit windows binaries (I am on 64bit windows, but i have dependency on a 3rd party legacy 32bit dll).  
* I installed conan using pip from inside the mingw32.exe shell.  
I used the python / pip that was installed from within msys2 using `pacman -S mingw-w64-i686-python-pip`  
I deliberatly kept the entire software suite inside msys2. I find mixing msys2 tools with native windows tools sometimes causes me problems.  
* conan works fine for me when used under the cmd prompt - using the windows python interpreter.  
* Yes, from within msys2 (mingw32.exe shell) everything works perfectly, UNTILL my credentials expire, and i am prompted to re-enter them.  

@sourcedelica 
I used the winpty from `pacman -S pwinpty`.  
when conan is launched from winty, credential input works perfectly!  

Perhaps this is a bug in msys2? or, perhaps my setup?

**Comment by memsharded** [comment]
Hi @chris-stones 

Yes, it seems that it could be a msys2 issue, because Conan there is doing "nothing", besides calling the python ``getpass`` functionality. I guess it is easily reproducible in msys2 by running inside python a ``import getpass`` and ``getpass.getpass("")``. Maybe @sourcedelica can confirm.

A couple of workarounds that you might use are:
- Define an env-var CONAN_PASSWORD instead (prompt will not ask for it anymore)
- Explicitly call ``conan user ... -p=password`` before those commands.

**Comment by chris-stones** [comment]
@memsharded - You are correct!

`getpass.getpass('')` halts - echoing typed characters to the terminal.  
ctrl-c kills the interpreter, then the shell tries to execute the password as a command.  

Thanks for all the help!  
Im not 100% where the bug lies, but it is certainly not in conan!  

```bash
ChrisStones@W1029078 MINGW32 ~
$ python
Python 3.8.6 (default, Nov  3 2020, 22:19:54)  [GCC 10.2.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import getpass
>>> getpass.getpass("")
HELLO



ChrisStones@W1029078 MINGW32 ~
$ HELLO
-bash: HELLO: command not found
```

**Comment by memsharded** [comment]
Thanks to you for the feedback and following up!
