### ISSUE TITLE
[question] how to store package lockfiles in Artifactory?

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8259]
I am interested in creating a lockfile for each package that is built in CI and storing it on Artifactory so that it can be used to exactly reproduce the package again in the future.

`conan lock create --reference=${ref} --lockfile=${product_lockfile} --lockfile-out=${package_lockfile}`

So far I have been storing these lockfiles in a generic repo under `name/version/user/channel/rrev/package_id/prev` thinking that this would be unique for each package but I'm now running into problems when building multiple configurations...

I have found that in some cases it is possible to have different lockfiles for the same full package reference.  For example, in the [ci example](https://github.com/conan-io/examples/tree/master/features/lockfiles/ci), if `libd` doesn't use the `build_type` setting I get this lockfile when integrating into a debug `app1`:

```
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "libb/0.2@user/testing",
    "options": "",
    "package_id": "281a7e3eaa861ca65ad8f566ded8fc8b48206913",
    "prev": "0",
    "requires": [
     "1"
    ],
    "context": "host"
   },
   "1": {
    "ref": "liba/0.1@user/testing",
    "options": "",
    "package_id": "5a67a79dbc25fd0fa149a0eb7a20715189a0d988",
    "prev": "0",
    "context": "host"
   },
   "4": {
    "ref": "libd/0.1@user/testing",
    "options": "",
    "package_id": "3dbaa18e9c58ee1730a3c70ec88b190afd7354f4",
    "prev": "0",
    "modified": true,
    "requires": [
     "0",
     "5"
    ],
    "context": "host"
   },
   "5": {
    "ref": "libc/0.1@user/testing",
    "options": "",
    "package_id": "281a7e3eaa861ca65ad8f566ded8fc8b48206913",
    "prev": "0",
    "requires": [
     "1"
    ],
    "context": "host"
   }
  },
  "revisions_enabled": false
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\narch_build=x86_64\nbuild_type=Debug\nos=Windows\nos_build=Windows\n[options]\n[build_requires]\n[env]\n"
}
```

and this lockfile when integrating into a release `app1`:

```
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "libb/0.2@user/testing",
    "options": "",
    "package_id": "39b0b5fad32aaf2a462d27d4282d12c08bd6c818",
    "prev": "0",
    "requires": [
     "1"
    ],
    "context": "host"
   },
   "1": {
    "ref": "liba/0.1@user/testing",
    "options": "",
    "package_id": "4024617540c4f240a6a5e8911b0de9ef38a11a72",
    "prev": "0",
    "context": "host"
   },
   "4": {
    "ref": "libd/0.1@user/testing",
    "options": "",
    "package_id": "3dbaa18e9c58ee1730a3c70ec88b190afd7354f4",
    "prev": "0",
    "modified": true,
    "requires": [
     "0",
     "5"
    ],
    "context": "host"
   },
   "5": {
    "ref": "libc/0.1@user/testing",
    "options": "",
    "package_id": "39b0b5fad32aaf2a462d27d4282d12c08bd6c818",
    "prev": "0",
    "requires": [
     "1"
    ],
    "context": "host"
   }
  },
  "revisions_enabled": false
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\narch_build=x86_64\nbuild_type=Release\nos=Windows\nos_build=Windows\n[options]\n[build_requires]\n[env]\n"
}
```

Following my repo structure, both are stored under the same path in the lockfile repo, and one of them overwrites the other.  

I understand that either file should create the same binary package based on the 'package ID mode' and that this shouldn't  prevent me from recreating the package at all.  But the two lockfiles still do resolve different packages so in one of the cases I'm still losing my exact lock.

I also lose buildinfo tracability due to the checksums of the lockfile changing.  The lockfile artifacts (which I add to the buildinfo) cannot be resolved properly in Artifactory once they are overwritten - and this becomes an even bigger issue for me because I collect the lockfile artifacts from a buildinfo to use in the promotion.

So I'd just like to check if you had any other ideas for storing these lockfiles?

**Comment by jgsogo** [comment]
Hi, @GordonJess 

I will pass this question to @solvingj . He is working on a new course/workshop about how to integrate Conan into a successful CI. He's been doing a lot of work around it, so I'm sure he will be able to point you in the right direction. 

---

(Probably he won't be able to answer before next week, I hope all of us will enjoy these Christmas days)

**Comment by solvingj** [comment]
@GordonJess I'm glad you're reaching out to ask for guidance here.  When we first started training with lockfiles, we started by leveraging Artifactory Generic repos for lockfile storage.  In the past 6 months, we've found several major difficulties with this approach. As a result, we've begun storing lockfiles in a GIT repository for our internal development, testing, and training.  We've found this to offer a variety of advantages over any other storage strategy we've seen, so we will begin promoting this strategy in the near future. We're planning to release an additional Conan course in the JFrog Academy focused on CI/CD, and there we will use and demonstrate this strategy in action. 

Hopefully this is helpful enough advice to get you moving forward for now.  However, if you can keep an eye on the Conan blog for the CI/CD course release announcement, there will be a much more extensive discussion about the strategy there.

**Comment by DukeOfKirkcaldy** [comment]
Hello @solvingj,

Many thanks for the info!   Looking forward to hearing more about it and what your recommendations are for structuring git repositories for lockfiles, as I think the issue still exists no matter what the repo type (artifactory, git, etc.).

In the meantime as a quick workaround to avoid any of the overwriting mentioned above, I have added the checksum to the artifactory storage path.

```<artifactory url>/<lockfile repo>/<name>/<version>/<user>/<channel>/<rrev>/<package_id>/<prev>/<lockfile_sha1>/conan.lock```

**Comment by domfellner** [comment]
Hi @solvingj,

Is there any more material on this topic yet? We are about to implement this in our company and are keen to do it the proper way.

**Comment by solvingj** [comment]
Hi @domfellner . Sorry but there is currently no new clear and general guidance on the details of how to manage lockfiles for CI and developer workflows.  The creation of an actual strategy for a dev team has to start with an analysis of several factors, including how source control is laid out and managed, and how components in the dependency tree will be versioned, and how the CI jobs will be structured and navigated in the CI system. Then, several choices must be made about the tradeoffs between complexity and convenience.  How much automation the team wants to support, and how complex it can be are important questions, because troubleshooting and maintaining automation code is a major factor.  There are many other related choices to make as well, and each of them implies significant tradeoffs and has implications upon the other choices.  

What I can tell you is that the lockfiles-in-GIT strategy we experimented delivered some noteworthy features, but involved substantial complexity (a really detailed and complicated folder structure, and a very complicated copy/update/promote strategy), and it was super delicate.  It also made a ton of assumptions, and we never tested it in a real production system.

 Nonetheless, in summary, what we tried was this:
- Make a dedicated lockfile repo for all applications/projects managed by the team
- Manually create and add a lockfile for each configuration of each "final application" (not intermediate libraries/packages)
- Put them in a simple folder structure that users and CI can easily navigate

The complexity came from updating the lockfiles:
* For our common CI Job workflow, we started with the case of a PR to change one random component
* We also started with the scenario where each component/application/package had a separate GIT repo and CI job 
* The general idea was to rebuild that component, and all downstream consumers automatically
* We started the job by making a temporary copy of the lockfile to work with
* During the rebuild of the changed component, the revisions in the lockfile were updated 
* Then, the rebuilds of the consumers would occur in order, and each would update the lockfile with their new binary revisions
* At the end of the pipeline, we would end up with a fully updated lockfile
* When the PR was merged, the updated lockfile should then be copied and overwrite the original it was started from

Again, this process makes SO many assumptions, it's hardly generally usable.  It imposes significant complexity based on the assumption that each component had a separate GIT repo and separate CI job.  It also supported diamond dependencies with full parallelism, and building multiple lockfiles/configurations for each component within a each "job/run".  It also imposes significant complexity to dynamically create branches on the lockfile repository for each PR , to hold the updated lockfiles as the job progressed.  If you change any one of these assumptions, the workflow for the CI could change significantly. 

The good news is that we were in communication with several real development teams using Conan, with lockfiles, in non-trivial CI scenarios.  They were actively communicating with the Conan developers and the Lockfiles were evolving rapidly based on that feedback.  We were also trying to give guidance for specific lockfile use-case questions on a case-by-case basis in slack.  

I'm sorry I don't have simpler guidance.  I do recommend you try to ask for help in starting out your own solution in the Conan slack channel.  If you can share some of the high-level details about your scenario, you may be able to get some good tips.

**Comment by domfellner** [comment]
Wow, thank you for your comprehensive answer! 🥇 

I'm starting to query the slack history to dig deeper into this topic. Haven't thought of this a resource. 

Thanks already! After doing some research, I will post our use case into the Slack channel :bird:

**Comment by memsharded** [comment]
The issue https://github.com/conan-io/conan/issues/6851 talks about the possibility of storing the lockfiles in the server. Lets follow the conversation there, I am closing this ticket.

Conan 2.0 metadata files allows to store extra files together with packages, lockfiles can be stored there too.

Also https://github.com/conan-io/conan/pull/10261 is an attempt to integrate lockfile storage and make it more automatic and integrated. Lets follow up there too, thanks!
