### ISSUE TITLE
[question] lockfiles: update reference to comp-b but keep reference to comp-a from existing lockfile?

### ISSUE THREAD

**Issue by mjb6** [conan-io/conan#8279]
Dear conan community,

We want to use conan as a generic system integration tool (not directly to build C-components, rather to put already compiled
dependencies into a target format, e.g. by coping files).

I'm not sure if lockfiles are the right approach for us - could you please give me short feedback?

To understand our use case, I created a small example: https://github.com/mjb6/conan-lockfile-question
You can run the example by calling: build-all.sh

Here is a description of the example:
```
+------+    +------+
|comp-a|    |comp-b|
+------+    +------+
     ^        ^
     |        |
    +-----------+
    |integration|
    +-----------+
```

"integration" consumes "comp-a" and "comp-b" by a version range matcher. I use recipe revisions and package_ids.
To define if a pre-packaged "comp-a" is binary compatible, I only have the option: "my_option".
The recipe for the "integration" package just copies in the `imports`-method files from the components a and b around.

Here are some things that we want to achieve:
- We have a package of comp-a and a package of comp-b. When creating the package for "integration", we want to create a lockfile. (This works as expected)
- Let's consider new packages are arising for comp-a and also for comp-b.
- Now I want to use the new comp-b package, but keep the old comp-a reference from the lockfile. How can I do this? I tried everything from the docs but I have the feeling that your use cases are a bit different? Or I did not understand the docs ;)

In addition, I have another question:
- I can not create base lock files for a recipe with "options" and no "default_options" without specificing the options on the command line. Is this intended? Why do I need default_options to create a base lock file?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Thank you

**Comment by czoido** [comment]
Hi @mjb6,

The problem is that in your example [at this point](https://github.com/mjb6/conan-lockfile-question/blob/d1b8ee52373683bbf64e7d43af935c09de76aa71/build-all.sh#L47) you already have a fully locked lockfile and you can't modify it integrating the changes made in `comp-b`. You should [create a new lockfile](https://docs.conan.io/en/latest/versioning/lockfiles/evolving.html#integrating-a-partial-lockfile) (check the _Important_ warning there) instead of modifying the old one.
As you are using version ranges if you want to freeze `comp-a` you can create a partial lockfile before bumping the version and the recreating the lockfile for `integration` using that lockfile as an input. In your script it would look something like this:

```
#!/bin/bash

set -x

## Clean old builds
#conan remove -f "*"
rm -f locks/*

## Prepare environment
# 1) Build comp-a and create lockfile
cd comp-a
conan create . mjb6/testing -o my_option=value1
cd -

# 2) Build comp-b and create lockfile
cd comp-b
conan create . mjb6/testing -o my_option=value1
cd -

# 3) Integrate 1) and 2) into our "integration" project
cd integration
conan create . mjb6/testing -o *:my_option=value1
conan lock create --reference=integration/3.0.0@mjb6/testing --lockfile-out=../locks/integration_value1.lock -o *:my_option=value1
cd -
read -p "Preparation done. Press enter to continue"


## Example 1: Create new version of comp-a and comp-b. Integrate the update of comp-b but keep old version of comp-a
#  1) Create new version of comp-a
cd comp-a

# Create a partial lockfile for comp-a (before bumping comp-a) for using later to generate a new lockfile for integration that takes comp-a/1.0 and not the latest from the cache
conan lock create --reference=comp-a/1.0.0@mjb6/testing --lockfile=../locks/integration_value1.lock --lockfile-out=../locks/comp-a-1.0.lock -o *:my_option=value1

cp conanfile.py conanfile.py.bak
cp conanfile2.py conanfile.py   # this just updates the version from 1.0.0 to 1.1.0
conan create . mjb6/testing -o my_option=value1
mv conanfile.py.bak conanfile.py
conan search "comp-a/*"
cd -

#2  1) Create new package of comp-b
cd comp-b
cp conanfile.py conanfile.py.bak
cp conanfile2.py conanfile.py   # this just updates the version from 2.0.0 to 2.1.0
conan create . mjb6/testing -o my_option=value1
mv conanfile.py.bak conanfile.py
conan search "comp-b/*"
cd -

# 3) Re-Create "integration" package. It should still use comp-a/1.0.0 and not comp-a/1.1.0, but comp-b/2.1.0
cd integration

conan lock create --reference=integration/3.0.0@mjb6/testing --lockfile=../locks/comp-a-1.0.lock --lockfile-out=../locks/integration_value-with-comp-a-frozen.lock -o *:my_option=value1

cd -
```

For the `default_options` question, I think that is because even for the --base lockfile the graph has to be calculated and it can't be calculated without specifying that option.

**Comment by mjb6** [comment]
Hi @czoido 
thank you very much for the clarification! I think I understood it better now 👍 

Only one more doubt:
What happens if I have in addition a `comp-c`, Let's consider `integration` directly depends also on `comp-c`. Now let's say we get similar as for `comp-b` and `comp-a` a new version of `comp-c`.
But in my `integration`, I only want to update `comp-b` (and keep `comp-c` and `comp-a` in the old version).

Then I would have to somehow specify for `integration` package both `../locks/comp-a-1.0.lock` and `../locks/comp-c-1.0.lock`, because these component-specific partial lockfiles only have the information about themselves.
But giving several --lockfile arguments is not allowed.

Do you have an idea for this?

Thank you and best regards

**Comment by czoido** [comment]
Hi @mjb6,
For that case, that you want to lock both _comp-a_ and _comp-c_ in the old version I would recommend to create a new "proxy" package that depends on both of them use the lockfile of that one as an input when generating the integration package:

```
+------+    +------+    +------+
|comp-a|    |comp-c|    |comp-b|
+------+    +------+    +------+
    ^          ^            ^       
    |          |            |
  +-------------+           |
  |  proxy pkg  |  |--------|
  +-------------+  |
         ^         |
         |         |  
        +-----------+
        |integration|
        +-----------+
```
Using several lockfiles as an input is not supported because the logic could be very complicated. They could have been generated in different moments for different configurations and it's likely that many times they do not match with the rest of the graph.
Hope this helps.

**Comment by mjb6** [comment]
Hi Carlos, thank you very much for the explanation!
Proxy package also does not fit quite good for our use case, because it is not fixed which components should be updated - so we would need proxy packages for all combinations.
I think for now I stay with my non-lockfile approach, where I have an additional script that defines the requires (incl. rrev) in the integration conanfile.py, based on our integration methodology.
Thanks & best regards
