### ISSUE TITLE
[question] How to properly specify cmake version as build_requires?

### ISSUE THREAD

**Issue by dragondive** [conan-io/conan#8294]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I am learning how to use the `build_requires`, for example, as described in [this webinar](https://www.youtube.com/watch?v=ExpkMy6DJ6o). I have `cmake 3.18.2` installed locally. I want to build the package also with `cmake 3.19.2` without installing it locally. This is also as described in the webinar. 

The `cmake_installer` package used in the webinar is now marked as "legacy" (which I take to mean "deprecated"). So instead, I specify the `cmake` package as `build_requires` in `conanfile.py`:

    build_requires = "cmake/3.19.2"

Calling `conan install` with this, of course, downloads the specified package, but it doesn't build my package with this cmake version. Naturally, calling cmake afterwards uses the locally installed cmake version.

I understand conan has changed since the time the webinar was recorded. What changes do I have to make here so that I can build with the specific cmake version mentioned in `build_requires`?

**Comment by jgsogo** [comment]
Hi, @dragondive 

A lot of exciting things have happened since 2017. You can still use `build_requires` as it is explained in the webinar (stability commitment), but now we really encourage user to start using [two-profiles approach](https://docs.conan.io/en/latest/devtools/build_requires.html?highlight=build_requires#build-and-host-contexts) which is a more clear approach and much more powerful (and it will be the default and maybe only way in next major version of Conan, v2.0). 

If you are using the `cmake` package from ConanCenter (https://conan.io/center/cmake), that recipe is appending the path to executable `cmake` to the PATH environment variable (check `package_info()` function). Now, depending on you using one-profile approach or two-profiles one the way Conan work is slightly different.

---

Start with this very basic _consumer_ recipe:

```python
from conans import ConanFile

class LibConan(ConanFile):
    name = "lib"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"

    def build(self):
        self.run("cmake --version")
```

It will use whatever CMake version you have installed in your system: 

```
$> conan create conanfile.py
...
----Running------      
> cmake --version      
-----------------      
cmake version 3.18.4
```

---

Now, **add CMake as a `build_requires`** (notice you can also add build_requires to the profiles):

```python
from conans import ConanFile

class LibConan(ConanFile):
    name = "lib"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"

    build_requires = "cmake/3.19.2"

    def build(self):
        self.run("cmake --version")
```

Now, Conan will populate the environment before entering the `build()` method and the CMake executable will be available:

 * using one-profile (Conan v1.x default): 

```
$> conan create conanfile.py

...
----Running------
> cmake --version
-----------------
cmake version 3.19.2
```

:tada: :tada:  As expected, Conan is using the version taken from `build_requires`.

**Comment by dragondive** [comment]
Hello @jgsogo 
Thanks for the explanation. I understood why it wasn't working. 

I was building my code in a "standalone" manner, that is, only consuming the package. By calling `conan create` to create a package, the `build_requires` package is used in the build.
