### ISSUE TITLE
Add option to encrypt/decrypt registry.txt on windows (at least)

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#830]
This could be done using CryptProtectData/CryptUnprotectData. This would be useful in the case the remote requires credentials so you don't need to store your credentials in plain text. Of course, a cross-platform solution would be nice but it seems common to use this method on windows (IIRC this is what TortoiseSVN does).

**Comment by memsharded** [comment]
registry.txt only contains urls, it does not contain sensitive information, does it?
If anything, the sensitive information could be the one stored in the sqlite DB, and the password is never stored, only a JWT token, that the server expires. A ``conan user --clean`` also removes this information.

Also, Windows and other OSs have the functionality of encrypting user files, the full user home, or selected folders, not sure if conan should be responsible for this feature.

**Comment by rconde01** [comment]
So this would be the case where there is a redirecting server with authentication. In that case you would want:

https://myServerUser:myServerUserPassword@myConanProxy.com

**Comment by memsharded** [comment]
I see. 

Even though, if there are security concerns, I would advise to use a trusted file encrypting solution as Windows or Veracrypt.

Doing it at the application level doesn't seem the best approach. Access to registry.txt is very frequent, all conan commands access it several times, so continuously requesting the user some password would be very inconvenient/annoying. And if the credentials to the decryption keys are somewhat stored, then the system is totally vulnerable. 
Veracrypt and similar (Windows crypt), operate at the device/driver level for transparent decryption/encryption.

If the redirecting server is indeed a proxy, have you tried to use the proxies configuration? http://conanio.readthedocs.io/en/latest/howtos/proxys.html. It can be set as environment variables, so it won't be stored in conan files.

**Comment by rconde01** [comment]
CryptProtectData/CryptUnprotectData use the current user data to do encrypt/unencrypt. So it would not require user intervention.

**Comment by memsharded** [comment]
That is true. But in any case, IMHO, this still sounds as excessive technical debt, because it would require platform specific code, python wrappers for the functionality (win32crypt in pywin32 might do it, but then we need to make sure this is redistributed, packaged with conan, which might not be simple, and problematic, later generating multiple troubleshooting and support requests), for a use case that as today is still not big. But as usual, if this feature gets enough support (just added request for feedback label) and more people request it, we will reconsider.

I know it really sucks to have a plain text user/password on a text file, but being pragmatic, if someone gets into our accounts to see that file, they will probably have access to our ssh keys for github and others, to our online accounts (email, social, etc), as being automatically logged in is quite the default, unless you are extremely concerned about security. And if you are really concerned about security, you typically just encrypt your full home-folder, which is what I sometimes do, depending on the machine.

As the package-signing is an open feature request that we want to address soon, if we found any portable and secure way to encrypt files (the same that is used for package signing could be used for file encrypting), we will think if applicable to this use case.

**Comment by rconde01** [comment]
First a couple of notes, and then an alternate solution:

- You may need to consider a bit the corporate standpoint where there are policies that users don't have control over.
- Auto logged in is not common in a corporate environment.
- The credentials accessing conan through the wrapping server may be domain credentials which have a big issue if compromised. 

What about instead having a hook to get the credentials. I'm thinking in conan.conf you could set:

credentials_hook_script=C:\getcreds.exe

Then conan would call that script with the url as an argument, and the script would return "user:pass".

This allows you to hook in any mechanism you want, and the that mechanism doesn't need to be shipped or maintained by you (people could contribute stuff potentially).

On a related note...isn't this an issue when conan is hosted in artifactory? If you're just using the conan client, then I'm not sure how the problem would be different there.

**Comment by memsharded** [comment]
Yes, I understand, don't think that we haven't seriously consider the implications, and the importance to satisfy corporate requirements. I am not saying this is not wanted/useful, it is just a trade-off: excessive complexity will slow us down, and won't allow us to scale properly, with a bad impact for the whole community.

Actually, I have been thinking too before your latest comment about possibilities of some plugin architecture, that would allow to do things like the one you propose, but haven't found anything that fits well enough. Maybe just using environment variables replacement (like in public CI systems) in the remotes urls could be another way. So I am trying to figure out some generic-enough way to provide file encryption or at least securing the urls with passwords, without compromising too much the codebase.

And this feature might not be isolated, it should take into account our ongoing efforts to precisely improve over some corporate needs, one of them security: package signing, verified users, secure auth... So it might take some time to address it properly. If you are in an urgent need of this feature, because you are already deploying conan that way (with the urls with passwords in the registry), and just encrypting the userhome with Windows or Veracrypt is not possible, please contact us by email, maybe we could think of a quick temporary solution for you.

**Comment by rconde01** [comment]
I appreciate tradeoffs and priorities you must make. It is not an urgent matter for me. But since plaintext passwords are a nonstarter it will limit us to being behind the firewall in the short term. For now this is just an inconvenience but longer term it could be a blocker to other efforts.

I took a quick look and it seems Bitlocker can only encrypt entire drives, unless the info was out of date. Veracrypt might be a solution but I would need to look into it more.

If some solution for secure credential storage is on the roadmap for a reasonable near term, then I think that is sufficient. If that is likely to be years off, and we can't find a local solution, then it might be worth discussing other alternatives.

**Comment by rconde01** [comment]
I now see that EFS is available which can do folders and files. Not as secure as bitlocker but it might be sufficient until something else is available. I'll check it out.

**Comment by memsharded** [comment]
Thanks for understanding. Ok, hope EFS might be sufficient for a while. No, it wont be years off, not planned, but we would be talking about very few months. And the minute it becomes really a stopper, tell us.

**Comment by memsharded** [comment]
This issue has been inactive for more than 2 years now, and since them there are way more companies using Conan in multiple corporate environments. Since no further comments or request for it, so I think we are good closing it at the moment, and if users request something similar again, we will discuss about it.
