### ISSUE TITLE
[bug] self.run with StringIO affected by print_run_commands

### ISSUE THREAD

**Issue by spoofedex** [conan-io/conan#8319]
Hi all,

In some cases we use Conan to fetch some compilation flags through the command line (e.g. through wx-config/pkg-config). We do this by using self.run with a StringIO. This was working fine, until we decided to enable the print_run_commands option; now, the output in the StringIO also contains the command being executed. This causes parsing to fail (and to be impossible to do in a well-defined, forward-compatible manner).
We would like to keep print_run_commands enabled, because it's very useful to see the commands that are executed. But, in my opinion, it's not desirable to include the output when writing to a StringIO (or, anything other than stdout, for that matter).
I reported this as a bug, because it feels like a bug to me, though you may disagree with me on that one. Would you agree this is a bug?

Thanks in advance!

Best regards,
SpoofedEx

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10/Ubuntu 18.04
  * Compiler+version: N.A.
  * Conan version: 1.32.1
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
In the configuration, set:
```
print_run_commands = True
```

Then, consider the following conanfile:
```
from conans import ConanFile

class PkgaConan(ConanFile):
    name = "pkga"
    version = "1.0"

    def package_info(self):
        from six import StringIO
        string_buf = StringIO()
        self.run("echo Hello, world", output=string_buf)
        out = string_buf.getvalue()
        self.output.error("Output is: {}".format(out))
```

Execute:
```
conan create . test/test
```

Resulting output:
```
pkga/1.0@test/test: ERROR: Output is:
----Running------
> echo Hello, world
-----------------
Hello, world
```

While I would expect it to be:
```
pkga/1.0@test/test: ERROR: Output is: Hello, world
```

**Comment by memsharded** [comment]
I agree that at least this is not expected and probably bad UX or not clear interface.

I am also afraid that at this stage, it is very possible that we could be breaking someone else that is using this feature. Thinking that anyone that is using the ``output=StringIO()`` is because it is very likely that they are parsing the result string, and some of them might have taken into account that the string contain those lines. So I would like to propose a solution that would be a new UI (focused on being the canonical one in Conan 2.0), that would implement this more clearly.

**Comment by SSE4** [comment]
I think it's already problematic for several recipes in conan-center-index (e.g. boost, which uses StringIO for python detection)
/cc @madebr @Croydon

**Comment by madebr** [comment]
Yes, a flag/argument to not have the commands printed at the start would be useful.
It'ls be nice to not require extra string parsing to extract the output.

**Comment by ytimenkov** [comment]
Yeah, found in one of my readmes:

**NOTE**: `CONAN_PRINT_RUN_COMMANDS` and `CONAN_LOG_RUN_TO_FILE`
break build of boost because they pollute the output with command being ran.

**Comment by fanselm** [comment]
Any news on this issue?

I workaround it by manually using `subprocess.run()` instead of Conan's `self.run()`, but it would be nice if one could use the standard workflow.

**Comment by memsharded** [comment]
Conan 2.0 has redesigned this part:

- Dropped all configuration like ``print_run_commands``, CONAN_PRINT_RUN_COMMANDS and CONAN_LOG_RUN_TO_FILE, env-vars do not exist anymore.
- ``self.run()`` contains argument ``stdout`` that accepts a stream and will redirect to it the output, and ``quiet=False`` in case we want to hide some command, otherwise the command will be always printed to stdout. So if redirecting to your own stream, you can perfectly avoid printing the command to it.
