### ISSUE TITLE
[feature] config_install_url_update to support migrations

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#8323]
The `config_install_interval` attribute now supported in `conan.conf` (  https://github.com/conan-io/conan/pull/6824  ) is great.  Thanks.

We've found, though, that we sometimes need to support migrating users to a new config repo location.

Could we add support for a `config_install_url_update` `conan.conf` attribute so that if we have:

```
C:\dev\src>conan config install --list
0: {'type': 'git', 'uri': 'git@github.dev.myorg.com:oldorg/oldrepo.git', 'verify_ssl': True, 'args': None, 'source_folder': None, 'target_folder': None}
```

and then `https://bbgithub.dev.bloomberg.com/oldorg/oldrepo/blob/master/config/conan.conf` is changed to contain:

```
git@github.dev.myorg.com:neworg/newrepo.git
```

then conan config install list will be updated to:

```
C:\dev\src>conan config install --list
0: {'type': 'git', 'uri': 'git@github.dev.myorg.com:neworg/newrepo.git', 'verify_ssl': True, 'args': None, 'source_folder': None, 'target_folder': None}
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @michaelmaguire 

Seems a bit overkill for a Conan feature? I mean, it would be a sed command:

```bash
sed -i 's#git@github.dev.myorg.com:oldorg/oldrepo.git#git@github.dev.myorg.com:neworg/newrepo.git#' ~/.conan/config_install.json
```

For the Conan command, there would be unknowns: is it to be replaced in all possible places? Because 1 repo can be used in more than 1 origin, different folders, for example. Or is the replace only in 1 origin? At the end, it would be more complicated to learn the Conan command and what it means, that directly editing the file. Also, this might be a very occasional case, rather the exception than a normal, frequent operation. Or is it really something that happens very often?

**Comment by michaelmaguire** [comment]
> ```shell
> sed -i 's#git@github.dev.myorg.com:oldorg/oldrepo.git#git@github.dev.myorg.com:neworg/newrepo.git#' ~/.conan/config_install.json
> ```

This is for teams of dozens of developers.  How do you even know which machines to run such a sed command on?

The "pull" model the `config_install_interval` feature enables is quite powerful -- it just needs this migration feature...

**Comment by memsharded** [comment]
Closing this ticket as outdated, Conan 2 removed the automatic ``conan config install``, so this wouldn't be relevant anymore.
