### ISSUE TITLE
[bug] Same recipe getting different package revision on Windows to Linux and Mac

### ISSUE THREAD

**Issue by djeverett** [conan-io/conan#8324]
[conan-trace.log](https://github.com/conan-io/conan/files/5802994/conan-trace.log)

I have a Jenkins pipeline building fmt 7.1.2 as per the [conan-center code](https://github.com/conan-io/conan-center-index/blob/master/recipes/fmt/all/conanfile.py).  This builds in parallel on Linux, macOS and Windows.  I have package revisions enabled.

The trouble is that the package revision is the same for Linux and macOS, but different on Windows.  A `conan search --remote` only finds the Windows package.  So `conan install fmt/7.1.2` does not work on Linux and macOS.

### Environment Details (include every applicable attribute)
Windows:
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.32.0
  * Python version: 3.8.0

Linux:
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: GCC 9.3.0
  * Conan version: 1.32.0
  * Python version: 3.8.5
  
macOS:
  * Operating System+version: macOS 10.15.7
  * Compiler+version: XCode 12.3, Build version 12C33 12.0.0 (clang-1200.0.32.28)
  * Conan version: 1.32.0
  * Python version: 3.7.7

### Logs (Executed commands with output) (Include/Attach if Applicable)

Will attach a trace file to illustrate how I build the package.

**Comment by memsharded** [comment]
Hi @djeverett 

It is very likely that the problem is the git checkout CRLF. Recipe revisions are based on the recipe contents. If the recipe is changed, because you are checking out differently, then the recipe revision will be different. 

This is very expected, as the recipe revision also takes into account the sources contents. Sources might change CRLF and in some cases this can lead to completely different binaries (like all embedded text strings), so Conan cannot make assumptions here, neither change or modify the line endings of the files that it is handling.

So the best approach is to make sure that everything works is to define a common CRLF for all platforms with a ``.gitattributes`` file in your repo, containing something like ``*.py text eol=lf``. By the way, nowadays that all modern editors, even in Windows, handle correctly LF, I think there are no benefits of using CRLF in Windows, and it can leads to annoying situations, like huge diffs in git.

Please check that and let us know, this doesn't seem a bug in Conan.

**Comment by djeverett** [comment]
Thanks @memsharded  - looks like you were correct.  Adding a `.gitattributes` of `* text eol=lf` fixed it such that all packages got the same revision.
