### ISSUE TITLE
[question] CMakeToolchain does not set CMAKE_MODULE_PATH/CMAKE_PREFIX_PATH (of dependencies)

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#8336]
Hello,

When using the new `conan.tools.cmake.CMakeToolchain`,
`CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH` are set af follows:
```cmake
    set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR} ${CMAKE_MODULE_PATH})
    set(CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR} ${CMAKE_PREFIX_PATH})
```
The previous `cmake` generator extended this variable with (at least) the root directories of all dependencies:
```cmake
    # CMake can find findXXX.cmake files in the root of packages
    set(CMAKE_MODULE_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_MODULE_PATH})

    # Make find_package() to work
    set(CMAKE_PREFIX_PATH ${CONAN_CMAKE_MODULE_PATH} ${CMAKE_PREFIX_PATH})
```
where `CONAN_CMAKE_MODULE_PATH` contained a list with the root directories of all host requirements.

I suppose the reason is that conan CMakeToolchain is not fully finished yet?
MSVC runtime is also not set. (previously `CONAN_LINK_RUNTIME`)

**Comment by memsharded** [comment]
Hi @madebr 

With the current design, I would say that it is not the responsibility of ``CMakeToolchain`` to add these paths to the current build. The toolchains main responsibility is to define configuration related to the current package, its settings, options, etc. Whatever comes from dependencies should be probably managed by ``CMakeDeps`` instead.

In this case it seems this has some overlap too with the ``cmake_paths`` generator. What is the use case of automatically adding the root folder to the CMAKE_MODULE/PREFIX_PATH? I guess to find build scripts there, but that should be declared as ``builddirs`` instead, and there is also the ``build_modules`` feature of the new ``cmake_find_package[_multi]`` generators. It seems there are several ways to achieve the same, and with the new toolchains we should converge to 1 way.

**Comment by memsharded** [comment]
Regarding the other issue, ``CMAKE_MSVC_RUNTIME_LIBRARY`` is now set by the toolchain, have you checked it recentely?

**Comment by solvingj** [comment]
> Whatever comes from dependencies should be probably managed by CMakeDeps instead.

Of note, we do consider some cases to be exceptions to this rule, such as `RPATH` flags. Last time it was discussed, any future `RPATH` handling was envisioned to be done in toolchains and not in generators. Is that still the case @memsharded ?

However, in this case, `CONAN_CMAKE_MODULE_PATH` seems build-system related, so indeed it would probably be a better fit in `CMakeDeps` if it goes anywhere.

**Comment by lasote** [comment]
I opened a [PR](https://github.com/conan-io/conan/pull/9077) with a test for the `CMakeDeps` generator verifying that any directory declared at `cpp_info.builddirs` is added to the `CMAKE_MODULE_PATH` so you can `include` any cmake file in these declared folders but AFTER doing a `find_package` that locates the dependency.

I agree with @memsharded, this is the responsibility of the CMakeDeps, not the toolchain, and adding the root folder of the packages to the `CMAKE_MODULE_PATH` makes no special sense when we have the `cpp_info.builddirs`. 

About having `cpp_info.builddirs` and `cpp_info.build_modules`, I don't think we should unify them because it is a different concept, a build_module is automatically loaded when calling `find_package`, in the other hand, the .cmake files contained in the `cpp_info.builddirs` require an explicit call to `include` by the consumer.

**Comment by memsharded** [comment]
Hi @madebr 

Could you please clarify if we are missing some use case? It seems the test in #9077 verifies that files from packages added to ``builddirs`` (which is the root of the package by default) can actually be included from consumers. Are we missing something or this could be considered solved?

**Comment by madebr** [comment]
I postponed the work on the project where I stumbled upon this problem/question.
I'll try to revive it soon and if you hear nothing from me, then assume your brilliant work solved everything :smile: .
