### ISSUE TITLE
[feature] config install interval - don't reinstall same config

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#8359]
`config_install_interval` is great.  We have it set to a pretty low interval (1 hour) so that changes to the config get picked up as quickly as possible so we don't have to ask developers to manually update the config.  However, it's annoying to have same config installed over and over again.  It would be helpful to have it the interval logic check to see of the current config is the same and if so don't reinstall.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by AbrilRBS** [comment]
Hi! We're sorry that we didn't get to write you back, it was not our intention to ignore the issue.
I'm going to close this as stale because we're not implementing any more features in Conan 1, and Conan 2 has dropped automatic config installations, instead relying on users setting up their own ways to call `conan config install` - The automatic way was super flaky and we kept getting more and more complains of it not working as users were expecting.

Again, sorry about the lack of communication :)
