### ISSUE TITLE
[question] Missing packages depending on workflow lockfiles

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#8382]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

My CI/CD broke this week and I do not understand why. So hopefully you can enlighten me 😸 
- [workflow](https://github.com/prince-chrismc/user-management/actions/runs/497488848/workflow)

Simply put there are two steps where it calls
1. Create lock and create package
    - [download results](https://github.com/prince-chrismc/user-management/runs/1732031703?check_suite_focus=true#step:6:127)
2. Install package
    - [missing package](https://github.com/prince-chrismc/user-management/runs/1732039740?check_suite_focus=true#step:6:152)

❗ Step two **cannot** find the a required package

- The same recipe existings in two remotes, same hash revision.
- The calculated `package_id` is always the same (`172d4df94cc1013f078f78cc17fcd87234a0b70f`)
- ➡️ One remote hosts the packages compiled with a different libc (musl) than the stock glibc from `conan-center`

Why is the straight `conan install` unable to find the correct binary?

***

My assumption is the call to `conan lock create`downloads the recipes. Once they are in the cache the preceding call to `conan create` does not know the remote so it searches all available remote. In contrast, when `conan install` is called it knows the remote of the recipe and looks *exclusively* in the same remote for the package.

If the above is correct, could you explain the motivation behind this design?

**Comment by PengolodhGoedath** [comment]
As far as I can tell, the recipe revision ID changed between the `create` (openssl/1.1.1i#55d4cf80244573060fbd973268276e3e) and `install` calls (openssl/1.1.1i#d8a9ac920ca866a9f6e09e0010110892).

Since the `install` call doesn't use the lockfile, it is looking for a binary package for the newer recipe revision - but the binary package used by `create` was for the old recipe revision, so it isn't considered as a match.

The fix would be to hand the created lockfile over to the `install` call - then it would ignore the newer recipe revision and use the one stated in the lockfile instead.

**Comment by prince-chrismc** [comment]
55d4cf80244573060fbd973268276e3e != d8a9ac920ca866a9f6e09e0010110892 Perfect

Thank you for solving my mystery!
