### ISSUE TITLE
[question] Can we get system environment  var in profiles?

### ISSUE THREAD

**Issue by 19317362** [conan-io/conan#8385]
- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

A profile  like this works fine
`standalone_toolchain=/opt/cross`
`[env]`
`CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain`

`export MY_CROSS_ENV_VAR=/opt/cross`
`A profile  like this works dose not work`

`standalone_toolchain=$MY_CROSS_ENV_VAR`
`[env]`
`CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain`

**Comment by czoido** [comment]
Hi @19317362,
Yes, that's the expected behaviour. Environment variables are not expanded inside the profile, you can just declare them to use later but not use them inside the profile. Maybe it should be stated a bit clearer in the [documentation](https://docs.conan.io/en/latest/reference/profiles.html).
Anyway, we are working in more advanced profiles ([maybe using Python](https://github.com/conan-io/conan/pull/7922/files)) that will probably allow doing more things like using environment variables in them.

**Comment by 19317362** [comment]
> Hi @19317362,
> Yes, that's the expected behaviour. Environment variables are not expanded inside the profile, you can just declare them to use later but not use them inside the profile. Maybe it should be stated a bit clearer in the [documentation](https://docs.conan.io/en/latest/reference/profiles.html).
> Anyway, we are working in more advanced profiles ([maybe using Python](https://github.com/conan-io/conan/pull/7922/files)) that will probably allow doing more things like using environment variables in them.

Thanks for your info.
I'm trying to use conan + win + docker + cross compile for arm ( linux, android and bare bones embedded).
It seems CONAN can make my image work. But a lot of trying and trying is needed.

It's strange that the  $MY_CROSS_ENV_VAR works with NDK R22 profile + toolchain.

**Comment by bevinhex** [comment]
it would definitely be an enhance to be able to use existing environment variables inside profile, in my case, I'm using `conan install` with profile to install dependencies, basically cross compiling to android , however I do have NDK_ROOT variable as environment variable, which I can set and compile my code without dependencies, however when I cannot find nice bridge between conan profile and CMakeLists.txt file , ENV was obvious choice to put settings together, which I cannot at the moment, we are trying to compile our code for 5 platform , linux/windows/android/ios/mac, however even after being able to compile our own code for all those and run inside, we are struggling to get dependencies compiled correctly, and for each platform we are using separate CMakeLists.txt file, but for conan, all we can do is create separate profile , thus have to maintain at least 20 configuration (64bit/32bit ... ARM ABI...)
so far it is nightmare
nevertheless, being able to use ENV inside would enhance the workflow.

**Comment by memsharded** [comment]
We have merged https://github.com/conan-io/conan/pull/9147, that supports jinja2 templating for profiles. This allows not only to read env-vars, or platform configuration, but also to manipulate them, join, conditionals, fors, etc.

So I think this issue is closed by this (will be released next 1.38), please have a look at it and test it when released, feedback very welcome.
