### ISSUE TITLE
[bug] CMake FindGTest does resolve correctly for Conan Debug package of GTest

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan#8402]
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 10.15.6
  * Compiler+version: n/a
  * Conan version: 1.32.0
  * Python version: 3.8.6

### Steps to reproduce (Include if Applicable)

Also reported here: https://github.com/bincrafters/community/issues/493#issuecomment-768726222

----

I think I am experiencing a similar situation as https://github.com/bincrafters/community/issues/493, even though using latest GTest 1.10.0 package from conan center and CMake 3.19.1 (or latest 3.19.3 which gives the same error).

Compiling on macOS and including gtest via `build_requires` and trying to compile my own package/library and CMake's `FindGTest` tries to set variables `GTEST_LIBRARY` `GTEST_INCLUDE_DIR` `GTEST_MAIN_LIBRARY` set, but these cannot be set when building your own library in `Debug` mode as the [`FindGTest` logic](https://github.com/Kitware/CMake/blob/v3.19.1/Modules/FindGTest.cmake#L205) tries to set these variables based off the library filenames in the found conan package.
So e.g. via Conan setting `-s build_type=Debug` which then targets the debug Conan package of GTest, which *has only* the debug libraries compiled and available there (i.e. `lib*d.a`) it sets variables `GTEST_LIBRARY_DEBUG` and `GTEST_MAIN_LIBRARY_DEBUG` but not  `GTEST_LIBRARY` and `GTEST_MAIN_LIBRARY` and thus the `FindGTest` fails with a `NOTFOUND` as its [logic](https://github.com/Kitware/CMake/blob/v3.19.1/Modules/FindGTest.cmake#L205) depends on the non-debug CMake variables.

To fix, either
1. `FindGTest` needs better logic to carry debug variables over to release ones when only debug is found, or
2.  Conan GTest package needs to [include both debug and release in the same package](https://docs.conan.io/en/latest/creating_packages/package_approaches.html#n-configs-1-package), and `FindGTest` will thus still always use released libraries, but at least it will not error.
3. Specify a Conan profile to always override/set GTest `build_type` to `Release` (https://github.com/conan-io/conan/issues/3000). But this is just circumvention of the problem.

**Comment by jgsogo** [comment]
Hi, @SeanSnyders 

I'm not sure which package are you talking about. I will refer to [`gtest` from ConanCenter](https://conan.io/center/gtest) (you can find the recipe in this repository: https://github.com/conan-io/conan-center-index/). If your issue is related to the recipe owned by Bincrafters (or any other recipe), then it is better for you to open an issue there.

Conan packages are expected to be consumed using Conan generators (`cmake_find_package`, for example will generate file `FindGTest.cmake`) that provide the variables and the paths to the headers/binaries included in the package and to all the transitive dependencies. Packages are not perfect, the community is continuously improving them, maybe this recipe requires some [`build_requires` to populate specific CMake variables](https://docs.conan.io/en/latest/reference/conanfile/attributes.html) based on the information provided by Conan. If this is the issue, then it is better to open it in the `conan-center-index` repository, I'm sure someone will be glad to improve the recipe.

Usually GTest is a library you want to use as `build_requires`, but you want it in the _host_ context because your tests will link with GTest. Use `self.build_requires('gtest/10...', force_host_context=True)` (in case you are using Conan with two-profiles, it will force you build-requires to be a _host_ package as your library). It is not the case of Protobuf and Protoc that complicates the graph a little bit more.

Let me know your comments about these introductory questions and then we can move to the GTest recipe you are using and see how you can consume it (or maybe the recipe has a bug or requires some patch).

Thanks!

**Comment by SeanSnyders** [comment]
@jgsogo Thanks for the reply and comments.

I think ultimately the problem does not seem to be a conan package issue.

Maybe a detail I missed to note: I first run `conan install ...` to install and collect all dependencies, etc. Then I want to generate project files for a specific IDE that CMake supports, say xcode, or VS. To achieve this, I need to run the same CMake as what my `build_requires` specifies, and this seems to pick up the `FindGTest` of the CMake installation. This does indeed find the right conan center package for the GTest (the one downloaded into my conan cache due to the `build_requires`), but the logic in the standard CMake 3.19.1 version of `FindGTest` does not resolve the difference for `debug` or `release` specifications via the conan settings, as noted in my original post.
The above description and explanation was using the plain `cmake` generator in conan.
(I refer to the links in my original message).

I then proceeded to only use `cmake_find_package` generator in conan (as you suggested), and this works well to find `GTest` and uses the generated `.cmake` file to resolve the dependency correctly during triggering of builds via conan **but if, and only if** builds are initiated through `conan`.
How would I go about to generate e.g. xcode or VS project files via `conan` instead of `cmake` such that it still picks up and correctly use the conan generated `Find*.cmake` etc files and not jump to the downloaded `cmake` versions thereof?

**Comment by SeanSnyders** [comment]
I have found an answer to my last question. If I add the conan generator `cmake_paths` in addition to the `cmake_find_package `, then I can specify this as a toolchain file for CMake which then sets up the paths correctly and thus use the conan generated `Find*.cmake` files, e.g.

1. Triggering build via conan:
```
conan install . -o shared=True -e CONAN_RUN_TESTS=1 -s build_type=Debug -if cmake-build-debug
conan build . -c -b -bf cmake-build-debug
```

2. Generating e.g. Xcode project:
```
conan install . -o shared=True -e CONAN_RUN_TESTS=1 -s build_type=Debug -if cmake-build-debug
cmake -B cmake-build-debug -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DBUILD_TESTS=1 -G Xcode
```

I think this issue can probably be resolved.
Overall pretty tricky situations catering for multi-platform development support whilst juggling conan dependencies for the various platforms as well as IDEs....
