### ISSUE TITLE
[feature] Parse options as first thing in conan workflow

### ISSUE THREAD

**Issue by at185190** [conan-io/conan#8411]
So we ran into few issues, stemming with our need to change package version and dependencies versions on the fly.

While we are able to do all that in set_version or within requires , its all static.
If we want to pass in a path to custom ini file containing version, we can't as options are not yet available during those methods evaluation.

We have to resolve to setting numerous env variables to override these options, which we should not have to do.

Is there a reason, why options, settings or any other conan variables not parsed and evaluated as a first thing within conan's workflow?

If I am able to change all those attributes statically, there should be no harm for me to pass in say -o version=1.2.3 and have it available during requires and set_version methods, I could argue that ability to pass in version should be standard conan feature.

**Comment by czoido** [comment]
Hi @at185190,
Thanks a lot for the feedback and question. The problem of having the options available in `set_version` is that the graph is not evaluated yet and you can't know the options at that point. Anyway, it would be impossible to evaluate the graph because you don't know the version... 
If you do a conan create for example, the order of executions of the methods is:

```
init()
set_name()
set_version()
export()
export_sources()
config_options()
configure()
requirements()
package_id()
validate()
build_requirements()
build_id()
imports()
build()
package()
package_info()
```

Options should not be fully available until the [validate()](https://docs.conan.io/en/latest/reference/conanfile/methods.html#validate) method. 
Maybe if you give us more details of the your workflow we can come up with some ideas.

**Comment by at185190** [comment]
Options are arguments you pass in, why do you need to know version to evaluate arguments that are being passed in, you don't have to act on them, just have them parsed?  

One of our requirements is to parse ini file for version, which is easy and is one of examples on official documentation, but that path is static, I can't say, build this and use this version file with this path, as there is no way for me to pass the the path via options argument, for it to be accessible in set_version()

Also no ability to pass in version via arguments or even versions of dependencies, which is something that would be very useful in CI workflows.

**Comment by czoido** [comment]
Hi @at185190,
Have you tried to set the version via the command line? You can do: `conan create . version@` and that will set the version of the package, maybe that helps you solving your problem?
If not, I think that for what you want to do, probably environment variables are a better option than using the options for passing those arguments. The purpose of options is defining the binary compatibility affecting the `package_id`. If you want to pass arguments as options you will have to clear those options later in the `package_id()` method.

**Comment by solvingj** [comment]
@at185190 

I want to add to what @czoido has said.

> Options are arguments you pass in, why do you need to know version to evaluate arguments that are being passed in, you don't have to act on them, just have them parsed?

This statement is technically correct (the best kind of correct). In theory, the arguments could be parsed and converted from strings to structured data which could be made available when you need them for your use case.  It's technically possible (again in theory).

However, Conan is of course, complex and nuanced.  The un-intuitive point causing confusion/frustration lies in your first question: 
> Is there a reason, why options, settings or any other conan variables not parsed and evaluated as a first thing within conan's workflow?

In this question, you grouped "parsed and evaluated" as if it was a single step, because logically these two things should almost always be done at the same time.  And, indeed, it currently is effectively a single step in Conan from the recipes perspective.  Also, for the record, it definitely is done very early in Conan's process.  

The problem for you is that you is that the "option evaluation" part of that step requires the recipe `version` to have a value (for fundamental graph reasons), so it is very much a chicken-and-egg problem.  As you are suggesting, your very specific case only requires the options to be parsed and exposed to the recipe at that point in time.  Then in theory you could read the one you need, and then set the `version` based on it, and then Conan could go forward with "option evaluation". 

With all that said, as @czoido said, environment variables are most certainly a more appropriate choice than options here for numerous reasons (mostly related to `package_id`).  

@memsharded does this seem like it could be a candidate for some combination of `[conf]` and the `init()` method?

**Comment by at185190** [comment]
> Have you tried to set the version via the command line? You can do: `conan create . version@` and that will set the version of the package, maybe that helps you solving your problem?

This doesn't work if you are using set_version() to read the value from a default location, which for us is local version.ini file.
Conan will barf that version passed in doesn't match one in recipe.

We are resorting to using env variables, but its ugly, clunky and all around horrible when compared to arguments you can pass in.
If options cannot be available due to package_id calculation, maybe there should be a type of options, that by default are not included in any hash and can be made available much quicker?

**Comment by solvingj** [comment]
> maybe there should be a type of options, that by default are not included in any hash and can be made available much quicker?

That's precisely what environment variables are.  

> We are resorting to using env variables, but its ugly, clunky and all around horrible when compared to arguments you can pass in.

They are variables that you can pass in.  

Actually, based on your comments, it seem like currently you might be setting the env vars from your shell/prompt prior to calling Conan.  Maybe you are unaware that you can pass env vars with `-e somevar=someval` which is syntactically identical to passing options with `-o somevar=someval`.  They both support the package specifier prefix as well: `somepkg:somevar=someval`.  If you want to do in profiles, you would just use the `[env]` block instead of the `[options]` block.  

Please clarify how you are setting environment variables. 

Of note, my question to @memsharded in my previous comment was referencing the new `[conf]`item which has some overlap with environment variables and options, but with some subtle differences from both.

**Comment by at185190** [comment]
Yup, I was unaware that environment variables can be passed in this way, that is indeed far more graceful that other ways to set them, also ability to pass env variables to dependencies is brilliant, exactly why we wanted to have options as those allow passing options to dependencies.

I assume I env variables names can be same for target and a dependency while having different values? e.g. 
-e firstDependency:dep_ver=2.1.1, bestDependency:dep_ver=12.3

**Comment by solvingj** [comment]
Yes, they certainly can.  IMO, it's a pretty amazing feature of Conan.

Please double check that the environment variables set this way have the appropriate values at the time you need them in order to set the `version` field. Let's make sure your use case is fully resolved before we close this ticket.

**Comment by at185190** [comment]
So I am having trouble retrieving env variables passed in with -e, conan in its settings table will show it under [env], but I am unable to retrieve it with tools.get_env, or via direct python  os.environ: both are not able to find any env variable i pass in via -e 

Ok it turns out, those env variables are bit fake, they are not available in set_version, surprisingly they are available in requirements, but I need them to be available in set_version too.

So I am back where I started as it seems.. Need something that is available straight away :(

**Comment by solvingj** [comment]
Ok, that is very unfortunate.  @memsharded do you think that `[conf]` values will be made available during the `set_version` method?

**Comment by DdOtzen** [comment]
I like to join the choir.
I have a similar problem, with set_version method.
In conjunction to introducing git and new build setup, we started to get the version based on git tree, this works fine.
But for back-compatibility reasons we need the option to use legacy versioning method in some builds
I wanted to to use options to tell conan to use legacy versioning, or after reading this thread the -e option. but as @at185190 I conclude it does not work.

My not so pretty workaround
``` python
    def set_version(self):
        if 'legacyVersion=True' in sys.argv:
            self.version = GetLegacyVersion()
        else :
            self.version = GetVersion()

```
As test i tried
``` python
    def set_version(self):
        print(tools.get_env('LEGACY_VERSION', 'not there'))
        self.version = '2.2.2'
```

if I thern call 
``` powershell
conan install -e LEGACY_VERSION="True" .
```
I get 
"not there"
but if I do 
``` powershell
$env:LEGACY_VERSION="True"
conan install  .
```
I get 
"True"¨

And i agree with @at185190 that is the clunky way of doing it.

**Comment by DdOtzen** [comment]
I might add, that I get henn and egg problem with options.
But I then vote that this feature request is renamed to something like
"Set environment vars from -e option  as first thing in conan workflow"

**Comment by at185190** [comment]
So something that's related, a global variable that's set during set_version method is not set/available within build() method during conan create step, but works perfectly if you do install build package export-pkg.

Why would that be?

**Comment by petermbauer** [comment]
Same usecase here with setName() and not wanting to use env vars in the shell for this.
Any news on this? Maybe for Conan 2.0?

**Comment by memsharded** [comment]
Hi @petermbauer 

I am afraid it is not possible. The ``set_version()`` and ``set_name()`` happen too early in the process, and they happen also in many contexts that there is no profile information at all (like ``conan export``, which is profile-less, there are no options defined at all, and it makes sense, because the export cannot be conditioned to anything, it must always be the same for all different configurations).

So whatever need to be hacked there, should be done via system env-vars (not Conan env-vars). And I'd like to suggest that this is probably not the best approach, as it is something that is clearly non-deterministic, and there might be other alternatives. The idea of this feature is that the name and version can be extracted from the repo, from files, or the git tags, but something that is clearly defined. Some ideas:
- If the name and version are defined in CI by the build process, they can be passed in command line directly, no need to define something so the methods can read it.
- In developers machines, typically depending on some env to be defined is a fragile approach and tend to be problematic, better make it explicit by requiring command-line arguments.

I think this ticket can be closed, as this is something that really cannot be implemented in Conan, and the only possibility is using system env-vars. Thanks!

**Comment by petermbauer** [comment]
Hi, thanks!

For the records, i also tried it with a "custom" `[conf]` entry in the profile file but the config values are apparently not available in the `set_name()` as well.

**Comment by memsharded** [comment]
Yes, exactly, the ``[conf]`` is part of the profile, and ``conan export`` that needs to obtain the name and the version, doesn't get profiles at all.

**Comment by petermbauer** [comment]
I ended up with separate conanfiles, one common `_conanfile_base.py` containing everything except the `name` and `description` attributes and one for each "variant" which imports the common file and defines the attributes like this:
```
from _conanfile_base import *


class VariantX(Base):
    name = "variantx"
    description = "Variant X of product Y"

```
The name could also be derived from the filename to get rid of the redundancy.
