### ISSUE TITLE
[question] conan upload --no-overwrite all still runs checks?

### ISSUE THREAD

**Issue by Chemrat** [conan-io/conan#8413]
Hello,

I've noticed that `conan upload` runs checks even for packages that have identical `PacakgeID` in the remote, even when `--no-overwrite all` is enabled, which I'd assume forbids conan to overwrite the package if it differs.

I'm trying to use the following workflow:
- in a clean environment, `conan install -b outdated` to pull in and build dependencies if nescessary, launched through conan-cmake
- build the application
- `conan upload "*" --confirm -r foo --all --no-overwrite all` to push the binaries back to the remote, so next time I won't have to build them

However conan upload ends up re-compressing all the downloaded packages each time, only to claim that they do not differ from the remote, and this blows up CI times significantly.

Is there a way to disable this? Or I'm misunderstanding something or doing something wrong?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Chemrat 

> I've noticed that conan upload runs checks even for packages that have identical PacakgeID in the remote, even when --no-overwrite all is enabled, which I'd assume forbids conan to overwrite the package if it differs.

Yes, the PackageID is not globally unique, it is the hash of settings+options+dependencies, so different packages can have the same PackageID for its binaries. Without using revisions, the binary can be rebuilt, and the checksum of the packaged ``conan_package.tgz`` is what is being used to check if necessary to re-upload it or not.

However, latest Conan versions do not need to re-compress the ``conan_package.tgz`` because they are cached. Make sure you are upgraded at least to Conan >= 1.31.0, and try again. Your CI should be much faster.

**Comment by Chemrat** [comment]
Oh this is my bad.

Before opening the question I actually checked if the behaviour still the same with 1.33.0 on my dev machine, but for some reason conan would still compress (probably because binary packages on the dev machine were built and not downloaded), so I assumed the behaviour actually haven't changed.

However this is not the case on CI after the update to 1.33.0: now conan performs no re-compression and the issue is now solved. Thank you for answering the question!
