### ISSUE TITLE
[bug] ERROR: compiler.version setting required for vcvars not defined

### ISSUE THREAD

**Issue by oranger34** [conan-io/conan#8429]
### Environment Details (include every applicable attribute)
  * Operating System+version: win10
  * Compiler+version: gcc 9.2.0
  * Conan version: 1.29.0
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)

I try to build libx264 in windows. I made it as a requirement of my project. But when I run conan install , it failed.
"ERROR: compiler.version setting required for vcvars not defined"
What does it mean？ How can I fix it?

In settings.yml, I set visual studio version to None.
Here is my profile:
Configuration for profile win32_profile:

[settings]
os=Windows
arch=x86
compiler=Visual Studio
build_type=Release
[options]
[build_requires]
[env]

I build it by gcc, but publish to conan using visual studio settings.

Thanks!

### Logs (Executed commands with output) (Include/Attach if Applicable)

conanfile.py (tutor_live_engine/0.2.0): Installing package
Requirements
    Eigen/3.3.7@yfd/stable from 'live_engine_conan_server' - Cache
    RapidJson/1.1.0@yfd/stable from 'live_engine_conan_server' - Cache
    boringssl/1.0.2@yfd/stable from 'live_engine_conan_server' - Cache
    poco/1.9.4.1@yfd/static from 'live_engine_conan_server' - Cache
    tutor_ffmpeg/0.2.0@yfd/stable from 'live_engine_conan_server' - Cache
    x264/0.1.1@yfd/stable from 'live_engine_conan_server' - Cache
    zlib/0.2.0@yfd/stable from 'live_engine_conan_server' - Cache
Packages
    Eigen/3.3.7@yfd/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    RapidJson/1.1.0@yfd/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    boringssl/1.0.2@yfd/stable:df5b97bfe76ac34ac02a124d39203043c41ec57c - Cache
    poco/1.9.4.1@yfd/static:df5b97bfe76ac34ac02a124d39203043c41ec57c - Cache
    tutor_ffmpeg/0.2.0@yfd/stable:1857c71a9899e0beb5ee8eaf30e3dbed7be4cc43 - Cache
    x264/0.1.1@yfd/stable:df5b97bfe76ac34ac02a124d39203043c41ec57c - Cache
    zlib/0.2.0@yfd/stable:df5b97bfe76ac34ac02a124d39203043c41ec57c - Cache

Cross-build from 'Windows:x86_64' to 'Windows:x86'
Installing (downloading, building) binaries...
Eigen/3.3.7@yfd/stable: Already installed!
RapidJson/1.1.0@yfd/stable: Already installed!
boringssl/1.0.2@yfd/stable: Already installed!
poco/1.9.4.1@yfd/static: Already installed!
x264/0.1.1@yfd/stable: Already installed!
zlib/0.2.0@yfd/stable: Already installed!
tutor_ffmpeg/0.2.0@yfd/stable: Already installed!
conanfile.py (tutor_live_engine/0.2.0): Generator json created conanbuildinfo.json
conanfile.py (tutor_live_engine/0.2.0): Generator txt created conanbuildinfo.txt
ERROR: compiler.version setting required for vcvars not defined

**Comment by memsharded** [comment]
Hi @oranger34 

You can see in your profile settings:
```
[settings]
os=Windows
arch=x86
compiler=Visual Studio
build_type=Release
[options]
[build_requires]
[env]
```

It doesn't have a ``compiler.version`` defined. You need to define ne, as that will be the VS version that will be used to define which binaries need to be installed and built. Please add it and re-check.

What I don't understand is ``I build it by gcc, but publish to conan using visual studio settings.``. How did you do this? Why? This is typically problematic. If you want, you might explicitly use per-package settings to define its values something like:
```
[settings]
os=Windows
arch=x86
compiler=Visual Studio
compiler.version=15
build_type=Release
mypkg:compiler=gcc
mypkg:compiler.version=6
[options]
[build_requires]
[env]
```

That will force ``mypkg`` dependency to be using gcc, but erasing that information from the package might typically be problematic.

**Comment by oranger34** [comment]
@memsharded  
Thanks for your quick reply!
As for the 'mypkg:compiler.." config, I may try it later on.

But I am wondering if 'compiler.version' is a must?
I have built a couple of packages and never specifies compiler.version.

https://github.com/conan-io/conan/issues/7077

In the above thread, you also mentioned we can set compiler.version to None.

Why does it happen on this libx264 package?
Is there anything I am missing?
If I want to leave the compiler.version empty, is there any other solution?

Thanks!

**Comment by memsharded** [comment]
> But I am wondering if 'compiler.version' is a must?
I have built a couple of packages and never specifies compiler.version.

 In #7077 I was explaining that you might delete and forget about the ``compiler.version`` in your package with ``del self.settings.compiler.version``, if your package recipe doesn't need it. It can work in gcc compiler, because it is not necessary to specify it, as the system might have a gcc installed by default, and it will be found. It is probably not a good or recommended approach, but it is doable with Conan. Conan always try to be very flexible and allow users to do what they want, at their own risk (like C and C++)

The error you get is happening because Visual Studio does not have a default version, and it is not in the path by default. The build helpers that recipes are using need the compiler.version to determine which Visual Studio to use for building things. As it is not defined, the build helper stops. You could try to provide your own build helpers that do whatever logic you want to do, but I guess that would require doing changes in the recipes and some effort.

I would totally recommend defining the ``compiler.version``. The possible benefits of not defining it are almost sure not worth for 99% of use cases.

**Comment by oranger34** [comment]
I may add these settings in profile:

x264:compiler=gcc
x264:compiler.version=9.2

It works!
Thank you very much!

**Comment by oranger34** [comment]
Here is my solution:

def configure(self):
        if self.settings.os == "Windows":
           self.settings.compiler.version = 15;

**Comment by solvingj** [comment]
@oranger34 may we close this issue?
