### ISSUE TITLE
Using cmake files provided by package (in custom dir, not root)

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [conan-io/conan#846]
Hi there,

i am currently working on a Qt package, which provides self packaged cmake files located in <package>/lib/cmake. I don't know what i should do that cmake now prefers the cmake files provided by the package in contrast to those of the system.

For example i want to use the `find_package(Qt5Core 5.8 REQUIRED)` statement, but this one searches in my system pathes, instead of the package pathes. Those cmake files are necessary to define additional cmake functionality, like the `qt5_add_resources` command.

best,
Christian

**Comment by lasote** [comment]
Currently we only support the `findXXX.cmake` files in the package root folder. We auto adjust the `CMAKE_MODULE_PATH` variable to the packages root folders.
If you want to use custom folders we need to adjust the `CMAKE_MODULE_PATH` manually or alter the `CONAN_CMAKE_MODULE_PATH` variable appending the subdir before calling the CONAN_BASIC_SETUP.

We understand this is not ideal, but the only supported right now. I'm marking the issue as a "feature needed" and will try to look for a better fix.

Thanks!

**Comment by d-schiffner** [comment]
Hi,

this is a very good idea. I'm actually trying to get this to work, because of the modern import using the INTERFACE does impose some limitations regarding the corrrect ordering of libraries if using static linking. I had a found a bug there #774, where i talked with @memsharded about a solution for the bug and the correct ordering as well.

I think, it would be possible to extend the existing conanbuildinfo.cmake template to support such a discovery of cmake files.

However, I see some challenges / questions:
- Naming of packages is different from conan: [PKG_NAME]::lib vs CONAN_PKG::[PKG_NAME]
- How are dependencies then found?
- Does the conanfile need the information of the location, or does cmake search for it?
- Does conan provide an own find_package compatile solution?

Because I need this for my conan solution as well, I going to have a look, whether or not i can provide such a solution.

**Comment by cguentherTUChemnitz** [comment]
I solved my problems in the meantime. Here are my insights:

It seems that the current conan does work for my use-case. I can use directly the `find_package` statement. The package Qt version if found and their Qt::[PKG_NAME] cmake targets are usable. I missed the qt package path reconfiguration for the runtime with `configure_file(qt.conf.in ${CMAKE_BINARY_DIR}/bin/qt.conf)` statement.
