### ISSUE TITLE
[feature] Local build policy

### ISSUE THREAD

**Issue by euttsov** [conan-io/conan#8479]
Hi all. 
It would be nice to have the build policy that for forbids download binary packages from remote. When this policy applied package sources should already be in local cache and if binary missed in local cache then it should be build and can be used later by other packages. 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment]
isn't this behavior covered by the `always` build policy?

> The always policy will retrieve the sources each time the package is installed, so it can be useful for providing a “latest” mechanism or ignoring the uploaded binary packages.

https://docs.conan.io/en/latest/mastering/policies.html#build-policies

**Comment by euttsov** [comment]
@danimtb `always` policy leads to rebuilding all dependencies from sources for each package, but I thought about the policy that allows reusing binary packages that already were built from sources in the local cache but forbids downloading binaries from remote at the same time.

**Comment by danimtb** [comment]
@euttsov thanks for the clarification. Indeed, something like a `local` build policy will make it. Currently I believe we do not have any kind of *mark* in the cache that says that the package was built locally. Maybe we could check if the build folder exists or something similar

**Comment by euttsov** [comment]
@danimtb yes, that something that i looked for. This is needed to ensure that all our package tree built correctly alltogether. Thanks for the answer.

**Comment by memsharded** [comment]
Closing this ticket as unplanned.

Something like this shouldn't be necessary. For this use case there are 2 alteranatives:
- if the reason is to control the binary model with more precision, the approach would be to define custom settings via ``settings_user.yml``
- If the reason is simply building from source, then building from source from a fork of ConanCenter Github repo, or using the ``local-recipes-index`` feature https://docs.conan.io/2/devops/devops_local_recipes_index.html would be recommended.

Please create new tickets for any further question or issue, thanks for your feedback.
