### ISSUE TITLE
[feature] Add an option to print local package paths in search

### ISSUE THREAD

**Issue by kdsx** [conan-io/conan#8481]
Maybe I miss something, but currently there's no a simple CLI way to get a package path in the local cache.
When I sometimes need to check what is inside the downloaded package, I have to invoke `conan search`, find the package ID, then manually compose the following: `~/.conan/data/<name>/<version>/<user>/<channel>/package/<package_id>`. It would be **much** simpler and faster if conan had an option to print package paths in the local cache (if any) for every found package ID in the search output.

Maybe it also useful to opt-in package paths printing for `conan install` summary. When our devs sometimes need to investigate a package internals, I suggest they open `conanbuildinfo.cmake` to find package paths, as it looks like the simplest option. Again, if conan just print all the paths in the `conan install` output, we won't need any instructions.

**Comment by nichmj01** [comment]
It looks like you can use conan info with the --paths option to get what you want? 

`conan info --paths mypackage/1.0.1`

It will also print out the paths for any dependencies

**Comment by kdsx** [comment]
Perfect! Thanks! It does the job.

**Comment by nichmj01** [comment]
You can also run it against your consumer project to list the paths to all your dependencies instead of having to know the package reference and it can be combined with the --only option to print only the folder locations and not all the other info, if you don't care about it.

`conan info --paths --only package_folder --only source_folder . `
or
`conan info --paths --only package_folder --only source_folder ./conanfile.py`

**Comment by kdsx** [comment]
Yep. I've already tried it.
