### ISSUE TITLE
[feature] allow no matches when using upload patterns

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8518]
Due to our access policies, all packages developed by third-party suppliers must be uploaded to a separate Artifactory repository.  This is to limit the suppliers' access to their own packages only.  (As far as I know Artifactory can only limit on a per repository basis.)

I tried to use upload patterns to achieve this:

`conan upload */*@<supplier>/* -r <supplier_repo>`

However, this fails when no packages in the cache match this pattern:

`ERROR: No packages found matching pattern '*/*@<supplier>/*'`

In that case I'd like it to exit silently, having found nothing to upload.

**Comment by danimtb** [comment]
Hi @GordonJess,

This is something not supported currently and the only thing you could do is to reduce the logging level, although that will not make the command exit without error.
I am adding this consideration to the redisgn of the command line towards Conan 2.0

**Comment by memsharded** [comment]
Yes, this has been fixed in 2.0, the way the pattern is analyzed, so this will not raise an error, as long as it contains a pattern. If an exact reference like ``conan upload zlib/1.2.11:*`` is used, and if zlib/1.2.11 doesn't exist in the cache, it will error. But as long as the first part contain a ``*``, it will not error.

This is part of the latest 2.0-beta.6
