### ISSUE TITLE
[feature] Have `update` only make a single request to avoid long delay

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#8548]
Hi, using Conan over a VPN network, each request and response has some delay (about 0.5 second in our case). This means that running Conan commands with the update switch (`-u`) takes upwards of a minute to complete even if everything is up-to-date when you have a large dependency graph. I was wondering if you could combine all the recipe revision checks in a single packet (or as few as possible).

- [✓] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @daravi,
Thanks for your suggestion. Unfortunately, there's nothing we can do right now to relieve this problem as this would imply changing the API with the server, but right now we are in the process of designing how Conan works with a multi-revision cache and servers and what does updating means in this context. We will have this kind of problems in mind to make the graph resolution with --update as fast as we can.
Sorry we can't do anything more right now.

**Comment by daravi** [comment]
@czoido Thanks it would be great if this was considered for next design then. Feel free to close the ticket or change the tag to that future version if this is something that will be considered seriously for that version thanks.

**Comment by memsharded** [comment]
It happens that recipe revision update checks cannot easily be done in batches, because recipes are evaluated one by one, in order to compute the graph. If a recipe is going to get an update, it can, and often will do, change its dependencies. So the transitive dependencies of every package in the graph need to wait until the update of the downstream one is done. And that for every package in the graph. While some minor degree of parallelism might be possible with an aggressive parallelization of the algorithm, its degree will always be limited, so at the moment doesn't seem worth the complexity.

In any case, the performance improvement will come not because of doing a single request for a batch of updates, but for doing parallel requests for recipes being processed in parallel.

We will probably do an attempt of parallelizing the graph resolution algorithm after Conan 2.0, but not high priority at this moment. I am going to close this ticket as this potential change of the API client-server is not possible in any case. Thanks!
