### ISSUE TITLE
[feature] get profile name from lockfile

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#8580]
Very excited about the new bundles feature and have been trying to take your examples one step further and test it out in a CI flow where packages are rebuilt by triggering their respective CI jobs.

When triggering the build I should only need to share the bundle and lockfiles with the downstream build.  But one issue with this is the loss of the profile name, and so far the name has been quite useful for organisation purposes.  Naming the lockfile upload paths for example:

`${env.JOB_NAME}/${env.BUILD_NUMBER}/${name}/${version}/${user}/${channel}/${profile}/conan.lock`

I can understand why you might not want to store the name in the lockfile itself, but for me it would be quite useful to trace a lockfile back to a profile name to quickly know which configuration it was created for.  Perhaps you can detect if any existing profile matches the values stored in the lockfile and return the name?  Just an idea!

**Comment by solvingj** [comment]
Hi @GordonJess , so, there's a related feature request here, and your input would be appreciated:

https://github.com/conan-io/conan/issues/7207

I will defer to @memsharded to decide whether or not to consider this feature for the future.  However, I will share my opinion, as someone who is working with lockfiles a lot. 

I think this feature would be exceptionally challenging and awkward to try to implement, and what could be delivered in the end would be extremely unreliable and unpredictable.  Here are a few complications:
- Users can pass multiple profiles
- Users can mix profiles and CLI args
- What the lockfile actually records is the "reconciled profile" (also labeled "Configuration" in `conan install` log). 

This will actually almost never match line-for-line or even string-for-string with a profile provided by the user. 

So, for these reasons, it seems un-reasonable to implement. 

With that said, the feature request I linked tries to provide exactly what you're describing but in a different way.  It could allow the user to actually include the `profile` and potentially even the `settings.yml` that were used to create the package.  Basically, anything a packager wishes. 

However, that is an extensive feature request, which requires server side changes. So rather than putting all my eggs in that basket, i'm also requesting an alternative feature which is more approachable. 

`conan lockfile extract profile`

The idea here is simply a first-class way to re-construct the profile from the lockfile so that it could be used in any number of workflows that people might come up with. I don't know if it addresses your actual situation at all (I suspect not actually), but please let me know either way.

**Comment by memsharded** [comment]
Closing as outdated, as 2.0 lockfiles do not contain profiles anymore
