### ISSUE TITLE
Hi, I am a little confused. Could you tell me the design principle of that version is prefer priority? Why does conan not consider the setting first? Thank you. @memsharded

### ISSUE THREAD

**Issue by gallencalade** [conan-io/conan#8616]
Hi, I am a little confused. Could you tell me the design principle of that version is prefer priority? Why does conan not consider the setting first? What headaches?

Expect your reply, Thank you.

_Originally posted by @gallencalade in https://github.com/conan-io/conan/issues/4407#issuecomment-792621944_

**Comment by danimtb** [comment]
Hi @gallencalade,

I might be missing some context from your question even after reading #4407. Could you please elaborate your case with an example that illustrates the issue? Thank you

**Comment by gallencalade** [comment]
I have a same problem which is commented by Johnnyxy #4407.

 For instance, We have a package PkgA/1.4.0 built with os=Linux, a package PkgA/1.5.0 with os=non-Linux like Neutrino, and have a PkgB with os=Linux and depending on PkgA/[>=1.0.0 <2.0.0]. When `conan create` compiles PkgB, the version ranges is resolved to PkgA1.5.0 and `conan` causes an error that missing prebuilt package for PkgA/1.5.0 with os=Linux.

In fact, different os and arch might not be deployed synchronously. So, I am confused

1. why conan can not solve PkgA/1.4.0 built with os=Linux?
2. What potential headache problem will happen?
3. Any way could let conan to solve PkgA/1.4.0?

Thank you.

**Comment by danimtb** [comment]
Thanks a lot for describing the issue with an example.

Yes, I understand the scenario, and unfortunately this intrinsic to the behavior of Conan based on how the graph is modeled.
Conan always resolves the recipe first and then the binaries. This is because the recipes define the binaries you need, so there is no possible way to know the binaries before resolving the recipes.

As quoted from the other issue:

> First, the "recipes" are resolved, and a dependency graph of recipes with exact versions is built. Then, the binary IDs of the graph are computed. Note that this is necessary, as the version of upstream dependencies can change the binary ID of packages.

So this is how Conan works, and you cannot know the package you need before having their recipe because Conan has to calculate first the package ID to pick the right package and that is impossible without the recipe.

Hope that helped to clarify the issue. Thank you

**Comment by gallencalade** [comment]
Well, thanks for your answer. 

Maybe we have to look for another solution.
