### ISSUE TITLE
[bug] Confusing error message with `conan lock create`

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#8675]
I ran `conan lock create . --pr myprofile`
and received the error message 
`ERROR: Conanfile does not exist in D:\path\to\folder`

However the correct invocation should have been
`conan lock create ./conanfile.py --pr myprofile`

I think the error message is very missleading. Especially, since the `conanfile.py` file is located in the mentioned folder and since the docs just mention
```
positional arguments:
  path                  Path to a conanfile
```
and in commands like `conan create` you always specify the folder, too.

**Comment by memsharded** [comment]
Hi @KerstinKeller 

Yes, you are right there is some inconsistency. It is because we decided to implement the ``conan lock`` command following some CLI design principles we plan to apply for Conan 2.0. For example, we will avoid all ambiguity, and commands will be more explicit. At the moment there is some "magic" that can select a conanfile.py or a conanfile.txt in the current folder, but this might sometimes cause some confusion and errors, so this is the reason we want to remove it, by making explicit always the full path to the conanfile.py, including the filename, not only the path.

I guess we can verify if the path is a folder or a file, lets try to add that check.
