### ISSUE TITLE
[question] Find*.cmake generated by the deploy generator has abs path to Conan cache

### ISSUE THREAD

**Issue by marcobergamin** [conan-io/conan#8683]
Dear all,

I am trying the deploy generator to copy my dependencies inside a specific deploy folder. The problem is that the Find*.cmake files of my libraries created inside my deploy folder have absolute paths to my cache libraries under .conan/data.
I was expecting paths relative to my deploy folder.
Is it supposed to work like this?

Thanks,
Marco Bergamin

**Comment by solvingj** [comment]
Yes, currently all built-in generators use full paths by design for a number of reasons.  The feature and concept of "deploying" a package outside of the Conan cache came MUCH later than the feature of Conan generators, and it was never designed (or re-designed) with the deployment case in mind. 

I completely understand and have experienced the desire to have generators which produce files with paths which are relative to some alternative root directory, or based on some layout. However, the only reasonable way to achieve this now is to write a custom generator that does this for you.   It's non-trivial, but it is definitely possible. 

Sorry I don't have a better suggestion at this time.

**Comment by marcobergamin** [comment]
Hello,
thanks for your reply. I'm new to Conan so I don't know its history and I'm still learning how to use it properly.
Regarding the paths issue, we have fixed it with a single small regex executed manually after the deployment, so it's not a big problem. 
In our case it would be a nice-to-have feature because we use Conan internally but we don't want or we can't force our clients to download extra dependencies from the internet for a number of reasons, no idea if our use case is common or not.
Thanks again for the clarification.
Marco

**Comment by solvingj** [comment]
I'm glad you found a strategy that works for you. We do have other users who deploy conan packages for use outside of Conan cache. You are the first case I recall hearing which needed to use the find* modules there, but I would bet there are others doing something similar.
