### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED when using the download function in conanfile.py

### ISSUE THREAD

**Issue by coding3d** [conan-io/conan#87]
Hi,

In a conanfile.py, I am using the "download( [url], [filename]) method, which I have seen in an example, in order to download the original source code of a package I am working on, from GitHub. On OS X El Capitan, I get the following error:

IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

I do not know if this is conan-related. Everything works fine on Windows and, on OS X, I am able to clone from GitHub over https. I have tried "resetting" my keychain on the Mac but that didn't work. Anyway, I thought to let you know, in case it is indeed something that must be corrected in the source code. Otherwise, I would greatly appreciate any advice you can give me about what to do.

**Comment by memsharded** [comment]
The download utility is a very thin wrapper around python Urllib FancyURLopener, so it seems just a python-ssl-osx issue. A quick search gave me http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error, it seems that the version of python you are running could be related. What  conan installation are you using? From source? The precompiled pkg package? If from source or pip, what exact version of python are you using? From one of the SO answers, it seems that could be fixed with the https://www.python.org/downloads version instead of the hombrew one.

**Comment by dimitrikourk** [comment]
Thanks for the info! I'll have a closer look at my setup. I am using the packaged edition of conan, v 0.5.0.
I don't have homebrew (I prefer macports) and my Python version is 2.7.11

**Comment by lasote** [comment]
What version of OpenSSL do you have?

**Comment by memsharded** [comment]
If using the packaged edition of conan, the ssl lib should be packaged by pyinstaller, I think. The python system version is not used either. 

@dimitrikourk if you could try the "pip install conan" version (make sure you remove the old pkg one), it could help to debug the issue.

**Comment by dimitrikourk** [comment]
That's the next thing I'll do; a bit of debugging to see if I catch something. I'll report back :)
In any case, in case it's useful in some way, my openssl version is the following:
OpenSSL 1.0.2e 3 Dec 2015

**Comment by dimitrikourk** [comment]
So, it has taken me a while, but I've gotten round to checking this out. It turns out that the pypi version of conan just works, so I did not even need to debug it. My version of OpenSSL is 1.0.2e 3 Dec 2015, as I've mentioned, while I've noticed that the conan pkg contains a libssl.1.0.0.dylib. Perhaps that's what is causing it? I am running OSX El Capitan.

**Comment by memsharded** [comment]
Yes, very likely. Probably, the machine we are using to create the installer has an old OpenSSL version, and upgrading would fix it. Maybe @lasote could try.

**Comment by dimitrikourk** [comment]
In the meantime I'm happy with the pypi version :+1:

**Comment by memsharded** [comment]
Hi @dimitrikourk,

This should be fixed by https://github.com/conan-io/conan/pull/173. It will be released in 0.8.

Cheers!

**Comment by dimitrikourk** [comment]
Great, thanks!
