### ISSUE TITLE
[question] conan copy replacement in conan 2.0

### ISSUE THREAD

**Issue by gsemet** [conan-io/conan#8730]
Hello,

I've came across the proposals for Conan 2.0 and I see in [016-package_immutability.md](https://github.com/conan-io/tribe/blob/main/design/016-package_immutability.md) that the `conan copy` is meant to be removed.

I use this command to perform a "promotion" of the package to its final landing site. Basically, the CI pushes to a specified user/channel (in Merge Requests it uploads by default to `pkg-name/1.2.3@testing/name-of-the-git-branch`, performs some tests, and then when all the campaign succeeded, `conan copy` them to `user/unstable` (or directly to `user/stable`).
This allows to have dedicated space where the package is in its final form (the versions are set, the content will not change), and at the very end, when everything is green is the CI, **promote** the package to its official release space so that other components can start consuming it.
It actually can promote several packages (that were all tested alltogether) at the same time to `stable`.

How would it behave in Conan 2.0 ? I really do not want to have to rebuild the package at the very end of the pipeline, I only want need to make my package visible as `pkg-name/1.2.3@user/stable`. I have a small tool that wraps conan to do that on an enterprise level (several dozens of projects that have to be fully tested before being green-lighted). I hope to be able to opensource this toolchain, it is my goal this year.

Thanks

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @gsemet 

The key is in the sentence:

> Another related concern about the package immutability and the proposed promotion mechanism (copying packages from one server repo to another) is the atomicity of the server promote operations.

You can also have a look at this page here https://docs.conan.io/en/latest/versioning/lockfiles/ci.html#repositories, it also highlights some ideas.

The key is to have a "testing" repository and a "stable" repository. Packages do not change, they are immutable. But based on the stage they can be put in one repository or the other. Instead of doing a ``conan copy``, the packages are copied from one server repo to the other. The goal is exactly the same, to avoid rebuilding from source if not necessary. But exactly for this reason this flow is more robust: the packages build can change based on user/channel. Not only because of the package_id that might change, but also the package recipes can have conditional logic based on the user/channel too. 

Does this clarify a bit?

**Comment by solvingj** [comment]
There is an "obvious-in-retrospect" but "unforeseen-in-early-design" consequence of using `channel` as an identifier of the "status" of a package (and the builds of that package).  When a package is first created, it is obviously in a "status" of `untested` (aka `unstable`). Then, once it's tested, the "status" of the package **changes** to `tested` (aka `stable` for example).  In theory, the rename makes sense...

However, in practice, conan dependency graphs are created from layers of package references.  Historically, it was taken as a fairly obvious thing to depend on the reference with `stable`, so for example:  `liba/1.0@solvingj/stable` 

At any non-trivial scale, as dependency graphs grow, it becomes impractical and hacky to identify and redirect all consumers which depend on `liba/1.0@solvingj/stable`  to depend on `liba/1.0@solvingj/testing` , just temporarily for a test, and then re-redirect them back to stable at the end, and then rename or copy the package at the same time. 

There's also a much bigger problem. That is, `package_id` calculation. In some `package_id` modes, a change in the `channel` will result in a new `package_id`.  So, in those cases, users will have to rebuild 100% of the time if the `channel` changes, or they will get "BINARY_MISSING" error, which completely defeats the purpose of the copy promotion to begin with. 
  
Finally, none of this is how promotion works with most other package managers work, so automation engineers were struggling to understand and creating tooling around the new `channel` abstraction.  To be honest, there are more reasons than just this. 

So, we started changing our thinking and the guidance around promotion to follow the high-level strategy of other package managers, which is to use multiple repositories, and for "promotion" to be a process of copying a package (or multiple packages) from one repository to another, and completely avoiding any change to the package reference, binaries, need for rebuild, etc. 

Here is how we test and promote pull-requests for Conan Center:
For each pull request, we use the Artifactory CLI to provision a temporary conan repo for that PR. 
Then, all packages generated in that PR are uploaded to the temporary repository. 
Once all packages are built and tested successfully, all the new packages and revisions are copied to the production repository. 

This is perhaps the most general and simple strategy we have to recommend at this time.

**Comment by gsemet** [comment]
Thanks for your answer.

I see that the user/channel concept loose flexibility. I have used it to have multiple rooms for testing, and indeed I have a companion class used in all package that is able to perform a dependency replacement to test a given library (so it replaces all « requires lib@user/stable » by « lib/<temp-version>@testing/git-branch-name » in all package. So that anyone can trigger a merge request that will test a given « flavor » of a package before merge. 

We often have several train of changes that needs to be tested on multiple projet before merge (often the « I want to see if I do not break anything in any of the project where my lib is used » use case, or the « I need to do a patch on the lib and the app at the same time » use case).

in Conan 2 I only get one shot for promotion to stable, I think I can get with it, I understand why you wanted to do that. 

Small idea: would it be possible to package to testing and then to stable around the same time, push to testing for test and save the content « to stable » to an archive that would be later uploaded? That would do the job for me. This is not technically a copy and the immutability feature is respected, and I almost have the same behavior

**Comment by memsharded** [comment]
> We often have several train of changes that needs to be tested on multiple projet before merge (often the « I want to see if I do not break anything in any of the project where my lib is used » use case, or the « I need to do a patch on the lib and the app at the same time » use case).

If you haven't yet, please have a look to https://docs.conan.io/en/latest/versioning/lockfiles/ci.html, this is more or less that idea: to check if something breaks downstream when there is a change in a package, without needing to put those packages in production repo yet.

> Small idea: would it be possible to package to testing and then to stable around the same time, push to testing for test and save the content « to stable » to an archive that would be later uploaded? That would do the job for me. This is not technically a copy and the immutability feature is respected, and I almost have the same behavior

That "saved for later" doesn't exist in the client side (at least in CI, it is difficult, there is the Conan cache, but shouldn't be use for ground-truth storage). But you can definitely use another repo. You might create both stable and testing channel, upload the testing one to the repo that you want (production if that is your current flow), and upload stable to another repo, lets call it "preproduction". When you are done testing, you can also promote the stable packages from "preproduction" to "production" with a copy. This might be a workaround that could work, but it still have a couple of issues: you are building packages twice which is costly, and when you are testing you are testing the other packages, not the ones that will be used later in production (and this is a big issue, because for some reason, some conditional logic in the recipes, the preproduction/stable packages might be broken while the testing ones work).

**Comment by technic** [comment]
> Here is how we test and promote pull-requests for Conan Center: For each pull request, we use the Artifactory CLI to provision a temporary conan repo for that PR. Then, all packages generated in that PR are uploaded to the temporary repository. Once all packages are built and tested successfully, all the new packages and revisions are copied to the production repository.

Do you have any guides or examples for about making such CI scripts?

**Comment by memsharded** [comment]
> Do you have any guides or examples for about making such CI scripts?

Not at this moment, sorry, we will work on docs and examples after 2.0 and we have time to work on documenting flows for CI.

**Comment by gsemet** [comment]
Hello. I am starting reworking more heavily on Conan and switching to Conan 2 so we went directly to multiple repository solution. So far so good, I think we can close this (old) discussion.

**Comment by memsharded** [comment]
Thanks for following up!
