### ISSUE TITLE
[bug] self.requires doesn't enforce keyword arguments

### ISSUE THREAD

**Issue by wadimklincov** [conan-io/conan#8742]
This is a very minor issue, but might be worth addressing anyway. I've tried to look for previously raised issues, but wasn't able to find one.

The issue is `self.requires` in the `requirements` method not enforcing keyword arguments and allowing users to pass anything as the `private` and `reference` arguments. Reading the documentation it's obvious what arguments `self.requires` and `self.build_requires` expect, but perhaps it should be more strict and check what is actually passed.

This issue appears when a user assumes `self.requires` works similarly to `SystemPackageTool.install` and passes 2 or 3 dependencies in one call. conan doesn't complain and the function converst both arguments to booleans, making the first dependency private and allowing it to be overriden. I imagine this can be very confusing, since it happens more or less silently.

My suggestion would be either enforcing keyword arguments or checking `private` and `override` and making sure they're correctly typed.

Thank you!

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu Focal 20.04
  * Compiler+version: gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
  * Conan version: 1.35.0
  * Python version: Python 3.8.5

### Steps to reproduce (Include if Applicable)

Run `conan install -if build .` with any conanfile, which calls `self.requires`, like the following:

  ```python
from conans import ConanFile

class ExampleConan(ConanFile):
    name = 'example'
    version = '0.1.0'
    def requirements(self):
        self.requires('nlohmann_json/3.9.1', 'rapidjson/1.1.0', 'flatc/1.12.0')
  ```

### Logs (Executed commands with output) (Include/Attach if Applicable)

Executing 

```
$ conan install -if build .

Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py (example/0.1.0): Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py (example/0.1.0): Generator txt created conanbuildinfo.txt
conanfile.py (example/0.1.0): Generated conaninfo.txt
conanfile.py (example/0.1.0): Generated graphinfo
```

The expected behavior might be something like the following, though I think a cleaner error message might be appreciated:

```
ERROR: conanfile.py (example/0.1.0): Error in requirements() method, line 9
        self.requires('nlohmann_json/3.9.1', 'rapidjson/1.1.0', 'flatc/1.12.0')
        TypeError: __call__() takes 2 positional arguments but 4 were given
```

**Comment by uilianries** [comment]
> This issue appears when a user assumes self.requires works similarly to SystemPackageTool.install and passes 2 or 3 dependencies in one call.

They are completely different. `SystemPackageTool.install` accepts variants for same package, because multi distro support. Both `self.requires()` and `self.build_requires()` only accept a single package reference because there is no name variation.

> Reading the documentation it's obvious what arguments self.requires and self.build_requires expect, but perhaps it should be more strict and check what is actually passed.

That's a prone error, and there are many methods which are following the same way. [Requirements](https://docs.conan.io/en/latest/reference/conanfile/methods.html#requirements) is well documented, anyone which read the documentation should not have problem.

Still, we can enforce adding an `assert isinstance()` (other methods are using it), but is the same situation for other all methods with optional parameters. I would say [type hints](https://www.python.org/dev/peps/pep-0484/) is the way, but requires Python 3.5 at least. Maybe for Conan 2.0

Thanks for reporting!
