### ISSUE TITLE
[question] what changed in settings api between 1.33.1 and 1.34.0?

### ISSUE THREAD

**Issue by fukanchik** [conan-io/conan#8754]
I have extended settings.yml, added the following:

    foo: bar

then in my conanfile.py I have:

    class LibraryConan(ConanFile):                                                                                                                                         
        settings = "os", "compiler", "build_type", "arch", "foo"
    ...
    def requirements(self):
        foo = self.settings.foo.value
       ... do something with foo
    def package_info(self):
        foo = self.settings.foo.value
       ... do something with foo

this works fine in conan version 1.33.1 but fails in 1.34.0:

    [GL] Exception: conan install . failed with code 1. b"ERROR: 'settings.foo' doesn't exist\n'settings' possible configurations are ['arch', 'arch_build', 'arch_target', 'build_type', 'compiler', 'cppstd', 'os', 'os_build', 'os_target']\n"

What changed in the API? What is the new API which I can use? I see nothing related in the changelog: https://docs.conan.io/en/1.35/changelog.html#feb-2021

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
Hello @fukanchik !

>  what changed in settings api between 1.33.1 and 1.34.0?

Nothing. Between 1.33.1 and 1.34.0 there were no changes for settings.yml. You can take a look on [changelog](https://docs.conan.io/en/latest/changelog.html) for further information.

> I have extended settings.yml, added the following:
>   foo: bar

I believe you wanted to say

    foo: ["bar"]

Otherwise, is incorrect and Conan will raise the follow error:

    ERROR: Error in resulting settings for package 'foo': Invalid setting 'bar' is not a valid 'settings.foo' value.

When a new version is updated, Conan client generates a new settings.yml. It doesn't replace if your current settings.yml is different, instead, `settings.yml.new` is generated. And, Conan client reports it with the follow message:

```
WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: settings.yml is locally modified, can't be updated
WARN: The new settings.yml has been stored in: /tmp/conan134/.conan/settings.yml.new
WARN: ****************************************
```

I can't reproduce your error, updating from 1.33.1 to 1.34.0, and using a custom setting. Conan works as spectated. 

I suggest you replacing your settings.yml by settings.yml.new or,
removing it and run `conan config init` to regenerate a new setting.yml. So, you can add your custom setting again.

You don't need to do it for each new Conan version, but your description sounds like your settings.yml is broken is relation to `foo`.

**Comment by fukanchik** [comment]
I'm sorry it's a mistake in the description. The actual value is

```
cat <<EOF>>$CONAN_USER_HOME/.conan/settings.yml
toolkit: [%TOOLKIT%.${DAY}]
EOF
```
so it's `foo:[bar]` indeed. I am trying to get a minimal example.

**Comment by fukanchik** [comment]
Ok, this was because settings.yml generated by newer version of conan does not have newline in the end and I am just appending to it..

**Comment by memsharded** [comment]
That is curious, I am not sure what is happening. In code, the settings.yml still has a newline in the end:

```python
    cppstd: [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20]  # Deprecated, use compiler.cppstd
    """))
```
It is true that it lost a blank line, but the final newline seems to be there. 
In any case if you managed to fix it, maybe not worth it, so just let us know if something else happens, thanks!

**Comment by fukanchik** [comment]
Yes, as you can see I am appending an extra line to the file, and in 1.34.0 it was becoming part of the comment:

        cppstd: [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20]  # Deprecated, use compiler.cppstdtoolkit: ["metastable.20210331"]

the fix was as simple as adding a newline in the beginning of my heredoc command.
