### ISSUE TITLE
[bug] missing exports_sources after first installation of prebuilt packages

### ISSUE THREAD

**Issue by thorsten-klein** [conan-io/conan#8756]
If a conan package is installed on the first time and it is available as prebuilt package, then the exports_sources directory is not available. If in a next run another revision of the package needs to be built, then the build fails because of the missing exports_sources. 

This is critical for CI jobs, since the conan behavior is depending on the fact, which package revision has been installed first.
We can solve via workarounds (e.g. remove whole conan cache in CI), but it is not scaling for long term.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: -
  * Conan version: 1.34.1
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)

Minimal example
conanfile.py
```
from conans import ConanFile
import os

class ConanPackage(ConanFile):
    name = "exports_sources_bug"
    version = "1.0.0"
    settings = "os", "compiler", "build_type", "arch"
    exports_sources =   ["exported_source.txt"]
    
    def source(self): 
        pass
        
    def build(self):
        self.run("cat %s" % self.exports_sources[0])

    def package_info(self):
        pass

```

run: 
```
conan create . demo/demo
conan upload exports_sources_bug/1.0.0@demo/demo --force --all
```

remove the conan cache:
```
rm -rf ~/.conan/data/exports_sources_bug/1.0.0/demo/demo
```

install the package (prebuilt revision):
```
conan install exports_sources_bug/1.0.0@demo/demo
```

install the package (prebuilt revision):
```
conan install exports_sources_bug/1.0.0@demo/demo -s build_type=Debug
```

This fails with:
```
ERROR: Missing prebuilt package for 'exports_sources_bug/1.0.0@demo/demo'
Try to build from sources with '--build=exports_sources_bug'
Use 'conan search <reference> --table table.html'
Or read 'http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

PS: Even the `-u` flag does not solve (even `conan install -u exports_sources_bug/1.0.0@demo/demo -s build_type=Debug` fails).

To fix the issue I manually need to download the package
```
conan download --recipe exports_sources_bug/1.0.0@demo/demo
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
see above

**Comment by thorsten-klein** [comment]
There are 2 possible solutions IMHO:

1. Preferred solution: download export_sources always, even if a prebuilt revision is installed (since the exports_sources are closely related to the export (conanfile.py)

2.  Download export_sources if it is needed for installation of a new revision --> instead of throwing current error message, first try to download exports_sources. Only if the download fails, exit with current error message.

**Comment by solvingj** [comment]
First, the easiest way to bypass this error is to pass the `--build=missing` flag to your build command.  So, specifically:

`conan install exports_sources_bug/1.0.0@demo/demo -s build_type=Debug --build=missing`

https://docs.conan.io/en/latest/reference/commands/consumer/install.html#build-options

Second, there seems to be one major point of confusion with how you've described the issue, so I will try to help clarify for future reference. 

In all cases where you mention `revision`, I believe you mean to say `package_id`, which corresponds to a unique build configuration (such as `-s build_type=Debug`).  A `revision` denotes a unique set of sources, often this would correspond to a unique GIT commit.  It's an easy mistake to make, because both `revisions` and `package_ids` are equal length hashes, and also, their appearance in the output of some `conan ...` commands can be confusing. We hope to make the output better in Conan 2.0. 

If you did in-fact mean `revision`, then there's another issue. 

So, please let me know if passing `--build=missing` solves your first issue, and also if my clarification made sense to you.

**Comment by thorsten-klein** [comment]
Hello @solvingj , yes you are right. `--build=missing` of course solves my described situation.
And yes, just replace revision by package_id, I mixed them up.

Actually I wanted to reproduce another error message (which our CI sometimes runs into) :
```
ERROR: The 'package/1.2.3@demo/demo' package has 'exports_sources' but sources not found in local cache.
```

When I tried to do this, I just saw that exports_sources are missing and I copied the error message without completely reading it. 

I will open another ticket as soon as I am able to reproduce my actual issue.

This Issue can be closed
