### ISSUE TITLE
resolving requirements/package-id's accross major-version numbers

### ISSUE THREAD

**Issue by walterschneider** [conan-io/conan#8764]
We have follwing pakages/dependencies:

**my_pkgbase**
```python
class Conan_pkgbase(ConanFile):

    name ="my_pkgbase"

    def requirements(self):
        pass
```

**my_pkgtools**
```python
class Conan_tools(ConanFile):

    name ="my_pkgtools"

    def requirements(self):
        self.requires("my_pkgbase/[>=2.0.0 <4.0.0]")
```

**my_pkgapp**
```python
class Conan_app(ConanFile):

    name ="my_pkgapp"

    def requirements(self):
        self.requires("my_pkgbase/2.0.0")
        self.requires("my_pkgtools/1.0.0")
```

build
* my_pkgbase/2.0.0
* my_pkgtools/1.0.0

my_pkgtools gets the requirement to my_pkgbase/2.Y.Z:
```
[requires]
    my_pkgbase/2.Y.Z
```

The dependencies for my_pkgapp are resolved (using conan install) fine.

If now a new major-release of my_pkgbase is released, my_pkgapp can not be resolved because  my_pkgtools requests my_pkgbase/2.Y.Z (different package-id).

I've set `self.info.requires["my_pkgbase"].unrelated_mode()` in my_pkgtools to get rid of this requires-field,
version-range checks are still working.

Why is this requirement resolved to the major-version number even if the range specified would allow other majors?
Isn't is a valid use-case to allow ranges crossing major-releases?

Thank you!

**Comment by memsharded** [comment]
Hi @walterschneider 

Conan dependency resolution is not fully SAT solving the possible version ranges, because that would basically be an intractable problem in practice. So the algorithm is greedy, and it always gives priority to the user-consumer package. In this case:

```python
class Conan_app(ConanFile):

    name ="my_pkgapp"

    def requirements(self):
        self.requires("my_pkgbase/2.0.0")
        self.requires("my_pkgtools/1.0.0")
```
Is defining exactly what versions to use upstream. Those values will propagate upstream overriding existing definitions. The ``my_pkgtools`` will be forced to require ``my_pkgbase/2.0.0``.

That is the dependency resolution phase, with happens first, and it is totally decoupled from the binary evaluation. Once all the versions have been resolved, the binary compatibility and the ``package_id`` is computed. As ``my_pkgtools`` was build previously with a more modern ``my_pkgbase`` version, and the package_id mode was selected to be one, now that it is being forced to use another upstream version, it knows that it needs to be built to achieve the correct binary compatibility with it. Relaxing the ``package_id`` mode will achieve not rebuilding but might be risky and fail at link time or run time if there is ABI incompatibility.

Please let me know if this clarifies a bit how dependencies and binaries are resolved. Thanks!

**Comment by AbrilRBS** [comment]
Closing as solved, please feel free to reopen should you still have any questions, thanks!
