### ISSUE TITLE
Often error running conan test_package

### ISSUE THREAD

**Issue by KindDragon** [conan-io/conan#877]
We get this error often in random places:
```
opencv/3.1.1@******/stable: WARN: Forced build from source
ERROR: [Error 145] The directory is not empty: 'C:\\Users\\WinBuilder\\.conan\\data\\opencv\\3.1.1\\merlin-ext\\stable\\build\\22357e08bed3f975c745816eb96079b8fc475506\\opencv\\.git\\logs\\refs\\remotes'
```

```
grpc/0.15.0@******/stable: WARN: Forced build from source
ERROR: [Error 145] The directory is not empty: u'C:/.conan\\f8jip9\\1\\grpc\\tools\\dockerfile'
```

We run `conan test_package --build=package_name --build=missing`
Please help

**Comment by memsharded** [comment]
Quick question: are you running such ``conan test_package`` concurrently in CI server or something similar?

**Comment by KindDragon** [comment]
No, it run in sequence on CI agent

**Comment by memsharded** [comment]
Ok, will have a look when possible, seems the typical problematic, being random and difficult to reproduce... I can see the first example is from ".git" files, which sometimes are kept locked by windows for some windows reason. Does it usually fail in such ".git" folders?

**Comment by memsharded** [comment]
This issue is a duplicated to https://github.com/conan-io/conan/issues/856

Underlying issue is the same: inability of Windows to remove a certain folder, Please follow conversation in: https://github.com/conan-io/conan/issues/856, thanks!

**Comment by KindDragon** [comment]
No, today it fail with this error:
```
grpc/0.15.0@merlin-ext/stable: WARN: Forced build from source
ERROR: [Error 145] The directory is not empty: u'C:/.conan\\2y2jxk\\1\\grpc\\third_party\\protobuf\\objectivec\\Tests\\CocoaPods\\iOSCocoaPodsTester\\iOSCocoaPodsTester.xcodeproj'

Couldn't remove folder, might be busy or open
```

**Comment by memsharded** [comment]
Why different? It is the same error as above, 145 directory not empty, isn't it? It happens when conan tries to remove one folder for a clean build or package, and it fails because Windows keeps some handle, or file open for unknown reasons (sometimes, if there is some other process inspecting the files, like AV)

**Comment by KindDragon** [comment]
"No" was answer to "Does it usually fail in such ".git" folders?" :)

**Comment by KindDragon** [comment]
> It happens when conan tries to remove one folder for a clean build or package, and it fails because Windows keeps some handle, or file open for unknown reasons (sometimes, if there is some other process inspecting the files, like AV)

I understand it, but we doesn't have AV and Proccess Explorer doesn't show anything. Maybe conan start deleting something before building finished?

**Comment by memsharded** [comment]
Nop, it could seem so, but conan is running in python, in a single thread, nothing concurrent at all. It is the OS that leaves some file handles open (maybe file caching in RAM before writing to disk), and seems the operations have finished, but actually when you try a subsequent action, it fails. It is not the first time it happens, sometimes (always Win), a build of an .exe has finished, you launch it, and it happens to launch the previous version of the .exe, because for some reason, it wasn't overwritten yet (even if the compile/build process finished). Those tests are usually fixed with one ``time.sleep(1) second``. For removal, it is more complicated, sometimes the handles are just not released by Windows, who knows why.

Still a matter of active investigation, thanks for the feedback!
