### ISSUE TITLE
[bug] python_requires breaks module self-identity

### ISSUE THREAD

**Issue by nikita240** [conan-io/conan#8770]
When using `python_requires` to obtain a module reference, conan prepends an id to the underlying module name. This breaks the fundamental operation `sys.modules[__name__]` that allows a module to self-identify and pass along a reference to itself. 

Given a conan recipe that exports a python tool such as:

```python
# ./conanfile.py
from conans import ConanFile
import sometool

class SometoolConan(ConanFile):
    name = "sometool"
    version = "0.1"
    exports = "sometool.py"
```
```python
# ./sometool.py
import sys

def what_module_am_i():
    return sys.modules[__name__]
```

And a test package recipe:

```python
from conans import ConanFile

class SometoolTestConan(ConanFile):
    python_requires = "sometool/[>0.0]"

    settings = "os", "compiler", "build_type", "arch"

    def build(self):
        sometool = self.python_requires["sometool"].module.sometool
        print(sometool.what_module_am_i())

    def test(self):
        return
```

Running `conan create .` will always result in a KeyError for `sys.modules[__name__]`:

```log
ERROR: sometool/0.1 (test package): Error in build() method, line 10
        print(sometool.what_module_am_i())
        KeyError: 'sometool'
```

Dumping out `sys.modules.keys()` will show that the module is actually keyed under `7b47708f-9770-11eb-9f8e-590e9d5af3a0.sometool`, however the module itself has no methodology for ever figuring that out.

### Environment Details
  * Operating System+version: Kubuntu 20.10
  * Compiler+version: N/A
  * Conan version: 1.33.0
  * Python version: 3.8.6

### Steps to reproduce
I created a [demo repo](https://github.com/Nikita240/conan-python-requires).
```bash
git clone git@github.com:Nikita240/conan-python-requires.git && cd conan-python-requires
conan create .

**Comment by memsharded** [comment]
Hi @Nikita240 

I don't think this is a bug, but necessary behavior. As there can be multiple Conan recipes with the same ``conanfile.py`` and multiple other files like ``sometool.py``, in different cache folders, with completely different implementations, and without a meaningful, unique module identifier, it is necessary to address them with something unique, otherwise they conflict with each other in the python interpreter, overwriting behavior and causing lots of issues and unexpected behavior.

The thing is that Conan recipes are not fully regular python modules, as they are fully dynamic and with a reference system that is not compatible with the standard Python interpreter one. I don't think this can be changed without massively breaking.

**Comment by nikita240** [comment]
That all makes sense.

I've been pounding my head against the wall trying to find any way to obtain a self-reference without using `__name__`, but no luck so far. 

I do feel that this can break some workflows though so I think some, at least "mildly-hacky", workaround should be invented. I'll try to come up with something.

**Comment by memsharded** [comment]
It would be good to know what problem you are trying to solve. Because the typical functionality you can put in ``sometool.py`` works, it can be used in consumers, etc. Why are you trying to obtain a self reference in such module?

**Comment by nikita240** [comment]
Here is the particular problem I am faced with. I am integrating `sometool.py` that has config files in each directory that look like the following:

```python
# ./test_package/config.py

def setup(tool):
    tool.add_file("helloworld.c")
```
`sometool.py` itself stores all of it's state in globals, sort of like a module-singleton pattern. It finds this `config.py`, executes it and invokes the `setup()` method by passing in a reference to itself for `setup.py()` to modify. 

```python
# ./sometool.py
import sys
from importlib.machinery import SourceFileLoader, FileFinder, SOURCE_SUFFIXES
from importlib.util import module_from_spec

files_to_compile = []

def add_file(file):
    files_to_compile.append(file)

def configure(root_folder):
    finder = FileFinder(root_folder, (SourceFileLoader, SOURCE_SUFFIXES))
    spec = finder.find_spec("config")
    config_module = module_from_spec(spec)
    spec.loader.exec_module(config_module)

    config_module.setup(sys.modules[__name__])

def build():
    for file in files_to_compile:
        print("building %s" % file)
```

And the appropriate test package recipe:

```python
# ./test_package/conanfile.py
from conans import ConanFile

class SometoolTestConan(ConanFile):
    python_requires = "sometool/[>0.0]"

    settings = "os", "compiler", "build_type", "arch"

    def build(self):
        sometool = self.python_requires["sometool"].module.sometool
        sometool.configure(self.recipe_folder)
        sometool.build()

    def test(self):
        return
```

I added the mocked up setup to the demo repo on branch [config](https://github.com/Nikita240/conan-python-requires/tree/config):
```bash
git clone --branch config git@github.com:Nikita240/conan-python-requires.git && conan-python-requires
conan create .
```

**Comment by nikita240** [comment]
Here is the workaround I came up with. It requires modifying `sometool.py` but it works quite nicely.

The idea is to encapsulate the entire global state of `sometool.py` into a class by binding `globals()` to the internal data structure of said class.

```python
# ./sometool.py
from importlib.machinery import SourceFileLoader, FileFinder, SOURCE_SUFFIXES
from importlib.util import module_from_spec

# Class to encapsulate the whole module
class SomeTool():
    def __init__(self):
        self.__dict__ = globals()

this = SomeTool() # Bind the whole module to a variable "this"

files_to_compile = []

def add_file(file):
    files_to_compile.append(file)

def configure(root_folder):
    finder = FileFinder(root_folder, (SourceFileLoader, SOURCE_SUFFIXES))
    spec = finder.find_spec("config")
    config_module = module_from_spec(spec)
    spec.loader.exec_module(config_module)

    config_module.setup(this) # Pass in a reference to this module

def build():
    for file in files_to_compile:
        print("building %s" % file)
```

**Comment by memsharded** [comment]
Hi @Nikita240 

Thanks for the detailed explanation. While I more or less understand what is happening and what is being implemented, I still miss the ultimate goal of this:
- Is it the purpose to have a global, common state for all packages that use this ``python-requires``? Kind of a way to skip the each ``python_require`` is "private" to its consumer?
- What happens with different versions of ``python_requires``? One of the advantages is that different packages can require different versions the same ``python_requires``, without breaking. This is a great way to move forward, in case a python_require require some breaking changes to the consumers, that typically cannot be done at once (it is impossible to modify all the recipes of a big project to account for some python_require change). But this will completely violate this, and that shared state will not be versioned by definition. (your implemented workaround seems to correctly achieve what you want, from a python point of view, nice job)
- What do you store in that global state? Have you considered other mechanisms for storing this state, as environment variables, configuration files, or something system-level like?

Thanks for the feedback!

**Comment by nikita240** [comment]
> What happens with different versions of python_requires? 

This approach still isolates the state to different versions of the `python_requires` package. Because `python_requires` will append an id to the imported module name, each import with a different id will re-import that module and hence create another global state object. 

> Is it the purpose to have a global, common state for all packages that use this python-requires? Kind of a way to skip the each python_require is "private" to its consumer?

You bring up a very good point that I failed to consider. I need to test how this will behave when the same version of this `python_requires` package is used to build multiple packages from sources within the same `conan` invocation.

I foresee a collision if the following two conditions are met: 

1. The same python process calls `ConanFile::build()` on two different conanfile recipes (building two packages).
2. The "id" that `python_requires` prepends to the imported module name is the same.

> Have you considered other mechanisms for storing this state, as environment variables, configuration files, or something system-level like?

Yes, this is clearly sub-optimal, but I'd like to integrate this tool with as little refactoring of it's internal workings as I can get away with. It would be more time-effective to simply switch to another build tool than rewrite it. 

On the note of environment variables though, I was under the impression that storing your build system state in environment variables is a bad idea because it opens up a lot of ways you can unintentionally break your builds with your local environment state. From my reading and examining of a lot of conan examples, one of the patterns I picked up on is that people typically aim to store all of the build state as a file in the build folder. I assumed this was to ensure repeatability of builds. Am I misguided and is using environment variables perfectly acceptable?

On a side note, I'd like to sincerely thank you for developing conan. It is a very very impressive tool.

**Comment by memsharded** [comment]
> You bring up a very good point that I failed to consider. I need to test how this will behave when the same version of this python_requires package is used to build multiple packages from sources within the same conan invocation.

Yes, please be aware that every python_requires obtains a unique-id, per package reference, that is, if there are these packages, they will get different unique ids:
- sometool/0.1 => `id1.conanfile.py`, `id1.sometool.py`
- sometool/0.2 => `id2.conanfile.py`, `id2.sometool.py`
- othertool/0.1 => `id3.conanfile.py`, `id3.sometool.py`

but if multiple packages do have a ``python_requires`` to the same version, like ``sometool/0.1``, the global state of that python module will be shared among all consumers of that python_requires. The id is unique, it is a UUID, so there is no risk of collision at all. But sharing the global state might potentially be an issue. Module globals like ``files_to_compile = []`` might totally be an issue. ``python_requires`` feature was designed as a way to reuse functionality, but not state. 

Also, the system is designed to be very self-contained and encapsulated. Once a recipe is "exported" or "create", it basically contains all the information to build the package, and the only inputs are configuration, like the compiler version or the architecture, but no functionality definition. In the system you are implementing it seems that part of the build functionality in the ``config`` is not self-contained in the recipes, and the system is unable to create packages without this. Without knowing the details of that tool, it is difficult to know if it makes sense, but one of the things that I would try is to include that ``config`` too in the packages, in the same way the ``sometool.py`` is packaged. 

In any case, yes, please, you need to check twice what happens in the first of your cases of collisions.

>On the note of environment variables though, I was under the impression that storing your build system state in environment variables is a bad idea because it opens up a lot of ways you can unintentionally break your builds with your local environment state. From my reading and examining of a lot of conan examples, one of the patterns I picked up on is that people typically aim to store all of the build state as a file in the build folder. I assumed this was to ensure repeatability of builds. Am I misguided and is using environment variables perfectly acceptable?

Yes, you are right, not really recommended, but if you fully managed the tool, it might be less problematic than the current python modules approach, because you can control them (and name them after packages or whatever to avoid conflicts). I was trying to think of other alternatives that were at least fully under your control (the python module system is not).

> On a side note, I'd like to sincerely thank you for developing conan. It is a very very impressive tool.

Thanks for your kind words! Really happy that Conan can be useful to you :)

**Comment by memsharded** [comment]
Closing this ticket as stale, but don't hesitate to open new ones as necessary, thanks!
