### ISSUE TITLE
conan server with two network IPs

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#882]
Hi,

is it possible to run conan server on two different hostnames or IPs (behind nginx)? 
I need to serve packages from one server on two different IPs/hostnames. Settings up the nginx is not the problem, but conan seems to use the host_name variable to create URLs.

Background:
I run a conan server behind a nginx server in my corporate network. The server has two IPs, one for internal communication (build servers, Jenkins master and so on) and one for the developers. 
currently, I run the conan server on the developer IP, wich works fine for local development. 
However, for the build servers, I have very long upload and download times (Corporate proxy hell). 
When I change to the intern IP, I have downloads and uploads for the build servers fast as hell, but no access for the developers. 

Best,
Claas

**Comment by memsharded** [comment]
I am not sure what could be happening, at least if the issue was symmetrical: changing IP would render the other unusable, but no, in one case the developers have no access, and in the other the transfers are very slow.

Maybe if I give some insights about the conan server structure, it could help to setup something:

- Conan API is divided in two main components, the business logic in the ``<url>/conans`` endpoint, and the file transfers in the ``<url>/files`` endpoint.
- The logic ``conans`` endpoint generates upload/download signed URLs for doing the effective transfers. These signed URLs, in the case of the local conan_server, will contain the ``<url>/files`` pattern.
- The ``host_name: localhost`` configuration in the ``server.conf`` file is used for defining the base hostname for those signed URLs
- You might want to have a look at the point where URLs for transfers are generated: https://github.com/conan-io/conan/blob/develop/conans/server/store/file_manager.py#L110, and you might hack the base_url for the transfers here: https://github.com/conan-io/conan/blob/develop/conans/server/store/disk_adapter.py#L76

If you need more information or discussion in private about your setup (we have an experimental slack channel too, you might find useful), please write us an email. Thanks!

**Comment by lasote** [comment]
It sounds to me like a DNS and network management problem.
If conan returns some urls with a `host_name` domain (let's say myconandomain.internal.com), maybe your CI DNS should resolve to the internal IP, in the other side, the developers DNS should resolve to the "public" ip. You can run conan using gunicorn and specify multiple IP interfaces with the `-b` option.

**Comment by claasd** [comment]
Yes , DNS is one solution. Another would be to modify the hosts file of the builds servers. 

Running gunicorn on different IPs does not solve the problem, as gunicorn is only listening on localhost and nginx is used as a proxy. The signed_urls are causing the problem, as they simply use the `host_name` variable. If there would be a way to give the `host_name` to conan via nginx, this would be a solution, or if leaving the `host_name` blank would result in conan automatically choosing the hostname from the logic conans url, but this may cause problems again with using conan behind a proxy. 

However, I too think this is not a conan problem, but one of our corporate network.
You can close this issue, I will try to solve this issue using DNS or hosts entries.

Thanks!

**Comment by memsharded** [comment]
Ok, lets close it, good luck with it. But please do not hesitate to open it again or ask for help if necessary. Thanks!

**Comment by claasd** [comment]
Just for information: artifactory supports this out of the box without any configuration.

**Comment by memsharded** [comment]
You mean, Artifactory as conan remote, or Artifactory in the general case? Have you already tried it with conan instead of using conan_server?

**Comment by claasd** [comment]
We are evaluating artifactory as remote for everything, including conan.

We installed artifactory on a server with two IPs. I use this artifactory as remote for conan instead of the conan server. It works without configuration fast on both IPs.
