### ISSUE TITLE
[question] using self.copy() outside of package()

### ISSUE THREAD

**Issue by Jochen0x90h** [conan-io/conan#8836]
Hi!
Is it possible to use self.copy() outside of def package(self) in the conanfile.py? For example self.copy("*.so*", "lib", "lib", symlinks = True). Is it even possible to write an own python script, import the conanfile.py, set the package folder and then call copy() so that all dependent libraries are copied to a folder of own choosing? If that's not possible, maybe you could point me to the implementation of self.copy() so that maybe it could be done directly

Thanks!

**Comment by uilianries** [comment]
Hi @Jochen0x90h 

> Is it possible to use self.copy() outside of def package(self) in the conanfile.py?

No, because `self.copy` is designed only to copy artifacts to the package folder. More info [here](
https://docs.conan.io/en/latest/reference/conanfile/methods.htm#package)

> Is it even possible to write an own python script, import the conanfile.py, set the package folder and then call copy() so that all dependent libraries are copied to a folder of own choosing? 

What do you mean by your own python script and import conanfile.py? Do you want to extend a recipe, so maybe you are looking for [python requires](https://docs.conan.io/en/latest/extending/python_requires.html). Or, maybe you want to copy all artifacts to your build folder, before building, so you are looking for [imports](https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports)

Please, try to give more details about your problem, if I didn't answer your question.

**Comment by Jochen0x90h** [comment]
Hi @uilianries,

Thanks for the hint with imports, it "magically" does what I want: If I open a CMake based project in CLion then I check if conanbuildinfo.cmake is already present and if not I call conan install conanfile.py ... which now also copies the dependent shared libs into my lib folder (via imports)

**Comment by memsharded** [comment]
``copy()`` is now a free function ``from conan.tools.files import copy``, that can be used anywhere in a recipe, closing this ticket.
