### ISSUE TITLE
[feature] Log User for Remote in Verbose Mode

### ISSUE THREAD

**Issue by p0fi** [conan-io/conan#8853]
When trying to download a package from a repo which hides existence of unauthorized resources (like Artifactory) trying to download a package results in an error that the package could not be found on the repo. Even when enabling the most verbose logging mode its nowhere written which user is used to get the package.

```
package/1.0.2@repo/stable: Trying with 'gitlab'...
DEBUG :rest_client_common.py[160]: REST: ping: https://gitlab.com/api/v4/packages/conan/v1/ping [2021-04-22 22:52:03,502]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: [] [2021-04-22 22:52:03,644]
DEBUG :rest_client_common.py[188]: REST: get: https://gitlab.com/api/v4/packages/conan/v1/conans/package/1.0.2/repo/stable/download_urls [2021-04-22 22:52:03,645]
DEBUG :rest_client_common.py[30]: REST ERROR: <class 'conans.errors.NotFoundException'> [2021-04-22 22:52:03,703]
ERROR: Unable to find 'package/1.0.2@repo/stable' in remotes
```

It would be a massive help if the user used for the remote could be found in those log lines!

It would may be even more helpful if the user used for the remote is logged in the general output not only in verbose mode. It could be something like 

```
package/1.0.2@repo/stable: Trying with 'anonymus' @ 'gitlab'...
```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment]
Hi @p0fi,
Thanks a lot for the suggestion, we'll try to add that information somewhere in the logs for the next release.

**Comment by memsharded** [comment]
I have added a look trying to implement this, but it seems way harder than it looks at first sight. It happens that the user is not available at that point in time at all (at ``package/1.0.2@repo/stable: Trying with 'gitlab'``), it is read much later at the "Rest" layer, so it would require either reading it again from the DB just for displaying, or quite a few changes to the architecture of the app. 

Furthermore, it is also not straightforward to add it at the Rest layer (for the ``DEBUG :`` messages), because that level only gets the token used, but not the username. I have tried to do it, but it was too many changes:

```
(conan36) λ git diff --stat
 conans/client/rest/auth_manager.py       |  5 +----
 conans/client/rest/rest_client.py        | 19 ++++++++++---------
 conans/client/rest/rest_client_common.py |  7 ++++---
 conans/client/rest/rest_client_v2.py     | 10 ++++++----
 4 files changed, 21 insertions(+), 20 deletions(-)
```
And not counting tests that could need to be fixed.
So it seems a lot of change, with some non-negligible risk to break something, for something that only shows in the log in debug mode, and for an information that can be displayed very easily with a ``conan user`` command.

So I think it is better not to implement this feature now. While we refactor the internals of the Rest layers for Conan 2.0, we will try to display the user if possible.

**Comment by p0fi** [comment]
Well this sometimes happens in software, something looks trivial but turns out its a major thing 🤓 

Thanks for letting me know! 

I know that this information can easily be obtained by the `conan user` command. I ran in some problems that took me over an hour to even think that something with the user could be wrong. To read which user is used for a given remote would have saved me a lot of trouble I think. 

It would be cool if this makes it into Conan 2.0 🎉

**Comment by memsharded** [comment]
I have tried to do a quick implementation of this for 2.0, but it turned out too dirty. As it is getting very close and this doesn't seem a high priority, I am moving this to 2.X.

I have been checking this, and the necessary refactors for this are:
- A central point ``RemotesRegistry`` access that hides the user login access and update, and that can be used by everyone without knowing about ``LocalDB`` and ``Remotes`` separately. ``LocalDB`` becomes an internal implementation detail initially (then it could be replaced for a text file if we wanted to, for simplicity, instead of using a full DB)
- AuthApiManager uses the new ``RemotesRegistry`` 
- The RemotesAPI uses the new ``RemotesRegistry``
- The ``Remote`` model can be extended to carry the ``user`` information.
- Finally, the ``ConanProxy`` will be able to display the ``user`` information while downloading.

**Comment by memsharded** [comment]
This has been implemented in https://github.com/conan-io/conan/pull/17517 for next Conan 2.12
