### ISSUE TITLE
[question] conan install/inspect not working after conan server migration

### ISSUE THREAD

**Issue by jonliubj** [conan-io/conan#8874]
Hi,

I am having some issues with a conan server migration. I have copied the conan data directory to the new server, package search works but inspect or install fails on the existing packages. A new package on the new server all works as expected, upload, search, inspect, and install.

The old server is using a venv and the data is on a NAS share, inherited so don't know much about the history but it is time expiring for a couple things so needs to be moved. The new server is not using a venv and a local drive for the conan files.

I have tried a couple different versions v1.9.2 and v1.9.3 but neither seem to work for me.

Search from the client:
```
DEBUG :tracer.py      [157]: CONAN_API: search_recipes(remote_name=conan1,case_sensitive=False) [2021-04-26 09:32:00,871]
DEBUG :rest_client_common.py[160]: REST: ping: http://conan1:9300/v1/ping [2021-04-26 09:32:00,880]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'revisions', 'revisions'] [2021-04-26 09:32:00,894]
DEBUG :rest_client_common.py[188]: REST: get: http://conan1:9300/v1/conans/search?q=jsoncpp%2F%2A [2021-04-26 09:32:00,894]
DEBUG :conan_api.py   [176]: INIT: Using config '/home/user/.conan/conan.conf' [2021-04-26 09:32:02,580]
DEBUG :tracer.py      [157]: CONAN_API: get_remote_by_name() [2021-04-26 09:32:02,587]
Existing package recipes:

jsoncpp/1.8.4@3rdparty/stable
```

Inspect from the client:
```
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'revisions', 'revisions'] [2021-04-22 09:28:17,570]
DEBUG :rest_client_common.py[188]: REST: get: http://conan1:9300/v1/conans/jsoncpp/1.8.4/3rdparty/stable/digest [2021-04-22 09:28:17,579]
DEBUG :rest_client_common.py[30]: REST ERROR: <class 'conans.errors.NotFoundException'> [2021-04-22 09:28:17,586]
ERROR: Recipe not found: 'jsoncpp/1.8.4@3rdparty/stable'
```
From the server:
```
Apr 26 09:32:00 conan1 gunicorn[1659]: [2021-04-26 09:32:00 -0700] [1662] [DEBUG] GET /v1/ping
Apr 26 09:32:00 conan1 gunicorn[1659]: [2021-04-26 09:32:00 -0700] [1662] [DEBUG] GET /v1/conans/search
Apr 22 09:28:17 conan1 gunicorn[4208]: [2021-04-22 09:28:17 -0700] [4213] [DEBUG] GET /v1/ping
Apr 22 09:28:17 conan1 gunicorn[4208]: [2021-04-22 09:28:17 -0700] [4213] [DEBUG] GET /v1/conans/jsoncpp/1.8.4/3rdparty/stable/digest
```

Thanks

**Comment by memsharded** [comment]
Hi @jonliubj 

From which version, to which version are you trying to upgrade?

Because in 1.10 there was a major layout change to accommodate for package revisions. The server upgrade will detect in an run an automatic migration, but it needs to be a server upgrade (that can detect the previous version and the current new one, and act accordingly).

In any case, I would strongly suggest to move to the free ArtifactoryCE (https://conan.io/downloads.html), it is completely free, and way more powerful, fast and stable than the conan_server, and it includes some other great features, like web UI, generic repos (to host any file there), better permission management, virtual and remote repos...

**Comment by jonliubj** [comment]
I ran a pip upgrade in the venv but conan is not in the module list so not sure the conans.server.server bits got touched. Is there an easy way to check that version? It did uppgrade gunicorn to 20.1.0, started the server, let it idle for a couple minutes while I checked the functionality, then stopped it and copied the files to the new server but the new server still has the same issue.

We are trying to move to v1.9.3, or latest but would be easy enough to grab a matching version to the old server, get it running and then do the upgrade.

**Comment by memsharded** [comment]
Hi @jonliubj 

The conan_server is packaged with the client. So ``conan --version`` should give you the server version too.

The problem is that the files cannot be moved after it has started, they won't be migrated. They should be there to be migrated when the version is checked while the server starts. In any case, the migration of revisions is with 1.10, so this shouldn't be the issue either. In order to manually force migrations, you could change the ``version.txt`` file inside your server folder, to an older version than the current one. That is the file that stores the "current" version, and used for comparison. If it is older than the current Conan running, then the matching migrations will run. Same mechanism is run in the client side if you need it too.

You are trying to move to v1.9.3, but from which version are you upgrading? This might be important too.

**Comment by jonliubj** [comment]
i copied the venv to the new server, ran the venv server package and checked the functionality. Shut down the venv conan server. Ran conan_server --migrate outside of the venv. Then started the conan_server outside of the venv. Everything is working as expected now. Thanks for pointing me to the older versions not being compatible with the newer versions.

**Comment by memsharded** [comment]
Happy to know it is solved now.

For the future, I would recommend:
- Using the free ArtifactoryCE: It is almost the same effort as running conan_server, but superior in all aspects.
- Take into account that 1.10 introduced revisions, and the layout changes (not sure if you upgraded to 1.9.3 or above 1.10). If you plan to migrate to ArtifactoryCE, the best is to download everything to the client (``conan download``) and re-upload to the new server.
