### ISSUE TITLE
[question] Get the source code from the artifactory using conan

### ISSUE THREAD

**Issue by military19** [conan-io/conan#8879]
Hi,

We are using conan packaging manager to get the dependencies binaries from the articatory and build our projects. The dependencies binaries and it's source code are packaged and is uploaded in the artifactory.
Now, we are working on a feature to download the source code in the cache from the artifactory and use it for debugging into our local machine.
We have tried ' conan install .. --build ', but it's not just downloading the source code but also doing other operation of build and package.
How do we just get the source code from the artifactory using conan ?

**Comment by danimtb** [comment]
If you have `conan create/install` already working by retrieving the source code from Artifactory, then `conan source` command might be what you are looking for: https://docs.conan.io/en/latest/reference/commands/development/source.html

Note that this command will download the source code to a local development folder instead of using the local cache. let me know if this works for your case. Thanks!

**Comment by memsharded** [comment]
This is now possible in Conan 2.0, see: https://docs.conan.io/2/examples/extensions/deployers/sources/custom_deployer_sources.html

Using:
- deployers
- ``-c tools.build:download_source=True`` configuration

Closing as implemented
