### ISSUE TITLE
CMake flag for exported packages

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#888]
Hi,

Is there some flag set in cmake when a package is built via `conan install` ? It would be useful for implementing some generic behaviour, like conan-io/cmake-conan#10.

If there is not such a flag I propose that something like `CONAN_EXPORTED` is set to true when invoking cmake from `conan install`.

**Comment by memsharded** [comment]
Hi Sixten, please don't close it yet, we leave issues opened until they are released, so users don't get confused. That is why we label them as fixed but open.

**Comment by sixten-hilborn** [comment]
Okay! Thanks for the information :)

**Comment by fjcalzado** [comment]
Hi guys, just a note regarding this issue:

`CONAN_EXPORTED` flag is added by default in `cmake.command_line`, and thus, everytime I run a `conan install`command I get CMake throwing the following warning:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CONAN_EXPORTED
```

which is forcing me to a fake use CONAN_EXPORTED flag in CMake just to hide the warning, eventhough I really do not need that flag. 
Is this the expected behaviour?

**Comment by memsharded** [comment]
I agree, it is a bit annoying. I think the default conanbuildinfo.cmake should include just a message to remove the warning. Please open a new issue for this feature request, it will be easy, so it can be fixed for next release.
