### ISSUE TITLE
[feature] Don't require compiler.version parameter

### ISSUE THREAD

**Issue by mcandre** [conan-io/conan#8886]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Please drop the requirement to input a `-s compiler.version` when setting the compiler name. When I set the compiler name, to clang, I simply want to use whatever version of clang is on my system. I don't care which version.

**Comment by memsharded** [comment]
This is not possible. The ``compiler.version`` needs to be specified for the packages, even if it uses the system clang, its version is necessary because that is stored and used to define the binary ``package_id``.

If you only had ``clang`` in your system, probably the auto-detected ``default`` profile would have stored the version automatically. As this doesn't seem the case, the recommendation is not to pass always ``-s compiler.version`` in the command line, but to put the compiler version in a ``clang`` profile file, together with the other possible necessary configurations, and use always in your commands ``--profile=clang``. Or if you plan to use only that configuration, just change your ``default`` profile and avoid passing it to the command line.

**Comment by IceflowRE** [comment]
Probably he is referring to the `settings.yml` which prevents the easy usage of newer compiler versions than conan has.

**Comment by memsharded** [comment]
Closing this as outdated/not planned. The ``compiler.version`` definition is and will keep being necessary

Conan 2 also added the ``settings_user.yml`` that makes even easier to add new compiler versions, if the are not already defined there.
