### ISSUE TITLE
How to access path info of build_requires?

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#8903]
Hello,
I have a custom cmake package that is used during build (e.g build_requires) To be able to use it, I need to provide the CMake package its location. Obviously it might be that a version range is provided, so I need the resolved path
How can I do that?
Thanks,

**Comment by czoido** [comment]
Hi @harsszegi,
You can use the `deps_cpp_info` object that contains the information of the requirements of the recipe to get that information of the requirement. Please check the documentation about this: https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=deps_cpp_info#deps-cpp-info
Calling something like: `self.deps_cpp_info["cmake"].bin_paths` will probably return the path you want of the resolved cmake version.
Also, in your build_requires recipe you can append that folder to the path so that it's automatically available for the consumers. Check the [recipe of cmake build_requires in conan-center-index](https://github.com/conan-io/conan-center-index/blob/1e219c43aacd6c8b30b697d1f95e84dd9cce29b7/recipes/cmake/3.x.x/conanfile.py#L104-L115) as an example of this.
Please tell me if this helps or you have further questions.

**Comment by harsszegi** [comment]
Awesome, thanks a lot, you can close the issue.
