### ISSUE TITLE
[question] explicitly allow duplicated requirement

### ISSUE THREAD

**Issue by snailcatcher** [conan-io/conan#8920]
Hi,
is it possible to allow *duplicated requirements* in conan?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by uilianries** [comment]
What do you mean? 

Same package, but different versions as a requirement?

https://docs.conan.io/en/latest/faq/general.html#is-it-possible-to-install-2-different-versions-of-the-same-library

Same package as requirement and build requirement? 

Yes, a real example is Protobuf: https://docs.conan.io/en/latest/devtools/build_requires.html#build-and-host-contexts

**Comment by snailcatcher** [comment]
@uilianries kind of the first one, but not exactly what's written in the documentation.

I will do a conanfile.txt which looks something like this:
```
[requires]
package/0.0@user/channel
package/1.0@user/channel2
...
```

When I ran the one above I will get *ERROR: Duplicated requirement package/0.0@user/channel != package/1.0@ci/user/channel*

**Comment by uilianries** [comment]
Your case is illegal by design.

The case allowed by Conan is when you have more dependencies, and those dependencies require a common package, but different versions. For instance:

```
A <-- B <- boost/1.69.0
  <-- C <- boost/1.74.0
```

The package A requires B and C. Both B and C require Boost, but different versions. Conan will rise an Error:

```
ERROR: Conflict in B/0.1:
    'B/0.1' requires 'boost/1.69.0' while 'C/0.1' requires 'boost/1.74.0'.
    To fix this conflict you need to override the package 'boost' in your root package.
```

But you can force a specific version: https://docs.conan.io/en/latest/faq/troubleshooting.html#error-incompatible-requirements-obtained-in-different-evaluations-of-requirements

As B and C are statically linked to Boost, there is no big deal. You can use the same idea.

I believe you need it because both versions are incompatible and you need to maintain a legacy project. My advice is, update to the newer version. I had the same situation years ago, was a hell to update due compatibility and behavior.

**Comment by snailcatcher** [comment]
Actually I want to use conan for a versioned doxygen documentation.
But as you mentioned above, I think I have to use an other approach.

So thank you for clarification.
I will close this one.
