### ISSUE TITLE
conan config install problem

### ISSUE THREAD

**Issue by tb185174** [conan-io/conan#8937]
Hi 
When I use  conan config install https://github.com/ncr-hw-engineering/aerocommon-conanbase.git -sf conan-config, I get a dialog box saying  "enter password to unlock private key" My password  fails every time. How do I reset this passowrd?

**Comment by memsharded** [comment]
Hi @tb185174 

https://github.com/ncr-hw-engineering/aerocommon-conanbase is a private git repo, if I understood correctly. Then it is expected that ``conan config install``, when trying to ``git clone`` will ask for credentials. A couple of quick questions:

- Don't you have the credentials in your git installation? Like git ssh keys or something? That might be the best approach in general for Conan usage, not only for ``conan config install``, but what happens when this is in CI?
- Have you tried ``conan config install git@github.com:ncr-hw-engineering/aerocommon-conanbase.git`` instead?
- I assume that your user/password is working correctly when you do ``git clone`` on the command line? Does exactly the same dialog box shows in this case?

**Comment by AbrilRBS** [comment]
Closing as solved as we didnt hear back from you in a while, and this is more an issue with your git setup. Thanks for the question!
