### ISSUE TITLE
[question] Env variables, sanitizers and gtest

### ISSUE THREAD

**Issue by GPages** [conan-io/conan#8953]
Hello,

I tried to follow the available documentation ( https://docs.conan.io/en/latest/howtos/sanitizers.html ) so that  packages ID are affected by sanitizers. In order to test i have a library "myLib" which has a unit test containing an error : 

```
TEST_F(MyLib_Test, overflow)
{
    EXPECT_TRUE(true);

    int x = INT_MAX;
    x += 1; // Integer overflow here
    printf("x = %i\n", x);
}
```

So i updated settings.yml : 

```
compiler:
    gcc:
        (...)
        sanitizer: [None, Address, Thread, Memory, UndefinedBehavior, AddressUndefinedBehavior]
```

Then using this profile : 
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
compiler.sanitizer=AddressUndefinedBehavior
build_type=Debug
```

I tried the following command (i also tried by providing the environment variables in the profile): 
```
MyLib/build :$ conan install ../ -e CONAN_RUN_TESTS=1 -e CXXFLAGS=-fsanitize=address,undefined CFLAGS=-fsanitize=address,undefined -s compiler.sanitizer=AddressUndefinedBehavior--build missing
MyLib/build :$ cmake ../ -DCMAKE_BUILD_TYPE=Debug
MyLib/build :$ make
```

Unfortunately i get a huge link error on gtest indicating undefined references to asan functions.  It is unclear to me how i should handle this.

Furthermore I also tried with conan create command: 
```
MyLib:$ conan create . myLib/1.0.1@foo/stable -e CONAN_RUN_TESTS=1 -e CXXFLAGS=-fsanitize=address,undefined -e CFLAGS=-fsanitize=address,undefined -s compiler.sanitizer=AddressUndefinedBehavior --build missing
```

This time everything compiles fine and "myLib" unit tests pass ( they should not). So i guess it was actually not built with the sanitizers.

So i wonder : 
  - What are the missing steps in my approach ?
  - My hope is to be able to rebuild my entire dependency tree  with sanitier (each lib is packaged in the same way) just by updating the profile accordingly, is it a naive hope or should it work ?

- [ X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Parcley** [comment]
@GPages I see that this issue has been closed. I am facing the same behaviour as you are describing on this issue. Can you tell if you could solve that issue?

Did https://github.com/conan-io/conan/issues/4754#issuecomment-474285354 solve your issue?

**Comment by memsharded** [comment]
Hi all,

There are a couple of important points to clarify:

- One thing is the binary model. What is defined in the ``settings.yml`` and the ``profiles`` files. That defines a ``package_id`` that can change when the settings change, and can be used to model different variants of binaries.
- The other part are the build-system integrations. There is not magic in them that will automatically listen to new, not built-in new settings, like user defined sanitizers, and magically inject the necessary flags, libraries, etc in the build. That part must be implemented in the build systems scripts.
- Typically, the user settings will be passed to the build system helpers, defining a CMake variable, or an environment variable, whatever the build scripts expect, to activate/deactivate or configure the build to add the desired sanitizers. 

This is a closed issue. The best way to proceed for something not working as expected is to put together a minimal reproducible case in a repo in a new issue, maybe starting from a ``conan new hello/0.1 --template=cmake_lib`` template, and then describe the settings, profiles, etc. But without a recipe that works, it is very difficult to help, because it completely depends on what is implemented in the package recipe.
