### ISSUE TITLE
[feature] Search with ability to filter only with existing prebuilt binaries

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8954]
It'd be nice to have a convenience flag to search for only packages which have prebuilt binaries for a given profile

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @xahon 

I am afraid this is not possible. To search packages based on matching settings and options, all the conaninfo.txt files from all the packages that match for all the binary configurations existing in the server should be loaded in the server, filtered and returned. This is very expensive operation. 

That, doesn't taking into account that for real profile matching recipes must be evaluated, because they can define to be a match for a given profile with a custom ``package_id()`` method. Parsing and loading recipes in the server is not possible, that would be a massive security issue. Returning all matching recipes to the client to be parsed would make this even worse, totally intractable.

Something might be doable in ConanCenter frontend, because there we have power and we can precompute and store things in a dedicated infrastructure, is that what you are asking for?

**Comment by AbrilRBS** [comment]
Closing this as solved in Conan 2.2, where the `conan list` command has learned to filter packages based on profiles, settings and options
