### ISSUE TITLE
[bug] self.deps_cpp_info[<dependency>] is not available in validate

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#8982]
When wanting to check the version of a dependency in the `validate` method, `self.deps_cpp_info[some_dependency]` is not available.

e.g. the following recipe fails:

```python
from conans import ConanFile, tools
from conans.errors import ConanInvalidConfiguration


class NeedBoost176(ConanFile):
    name = "needboost176"
    version = "0.1"

    def requirements(self):
        self.requires("boost/1.75.0")

    def validate(self):
        if tools.Version(self.deps_cpp_info["boost"].version) < "1.76.0":
            raise ConanInvalidConfiguration("Need boost version 1.76.0")
```
Access to the version of a dependency is useful to either disallow too new versions or disallow too old versions.

### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora 34
  * Compiler+version: gcc 11.1
  * Conan version: 1.36.0
  * Python version: 3.9.5

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: Traceback (most recent call last):
  File "/home/maarten/.local/lib/python3.9/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/home/maarten/.local/lib/python3.9/site-packages/conans/client/graph/graph_binaries.py", line 357, in _compute_package_id
    conanfile.validate()
  File "/home/maarten/.conan/data/needboost176/0.1/_/_/export/conanfile.py", line 13, in validate
    if tools.Version(self.deps_cpp_info["boost"].version) < "1.76.0":
  File "/home/maarten/.local/lib/python3.9/site-packages/conans/model/build_info.py", line 712, in __getitem__
    return self._dependencies[item]
KeyError: 'boost'
```

**Comment by memsharded** [comment]
Hi @madebr 

This is one of the things that will be addressed by the new dependencies access model, which we already have a proof of concept released in 1.37 (but not documented yet, we are evolving it in Conan 2.0 branch, to feed it back in 1.X and be sure that the transition will be smooth).

It seems very difficult to solve it via ``deps_cpp_info`` at this stage, because ``validate()`` executes before ``package_info`` is evaluated and propagated, but hopefully we can start stabilizing and documenting this new access in the next releases. At the moment, the best is to try to use ``self.requires["boost"].ref.version``, but as you know, this might not be the real value in all cases (diamonds with overrides)

**Comment by madebr** [comment]
Thanks, in conan-io/conan-center-index#5589 I want to test against the final resolved version.
Until this gets fixed in conan, I will implement a workaround.

Thanks for the feedback.

**Comment by AbrilRBS** [comment]
Closing as solved with the `self.dependencies` accessor available in both v1 and v2
