### ISSUE TITLE
[bug] Inconsistent behavior between 'conan source' and 'conan create' for 'export_sources'

### ISSUE THREAD

**Issue by Forbinn** [conan-io/conan#8998]
### Environment Details (include every applicable attribute)
  * Operating System+version: Fedora 31
  * Compiler+version: gcc9
  * Conan version: 1.36.0
  * Python version: 3.7.9

### Steps to reproduce (Include if Applicable)

- `conan new -s test/0.1.0`
- Edit the conanfile.py to add an `export_sources` function
```python
    def export_sources(self):
        print(self.settings.os)
``` 
- `conan source -sf .` -> Works fine
- `conan create .` -> Fails

If you execute the `conan source` step yourself, everything works fine but if you execute the `conan create` step then it fails with an obscure error on `self.settings`.

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
Exporting package recipe
test/0.1.0 exports_sources: Copied 1 '.cpp' file: test.cpp
test/0.1.0 exports_sources: Copied 1 '.h' file: test.h
test/0.1.0 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
test/0.1.0: Calling export_sources()
ERROR: test/0.1.0: Error in export_sources() method, line 19
	print(self.settings.os)
	AttributeError: 'tuple' object has no attribute 'os'
```

**Comment by memsharded** [comment]
Hi @Forbinn 

Actually, the misbehavior is in the current ``conan source`` command, something that is known, but couldn't be fixed so far, because even if a bug, it would be breaking to some users, so it was decided to leave it:

Please carefully read the note in the docs here: https://docs.conan.io/en/latest/reference/conanfile/methods.html#source

In summary: source related methods, like ``source()``, ``export()``, ``export_sources()`` cannot condition on settings, options or anything else, as they should contain the source code which is common to all possible binaries.

CONAN_V2_MODE will already launch an exception when trying to access ``self.settings`` from the ``source()`` method, and the same will be implemented in ``export_xxx()`` methods. If you need to do something configuration specific, it should probably go to the ``generate()`` or ``build()`` methods, depending on what it is.

**Comment by Forbinn** [comment]
Hi @memsharded,

Thank you for the reply. I understand and it makes sense when you see it like that.
So in my case I will do it inside the `build()` method instead of the `source()` one.
