### ISSUE TITLE
Conan metadata.json and metadata.json.lock remains with read-only to the group in linux

### ISSUE THREAD

**Issue by maoreliy** [conan-io/conan#9013]
Conan metadata.json and metadata.json.lock remains with read-only to the group in Linux.
We are using the storage.path in a share mode, means that all of the users are using the same area for consuming the packages,
the motivation for it is to reduce the overall wait time of download and unzip.
when we are using the precopmiled packages, conan creates metadata.json and metadata.json.lock with R/W permissions to the group and that's fine, we can set the storage.path with no issue.
the problem is when we use a package that should pass build or creating a new precompiled package for uploading to our internal artifactory,
That creates metadata.json and metadata.json.lock with Read-Only to the group which causes permission error when we tries to set the storage.path and run "conan config install"
it looks like at the end of the process it should "free" these files and also put them as R/W to the user.

### Environment Details (include every applicable attribute)
  * Suse 11:
  * Visual Studio 14:
  * 1.24:
  * 3.7.4:

### Steps to reproduce (Include if Applicable)
use common conan.cache areas with two different users,
1. first user will set the storage.path to this area
2. first user will run export-pkg
3. second user will try to set the storage.path to the same area and run conan config install <conf_directory (must include remote.txt>  - > that should raise an error.

### Logs (Executed commands with output) (Include/Attach if Applicable)
ERROR: [Errno 13] Permission denied: ...

**Comment by memsharded** [comment]
Hi @maoreli 

> We are using the storage.path in a share mode, means that all of the users are using the same area for consuming the packages,
the motivation for it is to reduce the overall wait time of download and unzip.

I am afraid that this is not a supported use case at the moment. The Conan cache is not designed for concurrency, not even single-user concurrency. It has some limited provisions (locks) for some limited cases, but in the general case it should be considered non-concurrent.

So multi-user support is not planned at the moment for Conan 1.X. Even if we tried to fix that specific thing, but then it is very possible that other permissions errors will happen, inside packages or elsewhere.

Conan 2.0 is preparing a new cache, that can store multiple revisions, and it will get rid of the metadata.json files too, so this problem will go away. But that is a huge amount of breaking changes that cannot be backported to 1.X.

**Comment by maoreliy** [comment]
Hi @memsharded,
Thanks for sharing your inputs,
I am trying to understand if it will be ok to use a conan.cache as read-only to the group and only specific user, kind of service user will manage the cache, and the group will only consume packages from this area,
can it be a valid case?

one more Q,
why conan doesn't support concurrency? what cases can cause an issue if we will use it in concurrency mode?

**Comment by maoreliy** [comment]
Hi @memsharded 
Can you please help me understand what are the answers for the above Qs?

**Comment by memsharded** [comment]
> I am trying to understand if it will be ok to use a conan.cache as read-only to the group and only specific user, kind of service user will manage the cache, and the group will only consume packages from this area,
can it be a valid case?

Maybe, yes, we would need to think more about this. But the thing is that this would start to really be a problem when the cache can be really used concurrently, and this is not any time close.

> one more Q,
> why conan doesn't support concurrency? what cases can cause an issue if we will use it in concurrency mode?

Because it is a very challenging problem. Concurrency in general is a challenging problem, and Conan in particular has some particularly challenging ones:

- It involves all kind of slow IO operations, from downloading Gbs of files, to saving, loading, unzipping those Gb files.
- It is not enough with mutex like sync, but it is necessary to implement Readers-Writers problems.
- There is no portable, robust and tested multi-platform Readers-Writers implementation in python. Only this individual problem would be a project by itself, and not an easy one.
- Synchronization for Conan package management is conceptually complex, not just implementation complex. For example the business logic to know that a recipe of a package cannot be removed when a package binary that belongs to that recipe is being built, or the fact that many concurrent operations cannot be known in advance if they collide or not, until they happen (and after things like actual file copies)

What is the scale of your problem? what is the impact of having each user to have their own cache? 
For things like reducing the transfer to the server, the "download cache" might be a possibility https://docs.conan.io/en/latest/configuration/download_cache.html?

**Comment by memsharded** [comment]
These files have been removed in 2.0, closing as outdated.
