### ISSUE TITLE
[bug] MSBuildDeps - Created prop sheets settings are not delimited

### ISSUE THREAD

**Issue by sd185233** [conan-io/conan#9027]
This screenshot shows the generated settings - note that there is no delimiter between the Conan include dir variable and the existing AdditionalIncludeDirectories var - 

![image](https://user-images.githubusercontent.com/69502342/120165405-73444600-c1f3-11eb-99ef-7ab7617b0ab8.png)

I think they should be delimited with a ";".  This applies for all the settings and groups. 
![image](https://user-images.githubusercontent.com/69502342/120165450-7f300800-c1f3-11eb-8493-12c87fb68179.png)

Note:  Still investigating issues around header paths not being searched, but with this change, the settings are starting to look better.  Previously the variables were all together on one line, with this change they are split correctly over multiple lines.

**Comment by memsharded** [comment]
Hi @sd185233 

But that shouldn't be an issue, because the variables themselves are using a ";" at the end:

```python
'include_dirs': "".join("%s;" % p for p in cpp_info.include_paths),
```

The idea is to avoid initial empty ``;%(AdditionalXXXX)`` when the Conan variables are empty (which often are).

**Comment by sd185233** [comment]
How does that work when the last path in the variable is not terminated?

![image](https://user-images.githubusercontent.com/69502342/120170321-c076e680-c1f8-11eb-9301-144b67775b76.png)

**Comment by sd185233** [comment]
This is how it looks when the variables are delimited - 

![image](https://user-images.githubusercontent.com/69502342/120170548-fb791a00-c1f8-11eb-94d3-9a380556cded.png)

**Comment by memsharded** [comment]
This is curious, if you could share directly the ``conan_xxxx_vars_xxxx.props`` file, that would help, because it seems impossible that such value is generated without being terminated in ";", at least I cannot see how this is possible from the python code, so maybe it is just the IDE not showing terminating ";"?

**Comment by sd185233** [comment]
You're right, the UI is dropping it off.  

![image](https://user-images.githubusercontent.com/69502342/120176046-be178b00-c1fe-11eb-909f-d8332ae69466.png)

Guess we can close this off :)  

Btw...This is all working after removing an empty AdditionalIncludeDirectories tag from the vcxproj :)

**Comment by memsharded** [comment]
Ok, happy to hear that it is working now!

If you think it would be better to try to change the delimiters we could give it another try, but if I recall correctly, it might be this way to avoid other problems with empty ";" things.

If not, yes, lets close it. Thanks for all the feedback! :)

**Comment by sd185233** [comment]
I think its's easier to follow from the UI with the delimiters...however, it does work and once set up we will rarely be looking at these settings.

Thanks!

**Comment by jdoubleu** [comment]
At first I found it odd, that there are no delimiters when the properties were placed e.g. in `<AdditionaIncludeDirectories>`. This doesn't follow the convention used everywhere else in `.vcxproj` files.

Furthermore, this introduces issues when parsing the Conan props (e.g. `Conan<component>IncludeDirectories`). Due to the delimiter at the end, its value may get interpreted as array _with an empty element_ by some functions.

**Comment by memsharded** [comment]
Hi @jdoubleu 

This ticket is closed. If there is some issue with the generated files it would be better to create a new ticket for it, with a full description of the problem and way to reproduce it. Thanks!
