### ISSUE TITLE
[question] custom/None compiler

### ISSUE THREAD

**Issue by snailcatcher** [conan-io/conan#9028]
Hi,

Is it possible to add a "None" compiler to the conan settings?
My goal is to install a conan package on my system, without the need to build it (even if the prebuild package is not available for my current system)

If there is any way to ignore that a package is not available as prebuild package for my system, that would also answer my question.
I don't need this for a single package, but for my whole conanfile.txt or for my whole system. My usecase is only relevant for CI.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @snailcatcher 

Why not just skipping the ``compiler`` in the recipe declaration?
Something like:

```python
class Pkg(ConanFile):
     settings = "os", "arch"

```

In that way, you don't need to define the ``compiler`` setting or any of its subsettings at all.
Is that what you are looking for?

**Comment by snailcatcher** [comment]
Hi @memsharded 

Not exactly.
1. this is not V2 compatible:
```sh
ConanV2Exception: Conan v2 incompatible: compiler setting should be defined.
```

2. I want this to be an explicit case:
So if I not define anything, I want my package to build with gcc (mingw on windows, gcc on linux). \
If I explicitly say that my ci script does not need the packages to be build (e.g. for documentation purposes or something like that), I want to tell conan that it should skip the whole build method (or return without doing the cmake stuff).

So the none build case should be the egde case which I can define either by a profile or by cli parameters (I don't need both, just one)

Is this possible, or is there a better solution?

**Comment by memsharded** [comment]
But ``ConanV2Exception: Conan v2 incompatible: compiler setting should be defined.`` should only happen if you are using a build integration that will need a compiler to compile something. How does your recipe look like?


I think your question could be resolved by https://github.com/conan-io/conan/issues/8366, which has been targeted for Conan 2.0:

- You add the ``compiler`` setting to your recipe, as usual
- You remove the ``compiler`` setting from the ``package_id``, if you want the package to be independent of the compiler who built it.
- Conan will not fail if you don't define the ``compiler`` value, as long as it doesn't try to build from source.

This is probably a more sound solution, that will work better for most cases, that having to provide a None value for a compiler, because it is actually not needed to build anything.

Would you please mind checking that thread, and if true, follow it, and we might close this one?

**Comment by snailcatcher** [comment]
I do, I use the CMake integration:

<details>
  <summary>My conanfile</summary>

```py
from conans import ConanFile, CMake

class Pkg(ConanFile):
    name = "my_pack"
    version = "0.0.0"
    description = "desc"
    exports_sources = "*"
    generators = "cmake"
    settings = "compiler", "build_type"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        self.copy("*.h", dst="include", src="include")
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = [self.name]
        self.cpp_info.srcdirs = ['src']

```
</details>

Yes I think your right, it will lead to the same thing.

So the correct package_info method for my issue should look like that? 
```py
    def package_info(self):
        del self.settings.compiler
        del self.settings.build_type
        self.cpp_info.libs = [self.name]
        self.cpp_info.srcdirs = ['src']
```

If that's correct you can close my issue and thank you for the good explanation.

**Comment by memsharded** [comment]
Actually, you should use:

```python
    def package_id(self):
        del self.info.settings.compiler
        del self.info.settings.build_type

    def package_info(self):
        self.cpp_info.libs = [self.name]
        self.cpp_info.srcdirs = ['src']
```

It is very important that you remove the ``self.info.xxxx`` to make package_id independent, while keeping the original value available for ``build()``. Also it should be in the ``package_id()`` method.

Ok, lets close it, and we can follow in the other issue. Thanks!
