### ISSUE TITLE
Make it possible to move short_path folder

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#904]
Hi,

we are doing a great deal of Jenkins builds, building for different compilers on different machines. Thus, i collect all the .conan and short path folders from all machines and integrate them in the end (after the tests) to upload them. 

As we use the short_path feature for every component, I ran into problems with the `CONAN_USER_HOME_SHORT` and the `.conan_link` files, as these files contain absolute paths. These paths may differ based on the build (Jenkins sometimes adds a @2 to the path on concurrent builds), resulting in 
```
Checking package integrity...                                         ERROR: Cannot upload corrupted package 'Package/1.0@demo/testing:c8ff78a405e8b6604eb5a2b4230c3b222986cabb'
```

One way to achieve this would be to use `CONAN_USER_HOME_SHORT` in `.conan_link` files instead of the absolute path.

As I don't care about the build and the source folders, another way would be to make it configurable whether the package folder is created in the short path folder. (This would be very easy, e.g. based on an env variable).

Of course, another way would be to publish everything directly after each build to a private channel, and copy it to a public channel after successful builds. Or to use transaction uploads :-)

Any thought on this?

**Comment by memsharded** [comment]
I am not sure that directly collecting information from ``.conan`` folders and the local cache in general is a good idea, as the storage and layout of the local conan cache might change. Actually, due to this feature request: https://github.com/conan-io/conan/issues/866, it is likely that it will have some changes soon.

Quick (dummy) question: are you using ``short_paths`` in all packages because all your packages have very long path names? It is designed as a workaround, when no other possibility exists, but I wouldn't it make the default for all my packages if not strictly necessary.

Sure I like much more the idea of uploading to a private channel, then promoting it entirely after successful builds. About the transactions, I would like them, they are beautiful as a concept, but from my experience, extremely hard to implement them correctly to work well in practice. 

If some workaround would be necessary, I have to think it. Probably using CONAN_USER_HOME_SHORT in the link could make sense, yes, but I am still concerned about depending on conan internal implementation details for operation, I strongly think that other solution should be found, so the conan local cache could be even completely refactored without any impact to users.

**Comment by claasd** [comment]
We need the `short_paths` option, otherwise the builds fail with the notorious windows long path error.

I think I will go with the use of a private channel (or even conan server) for CI builds and copy them over to a different channel (or server) when everything goes well.

Using artifactory, I can use two different conan servers from one artifactory and use the artifactory move command (wich seems to be transactional, yay) to move from CI conan server to public conan server.

I will cose this issue with this comment ;-)

**Comment by memsharded** [comment]
Ok, sounds good, thanks very much!

**Comment by patricia-gallardo** [comment]
Hi all :) , this is hitting me as well, because it means I can't move my CONAN_USER_HOME_SHORT directory, because the path to it is hard coded in my .conan - I can move my .conan, though. Is there any way to work around this now in 2020?

**Comment by patricia-gallardo** [comment]
Note that the scm_source/.conan_link and source/.conan_link seem to be fixed up after a move, but not the short .conan_link files - they still have the hardcoded paths
