### ISSUE TITLE
[bug] Max retries exceeded with url... (Caused by ResponseError('too many 500 error responses'))

### ISSUE THREAD

**Issue by gogoprog** [conan-io/conan#9040]
### Environment Details 
  * Operating System+version: Linux ggpc3 5.12.4-arch1-2  x86_64
  * Compiler+version: gcc11 but irrelevant
  * Conan version: 1.36.0
  * Python version: 3.9.5

### Steps to reproduce 
 * Have several remotes
 * Build a recipe that has a lot of dependencies (sdl2 in this case)
 * Notice the error related to a connection `Max retries exceeded with url... `

So one of the remote does not have the required dependencies. I can remove it temporarily solve the issue but I don't think this should stop the building process.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Debug;-s;compiler=gcc;-s;compiler.version=11;-s;compiler.libcxx=libstdc++11
-- Conan: checking conan executable
-- Conan: Found program /usr/bin/conan
-- Conan: Version found Conan version 1.36.0

-- Conan executing: /usr/bin/conan install . -s build_type=Debug -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++11 -g=cmake --build=missing -o=sdl2:arts=False -o=sdl2:jack=False -o=sdl2:nas=False -o=sdl2:sndio=False -o=sdl2:iconv=False
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
sdl2:arts=False
sdl2:iconv=False
sdl2:jack=False
sdl2:nas=False
sdl2:sndio=False
[build_requires]
[env]

ERROR: HTTPConnectionPool(host='******', port=9300): Max retries exceeded with url: /v1/conans/libalsa/1.2.4/_/_/packages/537964df6f37aee2c819b0357cf959e6cd7ed719/download_urls (Caused by ResponseError('too many 500 error responses')). [Remote: firefalcom]
CMake Error at /home/****/build/conan.cmake:522 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  /home/*****/build/conan.cmake:759 (old_conan_cmake_install)

```

**Comment by memsharded** [comment]
Hi @gogoprog 

I am a bit confused, there seems to be more than one issue here. 
On one hand, you are getting 500 internal errors from a server? How is that happening? Can you reproduce it consistently? Maybe we want to investigate first what happens with that server.

The other issue is that Conan will stop iterating remotes if one fails. This is by design, some users rely on the remote order to resolve their projects in that order, prioritizing their own packages for example versus the ConanCenter, and one remote going down and skipping to the next one, can have bad consequences in the final product. So when one remote is faulty, non-reachable or something similar it will stop. You have the ``conan remote disable`` to temporarily disable it without really removing if you know it is ok and you don't mind getting the packages that were there from another remote.

**Comment by gogoprog** [comment]
Thanks for the insights, I'll check the remote status

**Comment by gogoprog** [comment]
The remote server has been updated and the issue does not occur anymore. Thank you
