### ISSUE TITLE
[feature] Setup virtual environment without the need to invoke scripts and file creation

### ISSUE THREAD

**Issue by derived-coder** [conan-io/conan#9052]
I want to start a tool via conan, this required for me to do following atm:
```
conan install mytool/latest@company/stable -u -g virtualenv -g virtualrunenv
source activate.sh && source activate_run.sh
mytool
```
I would like to avoid the step: `source activate.sh && source activate_run.sh`
Which additionally required an writable, directory because files are written do disk.
Which should be avoided too.

I would like to have something like that:
```
conan install mytool/latest@company/stable -u -g run_env
mytool
```

or shorter with a new cmd:
```
conan setup-env mytool/latest@company/stable 
mytool
```

or:
```
conan start-app mytool/latest@company/stable 
```

- [ x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Closing as not planned.

Main reason: a running process cannot change the environment of the parent process. So this is not possible to implement, and the 2 steps are necessary. This is why the syntax is ``source ....sh`` and not just running the ``activate.sh`` file, because running the script has no effect on the parent environment.
