### ISSUE TITLE
[bug] conan info does not respect --remote if the recipe/binary has already been cached from a different remote

### ISSUE THREAD

**Issue by wKavey** [conan-io/conan#9074]
It seems that subsequent calls to `conan info` using a `--remote` argument will not respect the given `--remote` if the package/recipe/binary has already been cached from a different remote. 

This seems at odds with the help text for `--remote`
```
-r REMOTE, --remote REMOTE                               
                      Look in the specified remote server
```

### Environment Details (include every applicable attribute)
  * Operating System+version: SLES12SP3
  * Compiler+version: GCC 4.8
  * Conan version: 1.36.0
  * Python version: 3.8.1

### Steps to reproduce (Include if Applicable)

1. Run `conan info {package} --remote {remote_A}` using a `remote` that you know contains the recipe/binary
2. Run `conan info {package} --remote {remote_B}` using a `remote` that you know **does not** contain the recipe/binary. Conan info will still serve you information about the package that was cached from `remote_A`.

**Comment by memsharded** [comment]
Hi @wKavey 

This is not a bug, this is how the ``--remote`` argument works across all commands that resolve the dependency graph, including ``install``, ``create``, ``export-pkg``.

The dependency graph is always evaluated locally, from the Conan local cache, because the recipes have to be imported, loaded and evaluated, and that cannot be done in the server. So recipes are fetched from servers to the local cache by the ``info`` commands. 

The ``--remote`` argument has the semantics of "look in this server" but it means when a package is not found locally. Conan always check the local cache first for performance, before hitting the servers. If a recipe is in the local cache it will be found there and avoid looking for it in the server. If a recipe is already in the local cache, it will be loaded from there, even if ``--remote`` is specified. Only when ``--update`` is also specified, it will look first in the servers, to check if there are updates to the already installed recipe. If there is no update, nothing will be downloaded. If there are updates, they will be downloaded first, then loaded from the cache.

So it seems this is not a bug, but expected behavior.
