### ISSUE TITLE
[feature] Support for custom directory for conan_server

### ISSUE THREAD

**Issue by jenia90** [conan-io/conan#9098]
Currently conan_server only supports being deployed to a default location - `~/.conan_server/`. My suggestion is to let the user set a custom directory by adding command-line argument that will let the user set where the server config and data will be stored. As far as I see from the code it should be something that is rather easy to do, and I would like to open a PR to add the functionality.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @jenia90 

Sure, feel free to submit a PR for it, thanks for wanting to contribute. Just make sure that it is opt-in and it will not break existing users.

**Comment by jenia90** [comment]
Hi @memsharded 

Of course, it should be an optional flag that users can specify when they launch the server. What do you think about adding an environment variable, say CONAN_SERVER_DIR, as an alternative way of specifying the directory?

**Comment by memsharded** [comment]
> What do you think about adding an environment variable, say CONAN_SERVER_DIR, as an alternative way of specifying the directory?

Typically I would go for 1, possible the simplest or most demanded "main" implementation, then only add alternative ways based on user demand. In this case, actually I would probably go with just the env-var because it would be more symmetric to the client (CONAN_USER_HOME), so something like an env-var (CONAN_SERVER_HOME). But if you feel the cli arg is better for your case, go ahead for it.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/9099, will be in 1.38. Thanks for contributing it!
