### ISSUE TITLE
[question] Are the binaries in conan-center safe?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9102]
If yes, how does conan keep the binaries safe? Does  the binaries on conan-center are built on official servers?

**Comment by memsharded** [comment]
Yes, all the binaries available in ConanCenter (remote conancenter: https://center.conan.io) are built by our build service in the conan-center-index repo.

Still, a very large part of Conan users (more than 50%) do build their own binaries from the conan-center-index repo, and store their binaries in their own private Artifactory, because of policies, regulations, security, etc. And we support that, this is a better practice than relying so heavily on central repositories, like other communities (npm, pypi, etc) do.
