### ISSUE TITLE
Is it possible to specify build type of required package inside of the package recipe?

### ISSUE THREAD

**Issue by italiks** [conan-io/conan#9117]
Hi there!
I build a package and want it to depend on Release OpenSSL library no matter what build type is.
I've tried something like
```
class MyPkg(ConanFile):
...
    def configure(self):
        self.settings["openssl"].build_type = 'Release'
...
```
But it seems not a valid code.

Is it possible to make this kind of configuration?
If yes, could you show a sample?

**Comment by memsharded** [comment]
Hi @italiks!

It is not possible from recipes, by design, defining these things in the recipes is problematic.

Settings are external configuration. You can define it:

- In your profile files (recommended to use profile files)
- In command line 

In both cases, you could specify settings per package, in case you wanted, like ``-s openssl:build_type=Release``

**Comment by italiks** [comment]
Hi @memsharded !
Thanks a lot for your answer!
What about _conan-package-tools_? 
Is it possible to configure **ConanMultiPackager** to use `openssl:build_type=Release`?

**Comment by memsharded** [comment]
Not sure about it, I think it is possible in the ``settings`` argument to pass ``openssl:build_type``, but you might ask in https://github.com/conan-io/conan-package-tools, or maybe @uilianries can help here too.

**Comment by uilianries** [comment]
Hello @italiks ! 

It's not possible. The CPT is very strict in terms of settings, because we wanted to avoid nightmare scenarios or rare scenarios, where something goes wrong and we would need to "fix" CPT putting a constraint.
Also, CPT by default was designed to build any generic package using all settings x options combinations, but not focused on their dependencies.

If you need CPT for CI building, I would recommend [lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles/ci.html) instead, which preserves your reproducibility, so you can build using your CI service and execute the exactly same build locally.

**Comment by italiks** [comment]
Thank you guys! @uilianries @memsharded 
Gonna check out **lockfiles**
