### ISSUE TITLE
[feature] Generate find_package include with cmake_find_package*

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#9126]
Maybe this misses the point, but with cmake_find_package* you need to duplicate all your dependencies from your conanfile into your cmake file. Seems totally doable to generate a conan_find_package.cmake in which you autogenerate all those find_package calls.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This issue was reporting the legacy CMake integration, which has been superseded by the new one in Conan 1.X https://docs.conan.io/1/reference/conanfile/tools.html, and removed in Conan 2.0: https://docs.conan.io/2/reference/tools/cmake.html. Closing this ticket as outdated.

Please update to use the modern CMake integration, and please don't hesitate to open new tickets as necessary. Thanks!
