### ISSUE TITLE
[question] conan download fetches python_requires

### ISSUE THREAD

**Issue by Da-LiFe** [conan-io/conan#9128]
Hi everybody,

I've noticed some issues with `conan download` in our CI pipeline. A short summary of the pipline with pkgA depends on pkgB:

- the CI is building pkgB because of some code changes. It is uploading the pkg to a temp repo on artifactory, e.g. `conan-libs-temp`.
- the CI is automatically triggering the build of pkgA to test build against pkgB and tries to fetch the recipe of pkgB from the temp repo to create the build order:

`conan download pkgB/some_ver@some_org/snapshot#2ea7ed78fe8fb6c7a40451abd0db25c7 -r conan-libs-temp --recipe`
`conan graph lock pkgA/some_ver@some_org/stable -pr [...] --remote rmc-conan-libs --build missing`

However, `conan download` fails if pkgB uses python_requires:

`ERROR: Error loading conanfile at '[...]/conanfile.py': python_pkg/some_ver@some_org/stable was not found in remote 'conan-libs-temp'`

The `python_pkg` is not available in 'conan-libs-temp' because it was not build. The [docs](https://docs.conan.io/en/latest/reference/commands/misc/download.html) state that "_requirements of the specified reference will NOT be retrieved_", but this seems not true for python_requires.

What I would expect from the docs is, that conan download only fetches the recipe of pkgB and a subseqent call to `conan [graph] lock` on `pkgA` then fetches the `python_pkg` from a the same remote then `pkgA`. We are still using conan 1.22, but I don't think it's related as the docs didn't change.

Therefore, my questions are:
- is this behaviour of `conan download` expected?
- if yes: how would then one handle this case in the CI pipeline?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @Da-LiFe 

Yes, this is expected behavior. ``python_requires`` are necessary for every evaluation of a ``conanfile.py``, as it is an intrinsic part of it, the conanfile could be extending a class existing in the python-required conanfile with ``python_requires_extend``. The python_requires fetching and evaluation is necessary because ``conan download`` requires to know a few things:
- If recipe defines ``exports_sources`` to download those sources as well (the ``exports_sources`` definition could be inherited from python_requires).
- Recipe can define ``short_paths=True`` for windows, download location folder will be a different one to avoid long paths in the cache.
- The ``conanfile`` is also passed as an argument to pre-post download hooks


The behavior is similar for other commands that are not supposed to retrieve requirements, for example ``conan export``, when ``python_requires`` are defined, will also need to download those ``python_requires`` to evaluate the recipe to be able to do the export.

I think that the way to solve this could be here:

> the CI is building pkgB because of some code changes. It is uploading the pkg to a temp repo on artifactory, e.g. conan-libs-temp.

The CI building pkgB because of the code changes should upload to temp repo, not exclusively the ``pkgB``, but also its dependencies, including ``python_requires``. This upload should be also cheap (Artifactory de-duplication of packages), and will make the temp repo more self-contained and easy to reproduce builds using it. 

Have you considered that approach?

**Comment by Da-LiFe** [comment]
> The CI building pkgB because of the code changes should upload to temp repo, not exclusively the pkgB, but also its dependencies, including python_requires. This upload should be also cheap (Artifactory de-duplication of packages), and will make the temp repo more self-contained and easy to reproduce builds using it.

That's basically a good idea. However, our upload is currently based on the information found in the json file generated by `conan install`, but it seems that `python_requires` are not covered by this file, at least in conan 1.22. Is that observation correct? If yes, we would need to gather that information from the lockfile generated during `conan [graph] lock`, right?

**Comment by memsharded** [comment]
> but it seems that python_requires are not covered by this file, at least in conan 1.22. Is that observation correct? If yes, we would need to gather that information from the lockfile generated during conan [graph] lock, right?

Yes, it seems that ``python_requires`` are not there, and it would be difficult to add them, because the infrastructure for that feature doesn't have access to that. I guess you are right, and gathering them from the lockfile could be the best approach.

**Comment by Da-LiFe** [comment]
> 
> 
> > but it seems that python_requires are not covered by this file, at least in conan 1.22. Is that observation correct? If yes, we would need to gather that information from the lockfile generated during conan [graph] lock, right?
> 
> Yes, it seems that `python_requires` are not there, and it would be difficult to add them, because the infrastructure for that feature doesn't have access to that. I guess you are right, and gathering them from the lockfile could be the best approach.

I've created a POC using lockfiles for dependency upload including `python_requires`. The pipeline now succeeds. Thanks for the feedback!

**Comment by memsharded** [comment]
> I've created a POC using lockfiles for dependency upload including python_requires. The pipeline now succeeds. Thanks for the feedback!

Happy that it is working! 

We will use this feedback, and make the ``python_requires`` more easily available in graph information in Conan 2.0. Thanks!
