### ISSUE TITLE
[question] [workspaces] Pull Packages into Workspace from Remote

### ISSUE THREAD

**Issue by sammckee** [conan-io/conan#9136]
Conan version: 1.37.2

I believe the Conan workspace feature would be very useful for our team. However, I do not see a way to pull packages from our remote into the workspace. Are developers forced to build the entire workspace package tree from scratch? Our projects are large enough for this to be a dealbreaker since our existing tools do not require scratch builds for new developers.

I have tried to use the -r and -u flags but have not seen a difference on the initial workspace build.
 
Please let me know if pulling packages into the workspace is plausible and where I can find some examples. 

 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @sammckee 

At the moment, automatically pulling packages into the workspaces is not possible.

But yes, this feature would make sense. At the moment, the ``workspace`` feature is on hold, because we are working on other higher priority things. One of them is the re-thinking of the ``editable`` feature, which is the foundation for workspaces. Conan 1.37 released a new feature called ``layout()``, that dramatically improves the ``editable`` experience. We will keep working on that for the next releases, to stabilize it and make it ready for adoption.

After that, at some point we will resume work on workspaces (it might be after Conan 2.0), and one of the features that we would like to at least consider is this one. Most likely it will only be possible when using the ``scm`` component to define sources, but in that case, it might be doable.

Please track this issue for future progress (but be patience, it might take a while), and meanwhile I would suggest to try something like:

- Use the ``scm`` feature to store the source origin of package recipes
- When you want to pull things into the workspace, you can check the ``scm`` component information with some helper commands (you can try ``conan inspect``, for example).
- It sounds doable to have some helper script on your side that automate the process of doing the ``conan inspect`` + parsing + executing a ``git clone`` with the result to bring the clone into your current user folder.

Thanks for the feedback!

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466, closing this
