### ISSUE TITLE
[feature] per-project conan configuration

### ISSUE THREAD

**Issue by tthef** [conan-io/conan#9145]
Conan should support per-project configuration, e.g., using project/.conan directory. I am working on multiple projects using conan and at the moment that means all of them have to share the same settings / profiles / remote configs. This is very awkward.

Imagine the following scenario: project B depends on project A; project A needs to change profiles (e.g., because of toolchain update), this is a non trivial change that will take 2-3 weeks before project A is ready to release. During that time, work on project B needs to carry on, which means that each time a developer wants to switch between them, they need to reinstall a different config, to have the correct profiles; this also applies to any CI appliances. (While the CONAN_USER_HOME env variable can be used to create multiple caches, this doesn't do the right thing here, as the projects in the above example need to share a cache, just use different settings.)

Similarly, the different projects might require different remotes configuration, e.g., project A might require additional remotes that are not needed by project B, and might be subject to different access policies.

Being able to specify things like settings.yml, remotes.txt and profiles inside the project tree would address these usability issues.

**Comment by memsharded** [comment]
There is already a way to achieve this:

- Define for each project ``CONAN_USER_HOME=<project/.conan>``
- Define in project/.conan/conan.conf ``storage.path`` to point to a common location

```
$ set CONAN_USER_HOME=<project>
$ conan config set storage.path=<path to common storage>
```

**Comment by tthef** [comment]
That's not a viable way of doing it, since the storage.path would have to be an absolute when CONAN_USER_HOME is set, and this should work simultaneously on windows, mac and linux for an entire team. Also, environmental variables are about the worst way of configuring anything that involves humans, prone to obscure errors due to the non-deterministic nature of such config. If conan were to look in project/.conan before proceeding onto looking into CONAN_USER_HOME, this would JustWork upon cloning the  project git repo.

**Comment by memsharded** [comment]
> should work simultaneously on windows, mac and linux for an entire team

The cache is not designed for concurrency, in case you are thinking about sharing it in a shared folder or something.

> Also, environmental variables are about the worst way of configuring anything that involves humans, prone to obscure errors due to the non-deterministic nature of such config. If conan were to look in project/.conan before proceeding onto looking into CONAN_USER_HOME, this would JustWork upon cloning the project git repo.

And what is the "project" folder? the one that contains the conanfile.py? Not possible, there are projects with several conanfiles. Also other projects that put the conanfile in a dedicated subfolder. The current folder? Not possible either, because commands are very often issued in different locations of the project, in the "build" subfolder or something.

Of course there are other issues that comes from sharing the packages storage, while the configuration is separate. For example, one given project is not supposed to be using latest ``pkg/3.0`` version, because it is not defined in its remotes. But it happens that a different project that lives on the edge, defines the remote that contains ``pkg/3.0``, and fetches that into the shared storage, making it available to all the other projects. That might happen too for even more important things as permissions. Some project users might not have credentials to fetch from some repos, but still be getting those packages because they were put there by another project.

**Comment by memsharded** [comment]
> Being able to specify things like settings.yml, remotes.txt and profiles inside the project tree would address these usability issues.

This brings also other problems. Those things like settings.yml, remotes.txt,  profiles are shared and used by all the packages that are used in different applications. Most of the times, each package will be contained in its own git repo. How would you share the same set of settings.yml, remotes.txt, profiles, for all the packages? Will you put a copy of those things in every git repo of every package? Then it will be a maintenance nightmare, each time you do a change in configuration, profiles. Furthermore, changes in the repos, do typically fire a CI build of that package, and in Conan terms, it will create a new ``recipe revision`` if using things like the ``scm`` tracking.

There are strong reasons why putting these things in git repos (the same repo as the source code) is not the best approach, and the reason why things like ``conan config install`` to be able to sync all the configuration from an external git repo or zip exist.

**Comment by tthef** [comment]
> This brings also other problems. Those things like settings.yml, remotes.txt, profiles are shared and used by all the packages that are used in different applications.

Yes, and that sharing is precisely the problem.

> Most of the times, each package will be contained in its own git repo. How would you share the same set of settings.yml, remotes.txt, profiles, for all the packages? Will you put a copy of those things in every git repo of every package? Then it will be a maintenance nightmare, each time you do a change in configuration, profiles.

The local config can be delivered in any number of ways, it needn't be part of a git checkout, this is no more an issue than it is just now, it is not whether multiple configs are need (they are), but how these can be sensibly managed. The problem with running 'conan config install' on project-specific config is that it changes config for every single project on that box, it just doesn't scale. It's like git only having a global config file that you would have to edit every time you switch between different repos so that you pull from the correct remote.

Package signatures are already differentiated by the settings, so different flavours of package built with different configs happily co-exist (this is one of the nice things about Conan), so there is no technical hurdle here. The project folder would be $(pwd); if ./.conan exists anything there overrides the global defaults, if it doesn't exist, no harm done.

(Just to be clear, I am not suggesting the cache be shared between multiple users, I am asking for a better single developer workflow when working with multiple projects and configs.)

**Comment by memsharded** [comment]
> The local config can be delivered in any number of ways, it needn't be part of a git checkout, this is no more an issue than it is just now, it is not whether multiple configs are need (they are), but how these can be sensibly managed. The problem with running 'conan config install' on project-specific config is that it changes config for every single project on that box, it just doesn't scale. 

No, it doesnt. It applies only to the current CONAN_USER_HOME. If you have defined the env-var to point to the project, it will apply that configuration to that one only, not to every other Conan user home in your machine.

The solution scales. There are many big enterprise that manage hundreds of Conan packages for many configurations and projects using this ``conan config install`` successfully.

> It's like git only having a global config file that you would have to edit every time you switch between different repos so that you pull from the correct remote.

You can have as many ``config install`` configurations as you want. You dont have to edit it every time you switch between different repos, you only have to execute ``conan config install`` once when you first start a project in your machine. Then every project will have its own configuration, with its own remotes, settings, profile, and everything.

But what is very important and this discussion doesn't address yet, is how this feature would play with the most common scenario, that is having multiple git repos, and these repos need to use the same configuration of remotes, profiles, settings, etc. It really doesn't make sense to copy and duplicate it inside every repo.


> The project folder would be $(pwd); if ./.conan

This breaks with the very basic flow of:

```
git clone <some_repo>
cd some_repo
mkdir build && cd build
conan install .. 
```

**Comment by tthef** [comment]
> You can have as many `config install` configurations as you want. You dont have to edit it every time you switch between different repos, you only have to execute `conan config install` once when you first start a project in your machine. Then every project will have its own configuration, with its own remotes, settings, profile, and everything.

Having to manually run 'conan install config' every time you pull, switch branches or change to a different project is incredibly fragile, using different CONAN_USER_HOME for each project doesn't work for dependent projects, and any configuration system that relies on environmental variables is broken by design.

> It really doesn't make sense to copy and duplicate it inside every repo.

I think you misunderstood -- I am not suggesting the global config should be replaced with a per-project one, but that it should be possible to override parts of the global config from inside the project, so that the project can pin down settings that must not change (such as a compiler version). Whether such configuration is part of the git checkout, or is in a git submodule, or is provided some other way is beside the point.

> This breaks with the very basic flow of:
> 
> ```
> git clone <some_repo>
> cd some_repo
> mkdir build && cd build
> conan install .. 
> ```

I don't see what exactly would break here. Are you worried about locating the project config? Conan commands that operate on a checkout require to explicitly pass the directory in which to find conanfile.py, so locating any (optional) config files seems pretty straight forward if they are under that directory.

**Comment by memsharded** [comment]
> Having to manually run 'conan install config' every time you pull, switch branches or change to a different project is incredibly fragile, using different CONAN_USER_HOME for each project doesn't work for dependent projects, 

You don't need to run ``conan install config`` every time you pull a new repo. You just need to define the "project" (CONAN_USER_HOME) you are working on. The same project will be valid for all the packages and pulls that you do, you only need to change it when you are switching projects, which surely is not something to do every 5 minutes, and the number of projects or different configurations to work with by definition should be order of magnitude smaller than the number of packages and repos being used.

> and any configuration system that relies on environmental variables is broken by design.

The configuration system does not rely on environment variables. Everything is conf files, yaml files, ini files, etc. Actually, most of the previous env-vars is being removed from Conan with the new ``[conf]``. The one and only env-var that needs to be defined is where to find that configuration, that is the CONAN_USER_HOME. 

I guess that most OSs are broken by design then, because they rely on configuration like the PATH env-var to work. Much the same with most CI systems, that really need to configure things with env-vars.


> I think you misunderstood -- I am not suggesting the global config should be replaced with a per-project one, but that it should be possible to override parts of the global config from inside the project, so that the project can pin down settings that must not change (such as a compiler version).

Configuration files like ``settings.yml`` do not merge (we have considered that, but it is too complicated and fragile). So if you try to put a custom ``settings.yml`` in your current repo, it should completely replace the global one. And custom ``settings.yml`` is a very common thing, that clearly doesn't scale putting it in the sources repo.

The ``profiles`` do not merge either. If you have a ``profile_win`` profile in your current repo, it would completely replace a ``profile_win`` in the global location.

The ``remotes`` do not merge either. When some remotes are defined with ``conan config install``, the previous remotes are removed. This is one of the most common and requested behaviors: to remove existing remotes, and that can only be done assuming that the incoming definition of remotes replaces the previous one, not just add new remotes to it.

So the 3 most important parts of the configuration do not merge, they just replace the global one. So these 3 things put in source repos would have to be completely duplicated and maintained over time for every little modification you do to them, in all source repos for all your sources packages. If you end up with hundreds of git repos as many of our users, changing a settings.yml, a profile, or the remotes definition, will require you to edit and commit changes to hundreds of git repos.

> I don't see what exactly would break here. Are you worried about locating the project config? Conan commands that operate on a checkout require to explicitly pass the directory in which to find conanfile.py, so locating any (optional) config files seems pretty straight forward if they are under that directory.

The assumption that you can put the config files besides the conanfile.py doesn't scale either. There will be tons of users that would say:

- I have 2 conanfile.py in this repo, but it is just 1 repo, configuration should be per repo(project), not per conanfile.
- I have my conanfile.py in the root folder of my repo, but I am not going to put 15 different files (different profiles, etc) in the root of the repo, it would make it very dirty.

Then we would be requested a ``--project-config-folder`` argument to the command line to be able to specify where the local project config is, and this would be an argument to absolutely all Conan commands, further cluttering the UI.

**Comment by tthef** [comment]
> You don't need to run `conan install config` every time you pull a new repo. You just need to define the "project" (CONAN_USER_HOME) you are working on. The same project will be valid for all the packages and pulls that you do, you only need to change it when you are switching projects, which surely is not something to do every 5 minutes, and the number of projects or different configurations to work with by definition should be order of magnitude smaller than the number of packages and repos being used.

I do this often enough to be a problem, the per-project configuration changes infrequently, but switching between projects with different profile/setting/remotes sets happens much more often (different apps at different stages of dev cycle, LTS, etc.). Running builds with the wrong profile set will often not show until run time on specific targets, or generates errors that are unintuitive for members of the team who are merely consumers of the conan packages.

Environmental variables are ephemeral, you re-open a terminal window and your config is gone, relying on them doesn't scale to a team of people across different operating systems. The only workaround that currently scales to a team is to wrap every conan command so that its proceeded by 'conan config install'.

> Configuration files like `settings.yml` do not merge (we have considered that, but it is too complicated and fragile).

You don't have to merge them, you can just look for the complete files in multiple locations in an defined order of priority. Tools that have a config generally do this, usually having global, per user and per project configuration files. The fact that you can call 'conan config install' repeatedly with different configs shows that there is no technical reason why the config needs to be global-only.

Anyway, I can see that this works well enough for you guys not want to address this, so I am going to close this ticket.

**Comment by sschuberth** [comment]
This is to chime in that we'd also need per-project configuration (of remotes), just like Maven, NPM and several other build systems / package managers do support. We have a hard requirement that projects need to build out-of-the-box on a "naked" machine after a plain `git clone`, *without* any user / global configuration to be applied first. All information to build the project should be self-contained in the Git repository.

**Comment by memsharded** [comment]
@sschuberth 

You could do a ``conan config install`` of a folder inside the git repo:

```bash
$ git clone .... project
$ conan config install project/conan_config
```

**Comment by sschuberth** [comment]
Yes, thanks, that's the work-around we're [trying to implement](https://github.com/oss-review-toolkit/ort/issues/4312#issuecomment-888330638) now.
