### ISSUE TITLE
[question] How to packaging local existing binaries?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9149]
As in the doc: https://github.com/conan-io/docs/blob/master/creating_packages/existing_binaries.rst

It downloads binaries.
How to package local binaries?

**Comment by playgithub** [comment]
Just put the binaries there will do.

**Comment by memsharded** [comment]
For the record, the command to package local binaries is ``conan export-pkg``. It doesn't download anything, just take what is in the folder and package it.

**Comment by playgithub** [comment]
> For the record, the command to package local binaries is `conan export-pkg`. It doesn't download anything, just take what is in the folder and package it.

As in the doc, `conan create .` will pakcage local existing binaries, right? Is `conan export-pkg` equivalant?
```
class HelloConan(ConanFile):
    name = "hello"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"

    def package(self):
        self.copy("*")

    def package_info(self):
        self.cpp_info.libs = self.collect_libs()
```

**Comment by memsharded** [comment]
``conan create`` with that recipe will not package anything at all, unless you add a ``exports_source="*"`` or something like that, but that would be a bad idea, because you will make the package unnecessarily larger and waste storage.

For packaging local binaries, you need to use the ``conan export-pkg``. It also creates a package, but instead of creating it from the ``build()`` result, it doesn't have a ``build()`` method ,and it will copy binaries and files directly from your user folder.
