### ISSUE TITLE
[question] Time spend in `conan export`

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#9167]
Hi,

in our CI job, we're exporting ~170 recipes to a clean cache.
On Linux machines, this exports takes  ~1 minute, however on Windows machines (with short paths enabled) the process can take up to 10 minutes (sometimes it's quicker though, but always way slower that the Linux machines).

Is that something to be expected? Why the huge discrepancy? Or do you expect some issues (maybe misconfigurations) on our side?

And will this still be relevant for Conan 2.0?
(For me it's nothing urgent, but really wondering)

**Comment by uilianries** [comment]
Hello @KerstinKeller! 

> Is that something to be expected? Why the huge discrepancy?

Excellent question, it's something excepted indeed, but not because of Conan, but because the filesystem and OS used. As export command demands copy operation, on Windows it takes much longer than on Linux, naturally. Also, maybe you are running anti-virus or another service which scan files/directories and increases even more your time. Comparing Linux vs Windows copying time is not something new, [here](https://superuser.com/questions/1124472/why-is-linux-30x-faster-than-windows-10-in-copying-files) you can find more about it.

**Comment by aleksa2808** [comment]
@KerstinKeller probably not relevant for the Win/Linux issue, but out of curiosity are you calling the export commands separately from the CLI? In our setup I was doing just that and was only recently dumbfounded by the fact that the `conan` no-op command takes ~0.5s because of the Python imports. Upon switching to the (unstable) Conan API the entire exporting+locking CI step was sped up tremendously (~1m -> few secs; around 30-40 packages with multiple versions).

**Comment by KerstinKeller** [comment]
@aleksa2808 yes we are invoking `conan export` from CLI. Way back we started with the API, but heard it is unsupported.
And yes, it seems to me that the overhead is huge. I will try invoking everything directly. 
And how exactly are you using the api? `conans.client.cmd.export`, or even something higher level? (e.g. `conans.client.conan_api`)?

**Comment by aleksa2808** [comment]
```python
from conans.client.conan_api import Conan

conan_api, _, _ = Conan.factory()
conan_api.export("path/to/recipe/folder", "mypackage", "1.0.0", "user", "channel")
```
\+ similar thing for locking and other operations

Last I heard, the API is officially unstable, but, given the speedup that it gives us, being careful when changing versions is very much worth it.

**Comment by KerstinKeller** [comment]
Ok, wow. Conan export is now 5s on Linux, and 43s on Windows. Still a huge difference, which in my opinion can't entirely be explained by just the file copying. But these are times that I can easily live with. (Hehe at least for now, let's see how many recipes we might have to deal with in the future).

Are there any plans in making the Python API stable for Conan 2.0?

**Comment by memsharded** [comment]
Yes, the Python api will be released in Conan 2, if not directly in Conan 2.0, as soon as possible in Conan 2.X. Initially it will be experimental but documented, and then it will be stabilized as soon as usage and feedback allows it.

**Comment by KerstinKeller** [comment]
After reading #9173, I wondered if this could be connected to this issue in general. And (after switching from `conan export` to using the python API) I added some timing calls, for each `conan_api.export` as we iterate through all our recipes, starting with a clean cache, Y-Axis takes the time spend in `conan_api.export` in seconds.

On Windows: (using short paths)
![image](https://user-images.githubusercontent.com/13848742/123918790-81b58700-d984-11eb-8da4-2d16635b38f0.png)

On Linux:
![image](https://user-images.githubusercontent.com/13848742/123919716-8169bb80-d985-11eb-8588-b8e15ab04e98.png)

Note, Linux is about 10x as fast. Recipes with no `conandata.yml` are a tad faster (probably less file copies). 
However what is most interesting, the export times for recipes get slower, as the cache is populated, both on Windows and Linux. Between initial export to empty cache and to a cache of about 160 recipes, it gets about 2x slower.

I just wanted to share these insights with you, and no clue if it will be relevant at all for the new Cache layout.

**Comment by memsharded** [comment]
#9173 was because the user had the cache below the folder being exported. When they moved the cache to another location, the issue was solved.

It is true that at the moment, the export does internally a ``search_recipes`` to take into account possible casing conflicts. As this is no longer an issue in the 2.0 cache, it will be removed (it has already been done in develop2: https://github.com/conan-io/conan/pull/9175/files). So we should expect O(1) export time in Conan 2.0
