### ISSUE TITLE
How to change include path for Visual Studio Conan?

### ISSUE THREAD

**Issue by r1d1shka** [conan-io/conan#9201]
I am trying to create a cross platform application (Linux/Windows), which uses third party dependencies, like `jsoncpp`. On Linux I use `cmake`, on Windows I use `Visual Studio` + `Conan`. There is a problem that the paths to cpp headers differ on different operating systems. On Linux I include jsoncpp like this:

```
#include <jsoncpp/json/config.h>
#include <jsoncpp/json/value.h>
```
But on Windows I have to use other ways:

```
#include <json/config.h>
#include <json/value.h>
```
On Windows, Conan installs headers along the way (there is no jsoncpp prefix):

`C:\Users\User\.conan\data\jsoncpp\1.9.0\theirix\stable\package\3fb49604f9c2f729b85ba3115852006824e72cab\include\json`

Content of conaninfo.txt file:

```
[requires]
jsoncpp/1.9.0@theirix/stable
[generators]
MSBuildDeps
```
There is a way to use include paths, like on Linux? Without such ugly code:

```
#ifdef __linux__
#include <jsoncpp/json/config.h>
#include <jsoncpp/json/value.h>
#else
#include <json/config.h>
#include <json/value.h>
#endif
```

**Comment by memsharded** [comment]
Hi @r1d1shka 

It seems that you are using a legacy package from ``jsoncpp\1.9.0\theirix\stable``. I'd strongly suggest if you are using packages from ConanCenter, to use the packages without user channel: ``jsoncpp/1.9.4`` from https://conan.io/center/jsoncpp

But in any case, it is not possible to change the folder, the package has been created that way, with those folders. The only way to achieve that would be to change the package recipe and recompile the packages. But that will not be accepted, because the upstream canonical way of includes is doing the ``#include "json/json.hpp"``, without the extra folder. Check in https://github.com/open-source-parsers/jsoncpp/blob/master/example/streamWrite/streamWrite.cpp, for example. The Conan packages try to use whatever the original library is doing. 

So my recommendation would be:
- Use Conan also in Linux
- Fix what you are doing in Linux with CMake, because it seems that is the thing adding the extra ``jsoncpp`` that should be removed to match the way in https://github.com/open-source-parsers/jsoncpp
