### ISSUE TITLE
[question] Strange behavior of `self.copy` excludes patterns

### ISSUE THREAD

**Issue by t7wakim** [conan-io/conan#9208]
Hi, 
I have a few questions/concerns about how the `copy` method excludes files.

1. If I want to exclude all hidden files (i.e., using the `.*` pattern) no files are packaged at all (i.e., all files are excluded). Is this a bug or by design?
2. If I want to exclude a particular file (e.g., `test.txt`) from the `src` copy directory and also from all subdirectories of `src`, it is required to set 2 patterns for each file: `['test.txt', '*/'test.txt']`. Is this how it should work? Shouldn't the pattern not depend on the file path?

Thanks

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by AbrilRBS** [comment]
Sorry that this issue got lost thru the cracks, we apologize. I'm answering the question here just for posterity in case anyone ever stumbles upon it, I hope you were able to eventually figure this out.

You actually found a bug in how we handle the `.` dir for exclusions. This will be fixed in 2.1

For 2, yes! You need to specify both - that's the easier way :)

Again, thanks a lot for the report, we appreciate it even if the issue got lost along the way!

**Comment by memsharded** [comment]
Fixed by https://github.com/conan-io/conan/pull/15349, will be in next 2.1, thanks again!
