### ISSUE TITLE
ERROR: The revision field, must contain only letters and numbers with a length between 1 and 51

### ISSUE THREAD

**Issue by lohitgujjar** [conan-io/conan#9227]
Hello Everyone,
I am facing an issue when i try to use: lib/1.0@conan/stable#RREV:PACKAGE_ID (doc reference: [Versioning).](https://docs.conan.io/en/1.34/versioning/revisions.html) 

**Error: : The revision field, must contain only letters and numbers with a length between 1 and 51**

i want to use a specific version of binary from the artifactory. hence i am providing the filter till package_id.
When i use :  lib/1.0@conan/stable#RREV things work just fine. But the error is encountered when the package_is is used.

I am new to conan. Please help me in solving the issue.

**Comment by memsharded** [comment]
Hi @lohitgujjar 

This is the same error reported almost at the same time in: https://github.com/conan-io/conan/issues/9224, please check the response there, I am closing this issue as duplicate.

Just quick question: how are you learning Conan? It is curious these 2 same issues at the same time, is it that you are doing a course somewhere, or someone shared a blog post or something that indicates this is possible? Because this cannot be found in our docs, for sure.

**Comment by lohitgujjar** [comment]
Hello @memsharded ,
Thankyou for the reply. I am referring to the conan documentation in : [conan documantation](https://docs.conan.io/en/latest/versioning/revisions.html). If you check under Package Revisions section you will find the syntax i had mentioned in my question (lib/1.0@conan/stable#RREV:PACKAGE_ID)

**Comment by memsharded** [comment]
Thanks for the clarification @lohitgujjar 

Yes, that page is introducing and explaining the revisions format, but I agree maybe it is not fully clear from that page how to use them, and where can they be defined and where not. As for Conan 2.0 the revisions will be fully integrated and always in use, we will have to rewrite the docs, and this will be more clear.
