### ISSUE TITLE
[question] How to get recipe name? How to provide an option value only for created recipe?

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#9264]
We have a CI process that validate all pushes via a command of the form

          conan create  \
          -o ${{ recipe_name }}:build_tests=True -s compiler.cppstd=${{ matrix.cppstd }}  \
          conan/

We have a problem making it generic though, because of the options that are present on the recipe, but not on the test packages.
In this case, this is the `build_tests` option.

If we do not scope the option with the recipe name, the `conan create` call fails complaining that the option is not present on the test package. We are not aware of a way to solve that without prefixing the option with the actual `name` from the `conanfile.py` of the root package (Is there an alternative?)

At the same time, we cannot find a "compact" way to retrive the `name` field from the recipe, in order to make the prefix solution generic (at the moment, we have to touch every specific workflow file to change this value).
(As read elsewhere, the recipe name might be derived from other places, but that would be just a convention, and since there is an explicit `name` field we might as well use it).

Thank you for reading!

**Comment by AbrilRBS** [comment]
Sorry that this issue fell thru the cracks and never got an answer, hopefully you were able to figure something out, I'll answer in case anyone finds this issue again thru googling:

[Conan 1](https://docs.conan.io/1/reference/profiles.html#package-settings-and-env-vars) and [Conan 2](https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns) support "scoping" of configurations using the `&:` syntax, which means "the created package", so that `-o"&:my_option=True"` would only add the option to the created package, regardless of its name
