### ISSUE TITLE
conan create: can I run all test if --build=missing

### ISSUE THREAD

**Issue by stefaneicher** [conan-io/conan#9275]
We have multiple conan recipes/components and a big dependency tree between the recipes/components.

to avoid having to maintain the build order of the flattened dependency tree in the CI build script we run 

conan export a
conan export b
conan export c
..
conan export main

and then

conan create main --build=missing

Thus we build all packages/components a,b,c,..main in the correct order.

But this will only test_package of main. But I also would like to run the test_package of a,b,c,...

I hoped there was a thing like:

conan create main --build=missing_with_tests

**What would you recommend me to do?**

Invent my own solution by running run "conan info main" resolve the dependency tree and run conan creates from there.
_I want to avoid inventing my own stuff._

**Comment by lasote** [comment]
Hi, the problem is that the test_package folder/mechanism is no exported to the Conan cache so you cannot run it once it is there.

I recommend to take a look at the [lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles.html) feature. You can generate a lockfile for your dependency tree and you can obtain also the order you have to follow to build the packages. So your process could be automatic with little code.

**Comment by memsharded** [comment]
I'd like to add to this question:

``test_package`` is a very basic check that the package is correct, it contains the headers, the libs, etc.
Any real usage of the package, by their consumer should be a better check of correctness of the package than actually running ``test_package``.

Otherwise, yes, the "distributed" solution is necessary:

- Getting the build-order with Conan commands of the graph (better use lockfiles to guarantee nothing changes in between)
- Iterate the elements of the graph, checking out the source code/git clone at the right commit, then creating the package there

Probably this is a bit overkill if ``--build=missing`` works and it is not necessary to distribute the build.
