### ISSUE TITLE
[bug] no such file error when renaming files in import

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan#9291]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 x64
  * Compiler+version: N/A
  * Conan version: 1.38.0
  * Python version: 3.7.8

### Steps to reproduce (Include if Applicable)
in the import function do a self.copy and then rename the file to something else

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
Traceback (most recent call last):
  File "C:\Program Files\Python\Python37\site-packages\conans\client\command.py", line 2213, in run
    method(args[0][1:])
  File "C:\Program Files\Python\Python37\site-packages\conans\client\command.py", line 532, in install
    lockfile_out=args.lockfile_out)
  File "C:\Program Files\Python\Python37\site-packages\conans\client\conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "C:\Program Files\Python\Python37\site-packages\conans\client\conan_api.py", line 614, in install
    recorder=recorder)
  File "C:\Program Files\Python\Python37\site-packages\conans\client\manager.py", line 125, in deps_install
    run_imports(conanfile)
  File "C:\Program Files\Python\Python37\site-packages\conans\client\importer.py", line 85, in run_imports
    _report_save_manifest(copied_files, import_output, conanfile.imports_folder, IMPORTS_MANIFESTS)
  File "C:\Program Files\Python\Python37\site-packages\conans\client\importer.py", line 60, in _report_save_manifest
    file_dict[f] = md5sum(abs_path)
  File "C:\Program Files\Python\Python37\site-packages\conans\util\files.py", line 145, in md5sum
    return _generic_algorithm_sum(file_path, "md5")
  File "C:\Program Files\Python\Python37\site-packages\conans\util\files.py", line 158, in _generic_algorithm_sum
    with open(file_path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\dev\\tmp\\out\\conan\\Debug\\x64\\lib\\libssld.lib'
```
The file that it complains about was copied using `self.copy` in the import function of the conanfile.py and then renamed to get rid of the superfluous 'd' suffix (which is a ridiculously stupid idea to do in the first place).
The file needs to be renamed as the build system requires the library name to be the same for all configurations.

**Comment by memsharded** [comment]
Hi @Sil3ntStorm 

This reads more like an unsupported feature rather than a bug:

- imports are intended and designed to import file, not to manipulate them after importing them
- The generated ``conan_imports_manifest.txt`` manifest is necessary to implement the ``conan imports --undo`` operation, something that was demanded by users long time ago.
- If the files are manipulated after being imported, it is impossible to keep track of those files in the manifest, and that would break the ``undo`` operation.
- The ``undo`` operation is also needed while building in the cache, to make sure that temporarily imported files are cleaned and not accidentally repackaged.

> The file that it complains about was copied using self.copy in the import function of the conanfile.py and then renamed to get rid of the superfluous 'd' suffix (which is a ridiculously stupid idea to do in the first place).

Yes, I agree, but this is something cooked into many build system scripts, and typically Conan package recipe authors tend to do the minimal necessary changes to build scripts.

>The file needs to be renamed as the build system requires the library name to be the same for all configurations.

This is something that the Conan generated files, via a generator like ``CMakeDeps`` or a custom generator for any build system will take care of, passing the information to the consumer build system, so they don't need to figure out or hardcode anything about the dependencies, to avoid breakage when something changes upstream (like the library name, not that uncommon). I'd recommend trying using generators if possible.

**Comment by Sil3ntStorm** [comment]
The generator in question is a custom one. However the (meta) build system in question does not support specifying to link to 'foo.lib' in Release mode and 'food.lib' in Debug mode. It does allow to specify different library directories however. That works great and is all good as long as you don't have a dependency using an atrocious naming scheme with different library names for different configurations.
However now the situation is that the library required uses a different name for the library files, which causes lots of headaches. I figured since I can do imports and even script things in conan I could simply rename the file and be good, but it seems that is not the case.
I guess the next best solution would be to do a custom recipe for the dependency and just rename the file there before packaging, which I guess should work. That however means maintenance work for the recipe rather than simply using what's already there.
I don't think generators can rename the file, and even if they could, I foresee issues with multiple runs and sort of dirty states of the build folder.
No matter what, the file name needs to be sanitized at some stage, be it packaging, import, or generator. The best option would be the import stage as it would be the least effort and avoid special handling in the generator as well as avoiding a custom recipe. Ultimately though I don't care where it gets sanitized, it just needs to get done.

**Comment by memsharded** [comment]
``imports()`` and ``self.copy()`` have been removed in 2.0, closing this ticket as outdated.
