### ISSUE TITLE
[feature] conanfile.txt includes

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#9294]
We sometimes combine our projects by putting together source folders from different repositories like this:
* /
  * source  
    * main-project
    * shared-lib-A
    * shared-lib-B

Each shared lib has its own dependencies and is used in multiple other projects. Now instead of listing the dependencies of the shared libs in a "master" conanfile.txt, I'd like to automatically generate a combined conanfile.txt for the whole project. I could imagine using something like an include function that might look like this:

	include(source/shared-lib-A/conanfile.txt)
	include(source/shared-lib-B/conanfile.txt)

	[requires]
	main-dependency/1.0

Is there a way to already achieve this (defining requirements in multiple places) or is this something you might consider as a feature?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @fschoenm 

This is not possible as a built-in feature right now, and at the moment it seems it is a bit too specific use case to be implemented as built-in. Probably a good case for the modular custom user commands in Conan 2.0.

Probably if I had to implement this logic right now, I would go for this approach:
- Convert the projects ``conanfile.txt`` to simple ``conanfile.py``. As they are consumers, no need to implement build(), package() or package_info(), but still this could already imply some benefits, like the new ``layout()`` feature that helps to keep projects cleaner more easily by defining project layouts.
- Use the ``conandata.yml`` of each one to define the variable data that you want to aggregate, if it is only the ``requires``, have a ``requires`` section in your ``conandata.yml``. Use it in your ``requirements()`` method of each recipe.
- Write a project ``conanfile.py`` file, that loads the ``conandata.yml`` of each specified subfolder (you can make this really smart and dynamic, for example, scanning child folders, looking for all conandata.yml. This will allow to work without any changes at all when adding or removing child folders). Compose the data in the ``requirements()`` method to define your ``self.requires``.

I don't know if this sounds too complicated, but it might be way simpler than it seems, it might not disrupt the usage (the consumption of regular projects is still ``conan install .`` no need to change anything), and it might also even open interesting possibilities as improving the project layouts.

**Comment by fschoenm** [comment]
Hi @memsharded,

Thanks for the recommendations. I don't know if I agree that it's a very specific use case. I never quite understood why I cannot specify dependencies for each part/library of my project independently and instead have to specify them all in a kind of of "global" conanfile. But maybe I just have a different perspective onto that issue than you.

(One alternative that would make sense to me is to create conan packages for all my shared libs but that just is something I don't want to do because it would make the development workflow too inflexibel for our taste. For example I would have to give version numbers to each build I'd like to use and it would make developing/debugging more complicated.)

I actually implemented a feature like this today by using a central `conanfile.py` and collecting the `conanfile.txt` files from my sub-projects and parse and compose the requirements (and options) with the `ConanFileTextLoader` from the conan API. It does exactly what I want and works for now.

I'm off work now so I have to look into your recommendations later, maybe I'll find a way to improve my implementation.

**Comment by obsgolem** [comment]
Hey @fschoenm, my team is working on a project with very similar requirements. If you would be willing/able to share your implementation of that, that would be really cool. 

+1 for this entire issue, we basically have a bunch of independent plugins which all need to be built as part of the larger project build for a variety of reasons.

**Comment by fschoenm** [comment]
@obsgolem Sure, it's a super simple implementation (only covering requirements and options right now):

    import glob
    import os

    from conans import ConanFile
    from conans.client.loader import ConanFileTextLoader
    from conans.model.options import OptionsValues

    class Conan(ConanFile):

        @property
        def conanfiles(self):
            base_path = os.path.dirname(__file__)
            return list(glob.glob("{base_path}/source/*/conanfile.txt".format(base_path=base_path)))

        def requirements(self):
            options_str = ""

            for file in self.conanfiles:
                loader = ConanFileTextLoader(open(file, 'r').read())
                options_str = options_str + "\n" + loader.options
                for req in loader.requirements:
                    self.requires(req)

            self.options.values = OptionsValues.loads(options_str)

**Comment by memsharded** [comment]
I would like to highlight some potential problems and complexities that will appear down the rabbit hole with this approach, if this is built-in (not saying for you, but other users that start to use this potential feature):

- The priorities. If the different conanfile.txt in the different subfolders declare different dependencies, what would be the final used one. In an ``include()`` paradigm it should be the last one, but that means that when writing such a root conanfile.txt, order is important and must be carefully selected. Same applies to ``[options]`` defined in the different conanfile.txt
- ``requires`` can compose well, but what would be the behavior for other things declared in ``conanfile.txt`` files? Lets say that the main/conanfile contains a ``build_requires="cmake/1.2"`` because that subproject uses cmake as a build system, and shared-liba/conanfile contains a ``build_requires="meson/2.3"``, because that subproject uses meson as a build system. Probably you don't have this setup, but other users will, and then we will have a problem.
- Relationships between subprojects. Many users will declare that they have relative dependencies between such subprojects, like the main-project depends on shared-liba, and they would ask Conan to take this into account somewhere to define priorities, or even conflict resolution, and this would also be impossible to provide with this approach.

These issues are sources in trying to manage together some entities that look like packages, and want to manage together as packages, but without actually creating packages. So I would like to suggest a different approach that could also help to address your use case, and would solve the above issues:

- Use ``conanfile.py`` for the subprojects. No need that they implement ``build()``, ``package()`` methods if you don't want.
- Create the root ``conanfile.py`` with regular ``requires`` to such subprojects, lets say in "develop" version.
- Put the different packages in ``editable`` mode.
- ``conan install`` the root conanfile.


This is a unittest that implement this:

```python
def test_editables_project():
    c = TestClient()
    c.save({"conanfile.py": GenConanfile().with_requires("app1/develop", "app2/develop")
               .with_settings("os", "compiler", "arch", "build_type"),
            "app1/conanfile.py": GenConanfile().with_requires("liba/develop"),
            "app2/conanfile.py": GenConanfile().with_requires("libb/develop"),
            "liba/conanfile.py": GenConanfile().with_requires("libb/develop"),
            "libb/conanfile.py": GenConanfile()})
    c.run("editable add app1 app1/develop@")
    c.run("editable add app2 app2/develop@")
    c.run("editable add liba liba/develop@")
    c.run("editable add libb libb/develop@")

    c.run("install . -g CMakeDeps")
    assert "app1/develop from user folder - Editable" in c.out
    assert "app2/develop from user folder - Editable" in c.out
    assert "liba/develop from user folder - Editable" in c.out
    assert "libb/develop from user folder - Editable" in c.out
```

This would have a few advantages, lik natural dependency resolution, including relative ordering of dependencies between subprojects. Conflict management, etc. This approach will be valid also for dependencies, if at some point you want to edit together with the rest of the project one or several dependencies packages

**Comment by DoDoENT** [comment]
I just had the need for composing `conanfile.txt` files where one submodule has some Conan dependencies on its own and those dependencies need to be expanded with dependencies of the main module.
This happened on a project that used git submodules and binary zips exclusively for their dependencies and now I'm in the process of replacing binary zips with Conan, while still keeping git submodule dependencies.

The solution from @fschoenm works OK for me, but I agree with @memsharded - in the general case (i.e. if built-in support was added), it would make some things very complicated which are not needed for situations like we have here...

Hopefully, this all will get easier with Conan's 2.0 custom commands...

**Comment by memsharded** [comment]
I think that Conan 2.0 custom commands can definitely help filling the gap of the missing ``workspace`` feature. For example, implementing a custom command that walks the current folder, and for every folder, based on some convention calls ``conan editable add`` is basically all you need, something like:

```
conan mycommand .
conan install .
```

Recall that Conan 2.0 has also some improvements for editables, for example, it can do the orchestrated, ordered build. ``conan install . --build=editable`` can go in the right order to every subproject, doing the local build (that can be fast, will be incremental)

**Comment by memsharded** [comment]
Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.

Also the above mentioned new features can help a lot with this, which wouldn't be planned at the moment.
So closing this as both not planned and outdated, please create new tickets with the new features feedback as needed.
