### ISSUE TITLE
[question] cmake_paths generator doesn't contain paths to build_requires packages when using --profile:host and --profile:build?

### ISSUE THREAD

**Issue by nichmj01** [conan-io/conan#9311]
I'm using conan 1.38.0 and trying to cross-compile from Windows to Android. The android-ndk/r21e package on conan-center doesn't like the old style single profile using arch_build and os_build so I switched to using the newer separate host and build profiles.

I'm using cmake and have a set of cmake files that are shared among all my projects. I packaged these up into a conan package (my-cmake-tools) and reference the package using build_requires. 

Using the old style profile, the cmake_paths generator adds the path to my-cmake-tools from conan cache in the generated conan_paths.cmake file; ie the line `set(CONAN_MY-CMAKE-TOOLS_ROOT {conan cache path})` is in the conan_paths.cmake. This lets the code being built find my-cmake-tools as I use find_package to locate them (the cmake files are distributed in the conan package)

If I use the newer style split profile, the generated conan_paths.cmake does not have this line. In order to make this line appear I have to make the my-cmake-tools package a requires dependency and not a build_requires dependency (which seems less correct?)

Is this a bug or an intentional deviation between the old profile and newer profile set up?

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
This is expected behavior by default: "build_requires" in the build context are designed for build tools: cmake, meson, a compiler, etc. so by default they will not be available by some generators (the "legacy" generators, like ``cmake_paths``). We are working on providing these new functionalities in the new ``conan.tools`` one, and you can see features like this: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html#build-context-activated, to handle these cases. However, this won't directly apply for reusing build scripts only without doing a ``find_package()``. I suggest:

- Give it a try with this feature, and CMakeDeps generator, lets see if you can use ``find_package()`` to your package containing scripts, and those scripts are loaded and activated so you can use it.
- Lets see if this works, and then we could discuss if we want to give it an interface for locating them different to ``find_package`` and more in the line of ``cmake_paths``.

**Comment by memsharded** [comment]
This feature is connected to this Tribe discussion about "package_types" for Conan 2.0. https://github.com/conan-io/tribe/pull/27. The "build_scripts" package type is a suggestion there, and it would make sense to automate things based on this package type if this is a common case.

**Comment by nichmj01** [comment]
My understanding of your answer is that `--profile` alone and combining `--profile:build` and `--profile:host` are not equivalent. In the latter case, the build_requires packages are not provided to the generators by default. CMakeDeps build_context_activated  let's me specify build_requires packages that should also be generated.

Something like that?

**Comment by nichmj01** [comment]
I was able to to get `CMakeDeps` and `build_context_activated` to work with one hiccup. 

I named the conan package a different name than the cmake package that I look for using find_package.

Example: 
The conan package is called buildtools-cmake which has package layout of:
* package_root
  * cmake/
    * buildtools-config.cmake
    * my-cmake-files/
      * another-file.cmake
  * conaninfo.txt
  * conanmanifest.txt

In the CMakeLists.txt I use `find_package(buildtools)` so I had to add `find_package(buildtools-cmake)` before `find_package(buildtools)` so that cmake would find my buildtools cmake package. 

I have a couple more things to test as I have a couple other weird package configurations that may cause issues.

One question is, can I tell `CMakeDeps` to not generate files for the requires packages? That way I can use `CMakeDeps` to find buildtools and `cmake_paths` for the requires dependencies?

**Comment by memsharded** [comment]
Yes, ``CMakeDeps.set_property(dep, "cmake_find_mode", "none")`` can inhibit the creation of ``dep-config.cmake`` files.

Then, no need to use ``cmake_paths`` (actually, not recommended, it has been removed in 2.0). ``CMakeToolchain`` already implement the paths to the packages so the ``find_`` are able to find the scripts inside the packages.

Sorry that this question was not responded back then, sometimes when there are many tickets and we are very busy, some tickets might fall through the cracks.

As this question is a bit old now, I am going to close it, but don't hesitate to create new tickets for any further question. Thanks!
