### ISSUE TITLE
[question] Revision #0 ?

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan#9317]
I've noticed some of the recipes in my cache have revision zero. It may be when I originally created/exported the recipe, revisions were not enabled. But I expected they would be updated after enabling them. Is there a way to "normalize" this? Will revisions work correctly with these packages?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @rconde01 

No, revisions are not updated, because in fact you could be enabling and disabling revisions, and it would be messy, probably very fragile to keep recomputing all the metadata of the revisions of the cache at each change. 

Those packages with revision "0" are not a problem, because in fact you can obtain packages with revision 0 from a server, even if you have revisions enabled, if those packages were created without revisions. The revision "0" is just another revision, it is designed that both can coexist relatively smoothly. In the server side it is possible to have both revision 0 and full revisions of the same package. And if you have revisions enabled, next time you do a build from source, they will get a new full revision that will overwrite the previous one, no problems expected there.
