### ISSUE TITLE
[question] .conan_link problem

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9346]
After install boost on Windows

.conan\data\boost\1.76.0\_\_\package\a60baac5107ef779a5865836fcb50c28ae423a0b\.conan_link
```
C:\.conan\77dcf7\1
```

Why a new hard-coded path in C: root, it's ugly.
How to change the path in `.conan_link`?
How not to use `.conan_link`?

**Comment by memsharded** [comment]
Because boost has long paths and Windows has a limit of 256 chars in path lengths, so boost needs to be put in a "short folder" like this: ``C:\.conan\77dcf7\1``. If you disable it (for example, removing the ``short_paths = True`` of the boost recipe, it will fail to build due to long paths. Better not change it. You could try to define the env-var ``CONAN_USER_HOME_SHORT=None``, but it is very likely that the build or installation of boost package will fail if you do that.

**Comment by playgithub** [comment]
> Because boost has long paths and Windows has a limit of 256 chars in path lengths, so boost needs to be put in a "short folder" like this: `C:\.conan\77dcf7\1`. If you disable it (for example, removing the `short_paths = True` of the boost recipe, it will fail to build due to long paths. Better not change it. You could try to define the env-var `CONAN_USER_HOME_SHORT=None`, but it is very likely that the build or installation of boost package will fail if you do that.

It's ok.
I've disabled path limit on Windows, is an env-var the only way to disable `.conan_link`?

Thanks

**Comment by memsharded** [comment]
> I've disabled path limit on Windows, is an env-var the only way to disable .conan_link?

No, it is not ok. Many build systems and other tools still have issues with long paths, even if the OS allow long paths. Beware to have failures if you disable it.

Yes, I said it in my response, use ``CONAN_USER_HOME_SHORT=None`` env var.

**Comment by playgithub** [comment]
@memsharded 
After disable path limit on Windows, I have no problem building and using boost with long paths.
What about an option that not use `.conan_link`? And by default if should be off.
