### ISSUE TITLE
[bug] Clone fails if repo contains conandata.yml

### ISSUE THREAD

**Issue by mkacher** [conan-io/conan#9359]
I reproduced an issue in a skeleton project and linked it below. It appears that if a conandata.yml file exists in a project, it will be automagically exported and copied into the source folder. A call to git.clone in the source() method will then fail due to a non-empty folder.

Related discussion: https://github.com/conan-io/conan/issues/8658

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu18.04
  * Compiler+version: NA
  * Conan version: 1.38.0
  * Python version: 3.6.9
  * git version: 2.32.0

### Steps to reproduce (Include if Applicable)
https://github.com/mkacher/conanBug01082021

### Logs (Executed commands with output) (Include/Attach if Applicable)
https://github.com/mkacher/conanBug01082021#readme

**Comment by lasote** [comment]
Hi, thanks for reporting. I don't think this is a bug. The `conandata.yml` file is automatically exported, it is how it works. If you don't need it you can remove it.
Otherwise, you will need to clone the sources in a subfolder because git doesn't allow to clone in a dirty folder.

```
from conans import ConanFile, tools

class bugConan(ConanFile):
    name = "bug"
    version = "v0"

    def source(self):
        tools.mkdir("subfolder")
        with tools.chdir("subfolder"):
            git=tools.Git()
            _branch="main"
            _repo="https://github.com/mkacher/conanBug01082021.git"
            git.clone(_repo, _branch)
```

I also recommend you to take a look at the experimental [layout()](https://docs.conan.io/en/latest/developing_packages/package_layout.html#package-layout) feature, which will be part of Conan 2.0. That feature manages this kind of situation where you need/have a source subfolder by declaring the `self.folders.source`, then in the rest of the recipe the `self.source_folder` will point to the correct location.

**Comment by memsharded** [comment]
Closing this as a question responded, if there are any further question, please create a new ticket. Thanks!
