### ISSUE TITLE
tools.unzip() doesn't retain permissions stored in file

### ISSUE THREAD

**Issue by tru** [conan-io/conan#936]
unzip a file with `tools.unzip()` that has executable bits and they will be removed.

this works with external unzip binary.

There seems to be a bit of manual intervention needed for the ZipFile module: http://stackoverflow.com/questions/3007233/preserve-file-attributes-in-zipfile

**Comment by tru** [comment]
Here is another article that shows how it can be done: https://www.burgundywall.com/post/preserving-file-perms-with-python-zipfile-module

**Comment by tru** [comment]
```diff
diff --git a/conans/tools.py b/conans/tools.py
index b35dc5c..7d9dfc4 100644
--- a/conans/tools.py
+++ b/conans/tools.py
@@ -144,6 +144,8 @@ def unzip(filename, destination="."):
                 print_progress(extracted_size, uncompress_size)
                 try:
                     z.extract(file_, full_path)
+                    perm = file_.external_attr >> 16L
+                    os.chmod(os.path.join(full_path, file_.filename), perm)
                 except Exception as e:
                     print("Error extract %s\n%s" % (file_.filename, str(e)))
```

**Comment by lasote** [comment]
It only happens in Windows or Linux/OSX too?

**Comment by tru** [comment]
I have only seen it in Linux/OSX - not windows.

**Comment by lasote** [comment]
We are adding a "keep_permissions" parameter defaulted to False to the unzip method. Could be dangerous if the zip file has not been created in NIX system and contains bad bits. Could produce wrong permissions adjustment. https://bugs.python.org/issue15795

**Comment by tru** [comment]
SGTM

**Comment by nussbrot** [comment]
Hi, i'm currently running into a related issue. I'm not quite sure what's going on, so I decided to give you a quick summary here.

I have a conan package for a simulation tool. The package is like a tool installer. 
The problem i'm having is that the tool needs a config file to be read-only.
And i need that behaviour on Windows and Linux.

The first step is to make sure that the permissions are set correctly in my sources (these are a source.zip or a source.tgz file) and this is true. That means:

- when i unzip my source.zip under Windows i get file attributes RA (= read-only, archived) on the config.ini.
- when i untar my source.tgz under Linux i get chmod = 0444 on the config.ini.

 So, according to this thread i changed my conanfile and in the build method i use `tools.get(..., keep_permissions=True)`. The results are not promising, because the config.ini file, after the build step, has only the attribute A on Windows, missing the R.

As far as I can see it works on Linux as intended, so i guess the issue is only present for Windows file attributes.

**Comment by memsharded** [comment]
Hi @nussbrot 

I guess you are downloading and unzipping in the ``build()`` method, which is the right thing to do if those sources are different.

Could you share that ``source.zip`` file, or at least another one that allows to replicate this issue, that would help.

Of course in the meantime, you can try to run a ``self.run("chmod ...")`` in your recipe after the unzip to make sure you have the mode you need. Still a bit of a workaround, but should work.

**Comment by memsharded** [comment]
Hi again @nussbrot 

Could you please open it in a new issue, and give the feedback there? I prefer not to mess with this one, that was closed a long time ago. Thanks!

**Comment by nussbrot** [comment]
Hi @memsharded 
Thanks for the quick answer. I will open a new issue and add a stripped down zip-file,
but probably tomorrow.
