### ISSUE TITLE
[feature] Add ability to default --profile:build

### ISSUE THREAD

**Issue by pavlodenysov-vizio** [conan-io/conan#9365]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Same as omitting `--profile` is the same as using `--profile default`, omitting `--profile:build` should default to `--profile:build default` (or maybe some other profile, like `build_default` or something similar).

This may be breaking change for other users, but:
1. `--build:profile` is still experimental, so it's allowed to break things.
2. New environment variable (like `CONAN_DEFAULT_BUILD_PROFILE`) may be introduced to avoid breaking things for existing users.
3. New variable in `conan.conf` may be introduced (similar to `default_profile`). If not defined, or defined to `None`, Conan may preserve current behaviour.

**Comment by lasote** [comment]
Hi!

Yes, that would be breaking for the current users because specifying the build profile activates some internal mechanisms with the build requirements and other things. In Conan 2.0 that will be the default behavior.

We are not introducing "switches" to activate Conan 2.0 breaking features, we only have the [CONAN_V2_MODE](https://docs.conan.io/en/latest/reference/conan_v2_mode.html) but only to raise in case you are using things that are going to be deprecated. Before we release Conan 2.0 the build profile has to be specified, sorry.

Thanks!

**Comment by pavlodenysov-vizio** [comment]
@lasote What about introducing new environment variable or new variable in `conan.conf`? That will not be breaking.

**Comment by lasote** [comment]
We could do that but we are trying to avoid introducing switches to activate features that are potentially breaking. It is a matter of maintainability of the Conan code base.

**Comment by pavlodenysov-vizio** [comment]
@lasote Can you do that with `CONAN_V2_MODE` defined?

**Comment by memsharded** [comment]
Isn't https://github.com/conan-io/conan/issues/9336, assigned for 1.40 this feature?

We were discussing to add this to simplify the transition to the 2 profile approach.

**Comment by pavlodenysov-vizio** [comment]
@memsharded I missed that one. Would be great to have it. Thanks!

**Comment by lasote** [comment]
I missed that discussion too ;)

**Comment by lasote** [comment]
So I close this one and we can follow the other. Thanks and sorry for the confusion!
