### ISSUE TITLE
[question] Why not use continuous upgrading for conan 2.0?

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9372]
If it is possible, no break for developers and users of conan, they can be more focus.
e.g. while `archlinux` uses continous upragding, it can also make a big upgrade in long term.

Anyway just an idea for considering.

**Comment by lasote** [comment]
I don't think I understand the concept of "continuous upgrading". Do you mean Conan upgrading itself without user intervention?

**Comment by playgithub** [comment]
> Do you mean Conan upgrading itself without user intervention?

No, I mean upgrading without break.

**Comment by memsharded** [comment]
The bump of a major version, 1.0->2.0 means exactly that: this is a breaking version. Otherwise we would just keep releasing 1.X versions, like we have been doing for the last 3 years. 

Breaking is necessary, we need to get rid of bad behaviors, wrong defaults, legacy features and many more. As approved by the tribe, there will be a subset of recipe syntax that will be able to transition from 1.X(latest) to 2.0 without changing the recipe. But Conan 2.0 will definitely mean breaking.

**Comment by playgithub** [comment]
I think it is possible to be continuous, e.g. while a new break change is introduced, it can still work in the old way with a warning, that can have a date for deprecation or not.
My idea is to be focus on one branch for both developers and users.

**Comment by lasote** [comment]
It is indeed "possible", but the complexity of the code-base and support will grow forever and the project will fail eventually.

**Comment by playgithub** [comment]
Old codes can be deprecated when new alternatives are mature, there can be a period that both old and new coexist.

**Comment by lasote** [comment]
Yes, we will provide many tools in 1.X (so keeping old and new for some time) to ease the transition to Conan 2.0, the same recipe you write in 1.X with these tools (and the tools coming) will work in Conan 2.0 (https://docs.conan.io/en/latest/reference/conanfile/tools.html) But Conan 2.0 will remove old components.
