### ISSUE TITLE
[question] an idea to make concepts more clear

### ISSUE THREAD

**Issue by playgithub** [conan-io/conan#9373]
It's not intuitive for me to consider local `.conan` as `conan cache`,
I think it should be called `conan local` as compared to `conan remote`, or s.th. like `conan-repo` because it can work independently, like `git`.

In this way, 4 concepts there:
* local recipe
* local binary
* remote recipe
* remote binary

local & remote, recipe & binary, it is quite clear.
And because binary can be generated by recipe, it is not essential, it can be considered as cache.
I think all logics can be built on these 4 concepts, right?

**Comment by lasote** [comment]
But the server (or remote) storage structure is not the same as the local one, also the cache contains configuration etc.. so I think it is not the same concept. But I get your point. Thanks for the suggestions.

**Comment by playgithub** [comment]
While local and remote communicate with recipes & binaries,  they can be different, e.g. the local end have configurations while the remote end doesn't, and they can have different data structures and implementations.

**Comment by memsharded** [comment]
``local recipe`` will be very confusing, because this is the recipe that lives in the user folder, before creating the package or exporting.

- local recipe: in the user folder
- cache recipe: In the conan cache
- remote recipe: in the server

So I disagree, it shouldn't be called "local".

**Comment by playgithub** [comment]
> `local recipe` will be very confusing, because this is the recipe that lives in the user folder, before creating the package or exporting.

If `conanfile.py` is in a user folder, it should be treated as wild,  it's not necessarily for conan.

> * local recipe: in the user folder
> * cache recipe: In the conan cache
> * remote recipe: in the server

Generally `cache` should be transparent for users, manipulating cache is something like hacking.

**Comment by memsharded** [comment]
> If conanfile.py is in a user folder, it should be treated as wild, it's not necessarily for conan.

In which world a ``conanfile.py`` is not for Conan? The local conanfile.py in a user folder is one of the most common use cases, a ``conan install .`` or a ``conan create .`` will use the local ``conanfile.py`` in the user folder. And we need a terminology for this, and we are using "local" for this.

> Generally cache should be transparent for users, manipulating cache is something like hacking.

I am not telling to manipulate the cache. But when you do a ``conan create`` or a ``conan install`` recipes end installed in the cache. And we need a terminology for that, and we call them "recipes in the cache" or "cache recipes". Now you are proposing to name them "local" which I say will be very confusing, because that is the naming used to refer to conanfile.py in the user folders.

**Comment by playgithub** [comment]
> > If conanfile.py is in a user folder, it should be treated as wild, it's not necessarily for conan.
> 
> In which world a `conanfile.py` is not for Conan? The local conanfile.py in a user folder is one of the most common use cases, a `conan install .` or a `conan create .` will use the local `conanfile.py` in the user folder. And we need a terminology for this, and we are using "local" for this.

Theoretically, a file out of `.conan` should be treated as an arbitray file.
If change `conan install .`/`conan create .` to `conan install path/to/any-name.py`/`conan create path/to/any-name.py`,
it doesn't need a new concept here.
`conan install` & `conan create` can determine wheather to accept the content of the file.
It is more flexible, the flexibility can bring benifits,  e.g. put recipes in a folder called `recipe-bakup`, and every recipe can have its own file name, e.g.
* zlib-conan-recipe.py
* openssl-conan-recipe.py
* ...

> > Generally cache should be transparent for users, manipulating cache is something like hacking.
> 
> I am not telling to manipulate the cache.

It's rare to use commands to manipulate cache, generally only commands for clear cache or so are common.

**Comment by memsharded** [comment]
Sorry, but what you say makes no sense.

> Theoretically, a file out of .conan should be treated as an arbitray file.

All the opposite. Files there are not arbitrary at all. There is a clear layout of folders, files are structured. Getting files there needs a process. Nothing is arbitrary there.

> If change conan install ./conan create . to conan install path/to/any-name.py/conan create path/to/any-name.py,
it doesn't need a new concept here.

In both cases, you are using **local** user files. When, as a result of the ``create`` command, the file is copied from the **local** folder, a copy ends in the **cache**. 

> It's rare to use commands to manipulate cache, generally only commands for clear cache or so are common.

Practically all Conan commands manipulate the cache. ``conan install``, ``conan download``, ``conan export``, ``conan create``, ``conan export-pkg``, all modify the cache contents. So it is not rare, it is the most common case.

So, back to your original suggestion: It doesn't make sense to call ``local`` the files in the cache, because those are different concepts. So again:

- local: files in user folders
- cache: files in the cache.

We are not going to change that terminology, what you suggest would be way more confusing that the current one.

**Comment by playgithub** [comment]
> Practically all Conan commands manipulate the cache. `conan install`, `conan download`, `conan export`, `conan create`, `conan export-pkg`, all modify the cache contents. So it is not rare, it is the most common case.

Generally cache should be transparent to users, for conan, the concept of cache is special.
If treating `conanfile.py` in user folder as "conan local", the `conanfile.py`s in `.cache` folder are also `conan local` while they also belong to "conan cache".

**Comment by playgithub** [comment]
@memsharded 

I have tried to understand your design:
A local `conanfile.py` as a recipe outside `.conan` belongs to `conan local`,
and `.conan` as `conan cache` is as cache for `conan local`.
For the recipe is essential, all others can be considered as cache, I have to say no problem for `.conan` as `conan cache` when usderstanding it this way.

Problems:
* For the concept of `cache`, generally if a hit in cache is missed, it only slows down the procedure instead of failure. It is not true for conan
* If `.conan` is as `conan cache`, `confile.py` in `.conan` is also cache. When installed from local, `confile.py` in `.conan` is cache of local, when installed from remote, it is cache of remote, it is ambiguous, isn't it?

**Comment by memsharded** [comment]
> If .conan is as conan cache, confile.py in .conan is also cache. When installed from local, confile.py in .conan is cache of local, when installed from remote, it is cache of remote, it is ambiguous, isn't it?

No, it is not, caches can definitely work as bidirectional intermediate storage between 2 different systems, and in both directions. For example, in a memory cache you can have information that is coming from the main memory to make it available to the CPU, or it can come from the CPU as a result of some computing.

**Comment by playgithub** [comment]
> No, it is not, caches can definitely work as bidirectional intermediate storage between 2 different systems, and in both directions.

Agree
But generally `cache` is an optimization that should be transparent for application user interface.

**Comment by playgithub** [comment]
@memsharded 
If treat `conanfile.txt` as  essential, both recpice and binaries can be treated as cache.
But user defined profiles are not of any kind of cache, right?
