### ISSUE TITLE
[feature] Multiple toolchains in one recipe

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#9376]
Sometimes, building a package needs configuring + building multiple related autotools/cmake/meson projects.
Looking at e.g. current `conan.tools.gnu.Autotools` and `conan.tools.gnu.AutotoolsToolchain`,
it looks like these only support one "toolchain".
I think it would be useful to be able to generate multple toolchains, e.g. by namespacing.

An example of a recipe requiring this would be e.g. a toolchain.
I've written this recipe to build a ps2toolchain: https://github.com/madebr/conan-ps2dev/blob/master/recipes/ps2dev-ps2toolchain/all/conanfile.py
It needs to run configure+make+install multiple times for binutils (3 times), gcc (2+1 times), newlib (1 time).

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
Yes, looks like a limitation for the new model, thanks for raising the issue.

I was thinking that the `AutotoolsToolchain` generate method is very simple and might be done manually changing the names (continue reading, there is a BUT): 

```
    def generate(self, env=None, auto_activate=True):
        env = env or self.environment()
        env.save_script("conanautotoolstoolchain", auto_activate=auto_activate)
        self.generate_args()
```

BUT we still have a problem with the `conanbuild.conf` file we are writing:

 - The name is always the same (otherwise the build helper doesn't know what to read)
 - If we had a project that compiles for example a part with Autotools and a part with CMake (not common but possible I guess) we are overwriting that file.
 
As you said, maybe namespacing could be a solution. It might be something like:

```

def generate(self):
    autotools1 = AutotoolsToolchain(self, namespace="foo")
    autotools1.generate()
    autotools2 = AutotoolsToolchain(self, namespace="bar")
    autotools2.generate()
    cmake = CMakeToolchain(self, namespace="lur")
    cmake.generate()


def build(self):
     autotools1 = AutoTools(self, namespace="foo")
     autotools1.configure()
     autotools1.make()

     autotools2 = AutoTools(self, namespace="bar")
     autotools2.configure()
     autotools2.make()
 
     cmake = CMake(self, namespace="lur")
     cmake.configure()
     cmake.make()

```

Question, Should the `conanbuild.conf` be unique but with "namespace" entries? EDIT: If the file is the same for different toolchains, you would need to append to the files the keys from the different toolchains but you would need to make sure you clean the file before calling generate (sounds tricky).

I assign this to the release to see if we can discuss what to do in the next one at least. I give it high priority not because this is not a very very common use case but It can affect how we manage the new toolchains so better to think about it ASAP.

**Comment by lasote** [comment]
Hi, we discussed this and how to solve it, and my proposal is good. Given that the solution fits in the current model with some opt-in changes I lowered a bit the priority and assigned the task to the next release. Thanks again.
