### ISSUE TITLE
Expand --require-override to lockfiles

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9392]
Nice feature! 👍
I wonder why there is no similar functionality for `lock create` command where it could make sense with version ranges?

_Originally posted by @ytimenkov in https://github.com/conan-io/conan/issues/9195#issuecomment-893268894_

Summary:

Conan 1.39 added ``--require-override``, but only for install and create commands. It would make sense to extend it too to lockfiles.

**Comment by ytimenkov** [comment]
Yes, I saw the original discussion in #2140 after I wrote that comment :/

Maybe I was too quick and on the second thought it is not what I really want...

The idea I had in mind is that `--require-override` is looks like a way to propagate packages in CI.

I think this is related: #8331.

I remember you suggested to update dependencies by:

1. Clean the cache
2. Install current lockfile.
3. remove package-to-update (maybe, if it's a downgrading in terms of semver...).
4. Install updated package explicitly (version, revision from upstream job) so it is the one in the cache.
5. Create new lockfile with `conan lock create` so it should pick most of recipes from the cache (therefore from the previous lockfile) and the updated new one.

Now I realize that `--require-override` won't make it simpler because dependencies (versions and revisions) will be resolved from the recipe and not from the previous lockfile.

**Comment by memsharded** [comment]
Hi @ytimenkov 

Ok, understood. The thing is that we are exploring new alternatives for lockfiles in Conan 2.0 that will focus on simplifying the use case that you are describing, because it is true that such a flow is complicated.

Then: lets wait a bit to decide on this, until we understand better the future of lockfiles in Conan 2.0.

**Comment by rl-enjoyer** [comment]
Is this the sort of thing that would help with my question here https://cpplang.slack.com/archives/C41CWV9HA/p1637363530195300 ?

**Comment by samuel-emrys** [comment]
I think that this would be a useful feature. I'm currently running into the following problem:

```
$ conan lock create conanfile.py --lockfile-out=locks/project.lock
WARN: xapian-core/1.4.19: requirement zlib/1.2.13 overridden by doxygen/1.9.2 to zlib/1.2.12 
ERROR: Conflict in xapian-core/1.4.19:
    'xapian-core/1.4.19' requires 'zlib/1.2.12' while 'libcurl/7.78.0' requires 'zlib/1.2.13'.
    To fix this conflict you need to override the package 'zlib' in your root package.
```

This conflict is actually caused by build requirements and host requirements attempting to resolve a dependency diamond (which I think is probably an error - there shouldn't be any leakage across `tool_requires` boundaries that would influence the host context so I'm not convinced that resolving the diamond here makes sense, but maybe it should be an option for edge cases), and the fact that CCI recipes don't use version ranges.

I'd rather not create an explicit `zlib` override in my `conanfile` because my library doesn't depend on it directly. To resolve these, it would be useful to be able to be explicit about what I want the `zlib` version to be in the lockfile.

Having said that, I'm reasonably new to lockfiles, so maybe this wouldn't work because the cci dependencies don't use version ranges?

Edit: I've realised that the diamond dependency issue between build and host requirements is due to the fact that I was using a single profile, so this isn't useful for that particular use case. Having said that, this kind of conflict could still arise in one or the other tree, so I think that this feature still has enormous merit.

**Comment by memsharded** [comment]
Lockiles have been greatly improved in Conan 2.0. They are already available for testing in the several betas released.
They will replace the ``--require-override`` (for all commands, not only for ``lock create``), under some assumptions, like it is only possible to override within valid defined version ranges.

Still, the version conflict issue that you are seeing @samuel-emrys would not be solved by lockfiles, because it happens at the time the graph is computed. And yes, as conancenter doesn't use version ranges, it is not possible to solve it defining it a  lockfile (a lockfile is a snapshot of a graph that can be computed from conanfiles and their ``requires``, but cannot force a graph that is not realizable given conanfiles). I think that issue is resolved more by the graph (requirement traits, tool_requires, the 2 profiles, etc).

**Comment by memsharded** [comment]
As this is not planned for 2.0, and 2.0 is almost there, I think we can close this as not planned. If you have any question about the new lockfiles or anything related, please feel free to submit a new issue. Thanks!
