### ISSUE TITLE
[feature] tools.ftp_download's are not cached

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#9428]
The current `tools.ftp_download` implementation does not support caching.
This means that a repeated call to `tools.ftp_download` will always connect to the internets.
It would be nice if `tools.ftp_download` also received support for checking hashes.
Even better would be (imho) to integrate it into `tools.download`/`tools.get`.

https://github.com/conan-io/conan/blob/c3fc425871149b12a1d12153bed90a06a3d20132/conans/tools.py#L74-L75

https://github.com/conan-io/conan/blob/c3fc425871149b12a1d12153bed90a06a3d20132/conans/client/tools/net.py#L30-L50

**Comment by MariaMozgunova** [comment]
Can I take this issue?

**Comment by memsharded** [comment]
Better not now.

We are removing the "file download cache" in 2.0, because of some complexities, missing development in the 2.0 cache concurrency and lack of consistent feedback of the performance gains of the "file download cache".

In order to consider re-enabling the file download cache we need reports for different users about:

- What performance gains are being observed by enabling it
- What is the most important perceived value
- Is it being enabled for developers machines, CI, or both? For all OS? is the performance similar in all OS?
- Is it necessary to decouple caching of internet files (sources downloads) and caching of files coming from a conan server (like a conan_package.tgz from a Conan package binaries)

As we are no longer implementing this kind of new features in Conan 1.X, and the feature has been removed in 2.0, I am closing this issue, and opening a new one for 2.X scope from this comment.
