### ISSUE TITLE
[question] Checking License of Dependencies

### ISSUE THREAD

**Issue by wheeler1818** [conan-io/conan#9435]
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Background:**
I want to check the license of all the dependencies. In our company we a list with all types of licenses which we can use and which we must not use. During the build (or during validate) i want to check and raise an error if a forbidden license is used.

Is there any way to access the license property of the dependencies? I used the dependecies interface (https://docs.conan.io/en/latest/reference/conanfile/dependencies.html#dependencies-interface) but the license property is not accessible. It would be helpful if the license is accessible.

Thanks!

**Comment by memsharded** [comment]
Hi @wheeler1818 

Yes, I guess this could be added to the ``self.dependencies`` interface, but maybe a couple of ideas are worth mentioning:

- This could be a cross-aspect thing, probably you don't want to implement the same check in all ``validate()`` methods of all your recipes (or even third party recipes you would need to modify). Have you considered using hooks? Maybe a custom generator could help with this.
- Please do check the access model of ``self.dependencies``, which is very oriented to building. This means that it might not include absolutely all transitive dependencies in the first level dictionary, as private transitive dependencies (not visible, because they are build_requires or something like that), will not be there, and you would need to iterate the ``dep.dependencies`` for ``for req, dep in self.dependencies``, and so on, recursively. You might need to write a helper for this, it might be worth doing this in a generator or something, or it seems it could be a very valid feature request for the ``self.dependencies`` object, some recursive iterator.

**Comment by wheeler1818** [comment]
Hi @memsharded ,

thanks for your suggestions. I didn't know about hooks, so i think this is the way to go. 

Here is my code:
```
def pre_download_package(output, conanfile, conanfile_path, reference, package_id, remote, **kwargs):
    output.info("conanfile.name={}".format(conanfile.name))
    output.info("conanfile.license={}".format(conanfile.license))
    if (conanfile.license != "BSL-1.0"):
        raise Exception("Not allowed License.")
```
The packages are downloaded for each build on azure pipeline so i think this should work for all transitive dependencies? We do not have any build_requires, all packages are pre-built and cached on an aritfactory.

**Comment by memsharded** [comment]
> The packages are downloaded for each build on azure pipeline so i think this should work for all transitive dependencies? We do not have any build_requires, all packages are pre-built and cached on an aritfactory.

Yes, if doing a check on the download of the recipes is good for your case, and you don't need to evaluate the full dependency graph together, this would be a simple and effective approach. For your info, there is a hooks repo with some examples, like this license checker: https://github.com/conan-io/hooks/blob/master/hooks/spdx_checker.py (it checks at package creation time, to ensure created packages have a valid information).
