### ISSUE TITLE
[feature][suggestion] Merge remotes.json lists

### ISSUE THREAD

**Issue by CaptnMorgan833** [conan-io/conan#9441]
Hey,

We work in different projects with different remotes and profiles. When switching the project and using a new setup via "conan config install <GIT-REPO-WITH-CONFIG>" , new profiles from that repo are added to the old ones, but the remotes.json gets replaced completely.

It would be nice if there is a possibility to keep the old remotes.json and to merge new and old together to get the collection of all remotes needed for different projects. Maybe there could be a new argument for the "conan config install" command like "--merge" or something. Or the other way round by merging/keeping the old stuff by default and using something like "--replace" to explicitly remove the old stuff. 

Thanks for reading :) !

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @CaptnMorgan833 

We have considered a few times some scenarios similar to this one, that could "merge" information. The problem with this feature is that it has infinite edge cases, and it is particularly challenging when it is a 2-way  merge instead of a 3-way merge with a common base to compare, for this particular example:
- When there is a remote that is called the same, but 2 different URLs, is it a conflict? should the second one in order prevail?
- When there are 2 remotes with different name, but same URL what happen?
- What is the process to merge remotes, but at the same time make sure that some remotes get removed (like for example the built-in ``conancenter`` one, a lot of companies want to remove it, because they don't rely directly on it, but on their own Artifactory server). 

For every possible "default" behavior that we could consider, I bet there will be other users that will want the opposite one for their flow, and we can't keep adding ``--merge --url_update_no_conflict --remove=some-remote...`` arguments for the different cases. It is way more manageable, predictable and simple to do the merge manually and rely on a single ``conan config install`` for the desired remotes.

Lets see what @lasote thinks, but I think this feature would add a large overhead (code, tests, maintenance, support), for little user value.

**Comment by lasote** [comment]
Yeah, I agree. The merge could be done in a lot of different ways and you never know what the user expects. If you want to merge the remotes is probably better to add all of them by hand to the configuration.
