### ISSUE TITLE
[bug] conan search doesn't return the latest versions on conan center

### ISSUE THREAD

**Issue by lukasberbuer** [conan-io/conan#9445]
`conan search <package> -r all` does not return latest version(s) on conan center.

Are the results cached? If yes, how to clear the cache?

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Pro 19042.1165
  * Compiler+version: -
  * Conan version: 1.39.0
  * Python version: 3.9.0

### Steps to reproduce (Include if Applicable)

Compare results from `conan search` and https://conan.io/center, e.g. with package `spdlog`:
- `conan search spdlog -r all`: newest version: **1.8.5**
- https://conan.io/center/spdlog: newest version: **1.9.2**

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ conan search spdlog -r all
Existing package recipes:

Remote 'conan-center':
spdlog/0.14.0@bincrafters/stable
spdlog/0.16.3@bincrafters/stable
spdlog/0.17.0@bincrafters/stable
spdlog/1.0.0@bincrafters/stable
spdlog/1.1.0@bincrafters/stable
spdlog/1.2.1@bincrafters/stable
spdlog/1.3.0@bincrafters/stable
spdlog/1.3.1@bincrafters/stable
spdlog/1.4.1@bincrafters/stable
spdlog/1.4.2
spdlog/1.4.2@bincrafters/stable
spdlog/1.5.0
spdlog/1.6.0
spdlog/1.6.1
spdlog/1.7.0
spdlog/1.8.0
spdlog/1.8.1
spdlog/1.8.2
spdlog/1.8.5
```

**Comment by czoido** [comment]
Hi @lukasberbuer,
That's because you probably just have `conan.bintray.com` as your remote for conan center. This url is [being deprecated](https://blog.conan.io/2021/03/31/Bintray-sunset-timeline.html) and recently we are only adding new versions in conan center to `center.conan.io`. Since Conan 1.37 [this remote is added automatically](https://blog.conan.io/2021/04/23/New-Conan-Center-url.html) with new Conan installations. 
You can add the new remote using: 
`conan remote add conancenter https://center.conan.io`

**Comment by lukasberbuer** [comment]
Hell yeah, that's it! Thanks a lot :)
