### ISSUE TITLE
[feature] Improve CMakeToolchain support for xcode flags

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan#9448]
Coming from https://github.com/conan-io/conan-center-index/pull/5545

The `darwing-toolchain` generator recipe used to provide some useful configurable apple flags: https://github.com/ezored/conan-darwin-toolchain/blob/stable/1.3.0/conanfile.py#L87-L127

We should take a look at the cmake flags used there and see if we can improve the integration for cmake apple-clang projects

cc/ @theodelrieu @paulo-coutinho

**Comment by lasote** [comment]
To discuss:

- About the bitcode: We could add a `[conf]` entry and improve the `CMakeToolchain` to set the corresponding variable. I suggest `"tools.darwin:bitcode_generation_mode": "Activate the bitcode generation in OSX platfom: 'marker', 'bitcode'"`. I wouldn't couple it to CMake because it is a clang option on Darwin that could be used by other generators. Actually the [CMAKE_XCODE_ATTRIBUTE_XXX](https://cmake.org/cmake/help/latest/variable/CMAKE_XCODE_ATTRIBUTE_an-attribute.html) are only applied when the generator is `xcode`, otherwise the bare cflags `-fembed-bitcode-marker` and `-fembed-bitcode` should be adjusted to the compiler flags somehow.

- About the `CLANG_ENABLE_OBJC_ARC`, it only applies to objective C. Looks like something very specific, right? I would say then, why don't create `[conf]` entries for other cflags like sanitizers and so on? Not sure about the limit.
- About the `GCC_SYMBOLS_PRIVATE_EXTERN`. Same comment, that eventually adjust the `-fvisibility=hidden` so, why supporting that flag and not others? Just because xcode allows it?

@memsharded

**Comment by memsharded** [comment]
> About the bitcode: 

Yes, probably ``"tools.darwin:bitcode_generation_mode"`` => ``tools.apple:...`` to be more aligned with our namespaces.

> About the CLANG_ENABLE_OBJC_ARC, 

I have been trying to push the idea of generic CFLAGS, CXXFLAGS injection via ``[conf]`` for all integrations that will listen to them. Maybe it would be better to solve the generic flags problem?

**Comment by lasote** [comment]
I think yes, we should at least start by supporting something generic like cflags and see later if we create specific [conf] entries for higher-level stuff.

**Comment by lasote** [comment]
I'm moving this to Done as the look into of 1.40 and assigning to 1.41.

**Comment by a4z** [comment]
all apple cmake flags, like bitcode is very well handled by that: https://conan.io/center/ios-cmake
bitcode makes only sense for  iOS, tvOS, watchOS, and there only for the target, not simulator

**Comment by theodelrieu** [comment]
@a4z 

>and there only for the target, not simulator

Are you sure about that? I've used those flags for simulators as well.

**Comment by a4z** [comment]
I have written a linter for conan packages that checks the generated binaries if they contain bitcode, since I wanted to get that error after package creation, not on consumtion
Through that I detected that. Then I started to think about it and realized that it makes sense.
(I might add a blog entry on how to do that when I find the time)

The actually problem we have with the iOS/tvOS/watchOS build is that the conan docs are not mentioning the ios-cmake toolchain, and that recipes with custom/other builds need to handle that internal , openssl and libcurl for example. In doubt , they always should generate bitcode, because soon that will be required for devices anyway, and other builds do not care.
That said, I did not have time to look into the bitcode -> M1 relation, maybe apple sees the M1 as mobile device and it adds bitcode to the binary even if the target is BigSur

**Comment by a4z** [comment]
Addressed on problem and added some docs for the iOS toolchain,
https://github.com/conan-io/docs/pull/2223

This should (hopefully) show and explain a bit more details

**Comment by paulocoutinhox** [comment]
Hi,

Bitcode is only for apple recompile your application and delivery smaller size app (store or adhoc):
https://developer.apple.com/documentation/xcode/doing-basic-optimization-to-reduce-your-app-s-size

So, i've disabled it for simulators too:
https://github.com/ezored/ezored/blob/version-3/files/config/target_ios.py#L37

@a4z Your solution is good, be all flags need affect dependencies too. All options/flags from ios-cmake need be passed to all dependencies, like here:
https://github.com/ezored/ezored/blob/version-3/files/targets/ios/conan/profile/ezored_ios_profile#L8-L9

**Comment by a4z** [comment]
Yes, of course, you are supposed to rebuild all the conan packages you use with the same profiles, so all dependencies are compatible, but this is how you do it (hopefully) anyway with conan.

bitcode is required for watch and tvos, I think, for iOS it is optional (for now)

I think you do not need to omit the bitcode flag for the x86_64 simulator, it will just have no  effect.
Not sure how the compilation on M1 behaves, would need have to check, but I would not be surprised if there would be bitcode in the simulator binaries, so omitting it there could make sense, or not, I do not think you gain a lot not using it

**Comment by lasote** [comment]
Just for reference, the mentioned package `https://conan.io/center/ios-cmake` is using this project that provides a cmake toolchain for (iOS (+ Catalyst), watchOS, tvOS, and macOS) https://github.com/leetal/ios-cmake Almost 1000 stars. We should definitely take a look.

**Comment by a4z** [comment]
Yes, ios-cmake is the defacto default to build native things since years when it comes to cmake, that's why I added it to the cci.

**Comment by lasote** [comment]
Note: Look into combine external toolchains with the conan one.

**Comment by a4z** [comment]
I am not sure what you referring to exactly

**Comment by lasote** [comment]
Internal note

**Comment by a4z** [comment]
aha, ok, so it's clear I cant find it ...?

But you might bin interested that I already combined them, in the past

like that (in the conanfile.py of my project)
I cuttet away some parts, but to get the idea that should be sufficent,

whatever you plan to do, please do not break such thing in future, since everything basically works for mobile with conan :-) 

```
   def generate(self):
        tc = CMakeToolchain(self)
        tc.variables["DJINNI_BINDIR"] = self.deps_env_info["djinni-generator"].PATH[0]

        if self.settings.os == "Android":
            self.output.info('ANDROID_NDK environment variable: %s' % self.deps_env_info["android-ndk"].ANDROID_NDK_ROOT)
            os.environ["CONAN_CMAKE_ANDROID_NDK"] = self.deps_env_info["android-ndk"].ANDROID_NDK_ROOT
            os.environ["CONAN_CMAKE_ANDROID_NDK_HOME"] = self.deps_env_info["android-ndk"].ANDROID_NDK_HOME
            tc.variables["CMAKE_TOOLCHAIN_FILE"] = self.deps_env_info["android-ndk"].ANDROID_NDK_HOME + "/build/cmake/android.toolchain.cmake"
            tc.variables["ANDROID_PLATFORM"] = "android-" + str(self.settings.os.api_level)
            tc.variables["ANDROID_NATIVE_API_LEVEL"] = self.settings.os.api_level

        if self.settings.os == "iOS":
            #print("HERE MAKEING IOS", self.deps_env_info["ios-cmake"].CONAN_CMAKE_TOOLCHAIN_FILE)
            tc.variables["CMAKE_TOOLCHAIN_FILE"] = self.deps_env_info["ios-cmake"].CONAN_CMAKE_TOOLCHAIN_FILE
            tc.variables["ENABLE_BITCODE"] = self.deps_env_info["ios-cmake"].CONAN_ENABLE_BITCODE_FLAG
            tc.variables["ENABLE_ARC"] = self.deps_env_info["ios-cmake"].CONAN_ENABLE_ARC_FLAG
            tc.variables["ENABLE_VISIBILITY"] = self.deps_env_info["ios-cmake"].CONAN_ENABLE_VISIBILITY_FLAG
            tc.variables["ENABLE_STRICT_TRY_COMPILE"] = self.deps_env_info["ios-cmake"].CONAN_ENABLE_STRICT_TRY_COMPILE_FLAG
            if (self.settings.arch == "x86_64"):
                tc.variables["ARCHS"] = "x86_64"
            else:
                tc.variables["ARCHS"] = "arm64"

        tc.generate()

```

**Comment by lasote** [comment]
Thanks. I was thinking more about how it would affect/collide including the toolchain directly from the conan one and how could we solve it. (meaning using directly https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake)
https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html#using-a-custom-toolchain-file

**Comment by paulocoutinhox** [comment]
Hi,

We need a way to use it and pass flags for all dependencies only one time, it will be nice.

Example:

```
[build_requires]
darwin-toolchain/1.3.0@ezored/stable

[options]
darwin-toolchain:enable_arc=True
darwin-toolchain:enable_bitcode=True
darwin-toolchain:enable_visibility=False
```

**Comment by a4z** [comment]
@paulo-coutinho , what you request can already be done with the ios-cmake toolchain file

for software not using CMake, how to enforce bitcode flags might be kind of individual
you can of course set some env variables global instead of per package, as I show in https://github.com/conan-io/docs/pull/2223
```
    openssl:CFLAGS=-fembed-bitcode
    libcurl:CFLAGS=-fembed-bitcode
    libcurl:CPPFLAGS=-fembed-bitcode
``` 
but personally I prefer to be more explicit and set it per package, and then test if flags have been applied, because that might not be the case, some recipes are kind of special ;-)

**Comment by paulocoutinhox** [comment]
Hi,

The problem is described here:
https://github.com/cross-language-cpp/djinni-support-lib/issues/58

Don't make sense use ios-cmake recipe and need pass manually parameters for all my recipes. If bitcode is enabled, ALL recipes need be compiled with bitcode flags, else, clang will throw the error:

```
ld: '/Users/paulo/.conan/data/openssl/1.1.1k/_/_/package/a12e97b2c36daacff7553fa82efde5d2e1253fff/lib/libcrypto.a(rand_lib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by paulocoutinhox** [comment]
Hi @a4z.

What do you think in mix https://github.com/conan-io/conan-center-index/blob/master/recipes/ios-cmake/all/conanfile.py and https://github.com/ezored/conan-darwin-toolchain/blob/stable/1.3.0/conanfile.py?

We can still use cmake toolchain, but we need add the same flags to python manually too.

**Comment by a4z** [comment]
My main point for not having something that exports CFLAGS, CPPFLAGS and other global for everything, and prefer to set options per recipe in profiles is that this gives me more control what recipes do pick up on their own and what not. I also do not what that the global state interferes some autodedection that a build might do. This is why I think  control per package is better and I work that way and not with global state, even if it sometimes misses some convenience. But it is good that people have options in how to solve a problem and chan choose what ever works best for them

**Comment by paulocoutinhox** [comment]
Yes, it is a particular opinion.

But specify particular recipe options always can be used, with a Xcode package/recipe or not.

What we can do is set flags when user enable options explicitly, that is what im suggesting.

If they enable "bitcode", the flags will be defined, else, the default behaviour/flags/etc will still remain intact.

I can create a PR for "ios-cmake" recipe that will enable only required flags for each option, like i do here:
https://github.com/ezored/conan-darwin-toolchain/blob/stable/1.3.0/conanfile.py

**Comment by memsharded** [comment]
We are going to try to do a proof of concept for 1.43 with:

- Defining a [conf] item for one or more of the xcode flags
- Research what makes sense, like generalizing cxx_flags or the like
- Make ``CMakeToolchain`` listen and map that configuration

**Comment by paulocoutinhox** [comment]
Hi,

As I use my day-to-day compilation of things for Apple (iOS, watchOS, tvOS), mainly in the Ezored project (https://github.com/ezored/ezored) and several people and companies use my project and do the same thing as me, what makes the most sense is that the flags are passed to all libs at once, as you can't have one lib compiled with bitcode and one without, as this generates a compilation error. We've been doing this for years and I don't see why I keep setting these flags by dependencies, as they need to be for everyone.

Any news about this problem?

Thanks

**Comment by paulocoutinhox** [comment]
Hi. 

Any news about it?

Thanks.

**Comment by gegles** [comment]
Yes, any updates? We desperately need to be able to build on iOS...

**Comment by paulocoutinhox** [comment]
Hi @gegles,

I think no one has focus on it :(

What im doing to solve this problem is using the `darwin-toolchain/1.5.0@ezored/stable` in the recipe. It works.

Thanks.

**Comment by memsharded** [comment]
Hi @gegles 

This open issue is for some extra flags, but the standard support for Xcode is already there. We have tests in our tests suite that cross-compile for iOS and M1 for example:

- https://github.com/conan-io/conan/blob/develop/conans/test/functional/toolchains/ios/test_using_cmake.py
- https://github.com/conan-io/conan/blob/develop/conans/test/functional/toolchains/cmake/test_cmake_toolchain_m1.py

So it is not that it is not possible to build for XCode, for OSX, iOS, but for more complete support for some things like CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE. So far it seems @paulo-coutinho mentioned ezored toolchain package can help with this.

This has been difficult to get some time to integrate in the CMakeToolchain, but it is in the backlog, hopefully we will be able to get some time for this soon.

**Comment by a4z** [comment]
> I think no one has focus on it :(

not exactly true, for me things worked quite will on Mac, with the info I shared.

It is of course unfortunate that conan team decided to ignore the info I contributed as a PR to the conan docs, 
so that based on that toolchains could be build up, but that's how it is.

However, the main question might be, what is your actual problem you need to solve and the solution is missing?

**Comment by gegles** [comment]
Thanks @paulo-coutinho and @memsharded! 

I was actually running into bitcode issues... but:

* `darwin-toolchain/1.5.0@ezored/stable` overall seems to work for me now.
* `openssl/3.0.1` would not compile for me when using `[options] darwin-toolchain:enable_bitcode=True`
* So I ended up disabling bitcode in my library and it seems to build fine now (at least on iOS)

My issues are now on the Android side of things...  I cannot seem to make the `[tool_requires]android-ndk/r22b` (described in the [docs](https://docs.conan.io/en/latest/integrations/cross_platform/android.html)) work at all, even though I am running the latest v1.44.1 conan... The `tool_requires` is not even recognized (`profile: ConfigParser: Unrecognized field 'tool_requires'` and when using `build_requires` I get this: `android-ndk/r22: Invalid ID: os=Android is not supported by android-ndk (no binaries are available)`

**Comment by paulocoutinhox** [comment]
Hi @gegles,

I made a project that have all of this problem solved:
https://github.com/ezored/ezored

Im using openssl `openssl/1.1.1k` without problems with bitcode or other thing. I don't know what error you get for `openssl 3`.

Android things are built without problems too. My android profile on ezored:

```
include(default)

[settings]
os=Android
os.api_level=21
compiler=clang
compiler.version=11
compiler.libcxx=c++_static
arch=armv7

[build_requires]
*: android-ndk/r22
```

Maybe it help you.

**Comment by paulocoutinhox** [comment]
Hi,

There is something new to this problem on recent releases?

Thanks.

**Comment by franramirez688** [comment]
Hi @paulocoutinhox 

I'm working on trying to bring those Xcode flags (based on `conan-darwin-toolchain` recipe)  to `CMakeToolchain` directly. Still in progress but I hope we'll have something finished for the next Conan 1.48 version.

**Comment by memsharded** [comment]
Implemented in https://github.com/conan-io/conan/pull/10985, will be in next 1.48

**Comment by paulocoutinhox** [comment]
It was solved and is used in my new project:
https://nativium.github.io/

Thanks a lot!

**Comment by memsharded** [comment]
Thanks for the feedback @paulocoutinhox !
