### ISSUE TITLE
[Question] "conan export" -phase, how to access tools from a dependency package

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#9454]
Hi,

given the following:

A:
  cache: package/bin/tool.sh
  
B:

B -> A

I need to access a tool from A's bin directory during the "conan export B" -phase (the tool helps to parse B's options dynamically).
Is there a recommended way to accomplish this? E.g. the "deps_cpp_info" is not available during "conan export B ...".

By inspecting B's __dict__ to me it looks like there is no attributes available that could be used for referencing A's package directory?

**Comment by memsharded** [comment]
Hi @iiknd 

The only way to reuse some functionality from other package dependency at export time is the ``python_requires``, have you tried those?
The thing is that ``conan export`` will not compute the full dependency graph to produce the export, and it is extremely unlikely that we would consider this feature, because it would have a lot of drawbacks, like being way slower making it unfeasible for many users flows, or requiring a deterministic order when users want to export related package recipes.

**Comment by iiknd** [comment]
Hi @memsharded,

we are actually already using the python_requires. Most of the packages re-use shared (python) functionality via python_requires.
But I haven't tried to python_require a package (say A) which is also a normal Conan dependency.
So is this something that can be done?

A:python_requires -> shared
B:python_requires -> shared
**B:python_requires -> A**  # to access a tools from A's binary package: bin/tool.sh   
B:requires -> A

**Comment by memsharded** [comment]
Hi @iiknd 

No ``B:python_requires -> A `` it is not possible to access tools from A binary package, it can only access tools in the python conanfile.py of A, not in the binary package. 

This would be almost same question as in https://github.com/conan-io/conan/issues/9449.

A solution could be to put ``tool.sh`` in the ``exports`` of the recipe, and try to use it directly from there. It is not very clean, and if this is multi-platform (a different tool.sh for different platform) it will probably not work.

I have been re-thinking this, and the question here and https://github.com/conan-io/conan/issues/9449, has the same big blocker: it is not possible, because it would require a full evaluation of the dependency graph, which requires first all the configuration, settings, options, etc, just for a simple "export" and the dependency graph can in turn be conditional to this configuration, being a chicken and egg problem. Sorry, but you won't be able to use binary packages at the ``export`` phase. 
The alternative as suggested in https://github.com/conan-io/conan/issues/9449 is to setup an environment with the tools you need in a previous step, and call Conan again inside that environment.

**Comment by iiknd** [comment]
Thanks for the clarification. It is good to know that there are no good approaches for this case right now. Thanks!
