### ISSUE TITLE
[feature] Consider jinja templates for global.conf

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9481]
At the moment it is possible to use jinja for profiles.
Profiles can define a ``[conf]`` section, so it is possible to define conf based on env-var, for example.
But this is not possible for "core" configuration, that is only defined in *global.conf* file.

Does it make sense:
- To enable jinja for global.conf?
- To allow "core" configuration in profiles?

**Comment by memsharded** [comment]
At the moment not enough evidence that this is very necessary, we can wait.

**Comment by sharpepd** [comment]
I found this because I was just looking to see if it were possible to do this! 
What I was thinking was that I would somehow like to have the configuration option "core.version_ranges:resolve_prereleases=true" switchable say by an environment variable. But it could be that I am still not comfortable with the configuration approach yet....

**Comment by memsharded** [comment]
Hi @sharpepd 

Yes, it is possible to use ``{% if os.getenv("SOME_ENV_VAR") %}`` in jinja templates.

However it might not be necessary, you can also use ``-cc core.version_ranges:resolve_prereleases=true`` on the command line to define this conf dynamically without having to resort on a custom env-var.

**Comment by sharpepd** [comment]
OK. I thought I had read that core configurations could not be changed on the command-line.  But checking again, I see I am wrong. Thanks for the tip!
