### ISSUE TITLE
[bug] Taking (build)-requirements of test_package into account when creating lockfiles / build order

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#9484]
We're using the following flow to lock a graph and create packages:

```
conan lock create conanfile.py --lockfile-out conan.lock --build outdated
conan lock build-order conan.lock --json=build_order.json
```
and then create the packages one by one, as specified in the build order.

Also in that case, V2 mode was activated (though I can't tell if that causes the problem or not)

I get a build order like this:
```
[[('curl/7.68.0@user/stable#3fe6315d8257cdeee6ec11c984235959', '7363a0e3e7935f2ce948115d107166cb2069c79b', 'host', '17'), 
(other packages), 
 ('cmake/3.20.0@user/stable#43e9acd6200c4f6762bc34e5611bb194', '60b04a80ac4dd5c23f1acffacc679e9902e636e5', 'host', '68'),
 ('cmake/3.16.3@user/stable#1fa7eba0b70fafd40719c6f3013e468d', '60b04a80ac4dd5c23f1acffacc679e9902e636e5', 'host', '72')], 
[('asio/1.12.0@user/stable#f51c99650654f2059d35206a786ceea8', '09a20051a9ad104ae07be664fc2d4fc29d3df917', 'host', '1'),
(many other packages)]]
```
The build order states, that `curl` and `cmake` can be build independent of each other.
The problem is, while curl doesn't have a `build_requirement` of `cmake`, it's `test_package` has, and the `conan create` fails with::

```
ERROR: Missing binary: cmake/3.20.0@heat-rae/stable:60b04a80ac4dd5c23f1acffacc679e9902e636e5
cmake/3.20.0@user/stable: WARN: Can't find a 'cmake/3.20.0@user/stable' package for the specified settings, options and dependencies:
ERROR: Something failed while testing 'curl/7.68.0@user/stable' test_package after it was built using the lockfile. Please report this error: Missing prebuilt package for 'cmake/3.20.0@user/stable'
```

It seems, that the build order calculation does not take into account dependencies that are specified in the testpackage, but it should. Otherwise I cannot create packages successfully.

@memsharded, any ideas?

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version: 1.39.0
  * Python version:

### Steps to reproduce (Include if Applicable)
Not 100% sure how to come up with a simple, reproducible test case...

**Comment by memsharded** [comment]
Ok, I see what the problem is. The lockfile cannot capture or lock the requires or build_requires of test_package folders, because those folders and requires are completely outside of the graph. When computing the dependency graph that is being locked, the ``test_package`` of ``curl`` simply doesn't exist at all, so it cannot be locked.

This could have a partial solution or workaround if moving to the 2 profiles approach, in which the ``context`` will be "build", and then the "build" packages in the same level could be prioritized.  But in the general case, it seems there is a definition problem: ``test_package`` ``requires`` and ``build_requires`` cannot depend on the build_order of the main product graph:

- They are private to ``test_package``. A ``test_package`` could have a ``build_requires`` to ``cmake/3.20`` while the product itself is completely built with Autotools. It is impossible that the ``cmake/3.20`` package will be in the build order at all.
- Even if the main product used the same ``cmake`` build_require for the packages, there is no guarantee that it would be using the same version, all packages could be using ``cmake/3.15`` while the ``test_packages`` could be using ``cmake/3.20``. The build order will never command to build ``cmake/3.20``.

Some workarounds and ideas that I would try:

- This should only happen when modifying the ``cmake`` package itself, hopefully the lockfile with the right versioning and policies allows to build only what is necessary under a change, and ``cmake`` package will not be part of that for most cases. 
- For full rebuilds and cases that ``cmake`` package itself is modified, I would try to directly decouple the processing of build_requires like cmake in my pipeline. Always build them first, so they never become part of the lockfile ``build-order``.

In any case, the problem is very challenging, not only a tool problem, but a definition and flow problem. Making the "test_package" part of the package, something that we have discussed a few times seems could help, but this is not in the roadmap, as it is an extremely challenging feature by itself. We need to think about this issue.

**Comment by KerstinKeller** [comment]
Hi @memsharded,

thanks for the elaborate answer.
It makes a lot of sense, and I kind of figured that it is most likely the case that the `test_packages` are not considered during the locking stage.
And I feared, that conceptually, it might not be possible to resolve the issue at the moment.

> This should only happen when modifying the cmake package itself, hopefully the lockfile with the right versioning and policies allows to build only what is necessary under a change, and cmake package will not be part of that for most cases.

Yes that is the case, and that is why we only noticed last week, when doing bulk changes to a lot of recipes.

So as you proposed, we could always try and build all CMake versions upfront, though it's a somewhat non-generic (but pragmatic) approach to the problem.
Alternatively I could try to always yield CMake first when iterating through the build-order, though technically, it might not be ensured, that they necessarily even show up there. So I guess your approach is to be preferred.

In general, I think it'd certainly have advantages, if the `test_package` where an integral part of the actual package
- Changes in a `test_package` can trigger retesting a package (though probably they also trigger a rebuild of the complete package. -> though that might be circumvented depending on *how* `test_package` is made part of the actual package.)
- Tests can also be executed when doing a `--build missing` and potentially find issues with the package.
But I guess it might have disadvantages, too.

Thanks again, and I will follow this issue to see if / how you will eventually tackle it.

**Comment by memsharded** [comment]
Hi @KerstinKeller 

We have been discussing this during this iteration, and seems we are in the same place:

> And I feared, that conceptually, it might not be possible to resolve the issue at the moment.

Yes, it doesn't seem possible to address this conceptually at the moment. Even with the improvements we are working towards 2.0 seems infeasible

> In general, I think it'd certainly have advantages, if the test_package where an integral part of the actual package

Yes, we agree. We have tried to approach this feature a few times already, and have always failed. We have considered it again, but didn't find a viable path. The challenges are:

- It is not possible to make the ``test_package`` an actual part of the current package structure, as it would modify things like the current revision, when such revision shouldn't change.
- Even if it was made part, the reverse dependency problem would be an issue, because a dependency graph that includes all the ``test_package`` (by navigating packages down to their test_package and then up to the test_package dependencies), would be challenging: lack of unified ``reference`` name of the node of the graph, having graphs with multiple "root" nodes
- There would be scenarios were users really don't want to embed the test_package code inside the package (security concerns, private implementations). Now it should be opt-in, opt-out, and Conan would need to handle both scenarios, being more complex, etc.
- Not making it part of the package structure would require a new server API, new server implementations. That takes a very long time, and would also be breaking. Probably too much at the moment.


So I'd say at the moment I'd recommend a pragmatic solution like:

- Try to inject the ``build_requires`` at the profile level, instead of ``test_package/conanfile.py`` level, that might highly reduce the divergence of versions and the likelihood of wrong orders.
- Try to pre-build somehow in CI those special build-requires when they change, like treat differently the CI of the ``cmake`` package to ensure they are always pre-built.

From our side we are focusing right now on the challenges of 2.0, and one of them is improving over the very well known challenges of CI and lockfiles (even without taking into account the ``test_package``), and we are positive that this can be improved in the 2.0 timeframe, lowering the barrier in this area will leave more room for these pragmatic solutions be not much of a burden, because overall complexity will be way lower.

**Comment by KerstinKeller** [comment]
Thanks @memsharded for keeping me in the loop!
We have already taken measures in the CI build script to always build CMake first.

> Try to inject the build_requires at the profile level, instead of test_package/conanfile.py level, that might highly reduce the divergence of versions and the likelihood of wrong orders.

We have previously made the `cmake` package to be part of the build profile. However, this leads to the chicken - egg problem, where you cannot create the whole graph from scratch, because then cmake has a build requirement of cmake.
Therefore we do not put build-requires in our profiles anymore.

Thanks for addressing again the `test_package` issue. I feel like your concerns of making `test_package` part of the actual Conan package might not actually be a concern to the users:

> It is not possible to make the test_package an actual part of the current package structure, as it would modify things like the current revision, when such revision shouldn't change.

Isn't this an issue only once, or once `test_package` contents change? I would think it's ok, that the package_id changes, if the `test_package` changes. Sure, it doesn't really change the binaries, but there is so many things that already change `package_id` but not the binaries. E.g. if you make a comment in `conanfile.py`, it's already a different package id. So if something changes in test_package, sure it's a new `package_id`. 

> There would be scenarios were users really don't want to embed the test_package code inside the package (security concerns, private implementations). Now it should be opt-in, opt-out, and Conan would need to handle both scenarios, being more complex, etc.

You think that would be an issue? Isn't a test_package testing consumption of the public api of the package, linkage and execution? I cannot think of a usecase where you want to hide that. I certainly would not make it opt-in / opt-out. If there were concerns of disclosing the test_package, it might be users are abusing the purpose of the test_package?

Even, completely disregarding this issue, I think that the benefits of the test_package as part of the conan_package would outweight the drawbacks:
- Not being able to push packages to the server, where the test_package build was unsuccessful (though I am not 100% certain that that's still possible)
- Rerunning tests when they have changed
- Being able to run test in `--build missing` usecases, on platforms that have not been tested

Anyways, just wanted to note these points. Thanks for keeping me up to date and let's see what will happen with Conan 2.0! Will close this issue 😄
