### ISSUE TITLE
Layout source folder when using ``source()`` to ``git clone`` a third-party fails 

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#9532]
- Layout defines source folder as ``src``
- Conan exports at least ``conanfile.py`` and ``conanmanifests.txt`` into the ``export`` folder in the cache
- The ``export`` folder in the cache is automatically copied to ``source/src`` in the cache.
- If the package tries to do a ``git clone <url> src`` to put the sources inside the ``src`` folder as the layout specified, it fails with "folder already exists".

Should we?
- Do not copy the ``export`` into the ``source/src`` folder, only the ``exports_sources``?
- Document some git gymnastics to do it, like cloning in a different folder?

**Comment by lasote** [comment]
I think the "exports" shouldn't go to the `src` because if you have sources you should use `exports_sources` right?
In case you have both `exports_sources` and a `git clone` (not likely but surely used) you probably need some [some trick](https://stackoverflow.com/questions/2411031/how-do-i-clone-into-a-non-empty-directory).


A test to make it fail:

```
def test_git_clone_with_source_layout():
    client = TestClient()
    conanfile = textwrap.dedent("""
           import os
           from conans import ConanFile
           class Pkg(ConanFile):
               exports = "*.txt"
               exports_sources = "*.cpp"

               def layout(self):
                   self.folders.source = "src"

               def source(self):
                   self.run('git clone "{}" src')
       """).format(client.current_folder)

    client.save({"conanfile.py": conanfile, "myfile.txt": "My file is copied",
                 "source.cpp": "sources"})
    with client.chdir(client.current_folder):
        client.run_command("git init .")
        client.run_command('git config user.email "you@example.com"')
        client.run_command('git config user.name "Your Name"')
        client.run_command("git add .")
        client.run_command('git commit -m  "commiting"')

    client.run("create . hello/1.0@")
```

**Comment by lasote** [comment]
I noticed this in the `source.py`:

```
               if cache:
                    _clean_source_folder(src_folder)  # TODO: Why is it needed in cache?
```

The answer to the # TODO is exactly this issue: it is trying to remove the `conanfile.py` and others to skip the errors cloning repositories. BUT as it is cleaning `src_folder` instead of `conanfile.source_folder` it was not cleaning anything. 
So, I still think that the `exports` should go to the base directory but we could fix it if we keep it.
Let's talk about it.
