### ISSUE TITLE
[feature] .conan/data/<pkg> support for multiple build machines

### ISSUE THREAD

**Issue by gdray-dev** [conan-io/conan#9564]
Our software build team asked a reasonable question about the use of Conan.  They have ~20 build machines and over time we would have a significant set of built packages.  Of course these will be pushed up to a Conan repo but the build machines are generic and might be required to use any package for a build.  For simplicity, it would be nice to just leave all the built packages on the machine rather than pulling them and then discarding them after a given build.  This will result in ~20ish copies of a rather large .conan/data folder.

Desire: Allow all machines to point to a common network drive location for .conan/data.  For the most part, this data will be read-only once the packages are built.  But if a package is being newly built, there might be a conflict of two machines trying to build the package at the same time.  It seems reasonable to design build processes to try and avoid this but it would be a good feature to have something like read/write locks that would fail an accidental attempt of two machines trying to write the same package or fail a machine trying to use a package before it is fully built.

Is this possible already?  Either I have missed any documentation on such an option or the documentation is simply quiet on the topic.  Would this be a feature that the Conan team would see having value? While I had not thought about the question, this was literally the first question asked by the build team when we showed them the product.  It seems like a nice "enterprise" level feature.

Does the Conan team see an alternative idea that allows sharing across machines?

Thanks for any feedback.

**Comment by gdray-dev** [comment]
After more search through the documents, I found the CONAN_CACHE_NO_LOCKS environment variable.  I had already seen that the local cache could be redirected as required.  Does the default setting of this variable "FALSE" enforce local cache locking generally as described in my request?  There is a comment of "not for production use".  Would that mean turning OFF locking would not be good for normal use or that the locking scheme is not robust enough to be counted on in a production environment?

**Comment by memsharded** [comment]
Hi @gdray-dev 

Yes, there are some ideas here: https://docs.conan.io/en/latest/mastering/custom_cache.html, but that docs might be a bit outdated and not complete.

The important bits:

- The cache is not concurrent for the general case. It is simply too challenging. To give a reference you might be interested in Java Maven concurrent access story, see https://issues.apache.org/jira/browse/MNG-2802?focusedCommentId=17380459&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17380459. In short, they got some. They have struggled for decades, this was released in Maven 3.8.2 this summer. The Conan cache access patterns are probably one order of magnitude more complex than Maven ones.
- The limited concurrency support use OS-level mechanisms (we use file locks, through the fasteners library, and implement ourselves some primitive ReadersWriters lock, as it is not included in the library). There is no guarantee that sharing a cache among different machines will achieve any degree of locking.
- Even for same CI jobs in the same machine, still using a separate cache for each job is the recommended approach.
- While we will try to improve concurrency support in the cache for 2.0, that will still be limited to same-machine concurrency, as a general distributed locking cache mechanism is unfeasible.
- The locks disabling feature is intended only for removal of the limited concurrency support, in case Conan was running in some machine that doesn't support the OS synchronization primitives or something, but that won't allow any concurrency at all.

While we would really like to have this feature, and we have already put a good effort in approaching this, it is out of the table because in practice it is completely unfeasible. So the proposed solution at the moment is to keep independent caches, and do all package sharing via Artifactory repositories. At some point after 2.0 we will probably consider an attempt to implement read-only secondary caches (they will not be concurrent for writing, user should lock themselves to do that), but I am afraid nothing short term.
