### ISSUE TITLE
[feature] Conan 1.40 (PR-9361) breaking changes

### ISSUE THREAD

**Issue by sboehmann** [conan-io/conan#9587]
Sorry about the sloppy title. ;)

We used to have our own method, but then ported to `apply_conandata_patches()`. This worked fine, but with conan 1.40 _(due https://github.com/conan-io/conan/pull/9361)_ all our recipes are broken.

Sure, - this feature is still experimental, so I had to expect something to break during the update. But this PR also removes the possibility to specify a `base_path`. We use this option intensively and it is very useful. We try to take unmodified patches from upstream. But to apply them you often need to set `base_path` (and/or `strip`).

**Comment by memsharded** [comment]
Hi @sboehmann 

The possibility is encoded now in the ``source`` folder of the new layout. This change had to be done because the feature was broken when using the layouts, due to the duplicated and often incompatible definition.

You should be able to define and make it work with something like:
```python
def layout(self):
        self.folders.source = "mysrc_path"
```

Could you please have a look and see if that works for you?

From what I see in the diff to 1.39, the ``strip`` argument hasn't changed, it is still available in the ``patch()`` function, and it was not available in direct arg in ``apply_conandata_patches()`` in 1.39, the signature of the method hasn't changed here, so the ``strip`` should keep working as it was. If not, please clarify, we could do a patch for next 1.40.1 patch release. Thanks!

**Comment by sboehmann** [comment]
Thank you for your quick reply @memsharded.

#### Regarding `patch()`:
The pull request changes two things. 

One is the base directory _(the `root` argument for `patchset.apply`)_. I assume this will work again for me if I implement `layout()` according to your suggestion. This change makes sense and I am perfectly fine with it.

The second change is that the `base_path` argument has been removed. Only this part is a problem for me. I would have to modify a lot of patches now because I can't specify different `base_path` anymore. But I try to use unmodified patches provided by upstream. For these patches I often have to use a different `base_path`. And if I have multiple patches for the same recipe, it may even differ per patch.

My feature request is therefore to add `base_path` back to the `patch` method _(and if set, join `conanfile.source_folder` and `base_path`)_.

#### Regarding `apply_conandata_patches()`:
Sorry, I misremembered. Contrary to what I wrote above, I don't use this method. I wanted to use it, but had to implement it myself to be able to specify the `strip` argument.

So my second feature request, although not quite as important, would be to restore `base_path` here as well, but also to be able to specify the `strip` options in `conandata.yml`.

**Comment by memsharded** [comment]
Ok, yes, I was a bit confused about the method, if you were talking about the ``patch()`` one, that could make more sense.

Lets ask @lasote for this, he implemented this change, maybe there is another approach, or maybe the ``base_path`` makes sense.

**Comment by lasote** [comment]
Hi, I understand. I will open a PR to use again the `base_path` as relative to the `conanfile.source_folder`. If a layout is specified, it will use it, otherwise, it will use the base source folder as previously.

About the `strip` argument, I would say if specified in the `conandata.yml`, it will pass it to strip automatically like any other argument.

**Comment by memsharded** [comment]
Feature was added in https://github.com/conan-io/conan/pull/9593, will be in next 1.40.1 soon.
