### ISSUE TITLE
[bug] transient linkage with pure cmake_find_package

### ISSUE THREAD

**Issue by blackliner** [conan-io/conan#9600]
As seen in this slack: https://cpplang.slack.com/archives/C41CWV9HA/p1631005375278900

According to [the docs](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html) it is recommended to ` ... not need to specify or include anything related with Conan at all; just rely on the find_package feature ...`. This seems to be not true, as it seems that ` conan_basic_setup()`  is still somehow required to get 100% of conans functionality, especially if multiple, chained shared libraries are involved (I guess the LD_LIBRARY_PATH is missing).

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: gcc7
  * Conan version: 1.40+
  * Python version: 3.6.9

### Steps to reproduce (Include if Applicable)
clone https://github.com/blackliner/conan_transient_linkage
run build.sh

@ericLemanissier 's PR fixes it, while loosing CMake purity: https://github.com/blackliner/conan_transient_linkage/pull/1

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
...
[ 75%] Building CXX object tests/CMakeFiles/lib_a_test.dir/lib_a_test.cpp.o
[100%] Linking CXX executable lib_a_test
/usr/bin/ld: warning: liblib_c.so, needed by //home/fberchtold/.conan/data/lib_b/1.0.0/_/_/package/436fa0a6d3ec3ce29639456d6db8d06cd9bf62c9/lib/liblib_b.so, not found (try using -rpath or -rpath-link)
//home/fberchtold/.conan/data/lib_b/1.0.0/_/_/package/436fa0a6d3ec3ce29639456d6db8d06cd9bf62c9/lib/liblib_b.so: undefined reference to `lum::lib_c::SayHello[abi:cxx11]()'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/lib_a_test.dir/build.make:98: recipe for target 'tests/lib_a_test' failed
make[2]: *** [tests/lib_a_test] Error 1
CMakeFiles/Makefile2:881: recipe for target 'tests/CMakeFiles/lib_a_test.dir/all' failed
make[1]: *** [tests/CMakeFiles/lib_a_test.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
lib_a/1.0.0: 
lib_a/1.0.0: ERROR: Package '4c3f20be28cf1be70e428d9fc0e689236ff00f59' build failed
lib_a/1.0.0: WARN: Build folder /home/fberchtold/.conan/data/lib_a/1.0.0/_/_/build/4c3f20be28cf1be70e428d9fc0e689236ff00f59
ERROR: lib_a/1.0.0: Error in build() method, line 52
        cmake.build()
        ConanException: Error 2 while executing cmake --build '/home/fberchtold/.conan/data/lib_a/1.0.0/_/_/build/4c3f20be28cf1be70e428d9fc0e689236ff00f59' '--' '-j24'
```

**Comment by memsharded** [comment]
This is already achieved 100% with the new toolchains (you can have a peek at this blog post draft: https://github.com/conan-io/conan-io.github.io/pull/199):

- CMakeToolchain
- CMakeDeps
- CMake (``from conan.tools.cmake import CMake``)

We have already changed the creating packages Getting Started to use this: https://docs.conan.io/en/latest/creating_packages/getting_started.html, and usage in ConanCenter will start soon.

I think this issue is solved as in 1.40, if any, there are many improvements we need to do to the docs to update to this.

**Comment by blackliner** [comment]
I don't know if I can/want to jump onto CMakeDeps already. Its a production usecase, would you recommend it?

What would be the workaround for now, add a CMake wrapper that calls `conan_basic_setup()`?

**Comment by memsharded** [comment]
> What would be the workaround for now, add a CMake wrapper that calls conan_basic_setup()?

Yes, if not using the new integration, there are basically 2 options:
- Make sure yourself your build, CMakeLists.txt matches the Conan settings and options (parameterizing CMake call, your own toolchain... there are several options)
- Use the ``cmake`` integration with ``conan_basic_setup()`` to inject those with less effort.

**Comment by blackliner** [comment]
Thanks, atm its unclear to me what exactly is missing though... as seen in the slack thread, those seem to be the cmake arguments handed in by conan:
```
cmake -G "Unix Makefiles" 
-DCMAKE_BUILD_TYPE="Debug" 
-DCONAN_IN_LOCAL_CACHE="OFF" 
-DCONAN_COMPILER="gcc" 
-DCONAN_COMPILER_VERSION="7" 
-DCONAN_CXX_FLAGS="-m64" 
-DCONAN_SHARED_LINKER_FLAGS="-m64" 
-DCONAN_C_FLAGS="-m64" 
-DCONAN_LIBCXX="libstdc++11" 
-DBUILD_SHARED_LIBS="OFF" 
-DCMAKE_INSTALL_PREFIX="/home/fberchtold/LumPDK/packages/lum_swc_pcap_player/build/package" 
-DCMAKE_INSTALL_BINDIR="bin" 
-DCMAKE_INSTALL_SBINDIR="bin" 
-DCMAKE_INSTALL_LIBEXECDIR="bin" 
-DCMAKE_INSTALL_LIBDIR="lib" 
-DCMAKE_INSTALL_INCLUDEDIR="include" 
-DCMAKE_INSTALL_OLDINCLUDEDIR="include" 
-DCMAKE_INSTALL_DATAROOTDIR="share" 
-DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" 
-DCMAKE_MODULE_PATH="/home/fberchtold/LumPDK/packages/lum_swc_pcap_player/build" 
-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" 
-DCONAN_EXPORTED="1" 
-DBUILD_TESTING="True" -Wno-dev '/home/fberchtold/LumPDK/packages/lum_swc_pcap_player'
```
Anything obvious that could be the reason for the transient linkage to fail? I always expected that the autogenerated find-modules will take care of that 🤔

**Comment by memsharded** [comment]
I would probably bet on the c++11 abi, and ``-DCONAN_LIBCXX="libstdc++11" `` (just a guess, but I would start there)
Second thing I'd try is ``"-m64" `` flag (both in compiler and linker).

Those two fix most of binary compatibility issues

>  I always expected that the autogenerated find-modules will take care of tha

Auto generated modules take care of the dependencies themselves. If a dependency is a header-only, it cannot tell you that you should be using some architecture, because itself would be architecture independent. The information for this flags doesn't come from dependencies, but from the current settings. The fact that the settings are used to install dependencies binaries doesn't imply that the dependencies should always define the compile flags of the consumers. This is the reason why the new approach clearly separate in "Deps" and "Toolchain" helpers.

**Comment by blackliner** [comment]
Arch and ABI are not the issue at hand though. See the error log in the OP, shared objects of transient deps cannot be found during linking.

**Comment by memsharded** [comment]
> See the error log in the OP, shared objects of transient deps cannot be found during linking.

There are linkers that will skip a library if it doesn't match its expected architecture, looking like it didn't found a library that is there, you can find in the filesystem, but it keeps telling you library not found. I have verified this a couple of times, cannot be sure if it is the current issue, but worth at least considering.

**Comment by blackliner** [comment]
Nice, thanks, I think thats it for today :-)
