### ISSUE TITLE
Source generation depending on another package

### ISSUE THREAD

**Issue by dkgs** [conan-io/conan#961]
I'm actually using conan 0.18.1 but looking at the changelog my problem is not resolved.

I have two conans package, one containing a configuration file that could be required by multiple other packages and another which requires the first package with the configuration file.

To get the configuration file from the first package, I use the `imports()` method associated with the helper command `self.copy()`. This way, I'm able to get the configuration file from the first package.
But my problem is that the second package has its sources depending on this configuration file, they are generated. The `imports()` is called after the `source()` therefore I can't get the configuration file to generate my sources in the right section. I can generate my sources in the `build()` but then they will not be present in the package, hence my test_package method fail and further dependencies will be broken too.
I also tried to call `self.copy()` directly in the source method, but that was a fail (`'NoneType' object is not callable`).

Is it possible to accomplish what I'm trying ?
My guess to do it (only if it is wise from a general point of view)  : either call the `imports()` method before the `source()` method or enable the `self.copy` in the `source()` method.

**Comment by dkgs** [comment]
To be more concrete : 

First package conanfile.py : 
```
from conan import ConanFile

class ConfigPackage(ConanFile):
    name = "ConfigPackage"
    version = "1.0.0"
    settings = None
    exports = "config.xml"

    def package(self):
        self.copy("config.xml", dest="", src="")
```

The second package conanfile.py : 
```
from conan import ConanFile

class GeneratedSourcePackage(ConanFile):
    name = "GeneratedSourcePackage"
    version = "1.0.0"
    settings = None
    requires = "ConfigPackage/1.0.0@user/channel"
    exports = "include/*"
    
    def imports(self):
        self.copy("config.xml", dest="", src="") #if imported here, not available in source()
    
    def  source(self):
        # unable to call self.copy here and imports() not yet called
        #self.copy("config.xml", dest="", src="") #if imported here, not available in source()
        self.run("some_generation -with config.xml")
    
    def build(self):
        #if generation here, header won't be present in the package afterward
        #self.run("some_generation -with config.xml")
    
    def package(self):
        # package generated source code
        self.copy("*.h", dst="include", src="include")
```

**Comment by memsharded** [comment]
Let's see if I understood it:

- There could be a different approach, is not importing the ``config.xml`` file, but use it from its original location. You can access the path of your dependencies with ``self.deps_cpp_info["ConfigPackage"].rootpath``. I think this should work both in the ``source()`` and ``build()`` methods, just using such path to the ``run("gen -with %s/config.xml" % dep_path)``

- I don't fully understand why running the code generation would fail in the ``build()``  method. It is a common practice, when generated source code is specific to the current configuration. ``source()`` is only for generated code and code in general that is shared for all generated packages. I think maybe could be an issue with your paths, no in the ``src="include"`` one.

- The ``imports()`` before the ``source()`` method doesn't make much sense in the general case, as the ``source()`` method should be general enough not to depend on specific dependencies binaries. In your case you have only 1 ``config.xml``, because ``settings=None`` but if you had  a ``ConfigPackage`` with different ``config.xml`` for each configuration of settings/options, that would fail.

So, as a summary. I think that the ``imports`` + code generation in ``build()`` should work without problems. Also the "getting the path for ``ConfigPackage`` + code generation in ``build()``. In both cases the issue could be in the paths used by the code_generation, and why wouldn't those sources be packaged. Please tell me a bit more about it. Thanks very much for your feedback, and your detailed example, really helpful!

**Comment by dkgs** [comment]
Works like a charm !

I'm using your proposition by accessing the depency with `self.deps_cpp_info["ConfigPackage"].rootpath`.

The code generation doesn't fail in the `build()` method, its just that I need this code to be included in the package so I have to generate it in the `source()` method so it will be available for other dependencies.

Finally, I'm using your first point : get the path for the ConfigPackage + code generation in source() method.

Thanks for showing the way :)

**Comment by memsharded** [comment]
Still not sure about what you mean. The source code evolves as follows:

- "export" copies code from user spaces to the conan local cache
- code is copied from the "export" cache folder to the "source" cache folder
- ``source()`` is called
- code is copied from the "source" folder to the "build/<ID>" folder where ID is the package binary hash folder
- ``build()`` method is called
- ``package()`` copies from the "build/<ID>" folder to the "package/<ID>" folder, using the ``self.copy`` patterns

Code generated either in the ``source()`` method or in the ``build()`` method will end in the "package" folder if correctly managed by the ``package()`` method. Am I missing something?

In any case, very glad that I could help :)

**Comment by dkgs** [comment]
Aw ok, I missed the fact that the source are copied to the build folder. There wasn't any problem, just me that generate code at the wrong place ^^.

Thanks for the clarification :)
