### ISSUE TITLE
[question] workaround Azure upload size limit?

### ISSUE THREAD

**Issue by jsteinhofff** [conan-io/conan#9729]
Hi everyone,

we have some conan packages which are of massive size (6 GB) which now leads to problems when we try to upload those to Artifactory hosted in Azure. It seems that Azure has a size limitation of uploads of 4 GB as is also documented in
https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/application-gateway-limits.md (5th last row)

We are looking already how to split our package to stay clear of this limit, but still i wonder if it wouldn't make sense for conan to handle such issue transparently by splitting conan_package.tgz into multiple files (< 4GB) during upload, and assembling it back locally when downloading.

Would such a feature request (/contribution?) make sense also for others? Would it have a chance to get merged?

**Comment by memsharded** [comment]
Hi @jsteinhofff 

It seems this functionality would be very challenging to implement. First, because that involves changes server side, and with the growing ecosystem of server implementations, it can take a very long time and be painful. Changing only conan_server and Artifactory to implement this would take many many months (if approved, which seems difficult). The feature must be negotiated with the server too, as not all servers would immediately understand it.

So unfortunately, this seems very unlikely. I would suggest pushing Azure to increase that limit, or trying to reduce the package size by splitting or optimizing such a big package, as you already pointed out.

**Comment by memsharded** [comment]
Closing as not planned
