### ISSUE TITLE
"ERROR: Conanfile not found!" prints to stdout, not stderr

### ISSUE THREAD

**Issue by seanbollin** [conan-io/conan#973]
I ran into this while developing a conan module for Ansible.  The error was printed to stderr, not stdout.  Has this been examined?

**Comment by seanbollin** [comment]
can verify with: conan install 1> /dev/null

**Comment by memsharded** [comment]
> The error was printed to stderr, not stdout.

I guess that you meant the opposite.

Yes, that is true. Actually, all output is printed in the same stream. 
The issue is that the stream might not be always stdout, but also files, output is pipelined from processes to be logged, displayed in colors, scoped with the package reference prefix, etc. and it was complicated to split in both stderr/stdout, and keep information in sync (typically, when an error, you want to read the previous events), without cluttering the user output with time info. Also, there were some doubts, about where to direct the warnings.

The process should return error, which could be checked. And then all errors should be clearly labeled as ``ERROR:``. In any case, the process running conan should parse the stderr output to get individual errors. I think that using the return code and parsing stdout instead of stderr should be enough for processes running conan to know about errors. I know it is not the perfect solution, but should be good enough, and it helps keeping the conan codebase as simple as possible.
