### ISSUE TITLE
conan server write_permissions

### ISSUE THREAD

**Issue by olcto** [conan-io/conan#977]
I cannot seem to figure out why one configuration file works and the other does not work. I am trying to  create multiple users that have access to write to all projects onto our conan server instance.

Upgraded to latest 0.19.1

The following server.conf only user jmohlenhoff works:
```
[write_permissions]
*/*@*/*: jritchey
*/*@*/*: jmohlenhoff
```

~~The following both work:~~ The following only user jritchey works:
```
[write_permissions]
*/*@*/*: jmohlenhoff
*/*@*/*: jritchey
```

~~It almost seems to have to do with spelling.~~
Any help would be appreciated.

**Comment by memsharded** [comment]
I think you cannot have the same rule applied twice to different users, try with a comma separated list (no spaces):

```
*/*@*/*: jmohlenhoff,jritchey
```

**Comment by memsharded** [comment]
Actually, I'd say the example in the http://docs.conan.io/en/latest/server.html, might not work, so either the docs have to be changed, or even better, an improved parsing (and most likely a unit test) is required.

**Comment by olcto** [comment]
The one line no spaces worked!

I would say update the documentation to match the parsing requirements for now. I was following the default server.conf comments.

https://github.com/conan-io/conan/blob/develop/conans/server/conf/default_server_conf.py#L36

**Comment by memsharded** [comment]
Great!

Ok, so fixed in the docs: https://github.com/conan-io/docs/commit/ff27eb11ffa6ebfd6f4cdf8c4c65e940103930ec

And live: http://docs.conan.io/en/latest/server.html

I will close the issue, unless someone is specially interested in supporting lists including spaces, I think this does not deserve a great effort. 

Thanks for noticing this and giving feedback!
