### ISSUE TITLE
[feature] Add support for CycloneDX output to the `info` command

### ISSUE THREAD

**Issue by coderpatros** [conan-io/conan#9787]
Hi, full disclosure, I work on the OWASP CycloneDX software bill of materials project https://cyclonedx.org/. 

A software bill of materials, in a very basic sense, is a list of all the components that make up a piece of assembled software.

The current output of the `info` command provides this information.

But that output format is specific to the Conan ecosystem. CycloneDX is an ecosystem agnostic format.

Having this information in a standard format helps with a number of use cases. Identifying components with known vulnerabilities, OSS license compliance, and supply chain component analysis, as examples. Especially in organisations that are building software in multiple ecosystems.

I had been planning to implement a specific tool to do this. But after digging into it, I think it might be better to add it as an additional output format for the `info` command. Perhaps a `--cyclonedx-json` option?

If this is something you'd accept a PR for let me know and I'll start working on the implementation and tests.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @coderpatros 

This looks interesting, and we are willing to accept contributions for this. But right now we are moving fast from 1.X => 2.0, it won't make sense to duplicate the effort, all the interfaces, APIs, etc are being re-designed.

Lets follow up when the Conan 2.0 python api is at least there (will be in a few months, while beta stage), to implement this. Thanks for offering to contribute it!

**Comment by coderpatros** [comment]
Thanks @memsharded, sounds good to me.

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/14405 is proposing support for this

**Comment by czoido** [comment]
Hi @coderpatros,

Since Conan 2.12 we have new `conan.tools.sbom.cyclonedx` tools to manage this. Please check the docs: https://docs.conan.io/2/reference/tools/sbom.html

I think it's also relevant to mention here that starting in **Conan 2.14**, we introduced a new command: `conan audit`. It’s a built-in way to **scan your dependencies for known CVEs**.

You can read more in our [blog post](https://blog.conan.io/introducing-conan-audit-command/), but in short:

1. **Register** at [audit.conan.io/register](https://audit.conan.io/register)  
2. **Save your token** and **activate it** via the confirmation email you receive.  
3. **Configure Conan to use your token**:  

   ```bash
   conan audit provider auth conancenter --token=<token>
   ```

4. Run a scan:

   ```bash
   # Check a specific reference
   conan audit list zlib/1.2.13
   
   # Scan the entire dependency graph
   conan audit scan .  # Path to the conanfile.py/txt
   ```

Let us know if you try it, we’d love your feedback!
