### ISSUE TITLE
[question] Distinguish binaries between implementations used for the libc library?

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan#9794]
Should there be a setting to distinguish between various libc implementations such as glibc and musl on Linux?
This is similar to using a different implementation of the C++ standard library like `libc++` instead of `libstdc++`.
I've been opening issues related to the CMakeToolchain generator, but since musl is mostly used through a GCC compiler wrapper or using GCC on Linux distributions / toolchains that use musl, I'm not sure anything is required for configuration in the CMakeToolchain generator.
Perhaps `musl-gcc` would need to be an additional compiler?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by franramirez688** [comment]
Thanks for reporting it @jwillikers 

This issue is quite related to this one https://github.com/conan-io/conan/issues/9608

We have to have a look into both issues indeed.

As a workaround If you're stuck with this problem, you can add manually a `subsetting` into your `settings.yml`like this one:

```
    gcc: &gcc
        .....
        libc_version: [None, ANY]
```

Then, you'll be able to use it in your own `profile` putting something like:

```
compiler=gcc
...
compiler.libc_version=musl-1.2
```

Check [this comment](https://github.com/conan-io/conan/issues/9608#issuecomment-920088512) to know more about the custom settings.
