### ISSUE TITLE
[question] except build_req from consumer conanfile

### ISSUE THREAD

**Issue by reymondzzzz** [conan-io/conan#9829]
- & means apply these build requirements to the consumer conanfile
- &! means apply the build requirements to all packages except the consumer one.

Have conan option for excepting build_reqs from consumer conanfile and not applying for all reqs?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Hi @reymondzzzz 

Not sure what you mean with ``Have conan option for excepting build_reqs from consumer conanfile and not applying for all reqs?`` This is what the ``&`` will do, isn't it?

**Comment by reymondzzzz** [comment]
Nope. I tried `&` and packages(like msys) was be installed. It very difficult to use with vc compilers. When use activate_run.bat my path has cl and gcc. Cmake uses gcc. If I try `&!`, my PATH is good, but msys applies for all build_req, it is not what I wanted.

**Comment by memsharded** [comment]
Well, if you are working at the consumer level, you shouldn't be building the dependencies from that terminal with the environment activated, because no matter what the dependencies define, they will be running inside an MSYS environment, and there is no way that can be escaped. You should be building only your consumer project.

Another possibility, have you tried defining ``build_requires = "msys...."`` directly in the consumer ``conanfile.py``?
