### ISSUE TITLE
Uploading package that is built outside of the tree - to artifactory

### ISSUE THREAD

**Issue by kobi-ca** [conan-io/conan#9836]
General question. 
I'm looking at libfuse. I just realized that you can actually create a conan package "out of band".
In other words, the libfuse repo itself has no knowledge about conan. It does not have a conanfile.py.

Someone added libfuse to the conan-center-index. Added the YAMLs and the conanfile.py and created a package.

If I want to do something similar, is this going to behave like a regular package that has conanfile.py as part of its tree?
i.e. after I build it (similar to what libfuse in coann-center-index) I can just `conan upload` it?

So the bottom line as I see it, is that we can always leave a repo as is, without adding any conan related code to it, and "out of band" create a package (using the already created binaries from the original repo) and upload to artifactory.

Is the above understanding correct?

**Comment by memsharded** [comment]
Yes, there are 2 possible conanfile locations:

- You can put the conanfile.py inside your source repo. Typical flow for ``git clone`` and more focused on the developer flow, specially if the source repo already have some dependencies that are managed with Conan. In this case it is clearly the most recommended flow, because otherwise working in the repo would be more painful.
- You can put a conanfile.py in a separate repo. Typical flow is putting a few conanfile.py in the same repo to package a bunch of third party dependencies. This is the conan-center-index approach, and works best when it is only necessary to package those, but not working on the source code of such dependencies, just packaging

In any case, once you run the ``conan create`` for both scenarios, you create a Conan package in your local cache. ``conan upload`` flow is exclusively between the Conan cache and the server, the package origin source, location or layout is irrelevant at this point.
