### ISSUE TITLE
Feature: conan server statistics

### ISSUE THREAD

**Issue by CodingSpiderFox** [conan-io/conan#986]
I am interested in how much usage of resources is caused by my conan server. 

To easily and/or automatically have this information available, a command like "conan statistics -r <remote_name>" would be great.

Following values would be interesting:

* Uptime
* Disk space consumption
* Network IO (max bandwidth, data transfer in GB per hour / per day for both packages uploaded to conan and packages downloaded from conan server)
* Biggest n packages (where n is an integer) : names + size of each of them
* further values might be interesting in the future

**Comment by CodingSpiderFox** [comment]
This might especially interesting for people who want to host their conan server in an environment where the have to pay for the amount of data transferred over the network of their provider.

**Comment by CodingSpiderFox** [comment]
Can you please give me some feedback on whether this is a valid feature for conan-server?

**Comment by memsharded** [comment]
Yes, this is a valid feature, it simply didn't get the priority.
Please, note also that this is not a trivial issue. Doing statistics on demand is not feasible. Doing statistics on the background, requires deploying a task manager (e.g. celery or cron), and quite a bit of extra complexity. Maybe it also makes to address jointly to conan.io, but this is something we will have a look in a few months. Right now, stabilizing the client side and the core functionalities has higher priority.

**Comment by CodingSpiderFox** [comment]
Ok thanks!

**Comment by CodingSpiderFox** [comment]
Any updates on this one?

**Comment by lasote** [comment]
Even more busy than ever... sorry. We are working like crazy stabilizing the client to release the 1.0. For us, the priority is the client, where is the real value of the tool. Also, the professional use of Conan is well covered by Artifactory and Bintray. It doesn't mean that this issue is not valid, would be great, but it's not a priority for us, and currently we are at 250% of capacity. 😢

**Comment by lasote** [comment]
Now we have the Artifactory community edition for C/C++ totally free. It doesn't come with the features you are mentioning but certainly much better than the conan-server. We are keeping the conan server as the open source MIT reference implementation of the conan server protocol, but this kind of enterprise features not related with the package manager itself is not getting priority (as we told you we have very limited capacity). 

I've found some interesting info about the features you are requesting: https://www.jfrog.com/confluence/display/RTF/Log+Analytics

I'm closing this issue because honestly, we are not going to be able to do it. 
Thanks for your interest!
