### ISSUE TITLE
Locating installed package from command line 

### ISSUE THREAD

**Issue by kolis** [conan-io/conan#991]
It would be convenient to be able to locate the path to an installed package from the command line

eg something like

```
$ conan path my-package/0.5.0@kolis/stable
```
could give output
```
/Users/kolis/.conan/data/my-package/0.5.0/kolis/stable/package/ed52a5841768e616e14f89e1f52ae18ee5d1456a
```

**Comment by memsharded** [comment]
Such path doesn't exist. You get a different path for every posible binary you have for that package. You would need to add all the arguments you have to provide to the install command. If anything it could make sense as a ``conan info`` item.

What would be the problem you are trying to solve, what do you need that information for? Please note that you also have the path in the conan model, so you can access if from your conan recipes (even for project, using a conanfile.py instead of a conanfile.txt) very easily.

**Comment by kolis** [comment]
Ok, I was considering using conan for distributing a command line tool to a docker image I am maintaining.

But I see conan is probably not the right tool for this type of setup, this is not really a dev-environment, it is a runtime environment where I run the installed binaries. So I should probably be using some .deb package or similar instead.

**Comment by memsharded** [comment]
yes, you are right, conan is for developers, totally dev-oriented. It will probably include features to help create different deploys in the future, but this is not in the roadmap yet.
