### ISSUE TITLE
<URGENT> Issue with Conan -- Unable to build or publish

### ISSUE THREAD

**Issue by ganzyfrenzy** [conan-io/conan#9923]
Hello, My name is Rajguru from Germany. 
I have severe issues with conan that, it cannot build or publish. It shows 'building environment.. locked by another concurrent conan process, wait....
NOTE : I performed 'conan remove --locks' command, still issue exist. 

Can you please support me in resolving this at the earliest ?

**Comment by memsharded** [comment]
Hi @ganzyfrenzy 

If the ``conan remove --locks`` is showing any error output, I would like to see it.

Otherwise, these are the next things I would try:
- Remove all the  *.lock files and ``locks`` folders inside your cache (typically in ``userhome/.conan`` or where CONAN_USER_HOME is pointing to), and try again
- Completely clean your cache. Remove the ``userhome/.conan`` folder completely, and let the next commands to repopulate it from the servers. Recall that the cache is just that, a cache. Packages should be uploaded to servers like Artifactory, and every change in the configuration in the cache should be in a separate repo and managed via ``conan config install``

Please try that and let us know.

**Comment by memsharded** [comment]
Closing as staled.
