### ISSUE TITLE
[bug] self.copy has different behavior if called in subdirectory

### ISSUE THREAD

**Issue by Fettpet** [conan-io/conan#9947]
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 16
  * Conan version: 1.41.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
I have create a little example to demonstate. The conanLib has a header file with a single function inside. The conanfile.py build the library. I included two conanfile.py. The first one is on the root level. The second one is inside the subdirectory conan. 
I included two bash scripts to build both packages.

My expactation is that both conan recipts build the same package, since the only things which are changed are the location of the conanfile.py and the relative path of exports_sources. 

The output of the packages does differ (for me C:\Users\fettpet\.conan\data\MyLib\1.0\fettpet\testing\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9):
1. The root case: the add.h is inside the include directory. This is unexpected since the documentation of [copy](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package) says it should be inside the root directory
2. The subdirectory case: the add.h is inside the root directory. This is expected.

The issue was also disscussed [here](https://github.com/conan-io/docs/issues/2287)
[conan_min.zip](https://github.com/conan-io/conan/files/7474659/conan_min.zip)

**Comment by memsharded** [comment]
Hi @Fettpet 

This is expected to happen, because of an impossible to solve indetermination issue in the definition of ``exports_sources``.
If you want to have your recipe not in the root folder, and you have this issue, then you should use the ``export_sources()`` method alternative, which has better definition of locations. Please have a look at: https://docs.conan.io/en/latest/reference/conanfile/methods.html#export-sources

**Comment by Fettpet** [comment]
@memsharded Thanks for clarification.
