### ISSUE TITLE
Add support of long paths (more then 260 chars) on Windows (not using "short_paths=True")

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#997]
At the moment `conan` does not support projects with file paths more then 260 chars long on Windows.
Even if I am using `short_paths = True` some paths are still too long.
Meanwhile python does support long paths. Paths should be absolute and should have prefix `\\?\`.

Simple test that shows ability to create a path 260+ chars long:
```python
import os

p = os.path.abspath("abcdefghijklmnop0123456789/" * 10);
print("path: %s" % p)
print("len: %s" % len(p))

try:
    print("makedirs(path)")
    os.makedirs(p)
    print("  - ok")
except:
    print("  - failed")

try:
    print(r"makedirs(\\?\path)")
    os.makedirs(r"\\?\%s" % p)
    print("  - ok")
except:
    print("  - failed")
```

**Comment by memsharded** [comment]
The issue is that not all APIs support this. I think it might depend on the python version and the OS version, and also other functionalities (copying, removing, opening files...), so up to my knowledge the ``\\?\`` prefix is a limited and still not enough general solution.

If you still have the problem, and you can work with Python 3.6 in Windows10, you might be able to enable the long-paths API (it is an option at install time), and you could probably don't need the short_paths feature at all.

**Comment by DmitrySokolov** [comment]
* [Windows: support path longer than 260 bytes using "\\\\?\\" prefix](https://bugs.python.org/issue18199).
It looks like the long paths issue concerns a lot of Python modules and requires significant efforts to fix it. Since Window 10 supports long path without extra processing, the issue will not be fixed.
* [Opt-out of MAX_PATH on Windows 10](https://bugs.python.org/issue27731).
Solution.

It works on Windows 10 (ver. 10.0.14393) regardless of Python version (at least for 2.7, 3.5, 3.6) but requires modification of Windows Registry.

**Comment by memsharded** [comment]
Great Dmitry, thanks for telling.

I have added some details to the docs: http://conanio.readthedocs.io/en/latest/reference/conanfile.html#short-paths
