### ISSUE TITLE
[feature] Using short paths under Linux

### ISSUE THREAD

**Issue by d0nc1h0t** [conan-io/conan#9979]
The project uses a Node.js based package as shared library. After upgrading to version 16.13, the build stopped working due to the length of the paths.
`make: execvp: /bin/sh: Argument list too long`
The problem is in the size and number of parameters when calling make, which is not solved by changing the system limits. It looks like there is a kernel static buffer overflow (MAX_ARG_STRLEN). 
In fact, the base Node.js project has a build folder path length limitation. Using short paths would solve the problem, but it's only implemented for Windows.

**Comment by memsharded** [comment]
Hi @d0nc1h0t 

This will not be possible in Conan 1.X, because it would be too complicated and risky. Conan 2.0 has already changed to using a different cache layout, which paths will be always "short", so this can be closed as implemented, and to be released in 2.0 (keep tuned for the releases, we are starting the alpha stage now)
