### ISSUE TITLE
[feature] Upload lockfiles together with binary packages to artifactory (and possibility to retrieve them)

### ISSUE THREAD

**Issue by jsteinhofff** [conan-io/conan#9999]
**Background:**
To take SW components which are built and integrated with conan to the next level of process conformance we are thinking about using conan depdendency information to generate [SBOM](https://en.wikipedia.org/wiki/Software_bill_of_materials) but also to connect live cycle management related tools like vulnerability tracking, open source license management etc.

I believe the best starting point to feed such higher level live cycle management processes are conan lockfiles since they can fully describe the (conan based) input to the build process which produced the binary artefacts.

**Question:**
Is there a best practice about where to save lockfiles for later processing?

Starting with this question i did a comparison of the approaches which came to my mind (see picture in first comment) and came to the conclusion that it would be best if conan would have native support for persistence of lockfiles together with each binary package.

The benefit of this approach is, that those lockfiles would be implicitly be traceable to the binary package so no other mechanisms/book keeping would be required.

**Feature**
* Conan would need to provide a command to upload a lockfile for a binary package (or together with the upload right away)
* Conan would need to provide a command to fetch the lockfile for a binary package (or do it always if there is one uploaded) and place it in the cache. Additionally it would be helpful if conan could help me to get the path to that lockfile or "install" it in my current directory, so i dont have to fumble around in conan cache

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jsteinhofff** [comment]
Hi, since sofar there was no feedback here i tried to understand better the different approaches by myself. For me there is a clear favorite (#3 in the picture below) which is why i change the tag in the title of this ticket from [question] to [feature] .

![screenshot-conan-lockfile-persistence-approaches](https://user-images.githubusercontent.com/70687692/143453547-86913a6d-152f-45ed-b28f-69f2d8b598a5.png)

**Comment by ghost** [comment]
I would like to bump this topic and see if we can get a statement from the conan devs. 

I have checked [CI/CD in C/C++ Projects with Conan and Artifactory](https://github.com/conan-io/training-ci) and the way it is described there is to set up an extra conan-metadata repository and store the lockfiles there, so its basically the approach 2 as OP described. As the slides are from the main Conan devs themselves I would regard this approach as the de-facto standard way of solving this issue. 

Are there any plans for this issue for Conan 2.0 or will approach 2 remain standard?

**Comment by memsharded** [comment]
Hi all,

We are investigating the possibilities of exporting lockfiles together with the recipe in https://github.com/conan-io/conan/pull/10261. Very preliminary, a lot of work to do, but it could be that Conan 2.0 simplified lockfiles could allow this.

Otherwise, it is likely that putting the lockfiles in a git repo (a different one than the source, otherwise adding lockfiles keep modifying revisions), is more convenient for developers in general.

**Comment by ghost** [comment]
Thanks for the heads-up and the quick reply! As always you guys are doing a magnificent job!

**Comment by memsharded** [comment]
I'd like to add to this thread that now in Conan 2.0 there is file metadata, integrated in packages. It is possible to add extra files there, including lockfiles if desired. 

Furthemore, I'd say that https://github.com/conan-io/conan/pull/10261 is the place to track this, as it seems aligned with the number3 proposal.

This also referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, because also now 1 single lockfile for all configuration will work, which will highly simplify the problem above, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!
